### ISSUE TITLE
Extend component knobs into another component

### ISSUE THREAD

**Issue by RyanHavoc** [storybookjs/storybook#10004]
**Is your feature request related to a problem? Please describe.**
I want to know if it's possible to extend the knobs from one component into another component. For example I have a `BaseAnchor` component with knobs setup. I also have a `BaseAnchorIcon` component which has all the same props a `BaseAnchor` plus an additional `icon` prop.

**Describe the solution you'd like**
I'd like to be able to import the knobs from `BaseAnchor` and spread them into `BaseAnchorIcon` so they can be maintained in one story file. As we modify `BaseAnchor` to support more variant styles, for example, we don't need to update `BaseAnchorIcon` as well.

**Describe alternatives you've considered**
I've tried doing this, but it appears that once a knob is registered it can't be overridden. I've also tried giving each component knobs a group id and I can get the knobs to `BaseAnchor` to show, but if I change a knob Storybook refreshes and the knobs disappear from the component example...

![Mar-01-2020 11-50-43](https://user-images.githubusercontent.com/824169/75625130-f7ec8280-5bb2-11ea-9081-ec220ad35bda.gif)

**Are you able to assist bring the feature to reality?**
Possibly...

**Additional context**
We build upon base components a lot so being able to extend them in knobs would same us a lot of maintenance.

**Comment by quagliero** [comment]
>  I've also tried giving each component knobs a group id and I can get the knobs to BaseAnchor to show, but if I change a knob Storybook refreshes and the knobs disappear from the component example...

Just want to add we're currently struggling with this issue. We have a lot of 'Core' knobs that apply to a wrapping component that each story uses, and when you toggle one of the knobs, the entire 'Core' pane disappears.
