### ISSUE TITLE
Clearing global decorators / parameters does not work properly on HMR

### ISSUE THREAD

**Issue by tmeasday** [storybookjs/storybook#10005]
**Describe the bug**
There are few problems with the way global parameters&decorators work, some more problematic than others:

1. When you HMR and change global parameters (or decorators) we do not reload all stories so they don't actually change for the loaded stories.

2. We never clear global parameters so they accumulate over HMR.

3. We do clear global decorators (when reloading a `preview.js` file) which means that any decorators added by addons will get lost when you change `preview.js`

**Comment by shilman** [comment]
- [ ] distinguish between user-added global decorators/parameters from preset-added, clear the former not the latter. can use a different function in the generated entry?

**Comment by tmeasday** [comment]
Currently you get this warning on edit of `preview.js`:

```
Ignored an update to unaccepted module ./.storybook/preview.js -> ./.storybook/preview.js-generated-config-entry.js -> 0
```

Which causes a full reload of the iframe (rather than HMR).

Ideally we should fix that, probably by adding this to `lib/core/src/server/preview/virtualModuleEntry.template.js`:
```js
module.hot.accept();
```

However, it isn't a bad situation as it resolves all the issues above. So I am not going to fix it right now.

---

Here is a plan to fix this issue that I was going to do until I realised this:

1. Deprecate `addDecorator` / `addParameters`. Users can *only* use `export const decorators` / `export const parameters` in `preview.js`. Addons similarly should use the above.

2. Change `StoryStore` to have `_globalMetadata` and `_userGlobalMetadata`. Exports from `preview.js` should add to `_userGlobalMetadata` destructively, whereas exports from presets/addons should add to `_globalMetadata`, constructively. The idea is that as you can only do the former once, it should overwrite previous values, and as you cannot change the later, it can be additive.

3. When the `_userGlobalMetadata` is changed, we should re-decorate all stories. This is the bit I am most unsure about, but probably it will be OK (it just might have some implications.

**Comment by shilman** [comment]
¡Ay Caramba!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-beta.42 containing PR #11417 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
TODO @tmeasday 
- [ ] remove `module.hot.accept` from configure call
- [ ] deprecate preview.js configure call
- [ ] remove semi-functional HMR code

**Comment by shilman** [comment]
Huzzah!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-beta.44 containing PR #11431 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
@tmeasday what's left to do here?

**Comment by tmeasday** [comment]
I think we hoped to produce a proper solution here so we could do HMR to the `preview.js`. Not sure how important that is though.

**Comment by shilman** [comment]
OK, I think the current setup is fine. Dropping the priority on this.

**Comment by tmeasday** [comment]
This is fixed in the v7 store and will not be something we address in the v6 store.
