### ISSUE TITLE
Remove `setAddon` code

### ISSUE THREAD

**Issue by tmeasday** [storybookjs/storybook#10008]
Remove the `setAddon()` code from `client-api` and any addons that still use it.

**Comment by shilman** [comment]
- [ ] Deprecate this & add to MIGRATION.md

**Comment by shilman** [comment]
Jiminy cricket!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-beta.37 containing PR #11322 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
