### ISSUE TITLE
addon-docs: ${...} in code block is executed

### ISSUE THREAD

**Issue by thany** [storybookjs/storybook#10011]
**Describe the bug**
In a code block in MDX, inserting `${var}` is executed(-ish) and replaced by something that's not useful. There doesn't appear to be a way to escape it, and it shouldn't be neccesary anyway. This worked fine in Storybook 5.2.x but this bug may have creeped in at a later time.

This example MDX snippet:
````
```jsx
const CustomLabel = styled(Label)`
  ${display}
`;
```
````
Will be displayed as:
```
const CustomLabel = styled(Label)`
  ___CSS_0___
`;
```
I've tried to escape it with `\${display}`, `$\{display}`, `${\display}`. I've tried escaping the backticks with ` `` ` and `` \` ``. None of these escapings fix the problem. Either the escapes are displayed literally (and the bogus `___CSS_0___` remains), or I get an error that says `display is not defined`. Strangely, even without this error, it still manages to replace `${display}` with something.

**To Reproduce**
1. Have an MDX with the above code
2. Run it in your Storybook instance

**Expected behavior**
It shouldn't try to replace anything. It's not code, it's documentation.

**System:**
Results of `npx -p @storybook/cli@next sb info`:
```
  System:
    OS: Windows 10 10.0.18363
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
  Binaries:
    Node: 10.16.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
```
Too bad this command doesn't output my Storybook version, which is 5.3.14, and for addon-docs as well.

**Additional context**
One workaround is to replace ` ```jsx ` with ` ``` `, which changes the syntax highlighting. It also stops Storybook from replacing `${display}` with a bogus string. Really, the tag after ` ``` ` should *only* specify syntax highlighting and shouldn't apply any arbitrary parsing or additional code analysis. It should be treated as plain text, and *never* anything more.

**Comment by shilman** [comment]
@thany any chance you can bisect to figure out which version introduced the bug? that would help a lot.

**Comment by thany** [comment]
It's a commercial project so I can't spend too much time on it anymore, but I think I can give it a go. Would you suggest down/upgrading all storybook packages, or just addon-docs? Any specific versions where you might suspect changes pertaining to this problem?

It might help to know we came from SB 5.2.4, to be exact.

**Comment by shilman** [comment]
that would be really helpful. you should up/downgrade all the packages at once. it's a bit of a bore, but if you bisect it literally (divide in half each time), it should take you 7 tries at most (assuming there were 100 releases)

**Comment by shilman** [comment]
To confirm, the problem got introduced somewhere between `5.2.8` and `5.3.0` and you weren't able to bisect into the 5.3 pre-releases, other than to confirm that the problem is present in `5.3.0-rc.6`? i'm not sure when i'll get a chance to look at this, but that helps narrow it down. shouldn't be too hard to get to the bottom of it, but i'm juggling a lot right now.

**Comment by thany** [comment]
I understand. It's not *that* big of an issue, to be honest. If we must, we could temporarily remove the `jsx` tag and have MDX not syntax-highlight the code at all.

In the mean time, I took a little bit more time to gather some evidence that might help tracking this down.

So first of all, this screenshot of the React inspector shows the `SyntaxHighlighter` component having the correct text as its `children` prop. 
![1](https://user-images.githubusercontent.com/152227/76220900-88ad0900-6218-11ea-9b08-462f3480b011.PNG)

Digging deeper, I decided to take a look at the `code` "component", which is selected in this screenshot:
![2](https://user-images.githubusercontent.com/152227/76221082-cdd13b00-6218-11ea-9d55-81aa2e95ff39.PNG)
It's got to be in one of those spans.

And indeed, one of the spans has that weird `__CSS_0__` tag:
![3](https://user-images.githubusercontent.com/152227/76221165-eb9ea000-6218-11ea-8b8e-d80e647cbe45.PNG)
It seems like it magically decides to interpret the code inside my template literal as CSS, which could be correct, because it's styled-components code. It feels a bit arbitrary for it to do that, because it would need to do some deep analysis of the code, which is not always the best idea for a "dumb" syntax highlighter. I understand the appeal though.

To me, this says there's got to be some kind of issue inside the `SyntaxHighlighter` component, in the way it analyzes template literals, and in the way its support for styled-components-like code is seemingly broken.

Hopefully this helps a bit more.

**Comment by shilman** [comment]
Thanks @thany! I'll try my best to track it down when I get a few mins. If anybody else wants to take it, have at it!

**Comment by thany** [comment]
@shilman Just a quick followup, do you (or anyone else) know if this is solved in Storybook 6.0 by any chance? This would give me and my team another handle to justify spending time to do the upgrade 😎

**Comment by shilman** [comment]
@thany sorry i haven't looked into this yet. however, looking through the issue it looks like it corresponds to this issue in `react-syntax-highlighter`, which is the library we use under the hood: https://github.com/conorhastings/react-syntax-highlighter/issues/223

@ndelangen WDYT?

**Comment by ndelangen** [comment]
Does anyone have a minimal reproduction?

**Comment by adamborowski** [comment]
A hacky workaround (PLEASE DO NOT DO THIS IF YOU DO NOT HAVE TO)

You can paste a zero-width space after dollar sign and it works but please note that this may revenge in the future when you will play with version system

**Comment by thany** [comment]
> A hacky workaround (PLEASE DO NOT DO THIS IF YOU DO NOT HAVE TO)
> 
> You can paste a zero-width space after dollar sign and it works but please note that this may revenge in the future when you will play with version system

That is quite hacky indeed 😀
It will also mess with people trying to copypaste the code, and can't see (visually at least) why it won't work. Your warning is not undue 😀

**Comment by shilman** [comment]
@ndelangen yet another reason to get rid of `react-syntax-highlighter`

**Comment by ndelangen** [comment]
If anyone wants to pair with me on removing `react-syntax-highlighter` and solving this issue at the same time, I'd be happy to take a meeting:
https://calendly.com/ndelangen/storybook

**Comment by thany** [comment]
@ndelangen Just curious, what do you think/expect to replace it with?

**Comment by ndelangen** [comment]
@thany plan on replacing it with react-refractor, but whatever works and is maintained.

**Comment by thany** [comment]
I'm sad to find out this issue persists in Storybook 6 😞

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid.

Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
