### ISSUE TITLE
What is the type of storyFn?

### ISSUE THREAD

**Issue by baeharam** [storybookjs/storybook#10010]
I'm using storybook with typescript, but I cannot find the type of `storyFn` function.
How can I write the type of this function? Is it just `any` type?

**Comment by baeharam** [comment]
I found it from `import { StoryFn } from '@storybook/addons';`

**Comment by Hollister009** [comment]
I was able to pull it for JS-Doc:
![image](https://user-images.githubusercontent.com/34597767/153039921-e7ae9ac5-169d-4fef-af5b-d795f0663a11.png)
