### ISSUE TITLE
Docspage picks single type from a union from Typescript interface

### ISSUE THREAD

**Issue by kushalmahajan** [storybookjs/storybook#10017]
Okay. Let's say I have this code

```
interface AvatarProps {
	/** specify icon="search" or icon={IconComponent} */
	icon: React.ReactNode | string;
...
```

However, the `docspage` `props` shows only ReactNode

I have added a screenshot of the same.

<img width="1029" alt="Screenshot 2020-03-02 at 6 49 00 PM" src="https://user-images.githubusercontent.com/11805936/75680006-a9281100-5cb6-11ea-8bfa-b8d7ecf91ad2.png">

You may notice the `shape` prop shown properly. It is not a direct union but a string tuple. 

**System:**

```
Environment Info:

  System:
    OS: macOS 10.15.2
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
  Binaries:
    Node: 12.10.0 - ~/.nvm/versions/node/v12.10.0/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.10.3 - ~/.nvm/versions/node/v12.10.0/bin/npm
  Browsers:
    Chrome: 80.0.3987.122
    Safari: 13.0.4
  npmPackages:
    @storybook/addon-a11y: ^5.3.14 => 5.3.14 
    @storybook/addon-actions: ^5.3.14 => 5.3.14 
    @storybook/addon-console: ^1.2.1 => 1.2.1 
    @storybook/addon-docs: ^5.3.14 => 5.3.14 
    @storybook/addon-info: ^5.3.14 => 5.3.14 
    @storybook/addon-notes: ^5.3.14 => 5.3.14 
    @storybook/addon-storyshots: ^5.3.14 => 5.3.14 
    @storybook/addon-viewport: ^5.3.14 => 5.3.14 
    @storybook/react: ^5.3.14 => 5.3.14 
    @storybook/source-loader: ^5.3.14 => 5.3.14 
```

**Comment by shilman** [comment]
Any chance you can provide a repro? See the docs for details: https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/props-tables.md#reporting-a-bug

**Comment by kushalmahajan** [comment]
Umm...that's a little time-consuming to abstract it out. Here is an easy way. I can point to my monorepo where it can be reproduced - https://github.com/turtlemint/mint-ui



Also, you can see the deployed project here - https://mint-ui.netlify.com/?path=/docs/avatar--size

**Comment by shilman** [comment]
Added repro https://github.com/storybookjs/storybook/commit/1e2ab41dab191fd6a6b5b8f2f4b8400ba9c6b588

**Comment by shilman** [comment]
FYI the recommended 6.0 setup (should work in 5.3 too) is ready, and is the default in the most recent versions of both `@storybook/preset-typescript` and `@storybook/preset-create-react-app`:
 https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#react-prop-tables-with-typescript

I am commenting on all props-related issues to request that you upgrade so we can get this right before release. Thanks!
