### ISSUE TITLE
Problem to configure <base> to let storybook access statics in a subdirectory

### ISSUE THREAD

**Issue by Nabellaleen** [storybookjs/storybook#10025]
**Describe the bug**
I expose storybook behind a subpath on my website : `/storybook/`
So, as suggested in the [doc](https://storybook.js.org/docs/configurations/serving-static-files/#absolute-versus-relative-paths) for absolute path usage, I've tried to use `<base>` HTML element to define the base path of my statics

This is also mentionned in https://github.com/storybookjs/storybook/issues/7775

But, if the `<base>` element work well in `manager-head.html` to change the base path for scripts, it seems totally useless for cases like `<img src="/assets/my_img.png">`

Note : 
I've tried in `manager-head.html` and `preview-head.html`, with various base combinations with the various `target` available

**System:**
```
Environment Info:

  System:
    OS: Linux 5.5 Fedora 31 (Workstation Edition) 31 (Workstation Edition)
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.22.0 - /usr/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.15.3/bin/npm
  Browsers:
    Firefox: 73.0.1
  npmPackages:
    @storybook/addons: ^5.3.12 => 5.3.12 
    @storybook/core: ^5.3.12 => 5.3.12 
    @storybook/react: ^5.3.12 => 5.3.12 
```

**Comment by Nabellaleen** [comment]
Stale bots are a pain ...

**Comment by dmudro** [comment]
@Nabellaleen were you able to resolve the issue? 

I am facing a similar problem with hosting SB in a subfolder while referring to assets in public root folder in my React app - i. e. `<img src="/assets/my_img.png">`

`<base>` tag sounds almost like the solution though I think it does not work for absolute paths starting with `/` so it gets ignored for  `src="/assets/my_img.png"`.
