### ISSUE TITLE
docgen comments in CSF format stories not displaying

### ISSUE THREAD

**Issue by kushalmahajan** [storybookjs/storybook#10031]
**Describe the bug**
As per [docs](https://github.com/storybookjs/storybook/blob/master/addons/docs/docs/docspage.md#subcomponents-parameter)  the `docgen` comments should display. I wrote them in the exact format and the right place and couldn't see them above my story.

```
/**
 * By default the `Card` will take full width of the grid column put in. To control the width use style prop
 */
export const Basic = () => (
	<Card style={{ width: 300 }}>
		<Para>Card content</Para>
		<Para>Card content</Para>
		<Para>Card content</Para>
	</Card>
);
```
**System:**
Environment Info:

  System:
    OS: macOS 10.15.2
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
  Binaries:
    Node: 12.10.0 - ~/.nvm/versions/node/v12.10.0/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.10.3 - ~/.nvm/versions/node/v12.10.0/bin/npm
  Browsers:
    Chrome: 80.0.3987.122
    Safari: 13.0.4
  npmPackages:
    @storybook/addon-a11y: ^5.3.14 => 5.3.14 
    @storybook/addon-actions: ^5.3.14 => 5.3.14 
    @storybook/addon-console: ^1.2.1 => 1.2.1 
    @storybook/addon-docs: ^5.3.14 => 5.3.14 
    @storybook/addon-info: ^5.3.14 => 5.3.14 
    @storybook/addon-notes: ^5.3.14 => 5.3.14 
    @storybook/addon-storyshots: ^5.3.14 => 5.3.14 
    @storybook/addon-viewport: ^5.3.14 => 5.3.14 
    @storybook/react: ^5.3.14 => 5.3.14 
    @storybook/source-loader: ^5.3.14 => 5.3.14

**Comment by shilman** [comment]
Closing as dupe to #8527
