### ISSUE TITLE
Custom source in story

### ISSUE THREAD

**Issue by kushalmahajan** [storybookjs/storybook#10039]
When using MDX and CSF together still there is no way I can read in docs which can show full functional stateful code of a component.

JSX is pulled up by default as we know if using a simple presentational component. But that's not enough for components which are complex. Say Form.

Also when using `{stories.basic()}` in `.mdx` file show code toggle block shows literally the same text.

Let me know if there is an existing way to achieve this. Anyway, I propose that the parameters option should have something like this

```
<Story name="basic" paramters={{ source: SourceMDFile }}>
```

**Comment by kushalmahajan** [comment]
Actually CSF stories handle by default, unlike `storiesOf` API. Got that by experimentation.

Still, I have to define everything inside my story function for that. So basically functions inside functions and importantly no `import` statements to show.  It would be best and a closure to have all full fledged document at one place. So my proposal remains

**Comment by kushalmahajan** [comment]
import statements?

**Comment by shilman** [comment]
Fixed in #7479
