### ISSUE TITLE
CSF format stories disappear after some change - Hot reloading

### ISSUE THREAD

**Issue by kushalmahajan** [storybookjs/storybook#10030]
I have started to migrate to CSF format stories one by one. What I realised is that I have to reload manually to see my migrated stories.
 
1. Change the API from `storiesOf` API format to CSF format. 
2. Check the left side for your components
3. Congrats, you can't see
4. Refresh the page and you can.

**System:**

Environment Info:

  System:
    OS: macOS 10.15.2
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
  Binaries:
    Node: 12.10.0 - ~/.nvm/versions/node/v12.10.0/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.10.3 - ~/.nvm/versions/node/v12.10.0/bin/npm
  Browsers:
    Chrome: 80.0.3987.122
    Safari: 13.0.4
  npmPackages:
    @storybook/addon-a11y: ^5.3.14 => 5.3.14 
    @storybook/addon-actions: ^5.3.14 => 5.3.14 
    @storybook/addon-console: ^1.2.1 => 1.2.1 
    @storybook/addon-docs: ^5.3.14 => 5.3.14 
    @storybook/addon-info: ^5.3.14 => 5.3.14 
    @storybook/addon-notes: ^5.3.14 => 5.3.14 
    @storybook/addon-storyshots: ^5.3.14 => 5.3.14 
    @storybook/addon-viewport: ^5.3.14 => 5.3.14 
    @storybook/react: ^5.3.14 => 5.3.14 
    @storybook/source-loader: ^5.3.14 => 5.3.14

**Comment by shilman** [comment]
cc @ndelangen

**Comment by kushalmahajan** [comment]
I want this. It is clearly a bug

**Comment by shilman** [comment]
Do you have a repro repo?

**Comment by kushalmahajan** [comment]
Repo is open source at -  https://github.com/turtlemint/mint-ui

**Comment by shilman** [comment]
Any interest in trying to contribute a fix?

**Comment by kushalmahajan** [comment]
Is this the file to look in?

https://github.com/storybookjs/storybook/blob/next/lib/core/src/server/dev-server.js

**Comment by tmeasday** [comment]
These code paths have changed significantly in 6.0 (`next`). I would definitely try it with a recent alpha before investigating too much.

(Not saying the bug is necessarily fixed, but it might be!)
