### ISSUE TITLE
[Question] Building storybook in parallel

### ISSUE THREAD

**Issue by tobilen** [storybookjs/storybook#10048]
**Is your feature request related to a problem? Please describe.**
For some time, we have struggled with the build time of our storybook. It is by far the slowest part of our CI, clocking in somewhere at 4 minutes with 330 or so stories, and a subsequent 2 or so minutes for chromatic. We also use react-docgen for some of them. This will get worse fast, since we have several teams contributing to this project on a daily basis.

**Describe the solution you'd like**
Ideally, i would like to split up building the static version of the storybook over several nodes, and merge them into a single deployed storybook afterwards. I imagine something like a first step that precompiles the dlls, then compilation of the stories in parallel, maybe into chunks named by storyname/path?

**Describe alternatives you've considered**
I want to avoid deploying separate storybooks and spreading our component documentation over several urls. It'd also mean several chromatic projects which would complicate the approval process.

**Are you able to assist bring the feature to reality?**
yes, I can

**Comment by shilman** [comment]
@tobilen we're building a new feature, storybook composition, that allows you to compose multiple storybooks into one. the first version should be merged in the next few weeks -- maybe take a look at that and re-assess once it's ready?

https://github.com/storybookjs/storybook/pull/9210

**Comment by tobilen** [comment]
thats so awesome, its exactly what we need. subscribed and will take a closer look 😍
