### ISSUE TITLE
Unknown for oneOfType for arrayOf

### ISSUE THREAD

**Issue by diegofss11** [storybookjs/storybook#10047]
**Describe the bug**
Is there any reason why storybook is rendering `unknown` in the docs for the item description?

I want to validate that text can either be an `array of strings` or `string`.

```
Component.propTypes = {
  items: PropTypes.arrayOf(
    PropTypes.shape({
      text: PropTypes.oneOfType([PropTypes.arrayOf(PropTypes.string), PropTypes.string]),
    })
  ).isRequired,
};
```

**Screenshot**
![image](https://user-images.githubusercontent.com/1537929/75848122-59bc1f00-5e35-11ea-9e78-c385c8277412.png)

**Comment by shilman** [comment]
@diegofss11 any chance you can submit a repro per https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/props-tables.md#reporting-a-bug
