### ISSUE TITLE
Decorators do not trigger onDestroy for Svelte 3

### ISSUE THREAD

**Issue by tonai** [storybookjs/storybook#10044]
**Describe the bug**
When creating an addon providing a decorator with `makeDecorator` like in the [centered addon](https://github.com/storybookjs/storybook/blob/next/addons/centered/src/svelte.ts#L23-L38), the `onDestroy` callback you may set inside the Svelte decorator component is not trigegred.

**To Reproduce**
In the centered addon, add an `onDestroy` callback inside the [decorator component](https://github.com/storybookjs/storybook/blob/next/addons/centered/src/components/Centered.svelte):
```html
<div class="svelte-centered-wrapper" style="{style}">
  <div class="svelte-centered-container" style="{innerStyle}">
    <slot></slot>
  </div>
</div>

<script>
  import { onDestroy } from 'svelte';
  export let style = '';
  export let innerStyle = '';
  onDestroy(() => console.log('onDestroy'));
</script>
```
That callback is never called.

**Expected behavior**
That callback should be fired when the story component is destroyed (when you change the story).

**System:**
```
Environment Info:

  System:
    OS: Linux 4.15 Ubuntu 18.04.1 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
  Binaries:
    Node: 12.4.0 - ~/.nvm/versions/node/v12.4.0/bin/node
    Yarn: 1.13.0 - /usr/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v12.4.0/bin/npm
  Browsers:
    Chrome: 80.0.3987.116
    Firefox: 73.0.1
```

**Additional context**
The current code that should fix this behaviour exists in [this file](https://github.com/storybookjs/storybook/blob/next/app/svelte/src/client/preview/render.ts#L59-L61).
But this is Svelte 2 code, and it does not more work anymore on Svelte 3.
There is [an issue](https://github.com/sveltejs/svelte/issues/3089) about this in the Svelte repoitory.

**Comment by shilman** [comment]
FYI, there's a new layout parameter in 6.0 that should solve the centered issue specifically: https://raw.githubusercontent.com/storybookjs/storybook/next/examples/official-storybook/stories/core/layout.stories.mdx

I realize that it does not solve the general problem

**Comment by tonai** [comment]
In fact I took the centered addon as an exemple.
There is no issue with that addon because there is no `onDestroy` callback inside the Svelte decorator.
Maybe this can cause problems in other addons
