### ISSUE TITLE
Update docs for 5.2 CSF: @writing-stories/#decorators. Please add angular solution - (in this ticket)

### ISSUE THREAD

**Issue by chrisj-skinner** [storybookjs/storybook#10059]
**Is your feature request related to a problem? Please describe.**
Lack of 5.2 documentation for CSF at https://storybook.js.org/docs/basics/writing-stories/#decorators for angular users. Use of the latest spec across all frameworks would be more encourage with code snippets.

**Describe the solution you'd like**
Would be nice to see some demo code of how to implement this for an angular project

**Are you able to assist bring the feature to reality?**
Yes

**Additional context**
I found that the below worked for me. HOWEVER this is only on a individual level, would be great to declare the wrapper on the default story level.
```
import { TestComponent } from './test.component';
import { moduleMetadata, } from '@storybook/angular';
import { CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';

export default {
  title: 'Elements|Test',
  decorators: [
      moduleMetadata({
        schemas: [CUSTOM_ELEMENTS_SCHEMA],
        declarations: [TestComponent]
      })
  ]
};

export const Test = () => ({
  component: TestComponent,
  template: `<div class="testClass">test text<app-test></app-test></div>`
});
```

**Comment by shilman** [comment]
I think we're going to do a documentation overhaul once 6.0 is released where we document all of the features for each framework. In the short term, if the Discord solution that you got is working well, maybe you can add it here as a placeholder, and then we can clean it up during the overhaul?

https://storybook.js.org/docs/guides/guide-angular/

**Comment by chrisj-skinner** [comment]
Sure - I'll add that in tomorrow 👍
