### ISSUE TITLE
<Preview> component "height" property

### ISSUE THREAD

**Issue by FarisSum** [storybookjs/storybook#10051]
I have an issue where many components are being cut off, even with Preview being a dynamic component.

The classic case is when the component itself has a dynamic height (think dropdown menu when it's not collapsed). The Preview is not dynamic to state changes in its inner component.

This is not the only scenario, some components just simply don't look good in the default preview height.

Can there be a height property exposed?

**Comment by shilman** [comment]
Sounds reasonable! PRs welcome!

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if this is still relevant in SB 7.x
