### ISSUE TITLE
Buggy rendering of template literal expressions in MDX doc when using `js` coloring

### ISSUE THREAD

**Issue by Sidnioulz** [storybookjs/storybook#10050]
**Describe the bug**
When writing template literals, we need to inject expressions that look like so:
```
const myLiteral = someFunction`
  foo
  bar 
 ${expression}
`
```

In the Docs Addon with MDX, regardless of whether using the Markdown backtick syntax or `<Source>` blocks, expressions will not be properly rendered when syntax coloring is enabled and the language set to JS or JSX.

**To Reproduce**
1. Create a MDX file with the following content:
<pre>
import { Meta, Source } from '@storybook/addon-docs/blocks';

<Meta title="Bug Report" />

```jsx
import styled from '@xstyled/styled-components'
import { margin } from '@xstyled/system'

import _Bar from 'components/bar/Bar'

export const Root = styled.div`
	${margin}
	display: inline-flex;
	align-items: center;
	...

	${buggy}
`
```

<Source language="jsx" code={"foo = styled`bla bla ${buggy}`"} />

The end.
</pre>

2. Go to the docs addon, on that page
3. The expressions are not properly rendered. They are replaced by a string that looks like `___CSS_0___`, then `___CSS_1___`, etc. It works fine without syntax coloring so it seems it is the code that colors JS/CSS that bugs.

**Expected behavior**
The expressions should be displayed correctly and readable.

**Screenshots**
The buggy output:
![image](https://user-images.githubusercontent.com/5108577/75881776-0ab7bf00-5e20-11ea-9b02-a2f097c098b0.png)

The DOM output for the first `styled` template literal:
![image](https://user-images.githubusercontent.com/5108577/75881851-35097c80-5e20-11ea-9c09-4a0606271da3.png)

**Code snippets**
A repo contains a MWE that you can run directly with the same config as my live StoryBook instance. Note that the MWE contains a \<Source\> tag too, which GitHub's markdown isn't properly displaying above.

```sh
git clone https://github.com/Sidnioulz/BUGREPORT-storybook-mdx
cd BUGREPORT-storybook
yarn
yarn start
```

**System:**
Environment Info:

  System:
    OS: Linux 5.5 Arch Linux
    CPU: (12) x64 Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz
  Binaries:
    Node: 13.9.0 - /usr/bin/node
    Yarn: 1.22.0 - /usr/bin/yarn
    npm: 6.13.4 - ~/Development/front-components/node_modules/.bin/npm
  npmPackages:
    @storybook/addon-a11y: ^5.3.10 => 5.3.10 
    @storybook/addon-actions: ^5.3.10 => 5.3.10 
    @storybook/addon-docs: ^5.3.10 => 5.3.10 
    @storybook/addon-links: 5.3.10 => 5.3.10 
    @storybook/addon-viewport: ^5.3.10 => 5.3.10 
    @storybook/addons: 5.3.10 => 5.3.10 
    @storybook/preset-typescript: ^1.2.0 => 1.2.0 
    @storybook/react: ^5.3.10 => 5.3.10

**Comment by shilman** [comment]
Closing this as a duplicate to #10011
