### ISSUE TITLE
Keyboard shortcuts page has an errant comma rendering in the UI

### ISSUE THREAD

**Issue by domyen** [storybookjs/storybook#10067]
**Describe the bug**
An errant comma somehow made it into the UI (look right above the toolbar).
![image](https://user-images.githubusercontent.com/263385/76027259-580a5e00-5efe-11ea-9eb3-763fbb99ab09.png)

This appears on every Storybook including the [official SB](https://deploy-preview-9210--storybookjs.netlify.com/)

**To Reproduce**
1. Go to https://deploy-preview-9210--storybookjs.netlify.com/ (select official-storybook)
2. Click on the options > keyboard shortcuts
3. See error

**Expected behavior**
Not to render the `,`.

**Comment by emmanio** [comment]
I'll pick up this one :)

**Comment by domyen** [comment]
This is still up for grabs!

**Comment by shilman** [comment]
pretty sure this was fixed
