### ISSUE TITLE
Addon-Docs: 

### ISSUE THREAD

**Issue by vertic4l** [storybookjs/storybook#10060]
Tried to add @storybook/addon-docs, but got the following error:

<img width="499" alt="Bildschirmfoto 2020-03-05 um 14 48 08" src="https://user-images.githubusercontent.com/1771763/75987562-65b8e700-5ef0-11ea-91a1-45ced39fcf97.png">

I'm using tsx-Files with styled components... Any ideas someone ?

**main.js**
```
const custom = require("../webpack.config.js");
const MiniCssExtractPlugin = require("mini-css-extract-plugin");

module.exports = {
    stories: ["../src/**/*.story.tsx"],
    addons: [

        "@storybook/addon-actions",
        "@storybook/addon-links",
        "@storybook/addon-knobs",
        "@storybook/addon-viewport",
        {
            name: "@storybook/preset-typescript",
            options: {
                tsDocgenLoaderOptions: {},
            }
        },
        {
            name: "@storybook/addon-docs",
            options: {
                configureJSX: true,
            },
        },
    ],
    webpackFinal: async config => {
        // do mutation to the config

        return {
            ...config,
            module: {
                ...config.module,
                rules: custom.module.rules
            },
            resolve: custom.resolve,
            plugins: [
                new MiniCssExtractPlugin({
                    filename: "[name].[contenthash].css",
                }),
                ...config.plugins
            ]
        };
  },
};

```
**package.json**
```
"@storybook/addon-docs": "^5.3.14",
"@storybook/addon-info": "^5.3.14",
"@storybook/addon-knobs": "^5.3.14",
"@storybook/addon-links": "^5.3.14",
"@storybook/addon-storyshots": "^5.3.14",
"@storybook/addon-viewport": "^5.3.14",
"@storybook/addons": "^5.3.14",
"@storybook/preset-typescript": "^2.1.0",
"@storybook/react": "^5.3.14",
"react": "^16.13.0",
"typescript": "^3.8.3",
```

**Expected behavior**
Storybook loads like before (as without docs) and docs addon shows his magic.

**Comment by la99er** [comment]
I have the same problem. My issue is the custom resolve prop. Removing it, removes this error. How does your custom resolve look like?

**Comment by shilman** [comment]
The props table code uses `acorn-jsx` for processing dynamic PropTypes declarations (cc @patricklafrance) and I think it's causing problems in some cases

**Comment by la99er** [comment]
I just fixed my issue by changing the order of adding my custom resolve with the config resolve. @vertic4l , can you try to add config.resolve to you returning object? 
```
return {
            ...config,
            module: {
                ...config.module,
                rules: custom.module.rules
            },
            resolve: {
                ...custom.resolve,
                ...config.resolve,
            },
            plugins: [
                new MiniCssExtractPlugin({
                    filename: "[name].[contenthash].css",
                }),
                ...config.plugins
            ]
        };
```

**Comment by vertic4l** [comment]
@la99er you are absolutely right! Nice hint!

It was all about the resolve part:

```
resolve: {
    ...custom.resolve,
    ...config.resolve,
    modules: [
        ...config.resolve.modules,
        ...custom.resolve.modules,
    ]
},
```

works!

Thank you very much!

@shilman most of time it just seems to be the webpack config part if one wants to use his own.

**Comment by la99er** [comment]
You're welcome :)

**Comment by vertic4l** [comment]
@shilman Any chance to get the props too ?

**Comment by shilman** [comment]
Yeah, Props supports typescript. Here's a walkthrough for CRA:

https://gist.github.com/shilman/bc9cbedb2a7efb5ec6710337cbd20c0c

I'll be updating the recommendations this week based on recent developments in `react-docgen`, one of the libraries we use under the hood. But that walkthrough should still work.

**Comment by shilman** [comment]
FYI the recommended 6.0 setup (should work in 5.3 too) is ready, and is the default in the most recent versions of both `@storybook/preset-typescript` and `@storybook/preset-create-react-app`:

https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#react-prop-tables-with-typescript

I am commenting on all props-related issues to request that you upgrade so we can get this right before release. Thanks!
