### ISSUE TITLE
@storybook/addon-docs: @egoist/vue-to-react@1.1.0 requires a peer of vue@^2.6.10 but none is installed. You must install peer dependencies yourself.

### ISSUE THREAD

**Issue by tomdev10** [storybookjs/storybook#10062]
### Bug or support request summary

@storybook/addon-docs has what appears to me to be an erroenous dependancy on: `@egoist/vue-to-react@1.1.0 requires a peer of vue@^2.6.10 but none is installed. You must install peer dependencies yourself.`

### Steps to reproduce

Installed clean on new React project.

### Please specify which version of Storybook and optionally any affected addons that you're running

Version nos:
```
    "@storybook/addon-a11y": "^5.3.14",
    "@storybook/addon-docs": "^5.3.14",
    "@storybook/addon-knobs": "^5.3.14",
 "@storybook/addon-actions": "^5.3.14",
    "@storybook/addon-links": "^5.3.14",
    "@storybook/addons": "^5.3.14",
    "@storybook/react": "^5.3.14",
```
(all dev dependancies) 
### Affected platforms 

Version Nos see above

**Comment by shilman** [comment]
closing as dupe to #8936
