### ISSUE TITLE
Typescript preset-create-react-app documentation

### ISSUE THREAD

**Issue by amalv** [storybookjs/storybook#10080]
**Is your feature request related to a problem? Please describe.**
I've followed [the documentation](https://storybook.js.org/docs/configurations/typescript-config/) in order to get Typescript support for Storybook when using CRA but it did not load the `.tsx` extension.

These are the steps I followed:

* Install Create React App with the typescript template.
```
npx create-react-app storybook --template typescript
```

* Install storybook preset-create-react-app.

```
npm install -D @storybook/preset-create-react-app
```

* Rename `0-Welcome.stories.js` to `0-Welcome.stories.tsx`: the story is no longer being displayed.

**Describe the solution you'd like**
Improve the documentation. A `config.ts` file must be created inside the `.storybook` folder in order to load the `.tsx` extension with the following content:

```
import { configure } from '@storybook/react';

configure(require.context('../src', true, /\.stories\.tsx?$/), module);
```

**Describe alternatives you've considered**
May be I'm wrong or misunderstood the documentation and this is not a real issue.

**Are you able to assist bring the feature to reality?**
Yes, I can do a PR improving the documentation with the solution I've applied.

**Comment by shilman** [comment]
@amalv Take a look at these instructions. We need to do a rewrite of the page you referenced.

https://gist.github.com/shilman/bc9cbedb2a7efb5ec6710337cbd20c0c

**Comment by amalv** [comment]
Thanks for the link, pretty useful, let me know if you need help updating the documentation. Not sure if I should close the issue if a documentation update is pending, but please do so if appropriate.

**Comment by PatFawbertMills** [comment]
Thanks @shilman this helped me out massively today.
