### ISSUE TITLE
Storybook standalone preview example does NOT work

### ISSUE THREAD

**Issue by basher** [storybookjs/storybook#10081]
**Describe the bug**
The [standalone preview example](https://github.com/storybookjs/storybook/tree/next/examples/standalone-preview) does NOT work.

- No output is rendered in the browser. 
- No Storybook UI. 
- No stories.
- `<div id="root"></div>` is empty.

**To Reproduce**
Clone the repo, install NPM packages and start Storybook as per the README instructions.

**Screenshots**
The components are loaded, but not rendered in the browser.

![screenshot](https://user-images.githubusercontent.com/452809/76217445-55fc1400-620a-11ea-942e-952b70b4e3da.jpg)

**System:**
System:
    OS: Windows 10 10.0.18362
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 
2.60GHz
  Binaries:
    Node: 12.14.1 - C:\Program Files\nodejs\node.EXE
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD  
  Browsers:
    Edge: 44.18362.449.0

**Additional context**
I'm trying to setup Storybook for a Parcel-driven website, using HTML framework, not React. 

I'm getting exactly the same lack of rendered output as per your standalone React example.

**Comment by shilman** [comment]
@basher just confirmed that it's working for me. try running `yarn bootstrap --core` at the root of the repo, then run the instructions in the standalone README

**Comment by basher** [comment]
@shilman 
OK Michael, I now get the Storybook UI loaded in the browser for your standalone demo.

However, what I can't figure out is how to get it working in my Parcel HTML environement?

- I've installed [Storybook for HTML](https://storybook.js.org/docs/guides/guide-html/) into my Parcel repo.
- I've installed other required [standalone files and sample stories](https://github.com/storybookjs/storybook/tree/next/examples/standalone-preview).
- Here's my (simplified) `package.json` in my project root:
```json
{
  "devDependencies": {
    "@storybook/html": "^5.3.14",
    "parcel-bundler": "^1.12.4"
  },
  "scripts": {
    "storybook": "parcel ./storybook.html --port 1337"
  }
}
```

These instructions in your standalone sample docs do not make sense:
```
cd ../official-storybook
yarn storybook --preview-url=http://localhost:1337/iframe.html
```

I don't have a `/official-storybook/` folder in my repo, so how do I launch the `--preview-url`?

**Comment by basher** [comment]
I'm just creating a minimal setup repo that I can point you too.

**Comment by shilman** [comment]
@basher you can run `--preview-url` from any working storybook. it doesn't have to be the `official-storybook`

**Comment by basher** [comment]
Thanks @shilman 

- I have my Parcel + Storybook app running - `parcel ./storybook.html --port 9009`.
- I've created a brand new Create React App + Storybook app. `npm run storybook` works, so at least I know I have a working default Storybook environment.
- From this new CRA, I ran `npm run storybook --preview-url=http://localhost 
:9009/iframe.html`. Port 9009 was not available, so I chose 9010. Storybook loads, but with stories from the new CRA app, not the Parcel app:
![Screenshot](https://user-images.githubusercontent.com/452809/76299086-5f40bb80-62b2-11ea-923d-101c823a5936.jpg)

Is my understanding correct that I should be seeing the Parcel (HTML not React) stories?

**Comment by shilman** [comment]
That all looks reasonable to me. I know in the past you had to do `npm run x -- -y` to get the `-y` argument passed properly, not sure if that's still the case?

**Comment by basher** [comment]
Sorry, I'm not sure I understand your comment?

Are you saying that you expected to see the CRA React stories by running `npm run storybook --preview-url=http://localhost :9009/iframe.html`?

- In which case, what's the value of having a standalone Storybook with Parcel?
- It's beginning to look like I need to keep my Parcel app (with HTML) separate from any Storybook implementation (where I can add HTML stories). Is that correct? Hmmm.

**Comment by shilman** [comment]
I'm saying that you might need to run `npm run storybook -- --preview-url=http://localhost :9009/iframe.html`

**Comment by basher** [comment]
Thanks Michael, I appreciate your help with this. :)

`npm run storybook -- --preview-url=http://localhost :9009/iframe.html` works OK:

![Screenshot](https://user-images.githubusercontent.com/452809/76304122-bc406f80-62ba-11ea-9313-d833d333c2b8.jpg)

It now shows the [1 test HTML story in my repo](https://github.com/basher/parcel-boilerplate-storybook/blob/master/stories/index.stories.js), which I [configured like this](https://github.com/basher/parcel-boilerplate-storybook/blob/master/storybook.ts).

- You might want to update the standalone README to add the extra `--` in `npm run storybook -- --preview-url=http://localhost :1337/iframe.html`, and be more explicit about running this command from a different instance of Storybook rather than `official-storybook` folder, which makes no sense.
- And I look forward to seeing what happens with `@storybook/server`.

**Comment by shilman** [comment]
Glad you got it working and hope we can provide better support for this scenario very soon!
