### ISSUE TITLE
knobs addon does not work on 5.3.0 +

### ISSUE THREAD

**Issue by egauci** [storybookjs/storybook#10098]
**Describe the bug**
After upgrading storybook from 5.2.8 to 5.3.x I noticed that none of the knobs were working any more.

This project has been around for some time. It was started with create-react-app and uses storiesOf().add(). On upgrading to 5.3.x I also needed to include the preset-create-react-app addon. However, even if I keep the preset and simply back storybook to 5.2.8 everything works again.

The knobs UI updates itself correctly but the target component is never re-rendered. Here is a screenshot of console logs. Sorry this is the best I can get since my work computer will not allow me to log into github.

![storybook](https://user-images.githubusercontent.com/636829/76348617-b734ed80-62c5-11ea-8824-3f2ecb15871e.jpg)

You will notice that the 5.2.8 log contains one additional message which is missing in 5.3.0.

I apologize if I'm missing something obvious.

**To Reproduce**
In this project, I can manipulate the knobs panel UI and they appear to work. Checkboxes change state correctly etc. However, the target component's render method is never invoked.

**Expected behavior**
The previous behavior of re-rendering the component.

**Please paste the results of `npx -p @storybook/cli@next sb info` here.**
Cannot do that but my development laptop is Windows 10.10, node 12.15.0, npm 6.13.7

I got the same results by putting a static build on a Mac server running Apache and using Chrome and Edge.

**Additional context**
React and React DOM 16.12.0

The knobs addon is loaded with addDecorator(withKnobs) in config.js.

**Comment by jonniebigodes** [comment]
@egauci it would go a long way if you could get a actual reproduction going, i saw in your description that you're having issues with GitHub, With that in mind if you can hoist the code to [GitLab](https://about.gitlab.com/) i wouldn't mind taking a look at it and possibly help you with your issue.

**Comment by egauci** [comment]
@jonniebigodes Thank you for your offer. It's not possible for me to upload this code anywhere. It's proprietary not mine. There are no github issues with this though. Just upgrading from Storybook 5.2.8 to anything starting at 5.3.0 breaks knobs.

I don't think I'm doing anything extraordinary. The project was started with CRA but it is used only for Storybook (the standard CRA app is just the unchanged default it creates).

**Comment by jonniebigodes** [comment]
@egauci this is a bit of a bummer. But to the best of my knowledge there's some backward compatibility between 5.2.x and 5.3 for now. The only significant change is on how the configuration is handled. My recomendation for you based on this would be to take a look at the [intro to storybook](https://www.learnstorybook.com/intro-to-storybook/react/en/get-started/) and go over it step by step. Sorry for not being able to help you out more.

**Comment by egauci** [comment]
@jonniebigodes I really do appreciate your willingness. This is unfortunately something I have no input in. Rules are rules. Thanks also for the doc link.

**Comment by jgoz** [comment]
@egauci I was having the same issue and solved it by adding the `withKnobs` decorator to each of my story files. I think previously I had the decorator registered globally, but it must have been removed after upgrading to 5.3.

```ts
import { withKnobs } from "@storybook/addon-knobs";

export default {
    title: "MyComponent",
    decorators: [withKnobs],
    component: MyComponent
};
```
