### ISSUE TITLE
[lib/api] Move @types/reach__router into devDependencies?

### ISSUE THREAD

**Issue by ryota-ka** [storybookjs/storybook#10091]
**Is your feature request related to a problem? Please describe.**
I'm using Storybook with non-React JSX factory.
Since `@storybook/api` depends on `@types/reach__router` and it also brings `@types/react`, which introduces a global pollution of `JSX` namespace (`declare global { namespace JSX { ... } }`).

**Describe the solution you'd like**
Moving `@types/reach__router` from `dependencies` to `devDependencies` looks fine for me.
(Or is there a fair reason to declare it as a runtime dependency?)

https://github.com/storybookjs/storybook/blob/1af0458de81978964500a7a3d75cd10c0b0df4b8/lib/api/package.json#L37

**Describe alternatives you've considered**
Nothing.

**Are you able to assist bring the feature to reality?**
Yes.
If this change looks fine, I'm glad to open a pull request.

**Additional context**

Other `@types/*` packages are defined in `devDependencies`.

https://github.com/storybookjs/storybook/blob/1af0458de81978964500a7a3d75cd10c0b0df4b8/lib/api/package.json#L51-L53

**Comment by ndelangen** [comment]
We re-export some types from reach-router. If we move them, our packages break for typescript users, because the typings we refer to would be missing.
