### ISSUE TITLE
TypeError: _ref2 is undefined

### ISSUE THREAD

**Issue by jonhuteau** [storybookjs/storybook#10105]
**Describe the bug**
When I start storybook, it builds without error but it crashes in browser wiht the error

```
TypeError: _ref2 is undefined

The above error occurred in the <Manager> component:
    in Manager (created by Context.Consumer)
    in Location (created by QueryLocation)
    in QueryLocation (created by Root)
    in LocationProvider (created by Root)
    in HelmetProvider (created by Root)
    in Root

React will try to recreate this component tree from scratch using the error boundary you provided, LocationProvider.
```
**To Reproduce**
1. Update SB to 6.0.0-alpha.24
2. Start SB and go on your browser
3. The page should be blank with an error message in console 

**Expected behavior**
Storybook should start

**Screenshots**
![image](https://user-images.githubusercontent.com/58468627/76403617-756b7c00-6385-11ea-95ef-a25452515f06.png)

**System:**

```
Environment Info:

  System:
    OS: Linux 4.15 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
  Binaries:
    Node: 12.15.0 - /usr/bin/node
    npm: 6.13.4 - /usr/bin/npm
  Browsers:
    Chrome: 80.0.3987.106
    Firefox: 73.0
  npmPackages:
    @storybook/addon-a11y: ^6.0.0-alpha.24 => 6.0.0-alpha.24 
    @storybook/addon-docs: ^6.0.0-alpha.24 => 6.0.0-alpha.24 
    @storybook/addon-jest: ^6.0.0-alpha.24 => 6.0.0-alpha.24 
    @storybook/addon-knobs: ^6.0.0-alpha.24 => 6.0.0-alpha.24 
    @storybook/addon-viewport: ^6.0.0-alpha.24 => 6.0.0-alpha.24 
    @storybook/addons: ^6.0.0-alpha.24 => 6.0.0-alpha.24 
    @storybook/vue: ^6.0.0-alpha.24 => 6.0.0-alpha.24 
```

**Comment by shilman** [comment]
Sorry about that @jonhuteau -- this was due to a bad merge. Fixed and in the process of re-releasing now! 😬

**Comment by shilman** [comment]
¡Ay Caramba!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-alpha.25 containing PR #10106 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by jonhuteau** [comment]
@shilman Nice ! This one seems to be fixed. I can get a skeleton of Storybook UI but it throws another console error

```
Error: Singleton client API not yet initialized, cannot call addParameters
```

![image](https://user-images.githubusercontent.com/58468627/76411245-abaef880-6391-11ea-8693-17728328345e.png)

**Comment by shilman** [comment]
@jonhuteau make sure all your SB packages are upgraded to the latest alpha?

**Comment by jonhuteau** [comment]
@shilman 

```

Environment Info:

  System:
    OS: Linux 4.15 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
  Binaries:
    Node: 12.15.0 - /usr/bin/node
    npm: 6.13.4 - /usr/bin/npm
  Browsers:
    Chrome: 80.0.3987.106
    Firefox: 73.0
  npmPackages:
    @storybook/addon-a11y: ^6.0.0-alpha.25 => 6.0.0-alpha.25 
    @storybook/addon-docs: ^6.0.0-alpha.25 => 6.0.0-alpha.25 
    @storybook/addon-jest: ^6.0.0-alpha.25 => 6.0.0-alpha.25 
    @storybook/addon-knobs: ^6.0.0-alpha.25 => 6.0.0-alpha.25 
    @storybook/addon-viewport: ^6.0.0-alpha.25 => 6.0.0-alpha.25 
    @storybook/addons: ^6.0.0-alpha.25 => 6.0.0-alpha.25 
    @storybook/vue: ^6.0.0-alpha.25 => 6.0.0-alpha.25 
```

**Comment by shilman** [comment]
@jonhuteau can you try deleting your `node_modules` and try again? cc @tmeasday

**Comment by jonhuteau** [comment]
@shilman Yes, done already, and nothing changed

**Comment by shilman** [comment]
@jonhuteau do you have a repro?

**Comment by jonhuteau** [comment]
@shilman Well, can't figure out what I've done but this seem to be gone. I tried to remove `node_modules` and even `package-lock.json`, maybe one of this fixed it

**Comment by koriner** [comment]
I am getting this same error "Uncaught Error: Singleton client API not yet initialized, cannot call addParameters" all of a sudden.

I've tried deleting node_modules and reinstalling, but I'm still getting the error. My packages versions are:

```json
"@storybook/addon-a11y": "^6.0.0-beta.2",
    "@storybook/addon-actions": "^6.0.0-beta.2",
    "@storybook/addon-docs": "^6.0.0-beta.2",
    "@storybook/addon-knobs": "^6.0.0-beta.2",
    "@storybook/addon-links": "^6.0.0-beta.2",
    "@storybook/addon-storysource": "^6.0.0-beta.2",
    "@storybook/addon-viewport": "^6.0.0-beta.2",
    "@storybook/addons": "^6.0.0-beta.2",
    "@storybook/preset-create-react-app": "^2.1.1",
    "@storybook/react": "^6.0.0-beta.2",
    "@storybook/theming": "^6.0.0-beta.2",
```

Anybody know what is causing this?

**Comment by shilman** [comment]
@koriner clear node_modules & reinstall? regenerate lockfile & reinstall?

**Comment by koriner** [comment]
@shilman Yeah I did that :|

**Comment by shilman** [comment]
@koriner got a repro repo i can look at?

**Comment by koriner** [comment]
@shilman I'll try and put something together over the weekend. Just doing that might help me find the problem anyway!

**Comment by VsevolodChumachenko** [comment]
> 
> 
> @shilman Well, can't figure out what I've done but this seem to be gone. I tried to remove `node_modules` and even `package-lock.json`, maybe one of this fixed it

It works for me. Thank you!

**Comment by yelvert** [comment]
Still having this issue, on version 6.2.9, any solutions?

**Comment by shilman** [comment]
@yelvert Do you have a repro repo you can share?

**Comment by yelvert** [comment]
Unfortunately I do not. Just hit this tonight on a private repo. Everything was working fine on 6.1.(I think)14 and broke when upgrading. I've tried removing node_modules and reinstalling, removing lock and modules and reinstalling, no luck.

**Comment by yelvert** [comment]
Some debugging has led me to believe that the ClientApi singleton is actually getting created twice but the addParameters function is still pointing to the first one which has been reset back to undefined, instead of the second one which is correctly defined.

**Comment by shilman** [comment]
Have you verified that there is only one version of `@storybook/*` in your node_modules?
