### ISSUE TITLE
Is there a way to create a NOT nested story?

### ISSUE THREAD

**Issue by SilencerWeb** [storybookjs/storybook#10107]
As I can see in your docs, you were focused on examples of nested stories so I couldn't find any examples of creating a not nested story. Is there even a way to do it?

Right now my hierarchy looks like this which is not really comfortable to use since all stories are nested:

![image](https://user-images.githubusercontent.com/20713191/76411565-e2960600-63b3-11ea-9c27-35e8d7a36b8c.png)

If I'm not mistaken, there was a way to do it in older versions of Storybook, before this big update which includes CSF, but right now I can't find an example of such usage :(

**Comment by shilman** [comment]
@SilencerWeb AFAIK there was never any way to do this. Here's the `storiesOf` equivalent:

```
storiesOf('Header', module).add('Default', () => ...);
```

One thing you can do if you want to show a piece of documentation at the top-level is use "documentation-only mdx":

https://github.com/storybookjs/storybook/blob/8b11ec6eb9b710c5e7d896ce4da8074bd4af7f6f/addons/docs/docs/mdx.md#documentation-only-mdx

**Comment by shilman** [comment]
Duplicate to #8255
