### ISSUE TITLE
Docs(info link): info link under addons table in github docs is returning 404 error

### ISSUE THREAD

**Issue by kruthivijay31** [storybookjs/storybook#10100]
**Describe the bug**
In the github document https://github.com/storybookjs/storybook, under addons table - `info` link is broken and return 404 error.
**To Reproduce**
1. Go to 'https://github.com/storybookjs/storybook'
2. Click on 'info' link under addons table
4. See error - 404

**Expected behavior**
Render the doc for `info` usage.
**Screenshots**
<img width="803" alt="Screen Shot 2020-03-10 at 2 10 08 PM" src="https://user-images.githubusercontent.com/14045986/76359850-17815a80-62d9-11ea-9b30-00009c67f9fb.png">

**Code snippets**
If applicable, add code samples to help explain your problem.

**System:**
Please paste the results of `npx -p @storybook/cli@next sb info` here.

**Additional context**

**Comment by yannbf** [comment]
Hey @kruthivijay31, thanks for opening this issue! There is a PR which fixes the broken link at #10045.
For the time being please refer to [this link](https://github.com/storybookjs/storybook/tree/master/addons/info) for the documentation of the addon.

**Comment by kruthivijay31** [comment]
Thanks!!!
