### ISSUE TITLE
Documentation for peculiar frameworks integration

### ISSUE THREAD

**Issue by o0Djeen0o** [storybookjs/storybook#10119]
**Is your feature request related to a problem? Please describe.**
Most common frameworks are handled by the Storybook team (which is great, thanks !). however, when it comes to integrate under the hood/specific technologies, it is hard to know what should be the way to move forward in order to integrate a given stack with Storybook architecture.

For instance, I must work with https://openui5.org and, thus, need to know how to allow bootstrap of the stack, what webpack features are required, how to integrate with contexts...

**Describe the solution you'd like**
A tutorial, or a documented a way to build an integration with a technology.
For instance, a how to integration with XXX (svelte ?) has been done in order to see what should be handled by a developer

**Comment by shilman** [comment]
Closing as duplicate to #9403
