### ISSUE TITLE
MDX render vue component is not working

### ISSUE THREAD

**Issue by antony-k1208** [storybookjs/storybook#10111]
**Describe the bug**
If you try to render a component inside an mdx file its crashing with the following error message: `Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.`

**To Reproduce**
1. import a vue component inside an mdx file (i.e. `import BaseButton from './BaseButton/BaseButton.vue';`
2. try to use it somewhere inside your mdx file (like that `<BaseButton />`)
3. Serve storybook and have a look at the corresponding page in the browser

**Expected behavior**
The Component should be rendered on the desired page

**System:**
  System:
    OS: macOS 10.15.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Binaries:
    Node: 8.11.2 - ~/.nvm/versions/node/v8.11.2/bin/node
    npm: 5.6.0 - ~/.nvm/versions/node/v8.11.2/bin/npm
  Browsers:
    Chrome: 80.0.3987.132
    Firefox: 71.0
    Safari: 13.0.5
  npmPackages:
    @storybook/addon-actions: >=5.3.0 => 5.3.14 
    @storybook/addon-docs: >=5.3.0 => 5.3.14 
    @storybook/addon-knobs: >=5.3.0 => 5.3.14 
    @storybook/addon-links: >=5.3.0 => 5.3.14 
    @storybook/addon-viewport: ^5.3.14 => 5.3.14 
    @storybook/preset-typescript: ^2.1.0 => 2.1.0 
    @storybook/vue: >=5.3.0 => 5.3.14

**Comment by shilman** [comment]
Please see the docs for how to use vue components in MDX:

https://github.com/storybookjs/storybook/tree/next/addons/docs/vue#mdx

**Comment by antony-k1208** [comment]
Thanks for the fast answer and for providing this link. Sadly it isn't helping at all. 
The only thing mentioned there is how to create new stories. I do not want to create an new story but for example just show some use cases for a specific component as usual in documentations :)

MDX normally allows using components directly inside your markup. I found for example a `wrapper` component inside `@storybook/addon-docs/blocks`, unfortunately that does not work either.

**Comment by shilman** [comment]
@antony-k1208 The documentation shows exactly how to create stories. The syntax you are using is something you made up and doesn't work, and the syntax in the documentation is how you do it in Storybook.

There's an open issue to provide a more natural syntax for different view layers here https://github.com/storybookjs/storybook/issues/7984
