### ISSUE TITLE
Combine composition w/ `args` and `globalArgs`

### ISSUE THREAD

**Issue by tmeasday** [storybookjs/storybook#10115]
Following on / part of #9210:

We need to make composition work with args + global args.

### Args

This one is probably easy. We simply need to ensure that:

1. When the `STORY_ARGS_CHANGED` event is received to the manager it is routed to the correct `storiesHash`

2. When the `api.updateStoryArgs()` API is called, it sends the update to the correct ref. 

### Global Args

This one needs more thought. Options include:

 1. Combining all the global args from each ref into one big global args object. There is a potential problem with collision however. Each ref will initialize its own global args on bootup, which can happen at random times.

 2. Storing one set of global args for each ref, and updating them separately.

 3. Only storing global args for the local ref.

I prefer 2 or 3. I guess it depends on what the story is with manager-side addons and refs -- are we going to make built in addons try and take refs into account or just apply to the local ref only? For instance, should the set of toolbars displayed by the toolbars addon change as you browse between two stories in different refs?

**Comment by ndelangen** [comment]
For options 2. we can actually store the global args state on the ref object itself?

**Comment by tmeasday** [comment]
Yeah sounds about right.

**Comment by shilman** [comment]
Yippee!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-beta.43 containing PR #11407 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Zoinks!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-beta.44 containing PR #11401 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.
