### ISSUE TITLE
Remove useStoryState

### ISSUE THREAD

**Issue by tmeasday** [storybookjs/storybook#10113]
We should consider if we remove `useStoryState()`.

 - If you want to set state on a story that affects rendering, use `useArgs()` or `useGlobalArgs()`.

 - If you want to set state for an addon, use `useAddonState()`.

There are conceivably use cases for the "story-level" addon state that *does not* affect rendering, but I am not sure the complexity of `useStoryState()`'s implementation is worth it.

**Comment by tmeasday** [comment]
cc @shilman @ndelangen

**Comment by ndelangen** [comment]
PR open

**Comment by shilman** [comment]
Ooh-la-la!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-alpha.29 containing PR #10187 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.
