### ISSUE TITLE
Flow support

### ISSUE THREAD

**Issue by lihanqi** [storybookjs/storybook#10131]
Hi I'm currently working with docs and since our team is using Flow, Im wondering if current addon-docs support Flow props table?

I have seen some issues but its still unclear to me. I saw there is a way to use `react-docgen-typescript-loader` in webpack loader as follows:

```javascript
module.exports = {
  webpackFinal: async config => {
    config.module.rules.push({
      test: /\.(ts|tsx)$/,
      use: [
        {
          loader: require.resolve('ts-loader'),
        },
        // Optional
        {
          loader: require.resolve('react-docgen-typescript-loader'),
        },
      ],
    });
    config.resolve.extensions.push('.ts', '.tsx');
    return config;
  },
};

```

Since react-docgen already support Flow, can we replace `require.resolve('react-docgen-typescript-loader')` with something similar?

Any help would be appreciate, thanks ahead.

**Comment by shilman** [comment]
@lihanqi can you try the recommended 6.0 setup (should work in 5.3 too):

https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#react-prop-tables-with-typescript

We've consolidated on `react-docgen` as our typescript solution.

**Comment by lihanqi** [comment]
@shilman Thanks for the reply!

Currently I'm using 5.3.14. It seems does not support Flow type check, not TypeScript. Is Flow doc parsing natively supported in 6.x?

**Comment by shilman** [comment]
@lihanqi i'm pretty sure @patricklafrance got flow working. i'm working on the docgen default configuration this week and will try to get an example ready that you can look at.

**Comment by lihanqi** [comment]
Sounds awesome! Thanks!

**Comment by shilman** [comment]
Keeping this open

**Comment by raen79** [comment]
Hey guys, does anyone have even a temporary solution. I would need this feature quite urgently and I can't figure out how to get it working ... :(

**Comment by pascalduez** [comment]
I'm interested in Flow support as well, shouldn't be too much hassle since `react-docgen` already parse it pretty well.

I tried with `typescript: { reactDocgen: 'react-docgen' }` (oh the irony) but doesn't change a thing.

**Comment by shilman** [comment]
@pascalduez That setting does change Storybook to use `react-docgen` under the hood. There are downstream fixes that need to be made to support Flow. Contributions welcome!

**Comment by pascalduez** [comment]
Thanks @shilman, will try to digg deeper.
