### ISSUE TITLE
reading preview html to copy to clipboard via an addon

### ISSUE THREAD

**Issue by gijsbotje** [storybookjs/storybook#10141]
Hello everyone,

I'm trying to get make a storybook for my client where they can use the knobs to configure an element for their site. After they are happy with the configuration they should be able to copy the html and paste it in a text editor.
What i'm struggling with is finding an addon to copy the rendered html. I've already taken a dive into the docs to see if i can do it myself, but i can't find anything that would return me the rendered html.
Does anyone have a resource that would help me with this?

thanks in advance!

**Comment by shilman** [comment]
https://www.npmjs.com/package/storybook-addon-preview

haven't tried, but this is supposed to do that
