### ISSUE TITLE
Class Names not injected into components 

### ISSUE THREAD

**Issue by jcampbell05** [storybookjs/storybook#10140]
**Describe the bug**
When using storybook with preact the classname in my less file aren't injected into the component meaning the styles aren't loaded.

The stylesheets exist on the page which means less is working and it seems like a class is tying to be generated as all of the HTML for my components have a blank "class" attribute just no class name inside for the CSS style to be applied.

**Expected behavior**

My components should have a class generated from the less stylesheet so the style is correctly applied.

**Code snippets**

main.js
```
const path = require('path');

module.exports = {
  stories: ['../stories/**/*.stories.js'],
  addons: [],
  webpackFinal: async (config, { configType }) => {
    // `configType` has a value of 'DEVELOPMENT' or 'PRODUCTION'
    // You can change the configuration based on that.
    // 'PRODUCTION' is used when building the static version of storybook.

    // Make whatever fine-grained changes you need
    config.module.rules.push({
      test: /\.less$/,
      use: [
        {
          loader: 'style-loader'
        },
        {
          loader: 'css-loader'
        },
        {
          loader: 'less-loader'
        }
      ],
      include: path.resolve(__dirname, '../'),
    });

    // Return the altered config
    return config;
  },
};
```

A component
```
import { h } from 'preact';
import style from './style.less';

const renderDeviceDetails = (device) => {
	return (
		<div class={style.details}>
			<div>
				<p>{device.serial_number}</p>
			</div>
			<div>
				<p>{device.ethernet_mac_address}</p>
			</div>
			<div>
				<p>{device.wireless_mac_address}</p>
			</div>
		</div>
	)
};

export default (props) => {

	const device = props.device;

	return (
		<div class={style.container}>
			<div class={style.message}>
				<h3>{props.title}</h3>
			</div>
			{ (device) ? renderDeviceDetails(device) : null }
		</div>
	);
};

```

**System:**

Environment Info:

  System:
    OS: macOS 10.15.2
    CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
  Binaries:
    Node: 11.14.0 - /usr/local/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 80.0.3987.132
    Safari: 13.0.4
  npmPackages:
    @storybook/preact: ^5.3.17 => 5.3.17 

**Additional context**

**Comment by jcampbell05** [comment]
Still an issue

**Comment by aethelz** [comment]
Same issue (

**Comment by CaffeinateOften** [comment]
Think I'm running into this issue now.

**Comment by CaffeinateOften** [comment]
By messing around a bit, I did determine that the DOM element object that is created from JSX and `preact.h` does list `class` as a prop.

So by using `class={props.class}` on the child component, the class value is correctly passed down. I'm unsure with what the _expected_ behavior of Preact should be though.

**Comment by CaffeinateOften** [comment]
This problem also occurs for _all_ props used, including things like `onMouseEnter`

**Comment by marvinhagemeister** [comment]
@jcampbell05 This is not a bug in Preact, but a webpack configuration issue. If you want to make use of CSS Modules you need to enable that. To do that you need to pass `modules: true` as an option to `css-loader`. This is described in [the documentation for css-loader](https://webpack.js.org/loaders/css-loader/).

```js
{
  loader: "css-loader",
  options: {
    modules: true,
  }
}
```

**Comment by jcampbell05** [comment]
@marvinhagemeister im not using css modules though ?

**Comment by marvinhagemeister** [comment]
@jcampbell05 yeah, that's why it's not working.

**Comment by jcampbell05** [comment]
Is that CSS modules as in the css specification or CSS as in the JavaScript feature

**Comment by marvinhagemeister** [comment]
Neither, it's this thing: https://github.com/css-modules/css-modules That's what the `modules: true` enables in `css-loader`. It's not part of the CSS spec and it's not a feature of JS. It's more of a thing for bundlers only.

**Comment by jcampbell05** [comment]
Ah got it - I set it as false as I got it confused as being about CSS modules 

Cool I’ll enable it and see if it resolves it
