### ISSUE TITLE
If built with wrong configuration, the story frame turns recursive

### ISSUE THREAD

**Issue by prashnts** [storybookjs/storybook#10143]
**Describe the bug**

It's not particularly a bug, rather an interesting/concerning side effect.

My storybook configuration is out of date, but it is correct, and the static export of Storybook completes without errors. However the "story" iframe errors with a 404. Netlify substitute it with their 404 page, with a link to ´/´. Clicking this repeats.

![79653527-7134-48DC-AB4E-B3A8BDAB970A](https://user-images.githubusercontent.com/5663391/76895566-8722b700-6890-11ea-9564-57e701c825d8.png)
![6E0E3D05-72AE-427C-B6B1-C2A596C6DF60](https://user-images.githubusercontent.com/5663391/76895570-8a1da780-6890-11ea-9f18-24a0d573fef4.png)

 Here's a screenshot. Of course its not particularly a bug, and please close it if you think the same. But concerns, that i haven't checked, are:

- can this iFrame load whatever website if there's a link?
- if so, is that somehow a security problem?
- would it be useful to handle the 404 in the root page? (i can send a pull request)

Link to the page: https://deploy-preview-149--welearn-dev.netlify.com
Config: (outdated) https://github.com/CyberCRI/learn-ext/blob/36b1ec9f1d3224d1118caf6d7a4107b9a9ad500f/.storybook/config.js

**Comment by shilman** [comment]
Thanks! Closing as dupe to #5269
