### ISSUE TITLE
Feature request: Mock imports

### ISSUE THREAD

**Issue by lifeiscontent** [storybookjs/storybook#10142]
**Is your feature request related to a problem? Please describe.**

One thing I've noticed is I find myself mocking a lot of imports, e.g. if I am using apollo, I use the `MockedProvider` in storybook, or if I'm using next.js I will mock the `next/router`.

in jest, I can just do jest.mock('next/router') and it'll load a file from `__mocks__/next/router.js`

it would be nice if storybook could do this as well because then I wouldn't have to rearrange code just to make it easier to test in storybook.

**Describe the solution you'd like**

an API to mock imports and provide stubs in a different file

**Describe alternatives you've considered**
None, as this is a pretty clear solution to a problem

**Are you able to assist bring the feature to reality?**
maybe, I don't have a ton of experience with webpack, but I imagine that is where a portion of this feature would stem from.

**Additional context**
N/A

**Comment by lifeiscontent** [comment]
Just to shed some more light on why I think this feature should exist, I just recently created an example app in next.js and in order to test the full pages in the project, I ended up having to re-export all the pages so I could import them into storybook without having an apollo client trying to send API calls to production: https://github.com/lifeiscontent/realworld/tree/master/web/src/pages

**Comment by shilman** [comment]
Love this feature and think it could make Storybook a lot more powerful

**Comment by JuanCaicedo** [comment]
Hi! I'm new to this issue 😄 Makes me wonder if it would be possible to do this by tapping into storybook's [custom webpack config](https://storybook.js.org/docs/configurations/custom-webpack-config/).

My thinking is the dependency could be mocked out leveraging something like [webpack shims](https://webpack.js.org/guides/shimming/).

One tricky thing is that the webpack config is exposed in the storybook settings, but most likely the user would like to define mocks inside their stories. Those two mechanism would probably need a way to communicate 🤔

Just thinking out loud here!

**Comment by nickdandakis** [comment]
Just pulled this off with a [custom Storybook Webpack config](https://storybook.js.org/docs/configurations/custom-webpack-config/), and a [Webpack alias](https://webpack.js.org/configuration/resolve/#resolvealias).

Example `.storybook/main.js`:
```
const path = require('path');

module.exports = {
  stories: ['../stories/**/*.stories.js'],
  addons: [
    '@storybook/addon-actions',
    '@storybook/addon-links',
  ],
  webpackFinal: async (config) => {
    config.resolve.alias['next'] = path.resolve(__dirname, './mockNext');
    return config;
  }
};
```

Example `.storybook/mockNext/link.js`:
```
function MockLink({
  href,
  children,
  ...props
}) {
  return (
    <a href={href} {...props}>
      {children}
    </a>
  );
}

export default MockLink;
```

I'm mocking Next's `Link` component here, but you should be able to mock any import with this pattern.
Unsure if Storybook needs an API for this, but might be useful to add this pattern to the docs if @shilman approves.

**Comment by developer239** [comment]
@nickdandakis I don't think this is a correct solution because we should be able to mock/stub imports in runtime. 

Example:
- `Component B` is connected to redux
- `Component A` is not connected to redux and uses `Component B`

If I want to test `Component A` with Storybook I shouldn't have to connect it to redux just because `Component B` requires it. I likely have a separate story where `Component B` is tested so it would be better if I could stub `Component B` and not worry about redux when working with `Component A`.

**Comment by eric-burel** [comment]
Just linking @lifeiscontent excellent addon: https://storybook.js.org/addons/storybook-addon-next-router
I'll test that today but it sounds great, I've also opened a  related discussion on supporting full pages: https://github.com/vercel/next.js/discussions/28290
Mocking Next.js imports is a first necessary step for this.


For mocking imports more broadly, the way to go is definitely tweaking the Webpack config a bit. I am not necessarily fond of having something as advanced as Jest system, which I find very complex to understand.

**Comment by scottrippey** [comment]
I created `next-router-mock` to handle this, and it works well with Storybook.  You can enable it globally via a decorator, or per-component via a context provider:
https://www.npmjs.com/package/next-router-mock

**Comment by william-will-angi** [comment]
Hi all, I've been trying to experiment a bit with this as well. Has anyone figured out a more generic solution via webpack? I'm hoping to avoid an alias for all the modules we plan on mocking (there are a lot).

**Comment by eric-burel** [comment]
> Hi all, I've been trying to experiment a bit with this as well. Has anyone figured out a more generic solution via webpack? I'm hoping to avoid an alias for all the modules we plan on mocking (there are a lot).

Can you elaborate maybe? For Meteor what we did was pointing all `meteor/*` imports [to the right files](https://github.com/lbke/vulcan-loader) or [scrapping them](https://github.com/lbke/scrap-meteor-loader). In my experience, using Webpack was not the most suited approach (it's bad at rewriting imports) and Babel would have been more appropriate.

You can definitely generate your webpack alias automatically for instance. What's the reason for having a lot of mocked packages that wouldn't work with Next?

**Comment by william-will-angi** [comment]
Thanks for the response!
We have a mono-repo with a package structure like this: 

```
packages/
  package-1/
    index.js
    __mocks__/
      index.js
  package-2/
    index.js
    __mocks__/
      index.js
  package-3/
    index.js
    __mocks__/
      index.js
```

In jest all of the imports to mocks get updated automagically. However with webpack I'm hoping for a single config that avoids a manual alias for every mock. i.e. I don't want to end up with the following:

```
config.resolve.alias['package-1'] = path.resolve(__dirname, './packages/package-1');
config.resolve.alias['package-2'] = path.resolve(__dirname, './packages/package-2');
config.resolve.alias['package-3'] = path.resolve(__dirname, './packages/package-3');
...
```

I think an automatic generation of aliases by parsing the file structure of the repo would be possible. My understanding is that the webpack config gets computed at build time so if I create `__mocks__` directory while the server is running, I would think I need a reboot (maybe not the worst thing).


I took a look at your css-loaders and I think I could modify them to get the functionality I'm looking for, but may be overkill for my situation. I was hoping webpack may have another solution but it seems not.

**Comment by eric-burel** [comment]
> Thanks for the response! We have a mono-repo with a package structure like this:
> 
> ```
> packages/
>   package-1/
>     index.js
>     __mocks__/
>       index.js
>   package-2/
>     index.js
>     __mocks__/
>       index.js
>   package-3/
>     index.js
>     __mocks__/
>       index.js
> ```
> 
> In jest all of the imports to mocks get updated automagically. However with webpack I'm hoping for a single config that avoids a manual alias for every mock. i.e. I don't want to end up with the following:
> 
> ```
> config.resolve.alias['package-1'] = path.resolve(__dirname, './packages/package-1');
> config.resolve.alias['package-2'] = path.resolve(__dirname, './packages/package-2');
> config.resolve.alias['package-3'] = path.resolve(__dirname, './packages/package-3');
> ...
> ```
> 
> I think an automatic generation of aliases by parsing the file structure of the repo would be possible. My understanding is that the webpack config gets computed at build time so if I create `__mocks__` directory while the server is running, I would think I need a reboot (maybe not the worst thing).
> 
> I took a look at your css-loaders and I think I could modify them to get the functionality I'm looking for, but may be overkill for my situation. I was hoping webpack may have another solution but it seems not.

Let me know if you have something open source, I maintain a monorepo as well: https://github.com/VulcanJS/vulcan-npm

However I try to store global testing/storybook related stuff at top level to avoid this as much as possible, are often global mocks are roughly the same for all packages.

**Comment by SoraKumo001** [comment]
Addon created to mock the module.
https://github.com/SoraKumo001/storybook-module-mock

```tsx
import Link from "next/link";
import React, { FC } from "react";

interface Props {}

/**
 * NextHook
 *
 * @param {Props} { }
 */
export const NextHook: FC<Props> = ({}) => {
  return (
    <div>
      <Link href="/">Before</Link>
    </div>
  );
};
```

```tsx
import { expect } from "@storybook/jest";
import { ComponentMeta, ComponentStoryObj } from "@storybook/react";
import { within } from "@storybook/testing-library";
import * as link from "next/link";
import { createMock, getMock } from "storybook-addon-module-mock";
import { NextHook } from "./NextHook";

const meta: ComponentMeta<typeof NextHook> = {
  title: "Components/NextHook",
  component: NextHook,
};
export default meta;

export const Primary: ComponentStoryObj<typeof NextHook> = {};

export const Mock: ComponentStoryObj<typeof NextHook> = {
  parameters: {
    moduleMock: {
      mock: () => {
        const mock = createMock(link);
        mock.mockReturnValue(<div>After</div>);
        return [mock];
      },
    },
  },
  play: async ({ canvasElement, parameters }) => {
    const canvas = within(canvasElement);
    expect(canvas.getByText("After")).toBeInTheDocument();
    const mock = getMock(parameters, link);
    expect(mock).toBeCalled();
  },
};
```
![image](https://user-images.githubusercontent.com/54426986/224534557-7e4c23a6-4afd-4440-956b-34978afe497b.png)
![image](https://user-images.githubusercontent.com/54426986/224534570-aef28ae9-b124-41a6-872d-5c2268c2af9a.png)

**Comment by kasir-barati** [comment]
> I'm mocking Next's `Link` component here, but you should be able to mock any import with this pattern.
> Unsure if Storybook needs an API for this, but might be useful to add this pattern to the docs if @shilman approves.

I have tiny issue with this solution, when you have TS aliases it ignores this mocks, or at least that is what happened in my case. I have storybook configured to be able to read tsconfig aliases and they are working but when I am trying to mock an alias import I have this issue that storybook cannot see them so it goes and uses the actual code and not the mock one 😞 

Do you have any idea how can I mock the aliases' imports in storybook?

**Comment by SoraKumo001** [comment]
Mock may work if you apply Mock to 'mockNext/link.js'

**Comment by kasir-barati** [comment]
@SoraKumo001 I did not get your suggestion, I have a tsconf like this:
```json
// ...
"paths": {
  "@libs/*": ["libs/*"],
}
// ...
```
# Does not work

and in my react component:
```ts
import {something} from "@libs/something"
import {useGetUser} from "@libs/hooks/use-get-user"

export function Component() { const user = useGetUser(); }
```

And here is my main.js
```js
module.exports = {
  webpackFinal: async (config) => {
    config.resolve.alias = {
      ...config.resolve.alias,
      "@libs/hooks/use-get-user": path.resolve(__dirname, "./mocked-use-get-user"),
  }
}
```

# Work

and in my react component:
```ts
import {something} from "@libs/something"
import {useGetUser} from "../../../libs/hooks/use-get-user"

export function Component() { const user = useGetUser(); }
```

And here is my main.js
```js
module.exports = {
  webpackFinal: async (config) => {
    config.resolve.alias = {
      ...config.resolve.alias,
      "../../../libs/hooks/use-get-user": path.resolve(__dirname, "./mocked-use-get-user"),
  }
}
```

So now I wanna know why, JFI my TS aliases are working in general but just when I try to mock them they do not work

**Comment by SoraKumo001** [comment]
Try the following

- Use aliases on the component side
import {useGetUser} from "@libs/hooks/use-get-user"

- On the Storybook side, create a mock using the actual path
import {useGetUser} from "... /... /... /libs/hooks/use-get-user"

**Comment by kasir-barati** [comment]
@SoraKumo001 I did not get what you mean by storybook side, are you talking about `.storybook/main.js` or in the `stories.tsx`?

If the latter I should say that I do not know how I can mock it since it is not like the `jest.mock`, but also inside the component I am using it and not passing it as a prop or something similar

**Comment by SoraKumo001** [comment]
I specified paths in tsconfig.json and it worked without any problems.

```json
    "paths": {
      "@/*": ["./src/*"]
    }
```
https://github.com/SoraKumo001/storybook-module-mock/blob/master/src/components/Paths/Paths.stories.tsx
https://sorakumo001.github.io/storybook-module-mock/?path=/story/components-paths--path-mock

**Comment by gentlee** [comment]
> Just pulled this off with a [custom Storybook Webpack config](https://storybook.js.org/docs/configurations/custom-webpack-config/), and a [Webpack alias](https://webpack.js.org/configuration/resolve/#resolvealias).
> 
> Example `.storybook/main.js`:
> 
> ```
> const path = require('path');
> 
> module.exports = {
>   stories: ['../stories/**/*.stories.js'],
>   addons: [
>     '@storybook/addon-actions',
>     '@storybook/addon-links',
>   ],
>   webpackFinal: async (config) => {
>     config.resolve.alias['next'] = path.resolve(__dirname, './mockNext');
>     return config;
>   }
> };
> ```
> 
> Example `.storybook/mockNext/link.js`:
> 
> ```
> function MockLink({
>   href,
>   children,
>   ...props
> }) {
>   return (
>     <a href={href} {...props}>
>       {children}
>     </a>
>   );
> }
> 
> export default MockLink;
> ```
> 
> I'm mocking Next's `Link` component here, but you should be able to mock any import with this pattern. Unsure if Storybook needs an API for this, but might be useful to add this pattern to the docs if @shilman approves.

And what if I need to mock something in each Story differently?

**Comment by tillsanders** [comment]
I needed to mock the composables from `vue-router` and used the `viteFinal` configuration option. The component I was writing the story for imports these composables like this: 

```typescript
import { useRoute, useRouter } from 'vue-router'
```

This would be easy to mock in e.g. Vitest, but in Storybook this seems to require more work. There is a plugin that can mock imports, but only relative ones. So instead, I extended the vite config like this:

```typescript
// .storybook/main.ts

import path from "path";
import type { StorybookConfig } from "@storybook/vue3-vite";
import { mergeConfig } from 'vite';

const config: StorybookConfig = {
  // [...]
  async viteFinal (config) {
    return mergeConfig(config, {
      resolve: {
        alias: {
          "vue-router": path.resolve(__dirname, "./mocks/vue-router"),
        },
      }
    });
  }
};
export default config;
```

And then I created a stub for the composables I needed:

```typescript
// .storybook/mocks/vue-router.ts

export const useRouter = () => ({
  push: () => {}
});

export const useRoute = () => ({
  query: {}
});
```

This works for me. However, it would be nice to have a solution as simple as `storybook.mock('vue-router')`.

**Comment by valentinpalkovic** [comment]
Please use the addon https://github.com/ReactLibraries/storybook-addon-module-mock for module mocking. Please open an issue there if it doesn't satisfy your use case. Closing.

**Comment by rChaoz** [comment]
@valentinpalkovic I don't think this should be closed. The add-on you provided is React only, and right now there's no way to achieve mocking in frameworks that don't use Webpack (e.g. Svelte)

**Comment by vanessayuenn** [comment]
@kasperpeulen can you confirm that this has been addressed as part of module mocking project?

**Comment by vanessayuenn** [comment]
Closing this as it has been addressed! Check out [Type-safe module mocking in Storybook](https://storybook.js.org/blog/type-safe-module-mocking/).

**Comment by abdel-ships-it** [comment]
I cant upgrade to storybook v8, and found this solution using `jest.spyOn` for storybook v7 for a usecase where Im using `file-saver` [package](https://www.npmjs.com/package/file-saver).


```typescript
import { expect, jest } from '@storybook/jest';
import fileSaver from 'file-saver';
import noop from 'lodash/noop';
// replace noop with your implementation, for me a function that does nothing is good enough (NO-OP)
const saveAsMock = jest.spyOn(fileSaver, 'saveAs').mockImplementation(noop);

export const DownloadJson: StoryObj<typeof JsonPreview> = {
    name: 'Should download JSON',
    play: async ({ canvasElement }) => {
        const downloadButton = within(canvasElement).getByText('Download JSON');
        await userEvent.click(downloadButton);

        expect(saveAsMock).toBeCalled();
    },
};

```
