### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, utime '/.../storybookExample/.storybook/generated-entry.js'

### ISSUE THREAD

**Issue by devtreehouse** [storybookjs/storybook#10156]
**Describe the bug**
I simply tried to add a plugin in a brand new storybook repo, and it ran into the error in the title.
**To Reproduce**
1. Clone https://github.com/devtreehouse/StorybookLazyCompile
2. yarn storybook
3. See the error popup

**Expected behavior**
It should run storybook
**Screenshots**
![image](https://user-images.githubusercontent.com/41341666/76998459-5edb9c80-6912-11ea-9e5a-5f0cf4f7bd62.png)

**Code snippets**
If applicable, add code samples to help explain your problem.
webpack.config.js
```
const LazyCompilePlugin = require('lazy-compile-webpack-plugin');

module.exports = ({ config }) => {
  console.log('customized config');
  config.plugins.push(new LazyCompilePlugin());
  return config;
}
```
**System:**
Please paste the results of `npx -p @storybook/cli@next sb info` here.

**Additional context**
I tried adding it to finalWebpack in `main.js`, it runs into exact same problem
It is really weird that it works in one of my other complicated repos (not public), but very unstably. In this brand new repo it doesn't work.

**Comment by shilman** [comment]
cc @ndelangen

**Comment by ndelangen** [comment]
There must be some weird version mismatch going on here.

Please remove all node_modules and lockfiles and make sure all storybook related packages are of the same version.

**Comment by mgol** [comment]
@ndelangen You can see that @devtreehouse's test case has a `yarn.lock` so the whole dependency tree is locked and all `@storybook/*` packages are at version 5.2.0 there.

**Comment by ndelangen** [comment]
You have https://github.com/liximomo/lazy-compile-webpack-plugin/ which isn't compatible with storybook.

I think this might fix it:
https://github.com/liximomo/lazy-compile-webpack-plugin/#ignores

Add `.storybook` to the ignores list
