### ISSUE TITLE
[addon-backgrounds] Switching between stories does not reset background color to global default background color

### ISSUE THREAD

**Issue by winterlamon** [storybookjs/storybook#10157]
**Describe the bug**
When a default background in global parameters is set using the backgrounds add-on, navigating between stories does not reset the background to use the default. 

Given I have `preview.js` set up like the snippet below:

```js
// preview.js
import { addParameters } from '@storybook/react'

addParameters({
  backgrounds: [
    { name: 'Blue', value: '#094fdb' },
    { name: 'Light Grey', value: '#f7f7f7' },
    { name: 'Teal', value: '#85e5c6' },
    { name: 'White', value: '#fff', default: true },
    { name: 'Yellow', value: '#f5ff02' },
  ],
})
```

**Actual behavior**
When I set the global background color options, I expect any story I view to have a white background, unless that story has a different color background set at the story level.

And when I select a blue background for a story and navigate to a different story that does not have a story-level background default set, I see the new story with a blue background.

**Expected behavior**
When I set the global background color options, I expect any story I view to have a white background, unless that story has a different color background set at the story level.

And when I select a blue background for a story and navigate to a different story that does not have a story-level background default set, I expect the new story to have a white background.

**To Reproduce**
1. Set global background colors for `addon-backgrounds` with one of the colors set to default
2. Go to a story and observe that its background color was the one set to the default
3. Switch the background color for that story using the add-on
4. Go to a different story and observe that the background is the color that was last set on the previous story viewed instead of the global default color

**System:**
```
Environment Info:

  System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 10.18.1 - ~/.nvm/versions/node/v10.18.1/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v10.18.1/bin/npm
  Browsers:
    Chrome: 80.0.3987.149
    Firefox: 69.0.3
    Safari: 13.0.2
  npmPackages:
    @storybook/addon-a11y: ^5.3.17 => 5.3.17
    @storybook/addon-actions: ^5.3.17 => 5.3.17
    @storybook/addon-backgrounds: ^5.3.17 => 5.3.17
    @storybook/addon-docs: ^5.3.17 => 5.3.17
    @storybook/addon-knobs: ^5.3.17 => 5.3.17
    @storybook/addon-links: ^5.3.17 => 5.3.17
    @storybook/addon-storysource: ^5.3.17 => 5.3.17
    @storybook/addon-viewport: ^5.3.17 => 5.3.17
    @storybook/addons: ^5.3.17 => 5.3.17
    @storybook/react: ^5.3.17 => 5.3.17
```

**Comment by shilman** [comment]
@yannbf any chance you can take a look at this in the updated version?

**Comment by shilman** [comment]
@yannbf can you take a look at this?

**Comment by yannbf** [comment]
Oh wow sorry @shilman I didn't see this before! Will check right away.

**Comment by yannbf** [comment]
Hey @winterlamon, thanks for opening an issue with us! Sorry that it was stale for some time. 
If I understand you correctly, you only set programmatically the colors once in `preview.js`, in a global fashion. Then you change the color by *clicking in the addon button*, right? 
The addons keep their state, so that whenever you switch stories the addon will still respond with the last behavior you set. It would be quite annoying if you wanted to check how all your components looked with a blue background, then you had to set it back again every single time you switched stories.

You can however set backgrounds per story level if you want, so that when switching to other stories you will have the default background, and when visiting that specific story, you will get the blue background. You can find instructions [here](https://github.com/storybookjs/storybook/tree/master/addons/backgrounds) on how to do that.

I hope this was helpful! If I did understand you correctly, this is not a bug. Please close this issue if you see fit!

**Comment by winterlamon** [comment]
Hey, @yannbf. Thanks for writing. The behavior you described is correct.

I didn't realize that the addon buttons were meant to affect the stories globally. If that's the intended behavior, I can close the issue. 👍🏾

**Comment by worc** [comment]
this also seems to affect the parameters object when creating the meta object in later versions of storybook. you set a single background color for a one-off component, but then that color ends applying to _all_ stories. likewise there seems to be a similar bug with storybook's implementation of react context. setting context in one story redefines the context for all stories.

**Comment by yannbf** [comment]
> this also seems to affect the parameters object when creating the meta object in later versions of storybook. you set a single background color for a one-off component, but then that color ends applying to _all_ stories. likewise there seems to be a similar bug with storybook's implementation of react context. setting context in one story redefines the context for all stories.

Hey @worc can you provide a reproduction using https://storybook.new ? we could then reopen this issue and work on it.

**Comment by aadi-paypay** [comment]
> this also seems to affect the parameters object when creating the meta object in later versions of storybook. you set a single background color for a one-off component, but then that color ends applying to all stories. likewise there seems to be a similar bug with storybook's implementation of react context. setting context in one story redefines the context for all stories.

also facing this issue on storybook/vue

**Comment by yannbf** [comment]
@aadi-paypay please provide a reproduction if you can :)
