### ISSUE TITLE
Expose color picker options

### ISSUE THREAD

**Issue by alexkrolick** [storybookjs/storybook#10167]
http://casesandberg.github.io/react-color/

The `react-color` lib's Sketch picker has a few options that would be nice to be able to use in the color knob and/or the new controls.

1. presetColors - Array of Strings or Objects, Hex strings for default colors at bottom of picker
2. onChange => onChangeComplete should allow users to type in a value into the hex selector

**Are you able to assist bring the feature to reality?**
no, sorry

**Comment by alexkrolick** [comment]
go away stale bot

**Comment by alexkrolick** [comment]
<activity>

**Comment by alexkrolick** [comment]
not stale

**Comment by shilman** [comment]
Hi gang, We’ve just released addon-controls in 6.0-beta!

Controls are portable, auto-generated knobs that are intended to replace addon-knobs long term.

- [Controls README](https://github.com/storybookjs/storybook/tree/next/addons/controls)
- [Migration instructions](https://github.com/storybookjs/storybook/blob/next/addons/controls/README.md#how-do-i-migrate-from-addon-knobs)

Please upgrade and try them out today. Thanks for your help and support getting this stable for release!

**Comment by shilman** [comment]
For anybody who is interested in Controls but don't know where to start, I've created a quick & dirty step-by-step walkthrough to go from a fresh CRA project to a working demo. Check it out:

=> [Storybook Controls w/ CRA & TypeScript](https://gist.github.com/shilman/69c1dd41a466bae137cc88bd2c6ef487)

There are also some "knobs to controls" migration docs in the Controls README:

=> [How do I migrate from addon-knobs?](https://github.com/storybookjs/storybook/blob/next/addons/controls/README.md#how-do-i-migrate-from-addon-knobs)

**Comment by alexkrolick** [comment]
Does the new color control have all the options?

**Comment by Orpheusp** [comment]
Just chatted with @shilman and we both think we should expose some of the options for the color control. I'll start with exposing `presetColors`.

**Comment by shilman** [comment]
Shiver me timbers!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-rc.11 containing PR #11606 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
