### ISSUE TITLE
Storybook Storyshots + Playwright

### ISSUE THREAD

**Issue by DimitrK** [storybookjs/storybook#10162]
**Is your feature request related to a problem? Please describe.**
Currently Storyshots + Puppeteer support Chromium based browsers only. During development the developer should do the manual testing on other browsers on new and existing UI to ensure consistency and avoid regression issues. 
Running screenshot tests on other browsers such as webkit and firefox built better confidence on your suite and reduces the effort for manual testing on these environments.

**Describe the solution you'd like**
A new addon based on Storyshots with [Playwright](https://github.com/microsoft/playwright) is a good candidate to tackle this problem. Playwright team was also behind Puppeteer so they tried to provide a  concise way on this migration.
> Due to the similarity of the concepts and the APIs, migration between the two should be a mechanical task.

**Describe alternatives you've considered**
There is an effort made towards porting [Puppeteer to firexox](https://github.com/puppeteer/puppeteer/tree/master/experimental/puppeteer-firefox) which is experimental hence not a good candidate to tackle this problem right now.

**Are you able to assist bring the feature to reality?**
unfortunately not at the moment

**Additional context**
-

**Comment by wKich** [comment]
I also want to add `Playwright` support for my visual testing tool [creevey](https://github.com/wKich/creevey) in near future.

For now `creevey` support only selenium webdriver, but it provide ultra-fast cross-browser testing and fancy web ui runner with visual diff comparing.

**Comment by rajington** [comment]
this probably will be a more popular request as playwright becomes more popular

**Comment by bard** [comment]
@DimitrK puppeteer and Playwright have very similar APIs. This works for me:

```js
import playwright from 'playwright'
// ...

initStoryshots({
  test: imageSnapshot({
    getCustomBrowser: () => {
      return playwright.chromium.launch()
    }
  })
})
```

To also match Puppeteer's default viewport size:

```js
import playwright from 'playwright'
// ...

initStoryshots({
  test: imageSnapshot({
    getCustomBrowser: async () => {
      const browser = await playwright.chromium.launch()
      const context = await browser.newContext({
        viewport: { width: 800, height: 600 },
      })
      return context
    }
  })
})
```

**Comment by shilman** [comment]
@bard WHOA. maybe worth adding to the docs?!

**Comment by DimitrK** [comment]
Great to let us know @bard . Thank you!

**Comment by jedmao** [comment]
What is `imageSnapshot` in this context?

**Comment by bard** [comment]
@shilman I wouldn't bless it that far. :) As puppeteer is a hard (as opposed to peer) dependency of addon-storyshots-puppeteer, doing the above with TypeScript requires sprinkling a few `@ts-ignore` to make it work, because puppeteer's `Browser` type and playwright's `Browser` types aren't equivalent. IMHO it's best regarded as a hack until some more work can be done on Storyshots.

**Comment by o-alexandrov** [comment]
Please consider to reopen the issue and, at best, to guide on how the community could help you to transition to PlayWright.
Webkit-based browsers **is a must due to Safari**, which is the second most used browser.

**Comment by o-alexandrov** [comment]
As Storybook itself uses Playwright, could you please consider to reopen the issue?
