### ISSUE TITLE
Title case jest addon panel name

### ISSUE THREAD

**Issue by codejamninja** [storybookjs/storybook#10160]
Most of the panels seem to use title case for the panel name. I am confused why the jest addon panel does not use title case. I think it should use title case for consistency. I have attached a screenshot below that demonstrates this.

![Screenshot from 2020-03-19 15-37-47](https://user-images.githubusercontent.com/6234038/77056085-f36bfa80-69f7-11ea-8b88-8daf90bf8dd4.png)

**Comment by codejamninja** [comment]
I created the following pull request that should fix this issue.

https://github.com/storybookjs/storybook/pull/10161

**Comment by shilman** [comment]
Ta-da!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-alpha.29 containing PR #10161 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
