### ISSUE TITLE
Docs source loader doesn't render Vue code correctly.

### ISSUE THREAD

**Issue by lopis** [storybookjs/storybook#10163]
I have been trying to show code snippets of my Vue components in docs, but due to the limitations of vue in docs, the result is overly noisy (See example below)

**Expected behavior**

I expected to be able to control what appears inside the code box, or at least only render the actual vue code.

**Code snippets**

```
export const Button = () => ({
  components: { MyButton },
  template: `
  <div>
  <MyButton>Button</MyButton>
  <MyButton primary>Button</MyButton>
  </div>
  `,
})
```

This renders in docs like this:
![image](https://user-images.githubusercontent.com/2715751/77067013-87cc6200-69e4-11ea-833b-6a192657e628.png)

**System:**
```
Environment Info:

  System:
    OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
  Browsers:
    Firefox: 74.0
```

**Comment by lopis** [comment]
I'm currently exploring the option `addScriptHandler` from the `vueDocgenOptions` passed to docs.

**Comment by lopis** [comment]
As suggested by @shilman over on the discord channel, the easy way to solve this is with the new `formatSource` option in 6.0.

https://github.com/storybookjs/storybook/blob/38bc41f6bf892ebe26657d5565afcceedeb93026/addons/docs/docs/recipes.md

In my case, I added this function to my story:

```
const SOURCE_REGEX = /^is\(`\n?(.*)\n?`\)$/s
export default {
  title: 'Components/Button',
  component: EButton,
  parameters: {
    docs: {
      inlineStories: true,
      formatSource: (src, storyId) => {
        const match = SOURCE_REGEX.exec(src);
        return match ? match[1] : src;
      }
    },
    viewMode: 'docs'
  },
}
```

So that my function 

```
...
const is = (template, description) => () => ({
  components: { EButton },
  template,
})

export const Button = is(`
<div>
  <EButton>Button</EButton>
  <EButton primary>Button</EButton>
</div>
`)
...
```

Renders perfectly:

![image](https://user-images.githubusercontent.com/2715751/77079494-6d9c7f00-69f8-11ea-8aea-0f35d5640803.png)

**Comment by shilman** [comment]
Great job @lopis! Looks 💯
