### ISSUE TITLE
Implement polished's cssVar to add CSS variable support fully to theming.

### ISSUE THREAD

**Issue by bhough** [storybookjs/storybook#10170]
**Is your feature request related to a problem? Please describe.**
Previously theming would break when passed a CSS variable due to `polished` not supporting pulling variable values (https://github.com/storybookjs/storybook/issues/6135). A workaround was put in place (https://github.com/storybookjs/storybook/pull/6939) to guard against this but didn't add the ability to leverage them.

**Describe the solution you'd like**
We now provide a helper in `polished` that fetches CSS Variable values (https://polished.js.org/docs/#cssvar) and we'd like to help implement it into theming to provide support for CSS variables.

**Describe alternatives you've considered**
N/A

**Are you able to assist bring the feature to reality?**
Yes!

**Comment by shilman** [comment]
Can you explain the use case a bit more? Sounds like a great improvement but I don't quite get it yet. @ndelangen should be able to help if you have any q's about contributing!

**Comment by ndelangen** [comment]
@bhough that's great news! We'd love to take a PR fixing this.

What do you think about using that util function in the `@storybook/theming`'s `convert` util?

**Comment by bhough** [comment]
@ndelangen Great, `convert` seems like a logical starting point based on a brief look at the code. I'll put some time in this weekend and see what I can come up with.

**Comment by giorgiogalassi** [comment]
Hi,

Is this issue fixed?
If yes, how i'm supposed to integrate?

I have a library of ui-components, all written in Stencil.JS, using css-variables.

Regards.
