### ISSUE TITLE
Angular: addDecorator in preview.js throw error ''Can't find React variable"

### ISSUE THREAD

**Issue by RogierdeRuijter** [storybookjs/storybook#10174]
**Describe the bug**
addDecorator in preview.js throws error ''Can't find React variable" with Angular storybook

**To Reproduce**
1. Create angular app
2. Add storybook
3. Create preview.js file
4. Add a line with `addDecorator(...)`
5. Add packages: babel-loader, @babel/core, @babel/preset-env, @babel/preset-react,
6. Add babel.config.js in .storybook folder with 
```
module.exports = {
    presets: [
      "@babel/preset-env",
      "@babel/preset-react"
    ]
  };
```
7. start storybook

Dummy repo with issue:
https://github.com/RogierdeRuijter/angular-storybook

**System:**
Environment Info:

  System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
  Browsers:
    Chrome: 80.0.3987.149
    Firefox: 74.0
    Safari: 13.0.5
  npmPackages:
    @storybook/addon-actions: ^5.3.14 => 5.3.17 
    @storybook/addon-links: ^5.3.14 => 5.3.17 
    @storybook/addon-notes: ^5.3.14 => 5.3.17 
    @storybook/addons: ^5.3.14 => 5.3.17 
    @storybook/angular: ^5.3.14 => 5.3.17

**Comment by shilman** [comment]
@RogierdeRuijter you're wrapping your angular story in a React component, and `@storybook/angular` doesn't know how to render React. I'd recommend trying out `@storybook/addon-centered` if you want to center your stories.

@kroeder @ndelangen @tmeasday we need to fix our non-react decorator documentation

**Comment by RogierdeRuijter** [comment]
Thanks for your response.

My use case is the following. In my angular application I have different themes, dark and light. To apply one of these themes I add the css class, light-theme or dark-theme to the body tag in the angular application. 

Since this class is not there on the storybook body tag I need to add either the light or dark theme css class so it wraps around the story. I believe this is a good use case for decorators.

The workaround I am currently using is to use the template field of a story and wrap the component I want to display in a div with the class ‘light-theme’. It looks something like this:

```
<div class=“light-theme”>
  <my-component></my-component>
</div>
```

Cheers

**Comment by shilman** [comment]
Have you tried something like this?

```js
const themes = ['light-theme', 'dark-theme'];
export const themeDecorator = (storyFn, context) => {
  const themeClass = context?.parameters?.theme || 'light-theme';
  const bodyClasses = document.body.classList;
  themes.forEach(theme => { bodyClasses.remove(theme) });
  bodyClasses.add(theme);
  return storyFn();
}
```

Also easy to adapt to `addon-toolbars` in 6.0:

https://github.com/storybookjs/storybook/tree/next/addons/toolbars

**Comment by RogierdeRuijter** [comment]
Yeah this seems nice! Thanks for your help I am going to give this a try!

**Comment by anoopsinghbayes** [comment]
@shilman can also change the backgrounds (parameters)selection from the decorator ,as I neet to set a dark background and if I have a background color on the body the grid gets hidden
