### ISSUE TITLE
addon-docs iFrame local assets such as fonts getting fallback due to slow network?

### ISSUE THREAD

**Issue by Skullpluggery** [storybookjs/storybook#10177]
**Describe the bug**
I don't understand why local assets getting fallback in an iFrame. See the screenshots for more information. I am using the latest next version, Storybook 6.0.0-alpha.27

**To Reproduce**
1. Install Angular Material
2. Import custom font to CSS
3. Add Stories to demo Buttons
4. Run Storybook

Note: I can't share the repository as this is a company application.

**Expected behavior**
Should not fallback fonts as local assets are served locally.

**Screenshots**
https://imgur.com/a/fdgpz19

**System:**
Environment Info:
  System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz
  Binaries:
    Node: 12.16.1 - C:\Users\delacly\AppData\Local\Programs\nodejs\node.EXE
    Yarn: 1.22.0 - C:\Users\delacly\scoop\apps\yarn\current\Yarn\bin\yarn.CMD
    npm: 6.13.4 - C:\Users\delacly\AppData\Local\Programs\nodejs\npm.CMD
  Browsers:
    Chrome: 80.0.3987.132

**Comment by shilman** [comment]
This is a known issues with having too many iframes on the page. There are two possible solutions: https://github.com/storybookjs/storybook/issues/7455 https://github.com/storybookjs/storybook/issues/8153 

I'm going to close this as a duplicate to those... fingers crossed we'll get some movement on that soon. I understand this is a pain. 🤞
