### ISSUE TITLE
Addon to toggle all the CSS

### ISSUE THREAD

**Issue by revelt** [storybookjs/storybook#10173]
**Is your feature request related to a problem? Please describe.**
When coding HTML, it is handy to disable the CSS to see how the raw markup looks. It's for semantic markup decisions, accessibility and many other uses. 

**Describe the solution you'd like**
Let's add a button to toggle CSS:

<img width="754" alt="toggle_button" src="https://user-images.githubusercontent.com/8344688/77192824-191b0180-6ad5-11ea-96c5-af90ef6f2dcb.png">

**Describe alternatives you've considered**
Web developer tools can't toggle inside the frame, so it's not suitable... It's pretty much impossible to toggle off the CSS currently, isn't it? (Besides putting a component in a project and opening that project and disabling CSS via browser plugins...)

**Are you able to assist bring the feature to reality?**
I can help to the extent of my humble capabilities.

**Additional context**
This addon would help people to make better markup decisions and also developing for better accessibility.

**Comment by shilman** [comment]
That sounds like a great addon. If you can achieve that using a storybook decorator function, it might be easy to prototype using `@storybook/addon-toolbars`
