### ISSUE TITLE
Storybook busted on 5.3.10

### ISSUE THREAD

**Issue by lifeiscontent** [storybookjs/storybook#10176]
**Describe the bug**
```
ERROR in ./.storybook/generated-entry.js
Module build failed (from ../node_modules/babel-loader/lib/index.js):
Error: [BABEL] /Users/lifeiscontent/Source/lifetime/storybook/.storybook/generated-entry.js: Could not find plugin "proposal-numeric-separator". Ensure there is an entry in ./available-plugins.js for it. (While processing: "/Users/lifeiscontent/Source/lifetime/node_modules/@babel/preset-env/lib/index.js")
    at getPlugin (/Users/lifeiscontent/Source/lifetime/node_modules/@babel/preset-env/lib/index.js:67:11)
    at /Users/lifeiscontent/Source/lifetime/node_modules/@babel/preset-env/lib/index.js:258:62
    at Array.map (<anonymous>)
    at /Users/lifeiscontent/Source/lifetime/node_modules/@babel/preset-env/lib/index.js:258:43
    at /Users/lifeiscontent/Source/lifetime/node_modules/@babel/helper-plugin-utils/lib/index.js:19:12
    at /Users/lifeiscontent/Source/lifetime/node_modules/@babel/core/lib/config/full.js:199:14
    at Generator.next (<anonymous>)
    at Function.<anonymous> (/Users/lifeiscontent/Source/lifetime/node_modules/@babel/core/lib/gensync-utils/async.js:26:3)
    at Generator.next (<anonymous>)
    at step (/Users/lifeiscontent/Source/lifetime/node_modules/gensync/index.js:254:32)
    at evaluateAsync (/Users/lifeiscontent/Source/lifetime/node_modules/gensync/index.js:284:5)
    at Function.errback (/Users/lifeiscontent/Source/lifetime/node_modules/gensync/index.js:108:7)
    at errback (/Users/lifeiscontent/Source/lifetime/node_modules/@babel/core/lib/gensync-utils/async.js:70:18)
    at async (/Users/lifeiscontent/Source/lifetime/node_modules/gensync/index.js:183:31)
    at onFirstPause (/Users/lifeiscontent/Source/lifetime/node_modules/gensync/index.js:209:13)
    at Generator.next (<anonymous>)
 @ multi ../node_modules/@storybook/core/dist/server/common/polyfills.js ../node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/generated-entry.js ../node_modules/webpack-hot-middleware/client.js?reload=true&quiet=true main[2]
```

the only file I have in the `.storybook` folder is `main.ts`

```js
module.exports = {
  stories: ['../stories/*.stories.tsx']
};
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System:**
Please paste the results of `npx -p @storybook/cli@next sb info` here.

**Additional context**

**Comment by shilman** [comment]
cc @ndelangen

**Comment by lifeiscontent** [comment]
@shilman this ended up working once I changed all my storybook configs back to `.js`

**Comment by shilman** [comment]
Possibly related https://github.com/storybookjs/storybook/pull/10099

**Comment by ndelangen** [comment]
> the only file I have in the .storybook folder is main.js

> @shilman this ended up working once I changed all my storybook configs back to .js

I'm confused

**Comment by mayteio** [comment]
I had the same issue. Turns out its an issue with react-scripts [8680](https://github.com/facebook/create-react-app/issues/8680) so I fixed it by;
1. deleting node_modules
2. updating all dependancies on react-script 3.4.0 to 3.4.1 (monorepo)
3. yarn 
4. storybook working again.

**Comment by ndelangen** [comment]
@Aaron-Pool are you still having this issue? Could the elaborate on what's wrong?

**Comment by shilman** [comment]
I think you mean @lifeiscontent 😂

**Comment by Aaron-Pool** [comment]
How did I get here? Where did it all go wrong? 🤔

**Comment by lifeiscontent** [comment]
> > the only file I have in the .storybook folder is main.js
> 
> > @shilman this ended up working once I changed all my storybook configs back to .js
> 
> I'm confused

Sorry, corrected. main.ts

**Comment by alex-ald** [comment]
I have the same issue. I ran `npx @storybook/cli init` within an angular application.  Then ran npm run storybook, but received the same errors

**Comment by alex-ald** [comment]
Adding the dependency @babel/compat-data": "7.8.0" fixed the issue for me.

Resource: https://stackoverflow.com/questions/60790726/could-not-find-plugin-proposal-numeric-separator-in-angular-app

**Comment by ndelangen** [comment]
I can't even find what that package does... it has no readme.

**Comment by lifeiscontent** [comment]
Solution: use `.js` configs
