### ISSUE TITLE
[CLI] Add the ability to pause rebuilding or add an on-demand mode

### ISSUE THREAD

**Issue by iansan5653** [storybookjs/storybook#10175]
**Is your feature request related to a problem? Please describe.**
Running `start-storybook` continuously in the background while developing can consume significant amounts of memory, which makes it almost impossible to do unless running a high-end machine. On the other hand, the first compile when running that command can take 5-10 minutes on such machines. This makes developing with Storybook on low to midrange machines very slow.

**Describe the solution you'd like**
I'd like to be able to do one of two things:
1. Pause rebuilding with a key command, preserving the current built state for later without always rebuilding every time I save a file.
2. Add a mode where instead of rebuilding every time a file changes, it just rebuilds when I press a specific key, ie <kbd>Enter</kbd>.

**Are you able to assist bring the feature to reality?**
Possibly if given some pointers to where this would be in the code.

**Additional context**
Here's Storybook taking over 700 MB of RAM while running in watch mode and recompiling:
![image](https://user-images.githubusercontent.com/2294248/77204139-7ceafd80-6ac8-11ea-90f1-c67bc8762b70.png)

**Comment by shilman** [comment]
TBH this sounds like a lot of work. Storybook relies on webpack for building, and AFAIK the webpack file watcher is fairly efficient. I don't know whether turning it on and off would affect memory usage at all.

My guess is that the time would be much better spent optimizing Storybook. We're planning on doing a 6.x performance release to slim things down, but would gratefully accept perf-related PR's at any time.

**Comment by ndelangen** [comment]
We'd need support for this from webpack.

**Comment by iansan5653** [comment]
Could we at least be able to adjust the debounce rate of the refresh? My code editor autosaves every time I stop typing for a half second, which means that I'm usually rebuilding 5-10 times more often than I need to be. I don't really want to slow down autosave and risk losing work. That would just mean forwarding the `watchOptions.aggregateTimeout` option from webpack.

**Comment by ndelangen** [comment]
That's already possible:
https://github.com/storybookjs/storybook/blob/9da592591c4bd35b45a9a869f121e3ba156af0f3/lib/core/src/server/dev-server.js#L108-L109

**Comment by iansan5653** [comment]
Oh thanks, that's not documented on the CLI options page. Is that specified like `--watchOptions {"aggregateTimeout": 500}`?

**Comment by ndelangen** [comment]
uhm, You have to add those options to the webpack config:
https://storybook.js.org/docs/configurations/custom-webpack-config/

**Comment by iansan5653** [comment]
Oh duh, thanks.
