### ISSUE TITLE
Bug in glob to require-context regex: storybook 5.3 attempts to load stories from node_modules

### ISSUE THREAD

**Issue by yoavniran** [storybookjs/storybook#10178]
**Describe the bug**
i upgraded my monorepo to 5.3.17 (from 5.2.8) and SB now tries to load stories from storybook's own node_modules directories.

Im hoping its just me doing something wrong but from what i can see this is an issue with SB and a breaking change from pre 5.3.

my .storybook/config.js had this configure:

```
configure(require.context("../packages",
	true,
	/\.stor(y|ies)\.js/), module);
```
which i translated to main.js:

```
module.exports = {
    stories: [
        "../packages/**/*.stories.js"
    ]
...
}
```

when i run sb i get this error:

```
ReferenceError: exports is not defined
    at Module../packages/ui/upload-button/node_modules/@storybook/components/dist/ActionBar/ActionBar.stories.js (http://localhost:9111/vendors~main.8d3b8dd16022b2b66155.bundle.js:128649:23)
    at __webpack_require__ 
```

from debugging i can see the resulting configuration passed to the require context is: 

> ./packages sync recursive ^\.\/(?:(?:(?!\.)(?:(?:(?!(?:|\/)\.).)*?)\/)?(?!\.)(?=.)[^\/]*?\.stories\.js\/?)$

my repo has this structure:

root
 --- packages
 ----- pkg-a
 ----- pkg-b
 ----- ui
 ------- ui-pkg-a
 ------- ui-pkg-b

the UI packages have the story file in their root:

<img width="371" alt="Screen Shot 2020-03-21 at 11 24 53" src="https://user-images.githubusercontent.com/1102278/77223595-a78b9380-6b66-11ea-9744-7b5e9386e1ad.png">

but since each package has its own node_modules folder, SB attempts to load stories found in it (through symlink). it finds the stories from SB's own code.

When I tried to improve the glob pattern to be more precise. for example:

> "../packages/ui/\*/\*.stories.js"

SB doesnt find any stories...

when i run this pattern using glob it correctly returns only the relevant files:

```
console.log(glob.sync("./packages/ui/*/*.stories.js"));
```

returns:

[ './packages/ui/chunked-uploady/ChunkedUploady.stories.js',
  './packages/ui/upload-button/UploadButton.stories.js',
  './packages/ui/upload-drop-zone/UploadDropZone.stories.js',
  './packages/ui/upload-preview/UploadPreview.stories.js',
  './packages/ui/upload-url-input/UploadUrlInput.stories.js' ]

when i tried with exclude:

> "../packages/**/!(node_modules/)*.stor(y|ies).js"

SB still loads all the files.

**To Reproduce**

code is available on my branch.
https://github.com/yoavniran/react-uploady/blob/storybook-upgrade/.storybook/main.js

1. check out repo on branch: storybook-upgrade
2. run: yarn
3. run: yarn ssb
4. See error in browser

**Expected behavior**
SB shouldnt load stories from node_modules

there is also 0 documentation around the stories path configuration which would be very useful. 

**System:**

 System:
    OS: macOS 10.15.3
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Binaries:
    Node: 10.15.2 - ~/.nvm/versions/node/v10.15.2/bin/node
    Yarn: 1.19.1 - ~/.yarn/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v10.15.2/bin/npm
  Browsers:
    Firefox: 73.0.1
    Safari: 13.0.5
  npmPackages:
    @storybook/addon-actions: ^5.3.17 => 5.3.17 
    @storybook/addon-console: ^1.2.1 => 1.2.1 
    @storybook/addon-knobs: ^5.3.17 => 5.3.17 
    @storybook/addon-storysource: ^5.3.17 => 5.3.17 
    @storybook/react: ^5.3.17 => 5.3.17

**Comment by shilman** [comment]
cc @ndelangen

**Comment by ndelangen** [comment]
We turn the glob into a require.context regex here:

https://github.com/storybookjs/storybook/blob/54a1c0c5f6e6cb9ca078c884c45447b95fada29f/lib/core/src/server/preview/to-require-context.js#L27-L30

Do you see any obvious bugs @yoavniran I'm confused as to why `"../packages/**/!(node_modules/)*.stor(y|ies).js"` would still load files from `node_modules`.

**Comment by yoavniran** [comment]
hey @ndelangen as far as i can tell the resulting regex does match even if the path contains node_modules.

this can be seen here: https://jsbin.com/coxuqojuli/edit?js,console

the regex is the one stored in "m" from line 28 in: 
https://github.com/storybookjs/storybook/blob/54a1c0c5f6e6cb9ca078c884c45447b95fada29f/lib/core/src/server/preview/to-require-context.js#L28

```
/^\.\/(?:(?:|\/|(?:(?:(?!(?:|\/)\.).)*?)\/)(?:(?!(?:node_modules))[^\/]*?)[^\/]*?\.stories\.js)$/
```

my regex skills arent that sharp to tell why this is the case without starting to take it apart which may take a while. hopefully you guys have a better idea.

**Comment by ndelangen** [comment]
@yoavniran I'll try to debug and solve this before 6.0 release, any help would be appreciated!

**Comment by yoavniran** [comment]
thanks @ndelangen - I will be happy to help. Hopefully tonight will be able to troubleshoot

**Comment by ndelangen** [comment]
@yoavniran Perhaps instead of converting the globs to this webpack special thing (which seems to yield incorrect results) we could convert it to an actual list of files.

**Comment by yoavniran** [comment]
hey @ndelangen 
ive been trying to debug micromatch which looks to be the source of the issue. its definitely not returning what I would have expected. Might be due to my lack of familiarity with all of its complexity but the following seems like a problem to me:


```javascript
const paths = [
	{
		path: "./ui/button/button.stories.js",
		expected: true
	},
	{
		path: "./ui/button/node_modules/button.stories.js",
		expected: false
	},
	{
		path: "./ui/button/node_modules/test/button.stories.js",
		expected: false
	},
];

const ptrn = "**/!(node_modules)/*.stories.js";

paths.forEach(({ path, expected }) => {
	console.log(`${path} match =  ${isMatch(path, ptrn)} - expected: ${expected}`);
});

```

yields the following:

./ui/button/button.stories.js match =  **true** - expected: **true**
./ui/button/node_modules/button.stories.js match =  **false** - expected: **false**
./ui/button/node_modules/test/button.stories.js match =  **true** - expected: **false**

So the issue isnt with the webpack mechanism but with the resulting regex. 
Again, more likely to do with my pattern although using the [glob library](https://www.npmjs.com/package/glob) i got the expected results using the same pattern


Regarding your last comment. Did you mean replacing the use of require.context? Wouldnt that be a big change? Or is there a way to pass a list of paths to the context, as the result of running glob() ?

**Comment by ndelangen** [comment]
> Regarding your last comment. Did you mean replacing the use of require.context? Wouldn't that be a big change

Yes, and yes that would be a big change, but I think it would help making things simpler?

It would also allow us to injecting all stories as separate entrypoints!

**Comment by yoavniran** [comment]
Hey @ndelangen 
ive been playing with the implementation a bit and i was able to get the correct paths (using fast-glob).

i added those to the entries passed to the iframe webpack config (lib/core/src/server/preview/iframe-webpack.config.js)
however, im not so sure about how you see getting rid of require.context (if thats what you meant) because even though the story modules are bundled, we still need to require them on the fly and get their exports. Is there a way to do that other than using require.context?

What i did was pass the stories' path as strings to the loadCsf code but when call require() it breaks, saying it cant find the module (even though its bundled). 
also typescript doesnt seem happy for me to use require() dynamically this way.

thoughts?

**Comment by ndelangen** [comment]
@yoavniran looking at your original post again, I think you should try to make sure there are no node_modules directories inside the packages directory. If at all possible hoisting dependencies up.

`"../packages/**/!(node_modules/)*.stor(y|ies).js"` seems to not be transformed quite correctly in the `lib/core/src/server/preview/to-require-context.js`. That could be considered a bug.

One way you can fix it is by doing something like this:


```js
// main.js

module.exports = {
  stories: async () => {
    // use some glob library
    return []; // return the exploded glob
  },
};
```

**Comment by yoavniran** [comment]
regarding your first comment. Not sure how that can be accomplished. I'm working in a mono-repo (lerna + yarn workspaces) and my stories are co-located with their respective package. 
Changing my repo structure isnt really an option.

And no matter how I look at it, loading stories from node_modules is a (specific) bug and the pattern not being transformed correctly is the more general bug.

Although TBH, from my tests, i wasnt able to accomplish a single pattern that works with either glob or fast-glob libraries. 
They both have ways to pass in excludes (ignore) that require additional parameters. 

As for your second answer. I didnt know it was even an option to pass a function and it works !!! thanks! 

I did need to tweak it a bit: 

```javascript
const glob = require("fast-glob");

module.exports = {
      stories: async () => {
        const paths = await glob(["./packages/**/*.stories.js", "!**/node_modules"]);
        return paths.map((p)=> `.${p}`);
    },

```
since glob works from the root and SB works from the config folder.

This function form isnt documented anywhere or did I miss something?

**Comment by ndelangen** [comment]
All properties in main.js can be functions that take the previous config and return a new one.

**Comment by yoavniran** [comment]
@ndelangen I see you closed this. While I found a workaround I still think the fact that SB blindly loads stories from node_modules is a bug, especially as it breaks it. 
I also think that documentation is lacking around the area of configuration and the function variant. It needs more clarification so other users have an easier time

**Comment by adamborowski** [comment]
@yoavniran I found some solution but I am not sure if this can break from version to version as it is not documented. But right now main.js in contrasto to config.js is executed in a node process not in the browser. So you can synchronously query for all packages to prepare list of precise globs. Here is my example where I read all monorepo package roots and add glob for src and stories directories (those globs never find node_modules)
```javascript
const getGlobsForPackages = dev => {
  const extensions = ['ts', 'js', 'tsx', 'jsx'].join('|');
  const cwd = process.cwd();
  const _ = require('lodash');
  const fs = require('fs');
  const path = require('path');
  const packageGlobs = require('../lerna.json').packages;
  const globby = require('fast-glob').sync;

  const allPackageJsonPaths = _.flatten(packageGlobs.map(packageGlob => globby(['!**/node_modules/**', packageGlob + '/package.json'])));
  const storiesRoots = _.compact(
    _.flatten(
      allPackageJsonPaths
        .map(packageJson => path.resolve(packageJson, '..'))
        .map(packageRoot => {
          const src = path.join(packageRoot, 'src');
          const stories = path.join(packageRoot, 'stories');
          // it is important that src and stories are in separate globs because Storybook finds static base for require.context()
          return [fs.existsSync(src) && src, fs.existsSync(stories) && stories];
        })
    )
  ).map(root => path.relative(cwd, root));

  const convertStoriesRootToGlob = root => `../${root}/**/*.stories${dev ? '?(.dev)' : ''}.@(${extensions})`;
  return storiesRoots.map(convertStoriesRootToGlob);
};

const globsForPackages = getGlobsForPackages(process.env.DEV);
module.exports = {
  stories: globsForPackages,
  addons: [
    '...
  ],
};


```

And it produces correct globs. Please note that storybook is parsing globs to find a base for require.context so you don't have so flexiblity there.
![image](https://user-images.githubusercontent.com/3614676/80920750-241eae00-8d72-11ea-8a25-8a7e5b532fca.png)

**Comment by ndelangen** [comment]
@adamborowski This is actually the plan to become the default at some point, and make every story file be it's own webpack entry-point, making code-splitting possible too.
#10009
