### ISSUE TITLE
Broken link in the 'Writing Presets' article

### ISSUE THREAD

**Issue by sebastian-nowak** [storybookjs/storybook#10183]
1. Go to https://storybook.js.org/docs/presets/writing-presets/
2. Ctrl + f for `this is not possible using standard webpack configuration`
3. Click the `standard webpack configuration`

The link leads to https://storybook.js.org/docs/presets/custom-webpack-config/ which doesn't exist

**Comment by sebastian-nowak** [comment]
Just FYI if you click on the broken link (in my 1st post), the 404 page asks to create an issue in that repository :) That's why I posted there.

**Comment by shilman** [comment]
Fixed in c1bb8efc6f
