### ISSUE TITLE
Addon centered breaks story display in Docs mode

### ISSUE THREAD

**Issue by jgarplind** [storybookjs/storybook#10188]
**Describe the bug**
When adding `addDecorator(centered)` to `preview.js`, the display of the story in the Docs tab is silently ignored and I am instead presented with a blank slate.

**To Reproduce**
Append `addDecorator(centered)` to `preview.js` as is done here:
```
import { addDecorator, addParameters } from '@storybook/react'
import { withA11y } from '@storybook/addon-a11y'
import centered from '@storybook/addon-centered/react'

import '../src/Styles/_global.scss'

addDecorator(centered)
addDecorator(withA11y)

addParameters({
  backgrounds: [
    { name: 'light', value: '#eff0f9', default: true },
    { name: 'dark', value: '#392b64' },
  ],
})
```

**Expected behavior**
The component should render, ideally centered, even when embedded in the Docs page.

**Screenshots**

Canvas with `centered` :100:
![image](https://user-images.githubusercontent.com/10069144/77297931-54dae480-6cea-11ea-8a63-f0b67a7f0b34.png)

Docs with `centered` 👎 
![image](https://user-images.githubusercontent.com/10069144/77297974-63c19700-6cea-11ea-9fc8-f97b6dd10d59.png)

Canvas without `centered` 👎 
![image](https://user-images.githubusercontent.com/10069144/77297868-3543bc00-6cea-11ea-8ad1-64d4dba8ef8c.png)

Docs without `centered` 💯 
![image](https://user-images.githubusercontent.com/10069144/77297892-4096e780-6cea-11ea-9748-54d2c6da2494.png)

**System:**
Environment Info:

  System:
    OS: Windows 10 10.0.18362
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0

**Additional context**
Potential workaround: apply `addon-centered` only to Canvas tab. Is this easily achievable?

**Comment by shilman** [comment]
@jgarplind staring in storybook 6.0 we're deprecating addon centered and we have a built-in `layout` parameter that controls the layout:

https://github.com/storybookjs/storybook/blob/next/examples/official-storybook/stories/core/layout.stories.js

Give that a try?

**Comment by shilman** [comment]
Closing as dupe to #7227
