### ISSUE TITLE
storybook/react bug with margins

### ISSUE THREAD

**Issue by greenroach** [storybookjs/storybook#10205]
**Describe the bug**
Margins in layout create unnecessary scrolls and shift body

**To Reproduce**
1. Create a story with margin in any container 
```
const testStory: React.FC = () => {
  return <div style={{ margin: "10px" }}>text</div>;
};
```
2. Run the story. The body will be shifted and vertical scrolls will appear.
3. Remove margin or wrap it to another div with the same padding and all be ok.
```
const testStory: React.FC = () => {
  return <div style={{ margin: "10px" }}>text</div>;
};
```
**Expected behavior**
Margin in some div shouldn't create scrolls and shift body

**Screenshots**
With margins:
![image](https://user-images.githubusercontent.com/6224866/77436192-3f51e180-6df4-11ea-9c3b-7de16f92a804.png)

Without margin:
![image](https://user-images.githubusercontent.com/6224866/77436138-2b0de480-6df4-11ea-8069-321c4b1a485b.png)

**System:**
  System:
    OS: Linux 5.3 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz
  Binaries:
    Node: 12.16.1 - /usr/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.13.4 - /usr/bin/npm
  Browsers:
    Chrome: 80.0.3987.149
    Firefox: 74.0
  npmPackages:
    @storybook/addon-actions: ^5.2.5 => 5.3.14 
    @storybook/addon-knobs: ^5.2.5 => 5.3.14 
    @storybook/addon-links: ^5.2.5 => 5.3.14 
    @storybook/addons: ^5.2.5 => 5.3.14 
    @storybook/react: 5.2.5 => 5.2.5

**Comment by shilman** [comment]
@greenroach can you check out the new `layout` parameter in 6.0 and let me know if that solves the problem?

https://github.com/storybookjs/storybook/blob/next/examples/official-storybook/stories/core/layout.stories.js

**Comment by greenroach** [comment]
Hi, @shilman, sorry for a long answer. I checked layout and seems it not helped. Also I found that the bug reproduced only if body min-width set to 100vh. I created clean project with empty cra + stories to reproduce it. https://github.com/greenroach/storybook-margins

**Comment by shilman** [comment]
@ghengeveld @ndelangen can you guys take a look at this?

**Comment by ghengeveld** [comment]
The short answer is that you shouldn't wrap your component with a padded container, we have the new layout prop for that.

However, there may be valid use cases, so we'll have to investigate.

@greenroach can you try with the layout prop set to "fullscreen" in Storybook v6? Alternatively you can just set the html/body margin to 0, that's what it does.

**Comment by ndelangen** [comment]
Wrapping stories with divs that have margin isn't recommended. either padding would do, or use the layout parameter.

**Comment by greenroach** [comment]
@ghengeveld the body already have the margin 0 style.
@ndelangen this example works the same
```
  <div>
    <div style={{margin: "10px"}}>
      <Button onClick={action('clicked')}>
        Hello Button
      </Button>
    </div>
  </div>
```

**Comment by ndelangen** [comment]
@greenroach yes, margin 'bleeds' outside of containing box. that's the problem.

change it to padding, and it should be fixed.

**Comment by greenroach** [comment]
@ndelangen Yes, but I'f I need to place in story some component with margins there will be problems.

**Comment by ghengeveld** [comment]
Perhaps you're already aware, but components with margins are generally frowned upon. Read this: https://mxstbr.com/thoughts/margin

Regardless I'll investigate and see if we can improve it for v6.

**Comment by ndelangen** [comment]
A `overflow: hidden` will prevent margin bleed, but I don't see that as a good solution tbh, and not something i'd take as a PR for storybook, as I think it will cause many more issues than it would fix.
