### ISSUE TITLE
Redundant `core-js` and `airbnb-js-shims` deps

### ISSUE THREAD

**Issue by f-masche** [storybookjs/storybook#10206]
**Is your feature request related to a problem? Please describe.**

I recently started using storybook for an angular project, and I noticed the bundle size is HUGE (vendor bundle is about 7.8 MB !!!) and the startup times are not the greatest.

Question: Is there any effort taken on improving performance and reducing the bundle size in the future? 

During my research, I found some redundant dependencies like `core-js` and `airbnb-js-shims` in `storybook/core`, which kind of do the same thing 🤷‍♂️. 
Is there a reason for having both `lowlight` and `refactor` for syntax highlighting, including ALL language files?

**Describe the solution you'd like**
1. Remove either `core-js` or `airbnb-js-shims`. 
2. Choose between `lowlight` and `refactor` and load only js and css languages.

**Describe alternatives you've considered**
None so far. 

**Are you able to assist bring the feature to reality?**
Yes I could definitelly do some work.

**Comment by shilman** [comment]
@f-masche This would be a tremendous contribution to Storybook and we'd love help on this. I'm hoping to do a full performance release post 6.0 but in the meantime all perf-related contributions are welcome.

- The syntax highlighter issue is dupe: #9282 
- The `core-js` issue is something @ndelangen has looked at extensively, but I don't think we have any resolution yet.

In general, I suspect there's a lot of low-hanging fruit here. Renaming this issue to be more specific, but please feel free to open more issues/PRs as needed. Also you can filter issues by the `performance issue` label:

https://github.com/storybookjs/storybook/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22performance+issue%22

**Comment by ndelangen** [comment]
@f-masche want to talk in a zoom call about this some time?

Feel free to take a slot in my calendar:
https://calendly.com/ndelangen/storybook

**Comment by shilman** [comment]
[Current bundle](https://app.packtracker.io/organizations/184/projects/150/commits/c1e2477b3d6378d933af8eb612f8a30eeb939c9f/explore):
- core-js 249kb
- es6-shim 136kb
- es5-shim 107kb
- es-abstract 54kb
- regenerator-runtime 24kb

**Comment by ndelangen** [comment]
Is be removed in `future/base`, which is the main branch for `7.0`. So this is on the way!

**Comment by shilman** [comment]
closing as fixed in 7.0
