### ISSUE TITLE
Importing MD files in MDX

### ISSUE THREAD

**Issue by thany** [storybookjs/storybook#10209]
**Describe the bug**
The [MDX specification](https://mdxjs.com/getting-started#documents) suggests that one can import MD files in MDX and render them out. However, this does not work. I looks like this is called "tranclusion".

**To Reproduce**
1. Have an MDX story.
2. Import an existing MD file and render it out as if it were a component
3. Navigate to it in Storybook
4. Admire the error

**Expected behavior**
It should render markdown.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/152227/77536911-74fed500-6e9d-11ea-8ce2-f0d102716e6c.PNG)

**Code snippets**
According to the [MDX specification](https://mdxjs.com/getting-started#documents), this should work:
```
import Readme from './README.md';

<Meta title="Documentation|Readme" />

<Readme />
```

The current workaround is not awful, but involves more code than neccesary:
```
import { Description } from '@storybook/addon-docs/blocks';
import Readme from '.README.md';

<Meta title="Documentation|Readme" />

<Description>{Readme}</Description>
```

**System:**
Please paste the results of `npx -p @storybook/cli@next sb info` here:
```
Environment Info:

  System:
    OS: Windows 10 10.0.18363
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
  Binaries:
    Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
```

**Additional context**
Storybook core & addons-docs are both at 5.3.17.

**Comment by thany** [comment]
Worthy of note, triple-backtick code blocks from within the MD file are rendered somewhat weirdly, likely because I have to render the MD into a `Description` tag that doesn't handle codeblocks in the same way as straight MDX does. This means a very default `<pre>` tag with no syntax highlighting.

When this issue is resolved, I would expect codeblocks to get syntax highlighting as well.

**Comment by shilman** [comment]
@thany closing as dupe to #7644
