### ISSUE TITLE
Confusing warning: "…simply add `@storybook/preset-create-react-app` to your project."

### ISSUE THREAD

**Issue by techieshark** [storybookjs/storybook#10213]
**Describe the bug**

After upgrading to Storybook 5.3.17, I ran 'yarn storybook' and see the following warning:
```
WARN Storybook support for Create React App is now a separate preset.
WARN To get started with the new preset, simply add `@storybook/preset-create-react-app` to your project.
WARN The built-in preset will be disabled in Storybook 6.0.
```

This is confusing, because I have "@storybook/preset-create-react-app" in my package.json.

**To Reproduce**
1. Create storybook react project or upgrade one to 5.3.17.
2. Run 'yarn start-storybook`.
3. Observe warning. 

**Expected behavior**

A warning explaining more than "simply add `@storybook/preset-create-react-app` to your project.'". 

(Sidenote: searching the codebase for 'simply add', I ran across "simply add" as an example of ["bad documentation"](https://github.com/storybookjs/storybook/blob/a201adb5314563eb16e80b6d93c3f31e1bf8059b/docs/README.md#guidelines-for-writing-good-documentation)).

I was confused for quite a while because I thought I needed to only add it to package.json.

It seems I actually am supposed to add it to the list of addons in `./storybook/main.js`:
```
module.exports = {
  stories: ['../**/*.stories.js'],
  addons:
  [
    '@storybook/preset-create-react-app',
  ...
 ]
````

(Adding it has made the warning go away.)

**Screenshots**
<img width="752" alt="image" src="https://user-images.githubusercontent.com/1072292/77606557-f15fe980-6f6b-11ea-9923-318d850bc728.png">

**Code snippets**
Appears the message comes from here: https://github.com/storybookjs/storybook/blob/7ba88f6506f891033b867ff547066978fcc2db71/app/react/src/server/framework-preset-cra.ts#L18

**Comment by shilman** [comment]
@techieshark any chance you can contribute a PR to fix it?

**Comment by techieshark** [comment]
@shilman yep done! Thanks : )

**Comment by jeremyzilar** [comment]
Do you need to add `@storybook/preset-create-react-app` to your project even if you're not using create react app?

**Comment by umarmw** [comment]
@jeremyzilar, the same question that I'm asking as it makes no sense to me.

**Comment by its-miller-time** [comment]
+1 for @jeremyzilar quesion
