### ISSUE TITLE
How to define a function in mdx?

### ISSUE THREAD

**Issue by dragooncjw** [storybookjs/storybook#10214]
First, I want to ask if it has a export function to delete this
![image](https://user-images.githubusercontent.com/13393433/77623235-b4e7ba00-6f7a-11ea-9f5f-2e9fbc88aa15.png)
I'm using mdx to avoid this. However, I have no idea to use functions.
For example, I have code here:
```
<Story>
{{
  template: '<button @click="clickHandler">button</button>'
}}
</Story>
```
where should I define clickHandler?
I'v tried to import js file but in template it can not read import js files.

**Comment by dragooncjw** [comment]
By the way, if I use like below, 
```
<Story>
  <Button onClick="clickHandler"></Button>
</Story>
```
It will show error 'Cannot add property _Ctor, object is not extensible'.

**Comment by shilman** [comment]
Which frameworks is that?

**Comment by dragooncjw** [comment]
The framework I used is Vue. I've tried JSX by using onClick. It didn't work. 
But I have found a solution on this url by mix stories.js and stories.mdx:  https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/recipes.md#mixed-csf--mdx-stories

However, I still want to know the reason cause the error 'error 'Cannot add property _Ctor, object is not extensible'.

**Comment by shilman** [comment]
In Vue, how about this:

```js
<Story>
{{
  template: '<button @click="clickHandler">button</button>'
  methods: {
    clickHandler: e => {
      e.preventDefault();
      console.log('hello');
    },
  },}}
</Story>
```

Or this:

```js
export const clickHandler = e => {
  e.preventDefault();
  console.log('hello');
}

<Story>
{{
  template: '<button @click="clickHandler">button</button>'
  methods: { clickHandler }
}}
</Story>
```

**Comment by dragooncjw** [comment]
Yes, it works! Thanks!!
Could I use data() , and other life cycle functions or hooks in '{{ }}'?

**Comment by dragooncjw** [comment]
I found that if I use `parameters: {
        notes: markdownNotes
      }`
in Story in Preview, the second time I visit Doc tag, It will disappear. Which is the same in other way. Is it a bug?

**Comment by shilman** [comment]
Late answer to your original question, but here are the docs for remixing docsPage:

https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/docspage.md#remixing-docspage-using-doc-blocks
