### ISSUE TITLE
Storybook + Angular doesn't work on IE11

### ISSUE THREAD

**Issue by avistheripper** [storybookjs/storybook#10221]
I have blank Angular 9 application and the latest version of Storybook installed, but after running 'npm run storybook', the errors occurs pointing at 
stories/Welcome.stories.ts
export const ToStorybook = function () {
  return {
    component: Welcome,
    props: {},
  }
};
Probably having issues related to es6, is there any workaround for this issue?
The problem is related only to IE11.

**Comment by shilman** [comment]
Gadzooks!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-alpha.35 containing PR #10377 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
