### ISSUE TITLE
Failed to construct 'URL': Invalid URL [6.0.0-alpha.29]

### ISSUE THREAD

**Issue by idbartosz** [storybookjs/storybook#10227]
**Describe the bug**
After updating from`6.0.0-alpha.6` to `6.0.0-alpha.29` Storybook freezes with spinning loader and shows an error message.

```
TypeError: Failed to construct 'URL': Invalid URL
    at getEventSourceUrl (vendors~main.cb19d1134e7321a2d4ff.bundle.js:9519)
    at PostmsgTransport.handleEvent (vendors~main.cb19d1134e7321a2d4ff.bundle.js:9467)
```

**Expected behavior**
Storybook should load stories as usual.

**Screenshots**
<img width="993" alt="Screen Shot 2020-03-27 at 08 47 43" src="https://user-images.githubusercontent.com/21260478/77734064-481b0100-7008-11ea-947b-efa3895a376d.png">

**System:**
Browsers: 
- Chrome 80.0.3987.149 (Official Build) (64-bit)
- Firefox 74.0 (64-bit)

```
Environment Info:

  System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
  Browsers:
    Chrome: 80.0.3987.149
    Firefox: 74.0
    Safari: 13.0.5
  npmPackages:
    @storybook/addon-actions: 6.0.0-alpha.29 => 6.0.0-alpha.29 
    @storybook/addon-docs: 6.0.0-alpha.29 => 6.0.0-alpha.29 
    @storybook/addon-knobs: 6.0.0-alpha.29 => 6.0.0-alpha.29 
    @storybook/addon-links: 6.0.0-alpha.29 => 6.0.0-alpha.29 
    @storybook/addon-storysource: v6.0.0-alpha.29 => 6.0.0-alpha.29 
    @storybook/addon-viewport: v6.0.0-alpha.29 => 6.0.0-alpha.29 
    @storybook/addons: v6.0.0-alpha.29 => 6.0.0-alpha.29 
    @storybook/react: v6.0.0-alpha.29 => 6.0.0-alpha.29 
    @storybook/source-loader: v6.0.0-alpha.29 => 6.0.0-alpha.29 
```

**Comment by idbartosz** [comment]
After some debugging I've found the issue. It's related to the way `src` attribute is obtained from `iframe` and after altering the returned value `'iframe.html?id=*&viewMode=story'` to `http://localhost:6006/iframe.html?id=*&viewMode=story` Storybook started to work as normal.

#### Root problem

`var src = frame.getAttribute('src')` returns source but it's stripped from base url and that's why `new URL(src)` throws an error.

```js
var src = frame.getAttribute('src') // 'iframe.html?id=*&viewMode=story'
new URL(src) // TypeError: Failed to construct 'URL': Invalid URL
```

#### Possible solution:

A. switch from `frame.getAttribute('src')` to just `frame.src`
```js
var src = frame.src // 'http://localhost:6006/iframe.html?id=*&viewMode=story'
```

B. pass additional base to URL constructor like `new URL(src, base)`
```js
var base = 'http://localhost:6006/'
var src = frame.getAttribute('src') // 'iframe.html?id=*&viewMode=story'
new URL(src, base)
```

**Comment by shilman** [comment]
Zoinks!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-alpha.30 containing PR #10228 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

**Comment by sarahbethfederman** [comment]
I'm experiencing this issue in 6.1.20, but only in the chrome console. Everything seems to be loading correctly otherwise

**Comment by shilman** [comment]
@sarahbethfederman Do you have a repro repo you can share?

**Comment by sarahbethfederman** [comment]
Ah nevermind, turns out it was a chrome extension 😅

**Comment by david-genger** [comment]
> Ah nevermind, turns out it was a chrome extension 😅

What extension? I have the same issue. Can figure out what extension to uninstall

**Comment by sarahbethfederman** [comment]
I think it was axe that was causing the issue, they did a big release recently I think
