### ISSUE TITLE
IE 11 - Object doesn't support property or method 'bind'

### ISSUE THREAD

**Issue by lukepolo** [storybookjs/storybook#10234]
**Describe the bug**
When opening IE 11 we get three errors  

![image](https://user-images.githubusercontent.com/2066668/77771188-c4b7da80-701c-11ea-8874-4b4ad70fd7e3.png)

**To Reproduce**
1. Use The Repository  (https://github.com/lukepolo/ie-11-storybook-bug)
2. npm run storybook
3. Open IE 11

This is a clean install using the setup for a storybook vue 

**Expected behavior**
To load storybook without errors in IE 11

**Code snippets**
https://github.com/lukepolo/ie-11-storybook-bug

**System:**
```
  System:
    OS: macOS 10.15.4
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
  Binaries:
    Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
    Yarn: 1.17.3 - ~/.nvm/versions/node/v10.15.0/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.0/bin/npm
  Browsers:
    Chrome: 80.0.3987.149
    Safari: 13.1
  npmPackages:
    @storybook/addon-actions: ^5.3.17 => 5.3.17 
    @storybook/addon-links: ^5.3.17 => 5.3.17 
    @storybook/addons: ^5.3.17 => 5.3.17 
    @storybook/vue: ^5.3.17 => 5.3.17 
```

**Additional context**
I believe this is a different issue than: 

https://github.com/storybookjs/storybook/pull/9942

I also tried adding a custom babelrc 

https://github.com/lukepolo/ie-11-storybook-bug/tree/babelrc

**Comment by afebbraro** [comment]
Hey all! I'm getting this error (Syntax issue) in IE11 with these packages. Might be related to this issue.

<img width="853" alt="Screen Shot 2020-03-30 at 9 58 33 AM" src="https://user-images.githubusercontent.com/2117593/77921002-30908200-726d-11ea-9a1a-0f8513e255be.png">

```
 "@storybook/addon-a11y": "^5.3.17",
    "@storybook/addon-docs": "^5.3.17",
    "@storybook/addon-google-analytics": "^5.3.17",
    "@storybook/addon-jest": "^5.3.17",
    "@storybook/addons": "^5.3.17",
    "@storybook/angular": "^5.3.17",
```

**Comment by lukepolo** [comment]
@afebbraro I disabled the dll that is provided with storybook, `start-storybook --no-dll -p 6006`.  Now I am getting a similar error to yours. 

It is inside the `react-popper-tooltip` library. I tried modifying the webpack config to something like this: 

```
        // rule 0 is the JS rule
	config.module.rules[0].include = [
		'/Users/luke/Code/work/ui-framework/src',
		'/Users/luke/Code/work/ui-framework/.storybook',
		'/Users/luke/Code/work/ui-framework/node_modules/react',
	];

	delete config.module.rules[0].exclude;
```

But it seems webpack doesn't pick up that the file needs to go through babel

**Comment by tvsbrent** [comment]
I just opened an issue in the react-popper-tooltip library about this. Version 2.10.1 of that library didn't have this problem, but version 2.11.0 does.

https://github.com/mohsinulhaq/react-popper-tooltip/issues/91

**Comment by lukepolo** [comment]
Yah, thats what I found, was trying to have babel still run through it, but for the life of me I could not get it to run through babel.

**Comment by tvsbrent** [comment]
Our team recently fought with that _a lot_ recently, as the most recent releases of Babel really, really don't want to go into your node modules folder. What my team mate did (who is a lot smarter than me), was the following:

* Converted to using a `babel.config.js` file.
* In that file, did something like this:
```
const notIgnoredFile = 'cheese.js';
module.exports = {
  ignore: [ filename => {
    if (filename.includes(notIgnoredFile)) {
      return false;
    }
    return filename.includes('node_modules');
  } ]
};

```

**Comment by shilman** [comment]
w00t!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-alpha.35 containing PR #10377 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
