### ISSUE TITLE
@storybook/addon-toolbars default value not working at initial render

### ISSUE THREAD

**Issue by smmoosavi** [storybookjs/storybook#10239]
**Describe the bug**
@storybook/addon-toolbars default value not working at initial render, if the page reloaded or start navigation from the story URL, the default value is not applied, after navigation between stories, the default value will be applied.

**To Reproduce**
scenario 1:
1. Go to a story that using `globalArgs`
2. reload page
3. globalArgs default values are not applied
4. navigate between stories and came back to the story
5. default value is applied

scenario 2:
1. Go to a story that using `globalArgs`
2. Copy page URL
3. In a new tab paste URL
4. globalArgs default values are not applied
5. navigate between stories and came back to the story
6. default value is applied

**Expected behavior**
`defaultValue` defined in `globalArgTypes` is respected in first render

**Code snippets**
```js
// main.js
module.exports = {
  stories: ['../src/**/*.stories.js'],
  addons: [
    '@storybook/preset-create-react-app',
    '@storybook/addon-storysource',
    '@storybook/addon-toolbars',
    '@storybook/addon-actions',
    '@storybook/addon-links',
  ],
};
```
```js
//preview.js
export const globalArgTypes = {
    locale: {
        name: 'Locale',
        description: 'Internationalization locale',
        defaultValue: 'en',
        toolbar: {
            icon: 'globe',
            items: [
                { value: 'en', right: '🇺🇸', title: 'English' },
                { value: 'fa', right: '🇮🇷', title: 'فارسی' },
            ],
        },
    },
}
```
```js
// story
import React from 'react';

export default {
  title: 'Locale',
};

export const Text = ({ globalArgs: { locale } }) => {
  console.log(locale);
  return <div>Hello {locale}</div>
};
```
**System:**
```
Environment Info:

  System:
    OS: Linux 4.15 Ubuntu 16.04.6 LTS (Xenial Xerus)
    CPU: (4) x64 Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
  Binaries:
    Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.14.1/bin/npm
  Browsers:
    Chrome: 80.0.3987.149
    Firefox: 74.0
```

**Additional context**
```
y list --depth 0 --pattern @storybook  
yarn list v1.22.4
├─ @storybook/addon-actions@6.0.0-alpha.29
├─ @storybook/addon-links@6.0.0-alpha.29
├─ @storybook/addon-storysource@6.0.0-alpha.29
├─ @storybook/addon-toolbars@6.0.0-alpha.29
├─ @storybook/addons@6.0.0-alpha.29
├─ @storybook/api@6.0.0-alpha.29
├─ @storybook/channel-postmessage@6.0.0-alpha.29
├─ @storybook/channels@6.0.0-alpha.29
├─ @storybook/client-api@6.0.0-alpha.29
├─ @storybook/client-logger@6.0.0-alpha.29
├─ @storybook/components@6.0.0-alpha.29
├─ @storybook/core-events@6.0.0-alpha.29
├─ @storybook/core@6.0.0-alpha.29
├─ @storybook/csf@0.0.1
├─ @storybook/node-logger@6.0.0-alpha.29
├─ @storybook/preset-create-react-app@2.1.1
├─ @storybook/react@6.0.0-alpha.29
├─ @storybook/router@6.0.0-alpha.29
├─ @storybook/source-loader@6.0.0-alpha.29
├─ @storybook/theming@6.0.0-alpha.29
└─ @storybook/ui@6.0.0-alpha.29

```

**Comment by skattabrain** [comment]
I'm seeing this as well using a global decorator using Vue. Also not seeing the variable updated after an option is selected, I have to view a different story to see the change.

**Comment by shilman** [comment]
@tmeasday global args appear to initialize to `{}` due to this line:

https://github.com/storybookjs/storybook/blob/next/lib/api/src/modules/globalArgs.ts#L20

On the other hand `storyStore._globalArgs` appears to be initialized properly. Getting the values from there into the `ManagerContext` should fix this issue. Any ideas?

**Comment by tmeasday** [comment]
Hmm, yeah we should probably just emit `GLOBAL_ARGS_UPDATED` at the same time as we emit `SET_STORIES` in the store. WDYT @shilman?

**Comment by shilman** [comment]
Shiver me timbers!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-beta.9 containing PR #10833 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
