### ISSUE TITLE
CSS Modules in MDX docs not working?

### ISSUE THREAD

**Issue by RazvanDH** [storybookjs/storybook#10238]
**Describe the bug**
Hey. I'm trying to implement the latest version of Storybook (5.3) into a pattern library using React and CSS Modules. I've been trying to get CSS Modules to work correctly but it does not want to apply the style no matter.

**To Reproduce**
1. have a CSS file (let's call it `CompA.module.css`)
```
@value sizeSM from 'styles/typography.css';
@value padding: 0.75rem;

.componentA { display: block; }
```

2. The style is imported in the React component like this:
```
import css from './CompA.module.css`
```

3. The styles are used like this:
```
const ComponentA = ({ children }) => (
  <div className={css.componentA} />
)
```

4. Building storybook with the default webpack config loads without any styles applied (does not add the classes on the element either) to `ComponentA`. Modifying webpack keeps showing different errors (ranging from the CSS file not being seen as a CSS file `Module parse failed: Unexpected character '@' (1:0)` to `style-loader` or `css-loader` failing to import things).

**Expected behavior**
When building, it should apply the classes on the HTML elements from the React component and compile the CSS for them as well

**Screenshots**
This is when trying to update the `config.module` from Webpack by forcing `module: true` in `css-loder`:
![image](https://user-images.githubusercontent.com/5197675/77785539-3f501c80-7054-11ea-8311-baf3c3476f0c.png)

**Code snippets**
If applicable, add code samples to help explain your problem.

**System:**
```
 System:
    OS: macOS Mojave 10.14.2
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.19.1 - ~/.yarn/bin/yarn
    npm: 6.14.2 - ~/.nvm/versions/node/v10.15.3/bin/npm
  Browsers:
    Chrome: 80.0.3987.149
    Firefox: 72.0.2
    Safari: 12.0.2
  npmPackages:
    @storybook/addon-a11y: ^5.3.14 => 5.3.17
    @storybook/addon-actions: ^5.3.14 => 5.3.17
    @storybook/addon-docs: ^5.3.14 => 5.3.17
    @storybook/addon-knobs: ^5.3.14 => 5.3.17
    @storybook/addon-links: ^5.3.14 => 5.3.17
    @storybook/addons: ^5.3.14 => 5.3.17
    @storybook/react: ^5.3.14 => 5.3.17
  npmGlobalPackages:
    @storybook/cli: 5.1.9
```

**Additional context**
The project is not using another webpack file. All I need to do is to document some raw React components that are imported in a different project.

**Comment by shilman** [comment]
do you have a repro repo?

**Comment by RazvanDH** [comment]
Hey @shilman. Thank you for your quick answer. I've put together a stripped down version of the project with the issue. I'm sure it's something easy, but I can't figure it out as my experience with Webpack isn't great: https://github.com/RazvanDH/storybook-css-modules-example

**Comment by RazvanDH** [comment]
@shilman, if you have some time, would you mind having a look at the example repo, please?

**Comment by RazvanDH** [comment]
I found the issue. What was happening was that `resolve -> alias` in Webpack wasn't working as expected for CSS and it was failing on importing the shared files (like typography).

For anyone interested, this is final Webpack config I used in `.storybook/main.js`:

```
const path = require('path')
const MiniCssExtractPlugin = require('mini-css-extract-plugin')

module.exports = {
  addons: ['@storybook/addon-docs/preset'],
  webpackFinal: async (config, { configType }) => {

    const newRules = config.module.rules.map(rule => {
      if(!rule.sideEffects) {
        return rule
      }

      return {
        test: /\.css$/,
        include: [
          path.resolve(__dirname, '../src'),
          path.resolve(__dirname, '.'),
        ],
        use: [
          MiniCssExtractPlugin.loader,
          {
            loader: 'css-loader',
            options: {
              importLoaders: 1,
              modules: {
                localIdentName: '[name]__[local]___[hash:base64:5]'
              },
            },
          },
          'postcss-loader',
        ],
      }
    })

    config.plugins.push(
      new MiniCssExtractPlugin({
        filename: '[name].[contenthash].css'
      })
    )

    const newAlias = {
      ...config.resolve.alias,
      './styles/screenSizes.css': path.resolve('./src/styles/screenSizes.css'),
      './styles/colors.css': path.resolve('./src/styles/colors.css'),
      './styles/typography.css': path.resolve('./src/styles/typography.css'),
      './styles/fonts': path.resolve('./src/styles/fonts'),
      './styles/vendor': path.resolve('./src/styles/vendor'),
    }

    config.stats = 'verbose'

    config.module.rules = newRules
    config.resolve.alias = newAlias

    return config
  },
}

```
