### ISSUE TITLE
Issue registering custom addon on alpha.29

### ISSUE THREAD

**Issue by matheo** [storybookjs/storybook#10241]
**Describe the bug**
I upgraded to `alpha.29` and my custom addon stopped working because `api.on` was not defined (it's an empty object that gets populated later, as the console.log shows a full object). I reverted back to `alpha.28` and it worked again.

```
// manager.js
import { addons } from '@storybook/addons';
import { STORIES_CONFIGURED, STORY_MISSING } from '@storybook/core-events';

addons.register('my-first-page', api => {
  api.on(STORIES_CONFIGURED, () => {
    if (api.getUrlState().path === '/story/*') {
      api.selectStory('Overview');
    }
  })
  api.on(STORY_MISSING, () => {
    api.selectStory('Overview');
  })
})
```

**Screenshots**

![image](https://user-images.githubusercontent.com/260185/77813685-7df7ce00-7078-11ea-9f15-603ff8cd5a9a.png)

**Additional context**
I got updates of `@babel/*@7.9.*`, `@mdx-js/*@1.5.8` and `@webassemblyjs/*@1.9.0` but I reverted those changes to be sure that only `@storybook/*` changes were the only ones in my package.json, and cleaned up with `npm ci`.

Looks like a race condition that delays the creation of the `api` object.

**Comment by shilman** [comment]
Boo-yah!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-alpha.30 containing PR #10254 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

**Comment by matheo** [comment]
Thanks @shilman 
FYI, https://www.npmjs.com/package/@storybook/addon-options didn't triggered the `alpha.30` release, that's normal?
