### ISSUE TITLE
Docs plugin is broken on ember example site

### ISSUE THREAD

**Issue by gabrielcsapo** [storybookjs/storybook#10249]
**Describe the bug**
<img width="1792" alt="Screen Shot 2020-03-29 at 10 59 06 AM" src="https://user-images.githubusercontent.com/1854811/77856493-6a4d8400-71ac-11ea-85de-7ef10c4a7fc4.png">

**To Reproduce**
1. Go to https://storybookjs.netlify.com/ember-cli/?path=/docs/addon-a11y--label

**Expected behavior**
To be unsupported or to not show up. The current error causes the docs to not work at all after.

**Comment by shilman** [comment]
cc @meirish @gossi

**Comment by shilman** [comment]
Hurrah!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-beta.22 containing PR #10490 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
