### ISSUE TITLE
Handle .babelrc file extensions

### ISSUE THREAD

**Issue by stefanprobst** [storybookjs/storybook#10244]
**Describe the bug**
Storybook currently does not seem to handle `.babelrc` files with a file extension, e.g. `.babelrc.json`.
It looks like this is hardcoded here: https://github.com/storybookjs/storybook/blob/fb9813e79398c5d21a6a84d1ecef95c40cf53616/lib/core/src/server/utils/load-custom-babel-config.js#L87

**Expected behavior**
All supported file extensions (see [here](https://babeljs.io/docs/en/config-files#supported-file-extensions)) should be handled by storybook.

**Comment by shilman** [comment]
@stefanprobst can you contribute a fix?
