### ISSUE TITLE
Possibity to exclude Stories from the Menu

### ISSUE THREAD

**Issue by matheo** [storybookjs/storybook#10248]
**Is your feature request related to a problem? Please describe.**

Right now I'm trying to figure out how the `Designers` can have a clean `Docs` page with their stuff, and not dealing with `Developers` specifications of the `Canvas` page.

Turns out that the current approach of Storybook with MDX seems to integrate the Developer specs as a Table component inside the custom `Docs`, but I'd like to have it only in the `Canvas`  tab.

**Describe the solution you'd like**

What it comes to my mind is to remove some stories from the Menu, so I only show the ones with Dev Specs that have a Canvas view. The hidden ones will be used manually in the custom MDX file.

This is not ideal solution but may work when we have custom Stories that we want to manipulate manually in the docs, and showing them in the Menu is just confusing.

**Are you able to assist bring the feature to reality?**
no, I'm getting familiar with the system and it's being a little hard because I'm an Angular dev.

**Comment by shilman** [comment]
I'm closing this as a duplicate to #9209 

Your use case is interesting. Can you use something like addon-notes to achieve it? So your spec goes in notes, is available in the addons panel using `registerPanel`, and is kept separate from the docs?

**Comment by matheo** [comment]
Indeed, it's a duplicate! It would be awesome to have that for v6.0.0, please :)

**Comment by matheo** [comment]
And yes, I think that the spec will need to be inside a Panel :)
