### ISSUE TITLE
Possibility to define CSF Stories in different files

### ISSUE THREAD

**Issue by matheo** [storybookjs/storybook#10247]
**Is your feature request related to a problem? Please describe.**

Right now the [CSF Format Guide](https://storybook.js.org/docs/formats/component-story-format/) is clear about the possibilities to export stories, but the only alternative it offers is to export all the stories on the same single file.

**Describe the solution you'd like**

It would be nice to have the possibility to add Stories from multiple files, like:

I have the `tabs.stories.ts` with the CSF metadata, and no stories:
```
import { moduleMetadata } from '@storybook/angular';
import page from 'design-system/components/tabs.docs.mdx';

// components story metadata
export default {
  id: 'layout-tabs',
  title: 'Components / Tabs',
  componentSubtitle: null,
  decorators: [
    moduleMetadata({ imports: [LayoutModule] }),
  ],
  parameters: {
    docs: { page },
  },
};
```

Then from the components subfolders, I'd like to be able to add Stories, and right now it seems possible using the `storiesOf` API, but it doesn't respect the CSF Metadata.

In the CSF Metadata I'm trying to override the `docs` page, and it's not working. So it's probable that one of the components `storiesOf` file is being loaded first, and it's defining the Story without the override.

**Are you able to assist bring the feature to reality?**
no, I'm not familiar enough with the way Storybook does its stuff, I'm starting to understand tho :)

**Comment by shilman** [comment]
Unfortunately all `storiesOf` files load before all CSF/MDX files, due to an implementation gotcha.

What are you trying to achieve?

I don't think this is what you're looking for but FYI it's currently possible to load CSF stories for the same component in different files:

### CompA.stories.js
```js
export default { title: 'Comp' };
export const A = () => <Comp prop='A' />
```

### CompB.stories.js
```js
export default { title: 'Comp' };
export const B = () => <Comp prop='B' />
```

**Comment by matheo** [comment]
@shilman thanks for the fast answer.

So maybe I've been misunderstanding the CSF format, and I thought the default export could be defined once for all the Stories under the title, but now I see that it's just a matter format, it's not like the code I'm used to :)

Thanks for the great stuff!

**Comment by matheo** [comment]
Now I kinda understand that I have to override the DocsPage for all the stories right?
they act like units even if they "share" the Docs page, they implement it individually

**Comment by shilman** [comment]
You can override the DocsPage once globally in `.storybook/preview.js` if it helps:

```js
import { addParameters } from '@storybook/client-api'; // or your framework
addParameters({
  docs: { page: MyCustomPage },
});
```

**Comment by matheo** [comment]
@shilman but I'm customizing that per-category with an MDX file tho.

BTW, can we `Preview` in the MDX something else like a Figma file?
I see that the Design Specs can have some stuff that is not replicable sometimes (like instruction) and it would be nice to be able to show their stuff in the MDX, while in the Stories we show the Component Behavior in the Canvas tab.

**Comment by shilman** [comment]
@matheo I would recommend one of two different strategies. Both use custom DocBlocks. I will be writing more about custom DocBlocks as part of the 6.0 release. They are just React components with a little bit extra. For the purposes of this issue, let's assume that you have an `DesignPreview` block that takes a URL as its parameter:

```
<DesignPreview url="https://figma.com/path/to/design" />
```

If you are using MDX, you can just drop this in directly into your file, and that's the simplest way to do it.

If committed to using CSF, I would instead define a custom docs page like I described in the comment above. [More detail here](https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/docspage.md#remixing-docspage-using-doc-blocks)

Globally:

```ks
addParameters({
  docs: { page: page: () => (
    <>
      <Title />
      <Subtitle />
      <Spec />
      ...
    </>
  )},
});
```

Per component:

```js
export default {
  title: 'MyComponent'
  parameters: {
    spec: {
      designUrl: 'https://figma.com/path/to/design'
    }
  }
}

export const Story1 = ...
```

The `Spec` custom DocBlock would read the `designUrl` from the component's parameters and pass it into `DesignPreview`

**Comment by matheo** [comment]
@shilman I love the `<DesignPreview url="https://figma.com/path/to/design" />` component to be placed one or multiple times inside the custom MDX docs page, I will need that one :)

And about this ticket, it's clear to me now that each Component Story of my system must have its default export, and decorators, and trying to merge that into a single file just complicates the things on my case.

Thank you very much for your help!
