### ISSUE TITLE
Something in Storybook's default Babel config causes ReferenceError (tdz) errors

### ISSUE THREAD

**Issue by vdh** [storybookjs/storybook#10250]
With some Typescript code like this example:
```ts
const Column: FC<ColumnProps> = ({
	cards = [],
  /* … */
}) => {
  /* … */
  return (
    {/* … */}
      <CardList
        cards={cards}
      />
    {/* … */}
  );
};
```
Will get compiled normally by Babel into:
```js
const Column = (_ref) => {
  let {
    cards = [],
    /* … */
  } = _ref;
  /* … */
  react__WEBPACK_IMPORTED_MODULE_1___default.a.createElement(_CardList__WEBPACK_IMPORTED_MODULE_24__["default"], {
    cards: cards,
    /* … */
  })
};
```

But under the default Storybook babel setup, gets compiled into:

```js
const Column = (_ref) => {
  var _ref3 =
  /*#__PURE__*/
  react__WEBPACK_IMPORTED_MODULE_1___default.a.createElement(_CardList__WEBPACK_IMPORTED_MODULE_24__["default"], {
    cards: cards,
    /* … */
  });

  let {
    cards = [],
    /* … */
  } = _ref;
  /* … */
};
```

And creates a `ReferenceError` error because the `React.createElement` call is moved higher than the `let`, so it's trying to use `cards` too early.

But I can't figure out how to debug this to find out which Babel plugin or config is doing this broken `var` / `let` interaction.

**Comment by shilman** [comment]
Can you create a minimal repro?

**Comment by vdh** [comment]
@shilman I haven't had time to put together one yet. Until I have time to create a full repro, I suspect this is due to `@babel/plugin-transform-react-constant-elements`, because the error is happening when JSX is being hoisted above `let` statements.

**Comment by vdh** [comment]
After patching Storybook's Webpack config for `babel-loader` to exclude `@babel/plugin-transform-react-constant-elements`, the code runs normally again. I had to jump through some hoops of assumptions about the config to patch it out though.

I couldn't find an exact issue in the Babel repo that relates directly to what I encountered, but the plugin seems to have a history of being buggy, e.g.: https://github.com/facebook/create-react-app/issues/553

The closest I could find was https://github.com/babel/babel/issues/4419 which seems to have a PR, but that PR hasn't been shipped as far as I can tell (and isn't referenced from any release notes I checked).

**Comment by vdh** [comment]
@shilman So what exactly is the reason why Storybook includes `@babel/plugin-transform-react-constant-elements` by default anyway? Why is an optimisation plugin bundled by default? It changes the way the user's code is executed, and has plenty of demonstrable flaws.

**Comment by shilman** [comment]
@vdh i'm not sure, but maybe @ndelangen knows

**Comment by ndelangen** [comment]
Let's remove the plugin!

Would anyone be able to open a PR removing it?

**Comment by Pyrolistical** [comment]
the plugin was removed in https://github.com/storybookjs/storybook/pull/11086
