### ISSUE TITLE
Storybook for Angular and Angular Material 9

### ISSUE THREAD

**Issue by vorant94** [storybookjs/storybook#10253]
I am using the Storybook a little time for my projects which are heavily based on Angular Material and it works really nice. But recently I updated the Angular and also Angular Material to 9 version and Storybook doesn't load the styles or something like this any more. I have no clue what happens under the hood, so I appreciate if you ask some suggestive questions so I can tell you more. Here is the screenshot which are showing the difference before and after ng9

![Screen Shot 2020-03-30 at 10 55 43](https://user-images.githubusercontent.com/9719319/77889130-0d1e0500-7276-11ea-9220-b6e870ef9bfd.png)

![Screen Shot 2020-03-30 at 10 53 52](https://user-images.githubusercontent.com/9719319/77889195-2a52d380-7276-11ea-980c-df8e1b882d2d.png)

**Comment by Korsche09** [comment]
I have the same Problem ist ther any Solution @vorant94 ?Would be glad if  you solved tha problem by now

**Comment by vorant94** [comment]
> I have the same Problem ist there any Solution @vorant94 ?Would be glad if  you solved tha problem by now

I haven't fount one... just stopped to use storybook😢
