### ISSUE TITLE
@storybook/addon-backgrounds not working with Vue

### ISSUE THREAD

**Issue by gesseekur** [storybookjs/storybook#10275]
**Describe the bug**
I am trying to add @storybook/addon-backgrounds to my vue storybook project and it is not working. 

I followed the exact steps here: 
https://www.npmjs.com/package/@storybook/addon-backgrounds

and also manually installed all the dependencies (not sure if that was required) and it still is not working for me. 

**Expected behavior**
I was expecting the background color of my specific story to change.

**Screenshots**
<img width="1404" alt="Screen Shot 2020-03-31 at 1 11 45 PM" src="https://user-images.githubusercontent.com/13419784/78070801-45464600-7351-11ea-83b7-efc49aa28fc9.png">

**Code snippets**
this is my code snippet for my story: 
```
import Primary from "./Primary";
import Basic from "./Basic";
import Error from "./Error";
import Secondary from "./Secondary";
import White from "./White";
import Disabled from "./Disabled";

export default {
  title: "MewButton"
};

export const PrimaryTheme = () => Primary;
export const BasicTheme = () => Basic;
export const ErrorTheme = () => Error;
export const SecondaryTheme = () => Secondary;
export const WhiteTheme = () => White;
export const DisabledTheme = () => Disabled;

WhiteTheme.story = {
  parameters: {
    backgrounds: [{ name: "dark background", value: "#FF0000", default: true }]
  }
};
```

and this is my main.js

```
module.exports = {
 stories: ['../stories/**/*.stories.js'],
 addons: ['@storybook/addon-actions', '@storybook/addon-links', '@storybook/addon- 
 backgrounds/register'],
};```


**System:**
after running npx -p @storybook/cli@next sb info: 
```/Users/jessicapeng/.npm/_npx/79550/lib/node_modules/@storybook/cli/node_modules/fs-extra/lib/mkdirs/make-dir.js:86
      } catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/jessicapeng/.npm/_npx/79550/lib/node_modules/@storybook/cli/node_modules/fs-extra/lib/mkdirs/index.js:3:44)
```

Any help is appreciated. Thank you! I've been trying to get this work for days.

**Comment by shilman** [comment]
Can you share a reproduction repo?

**Comment by gesseekur** [comment]
@shilman  Hello, this is the repo I am currently working on: https://github.com/MyEtherWallet/mew-components

**Comment by shilman** [comment]
What I did:
1) rename config.js to `preview.js`
2) delete the following code which is redundant with `main.js`:
```js
const req = require.context('../stories', true, /.stories.js$/);
function loadStories() {
  req.keys().forEach(filename => req(filename));
}

configure(loadStories, module);
```
3) add some background configuration code:
```
addParameters({
  backgrounds: [
    { name: "light", value: "#eeeeee" },
    { name: "dark", value: "#222222" }
  ]
});
```

At this point the backgrounds icon is showing up and I can toggle the background. However, your stories are configured to obscure the background, so I couldn't easily test it out.

**Comment by gesseekur** [comment]
@shilman awesome thank you, I do see the options now! I did comment out the css I used to change the background color as well as the theme I was using and it still does not work. Any ideas? 

Thanks again!

**Comment by gesseekur** [comment]
@shilman these are my changes: https://github.com/MyEtherWallet/mew-components/pull/10/files

**Comment by gesseekur** [comment]
@shilman I found the culprit - it was done by one of my colleagues :) thank you so much!

**Comment by gesseekur** [comment]
never mind ..that wasn't it.

**Comment by shilman** [comment]
Awesome, glad to hear you got it working! 💯
