### ISSUE TITLE
Add ability to reset the styles of the Preview component to preserve documentation-only mdx files

### ISSUE THREAD

**Issue by tsnolan23** [storybookjs/storybook#10273]
**Is your feature request related to a problem? Please describe.**
Yes. There is no way to have a documentation-only MDX file with the styles reset since `Story` is the only component that resets the styles of its children. For it to remain a documentation-only file, it cannot contain a `Story`.

**Describe the solution you'd like**
I propose a prop on the `Preview` component, such as `resetStyles?: boolean` that would reset the styles of the children of the `Preview` component as the `Story` component currently does

**Describe alternatives you've considered**
Initially stumbled upon this thread:
https://github.com/storybookjs/storybook/issues/9630
However, that doesn't really preserve the ability to have documentation-only mdx files

**Are you able to assist bring the feature to reality?**
Yes

**Additional context**
Not applicable

**Comment by shilman** [comment]
Gadzooks!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-alpha.41 containing PR #10274 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
