### ISSUE TITLE
Storybook unable to resolve model when used to declare angular component input type

### ISSUE THREAD

**Issue by danverde** [storybookjs/storybook#10293]
**Describe the bug**
Storybook is unable to resolve a model imported from a library when used to define the type of an Angular component `@Input` property.

**To Reproduce**
1. Import an interface from a library
2. Use that interface to declare the type of a component's input property
3. Start storybook 

**Expected behavior**
The Storybook should be able to resolve the model & the project should build successfully.

**Screenshots**
This is the error:
<img width="1259" alt="Screen Shot 2020-04-02 at 10 29 03 AM" src="https://user-images.githubusercontent.com/19293059/78274019-d42b9d80-74cc-11ea-99c4-4ad2f28f416a.png">

**Code snippets**
```
import { IScore } from '@stukent/mimic-core/lib/models/scoring';

@Component({
  selector: 'lib-purchase-research-report',
  templateUrl: './purchase-research-report.component.html',
  styleUrls: ['./purchase-research-report.component.scss']
})
export class PurchaseResearchReportComponent {

  @Input() score: IScore; // unable to resolve '@stukent/mimic-core/lib/models/scoring'
  score: IScore; // works just fine

}
```

**System:**
Using Angular 9.1.0
System:
    OS: macOS 10.15.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Binaries:
    Node: 12.16.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 80.0.3987.162
    Firefox: 73.0
    Safari: 13.1

**Comment by kroeder** [comment]
Hey, 

does your `.storybook/tsconfig.json` extend your root tsconfig that declares your tsconfig paths?

**Comment by danverde** [comment]
Yes it does
