### ISSUE TITLE
addon-docs Source component does not return source when no props provided 

### ISSUE THREAD

**Issue by idbartosz** [storybookjs/storybook#10308]
**Describe the bug**
Source component from `@storybook/addon-docs/blocks` doesn't return source when no props provided.

**To Reproduce**
Use Source component from addon-docs in custom Preview component.

**Expected behavior**
Should render source for the current story as described in comments:
https://github.com/storybookjs/storybook/blob/c8c0a7f6634dbf2358653bcb44b0892523bf2216/addons/docs/src/blocks/Source.tsx#L85-L88

**Screenshots**
<img width="1020" alt="Screen Shot 2020-04-03 at 23 15 00" src="https://user-images.githubusercontent.com/21260478/78405560-0807df80-7601-11ea-9205-45f0e1f55ed4.png">

**System:**
```
Environment Info:
  System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
  Browsers:
    Chrome: 80.0.3987.149
    Firefox: 74.0
    Safari: 13.0.5
  npmPackages:
    @storybook/addon-actions: v6.0.0-alpha.6 => 6.0.0-alpha.6 
    @storybook/addon-docs: v6.0.0-alpha.6 => 6.0.0-alpha.6 
    @storybook/addon-info: 5.3.12 => 5.3.12 
    @storybook/addon-knobs: v6.0.0-alpha.6 => 6.0.0-alpha.6 
    @storybook/addon-links: v6.0.0-alpha.6 => 6.0.0-alpha.6 
    @storybook/addon-notes: ^5.3.12 => 5.3.18 
    @storybook/addon-storysource: v6.0.0-alpha.6 => 6.0.0-alpha.6 
    @storybook/addon-viewport: v6.0.0-alpha.6 => 6.0.0-alpha.6 
    @storybook/addons: v6.0.0-alpha.6 => 6.0.0-alpha.6 
    @storybook/react: v6.0.0-alpha.6 => 6.0.0-alpha.6 
    @storybook/source-loader: v6.0.0-alpha.6 => 6.0.0-alpha.6 
```

**Comment by idbartosz** [comment]
Problem is with condition on line 66. When no props are passed (e.g. `<Source />`) then 
1. `targetId` value is obtained from ternary condition
2. condition `singleProps.id === CURRENT_SELECTION` is evaluated to `false` 
3. assigned value is `singleProps.id` which is equal to `undefiled`. 

For the scenario with self closing `<Source />` value assigned to `targetId` should equal to the `currentId` obtained from context.

https://github.com/storybookjs/storybook/blob/c8c0a7f6634dbf2358653bcb44b0892523bf2216/addons/docs/src/blocks/Source.tsx#L66

**Comment by shilman** [comment]
w00t!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-beta.1 containing PR #10619 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
