### ISSUE TITLE
Hierarchy order

### ISSUE THREAD

**Issue by ton03** [storybookjs/storybook#10306]
**Is your feature request related to a problem? Please describe.**
I would prefer to have an option to set an order of the story hierarchies. In the case of the demo site, I may want to see "Basics" first, then "UI", etc.

**Describe the solution you'd like**
Set the order via `manager.js`?
```
hierarchyOrder: ['Basics', 'UI', ...], // manual
```
or
```
hierarchyOrder: true, // auto; alphabetical
```
the rest that are not mentioned would be rendered in whatever order they are rendered now.

It could default to a falsy value so storybook won't sort it

**Describe alternatives you've considered**
Something similar to `storySort`
```
addParameters({
  options: {
    hierarchySort: ...
  },
});
```

**Are you able to assist bring the feature to reality?**
I can give it a shot... 😅 

**Additional context**
This would be useful to set a logical order of hierarchy in a Design System

**Comment by shilman** [comment]
You can currently achieve this by simply loading your stories in the desired order in `main.js`:

```js
module.exports = {
  stories: [
    'Basics.stories.js',
    'UI.stories.js'
    ...
  ]
}
```

There's also an options argument to `StorySort` that basically does what you're asking for: https://github.com/storybookjs/storybook/pull/9188

**Comment by ton03** [comment]
Hi @shilman thanks for that but I don't think the default `storySort` function works well with hierarchy and custom separators. Should it also consider `hierarchySeparator` and `hierarchyRootSeparator`?

https://github.com/storybookjs/storybook/blob/next/lib/client-api/src/storySort.ts#L18

But here's my solution
```
storySort: (a, b) => {
  const getIndex = (s) => (
    ['Widgets', 'UI', 'Charts', 'Pages']
      .findIndex((story) => s.startsWith(story))
  );
  return getIndex(a[1].kind) > getIndex(b[1].kind) ? 1 : 0;
},
```

**Comment by shilman** [comment]
@ton03 hierarchy separators are deprecated as of 5.3 and will be removed in 6.0

**Comment by StephanBijzitter** [comment]
@shilman what's the alternative to `hierarchySeparator` in that case? I just updated (for the require.requireActual bugfix), and I cannot really find any information on this change (yet)

**Comment by shilman** [comment]
https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#removed-hierarchy-separators
