### ISSUE TITLE
Add way to remove nesting when using CSF

### ISSUE THREAD

**Issue by Albert-Gao** [storybookjs/storybook#10309]
A CSF like following.

```javascript
import React from 'react'
import { MyButton } from '../components/MyButton'
import { StorybookStack } from './storybookUtils'

export const Button = () => <MyButton> ok </MyButton>

export default {
  title: 'Button',
  component: MyButton
}
```

will generate a structure like this

![image](https://user-images.githubusercontent.com/18282328/78414050-c285f980-7676-11ea-824e-d52cdcb1a9d6.png)

It would be helpful to remove the nesting, so the named export `Button` in the csf can be displayed as a root. Thanks

Or it is already supported? But I went through the documentation multiple times, can not find it. Thanks

**Comment by shilman** [comment]
@Albert-Gao no, that's not supported. however if you run storybook with `addon-docs` in `--docs` mode it collapses the navigation.

**Comment by shilman** [comment]
Closing as dupe to #8255
