### ISSUE TITLE
Errors in angular.json should lead to non-zero exit code

### ISSUE THREAD

**Issue by jeroenheijmans** [storybookjs/storybook#10303]
When I run `build-storybook` in an Angular application, I expect it to exit with `1` (or some non-zero code) when the `angular.json` file is incorrect, just as you'd get nonzero exit code for errors in your stories.

To reproduce:

1. Run `ng new foo`
2. Folllow https://storybook.js.org/docs/guides/guide-angular/ (manual steps, I don't use `npx` here)
3. Add `"storybook-ci": "build-storybook"` to `package.json`
4. Add a trailing comma in your `angular.json` file somewhere (this is _technically_ invalid in json)
5. For reference, run `ng build` and see it succeed (apparently it treats json as js, thus allowing the trailing comma?)
6. Run `npm run storybook-ci`

Then:

- **Result:** this fails, but with exit code 0 (I'm in Powershell, and check with `$LASTEXITCODE`)
- **Expected:** failure, but with `$LASTEXITCODE` `1` or some nonzero code

See also:

![shell output for the above](https://user-images.githubusercontent.com/1590536/78359321-2942de80-75b5-11ea-8213-546e29b4bb2a.png)

**Comment by shilman** [comment]
@jeroenheijmans any interest in contributing a fix?

**Comment by jeroenheijmans** [comment]
I.... would be, but it is [rather daunting to contribute](https://github.com/storybookjs/storybook/blob/next/CONTRIBUTING.md) for a newcomer, especially since this bug will be about interaction of multiple tools and parts. So on the short term I might not be able to do so, and fully appreciate that others also have limited time and this bug may sit unresolved until then.

Thx to all those that do contribute, for a great project!
