### ISSUE TITLE
The order of addon panels doesn't match main.js configuration

### ISSUE THREAD

**Issue by tajo** [storybookjs/storybook#10312]
**Describe the bug**
It seems that the order of addon panels is somewhat arbitrary.

**To Reproduce**

main.js:

```js
module.exports = {
  addons: [
    "@storybook/addon-a11y",
    "@storybook/addon-actions",
    "@storybook/addon-knobs",
    "@storybook/addon-links",
    "@storybook/addon-viewport"
  ],
}
```

**Expected behavior**
Should see 3 panels in this order:

1. Accessibility
2. Actions
3. Knobs

Instead, I get:

1. Knobs
2. Accessibility
3. Actions

Not sure where this order comes from. Is there some other way how to control it? Thanks.

**Comment by shilman** [comment]
Closing as dupe to #9819
