### ISSUE TITLE
Notes addon link doesn't work

### ISSUE THREAD

**Issue by Donghoon759** [storybookjs/storybook#10314]
**Describe the bug**
stories with Markdown notes using parameters in the Notes addon link doesn't work.
https://github.com/storybookjs/storybook/tree/next/addons/notes

**Comment by shilman** [comment]
What's linking to this?

**Comment by Donghoon759** [comment]
https://storybook.js.org/docs/basics/writing-stories/
------------------------------------------------------------------------------------------------
Parameters
Parameters are custom metadata for a story. Like decorators, they can also be hierarchically applied: globally, at the component level, or locally at the story level.

Here’s an example where we are annotating our stories with Markdown notes using parameters, to be displayed in the Notes addon.
------------------------------------------------------------------------------------------------
The link is linked on "Notes addon"

**Comment by shilman** [comment]
Thanks @Donghoon759. Will rewrite that soon!

**Comment by Donghoon759** [comment]
Very nice!
Sorry for poor issue format :(
