### ISSUE TITLE
Reuse existing tab if possible

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#10328]
**Is your feature request related to a problem? Please describe.**
Whenever I am making changes to configuration files (e.g. adding a new addon) or just leaving tabs open because I forgot them open, I end up in a situation like this as result of running storybook multiple times:
![image](https://user-images.githubusercontent.com/1671563/78577918-14717f80-782f-11ea-9617-d131b1f6c2f5.png)

It's a bit frustating.

**Describe the solution you'd like**
Would be nice if it could reuse an existing tab.

**Are you able to assist bring the feature to reality?**
Sure thing, it's on the way 🚀

**Comment by shilman** [comment]
Gadzooks!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-alpha.34 containing PR #10329 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.
