### ISSUE TITLE
Publish Storybooks on a lab

### ISSUE THREAD

**Issue by sali1982** [storybookjs/storybook#10323]
Hi All,

I looked at the documentation, I cannot find out how we can run the storybooks on a live lab.
I know these are tests, but our Product owners and manager want to see it on a running lab to see our fetures.

I am thinking the way would be instead of npm start, we need to do: start-storybook on the running app and that should just work?

**Comment by sali1982** [comment]
No one answers this?

**Comment by shilman** [comment]
Chromatic will be launching a service for this soon. https://blog.hichroma.com/chromatic-2-0-beta-3bf9172b6a4

**Comment by sali1982** [comment]
https://storybook.js.org/docs/basics/exporting-storybook/
