### ISSUE TITLE
Stories glob doesn't work as expected

### ISSUE THREAD

**Issue by valerybugakov** [storybookjs/storybook#10322]
**Expected Behavior**
Using glob `**/*.stories.tsx` should match all files ending with `.stories.tsx` in all subdirectories.

**To Reproduce**
Use glob in storybook config `**/*.stories.tsx`
Notice that stories located in folders that have the same suffix `*.stories` won't load into a storybook.

**Additional context**
The root of the issue is hidden in [to-require-context.js](https://github.com/storybookjs/storybook/blob/b6136e1539c85d253504391a7d3f65e2c1239143/lib/core/src/server/preview/to-require-context.js). After the last modification of the generated regex:
```js
.replace(/\?:\^/g, '?:')
```
Regex stops working correctly in the described case. Minimal [example](https://codesandbox.io/s/storybook-glob-issue-cue8q) on codesandbox. 

What's the purpose of the last replacement?

**Comment by ndelangen** [comment]
@valerybugakov I don't know anymore what `.replace(/\?:\^/g, '?:')` is supposed to do/fix.

It seems we should just never try to match relative paths to the regex to me.

**Comment by valerybugakov** [comment]
@ndelangen can you clarify about relative paths? 

As far as I understand the relative prefix is added by Webpack and generated regex is changed respectively because of that. The issue that I'm facing is caused by `.replace(/\?:\^/g, '?:')` replacement.

**Comment by ndelangen** [comment]
If the filepath is always ansolute then we can do just this:
https://codesandbox.io/s/storybook-glob-issue-hb3ox

**Comment by valerybugakov** [comment]
File-path is not absolute because of Webpack. 
Regex is used later in [require-context](https://github.com/storybookjs/storybook/blob/b6136e1539c85d253504391a7d3f65e2c1239143/lib/core/src/server/preview/to-require-context.js#L29) expression. See comment [here](https://github.com/storybookjs/storybook/blob/b6136e1539c85d253504391a7d3f65e2c1239143/lib/core/src/server/preview/to-require-context.js#L11).

**Comment by ndelangen** [comment]
So I think that's the main issue, where the regex created from `micromatch` only matches absolute filepaths, and we're trying to make it match relative paths.
And that regex conversion is buggy.

@valerybugakov Do you have a fix? A PR would be immensely welcome!

**Comment by valerybugakov** [comment]
@ndelangen yep, the fix is to remove the second replacement. But I don't understand the purpose of this part of the conversion, so it's not save until we know why it was added. Maybe @Hypnosphi can shed some light on it as the author of [this line](https://github.com/storybookjs/storybook/blob/b6136e1539c85d253504391a7d3f65e2c1239143/lib/core/src/server/preview/to-require-context.js#L13)?

**Comment by ndelangen** [comment]
I think @Hypnosphi just moved the code.

**Comment by valerybugakov** [comment]
Seems like it was changed by @Hypnosphi from the other replacement [here](https://github.com/storybookjs/storybook/commit/54a1c0c5f6e6cb9ca078c884c45447b95fada29f#diff-b2967ea5bba766646d93fe3653239d67L35).

**Comment by ndelangen** [comment]
@valerybugakov let's remove the extra replacement, add some tests, and see how that affect things.

**Comment by valerybugakov** [comment]
Fixed in https://github.com/storybookjs/storybook/pull/10400

**Comment by shilman** [comment]
Whoopee!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-alpha.34 containing PR #10400 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.
