### ISSUE TITLE
Handling prettier dependency properly

### ISSUE THREAD

**Issue by sebarthel89** [storybookjs/storybook#10339]
**Problem description**
We are using storybook's source loader as a dependency in our project. We realized, that there is a dependency to prettier that conflicts with our own prettier version.

Usually, handling multiple package versions in a project is possible but it still creates annoying issues. Internally, we migrated to prettier v2 that comes transitively from our own configuration package and we are still using a storybook version that uses prettier v1. 

_dependency chain example_:

custom-configuration-package  -- depends on --> prettier v2
storybook                                      -- depends on --> prettier v1

Due to internal npm package resolving priorities, the source-loader prettier version is put on the top level, that is v1 and that will be used for general prettier formatting tasks.

I am curious about a general solution for this. I know, the current github version uses already v2. Still, this issue will be relevant again as soon as new breaking changes come up.

**Our current workaround**

We define in our project added an explicit prettier version to make sure, the top level prettier version is v2.

**Describe the solution you'd like**
I am not 100% sure about this, and I would love to get your opinions on that. My feeling is that, having a non-formatting related dependency to prettier feels a bit wrong. Usually, you should not have formatting dependencies in your real dependencies because it might cause issues on packages that depend on it. This causes our formatting requirements to fail. 

I think there is only 1 usage that is about abstract syntax tree parsing. Still, maybe there is a solution not using prettier for it.

**Describe alternatives you've considered**
Maybe there are approaches using peer dependencies for configuration packages like ours to enforce clients of this package to define the dependency explicitly.

**Are you able to assist bring the feature to reality?**
Sure, but first I would like to get some different perspectives on it.

**Comment by shilman** [comment]
closing as dupe to #10192
