### ISSUE TITLE
Storybook Composition styling QA/polish

### ISSUE THREAD

**Issue by domyen** [storybookjs/storybook#10340]
This issue tracks user interface QA on Storybook Composition. Previously discussed with @mrmckeb @shilman in the monthly maintainers meeting.

- Ensure styling matches design
- Code review for styling
- Test styling in different cases (wide/narrow sidebar, mobile view, dark/light themes etc.)

[Link to design in InVision](https://invis.io/SEWAH6E43RZ)

**Comment by shilman** [comment]
Yee-haw!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-alpha.42 containing PR #10504 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
