### ISSUE TITLE
Remove configurable path separator for 6.0

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#10346]
In Storybook 5.3 we added simplified hierarchy separators: https://github.com/storybookjs/storybook/pull/8796

In 6.0 we should make that the default, and consider removing the configuration logic across the codebase.

**Comment by shilman** [comment]
@tmeasday suggests, moving showRoots to manager side config since we don't need it in preview anymore

**Comment by shilman** [comment]
Gadzooks!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-beta.38 containing PR #11344 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by tgelu** [comment]
> This proposed change would reduce that list of "reserved" characters to 1 ('/') which I think is not too bad.

Was there a lot of pushback on this? I find myself surprised that I can't add a `/` in a title. Especially when documenting namespaced packages.

Is it really that the only solution is to use a homoglyph?
