### ISSUE TITLE
Objects are not valid as a React child when not using backticks after .attrs

### ISSUE THREAD

**Issue by MelMacaluso** [storybookjs/storybook#10350]
I tried to search the docs, asked StackOverflow and searched the issues but I didn't come up with a satisfactory answer (maybe is me doing something silly ahah). 

Context:
```
    "styled-components": "^5.0.1",
    "@babel/core": "^7.9.0",
    "@storybook/addon-actions": "^5.3.18",
    "@storybook/addon-knobs": "^5.3.18",
    "@storybook/addon-links": "^5.3.18",
    "@storybook/addons": "^5.3.18",
    "@storybook/preset-create-react-app": "^2.1.1",
    "@storybook/react": "^5.3.18",
    "babel-loader": "^8.1.0",
    "css-loader": "^3.5.0",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "sass-loader": "^8.0.2",
    "style-loader": "^1.1.3"
```

I have the following simple `styled-component`:

```js
const Button = styled.bytton.attrs(({primary}) => ({
  className: primary ? 'something' : 'something-else'
})
```

Now for some reason unless I append the backticks in the ed such as:

```js
const Button = styled.bytton.attrs(({primary}) => ({
  className: primary ? 'something' : 'something-else'
})`` // here
```

I will get an error from storybook:

>Objects are not valid as a React child (found: object with keys {$$typeof, render, attrs, >componentStyle, displayName, foldedComponentIds, styledComponentId, target, withComponent, >warnTooManyClasses, toString}). If you meant to render a collection of children, use an array >instead.

Ideally, I would like to avoid putting random backticks in the codebase just to suppress the error...

**Comment by yannbf** [comment]
Hey @MelMacaluso, the backticks are not random, they are template literals used in most styled component functions. [Refer to this docs](https://styled-components.com/docs/basics#attaching-additional-props) for more information. This error is not related to storybook.

**Comment by MelMacaluso** [comment]
Hi @yannbf feel free to close the issue, for some reason, I thought I made this in `styled-component`'s repo ahaha. ps: by random I mean the fact they *must* be there, I am well aware of what template literals/interpolations are. 

Thanks a lot and sorry for the trouble ahah 🙏

**Comment by yannbf** [comment]
> Hi @yannbf feel free to close the issue, for some reason, I thought I made this in `styled-component`'s repo ahaha. ps: by random I mean the fact they _must_ be there, I am well aware of what template literals/interpolations are.
> 
> Thanks a lot and sorry for the trouble ahah 🙏

No worries! Happy to help!
