### ISSUE TITLE
addon: parameters updated before any core events fired

### ISSUE THREAD

**Issue by alexreardon** [storybookjs/storybook#10352]
When changing between stories, the new parameters are sent to a panel just before the `coreEvents.STORY_CHANGED` is fired. No core event is fired before the parameters are updated.This makes it hard to know if the params are changing because of a story change, or for some other reason

**Comment by shilman** [comment]
Good one! cc @ndelangen

**Comment by ndelangen** [comment]
The parameters change because:

- the story HMR'ed
- the story changed

Can I know why you need to know the difference?

> or for some other reason

Am I missing anything?
What other reasons?

**Comment by ndelangen** [comment]
I don't think there's a need for listening for the STORY_CHANGED *and* listening for parameter changes?
