### ISSUE TITLE
addon-docs <Props> table should show CSS custom properties and parts

### ISSUE THREAD

**Issue by runarberg** [storybookjs/storybook#10353]
**Is your feature request related to a problem? Please describe.**

I have a `custom-elements.json` with the `cssCustomProperties` and `cssShadowParts` fields but when I add the `<Props />` element to generate the props table in my `mdx` storybook these relevant tables are noticeably missing from the docs tab.

**Describe the solution you'd like**

The generated table has all the other relevant properties (like attributes, properties, slots, etc.) it would be nice if CSS custom properties and CSS shadow parts would be added as well

**Describe alternatives you've considered**

I could manually document these, but those run the risk of becoming obsolete, missing, or out of sync. Also the noticeable jump between the built in table and the manual table is weird.

**Are you able to assist bring the feature to reality?**

Yes, but only requested.

**Additional context**

- [custom-elements.json draft](https://github.com/webcomponents/custom-elements-json/blob/2e66324413c7876a68db9d34f8cbc02d75ac289e/README.md#version-1.2)

![The two added props table sections](https://user-images.githubusercontent.com/3984600/78849956-c6917e80-79ca-11ea-9d03-e4dbb478210c.png)

**Comment by shilman** [comment]
Would be easy enough to add. If you wanted to take a shot, I'd be happy to point you in the right direction.

**Comment by runarberg** [comment]
@shilman sure, I can take a look at this after the weekend. I assume amending the function below is a good place to start:

https://github.com/storybookjs/storybook/blob/next/addons/docs/src/frameworks/web-components/custom-elements.ts#L48

**Comment by shilman** [comment]
That's the one! 👍

**Comment by shilman** [comment]
Yowza!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.0-alpha.17 containing PR #10442 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
