### ISSUE TITLE
Knobs are not working with Angular's Async Pipe

### ISSUE THREAD

**Issue by twittwer** [storybookjs/storybook#10365]
**Describe the bug**

When knobs are used in combination with an async pipe the value does not get updated.

**To Reproduce**
1. Checkout this Repo: https://github.com/twittwer/repro-storybook-async
2. `npm i` & `npm run storybook`
3. Initially plain & async messages are updated correctly
4. Change the message via knob
5. Now the async message is not updated anymore

**Screenshots**

Initially working example:
![image](https://user-images.githubusercontent.com/8677948/78907804-79bcaf00-7a81-11ea-9539-bd4bb501702d.png)
Broken example after changing message via knob:
![image](https://user-images.githubusercontent.com/8677948/78907886-9b1d9b00-7a81-11ea-91e4-9f1adab888bc.png)

**Comment by twittwer** [comment]
@shilman Can you say something about the problem or give hint where to find the problems cause?  
Should I provide some more information?

**Comment by shilman** [comment]
@twittwer unfortunately I’m ignorant about angular. Maybe @kroeder  can help?

**Comment by shilman** [comment]
Hi gang, We’ve just released addon-controls in 6.0-beta!

Controls are portable, auto-generated knobs that are intended to replace addon-knobs long term.

- [Controls README](https://github.com/storybookjs/storybook/tree/next/addons/controls)
- [Migration instructions](https://github.com/storybookjs/storybook/blob/next/addons/controls/README.md#how-do-i-migrate-from-addon-knobs)

Please upgrade and try them out today. Thanks for your help and support getting this stable for release!

**Comment by shilman** [comment]
For anybody who is interested in Controls but don't know where to start, I've created a quick & dirty step-by-step walkthrough to go from a fresh CRA project to a working demo. Check it out:

=> [Storybook Controls w/ CRA & TypeScript](https://gist.github.com/shilman/69c1dd41a466bae137cc88bd2c6ef487)

There are also some "knobs to controls" migration docs in the Controls README:

=> [How do I migrate from addon-knobs?](https://github.com/storybookjs/storybook/blob/next/addons/controls/README.md#how-do-i-migrate-from-addon-knobs)
