### ISSUE TITLE
Normalize parameter storage

### ISSUE THREAD

**Issue by tmeasday** [storybookjs/storybook#10361]
Change the way we store + publish parameters at least on the preview side to be normalized -- ie. don't spread global+component parameters until we fetch a story.

**Comment by shilman** [comment]
Son of a gun!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-alpha.46 containing PR #10373 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
