### ISSUE TITLE
Can toolbar addons appear on DocsPage Previews?

### ISSUE THREAD

**Issue by benedfit** [storybookjs/storybook#10366]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to use toolbar addons, such as `@storybook/addon-backgrounds`, in conjunction with DocsPage as per the image shown here: https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/media/hero.png

`<Preview withToolbar>` currently only renders the default buttons for zooming and opening in a new window. 

**Describe the solution you'd like**
An example of how to configure the docs addon to display the `@storybook/addon-backgrounds` button

**Are you able to assist bring the feature to reality?**
yes, I'd be happy to collaborate with someone to make this a reality

**Comment by benedfit** [comment]
Looks like this is related to https://github.com/storybookjs/storybook/issues/6700. I assume there will be some refactoring required before it all works together?

**Comment by shilman** [comment]
Also related: #8521

**Comment by shilman** [comment]
gonna close this as dupe to #8521

**Comment by shilman** [comment]
Sorry this is a different issue. 🙈 reopening

**Comment by shilman** [comment]
Each addon registers toolbars for the viewModes that it supports. Most addons only support `story` mode (AKA "Canvas" in the UI), but some addons can support `docs` mode as well. For example, I enabled this for the Toolbars addon here: https://github.com/storybookjs/storybook/pull/10810

Closing this. LMK if you think there's more to be done!

**Comment by benedfit** [comment]
@shilman thanks. Are there any plans to change some of the other official addons to be available in docs too?

**Comment by shilman** [comment]
@benedfit see #6700, hopefully in 6.x
