### ISSUE TITLE
[storyshots] Is there any coverage report for storyshots?

### ISSUE THREAD

**Issue by ajkl2533** [storybookjs/storybook#10364]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
I wonder if there is any way how to generate a coverage report from Storyshots addon. We are using it partly instead of unit test for components in React and we want to include it in overall coverage.

**Comment by shilman** [comment]
I prototyped this before but it will take a bunch of work to get this into production. Not currently on the roadmap, but I'd be happy to provide support for anybody who wants to tackle this.
