### ISSUE TITLE
Possibility to only show doc tab

### ISSUE THREAD

**Issue by YuunYang** [storybookjs/storybook#10362]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/15278220/78896695-72a69880-7aa3-11ea-8289-e07aab3c66e5.png)
Remove the `canvas` tab

**Describe alternatives you've considered**
Set default tab to `doc`

**Are you able to assist bring the feature to reality?**
maybe

**Additional context**

**Comment by ajkl2533** [comment]
I believe you can run storybook with `--docs` flag to achieve that, like:
```
yarn storybook --docs
```

**Comment by yannbf** [comment]
Hey @YuunYang, @ajkl2533 is correct. If you run `yarn storybook --docs` you will get something like the following:
![image](https://user-images.githubusercontent.com/1671563/78925730-39b6f580-7a9c-11ea-982d-84b55e12e00d.png)

If you don't mind I'll be closing the issue. Thanks @ajkl2533!
