### ISSUE TITLE
"No stories" in monorepo - source-map-support issue?

### ISSUE THREAD

**Issue by mikestopcontinues** [storybookjs/storybook#10368]
**Describe the bug**

I'm trying to get storybook working in my monorepo. I read the most recent tutorials on the matter and ended up using `require.context` to collect the right files.

I get this error in storybook: `Sorry, but you either have no stories or none are selected somehow.`

And I see this warning in the console for both webpack instances:
```
WARNING in ./node_modules/source-map-support/source-map-support.js
Module not found: Error: Can't resolve 'fs' in '/Users/msc/Code/hub/@arc/node_modules/source-map-support'
 @ ./node_modules/source-map-support/source-map-support.js
 @ ./node_modules/source-map-support/register.js
 @ ./tools/storybook/manager.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/client/manager/index.js ./tools/storybook/manager.js

WARNING in ./node_modules/source-map-support/source-map-support.js
Module not found: Error: Can't resolve 'module' in '/Users/msc/Code/hub/@arc/node_modules/source-map-support'
 @ ./node_modules/source-map-support/source-map-support.js
 @ ./node_modules/source-map-support/register.js
 @ ./tools/storybook/manager.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/client/manager/index.js ./tools/storybook/manager.js
```

I updated `main.js` to compensate, but it only helps errors on the `preview` side, not the `manager` side...

```js
// export

module.exports = {
  async webpackFinal(cfg) {
    cfg.node = cfg.node || {};
    cfg.node.fs = 'empty';
    cfg.node.module = 'empty';

    return cfg;
  },
};
```

**To Reproduce**

1. Create `/tools/storybook/preview.js`
```js
import {configure} from '@storybook/react';

const req = require.context('../../', true, /\.story\.[jt]sx?$/);

configure(() => {
  req.keys()
    .filter((loc) => !loc.includes('node_modules'))
    .forEach((loc) => req(loc));

  // console.log shows correct file locs and successful requires
  // e.g. ./common/ui/components/Circle.story.js
}, module);
```

2. Run from root: `start-storybook -c ./tools/storybook`

**Expected behavior**

I want storybook to show stories from across my monorepo.

**System:**
Environment Info:

  System:
    OS: macOS 10.15.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Binaries:
    Node: 13.10.1 - ~/.nvm/versions/node/v13.10.1/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v13.10.1/bin/npm
  Browsers:
    Chrome: 81.0.4044.92
    Firefox: 70.0.1
    Safari: 13.0.5
  npmPackages:
    @storybook/react: 5.3.18 => 5.3.18

**Comment by shilman** [comment]
Can you try adding `stories` in `.storybook/main.js` and removing the `configure` code in `preview.js` per the migration instructions:

```js
module.exports = {
  stories: ['../../*.story.js'],
  ...
}
```

**Comment by mikestopcontinues** [comment]
Awesome, @shilman ! For anyone else who comes across the issue, add a `/**`. 

I'm still getting the source-map warnings, but that seems like an upstream issue, as it's not getting in the way of storybook.
