### ISSUE TITLE
Ability to exclude some chained prop types

### ISSUE THREAD

**Issue by mustran** [storybookjs/storybook#10371]
**Is your feature request related to a problem? Please describe.**
I am trying to generate docs for a library and suddenly I got into a problem where I can't exclude some inherited types (props) from TypeScript.

TypeScript types:
```tsx
type ContentProps = {
  icon?: ReactNode | null;
  iconPosition?: string;
  children?: any;
};

export type Props = ButtonHTMLAttributes<HTMLButtonElement> &
  ContentProps & {
    buttonModifiers?: Array<string>;
    sizeType?: Size;
    style?: CSSProperties;
    className?: string;
    fullWidth?: boolean;
    fullHeight?: boolean;
  };
```
Button Component:
```tsx
const Button = (props: Props) => ()
```

**Describe the solution you'd like**
I want to be able to remove the props from `HTMLButtonElement` so it shows only the `ContentProps` and the other defined props (`buttonModifiers`,`sizeType` etc).

**Describe alternatives you've considered**
None.

**Are you able to assist bring the feature to reality?**
maybe ..

**Screenshot**

![Screenshot from 2020-04-09 21-39-29](https://user-images.githubusercontent.com/45851256/78934161-bbae1b00-7aaa-11ea-82aa-f952973519fc.png)

**Comment by shilman** [comment]
Sort of dupe to #7943

**Comment by mustran** [comment]
@shilman As I can see, the issue is still opened which means that there is still no support for this feature ? If that is the case, in which version we should expect this feature to be available ?

**Comment by shilman** [comment]
@mustran Either 6.0, which should be stable by mid-May, or 6.1, which should be stable mid-Summer.

**Comment by shilman** [comment]
A workaround I've added is the ability to specify props `include` and `exclude`:

```ts
type PropDescriptor = string[] | RegExp;

interface BaseProps {
  include?: PropDescriptor;
  exclude?: PropDescriptor;
}
```

So you could achieve what you want by only including non-chained props.

**Comment by mustran** [comment]
Hi @shilman. Thank you a lot for your answer, it looks amazing. 
Is the feature available in the beta version ?

**Comment by shilman** [comment]
Yeah, available for a couple weeks https://github.com/storybookjs/storybook/pull/10464

**Comment by mustran** [comment]
@shilman I deleted `node_modules`, installed the beta version and when I run `yarn run storybook` I get this error:

![Screenshot from 2020-05-04 15-07-56](https://user-images.githubusercontent.com/45851256/80969230-93031200-8e19-11ea-82fa-6a7fdc793652.png)

Also, this is how my `scripts` are defined:

![Screenshot from 2020-05-04 15-04-08](https://user-images.githubusercontent.com/45851256/80969424-dd848e80-8e19-11ea-8db1-29c06f8ee7c5.png)

and in the dependencies I have `storybook: '6.0.0-beta/2'`

**Comment by shilman** [comment]
https://raw.githubusercontent.com/storybookjs/storybook/next/examples/official-storybook/stories/addon-docs/props-include-exclude.stories.mdx

**Comment by shilman** [comment]
Disabling via `argTypes` customization:

https://github.com/storybookjs/storybook/blob/next/addons/controls/README.md#how-can-i-disable-controls-for-certain-fields-on-a-particular-story

Disabling via `propFilter`:

https://github.com/storybookjs/storybook/blob/next/docs/src/pages/configurations/typescript-config/index.md#mainjs-configuration
