### ISSUE TITLE
Add Polish version docs

### ISSUE THREAD

**Issue by mbiesiad** [storybookjs/storybook#10389]
Hi. First of all, awesome & great project! 🔥

If you consider a languages version support, here is a finished intros for Polish version:
https://github.com/mbiesiad/storybook/blob/pl_PL/README.md
// referring to PR #10388
https://github.com/storybookjs/storybook/pull/10388

Finished are also parts:
https://github.com/mbiesiad/storybook/tree/pl_PL/app/react
https://github.com/mbiesiad/storybook/tree/pl_PL/app/vue
https://github.com/mbiesiad/storybook/tree/pl_PL/app/angular
Other are under way [WIP]

You can use it, if you want anytime.
Best wishes

**Comment by jonniebigodes** [comment]
Closing this issue out as we don't have plans for the foreseeable future on including translations for the documentation. Once we've implemented it we'd love the translation from you @mbiesiad . We'll re-open the issue and follow up with you once and when we have it implemented.

Have a great day!

Stay safe

**Comment by mbiesiad** [comment]
Sure, thank you for your message. Let's keep in touch. Best wishes!
