### ISSUE TITLE
Support for webpack 5

### ISSUE THREAD

**Issue by saravanan10393** [storybookjs/storybook#10397]
**Describe the bug**
I am developing the react application with webpack 5-beata-14 and i am trying to setup a storybook for it. When i run the storybook command, it throws me an error saying `Cannot read property 'tapAsync' of undefined at ExternalModuleFactoryPlugin.js:30` When i looked at the code i found, the hooks provided by `NormalModuleFactory` plugin in webpack 5 is different from webpack 4. For example, `factory` hook is renamed to `factorize` in `NormalModuleFactory` plugin which causes the above specified error in `ExternalModuleFactory` plugin. 

**To Reproduce**
1. create new react app with webpack-5-beta-14
2. install story book
3. start storybook command

**Expected behavior**
Since storybook is using webpack 4, it will be helpful i can tell the story book to use my webpack version instead of default without forking storybook.

**Comment by shilman** [comment]
Closing as dupe to #9216

**Comment by worc** [comment]
specifically https://github.com/storybookjs/storybook/issues/9216#issuecomment-714476871 mentions the tapAsync issue
