### ISSUE TITLE
Error in storybook while deploying on netlify

### ISSUE THREAD

**Issue by kanav-raina** [storybookjs/storybook#10392]
hello guys I am using storybook. Its working fine on my local computer but when I am deploying it on netlify its giving me this error
![error_in_main_area](https://user-images.githubusercontent.com/29794748/79062245-09e33a00-7cb6-11ea-95b6-ce5fa151c4a8.png)

here is my package.json file
{
  "name": "concerto-web-editor",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@accordproject/concerto-core": "^0.82.7",
    "@ant-design/icons": "^4.0.2",
    "@babel/core": "^7.0.0-0",
    "@babel/plugin-proposal-class-properties": "7.8.3",
    "@babel/plugin-proposal-decorators": "7.8.3",
    "@babel/plugin-syntax-decorators": "^7.8.3",
    "@babel/plugin-syntax-flow": "^7.8.3",
    "@babel/plugin-transform-literals": "^7.8.3",
    "@babel/plugin-transform-react-jsx": "^7.9.1",
    "@babel/preset-typescript": "7.9.0",
    "@emotion/core": "^10.0.28",
    "@emotion/styled": "^10.0.27",
    "@jest/core": "^24.9.0",
    "@projectstorm/react-diagrams": "^6.0.1-beta.7",
    "@svgr/webpack": "4.3.3",
    "@testing-library/dom": "^7.2.1",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.3.2",
    "@testing-library/user-event": "^7.1.2",
    "@typescript-eslint/eslint-plugin": "^2.10.0",
    "@typescript-eslint/parser": "^2.10.0",
    "@webassemblyjs/helper-module-context": "1.8.5",
    "antd": "^3.26.13",
    "babel-eslint": "10.0.3",
    "babel-jest": "^24.9.0",
    "babel-loader": "8.0.6",
    "babel-plugin-named-asset-import": "^0.3.6",
    "babel-preset-react-app": "^9.1.1",
    "chalk": "^2.3.0",
    "closest": "0.0.1",
    "css-loader": "3.4.2",
    "dagre": "^0.8.5",
    "es-abstract": "^1.17.2",
    "eslint": "6.x",
    "eslint-config-react-app": "^5.2.0",
    "eslint-loader": "3.0.3",
    "eslint-plugin-flowtype": "3.x",
    "eslint-plugin-import": "2.x",
    "eslint-plugin-jsx-a11y": "6.2.3",
    "eslint-plugin-react": "7.18.0",
    "eslint-plugin-react-hooks": "1.x",
    "file-loader": "4.3.0",
    "filesize": "6.0.1",
    "js-yaml": "^3.13.1",
    "lodash": "4.*",
    "mathjs": "^6.6.1",
    "mini-css-extract-plugin": "0.9.0",
    "optimize-css-assets-webpack-plugin": "5.0.3",
    "path-js": "^1.0.1",
    "pathfinding": "^0.4.18",
    "paths-js": "^0.4.9",
    "react": "^16.13.0",
    "react-dom": "^16.13.0",
    "react-monaco-editor": "^0.35.0",
    "react-scripts": "3.4.0",
    "regenerator-runtime": "*",
    "resize-observer-polyfill": "^1.5.1",
    "storm-react-diagrams": "^5.2.1",
    "tapable": "^1.0.0",
    "typescript": "^3.8.3",
    "webpack": "^4.0.0",
    "webpack-dev-middleware": "^3.7.2"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "storybook": "start-storybook -p 9009 -s public",
    "build-storybook": "build-storybook -s public"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "@storybook/addon-actions": "^5.3.17",
    "@storybook/addon-links": "^5.3.17",
    "@storybook/addons": "^5.3.17",
    "@storybook/preset-create-react-app": "^2.0.0",
    "@storybook/react": "^5.3.17"
  }
}
Kindly help me in resolving this issue 
Thanks!

**Comment by shilman** [comment]
Do you have a repro repo?

**Comment by kanav-raina** [comment]
Thanks for replying @shilman 
Here is the link to my repo: https://github.com/kanav-raina/concerto-web-editor 
Here is the netlify link: https://awesome-hugle-ff3efc.netlify.com/?path=/story/add-new-class--class

**Comment by kanav-raina** [comment]
This was fixed by adding a .env file in react app
