### ISSUE TITLE
Add knobs to docs

### ISSUE THREAD

**Issue by YuunYang** [storybookjs/storybook#10399]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/15278220/79090703-1c747680-7d7d-11ea-8891-c600ea8af8b5.png)
docs have a feature to preview source code, and knobs can set props, so can we combine those two features? like we can add a tab in Preview which names `props`, and inside is the knobs config. 

**Are you able to assist bring the feature to reality?**
Maybe

**Comment by shilman** [comment]
Closing as dupe to #6639
