### ISSUE TITLE
TypeScript setup does not start without semicolons

### ISSUE THREAD

**Issue by balazsorban44** [storybookjs/storybook#10395]
**Describe the bug**
I have a setup with TypeScript + ESLint. I configured ESLint with the rule:
```js
semi: ["error", "never"]
```
and set autofix on save in VSCode.
When Running storybook, I get errors like:
![image](https://user-images.githubusercontent.com/18369201/79069355-d8766880-7ccd-11ea-9d0b-f7f050a6bce5.png)
![image](https://user-images.githubusercontent.com/18369201/79069357-dca28600-7ccd-11ea-9880-3fc1740fa3d0.png)

*To get rid of all these errors*, I have to set the ESLint rule to:
```js
semi: ["error", "always"]
```

and restart Storybook.

**To Reproduce**
<summary>
My main.js config:
<details>
<pre>
const path = require("path")

const TsconfigPathsPlugin = require('tsconfig-paths-webpack-plugin');
module.exports = {
  stories: ['../src/**/*.stories.(ts|tsx)'],
  addons: [
    '@storybook/addon-actions',
    '@storybook/addon-links',
    '@storybook/addon-docs',
    '@storybook/addon-a11y',
    '@storybook/addon-knobs'
  ],
  webpackFinal: async (config) => {
    
    config.module.rules.push({
      test: /\.(ts|tsx)$/,
      use: [
        {
          loader: require.resolve('ts-loader'),
          options: {
            transpileOnly: true,
          },
        },
        {
          loader: require.resolve("react-docgen-typescript-loader"),
          options: {
            tsconfigPath: path.resolve(__dirname, "../tsconfig.json"),
          },
        },
      ],
    });

    config.resolve.plugins = config.resolve.plugins || [];
    config.resolve.plugins.push(
      new TsconfigPathsPlugin({
          baseUrl: path.resolve(__dirname, '../src')
      })
    );
    config.resolve.extensions.push('.ts', '.tsx');

    return config;
  },
}
</pre>
</summary>

<summary>
My tsconfig.json
<details>
<pre>
{
  "include": ["src", "types"],
  "compilerOptions": {
    "module": "esnext",
    "lib": ["dom", "esnext"],
    "importHelpers": true,
    "declaration": true,
    "sourceMap": true,
    "rootDir": "./src",
    "strict": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "noImplicitThis": true,
    "alwaysStrict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "moduleResolution": "node",
    "baseUrl": "./src",
    "jsx": "react",
    "esModuleInterop": true,
    "resolveJsonModule": true
  }
}</pre>
</details>
</summary>

**Expected behavior**
It should allow a semicolon-less codebase.

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System:**
```
System:
    OS: Linux 5.3 Ubuntu 19.10 (Eoan Ermine)
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 12.6.0 - ~/.nvm/versions/node/v12.6.0/bin/node
    Yarn: 1.21.1 - /usr/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v12.6.0/bin/npm
  Browsers:
    Chrome: 81.0.4044.92
    Firefox: 75.0
  npmPackages:
    @storybook/addon-a11y: ^5.3.18 => 5.3.18 
    @storybook/addon-actions: ^5.3.18 => 5.3.18 
    @storybook/addon-docs: ^5.3.18 => 5.3.18 
    @storybook/addon-knobs: ^5.3.18 => 5.3.18 
    @storybook/addon-links: ^5.3.18 => 5.3.18 
    @storybook/addons: ^5.3.18 => 5.3.18 
    @storybook/react: ^5.3.18 => 5.3.18
```
**Additional context**

**Comment by shilman** [comment]
Does this still happen when you remove `addon-docs` from `main.js`?

**Comment by balazsorban44** [comment]
Commenting out `'@storybook/addon-docs',` does not seem to fix the problem.
