### ISSUE TITLE
Cannot read property 'theme' of undefined

### ISSUE THREAD

**Issue by zhangKunUserGit** [storybookjs/storybook#10394]
TypeError: Cannot read property 'theme' of undefined
    at getParameters (http://localhost:8081/vendors~main.e855c3ad9176593d5b21.bundle.js:162920:63)
    at wrapper (http://localhost:8081/vendors~main.e855c3ad9176593d5b21.bundle.js:160938:49)
    at http://localhost:8081/vendors~main.e855c3ad9176593d5b21.bundle.js:7719:14
    at http://localhost:8081/vendors~main.e855c3ad9176593d5b21.bundle.js:7733:26
    at http://localhost:8081/vendors~main.e855c3ad9176593d5b21.bundle.js:7243:21
    at http://localhost:8081/vendors~main.e855c3ad9176593d5b21.bundle.js:8545:14
    at http://localhost:8081/vendors~main.e855c3ad9176593d5b21.bundle.js:8546:16
    at withSubscriptionTracking (http://localhost:8081/vendors~main.e855c3ad9176593d5b21.bundle.js:8574:16)
    at http://localhost:8081/vendors~main.e855c3ad9176593d5b21.bundle.js:7243:21
    at http://localhost:8081/vendors~main.e855c3ad9176593d5b21.bundle.js:8545:14

**Comment by natashasheviakova** [comment]
@zhangKunUserGit I have the same issue, wonder if you use storybook-readme ?

for me it started happening suddenly (didn;'t update any dependencies), error is disappeared if do not use storybook-readme. So I am not quite sure what the issue is, need to look further.

**Comment by natashasheviakova** [comment]
@zhangKunUserGit 

looks like others have similar issues:
https://github.com/tuchk4/storybook-readme/issues/220
https://github.com/tuchk4/storybook-readme/issues/221 (temporarily solutions here)
https://github.com/tuchk4/storybook-readme/issues/228

**Comment by natashasheviakova** [comment]
@zhangKunUserGit also as an option, you can lock to storybook version 5.2.8

**Comment by TrueWill** [comment]
You could try adding an empty `options` object to `addParameters`; that worked around it for me. (It's still a bug though.)

```
addParameters({
  // ... whatever you had before
  options: {}
});
```

**Comment by shilman** [comment]
looks like `storybook-readme` needs to update its dependencies
