### ISSUE TITLE
How to use fonts and global styles in component library package

### ISSUE THREAD

**Issue by Benwick91** [storybookjs/storybook#10409]
**Describe the bug**
I have built a component library npm package and I am using styled-components and storybook for this. I can use the components from the installed package and it works.
But I have two questions:

1. Is it possible, to include the font in the component library or should I include the font in the  head of my project, where I installed and use my storybook library package?
2. What is the best way to use the global styles in the package? Should I import them in the entrypoint of my project, where I installed my storybook library package? Or is there a better way, so my component library uses the global styles from the storybook project. 

Thank you!

**System:**
  System:
```
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
  Browsers:
    Chrome: 80.0.3987.163
    Firefox: 74.0.1
    Safari: 13.1
  npmPackages:
    @storybook/addon-a11y: ^5.3.17 => 5.3.17 
    @storybook/addon-actions: ^5.3.17 => 5.3.17 
    @storybook/addon-console: ^1.2.1 => 1.2.1 
    @storybook/addon-docs: ^5.3.17 => 5.3.17 
    @storybook/addon-info: ^5.3.17 => 5.3.17 
    @storybook/addon-knobs: ^5.3.17 => 5.3.17 
    @storybook/addon-links: ^5.3.17 => 5.3.17 
    @storybook/addon-notes: ^5.3.17 => 5.3.17 
    @storybook/addon-storyshots: ^5.3.17 => 5.3.17 
    @storybook/addon-storysource: ^5.3.17 => 5.3.17 
    @storybook/addon-viewport: ^5.3.17 => 5.3.17 
    @storybook/addons: ^5.3.17 => 5.3.17 
    @storybook/preset-create-react-app: ^2.1.1 => 2.1.1 
    @storybook/react: ^5.3.17 => 5.3.17 
```
Thank you!

**Comment by rrsai** [comment]
I am investigating this as well.  One possible approach: Create a wrapper component with children, and put a react-helmet <Helmet> component into the top of the wrapper, then use it as a decorator simply on the stories that need things like the global font.  Or use it as a global decorator, but often it's *good* to find the places where a component is relying on global styles, if you want to make the component reusable without the global styles at all.
