### ISSUE TITLE
ERR_INCOMPLETE_CHUNKED_ENCODING - storybook side bar remains in loading stage

### ISSUE THREAD

**Issue by scottc11** [storybookjs/storybook#10406]
**Describe the bug**

The build phase executed by storybook completes as expected - with no errors - but I am getting `ERR_INCOMPLETE_CHUNKED_ENCODING` in the browser console after waiting over a minute for the storybook side bar to finish its loading phase, which never does end up completing.

![Screen Shot 2020-04-13 at 12 53 19 PM](https://user-images.githubusercontent.com/8580345/79140561-2fd80f80-7d86-11ea-92b5-be78881f1120.png)

**To Reproduce**

I am not sure how you could reproduce this, but here are some package versions
```
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-redux": "^7.2.0",
    "react-router": "^5.1.2",
    "react-router-dom": "^5.1.2",
    "@storybook/react": "^5.3.18",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-preset-stage-0": "^6.24.1",
    "uglifyjs-webpack-plugin": "^1.3.0",
    "webpack": "^4.41.6",
    "webpack-cli": "^3.3.11"
```

**Expected behavior**
Storybook was working for me just last week. I did update a few key packages such as react, redux, react-redux, but I figured those were decoupled from the storybook webpack build

**Code snippets**
```
// main.js
module.exports = {
  
  // crawl react repo for [componentName].stories.js files
  stories: ['../client//react/**/*.stories.js'],
};
```

**System:**
```
Environment Info:

  System:
    OS: macOS Sierra 10.12.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
  Binaries:
    Node: 10.15.0 - /usr/local/bin/node
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 80.0.3987.163
    Safari: 10.1.2
  npmPackages:
    @storybook/react: ^5.3.18 => 5.3.18
```

**Comment by scottc11** [comment]
Something I have also noticed in the terminal is that the storybook software is not re-building the bundle when I edit a component file or story. I checked my path to src folder and it checks out.

**Comment by shilman** [comment]
do you have a repro repo?

**Comment by scottc11** [comment]
> do you have a repro repo?

not one that I can share with the world. If I have time today I will create a fresh repo and see if I can notice anything different in the configuration - but the configuration is really quite bare-bones which is what has me stumped.  I want to say it has to do with how I am loading the `.stories.js` files but any errors there should show up in the terminal no?

**Comment by gogoku** [comment]
have you found the solution for this , facing the same issue. will try to put up a repo

**Comment by scottc11** [comment]
I am beginning to think it did not like the recent upgrade of react/react-dom.
I went from 
```
"react": "^16.3.2",          --> "react": "^16.13.1",
"react-dom": "^16.3.3", --> "react-dom": "^16.13.1",
```

I will revert this and see

**Comment by TadeuA** [comment]
have you found the solution for this , facing the same issue.
