### ISSUE TITLE
Using declarators on Storybook with CSF | ReactJs

### ISSUE THREAD

**Issue by ItzaMi** [storybookjs/storybook#10424]
### Bug or support request summary
I'm using Storybook with React and I'm using the 'new' CSF.

Now my stories are being displayed like this:

```
export const RegularDefault = () => <Button {...defaultButton} {...actions} />
RegularDefault.story = {
  decorators: [whiteDecorator],
}
```

If I'm not mistaken I can use my decorators on default but considering that I have 2 different decorators that I want to use, that really doesn't help me.

I was wondering if there's a cleaner way to show the decorators without having to call story on each one.

### Steps to reproduce

- create intended declarator
```
const whiteDecorator = (story: Function) => (
  <div style={{ padding: 30 }}>{story()}</div>
)
```

- create story and add declarator with new CSF logic

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react 5.3.18

### Affected platforms 

- Browser: chrome
- Framework: react

**Comment by shilman** [comment]
That's the syntax for story-level decorators. Do you have any improvements to the syntax that you'd suggest?

Maybe you could look into doing something with parameters and a global decorator?

```
// preview.js
addParameters({ storyPadding: 30 });
addDecorator((storyFn, { parameters }) => (
  <div style={{ padding: storyPadding }}>{storyFn()}</div>
));

// story file
export const RegularDefault = () => <Button {...defaultButton} {...actions} />
RegularDefault.story = {
  parameters: { storyPadding: 30 }
}
```

**Comment by ItzaMi** [comment]
Thank you for your answer, @shilman . At least for now I have no suggestions on how to improve the syntax. 
I was just making sure that the choice of having the decorators like this and that not having them highlight in Storybook was deliberate.
Thank you for your time explaining it!
