### ISSUE TITLE
Storybook breaks in IE11

### ISSUE THREAD

**Issue by kodmunki** [storybookjs/storybook#10427]
**Describe the bug**
Storybook 6.0.0-alpha.33 blows in IE11

**To Reproduce**
1. Run Storybook
2. Navigate to Storybook in IE11

**Expected behavior**
Storybook works in IE11

**Screenshots**
N/A

**Code snippets**
N/A

**System:**
Environment Info:

  System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i5-2557M CPU @ 1.70GHz
  Binaries:
    Node: 13.12.0 - ~/.nvm/versions/node/v13.12.0/bin/node
    npm: 6.14.4 - ~/.nvm/versions/node/v13.12.0/bin/npm
  Browsers:
    Chrome: 80.0.3987.163
    Firefox: 75.0
    Safari: 13.1
  npmPackages:
    @storybook/addon-a11y: ^6.0.0-alpha.33 => 6.0.0-alpha.33 
    @storybook/addon-actions: ^6.0.0-alpha.33 => 6.0.0-alpha.33 
    @storybook/addon-docs: ^6.0.0-alpha.33 => 6.0.0-alpha.33 
    @storybook/addon-knobs: ^6.0.0-alpha.33 => 6.0.0-alpha.33 
    @storybook/addon-links: ^6.0.0-alpha.33 => 6.0.0-alpha.33 
    @storybook/addon-notes: ^5.3.18 => 5.3.18 
    @storybook/addon-storyshots: ^6.0.0-alpha.33 => 6.0.0-alpha.33 
    @storybook/addon-viewport: ^6.0.0-alpha.33 => 6.0.0-alpha.33 
    @storybook/addons: ^6.0.0-alpha.33 => 6.0.0-alpha.33 
    @storybook/react: ^6.0.0-alpha.33 => 6.0.0-alpha.33 
    @storybook/theming: ^6.0.0-alpha.33 => 6.0.0-alpha.33 

**Additional context**
Appears to be an invalid character. Possibly a transpilation issue?

**Comment by tooppaaa** [comment]
Reproducible while running official storybook with the dlls
![image](https://user-images.githubusercontent.com/599163/79382034-31aafa00-7f63-11ea-87c1-ab7d5fea1e17.png)

**Comment by shilman** [comment]
Whoopee!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-alpha.43 containing PR #10471 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
