### ISSUE TITLE
Back port peer dependency fixes to 5.x?

### ISSUE THREAD

**Issue by voxpelli** [storybookjs/storybook#10425]
**Is your feature request related to a problem? Please describe.**
Installing complains of lots of different missing peer dependencies + apparently it doesn't work at all in Yarn 2 (see  #9667, #9916 and #9965 )

**Describe the solution you'd like**
Backport the fix in  #9667, #9916, #9965 and maybe others of the same to 5.x

**Describe alternatives you've considered**
I guess it works kind of as it is now in 5.x, unless one uses Yarn 2, but it becomes rather noisy at times, with risks of causing some alert fatigue around missing peer dependencies

**Are you able to assist bring the feature to reality?**
Maybe I can find time to help cherry-pick the relevant changes into a PR if there's interest.

Related: #2303, #7625, #7989

**Comment by shilman** [comment]
I'd rather focus on getting 6.0 out the door. After some time-consuming destabilizing patches-gone-wrong early in the 5.3.x cycle, I'd like to reserve patching to critical bugs.

**Comment by voxpelli** [comment]
@shilman That sounds totally reasonable. Where can one track what work remains for 6.x to move to beta/rc so that one could start trying that one in live projects?

**Comment by shilman** [comment]
There are a number of milestones with active issues for each major 6.0 feature

https://github.com/storybookjs/storybook/milestones

This issue tracks estimates, tho it’s slipping

https://github.com/storybookjs/storybook/issues/9311
