### ISSUE TITLE
Addons-knobs split object

### ISSUE THREAD

**Issue by YuunYang** [storybookjs/storybook#10428]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
When I define a object, it seems it display as a text field, but I want to know if I have a to split it into many single items, so that I don't need to edit configs by edit on a bunch of object text

**Describe alternatives you've considered**
I have tried to use single items and then use Object.assign to assign it to a main config object, but seems not working when I changed the item content.

**Are you able to assist bring the feature to reality?**
maybe

**Comment by YuunYang** [comment]
![image](https://user-images.githubusercontent.com/15278220/79298335-6db66e80-7f13-11ea-89f6-50beb365e256.png)
like this

**Comment by YuunYang** [comment]
I complete it by do some thing on the component by split one config props into many other props. It is a stupid question.

**Comment by piotrbekas-ee** [comment]
Did you split it in component or in `.stories`?
