### ISSUE TITLE
addon-jest: Documentation Angular Usage

### ISSUE THREAD

**Issue by ChazUK** [storybookjs/storybook#10434]
Documentation is incorrect for Angular Usage https://github.com/storybookjs/storybook/tree/master/addons/jest#usage-with-angular

```
import * as results from '../.jest-test-results.json';
```

should be

```
import results from '../.jest-test-results.json';
```

**Comment by shilman** [comment]
want to submit a PR?

**Comment by parulpriyedarshani** [comment]
@shilman Is anyone working on this issue? No active work has been done here lately. I would like to submit a PR on the same.

**Comment by shilman** [comment]
@parulpriyedarshani yes please! PRs welcome!

**Comment by parulpriyedarshani** [comment]
@ChazUK Thanks for opening this issue. After going through this issue and digging deep into it, I think that the documentation is correct here. One could import a file in this manner as we have by creating the typings.d.ts file and so have used * as here. I referred to the link as follows and hope this solves the problem : https://stackoverflow.com/questions/44817349/how-do-i-include-a-javascript-script-file-in-angular-and-call-a-function-from-th
