### ISSUE TITLE
docs: Show Code Open by default 

### ISSUE THREAD

**Issue by kschoi** [storybookjs/storybook#10430]
Hey team, I noticed the issue #8356 closed.
I'd only like to have an option to customize the story view (especially source code view), too.
Have you got any plan to resolve this issue?

```javascript
addParameters({ docs: { previewSource: 'open' } })
```

**Comment by SimplyY** [comment]
@shilman has new progress？

**Comment by ldeveber** [comment]
This would be lovely, I was just searching the docs on how to do this!

**Comment by signal-intrusion** [comment]
🤞 my current workaround is to poll the page for show code buttons and click them. It's crazy janky.

**Comment by ron0115** [comment]
> 🤞 my current workaround is to poll the page for show code buttons and click them. It's crazy janky.

@signal-intrusion How can you solve the problem by this hacking tricks.Could you pls show the code?Thank you

**Comment by AshConnolly** [comment]
Any progress on this?

**Comment by signal-intrusion** [comment]
@ron0115 In preview.js I added this:

```js
// this little bit of hacky code opens code samples
window.addEventListener('load', () => {
  let loc = window.location.href
  showCodeSamples()

  window.setInterval(() => {
    let newLoc = window.location.href

    if (newLoc !== loc && window.Prism) {
      loc = newLoc
      showCodeSamples()
    }
  }, 300)
})

function showCodeSamples() {
  try {
    const docs = document.querySelectorAll('.sbdocs')

    ;[].forEach.call(docs, (el) => {
      const buttons = el.querySelectorAll('button')
      const codeButton = [].find.call(buttons, (el) => el.textContent === 'Show code')
      if (codeButton) {
        codeButton.click()
      }
    })
  } catch (e) {
    console.warn(e)
  }
}
```

**Comment by frassinier** [comment]
I'm looking for a review, please👆🏻

**Comment by frassinier** [comment]
@shilman can we close this one now?

**Comment by shilman** [comment]
Gadzooks!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.3.0-alpha.17 containing PR #14729 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by tklives** [comment]
Leaving this here to hopefully help someone in the future...

If you are just looking to have the code block open for a single story, you just need to add `withSource="open"` to your `<Canvas>` tag that wraps the story:

```jsx
<Canvas withSource="open">
  <Story name="Cool story bro">
    <>
  </Story>
</Canvas>
```
Hope this helps someone like myself, since this isn't documented anywhere that I could find.

Cheers!

**Comment by jared-christensen** [comment]
It has been added, took me a bit to find.
https://github.com/storybookjs/storybook/pull/14729/files/0fd1b67ae1c4017f5678bc7faa21407f0f48a1ed#showhide-code

**Comment by JUNNNI** [comment]
Based on shilman comment [above](https://github.com/storybookjs/storybook/issues/10430#issuecomment-829876571), for those that are looking on how to implement it:

```ts
// .storybook/preview.ts

export const parameters = {
    docs: {
        source: {
            state: 'open',
        },
    }
}
```

**Comment by ryuheechul** [comment]
now [with storybook 7, it seems to be changed](https://sourcegraph.com/search?q=context%3Aglobal+repo%3A%5Egithub%5C.com%2Fstorybookjs%2Fstorybook%24+sourcestate&patternType=standard&sm=1&groupBy=path) to following and it works for me:

```js
// .storybook/preview.js

export const parameters = {
  // ...
  docs: {
    canvas: {
      sourceState: 'shown'
    }
  }
};
```

Couldn't find a corresponding documentation on this though.

**Comment by kasperskov-pdk** [comment]
> now [with storybook 7, it seems to be changed](https://sourcegraph.com/search?q=context%3Aglobal+repo%3A%5Egithub%5C.com%2Fstorybookjs%2Fstorybook%24+sourcestate&patternType=standard&sm=1&groupBy=path) to following and it works for me:
> 
> ```js
> // .storybook/preview.js
> 
> export const parameters = {
>   // ...
>   docs: {
>     canvas: {
>       sourceState: 'shown'
>     }
>   }
> };
> ```
> 
> Couldn't find a corresponding documentation on this though.

As I read the source code, your example is on story level, not global in preview.js. For example, the enum for SourceState is still close or open.
```
export enum SourceState {
  OPEN = 'open',
  CLOSED = 'closed',
  NONE = 'none',
}
```
But then again the function filtering the states is on story level with the "old" docs.source.state:
`const states = stories.map((story) => story.parameters.docs?.source?.state).filter(Boolean);`
Readme still refers to docs.source.state [See here](https://sourcegraph.com/github.com/storybookjs/storybook/-/blob/code/addons/docs/docs/docspage.md?L169:7)
I'm so confused.


Anyways neither solution works for me on storybook 7.4.0. Anyone else still having issues?

**Comment by jared-christensen** [comment]
I found the docs for it. https://storybook.js.org/docs/react/api/doc-block-canvas#sourcestate

**Comment by StanLaurent** [comment]
Does not seem to work (7.5.0)
