### ISSUE TITLE
addon-jest: Cant read errors due to CSS being applied

### ISSUE THREAD

**Issue by red-coat** [storybookjs/storybook#10433]
Cant read errors due to CSS being applied, cant override either due to dynamic import, please see screenshot attached:
<img width="1358" alt="Screenshot 2020-04-15 at 12 37 22" src="https://user-images.githubusercontent.com/20561665/79333128-e61e2f00-7f15-11ea-9605-a6a75272bf33.png">

**Comment by shilman** [comment]
Closing as dupe to https://github.com/storybookjs/storybook/issues/9858
