### ISSUE TITLE
Can't figure out how to make storybook work with ngx-formly

### ISSUE THREAD

**Issue by roger-gl** [storybookjs/storybook#10449]
First of all, this is the first day I'm using storybook, so I'm sure I'm doing something wrong. I have an Angular application that uses ngx-formly. But if I try to use a component that uses it I get:

> Can't bind to 'form' since it isn't a known property of 'formly-form'.

I thought that storybook reuses somehow the config of the existing Angular app ?

BTW: The app is based on nx, could that be the cause of the problem ?

**Comment by roger-gl** [comment]
I upgraded nx and used their tooling. With that it is working.

**Comment by yannbf** [comment]
Hey @roger-gl, nice to know that you started using storybook! Do I understand correctly that you managed to fix your issue? If that's the case, can this issue be closed?

**Comment by roger-gl** [comment]
Yes, thanks the ticket can be closed.

**Comment by yannbf** [comment]
Cool, hope you enjoy your experience with storybook! 😄
