### ISSUE TITLE
Run tests across all stories using a single configuration

### ISSUE THREAD

**Issue by linasmnew** [storybookjs/storybook#10461]
Looking for the ability to run tests across all stories using a single configuration such as is provided by Storyshots, i.e.:

```
initStoryshots({
    test: ({story}) => {
        render(story.render()) // will make sure every single story renders
    }
})
```

While above works, it doesn't seem like running these sort of tests is what this package was made for as above example has nothing to do with snapshotting.

So my question is whether I can already achieve above without using this addon, and if not it would be very useful if you guys could expose a standalone version of such functionality.

**Comment by shilman** [comment]
what are you trying to achieve? and what does storyshots NOT do that you need? or does it do too much?

**Comment by linasmnew** [comment]
Hey, I would like to run enzyme.render over each of my stories from a single configuration file - while this **can** be achieved with `storyshots` it seems a bit hacky because what I'm doing has nothing to really do with snapshotting. So to answer your question, yes it does too much 😄.
