### ISSUE TITLE
Knobs update on local story state update

### ISSUE THREAD

**Issue by Klaudia-Brysiewicz** [storybookjs/storybook#10474]
Hi,

Maybe I'm wrong but it seems that knobs addon can't be updated when using args update. To give  you some example I have some sample code which is:

```js
   .add('with storybook 6 using hooks', () => {
        const [args, updateArgs] = useArgs(false);
        console.log('args', args);
        const knobs = {
            name: text('name', 'name'),
            title: text('title', 'Input title'),
            isDisabled: boolean('isDisabled', false),
            //isChecked: boolean('isChecked', args.isChecked || false), // when using this update is blocked
            customClasses: text('customClasses', 'custom-class')
        };
        return (<InputCheckbox
            {...knobs}
            {...otherActions}
            isChecked={args.isChecked || false}
            onChange={(isChecked) => {
                updateArgs({ isChecked });
            }}/>);
    }
    )
```

old knobs are working fine for me but updating `isChecked` knob from `args ` doesn't trigger any change, how can I make it work? As we have many stories to update I would appreciate a simple solution.

**Comment by shilman** [comment]
@Klaudia-Brysiewicz did you try:

```js
   .add('with storybook 6 using hooks', (args) => {
      return (
        <InputCheckbox
          {...args}
          {...otherActions}
        />
      );
    }, {
      argTypes: {
        name: { type: { name: 'string' } },
        title: { type: { name: 'string' } },
        isDisabled: { type: { name: 'boolean' } },
        isChecked: { type: { name: 'boolean' } },
        customClasses: { type: { name: 'string' } },
      }
    }
)
```

**Comment by Klaudia-Brysiewicz** [comment]
hey,

just tried it out and it seems not to work correctly, I also tried setting defaultValue but both don't show the result in knobs panel, any other solution?
When I pass args as an argument to function I see an empty object of args ... 
Actually my knobs work well without one which is not more visible in knobs:

this line works well and we have our state updated:  `isChecked={args.isChecked || false} `
however, this one blocks everything:  `isChecked: boolean('isChecked', args.isChecked || false), // when using this update is blocked`

I would appreciate any solution ;)

**Comment by Klaudia-Brysiewicz** [comment]
hi, nothing new in this issue. I would appreciate some support as we want to introduce new storybook 6 in our company.

**Comment by shilman** [comment]
Does args work without knobs? The two packages are not designed to work together, and I anticipate args to replace knobs entirely at some point in the 6.x release cycle.

**Comment by Klaudia-Brysiewicz** [comment]
yes, args works perfectly without knobs, just in our case we truly need knobs panel to show component props. Can we register args panel the same way as we use knobs? If knobs will be replaced how can we show data passed to the component?

**Comment by shilman** [comment]
@Klaudia-Brysiewicz currently args show up in the `Docs` tab. In 6.1 we'll add the ability to show them in an addon panel. At that point, it should have (rough) feature parity with knobs, but:
1. has a nicer API
2. can be automatically generated for many frameworks
3. can work in both canvas and docs mode
4. potentially will get support in other tools because it's baked into CSF

**Comment by shilman** [comment]
Hi gang, We’ve just released addon-controls in 6.0-beta!

Controls are portable, auto-generated knobs that are intended to replace addon-knobs long term.

- [Controls README](https://github.com/storybookjs/storybook/tree/next/addons/controls)
- [Migration instructions](https://github.com/storybookjs/storybook/blob/next/addons/controls/README.md#how-do-i-migrate-from-addon-knobs)

Please upgrade and try them out today. Thanks for your help and support getting this stable for release!

**Comment by shilman** [comment]
For anybody who is interested in Controls but don't know where to start, I've created a quick & dirty step-by-step walkthrough to go from a fresh CRA project to a working demo. Check it out:

=> [Storybook Controls w/ CRA & TypeScript](https://gist.github.com/shilman/69c1dd41a466bae137cc88bd2c6ef487)

There are also some "knobs to controls" migration docs in the Controls README:

=> [How do I migrate from addon-knobs?](https://github.com/storybookjs/storybook/blob/next/addons/controls/README.md#how-do-i-migrate-from-addon-knobs)

**Comment by Klaudia-Brysiewicz** [comment]
thanks a lot for those tutorials !! I will check them out ;)
