### ISSUE TITLE
Addon-Doc: Props table prints expression instead interpret it

### ISSUE THREAD

**Issue by duarteCost** [storybookjs/storybook#10475]
Hi,

Using a `javascript`  expression inside props documentation like `PropTypes.oneOf([...Object.keys(obj1), ...Object.keys(obj2)]),` the props table displays the source code:

![image](https://user-images.githubusercontent.com/23384922/79749428-1ba48d00-8307-11ea-8ec9-071e50319774.png)

**Expected behavior**
`prop` property in props table with the keys of `obj1` and `obj2`.

**System:**
```
  System:
    OS: Windows 10 10.0.18362
    CPU: (6) x64 Intel(R) Core(TM) i5-8500T CPU @ 2.10GHz
  Binaries:
    Node: 11.9.0 - C:\node\node.EXE
    npm: 6.5.0 - C:\node\npm.CMD
  Browsers:
    Edge: 44.18362.449.0

```

**Comment by shilman** [comment]
Can you try using the `react-docgen-typescript-loader` setup described here and let me know if you still see this problem:

https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#rolling-back

**Comment by duarteCost** [comment]
@shilman i thinks this loader will not solve my problem because i'm using React `PropTypes` only without typescript

**Comment by shilman** [comment]
@duarteCost Aha! Sorry for the confusion. Which version of Storybook are you using?

**Comment by duarteCost** [comment]
@shilman no problem 👍

![image](https://user-images.githubusercontent.com/23384922/79768994-76e47880-8323-11ea-9033-350b99223c6a.png)

**Comment by shilman** [comment]
@patricklafrance any thoughts on this? i know you added some support for interpreted types in 5.3, but maybe not for this use case?

**Comment by patricklafrance** [comment]
@shilman not sure but usually it's has to do with react-docgen not handling the spread operators for this use case.

**Comment by duarteCost** [comment]
@patricklafrance I think the problem is no the spread operators. Any complex javascript is not interpreted.
Test case:
![image](https://user-images.githubusercontent.com/23384922/81171552-763f1980-8f94-11ea-9488-57bb7e051016.png)
![image](https://user-images.githubusercontent.com/23384922/81171613-940c7e80-8f94-11ea-9145-c48a02b15920.png)
The result is this:
![image](https://user-images.githubusercontent.com/23384922/81171723-cb7b2b00-8f94-11ea-8bae-dc4f85c05f88.png)
