### ISSUE TITLE
Support hooks in storyshots

### ISSUE THREAD

**Issue by brandon-leapyear** [storybookjs/storybook#10483]
**Is your feature request related to a problem? Please describe.**
#8177 

This PR added support for hooks in stories: https://github.com/storybookjs/storybook/pull/7571, but storyshots still breaks, even though the story works.

**Describe the solution you'd like**

**Describe alternatives you've considered**
There are many workarounds in the linked issue, but since storybook now supports hooks, i expect storyshots to have the same built-in support.

**Are you able to assist bring the feature to reality?**
yes, i can make a PR

**Additional context**

**Comment by shilman** [comment]
Released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-alpha.43 which references this issue in #10529 . Closing this!
