### ISSUE TITLE
Cannot run storybook server on alpha.34 and above

### ISSUE THREAD

**Issue by rey-wright** [storybookjs/storybook#10488]
**Describe the bug**
After upgrading to alpha.34, there are server breaking buds that stop the storybook server from being ran 

**To Reproduce**
1. update all `@storybook` packages to `6.0.0-alpha.32`
2. Run storybook server
3. See error about `testfixtures`

**Expected behavior**
I expect to be able to run storybook server successfully

**Screenshots**
<img width="705" alt="Screen Shot 2020-04-20 at 6 12 33 PM" src="https://user-images.githubusercontent.com/52427513/79805615-802a1100-8334-11ea-9d79-6a85a7b6a4f9.png">

**Code snippets**
If applicable, add code samples to help explain your problem.

**System:**

```
Environment Info:

  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
  Binaries:
    Node: 12.16.0 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 80.0.3987.163
    Firefox: 67.0.1
    Safari: 13.1
  npmPackages:
    @storybook/addon-a11y: 6.0.0-alpha.34 => 6.0.0-alpha.34 
    @storybook/addon-actions: 6.0.0-alpha.34 => 6.0.0-alpha.34 
    @storybook/addon-backgrounds: 6.0.0-alpha.34 => 6.0.0-alpha.34 
    @storybook/addon-docs: 6.0.0-alpha.34 => 6.0.0-alpha.34 
    @storybook/addon-knobs: 6.0.0-alpha.34 => 6.0.0-alpha.34 
    @storybook/addon-links: 6.0.0-alpha.34 => 6.0.0-alpha.34 
    @storybook/addons: 6.0.0-alpha.34 => 6.0.0-alpha.34 
    @storybook/react: 6.0.0-alpha.34 => 6.0.0-alpha.34 
    @storybook/theming: 6.0.0-alpha.34 => 6.0.0-alpha.34 
```

**Additional context**

**Comment by shilman** [comment]
@rey-wright are you including storybook's stories in your storybook?

**Comment by matheo** [comment]
@shilman I'm back to work with `@storybook` after busy days at the company, and trying to upgrade from `alpha.28` to `alpha.41`, it didn't load the stories at all with no error message:
![image](https://user-images.githubusercontent.com/260185/79937113-a7f5a380-841e-11ea-9b49-6369054bae78.png)
did something change loading the stories?
is there any way to have a verbose debug output?
TIA

**Comment by shilman** [comment]
@matheo if you're not seeing the same symptoms as @rey-wright can you file a separate issue?

**Comment by matheo** [comment]
yeah, no answer from @ndelangen so far on #10294 :( 
a quite disruptive change on `alpha.29` because it was fine on `alpha.28`

**Comment by rey-wright** [comment]
@shilman I'm not entirely sure what you mean by including storybook's stories. I'm scanning a particular src directory in my repo for stories.

**Comment by shilman** [comment]
@rey-wright Those errors seem to indicate that you are including Storybook's own stories inside your Storybook somehow. This might happen with a main.js glob like the following, which would inadvertently include `node_modules`:

```
module.export = { stories: ['../**/*.stories.*'] }
```

**Comment by rey-wright** [comment]
@shilman here is my main.js file

```
module.exports = {
  stories: ["../reusable/**/*.stories.(js|mdx)"],
  addons: [
    "@storybook/addon-docs",
    "@storybook/addon-knobs",
    "@storybook/addon-actions",
    "@storybook/addon-backgrounds",
    "@storybook/addon-a11y"
  ]
};
```

I guess what I would wonder give your statement.. even if I was picking up something (though unsure how the above would do that) why would this change only for a beta update.

**Comment by shilman** [comment]
@rey-wright it would change because those stories are effectively broken in the distribution, but since nobody should be loading them anyway, it shouldn't matter. i'll probably fix it anyway--since it's a bug--but it also indicates something weird is going on with your setup.

**Comment by vanessayuenn** [comment]
Hi! I am going through and cleaning up old issues in the repo. I suspect this bug might be fixed already in the latest Storybook release. Can you please try it out? If this issue persists with the latest version, please open a new bug report with a 7.x reproduction. Thank you so much! 🙏🏼
