### ISSUE TITLE
Addon-Docs

### ISSUE THREAD

**Issue by svenbatistasteinbach** [storybookjs/storybook#10507]
Is it possible to add your own styling to the ColorPalette or to implement the following things?

Show shades and tints with each other and with names see: https://design.gitlab.com/product-foundations/colors/
Instead of displaying only the HEX code also RGB, HSL, etc. 
Also it would be good if you could display the WCAG levels and contrast ratio.

Unfortunately I didn't find anything in the documentation or anywhere else. I am grateful for any hint.

**Comment by matheo** [comment]
@svenbatistasteinbach I found this one with the code of their custom components implementing some nice stuff, hope you get ideas there: https://github.com/wfp/ui

**Comment by svenbatistasteinbach** [comment]
cool thanks!

**Comment by shilman** [comment]
MDX doc blocks are just React components, so you can use any custom color swatch you want!
