### ISSUE TITLE
Static web page failed to load with error: "Uncaught TypeError: Super expression must either be null or a function" if you have terser-webpack-plugin with version 1.3.0

### ISSUE THREAD

**Issue by Pashokus** [storybookjs/storybook#10505]
**Describe the bug**
Static web page failed to load with error: "Uncaught TypeError: Super expression must either be null or a function" if you have terser-webpack-plugin with version 1.3.0. Any warnings or error during build time. the start script works without any error.  

v5.3.18

**To Reproduce**
1. add terser-webpack-plugin with version 1.3.0 to your devDependencies.
2. run build-storybook -c .storybook -o public
3. run npx http-server public
4. Open provided url and check error in the browser console.

update of terser-webpack-plugin to the version 2.3.5 fixes the issue. But maybe it makes sense to add a check.

**Comment by peterp** [comment]
I'm getting the same issue, but changing `terser-webpack-plugin` does not seem to work, so I modified `core/dist/server/build-static.js` and disabled minification:

```js
// node_modules/@storybook/core/dist/server/build-static.js

const managerConfig = await (0, _managerConfig.default)({
    configType,
    outputDir,
    configDir,
    corePresets: [require.resolve('./manager/manager-preset.js')],
    frameworkPresets: options.frameworkPresets,
    docsMode: options.docsMode,
    previewUrl: options.previewUrl
  });

  managerConfig.optimization.minimize = false
```

Is there a way to modify the manager's config?

**Comment by Adam-Michalski** [comment]
I have this problem after build-storybook.
I have installed terser-webpack-plugin but I still receive this error.
Is there any workaround to this issue?

**Comment by peterp** [comment]
if you're using yarn, then `yarn upgrade webpack` worked for me

**Comment by Adam-Michalski** [comment]
using `npm` I have tried to install/update webpack and it does not work for me

**Comment by Adam-Michalski** [comment]
I have found this https://medium.com/@anuhosad/react-errors-super-expression-must-either-be-null-or-a-function-4aac6e5173ad but I am using storybook with angular and have no idea what to do to run this app from builded sources. When I serve it everthing is ok

**Comment by PhiLhoSoft** [comment]
I have this issue without using terser-webpack-plugin.  
I just updated all the storybook dependencies.
Like Adam, it is in an Angular project, so Webpack is bundled.
Current relevant dependencies:

    "@angular-devkit/build-angular": "^0.803.2",
    "@angular-devkit/build-ng-packagr": "^0.803.2",
    "@angular/cdk": "8.1.1",
    "@angular/cli": "^8.3.2",
    "@angular/common": "^8.2.4",
    "@angular/compiler": "^8.2.4",
    "@angular/compiler-cli": "^8.2.4",
    "@angular/core": "^8.2.4",
    "@angular/forms": "^8.2.4",
    "@angular/platform-browser": "^8.2.4",
    "@angular/platform-browser-dynamic": "^8.2.4",
    "@babel/core": "^7.9.6",
    "@storybook/addon-actions": "5.3.18",
    "@storybook/addon-backgrounds": "5.3.18",
    "@storybook/addon-console": "^1.2.1",
    "@storybook/addon-knobs": "5.3.18",
    "@storybook/addon-links": "5.3.18",
    "@storybook/addon-notes": "5.3.18",
    "@storybook/addon-storysource": "5.3.18",
    "@storybook/addon-viewport": "5.3.18",
    "@storybook/angular": "5.3.18",
    "@storybook/source-loader": "5.3.18",
    "@types/core-js": "^2.5.3",
    "@types/faker": "^4.1.11",
    "@types/jasmine": "^3.5.10",
    "@types/react-color": "^3.0.1",
    "awesome-typescript-loader": "^5.2.1",
    "babel-loader": "^8.1.0",
    "core-js": "^3.6.5",
    "css-loader": "^3.5.3",
    "dom4": "^2.1.5",
    "faker": "^4.1.0",
    "fetch-ie8": "^1.5.0",
    "globby": "^11.0.0",
    "html-loader": "^1.1.0",
    "markdown-loader": "^5.1.0",
    "ng-packagr": "5.5.0",
    "node-sass": "^4.14.0",
    "raw-loader": "^1.0.0",
    "rxjs": "^6.5.5",
    "sass-loader": "^7.3.1",
    "style-loader": "^1.2.1",
    "stylelint": "^13.3.3",
    "tslint": "^5.20.1",
    "zone.js": "^0.10.3"

**Comment by shilman** [comment]
@PhiLhoSoft you're seeing https://github.com/storybookjs/storybook/issues/10204

**Comment by Adam-Michalski** [comment]
Any updates on this issue https://github.com/storybookjs/storybook/issues/10505#issuecomment-621182073

**Comment by PhiLhoSoft** [comment]
Thanks @shilman, I found a workaround in the pointed out issue, and indeed it is unrelated to this one, which I still have.

**Comment by PhiLhoSoft** [comment]
FYI, I found this interesting article: https://medium.com/@omril321/fixing-overly-aggressive-optimization-with-terser-f07309761b50

I tried it like that, in main.js :
```
const TerserPlugin = require('terser-webpack-plugin');

module.exports = {
	webpackFinal: async (config) => {
		config.optimization = {
			minimize: true, // Also tried false…
			minimizer: [
				new TerserPlugin({
					terserOptions: {
						keep_fnames: /./,
					},
				}),
			],
		};
		return config;
	},
	stories: ['./demo/stories/*.stories.ts'],
	addons: [
		'@storybook/addon-actions', // Also used for @storybook/addon-console
		'@storybook/addon-docs',
		'@storybook/addon-knobs',
		'@storybook/addon-viewport',
	],
};
```
and alas, I still have the issue, but if it can help…

**Comment by PhiLhoSoft** [comment]
Update: I finally got rid of this error by upgrading to 6.0.0-beta.4.

I had to add `"sass-loader": "^7.3.1"` to the package.json, because Storybook 6 brings the v. 8 which has a breaking change in the config, conflicting with some library we use.
