### ISSUE TITLE
Composition: Remote stories are not loading due to refs being parsed as `"[object Object]"`

### ISSUE THREAD

**Issue by evanroane** [storybookjs/storybook#10509]
**Describe the bug**
I first experienced this behavior in my own project where I have the storybook version 6 alpha package installed, but I figured I probably missed something, so I sought to reproduce the issue in `examples/dev-kits` since it illustrates the behavior I’m interested in using.

When I run the `dev-kits` example with refs, the storybooks defined on the `refs` key in main.js do not load.
In the browser console and network tabs I can see repeated attempts to fetch `http://localhost:9011/undefined/metadata.json` and `http://localhost:9011/undefined/stories.json`
I tracked down the issue to https://github.com/storybookjs/storybook/blob/next/lib/api/src/modules/refs.ts#L158

Here, I was able to see that the value of `refs` here is `"[object Object]"`. When `refs` is looped over, `checkRef` is consequently getting called on each character of `"[object Object]"`. Interestingly, TypeScript did not catch that a character string is not the `SetRefData` type since it is being cast with `as` in that context.

**To Reproduce**
1. Clone the storybook repo
2. compile core `yarn bootstrap --core`
3. move into the dev-kits example `cd examples/dev-kits` and  and install deps `yarn install`
4. Run this storybook example `yarn storybook`
5. When you navigate to the running storybook, you will see the failed attempts to access `stories.json` and `metadata.json` in the JS and network tabs.

**Expected behavior**
I expect remote storybooks to load and be populated in the manager sidebar.

**Screenshots**
<img width="1266" alt="image" src="https://user-images.githubusercontent.com/8975323/79916594-a01e0b00-83ee-11ea-809c-88969646961b.png">

**Code snippets**
See links provided above

**System:**
```
Environment Info:

  System:
    OS: macOS 10.15.3
    CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
  Binaries:
    Node: 12.10.0 - ~/.nvm/versions/node/v12.10.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.11.3 - ~/.nvm/versions/node/v12.10.0/bin/npm
  Browsers:
    Chrome: 81.0.4044.113
    Firefox: 74.0
    Safari: 13.0.5
```

**Comment by eroane-rms** [comment]
Pull request with fix: https://github.com/storybookjs/storybook/pull/10510
