### ISSUE TITLE
 defaultViewport not work when use @storybook/addon-viewport (ver. 5.3.18)

### ISSUE THREAD

**Issue by Brew-Brew** [storybookjs/storybook#10515]
**Describe the bug**
I add below code to preview.js file, but it doesn't work.
```javascript
import { addParameters } from '@storybook/react'

addParameters({
  viewport: {
    defaultViewport: 'iphone6'
  }
})
```

**To Reproduce**
1. install @storybook/addon-viewport
2. make preview.js file and add configure code about defaultViewport

**Expected behavior**
default viewport work

**Screenshots**

**Code snippets**
```javascript
import { addParameters } from '@storybook/react'

addParameters({
  viewport: {
    defaultViewport: 'iphone6'
  }
})
```

**System:**
 "@storybook/addon-viewport": "^5.3.18"
 "@storybook/addons": "^5.3.18"
 "@storybook/react": "^5.3.18"

**Additional context**

**Comment by Brew-Brew** [comment]
It works if i set like this
```javascript
import { addParameters } from '@storybook/react'
import { INITIAL_VIEWPORTS } from '@storybook/addon-viewport'

addParameters({
  viewport: {
    viewports: INITIAL_VIEWPORTS,
    defaultViewport: 'iphone6'
  }
})

```

**Comment by webhacking** [comment]
Same here

**Comment by webhacking** [comment]
I'm experiencing the same bug.

**Comment by webhacking** [comment]
@Brew-Brew

**Comment by YassineGherbi** [comment]
I don't understand why this is closed @Brew-Brew I don't see anyone agreeing with the "solution". For me, it doesn't work as well. Could we set this to open again?

**Comment by hurrii** [comment]
Still not fixed

Config I use:
```
const preview: Preview = {
    parameters: {
        ...
        viewport: {
            viewports: INITIAL_VIEWPORTS,
            defaultViewport: INITIAL_VIEWPORTS.iphonex
        }
    },
};
```

'@storybook/addon-viewport' added to main.ts addons part of the config
