### ISSUE TITLE
Search is not working on 5.x.x release.

### ISSUE THREAD

**Issue by Vlad160** [storybookjs/storybook#10519]
**Describe the bug**
Search is not working on 5.x.x release.

**To Reproduce**
1. Go to https://storybookjs.netlify.com/official-storybook/
2. Open dev tools.
3. Type anything in the search input.
4. See an error in the console. 
```
Uncaught TypeError: t.parameters.fileName.includes is not a function
```

**Expected behavior**
Search is working as described in the documentation. It should use filename. 

**Additional context**
Search is working correctly in `serve` mode (using `start-storybook`).
I debugged the issue a little bit and found that `fileName` property is set to number. Something goes wrong during build process.

**Comment by shilman** [comment]
Yo-ho-ho!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.19 containing PR #10539 that references this issue. Upgrade today to try it out!

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Yippee!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-beta.24 containing PR #10917 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.
