### ISSUE TITLE
Ability to extract MDX component boilerplate 

### ISSUE THREAD

**Issue by lopis** [storybookjs/storybook#10514]
**Is your feature request related to a problem? Please describe.**

I found a way to write my stories in vue files. Then I created a "story" function that sets all the story parameters I need to make it work. This caused the source on Storybook to just show `story(BaseRadios)`, that's why I need the custom source:

```jsx
<Preview>
  <Story name='BaseRadios' inline
  parameters={{ storySource: { source: BaseRadios.__source } }}>
    {story(BaseRadios)}
  </Story>
</Preview>
```

I found this very noisy, so I tried to extract all this boilerplate to a reusable component like this (actually I used React.createElement, but that's just issues with the loader):

```jsx
const StoryWrapper = ({ Component, name }) => {
  return (
    <Preview>
      <Story name={name} inline
        parameters={{ storySource: { source: Components.__source } }}>
      {story(Component)}
      </Story>
      </Preview>
  )
}
```

Unfortunately this doesn't work. It kept telling me that the story name was an empty string (`'' must include alphanumeric characters`). Diving into the source of Storybook, I think this is because of the way MDX is loaded. Some magic happens and the name prop of `Story` is read into some global registry called `mdxStoryNameToKey` and later read by `Preview`. 

**Describe the solution you'd like**

I understand this is super custom stuff, but I'm wondering if I can work around this? Maybe some way of passing the name to mdxStoryNameToKey without using the Story component?

**Describe alternatives you've considered**

I tried several different ways to create my custom component but always hit the same problem.

My last attempt was to only create a custom Story component and leave the Preview alone:

```jsx
// story.mdx
import { Preview } from '@storybook/addon-docs/blocks';
<Preview>
  <Story name='SizeRadio' component={SizeRadio}/>
</Preview>
```

```jsx
// story-util.js
import { Story as StoryBlock } from '@storybook/addon-docs/blocks';
export const Story = ({component, ...props}) => {
  return React.createElement(
    StoryBlock,
    {
      inline: true,
      parameters: {
        storySource: {
          source: component.__source
        }
      },
      ...props
    },
    story(component),
  );
}
```
This already looks much cleaner, but It won't let me pass the story as a prop. I get this error:

    [Vue warn]: Failed to mount component: template or render function not defined.

Then I tried another version like this:

```jsx
<Preview>
  <Story name='BaseRadios' component={BaseRadios}>
    {story(BaseRadios)}
  </Story>
</Preview>
```

This renders correctly, but it still won't set `parameter.storySource.source`. I just see `story(BaseRadios)` in the UI.

So I can conclude that I can't really extract much. If `name` and `parameters`, as well as the children of `Story` are not explicit in the MDX file, they are not picked up at all. Any way around this?

**Are you able to assist bring the feature to reality?**
Yes, I'd love to contribute. Just need some guidance.

**Comment by shilman** [comment]
Indeed the `mdxStoryNameToKey` is pretty tricky, and I'm not sure of a better way to do it.

Could you simply override `docs.source.code` parameter, either at the component or story level?

```
<Meta
  title="..."
  parameters={{
    docs: { source: { code: BaseRadios.__source } }
  }}
/>
```

Alternatively 6.0 has a `transformSource` parameter https://github.com/storybookjs/storybook/pull/10503.

It currently takes the existing story source code and a story ID as arguments and returns updated source code. We could update it to take the story source and the story context as arguments, and then you could override it to return the source you want based on one of the parameters?

WDYT?

**Comment by lopis** [comment]
I did explore the `formatSource` initially, but since that function already receives the useless source, I dropped it. So some sort of update to that could certainly be useful.

Your suggestion works, but naturally that won't do for stories with multiple sub-stories.

Another thing I noticed is that decorators are also totally ignored when using MDX, which means I'll have to manually add my decorator to each `Story`.

**Comment by shilman** [comment]
You can also do:

```
<Story name=“...” parameters={{ ... }}>...</Story>
```

I’m almost positive decorators work fine in MDX so please double check. If you can’t get it working please file a separate issue and I can help you figure it out.

**Comment by lopis** [comment]
Ah, never mind.. The decorators were not working because they depend on a parameter, which I have to set in the MDX now. I guess there's not much I can do, considering the way the MDX loader works, so I will close it. Thank you so much for your time!

**Comment by shilman** [comment]
@lopis hope you figured it out. in general, anything you can do in CSF you can also do in MDX. and anything you can do in `storiesOf`, except for dynamically-generated stories, you can do in both CSF and MDX.
