### ISSUE TITLE
Addon-Docs: Ember framework doesn't output default value properly

### ISSUE THREAD

**Issue by jguze** [storybookjs/storybook#10511]
**Describe the bug**
The ember version of the addon-docs addon doesn't output the default value properly. It is being output as a string, but should be output in the summary node of an object as `defaultValue: { summary: prop.defaultValue }`

**To Reproduce**
1. Create a component with a default value. For example, add an `@defaultValue null` in the `welcome-banner.js` example in the ember live example
2. See that the default value is empty

**Expected behavior**
The default value should appear

**Code snippets**
This line [here](https://github.com/storybookjs/storybook/blob/next/addons/docs/src/frameworks/ember/jsondoc.js#L17) should instead be:
```
defaultValue: { summary: prop.defaultValue },
```

**Comment by shilman** [comment]
Yowza!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-rc.22 containing PR #10512 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.
