### ISSUE TITLE
Addon-docs: Ember props aren't displaying

### ISSUE THREAD

**Issue by jguze** [storybookjs/storybook#10524]
**Describe the bug**
Props aren't being displayed in the ember framework of addon-docs.

Looking through, it looks like in @next, it expects the response of `extractArgTypes` to be just the rows rather than `{ rows }`.

**Screenshots**
See the live example site's 'Welcome Banner'.
https://next--storybookjs.netlify.app/ember-cli/?path=/docs/welcome-banner--basic
![image](https://user-images.githubusercontent.com/2375555/80029632-ee3d1800-849b-11ea-820e-504b47ba668a.png)

**Comment by shilman** [comment]
ZOMG!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-rc.22 containing PR #11760 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
