### ISSUE TITLE
Use of obsolete browser API execCommand in syntaxhighlighter.tsx

### ISSUE THREAD

**Issue by ghengeveld** [storybookjs/storybook#10526]
The [document.execCommand](https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand) method is obsolete and nonstandard. It's not supported in JSDOM, which causes Chromatic builds to fail.

Storybook uses this API [right here](https://github.com/storybookjs/storybook/blob/f95829a2c07ae601e32874ef4f4a25bb8c485836/lib/components/src/syntaxhighlighter/syntaxhighlighter.tsx#L137). It's used to copy something to the clipboard. There's [a better way](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API) to do that nowadays.

**Comment by shilman** [comment]
Great Caesar's ghost!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-beta.34 containing PR #11251 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
