### ISSUE TITLE
Addon-docs: cannot inject a docsOnly story into MDX

### ISSUE THREAD

**Issue by meyerds** [storybookjs/storybook#10522]
**Describe the bug**
If I try to setup a Preview containing a docsOnly Story in my MDX, the application crashes.

**To Reproduce**
1. Create a component:
   
   Test.tsx
   ```
   import React from 'react';
   export interface TestProps { subject: string }
   export const Test: React.FC<TestProps> = ({ subject  }: TestProps) => `Hello ${subject}!`;
   ```
2. Create a CSF story:
   
   test.stories.tsx
   ```
   import React from 'react';
   import { Test } from './Test';
   import testStoryMdx from './test.mdx';
   
   export default {
      title: 'Stories/Test',
      component: Test,
      parameters: { docs: { page: testStoryMdx }}
   };
   
   export const canvasAndDocsStory = () => <Test subject="world" />;
   export const docsOnlyStory = () => <Test subject="docs" />;
   docsOnlyStory.story = { parameters: { docsOnly: true }};
   ```
3. Create MDX docs
   
   test.mdx
   ```
   import { Story, Preview } from '@storybook/addon-docs/blocks';
   import { Test } from './Test';
   
   <Preview>
      <Story id="stories-test--docs-only-story" />
   </Preview>
   ```
4. Attempt to load Storybook

**Expected behavior**
The docsOnly story should render in the Preview block.

**Actual behavior**
The application crashes with error
> Uncaught TypeError: Cannot read property 'children' of undefined

**System:**
Environment Info:
  System:
    OS: macOS 10.15.3
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 12.10.0 - ~/.nvm/versions/node/v12.10.0/bin/node
    npm: 6.14.4 - ~/.nvm/versions/node/v12.10.0/bin/npm
  Browsers:
    Chrome: 81.0.4044.113
    Safari: 13.0.5
  npmPackages:
    @storybook/addon-actions: ^5.3.18 => 5.3.18 
    @storybook/addon-docs: ^5.3.18 => 5.3.18 
    @storybook/addon-knobs: ^5.3.18 => 5.3.18 
    @storybook/addon-links: ^5.3.18 => 5.3.18 
    @storybook/addon-viewport: ^5.3.18 => 5.3.18 
    @storybook/addons: ^5.3.18 => 5.3.18 
    @storybook/preset-ant-design: ^0.0.1 => 0.0.1 
    @storybook/preset-create-react-app: ^2.1.1 => 2.1.1 
    @storybook/react: ^5.3.18 => 5.3.18

**Comment by meyerds** [comment]
hey stale bot I still care about this issue ;-)

**Comment by frassinier** [comment]
Hey @meyerds 

Did you get the same result using this instead?

test.stories.tsx

```diff
import React from 'react';
import { Test } from './Test';
import testStoryMdx from './test.mdx';

export default {
   title: 'Stories/Test',
   component: Test,
   parameters: { docs: { page: testStoryMdx }}
};

export const canvasAndDocsStory = () => <Test subject="world" />;
export const docsOnlyStory = () => <Test subject="docs" />;
-docsOnlyStory.story = { parameters: { docsOnly: true }};
+docsOnlyStory.parameters = { docsOnly: true };
```

**Comment by meyerds** [comment]
@frassinier using that, there is no effect. There is no error, but neither is the story hidden in the navigation tree.
