### ISSUE TITLE
Ability to initially select canvas tab when entering mobile mode

### ISSUE THREAD

**Issue by WayneEllery** [storybookjs/storybook#10538]
**Is your feature request related to a problem? Please describe.**
When entering mobile mode the sidebar tab is initially shown. Is there a way to configure Storybook to show the canvas instead of the sidebar?

**Describe the solution you'd like**
A way to configure Storybook to initially show the canvas instead of the sidebar when entering mobile mode.

**Are you able to assist bring the feature to reality?**
maybe

**Comment by shilman** [comment]
This makes sense to me, and probably should be the default. @domyen @ndelangen WDYT?

**Comment by ndelangen** [comment]
We can make it the default, if you want @shilman.

**Comment by domyen** [comment]
sgtm

**Comment by shilman** [comment]
Hurrah!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-beta.9 containing PR #10818 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
