### ISSUE TITLE
Addon-docs mdx docs disappeared on the menu when using --docs

### ISSUE THREAD

**Issue by YuunYang** [storybookjs/storybook#10530]
**Describe the bug**
When I start a project by add --docs, it seems disappeared in left menu
![image](https://user-images.githubusercontent.com/15278220/80104970-7f021980-85aa-11ea-8b72-e43ddad6497d.png)
I can access this page by typing the url, but can not find it on the left.

Actually, I can see it if I don't start a docs-only page.

**To Reproduce**
NODE_PATH=src start-storybook -c .storybook -p 6006 --docs

**Expected behavior**
Show items when use `--docs`

**Code snippets**
mdxfile
```mdx
import { Meta, Story, Props, Preview } from '@storybook/addon-docs/blocks';
import { text, object } from '@storybook/addon-knobs';
import getConfig from '../utils/getConfig';

<Meta title="Xtable" component={Live} />

## 代码演示
....
<Preview withToolbar mdxSource={BasicText}>
  <Story name="基本例子">
    <Basic />
  </Story>
</Preview>

## Live Demo
 ...
<Story name="live-demo" args={config}>
  {(args) => {
    return <Live {...args} />
  }}
</Story>

<Props story="live-demo" />
```

**System:**
System:
    OS: macOS Mojave 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-4771 CPU @ 3.50GHz
  Binaries:
    Node: 12.16.1 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 81.0.4044.122
    Safari: 12.1.1
  npmPackages:
    @storybook/addon-docs: ^6.0.0-alpha.39 => 6.0.0-alpha.41
    @storybook/addon-knobs: ^6.0.0-alpha.41 => 6.0.0-alpha.41
    @storybook/react: ^6.0.0-alpha.41 => 6.0.0-alpha.41
    @storybook/source-loader: ^6.0.0-alpha.41 => 6.0.0-alpha.41

**Additional context**

**Comment by shilman** [comment]
That's a feature of `--docs`, not a bug

**Comment by YuunYang** [comment]
So if I want use --docs, I can't use mdx :(, sad

**Comment by shilman** [comment]
it's a `--docs` thing, not an MDX thing. it's the same in CSF.

i'm confused about what you want?

**Comment by cmeiller** [comment]
> That's a feature of `--docs`, not a bug

@shilman I'm a bit surprised by that too. I don't need the canvas tab so my doc is build with the `--docs` option for a better reading. But I don't understand why there is no depth in this case to navigate in the page.

Fun fact: We retrieve the stories when we add a subpage

> yarn storybook
![Capture d’écran 2020-05-27 à 12 28 29](https://user-images.githubusercontent.com/412839/83008922-3fe63e80-a016-11ea-8927-a5239de9fc77.png)

> yarn storybook --docs
![Capture d’écran 2020-05-27 à 12 28 53](https://user-images.githubusercontent.com/412839/83008952-4d032d80-a016-11ea-8465-6f24d3354326.png)

> yarn storybook --docs with subpage
![Capture d’écran 2020-05-27 à 12 30 23](https://user-images.githubusercontent.com/412839/83009009-6015fd80-a016-11ea-913e-59053010de00.png)

**Comment by shilman** [comment]
cc @domyen

**Comment by domyen** [comment]
So the request seems to be seeing stories as nested elements in the sidebar of the `--docs` page? 

That's not the common behavior in most design systems I researched, however I could see why folks might want to quickly navigate to the story section. 

I don't think it makes sense to link to every story but perhaps we can auto-generate nested sidebar elements for all `h2`s instead. That's inline with typical documentation site behavior and is general enough to apply to many cases. (We also dogfood `--docs` mode for [Storybook Design System](https://storybook-design-system.netlify.app/))

**Comment by as-zlynn-philipps** [comment]
This is still an "issue" in v6.2.9. Also, it'd be nice to be able to search by story in docs mode. We just wanted to hide the Canvas tab, not remove these features.
