### ISSUE TITLE
Error while trying to install storybook. Error: EPERM: operation not permitted

### ISSUE THREAD

**Issue by arun678** [storybookjs/storybook#10544]
I tried installing storybook in my newly created React App, but got this error
Error: EPERM: operation not permitted, mkdir 'C:\Users\XXX'
'sb' is not recognized as an internal or external command,
operable program or batch file.

**To Reproduce**
1. Create React App using npx create react app
2. To Install storybook, use the following command `npx -p @storybook/cli sb init --type react_scripts` 

*Package.json**
{
  "name": "XXX",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.5.0",
    "@testing-library/user-event": "^7.2.1",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-scripts": "3.4.1"
  },
  "scripts": {
    "storybook": "start-storybook",
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}

*System:**
Please paste the results of `npx -p @storybook/cli@next sb info` here.
Error: EPERM: operation not permitted, mkdir 'C:\Users\XXX'
'sb' is not recognized as an internal or external command,
operable program or batch file.

**Additional context**

**Comment by jonniebigodes** [comment]
@arun678 you don't need the react scripts. Storybook detects automatically that you're using react when you issue the initialize command inside a react project, take a look at [this](https://www.learnstorybook.com/intro-to-storybook/react/en/get-started/)

**Comment by arun678** [comment]
I have tried even this. `npx -p @storybook/cli sb init` But its the same error.

**Comment by jonniebigodes** [comment]
@arun678 i've tried it during this weekend as i was triaging a completely different issue. And it worked without a hitch. 

Based on the description you have it seems that this could be a permission usage with windows. Or your antivirus acting up. As it might be looking into the folders/files that are being downloaded and it breaks the install. 

Can you try installing the cli globally with `npm install -g @storybook/cli` and initialize it in a new react project created to see if the error pops up? 

Because the alternative will be to clean the cache and add them again

**Comment by arun678** [comment]
@jonniebigodes Thanks for that. I tried on a different system. It worked without any issues. When tried to inspect from logs, got to know that its because of file permission issues. My PC's name has a space. However i wasnt able to rename the PC to make it 1 word without space.

**Comment by jonniebigodes** [comment]
@arun678 no need to thank. Glad that i was able to provide you with some context and you managed to solve the issue.

**Comment by C3SC0-V4113** [comment]
I had the same issue, but i fixed it, i was running the project and it was messing with the command

**Comment by amitpatil321** [comment]
I think this happens when you have dev server running and you try to install/init storybook...Stop the dev server and then try installing, it should work.
