### ISSUE TITLE
Addon-links doesn't work in some cases

### ISSUE THREAD

**Issue by aadamsx** [storybookjs/storybook#10546]
**Describe the bug**
The most common usage for LinkTo() doesn't work with the latest LinkTo lib on Windows 10 inside a out of the box CRA.

**To Reproduce**
$ npx create-react-app linkto-test
$ npm install --save-dev @storybook/addon-links
// Added '@react-theming/storybook-addon' to .storybook/main.js
// Created story to test straight from the README.md example

```
// linkto.stories.js

import React from "react";

import { linkTo } from '@storybook/addon-links';
import LinkTo from '@storybook/addon-links/react';

export default {
  title: 'Select',
};

export const index = () => (
  <select value="Index" onChange={linkTo('Select', e => e.currentTarget.value)}>
    <option>index</option>
    <option>first</option>
    <option>second</option>
    <option>third</option>
  </select>  
);
export const first = () => (
  <LinkTo story="index">Go back</LinkTo>
);
export const second = () => (
  <LinkTo story="index">Go back</LinkTo>
);
export const third = () => (
  <LinkTo story="index">Go back</LinkTo>
);
```

$ npm run storybook

// Inside storybook:
// Select one of the other components from the drop down (first, second, or third).

// Check the Actions tab (if enabled)

```
// error message inside Actions tab
Select/Index/error: (1) ["could not navigate to provided story"]
```

// Result: No navigation,
// Now go to one of the other three component links (first, second, or third).
// Select the "Go back" link
// Result: You will be taken back to the drop down

// Conclusion: React "LinkTo" ('@storybook/addon-links/react') works, but "linkTo" (with a lower case L) ('@storybook/addon-links') doesn't.

**Expected behavior**
Expected both React "LinkTo" ('@storybook/addon-links/react') AND "linkTo" (with a lower case L) ('@storybook/addon-links') to work

**System:**
Windows 10, latest (as of today): CRA, Storybook, addon-links

Please paste the results of `npx -p @storybook/cli@next sb info` here. 
Environment Info:
  System:
    OS: Windows 10 10.0.17763
    CPU: (8) x64 Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
  Binaries:
    Node: 12.4.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.17763.831.0

**Comment by javierguzman** [comment]
Hello @aadamsx! Did you manage to solve this? I am facing the same error message. Thank you in advance and regards
