### ISSUE TITLE
Right side of assignment cannot be destructured.

### ISSUE THREAD

**Issue by webber-jiang** [storybookjs/storybook#10548]
In a component that has destructuring, storybook throws the error "Right side of assignment cannot be destructured"; even though it run perfectly fine in normal build. 

**Screenshots**
![Screen Shot 2020-04-26 at 1 26 12 PM](https://user-images.githubusercontent.com/52307458/80294874-9ff08780-87c1-11ea-8a7f-1399fd81c5fd.png)
![Screen Shot 2020-04-26 at 1 23 12 PM](https://user-images.githubusercontent.com/52307458/80294877-a252e180-87c1-11ea-8a1e-b5b31a08c155.png)
![Screen Shot 2020-04-26 at 1 02 16 PM](https://user-images.githubusercontent.com/52307458/80294880-a4b53b80-87c1-11ea-8166-95e3ae8d0b9b.png)

**Comment by shilman** [comment]
You probably need to add the context in a decorator

https://storybook.js.org/docs/basics/writing-stories/#decorators

**Comment by webber-jiang** [comment]
Hi Shilman, I had a read of the docs but I couldn't find how to apply context as a decorator.

**Comment by shilman** [comment]
It depends on the context. Typically it looks like this in `.storybook/preview.js`:

```js
import { addDecorator} from `@storybook/client-api';
import { Provider } from 'some-context-having-library';

addDecorator(storyFn => <Provider>{storyFn()}</Provider>);
```

The specific provider and what props you pass to it are specific to your use case.

**Comment by webber-jiang** [comment]
Thank you so much, that worked!! :)
