### ISSUE TITLE
automatic setup for Angular 9

### ISSUE THREAD

**Issue by jonathanohayon26** [storybookjs/storybook#10549]
**To Reproduce**
1. Run npx -p @storybook/cli sb init --type angular

Here is the exception:

*$ npx -p @storybook/cli sb init --type angular sb init - 
 "Adding storybook support to your "Angular" app
     Error: Could not find a default project in your Angular workspace. Add a project and re-run the installation. at default (/Users/jonathan.ohayon/.npm/_npx/59743/lib/node_modules/@storybook/cli/generators/ANGULAR/index.js:67:11)"

**Comment by shilman** [comment]
cc @yannbf

**Comment by yannbf** [comment]
Hey @jonathanohayon26, sorry that you're experiencing issues with Storybook. 
Could you please check in your `angular.json` if there is a property called `"defaultProject"`, and that it's correctly set? It's set by default when you initiate your app using angular CLI. It should look like this:
```js
{
  ...
  "projects": {
    "my-project": {},
    "my-project-e2e": {}
  },
  "defaultProject": "my-project", // <--- here!
  "schematics": {
    ...
  }
}
```

**Comment by jonathanohayon26** [comment]
Hey @yannbf 
The angular.json is correctly set with the "defaultProject": "my-project", // <--- here!
I simply create a new app angular 9 with cli and run "npx -p @storybook/cli sb init --type angular" as mentioned in the doc.
It is a pity that every new project in angular will meet this issue.
Thanks

**Comment by yannbf** [comment]
That's pretty odd. I created two new apps with angular CLI, versions 9 and 10, then in each I ran `npx -p @storybook/cli sb init --type angular` (by the way --type is optional, the cli should be able to detect that you're using an angular project), and the installation was successful. My suspicion is that maybe you ran the storybook install command in a different folder than the root folder of your project.

As reference, I just pushed the project example with angular 9 + storybook for you at: https://github.com/yannbf/angular9-storybook-example

**Comment by jonathanohayon26** [comment]
Hey @yannbf , I started from scratch, it works! Thanks

**Comment by glutengo** [comment]
@yannbf I have experienced the same and in my case the issue was that I was not in the root directory. Thanks to the suggestion in your comment I was able to run the command successfully. Maybe it is worth a note in the docs.

**Comment by safwaan-menk** [comment]
> @yannbf I have experienced the same and in my case the issue was that I was not in the root directory. Thanks to the suggestion in your comment I was able to run the command successfully. Maybe it is worth a note in the docs.

This is the solution so it should get marked as such and the documentation should be updated accordingly.  I had the same issue  and this was the answer. 🥂

**Comment by NsdHSO** [comment]
> @yannbf I have experienced the same and in my case the issue was that I was not in the root directory. Thanks to the suggestion in your comment I was able to run the command successfully. Maybe it is worth a note in the docs.

This is the answer

**Comment by jonniebigodes** [comment]
@NsdHSO the pull request is up. I've reviewed it and waiting on the pull request's author changes. If he/she doesn't address it within a reasonable timeframe. I'll push the changes myself in a pull request and address this issue. Hope you don't mind waiting a bit longer on this.

Stay safe

**Comment by esanchezdeidev** [comment]
How can i go to the root directory?

**Comment by ronaldohoch** [comment]
Hello!

I just have created a project with
`ng new project-name`
`cd project-name`
`npx sb init` <- Throwing me the error message:
![image](https://user-images.githubusercontent.com/2287371/186668477-c222af43-9ace-4df3-a196-1fbbfd734dc0.png)


But, angular have deprecated the defaultProject from angular.json:
![image](https://user-images.githubusercontent.com/2287371/186668381-cc5e8a65-2b1e-4c0b-be9b-d563df6c0559.png)

Check my environment: 
![image](https://user-images.githubusercontent.com/2287371/186668820-7cb3d9de-74f7-456a-b518-76a46db41881.png)

But, when i add the property, it install and run normally.
