### ISSUE TITLE
is it by design that changing a tab makes all tabs content rerender?

### ISSUE THREAD

**Issue by JadeTao** [storybookjs/storybook#10551]
i'm using `angular v9.1.0` `@storybook/angular v5.3.18` `@storybook/addon-notes v5.3.18`.

i'm writing components with fade in/out animations then come across this phenomenon.

critical code:
https://github.com/storybookjs/storybook/blob/master/lib/client-api/src/story_store.ts#L170

changing a tab will trigger `STORY_RENDER` event.

then storybook will render all 'canvas' and 'note' tab content.

can it just render the active tab?

p.s.
1. hope someone know what i'm talking about. or i have to create a demo to prove it.
2. it seems that code at `next` branch has changed. don't konw if this phenomenon still exists.

**Comment by shilman** [comment]
cc @tmeasday

**Comment by tmeasday** [comment]
hi @JadeTao, thanks for the report.

I don't really understand what you mean by "changing a tab"? Do you mean a tab in the browser? Or the addon panel? Or switching between docs / story mode?

As you mentioned, the code you highlighted doesn't exist any more in 6.0. Unless you meant switching from docs mode to story mode, in which case I think re-rendering the story is unavoidable..

**Comment by JadeTao** [comment]
![image](https://user-images.githubusercontent.com/11882787/81250606-ee204900-9053-11ea-94d2-4ab667ddd224.png)
@tmeasday  here are the tabs I meant.
Thanks anyway. I am looking forward to next version to see if the phenomenon will exist anymore.

**Comment by tmeasday** [comment]
Hmm, I suspect there is no fundamental reason when changing from an addon tab (Notes) to the current story tab (Canvas) it would re-render any contents of the tab. I suppose that's what you mean @JadeTao. 

@ndelangen do you have any insight into what's happening here? I don't really know what the mechanism to change the "active tab" is in this case. Is it URL based in the manager?

**Comment by JadeTao** [comment]
@tmeasday 
http://jader.xyz/ng-arwes/?path=/story/words--text
https://github.com/JadeTao/ng-arwes/commit/2e8aa2012b995eb0d95c43f1c89869df3128373b
you can toggle tabs and check the log(btw, there are 3 words components)

**Comment by ndelangen** [comment]
I think it can be considered a bug.

When the viewMode is changed, the URL changes.

The Preview component emits a message with { viewmode, id } to the iframe.

This then renders either the component in isolation or the docs.

If it switches from story to docs, it destroys the mounted story.

@shilman I do believe we can optimize this a bit actually. WDYT?

**Comment by shilman** [comment]
If the optimization also simplifies things, I'm for it. If it makes these more complicated, I don't think that's a good tradeoff.

**Comment by ndelangen** [comment]
@shilman I noticed this:

<img width="681" alt="Screenshot 2020-05-11 at 11 10 17" src="https://user-images.githubusercontent.com/3070389/81544602-08ba3100-9378-11ea-9a88-503a54ec1f91.png">

Emitting an event to the preview with an viewMode it cannot render is redundant..

I think we should have a look at this code, there's possibly a bug there, that re-renders the component when it's not needed:

https://github.com/storybookjs/storybook/blob/d51c19687f5f43a734eb170e9647a0ea78910bb7/lib/core/src/client/preview/StoryRenderer.tsx#L154-L211

**Comment by shilman** [comment]
@ndelangen why would it emit an viewMode that it can't render?

**Comment by ndelangen** [comment]
We currently don't make any assumptions about which viewmodes can be or can not be rendered.

**Comment by shilman** [comment]
Sure, but where does it even get the "info" viewMode from in that example? If something is misconfigured, is it up to the core to be filtering events? That sounds like needless complexity to me

**Comment by ndelangen** [comment]
that what addon-notes does

**Comment by shilman** [comment]
@ndelangen yes, but won't addon-notes know how to render that?

**Comment by ndelangen** [comment]
It does, the manager is just written to pass down whatever viewMode the manger's in. It doesn't assume that particular viewModes cannot be rendered by the preview.

I think we should change this behavior so the manager only emits when the viewMode is `story` or `docs`, nothing else.

**Comment by shilman** [comment]
Ok, I get it now. Thanks for explaining ❤️

**Comment by shilman** [comment]
Huzzah!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-beta.9 containing PR #10838 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.
