### ISSUE TITLE
No preview + error only in built app.

### ISSUE THREAD

**Issue by Dulan666** [storybookjs/storybook#10554]
**Describe the bug**
When the built app is running, stories are not loading. "No Preview" message is shown.

this error pops up in console:

![image](https://user-images.githubusercontent.com/15976939/80343863-4735f300-8884-11ea-9520-087045957914.png)

But this happens only when I'm running the build. In dev server there's no errors.

**To Reproduce**
1. run command `npm run build-storybook`
2. run command `serve storybook-static` (I'm using [serve ](https://www.npmjs.com/package/serve) npm package to start a sever)
3. open the browser
4. see error

**Expected behavior**
Two stories should be displayed.

**Screenshots**

![image](https://user-images.githubusercontent.com/15976939/80344306-fb377e00-8884-11ea-8bfb-03374df81aab.png)

**Code snippets**
**main.js**
```js
module.exports = {
  stories: ['../src/stories/**/*.stories.(js|mdx)'],
  addons: [
    '@storybook/addon-docs',
    '@storybook/addon-storysource',
    '@storybook/addon-actions',
    '@storybook/addon-links',
    '@storybook/addon-knobs',
    '@storybook/addon-viewport',
    '@storybook/addon-backgrounds',
    '@storybook/addon-a11y',
    '@storybook/addon-contexts',
    '@storybook/addon-notes/register-panel'
  ],
};
```
**manager.js**
```js
import { addons } from '@storybook/addons';

addons.setConfig({
  showRoots: true,
  panelPosition: 'right',
});
```
**preview.js**
```js
import { addParameters } from '@storybook/vue';
import Vue from 'vue';
import Vuex from 'vuex';
import 'p1-design-system/CSS Framework/framework.css'

Vue.use(Vuex);

addParameters({
  docs: {
    inlineStories: true,
    iframeHeight: '60px',
  },
});
```

**System:**

    OS: Windows 10 10.0.16299
    CPU: (4) x64 Intel(R) Core(TM) i3-8130U CPU @ 2.20GHz
  Binaries:
    Node: 10.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 41.16299.967.0
  npmPackages:
    @storybook/addon-a11y: 6.0.0-alpha.30 => 6.0.0-alpha.30
    @storybook/addon-actions: 6.0.0-alpha.30 => 6.0.0-alpha.30
    @storybook/addon-backgrounds: 6.0.0-alpha.30 => 6.0.0-alpha.30
    @storybook/addon-centered: 6.0.0-alpha.30 => 6.0.0-alpha.30
    @storybook/addon-contexts: 6.0.0-alpha.30 => 6.0.0-alpha.30
    @storybook/addon-docs: 6.0.0-alpha.30 => 6.0.0-alpha.30
    @storybook/addon-knobs: 6.0.0-alpha.30 => 6.0.0-alpha.30
    @storybook/addon-links: 6.0.0-alpha.30 => 6.0.0-alpha.30
    @storybook/addon-notes: ^5.3.18 => 5.3.18
    @storybook/addon-storyshots: 6.0.0-alpha.30 => 6.0.0-alpha.30
    @storybook/addon-storysource: 6.0.0-alpha.30 => 6.0.0-alpha.30
    @storybook/addon-viewport: 6.0.0-alpha.30 => 6.0.0-alpha.30
    @storybook/addons: 6.0.0-alpha.30 => 6.0.0-alpha.30
    @storybook/source-loader: 6.0.0-alpha.30 => 6.0.0-alpha.30
    @storybook/vue: 6.0.0-alpha.30 => 6.0.0-alpha.30

**Additional context**
I used this as the starter project: https://github.com/storybookjs/storybook/tree/next/examples/vue-kitchen-sink

**Comment by shilman** [comment]
@Dulan666 in the past `serve storybook-static` has been problematic. what happens if you run `cd storybook-static && serve` or `npx http-server storybook-static`?

**Comment by Dulan666** [comment]
> @Dulan666 in the past `serve storybook-static` has been problematic. what happens if you run `cd storybook-static && serve` or `npx http-server storybook-static`?

@shilman 
I tried : 
`storybook-static && serve` - same error
`npx http-server storybook-static` - error : This localhost page can’t be found
running with [Live Server](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer) extension for vs code - same error

**Comment by shilman** [comment]
Do you have a repro?

**Comment by Dulan666** [comment]
> Do you have a repro?

@shilman Can't share the original repo since it's a company application. but here I just created a copy of the same project.
https://github.com/Dulan666/design-system-storybook

**Comment by shilman** [comment]
I get the following error when I run `yarn storybook`:

```
Module not found: Error: Can't resolve 'p1-design-system/CSS Framework/framework.css' in '/Users/shilman/projects/testing/design-system-storybook/.storybook'
```

**Comment by Dulan666** [comment]
> I get the following error when I run `yarn storybook`:
> 
> > Module not found: Error: Can't resolve 'p1-design-system/CSS Framework/framework.css' in '/Users/shilman/projects/testing/design-system-storybook/.storybook'

Okay, updated. now it should work.

**Comment by shilman** [comment]
This works for me:

```
yarn build-storybook
npx http-server ./storybook-static/
``

**Comment by Dulan666** [comment]
`yarn build-storybook`
`npx http-server ./storybook-static/` 

![image](https://user-images.githubusercontent.com/15976939/80375899-a3196f80-88b6-11ea-86cc-41d77979fe25.png)

still no preview

**Comment by Dulan666** [comment]
Since I haven't got any luck with `TypeError: Cannot read property 'id' of undefined` error, I re-created my project with a fresh copy of [vue-kitchen-sink](https://github.com/storybookjs/storybook/tree/next/examples/vue-kitchen-sink)

now the prod. build is working fine. as @shilman mentioned app doesn't load on [serve](https://www.npmjs.com/package/serve) server. I had to use [http-server](https://www.npmjs.com/package/http-server)
