### ISSUE TITLE
Docs: pseudo class ":first-child" console error caused by Props table

### ISSUE THREAD

**Issue by igloude** [storybookjs/storybook#10565]
**Describe the bug**
The docs props table uses the `:first-child` pesudo class and pops a console error.

NOTE - the error will also pop any time a SSR-incompliant pseudo class is used. That is expected, and we want to keep it that way.

**To Reproduce**
1. Spin up `cra-ts-kitchen-sink`
2. Go to any mdx story with a props table (Button/Simple Button works)
3. Open console & observe errors
4. Inspect props table and see use of `:first-child` pseudo class

**Expected behavior**
No console errors coming from base Storybook code.

**System:**
```
Environment Info:

  System:
    OS: macOS 10.15.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Binaries:
    Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.13.6 - ~/.nvm/versions/node/v10.13.0/bin/npm
  Browsers:
    Chrome: 81.0.4044.122
    Edge: 81.0.416.64
    Firefox: 75.0
    Safari: 13.1
```

**Additional context**
This has been discussed in a handful of other issues, most recently #6998.

**Comment by shilman** [comment]
> NOTE - the error will also pop any time a SSR-incompliant pseudo class is used. That is expected, and we want to keep it that way.

What is the recommended resolution then?

**Comment by igloude** [comment]
> > NOTE - the error will also pop any time a SSR-incompliant pseudo class is used. That is expected, and we want to keep it that way.
> 
> What is the recommended resolution?

There are styles coming from the addon-docs Props table that pop the error - ideally there aren't console errors coming from an addon.

**Comment by igloude** [comment]
Apologies @shilman, that wasn't very clear. Midnight me isn't as descriptive I'd like sometimes 😆 

Two ideas for a resolution here:

1.  Suppress the error if its coming from Storybook's own styles
2. Re-write the addon-docs Props table styles so they aren't triggering the error.
