### ISSUE TITLE
Version all events

### ISSUE THREAD

**Issue by tmeasday** [storybookjs/storybook#10576]
- [ ] Ensure all events have a `v:1` field
 - [ ] Check when receiving an event it either has no `v` field (SB5 or less), or `v==1`. If it has a higher version number, log a warning that the event may not be handled correctly.

This is for refs in particular (in the future we may connect to SB7+ iframes), but also for addon compatibility.

@ndelangen suggested `v:6` to start. I'm OK with that, but we wouldn't want to change it to `v:7` in SB7 unless the event payload changed. So it might get confusing. I'm not sure.

**Comment by ndelangen** [comment]
@tmeasday after giving it some more thought, i think having a v:1 is better. versioning storybook separately from the event versions seems fair to me.
