### ISSUE TITLE
addon-docs Preview problems

### ISSUE THREAD

**Issue by kolisko** [storybookjs/storybook#10578]
**Describe the bug**
- Preview parametr *isExpanded* and *withSource* do not do anything
- Preview 'show code' shows unreadable code on black background because some strings are also black.

```
<Preview isExpanded withSource={{ dark: false }}>
  <Story name='Button Component' height='60px'>
    {{
      component: ButtonComponent,
      props: {
        title: text('text', 'Click Me'),
        btnClick: action('click')
      }
    }}
  </Story>
</Preview>
```

![image](https://user-images.githubusercontent.com/460056/80480252-947f9680-8950-11ea-9d96-12680063928b.png)

**To Reproduce**
1. Download https://github.com/kolisko/mvb-proto.git
2. npm run storybook
3. Click on Component/Button/ButtonComponent/Docs/Show Code
4. See unreadable source code

![image](https://user-images.githubusercontent.com/460056/80481165-394ea380-8952-11ea-9cd2-b4df952deb7c.png)

**Expected behavior**
1. See expanded preview with code by default
2. See the code readable
3. See the code with disabled dark mode

**System:**
```
Environment Info:

  System:
    OS: macOS 10.15.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v10.15.3/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
  Browsers:
    Chrome: 81.0.4044.122
    Firefox: 74.0.1
    Safari: 13.1
  npmPackages:
    @storybook/addon-actions: ^5.3.18 => 5.3.18 
    @storybook/addon-docs: ^5.3.18 => 5.3.18 
    @storybook/addon-knobs: ^5.3.18 => 5.3.18 
    @storybook/addon-links: ^5.3.18 => 5.3.18 
    @storybook/addon-notes: ^5.3.18 => 5.3.18 
    @storybook/addons: ^5.3.18 => 5.3.18 
    @storybook/angular: ^5.3.18 => 5.3.18 

```

**Comment by jsc144** [comment]
Ive run into the same behavior, it looks like it primarily effects string literals and variable names. 

If you comment out color:inherit in chrome devtools, the text all appears correctly until you refresh the page.

`pre code {
    font-size: inherit;
    /* color: inherit; */
    word-break: normal;
}`

**Comment by jsc144** [comment]
A quick workaround as an end user would be to create a style sheet with the following rule:

`pre code {
    color: #e83e8c;
}
` 
and import it in the .stories/preview.js file  (create it if it doesnt exist)
`import 'PATH_TO_STYLESHEET'`

**Comment by shilman** [comment]
Duplicate to #10211

**Comment by kolisko** [comment]
Thank you @jsc144 
I tried to disable color inherit using devtools, it works well. 
But workaround does not. Still see inherit. Any idea? I added to the ``.storybook/preview.ts``:

``import './showCodeFix.css';``

and to the ``showCodeFix.css``:

``pre code { color: #e83e8c; }``

**Comment by jsc144** [comment]
Can you see your rule being overwritten in devtools? You could try making it more specific, like pre code.hljs{}

**Comment by kolisko** [comment]
no, I can not see any change in devtools. Tried 

``pre code { color: #e83e8c; }``
``pre.hljs code { color: #e83e8c; }``
``pre.hljs code { color: #e83e8c !important; }``
``* { color: #e83e8c !important;}``

no change in devtools. Seems like it do not apply any style in imported css file.

**Comment by Xegyn** [comment]
For some reason, importing the css in `preview.ts` does not work for me either. What works for me is adding the style to `preview-head.html`.
Side note: It needs to be more specific than `pre code`.

`.storybook/preview-head.html`

```html
<style type="text/css">
  .sbdocs-preview pre code {
    color: #e83e8c;
  }
</style>
```
