### ISSUE TITLE
Bootup errors are not displayed

### ISSUE THREAD

**Issue by tmeasday** [storybookjs/storybook#10577]
Due to my refactoring of `StoryRenderer`, I guess.

**Comment by shilman** [comment]
Jeepers creepers!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-beta.5 containing PR #10659 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
