### ISSUE TITLE
@storybook/addon-docs [Angular] - Silently failing

### ISSUE THREAD

**Issue by sashafklein** [storybookjs/storybook#10582]
I have a pretty simple Angular app that defines some components and has a Storybook for them. wanted to add addon-docs, and followed [these instructions](https://github.com/storybookjs/storybook/tree/master/addons/docs/angular).

I ran into some installation snags (see below), but once those were resolved, the Storybook built without warning/error, but also without any Docs tab for my components.

At first, I ran into this error trying to run the `storybook` command (it still built):

```
info => Loading presets
WARN   Failed to load preset: "<dir>/node_modules/@storybook/addon-docs/preset.js" on level 1
ERR! Error: <dir>/node_modules/@storybook/addon-docs/preset.js is not a valid preset
```

After looking at [this issue](https://github.com/storybookjs/storybook/issues/9015), I changed `addons: ['@storybook/addon-docs']` in my `.storybook/main.js` file to `addons: ['@storybook/addon-docs/angular']`, and that fixed the build error. 

My stories are set up approximately as the documentation suggests, eg:

```ts
import { ButtonsComponent } from '../../app/buttons/buttons.component';

export default {
  title: 'Buttons',
  component: ButtonsComponent,
};

export const Dark = () => ({
  component: ButtonsComponent,
  props: {
    class: 'button--dark',
    linkUrl: 'http://www.google.com',
  },
});

// ...
```

After the above config fix, the build appears to work correctly (without warning/error), and creates a `documentation.json` file that looks complete and references some of my components. 

For example, I see this in it:

```json
            "src/stories/Components/7-Buttons.stories.ts": [
                {
                    "name": "Dark",
                    "ctype": "miscellaneous",
                    "subtype": "variable",
                    "file": "src/stories/Components/7-Buttons.stories.ts",
                    "type": "",
                    "defaultValue": "() => ({\n  component: ButtonsComponent,\n  props: {\n    class: 'button--dark',\n    linkUrl: 'http://www.google.com',\n  },\n})"
                },
```

But when I run the Storybook, I see no Docs tab. It's just the plain Story.

![image](https://user-images.githubusercontent.com/1746778/80534919-d6124080-8954-11ea-959a-4de92cb9eff7.png)

Environment info:

```
  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
  Binaries:
    Node: 10.19.0 - ~/.nvm/versions/node/v10.19.0/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v10.19.0/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v10.19.0/bin/npm
  Browsers:
    Chrome: 81.0.4044.122
    Firefox: 75.0
    Safari: 13.1
  npmPackages:
    @storybook/addon-actions: ^5.3.18 => 5.3.18 
    @storybook/addon-docs: ^6.0.0-alpha.45 => 6.0.0-alpha.45 
    @storybook/addon-links: ^5.3.18 => 5.3.18 
    @storybook/addon-notes: ^5.3.18 => 5.3.18 
    @storybook/addons: ^5.3.18 => 5.3.18 
    @storybook/angular: ^5.3.18 => 5.3.18 
```

> Note, to simplify this, I'm not currently using the other addons above.

**Comment by shilman** [comment]
@sashafklein all `@storybook/*` should be the same version number. try upgrading everything to `6.0.0-alpha.45` or downgrading `addon-docs`. be sure to clear out node_modules when you do. and if that still doesn't work, try regenerating lockfiles

**Comment by sashafklein** [comment]
Thanks. 

I removed the unused addons and then tried both lowering all the versions to `^5.3.18` and then bumping them all to `6.0.0-alpha.45`. No dice, unfortunately.

I'm on Angular 8. Does that potentially affect things? I'll try to push a reproduction repo.

**Comment by sashafklein** [comment]
OK. Got it! The change I made to fix that first error (`addons: ['@storybook/addon-docs']` to `addons: ['@storybook/addon-docs/angular']` in `.storybook/main.ts`) was unnecessary once I got version parity, and was silently breaking the docs addon. I reverted it, and the docs tab appeared!

**Comment by f3ltron** [comment]
got the same issue here for vuejs 

Failed to load preset: "@storybook/addon-docs/vue" on level 1
ERR! Error: Cannot find module '../dist/frameworks/common/index'

**Comment by f3ltron** [comment]
i have added '@storybook/addon-docs/vue' and all my @storybook/ are in `"^6.0.0-beta.2"`

**Comment by shilman** [comment]
@f3ltron did you try clearing node_modules and possibly regenerating lockfile?

**Comment by f3ltron** [comment]
Yes I tried it :$

**Comment by shilman** [comment]
Do you have a public repo I can look at?

**Comment by f3ltron** [comment]
Yes you can go here https://github.com/vuemontreal/vuemontreal. I rollback my pr on that but you have storybook in our project so maybe you can try a bit

**Comment by shilman** [comment]
@f3ltron https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#remove-framework-specific-docs-presets

**Comment by f3ltron** [comment]
i created an issue https://github.com/storybookjs/storybook/issues/10724. Really hard to work with :s

**Comment by dora-gt** [comment]
Why is this closed?
I think the bug is still there.

**Comment by NsdHSO** [comment]
@sashafklein  I had this issue, but what I did was only add this addon
![image](https://user-images.githubusercontent.com/37635083/187885188-67437575-6ede-429a-b552-11bf341a3215.png)
I hope it works for you too
