### ISSUE TITLE
Storybook 6.0 alpha breaks deployment in sub directories

### ISSUE THREAD

**Issue by lifeiscontent** [storybookjs/storybook#10595]
**Describe the bug**
Previously, I could create a `manager-head.html` and add this code to it:

```html
<script type="application/javascript">
  var hostname = window.location.hostname;
  if (hostname !== '' && hostname !== 'localhost') {
    var script = document.createElement('base');
    script.href = '/storybook/';
    document.head.appendChild(script);
  }
</script>
```

but since the 6.0 alpha there is a new script tag linking to `./sb_dll/storybook_ui_dll.js` which is now breaking what was once working.

**To Reproduce**
1. Create a `manager-head.html` file with the code I've pasted above
2. Deploy storybook to a subpath such as `/storybook`
3. Visit deployment

**Expected behavior**
A way to deploy storybook under a subpath.

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System:**
Please paste the results of `npx -p @storybook/cli@next sb info` here.

**Additional context**

**Comment by ndelangen** [comment]
you can pass `--no-dll` as a temporary "fix".

The base tag shouldn't be needed at all, I think.
Why do you add the base tag?

We deploy many storybooks under subdirs for testing storybook:
https://next--storybookjs.netlify.app/official-storybook/

This is certainly not broken.

**Comment by lifeiscontent** [comment]
@ndelangen I can add you to the monorepo I'm working in if you're curious, but essentially I have my deployments setup on now.sh and I believe Shilman told me you were the one who dug into the now.sh deployments of storybook. Anyway the base tag I believe was the recommendation on the the old docs. and as it stands the docs for deploying to now are busted as the example has been removed: https://storybook.js.org/docs/basics/exporting-storybook/ (dead link to example project)

my now.json looks like this:

```json
{
  "name": "lifetime",
  "version": 2,
  "builds": [
    { "src": "storybook/package.json", "use": "@now/static-build" },
    {
      "src": "website/package.json",
      "use": "@now/next"
    }
  ],
  "rewrites": [
    {
      "source": "/storybook/(.*)",
      "destination": "/storybook/storybook-static/$1"
    },
    {
      "source": "/(.*)",
      "destination": "/website/$1"
    }
  ]
}
```

**Comment by ndelangen** [comment]
@lifeiscontent could you try removing the base tag, see if it works without?

**Comment by lifeiscontent** [comment]
@ndelangen yep, will do once I can get storybook 6.0 to compile for me :)

**Comment by lifeiscontent** [comment]
@ndelangen here's a link to the build: https://lifetime-497nhbw39.now.sh/storybook

here's the main.js

```js
module.exports = {
  stories: ['../../packages/**/index.stories.tsx'],
  addons: [
    '@storybook/preset-typescript',
    '@storybook/addon-a11y',
    '@storybook/addon-actions',
    '@storybook/addon-knobs',
    '@storybook/addon-links',
    '@storybook/addon-storysource',
    '@storybook/addon-viewport'
  ],
};
```

let me know if I should add you to the repo to debug.
