### ISSUE TITLE
[v6] scroll to story with offset or different anchor

### ISSUE THREAD

**Issue by idbartosz** [storybookjs/storybook#10598]
**Is your feature request related to a problem? Please describe.**
Storybook introduced great MDX docs (shouts 📣for CSF with MDX) which enables to describe our stories in great details. Unfortunately this doesn't play well with the automatic scrolling functionality because it always scrolls to the story itself and there are cases where you'd like to scroll to the start of the story description instead.

**Describe the solution you'd like**
It would be nice to have an option to specify the offset which we want to add while scrolling to story.

**Describe alternatives you've considered**
Second idea isn't alternative but rather an additional advanced option to give the user ability to specify element to which he want to scroll while clicking story in the menu.

**Comment by shilman** [comment]
I think this already exists but needs some documentation.

There's a doc block called `Anchor`, which I believe you can pass the Story ID to, and override the existing scroll behavior.

https://github.com/storybookjs/storybook/blob/next/addons/docs/src/blocks/Anchor.tsx

cc @patricklafrance

**Comment by idbartosz** [comment]
Thanks @shilman, `Anchor` works but after scroll content is positioned at bottom of the screen. Would be nice to have some prop to change scroll behavior that the content begin on top of the page.
