### ISSUE TITLE
Panel section wrong background color

### ISSUE THREAD

**Issue by hipstersmoothie** [storybookjs/storybook#10597]
**Describe the bug**

In storybook 5.0 the background of the panel area was white on large screens, in 6.0 it is the gray sideabar color.

**Expected behavior**

Displays the same as 5.0

**Screenshots**

5.0

<img width="440" alt="Screen Shot 2020-04-30 at 12 10 03 AM" src="https://user-images.githubusercontent.com/1192452/80682451-62b51f80-8a77-11ea-98de-586675e56aaf.png">

6.0

<img width="342" alt="Screen Shot 2020-04-30 at 12 10 25 AM" src="https://user-images.githubusercontent.com/1192452/80682475-73659580-8a77-11ea-9026-791500a53a5e.png">

**System:**

storybook 6.0.0-beta.0

**Comment by shilman** [comment]
@ndelangen @ghengeveld is this related to the layout work?

**Comment by ghengeveld** [comment]
I checked the [PR](https://github.com/storybookjs/storybook/pull/9229/files) that introduced the layout option and it didn't touch the background.

**Comment by ndelangen** [comment]
I'll check it out, thanks @hipstersmoothie

**Comment by shilman** [comment]
Fixed in #10612 and released in 6.0-beta
