### ISSUE TITLE
Docs for Actions addon sparse for HTML Storybook

### ISSUE THREAD

**Issue by chrisj-skinner** [storybookjs/storybook#10594]
**Describe the bug**
I'm trying to get my head around using actions within a HTML version of storybook. https://github.com/storybookjs/storybook/tree/master/addons/actions#withactions-decorator

I have the action outputting a log to the actions addon window when I click on the `<button>` in my story but finding it very hard to implement an action decorator as I really want to be able do as is described at: https://github.com/storybookjs/storybook/tree/master/addons/actions#action-decorators

> If you wish to process action data before sending them over to the logger, you can do it with action decorators. 

My goal is to pull some data attributes from the action event and display these in the console.

**Expected behavior**
To be able to easily attach an action / function to my click event with some docs to guide me / demo code.

**Code snippets**
I have the following working code for using the `withActions` decorator.
**form.stories.js**
```
import markdown from './notes/accordian.stories.md';
import { withActions } from '@storybook/addon-actions';

export default {
  title: 'Components/Accordian',
  parameters: {
    componentSubtitle: 'Form',
  },
  decorators: [withActions('click [data-event])],
};

export const Primary = () =>
  `<form id="Form">
       <div class="form-group form-group--inline">
         <label for="name">Name</label>
         <input type="text" id="name" />
       </div>
       <div class="form-group form-group--inline">
         <button
           type="submit"
           data-event="genericGAEvent"
           data-category="form"
           data-action="FormSubmit"
           >Submit</button>
       </div>
     </form>`;
```

**System:**
  System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
  Binaries:
    Node: 10.15.1 - /usr/local/bin/node
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 81.0.4044.122
    Firefox: 75.0
    Safari: 13.0.4
  npmPackages:
    @storybook/addon-actions: ^5.3.18 => 5.3.18 
    @storybook/addon-console: ^1.2.1 => 1.2.1 
    @storybook/addon-docs: ^5.3.14 => 5.3.14 
    @storybook/addon-notes: ^5.3.18 => 5.3.18 
    @storybook/addon-viewport: ^5.3.14 => 5.3.14 
    @storybook/html: ^5.3.14 => 5.3.14 
    @storybook/storybook-deployer: ^2.8.3 => 2.8.3 

**Additional context**
What I'm aiming to do here is use **Actions addon** to display my datalayer events so they can be reviewed. Then have a js script to push them within a prod environment.

**Comment by shilman** [comment]
cc @jonspalmer

**Comment by jonspalmer** [comment]
@chrisj-skinner actions and "static' stories are something of a challenge and one that we've been working on the understand the use cases for. Similar issues came up was we're working on @storybook/sever and web components have the same challenges. 

As an aside in Storybook 6 you won't need to use the withActions decorator to configure actions. Instead you can use parameters:

```javascript
export default {
  title: 'Components/Accordian',
  parameters: {
    componentSubtitle: 'Form',
    actions: {
      handles: 'click [data-event]',
    }.
  },
};
```


To address your question. I don't believe we have out of the box support for action-decorators in static story environments like html/sever/web-components to "process" the action data. This is a use case we discussed about supporting but never felt we properly understood it to come up with an appropriate implementation. Could you explain it a little further? How would you use it and what does the processing get you? If you have an infinite choice of API how would you expect/like to interact with it?

**Comment by chrisj-skinner** [comment]
@jonspalmer I initially wanted this to log out data attributes on the element (used for my datalayer), but I've since found a neater and more efficient way to display and test this. Feel free to close this - thanks for your time in responding etc 👍

**Comment by jonspalmer** [comment]
@chrisj-skinner Could you perhaps share where you started and the solution you ended up with? We'd be really interested to collect use cases and alternative solutions so we can shape features in the future to line up with how folks are using Storybook.
