### ISSUE TITLE
Storybook 6.0 Alpha: `subcomponents` no longer works on default exports

### ISSUE THREAD

**Issue by lifeiscontent** [storybookjs/storybook#10596]
**Describe the bug**
In a recent release of 6.0 `subcomponents` no longer works on the default export.

**To Reproduce**
1. Create a story with a default export
2. Add `subcomponents`
3. See error

**Expected behavior**
expect to see subcomponents when using the `subcomponents` key in the default export.

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System:**
Please paste the results of `npx -p @storybook/cli@next sb info` here.

**Additional context**

**Comment by shilman** [comment]
Yippee!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-beta.1 containing PR #10608 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
