### ISSUE TITLE
Docs markdown table styles dont get applied in a yarn workspace

### ISSUE THREAD

**Issue by michaelwarren1106** [storybookjs/storybook#10600]
**Describe the bug**
I have a lerna/yarn workspaces repo set up with a storybook app as a top level package. Cant share the repo code because its corporate owned, but here's my folder structure:

```
/packages
   /docs
      .storybook
      ...storybook app stuff
   /core
lerna.json
package.json
```

If it helps here's the addons im using:

```
'@storybook/addon-knobs',
'@storybook/addon-a11y',
'@storybook/addon-actions',
'@storybook/addon-links',
'@storybook/addon-viewport',
{
   name: '@storybook/addon-docs',
      options: {
         configureJSX: true,
         babelOptions: {},
         sourceLoaderOptions: null,
      },
},
```

in my `stories.jsx` files im importing a README.md file for the `core` package that is autogenerated with a markdown table.

When the docs package is listed as a yarn workspace (not positive, but I dont think `useWorkspaces` in lerna.json matters), the markdown table style classes `sbdocs sbdocs-table css-<hash>` etc dont get added to the compiled HTML table element.

If I change nothing else about the storybook app config but remove storybook as a workspace and reinstall dependencies (manually or through lerna bootstrap, doesnt seem to matter), the styles get applied. I've also tried several custom yarn workspace configs in the docs repo with nothing working. I even tried to turn off hoisting for all packages like:

```
nohoist: [
   "**"
]
```

That `nohoist` seemed to correctly install all the storybook and other app dependencies in the storybook folder, but the docs table styles were still not applied. The readme file import works every time hoisting/workspace or not.

I havent tested other styles, but I believe those might also not always get applied correctly.

**Expected behavior**
The addon/docs table styles for markdown conversion should always be applied

**Screenshots**
No styles:
![image](https://user-images.githubusercontent.com/8377369/80719351-5ce82a00-8ac9-11ea-9623-be63c8ff3a86.png)

Styles:
![image](https://user-images.githubusercontent.com/8377369/80719431-79846200-8ac9-11ea-8055-b546a5e5f64f.png)

**System:**
```
Environment Info:

  System:
    OS: macOS 10.15.4
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
  Binaries:
    Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
    Yarn: 1.17.3 - ~/.nvm/versions/node/v10.16.3/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v10.16.3/bin/npm
  Browsers:
    Chrome: 81.0.4044.129
    Firefox: 75.0
    Safari: 13.1
```

**Comment by shilman** [comment]
That sounds weird--can't imagine what's causing the problem. Can you share what an example MDX/MD/Story looks like?

**Comment by michaelwarren1106** [comment]
yeah it was definitely weird to us too.

Here's a sample of our stories.jsx:

```
import React from 'react';
import { withKnobs } from '@storybook/addon-knobs';
import { withA11y } from '@storybook/addon-a11y';

import { useKnobs, decorateActions } from '../../storybook';
import page from '../readmes/component.md';


export default {
  title: 'Design System/Components/Component,
  decorators: [withA11y, withKnobs, decorateActions.withActions('our actions')],
  parameters: {
    options: {
      showPanel: true
    },
    docs: {
      page
    }
  }
};

export const example = () => {
  const knobs = useKnobs('component');

  return (
    <div>
      <h3 style={{ textTransform: 'capitalize' }}>{knobs.type}</h3>
      <component {...knobs}>
        Message goes here. <span slot="button-text">Acknowledge</span>
      </component>
    </div>
  );
};

```

**Comment by michaelwarren1106** [comment]
i should prolly add that we're using mdx, but the readme that gets pulled in is not an mdx file, nor does it have any jsx in it. The readme that gets imported is auto-generated by jsdocs as just plain-ole markdown...i've checked the contents of that file and it seems just fine, no weirdness

**Comment by shilman** [comment]
I'm not familiar with this usage:

```js
import page from '../readmes/component.md';
```

So you're saying that gets successfully rendered outside the workspace but not inside? What webpack loader are you using for Markdown? My first reaction is that this looks like a webpack config issue on your side and not a storybook issue per se. 🤷‍♂️

**Comment by michaelwarren1106** [comment]
We're using @mdx-js to load/transform the markdown as JSX. Here's our main.js:

```
const path = require('path');

const stringStyleToJsx = require('./stringStyleToJsx');

module.exports = {
  stories: [
    '../src/stories/general/introduction/*.stories.mdx',
    '../src/stories/general/framework-integration/*.stories.mdx',
    '../src/stories/general/design-system/*.stories.mdx',
    '../src/stories/components/**/*.stories.(js|ts|jsx|tsx|mdx)',
  ],
  addons: [
    '@storybook/addon-knobs',
    '@storybook/addon-a11y',
    '@storybook/addon-actions',
    '@storybook/addon-links',
    '@storybook/addon-viewport',
    {
      name: '@storybook/addon-docs',
      options: {
        configureJSX: true,
        babelOptions: {},
        sourceLoaderOptions: null,
      },
    },
  ],
  managerWebpack: async (config, options) => {
    config.optimization.splitChunks = {
      chunks: 'all',
      maxSize: 1024 * 1024,
    };

    return {
      ...config,
      stats: 'errors-warnings',
    };
  },
  webpackFinal: async (config) => {
    // configType has a value of 'DEVELOPMENT' or 'PRODUCTION'
    // You can change the configuration based on that.
    // 'PRODUCTION' is used when building the static version of storybook.


    const mdx = config.module.rules.find((rule) => {
      if (rule.test) {
        return rule.test.toString() === /\.mdx$/.toString();
      }
      return false;
    });
    mdx.test = /\.(md|mdx)$/;
    const babelLoader = mdx.use.find((loader) => loader.loader === 'babel-loader');
    babelLoader.options.plugins.push(stringStyleToJsx);

    config.module.rules.push({
      test: /\.scss$/,
      loaders: [
        'style-loader',
        'css-loader',
        {
          loader: 'sass-loader',
          options: {
            implementation: require('sass'),
            prependData: `
              @import 'src/globals/styles/colors';
              @import 'src/globals/styles/typography';
            `,
          },
        },
      ],
      include: path.resolve(__dirname, '../src'),
    });


    config.resolve.modules.push(path.join(__dirname, '../node_modules'));
    config.resolve.modules.push(path.join(__dirname, '../../../packages'));
    config.resolve.extensions.push('.ts', '.tsx', '.md', '.mdx');

    config.performance.hints = false;

    config.optimization.splitChunks = {
      chunks: 'all',
      maxSize: 1024 * 1024,
    };

    config.plugins = config.plugins.filter((plugin) => plugin.constructor.name !== 'ProgressPlugin');

    const filteredRules = config.module.rules.filter((rule) => {
      if (rule.test) {
        return rule.test.toString() !== /\.md$/.toString();
      }
      return false;
    });

    // Return the altered config
    return {
      ...config,
      node: {
        fs: 'empty',
      },
      stats: 'errors-warnings',
      module: {
        ...config.module,
        rules: [...filteredRules],
      },
    };
  },
};

```

**Comment by shilman** [comment]
@michaelwarren1106 have you run `yarn storybook --debug-webpack` on your setup? But eyeballing it all looks fine to me.

And to confirm: this works well outside the monorepo but not in it? The one thing I can think of is React context hooks failing due to incompatible react versions somehow. Under the hood, MDX uses React context via hooks, and it's possible that the `components` MDX context is getting lost somehow.

**Comment by michaelwarren1106** [comment]
so, let me be clear, it always "works" in that the app builds, compiles and renders without console errors...the only thing "wrong" is that the docs styles dont get applied when in a workspace...

I've run the webpack debug and everything seems fine from my perspective given that i think the issue is somewhere with the docs addon. I can run the exact same config, the only difference being an npm install with/without workspaces and get different visual results...

**Comment by shilman** [comment]
Can you do a standalone test to see if react hooks contexts are working for you? I wouldn't know how to debug it without a public repro
