### ISSUE TITLE
Addon-docs (React): component using withTheme HOC not working with <IconGallery> block

### ISSUE THREAD

**Issue by melanieseltzer** [storybookjs/storybook#10618]
**Describe the bug**
I have a component that uses the styled-components `withTheme` HOC:

```js
// Icon.tsx
import { withTheme } from 'styled-components'
import { themeGet } from '@styled-system/theme-get'

const Icon = ({
  theme,
  color = 'gray.900',
  ...more props
}: Props) => {
  // do stuff with the theme
  const themeColor = themeGet(`colors.${color}`)({ theme })
  return ...
}

export default withTheme(Icon)
```

I want to document the `<Icon>` component so I tried this:

```js
// Icon.stories.mdx
import { Meta, IconGallery, IconItem } from "@storybook/addon-docs/blocks"
import Icon from '../Icon'

<Meta title='Components/Icon' />

# Icon

<IconGallery>
  <IconItem name='rightArrow'>
    <Icon type="rightArrow" />
   </IconItem>
</IconGallery>
```

As you can see from the icon component, the default value for the `color` prop should be theme resolved. However I see this error in my storybook:

```
[withTheme] You are not using a ThemeProvider nor passing a theme prop or a theme in defaultProps in component class "Icon"
```

I actually do have a theme decorator added for stories in preview.js:

```js
import { addDecorator } from '@storybook/react'
import { ThemeDecorator } from './ThemeDecorator'

addDecorator(ThemeDecorator)
```

But this doesn't work for `<IconGallery>` since I'm not wrapping it in a `<Story>`. And from what I can tell, I'm not _supposed_ to wrap `<IconGallery>` and other such components in `<Story>` (I tried but it error'ed for me).

Any way to wrap `<IconGallery>` (and other blocks, I suppose) with the theme decorator?

**To Reproduce**
Company internal code, cannot provide a repro.

**Expected behavior**
`<IconGallery>` inherits the theme from a decorator (or similar).

**Screenshots**
<img width="500" alt="Screen Shot 2020-05-01 at 5 18 23 PM" src="https://user-images.githubusercontent.com/17421347/80850319-1f21f900-8bd0-11ea-990e-99fa8f23a483.png">

**Code snippets**
If applicable, add code samples to help explain your problem.

**System:**
```bash
Environment Info:

  System:
    OS: macOS 10.15.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
  Browsers:
    Chrome: 81.0.4044.129
    Firefox: 68.6.0
    Safari: 13.1

```

**Additional context**

**Comment by shilman** [comment]
Yes! Added some documentation -- please let me know if that works for you https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/recipes.md#overwriting-docs-container

**Comment by melanieseltzer** [comment]
@shilman Brilliant, this works great! Thanks a bunch 😄

**Comment by melanieseltzer** [comment]
Thought it might be useful to have this in the docs: https://github.com/storybookjs/storybook/pull/10645

**Comment by phil-tutti** [comment]
I actually needed exactly this again, but the links to the docs are only showing a 404 page. I also tried looking for the docs elsewhere, but couldn't find them. Have they been moved? Is there a different way to do this now?

**Comment by melanieseltzer** [comment]
@phil-tutti I think it lives here now: https://github.com/storybookjs/storybook/blob/next/code/addons/docs/docs/recipes.md#overwriting-docs-container

**Comment by phil-tutti** [comment]
> @phil-tutti I think it lives here now: https://github.com/storybookjs/storybook/blob/next/code/addons/docs/docs/recipes.md#overwriting-docs-container

They indeed are. Thank you very much for the help, much appreciated!
