### ISSUE TITLE
Mismatching versions of React & Renderer with react being a dependency in addons and core

### ISSUE THREAD

**Issue by Manishalexin** [storybookjs/storybook#10615]
There is a mismatching version of react & renderer in monorepos. React is set as a Dependency in Addons & Storybook core instead of it being a PeerDependency. And it's also set to update minor versions. So, React being a transitive dependency in a project with Storybook keeps a duplicate copy of whatever is the latest version of React in the project (assuming the project is not on the latest version of react).

**To Reproduce**

1. Create a monorepo with React & React Native
2. Add Storybook as a dependency in the project
3. React Native is set to use React 16.11.0 while the storybook uses the latest dependency of 16.13.1 ( as of today ) and it creates a duplicate copy of react in the project.

**More Details**
https://reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react

**Expected behavior**
React, React Dom & React Native should be a peer dependency in the core and addons projects.

**Screenshots**
![Storybook Error](https://user-images.githubusercontent.com/1404463/80838093-d12fe400-8c15-11ea-8736-f2bc6fb066d3.jpeg)

**System:**
Environment Info:

System:
OS: macOS 10.15.5
CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
Binaries:
Node: 10.16.0 - /usr/local/bin/node
Yarn: 1.22.4 - /usr/local/bin/yarn
npm: 6.14.4 - /usr/local/bin/npm
Browsers:
Chrome: 81.0.4044.129
Edge: 79.0.309.65
Firefox: 72.0.2
Safari: 13.1.1

EDIT:  Added more details from react docs on why and when this could be an issue.

**Comment by Manishalexin** [comment]
I can create a PR to move all the react, react native and react-dom dependencies to peerDependency in the next branch. Can someone review and let me know if this is the correct approach to solve this issue?

**Comment by shilman** [comment]
That's by design. Storybook's UI requires a specific version of React (16.x) but Storybook also supports libraries built in 15.x. Your `node_modules` is filled with multiple package versions based on what package is required--that's how  NPM works.

**Comment by Manishalexin** [comment]
I agree.

But the storybook for react is not supposed to run on its own without a react project including it right? So is it necessary that it packages react with it? Especially for all the addons? 
Shouldn't peerDependency enforce the inclusion of react with version lets say greater than 15.1 or if storybook supports any react version, it can always mark it as * in peerDependency?
@gaetanmaisse & @jmakGH refactored to include react and react-dom as peerDependency in **a11y addon** for a similar reason I believe. ( [a978bd2](https://github.com/storybookjs/storybook/commit/a978bd2) & [568421c](https://github.com/storybookjs/storybook/commit/568421c) )

**Comment by shilman** [comment]
@Manishalexin The entire Storybook UI is built in React
