### ISSUE TITLE
Docs - oneOf does not show correct data when using an imported variable

### ISSUE THREAD

**Issue by maeriens** [storybookjs/storybook#10620]
**Describe the bug**
 When passing down an array of strings to `oneOf` from a variable that is being imported, the docs shows the variable name (if passing an array directly) or the string `Object.keys(object)` if doing so with an object. 
 If the exact same variable is created in the same file as the propType definition, this does not happen.
 I did research around to see if this can be fixed by passing down some option or similar but could not find anything relevant to this issue.

**To Reproduce**
Example with an array:
1.Have Storybook installed with React and Docs addon
2.Create a simple component with a prop (e.g. 'color')
3.Add the PropType `oneOf` with an array of strings (e.g: ['blue', 'yellow', 'red'])
4.Generate the story for such component
5.Observe that `oneOf` shows the array items
6.Go back to the component and extract the `oneOf` to a variable declared above
7.Pass that variable to the`oneOf`proptype
8.Observe that `oneOf` shows the array items
9.Go back to the component, extract the variable created in 6 to another file and import it
10.Observe that `oneOf` now shows the name of the variable holding the array items

**Expected behavior**
The variables are shown even if the file is being imported from outside, instead of the variable name or the string `Object.keys(variableName)`.

**Code snippets w/Screenshots**
This works
```javascript
import React from 'react';
import PropTypes from 'prop-types';
const Button = ({children, color}) => <button style={{ color }}>{children}</button>;
Button.propTypes = {
  color: PropTypes.oneOf(['blue', 'yellow', 'red']),
};
```
![image](https://user-images.githubusercontent.com/5074186/80853292-03d1e080-8c06-11ea-885c-4eec0bcaca8b.png)

This ALSO works
```javascript
import React from 'react';
import PropTypes from 'prop-types';
const COLORS = ['blue', 'yellow', 'red'];
const Button = ({children, color}) => <button style={{ color }}>{children}</button>;
Button.propTypes = {
  color: PropTypes.oneOf(COLORS)
};
```
![image](https://user-images.githubusercontent.com/5074186/80853291-016f8680-8c06-11ea-863d-79bcde99df90.png)

This does not work. It will show the name of the variable (in this case, COLORS) if it is an array; and if it passed `Object.keys(someObject)` it will show that string.
```javascript
import React from 'react';
import PropTypes from 'prop-types';
import COLORS from './wherever'; // this being export const COLORS = ['blue', 'yellow', 'red'];
const Button = ({children, color}) => <button style={{ color }}>{children}</button>;
Button.propTypes = {
  color: PropTypes.oneOf(COLORS)
};
```
![image](https://user-images.githubusercontent.com/5074186/80853277-e9980280-8c05-11ea-83be-0d2bcf794cdd.png)

**System:**
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 10.16.1 - ~/.nvm/versions/node/v10.16.1/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.12.0 - ~/.nvm/versions/node/v10.16.1/bin/npm
  Browsers:
    Chrome: 81.0.4044.129
    Firefox: 68.5.0
    Safari: 13.1
  npmPackages:
    @storybook/addon-actions: ^5.3.18 => 5.3.18 
    @storybook/addon-docs: ^5.3.18 => 5.3.18 
    @storybook/addon-info: ^5.3.18 => 5.3.18 
    @storybook/addon-knobs: ^5.3.18 => 5.3.18 
    @storybook/addon-links: ^5.3.18 => 5.3.18 
    @storybook/addon-options: ^5.3.18 => 5.3.18 
    @storybook/addons: ^5.3.18 => 5.3.18 
    @storybook/react: ^5.3.18 => 5.3.18

**Comment by shilman** [comment]
I believe this is a known limitation: https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/props-tables.md#imported-types

**Comment by maeriens** [comment]
Just when I thought I had seen all the docs pages... there is another one I hadn't. 
Closing this then, it looks like that ticket is close to be finished. Thanks @shilman!

**Comment by shilman** [comment]
@maeriens I wish it was close to being finished! That PR has been open for over a year. We'll see what we can do, but in the meantime, it's just a limitation of that library and also of Storybook.

**Comment by Sm1t** [comment]
> I believe this is a known limitation: https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/props-tables.md#imported-types

updated link: https://github.com/storybookjs/storybook/tree/next/addons/docs/react#typescript-props-with-react-docgen

**Comment by maeriens** [comment]
If anyone comes wondering here about the state of this, this is being investigated in https://github.com/storybookjs/storybook/issues/14092.
