### ISSUE TITLE
HTML Presentation of React Component

### ISSUE THREAD

**Issue by vertic4l** [storybookjs/storybook#10636]
I'm using Storybook for React and thought about a possibility within docs / source addon to have the html representation of the current component.

Is there anyway to have one of these addons to show the html markup 
with ReactDOMServer.renderToStaticMarkup() ?

**Comment by napolux** [comment]
@vertic4l did you solve it? How?

**Comment by vertic4l** [comment]
@napolux Hey! I've found this handy addon for storybook which is the right approach to what i was looking for: https://github.com/whitespace-se/storybook-addon-html
