### ISSUE TITLE
Storybook 6.0.0-beta.0 bug: layout:centered affects all stories after visiting centered story

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#10641]
**Describe the bug**
When using `layout: 'centered'` as parameter, after opening the centralized block, all the others are centralized too. I tested using 6.0.0-beta.0 and v6.0.0-alpha.46.
_Originally posted by @AnnyCaroline in https://github.com/storybookjs/storybook/issues/10407#issuecomment-621504405_

**To Reproduce**
1 - Have more than one story
2 - Add `layout: centered` to one story:
```
export default {
  title: 'Button',
  component: Button,
  parameters: {
    layout: 'centered'
  }
};
```

3 - Make sure you have other story that does not have the layout property
4 - Select the centered story then select others (refer to the gif below)

**Expected behavior**
Only the specified story should be centered.

**Screenshots**
<img src="https://user-images.githubusercontent.com/17753656/80653359-6bdec600-8a50-11ea-9888-bb159fa17772.gif" />

**Comment by shilman** [comment]
Boo-yah!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-beta.6 containing PR #10643 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
