### ISSUE TITLE
Docs - PropTypes.exact reads 'exact' as prop description

### ISSUE THREAD

**Issue by maeriens** [storybookjs/storybook#10646]
**Describe the bug**
When using `PropTypes.exact({ ... })`, the description in the prop table inside the docs shows only the word **exact**. I am using sb@next (6.beta.2)

**To Reproduce**
1. Create a component inside a storybook
2. Add an exact propType
3. See it's associated doc page

**Expected behavior**
The exact props are shown - in this case, an object with `first` and `last` strings.

**Screenshots**
![image](https://user-images.githubusercontent.com/5074186/81031624-3d535780-8e63-11ea-8df1-01b5ab2f040e.png)

**Code snippets**
```javascript
const Message = ({user}) => <p>`Hello ${user.first} ${user.last}`</p>;
Button.propTypes = {
  user: PropTypes.exact({
    first: PropTypes.string,
    last: PropTypes.string
  })
}
```

**System:**
System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 10.16.1 - ~/.nvm/versions/node/v10.16.1/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.12.0 - ~/.nvm/versions/node/v10.16.1/bin/npm
  Browsers:
    Chrome: 81.0.4044.129
    Firefox: 68.5.0
    Safari: 13.1
  npmPackages:
    @storybook/addon-actions: ^6.0.0-beta.2 => 6.0.0-beta.2 
    @storybook/addon-docs: ^6.0.0-beta.2 => 6.0.0-beta.2 
    @storybook/addon-info: ^6.0.0-alpha.2 => 6.0.0-alpha.2 
    @storybook/addon-knobs: ^6.0.0-beta.2 => 6.0.0-beta.2 
    @storybook/addon-links: ^6.0.0-beta.2 => 6.0.0-beta.2 
    @storybook/addons: ^6.0.0-beta.2 => 6.0.0-beta.2 
    @storybook/react: ^6.0.0-beta.2 => 6.0.0-beta.2

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid.

Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
