### ISSUE TITLE
Configuration of Storybook logo link

### ISSUE THREAD

**Issue by ShkiperMe** [storybookjs/storybook#10647]
Link from Storybook logo opens in a new window. Is it possible to change it?
![Selection_108](https://user-images.githubusercontent.com/1908843/81035763-1584e380-8ea5-11ea-94e3-4a46a49d0147.jpg)

**Comment by shilman** [comment]
Yes. That's a ver old version of Storybook. In recent versions, set `brandUrl` to change the links: https://github.com/storybookjs/storybook/blob/9b7d7d271bdfea1e03c8958b6b7c0ce089b2ebcb/docs/src/pages/configurations/theming/index.md

**Comment by gerhat** [comment]
@shilman I believe the question if about how to remove `target="_blank"` from the url. I am facing this issue as well.

**Comment by afonsoalban** [comment]
Any news on this?

**Comment by vascomotaborges** [comment]
I have the same issue on v.6.3.4. Any updates?

**Comment by dimitrieh** [comment]
Looking for this as well

**Comment by yannickoo** [comment]
I was just trying to achieve the same and it seems next to `brandUrl` there is also the `brandTarget` option, so you could do the following 🎉

#### `.storybook/manager.js`

```
addons.setConfig({
  theme: create({
    brandUrl: '/index.html',
    brandTarget: '_self',
  })
})
```
