### ISSUE TITLE
@storybook/storyshots snaps have duplicated components

### ISSUE THREAD

**Issue by ybrodsky** [storybookjs/storybook#10640]
As the title says, storybook/storyshots is creating snaps with duplicated components. The number of files being created are fine, the problem is the content. So what should be 

    exports[`Storyshots Advertise Advertise 1`] = `
    Array [
      <div>something</div>
    ]

Ends up being 

    exports[`Storyshots Advertise Advertise 1`] = `
    Array [
      <div>something</div>,
      <div>something</div>,
    ]

This is happening in my local machine; if I run the tests again they pass because its always generating the snapshots the same way. However, if I run this in circleci it fails; logging into circleci via ssh and running the command to regenerate the snaps creates them correctly (no repeating components) and then the tests pass.

I am using:

    "next": "^9.3.4",
    "@storybook/addon-storyshots": "^5.3.18",
    "@storybook/addons": "^5.3.18",
    "@storybook/react": "^5.3.18",
    "jest": "^24.9.0",
    "enzyme": "^3.11.0",

Jest config:

    module.exports = {
      setupFiles: ['<rootDir>/jest.setup.js'],
      testPathIgnorePatterns: ['<rootDir>/.next/', '<rootDir>/node_modules/'],
      moduleFileExtensions: [
        "ts",
        "tsx",
        "js",
        "scss",
        "json",
        "jsx"
      ],
    
      transform: {
        '^.+\\.stories\\.js$': '@storybook/addon-storyshots/injectFileName',
        '^.+\\.(js|jsx|ts|tsx)$': '<rootDir>/node_modules/babel-jest',
        ".+\\.(css|styl|less|sass|scss)$": "jest-css-modules-transform",
      },
      transformIgnorePatterns: [
        '/node_modules/',
        '^.+\\.module\\.(css|sass|scss)$',
      ],
      moduleNameMapper: {
        '^.+\\.module\\.(css|sass|scss)$': 'identity-obj-proxy'
      },
    };

jest.setup.js

    import { configure } from 'enzyme';
    import Adapter from 'enzyme-adapter-react-16';
    
    configure({ adapter: new Adapter() });

Test file being run:

    import initStoryshots, { multiSnapshotWithOptions } from '@storybook/addon-storyshots';
    
    initStoryshots({
      test: multiSnapshotWithOptions(story => ({
        createNodeMock: (element) => {
          if (['input'].includes(element.type)) {
            // mock a focus function
            return {
              focus: () => {
              },
            };
          }
    
          return null;
        },
      })),
    });

Storybook main.js
```
module.exports = {
  stories: ['../src/components/**/*.stories.[tj]s'],
  addons: [
    '@storybook/addon-actions/register',
    '@storybook/addon-links/register',
    '@storybook/addon-knobs/register',
  ],
  webpackFinal: async (config) => {
    config.module.rules.push({
      test: /\.(ts|tsx)$/,
      loader: require.resolve('babel-loader'),
      options: {
        presets: [['react-app', { flow: false, typescript: true }]],
      },
    });
    config.resolve.extensions.push('.ts', '.tsx');

    config.module.rules.push({
      test: /\.scss$/,
      use: ['style-loader', 'css-loader', 'sass-loader'],
      include: path.resolve(__dirname, '../'),
    });

    return config;
  }
};
```

Node, yarn, npm version match in my PC and Circleci instance. The only difference is the OS, Debian vs my Ubuntu. I tested in another computer with IOS and the snaps are also generated incorrectly.

Any ideas what might be causing this duplicate snap code?

**System:**
```
  System:
    OS: Linux 4.18 Ubuntu 18.10 (Cosmic Cuttlefish)
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
  Browsers:
    Chrome: 80.0.3987.149
    Firefox: 74.0
  npmPackages:
    @storybook/addon-actions: ^5.3.18 => 5.3.18 
    @storybook/addon-knobs: ^5.3.18 => 5.3.18 
    @storybook/addon-links: ^5.3.18 => 5.3.18 
    @storybook/addon-storyshots: ^5.3.18 => 5.3.18 
    @storybook/addons: ^5.3.18 => 5.3.18 
    @storybook/react: ^5.3.18 => 5.3.18
```

**Comment by shilman** [comment]
Can you create a repro repo?

**Comment by ybrodsky** [comment]
Okay, nevermind.
The problem was in my code and I am an idiot.

Sorry.

**Comment by trainoasis** [comment]
What was the problem you had?

**Comment by ybrodsky** [comment]
I was calling the render story function twice. For some reason it was causing no effect in storybook itself but it did in the snaps.
