### ISSUE TITLE
Possibility to add toolbar to all stories

### ISSUE THREAD

**Issue by lipeavelar** [storybookjs/storybook#10658]
**Is your feature request related to a problem? Please describe.**
Based on #9593, it is not possible, by default, to use toolbar in all stories, so the solution is to customize the story page to show it in all stories, but to do this, we need to understand the framework and write a way to customize the wait to print stories for the page.

**Describe the solution you'd like**
I think it would be easier to only add a prop on Stories component, something like withToolbar from DocsStory, that put a toolbar on all stories.

**Are you able to assist bring the feature to reality?**
Yes, I can code the solution, since it is only to add a prop on Stories component, I think it is a pretty straightfoward and simple issue.

**Comment by lipeavelar** [comment]
@shilman Can I do anything to help in this issue?

**Comment by shilman** [comment]
@lipeavelar yes, i'd love to work with you on this. i think there are a couple ways to go here, both which might make the code better.

1. we can add `withToolbars` to the `Stories` doc block and the user can override the DocsPage. this is consistent with the current design and i'd be comfortable with that change.

2. we can make the `docs` parameters align with the props of the doc blocks. something like:
```js
export const Basic = () => ....
Basic.story = {
  parameters: {
    docs: {
        preview: {  withToolbars: true }
     }
  }
}
```
this change would ideally correspond to all core doc blocks, `preview`, `source`, `props`, etc. so it's a sweeping change and probably out of scope for 6.0

**Comment by lipeavelar** [comment]
@shilman The first solution seems the ideal to me, since we already have a pattern `title` and `includePrimary ` as props, I think that adding `withToolbars` and set its default value to false would respect customizing pattern we already have. Then, should we go with the first one?

**Comment by jbadan** [comment]
@lipeavelar I've found a relatively straightforward workaround for the meantime - you can use your own custom `DocsPage`, injecting this where the `Stories` block would traditionally go:

```
const context = useContext(DocsContext);

    // do not display disabled stories (dev only)
 const stories = context.storyStore?.getStoriesForKind(context.kind)?.filter((s) => !s.parameters?.docs?.disable)
....
{stories.map((story) => story && <DocsStory
            key={story.id}
            {...story}
            expanded
            withToolbar />)}
```
