### ISSUE TITLE
[v6.0.0-beta.2] React, CSF, ForwardRef cause infinite loading

### ISSUE THREAD

**Issue by tooppaaa** [storybookjs/storybook#10655]
**Describe the bug**
Infinite loading on startup

**To Reproduce**
Cherry pick https://github.com/storybookjs/storybook/commit/8c6172e1db5a58e8e5995d5e4a46201968eabdd2
Launch Storybook
See infinite scroll

**Expected behavior**
Storybook to load.

If you comment  ` component: ForwardedButton,`, launch and uncomment, you can see an error like "cannot read label from undefined"

**Comment by shilman** [comment]
Zoinks!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-beta.13 containing PR #10864 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
