### ISSUE TITLE
Addon-docs: Markdown tables do not support column alignment

### ISSUE THREAD

**Issue by zbream** [storybookjs/storybook#10666]
**Describe the bug**

When writing MDX in **addon-docs**, Markdown tables do not support column alignment using the typical [colon syntax](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#tables).

It seems like this was supported at one point, given the example below.

**To Reproduce**

The **official-storybook** demonstrates this bug: https://storybookjs.netlify.app/official-storybook/?path=/docs/addons-docs-markdown-docs--page#tables

Under header **Tables**, notice the "right aligned columns" example is not right-aligned.

Source: https://github.com/storybookjs/storybook/blob/next/examples/official-storybook/stories/addon-docs/markdown.stories.mdx

**Expected behavior**

Markdown tables should allow column alignment.

**Screenshots**

![image](https://user-images.githubusercontent.com/16364440/81225677-9a602200-8fb7-11ea-8534-1bde7d829f3a.png)

**Code snippets**

**System:**

**Additional context**

It seems that MDX itself supports this in the HTML that gets stamped out, but Storybook has styles to override it:

https://github.com/storybookjs/storybook/blob/next/lib/components/src/typography/DocumentFormatting.tsx#L184

**Comment by shilman** [comment]
Good catch @zbream. Mind submitting a small PR to delete that and we can use Chromatic to see what blows up?

**Comment by shilman** [comment]
Ta-da!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-beta.35 containing PR #11280 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.
