### ISSUE TITLE
Log or Throw error when stories fail to load.

### ISSUE THREAD

**Issue by lpoulter** [storybookjs/storybook#10664]
**Is your feature request related to a problem? Please describe.**
It's very hard to debug which story is causing the issue when no error is reported.

**Describe the solution you'd like**
A descriptive error or at least a stack trace.

**Additional context**
Stuck on this screen. 
<img width="320" alt="Screenshot 2020-05-06 at 16 52 49" src="https://user-images.githubusercontent.com/3940567/81199142-30954780-8fba-11ea-8c33-7f626ffe8153.png">
Webpack, no error
<img width="761" alt="Screenshot 2020-05-06 at 16 54 09" src="https://user-images.githubusercontent.com/3940567/81199189-3f7bfa00-8fba-11ea-974a-5b5854d64cce.png">

**Comment by ndelangen** [comment]
#10659

**Comment by shilman** [comment]
Yippee!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-beta.5 containing PR #10659 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
