### ISSUE TITLE
Add PREVIEW_URL support to other iframes

### ISSUE THREAD

**Issue by flynnham** [storybookjs/storybook#10660]
**Is your feature request related to a problem? Please describe.**
For Storybook apps that are hosted on remote CDNs, I've been finding it difficult to enable previews and stories without severe compromises.

**Describe the solution you'd like**

Make the `PREVIEW_URL` global available to other iframes as well

Allow developers to use env variables to override this value: https://github.com/storybookjs/storybook/blob/next/lib/components/src/blocks/Story.tsx#L6

It should look like the already existing: https://github.com/storybookjs/storybook/blob/b6136e1539c85d253504391a7d3f65e2c1239143/lib/ui/src/containers/preview.tsx#L45

Having this point to a custom location, either relative or remote, would likely help me and other developers who are using storybook in non standard ways. I.e mounted in a microfront-end, or hosted on a remote CDN.

**Describe alternatives you've considered**

Right now, I'm using a nginx proxy to match `/iframe.html` to an externally hosted resources. This isn't a suitable solution for a production environment.

**Are you able to assist bring the feature to reality?**
~Doing this now, if you could make it available in the next beta version that would be incredibly helpful.~ Just realized that this won't work because of same-origin policy.

**Additional context**

**Comment by flynnham** [comment]
This isn't a feature request, it's a bug. The `PREVIEW_URL` isn't being consistently handled.

**Comment by shilman** [comment]
@flynnham do you want to fix it?

**Comment by Alonski** [comment]
I would also like this feature :)

**Comment by SebDuf** [comment]
Is there a workaround available for this? I've just stumbled on this and thought changing the `PREVIEW_URL` would solve my issues, but this is still blocking me.

I'm trying to deploy Storybook under `/storybook/`, here's what I currently have:

`build-storybook --preview-url=/storybook/iframe.html`

and in `main.js`:

```
...
webpackFinal: (config, {configType}) => {
    if (configType === 'PRODUCTION') {
      config.output.publicPath = '/storybook/';
    }

    return config;
},
managerWebpack: (config, {configType}) => {
    if (configType === 'PRODUCTION') {
      config.output.publicPath = '/storybook/';
    }

    return config;
},

```
