### ISSUE TITLE
Addon docs shows too much story information

### ISSUE THREAD

**Issue by danielo515** [storybookjs/storybook#10665]
**Is your feature request related to a problem? 
I think that addon-docs shows too much info from the actual story function, specially compared with addon-info:

This is what addon-info shows, and what I would expect addon-docs to show too:

![image](https://user-images.githubusercontent.com/2270425/81203008-ae138480-8fc7-11ea-8df5-976724b01d1f.png)

Instead, this is what I get: 

![image](https://user-images.githubusercontent.com/2270425/81203256-0a76a400-8fc8-11ea-8b8c-8e3b7c72e91f.png)

It includes a lot of noise of the knobs addon that I'm using and doesn't add anything to the documentation.

**Describe the solution you'd like**
I really wish the old behavior of addon-info. That addon really nailed it in a lot of ways, It's a shame that you completely deprecated it without porting all of it's features

**Describe alternatives you've considered**
Currently I'm running both addons, which is not the best solution IMO. I would prefer to only have one running.

**Are you able to assist bring the feature to reality?**
Maybe

**Comment by shilman** [comment]
Addon-info didn't really nail anything. What you are showing is the reconstructed source of the current state of the runtime component, which works in a bunch of cases, but is react-specific, and brings up countless other issues that you can find by looking through old issues. i think we could bring back a mode for this in react, but would rather focus on doing it properly as part of #8342. Closing this issue as a duplicate to that.
