### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by kruthivijay31** [storybookjs/storybook#10678]
In this [document section](https://storybook.js.org/docs/formats/mdx-syntax/#documentation-only-mdx) “CSF Stories with MDX Docs” link is broken and returns 404.
<img width="1671" alt="Screen Shot 2020-05-07 at 3 00 11 PM" src="https://user-images.githubusercontent.com/14045986/81348736-837f0580-9073-11ea-86cb-aa3750ae8592.png">

**Comment by shilman** [comment]
Fixed
