### ISSUE TITLE
Storybook 5.3.+ with Angular 9.1 with IE 11 script syntax error

### ISSUE THREAD

**Issue by akapaddy** [storybookjs/storybook#10674]
**Describe the bug**
Using Storybook 5.3.+ with angular 9.1 - getting an ie11 script error targeting the story shown within the code snippet example.

Have attempted to update the webpack.config with the following configuration

``` Javascript
config.module.rules.push({
    test: /\.[t|j]s$/,
    exclude: /node_modules/,
    use: {
      loader: 'babel-loader',
      options: {
        presets: [
          [
            '@babel/preset-env',
            { shippedProposals: true, useBuiltIns: 'usage', corejs: '3' },
          ],
          '@babel/preset-typescript',
          '@babel/preset-react',
          '@babel/preset-flow',
        ],
        plugins: [
          [require('@babel/plugin-proposal-decorators'), { legacy: true }],
          [require('@babel/plugin-proposal-class-properties'), { loose: true }],
          require('@babel/plugin-proposal-export-default-from'),
          require('@babel/plugin-syntax-dynamic-import'),
          [
            require('@babel/plugin-proposal-object-rest-spread'),
            { loose: true, useBuiltIns: true },
          ],
          require('babel-plugin-macros'),
        ],
      },
    },
  });
```

But then getting a compile error with Angular Dependency Injection from injectable services in all browsers e.g. `Can't resolve all parameters for IconComponent: (?)` (IconComponent is on another story)

Without any service injection within a component, storybook is working in ie 11 and other browsers.

Would like to see if there is a fix or work around, to get ie11 working which will also work with service dependency injection

**Code snippets**
IE 11 - Error: Syntax error - story without webpack update
``` javascript
export const cta = () => ({
  template: `
    <button cta class=”primary" >{{ text }}</button>
  `,
  props: {
    text: text('Button text', 'CTA'),
  },
});
```

All browsers - Error: cant resolve parameters - story with webpack config updated
``` javascript

export default {
  title: 'Icon',
  decorators: [moduleMetadata({ providers: [IconService] })],
};

export const Default = () => ({
  component: IconComponent,
  props: {
    icon: 'star'
  },
});
```

IconComponent
``` javascript
import { IconType } from './icon-type';
import { IconService } from './icon.service';

@Component({
  selector: 'icon',
})
export class IconComponent {
  @Input() icon: IconType;

  constructor(private iconService: IconService) {}
```

**Additional context**
Have attempted to change tsconfig to target es5, but this causes template interpolation issues in ie 11, but other browsers still work.

**Comment by shilman** [comment]
Have you tried in 6.0-beta? We've recently made a bunch of IE related fixes that won't get ported back into 5.3.x and are better equipped to offer support help there.

**Comment by akapaddy** [comment]
Not tried with 6.0-beta as yet, but will do with this scenario and feedback here

**Comment by shilman** [comment]
Jeepers creepers!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-beta.9 containing PR #10725 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
