### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by kruthivijay31** [storybookjs/storybook#10675]
#10279 # Bug or support request summary

In this [document](https://storybook.js.org/docs/formats/mdx-syntax/) `Installation Instructions` link under `MDX files name` section is broken. 

**404 error**

<img width="1578" alt="Screen Shot 2020-05-07 at 11 24 41 AM" src="https://user-images.githubusercontent.com/14045986/81330744-63404e00-9055-11ea-8cad-8a53c56ed8ce.png">

**Comment by shilman** [comment]
Thanks, fixed!
