### ISSUE TITLE
https://www.webagim.com/

### ISSUE THREAD

**Issue by yusufezelcakan** [storybookjs/storybook#10698]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
https://www.webagim.com/
**Describe alternatives you've considered**
https://www.webagim.com/
**Are you able to assist bring the feature to reality?**
no | yes, I can...

**Additional context**
https://www.webagim.com/

**Comment by yannbf** [comment]
Closing this issue as it's not related at all with Storybook. Advertising like this are not cool! :)
