### ISSUE TITLE
[addon-knobs]: options knob with display: multi-select inferring wrong type info

### ISSUE THREAD

**Issue by jpmarra** [storybookjs/storybook#10692]
**Describe the bug**
When using the options knob with `{display: multi-select}`, it is inferring the return type from the values of the `valuesObj`, which need to be strings in order for the multi-select to work. The return type is being inferred as `string` when the multi-select actually returns an array of strings, so `string[]`.

**To Reproduce**
1. Create a `optionsKnob` with the display set to `multi-select`
2. pass in a values object with the labels and values you expect to see in the dropdown.
3. pass in a default value, an array of the values you expect to be auto-selected.
4. check the return value that `optionsKnob` returns

**Expected behavior**
Given that the `optionsKnob` returns an array of strings when it is being used as a multi-select, it should return the correct type information: `string[]`

**Screenshots**
The implementation:
![Screen Shot 2020-05-08 at 11 46 18 AM](https://user-images.githubusercontent.com/22504731/81423937-25116000-9123-11ea-9999-59c126d8bfd0.png)

The resulting console log of what `options` is returning:
![Screen Shot 2020-05-08 at 11 58 25 AM](https://user-images.githubusercontent.com/22504731/81423999-3e1a1100-9123-11ea-8cd6-69b50baa549c.png)

The type error:
![Screen Shot 2020-05-08 at 11 47 03 AM](https://user-images.githubusercontent.com/22504731/81423892-1460ea00-9123-11ea-969f-ab88813f2b7b.png)

The knob used in the UI is correct:
![Screen Shot 2020-05-08 at 12 05 21 PM](https://user-images.githubusercontent.com/22504731/81424659-4b83cb00-9124-11ea-89f8-9a5e90bcb25e.png)

**Code snippets**
```javascript
      const valueOptions = {
        facebook: "facebook",
        twitter: "twitter",
        email: "email",
        link: "link"
      };
      const defaultNetworks: string[] = [
        "facebook",
        "twitter",
        "email",
        "link"
      ];

      const networks: string[] = options( //should return an array of strings
        "Networks",
        valueOptions,
        defaultNetworks,
        {
          display: "multi-select"
        }
      );
```

**System:**
```bash
  System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 81.0.4044.138
    Safari: 13.1
  npmPackages:
    @storybook/addon-actions: 5.3.10 => 5.3.10 
    @storybook/addon-docs: 5.3.10 => 5.3.10 
    @storybook/addon-info: 5.3.10 => 5.3.10 
    @storybook/addon-knobs: 5.3.10 => 5.3.10 
    @storybook/addon-links: 5.3.10 => 5.3.10 
    @storybook/addon-options: 5.3.10 => 5.3.10 
    @storybook/addon-storysource: ^5.3.13 => 5.3.18 
    @storybook/addons: 5.3.10 => 5.3.10 
    @storybook/react: 5.3.10 => 5.3.10 
```

**Comment by shilman** [comment]
Hi gang, We’ve just released addon-controls in 6.0-beta!

Controls are portable, auto-generated knobs that are intended to replace addon-knobs long term.

- [Controls README](https://github.com/storybookjs/storybook/tree/next/addons/controls)
- [Migration instructions](https://github.com/storybookjs/storybook/blob/next/addons/controls/README.md#how-do-i-migrate-from-addon-knobs)

Please upgrade and try them out today. Thanks for your help and support getting this stable for release!

**Comment by shilman** [comment]
For anybody who is interested in Controls but don't know where to start, I've created a quick & dirty step-by-step walkthrough to go from a fresh CRA project to a working demo. Check it out:

=> [Storybook Controls w/ CRA & TypeScript](https://gist.github.com/shilman/69c1dd41a466bae137cc88bd2c6ef487)

There are also some "knobs to controls" migration docs in the Controls README:

=> [How do I migrate from addon-knobs?](https://github.com/storybookjs/storybook/blob/next/addons/controls/README.md#how-do-i-migrate-from-addon-knobs)

**Comment by t-moennich** [comment]
Until #12561 is resolved, some project are stuck to v5 and could need **this** to prevent some type juggling :)
