### ISSUE TITLE
source-loader cannot parse index.stories.tsx during build

### ISSUE THREAD

**Issue by lifeiscontent** [storybookjs/storybook#10717]
**Describe the bug**
@ndelangen and I worked together on setting up a `main.js` for typescript this is what we came up with:

```js
module.exports = {
  webpackFinal: async function (config) {
    config.module.rules = config.module.rules.slice(0, 2).concat(config.module.rules.slice(3));
    const babelLoader = config.module.rules.find(
      r => Array.isArray(r.use) && r.use.find(u => u.loader === 'babel-loader')
    );

    if (babelLoader) {
      babelLoader.test = /\.(mjs|jsx?|tsx?)$/;
    }

    config.resolve.extensions.unshift('.ts', '.tsx');

    return config;
  },
  babel: async function (config) {
    config.presets.push(require.resolve('@babel/preset-typescript'));
    config.plugins.push(require.resolve('styled-jsx/babel'));

    return config;
  },
  stories: ['../../packages/**/index.stories.tsx'],
  addons: [
    '@storybook/addon-a11y',
    '@storybook/addon-actions',
    '@storybook/addon-docs',
    '@storybook/addon-knobs',
    '@storybook/addon-links',
    '@storybook/addon-viewport',
  ],
};
```

when I deploy my storybook to `now.sh` I get an error saying source-loader cannot parse index.stories.tsx

**To Reproduce**
I don't have a clear way on how to debug this behavior, I can add someone from the storybook team to my project if needed.

**Expected behavior**
source-loader doesn't fall over

**Screenshots**
<img width="1792" alt="Screen Shot 2020-05-09 at 10 18 14 PM" src="https://user-images.githubusercontent.com/180963/81491389-fc808780-9242-11ea-8215-5fc188fc87ba.png">

**Code snippets**
If applicable, add code samples to help explain your problem.

one of the stories that won't parse:

```tsx
import React from 'react';
import { number, boolean } from '@storybook/addon-knobs';
import { LoaderBar, LoaderBarProgress } from '.';

export default {
  title: 'UI/Alerts/Loaders',
  component: LoaderBar,
  subcomponents: { LoaderBarProgress }
};

export const bar = (): JSX.Element => {
  return (
    <LoaderBar indeterminate={boolean('Indeterminate', false)}>
      <LoaderBarProgress
        value={number('Value', 1, { min: 0, max: 1, step: 0.01 })}
      />
    </LoaderBar>
  );
};
```

**System:**
Please paste the results of `npx -p @storybook/cli@next sb info` here.

Environment Info:

  System:
    OS: macOS 10.15.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 12.16.1 - ~/n/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.13.4 - ~/n/bin/npm
  Browsers:
    Firefox: 70.0
    Safari: 13.1

**Additional context**

**Comment by shilman** [comment]
Do you have a minimal repro i can look at? possibly following this? https://gist.github.com/yannbf/d7a32cfe697e71489db00bfd50e7ab5c

**Comment by ndelangen** [comment]
Please paste the full output of `--debug-webpack` ? 

https://storybook.js.org/docs/configurations/custom-webpack-config/#debug-the-default-webpack-config

**Comment by lifeiscontent** [comment]
@shilman @ndelangen this is my reproduction: https://github.com/lifeiscontent/sbnow if its easier for you, I can run --debug-webpack or do it in the format you want via codesandbox.

fwiw I was able to fix my issue by using the main.js from the official storybook example. So I suspect some functionality that we're adding there should be included in the defaults in order to fix these issues.

**Comment by shilman** [comment]
We've just released zero-config typescript support in 6.0-beta. Please upgrade and test it!

- [Release 6.0.0-beta.12+](https://github.com/storybookjs/storybook/releases/tag/v6.0.0-beta.12)
- [Migration instructions](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#zero-config-typescript)
- [Updated docs](https://github.com/storybookjs/storybook/blob/next/docs/src/pages/configurations/typescript-config/index.md)

Thanks for your help and support getting this stable for release!

**Comment by ndelangen** [comment]
@shilman we should investigate how much of the special needs code on the official example can be deleted now.

**Comment by shilman** [comment]
@ndelangen sounds good. i don't really know the background of that code

**Comment by ndelangen** [comment]
It's to make everything work together. I'm hoping at some point that all special webpack code can be removed.

**Comment by shilman** [comment]
@ndelangen FYI this was a critical bugfix that might have messed up the babel settings when you tried to delete that special webpack code: https://github.com/storybookjs/storybook/pull/11217. let's try again soon?
