### ISSUE TITLE
docs scrolling is slow

### ISSUE THREAD

**Issue by zhaoyao91** [storybookjs/storybook#10718]
**Describe the bug**

presets

- docs addon
- a component with many props
- some stories

it is slow to scroll to bottom story.

**Screenshots**

![Kapture 2020-05-10 at 15 19 05](https://user-images.githubusercontent.com/3808838/81493269-a1e23c80-92d1-11ea-97b7-f5482873d30f.gif)

**System:**

```
  System:
    OS: macOS 10.15.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.14.1/bin/npm
  Browsers:
    Chrome: 81.0.4044.138
    Safari: 13.1
```

**Additional context**

```
    "@storybook/addon-actions": "^5.3.18",
    "@storybook/addon-docs": "^5.3.18",
    "@storybook/addon-knobs": "^5.3.18",
    "@storybook/addon-links": "^5.3.18",
    "@storybook/addons": "^5.3.18",
    "@storybook/preset-create-react-app": "^2.1.1",
    "@storybook/react": "^5.3.18",
```

**Comment by eybbus** [comment]
Having the same experience. component with 101 props. when I click on the bottom story it takes 7 seconds to start the scroll animation.

If I click on the bottom story and start scrolling manually, half of the content is not rendered until 7 seconds have passed.

**Comment by eybbus** [comment]
mmh, my issue seems more connected to how many stories I have, less stories make the animation start sooner.
