### ISSUE TITLE
Tests won't pass on Windows 10 environment

### ISSUE THREAD

**Issue by jeroenheijmans** [storybookjs/storybook#10722]
While investigating #10721 I got to run the tests on my Windows 10 PC with Powershell. However, a whole bunch of tests fail out-of-the-box.

**To Reproduce**

1. Use Windows 10 + Powershell
2. Clone a fork of Storybook, `cd` into the folder
3. Run `yarn` and then `yarn bootstrap`
4. Run tests (use `yarn jest` to circumvent #10721)

- Expected: all tests pass.
- Actual: 7 test suites failed, 27 tests failed, 10 snapshots failed

**Output**

The summary of the test run is like this:

```
Test Suites: 7 failed, 111 passed, 118 total
Tests:       27 failed, 1351 passed, 1378 total
Snapshots:   10 failed, 395 passed, 405 total
Time:        41.495 s
Ran all test suites in 7 projects.
```

An example test failure that made me relate it to me using Windows:

```
 FAIL  app/react/src/server/cra-config.test.ts
  ● cra-config › when used with the default react-scripts package › should locate the react-scripts package

    expect(received).toEqual(expected) // deep equality

    Expected: "/test-project/node_modules/react-scripts"
    Received: "\\test-project\\node_modules"

      19 |
      20 |     it('should locate the react-scripts package', () => {
    > 21 |       expect(getReactScriptsPath({ noCache: true })).toEqual(
         |                                                      ^
      22 |         '/test-project/node_modules/react-scripts'
      23 |       );
      24 |     });

      at Object.<anonymous> (app/react/src/server/cra-config.test.ts:21:54)
```

**System:**

The results of `npx -p @storybook/cli@next sb info`:

```
  System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
  Binaries:
    Node: 12.16.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    @storybook/eslint-config-storybook: ^2.4.0 => 2.4.0
    @storybook/linter-config: ^2.5.0 => 2.5.0
```

**Additional Info**

A kind user helped me get to this stage on Discord, and [confirms my experience with failures while developing on Windows](https://discordapp.com/channels/486522875931656193/490770949910691862/709036863893143624)

**Comment by shilman** [comment]
@jeroenheijmans AFAIK none of the core maintainers develop on windows. Would you be interested in contributing fixes for the tests?

@patricklafrance You had this working on Windows before didn't you?

**Comment by patricklafrance** [comment]
@shilman running all the test suits never worked. It only worked when filtering to run specific test suits.

I believed those we fixed together were in babel-plugin-react-docgen.

**Comment by jeroenheijmans** [comment]
@shilman Thx for the confirmation that this doesn't work on Windows. 

I might try to squeeze in a PR for a warning to the guidelines that Windows is not well supported until a community member or maintainer stands up to get that fixed. But unfortunately I'm otherwise maxed out with OSS efforts on other libraries. I don't think I'm up for getting an OS supported in this large a framework at this point in time.

I realize and appreciate others might not have time or priority for this either, and am okay with that. Just wanted to report this issue for visibility, to help others encountering the same issue discover it. 

Thanks either way for a lovely project! <3
