### ISSUE TITLE
Error running `yarn test` on Windows 10 PowerShell

### ISSUE THREAD

**Issue by jeroenheijmans** [storybookjs/storybook#10721]
To assist with #10302 I've been following [the CONTRIBUTING.md guide](https://github.com/storybookjs/storybook/blob/next/CONTRIBUTING.md) on my Windows 10 1909 machine. I run into script errors when doing so.

**To Reproduce**

1. On Windows 10 Pro 64bit open PowerShell 5.1
2. Install `yarn` (I got 1.22.4)
3. Clone a fork of storybook with `git`, `cd` into that folder
4. Run `yarn`
5. Run `yarn` bootstrap and pick the default option
6. Run `yarn test` and pick the default option (or run `yarn test --core`, same result)

- Result: an error about `dirname` in the `test.js --core` command (details below)
- Expected: a clean test run

Here's the output from my command line:

```
[next ≡ +0 ~1 -0 !] D:\git\storybook>  yarn test
yarn run v1.22.4
$ node ./scripts/test.js
? Select which tests to run Core & Examples � (core)
D:\git\storybook\node_modules\.bin\jest:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at Module._compile (internal/modules/cjs/loader.js:811:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:931:10)
    at internal/main/run_main_module.js:17:11
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

With `git show` I can see that I'm on e54b70a2bc03581be2e910614b58de2399750c62

**System:**

The results of `npx -p @storybook/cli@next sb info` are:

```
[next ≡ +0 ~1 -0 !] D:\git\storybook>  npx -p @storybook/cli@next sb info

Environment Info:

  System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
  Binaries:
    Node: 12.8.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    @storybook/eslint-config-storybook: ^2.4.0 => 2.4.0
    @storybook/linter-config: ^2.5.0 => 2.5.0
```

PS. Edit: I've updated my Node install to "latest stable" available via Chocolatey (12.16.3), as well as NPM (6.14.5) but the issue persists.

PS. Edit: I've tried gitbash that comes with `git version 2.25.0.windows.1` but I get the same error.

**Comment by jeroenheijmans** [comment]
On a side note, I ran `yarn lint` to see if a simpler command _would_ work, but it spits out:

```
✖ 89466 problems (3 errors, 89463 warnings)
  0 errors and 89438 warnings potentially fixable with the `--fix` option.
```

After first listing all those 89k errors 😅. So ~perhaps~ probably I'm doing something wrong, and all of this is caused by missing a step in the guide? Or maybe developing Storybook on Windows is unsupported?

**Comment by jeroenheijmans** [comment]
Found that #6980 describes the same _symptoms_ but in a very different situation. So presuming this is not a duplicate? In any case, that issue was closed without ever being resolved.

**Comment by jeroenheijmans** [comment]
This symptom is described in [jest issue 3750](https://github.com/facebook/jest/issues/3750). Weirdly, a fix was merged last Feb 26, and since then version 26.0.0 has been released which [seems to be the version in use](https://github.com/storybookjs/storybook/blob/e54b70a2bc03581be2e910614b58de2399750c62/package.json#L187). So not sure why Storybook's `yarn test` command still runs into this issue.

**Comment by tooppaaa** [comment]
`yarn jest` does the same as `yarn test --core` if I'm right.

**Comment by jeroenheijmans** [comment]
Thanks for the help! I can confirm that tests then indeed run on my machine with `yarn jest`. I guess it doesn't do "the same" but something "similar", as the effect is different. I still suppose it's something that could be fixed (or at least mentioned in the contributing guidelines).

When I _do_ run the tests like that, a whole bunch of them fail. Some of them most likely related to my env being Windows, as they complain about failures around actual paths being different from expacted paths (forward vs backward slashes). I suppose that's a different issue though, will report a separate one.

**Comment by shilman** [comment]
w00t!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-beta.14 containing PR #10904 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
