### ISSUE TITLE
Display others properties in knobs

### ISSUE THREAD

**Issue by sanyaches** [storybookjs/storybook#10739]
**Describe the bug**
Assign knobs-properties from others stories 

**To Reproduce**
1. Go to some story
2. Click on tab 'Docs'
3. Change story
4. Click on tab 'Canvas'
5. See strange knobs-properties from other story

**Expected behavior**
See only current knobs-props

**Screenshots**
1 step) 
![image](https://user-images.githubusercontent.com/22271980/81663926-8190ba00-9458-11ea-86fe-c372d8b80e79.png)

2 step)
![image](https://user-images.githubusercontent.com/22271980/81664029-93725d00-9458-11ea-8a57-3d8698fbe8ab.png)

3,4,5 step)
![image](https://user-images.githubusercontent.com/22271980/81664176-b1d85880-9458-11ea-9c80-0a764a76b191.png)

Expected on 5 step(click refresh))
![image](https://user-images.githubusercontent.com/22271980/81664398-dd5b4300-9458-11ea-989f-20f5d134350f.png)

**Comment by shilman** [comment]
Hi gang, We’ve just released addon-controls in 6.0-beta!

Controls are portable, auto-generated knobs that are intended to replace addon-knobs long term.

- [Controls README](https://github.com/storybookjs/storybook/tree/next/addons/controls)
- [Migration instructions](https://github.com/storybookjs/storybook/blob/next/addons/controls/README.md#how-do-i-migrate-from-addon-knobs)

Please upgrade and try them out today. Thanks for your help and support getting this stable for release!

**Comment by shilman** [comment]
For anybody who is interested in Controls but don't know where to start, I've created a quick & dirty step-by-step walkthrough to go from a fresh CRA project to a working demo. Check it out:

=> [Storybook Controls w/ CRA & TypeScript](https://gist.github.com/shilman/69c1dd41a466bae137cc88bd2c6ef487)

There are also some "knobs to controls" migration docs in the Controls README:

=> [How do I migrate from addon-knobs?](https://github.com/storybookjs/storybook/blob/next/addons/controls/README.md#how-do-i-migrate-from-addon-knobs)

**Comment by sanyaches** [comment]
Thank you, @shilman! I will try to migrate from knobs to controls.
