### ISSUE TITLE
Partial component is not showing on Storybook but on development server

### ISSUE THREAD

**Issue by isaaclem** [storybookjs/storybook#10759]
I have a simple header component as below
```js
import './Header.css';
import React from 'react';
import styled from 'styled-components';
import ProgressBar from 'react-bootstrap/ProgressBar';
import { ArrowLeft, Info } from './icons';
import Burger from './Burger';

const Header = ({
  className
}) => (
  <div className={className}>
    <ArrowLeft />
    <ProgressBar style={{ width: '100%' }} now={30} />
    <Burger />
  </div>
);


const StyledHeader = styled(Header)`
  display: flex;
  justify-content: space-between;
  background-color: purple;
  align-items: center;
  height: 4rem;
  padding: 0 2rem;
`;

export default StyledHeader;
```

On localhost:3000, it shows below, which is exactly what I want

![image](https://user-images.githubusercontent.com/32945572/81762232-b9ead380-94fe-11ea-86be-a3454dd55684.png)

However, I got the different output on Storybook

![image](https://user-images.githubusercontent.com/32945572/81762248-c2dba500-94fe-11ea-9a3a-c7cb646a0f2e.png)

As you can tell, the `progressbar` is missing, I am wondering if anyone faced the similar issue before?

Below the storybook file `3-Header.stories.js`

```js
import React, { useState } from 'react';
import { action } from '@storybook/addon-actions';
import Header from '../components/Header';

export default { title: 'Header', component: Header };

function Parent({ children, ...props }) {
  const [open, setOpen] = useState();
  return <div>{children(open, setOpen)}</div>;
}

export const WithProgressBar = () => (
  <Parent>
    {(open, setOpen) => (
      <>
        <Header />
        {/* <Menu open={open} /> */}
      </>
    )}
  </Parent>
);
```

And below is the screenshot captured on react-devtool, ProgressBar does seems to be there?

![image](https://user-images.githubusercontent.com/32945572/81762276-d1c25780-94fe-11ea-9bf0-5c51a654f8eb.png)

**System:**
Environment Info:

  System:
    OS: macOS 10.15.4
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
  Binaries:
    Node: 14.1.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 81.0.4044.138
    Safari: 13.1
  npmPackages:
    @storybook/addon-actions: ^5.3.18 => 5.3.18 
    @storybook/addon-links: ^5.3.18 => 5.3.18 
    @storybook/addons: ^5.3.18 => 5.3.18 
    @storybook/preset-create-react-app: ^2.1.2 => 2.1.2 
    @storybook/react: ^5.3.18 => 5.3.18

**Comment by yannbf** [comment]
Hey @isaaclem, thanks for opening this issue! Would you be so kind to create a reproduction sandbox so that we can help you better?
You can follow [these instructions](https://gist.github.com/yannbf/d7a32cfe697e71489db00bfd50e7ab5c). Thanks!
