### ISSUE TITLE
Variable Viewport Definitions | @storybook/addon-viewport

### ISSUE THREAD

**Issue by samholmes** [storybookjs/storybook#10755]
#### Problem

Sometimes you are interested in how your component responds to variable viewport dimensions. Current there is no way to define a viewport definitions that would allow you to test out dimension ranges.

#### Solution

My Recommendation is two fold:

1. Allow for drag handles at the edges of the viewport UI to resize the viewport.
2. Allow for ranges in width/height fields on the viewport definitions

~~When selecting a viewport with a range set on the dimension fields, randomly select a value within this range, and restrict the resizing to the range(s) when using the drag handles.~~

When selecting a viewport with a range set on a dimension field (width/height), the following algorithm is used to choose the new dimension value:

* If the previous dimension is is greater than the any number in the range, then choose the upper bound value in the range. 
* If the previous dimension is is lesser than the any number in the range, then choose the lower bound value in the range.
* Otherwise, default to:
  1. No change
  2. Choose a random value in the range.

If the first option is chosen for the algorithm, then there is no randomize behavior for this feature. However, it could be a secondary feature via dedicated button for viewports with range dimensions.

### Regarding Contributions

Given more familiarity on the codebase and accepting such a feature to be in the scope of the project, I'm willing to assist with a PR.

**Comment by yannbf** [comment]
Hey @samholmes thanks for opening this issue!
That's an interesting idea, but I'm wondering if [this](https://github.com/storybookjs/storybook/tree/master/addons/viewport#add-new-device) doesn't already solve your problem? You can add as many custom viewports you want and either just use the custom ones or merge them together with the default ones from Storybook!

**Comment by samholmes** [comment]
@yannbf The custom viewports are static. My proposal is to allow for ranges and an ability to drag the viewport edges between those ranges.

**Comment by samholmes** [comment]
I'm going to update my proposal with an added behavior when going from a smaller size to a larger range size.

**Comment by samholmes** [comment]
Rather than closing the issues, is it possible to put them in an icebox after 30 days?

**Comment by shilman** [comment]
@samholmes are you working on it or do you want to work on it? if so let me know and I'm happy to reopen it.

**Comment by samholmes** [comment]
@shilman Is there decent documentation on the the addons API in order to fast track me into knowing enough to tackle the issue on my off time?

Also, why are all the packages maintained in a mono-repo? It seems disadvantageous to have all the issues tracked under a single repo when each addon could be maintained in its own repo.

**Comment by shilman** [comment]
@samholmes we're due for an addons documentation overhaul. in the meantime here's something https://www.learnstorybook.com/intro-to-storybook/react/en/creating-addons/

we maintain the packages in a monorepo so that it's easy to test changes and release coordinated versions that work together

**Comment by stad-nico** [comment]
Is this still something the teams plans on implementing?
