### ISSUE TITLE
Dark Mode in Main.js

### ISSUE THREAD

**Issue by TurtleWolf** [storybookjs/storybook#10763]
I'm using **_StoryBook_** for **_Create React App_**
I'm assuming the documentation is out of date? It says to change global theming in the **_`.storybook/manager.js`_** file but that's been merged into the **_`.storybook/main.js`_**. 
 I'm unsure of how to add the syntax to the file. It says **_theming_** comes **_out of the box_** but then it says to make sure I **_install_** theming. I've added, **_`info`_** and **_`knobs`_**.. **_`addons`_**, but I'm running it in all in a **_docker container_**. So each time I add a **_package_** I have to let the server rebuild and I'm not sure if I need to actually install theming or just import it into the **_`main`_** file and then what is the syntax to actually activate the default dark theme?
```
module.exports = {
  stories: ['../src/**/*.stories.js'],
  addons: [
    '@storybook/addon-actions',
    '@storybook/addon-knobs/register',
    '@storybook/addon-links',
    '@storybook/preset-create-react-app',
  ],
};
// //  documentation is out of date? This use to be set in a different file
// //  which has been merged into the main.js..
//   addons.setConfig({
//   theme: themes.dark,
```

**Comment by shilman** [comment]
Three are actually up to three files: `main.js`, `manager.js`/`preview.js` (both optional)

https://storybook.js.org/docs/configurations/overview/#manager--preview

The theming docs are up to date AFAIK
