### ISSUE TITLE
storyshots: Unexpected loaded state. Did you call `load` twice?

### ISSUE THREAD

**Issue by svewag** [storybookjs/storybook#10768]
**Describe the bug**
I have a setup using storyshots / storyshots-puppeteer and I want to make a screenshot of a story on multiple devices. When I execute the code I receive a warning.

>Unexpected loaded state. Did you call `load` twice?

**Expected behavior**
No warning.

**Screenshots**
<img width="917" alt="1" src="https://user-images.githubusercontent.com/155578/81857863-27305000-9563-11ea-8911-5a2324bcbc52.png">

**Code snippets**
```js
import initStoryshots from '@storybook/addon-storyshots'
import { devices } from 'puppeteer'

function createCustomizePage(pupDevice) {
  return page => page.emulate(pupDevice)
}

['iPad', 'iPhone X'].forEach(supportedDevice => {
  const pupDevice = devices[supportedDevice]

  const customizePage = createCustomizePage(pupDevice)

  initStoryshots({
    suite: `Image storyshots: ${pupDevice.name}`,
    test: imageSnapshot({
      customizePage,
    }),
  })
})
```

**System:**
System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.22.4 - 
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
  Browsers:
    Chrome: 81.0.4044.138
    Firefox: 67.0
    Safari: 13.1
  npmPackages:
    @storybook/addon-actions: 5.3.18 => 5.3.18
    @storybook/addon-backgrounds: 5.3.18 => 5.3.18
    @storybook/addon-centered: 5.3.18 => 5.3.18
    @storybook/addon-contexts: 5.3.18 => 5.3.18
    @storybook/addon-docs: 5.3.18 => 5.3.18
    @storybook/addon-knobs: 5.3.18 => 5.3.18
    @storybook/addon-links: 5.3.18 => 5.3.18
    @storybook/addon-notes: 5.3.18 => 5.3.18
    @storybook/addon-storyshots: 5.3.18 => 5.3.18
    @storybook/addon-storyshots-puppeteer: 5.3.18 => 5.3.18
    @storybook/addon-viewport: 5.3.18 => 5.3.18
    @storybook/addons: 5.3.18 => 5.3.18
    @storybook/codemod: 5.3.18 => 5.3.18
    @storybook/vue: 5.3.18 => 5.3.18

**Additional context**
The screenshots look correct. There are no errors.

**Comment by jaruesink** [comment]
Or if I'm just interested in having multiple test types utilizing storyshots, is there a way to suppress this warning?

**Comment by Hongbo-Miao** [comment]
Activate.

**Comment by DDDDDanica** [comment]
Got same issue with following config: 
```
    "@storybook/addon-actions": "5.3.18",
    "@storybook/addon-links": "5.3.18",
    "@storybook/addon-storyshots": "^5.3.18",
    "@storybook/addons": "5.3.18",
    "@storybook/preset-create-react-app": "^3.1.2",
    "@storybook/react": "5.3.18",
```

**Comment by DDDDDanica** [comment]
Update: tried `5.3.19` version, still got the same warning :(

**Comment by Hongbo-Miao** [comment]
Activate.

**Comment by jaxxreal** [comment]
I'm on `5.3.19` and have similar to @DDDDDanica config and also experiencing this issue.

**Comment by shilman** [comment]
Does the error still occur in 6.0-RC? `npx sb@next upgrade --prerelease`

**Comment by jaxxreal** [comment]
@shilman it says I cannot use both `main` and `config` files. But I figured out my issue. I loaded stories twice - once in config file and second time in main, using glob pattern. Removed manual loading from config and it works like charm! Thanks for pushing towards right direction!

**Comment by webholics** [comment]
The issue that its not possible to call `initStoryshots` twice within one test run which @svewag and @jaruesink mentioned still persists. We have it too.

**Comment by onimougwo** [comment]
So it's basically not possible to run both storyshots and A11y checks ? The code below wouldn't run both ? 

![image](https://user-images.githubusercontent.com/40011061/114406332-74eb7900-9b75-11eb-9a75-100b22ee11f2.png)

**Comment by maximegel** [comment]
I would really use a way to run tests for multiples viewports too. Is there a way to loop inside de `test` function instead? Something like:
```ts
initStoryshots({
  suite: `Visual tests`,
  test: options => ['iPad', 'iPhone X'].forEach(supportedDevice => imageSnapshot({ customizePage }),
})
```

**Comment by samboylett** [comment]
+1 for supporting multiple test suites. In the mean time, you can create a custom test suite and call as many tests as you want, it's a bit hacky but works:

```typescript
describe('Regression Tests', () => {
  let browser: Browser;

  async function getCustomBrowser() {
    if (!browser) {
      const puppeteer = require('puppeteer');

      browser = await puppeteer.launch({
        args: ['--no-sandbox ', '--disable-setuid-sandbox', '--disable-dev-shm-usage'],
        executablePath: undefined,
      });
    }

    return browser;
  }

  function runAllTests() {
    const tests = [
      multiSnapshotWithOptions(),
      imageSnapshot({
        getCustomBrowser,
        async customizePage(page) {
          page.setViewport({
            width: parseInt(styles.width),
            height: parseInt(styles.height),
          });
        },
      }),
    ];

    const hooks: any = {};

    const testFn: any = async (context: any) => {
      for (let test of tests) {
        await test(context);
      };
    };

    tests.forEach((localTestFn: any) => {
      ['beforeAll']
        .filter(name => localTestFn[name])
        .forEach(name => {
          hooks[name] = hooks[name] || [];
          hooks[name].push(localTestFn[name]);
        })
    })

    Object.keys(hooks).forEach(name => {
      testFn[name] = async () => {
        for (let fn of hooks[name]) {
          await fn();
        }
      };
    });

    return testFn;
  }

  afterAll(async () => {
    await browser.close();
  });

  initStoryshots({
    suite: 'Snapshots',
    test: runAllTests(),
  });
});```

**Comment by ndelangen** [comment]
The future of storyshots is the test-runner:
https://storybook.js.org/docs/react/writing-tests/test-runner#page-top

And use the play function for expectations:
https://storybook.js.org/docs/react/writing-stories/play-function#page-top

We will not be making any improvement / changes to storyshots.
