### ISSUE TITLE
addon-storysource - Not showing stories imported from other source files.

### ISSUE THREAD

**Issue by nanandn** [storybookjs/storybook#10769]
Storybook addons "storysource" and "docs" not loading the story source imported from other files. In the example shown below, storybook preview and docs story panel renders the component, but storysource addon panel is not loading the source. Just shows "loading source..." and docs page shows "no code available". 

My example seems very simple to be included in the main story file. But in reality, each of my example may have some more logic/code. I'd like to put them in separate files and import it in the main story. 

Is this possible?

For example, my story is "MyComponent.stories.jsx".

```
import React from "react";
import MyComponent from "mycomponent";
import SimpleComponent from "./Simple";
import AdvancedComponent from "./Advanced";

export default {
    title: "Components",
    component: MyComponent
};

export {
    SimpleComponent,
    AdvancedComponent
}

```

Simple.jsx

```
import React from 'react';

export default () => <MyComponent {...props}/>;
```

Advanced.jsx

```
import React from 'react';

export default () => <MyComponent {...props} {...advancedProps}/>;
```

- @storybook/react  5.3.18
- @storybook/addon-storysource 5.3.1.8
- @storybook/addon-docs 5.3.1.8

**Comment by shilman** [comment]
Not possible in Storysource

**Comment by grit96** [comment]
There's a conversation in #3566 about adding support for this.
