### ISSUE TITLE
Static folder copied before creation

### ISSUE THREAD

**Issue by Bruno-Tavares-Bose** [storybookjs/storybook#10773]
**Describe the bug**
Building the standalone Storybook, in a clean repo, will try to copy the static folder before it's creation.

**To Reproduce**
1. Having a clean (no `node_modules`, no `build`/`dist` folder) repo with Storybook configured
1. Run `yarn` or `npm install` to install dependencies
1. Run your build command (`yarn build` for example)
1. Run your build Storybook command with static folder (`yarn build-storybook -s ./public -o output` for example)
-  note that, `public` folder, is not created yet.

**Expected behavior**
The content of `public` folder would be inside `output` folder

**System:**
```
Environment Info:

  System:
    OS: macOS 10.15.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 5.1.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 81.0.4044.138
    Safari: 13.1
  npmPackages:
    @storybook/addon-a11y: 6.0.0-beta.3 => 6.0.0-beta.3 
    @storybook/addon-actions: 6.0.0-beta.3 => 6.0.0-beta.3 
    @storybook/addon-docs: 6.0.0-beta.3 => 6.0.0-beta.3 
    @storybook/addon-essentials: 6.0.0-beta.3 => 6.0.0-beta.3 
    @storybook/addon-links: 6.0.0-beta.3 => 6.0.0-beta.3 
    @storybook/addon-storyshots: 6.0.0-beta.3 => 6.0.0-beta.3 
    @storybook/addon-storyshots-puppeteer: 6.0.0-beta.3 => 6.0.0-beta.3 
    @storybook/addon-storysource: 6.0.0-beta.3 => 6.0.0-beta.3 
    @storybook/addons: 6.0.0-beta.3 => 6.0.0-beta.3 
    @storybook/react: 6.0.0-beta.3 => 6.0.0-beta.3 
    @storybook/theming: 6.0.0-beta.3 => 6.0.0-beta.3 
    @storybook/vue: 6.0.0-beta.3 => 6.0.0-beta.3
```

**Additional context**
I have tried to change [build-static](https://github.com/storybookjs/storybook/blob/next/lib/core/src/server/build-static.js) directly in my `node_module`, like this:
```javascript
async function buildStaticStandalone(options) {
  var staticDir = options.staticDir,
      configDir = options.configDir,
      packageJson = options.packageJson;
  var configType = 'PRODUCTION';
  var outputDir = _path.default.isAbsolute(options.outputDir) ? options.outputDir : _path.default.join(process.cwd(), options.outputDir);

  var dllPath = _path.default.join(__dirname, '../../dll/*');

  var defaultFavIcon = require.resolve('./public/favicon.ico');

  prepareFilesStructure(outputDir, defaultFavIcon);

  _nodeLogger.logger.info(`=> Copying prebuild dll's..`);

  _shelljs.default.cp('-r', dllPath, _path.default.join(outputDir, 'sb_dll'));

  await buildManager(configType, outputDir, configDir, options);
  await buildPreview(configType, outputDir, packageJson, options);
  await copyAllStaticFiles(staticDir, outputDir);

  _nodeLogger.logger.info(`=> Output directory: ${outputDir}`);
}
```
moving the `copyAllStaticFiles` to the end of the process, and it seems to fix it.
If you don't see any issue that this can create, I can open a PR with this change.

**Comment by shilman** [comment]
cc @CodeByAlex is this related to the issue you found?

**Comment by CodeByAlex** [comment]
@shilman This was not the same issue I was seeing

**Comment by Bruno-Tavares-Bose** [comment]
I think I figure out what I was doing wrong... I was assuming the assets folder that was created in build time (SVG) was "static", and of course, it's not.

Nevertheless, we could consider this change, if it don't break nothing, and make it possible to serve building assets. And we may close this issue.
