### ISSUE TITLE
[v6.0.0-beta.6] Routing not working on static build

### ISSUE THREAD

**Issue by lpoulter** [storybookjs/storybook#10782]
**Describe the bug**
Routing not working on static build. This was last known to work on v6.0.0-alpha.30. No issues in dev mode.

**To Reproduce**
run `build-storybook`
Navigate between stories, URL changes but the page does not. Manual refresh caused the story to load.

**Expected behavior**
Stories change on navigation. 

**Example**
![2020-05-14 17 49 37](https://user-images.githubusercontent.com/3940567/81962420-9e212380-960b-11ea-96b6-bde46a73c001.gif)

**System:**
Environment Info:

  System:
    OS: macOS Mojave 10.14.3
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
  Binaries:
    Node: 13.3.0 - ~/.nvm/versions/node/v13.3.0/bin/node
    Yarn: 1.15.2 - ~/.yarn/bin/yarn
    npm: 6.13.1 - ~/.nvm/versions/node/v13.3.0/bin/npm
  Browsers:
    Chrome: 81.0.4044.138
    Edge: 81.0.416.72
    Firefox: 76.0
    Safari: 12.0.3
  npmPackages:
    @storybook/addon-docs: ^6.0.0-beta.6 => 6.0.0-beta.6
    @storybook/addon-knobs: ^6.0.0-beta.6 => 6.0.0-beta.6
    @storybook/react: ^6.0.0-beta.6 => 6.0.0-beta.6

**Comment by shilman** [comment]
Guessing this is a composition thing @ndelangen

**Comment by ndelangen** [comment]
Investigating now..

**Comment by ndelangen** [comment]
I cannot reproduce

i tried the official example & dev-kit example.. @lpoulter can you supply a reproduction repo?

**Comment by lpoulter** [comment]
I'll see if I can reproduce in another repo. Here is the [preview build](https://5ebd8ade0210295129008087--axiom-react.netlify.app/) with the error I describe if that helps.

**Comment by lpoulter** [comment]
@ndelangen here is [the repo](https://github.com/BrandwatchLtd/axiom-react) with the bug.
```
yarn build:esm:packages
yarn build:storybook
```
Will build the static site. No errors on build, things that might be relevant,
* It's a monorepo
* The static build is large `10.9 MiB`

**Comment by lpoulter** [comment]
Turns out regenerating my `yarn.lock` file fixed this. I don't really know why!
