### ISSUE TITLE
Addon-docs: Add `layout` parameter support to `Preview`

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#10789]
Storybook has a new `layout` parameter feature built-in in 6.0 [that replaces addon-centered](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#removed-addon-centered).

The `Preview` component should respect the valid values: 'centered', 'padded', 'fullscreen'

Here are the layouts the Canvas uses for each value: 

https://github.com/storybookjs/storybook/blob/next/lib/core/src/client/preview/StoryRenderer.tsx#L24-L52

- [ ] Add support
- [ ] Make sure there are test cases in `official-storybook`

Follow up to https://github.com/storybookjs/storybook/issues/8128

**Comment by shilman** [comment]
cc @yannbf

**Comment by PascalPixel** [comment]
Seems to be done in #10801

**Comment by shilman** [comment]
Thanks @PascalPixel -- indeed!
