### ISSUE TITLE
@storybook/addon-knobs: color selector doesn't work in IE11

### ISSUE THREAD

**Issue by vandhuymartins** [storybookjs/storybook#10792]
**Describe the bug**
The color selector doesn't work in IE11. It closes immediately when clicked. The value does not change.

**To Reproduce**
Try to change color with corresponding control in IE11.

**Expected behavior**
Color is changed.

**Actual behavior**
Nothing happens.

**System**
OS: Windows 10 Pro
Device: Desktop w/ AMD Ryzen 5 16GB RAM
Browser: Internet Explorer 11 | Version 11.836
Framework: React
Addons: knobs
Version: 5.2.5

**Relates to**
[#5390](https://github.com/storybookjs/storybook/issues/5390) - [#6992](https://github.com/storybookjs/storybook/issues/6992)
This same bug was happening in Firefox in a previous version and it was fixed.

**Comment by shilman** [comment]
Hi gang, We’ve just released addon-controls in 6.0-beta!

Controls are portable, auto-generated knobs that are intended to replace addon-knobs long term.

- [Controls README](https://github.com/storybookjs/storybook/tree/next/addons/controls)
- [Migration instructions](https://github.com/storybookjs/storybook/blob/next/addons/controls/README.md#how-do-i-migrate-from-addon-knobs)

Please upgrade and try them out today. Thanks for your help and support getting this stable for release!

**Comment by shilman** [comment]
For anybody who is interested in Controls but don't know where to start, I've created a quick & dirty step-by-step walkthrough to go from a fresh CRA project to a working demo. Check it out:

=> [Storybook Controls w/ CRA & TypeScript](https://gist.github.com/shilman/69c1dd41a466bae137cc88bd2c6ef487)

There are also some "knobs to controls" migration docs in the Controls README:

=> [How do I migrate from addon-knobs?](https://github.com/storybookjs/storybook/blob/next/addons/controls/README.md#how-do-i-migrate-from-addon-knobs)
