### ISSUE TITLE
Storybook zero-config typescript support

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#10790]
- [x] Base Webpack config gets support for TypeScript via `@babel/preset-typescript`
- [x] For Angular and Vue, base support is disabled.
- [x] Support is added into Vue framework.
- [x] Checking via `ts-fork-checker-webpack-plugin` should be opt-in
- [x] Add support for `ts-fork-checker-webpack-plugin` options
- [x] For 6.0, TS preset is no more - we'll ignore and warn if detected
- [x] For React, `react-docgen-typescript-loader` needs to be added - with optional flag to use `babel-plugin-react-docgen` instead.
- [ ] Allow passing options for `react-docgen-typescript-loader` (React)
- [ ] Allow passing options for `ts-loader` (Vue)
- [ ] Add example for Vue with TypeScript.
- [ ] Document new TS support.
- [ ] Add `react-docgen-typescript-loader` to CRA preset.

For flags, we will use a typescript object in `main.js`:

```ts
interface TypescriptOptions {
  check?: boolean;
  docgen?: 'none' | 'react-docgen' | 'react-docgen-typescript';
}

// default values
export const typescript: TypescriptOptions = {
  check: false,
  docgen: 'react-docgen-typescript'
}
```

**👉 [Original spec](https://docs.google.com/document/d/12ZgeB41t67PDPTQO3QoXt3wrSxgsRMcbqsL9nAt6MoU/edit?usp=sharing)**

**Comment by shilman** [comment]
Yowza!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-beta.12 containing PR #10813 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by EdenTurgeman** [comment]
@shilman This looks amazing, I've been following this as closely as possible and it's awesome to see storybook getting to this level.
One thing that is missing imo is after reading the doc + spec it is still unclear to me how to configure storybook to use react-docgen typescript loader in the _"new way"_ since my old webpack rule is still slow and buggy and exporting the typescript object from `main.js` (as the spec suggests) seems to do nothing.

**Comment by EdenTurgeman** [comment]
@shilman 
First of all I have to say, I've been following this for a while now and it's amazing to see how much this has progressed!.
Secondly, I'm still a bit confused as to how this change works? after exporting the typescript object from `main.ts` it seems to have no effect on the compile time and the docs tab doesn't show up. 
![image](https://user-images.githubusercontent.com/12447231/82754854-6c147c00-9dd8-11ea-8d75-f46d7958e71f.png)

Lastly, It would be great if you could allow passing the propfilter function directly from there so people can filter unwanted props as this gets better.

**Comment by shilman** [comment]
@EdenTurgeman the purpose of this issue is to:
1) load typescript stories/components without any configuration needed on the user's part
2) allow you to configure which docgen you use since neither option is perfect and there are pros and cons to each choice

To configure addon-docs you need to add the following to your `.storybook/main.js`:

```js
module.exports = {
  addons: ['@storybook/addon-docs']
}
```

You can configure `react-docgen-typescript`'s `propFilter` directly in `main.js`:

```
module.exports = {
   typescript: {
         reactDocgenTypescriptOptions: {
      propFilter: (prop) => ['label', 'disabled'].includes(prop.name),
    }
};
```

**Comment by EdenTurgeman** [comment]
@shilman I see now!
Looks good!
after adding re-adding `@storybook/addon-docs` to my main.ts I'm getting this error unfortunately
```jsinfo => Loading presets
WARN   Failed to load preset: "@storybook/addon-docs" on level 1
ERR! Error: Cannot find module '@storybook/addon-docs'
ERR! Require stack:
ERR! - /Users/**/**/**/node_modules/@storybook/core/dist/server/presets.js
ERR! - /Users/**/**/**/node_modules/@storybook/core/dist/server/config.js
ERR! - /Users/**/**/**/node_modules/@storybook/core/dist/server/build-static.js
ERR! - /Users/**/**/**/node_modules/@storybook/core/server.js
ERR! - /Users/**/**/**/node_modules/@storybook/react/dist/server/index.js
ERR! - /Users/**/**/**/node_modules/@storybook/react/bin/index.js
ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:690:27)
ERR!     at Module.require (internal/modules/cjs/loader.js:852:19)
ERR!     at require (internal/modules/cjs/helpers.js:74:18)
ERR!     at interopRequireDefault (/Users/**/**/**/node_modules/@storybook/core/dist/server/presets.js:172:16)
ERR!     at loadPreset (/Users/**/**/**/node_modules/@storybook/core/dist/server/presets.js:182:20)
ERR!     at /Users/**/**/**/node_modules/@storybook/core/dist/server/presets.js:244:18
ERR!     at Array.reduce (<anonymous>)
ERR!     at loadPresets (/Users/**/**/**/node_modules/@storybook/core/dist/server/presets.js:243:18)
ERR!     at loadPreset (/Users/**/**/**/node_modules/@storybook/core/dist/server/presets.js:208:18)
ERR!     at /Users/**/**/**/node_modules/@storybook/core/dist/server/presets.js:244:18
ERR!     at Array.reduce (<anonymous>)
ERR!     at loadPresets (/Users/**/**/**/node_modules/@storybook/core/dist/server/presets.js:243:18)
ERR!     at getPresets (/Users/**/**/**/node_modules/@storybook/core/dist/server/presets.js:297:23)
ERR!     at _default (/Users/**/**/**/node_modules/@storybook/core/dist/server/config.js:72:38)
ERR!     at _default (/Users/**/**/**/node_modules/@storybook/core/dist/server/dev-server.js:104:28)
ERR!  Error: Cannot find module '@storybook/addon-docs'
ERR! Require stack:
ERR! - /Users/**/**/**/node_modules/@storybook/core/dist/server/presets.js
ERR! - /Users/**/**/**/node_modules/@storybook/core/dist/server/config.js
ERR! - /Users/**/**/**/node_modules/@storybook/core/dist/server/build-static.js
ERR! - /Users/**/**/**/node_modules/@storybook/core/server.js
ERR! - /Users/**/**/**/node_modules/@storybook/react/dist/server/index.js
ERR! - /Users/**/**/**/node_modules/@storybook/react/bin/index.js
ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:690:27)
ERR!     at Module.require (internal/modules/cjs/loader.js:852:19)
ERR!     at require (internal/modules/cjs/helpers.js:74:18)
ERR!     at interopRequireDefault (/Users/**/**/**/node_modules/@storybook/core/dist/server/presets.js:172:16)
ERR!     at loadPreset (/Users/**/**/**/node_modules/@storybook/core/dist/server/presets.js:182:20)
ERR!     at /Users/**/**/**/node_modules/@storybook/core/dist/server/presets.js:244:18
ERR!     at Array.reduce (<anonymous>)
ERR!     at loadPresets (/Users/**/**/**/node_modules/@storybook/core/dist/server/presets.js:243:18)
ERR!     at loadPreset (/Users/**/**/**/node_modules/@storybook/core/dist/server/presets.js:208:18)
ERR!     at /Users/**/**/**/node_modules/@storybook/core/dist/server/presets.js:244:18
ERR!     at Array.reduce (<anonymous>)
ERR!     at loadPresets (/Users/**/**/**/node_modules/@storybook/core/dist/server/presets.js:243:18)
ERR!     at getPresets (/Users/**/**/**/node_modules/@storybook/core/dist/server/presets.js:297:23)
ERR!     at _default (/Users/**/**/**/node_modules/@storybook/core/dist/server/config.js:72:38)
ERR!     at _default (/Users/**/**/**/node_modules/@storybook/core/dist/server/dev-server.js:104:28) {
ERR!   stack: "Error: Cannot find module '@storybook/addon-docs'\n" +
ERR!     'Require stack:\n' +
ERR!     '- /Users/**/**/**/node_modules/@storybook/core/dist/server/presets.js\n' +
ERR!     '- /Users/**/**/**/node_modules/@storybook/core/dist/server/config.js\n' +
ERR!     '- /Users/**/**/**/node_modules/@storybook/core/dist/server/build-static.js\n' +
ERR!     '- /Users/**/**/**/node_modules/@storybook/core/server.js\n' +
ERR!     '- /Users/**/**/**/node_modules/@storybook/react/dist/server/index.js\n' +
ERR!     '- /Users/**/**/**/node_modules/@storybook/react/bin/index.js\n' +
ERR!     '    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)\n' +
ERR!     '    at Function.Module._load (internal/modules/cjs/loader.js:690:27)\n' +
ERR!     '    at Module.require (internal/modules/cjs/loader.js:852:19)\n' +
ERR!     '    at require (internal/modules/cjs/helpers.js:74:18)\n' +
ERR!     '    at interopRequireDefault (/Users/**/**/**/node_modules/@storybook/core/dist/server/presets.js:172:16)\n' +
ERR!     '    at loadPreset (/Users/**/**/**/node_modules/@storybook/core/dist/server/presets.js:182:20)\n' +
ERR!     '    at /Users/**/**/**/node_modules/@storybook/core/dist/server/presets.js:244:18\n' +
ERR!     '    at Array.reduce (<anonymous>)\n' +
ERR!     '    at loadPresets (/Users/**/**/**/node_modules/@storybook/core/dist/server/presets.js:243:18)\n' +
ERR!     '    at loadPreset (/Users/**/**/**/node_modules/@storybook/core/dist/server/presets.js:208:18)\n' +
ERR!     '    at /Users/**/**/**/node_modules/@storybook/core/dist/server/presets.js:244:18\n' +
ERR!     '    at Array.reduce (<anonymous>)\n' +
ERR!     '    at loadPresets (/Users/**/**/**/node_modules/@storybook/core/dist/server/presets.js:243:18)\n' +
ERR!     '    at getPresets (/Users/**/**/**/node_modules/@storybook/core/dist/server/presets.js:297:23)\n' +
ERR!     '    at _default (/Users/**/**/**/node_modules/@storybook/core/dist/server/config.js:72:38)\n' +
ERR!     '    at _default (/Users/**/**/**/node_modules/@storybook/core/dist/server/dev-server.js:104:28)',
ERR!   code: 'MODULE_NOT_FOUND',

```

**Comment by shilman** [comment]
@EdenTurgeman did you npm install / yarn add it? The setup instructions for sb docs haven’t changed. The major difference Is that now you shouldn’t have to worry about any typescript-related configuration now, and reconfiguring is simpler if needed

**Comment by EdenTurgeman** [comment]
@shilman Actually I did, not a new dep in my repo could it be a problem with yarn?

**Comment by codemaster138** [comment]
@shilman The latest release of `react-docgen-typescript` is having issues (see [styleguidist/react-docgen-typescript#356](https://github.com/styleguidist/react-docgen-typescript/issues/356)), which was causing storybook to crash on startup.

To get around it, I wanted to disable `react-docgen-typescript`. My `.storybook/main.js` looks like this:
```js
module.exports = {
  "stories": [
    "../src/**/*.stories.mdx",
    "../src/**/*.stories.@(js|jsx|ts|tsx)"
  ],
  "addons": [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/preset-create-react-app"
  ],
  typescript: {
    docgen: 'none'
  }
}
```

However, storybook is still loading `react-docgen-typescript`. Am I doing something wrong?

**Comment by codemaster138** [comment]
I was able to temporarily get around the issue by changing the typescript options to the following:

```js
...
  typescript: {
    docgen: 'none',
    reactDocgenTypescriptOptions: {
      include: ['src/**/*.tsx']
    }
  }
...
```

(As described [here](https://github.com/styleguidist/react-docgen-typescript/issues/356#issuecomment-850260404)). However, the `docgen: none` option is still broken.

**Comment by Philzen** [comment]
> However, the docgen: none option is still broken.

That's because the option should be `reactDocgen: false` as per https://storybook.js.org/docs/react/configure/typescript

Found via https://github.com/styleguidist/react-docgen-typescript/issues/356.

Just posting it here in case anyone else comes by wondering about the same as i did.
