### ISSUE TITLE
CLI: check for missing/unneeded deps when initializing SB in a project 

### ISSUE THREAD

**Issue by gaetanmaisse** [storybookjs/storybook#10798]
### Work summary

When using CLI to initialize Storybook in a project some dependencies are added (according to the framework) to have everything working out of the box. For instance, for a CRA project [the following dependencies](https://github.com/storybookjs/storybook/blob/next/lib/cli/src/generators/REACT_SCRIPTS/index.js#L15) are added:
   - @storybook/react
   - @storybook/preset-create-react-app
   - @storybook/addon-actions
   - @storybook/addon-links
   - @storybook/addons

To offer the best UX, make a good impression and so improve Storybook adoption we need to be sure that all added dependencies are necessary and that there is no missing dependency or peer dependency.

This work is part of #10723

### Where to start

🔍 Run E2E tests locally and check all dependency warnings returned by NPM or Yarn.

➕ Add the dependencies that are reported as missing by the package manager OR the origin of this warning and make sure that this is not due to missing or unneeded dependencies in `@storybook` packages.

🗑️ Remove potentially unneeded dependencies and check that everything is still ok (for instance, `@storybook/addons` looks to be a dependency of each addon so no need to add it one more time via the project dependencies)

Note: Yarn 2 can help with that because it is way more strict on missing dependencies than NPM or Yarn 1.

### Acceptance criteria

- [ ] E2E tests are passing
- [ ] Changes are properly reviewed by some of the members mentioned below
- [ ] 🤷 Not sure how we can test that we are only adding needed dependencies

### Who to contact

@gaetanmaisse @ndelangen @tooppaaa @yannbf

**Comment by gaetanmaisse** [comment]
Don't worry @stale we will do it ;)

**Comment by gaetanmaisse** [comment]
I will work on it after https://github.com/storybookjs/storybook/issues/10797

**Comment by shilman** [comment]
Related (but different): https://github.com/storybookjs/storybook/pull/11396

**Comment by yannbf** [comment]
Hey @gaetanmaisse, shall we check about the state of this again, given that quite some things changed and the addons that come via the CLI templates are now a bit different?

**Comment by gaetanmaisse** [comment]
🤔  True! We should take a deep look at all packages' deps and devDeps but it's not directly related to the CLI anynore.
