### ISSUE TITLE
CLI: Improve support of Yarn 2 in E2E tests

### ISSUE THREAD

**Issue by gaetanmaisse** [storybookjs/storybook#10797]
### Work summary

Currently, there is only one E2E test that uses Yarn 2, it's a simple CRA setup: https://github.com/storybookjs/storybook/pull/10702/files#diff-054afb61fcbf5f01b1e17e1341d869e4R147-R154

It would be great if the package manager used when running E2E tests was a CLI param and everything needed to bootstrap and run tests were using NPM or Yarn accordingly to that param.

By doing so:
- We will be able to have all E2E on Npm or Yarn 2 without duplicating the configs
- Increasing the test coverage, we will become way more confidant about Yarn 2 support and non-regression

This work is part of #10723

### Where to start

📚 Surely, read some doc about [Yarn 2](https://yarnpkg.com/).

🏗️ Then try to extract all references to `npx` or `npm install` to functions or class that will hide the specific syntax of each package manager (i.e. use `yarn dlx` for Yarn instead of `npx` etc).

⚔️ Fight with something because it will not be so simple.

🎛️ Update the Yarn 2 E2E tests job in Circle CI config file to run E2E tests with Yarn 2 for as much framework as possible (some are incompatible with Yarn 2 for now).

### Acceptance criteria

- [ ] Current E2E tests are passing
- [ ] New Yarn 2 E2E tests are passing
- [ ] Changes are properly reviewed by some of the members mentioned below

### Who to contact

@gaetanmaisse @ndelangen @tooppaaa @yannbf

**Comment by gaetanmaisse** [comment]
Don't worry @stale we will do it ;)

**Comment by shilman** [comment]
Zoinks!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-rc.16 containing PR #11354 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
