### ISSUE TITLE
CLI: use addon essentials in storybook templates

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#10795]
### Work summary
Make the generated boilerplate from CLI to use [addon-essentials](https://www.npmjs.com/package/@storybook/addon-essentials) and remove the explicit use of `@storybook/addon-actions`, `@storybook/addon-links` and `@storybook/docs` (when applicable) in `main.js` files.

Essentials will be the easiest way to get started with a high-quality Storybook experience. If all the CLI templates use it and all the tests make sure that it works smoothly with all the existing frameworks, it will be a huge win for users and for Storybook maintenance.

This work is part of #10723 and depends on the E2E setup from #10702 

@shilman please chime in about the usage of addons from essentials in the boilerplate! Edit this issue so it's clear for everyone who's reading it.

### Where to start

Check all framework templates under [generators](https://github.com/storybookjs/storybook/tree/next/lib/cli/src/generators) folder and change them accordingly.

### Acceptance criteria

- [x] CLI tests are passing
- [x] E2E tests are passing
- [ ] Usage of the addon is proper, aligned with @shilman 
- [x] Changes are properly reviewed by some of the members mentioned below

### Who to contact

@shilman @yannbf @tooppaaa @ndelangen @gaetanmaisse

**Comment by shilman** [comment]
Gadzooks!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-beta.39 containing PR #11282 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
