### ISSUE TITLE
Props are not resolved as expected in props table with typescript

### ISSUE THREAD

**Issue by kruthivijay31** [storybookjs/storybook#10804]
**Describe the bug**
```js
type TooltipProps = {
   position?: 'left' | 'right' // Not getting resolved instead shows union
}
```
<img width="1013" alt="Screen Shot 2020-05-15 at 4 35 34 PM" src="https://user-images.githubusercontent.com/14045986/82104063-41387280-96ca-11ea-9dd1-7fb3a803886d.png">

**main.js**
```js
const path = require('path')

module.exports = {
  stories: ['../packages/**/*.story.mdx', '../packages/**/*.stories.tsx'],
  addons: [
    {
      name: '@storybook/preset-typescript',
      options: {
        tsLoaderOptions: {
          configFile: path.resolve(__dirname, '../tsconfig.json'),
        },
        transpileManager: true,
      },
    },
    {
      name: '@paypalcorp/storybook-preset',
      options: {
        parser: 'typescript'
      },
    },
    '@storybook/addon-viewport/register'
  ],
  webpackFinal: async config => {
    config.module.rules.push({
      test: /\.less$/,
      use: [
        'style-loader',
        'css-loader',
        {
          loader: 'less-loader', // compiles Less to CSS
          options: {
            paths: [path.resolve(__dirname, '../node_modules')],
          },
        },
      ],
    })
    config.resolve.extensions.push('.ts', '.tsx')
    return config
  },
}
```

**Expected behavior**
position -> 'left' | 'right'
Similar to the image in this docs https://github.com/storybookjs/storybook/blob/next/addons/docs/react/README.md

TIA for helping me to figure this out!!

**Comment by shilman** [comment]
closing as dupe to #10311

**Comment by kruthivijay31** [comment]
@shilman i am using 5.3 storybook and config is based on the doc https://storybook.js.org/docs/configurations/typescript-config/. 
```
If you are not using CRA or have other requirements, then the next best option is @storybook/preset-typescript, which configures ts-loader under the hood.
```
Dupe mentioned is for 6.0. Please let me know what am i missing. I see in this example the values are resolved as expected https://github.com/storybookjs/storybook/blob/next/addons/docs/react/README.md

**Comment by shilman** [comment]
The behavior you’re seeing is a function of the CRA preset, not of SB 5.x vs 6.0

**Comment by kruthivijay31** [comment]
Thanks @shilman! I am not using CRA

**Comment by shilman** [comment]
Are you suing a custom babel or webpack config?

**Comment by kruthivijay31** [comment]
I am using webpack config with `@storybook/preset-typescript`. Details are added in the description.
