### ISSUE TITLE
Toolbars Addon bugs

### ISSUE THREAD

**Issue by lifeiscontent** [storybookjs/storybook#10800]
**Describe the bug**

Docs says to use `options` when the code is using `items` for the dropdown items.

`defaultValue` does not work currently.

**Comment by lifeiscontent** [comment]
CC: @shilman

**Comment by shilman** [comment]
@lifeiscontent NPM documentation is out of date because the package is released on the `next` tag. `defaultValue`  issue dupe to #10239 and fixed in next release
