### ISSUE TITLE
Storybook Breaks Chrome Inspect Elements

### ISSUE THREAD

**Issue by machineghost** [storybookjs/storybook#10809]
**Describe the bug**
I use storybook to render a component.  I inspect an element in the component rendered by storybook (using the Chrome dev tools). Chrome shows me the CSS for ... some other element (I see no styles defined except for inherited body styles).

It does not show the CSS for the element I inspected.

**To Reproduce**
See above.  My component is extremely simple; the only thing of interest about it is that it uses styled components.

**Expected behavior**
I should see the element's styles.

**System:**
Environment Info:

  System:
    OS: Linux 4.15 Linux Mint 18.2 (Sonya)
    CPU: (8) x64 Intel(R) Core(TM) i7-4810MQ CPU @ 2.80GHz
  Binaries:
    Node: 11.15.0 - /usr/bin/node
    npm: 6.7.0 - /usr/bin/npm
  Browsers:
    Chrome: 81.0.4044.129
    Firefox: 75.0
  npmPackages:
    @storybook/addon-actions: ^5.3.18 => 5.3.18 
    @storybook/addon-links: ^5.3.18 => 5.3.18 
    @storybook/addons: ^5.3.18 => 5.3.18 
    @storybook/preset-create-react-app: ^2.1.2 => 2.1.2 
    @storybook/react: ^5.3.18 => 5.3.18 

**Additional context**
This appears very similar to https://github.com/storybookjs/storybook/issues/4769, and seems to be somehow related to Storybook's use of iframes.  Quite frankly I've never in my life seen a library "break the dev tools" in this way.

**Comment by shilman** [comment]
<img width="152" alt="Addons___A11y___BaseButton_-_Default_⋅_Storybook" src="https://user-images.githubusercontent.com/488689/82133592-9d150f80-9820-11ea-946b-3b0977249d1d.png">

Does hitting the "eject" button in the upper right hand corner and inspecting in the ejected iframe help at all?

Do you have a public repro?

**Comment by machineghost** [comment]
Yes, it does fix it (although obviously that's not a very viable workaround).

And no unfortunately I don't.
