### ISSUE TITLE
Vue components can't access to $refs

### ISSUE THREAD

**Issue by skill83** [storybookjs/storybook#10806]
**Describe the bug**
In the mount callback of a component if you try to get a ref it's undefined

**To Reproduce**
1. In the template of a component add a ref
```
<template>
  <button ref="btn" class="button-styles" @click="onClick">
    <slot></slot>
  </button>
</template>
```
2. In the mounted cb add a console.log of the ref
```
mounted() {
  console.log(this.$refs.btn)
}
```
3. You will get undefined in tthe console

**Expected behavior**
Find in the console the node logged

**System:**
Environment Info:

  System:
    OS: macOS 10.15.4
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
  Binaries:
    Node: 10.19.0 - ~/.nvm/versions/node/v10.19.0/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v10.19.0/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v10.19.0/bin/npm
  Browsers:
    Chrome: 81.0.4044.138
    Edge: 81.0.416.72
    Firefox: 76.0.1
    Safari: 13.1
  npmPackages:
    @storybook/addon-actions: ^5.3.18 => 5.3.18
    @storybook/addon-links: ^5.3.18 => 5.3.18
    @storybook/addons: ^5.3.18 => 5.3.18
    @storybook/vue: ^5.3.18 => 5.3.18

**Comment by shilman** [comment]
have you looked at #6288

**Comment by skill83** [comment]
Hi @shilman  yes, i looked at it.
It seems it broke up with some updates of storybook.
If i try `learnstorybook-code`, that use an older version of storybook i do not get the issue.
I tried both with the vue cli and without, and with the last version of sb there's no way to get the refs working.

Thanks

**Comment by skill83** [comment]
Hi @shilman i started everything again.
With the cli and the plugin it's working.
Now i'm trying to integrate storybook in a project that do not use the cli.
I made `npx -p @storybook/cli sb init --type vue` but i have the issue of the refs.
What exactly the cli plugin does? what should i look for to change in my custom configuration?
A hint could be enough.

Thanks

**Comment by shilman** [comment]
cc @pksunkara @graup @Aaron-Pool

**Comment by Aaron-Pool** [comment]
@skill83 if I'm remembering correctly, I didn't think child refs were guaranteed to exist until the `$nextTick` _after_ the `mounted` lifecycle had been called. Have you tested this?

```js
mounted() {
  this.$nextTick(() => console.log(this.$refs.btn));
}
```

**Comment by Aaron-Pool** [comment]
Further reading here: https://vuejs.org/v2/api/#mounted

Relevant text:
> Note that mounted does not guarantee that all child components have also been mounted. If you want to wait until the entire view has been rendered, you can use vm.$nextTick inside of mounted

**Comment by skill83** [comment]
Hi @Aaron-Pool ,
I know about $nextTick, it wasn't related to it the issue, anyway thanks a lot for trying to help me.
Now i was able to make all the enviroment work.
What i found a bit boring is to inject in each component the store.
I try to explain.

In my case i have already a huge project with hundred of components in a SPA.
All the component are under the same vue instance and use the same store, and also there can be  plugins that share it.

1) So what i have done is create the store outside 

store/index.js
```
/* Import dependencies */
import Vue from 'vue';
import Vuex from 'vuex';

Vue.use(Vuex);

/* Mutations, actions and getters */
import mutations from './mutations';
import actions from './actions';
import getters from './getters';

/* Modules */
// Import modules here

export default new Vuex.Store({
  state: {
    appReady: false,
    loading: true,
    unlockedView: null
  },
  actions,
  mutations,
  getters,
  modules: {
    // Register modules here
  }
});
```
2) import in preview.js with all the plugins

preview.js

```
import { configure } from '@storybook/vue';

import Vue from 'vue';

// Import Vue plugins
import VueBootstrapper from 'vue-bootstrapper';
import VueViewportManager from 'vue-viewport-manager';
import VueScrollTo from 'vue-scrollto';
import VueDjangoGettext from '@plugins/vue_django_gettext';
import fxDirective from '@directives/fx-directive';

/* Store */
import store from '@store';

/* FontAwesome */
import { library } from '@fortawesome/fontawesome-svg-core';

/* Common styles */
import '$scss/common.scss'

/* Global components */
import Im0IconList from '@components/im0-icon-list';
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';

Vue.component('font-awesome-icon', FontAwesomeIcon);
Vue.component('im0-icon-list', Im0IconList);

Vue.use(VueBootstrapper, {store});
Vue.use(VueViewportManager, {store});
Vue.use(VueScrollTo);
Vue.use(VueDjangoGettext, {store});

configure(require.context('../fe-src/src/', true, /\.stories\.js$/), module);
```

3) Create a wrapper for all the components to inject a common store, and for future im provements 

base.js

```
import store from '@store';
import router from '@views/home/router';


export default (wrapped,components) => {
  return {
    components,
    router,
    store,
    template: `<div>${wrapped}<im0-icon-list /></div>`
  }
}
```

4) In my stories use the wrapper

im3-header.stories.js

```
import Im3Header from '@components/im3-header';
import Base from './base.js';

export default {
  component: Im3Header,
  title: 'Header',
};

export const defaultStyle = () => (Base(
  '<im3-header />',
  { Im3Header }
))
```

Of course this can be improved a lot.
From the docs i didn't understand that for each story is mounted an instance of vue, so it was a bit hard to make everything working. 
Probably it was because i didn't understand the whole enviroment correctly.
In my opinion the idea to share a common base initialize for all the vue instances, should be evaluated, and expected in preview.js.

Thanks for your time, and support

Regards
