### ISSUE TITLE
Importing tsx addons inside manager.js

### ISSUE THREAD

**Issue by matheo** [storybookjs/storybook#10811]
**Is your feature request related to a problem? Please describe.**

Is it possible to include addons with custom tsx components inside the `manager.js`?
or do I need to compile the addons to es2015 to be properly imported?

It would be nice if there's some workaround to be able to support some custom paths to `register.tsx` in the addons list tho. I'm no expert about webpack so I have no idea about the possibilities nor the internals :(

Thanks in advance!

**Comment by shilman** [comment]
Shiver me timbers!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-beta.13 containing PR #10886 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
