### ISSUE TITLE
Storybook 6.0 iframe.html preview is broken on first render

### ISSUE THREAD

**Issue by lifeiscontent** [storybookjs/storybook#10815]
**Describe the bug**
I am using storybook and cypress together to test the behavior of my UI components.

on Storybook v5 I was always able to get this to work, so I'm assuming this might have something to do with the refactor @tmeasday worked on.

**To Reproduce**

in the reproduction, you'll need to boot storybook using `yarn storybook` and then in another terminal run `yarn test:cypress:ci` you'll see it fail.

**Expected behavior**
having consistent rendering behavior if you run `yarn test:cypress` and refresh the browser a few times you'll see the tests always pass.

**Screenshots**

**Code snippets**
https://github.com/lifeiscontent/sb-tech-talk

**System:**
Please paste the results of `npx -p @storybook/cli@next sb info` here.

**Additional context**

**Comment by tmeasday** [comment]
In what way is it broken @lifeiscontent?

**Comment by lifeiscontent** [comment]
@tmeasday it looks like the state doesn't get bootstrapped.

**Comment by lifeiscontent** [comment]
@tmeasday my repo was invalid, my bad!
