### ISSUE TITLE
@storybook/addon-docs: Broken source code with shorthand parameters

### ISSUE THREAD

**Issue by yarastqt** [storybookjs/storybook#10827]
**Describe the bug**
I'm use shorthand syntax for parameters and all my stories don't have source code.

**To Reproduce**

1. Define `parameters` in other place, and use shorthand syntax for export default.
2. Run storybook.
3. See `No code available` for all stories.

**Expected behavior**

Property `parameters` should be extended, for example:

```js
export default {
  title: 'Controls/Button',
  parameters: Object.assig(parameters, {"storySource":{"source":"...","locationsMap":{}}),
}
```

**Code snippets**

Minimal code for reproduce:

```js
import React from 'react'

const parameters = {}

export default {
  title: 'Controls/Button',
  parameters,
}

export const Plain = () => (
  <div style={{ height: 60 }}>
    <button>Hello Button</button>
  </div>
)
```

Code after processing:

```js
export default {parameters: {"storySource":{"source":"...","locationsMap":{}},},
    title: 'Controls/Button',
    parameters,
}
```

**System:**

Dependencies:

```
"@storybook/addon-docs": "5.3.18",
```

**Comment by yarastqt** [comment]
Also if define `title` too in  other place, then `locationsMap` will be empty and source code will not available too.

**Comment by shilman** [comment]
That's not currently supported. For now you should declare stuff statically as a workaround.
