### ISSUE TITLE
Is it possible to add extra info for a specific story

### ISSUE THREAD

**Issue by danielo515** [storybookjs/storybook#10823]
I was guessing if it is possible to add certain extra documentation to one story. I'm not talking about using mdx, but adding some "notes" to one particular story and let them show up on the generated documentation.

**Comment by shilman** [comment]
https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/recipes.md#migrating-from-notesinfo-addons

We'll be supporting this more natively in a future release

**Comment by danielo515** [comment]
Thanks for the answer
so the way to go for now, if I understood correctly is:

- Write that decorator and add it to preview.js
- use the same decoration as if you are using the notes addon but the notes addon is not required

Am I correct? Is it possible to directly add the docs -> extraComponentDescription into the component itself rather than using this decorator?

Thanks and regards.

**Comment by shilman** [comment]
@danielo515 yes you can add override `extractComponentDescription`. Also, depending on which framework you're using, you can also add docgen comments above your component definition, e.g. React:

```jsx
import React from 'react';

/**
 * Some button description
 */
export const Button = () => <button>hi</button>
```

**Comment by danielo515** [comment]
@shilman I tested the proposed solution and the comments are added to the top of the documentation page, not to the specific story where I defined the parameter. Is that the expected behaviour or I did something wrong?

**Comment by danielo515** [comment]
My request is exactly the same as https://github.com/storybookjs/storybook/issues/8527
And I can workaround it with: `parameters.docs.storyDescription`

**Comment by shilman** [comment]
Aha there’s also a community provided webpack plugin to do it at the story level
