### ISSUE TITLE
Can't use components using npm classNames function

### ISSUE THREAD

**Issue by ktw-studio** [storybookjs/storybook#10829]
Hi,

I hope you're doing well during this pandemic thing. I'd like to know if the issue I am facing has any solution. In my components I am using this little package:
https://www.npmjs.com/package/classnames

Once I load components into the StoryBook classes generated by classNames functions returns "undefined". Is there any additional config I need to do in order to make it work? Or is it just a bug that needs to be resolved?

Kind regards,
Martin

**Comment by igor-dv** [comment]
`classnames` package is only joining strings in a smart way. I assume you are using some css framework or css-in-js framework that might not be configured well.
