### ISSUE TITLE
Acorn doesn't install with `--production` flag on npm install (storybook/react)

### ISSUE THREAD

**Issue by Smolations** [storybookjs/storybook#10828]
**Describe the bug**
I have been working with storybook only in a dev environment, but now my team has a need to deploy storybook to test/staging instances, so I've been working on building the static app. It was working fine locally, but I think it was a false positive as I don't include the `--production` flag locally and my node modules were sitting around. However, when building the docker image in CI, running `npm install --production` (because we use prod builds in these environments) results in the missing `acorn` folder in node modules. Part of my change was to move all the storybook stuff out of `devDependencies` and into `dependencies` in my project's `package.json`.

**To Reproduce**
1. Locally, for a react storybook project, delete the `node_modules` folder. 
2. Ensure storybook deps are all `dependencies` in the project's `package.json`
3. Run `npm install --production`
4. Observe that `node_modules/acorn` does not exist (even though listed as a dependency for storybook addon-docs)
5. Run storybook build command for static site generation 

**Expected behavior**
The build should complete with all expected artifacts in output directory.

**Code snippets**
Relevant part of `package.json`:
```json
  "dependencies": {
    "@babel/core": "7.3.4",
    "@babel/plugin-proposal-class-properties": "7.3.4",
    "@babel/plugin-proposal-optional-chaining": "7.7.5",
    "@babel/plugin-transform-modules-commonjs": "7.2.0",
    "@babel/plugin-transform-object-assign": "7.2.0",
    "@babel/plugin-transform-runtime": "7.6.2",
    "@babel/polyfill": "7.2.5",
    "@babel/preset-env": "7.3.4",
    "@babel/preset-react": "7.0.0",
    "@storybook/addon-a11y": "5.3.18",
    "@storybook/addon-actions": "5.3.18",
    "@storybook/addon-docs": "5.3.18",
    "@storybook/addon-knobs": "5.3.18",
    "@storybook/addon-links": "5.3.18",
    "@storybook/addons": "5.3.18",
    "@storybook/react": "5.3.18",
    "@storybook/source-loader": "5.3.18",
```

Terminal output (note that some output is a result of custom logging for custom webpack config):
```
info @storybook/react v5.3.18
info 
info clean outputDir..
info => Copying prebuild dll's..
info => Building manager..
info => Loading manager config..
info => Loading presets
info => Loading custom manager config.
info => Compiling manager..
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
info => manager built (57 s)
info => Building preview..
info => Loading preview config..
info => Loading presets
info => Loading config/preview file in "./.storybook".
info => Loading custom Webpack config (full-control mode).
info => Using custom postcss.config.js
info => Using base config because react-scripts is not installed.
Ensuring tmp directory exists: /Volumes/projects/recurly-app/snappy/tmp
Removing ProgressPlugin...
Adding to config.resolve.modules...
Adding to config.plugins...
Replacing rule matching test: woff
Adding to config.module.rules...
info => Compiling preview..
Original webpack config found in snappy/tmp/storybook-webpack.original.config.json
Modified webpack config found in snappy/tmp/storybook-webpack.modified.config.json
ERR! => Failed to build the preview
ERR! Module not found: Error: Can't resolve 'acorn' in '/Volumes/projects/recurly-app/snappy/node_modules/acorn-jsx'
(node:72305) UnhandledPromiseRejectionWarning: ModuleNotFoundError: Module not found: Error: Can't resolve 'acorn' in '/Volumes/projects/recurly-app/snappy/node_modules/acorn-jsx'
    at factory.create (/Volumes/projects/recurly-app/snappy/node_modules/webpack/lib/Compilation.js:925:10)
```

**System:**
```
Environment Info:

  System:
    OS: macOS 10.15.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 10.18.0 - ~/.nvm/versions/node/v10.18.0/bin/node
    Yarn: 1.22.0 - ~/.yarn/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v10.18.0/bin/npm
  Browsers:
    Chrome: 81.0.4044.138
    Firefox: 74.0
    Safari: 13.1
  npmPackages:
    @storybook/addon-a11y: 5.3.18 => 5.3.18 
    @storybook/addon-actions: 5.3.18 => 5.3.18 
    @storybook/addon-docs: 5.3.18 => 5.3.18 
    @storybook/addon-knobs: 5.3.18 => 5.3.18 
    @storybook/addon-links: 5.3.18 => 5.3.18 
    @storybook/addons: 5.3.18 => 5.3.18 
    @storybook/react: 5.3.18 => 5.3.18 
    @storybook/source-loader: 5.3.18 => 5.3.18
```

**Additional context**
Not sure if this is an issue with storybook or `acorn-jsx` which seems to need `acorn`, but I reproduced the issue locally so I know it's not anything to do with CI or its environment.

**Comment by Smolations** [comment]
Not inactive, just waaaiiittiiiinnnngggg! 😋

**Comment by juliopiubello** [comment]
How painful it is to manage storybook dependencies. Every time it is a different issue

After an update to package-lock.json this issue started to pop up

**Comment by TimLanzi** [comment]
Also experiencing this

**Comment by fozziethebeat** [comment]
I just encountered this.  I fixed it by installing acorn manually:

```
npm install acorn
```

This problem only occurred when I ran `npx sb init` and `npm run storybook` So I'm guessing this is a problem with Storybook dependencies.
