### ISSUE TITLE
Always go to "Canvas" when new story is opened.

### ISSUE THREAD

**Issue by nanandn** [storybookjs/storybook#10826]
Hi,

Is there a way to reset to the "Canvas" tab when a different story is selected? I am using addon-docs, so there are two tabs "Canvas" and "Docs". If I go to the Docs tab and then go to a different story, I want to reset back to the "Canvas" tab for the selected story.

**Comment by shilman** [comment]
in 6.0:

```js
addParameters({
  viewMode: 'canvas',
});
```
