### ISSUE TITLE
Addon-docs: Extract ArgType parameters by component

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#10844]
#10373 intended to reduce the data sent over the channel on app startup by "normalizing" story parameters (e.g. sending component-level parameters once per component rather than once per story).

It appears that component ArgTypes are being sent per-story rather than per-component, thus losing out on a performance opportunity. Need to fix the `argTypes` extractor to do the right thing.

**Comment by shilman** [comment]
@tmeasday this requires:
- [ ] a protocol for enhancers to know whether they are being called on component/kind parameters or story parameters
- [ ] enhancers to be updated to support this protocol
- [ ] story store to be updated to support the protocol and to call the enhancers on kind parameters

Pretty sure I'd come up when we did the normalization work, but none of that is implemented AFAICT and it seems like a bigger task than I'd thought. WDYT?

**Comment by tmeasday** [comment]
Sounds about right! I'm not sure how hard it is to update the individual enhancers @shilman but if we decide on the API the store part will be quick I think.

**Comment by matheo** [comment]
@tmeasday I've highlighted all the extractors in this PR: https://github.com/storybookjs/storybook/pull/11068/files

In the code, I only see one `enhanceArgTypes` in `docs/frameworks/common`
and I'm assuming that's the one to be called once by component @shilman?

**Comment by shilman** [comment]
Won't fix. On-demand architecture fixes plus we're moving to annotations server in the future.
