### ISSUE TITLE
Storybook Build has different/incorrect image url for css background image

### ISSUE THREAD

**Issue by seanbrightly** [storybookjs/storybook#10849]
**Describe the bug**

Storybook build has incorrect image urls for css background images.

Storybook build: file:///Users/sean/Projects/culch/storybook-static/static/css/static/media/drag.1860693f.svg

Storybook: http://localhost:9009/static/media/drag.1860693f.svg

When adding a background image in SCSS the asset is loaded correctly when running `yarn storybook`. However, after running `yarn build-storybook` the image is not loaded and the path is incorrect.

**To Reproduce**
1. Working with a create-react-app default webpack setup
2. Add a background image in an scss file
3. Run `yarn storybook`
4. Run a storybook build: `yarn build-storybook -s public`
5. Observe the urls for the image in both

**Expected behavior**
Expected the image to load the same in both storybook and storybook-build

**Code snippets**
background: url('~assets/svg/drag.svg') no-repeat center;

**System:**

Environment Info:

  System:
    OS: macOS 10.15.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 10.19.0 - ~/.nvm/versions/node/v10.19.0/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v10.19.0/bin/npm
  Browsers:
    Chrome: 81.0.4044.138
    Firefox: 76.0.1
    Safari: 13.1
  npmPackages:
    @storybook/addon-a11y: ^5.3.9 => 5.3.9 
    @storybook/addon-actions: ^5.3.7 => 5.3.7 
    @storybook/addon-docs: ^5.3.9 => 5.3.9 
    @storybook/addon-knobs: ^5.3.9 => 5.3.9 
    @storybook/addon-links: ^5.3.7 => 5.3.7 
    @storybook/addon-storysource: ^5.3.9 => 5.3.9 
    @storybook/addon-viewport: ^5.3.9 => 5.3.9 
    @storybook/addons: ^5.3.7 => 5.3.7 
    @storybook/preset-create-react-app: ^1.5.2 => 1.5.2 
    @storybook/react: ^5.3.7 => 5.3.7

**Comment by mateusgf** [comment]
Was this issue resolved?
I'm having the same error...
