### ISSUE TITLE
[React] Storybook Imports not recognized when importing from src typescript class

### ISSUE THREAD

**Issue by rprasad25** [storybookjs/storybook#10841]
**Describe the bug**
I'm trying to import components stored in a typescript class into a story javascript class. When trying to import an alias or an absolute path I get a "Module not found" error:

**To Reproduce**
1. Attempt importing an item from a different directory as storybook
1. Run npm run storybook and receive an error.

**Expected behavior**
I'd expect the import to not throw an error
**Screenshots**
Story Class (Button Story):
![image](https://user-images.githubusercontent.com/65511478/82353541-98418e80-99cd-11ea-9da4-41edda24f327.png)
Webpack Config with aliases:
![image](https://user-images.githubusercontent.com/65511478/82353485-85c75500-99cd-11ea-8a04-83cab2452714.png)
Error message: 
![image](https://user-images.githubusercontent.com/65511478/82353628-b4453000-99cd-11ea-8aec-5d70f9fcef34.png)

**Code snippets**
Above

**System:**
This threw an error, but I'm not sure how relevant it was

**Additional context**
My Project Structure is
src->components->dependency (typings)
stories->buttonstories

**Comment by shilman** [comment]
We've just released zero-config typescript support in 6.0-beta. Please upgrade and test it!

- [Release 6.0.0-beta.12+](https://github.com/storybookjs/storybook/releases/tag/v6.0.0-beta.12)
- [Migration instructions](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#zero-config-typescript)
- [Updated docs](https://github.com/storybookjs/storybook/blob/next/docs/src/pages/configurations/typescript-config/index.md)

Thanks for your help and support getting this stable for release!
