### ISSUE TITLE
Typo in root path detection.

### ISSUE THREAD

**Issue by christianwiedemann** [storybookjs/storybook#10847]
**Describe the bug**
There is a typo 'node-modules' instead of node_modules in root detection in lib/core/src/server/config/utils.js in storybook 6.x

**To Reproduce**
1. Start storybook without .git or .svn folder in root. You got an "Module parse failed: Unexpected token (9:31)" because the babel loader did not include the right root.

**Expected behavior**
Start and compile js and jsx files correctly.

**Code snippets**
`result = result || __dirname.split('node-modules')[0];` should be result = result || __dirname.split('node_modules')[0];

A PR will follow.

**Comment by shilman** [comment]
Yo-ho-ho!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-beta.13 containing PR #10848 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
