### ISSUE TITLE
Storybook 6.0 defaultValue for args doesn't show up

### ISSUE THREAD

**Issue by lifeiscontent** [storybookjs/storybook#10855]
**Describe the bug**
When specifying a defaultValue for an arg, it doesn't automatically get populated

<img width="820" alt="Screen Shot 2020-05-20 at 11 33 03 PM" src="https://user-images.githubusercontent.com/180963/82530489-42b2d200-9af2-11ea-92c7-f65be4ca1498.png">

**Comment by shilman** [comment]
Hurrah!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-beta.21 containing PR #11024 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
