### ISSUE TITLE
Ability to import .md into a story and hide the cavas toolbar

### ISSUE THREAD

**Issue by chrisj-skinner** [storybookjs/storybook#10854]
**Describe the bug**
Firstly I need to mention that I have seen what I'm trying to do at: https://bolt.argos.co.uk/?path=/story/1-intro-introduction--get-started

The toolbar is hidden, still present in the markup (view the source)
Also it looks like (from the class name that contains the story / markup) that markdown has been imported to populate this page. 

I don't believe this is the NOTES add-on as I cannot find the `addon-notes-container` class on any containing element.
Nor do I think it is a DOCS page, again due to class names.

It would be great to be able to import md files in as introduction templates with no toolbar etc as shown in the link. However I can't find this anywhere in the docs.

**Screenshots**
<img width="1131" alt="Screen" src="https://user-images.githubusercontent.com/5794048/82518823-720b1400-9add-11ea-836b-7970230d8739.png">

**System Info**
Environment Info:

  System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
  Binaries:
    Node: 10.15.1 - /usr/local/bin/node
    npm: 6.14.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 81.0.4044.138
    Firefox: 76.0.1
    Safari: 13.0.4
  npmPackages:
    @storybook/addon-actions: ^5.3.18 => 5.3.18 
    @storybook/addon-docs: ^5.3.18 => 5.3.18 
    @storybook/addon-links: ^5.3.18 => 5.3.18 
    @storybook/addon-notes: ^5.3.18 => 5.3.18 
    @storybook/addon-viewport: ^5.3.18 => 5.3.18 
    @storybook/addons: ^5.3.18 => 5.3.18 
    @storybook/angular: ^5.3.18 => 5.3.18 

**Additional context**
I'm wondering how this is possible to import markdown into a story.
I have tried using:
```
import * as markdown from "./readme.md";

export const Intro = () => ({
  component: markdown,
  ...
```
But with no luck.

I was wondering if this was an addon I have missed.

On the note of hiding the toolbar (canvas etc)
Since the class I want to hide is `css-lhyj5z`, I know that there is a styles array that can be added to the story. For example:
```
styles: [
    `
      .css-lhyj5z {
        display: none!important;
      }
    `
  ]
```
However this only scopes the above class to the story so doesn't change the global class.

**NOTE:** I want to also add at this stage that I only want to hide the toolbar and display markdown on this story. NOT across any other story so declaring my styles and importing it into `main.js` is not an option.

Typings: 
I have the following in my typings.d.ts
```
declare module '*.md' {
  const content: string;
  export default content;
}
```

**Comment by shilman** [comment]
Possible dupe: https://github.com/storybookjs/storybook/issues/7644

**Comment by chrisj-skinner** [comment]
@shilman  Thanks for the reference but unfortunately none of those solutions worked for me.
