### ISSUE TITLE
Storybook 6.0 on* args don't show up in docs

### ISSUE THREAD

**Issue by lifeiscontent** [storybookjs/storybook#10857]
**Describe the bug**
if I specify an action arg like `onClick` it doesn't show up in the addon-docs view, how can I interact with it?

<img width="1170" alt="Screen Shot 2020-05-20 at 11 35 15 PM" src="https://user-images.githubusercontent.com/180963/82530687-bb199300-9af2-11ea-9ace-82dddfb352bc.png">

**Comment by lifeiscontent** [comment]
CC @shilman

**Comment by shilman** [comment]
What does it mean to interact with `onX` events? If you click the button it should log the event to the actions panel. It could also do something cute like flash-highlight the row of the prop table. What do you have in mind?

**Comment by lifeiscontent** [comment]
@shilman would it be possible to get the addon-actions to show up in docs? Or is that going against the idea?

**Comment by shilman** [comment]
@lifeiscontent meaning show the addons panel? i think that's an instance of https://github.com/storybookjs/storybook/issues/6700

**Comment by lifeiscontent** [comment]
@shilman yep, closing in favor of #6700
