### ISSUE TITLE
Storybook 6.0 children args defaultValue quirk

### ISSUE THREAD

**Issue by lifeiscontent** [storybookjs/storybook#10858]
**Describe the bug**

if I have a `children` arg and the default value is "Button" and I type "Buttonnn" and then "Butto" and try to go back to "Button" it will never go back unless I hard refresh the story.

<img width="810" alt="Screen Shot 2020-05-20 at 11 38 36 PM" src="https://user-images.githubusercontent.com/180963/82530842-0a5fc380-9af3-11ea-8017-95cc6e1d9f72.png">

**Comment by lifeiscontent** [comment]
CC: @shilman

**Comment by shilman** [comment]
@lifeiscontent is this still an issue in the latest beta? i couldn't repro

**Comment by lifeiscontent** [comment]
@shilman I'll take a look this weekend.
