### ISSUE TITLE
Less CSS rules missing from production build, but visible in dev build

### ISSUE THREAD

**Issue by phoenixeliot** [storybookjs/storybook#10865]
### Bug or support request summary

CSS rules from Less files imported by my components are missing entirely from just the production build (`build-storybook`).

The local dev build works fine, and imports and applies all the Less rules correctly there. But the rules are missing entirely from the production build output, even if I search the entire file/folder contents for classnames that should be there.

The setup I have is, I admit, a bit complicated and perhaps outdated — I did not do the initial storybook setup for this project, so I don't know how much of the configuration of storybook is incorrect here. We're using storybook 5.2; I haven't updated yet because the API/configuration seems to be different in newer versions.

Is there something missing from the webpack configuration that would cause the production build to omit the compiled Less contents? Or is there something else misconfigured in our storybook setup that would cause this?

Here is the current state of our repo, that can be downloaded and tested: https://github.com/phoenixeliot/design-system/tree/5a2df479aa2984dda23d86a3621d2034e52dea42
Look at the .storybook folder and its webpack config, in particular; but, there may be issues elsewhere in the storybook config.

### Steps to reproduce

- Download the above repo at that commit
- Run `yarn install`
- Run `yarn run build-storybook`
- Host the contents with `npx http-server storybook-dist`
- View http://127.0.0.1:8080/?path=/story/mlbutton--multiple 

Result: The "highlight" button should be a different color than the "primary" button, but instead is the same color. The highlight button's style is determined by this file: https://github.com/phoenixeliot/design-system/blob/7547a8e8deacca866dfccf251503b56fd1f71f87/src/MLButton/style/index.less#L3-L6

Some extra complications/notes:
- This is a component library wrapping Ant Design, so it uses babel-plugin-import in the webpack config for both Ant _and_ itself. However, I've found that even if I explicitly import the less files inside my components, or inside the stories, they still are not included in the bundle. So I don't think it is a problem with babel-plugin-imports
- Somehow, Ant's styles _are_ being included, but I'm not clear why.
- I have tried adding `sideEffects: true` to the Less rule, to no effect.
- I tried adding `config.resolve.extensions.push('.less')`, to no effect.
- Imported _css_ files seem to work just fine.
- Based on my very confusing experience so far, I think there might even be nondeterministic stuff happening — I will sometimes get builds that are missing Ant's styles, or are including Story styles, but are incompletely working, and don't work on the next build without any changes made. This may be getting complicated by browser caching, but I'm trying to clear that every time.

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react 5.2.8

### Affected platforms 

I don't believe this should be affected by platform, but I am building it on MacOS 10.14.6.
All our dependencies are listed here: https://github.com/phoenixeliot/design-system/blob/c67471982129f673ad57bc8400a6039fb3956fb4/package.json

**Comment by jacksonofalltrades** [comment]
@shilman I was wondering if you had an ETA on when someone might be able to take a look into this? We're trying to provide custom CSS for a client project that ends very soon. Thank you.

**Comment by phoenixeliot** [comment]
In the end how I fixed this was to use a separate Gulp script to compile Ant's combined less file and all of our less files into one combined CSS file, and then have preview.js import that CSS file.

**Comment by shilman** [comment]
@jacksonofalltrades I don't really have an ETA. we generally prioritize things related to areas we're actively working on (e.g. 6.0 maintenance/features) or things that get a [high number of upvotes](https://github.com/storybookjs/storybook/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc) (this issue currently has zero upvotes). otherwise it's pretty much random according to the whims of the community.
