### ISSUE TITLE
Addon Docs: iframe size isn't 100% width

### ISSUE THREAD

**Issue by jonhuteau** [storybookjs/storybook#10860]
**Describe the bug**

When you navigate to `Docs` tab, all stories are shown in an iframe with ~320px large instead of 100% width

**To Reproduce**

https://next--storybookjs.netlify.app/vue-kitchen-sink/?path=/docs/app--app

**Expected behavior**

iframe should use all available space

**Screenshots**

![image](https://user-images.githubusercontent.com/58468627/82561130-1db27380-9b73-11ea-997f-885d22cf43c7.png)

**System:**

```
Environment Info:

  System:
    OS: Linux 4.15 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
  Binaries:
    Node: 12.16.3 - /usr/bin/node
    npm: 6.14.5 - /usr/bin/npm
  Browsers:
    Chrome: 83.0.4103.61
    Firefox: 76.0.1
  npmPackages:
    @storybook/addon-a11y: ^6.0.0-beta.12 => 6.0.0-beta.12 
    @storybook/addon-docs: ^6.0.0-beta.12 => 6.0.0-beta.12 
    @storybook/addon-jest: ^6.0.0-beta.12 => 6.0.0-beta.12 
    @storybook/addon-knobs: ^6.0.0-beta.12 => 6.0.0-beta.12 
    @storybook/addon-viewport: ^6.0.0-beta.12 => 6.0.0-beta.12 
    @storybook/addons: ^6.0.0-beta.12 => 6.0.0-beta.12 
    @storybook/vue: ^6.0.0-beta.12 => 6.0.0-beta.12 
```

**Additional context**

Upgraded from `6.0.0-beta.6` to `6.0.0-beta.12`, don't know which release might be in cause

**Comment by shilman** [comment]
@ndelangen seems related to https://github.com/storybookjs/storybook/pull/10801, can you take a look?

**Comment by ndelangen** [comment]
https://github.com/storybookjs/storybook/pull/10877

**Comment by shilman** [comment]
¡Ay Caramba!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-beta.14 containing PR #10877 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
