### ISSUE TITLE
Cannot find module '@storybook/angular/demo'.

### ISSUE THREAD

**Issue by wcorderolara** [storybookjs/storybook#10869]
**Describe the bug**
I'm following the tutorioal that I've founded on [https://storybook.js.org/docs/guides/guide-angular/ ](https://storybook.js.org/docs/guides/guide-angular/ ) and implementing this example [https://medium.com/angular-in-depth/how-to-build-a-component-library-with-angular-and-storybook-718278ab976](https://medium.com/angular-in-depth/how-to-build-a-component-library-with-angular-and-storybook-718278ab976) at the moment to execute the npm run storybook command appears like is executing everything but almost at the finish appearse the next messages.

ERROR in C:/Users/30202775/Documents/Visual Studio 2019/Repos/LibraryPoc/ng-ui/src/stories/index.stories.ts
ERROR in C:/Users/30202775/Documents/Visual Studio 2019/Repos/LibraryPoc/ng-ui/src/stories/index.stories.ts(1,24):
**TS2307: Cannot find module '@storybook/angular/demo'.**

**Expected behavior**
the expected behavior is that the app will run.

**System:**
Environment Info:

  System:
    OS: Windows 10 10.0.17763
    CPU: (8) x64 Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
  Binaries:
    Node: 10.16.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.5 - ~\AppData\Roaming\npm\npm.CMD
  npmPackages:
    @storybook/addon-actions: ^5.3.18 => 5.3.18
    @storybook/addon-links: ^5.3.18 => 5.3.18
    @storybook/addon-notes: ^5.3.18 => 5.3.18
    @storybook/addons: ^5.3.18 => 5.3.18
    @storybook/angular: ^5.3.18 => 5.3.18

**Additional context**
Angular CLI
![imagen](https://user-images.githubusercontent.com/3922920/82641295-5d0baf00-9bc9-11ea-8501-2ebef9fe41e2.png)

**Comment by witwit** [comment]
Same problem here

**Comment by lyx383982759** [comment]
Same problem here

**Comment by shilman** [comment]
@kroeder @matheo any idea what's going on here?

**Comment by adbenson** [comment]
I have a workaround:

In `src/stories/0-Welcome.stories.ts`, replace:
`import { Welcome } from '@storybook/angular/demo';` with
`import Welcome from '@storybook/angular/dist/demo/welcome.component';`

In `src/stories/1-Button.stories.ts`, replace:
`import { action } from '@storybook/addon-actions';` with
`import { action } from '@storybook/addon-actions/dist/preview/action';`
and
`import { linkTo } from '@storybook/addon-links';` with
`import { linkTo } from '@storybook/addon-links/dist/preview';`
and
`import { Button } from '@storybook/angular/demo';` with
`import Button from '@storybook/angular/dist/demo/button.component';`

Still needs to be fixed, but this got me started.

**Comment by matheo** [comment]
@adbenson I've worked with `import { linkTo } from '@storybook/addon-links'` without problems.

But I have no idea why the exported components could not work with this demo.js entrypoint:
```
/* eslint-disable global-require */
module.exports = {
  Welcome: require('./dist/demo/welcome.component').default,
  Button: require('./dist/demo/button.component').default,
};
```

**Comment by LeandroCarolino01** [comment]
Why the fuck do they keep storybook with a bug like that?

**Comment by shilman** [comment]
We are getting rid of the demo components in 6.0, which is currently in RC. If you create a new angular project and run:

```
npx sb@next init
```

You'll get a beautiful Angular storybook with a Button, Header, Page, and full Intro page and current best practices for writing your stories.

<img width="909" alt="Example___Introduction_-_Page_⋅_Storybook" src="https://user-images.githubusercontent.com/488689/87841433-aa5d8180-c8d7-11ea-8664-c453179f82f7.png">

**Comment by LeandroCarolino01** [comment]
still getting an error when running npm run storybook....

**Comment by shilman** [comment]
@LeandroCarolino01 in SB6 with a fresh install?

**Comment by LeandroCarolino01** [comment]
[14:50:23] No configuration file found, switching to CLI flags.
[14:50:23] "./tsconfig.base.json" file was not found in the current directory
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! testing-sb@0.0.0 docs:json: `compodoc -p ./tsconfig.base.json -e json -d .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the testing-sb@0.0.0 docs:json script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/leandrocarolino/.npm/_logs/2020-07-19T12_50_23_579Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! testing-sb@0.0.0 storybook: `npm run docs:json && start-storybook -p 6006`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the testing-sb@0.0.0 storybook script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/leandrocarolino/.npm/_logs/2020-07-19T12_50_23_606Z-debug.log






this is the error i am getting...

**Comment by shilman** [comment]
@LeandroCarolino01 seems like a separate issue. continuing the conversation here: https://github.com/storybookjs/storybook/issues/11609

**Comment by vinothmdev** [comment]
I tried the solution proposed in [Stackoverflow](https://stackoverflow.com/questions/60754585/unable-to-start-storybook-with-angular)
It worked for me.

The explicit declaration in **_typings.d.ts_** made it work

`declare module '@storybook/angular/demo'`
