### ISSUE TITLE
v6.0.0-beta.9 - Docs Story wrapper not full width.

### ISSUE THREAD

**Issue by lpoulter** [storybookjs/storybook#10872]
Not sure if this is a bug or not but #10801 changed the default behaviour of the story wrapper in docs. Before it was the full width of the storybook now it is sized to fit's it's content. 

This results in this change in my stories.

Before
<img width="1038" alt="Screenshot 2020-05-22 at 10 36 01" src="https://user-images.githubusercontent.com/3940567/82654066-109b9000-9c18-11ea-9d5e-a27d29a9e133.png">

After
<img width="1070" alt="Screenshot 2020-05-22 at 10 33 36" src="https://user-images.githubusercontent.com/3940567/82653941-e1851e80-9c17-11ea-97af-5d13743c35a8.png">

**Comment by benjamin-schneider** [comment]
I have the same issue (SB 6.0.0-beta.12 / react / ts)
![Peek 22-05-2020 11-49](https://user-images.githubusercontent.com/3585213/82655468-84429a80-9c22-11ea-8ba7-7897fcdce55d.gif)
Don't known if it would be possible to `display: block` instead of inline-block

**Comment by persefoniai** [comment]
Bit of a hack but you can address the issue by adding css overrides in the `preview.head.html`.  Couldn't quite figure through the wonky layout but the 42px right margin landed our content approximately evenly inside the preview block.

``` 
.sbdocs-preview > div:first-child > div:first-child {
    margin: 0px;
    padding-right: 42px;
  }

.sbdocs-preview > div:first-child > div:first-child > div:first-child {
    width: 100%;
  }
```

**Comment by shilman** [comment]
Jiminy cricket!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-beta.14 containing PR #10877 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
