### ISSUE TITLE
Toolbar buttons not centered

### ISSUE THREAD

**Issue by benjamin-schneider** [storybookjs/storybook#10870]
**Describe the bug**
_This is minor_
Since my last update from 6.0.0.-beta-8 to beta 6.0.0.-beta-12, buttons in the top bar (ToolbarComp) are no more vertically centered.

**To Reproduce**
1. Go to storybook home
2. Buttons are not vertically centered (see screenshot below)

**Expected behavior**
Buttons should be vertically centered

**Screenshots**
![Capture d’écran de 2020-05-22 09-37-32](https://user-images.githubusercontent.com/3585213/82643525-efcf3c80-9c0f-11ea-8838-0b945779dba4.png)

**System:**
`Environment Info:

  System:
    OS: Linux 5.4 Ubuntu 20.04 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
  Binaries:
    Node: 13.3.0 - ~/.nvm/versions/node/v13.3.0/bin/node
    npm: 6.13.1 - ~/.nvm/versions/node/v13.3.0/bin/npm
  Browsers:
    Chrome: 83.0.4103.61
    Firefox: 76.0.1
  npmPackages:
    @storybook/addon-actions: ^6.0.0-beta.12 => 6.0.0-beta.12 
    @storybook/addon-docs: ^6.0.0-beta.12 => 6.0.0-beta.12 
    @storybook/addon-jest: ^6.0.0-beta.12 => 6.0.0-beta.12 
    @storybook/addon-links: ^6.0.0-beta.12 => 6.0.0-beta.12 
    @storybook/addon-storysource: ^6.0.0-beta.12 => 6.0.0-beta.12 
    @storybook/addons: ^6.0.0-beta.12 => 6.0.0-beta.12 
    @storybook/preset-create-react-app: ^3.0.0 => 3.0.0 
    @storybook/react: ^6.0.0-beta.12 => 6.0.0-beta.12`

**Additional context**
I am not experienced enough with the project but it seems after a quick debug session that it comes from this component :
https://github.com/storybookjs/storybook/blob/v6.0.0-beta.12/lib/components/src/bar/button.tsx#L85
A simple `alignItems: 'center'` fixes the display problem.

**Comment by shilman** [comment]
Gadzooks!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-beta.14 containing PR #10897 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.
