### ISSUE TITLE
If I use component with knobs, I will get incorrect knobs when I switch page

### ISSUE THREAD

**Issue by evless** [storybookjs/storybook#10879]
**Describe the bug**
Hi! I met with a problem when I used @storybook/addon-knobs and @storybook/addon-docs. If I try to use components with knobs in docs and I open docs for other components, I will get component with knobs values for the previous component. If I switch docs on canvas, the problem will remain.

**Screenshots**
[first step](http://s.csssr.ru/U7RQKLD4J/2020-05-22-15-54-33-gadzw.jpg)
[second step](http://s.csssr.ru/U7RQKLD4J/2020-05-22-15-56-01-h7t9n.jpg)
[third step](http://s.csssr.ru/U7RQKLD4J/2020-05-22-15-56-23-wkyi2.jpg)

**Code snippets**
```tsx
// src/Button/index.stories.tsx

import React from "react";
import { Preview } from '@storybook/addon-docs/blocks'
import { text } from '@storybook/addon-knobs'

import { Button } from ".";

import page from './docs.mdx'

export default {
  title: "components/Button",
  parameters: { docs: { page } },
  includeStories: ['Interactive']
};

export const Interactive = () => <Button text={text('text', 'Button text')} />;

export const PreviewWrapper = () => (
  <Preview>
    <Interactive />
  </Preview>
)
```

```md
// src/Button/doc.mdx

import { PreviewWrapper } from './index.stories'

# Button

<PreviewWrapper />
```

```tsx
// src/Text/index.stories.tsx

import React from "react";
import { Preview } from '@storybook/addon-docs/blocks'
import { text } from '@storybook/addon-knobs'

import { Text } from ".";

import page from './docs.mdx'

export default {
  title: "components/Text",
  parameters: { docs: { page } },
  includeStories: ['Interactive']
};

export const Interactive = () => <Text text={text('text', 'Text')} color={text('color', 'red')} />;

export const PreviewWrapper = () => (
  <Preview>
    <Interactive />
  </Preview>
)
```

```
// src/Text/doc.mdx

import { PreviewWrapper } from './index.stories'

# Text

<PreviewWrapper />
```

**System:**
Environment Info:

  System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
  Binaries:
    Node: 13.10.1 - /usr/local/bin/node
    Yarn: 1.22.1 - /usr/local/bin/yarn
    npm: 6.13.7 - /usr/local/bin/npm
  Browsers:
    Chrome: 81.0.4044.138
    Firefox: 73.0.1
    Safari: 12.1.2
  npmPackages:
    @storybook/addon-docs: 5.3.18 => 5.3.18
    @storybook/addon-info: 5.3.18 => 5.3.18
    @storybook/addon-knobs: 5.3.18 => 5.3.18
    @storybook/react: 5.3.18 => 5.3.18
    @storybook/theming: 5.3.18 => 5.3.18

_But I tried and 6.0.0-beta.12 version_

**Additional context**
I created repo with example https://github.com/evless/storybook-docs-knobs-example

**Comment by shilman** [comment]
Hi gang, We’ve just released addon-controls in 6.0-beta!

Controls are portable, auto-generated knobs that are intended to replace addon-knobs long term.

- [Controls README](https://github.com/storybookjs/storybook/tree/next/addons/controls)
- [Migration instructions](https://github.com/storybookjs/storybook/blob/next/addons/controls/README.md#how-do-i-migrate-from-addon-knobs)

Please upgrade and try them out today. Thanks for your help and support getting this stable for release!

**Comment by evless** [comment]
Hi! I checked this package and yep, problem was resolved. :)
But I have come across another problem, I didn't get auto-generated knobs [screenshot](http://s.csssr.ru/U7RQKLD4J/2020-05-29-10-19-59-jj9mo.jpg) . I can create other issue. I did another branch, maybe it will be help you

https://github.com/evless/storybook-docs-knobs-example/tree/storybook-v6

**Comment by shilman** [comment]
For anybody who is interested in Controls but don't know where to start, I've created a quick & dirty step-by-step walkthrough to go from a fresh CRA project to a working demo. Check it out:

=> [Storybook Controls w/ CRA & TypeScript](https://gist.github.com/shilman/69c1dd41a466bae137cc88bd2c6ef487)

There are also some "knobs to controls" migration docs in the Controls README:

=> [How do I migrate from addon-knobs?](https://github.com/storybookjs/storybook/blob/next/addons/controls/README.md#how-do-i-migrate-from-addon-knobs)
