### ISSUE TITLE
HELP: Storyshots found 0 stories (Storybook v6 beta)

### ISSUE THREAD

**Issue by krankur** [storybookjs/storybook#10876]
### Support request 

Need help with setting up Storyshots. I am always getting the following error when I run `npm test`:

```
> jest tests

 FAIL  tests/storyshots.test.js
  ● Test suite failed to run

    storyshots found 0 stories

      2 | import initStoryshots, { multiSnapshotWithOptions } from '@storybook/addon-storyshots';
      3 | 
    > 4 | initStoryshots({
        | ^
      5 |     framework: 'html',
      6 |     integrityOptions: { cwd: path.resolve(__dirname, '../stories') },
      7 |     configPath: path.resolve(__dirname, '../.storybook'),

      at testStorySnapshots (node_modules/@storybook/addon-storyshots/dist/api/index.js:108:15)
      at Object.<anonymous> (tests/storyshots.test.js:4:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        4.028 s
Ran all test suites matching /tests/i.
(node:20997) ExperimentalWarning: The fs.promises API is experimental
npm ERR! Test failed.  See above for more details.
``` 

### My settings

- @storybook/html@6.0.0-beta.6
- @storybook/addon-storysource@6.0.0-beta.8

#### jest.config.js
```js
module.exports = {
    moduleNameMapper: {
        '^.+\\.(css|less|scss)$': 'babel-jest'
    },
    transform: {
        '^.+\\.js$': 'babel-jest'
    },
    moduleFileExtensions: ['js', 'json']
};
```

#### tests/storyshots.test.js
```js
import path from 'path';
import initStoryshots, { multiSnapshotWithOptions } from '@storybook/addon-storyshots';

initStoryshots({
    framework: 'html',
    integrityOptions: { cwd: path.resolve(__dirname, '../stories') },
    configPath: path.resolve(__dirname, '../.storybook'),
    test: multiSnapshotWithOptions()
});
```

#### stories/button.stories.js
```js
export default {
    title: 'Components|Button',
};

export const basic = () => '<button>Click me!</button>';
```

#### Folder structure
- .storybook
  - main.js
  - preview.js
- src
- stories
  - button.stories.js
- tests
  - storyshots.test.js
- jest.config.js

**Comment by MarkLyck** [comment]
I have the same issue with a more minimal setup:

Storyshots.test.js
```
import initStoryshots from '@storybook/addon-storyshots'

initStoryshots()
```

jest.config.js
```
module.exports = {
  moduleNameMapper: {
    '\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$':
      '<rootDir>/__mocks__/fileMock.js',
    '\\.(css|less|scss)$': 'identity-obj-proxy',
  },
}
```

**Comment by krankur** [comment]
So, I tried looking at the official [live examples](https://github.com/storybookjs/storybook/tree/next/examples) but still can't figure out what is the issue. Looks like something is wrong with my configurations. Any help here would be much appreciated.

**Comment by shivamyth** [comment]
getting error on npm test


Test suite failed to run

    storyshots found 0 stories

      2 | 
      3 | import initStoryshots from "@storybook/addon-storyshots";
    > 4 | initStoryshots();
        | ^
      5 | 

      at testStorySnapshots (node_modules/@storybook/addon-storyshots/dist/api/index.js:108:15)
      at Object.<anonymous> (src/storybook.test.ts:4:1)

**Comment by daviddwmd** [comment]
I'm getting the exact same error as @shivamyth - standard cra setup.  When I run storybook, it finds my stories just fine, but npm run test gives the error above.

**Comment by omegazheng** [comment]
I had similar issues when I put storyshots.test.js under project root folder. When I moved storyshots.test.js to /stories folder, it works.

**Comment by RomkeVdMeulen** [comment]
Bizarre: if I rename `next-env.d.ts` to anything else, I get `storyshots found 0 stories`. I rename it back, the error is gone. Even though there's no reference to that file anywhere that Storyshots should be affected by.

**Comment by RomkeVdMeulen** [comment]
This workaround helped me: https://github.com/storybookjs/storybook/issues/12242

> Changing typescript.json's jsx:"preserve" to jsx: "react" fixes this issue, though some warnings remain.

**Comment by israeldax** [comment]
not for me

**Comment by jorgegir** [comment]
I'm using latest CRA setup. Storybook works ok and storyshots finds 0 stories.

**Comment by Nakroma** [comment]
For me the issue was unmocked css files (e.g. a `cannot find module `./pages.css` error). However, I have no idea why this isn't logged (this line here doesn't output anything https://github.com/storybookjs/storybook/blob/next/lib/core/src/client/preview/loadCsf.ts#L60). If you have the same problem I suggest you going into `node_modules/@storybook/core/dist/client/preview/loadCsf.js` and outputing the error to a file in the try/catch in loadStories() to get why your stories aren't loading.

**Comment by mivd7** [comment]
Hi,
I'm very new to Storybook, so sorry for any ignorance on my part. I'm trying to learn it from your tutorial. I have followed each step in the tutorial exactly the way it's prescribed and have reached the part about snapshot testing [on this page](https://www.learnstorybook.com/intro-to-storybook/react/en/simple-component/). However after adding the 'storybook.test.js' file with the provided code, it gives me the same error as stated in this issue. I'm using the latest version of CRA and Storybook. Anyone know what might be wrong?

**Comment by MR-Neto** [comment]
@shilman any news? I am running CRA latest with storybook latest and storyshots doesn't find my MDX stories. I have added the jest transform.

**Comment by bryanrasmussen** [comment]
I just had the problem, it turns out it was the same solution as Nakroma, there were a  couple modules that storybook couldn't find even though everything else worked with loading them fine.

**Comment by mike-odom** [comment]
We ran into this issue and spent a good amount of time trying to fix it. 

I think the big issue here is that Jest suppresses console logs  by default. I went into our jest config in package.json and added:
```"verbose": true,```

That then showed the error we were having that prevented it from loading the stories:
```
console.warn
    Unexpected error while loading ./components/common/add-button/AddButton.stories.js: TypeError: basePath.slice is not a function
```

(There was something in our code that depended on a babel macro. Adding `"macros"` to the babel plugins fixed it. But your issue will probably vary.)

**Comment by Saiteja-vadlapatla** [comment]
I was banging my head over this issue for a ridiculous amount of time. I could finally fix it by making two crucial changes -
1. Move the entire jest config to `jest.config.js` file.
2. Although you mention environment as `jsdom` in the config file, it could be overridden, especially in the case of CRA. Add a CLI command explicitly as `jest --env=jsdom` to the test script.

Although, each might have a different reason for failure, I thought this might help.

**Comment by cimbis** [comment]
None of the above proposed solutions worked for me - switched to https://github.com/oblador/loki for image snapshot testing.

**Comment by kpdecker** [comment]
I was able to resolve one instance of this by using `module.exports =` rather than `export default` in main.ts.

https://github.com/storybookjs/storybook/blob/8d7fa4249cc73f315cfc15ebd8c6f0d574f341d5/addons/storyshots/storyshots-core/src/frameworks/configure.ts#L53

Does not appear to be aware of `default` export which works for other parts of storybook.

**Comment by ndelangen** [comment]
The future of storyshots is the test-runner:
https://storybook.js.org/docs/react/writing-tests/test-runner#page-top

And use the play function for expectations:
https://storybook.js.org/docs/react/writing-stories/play-function#page-top

We will not be making any improvement / changes to storyshots.
