### ISSUE TITLE
Built storybook show the application included revursively

### ISSUE THREAD

**Issue by chrifmarwen** [storybookjs/storybook#10882]
**Describe the bug**
Got Storybook app included recusrsivelry when serving the build.
Starting the storybook on dev mode is working fine.

**To Reproduce**
1. Build sotrybook
2. Serve the build

**Expected behavior**
Storybook that works perfectly.

**Screenshots**

![image](https://user-images.githubusercontent.com/3867438/82682437-8bcc6880-9c4f-11ea-8aab-c4246bbffe72.png)

**System:**
Environment Info:

  System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  Binaries:
    Node: 10.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.11.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    @storybook/addon-actions: ^5.3.18 => 5.3.18
    @storybook/addon-knobs: ^5.3.18 => 5.3.18
    @storybook/addon-links: ^5.3.18 => 5.3.18
    @storybook/addon-notes: ^5.3.18 => 5.3.18
    @storybook/addon-options: ^5.3.18 => 5.3.18
    @storybook/channels: ^5.3.18 => 5.3.18
    @storybook/preset-create-react-app: ^3.0.0 => 3.0.0
    @storybook/react: ^5.3.18 => 5.3.18

**Additional context**
It's a mono-repo package, i got the problem after upgrade from 5.2.5
On my webpack.config.js i have a rule that inclue all the concerned packages:
```javascript
{
    test: /\.(js|mjs|jsx|ts|tsx)$/,
    include: [
      path.resolve(__dirname, '../../front-ui/src'),
      path.resolve(__dirname, '../../front-control/src'),
      path.resolve(__dirname, '../../front-myaccount/src'),
      path.resolve(
        __dirname,
        '../../common/backoffice-components/src',
      ),
    ],
    use: [
      {
        loader: 'babel-loader',
        options: {
          cacheDirectory: './node_modules/.cache/storybook',
          presets: [
            [
              '@babel/preset-env',
              {
                shippedProposals: true,
                useBuiltIns: 'usage',
                corejs: '3',
              },
            ],
            '@babel/preset-react',
            '@babel/preset-flow',
          ],
          plugins: ['@babel/plugin-proposal-class-properties'],
        },
      },
    ],
  }
```

**Comment by shilman** [comment]
closing as dupe to #5269
