### ISSUE TITLE
addon-docs - Story cannot be a child of another element or Component

### ISSUE THREAD

**Issue by alanshortis** [storybookjs/storybook#10883]
When using the `Story` component to create stories for the canvas view inside my documentation, I'd like to be able to make stories the child of another element. E.g. listing a set of icons available, which happen to be React components.

I'd like to be able to have these in the canvas view (so I can use knobs, a11y, etc) but make the documentation for them more attractive.

1. Place a component inside a `Story` component.
2. Wrap that in any other element, either a component or just a div.
3. Reloading the page thows an error: `Invalid name '', must include alphanumeric characters`

**Expected behavior**
Stories should work as normal even if they're a child of any other component or element.

**Code snippets**
Adding a wrapper like this causes the error:

```
<div>
  <Story name="CoachProductIcon">
    <Icons.CoachProductIcon />
  </Story>

  <Story name="IdProductIcon">
    <Icons.IdProductIcon />
  </Story>
</div>
```

**System:**
```
System:
    OS: macOS 10.15.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 12.1.0 - ~/.nvm/versions/node/v12.1.0/bin/node
    npm: 6.9.0 - ~/.nvm/versions/node/v12.1.0/bin/npm
  Browsers:
    Chrome: 81.0.4044.138
    Safari: 13.1
  npmPackages:
    @storybook/addon-a11y: ^5.3.18 => 5.3.18 
    @storybook/addon-backgrounds: ^5.3.18 => 5.3.18 
    @storybook/addon-docs: ^5.3.18 => 5.3.18 
    @storybook/addon-knobs: ^5.3.18 => 5.3.18 
    @storybook/addon-viewport: ^5.3.18 => 5.3.18 
    @storybook/react: ^5.3.18 => 5.3.18 
    @storybook/storybook-deployer: ^2.8.1 => 2.8.1 
```

**Comment by davidleiva** [comment]
Same error here, but when using styled components....

**Comment by shilman** [comment]
You should be able to wrap these in a `Canvas` block:

```
import { Canvas, Story } from '@storybook/addon-docs/blocks';

```md
<Canvas>
  <Story name="CoachProductIcon">
    <Icons.CoachProductIcon />
  </Story>
  <Story name="IdProductIcon">
    <Icons.IdProductIcon />
  </Story>
</Canvas>
```

**Comment by alanshortis** [comment]
Just adding a new comment - I'm still unable to get the desired result in MDX stories. The suggestion to put multiple stories in one `Canvas` isn't really viable, as they just sit toegther in the canvas and their code snippets are combined:

<img width="1029" alt="Screenshot 2022-05-11 at 16 52 12" src="https://user-images.githubusercontent.com/3787454/167893648-dde287ba-08fb-4980-b022-7e66ff8bb920.png">

What I really want to do is render all of my icons in a Grid, while still using `Story` around each one so that I can keep using Chromatic for varification and getting the list of icons in the sidebar. 

Ideally, `Canvas` should  still work when it's the child of a containing element, AND can be extended in a styled component:

```
const SomeStyledContainer = styled(Canvas)`
  // Grid styles or whatever
`;

```

Later...

```
<SomeStyledContainer>
  <Story name="Chevron left">
    <ChevronIcon direction="left" />
  </Story>
</SomeStyledContainer>
```
