### ISSUE TITLE
Beta.13: Angular preview is broken

### ISSUE THREAD

**Issue by matheo** [storybookjs/storybook#10891]
**Describe the bug**

The docs for my Angular components were working on `beta.8` but in `beta.13` they are broken.

I have a custom MDX page as default doc page:
```
import { Description, Story, Subtitle, Title } from '@storybook/addon-docs/blocks';

<Title />
<Subtitle />
<Description />

<Story id="." />
```
and the Story only renders fine in the Canvas tab, but not in the Docs page.

**Screenshots**

In `beta.8` I had this log:
![image](https://user-images.githubusercontent.com/260185/82719832-c1834880-9c73-11ea-8391-b243a4a20561.png)

and in `beta.13` the `globalArgsUpdated` maybe had a side effect:
![image](https://user-images.githubusercontent.com/260185/82719901-3191ce80-9c74-11ea-9ef8-02a4255ba28f.png)

**Comment by matheo** [comment]
@shilman reverting https://github.com/storybookjs/storybook/pull/10833/files made it work again :(

**Comment by shilman** [comment]
@matheo thanks for tracking this down. checking it out now!

**Comment by matheo** [comment]
@shilman I've applied your double-rendering fix attempt and I'm afraid that it doesn't work, the `GLOBAL_ARGS_UPDATED` event triggers the error.

Looking at `lib/core/src/client/preview/StoryRenderer.tsx`, the listener to `GLOBAL_ARGS_UPDATED` is set to force the render, so I changed it to `this.renderCurrentStory(false)` instead `this.forceReRender()` and that seems to work.

Anyways, the pushed fix definitely removes the double `RENDER_CURRENT_STORY` event, and the complete refactor will be nice to have. Now I will create a PR.

**Comment by matheo** [comment]
Can we have another beta release with this stuff
so I can present the latest beta in my company please? :)
Thanks in advance!

**Comment by shilman** [comment]
Jeepers creepers!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-beta.14 containing PR #10892 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Shiver me timbers!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-beta.18 containing PR #10910 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
