### ISSUE TITLE
markdown-to-jsx high risk vulnerability

### ISSUE THREAD

**Issue by merlinpatt** [storybookjs/storybook#10899]
**Describe the bug**
`npm audit` reports an unpatched vulnerability with markdown-to-jsx.

| High | Cross-Site Scripting |
|-----|-----|
| Package       | markdown-to-jsx                                              |
| Patched in    | No patch available                                           |
| Dependency of | @storybook/react [dev]                                       |
| Path          | @storybook/react > @storybook/core > @storybook/ui > markdown-to-jsx  |
| More info     | https://npmjs.com/advisories/1219                            |

This is also a dependency of `addon-actions`, `addon-storyshots`, and `addon-viewport`

**To Reproduce**
1. Install latest versions of `@storybook/react` or addons listed above
2. Run `npm audit`
3. See error

**Comment by shilman** [comment]
closing as dupe to #10871
