### ISSUE TITLE
Beta.13: Toolbar styles not centered

### ISSUE THREAD

**Issue by matheo** [storybookjs/storybook#10890]
**Describe the bug**

Playing with `beta.13` I've notices some missing flex-centered buttons in the toolbar.
Seems to apply for `button` elements but doesn't affect the `a` links.

**Screenshots**

![image](https://user-images.githubusercontent.com/260185/82716428-fcc64d00-9c5c-11ea-891a-5e1809faa684.png)

![image](https://user-images.githubusercontent.com/260185/82716944-bf16f380-9c5f-11ea-83da-297d99468bf5.png)

**Comment by shilman** [comment]
Closing as dupe to #10870
