### ISSUE TITLE
CSF: Hoist story annotation

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#10906]
### What

Hoist the `.story` annotation in CSF, deprecating `.story` and moving all `.story` fields to the story function directly (except `.name` which gets renamed `.storyName`.

So the following:

```js
export const Basic = () => <Button />
Basic.story = {
  name: 'foo',
  parameters: { ... },
  decorators: [ ... ],
};
```

Becomes:

```js
export const Basic = () => <Button />
Basic.storyName = 'foo';
Basic.parameters = { ... };
Basic.decorators = [ ... ];
```

### Why

1. The new syntax is slightly more compact/ergonomic compared the the old one
2. Similar to React's `displayName`, `propTypes`, `defaultProps` annotations
3. We're introducing a new feature, [Storybook Args](https://docs.google.com/document/d/1Mhp1UFRCKCsN8pjlfPdz8ZdisgjNXeMXpXvGoALjxYM/edit?usp=sharing), where the new syntax will be significantly more ergonomic

### What

- [x] Update CSF loader
- [x] Deprecate `.story` annotation
- [x] Codemod `csf-hoist-story-annotations`
- [x] Update MDX compiler
- [ ] Update documentation
- [ ] Update CSF type definitions
- [ ] Update existing codemods

**Comment by kroeder** [comment]
Looks good! Any plans for shipping an auto-update for existing stories?

**Comment by shilman** [comment]
Boo-yah!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-beta.14 containing PR #10907 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
