### ISSUE TITLE
storybook 5.3.19    react-scripts 3.4.1    TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by roger922222** [storybookjs/storybook#10903]
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined

**Comment by tooppaaa** [comment]
Could you please provide a bit more context ?

**Comment by roger922222** [comment]
> Could you please provide a bit more context ?

start-storybook -p 9009 -s public

info @storybook/react v5.3.19
info => Loading presets
info => Loading presets
info => Adding stories defined in ".storybook/main.js".
WARN Unable to close preview build!
info => Loading Webpack configuration from `node_modules/react-scripts`
info => Removing existing JavaScript and TypeScript rules.
info => Modifying Create React App rules.
ERR! TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined

tsconfig.json
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react"
  },
  "include": [
    "src"
  ]
}

.storybook/main.js
module.exports = {
  stories: ['../src/**/*.stories.js'],
  addons: [
    '@storybook/preset-create-react-app',
    '@storybook/addon-actions',
    '@storybook/addon-links',
  ],
};

package.json
"dependencies": {
    "@fortawesome/fontawesome-svg-core": "^1.2.28",
    "@fortawesome/free-solid-svg-icons": "^5.13.0",
    "@fortawesome/react-fontawesome": "^0.1.9",
    "classnames": "^2.2.6",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-transition-group": "4.3.0"
  },
"devDependencies": {
    "@storybook/addon-actions": "^5.3.19",
    "@storybook/addon-links": "^5.3.19",
    "@storybook/addons": "^5.3.19",
    "@storybook/preset-create-react-app": "^3.0.0",
    "@storybook/react": "^5.3.19",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.3.2",
    "@testing-library/user-event": "^7.1.2",
    "@types/classnames": "^2.2.10",
    "@types/jest": "^24.0.0",
    "@types/node": "12.12.14",
    "@types/react": "^16.9.0",
    "@types/react-dom": "^16.9.0",
    "@types/react-transition-group": "4.2.3",
    "node-sass": "^4.14.1",
    "typescript": "~3.7.2",
    "react-scripts": "3.4.1"
  }

**Comment by shilman** [comment]
Do you have a repro repo?

**Comment by roger922222** [comment]
> Do you have a repro repo?

https://github.com/roger922222/popular-ui.git

**Comment by vikene** [comment]
@shilman I too face this same issue.

**Comment by shilman** [comment]
@roger922222 not able to repro on a fresh install

**Comment by lukasholzer** [comment]
Maybe this is connected with the react issue as well: #11125

**Comment by roger922222** [comment]
> @roger922222 not able to repro on a fresh install

separate storybooks from react-scripts
