### ISSUE TITLE
Story code doesn't show up for `storiesOf` syntax

### ISSUE THREAD

**Issue by vaclav-zeman** [storybookjs/storybook#10911]
**Describe the bug**
When I migrate from addons-info to addons-docs and use codemod to add `addParameters({ component: ... })` to my stories, the code button doesn't show the story's code. Instead it just shows e.g. `DefaultButton` (just the name of the story)

However when I rewrite it using CSF syntax, it works but that's not a solution for me - I'd like to keep `storiesOf` for now.

EDIT: also it works like this `.add('Simple badge', () => <Badge count={5} />)` but that makes it impossible to use the story component inside tests. 

**Expected behavior**
Show story's code for `storiesOf` syntax

**Screenshots**
(another bug: the non-code text is black btw) 
![image](https://user-images.githubusercontent.com/8337116/82808154-ac800280-9e89-11ea-9b2c-af47f6510a4c.png)

**Code snippets**
main.js `...   addons: ['@storybook/addon-actions', '@storybook/addon-docs'], ...`
index.stories.js
```js
import React from 'react';
import { storiesOf } from '@storybook/react';

import Badge from './index';

export const DefaultBadge = () => <Badge count={5} />;

storiesOf('Badge', module)
  .addParameters({
    component: Badge,
  })
  .add('Simple badge', DefaultBadge);
```

**System:**
```
Environment Info:

  System:
    OS: macOS 10.15.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.12.1 - ~/.nvm/versions/node/v12.13.1/bin/npm
  Browsers:
    Chrome: 81.0.4044.138
    Edge: 83.0.478.37
    Firefox: 72.0.2
    Safari: 13.0.5
  npmPackages:
    @storybook/addon-actions: ^5.3.19 => 5.3.19 
    @storybook/addon-docs: ^5.3.19 => 5.3.19 
    @storybook/addon-storyshots: ^5.3.19 => 5.3.19 
    @storybook/addon-storyshots-puppeteer: ^5.3.19 => 5.3.19 
    @storybook/addons: ^5.3.19 => 5.3.19 
    @storybook/codemod: ^5.3.19 => 5.3.19 
    @storybook/react: ^5.3.19 => 5.3.19 
    @storybook/theming: 5.3.19 => 5.3.19 
```

**Comment by shilman** [comment]
As of #11601 in 6.0 when you set the parameter `docs.source.type` to `'dynamic'` it will force docs to display the rendered JSX output, similar to addon-info.

```
npx sb@next upgrade --prerelease
```
