### ISSUE TITLE
`fileName` parameter broken in 5.3.19

### ISSUE THREAD

**Issue by rhendric** [storybookjs/storybook#10914]
**Describe the bug**
In 5.3.18, the `fileName` parameter could be relied upon to give the webpack module ID of the story file (either a path, in development mode, or a numeric ID in production). With 5.3.19, the `fileName` parameter is now a path that is not the module ID.

It looks like this was changed in #10539, in order to fix #10519. But the v6 branch doesn't seem to have this change, so perhaps there is some other way to fix search that doesn't break `fileName`?

Alternatively, if the new `fileName` behavior is here to stay, maybe there could be another parameter added to stories with the module ID instead?

**Comment by shilman** [comment]
Aha this got merged directly into master (cc @ndelangen)

We can probably revert this fix if it's a deal-breaker. We plan to overhaul search in 6.1 and can probably find a proper workaround then.

Why do you need to the module ID?

**Comment by rhendric** [comment]
Well, I've been working on an addon to address #729 more robustly than existing solutions in that thread; it's almost ready to be published, as soon as I figure out how to deal with this issue. Based on the design I outlined [here](https://github.com/storybookjs/storybook/issues/729#issuecomment-620090330), it uses a custom webpack plugin to determine at build time which stories use which CSS files, but the only identifier webpack has for story files is their module IDs. So at run time, the addon needs a way to get the module ID for the story that was just selected, so that it can look up which styles to activate.

This is admittedly a warranty-voiding sort of situation; it wouldn't surprise me if you just wanted to say you don't support using `fileName` for this purpose. But if it isn't too much trouble to revert, it's certainly much more convenient for me to use that rather than do even more hacking in webpack internals to try to inject module IDs into story parameters myself. As I said, I'd also be perfectly happy with a new parameter instead of `fileName`, if that would be preferable.

**Comment by shilman** [comment]
@ndelangen this sounds like your territory

**Comment by ndelangen** [comment]
https://github.com/storybookjs/storybook/pull/10916

**Comment by shilman** [comment]
Olé!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.20 containing PR #10916 that references this issue. Upgrade today to try it out!
