### ISSUE TITLE
MDX story with @storybook/addon-jest

### ISSUE THREAD

**Issue by Bowriverstudio** [storybookjs/storybook#10912]
**Is your feature request related to a problem? Please describe.**

I am not sure how to get "addon-jest" to work with MDX.

**Describe alternatives you've considered**

In my CSF story.

``
export default {
  title: "Menu-Icon",
  decorators: [withKnobs],
  excludeStories: /.*Data$/,
};

export const closeIconStory = () => (
  <CloseIcon color={text("Color", "red")} size={text("Size", "24px")} />
);

closeIconStory.story = {
  parameters: {
    jest: ["MenuIcon.test.js"]
  }
};
``

In my MDX file

import {closeIconStory} from "./MenuIcon.stories.js"

<Preview>
  <Story name="CloseIcon">
    <div style={{background : '#1f38c5', padding: '15px'}}>
    	{closeIconStory()}
    </div>
  </Story>
</Preview>

When viewing the component from MDX I get:

No tests found
Learn how to add Jest test results to your story

When viewing the story from CSF I see the tests as expected.

In the ideal case, I would not need to import the story from CSF.

**Are you able to assist bring the feature to reality?**
No

**Comment by shilman** [comment]
Possible dupe to #9470

**Comment by Bowriverstudio** [comment]
@shilman thank you for the response.  I think I'm just having a syntax issue.  I'm not really sure where to look for the documentation.

**Comment by Bowriverstudio** [comment]
Sorry if I am not clear: 

This works perfectly. 

https://github.com/storybookjs/storybook/tree/master/addons/jest 

I cannot get it to work in my "MDX" stories.

**Comment by shilman** [comment]
I see. I didn't understand the question.

You can use parameters in MDX at both the component and story level,  and it's documented here: https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/mdx.md#decorators-and-parameters

Translating your CSF from above:

```
<Story name="Close Icon" parameters={{ jest: ["MenuIcon.test.js"]}} >
  <CloseIcon color={text("Color", "red")} size={text("Size", "24px")} />
</Story>
``` 

Hope that helps!

**Comment by Bowriverstudio** [comment]
Thank you - that works perfectly
