### ISSUE TITLE
automatic initialization fails in projects using yarn workspaces

### ISSUE THREAD

**Issue by dantman** [storybookjs/storybook#10915]
**Describe the bug**
Attempting to run `npx -p @storybook/cli sb init` in projects using yarn workspaces fails with the following error:
```
 • Detecting project type. ✓
yarn add v1.22.4
error Running this command will add the dependency to the workspace root rather than the workspace itself, which might not be what you want - if you really meant it, make it explicit by running this command again with the -W flag (or --ignore-workspace-root-check).
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
An error occurred while installing dependencies.
{
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 47115,
  stdout: null,
  stderr: null,
  error: null
}
```

This is because `yarn add` requires a `-W` flag as a safety measure when adding something to the root of a workspace.

**To Reproduce**
Steps to reproduce the behaviour:
1. Setup yarn workspaces in a project: https://classic.yarnpkg.com/en/docs/workspaces/
2. Try to run the storybook init command

**Expected behaviour**
Storybook should automatically add the -W flag so the init command continues working.

**Comment by shilman** [comment]
@tooppaaa maybe related to your current project?

**Comment by tooppaaa** [comment]
Nop, it's close but it's not :)
The line responsible of the error is probably
https://github.com/storybookjs/storybook/blob/next/lib/cli/src/helpers.ts#L250

We can either:
- detect if we're in a yarn workspace using package.json and add `-W`
- add `--ignore-workspace-root-check`

I would go for second option. Just need to make sure it's a no-op on non-workspace environment

**Comment by shilman** [comment]
🤔  hmmm @gaetanmaisse @ndelangen ?

**Comment by gaetanmaisse** [comment]
+1 for the second option, `-W` is a shortcut for `--ignore-workspace-root-check` and is a no-op in non-workspace env so I think we should use the most understandable name 😄

**Comment by shilman** [comment]
Boo-yah!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-beta.21 containing PR #10985 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.
