### ISSUE TITLE
Addon-docs: Canvas mode

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#10921]
### What

Add a "canvas" mode for addon-docs to address mode-switching headaches in the current "normal" mode. Users will create "docs-only" stories that show up in the canvas, and the `Docs` tab will be completely hidden

<img width="746" alt="CSF" src="https://user-images.githubusercontent.com/488689/82970667-59ca5600-a003-11ea-8fed-31503a2ca147.png">

### Why

We currently have "mixed" mode (currently the default), which shows both `Canvas` and `Docs` tabs. The idea here is that you can develop your stories in `Canvas` mode and easily see the generated documentation by switching tabs.

We also have a "docs" mode. This is optimized for users browsing the app or library documentation. It hides the Canvas tab completely and compacts the UI a bit.

However, there's another use case, as [described here](https://github.com/storybookjs/storybook/issues/10592#issuecomment-623632745) where devs want to see the stories, and designers want to see all the stories in one place. Currently the user achieves this by hacking the `viewMode` parameter to automatically switch between the tabs in mixed mode. But what if, instead, we made it easy to embed docs-only MDX that shows up as stories alongside the normal stories, and eliminates the need for a Docs tab in this case? It would eliminate the need for a separate tab, and potentially result in a cleaner, non-moded UI.

**Comment by ndelangen** [comment]
> But what if, instead, we made it easy to embed docs-only MDX that shows up as stories alongside the normal stories, and eliminates the need for a Docs tab in this case? It would eliminate the need for a separate tab, and potentially result in a cleaner, non-moded UI.

Could you help me understand this better?

Maybe some visual will help. I'm having difficulty understanding, sorry.

**Comment by shilman** [comment]
@ndelangen here you go:

<img width="746" alt="CSF" src="https://user-images.githubusercontent.com/488689/82970667-59ca5600-a003-11ea-8fed-31503a2ca147.png">

**Comment by ndelangen** [comment]
I like it!

**Comment by marvhen** [comment]
I am interested in this functionality.  Any updates?
