### ISSUE TITLE
Addon-docs for ember can't be install

### ISSUE THREAD

**Issue by Anne-Gaelle-S** [storybookjs/storybook#10945]
**Describe the bug**

I was trying to follow the installation of addon-docs at : https://github.com/storybookjs/storybook/tree/master/addons/docs/ember#docspage but I can't get it works.
I tried a lot of different way but none works ... What I am missing ? Is addon-docs really supported for ember ?

**To Reproduce 1**
1. `npm install @storybook/addon-docs@next`
2. Add `addons: ['@storybook/addon-docs'], ` in `.storybook/main.js` : 
```js
module.exports = {
  addons: ['@storybook/addon-docs'],
  stories: ['../addon/**/*.stories.[tj]s'],
};
```
3. `npm run storybook`
4. See error : `TypeError: modules[moduleId] is undefined` in console and storybook is infinitly loading : 
<img width="1678" alt="image" src="https://user-images.githubusercontent.com/38167520/83021741-c278f900-a02a-11ea-80d4-04f69493e44c.png">

**To Reproduce 2**
1. `npm install @storybook/addon-docs` -> just a test without @next
2. Add `addons: ['@storybook/addon-docs'], ` in `.storybook/main.js` : 
```js
module.exports = {
  addons: ['@storybook/addon-docs'],
  stories: ['../addon/**/*.stories.[tj]s'],
};
```
3. `npm run storybook` -> working here, with a new "docs" tab !!
4. Add `enableAddonDocsIntegration: true` in `ember-cli-build.js` :
```js 
'use strict';
const EmberAddon = require('ember-cli/lib/broccoli/ember-addon');
module.exports = function(defaults) {
  let app = new EmberAddon(defaults, {
    'ember-cli-storybook': {
      enableAddonDocsIntegration: true,
    }
  });
  return app.toTree();
};
```

5.  `npm run storybook` -> failing at 68% build time with : `EMFILE: too many open files, watch`.
After write endlessly : 

```
error: Node.js version: v12.14.1
error: YUI version: 3.18.1
error: YUIDoc version: 0.10.2
error: Please file all tickets here: http://github.com/yui/yuidoc/issues
error: --------------------------------------------------------------------------
error: --------------------------------------------------------------------------
error: An uncaught YUIDoc error has occurred, stack trace given below
error: --------------------------------------------------------------------------
error: Error: EMFILE: too many open files, watch
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:123:28)
error: --------------------------------------------------------------------------
```

**Expected behavior**
I was expected to see my Tooltip component (working before installing addon-docs) with a new "docs" tab...

**System:**
```
Environment Info:

  System:
    OS: macOS 10.15.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.14.1/bin/npm
  Browsers:
    Firefox: 76.0.1
    Safari: 13.0.5
  npmPackages:
    @storybook/addon-docs: ^5.3.19 => 5.3.19
    @storybook/addons: ^5.3.19 => 5.3.19
    @storybook/ember: ^6.0.0-alpha.27 => 6.0.0-alpha.45
    @storybook/ember-cli-storybook: ^0.2.1 => 0.2.1
    @storybook/theming: ^5.3.19 => 5.3.19
```

**Comment by shilman** [comment]
cc @meirish

**Comment by Krysthalia** [comment]
This bug is not solved and we could not install addon-doc. 
However we are still interested to use this addon...
