### ISSUE TITLE
Add helper for missing dependencies and setup

### ISSUE THREAD

**Issue by mrmckeb** [storybookjs/storybook#10943]
We notice that a lot of reported issues relate to incorrect project configuration. If users are missing critical dependencies or config, we should warn them - or in some cases throw.

Examples:
- `typescript` (dependency)
- `tsconfig.json`

**Comment by mrmckeb** [comment]
I think we can use this as a reference for this work:
https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/scripts/utils/verifyTypeScriptSetup.js

**Comment by shilman** [comment]
Shiver me timbers!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-beta.21 containing PR #10998 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
