### ISSUE TITLE
6.0.0-beta.14 issues with css display

### ISSUE THREAD

**Issue by JBusch** [storybookjs/storybook#10940]
Components are getting displayed as if they are zoomed.

For example radio-buttons local: 
![image](https://user-images.githubusercontent.com/287425/82990269-36e87380-9ffc-11ea-9434-df56ae8b3da6.png)

vs. radio-buttons in storybook:
![image](https://user-images.githubusercontent.com/287425/82990229-259f6700-9ffc-11ea-9d3e-5adea2b7f07f.png)

I'm using angular storybook.

**Comment by shilman** [comment]
@JBusch do you have a repro repo we can look at?

@ndelangen could this be related to the zoom / layout changes?

**Comment by JBusch** [comment]
@shilman i'm sorry, it is not public :-/
I'm in the discord chat so if i could provide feedback this way, i'm happy to help.

**Comment by ndelangen** [comment]
Please ping me on discord! Happy to debug this a bit!

**Comment by shilman** [comment]
@ndelangen possibly (but not necessarily) related:

<img width="823" alt="Addons___A11y___BaseButton_-_Default_⋅_Storybook" src="https://user-images.githubusercontent.com/488689/83038590-b9f6e180-a06f-11ea-9ef3-c7c44118e4b9.png">

This button showed up as a square until recently. Now it shows up as a squished rectangle for me. I don't know when it changed and why chromatic didn't catch it.

**Comment by ndelangen** [comment]
works on my machine on `next` ?

<img width="677" alt="Screenshot 2020-05-28 at 11 38 02" src="https://user-images.githubusercontent.com/3070389/83125418-cadb3d80-a0d7-11ea-8409-f242643a8474.png">

**Comment by ndelangen** [comment]
You must have zoomed @shilman ..

**Comment by jkimmeyer** [comment]
@ndelangen This problem appears, in case you are not using  `boxSizing: border-box` for your button component. I assume you use a centered layout in your local setup. You should also be able to confirm the bug on https://next--storybookjs.netlify.app/official-storybook/?path=/story/addons-a11y-basebutton--default, where a padded layout is applied.

Currently the `box-sizing` property is set to `initial` for padded and fullscreen layouts right here and this is leading to the aforementioned issue: https://github.com/storybookjs/storybook/blob/4b18fb65102c8a3f9bb58473138bc4905d1e966c/lib/core/src/client/preview/StoryRenderer.tsx#L24-L52

**Comment by lpoulter** [comment]
We have the same issue. We set the following CSS in our library
```
*,
*::before,
*::after {
  box-sizing: inherit;
}

html,
body {
  box-sizing: border-box;
}
```

However Storybook resets `box-sizing` to `box-sizing: initial;` this causes our :after elements to inherit an unintended box-sizing

**Comment by shilman** [comment]
Great Caesar's ghost!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-beta.28 containing PR #11175 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.
