### ISSUE TITLE
Addon-docs: props table also for classes (not only components)

### ISSUE THREAD

**Issue by meriturva** [storybookjs/storybook#10952]
We just would like to use StoryBook to document also business classes and we would like to use props table to show on our mdx properties and method of our classes (mixed with stories for UI).

Is it possible to have props table works also on `methods` and `properties` array of document.json produced by compodoc?

**Comment by shilman** [comment]
Should be possible to add this, but I don't know that we'd support it officially any time soon. I'd like to see the demand for this feature before considering it.

In the short term, here's where to look if you'd like to play around with it:

https://github.com/storybookjs/storybook/blob/next/addons/docs/src/frameworks/angular/compodoc.ts#L71-L73

**Comment by tommyc38** [comment]
Too was wondering about this.  I think it was be particularly helpful for documenting Angular services within Storybook.

**Comment by Steven-Harris** [comment]
#11016
