### ISSUE TITLE
Controls: exception for Angular stories

### ISSUE THREAD

**Issue by matheo** [storybookjs/storybook#10956]
**Describe the bug**

Trying out `"@storybook/addon-controls": "6.0.0-beta.16"` I got this exception:

![image](https://user-images.githubusercontent.com/260185/83085200-e0f1eb00-a050-11ea-81b4-098f30ed5322.png)

the Story with the Compodoc argTypes looks like this:

![image](https://user-images.githubusercontent.com/260185/83085332-4514af00-a051-11ea-8e6a-d6edc58f48ce.png)

**System:**

```
Environment Info:

  System:
    OS: Linux 5.4 Ubuntu 20.04 LTS (Focal Fossa)
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 10.18.0 - ~/.nvm/versions/node/v10.18.0/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.14.2 - ~/.nvm/versions/node/v10.18.0/bin/npm
  Browsers:
    Chrome: 83.0.4103.61
    Firefox: 76.0.1
  npmPackages:
    @storybook/addon-a11y: 6.0.0-beta.16 => 6.0.0-beta.16 
    @storybook/addon-actions: 6.0.0-beta.16 => 6.0.0-beta.16 
    @storybook/addon-controls: 6.0.0-beta.16 => 6.0.0-beta.16 
    @storybook/addon-docs: 6.0.0-beta.16 => 6.0.0-beta.16 
    @storybook/addon-links: 6.0.0-beta.16 => 6.0.0-beta.16 
    @storybook/addon-viewport: 6.0.0-beta.16 => 6.0.0-beta.16 
    @storybook/addons: 6.0.0-beta.16 => 6.0.0-beta.16 
    @storybook/angular: 6.0.0-beta.16 => 6.0.0-beta.16 
    @storybook/cli: 6.0.0-beta.16 => 6.0.0-beta.16 
    @storybook/source-loader: 6.0.0-beta.16 => 6.0.0-beta.16
```

**Comment by matheo** [comment]
@shilman I wonder if something is missing to make it work, or if we need an adapter on `@storybook/angular` to process the `argTypes` and complete it.

**Comment by shilman** [comment]
Thanks @matheo. I've seen this and will look into it now as part of #10946

**Comment by shilman** [comment]
¡Ay Caramba!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-beta.17 containing PR #10946 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
