### ISSUE TITLE
Shoryshot-puppeteer --allow-file-access-from-files flag

### ISSUE THREAD

**Issue by Bruno-Tavares-Bose** [storybookjs/storybook#10962]
**Describe the bug**
Trying to run `Storyshots` (image snapshots) with a `file://...` in a project with SVG (for example) is not possible.

**To Reproduce**
1. Having a project with SVG assets to be used in `href` (in icons for instance)
2. Setup `jest` and `storyshots`/`storyshots-puppeteer` to run visual regression tests
3. Having you `storybookUrl` point to your static storybook (`file:///${path.resolve(__dirname, 'path/to/storybook-static')`)
4. Check your images_snapshots "icons" components

**Expected behavior**
Those images should have our SVGs.

**Code snippets**
```javascript
initStoryshots({
	test: imageSnapshot({
		storybookUrl: `file:///${path.resolve(__dirname, 'storybook-static')}`
	}),
...
```

**System:**
```
Environment Info:

  System:
    OS: macOS 10.15.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.22.0 - ~/.nvm/versions/node/v12.16.1/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
  Browsers:
    Chrome: 83.0.4103.61
    Safari: 13.1
  npmPackages:
    @storybook/addon-a11y: 6.0.0-beta.17 => 6.0.0-beta.17 
    @storybook/addon-actions: 6.0.0-beta.17 => 6.0.0-beta.17 
    @storybook/addon-docs: 6.0.0-beta.17 => 6.0.0-beta.17 
    @storybook/addon-storyshots: 6.0.0-beta.17 => 6.0.0-beta.17 
    @storybook/addon-storyshots-puppeteer: 6.0.0-beta.17 => 6.0.0-beta.17 
    @storybook/addons: 6.0.0-beta.17 => 6.0.0-beta.17 
    @storybook/react: 6.0.0-beta.17 => 6.0.0-beta.17 
    @storybook/theming: 6.0.0-beta.17 => 6.0.0-beta.17 
    @storybook/vue: 6.0.0-beta.17 => 6.0.0-beta.17
```

**Additional context**
Changing this [line](https://github.com/storybookjs/storybook/blob/master/addons/storyshots/storyshots-puppeteer/src/puppeteerTest.ts#L81) to have `--allow-file-access-from-files` flag, fix the issue.
Therefore, we may want to have this `args` to be set up (like we have `executablePath` already) or having a specific flag to add this flag (I would not recommend adding it by default since it is a dangerous one...)

**Comment by Claudia-Sardinha-Bose** [comment]
There are other situations (e.g. [storybook-dark-mode](https://github.com/hipstersmoothie/storybook-dark-mode) that changes the iframe body class from the outside of the iframe) that requires adding other flags to puppeteer (`--disable-web-security`, `--disable-site-isolation-trials`).

**Comment by Bruno-Tavares-Bose** [comment]
Any news on this one?
