### ISSUE TITLE
Deprecate `storyName=X` URL scheme

### ISSUE THREAD

**Issue by tmeasday** [storybookjs/storybook#10960]
- Remove legacy URL support
 - Move `setSelection` to earlier in startup cycle
 - Get rid of `RENDER_CURRENT_STORY` event and use `SET_SELECTION/SET_STORIES` events instead.

**Comment by tmeasday** [comment]
This was implemented in #11111 - @shilman should we close this issue?

**Comment by shilman** [comment]
@tmeasday If you reference the issue in first line of the PR that fixes it, it will get closed as soon as I do a release.

**Comment by shilman** [comment]
Jeepers creepers!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-beta.33 containing PR #11111 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
