### ISSUE TITLE
Addon a11y latest version returning TypeError: {}

### ISSUE THREAD

**Issue by christinec01** [storybookjs/storybook#10968]
If you are reporting a bug or requesting support, start here:
### Bug or support request summary
Expected: @storybook/addon-a11y to display accessibility data in a story

What actually happened: Getting the following error:
![image](https://user-images.githubusercontent.com/16041595/83177725-73879e00-a0d4-11ea-902b-f94aad03a0c4.png)
 

### Steps to reproduce
Using @storybook version 5.3.14
@storybook/addon-a11y version 6.0.0-beta.16

My project's main.js file adds `@storybook/addon-a11y` to addons

My preview.js file looks like this:

![image](https://user-images.githubusercontent.com/16041595/83178103-f14ba980-a0d4-11ea-9921-81f7155ec0ed.png)

_(A screencast can be useful for visual bugs, but it is not a substitute for a textual description.)_
Console output: 
![image](https://user-images.githubusercontent.com/16041595/83178995-358b7980-a0d6-11ea-9b92-92273cce55c2.png)

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react 5.3.14
- @storybook/addon-a11y 6.0.0-beta.16
### Affected platforms 
Tried on macOS Chrome and Safari (same issue on both)

**Comment by tooppaaa** [comment]
@christinec01 We refactored a bit addon-a11y in 6.0. If you also upgrade @storybook/react to the same version of a11y, it should resolve your issue.

**Comment by christinec01** [comment]
@tooppaaa - that did the trick, thanks!
