### ISSUE TITLE
Update @storybook/preact to support Preact 10

### ISSUE THREAD

**Issue by fjorgemota** [storybookjs/storybook#10973]
**Is your feature request related to a problem? Please describe.**
Preact 10 is already a few months old, but, at least according to `@storybook/preact`'s `peerDependencies`, it's not supported by Storybook yet. However, that module seems to work fine with latest Preact 10...

**Describe the solution you'd like**
Check if Preact 10 definitely works fine with `@storybook/preact` and update peerDependencies to reflect that. 

**Are you able to assist bring the feature to reality?**
Assuming that the test suite already covers `@storybook/preact` successfully, I think I can try to update the peerDependencies requirement and verify if everything still works fine.

**Additional questions**
Do we will still support Preact 8? Or just support Preact 10 from now on? Again, according to my experience, Preact 10 works just fine with Storybook..and according to what I saw Storybook doesn't use too much from Preact too, so I think that this compatibility could be preserved for more time without problems.

**Comment by shilman** [comment]
@fjorgemota would you mind submitting a PR with that one-line change?

**Comment by fjorgemota** [comment]
Closed by #10978.

**Comment by shilman** [comment]
Huzzah!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-beta.21 containing PR #10978 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

**Comment by fjorgemota** [comment]
Nice! Thanks!
