### ISSUE TITLE
@storybook/addon-docs Rendered code format is wrong

### ISSUE THREAD

**Issue by elowes** [storybookjs/storybook#10975]
**Describe the bug**
If use arrow function in JSX, the rendered code format is not perfect.

**Expected behavior**
Hope the rendered code format is perfect

**Screenshots**
![image](https://user-images.githubusercontent.com/8766034/83211772-8c558980-a190-11ea-9585-244e858a35e7.png)

**System:**
Environment Info:

  System:
    OS: macOS 10.15.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 12.16.2 - ~/.nvm/versions/node/v12.16.2/bin/node
    Yarn: 1.22.4 - ~/WorkCodes/utils/packages/components/node_modules/.bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.16.2/bin/npm
  Browsers:
    Chrome: 83.0.4103.61
    Safari: 13.1
  npmPackages:
    @storybook/addon-actions: next => 6.0.0-beta.17 
    @storybook/addon-docs: next => 6.0.0-beta.17 
    @storybook/addon-info: next => 6.0.0-alpha.2 
    @storybook/addon-links: next => 6.0.0-beta.17 
    @storybook/react: next => 6.0.0-beta.17

**Comment by shilman** [comment]
closing as dupe to #8078
