### ISSUE TITLE
Snowpack

### ISSUE THREAD

**Issue by phaistonian** [storybookjs/storybook#10987]
[Snowpack](https://www.snowpack.dev/posts/2020-05-26-snowpack-2-0-release/) makes development both fun and instant.

It'd be great If, somehow, it'd work with Storybook - by optionally _replacing_ webpack.

A quick look at the Snowpack docs indicates that it's rather doable.

**Comment by o-alexandrov** [comment]
it makes sense to keep this open as the opportunity to get rid of bundling from the process, resulting in extremely quick iterations, would be awesome to be built into storybook

**Comment by desireco** [comment]
I am willing to poke around if someone who is knowledgable wants to pair. It would be huge if we could figure out how to make this work. I have sizable storybook instance.

**Comment by techieshark** [comment]
@desireco I'm curious - how long does storybook take to start up on your (sizeable) storybook instance? Mine is not large but is taking over two minutes which is why I'd love to see snowpack used.

**Comment by desireco** [comment]
@techieshark 10-15 mins.

**Comment by shilman** [comment]
that's nuts guys. can you share more about your respective projects? chromatic's storybook has 1500 stories including entire pages and takes 40 seconds to build.

**Comment by phaistonian** [comment]
@desireco it all comes down to the webpack config you use. 

If you invest time to tweak it, you can get quite decent build times.

**Comment by fcamblor** [comment]
Hi there !

FYI I achieved to integrate storybook in a snowpack-based project using a "statically generated" storybook 5.3 based on [openwc's prebuilt-storybook](https://github.com/open-wc/open-wc/tree/master/packages/demoing-storybook).

Fork of this prebuilt-storybook is here : https://github.com/fcamblor/fcr-storybook-prebuilt-wrapper (I had to tweak some stuff here and there (most important one being the possibility to have [absolute imports](https://github.com/fcamblor/fcr-storybook-prebuilt-wrapper/commit/ce44443f2a6d7130d5e8b9c8cb80bd7a55daf44e) in the wrapper, backed by this PR https://github.com/open-wc/open-wc/pull/1694 which didn't get enough traction)

Snowpack + storybook demo available in this starter : https://github.com/fcamblor/lit-element-typescript-sass-constructible-stylesheet-storybook-starter
(_I decided to keep my project and storybook completely separated, storybook being into a dedicated folder so that its dependencies don't transpire into the main project_)

Downside of this is are :
- this works only with a specific version of storybook (in my case, 5.3) and if we want to follow new versions of storybook, you have to adapt prebuilt storybook to fit changes occured on the new versions (didn't tried to adapt against storybook 6 yet)
- addons are kind of "hardcoded" in the prebuilt version.. it is not complicated to add some, but here again you have to update prebuilt version of storybook to take it into consideration

Hope this can help and I would obviously be interested into completely replacing webpack with snowpack ... this would remove the prebuilt-storybook dependency and would make things definitely more maintainable on the long term :-)

**Comment by shilman** [comment]
@fcamblor this is awesome, thanks so much for sharing! 💯

we're fans of `prebuilt-storybook` and will be looking at ways of incorporating some of those improvements into storybook 6.x to make this all integrate better and not be tied to a specific storybook version.

**Comment by techieshark** [comment]
@shilman my repo isn't open but if it helps I can add you as a contributor so you could test it. It may just be my computer - on a good day it's 33-45 seconds.

**Comment by FredKSchott** [comment]
Hey everyone, maintainer of Snowpack here! 👋 

@ndelangen and I chatted about this a while ago, so I know he's excited about the ESM story for Storybook as well. I'd love to help out however I can on a Snowpack + Storybook integration. Feel free to reach out with any questions or thoughts.

**Comment by ndelangen** [comment]
@fcamblor @desireco

I'd love to talk to you about a path going forwards having snowpack as an options in storybook.

schedule a meeting with me?
https://calendly.com/ndelangen/storybook

**Comment by desireco** [comment]
@ndelangen I really appreciate the offer. I am currently swamped with work, but I will see to find time for this.

**Comment by paralin** [comment]
I'm interested in a Snowpack plugin which brings in Storybook to a project.

**Comment by zachintosh** [comment]
Yesssssss.

**Comment by ndelangen** [comment]
Offer is open to anyone interested in working on this!

**Comment by MIreland** [comment]
@ndelangen - Could you give a brief overview of the scope of work involved?

**Comment by ndelangen** [comment]
@MIreland I've never used snowpack before, but we're very interested in the option of switching from webpack to snowpack, to ship modern ESM to the browsers that support it.

**Comment by o-alexandrov** [comment]
I have tried adding `snowpack` only for development bundling, while keeping `webpack`.
And started to have seen issues, fixed some, but then I realized:
- I am introducing a second bundler, when:
  - initial bundling with `webpack 4` at that time was about 20 seconds on my laptop
  - HMR took from 0.5s to 1s

When talking about bundling, it's not only JavaScript, but also: HTML, Favicons, PWA-specific scripts, sometimes bundled JS app is a hybrid app (adding more complexity to the bundling), sometimes CSS & pre-processors, etc., so for me it's obvious now:
- we cannot rely on Snowpack (being a relatively new solution) to handle all such cases in production reliably at this time
  - even if we can, adding webpack on top of snowpack, it adds complexity and potential unpredictability with upgrades
  - there could be bundler-specific issues
  - if you are still not convinced about reliability, look at the changelog of webpack and realize, for example: how many different module concatenation scenarios there are for different types of output
- webpack's HMR is not drastically different from snowpack, so it's not really noticeable
- more maintenance time expense: additional deps to familiarize with and support integration of

With introduction of `webpack 5`, our initial bundling dropped from 20s to 13s, and HMR takes up to 0.5s now.
- then, there is [built-in now](https://github.com/webpack/changelog-v5/blob/master/guides/persistent-caching.md) hard disk caching which makes initial bundling to happen almost in up to a couple of seconds

And finally:
- the author of webpack mentioned [ESM is their current priority](https://github.com/webpack/webpack/issues/2933#issuecomment-715903657), most probably not right when the feature is available, but a bit later we would probably see a switch for "no bundling for JavaScript" in development.

So let me please withdraw my interest from the [first comment](https://github.com/storybookjs/storybook/issues/10987#issuecomment-647045016) on this topic above. I believe sticking to a single bundling process is the way to go. On a side note, also removing rollup when creating libraries once webpack supports ESM output to decrease maintenance complexity.

**Comment by chrislambe** [comment]
@o-alexandrov to clarify something you mentioned: Snowpack is a developer build tool, not a bundler. Snowpack does not produce production builds/bundles. It does have a plugin architecture for integrated bundlers like Webpack:
https://www.snowpack.dev/#bundle-for-production

Your point about about Webpack pushing for ESM builds is interesting, though. I'm curious if it will result in similarly low (re)build times.

**Comment by MIreland** [comment]
My understanding is that Snowpack uses [esbuild](https://esbuild.github.io/) under the hood, which is likely to have substantial performance improvements even for unbundled states (I would think?):

![image](https://user-images.githubusercontent.com/1170700/97653365-9d037780-1a2e-11eb-832d-283da1ab2f7c.png)

**Comment by shilman** [comment]
Related: We released https://github.com/storybookjs/storybook/pull/12707 yesterday which means that the "manager" UI only builds when it changes. This comes with a better UI and also frees up CPU for building the user's "preview" bundle. Should help with webpack, snowpack, or whatever we end up with on the user's side.

Try it out today in 6.1-alpha:

```
npx sb@next upgrade --prerelease
```

**Comment by schickling** [comment]
Now that 6.1 has been out for a while, is there any progress update on this for the upcoming 6.2?

**Comment by shilman** [comment]
@schickling we have a rough design for supporting both webpack4 and webpack5 side by side, feedback welcome:

https://docs.google.com/document/d/18EPCmRfbInPRotC7wtrPtr_533BGJaZK7JsJ9K3OnOQ/edit?usp=sharing

this may go out in 6.2 but not sure yet. once we get this going, adding another package for snowpack should also be possible.

**Comment by skidding** [comment]
If anyone's curious, [this is how React Cosmos integrates with Snowpack](https://github.com/react-cosmos/react-cosmos/blob/main/docs/snowpack.md). Not trying to promote Cosmos on a Storybook thread, just wanted to share how we do it. Storybook and Cosmos are similar in many respects so you might be able to get some inspiration.

The Cosmos integration is pretty verbose and requires some manual wiring, compared to using webpack. Essentially, you have to manually add a Snowpack route for the preview iframe (we call it the renderer), which loads an auto-generated map of all the user's fixtures (you call them stories), and point the main UI to load the new Snowpack route as the iframe URL. Not ideal, but I think it's a good starting point for people who are eager to use Snowpack, like myself.

Happy to share more from my (limited) Snowpack experience to anyone who is looking to replicate something similar on the Storybook side. I'm also curious to hear ideas for simplifying this integration by making use of Snowpack's JS API, so I'll be following this thread to see what solution you come up with.

**Comment by ndelangen** [comment]
@skidding I'd love to learn more, would you have the time to do a knowledge sharing zoom meeting some day?
https://calendly.com/ndelangen/storybook

or reach out to me on our discord:
https://discord.gg/js3AjMg6dW

**Comment by skidding** [comment]
> @skidding I'd love to learn more, would you have the time to do a knowledge sharing zoom meeting some day?
> https://calendly.com/ndelangen/storybook
> 
> or reach out to me on our discord:
> https://discord.gg/js3AjMg6dW

Happy to help. Just sent you a DM.

**Comment by bard** [comment]
I have a create-react-app project where I use Snowpack in dev and WebPack 4 for the prod build.

Storybook was taking 6+ seconds to refresh simple components; I brought it down to around 3s by disabling DocgenPlugin, ESLintWebpackPlugin, and ForkTsCheckerWebpackPlugin, and further to around 2s by enabling the [turbo build](https://github.com/pocka/storybook-addon-turbo-build) plugin with `optimizationLevel: 3` . At some point I tried the Webpack 5 builder, but it made no significant difference and I didn't record the time.

Unfortunately, at 2s per refresh I still find it unusable for interactive development. Maybe I've been spoiled by Snowpack, but anything >1s quickly drives me up a wall.

In the end, I added a new `/canvas` route to the application, only available in development, where I develop stories interactively with the benefit of Snowpack's fast feedback. Stories are then fully reusable in Storybook. The idea is simple:

```ts
import * as Button from './Button.stories'

export const Canvas: React.FC = () => {
  const Story = Button.Basic
  return (
    <div>
      <Story {...Story.args} />
    </div>
  )
}
```

```ts
// ...
  <Router>
    <Switch>
      <Route ... />
      <Route ... />
      {process.env.NODE_ENV === 'development' && (
        <Route path="/canvas" component={Canvas} exact={true} />
      )}
    </Switch>
  </Router>
// ...
```

(In reality, I'm importing several `*.stories.tsx` files, and building a two-level menu to switch stories like the one in Storybook, but the above is the essence of it.)

Kudos to the forward-thinking people who came up with CSF, this is only possible because of that.

The downsides of this strategy are 1) when you change component args in story files, the changes aren't picked up and you need a full page reload (perhaps related to https://github.com/snowpackjs/snowpack/discussions/2010); and 2) if you use decorators, you need to write some more support code.

---

My `.storybook/main.js`:

```js
const { inspect } = require('util')

module.exports = {
  stories: [
    '../src/**/*.stories.@(js|jsx|ts|tsx)',
  ],
  addons: [
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    '@storybook/preset-create-react-app',
    ['storybook-addon-turbo-build', { optimizationLevel: 3 }],
  ],

  webpackFinal: async (config, { configType }) => {
    config.plugins = config.plugins.filter(
      (p) =>
        !inspect(p).match(
          /^(DocgenPlugin|ESLintWebpackPlugin|ForkTsCheckerWebpackPlugin)/,
        ),
    )

    return config
  },
}
```

**Comment by sebastienbarre** [comment]
@bard I think I could deal with 2 seconds. Could you give us more details about "disabling DocgenPlugin, ESLintWebpackPlugin, and ForkTsCheckerWebpackPlugin, and further to around 2s by enabling the turbo build plugin with optimizationLevel: 3" ? Thanks

**Comment by bard** [comment]
@sebastienbarre the `.storybook/main.js` above, plus `npm i storybook-addon-turbo-build`, should be enough. Lower the optimization level if things break.

**Comment by justgook** [comment]
Doesn't this #14545 (didn't check yet) opens ability to use storybook with snowpack?

**Comment by shilman** [comment]
#14545 means that if somebody wrote an experimental snowpack builder, users would be able to try it out without having to fork storybook. AFAIK nobody's written that builder yet. (but if anybody's interested, I'd be happy to guide!)

**Comment by justgook** [comment]
I'm kind of have idea for that, tryout, check what it spits out, and see what it needs.. and if at all it is possible to build snowpack into storybook or storybook into snowpack.

**Comment by justgook** [comment]
Main point of snowpack - that it acts just as middleware for each file - so it results just 1:1 if imports.. only way that I can imagine how it can work with storybook and custom bundler - is just provide full files that is required, and give snowpack ability to build/serve it.. but for that storybook should become something like Storybook prebuilt - that acts just like bare framework that can be included as part of application, or just proxy all file requests to different HTTP server.. (just personal opinion, still would like investigate that question, and maybe get some help / feedback)

**Comment by shilman** [comment]
@justgook vite is also doing browser-native ESM for the dev server and there is a WIP vite builder here: https://github.com/eirslett/storybook-builder-vite

**Comment by ndelangen** [comment]
@justgook I'd love to pair on this together with you.

If you have the time and interest of course!
I know the ins and outs of storybook, the webpack builder.

If you'd like to schedule a meeting to talk about this:
https://calendly.com/ndelangen/storybook

**Comment by o-alexandrov** [comment]
Vite's builder from eirslett has an open HMR issue on the Storybook's side.
Reproducible with the [example in this repo](https://github.com/eirslett/storybook-builder-vite/tree/main/packages/example-react).
- HMR works for Vite-managed parts (actual components used in stories), but doesn't work for Storybook-managed parts (thru Webpack)
  - [related issue ](https://github.com/eirslett/storybook-builder-vite/issues/3)

Ideally, 3rd party builders replace Webpack completely; that's how I believe most of us would think `@storybook/*/standalone` should work.
- also would be great, if those, who are using the standalone version or 3rd party bundlers/builders, won't need to download the dependencies related to the default bundling (webpack 4, etc.)

**Comment by Manubi** [comment]
Any news on this one? 😄

**Comment by aryaniyaps** [comment]
small bump on this. I would really like to see smaller wait times! 😄

**Comment by siva-sundar** [comment]
Curious to know if there are any updates 😀

**Comment by shilman** [comment]
@fabb check out storybook's vite builder, which is also much faster https://storybook.js.org/blog/storybook-for-vite/

**Comment by siva-sundar** [comment]
@shilman Vite builder for storybook works but it has some issues like frequent pre-bundling dependencies. https://github.com/eirslett/storybook-builder-vite/issues/75

**Comment by IanVS** [comment]
Snowpack is no longer maintained, so I don't think Storybook will create a builder for it.  If you're tied to Snowpack and want to create your own Storybook builder, hit me up and I can walk you through how the vite builder works as a bit of an example.
