### ISSUE TITLE
Addon-docs: Disable story scroll

### ISSUE THREAD

**Issue by Sqrrl** [storybookjs/storybook#10983]
**Is your feature request related to a problem? Please describe.**
I'm using custom mdx doc pages where the first story doesn't have to be at the top of the docs page. When opening the docs the page scrolls to the first story somewhere on the page, which is confusing.

**Describe the solution you'd like**
It would be nice if the auto scroll could be disabled.

**To Reproduce**
1. Add a story preview with the first story to the bottom of a MDX doc page. (see example below)
2. Open docs page -> Page scroll down till story is in viewport.

**Code snippets**
```
import {
  Preview,
  Story
} from '@storybook/addon-docs/blocks';

# Button

Longer text …

<Preview>
  <Story id="components-button--default" />
</Preview>
```

**Comment by shilman** [comment]
@Sqrrl do you want it to jump to the story without an animated scroll, or just stay at the top of the page?

**Comment by shilman** [comment]
I think this is a workaround: https://github.com/storybookjs/storybook/issues/10598#issuecomment-622294085

**Comment by Sqrrl** [comment]
Stay at the top. The anchor trick works, thanks.

**Comment by SimonFinney** [comment]
For anyone still running into this and looking for a global workaround - 

```jsx
// preview.js
import { Anchor, DocsContainer } from '@storybook/addon-docs/blocks';

export const parameters = {
  docs: {
    container: ({ children, context }) => (
      <DocsContainer context={context}>
        <Anchor storyId={new URLSearchParams(window.location.search).get('id')} />
          {children}
      </DocsContainer>
    ),
  },
};
```

**Comment by DesselBane** [comment]
Is there a way to disable the behavior maybe via a parameter? In vue or at least my project the anchor trick doesnt work. (v6.1.9)

**Comment by shilman** [comment]
@patricklafrance didn't you look into this very recently?

**Comment by patricklafrance** [comment]
@shilman yes and no.

While developing my custom preview I noticed that I wasn’t rendering the Story component.

A side effect of this was that the story Anchor wasn’t rendered which means that I couldn’t scroll to a specific story.

Short story, someone could add a parameter to the addon-docs Story block to prevent rendering the story Anchor and it should disable the initial scrolling. However it would also disable navigating to the story from the sidebar nav. 

There should be a better way to do this.

**Comment by DesselBane** [comment]
Maybe to clarify why I need this: I use storybook mainly in the `--docs` mode. So I don't click on a specific story but always the entire component. So for the `--docs` mode it would be great if the scrollBehavior would be "scrollToTop".

**Comment by ricovitch** [comment]
> For anyone still running into this and looking for a global workaround -
> 
> ```js
> // preview.js
> import { Anchor, DocsContainer } from '@storybook/addon-docs/blocks';
> import React from 'react';
> 
> export const parameters = {
>   docs: {
>     container: ({ children, context }) => (
>       <DocsContainer>
>         <Anchor storyId={context.id)} />
>         {children}
>       </DocsContainer>
>     ),
>   },
> };
> ```

Seems we need to use the `page` option instead of `container` with latests storybook versions (6.2.0 as of today) for this workaround to work.

**Comment by renatamottam** [comment]
Lost a couple hours trying to fix this and I found out a simple fix [here](https://github.com/storybookjs/storybook/issues/8914).

Just add a `Meta` at the beginning of your MDX file with the `anchor` on the end 🥳 

`<Meta title='some/component' anchor />`

**Comment by s0ber** [comment]
To anyone who's interested in the problem — use `DocsStory` instead of the `Story` for your stories and scrolling will work as intended. You can also implement your custom story wrapper, but take `DocsStory` as an example, so correct anchoring will be retained.

**Comment by xunfeng911** [comment]
> To anyone who's interested in the problem — use `DocsStory` instead of the `Story` for your stories and scrolling will work as intended. You can also implement your custom story wrapper, but take `DocsStory` as an example, so correct anchoring will be retained.

That's cool，I've tried many ways, but you're the only one that works.
`
<DocsStory id="some--id />
`
