### ISSUE TITLE
Prop table row customisation 

### ISSUE THREAD

**Issue by sami616** [storybookjs/storybook#10993]
The below link 👇🏼 details how to customise, or 'override' the `defaultValue` or `description` fields in the prop tables, but doesn't explain how to do this for the actual *type* that is output in the row.

Is this possible? Would be fantastic as an escape hatch for complex components where `react-docgen` might not be able to properly detect the correct type to output and avoid `any` being displayed.
 
https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/props-tables.md#rows-customization

**Comment by shilman** [comment]
Will do 👍

**Comment by shilman** [comment]
Yowza!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-beta.20 containing PR #11001 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Look at the source of DocsPage. It’s passing a different prop to `Props`. Probably needs more documentation or maybe we need to update the defaultProps of `Props`? I didn’t do that because it’s a breaking change. Then again this is a breaking release... WDYT?

**Comment by sami616** [comment]
Ah yes, i see what you mean. I have passed `story='^'` as a prop to `<Props/>` and is now working as expected. I expected the overriding of the props to just work across controls *and* prop tables so perhaps it might be worth updating `Props.defaultProps.story` to `PRIMARY_STORY` ?

**Comment by sami616** [comment]
At closer inspection, passing `story='^'` to Props seems to break the subcomponents tabs

**Comment by shilman** [comment]
@sami616 yeah there's an open issue for the subcomponents thing #10958
