### ISSUE TITLE
Can't resolve assets file path in SCSS file

### ISSUE THREAD

**Issue by stegano** [storybookjs/storybook#10990]
**Describe the bug**
When importing a file using `@import`, it seems that there is a problem with the image path of the imported file.  The relative path of the file in SCSS should be based on the imported target file, but it doesn't seems to be. (Please see code snippet)

**Expected behavior**
- Must search the file path based on the `mixins` folder path

**Code snippets**
> .storybook/main.js
```js
const path = require('path');
module.exports = {
  stories: ['../src/**/*.stories.tsx'],
  addons: ['@storybook/addon-actions', '@storybook/addon-links'],
  webpack: async config => {
 ...
    config.module.rules.push(
      {
        test: /\.scss$/,
        use: ['style-loader', 'css-loader', 'sass-loader'],
        include: path.resolve(__dirname, '../'),
      },
    );
...
    return config;
  },
};
```

> src/index.scss
```scss
@import "~src/shared/_mixins";
@include test;
```

> src/shared/_mixin.scss
```scss
@mixin test {
  background: url("./images/img.svg"); // << not works, but moving image directory to 'src' work fine.
}
```

> directory
```bash
.storybook/
src/
 - index.tsx
 - index.scss
 - shared/
    -_mixin.scss
    - images/
      - img.svg
```

**Output:**
ERROR in ./src/index.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./src/index.scss)
Module not found: Error: Can't resolve './images/test.svg' in '/Users/test/src/index'

**System:**
```
  System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i5-2500S CPU @ 2.70GHz
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    npm: 6.12.0 - ~/.nvm/versions/node/v10.15.3/bin/npm
  Browsers:
    Chrome: 83.0.4103.61
    Firefox: 72.0.2
    Safari: 13.1.1
  npmPackages:
    @storybook/addon-actions: ^5.3.19 => 5.3.19 
    @storybook/addon-links: ^5.3.19 => 5.3.19 
    @storybook/addons: ^5.3.19 => 5.3.19 
    @storybook/preset-scss: ^1.0.2 => 1.0.2 
    @storybook/react: ^5.3.19 => 5.3.19 
  npmGlobalPackages:
    @storybook/cli: 5.0.11
    @storybook/react: 5.0.11
```

**Comment by stegano** [comment]
I've resolved this issue by referring to the content below.
-https://github.com/webpack-contrib/sass-loader#problems-with-url

**Comment by phong10119** [comment]
@stegano I added ```resolve-url-loader``` but couldn't solve the problem, would you mind taking a look?

```
    newConfig.module.rules.push({
      test: /\.module\.(s*)css$/,
      use: [
        'style-loader',
        {
          loader: 'css-loader',
          options: {
            importLoaders: 1,
            modules: true
          }
        },
        'resolve-url-loader',
        {
          loader: 'sass-loader',
          options: {
            sourceMap: true
          }
        }
      ]
    })
```

**Comment by stegano** [comment]
Hi @phong10119,
Could you attach your error message that is output?

The settings I've tried are below. 
it worked
```ts
...
{
    test: /\.scss$/,
    use: [
      'style-loader',
      {
        loader: 'css-loader',
        options: {
          modules: {
            auto: true,
            localIdentName: "[local]--[hash:base64:5]",
          },
        },
      },
      'resolve-url-loader',
      'sass-loader'
    ]
  },
...
```

**Comment by phong10119** [comment]
Thank you @stegano, I had to make the import in global.module.scss relative. It works now!

**Comment by lethanhtupk** [comment]
Hi, @stegano  I'm facing the error exactly the same as you. My config in main.js as below 
``` 
...
config.module.rules.push({
      test: /\.s[ac]ss$/i,
      use: ['style-loader', 'css-loader', 'resolve-url-loader', 'sass-loader'],
      include: path.resolve(__dirname, '../'),
})
```
The error output is 

> Error: Can't resolve '/images/icons/triangle-right.svg' in '/home/tult/RikkeiSoft/pms-frontend/styles/components/elements'

**Comment by stegano** [comment]
> Hi, @stegano I'm facing the error exactly the same as you. My config in main.js as below
> 
> ```
> ...
> config.module.rules.push({
>       test: /\.s[ac]ss$/i,
>       use: ['style-loader', 'css-loader', 'resolve-url-loader', 'sass-loader'],
>       include: path.resolve(__dirname, '../'),
> })
> ```
> 
> The error output is
> 
> > Error: Can't resolve '/images/icons/triangle-right.svg' in '/home/tult/RikkeiSoft/pms-frontend/styles/components/elements'

Hi, @lethanhtupk 
Could you attach your (s)css file and module path?

**Comment by phong10119** [comment]
> Hi, @stegano I'm facing the error exactly the same as you. My config in main.js as below
> 
> ```
> ...
> config.module.rules.push({
>       test: /\.s[ac]ss$/i,
>       use: ['style-loader', 'css-loader', 'resolve-url-loader', 'sass-loader'],
>       include: path.resolve(__dirname, '../'),
> })
> ```
> 
> The error output is
> 
> > Error: Can't resolve '/images/icons/triangle-right.svg' in '/home/tult/RikkeiSoft/pms-frontend/styles/components/elements'

Seems like you missing this? It's in resolve-url-loader doc

<img width="912" alt="Screen Shot 2021-01-05 at 10 30 01" src="https://user-images.githubusercontent.com/54445063/103603405-1f357e00-4f41-11eb-9a87-2c77fd07d39b.png">

**Comment by stegano** [comment]
@lethanhtupk 
I just checked the output of the added error message and it seems that the image path is not a relative path. Try changing the image path to start with `.`

**Comment by lethanhtupk** [comment]
@phong10119  @stegano  thanks for the response 
I've tried to put ```sourceMap``` option but got the same result 
On my scss file. I use ```background-image``` with ```url('/images/icons/triangle-right.svg')```

directory 
```directory 
public/ 
  - images/  
      - icons
          .svg files in here
styles/
  - components/ 
      - elements/ 
         - scss files in here
```

I found that if I changed the path in scss file into ```../../../public/images/icon/triangle-right.svg```, then bookstory work fine. So I think I need to use ```resolve-url-loader``` to change the url into relative path as above but don't know how to do that yet

**Comment by stegano** [comment]
@lethanhtupk 
If you want to use absolute path, try using alias feature in webpack.
but, this setting must be applied to both the storybook and the project webpack.

**Comment by lethanhtupk** [comment]
@stegano 
I don't want to re-config project webpack. Have any solution to use ```resolve-url-loader``` to modify the url in scss file to correct it before it being build by storybook?

**Comment by stegano** [comment]
@lethanhtupk Unfortunately, the simplest way I know of is to set an alias for the webpack. 😥

**Comment by ajeetshah** [comment]
You can use [`resolve-url-loader`](https://github.com/bholloway/resolve-url-loader) to fix the [problem-with-url](https://github.com/webpack-contrib/sass-loader#problems-with-url) in one of the following ways:

1. If you are using *inline loaders* (e.g. in `.storybook/preview.js` file):
```js
import '!style-loader!css-loader!resolve-url-loader!sass-loader!../src/styles/my-global-file.scss'
```
or

2. If you want to specify the loaders by [extending the storybook's webpack config](https://storybook.js.org/docs/react/configure/webpack#extending-storybooks-webpack-config) (in `.storybook/main.js`):
```js
const path = require('path');
module.exports = {
  webpackFinal: async (config, { configType }) => {
    config.module.rules.push({
      test: /\.scss$/,
      use: ['style-loader', 'css-loader', 'resolve-url-loader', 'sass-loader'],
      include: path.resolve(__dirname, '../'),
    });
    return config;
  },
};

```

**Comment by Bruno-Daldegan** [comment]
Hello ... which versions of "style-loader, css-loader, resolve-url-loader, sass-loader" worked for you?

**Comment by ajeetshah** [comment]
@Bruno-Daldegan 

I had solved this (assets file path) issue by using [**method-1**](https://github.com/storybookjs/storybook/issues/10990#issuecomment-778658549) i.e. `import '!style-loader!css-loader!resolve-url-loader!sass-loader!../src/styles/my-global-file.scss'` in **version 5** of storybook.

After a few months, I upgraded storybook to **V6** and found that I no longer needed to use _method-1_ and I could just write `import '../src/styles/my-global-file.scss'` in `preview.js` file (and it would let me resolve assets file paths). 

To answer your question, I had `style-loader "^1.0.0"`, `css-loader "^3.0.0"`, `resolve-url-loader "^3.1.2"` and `sass-loader "^10.0.5"`, in my `yarn.lock` file, when I was using V5 of storybook. Now, I would simply recommend you to try the latest V6 of Storybook.

PS: I used storybook in a React project built with CRA.

**Comment by PFight** [comment]
Found next solution (for css, not scss):

       for (let rule of config.module.rules) {
		if (rule.use && rule.use.length > 0) {
			for (let use of rule.use) {
			  if (use.loader && use.loader.includes("css-loader")) {
				use.options.url = false;
			  }
			}
		}
	   }

**Comment by jackhkmatthews** [comment]
Thanks @PFight , this resolved my url path issues:
```js
// .storybook/main.js
module.exports = {
  addons: [
    "@storybook/preset-scss",
  ],
  framework: "@storybook/react",
  staticDirs: ["../public"],
  webpackFinal: async (config, { configType }) => {
    for (let rule of config.module.rules) {
      if (rule.use && rule.use.length > 0) {
        for (let use of rule.use) {
          console.log(use.loader);
          if (use.loader && use.loader.includes("/css-loader/")) {
            use.options = {
              url: false,
            };
          }
        }
      }
    }
    return config;
  },
};
```
My erroring SCSS file:
```
@font-face {
  font-display: optional;
  font-family: "Arial Narrow";
  font-style: normal;
  font-weight: 400;
  src: url("/ArialNarrow.woff2") format("woff2"); // font file is in /public/
}
```

**Comment by algomachine007** [comment]
> Hi @phong10119, Could you attach your error message that is output?
> 
> The settings I've tried are below. it worked
> 
> ```ts
> ...
> {
>     test: /\.scss$/,
>     use: [
>       'style-loader',
>       {
>         loader: 'css-loader',
>         options: {
>           modules: {
>             auto: true,
>             localIdentName: "[local]--[hash:base64:5]",
>           },
>         },
>       },
>       'resolve-url-loader',
>       'sass-loader'
>     ]
>   },
> ...
> ```

Hey Stengato, is there a way of using absolute import for asset file in scss?

// absolute imports
$assetPath: "@/assets/vector.png"; (what i want)

// relative imports
$assetPath: "../../../assets";   (wrong)

Your input would be highly appreciated

**Comment by stegano** [comment]
> > Hi @phong10119, Could you attach your error message that is output?
> > The settings I've tried are below. it worked
> > ```ts
> > ...
> > {
> >     test: /\.scss$/,
> >     use: [
> >       'style-loader',
> >       {
> >         loader: 'css-loader',
> >         options: {
> >           modules: {
> >             auto: true,
> >             localIdentName: "[local]--[hash:base64:5]",
> >           },
> >         },
> >       },
> >       'resolve-url-loader',
> >       'sass-loader'
> >     ]
> >   },
> > ...
> > ```
> 
> Hey Stengato, is there a way of using absolute import for asset file in scss?
> 
> // absolute imports $assetPath: "@/assets/vector.png"; (what i want)
> 
> // relative imports $assetPath: "../../../assets"; (wrong)
> 
> Your input would be highly appreciated

Hi @algomachine007 
Try using the webpack `resolve.alias` settings.
https://webpack.js.org/configuration/resolve/

**Comment by algomachine007** [comment]
Hey, here are pics, its a next js app and i don't think the app is aware of the webpack config file
<img width="899" alt="Screen Shot 2022-03-03 at 8 40 49 AM" src="https://user-images.githubusercontent.com/95980716/156519091-ef599ea8-9ad1-4fa7-aa48-de73bbfa188e.png">
<img width="899" alt="Screen Shot 2022-03-03 at 8 41 18 AM" src="https://user-images.githubusercontent.com/95980716/156519104-c3e950d1-ccf5-46bd-948b-0096f560e7f2.png">
<img width="899" alt="Screen Shot 2022-03-03 at 8 41 27 AM" src="https://user-images.githubusercontent.com/95980716/156519111-c265094b-9eaa-4226-aaa6-b6cf7f172cd3.png">

**Comment by stegano** [comment]
@algomachine007 Can you show me the next.config.js file you are using?

**Comment by algomachine007** [comment]
Yeah, sure

<img width="555" alt="Screen Shot 2022-03-03 at 9 11 07 AM" src="https://user-images.githubusercontent.com/95980716/156523550-9f14ea69-4855-4ef0-8a5a-5b43d09236fc.png">

**Comment by stegano** [comment]
🤔
Can you try this?
```ts
module.exports = () => {
  return {
    webpack: (config, { buildId }) => {
      config.resolve = { alias: images: path.resolve(...) };
      return config;
    }
  }
}
```

**Comment by stegano** [comment]
> Yeah, sure
> 
> <img alt="Screen Shot 2022-03-03 at 9 11 07 AM" width="555" src="https://user-images.githubusercontent.com/95980716/156523550-9f14ea69-4855-4ef0-8a5a-5b43d09236fc.png">


🤔 
Can you try this?
```ts
module.exports = () => {
  return {
    webpack: (config, { buildId }) => {
      config.resolve = { alias: images: path.resolve(...) };
      return config;
    }
  }
}
```

**Comment by algomachine007** [comment]
Hey, i've used it but i'm now getting an internal server error
<img width="831" alt="Screen Shot 2022-03-03 at 9 58 33 AM" src="https://user-images.githubusercontent.com/95980716/156531601-f785b4f9-05a8-4c4d-88f0-ea9bde49eedf.png">


<img width="831" alt="Screen Shot 2022-03-03 at 10 00 51 AM" src="https://user-images.githubusercontent.com/95980716/156531611-de836dac-932f-418e-aebd-56bbcf694185.png">
Thanks for your help and patience

**Comment by stegano** [comment]
> Hey, i've used it but i'm now getting an internal server error <img alt="Screen Shot 2022-03-03 at 9 58 33 AM" width="831" src="https://user-images.githubusercontent.com/95980716/156531601-f785b4f9-05a8-4c4d-88f0-ea9bde49eedf.png">
> 
> <img alt="Screen Shot 2022-03-03 at 10 00 51 AM" width="831" src="https://user-images.githubusercontent.com/95980716/156531611-de836dac-932f-418e-aebd-56bbcf694185.png">
> 
> Thanks for your help and patience

😓  
can you like to try again?

```ts
// In existing your settings..
module.exports = {
    tailringSlash:true,
    webpackDevMiddleware: (config) => {
        ...
        config.resolve.alias = {
            images: path.resolve(...)
        }
    }
    ...
}
```

and

```scss
// your (s)css file
background: url('~image/bg.png') // <- use `~` ahead file path
```

**Comment by algomachine007** [comment]
// next.config.js
const path = require("path");

module.exports = {
  webpack(config, options) {
    config.resolve.alias["images"] = path.join(__dirname, "./src/assets");
    return config;
  },
};

Hey, finally figured it out, wouldn't have been possible without your help, thanks man
