### ISSUE TITLE
Args contains the Window object for prop that has 'top' set as a default value.

### ISSUE THREAD

**Issue by sami616** [storybookjs/storybook#11027]
Example: 👇🏼

```typescript
export interface ComponentProps {
  /** The vertical alignment to use */
  vAlign?: 'top' | 'middle' | 'bottom'
}

const MyComponent = ({vAlign = 'top'}) => {
  //...
} 
```

When this is used in a story, storybook always passes vAlign the `Window` object, if i change the default value of `vAlign` to something else, ie - `middle` i get the correct value passed into my story.

**Comment by shilman** [comment]
Do you have a repro repo available?!

**Comment by henrywoody** [comment]
Have this same issue too.

Storybook version: `6.0.26`
Using typescript with create-react-library

**Example**:

```react
type ComponentProps = {
    direction?: "top" | "right" | "bottom" | "left";
}

function Component({direction = "top"}: ComponentProps) {
    return <div>{direction}</div>
}
```
