### ISSUE TITLE
addon-docs + typescript does not pick up default props

### ISSUE THREAD

**Issue by youfoundron** [storybookjs/storybook#11026]
**Describe the bug**
Default props are not picked up by the `@storybook/addon-docs` addon when using typescript.

**To Reproduce**
1. Install latest storybook and addon-docs modules.
2. Setup a functional component with a default prop and a story for the component.
3. Run storybook and navigate to the props table in docs.
4. Note the Default column is empty for the property with a default value specified.

**Expected behavior**
Expect *Default* column to be populated based on React functional component definition per page 7 of the [args RFC](https://docs.google.com/document/d/1Mhp1UFRCKCsN8pjlfPdz8ZdisgjNXeMXpXvGoALjxYM/)

**Screenshots**
<img width="1552" alt="Screen Shot 2020-06-03 at 12 42 56 AM" src="https://user-images.githubusercontent.com/4658359/83609738-87e3f480-a533-11ea-997b-3bb2254ecccb.png">

**Code snippets**
```typescript
/* button.tsx */
import React from 'react'
import cn from 'classnames'

export interface Props {
  label?: string;
  bgColor: string;
  textColor: string;
}

export const Button: React.FC<Props> = ({
  label = 'Submit',
  bgColor,
  textColor,
  ...rest
}) => {
  return (
    <button
      className={cn(
        `text-${textColor}`,
        `bg-${bgColor}-500`,
        `hover:bg-${bgColor}-700`,
      )}
      {...rest}
    >
      {label}
    </button>
  );
};
```

```typescript
/* button.stories.tsx */

import React from 'react'
import { actions } from '@storybook/addon-actions'
import { Button, Props as ButtonProps } from './base'

export default {
  title: 'Button',
  component: Button
}

export const basic = (_args: ButtonProps) => {
  const { label, bgColor, textColor, ...rest } = _args
  return (
    <Button
      label={label}
      bgColor={bgColor}
      textColor={textColor}
      {...rest}
    />
  )
}
basic.args = {
  label: 'Hello World',
  bgColor: 'blue',
  textColor: 'white',
  ...actions('onClick', 'onMouseOver')
};
```

**System:**
```
Environment Info:

  System:
    OS: macOS 10.15.5
    CPU: (4) x64 Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz
  Binaries:
    Node: 14.3.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
  Browsers:
    Safari: 13.1.1
  npmPackages:
    @storybook/addon-actions: 6.0.0-beta.20 => 6.0.0-beta.20
    @storybook/addon-controls: 6.0.0-beta.20 => 6.0.0-beta.20
    @storybook/addon-docs: 6.0.0-beta.20 => 6.0.0-beta.20
    @storybook/addon-links: 6.0.0-beta.20 => 6.0.0-beta.20
    @storybook/react: 6.0.0-beta.20 => 6.0.0-beta.20
```

**Comment by danielgamage** [comment]
I've been having trouble with this setup, too. You might get some mileage out of the following changes which I keep having to make to my components:


```diff
  export interface Props {
+   /** annotation */
    label?: string;
+   /** annotation */
    bgColor: string;
+   /** annotation */
    textColor: string;
  }

- export const Button: React.FC<Props> = ({
+ export const Button = ({ 
    label = 'Submit',
    bgColor,
    textColor,
    ...rest
- }) => {
+ }: Props) => {
```

**Comment by shilman** [comment]
cc @hipstersmoothie is there anything we can do about this on the `react-docgen-typescript` side?

**Comment by hipstersmoothie** [comment]
I think this might have been fixed already. react-docgen-typescript supports this and has tests to show it. I think this should have been fixed with https://github.com/storybookjs/storybook/pull/11184 which went out in beta 31

**Comment by shilman** [comment]
You rock @hipstersmoothie. @youfoundron can you try upgrading?

**Comment by dgreene1** [comment]
> @youfoundron can you try upgrading?

I think he wants you to try the newest storybook beta/alpha

**Comment by shilman** [comment]
`npx sb@next upgrade --prerelease`
