### ISSUE TITLE
Add webpack instance to "webpackFinal" function

### ISSUE THREAD

**Issue by rodrigofariow** [storybookjs/storybook#11030]
**Is your feature request related to a problem? Please describe.**
I'm using a different webpack version from storybook in my app.
This may cause issues when I want to use a certain webpack core plugin (e.g `webpack.DefinePlugin`) in storybook config since I risk not using the same version of that same plugin as storybook's.

**Describe the solution you'd like**
Adding `webpack` to `webpackFinal` function (**not a final api**):
```Typescript
webpackFinal: async (config, {webpack, ...otherOptions} ) => {
    config.plugins.push(webpack.DefinePlugin(/* reuse some variables here */)
}
```
If my current webpack version had a breaking change in `DefinePlugin` I could now adapt my usage of it and still reuse variables that were defined in my other webpack configs.

**Describe alternatives you've considered**
I could check which webpack version my current storybook version uses and install _the exact same webpack version/compatible webpack version_ on my behalf to assure the same behavior but I would be dependent on storybook, which is sub optimal.

**Are you able to assist bring the feature to reality?**
I have never contributed to this project but I could get informed and try to implement the feature if needed :)

I appreciate the time and hope I could be clear enough.

Cheers!

**Comment by shilman** [comment]
cc @ndelangen @igor-dv

**Comment by ndelangen** [comment]
Here's an alternative solution:

Much like we did with `@storybook/theming`, we can make a `@storybook/build` package that exports all things webpack we use.

You can then import webpack like so:

```
import { DefinePlugin } from '@storybook/build';
```

and ensure it's the version we use.

WDYT?

Would be be interested in working on this? I can help you get started for sure!

**Comment by rodrigofariow** [comment]
Hi @ndelangen!

It sounds great! And I would surely be interested on helping anyway I can.
I have already taken a look at CONTRIBUTING.md and have configured the repo locally.
What should be my next steps?

Cheers :)

**Comment by ndelangen** [comment]
@rodrigofariow I think what we should do is -if you can- meet in a zoom meeting, where I can help you set up. We'd be:

- creating a new package (`@storybook/builder`?)
- add a bunch of webpack related dependencies to it
- write some code exporting all of those dependencies's exports
- change all the current packages using webpack, to use the newly created package.

You can create a meeting in my calendar here:
https://calendly.com/ndelangen/storybook
