### ISSUE TITLE
Controls: Guard against incorrect `args` annotation

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#11032]
We've seen two instances of the following in the code already:

```js
export const Basic = (args) => <Icon {...args} />;
Icon.args = { icon: 'watch' }; // should be Basic.args
```

This can cause insidious bugs that are hard to track down, especially if `Icon` happens to be another story, so it's a "long-distance mutation"

Options:
- [ ] Static analysis (e.g. in `source-loader`) that detects this pattern and raises a warning.
- [ ] eslint rules  that detects this pattern and raises a warning.
- [ ] Some kind of dynamic wrapper for stories that ensures type safety and adds a `setter` that throws an error after initialization
- [ ] ???

**Comment by tmeasday** [comment]
My feeling is we should make one ore more eslint rules and optionally also check those rules (and warn) in static analysis.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if this is still relevant in SB 7.x.
