### ISSUE TITLE
storyStore is undefined

### ISSUE THREAD

**Issue by GiraffeCoding** [storybookjs/storybook#11031]
Hi,
When I'm trying to view the js/mdx docs in my Html based storybook I'm getting the following error.

`TypeError: storyStore is undefined2 Story.js:71
    getStoryProps Story.js:71
    StoryContainer Story.js:118
    React 15
    renderMain start.js:361
    renderUI start.js:429
    emit index.js:180
    setSelection story_store.js:357`

**System:**
`"devDependencies": {
    "@babel/core": "^7.10.2",
    "@storybook/html": "^5.3.18",
    "babel-loader": "^8.1.0"
  },
  "dependencies": {
    "@material-ui/core": "^4.10.1",
    "@storybook/addon-a11y": "^5.3.18",
    "@storybook/addon-actions": "^5.3.18",
    "@storybook/addon-backgrounds": "^5.3.18",
    "@storybook/addon-docs": "^5.3.18",
    "@storybook/addon-events": "^5.3.18",
    "@storybook/addon-jest": "^5.3.18",
    "@storybook/addon-knobs": "^5.3.18",
    "@storybook/addon-links": "^5.3.18",
    "@storybook/addon-storyshots": "^5.3.18",
    "@storybook/addon-storysource": "^5.3.18",
    "@storybook/addon-viewport": "^5.3.18",
    "@storybook/addons": "^5.3.18",
    "@storybook/client-api": "^5.3.18",
    "@storybook/core": "^5.3.18",
    "@storybook/core-events": "^5.3.18",
    "@storybook/source-loader": "^5.3.18"
  }`

I have followed the example shown in the HTML-kitchen-Sink but even those are showing the same error.

**Comment by shilman** [comment]
Do you have a public repro repo?

**Comment by iskilber** [comment]
Hi @GiraffeCoding 

I faced the same issue today in @nrwl monorepo with storybook at version 6.0.2 for React. It helped me to configure `preview.js` file as described here at: https://www.npmjs.com/package/@storybook/addon-docs
