### ISSUE TITLE
Is context deprecated?

### ISSUE THREAD

**Issue by kruthivijay31** [storybookjs/storybook#11033]
**Describe the Issue**

I see `context` in the [master](https://github.com/storybookjs/storybook/tree/master/addons/contexts) branch but I don't it in the [next](https://github.com/storybookjs/storybook/tree/next/addons/contexts) branch (returns 404). 
[toolbars](https://github.com/storybookjs/storybook/tree/next/addons/toolbars) is the successor of context. Please can anyone confirm `context` is deprecated and the toolbar is the replacement I checked the deprecation docs section but I didn't see context (https://github.com/storybookjs/storybook#deprecated-addons)

**Additional context**
If the context is deprecated, I can create a PR to add it to the deprecation section of docs.

**Comment by shilman** [comment]
Yes it is: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-addon-contexts

PR would be wonderful 🙏

**Comment by kruthivijay31** [comment]
@shilman here is the PR https://github.com/storybookjs/storybook/pull/11034. Please review and let me know if any changes required. Thanks!
