### ISSUE TITLE
Regression in babel transpilation

### ISSUE THREAD

**Issue by bard** [storybookjs/storybook#11045]
**Describe the bug**

The following transpiled fine in 5.x:

```ts
export class ClassWithTranspilationIssues {
  constructor(private configuration: any = { foo: 'bar' }) { }

  printConfigParameter(): void {
    console.log(this.configuration.foo);
  }
}
```

It no longer transpiles correctly with Storybook 6:

```ts
new ClassWithTranspilationIssues().printConfigParameter() // => Unexpected error: TypeError: Cannot read property 'foo' of undefined
```

**To Reproduce**

Minimal repro: https://github.com/bard/storybook-6-babel-regression
Commit: https://github.com/bard/storybook-6-babel-regression/commit/eb6cb309bfd6f6de62bbb5216d4f817d19a5741b

**Expected behavior**

Constructor parameters with default values should be transpiled correctly.

**System:**

```
Environment Info:

  System:
    OS: Linux 5.6 Arch Linux
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
  Binaries:
    Node: 12.17.0 - /tmp/yarn--1591296461799-0.8326352750887624/node
    Yarn: 1.22.4 - /tmp/yarn--1591296461799-0.8326352750887624/yarn
    npm: 6.14.5 - /usr/sbin/npm
  Browsers:
    Firefox: 76.0.1
  npmPackages:
    @storybook/addon-actions: ^6.0.0-beta.21 => 6.0.0-beta.21 
    @storybook/addon-links: ^6.0.0-beta.21 => 6.0.0-beta.21 
    @storybook/addons: ^6.0.0-beta.21 => 6.0.0-beta.21 
    @storybook/cli: ^6.0.0-beta.21 => 6.0.0-beta.21 
    @storybook/preset-create-react-app: ^3.0.0 => 3.0.0 
    @storybook/react: ^6.0.0-beta.21 => 6.0.0-beta.21 
```

**Additional context**

The issue is related to the order in which babel plugins run. I fixed this locally in `storybook/lib/core/src/server/common/babel.js`:

```diff
  export const plugins = [
+   require.resolve('@babel/plugin-transform-typescript'),
    require.resolve('@babel/plugin-transform-shorthand-properties'),
    require.resolve('@babel/plugin-transform-block-scoping'),
```

The clue was in https://github.com/babel/babel/pull/8682#issuecomment-420408858

**Comment by shilman** [comment]
cc @mrmckeb

**Comment by matheo** [comment]
@bard do you have that code in a `.tsx?` file inside your Storybook Config or is it loaded by your Stories?

**Comment by mrmckeb** [comment]
I found the issue here, it looks like a change in behaviour. I'll try to get a fix in ASAP.

**Comment by shilman** [comment]
Released https://github.com/storybookjs/presets/pull/147 as `@storybook/preset-create-app@3.0.1`. Please upgrade today!
