### ISSUE TITLE
[addon-a11y] make colorblindness filter feature optional

### ISSUE THREAD

**Issue by rheydt** [storybookjs/storybook#11059]
**Is your feature request related to a problem? Please describe.**
The a11y addon is great! However, we already have a colorblindness simulator we are using, and don't need the one that comes with the a11y addon. Is there a way to disable it?

**Describe the solution you'd like**
Make the colorblindness filter dropdown an optional feature (defaulted on). Or, if this is already possible, improve the docs to show how to do this.

**Describe alternatives you've considered**
Considering hiding the dropdown via some hacky CSS, but hope I don't need to go that route.

**Are you able to assist bring the feature to reality?**
maybe?

**Comment by tooppaaa** [comment]
@rheydt do you mind sharing what's the differences between the one shipped by the addon and yours ?
