### ISSUE TITLE
[addon-docs] Feature request - Add letter spacing as a configurable value on the Typeset block 

### ISSUE THREAD

**Issue by mmellado** [storybookjs/storybook#11050]
**Is your feature request related to a problem? Please describe.**
We are using addon-docs to create part of our styleguide. Some of the typography definitions we have also include different kernings. However, the Typeset block does not support this. I can create a pull request for this but I want to first validate that this is an acceptable feature to add to the addon.

**Describe the solution you'd like**
Add a new prop `letterSpacing` to the Typeset component which applies the necessary kerning.

**Describe alternatives you've considered**
I haven't tried any alternatives other than not using the Typeset component and build my own to display the Typographies of my projects

**Are you able to assist bring the feature to reality?**
yes, I can create a PR if this is approved

**Additional context**
I may have a slightly wrong understanding of the intention of the Typeset component, but I think right now it is very limitting. While my type definitions do share a font family, they each have a different font size, line height, font-weight and letter spacing. Would it make sense to have an option where an array of typeset settings is passed, instead of just an array of font sizes? I'm happy to help implement as well.

**Comment by shilman** [comment]
closing as dupe to https://github.com/storybookjs/storybook/issues/10560
