### ISSUE TITLE
Add control column to props table

### ISSUE THREAD

**Issue by hmajid2301** [storybookjs/storybook#11067]
I was looking at this [Design System Website](https://5ccbc373887ca40020446347-frgogtvejg.chromatic.com/?path=/docs/design-system-progressdots--basic). I noticed that the prop tables have a control column, where the user can adjust the props and the components changes as well. 

I found the [source code here](https://github.com/storybookjs/design-system). But I don't understand how they've managed to do this. Can anyone explain what I need to do **add the control column** to my storybook components. I looked into `addon-knobs` but I don't think this quite does the same thing. 

Currently I am able to get a prop tables to load using the `addon-docs` in a simple mdx file shown below.

```mdx
import { Meta, Story, Preview, Props } from '@storybook/addon-docs/blocks';

import Logo from './Logo';

<Meta
  title="Logo"
  subtitle="The logo component"
  description="A customisable logo component."
  component={Logo}
/>

# Logo

<Props of={Logo} />
```

Any help would be greatly appreciated thanks

**Comment by matheo** [comment]
@hmajid2301 `addon-controls` is the new `addon-knobs` and you just need to setup your stories to receive `(args) => {...` to show the column with the controls.

Jus follow the [docs](https://github.com/storybookjs/storybook/tree/next/addons/controls) and you'll be ready to go!

**Comment by hmajid2301** [comment]
@matheo  If I have an `.mdx` file like so:

```mdx
## Accent

You can adjust the accent (tags) color by passing the `accent` prop.

<Preview>
  <Story name="Accent Colour">
    <div>
      <Logo accent="gray-500" color="blue-500" text="Haseeb" />
    </div>
  </Story>
</Preview>
```

How can I pass the arg to that ?

**Comment by matheo** [comment]
@hmajid2301 woops, I haven't seen how to manipulate that kind of stories tho
it's clearer with the [MDX flavored CSF](https://storybook.js.org/docs/formats/mdx-syntax/#mdx-flavored-csf) stories

@shilman is there a way to manipulate the `args` in pure MDX Stories?

**Comment by shilman** [comment]
```
<Preview>
  <Story
    name="ArgTypes"
    args={{
      boolArg: true,
      stringArg: 'overwritten',
      arrayArg: ['a', 'b'],
    }}
  >
    {(args) => <Comp {...args} />}
  </Story>
</Preview>
```

**Comment by hmajid2301** [comment]
I can see the `control` tab in the `canvas` panel.

However I cannot get it show up in the `docs` panel in the props table. Is this because I am using the `Props` component ? 

```mdx
<Props of={Logo} />

<Preview>
  <Story
    name="Basic"
    args={{
      text: "Haseeb",
      color: 'gray-500',
    }}
  >
    {(args) => <Logo {...args} />}
  </Story>
</Preview>
```

Thanks

**Comment by shilman** [comment]
You need `<Props story=“Basic” />`

**Comment by hmajid2301** [comment]
Thank you very much thats fixed it, is this documented somewhere ?

**Comment by shilman** [comment]
@hmajid2301 https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/props-tables.md#controls
