### ISSUE TITLE
Add support for decorators for full zero configuration typescript

### ISSUE THREAD

**Issue by fernandopasik** [storybookjs/storybook#11061]
**Is your feature request related to a problem? Please describe.**
Since the objective is to provide zero configuration for typescript one feature is decorators.

**Describe the solution you'd like**
To add `@babel/plugin-proposal-decorators` to the core 
https://github.com/storybookjs/storybook/blob/next/lib/core/src/server/common/babel.js

**Describe alternatives you've considered**
Could have a project config, but since we want to provide zero config for typescript including decorators plugin seems small and reasonable.

**Are you able to assist bring the feature to reality?**
Yes, I can prepare a PR and modify 
https://github.com/storybookjs/storybook/blob/next/lib/core/src/server/common/babel.js

**Comment by fernandopasik** [comment]
Have a branch ready if this is agreed
https://github.com/storybookjs/storybook/tree/decorators-support

**Comment by shilman** [comment]
Nice @fernandopasik 👍   I don't use decorators and don't have a strong opinion on this. Is this officially part of the Typescript spec? @ndelangen @mrmckeb @tmeasday

**Comment by fernandopasik** [comment]
Yes, decorators are part of the language for a while.
https://www.typescriptlang.org/docs/handbook/decorators.html

**Comment by fernandopasik** [comment]
I've use them regulary with web-components as they are included in lit-html.
I was wondering if creating a separate `web-components-ts-kitchen-sink` or migrating the existing one to typescript

**Comment by shilman** [comment]
@fernandopasik thanks for the clarification, that's great, and let's do it! (unless somebody strongly objects).

regarding web components + typescript example: @tooppaaa and a few others are overhauling the example setup in storybook to make it much more lightweight. once that's done (hopefully in the next couple weeks?), it would be awesome if you could follow that format to add a web-components + typescript example 🙏

**Comment by fernandopasik** [comment]
Cool, is there a PR I can look for the new format of the examples?

**Comment by fernandopasik** [comment]
I've created a PR with a couple of lines to modify the babel config #11063 
I could create a second one with the new kitchen example app based on the refactor of the examples.

**Comment by shilman** [comment]
Awesome @fernandopasik 🙏

**Comment by mrmckeb** [comment]
@shilman, they are supported behind an `experimental` flag in TypeScript. Opinions aside, I think we should support them ;)

**Comment by shilman** [comment]
If it's experimental, do you think we should figure out how to make it experimental in Storybook too? For example, we could add an opt-in preset that adds both the dependency and the configuration

**Comment by fernandopasik** [comment]
For angular development are used quite often.
In the branch you mentioned about the revamp of the examples they are used also in several occasions.

https://github.com/storybookjs/storybook/pull/10913/files#diff-8b989a93ea2eb835431322332a2990a4R3

**Comment by fernandopasik** [comment]
Also, the @babel/plugin-proposal-decorators is already in yarn.lock
https://raw.githubusercontent.com/storybookjs/storybook/next/yarn.lock

**Comment by mrmckeb** [comment]
We could, like the Babel preset for TypeScript, just document that you need to add this plugin if you want to use experimental decorators?

**Comment by mrmckeb** [comment]
My only concern about adding it is that the more we have by default, the harder it is for users to override if they have a different project setup.

**Comment by fernandopasik** [comment]
What about having a prop in main.js to override the babel config, like the one for webpackFinal?

**Comment by fernandopasik** [comment]
Sorry I didn't mean as override, more like extend. It would be a waste to have to include all the good choices already made in the core babel configuration.

**Comment by mrmckeb** [comment]
Currently you can _extend_ the base config, not replace, unless you modify the final config with `webpackFinal`. I'm currently trying to solve a related issue with this for the CRA preset - in that case the new defaults are duplicated in the CRA preset.

**Comment by pumano** [comment]
Would love to see works it out of the box. I think it should be supported by default because vue has `vue-class-component` and `vue-property-decorator` also angular use decorators out of the box and Mobx.

**Comment by fernandopasik** [comment]
fixed by #11063

**Comment by shilman** [comment]
Huzzah!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-beta.24 containing PR #11063 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.
