### ISSUE TITLE
Collapse parent item (folder or component) when a story is selected

### ISSUE THREAD

**Issue by AnnyCaroline** [storybookjs/storybook#11065]
**Describe the bug**
Using storybook 6.0.0-beta.22, the error described at #5594 happening again.

**To Reproduce**
Steps to reproduce the behavior (same steps from #5594):
1. Click on a folder to reveal stories
2. Click on a story
3. Try to collapse the folder
4. See that it wont collapse

**Expected behavior** 
(same steps from #5594): "I expect to be able to collapse parent elements arbitrarily even if something nested inside them is selected."

**System:**
Please paste the results of `npx -p @storybook/cli@next sb info` here.

Environment Info:

  System:
    OS: Linux 5.3 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
  Binaries:
    Node: 12.1.0 - ~/.nvm/versions/node/v12.1.0/bin/node
    Yarn: 1.17.3 - ~/.yarn/bin/yarn
    npm: 5.1.0 - ~/dev/intelie/liverig/live-plugins/node_modules/.bin/npm
  Browsers:
    Chrome: 78.0.3904.97
    Firefox: 76.0.1
  npmPackages:
    @storybook/addon-docs: ^6.0.0-beta.22 => 6.0.0-beta.22 
    @storybook/addon-knobs: ^6.0.0-beta.22 => 6.0.0-beta.22 
    @storybook/addon-links: ^6.0.0-beta.22 => 6.0.0-beta.22 
    @storybook/addons: ^6.0.0-beta.22 => 6.0.0-beta.22 
    @storybook/react: ^6.0.0-beta.22 => 6.0.0-beta.22

**Comment by JackHowa** [comment]
I've had the same issue with @next version

**Comment by shilman** [comment]
@JackHowa unrelated issue, but please upgrade all your `@storybook/*` packages to the same version. Having a mixture of 5.3 and 6.0 packages is bound to cause problems

**Comment by AnnyCaroline** [comment]
@shilman I upgraded from 5.3. It was working fine.

However, I don't think it has anything to do with the update. I tested it now with a new installation, and the problem happens.

**To reproduce:**
1. create-react-app storybook --template=type
2. cd storybook
3. yarn add -D @storybook/react@next
4. yarn add babel-loader @babel/core -D
5. create .storybook/main with the following content:
    ```
    module.exports = {
        stories: ['../src/**/*.stories.js']
    };
    ```
6.  Add storybook script to package.json
7. Create two stories:
    - src/storie/one.stories.js:
        ```
        import React from 'react';

        export default { title: 'Test1/subfolder' };

        export const one = () => (
        <h1>
            One
        </h1>
        );
        ```
    - src/storie/two.stories.js: 
        ```
        import React from 'react';

        export default { title: 'Test2/subfolder' };

        export const two = () => (
        <h1>
            Two
        </h1>
        );

        ```

**Comment by JackHowa** [comment]
@shilman was able to replicate with using all the same version packages. thanks for the note

```
Environment Info:

  System:
    OS: macOS 10.15.5
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
  Browsers:
    Chrome: 83.0.4103.97
    Safari: 13.1.1
  npmPackages:
    @storybook/addon-a11y: ^6.0.0-beta.23 => 6.0.0-beta.23 
    @storybook/addon-backgrounds: ^6.0.0-beta.23 => 6.0.0-beta.23 
    @storybook/addons: ^6.0.0-beta.23 => 6.0.0-beta.23 
    @storybook/react: ^6.0.0-beta.23 => 6.0.0-beta.23

**Comment by JackHowa** [comment]
I can look into this tonight. Looks like it may have been a solved problem per @ndelangen's note?

**Comment by ndelangen** [comment]
Yes, it's been solved once, but a refactor caused the feature to be removed. Totally my fault.

What can I do to assist @JackHowa? 

I think the code-change would be relatively simple, and I can definitely make some time pair programming on it.
Please add a meeting in my calendar if you'd like to take me up on that offer:
https://calendly.com/ndelangen/storybook

Perhaps it would be as easy as:

```
 const { expandedSet, setExpanded } = useExpanded( 
   type, 
   [], 
   initial.filtered, 
   initial.unfiltered 
 );
```

**Comment by JackHowa** [comment]
thanks for the offer @ndelangen. Was looking at my calendar (CST-based). I may be able to later in the week. As I mentioned in the pr, I was not able to validate the fix. I tried linking and the example folder.

The tests pass with the fix so I'm not sure if that's helpful.

Really appreciate the offer. And this project is amazing!!

**Comment by JackHowa** [comment]
addressed in https://github.com/storybookjs/storybook/pull/11243

**Comment by fkurniaw** [comment]
is anyone still taking on this bug? I see the current open PR was closed 😞

**Comment by JackHowa** [comment]
@fkurniaw yeah I tried a couple times and paired on it. but couldn't satisfy some of the testcases and ensure the functionality stayed in-tact. you're welcome to take a shot at it if you want? tried to leave comments where appropriate in the branch

**Comment by shilman** [comment]
This was fixed in #12601 and released on the 6.1-alpha. Closing.

**Comment by irvingv8** [comment]
Would you consider back-porting it to 6.X ? 6.1 is alpha, and some places have a policy on installing alpha versions 😐, willing to help myself.

**Comment by shilman** [comment]
@irvingv8 we're fast tracking the 6.1 release and won't spend any time back-porting stuff to 6.0
