### ISSUE TITLE
@babel/plugin-transform-react-constant-elements produces invalid code

### ISSUE THREAD

**Issue by Pyrolistical** [storybookjs/storybook#11060]
**Describe the bug**
@babel/plugin-transform-react-constant-elements pulls up static jsx into an import statement resulting in invalid code

**To Reproduce**
https://github.com/Pyrolistical/bad-storybook-with-babel-plugin-transform-react-constant-elements
Run
```
npm install
npm run storybook
```
Error
```
ERROR in ./src/index.js 2:19
Module parse failed: Unexpected keyword 'var' (2:19)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| import React from 'react';
> import Imported, { var _ref = /*#__PURE__*/React.createElement(Container, null, /*#__PURE__*/React.createElement(Imported, null)); } from './imported';
| export default (function () {
|   return _ref;
 @ ./src/stories.js 2:0-27 7:44-53
 @ . sync ^\.\/(?:(?:|\/|(?:(?:(?!(?:|\/)\.).)*?)\/)stories\.js)$
 @ ./.storybook/generated-entry.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/generated-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=true
```

**Expected behavior**
Storybook starts without error
**System:**
```
Environment Info:

  System:
    OS: macOS 10.15.5
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  Binaries:
    Node: 12.16.3 - ~/.nodenv/versions/12.16.3/bin/node
    npm: 6.14.4 - ~/.nodenv/versions/12.16.3/bin/npm
  Browsers:
    Chrome: 83.0.4103.97
    Safari: 13.1.1
  npmPackages:
    @storybook/react: 5.3.19 => 5.3.19
```

**Additional context**
Related cases
  * https://github.com/storybookjs/storybook/issues/10250
  * https://stackoverflow.com/questions/55218379/react-styled-component-causes-build-error-in-production-but-runs-fine-in-develo
  * https://github.com/babel/babel/issues/10879

### Workaround
If you remove @babel/plugin-transform-react-constant-elements out of the storybook webpack config, it works
https://github.com/Pyrolistical/bad-storybook-with-babel-plugin-transform-react-constant-elements/blob/master/.storybook/main.js#L8-L11

**Comment by Pyrolistical** [comment]
This is a pointless optimization plugin that should not be included as part of the storybook webpack config

**Comment by shilman** [comment]
@ndelangen what's your take?

**Comment by ndelangen** [comment]
OK, we can remove it, @Pyrolistical would you be able to open a PR?

**Comment by Pyrolistical** [comment]
@ndelangen the pr is up

**Comment by shilman** [comment]
Yay!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-beta.24 containing PR #11086 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.
