### ISSUE TITLE
Addon-docs: "Unexpected default export without title" error

### ISSUE THREAD

**Issue by alzalabany** [storybookjs/storybook#11079]
## current behaviour

Addon-docs does not respect `stories` property in `.stroybook/main.js` file.

it expect all stories to have .stories.mdx extention other wise "Unexpected default export without title"  will fireup.

## expected behaviour

it should import configutration file of storybook for .storybook folder and respect its stories property.

## how to replicate problem ?

1. modify `.stroybook/main.js` to look like :

```
module.exports = {
	stories: ['../stories/*.mdx', '../stories/**/*.mdx'],
	addons: [
		'@storybook/addon-actions',
		'@storybook/addon-links',
		'@storybook/addon-storysource',
		'@storybook/addon-knobs',
		'@storybook/addon-docs',
```

2. create any file .mdx inside stories folder.  "intro.mdx" with any kind of content

```
import { Meta } from '@storybook/addon-docs/blocks';

<Meta title="Design System|Gettings started" />

# Example of problem
```

## current env:

- Storybook 5.3.19 started 

```
"dependencies": {
		"react": "^16.12.0",
		"react-dom": "^16.12.0"
},
```

**Comment by shilman** [comment]
Documented here: https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/mdx.md#mdx-file-names
