### ISSUE TITLE
Core: Log-level is wrong for channel messages and other SB internals

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#11077]
#10370 Added loglevel filtering for Storybook, but it doesn't work the way I'd expect it to (and is much less useful than it could be as a result).

Current behavior:
✅ Out of the box, it doesn't show any channel messages  
✅ When I set `logLevel` to `debug` all of those messages show up
❌ When try to filter out those messages using the browser loglevel, the internal messages are getting logged at at the `info` level

What I want:
- Setting the loglevel causes Storybook to emit events "at and above" that loglevel
- The loglevel doesn't change from older versions of storybook, e.g. internal events are still emitted at the `debug` level. That way I can easily turn them on and off in the browser and distinguish them from other "more important" events like loglevel was designed for

**Comment by ndelangen** [comment]
> When try to filter out those messages using the browser loglevel, the internal messages are getting logged at at the info level

sounds like an unexpected bug

**Comment by shilman** [comment]
Yay!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-beta.24 containing PR #11096 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
