### ISSUE TITLE
Addon-controls: missing no-args warning if argTypes are being used

### ISSUE THREAD

**Issue by AnnyCaroline** [storybookjs/storybook#11083]
**Describe the bug**
no-args warning is not being shown if argTypes are being used. For me this became a problem when I tried to define two stories in the same file: one using `args` and `argTypes`, and the other without args.

**To Reproduce**
1. Create a simple tsx story, with no args configured
2. Run `yarn storybook` and see the warning
3. Add an `argType`
4. See that warning is not being shown anymore.

**Expected behavior**
Stories not configured to handle controls should show warning even if `argTypes` is being used.

**Screenshots**
Without `argTypes`
![image](https://user-images.githubusercontent.com/17753656/84043718-08b04f80-a97d-11ea-8f97-97600cf94218.png)

With `argTypes`
![image](https://user-images.githubusercontent.com/17753656/84043859-31d0e000-a97d-11ea-8d1b-ad5a0036c44c.png)

**Code snippets**
Without `argTypes`: 
```
import React, { FC } from 'react'
import { Button } from './Button'

export default {
    title: 'Button',
    component: Button
}

export const Basic = (): FC => {
    return <Button />
}
```
With `argTypes`: 
```
import React, { FC } from 'react'
import { Button } from './Button'

export default {
    title: 'Button',
    component: Button,
    argTypes: {
        background: { control: { type: 'color' } }
    }
}

export const Basic = (): FC => {
    return <Button />
}
```

**System:**

  System:
    OS: Linux 5.3 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
  Binaries:
    Node: 12.1.0 - ~/.nvm/versions/node/v12.1.0/bin/node
    Yarn: 1.17.3 - ~/.yarn/bin/yarn
    npm: 5.1.0 - ~/dev/intelie/liverig/live-plugins/node_modules/.bin/npm
  Browsers:
    Chrome: 78.0.3904.97
    Firefox: 76.0.1
  npmPackages:
    @storybook/addon-controls: ^6.0.0-beta.22 => 6.0.0-beta.22 
    @storybook/addon-docs: ^6.0.0-beta.22 => 6.0.0-beta.22 
    @storybook/addon-links: ^6.0.0-beta.22 => 6.0.0-beta.22 
    @storybook/addons: ^6.0.0-beta.22 => 6.0.0-beta.22 
    @storybook/react: ^6.0.0-beta.22 => 6.0.0-beta.22

**Comment by shilman** [comment]
Good catch @AnnyCaroline ! 👍

**Comment by shilman** [comment]
Good golly!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-rc.9 containing PR #11598 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
