### ISSUE TITLE
Disable or replace autogenerated .env file

### ISSUE THREAD

**Issue by ozywuli** [storybookjs/storybook#11085]
**Is your feature request related to a problem? Please describe.**
We use an `.envrc` file instead of `.env` for our app. But whenever storybook runs, an extra `.env` file is generated. 

**Describe the solution you'd like**
Ideally, we have an option that disables the autogenerated `.env`.

EDIT: Turns out this .env is actually autogenerated through the ember-cli-storybook https://github.com/storybookjs/ember-cli-storybook/blob/master/index.js#L99 . Sorry about this. This can be closed.

EDIT2: you can track the issue for ember-cli-storybook here https://github.com/storybookjs/ember-cli-storybook/issues/41

**Comment by tooppaaa** [comment]
Closing per your edit ;)
