### ISSUE TITLE
dynamic preview-head.html

### ISSUE THREAD

**Issue by andre-brdoch** [storybookjs/storybook#11084]
Hi everyone 👋 Is it possible to somehow dynamically generate `preview-head.html`? Basically we want to include different resources, depending on the environment, for example:

```html
<!-- staging -->
<script src="https://stagingdomain.com/lib.js"></script>
```

```html
<!-- production-->
<script src="https://productiondomain.com/lib.js"></script>
```

The only way I found in the docs, was using the CLI option `--config-dir`. However, this would mean we need to have several dirs with mostly identical configs.

**Comment by andre-brdoch** [comment]
I just found the answer in the docs, it is actually possible to use env vars in `preview-head.html`:
https://storybook.js.org/docs/configurations/env-vars/#usage-in-custom-headbody

**Comment by andre-brdoch** [comment]
i created a PR for making this more clear in the docs: https://github.com/storybookjs/storybook/pull/11095

**Comment by donaldpipowitch** [comment]
Can this be re-opened? I actually just needed this, but with a little bit more logic involved than env variables. Something like this would be nice, so I can align `preview-head.html` a little bit more with the behaviour of our `src/index.html`:

```
<!-- my preview-head.html →
<%= require('./some-module').someExportedValueCalculatedAtBuildTime %>
```

**Comment by MaRuifeng** [comment]
Can this be re-opened? I faced a similar use case on EJS syntax support documented here https://stackoverflow.com/questions/63613348/is-it-possible-to-access-webpack-config-properties-through-the-preview-head-html.

**Comment by dutscher** [comment]
> Can this be re-opened? I actually just needed this, but with a little bit more logic involved than env variables. Something like this would be nice, so I can align `preview-head.html` a little bit more with the behaviour of our `src/index.html`:
> 
> ```
> 
> 
> <%= require('./some-module').someExportedValueCalculatedAtBuildTime %>
> ```
> 
> **Update**
> 
> For now I'll manually override the template `config.plugins[1].options.template = resolve(__dirname, 'iframe.ejs');`

i end up with this
```// template default: @storybook/core/dist/server/templates/index.ejs
  config.plugins[1].options = {
    ...config.plugins[1].options,
    template: path.resolve(__dirname, 'index.override.ejs'),
  };
```

index.override.ejs
```
<% // OVERRIDE START
    const { name } = require('../package.json');
%>
<script type="module" src="<%= name %>/<%= name %>.esm.js"></script>
<link rel="stylesheet" href="<%= name %>/<%= name %>.css" />
<%   // OVERRIDE ENDS %>
```

**Comment by donaldpipowitch** [comment]
In order to add some global styles to storybook which are the _same_ global styles I have in my app I'd actually need to generate this HTML file asynchronously 🤔  (Background: https://github.com/styleguidist/mini-html-webpack-plugin/issues/39)

**Comment by dutscher** [comment]
@donaldpipowitch look into my main.js https://github.com/dutscher/stencil-storybook/blob/master/.storybook/main.js#L26 then u can handle your override by yourself ;)

cheers

**Comment by shilman** [comment]
I believe this was fixed here https://github.com/storybookjs/storybook/pull/13432
