### ISSUE TITLE
Webstorm complaining about unused exports

### ISSUE THREAD

**Issue by dominikabieder** [storybookjs/storybook#11093]
Webstorm is complaining about `unused default` and `unused constant VariationOfStory`. 

<img width="193" alt="Screenshot 2020-06-09 at 11 58 56" src="https://user-images.githubusercontent.com/31188583/84134263-9efd7780-aa48-11ea-8af6-6f294c9ba3ca.png">

<img width="683" alt="Screenshot 2020-06-09 at 11 59 34" src="https://user-images.githubusercontent.com/31188583/84134327-b2104780-aa48-11ea-9a07-0bff993d419a.png">

This has occurred after migrating the syntax of old stories to the new one with codemod storiesof-to-csf. 

Any idea how to fix that?

**Comment by Obiwarn** [comment]
Same problem here

**Comment by shilman** [comment]
good question for webstorm community?

**Comment by landsman** [comment]
same problem here, can you please provider an eslint rule or something?

**Comment by beckettart** [comment]
Having this issue in PhpStorm currently. Really clutters my results when using the "Inspect Code" tool. An ESLint rule would be helpful.
