### ISSUE TITLE
SB Docs: Escape HTML in jsdoc comments so that it doesn't render in PropsTable

### ISSUE THREAD

**Issue by domyen** [storybookjs/storybook#11104]
**Describe the bug**
SB Docs renders the markup inside of JSDoc comments when it shouldn't. 

For this JSDoc comment: 
![image](https://user-images.githubusercontent.com/263385/84196897-ef87cb80-aa6e-11ea-9854-09c9493405c3.png)

SBDocs' PropTable renders the real markup for `<a>` and `<button>`. When it should output the string instead.
![image](https://user-images.githubusercontent.com/263385/84197011-2bbb2c00-aa6f-11ea-886d-10d36ebe6f85.png)

**To Reproduce**
1. Go to SB Design System storybook [here](https://5ccbc373887ca40020446347-frgogtvejg.chromatic.com/?path=/docs/design-system-button--basic)
2. Scroll down to `isLink`
4. See that an empty `<button>` is added to the DOM 

**Expected behavior**
SB Docs should output the string instead. When I comment `<button>` in JSDocs should render as `<button>` in SB Docs instead of laying down a real DOM element.

**Comment by shilman** [comment]
@domyen sorry i missed this. we treat JSdoc comments as markdown, so the user should escape the html manually like this:

```
[...] hrefs should use `<a>` instead of `<button>` [...]
```

**Comment by domyen** [comment]
Thanks! Will make note to add it to the new docs.
