### ISSUE TITLE
Cannot read property 'debug' of undefined when upgrading from v5.3.x to v6.0.0-beta.23 (Storybook Angular)

### ISSUE THREAD

**Issue by mattgek** [storybookjs/storybook#11116]
**Describe the bug**
When upgrading to v6.0.0-beta.23, I'm getting an error when starting Storybook.
The build indicates a successful build, but I'm having a type error `PostmsgTransport.handleEvent`

**To Reproduce**
1. Upgrade your package.json @storybook dependencies to version 6.0.0-beta.23
2. Follow the migration guide for the section related to your project setup.
3. Build storybook by running following command: `build-storybook -c .storybook -o .out`
4. Start storybook with the following command: `start-storybook -c .storybook -p 9001`
4. Open your browser

RESULT: once the first story has been loaded i'm getting the type error occur and I'm not able to switch between stories. The first story although loads without a problem. 

**Expected behavior**
Being able to switch between stories without type errors

**Screenshots**
<img width="1679" alt="Screen Shot 2020-06-10 at 16 13 56" src="https://user-images.githubusercontent.com/17617446/84278723-66879780-ab35-11ea-9eaa-16fbc05141d3.png">

**Code snippets**
main.js file
```js
module.exports = {
  stories: ['../src/stories/**/badge.stories.ts'],
  addons: [
    '@storybook/addon-actions',
    '@storybook/addon-links',
    '@storybook/addon-knobs',
    '@storybook/addon-a11y',
    '@storybook/addon-docs'
  ]
};
```

preview.ts file
```ts
import { addParameters } from '@storybook/angular';
import { themes } from '@storybook/theming';
import { setCompodocJson } from '@storybook/addon-docs/dist/frameworks/angular';
import '../src/polyfills.ts';

// @ts-ignore
// eslint-disable-next-line import/extensions, import/no-unresolved
import docJson from '../documentation.json';

setCompodocJson(docJson);

addParameters({
  options: {
    theme: themes.light
  },
  viewMode: 'docs',
  docs: {
    iframeHeight: '100vh'
  }
});
```

manager.js file
```js
import { addons } from '@storybook/addons';
import { themes } from '@storybook/theming';

addons.setConfig({
  showRoots: true,
  themes: themes.light
});

```

**System:**
Environment Info:

  System:
    OS: macOS 10.15.5
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 12.16.1 - /usr/local/bin/node
    npm: 6.13.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 83.0.4103.97
    Firefox: 74.0
  npmPackages:
    @storybook/addon-a11y: ^6.0.0-beta.23 => 6.0.0-beta.23 
    @storybook/addon-actions: ^6.0.0-beta.23 => 6.0.0-beta.23 
    @storybook/addon-docs: ^6.0.0-beta.23 => 6.0.0-beta.23 
    @storybook/addon-knobs: ^6.0.0-beta.23 => 6.0.0-beta.23 
    @storybook/addon-links: ^6.0.0-beta.23 => 6.0.0-beta.23 
    @storybook/addons: ^6.0.0-beta.23 => 6.0.0-beta.23 
    @storybook/angular: ^6.0.0-beta.23 => 6.0.0-beta.23 
    @storybook/theming: ^6.0.0-beta.23 => 6.0.0-beta.23 

**Additional context**
we are on Angular 8+ with the lib.

**Comment by shilman** [comment]
@ndelangen could this be related to the logLevel stuff?
@mattgek could you try 6.0.0-beta.20 for me? and provide a repro if that's convenient?

**Comment by ndelangen** [comment]
the name `debug` would suggest it... but I don't really see how this is possible.

I'd like to be able to debug this myself.

**Comment by shilman** [comment]
Also @ndelangen your latest log level stuff just went out today so @mattgek  maybe it’s fixed in the latest beta?

**Comment by mattgek** [comment]
@shilman I'll first test with the latest beta. If that does not work I'll create a small repo and reproduce the issue. Keep you posted. Thx for the quick responses

**Comment by mattgek** [comment]
I'm having very busy days at work. I'm hoping to provide you some additional information in my spare time. Hopefully by the end of this week (Sunday) @shilman

**Comment by RichardPK** [comment]
Hi all - did you find a solution for this? Having exactly the same problem with `6.0.21` throwing this error when changing components, or components' knobs:

`@storybook/client-logger/dist/index.js` 
`index.js:47 TypeError: Cannot read property 'debug' of undefined`

Our repo uses Storybook quite extensively, so can't provide a neat snippet. Let me know if you need any specific pieces of code though, the repo is https://github.com/bbc/psammead and our v6 migration PR is (in progress) here https://github.com/bbc/psammead/pull/3728
