### ISSUE TITLE
addon-redux not working with the new syntaxt

### ISSUE THREAD

**Issue by dominikabieder** [storybookjs/storybook#11114]
The code below is what I need for the addon-redux to be working. I have that in the preview.js but the addon doesn't seem to be working. Any idea how to make it work?

```
import addons from '@storybook/addons';
import registerRedux from 'addon-redux/register';
registerRedux(addons);
```

**Comment by shilman** [comment]
Maybe this question is better posed on the `addon-redux` repo?
