### ISSUE TITLE
Storybook background make grid size customizable

### ISSUE THREAD

**Issue by T04435** [storybookjs/storybook#11128]
I have added `"@storybook/addon-backgrounds": "^5.3.19",` and see that it has the option to toggle a grid:

![image](https://user-images.githubusercontent.com/10654469/84386067-062b4f80-ac34-11ea-8d59-6757023c3512.png)

I see that the grid is generated by the linked file and the size is set to 20 on the linked line.

https://github.com/storybookjs/storybook/blob/62cd26251eb2c85d24dadb83c7f9be100b336cea/addons/backgrounds/src/containers/GridSelector.tsx#L17

Is there a way to change the `cellSize` value?

I see there is another plugin (theming) that has a similar option, but don't want to add an extra plugin for the same feature.

https://github.com/storybookjs/storybook/blob/62cd26251eb2c85d24dadb83c7f9be100b336cea/examples/cra-kitchen-sink/.storybook/manager.js#L12

**Comment by Dangoo** [comment]
Hey @T04435,

I traced down `GRID_PARAM_KEY` to being resolved to `"grid"` which can be specified in `preview.ts` like so:

```javascript
export const parameters = {
  grid: {
    cellSize: 5
  }
}
```

Cheers!

**Comment by shilman** [comment]
@yannbf can you add to the docs?

**Comment by shilman** [comment]
@Dangoo Grid is not an addon tho..

**Comment by Dangoo** [comment]
@shilman my bad, was misguided - even though it would be valuable feature to turn of either the of them.

**Comment by yannbf** [comment]
Hey @Dangoo that is pretty valuable feedback, thanks for that! I'm currently making changes in the addon and will make sure that it's well documented as well as it allows you to disable the grid separately from backgrounds. If you have some feedback or ideas, feel free to share!

**Comment by Dangoo** [comment]
Hey @yannbf thanks for taking this on!

Regarding the grid here are some additional customization ideas:

- customizable grid line lightness/opacity to make it more subtle
  - Could be implemented passing the parameter as alpha value [here](https://github.com/storybookjs/storybook/blob/next/addons/backgrounds/src/containers/GridSelector.tsx#L40-L43), default `0.5`
- customizable grid sub cell amount (currently 5 sub cells, there are use cases when you may want e.g. 4 or 10)
  - Could be implemented passing the parameter [here](https://github.com/storybookjs/storybook/blob/next/addons/backgrounds/src/containers/GridSelector.tsx#L32-L33), default `5`
- Adjustable grid origin offset (e.g. to match story iframe padding)
  - Could be implemented by [here](https://github.com/storybookjs/storybook/blob/next/addons/backgrounds/src/containers/GridSelector.tsx#L37) using `calc(-1 px + <offsetX>) calc(-1px + <offsetY>)`, default `0`

Regarding your comment [here](https://github.com/storybookjs/storybook/issues/12147#issuecomment-677859331) about creating a theme selector, do you see any chance the background selector could be "remote controlled" based on a selected theme (light background for light theme, dark background for dark theme)?

**Comment by shilman** [comment]
Huzzah!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.0-alpha.16 containing PR #12368 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.
