### ISSUE TITLE
Docs: All the github doc links in the npm @storybook/addon-docs package page don't work

### ISSUE THREAD

**Issue by ChamsBouzaiene** [storybookjs/storybook#11127]
**Describe the bug**
All the github doc links in the npm @storybook/addon-docs package page don't work when you open the page you get Page Not Found

**To Reproduce**
1. Go to [@storybook/addon-docs](https://github.com/storybookjs/storybook/blob/master/addons/docs/docs/docspage.md)
2. Click on any refrence link for the docs like mdx refrence
3. get Page Not Found on github

**Expected behavior**
the docs should work from the npm package page

**Comment by shilman** [comment]
That's a bug in NPM. All of the links are relative links that are correct and fine in Github and NPM knows that the project is hosted on Github.

**Comment by shilman** [comment]
Have a workaround for this on our side that I'm going to try to hook up this weekend!

**Comment by jonniebigodes** [comment]
We are closing this as it's no longer an issue. Thanks for reaching out and putting this on our radar.
