### ISSUE TITLE
Addon Actions should have 'new actions' indicator on the addons toolbar tab

### ISSUE THREAD

**Issue by stefan-toubia** [storybookjs/storybook#11124]
The actions addon is not very useful unless you're on the addons action toolbar tab, there's nothing to notify you when actions are being logged. It would be a great improvement if there was some type of visual indication for when actions are being logged while you are on a different addon tab.

Something like this, but not ugly.
![image](https://user-images.githubusercontent.com/4265922/84344986-03abf580-ab61-11ea-8266-7fcf0b8f2b72.png)

To me the most important feature would be having any type of visual indication, so whatever is simplest will probably be best. I prefer not to use `alerts` but currently some teammates are preferring it for the sake of having active feedback.

Another option, though much more involved, would be to mimic chrome devtools behavior for the actions output. In devtools, there is a dedicated console tab. But when you are in any of the other tabs such as Elements, Network etc, hitting the `esc` key open the console drawer. It would be interesting if the addons panel had a console drawer of it's own, and addons could log structured output to it, and a keyboard shortcut could toggle it.

**Comment by Mahyar1982** [comment]
Hello @shilman 
Could I give it a try?

**Comment by yannbf** [comment]
Hey @Mahyar1982, contributions are always welcome!
If you're feeling adventurous, this is how something similar was done in [addon controls](https://github.com/storybookjs/storybook/commit/ceb6583450ce09ec2d7cbee3ed186c6dc15cb0e2#diff-1e98f7c643836d1bde48cda4085f1090R11).

**Comment by andre-brdoch** [comment]
@Mahyar1982 are you still interested in making a PR? Otherwise I would like to give it a shot in the next days 😃 

Were you guys imagining an "unread messages" counter (only displaying new action amount), or a counter always displaying the total amount of actions?

**Comment by Mahyar1982** [comment]
@andre-brdoch No. Please go on.

**Comment by yannbf** [comment]
> @Mahyar1982 are you still interested in making a PR? Otherwise I would like to give it a shot in the next days 😃
> 
> Were you guys imagining an "unread messages" counter (only displaying new action amount), or a counter always displaying the total amount of actions?

I assume it's good to keep consistency with the UI that's already in controls, however controls has a fixed number and actions is dynamic.. thus would be nice to have a way to indicate when a new action is logged so that it can catch the user's  attention.

@domyen have you got any ideas? 😄

**Comment by marthaerm** [comment]
Hi! @yannbf I would like to give this issue a try :)

**Comment by yannbf** [comment]
Awesome @marthaerm! Let us know if you need assistance. 🙏

**Comment by andre-brdoch** [comment]
that would be great, i don't think i will find time soon to look into it 😅 sorry!

**Comment by apapadopoulou** [comment]
Hello! Is anyone working on this?

**Comment by shilman** [comment]
@apapadopoulou it's wide open! I believe @yannbf took a crack at it but had some problems getting it working, so you might want to check with him if you're thinking about tackling it. Thanks!!! 🙏

**Comment by apapadopoulou** [comment]
@shilman Thank you! I would like to take a look at it, so I will check with @yannbf in order to catch up.

**Comment by yannbf** [comment]
Hey @apapadopoulou hit me up on discord if you'd like! Yann#9096

**Comment by domyen** [comment]
Nice! Here's an example of the `BadgeCount` UI we're moving towards for counters:  
![image](https://user-images.githubusercontent.com/263385/114032406-46eef780-984a-11eb-848a-1c9ae5ffa25a.png)

We don't have a component for this in Storybook yet. The Figma spec https://www.figma.com/file/woQ3HfwrxO84lXKvv7Gq2O/BadgeCount?node-id=0%3A1

**Comment by apapadopoulou** [comment]
Hello! I have looked into it a bit and I am currently working on the solution. Could you assign me to this issue?

**Comment by shilman** [comment]
Fantastic! 🎉 Excited to see this happen!!!

**Comment by shilman** [comment]
Good golly!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.3.0-alpha.17 containing PR #14728 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
