### ISSUE TITLE
the react-textarea-autosize@8.0.1 of @storybook/components@6.0.0-beta.22 are not found

### ISSUE THREAD

**Issue by mengfei0053** [storybookjs/storybook#11123]
### the react-textarea-autosize@8.0.1 of @storybook/components@6.0.0-beta.22 are not found

if i use npm install , it will be will be interrupted。
if i use yarn , it will let me choose the version of react-textarea-autosize && react-textarea-autosize has no version 8.0.1

**Comment by shilman** [comment]
not seeing this error, can you try clearing your caches?

**Comment by mengfei0053** [comment]
@shilman ， thx && sorry, I've tried the cache clearly, it's working. It could be my own problem.
