### ISSUE TITLE
If there is no "Enter" in the front of <Meta> in the .mdx file will cause the error.

### ISSUE THREAD

**Issue by woaiwodib107** [storybookjs/storybook#11122]
If there is no "Enter" in the front of <Meta> in the .mdx file, it will cause the error :"Unexpected default export without title: {"includeStories":[],"parameters":{"docs":{}}}"

There is no "Enter" in the front of <Meta> in the .mdx file
![image](https://user-images.githubusercontent.com/14672095/84337770-00e6ea00-abcd-11ea-8218-82ae37b421db.png)
There will be the error.
![image](https://user-images.githubusercontent.com/14672095/84337954-75ba2400-abcd-11ea-86cb-2b2bd6382339.png)

There is "Enter" in the front of <Meta> in the .mdx file
It is work.
![image](https://user-images.githubusercontent.com/14672095/84337828-24aa3000-abcd-11ea-9f01-d31b2d5efea1.png)

**Comment by shilman** [comment]
Whitespace matters in MDX. Hopefully this gets fixed in MDX 2.0. Closing this as dupe to https://github.com/storybookjs/storybook/issues/7902
