### ISSUE TITLE
Storybook in other languages

### ISSUE THREAD

**Issue by Shuunen** [storybookjs/storybook#11130]
Hi there,

I found a lot of plugins to switch locale inside stories, but I was not able to find any configuration or plugin to display Storybook itself in other lang than the English default.

![image](https://user-images.githubusercontent.com/439158/84391918-e8d98f80-abf9-11ea-8963-ccd5f904fc2e.png)
![image](https://user-images.githubusercontent.com/439158/84392359-8fbe2b80-abfa-11ea-97dd-d20a15d4ec70.png)

Am I missing something or is it planned to i18n Storybook UI ?

**Describe the solution you'd like**
See Storybook in French :)

**Are you able to assist bring the feature to reality?**
Yes, I can contribute to translate EN -> FR

**Comment by shilman** [comment]
Hi @Shuunen, it's not on the roadmap yet since there are lots of other issues outstanding. We prioritize issues that are upvoted on Github, so I'm curious to see the community response here. Certainly open to it!

**Comment by Shuunen** [comment]
> We prioritize issues that are upvoted on Github

Sure, this one is not critical or blocking anyway, I'm just anticipating my customer request 😃 

Also, I'm seeing some public storybooks from French companies that seems to be fine with it in English, so this feature might not get that much upvotes 😅 But let's see.

**Comment by pumano** [comment]
Good idea. it should be possible by i18n plugins and translations can be stored as json files.

**Comment by webface** [comment]
I'm trying to use this code for translating components but there is no documentation of how to connect to /public/locale/{en}/translation.json
https://github.com/goooseman/storybook-addon-i18n
Its supposed to be possible with https://github.com/storybookjs/storybook/tree/master/addons/contexts

I've tried to configure it with no luck. What goes in `translations:{}` I tried pasting my translations.json into the obj but no diff.
 
```
import ThemeProvider from "./theme-provider";
import { useTranslation } from "react-i18next";

export const contexts = [
	{
		icon: "globe",
		title: "Locale",
		components: [ThemeProvider],
		params: [
			{
				name: "en",
				locale: "en",
				translations: {},
			},
			{
				name: "fr",
				locale: "fr",
				translations: {},
			},
		],
	},
![Screen Shot 2020-06-13 at 9 07 37 PM](https://user-images.githubusercontent.com/681890/84582439-f63d7800-adb9-11ea-85fa-0bb1195fe90f.png)

];
```

**Comment by shilman** [comment]
@webface please take a look at `addon-toolbars` in SB 6.0. if you can't get it working in toolbars, I'd be happy to help out on the Storybook Discord

**Comment by webface** [comment]
@shilman how do you update storybook to 6.0? Im pretty new to this. I have translations working in react reading json files in the public folder. Id like the same in storybook. I installed addon-toolbars but now there is a conflict between my config and preview .js as I cant have both. I'm running 5.3.19 and having problems with a few addons.

**Comment by shilman** [comment]
I'll create an upgrade guide soon, but the first step is to upgrade ALL storybook packages to the latest:

```
npx npm-check-updates '/storybook/' -un
npm install # or yarn
```

**Comment by shilman** [comment]
NOTE: new command for upgrading

```
npx sb@next upgrade --prerelease
```

**Comment by monolithed** [comment]
<img width="1923" alt="Снимок экрана 2020-10-15 в 19 16 20" src="https://user-images.githubusercontent.com/803674/96157653-3bfe7e80-0f1b-11eb-9068-30aa259ab81e.png">

@shilman, there are a lot of people who know english, but Storybook is demonstrated not for developers only. We use Storybook for managers, designers, analytics and other people who know only a national language or who want to make a screenshot for their presentations. Could you make some static ids for the tags or something else to redefine english texts?

**Comment by MatheusPatrickZup** [comment]
Yes please! Our documentation is a mix between storybook and zeroheight.
It's a bit odd right now that there are parts in english and parts in portuguese.

**Comment by aymonYU** [comment]
I also need this feature. We need to customize the menu and the sidebar in Chinese. hope support this, please!!!
