### ISSUE TITLE
Turn off esModulesInterop and allowSyntheticDefaultImports

### ISSUE THREAD

**Issue by hipstersmoothie** [storybookjs/storybook#11131]
**Describe the bug**

These two typescript config option make it so that consumer **must** also set these settings. [Read more from a core typescript member here](https://github.com/quilljs/delta/pull/34#issue-232142412).

After trying to speed up `react-typescript-docgen` I found that these two options killl typechecking performance. just these options added 15 seconds to my startup time.

**Expected behavior**

We don't force consumers to use these options. 

All imports of react are like

```js
import * as React from 'react';
```

[This is the suggested way by the core react team](https://twitter.com/sebmarkbage/status/1250284377138802689?lang=en)

**Comment by shilman** [comment]
Cc @ndelangen 

How breaking is this change? That speedup sounds awesome but I’m worried about overloading people with breaking changes in 6.0. Or is this one that won’t affect many users?

**Comment by hipstersmoothie** [comment]
I'll test it out but I think this actually makes the types easier to consume. Currently you must have `esModulesInterop` on to get the types produced by storybook to work. If we turn it off consumers can still have the option on and everything will work as expected (I think) they just won't *need* to have it on.

**Comment by hipstersmoothie** [comment]
I also volunteer to do this. It will probably require making a few PR to other repos.

**Comment by hipstersmoothie** [comment]
I might have been reading old guidance on esModuleInterop. It is unfortunate that it slows down type-generation so much. maybe we just turn it off for docgen? it only effects the output I think so it might be fine. I'll play around with it on my project

**Comment by ndelangen** [comment]
@hipstersmoothie if we abolish default exports... convert everything to named exports... Does that help?

**Comment by hipstersmoothie** [comment]
This is actually a pretty big breaking change and I'm not sure the ecosystem is quite ready for this change

**Comment by tooppaaa** [comment]
Maybe not related to esModulesInterop but while looking at #10895 I had this test done:

Using `React.forwardRef<HTMLSpanElement, ComplexForwardRefProps>(...)` 
With 
Using `import React from "react"`
- ✔️ In storybook (official)
- 🔴 in clean react + typescript

Using `import * as React from "react"`
- ✔️ In storybook (official)
- ✔️ in clean react + typescript

Using `forwardRef<HTMLSpanElement, ComplexForwardRefProps>(...)` 
With 
Using `import React, { forwardRef } from "react"`
- ✔️ In storybook (official)
- ✔️ in clean react + typescript

I am used to the `import * as`.. which leads to making the "mistake" (that compiles) in my project.
I'm in favor of using import * per many comments.
There's some discussions here https://github.com/mui-org/material-ui/pull/19802 that can provide more some context
