### ISSUE TITLE
[v6.0.0-beta.25] Static build fails to load

### ISSUE THREAD

**Issue by aputinski** [storybookjs/storybook#11132]
**Describe the bug**
Storybook works as expected when running in dev mode, but when serving the static build, the loading spinner / stencils display indefinitely and the following warning is logged:

```
received a SET_STORIES frame that was not configured as a ref
````

**To Reproduce**
https://github.com/aputinski/storybook-build-test-case

**System:**
```
System:
    OS: macOS 10.15.3
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Binaries:
    Node: 12.16.1
    Yarn: 1.22.4 
    npm: 6.13.4
  Browsers:
    Chrome: 83.0.4103.97
    Firefox: 77.0
    Safari: 13.0.5
  npmPackages:
    @storybook/addon-actions: 6.0.0-beta.25 => 6.0.0-beta.25
    @storybook/addon-docs: 6.0.0-beta.25 => 6.0.0-beta.25
    @storybook/addon-knobs: 6.0.0-beta.25 => 6.0.0-beta.25
    @storybook/addons: 6.0.0-beta.25 => 6.0.0-beta.25
    @storybook/react: 6.0.0-beta.25 => 6.0.0-beta.25
    @storybook/web-components: 6.0.0-beta.25 => 6.0.0-beta.25
```

**Comment by aputinski** [comment]
Did some more digging, and it looks like this RegExp is the culprit: https://github.com/storybookjs/storybook/blob/f95829a2c07ae601e32874ef4f4a25bb8c485836/lib/api/src/modules/refs.ts#L48

My server is stripping file extensions, so `/iframe.html` is rewritten to`/iframe` which causes the RegExp to no longer match which causes `getSourceType` to return `external`

**Comment by ndelangen** [comment]
@aputinski do you have a suggestion for a fix?

**Comment by ndelangen** [comment]
I upgraded this reproduction to the latest RC and it seems fixed already. 

@aputinski mind testing it for us? 🙏

**Comment by aputinski** [comment]
@ndelangen Just upgraded to the latest RC and it's working as expected. Thanks!
