### ISSUE TITLE
Stories glob broke

### ISSUE THREAD

**Issue by hipstersmoothie** [storybookjs/storybook#11135]
**Describe the bug**

Previously storybook just tried to glob the provided globPattern.
It new joins the glob pattern with the configDir resulting in the glob not matching anything.

In my case I'm using another globbing library and all paths are already resolved.

**Expected behavior**

Globs before [this change](https://github.com/storybookjs/storybook/pull/10926/files#r439078951) should still work.

**Screenshots**

You can see that storybook is joining my configDir with the provided glob (in the case a full path)

![Screen Shot 2020-06-11 at 2 28 01 PM](https://user-images.githubusercontent.com/1192452/84440972-c3478880-abef-11ea-9ef0-ef325e864e1b.png)

**Code snippets**
If applicable, add code samples to help explain your problem.

**System:**

beta-25

**Comment by ndelangen** [comment]
maybe instead of joining paths we can set the cwd in the glob library to resolve from there, this should make absolute paths work AND relative paths be resolved from the config dir.

Shouldn't be too big of a change, and would resolve your issue @hipstersmoothie. WDYT?

**Comment by hipstersmoothie** [comment]
sounds good to me! Respecting absolute paths would solve my problem

**Comment by ndelangen** [comment]
I think someone else already picked this up, I saw a PR that used `isAbsolute()` to determine whether to join the path or not.

**Comment by ndelangen** [comment]
https://github.com/storybookjs/storybook/blob/6f7420531d17fb6fd0320c2c41c46ca0be535294/lib/core/src/server/preview/entries.js#L61-L62
