### ISSUE TITLE
Two prettier config files

### ISSUE THREAD

**Issue by mbelsky** [storybookjs/storybook#11147]
Hey,

I've found the following prettier config files in this repo:
1. `.prettierrc`
1. `prettier.config.js`

Is there a reason to have both of them?

**Comment by shilman** [comment]
I think `.prettierrc` is redundant cc @ndelangen

**Comment by ndelangen** [comment]
deepscan doesn't support `prettier.config.js` yet, when it does, we should be able to remove it.
