### ISSUE TITLE
Officially deprecate options parameter (except storySort?)

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#11142]
Most of the options parameters have been moved to manager `addons.setConfig`. Make sure these are officially deprecated and/or removed and the appropriate message is logged to the user to help them migrate.

**Comment by tmeasday** [comment]
Ok, here is the plan in detail:

1. There's a subset of `options` parameters that control the UI of Storybook in a "mutable" way, think `showAddonsPanel` et al. 

 a. People want to set these parameters per-story, for various reasons.
 b. Arguably there could be a couple more here: `showDocs`, `showCanvas`, `activePane` or such.
 c. Currently there are various known issues with those parameters conflicting with user action + persistence. We aren't going to solve those issues right now, but hopefully we can address those and b. in the near future.
 d. Probably we should put these on `parameters.ui` as that feels like a better name.
 e. Right now we are not going to touch these.

2. There's another set of `options` parameters that are *not* mutable, certainly at a story level, like `showRoots` and `enableShortcuts`. These should be deprecated.

3. Finally there's `storySort` which is preview-only and probably should be at the top-level but I'm not going to change that now either.

**Comment by shilman** [comment]
Yay!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-beta.40 containing PR #11387 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
