### ISSUE TITLE
Object is not a function

### ISSUE THREAD

**Issue by vanpana** [storybookjs/storybook#11144]
**Describe the bug**

Opening up Storybook which has `addon-docs` enabled as an addon will result in an infinitely loading page and the following error in the console:

```
core.browser.esm.js:10 Uncaught TypeError: Object(...) is not a function
    at Module../node_modules/@emotion/core/dist/core.browser.esm.js (core.browser.esm.js:10)
    at __webpack_require__ (bootstrap:789)
    at fn (bootstrap:150)
    at Module../node_modules/@emotion/styled-base/dist/styled-base.browser.esm.js (styled-base.browser.esm.js:1)
    at __webpack_require__ (bootstrap:789)
    at fn (bootstrap:150)
    at Module../node_modules/@emotion/styled/dist/styled.browser.esm.js (styled.browser.esm.js:1)
    at __webpack_require__ (bootstrap:789)
    at fn (bootstrap:150)
    at Object../node_modules/@storybook/theming/dist/index.js (index.js:39)
```

**Expected behavior**
Not to throw an error

**Screenshots**
Screenshot with infinite loading and console error.
<img width="1616" alt="Screenshot 2020-06-12 at 12 08 47" src="https://user-images.githubusercontent.com/13353799/84491850-7c1bcf00-aca5-11ea-8279-96ef974b5eee.png">

**System:**
Environment Info:

  System:
    OS: macOS 10.15.3
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    npm: 6.13.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 84.0.4147.45
    Safari: 13.0.5
  npmPackages:
    @storybook/addon-docs: ^5.3.19 => 5.3.19 
    @storybook/addon-storysource: ^5.3.19 => 5.3.19 
    @storybook/preact: ^5.3.19 => 5.3.19 
    @storybook/preset-scss: ^1.0.2 => 1.0.2 

**Additional context**
main.js file
```
module.exports = {
    stories: ['../**/*.stories.[tj]sx'],
    addons: [
        '@storybook/addon-docs',
        '@storybook/addon-storysource',
        '@storybook/preset-scss'
    ]
};
```
It works just fine **without** `addon-docs`.
It doens't matter the order that I put the addons in, the error will still occur.

**Comment by shilman** [comment]
Do you have a public repro repo I can look at? Is it still a problem in 6.0-beta?

**Comment by vanpana** [comment]
Unfortunately, the repo is not public and I cannot make it this way. 😞
6.0-beta is not an option, but I tried upgrading just to see if it works and I get a lot of errors like `Module not found: Error: Can't resolve 'core-js/modules/web.dom-collections.iterator'`

**Comment by shilman** [comment]
@vanpana might be an issue with `preact/compat`? i've added a working example of `addon-docs` to our sample project here: https://github.com/storybookjs/storybook/pull/11145

**Comment by vanpana** [comment]
Just to check that `preact/compat` is working, I changed the `Button` component on your branch to 
```
import { h } from 'preact';
import Preact from 'preact/compat';

/**
 * The button component will render a clickable button
 */
export default class Button extends Preact.Component {
  render() {
    const TagName = this.props.href ? 'a' : 'button';

    return (
      <TagName class="button" href={this.props.href} {...this.props}>
      {this.props.children}
    </TagName>
    )
  }
}
```

And it is indeed working.
That probably means, somehow, my code is faulty.

If I find any clue, I'll update this issue in case others have this problem.

**Comment by vanpana** [comment]
Quick update:
After getting the project sample working with preact/compat, I wondered what's different in my code.
It turns out that when moving to a fresh folder, I can get the Storybook addon to work. So the problem is not the addon or preact, but maybe some other dependency in the project that interferes.

Thanks a lot for the help!
