### ISSUE TITLE
100% height in documentation iframe

### ISSUE THREAD

**Issue by stefanoScalzo** [storybookjs/storybook#11148]
**Is your feature request related to a problem? Please describe.**
Im always frustrated when i need to constantly specify the iFrameHeight just to make all my components iframeHeight to take the full height of the example.

**Describe the solution you'd like**
A way to put a general tag on the documentation that would make all of the iframe's heights to be equal to 100% of the example within it.

**Describe alternatives you've considered**
I've tried to use padding top with position absolute on the iframe, with a parent container being 100% height. I think this is the smart solution, but I don't think it is possible to apply as storybook creates the examples behind the scenes. 

**Are you able to assist bring the feature to reality?**
I could help provide the concept to fixing this issue

**Comment by shilman** [comment]
Closing as dupe to #8112
