### ISSUE TITLE
[client-api] Typescript error due to missing types include

### ISSUE THREAD

**Issue by fernandopasik** [storybookjs/storybook#11161]
**Describe the bug**
When checking types on my own project where I use storybook it runs an error indicating that a type of a library used by storybook is missing and treats it like "any"

**To Reproduce**
run tsc --noEmit in a project that uses storybook

**Expected behavior**
No errors

**Screenshots**
```
$ tsc --noEmit -p tsconfig.all.json
node_modules/@storybook/client-api/dist/queryparams.d.ts:1:16 - error TS7016: Could not find a declaration file for module 'qs'. '/hello-web-components/node_modules/qs/lib/index.js' implicitly has an 'any' type.
  Try `npm install @types/qs` if it exists or add a new declaration (.d.ts) file containing `declare module 'qs';`

1 import qs from 'qs';
                 ~~~~


Found 1 error.
```

**Additional context**
Latest storybook beta version

**Comment by fernandopasik** [comment]
Solution proposed is to add @types/qs to dependencies in https://github.com/storybookjs/storybook/blob/next/lib/client-api/package.json#L42

**Comment by fernandopasik** [comment]
An example where this didn't happen and has that types library
https://github.com/storybookjs/storybook/blob/next/addons/links/package.json

**Comment by fernandopasik** [comment]
fixed by #11162

**Comment by shilman** [comment]
@fernandopasik our convention is to close the issues once the fix is released, which happens automatically in my release script if the first line of the PR includes a reference to the issue, e.g.  `#XXXX` or a URL. So no need to close the issue by hand.

**Comment by fernandopasik** [comment]
@shilman sorry about that, thanks for the clarification, won't happen again

**Comment by shilman** [comment]
@fernandopasik no problem! ❤️

**Comment by shilman** [comment]
Huzzah!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-beta.28 containing PR #11162 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.
