### ISSUE TITLE
Validate storybook id references

### ISSUE THREAD

**Issue by hipstersmoothie** [storybookjs/storybook#11163]
**Describe the bug**

When I write mdx for my stories and reference them by `id` I can't validate that the links are correct without opening storybook.

```js
<Preview>
  <Story id='components-badge-features--text' />
</Preview>
```

If the `id` above changes the story won't display and no other warnings are presented

**Expected behavior**

When I `build` my storybook it should warn about broken `Story` links

**System:**

6.0.0-beta.25

**Comment by hipstersmoothie** [comment]
bump

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and SB7 now references stories by import rather than by string. https://storybook.js.org/blog/storybook-7-docs/

Please open a new issue referencing this one if this is still relevant in SB 7.x.
