### ISSUE TITLE
add story ID to canvas mode.

### ISSUE THREAD

**Issue by lifeiscontent** [storybookjs/storybook#11177]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to have the story id on both canvas and docs pages so we could use it as a hook to style a story.

**Describe the solution you'd like**
I have a storybook decorator:

```tsx
import { makeDecorator } from '@storybook/addons';
import { useLayoutEffect } from 'react';

export const withBodyStyle = makeDecorator({
  name: 'withBodyStyle',
  parameterName: 'bodyStyle',
  wrapper(getStory, context, settings) {
    // eslint-disable-next-line react-hooks/rules-of-hooks
    useLayoutEffect(() => {
      document.body.style.backgroundColor =
        (settings.parameters as CSSStyleDeclaration)?.backgroundColor ??
        settings.options?.backgroundColor;

      return (): void => {
        document.body.style.backgroundColor = '';
      };
    }, [settings.options, settings.parameters]);

    return getStory(context) as JSX.Element;
  },
});

if (module?.hot?.decline) {
  module.hot.decline();
}
```

right now all it does is change background colors, but I plan on adding things like backgroundImage.

it has worked very well in canvas mode, but now that I've added docs, it makes it much more difficult. So I think an easy way to handle the complexity is to some how feed the story ID into the decorator and instead of styling the body, style whatever the tag is that has the ID.

As a convention, You'd want the tag to be the entire canvas of the story so you could have the background-color applied to the entire preview of the story.

**Describe alternatives you've considered**
N/A

**Are you able to assist bring the feature to reality?**
I can if someone wants to help guide me through the changes that would need to be made.

**Additional context**

**Comment by lifeiscontent** [comment]
@shilman

**Comment by shilman** [comment]
@ndelangen WDYT? i think it makes sense and would be easy to add

**Comment by ndelangen** [comment]
I propose we create a new hook in lib/addons called `useRenderRootNode()` which returns the root DOM-node the story is being rendered on.

This way we do not have to change any APIs, just add something that's optional.

**Comment by ndelangen** [comment]
Want to work on this feature together @lifeiscontent?

https://calendly.com/ndelangen/storybook

**Comment by lifeiscontent** [comment]
@ndelangen scheduled! :)
