### ISSUE TITLE
Server onListening callback and lazy flag

### ISSUE THREAD

**Issue by karlhepler** [storybookjs/storybook#11179]
**Is your feature request related to a problem? Please describe.**
I am using [Bazel](https://bazel.build) to build my Typescript project. To get Bazel to play nicely with webpack-dev-server, I had to set it to [lazy](https://webpack.js.org/configuration/dev-server/#devserverlazy-) mode and define a custom implementation of [onListening](https://webpack.js.org/configuration/dev-server/#devserveronlistening) in which - under the right circumstances - I manually invoke `server.compiler.run`. I need the same sort of listener for Storybook.

**Describe the solution you'd like**
I would like to make available a new property in the `main.js` config called `onListening`. `onListening` is a function that is passed a single argument: the `webpack-dev-middleware` instance. This will allow me to invoke [invalidate](https://github.com/webpack/webpack-dev-middleware#invalidate) and [waitUntilValid](https://github.com/webpack/webpack-dev-middleware#waituntilvalidcallback) as I see fit.

In addition to this, I would also like an additional property in the `main.js` config called `lazy`. This will be a boolean value and will function in exactly the same way as the [lazy](https://webpack.js.org/configuration/dev-server/#devserverlazy-) property in `webpack-dev-config`.

**Describe alternatives you've considered**
Writing my own custom implementation of Storybook's dev server.

**Are you able to assist bring the feature to reality?**
Yes I can. I'm pretty confident that implementing `onListening` shouldn't be too hard, but I'm not familiar enough with the code to know how to prevent automatic rebuilding with a "lazy" flag.

**Additional context**
n/a

**Comment by karlhepler** [comment]
I noticed that I can add the `extendServer` property to the standalone storybook function options. If we could ensure that access to the webpack compiler is in the server's context, then that would satisfy my feature request.

**Comment by pward123** [comment]
Did you ever find a solution? I'd also like to run storybook with bazel using lazy.

**Comment by karlhepler** [comment]
No. I decided to just run it natively without bazel.
