### ISSUE TITLE
Storybook build failing in Travis with error : The job exceeded the maximum log length, and has been terminated

### ISSUE THREAD

**Issue by IshratPahalwi** [storybookjs/storybook#11203]
My travis build seems to give the error : "The job exceeded the maximum log length, and has been terminated" during the storybook build. 
I am building using the command :
NODE_OPTIONS=--max_old_space_size=4096 build-storybook -s --quiet ./public -o .out

I am assuming the storybook build is generating too much logs which is causing the travis build to terminate . Can anyone please suggest how to supress storybook from generating too much unnecessary logs ?

Is there a way that I can edit my storybook webpack.config.js ?
I am using storybook ^5.3.8 and node v12.16.1.
Please advise. Thanks in advance.

**Comment by shilman** [comment]
I think `--quiet` was made more quiet in 6.0-beta. maybe try upgrading?

**Comment by IshratPahalwi** [comment]
@shilman : When I am using storybook :
"@storybook/addon-a11y": "^6.0.14",
"@storybook/addon-actions": "^6.0.14",
"@storybook/addon-knobs": "^6.0.14",
"@storybook/addon-options": "^6.0.14",
"@storybook/addon-storysource": "^6.0.14",
"@storybook/react": "^6.0.14",
"@storybook/theming": "^6.0.14",
I am getting : 
No matching version found for @storybook/addon-a11y@^6.0.14

**Comment by shilman** [comment]
try "next"

**Comment by IshratPahalwi** [comment]
@shilman : I upgraded my storybook to ^6.0.14. My package.json : 
"devDependencies": {
		"@babel/core": "^7.9.0",
		"@babel/runtime-corejs2": "^7.5.5",
		"@commitlint/cli": "^8.1.0",
		"@commitlint/config-angular": "^7.1.2",
		"@isc/spotlight-devops": "^2.8.11",
		"@storybook/addon-a11y": "next",
		"@storybook/addon-actions": "next",
		"@storybook/addon-knobs": "next",
		"@storybook/addon-options": "next",
		"@storybook/addon-storysource": "next",
		"@storybook/react": "next",
		"@storybook/theming": "next",
		"@testing-library/cypress": "^6.0.0",
		"@testing-library/jest-dom": "^5.5.0",
		"@testing-library/react": "^10.0.2",
		"@testing-library/user-event": "^10.0.1",
		"@types/jest": "^24.0.15",
		"autoprefixer": "^8.5.1",
		"babel-eslint": "^8.2.3",
		"babel-jest": "^25.1.0",
		"babel-loader": "^8.0.6",
		"babel-plugin-module-resolver": "^3.1.1",
		"babel-plugin-wrap-in-js": "^1.1.1",
However, when I am building my storybook, I am getting the following error message :
ERR! Module not found: Error: Can't resolve 'core-js/modules/es.symbol' in '/Users/Ishrat.Pahalwi@ibm.com/Documents/IBM_Projects/investigate/.storybook'
(node:6609) UnhandledPromiseRejectionWarning: ModuleNotFoundError: Module not found: Error: Can't resolve 'core-js/modules/es.symbol' in '/Users/Ishrat.Pahalwi@ibm.com/Documents/IBM_Projects/investigate/.storybook'
    at /Users/Ishrat.Pahalwi@ibm.com/Documents/IBM_Projects/investigate/node_modules/webpack/lib/Compilation.js:925:10
    at /Users/Ishrat.Pahalwi@ibm.com/Documents/IBM_Projects/investigate/node_modules/webpack/lib/NormalModuleFactory.js:401:22
    at /Users/Ishrat.Pahalwi@ibm.com/Documents/IBM_Projects/investigate/node_modules/webpack/lib/NormalModuleFactory.js:130:21
    at /Users/Ishrat.Pahalwi@ibm.com/Documents/IBM_Projects/investigate/node_modules/webpack/lib/NormalModuleFactory.js:224:22
    at /Users/Ishrat.Pahalwi@ibm.com/Documents/IBM_Projects/investigate/node_modules/neo-async/async.js:2830:7
    at /Users/Ishrat.Pahalwi@ibm.com/Documents/IBM_Projects/investigate/node_modules/neo-async/async.js:6877:13
Can you please if I need to update any other dependencies or any other storybook changes ?
