### ISSUE TITLE
[v6.0.0-beta.28] question: how to render stories into a new tab

### ISSUE THREAD

**Issue by sarah-martinellibenedetti** [storybookjs/storybook#11200]
I would like to render stories that have the viewMode: lite into a new tab. I've created a new addon to add a new tab, which worked fine:

```js
addons.add(PANEL_ID, {
    type: types.TAB,
    route: ({ storyId }) => `/lite/${storyId}`,
    match: ({ viewMode }) => viewMode === "lite",
    title,
    render: () => null
```

but I cannot get it to work - no matter what is in the render. I thought that the issue was that I was missing a decorator, something like this:

```js
import React from "react";
import addons, { makeDecorator } from "@storybook/addons";

export default makeDecorator({
  name: "withMyAddon",
  parameterName: "myParameter",
  wrapper: (getStory, context, { parameters }) => {
    return getStory(context);
  }
});
```
but it didn't work (I've added the decorator on meta and on the story itself).
My assumption is that I cannot use render null, but no matter if try to use, story, preview, docsContainer, it will not work.

Any hints/directions would be greatly appreciated. Thanks

**system**
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
  Binaries:
    Node: 12.16.2 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    @storybook/addon-a11y: ^5.3.17 => 5.3.18
    @storybook/addon-actions: ^6.0.0-alpha.44 => 6.0.0-beta.28
    @storybook/addon-docs: ^6.0.0-alpha.44 => 6.0.0-beta.28
    @storybook/addon-knobs: ^5.3.17 => 5.3.18
    @storybook/addon-links: ^6.0.0-alpha.44 => 6.0.0-beta.28
    @storybook/addon-storysource: ^5.3.17 => 5.3.18
    @storybook/addon-viewport: ^5.3.19 => 5.3.19
    @storybook/addons: ^6.0.0-alpha.44 => 6.0.0-beta.28
    @storybook/preset-create-react-app: ^2.1.1 => 2.1.1
    @storybook/react: ^6.0.0-alpha.44 => 6.0.0-beta.28
    @storybook/source-loader: ^5.3.18 => 5.3.18

**Comment by shilman** [comment]
Unrelated, but please upgrade all your packages to the same version. If 5.3 and 6.0 packages work together properly, it's only by accident.
