### ISSUE TITLE
storybook-dynamic-app-root not reloading after knobs change in version 5.3.19

### ISSUE THREAD

**Issue by nikhilbasware** [storybookjs/storybook#11219]
HI ,

I was using storybook version 4 the time when I upgraded it to version 5 , component stops reloading after changing knobs value , It picks all the knobs value only one during initialization after that it does not show my angular component with updated knobs value.I have seen this thing that on version 4 it used to reload and the values such as placeholder used to get updated. Please suggest me solution.I was using  knobs and passing multiple object to story like this

storiesOf("Input controls|Amount Filter", module)
  .addDecorator(withKnobs)
  .add("with text", () => ( {
    props: {
      ptFilters: object("ptFilters", [
        {
          label: "Less than",
          isSelected: true,
          isDefault: true,
          startRange: 10
        },
        {
          label: "Greater than",
          startRange: 10,
          isSelected: false
        },
        {
          label: "In range",
          startRange: 10,
          endRange: 100,
          isSelected: false
        },
        {
          label: "Equals",
          startRange: 0,
          isSelected: false
        },
        {
          label: "Empty",
          hideInputs: true,
          isSelected: false
        }
      ]),
      ptConfig: object("ptConfig", {
        label: "Amount Filter",
        name: "amountFilter"
      }),
      ptTranslations: object("ptTranslations", {
        clear: "Clear",
        placeholder: "Enter Sum",
        minimum: "Minimum",
        maximum: "Maximum"
      }),
      ptRequired: boolean("ptRequired", false),
      ptDisabled: boolean("ptDisabled", false),
      ptNumericRangeConfig: object("ptNumericRangeConfig", {
        name: "amountFilter",
        minRange: 5,
        maxRange: 200
      }),
      ptEvent: (event: AmountFilterEvents | ProtonEvents) => {
        action("event: ")(event);
      }
    }
  }));

**Comment by Maks-Yaremenko** [comment]
I have the same issue, after changing stories, rebuilding executed automatically, but the browser doesn't reload the page after I'm doing it my self - I'm able to see updated values.

so for some reason live-reload won't work.

**Comment by shilman** [comment]
FYI, we’ve released `addon-controls` in Storybook 6.0. Controls are portable, auto-generated knobs that are intended to replace `addon-knobs` long term.

- [Controls documentation](https://storybook.js.org/docs/react/essentials/controls)
- [Migration instructions](https://github.com/storybookjs/storybook/blob/next/addons/controls/README.md#how-do-i-migrate-from-addon-knobs)

Please upgrade and try them out today!
