### ISSUE TITLE
"the types mismatch" warning when using same prop name with different types

### ISSUE THREAD

**Issue by Claudia-Sardinha-Bose** [storybookjs/storybook#11229]
**Describe the bug**

Storybook (addon-docs) shows a warning in console when defining a prop and defaultProp with the same name but different types in two different components. 

**To Reproduce**

1. Create a React Storybook with the addon-docs
2. Create two React components with a prop that has the same name but different types:

```
MyFirstComponent.propTypes = {
      myProp: PropTypes.number
}

MyFirstComponent.defaultProps = {
      myProp: 0
}
```

```
MySecondComponent.propTypes = {
      myProp: PropTypes.array
}

MySecondComponent.defaultProps = {
      myProp: []
}
```
3. Check the console 

![image](https://user-images.githubusercontent.com/24386643/85053384-4fc6ed80-b192-11ea-8d73-70bbacb729b5.png)

**Expected behavior**
No error should appear in the console

**System:**

> Environment Info:
> 
>   System:
>     OS: macOS 10.15.5
>     CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
>   Binaries:
>     Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
>     Yarn: 1.22.4 - ~/.nvm/versions/node/v12.16.1/bin/yarn
>     npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
>   Browsers:
>     Chrome: 83.0.4103.106
>     Safari: 13.1.1
>   npmPackages:
>     @storybook/addon-a11y: 6.0.0-beta.23 => 6.0.0-beta.23 
>     @storybook/addon-actions: 6.0.0-beta.23 => 6.0.0-beta.23 
>     @storybook/addon-docs: 6.0.0-beta.23 => 6.0.0-beta.23 
>     @storybook/addon-storyshots: 6.0.0-beta.23 => 6.0.0-beta.23 
>     @storybook/addon-storyshots-puppeteer: 6.0.0-beta.23 => 6.0.0-beta.23 
>     @storybook/addons: 6.0.0-beta.23 => 6.0.0-beta.23 
>     @storybook/react: 6.0.0-beta.23 => 6.0.0-beta.23 
>     @storybook/theming: 6.0.0-beta.23 => 6.0.0-beta.23 
>     @storybook/vue: 6.0.0-beta.23 => 6.0.0-beta.23

**Comment by shilman** [comment]
Son of a gun!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-rc.13 containing PR #11624 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
