### ISSUE TITLE
Addon-docs: Story selection broken in Docs panel after upgrading to v6.0

### ISSUE THREAD

**Issue by mklanjsek** [storybookjs/storybook#11228]
**Describe the bug**
After upgrading Storybook on our Angular based project from 5.3.18 to v6.0.0-beta.31, the MDX docs selection is broken. The Docs panel always shows the last MDX story, regardless of which story is selected on the left. It's only the Docs panel that's broken, the Canvas panel still shows the right story when changing the selection.

This has been broken for a while, I've seen it since at least v6.0.0-beta.18, and all attempts to work around it or find a resolution on our side failed.

**To Reproduce**
1. Bumped Storybook from 5.3.18 to v6.0.0-beta.31,
2. Open Storybook and select one of the MDX stories,
3. Notice the Docs panel incorrectly displays the last story `Timestamp`  
4. Repeat selection for all MDX stories and Docs panel will always display the same `Timestamp` story.

**Expected behavior**
Correct Docs should be displayed for each selected story.

**Screenshots**
![Screen Shot 2020-06-18 at 7 33 33 AM](https://user-images.githubusercontent.com/34245594/85026641-25474700-b136-11ea-94cd-a5d2175a7fc4.png)
![Screen Shot 2020-06-18 at 7 43 10 AM](https://user-images.githubusercontent.com/34245594/85027701-70ae2500-b137-11ea-86e6-bbc05004d5af.png)

**Code snippets**
Here is an example of one of our stories:
```
import { Meta, Story, Props } from '@storybook/addon-docs/blocks';
import { object, withKnobs } from '@storybook/addon-knobs';
import {TextComponent} from "../app/modules/shared/components/presentation/text/text.component";

<h1>Text component</h1>
<h2>Description</h2>

<p>The Text component is used to present simple text</p>
<h2>Example</h2>

<Meta title="Octant/Components" component={TextComponent} />

<Story name="Text" height="150px">
{{
    props: {
      view:  object('View', {
        metadata: {
          type: 'text',
        },
        config: {
          value: 'hello world',
          isMarkdown: false,
        },
      }),
    },
    component: TextComponent,
    }}
</Story>

<h2>Props</h2>
<Props of={TextComponent} />
```

**System:**
```Environment Info:

  System:
    OS: macOS Mojave 10.14
    CPU: (4) x64 Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
  Binaries:
    Node: 12.5.0 - /usr/local/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 6.13.7 - /usr/local/bin/npm
  Browsers:
    Chrome: 83.0.4103.106
    Firefox: 77.0.1
    Safari: 12.0
  npmPackages:
    @storybook/addon-actions: v6.0.0-beta.31 => 6.0.0-beta.31
    @storybook/addon-console: ^1.2.1 => 1.2.1
    @storybook/addon-docs: v6.0.0-beta.31 => 6.0.0-beta.31
    @storybook/addon-knobs: v6.0.0-beta.31 => 6.0.0-beta.31
    @storybook/addon-links: v6.0.0-beta.31 => 6.0.0-beta.31
    @storybook/addons: v6.0.0-beta.31 => 6.0.0-beta.31
    @storybook/angular: v6.0.0-beta.31 => 6.0.0-beta.31
    @storybook/theming: v6.0.0-beta.31 => 6.0.0-beta.31
```
**Additional context**

**Comment by shilman** [comment]
I'm unable to repro. Do you have a public repro I can look at?

**Comment by mklanjsek** [comment]
@shilman Unfortunately I do not have the reproduce case anymore. We worked around the problem by temporarily changing the story tree structure - basically changing the story tree pattern from `Octant/Components/[ComponentXYZ]` to `Octant/[ComponentXYZ]/[ComponentXYZ]`.  That may give you some clues for reproducing the problem - basically all stories that have identical 2nd level in tree structure are showing the same docs page (the very last one).

If that does not help, I can try creating a small repro case on stackblitz or somewhere else.
