### ISSUE TITLE
support for gradient backgrounds in addon-backgrounds api

### ISSUE THREAD

**Issue by Jessica-Koch** [storybookjs/storybook#11231]
Would love the ability to add a gradient background to preview-iframe with addon backgrounds.  I can make the PR for this if this is as simple as I think it is, which it never is...

**Describe the solution you'd like**
addon backgrounds changes `background` CSS property instead of `background-color`.
![image](https://user-images.githubusercontent.com/9360417/85076729-9823e280-b175-11ea-81a0-70241dfcc76b.png)

**Describe alternatives you've considered**

**Are you able to assist bring the feature to reality?**
I know where this change would need to take place in the code, but not sure if there was a reason that `background-color` was used instead of `background`.

**Additional Context**
current: 
![image](https://user-images.githubusercontent.com/9360417/85076888-ef29b780-b175-11ea-924e-956fefde94d4.png)

ideal: 
![image](https://user-images.githubusercontent.com/9360417/85076838-d4efd980-b175-11ea-8ef5-88861169865b.png)

**Comment by shilman** [comment]
Ooh-la-la!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-beta.34 containing PR #11265 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
