### ISSUE TITLE
What's new page state & manager UI

### ISSUE THREAD

**Issue by kylesuss** [storybookjs/storybook#11232]
**Are you able to assist bring the feature to reality?**
yes

**Additional context**

This is a new screen that shows the latest major/minor versions release notes.

* It appears automatically when SB is first opened after installing a new major or minor release. 
* It does not appear when you install Storybook for the first time
* It does not appear when you build Storybook statically 
* It does not appear when running SB in a production environment
* You must exit from the screen to go back to normal usage (similar to VSCode or Chrome Devtools). Track when this page is closed so that we don’t show it multiple times.

STRETCH goal: Add a config/option to disable release notes
E.g., VSCode has a bool update.showReleaseNotes that the user can set to false if they want

**Project pieces**

1. Save state of versions/what's new viewing in SB cache
2. Implement SB manager UI which opens the what's new page in an iframe when the criteria are met

**Comment by shilman** [comment]
#11360 merged & released
