### ISSUE TITLE
Theming: Line Height is absolute for many of the block components

### ISSUE THREAD

**Issue by dfernandez-asapp** [storybookjs/storybook#11230]
**Is your feature request related to a problem? Please describe.**
Storybook Docs add-on allows customizations using themes.

While you can change the font family and size, in some components the line height is set with an absolute value in pixels.

Source code: 
https://github.com/storybookjs/storybook/blob/master/lib/components/src/blocks/DocsPage.tsx

**Describe the solution you'd like**
Using relative line height allows the theme to change the font size and let the line height to adapt.

**Describe alternatives you've considered**
The workaround is to set the CSS: https://github.com/storybookjs/storybook/blob/master/addons/docs/docs/theming.md#css-escape-hatches

However, since the theme object allows configuring font sizes, the line height should be relative or provide also a way to configure it using the theme.

**Are you able to assist bring the feature to reality?**
yes

**Comment by shilman** [comment]
checking with @domyen who did the theming

**Comment by shilman** [comment]
cc @domyen

**Comment by domyen** [comment]
Thanks for the feature request! Apologies for the lag in the reply. 

I recommend using the CSS escape hatches for font-size and line-height combinations. Fonts have different "x-heights" which affect how large/small text appears even if they're technically the same font-size. 
![image](https://user-images.githubusercontent.com/263385/89221832-ef550980-d5a1-11ea-925e-827d17bce555.png)

That means there's no "perfect" relative line-height value for all fonts. e.g., You might want 16/24 for Helvetica and 16/26 for Georgia. 

Unfortunately, I don't think it makes sense to do this one, but I definitely appreciate your suggestion. 🙇‍♂️
