### ISSUE TITLE
Addon Docs and Controls not working with Yarn 2.

### ISSUE THREAD

**Issue by nnennajohn** [storybookjs/storybook#11233]
**Describe the bug**
Hi. I have a monorepo setup with Yarn 2 and the latest storybook and addons. The Doc page shows an error when I navigate to it, and the controls section shows not setup, despite following the examples shown in the Docs.

**To Reproduce**
1. Create New Repo with Yarn 2
2. Try to setup Addon Docs and Controls
3. Observe errors in screenshots below

**Expected behavior**
Docs page and Controls tabs work as specified in docs

**Screenshots**
<img width="1056" alt="Screen Shot 2020-06-18 at 5 59 01 PM" src="https://user-images.githubusercontent.com/1761197/85085862-f361cf00-b18d-11ea-99ba-e7210115ebd5.png">

<img width="898" alt="Screen Shot 2020-06-18 at 5 58 00 PM" src="https://user-images.githubusercontent.com/1761197/85085865-f5c42900-b18d-11ea-901e-903500e45fb5.png">

**Code snippets**
If applicable, add code samples to help explain your problem.

***main.js file***
```const { readFileSync } = require('fs');
const { resolve, join } = require('path');
const lessToJS = require('less-vars-to-js');

const UNIVERSAL_PATH = join(__dirname, '../../universal/src');

if (typeof require !== 'undefined') {
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  require.extensions['.less'] = (file) => {};
}

const themeVariables = lessToJS(
  readFileSync(
    resolve(__dirname, `${UNIVERSAL_PATH}/theme/antdThemeVariables.less`),
    'utf8'
  )
);

module.exports = {
  // stories: [`${SRC_PATH}/**/*.stories.tsx`],
  stories: ['../src/**/*.stories.tsx'],
  addons: [
    '@storybook/addon-links',
    '@storybook/addon-viewport',
    '@storybook/addon-backgrounds',
    {
      name: '@storybook/addon-docs',
      options: {
        configureJSX: true,
      },
    },

    '@storybook/addon-controls',
    '@storybook/addon-actions',
  ],
  webpackFinal: async (config, { configType }) => {
    // `configType` has a value of 'DEVELOPMENT' or 'PRODUCTION'
    // You can change the configuration based on that.
    // 'PRODUCTION' is used when building the static version of storybook.

    // Make whatever fine-grained changes you need
    const isDEV = configType === 'DEVELOPMENT';
    const isPROD = configType !== 'DEVELOPMENT';
    // config.resolve.extensions.push('.ts', '.tsx');
    config.module.rules.push({
      test: /\.css$/,
      use: [
        {
          loader: 'postcss-loader',
          options: {
            plugins:
              process.env.NODE_ENV === 'production'
                ? [
                    require('postcss-import'), // use with https://github.com/postcss/postcss-url in prod
                    require('tailwindcss')('../universal/tailwind.config.js'),
                    require('postcss-flexbugs-fixes'),
                    require('postcss-preset-env')({
                      autoprefixer: {
                        flexbox: 'no-2009',
                        grid: 'autoplace',
                      },
                      stage: 3,
                      features: {
                        'custom-properties': false,
                      },
                    }),
                  ]
                : [
                    require('tailwindcss')('../universal/tailwind.config.js'),
                    require('postcss-preset-env'),
                  ],
          },
        },
      ],
      include: [
        resolve(__dirname, '../'),
        resolve(__dirname, `${UNIVERSAL_PATH}/`),
      ],
    });

    config.module.rules.push({
      test: /\.scss$/,
      use: ['style-loader', 'css-loader', 'sass-loader'],
      include: [
        resolve(__dirname, '../'),
        resolve(__dirname, `${UNIVERSAL_PATH}/styles/main.scss`),
      ],
    });

    config.module.rules.push({
      test: /\.less$/,
      use: [
        {
          loader: 'style-loader',
        },
        {
          loader: 'css-loader', // translates CSS into CommonJS
        },
        {
          loader: 'less-loader', // compiles Less to CSS
          options: {
            javascriptEnabled: true,
            modifyVars: themeVariables,
          },
        },
      ],
    });

    // Return the altered config
    return config;
  },
};```

***preview.js file***
```export const parameters = {
  actions: { argTypesRegex: '^on.*' },
};```

**System:**
Using Yarn 2, Node 12, Storybook versions:
```
    "@storybook/addon-actions": "^6.0.0-beta.31",
    "@storybook/addon-backgrounds": "^6.0.0-beta.31",
    "@storybook/addon-controls": "^6.0.0-beta.31",
    "@storybook/addon-docs": "^6.0.0-beta.31",
    "@storybook/addon-essentials": "^6.0.0-beta.31",
    "@storybook/addon-knobs": "^6.0.0-beta.31",
    "@storybook/addon-links": "^6.0.0-beta.31",
    "@storybook/addon-storyshots": "^6.0.0-beta.31",
    "@storybook/addon-viewport": "^6.0.0-beta.31",
    "@storybook/addons": "^6.0.0-beta.31",
    "@storybook/client-api": "^6.0.0-beta.31",
    "@storybook/client-logger": "^6.0.0-beta.31",
    "@storybook/react": "^6.0.0-beta.31",
```

**Comment by shilman** [comment]
@nnennajohn do you have mutliple copies of addon-docs installed? that stack trace looks like it's from a 5.3 version, which def won't work with the 6.0 setup. maybe somewhere else in the monorepo?

**Comment by nnennajohn** [comment]
@shilman You are right. Thanks for the prompt search. Let me remove the other version on the root folder and try again.

Screenshot:
<img width="680" alt="Screen Shot 2020-06-19 at 8 40 59 PM" src="https://user-images.githubusercontent.com/1761197/85190607-c6391d80-b26e-11ea-9299-b2328c3f164f.png">

**Comment by nnennajohn** [comment]
@shilman, Thank you. Removing the rogue mismatch version of storybook resolved addon-docs showing up. 

But still don't have addon-controls working. 

Per the docs, which I followed:

<img width="958" alt="Screen Shot 2020-06-19 at 9 21 59 PM" src="https://user-images.githubusercontent.com/1761197/85191609-5af24a00-b274-11ea-9464-42a9cdff053a.png">

It does not show up, both in the controls panel and in the docs page.
<img width="982" alt="Screen Shot 2020-06-19 at 9 30 19 PM" src="https://user-images.githubusercontent.com/1761197/85191634-6b0a2980-b274-11ea-8313-73d6f5dd49a4.png">

<img width="1044" alt="Screen Shot 2020-06-19 at 9 30 56 PM" src="https://user-images.githubusercontent.com/1761197/85191687-9a209b00-b274-11ea-94f5-e4bbccdefb92.png">

<img width="904" alt="Screen Shot 2020-06-19 at 9 34 56 PM" src="https://user-images.githubusercontent.com/1761197/85191729-c20ffe80-b274-11ea-8b9c-2fe3d2ac54b8.png">

Could this be because it is being imported from another package?: If so is there any solution? Thank you.

**Comment by shilman** [comment]
It’s because your story function does not accept an argument — see the big yellow warning in the Controls panel

**Comment by nnennajohn** [comment]
@shilman Can you please point me to somewhere in the doc that shows how to resolve it? I thought my stories.tsx looks exactly like the demo. I see the big yellow error. But clicking the link leads me to the docs where I followed it exactly, still it shows the same error.

**Comment by shilman** [comment]
Sorry, I misread your story example on my phone! The `BaseCard` story looks good to me, so I think it's probably the fact that you're importing the `Card` component from an external library.

I've updated the documentation to include your use case. Please let me know if this works for you:

https://github.com/storybookjs/storybook/blob/next/addons/controls/README.md#my-controls-arent-being-auto-generated-what-should-i-do

That said, we encourage colocating your stories alongside your components, (i.e. `import { Card, StyledComponentProps} from './Card'`) If that's an option for you, consider making the switch!

**Comment by nnennajohn** [comment]
Thanks so much @shilman. You are right. I think its because my stories are in its own package. Sadly, I can't move it, as it's intentionally structured that way. I found that just adding `SampleStory.args = { someSampleProp: '' }` generates the specified arg. I will def be loosing out on automatic arg generation. But I get all the other awesome stuff with Storybook 6. So still happy. 

Thanks again for helping me figure this out.

**Comment by shilman** [comment]
@nnennajohn so happy you got it working & thanks for your patience as we get all the pre-release issues ironed out!
