### ISSUE TITLE
MDX SyntaxError warnings in CRA TS Kitchen sink

### ISSUE THREAD

**Issue by RiaanWest** [storybookjs/storybook#11239]
**Describe the bug**
The example MDX stories in 6.0.0-beta.31 throw SyntaxError warnings. I've removed all empty lines between JSX blocks, which took care of some errors, but not all of them.

**To Reproduce**
1. Run `yarn install`
2. Run `yarn storybook`
3. See errors in terminal

**Expected behavior**
Storybook should start up without errors, as this is the official example project

**Screenshots**
![image](https://user-images.githubusercontent.com/67014/85126092-11324100-b22d-11ea-9821-1ddc47983b11.png)

**System:**
```
Environment Info:

  System:
    OS: macOS 10.15.5
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 12.6.0 - ~/.nvm/versions/node/v12.6.0/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v12.6.0/bin/npm
  Browsers:
    Chrome: 83.0.4103.106
    Edge: 83.0.478.54
    Firefox: 77.0.1
    Safari: 13.1.1
  npmPackages:
    @storybook/addon-a11y: 6.0.0-beta.31 => 6.0.0-beta.31
    @storybook/addon-actions: 6.0.0-beta.31 => 6.0.0-beta.31
    @storybook/addon-docs: 6.0.0-beta.31 => 6.0.0-beta.31
    @storybook/addon-knobs: 6.0.0-beta.31 => 6.0.0-beta.31
    @storybook/addon-links: 6.0.0-beta.31 => 6.0.0-beta.31
    @storybook/addons: 6.0.0-beta.31 => 6.0.0-beta.31
    @storybook/preset-create-react-app: ^3.0.0 => 3.1.1
    @storybook/react: 6.0.0-beta.31 => 6.0.0-beta.31
```

**Comment by shilman** [comment]
These projects are written and run inside our monorepo and is picking up some babel settings from the monorepo that make it work. However, I can confirm the problem as soon as you remove the project from our monorepo. We're in the process of moving all the examples OUT of the monorepo, so we'll probably take care of this as part of that project.

cc @gaetanmaisse @tooppaaa

**Comment by RiaanWest** [comment]
So just to make sure I understand: currently, this example project won't work separately, because it's relying on settings from the monorepo?

**Comment by RiaanWest** [comment]
I'm happy to say that as of rc-0, the problem has now been resolved. Thank you!
