### ISSUE TITLE
[v6.0.0-beta.31-32] camelCase ref key leads to blank page on click

### ISSUE THREAD

**Issue by lostdesign** [storybookjs/storybook#11245]
**Describe the bug**
Adding another storybook ref written in camelCase, will lead to the site not rendering anything once you click on that added storybook. Going back to the main sb doesn't fix it, a refresh is then necessary to display the main sb even.

**To Reproduce**
1. Add a ref at `main.js` as follows:
![Bildschirmfoto 2020-06-19 um 17 34 39](https://user-images.githubusercontent.com/5164617/85152327-28852480-b255-11ea-98ca-ba58188fa5dc.png)
2. Open main storybook
3. Click on a story of `camelCase`
4. Page now is blank, url will be `http://localhost:6001/?path=/story/camelCase_story--name`

**Expected behavior**
The site should just render normally and accept camelCase written refs. 

**Screenshots**
Breaking with camelCase ref
![camelCase-broken](https://user-images.githubusercontent.com/5164617/85152594-7ef26300-b255-11ea-94dd-55254319d18d.gif)
Working with lowercase ref
![lowercase-working](https://user-images.githubusercontent.com/5164617/85152296-1e632600-b255-11ea-9fb8-3bcbb4baeaa4.gif)

**System:**
![Bildschirmfoto 2020-06-19 um 17 53 26](https://user-images.githubusercontent.com/5164617/85152908-d85a9200-b255-11ea-809a-d10dbf5d1acf.png)

**Comment by lostdesign** [comment]
Isn't this also labeled wrong? I intended it to be a bug report.

**Comment by shilman** [comment]
@lostdesign it's not a bug until somebody actually confirms it as a bug. half our bug reports are configuration issues.

**Comment by shilman** [comment]
I think this was fixed, can you verify @lostdesign ?

https://github.com/storybookjs/storybook/pull/11541
