### ISSUE TITLE
Use SystemJS along with Storybook

### ISSUE THREAD

**Issue by abhijit945** [storybookjs/storybook#11258]
**Describe the bug**
Unable to load a SystemJS bundle in storybook. Already reported [here](https://github.com/storybookjs/storybook/issues/9979)

**To Reproduce**

* Use a regular story
* Add `config.output.libraryTarget = 'system';` to your `webpackFinal`
* Add `<script src="https://cdn.jsdelivr.net/npm/systemjs@latest/dist/system.min.js"></script>` to your `preview-head.html`

**Screenshots**
<img width="1122" alt="Screen Shot 2020-06-22 at 8 32 24 AM" src="https://user-images.githubusercontent.com/4908886/85293409-e92c2300-b462-11ea-8554-75da2b2770e1.png">

**System:**
Please paste the results of `npx -p @storybook/cli@next sb info` here.

```
Environment Info:

  System:
    OS: macOS 10.15.5
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 13.14.0 - ~/.nvm/versions/node/v13.14.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.5 - ~/Documents/Projects/node_modules/.bin/npm
  Browsers:
    Chrome: 83.0.4103.106
    Firefox: 77.0.1
    Safari: 13.1.1
  npmPackages:
    @storybook/addon-actions: ^5.3.19 => 5.3.19 
    @storybook/addon-centered: ^5.3.19 => 5.3.19 
    @storybook/addon-docs: ^5.3.19 => 5.3.19 
    @storybook/addon-jest: ^5.3.19 => 5.3.19 
    @storybook/addon-knobs: ^5.3.19 => 5.3.19 
    @storybook/addons: ^5.3.19 => 5.3.19 
    @storybook/cli: ^5.3.19 => 5.3.19 
    @storybook/components: ^5.3.19 => 5.3.19 
    @storybook/preact: ^5.3.19 => 5.3.19 
    @storybook/theming: ^5.3.19 => 5.3.19 

```

**Comment by abhijit945** [comment]
Nevermind, I found a solution to this for now. 
I used a mutation observer and added it to `preview-body.html`

```html
<div id="custom-root">
  <script>
    function handleScripts(list) {
      for (let item of list) {
        item.setAttribute('type', 'systemjs-module');
      }
    }
    var observer = new MutationObserver(function (mutations, me) {
      var scripts = document.body.getElementsByTagName('script');
      if (scripts.length) {
        handleScripts(scripts);
      }
    });
    observer.observe(document.body, {
      childList: true,
      subtree: true,
    });
  </script>
</div>

```

**Comment by sourceful-debarshi** [comment]
@abhijit945 I am facing the same issue, and the above fix is not working for me. Is it possible to connect with you?
