### ISSUE TITLE
storyshots-core Validation Error jest-preset-angular/preprocessor.js not found - Storybook 6.0.0-beta.27

### ISSUE THREAD

**Issue by chrisj-skinner** [storybookjs/storybook#11250]
**Describe the bug**
In an AngularV9 + Storybook 6.0.0-beta.27 env I receive a `Validation Error`

It appears `preprocessor.js` does not exist in jest-preset-angular

**To Reproduce**
1.  Setup at: https://github.com/storybookjs/storybook/tree/master/addons/storyshots/storyshots-core#configure-jest-for-angular
2. Run `ng test`
3. See error

**Expected behavior**
Tests to pass and shotshots to be created from stories

**Screenshots**
<img width="211" alt="Screen Shot 2020-06-20 at 22 14 05" src="https://user-images.githubusercontent.com/5794048/85216580-6f514800-b343-11ea-9e97-52c1db06255c.png">

**Code snippets**
```
Validation Error:

  Module <rootDir>/node_modules/jest-preset-angular/preprocessor.js in the transform option was not found.
```

**System:**
  System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
  Binaries:
    Node: 10.15.1 - /usr/local/bin/node
    npm: 6.14.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 83.0.4103.106
    Firefox: 76.0.1
    Safari: 13.0.4
  npmPackages:
    @storybook/addon-a11y: ^6.0.0-beta.27 => 6.0.0-beta.27 
    @storybook/addon-actions: ^6.0.0-beta.27 => 6.0.0-beta.27 
    @storybook/addon-controls: ^6.0.0-beta.27 => 6.0.0-beta.27 
    @storybook/addon-docs: ^6.0.0-beta.27 => 6.0.0-beta.27 
    @storybook/addon-jest: ^6.0.0-beta.27 => 6.0.0-beta.27 
    @storybook/addon-links: ^6.0.0-beta.27 => 6.0.0-beta.27 
    @storybook/addon-storyshots: ^6.0.0-beta.32 => 6.0.0-beta.32 
    @storybook/addon-viewport: ^6.0.0-beta.27 => 6.0.0-beta.27 
    @storybook/addons: ^6.0.0-beta.27 => 6.0.0-beta.27 
    @storybook/angular: ^6.0.0-beta.27 => 6.0.0-beta.27 
    @storybook/components: ^5.3.19 => 5.3.19 
    @storybook/storybook-deployer: ^2.8.6 => 2.8.6 
    @storybook/theming: ^5.3.19 => 5.3.19

**Comment by shilman** [comment]
What version of jest are you using? I think we require `jest@26` now

**Comment by chrisj-skinner** [comment]
@shilman 
I found by upgraded every plugin except storyshots (where we kept at beta-27) as well as configuring jest.config.ts `jest-present-angular` like so, worked.

```

globals: {
...
    'ts-jest': {
      ...
      astTransformers: [
        'jest-preset-angular/build/InlineFilesTransformer',
        'jest-preset-angular/build/StripStylesTransformer'
      ],
    },
  },
...
}
```
Current working package.json file

```
...
  "dependencies": {
    "@angular/animations": "~9.0.3",
    "@angular/common": "~9.0.3",
    "@angular/compiler": "~9.0.3",
    "@angular/core": "~9.0.3",
    "@angular/forms": "~9.0.3",
    "@angular/platform-browser": "~9.0.3",
    "@angular/platform-browser-dynamic": "~9.0.3",
    "@angular/router": "~9.0.3",
    "@ngrx/effects": "^9.2.0",
    "@ngrx/store": "^9.2.0",
    "@ngrx/store-devtools": "^9.2.0",
    "bowser": "^2.9.0",
    "ngrx-store-freeze": "^0.2.4",
    "node-sass": "^4.14.1",
    "rxjs": "~6.5.4",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-builders/jest": "^9.0.1",
    "@angular-devkit/build-angular": "~0.900.4",
    "@angular/cli": "~9.0.4",
    "@angular/compiler-cli": "~9.0.3",
    "@angular/language-service": "~9.0.3",
    "@babel/core": "^7.9.6",
    "@compodoc/compodoc": "^1.1.11",
    "@storybook/addon-a11y": "^6.0.0-beta.20",
    "@storybook/addon-actions": "^6.0.0-beta.20",
    "@storybook/addon-controls": "^6.0.0-beta.20",
    "@storybook/addon-docs": "^6.0.0-beta.20",
    "@storybook/addon-jest": "^6.0.0-beta.20",
    "@storybook/addon-links": "^6.0.0-beta.20",
    "@storybook/addon-storyshots": "6.0.0-beta.27",
    "@storybook/addon-viewport": "^6.0.0-beta.20",
    "@storybook/addons": "^6.0.0-beta.20",
    "@storybook/angular": "^6.0.0-beta.20",
    "@storybook/components": "^5.3.19",
    "@storybook/storybook-deployer": "^2.8.6",
    "@storybook/theming": "^5.3.19",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/jest": "^25.2.3",
    "@types/node": "^12.12.47",
    "codelyzer": "^5.1.2",
    "cypress": "^4.8.0",
    "husky": "^4.2.5",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "jest": "^26.0.1",
    "jest-cli": "^26.0.1",
    "jest-junit": "^10.0.0",
    "jest-preset-angular": "^8.2.0",
    "karma": "~4.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "lint-staged": "^10.2.9",
    "prettier": "2.0.5",
    "protractor": "~5.4.3",
    "storybook-addon-root-attribute": "^1.0.0",
    "storybook-addon-xd-designs": "^5.5.0",
    "ts-node": "~8.3.0",
    "tslint": "~5.18.0",
    "typescript": "~3.7.5",
    "wallaby-webpack": "^3.9.15"
  }
...
```

**Comment by shilman** [comment]
@Hypnosphi @SimenB @adover any help here?

**Comment by SimenB** [comment]
I haven't used angular since v1 days, so not much help I'm afraid. If a repository with a full repro was posted I might be able to take a look, but no promises.

(Currently on vacation, so 2 weeks until I can check, btw)
