### ISSUE TITLE
Storysource: Converting args spread into component current usage  

### ISSUE THREAD

**Issue by abbudao** [storybookjs/storybook#11252]
**Is your feature request related to a problem? Please describe.**
Storybook 6 has been awesome! 
Addon controls and using args made writing stories very streamlined and I've been loving it!
The dev experience of just spreading args on components is superb! 
The only drawback that I've perceived is how story source looks like; it always yields similar results, a source code that looks like:
```jsx
<Component {...args} />
```     

**Describe the solution you'd like**
I would like to convert the "args" spreading to a simple props assignment. Consider the example:
  ```tsx
import React from 'react';
import Component from 'components/Component';

type ComponentProps = {
  id: string;
  label: string;
  errorMessage?: string;
};

export default {
  title: 'Components/Component',
  component: Component,
};

export const Basic = (args: ComponentProps) => <Component {...args} />

Basic.args = {
  label: 'Label',
  id: 'name',
};
```
Story Source will show:
```jsx
<Component {...args} />
```
But this output would be way better:
```jsx
<Component id={id} label={label} />
```
This is particularly useful when the component has many optional props and you want to showcase some useful patterns, by providing only some of them.

**Describe alternatives you've considered**
You could have just written what you want to show on Story Source:
```jsx
export const Basic = ({id, label}: ComponentProps) => <Component id={id} label={label} />
```
And that's what I've been doing, but the Dev experience it's not as great as just spreading args.

**Are you able to assist bring the feature to reality?**
Yes, I can. But as this is my first time contributing, I would love to receive some guidance on things like where should I start.

**Additional context**
The feature should be opt-out by setting a parameter on a storybook configuration file.

**Comment by shilman** [comment]
Closing this as duplicate to #8342. Slightly different problem, but same solution, coming soon!
