### ISSUE TITLE
Arrays and objects in Storybook for web components

### ISSUE THREAD

**Issue by dj-neza** [storybookjs/storybook#11272]
### Bug or support request summary

Hi!
I'm trying to upgrade the Storybook of a Stencil Web components project from the storybook for html to the one for web components. I've managed to set up basic stories using the lit html as in the demo but I'm having a problem with the more advanced Prop types (e.g. arrays and objects). My question is - is this possible in storybook for web components and if so could an example be provided on how to do it? 

Ideally, I'd like to also use knobs for those properties.
- @storybook/web-components 5.3.19
- @storybook/addon-knobs 5.3.17

**Comment by jiulingxiaoxin** [comment]
I have the same problem. My components project was set up by using vue.js and echarts. I use objects and arrays as the props usually. But it's invalid when I set the props as object type.

**Comment by shilman** [comment]
Can you clarify your question with an example of something that isn't working for you, or better yet, something that works in `@storybook/html` and doesn't work in `@storybook/web-components`?

**Comment by dj-neza** [comment]
Hey!
The thing is that it doesn't work in basic html storybook (or at least I haven't found a good way to do it yet 😅) but I assumed it would be possible with the storybook for web components. To give an example, I have Stencil based web components that take in different props - I guess a good example is Date objects for a calendar component and an array with content for a tabs menu. For both of these I haven't been able to make them work in storybook/html but it would be awesome to know IF and HOW it might be possible in storybook/web-components. 
Essentially, what I'm saying is that I think storybook/web-components needs to be covered in the official documentation on the webpage, where these things are explained for other storybook versions. ☺️

**Comment by rjborba** [comment]
This is still a opened point for me. I could not find any way around it yet.
