### ISSUE TITLE
Scrollbar for toolbars doesn't work in 6.0 beta like it did in 5.3

### ISSUE THREAD

**Issue by domyen** [storybookjs/storybook#11283]
**Describe the bug**
When there is horizontal overflow, the toolbar shows unsightly system scroll bars that obfuscate the toolbar tabs and icons. This was not the case in 5.3 (see before:after screenshots below).

| 5.3 ([link](https://storybookjs.netlify.app/official-storybook/?path=/story/*))  | 6.0 beta ([link](https://next--storybookjs.netlify.app/official-storybook/?path=/undefined/undefined)) |
|---|---|
| ![image](https://user-images.githubusercontent.com/263385/85465814-3d282c00-b577-11ea-85ac-b805db103542.png)  | ![image](https://user-images.githubusercontent.com/263385/85465633-0225f880-b577-11ea-9216-8d4de11cc384.png)  |

**To Reproduce**
1. Go to the latest SB on `next` [here](https://next--storybookjs.netlify.app/official-storybook/?path=/undefined/undefined)
2. Resize the right hand side (Canvas) till you see horizontal scrollbars 
3. See that the horizontal scrollbars block the content

**Expected behavior**
The scrollbars behave like they did in 5.3 and do not obfuscate the content.

**System:**
This is a Storybook UI issue. It's reproducible by navigating to the above links in Chrome.

**Comment by shilman** [comment]
Huzzah!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-rc.9 containing PR #11579 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
