### ISSUE TITLE
addons-actions: option to return something

### ISSUE THREAD

**Issue by christophehurpeau** [storybookjs/storybook#11290]
**Is your feature request related to a problem? Please describe.**

We have stories with callbacks that should return Promise.

```
storiesOf('Some Form', module).add('Default', () => (
  <Form initialValues={{}} onSubmit={action('Submit')} />
));
```

Form onSubmit prop: `onSubmit: Promise<void>;`

**Describe the solution you'd like**
Option to specify a return value, either with a function or directly the value we want to return ?

```
storiesOf('Some Form', module).add('Default', () => (
  <Form initialValues={{}} onSubmit={action('Submit', { returnValue: Promise.resolve() )} />
));
```

```
storiesOf('Some Form', module).add('Default', () => (
  <Form initialValues={{}} onSubmit={action('Submit', { getReturnValue: (values) => Promise.resolve() )} />
));
```

I'm not sure about the naming

**Describe alternatives you've considered**

Allowing `onSubmit` return type to accept void.

**Are you able to assist bring the feature to reality?**
yes, I can open a PR if it's accepted

**Comment by Ponayobi** [comment]
Maybe try something like this?
`async (...args) => { action('Submit')(...args) }}`

**Comment by christophehurpeau** [comment]
I can open a PR if this proposal is approved ?

**Comment by shilman** [comment]
Why not just:

```js
const promiseAction = (msg) => {
  action(msg)();
  return Promise.resolve();
}

storiesOf('Some Form', module).add('Default', () => (
  <Form initialValues={{}} onSubmit={promiseAction('Submit')} />
));
```

**Comment by iamxyzby** [comment]
You can try this:
```js
const promiseAction = (msg) => (...args) => {
    action(msg)(...args)
    return Promise.resolve()
}

storiesOf('Some Form', module).add('Default', () => (
  <Form initialValues={{}} onSubmit={promiseAction('Submit1')} />
));

storiesOf('Some Form', module).add('Default', () => (
  <Form initialValues={{}} onSubmit={promiseAction('Other Submit')} />
));
```

**Comment by soullivaneuh** [comment]
@iamxyzby The workaround is working, but it would be great to have this automatically managed by the `argTypesRegex` configuration.

@christophehurpeau may we re-open this issue?

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if this is still relevant in SB 7.x.

**Comment by dominicfraser** [comment]
> Maybe try something like this? `async (...args) => { action('Submit')(...args) }}`

Using `@storybook/react` `^7.6.7` and encountered this same problem.

The `onClick` to our component is typed as `onClick: () => Promise<void>`.

To make this work we needed to do:

```tsx
const meta: Meta<typeof MyComponent> = {
  title: 'Global Navigation Fallback Card',
  component: MyComponent,
  args: {
    label: 'My Label',
    onClick: async (...args) => {
      action('on-click')(...args);
    },
  },
};

export default meta;
```

**Comment by CamJohnson26** [comment]
Yeah still an issue, and really annoying

**Comment by christophehurpeau** [comment]
Reopened here: https://github.com/storybookjs/storybook/discussions/31040
