### ISSUE TITLE
Beta 35: start-storybook not loading styles imported by preview.js

### ISSUE THREAD

**Issue by matheo** [storybookjs/storybook#11304]
**Describe the bug**

I have some CSS files imported at the end of `preview.js` and they doesn't seems to be loaded in the dev environment (`start-storybook`). Something changed around that after beta.28?

**Screenshots**
In the latest working build with `beta.32`, I'm able to see the imported CSS before the emotion ones:

![image](https://user-images.githubusercontent.com/260185/85629389-66a88c80-b637-11ea-9696-4bc1abc439f3.png)

but serving the latest `beta.35` I don't have my styles :(

![image](https://user-images.githubusercontent.com/260185/85629347-51cbf900-b637-11ea-8014-f991e183c276.png)

**System:**
```
Environment Info:

  System:
    OS: Linux 5.4 Ubuntu 20.04 LTS (Focal Fossa)
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 10.18.0 - ~/.nvm/versions/node/v10.18.0/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.14.2 - ~/.nvm/versions/node/v10.18.0/bin/npm
  Browsers:
    Chrome: 83.0.4103.106
    Firefox: 77.0.1
  npmPackages:
    @storybook/addon-a11y: 6.0.0-beta.35 => 6.0.0-beta.35 
    @storybook/addon-actions: 6.0.0-beta.35 => 6.0.0-beta.35 
    @storybook/addon-docs: 6.0.0-beta.35 => 6.0.0-beta.35 
    @storybook/addon-links: 6.0.0-beta.35 => 6.0.0-beta.35 
    @storybook/addon-viewport: 6.0.0-beta.35 => 6.0.0-beta.35 
    @storybook/addons: 6.0.0-beta.35 => 6.0.0-beta.35 
    @storybook/angular: 6.0.0-beta.35 => 6.0.0-beta.35 
```

**Comment by shilman** [comment]
@tmeasday @ndelangen something to do with composition?

**Comment by tmeasday** [comment]
Hmm, sort of doubt it, but could be?

**Comment by rvanlaar** [comment]
It seems I'm hitting this bug while working though the tutorial. https://www.learnstorybook.com/intro-to-storybook/react/en/get-started/

Installed  versions:
nodejs v12.18.0
yarn: 1.22.4
npm: 6.14.4
My package.json: https://gist.github.com/rvanlaar/db9b754d7ebd738f5deb931b83a16cb9

**Comment by ndelangen** [comment]
@matheo can you confirm the above?

**Comment by matheo** [comment]
@ndelangen nope
updated to `beta.38` and it doesn't work for me.
I will have to debug-webpack to see what changed around the CSS rules it seems.

**Comment by matheo** [comment]
@ndelangen I confirmed that webpack is loading the CSSs
but they are not being included in the iframe HTML :-?
I don't have idea of what's happening with Storybook's core :(

**Comment by ndelangen** [comment]
@shreyaghate02 This might be a good starting point for contributing?

**Comment by matheo** [comment]
@ndelangen it seems that my preview is only including the `base-preview-head.html`, the rest are `emotion` styles loaded dynamically. There's something we can do with webpack config to restore the styles imported from the `preview.js`?

**Comment by matheo** [comment]
Ok, I went through the commits and didn't find a relevant change
so I went back to my webpack config to compare the rules loading the CSS files.

I found this on my latest installation with rc2:
```
        { exclude: [],
          test: /\.css$/,
          use:
           [ { loader: 'raw-loader' },
             { loader: 'postcss-loader',
               options:
                { ident: 'embedded',
                  plugins: [Function: postcssPluginCreator],
                  sourceMap: false } } ] },
```
but I saw another defaults being set by `@storybook/core`,
and after modifying this config to fic the storybook defaults:
```
        { exclude: [],
          test: /\.css$/,
          use:
           [ { loader: 'style-loader' },
             { loader: 'css-loader', options: { importLoaders: 1 } },
             { loader: 'postcss-loader',
               options:
                { ident: 'postcss',
                  plugins: [Function: postcssPluginCreator],
                  sourceMap: false,
                  postcss: {} } } ] },
```
it worked!

Holy cow, I've tried to search who's setting this inside my node_modules but didn't find anything :scream: 
maybe Angular is able to add that rule :-?

**Comment by matheo** [comment]
yes, `@angular-devkit/build-angular` does that, I didn't know that it was able to do it!
```
    const rules = baseRules.map(({ test, use }) => ({
        exclude: globalStylePaths,
        test,
        use: [
            { loader: 'raw-loader' },
            {
                loader: 'postcss-loader',
                options: {
                    ident: 'embedded',
                    plugins: postcssPluginCreator,
                    sourceMap: cssSourceMap
                        // Never use component css sourcemap when style optimizations are on.
                        // It will just increase bundle size without offering good debug experience.
                        && !buildOptions.optimization.styles
                        // Inline all sourcemap types except hidden ones, which are the same as no sourcemaps
                        // for component css.
                        && !buildOptions.sourceMap.hidden ? 'inline' : false,
                },
            },
            ...use,
        ],
    }));
```
Nice to know tho
