### ISSUE TITLE
Composition: MDX pages don't get the appropriate Sidebar list items 

### ISSUE THREAD

**Issue by domyen** [storybookjs/storybook#11302]
**Describe the bug**
I'm composing [Storybook Design System](https://5ccbc373887ca40020446347-synmdrrwjj.chromatic.com/?path=/story/design-system-intro--page) into [LearnStorybook's own Storybook](https://5cf841a3f3e3d200208ffc74-hjwclwhfba.chromatic.com/?path=/story/@storybook/design-system_design-system-intro--page). However the sidebar UI of the composed Storybook does not match SDS when it should.

| Composed Storybook in LSB  | Original Storybook in SDS  |
|----|----|
| :x: ![image](https://user-images.githubusercontent.com/263385/85625719-e0da1080-b639-11ea-855c-683f57929aaa.png) | :white_check_mark: ![image](https://user-images.githubusercontent.com/263385/85625752-eafc0f00-b639-11ea-9999-ff8689efb3d9.png) |

**To Reproduce**

1. Go to [Storybook Design System](https://5ccbc373887ca40020446347-synmdrrwjj.chromatic.com/?path=/story/design-system-intro--page) that's published online
1. Look at the sidebar. Specifically, the yellow "document" icons for the DocPages
1. Now go to [LearnStorybook's own Storybook](https://5cf841a3f3e3d200208ffc74-hjwclwhfba.chromatic.com/?path=/story/@storybook/design-system_design-system-intro--page) published online
1. See that these aren't the same. When SDS is composed, we show the DocPages as regular stories instead of pages.

**Expected behavior**
I expect to see the same sidebar UI when I compose an external Storybook. DocPages should be rendered as Docpages.

shilman ndelangen do you know why this would happen?

**Comment by ndelangen** [comment]
Oof, I'm not sure, will have to investigate!

**Comment by ndelangen** [comment]
@shilman would you be able to be on a call tomorrow with me (my morning) dot see what is causing this diff:
<img width="319" alt="Screenshot 2020-07-13 at 17 57 35" src="https://user-images.githubusercontent.com/3070389/87326002-762e3d80-c532-11ea-83b6-b296a5dfcc98.png">
<img width="220" alt="Screenshot 2020-07-13 at 17 57 41" src="https://user-images.githubusercontent.com/3070389/87326006-775f6a80-c532-11ea-9172-d8c0a6e174e3.png">

I checked the generated json a bit, and I'm guessing it's some parameter | arg | global | config diff. But I'm not sure. Would love your assist.

**Comment by shilman** [comment]
@ndelangen i'm guessing this has to do with parameter normalization, where global parameters are now stored separately from component/story parameters, but i'd be happy to look at this together.

**Comment by ndelangen** [comment]
<img width="1791" alt="Screenshot 2020-07-13 at 18 20 42" src="https://user-images.githubusercontent.com/3070389/87328324-a0352f00-c535-11ea-9572-18d147a21110.png">

**Comment by shilman** [comment]
@tmeasday do you know what's up with this ☝️

**Comment by tmeasday** [comment]
@ndelangen initially when you load the outer storybook and it grabs the `/stories.json` there are no docs-only stories listed as we currently filter them out in `extract()` and thus Chromatic doesn't get them, so they don't end up in there. We need to figure that out on the Chromatic side I suppose.

As for the second problem (what happens when you browse to a story) I don't think it is likely anything to do with normalization. AFAICT the display in the LHS is fairly simply associated with `parameters.docsOnly` which is set at the story level: 

<img width="301" alt="image" src="https://user-images.githubusercontent.com/132554/87385320-1f337180-c5e1-11ea-90c6-7bbdca26dd6e.png">

I can't see why it wouldn't be the same `SET_STORIES` event emitted in both cases (embedded vs browsed to directly). I can't see any possible way for them to be different. I would expect the handling in the refs code is likely what's going on there.

**Comment by ndelangen** [comment]
Thanks to @shilman I now know how to fix 1 of these 2 issues:
Once the page type stories are added, they are still rendered incorrectly:
<img width="332" alt="Screenshot 2020-07-14 at 13 01 09" src="https://user-images.githubusercontent.com/3070389/87418816-b1804900-c5d2-11ea-819e-4209e7a92123.png">

**Comment by ndelangen** [comment]
To solve the other problem, we should probably start using this:
https://github.com/storybookjs/storybook/blob/1d08802a5e92db6edb83003beb13a08253accf93/lib/client-api/src/story_store.ts#L536-L546

over raw `.extract()`, WDYT @shilman @tmeasday ?

I assume we use `.extract()` in chromatic somewhere? @ghengeveld ?

**Comment by ndelangen** [comment]
The above should also be changed in the `sb extract` command

**Comment by shilman** [comment]
@ndelangen I think that makes sense. The reason I didn't implement this for more different consumers (e.g. storyshots, chromatic) was because i didn't understand the impact and didn't want to break anything. and i still don't understand the impact, but i think it sounds reasonable provided the calling code is updated to deal with those docsOnly stories.

**Comment by shilman** [comment]
Whoopee!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-rc.5 containing PR #11537 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Jeepers creepers!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-rc.13 containing PR #11584 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by hipstersmoothie** [comment]
I'm still seeing this issue on 6.1.x

**Comment by hipstersmoothie** [comment]
MDX only stories from the storybook work but not from the composed storybook

![Screen Shot 2020-12-01 at 4 34 14 PM](https://user-images.githubusercontent.com/1192452/100812944-0fcb8e00-33f3-11eb-93c2-eec441ad25a2.png)

**Comment by shilman** [comment]
@ndelangen @ghengeveld did this regress with the sidebar refactor?

**Comment by shilman** [comment]
We want to address this in 6.3. If you want to contribute to Storybook, we'll prioritize PR review for any fixes here. And if you'd like any help getting started, please jump into the #support channel on our Discord: https://discord.gg/storybook

**Comment by zavlalayan** [comment]
Hi,
I did a small research and found out that in [Sidebar component](https://github.com/storybookjs/storybook/blob/b9aa7416fcd976ae48936413e8cd5e209c883e1e/lib/ui/src/components/sidebar/Sidebar.tsx#L103) the [collapseDocsOnlyStories method](https://github.com/storybookjs/storybook/blob/7472450a8391d0aaf5ee34dc8545d3eb48ce7d2a/lib/ui/src/components/sidebar/data.ts#L79-L85) removes leaf items that have only docs. But it is called only on storybook_internal stories, not the ref ones.
It causes the issue that in storybook composition there are 'Page' items.

**Comment by ndelangen** [comment]
@zavlalayan can you open a PR with a fix?

**Comment by atflick** [comment]
Not sure if this is related, but when I am developing I get links to all stories on a page and when it is built and deployed the sidebar only shows links to the pages.  Making you scroll down to what you want vs. having the nice jump links.  I'm using mdx stories

**when developing:**
![image](https://user-images.githubusercontent.com/18269370/129399223-293f9a14-59fe-4de3-a2fe-e026258cca31.png)

**this is built:**
![image](https://user-images.githubusercontent.com/18269370/129399015-e7bca38a-b685-4b92-aee0-67a58c01e767.png)

this is what my `Forms.stories.mdx` looks like essentially:
```mdx
<Meta title="Styleguide/Forms" />

# Forms
---

## Inputs
<Story name='Inputs'>
  {{
    components: { Inputs },
    template: '<Inputs />'
  }}
</Story>

## Selects
<Story name='Selects'>
  {{
    components: { Selects },
    template: '<Selects />'
  }}
</Story>

## Checkboxes
<Story name='Checkboxes'>
  {{
    components: { Checkboxes },
    template: '<Checkboxes />'
  }}
</Story>

## Radios
<Story name='Radios'>
  {{
    components: { Radios },
    template: '<Radios />'
  }}
</Story>

## Layout
Vertical layout is preferred and should be the standard, however there are times when horizontal may make more sense.

<Story name='Layout'>
  {{
    components: { Layout },
    template: '<Layout />'
  }}
</Story>

## Validation

<Story name='Validation'>
  {{
    components: { Validation },
    template: '<Validation />'
  }}
</Story>

```
