### ISSUE TITLE
[v6.0.0-beta.23-36] Selecting story in manager updates URL but does not display story in preview (statically built storybook only)

### ISSUE THREAD

**Issue by chrislopresto** [storybookjs/storybook#11308]
**Describe the bug**
After a **statically built Storybook** loads and displays a story, selecting a different story in the manager sidebar does not display the story in the preview pane.

**To Reproduce**
I do not have a standalone repro, but I'm happy to assist, debug locally, etc.

1.  Build static storybook with `yarn build-storybook`
2. Open the static storybook index.html file in a browser. The first story will display properly in the preview pane.
3. Select a different story. The URL will update but the story is not displayed in the preview pane.

**Expected behavior**
Selecting a story in the manager sidebar should display it in the preview pane.

**Screenshots**

![subsequent-stories](https://user-images.githubusercontent.com/93691/85663595-430d3280-b687-11ea-8f97-7853649d51c7.gif)

**Code snippets**
N/A

**System:**

```
Environment Info:

  System:
    OS: macOS 10.15.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Binaries:
    Node: 10.19.0 - ~/.nodenv/versions/10.19.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.10.3 - ~/workspace/bubble-ui/node_modules/.bin/npm
  Browsers:
    Chrome: 83.0.4103.116
    Firefox: 77.0.1
    Safari: 13.1.1
  npmPackages:
    @storybook/addon-actions: 6.0.0-beta.36 => 6.0.0-beta.36 
    @storybook/addon-knobs: 6.0.0-beta.36 => 6.0.0-beta.36 
    @storybook/addon-links: 6.0.0-beta.36 => 6.0.0-beta.36 
    @storybook/addons: 6.0.0-beta.36 => 6.0.0-beta.36 
    @storybook/cli: 6.0.0-beta.36 => 6.0.0-beta.36 
    @storybook/react: 6.0.0-beta.36 => 6.0.0-beta.36 
```

**Additional context**

* **Only affects statically built storybooks. Development mode works fine.**
* We have experienced this issue in Storybook 6 betas 23, 32, 33, and 36.
* Opening the storybook at its root path – `/index.html` – redirects to the first story – `/index.html?path=/story/button--button` – which is properly displayed.  
* After the storybook is loaded, selecting a different story in the manager sidebar updates the URL – e.g. `/index.html?path=/story/menu--menu` – but that story is not displayed.
* Refreshing the browser with a fully specified story URL – e.g. `/index.html?path=/story/menu--menu` – properly displays that story. Subsequent story navigation does not work, as described above.
* No manager or preview events are logged when selecting subsequent stories

**Comment by tmeasday** [comment]
Thanks for the report @chrislopresto. 

I tried reproducing w/ https://github.com/chromaui/storybook-template-react but I didn't see the problem. Can you quickly try you steps there (I think I followed them but you know how it is)?

When you select a story, the manager should emit `setCurrentStory` via [this file](https://github.com/storybookjs/storybook/blob/next/lib/ui/src/components/preview/preview.tsx#L156-L162). It looks like that event is either not being emitted or not being received in the preview. Perhaps you could try debugging those lines I posted?

**Comment by chrislopresto** [comment]
Got my Storybook dev environment up (thanks @ndelangen!) and verified that this problem is _NOT_ with Storybook. Closing this issue. Thanks for the help.

**Comment by chrislopresto** [comment]
@tmeasday Turns out the problem was somehow caused by resolving multiple react|react-dom versions.

**Before - Story loading broken**

```
> yarn list react                  
yarn list v1.22.4
├─ @storybook/addon-actions@6.0.0-beta.36
│  └─ react@16.13.1
├─ @storybook/api@6.0.0-beta.36
│  └─ react@16.13.1
├─ @storybook/components@6.0.0-beta.36
│  └─ react@16.13.1
├─ @storybook/ui@6.0.0-beta.36
│  └─ react@16.13.1
└─ react@16.8.6
✨  Done in 0.89s.
```

**After - Story loading fixed**

_package.json_

```json
"resolutions": {
  "react": "~16.8.0",
  "react-dom": "~16.8.0"
},
```

```
 yarn list react
yarn list v1.22.4
└─ react@16.8.6
```

**Comment by tmeasday** [comment]
Uggh, thanks yarn!
