### ISSUE TITLE
Regression in babel transpilation

### ISSUE THREAD

**Issue by bard** [storybookjs/storybook#11312]
Same as #11045, which was closed as fixed. I re-tested under `beta.36`, same issue is present.

**Describe the bug**

The following transpiled fine in 5.x:

```ts
export class ClassWithTranspilationIssues {
  constructor(private configuration: any = { foo: 'bar' }) { }

  printConfigParameter(): void {
    console.log(this.configuration.foo);
  }
}
```

It no longer transpiles correctly with Storybook 6:

```ts
new ClassWithTranspilationIssues().printConfigParameter() // => Unexpected error: TypeError: Cannot read property 'foo' of undefined
```

**To reproduce:**

- clone the minimal repro https://github.com/bard/storybook-6-babel-regression
- run `yarn && yarn storybook`
- storybook opens
- notice the absence of the `Button` story
- open the web developer console to see the error message

**Expected behavior**

Constructor parameters with default values should be transpiled correctly.

**System:**

```
  System:
    OS: Linux 5.7 Arch Linux
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
  Binaries:
    Node: 14.4.0 - /tmp/yarn--1593089574779-0.009958780001808165/node
    Yarn: 1.22.4 - /tmp/yarn--1593089574779-0.009958780001808165/yarn
    npm: 6.14.5 - /usr/sbin/npm
  Browsers:
    Firefox: 77.0.1
  npmPackages:
    @storybook/addon-actions: ^6.0.0-beta.36 => 6.0.0-beta.36 
    @storybook/addon-links: ^6.0.0-beta.36 => 6.0.0-beta.36 
    @storybook/addons: ^6.0.0-beta.36 => 6.0.0-beta.36 
    @storybook/cli: ^6.0.0-beta.36 => 6.0.0-beta.36 
    @storybook/preset-create-react-app: ^3.0.0 => 3.0.0 
    @storybook/react: ^6.0.0-beta.36 => 6.0.0-beta.36 
```

**Additional context**

The issue is related to the order in which babel plugins run. I fixed this locally in `storybook/lib/core/src/server/common/babel.js`:

The clue was in https://github.com/babel/babel/pull/8682#issuecomment-420408858

**Comment by shilman** [comment]
@bard you need to upgrade to @storybook/preset-create-app@3.0.1 or greater

**Comment by bard** [comment]
Sorry @shilman, I had missed that bit.

The code base where I encountered the problem does not use create-react-app (the minimal repro did so just for ease of reproducing). Unfortunately, using @storybook/preset-create-react-app in this code base causes a cascade of parsing errors.

With the regression being just about TypeScript transpilation, wouldn't this be more properly addressed outside of a preset specific to create-react-app?

**Comment by bard** [comment]
I hacked around this in the code base I'm working. Here's the summary in case someone finds this through a search.

- If your project was created with create-react-app and you're using `@storybook/preset-create-react-app`, you shouldn't need to worry about anything, because project and Storybook will be using compatible webpack configurations.
- If you're adding Storybook to an existing project with a custom webpack config, you might run into situations where code transpiles fine for your project but not for Storybook, due to Storybook's defaults differing for your custom webpack config.
- This may be especially insidious if your project is stuck with ts-loader because e.g. your project won't run with babel-loader due to `--isolatedModules`.
- The following hack in `.storybook/main.js` fixed things in my case. It discards Storybook's default rules, except for MDX ones, replaces them with local rules.

```js
module.exports = {
    stories: [
        '../src/**/*.stories.tsx'
    ],
    addons: [
        '@storybook/addon-essentials'
    ],
    webpackFinal: async config => {
    
        const storybookWebpackMdxRules = config.module.rules.filter(r => {
            return (
                r.test.test('example.mdx') ||
                r.test.test('example.stories.mdx')
            )
        })

        config.module.rules = [
            ...storybookWebpackMdxRules,
            ...require('../webpack.config').module.rules
        ]

        return config
    }
}
```

**Comment by shilman** [comment]
When Storybook runs with `preset-create-react-app` it discards nearly all of Storybook's settings and replaces them with CRA's, so addressing Typescript issues in `preset-cra` is necessary.

**Comment by shilman** [comment]
cc @mrmckeb about the workaround ☝️

**Comment by mrmckeb** [comment]
Yes, Storybook will never match a project's Webpack config unless the user sets it to. So you might be unlucky in some cases and you'll need to tweak Storybook to match your local config... the more we add to the base config, the more likely users are to hit compatibility issues.

I think we need to improve the story here, but I'm not sure how right now... something to think about for v7.

**Comment by DanWahlin** [comment]
I'm seeing this issue as well with Storybook 6.0.0-rc.13 with `@storybook/preset-create-react-app` 3.1.4. 

I don't have any local webpack rules defined so I'm not sure what else to change there. Any ideas?

**Comment by shilman** [comment]
@DanWahlin You can look at Storybook's runtime setup with `yarn storybook --debug-webpack` which shows the final weback configuration Storybook is using, including `babel-loader` configs. Maybe that will help you narrow it down? If you're stuck, post a repro and we'll try to look into it.

**Comment by DanWahlin** [comment]
Well - deleting node_modules and package-lock.json to try fixing the other issue I mentioned (#11633) seems to have fixed this one. No idea what changed (which is frustrating given the time I spent trying to debug it) but for now I'm just happy it's working as expected. :-)

**Comment by shilman** [comment]
Hahaha. "Did you try turning it off and turning it back on again?"

We've seen a bunch of yarn/npm bugs like this in the past year. I'm hoping [simplifications to our dependency structure](https://github.com/storybookjs/storybook/pull/11628) will help improve this in future releases...

**Comment by DanWahlin** [comment]
I'll definitely have to "turn it off and back on again" next time I hit something like that. :-) Managing dependencies is definitely tough - so many packages out there using packages (which use packages.....and on and on).

**Comment by bard** [comment]
> Yes, Storybook will never match a project's Webpack config unless the user sets it to. So you might be unlucky in some cases and you'll need to tweak Storybook to match your local config... the more we add to the base config, the more likely users are to hit compatibility issues.
> 
> I think we need to improve the story here, but I'm not sure how right now... something to think about for v7.

@mrmckeb It might be enough to qualify the "zero-configuration TypeScript support" statement. In my case, it led me down the thought route: _It supports TypeScript with zero config → it's not working → so it must be a bug with my configuration → debug → still not working → it might be a bug with Storybook → debug_. It's obvious in retrospect that my app and Storybook are two different projects with distinct bundling configurations, but when you make one of the bundling configurations almost disappear, it's very easy to imagine some automatic integration where there is none.

The actual story would be:

> Your code is bundled once for your app using your webpack config, and again for Storybook using its webpack config. If you're using create-react-app, those configurations are already compatible. If not, you might need a little work to make them compatible. As a nuclear hack, you might import your app's webpack config in your Storybook's webpack config.

Granted, it needs better writing form, but as long as the information is there, I think it would be enough.
