### ISSUE TITLE
outdated react-textarea-autosize dep. causes Error: Invalid hook call.

### ISSUE THREAD

**Issue by antoniosZ** [storybookjs/storybook#11318]
**Describe the bug**
Please note this bug is for the **next/v6**
```
"@storybook/web-components": "^6.0.0-beta.36"
"@storybook/addon-controls": "^6.0.0-beta.36",
"@storybook/addon-docs": "^6.0.0-beta.36",
```

a web components typescript project, with args + controls for a text type and default text value throws
`Error: Invalid hook call. Hooks can only be called inside of the body of a function component.`
as described here
https://github.com/Andarist/react-textarea-autosize/issues/273

I was able to "fix" this by forcing storybook to use the latest version of "react-textarea-autosize"
by installing
https://www.npmjs.com/package/npm-force-resolutions
and setting
```json
"resolutions": {
  "react-textarea-autosize": "^8.1.1"
}
```

instead of the required `react-textarea-autosize": "^8.0.1"`.

I believe, updating your dependencies of `react-textarea-autosize` to use the latest version (8.1.1) should fix this.

**To Reproduce**
1. create web components typescript project
1. use args + controls for a text type
1. set a default arg text value

**Expected behavior**
it should render the text area properly

**Comment by shilman** [comment]
Gadzooks!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-beta.37 containing PR #11319 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by nkov** [comment]
I had this issue even on latest `react-textarea-autosize` in my dependency tree and was able to resolve by removing `node_modules/` and `package-lock.json` and reinstalling
