### ISSUE TITLE
Docs don't render PropTypes arrays of primitives in shapes correctly

### ISSUE THREAD

**Issue by christofflueck** [storybookjs/storybook#11311]
**Describe the bug**
When using an array of strings or numbers as a property in a shape the docs render it as "unknown[]"

**To Reproduce**
1. Create a Component with the following code:
```javascript
import PropTypes from 'prop-types';
import React from 'react';

export const Test = (props) => {
  return <span>Test</span>;
};

Test.propTypes = {
  a: PropTypes.shape({
    not_working: PropTypes.arrayOf(PropTypes.number),
  }),
  b: PropTypes.shape({
    working: PropTypes.arrayOf(PropTypes.shape({p: PropTypes.string})),
  }),
};
```

2. Create a Story with the following content:
```javascript
import React from 'react';

import {Test} from './Test';

export default {
  component: Test,
  title: 'Test Story',
  excludeStories: /^_.*$/,

  parameters: {
    component: Test,
    componentSubtitle: '',
    notes: '',
  },
};

export const Default = () => {
  return <Test />;
};
```

**Expected behavior**
The prop should get rendered as "object[]" and the drop down should display
`{ not_working: string[] }`

**Screenshots**
![image](https://user-images.githubusercontent.com/58776530/85712410-98c5f700-b6e8-11ea-961b-ee3f00f6e102.png)

**System:**
`
Environment Info:

  System:
    OS: Windows 7 6.1.7601
    CPU: (4) x64 Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
  Binaries:
    Node: 12.16.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    @storybook/addon-actions: ^5.3.19 => 5.3.19
    @storybook/addon-docs: ^5.3.19 => 5.3.19
    @storybook/addon-links: ^5.3.19 => 5.3.19
    @storybook/addon-storyshots: ^5.3.19 => 5.3.19
    @storybook/addons: ^5.3.19 => 5.3.19
    @storybook/preset-create-react-app: ^2.1.2 => 2.12
    @storybook/react: ^5.3.19 => 5.3.19
`

**Comment by vanessayuenn** [comment]
Hi! I am going through and cleaning up old issues in the repo. We just shipped a ton of improvements in Storybook 7.0, and I suspect this bug might be fixed already. Can you please try it out? If this issue persists with the latest version, please open a new bug report with a 7.x reproduction. Thank you so much! 🙏🏼
