### ISSUE TITLE
Add version=$VERSION for package composition

### ISSUE THREAD

**Issue by tmeasday** [storybookjs/storybook#11321]
When loading a composed Storybook based on a `package.json:storybook.url`, append a `version=${package.json:version}` query parameter.

(This currently won't do anything but it would be good to get it in before the RC in case it causes problems. I don't think it will, but you never know!)

**Comment by ndelangen** [comment]
Refs are currently configured with their 'base' path:
`https://example.com` rather then their full path`https://example.com/iframe.html`.

if I want to add some query parameter, I need to store that on the ComposedRef object; and then append it in the IframesRenderer. WDYT @tmeasday ?

**Comment by tmeasday** [comment]
@ndelangen that sounds ok although won't we need to also do the appending in the `fetch`-es in `refs.js` (e.g. for `/stories.json`?)

**Comment by ndelangen** [comment]
yeah that's right

**Comment by shilman** [comment]
Boo-yah!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-beta.46 containing PR #11447 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
