### ISSUE TITLE
api.getCurrentStoryData return invalid FileName

### ISSUE THREAD

**Issue by ccpu** [storybookjs/storybook#11335]
**Describe the bug**

Assuming that all of the stories are in a folder named `stories` under the root of the application; using `../stories/*.stories.[tj]sx` matcher in `main.js` will cause storybook to ignore the folder name and return the file path like `./first.stories.tsx` but it should be `./stories/first.stories.tsx`. this happens when having a path in the matcher, so `../**/*.stories.[tj]sx` will return the correct path.

**To Reproduce**
Steps to reproduce the behaviour:
1. `git clone -b fileName-propblem --single-branch https://github.com/ccpu/storybook-addon-typescript-boilerplate.git`
2. Run storybook
3. Click on camerashot icon in toolbar
4. Look the message in the console

**Expected behaviour**
To return the story file path relative to the root of the application.

**Comment by ndelangen** [comment]
@ccpu Is this still an issue in storybook 7.0 beta with storyStoreV7 on by default? I suspect not.
