### ISSUE TITLE
Addon order not respected

### ISSUE THREAD

**Issue by elie222** [storybookjs/storybook#11359]
**Describe the bug**

The order of the addons I've added do not appear in the expected order.

```ts
module.exports = {
  stories: ['../src/**/*.stories.tsx'],
  addons: [
    '@storybook/preset-create-react-app',
    '@storybook/addon-actions/register',
    '@storybook/addon-knobs/register',
    '@storybook/addon-notes/register',
    '@storybook/addon-links/register',
    '@storybook/addon-storysource',
  ],
};
```

![image](https://user-images.githubusercontent.com/3090527/86059782-1e8cce00-ba6c-11ea-8ef5-e91ab84b3bac.png)

**To Reproduce**

Use this for `main.js`:

```ts
module.exports = {
  stories: ['../src/**/*.stories.tsx'],
  addons: [
    '@storybook/preset-create-react-app',
    '@storybook/addon-actions/register',
    '@storybook/addon-knobs/register',
    '@storybook/addon-notes/register',
    '@storybook/addon-links/register',
    '@storybook/addon-storysource',
  ],
};
```

**Expected behavior**
Storysource should be the last tab. Instead it's the first.

**Screenshots**
![image](https://user-images.githubusercontent.com/3090527/86059782-1e8cce00-ba6c-11ea-8ef5-e91ab84b3bac.png)

**Code snippets**

**System:**

Environment Info:

  System:
    OS: macOS 10.15.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Binaries:
    Node: 12.18.1 - ~/.nvm/versions/node/v12.18.1/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v12.18.1/bin/npm
  Browsers:
    Chrome: 83.0.4103.116
    Firefox: 76.0.1
    Safari: 13.1.1
  npmPackages:
    @storybook/addon-actions: ^5.3.19 => 5.3.19 
    @storybook/addon-knobs: ^5.3.19 => 5.3.19 
    @storybook/addon-links: ^5.3.19 => 5.3.19 
    @storybook/addon-notes: ^5.3.19 => 5.3.19 
    @storybook/addon-storysource: ^5.3.19 => 5.3.19 
    @storybook/addons: ^5.3.19 => 5.3.19 
    @storybook/preset-create-react-app: ^2.1.1 => 2.1.1 
    @storybook/react: ^5.3.19 => 5.3.19

**Additional context**

**Comment by shilman** [comment]
closing as dupe to #9819, fixed in 6.0
