### ISSUE TITLE
isChromatic error when building Storybook

### ISSUE THREAD

**Issue by atan4** [storybookjs/storybook#11356]
**Describe the bug**
I receive an error when building storybook `npm run storybook` even though I certainly do not have `isChromatic` installed in any capacity in my app. The same thing started happening to my coworkers as well. The error only goes away when i go to `node_modules/@storybook/ui/dist/components/layouts/layouts.stories.js` and comment out the two lines related to `isChromatic`.

**To Reproduce**
1. Use `@storybook/react v5.3.19`
2. `npm run storybook` and the error appears within seconds

**Expected behavior**
Storybook should successfully build

**Screenshots**
<img width="595" alt="Screen Shot 2020-06-29 at 5 03 30 PM" src="https://user-images.githubusercontent.com/14955150/86055944-a18d3480-ba2a-11ea-8b75-0fc423c3a096.png">

**Code snippets**
`ERROR in ./node_modules/@storybook/ui/dist/components/layout/layout.stories.js
Module not found: Error: Can't resolve 'storybook-chromatic/isChromatic' in '/Users/adriannatan/Documents/teampay/app/node_modules/@storybook/ui/dist/components/layout'
 @ ./node_modules/@storybook/ui/dist/components/layout/layout.stories.js 41:19-61
 @ . sync stories\.jsx?$
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/config.js (webpack)-hot-middleware/client.js?reload=true&quiet=true`

**System:**
Please paste the results of `npx -p @storybook/cli@next sb info` here.

`Environment Info:

  System:
    OS: macOS Mojave 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
  Binaries:
    Node: 12.10.0 - ~/.nvm/versions/node/v12.10.0/bin/node
    npm: 6.14.5 - ~/.nvm/versions/node/v12.10.0/bin/npm
  Browsers:
    Chrome: 83.0.4103.116
    Firefox: 68.0.2
    Safari: 13.1.1
  npmPackages:
    @storybook/addon-a11y: ^5.2.6 => 5.3.19
    @storybook/addon-actions: ^5.2.6 => 5.3.19
    @storybook/addon-knobs: ^5.2.6 => 5.3.19
    @storybook/addon-links: ^5.2.6 => 5.3.19
    @storybook/addon-notes: ^5.2.6 => 5.3.19
    @storybook/addon-options: ^5.3.3 => 5.3.19
    @storybook/addon-viewport: ^5.2.6 => 5.3.19
    @storybook/addons: ^5.2.6 => 5.3.19
    @storybook/react: ^5.2.6 => 5.3.19
    @storybook/theming: ^5.2.6 => 5.3.19
`

**Comment by shilman** [comment]
This looks like a configuration issue. I'd guess your storybook is configured to load stories from `node_modules` and is loading Storybook's own stories, which use Chromatic. Can you make your `stories` glob in `main.js` more specific?

**Comment by ndelangen** [comment]
Please don't include stories from within `node_modules`.
