### ISSUE TITLE
Migration from addon-info to addon-docs

### ISSUE THREAD

**Issue by ginaperez-kubra** [storybookjs/storybook#11355]
**Describe the bug**
I haven't found documentation on how to migrate from addon-info to addon-docs without using MDX. Right now, I have a `config.js` file using `withInfo` and `infoAddon` from addon-info. Are there equivalent functions to use with addon-docs? Or is there a different way to write this with addon-docs?

My full code snippet is below. 

**Code snippets**
```
import { configure, addDecorator, setAddon } from '@storybook/react';
import { withInfo, infoAddon } from '@storybook/addon-info';
import '../src/sass/index.scss';
import '../stories/demo.scss';
import '../src/sass/storybook.scss';
import { withA11y } from '@storybook/addon-a11y';

setAddon(infoAddon);
addDecorator(withInfo({
  header: true, // Toggles display of header with component name and description
  inline: true, // Displays info inline vs click button to view
  source: true // Displays the source of story Component
}));
addDecorator(withA11y);


// Load either typescript or javascript stories
const req = require.context('../stories', true, /\.story\.(js|tsx)$/);

function loadStories() {
  req.keys().forEach((filename) => req(filename));
}

configure(loadStories, module);

**Comment by shilman** [comment]
When you install addon-docs, it automatically installs a [DocsPage](https://medium.com/storybookjs/storybook-docspage-e185bc3622bf) which is the zero-config replacement for `addon-info`. Is that showing up for you?

**Comment by ginaperez-kubra** [comment]
@shilman It is not showing up. I installed addon-docs and when I started it up, it just showed the loading screen with this error in the console `Warning: Failed prop type: Invalid prop `type` of type `symbol` supplied to `TableComponent`, expected `function`.`

The only way it would compile is if I commented out all the code above from `setAddon(infoAddon)` to `addDecorator(witha11y);` and everything between. But then of course, the only thing left rendering is the components themselves and nothing else.

**Comment by shilman** [comment]
First time I've heard about that error. Try removing that config file and creating the following two files:

```js
// .storybook/main.js
module.exports = {
  stories: ['../stories/**/*.stories.(js|tsx)'],
  addons: ['@storybook/addon-docs', '@storybook/addon-a11y'],
}
```

```js
// .storybook/preview.js
import '../src/sass/index.scss';
import '../stories/demo.scss';
import '../src/sass/storybook.scss';
```
