### ISSUE TITLE
addon-docs: "Show code" feature becomes useless in version 6

### ISSUE THREAD

**Issue by jayarjo** [storybookjs/storybook#11367]
_Show code_ feature of `addon-docs`, is not useful for stories using new, concise syntax involving `args`:

![Screen Shot 2020-06-30 at 10 36 49 PM](https://user-images.githubusercontent.com/150075/86164037-31fa7080-bb22-11ea-9cd2-8cd20253b06b.png)

Basically makes the whole thing useless, since we will have to either not use it at all, or write full stories manually.

I think it should somehow manage to show a resolved snippet instead, with args expanded. And not the story, but rather a component only.

**Comment by shilman** [comment]
Please upgrade to the latest beta that contains this change: https://github.com/storybookjs/storybook/pull/11332

**Comment by jayarjo** [comment]
Awesome!
