### ISSUE TITLE
ability to set default addon tab per stories module

### ISSUE THREAD

**Issue by jayarjo** [storybookjs/storybook#11375]
Would be great to have a way to set default addon panel. For some stories actions to be default, for others it'd better be controls, and then there might be several additional addons enabled too.

Something like `activeAddonTab` as one of the options in default export would do.

**Comment by shilman** [comment]
It looks like such a thing already exists:

https://github.com/storybookjs/storybook/blob/next/examples/official-storybook/stories/addon-a11y/base-button.stories.js#L10-L12

**Comment by jayarjo** [comment]
Awesome!
