### ISSUE TITLE
Getting "Cannot use import statement outside a module" with MDX files running with Jest

### ISSUE THREAD

**Issue by ajkl2533** [storybookjs/storybook#11376]
**Describe the bug**
When I add MDX documentation files into my Storybook and run Storyshots with Jest I'm getting `SyntaxError: Cannot use import statement outside a module` for each of loaded MDX.

**Expected behavior**
Console should be without errors

**Code snippets**
```
console.warn
    Unexpected error: SyntaxError: Cannot use import statement outside a module

      at Object.warn (node_modules/@storybook/client-logger/dist/index.js:53:73)
      at node_modules/@storybook/core/dist/client/preview/loadCsf.js:110:34
          at Array.forEach (<anonymous>)
      at node_modules/@storybook/core/dist/client/preview/loadCsf.js:103:20
          at Array.forEach (<anonymous>)
      at node_modules/@storybook/core/dist/client/preview/loadCsf.js:102:12
      at ConfigApi.configure (node_modules/@storybook/client-api/dist/config_api.js:27:7)
```

```js
//jest.config.js

module.exports = {
  roots: ['./src'],
  setupFilesAfterEnv: ['./jest.setup.ts'],
  moduleFileExtensions: ['js', 'ts', 'tsx', 'json'],
  testPathIgnorePatterns: ['node_modules/'],
  transform: {
    '^.+\\.tsx?$': 'ts-jest',
    '^.+\\.mdx?$': '@storybook/addon-docs/jest-transform-mdx',
  },
  testMatch: ['./**/*.(test).(ts|tsx)'],
  moduleNameMapper: {
    '\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$':
      'identity-obj-proxy',
  },
};
```

```js
// main.ts

module.exports = {
  stories: ['../src/**/*.stories.@(tsx|jsx|mdx)'],
  addons: ['@storybook/addon-actions', '@storybook/addon-docs'],
  typescript: {
    check: false,
    checkOptions: {},
    reactDocgen: 'react-docgen-typescript',
    reactDocgenTypescriptOptions: {
      shouldExtractLiteralValuesFromEnum: true,
      propFilter: (prop) => (prop.parent ? !/node_modules/.test(prop.parent.fileName) : true),
    },
  },
};
```

```js
//storyshots/jest.config.js

/* eslint-disable @typescript-eslint/no-var-requires */
const path = require('path');
const { mergeRight } = require('ramda');
const globalJestConfig = require('../jest.config');
/* eslint-enable */

const storyshotsJestConfig = {
  rootDir: path.join(__dirname, '..'),
  roots: ['./storyshots'],
  testMatch: ['./**/storyshots.runner.ts'],
};

module.exports = mergeRight(globalJestConfig, storyshotsJestConfig);
```

```js
// storyshots/storyshots.runner.ts
import path from 'path';
import initStoryshots from '@storybook/addon-storyshots';
import { imageSnapshot } from '@storybook/addon-storyshots-puppeteer';

const pathToStorybookStatic = path.join(__dirname, '../storybook-static');

const beforeScreenshot = () => {
  return new Promise(
    (resolve) =>
      setTimeout(() => {
        resolve();
      }, 1000), // sometimes text doesn't render in time, so we wait one second for each image
  );
};

initStoryshots({
  suite: 'Image snapshots',
  storyNameRegex: /^((?!.*?DontTest).)*$/,
  framework: 'react',
  configPath: path.join(__dirname, '../.storybook'),
  test: imageSnapshot({
    beforeScreenshot,
    storybookUrl:
      process.env.CI === 'true'
        ? `file://${pathToStorybookStatic}`
        : `http://host.docker.internal:6006`,
    getMatchOptions: () => ({
      failureThreshold: 0.0,
      failureThresholdType: 'percent',
    }),
  }),
});
```
**System:**
```
System:
    OS: macOS 10.15.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.5 - ~/Documents/PROJECTS/ambrosia-design-system/node_modules/.bin/npm
  Browsers:
    Chrome: 83.0.4103.116
    Safari: 13.1
  npmPackages:
    @storybook/addon-actions: ^6.0.0-beta.36 => 6.0.0-beta.37 
    @storybook/addon-docs: ^6.0.0-beta.36 => 6.0.0-beta.37 
    @storybook/addon-storyshots: ^6.0.0-beta.36 => 6.0.0-beta.37 
    @storybook/addon-storyshots-puppeteer: ^6.0.0-beta.36 => 6.0.0-beta.37 
    @storybook/react: ^6.0.0-beta.36 => 6.0.0-beta.37 
    @storybook/theming: ^6.0.0-beta.36 => 6.0.0-beta.37 
```

**Comment by ajkl2533** [comment]
@shilman Any update on this?

**Comment by miguelangeltorresfp** [comment]
@shilman I had the same problem, I solved this by including `.storybook` folder in the `include` option in `tsconfig.json`

```json
{
  "compilerOptions": {
  "allowJs": true,
  "declaration": true 
    ...
  },
  "include": ["src/**/*", ".storybook"],
...
}

```

**Comment by shilman** [comment]
Nope, would appreciate if someone else can take a look. @Hypnosphi do you have any ideas?

**Comment by Hypnosphi** [comment]
@ajkl2533 you also need babel-jest: https://github.com/storybookjs/storybook/tree/next/addons/docs#installation

**Comment by bogdanorzea** [comment]
I have the same problem when running Jest after enabling the storyshot addon. It can also be reproduced on the 'sb init' project.

**Comment by norin89** [comment]
Same here.

**Comment by topcheese** [comment]
I just discovered this project, so I pretty much don't know what I'm doing.  I got this error because my .babel file wasn't in the root directory of the project.  I know nothing about Babel, but I'd make sure that's straight.
I'm trying to follow along with the Svelte V2 tutorials.

**Comment by miguelangeltorresfp** [comment]
@ajkl2533 Did you get this to work with ts-jest ?

**Comment by sarahbethfederman** [comment]
I'm getting this error too and I'm using babel-jest

**Comment by oxilor** [comment]
I replaced `ts-jest` to `babel-jest` and the error was disappear.

### 1. Install the babel
```
yarn add -D babel-jest @babel/preset-env @babel/preset-react @babel/preset-typescript
```

### 2. Create the `jest.transform.js` file
```js
module.exports = require('babel-jest').createTransformer({
  presets: [
    [
      '@babel/preset-env',
      {
        targets: {
          esmodules: true,
        },
      },
    ],
    '@babel/preset-react',
    '@babel/preset-typescript',
  ],
});
```
### 3. Add `transform` to your `jest.config.js`
```js
module.exports = {
  testEnvironment: 'jsdom',
  transform: {
    '^.+\\.[tj]sx?$': './jest.transform.js',
    '^.+\\.mdx?$': '@storybook/addon-docs/jest-transform-mdx',
  },
};
```

**Comment by cherylcarpenter** [comment]
@oxilor this did not fix for me :(

**Comment by kylemh** [comment]
So we can't use `ts-jest`? I wouldn't consider TSDX an active project anymore, but a lot of people obviously still use it and are stuck with `ts-jest` @shilman

**Comment by oxilor** [comment]
Hm. I have the latest version of the Storybook and [this way](https://github.com/storybookjs/storybook/issues/11376#issuecomment-757417250) still works.

**Comment by kylemh** [comment]
@oxilor are you using https://tsdx.io ?

**Comment by oxilor** [comment]
I created a [repo](https://github.com/oxilor/storybook-mdx-ts) with configuration that works for me, but in this project storyshots started to include Storybook's stories from node_modules. In my real project it works nice. Unfortunately, I don't have time to deal with this problem. If someone knows how to fix it, let me know.

**Comment by jeremyzilar** [comment]
The config that @oxilor shared seems to work 🤞
also ensure the your packages are up to date!

**Comment by K3TH3R** [comment]
My repo's setup to use [CSF for Stories with MDX for docs](https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/recipes.md#csf-stories-with-mdx-docs). Because my MDX is only for docs, I don't actually need the MDX for my unit tests so I can just tell Jest to throw it away:

## jest.config.js
```js
module.exports = {
  moduleNameMapper: {
    '\\.mdx?$': '<rootDir/__mocks__/mdxMock.js',
  }
}
```

## __mocks__/mdxMock.js
```js
module.exports = {}
```

**Comment by ndelangen** [comment]
The future of storyshots is the test-runner:
https://storybook.js.org/docs/react/writing-tests/test-runner#page-top

And use the play function for expectations:
https://storybook.js.org/docs/react/writing-stories/play-function#page-top

We will not be making any improvement / changes to storyshots.

**Comment by squidjam** [comment]
As a suggestion, if this is how it will go forward, please update the documentation on your website, as it states that Snapshots is an alternative to Chromatic.

> For a self-managed alternative to Chromatic, we offer [StoryShots](https://github.com/storybookjs/storybook/tree/next/code/addons/storyshots-core). It allows you to run visual tests on stories by integrating with [jest-image-snapshot](https://github.com/storybookjs/storybook/tree/main/code/addons/storyshots-puppeteer#imagesnapshots).

It will be simpler and we won't need to invest time to try and implement it only to have it not work and spend a couple of hours trying to find a solution on search engines.

**Comment by ricovitch** [comment]
@ndelangen what about puppeteer integration for visual regression snapshots ? Will it be supported by test-runner approach ? We currently use @storybook/addon-storyshots-puppeteer for the job.
