### ISSUE TITLE
Rename GlobalArgs to Globals

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#11384]
[Storybook Args RFC](https://docs.google.com/document/d/1Mhp1UFRCKCsN8pjlfPdz8ZdisgjNXeMXpXvGoALjxYM/edit?usp=sharing) introduces two types of dynamic data to Storybook, Args and GlobalArgs, and we are renaming GlobalArgs to Globals

## Rationale

Args and GlobalArgs share a similar implementation, but different semantics. Specifically, Args are arguments to a story and can only be set at the story or component levels. GlobalArgs are dynamic global variables for Storybook UI (and potentially other uses?) and can only be set globally.

In documenting Args, we found it confusing that there are no "global Args" but there are "GlobalArgs." So before we release and the name sticks forever, we're renaming `globalArgs` to `globals`. And `globalArgTypes` to `globalTypes`.

**Comment by kylemh** [comment]
DEFINITELY! My favorite draw to CSF was the ability to easily write "tests" once and use them across two tools, and this makes that very simple.

I basically already do this, but with way more silly boiler plate: https://github.com/innocuous-tech/core/blob/master/packages/components/src/Button/__stories__/Button.stories.tsx

**Comment by shilman** [comment]
Gadzooks!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-beta.39 containing PR #11385 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
