### ISSUE TITLE
[Feature Request] Add possibility to design with `Blazor`

### ISSUE THREAD

**Issue by redradist** [storybookjs/storybook#11380]
**Is your feature request related to a problem? Please describe.**
Add possibility to design components with [Blazor](https://dotnet.microsoft.com/apps/aspnet/web-apps/blazor
)
`npm` package for this is available [`dotnet` package](https://www.npmjs.com/package/dotnet)

**Are you able to assist bring the feature to reality?**
yes, I can

**Comment by acherkashin** [comment]
It could be really cool to have storybook for Blazor

**Comment by shilman** [comment]
https://storybook.js.org/docs/react/api/new-frameworks

**Comment by ntindle** [comment]
I know this got closed for staleness but I was looking again today for something like this and would appreciate it if it was reopened
