### ISSUE TITLE
Upgraded to 5.3.4 and now build fails with all Stories reporting "Module not found: Cannot resolve......"

### ISSUE THREAD

**Issue by jonnysmith1981** [storybookjs/storybook#11394]
Previously had successful setup using Storybook 5.3.1. Built with no problems whatsoever.

Updated Storybook to 5.3.4

**Expected behavior**
Storybook continues to build without any additional config required.

**Actual behavior**
Storybook no longer builds. All storybook files fail to build with spurious "Module not found" errors. 

**Screenshots**
Fails with relative paths
![image](https://user-images.githubusercontent.com/8254912/86383051-e6f96e00-bc85-11ea-8544-4b85173c35e7.png)

Fails with absolute paths
![image](https://user-images.githubusercontent.com/8254912/86383761-23c56500-bc86-11ea-873a-913baa3b1010.png)

Fails with aliased paths
![image](https://user-images.githubusercontent.com/8254912/86383931-32138100-bc86-11ea-8e0a-d2fca7faf1a2.png)

**Code snippets**
If applicable, add code samples to help explain your problem.

**System:**
Environment Info:

  System:
    OS: Windows 10 10.0.18362
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
  Binaries:
    Node: 10.16.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    @storybook/addon-actions: 5.3.4 => 5.3.4
    @storybook/addon-docs: 5.3.4 => 5.3.4
    @storybook/addon-links: 5.3.4 => 5.3.4
    @storybook/addon-notes: 5.3.4 => 5.3.4
    @storybook/addon-options: 5.3.4 => 5.3.4
    @storybook/addons: 5.3.4 => 5.3.4
    @storybook/angular: 5.3.4 => 5.3.4
    @storybook/react: 5.3.4 => 5.3.4
  npmGlobalPackages:
    @storybook/cli: 5.3.4

**Comment by shilman** [comment]
Did you try removing node_modules and possibly clearing lockfiles and reinstalling?

**Comment by jonnysmith1981** [comment]
Complete non-issue. Closing.
