### ISSUE TITLE
[addon-docs] Links in headings have smaller font-size than text

### ISSUE THREAD

**Issue by ajkl2533** [storybookjs/storybook#11393]
**Describe the bug**
When using a link in heading in the MDX file than the link and text have different font-size. I suspect that the issue is coming from [here](https://github.com/storybookjs/storybook/blob/next/lib/components/src/typography/DocumentFormatting.tsx#L88) where is hardcoded the `14px` font-size for links, instead, there should be probable `inherited` because the size of the link should be probably inherited from an element in which is placed.

**To Reproduce**
Create MDX file with:
```md
# [Link](#test) Text

## [Link](#test) Text
```

**Expected behavior**
Links should have the same font size as the text in the heading

**Screenshots**
<img width="813" alt="Screenshot 2020-07-02 at 17 44 33" src="https://user-images.githubusercontent.com/18654425/86380227-2b880800-bc8c-11ea-99a3-afa8d14ee8b8.png">

**Code snippets**
```md
# [Link](#test) Text

## [Link](#test) Text
```

**System:**
```
  System:
    OS: macOS 10.15.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.5 - ~/Documents/PROJECTS/ambrosia-design-system/node_modules/.bin/npm
  Browsers:
    Chrome: 83.0.4103.116
    Safari: 13.1
  npmPackages:
    @storybook/addon-actions: ^6.0.0-beta.38 => 6.0.0-beta.39 
    @storybook/addon-docs: ^6.0.0-beta.38 => 6.0.0-beta.39 
    @storybook/addon-storyshots: ^6.0.0-beta.38 => 6.0.0-beta.39 
    @storybook/addon-storyshots-puppeteer: ^6.0.0-beta.38 => 6.0.0-beta.39 
    @storybook/react: ^6.0.0-beta.38 => 6.0.0-beta.39 
    @storybook/theming: ^6.0.0-beta.38 => 6.0.0-beta.39 
```

**Comment by ajkl2533** [comment]
@shilman Any update on this?

**Comment by shilman** [comment]
Zoinks!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-rc.24 containing PR #11770 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.
