### ISSUE TITLE
[addon-docs] mdx breaks with expressions as Story name

### ISSUE THREAD

**Issue by mitchellwarr** [storybookjs/storybook#11399]
### Describe the bug
When using a Story in mdx, if you use brackets around your text variable like below, then the compiler errors out.

```js
<Preview>
  <Story name={'text'}>
    <Button onClick={action('clicked')}>Hello Button</Button>
  </Story>
</Preview>
```

### To Reproduce
Create MDX file with brackets around the Story name text

### Expected behavior
Storybook should compile

### possible cause

Error message points to this

https://github.com/storybookjs/storybook/blob/0ee0e2f1869f6565c84a8424b32bc39ee94fab23/addons/docs/src/mdx/mdx-compiler-plugin.js#L45-L48

**Comment by shilman** [comment]
Yeah, MDX compiles to [CSF](https://medium.com/storybookjs/component-story-format-66f4c32366df) under the hood.  CSF requires that story names be statically analyzable. So this kind of dynamic expression won't be possible in MDX. What's the use case?

**Comment by mitchellwarr** [comment]
The use case is that we would like to be able to keep our linter consistent across all jsx. We have the lint rule for everything being wrapped in curly brackets.

But besides that use case, using curly brackets in jsx is expected and valid behavior. It feels like a bug that this is breaking. I'm not sure if i just missed some important note in the docs pointing our the different behavior though. But i am a little concerned that when someone else in the team goes to make a doc that they keep the same style of jsx we use everywhere else, get this bug, and then not know why its not compiling

**Comment by mitchellwarr** [comment]
Are there other ways to make the field statically analyzable? It might be that one of those would suit my use case better
