### ISSUE TITLE
SB Docs gets padding from the layout parameter when it should not

### ISSUE THREAD

**Issue by domyen** [storybookjs/storybook#11398]
**Describe the bug**
SB Docs gets padding from the layout parameter when it should not. The layout parameter should be stories only. This is on `next`. 

![image](https://user-images.githubusercontent.com/263385/86424187-d827b100-bcaf-11ea-9b2c-468ca0dbd495.png)

**To Reproduce**
1. Go to an MDX doc like in [Storybook Design System](https://5ccbc373887ca40020446347-yldsqjoxzb.chromatic.com/?path=/docs/design-system-intro--page)
2. Inspect the body of the iframe to see that it gets 1em padding
3. See bug

**Expected behavior**
It should not be padded. Docs has its own styling.

**Comment by domyen** [comment]
@shilman @ndelangen Any movement on this? I'm currently removing this padding manually via devtools so I can take screenshots for the new documentation 😅

**Comment by ndelangen** [comment]
I'll take a look today @domyen

**Comment by shilman** [comment]
Zoinks!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-rc.16 containing PR #11699 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
