### ISSUE TITLE
CSS Custom Properties support for knobs

### ISSUE THREAD

**Issue by coltpini** [storybookjs/storybook#11395]
**Is your feature request related to a problem? Please describe.**

As we are able to use custom properties more and more we are able to move styling props to styles and keep other props in the js. Knobs has become so integrated into our workflow it creates a sort of documentation on how to use the component and what values are allowed. Currently we cannot incorporate custom properties into our workflow. 

**Describe the solution you'd like**

We would love to be able to define our custom properties in knobs and have them be used to document our component APIs and show what changes to those props effects.

**Describe alternatives you've considered**

We have thought about using the custom elements as a param and injecting them in the style element. Maybe using the param feature of knobs.

**Are you able to assist bring the feature to reality?**
no | yes, I can...

I would love to, but I cannot guarantee my availability. I really wish I could give a better answer, I really would like to try and make it happen.

**Additional context**

This probably won't help, but here is a project I built, years ago, to use a storybook experience with custom elements, built using custom elements.
It allowed to add a custom props. This was created before knobs was an extension. (https://github.com/LuceStudio/prova)

**Comment by shilman** [comment]
@coltpini Nice demo!!!

FYI, we’ve released addon-controls in 6.0-beta. Controls are portable, auto-generated knobs that are intended to replace addon-knobs long term.

- [Controls README](https://github.com/storybookjs/storybook/tree/next/addons/controls)
- [Migration instructions](https://github.com/storybookjs/storybook/blob/next/addons/controls/README.md#how-do-i-migrate-from-addon-knobs)
- [Walkthrough: Controls w/ CRA & TypeScript](https://gist.github.com/shilman/69c1dd41a466bae137cc88bd2c6ef487)

Please upgrade and try them out today!

**Comment by coltpini** [comment]
Ok, cool controls looks great. I am not seeing support for custom property support in controls. Am I just missing it, or is that something I would feature request for controls?

**Comment by shilman** [comment]
@coltpini Can you define custom property for me?

**Comment by coltpini** [comment]
A custom property: https://developer.mozilla.org/en-US/docs/Web/CSS/--*

I would use them in a component like this:
```
:host {
  --color: var(--theme-color, #69f);
}
:host([disabled]){
  --color: var(--theme-color-disabled, #acf);
}
.example-selector-in-component {
  background: var(--color);
}
```

then in the css that uses the above component:
```
my-example-component {
  --color: red;
}
my-example-component[disabled] {
  --color: pink;
}
```
```

**Comment by shilman** [comment]
Thanks for the clarification. Definitely not supported explicitly in either Knobs or Controls currently. Both support all the building blocks you'd need to do this (numbers, strings, colors, etc.), but I'm not sure the best way to hook those up to CSS vars.

**Comment by coltpini** [comment]
The way I was planning on doing it was to add a style to the element based on the value using the setProperty function. It would be pretty simple for styles on the host element. It would be more difficult to figure out how to change the value on different scopes, but I am not sure that would be needed. I would want to see how it would be used first.

**Comment by jbuckner** [comment]
I'm also interested in using controls for CSS Custom Properties to demo WebComponents. I've come up with a solution that works, but could probably be abstracted to remove some of the boilerplate: 

```
export default {
  title: 'Demos/FooComponent',
  argTypes: {
    trackColor: {
      control: { type: 'color' }
    }
  }
};

const Template = (options: {
  trackColor: string;
}) => {
  // set the CSS variable explicitly
  const styleContainer = document.documentElement.style;
  styleContainer.setProperty('--trackColor', options.trackColor);

  return html`
    <foo-component></foo-component>
  `
};

export const Demo = Template.bind({});
Demo.args = {
  trackColor: 'rgba(50, 114, 182, 1)'
};
```

**Comment by shilman** [comment]
cc @storybookjs/web-components ☝️
