### ISSUE TITLE
Unable to display nested components props correctly

### ISSUE THREAD

**Issue by benbonnet** [storybookjs/storybook#11402]
I might be mis-using the functionnality, in case apologies; but I havent't found any relevant clues if this use case had to be handled differently

*Feature request related to a problem?**
Re-using nested components props to validate on parent component as follow :

```
Component.propTypes = {
  header: PropTypes.shape(CardHeader.propTypes),
  ...
};

```

But getting weird displays :
<img width="562" alt="Capture d’écran 2020-07-03 à 11 14 20" src="https://user-images.githubusercontent.com/7711/86453650-6c306180-bd1e-11ea-90eb-cf26602f483d.png">

Using the following syntax :

```
Component.propTypes = {
  header: PropTypes.shape({ ...CardHeader.propTypes })
};
```

Getting the following display (empty hash) :

<img width="1059" alt="Capture d’écran 2020-07-03 à 12 32 28" src="https://user-images.githubusercontent.com/7711/86460788-4b213e00-bd29-11ea-8a1f-5153310e678d.png">

**Describe the solution you'd like**
Getting the same output as a manual `shape` use would provide

**Alternatives considered**
None yet

**Able to bring the feature to reality?**
no, unsure

**Comment by benbonnet** [comment]
sorry to ask again;  is this case could be handled with a different pattern; or is it just a limitation at the moment ?

**Comment by benbonnet** [comment]
If someone could provide help; just to know if our expectation is something that should not be considered; and what would be the workaround

**Comment by shilman** [comment]
Sorry I haven't had a chance to dig into this. But maybe this helps: https://github.com/storybookjs/storybook/blob/next/addons/controls/README.md#my-controls-arent-being-auto-generated-what-should-i-do

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
