### ISSUE TITLE
Vue Storybook doesn't compile with Pug components

### ISSUE THREAD

**Issue by Rusinas** [storybookjs/storybook#11409]
**Describe the bug**
Can't compile my storybook, if it contains components that written using pug. Compiler just stops at 14%. If I change template language in that components to html, compiling is successful and storybook works just fine. But the entire project written using Pug! :( 

**To Reproduce**
Install vue, install storybook, create component using Pug, try to create story with it. 

**Expected behavior**
Successful compiling for sure. 

**Additional context**

**Comment by shilman** [comment]
Is pug a standard thing in ALL Vue projects and should we support it out of the box? If not, you probably need to customize your webpack config: https://storybook.js.org/docs/configurations/custom-webpack-config/

**Comment by doutatsu** [comment]
Same here, I am unable to get it to work. I've attempted to adjust the webpack configuration as such:
```
const path = require('path');

module.exports = {
  "stories": [
    "../src/**/*.stories.mdx",
    "../src/**/*.stories.@(js|jsx|ts|tsx)"
  ],
  "addons": [
    "@storybook/addon-links",
    "@storybook/addon-essentials"
  ],
  webpackFinal: async config => {
    // config.module.rules.push({
    //   test: /\.scss$/,
    //   use: ['style-loader', 'css-loader', 'sass-loader'],
    //   include: path.resolve(__dirname, '../'),
    // });
    config.module.rules.push({
      test: /\.pug$/,
      use: [{ loader: 'pug-plain-loader' }]
    });

    return config;
  },
}
```

but still get

```
ERROR in ./src/components/base_components/BaseBadge.vue 1:0
Module parse failed: Unexpected token (1:0)
File was processed with these loaders:
 * ./node_modules/vue-docgen-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
> <template lang="pug">
|   span(v-text="text" :class="classes")
| </template>
```

**Comment by yoyoys** [comment]
@shilman 
Yes, it's support by vue-loader.
Just install `pug pug-plain-loader` and works(by vue-cli).
