### ISSUE TITLE
Support absolute anchors when Storybook is deployed at non-root

### ISSUE THREAD

**Issue by amannn** [storybookjs/storybook#11404]
**Describe the bug**

When Storybook is deployed at an URL like `https://example.com/storybook/component-library/v48.3.2/`, the anchors within docs content will remove the base url.

E.g. when you're on `https://example.com/storybook/component-library/v48.3.2/?path=/docs/components-icon--default` and you have a link to `/docs/components-button--default` in the documentation, the resulting link will point to `https://example.com/?path=/docs/components-button--default`.

**To Reproduce**

1. Build a storybook locally
2. Run `npx http-server` in a parent folder
3. Navigate to the storybook
4. Try clicking on a link as described above and it will fail

**Expected behavior**

The base url of the deployment should be considered for the link.

**System:**

```
  System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  Binaries:
    Node: 12.3.1 - /usr/local/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.14.3 - ~/Projects/alpine/component-library/node_modules/.bin/npm
  Browsers:
    Chrome: 83.0.4103.116
    Edge: 81.0.416.53
    Firefox: 77.0.1
    Safari: 13.1
  npmPackages:
    @storybook/addon-actions: ^5.3.19 => 5.3.19 
    @storybook/addon-docs: ^5.3.19 => 5.3.19 
    @storybook/addon-storyshots: ^5.3.19 => 5.3.19 
    @storybook/addons: ^5.3.19 => 5.3.19 
    @storybook/csf: ^0.0.1 => 0.0.1 
    @storybook/react: ^5.3.19 => 5.3.19 
    @storybook/theming: ^5.3.19 => 5.3.19 
```

**Additional context**

I've created a PR that should solve this here: https://github.com/storybookjs/storybook/pull/11403

**Comment by amannn** [comment]
I've already created a PR 😬

**Comment by shilman** [comment]
Ooh-la-la!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-rc.19 containing PR #11403 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by anatel** [comment]
Is this problem back in `6.2.9`? I'm trying to have the following link as part of a story's doc:
```js
Primary.parameters = {
    docs: {
        description: {
            story: 'Go to [another story](?path=/story/design-system-another-story--default)'
        },
    },
};
```
But the link redirects to: http://localhost:6006/iframe.html?path=/story/design-system-another-story--default
Notice the `iframe.html` :(

**Comment by amannn** [comment]
@anatel I think so, yes. I've worked on resolving the issue again here: https://github.com/storybookjs/storybook/pull/14558

**Comment by anatel** [comment]
Cool, hope it'll be merged soon
