### ISSUE TITLE
Issue with deepEqual in SourceContainer 

### ISSUE THREAD

**Issue by azaxarov** [storybookjs/storybook#11413]
**Describe the bug**
My current Storybook setup works up to and including v6.0.0-beta.37. However, once Storybook dependencies are updated to v6.0.0-beta.38, the stories break on the deepEqual check in SourceContainer. The changes were introduced in https://github.com/storybookjs/storybook/pull/11332.

https://github.com/storybookjs/storybook/blob/b25b434faa174105003a3cbf859db81e2841feb9/addons/docs/src/blocks/SourceContainer.tsx#L35

I suspect that it results in a false positive by checking equality of initial sources ({}) with sourcesRef.current that is undefined in my case. An additional check for undefined ref value seems reasonable:

```
if (sourcesRef.current && !deepEqual(sources, sourcesRef.current))
```

I appreciate the work you guys are doing and hope this is a relatively easy fix!

**To Reproduce**

**Expected behavior**

**Screenshots**
![Screen Shot 2020-07-03 at 21 17 18](https://user-images.githubusercontent.com/29962353/86493721-dffc5980-bd72-11ea-8e98-e01498213b49.png)

**Code snippets**
If applicable, add code samples to help explain your problem.

**System:**
```
Environment Info:

  System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-2635QM CPU @ 2.00GHz
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    npm: 6.14.5 - ~/.nvm/versions/node/v12.16.1/bin/npm
  Browsers:
    Chrome: 83.0.4103.116
    Firefox: 76.0.1
    Safari: 13.0.5
  npmPackages:
    @storybook/addon-a11y: ^6.0.0-beta.40 => 6.0.0-beta.40 
    @storybook/addon-essentials: ^6.0.0-beta.40 => 6.0.0-beta.40 
    @storybook/addon-links: ^6.0.0-beta.40 => 6.0.0-beta.40 
    @storybook/addons: ^6.0.0-beta.40 => 6.0.0-beta.40 
    @storybook/react: ^6.0.0-beta.40 => 6.0.0-beta.40 
    @storybook/theming: ^6.0.0-beta.40 => 6.0.0-beta.40
```

**Additional context**

**Comment by shilman** [comment]
Yo-ho-ho!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-beta.41 containing PR #11414 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by azaxarov** [comment]
Great news! I'll give it a go today.
