### ISSUE TITLE
Can't use global installation of prettier when `addon-storysource` or `source-loader` is installed

### ISSUE THREAD

**Issue by manjunatha-d** [storybookjs/storybook#11416]
**Describe the bug**
We can't use a global installation of prettier in yarn scripts (or npm scripts) when certain storybook packages like @storybook/addon-storysource or @storybook/source-loader are installed.

**To Reproduce**
0. Run `yarn global add prettier@2.0.5` to install prettier globally.
1. Clone the repo https://github.com/manjunatha-d/storybook-prettier-issue-reproduction
2. Run `yarn install` in the cloned repo
3. Run `yarn format` (the script format is defined as `prettier --version && which prettier && prettier '*.js'`)

**Expected behavior**
`prettier` should be a `devDependency` of these addons. Is there any particular reason for declaring `prettier` as a `dependency` instead of `devDependency`?

**System:**
Environment Info:

  System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  Binaries:
    Node: 12.10.0 - ~/Projects/spark/.buildenv/bin/node
    Yarn: 1.21.0 - ~/Projects/spark/src/rubrik/spark-ui/node_modules/.bin/yarn
    npm: 6.10.3 - ~/Projects/spark/.buildenv/bin/npm
  Browsers:
    Chrome: 83.0.4103.116
    Safari: 13.0.4
  npmPackages:
    @storybook/addon-a11y: ^5.3.14 => 5.3.14
    @storybook/addon-actions: ^5.3.14 => 5.3.14
    @storybook/addon-backgrounds: ^5.3.14 => 5.3.14
    @storybook/addon-docs: ^5.3.14 => 5.3.14
    @storybook/addon-knobs: 5.3.14 => 5.3.14
    @storybook/addon-links: ^5.3.18 => 5.3.18
    @storybook/addon-storysource: ^5.3.14 => 5.3.14
    @storybook/addon-viewport: ^5.3.14 => 5.3.14
    @storybook/addons: ^5.3.14 => 5.3.14
    @storybook/preset-create-react-app: ^1.5.2 => 1.5.2
    @storybook/react: ^5.3.14 => 5.3.14

**Comment by shilman** [comment]
please upgrade to 6.0, i think the dependency has been ugpraded

**Comment by manjunatha-d** [comment]
@shilman Upgrading will not fix the root cause. The prettier version used will be dependent on the version specified in storybook packages. This is a problem because the dependencies should not determine the version of a package used in the main application.

**Comment by shilman** [comment]
Why can't storybook depend on a specific version of a package. Getting your monorepo to work is up to you, isn't it?

**Comment by manjunatha-d** [comment]
@shilman Absolutely. 

The problem is with how dependencies are installed and how npm resolves dependencies. We don't have control over either of them to fix our issue. Their approach works fine for most of the cases. Unfortunately, ours is an edge case.

This will be a problem for all monorepos that want to use a prettier version different from the one that storybook addons depend on.

If these storybook addons don't need prettier at runtime, we can safely address this issue by making `prettier` a dev dependency.

**Comment by shilman** [comment]
Unfortunately those libraries do depend on prettier at the moment. I think there are some smaller alternatives we should consider using, but that’s a separate issue

**Comment by manjunatha-d** [comment]
@shilman Alright, thanks!

For others with the same issue:
We can make it work in monorepos by using path to the global prettier binary, something like:
``` 
format: "path_to_dir_containing_global_prettier/prettier '*.js'"
```
