### ISSUE TITLE
Multiple children of a <Story> block in MDX files breaks the parsing

### ISSUE THREAD

**Issue by Nvveen** [storybookjs/storybook#11411]
**Describe the bug**
Multiple children of a <Story> block in an MDX file breaks the parsing (with a default create-react-app setup) @6.0.0-beta.39 with the following error:
`Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: example/src/stories/Test.stories.mdx: transform-react-jsx: pragma has been set but pragmaFrag has not been set`

**To Reproduce**
1. Create a new `create-react-app` project and upgrade everything to the latest version.
2. Install storybook: `npx -p @storybook/cli sb init --type react_scripts`
3. Upgrade storybook: `yarn add -D @storybook/{addon-actions,addon-docs,addon-links,addons,preset-create-react-app,react}@next`.
4. Configure storybook to accept MDX:
```js
module.exports = {
  stories: ['../src/**/*.stories.*'],
  addons: [
    '@storybook/preset-create-react-app',
    '@storybook/addon-actions',
    { name: '@storybook/addon-docs', options: { configureJSX: true } },
    '@storybook/addon-links',
  ],
};
```
5. Write an MDX component:
```js
import { Meta, Story, Preview } from '@storybook/addon-docs/blocks';
import { Button } from '@storybook/react/demo';

<Meta title="MDX/Example" component={Button} />

# Example

<Preview>
  <Story name="Example">
    <span>First</span>
    <span>Second</span>
  </Story>
</Preview>
```

**Expected behavior**
To show multiple children in a story, for example when having one story describe multiple variants of the same component.

**System:**
Environment Info:

  System:
    OS: macOS 10.15.5
    CPU: (4) x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
  Binaries:
    Node: 14.2.0 - ~/.nvm/versions/node/v14.2.0/bin/node
    Yarn: 1.21.1 - ~/.yarn/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v14.2.0/bin/npm
  Browsers:
    Chrome: 83.0.4103.116
    Firefox: 73.0.1
    Safari: 13.1.1
  npmPackages:
    @storybook/addon-actions: ^6.0.0-beta.39 => 6.0.0-beta.39
    @storybook/addon-docs: ^6.0.0-beta.39 => 6.0.0-beta.39
    @storybook/addon-links: ^6.0.0-beta.39 => 6.0.0-beta.39
    @storybook/addons: ^6.0.0-beta.39 => 6.0.0-beta.39
    @storybook/preset-create-react-app: ^3.1.2 => 3.1.2
    @storybook/react: ^6.0.0-beta.39 => 6.0.0-beta.39

**Additional context**
Wrapping the children in a fragment is one solution, although you have to explicitly write `<React.Fragment>`, and `<></>` throws the same error.

**Comment by frebro** [comment]
I see the same warning on a similar setup, after upgrading from 6.0.0-beta.20 to 6.0.0-beta.43. I rolled back the beta version number a few times and found that it gets introduced at 6.0.0-beta.38. Ping me for more specs if that helps!
