### ISSUE TITLE
MDX error: Support for the experimental syntax 'jsx' isn't currently enabled

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#11439]
A recent change in `babel` has broken Storybook's MDX configuration in CRA, with the error: `Support for the experimental syntax 'jsx' isn't currently enabled`.

More info here: https://github.com/storybookjs/storybook/pull/11422#issuecomment-653939846

This is reproducible in a fresh CRA install, and the problem is present on both `next` and `latest` branches, unrelated to any code changes on our side.

cc @tooppaaa @ndelangen

**Comment by shilman** [comment]
There are two workarounds for this issue. For React projects (e.g. CRA) that have the following line in their `main.js`:

```js
module.exports = {
  addons: [
    '@storybook/addon-docs'
  ]
};
```

Update to:

```js
module.exports = {
  addons: [
    {
       name: '@storybook/addon-docs',
       options: { configureJSX: true }
    }
  ]
};
```

If you use `<>blah</>` style fragments in your MDX, this will unlock a second bug (presumably from the same underlying source): `transform-react-jsx: pragma has been set but pragmaFrag has not been set`.

For now, the workaround is to rewrite those fragments as `<React.Fragment>blah</React.Fragment>`.

We're working on:
1. A better workaround for the fragment issue
2. A proper fix to both issues

**Comment by DanWahlin** [comment]
Thanks for posting this - appreciate it. Been fighting that exact error for a day but it's related to a custom addon in the project:

```javascript
addons: [
  './.storybook/sourcecode-addon/register'
]
```

This loads register.js fine but the .jsx inside of the addon gives the 'jsx' isn't currently enabled error when trying to load a `storybookPanel.jsx` file in the sourcecode-addon folder.

Changed it to:

```javascript
addons: [
    {
      name: './.storybook/sourcecode-addon/register',
      options: { configureJSX: true }
    }
]
```

But, now I get a "Cannot find module './.storybook/sourcecode-addon/register' error. Any guess if it's related to the same thing you're reporting or am I just doing it wrong? Fought this one so long I'm about ready to throw in the towel. :-)

**Comment by shilman** [comment]
Olé!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-beta.45 containing PR #11448 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Yay!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.20 containing PR #11448 that references this issue. Upgrade today to try it out!
