### ISSUE TITLE
Tutorial Bug

### ISSUE THREAD

**Issue by James-Hudson3010** [storybookjs/storybook#11435]
In the Add Assets section, there are the two commands:

```
svn export https://github.com/chromaui/learnstorybook-code/branches/master/public/icon public/icon
svn export https://github.com/chromaui/learnstorybook-code/branches/master/public/font public/font
```

these apparently no longer work. It would seem that GitHub has removed the feature needed for these commands.

**Comment by shilman** [comment]
Please file against https://github.com/chromaui/learnstorybook.com/
