### ISSUE TITLE
Primary slot description using JsDoc comment not working

### ISSUE THREAD

**Issue by hardikjain0309** [storybookjs/storybook#11434]
**Describe the bug**
I have a JsDoc comment in my component source file, just above the line export default but it doesn't reflect in DocsPage generated for my component. Its my first time trying this feature so I am not sure if this is actually a bug or something I might be doing wrong

**To Reproduce**
I have a source component file that looks like this 
```
/**
 * Controlled stateless component for a circular checkbox with a click event handler prop.
 */
export default class CheckboxCircular extends React.Component<ICheckboxCircularProps> { ...`
```

**Expected behavior**
But right now description only gets populated in the generated DocsPage when I try this in my story file
```
export default {
    title: 'Circular Checkbox',
    component: CheckboxCircular,
    decorators: [cardDecorator, withKnobs],
    parameters: {
        componentSubtitle: "Controlled component",
        docs: {
            extractComponentDescription: () => "Controlled stateless component for a circular checkbox with a click event handler prop."
        }
    }
}
```
I want it to work out of the box since I don't want to use this workaround everywhere. I am onboarding a big ux repo to storybook with lots of components

**Screenshots**
It should look like this in the doc page of this component
![image](https://user-images.githubusercontent.com/40684057/86594559-dd894200-bfb4-11ea-84a7-590e9c8e315a.png)

But without  'extractComponentDescription' it looks like 
![image](https://user-images.githubusercontent.com/40684057/86594968-9a7b9e80-bfb5-11ea-96c8-33561bd9c8ed.png)

**System:**
 System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz
  Binaries:
    Node: 12.18.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    @storybook/addon-actions: ^5.3.19 => 5.3.19
    @storybook/addon-docs: ^5.3.19 => 5.3.19
    @storybook/addon-knobs: ^5.3.19 => 5.3.19
    @storybook/addon-links: ^5.3.19 => 5.3.19
    @storybook/addon-storysource: ^5.3.19 => 5.3.19
    @storybook/addons: ^5.3.19 => 5.3.19
    @storybook/react: ^5.3.19 => 5.3.19

**Additional context**

**Comment by shilman** [comment]
You might try upgrading to 6.0-beta (soon to be RC). We've overhauled the typescript handling there, and this is almost certainly a typescript configuration issue.

https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#zero-config-typescript

**Comment by hardikjain0309** [comment]
I finally upgraded to beta (.44) but now the whole docs add on is super buggy. I am seeing scrollbars everywhere and this message where propsTable used to be: Args unsupported. See Args documentation for your framework. 
Read the docs

![image](https://user-images.githubusercontent.com/40684057/86623486-52717180-bfdf-11ea-9252-2f1b24a84a17.png)

The only good thing that came out of this was that my typescript config is gone but considering the whole docs addon broke i am not sure what to do here

**Comment by shilman** [comment]
@hardikjain0309 Do you have a repro?

**Comment by hardikjain0309** [comment]
Hmm I am not sure how to create the exact situation for you. How do people usually do this here? Give you steps? I can try creating a new app soon to repro this if you want. Also, in 5.3.x I am seeing that the descriptions (From JSDoc comments) for props are getting displayed, just the main primary description is not getting displayed. Havent tried the same with 6.0.0-beta. Also which repro do you want to see? The beta version issue I guess?

**Comment by shilman** [comment]
To create a repro, either:
- create a temporary github repo that i can download, install, and observe the error
- @yannbf has created a codesandbox template https://gist.github.com/yannbf/d7a32cfe697e71489db00bfd50e7ab5c

**Comment by hardikjain0309** [comment]
[https://codesandbox.io/s/wandering-bird-vmtf1](url)

I thought the repro might be difficult but this was really easy. I guess beta docs really is broken

**Comment by shilman** [comment]
No, I think it's just your example that's pretty badly broken. Did you follow the upgrade instructions in https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#from-version-53x-to-60x

**Comment by shilman** [comment]
A couple things jumped out from a quick look at the example:
1. you're not using the docs preset, so there are lots of configuration changes in 6.0. i'd really recommend using the docs preset unless you have a good reason not to
2. there's no CRA preset https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#cra-preset-removed

Lack of docs preset would explain why there is no JSDoc extracted -- you didn't configure that. And lack of CRA preset would explain where there's no props table. There maybe other issues as well.

**Comment by hardikjain0309** [comment]
I am not using CRA so wont be using the cra-preset. Also, how to use the docs preset?

**Comment by hardikjain0309** [comment]
Ok I tried the main.js:

```
module.exports = {
  stories: ["../**/*.stories.@(ts|tsx)"],
  addons: [
    "@storybook/addon-docs/register",
    "@storybook/addon-knobs/register",
    "@storybook/addon-storysource",
    "@storybook/addon-actions/register"
  ],
  presets: ["@storybook/addon-docs/preset"]
};
```

Btw I was unable to find the docs on how to use this preset, and had to go through https://medium.com/storybookjs/storybook-docspage-e185bc3622bf
can we put this in the documentation for addon-docs? And now the docs don't show vertical scroll bars but instead of args not supported I am seeing the error 

![image](https://user-images.githubusercontent.com/40684057/86714535-e6255b00-c03c-11ea-9692-36312d037db5.png)

in the place of propsTable

**Comment by hardikjain0309** [comment]
Finally, this worked for me

typescript: {
    // also valid 'react-docgen-typescript' | false
    reactDocgen: "react-docgen"
  }

That means react-docgen-typescript has some corner case my code isnt passing. Thanks for all the help!

![image](https://user-images.githubusercontent.com/40684057/86716056-73b57a80-c03e-11ea-8ed9-3bef7ab2cb6d.png)

**Comment by shilman** [comment]
@hardikjain0309 glad you got it working! FYI, the installation instructions are here:

https://github.com/storybookjs/storybook/blob/next/addons/docs/README.md#installation

Specifically:

> Then add the following to your .storybook/main.js:

```js
module.exports = {
  stories: ['../src/**/*.stories.@(js|mdx)'],
  addons: ['@storybook/addon-docs'],
};
```

When you don't add `/register` to the end, it uses the preset, which pre-configures a lot of stuff for you.

Here's another variant of that a little bit lower in the same file:

> ## Preset options
> 
> The addon-docs preset has a few configuration options that can be used to configure its babel/webpack loading behavior. 
 Here's an example of how to use the preset with options:

```js
module.exports = {
  addons: [
    {
      name: '@storybook/addon-docs',
      options: {
        configureJSX: true,
        babelOptions: {},
        sourceLoaderOptions: null,
      },
    },
  ],
};
```

A few lines lower:

> We recommend using the preset, which should work out of the box. 

And so on...

**Comment by etedesco** [comment]
I’m having the same problem as NikolaiDokken using the latest 6.5.8 version

**Comment by wbr911** [comment]
> I’m having the same problem as NikolaiDokken using the latest 6.5.8 version

after my investigation. the easy way is to add additional `named export`  since react-docgen-typescript only support `named export`

# before
```javascript
/** 
* your comments
*/
export default class CheckboxCircular 
```

# change to
```javascript
/** 
* your comments
*/
export const class CheckboxCircular 
export default CheckboxCircular
```
