### ISSUE TITLE
addon-docs: stories on DocsPage are not self-contained

### ISSUE THREAD

**Issue by jayarjo** [storybookjs/storybook#11436]
**Describe the bug**
When component triggers a modal, it becomes a modal for the whole DocsPage.

**To Reproduce**
Have a component that opens a modal in portal for example.

**Expected behavior**
Each story should somehow be contained within its own area, perhaps by loading each one in a separate iframe?

For some reason I thought that that's how it is implemented in first place, and was quite surprised when I found all stories embedded in a single document. How do you even achieve styling consistency is quite a mystery for me. Or is it feature of styled components that we use?

**Screenshots**
![Jul-06-2020 17-54-11](https://user-images.githubusercontent.com/150075/86600919-c1d06c80-bfb1-11ea-96f3-1566300dc806.gif)

**System:**
```
Environment Info:

  System:
    OS: macOS 10.15.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 10.20.1 - ~/.nvm/versions/node/v10.20.1/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v10.20.1/bin/npm
  Browsers:
    Chrome: 83.0.4103.116
    Safari: 13.1.1
```

**Comment by shilman** [comment]
You can force stories to render in their own iframes, tho it has performance issues:

https://github.com/storybookjs/storybook/blob/next/addons/docs/react/README.md#inline-stories

**Comment by jayarjo** [comment]
Thanks!
