### ISSUE TITLE
how can build component json

### ISSUE THREAD

**Issue by v-yafeili** [storybookjs/storybook#11443]
like this: 
[{button:[{name:"with text", showult:"/button--with-text"}]}]

**Comment by yannbf** [comment]
Hey @v-yafeili thanks for opening an issue with Storybook! I'd suggest you to elaborate your questions a bit more on future issues so we can provide you with better support. There's a great template that you can use!

For assistance in building your components with Storybook server, please check the following docs:
https://github.com/storybookjs/storybook/tree/next/app/server#getting-started

And here's a kitchen-sink that can help you get a few more ideas:
https://github.com/storybookjs/storybook/tree/next/examples/server-kitchen-sink
