### ISSUE TITLE
addParameters deprecation warning is also triggered by addons

### ISSUE THREAD

**Issue by jpzwarte** [storybookjs/storybook#11451]
With the latest beta, the `addParameters` deprecation warning about `preview.js` is also triggered when `addParameters` is called by an addon. This can be confusing since a user may think he still needs to change something in `preview.js`.

To be clear: the deprecation warning still persists even after you have changed `preview.js` to use `export const parameters = {...};`.

I traced one such deprecation warning to the docs addon (i think?).
<img width="552" alt="Screen Shot 2020-07-07 at 12 17 48" src="https://user-images.githubusercontent.com/3968/86804512-476a2000-c077-11ea-8e19-7b3bcdf88a25.png">

**Comment by shilman** [comment]
Yowza!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-beta.46 containing PR #11455 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
