### ISSUE TITLE
Addon-docs: Doesn't render values within objects

### ISSUE THREAD

**Issue by doglasbatista** [storybookjs/storybook#11465]
**Describe the bug**

This is my code:

`GridContainer.tsx`
```tsx
import React, { ReactNode } from 'react';

import { grid } from './variables';

import { Container } from './Grid.styles';

interface GridContainerProps {
  children: ReactNode;
  columns?: number;
  gutter?: number;
}

const GridContainer = ({ children, columns, gutter }: GridContainerProps) => {
  return (
    <Container columns={columns} gutter={gutter}>
      {children}
    </Container>
  );
};

GridContainer.defaultProps = {
  columns: grid.numberOfColumns,
  gutter: grid.gutter,
};

export default GridContainer;
```

`variables.ts`
```ts
const grid = {
  numberOfColumns: 12,
  gutter: 24,
};
...

export { grid, .... };
```

And this is the generated doc table

![image](https://user-images.githubusercontent.com/5438099/86925556-67e1bb00-c107-11ea-932b-bd224d72cee0.png)

**Expected behavior**
Print `grid` object value in the "default" column

**System:**
OS: macOS 10.15.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
Binaries:
    Node: 12.18.1 - ~/.asdf/installs/nodejs/12.18.1/bin/node
    Yarn: 1.22.4 - ~/.asdf/installs/nodejs/12.18.1/.npm/bin/yarn
Browsers:
    Chrome: 83.0.4103.116
npmPackages:
    @storybook/addon-actions: 5.3.19 => 5.3.19 
    @storybook/addon-docs: 5.3.19 => 5.3.19 
    @storybook/addon-knobs: 5.3.19 => 5.3.19 
    @storybook/addon-links: 5.3.19 => 5.3.19 
    @storybook/addon-storysource: 5.3.19 => 5.3.19 
    @storybook/addons: 5.3.19 => 5.3.19 
    @storybook/preset-create-react-app: 3.0.1 => 3.0.1 
    @storybook/preset-typescript: 3.0.0 => 3.0.0 
    @storybook/react: 5.3.19 => 5.3.19

**Comment by shilman** [comment]
There are too many props-related issues to support on both SB5 and SB6, so please upgrade to SB6 with `npx sb@next upgrade --prerelease` and if it's still an issue I'm happy to investigate.

**Comment by doglasbatista** [comment]
The error continues even with the version 6.0.0-rc.1 :disappointed:

npmPackages:
    @storybook/addon-actions: 6.0.0-rc.1 => 6.0.0-rc.1 
    @storybook/addon-docs: 6.0.0-rc.1 => 6.0.0-rc.1 
    @storybook/addon-knobs: 6.0.0-rc.1 => 6.0.0-rc.1 
    @storybook/addon-links: 6.0.0-rc.1 => 6.0.0-rc.1 
    @storybook/addon-storysource: 6.0.0-rc.1 => 6.0.0-rc.1 
    @storybook/addons: 6.0.0-rc.1 => 6.0.0-rc.1 
    @storybook/preset-create-react-app: 3.1.3 => 3.1.3 
    @storybook/preset-typescript: 3.0.0 => 3.0.0 
    @storybook/react: 6.0.0-rc.1 => 6.0.0-rc.1

**Comment by shilman** [comment]
Thanks for upgrading. I’ll give it a look during the RC period!

**Comment by shilman** [comment]
can you try upgrading to the latest RC?

**Comment by doglasbatista** [comment]
Hey @shilman, sorry for the delay man.

I still have this problem here
![image](https://user-images.githubusercontent.com/5438099/90806522-84bb0200-e2f3-11ea-97b2-4c28122910c4.png)

```
npmPackages:
    @storybook/addon-a11y: ^6.0.16 => 6.0.16 
    @storybook/addon-actions: 6.0.16 => 6.0.16 
    @storybook/addon-docs: 6.0.16 => 6.0.16 
    @storybook/addon-knobs: 6.0.16 => 6.0.16 
    @storybook/addon-links: 6.0.16 => 6.0.16 
    @storybook/addon-storysource: 6.0.16 => 6.0.16 
    @storybook/addons: 6.0.16 => 6.0.16 
    @storybook/preset-create-react-app: 3.1.4 => 3.1.4 
    @storybook/preset-typescript: 3.0.0 => 3.0.0 
    @storybook/react: 6.0.16 => 6.0.16 
```

**Comment by shilman** [comment]
hmm @hipstersmoothie does this look like an issue on the storybook side, or `react-docgen-typescript`?

**Comment by hipstersmoothie** [comment]
PR is up now! https://github.com/styleguidist/react-docgen-typescript/pull/286

This doesn't solve for defaults stored in another file. but i'll wait til the next issue to fix that ;P

**Comment by hipstersmoothie** [comment]
Since the PR on `react-docgen-typescript` has been merged this should no longer be a problem. If the issue persists or didn't cover @doglasbatista's use case enough feel free to open another issue and tag me in it!
