### ISSUE TITLE
[Storybook 6.0.0-rc.0] build fails on sass-loader 

### ISSUE THREAD

**Issue by dpouliot** [storybookjs/storybook#11466]
**Describe the bug**
I'm testing upgrading my storybook 5.3 repo to 6. I haven't changed the `webpack.config.js`, but Storybook fails on build with:
```bash
Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> @import "../../../assets/mixins";
```

**Code snippets**
```js
const path = require("path");
const webpack = require('webpack');
const config = require('../package.json');

module.exports = {
  module: {
    rules: [
      {
        test: /\.scss$/,
        loaders: ["style-loader", "css-loader", "sass-loader"],
        include: path.resolve(__dirname, "../"),
      },
      {
        test: /\.css$/,
        use: [
          'style-loader',
          {
            loader: 'css-loader',
            options: {
              importLoaders: 1,
              sourceMap: true,
            },
          },
        ],
      },
      {
        test: /\.(ttf|eot|png|svg|gif|ico|woff(2)?)(\?[a-z0-9=&.]+)?$/,
        loader: 'file-loader?name=[name].[ext]',
      }
    ]
  },
  plugins: [
    new webpack.DefinePlugin({
      VERSION: JSON.stringify(config.version),
    }),
  ],
};
```
**System:**
Environment Info:

  System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
  Binaries:
    Node: 10.21.0 - /usr/local/bin/node
    Yarn: 1.18.0 - /usr/local/Cellar/yarn/1.22.4/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 83.0.4103.116
    Edge: 81.0.416.77
    Firefox: 76.0.1
    Safari: 13.1.1
  npmPackages:
    @storybook/addon-a11y: 6.0.0-rc.0 => 6.0.0-rc.0 
    @storybook/addon-actions: 6.0.0-rc.0 => 6.0.0-rc.0 
    @storybook/addon-backgrounds: 6.0.0-rc.0 => 6.0.0-rc.0 
    @storybook/addon-docs: 6.0.0-rc.0 => 6.0.0-rc.0 
    @storybook/addon-knobs: 6.0.0-rc.0 => 6.0.0-rc.0 
    @storybook/addon-links: 6.0.0-rc.0 => 6.0.0-rc.0 
    @storybook/addon-notes: 6.0.0-rc.0 => 6.0.0-alpha.6 
    @storybook/addon-options: 6.0.0-rc.0 => 6.0.0-alpha.29 
    @storybook/addon-storyshots: 6.0.0-rc.0 => 6.0.0-rc.0 
    @storybook/addon-storysource: 6.0.0-rc.0 => 6.0.0-rc.0 
    @storybook/addon-viewport: 6.0.0-rc.0 => 6.0.0-rc.0 
    @storybook/addons: 6.0.0-rc.0 => 6.0.0-rc.0 
    @storybook/react: 6.0.0-rc.0 => 6.0.0-rc.0 
    @storybook/source-loader: 6.0.0-rc.0 => 6.0.0-rc.0

**Comment by shilman** [comment]
So to confirm, this config was working fine in 5.3 and is now failing in 6.0?

**Comment by dpouliot** [comment]
Yes.

**Comment by ron23** [comment]
Same issue here

**Comment by ndelangen** [comment]
Can someone help me reproduce this issue on my local machine? A repo that shows this issue would really help get this fixed.

I can also help you @dpouliot get the storybook repo setup so you can fix this? Happy to take a meeting request:
https://calendly.com/ndelangen/storybook

**Comment by dpouliot** [comment]
@ndelangen 
https://drive.google.com/file/d/10oD9Z2Tt0zGhMqvAw6bPxE04YqIXxiSN/view?usp=sharing
Let me know once you've got it, I'd like to take it down.
Storybook 5 will build successfully. Storybook 6 won't.

**Comment by ron23** [comment]
I realized my issue was a bit different. 
I have babelrc file with the following plugin:

```
["transform-rename-import", { "original": "^(.+?)\\.scss$", "replacement": "$1.css" }]
```

I got errors saying the files couldn't find the *.css file (probably because babel already transformed it to use .css).
This wasn't happening before on 5.2 or 5.3.

**Comment by ndelangen** [comment]
@shilman didn't you do some recent changes to babel config loading?

**Comment by shilman** [comment]
Yeah, but AFAIK only related to processing `.mdx` files.

- Before: The MDX handler was including user babel config
- After: The MDX handler only includes Storybook configuration by default and users need to override the `babelrc/babelConfig: false` if they want a custom babel configuration. I expect most users won't want to do this ever.

The change shouldn't affect any other file types in the project.

**Comment by ndelangen** [comment]
ok, so it's not that then. thanks.

**Comment by ndelangen** [comment]
@dpouliot got it

**Comment by ndelangen** [comment]
I investigated:

The webpack extend mode is no longer supported in Storybook V6. 
The best course of action is to migrate to the `main.js` config file format introduced in 5.3:
https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#to-mainjs-configuration

Once you've done that migrating to SB6 should be easier.

To get sass support in SB6 we actually have an example here:
https://storybook.js.org/docs/configurations/custom-webpack-config/#examples

**Comment by ndelangen** [comment]
Previously you could do:
```js
// webpack.config.js 
const path = require("path");
const webpack = require('webpack');
const config = require('../package.json');

module.exports = {
  // ...
};
```

That's no longer supported, this is the new way:
```js
// .storybook/main.js
const path = require('path');

// Export a function. Accept the base config as the only param.
module.exports = {
  webpackFinal: async (config, { configType }) => {
    // `configType` has a value of 'DEVELOPMENT' or 'PRODUCTION'
    // You can change the configuration based on that.
    // 'PRODUCTION' is used when building the static version of storybook.

    // Make whatever fine-grained changes you need
    config.module.rules.push({
      test: /\.scss$/,
      use: ['style-loader', 'css-loader', 'sass-loader'],
      include: path.resolve(__dirname, '../'),
    });

    // Return the altered config
    return config;
  },
};
```

**Comment by ndelangen** [comment]
Please re-open if this doesn't fix it, and you find storybook is not compatible with sass-loader in some way.

**Comment by dpouliot** [comment]
@ndelangen Thank you, this basically fixed it. There are other issues, but I'll follow up on those through the appropriate channels.

**Comment by amcdnl** [comment]
@ndelangen - I'm having this issue w/ the CRA default setup. Have you ran into this there?

**Comment by rohanvachheta** [comment]
@amcdnl  having same issue , can anyone please help me with that ,thanks

**Comment by productfrontenddeveloper** [comment]
> Previously you could do:
> 
> ```js
> // webpack.config.js 
> const path = require("path");
> const webpack = require('webpack');
> const config = require('../package.json');
> 
> module.exports = {
>   // ...
> };
> ```
> 
> That's no longer supported, this is the new way:
> 
> ```js
> // .storybook/main.js
> const path = require('path');
> 
> // Export a function. Accept the base config as the only param.
> module.exports = {
>   webpackFinal: async (config, { configType }) => {
>     // `configType` has a value of 'DEVELOPMENT' or 'PRODUCTION'
>     // You can change the configuration based on that.
>     // 'PRODUCTION' is used when building the static version of storybook.
> 
>     // Make whatever fine-grained changes you need
>     config.module.rules.push({
>       test: /\.scss$/,
>       use: ['style-loader', 'css-loader', 'sass-loader'],
>       include: path.resolve(__dirname, '../'),
>     });
> 
>     // Return the altered config
>     return config;
>   },
> };
> ```

```
SassError: expected "{".
  ╷
1 │ import api from "!../node_modules/style-loader/dist/runtime/injectStylesIntoStyleTag.js";
  │                                                                                         ^
  ╵
  src/index.scss 1:89  root stylesheet
    at processResult (/Users/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/NormalModule.js:700:19)
    at /node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/NormalModule.js:806:5
    at /Users/node_modules/@storybook/builder-webpack5/node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at /node_modules/@storybook/builder-webpack5/node_modules/loader-runner/lib/LoaderRunner.js:251:18
    at context.callback (/node_modules/@storybook/builder-webpack5/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at /node_modules/sass-loader/dist/index.js:54:7
    at Function.call$2 (/node_modules/sass/sass.dart.js:93041:16)
    at _render_closure.call$0 (/node_modules/sass/sass.dart.js:81441:23)
    at Object.Primitives_applyFunction (/node_modules/sass/sass.dart.js:1124:30)
    at Object.Function_apply (/node_modules/sass/sass.dart.js:5894:16)
    at _callDartFunctionFast (/node_modules/sass/sass.dart.js:7596:16)
    at /node_modules/sass/sass.dart.js:7574:18
SassError: SassError: expected "{".
```

**Comment by ndelangen** [comment]
@productfrontenddeveloper 

I can't help you based on 1 sass-loader webpack error.

My comment wasn't really about sass-loader. It was about the change from `webpack.config.js` to `main.js`.

This: `// Make whatever fine-grained changes you need`
Is meant to simply be an example of what you can do. It's not a recommendation on how to fix anything.

**Comment by FreakyHarsh** [comment]
> > Previously you could do:
> > ```js
> > // webpack.config.js 
> > const path = require("path");
> > const webpack = require('webpack');
> > const config = require('../package.json');
> > 
> > module.exports = {
> >   // ...
> > };
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > That's no longer supported, this is the new way:
> > ```js
> > // .storybook/main.js
> > const path = require('path');
> > 
> > // Export a function. Accept the base config as the only param.
> > module.exports = {
> >   webpackFinal: async (config, { configType }) => {
> >     // `configType` has a value of 'DEVELOPMENT' or 'PRODUCTION'
> >     // You can change the configuration based on that.
> >     // 'PRODUCTION' is used when building the static version of storybook.
> > 
> >     // Make whatever fine-grained changes you need
> >     config.module.rules.push({
> >       test: /\.scss$/,
> >       use: ['style-loader', 'css-loader', 'sass-loader'],
> >       include: path.resolve(__dirname, '../'),
> >     });
> > 
> >     // Return the altered config
> >     return config;
> >   },
> > };
> > ```
> 
> @ndelangen
> 
> ```
> SassError: expected "{".
>   ╷
> 1 │ import api from "!../node_modules/style-loader/dist/runtime/injectStylesIntoStyleTag.js";
>   │                                                                                         ^
>   ╵
>   src/index.scss 1:89  root stylesheet
>     at processResult (/Users/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/NormalModule.js:700:19)
>     at /node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/NormalModule.js:806:5
>     at /Users/node_modules/@storybook/builder-webpack5/node_modules/loader-runner/lib/LoaderRunner.js:399:11
>     at /node_modules/@storybook/builder-webpack5/node_modules/loader-runner/lib/LoaderRunner.js:251:18
>     at context.callback (/node_modules/@storybook/builder-webpack5/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
>     at /node_modules/sass-loader/dist/index.js:54:7
>     at Function.call$2 (/node_modules/sass/sass.dart.js:93041:16)
>     at _render_closure.call$0 (/node_modules/sass/sass.dart.js:81441:23)
>     at Object.Primitives_applyFunction (/node_modules/sass/sass.dart.js:1124:30)
>     at Object.Function_apply (/node_modules/sass/sass.dart.js:5894:16)
>     at _callDartFunctionFast (/node_modules/sass/sass.dart.js:7596:16)
>     at /node_modules/sass/sass.dart.js:7574:18
> SassError: SassError: expected "{".
> ```

I'm facing the same issue. Any leads?

**Comment by tbogard** [comment]
installing sass-loader@10 fixed most of my problems. I had to deal with NX generator for storybook to allow including fonts! I had to use `CopyWebpackPlugin` to allow my fonts to be accessible as intended in my scss project.

**Comment by tbogard** [comment]
```js
// webpack.config.json in your .storybook folder
const TsconfigPathsPlugin = require('tsconfig-paths-webpack-plugin');
const rootWebpackConfig = require('../../../.storybook/webpack.config');
const CopyWebpackPlugin = require('copy-webpack-plugin');
const path = require('path');
/**
 * Export a function. Accept the base config as the only param.
 *
 * @param {Parameters<typeof rootWebpackConfig>[0]} options
 */
module.exports = async ({ config, mode }) => {
  config = await rootWebpackConfig({ config, mode });

  const tsPaths = new TsconfigPathsPlugin({
    configFile: './tsconfig.base.json',
  });

  config.resolve.plugins
    ? config.resolve.plugins.push(tsPaths)
    : (config.resolve.plugins = [tsPaths]);

  // Found this here: https://github.com/nrwl/nx/issues/2859
  // And copied the part of the solution that made it work

  const svgRuleIndex = config.module.rules.findIndex((rule) => {
    const { test } = rule;

    return test.toString().startsWith('/\\.(svg|ico');
  });
  config.module.rules[svgRuleIndex].test =
    /\.(ico|jpg|jpeg|png|gif|eot|otf|webp|ttf|woff|woff2|cur|ani|pdf)(\?.*)?$/;

  config.module.rules.push(
    {
      test: /\.(png|jpe?g|gif|webp)$/,
      loader: require.resolve('url-loader'),
      options: {
        limit: 10000, // 10kB
        name: '[name].[hash:7].[ext]',
      },
    },
    {
      test: /\.svg$/,
      oneOf: [
        // If coming from JS/TS file, then transform into React component using SVGR.
        {
          issuer: {
            test: /\.[jt]sx?$/,
          },
          use: [
            {
              loader: require.resolve('@svgr/webpack'),
              options: {
                svgo: false,
                titleProp: true,
                ref: true,
              },
            },
            {
              loader: require.resolve('url-loader'),
              options: {
                limit: 10000, // 10kB
                name: '[name].[hash:7].[ext]',
                esModule: false,
              },
            },
          ],
        },
        // Fallback to plain URL loader.
        {
          use: [
            {
              loader: require.resolve('url-loader'),
              options: {
                limit: 10000, // 10kB
                name: '[name].[hash:7].[ext]',
              },
            },
          ],
        },
      ],
    },
    {
      test: /\.scss$/,
      use: ['style-loader', 'css-loader', 'sass-loader'],
      include: path.resolve(__dirname, '../src'),
    },
    {
      test: /\.(woff(2)?|ttf|eot|svg)(\?v=\d+\.\d+\.\d+)?$/,
      use: [
        {
          loader: 'file-loader',
          options: {
            name: '[name].[ext]',
            outputPath: 'assets/fonts/',
          },
        },
      ],
      include: path.resolve(__dirname, '../src/app/lib/fonts/'),
    }
  );

  config.plugins.push(
    new CopyWebpackPlugin({
      patterns: [
        {
          from: path.resolve(__dirname, '../src/app/lib/fonts/'),
          to: 'assets/fonts',
        },
      ],
    })
  );

  return config;
};
```

**Comment by ksielyov** [comment]
99% done plugins webpack-hot-middlewarewebpack built preview cf6bb7c17b1db928f3cc in 11382ms
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: expected "{".
  ╷
2 │       import API from "!../../node_modules/style-loader/dist/runtime/injectStylesIntoStyleTag.js";
  │                                                                                                  ^
  ╵
  components/Button/styles.module.scss 2:98  root stylesheet
    at processResult (/Users/mikhailkiselyov/WebstormProjects/tajwork/node_modules/webpack/lib/NormalModule.js:758:19)
    at /Users/mikhailkiselyov/WebstormProjects/tajwork/node_modules/webpack/lib/NormalModule.js:860:5
    at /Users/mikhailkiselyov/WebstormProjects/tajwork/node_modules/loader-runner/lib/LoaderRunner.js:400:11
    at /Users/mikhailkiselyov/WebstormProjects/tajwork/node_modules/loader-runner/lib/LoaderRunner.js:252:18
    at context.callback (/Users/mikhailkiselyov/WebstormProjects/tajwork/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at Object.loader (/Users/mikhailkiselyov/WebstormProjects/tajwork/node_modules/sass-loader/dist/index.js:69:5)
    at runNextTicks (internal/process/task_queues.js:60:5)
    at processImmediate (internal/timers.js:437:9)


```
const TsconfigPathsPlugin = require('tsconfig-paths-webpack-plugin');

module.exports = {
  "stories": [
    "../**/*.stories.mdx",
    "../**/*.stories.@(js|jsx|ts|tsx)",
  ],
  "addons": [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/addon-interactions",
    "@storybook/preset-scss",
    "storybook-addon-next"
  ],
  "framework": "@storybook/react",
  "core": {
    "builder": "@storybook/builder-webpack5"
  },
  "webpackFinal": async (config) => {
    config.resolve.plugins = [
      ...(config.resolve.plugins || []),
      new TsconfigPathsPlugin({
        extensions: config.resolve.extensions,
      }),
    ];
    return config;
  },
}
```

**Comment by huraji** [comment]
> 99% done plugins webpack-hot-middlewarewebpack built preview cf6bb7c17b1db928f3cc in 11382ms ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js): SassError: expected "{". ╷ 2 │ import API from "!../../node_modules/style-loader/dist/runtime/injectStylesIntoStyleTag.js"; │ ^ ╵ components/Button/styles.module.scss 2:98 root stylesheet at processResult (/Users/mikhailkiselyov/WebstormProjects/tajwork/node_modules/webpack/lib/NormalModule.js:758:19) at /Users/mikhailkiselyov/WebstormProjects/tajwork/node_modules/webpack/lib/NormalModule.js:860:5 at /Users/mikhailkiselyov/WebstormProjects/tajwork/node_modules/loader-runner/lib/LoaderRunner.js:400:11 at /Users/mikhailkiselyov/WebstormProjects/tajwork/node_modules/loader-runner/lib/LoaderRunner.js:252:18 at context.callback (/Users/mikhailkiselyov/WebstormProjects/tajwork/node_modules/loader-runner/lib/LoaderRunner.js:124:13) at Object.loader (/Users/mikhailkiselyov/WebstormProjects/tajwork/node_modules/sass-loader/dist/index.js:69:5) at runNextTicks (internal/process/task_queues.js:60:5) at processImmediate (internal/timers.js:437:9)
> 
> ```
> const TsconfigPathsPlugin = require('tsconfig-paths-webpack-plugin');
> 
> module.exports = {
>   "stories": [
>     "../**/*.stories.mdx",
>     "../**/*.stories.@(js|jsx|ts|tsx)",
>   ],
>   "addons": [
>     "@storybook/addon-links",
>     "@storybook/addon-essentials",
>     "@storybook/addon-interactions",
>     "@storybook/preset-scss",
>     "storybook-addon-next"
>   ],
>   "framework": "@storybook/react",
>   "core": {
>     "builder": "@storybook/builder-webpack5"
>   },
>   "webpackFinal": async (config) => {
>     config.resolve.plugins = [
>       ...(config.resolve.plugins || []),
>       new TsconfigPathsPlugin({
>         extensions: config.resolve.extensions,
>       }),
>     ];
>     return config;
>   },
> }
> ```

How did you fixed this? I am having the same issue with nx / react.
