### ISSUE TITLE
Menu tooltip is not aligned in 6.0 RC

### ISSUE THREAD

**Issue by domyen** [storybookjs/storybook#11468]
**Describe the bug**
The menu tooltip is misaligned. It was caused by [these styles](https://github.com/storybookjs/storybook/commit/e1425c90660833b183f1e321f5d117d1d0fb1fe9#diff-4375d40e4d5c41d7a7a5aef77e493c29R44) committed in [this PR](https://github.com/storybookjs/storybook/pull/9210).

![image](https://user-images.githubusercontent.com/263385/86955735-0ed54f80-c126-11ea-8e93-0dfacfca8ecf.png)

**To Reproduce**
1. Go to [latest on `next`](https://next--storybookjs.netlify.app/official-storybook/) ([this worked correctly in 5.3](https://storybookjs.netlify.app/official-storybook/?path=/story/ui-sidebar-sidebarheading--menu-highlighted))
2. Click on the menu in the sidebar
3. See misaligned button above

**Expected behavior**
It is aligned correctly.

**Comment by shilman** [comment]
Yo-ho-ho!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-rc.2 containing PR #11469 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
