### ISSUE TITLE
Menu tooltip shows scrollbar

### ISSUE THREAD

**Issue by domyen** [storybookjs/storybook#11470]
**Describe the bug**
The menu tooltip shows a scrollbar when more links can fit on the page.

**To Reproduce**
1. Go to latest [official SB on next](https://next--storybookjs.netlify.app/official-storybook/?path=/story/addons-a11y-basebutton--default)
2. Click on menu
3. See scrollbar

**Expected behavior**
It shouldn't show the scrollbar.

**Screenshots**
![image](https://user-images.githubusercontent.com/263385/86961327-0b929180-c12f-11ea-907c-8a90d7a68174.png)

**Comment by shilman** [comment]
Zoinks!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-rc.2 containing PR #11471 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
