### ISSUE TITLE
@storybook/addon-controls -- Uncaught TypeError: (0 , _api.useArgTypes) is not a function

### ISSUE THREAD

**Issue by undefinederror** [storybookjs/storybook#11485]
As soon as I add @storybook/addon-controls in main.js addons I get a blank page in browser and these errors in browser console

Warning: Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state.
Warning: Failed prop type: Invalid prop `title` of type `function` supplied to `SafeTab`, expected `string`.
The above error occurred in one of your React components:
The above error occurred in the `<LocationProvider>` component:
Uncaught TypeError: (0 , _api.useArgTypes) is not a function

My addons
```
addons: [
    "@storybook/addon-storysource", 
    "@storybook/addon-actions",
    "@storybook/addon-a11y",
    "@storybook/addon-viewport",  
    "@storybook/addon-docs",
    "@storybook/addon-controls"  
  ]
```

Am I doing anything wrong?

**System:**
Environment Info:

  System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-2700K CPU @ 3.50GHz
  Binaries:
    Node: 10.16.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.19.1 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.8.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    @storybook/addon-a11y: ^5.3.19 => 5.3.19
    @storybook/addon-actions: >=5.3.0 => 5.3.19
    @storybook/addon-controls: ^6.0.0-rc.1 => 6.0.0-rc.1
    @storybook/addon-docs: ^5.3.19 => 5.3.19
    @storybook/addon-links: >=5.3.0 => 5.3.19
    @storybook/addon-storysource: ^5.3.19 => 5.3.19
    @storybook/addon-viewport: ^5.3.19 => 5.3.19
    @storybook/vue: >=5.3.0 => 5.3.19

**Comment by shilman** [comment]
5.x and 6.x not compatible, you need to upgrade all your packages:
```
npx sb@next upgrade --prerelease
```

**Comment by undefinederror** [comment]
Hi @shilman,
Thanks for the reply.
It does indeed work if upgrading everything to 6.x. :+1: 

Is this the only way to use @storybook/addon-controls? Since I see that it doesn't have any release 5.x.
If so I feel like documentation could definitely benefit from an extra line about that.

![image](https://user-images.githubusercontent.com/8209966/87126389-6392da80-c28c-11ea-8978-fa2716cf6112.png)
