### ISSUE TITLE
options addon link in README 404s

### ISSUE THREAD

**Issue by corysimmons** [storybookjs/storybook#11482]
![image](https://user-images.githubusercontent.com/224636/87044893-2ca5c180-c1c5-11ea-822f-9f6cfc70e7b3.png)

Seems like it was deprecated/removed from addons folder: https://www.npmjs.com/package/@storybook/addon-options

Maybe point it to https://storybook.js.org/docs/configurations/options-parameter/ or just remove it to avoid confusion?

**Comment by corysimmons** [comment]
.

**Comment by shilman** [comment]
Fixed
