### ISSUE TITLE
Controls: Add mechanism to reset control state

### ISSUE THREAD

**Issue by BPScott** [storybookjs/storybook#11487]
https://github.com/storybookjs/storybook/blob/next/addons/controls/README.md#template-stories demonstrates the power of template stories. It means I can write something like the following, leveraging a template and creating multiple stories with different args:

```js
import React from 'react';
import {Button, ButtonProps} from '../src';

export default {
  title: 'Playground/0-Button - CSF',
  component: Button,
};

const Template = (args: ButtonProps) => <Button {...args} />;
Template.args = {} as ButtonProps;

export const ButtonDefault = Template.bind({});
ButtonDefault.args = {children: 'Hello Button'};

export const ButtonWithPrimary = Template.bind({});
ButtonWithPrimary.args = {children: 'Hello Button', primary: true};

```

However after a fun day of editing controls in the addons panel, such as toggling `primary` to false in the `ButtonWithPrimary` story I find myself in a state where my story state no longer reflects what I wanted to demo in the story and I've changed so many controls that I'm not sure where I started (obviously not in this contrived example with one control, but imagine example a component with several controls.

I can reset the state by reloading the whole page but that feels rather clunky.  Perhaps there should be a button within the Controls panel that resets the state to its initial value?

There could be a button for each individual controle to reset that particular value, and also a button to reset all controls to their initial state.

**Comment by shilman** [comment]
Yee-haw!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-rc.5 containing PR #11519 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Good golly!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-rc.8 containing PR #11550 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
