### ISSUE TITLE
About, release notes, keyboard shortcuts pages go blank 

### ISSUE THREAD

**Issue by domyen** [storybookjs/storybook#11483]
**Describe the bug**
When I go to about, release notes, or keyboard shortcuts page in the [latest built Storybook for `next`](https://next--storybookjs.netlify.app/official-storybook/?path=/settings/release-notes), the page goes blank.

[Video of that here](https://www.loom.com/share/79ea9ef961024134bce9ee21100068f8)

**To Reproduce**
1. Go to https://next--storybookjs.netlify.app/official-storybook/?path=/settings/release-notes
2. Click on menu and then on the "about" link
3. The page goes blank

**Expected behavior**
The page does not go blank. Storybook should show the content in a tabbed interface.

**Comment by ndelangen** [comment]
I'm on it

**Comment by shilman** [comment]
Ta-da!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-rc.16 containing PR #11700 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
