### ISSUE TITLE
Text knob is not rendering special character as expected

### ISSUE THREAD

**Issue by michielmetcake** [storybookjs/storybook#11493]
**Describe the bug**
Text knob is escaping the value in the canvas. When using the '&' in the text knob the rendered value of '&' is equal to '&amp'

**To Reproduce**
1. Go to https://next--storybookjs.netlify.app/official-storybook/?path=/story/addons-knobs-withknobs--tweaks-static-values
2. Click on 'knobs' tab
3. Scroll down to the 'name' input
4. Change name to 'Storyteller & bla'
5. See canvas contains '&amp' 

**Expected behavior**
Not escape the text.

**Comment by psimyn** [comment]
this looks due to the `escapeHTML` option - https://github.com/storybookjs/storybook/blob/18e0738b46355f5e4de3f20b944d08aa2f204c60/addons/knobs/README.md#withknobs-options

**Comment by shilman** [comment]
FYI, we’ve released addon-controls in 6.0-beta. Controls are portable, auto-generated knobs that are intended to replace addon-knobs long term.

- [Controls README](https://github.com/storybookjs/storybook/tree/next/addons/controls)
- [Migration instructions](https://github.com/storybookjs/storybook/blob/next/addons/controls/README.md#how-do-i-migrate-from-addon-knobs)
- [Walkthrough: Controls w/ CRA & TypeScript](https://gist.github.com/shilman/69c1dd41a466bae137cc88bd2c6ef487)

Please upgrade and try them out today!
