### ISSUE TITLE
@storybook/addon-controls with vuejs, props show up only if statically typed

### ISSUE THREAD

**Issue by undefinederror** [storybookjs/storybook#11494]
**Describe the bug**
props come up in the controls tab only when statically typed

**To Reproduce**
I have a `schema.js` file when I keep the component props 

```
export default {
  cta: {
    type: String,
    default: "some text",
    required: true
  },
  url: {
    type: String
  }
};
```
Then in my component
```
import schema from "./schema"

export default {
  name: 'WCtaButton',
  props: schema,
  methods: {
    onClick() {
      this.$emit('onClick', new Date().toLocaleString())
    }
  }
}
```

This unfortunately doesn't populate props

![image](https://user-images.githubusercontent.com/8209966/87148054-f85a0000-c2ad-11ea-9b06-86b72937d99e.png)

If I copy paste the content of `schema.js` in  `props`
```
export default {
  name: 'WCtaButton',
  props: {
    cta: {
      type: String,
      default: "some text",
      required: true
    },
    url: {
      type: String
    }
  },
  methods: {
    onClick() {
      this.$emit('onClick', new Date().toLocaleString())
    }
  }
}
```
Then props come up in controls

![image](https://user-images.githubusercontent.com/8209966/87148163-335c3380-c2ae-11ea-8863-bbc8be280029.png)

**Additional context**
Unfortunately I need to have props in a separate schema.js, as that is by design for the application where these components are imported in.

**System:**
Environment Info:

  System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-2700K CPU @ 3.50GHz
  Binaries:
    Node: 10.16.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.19.1 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.8.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    @storybook/addon-a11y: ^6.0.0-rc.1 => 6.0.0-rc.1
    @storybook/addon-actions: ^6.0.0-rc.1 => 6.0.0-rc.1
    @storybook/addon-controls: ^6.0.0-rc.1 => 6.0.0-rc.1
    @storybook/addon-docs: ^6.0.0-rc.1 => 6.0.0-rc.1
    @storybook/addon-links: >=6.0.0-rc.1 => 6.0.0-rc.1
    @storybook/addon-storysource: ^6.0.0-rc.1 => 6.0.0-rc.1
    @storybook/addon-viewport: ^6.0.0-rc.1 => 6.0.0-rc.1
    @storybook/vue: ^6.0.0-rc.1 => 6.0.0-rc.1

**Comment by shilman** [comment]
@elevatebart do you know anything about this?

As a workaround you can manually define argTypes for your component: https://github.com/storybookjs/storybook/blob/next/addons/controls/README.md#my-controls-arent-being-auto-generated-what-should-i-do

**Comment by elevatebart** [comment]
I do know anything about it.

The static analyser vue-docgen-api is very fast because it does not compile nor loads any extra file that it does not understand.

I have wanted to solve this for a while: to be able to define prop definitions in a variable then use this variable in the props. Then it would matter very little if the variable is in the same file or not. If the type definition is a variable name, I would try to replace the variable name by its initial value and do the prop resolution this way.

Vue does not have a concept of shape in prop types. This would have been, for me the strongest appeal for a use case.

@mesqueeb what is your opinion on this one?

I have not had time to investigate how to do

**Comment by shilman** [comment]
@elevatebart thanks for the fast reply! given we have a workaround i don't think it's critical on the storybook side. but i guess you have another potential user here in @undefinederror if you do manage to solve it. 🚀

**Comment by undefinederror** [comment]
Hey @elevatebart indeed should you manage to solve this I'd be first in line to try it out 😄 

Thank you @shilman, yes I can do with the `argTypes` workaround for now. I can parse my schema.js and convert into argTypes format.

I am experiencing another weird issue though with the component in canvas not being reactive, while the same component in Docs is.
I am going to open a dedicated issue for that.

**Comment by mesqueeb** [comment]
I'm personally not a fan of extracting the entire "props" section into a separate "schema.js", so I'm not sure. 😅 

I am more interested in allowing JSDoc typedefs like so:
<img width="440" alt="image" src="https://user-images.githubusercontent.com/3253920/87209109-bda6a500-c34b-11ea-9dec-7fa7d53a615f.png">

And then have the actual type of this typedef provided in the JSON that `vue-docgen` provides via the loader, so I can create some custom documentation for this. 😉 

But I believe that's a different topic / repository, so I digress.
