### ISSUE TITLE
Storybook for Angular nrwl/nx Multi-Tenant Monorepo - selects first project but should take a name as parameter

### ISSUE THREAD

**Issue by mchl18** [storybookjs/storybook#11499]
**Is your feature request related to a problem? Please describe.**

Hello,

while running storybook in a multi tenant monorepo we discovered a problem while loading configs. This happens when using `@nx/storybook`. It loads the correct storybook config but not the correct angular config.

Currently the storybook inetgration with angular cli only lets us use a default-project for compilation. If there is none it just takes the first one. We however have a repo with mutliple applications and no default-project. 
With the current implemetation we cannot pass the project name for loading things such as styles.

The only way to load a specific tenant is either setting a default project or rewriting the config file just for running storybook, both of which are not scalable. We need to be able to set the project name by passing an argument or setting a config.

The problematic lines of code:

@storybook\angular\dist\server\angular-cli_config.js
```javascript
    var defaultProject = ngCliConfig.defaultProject;
    var projects = ngCliConfig.projects;
    if (!projects || !Object.keys(projects).length) {
        throw new Error('angular.json must have projects entry.');
    }
    var projectName;
    var firstProjectName = Object.keys(projects)[0];
    if (projects.storybook) {
        projectName = 'storybook';
    }
    else if (defaultProject && projects[defaultProject]) {
        projectName = defaultProject;
    }
    else if (projects[firstProjectName]) {
        projectName = firstProjectName;
    }
    var project = projects[projectName];

```

**Describe the solution you'd like**
It would be really nice if the selection of projects would try to match with a parameter which is being passed along or at least read the name from the storybook config which is already being passed along fine.

**Are you able to assist bring the feature to reality?**

 yes, if anyone is able to explain me which is the best entry point for passing a parameter as such.

**Additional context**

```
    "@nrwl/storybook": "^9.5.1",
    "@storybook/angular": "^5.3.19",
```

**Comment by luisferreira90** [comment]
I am having the same problem. It would be great if we could use environment variables to choose the default project.

**Comment by shilman** [comment]
Ooh-la-la!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.0-alpha.22 containing PR #12565 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by artaommahe** [comment]
@shilman i'll copy my comment from that pr

> Can we have some config param instead of env var? It's hard to use env var for each stroybook run (we have monorepo with many apps and storybooks too) and would be more convenient to declare this value once in config and just run regular dev/prod storybook builds
