### ISSUE TITLE
@storybook/addon-controls with vuejs, component reactive in docs while not reactive in canvas

### ISSUE THREAD

**Issue by undefinederror** [storybookjs/storybook#11501]
My component is reactive only in Docs tab.

My story
```
export default {
  title: "WCtaButton",
  component: WCtaButton,
  argTypes: {
    url: { control: 'text' },
    cta: { control: 'text' },
  }
}

export const defaultState = (args) => {
  console.log(args)
  return ({
    components: { WCtaButton },
    template: `<div :style="style">
    <w-cta-button v-bind="props"/>
    </div>`,
    data() {
      return {
        style: {
          height: '10em',
          border: '1px solid'
        }
      }
    },
    computed: {
      props() {
        return args
      }
    },
    mounted() {
      console.log('mounted')
    }
  })
};
defaultState.args = adapter(manifest)
```

Controls are populated correctly, defaults included. Though when I start typing the component doesn't update

![image](https://user-images.githubusercontent.com/8209966/87184175-cfeef780-c2e7-11ea-8d57-b026ea775a09.png)

I can see the args, being logged on each input event, but component doesn't get remounted

![image](https://user-images.githubusercontent.com/8209966/87184272-0298f000-c2e8-11ea-8b59-7be86e725137.png)

If I switch tab to Docs, I can immediately see my latest input being rendered, and when I type in more the component is reactive.

![image](https://user-images.githubusercontent.com/8209966/87184413-40961400-c2e8-11ea-83c7-c754315c8ed2.png)

Also, I see that here the component is remounted on each input event

![image](https://user-images.githubusercontent.com/8209966/87184456-5277b700-c2e8-11ea-9c62-049d8943913b.png)

Am I doing anything wrong?

**System info**
Environment Info:

  System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-2700K CPU @ 3.50GHz
  Binaries:
    Node: 10.16.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.19.1 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.8.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
 npmPackages:
    @storybook/addon-a11y: ^6.0.0-rc.1 => 6.0.0-rc.1
    @storybook/addon-actions: ^6.0.0-rc.1 => 6.0.0-rc.1
    @storybook/addon-controls: ^6.0.0-rc.1 => 6.0.0-rc.1
    @storybook/addon-docs: ^6.0.0-rc.1 => 6.0.0-rc.1
    @storybook/addon-links: >=6.0.0-rc.1 => 6.0.0-rc.1
    @storybook/addon-storysource: ^6.0.0-rc.1 => 6.0.0-rc.1
    @storybook/addon-viewport: ^6.0.0-rc.1 => 6.0.0-rc.1
    @storybook/vue: ^6.0.0-rc.1 => 6.0.0-rc.1

**Comment by shilman** [comment]
Take a look at the recommended pattern here:

https://github.com/storybookjs/storybook/blob/next/examples/vue-kitchen-sink/src/stories/addon-controls.stories.js#L11-L15

**Comment by undefinederror** [comment]
Yes, that works, thank you!

Seems like `props: Object.keys(args),` is necessary for reactivity.

thank you

**Comment by Sebastian1830** [comment]
I have the same problem :disappointed: 

`mycomponent.vue`
```vue
<template>
  <div>
    <div class='row'>
      <div class='col-12 bg-primary is-click'>
        <span class='text-h6 q-mx-sm'>{{ hi }}</span>
      </div>
      <div v-if='open' class='col-12 bg-grey-3'>
        <slot></slot>
      </div>
    </div>
  </div>
</template>

<script lang='ts'>
import { defineComponent, reactive, computed } from 'vue';

export default defineComponent({
  name: 'detailsHidden',
  props: {
    open: { type: Boolean, default: false },
    name: { type: String, default: 'Juan' }
  },
  setup(props) {
    const p = reactive(props)
    const hi = computed(() => { return `Welcome ${p.name} !` })
    return { hi }
  }
});
</script>

<style lang='scss' scoped>
  @import "detailsHidden.scss";
</style>
```

`mycomponent.stories.js`
```js
import detailsHidden from './detailsHidden.vue';
import { QBtn } from 'quasar';

export default {
  title: 'Test/FuDetailsHidden',
  component: detailsHidden,
  argTypes: {
    name: { control: "text" },
    open: { control: "boolean" }
  }
}

const Template = (args, { argTypes }) => ({
    components: { detailsHidden, QBtn },
    props: Object.keys(argTypes),
    template: '<details-hidden v-bind="$props">' +
      '           <div class=\'q-mx-md q-my-md\'>\n' +
      '               <span>This is a storybook</span>\n' +
      '               <q-btn color="secondary" label="Secondary" class="q-ml-lg" />\n' +
      '           </div>' +
      '        </details-hidden>'
});

export const FirstStory = Template.bind({});
FirstStory.args = {
  name: 'Sophia',
  open: false
}
```
`package.json`
```json
{
...
    "@storybook/addon-actions": "^6.2.0-alpha.29",
    "@storybook/addon-essentials": "^6.2.0-alpha.29",
    "@storybook/addon-links": "^6.2.0-alpha.29",
    "@storybook/addon-postcss": "^2.0.0",
    "@storybook/vue3": "^6.2.0-alpha.29",
...
}
```
**What can be wrong? , please help me** :raised_hands:
