### ISSUE TITLE
[Angular 7] Warning "The Types mismatch" while using same argTypes in Controls addon

### ISSUE THREAD

**Issue by akhilesh85** [storybookjs/storybook#11508]
**Describe the bug**
When there are two select option control arg types with the same name declared in two different stories have different data types. This warning popups up. The behavior is observed in the Angular 7 workspace on Mac. When I investigated the warning comes from merge.js in @storybook/api/dist/lib/merge.js

**To Reproduce**
1. Add the same argTypes to two stories with different data types. For Instance, assign one with JSON and the other an Array.
2. Then start the storybook, you will be able to see the error in the console as shown in the screenshot.

**Expected behavior**
As these are two different stories it should not check the objValue and srcValue from two different stories.

**Screenshots**

![IMG-8229](https://user-images.githubusercontent.com/67741191/87224506-6c80ca80-c3b8-11ea-9861-285476253426.JPG)
![IMG-8230](https://user-images.githubusercontent.com/67741191/87224510-6ee32480-c3b8-11ea-99a7-076be806e986.JPG)
![IMG-8231](https://user-images.githubusercontent.com/67741191/87224511-70ace800-c3b8-11ea-87d0-c8a111d2ed22.JPG)

**Code snippets**

**button.stories.ts**

`export default {
  title: 'UIUX/Button',
  component: Button,
  argTypes: {
    text: {control: 'text'},
    bgColor: {control: 
      { type: 'select', options:  {"white": "#fff", "Red": "#F00", "Green": "#0F0"}}
    }}
};`

**label.stories.ts**

`export default {
  title: 'UIUX/Label',
  component: Label,
  argTypes: { 
    text: {control: 'text'},
    bgColor: {control: 
      { type: 'select', options:  ["#fff", "#F00", "#0F0"]}
    }}
};`

**System:**

Environment Info:

  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7 CPU @ 2.60GHz
  Binaries:
    Node: 12.18.0 - /usr/local/bin/node
    npm: 6.14.4 -  /usr/local/bin/npm
  Browsers:
    Chrome: 80.0.3987.132
    Safari: 13.1.1
  npmPackages:
    @storybook/addon-actions: ^6.0.0-rc.3 => 6.0.0-rc.3
    @storybook/addon-controls: ^6.0.0-rc.3 => 6.0.0-rc.3
    @storybook/addon-docs: ^6.0.0-rc.3 => 6.0.0-rc.3
    @storybook/addon-links: ^6.0.0-rc.3 => 6.0.0-rc.3
    @storybook/angular: ^6.0.0-rc.3 => 6.0.0-rc.3

**Comment by shilman** [comment]
Closing as dupe to #11229

**Comment by akhilesh85** [comment]
Super thanks 😊
