### ISSUE TITLE
addon-docs [6.0.0-rc.3]: HTML style comments not showing up in transcluded code blocks

### ISSUE THREAD

**Issue by chris-dura** [storybookjs/storybook#11517]
**Describe the bug**
Comments in fenced code blocks are not displayed when they're transcluded into the MDX story.

**To Reproduce**
1. Create a `.md` file with fenced code blocks containing an HTML style comment (`<!-- -->`)
2. Transclude that `.md` file into a `.mdx` story using the `<Description>` block
3. Run storybook
4. HTML comments are not displayed

**Expected behavior**
HTML comments in fenced code blocks should render.

**Screenshots**
<img width="506" alt="Screen Shot 2020-07-12 at 11 21 59 AM" src="https://user-images.githubusercontent.com/3680914/87252912-fde15280-c433-11ea-9681-bcd67ba9944a.png">

**Code snippets**
readme.md
````md
**README markdown:**

```html
<!-- This is a comment -->
<my-component></my-component>
```
````

my-component.stories.mdx
````mdx
import { Description, Meta, Preview, Story } from '@storybook/addon-docs/blocks';
import readme from './readme.md';

<Meta title="Test" component="my-component"/>

**Inline markdown:**

```html
<!-- This is a comment -->
<my-component></my-component>
```

<Description>{readme}</Description>
````

**System:**
```
Environment Info:

  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4960HQ CPU @ 2.60GHz
  Binaries:
    Node: 12.18.0 - ~/.nvm/versions/node/v12.18.0/bin/node
    Yarn: 1.16.0 - ~/.yarn/bin/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.0/bin/npm
  Browsers:
    Chrome: 83.0.4103.116
    Firefox: 70.0.1
    Safari: 13.1.1
  npmPackages:
    @storybook/addon-a11y: ^6.0.0-rc.3 => 6.0.0-rc.3 
    @storybook/addon-actions: ^6.0.0-rc.3 => 6.0.0-rc.3 
    @storybook/addon-controls: ^6.0.0-rc.3 => 6.0.0-rc.3 
    @storybook/addon-docs: ^6.0.0-rc.3 => 6.0.0-rc.3 
    @storybook/addon-google-analytics: ^6.0.0-rc.3 => 6.0.0-rc.3 
    @storybook/addon-jest: ^6.0.0-rc.3 => 6.0.0-rc.3 
    @storybook/addon-knobs: ^6.0.0-rc.3 => 6.0.0-rc.3 
    @storybook/addon-links: ^6.0.0-rc.3 => 6.0.0-rc.3 
    @storybook/addon-notes: ^6.0.0-alpha.6 => 6.0.0-alpha.6 
    @storybook/addon-viewport: ^6.0.0-rc.3 => 6.0.0-rc.3 
    @storybook/theming: ^6.0.0-rc.3 => 6.0.0-rc.3 
    @storybook/web-components: ^6.0.0-rc.3 => 6.0.0-rc.3
```

**Comment by shilman** [comment]
FYI `addon-docs` supports first-class transclusion in 6.0 -- maybe try that?

https://github.com/storybookjs/storybook/pull/11334

**Comment by chris-dura** [comment]
@shilman -- thanks! That option worked (at least for the `.mdx` files)!

Unfortunately, I'm in the process of migrating away from CSF (*.tsx) stories using the `notes` addon, towards (hopefully) all MDX stories. I followed the [migrating recipe](https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/recipes.md#migrating-from-notesinfo-addons) and setting the `transcludeMarkdown: true` seems to break my legacy CSF stories that I haven't moved to MDX yet, and the notes aren't showing up in those stories anymore :/

**Comment by shilman** [comment]
@chris-dura Yeah. It's an all or nothing change.
