### ISSUE TITLE
"Show code" not properly positioned after switching tabs

### ISSUE THREAD

**Issue by jpzwarte** [storybookjs/storybook#11520]
See the video.

Storybook 6.0.0-rc.3, on a mac Firefox Developer Edition.

[Screen Recording 2020-07-13 at 09.03.25.zip](https://github.com/storybookjs/storybook/files/4911075/Screen.Recording.2020-07-13.at.09.03.25.zip)

Reproducible in FF, not in Chrome.

**Comment by domyen** [comment]
Closing, we chatted about this in Discord. This was a Firefox rendering bug upstream of us that has to do with layout reflows when animations
