### ISSUE TITLE
@storybook/addon-controls with vuejs, argType on nested arg property

### ISSUE THREAD

**Issue by undefinederror** [storybookjs/storybook#11525]
This is just a question.

say I have 
```
Default.args = {
  config: {
    bg: '#fff'
  }
}
```
Is there any way to define config.bg as `{ control: { type: color } }`?

Thank you

**Comment by shilman** [comment]
Not currently. We need to figure out how to provide nested controls in a future iteration.

**Comment by undefinederror** [comment]
Yeah, I was fearing that.
Ok, thank you.
