### ISSUE TITLE
Storybook 6 Vue docgen cannot parse component file in ESM export from other file

### ISSUE THREAD

**Issue by jackysee** [storybookjs/storybook#11521]
**Describe the bug**

When using vue component in its compiled form (esm), vue-docgen-api cannot extract the documentation if the component itself is exporting from other files.

**To Reproduce**
1. Clone this repo `https://github.com/jackysee/storybookVueDocgenDemo` 
2. run `npm ci` 
3. run `npm run storybook`
4. open browser 

**Expected behavior**
The props table of `Test` component should appear at doc tab.

**Screenshots**
![image](https://user-images.githubusercontent.com/30516/87281438-ce127780-c525-11ea-8710-24f044bea289.png)

**Code snippets**
Component `Test.js`
```
export { _ as default } from "./test-1234";
```

`test-1234.js`

```
const comp = {
  render(h) {
    return h("div", this.name);
  },
  props: {
    name: { type: String },
  },
};

export { comp as _ };
```

`Test.stories.js`

```
import Test from "../dist/Test";

export default {
  title: "Test",
  component: Test,
};

export const Default = () => ({
  components: { Test },
  template: `
      <div>
        <test name="TEST NAME"></test>
      </div>
  `,
});
```
`main.js`
```
const path = require("path");

module.exports = {
  stories: ["../stories/**/*.stories.*"],
  addons: [
    "@storybook/addon-docs",
    // "@storybook/addon-links",
    // "@storybook/addon-actions",
    // "@storybook/addon-essentials",
  ],
  webpackFinal: async (config) => {
    config.module.rules.push({
      test: /\.js$/,
      include: [path.resolve(__dirname, "../dist/Test.js")],
      use: "vue-docgen-loader",
      enforce: "post",
    });
    return config;
  },
};

```

**System:**
```
Environment Info:
  System:
    OS: Linux 5.4 Manjaro Linux
    CPU: (2) x64 Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
  Binaries:
    Node: 12.13.0 - /tmp/fnm-shell-9297708/bin/node
    npm: 6.12.0 - /tmp/fnm-shell-9297708/bin/npm
  Browsers:
    Firefox: 77.0.1
  npmPackages:
    @storybook/addon-actions: ^6.0.0-rc.3 => 6.0.0-rc.3
    @storybook/addon-essentials: ^6.0.0-rc.3 => 6.0.0-rc.3
    @storybook/addon-links: ^6.0.0-rc.3 => 6.0.0-rc.3
    @storybook/vue: ^6.0.0-rc.3 => 6.0.0-rc.3
```

**Additional context**
I'm making a storybook for a library where I use the rollup compiled source directly. The source code may look like that.

**Comment by shilman** [comment]
Workaround `component: test1234` if you import that directly into your story

**Comment by jackysee** [comment]
The test component is a simplified case, a typical component entry would look like

```
import './Config.js';
import './_commonjsHelpers-a9661e55.js';
import './runtime-0c23bc81.js';
import './_rollupPluginBabelHelpers-71961d8c.js';
export { _ as default } from './icon-f175ce6b.js';
import './normalize-component-4c117f32.js';
```

**Comment by jackysee** [comment]
vue-docgen-api should have fixed this https://github.com/vue-styleguidist/vue-styleguidist/commit/f7ac47cf89667e389670c11f44f3edc7e1cdfd0f

**Comment by jackysee** [comment]
Tried to manual install vue-docgen-api to latest (4.28.0), now the component cannot be found.

**Comment by shilman** [comment]
We're now on `"vue-docgen-api": "^4.29.1",` FWIW
