### ISSUE TITLE
toRequireContext does not work in all cases

### ISSUE THREAD

**Issue by daniel-ac-martin** [storybookjs/storybook#11530]
Storybook v6.0.0-rc.3 accepts globs to describe the location of 'stories' files. It appears to attempt to convert these globs into calls to `require.context`. - https://github.com/storybookjs/storybook/blob/next/lib/core/src/server/preview/to-require-context.ts#L28

It currently sets the `recursive` flag based on whether the glob contains a 'globstar' / `**` pattern:
```js
      const recursive = glob.startsWith('**');
```

However, many other globs will also need this flag to be set. For example, `../components/*/stories/*.js`; without the recursive flag webpack will never look in the `stories/` directories and so no stories will be found.

I've not had time to think it through fully, but it seems like any glob (after being split from its `base` will need the recursive flag if it contains more than one `/`.

If my argument hold so far, then I think it's important to point out that one of the consequences of this is that globs cannot always be fully represented as calls to `require.context` as `require.context` will need to traverse the entire base and the regexp will be used to eliminate unwanted matches afterwards. In some cases (such as when `node_modules/` directories are being traversed) this can lead to webpack running out of memory.

Additionally, it seems to me that if the following code is still required;
```js
      if (source.startsWith('^')) {
        // prepended '^' char causes webpack require.context to fail
        const match = source.substring(1);

        return { path: base, recursive, match };
      }
```
it will be impossible to represent wildcard (`*`) globs, such as the example above, that should _not_ match across directories.

**Comment by daniel-ac-martin** [comment]
```js
// prepended '^' char causes webpack require.context to fail
```
I suspect that this is simply due to the regexp being applied to a path that starts `./`. i.e. It should be possible to patch the regexp to handle that and reinstate the `^` for stricter matching.

**Comment by daniel-ac-martin** [comment]
I think that PR largely addresses his issue. Except that webpack will (usually) traverse the entire base-directory even in the absence of a globstar (`**`) which is pretty unintuitive and can lead to huge memory consumption.

I think this is unavoidable with `require.context` though. - It would be nice if it let us limit the depth.

**Comment by daniel-ac-martin** [comment]
Now that PR's been merged I wonder whether this issue should be closed or whether it is worth starting a campaign to improve `require.context`.

FWIW, it _looks like_ the starting point to improving the implementation would be here: https://github.com/webpack/webpack/blob/master/lib/dependencies/RequireContextDependencyParserPlugin.js#L18

Mind you it looks like a related subject was brought up quite recently (and storybook was even mentioned): https://github.com/webpack/webpack/issues/11149
I'm not sure I understand the resolution to that one.

There's also this that I still believe to be relevant: https://github.com/webpack/webpack/issues/2952

If nothing else, I think it's worth noting that Storybook users are likely to encounter failures due to huge memory consumption when globbing for story files in a monorepo in which each component has it's own package and therefore `node_modules/` dir. In these cases require.context will descend into those `node_modules/` directories (and perhaps into an infinite symlink loop) even though the glob would imply that it shouldn't do so.

And those users are likely to blame Storybook. :-/

**Comment by shilman** [comment]
@daniel-ac-martin Thanks so much for your work identifying the issue and improving the situation.

I don't fully understand all the moving pieces here, but I wonder if it would be possible to statically detect some common patterns that would incorrectly dive into node_modules with a warning and a link to storybook documentation that explains how to rewrite your globes to avoid this. What do you think?

**Comment by daniel-ac-martin** [comment]
Hi @shilman.

Unfortunately, that will be the case a lot of the time and I don't think it is possible to avoid by re-writing globs. It will happen whenever the `recursive` flag is set on `require.context`. The logic for that is here: https://github.com/storybookjs/storybook/blob/next/lib/core/src/server/preview/to-require-context.ts#L34

And now I look at it again, I wonder if the code should _actually_ be:
```ts
      const recursive = glob.includes('**') || glob.split('/').length > 1;
```
i.e. `1` and not `2`.
(Unfortunately the flag is not covered by the unit tests. - I don't think it could be, really.)

Or to put it another way:
- `../base-dir/*.stories.jsx`: fine, no need for recursion
- `../base-dir/**.stories.jsx`: needs recursion
- `../base-dir/*/index.stories.jsx`: needs recursion (or webpack will never look inside the directories)

To be more clear the scenario that I believe would be problematic would be when someone has a monorepo and is packaging components individually. (So that consumers can just pick the ones the want to use.) Imagine the following structure:
```
./components/foo/Foo.jsx
./components/foo/Foo.stories.jsx
./components/foo/node_modules/[...]
./components/foo/package.json
./components/bar/Bar.jsx
./components/bar/Bar.stories.jsx
./components/bar/node_modules/[...]
./components/bar/package.json
./.storybook/main.js (glob = '../components/*/*.stories.jsx')
./package.json
```

(After the amendment I suggest above.) This would lead the to `require.context`'s `recursive` flag being set and webpack descending into `./components/foo/node_modules/` and `./components/bar/node_modules/`. (And if they depend on each other I think you would get an infinite loop due to circular symlinks.)

I suppose to warn against it, perhaps you could look for files managing monorepos such as `lerna.json` or `pnpm-workspace.yaml` and then seeing if the glob would match any packages. That might work...

**Comment by ndelangen** [comment]
fixed in https://github.com/storybookjs/storybook/pull/11647
