### ISSUE TITLE
Storybook 5.3 failing to install on node 8

### ISSUE THREAD

**Issue by IanVS** [storybookjs/storybook#11544]
**Describe the bug**
Due to inquirer dropping support for node 8 in a minor version (7.3.0), it's no longer possible to install @storybook/react@5.3.x in node 8.

**To Reproduce**
1. `nvm use 8`
2. `yarn add --dev @storybook/react@5.3`
3. `error chalk@4.1.0: The engine "node" is incompatible with this module. Expected version ">=10". Got "8.17.0"`

**Expected behavior**
It should install without error

**Additional context**
I traced this down to https://github.com/SBoudrias/Inquirer.js/issues/940.  One workaround that storybook could do is to release a 5.3 patch using `inquirer@7.2.0` instead of relying on semver and `^7.0.0`.  For now, I've been able to work around this using `resolutions` in my package.json, but that's not ideal.  Hopefully inquirer will release a fix, but I wanted to at least raise this issue here because that's where I ran into it and others might too.

**Comment by IanVS** [comment]
@shilman it doesn't seem like inquirer will be making a change to follow semver.  Would you accept a PR to lock down to 7.2.0?  Otherwise folks trying to install storybook 5.3 using node 8 will have a bad time.

**Comment by IanVS** [comment]
Hi Stalebot, I'm still willing to submit a PR to lock down the version of inquirer, if that would be useful/acceptable to the maintainers.

**Comment by shilman** [comment]
I believe Node 10 is required. cc @ndelangen

**Comment by IanVS** [comment]
Storybook 5.3 supports Node 8, or at least used to except for the inquirer dependency breaking semver in a minor release.

**Comment by ndelangen** [comment]
In 5.3 we started testing Storybook on Node10 only:
https://github.com/storybookjs/storybook/commit/0ae3036091dec03ff1ca52f992110f2a165acf5b

**Comment by IanVS** [comment]
But your `engines` still only indicates that node 8 or above is required: https://github.com/storybookjs/storybook/blob/a939e7204a448e9d24e5431f1c9dba8dd7ec05e9/app/react/package.json#L71

And if you decide to require a more recent version of node, I think the right thing to do is to make that change at a major semver version bump.  I realize that everyone should be using more modern versions of node by now, but some of us poor saps are stuck at an old version for the time being.

**Comment by ndelangen** [comment]
@IanVS I sympathize. Can you downgrade to a lower version of storybook if you need node 8 support?

We need to change this in 6.0.x. We don't test with Node 8, we don't support it.
https://github.com/storybookjs/storybook/blob/a939e7204a448e9d24e5431f1c9dba8dd7ec05e9/app/react/package.json#L71

**Comment by IanVS** [comment]
What is the last version of storybook which does officially support node 8?  I'm using the latest 5.3.x right now with success, as long as I force inquirer 7.2.0 to be installed instead of 7.3.0 by setting `resolutions` in my package.json.  I guess I just thought it would be an easy change to lock that version in storybook and restore node 8 support.

**Comment by shilman** [comment]
<img width="743" alt="Mouse_Highlight_Overlay" src="https://user-images.githubusercontent.com/488689/95009866-b693e800-0657-11eb-8314-be74b08b56ec.png">

**Comment by IanVS** [comment]
Hi @shilman, yes I understand that Node 8 is out of support.  But some people like me are forced to still use it because of complicated reasons.  I think it is a project's responsibility to bump their major version any time a "breaking" change is made, and that dropping support for an execution environment is a breaking change.  It definitely broke my usage.  

I'm not asking that storybook continue to support old node versions, just that you are clear about which versions of storybook support which versions of node.  @ndelangen suggested I downgrade to an old version of storybook.  But I cannot tell which version I would need to downgrade to.  And no matter what, your `engines` in package.json should be updated to reflect your current level of support.

And ideally, a simple change to lock storybook 5.x to inquirer 7.2 would restore node 8 compatibility, allowing you to say that 5.x will at least _probably_ work in node 8 (even if it's not totally tested), and 6.x is node 10+.  Would you consider a PR that makes these changes?

**Comment by shilman** [comment]
@IanVS The dependency in 5.3 is:

```
    "inquirer": "^7.0.0",
```

Why can't you just install inquirer@7.2.0 in your project and then yarn should use that since it satisfies the version specifier?

**Comment by IanVS** [comment]
Yes, I did figure that out, but it took me a while of troubleshooting to determine what was going on.  I was just suggesting that you could make it easier on users by changing from `"^7.0.0"` to `"^7.2.0"`.  But if you're not interested in making any changes, feel free to close this out.  I was just trying to be helpful for others, that's all.  Thanks for hearing me out.
