### ISSUE TITLE
Addon-controls: Make sure all argTypes are args (even if undefined)

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#11555]
When we construct the initial set of args, we don't include an arg in the initial state if it doesn't have a default value. (Thanks to @backbone87 for helping me figure this all out).

This conflicts with our idiom for args in Vue, e.g.

```js
const Template = (args) => ({
  props: Object.keys(args),
  components: { MyButton },
  ...
});
```

Supposing I have an argType like this, e.g. in #11505 

```js
  argTypes: {
    backgroundColor: { control: "color" },
  },
```

Because it's default value is undefined, it doesn't get set in `args` initially, and doesn't get a prop, causing the control for `backgroundColor` to have no effect.

**Comment by shilman** [comment]
Another option is to update the idiom to be:

```js
const Template = (args, { parameters }) => ({
  props: Object.keys(parameters.argTypes),
...
```

This solves the problem, but is a little verbose.

**Comment by tmeasday** [comment]
Are we sure there'll be an arg type for every arg though?

**Comment by shilman** [comment]
Pretty sure we will:

https://github.com/storybookjs/storybook/blob/next/addons/docs/src/frameworks/common/enhanceArgTypes.ts#L13

**Comment by tmeasday** [comment]
And if they aren't using docs?

**Comment by shilman** [comment]
Zoinks!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-rc.5 containing PR #11558 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Son of a gun!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-rc.8 containing PR #11561 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
