### ISSUE TITLE
Loading stories from a YAML file in storybook 6.

### ISSUE THREAD

**Issue by christianwiedemann** [storybookjs/storybook#11553]
I want to generate dynamic stories from a YAML file in stroybook 6 and above. 

### Steps to reproduce
In storybook 5.x it was possible to provide a load function where I can load the YAML inside the preview.js and generate stories with storiesof api from this YAML file. 
With storybook 6 I get deprecated messages with the notice that I should using a GLOB inside the main.js to load stories. 

It is still working but I get:

``` 
`configure()` is deprecated and will be removed in Storybook 7.0. 
Please use the `stories` field of `main.js` to load stories.
Read more at https://github.com/storybookjs/storybook/MIGRATE.md#deprecated-configure
``` 

What is the correct way to load stories with storiesof api in storybook 6+

Thanks

**Comment by shilman** [comment]
I'd recommend looking at https://github.com/storybookjs/storybook/tree/next/app/server

It's loading in JSON files with a custom webpack loader that "compiles to CSF", which I'm guessing is very similar to what you want

**Comment by christianwiedemann** [comment]
Thanks for help!
