### ISSUE TITLE
Inline styling of any html tag inside <Preview> throws error

### ISSUE THREAD

**Issue by dcts** [storybookjs/storybook#11565]
**Describe the bug**
Html written inside a `Preview` element (inside an MDX file) throws an error when trying to set inline-styling with `style=""`.

**To Reproduce**
I am using lit-element [storybook template by open-wc](https://open-wc.org/demoing/), not sure if you need further information?

**Expected behavior**
I expected that adding properties to html-tags would not break the storybook.

**Code snippets**
my file **`mystory.stories.mdx`**:
```mdx
import { Story, Preview, Meta, Props, html } from '@open-wc/demoing-storybook';
import '../src/MyComponent.js';

<Meta
  title="atoms|MyComponent"
  parameters={{
    options: { selectedPanel: "storybookjs/knobs/panel" }
  }}
/>

# MyComponent
<Preview>
  <div style="background-color: black;">
    <my-component></my-component>
  </div>
</Preview>
```

**Screenshots**
![Bildschirmfoto von 2020-07-15 18-15-21](https://user-images.githubusercontent.com/44790691/87569343-44021480-c6c7-11ea-92af-fa9a332c2b40.png)

**System:**
```
Environment Info:
  System:
    OS: Linux 5.3 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.21.1 - /usr/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v12.16.1/bin/npm
  Browsers:
    Chrome: 83.0.4103.116
    Firefox: 78.0.1

```

**Comment by shilman** [comment]
Try `style={{ backgroundColor: 'black' }}`?

**Comment by dcts** [comment]
> Try `style={{ backgroundColor: 'black' }}` which is valid React?

Thanks a lot, this worked! I didnt work at all with react so wasn't aware of the syntax! Thanks!

**Comment by romitestream** [comment]
how to put style={{ font-size: "10px" }}

the mdx throwing an error -  Could not parse expression with acorn
means the '-' in between font and size creates an error, If i put style={{ width: "10px" }} this acceptable
help me to get rid of this issue.
