### ISSUE TITLE
docs: Render markdown content error in the document site

### ISSUE THREAD

**Issue by baurine** [storybookjs/storybook#11573]
**Describe the bug**

The document site page renders some markdown contents incorrectly, which will misguide the readers.

**To Reproduce**

The incorrect content link: https://storybook.js.org/docs/basics/writing-stories/#story-file-location

![image](https://user-images.githubusercontent.com/1284531/87638791-f0e79a80-c776-11ea-9caf-6662bef6a6ff.png)

The `src` and `components` folders look like at the same level but actually `components` is a sub-folder of `src` shows in the below which is just copied and pasted.

**Expected behavior**

```
•
└── src
    └── components
        └── button
            ├── button.js
            └── button.stories.js
```

**Comment by alas1n** [comment]
@shilman I think this is fixed, 
because there is no **Story file location** section in [page](https://storybook.js.org/docs/basics/writing-stories/#story-file-location):

**Comment by shilman** [comment]
Thanks @alas1n, closing. Please let me know if there's more to be done here!
