### ISSUE TITLE
Common name prefix causes rapid switching between stories on load

### ISSUE THREAD

**Issue by pelotom** [storybookjs/storybook#11571]
This appears to have been introduced in 6.0.0-beta.33.

Using these stories:

```js
import { storiesOf } from '@storybook/react';
import React from 'react';

storiesOf('test', module)
  .add('x y', () => {
    console.log('render x y'); 
    return <div>x y</div>
  })
  .add('x', () => {
    console.log('render x');
    return <div>x</div>
  });
```

if you start on the "x" story and then reload the page, it will switch to the "x y" story, and the console prints

```
render x y
render x
render x y
```

(In my real project using typescript it actually switches between the 2 stories many more times, sometimes endlessly.)

This seems somehow related to the fact that the second story's name is a prefix of the first. If you change the second story name to "x z" the bug doesn't occur. It also doesn't occur if you change the order of the stories or change which one is selected at the beginning.

**Comment by pelotom** [comment]
Ping? Just want to make sure this doesn't fall thru the cracks before the release!

**Comment by shilman** [comment]
Thanks for the ping @pelotom -- I missed this one somehow. Are you still seeing it on the latest RC? `npx sb@next upgrade --prerelease` to make sure all the packages are up to date.

**Comment by pelotom** [comment]
Hi @shilman, I tried with the latest and it's still happening.

**Comment by shilman** [comment]
Do you have a public repro you can share?

**Comment by pelotom** [comment]
Sure: https://github.com/pelotom/storybook-bug-11571

**Comment by tmeasday** [comment]
I'll take a look, thanks @pelotom

**Comment by shilman** [comment]
Crikey!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-rc.14 containing PR #11637 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by pelotom** [comment]
Thanks guys!

**Comment by shilman** [comment]
Whoopee!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-rc.15 containing PR #11660 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.
