### ISSUE TITLE
Invalid default values for VueJS components in props table

### ISSUE THREAD

**Issue by jonhuteau** [storybookjs/storybook#11582]
**Describe the bug**
I'm upgrading to v6.0.0-rc.8 and defaults values in props tables are empty. If I revert changes made at https://github.com/storybookjs/storybook/pull/11534/files#diff-ac92839dce97cc5e5fdcc8587102c691, I can see default values.

**To Reproduce**
1. Go to https://next--storybookjs.netlify.app/vue-kitchen-sink/?path=/docs/button--rounded
2. Look at button's default values
3. `controls` should be OK but `default` col contains empty string (for `color` prop for example)

**Expected behavior**
Default values should be present in `default` column of props table

**Screenshots**

![image](https://user-images.githubusercontent.com/58468627/87683830-cea74a00-c781-11ea-9c2e-1613013a46f3.png)

**System:**
```
$ npx -p @storybook/cli@next sb info

Environment Info:

  System:
    OS: Linux 4.15 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
  Binaries:
    Node: 12.18.2 - /usr/bin/node
    npm: 6.14.5 - /usr/bin/npm
  Browsers:
    Chrome: 83.0.4103.116
    Firefox: 78.0.2
  npmPackages:
    @storybook/addon-a11y: ^6.0.0-rc.8 => 6.0.0-rc.8 
    @storybook/addon-controls: ^6.0.0-rc.8 => 6.0.0-rc.8 
    @storybook/addon-docs: ^6.0.0-rc.8 => 6.0.0-rc.8 
    @storybook/addon-jest: ^6.0.0-rc.8 => 6.0.0-rc.8 
    @storybook/addon-viewport: ^6.0.0-rc.8 => 6.0.0-rc.8 
    @storybook/addons: ^6.0.0-rc.8 => 6.0.0-rc.8 
    @storybook/vue: ^6.0.0-rc.8 => 6.0.0-rc.8 
```

**Comment by shilman** [comment]
Thanks @jonhuteau -- will get it sorted!

**Comment by shilman** [comment]
Egads!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-rc.11 containing PR #11603 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
