### ISSUE TITLE
Controls panel does not refresh properly

### ISSUE THREAD

**Issue by priandsf** [storybookjs/storybook#11586]
**Describe the bug**
The controls panel (from addon-controls) does not proper refresh when selecting a different story on the same component.

**To Reproduce**
1 Go to https://lwc-essentials.github.io/storybook/lwc-library/?path=/story/units-1-attributes--default-with-args
2 Add some test to attrString (ex' ABCDEF'). You see the JSON dump being updated
3 Select the next story ('Default With Spread Args'). The attrString in the control panel still hold the previous value but the current component does not consume it. Add one character, 'G', at the end of edited value to make 'ABCDEFG'. Now the component picks up the whole value
4 When you switch back between the 2 stories, it looks like they no have their own values.

**Expected behavior**
on Step 3, the panel should should empty values

**Screenshots**
N/A

**Code snippets**
N/A

**System:**
"@storybook/core": "6.0.0-rc.8",
  System:
    OS: macOS 10.15.5
    CPU: (16) x64 Intel(R) Xeon(R) CPU E5-1680 v2 @ 3.00GHz
  Binaries:
    Node: 12.18.2 - ~/.nvm/versions/node/v12.18.2/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v12.18.2/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v12.18.2/bin/npm
  Browsers:
    Safari: 13.1.1

**Additional context**
N/A

**Comment by tmeasday** [comment]
@shilman I think this is likely just a problem with `undefined` coming down the line into your stateful control component.

I added a repro in the branch 11586-fix-args-refresh:

https://www.loom.com/share/c195dee7689040b7bb5d0edae88d443f

**Comment by shilman** [comment]
Yee-haw!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-rc.12 containing PR #11619 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by priandsf** [comment]
Thanks, first quick tests show it working properly!
