### ISSUE TITLE
Storybook shows no story content on Heroku

### ISSUE THREAD

**Issue by larsreith** [storybookjs/storybook#11580]
**Describe the bug**
I build storybook locally, and it runs fine (both start-storybook and serve storybook-static)
I deploy it on Heroku. It builds and deploys fine. It shows the navigation, but no content for the stories

**To Reproduce**
1. Go to https://teamx-storybook.herokuapp.com/?path=/story/web-app--header

**Expected behavior**
Story content should display in IFrame. For example the welcome story.
![Storybook-empty-stories-on-heroku](https://user-images.githubusercontent.com/1035293/87680212-6ce4e100-c77d-11ea-85a0-ff87634fb3c9.png)

On Heroku, the static build is served with serve storybook-static (I removed the -s as this yield to the nested IFrame issue)
I don't know how to further debug this, the console shows no issues.

**Comment by shilman** [comment]
I think this is a known issue with `serve`.

Can you try either:
```
cd storybook-static
serve
```

OR:
```
http-server storybook-static
```

**Comment by larsreith** [comment]
@shilman 

Perfect, your proposal just works fine!
Thank you very much, highly appreciated :)

Lars
