### ISSUE TITLE
Addon-Docs: Props of subcomponents are not indexed

### ISSUE THREAD

**Issue by gisu** [storybookjs/storybook#11583]
**Describe the bug**
With the current Storybook 6 RC 8 I want to display the props of my subcomponents within the MDX files. In the beta I did this using `<Props components={{ProjectOverview, ProjectOverviewEntry, ProjectOverviewProgress}} />`, but in RC this seems to be impossible. I only get the props of the main component displayed. So I can even omit `components={{}}`, I still get the props of the main component when I note `<props />` in the MDX file.

**Expected behavior**
Representation of the props of the main and sub components.

**Code snippets**
Example Documentation with MDX (Vue)

```mdx
import { Meta, Story, Props, Preview } from '@storybook/addon-docs/blocks'
import ProjectOverview from './ProjectOverview.vue'
import ProjectOverviewEntry from './ProjectOverviewEntry.vue'
import ProjectOverviewProgress from './ProjectOverviewProgress.vue'

<Meta
  title='Components|component/ProjectOverview'
  component={ ProjectOverview }
/>

export const ProjectOverviewElement = () => ({
  data () {
    return {
      projects: [...]
    }
  },
  components: { ProjectOverview },
  template: `
    <ProjectOverview :projects="projects" />
  `
})

# ProjectOverview

<Preview withToolbar="true">
  <Story name='ProjectOverviewStory'>
    {ProjectOverviewElement.bind({})}
  </Story>
</Preview>

<Props components={{ProjectOverview, ProjectOverviewEntry, ProjectOverviewProgress}} />
```

**System:**
Environment Info:

  System:
    OS: macOS 10.15.5
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 14.4.0 - ~/.nvm/versions/node/v14.4.0/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v14.4.0/bin/npm
  Browsers:
    Chrome: 83.0.4103.116
    Firefox: 78.0.2
    Safari: 13.1.1
  npmPackages:
    @storybook/addon-a11y: ^6.0.0-rc.8 => 6.0.0-rc.8 
    @storybook/addon-actions: ^6.0.0-rc.8 => 6.0.0-rc.8 
    @storybook/addon-backgrounds: ^6.0.0-rc.8 => 6.0.0-rc.8 
    @storybook/addon-controls: ^6.0.0-rc.8 => 6.0.0-rc.8 
    @storybook/addon-docs: ^6.0.0-rc.8 => 6.0.0-rc.8 
    @storybook/addon-knobs: ^6.0.0-rc.8 => 6.0.0-rc.8 
    @storybook/addon-links: ^6.0.0-rc.8 => 6.0.0-rc.8 
    @storybook/addon-storyshots: ^6.0.0-rc.8 => 6.0.0-rc.8 
    @storybook/addon-storysource: ^6.0.0-rc.8 => 6.0.0-rc.8 
    @storybook/addon-viewport: ^6.0.0-rc.8 => 6.0.0-rc.8 
    @storybook/addons: ^6.0.0-rc.8 => 6.0.0-rc.8 
    @storybook/source-loader: ^6.0.0-rc.8 => 6.0.0-rc.8 
    @storybook/vue: ^6.0.0-rc.8 => 6.0.0-rc.8

**Comment by shilman** [comment]
¡Ay Caramba!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-rc.12 containing PR #11612 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
