### ISSUE TITLE
Deprecation warning in v6 beta when using storyshots

### ISSUE THREAD

**Issue by pelotom** [storybookjs/storybook#11585]
I get the following warning when running storyshots with the v6 beta:

```
(node:77094) DeprecationWarning: `configure()` is deprecated and will be removed in Storybook 7.0.
Please use the `stories` field of `main.js` to load stories.
```

even though I've already refactored to use `main.js`. It seems that `initStoryshots` may still be using `configure` under the hood?

**Comment by shilman** [comment]
Boo-yah!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-rc.12 containing PR #11611 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
