### ISSUE TITLE
Storybook >10 seconds to launch, slowed down by merge in transformStoriesRawToStoriesHash

### ISSUE THREAD

**Issue by koop-stripe** [storybookjs/storybook#11591]
**Describe the bug**
Storybook takes 10-15 seconds to launch in production. Most of the time (7-10 seconds) is spent in `transformStoriesRawToStoriesHash` repeatedly calling `merge`.

Screenshots of both are provided below. This only occurs for us when building for production. We have 505 stories in our storybook.

**To Reproduce**
1. Build storybook for production `build-storybook --docs -c .storybook -o .storybook-dist`
2. Start the server, load a page in your browser.
3. Wait 10-15 seconds until the page loads.

Update: I've since confirmed that this also occurs in development mode.

**Expected behavior**
Don't wait 10-15 seconds. 😛 

**Screenshots**
Full performance view:

<img width="1792" alt="storybook-slowdown" src="https://user-images.githubusercontent.com/38669756/87731825-407e9400-c780-11ea-9340-a9e79530d887.png">

Zoomed in on `baseMerge` calls:
![storybook-basemerge](https://user-images.githubusercontent.com/38669756/87731843-483e3880-c780-11ea-9668-8fceb3fc7399.png)

**System:**
System:
OS: macOS 10.15.4
CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
Binaries:
Node: 10.16.0 - ~/.nodenv/versions/10.16.0/bin/node
Yarn: 1.19.1 - ~/.yarn/bin/yarn
npm: 6.9.0 - ~/.nodenv/versions/10.16.0/bin/npm
Browsers:
Chrome: 83.0.4103.116
Firefox: 78.0.1
Safari: 13.1
npmPackages:
@storybook/addon-docs: 6.0.0-rc.5 => 6.0.0-rc.5
@storybook/react: 6.0.0-rc.5 => 6.0.0-rc.5

**Comment by blaine-stripe** [comment]
@shilman Your PR helped a bunch, especially around the stories hash, but it seems that 7 seconds are still being spent in `configure` on page load. 

<img width="811" alt="Screen Shot 2020-07-21 at 5 02 12 PM" src="https://user-images.githubusercontent.com/67979863/88119073-38ee2f00-cb74-11ea-83ed-024024e64518.png">

**Comment by shilman** [comment]
Egads!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-rc.16 containing PR #11707 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Yippee!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-rc.20 containing PR #11740 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
