### ISSUE TITLE
Knobs label update is not reflecting into React Component . Stories implemented into MDX.

### ISSUE THREAD

**Issue by kontactmaneesh** [storybookjs/storybook#11595]
**Describe the bug**
Stories implemented into MDX  and trying to use addon-knobs.
Calling React component and passing some props while calling the react component.
As per Knobs , I am trying to change label dynamically into react component . I am passing label into the react component. Changes are not reflecting. 
To cross-check that did i added knobs properly , I added simple code like button and changing label via knobs and it is working fine . i.e My changes into knobs label are reflecting.

I feel , issue is with react component call , react component is not rendering again .
Kindly provide your help  

**To Reproduce**
Try to modify label , Changes will not reflect.

**Expected behavior**
I am expecting to reflect my changes into react component UI.

**Screenshots**
![image](https://user-images.githubusercontent.com/25843543/87750217-75d6c080-c818-11ea-9e68-5513e5ce79f4.png)

**Code snippets**
Sharing code below, It has been implemented into the MDX file.

1. Story name : grouped stacked bar is not working.
2. Story name : hello is working.

//Adding knobs
import { withKnobs, text} from "@storybook/addon-knobs";

<Meta title="Charts" decorators={[withKnobs]}/>

<Preview>
<Story name="Grouped Stacked Bar">
{ () => {  
  const[example, setExample] = useState();
  
  useEffect(() => {
      setExample(text('label','Database Cluster Nodes'));
  });

      return (
<GroupedStackedBar
            chartData={groupedStackedBarChartData}
            xAxisLabel={example}
            yAxisLabel={'Storage Utilization'}
            chartHeight={150}
            chartWidth={600}
            groupName={['Catalog', 'Data']}
            noDataMsg={`No data`}
            toolTipString={{
                storageUsed: 'Storage used',
                freeSpace: 'Available Space is',
                usedOutOf: 'used out of',
                throughput: 'Throughput',
                latency: 'Latency',
                readTime: 'ReadTime',
            }}
        />
      )
        
}}
</Story>
<Story name="hello">
  {() => { 
  const test = 'Database Cluster Nodes';
  {/* const label = 'Your Name';
  const defaultValue = 'James';
  const groupId = 'GROUP-ID1';
  const value = text(label, defaultValue, groupId); */}
  return (
<button > {text('label','hello') } </button>
  )
  
  }}
</Story>
</Preview>

**System:**
"@storybook/addon-actions": "^5.3.19",
    "@storybook/addon-docs": "^5.3.19",
    "@storybook/addon-knobs": "^5.3.19",
    "@storybook/addon-links": "^5.3.19",
    "@storybook/addon-viewport": "^5.3.19",
    "@storybook/addons": "^5.3.19",

**Additional context**

**Comment by shilman** [comment]
FYI, we’ve released addon-controls in 6.0-beta. Controls are portable, auto-generated knobs that are intended to replace addon-knobs long term.

- [Controls README](https://github.com/storybookjs/storybook/tree/next/addons/controls)
- [Migration instructions](https://github.com/storybookjs/storybook/blob/next/addons/controls/README.md#how-do-i-migrate-from-addon-knobs)
- [Walkthrough: Controls w/ CRA & TypeScript](https://gist.github.com/shilman/69c1dd41a466bae137cc88bd2c6ef487)

Please upgrade and try them out today!

**Comment by kontactmaneesh** [comment]
Thanks a lot for your quick reply with useful information.
I just installed latest version of the control.
And mentioned into main.js file .

addons: ['@storybook/addon-actions', '@storybook/addon-links',
    '@storybook/addon-viewport/register',
    "@storybook/addon-docs", '@storybook/addon-controls'],

"@storybook/addon-controls": "^6.0.0-beta.15",
But I am always facing below issue.   App is unable to up once using control addon.  
If I will remove control addon , it will work fine.

Kindly provide me your valuable input . I want to use control for my stories (MDX).

![image](https://user-images.githubusercontent.com/25843543/87778251-8a32b180-c848-11ea-9237-fa5bbb69b840.png)

**Comment by shilman** [comment]
Upgrade using:
```
npx sb@next upgrade --prerelease
```

**Comment by kontactmaneesh** [comment]
Thanks a lot for your quick reply.
Run npx sb@next upgrade --prerelease command but it is giving me the same issue.
So I updated version directly into package.json 

"@storybook/addon-actions": "^6.0.0-rc.11",
    "@storybook/addon-controls": "^6.0.0-rc.11",
    "@storybook/addon-docs": "^6.0.0-rc.11",
    "@storybook/addon-links": "^^6.0.0-rc.11",
    "@storybook/addon-viewport": "^^6.0.0-rc.11",
    "@storybook/addons": "^^6.0.0-rc.11",
    "@storybook/react": "^^6.0.0-rc.11",
But it is giving me "loose configuration" issue .  
Kindly refer attahment

![image](https://user-images.githubusercontent.com/25843543/87905674-c3ecfd80-ca7e-11ea-9653-3ad3ecde36a6.png)

To solve the above issue, I added a loose configuration into babelrc file plugin .

	"plugins": [ [ "@babel/plugin-proposal-class-properties", { "loose": true } ],
		["@babel/plugin-proposal-private-methods", { "loose": true } ],
]
But issues could not resolve and I am getting a new issue which is related that "Can't resolve 'core-js/modules/"* " Kindly refer attachment.

![image](https://user-images.githubusercontent.com/25843543/87905932-44136300-ca7f-11ea-8923-549da66a7bc1.png)
 
I am trying to solve the above issue also but it's always giving me the same issue.
I added core-js configuration also.

Babelrc configuration 
	"presets": [
		[ "@babel/preset-env",
			{ "targets": {  "browsers": [ "> 1%", "last 2 versions", "not ie <= 8" ] },
				"loose": true,
				"useBuiltIns": "usage",
				"corejs": 3,
				"modules": false
			}
		],
		"@babel/preset-react" ],
	"plugins": [ ["@babel/plugin-proposal-class-properties", { "loose": true } ],
		["@babel/plugin-proposal-private-methods",{"loose": true}],
		["@babel/plugin-transform-runtime", { "helpers": false, "regenerator": true, "corejs": 3 } ]
	]

Package json 
"devDependencies": {
    "@babel/cli": "7.10.1",
    "@babel/core": "7.8.7",
    "@babel/plugin-proposal-class-properties": "7.8.3",
    "@babel/plugin-proposal-private-methods": "^7.8.3",
    "@babel/plugin-transform-runtime": "^7.10.5",
    "@babel/preset-env": "^7.10.4",
    "@babel/preset-react": "7.10.1",
    "@babel/runtime-corejs3": "^7.10.5",
    "@storybook/addon-actions": "^6.0.0-rc.11",
    "@storybook/addon-controls": "^6.0.0-rc.11",
    "@storybook/addon-docs": "^6.0.0-rc.11",
    "@storybook/addon-links": "^^6.0.0-rc.11",
    "@storybook/addon-viewport": "^^6.0.0-rc.11",
    "@storybook/addons": "^^6.0.0-rc.11",
    "@storybook/react": "^^6.0.0-rc.11",
    "babel-loader": "^8.1.0",
    "babel-preset-es2015": "6.24.1",
    "core-js": "3"
  }


I would be really grateful for your reply. 

Note : All issues are started once I am adding addon-control. Once I will remove addon-control from main.js, package.json, and  node module . Everything will work fine.

**Comment by shilman** [comment]
> "@storybook/react": "^^6.0.0-rc.11",

What's going on with your `package.json` here? `^^6.0.0-rc.11` is not a valid version specifier for this and a few other entries.

**Comment by kontactmaneesh** [comment]
it was a typo error. I already corrected and getting same issue.

"@storybook/addon-actions": "^6.0.0-rc.11",
    "@storybook/addon-docs": "^6.0.0-rc.11",
    "@storybook/addon-links": "^6.0.0-rc.11",
    "@storybook/addon-viewport": "^6.0.0-rc.11",
    "@storybook/addons": "^6.0.0-rc.11",
    "@storybook/react": "^6.0.0-rc.11",

**Comment by shilman** [comment]
Did you try clearing `node_modules` and your package lock and reinstalling

**Comment by kontactmaneesh** [comment]
Yes, I tried many times.
Cleaned node_modules, yarn.lock file and did the fresh install. 
But it is always giving me same error. 

Important: If I will use below version so everything will work.

    "@storybook/addon-actions": "^5.3.19",
    "@storybook/addon-docs": "^5.3.19",
    "@storybook/addon-links": "^5.3.19",
    "@storybook/addon-viewport": "^5.3.19",
    "@storybook/addons": "^5.3.19",
    "@storybook/react": "^5.3.19",

**Comment by shilman** [comment]
@ndelangen can you help out with this core-js related issue?

**Comment by kontactmaneesh** [comment]
Thanks, @shilman .  
@ndelangen : please let me know if I can provide further inputs.
I am also trying all the possible scenarios to resolve this issue but did not resolve it till now.

**Comment by kontactmaneesh** [comment]
Hi 
 I am trying for my end but did not get any solution.
Kindly let me know if you have any suggestions which I should try.

**Comment by kontactmaneesh** [comment]
@shilman @ndelangen : Waiting for your needful help.
