### ISSUE TITLE
CLI: Generate compodoc command based on user's setup

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#11609]
According to @LeandroCarolino01 the new angular CLI template is not working out of the box in his project https://github.com/storybookjs/storybook/issues/10869#issuecomment-660639116

> [14:50:23] "./tsconfig.base.json" file was not found in the current directory
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! testing-sb@0.0.0 docs:json: compodoc -p ./tsconfig.base.json -e json -d .
> npm ERR! Exit status 1

We should generate the `docs:json` command based on the user's setup rather than hard-coding it to the latest `angular-cli`. Help wanted @tooppaaa @kroeder @gaetanmaisse 

@LeandroCarolino01 can you help kick this off by telling us more about your setup?

**Comment by LeandroCarolino01** [comment]
Sure, This is my set up

**Comment by shilman** [comment]
@LeandroCarolino01 how about your angular project? Is it generated by `angular-cli`? What version? Do you have a single `tsconfig.json` file or multiple? Do you happen to have the project available publicly?

**Comment by LeandroCarolino01** [comment]
I am going to send you the link to the project on github here, thanks 
https://github.com/LeandroCarolino01/sb-setup

**Comment by shilman** [comment]
@LeandroCarolino01 we've updated the CLI so it's now compatible with older versions of `angular-cli`. After we release the next RC, you can re-run it on a fresh project. Or you can update the breaking line in your `package.json`:

```
    "docs:json": "compodoc -p ./tsconfig.json -e json -d .",
```

**Comment by shilman** [comment]
Whoopee!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-rc.13 containing PR #11622 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

**Comment by LeandroCarolino01** [comment]
Thank you so much, it is working fine now.
