### ISSUE TITLE
Global Args / Toolbars: Mechanism to load preview iframe with particular global args configuration

### ISSUE THREAD

**Issue by BPScott** [storybookjs/storybook#11604]
**Is your feature request related to a problem? Please describe.**

I would like to be able set the preview iframe into a given global args state. This was possible using addon-controls as it passed values into preview iframe's querystring. However it is not clear how to do that with addon-toolbars / global args.

I want to use chromatic/percy to screenshot a story with different values for global args. This would be useful for visual regression testing a story using multiple multiple themes. (disclaimer: this is currently hypothetical but I've raised [feature requests](https://github.com/percy/percy-storybook/issues/146)).
I want to pass a list of story preview iframe urls into acessibility checking tools to check that my themes pass contrast checks etc ([I am doing this currently](https://github.com/Shopify/polaris-react/blob/7a962791a1a55aaf1dbb12d766e0883765d136f0/scripts/pa11y.js#L60-L75)).

In storybook 5.3 I can use addon-controls to [create a toggle between different visual themes](https://5d559397bae39100201eedc1-mbvrgbsbwq.chromatic.com/?path=/story/all-components-button--basic-button) - the "New design language button". This is then passed into the iframe as a query parameter, and I can access the preview iframe directly:

- New design language disabled: https://5d559397bae39100201eedc1-mbvrgbsbwq.chromatic.com/iframe.html?id=all-components-button--basic-button
- New design language enabled light mode: https://5d559397bae39100201eedc1-mbvrgbsbwq.chromatic.com/iframe.html?id=all-components-button--basic-button&contexts=New%20Design%20Language=Enabled%20-%20Light%20Mode
- New design language enabled dark mode: https://5d559397bae39100201eedc1-mbvrgbsbwq.chromatic.com/iframe.html?id=all-components-button--basic-button&contexts=New%20Design%20Language=Enabled%20-%20Dark%20Mode

However when [trialing v6 and replacing my addon-controls usage with addon-toolbars](https://5d559397bae39100201eedc1-wnkvmeevfo.chromatic.com/?path=/story/all-components-button--basic-button), there doesn't seem to be an equivalent functionality for global args.

**Describe the solution you'd like**

A mechanism to load the preview iframe with a particular global args configuration. At its most simplistic, this could be done by storing the serialised state in a query string parametes, though this may have some limitations depending on if global args can be serialized.

Rather than generalising to all global args this could be limited to just defining an initial addon-toolbars state in the same way as how addon-controls sets the `contexts` query param as I think that should all be stringy. This would solve my particular use case.

**Are you able to assist bring the feature to reality?**
no

**Comment by shilman** [comment]
Ermahgerd!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.3.0-beta.2 containing PR #15056 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
