### ISSUE TITLE
[Feature request] Ink Storybook

### ISSUE THREAD

**Issue by streamich** [storybookjs/storybook#11607]
Add support for [`ink`](https://github.com/vadimdemedes/ink) React renderer. It could be a `@storybook/ink` package that works just like `@storybook/react`, but instead renders components in a browser terminal like [`xterm`](https://xtermjs.org/).

**Comment by shilman** [comment]
cc @ghengeveld

**Comment by skorfmann** [comment]
Here's a demo of ink running in a browser via xtermjs https://ink-storybook.netlify.app/ - Would be really nice to take this further and make it an actual storybook package.

**Comment by shilman** [comment]
Cc @ghengeveld
