### ISSUE TITLE
Storybook 6.0 args don't maintain array order.

### ISSUE THREAD

**Issue by lifeiscontent** [storybookjs/storybook#11605]
**Describe the bug**
When using both typescript types and argTypes,  the order of args are not maintained.

**To Reproduce**
1. Create a component that has a prop with multiple options
2. Add story with args
3. See arg order is not maintained

**Expected behavior**
Args are ordered

**Screenshots**
<img width="1083" alt="Screen Shot 2020-07-18 at 3 41 17 PM" src="https://user-images.githubusercontent.com/180963/87863177-53729f00-c90d-11ea-840d-6f9648c5624f.png">

**Code snippets**
using this as props
```tsx
interface Props {
  src: string;
  alt: string;
  size: 'smallest' | 'small' | 'medium' | 'large' | 'largest';
}
```

```tsx
export function Example(
  args: React.ComponentPropsWithoutRef<typeof UIAvatar>
): JSX.Element {
  return <UIAvatar {...args} />;
}

Example.args = {
  src: 'avatar.jpg',
  alt: 'Avatar',
  size: 'medium',
};
```

**System:**
Please paste the results of `npx -p @storybook/cli@next sb info` here.

Environment Info:

  System:
    OS: macOS 10.15.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 12.8.1 - ~/n/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.14.5 - ~/n/bin/npm
  Browsers:
    Firefox: 72.0.2
    Safari: 13.1.2

**Additional context**
I don't know if this is possible, but I love you

**Comment by shilman** [comment]
@hipstersmoothie  is this something you can look into? I think it's happening in `react-docgen-typescript`. Even worse it's nondeterministic, so our snapshot tests become flakey. Any help you can provide would be much appreciated!

**Comment by lifeiscontent** [comment]
@shilman I looked into it more on the TypeScript side, looks like it might be planned to fix this behavior upstream, but currently no fix.

https://github.com/Microsoft/TypeScript/issues/17944

**Comment by hipstersmoothie** [comment]
I could add an option to one of the underlying libraries to sort the props. I'm not sure this will ever get "fixed" in typescript

**Comment by hipstersmoothie** [comment]
Yeah I don't think this is fixable from anyone but the typescript team. So this could probs be closed in the meantime @shilman

**Comment by shilman** [comment]
We added user-configurable sorting here:

https://github.com/storybookjs/storybook/pull/13125
