### ISSUE TITLE
Vue automatic controls, required dependencies

### ISSUE THREAD

**Issue by abrenneke** [storybookjs/storybook#11600]
Looking into this problem is what lead me to work on #11547. So, there are four somewhat unrelated things here:

- [ ] Storybook does not automatically generate controls for Vue as well as it does for React
- [ ] Vue requires `vue-docgen-loader` and docgens created for Vue components - this seems like an unnecessary dependency.
- [ ] `@storybook/addon-controls` requires `@storybook/addon-docs`, which doesn't make much sense to me.
- [ ] `@storybook/addon-docs` has code for each app type directly in it, instead of app-specific (e.g. Vue) code staying in the `@storybook/vue` package.

> Storybook does not automatically generate controls for Vue as well as it does for React

This story will generate controls for React:

```tsx
export default {
  title: 'Button',
  component: Button
};

export const WithArgs = (args: any) => <Button label="etc" />;
```

This story will _not_ generate controls for Vue:

```typescript
export default {
  title: 'Button',
  component: Button
};

export const Button = (args: any) => ({ components: { Button }, template: '<Button label="etc" />' });
```

When I looked into this, it seemed to be because automatic control generation requires either 

a) `vue-docgen-loader` stuff (I couldn't find _any_ documentation on how to get this going, either. It was all in `vue-styleguidist` which is a whole project on its own)
b) Hints such as `Button.args = { label }` and exporting `argTypes: { label: 'text' }`.

This restriction doesn't seem necessary, because the prop types should be extractable from the component options almost as well as in React. It won't have a description or anything, but that's enough.

> Vue requires `vue-docgen-loader` and docgens created for Vue components - this seems like an unnecessary dependency.

Continued from above, it seems like `vue-docgen-loader` is used to extract the prop types from the component, as well as descriptions and such. While that's nice if it's there, it shouldn't be required in order for prop types to be extracted, as most Vue components look like this, and have props that can be realtively easily extracted:

```typescript
export default {
  props: {
    label: { type: String, required: true },
    color: { type: String, validator: ( x ) => isColor( x ), default: '#fff' },
    enable: { type: Boolean }
  }
};
```

> `@storybook/addon-controls` requires `@storybook/addon-docs`, which doesn't make much sense to me.

From my short investigation, it seems that the reason that `@storybook/addon-docs` is required is because automatic prop extraction from components is handled in `@storybook/addon-docs`, as well as a few other bits of code that glue together the UI and props. This code could be added to `@storybook/addon-controls` and each app (e.g.) `@storybook/vue`, then `@storybook/addon-docs` would not be required for the controls.

> `@storybook/addon-docs` has code for each app type directly in it, instead of app-specific (e.g. Vue) code staying in the `@storybook/vue` package.

Right now `@storybook/addon-docs` has code for each app type, for automatically extracting props to the components. Instead, I think each app type e.g. `@storybook/vue` should (somehow, perhaps the `ClientApi` interface they all export) include methods for extracting the props from a component, and then returning them in a format that `@storybook/addon-controls` supports. Then `@storybook/addon-docs` and `@storybook/addon-controls` would have no implicit dependencies on any app type.

Let me know your thoughts, or if I missed any reasons that things are the way they currently are!

@shilman?

**Comment by shilman** [comment]
> Storybook does not automatically generate controls for Vue as well as it does for React

I disagree with this. React requires `react-docgen` or `react-docgen-typescript`. Vue requires `vue-docgen-api`. Once you have these set up, the experiences are on a par with one another.

> Vue requires vue-docgen-loader and docgens created for Vue components - this seems like an unnecessary dependency.

Why is it a bad thing to depend on a library that does the task that you want it to do? As you point out, Vue components expose their metadata, so we could get away with a much simpler library. But we also want to extract descriptions, JSDoc annotations, etc. `vue-docgen-api` handles all of this.

> @storybook/addon-controls requires @storybook/addon-docs, which doesn't make much sense to me.
> @storybook/addon-docs has code for each app type directly in it, instead of app-specific (e.g. Vue) code staying in the @storybook/vue package

I agree with this. We weren't even planning to release `addon-controls` in 6.0, but once we had `ArgsTable` controls working well in docs we saw an easy path to get there. This definitely needs a refactor. Would you like to work on this together in 6.1?

**Comment by abrenneke** [comment]
> Why is it a bad thing to depend on a library that does the task that you want it to do? As you point out, Vue components expose their metadata, so we could get away with a much simpler library. But we also want to extract descriptions, JSDoc annotations, etc. vue-docgen-api handles all of this.

Maybe I misinterpreted the code @shilman - is `vue-docgen-api` only required on the storybook side, and no extra code is required on the story developer's side? Because from my two examples, the React one worked out of the box, and the Vue one did not because there was no docgen information present.

**Comment by shilman** [comment]
The SB docs for vue setup is here:

https://github.com/storybookjs/storybook/tree/next/addons/docs/vue

there shouldn't be any special setup required beyond adding the addon-docs to your list of addons in main.js

**Comment by altryne** [comment]
I want to chime in here, and say that in my case, vue app, controls are desired, but docs are breaking on some other issue. 
Following the documentation, I really struggled to understand why I need argTypes as the documentation clearly states that they will be magically assumed from the args. 
Took me 2 hours of googling to get to this issue that describes this dependency (as the documentation doesn't), and since docs addon is breaking (on something else) I can't enjoy the magical extraction

**Comment by shilman** [comment]
@altryne Installing `@storybook/vue` should also install `vue-docgen-loader`/`vue-docgen-api` as dependencies. Are you saying that you need to install them manually in order to get things working? If so, I'd like to get to the bottom of that.

**Comment by altryne** [comment]
I think I resolved it, by fixing my other issue, and then using essentials which includes docs and control addons. 

What I meant was the vue documentation is not very clear on this dependency which led me to google and to this issue
After you responded I went back to the docs and read them again in depth: 
This section does not explain the dependancy on having docs which is confusing: 

<img width="878" alt="CleanShot 2020-08-14 at 18 56 39@2x" src="https://user-images.githubusercontent.com/463317/90301921-f6143400-de5f-11ea-8c05-480d76b6d2ab.png">

Only going through the whole documentation it says so vaguely in this part: 
![CleanShot 2020-08-14 at 18 57 38@2x](https://user-images.githubusercontent.com/463317/90301939-0e844e80-de60-11ea-8546-dd0b88f02683.png)

But it doesn't explain that I have to have the addon-docs in my addons in main.js
