### ISSUE TITLE
[Angular] Addon Controls "reset functionality" does not reset a component to its Initial State

### ISSUE THREAD

**Issue by akhilesh85** [storybookjs/storybook#11614]
**Describe the bug**
When we use the reset functionality under the controls tab, it does not reset the component to its initial state.

**To Reproduce**
1. Go to controls
2. Update the Input for both text and select controls
3. Click on the reset button under the controls
4. The values reset under controls but the component instance variables do not resets

**Expected behavior**
When we reset the controls it should also reset all the component's instance ie., to its initial state.

**Screenshots**
![Storybook_Addon_Control_Issue_Reset_Not_Working](https://user-images.githubusercontent.com/67741191/87897414-d4e93f00-ca7d-11ea-9ec3-1438fcdba560.gif)

**Code snippets**
[1-Label.stories.ts.txt](https://github.com/storybookjs/storybook/files/4945376/1-Label.stories.ts.txt)
[label.component.ts.txt](https://github.com/storybookjs/storybook/files/4945377/label.component.ts.txt)

**System:**
 System:
    OS: Windows 10 10.0.18362
    CPU: (4) x64 Intel(R) Core(TM) i5 CPU       M 460  @ 2.53GHz 
  Binaries:
    Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    @storybook/addon-actions: ^6.0.0-rc.11 => 6.0.0-rc.11        
    @storybook/addon-controls: ^6.0.0-rc.11 => 6.0.0-rc.11       
    @storybook/addon-docs: ^6.0.0-rc.11 => 6.0.0-rc.11 
    @storybook/addon-links: ^6.0.0-rc.11 => 6.0.0-rc.11
    @storybook/angular: ^6.0.0-rc.11 => 6.0.0-rc.11

**Comment by shilman** [comment]
Do you have a public repro of this error? I'm not seeing it in `examples/angular-cli` in the storybook repo

**Comment by akhilesh85** [comment]
Hi @shilman 

Do you want me to provide more details or are we good? I don't have a hosted storybook repo. Let me know how can I achieve this? Going forward I can publish my Issues there itself. Thanks.

Regards,
Akhilesh

**Comment by shilman** [comment]
I added your component/stories to the storybook repo. It doesn't repro exactly as you describe it (i think), but it does show something weird that we can discuss and either fix in storybook itself or as suggestions for how to write args stories for angular. I think we're good for now!

**Comment by akhilesh85** [comment]
> I added your component/stories to the storybook repo. It doesn't repro exactly as you describe it (i think), but it does show something weird that we can discuss and either fix in storybook itself or as suggestions for how to write args stories for angular. I think we're good for now!

Sure, thanks @shilman 😊👍🏻

**Comment by tmeasday** [comment]
@akhilesh85 

I took a look at this. I'm not an angular expert so apologies in advance for my ignorance. I'm looking at the stories that @shilman added in https://github.com/storybookjs/storybook/commit/0670442f3394305c81bc33199c7744e57e87dcaf which appear to show the same behaviour as you reported.

What I am seeing is that when I reset the controls, the `Template` is rendered  with:

```js
args = {
  text: 'Default Label',
  bgColor: undefined,
}
```

I think this is technically correct, at least from the perspective of args. I am not sure if it is a bug in `@storybook/angular` or our documentation or your component implementation that when `bgColor` is passed in `undefined` the component does not reset itself back to its initial value. What would you expect to happen?

**Comment by shilman** [comment]
Yo-ho-ho!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.0-alpha.2 containing PR #13215 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
