### ISSUE TITLE
[Angular] Addon Control Input borders not showing up correctly under the Docs section

### ISSUE THREAD

**Issue by akhilesh85** [storybookjs/storybook#11616]
**Describe the bug**
The border on the right-hand side of the select control gets cut off. 

**To Reproduce**
1. Create some inputs like text, select.
2. Go to the controls tab under the Canvas tab. The select and input control borders show up correctly.
3. Go to the props section under the Docs tab. The borders or the select control do not show up correctly whereas input borders show up correctly.

**Expected behavior**
The border of the controls should not change irrespective of where they are being shown.

**Screenshots**
![Storybook_Addon_Control_Issue_Borders](https://user-images.githubusercontent.com/67741191/87899138-d406dc00-ca82-11ea-8214-27cf3f162014.gif)

**Code snippets**
[1-Label.stories.ts.txt](https://github.com/storybookjs/storybook/files/4945443/1-Label.stories.ts.txt)
[label.component.ts.txt](https://github.com/storybookjs/storybook/files/4945444/label.component.ts.txt)

**System:**
  System:
    OS: Windows 10 10.0.18362
    CPU: (4) x64 Intel(R) Core(TM) i5 CPU       M 460  @ 2.53GHz 
  Binaries:
    Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    @storybook/addon-actions: ^6.0.0-rc.11 => 6.0.0-rc.11        
    @storybook/addon-controls: ^6.0.0-rc.11 => 6.0.0-rc.11       
    @storybook/addon-docs: ^6.0.0-rc.11 => 6.0.0-rc.11 
    @storybook/addon-links: ^6.0.0-rc.11 => 6.0.0-rc.11
    @storybook/angular: ^6.0.0-rc.11 => 6.0.0-rc.11

**Comment by shilman** [comment]
cc @domynen

**Comment by robbertkl** [comment]
Just ran into this as well. Found out if you remove `box-sizing: inherit` from the `<select>`, it does show up correctly. Hope this helps narrow down the cause.

**Comment by domyen** [comment]
Hey there, thanks for the bug report! 

I can't seem to reproduce this on rc26 in the official-storybook (where we QA and test Storybook itself). It would help me debug if a reproduction was published online somewhere.

Video here: https://www.loom.com/share/3c3fb5b644dc4c698bdcd85293b45a57

**Comment by domyen** [comment]
Closing. I couldn't reproduce this a few weeks ago in the official storybook. Please reopen if a reproduction is found.
