### ISSUE TITLE
Core: Ensure decorators are not run twice

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#11623]
In SB6 we added a bunch of addon presets which automatically register decorators. Although this is documented in [MIGRATION.md](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#new-addon-presets) it will also likely lead to difficult to debug situations. We are also [recommending duplicate decorators to storyshots users](https://github.com/storybookjs/storybook/pull/11518), which will also break things if decorators are run twice (unless the decorators themselves are run twice).

Therefore, we should:
- [ ] Ensure that decorators are not run twice
- [ ] Log a warning if they are

**Comment by ndelangen** [comment]
@tmeasday @shilman I'd like to discuss this first before I start working on a solution..

Also see my comment here:
https://github.com/storybookjs/storybook/pull/11518#issuecomment-661847900

(I understand that "proposal" isn't feasible for 6.0)

**Comment by shilman** [comment]
Boo-yah!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-rc.14 containing PR #11643 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
