### ISSUE TITLE
Can't start storybook: recieve error

### ISSUE THREAD

**Issue by Meugenn** [storybookjs/storybook#11630]
Hi. I'm trying to start storybook, but recieve an error: 
ERROR in  SyntaxError: Invalid regular expression: /%g++%/: Nothing to repeat

### Steps to reproduce
Repeating the guide:
npx create-react-app taskbox
cd taskbox
npx -p @storybook/cli sb init
yarn storybook

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react ^5.3.19
- NodeJS v12.18.2
- Windows 10

### Screenshots / Screencast / Code Snippets (Optional)

ERROR in   SyntaxError: Invalid regular expression: /%g++%/: Nothing to repeat

  - new RegExp

  - template.js:20
    [clicker]/[@storybook]/core/dist/server/utils/template.js:20:101

  - Array.reduce

  - template.js:20 interpolate
    [clicker]/[@storybook]/core/dist/server/utils/template.js:20:65

  - template.js:61 getManagerHeadHtml
    [clicker]/[@storybook]/core/dist/server/utils/template.js:61:10

  - manager-webpack.config.js:106 templateParameters
    [clicker]/[@storybook]/core/dist/server/manager/manager-webpack.config.js:106:59

  - index.js:364
    [clicker]/[core]/[html-webpack-plugin]/index.js:364:19

  - task_queues.js:97 processTicksAndRejections
    internal/process/task_queues.js:97:5

**Comment by shilman** [comment]
I tried the repro steps and it works on my machine. Can you post a link to a public repo that demonstrates this problem?

**Comment by Meugenn** [comment]
That code doesn't work: https://github.com/Meugenn/storybook-issue

**Comment by shilman** [comment]
your repo works for me. did you try removing node_modules & reinstalling?

**Comment by Meugenn** [comment]
Yeah, I've tried to run storybook on several projects and everywhere it doesn't work

**Comment by shilman** [comment]
are they all windows machines?

**Comment by Meugenn** [comment]
Yes, on ubuntu virtual machine everything works fine

**Comment by shilman** [comment]
@jonniebigodes can you help?

**Comment by jonniebigodes** [comment]
@shilman i'll take a look at it. @Meugenn i'm going to clone the repo and take a look at it and see if we can find out what's happening and possibly solve it. Do you mind waiting a bit?

**Comment by Meugenn** [comment]
As you see, I don't mind 😅

**Comment by danilomr12** [comment]
Hi there, I am facing the same with angular 11.2 and storybook 6.2^
