### ISSUE TITLE
Chakra UI: Storybook not running after upgrade

### ISSUE THREAD

**Issue by segunadebayo** [storybookjs/storybook#11636]
**Describe the bug**
I recently upgraded to `6.0.0-rc.13` and I'm getting some errors related to React Docgen Typescript. Is there a way to turn off this step?

**Steps to reproduce**
1. Clone https://github.com/chakra-ui/chakra-ui/tree/develop
2. Edit `main.js` to run all storybook files
3. You'll see the same error as attached below. The packages that seem to be problematic are "slider", and "system". I wonder if I'm doing anything wrong there.

**Expected behavior**
Ideally, I'd love it to just work out of the box. If there are any changes I need to make, I'd love to know

**Screenshots**
![Screenshot 2020-07-22 at 3 16 47 AM](https://user-images.githubusercontent.com/6916170/88116585-ed667000-cbc9-11ea-909d-e25c8f8a7aeb.png)

**Comment by shilman** [comment]
Hey @segunadebayo, big fan of Chakra UI! A few things from looking at the Storybook setup:

1. Upgrade using `npx sb@next upgrade --prerelease`. That way all the storybook packages are on the latest version.
2. Remove `@storybook/preset-typescript`. [Zero-config typescript is built in now](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#zero-config-typescript).

After doing those two steps it's working out of the box on my machine. If you want, you can turn off `react-docgen-typescript` by adding the following line to your `main.js`:

```js
module.exports = {
  stories: ["../packages/**/*.stories.tsx"],
  typescript: {
    reactDocgen: false,
  },
}
```

`react-docgen-typescript` is used to automatically generate prop tables and [controls](https://medium.com/storybookjs/storybook-controls-ce82af93e430) in SB6 if you have `addon-docs` and `addon-controls` enabled. On my machine, turning it off reduced the startup time from 32s to 9s.

Let me know if that works for you!

**Comment by segunadebayo** [comment]
Amazing! Thank you @shilman.

It worked!

I'm forever a big fan of Storybook 💖
