### ISSUE TITLE
ability to blacklist or whitelist a range of controls

### ISSUE THREAD

**Issue by Aaike** [storybookjs/storybook#11638]
**Is your feature request related to a problem? Please describe.**
At the moment the only way to disable a control is to use `controls: { disable: true }` and `table: { disable: true }` for each control.
In my case there are a lot of options i want to hide so i don't want to have to list them all out.

**Describe the solution you'd like**
the ability to blacklist of whitelist a range of controls using an array of strings or regex perhaps ?

**Describe alternatives you've considered**
disabling all of them manually in the `argTypes` object.

**Are you able to assist bring the feature to reality?**
no, please help implement this feature :)

**Comment by valleywood** [comment]
I have the same situation where I'd only like to specify what controls to include rather than having to specify all controls that I want to leave out (which for some components can be > 150)

**Comment by shilman** [comment]
There are a few different workarounds here (cc @jonniebigodes):
1. `ArgsTable` has `include`/`exclude` props if you're using MDX https://github.com/storybookjs/storybook/blob/next/addons/docs/src/blocks/ArgsTable.tsx#L24-L27
2. If you're using Typescript you can modify `reactDocgenTypescriptOptions` globally https://storybook.js.org/docs/react/configure/typescript#mainjs-configuration

@valleywood what's the situation in which you have 150+ controls on a component?

**Comment by valleywood** [comment]
> @valleywood what's the situation in which you have 150+ controls on a component?

Thanks @shilman will have a look at you suggestions!

I'm wrapping a couple of Material UI components currently and some of them takes a long list of css-properties as props.
Just took one out of the list now which is the Box component. From the MUI documentation:

"The Box component packages all the style functions that are exposed in @material-ui/system. It's created using the styled() function of @material-ui/core/styles." - https://material-ui.com/components/box/

<img width="460" alt="Skärmavbild 2020-12-18 kl  15 24 44" src="https://user-images.githubusercontent.com/3974008/102782982-8f1d0380-439a-11eb-8ed6-ff214f889fab.png">

**Comment by shilman** [comment]
Crikey!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.0-alpha.27 containing PR #13898 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
