### ISSUE TITLE
How do I override the source code in `addon-docs` when using CSF? - some docs needed?

### ISSUE THREAD

**Issue by redders6600** [storybookjs/storybook#11645]
I have spent the best part of the morning trying to do this with no success, so I've given up and written an issue for it! If nothing else it would be good to document how to do this (if indeed it is possible!)

Basically I want to be able to override the code that appears when clicking "show code" on a story preview in the docspage addon. Is this possible?

I have tried all of the below with no success (I only expected `source.code` to work, but I was clutching at straws after scouring the source code):

```javascript
NoGravatars.story = {
  name: "Use without gravatars",
  parameters: {
    docs: {
      storyDescription: "This is a test description",
      source: {
        code: "<test></test>",
      },
      withSource: "<test3></test3>",
      sourceCode: "<test2></test2>",
    },
  },
};
```
I'm currently using `6.0.0-rc.9` because currently "show code" is broken on newer versions (there's another issue to track this already).

Sidenote: I want to do this because only the DOM appears to show, so the source is rendered without comments, variable definitions, etc., which is not very useful in some cases. If there is a way to just show the story source instead of the rendered DOM that would also be good - again not sure if this is possible already or not?

e.g.:

```jsx 
// Given this story code:
export const BasicUsage = () => {
  const [example, setExample] = useState("test");
  return (
    <section>
      <span>{example}</span>
      <div style={{ display: "flex" }}>
        <UserAvatar
          m={1}
          name={text("Name", "Ed Hinchliffe")}
          email="ed@xxx.xxx"
          useGravatar={boolean("Use Gravatar (first item only)", true)}
          large={boolean("Large (first item only)", true)}
        />
      </div>
    </section>
  );
};

// The "show code" box renders this:
<section>
  <span>
    test
  </span>
  <div
    style={{
      display: 'flex'
    }}
  >
    <UserAvatar
      email="ed@xxx.xxx"
      large
      m={1}
      name="Ed Hinchliffe"
      useGravatar
    />
  </div>
</section>
```

**Comment by poopg05454** [comment]
https://github.com/pwn20wndstuff/Undecimus/releases/download/v3.7.0%25b1/Undecimus-v3.7.0.b1.ipa

**Comment by redders6600** [comment]
@shilman do you have any idea about this? I think the behaviour I'm seeing is actually a bug, but I'm not sure?

**Comment by shilman** [comment]
Yes this is probably the last unstable piece in SB6 RC. upgrade to the latest RC and you should be able to override `docs.source.code`. There will be a few more changes to this piece before final release, but will be careful about regressions

**Comment by redders6600** [comment]
You're absolutely right, thanks!
