### ISSUE TITLE
@storybook/react: Update react-docgen-typescript-plugin

### ISSUE THREAD

**Issue by marjorg** [storybookjs/storybook#11656]
**Describe the bug**
An issue in https://github.com/styleguidist/react-docgen-typescript/issues/276 cause errors when `commentSource.valueDeclaration` is `undefined`, this has been fixed in version `1.20.1`. 

**react-docgen-typescript-plugin** depends on **react-docgen-typescript** and has released `0.5.2` containing the fixed version. See https://github.com/hipstersmoothie/react-docgen-typescript-plugin/issues/11.

Could you update the version of **react-docgen-typescript-plugin** used by **@storybook/react** to fix this issue?

**Comment by shilman** [comment]
Gadzooks!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-rc.15 containing PR #11658 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

**Comment by marjorg** [comment]
It works :)
