### ISSUE TITLE
Storybook + Angular CSF Stories causes 'Multiple defintions' error in IE11

### ISSUE THREAD

**Issue by endlist** [storybookjs/storybook#11653]
**Describe the bug**
I had been writing simple MDX stories with Angular, but when I started to try to write more complex stories I found it easier to switch to CSF format.  Doing so seems to break IE11, though, so the entire Storybook instance fails to load with the sidebar remaining the grey loader boxes and the main window spinning a loader.  If the console was open on load or opened and refreshed you'll notice an error `Multiple definitions of a property not allowed in strict mode`

**To Reproduce**
Going to either the current or next Angular examples using IE11 (https://next--storybookjs.netlify.app/angular-cli or https://storybookjs.netlify.app/angular-cli/) has the same behavior.

**Expected behavior**
No error, the page loads successfully.

**Screenshots**
![image](https://user-images.githubusercontent.com/453902/88235990-3f92aa00-cc39-11ea-9f22-1bd92b220c63.png)
![image](https://user-images.githubusercontent.com/453902/88235931-1c67fa80-cc39-11ea-865e-bb7a30678581.png)

**Code snippets**
An example of how I'm setting up the component in case that's the issue:

```js
// example.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'lib-example',
  styleUrls: ['./example.component.scss'],
  template: `<div>I do something</div>`
})
export class LibExampleComponent {
  constructor() {}
}

// example.component.stories.ts
import { ExampleComponent } from './example.component';
import { moduleMetadata } from '@storybook/angular';

export default {
  title: 'Components/Example',
  component: ExampleComponent,
  decorators: [
    moduleMetadata({
      declarations: [ExampleComponent]
    })
  ]
}

export const testStory = () => {
  return {
    template: `<lib-example></lib-example>`
  }
}
```

**System:**
Please paste the results of `npx -p @storybook/cli@next sb info` here.

The above command keeps failing with a `DeprecationWarning` about unhandled promise rejections for some reason, but I'm running `@storybook/angular` at `5.3.19`, MacOS Mojave, Node 10.16.2, npm v6.14.6, and as noted above this seems to be happening on version 6 also if the live Angular examples are up to date.

**Comment by shilman** [comment]
Try upgrading to 6.0 RC?

```
npx sb@next upgrade --prerelease
```

**Comment by ndelangen** [comment]
Storybook 7.0 won't support IE11 anymore.

6.5 won't receive updates other than critical security issues, this won't get fixed.
