### ISSUE TITLE
Addon-docs: Vue binding/property support in Props table

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#11655]
Hi @shilman, I would like to know any news about props table for **Vue**, I'm currently testing on `6.0.0-rc.14` and the props table is really fine, but I'm wondering if there is support for `@binding` in `@slot` and `@property` in `@event`.

https://github.com/vue-styleguidist/vue-styleguidist/tree/dev/packages/vue-docgen-api#events

https://github.com/vue-styleguidist/vue-styleguidist/tree/dev/packages/vue-docgen-api#slots

_Originally posted by @ecarrera in https://github.com/storybookjs/storybook/pull/9838#issuecomment-662661736_

**Comment by shilman** [comment]
Any interest in adding this? Contributions welcome!

**Comment by fallemand** [comment]
It would be great to support `@values`: https://vue-styleguidist.github.io/docs/Documenting.html#available-tags
In `Vue` `ArgsTable` it's not possible to show a list with the possible values in the type. 😢
