### ISSUE TITLE
[Angular] The addon docs content zooms when the canvas is zoomed

### ISSUE THREAD

**Issue by akhilesh85** [storybookjs/storybook#11662]
**Describe the bug**
When we use the Zoom In and out buttons under the canvas tab. This has a repercussion effect on the docs tab. For instance, if we zoom in the canvas tab and then navigate to the docs tab the content is zoomed in.

**To Reproduce**
1. Go to the Canvas tab, click on zoom in until the content in the preview maximizes
2. Navigate to the docs tab, you will see all the contents are zoomed in

**Expected behavior**
Zooming in the Canvas tab should not zoom in for the docs tab as they are two independent modules.

**Screenshots**
![Storybook_Addon_Docs_Zoom_Issue](https://user-images.githubusercontent.com/67741191/88257634-c3f43400-ccf0-11ea-98f4-e9869bb805bf.gif)

**Code snippets**
It is not associated to a specific storybook format or component. This is at the storybook framework level.

**System:**

  System: (Behaviour is same for the mac OS as well)
    OS: Windows 10 10.0.18362
    CPU: (4) x64 Intel(R) Core(TM) i5 CPU       M 460  @ 2.53GHz
  Binaries:
    Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 84.0.4147.89
    Edge: Spartan (44.18362.449.0)
  npmPackages:
    @storybook/addon-actions: ^6.0.0-rc.14 => 6.0.0-rc.14
    @storybook/addon-controls: ^6.0.0-rc.14 => 6.0.0-rc.14
    @storybook/addon-docs: ^6.0.0-rc.14 => 6.0.0-rc.14
    @storybook/addon-links: ^6.0.0-rc.14 => 6.0.0-rc.14
    @storybook/addon-storysource: ^6.0.0-rc.14 => 6.0.0-rc.14
    @storybook/angular: ^6.0.0-rc.14 => 6.0.0-rc.14

**Comment by shilman** [comment]
w00t!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-rc.27 containing PR #11795 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
