### ISSUE TITLE
Issue with Info addon while using with intl

### ISSUE THREAD

**Issue by qburst-riju** [storybookjs/storybook#11661]
**Bug**
Since I'm using intl along with info addon, the output I'm getting is 
<img width="1196" alt="Screenshot 2020-07-22 at 3 08 11 PM" src="https://user-images.githubusercontent.com/8123580/88257399-39550a00-ccdb-11ea-93b0-d62e05264098.png">
Expected output is 
<img width="943" alt="Screenshot 2020-07-23 at 11 54 51 AM" src="https://user-images.githubusercontent.com/8123580/88257442-55f14200-ccdb-11ea-840b-93af5712bf33.png">
Is there a way to unwrap hoc of intl.

This is code
stories.tsx
`export const CaptionExample = injectIntl(({ intl: { messages } }: any) => {
  return (
    <Caption element={'p'} variant={variant} color={color}>
      {messages.text_order_cancel}
    </Caption>
  );
});
storiesOf('Components|Caption', module)
  .addDecorator(withKnobs)
  .addParameters({
    info: {
      header: false,
      inline: true,
      propTables: false,
    }
  })
  .add('CaptionExample', () => <CaptionExample />);
`

**Comment by shilman** [comment]
`Addon-info` has been superceded by `addon-docs`, which fixes a bunch of bugs and is easier to maintain. Please give it a try! https://medium.com/storybookjs/storybook-docspage-e185bc3622bf

**Comment by qburst-riju** [comment]
Thanks for your prompt response. I would like to check whether `addon-docs` will be able to manage the scenario I'm trying. Since I'm using Intl as a HOC the output is `<InjectIntl(Component) />`, can we get rid of this wrapping in `addon-docs`.

**Comment by qburst-riju** [comment]
I want to show users the dynamic props with knobs we are using in Storybook. This is currently working with `addon-info`, the only issue is with when it is using along with Intl.
![ezgif com-crop](https://user-images.githubusercontent.com/8123580/88365714-8fda4b00-cda4-11ea-9f62-013eb6effe0c.gif)
👆 this is my expectation.

**Comment by shilman** [comment]
HOC's are tricky so I'm not sure if it works in addon-docs, but if it doesn't work we can make it work since addon-docs is being actively maintained and improved
