### ISSUE TITLE
addon-storysource Error: Cannot read property 'kind' of undefined

### ISSUE THREAD

**Issue by kylesuss** [storybookjs/storybook#11672]
**Describe the bug**
The settings pages are broken on `next` when navigating from the dropdown menu. The stacktrack points to `addon-storysource` as the culprit. Can be recreated with `examples/official-storybook`:

https://www.loom.com/share/c86c2d2de1bf4800b17ff17e4ee6db1b

**To Reproduce**
1. Go to the official Storybook dir: `cd examples/official-storybook`
2. Start Storybook: `yarn storybook`
3. Open the dropdown menu in the sidebar, click "Keyboard shortcuts"

**Expected behavior**

**Screenshots**
![Screen Shot 2020-07-23 at 10 50 09 AM](https://user-images.githubusercontent.com/3035355/88314546-50432e80-ccd2-11ea-81ee-f8583daed070.png)

**Code snippets**
The stack trace seems to point here:
https://github.com/storybookjs/storybook/blob/3bc466689bae8d41bbaa75be1975eea32db33ecb/addons/storysource/src/StoryPanel.tsx#L123-L131

**System:**
Please paste the results of `npx -p @storybook/cli@next sb info` here.

```
Environment Info:

  System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 12.18.2 - ~/.nvm/versions/node/v12.18.2/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v12.18.2/bin/npm
  Browsers:
    Chrome: 84.0.4147.89
    Firefox: 77.0.1
    Safari: 13.1
```

**Additional context**

**Comment by kylesuss** [comment]
cc @shilman as this is likely a 6.0 blocker.

**Comment by shilman** [comment]
Great Caesar's ghost!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-rc.15 containing PR #11679 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
