### ISSUE TITLE
[Angular] [Docs] JSDoc markdown not rendered properly

### ISSUE THREAD

**Issue by cjwang18** [storybookjs/storybook#11674]
**Describe the bug**
Bulleted and numbered lists written in an Angular component's JSDoc do not render properly in the Docs page output.

**To Reproduce**
1. Use example as source: https://github.com/storybookjs/storybook/tree/next/examples/angular-cli
2. Modify `doc-button.component.ts` to include bulleted and numbered lists within the component-level JSDoc
3. Start `storybook`
4. Navigate to the Docs page for the Addon -> Controls -> Basic story and observe the output

**Expected behavior**
Bulleted and ordered lists should render properly when specified in the JSDoc

**Screenshots**
_How the JSDoc was modified_
![image](https://user-images.githubusercontent.com/7762383/88321978-df514600-ccd4-11ea-9c12-01b92f735a73.png)

_Actual output_
![image](https://user-images.githubusercontent.com/7762383/88322046-f55f0680-ccd4-11ea-819f-c64f2de01df6.png)

**System:**
```
Environment Info:

  System:
    OS: macOS 10.15.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    npm: 6.13.7 - /usr/local/bin/npm
  Browsers:
    Chrome: 84.0.4147.89
    Safari: 13.1.1
  npmPackages:
    @storybook/addon-a11y: 6.0.0-rc.14 => 6.0.0-rc.14
    @storybook/addon-actions: 6.0.0-rc.14 => 6.0.0-rc.14
    @storybook/addon-backgrounds: 6.0.0-rc.14 => 6.0.0-rc.14
    @storybook/addon-controls: 6.0.0-rc.14 => 6.0.0-rc.14
    @storybook/addon-docs: 6.0.0-rc.14 => 6.0.0-rc.14
    @storybook/addon-jest: 6.0.0-rc.14 => 6.0.0-rc.14
    @storybook/addon-knobs: 6.0.0-rc.14 => 6.0.0-rc.14
    @storybook/addon-links: 6.0.0-rc.14 => 6.0.0-rc.14
    @storybook/addon-storyshots: 6.0.0-rc.14 => 6.0.0-rc.14
    @storybook/addon-storysource: 6.0.0-rc.14 => 6.0.0-rc.14
    @storybook/addons: 6.0.0-rc.14 => 6.0.0-rc.14
    @storybook/angular: 6.0.0-rc.14 => 6.0.0-rc.14
    @storybook/source-loader: 6.0.0-rc.14 => 6.0.0-rc.14
```

**Additional context**
* This was occurring with Storybook v5.3.19 as well.
* Tried varying number of spaces between the JSDoc star and the bullet point but to no avail.

**Comment by ecnaidar** [comment]
Still present when using `@storybook/react@6.0.16`

**Comment by drik98** [comment]
Thanks @mcosand-caltopo that seems to work.

```js
{
   props: {
      /**
       * An object containing foo
       *
       * It consists of:
       *
       * - key1: bar
       * - key2: baz
       */
      property1: Object
   }
}
```

whereas 

```js
{
   props: {
      /**
       * An object containing foo
       *
       * It consists of:
       * - key1: bar
       * - key2: baz
       */
      property1: Object
   }
}
``` 

does not render the markdown list correctly.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
