### ISSUE TITLE
addon-docs, unconsistent "showCode" behaviour (6.0.0-rc.14)

### ISSUE THREAD

**Issue by benjamin-schneider** [storybookjs/storybook#11678]
**Describe the bug**
Given 2 story functions implementing the same component, the rendered source code is not the same depending on the story function parameters (6.0.0-rc.14, typescript and react)

**To Reproduce**
This is reproductible in an easy manner. In a *.stories.tsx, add these 2 functions :
```
export const SampleWithoutParams = () => {
  return (<div>a</div>);
};

export const SampleWithParams = (args: Args, ctx: StoryContext) => {
  return (<div>a</div>);
};
```

Then in the docs tab, click on "showCode" :
![Capture d’écran de 2020-07-24 09-37-27](https://user-images.githubusercontent.com/3585213/88369909-551ae780-cd91-11ea-9ff5-19ba6362d510.png)

**Expected behavior**
IMHO, the source code should be the same. I mean the first one eg :
```
() => {
  return (<div>a</div>);
}
```

Seems that when there are params, source code is "interpreted". 

**System:**
```
Environment Info:

  System:
    OS: Linux 5.4 Ubuntu 20.04 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
  Binaries:
    Node: 13.3.0 - ~/.nvm/versions/node/v13.3.0/bin/node
    npm: 6.13.1 - ~/.nvm/versions/node/v13.3.0/bin/npm
  Browsers:
    Chrome: 84.0.4147.89
    Firefox: 78.0.2
  npmPackages:
    @storybook/addon-actions: ^6.0.0-rc.14 => 6.0.0-rc.14 
    @storybook/addon-docs: ^6.0.0-rc.14 => 6.0.0-rc.14 
    @storybook/addon-jest: ^6.0.0-rc.14 => 6.0.0-rc.14 
    @storybook/addon-links: ^6.0.0-rc.14 => 6.0.0-rc.14 
    @storybook/addon-storysource: ^6.0.0-rc.14 => 6.0.0-rc.14 
    @storybook/addons: ^6.0.0-rc.14 => 6.0.0-rc.14 
    @storybook/preset-create-react-app: ^3.1.4 => 3.1.4 
    @storybook/react: ^6.0.0-rc.14 => 6.0.0-rc.14
```

**Additional context**
Sorry if this is not a bug, I tried to search but did not found an issue about that.

**Comment by redders6600** [comment]
Ah - I think all of my stories must have params, as mine always look like your second option, hence opening this issue: #11645...

Definitely would prefer if the actual source was used instead of just displaying the resulting DOM.

**Comment by shilman** [comment]
This is still WIP and I'll document it properly including the rationale once things are finalized. In a nutshell, there is a new parameter `docs.source.type` which can take on the values `'auto' | 'code' | 'dynamic'`. Default is 'auto' which chooses 'dynamic' for args stories and 'code' for classic stories. You can force this to be 'code' globally to get the behavior you want.

**Comment by benjamin-schneider** [comment]
@shilman This will be a killer feature. Thanks for your precise and concise explanation

**Comment by shilman** [comment]
Yowza!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-rc.16 containing PR #11710 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by yyynnn** [comment]
@shilman 
<Preview /> outputs nonsense of a controlled story.
With this syntax:

```js
<Preview>
  <Story name="Radio types">{Template.bind({})}</Story>
</Preview>
```


<img width="706" alt="Снимок экрана 2020-07-28 в 23 31 13" src="https://user-images.githubusercontent.com/13677727/88718673-cd373380-d12a-11ea-81b7-826e1785e5b3.png">

**Comment by benjamin-schneider** [comment]
@shilman Thanks a lot for the resolution, it works very well (CSF)
With the sample you gave 
> See the updated snapshots & the ForceCodeSource story in official-storybook for e2e

I just had to add `docs: { source: { type: 'code' } }` in the story parameters, and everything is fine.

To illustrate, here is a before/after if somebody else encounters this problem :

**Before :** ![Capture d’écran de 2020-07-29 14-03-03](https://user-images.githubusercontent.com/3585213/88797942-67878d80-d1a4-11ea-807b-937efd12c748.png)

**After (with docs: { source: { type: 'code' } }` in the story parameters) :** ![Capture d’écran de 2020-07-29 14-02-35](https://user-images.githubusercontent.com/3585213/88797928-622a4300-d1a4-11ea-8939-fec66fab6204.png)

**Comment by shilman** [comment]
Thanks for documenting @benjamin-schneider!! 🙏
