### ISSUE TITLE
bug: addon-actions: Unable to view the actions panel in Firefox (Desktop View)

### ISSUE THREAD

**Issue by mrsauravsahu** [storybookjs/storybook#11670]
**Describe the bug**
Opening storybook for any project in Firefox, the actions addon panel is not visible (I'm using Firefox: 78.0.2 64-bit)
The addons panel is visible in Edge, Chrome though, and also when the browser is squished to mobile view (the panel becomes visible in mobile view in Firefox).
However, the panel is visible when the same storybook is statically deployed.  

**To Reproduce**
1. Open a storybook project (example: https://propfull.github.io/kit/) - the actions panel is visible.
2. Run the same project locally (https://github.com/propfull/kit/)
3. Make sure addons is on in the settings by pressing `A`
4. Goto the canvas for a button story
5. The actions panel is not available in desktop view

**Expected behavior**
The actions panel should be visible in all views.

**Screenshots**
![image](https://user-images.githubusercontent.com/9134050/88289027-3cb7b800-cd12-11ea-9849-dddeb4ff7095.png)

**System:**
Please paste the results of `npx -p @storybook/cli@next sb info` here.
```
Environment Info:

  System:
    OS: macOS 10.15.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Binaries:
    Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v12.16.3/bin/npm
  Browsers:
    Chrome: 84.0.4147.89
    Edge: 83.0.478.61
    Firefox: 78.0.2
    Safari: 13.1.2
  npmPackages:
    @storybook/addon-actions: ^5.3.19 => 5.3.19 
    @storybook/addon-docs: ^5.3.19 => 5.3.19 
    @storybook/cli: ^5.3.19 => 5.3.19 
    @storybook/svelte: ^5.3.19 => 5.3.19 
```

**Additional context**

**Comment by shilman** [comment]
There's some state where the addons panel disappears. Try hitting "d" on the keyboard to toggle the addons panel orientation to get it back. If that doesn't work, `localStorage.clear()` in the browser console and hard refresh.

**Comment by mrsauravsahu** [comment]
Toggling the orientation worked (`D`). Nevertheless, I can try and look at why this was an issue in the first place. Thanks 😁

**Comment by michaelaflores** [comment]
This is still an issue in 6.1.x.
