### ISSUE TITLE
Refactor handling of `viewMode/storyId`

### ISSUE THREAD

**Issue by tmeasday** [storybookjs/storybook#11675]
Currently our handling of `viewMode` & `storyId` in the manager is a bit confused and has several issues.

The root of the problem is that we map the URL segments from the `path` query parameter to `viewMode` and `storyId` but it doesn't always make sense to do so. In particular when you are at a settings page (e.g. `path=/settings/release-notes` => `viewMode = 'settings'` and `storyId = 'release-notes'`) there are two main issues:

1. `storyId == 'release-notes'` is sort of a nonsense and we have to special case our code all over the place to deal with it.
2. In particular the preview iframe *does not* deal with such view modes and so we have to be careful to not pass the variables through to the preview when they are "invalid".

This means that the preview "remembers" the last "valid"[1] `viewMode`/`storyId` but the manager itself does not[2]. In https://github.com/storybookjs/storybook/pull/11576, @ndelangen actually added a memory mechanism in the manager but it is adhoc and doesn't map to what the preview is doing.

A better idea is to properly account for it. I have two suggestions:

1. Call the path segments `path` and `subpath` or something similar, and reserve `storyId` and `viewMode` for the "last rendered story" == what the preview is rendering *at all times*. OR

2. Don't actually store the setting URLs in `path`, instead use a separate URL parameter and treat the setting properly as an overlay (which is kind of the UX intention I think). So the URL would look something like `/?path=/story/xyz&settings=release-notes`

What do people think?

[1] ie. for an actual rendered story
[2] And there are bugs anyway, for instance if you start on a settings page the preview is not initialised properly.

**Comment by ndelangen** [comment]
I prefer:
> Call the path segments path and subpath or something similar, and reserve storyId and viewMode for the "last rendered story" == what the preview is rendering at all times.

**Comment by ndelangen** [comment]
Probably 8.0 material?

**Comment by tmeasday** [comment]
Also the fact that we don't alternate between view modes for the same `storyId` any more (with docs 2) means the whole concept probably deserves a rethink. @ndelangen should we just close this issue? Is it helping having it?

**Comment by ndelangen** [comment]
nope, happy to close!
