### ISSUE TITLE
[addon-docs]: Make PropsTable values, cleaner and more readable

### ISSUE THREAD

**Issue by ajkl2533** [storybookjs/storybook#11681]
**Is your feature request related to a problem?**
I have some components with props obtaining CSS prop values, like prop `justifyContent` which can have any valid CSS value ( "end" | "inherit" | "initial" | "start" | "left" |...) and there can potentially dozens of those values and that makes prop table messy. Is there any way how to override the format of the output?

**Describe the solution you'd like**
I'd like if there is some number of possible values, they will be rendered in one or two rows with an ellipsis at the end and button `Show more` and after expanding those values will be rendered in rows (one value on one row).

**Describe alternatives you've considered**
Maybe at least remove the pipes and somehow differentiate (e.g. grey background) each possible value would result in more readable props table.

**Are you able to assist bring the feature to reality?**
I probably can

**Additional context**
## How it looks now
<img width="745" alt="Screenshot 2020-07-24 at 16 14 52" src="https://user-images.githubusercontent.com/18654425/88401582-37b63f80-cdca-11ea-9aa7-8c0344f1086f.png">

## How it can look like
![after-collapsed](https://user-images.githubusercontent.com/18654425/88402745-d4c5a800-cdcb-11ea-86b7-297f6e0db1d0.jpg)
![after-expanded](https://user-images.githubusercontent.com/18654425/88402753-d7280200-cdcb-11ea-9c05-2db5922c3644.jpg)

**Comment by shilman** [comment]
Love this. @domyen thoughts?

**Comment by domyen** [comment]
I like it! Awesome suggestion @ajkl2533. Will support you if you can implement.  

**Some design feedback**
- Remove the quotes and the commas (I don't think these are necessary in this design) 
- We still have to wrap the values to the next line because the table can be resized horizontally.

**Comment by ajkl2533** [comment]
@shilman @domyen Thank you guys, I'll try to prepare PR for this.

@domyen Thoughts about your thoughts:
- personally I would leave quotes there since there can be a situation where you have values in enum defined and also have some fallback value and if you remove the quotes then you have no way how to differentiate, see below
<img width="686" alt="Screenshot 2020-07-27 at 13 40 48" src="https://user-images.githubusercontent.com/18654425/88538023-efd42a00-d00e-11ea-8f8b-251e85b2882e.png">

- not sure what you mean by the second point, you mean that the values should on lines all the time? Not only for the expanded state?

**Comment by domyen** [comment]
Got it, leave the quotes in :)

I meant that the implementation should truncate the list after a certain number of items. It shouldn't expect that the # of items will always fit in one row because the layout should be responsive and reflow depending on the column width.

**Comment by ajkl2533** [comment]
@domyen Got it 👍

**Comment by shilman** [comment]
Ooh-la-la!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-rc.27 containing PR #11768 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.
