### ISSUE TITLE
Undefined title in old style stories files, _no_ mdx

### ISSUE THREAD

**Issue by RobIsHere** [storybookjs/storybook#11688]
**Describe the bug**
After upgrading Storybooks, it failed complaining about a missing title in some file.

**To Reproduce**
Write storiesOf story, add some default exported item. Works in old, but not new storybook

**Expected behavior**
Some hint in docs or some error message 
Improve error message

**Code snippets**
https://github.com/storybookjs/storybook/blob/670abd4191c8c0d2e072425ef3070967ae50ae68/lib/core/src/client/preview/loadCsf.ts#L88

**Problem description**
Storybook checks if a file has new or old way of defining stories by checking if there is a default export.
If there is a default export, it assumes a new file.
But my file has been an old file which just happened to have an export. I don't even have new stories files.

The solution:
Find a proper way to decide which file format it is. Just checking export is way too generic.

Minimal solution:
Add to migration docs: "Check your storiesOf .stories.js files for default exports and remove them or you will be stuck with a cryptic error message for hours" ;)

**Comment by jonniebigodes** [comment]
Closing this as we have documentation on the topic in the form of the migration docs currently configured under the [configure](https://storybook.js.org/docs/react/configure/upgrading) section.
