### ISSUE TITLE
Post upgradation from 6.0.0-rc.2 to 6.0.0-rc.14, storybook failing with invalid hooks usage errors.

### ISSUE THREAD

**Issue by ashr81** [storybookjs/storybook#11691]
**Describe the bug**

I have upgraded my storybook packages from 6.0.0-rc.2 to 6.0.0-rc.14. Attaching screenshot of packages I am using and degradation step:
<img width="481" alt="Screenshot 2020-07-26 at 1 24 53 PM" src="https://user-images.githubusercontent.com/5508780/88474441-1711f500-cf44-11ea-87ed-a12755be3e19.png">

**To Reproduce**
1. Go to Install the version 6.0.0-rc.2 and theme upgrade it to 6.0.0-rc.14
4. See error. You will see the below error:

**Expected behavior**
It should work as previously with 6.0.0-rc.2. Nothing changed between both versions.

**Screenshots**
![Screenshot 2020-07-26 at 1 26 50 PM](https://user-images.githubusercontent.com/5508780/88474458-34df5a00-cf44-11ea-9eaf-33066538c56a.png)

**Code snippets**
If applicable, add code samples to help explain your problem.

**System:**
Environment Info:

  System:
    OS: macOS 10.15.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 10.21.0 - ~/.nvm/versions/node/v10.21.0/bin/node
    Yarn: 1.17.3 - ~/.yvm/shim/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v10.21.0/bin/npm
  Browsers:
    Chrome: 84.0.4147.89
    Safari: 13.1.2
  npmPackages:
    @storybook/addon-a11y: 6.0.0-rc.14 => 6.0.0-rc.14 
    @storybook/addon-actions: 6.0.0-rc.14 => 6.0.0-rc.14 
    @storybook/addon-docs: 6.0.0-rc.14 => 6.0.0-rc.14 
    @storybook/addon-knobs: 6.0.0-rc.14 => 6.0.0-rc.14 
    @storybook/addon-storyshots: 6.0.0-rc.14 => 6.0.0-rc.14 
    @storybook/addon-viewport: 6.0.0-rc.14 => 6.0.0-rc.14 
    @storybook/addons: 6.0.0-rc.14 => 6.0.0-rc.14 
    @storybook/core: 6.0.0-rc.14 => 6.0.0-rc.14 
    @storybook/react: 6.0.0-rc.14 => 6.0.0-rc.14 
    @storybook/theming: 6.0.0-rc.14 => 6.0.0-rc.14 

**Additional context**

**Comment by shilman** [comment]
Did you try removing node_modules and/or lockfiles and reinstalling?

**Comment by ashr81** [comment]
Removed node_modules doesn't work. But removing `yarn.lock` file worked. But, that not an option for me. I am working on `yarn workspace` by removing `yarn.lock` all the dependencies in other package gets upgraded. We have storybook versions on different packages: `^3.4.8`, `^3.4.3`, and `6.0.0-rc.2`. It worked perfectly until `6.0.0-rc.2`. but upgrading to `6.0.0-rc.14` broke it.

**Comment by ashr81** [comment]
@shilman , i have made an incremental upgrading from  `6.0.0-rc.2` to `6.0.0-rc.14` and found my storybook has this issue from `6.0.0-rc.12`

**Comment by shilman** [comment]
It sounds like a yarn issue to me. Closing.

**Comment by ashr81** [comment]
Hey @shilman , these line of code has broken my storybook [here](https://github.com/storybookjs/storybook/commit/f6227ece1ebae6440ba5bd12b4d2bfd914612ff1#diff-dfce92fa92b455828b05711d0078d4fdR26).

**Comment by shilman** [comment]
@ndelangen any thoughts on this one? ☝️

**Comment by ndelangen** [comment]
Uhm... that's unexpected. I'm not able to reproduce this in the monorepo.. do you have a reproduction repo you can demonstrate this on?

**Comment by ashr81** [comment]
I am using `styled-components` `ThemeProvider` to pass our custom theme. I will try to reproduce this issue in an example project for the reference.

**Comment by ndelangen** [comment]
thanks!

**Comment by ashr81** [comment]
In the latest upgrade to `6.0.0-rc.28`. This issue is fixed. Thanks for your support
