### ISSUE TITLE
Props table does not show border on Safari

### ISSUE THREAD

**Issue by robbertkl** [storybookjs/storybook#11698]
For example, go to [the Avatar component on the Storybook Design System](https://5ccbc373887ca40020446347-synmdrrwjj.chromatic.com/?path=/docs/design-system-avatar--basic) using Safari. The props table should show a nice shadow border with rounded corners, but it's missing in Safari.

The underlying reason is that it's a `box-shadow` and `border-radius` on the `<tbody>` element. It seems Safari does not support this. Giving the tbody a `display: block` does make the shadow appear, but breaks the layout.

## Safari screenshot

<img width="570" alt="Screen Shot 2020-07-27 at 15 22 40" src="https://user-images.githubusercontent.com/5704510/88546708-100ae580-d01d-11ea-8e03-5edd812913e1.png">

## Chrome screenshot

<img width="588" alt="Screen Shot 2020-07-27 at 15 22 33" src="https://user-images.githubusercontent.com/5704510/88546716-139e6c80-d01d-11ea-9b9b-3862c05a35e3.png">

**Comment by shilman** [comment]
@domyen can you take a look?

**Comment by domyen** [comment]
Got it! We'll need to provide separate styles for Safari (that aren't as handsome) due to limitations with table styling in Webkit.

**Comment by shilman** [comment]
Boo-yah!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-rc.27 containing PR #11805 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
