### ISSUE TITLE
Crash in Edge 18

### ISSUE THREAD

**Issue by atl-mk** [storybookjs/storybook#11705]
**Describe the bug**
Storybook crashes in Edge 18 on load (blank page)

**To Reproduce**
1. Go to [https://storybookjs.netlify.app/official-storybook/?path=/story/*](https://storybookjs.netlify.app/official-storybook/?path=/story/*) in Edge 18
2. See the error in the console

**Expected behavior**
For Storybook to work on Edge 18

**Screenshots**
![image](https://user-images.githubusercontent.com/47995834/88622929-21202900-d0e7-11ea-8e16-924d558aad96.png)
![image](https://user-images.githubusercontent.com/47995834/88622975-3c8b3400-d0e7-11ea-8989-bdf9f197b1c9.png)

**Comment by tooppaaa** [comment]
official-storybook is still runnning 5.x version.

Lots of efforts has been made to resolve IE 11 compatibility.

You can look at https://next--storybookjs.netlify.app/official-storybook/.

**Comment by atl-mk** [comment]
I assume and thus supporting Edge 18 by proxy? if so all good, feel free to close

**Comment by Shackless** [comment]
Same issue here. Is Edge 18 not supported by Storybook 6?
