### ISSUE TITLE
Perf: useDataset slow in 6.0

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#11719]
There's a performance regression in 6.0 related to `useDataset`. The following flame chart is from Chromatic's storybook on 6.0-rc.16:

<img width="940" alt="Emails___BuildNotification_-_with_changes_⋅_Storybook" src="https://user-images.githubusercontent.com/488689/88783466-644eca80-d1c1-11ea-8dd6-2234a0e9e3eb.png">

In contrast, the entire `handleEvent` took 560ms in 5.3.

<img width="576" alt="Emails___BuildNotification_-_with_changes_⋅_Storybook" src="https://user-images.githubusercontent.com/488689/88783630-9b24e080-d1c1-11ea-83b9-b50151bfec10.png">

This is not an apples-to-apples comparison, but `useDataset` definitely looks like a hot spot. Fixing this will complement other perf work such as #10844

**Comment by ndelangen** [comment]
I'll dive in!

**Comment by ndelangen** [comment]
I'm finding:
<img width="909" alt="Screenshot 2020-07-29 at 11 59 52" src="https://user-images.githubusercontent.com/3070389/88786650-0efbc480-d193-11ea-8948-61016b5e6811.png">

**Comment by ndelangen** [comment]
PR incoming

before:
<img width="215" alt="Screenshot 2020-07-29 at 16 25 24" src="https://user-images.githubusercontent.com/3070389/88826912-96642a80-d1c9-11ea-92c4-8d5c8d4f72ce.png">

after:
<img width="359" alt="Screenshot 2020-07-29 at 18 29 29" src="https://user-images.githubusercontent.com/3070389/88826917-97955780-d1c9-11ea-9ea9-639cc365f52e.png">

**Comment by shilman** [comment]
w00t!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-rc.18 containing PR #11725 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
