### ISSUE TITLE
Static Typing in MDX stories

### ISSUE THREAD

**Issue by pladaria** [storybookjs/storybook#11712]
Our components library is written in Typescript.

Writing stories using MDX is nice but we lose static typing checks so stories can easily get outdated without notifying. I was unable to find a solution for this so for now we keep using CSF.

Is there any tooling/configuration to typecheck MDX files?

**Comment by shilman** [comment]
Not AFAIK. I know MDX v2 is coming out soon and might have some Typescript-related features, but I'm unclear on the extent of that work. You're better off asking there: https://github.com/mdx-js/mdx/issues/1041
