### ISSUE TITLE
 Failed to load preset: "@storybook/addon-info" on level 1 

### ISSUE THREAD

**Issue by fandepeng1993** [storybookjs/storybook#11720]
Failed to load preset: "@storybook/addon-info" on level 1
ERR! /Users/fdp/Desktop/fandepeng/NPM/@frid/fdp-ui/node_modules/@storybook/addon-info/dist/components/PropTable/style.css:1
ERR! .info-table {
ERR! ^
ERR! 
ERR! SyntaxError: Unexpected token '.'
ERR!     at wrapSafe (internal/modules/cjs/loader.js:1071:16)
ERR!     at Module._compile (internal/modules/cjs/loader.js:1121:27)
ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1177:10)
ERR!     at Module.load (internal/modules/cjs/loader.js:1001:32)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:900:14)
ERR!     at Module.require (internal/modules/cjs/loader.js:1043:19)
ERR!     at require (internal/modules/cjs/helpers.js:77:18)
ERR!     at Object.<anonymous> (/Users/fdp/Desktop/fandepeng/NPM/@frid/fdp-ui/node_modules/@storybook/addon-info/dist/components/PropTable/components/Table.js:12:1)
ERR!     at Module._compile (internal/modules/cjs/loader.js:1157:30)
ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1177:10)
ERR!     at Module.load (internal/modules/cjs/loader.js:1001:32)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:900:14)
ERR!     at Module.require (internal/modules/cjs/loader.js:1043:19)
ERR!     at require (internal/modules/cjs/helpers.js:77:18)
ERR!     at Object.<anonymous> (/Users/fdp/Desktop/fandepeng/NPM/@frid/fdp-ui/node_modules/@storybook/addon-info/dist/components/PropTable/index.js:37:37)
ERR!     at Module._compile (internal/modules/cjs/loader.js:1157:30)

**Comment by joneldiablo** [comment]
I have the same error!!!!

**Comment by shilman** [comment]
`addon-info` is deprecated and has been superceded by `addon-docs`, which fixes a bunch of bugs and is easier to maintain. Please give it a try! https://medium.com/storybookjs/storybook-docspage-e185bc3622bf

https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-addon-info-addon-notes
