### ISSUE TITLE
Not possible to display controls if using a custom `page` function?

### ISSUE THREAD

**Issue by redders6600** [storybookjs/storybook#11722]
**Describe the bug**
It's either not possible or not documented as to how we can display controls in `addon-docs`'s `<Props/>` block if using a custom `docs.page` parameter.

**To Reproduce**
1. Define a custom page function for addon docs in `preivew.js` e.g.:

   ```javascript
    addParameters({
      docs: {
        source: {
          type: "code",
        } ,
        page: () => {
          return (
            <>
              <Title />
              <Subtitle />
              <Primary />
              <Description />
              <Props />
              <Stories includePrimary />
            </>
          );
        },
      },
    });
    ```

2. Create an args story
3. Confirm you can see controls tab in `canvas` view
4. Check props table in `docs` page -> No prop types.

**Expected behavior**
The [docs for `addon-docs`](https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/props-tables.md#controls) suggest that if using a CSF, props table automatically shows controls if they are there, so I'd expect that to happen.

If this is not possible, it should probably be indicated [here](https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/docspage.md#remixing-docspage-using-doc-blocks) and [here](https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/props-tables.md#controls)

**Comment by shilman** [comment]
To set controls for the primary story:

```
<Props story="^" />
```

**Comment by redders6600** [comment]
Perfect, that's the one. I've also found this in the source so for anyone else who finds this in future you can also pass `.` to use the selected story (select via the sidebar).

@shilman thanks again for helping me out - really enjoying SB6.

**Comment by shilman** [comment]
FYI, we're renaming the blocks and making `^` the default in `ArgsTable`. You can still opt in to the old behavior with `of='.'`: https://github.com/storybookjs/storybook/pull/11744
