### ISSUE TITLE
Stop stringifying data over channel

### ISSUE THREAD

**Issue by ndelangen** [storybookjs/storybook#11734]
The storybook channel is an abstraction over either a post-message or websocket.

It is used to transfer data, state & commands from 1 application to another.
Most prominent use is to transfer the list of stories to the manager, and set the selected story in the preview.

When we send a command or data, we stringily it before we send it. For small bits of data this is fast, but the larger the blob of data, the longer it takes.

In large storybooks, updating stories (either the initial load, or HMR) can feel sluggish, because of this reason.

---

We stringify because some data is not serializable, such as: cyclical data, regular expressions, functions, date-objects.

---

Proposal:
We should stop stringifying the data!

We would remove the stringification & parsing code in the channel, and send the event-data as an object.

If an addon needs more rich data than is naturally serializable, then that should be handled at a higher level than the channel.

The truth is, most data we send would work just fine without stringification/parsing.

From what I've seen we can gain 1-2 seconds of start-up time and ~1s of HMR time on large storybooks.

**Comment by ndelangen** [comment]
Here's some data to back this up:

Here's a flame-chart of storybook loading:
<img width="1224" alt="Screenshot 2020-07-30 at 13 26 14" src="https://user-images.githubusercontent.com/3070389/88917593-51db9c00-d268-11ea-8786-c3c24942032b.png">
`stringifying + parsing combined = 1.08s`

**Comment by tmeasday** [comment]
I think we can likely close this. We no longer send large chunks of data (i.e. `SET_STORIES`) so I'd be surprised if this was still a low hanging fruit. We can always re-open if we find it to be an avenue worth pursuing.
