### ISSUE TITLE
Vue slots after v-if are not showing in props table of Addon Docs.

### ISSUE THREAD

**Issue by ecarrera** [storybookjs/storybook#11731]
Slots after v-if are not shown in props table of the addon "Docs".

This example will produce a table props without the slots `adolescent` neither `adult`.

```html
<slot v-if="age<=12" name="child">
  <!-- something for children -->
</slot>
<slot v-else-if="age<=19" name="adolescent">
  <!-- something for adolescents -->
</slot>
<slot v-else name="adult">
  <!-- something for adults -->
</slot>
```

My real code is the following:
```html
<!--
  @slot Dynamic slot for individual body cell. X is the column and Y is the row.
  <span class="d-block mt-3">Example: <pre class="mt-2"><code>body-x0y1</code></pre> will set the slot
  for the cell in the column at index 0 and the row at index 1</span>
  -->
<slot
  v-if="$scopedSlots[`body-x${columnIndex}y${rowIndex}`]"
  :name="`body-x${columnIndex}y${rowIndex}`"
  :cell-data="cell">
  {{ cell }}
</slot>

<!--
  @slot Dynamic slot for all cells in a column of the table body.
  <span class="d-block mt-3">Example: <pre class="mt-2"><code>body-column-0</code></pre> will set
  all the cells of the column with index 0</span>
  -->
<slot
  v-else
  :name="`body-column-${columnIndex}`"
  :cell-data="cell">
  {{ cell }}
</slot>
```

The documentation props result:

<img width="1011" alt="Screen Shot 2020-07-29 at 22 10 55" src="https://user-images.githubusercontent.com/2139735/88872541-64ae8c00-d1e8-11ea-8f74-5c64d2e219b0.png">

As you can see there isn't the slot description for `body-column-${columnIndex}`

Is this a bug or am I missing something?

**Comment by shilman** [comment]
@elevatebart know anything about this?

**Comment by elevatebart** [comment]
Hello @ecarrera 
This is indeed a known issue.

https://github.com/vue-styleguidist/vue-styleguidist/issues/430

And ultimately this

https://github.com/vuejs/vue/pull/10286

**Comment by ecarrera** [comment]
Hi @elevatebart, thanks 👍🏻 Maybe it will work for Vue 3?
