### ISSUE TITLE
@storybook/mithril@5.3.19 requires a peer of mithril@^1.1.6 but none is installed.

### ISSUE THREAD

**Issue by josephspurrier** [storybookjs/storybook#11742]
**Describe the bug**
When using the latest version of Mithril 2.0.4 and then installing @storybook/mithril 5.3.19, this warning will be thrown when you do an npm install:
`npm WARN @storybook/mithril@5.3.19 requires a peer of mithril@^1.1.6 but none is installed. You must install peer dependencies yourself.`

**To Reproduce**
1. npm init
2. npm install mithril
3. npm install @storybook/mithril
4. The warning will appear.

**Expected behavior**
I expected there to be no warning when using the latest version of Mithril.

**Screenshots**
![image](https://user-images.githubusercontent.com/2394539/89001892-87fd3800-d2c9-11ea-9af2-1fcb32363c50.png)

**Code snippets**
Here is a sample package.json:
```json
{
  "name": "jtest",
  "version": "1.0.0",
  "description": "Test",
  "main": "index.js",
  "dependencies": {
    "@storybook/mithril": "^5.3.19",
    "babel-loader": "^8.1.0",
    "mithril": "^2.0.4"
  },
  "devDependencies": {},
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git://github.com/josephspurrier/none.git"
  },
  "author": "",
  "license": "ISC"
}

```

**System:**
```
Environment Info:

  System:
    OS: macOS 10.15.5
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 12.16.1 - /usr/local/bin/node
    npm: 6.14.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 84.0.4147.105
    Firefox: 74.0
    Safari: 13.1.1
  npmPackages:
    @storybook/mithril: ^5.3.19 => 5.3.19
```

**Additional context**
None.

**Comment by josephspurrier** [comment]
Is there a way to remove the stale label on the issue?

**Comment by josephspurrier** [comment]
Ah, it's automatic. The MR is in for this.

**Comment by shilman** [comment]
Any interest in contributing a PR to fix this?

**Comment by josephspurrier** [comment]
Merged in.

**Comment by shilman** [comment]
Yee-haw!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.18 containing PR #12229 that references this issue. Upgrade today to try it out!
