### ISSUE TITLE
Fullscreen toggle does not work when all panels are collapsed

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#11782]
**Describe the bug**
I am unsure whether this is the intended behavior, but the full screen button does not work when the panels are collapsed.

A bit unrelated to the bug, but it would be great to have a tooltip of some sorts indicating that when the user goes full screen they can press the toggle button or "F", because sometimes people press letters such as "A S D F"  by mistake and might feel lost on how to get back to the normal state of which they were before. 

**To Reproduce**
1. Collapse all panels as can be seen on the video below
2. Click on the full screen toggle button

**Expected behavior**
Full screen would be toggled back and panels become visible again

**Screenshots**
![storybook issue](https://user-images.githubusercontent.com/1671563/89272123-fcbfd180-d63d-11ea-9448-991438dd0f80.gif)

**Additional context**
This has been tested on the [official-storybook@next example](https://next--storybookjs.netlify.app/official-storybook/?path=/story/addons-a11y-button--content)

**Comment by Tomastomaslol** [comment]
Hi @yannbf 

Just to clarify.do you expect the bottom panel to reappear when fullscreen mode is toggled and the sidebar is open?

![Kapture 2020-08-05 at 8 35 34](https://user-images.githubusercontent.com/1872246/89352077-a82c5d00-d6f6-11ea-8486-539e08c90343.gif)

Or is this fix only supposed affect the scenario when all panels have been closed and fullscreen mode is toggled?

I would love to try and fix this. Is this issue open for anyone to work on or is it only for a storybook team member?

**Comment by shilman** [comment]
@Tomastomaslol we welcome all contributions. any issue that is not assigned is fair game (and if an issue is assigned and you want to grab it, just check with the person it's assigned to -- they might be happy for you to take it!)

@yannbf I guess when everything is hidden and you toggle fullscreen you expect everything to be shown again?

**Comment by Tomastomaslol** [comment]
Thank you for explaining to me how it works. Could you assign this issue to me? I will try to get come up with a solution for it

**Comment by Tomastomaslol** [comment]
Could someone please confirm if this is the behaviour we desire:

### Scenario 1
* Hide `Panel` or `Nav`
* Enter fullscreen mode
* Exit fullscreen mode
* One panel should be visible

![scenarioA](https://user-images.githubusercontent.com/1872246/89377786-ded59800-d735-11ea-9663-fbcdd4115e2e.gif)


### Scenario 2 
* Hide  `Panel` and `Nav`
* Enter fullscreen mode
* Exit fullscreen mode
* `Panel` and `Nav` should be visible

![scenarioB](https://user-images.githubusercontent.com/1872246/89377685-aa61dc00-d735-11ea-81b7-1fbcc2909390.gif)


Cheers!

**Comment by yannbf** [comment]
Hey @Tomastomaslol great question! 
@domyen, what do you think is the best way from the user's perspective? Keep the precedence of closed panels or just toggle them back? 

I can see a use case where the user is developing a page on Storybook and wants to use controls in the addons panel but also want to view the page in full screen, so the user could:
- Hide the navigation
- Move addons panel to the right to change a few things on controls and save some bottom space
- Go full screen

When coming back from that (maybe to switch stories or change some controls), which would be the ideal scenario:

1 - User toggles full screen and navigation comes back with addon panel
2 - User toggles full screen and just the addon panel comes back

I created this issue because user could press some keys by mistake and if all panels are closed, full screen will do nothing. But if the intention is that full screen should not affect panels toggled by the user, then it's not a bug but a feature (although I can still see a bit of confusion in that).

**Comment by Tomastomaslol** [comment]
I had a think about this and maybe it would be helpful if we tried to redefine the issue. What about if we try to tackle the problem that the UI looks almost identical if all panels are hidden and fullscreen is toggled on and off?

## UI state when all panels are hidden, fullscreen mode OFF
![Screen Shot 2020-08-08 at 2 25 17 pm](https://user-images.githubusercontent.com/1872246/89702301-46ccee00-d983-11ea-8500-fa5a8b2dee56.png)
## UI state when all panels are hidden, fullscreen mode ON
![Screen Shot 2020-08-08 at 2 25 34 pm](https://user-images.githubusercontent.com/1872246/89702307-4fbdbf80-d983-11ea-936e-6244534e5dda.png)

Maybe a better solution to try to avoid any confusion would be to disable fullscreen mode when panels are hidden and hide the fullscreen toggle button?

**Comment by yannbf** [comment]
Question to think about:
- from a user standpoint, if you hide all panels, are you then on full screen?

If so, then I think it makes sense to have the full screen button in the "on" state when that happens, so that when the user closes it, it just does its normal behaviour which is to bring back the panels.

**Comment by Tomastomaslol** [comment]
> from a user standpoint, if you hide all panels, are you then on full screen?

That is a great point.  Playing around with UI again I think it might be beneficial to think about the full-screen mode as a separate state from `showPanel` and `showNav`. 

I can't really come up with anything else that makes sense and would be easy to understand.

At the moment I feel like we have 2 options: 

1. Go with https://github.com/storybookjs/storybook/issues/11782#issuecomment-669005097
3. Or do nothing (Which might be the best option, I'm not really sure what I think is best


@yannbf Do you have any alternative suggestions that make sense to you? If not what approach do you think makes the most sense?

**Comment by yannbf** [comment]
Hey @Tomastomaslol I guess the main problem here is the scenario of which a user (could be developer or designer/stakeholder checking a component) _by mistake_, ends up pressing one of the keys: A S D F. It could be that they were trying to type on an input component which was not focused, I don't know. In the case of the panels toggling and the user not understanding what's going on, I personally think there could be some indication for the user.

@domyen what do you think about this? Maybe it could be just a small notification that appears for 3 seconds when the toggle is done for the first time in a user session, giving a quick instruction on how to toggle back.

Also maybe I'm overthinking and like it was mentioned we could do nothing. What are your perspectives?

**Comment by domyen** [comment]
Sorry for the late reply. Was working on the 6.0 launch

> from a user standpoint, if you hide all panels, are you then on full screen?

Yes. There's a bug right now. If you hide the addon panel and sidebar the UI doesn't show the full screen "close" button, thus you end up in a dead end not knowing how to get back. 

**Strawman**
- When the sidebar or addon panels are hidden, it should enter full screen mode. 
- When you press the close button in full screen mode, it should open the sidebar. If the addon panel was previous open it should take you back to it's previous state. If the previous state of the sidebar or addon panel can't be determined, reset the manager UI.

Anyone interested in making this PR? 🙏

**re: Addons in full screen**
Not currently a behavior we support. The point of going full screen is to focus solely on your component. Folks can hide the sidebar if they want to see more of the component and the addons panel.

**re: notifications**
Not sure about adding notifications when full-screen is toggled. I think if we fix the bug it will be more obvious how to exit full screen. 

It occurs to me that we can make the keyboard shortcut more obvious by adding it to the title attribute of these buttons. That way when you hover over the full screen button or the addon panel close button it shows it.

![image](https://user-images.githubusercontent.com/263385/90319447-4940c200-df06-11ea-91ec-e3fb7f539557.png)
"Go full screen [F]"

![image](https://user-images.githubusercontent.com/263385/90319452-552c8400-df06-11ea-8fb0-8928c09ade6f.png)
"Change addon orientation [D]
"Hide addons [A]"

**Comment by Tomastomaslol** [comment]
@domyen 

> Anyone interested in making this PR? 🙏

Opened a pull request https://github.com/storybookjs/storybook/pull/11810 and tired to add test examples for all scenarios. Any feedback would be greatly appreciated.

**Comment by shilman** [comment]
¡Ay Caramba!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.0-alpha.24 containing PR #11810 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
