### ISSUE TITLE
Source loader adds `X.parameters`, clobbering `X.story.parameters`

### ISSUE THREAD

**Issue by tmeasday** [storybookjs/storybook#11780]
**Describe the bug**
Our CSF loader only allows one of `X.parameters` and `X.story.parameters` being set: https://github.com/storybookjs/storybook/blob/next/lib/core/src/client/preview/loadCsf.ts#L173:L173

However, the source loader adds `X.parameters`, effectively making it impossible to use `X.story.parameters`.

**To Reproduce**
I can create a repro if it is helpful.

**Comment by shilman** [comment]
Good golly!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-rc.25 containing PR #11781 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
