### ISSUE TITLE
Type issues in fresh CRA+TypeScript using storybook/cli@6.0.0-rc.25

### ISSUE THREAD

**Issue by wKich** [storybookjs/storybook#11791]
**Describe the bug**
After init placeholder stories in fresh CRA+TypeScript project. Project failed to start/build due type errors.

**To Reproduce**
1. `yarn create react-app my-app --template typescript`
2. `cd my-app`
3. `npx -p @storybook/cli@next sb init`
4. `yarn storybook` — Works without issues
5. `yarn start` — Failed to compile

**Expected behavior**
Application should start without issues. I think the simplest way to fix this, revert back placeholder stories files to `.jsx` extension 

**Screenshots**
![image](https://user-images.githubusercontent.com/6397708/89278556-b3807980-d65f-11ea-9098-4f079e653a68.png)

**System:**
  System:
    OS: Linux 4.19 Ubuntu 20.04 LTS (Focal Fossa)
    CPU: (16) x64 AMD Ryzen 7 1700X Eight-Core Processor
  Binaries:
    Node: 12.16.3 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
  npmPackages:
    @storybook/addon-actions: ^6.0.0-rc.25 => 6.0.0-rc.25 
    @storybook/addon-essentials: ^6.0.0-rc.25 => 6.0.0-rc.25 
    @storybook/addon-links: ^6.0.0-rc.25 => 6.0.0-rc.25 
    @storybook/node-logger: ^6.0.0-rc.25 => 6.0.0-rc.25 
    @storybook/preset-create-react-app: ^3.1.4 => 3.1.4 
    @storybook/react: ^6.0.0-rc.25 => 6.0.0-rc.25

**Comment by shilman** [comment]
Olé!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-rc.28 containing PR #11811 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
