### ISSUE TITLE
The latest version of Storybook couldn't be fetched (in static build)

### ISSUE THREAD

**Issue by Spielboerg** [storybookjs/storybook#11798]
**Describe the bug**
In the static build of Storybook, the latest version of Storybook cannot be fetched. It doesn't matter if I open the `index.html` locally or open the deployed version on my server.

**To Reproduce**
1. Build Storybook
2. Open `storybook-static/index.html` in your browser
3. Got to the "About your Storybook" page
4. Error: `Oops! The latest version of Storybook couldn't be fetched.`

**Screenshots**
<img width="763" alt="Bildschirmfoto 2020-08-04 um 17 49 50@2x" src="https://user-images.githubusercontent.com/7893762/89317081-32d07600-d67d-11ea-92d5-0205386696fe.png">

**Expected behavior**
Fetch the current version of Storybook and display the information like in the served version:
<img width="723" alt="Bildschirmfoto 2020-08-04 um 18 05 23" src="https://user-images.githubusercontent.com/7893762/89317103-395eed80-d67d-11ea-9b6f-5456fa2f9973.png">

**System:**
`npx -p @storybook/cli@next sb info` (or without `@next`) is throwing an error:
```
Environment Info:
(node:45923) UnhandledPromiseRejectionWarning: TypeError: (e || []).filter is not a function
    at /Users/<my name>/.npm/_npx/45915/lib/node_modules/@storybook/cli/node_modules/envinfo/dist/envinfo.js:1:73314
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 6)
(node:45923) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:45923) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Spielboerg** [comment]
In v6 it also does not work in the served version.

**Comment by Spielboerg** [comment]
Since v6.0.12 it works again in the served version.

**Comment by shilman** [comment]
I think we had some problems with the server which have since been resolved. Closing this.

**Comment by Spielboerg** [comment]
Unfortunately it does not work for me yet 😕 only in the served version, but neither with a local build nor with a deployed version.

Another problem is that the version number in Storybook 6.0.21 is not correct:

CLI output:
```
╭───────────────────────────────────────────────────╮
│                                                   │
│   Storybook 6.0.21 started                        │
│   11 s for manager and 12 s for preview           │
│                                                   │
│    Local:            http://localhost:6006/       │
│    On your network:  http://192.168.2.71:6006/    │
│                                                   │
╰───────────────────────────────────────────────────╯
```

Served Storybook (serving is the only way in which loading the version number works):

<img width="654" alt="Bildschirmfoto 2020-09-25 um 11 45 37@2x" src="https://user-images.githubusercontent.com/7893762/94252745-a9bf1800-ff24-11ea-8538-e9fd2302959b.png">

Build and deployed Storybook (v.6.0.21):

<img width="655" alt="Bildschirmfoto 2020-09-25 um 11 59 52@2x" src="https://user-images.githubusercontent.com/7893762/94254796-8d70aa80-ff27-11ea-9de7-b50b62a97469.png">

---

I also wonder why I don't see a failed request in the network tab of the developer tools:

![Bildschirmfoto 2020-09-25 um 12 02 04@2x](https://user-images.githubusercontent.com/7893762/94254620-55696780-ff27-11ea-90c4-30f8a8b7d553.png)

**Comment by shilman** [comment]
dupe to https://github.com/storybookjs/storybook/issues/12183

**Comment by Spielboerg** [comment]
@shilman Could you please re-open this issue, as it has not been fixed yet?

In your official example it does not work either: https://storybookjs.netlify.app/official-storybook/?path=/settings/about

**Comment by Spielboerg** [comment]
Not fixed in v6.1.11

**Comment by pixelkritzel** [comment]
Still an issue with 6.1.21

**Comment by Greenie10** [comment]
Still an issue with 6.2.7

<img width="581" alt="Screenshot 2021-04-13 at 08 17 33" src="https://user-images.githubusercontent.com/1492173/114512208-c278ec00-9c30-11eb-888c-8ca2e3d8c479.png">

**Comment by RiteshMakan** [comment]
Seems to still be an issue, unless there is something that I am missing in config somewhere

![Screenshot 2021-07-08 at 11 52 49](https://user-images.githubusercontent.com/82932397/124902294-16526180-dfe3-11eb-92ac-5f99acdce157.png)

**Comment by siyavash4812** [comment]
Still not working!
<img width="1043" alt="Screenshot 2021-09-16 at 17 44 11" src="https://user-images.githubusercontent.com/22658677/133652278-eb96fbd6-32bd-40b2-a36c-8c9cf68f396e.png">

]

**Comment by holamau** [comment]
Yeah... the deployed (build) version of sb always throws this error. currently on 6.3.12 
<img width="684" alt="Screen Shot 2021-10-29 at 2 14 13 PM" src="https://user-images.githubusercontent.com/6577028/139489927-e3a41155-7edf-4bed-a5fd-49a1a6c1f947.png">

**Comment by telestrial** [comment]
I decided to take a look at this one, and I have some information to push it ahead. I do not have a solve, yet.

1) First off, the actual object coming into the AboutScreen component in `about.tsx` looks like this:

![sb_version1](https://user-images.githubusercontent.com/1040081/174491469-ff62246b-8d43-4f0d-964c-a7e11a050ff6.PNG)

And so it is no wonder that this always happens. Our `canUpdate` in this file will always evaluate to null, which means we will always take the `Oops! ...` route.

2) Following this to the base of where I think this "latest" property gets fetched brings us to `updateCheck` in `update-check.ts`:

```typescript
export const updateCheck = async (version: string): Promise<VersionCheck> => {
  const time = Date.now();
  try {
    const fromCache = await cache.get('lastUpdateCheck', { success: false, time: 0 });

    // if last check was more then 24h ago
    if (time - 86400000 > fromCache.time && !CI) {
      const fromFetch: any = await Promise.race([
        fetch(`${STORYBOOK_VERSION_BASE}/versions.json?current=${version}`),
        // if fetch is too slow, we won't wait for it
        new Promise((res, rej) => global.setTimeout(rej, 1500)),
      ]);
      const data = await fromFetch.json();
      result = { success: true, data, time };
      await cache.set('lastUpdateCheck', result);
    } else {
      result = fromCache;
    }
  } catch (error) {
    result = { success: false, error, time };
  }
  return result;
};
```

To be honest, I'm a junior developer and don't understand everything about what I'm looking at here. However, I do **not** think that the problem is that we're hitting the timeout promise. I believe someone alludes to that upward in this thread, and I just don't buy it. `https://storybook.js.org/versions.json` responds well within 1500 milliseconds. Usually ~200 for me. Here are some questions I have:

* What's the best way to log output from this? I've been trying different methods and I can't seem to get output either when I build or within the browser. Is nodelogger the thing to use here? Any help here would be appreciated as I could step through this function and get more details about what it's doing and when.
* What is the actual value being passed into this function and why are we using it as a parameter on the .json file? Can you even query a .json file like this? `https://storybook.js.org/versions.json?current=?????`.  The .json file has no property of "current," if that's what this is trying to get at.

**Comment by Spielboerg** [comment]
Probably not a big surprise, but just wanted to mention it: It's still not working in v7.

**Comment by Spielboerg** [comment]
With v7.1.0 the About page has changed and no longer checks for updates, but shows only generic information:

<img width="440" src="https://github.com/storybookjs/storybook/assets/7893762/52cad0e6-5e57-4c1f-b53f-74f63c69e78e">

I consider this as "fixed" and therefore close this issue.
