### ISSUE TITLE
packages should not install react as dependency

### ISSUE THREAD

**Issue by zhaoyao91** [storybookjs/storybook#11809]
**Describe the bug**

packages, such as [storybook/addons/actions](https://github.com/storybookjs/storybook/blob/next/addons/actions/package.json#L43) installs `react` as dependency, this may cause [duplicate react problem](https://reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react).

say, I have a component package which declares react as peerDependency but installs storybook as devDependency. in the final app, it locks the version of react and install my component package, but the app will have installed two versions of react since install my component will install storybook, and install the inner react.

```
ncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
```

storybook in my component package
```
devDependencies:

    "@storybook/addon-actions": "^6.0.0-rc.25",
    "@storybook/addon-essentials": "^6.0.0-rc.25",
    "@storybook/addon-links": "^6.0.0-rc.25",
    "@storybook/react": "^6.0.0-rc.25",
```

react in my app

```
dependencies:

    "react": "~16.8.0",
    "react-dom": "~16.8.0",
```

**Comment by wintercounter** [comment]
Same problem on my side. It's completely failing our Storybooks now (we're updating custom configs to the new way).

**Comment by wintercounter** [comment]
Update: Seems like with latest RC everything's fine.

**Comment by shilman** [comment]
That error can be due to duplicate versions of React, but can also be due to a variety of other things.

The `Docs` tab mixes user code & Storybook code and can potentially mix React versions.

The `Canvas` tab isolates the user's environment, so if you're seeing this on `Canvas` my guess is that it's an issue with your code and probably unrelated to the multiple versions.

**Comment by wintercounter** [comment]
As OP said it started to happen when addon-actions was added. For me when I added addon-docs. As I stated the latest 6.0.0 RC fixed the problem for me, so the issue must have been around Storybook somewhere.

**Comment by jimmyandrade** [comment]
+1

**Comment by RiyadWu** [comment]
> Update: Seems like with latest RC everything's fine.

The latest version still have this bug
