### ISSUE TITLE
6.0 isn't possible to reset UI in Vue if props don't provide default value

### ISSUE THREAD

**Issue by rockmandash** [storybookjs/storybook#11819]
It seems like if your Vue component doesn't provide a default value, you won't be able to reset UI due to this line.

![image](https://user-images.githubusercontent.com/7580792/89488169-dcc51500-d7d9-11ea-9519-3febbed1bc36.png)

https://github.com/storybookjs/storybook/blob/dee5c3ec5dec5cb6d870b2c573326246b0ac7b5b/lib/client-api/src/story_store.ts#L482

###### Step to Reproduce

1. `vue create hello-world`
2. `cd hello-world`
3. `npx sb@next init`
4. `npm run storybook`
5. hit the rest button on Button stories

**Comment by shilman** [comment]
This was introduced in https://github.com/storybookjs/storybook/releases/tag/v6.0.0-rc.26

Apparently the telejson upgrade has broken `undefined` serialization. Will follow up there.

**Comment by shilman** [comment]
Shiver me timbers!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-rc.29 containing PR #11829 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
