### ISSUE TITLE
addon-docs blocks has no exported member SourceState

### ISSUE THREAD

**Issue by Bellfalasch** [storybookjs/storybook#11828]
**Describe the bug**
So, this might be intentional from your side, but after the refactoring of Preview > Canvas we can no longer use the exportet enum `SourceState` from addon-docs blocks. We used it for customizing our Preview and making sure type checking worked internally for `SourceState`. No later RC-release of SB6 works for this.

**Error message**
```
TS2305: Module '"../../../node_modules/@storybook/addon-docs/blocks"' has no exported member 'SourceState'.
```

The odd thing is that if I look at [Canvas.tsx](https://github.com/storybookjs/storybook/blob/next/addons/docs/src/blocks/Canvas.tsx) it does export `SourceState`, and within the index.ts it too exports * from Canvas. So not really sure why I cannot use it.

**To Reproduce**
1. Use SB6 for your application, RC19 or any later RC version (tested up to RC27).
2. Create a .tsx file and import the enum:
`import { Preview, SourceState } from '@storybook/addon-docs/blocks';`
3. See error in terminal logs.

**Expected behavior**
Before refactoring we could use this enum for type checking in our modified `<Preview>`. This .tsx worked previously, on lower RC versions, or on the beta, this error does not occur.

**Comment by shilman** [comment]
Seems to be working for me. Do you have a repro?

**Comment by Bellfalasch** [comment]
We basically just implemented what we needed in our own code, as it was only three different options. So haven't experienced this issue because of that. This can be closed, it was raised during beta/alpha and nobody else experienced this.
