### ISSUE TITLE
Links in included Introduction.stories.mdx are broken

### ISSUE THREAD

**Issue by Yardie83** [storybookjs/storybook#11830]
**Describe the bug**
Most links in the Introdcution.stories.mdx are pointing to nonexisting or outdated sites

**To Reproduce**
1. npx  sb@next init
2.  run storybook
3. click on the links in Introduction.stories.mdx

**Expected behavior**
Links should point to the right websites

**Comment by shilman** [comment]
Yep it's a prerelease. Those links will be live by the time we release. Thanks & sorry for the confusion!

**Comment by Yardie83** [comment]
Hi, thanks for the reply. Just as a suggestion, I know it's always easier said than done, but maybe put preleases or unreleased things in its own category like "next", or "lab" in the storybook to make it clear what is available and what not. Have a great day!

**Comment by shilman** [comment]
Thanks! should be fixed now! 🤞
