### ISSUE TITLE
Storybook can't detect dynamic Vue Component Props' default values both in v6 and v5.

### ISSUE THREAD

**Issue by rockmandash** [storybookjs/storybook#11837]
Thanks for resolving bugs so fast for previously issues!

**Describe the bug**

When Storybook is analyzing a Vue Component Props' default values, it only supports static analysis, no dynamic.

![image](https://user-images.githubusercontent.com/7580792/89706954-c74c1880-d99c-11ea-9f91-52c99b13a1bd.png)
![image](https://user-images.githubusercontent.com/7580792/89706959-ce732680-d99c-11ea-9b88-df3a3a5e7921.png)

**To Reproduce**

1. `vue create sb6-test` with TypeScript template
2. `cd sb6-test`
3. `npx sb@next init`
4. create two files

### TestProp.vue

```vue
<template>
  <div :style="style" />
</template>

<script lang="ts">
import Vue, { PropType } from "vue";

export default Vue.extend({
  props: {
    backgroundSize: {
      default: "cover" as const,
      type: String as PropType<"contain" | "cover">,
      validator: (value) => ["contain", "cover"].includes(value),
    },
  },

  computed: {
    style() {
      return {
        width: "200px",
        height: "200px",
        background: "url(https://source.unsplash.com/weekly?water)",
        backgroundSize: this.backgroundSize,
        backgroundPosition: "center center",
      };
    },
  },
});
</script>
```

### TestProp.stories.js

```js
import TestProp from "./TestProp.vue";

export default {
  title: "TestProp",
  component: TestProp,
};

export const Primary = (args, { argTypes }) => ({
  props: Object.keys(argTypes),
  components: { TestProp },
  template: '<TestProp v-bind="$props"/>',
});
```

Storybook can't detect dynamic Vue Component Props' default values in this case.

However, I can't simply remove `as const` since it will widen to `string type`.

**Suggestion**

If you log out Vue Components, you can get the real default value like this

```js
import TestProp from "./TestProp.vue";

console.log("TestProp", JSON.stringify(TestProp.options.props));
// =>  { backgroundSize: { default: "cover" } }
```

Maybe using this method can solve the problem.

**Comment by shilman** [comment]
@elevatebart any thoughts on this one?

**Comment by adallos** [comment]
I'm having this bug as well!! Any updates? 😮

**Comment by shilman** [comment]
@elevatebart is this something `vue-docgen-api` would ever support?

@jonniebigodes this is the kind of limitation we probably need to add to the documentation ... so many different corner cases tho.

**Comment by elevatebart** [comment]
@shilman @rockmandash I was very busy recently but this seems like a quick fix that should be done on the vue-docgen-api side. 

Let me see what I can cook up.

**Comment by elevatebart** [comment]
I delivered 4.33.1 in which I only take the value of the expression of default... fixing the bug mentioned here ;)

**Comment by shilman** [comment]
Good golly!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.0-alpha.26 containing PR #12808 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
