### ISSUE TITLE
Please move applied "zoom" css property to preview root rather than body

### ISSUE THREAD

**Issue by IgorSzyporyn** [storybookjs/storybook#11833]
**Is your feature request related to a problem? Please describe.**
When you apply the zoom feature in "Canvas" - this will leak into other panels like "Docs"

**Describe the solution you'd like**
Please move the css property "zoom" with applied value to "iframe > body > #root" element instead

**Describe alternatives you've considered**
No other alternative exists

**Are you able to assist bring the feature to reality?**
Thought it would be a rather easy fix - looked in source, not simple

**Additional context**
![Capture](https://user-images.githubusercontent.com/6172338/89663754-4f1b1f80-d8d6-11ea-8f76-d13d9d4864a3.PNG)

Thank you

**Comment by Tomastomaslol** [comment]
Hi @IgorSzyporyn The behaviour you are describing sounds very similar to https://github.com/storybookjs/storybook/issues/11662. There should be a fix for this in the latest next build. 

Are you still able to recreate the behaviour in the latest next build of Storybook?

https://next--storybookjs.netlify.app/official-storybook/

**Comment by IgorSzyporyn** [comment]
@Tomastomaslol tested, and fixed in next
