### ISSUE TITLE
[BUG] Angular+Docs "Show code" button does not exist for stories described in MDX

### ISSUE THREAD

**Issue by oleg088097** [storybookjs/storybook#11832]
**Describe the bug**
Stories described in MDX files don't have "Show code" in Docs page.

**To Reproduce**
1. Run storybook in examples/angular-cli
2. Check any story in "background" section. All of them have "Show code" in Docs tab
3. Check any story in "docs" section. None of them have "Show code" in Docs tab

**Expected behavior**
I expect Docs stories to have "Show code" just like any other story. The only difference between them - docs described with MDX. The same conclusion I have from my local experiments - MDX stories in angular don't have that button.

**Screenshots**
MDX stories:
![image](https://user-images.githubusercontent.com/36167478/89656898-ed0dea80-d8d4-11ea-900a-e5f0f5d4f856.png)

CSF stories:
![image](https://user-images.githubusercontent.com/36167478/89656952-057e0500-d8d5-11ea-96f9-2334b86fb6b1.png)

**System:**
Branch next
Storybook 6.0.0-rc.29
Angular 9.1.0

Environment Info:
  System:
    OS: Windows 10 10.0.17134
    CPU: (8) x64 Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
  Binaries:
    Node: 12.11.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 84.0.4147.105
    Edge: Spartan (42.17134.1098.0)

**Comment by shilman** [comment]
Are you wrapping the `<Story>` in a `<Canvas>` wrapper?

```jsx
import { Story, Meta, Canvas } from '@storybook/addon-docs/blocks';
import { Button } from '@storybook/angular/demo';

<Meta title="Addon/Docs" decorators={[withKnobs, moduleMetadata({ declarations: [Button] })]} />

<Canvas>
  <Story name="with text">
    {{
      template: `<storybook-button-component [text]="text" (onClick)="onClick($event)"></storybook-button-component>`,
      props: {
        text: text('Button text', 'Hello Button'),
        onClick: () => {},
      },
    }}
  </Story>
</Canvas>
```

**Comment by oleg088097** [comment]
@shamin yep, still the same
![image](https://user-images.githubusercontent.com/36167478/89731249-1ef68c80-da4e-11ea-9c40-30bc1ca6e753.png)
![image](https://user-images.githubusercontent.com/36167478/89731265-43526900-da4e-11ea-82c5-884aa65e6846.png)

**Comment by oleg088097** [comment]
@shilman I need to wrap it with Canvas, I see. Thanks, missed that
