### ISSUE TITLE
Create stories in JSON?

### ISSUE THREAD

**Issue by jayarjo** [storybookjs/storybook#11851]
Is it possible to create stories in some other format, more portable that is, in json for example?

**Comment by jayarjo** [comment]
@shilman I'm eager to invest my time in writing something like this, however not being familiar with the architecture of the Storybook itself, my plan is to simply:

 * have stories in my own format in json
 * make webpack to somehow pick them up
 * have custom webpack loader for given files that will transform them to regular React stories

If you guys interested in something like this as well, any advice or a hint is appreciated.

**Comment by shilman** [comment]
Sorry for the slow reply. This issue slipped through the cracks.

We currently support a JSON format in `@storybook/server`: https://github.com/storybookjs/storybook/blob/next/app/server/README.md#writing-stories

We expect to invest more in this in the future, so I'd recommend using this as your format if it works for you.

**Comment by jayarjo** [comment]
@shilman while this is cool, it doesn't seem to be a proper equivalent for what I'm looking for.

Any reason of not having JSON as the single shared format? All framework specific storybook extensions could simply compile into one standartised JSON format and then this JSON can be processed by storybooks core.

**Comment by shilman** [comment]
@jayarjo how do you specify functions in JSON?

**Comment by jayarjo** [comment]
@shilman good point, haven't thought about that. It even didn't come to me, probably because all of our stories are very declarative.

**Comment by ndelangen** [comment]
Here it is:
https://storybook.js.org/docs/react/api/csf#page-top
