### ISSUE TITLE
Decorator does not wrap the story

### ISSUE THREAD

**Issue by nareshbhatia** [storybookjs/storybook#11852]
**Describe the bug**
The decorator is expected to _decorate_/wrap a story. Instead the story is wrapping the decorator. Please see below. Note that `storyFn` is wrapping the decorator (`ThemeProvider`).

![image](https://user-images.githubusercontent.com/1220198/89737602-1b5c0900-da40-11ea-9c02-5e5f93e4b271.png)

**To Reproduce**
1. Create a simple decorator like this one:

```
addDecorator((storyFn) => (
    <ThemeProvider theme={theme}>
        {storyFn()}
    </ThemeProvider>
));
```

2. Run Storybook and inspect the component hierarchy using React Dev Tools. You will find that `storyFn` is wrapping `ThemeProvider` instead of the other way round.

As a result, the story itself can't use the context provided by the `ThemeProvider`. Interestingly enough, the way the hierarchy is set up, child components of the story can!

BTW, the exact same functionality used to work with the `storiesOf` API:

```
const StoryDecorator = (story: any) => (
    <ThemeProvider theme={theme}>
        {story()}
    </ThemeProvider>
);

storiesOf('Header', module)
    .addDecorator(StoryDecorator)
    .add('Header', () => <Header />);
```

**Expected behavior**
Decorator should wrap `storyFn`.

**Screenshots**
Here's my [live Storybook](https://nareshbhatia.github.io/react-force/?path=/story/core-header--header-story). Simply inspect in React Dev Tools and you will see the component hierarchy as shown above.

**Code snippets**
Here' s my [Storybook code showing the decorator](https://github.com/nareshbhatia/react-force/blob/master/.storybook/preview.tsx#L12-L20).

**System:**
Please paste the results of `npx -p @storybook/cli@next sb info` here.

```
  System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz
  Binaries:
    Node: 12.18.2 - ~/.nvm/versions/node/v12.18.2/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.2/bin/npm
  Browsers:
    Chrome: 84.0.4147.105
    Safari: 13.1.2
  npmPackages:
    @storybook/addon-console: ^1.2.1 => 1.2.1
    @storybook/addon-essentials: 6.0.0-rc.21 => 6.0.0-rc.21
    @storybook/addon-links: 6.0.0-rc.21 => 6.0.0-rc.21
    @storybook/addons: 6.0.0-rc.21 => 6.0.0-rc.21
    @storybook/react: 6.0.0-rc.21 => 6.0.0-rc.21
```

**Additional context**
Here are some related issues that have the same root cause:
1. https://github.com/storybookjs/storybook/issues/8426
2. https://github.com/storybookjs/storybook/issues/8531

**Comment by shilman** [comment]
What happens when you use:

```ts
const StoryDecorator = (Story: any) => (
    <ThemeProvider theme={theme}>
        <Story />
    </ThemeProvider>
);
```

**Comment by nareshbhatia** [comment]
@shilman, can you please clarify your suggestion? I don't understand where I would use the `StoryDecorator`. Are you suggesting that I go back to the `storiesOf` API? The latest [Decorators](https://storybook.js.org/docs/basics/writing-stories/#decorators) documentation does not describe anything like this.

**Comment by shilman** [comment]
Try replacing this code: 

```ts
const StoryDecorator = (story: any) => (
    <ThemeProvider theme={theme}>
        {story()}
    </ThemeProvider>
);
```

With this code:

```ts
const StoryDecorator = (Story: any) => (
    <ThemeProvider theme={theme}>
        <Story />
    </ThemeProvider>
);
```

**Comment by nareshbhatia** [comment]
Ah, ok. So that's to be used in conjunction with `addDecorator`:

```
addDecorator(StoryDecorator);
```

Yes, that indeed fixes the issue. Interesting that it adds an `Anonymous` component wrapping the story:

![image](https://user-images.githubusercontent.com/1220198/89747420-b67ad000-da8c-11ea-9151-770bfe545a4c.png)

Not sure what's going on under the scenes, but should this be the preferred way to use the decorator compared to the docs?

**Comment by nareshbhatia** [comment]
Please feel free to close this issue. However I would suggest an action item to clarify the difference between `{storyFn()}` as suggested in current docs, vs. `<Story />` as suggested in this issue, which seems to work better.

**Comment by nareshbhatia** [comment]
Never mind - just looked at the final 6.0 docs and `<Story />` is the recommended way.

Closing.

**Comment by backnotprop** [comment]
In 2021, the only way Ive been able to get this to work is with a `memo` component. Otherwise we introduce an infinite rendering loop. 

Wrapper 1 -- Decorator:
```
export default {
  title: 'Similarity/FullDemo',
  decorators: [
    (Story): ReactElement => (
      <AIXViewsContainer>
        <Story />
      </AIXViewsContainer>
    ),
  ],
};
```

Wrapper 2 -- Use context
```
export const Template = (args: any) => {
  const AIXCONTEXT = useContext(AIXContext);
  const { states } = AIXCONTEXT;
  return <Memod s={states} />;
};
```

Actual Story -- memo component
``` 
const Memod = React.memo(({ s }: { s: Readonly<IStateAIXViews> }) => (
... what we actually intend to render ...
```
