### ISSUE TITLE
Addon-docs: Adding id for story in CSF breaks story source preview ("No code available")

### ISSUE THREAD

**Issue by klavsjs** [storybookjs/storybook#11865]
**Describe the bug**
When enabling [permalinking of a story](https://github.com/klavsjs/storybook-addon-docs-story-id/blob/4bb58af07c9732123f4dafee74fa577a0b21194e/src/stories/1-Button.stories.js#L7) by adding an `id` to the story in CSF, the story source preview button in the `Docs` view becomes disabled with the label "No code available".

**To Reproduce**
1. Clone https://github.com/klavsjs/storybook-addon-docs-story-id
2. Run `yarn && yarn storybook`
3. Story source preview button for stories under the path `/?path=/docs/someid--text` in the `Docs` is disabled with label _No code available_
4. Remove the story id ([line 7](https://github.com/klavsjs/storybook-addon-docs-story-id/blob/4bb58af07c9732123f4dafee74fa577a0b21194e/src/stories/1-Button.stories.js#L7)) in `src/stories/1-Button.stories.js`
5. Story source preview button becomes enabled with label _Show code_

**Expected behavior**
Story source preview should be available with or without setting an id for a story.

**Screenshots**
![image](https://user-images.githubusercontent.com/4437820/89777294-14062f80-db14-11ea-99ab-366c00c9fcf0.png)

**Code snippets**
```
import React from 'react';
import { Button } from '@storybook/react/demo';

export default {
  title: 'Button',
  id: 'someId',
  component: Button,
};

export const Text = () => <Button>Hello Button</Button>;
```

**System:**
    - OS: macOS 10.15.6
    - CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    - Node: 13.12.0 - ~/.nodenv/shims/node
    - Yarn: 1.22.4 - /usr/local/bin/yarn
    - npm: 6.14.4 - ~/.nodenv/shims/npm
  Browsers:
    - Chrome: 84.0.4147.105
    - Firefox: 79.0
    - Safari: 13.1.2
  npmPackages:
    - @storybook/addon-actions: ^5.3.19 => 5.3.19 
    - @storybook/addon-docs: ^5.3.19 => 5.3.19 
    - @storybook/addon-links: ^5.3.19 => 5.3.19 
    - @storybook/addons: ^5.3.19 => 5.3.19 
    - @storybook/preset-create-react-app: ^3.1.4 => 3.1.4 
    - @storybook/react: ^5.3.19 => 5.3.19

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid.

Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
