### ISSUE TITLE
Addon knobs - object converting deep objects to ["Object"]

### ISSUE THREAD

**Issue by mamodom** [storybookjs/storybook#11863]
**Describe the bug**
The addon knob of type object transforms deep objects to ["Object"]. The value is not thrown away, but it makes it imposible to modify these values

**To Reproduce**
1. Create an addon of type `object`
2. through the addons ui, set the value of the addon to the output of:
```
JSON.stringify(
  [...Array(15)]
    .map((_, i) => i)
    .reduceRight((acc, cur) => ({ [cur]: acc }), {})
);
```
3. The contents of the knob are then formatted.
4. for depth: 9, the text area displays `"9": "[Object]"`

**Expected behavior**
I expect to see all the keys like this:
`"9": { "10": { "11": { "12": { "13": { "14": {} } } } } }`
Without that I'm not able to modify deeply nested values

**Screenshots**

![Screen Recording 2020-08-10 at 11 25 06](https://user-images.githubusercontent.com/5097424/89769117-ebbf0680-dafc-11ea-8bee-38bea375d366.gif)

**Code snippets**
N/A

**System:**
```
Environment Info:

  System:
    OS: macOS 10.15.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 12.18.1 - ~/.nvm/versions/node/v12.18.1/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v12.18.1/bin/yarn
    npm: 6.12.1 - ~/dev/klarna/shipping-module-frontend/node_modules/.bin/npm
  Browsers:
    Chrome: 84.0.4147.105
    Firefox: 78.0
    Safari: 13.1.2
  npmPackages:
    @storybook/addon-knobs: ^5.3.19 => 5.3.19 
    @storybook/addon-links: ^5.3.19 => 5.3.19 
    @storybook/addon-options: ^5.3.19 => 5.3.19 
    @storybook/addon-viewport: ^5.3.19 => 5.3.19 
    @storybook/addons: ^5.3.19 => 5.3.19 
    @storybook/cli: ^5.3.19 => 5.3.19 
    @storybook/react: ^5.3.19 => 5.3.19 
```

**Additional context**
N/A

**Comment by shilman** [comment]
FYI, we’ve released addon-controls in Storybook 6.0. Controls are portable, auto-generated knobs that are intended to replace addon-knobs long term.

- [Controls README](https://github.com/storybookjs/storybook/tree/next/addons/controls)
- [Migration instructions](https://github.com/storybookjs/storybook/blob/next/addons/controls/README.md#how-do-i-migrate-from-addon-knobs)
- [Walkthrough: Controls w/ CRA & TypeScript](https://gist.github.com/shilman/69c1dd41a466bae137cc88bd2c6ef487)

Please upgrade and try them out today!
