### ISSUE TITLE
Presets: Rename `config` to `previewEntries`

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#11875]
Make it parallel to `managerEntries` for consistency:
- [ ] Add `previewEntries`
- [ ] Deprecate `config`
- [ ] Update the entrypoint generation in core
- [ ] Update all addons
- [ ] Update documentation

NOTE: I tried to do this quickly and it failed, so punting to 6.1

**Comment by ndelangen** [comment]
I think you might have had issues with the generated entry-point naming perhaps?

**Comment by ndelangen** [comment]
This has been replaced by having addons have a `./preview` export, and these are auto-loaded, without a need to explicitly configure previewEntries.

Though I still really prefer previewEntries, @tmeasday has made changes internally to name them `previewAnnotations`.
for example see here:
https://github.com/storybookjs/storybook/blob/74f55bd35da98a227b0af16d91b7bcb10b26cc30/code/frameworks/nextjs/src/preset.ts#L67-L70

@shilman do you think we should put this in 7.0 beta?

**Comment by tmeasday** [comment]
@ndelangen actually `previewEntries` were a subtly different thing from `config` / `previewAnnotations` and it was cleaned up in https://github.com/storybookjs/storybook/pull/19152. We can close this issue I think?
