### ISSUE TITLE
Storybook 6.1 Release 🚀 

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#11884]
Storybook 6.1 is in RC (release candidate). Originally scheduled for a January release, we've accelerated the schedule to support React 17 in a stable release as quickly as possible.

## Schedule

- ✅ `6.1.0-alpha.0` 2020-09-01
- ✅ `6.1.0-beta.0` 2020-11-02
- ✅ `6.1.0-rc.0` 2020-11-12
- 🏁 `6.1.0` 2020-11-17 ETA

## Contents

- Fast search and navigation #12601
- Manager caching for faster startup #12707
- Asynchronous loaders #12699 
- React improvements
  - React 17 support #12972 #12975
  - Fast refresh #12470 #12535
  - Strict mode #12781

Plus hundreds more changes of varying sizes and shapes, documented in the [CHANGELOG](https://github.com/storybookjs/storybook/blob/next/CHANGELOG.md)

## Help wanted

We need your help stabilizing Storybook 6.1 for the final release. It's in RC now because we think it's ready to use in most projects and we'll only be providing bugfixes between now and the release.

To upgrade to 6.1-RC:

```
npx sb upgrade --prerelease
```

There should be no breaking changes in 6.1. See [MIGRATION guide](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#from-version-60x-to-610) for potential gotchas.

And of course, if you see any [issues](https://github.com/storybookjs/storybook/issues) that you can help with, PRs are always welcome. Storybook wouldn't be possible without high-quality contributions from our wonderful community.

Thanks for your help and stay posted for more updates!

**Comment by AlanGreene** [comment]
Hopefully the date is just a typo 😉 Really looking forward to using some of the changes introduced in this release! Thanks for all the hard work.

🏁 6.1.0 **2021**-11-17 ETA

**Comment by shilman** [comment]
LOL @AlanGreene typo indeed. it was originally scheduled for jan, but we had to move it up for react17 support. 🙈  hopefully shipping today or tomorrow! 🤞

**Comment by shilman** [comment]
And it's done. After 6.1 stabilizes, we're onto 6.2! #13160
