### ISSUE TITLE
Docs: react/configure/integration#extending-storybooks-webpack-config is 404

### ISSUE THREAD

**Issue by matamatanot** [storybookjs/storybook#11896]
**Describe the bug**
https://storybook.js.org/docs/react/configure/integration#extending-storybooks-webpack-config is 404

**To Reproduce**
1. Go to 'https://storybook.js.org/docs/react/configure/overview#configure-your-storybook-project'
2. Click on 'webpackFinal - custom [webpack configuration](https://storybook.js.org/docs/react/configure/integration#extending-storybooks-webpack-config).'
3. See 404

**Expected behavior**
Go to https://storybook.js.org/docs/react/configure/webpack

**Comment by domyen** [comment]
@jonniebigodes we broke out integration into several files so the new url is `https://storybook.js.org/docs/react/configure/webpack#extending-storybooks-webpack-config`

Might make sense to search the project for all instances of `https://storybook.js.org/docs/react/configure/integration` (which no longer exists) and replace it with the correct urls.

**Comment by jonniebigodes** [comment]
@matamatanot sorry for the inconvenience, we've been doing a big overhaul in the documentation and it seems that some items need a bit more of attention. 

@domyen i'm going to take a look at the documentation and check the links.


Stay safe

**Comment by jonniebigodes** [comment]
@matamatanot i've just merged the pull request. Soon the changes will be in place. 

Once again thank you for bringing us this to our attention
