### ISSUE TITLE
Upgrade react-syntax-highlighter in order to delete security issue about prismjs

### ISSUE THREAD

**Issue by lauthieb** [storybookjs/storybook#11890]
**Describe the bug**

It could be nice to upgrade `react-syntax-highlighter` to its last version 13.3.1 because it causes a security issue on my repository about `prismjs` (https://github.com/advisories/GHSA-wvhm-4hhf-97x9).

So, we need `prismjs` major to 1.21.0. This has been required in last version of `react-syntax-highlighter` (13.3.1) that Storybook uses in `@storybook/components` :

![image](https://user-images.githubusercontent.com/9600228/89887174-1d53d280-dbce-11ea-9edb-79f1301869e7.png)

Thanks a lot for your help.

**Comment by rnsloan** [comment]
Fixed by #11838

**Comment by shilman** [comment]
Ermahgerd!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.0-alpha.0 containing PR #11838 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
@yoiang there will be another comment if this gets patched back to 6.0.x. my script closes issues when the fix is published, regardless of whether it's a stable or prerelease version--basically once it's easily available to use.

**Comment by yoiang** [comment]
@shilman oh that's perfect, thanks for letting me know! Are these your own scripts or are they publicly available, that sounds super handy
