### ISSUE TITLE
Storybook 6 wrong style order with material ui

### ISSUE THREAD

**Issue by NorbertBodziony** [storybookjs/storybook#11906]
**Describe the bug**
After upgrading  to storybook 6 from version 5.3 material (v4.11.0) styles are overwritten by default ones. This is not consistent some components work fine. I am using `create react app` with typescript.

**Screenshots**
![image](https://user-images.githubusercontent.com/38857779/89932625-367c7380-dc0e-11ea-9573-11e2663d110d.png)

**Code snippets**
`main.js`
```
module.exports = {
  stories:['../src/**/*.stories.tsx'],
  addons: [
    '@storybook/preset-create-react-app',
    '@storybook/addon-actions/register',
    '@storybook/addon-knobs/register',
    '@storybook/addon-viewport/register',
    '@storybook/addon-storysource'
  ]
}
```
`preview.js`
```
import { addDecorator, addParameters } from '@storybook/react'
import { muiTheme } from 'storybook-addon-material-ui'
import { themes } from '@storybook/theming'
import { theme } from '../src/static/theme'

addDecorator(muiTheme([theme]))
addParameters({
  backgrounds: [
    { name: 'dark', value: '#202020', default: true },
    { name: 'light', value: '#FFFFFF' }
  ],
  options: { theme: themes.dark }
})
```
I found some issues with exact problem but fix does not work https://github.com/mui-org/material-ui/issues/14348

Edit: After change on hot reload styles works in correct order.

**Comment by NorbertBodziony** [comment]
So i fixed that by adding :
```
addDecorator(storyFn => (
  <StylesProvider injectFirst>
      { storyFn() }
  </StylesProvider>
))
```
Instead of 
```
export const withStylesDecorator = storyFn => (
  <StylesProvider injectFirst>{storyFn()}</StylesProvider>
)
```
and 
```
addDecorator(withStylesDecorator)
```
No idea why it works.

**Comment by mykola-yarchuk** [comment]
Thank you guys it helps, but it looks a bit different at this point.

this worked for me:

`preview.js`

`import { StylesProvider } from "@material-ui/styles";

export const decorators = [
  (storyFn) => (
    <StylesProvider injectFirst>
      {storyFn()}
    </StylesProvider>
  )
]`
