### ISSUE TITLE
Vue components with `functional: true` invoked without `context` argument when included in metadata

### ISSUE THREAD

**Issue by Ignigena** [storybookjs/storybook#11912]
**Describe the bug**

After upgrading Storybook from 5.3 to 6, we had several stories breaking so dramatically it would prevent the entire Storybook from loading. The error message was rather vague and it took a bit to isolate the issue from the number of stories we had. After digging in, it appears that the issue is due to Vue components which have been marked as `functional`.

For functional components, the `render` function is invoked with a second `context` argument. While the actual story itself works fine, if we pass the Vue component to the `component` property on the default export the entire build fails. In our case, we were de-structuring this context argument and it appears that when the component is invoked as part of the story setup it is done without the second argument.

To solve for this we had to remove the component assignment on the story metadata.

**To Reproduce**

1. Add a new Vue functional component where the `context` argument is required, ex:

```js
export default {
  functional: true,
  props: {
    name: {
      type: String,
      required: true
    }
  },
  render (h, { props }) {
    return h('h1', `Hello ${props.name}`)
  }
}

```

2. Add a new story for the component where the story metadata includes the component:

```js
import Greeting from './Greeting.vue'

export default {
  title: 'Greeting',
  component: Greeting
}

export const Component = () => ({
  components: { Greeting },
  template: '<Greeting name="World" />'
})
```

3. Launch the Storybook
4. Observe the error message

**Expected behavior**

The functional Vue component should be invoked with the `context` argument supplied.

**Actual behaviour**

The entire Storybook is broken, not just the individual story we just added. The error message is not very clear and the stacktrace does not point to the actual story that had issues. This means you essentially have to disable stories one at a time until you find the one with issues.

```
Cannot convert undefined or null to object
TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at http://localhost:51561/vendors~main.e1ac2f87c909a581580c.bundle.js:25799:12
    at Array.reduce (<anonymous>)
    at combineParameters (http://localhost:51561/vendors~main.e1ac2f87c909a581580c.bundle.js:25798:32)
    at enhanceArgTypes (http://localhost:51561/vendors~main.e1ac2f87c909a581580c.bundle.js:19892:55)
    at _this$_argTypesEnhanc._argTypesEnhancers.reduce.Object.assign.__isArgsStory (http://localhost:51561/vendors~main.e1ac2f87c909a581580c.bundle.js:26627:21)
    at Array.reduce (<anonymous>)
    at StoryStore.addStory (http://localhost:51561/vendors~main.e1ac2f87c909a581580c.bundle.js:26625:59)
    at Object.api.add (http://localhost:51561/vendors~main.e1ac2f87c909a581580c.bundle.js:25088:25)
    at http://localhost:51561/vendors~main.e1ac2f87c909a581580c.bundle.js:44029:16
```

If you delete `component: Greeting` from the second snippet above, the Storybook will load correct and the individual story will also render as expected with the appropriate context argument provided.

**System:**

```
Environment Info:
(node:60922) UnhandledPromiseRejectionWarning: TypeError: (e || []).filter is not a function
    at /Users/albertmartin/.npm/_npx/60917/lib/node_modules/@storybook/cli/node_modules/envinfo/dist/envinfo.js:1:73314
    at async Promise.all (index 6)
(node:60922) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:60922) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Pretty sure that's not the output you're looking for 😬

**Comment by atcha** [comment]
Hello,
I have the same problem. It breaks the story when you put component into metadata :
`TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at http://localhost:6006/vendors~main.f5a0f310e4a580f87d7f.bundle.js:126005:12
    at Array.reduce (<anonymous>)
    at combineParameters (http://localhost:6006/vendors~main.f5a0f310e4a580f87d7f.bundle.js:126004:32)
    at enhanceArgTypes (http://localhost:6006/vendors~main.f5a0f310e4a580f87d7f.bundle.js:107672:55)
    at _this$_argTypesEnhanc._argTypesEnhancers.reduce.Object.assign.__isArgsStory (http://localhost:6006/vendors~main.f5a0f310e4a580f87d7f.bundle.js:126833:21)
    at Array.reduce (<anonymous>)
    at StoryStore.addStory (http://localhost:6006/vendors~main.f5a0f310e4a580f87d7f.bundle.js:126831:59)
    at Object.api.add (http://localhost:6006/vendors~main.f5a0f310e4a580f87d7f.bundle.js:125294:25)
    at http://localhost:6006/vendors~main.f5a0f310e4a580f87d7f.bundle.js:128264:16`

And not puting component into metadata breaking jsdoc etc.
Is there a conflict between auto generated doc and argTypes ?

**Comment by shilman** [comment]
I believe this was fixed in https://github.com/storybookjs/storybook/pull/12012 and released in https://github.com/storybookjs/storybook/releases/tag/v6.0.7. please let me know if there's more to do here!

**Comment by atcha** [comment]
Bug fixed for me but still have no auto docs.

**Comment by shilman** [comment]
@atcha do you have a repro?

**Comment by atcha** [comment]
@shilman An internal one unfortunately.
I will continue to search why and keep you in touch :). 
Thanks btw.

**Comment by atcha** [comment]
Find a solution @shilman. We are working with a specific webpackconfig so i've haded a specific rule for vue-docgen-loader.
