### ISSUE TITLE
upgrade to storybook  6.0 bug

### ISSUE THREAD

**Issue by alonfai** [storybookjs/storybook#11913]
**Describe the bug**
I currently have version 5.3 installed. When using the guide at https://medium.com/storybookjs/storybook-6-migration-guide-200346241bb5,  after running `npx sb upgrade` I receive the following error:

```bash

npm ERR! code ETARGET
npm ERR! notarget No matching version found for @storybook/node-logger@6.0.3.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of '@storybook/cli'
npm ERR! notarget 

```
**Expected behavior**
All packages should be updated to the latest. When inspecting @storybook/node-logger version, it still states the latest release was the RC `  '6.0.0-rc.30'`, and hasn't updated like the rest

**Comment by shilman** [comment]
Try clearing your cache?

```
$ npm info @storybook/node-logger

@storybook/node-logger@6.0.3 | MIT | deps: 5 | versions: 582
...
```
