### ISSUE TITLE
Does Storybook V6 `@storybook/server` supercede standalone implementation for HTML framework + Parcel Bundler?

### ISSUE THREAD

**Issue by basher** [storybookjs/storybook#11927]
Yeah, `@storybook/server` builds on the standalone stuff and supercedes it. We should probably get rid of standalone, right @jonspalmer @tmeasday ?

_Originally posted by @shilman in https://github.com/storybookjs/storybook/issues/10110#issuecomment-607757055_

**Comment by shilman** [comment]
Sounds like standalone still has its own utility, tho unmaintained. And `@storybook/server` is in an experimental release already in 6.0

**Comment by basher** [comment]
Ah, OK.

It still works for me... thankfully... but I'm concerned about the `unmaintained` comment. 😉

**Comment by shilman** [comment]
You know the best way to make sure something's maintained right?! 😉
