### ISSUE TITLE
Injecting global argument using new controls and args addons

### ISSUE THREAD

**Issue by alonfai** [storybookjs/storybook#11926]
I currently migrating existing stories to using the new args syntax instead of knobs (following the manual here https://github.com/storybookjs/storybook/tree/next/addons/controls#how-will-this-replace-addon-knobs). 

I have several knobs I use to define global props that are not bound to the component. 

A good example of it is an `API` URL to where the component fetches remote data from.  The custom component I have uses a prop for a callback to load data inside the component and links with react-select `loadOptions` prop (https://react-select.com/props). 

Now that args is the new form, is there a way to have this custom props be shown in the docs panel and enable the user to modify this global settings without using knobs ?

![Screen Shot 2020-08-12 at 8 03 53 pm](https://user-images.githubusercontent.com/11208491/90003114-f46b3480-dcd6-11ea-9083-b7924bce3b54.png)

**Comment by shilman** [comment]
@alonfai the UI isn't really there yet, but the underlying mechanism is: https://storybook.js.org/docs/react/essentials/toolbars-and-globals

@tmeasday something we should figure out

**Comment by Angelk90** [comment]
@alonfai : may I ask you how do you do a fetch to get the data based on the url and the parameters you pass?

**Comment by alonfai** [comment]
@Angelk90 : I  use an external module with utility functions that internally call the API. In my specific case, it was a custom Auto Complete dropdown component.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if this is still relevant in SB 7.x.
