### ISSUE TITLE
isToolsShown parameter doesn't disable toolbar on initial load when set to false (on mdx Meta tag)

### ISSUE THREAD

**Issue by Gideon28** [storybookjs/storybook#11924]
When updating from Storybook 5.3 to 6, our setting on the introduction page to hide the toolbar doesn't work. Navigating to other documentation pages and returning correctly removes it, but a refresh confirms that this isn't the case on first load.

**To Reproduce**

1. In `preview.js` we have added a parameter with options: isToolsShown: true (so that the toolbar re-appears unless otherwise disabled).
```
import { addParameters } from "@storybook/react";

addParameters({
  ...
  options: {
    ...
    // Toggle toolbar on by default - override per story if unwanted
    isToolshown: true,
  }
});
```
2. Our `intro.story.mdx` sets this parameter to false on the `Meta` tag from addon-docs, i.e.
 ```
import { Meta } from "@storybook/addon-docs/blocks";

<Meta
  title="Documentation/Introduction"
  parameters={{ options: { isToolshown: false } }}
/>
```
3. The introduction page loads initially with the toolbar visible, until navigating around produces the expected behaviour.

**System:**
- React 16.13
- Storybook 6.0.3
- Addon-docs 6.0.3

**Comment by shilman** [comment]
Yay!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.22 containing PR #11938 that references this issue. Upgrade today to try it out!

**Comment by dimitrieh** [comment]
@shilman do you know if this is truly fixed? I still seem to be getting this issue, though subsequent load it is gone? Preview.js features:

```
options: {
    isToolshown: false,
```
