### ISSUE TITLE
withA11y decorator has been removed in V6 - migration docs are a bit vague when explaining how to use accessibility addon

### ISSUE THREAD

**Issue by basher** [storybookjs/storybook#11929]
The [V6 migration docs](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#removed-witha11y-decorator) indicate replacing the decorator with `addParameters({ ... })`.

But where exactly?
- Presumably some global config file?
- I tried in `main.js` which didn't work?
- I don't have `config` or `preview` files - I tried adding them, but to no avail.

## Context

I'm using `@storybook/html` in [standalone mode because I use Parcel to bundle my UI rather than Webpack](https://github.com/storybookjs/storybook/tree/next/examples/standalone-preview).

In V5.3, a simple HTML story would look something like this:
```
import { withA11y } from '@storybook/addon-a11y';

export default {
    title: 'Component Title',
    decorators: [withA11y]
};

export const MyComponent = () => `
<div>
    ...some HTML...
</div>
`;
```

## System:
```
System:
    OS: Windows 10 10.0.18362       
    CPU: (12) x64 Intel(R) Core(TM) 
i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 12.14.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.1 - C:\Program Files 
(x86)\Yarn\bin\yarn.CMD
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 84.0.4147.105
    Edge: Spartan (44.18362.449.0)  
  npmPackages:
    @storybook/addon-a11y: ^6.0.4 => 6.0.4 
    @storybook/addon-docs: ^6.0.4 => 6.0.4 
    @storybook/addon-knobs: ^6.0.4 => 6.0.4 
    @storybook/html: ^6.0.4 => 6.0.4
```

**Comment by shilman** [comment]
Updated the doc. Can you check again?

**Comment by basher** [comment]
Thanks, but still not working. I still get `Initializing...`.

I've tried adding `preview.js` in the each of my 2 storybooks (the preview storybook, and the standalone HTML storybook) -  individually, and both of them at the same time.

And, of course, I've removed the decorator from the story.

**Comment by AleshaOleg** [comment]
Same for me

**Comment by shilman** [comment]
cc @tmeasday @tooppaaa

**Comment by basher** [comment]
I've updated my 2 test repos to demo the problem in Storybook V6 with Parcel V2:

[Storybook HTML standalone](https://github.com/basher/parcel-boilerplate-storybook)
[Storybook preview wrapper](https://github.com/basher/parcel-boilerplate-storybook-preview)

**Comment by marie-maxime** [comment]
If the a11y tab is stuck to "initialize" and no error is displayed, make sure to update this:

In main.js
 change
```js
// .storybook/main.js
module.exports = {
  addons: [
    '@storybook/addon-a11y/register',
  ],
};
```
to
```js
// .storybook/main.js
module.exports = {
  addons: [
    '@storybook/addon-a11y',
  ],
};
```

Remove `/register`.

**Comment by tmeasday** [comment]
@shilman should we add @marie-maxime's note to the migration doc?

**Comment by basher** [comment]
Sorry to say @marie-maxime but it doesn't work for me. 😢 

I've pushed change to my repo.

**Comment by tooppaaa** [comment]
Done some small fixes on a11y-addon on https://github.com/storybookjs/storybook/pull/12003

This might resolve your issues but haven't verified yet. @basher, I saw on your second repo that you used `manual: true` which will be fixed by this. 

@tmeasday If I'm right, the migration for removing `/register` is documented and this should be done for all addons (I'm sure I've read this somewhere 🤔)

**Comment by basher** [comment]
Thanks @tooppaaa - I'll keep my fingers crossed! 😄

**Comment by tooppaaa** [comment]
@basher I did some digging on your repos.

- Running `npm run storybook` **worked**
- Running `npm run storybook:preview` **doesn't worked**

I am not sure what you try to do is supported. Using your own iframe served from a custom page means storybook is not able to apply presets and inject addons code in your preview.

Addon a11y and many others, needs to be present in both applications (manager & preview).
In addition, we're relying on a channel to communicate between these 2 instances, another bit of code needed.

**Comment by basher** [comment]
@tooppaaa I'm using standalone/preview mode because I use Parcel to bundle my CSS/JS, not Webpack - see my original comment.

This works with accessibility addon in Storybook v5.3 but not in v6.

I understand that standalone is no longer supported, and I've had conversations previously with @shilman regarding Storybook server, and whether that would be a better solution to using Parcel bundler.

I've also tried using Storybook composition in v6 instead of standalone/preview to see if that works better... just waiting for a [CORS issue](https://github.com/storybookjs/storybook/issues/11892) to be resolved.

**Comment by tooppaaa** [comment]
We changed how the addon id working to use channel instead. 
Let me know if this works using composition, that will be a good use case ! 
If it's not, we can definetely spend some time to fix this.

**Comment by basher** [comment]
Will do... thanks.

I really want to keep using Storybook, even though my specific use case is _"unusual"_ (i.e. HTML stories + Parcel). 😉

**Comment by basher** [comment]
CORS issue now fixed.
Accessibility addon now works for my "wrapper" Storybook - so maybe this specific issue can be closed?

However...
I've added some details to [this validateDOMNesting bug](https://github.com/storybookjs/storybook/issues/12139) for issues with my Storybook composition + HTML/Parcel stories.

😢

**Comment by tooppaaa** [comment]
Awesome !
Happy to hear that it work in your use cases.

In favor of closing as well to track DOM Nesting in the other issue.
I don't think it's related to addon a11y :)

**Comment by shilman** [comment]
🎉

**Comment by LordRembo** [comment]
I upgraded to 6.0.21 and having the same issue with A11y being stuck ast 'initializing'. 
However, I'm using a 'config.js'-file in combination with a 'addons.js' file and when I drop the '/register', A11y simply doesn't load.
Any ideas on how I could get it to work?

**Comment by shilman** [comment]
@LordRembo your best bet is upgrading to `main.js`

**Comment by LordRembo** [comment]
Alright, thanks. I was just going over the migration doc and stumbled upon info saying config.js was 'soft' deprecated in 5.3 :D
