### ISSUE TITLE
Add support for story-specific styles

### ISSUE THREAD

**Issue by cascornelissen** [storybookjs/storybook#11941]
**Is your feature request related to a problem? Please describe.**
It's impossible to add story-specific styles in Storybook. For example we have some stories where multiple button or badge components are shown side by side and I would like to include some whitespace between these elements but then we have stories with components (or a single component) where this shouldn't happen or there should be more/less.

**Describe the solution you'd like**
The ability to include styles on a per-story basis, maybe through `preview-head.html` or by being able to write a custom wrapping component for the component that sets up the actual content available in the rendered iframe.

**Describe alternatives you've considered**
There was a way to do this in Storybook 5 because the identifier of each story was available in the iframe's HTML but it's no longer included as of Storybook 6. I've also tried working around it by using a custom implementation of some of the component but wasn't able to do anything that's happening inside the iframe.

**Are you able to assist bring the feature to reality?**
If given some guidance on where changes have to be made, yes.

**Additional context**
I'm using `addon-docs` and write all stories in MDX.

**Comment by shilman** [comment]
Can you share the before & after HTML that you're seeing between 5 and 6? If there was an ID there that's missing in 6 we should probably add it back.

**Comment by cascornelissen** [comment]
Nevermind, it must've been the heath. In Storybook 5 the stories were inline and with Storybook 6 they're now inside iframes... I guess I confused the top/page-level iframe with it. I did not make any changes related to that in the configuration IIRC but I can check it out once more.

**Comment by shilman** [comment]
Surprising! If anything I'd expect the opposite (5 in iframes, 6 inline). Which framework are you using?

https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#60-inline-stories

**Comment by cascornelissen** [comment]
That's exactly what I was expecting as well. I'm using React and I just tried it again, removing most of the extra implementations (because of TS and the usage of SCSS) I had to do for Storybook 5 but I'm still running into the problem where stories are now loading in iframes.

I tried setting `docs.inlineStories` to `true` but then I get the following error for all components.

```
Story 'Block.Table' is set to render inline, but no 'prepareForInline' function is implemented in your docs configuration!
```

It's almost as if Storybook doesn't detect that I'm using React somehow but I can't really find documentation on that?

**Comment by shilman** [comment]
Can you share your `addons` setting in `main.js`?

**Comment by cascornelissen** [comment]
Here's the entire `main.js` since I'm using the `register` because I want to have all the files named `story.mdx`.

```es6
const createCompiler = require('@storybook/addon-docs/mdx-compiler-plugin');

module.exports = {
    stories: [
        './docs/*.mdx',
        '../src/js/**/story.mdx'
    ],
    addons: [
        '@storybook/addon-docs/register'
    ],
    typescript: {
        reactDocgen: 'react-docgen-typescript',
    },
    webpackFinal: (config) => {
        config.module.rules.push({
            test: /\.mdx$/,
            use: [{
                loader: require.resolve('babel-loader'),
                options: {
                    plugins: ['@babel/plugin-transform-react-jsx'],
                },
            }, {
                loader: require.resolve('@mdx-js/loader'),
                options: {
                    compilers: [createCompiler({})],
                },
            }]
        }, {
            test: /\.scss$/,
            use: [{
                loader: require.resolve('style-loader')
            }, {
                loader: require.resolve('css-loader'),
                options: {
                    modules: true
                }
            }, {
                loader: require.resolve('sass-loader')
            }]
        });

        return config;
    },
};
```

---

Took another dive myself and I can fix the issue by applying these changes: https://github.com/storybookjs/storybook/issues/11071#issuecomment-657493513

**Comment by cascornelissen** [comment]
Just wanted to make clear that I'm still using the workaround as described in https://github.com/storybookjs/storybook/issues/11071#issuecomment-657493513 as the original issue still appears in 6.0.21.

**Comment by shilman** [comment]
I see. You have a manually-configured docs setup.

You need to set the `docs.inlineStories` parameter to `true`.

**Comment by cascornelissen** [comment]
I run into other problems when setting that parameter to `true`:"

```
Uncaught Error: Story 'Columns' is set to render inline, but no 'prepareForInline' function is implemented in your docs configuration!
```

**Comment by shilman** [comment]
You really should use the preset. It already sets all this up for you. If you want to do it by hand you can define it like this:

```
docs:{
 prepareForInline: (storyFn: StoryFn) => storyFn(),
}

```

**Comment by cascornelissen** [comment]
I would love to just use the preset but last time (a month or 2 ago) I couldn't get it to work correctly for our setup which contains custom values for `docs.container` and `docs.page`, the entire documentation in MDX, uses `jest-image-snapshot` and has to run inside a Docker container both locally and on Bamboo... 

Can't remember what the exact problems were at the time and I don't have enough time at the moment to try and redo the entire setup so I'm ok with closing this issue as I do have a workaround which has been working well for the last few weeks.
