### ISSUE TITLE
Start:storybook with React/Typescript fails on @storybook/core package

### ISSUE THREAD

**Issue by alonfai** [storybookjs/storybook#11942]
Hey,

I'm in process of migrating existing Storybook 5.3 React/TypeScript components in a monorepo project to the latest release. When I start storybook `yarn start:storybook`,  I'm getting the following warnings across most of the source files, unable to resolve the typings across.

```sh
WARNING in ./packages/components/src/Notification/props.ts 1:0-50
"export 'ComponentProps' (reexported as 'Error') was not found in './Error'
 @ ./packages/components/src/Notification/index.ts
 @ ./packages/components/src/index.ts
 @ ./packages/components/src/Page/Page.stories.tsx
 @ ./packages sync ^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.(ts|tsx|js|jsx|mdx))$
 @ ./.storybook/generated-stories-entry.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/storybook-init-framework-entry.js ./node_modules/@storybook/addon-docs/dist/frameworks/common/config.js-generated-other-entry.js ./node_modules/@storybook/addon-docs/dist/frameworks/react/config.js-generated-other-entry.js ./node_modules/@storybook/addon-actions/dist/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-actions/dist/preset/addArgs.js-generated-other-entry.js ./node_modules/@storybook/addon-backgrounds/dist/preset/defaultParameters.js-generated-other-entry.js ./node_modules/@storybook/addon-links/dist/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-a11y/dist/a11yRunner.js-generated-other-entry.js ./node_modules/@storybook/addon-a11y/dist/a11yHighlight.js-generated-other-entry.js ./.storybook/preview.js-generated-config-entry.js ./.storybook/generated-stories-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined
``` 
**To Reproduce**

Following the migration doc (<https://github.com/storybookjs/storybook/blob/next/MIGRATION.md>) and remove existing @storybook/preset-typescript from my node_modules folder. 

The error above occurs across other sources, trying to remove all warnings isn't possible as it covers about 90% of the project. Any help will be appreciated and see if anyone else came across with these type of errors  (believe it's relating to the new typescript built-in settings in the new release)

A snippet of My package.json dependencies are:

```json

  "peerDependencies": {
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-router-dom": "^5.2.0",
    "react-storage-hooks": "^4.0.1",
    "react-use": "^15.3.3"
  },
  "devDependencies": {
    "@babel/core": "^7.11.1",
    "@babel/generator": "^7.11.0",
    "@babel/parser": "^7.11.3",
    "@babel/types": "^7.11.0",
    "@storybook/addon-a11y": "^6.0.3",
    "@storybook/addon-essentials": "^6.0.3",
    "@storybook/addon-jest": "^6.0.3",
    "@storybook/addon-knobs": "^6.0.3",
    "@storybook/addon-links": "^6.0.3",
    "@storybook/addons": "^6.0.3",
    "@storybook/preset-scss": "^1.0.2",
    "@storybook/react": "^6.0.3",
    "@testing-library/jest-dom": "^5.11.2",
    "@testing-library/react": "^10.4.7",
    "@testing-library/react-hooks": "^3.4.1",
    "@testing-library/user-event": "^12.1.1",
    "@typescript-eslint/eslint-plugin": "^3.9.0",
    "@typescript-eslint/parser": "^3.9.0",
    "@welldone-software/why-did-you-render": "^4.3.0",
    "autoprefixer": "^9.8.6",
    "core-js": "^3.0.1",
    "cross-env": "^7.0.2",
    "fork-ts-checker-webpack-plugin": "^5.0.14",
    "husky": "^4.2.5",
    "immer": "^7.0.7",
    "jest": "^26.3.0",
    "jest-environment-jsdom-sixteen": "^1.0.3",
    "jest-styled-components": "^7.0.2",
    "jest-watch-typeahead": "^0.6.0",
    "lerna": "^3.22.1",
    "react": "^16.13.1",
    "react-app-polyfill": "^1.0.6",
    "react-dom": "^16.13.1",
    "ts-loader": "^8.0.2",
    "tsdx": "^0.13.2",
    "tslib": "^2.0.1",
    "typescript": "^3.9.7",
  }
```

Thanks in advance 

### additional info

I believe its a similar issue to  #11931

**Comment by shilman** [comment]
cc @mrmckeb @gaetanmaisse

**Comment by dorianj** [comment]
I'm seeing this as well -- [this branch](https://github.com/amundsen-io/amundsenfrontendlibrary/pull/579) has a React app in `amundsen_application/static` that is giving a bunch of nonsensical Typescript errors.

**Comment by kelvinlouis** [comment]
I am having the same issue. It seems that the dev server complains about exporting types, using the `type` definition, and re-exporting any types (including interfaces) in barrels. It is unbearable to develop with these warnings. It complains on every save, for all barrel files. Is is possible to turn them off? I tried overwriting the TS config, as described in [here](https://storybook.js.org/docs/react/configure/typescript), but without any success.

**Comment by shilman** [comment]
@kelvinlouis why do you have typescript source in your project? we only distribute the compiled `dist` in the NPM package AFAIK

**Comment by kelvinlouis** [comment]
Hey @shilman,

Thanks for reaching out!

After some digging it looks like a babel issue. I stumbled upon [this issue](https://github.com/babel/babel/issues/8361).
I am now explicitly exporting some types using `export type` in my barrel files and the warnings disappeared for those files.
This is promising. I will repeat this for all the other (200 files) and update this ticket.

In the meantime, @alonfai can you check if this resolves your issues regarding the warnings as well?

**Comment by kelvinlouis** [comment]
I can verify that the warnings disappear, after changing all the barrel files to explicitly export types using `export type`.

**Comment by alonfai** [comment]
@kelvinlouis Thanks for the tip. Confirming that the switch to exporting types using `export type` does resolve all warnings also
