### ISSUE TITLE
Keyboard shortcuts on non-english keyboards

### ISSUE THREAD

**Issue by kevinsimper** [storybookjs/storybook#11945]
**Describe the bug**
If you use a non-english keyboards, the keyboard shortcuts does not work, for example "/".

**To Reproduce**
I wrote a blogpost about it as it is a common a11y problem for non-native english programmers. 
https://medium.com/@kevinsimper/why-keyboard-shortcuts-and-accessibility-in-other-keyboard-languages-rarely-works-8638abc15e71

**How to solve**
The reason is that a keycode integer is used instead of a key string to compare what was pressed.

**Comment by Tomastomaslol** [comment]
Hi @kevinsimper!

Thanks for sharing your article! I wasn't aware of this issue so this will help me to build better applications in future! :) 

Would you like to try and solve it? Otherwise, I would be happy to fix this

**Comment by kevinsimper** [comment]
@Tomastomaslol Thank you 👍

Looking at the code I found something in UI, but the README also needs a update:
https://github.com/storybookjs/storybook/blob/next/lib/ui/README.md#keyboard-shortcuts as `src/modules/ui/configs/handle_routing.js` does not exist inside `ui` anymore.

So the keyboard shortcuts are here:
https://github.com/storybookjs/storybook/blob/00628f89134f1d3044baff46dd1c1543a37dca39/lib/api/src/modules/shortcuts.ts#L61

And it looks to be that the bug is looks if shiftKey is pressed down, which it is on non-english keyboards, but the shortcut does not specify it:
https://github.com/storybookjs/storybook/blob/00628f89134f1d3044baff46dd1c1543a37dca39/lib/api/src/lib/shortcut.ts#L33

**Comment by kevinsimper** [comment]
@tmeasday I can see you have worked in the shortcuts for storybook, that is super awesome! 👍 😄 Do you have an idea on how to solve this? What would be the approach?

**Comment by tmeasday** [comment]
Hi @kevinsimper sorry for the slow response I thought I had written something earlier but it seems to have been lost into the matrix..

I haven't worked on this code in quite a while so I would be pretty much figuring out it from first principles too ;) What I do know is the code is pretty contained to the [setting page that sets them](https://github.com/storybookjs/storybook/blob/next/lib/ui/src/settings/shortcuts.tsx) and the ["module" that provides the API](https://github.com/storybookjs/storybook/blob/next/lib/api/src/lib/shortcut.ts)

**Comment by kainbacher** [comment]
+1 for this issue

**Comment by ghengeveld** [comment]
This should have been addressed already in https://github.com/storybookjs/storybook/pull/13319

Looks like a regression to me.
