### ISSUE TITLE
No stories shown following the setup instruction in Storybook 6+

### ISSUE THREAD

**Issue by DoompyGames** [storybookjs/storybook#11966]
**Describe the bug**
No stories are shown after running `npx sb init` and `yarn storybook` in a web/RN monorepo using yarn, following the instructions outlined here: https://storybook.js.org/docs/react/get-started/install

A simple test on having a more generic `main.js` didn't change anything:
```
module.exports = {
  stories: [
    '../src/**/*.stories.mdx',
    '../src/**/*.stories.@(js|jsx|ts|tsx)',
    '../**/*.stories.mdx',
    '../**/*.stories.@(js|jsx|ts|tsx)',
  ],
  addons: ['@storybook/addon-links', '@storybook/addon-essentials'],
}
```

.. with a simple test story in `../storybook/stories/test.stories.jsx`

```
import React from 'react'

export default {
  title: 'Components/Button',
  component: () => <button>Test</button>,
}
```

![image](https://user-images.githubusercontent.com/14872173/90121855-cc261900-dd5c-11ea-9728-9adfee553ba2.png)

**To Reproduce**
1. `npx sb init` 
2. `yarn storybook`
3. Stories are loading endlessly

**System:**
 System:
    OS: macOS 10.15.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
  Browsers:
    Chrome: 84.0.4147.125
    Firefox: 73.0.1
    Safari: 13.1.1
  npmPackages:
    @storybook/addon-actions: ^6.0.5 => 6.0.5
    @storybook/addon-essentials: ^6.0.5 => 6.0.5
    @storybook/addon-links: ^6.0.5 => 6.0.5
    @storybook/react-native: ^5.3.19 => 5.3.19
    @storybook/react-native-server: ^5.3.19 => 5.3.19

**Comment by shilman** [comment]
I'm guessing the problem is here:

```
@storybook/react-native: ^5.3.19 => 5.3.19
@storybook/react-native-server: ^5.3.19 => 5.3.19
```

If you want to use Storybook for RN, that's 5.3 only for now.

**Comment by newdaveespionage** [comment]
@shilman where is this documented? I've come to this issue because I can't find a clear "React Native is unsupported in 6.0" in the widely publicized documentation.

**Comment by shilman** [comment]
Added, does this work for you? 

https://github.com/storybookjs/react-native/pull/93/files

**Comment by artalat** [comment]
If the old story format is used, i.e. `storiesOf`, it seems to work. 

We're using this workaround by creating a compat file for react-native. Seems to work for us for now:

```
// MyStory.native.stories.ts

import ViewMain, { MyStory } from './MyStory.stories';

import { Platform } from 'react-native';
import React from 'react';
import storiesOf from '@bluebase/storybook-addon';

/**
 * This file exists to run storybook-native@v5 stories on storybook@v6,
 * as there is no v6 stories compatibility on react native yet.
 *
 * Once this issue is solved, this file should be deleted.
 *
 * https://github.com/storybookjs/storybook/issues/11966
 */
if (Platform.OS !== 'web') {

	storiesOf(ViewMain.title, module).add(MyStory.storyName, () => (
		<MyStory {...(MyStory.args as any)} />
	));
}

```

**Comment by newdaveespionage** [comment]
> @newdaveespionage Added, does this work for you? 
> 
> https://github.com/storybookjs/react-native/pull/93/files

@shilman thank you so much!
