### ISSUE TITLE
[Fixed] Upgrading to Storybook 6.0.5 from 5.3.19 (using with Vue.js) results in "fn is undefined" in render/storyFn/applyHooks/decorateStory/hookify

### ISSUE THREAD

**Issue by lewishowles** [storybookjs/storybook#11969]
**Describe the bug**
I have just upgraded to Storybook 6.0.5 after seeing the notification in Storybook itself when running my Storybook instance. I was previously using 5.3.19, and we only started looking into Storybook in the last 2 weeks.

Everything was working fine with normal stories, until upgrading, which now produces the error:

![image](https://user-images.githubusercontent.com/1140753/90124446-4f913b80-dd58-11ea-9bac-8f2abd7bc6fb.png)

We are using Storybook with Vue.js. I have installed addons, but removed them for testing and the error still occurs.

Hopefully it's a stupid config error somewhere. If it helps, it was originally installed using vue-cli, and is run using `npm run storybook:serve`, so it could be an incompatibility there.

**To Reproduce**
Run my storybook with the examples below.

**Code snippets**
A minimal reproduction is the following story:

```javascript
import ImageTag from '@/components/basic/image-tag';

export default {
	title: 'basic/image-tag',
	component: ImageTag,
};

export const basicUsage = () => ({
	render() {
		return <ImageTag src="https://images.unsplash.com/photo-1589538673782-16318ea8dc19?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1534&q=80" alt="Soča valley" />;
	},
});

basicUsage.story = {
	name: 'Basic usage',
};
```

A simplified version of ImageTag itself that still shows the error:

```javascript
<template>
	<img :src="src" :alt="alt" class="h-32 w-auto" />
</template>

<script>
export default {
	name: 'image-tag',
	props: {
		/**
		 * The source image path.
		 */
		src: {
			type: String,
			required: true,
		},

		/**
		 * Alternate text for the image tag. This is required for accessibility.
		 */
		alt: {
			type: String,
			required: true,
		},
	},
};
</script>
```

And a reduced main.js that again still shows the error:

```javascript
module.exports = {
	stories: ['../../src/stories/**/*.stories.@(js|mdx)'],
};
```

**System:**
```
Environment Info:

  System:
    OS: macOS 10.15.5
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 14.3.0 - ~/.nvm/versions/node/v14.3.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v14.3.0/bin/npm
  Browsers:
    Chrome: 84.0.4147.125
    Firefox: 79.0
    Safari: 13.1.1
  npmPackages:
    @storybook/addon-a11y: ^6.0.5 => 6.0.5 
    @storybook/addon-actions: ^6.0.5 => 6.0.5 
    @storybook/addon-docs: ^6.0.5 => 6.0.5 
    @storybook/addon-knobs: ^6.0.5 => 6.0.5 
    @storybook/addon-links: ^6.0.5 => 6.0.5 
    @storybook/addon-storysource: ^6.0.5 => 6.0.5 
    @storybook/addon-viewport: ^6.0.5 => 6.0.5 
    @storybook/vue: ^6.0.5 => 6.0.5 
```

**Additional context**
As I say I don't think it's a major issue with the setup, as it's all very basic so far and was working with the previous version, and reducing it further doesn't solve the issue. I followed through the migration guide but most of it doesn't apply as we only started using Storybook in the last few weeks.

**Comment by lewishowles** [comment]
Huh, played with this some more, and it looks like it was caused by `addon-a11y`. Removing these lines from `preview.js`:

```javascript
import { addDecorator } from '@storybook/vue';

import { withA11Y } from '@storybook/addon-a11y';

addDecorator(withA11Y);
```

made it work again - I guess this setup is no longer needed.

**Comment by shilman** [comment]
Yes, `withA11y` is no longer needed: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#removed-witha11y-decorator
