### ISSUE TITLE
React Native is referenced, but related docs are missing

### ISSUE THREAD

**Issue by arvigeus** [storybookjs/storybook#11968]
**Describe the bug**
During `npx sb init` in an expo project, I got the following message:

```
NOTE: installation is not 100% automated.
To quickly run Storybook, replace contents of your app entry with:

   export default from './storybook'; 

 For more in depth setup instructions, see:

https://github.com/storybookjs/storybook/blob/master/app/react-native/docs/manual-setup.md
```

`/app/react-native/docs/manual-setup.md` seems removed from the repo. Found a dead link in [ADDONS_SUPPORT.md](https://github.com/storybookjs/storybook/blob/8ce418ba180cea067c7b7f91ee482a51d9a4eb4f/ADDONS_SUPPORT.md) as well while investigating.

Haven't tried to run it yet.

**Comment by shilman** [comment]
ZOMG!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.6 containing PR #11973 that references this issue. Upgrade today to try it out!

Closing this issue. Please re-open if you think there's still more to do.

**Comment by arvigeus** [comment]
Are the instructions there still relevant? They seem written before version 6. I could be wrong though.

**Comment by shilman** [comment]
@dannyhw might be the best person to answer that. RN is on its own versioning system now and the 5.3 docs should still apply. next week we're going to figure out what a 6.0 release of RN might look like.

**Comment by dannyhw** [comment]
I've tried doing the automatic setup myself and it didn't seem to work. I'm unsure currently exactly what changed, however I've changed the readme here to a manual setup that works until it can be resolved. So yeah at this moment the steps or the cli script are wrong somehow. I'll look into it.
