### ISSUE TITLE
Define `Story` for web-components in typings

### ISSUE THREAD

**Issue by 43081j** [storybookjs/storybook#11974]
We currently define a `Story` in the react types:

https://github.com/storybookjs/storybook/blob/3fe7d96fd8d289f40bd8a38ec836ed95e6afe865/app/react/src/client/preview/types-6-0.ts#L23

But we don't have the equivalent for web components, even though it looks like it should be possible.

Is it as simple as defining the following in the typings?

```ts
export type WebComponentReturnType = TemplateResult|string|Node;
export type Story<Args = DefaultArgs> = BaseStory<Args, WebComponentReturnType> &
  Annotations<Args, WebComponentReturnType>;
```

im happy to PR it if that's right, and if you can let me know where it belongs if so.

**Comment by shilman** [comment]
Parent issue #11845 

You'll also need to define the `Meta` type. If you can add both of those and test cases in the monorepo, we could potentially patch it in as a bugfix, tho it's scheduled as a 6.1 feature.

**Comment by shilman** [comment]
Gadzooks!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.0-alpha.9 containing PR #12395 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
