### ISSUE TITLE
@storybook/addon-docs/blocks has no exported member 'ArgsTable'

### ISSUE THREAD

**Issue by Yardie83** [storybookjs/storybook#11977]
### Bug or support request summary
The import of ArgsTable from @storybook/addon-docs/block shows "@storybook/addon-docs/blocks has no exported member 'ArgsTable'"

The ArgsTable still shows up though. 

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react 6.0.5
- @storybook/addon-essentials 6.0.5
                       - @storybook/addon-docs 6.05

### Screenshots / Screencast / Code Snippets (Optional)
![image](https://user-images.githubusercontent.com/7658916/90142188-6053a880-dd7c-11ea-84a3-06097fe15622.png)

![image](https://user-images.githubusercontent.com/7658916/90142145-53cf5000-dd7c-11ea-9acf-179c3a7fea9b.png)

**Comment by shilman** [comment]
Egads!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.6 containing PR #11987 that references this issue. Upgrade today to try it out!

Closing this issue. Please re-open if you think there's still more to do.
