### ISSUE TITLE
6.0 Background API throws error / warrning when using name 'light'

### ISSUE THREAD

**Issue by blowsie** [storybookjs/storybook#11972]
**Describe the bug**
>vendors~main.5063dee1e50332a36a43.bundle.js:21966 Backgrounds Addon: could not find the default color "light".
      These are the available colors for your story based on your configuration: light , dark

**To Reproduce**
```
addParameters({
  backgrounds: {
    default: 'light',
    values: [
      { name: 'light ', value: '#ffffff'},
      { name: 'dark', value: '#001133' },
    ]
  },
....
```

**Expected behavior**
Working

**Screenshots**
n/a

**Code snippets**
n/a

**System:**

**Additional context**
To fix you can prefix or use other names
```
addParameters({
  backgrounds: {
    default: 'app-light',
    values: [
      { name: 'app-light ', value: '#ffffff'},
      { name: 'app-dark', value: '#001133' },
    ]
  },
...
```

**Comment by shilman** [comment]
Which version? That's the 6.0 API

https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#backgrounds-addon-has-a-new-api

**Comment by blowsie** [comment]
Yes version 6.0, i got this after following migration notes

**Comment by blowsie** [comment]
I had a space on the background name, sorry
