### ISSUE TITLE
Resetting controls reverts optional props to "undefined"

### ISSUE THREAD

**Issue by Glinkis** [storybookjs/storybook#11976]
When selecting an optional value, and then resetting the controls, the value is not removed but instead set to `={undefined}`.

The inital state:
```jsx
<Button label="Button" />
```

After toggling the value in controls:
```jsx
<Button
  disabled={true}
  label="Button"
/>
```

And after resetting the controls:
```jsx
<Button
  disabled={undefined}
  label="Button"
/>
```

My `.stores.tsx` file looks like this:
```tsx
import { Story, Meta } from '@storybook/react/types-6-0'
import React from 'react'
import { Button, Props } from './button'

export default {
  title: 'Button',
  component: Button
} as Meta

export const Template: Story<Props> = args => <Button {...args} />

Template.args = { label: 'Button' }
```

**Comment by shilman** [comment]
Are you talking about the source snippet that is displayed in `addon-docs`?

**Comment by Glinkis** [comment]
Yes exactly. The snippet that displays when toggling "Show/hide code"

**Comment by shilman** [comment]
Good golly!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.0-alpha.4 containing PR #12365 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
