### ISSUE TITLE
Add documentation about how to locally run documentation 😅

### ISSUE THREAD

**Issue by HerrBertling** [storybookjs/storybook#11986]
**Is your feature request related to a problem? Please describe.**

Seeing this nice prompt:

![image](https://user-images.githubusercontent.com/1827373/90153510-5edcad00-dd89-11ea-91a9-4c52a3915084.png)

I figured: Hey, I should add that code snippet for Vue!

Unfortunately, I couldn't get the docs to work locally by running `yarn docs:dev`, although I chose to also bootstrap the documentation when running `yarn bootstrap`. So I could open a PR now with my Vue snippet additions, but that would be without checking locally whether they show up and work within the documentation.

This is the error I get:

```sh
$ yarn docs:dev
yarn run v1.22.4
$ npm --prefix docs run dev
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /Users/herrbertling/Sites/storybook/docs/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/Users/herrbertling/Sites/storybook/docs/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/herrbertling/.npm/_logs/2020-08-13T15_26_09_966Z-debug.log
error Command failed with exit code 254.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I also tried this, but it didn't do anything:

```sh
$ yarn bootstrap:docs
yarn run v1.22.4
$ yarn install --cwd docs
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 3.52s.

```

I couldn't find any contribution guildelines/setup help for running the docs locally, unfortunately. I guess that would be of great help for anyone having the same idea as I had 😊 

**Describe the solution you'd like**

Add documentation about how to run the actual documentation/website locally.

**Describe alternatives you've considered**

Not contributing, pushing something I haven't confirmed is working?

**Are you able to assist bring the feature to reality?**

Since I can't get the docs/website running locally by running what *seems* to be the correct command: Nope 😅

**Comment by shilman** [comment]
cc @tmeasday @kylesuss

**Comment by tmeasday** [comment]
Ohh, yeah. @HerrBertling -- we now run the docs via the frontpage: https://github.com/storybookjs/frontpage#docs-content

I neglected to update the documentation in this repository. Apologies! Will sort it out!

**Comment by shilman** [comment]
Egads!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.7 containing PR #12015 that references this issue. Upgrade today to try it out!

Closing this issue. Please re-open if you think there's still more to do.

**Comment by HerrBertling** [comment]
Thank you :blush:
