### ISSUE TITLE
ArgTypes `defaultValue` displaying as blank in preview.

### ISSUE THREAD

**Issue by SamSverko** [storybookjs/storybook#11983]
**Describe the bug**
Providing a value for the `defaultValue` key in the `ArgType` object results in nothing being displayed on preview.

**To Reproduce**

1. Create a new story with a similar structure as the code snippet below.
2. Build storybook and view the component.

**Expected behavior**
The value of `devaultValue` would appear under the **Default** section of the Controls addon.

**Screenshots**
<img width="826" alt="Screen Shot 2020-08-13 at 10 50 32 AM" src="https://user-images.githubusercontent.com/4431967/90149737-d80cdd80-dd52-11ea-839d-02ff4b1b1062.png">

**Code snippets**
```javascript
import { action } from '@storybook/addon-actions'
import { Button } from '../src/button'

export default {
  title: 'Button',
  component: Button,
  argTypes: {
    type: {
      defaultValue: 'primary', // does not display on preview
      description: 'type description',
      control: {
        type: 'select',
        options: ['primary', 'secondary', 'tertiary'],
      },
    },
    children: {
      defaultValue: 'Button text', // does not display on preview
      description: 'children description',
    },
  },
}

const Template = (args) => <Button onClick={action('onClick')} {...args} />

export const Default = Template.bind({})
Default.args = {
  type: 'primary',
  children: 'Button text',
}
```

**System:**
```
Environment Info:

  System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  Binaries:
    Node: 14.0.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.7 - /usr/local/bin/npm
  Browsers:
    Chrome: 84.0.4147.125
    Firefox: 78.0.2
    Safari: 13.1.2
  npmPackages:
    @storybook/addon-actions: ^6.0.5 => 6.0.5 
    @storybook/addon-essentials: ^6.0.5 => 6.0.5 
    @storybook/addon-knobs: ^6.0.5 => 6.0.5 
    @storybook/addon-links: ^6.0.5 => 6.0.5 
    @storybook/addon-storysource: ^6.0.5 => 6.0.5 
    @storybook/addons: ^6.0.5 => 6.0.5 
    @storybook/react: ^6.0.5 => 6.0.5 
    @storybook/storybook-deployer: ^2.8.6 => 2.8.6 
    @storybook/theming: ^6.0.5 => 6.0.5 
```

**Comment by marie-maxime** [comment]
Not sure if this is a bug, but I had to add a `table` property for it to works on my storybook.

Here's an example:
```js

export default {
  title: 'Button',
  component: Button,
  argTypes: {
    isExpanded: {
      control: "boolean",
      defaultValue: false,
      description: "if true, acoordion is expanded on render",
      table: {
        type: { summary: 'boolean' },
        defaultValue: { summary: false },
      }
    },
  },
}

**Comment by shilman** [comment]
@marie-maxime What you've pasted is correct. However, it should probably also use the `argType.defaultValue` field if `table.defaultValue` is not specified.

**Comment by SamSverko** [comment]
Thank you for the alternative @marie-maxime , I'm using that for now until I figure out what I'm doing wrong. The `summary` does have different styling than description.

I found this helpful [table](https://storybook.js.org/docs/react/writing-docs/doc-blocks#customizing) that details the `argTypes` values. It includes the table portion. I see that `description` is provided, but not `defaultValue`.

<img width="800" alt="Screen Shot 2020-08-13 at 1 02 52 PM" src="https://user-images.githubusercontent.com/4431967/90164368-507c9a00-dd65-11ea-853a-749940fe611e.png">

The `summary` is styled to look like code, or some form of highlighting.

<img width="868" alt="Screen Shot 2020-08-13 at 1 03 02 PM" src="https://user-images.githubusercontent.com/4431967/90164481-72761c80-dd65-11ea-87d6-e942fb3d1d89.png">

**Comment by feerzlay** [comment]
Having the same issue with angular and compodoc when using `ArgsTable` block.

**Comment by anna-tsukanova** [comment]
The same problem. When I'm using 
```js
Component.argTypes = {
  someProp: {
    defaultValue: 'm', // does not display in Controls panel
    description:
      'Some text', // works
  }
}
```

![image](https://user-images.githubusercontent.com/60427427/95087061-e3b0cb00-0729-11eb-8374-895845149e01.png)

**Comment by shilman** [comment]
To affect the "default" column in the ArgsTable, you should set the `argTypes.<field>.table.defaultValue` field. The value should be an object with the keys `summary` and optionally `details`, which are both strings.

For example:

```js
export default {
  component: MyComponent,
  argTypes: {
    argName: {
      table: { defaultValue: { summary: 'SomeType<T>' } },
    },
  },
};
```

For the current state of `argTypes.<field>.defaultValue` see: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#no-longer-inferring-default-values-of-args

**Comment by shilman** [comment]
@dexster I think #12644 is saying that there is a bug for Angular's default value extraction. I think it's an easy fix and then it will show up in both MDX and DocsPage.

**Comment by michaelfaith** [comment]
@shilman I'm still seeing it as an issue in React with MDX, but only for the ArgsTable element in docs view.  On the Canvas view, it shows the default.

Docs
![image](https://user-images.githubusercontent.com/8071845/129104220-cd3673ac-92e1-443a-b44c-d136958edbab.png)

Canvas
![image](https://user-images.githubusercontent.com/8071845/129104357-c665e755-635f-43fa-8af9-d075f9abc178.png)


```
<Meta
  title="Theme/QtmThemeProvider"
  component={QtmThemeProvider}
  argTypes={{
    themeSetting: {
      type: 'QtmThemeSetting',
      description: 'Determines what theme should be applied to the application.',
      options: [
        'dark',
        'light',
        'system',
      ],
      table: {
        defaultValue: { summary: 'light' }
      },
    }
  }}
/>
```

**Comment by shilman** [comment]
@michaelfaith Do you a have a reproduction repo you can share? If not, can you create one? See [how to create a repro](https://storybook.js.org/docs/react/contribute/how-to-reproduce).

**Comment by michaelfaith** [comment]
@shilman  Here's a repo demonstrating the bug  https://github.com/michaelfaith/storybook-mdx-argtype-bug

**Comment by michaelfaith** [comment]
Went ahead and opened a new issue here:  https://github.com/storybookjs/storybook/issues/15838

**Comment by JRRS1982** [comment]
Same issue here, but not on tables, the defaultValue under a prop is not populating the children field...  react mdx. When i manually enter text to the children field in the addons section it populates the canvas with the mapping i.e. a reactNode, but i was / am hoping to have the node declared in the stories.mdx file and have a default mapping applied.

```
  argTypes={{
    linkVariant: {
      options: ['text', 'button'],
      control: { type: 'radio' },
    },
    children: {
      options: ['Default'],
      control: { type: 'text', defaultValue: 'ExampleReactNode'},
      mapping: {
```

**Comment by sai-github** [comment]
For anyone visiting this page, this is now possible with `args` along with `argTypes`
Check this comment https://github.com/storybookjs/storybook/issues/21016#issuecomment-1432746552

**Comment by MichaelJHaywood** [comment]
> For anyone visiting this page, this is now possible with `args` along with `argTypes` Check this comment [#21016 (comment)](https://github.com/storybookjs/storybook/issues/21016#issuecomment-1432746552)

@sai-github Does this solve it? `args` will populate the control but it doesn't populate the `Default` column from what I can tell. 

![image](https://github.com/storybookjs/storybook/assets/103497941/2a8dad35-66b7-4fe5-aaa7-997b947cbc68)

```
  args: {
        gap: 4
    },
    argTypes: {
        gap: {
            description: "Letter type unit distance between left and right sides",
            control: {
              type: "number"
            },
            defaultValue: 4
        }
}
```
