### ISSUE TITLE
Controls Addon for Preact

### ISSUE THREAD

**Issue by wahidshafique** [storybookjs/storybook#11991]
**Is your feature request related to a problem? Please describe.**
I am trying to add Controls functionality, however I get this error, even while following the necessary setup guide

```This story is not configured to handle controls. Learn how to add controls »```

**Describe the solution you'd like**
I know that the feature is still not [supported](https://storybook.js.org/docs/react/api/frameworks-feature-support), but I was not clear on the state of the issue. I would like this to match the same behaviour as React.

**Describe alternatives you've considered**
There are no alternatives since this is strictly a blocker to using Controls.

**Are you able to assist bring the feature to reality?**
no 

**Additional context**
Using `    "@storybook/preact": "^6.0.5",`

**Comment by shilman** [comment]
https://github.com/storybookjs/storybook/blob/next/addons/controls/README.md#my-controls-arent-being-auto-generated-what-should-i-do
