### ISSUE TITLE
Controls: String literal type with "." in it uses "object" control

### ISSUE THREAD

**Issue by ofagbemi** [storybookjs/storybook#12008]
**Describe the bug**
I noticed in my TypeScript + React app, if I specify a string enum with string literals that have dots "." in them, the control appears to default to the "object" control text area. I'm using storybook@6.0.6.

**To Reproduce**

1. Follow the steps in this setup guide: https://gist.github.com/shilman/69c1dd41a466bae137cc88bd2c6ef487
2. Add a prop `test: 'test.thing' | 'other.thing'` to the `ButtonProps` interface defined in Button.tsx.
3. Start storybook and view Button story
4. See that the new "test" control has the object control text area

**Expected behavior**
"test" control should be a select element with "test.thing" and "other.thing" as options

**Comment by shilman** [comment]
This might be an issue in `react-docgen-typescript`? cc @hipster

**Comment by Morteza-Jenabzadeh** [comment]
As I saw the code row.type is wrong but can't figure out which part of the code cause this 
@shilman @hipstersmoothie  any hint that I can contribute to this issue?

**Comment by hipstersmoothie** [comment]
This issue seems to be fixed

<img width="432" alt="Screen Shot 2020-10-23 at 1 50 49 PM" src="https://user-images.githubusercontent.com/1192452/97052929-c5730980-1536-11eb-9924-857300f1c43b.png">
