### ISSUE TITLE
MDX stories have an iframe all around them instead of one per story

### ISSUE THREAD

**Issue by PupoSDC** [storybookjs/storybook#12018]
**Describe the bug**

A normal storybook story is wrapped in an iframe, which is very important for demos showcasing components that have `fixed` positioning. The MDX story only has one iframe wrapping the whole document.

**To Reproduce**

create a component like

```tsx
const Container = styled.div`
  position: fixed;
  top: 0;
`;

const FixedToTheTop = () => (<Container>"Hello World"</Container);
```

and add a story for it 

```tsx
import { Meta, Story, Preview, Props } from '@storybook/addon-docs/blocks';
import FixedToTheTop from './FixedToTheTop';

# Fixed To The Top

- some bla bla bla bla bla 
- more bla bla bla

<Preview>
  <Story name="Fixed To The Top">
    <FixedToTheTop />
  </Story>
</Preview> 
```

The fixed bar will be placed on top of the story instead of being contained in the preview 😢 

**Expected behavior**

`Story` should create a self contained sandbox with an `iframe`.

**Screenshots**

Looks broken in the docs:

<img width="1128" alt="Screenshot 2020-08-14 at 11 40 45" src="https://user-images.githubusercontent.com/9625304/90236428-0ce86580-de23-11ea-9669-23d52f78f51a.png">

Looks ok in the canvas:

<img width="1145" alt="Screenshot 2020-08-14 at 11 40 31" src="https://user-images.githubusercontent.com/9625304/90236429-0e199280-de23-11ea-861f-3396641940e1.png">

**Code snippets**

See "To Reproduce"

**System:**

```
Environment Info:

  System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
  Binaries:
    Node: 14.7.0 - ~/.nvm/versions/node/v14.7.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.7 - ~/.nvm/versions/node/v14.7.0/bin/npm
  Browsers:
    Safari: 13.1.2
  npmPackages:
    @storybook/addon-actions: ^6.0.0 => 6.0.0
    @storybook/addon-essentials: ^6.0.0 => 6.0.0
    @storybook/addon-links: ^6.0.0 => 6.0.0
    @storybook/node-logger: ^6.0.0 => 6.0.0
    @storybook/preset-create-react-app: ^3.1.4 => 3.1.4
    @storybook/react: ^6.0.0 => 6.0.0
```

**Comment by shilman** [comment]
https://storybook.js.org/docs/react/writing-docs/doc-blocks#inline-rendering

**Comment by PupoSDC** [comment]
Great! Thanks!
