### ISSUE TITLE
How to run async logic before stories are loaded in 6.0

### ISSUE THREAD

**Issue by huntjosh** [storybookjs/storybook#12010]
Hi, please let me know if there is a better place for discussion.

We currently run async logic within config.ts prior to migrating to 6.0. Now we are moving to 6.0 and we no longer have access to the configure() function like so:
`asyncSetup().then(() => {
    configure(
        [
            require.context('../components', true, /\.stories\.tsx?$/),
        ],
        module
    );
});`

In 6.0 how can I run an async function before stories are loaded?

Thanks

**Comment by shilman** [comment]
Open discussion in #10009

I don' think this issue is quite a duplicate, but let's have the discussion one place. Thanks for raising!
