### ISSUE TITLE
storysource tab preview is empty

### ISSUE THREAD

**Issue by Toesmash** [storybookjs/storybook#12021]
**Describe the bug**
Storysource addon tab renders with empty preview

**Expected behavior**
Tab contains preview of story source code

**Screenshots**
![image](https://user-images.githubusercontent.com/16369241/90245336-c569d580-de32-11ea-8ab2-b892f45b6b0c.png)

**Code snippets**
basic setup in `main.js`
```javascript
module.exports = {
  addons: ['@storybook/addon-storysource'],
};
```

**System:**
    OS: macOS 10.15.3
    CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
  Binaries:
    Node: 10.16.1 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
  npmPackages:
    @storybook/addon-actions: 6.0.7 => 6.0.7
    @storybook/addon-backgrounds: 6.0.7 => 6.0.7
    @storybook/addon-controls: ^6.0.7 => 6.0.7
    @storybook/addon-docs: 6.0.7 => 6.0.7
    @storybook/addon-info: ^5.3.19 => 5.3.19
    @storybook/addon-knobs: 6.0.7 => 6.0.7
    @storybook/addon-storysource: ^6.0.7 => 6.0.7
    @storybook/addon-viewport: ^6.0.7 => 6.0.7
    @storybook/addons: 6.0.7 => 6.0.7
    @storybook/react: 6.0.7 => 6.0.7
on React 16.13.1

**Comment by shilman** [comment]
Unrelated but you probably want to get rid of this:

```
@storybook/addon-info: ^5.3.19 => 5.3.19
```

**Comment by Toesmash** [comment]
removing the addon-info dependency fixed the issue.

**Comment by shilman** [comment]
Awesome--pleasant surprise! 💯
