### ISSUE TITLE
Custom control type in controls plugin

### ISSUE THREAD

**Issue by alirezamirian** [storybookjs/storybook#12029]
**Is your feature request related to a problem? Please describe.**
Controls plugin could be more useful if it was possible to provide custom ui components to be used as `control.type` for args. 
For example my component may accept a lat,lng coordinate and it would be nice if I could use my custom location picker component. Or I have a color input but I want to have a custom UI which allows picking from my theme.

**Describe the solution you'd like**
in [ArgControl](https://github.com/storybookjs/storybook/blob/next/lib/components/src/blocks/ArgsTable/ArgControl.tsx) component, there is a switch case based on control.type. It can be generalized to allow extension. 

One approach would be to use a map from type to components and allow registering new types in this map via an API exposed by Controls Plugin. Another approach would be to allow `control.type` to be a component in addition to string. and if this is the case, it will be rendered with the same props that other default controls are rendered.

**Describe alternatives you've considered**
I can't think of any alternative which covers this need.

**Are you able to assist bring the feature to reality?**
Yes. I think the second proposed solution is a very low-hanging fruit and I can create a PR for it.

**Comment by shilman** [comment]
Closing as duplicate to #11486
