### ISSUE TITLE
React Sidebar / Drawer

### ISSUE THREAD

**Issue by danschoe** [storybookjs/storybook#12023]
Question for: @storybook/react x.x.x

How can I have BOTH a left and right sidebar/drawer ? With hamburger on left end AND right end in top nav bar which reduces each sidebar to mini-sidebar independently?

**Comment by shilman** [comment]
can you show a picture? i can't understand what you're asking for

**Comment by danschoe** [comment]
I've attached 4 images. One is with both sidebars open, another with both closed, another with only one closed.
It would be great if when they are closed only icons show. Right now I am using material-ui, but I would like to convert this using your storybook ui

<img width="1322" alt="Screen Shot 2020-08-14 at 08 38 49" src="https://user-images.githubusercontent.com/43573595/90250533-2af59c00-de0a-11ea-8333-ee33a9f85021.png">
<img width="1322" alt="Screen Shot 2020-08-14 at 08 38 58" src="https://user-images.githubusercontent.com/43573595/90250559-3943b800-de0a-11ea-8485-09a3c3a8be6c.png">
<img width="1322" alt="Screen Shot 2020-08-14 at 08 39 07" src="https://user-images.githubusercontent.com/43573595/90250570-3d6fd580-de0a-11ea-841c-d966b9d4f5a1.png">

<img width="1322" alt="Screen Shot 2020-08-14 at 08 41 47" src="https://user-images.githubusercontent.com/43573595/90250577-406ac600-de0a-11ea-923e-468fc0db941c.png">

**Comment by shilman** [comment]
what do you want to show in each sidebar?

**Comment by danschoe** [comment]
Essentially menu items - but instead of bringing up a new "page" in the center console, it will modify the chart that is in the center. So I need to pass props from sidebar to center/main component.

<Sidebar_left>
<Main>
<Sidebar_right>

export default App;
 
I'm guessing App.js would look something like this? New to storybook. But it looks great, I would like to use components that have more ability and UX than material-ui.

**Comment by shilman** [comment]
what would be the contents of those sidebars?

**Comment by danschoe** [comment]
Left sidebar:
- Import (data for chart - which creates the chart in the center)
- Chart Type 
  - line (sub-menu item)
  - scatter (sub-menu item)

Right sidebar:
- Modify chart:
  - Add line data (sub-menu item)
  - Delete line data (sub-menu item)
- Timeframe

**Comment by shilman** [comment]
What does any of that have to do with storybook?

**Comment by danschoe** [comment]
I just want to use the components of your open sourced library. I don't know how to have two sidebars, one on the left and one on the right.
