### ISSUE TITLE
[addon-docs]: markdown should be a part of manager and not preview

### ISSUE THREAD

**Issue by wintercounter** [storybookjs/storybook#12031]
**Is your feature request related to a problem? Please describe.**
Our components are using flex-reset which means we reset our CSS from `display: block` to `display: flex` by default. However, including our reset CSS will result in breaking the layout of the rendered markdown. Even if not using such a technique, markdown's style should not be able to affect in any way the rendered previews and vice-versa.

**Describe the solution you'd like**
`<Preview>` component rendering a preview iframe to achieve full isolation. Markdown docs itself would be a part of the manager instead.

**Describe alternatives you've considered**
There are hacks and workarounds but this could be a potential problem for several projects.

**Are you able to assist bring the feature to reality?**
I could after some learning curve, but I want to discuss first in detail.

**Comment by shilman** [comment]
Here is the design doc for why we put everything into the preview. I don't think this is going to change any time soon.

https://docs.google.com/document/d/16u5L5rIrHexLoeyoNpSYr9krgrc0A8Q2WZxiDQk_67A/edit?usp=sharing

**Comment by wintercounter** [comment]
While it has some valid points, imo as adoption of v6 and addon-docs will grow, this problem will come up again and again. How about rendering Preview-in-Preview? The outer preview would not run any decorators, that's going to be isolated for the story only thus giving complete control for the user.

**Comment by shilman** [comment]
You can already do that by rendering stories in iframes instead of inline:

https://storybook.js.org/docs/react/writing-docs/doc-blocks#inline-rendering

**Comment by wintercounter** [comment]
Thank you for bringing my attention to this option, I missed it. However, seems like there is no way to apply this globally. Is that correct?

**Comment by shilman** [comment]
I think you can set the parameter in `.storybook/main.js`:

```
export const parameters = { docs: { inlineStories: false } }
```

**Comment by wintercounter** [comment]
Unfortunately, that's not working. Also, the option is not a solution either. Even if it's not inline, it'll still apply my decorators on the MDX preview also ruining the docs page completely.

**Comment by shilman** [comment]
If you're talking about storybook decorators, they only apply to the stories themselves, not to the `Docs` pane itself.

**Comment by wintercounter** [comment]
Well, yes, but as a reset CSS, it includes a styled-component created with GlobalStyles. Btw, exporting parameters in preview.js works fine, I could set the config option successfully.

**Comment by wintercounter** [comment]
After some tries I found that things here are pretty much inconsistent and weird. I have `inlineStories: false` in my `preview.js`.

If:
- I directly open the docs url, all decorators are applied to the root preview (wrong)
- I navigate to the Docs tab from the Canvas tab or another story, it'll work fine (good)
- Sometimes stories are inline anyway without iframe (don't know how to reproduce it yet 100%)

All in all, there are some weird cases here. Tomorrow I'll try to create a repro for this.

**Comment by shilman** [comment]
Thanks for your patience @wintercounter . If you have a good repro for those things we'll do our best to get them fixed
