### ISSUE TITLE
Add a subtree to the outline view that shows story's child component hierarchy w/ links to stories

### ISSUE THREAD

**Issue by rajington** [storybookjs/storybook#12034]
**Is your feature request related to a problem? Please describe.**
How do we discover related stories to the current story?

**Describe the solution you'd like**
When a story's component is defined, we also analyze the child components and visually show an outline of links to their stories (maybe underneath the existing story in the outline view with a different icon).

**Describe alternatives you've considered**
Manually creating the links or child stories, using storybook links to include links inside the story.

**Are you able to assist bring the feature to reality?**
Maybe? It probably has more to do with the build system than I'm comfortable with without help.

**Comment by shilman** [comment]
Can you give an example?

**Comment by shilman** [comment]
This might be what you want https://medium.com/storybookjs/discover-dependencies-in-storybook-49264d361e21
