### ISSUE TITLE
TypeScript TS2717 error

### ISSUE THREAD

**Issue by endquote** [storybookjs/storybook#12039]
Apologies that this is a little difficult to describe. 

I have a React hook which causes global custom events to be dispatched. I have the global events typed this way:

```ts

export enum Input {
  UP = "UP",
  DOWN = "DOWN",
  LEFT = "LEFT",
  RIGHT = "RIGHT",
}

declare global {
  interface WindowEventMap {
    press: CustomEvent<{ detail: Input }>;
    longpress: CustomEvent<{ detail: Input }>;
    doublepress: CustomEvent<{ detail: Input }>;
  }
}
```

Elsewhere in my project I listen for these events like so:

```ts
const onInput = (e: CustomEvent) => {
    if (e.detail === Input.UP) {
        // stuff
    }
}

window.addEventListener("press", onInput)
```

This all works fine, except for when running the Storybook (6.0.7). I get errors like this:

TS2717: Subsequent property declarations must have the same type.  Property 'doublepress' must be of type 'CustomEvent<{ detail: Input; }>', but here has type 'CustomEvent<{ detail: Input; }>'

This error is confusing since it's saying it should be the thing that it is, but also because I don't get complaints in actual usage.

I suspect the declaration is being parsed each time it's referenced, and is interpreted as some sort of conflict on subsequent times.

**System:**
Please paste the results of `npx sb@next info` here.

```
npx sb@next info                                                                               

Environment Info:
(node:12107) UnhandledPromiseRejectionWarning: TypeError: (e || []).filter is not a function
    at /Users/xxx/.npm/_npx/12107/lib/node_modules/sb/node_modules/envinfo/dist/envinfo.js:1:73314
    at async Promise.all (index 6)
(node:12107) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:12107) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by csantos-nydig** [comment]
This aged bad 😞 

I started to experience the same issue with **TypeScript: 4.9.X**, **Storybook: 6.5.12** and https://tanstack.com/table/v8/docs/api/core/table#meta

It only fails in Storybook.

Any idea how to fix this?

**Comment by raybrownco** [comment]
I ran into this error today after upgrading some packages that reference `@types/react` under the hood. This resulted in 180 type errors along the lines of:

```
node_modules/@types/react/index.d.ts:3432:13 - error TS2717: Subsequent property declarations must have the same type.  Property 'pattern' must be of type 'SVGProps<SVGPatternElement>', but here has type 'SVGProps<SVGPatternElement>'.

3432             pattern: React.SVGProps<SVGPatternElement>;
                 ~~~~~~~

  node_modules/@storybook/types/node_modules/@types/react/index.d.ts:3278:13
    3278             pattern: React.SVGProps<SVGPatternElement>;
                     ~~~~~~~
    'pattern' was also declared here.
```

I used the `yarn list --pattern @types/react` command to figure out which version(s) of `@types/react` were desired by the various packages in my project:

```
yarn list v1.22.19
├─ @storybook/types@7.4.0
│  └─ @types/react@16.14.46
└─ @types/react@18.2.21
```

Okay, so...`@storybook/types` is seeking a much older version of `@types/react` than everyone else.

I was able to fix the issue via the `resolutions` entry in `package.json`:
```json
{
  "resolutions": {
    "@types/react": "18.2.21"
  }
}
```

While this isn't the most ideal solution, it fixes the issue for now and lets me get back to the work I need to be doing.
