### ISSUE TITLE
Ability to not use @storybook/theming or to set "undefined" theme values, in favour of pure CSS styling

### ISSUE THREAD

**Issue by rikkit** [storybookjs/storybook#12030]
**Is your feature request related to a problem? Please describe.**
The project I work on is primarily built with CSS classes and we have little desire to go down the CSS-in-JS route. I am building design system documentation using these classes, but Storybook's theming keeps getting in the way; I want our brand documentation to be "on brand" and that includes things like line-height, font family, font size, etc. 

In an MDX doc I write `<span class="heading">Heading</span>`, which is then partially overridden by the storybook theme:

![image](https://user-images.githubusercontent.com/692840/90273474-ee03c680-de56-11ea-8d75-dfc34f07998b.png)

**Describe the solution you'd like**
I would like the ability to disable theming for certain properties. This configuration is along the right lines - the generated CSS does not have a `font-family` property, which is what I want.

``` 
addParameters({
  docs: {
    theme: {
      ...themes.light,
      fontBase: ""
    }
  },
});
```

![image](https://user-images.githubusercontent.com/692840/90274020-c3fed400-de57-11ea-8bed-1025e8cea739.png)

But unfortunately, theming doesn't support `line-height`, `font-size` etc. so this is not a complete solution.

**Describe alternatives you've considered**
- Convert all my CSS to SASS mixins, and generate CSS with higher specificity than the output of styled components (this is suggested in the "escape hatch" documentation)
- Ignoring brand guidelines for brand documentation

**Are you able to assist bring the feature to reality?**
yes, I can...

**Additional context**
See also #10054 #11230

**Comment by shilman** [comment]
@domyen @ndelangen WDYT?

**Comment by ndelangen** [comment]
> But unfortunately, theming doesn't support line-height, font-size etc. so this is not a complete solution.

This is intentional. In order for storybook development to not grind to a halt OR break user's themes with every release, we've limited the theme-ability on purpose.

The proposed solution in the docs:
> generate CSS with higher specificity than the output of styled components (this is suggested in the "escape hatch" documentation)

Is correct, this makes it clear you're 'hacking' storybook to look the way you want, but we don't promote this unless you know what you're doing and are committed to supporting this yourself.

We know some users do this and want us to do more, but we have to weight this against how much more effort it would cost us to support richer theming when for most users this level of theming is adequate.

**Comment by ndelangen** [comment]
In short: I'm not in favor of making our theming system more complex than it already is.

**Comment by rikkit** [comment]
Sorry if I've touched a sore spot!

I just want to say, that in my eyes, it's strange to view CSS as an "advanced usage" or "hacking" when it's universal, as opposed to Storybook's theming system; CSS is already a theming system. I appreciate your point that you don't want to commit to maintaining that class names remain consistent between releases and that's not what I'm asking for, it's totally normal + expected part of web dev.

What do you think about the ability to turn off `@storybook/theming` completely, at least for docs pages? It could possibly be implemented using [a custom prop forwarding filter](https://emotion.sh/docs/styled#customizing-prop-forwarding) provided somewhere (I think Storybook uses `@emotion/styled`?). My problem at its core is that classes generated by styled-components are more specific that any of my own CSS, so filtering out all properties would help.

The reason that I am reluctant to use the "escape hatch" is really just the amount of duplicated code it would require. I am documenting a design system that is partially implemented with CSS classes so there are a fair few of them around. 

```scss
.style {
  color: red;
}
```

vs

```scss
@mixin style {
  color: red;
}

.style {
  @include style;
}

.sbdocs.style {
  @include style;
}
```

... multiply by the number of classes needed.

**Comment by ndelangen** [comment]
> Sorry if I've touched a sore spot!

You didn't don't worry, all is good! 👍 

I know this is what some users want, I also appreciate you want to make storybook look and feel the way that feels right to you. It's a moving target, and that's what I'm conveying here. You wouldn't expect a user-agent CSS override on facebook.com to keep working indefinitely.. same here, though we will do our outmost best to keep changes to a minimum and keep a change-log to the best of our abilities, and listen to feedback.

You're essentially asking for us to provide an API to toggle all our styles 'off'?

**Comment by rikkit** [comment]
>You didn't don't worry, all is good! 👍

👍 

> You wouldn't expect a user-agent CSS override on facebook.com to keep working indefinitely..

I'm sure there are people out there, but as far as I am concerned if you keep using `h1` for headings, `p` for paragraphs.... the basic semantic web principles we all know and love... then all is good. :)

> You're essentially asking for us to provide an API to toggle all our styles 'off'?

Hmm - ideally it would not be entirely; ideally, I could use my own CSS for "standard" elements like `h1` `p` etc, but Storybook would theme its own components (e.g. `Preview`). I recognise that's where the complication could come in so I would be happy with starting from scratch (for the docs pages - I'm happy with the theming for the Storybook container).

**Comment by domyen** [comment]
Agree with Norbert’s earlier comment. The official theming api is narrow;
we have css escape hatches for additional (custom/rare) use cases. This
balances customizability while allowing the project to move forward.

It seems like this request is a convenience that might save some duplicate
css. The escape hatches should work fine here; you can add extra
specificity in css by nesting, or using “important!”, etc.
