### ISSUE TITLE
DocsPage - Unexpected scroll behavior

### ISSUE THREAD

**Issue by lisamartin00** [storybookjs/storybook#12042]
**Describe the bug**
Clicking on the first story in the navigation scrolls you to the bottom of the first story's wrapper div.  This is particularly noticeable when the story's height exceeds the height of the window.

**To Reproduce**

1. Go to https://storybookjs.netlify.app/official-storybook/?path=/docs/docs-docspage--with-subtitle
2. Note in the left nav, you are on the first item in the "DocsPage" group, "With Subtitle."
3. Note that you are scrolled to the bottom of that story's wrapper div.

**Expected behavior**
You are not scrolled at all when visiting the first story but remain at the top of the view.

**Screenshots**
<img width="1645" alt="Screen Shot 2020-08-14 at 5 18 57 PM" src="https://user-images.githubusercontent.com/6465955/90299161-5603de00-de52-11ea-95fd-ae37f01fdcd7.png">

Thanks!

**Comment by shilman** [comment]
Boo-yah!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.0-alpha.8 containing PR #12047 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
