### ISSUE TITLE
Chromatic PRs invalid build links

### ISSUE THREAD

**Issue by mrlubos** [storybookjs/storybook#12046]
**Describe the bug**
Chromatic PR build links are broken.

**To Reproduce**

1. Go to `https://www.chromatic.com/pullrequest?appId=<appId>&number=<number>`
2. Click on `"Go to build <number>"`
3. See Chromatic tries to access `https://www.chromatic.com/[object%20Object]`

**Expected behavior**
Chromatic displays a correct, working link.

**Screenshots**
<img width="1376" alt="Screenshot 2020-08-15 at 1 53 54 pm" src="https://user-images.githubusercontent.com/12529395/90306353-04655d00-deff-11ea-86c6-c98fa5c56b24.png">

**Code snippets**
–

**System:**
–

**Additional context**
I know this is not a Chromatic repository, sorry! Just not sure where else I can submit this issue.

**Comment by domyen** [comment]
Thanks for reporting @mrlubos, we're tracking this and will fix it ASAP. 🙇‍♂️

**Comment by mrlubos** [comment]
Yay, thanks @domyen!

**Comment by shilman** [comment]
closing this since it's not a storbyook issue 😄

**Comment by mrlubos** [comment]
Thanks @shilman! It got the attention already, so hopefully it will be solved soon. Is there a better way to report issues regarding Chromatic?

**Comment by shilman** [comment]
Best way is through the Chromatic Intercom 👍
