### ISSUE TITLE
Addon-docs: no binding updates on angular

### ISSUE THREAD

**Issue by negue** [storybookjs/storybook#12059]
**Describe the bug**
When you change the control values on the `Docs`-Tab, nothing is changing on the story-component. 

BUT

Those changes are applied on the `Canvas`-Tab. 

**To Reproduce**

1.  Create a fresh angular app with `ng new app-name`
2. `cd app-name`
3. `npx sb init`
4. `npm run storybook`
5.  Select `Button` click on `Docs` at the top
6. Change any of the values like `backgroundColor` or `label`

**Expected behavior**

The changed values in the controls are updated on the `Docs`-Tab's component.

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System:**
Environment Info:

  System:
    OS: macOS 10.15.4
    CPU: (4) x64 Intel(R) Core(TM) i7-5650U CPU @ 2.20GHz
  Binaries:
    Node: 12.13.1 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.12.1 - /usr/local/bin/npm
  npmPackages:
    @storybook/addon-actions: ^6.0.10 => 6.0.10
    @storybook/addon-essentials: ^6.0.10 => 6.0.10
    @storybook/addon-links: ^6.0.10 => 6.0.10
    @storybook/angular: ^6.0.10 => 6.0.10

**Additional context**

Tried it on Vivaldi, Chrome & Firefox, same issue on all browsers.

I didn't find any other opened issues for this.

**Comment by shilman** [comment]
Closing as dupe to #11908
