### ISSUE TITLE
TypeScript 'private name ' error in Stories

### ISSUE THREAD

**Issue by mjcampagna** [storybookjs/storybook#12064]
I'm getting this error in VSCode, on this entire block:
```
Default export of the module has or is using private name 'Props'.ts(4082)
```

The only way I've found to get rid of it is to remove the `component` line from the block.

```js
export default {
	title: 'Atoms/SVGs',
	component: TimesSvg,
	args: {
		color: '#000000',
		size: 12,
	},
	argTypes: {
		color: { control: 'color' },
		size: { control: 'range' },
  },
  decorators: [(Story: any) => (
		<Decorator>
			<Story />
		</Decorator>
	)],
}
```

Anyone have a clue how to resolve this error?

**Comment by AliakbarSu** [comment]
@danielbeutner Thanks. it did the trick. However, make sure you don't export with the same name from different modules or you'll get a different error

**Comment by dani-mp** [comment]
I feel we shouldn't have to explicitly export the props interface just because Storybook is complaining about it. Is there any alternative that doesn't involve modifying production code to make Storybook happy?

**Comment by MarceloPrado** [comment]
Agree with @dani-mp. We shouldn't increase the API surface area for consumers of a component just to pass a TS error. I'm seeing this error in a slightly different format:

```tsx
// MyComponent.tsx
import type { SomeProps } from "./foo"

type PrivateMyComponentProps = {
  bar: "baz"
}

export type MyComponentProps = SomeProps & PrivateMyComponentProps
```

The error: Default export of the module has or is using private name 'PrivateMyComponentProps'.

I don't want to export many types per component, just the "root" one.

**Comment by clearly-outsane** [comment]
Yeha i'm getting this error in the storybook example - Default export of the module has or is using private name 'ButtonProps'.ts(4082)

**Comment by andrewmelnyk** [comment]
I noticed this is closed but I am having this issue in a mono repo with a structure like

packageA
- has its own viteconfig, ts config etc
pacakgeB
- has its own viteconfig, ts config etc

where packageA uses project references to reference packageB
packageB's tsconfig is thus using the composite: true flag, among others, and i get this typescript error 

`Default export of the module has or is using private name 'nameOfFile'.ts(4082)`

i can change it to `export interface` or change the interface to a type and it goes away but it feels like i'm either covering up an issue with storybook, typescript or how i've configured the project 

if i make composite: false it will not throw this error however the typescript build for packageA (which references packageB) will fail saying packageB must have composite: true

hoping someone can help me understand the best way to handle this? 

note: i did not have this issue when i was using next/create react app this only appeared after i had migrated the project away from next/cra and starting using vite so i'm open to the idea that i've configured something incorrectly but considering that other's are having the same issue and this *only* shows up in storybook (and in my project only the first use of the interface keyword in packageB) i am wondering if something fishy is going on with storybook?

**Comment by kmalone-thescore** [comment]
@andrewmelnyk I see the exact same thing in the context of an NX monorepo.

**Comment by iampava** [comment]
I have the exact same problem...

**Comment by iampava** [comment]
Update: refactoring the `interface` to `type` has fixed the problem for me

**Comment by andrewmelnyk** [comment]
@iampava That does work, so does `export interface xxx` but we shouldn't have to do that

**Comment by harperj1029** [comment]
Same issue as everyone else here.

**Comment by vincentywx** [comment]
```
type Props = {
  color: string
  size: number
}
```
change the interface to type works for me, and you don't need to export

**Comment by evertdespiegeleer** [comment]
I got the same error in a slightly different situation:

```tsx
type Story = StoryObj<ComponentProps<typeof Comp>>

export const Default = {
  render: (args) => (
    <Comp {...args}>
      content
    </Comp>
  )
} satisfies Story

```

It had to do with TS attempting to infer the type or `args` in the render function. Explicitly passing it (without exporting the Props interface from the component) fixed it:

```tsx
type Story = StoryObj<ComponentProps<typeof Comp>>

export const Default = {
  render: (args: Story['args']) => (
    <Comp {...args}>
      content
    </Comp>
  )
} satisfies Story
```
