### ISSUE TITLE
Story not detected when using native ESM as vue component with "indirect" export

### ISSUE THREAD

**Issue by jackysee** [storybookjs/storybook#12069]
When using native ESM as vue component and it has some "indirect" export statement, the whole story cannot be detected and listed.

**To Reproduce**
Clone this repo https://github.com/jackysee/sb6-vue-non-sfc 
And `npm run storybook`

**Screenshots**
![image](https://user-images.githubusercontent.com/30516/90357094-5f748c80-e084-11ea-972d-3f3be24520e1.png)

**Code snippets**
The native ESM vue component `hello.js`. 
```
const comp = {
  name: "compA",
  render(h) {
    return h("div", "hello " + this.name);
  },
  props: {
    name: { type: String },
  },
};

const normalize = (i) => i;
const __comp__ = normalize(i);
export default __comp__;
```
Warning message by react:
```
Warning: validateDOMNesting(...): <ul> cannot appear as a descendant of <p>.
    in ul (created by EmptyBlock)
    in p (created by Context.Consumer)
    in Styled(p) (created by EmptyBlock)
    in div (created by Context.Consumer)
    in Styled(div) (created by Spaced)
    in Spaced (created by Context.Consumer)
    in Styled(Spaced) (created by EmptyBlock)
    in div (created by Context.Consumer)
    in Styled(div) (created by Spaced)
    in Spaced (created by Context.Consumer)
    in Styled(Spaced) (created by EmptyBlock)
    in div (created by Context.Consumer)
    in Styled(div) (created by EmptyBlock)
    in EmptyBlock (created by Ref)
    in div (created by Context.Consumer)
    in Styled(div) (created by Ref)
    in Ref (created by Sidebar)
    in div (created by Context.Consumer)
    in Styled(div) (created by Spaced)
    in Spaced (created by Context.Consumer)
    in Styled(Spaced) (created by Sidebar)
    in div (created by OverlayScrollbarsComponent)
    in div (created by OverlayScrollbarsComponent)
    in div (created by OverlayScrollbarsComponent)
    in div (created by OverlayScrollbarsComponent)
    in OverlayScrollbarsComponent
    in Unknown (created by Context.Consumer)
    in Styled(Component) (created by ScrollArea)
    in ScrollArea (created by Context.Consumer)
    in Styled(ScrollArea) (created by Sidebar)
    in nav (created by Context.Consumer)
    in Styled(nav) (created by Sidebar)
    in Sidebar
    in Unknown (created by ManagerConsumer)
    in ManagerConsumer
    in Unknown (created by Layout)
    in div (created by Context.Consumer)
    in Styled(div) (created by Sidebar)
    in Sidebar (created by Layout)
    in Layout (created by Context.Consumer)
    in WithTheme(Layout)
    in Unknown
    in div (created by Context.Consumer)
    in Styled(div)
    in Unknown (created by SizeMeRenderer(Component))
    in SizeMeReferenceWrapper (created by SizeMeRenderer(Component))
    in SizeMeRenderer(Component) (created by SizeMe(Component))
    in SizeMe(Component)
    in ThemeProvider
    in Unknown (created by ManagerConsumer)
    in ManagerConsumer (created by Manager)
    in EffectOnMount (created by Manager)
    in Manager (created by Context.Consumer)
    in Location (created by QueryLocation)
    in QueryLocation (created by Root)
    in LocationProvider (created by Root)
    in HelmetProvider (created by Root)
    in Root
```
**System:**
```
Environment Info:

  System:
    OS: Linux 5.4 Manjaro Linux
    CPU: (2) x64 Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
  Binaries:
    Node: 12.13.0 - /tmp/fnm-shell-4690607/bin/node
    npm: 6.12.0 - /tmp/fnm-shell-4690607/bin/npm
  Browsers:
    Firefox: 79.0
  npmPackages:
    @storybook/addon-actions: ^6.0.10 => 6.0.10 
    @storybook/addon-essentials: ^6.0.10 => 6.0.10 
    @storybook/addon-links: ^6.0.10 => 6.0.10 
    @storybook/vue: ^6.0.10 => 6.0.10 
```

**Additional context**
The native ESM code is generated by rollup. So it's not easy to control how it generate the runtime code.

**Comment by ndelangen** [comment]
I think the react warning is just a warning regarding invalid markup in the sidebar message, saying your storybook is empty. In other words, it's a symptom, not a cause.

I looked at your code, but I don't see any obvious reasons for your storybook to be empty.

If your stories don't match the expected output by storybook, and so they don't register / aren't added. Your storybook stays empty, and thus nothing shows.

First let's ensure your story files picked up by storybook?
Add a debugger or console.log here:
https://github.com/jackysee/sb6-vue-non-sfc/blob/master/src/hello.stories.js#L7
...then check if this is executed, if so your story IS part of the storybook bundle.

Second check the compiled code if the babel-output actually exports your stories, if it doesn't storybook can't find any stories.

**Comment by jackysee** [comment]
Adding a console.log there won't show.

The story will get loaded if the component is written this way:
```
const comp = {
  name: "compA",
  render(h) {
    return h("div", "hello " + this.name);
  },
  props: {
    name: { type: String },
  },
};

// const normalize = (i) => i;
// const __comp__ = normalize(i);
// export default __comp__;

export default comp;
```
But as I said, this coded is generated by rollup so it is not easy to control how they export things.

**Comment by ndelangen** [comment]
> Adding a console.log there won't show.

> The story will get loaded if the component is written this way

The console.log not showing is pretty darn confusing, but the second quote seems to confirm storybook IS finding your story file(s).

I'm puzzled by how a change in a component-file can cause a story file to not register anymore.
Is webpack giving you any errors?

**Comment by jackysee** [comment]
No error in webpack.

**Comment by jackysee** [comment]
There is a warning log above the react one, may be related?

![image](https://user-images.githubusercontent.com/30516/90380664-f0605d80-e0ae-11ea-914f-17a42b59dfb6.png)

**Comment by ndelangen** [comment]
```js
const __comp__ = normalize(i);
```

what's `i` here? it's a reference error
