### ISSUE TITLE
Gatsby Static queries not working in Storybook

### ISSUE THREAD

**Issue by mrseanbaines** [storybookjs/storybook#12061]
**Describe the bug**
I'm getting "Loading (StaticQuery)" in Storybook for any component that uses `StaticQuery` and "The result of this StaticQuery could not be fetched." in Storybook for any component that uses `useStaticQuery`. Everything seems to work fine locally and when built, but in Storybook I am getting these errors.

Minimal reproduction: https://github.com/mrseanbaines/gatsby-storybook-static-query

I also tried making the minimal reproduction even more minimal by removing any use of Prismic and only querying data from the `siteMetadata`, but I'm still getting the same results. Updated _all_ of the packages to the latest versions and also added a version of the stories using the new [CSF format](https://storybook.js.org/docs/react/api/csf) but again, same results. Made a branch with these changes [here](https://github.com/mrseanbaines/gatsby-storybook-static-query/tree/no-prismic).

Also then tried removing usage of TypeScript but still doesn't work: See branch [here](https://github.com/mrseanbaines/gatsby-storybook-static-query/tree/no-typescript).

**To Reproduce**

1. Clone the repo (`git@github.com:mrseanbaines/gatsby-storybook-static-query.git`)
2. Run Storybook (`yarn storybook`)

**Expected behavior**
The components should render

**Screenshots**
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/24367010/90175592-8dfe1900-dd9f-11ea-90eb-474390a9d72d.png">

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/24367010/90175825-ef25ec80-dd9f-11ea-9a14-dca0bb5939a8.png">

**System:**
```sh
  System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
  Binaries:
    Node: 12.17.0 - ~/.nvm/versions/node/v12.17.0/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.17.0/bin/npm
  Browsers:
    Chrome: 84.0.4147.125
    Firefox: 79.0
    Safari: 13.1.2
  npmPackages:
    @storybook/addon-actions: 6.0.10 => 6.0.10
    @storybook/addons: 6.0.10 => 6.0.10
    @storybook/react: 6.0.10 => 6.0.10
```

**Comment by shilman** [comment]
We're most likely getting async data loaders in 6.1 https://github.com/storybookjs/storybook/pull/11012

In the meantime, I'm not sure what the best workaround is. @tmeasday ?

**Comment by domyen** [comment]
We experienced this issue in the storybookjs/frontpage Gatsby project. This comment from @dakebl 👏 helped us resolve it: https://github.com/storybookjs/frontpage/issues/43

**Comment by mrseanbaines** [comment]
Thanks for the response @domyen. I had a look at the issue/comment you pointed to, but it looks like I'm already doing what was suggested (i.e. setting `NODE_ENV` and using `babel-plugin-remove-graphql-queries`). This is all mentioned in the [Gatsby/Storybook setup guide](https://www.gatsbyjs.com/docs/visual-testing-with-storybook/), which is where I copied the config for the reproduction site from.

https://github.com/mrseanbaines/gatsby-storybook-static-query/blob/3e513029ae1c454543aaa39cc7c29cd9975a9a0d/package.json#L6

https://github.com/mrseanbaines/gatsby-storybook-static-query/blob/3e513029ae1c454543aaa39cc7c29cd9975a9a0d/.storybook/main.js#L19

**Comment by tmeasday** [comment]
@shilman I don't think this is a async thing, more likely a Gatsby/SB interop problem. I'm not sure what changed in 6.0 to break this.

@kylesuss I think you recently worked around `useSiteMetadata` in a different way in front page, any insight for us?

**Comment by kylesuss** [comment]
Yeah the fix outlined here no longer works:

https://github.com/storybookjs/frontpage/issues/43

I didn't really solve the underlying issue, but worked around it by overriding a hook that we use to make static queries. I added this to our Storybook's webpack config:

https://github.com/storybookjs/frontpage/blob/b150f80f2f8d84cddf80f7ad108cdb469c388959/.storybook/main.js#L54=L61

Along with this file:

https://github.com/storybookjs/frontpage/blob/b150f80f2f8d84cddf80f7ad108cdb469c388959/.storybook/useSiteMetadata.js

**Comment by papistan** [comment]
@piemasters solution above worked: babel-plugin-remove-graphql-queries@2.9.14 + @storybook/react@6.0.16
