### ISSUE TITLE
typescript controls formatting wrong default props value for type object

### ISSUE THREAD

**Issue by wengsj11** [storybookjs/storybook#12076]
**Describe the bug**
my component props type definition:
![image](https://user-images.githubusercontent.com/25152128/90383571-e6d8f480-e0b2-11ea-9073-ee644ea8cafb.png)

**To Reproduce**
Giving the component a default value.
case 1: 
![image](https://user-images.githubusercontent.com/25152128/90383646-feb07880-e0b2-11ea-8543-3b9890a42efd.png)
![image](https://user-images.githubusercontent.com/25152128/90384066-94e49e80-e0b3-11ea-9ce1-b87f2f4353cf.png)
the default value shown in the controls Input box is wrapped with quotation marks.

case 2: 
![image](https://user-images.githubusercontent.com/25152128/90384409-10465000-e0b4-11ea-920e-d6703af895ce.png)

![image](https://user-images.githubusercontent.com/25152128/90384369-045a8e00-e0b4-11ea-9e23-2b5113105714.png)
In this way, the default value shown in the controls Input box contains character `/n` s

Both of these two are kind of not convenient for user to change the value, and are ineffective to the component.

**Expected behavior**
I tried different ways writing down the object value to make props effective, and the only format  works should be like this:

this won't work:
![image](https://user-images.githubusercontent.com/25152128/90385233-67005980-e0b5-11ea-92fc-07dcf6d96cf1.png)
this one can: (using double quotation marks)
![image](https://user-images.githubusercontent.com/25152128/90385268-77183900-e0b5-11ea-80cd-4fe0a16eb4ab.png)

**System:**
"devDependencies": {
    "@babel/core": "^7.10.5",
    "@storybook/addon-actions": "^6.0.6",
    "@storybook/addon-essentials": "^6.0.6",
    "@storybook/addon-links": "^6.0.6",
    "@storybook/node-logger": "^6.0.6",
    "@storybook/preset-create-react-app": "^3.1.4",
    "@storybook/react": "^6.0.6",
    "babel-loader": "^8.1.0",
    "babel-plugin-import": "^1.13.0",
    "react-is": "^16.13.1"
  }

**Comment by shilman** [comment]
The format of the object control is JSON, hence the double quotation marks. We'll include a more convenient object editor in a future version.

Any idea why it's showing a string by default in the earlier examples and not in the later examples? Seems like it's using the `text` control instead of the `object` control, but based on your example I'm not sure why that would be.

Do you have a repro?

**Comment by wengsj11** [comment]
To Reproduce:
1. Creating a component `Button.tsx` in typescript.
```
import React from 'react';

interface QueryType {
  xs?: number;
  sm?: number;
  md?: number;
  lg?: number;
  xl?: number;
  xxl?: number;
};

type Props = {
  query?: QueryType;
}

const Button = (props: Props) => {
  return <button onClick={() => console.log(props)}>OK</button>
}

Button.defaultProps = {
  query: { xs: 24, md: 12, xl: 8, xxl: 6 }
}

export default Button
```
2. Creating `button.stories.js` file
```
import React from 'react'
import Button from "../components/Button/index";

export default {
  title: 'UI Components/Button',
  component: Button,
};
export const Main = (args) => <Button {...args} />;

Main.story = {
  name: 'example 01',
}
```
3. voilà~!
![image](https://user-images.githubusercontent.com/25152128/90460573-b33fae00-e136-11ea-806d-b4b63d5263d2.png)

**Comment by wengsj11** [comment]
And as you can see, when clicked the button, the console printed the prop as a string format, not sure the reason why.
Any way hope to see the future version sooner.
![image](https://user-images.githubusercontent.com/25152128/90460967-af605b80-e137-11ea-9683-def4095fadc8.png)

**Comment by pixelass** [comment]
I have the same issue with enums (see: https://github.com/storybookjs/storybook/issues/12529#issuecomment-696066753)

So this is not only an issue with objects but in general values getting stringified instead of resolved/computed. 
The defaultProps work everywhere except for storybook.

**Comment by huynhhuutai** [comment]
@pixelass I am facing the same issue with you. You have any solution or workaround for this, @pixelass?

**Comment by pixelass** [comment]
the workaround is to not rely on defaultProps in stories. Instead make sure you manually set the props. (probably not what you want to do but the only solution AFAIK)

**Comment by ZouYouShun** [comment]
same issue here,
![image](https://user-images.githubusercontent.com/5878538/100691175-16421180-33c3-11eb-87b6-d32bd8e7111c.png)

and get args result is
![image](https://user-images.githubusercontent.com/5878538/100691419-a6805680-33c3-11eb-8a20-6f23e6edc2ef.png)

**Comment by davidgape89** [comment]
This issue is also happening with React Components in 6.1.11:
![Screenshot 2021-01-12 at 13 37 01](https://user-images.githubusercontent.com/10955261/104315456-4230d680-54db-11eb-8936-4b1db853a203.png)

It gets stringified when rendered on storybook
![image](https://user-images.githubusercontent.com/10955261/104315499-5674d380-54db-11eb-87cc-53343d851662.png)

Overriding the default props in storybook args seems to be the only workaround for now.

**Comment by pixelass** [comment]
@shilman Is this issue being worked on?
Sadly we'll have to drop Storybook unless this gets fixed

**Comment by shilman** [comment]
@pixelass we did a bunch of work on default value handling in 6.2. can you see if your issue is resolved?

```
npx sb@next upgrade --prerelease
```

**Comment by pixelass** [comment]
@shilman sounds good we'll try and report back next week.
