### ISSUE TITLE
Custom keyboard-shortcut tagName blacklist

### ISSUE THREAD

**Issue by RatherSlowTurtle** [storybookjs/storybook#12074]
**Is your feature request related to a problem? Please describe.**
When using custom elements/web-components (with a closed shadow-dom) that allow user input (e.g. a wrapped text input with a bubbling composed event) the Storybook keyboard navigation is triggering on every keypress.

**Describe the solution you'd like**
This problem seems to be because the Storybook shortcut logic is only checking `event.target.tagName` for `input`s / `textarea`s and isn't aware that these custom elements are input elements.
... So a solution could maybe be to allow customising the `disableShortcuts` config option (or adding a new option) to allow a custom regexp, e.g. `/textarea|input|my-custom-element-prefix-/`.

**Describe alternatives you've considered**
I was also thinking of maybe looking at the first entry of the path instead of `event.target.tagName`, which would work for 'open' shadow modes, but I suspect this will not work if the shadow mode is 'closed', as you won't see that first entry of the path.
As an interim fix in our app, we block events from leaving the PreviewArea if they are of an input type we know about. But it would be nice to have a solution as part of Storybook.

**Are you able to assist bring the feature to reality?**
yes

Thanks for reading and for your hard work on the project :-) ... I'm happy to look into this if you think it's a feature worthwhile adding!

**Comment by tfrijsewijk** [comment]
Hi, this is still an issue -- Can this issue be re-opened?

**Comment by AlansCodeLog** [comment]
Can this please be reopened?

Also one working but ugly workaround is to set `contenteditable=false` on the element since the code just seems to check it's not null:
https://github.com/storybookjs/storybook/blob/a8db9585f07d8cfc7354e68f6b780a6ff6536b38/lib/api/src/modules/shortcuts.ts#L105-L109

**Comment by lennartbuit** [comment]
Stumbled on this too, maybe extend the check to use [`composedPath`](https://developer.mozilla.org/en-US/docs/Web/API/Event/composedPath) instead.

In my example, I have a `my-combobox` element, so `e.target.tagName === "my-combobox"`, but `e.composedPath()` has an actual `input` as first member.

**Comment by nnmax** [comment]
This is still an issue.

**Comment by tfrijsewijk** [comment]
With v7 (?) this has become even worse: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-immutable-options-parameters

I used to disable shortcuts on a per-story base (Web Components with an embedded input), but we can't even do that anymore...
