### ISSUE TITLE
Could not import renderStory from import { renderStory } from '@storybook/react/render';

### ISSUE THREAD

**Issue by tidusia** [storybookjs/storybook#12079]
First of all : 🙏  thanks a lot for this great tool you provide.

**Describe the bug**
I like to use Stories to unit test my components.
In [the docs](https://storybook.js.org/docs/react/workflows/unit-testing), it says that from v6, I can `import { renderStory } from '@storybook/react/render';`

But  actually it seems that there is no @storybook/react/render path to import from.

**To Reproduce**

Basic CRA + TypeScript + Storybook init + try `import { renderStory } from '@storybook/react/render';` from a test file.

**Expected behavior**
The import should work, and I can follow the example given in [the docs](https://storybook.js.org/docs/react/workflows/unit-testing)

**System:**
Please paste the results of `npx sb@next info` here.
This command did not work on my machine.

**Comment by tmeasday** [comment]
Oh, sorry, we didn't end up shipping this in 6.0 as we ran into some complexities. I thought we had removed this from the docs and replaced with a purer snippet. I wonder what happened to that. Will fix.

**Comment by tidusia** [comment]
Thx a lot 🙏 
Now that I can see it, the solution was pretty straightforward 😅
Should I close that?

**Comment by tmeasday** [comment]
> Now that I can see it, the solution was pretty straightforward 😅

Ha! You might think so but what we gloss over there is what happens if you have global decorators that you are relying on for the story's rendering 😅

**Comment by HUYNHHOANGNAM** [comment]
Bạn đang cần gì ở toi

Vào 19:35, Th 4, 19 thg 8, 2020 Tom Coleman <notifications@github.com> đã
viết:
