### ISSUE TITLE
Allow support for custom frameworks by overriding the @storybook/{framework} in iframe-webpack

### ISSUE THREAD

**Issue by ThaNarie** [storybookjs/storybook#12075]
**Is your feature request related to a problem? Please describe.**
I want to create my custom storybook framework (either in my project, or a separate package), but the code inside storybook core server throws errors.

The code below expects the framework to be published within the storybook namespace.
https://github.com/storybookjs/storybook/blob/next/lib/core/src/server/preview/iframe-webpack.config.js#L84-L88

Obviously this is impossible for custom frameworks that other developers are creating. (they can't publish to `@storybook`).

```
ERROR in ./.storybook/storybook-init-framework-entry.js
Module not found: Error: Can't resolve '@storybook/custom-framework-name' in 'project-path/.storybook'
 @ ./.storybook/storybook-init-framework-entry.js 1:0-27
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/storybook-init-framework-entry.js ./node_modules/@storybook/addon-docs/dist/frameworks/common/config.js-generated-other-entry.js ./node_modules/@storybook/addon-links/dist/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-actions/dist/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-actions/dist/preset/addArgs.js-generated-other-entry.js ./node_modules/@storybook/addon-backgrounds/dist/preset/defaultParameters.js-generated-other-entry.js ./.storybook/preview.js-generated-config-entry.js ./.storybook/generated-stories-entry.js ./node_modules/webpack-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined
```

**Describe the solution you'd like**
A way to make this configurable, potentially via the app/server/options.ts

**Describe alternatives you've considered**
I tried adding a webpack resolve alias to the `framework-preset-custom-framework-name.js`, but it seems this webpack config is used for some other build.

**Are you able to assist bring the feature to reality?**
Potentially, I'm trying to patch the node_modules locally to see if I can get this to work, or maybe run into more issues. But seeing that the location of the changes are quite complex (the storybook build process), I might need proper reviews :)

**Additional context**
I talked with @shilman on Discord about this, he suggested to create an issue to see if this can be addressed.

**Comment by ThaNarie** [comment]
So I've managed to get this running locally, and I found a second location that needs a change:
https://github.com/storybookjs/storybook/blob/next/lib/core/src/server/preview/virtualModuleStory.template.js#L1

In both places, I changed the import to `'../custom-framewwork-name/dist/client/index.js'`.

Which could later be changed to `@custom-framework-name/storybook` or something similar once I publish it as my own package on NPM. But for now I started developing it within a folder inside my current project.

---

After that, I checked to see what changes were needed inside storybook to make this configurable from the outside, and came up with the following.

```js
// server/options.ts (in framework app)
var _default = {
  packageJson: packageJson,
  framework: 'custom-framework-name',
  frameworkPath: '../custom-framework-name/dist/client/index.js', // or @custom-framework-name/storybook later - this is optional
  frameworkPresets: [require.resolve('./framework-preset-html.js')]
};
```

```js
// iframe-webpack.config.ts

// grab frameworkPath from the passed options 

const frameworkImportPath = frameworkPath || `@storybook/${framework}`; // fall back to default behaviour

[frameworkInitEntry]: `import '${frameworkImportPath}';`

virtualModuleMapping[storiesFilename] = interpolate(storyTemplate, {
  frameworkImportPath: frameworkImportPath
})
```

```
// virtualModuleStory.template.js
import { configure } from '{{frameworkImportPath}}';
```

If this approach sounds reasonable, I'm happy to follow this up with a PR.

**Comment by shilman** [comment]
That's exactly what i had in mind. PR welcome!

**Comment by shilman** [comment]
Egads!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.13 containing PR #12087 that references this issue. Upgrade today to try it out!

Closing this issue. Please re-open if you think there's still more to do.
