### ISSUE TITLE
Getting started readme of framework/server suggests it can be inited with sb init -t server, but it can't

### ISSUE THREAD

**Issue by ThaNarie** [storybookjs/storybook#12077]
**Describe the bug**
The documentation of the framework/server suggest to run `sb init -t server`.

https://github.com/storybookjs/storybook/tree/master/app/server
`npx -p @storybook/cli sb init -t server`

However, the server framework is currently not available in the sb cli.
https://github.com/storybookjs/storybook/blob/next/lib/cli/src/project_types.ts#L45-L59

**To Reproduce**

1. Open https://github.com/storybookjs/storybook/tree/master/app/server
2. Enter `npx -p @storybook/cli sb init -t server` in terminal
4. See error (`server is not available`)

**Expected behavior**
Either the documentation to show the correct install instructions, or the `cli` to include the `server` framework.

**Additional context**
Mentioned this to @shilman on Discord, he suggested to create an Issue to have look about what to do.

**Comment by shilman** [comment]
¡Ay Caramba!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.3.0-beta.6 containing PR #13979 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```
