### ISSUE TITLE
Storybook 6 performance

### ISSUE THREAD

**Issue by Obiwarn** [storybookjs/storybook#12082]
I just updated to SB 6 (from 5).

Hot code reloading got much slower. 

It hangs some seconds at 70% when building (sth. like: sealing react docgen plugin).

**Comment by shilman** [comment]
Based on my experiments `react-docgen-typescript-plugin` is dramatically faster than `react-docgen-typescript-loader` which it replaced, even with the "hang."

If you want to disable it, you can configure `.storybook/main.js`:

```js
module.exports = {
  typescript: {
    reactDocgen: 'none'
  }
}
```

As for hot code reloading, do you have a repro? We're going to focus on performance in 6.1.

**Comment by Obiwarn** [comment]
I just disabled it. 

Thank you! Back to normal speed.

**Comment by shilman** [comment]
Glad to hear that fixed it. I'm guessing you weren't generating any docgen information 5.3 but since it's the default in 6.0 things slowed down for you.

cc @tmeasday @ndelangen @ghengeveld
