### ISSUE TITLE
Allow for test files to be automatically inferred 

### ISSUE THREAD

**Issue by samturrell** [storybookjs/storybook#12084]
**Is your feature request related to a problem? Please describe.**
I have jest setup to test against my stories, and my directory structure is something like the below:

```
MyComponent.vue
MyComponent.spec.js
MyComponent.stories.js
```

To integrate `addon-jest` in my stories I have to add the following lines (or similar) to each story file in my application:

```
parameters: {
    jest: ['MyComponent'],
},
```

This seems a bit redundant when the name can be inferred from the name of the story file itself. I imagine this is a similar setup for a lot of people.

**Describe the solution you'd like**
Either an extra option on the initial addon setup to inherit the name from the story file, or allow the `jest` parameter to accept a function which can return the story name based on the current data available.

**Option A:**

```
export const parameters = {
    jest: {
        inheritFile: true,
    },
];
```

**Option B:**

```
export const parameters = {
    jest(parameters) {
        return parameters.fileName.replace(/.+\/(.*)\.stories\.js/, '$1');
    },
];
```

**Option C:**

This option probably isn't explicit enough, but possibly if the `jest` parameter is not set we just inherit it from the story by default. But hey, zero-config? 🤷‍♂️ 

**Describe alternatives you've considered**
Attempted to mutate parameters in another decorator, but they seem to be immutable.

**Are you able to assist bring the feature to reality?**
Possibly!

I have modified the addon code locally to ensure this change is possible. In `index.js` I have added an additional line to fallback to the inferred value:

```
    var testFiles = parameters.jest;

    testFiles = testFiles || _args$.parameters.fileName.replace(/.+\/(.*)\.stories\.js/, '$1');
```

**Additional context**
N/A

**Comment by shilman** [comment]
Yowza!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.0-alpha.11 containing PR #13535 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
