### ISSUE TITLE
preview-head.html not used in docs page iframe in Storybook 6

### ISSUE THREAD

**Issue by mattschloss** [storybookjs/storybook#12090]
**Is your feature request related to a problem? Please describe.**
In Storybook 5, we were able to use preview-head.html to define custom styles on the docs page. This was needed to fix a conflict for the background-color of code previews.

**Describe the solution you'd like**
Provide a way to inject custom styles into the docs page iframe.

**Describe alternatives you've considered**
Setting docs theme to light or dark doesn't change the code preview styles. The current alternative is to add a class to our application/library's css.

**Are you able to assist bring the feature to reality?**
no

**Additional context**

**Comment by shilman** [comment]
@mattschloss I think this is a bug. What version are you upgrading from?

**Comment by mattschloss** [comment]
I upgraded from version 5.3.19

**Comment by parash-namespace** [comment]
preview-body seems to work rather than preview-head with version 6.0.26. preview-body fixed it for me.

**Comment by worc** [comment]
is this change documented anywhere (besides this thread)?

**Comment by aaronjones1** [comment]
I was not able to get Google Material Symbols to load in Storybook `v6.5.4` by creating `preview-head.html` in the `.storybook`  folder and linking:
```html
<!-- .storybook/preview-head.html -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
```

I'm using Angular `v13.3.6`.

### Workaround
I _was_ able to get them to load by adding the `<link>` to `preview-body.html` (as mentioned above by @parash-namespace) but the [documentation](https://storybook.js.org/docs/angular/configure/story-rendering) says `preview-head.html` is an option.

**Comment by sidevesh** [comment]
Same here, preview-head.html does not work but preview-body.html does.
