### ISSUE TITLE
After the update from 5.3.19 to 6.0.12, @storybook/addon-storysource doesn't work anymore

### ISSUE THREAD

**Issue by prma85** [storybookjs/storybook#12097]
**Describe the bug**
Related to https://github.com/storybookjs/storybook/issues/12096

I have 2 custom addons that after the update from 5.3.19 to 6.0.12, custom addons don't work anymore when using the .storybook folder. It still works if I am using the addons.js file, but not when using the .storybook/main.js.

So, I decided to keep the use of the `config.js` and the `addons.js` for now until it is resolved. However, I am getting an error when trying to use the `@storybook/addon-storysource`. I didn't see anything in the documentation about a different form of usage or different instructions. Everything (system and addons) are updated to 6.0.12.

The panel is loaded, but it just shows an empty panel instead of the source code.

**To Reproduce**

1. Add storybook to a typescript project (not CRA, using Lerna)
2. Add the `@storybook/addon-storysource/register` to your `addons.js`
3. Have the `config.js` pointing to the stories
4. Run storybook with `-c .`

**Expected behavior**
We would be able to see the source code

**Screenshots**
![image](https://user-images.githubusercontent.com/1236101/90457763-b8aae300-e0b9-11ea-884a-3d697748b4b3.png)

**Code snippets**
```js
// addons.js
import "@storybook/addon-storysource/register";
import "@storybook/addon-actions/register";
import "@storybook/addon-links/register";
import "@storybook/addon-viewport/register";
```

**System:**
OS: Windows 10 10.0.18362
CPU: (8) x64 Intel(R) Core(TM) i7-4810MQ CPU @ 2.80GHz
Binaries:
Node: 12.4.0 - C:\Program Files\nodejs\node.EXE
Yarn: 1.22.4 - C:\Program Files\nodejs\yarn.CMD
npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
Browsers:
Chrome: 84.0.4147.105
Edge: Spartan (44.18362.449.0)

**Additional context**

**Comment by prma85** [comment]
FYI, it will work normally when using the `.storybook/main.js` but to use `./addons.js` it requires the webpack configuration using the `"@storybook/source-loader"`

**Comment by shilman** [comment]
Regarding local addons, did you see this change: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#consistent-local-addon-paths-in-mainjs

**Comment by shilman** [comment]
Regarding storysource, possibly related https://github.com/storybookjs/storybook/issues/11994

**Comment by prma85** [comment]
Hey @shilman thanks for your reply

> Regarding local addons, did you see this change: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#consistent-local-addon-paths-in-mainjs

I talked about it on this reply https://github.com/storybookjs/storybook/issues/12096#issuecomment-675580504

> Regarding storysource, possibly related #11994

I don't think it is related because I am not using the stories in this format. I am using `@storybook/react`

An example is the following: `message.stories.tsx`

```tsx
import { Button, message } from "antd";
import { storiesOf } from "@storybook/react";
import React from "react";

import Center from "../../../util/center";

storiesOf("Antd|Feedback/Message", module)
  .addParameters({
    docs: {
      docs: "https://ant.design/components/message/",
      readme: "https://raw.githubusercontent.com/ant-design/ant-design/master/components/message/index.en-US.md",
    },
  })
  .addDecorator(story => <Center>{story()}</Center>)
  .add("Info message", () => <Button onClick={() => message.info("This is an info message.")}>Info Message</Button>)
```

So, there are 2 problems here:
1. The story source doesn't work when using the `addons.js`
2. When using `main.js` it works but it always shows the same source, doesn't matter that you are changing stories.

**Comment by shilman** [comment]
We've deprecated `addons.js` and you should migrate to `main.js`.

Second problem seems to be a bug introduced in `source-loader`. I'd recommend upgrading to [CSF](https://storybook.js.org/docs/react/api/csf) which is the recommended story format and better supported. There are codemods to do this mostly automatically. I'd also happily merge a PR that fixes this for `storiesOf`.

**Comment by prma85** [comment]
I see. I will take a deeper look to see if I can get the storiesOf working again (trying to change different webpack configurations for the loader or even the loader itself). If I use `jsx` it looks ok (just did a `find` with a `git mv`) but the same is not true for `tsx` format.
