### ISSUE TITLE
After the update from 5.3.19 to 6.0.12, custom addons don't work anymore

### ISSUE THREAD

**Issue by prma85** [storybookjs/storybook#12096]
**Describe the bug**
I have 2 custom addons that after the update from 5.3.19 to 6.0.12, custom addons don't work anymore when using the `.storybook` folder. It still works if I am using the `addons.js` file, but not when using the `.storybook/main.js`.

I could keep using the `addons.js`, however, when doing it, the `@storybook/addon-storysource/register` stops to work.

At this moment, I am in the middle, one side I have my custom addon working but bot the story source, on the other hand, I have the story source working, but not my custom addon.

Maybe it is missing something in the migration docs (I already read the new API docs and I didn't find anything that could help).

**To Reproduce**

1. Create a custom addon (.storybook/docs.jsx)simple as:

```tsx
import React from "react";
import { STORY_RENDERED } from "@storybook/core-events";
import { AddonPanel, Placeholder, DocumentWrapper } from "@storybook/components";
import Markdown from "react-markdown";
import { addons, types } from '@storybook/addons';

const ADDON_ID = "CUSTOM_DOCUMENTATION";
const PARAM_KEY = "docs";
const PANEL_ID = `${ADDON_ID}/panel`;
const TITLE = "Docs";

class DocsPanel extends React.Component {
  componentDidMount() {
    this.props.api.on(STORY_RENDERED, this.onStoryChange);
  }

  componentWillUnmount() {
    this.props.api.off(STORY_RENDERED, this.onStoryChange);
  }
  onStoryChange = async (id) => {
    const params = this.props.api.getParameters(id, PARAM_KEY);

    if (!params || params.disable) {
      this.setState(DEFAULT_STATE);
      return;
    }

    this.setState({
      docs: params.docs,
    });
  };

  render() {
    return (
      <div>
        <iframe src={this.state.docs} />
      </div>
    )
  }
}

addons.register(ADDON_ID, api => {
  addons.add(PANEL_ID, {
    title: TITLE,
    type: types.PANEL,
    render: ({ active, key }) => (
      <AddonPanel active={active} key={key}>
        <DocsPanel api={api} active={active} />
      </AddonPanel>
    )
  });
})
```
2. Try to import it into `.storybook/main.js`.
3. You will get an error:

```bash
ERR! import React from "react";
ERR!        ^^^^^
ERR!
ERR! SyntaxError: Unexpected identifier
ERR!     at Module._compile (internal/modules/cjs/loader.js:718:23)
ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
ERR!     at Module.load (internal/modules/cjs/loader.js:641:32)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:556:12)
ERR!     at Module.require (internal/modules/cjs/loader.js:681:19)
ERR!     at require (internal/modules/cjs/helpers.js:16:16)
ERR!     at interopRequireDefault (C:\Users\Paulo.Andrade\Documents\GitHub\frontend-packages\node_modules\@storybook\core\dist\server\presets.js:149:16)
ERR!     at getContent (C:\Users\Paulo.Andrade\Documents\GitHub\frontend-packages\node_modules\@storybook\core\dist\server\presets.js:165:10)
ERR!     at loadPreset (C:\Users\Paulo.Andrade\Documents\GitHub\frontend-packages\node_modules\@storybook\core\dist\server\presets.js:172:20)
ERR!     at C:\Users\Paulo.Andrade\Documents\GitHub\frontend-packages\node_modules\@storybook\core\dist\server\presets.js:224:18   
ERR!     at Array.reduce (<anonymous>)
ERR!     at loadPresets (C:\Users\Paulo.Andrade\Documents\GitHub\frontend-packages\node_modules\@storybook\core\dist\server\presets.js:223:18)
ERR!     at loadPreset (C:\Users\Paulo.Andrade\Documents\GitHub\frontend-packages\node_modules\@storybook\core\dist\server\presets.js:193:81)
ERR!     at C:\Users\Paulo.Andrade\Documents\GitHub\frontend-packages\node_modules\@storybook\core\dist\server\presets.js:224:18   
ERR!     at Array.reduce (<anonymous>)
ERR!     at loadPresets (C:\Users\Paulo.Andrade\Documents\GitHub\frontend-packages\node_modules\@storybook\core\dist\server\presets.js:223:18) {
ERR!   stack: 'C:\\Users\\Paulo.Andrade\\Documents\\GitHub\\frontend-packages\\packages\\utilities\\storybook\\addons\\docs.js:1\n' +
ERR!     'import React from "react";\n       ^^^^^\n\nSyntaxError: Unexpected ' +
ERR!     'identifier\n    at Module._compile ' +
ERR!     '(internal/modules/cjs/loader.js:718:23)\n    at ' +
ERR!     'Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)\n   ' +
ERR!     ' at Module.load (internal/modules/cjs/loader.js:641:32)\n    at ' +
ERR!     'Function.Module._load (internal/modules/cjs/loader.js:556:12)\n    at ' +
ERR!     'Module.require (internal/modules/cjs/loader.js:681:19)\n    at require ' +
ERR!     '(internal/modules/cjs/helpers.js:16:16)\n    at interopRequireDefault ' +
ERR!     '(C:\\Users\\Paulo.Andrade\\Documents\\GitHub\\frontend-packages\\node_modules\\@storybook\\core\\dist\\server\\presets.js:149:16)\n' +
```

**Expected behavior**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System:**
  System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i7-4810MQ CPU @ 2.80GHz
  Binaries:
    Node: 12.4.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files\nodejs\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 84.0.4147.105
    Edge: Spartan (44.18362.449.0)

**Additional context**

**Comment by shilman** [comment]
Did you see this change: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#consistent-local-addon-paths-in-mainjs

**Comment by prma85** [comment]
Hey @shilman thanks for your reply

> Did you see this change: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#consistent-local-addon-paths-in-mainjs

I saw these changes but it doesn't look related. It can find the file but it complains about the imports. I even tried the example that has on the addons API page (simple and doing nothing) and it complains about the same, the `import`.

My guess here is that when using local addons with `addons.js` it is converted to commonjs using webpack but when using it from `main.js` it already expects commonjs modules and gives an error when using the ES module syntax. The error is for the `import` itself. 

```bash
ERR! import React from "react";
ERR!        ^^^^^
ERR!
ERR! SyntaxError: Unexpected identifier
```

also tried `import * as React from "react" and I had the same issue.

**Comment by shilman** [comment]
Re-read your original post. Here's how to use a local addon defined in `.storybook/my-addon` from `.storybook/main.js`:

```js
module.exports = {
  addons: ['./my-addon'],
}
```

Is that what you're doing?

**Comment by prma85** [comment]
Yes

```js

module.exports = {
  "stories": [
    "../stories/**/*.stories.mdx",
    "../stories/**/*.stories.@(js|jsx|ts|tsx)"
  ],
  "addons": [
    "@storybook/addon-links",
    "@storybook/addon-storysource",
    '@storybook/addon-viewport',
    '@storybook/addon-actions',
    '@storybook/addon-actions',
    '../addons/docs',
    '../addons/iframe',
  ]
}
```

**Comment by prma85** [comment]
I also tried the simple add from https://storybook.js.org/docs/react/api/addons-api

```js
import React from 'react';
import { addons, types } from '@storybook/addons';
import { AddonPanel } from '@storybook/components';

const ADDON_ID = 'myaddon';
const PANEL_ID = `${ADDON_ID}/panel`;

// give a unique name for the panel
const MyPanel = () => <div>MyAddon</div>;
addons.register(ADDON_ID, (api) => {
  addons.add(PANEL_ID, {
    type: types.PANEL,
    title: 'My Addon',
    render: ({ active, key }) => (
      <AddonPanel active={active} key={key}>
        <MyPanel />
      </AddonPanel>
    ),
  });
});
```

And I get the same error when trying to run the storybook

```bash
ERR! import React from "react";
ERR!        ^^^^^
ERR!
ERR! SyntaxError: Unexpected identifier
```

**Comment by ndelangen** [comment]
Seems like the babel-loader isn't activated for the files in that location.

You'd need to ensure those custom addons's files are passed through babel.

If your custom addons are within the storybook config folder, we should be passing them through babel-loader. Might be a bug.
We have a test for this: `/examples/cra-ts-kitchen-sink/.storybook/localAddon`, but in a monorepo babel configs can easily get super confusing.

Would you be able to supply a reproduction repo, so I can test this?

**Comment by prma85** [comment]
I was able to get it working with storybook 6.0.22
Thanks everyone ;) 🎉
