### ISSUE TITLE
`entries` field + `addDecorators` not working together

### ISSUE THREAD

**Issue by wintercounter** [storybookjs/storybook#12100]
If I switch to `main.js` + `stories` from `configure`, the deprecated `addDecorator` API will stop work. Only works with the new `export const decorators` method. It's also true vice-versa. If I add decorators the new way then those decorators are not applied when I use `configure`. It was driving me mad for a few hours during migration :)

**Comment by shilman** [comment]
Ok @wintercounter sorry for the misunderstanding in the other issue. We'll get to the bottom of it!

**Comment by tmeasday** [comment]
@wintercounter do you have a reproduction of this?

**Comment by wintercounter** [comment]
https://github.com/wintercounter/repro-strorybook-entries-vs-adddecorators

What I did is:

- `create-react-app`
- `sb init`
- `addDecorator` in `preview.js`

The `console.log` I added will simply not work.

**Comment by wintercounter** [comment]
After some poking around, seems like the issue is with mdx. The decorator for the `Introduction.mdx` is not running, for the others it does.

**Comment by shilman** [comment]
@wintercounter decorators only run on stories. `Introduction.stories.mdx` is just documentation. If there was a `<Story>...</Story>` in the file, it would run on that. If you want to wrap MDX, there's a different mechanism:

https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/recipes.md#overwriting-docs-container

**Comment by wintercounter** [comment]
Ah yes, you're right. Anyway, I've done a test run with our Storybooks, seems like they still suffer from this issue, but idk how to reproduce it separately. It's a huge codebase with complex config. I close the issue now, hopefully no one else will have such problem :D
