### ISSUE TITLE
Stories don't work with a base tag

### ISSUE THREAD

**Issue by roman-16** [storybookjs/storybook#12106]
**Describe the bug**
I use a base tag which points to a different url in my story. When i do this the preview won't load and I get an error message in my console.

**To Reproduce**

1. Create a story with a [base tag](https://www.w3schools.com/TAGs/tag_base.asp) which points to a different url.
2. Open the story in storybook

**Expected behavior**
No error is thrown and the story loads like in version 5.

**Screenshots**
<img width="1405" alt="image" src="https://user-images.githubusercontent.com/15262665/90506929-530c3480-e155-11ea-8dcf-a2c350f930e0.png">

**System:**
```
Environment Info:

  System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
  Binaries:
    Node: 10.21.0 - /usr/local/bin/node
    Yarn: 1.22.4 - ~/Documents/bt-widgets/node_modules/.bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 84.0.4147.125
    Firefox: 79.0
    Safari: 13.1.2
  npmPackages:
    @storybook/addon-knobs: ^6.0.12 => 6.0.12 
    @storybook/addon-viewport: ^6.0.12 => 6.0.12 
    @storybook/addons: ^6.0.12 => 6.0.12 
    @storybook/cli: ^6.0.12 => 6.0.12 
    @storybook/react: ^6.0.12 => 6.0.12
```

**Comment by shilman** [comment]
@ndelangen any idea about this?

**Comment by ndelangen** [comment]
Ive never seen a base tag with an external url in it. Is that really a thing? Seems like it breaks the browser..

**Comment by wa4-fearless-otter** [comment]
@ndelangen Yeah, we use it to develop for legacy systems. It's rather complicated but needed.

**Comment by ndelangen** [comment]
Might be this line:
https://github.com/storybookjs/storybook/blob/1d62de0d6a1abc84b80370a33914297da82382f3/lib/core/src/client/preview/url.ts#L30
