### ISSUE TITLE
How to remove preview body padding in SB 6.0?

### ISSUE THREAD

**Issue by Obiwarn** [storybookjs/storybook#12109]
This does not work (fixed element.style seems to be "padding: 1 rem"):

````
<!--  .storybook/preview-body.html -->
<style>
    body {
        padding: 0;
        background-color: #005cc5;
    }
</style>
````

Any ideas?

**Comment by shilman** [comment]
try  the `layout: 'fullscreen'` story parameter

**Comment by coconewty** [comment]
Same issue here, setting isFullscreen: true as per https://storybook.js.org/docs/react/configure/features-and-behavior doesn't fix it.

Must admit I haven't dug far but SB is adding style="margin: 0px; padding: 1rem; display: block; justify-content: initial; align-items: initial; min-height: initial;" to body for some reason.

**Comment by shilman** [comment]
@coconewty `isFullscreen: true` isn't the same thing as `layout: 'fullscreen'`. in `.storybook/preview.js`:

```js
export const parameters = { layout: 'fullscreen' }
```

**Comment by Obiwarn** [comment]
Works great. Thank you.

**Comment by coconewty** [comment]
Thanks @shilman I missed this.

FYI of anyone else hunting for this, it's here... https://storybook.js.org/docs/react/configure/story-layout

**Comment by shincurry** [comment]
can i set `<Meta parameters={{ layout: 'fullscreen' }} />` in specific one MDX doc?

**Comment by webunderconstruction** [comment]
> Thanks @shilman I missed this.
> 
> FYI of anyone else hunting for this, it's here... https://storybook.js.org/docs/react/configure/story-layout

Adding some google search keywords;

How to remove default canvas margin in Storybook v6

**Comment by mnlfischer** [comment]
is it possible to disable it for only specific stories and not global?

**Comment by samwyma** [comment]
Yeah, second that ^^. Our use case is having a few stories which are full app pages (where padding screws up things like screen positioned elements) where we would like to disable padding, but also having component stories (e.g. buttons) where padding makes the viewing of those components nicer

**Comment by mnlfischer** [comment]
one solution are [decorators](https://storybook.js.org/docs/react/writing-stories/decorators) but it is annoying set the layout to fullscreen and use decorators on 300 components only for a few pages that needs a fullscreen.

**Comment by benjaminbaldoni** [comment]
@mnlfischer you can achieve that by using the `parameters` attribute on each individual story:

```
export const Primary = Template.bind({})

Primary.args = {
  primary: true,
  label: 'Button',
}

Primary.parameters = {
  layout: 'fullscreen',
}
```

**Comment by mnlfischer** [comment]
> @mnlfischer you can achieve that by using the `parameters` attribute on each individual story:
> 
> ```
> export const Primary = Template.bind({})
> 
> Primary.args = {
>   primary: true,
>   label: 'Button',
> }
> 
> Primary.parameters = {
>   layout: 'fullscreen',
> }
> ```

misses that in the docs. thanks!

**Comment by iamandrewluca** [comment]
So to generalise

**Affects globally** `.storybook/preview.ts`

```ts
import type { Parameters } from '@storybook/react';

export const parameters: Parameters = {
  layout: 'fullscreen'
};
```

**Affects all stories in a file** `*.stories.tsx`

```ts
import { Meta } from '@storybook/react';

export default {
  title: 'Stories Name',
  parameters: {
    layout: 'fullscreen',
  },
} as Meta;
```

**Affects single story in a file** `*.stories.tsx`

```ts
import { Story } from '@storybook/react';

export const MyStory: Story = () => <div />;
MyStory.parameters = {
  layout: 'fullscreen'
}
```

**Comment by shilman** [comment]
@benwinding For what it's worth, we recommend converting your stories from the `storiesOf` API to Component Story Format (CSF): https://storybook.js.org/docs/react/writing-stories/introduction

We've even provided a codemod to help automate this migration:

```sh
npx sb migrate storiesof-to-csf --glob "src/**/*.stories.js"
```

**Comment by benwinding** [comment]
@shilman thanks mate, it will take a while, but could be worth it

**Comment by jayarjo** [comment]
@iamandrewluca neither one has any effect for me for some reason. Do you need to add some addon for this to have an effect?

**Comment by Fontopen** [comment]
@webunderconstruction https://csser.space/questions/how-can-i-eliminate-margin-and-padding-from-html-and-body-elements-in-a-vue-application
