### ISSUE TITLE
Add cors headers to storybook dev server

### ISSUE THREAD

**Issue by ndelangen** [storybookjs/storybook#12108]
Ensure composing local refs work without console log errors

**Comment by ndelangen** [comment]
Odd, we actually have this code:
https://github.com/storybookjs/storybook/blob/9182d9f5ddbe136e9cd5fc9f11fa962a3cfe08f1/lib/core/src/server/build-dev.js#L361-L366

So this should already work!

**Comment by ndelangen** [comment]
https://github.com/storybookjs/storybook/commit/2eae03e89da0e1b22395f65eb07ff5c2cfc0fbc3

**Comment by ndelangen** [comment]
@shilman @tmeasday did we get reports local dev storybooks didn't ref correctly? I think it was NOT because of missing cors headers, but rather the problem of iframe.html always failing to be fetched.

I think this can be closed.

**Comment by tmeasday** [comment]
Ahh, ok I may have misunderstood!

**Comment by asherccohen** [comment]
Hi everyone. Is this an issue in storybook@6.0.27? I am getting cors errors fetching stories.json.
I am serving storybook instances locally (npx serve) and I cannot get my main Storybook to fetch stories from other instances running.

**Comment by ndelangen** [comment]
does `npx serve` serve with CORS header enabled?

**Comment by shilman** [comment]
I think `npx serve` has problems in general with storybook because it rewrites routes. We recommend `http-server` instead.

**Comment by tmeasday** [comment]
@asherccohen -- did you generate `stories.json`?

**Comment by asherccohen** [comment]
Thanks everyone, that helped. I had to manually generate stories.json and also metadata.json (this I hacked by simply adding an empty json file as I don't know how to generate it, any advice is appreciated).

I also had to use http-server wth cors enabled:

npx http-server -p 5000 --cors

**Comment by tmeasday** [comment]
> I also had to use http-server wth cors enabled:

Interesting, good tip.

> metadata.json

Empty is fine. I don't think this file needs to exist though -- was it not working, or were you just concerned about a CORS error in the browser console?

**Comment by asherccohen** [comment]
@tmeasday Now that u pointed it out, metadata.json is optional, but I was driven by the network error and fixed it anyway.

**Comment by matis-dk** [comment]
> .

Works just fine if you add the `--cors` flag.
`npx serve storybook-static --cors`

**Comment by henrycity** [comment]
Is there a way that I could just use `npm run start-storybook` to avoid cors errors when fetching stories.json?

**Comment by shilman** [comment]
@henrycity `start-storybook` doesn't currently serve `stories.json` as far as I know. I've added an experimental feature for that in 6.3, hidden behind a feature flag, and I think that should be fully supported in 6.4.

**Comment by unikitty37** [comment]
@shilman Was that support ever added? I'm running 6.5.16, and `yarn start-storybook` in conjunction with the Ruby/Rails gem `view_component-storybook` still leaves me with this:

```
Access to fetch at 'http://localhost:3030/rails/stories/accordion_component/default?measureEnabled=false&outline=false' 
from origin 'http://localhost:9090' has been blocked by CORS policy: No 'Access-Control-Allow-Origin'
header is present on the requested resource. If an opaque response serves your needs, set the request's
mode to 'no-cors' to fetch the resource with CORS disabled.
```

I can't find anything relating to CORS in the documentation:

![image](https://user-images.githubusercontent.com/139183/219094450-aecc3c1c-022f-4ad5-bce2-56adcf67d003.png)

(including any mention of the experimental feature in the CHANGELOG.md, FWIW)

My current `package.json` entry is

```
  "scripts": {
    "storybook": "start-storybook -p 6006"
  }
```

but if I add `--cors` to that it fails to recognise it as a valid option. What _should_ I be putting there?

**Comment by ndelangen** [comment]
Hmm, I think it's had been implemented in 6.5... I'm pretty sure.

In 7.0 the code for this is here:
https://github.com/storybookjs/storybook/blob/e54cfed6c7079dac855bfb41349356f55a28ad0b/code/lib/core-server/src/dev-server.ts#L50
https://github.com/storybookjs/storybook/blob/43f93bb8fb8056fbbd46f6d5fd90ca460c5f858a/code/lib/core-server/src/utils/getAccessControlMiddleware.ts#L3-L17

**Comment by ndelangen** [comment]
Here's the code for 6.5:
https://github.com/storybookjs/storybook/blob/68361889edf068fbf0f22a85199a1c3e217f9353/lib/core-server/src/dev-server.ts#L102-L119

**Comment by tmeasday** [comment]
@unikitty37 that looks like you need CORS header from your Rails server (port 3030)?

**Comment by unikitty37** [comment]
Thanks — a previous dev had already set CORS up, but using a rather old method (probably left over from when the app used a much older Rails version). Updating the CORS code to use Rack::Cors seems to have fixed that.

**Comment by FilipSwiatczak** [comment]
Using "@storybook/react": "^6.5.16" and still seeing this issue:
"has been blocked by CORS policy: No 'Access-Control-Allow-Origin'" 
This is the case for local dev and for locally browsed storybook-static. 
Pushed storybook-static to aws s3 and same thing there, even with CORS policy open on the bucket. 
Seems to be related to the storybook itself and I'm hitting a wall. Any suggestions please? This should really work "out of the box"!

**Comment by tmeasday** [comment]
@FilipSwiatczak have you tried SB7? We fixed some issues around CORS in v7, so it might be fixed there.

Otherwise, how are you serving on port 61776?

**Comment by ndelangen** [comment]
You're expecting the `'our-design-system'` to work?

That's completely dependent on `'https://xxx.co.uk/'` having CORS enabled/supported there.

---

The storybook design system indeed tries to load `index.json` which fails, with a 404, because it hasn't been updated to 7.0 yet. Therefore it uses the fallback `stories.json` which you can see in your screenshot succeeds.

The other composed storybook also tries both, but both fail (presumingly due to CORS errors), therefore the UI in storybook shows the composed storybook failed to load.

**Comment by FilipSwiatczak** [comment]
thanks @ndelangen are there any resources/guides/pointers from storybook on how CORS should be set in aws s3 static webhosting? Asking since storybook deployer used to take care of that and has been recently archived which makes searching return some outdated results. Thanks!

**Comment by ndelangen** [comment]
@FilipSwiatczak that's unfortunately something that's outside of my expertise.

But likely a good question to find/ask on StackOverflow

**Comment by FilipSwiatczak** [comment]
Update, I made it work in s3 following instructions here: https://stackoverflow.com/questions/50022326/amazon-s3-image-cors-issue

Mostly setting CORS policy in S3 bucket that is Embedded to:
```
[
    {
        "AllowedHeaders": [
            "*"
        ],
        "AllowedMethods": [
            "GET"
        ],
        "AllowedOrigins": [
            "*"
        ],
        "ExposeHeaders": []
    }
]
```
Hope this helps anyone landing here figuring out CORS in aws s3. Cheers

**Comment by sneko** [comment]
Sorry to continue this issue but I'm using Vite locally and launching 2 Storybook at the same time and I'm getting the error:
```
Access to fetch at 'http://localhost:6007/index.json' from origin 'http://localhost:6006' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'.
```

I can confirm `http://localhost:6007/index.json` exists, and I tried to set server headers in the Vite configuration but it still mention `must not be the wildcard '*'`. I tried multiple way to configure it (configuring `cors`, `headers`, `middlewares` setting headers).

I'm a bit lost, I was expecting Composition to be out of the box. Do you have a working example with Vite?

Thank you,

**Comment by sneko** [comment]
Found a "solution": despite I fixed a shared cache issue and that I'm now using different NPM package for each Storybook instance (ref: https://github.com/storybookjs/storybook/issues/15805#issuecomment-1563690740) the CORS issue was still happening when serving at the same time my 2 instances.

The solution was to delay from 3 seconds serving the instance referencing the other one. From there, no more issue! It's kind of weird (remember, everything is done locally, so no real custom CORS errors...), my conclusion:
* either during the "dev" process, the builder tries to reach the other URL, seeing nothing it changes its CORS strategy to a more restrictive one
* or I still have somewhere a concurrent access on something, but I'm in a monorepo with `pnpm`, instances separated in different NPM packages, and I checked both commands do not pollute the `node_modules/.cache/*` of the other...

Anyway, lost too much time on time, the simple delay of 3s is ugly but I'm fine with it for now 👍

**Comment by ndelangen** [comment]
I'm sorry you spend so much time on this @sneko. 

We indeed have code that tries to compose a storybook in a few ways.
The assumption we made as maintainers is that a storybook that's being composed will be fully available and ready before it's requested.

We could likely make some tweaks to our server to "hold" the request for longer, whilst the storybook is still getting "booted".

**Comment by ndelangen** [comment]
Yes it's possible that that changed.
Though the fact it worked prior to 7.0 was more of a happy accident.

@eloiqs you could invest a tiny bit of time writing a script that spawns the composed storybooks first, wait for them to be ready, and then spawn the main one?

Sorry for this nuisance.

**Comment by sneko** [comment]
@eloiqs no matter you want a script or direct CLI you can rely on https://github.com/open-cli-tools/concurrently to do so. Having each subcommand with a `sleep X && storybook dev` (X being like: 0, 3, 6).

**Comment by tmeasday** [comment]
You might try using [`wait-on`](https://github.com/jeffbski/wait-on) too.

**Comment by eloiqs** [comment]
👍 `wait-on` is perfect for this, thanks!
Here's what I ended up with 

```bash
npx concurrently -k -s first -n "app1,app2,composed" -c "magenta,blue,green" \
"storybook dev -c .storybook/apps/app1 -p 6007 --no-open" \
"storybook dev -c .storybook/apps/app2 -p 6008 --no-open" \
"wait-on tcp:6007 && wait-on tcp:6008 && storybook dev -c .storybook/apps/composed -p 6009 --no-open"
```

**Comment by bitttttten** [comment]
I am using this in turborepo, where my storybook config lives inside `packages/sb`, and there are a lot of apps and packages that have their own storybooks.

So I went with something like:

```sh
npx concurrently -k -s first -n 'sb,composed' -c 'magenta,blue' 'turbo run storybook --parallel --filter=!sb -- --no-open' 'npx wait-on tcp:6007 && npx wait-on tcp:6008 && turbo run storybook --filter=sb'
```

**Comment by bitttttten** [comment]
Although this is not without issues 😅 

![Screenshot 2023-07-11 at 11 29 39](https://github.com/storybookjs/storybook/assets/19930241/2ac94667-94eb-4774-b201-50b3f61c29d9)

I get a lot of errors in the console and some remote images don't load (because of cross origin errors I think):

```sh
Failed to load resource: the server responded with a status of 404 (Not Found)
:6008/metadata.json:1     Failed to load resource: the server responded with a status of 404 (Not Found)
:6007/metadata.json:1     Failed to load resource: the server responded with a status of 404 (Not Found)
VM721 iframe.html:12 unable to connect to top frame for connecting dev tools
(anonymous) @ VM721 iframe.html:12
runtime.js:4 DOMException: Blocked a frame with origin "http://localhost:6007" from accessing a cross-origin frame.
    at new Instrumenter (http://localhost:6007/node_modules/.cache/.vite-storybook/deps/@storybook_addon-interactions_preview.js?v=5d03fbdf:60:93)
    at instrument (http://localhost:6007/node_modules/.cache/.vite-storybook/deps/@storybook_addon-interactions_preview.js?v=5d03fbdf:239:510)
    at http://localhost:6007/node_modules/.cache/.vite-storybook/deps/@storybook_addon-interactions_preview.js?v=5d03fbdf:249:18
warn @ runtime.js:4
runtime.js:4 DOMException: Blocked a frame with origin "http://localhost:6007" from accessing a cross-origin frame.
    at new Instrumenter (http://localhost:6007/node_modules/.cache/.vite-storybook/deps/@storybook_addon-interactions_preview.js?v=5d03fbdf:60:93)
    at instrument (http://localhost:6007/node_modules/.cache/.vite-storybook/deps/@storybook_addon-interactions_preview.js?v=5d03fbdf:239:510)
    at http://localhost:6007/node_modules/.cache/.vite-storybook/deps/@storybook_addon-interactions_preview.js?v=5d03fbdf:286:25
warn @ runtime.js:4
chunk-F3MVQVF6.js:1 received globals from a non-local ref. This is not currently supported.
```

**Comment by dugip** [comment]
I'm getting this error when trying to work with the Google Maps Places API in Storybook on localhost:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://maps.googleapis.com/maps/api/mapsjs/gen_204?csp_test=true. (Reason: CORS request did not succeed). Status code: (null).

I'm using Storybook 7.0.20.
