### ISSUE TITLE
Viewport addon doesn't work by default even though it is an 'essential addon'

### ISSUE THREAD

**Issue by gopinav** [storybookjs/storybook#12113]
**Describe the bug**
Storybook with React - The change viewport icon does not appear in the toolbar area by default. I take this as an issue since the docs mention "By default, you are presented with a set of common viewports."

**Work around at the moment**
I have to specify the addon explicitly in main.js
`  "addons": [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/addon-viewport",
    "@storybook/preset-create-react-app"
  ]`

**To Reproduce**
Create a react app
Install storybook
Run storybook

1. Go to 'browser'
2. View the storybook toolbar
**Expected behavior**
Viewport icon should appear.

**Screenshots**
![image](https://user-images.githubusercontent.com/13146172/90527181-e3b33680-e18e-11ea-9af3-377040ecd7e7.png)

After explicitly specifying the addon in main.js
![image](https://user-images.githubusercontent.com/13146172/90527495-3ab90b80-e18f-11ea-81d9-843987a957bf.png)

**Comment by shilman** [comment]
Closing as dupe to #12024

**Comment by tooppaaa** [comment]
@gopinav Are you using windows ? (also closing per previous comment)

**Comment by gopinav** [comment]
@tooppaaa Yes I am
