### ISSUE TITLE
Documentation how to connect argTypes with props in angular

### ISSUE THREAD

**Issue by noelelias** [storybookjs/storybook#12116]
Currently there is no documentation I could find on how to connect argTypes with props in [angular](https://github.com/storybookjs/storybook/search?q=argTypes+angular&unscoped_q=argTypes+angular).
But there are example for [react](https://github.com/storybookjs/storybook/search?q=argTypes+react&unscoped_q=argTypes+react). With the introduction of CSF a lot of documentation is no longer up to date and not compatible with the react documentation anymore. It's pretty hard to get started ATM. 

It would be nice to have some code example of how to connect argTypes with props in angular with CSF.

**Comment by jonniebigodes** [comment]
@noelelias thank you for bringing this to our attention. I'm currently working implementing the snippets for the core frameworks (vue,react and angular). There's still some nuances to each framework that need to be taken care of in order to present not only you, but the rest of the community the best information possible. 

If you want you can contribute angular snippets with a pull request. I would be more than welcome to review it and get it merged.

Feel free to provide feedback.

**Comment by noelelias** [comment]
@jonniebigodes thank you for the update. Current I'm still figuring out stuff myself. Once I got it together, I will look into documenting. :)

**Comment by shilman** [comment]
In the meantime there's a basic example here:

https://github.com/storybookjs/storybook/blob/master/examples/angular-cli/src/stories/addon-controls.stories.ts

**Comment by jonniebigodes** [comment]
Not stale

**Comment by meriturva** [comment]
Actually, I cannot migrate from knobs to controls on my angular mdx files because I have no idea how to connect args.
is it possible just to have a really simple example?

**Comment by shilman** [comment]
@meriturva did you already look at this https://storybook.js.org/docs/react/essentials/controls

cc @jonniebigodes

**Comment by meriturva** [comment]
@shilman we have already checked doc linked, thanks anyway.
Actually, we write stories using MDX and really simple template syntax:

Using knobs:
```
<Canvas>
  <Story name="Container disabled">
    {{
      template: `<my-component [disabled]="disabled">
                  </my-component>`,
      props: {
          disabled: boolean('Disabled flag', true)
      }
    }}
  </Story>
</Canvas>
```

Migrating to controls we have started with:
```
<Canvas>
  <Story name="Container disabled"
    args={{disabled: true}}
    argTypes={{disabled: { control: "boolean" }}}
  >
    {{
      template: `<my-component [disabled]="disabled">
                  </my-component>`,
// Dosen't work
      props: args
    }}
  </Story>
</Canvas>
```

but we don't find any way to bind args to component props.

**Comment by meriturva** [comment]
Sorry @jonniebigodes and @shilman , just to know: do you plan to add an example on repo to explain how to use MDX, ArgsType and Angular?

Thanks!

**Comment by shilman** [comment]
You probably need something like:

```
<Canvas>
  <Story name="Container disabled"
    args={{disabled: true}}
    argTypes={{disabled: { control: "boolean" }}}
  >
    {(args) => ({
      template: `<my-component [disabled]="disabled">
                  </my-component>`,
// Dosen't work
      props: args
    })}
  </Story>
</Canvas>

**Comment by parkersweb** [comment]
Just an alternative that works for us connecting mdx to the Story args with a custom template:
```
<Canvas>
  <Story
    height="300"
    name="Simple"
    args={{
      appearance: 'level1',
    }}
  >
    {(args) => ({
      template: `<my-component appearance='${args.appearance}'>Content</my-component>`,
    })}
  </Story>
</Canvas>
<ArgsTable story="Simple" />
```
Obviously adding argTypes if you need them where the ArgsTable doesn't derive them automatically from the type.

**Comment by meriturva** [comment]
Thanks for examples @parkersweb @shilman ! It works correctly!

Issue could be closed for me!
