### ISSUE TITLE
"npx sb init"  error

### ISSUE THREAD

**Issue by wtl1019** [storybookjs/storybook#12125]
run   " npx sb init " 
安装 [ '@storybook/cli@latest' ] 失败，错误代码：1

**Comment by wtl1019** [comment]
npm ERR! code EINTEGRITY npm ERR! sha512-P+lWzPrsgfN+UEpDS3U8AQKg/UjZX6mQSJueZj3EK+vNESoqBSpBUD3gmu4sF9lOsjXWjF11dQKUqemf3veq1w== integrity checksum failed when using sha512: wanted sha512-P+lWzPrsgfN+UEpDS3U8AQKg/UjZX6mQSJueZj3EK+vNESoqBSpBUD3gmu4sF9lOsjXWjF11dQKUqemf3veq1w== but got sha512-z4PhNX7vuL3xVChQ1m2AB9Yg5AULVxXcg/SpIdNs6c5H0NE8XYXysP+DGNKHfuwvY7kxvUdBeoGlODJ6+SfaPg==. (0 bytes)

**Comment by shilman** [comment]
sounds like an issue with your npm registry?
