### ISSUE TITLE
Navigation broken after upgrade to 6 (only in static build)

### ISSUE THREAD

**Issue by sakulstra** [storybookjs/storybook#12128]
**Describe the bug**
When running storybook in dev mode everything works as it should. When running the static build `build-storybook -s ./src/fonts -o public` the navigation doesn't work any more. Clicking on a navigation link changes the url, but not the view -> reloading will open the page on that specific page though,

**To Reproduce**
That's kinda hard - I cannot reproduce it in a new demo project and i cannot share our work project :(

**Expected behavior**
Navigation should work :shrug: 

**Screenshots**
![gifcast_200819111559](https://user-images.githubusercontent.com/4396533/90616273-84e0d200-e20d-11ea-95c2-bb1f8e4dd459.gif)

**System:**
```
Environment Info:

  System:
    OS: Linux 5.4 Manjaro Linux
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  Binaries:
    Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v12.13.0/bin/yarn
    npm: 6.12.0 - ~/.nvm/versions/node/v12.13.0/bin/npm
  Browsers:
    Firefox: 79.0
```

**Additional context**
Might be related to #10782, #11590 ( i tried regenerating lockfiles, but it didn't help)

We're not using any fancy plugins, but typescript and a mixture of new and old story format.
```
// main
module.exports = {
  stories: ['../**/*.stories.@(ts|tsx)'],
  addons: [
    '@storybook/addon-actions',
    '@storybook/addon-links',
    '@storybook/addon-viewport',
  ],
};
// preview
import React from 'react';
import { addDecorator, addParameters } from '@storybook/react';
import { INITIAL_VIEWPORTS } from '@storybook/addon-viewport';
import CssBaseline from '../src/components/CssBaseline';
import { MuiThemeProvider } from '@material-ui/core/styles';
import legalheadusTheme from '../src/themes/legalheadus';

const Decorator = (fn) => (
  <MuiThemeProvider theme={legalheadusTheme}>
    <CssBaseline />
    {fn()}
  </MuiThemeProvider>
);

addDecorator(Decorator);

addParameters({
  options: {
    panelPosition: 'bottom',
  },
  viewport: { viewports: INITIAL_VIEWPORTS },
});
```

**Comment by shilman** [comment]
closing as dupe to #11958

**Comment by sakulstra** [comment]
sorry didn't see that, thx for pointing me to the correct ticket :+1:
