### ISSUE TITLE
Link to mdx ArgTypes documentation in DocBlocks documentation is incorrect

### ISSUE THREAD

**Issue by mattdarveniza** [storybookjs/storybook#12124]
**Describe the bug**

In the [doc-blocks documentation](https://storybook.js.org/docs/react/writing-docs/doc-blocks#customizing) for usage of ArgTypes with mdx, it references `/docs/react/api/mdx#argtypes` as a way to see docs on usage of that, [on this line](https://github.com/storybookjs/storybook/blame/next/docs/writing-docs/doc-blocks.md#L78)

That link takes us to the [mdx page](https://storybook.js.org/docs/react/api/mdx#argtypes) but there is no `#argtypes` heading or section on that page.

**To Reproduce**
Visit links above, see that argtypes is a missing section

**Expected behavior**
Ideally some documentation on how to use ArgTypes or the ArgsTable component would exist

**Additional context**
The whole documentation on ArgTypes and ArgsTable seems a bit half-baked... the table below where this issue is seems to also be incorrect or filled with fluff data. Would love some more concrete documentation on getting an ArgsTable with controls in it in mdx but maybe that's still in the works?

**Comment by jonniebigodes** [comment]
@mattdarveniza thanks for bringing this to our attention. I'm going to check it in a bit and create a pull request addressing this issue.

Stay safe

**Comment by jonniebigodes** [comment]
@mattdarveniza just merged pull request with the change you brought up. If you don't mind i'm going to close this issue as the documentation is now pointing to the correct place. 

Feel free to re open it should any further adjustments are required. 

Once again thank you for bringing this to my attention and sorry for the inconvenience.

Stay safe.

**Comment by mattdarveniza** [comment]
Great, thanks for the speedy fix!
