### ISSUE TITLE
Addon-controls: do not show addon tab for a particular story in one mdx file

### ISSUE THREAD

**Issue by zhdanouskikh** [storybookjs/storybook#12133]
I have 3 stories in one mdx file. I want controls tab to be shown only for one story.

**Additional context**

This is the story where I don't want to see controls (It's written, that this story does not support controls. So maybe it' better to show empty screen, instead of all controls from other story?)
![image](https://user-images.githubusercontent.com/8644307/90640643-e66a6600-e238-11ea-9805-7af7a2bc2696.png)

And I wanna show controls for this story, and they are shown. No problems with this.
![image](https://user-images.githubusercontent.com/8644307/90640710-feda8080-e238-11ea-989c-f6a44b67741c.png)

**Comment by shilman** [comment]
Sorry missed this issue first time around. This looks like a bug.

**Comment by shilman** [comment]
Do you have a reproduction repo?
