### ISSUE TITLE
[Storybook 6.0.12 addon-essentials, controls]  type of control with type = "range" interpreted as "color"

### ISSUE THREAD

**Issue by kseniya57** [storybookjs/storybook#12131]
**Describe the bug**
type of control with type = "range" interpreted as "color"

**To Reproduce**

1. add to argTypes (for one of props) the following configuration:  `{ control: { type: 'range', min: 50, max: 1000, step: 50 } }`
2. Click on tab controls
4. See error in console

**Expected behavior**
type of control with type = "range" interpreted as "range"

**Screenshots**

<img width="1107" alt="Снимок экрана 2020-08-19 в 18 49 38" src="https://user-images.githubusercontent.com/31247233/90625858-c5ac0b80-e24c-11ea-939d-ac570032930e.png">

**Comment by shilman** [comment]
Do you have a repro repo you can share?

**Comment by kseniya57** [comment]
The problem is:

in my configuration theme.appBorderColor === 'transparent'

**Comment by kseniya57** [comment]
https://github.com/kseniya57/storybook-range-control-issue

**Comment by shilman** [comment]
This looks like a bug in your theme. I commented out this code in `manager.js` and it's working:

```js
// addons.setConfig({
//   theme,
// });
```

Also, `addon-centered` has been deprecated. Use `layout: 'center'` story parameter instead.

**Comment by kseniya57** [comment]
Yes, thank you, i've already mentioned it in comment before

**Comment by shilman** [comment]
Ah sorry I didn't understand your comment above.
