### ISSUE TITLE
[addon-docs] Story name & path appended with "Story" when using "CSF Stories with MDX Docs"

### ISSUE THREAD

**Issue by kylegach** [storybookjs/storybook#12143]
**Describe the bug**
When organizing my stories and docs using the ["CSF Stories with MDX Docs" recipe](https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/recipes.md#csf-stories-with-mdx-docs), the displayed story name is appended with `" Story"` and the path is appended with `"-story"`, unless I define an explicit `name` for the story. The displayed name is a bit annoying, but the path breaks existing story permalinks.

**To Reproduce**
_See code snippets_

**Expected behavior**
I would expect the displayed story name and path to be unaffected, regardless of story organization method.

**Code snippets**

```jsx
// Component.stories.jsx

import { Component } from '..';

export const Example1 = () => <Component />;

export const Example2 = () => <Component />;
Example2.storyName = 'Example2';

export const Example3 = () => <Component />;
```

```jsx
// Component.stories.mdx

import { Component } from '..';
import * as stories from './Component.stories';

<Meta title="Component" component={Component} />

<Story story={stories.Example1} />

<Story story={stories.Example2} />

<Story story={stories.Example3} name="Example3" />
```

The three stories in the snippets above display as:

1. "Example1 Story" (/?path=/story/component--example-1-story)
    - Incorrect; should be: "Example1" (/?path=/story/component--example-1)
1. "Example2" (/?path=/story/component--example-2)
    - Correct
1. "Example3" (/?path=/story/component--example-3)
    - Correct

**System:**

- @storybook/addon-docs@6.0.12
- @storybook/react@6.0.12

```
System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Binaries:
    Node: 12.16.0 - ~/.nvm/versions/node/v12.16.0/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v12.16.0/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.0/bin/npm
  Browsers:
    Chrome: 84.0.4147.135
    Firefox: 78.0.2
    Safari: 13.1.1
```

**Comment by shilman** [comment]
Crikey!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.14 containing PR #12154 that references this issue. Upgrade today to try it out!

Closing this issue. Please re-open if you think there's still more to do.
