### ISSUE TITLE
Storybook iframe adding padding on version 6

### ISSUE THREAD

**Issue by abeledovictor** [storybookjs/storybook#12142]
**Describe the bug**
When migrating to v6 there's an extra padding of 1rem added to the iframe rendering the story.

**To Reproduce**

1. Create a story
2. Open it on a separate tab
3. Inspect HTML body tag of iframe
4. HTML body tag adds 1rem of padding to story

**Expected behavior**
No padding is added

**Screenshots**

After:

<img width="991" alt="Screen Shot 2020-08-19 at 14 04 19" src="https://user-images.githubusercontent.com/18119352/90667233-e496a780-e224-11ea-95f8-20b9aee2861a.png">

Before:

<img width="985" alt="Screen Shot 2020-08-19 at 14 05 32" src="https://user-images.githubusercontent.com/18119352/90667371-0ee86500-e225-11ea-85e7-b4165428e758.png">

**System:**
  System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
  Binaries:
    Node: 12.18.2 - ~/.nvm/versions/node/v12.18.2/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.2/bin/npm
  Browsers:
    Chrome: 84.0.4147.125
    Firefox: 77.0.1
    Safari: 13.1
  npmPackages:
    @storybook/addon-a11y: ~6.0.12 => 6.0.12
    @storybook/addon-console: ~1.2.1 => 1.2.1
    @storybook/addon-essentials: ~6.0.12 => 6.0.12
    @storybook/addon-events: ~6.0.12 => 6.0.12
    @storybook/addon-knobs: ~6.0.12 => 6.0.12
    @storybook/addon-links: ~6.0.12 => 6.0.12
    @storybook/addon-storysource: ~6.0.12 => 6.0.12
    @storybook/addons: ~6.0.12 => 6.0.12
    @storybook/client-logger: ~6.0.12 => 6.0.12
    @storybook/react: ~6.0.12 => 6.0.12
    @storybook/theming: ~6.0.12 => 6.0.12

**Previous system**
  System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
  Binaries:
    Node: 12.18.2 - ~/.nvm/versions/node/v12.18.2/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.2/bin/npm
  Browsers:
    Chrome: 84.0.4147.125
    Firefox: 77.0.1
    Safari: 13.1
  npmPackages:
    @storybook/addon-a11y: ~5.3.19 => 5.3.19
    @storybook/addon-actions: ~5.3.19 => 5.3.19
    @storybook/addon-backgrounds: ~5.3.19 => 5.3.19
    @storybook/addon-centered: ~5.3.19 => 5.3.19
    @storybook/addon-console: ~1.2.1 => 1.2.1
    @storybook/addon-docs: ~5.3.19 => 5.3.19
    @storybook/addon-events: ~5.3.19 => 5.3.19
    @storybook/addon-info: ~5.3.19 => 5.3.19
    @storybook/addon-jest: ~5.3.19 => 5.3.19
    @storybook/addon-knobs: ~5.3.19 => 5.3.19
    @storybook/addon-links: ~5.3.19 => 5.3.19
    @storybook/addon-notes: ~5.3.19 => 5.3.19
    @storybook/addon-options: ~5.3.19 => 5.3.19
    @storybook/addon-storyshots: ~5.3.19 => 5.3.19
    @storybook/addon-storysource: ~5.3.19 => 5.3.19
    @storybook/addon-viewport: ~5.3.19 => 5.3.19
    @storybook/addons: ~5.3.19 => 5.3.19
    @storybook/client-logger: ~5.3.19 => 5.3.19
    @storybook/react: ~5.3.19 => 5.3.19
    @storybook/theming: ~5.3.19 => 5.3.19

**Comment by shilman** [comment]
closing as dupe to #12109
