### ISSUE TITLE
Controls: target single property as control inside an object

### ISSUE THREAD

**Issue by RobbertWolfs** [storybookjs/storybook#12156]
When we used the `knobs` addon we could create knobs of an object's property..

```ts
const timeTicks = {
   Month: 'month',
   Year: 'year',
   Quarter: 'quarter'
};

...

props: {
    config: {
        xAxis: {
            tickInterval: select('tickInterval', timeTicks, timeTicks.Month, 'config.xaxis'),
            legend: true,
        },
    },
},


...
```

Which resulted in the following knob:

![image](https://user-images.githubusercontent.com/12511178/90729901-853da380-e2c7-11ea-9e7b-01ade96e6731.png)

As you can see is this a property (tickInterval) inside an object (config) but with its own `knob`, also it is `grouped` inside `config.xaxis`..

Are both options `grouping` and `a property inside an object as own control` possible using the new `controls addon`??

**Comment by shilman** [comment]
Yes, manually. Something like:

```js
export default { 
  ... 
  argTypes: { xAxis: { control: { type: 'select', options: ['hour', 'day', ... ] } } }
};

const Template = ({ xAxis }) => (
  <Chart config={{ xAxis: { tickInterval: xAxis, legend: true } }} />
)
```

We'll try to build a more ergonomic version of this in a future iteration.

**Comment by RobbertWolfs** [comment]
Forgot to mention that I use `angular` instead of `react`.. 

But I will see if I can get something like this to work 👍

**Comment by RobbertWolfs** [comment]
@shilman and is it possible to `group` control properties?

**Comment by shilman** [comment]
Yes but not documented. We didn't have time to figure out the best way to expose it in 6.0.

**Comment by RobbertWolfs** [comment]
Thanks!
