### ISSUE TITLE
Unexpected Behaviors with storiesOf.addDecorator

### ISSUE THREAD

**Issue by jinmayamashita** [storybookjs/storybook#12152]
**Describe the bug**

I have an issue with `storiesOf` (Legacy) API in v6. 
If has multiple `storiesOf` in single file, `storiesOf.addDecorator` is `storiesOf` without `.addDecorator` also affects.
Please see below *Screenshots*

is this is a bug or Better solution in v6?

**To Reproduce**

1. Create a multiple storiesOf like *Code snippets*
2. Run Storybook and see *Screenshots*

**Expected behavior**

`.addDecorator` of first `storiesOf` should not wrap second `storiesOf`

![Kapture 2020-08-20 at 10 50 40](https://user-images.githubusercontent.com/9401060/90707708-2a11ae00-e2d3-11ea-9703-cd10b4053d0e.gif)

**Screenshots**
![Kapture 2020-08-20 at 6 57 38](https://user-images.githubusercontent.com/9401060/90693832-7dbfcf80-e2b2-11ea-87d7-4bde2a3a6350.gif)

**Code snippets**

```jsx
const withBackground = (story) => (
  <div style={{ backgroundColor: 'blue' }}>{story()}</div>
)

// first storiesOf
storiesOf('Button', module)
  .addDecorator(withBackground)
  .add('default', () => <Button />)

// second storiesOf
storiesOf('Button', module)
  .add('color is red', () => <Button color="red" />)
```

Here' s my [Storybook code](https://github.com/jinmayamashita/sandbox-storybook-v6/blob/master/stories/Button.stories.js) using the addDecorator.

**System:**

```
Environment Info:

  System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
  Binaries:
    Node: 13.10.1 - ~/.nodenv/versions/13.10.1/bin/node
    npm: 6.14.7 - ~/.nodenv/versions/13.10.1/bin/npm
  Browsers:
    Chrome: 84.0.4147.125
    Firefox: 79.0
    Safari: 13.1.2
  npmPackages:
    @storybook/addon-actions: 6.0.10 => 6.0.10
    @storybook/addon-knobs: 6.0.10 => 6.0.10
    @storybook/react: 6.0.10 => 6.0.10
    @storybook/theming: 6.0.10 => 6.0.10
```

**Comment by shilman** [comment]
Yes, this was a breaking change in 6.0:

https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#can-no-longer-add-decoratorsparameters-after-stories

**Comment by jinmayamashita** [comment]
Thanks @shilman maybe I have to refactor for v6
