### ISSUE TITLE
storybook-static: toolbar 'open canvas in new tab' has wrong url: storybook-static/index.htmliframe.html

### ISSUE THREAD

**Issue by davidhildering** [storybookjs/storybook#12162]
**Describe the bug**
I just migrated from 5.3 to 6.014. Now, if I npm run build-storybook and check storybook-static, the link set for the 'open canvas in new tab' is wrong. 

output: `storybook-static/index.htmliframe.html?id=`
what it should be: `storybook-static/iframe.html?id=`

my version: 
 "@babel/preset-react": "^7.9.4",
    "@storybook/addon-a11y": "^6.0.6",
    "@storybook/addon-backgrounds": "latest",
    "@storybook/addon-knobs": "latest",
    "@storybook/addon-links": "latest",
    "@storybook/addon-storyshots": "latest",
    "@storybook/addons": "latest",
    "@storybook/components": "latest",
    "@storybook/preset-create-react-app": "3.1.4",
    "@storybook/preset-scss": "^1.0.2",
    "@storybook/react": "^6.0.14",
 "@storybook/theming": "^6.0.6",

1. npm run build-storybook
2. open storybook-static/index.html
2. click on open canvas in new tab
3. result

**Expected behavior**
a correct url

**System:**
windows10, storybook-react

**Comment by ndelangen** [comment]
Strange, it seems to work here:
https://next--storybookjs.netlify.app/official-storybook/?path=/story/addons-a11y-basebutton--default

But it doesn't here:
https://next--storybookjs.netlify.app/official-storybook/index.html?path=/story/addons-a11y-basebutton--default

**Comment by shilman** [comment]
Egads!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.19 containing PR #12233 that references this issue. Upgrade today to try it out!
