### ISSUE TITLE
Use babelrc config in stories.mdx files

### ISSUE THREAD

**Issue by matthisk** [storybookjs/storybook#12169]
**Describe the bug**
We use [twin.macro](https://github.com/ben-rogerson/twin.macro) in our `stories.mdx` file. Since Storybook 6.0 this macro no longer applies correctly. The reason for this seems to be that the `stories.mdx` loader in the webpack config disables `babelrc`. Why was this setting disabled, and is it safe to enable the `babelrc` config again?

**Code snippets**
This is the (simplified) loader config for `stories.mdx` files:

```json
{
  "test": "/(stories|story).mdx/",
  "use": [
    {
      "loader": "babel-loader/lib/index.js",
      "options": {
        "babelrc": false,
        "configFile": false
       }
    }
  ]
}
```

**Additional context**
See [related issue](https://github.com/ben-rogerson/twin.macro/issues/125) on the `twin.macro` repository.

**Comment by shilman** [comment]
Updated MIGRATION.md. Does that work?

https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#user-babelrc-disabled-by-default-in-mdx

**Comment by matthisk** [comment]
Yes that works, thanks!

**Comment by fvanwijk** [comment]
Well, it works fine, but I don't like the distracting warning message.
This is the current config (order of both addons seems not to matter):
```
{
  name: '@storybook/addon-docs',
  options: { mdxBabelOptions: { babelrc: true, configFile: true } },
},
'@storybook/addon-essentials',
```

I'm looking for a way to make the warning disappear :)

**Comment by shilman** [comment]
If we made it log as info instead of warning would that be better? What I described is the recommended way to override override essentials.

**Comment by fvanwijk** [comment]
Sounds good to me!
Alternatively you could proxy the config via essentials:
```js
{
  name: '@storybook/addon-essentials',
  options: {
    docs: {
      mdxBabelOptions: { babelrc: true, configFile: true }
    }
  }
```

**Comment by shilman** [comment]
Yeah I didn't want to create two different configuration mechanisms. Either use the essentials configuration OR "eject" and configure it manually.

**Comment by shilman** [comment]
¡Ay Caramba!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.17 containing PR #12211 that references this issue. Upgrade today to try it out!
