### ISSUE TITLE
Deprecated addons should have a stable release compatible with Storybook 6

### ISSUE THREAD

**Issue by stof** [storybookjs/storybook#12163]
Deprecated addons like `addon-notes` don't have a 6.0 release, and their existing 5.x releases have dependencies on Storybook 5. This leads to mixing 2 versions of Storybook.
IMO, these addons should receive a 6.0 release using semver ranges for the storybook dependencies (as they won't get released again for each storybook release), otherwise the deprecation does not work well and it is effectively an immediate removal.

**Comment by shilman** [comment]
That's true, 6.0 is a breaking release and we've been warning about `addon-docs` replacing `info` and `notes` in hundreds of issues and several posts for over a year.

What you're asking for is reasonable. If anybody wants to maintain these addons, they are welcome to do that as part of the maintenance. I've asked for volunteers in the release announcement, and will ask again here.

**Comment by stof** [comment]
@shilman the issue is that because of the way the change was done, `addon-notes` is not actually deprecated in 6.0 but fully removed, as there is no compatible release.
Note that I'm not asking for an active maintenance of the addon (I know that `addon-docs` is the new way to go, but migrating to it is not yet done in our project). what I'd like to see is a release of the addon allowing a `^6.0` range for its storybook dependencies (even if it is marked as "use with caution as it is not officially supported anymore") to allow  decoupling the upgrade from the migration.
