### ISSUE TITLE
[addon-docs] MDX <Story> only renders [Object object]

### ISSUE THREAD

**Issue by airtonix** [storybookjs/storybook#12176]
**Describe the bug**

- Upgraded from 5.3.x to 6.0.13
- converted old `storysOf('blah blah blah')` to mdx format
- `<Canvas><MyComponent /></Canvas>` renders MyComponent correctly, but
- `<Canvas><Story name='blah blah'><MyComponent /></Story></Canvas>` results only `[Object object]` : 

**To Reproduce**

1. Follow 5.x to 6.x upgrade guide
2. Creates story:

```mdx
import { Meta, Story, ArgsTable, Canvas, Description } from '@storybook/addon-docs/blocks'
import { text, color } from '@storybook/addon-knobs'
import { action } from '@storybook/addon-actions'

import ExampleComponent from './ExampleComponent'

<Meta
  title="Getting Started/Writing Components/ExampleComponent"
  component={ExampleComponent}
/>

# Example Component

<Description of={ExampleComponent} />

<Canvas>
  <Story name="basic" args={{}}>
    <ExampleComponent />
  </Story>
</Canvas>

<ArgsTable of={ExampleComponent} />
```

Results in:

![image](https://user-images.githubusercontent.com/61225/90838697-b041f900-e394-11ea-8571-817a22a43f36.png)

but this story: 

```mdx
import { Meta, Story, ArgsTable, Canvas, Description } from '@storybook/addon-docs/blocks'
import { text, color } from '@storybook/addon-knobs'
import { action } from '@storybook/addon-actions'

import ExampleComponent from './ExampleComponent'

<Meta
  title="Getting Started/Writing Components/ExampleComponent"
  component={ExampleComponent}
/>

# Example Component

<Description of={ExampleComponent} />

<Canvas>
    <ExampleComponent />
</Canvas>

<ArgsTable of={ExampleComponent} />

```
results in 
![image](https://user-images.githubusercontent.com/61225/90839263-3c085500-e396-11ea-938d-1051a43b6ecf.png)

**Code snippets**

`package.json`
```
...
 "private": true,
  "browserslist": "> .5% or last 2 versions",
  "dependencies": {
    "@babel/cli": "7.4.3",
    "@babel/core": "7.4.3",
    "@babel/plugin-proposal-class-properties": "7.4.0",
    "@babel/plugin-proposal-decorators": "7.4.0",
    "@babel/plugin-transform-runtime": "7.4.3",
    "@babel/polyfill": "^7.0.0",
    "@babel/preset-env": "7.4.3",
    "@babel/preset-react": "7.0.0",
    "@babel/register": "^7.6.2",
    "@babel/runtime": "7.4.3",
    "@ckeditor/ckeditor5-build-classic": "^17.0.0",
    "@ckeditor/ckeditor5-react": "^2.1.0",
    "@storybook/addon-a11y": "6.0.13",
    "@storybook/addon-actions": "6.0.13",
    "@storybook/addon-backgrounds": "6.0.13",
    "@storybook/addon-docs": "6.0.13",
    "@storybook/addon-knobs": "6.0.13",
    "@storybook/addon-links": "6.0.13",
    "@storybook/addon-storysource": "6.0.13",
    "@storybook/addon-viewport": "6.0.13",
    "@storybook/html": "6.0.13",
    "@storybook/preset-scss": "1.0.2",
    "@storybook/react": "6.0.13",
    "@tinymce/tinymce-react": "^3.5.0",
    "anysort": "^2.0.0",
    "axios": "0.16.2",
    "babel-eslint": "9.0.0",
    "babel-loader": "8.0.5",
    "babel-plugin-lodash": "3.2.11",
    "babel-plugin-require-context-hook": "1.0.0",
    "babel-plugin-transform-imports": "1.5.1",
    "classnames": "^2.2.6",
    "color": "3.1.0",
    "core-js": "^3.6.5",
    "cross-env": "5.2.0",
    "cross-var": "1.1.0",
    "css-loader": "2.1.0",
    "debug": "3.1.0",
    "djanjucks": "0.0.3",
    "enzyme": "3.10.0",
    "enzyme-adapter-react-16": "1.14.0",
    "eslint": "^5.5.0",
    "eslint-config-airbnb": "^17.1.0",
    "eslint-config-prettier": "^3.0.1",
    "eslint-config-react-app": "3.0.8",
    "eslint-config-standard": "6.0.0",
    "eslint-config-standard-react": "4.0.0",
    "eslint-import-resolver-webpack": "^0.12.2",
    "eslint-loader": "2.1.2",
    "eslint-plugin-babel": "4.1.1",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-jsx-a11y": "^6.1.1",
    "eslint-plugin-prettier": "^2.6.2",
    "eslint-plugin-promise": "3.0.0",
    "eslint-plugin-react": "^7.11.1",
    "eslint-plugin-standard": "^4.0.1",
    "fecha": "3.0.2",
    "file-loader": "^0.11.2",
    "flat": "^5.0.2",
    "formstate": "^1.0.2",
    "history": "^4.7.2",
    "html-loader": "^0.5.5",
    "html-react-parser": "^0.9.1",
    "imports-loader": "0.7.0",
    "jest": "24.9.0",
    "jquery": "^3.5.1",
    "jss": "^10.4.0",
    "jss-preset-default": "^10.4.0",
    "loadjs": "^4.2.0",
    "lodash": "^4.17.11",
    "markserv": "1.17.2",
    "microevent": "^1.0.0",
    "mini-css-extract-plugin": "0.6.0",
    "mobx": "4.9.4",
    "mobx-react": "^5.2.8",
    "nconf": "0.10.0",
    "node-sass": "4.11.0",
    "npm-run-all": "4.1.5",
    "nunjucks-loader": "^3.0.0",
    "onchange": "5.2.0",
    "postcss-loader": "2.1.5",
    "postcss-preset-env": "6.5.0",
    "prop-types": "15.5.6",
    "react": "^16.6.3",
    "react-dom": "^16.6.3",
    "require-context.macro": "1.0.4",
    "sass-loader": "7.1.0",
    "semantic-ui-react": "^0.84.0",
    "standard-version": "5.0.2",
    "style-loader": "0.23.1",
    "swig-loader": "^2.1.0",
    "tinymce": "^5.2.0",
    "url-loader": "^0.5.6",
    "webpack": "4.39.3",
    "webpack-bundle-analyzer": "3.3.2",
    "webpack-cli": "3.3.8",
    "webpack-config": "7.5.0",
    "webpack-dev-server": "3.3.1",
    "webpack-manifest-plugin": "2.0.4"
  },
...
```

`tools/storybook/main.js`
```
const Config = require('webpack-config').default

const path = require('path')
const CWD = process.cwd()
const WEBPACK_CONFIG = path.join(CWD, 'tools', 'webpack', 'builder')

module.exports = {
  stories: [
    `../../src/**/*.stories.@(js|mdx)`,
  ],
  addons: [
    '@storybook/addon-actions',
    '@storybook/addon-knobs',
    '@storybook/addon-a11y',
    '@storybook/addon-backgrounds',
    '@storybook/addon-viewport',
    {
      name: '@storybook/addon-docs',
      options: { configureJSX: true },
    },
  ],
  webpackFinal: async (config, { configType }) => {
    const output = new Config()
      .merge(config)
      .extend(`${WEBPACK_CONFIG}/base/core__resolve.js`)
      .extend(`${WEBPACK_CONFIG}/${configType.toLowerCase()}/aspect__styles.js`)

    config.externals = config.externals || {}
    delete config.resolve.alias['react']
    delete config.resolve.alias['react-dom']

    return output
  }
}
```
`babel.config.js`
```
module.exports = function (api) {
  api.cache(true)

  return {
    'plugins': [
      '@babel/plugin-transform-runtime',
      [
        '@babel/plugin-proposal-decorators',
        {
          'legacy': true
        }
      ],
      [
        'transform-imports',
        {
          'lodash': {
            'preventFullImport': false,
            'transform': 'lodash/${member}'
          }
        }
      ],
      ['@babel/plugin-proposal-class-properties', { 'loose': true }],
    ],
    'presets': [
      '@babel/preset-env',
      '@babel/preset-react'
    ]
  }
}
```

**System:**
`npx sb@next info` is broken, so here's `npx envinfo` instead: 

using Docker container: `node:10`

```
root@dcc63b0f7709:/opt/app# npx envinfo
npx: installed 1 in 0.953s

  System:
    OS: Linux 4.19 Debian GNU/Linux 9 (stretch) 9 (stretch)
    CPU: (2) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 2.64 GB / 7.78 GB
    Container: Yes
    Shell: 4.4.12 - /bin/bash
  Binaries:
    Node: 10.18.0 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  Managers:
    Apt: 1.4.9 - /usr/bin/apt
  Utilities:
    Make: 4.1 - /usr/bin/make
    GCC: 6.3.0 - /usr/bin/gcc
    Git: 2.11.0 - /usr/bin/git
    Mercurial: 4.0 - /usr/bin/hg
    Subversion: 1.9.5 - /usr/bin/svn
  IDEs:
    VSCode: 1.48.0 - /root/.vscode-server/bin/db40434f562994116e5b21c24015a2e40b2504e6/bin/code
  Languages:
    Bash: 4.4.12 - /bin/bash
    Perl: 5.24.1 - /usr/bin/perl
    Python: 2.7.13 - /usr/bin/python
    Python3: 3.5.3 - /usr/bin/python3
```

**Additional context**

`ExampleComponent.js` looks like : 

```jsx
import React from 'react'
import PropTypes from 'prop-types'
import { Button } from 'semantic-ui-react'
import classnames from 'classnames'

import './ExampleComponent.scss'

export default function ExampleComponent ({
  className,
  mixClass,
  children,
  loading = false,
  title,
  icon,
  onSendClick,
  sendButtonLabel = 'Send',
  description,
  ...props
}) {
  return (
    <div
      className={classnames(
        'example-component',
        loading && 'example-component--loading',
        mixClass,
        mixClass && loading && `${mixClass}--loading`,
        className
      )}
      {...props}>
      <div
        className={classnames(
          'example-component__container',
          mixClass && `${mixClass}__container`,
        )}>
        <header
          className={classnames(
            'example-component__header',
            mixClass && `${mixClass}__header`,
          )}>
          {title}
        </header>

        <div
          className={classnames(
            'example-component__description',
            mixClass && `${mixClass}__description`,
          )}>
          {description}
        </div>

        <div
          className={classnames(
            'example-component__content',
            mixClass && `${mixClass}__content`,
          )}>
          {children}
        </div>

        <Button
          onClick={onSendClick}>
          {sendButtonLabel}
        </Button>
      </div>
    </div>
  )
}

ExampleComponent.propTypes = {
  className: PropTypes.string,
  mixClass: PropTypes.string,
  children: PropTypes.oneOfType([
    PropTypes.node,
    PropTypes.element
  ]),
  loading: PropTypes.bool,
  title: PropTypes.string,
  icon: PropTypes.string,
  onSendClick: PropTypes.func,
  sendButtonLabel: PropTypes.string,
  description: PropTypes.string,
}

```

**Comment by erouze** [comment]
> **Describe the bug**
> 
> * Upgraded from 5.3.x to 6.0.13
> * converted old `storysOf('blah blah blah')` to mdx format
> * `<Canvas><MyComponent /></Canvas>` renders MyComponent correctly, but
> * `<Canvas><Story name='blah blah'><MyComponent /></Story></Canvas>` results only `[Object object]` :
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Follow 5.x to 6.x upgrade guide
> 2. Creates story:
> 
> ```gfm
> import { Meta, Story, ArgsTable, Canvas, Description } from '@storybook/addon-docs/blocks'
> import { text, color } from '@storybook/addon-knobs'
> import { action } from '@storybook/addon-actions'
> 
> import ExampleComponent from './ExampleComponent'
> 
> <Meta
>   title="Getting Started/Writing Components/ExampleComponent"
>   component={ExampleComponent}
> />
> 
> # Example Component
> 
> <Description of={ExampleComponent} />
> 
> <Canvas>
>   <Story name="basic" args={{}}>
>     <ExampleComponent />
>   </Story>
> </Canvas>
> 
> <ArgsTable of={ExampleComponent} />
> ```
> 
> Results in:
> 
> ![image](https://user-images.githubusercontent.com/61225/90838697-b041f900-e394-11ea-8571-817a22a43f36.png)
> 
> but this story:
> 
> ```gfm
> import { Meta, Story, ArgsTable, Canvas, Description } from '@storybook/addon-docs/blocks'
> import { text, color } from '@storybook/addon-knobs'
> import { action } from '@storybook/addon-actions'
> 
> import ExampleComponent from './ExampleComponent'
> 
> <Meta
>   title="Getting Started/Writing Components/ExampleComponent"
>   component={ExampleComponent}
> />
> 
> # Example Component
> 
> <Description of={ExampleComponent} />
> 
> <Canvas>
>     <ExampleComponent />
> </Canvas>
> 
> <ArgsTable of={ExampleComponent} />
> ```
> 
> results in
> ![image](https://user-images.githubusercontent.com/61225/90839263-3c085500-e396-11ea-938d-1051a43b6ecf.png)
> 
> **Code snippets**
> 
> `package.json`
> 
> ```
> ...
>  "private": true,
>   "browserslist": "> .5% or last 2 versions",
>   "dependencies": {
>     "@babel/cli": "7.4.3",
>     "@babel/core": "7.4.3",
>     "@babel/plugin-proposal-class-properties": "7.4.0",
>     "@babel/plugin-proposal-decorators": "7.4.0",
>     "@babel/plugin-transform-runtime": "7.4.3",
>     "@babel/polyfill": "^7.0.0",
>     "@babel/preset-env": "7.4.3",
>     "@babel/preset-react": "7.0.0",
>     "@babel/register": "^7.6.2",
>     "@babel/runtime": "7.4.3",
>     "@ckeditor/ckeditor5-build-classic": "^17.0.0",
>     "@ckeditor/ckeditor5-react": "^2.1.0",
>     "@storybook/addon-a11y": "6.0.13",
>     "@storybook/addon-actions": "6.0.13",
>     "@storybook/addon-backgrounds": "6.0.13",
>     "@storybook/addon-docs": "6.0.13",
>     "@storybook/addon-knobs": "6.0.13",
>     "@storybook/addon-links": "6.0.13",
>     "@storybook/addon-storysource": "6.0.13",
>     "@storybook/addon-viewport": "6.0.13",
>     "@storybook/html": "6.0.13",
>     "@storybook/preset-scss": "1.0.2",
>     "@storybook/react": "6.0.13",
>     "@tinymce/tinymce-react": "^3.5.0",
>     "anysort": "^2.0.0",
>     "axios": "0.16.2",
>     "babel-eslint": "9.0.0",
>     "babel-loader": "8.0.5",
>     "babel-plugin-lodash": "3.2.11",
>     "babel-plugin-require-context-hook": "1.0.0",
>     "babel-plugin-transform-imports": "1.5.1",
>     "classnames": "^2.2.6",
>     "color": "3.1.0",
>     "core-js": "^3.6.5",
>     "cross-env": "5.2.0",
>     "cross-var": "1.1.0",
>     "css-loader": "2.1.0",
>     "debug": "3.1.0",
>     "djanjucks": "0.0.3",
>     "enzyme": "3.10.0",
>     "enzyme-adapter-react-16": "1.14.0",
>     "eslint": "^5.5.0",
>     "eslint-config-airbnb": "^17.1.0",
>     "eslint-config-prettier": "^3.0.1",
>     "eslint-config-react-app": "3.0.8",
>     "eslint-config-standard": "6.0.0",
>     "eslint-config-standard-react": "4.0.0",
>     "eslint-import-resolver-webpack": "^0.12.2",
>     "eslint-loader": "2.1.2",
>     "eslint-plugin-babel": "4.1.1",
>     "eslint-plugin-import": "^2.14.0",
>     "eslint-plugin-jsx-a11y": "^6.1.1",
>     "eslint-plugin-prettier": "^2.6.2",
>     "eslint-plugin-promise": "3.0.0",
>     "eslint-plugin-react": "^7.11.1",
>     "eslint-plugin-standard": "^4.0.1",
>     "fecha": "3.0.2",
>     "file-loader": "^0.11.2",
>     "flat": "^5.0.2",
>     "formstate": "^1.0.2",
>     "history": "^4.7.2",
>     "html-loader": "^0.5.5",
>     "html-react-parser": "^0.9.1",
>     "imports-loader": "0.7.0",
>     "jest": "24.9.0",
>     "jquery": "^3.5.1",
>     "jss": "^10.4.0",
>     "jss-preset-default": "^10.4.0",
>     "loadjs": "^4.2.0",
>     "lodash": "^4.17.11",
>     "markserv": "1.17.2",
>     "microevent": "^1.0.0",
>     "mini-css-extract-plugin": "0.6.0",
>     "mobx": "4.9.4",
>     "mobx-react": "^5.2.8",
>     "nconf": "0.10.0",
>     "node-sass": "4.11.0",
>     "npm-run-all": "4.1.5",
>     "nunjucks-loader": "^3.0.0",
>     "onchange": "5.2.0",
>     "postcss-loader": "2.1.5",
>     "postcss-preset-env": "6.5.0",
>     "prop-types": "15.5.6",
>     "react": "^16.6.3",
>     "react-dom": "^16.6.3",
>     "require-context.macro": "1.0.4",
>     "sass-loader": "7.1.0",
>     "semantic-ui-react": "^0.84.0",
>     "standard-version": "5.0.2",
>     "style-loader": "0.23.1",
>     "swig-loader": "^2.1.0",
>     "tinymce": "^5.2.0",
>     "url-loader": "^0.5.6",
>     "webpack": "4.39.3",
>     "webpack-bundle-analyzer": "3.3.2",
>     "webpack-cli": "3.3.8",
>     "webpack-config": "7.5.0",
>     "webpack-dev-server": "3.3.1",
>     "webpack-manifest-plugin": "2.0.4"
>   },
> ...
> ```
> 
> `tools/storybook/main.js`
> 
> ```
> const Config = require('webpack-config').default
> 
> const path = require('path')
> const CWD = process.cwd()
> const WEBPACK_CONFIG = path.join(CWD, 'tools', 'webpack', 'builder')
> 
> module.exports = {
>   stories: [
>     `../../src/**/*.stories.@(js|mdx)`,
>   ],
>   addons: [
>     '@storybook/addon-actions',
>     '@storybook/addon-knobs',
>     '@storybook/addon-a11y',
>     '@storybook/addon-backgrounds',
>     '@storybook/addon-viewport',
>     {
>       name: '@storybook/addon-docs',
>       options: { configureJSX: true },
>     },
>   ],
>   webpackFinal: async (config, { configType }) => {
>     const output = new Config()
>       .merge(config)
>       .extend(`${WEBPACK_CONFIG}/base/core__resolve.js`)
>       .extend(`${WEBPACK_CONFIG}/${configType.toLowerCase()}/aspect__styles.js`)
> 
>     config.externals = config.externals || {}
>     delete config.resolve.alias['react']
>     delete config.resolve.alias['react-dom']
> 
>     return output
>   }
> }
> ```
> 
> `babel.config.js`
> 
> ```
> module.exports = function (api) {
>   api.cache(true)
> 
>   return {
>     'plugins': [
>       '@babel/plugin-transform-runtime',
>       [
>         '@babel/plugin-proposal-decorators',
>         {
>           'legacy': true
>         }
>       ],
>       [
>         'transform-imports',
>         {
>           'lodash': {
>             'preventFullImport': false,
>             'transform': 'lodash/${member}'
>           }
>         }
>       ],
>       ['@babel/plugin-proposal-class-properties', { 'loose': true }],
>     ],
>     'presets': [
>       '@babel/preset-env',
>       '@babel/preset-react'
>     ]
>   }
> }
> ```
> 
> **System:**
> `npx sb@next info` is broken, so here's `npx envinfo` instead:
> 
> using Docker container: `node:10`
> 
> ```
> root@dcc63b0f7709:/opt/app# npx envinfo
> npx: installed 1 in 0.953s
> 
>   System:
>     OS: Linux 4.19 Debian GNU/Linux 9 (stretch) 9 (stretch)
>     CPU: (2) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
>     Memory: 2.64 GB / 7.78 GB
>     Container: Yes
>     Shell: 4.4.12 - /bin/bash
>   Binaries:
>     Node: 10.18.0 - /usr/local/bin/node
>     Yarn: 1.21.1 - /usr/local/bin/yarn
>     npm: 6.13.4 - /usr/local/bin/npm
>   Managers:
>     Apt: 1.4.9 - /usr/bin/apt
>   Utilities:
>     Make: 4.1 - /usr/bin/make
>     GCC: 6.3.0 - /usr/bin/gcc
>     Git: 2.11.0 - /usr/bin/git
>     Mercurial: 4.0 - /usr/bin/hg
>     Subversion: 1.9.5 - /usr/bin/svn
>   IDEs:
>     VSCode: 1.48.0 - /root/.vscode-server/bin/db40434f562994116e5b21c24015a2e40b2504e6/bin/code
>   Languages:
>     Bash: 4.4.12 - /bin/bash
>     Perl: 5.24.1 - /usr/bin/perl
>     Python: 2.7.13 - /usr/bin/python
>     Python3: 3.5.3 - /usr/bin/python3
> ```
> 
> **Additional context**
> 
> `ExampleComponent.js` looks like :
> 
> ```js
> import React from 'react'
> import PropTypes from 'prop-types'
> import { Button } from 'semantic-ui-react'
> import classnames from 'classnames'
> 
> import './ExampleComponent.scss'
> 
> export default function ExampleComponent ({
>   className,
>   mixClass,
>   children,
>   loading = false,
>   title,
>   icon,
>   onSendClick,
>   sendButtonLabel = 'Send',
>   description,
>   ...props
> }) {
>   return (
>     <div
>       className={classnames(
>         'example-component',
>         loading && 'example-component--loading',
>         mixClass,
>         mixClass && loading && `${mixClass}--loading`,
>         className
>       )}
>       {...props}>
>       <div
>         className={classnames(
>           'example-component__container',
>           mixClass && `${mixClass}__container`,
>         )}>
>         <header
>           className={classnames(
>             'example-component__header',
>             mixClass && `${mixClass}__header`,
>           )}>
>           {title}
>         </header>
> 
>         <div
>           className={classnames(
>             'example-component__description',
>             mixClass && `${mixClass}__description`,
>           )}>
>           {description}
>         </div>
> 
>         <div
>           className={classnames(
>             'example-component__content',
>             mixClass && `${mixClass}__content`,
>           )}>
>           {children}
>         </div>
> 
>         <Button
>           onClick={onSendClick}>
>           {sendButtonLabel}
>         </Button>
>       </div>
>     </div>
>   )
> }
> 
> ExampleComponent.propTypes = {
>   className: PropTypes.string,
>   mixClass: PropTypes.string,
>   children: PropTypes.oneOfType([
>     PropTypes.node,
>     PropTypes.element
>   ]),
>   loading: PropTypes.bool,
>   title: PropTypes.string,
>   icon: PropTypes.string,
>   onSendClick: PropTypes.func,
>   sendButtonLabel: PropTypes.string,
>   description: PropTypes.string,
> }
> ```

Were you able to figure out what was going on to have the [object object] show up in the Canvas? I'm having this same problem
