### ISSUE TITLE
storybook/preact: clears out and rerenders story on each knob change

### ISSUE THREAD

**Issue by dvoytenko** [storybookjs/storybook#12177]
**Is your feature request related to a problem? Please describe.**
For some components it's important to test changes in reaction to knob changes and not just rendering from the "clean slate". For instance, a Preact component's reaction to a prop change or a context change could cause performance problems which would otherwise be invisible if the component is rerendered from scratch. `@storybook/react` does not have this problem. But `@storybook/preact` forces the complete rerender. See [this code](https://github.com/storybookjs/storybook/blob/2de6e597c01db1d3ae5cbb023ba9591d8831c418/app/preact/src/client/preview/render.tsx#L35).

**Describe the solution you'd like**
Ideally, the normal Preact rendering would be used when knobs change w/o first clearing and unmounting of the component first. 

**Are you able to assist bring the feature to reality?**
May be. It looks like the change would otherwise be very simple.

**Comment by tmeasday** [comment]
Hi @dvoytenko I am not experienced with Preact, but in React, this is the relevant link here: https://github.com/storybookjs/storybook/blob/2de6e597c01db1d3ae5cbb023ba9591d8831c418/app/react/src/client/preview/render.tsx#L70-L72

Basically, when `forceReRender` is true, we should make sure (p)react does not remount the component. Hopefully an easy change to make

**Comment by dvoytenko** [comment]
@tmeasday that makes sense and looks like an easy fix. But I'm just noticing that this code also existed in Preact before and was "fixed" the other way [at some point](https://github.com/storybookjs/storybook/commit/dfce65df3aa369bce982902934bef7911d2c39c1#diff-1c5b1f58ac17d3362f80cffd129bf688R23). I can send a pull request, but not sure what reasons there were to change it before.

**Comment by dvoytenko** [comment]
Here's the fix: https://github.com/storybookjs/storybook/pull/12221. But I need some guidance with tests.

**Comment by shilman** [comment]
Great Caesar's ghost!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.0-alpha.11 containing PR #12221 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by dvoytenko** [comment]
Tried it. Seems to work as expected now. Thanks a lot!

**Comment by shilman** [comment]
@dvoytenko thank you! great job fixing it! 🙏
