### ISSUE TITLE
Composite storybooks display order is undefined

### ISSUE THREAD

**Issue by dsanders1234** [storybookjs/storybook#12188]
**Describe the bug**
When main.js has refs to other storybooks, the order that they show up in the list seems to be based on which one loads first rather than their definition order.  There does not seem to be documentation for how to control their order.

**To Reproduce**

1. Add multiple refs to create a composite storybook
2. Add stories to the storybook in the last ref, but don't add stories to the storybook in the first ref
3. When running the composite storybook, the last storybook in the ref list will show up first

**Expected behavior**
The order should not change or be based on documented behavior that can be controlled via configuration

**Comment by dsanders1234** [comment]
Still interested in a solution!

**Comment by dsanders1234** [comment]
Still interested!

**Comment by shilman** [comment]
What version of storybook? Do you have a repro repo you can share?

**Comment by dsanders1234** [comment]
I'm on version 6.0.21  I don't have a repro repo and this storybook is for business.  At the time I posted, the setup was pretty basic, just three mostly empty storybooks.  One didn't have stories in it.  Perhaps that is what causes the out of order render?  In any case, it shouldn't change order.

**Comment by nickvisut** [comment]
Hi there. I'm on 6.0.27 and it does appear that SBs show up in the composition menu UI in a random order that changes on each browser reload. I have 4 SBs and all contain stories (also a private repo so can't share).

I do notice that the "refs" used to configure external Storybooks is an object and not an array, so is it possible there isn't yet a way to specify an order?

**Comment by dsanders1234** [comment]
I believe that it is based on how fast each storybook gets loaded.  The ones that load faster get displayed first and it can be random.

**Comment by dsanders1234** [comment]
This is still an issue as far as I know

**Comment by MatthijsBe** [comment]
I have the same situation, and like to know if it's possible to change the order. Since we're working with the atomic design principle the order is somewhat important.  

I tried to add the option `storySort` to the preview.js, but this doesn't have any impact on the ref storybooks that get loaded.

Storybook version: 6.2.0-alpha.24

**Comment by shilman** [comment]
If you want this fixed, please upvote by adding a 👍 to the issue description. We use this to help prioritize!

**Comment by shilman** [comment]
We want to address this in 6.3. If you want to contribute to Storybook, we'll prioritize PR review for any fixes here. And if you'd like any help getting started, please jump into the #support channel on our Discord: https://discord.gg/storybook

**Comment by shilman** [comment]
ZOMG!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-alpha.13 containing PR #15527 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

**Comment by shilman** [comment]
Good golly!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.3.5 containing PR #15527 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```
