### ISSUE TITLE
Storyshots: Fix client-logger logging

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#12184]
Fix `_clientLogger.logger.warn` in places where Jest config might come up. The custom logger ate *all* the useful information in that stack trace.

For context see original comment by @aendrew in https://github.com/storybookjs/storybook/issues/10351#issuecomment-678001843_

**Comment by shobhitexe** [comment]
Hy is this issue still open would like to take this

**Comment by valentinpalkovic** [comment]
The Storyshots addon is officially deprecated and will be removed in Storybook 8.0. To help with the transition process, we've created a [migration guide](https://storybook.js.org/docs/writing-tests/storyshots-migration-guide) for the available options and common use cases.
