### ISSUE TITLE
Adding a link breaks docs page in composition host storybook

### ISSUE THREAD

**Issue by dvh91** [storybookjs/storybook#12194]
After upgrading from v5 to v6, and implementing the composition feature, it looks like links in the different docs page in the storybooks breaks the host storybook.

The error thrown:
```
Uncaught DOMException: Blocked a frame with origin "http://localhost:6002" from accessing a cross-origin frame.
    at Link (http://localhost:6002/vendors~main.2fda63c8d929018b1d7c.bundle.js:77355:88)
```

Removing the link in the story fixes the issue.

I've tried two ways of adding links to the docs page: one with markup and then other is jsx a href and both breaks the docs page in the host storybook.

**Comment by ndelangen** [comment]
> links in the different docs page

Could you explain this in a bit more detail?

**Comment by dvh91** [comment]
Let's say we have:
1. Storybook composition host
2. Package storybook

Try add a link (a href or markup link) in a mdx file in the package storybook.
Then open this docs page in the Storybook composition host, and you'll get the thrown error.

**Comment by ytakayanagi** [comment]
I've encountered the same problem. Here is a link that I have form my Icon.stories.mdx:
`A icon is a visual image and symbol. All icons from [Feather](https://feathericons.com/>) is available.`

I built it using the basic build command for docs: 
`"build-storybook-docs": "build-storybook --docs"`

The build succeeds, but I get a blank screen for my Icon story. Removing the link from the story page does make the page appear.

**Comment by ytakayanagi** [comment]
I found a fix for my issue. It was due to usage of build-storybook in Next.js. First of all you want to make sure the built files are placed in the `public` folder. Now instead of simply opening the `index.html` directly, you want to run Next.js locally and then access it.

For example in my case my build creates a folder called `storybook`in `public` folder.
After running Next.js locally, access `http://localhost:3000/storybook/index.html`.

Everything should work fine. I think we should add the build example in the example for Next.js.

**Comment by ndelangen** [comment]
Here's the responsible code:

https://github.com/storybookjs/storybook/blob/c1ff295246bd17822177a2c9afccfd9f0c93f154/lib/components/src/typography/DocumentFormatting.tsx#L78-L79

**Comment by ndelangen** [comment]
I think the link component should be changed to:

```js
const Link: FunctionComponent<any> = ({ href: input, children, ...props }) => {
  const isStorybookPath = /^\//.test(input);
  const isAnchorUrl = /^#.*/.test(input);

  const href = isStorybookPath ? `?path=${input}` : input;
  const target = isAnchorUrl ? '_self' : '_top';

  return (
    <a href={href} target={target} {...props}>
      {children}
    </a>
  );
};
```

@dvh91 would you be able to open a PR changing this?

**Comment by mmillet** [comment]
I resolved with this workaround:
```javascript
// Add into index.html
Object.defineProperty(window, "parent", {
  value: window
});
```

**Comment by sarahbethfederman** [comment]
Would love to see some progress on this! Not being able to link to external sites is a big limitation of docs. For instance, we'd like to be able to link to the component repo in bitbucket, but getting the above `Uncaught (in promise) DOMException: Blocked a frame with origin "null" from accessing a cross-origin frame.` error

**Comment by thomasoreilly** [comment]
I noticed that `foo@bar.com` in the MDX content can cause this CORS policy issue. FYI

**Comment by shilman** [comment]
Jeepers creepers!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.0-alpha.11 containing PR #13022 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Crikey!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.12 containing PR #13022 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```
