### ISSUE TITLE
Release notes page in dark mode should have a white background

### ISSUE THREAD

**Issue by stevezhu** [storybookjs/storybook#12193]
**Describe the bug**
The majority of the release notes page in storybook is unreadable in dark mode.

**To Reproduce**

1. Set theme to dark mode
2. Go to Settings -> Release Notes

**Expected behavior**
Release notes should have a white background.

**Screenshots**
![image](https://user-images.githubusercontent.com/4130171/90958908-2ada4980-e465-11ea-84ec-3d10f56c7333.png)

**Code snippets**
If applicable, add code samples to help explain your problem.

**System:**
Please paste the results of `npx sb@next info` here.

**Additional context**
On `@storybook/react@6.0.7`

**Comment by kylesuss** [comment]
Fixed on the frontpage! Thanks for reporting @stevezhu 👌
