### ISSUE TITLE
Storybook 6 opens wrong browser

### ISSUE THREAD

**Issue by noah-friedman** [storybookjs/storybook#12206]
**Describe the bug**
Running `BROWSER=chromium yarn storybook` still opens default browser.

**To Reproduce**

1. Set up new CRA typescript project
2. Run `npx sb init`
3. Running `BROWSER=chromium yarn start` opens Chromium
4. Running `BROWSER=chromium yarn storybook` opens default browser

**Expected behavior**
Should open storybook URL in Chromium. See #11014.

**Screenshots**
N/A

**Code snippets**
N/A

**System:**

Environment Info:

  System:
    OS: macOS 11.0
    CPU: (4) x64 Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz
  Binaries:
    Node: 14.5.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.6 - /usr/local/bin/npm
  Browsers:
    Chrome: 84.0.4147.135
    Safari: 14.0
  npmPackages:
    @storybook/addon-actions: ^6.0.16 => 6.0.16 
    @storybook/addon-essentials: ^6.0.16 => 6.0.16 
    @storybook/addon-links: ^6.0.16 => 6.0.16 
    @storybook/node-logger: ^6.0.16 => 6.0.16 
    @storybook/preset-create-react-app: ^3.1.4 => 3.1.4 
    @storybook/react: ^6.0.16 => 6.0.16 

**Additional context**
Issue occurs with `BROWSER=safari` as well.

**Comment by shilman** [comment]
@yannbf can you help with this?

**Comment by yannbf** [comment]
Hey @noah-friedman, thanks for opening an issue!  

Storybook uses [better-opn](https://github.com/ExiaSR/better-opn) to open the browser, which is a pretty similar, almost identical implementation than CRA.

I've tried to reproduce the issue but it worked fine for me.

**Opens my default browser:**
`yarn storybook`

**All opened the specific browsers successfully:**
`BROWSER="chromium" yarn storybook`
`BROWSER="safari" yarn storybook`
`BROWSER="firefox" yarn storybook`

**Comment by noah-friedman** [comment]
Weird, I've tried with the quotes as well but to no avail. It's a minor issue though, guess I'll just have it open the default for now.

**Comment by noah-friedman** [comment]
Update: After switching to Node v12.8.3 (previously on 14.something) and using npm instead of yarn I've stopped having this issue. I'm unsure if it was one or both of those things that fixed the problem, as I did them at the same time. Hopefully this can help anyone else having the same problem.

**Comment by tvanantwerp** [comment]
I'm also having it always open Chrome when my default is Firefox. I'm running macOS 12.0.1 and node 16.12.0.

**Comment by kilinkis** [comment]
also happening to me, always opens Chrome, my default is also Firefox. My system is: macOS 11.5.2 and node v14.16.0
