### ISSUE TITLE
Writing Docs - DocBlocks - Custom Addons Link not working

### ISSUE THREAD

**Issue by silvicardo** [storybookjs/storybook#12205]
This link is broken
<p>Custom <a href="../configure/user-interface#storybook-addons">addons</a> can also provide their own doc blocks.</p>

**Comment by jonniebigodes** [comment]
@silvicardo thank for bringing this to our attention and sorry for the delay in updating the documentation.

I've created a pull request addressing the issue and will soon be merged.

Stay safe

**Comment by silvicardo** [comment]
No problem. Nice work! Have a nice weekend!
