### ISSUE TITLE
storybook fails on fresh installation in a create react app

### ISSUE THREAD

**Issue by ameerthehacker** [storybookjs/storybook#12218]
<img width="724" alt="Screenshot 2020-08-24 at 8 06 17 PM" src="https://user-images.githubusercontent.com/15448192/91057888-6e8ba980-e645-11ea-8d7d-cf6de8918413.png">

**Comment by Guria** [comment]
see #12217

**Comment by shilman** [comment]
Closing as dupe to #12217
