### ISSUE TITLE
Props not showing up in docs when slot with same name is defined (Vue)

### ISSUE THREAD

**Issue by puyt** [storybookjs/storybook#12224]
**Describe the bug**
The props aren't displayed in the docs when a slot with the same name is defined.
See the example and screenshot below. 

Note that this is just a simple example and not the real use-case.
The real use-case is that we have props to easily customize a component (icon, label & description) and the slots are used when text (prop) isn't enough to customize the component and an user wants customize the html for that specific part (e.g. multi-line, bold text, colored text).
 
**Expected behavior**
Both the props and slots should be visible in the docs page.

**Screenshots**
![image](https://user-images.githubusercontent.com/3668615/91083672-f627e700-e64a-11ea-837c-1a7addb65085.png)

**Code snippets**
```jsx
// BButton.vue
<template>
    <button>
        <!-- @slot label -->
        <slot name="label">{{ label }}</slot>
    </button>
</template>

<script>
  export default {
      props: {
          label: {
              type: String,
              default: 'label',
          },
      },
  };
</script>
```

```mdx
// BButton.stories.mdx
import { Meta, Story, Props, Preview } from '@storybook/addon-docs/blocks';
import BButton from './BButton.vue';

<Meta title='Components/BButton' component={BButton} />


# BButton
<Preview>
    <Story name="Default">
    {{
        components: { BButton },
        template: '<b-button />',
    }}
    </Story>
</Preview>

## Props, Events & Slots
<Props of={BButton} />
```

**System:**

```
Environment Info:

  System:
    OS: Linux 5.4 Ubuntu 19.10 (Eoan Ermine)
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
  Binaries:
    Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
    npm: 6.12.0 - ~/.nvm/versions/node/v12.13.0/bin/npm
  Browsers:
    Chrome: 84.0.4147.125
    Firefox: 78.0.2
  npmPackages:
    @storybook/addon-actions: ^6.0.16 => 6.0.16
    @storybook/addon-docs:  ^6.0.16 => 6.0.16
    @storybook/addon-essentials:  ^6.0.16 => 6.0.16
    @storybook/addon-links:  ^6.0.16 => 6.0.16
    @storybook/vue:  ^6.0.16 => 6.0.16 

```

**Comment by shilman** [comment]
Closing as duplicate to https://github.com/storybookjs/storybook/issues/12850 (thanks @braddialpad!)
