### ISSUE TITLE
Installation fails in an existing Angular 9 project

### ISSUE THREAD

**Issue by vadal** [storybookjs/storybook#12232]
**Describe the bug**
When I run `npx sb init` or `npx -p @storybook/cli sb init` in an existing angular 9 project, I get the following error:
Cannot read property 'build' of undefined.

**To Reproduce**

1. Open terminal inside an angular9 project
2. Run `npx sb init` or `npx -p @storybook/cli sb init` command

**Expected behavior**
Installation succeeds

**Screenshots**
<img width="991" alt="error" src="https://user-images.githubusercontent.com/4260120/91148639-9e2cc700-e6c2-11ea-9da0-1537a76cf450.png">

**System:**
OS: macOS Mojave 10.14.6
CPU: (8) x64 Intel(R) Core(TM) i7-3635QM CPU @ 2.40GHz
Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.0.2 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
Browsers:
    Chrome: 84.0.4147.135
    Firefox: 79.0
    Safari: 13.1.2
npmGlobalPackages:
    @storybook/cli: 6.0.16

**Additional context**
- Angular version: 9.1.6

Can you please help? I can't find any workaround.

**Comment by vadal** [comment]
Can please someone help?
I haven't got an answer neither here nor in support chat. It seems that support team ignores my issue.

**Comment by Marklb** [comment]
Can you provide a repo that reproduces the issue? That error looks like your default project in `angular.json` does not have the `build` property at `projects.default-project-name.architect.build`.

Since no configuration details are provided, my best guess is that you are maybe using Nx? If that is the case, you may find steps to help here: https://nx.dev/angular/plugins/storybook/overview

**Comment by JamboBuenna** [comment]
Also getting the same issue. I followed the install on an Ionic Project and straight Angular project both on ng9. I did this initially using the standard tutorial & then also the tutorial [here](https://www.learnstorybook.com/intro-to-storybook/angular/en/get-started/). I got the invalid hook calls errors other are getting, it seemed to be in this case the app wanted to instanciate React but no react instance was installed.

![image](https://user-images.githubusercontent.com/2864327/93470333-a6ef7200-f8e9-11ea-8eac-91e22e7687fb.png)

There were also a number more errors.

![image](https://user-images.githubusercontent.com/2864327/93470418-cbe3e500-f8e9-11ea-83c7-5160bed12fb7.png)

We're not using an nx repro.

**Comment by vadal** [comment]
@Marklb thank you for the answer. I don't use an nx repo either.
I was able to make it work by adding the architect property in angular.json

**Comment by shilman** [comment]
Good golly!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.0-alpha.13 containing PR #13558 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

**Comment by shilman** [comment]
Olé!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.15 containing PR #13558 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```
