### ISSUE TITLE
Babel-loader installed by Storybook but requested to be removed by Create-React-App

### ISSUE THREAD

**Issue by angelod1as** [storybookjs/storybook#12245]
**Describe the bug**
I have a `create-react-app` app with `storybook`. Developing my storybook, all runs fine. When I run `yarn start`, React Scripts gives me the following error:

```
There might be a problem with the project dependency tree.
It is likely not a bug in Create React App, but something you need to fix locally.

The react-scripts package provided by Create React App requires a dependency:

  "babel-loader": "8.0.6"

Don't try to install it manually: your package manager does it automatically.
However, a different version of babel-loader was detected higher up in the tree:

  /Users/angelodias/GIT/personal/submissions/clients/front/node_modules/babel-loader (version: 8.1.0)

Manually installing incompatible versions is known to cause hard-to-debug issues.

If you would prefer to ignore this check, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
That will permanently disable this message but you might encounter other issues.
````

I follow their suggestions and remove `babel-loader` from my deps. That way, when I try to run Storybook... it gives me an error saying that `babel-loader` is missing, so I go and add it...

This happens in a never-ending cycle, removing and adding. I don't want to `SKIP_PREFLIGHT_CHECK` because that suppresses all possible errors.

**To Reproduce**

1. Create a new React App with `create-react-app`
2. Run it with `yarn start`
3. Stop the process, add `storybook`
4. Run `yarn storybook`
5. Stop the process and try to run `yarn start`. There's an error here.
6. Do as the instructions says and try to run `yarn storybook`.
7. There's another error here.
9. Add `babel-loader`.
10. Repeat from 4 to 10.

**Expected behavior**
`yarn start` and `yarn storybook` should run without bumping into each other.

**System:**

```
Environment Info:

  System:
    OS: macOS 10.15.5
    CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
  Binaries:
    Node: 12.14.1 - /usr/local/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 84.0.4147.135
    Firefox: 79.0
    Safari: 13.1.1
  npmPackages:
    @storybook/addon-actions: ^6.0.16 => 6.0.16
    @storybook/addon-essentials: ^6.0.16 => 6.0.16
    @storybook/addon-links: ^6.0.16 => 6.0.16
    @storybook/node-logger: ^6.0.16 => 6.0.16
    @storybook/preset-create-react-app: ^3.1.4 => 3.1.4
    @storybook/react: ^6.0.16 => 6.0.16
```

**Comment by shilman** [comment]
cc @mrmckeb

**Comment by merceyz** [comment]
The check `create-react-app` uses for this is IMO completly pointless, as long as they declare their dependencies correctly (which they do at the time of writing) they'll get the correct version they want anyways.

To work around this you can make sure you declare `babel-loader@8.0.6`
