### ISSUE TITLE
ts-jest preset = storyshots found 0 stories

### ISSUE THREAD

**Issue by Sun-2** [storybookjs/storybook#12242]
**Describe the bug**
Storyshots work fine on their own. However, when ts-jest is added (with the `ts-jest` preset in `jest.config.js`), then `yarn jest` throws with `storyshots found 0 stories`

Without ts-jest, there are some syntax warnings thrown, however things do work.

[REPO LINK](https://github.com/Sun-2/next-strapi/tree/broken-ts-jest-storyshot/next)

**To Reproduce**

1. Clone the repo
2. `cd next-strapi/next && yarn && yarn jest`

-----
1. Now, go to `next-strapi/next/jest.config.js`. Comment out the `preset` setting. 
2. `yarn jest` - everything works, snapshots are captured, although some warnings about syntax errors are thrown.

**Screenshots**

No preset:
![image](https://user-images.githubusercontent.com/70162247/91185175-c67deb00-e6ed-11ea-9be5-e9dfe4a3286f.png)

Preset active:
![image](https://user-images.githubusercontent.com/70162247/91185241-da295180-e6ed-11ea-9c91-a9087f45bea2.png)

**System:**
```
  System:
    OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor
  Binaries:
    Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.3/bin/npm
  Browsers:
    Chrome: 84.0.4147.125
    Firefox: 79.0
  npmPackages:
    @storybook/addon-actions: ^6.0.17 => 6.0.17 
    @storybook/addon-essentials: ^6.0.17 => 6.0.17 
    @storybook/addon-links: ^6.0.17 => 6.0.17 
    @storybook/addon-storyshots: ^6.0.17 => 6.0.17 
    @storybook/react: ^6.0.17 => 6.0.17 
```

**Extra: **
With the preset, on
`node_modules/@storybook/addon-storyshots/dist/api/index.js`
```
 var data = storybook
        .raw()
```
The above returns an empty array.

**Comment by Sun-2** [comment]
Changing `typescript.json`'s `jsx:"preserve:" to `jsx: "react"` fixes this issue.

**Comment by RomkeVdMeulen** [comment]
@Sun-2 Thanks for sharing that workaround! I've been pulling my hair out: seemingly random changes to my code throw the `storyshots found 0 stories` error.

**Comment by nigelsim** [comment]
For me the issue was that glob matching worked differently in Storybook vs Storyshots. Had to change `.storybook/main.js` from
```
module.exports = {
    stories: ['../src/**/*.stories']
};
```

to

```
module.exports = {
    stories: ['../src/**/*.stories.ts']
};
```

**Comment by shilman** [comment]
cc @yannbf @ndelangen ☝️

**Comment by ndelangen** [comment]
correct me if I'm wrong but:
```
stories: ['../src/**/*.stories']
```
only matches files with a `.stories` extension? which is not what we tell users to do.

I think this is the underlying change:
https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#correct-globs-in-mainjs

**Comment by RomkeVdMeulen** [comment]
FYI, the glob I'm using in `main.js`: `"../src/**/*.stories.@(ts|tsx)"`. This is probable a separate issue to these `ts-jest` problems.

**Comment by nigelsim** [comment]
I'm not sure I was strictly following a StoryBook guide when I put those
globs in. I was just following module naming convention which omits the
extension. This just happened to work in the stand alone StoryBook.

**Comment by ouranos588** [comment]
Hi, 

Just to let know that I'm facing the same issue using ts-jest.
my repository is the following : https://github.com/ouranos588/oura-node-editor

**Comment by explodingcamera** [comment]
I solved this issue by using babel and adding @babel/preset-react for normal .js files

**Comment by israeldax** [comment]
I use CRA setup. The workaround is my default config. Storybook runs ok, but storyshots finds nothing. Tried everything but nothing works.

**Comment by thielium** [comment]
I only found time to dig into part of the solution, but I found that using `export default` in my `main` resulted in `0 storyshots`. However, if I used `module.exports = myConfiguration`, things worked fine.

On my end, it probably means that my `babel-jest` isn't wired up quite right.

In Storybook, for some reason `jest.requireActual` is not resolving the main configuration file's exports. Storybook then behaves as though you did not specify any configuration file. Though it's almost certainly my configuration, maybe it would help to warn when no `main` is supplied?

**Comment by ndelangen** [comment]
> but I found that using export default in my main

Do we document this anywhere?, because that's simply the wrong way of defining `main.js`'s contents.

**Comment by thielium** [comment]
From the docs, as far as I can tell, all the examples to have a `module.exports` block.

I'm transpiling `main.ts -> main.js` (I know that voids my warranty when) -- it's probably configuration issue in my case. 

More generally, though, I do think it would be helpful to warn when no configuration is detected, since that's almost certainly a mistake.

**Comment by ndelangen** [comment]
We do warn the user there are 0 stories detected right?

**Comment by bread-pool** [comment]
I recently ran into this issue as well.

After hours of debugging, I found I forgot to add `import React from 'react';` to the top of my React-based story🤦‍♂️

Adding that line immediately got StoryShots to recognize the story even though StoryBook itself recognizes the story without that line when I start up StoryBook.

Hope this helps someone and saves someone else's time!

**Comment by thielium** [comment]
> We do warn the user there are 0 stories detected right?

It's true! And that was helpful. However, that could be from a malformed blob versus an absent config (in fact, that's what I assumed the problem was for quite awhile). In this case, it would've saved me time to know that my configuration wasn't even being read. I can't speak to whether it would save others time, just myself; maybe it doesn't make sense to generalize.

**Comment by ndelangen** [comment]
The future of storyshots is the test-runner:
https://storybook.js.org/docs/react/writing-tests/test-runner#page-top

And use the play function for expectations:
https://storybook.js.org/docs/react/writing-stories/play-function#page-top

We will not be making any improvement / changes to storyshots.
