### ISSUE TITLE
Typescript type "Story" not compactible with examples for testing

### ISSUE THREAD

**Issue by valentinpalkovic** [storybookjs/storybook#12247]
**Describe the bug**
Let's assume we define a very straightforward story:

```typescript
import type { Story, Meta } from "@storybook/react";
import React from "react";
import { PageHeadline } from ".";

export default {
  title: "Atoms/PageHeadline",
  component: PageHeadline,
  argTypes: {
    children: { control: "text" },
  },
} as Meta;

const Template: Story<{ children: string }> = (args) => (
  <PageHeadline {...args} />
);

export const Basic = Template.bind({});
Basic.args = { children: "I am a very special headline" };
```

And I want to test it:

```typescript
import { Basic } from "./index.stories";
import { render } from "../../../utils/test-utils";
import React from "react";

describe("PageHeadline", () => {
  it("should match snapshot", () => {
    const { container } = render(<Basic {...Basic.args} />, {});
    expect(container).toMatchSnapshot();
  });
});
```

Then I get the following error:

```typescript
(alias) const Basic: Story<{
    children: string;
}>
import Basic
Type '{} | { children?: string | undefined; }' is not assignable to type 'IntrinsicAttributes & { children: string; }'.
  Property 'children' is missing in type '{}' but required in type '{ children: string; }'.ts(2322)
index.stories.tsx(13, 25): 'children' is declared here.
```

If I follow one of your test examples, then I will get a type error, because first, `Basic.args` can be undefined, and second, all properties of `Basic.args` are optional. In general, I can clearly understand the decision to type `args` as it is now. But for testing purposes, it makes the developer experience a bit harder. If I make the assumption, that all properties are already defined correctly in our story, then I can apply in my test file a fix like this to avoid typescript type errors:

```typescript
type Props = NonNullable<Required<typeof Basic["args"]>>;
...
it("should match snapshot", () => {
    const { container } = render(<Basic {...(Basic.args as Props)} />, {});
    expect(container).toMatchSnapshot();
});
...
```

But of course, this solution will not always work, because click handlers, for example for `onClick` will not be defined in the story args, because it will be handled by an addon.

**Question**:
The typing of `args` in general is valid. But how can we avoid type errors in tests? How could we reuse the `args` definition in our test file to make sure, which properties are already defined in the story? The make-every-property-partial nature of `args` makes it very difficult to achieve proper typings in our tests.

**Expected behavior**
A clear and straightforward DX to reuse stories in tests, without the need for overwriting types of the component `args` type.

**Screenshots**

**Story:**
![image](https://user-images.githubusercontent.com/5889929/91258909-bf96bd00-e76d-11ea-9316-9c1216a8d685.png)

**Test:**
![image](https://user-images.githubusercontent.com/5889929/91258946-cfae9c80-e76d-11ea-9679-1589ddd21a65.png)

**Error:**
![image](https://user-images.githubusercontent.com/5889929/91259011-ea811100-e76d-11ea-87ac-749182515c38.png)

**Temporary solution:**
![image](https://user-images.githubusercontent.com/5889929/91259051-02f12b80-e76e-11ea-96e4-f9f1bb818a34.png)

**System:**
```
System:
    OS: Linux 4.19 Ubuntu 19.10 (Eoan Ermine)
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
Binaries:
    Node: 14.6.0 - ~/.nvm/versions/node/v14.6.0/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v14.6.0/bin/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v14.6.0/bin/npm
npmPackages:
    @storybook/addon-actions: 6.0.16 => 6.0.16 
    @storybook/addon-controls: ^6.0.16 => 6.0.16 
    @storybook/addon-docs: ^6.0.16 => 6.0.16 
    @storybook/addon-links: 6.0.16 => 6.0.16 
    @storybook/addons: 6.0.16 => 6.0.16 
    @storybook/preset-create-react-app: 3.1.4 => 3.1.4 
    @storybook/react: 6.0.16 => 6.0.16
Typescript: "4.0.2"
```

**Comment by shilman** [comment]
@gaetanmaisse @tooppaaa any thoughts on this one?

**Comment by jchild3rs** [comment]
The `args` get wrapped in `Partial` which makes everything conditional, therefore breaks required props in testing.

**Comment by fefrontend** [comment]
This is my workaround:

```ts
interface IProps {
  children: string;
}

export default {
  title: "...",
  component: PageHeadline,
} as Meta<IProps>;

const Template: Story<IProps> = args => <PageHeadline {...args} />;

...

render(<Basic {...(Basic.args as IProps)} />);
```

**Comment by davidcai** [comment]
This is my workaround:

```ts
interface IProps {
  children: string;
}

export default {
  title: "...",
  component: PageHeadline,
} as Meta<IProps>;

const Template: Story<IProps> = args => <PageHeadline {...args} />;

...

render(<Basic {...(Basic.args as IProps)} />);
```

**Comment by axelnormand** [comment]
I'd also love to have any easy way of sharing the component and args with jest and typescript

Here's how i do it by exporting the typed args themselves (and using `excludeStories`), to then use in jest

```
// Test.stories.tsx
import {Test, Props} from './Test';

const meta: Meta = {
  title: 'Test',
  component: Test,
  excludeStories: /^[a-z]/,
};
export default meta;

const Template: Story<Props> = (args) => <Test {...args} />;

export const TestExample = Template.bind({});
export const testExampleArgs: Props = {
  name: "Hello",
};
TestExample.args = testExampleArgs;

// Test.test.tsx
import { TestExample, testExampleArgs } from './Test.stories';

it('renders name', () => {
  render(<Test {...testExampleArgs} />);
  expect(screen.getByText(/Hello/)).toBeInTheDocument();
});
```

**Comment by rpowis** [comment]
Same. I just stumbled into this issue while writing stories and tests for components with required props in TS. Has there been any further thinking on the best way to handle this?

**Comment by shilman** [comment]
Here's the current best solution to reusing your stories in test, if you haven't seen it yet: https://storybook.js.org/addons/@storybook/testing-react

(Also https://storybook.js.org/addons/@storybook/testing-vue etc.)

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
