### ISSUE TITLE
Support ArgsTables with only a subset of available props in mdx stories.

### ISSUE THREAD

**Issue by mattdarveniza** [storybookjs/storybook#12248]
**Is your feature request related to a problem? Please describe.**
Often when writing mdx stories, it's desirable to walk through a series of uses, starting with a basic example and then going on to more complex examples.

**Describe the solution you'd like**
It would be amazing if we could expose only the desired props and controls for that specific story, rather than everything all the time.

In the screenshot below, I really only want to talk to the `direction` and `space` props, for which I've provided args in the Story like so:

```
<Story name="Vertical List" args={{ direction: 'vertical', space: 1 }}>
...
</Story>

<ArgsTable story="Vertical List" />
```

![Screen Shot 2020-08-26 at 5 05 10 pm](https://user-images.githubusercontent.com/946261/91271941-4ffcee00-e7be-11ea-9c57-15c81269e9cb.png)

What I'd really like is for the option to only show Args in an ArgsTable for the args listed in the story. Alternatively I'd also happily just take a list of values to show or hide, or even just as part of the `ArgTypes` api, have an option to set some arg rows as `argTypes={{ padding: false }}` or something similar to explicitly hide them.

**Describe alternatives you've considered**
Right now I don't really see any way of achieving this with the current featureset, and showing a bunch of extraneous args is pretty undesirable

**Are you able to assist bring the feature to reality?**
If there's appetite to support this, I'd be more than happy to build it with a bit of pointing in the right direction

**Comment by shilman** [comment]
try:

```js
argTypes: {
  padding: { table: { disable: true } }
}
```

it's a little verbose; we might introduce a shorter syntax later.

**Comment by mattdarveniza** [comment]
Great. Is that documented anywhere? If not would you be open to a PR documenting it in https://storybook.js.org/docs/react/writing-docs/doc-blocks#customizing ?

**Comment by shilman** [comment]
It's documented here: https://github.com/storybookjs/storybook/blob/next/addons/controls/README.md#how-can-i-disable-controls-for-certain-fields-on-a-particular-story

But we're always open to PRs for documentation or any other aspect of Storybook
