### ISSUE TITLE
Does addon-storyshots-puppeteer support code coverage?

### ISSUE THREAD

**Issue by danvk** [storybookjs/storybook#12243]
**Describe the bug**

I created a `Storyshots.test.ts` file like so:

```ts
import initStoryshots from '@storybook/addon-storyshots';
import {imageSnapshot} from '@storybook/addon-storyshots-puppeteer';

initStoryshots({
  suite: 'Puppeteer storyshots',
  test: imageSnapshot({
    storybookUrl: 'file:///Users/danvk/github/project/ts/storybook-static',
  }),
  storyNameRegex: /^((?!.*?DontTest).)*$/,
});
```

I filled out the `storybook-static` directory by running `build-storybook`.

When I run:

    jest --coverage src/Storyshots.test.ts

It takes 30-60 seconds and produces a beautiful collection of PNG snapshots of all my stories in `src/__image_snapshots__`. It also lists all my stories as tests and shows them as having run successfully (green checkmarks).

Unfortunately, the code coverage numbers that it reports don't seem to reflect the code that it must have run to produce those screenshots. The coverage results I see are much lower than expected. They reflect what you'd get if you imported all the stories but didn't render any of them. For example:

![image](https://user-images.githubusercontent.com/98301/91198987-46468e00-e6cb-11ea-9d16-36e5faa33e3b.png)

when I know that there are stories (with screenshots) that include this component.

If this isn't expected to work, that's fine! I'd just like to know. And also whether there are any known workarounds.

**To Reproduce**

1. Create a `Storyshots.test.ts` file as above.
2. Run `build-storybook` to produce a static storybook
3. Run `jest --coverage Storyshots.test.ts` to produce screenshots
4. Observe that the code coverage numbers do not reflect the code that was run in stories.

**Expected behavior**
I would have expected the code coverage numbers to reflect code that was run while taking the screenshots.

**Screenshots**
(See above)

**Code snippets**
(See above)

**System:**
Please paste the results of `npx sb@next info` here.

```
Environment Info:

  System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
  Binaries:
    Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
    Yarn: 1.17.3 - ~/.yarn/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.16.3/bin/npm
  Browsers:
    Chrome: 84.0.4147.135
    Firefox: 77.0.1
    Safari: 13.1.1
  npmPackages:
    @storybook/addon-actions: ^6.0.16 => 6.0.16
    @storybook/addon-knobs: ^6.0.16 => 6.0.16
    @storybook/addon-links: ^6.0.16 => 6.0.16
    @storybook/addon-storyshots: ^6.0.16 => 6.0.16
    @storybook/addon-storyshots-puppeteer: ^6.0.16 => 6.0.16
    @storybook/addon-storysource: ^6.0.16 => 6.0.16
    @storybook/addons: ^6.0.16 => 6.0.16
    @storybook/react: ^6.0.16 => 6.0.16
```

**Additional context**

If it's relevant, I get these warnings when running `jest`:

```
$ jest --coverage src/Storyshots.test.ts
(node:90408) DeprecationWarning: CSF .story annotations deprecated; annotate story functions directly:
- StoryFn.story.name => StoryFn.storyName
- StoryFn.story.(parameters|decorators) => StoryFn.(parameters|decorators)
See https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#hoisted-csf-annotations for details and codemod.
  console.warn
    Unexpected error: TypeError: window.URL.createObjectURL is not a function

      at Object.warn (node_modules/@storybook/client-logger/dist/index.js:53:73)
      at node_modules/@storybook/core/dist/client/preview/loadCsf.js:149:34
          at Array.forEach (<anonymous>)
      at node_modules/@storybook/core/dist/client/preview/loadCsf.js:142:20
          at Array.forEach (<anonymous>)
      at node_modules/@storybook/core/dist/client/preview/loadCsf.js:141:12
      at ConfigApi.configure (node_modules/@storybook/client-api/dist/config_api.js:26:7)

  console.warn
    Unexpected error: SyntaxError: Cannot use import statement outside a module

      at Object.warn (node_modules/@storybook/client-logger/dist/index.js:53:73)
      at node_modules/@storybook/core/dist/client/preview/loadCsf.js:149:34
          at Array.forEach (<anonymous>)
      at node_modules/@storybook/core/dist/client/preview/loadCsf.js:142:20
          at Array.forEach (<anonymous>)
      at node_modules/@storybook/core/dist/client/preview/loadCsf.js:141:12
      at ConfigApi.configure (node_modules/@storybook/client-api/dist/config_api.js:26:7)
```

**Comment by shilman** [comment]
I prototyped a coverage addon for Storybook once upon a time. I used `storyshots`--not `storyshots-puppeteer`--and it worked as expected.

**Comment by nkov** [comment]
+1, bumping thread as this would be a cool feature. @shilman is your addon hosted anywhere we could take a look? or some implementation suggestions for someone that wants to take a crack at supporting this?

**Comment by danvk** [comment]
Almost two years later, I finally found a solution for this! The trick was to directly instrument my storybook webpack bundle using Istanbul. You can do this by adding [@jsdevtools/coverage-istanbul-loader](https://jstools.dev/coverage-istanbul-loader/) to your Storybook webpack config:

```ts
// .storybook/main.js
module.exports = {
  // ...
  webpackFinal: async config => {
    config.module.rules.push({
      test: /\.(ts|tsx)$/,
      use: [
        '@jsdevtools/coverage-istanbul-loader',
        {
          loader: require.resolve('ts-loader'),
          options: {
            configFile: path.resolve(__dirname, '..', 'client', './tsconfig.webpack.json'),
            transpileOnly: true,
          },
        },
      ],
    });
    config.resolve.extensions.push('.ts', '.tsx');

    config.mode = 'development';
    config.devtool = 'source-map';
    console.log(config);
    return config;
  },
};
```

Then you can run your story via addon-storyshots-puppeteer and extract the coverage data from Istanbul's global counter:

```ts
initStoryshots({
    test: puppeteerTest({
      storybookUrl,
      async customizePage(page) {
        page.on('console', msg => console.log('PAGE LOG:', msg.text()));
      },
      async testBody(page, options) {
        const id = (options.context as any).id as string;
        console.log('Running', id);
        const outputPng = './.nyc_output/' + id + '.png';
        await page.screenshot({fullPage: true, path: outputPng});
        const coverage = await page.evaluate('window.__coverage__');
        const outputFile = './.nyc_output/' + id + '.json';
        await fs.promises.writeFile(outputFile, JSON.stringify(coverage, null, 2), {
          encoding: 'utf-8',
        });
      },
    }),
  });
```

Run that via:

```
mkdir .nyc_output
npm run jest ...path to your storyshots jest config...
nyc report --reporter=html -x '**/__stories__/**'
```

and then view your beautiful coverage data in `coverage/index.html`.

**Comment by ndelangen** [comment]
The future of storyshots is the test-runner:
https://storybook.js.org/docs/react/writing-tests/test-runner#page-top

And use the play function for expectations:
https://storybook.js.org/docs/react/writing-stories/play-function#page-top

We will not be making any improvement / changes to storyshots.
