### ISSUE TITLE
Addon actions won't display its standard “log” message and the actual component event handler to update the UI

### ISSUE THREAD

**Issue by JanettaH** [storybookjs/storybook#12256]
**Describe the bug**
I can't get my event handling function to do its logic to update the UI and storybook's addon - actions() to log the output.

**To Reproduce**

1. Create a function
2. Make the component use automatically matching args
3. Fire an action and execute function inside of a component
4. The action log appears, but the function doesn't execute

**Expected behavior**
Addon actions should display its standard “log” message and the actual component event handler to update the UI.

**Screenshots**

![image](https://user-images.githubusercontent.com/32257620/91303088-2b9a1500-e7b0-11ea-991c-e2378721eb2b.png)

**Code snippets**

![image](https://user-images.githubusercontent.com/32257620/91302866-c9d9ab00-e7af-11ea-8262-37844a1dc480.png)

**System:**
Environment Info:

  System:
    OS: macOS 10.15.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 12.18.3 - /usr/local/bin/node
    npm: 6.14.6 - /usr/local/bin/npm
  Browsers:
    Chrome: 84.0.4147.135
    Edge: 84.0.522.63
    Firefox: 79.0
    Safari: 13.1.2
  npmPackages:
    @storybook/addon-a11y: 6.0.16 => 6.0.16 
    @storybook/addon-essentials: 6.0.16 => 6.0.16 
    @storybook/addon-jest: 6.0.16 => 6.0.16 
    @storybook/addon-knobs: 6.0.16 => 6.0.16 
    @storybook/addon-links: 6.0.16 => 6.0.16 
    @storybook/addons: ^6.0.16 => 6.0.16 
    @storybook/preset-create-react-app: ^3.1.4 => 3.1.4 
    @storybook/react: 6.0.16 => 6.0.16 
    @storybook/theming: 6.0.16 => 6.0.16

**Comment by shilman** [comment]
Typo? `agrTypes` => `argTypes`

**Comment by JanettaH** [comment]
> Typo? `agrTypes` => `argTypes`

Won't fix the issue.

**Comment by henrycity** [comment]
I was trying this out and doesn't work either
```jsx
const handleClick = (e) => {
    args.onClick(e);
    toggleSelected(true);
}

return <Component onClick={handleClick} />
```

If I remove `toggleSelected(true);`, I can see the log. If both are there and I click very fast, it shows the log and then disappears immediately.

It is similar to this question I found https://stackoverflow.com/questions/59669031/i-want-storybook-addon-actions-to-display-its-standard-log-message-and-the-act

**Comment by ndelangen** [comment]
This issue is old, and doesn't have a reproduction, and thus I'm closing it.
I kind of assume the issue has been resolved at some point.
