### ISSUE TITLE
react mdx example fails when adding second storybook config to project

### ISSUE THREAD

**Issue by patsplat** [storybookjs/storybook#12253]
**Describe the bug**
Encountered an import error when adding a second storybook config with `--story-format mdx` to an existing storybook react installation.

**To Reproduce**

1. `npx create-react-app my-app`
2. `cd my-app`
3. `npx sb init`
4. `mkdir nested-config`
5. `cd nested-config`
6. `npx sb init -s -t react --story-format mdx`
7. `cd ..`
8. `yarn storybook -c nested-config/.storybook`
9. See Error: `Element type is invalid`

**Expected behavior**
Storybook to start without errors

**Screenshots**
![image](https://user-images.githubusercontent.com/178626/91295884-bd326400-e769-11ea-9d5b-b96fad5364cb.png)

**System:**
```
Environment Info:

  System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
    Yarn: 1.21.1 - ~/.yarn/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v10.16.3/bin/npm
  Browsers:
    Chrome: 84.0.4147.135
    Safari: 13.1.2
  npmPackages:
    @storybook/addon-actions: ^6.0.18 => 6.0.18 
    @storybook/addon-essentials: ^6.0.18 => 6.0.18 
    @storybook/addon-links: ^6.0.18 => 6.0.18 
    @storybook/node-logger: ^6.0.18 => 6.0.18 
    @storybook/preset-create-react-app: ^3.1.4 => 3.1.4 
    @storybook/react: ^6.0.18 => 6.0.18
```

**Additional context**
This error was originally encountered in the context of a production monolith managed by a large team.  The `create-react-app` example is provided to reproduce the error.

There is a bug fix for the import error in https://github.com/storybookjs/storybook/pull/12252

**Comment by shilman** [comment]
Crikey!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.20 containing PR #12252 that references this issue. Upgrade today to try it out!

Closing this issue. Please re-open if you think there's still more to do.
