### ISSUE TITLE
storybook 6 seems not working with css-loader 4.x on a vuetify project.

### ISSUE THREAD

**Issue by xiaoshuw** [storybookjs/storybook#12259]
**Describe the bug**
Story book seems failed to render vuetify-based project when upgrading css-loader from 3.x to 4.x

**To Reproduce**
Well, I have lerna project, using vue, and vuetify. It has been working fine. But when I try to upgrade css-loader from 3.6.0 to 4.x version, the storybook will load but the component won't render as expected. I think it lost all the styles that vuetify provided.

Here is my main.js

```
const path = require('path')
const rootPath = path.resolve(__dirname, '../')
module.exports = {
  stories: ['../components/**/*.stories.js'],
  addons: ['@storybook/addon-essentials',
    '@storybook/addon-knobs',
    '@storybook/addon-links',
    '@storybook/addon-a11y',
  ],
  webpackFinal: async (config, { configType }) => {
    config.resolve.extensions.push(
      '.vue',
      '.css',
      '.less',
      '.scss',
      '.sass',
      '.html',
    );
    config.module.rules.push({
      test: /\.s(c|a)ss$/,
      use: [
        'vue-style-loader',
        'css-loader',
        {
          loader: 'sass-loader',
          options: {
            implementation: require('sass'),
            sassOptions: {
              data: `@import "@/packages/theme/styles/idm.scss"`,
              indentedSyntax: true,
              fiber: require('fibers'),
            }
          },
        },
      ],
    },
    {
      test: /\.html$/,
      exclude: /node_modules/,
      use: {loader: 'html-loader'}
    });
    config.resolve.alias['@'] = rootPath
    return config;
  },
}
```
and my preview.js

```
import { withKnobs, object } from '@storybook/addon-knobs';
import { configure, addDecorator } from '@storybook/vue';
import { VApp, VContent } from 'vuetify/lib';
import vuetifyConfig from '../plugins/vuetify'
const appDecorator = () => {
  return {
    vuetify: vuetifyConfig,
    components: { VApp, VContent },
    template: `
      <v-app>
          <v-main>
            <story/>
          </v-main>
      </v-app>
    `
  };
};
addDecorator(appDecorator)
addDecorator(withKnobs)
```
![Screen Shot 2020-08-26 at 11 34 56 AM](https://user-images.githubusercontent.com/10134745/91324755-668c5080-e790-11ea-9c54-307a22c0d1e1.png)
![Screen Shot 2020-08-26 at 11 35 41 AM](https://user-images.githubusercontent.com/10134745/91324759-6724e700-e790-11ea-8975-a5573f6d5d3d.png)

**Comment by ctestama** [comment]
I'm experiencing the same issue with @storybook/html and css-loader 4.3.0. Storybook starts up fine, but the styles are missing.

**Comment by andreasschuele** [comment]
I had a similar issue in a different project. Adding _esModule = false_ option helped. It looks like that the default for this option was set to true in css-loader (https://github.com/webpack-contrib/css-loader/releases/tag/v4.0.0)

```css
{ 
  loader: 'css-loader',
  options: {
    esModule: false
  } 
}
```

**Comment by xiaoshuw** [comment]
Thanks: andreasschuele 

I think that fix the problem. Thanks.
