### ISSUE TITLE
Support: Can i render an Angular-Component in a docs page without story? 

### ISSUE THREAD

**Issue by flobiber** [storybookjs/storybook#12264]
I would like to create a component that reads all defined css-colors (var(--example-color)) and shows that like a color-palette.

For that scenario i would like to create a angular component that exactly does that. 

I try to show that component like that: 

```
import { Meta, Canvas, Preview, ColorPalette, ColorItem, Wrapper, Primary } from '@storybook/addon-docs/blocks';
import { ColorPaletteComponent } from './color-palette/color-palette.component';
import { moduleMetadata } from '@storybook/angular';


<Meta title="LIB / Colors" decorators="{[moduleMetadata({declarations:[ColorPaletteComponent]})]}" />

# Colors

Here you can see all colors.

<Preview>
  <color-palette></color-palette>
</Preview>
```

But it isn't rendering the content of the ColorPalette-Component.

Is it possible? Or which alternatives i have?

**Comment by shilman** [comment]
Currently the only way to render Angular examples in the docs page is using stories.

There are some other options for different frameworks, but until the community figures out inline rendering for Angular (https://github.com/storybookjs/storybook/issues/8153), stories are the only option

**Comment by shilman** [comment]
Great Caesar's ghost!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.0-alpha.19 containing PR #13525 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
