### ISSUE TITLE
create-react-app and storybook v6 webpack versions conflict

### ISSUE THREAD

**Issue by AskAlice** [storybookjs/storybook#12266]
**Describe the bug**

```
$ npm ls webpack
+-- @storybook/react@6.0.19
| +-- @storybook/core@6.0.19
| | `-- webpack@4.44.1  deduped
| `-- webpack@4.44.1 
`-- react-scripts@3.4.3
  `-- webpack@4.42.0 
```

causes this error when running `npm run start`

```
There might be a problem with the project dependency tree.
It is likely not a bug in Create React App, but something you need to fix locally.

The react-scripts package provided by Create React App requires a dependency:     

  "webpack": "4.42.0"
```
**To Reproduce**
```
"react": "^16.13.1",
"react-dom": "^16.13.1",
"react-scripts": "^3.4.1",
```
storybook version 6.0.19

**Expected behavior**

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System:**
Please paste the results of `npx sb@next info` here.

**Additional context**

**Comment by shilman** [comment]
Closing as duplicate to https://github.com/storybookjs/storybook/issues/6505
