### ISSUE TITLE
Addon-docs: empty props on DocsPage. TypeScript and dot notation.

### ISSUE THREAD

**Issue by Jekins** [storybookjs/storybook#12263]
**Describe the bug**
I am using TypeScript and dot notation with FunctionComponent. If the main FC component is additionally passed an object with child components for dot notation, then he properties are not shown on the DocsPage.

This is showing props: `const Main: FC<IMainProps> = ...`
This is **not** showing props: `const Main: FC<IMainProps> & { Item: FC<IItemProps> } = ...`

**Expected behavior**
Props FC Main are shown on DocsPage

**Code snippets**
_./Main.tsx_
```
import React, { FC } from 'react'

interface IItemProps {
  spacing: 'large' | 'small'
}

const Item: FC<IItemProps> = ({ spacing, children }) => (
  <div spacing={spacing}>{children}</div>
)

interface IMainProps {
  color: 'blue' | 'red'
}

const Main: FC<IMainProps> & { Item: FC<IItemProps> } = ({ color, children }) => (
  <div color={color}>{children}</div>
)

Main.item = Item

export default Main
```

_./index.ts_
```
import Main from './Main'

export { Main }

```

_./Main.stories.tsx_
```
import React, { FC } from 'react'
import { Main } from '.'

export default {
  title: 'UI/Components/Main',
  component: Main,
}

export const playground: FC = () => (
  <Main color='blue'>
    <Main.Item spacing='large'>Text</Main.Item>
  </Main>
)

```

**System:**
  System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
  Browsers:
    Chrome: 84.0.4147.135
    Firefox: 72.0.2
    Safari: 12.1.2

**Additional context**
"@storybook/addon-docs": "^6.0.18",
"@storybook/react": "^6.0.18",
"typescript": "^4.0.2"

**Comment by shilman** [comment]
can you share a screenshot to help explain?

**Comment by Jekins** [comment]
> can you share a screenshot to help explain?
A screenshot of what exactly? On DocsPage, instead of a table with props, it says "No inputs found for this component. Read the docs >"

**Comment by shilman** [comment]
thanks for the clarification

**Comment by imeredith** [comment]
I have the same issue with propTypes. I have verified that docgen is attaching the info to the component, but then I don't see any props in controls/addon-docs.

If I set Story.args = { ... } then whatever defaults I have set will show up as props and be editable but the type is inferred from the defaults

**Comment by seschi98** [comment]
I can confirm this issue, I have exactly the same problem. If you need further details to reproduce this, please let me know (my code is almost the same as the one from @Jekins and I am on v6.0.21). One more note: This broke with the upgrade to SB6, with SB5 the props are displayed as usual.

**Comment by shilman** [comment]
Do you have a repro repo you can share?

**Comment by seschi98** [comment]
> Do you have a repro repo you can share?

@shilman I can try to copy some of the code to a public repo on Monday.

**Comment by seschi98** [comment]
@shilman I created a repo with a demo component where you can see the issue.
https://github.com/seschi98/storybook-typescript-demo

If you open up `Table.stories.tsx` in your browser and navigate to the Doc tab, you can see that there are no props shown for the `Table` Component, but only for `Table.Column`.

**Comment by apdrsn** [comment]
Hi :) This still seems to be an issue. Any progress on it? :)

**Comment by seschi98** [comment]
> Hi :) This still seems to be an issue. Any progress on it? :)

@apdrsn I think I managed to get it to work, but I will have to check how I did it on monday :)

**Comment by apdrsn** [comment]
@seschi98 That would be lovely! Thanks 💯

**Comment by apdrsn** [comment]
Hi agian @seschi98 :) Did you get to have a look if you managed to solve this?

**Comment by seschi98** [comment]
@apdrsn Yes i did some research and unfortunately I was wrong... I did not find a solution for the problem

**Comment by apdrsn** [comment]
@seschi98 alright - no worries :)
A colleague of mine found the solution for my use case. Turns out it was pretty simple:

```ts
import { Flex } from '../Flex';

export default {
  title: 'Components/Layout/Flex',
  component: Flex,
  subcomponents: { 'Flex.Item': Flex.Item },
} as Meta;
```

**Comment by atlk-kv** [comment]
I have the same problem + does not logging events in actions tab. Adding a subcomponent to Meta object doesn't solve the problem.

```
type SliderComponent = React.FunctionComponent<SliderPropsTypes> & {
  Range: React.FunctionComponent<SliderRangePropsTypes>;
};

const Slider: SliderComponent = ({
...
...
...

Slider.Range = SliderRange

export default Slider
```

```
export default {
  title: 'Core components/Slider',
  component: Slider,
  subcomponents: { 'Slider.Range': Slider.Range },
} as Meta;
```

**Comment by jzempel** [comment]
Similar problem with various components in https://zendeskgarden.github.io/react-components/. I found that exporting a subcomponent with a `displayName` mismatch results in the following:

<img width="1022" alt="Screen Shot 2022-01-10 at 8 07 53 AM" src="https://user-images.githubusercontent.com/143773/148771079-0ce8ddb4-aced-4ebd-90d7-401eefa8132c.png">

...where the subcomponent code looks some thing like:

```tsx
interface ITimelineItemProps extends LiHTMLAttributes<HTMLLIElement> {
  /** Replaces the dot with an icon */
  icon?: ReactNode;
  /** Provides surface color for an icon placed on a non-white background */
  surfaceColor?: string;
}

export const ItemComponent = forwardRef<HTMLLIElement, ITimelineItemProps>(/* subcomponent code here... */);

Item.displayName = 'Timeline.Item';
```

I can get Storybook to render subcomponent props with the following export tweak...

```tsx
interface ITimelineItemProps extends LiHTMLAttributes<HTMLLIElement> {
  /** Replaces the dot with an icon */
  icon?: ReactNode;
  /** Provides surface color for an icon placed on a non-white background */
  surfaceColor?: string;
}

const ItemComponent = forwardRef<HTMLLIElement, ITimelineItemProps>(/* subcomponent code here... */);

ItemComponent.displayName = 'Timeline.Item';

export const Item = ItemComponent;
```

A bit hacky, but I get the `displayName` I need (for my own docgen parsing) and Storybook is updated with:

<img width="1025" alt="Screen Shot 2022-01-10 at 8 14 12 AM" src="https://user-images.githubusercontent.com/143773/148771915-36d3580a-33f0-4948-a8a4-e9d4e672019e.png">

In either case, the main component type definition is shaped something like...

```tsx
interface ITimelineProps extends OlHTMLAttributes<HTMLOListElement> {
  /** Applies alternate styling */
  isAlternate?: boolean;
}

const TimelineComponent = forwardRef<HTMLOListElement, ITimelineProps>(/* component code here... */);

TimelineComponent.displayName = 'Timeline';

export const Timeline = TimelineComponent as typeof TimelineComponent & {
  Content: typeof Content;
  Item: typeof Item;
  OppositeContent: typeof OppositeContent;
};

Timeline.Content = Content;
Timeline.Item = Item;
Timeline.OppositeContent = OppositeContent;
```

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
