### ISSUE TITLE
Documentation (Controls Addon) - Add instructions for disabling controls

### ISSUE THREAD

**Issue by novellac** [storybookjs/storybook#12260]
**Is your feature request related to a problem? Please describe.**
In using Storybook, particularly the Controls addon, I read the [documentation site](https://storybook.js.org/docs/vue/essentials/controls) a lot. However, when I searched the docs for a way to disable controls for a property, I couldn't find any results.

**Describe the solution you'd like**
 - It would be helpful to add [this section](https://github.com/storybookjs/storybook/blob/next/addons/controls/README.md#how-can-i-disable-controls-for-certain-fields-on-a-particular-story) from the [Controls addon README](https://github.com/storybookjs/storybook/blob/next/addons/controls/README.md) file to the [docs site](https://storybook.js.org/docs/vue/essentials/controls).
- An added bonus would be to also provide information on how to disable controls per stories file.

**Describe alternatives you've considered**
The instructions can also be found on the [Controls addon README](https://github.com/storybookjs/storybook/blob/next/addons/controls/README.md) file (but this is not as streamlined as having it on the docs site).

**Are you able to assist bring the feature to reality?**
I'd be glad to make a PR for it, but wasn't sure if it was purposefully left off, or if it is located in the docs somewhere else (in which case, perhaps a link would suffice).

**Additional context**
N/A

**Comment by shilman** [comment]
@tmeasday any thoughts on this?

**Comment by tmeasday** [comment]
Nope, wasn't intentional @novellac! I feel like I remember adding it but who knows! Send a PR, please!

**Comment by novellac** [comment]
Ok, I'll get on it (unless someone else does first!).

**Comment by jonniebigodes** [comment]
@novellac just left some feedback on the pull request you made. 

Feel free to provide feedback.

**Comment by jonniebigodes** [comment]
@novellac closing this as with a recent pull request (#12917) the documentation was updated to provide a set of clearer instructions on how to disable controls. Nonetheless thank you for bringing this to our attention and for the time and effort you put into the pull request.

Stay safe
