### ISSUE TITLE
Can't make storybook work with ngx-formly

### ISSUE THREAD

**Issue by phamhaibkit** [storybookjs/storybook#12276]
Hi guys,
I faced a problem when using storybook with ngx-formly [https://formly.dev/guide/getting-started](url).
Storybook working fine with a common angular component, but with formly-form always get errors as the picture attached
![Capture](https://user-images.githubusercontent.com/29273243/91420050-5357ae80-e87e-11ea-9e77-6712d655ac0f.PNG)
. 
I have reference to another issue #10449
But I can't figure out how to make it work.
Could you help me to find the cause of the problem?
Thanks,

**Comment by Marklb** [comment]
Without more information about how the story and maybe configuration is set, it is hard to knew the problem.

My best guess is that you aren't importing the `ReactiveFormsModule`, since that is what that error usually means in Angular.

**Comment by phamhaibkit** [comment]
@Marklb many thanks for the prompt reply. I upgrade "core-js" and resolve the problem so I will close this issue.
Thanks,
