### ISSUE TITLE
Addons not updated while moving between stories at composed storybook

### ISSUE THREAD

**Issue by rannyeli** [storybookjs/storybook#12278]
Addons updated only when i'm focusing on them.
Here is a gif to represent the problem:
[
![Peek 2020-08-27 15-16](https://user-images.githubusercontent.com/42379604/91441447-e42b8b80-e878-11ea-88c3-74598e0fdf66.gif)
](url)

**System:**
```
    OS: Linux 5.4 Ubuntu 18.04.5 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
  Binaries:
    Node: 14.5.0 - ~/.nvm/versions/node/v14.5.0/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v14.5.0/bin/npm
  Browsers:
    Chrome: 84.0.4147.135
    Firefox: 79.0
  npmPackages:
    @storybook/addon-actions: ^6.0.18 => 6.0.18 
    @storybook/addon-docs: ^6.0.18 => 6.0.18 
    @storybook/addon-knobs: ^6.0.18 => 6.0.18 
    @storybook/addon-links: ^6.0.18 => 6.0.18 
    @storybook/addon-storysource: ^6.0.18 => 6.0.18 
    @storybook/addons: ^6.0.18 => 6.0.18 
    @storybook/preset-create-react-app: ^3.1.4 => 3.1.4 
    @storybook/react: ^6.0.18 => 6.0.18 
    @storybook/theming: ^6.0.18 => 6.0.18
```

**Comment by syncush** [comment]
Hey, any updates?

**Comment by shilman** [comment]
@ndelangen any thoughts on this?

**Comment by rannyeli** [comment]
@shilman yes they both have `addon-storysource` installed with the same version `6.0.18`, it appears on `addon-knobs` and `addon-actions` as well

**Comment by inthegreenwild** [comment]
I have a similar issue where one storybook is using controls (version 6) and another storybook is using knobs (stories built on storybook 5.3). 

Only the action tab shows up for all stories in the composition, knobs never shows up in the 5.3 storybook

**Comment by ndelangen** [comment]
Composition -right now- doesn't support taking manage-addons from the composed storybook into the parent storybook.

We're looking into making addons more stand-alone and thus be possible to be loaded without them being in the bundle.

But it does look like addon panels might not be updating correctly when the selected story is from a composed storybook.

**Comment by syncush** [comment]
bump
