### ISSUE TITLE
[addon-storyshots-puppeteer] add custom arguments --font-render-hinting for puppeteer

### ISSUE THREAD

**Issue by alexandrzavalii** [storybookjs/storybook#12284]
**Is your feature request related to a problem? Please describe.**
There is an inconsistency of how fonts are rendered in different environemnt.

**Describe the solution you'd like**
By adding this arg '--font-render-hinting=none' or `--disable-gpu` to launch configuration makes rendering of the font much more consistent.

Related issue:
https://github.com/puppeteer/puppeteer/issues/661

**Comment by shilman** [comment]
PRs welcome!

**Comment by alexandrzavalii** [comment]
Hey @shilman 
I think I figured out the solution.
I will post it below in case someone faces the same issue.

```
let Browser;
const getCustomBrowser = async () => {
  Browser = await puppeteer.launch({
    headless: true,
    args: [
      '--no-sandbox ',
      '--disable-setuid-sandbox',
      '--disable-dev-shm-usage',
      '--disable-gpu',
      '--font-render-hinting=medium',
    ],
  });

  return Browser;
};

imageSnapshot({
  storybookUrl: staticStorybook,
  getCustomBrowser,
})

test.afterAll = async () => {
  await Browser.close();
};


```

**Comment by ndelangen** [comment]
The future of storyshots is the test-runner:
https://storybook.js.org/docs/react/writing-tests/test-runner#page-top

And use the play function for expectations:
https://storybook.js.org/docs/react/writing-stories/play-function#page-top

We will not be making any improvement / changes to storyshots.
