### ISSUE TITLE
Storybook 6.x Scripting: Get URLs of all stories?

### ISSUE THREAD

**Issue by smurrayatwork** [storybookjs/storybook#12283]
I'm trying to work with Storybook 6.0's APIs from within node 12.x and I have a need to get all the URLs for the stories of my storybook - is this possible to do? I'm not creating an add-on in this case - I'm passing the URLs to backstop for further processing.

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react 6.0.16

**Comment by shilman** [comment]
Did you try `npx sb extract`?

**Comment by smurrayatwork** [comment]
@shilman What does that command do? I tried it, but the help description doesn't tell me how to properly use the command with options. Do you have an example?

**Comment by shilman** [comment]
Cc @ndelangen

**Comment by smurrayatwork** [comment]
@shilman @ndelangen 

Is there any way to run the extract command on CI? I was able to use the stories.json file generated by `sb extract` locally, but trying to do so with CircleCI ends up with timeouts on this line:
```
  await page.waitForFunction('window.__STORYBOOK_STORY_STORE__ && window.__STORYBOOK_STORY_STORE__.extract && window.__STORYBOOK_STORY_STORE__.extract()');
```

**Comment by sghoweri** [comment]
I'd also love to know if there was a way to grab this info in Node directly (vs having to go through the CLI's extract command).

**Comment by ahelmel** [comment]
Is there any progress on this issue? I would like to get all story urls inside a node script.

**Comment by ndelangen** [comment]
@ahelmel the progress is slow.

Our goal is to push forwards static analyzable stories via https://storybook.js.org/docs/react/api/csf

And statically analyzable definitions and config via https://storybook.js.org/docs/react/configure/overview

This will allow us to extract stories.json without running the code.
(running the stories code can't reliably done in node)

**Comment by shilman** [comment]
@ndelangen @ahelmel open issue for that here https://github.com/storybookjs/storybook/issues/14254

**Comment by shilman** [comment]
Per #15254 you can now get `stories.json` in both dev and production mode with `buildStoriesJson: true` feature flag set in 6.4 and above. Closing this for now. Please let me know if there's more to be done here!
