### ISSUE TITLE
CLI: Deprecate --mdx option

### ISSUE THREAD

**Issue by tooppaaa** [storybookjs/storybook#12285]
Part of the CLI revamping, we added addon-essentials and a Introduciton.mdx story.

This bring the question, should we deprecate --mdx completely ?

Refers to: #12252

Pros:
- Only a few framework had it implemented
- Shows the capacity to include stories from MDX

Cons
- Loose demo of creating stories in MDX directly

**Comment by shilman** [comment]
We should probably deprecate it now and get rid of it in 7.0 for simplicity's sake.

**Comment by tmeasday** [comment]
I suspect folks ain't using such options

**Comment by tooppaaa** [comment]
Objective is to make option no-op with a warning. It should fallback to detect ts or js.

**Comment by shilman** [comment]
That makes sense @tooppaaa. Great solution. 💯

**Comment by shilman** [comment]
Ooh-la-la!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.0-alpha.30 containing PR #12905 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
