### ISSUE TITLE
Typo in exported constant name: MAX_DEFALUT_VALUE_SUMMARY_LENGTH

### ISSUE THREAD

**Issue by ankon** [storybookjs/storybook#12280]
https://github.com/storybookjs/storybook/blob/f90f10d43c8da7aa7262a7f2003eb4c618657c92/addons/docs/src/lib/utils.ts#L4

That should be `MAX_DEFAULT_VALUE_SUMMARY_LENGTH`, but I'm not sure if this can be fixed trivially or whether other components are expected to reference that constant.

**Comment by shilman** [comment]
Thanks! Fixed in ae993d0cdf!
