### ISSUE TITLE
React Docgen Typescript errors when using certain Material-ui components

### ISSUE THREAD

**Issue by mlenser** [storybookjs/storybook#12297]
**Describe the bug**
I have a design system based on material ui, using typescript. All stories work except any story including the `Card` or `Radio` material ui component. I tried very simple cases that only import those components directly.

When I run `start-storybook` or `build-storybook` I get the following:

```
70% sealing React Docgen Typescript Plugin \node_modules\react-docgen-typescript\lib\parser.js:6
11
                if (symbol_3 && symbol_3.declarations.length) {
                                                      ^

TypeError: Cannot read property 'length' of undefined
    at Parser.getLiteralValueFromPropertyAssignment (\node_modules\react-docgen-typescript\lib\
parser.js:611:55)

```

**To Reproduce**
I can create a reproducable package if necessary, but it's a bit of work

**Expected behavior**
The stories build

**Screenshots**
![image](https://user-images.githubusercontent.com/235857/91551499-86f01280-e92a-11ea-9d32-8c6bcef3664e.png)

**System:**
I tried this on Windows and Mac

Windows:
```
Environment Info:

  System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz
  Binaries:
    Node: 14.8.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - \node_modules\.bin\yarn.CMD
    npm: 6.14.6 - \node_modules\.bin\npm.CMD
  Browsers:
    Chrome: 84.0.4147.135
    Edge: Spartan (44.18362.449.0)
  npmPackages:
    @storybook/addon-a11y: 6.0.20 => 6.0.20
    @storybook/addon-actions: 6.0.20 => 6.0.20
    @storybook/addon-backgrounds: 6.0.20 => 6.0.20
    @storybook/addon-centered: 5.3.21 => 5.3.21
    @storybook/addon-knobs: 6.0.20 => 6.0.20
    @storybook/addon-viewport: 6.0.20 => 6.0.20
    @storybook/react: 6.0.20 => 6.0.20
    @storybook/theming: 6.0.20 => 6.0.20
```
Mac:
```
Environment Info:

  System:
    OS: macOS Mojave 10.14.5
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Binaries:
    Node: 14.5.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /node_modules/.bin/yarn
    npm: 6.14.6 - /node_modules/.bin/npm
  Browsers:
    Chrome: 84.0.4147.135
    Firefox: 69.0.1
    Safari: 12.1.1
  npmPackages:
    @storybook/addon-a11y: 6.0.20 => 6.0.20 
    @storybook/addon-actions: 6.0.20 => 6.0.20 
    @storybook/addon-backgrounds: 6.0.20 => 6.0.20 
    @storybook/addon-centered: 5.3.21 => 5.3.21 
    @storybook/addon-knobs: 6.0.20 => 6.0.20 
    @storybook/addon-viewport: 6.0.20 => 6.0.20 
    @storybook/react: 6.0.20 => 6.0.20 
    @storybook/theming: 6.0.20 => 6.0.20 
```

**Comment by kitety** [comment]
Me too.I hope someone to resolve it.

**Comment by shilman** [comment]
@mlenser is this an issue you can file a repro for on the `react-docgen-typescript` repo? cc @hipstersmoothie

**Comment by hipstersmoothie** [comment]
I was able to get the docgen to work for the following example

```tsx
import * as React from 'react';
import Card, { CardProps } from '@material-ui/core/Card';

/**
 * MaterialUICard description
 */
export class MaterialUICard extends React.PureComponent<CardProps, {}> {
  public render() {
    return <Card>Test</Card>;
  }
}
```

Looking at the error you posted I can't find any code that looks like that. What version of `react-docgen-typescript` is installed in your project? If I could get a reproduction repo I could probably fix this pretty easily.

**Comment by charlesverge** [comment]
Utilizing the parse function from html-react-parser const reactElement = parse(html, options); Triggered this error as well. Sorry no repo.

**Comment by mlenser** [comment]
This is no longer an issue as of a month or two ago so I will close this. Sorry for the delay.

**Comment by hazem3500** [comment]
@mlenser how did you solve it?

**Comment by mlenser** [comment]
@hazem3500 sorry, normally I document why these things are fixed. I believe it was solved by one of our dependency updates that came a few months after I opened this issue.

I suggest updating all your dependencies and hopefully that'll solve it.
