### ISSUE TITLE
Is there a way to display the key of the object of the array as props?

### ISSUE THREAD

**Issue by Inhye-Cheong** [storybookjs/storybook#12294]
**Is your feature request related to a problem? Please describe.**
Is there a way to display the key of the object of the array as props in storybook? (not just inline props definition)

**Describe alternatives you've considered**
I want to show the details of the Content type in storybook props (like `Content[{title: string, description: string}]`), but it only displays `Content[]`. Is there any way?
```tsx
type Content = {
  title: string;
  description: string;
};
type Props = {
  lists: Content[];
};
export const SOME_COMPONENT: FC<Props> = ({lists}) => {
  : 
  : 
};
```

**Additional context**
* storybook v6.0.18
* addons
```js
addons: [
    '@storybook/addon-docs',
    '@storybook/addon-knobs',
    '@storybook/addon-viewport',
  ]
```
* loaders
`url-loaders`, `babel-loader`, `react-docgen-typescript-loader`

**Comment by shilman** [comment]
How about:
```
JSON.stringify(lists)
```

**Comment by Inhye-Cheong** [comment]
> How about:
> 
> ```
> JSON.stringify(lists)
> ```
@shilman Thank you for quick response.
Where can I add that code?

**Comment by ajkl2533** [comment]
@Inhye-Cheong you can do it manually in story argTypes
```js
story.argTypes = {
  lists: {
    table: {
      type: {
        summary: 'Content[]',  // <- this is probably not needed
        detail: `
[
  {
    title: string;
    description: string;
  }
]
        `,
      },
    },
  },
};

**Comment by shilman** [comment]
Thanks @ajkl2533 -- I misunderstood the question!
