### ISSUE TITLE
Get decorator to fire when user interacts with MDX Docs tab

### ISSUE THREAD

**Issue by DanWahlin** [storybookjs/storybook#12290]
**Is your feature request related to a problem? Please describe.**
A decorator function is triggered when the user clicks on the Canvas tab or loads the Canvas panel. However, when they click on the MDX Docs tab the same decorator function doesn't fire. We're using a global decorator (see below) to capture the story file name that the user is on for a custom source code viewer.

**Describe the solution you'd like**
It'd be great to have the decorator fire when the user clicks on Canvas or on Docs.

**Describe alternatives you've considered**
Considered adding some custom DOM code to handle emitting but would prefer to use the channel within a decorator.

**Are you able to assist bring the feature to reality?**
No (not without hacking something in anyway)

**Additional context**
This is the decorator currently being used that fires as expected when the user clicks on the Canvas tab. When they click the Docs tab the wrapper function doesn't fire though as mentioned. This may be the intended behavior but this type of functionality is needed for our solution. 

If there's already something in place to handle this I'd be very interested - searched quite a bit but it's certainly possible I missed a potential built-in solution. Thanks in advance for your help!

```javascript
import { addons, makeDecorator } from '@storybook/addons'

export default makeDecorator({
  name: 'withSourceInfo',
  parameterName: 'sourcecode',
  wrapper: (getStory, context) => {
   // fires when user clicks on Canvas tab but not on Docs tab
    const channel = addons.getChannel();
    channel.emit('sourcecode/selectedStory', context.parameters.fileName);
    return getStory(context);
  },
});
```

**Comment by shilman** [comment]
I'd expect that the decorator would be called every time a story is rendered. So if an MDX docs page has 5 stories that use that decorator, I'd expect the decorator to be called 5 times.

Storybook does not use decorators at the docs page level. It uses a container component, documented here:

https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/recipes.md#overwriting-docs-container

If you wanted to fire an event when the page is rendered, you could do it with a custom container.

**Comment by DanWahlin** [comment]
I'm using a global decorator in this case so it sounds like it would have to be hooked directly to each story to fire with MDX docs (it definitely doesn't fire currently when a story in an MDX page is loaded - at least that's what we're seeing). I'll check out the custom container option though - really appreciate it.

**Comment by shilman** [comment]
Every time a story renders, its decorators should also be called.

A docs page can have zero or more stories on it. If it has no stories on it, no decorators will get called. The docs page itself always has a container and its container will be rendered as a wrapper every time the page rendered regardless of whether the page contains stories.

I would expect your "border decorator" above to be called. I just verified this one is called in `examples/addon-docs.stories.mdx`:

```
<Story
  name="decorator story"
  decorators={[
    (StoryFn) => (
      <div style={{ backgroundColor: 'pink' }}>
        <StoryFn />
      </div>
    ),
  ]}
>
  <>Story decorators</>
</Story>
```

**Comment by DanWahlin** [comment]
We're not seeing that behavior so I think there must be some type of side effect interfering. Thanks for the clarification there, helps a lot.

**Comment by shilman** [comment]
Yep it's pink in both tabs.

**Comment by DanWahlin** [comment]
Thanks @shilman! Really appreciate your time and responses. That's good to hear but a little worrisome because it means there's definitely something blocking that from happening in our project. Thanks for checking into it and for the info. I'll start peeling back layers to figure out what interrupted that process (we have quite a bit of complexity in there now :-)).

**Comment by shilman** [comment]
@DanWahlin Happy to pair for a few min if UT helps. Are your docs stories rendering inline or in iframes? Shouldn't make a difference but it's another variation

**Comment by DanWahlin** [comment]
You are seriously too kind. :-) I'll DM you.

**Comment by DanWahlin** [comment]
For anyone that runs into this it was a super simple fix. My stories were running fine in Canvas and Docs modes but the decorator wasn't firing in Docs mode as mentioned above. All that was required to get it working in Docs mode was the following import (which makes total sense thanks to @shilman walking me through what's going on):

`import { Story } from '@storybook/addon-docs/blocks';`
