### ISSUE TITLE
addon-storysource: source tab does not look like in the readme

### ISSUE THREAD

**Issue by DanielRuf** [storybookjs/storybook#12299]
**Describe the bug**
Currently the source tab does not look like in the readme.

**To Reproduce**

1. create a new default storybook setup
1. install the source plugin
1. start storybook and check the content of the source tab

**Expected behavior**
![grafik](https://user-images.githubusercontent.com/827205/91567411-5b2e5600-e945-11ea-86d8-541236768593.png)

**Screenshots**
![grafik](https://user-images.githubusercontent.com/827205/91567334-43ef6880-e945-11ea-83e3-ed297efe8f54.png)

**System:**
```
Environment Info:

  System:
    OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-4710MQ CPU @ 2.50GHz
  Binaries:
    Node: 10.16.0 - ~/.nodenv/versions/10.16.0/bin/node
    Yarn: 1.22.5 - ~/.yvm/shim/yarn
    npm: 6.13.4 - ~/.nodenv/versions/10.16.0/bin/npm
  Browsers:
    Chrome: 81.0.4044.113
    Firefox: 79.0
  npmPackages:
    @storybook/addon-actions: ^6.0.19 => 6.0.20 
    @storybook/addon-essentials: ^6.0.19 => 6.0.20 
    @storybook/addon-links: ^6.0.19 => 6.0.20 
    @storybook/addon-storysource: ^6.0.20 => 6.0.20 
    @storybook/node-logger: ^6.0.19 => 6.0.20 
    @storybook/preset-create-react-app: ^3.1.4 => 3.1.4 
    @storybook/react: ^6.0.19 => 6.0.20
```

**Additional context**
everything default (yarn, TypeScript)

**Comment by petermikitsh** [comment]
In main.js, try setting up your addons like this:

```js
{
  addons: [
    '@storybook/addon-essentials',
    '@storybook/addon-controls',
    '@storybook/addon-storysource',
    {
      name: '@storybook/addon-docs',
      options: {
        sourceLoaderOptions: {
          parser: 'typescript',
          injectStoryParameters: false,
        },
      },
    },
  ]
}
```

**Comment by DanielRuf** [comment]
Thanks for your input @petermikitsh. So we have to pass custom options for the ?@storybook/addon-docs` addon? So is this piece of information missing in the readme?

**Comment by DanielRuf** [comment]
> In main.js, try setting up your addons like this:

Thanks, this seems to work now.

So I guess the docs are incomplete in both branches:
https://github.com/storybookjs/storybook/tree/master/addons/storysource
https://github.com/storybookjs/storybook/tree/next/addons/storysource

**Comment by DanielRuf** [comment]
Hm, this is weird.

source code:

![grafik](https://user-images.githubusercontent.com/827205/91713029-404c2380-eb89-11ea-934d-6f6452318075.png)

in storybook:

![grafik](https://user-images.githubusercontent.com/827205/91713071-578b1100-eb89-11ea-8fdd-13ef2470105c.png)


See the repeated `const Template` line. I guess this is a bug?

**Comment by petermikitsh** [comment]
@DanielRuf Yes, the duplicate variable bug has been reported here: https://github.com/storybookjs/storybook/issues/12065

**Comment by DanielRuf** [comment]
Ah ok, thanks for pointing me to the relevant issue.

Closing this issue as resolved.
I guess the bug will be debugged and fixed in a future release.
