### ISSUE TITLE
when running storybook with npm Ref does not seem to resolve, no output in shell console.

### ISSUE THREAD

**Issue by bryanrasmussen** [storybookjs/storybook#12296]
Browser - Firefox Developer, OS Mac Mojave

I'm trying to use the storybook composability functionality in the latest release , I am on storybook/react v6.0.18 - both the storybook that is referencing and the referenced storybook are the same version.

Both storybooks run with npm. 

I have two projects - one running on localhost:6006 the other at localhost:6007. 

The localhost:6006 is trying to refer to localhost:6007
this is my make.js for localhost:6006

```
module.exports = {
  "stories": [
    "../stories/**/*.stories.mdx",
    "../stories/**/*.stories.@(js|jsx|ts|tsx)"
  ],
  refs: {
     astronomisk: { 
       title: "Astronomisk Selskab", 
       url: "http://localhost:6007"
     }
    },
  "addons": [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    {
      name: '@storybook/addon-docs',
      options: {
        configureJSX: true,
      },
    },
  ]
}
```

The storybook running on localhost:6007 looks fine by itself. 
But in localhost:6006 when I look at it the left panel where the ref should be shows the title "astronomisk selskab" is present , and 5 placeholders for components to load (gray boxes, animated to imply that they are loading)

The following error is being thrown clientside

Uncaught DOMException: Permission denied to access property "document" on cross-origin object DocumentFormatting.js:154

there is no output in either shell console, so it seems completely a clientside issue. 

If I run with Yarn I do not have this issue.

**Comment by kije** [comment]
I have the same issue with storybook v6.1.5 and vue

I have a storybook running on http://localhost:6046 and another on http://localhost:7047

main.js
```js
module.exports = {
  stories: ['../../src/**/*.stories.@(js|ts|mdx)'],

  refs: {
    'web-ui-base': {
      title: 'web-ui-base',
      url: 'http://localhost:7047',
    },
  },
};
```

Additionally I get the following error in devtools console:
![GUI-Editor___WYSIWYG_Preview___Layers___BackgroundLayer_-_Base_⋅_Storybook](https://user-images.githubusercontent.com/3481639/100376250-77f32c00-300f-11eb-8ac8-95b3cb577294.png)


I can access both storybooks (http://localhost:6046 and http://localhost:7047) individually, but in my "main" storybook (http://localhost:6046) the section of the ref stays forever

![GUI-Dashboard_-_Page_⋅_Storybook](https://user-images.githubusercontent.com/3481639/100376514-ef28c000-300f-11eb-87f0-1884fda88de3.png)
 in the loading state:

**Comment by apete343** [comment]
Having the same issue as @kije with `@storybook/react` v`6.1.11`

**Comment by apete343** [comment]
hrm, i made a simple test here: https://github.com/apete343/storybook-ref-test

And the refs to localhost work as expected. So not sure what my issue is in the real life scenario yet.

**Comment by rmknecht** [comment]
Also seeing the same issue with `@storybook/react` v`6.1.1`. 

- Both projects are on the same storybook versions.
- The referenced storybook is accessible on its own at `http://localhost:6009`
- The parent project at `http://localhost:8080` displays **"Please wait. This story is loading"** for the referenced project and hangs



I resolved the 404 `/stories.json` error in referenced projects by building storybook:
```bash
build-storybook && npx sb extract
``` 

.. and serving the static build:


```bash
start-storybook -p 6009 -s ./storybook-static
```

**Comment by rmknecht** [comment]
Also noticed that the  `/progress` endpoint hangs with a "pending" status:

![Screen Shot 2021-01-21 at 6 10 38 PM](https://user-images.githubusercontent.com/4553857/105428363-df46ea00-5c14-11eb-9372-40030618ee1c.png)

**Comment by IanVS** [comment]
I also have this issue in 6.1.11, but I've noticed that the order in which I start the storybooks matters.

If I start the main storybook (the one with `refs` pointing to the sub-storybook) first, let it finish, and then start the sub-storybook I get the CORS error.  No matter if I refresh after everything has finished.

BUT if I let the sub-storybook start up first, and then bring up the main storybook, it loads up just fine without any errors.  Maybe that provides a clue as to what is going on?

**Comment by rmknecht** [comment]
Double checked with @IanVS recommendation and still see the parent storybook "hanging." The referenced storybooks load normally when opened directly.

I'm building ~7 storybooks from within a mono-repo, and referencing them from a parent storybook that doesn't contain any stories itself. Each storybook is served from the same host, statically. Storybooks include addons such as a11y, knobs, links, and actions.

**Comment by rogemus** [comment]
I have the same problem on v 6.3.6. And my current setup is similar to @rmccue with the only difference being that I have 3 packages and we don't use an a11y addon.

**Comment by nagromLobo** [comment]
Ahh, I'm seeing a similar issue if I run `start-storybook` for the instance that is consuming a `ref` of another storybook, before I have opened that second storybook. Seems like it's a bit different because mine is a race-condition that goes away if I let the consumed storybook start fully before opening the consuming storybook. Feels like a similar root problem, but I have a workaround now!

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
