### ISSUE TITLE
I can't pass icons to controls (type: select) as React Component

### ISSUE THREAD

**Issue by inginging** [storybookjs/storybook#12308]
**Describe the bug**
I want to pass React Components with the controls via the select control type. But it doesn't render. The error I get is: 

> PencilIcon(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.

**Expected behavior**
I want to see the icons when I select the belonging icon on the control

**Screenshots**
![Capture](https://user-images.githubusercontent.com/8210897/91634310-be74c280-e9ef-11ea-9286-48e65660353e.PNG)

**Code snippets**

_button.stories.js_

```
import React from "react";
import { Button } from "../src/";
import {
    PencilIcon,
    TrashcanIcon,
    DownloadIcon,
    ArrowIcon,
} from "../../icons/src";

export default {
    title: "Buttons",
    component: Button,
};

export const button = (args) => {
    return <Button {...args} />;
};

button.argTypes = {
    text: {
        name: "text",
        type: { name: "string", required: true },
        defaultValue: "Button",
        description:
            "You can either pass children or text as a string, not both.",
        control: "text",
    },
    children: {
        description:
            "You can either pass children or text as a string, not both",
    },
    icon: {
        control: {
            type: "select",
            options: {
                PencilIcon: PencilIcon,
                TrashcanIcon: TrashcanIcon,
                DownloadIcon: DownloadIcon,
                ArrowIcon: ArrowIcon,
            },
        },
    },
};
```

_button.js_

```
import React from "react";
import { string, node, bool, func, oneOf, object } from "prop-types";

import classNames from "classnames";

function Button({
    attributes = {},
    children,
    icon = null,
    className = null,
    id = null,
    isDisabled = false,
    isLink = false,
    href = null,
    name = null,
    onClick,
    target = null,
    text = null,
    type = "button",
    variant = "primary",
    size = null,
}) {
    console.log(typeof icon);
    const buttonSize = size ? `Trinity-Button--${size}` : null;

    const classes = classNames(
        "Trinity-Button",
        `Trinity-Button--${variant}`,
        buttonSize,
        { "Trinity-Button--is-disabled": isDisabled },
        className
    );

    const Icon = icon;

    const buttonIcon = () =>
        icon && (
            <span className="Trinity-Button__icon">
                <Icon
                    width={size !== "small" ? "24" : "16"}
                    height={size !== "small" ? "24" : "16"}
                />
            </span>
        );

    if (isLink)
        return (
            <a
                aria-disabled={isDisabled}
                className={classes}
                disabled={isDisabled}
                href={href}
                id={id}
                tabIndex={0}
                target={target}
            >
                {buttonIcon()}
                {text || children}
            </a>
        );

    if (isLink)
        return (
            <a
                aria-disabled={isDisabled}
                className={classes}
                disabled={isDisabled}
                href={href}
                id={id}
                tabIndex={0}
                target={target}
            >
                {icon && (
                    <span className="Trinity-Button__icon">{buttonIcon}</span>
                )}
                {text || children}
            </a>
        );

    return (
        <button
            type={type}
            name={name}
            id={id}
            disabled={isDisabled}
            aria-disabled={isDisabled}
            className={classes}
            tabIndex={0}
            onClick={onClick}
            {...attributes}
        >
            {buttonIcon()}
            {text || children}
        </button>
    );
}

Button.propTypes = {
    attributes: object,
    children: node,
    className: string,
    href: (props, propName) =>
        props.isLink
            ? new Error(`${propName} is required if Button is used as a href`)
            : null,
    icon: func,
    id: string,
    isDisabled: bool,
    isLink: bool,
    name: string,
    onClick: func.isRequired,
    size: oneOf(["small"]),
    target: string,
    text: (props, propName) => {
        if (!props.children && !props.text) {
            return new Error(`${propName} is required if not passing children`);
        }
        if (props.children && props.text) {
            return new Error(
                `${propName} can not be combined with children, either specify ${propName} or pass children, but not both`
            );
        }
        return null;
    },
    type: oneOf(["button", "submit", "reset"]),
    variant: oneOf(["primary", "secondary"]),
};

export default Button;
```

**Comment by Marklb** [comment]
From my understanding of what it going on, it seems like the argTypes are getting serialized by `telejson` when sent to the controls, which is loosing parts of the React object during that serialization/deserialization. I have noticed this with various other object types in Angular as well.

If I am correctly understanding what is going on, these questions may help direct this issue at the problem that needs solving.
- Even though `telejson` supports classes and functions, there are things that can't be serialized, but is there a way that it could predict when a serialization will not be able to deserialize correctly?
- Is it a bug or expected that a React component doesn't correctly revive from telejson's serialization?

After looking into what is happening, it seemed obvious why it would fail, but I don't see a clear solution. If telejson can recognize properties that will not revive correctly, then maybe those could be mapped to a reference and back to the object instance when returning from controls to the story. Deciding what unserializable props are actually an error, since their whole value is need by the control, could be difficult to determine though. I implemented a custom control that could toggle features of a FormControl in Angular, but the FormControl instance couldn't survive the serialization, so I had to use of sort of hacky solution to make sure the changes were reflected on the FormControl instance in the stories iframe. That was just to see if I could make controls work for a component input like that, but I don't know if it is a valid feature that it should support.

@inginging If you just want a workaround, you can keep the React components from being serialized by using a reference in the control. It doesn't look as good, but should at least work.
Example:
```js
import React from "react";
import { Button } from "../src/";
import {
    PencilIcon,
    TrashcanIcon,
    DownloadIcon,
    ArrowIcon,
} from "../../icons/src";

const iconMap = { PencilIcon, TrashcanIcon, DownloadIcon, ArrowIcon }

export default {
    title: "Buttons",
    component: Button,
};

export const button = (args) => {
    const icon = iconMap[args.icon]
    return <Button {...args, icon} />;
};

button.argTypes = {
    text: {
        name: "text",
        type: { name: "string", required: true },
        defaultValue: "Button",
        description:
            "You can either pass children or text as a string, not both.",
        control: "text",
    },
    children: {
        description:
            "You can either pass children or text as a string, not both",
    },
    icon: {
        control: {
            type: "select",
            options: {
                PencilIcon: 'PencilIcon',
                TrashcanIcon: 'TrashcanIcon',
                DownloadIcon: 'DownloadIcon',
                ArrowIcon: 'ArrowIcon',
            },
        },
    },
};
```

**Comment by inginging** [comment]
@Marklb Thank you so much. The workaround helped me.

**Comment by shilman** [comment]
@Marklb that's exactly right--`telejson` (and storybook's channel in general) is a bottleneck in this approach. we probably need to update the documentation accordingly OR adjust the implementation to do something like your workaround internally. Not sure what's the best approach. Thoughts?

**Comment by Marklb** [comment]
@shilman Mentioning it in the documentation would at least give a place to direct people to when they report this.

As for fixing it, the only control types I can think of that would be affected by this currently are the enum types, since the others deal with primatives. If the object used a JSON tree style editor, instead of the textarea, then I could understand it having problems, but knowing that it is edited as a string makes it obvious. Just sending the property names, on the channel, for the options would probably make sense. From what I can tell the properties content doesn't matter for any of the options anyway.

I don't know if there is a plan to let frameworks or addons provide their own control types, like I partially did for Angular's FormControl class(https://media.giphy.com/media/SY8gUWzqNXgwIKzqJT/source.gif), but a beforeSerialization and beforeDeserialization hook/handler could potentially be added. That way the control could handle the problem if it needs to, instead of complicating the implementation for all controls.

**Comment by shilman** [comment]
@Marklb Indeed! https://github.com/storybookjs/storybook/issues/11486

**Comment by shilman** [comment]
Currently args must be JSON serializable (ish), but you can workaround as follows:

```
const ICONS = {
 PencilIcon,
 TrashcanIcon,
 DownloadIcon,
 ArrowIcon,
};

export default {
  ....,
  argTypes: {
    iconName: {
        control: {
          type: "select",
          options: Object.keys(ICONS)
        },
    },
  }
}
```

Then in your story you can do whatever you want with it:

```
const Template = ({ iconName, ...rest }) => {
  const icon = ICONS[iconName];
  return <MyComponent icon={icon} />;
}
```

More info: https://storybook.js.org/docs/react/essentials/controls#fully-custom-args

**Comment by jonniebigodes** [comment]
@inginging sorry for the issue you've ran into. The documentation was recently updated to include additional context on this topic.

@Marklb and @shilman thanks for the help and additional context on this.

Going to close this as it seems to be resolved. Let us know if the problem persists and we can circle back to it.

Stay safe

**Comment by as-zlynn-philipps** [comment]
What about the code snippet that is generated with this approach? I'm getting a noop instead of the icon name, which is confusing to devs trying to generate a usable code snippet:

![image](https://user-images.githubusercontent.com/71240190/104232119-d9375900-541d-11eb-8d09-810da1a93ac5.png)

**Comment by ScorpAL** [comment]
Hi Guys,
Could you please help me to optimize next code?

It works fine, but I feel that I miss something and can utilize duplicated `mapping` in `argTypes`.

```typescript
import {
    Warning,
    Cart,
    Correct,
    Home,
    Info,
    ChevronLeft,
    ChevronRight,
    ChevronDown,
    ArrowLeft,
    ArrowRight
} from '@super/icons';

const iconMap = {
    Warning,
    Cart,
    Correct,
    Home,
    Info,
    ChevronLeft,
    ChevronRight,
    ChevronDown,
    ArrowLeft,
    ArrowRight
};

export default {
    title: 'Store/Button',
    component: Button,
    argTypes: {
        icon: {
            options: [
                'none',
                ...Object.keys(iconMap)
            ],

            // Ho to reduce this ⬇⬇⬇⬇⬇ duplicated mapping?

            mapping: {
                none: null,                       // <---- None used to unselect Icon from button
                Warning: <Warning />,
                Cart: <Cart />,
                Correct: <Correct />,
                Warning: <Warning />,
                Home: <Home />,
                Info: <Info />,
                ChevronLeft: <ChevronLeft />,
                ChevronRight: <ChevronRight />,
                ChevronDown: <ChevronDown />,
                ArrowLeft: <ArrowLeft />,
                ArrowRight: <ArrowRight />,
            },
            control: {
                labels: {
                    none: 'No Icon',
                    ...Object.keys(iconMap)
                }
            }
        }
    }
} as ComponentMeta<typeof Button>;

...

const Template: ComponentStory<typeof Button> = ({ children, icon, ...args }) => {
    const Icon = () => {
        return <>{icon}</>;
    };

    return (
        <Button {...args} icon={<Icon />}> // Need to pass icon in this way as Icons might have additional properties like <SuperIcon width={50} height={80} />
            {children}
        </Button>
    );
};
```

**Comment by ScorpAL** [comment]
Whooh....
utilized a little bit....

```typescript
import {
    Warning,
    Cart,
    Correct,
    Home,
    Info,
    ChevronLeft,
    ChevronRight,
    ChevronDown,
    ArrowLeft,
    ArrowRight
} from '@super/icons';

const iconsMap = {
    Warning: <Warning />,
    Cart: <Cart />,
    Correct: <Correct />,
    Warning: <Warning />,
    Home: <Home />,
    Info: <Info />,
    ChevronLeft: <ChevronLeft />,
    ChevronRight: <ChevronRight />,
    ChevronDown: <ChevronDown />,
    ArrowLeft: <ArrowLeft />,
    ArrowRight: <ArrowRight />
}

export default {
    title: 'Store/Button',
    component: Button,
    argTypes: {
        iconStart: {
            options: [null, ...Object.keys(iconsMap)],
            mapping: {
                none: null,
                ...iconsMap
            }
        }
    }
} as ComponentMeta<typeof Button>;

...

const Template: ComponentStory<typeof Button> = ({ children, icon, ...args }) => {
    const Icon = () => {
        return <>{icon}</>;
    };

    return (
        <Button icon={<Icon />} {...args}>
            {children}
        </Button>
    );
};
```

**Comment by TofuTseng** [comment]
I try all above solution, but still can't pass icon to stories control panel.
Someone can help? I've tried the link below, but still not working.
https://storybook.js.org/docs/react/essentials/controls#dealing-with-complex-values

**Comment by ScorpAL** [comment]
@TofuTseng could you please provide your component story code?
Did you tried [mine ](https://github.com/storybookjs/storybook/issues/12308#issuecomment-1327843058) ?

**Comment by TofuTseng** [comment]
@ScorpAL Hi, I've tried your solution.
I use Next.js with storybook.
Here is my project dependency below:
```javascript
// package.json
"next": "^12.3.1",
"@storybook/addon-actions": "^6.5.14",
"@storybook/addon-essentials": "^6.5.14",
"@storybook/addon-interactions": "^6.5.14",
"@storybook/addon-links": "^6.5.14",
"@storybook/builder-webpack5": "^6.5.14",
"@storybook/manager-webpack5": "^6.5.14",
"@storybook/react": "^6.5.14",
"@storybook/testing-library": "0.0.13",
```

The props "icon" in the RippleButton component, need to pass <IconName /> node element.
And the key code below:
```javascript
// icon.js where icon comes from
import { plus } from 'react-icons-kit/feather/plus';
const Icon = withBaseIcon({ size: 24, style: { color: '#000' } });
export const Plus = () => (
  <Icon icon={plus} size="20" style={{ color: '#000' }} />
);


// RippleButton.stories.jsx
import { Plus, OrangeFlag, Lock } from '@/components/icon/icon';

const icons = {
  Plus,
  OrangeFlag,
  Lock,
};

export default {
  title: 'RippleButton',
  component: RippleButtonComponent,
  argTypes: {
    icon: {
      options: Object.keys(icons),
      mapping: icons,
      control: {
        type: 'select',
        labels: {
          Plus: 'Plus',
          OrangeFlag: 'OrangeFlag',
          Lock: 'Lock',
        },
      },
    },
  },
};


```

What I expect result:
When I select one of the options in the icon props, I want to render the selected icon on the CANVAS panel.
<img width="1192" alt="image" src="https://user-images.githubusercontent.com/75705724/206084898-7178e99a-f4ba-46d5-b481-d11520cd366f.png">


Just my little guess, NEXT.js provide `next/image` to wrap image format.
I will keep trying to import image, or some other format to test.
If you have any idea with this problem, please help, thank you.
