### ISSUE TITLE
Lerna storybook at root and package, addon-docs crash

### ISSUE THREAD

**Issue by ddamato** [storybookjs/storybook#12310]
**Describe the bug**
Docs page crashes after launching a Storybook from the root of a Lerna monorepo. Canvas is fine.
```
Unable to find source for story ID 'design-system-alert--default-story'
Uncaught TypeError: Cannot read property 'fromId' of undefined
    at getStoryProps ...
```

**To Reproduce**

1. Create Lerna monorepo
1. Install storybook at root and a package level
1. Run storybook at root level
1. See error in console after clicking on Docs.

**Expected behavior**
No crash.

**Screenshots**
https://share.getcloudapp.com/7KuLjB1j

**Code snippets**
```js
// ./packages/alert/src/index.js (the component)
import React from 'react';

const Alert = ({ children }) => {
  return <div className='alert'>{ children }</div>;
}

export default Alert;
```

```mdx
// ./packages/alert/src/alert.stories.mdx
import { Meta, Story, Canvas } from '@storybook/addon-docs/blocks';
import Alert from './index.js';

<Meta title="Design System/Alert" component={Alert} />

# Alert

With `MDX` we can define a story for `Alert` right in the middle of our
Markdown documentation.

<Canvas>
  <Story name="Default" args={{ children: 'Hello World' }}>
    { args => <Alert { ...args } /> }
  </Story>
</Canvas>
```

```js
//  ./packages/alert/.storybook/main.js
module.exports = {
  stories: ['../src/**/*.stories.@(js|mdx)'],
  addons: ['@storybook/addon-essentials']
}
```

```js
//  ./.storybook/main.js
module.exports = {
  stories: ['../packages/*/!(node_modules)/**/*.stories.@(js|mdx)'],
  addons: ['@storybook/addon-essentials']
}
```
There is no custom webpack config.

**System:**
```
  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  Binaries:
    Node: 12.16.0 - /usr/local/bin/node
    npm: 6.13.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 84.0.4147.135
    Edge: 85.0.564.41
    Firefox: 80.0
    Safari: 13.1.2
  npmPackages:
    @storybook/addon-essentials: ^6.0.20 => 6.0.20 
    @storybook/react: ^6.0.20 => 6.0.20 
```

**Additional context**
I'm preparing a repo that uses [lerna.js](https://lerna.js.org/) to manage the React components as separate packages. Each package has a `src/component.js` and a `src/component.stories.mdx` file. I've installed Storybook in both the root Lerna package as well as the component package (although I'd really like to do just do this at the root in some future). I've also installed the addon-essentials for both.

The resulting storybook runs fine at the component package level, the Canvas and the Docs show fine. Although I will say that I had to deviate from the guide to writing a story. The `Template.bind()` method resulted in showing the `MDXComponent` instead of the actual component. So my change will be found below.

```mdx
<Story name="Default" args={{ children: 'Hello World' }}>
  { args => <Alert { ...args } /> }
</Story>
```

However, when running at the root level, I initially had an issue where Storybook wouldn't launch at all. This was solved with excluding `node_modules` from the glob path as it went into the component folders. Now the storybook launches and the Canvas renders fine but the Docs page crashes.

The reason why I want the storybook at both is because when working on a component in isolation, I'd like to focus on that work specifically in the component package. However, for library-level review, I'd like storybook to collect everything from the library into one big storybook. Ideally, I'd like [Storybook Composition](https://medium.com/storybookjs/storybook-composition-af0da9084fba) to handle this _without_ needing to run all of the package-level storybooks individually (in other words, a way to not need a url).

Admittedly, I tested the storybook working at the package level first. When that was working, I did the installs for the root level and that's where this issue began.

**Comment by shilman** [comment]
I suspect this is a dependency issue where React is resolving incorrectly when running from the root and the React Context that's being provided to the Docs page is being corrupted. I think the workaround is something to do with yarn resolutions. We're also going to experiment with making React a direct dependency in 6.1 https://github.com/storybookjs/storybook/pull/11628 which might solve this more cleanly

**Comment by ddamato** [comment]
Thanks for the quick reply. Is there anything I can do now to help confirm the suspicion for you?

**Comment by ddamato** [comment]
Just tried uninstalling Storybook from the package-level, and the root-level now runs fine. Canvas and Docs render as expected.

**Comment by ddamato** [comment]
Ok I have a solve for this. Trick is to _not_ install Storybook at the package-level. Leave it at the root level and run `lerna bootstrap --hoist` in the root. This seems to resolve the dependencies properly. You can still run `npm run storybook` at the root-level or the package-level but you'll still need to have a separate config for each component to point specifically to that components stories (shown in the code samples above)

```js
//  ./packages/alert/.storybook/main.js
module.exports = {
  stories: ['../src/**/*.stories.@(js|mdx)'],
  addons: ['@storybook/addon-essentials']
}
```

```js
//  ./.storybook/main.js
module.exports = {
  stories: ['../packages/*/!(node_modules)/**/*.stories.@(js|mdx)'],
  addons: ['@storybook/addon-essentials']
}
```
