### ISSUE TITLE
Documentation for creating custom DocBlocks missing?

### ISSUE THREAD

**Issue by thepeted** [storybookjs/storybook#12314]
https://storybook.js.org/docs/react/writing-docs/doc-blocks hints that "Custom addons can also provide their own doc blocks" and links to the Addon section.  

I am not an experienced addon author however having read the addon API docs I am none the wiser.

Is there a more relevant link or guide that can be provided?

**Comment by cy6erskunk** [comment]
It's been a year, but there seem to be nothing at all. Am I missing something?

**Comment by CallumHoward** [comment]
For anyone that finds this, it's certainly not docs, but it may be possible to reverse engineer from this example here:
https://github.com/pocka/storybook-addon-designs/blob/master/packages/storybook-addon-designs/src/blocks.tsx 

Live example here: https://pocka.github.io/storybook-addon-designs/?path=/story/internal-blocks-iframe--page

**Comment by jonniebigodes** [comment]
Closing this issue per recent pull request to avoid introducing some misconceptions. Once we have a better way to document this I'll circle back to it and reference it. 

Thanks for reaching out to us with your question we appreciate it.

Hope y'all have a great week!

Stay safe
