### ISSUE TITLE
yarn start-storybook => freeze on 95% emitting fork-ts-checker-webpack-plugin

### ISSUE THREAD

**Issue by fmipsylone** [storybookjs/storybook#12311]
**Describe the bug**
Everything is in the issue title

**To Reproduce**
I'm on fresh new angular 10 project. I am in the setup phase preparing all the necessary tools before starting the development. 

Just to mentioned that I used Storybook for two previous projects based on Web Components and I did not meet issues.

So, based on an fresh new angular 10 project:
1. I installed storybook from the CLI command in my fresh angular project.
2. To test the install, I ran the command below (automatically added by storybook during its setup in my `package.json`):
`npm run storybook`  => the besides command is `yarn start-storybook -p 6006` from the `package.json`
3. Everything compiled fine and the web page is opened as well in my browser... So it's OK until then
4. I made a change in the file `stories/Button.stories.ts` (also an example file added by storybook during setup).
I just changed the Button `label` property in the Primary story. Nothing more.
5. The start-storybook watcher detected my change and recompile as expected. And my change appeared in the browser.
6. I made the same change, in the same file on the same property... And... the issue appeared
`95% emitting fork-ts-checker-webpack-plugin`
7. The prompt is frozen and does not exit. I have to `Ctrl+c` to force exit.

And the issues is reproduced each time on the second build pass after a second change I made in any file after the storybook server startup. The first pass always seems to work.

I tried to disable the typescript checker as mentioned in storybook documentation in `.storybook/main.js` ([See here](https://storybook.js.org/docs/react/configure/typescript)):
```
module.exports = {
  typescript: {
    check: false,
    checkOptions: {},
  }
};
```
But it seems that this setup snippet is not taken into account by the build... I tried other setup from `fork-ts-checker-webpack-plugin` package with `fork-ts-checker` config files, `fork-ts-checker` setup in package.json to enable logging, increase memory... But nothing seems to have an effect...

**Expected behavior**
Finish the build and refresh the storybook web page in the browser.

**Screenshots**
![idle-after-start-screenshot](https://user-images.githubusercontent.com/1833732/91641469-e7637a80-ea24-11ea-92ff-9628d3f8724d.png)
**==> Idle after storybook server launch**

![first-pass-idle-screenshot](https://user-images.githubusercontent.com/1833732/91641493-0e21b100-ea25-11ea-8ebc-f5716a63c9f9.png)
**==> First build pass OK after a first change made in a story source file sample `stories/Button.stories.ts`**

![second-pass-freeze-screenshot](https://user-images.githubusercontent.com/1833732/91641500-1a0d7300-ea25-11ea-809e-bc0c778afbbf.png)
**==> Second build pass freezes !!! After the same change made in the same story source file sample  `stories/Button.stories.ts`**

**System:**
```
Environment Info:

  System:
    OS: Linux 3.16 Debian GNU/Linux 8 (jessie) 8 (jessie)
    CPU: (4) x64 Intel(R) Core(TM) i5 CPU       M 480  @ 2.67GHz
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.22.5 - ~/.nvm/versions/node/v12.16.1/bin/yarn
    npm: 6.14.7 - ~/.nvm/versions/node/v12.16.1/bin/npm
  Browsers:
    Chrome: 84.0.4147.135
    Firefox: 60.4.0
  npmPackages:
    @storybook/addon-actions: ^6.0.20 => 6.0.20 
    @storybook/addon-essentials: ^6.0.20 => 6.0.20 
    @storybook/addon-links: ^6.0.20 => 6.0.20 
    @storybook/angular: ^6.0.20 => 6.0.20 
    @storybook/preset-typescript: ^3.0.0 => 3.0.0
```

Thank you all in advance for your help or your tips !

**Comment by Flambe** [comment]
Getting the same issue but with npm

**Comment by shilman** [comment]
Storybook for angular has its own typescript compilation setup independent of the other frameworks. @kroeder can you give any help here?

**Comment by desirelabs** [comment]
Hi, having the same issue with Angular and npm. I'm forced to restart storybook periodically.

**Comment by shilman** [comment]
@desirelabs Looks like maybe a memory leak? WDYT?

**Comment by CappeFra** [comment]
I have the same issue. It happens to me randomly when I run npm test with the following code.
By randomly I mean maybe 1/10 runs everything works and the tests run successfully, but 9/10 times it hangs at 
95% emitting fork-ts-checker-webpack-plugin

```
import { imageSnapshot } from '@storybook/addon-storyshots-puppeteer'

initStoryshots({
  suite : 'Image Snapshots',
  test: imageSnapshot({ storybookUrl: 'http://localhost:6006', getMatchOptions, beforeScreenshot, afterScreenshot })
});
```

**Comment by desirelabs** [comment]
FYI, I have this issue only when saving with vim, not with Visual Studio Code nor Intellij Idea. This is weird, maybe the ts-server used provided with coc-nvim (coc-tsserver).

**Comment by lukaskl** [comment]
(Basically replying due to stale bot)

I still can confirm that our team is still witnessing this issue and so far our workaround it just to retry building storybook multiple times.

**Comment by erhise** [comment]
Can confirm the same issue. Using nvim to save file changes if that in some strange way can be related

**Comment by nathanielgreen** [comment]
I was getting the same problem after re configuring my .vimrc for use with neovim, storybook, and angular.

Adding these 2 line to my .vimrc seemed to solve the issue for me: 
```
set nobackup      " No autocreation of backup files
set nowritebackup " No autocreation of backup files
```

**Comment by erhise** [comment]
I solve the problem with setting `backupcopy=yes`

**Comment by Anzumana** [comment]
Can also confirm that this seems to be related to saving files from vim specifically. very strange . The fix that @nathanielgreen posted work in my case.

**Comment by Anzumana** [comment]
tbh did not expect that an editor could be the cause of this.

**Comment by erhise** [comment]
> Can also confirm that this seems to be related to saving files from vim specifically. very strange . The fix that @nathanielgreen posted work in my case. 

Probably it's something that storybook can fix but I would define at an editor problem primarily

**Comment by Anzumana** [comment]
I think the only thing that is really strange about it, is that when using storybook with react, the issue never occurred.
Thats was the main reason for me why i did not really consider the editor in the first place.

**Comment by PhilippeMorier** [comment]
FYI: I have this problem with WebStorm & Angular 🤔.

**Comment by desirelabs** [comment]
I assume the issue might have different causes. The one I had was with vim, setting `backupcopy=yes` solved it.

**Comment by fmipsylone** [comment]
> I was getting the same problem after re configuring my .vimrc for use with neovim, storybook, and angular. I went through my old settings and managed to narrow down the problem.
> 
> Adding these 2 line to my .vimrc seemed to solve the issue for me:
> 
> ```
> set nobackup      " No autocreation of backup files
> set nowritebackup " No autocreation of backup files
> ```

I think that it would be better to not have to disable Vim features just to be able to use a node package. Maybe an .ignore or a .*rc style file would be preferable.

The problem is that due to the freeze it is very difficult to know where the issue happens. I personally can not say if the responsible package is fork-ts-checker-webpack-plugin or one of its dependencies.

If the issue is sovled with file exclusion for some extensions as @nathanielgreen says, this workaround seems very curious and it would be interesting to know which node package does take temp files in consideration for its parsing and maybe why this package does not follow tsconfig ? or the ts linter ?.

**Comment by chrisodom** [comment]
So I was facing the exact same issue with Storybook 6.3.4 and Angular 12.1.1 running in VS Code command terminal on Windows 10. I also tried to add in several solutions that said to be working to turn off fork-ts-checker-webpack-plugin, but non of them worked as the checker continued to run and freeze every time.  After a lot of playing around trying to find out why this consistently was occurring and just out of frustration of not being able to resolve the issue I deleted the node_modules/.cache/storybook folder and re-ran start-storybook several times and noticed that the storybook cache folder was not being re-created. After a few tries Storybook finally started up correctly no longer freezing at "95% emitting emit fork-ts-checker-webpack-plugin". So at this point I decided that the Storybook cache may have something to do with my issue and decided to add the cli flag to my start-storybook --no-manager-cache. With that one change Storybook now starts consistently every time. I think there is an issue with storybook cache creation and the threaded fork-ts-checker-webpack-plugin. So if you are running into this issue you can try adding the --no-manager-cache to see if this resolves your issue.

**Comment by wabi91** [comment]
[Issue reason]

ForkTsCheckerWebpackPlugin memory leak. (I guess)

[My solution]

Use the type check plugin not on production mode.
So, remove the plugin from the webpackFinal options of stroybook.
```
// storybook/.storybook/main.js

module.exports = {
  // ...
  webpackFinal: async (config) => {
    let ForkTsCheckerWebpackPluginIdx;
    config.plugins.forEach((plugin, idx) => {
      if ('ForkTsCheckerWebpackPlugin' === plugin.constructor.name) {
        ForkTsCheckerWebpackPluginIdx = idx;
      }
    });
    if (
      config.mode === 'production' &&
      ForkTsCheckerWebpackPluginIdx !== undefined
    ) {
      config.plugins.splice(ForkTsCheckerWebpackPluginIdx, 1);
    }

    return config;
  },
};

```

**Comment by valentinpalkovic** [comment]
Please provide a reproduction for Storybook 7 (https://storybook.new) and feel free to reopen the issue, if it is still reproducible.
