### ISSUE TITLE
the `docs` for each component is overwritten with the last one.

### ISSUE THREAD

**Issue by mulder21c** [storybookjs/storybook#12319]
**Describe the bug**

the `docs` for each component is overwritten with the last one.

**To Reproduce**

You can run and see all codes in [codesandbox](https://codesandbox.io/s/dreamy-neumann-0814f)

I wrote some component for test in `/components/`.
You can see 2 components — `Atoms/Buttons/DefaultButton`, `Molecules/Links/LinksGroup` in Storybook.
When I try see `docs` of `DefaultButton`, the docs of the last component `LinksGroup` appear.

**Expected behavior**

It should be able to see the docs for each.

**Screenshots**
![캡처](https://user-images.githubusercontent.com/14821565/91654216-f1977e80-eae1-11ea-854b-de7819711ecd.PNG)
![캡처 2](https://user-images.githubusercontent.com/14821565/91654217-f3f9d880-eae1-11ea-934d-7bd24a7103c9.PNG)

**Code snippets**

You can see my codes in [codesandbox](https://codesandbox.io/s/dreamy-neumann-0814f) or [github](https://github.com/mulder21c/storybook-nuxt-example)

**System:**

On my PC
```bash
Environment Info:

  System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
  Binaries:
    Node: 12.18.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files\nodejs\yarn.CMD
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 84.0.4147.135
    Edge: Spartan (44.18362.449.0)
  npmPackages:
    @storybook/addon-a11y: ^6.0.20 => 6.0.20
    @storybook/addon-actions: ^6.0.20 => 6.0.20
    @storybook/addon-essentials: ^6.0.20 => 6.0.20
    @storybook/addon-links: ^6.0.20 => 6.0.20
    @storybook/source-loader: ^6.0.20 => 6.0.20
    @storybook/vue: ^6.0.20 => 6.0.20
```

on codesandbox
```bash
Environment Info:

  System:
    OS: Linux 5.4 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
  Binaries:
    Node: 10.21.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
  npmPackages:
    @storybook/addon-a11y: ^6.0.20 => 6.0.20
    @storybook/addon-actions: ^6.0.20 => 6.0.20
    @storybook/addon-essentials: ^6.0.20 => 6.0.20
    @storybook/addon-links: ^6.0.20 => 6.0.20
    @storybook/source-loader: ^6.0.20 => 6.0.20
    @storybook/vue: ^6.0.20 => 6.0.20
```

**Comment by shilman** [comment]
I looked into this with @gaetanmaisse 

We observed that Storybook is working as intended except for this line:

https://github.com/storybookjs/storybook/blob/master/lib/core/src/client/preview/loadCsf.ts#L52

Initially, Button stories are loaded with the correct `docs.page` parameter. During the second iteration of the loop, LinkGroup stories are loaded and the Button's `docs.page` is mysteriously overwritten.

Needs more digging to figure out what's going on.

**Comment by shilman** [comment]
This weird behavior is due to a bug in the stories. Both files contain the following line:

```
  parameters={withA11y}
```

`withA11y` is a decorator not a parameter, and somehow setting this causes the `docs.page` conflict to occur. Deleting this line or replacing it with an actual parameters object fixes the problem.

**Comment by mulder21c** [comment]
@shilman Oh..... right!! 
I wrote it wrong. 🤣🤣
Thx.
