### ISSUE TITLE
Documentation: "What's a story" page code snippet is missing

### ISSUE THREAD

**Issue by domyen** [storybookjs/storybook#12316]
**Describe the bug**
The [What's a story](https://storybook.js.org/docs/react/get-started/whats-a-story) page has a snippet missing.

![image](https://user-images.githubusercontent.com/263385/91645822-db70bc00-ea16-11ea-82b3-03c8c22c4fd2.png)

**To Reproduce**

1. Go to [What's a story](https://storybook.js.org/docs/react/get-started/whats-a-story)
2. See that the snippet above is missing

The console also reports an error trying to find the path to the snippet.

![image](https://user-images.githubusercontent.com/263385/91645841-ffcc9880-ea16-11ea-9ca5-141cb3f2374d.png)

**Expected behavior**
The snippet is included.

**Comment by jonniebigodes** [comment]
Closing this as the pull request was just merged.
