### ISSUE TITLE
storybook 6: preview in new tab does not work

### ISSUE THREAD

**Issue by DanielRuf** [storybookjs/storybook#12323]
**Describe the bug**
Opening `http://localhost:6006/iframe.html?id=example-button--primary&viewMode=story` shows nothing, just a blank page.

**To Reproduce**

1. Create a new default sotrybook setup with `npx sb init`
1. Start storybook and go to `http://localhost:6006/iframe.html?id=example-button--primary&viewMode=story`

**Expected behavior**
The rendered component should be visible.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/827205/91715625-4abcec00-eb8e-11ea-8059-9ae8f7b07b4e.png)

**Code snippets**

**System:**
```
  System:
    OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-4710MQ CPU @ 2.50GHz
  Binaries:
    Node: 10.16.0 - ~/.nodenv/versions/10.16.0/bin/node
    Yarn: 1.22.5 - ~/.yvm/shim/yarn
    npm: 6.13.4 - ~/.nodenv/versions/10.16.0/bin/npm
  Browsers:
    Chrome: 81.0.4044.113
    Firefox: 79.0
  npmPackages:
    @storybook/addon-a11y: ^6.0.20 => 6.0.20 
    @storybook/addon-actions: ^6.0.19 => 6.0.20 
    @storybook/addon-console: ^1.2.1 => 1.2.1 
    @storybook/addon-essentials: ^6.0.19 => 6.0.20 
    @storybook/addon-links: ^6.0.20 => 6.0.20 
    @storybook/addon-storysource: ^6.0.20 => 6.0.20 
    @storybook/node-logger: ^6.0.19 => 6.0.20 
    @storybook/preset-create-react-app: ^3.1.4 => 3.1.4 
    @storybook/react: ^6.0.19 => 6.0.20 

```

**Additional context**

**Comment by shilman** [comment]
Sorry I missed this the first time around. Do you have a repro repo you can share?

**Comment by DanielRuf** [comment]
Currently I just have the steps that I've listed.
