### ISSUE TITLE
storybook 6: zoom buttons in docs do not work

### ISSUE THREAD

**Issue by DanielRuf** [storybookjs/storybook#12324]
**Describe the bug**
Clicking the zoom in / out buttons in the docs tab does nothing.

**To Reproduce**

1. Create a new default sotrybook setup with `npx sb init`
1. Start storybook and go to `http://localhost:6006/?path=/docs/example-button--primary`
1. Click on the zoom in / out buttons.

**Expected behavior**
The rendered component should be visible.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/827205/91715739-966f9580-eb8e-11ea-8f33-670941171b87.png)

**Code snippets**

**System:**
```
  System:
    OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-4710MQ CPU @ 2.50GHz
  Binaries:
    Node: 10.16.0 - ~/.nodenv/versions/10.16.0/bin/node
    Yarn: 1.22.5 - ~/.yvm/shim/yarn
    npm: 6.13.4 - ~/.nodenv/versions/10.16.0/bin/npm
  Browsers:
    Chrome: 81.0.4044.113
    Firefox: 79.0
  npmPackages:
    @storybook/addon-a11y: ^6.0.20 => 6.0.20 
    @storybook/addon-actions: ^6.0.19 => 6.0.20 
    @storybook/addon-console: ^1.2.1 => 1.2.1 
    @storybook/addon-essentials: ^6.0.19 => 6.0.20 
    @storybook/addon-links: ^6.0.20 => 6.0.20 
    @storybook/addon-storysource: ^6.0.20 => 6.0.20 
    @storybook/node-logger: ^6.0.19 => 6.0.20 
    @storybook/preset-create-react-app: ^3.1.4 => 3.1.4 
    @storybook/react: ^6.0.19 => 6.0.20 

```

**Additional context**

**Comment by shilman** [comment]
Works in chrome, appears to be broken in FF

**Comment by ndelangen** [comment]
Here's the relevant code:
https://github.com/storybookjs/storybook/blob/3b58f16c33f9145a78beec18318d7dd85d521f72/lib/components/src/blocks/Preview.tsx#L63-L66

**Comment by Tomastomaslol** [comment]
It doesn't look like there is any support for zoom in firefox.

https://caniuse.com/#feat=css-zoom

I think it should be enough to replace it with a `transform: scale()`.  I will give go locally and see if it works! 🙂

**Comment by ndelangen** [comment]
It will, but it will mean the scrollbar will scale as well. This is why `zoom` was used.

**Comment by DanielRuf** [comment]
> It will, but it will mean the scrollbar will scale as well. This is why `zoom` was used.

The scrollbar of an iframe? Should not be the case when you apply scale only on the rendered component(s). Or maybe I missed something.

**Comment by Tomastomaslol** [comment]
> The scrollbar of an iframe? Should not be the case when you apply scale only on the rendered component(s). Or maybe I missed something.

Out of interest, I had a quick play around with this and the behaviour of `zoom` and `transform: scale()`  is quite different.

**Using zoom:**

![zoom](https://user-images.githubusercontent.com/1872246/91849146-ec336300-ec9e-11ea-90ba-986d5bbbec50.gif)

```js
{ zoom = 1 }) => ({
    '> *': {
      zoom: 1 / zoom,
    },

```

**Using transform scale:**

![transform](https://user-images.githubusercontent.com/1872246/91849299-30befe80-ec9f-11ea-99bf-10136d7f4870.gif)

```js
  ({ zoom = 1 }) => ({
    '> *': {
      transform: `scale(${1 / zoom})`,
    },
  }),
```

It's possible that the functionality could be rewritten using `transform scale` but the effort would greater than a simple one-liner.

**Comment by DanielRuf** [comment]
> Out of interest, I had a quick play around with this and the behaviour of `zoom` and `transform: scale()` is quite different.

That is probably because of how it is positioned and some transform-origin issue maybe.

**Comment by ndelangen** [comment]
looks like a `transform-origin: top left` should fix that issue @DanielRuf

**Comment by Tomastomaslol** [comment]
Hi @ndelangen!

I took another look at this issue and tried to replicate the behaviour of the CSS `zoom` using `transform` and `scale`.  I think I managed to create something that is fairly close to original behaviour:

https://github.com/storybookjs/storybook/pull/12845
![firefoxpreview](https://user-images.githubusercontent.com/1872246/96706032-c5adc080-13e1-11eb-8dc1-6883cd04bff9.gif)

If you have some spare time please let me know if you think the solution would work and if you would like me to spend some more time testing/tweaking it to try to get a fix merged.

**Comment by ndelangen** [comment]
@Tomastomaslol of course I do! https://calendly.com/ndelangen/storybook just pick a date & time 👍

**Comment by shilman** [comment]
ZOMG!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.0-rc.6 containing PR #12845 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
