### ISSUE TITLE
Issue with addon-docs not showing generated arg types

### ISSUE THREAD

**Issue by imeredith** [storybookjs/storybook#12333]
**Describe the bug**

Addon docs and controls are not using react-docgen generated props from propTypes. I can specify types manually with argTypes and it works.

**To Reproduce**

I dont have a minimal example for testing with however I will post configuration

`main.js`
```
module.exports = {
    stories: ['../src/**/*.stories.js'],
    addons: [
        '@storybook/preset-scss',
        '@storybook/addon-essentials',
        '@storybook/addon-a11y',
    ],
    webpackFinal: async (config) => {
        config.module.rules = [
            {
                test: /\.svg$/,
                use: ['@svgr/webpack', 'url-loader'],
            },

            ...config.module.rules,
        ]

        config.resolve.alias = {
            ...config.resolve.alias,
            '@': require('path').resolve(__dirname, '../src'),
        }
        return config
    },
}
```
`.babelrc`
```
{
    "presets": [
        [
            "@babel/preset-env",
            {
                "loose": true,
                "shippedProposals": true
            }
        ],
        "@babel/preset-react"
    ],
    "plugins": ["@babel/plugin-proposal-optional-chaining"]
}
```

__docgenInfo from a Component
```
{
  "description": "",
  "methods": [],
  "displayName": "MessageBar",
  "props": {
    "message": {
      "type": {
        "name": "string"
      },
      "required": true,
      "description": ""
    },
    "icon": {
      "type": {
        "name": "string"
      },
      "required": true,
      "description": ""
    }
  }

```
**Expected behavior**

propTypes to populate controls and addon docs liike manually using argTypes does

**Code snippets**

**System:**
  System:
    OS: Linux 5.0 Ubuntu 19.04 (Disco Dingo)
    CPU: (1) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
  Binaries:
    Node: 13.14.0 - ~/.nvm/versions/node/v13.14.0/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v13.14.0/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v13.14.0/bin/npm
  Browsers:
    Chrome: 76.0.3809.100
    Firefox: 72.0.1
  npmPackages:
    @storybook/addon-a11y: ^6.0.20 => 6.0.20 
    @storybook/addon-actions: ^6.0.20 => 6.0.20 
    @storybook/addon-controls: ^6.0.20 => 6.0.20 
    @storybook/addon-docs: ^6.0.20 => 6.0.20 
    @storybook/addon-essentials: ^6.0.20 => 6.0.20 
    @storybook/addon-knobs: ^6.0.20 => 6.0.20 
    @storybook/addon-links: ^6.0.20 => 6.0.20 
    @storybook/addon-storysource: ^6.0.20 => 6.0.20 
    @storybook/addons: ^6.0.20 => 6.0.20 
    @storybook/preset-scss: ^1.0.2 => 1.0.2 
    @storybook/react: ^6.0.20 => 6.0.20 

**Additional context**

I'm fairly sure this is a mis configuration on my end but I just can't see it. Googling issues finds cases were docgenInfo is not present which is not the case here.

**Comment by shilman** [comment]
Are you specifying the `component` property on the default export in your `MessageBar.stories.js` file? If you have a repro repo I could probably diagnose in a few mins.

**Comment by imeredith** [comment]
Well don't I just feel stupid 😄 

I never really understood what the component field was for almost a year it hasn't been a problem as far as I knew, but when migrating to controls I passed over that bit of the docs I guess because I was so used to just ignoring it.

Thanks for the help
