### ISSUE TITLE
Documentation - DocsPage - Add additional explanation of how to replace DocsPage

### ISSUE THREAD

**Issue by novellac** [storybookjs/storybook#12330]
**Is your feature request related to a problem? Please describe.**
I would like to override the `docsPage` with my own documentation. The current [DocsPage documentation](https://storybook.js.org/docs/react/writing-docs/docs-page#replacing-docspage) details how to override the `docsPage` with null but does not suggest how one might replace it with something else (specifically MDX docs). However, [there is a recipe](https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/recipes.md#csf-stories-with-arbitrary-mdx) for this elsewhere.

**Describe the solution you'd like**
Ideally, the [Replacing DocsPage](https://storybook.js.org/docs/react/writing-docs/docs-page#replacing-docspage) section would be reorganized by the three options given (null, MDX, custom component), and snippets would be given for each.

**Describe alternatives you've considered**
As an alternative, it would still be helpful to link to the [recipe](https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/recipes.md#csf-stories-with-arbitrary-mdx).

**Are you able to assist bring the feature to reality?**
I can reorganize the section and write the snippets for MDX. I don't know about the custom component part, so I wouldn't be able to write that part without some help.

**Additional context**

**Comment by sethbro** [comment]
Just ran into an issue that is related enough that I'll comment here.

I was attempting to remix a `DocsPage` using the instructions here: https://storybook.js.org/docs/react/writing-docs/docs-page#remixing-docspage-using-doc-blocks

However, copying this code verbatim only resulted in console errors & a blank page. This was b/c no `DocsContext` was available to the doc block code.

I finally discovered that I needed to add `@storybook/addon-docs` to my `addons` in *main.js*.

However, '@storybook/addon-essentials` with `options: { docs: true }` was already present in my addons list. And obviously basic Docs functionality was already working.

I find the relationship between `addon-essentials` & its component addons confusing, & do not understand when or why both need to be specified in config.

Thanks for listening.

**Comment by shilman** [comment]
@sethbro Sounds like maybe some kind of yarn/npm hoisting issue. `@storybook/addon-essentials` is just a macro that adds an un-configured `@storybook/addon-docs`

**Comment by jonniebigodes** [comment]
@novellac closing this issue as the documentation was already updated by a recent pull request that was pushed by me. Feel free to ping me here if the documentation can be improved in any other way and we'll go from there. Sounds good?

Stay safe!
