### ISSUE TITLE
Storybook running out of memory when building

### ISSUE THREAD

**Issue by huntjosh** [storybookjs/storybook#12348]
**Describe the bug**
After upgrading from 6.0.12 to 6.0.21 when running `npx http-server ./lib/storybook -p 8082 -a localhost` at 69% built I get: `FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory`

Note: in the past we have had the same problem on 5.x versions, which were resolved by upgrading node.

I appreciate this lacks a lot of context, and it's a private repo so I'm unable to share as is, but if anyone is able to point me in the direction of diagnosing or potential causes, that would be of great help.

We are running typescript.

**To Reproduce**

Run `npx http-server ./lib/storybook -p 8082 -a localhost` 

**Expected behavior**
Builds as expected

**System:**
Please paste the results of `npx sb@next info` here.
                                           
  System:                                  
    OS: Windows 10 10.0.19041              
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U
  Binaries:                                
    Node: 12.16.1 - C:\Program Files\nodejs
    npm: 6.13.4 - C:\Program Files\nodejs\n
  Browsers:                                
    Chrome: 84.0.4147.135                  
    Edge: Spartan (44.19041.423.0), Chromiu
  npmPackages:                             
    @storybook/addon-actions: 6.0.21 => 6.0
    @storybook/addon-essentials: 6.0.21 => 
    @storybook/addon-knobs: 6.0.21 => 6.0.2
    @storybook/addon-links: 6.0.21 => 6.0.2
    @storybook/addon-toolbars: 6.0.21 => 6.
    @storybook/addons: 6.0.21 => 6.0.21    
    @storybook/react: 6.0.21 => 6.0.21     
    @storybook/theming: 6.0.21 => 6.0.21

**Comment by shilman** [comment]
What happens if you set the following in `.storybook/main.js`:

```js
module.exports = { 
  typescript: { reactDocgen: 'none' }
}
```

**Comment by ffjanhoeck** [comment]
Having the same issue, since I upgraded from 5.x to 6.x
I am not able to get this fixed. 
Your solution does not work @shilman  :)

**Comment by shilman** [comment]
What about

```js
module.exports = { 
  typescript: { reactDocgen: 'react-docgen' }
}
```

**Comment by ffjanhoeck** [comment]
@shilman Nope, still failing :(

**Comment by shilman** [comment]
Can you scope your `stories` glob in `main.js` more tightly, i.e. make sure it doesn't include node_modules?

**Comment by ffjanhoeck** [comment]
@shilman I am currently just have 5 tiny stories :) How do I make sure not to include the node_modules folder?

**Comment by ffjanhoeck** [comment]
@shilman the `build-storybook` script is working for be but not the `start-storybook -p 6006 -c .storybook` command :) I think that wasn't clear before

**Comment by shilman** [comment]
@ffjanhoeck for example, consider the following two globs:

1. `'../**/*.stories.*'`
2. `'../src/**/*.stories.*'`

the former finds all the stories under the parent directory (which probably includes node_modules and maybe hundreds or thousands of more files). even tho there are only a few stories, the process still scans over a lot.

the latter restricts the search to the `src` directory, which is prob

**Comment by ffjanhoeck** [comment]
@shilman Ok got it. I confirm that the node_modules folder isn't included: `../stories/**/*.stories.@(tsx)`

**Comment by shilman** [comment]
@ffjanhoeck do you have a repro repo?

**Comment by ffjanhoeck** [comment]
@shilman I don't have a reproduction repo - sorry for that :/ Our storybook is mixed with our client, which I am not allowed to share :/

**Comment by latviancoder** [comment]
In our case it happens when running `build-storybook` with `addon-docs` (`6.0.21` or `6.1.0-alpha.17`, doesn't matter).

`92% chunk asset optimization UglifyJsPlugin` runs for a long time and fails.

main.js

```
module.exports = {
  stories: ['../src/**/*.story.@(js|ts|jsx|tsx)'],
  addons: [
    '@storybook/addon-knobs',
    '@storybook/addon-backgrounds',
    '@storybook/addon-actions',
    // '@storybook/addon-docs',
  ],
};
```

Adding `typescript: { reactDocgen: 'none' }` helps but removes prop tables.

**Comment by ffjanhoeck** [comment]
Since I changed the command from
`start-storybook -p 6006 -c .storybook`
to
`node --max_old_space_size=4096 ./node_modules/@storybook/react/bin/index.js -p 6006 -c .storybook`
it works for me!

**Comment by latviancoder** [comment]
I can confirm that this works. 

Although in our case the issue was solved by simply not uglifying storybook build.

**Comment by yury-cx** [comment]
In my case following construction caused error:
`_ => someObj[_?.someProp]`
When I replaced `?.` with && or just extracted `_?.someProp` to the separate variable, the problem disappeared.

It's even more strange, because app build is based exactly on the same webpack and babel config as storybook build and it passes without any problem.

**Comment by gabrielliwerant** [comment]
This is an issue when using storybook in a monorepo (a repo containing many individual packages and their own node_modules folders). It seems that when using default configs, storybook runs out of memory because it is scanning all of the node_modules sub folders. If I remove all the node_modules folders, it works fine. Is there a recommended way to include storybook in a monorepo? I'm thinking I'll have to use a custom webpack config that excludes the appropriate folders.

**Comment by david-shortman** [comment]
@gabrielliwerant Have you tried using the Nx command for your monorepo?
```sh
nx run project-name:build-storybook -o ./path/to/output
```

**Comment by gazpachu** [comment]
Even with 6BG of RAM in docker, the build still fails:

```
INFO[0062] RUN npm install --unsafe-perm --legacy-peer-deps 
INFO[0062] cmd: /bin/sh                                 
INFO[0062] args: [-c npm install --unsafe-perm --legacy-peer-deps] 
INFO[0062] Pushing layer 934763610305.dkr.ecr.ap-northeast-1.amazonaws.com/.../cache:ba662032840e3c5582929a9c68cdd7bfa6ffa753c1a039216d2886f6e9234a82 to cache now 
INFO[0062] Running: [/bin/sh -c npm install --unsafe-perm --legacy-peer-deps] 
<--- Last few GCs --->
[113:0x589ab50]   107832 ms: Scavenge 2000.0 (2067.4) -> 1997.6 (2069.1) MB, 16.8 / 0.0 ms  (average mu = 0.723, current mu = 0.475) allocation failure 
[113:0x589ab50]   107936 ms: Scavenge 2001.6 (2069.1) -> 1999.8 (2072.6) MB, 12.5 / 0.1 ms  (average mu = 0.723, current mu = 0.475) allocation failure 
[113:0x589ab50]   108042 ms: Scavenge 2005.4 (2072.6) -> 2003.3 (2091.4) MB, 16.8 / 0.0 ms  (average mu = 0.723, current mu = 0.475) allocation failure 
<--- JS stacktrace --->
FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory
Segmentation fault (core dumped)
error building image: error building stage: failed to execute command: waiting for process to exit: exit status 139
Cleaning up file based variables
00:00
ERROR: Job failed: command terminated with exit code 1
```

**Comment by gabrielliwerant** [comment]
@david-shortman The project I'm working on does not use nx. I'm looking for a solution within the webpack/rush/storybook ecosystem.

**Comment by Jaraujo6** [comment]
> What happens if you set the following in `.storybook/main.js`:
> 
> ```js
> module.exports = { 
>   typescript: { reactDocgen: 'none' }
> }
> ```

Writing here to say that I have a large production project that builds storybook in CI. Building was fine using SB v5.3 but 6.3 would not work using Webpack 5 because it would run out of memory. Disabling `reactDocgen` did the trick! Thanks Shilman!

**Comment by bohendo** [comment]
I ran into a similar problem & resolved it by removing some source maps.
https://github.com/facebook/create-react-app/issues/8413#issuecomment-924223670

**Comment by MorganIsBatman** [comment]
Kind of related/unrelated, I had the same issue when running init within a package in a Yarn Workspaces monorepo - the out of memory error occurred some time during setup.  Pulling the single package out out of the monorepo (just moved the directory out), running init, then pulling it back in seemed to work.  It builds and runs fine

**Comment by TobiKaestle** [comment]
I just ran into the same error. For me it helped just setting the creation of sourcemap to false in the .storybook/main.js config for vite 2.9.9 with vue 3.2.25 and sb 6.5.9


    async viteFinal(config) {
        config.build.sourcemap = false;
        return config;
    }

**Comment by ryu-man** [comment]
disable the creation of sourcemap in `storybook@6.5.13` works for me

**Comment by jansen-imagem** [comment]
> I just ran into the same error. For me it helped just setting the creation of sourcemap to false in the .storybook/main.js config for vite 2.9.9 with vue 3.2.25 and sb 6.5.9
> 
> ```
> async viteFinal(config) {
>     config.build.sourcemap = false;
>     return config;
> }
> ```

Disabling the sourcemaps also resolved this issue for me in `stroybook@7.0.24` with `vue@3.2` and `vite@4.3`.

**Comment by deluksic** [comment]
We need source maps in order to get test coverage. Why was this closed?

**Comment by alexmnv** [comment]
Had the same issue when the build failed with 4Gb.
Deleting `package-lock.json` with `node_modules` and reinstalling the packages worked for me. Now the build works with just 1Gb.
I have no idea what was the issue though.
