### ISSUE TITLE
@storybook/html - v6 - how to use MDX stories?

### ISSUE THREAD

**Issue by basher** [storybookjs/storybook#12344]
I'm trying to  understand how to correctly author `storybook/html' stories so that I can add additional markdown documentation in the stories.

- My [test repo](https://github.com/basher/storybook-html).
- I have authored both `Button.stories.js` and `Button.stories.mdx` to see what is rendered.
- I have a [separate Parcel repo](https://github.com/basher/parcel-boilerplate-storybook) to bundle my CSS, which I include via `.storybook/preview-head.html` in the repo above.

Despite reading the [addon-docs documentation](https://storybook.js.org/docs/react/writing-docs/introduction), viewing the [html kitchen sink](https://github.com/storybookjs/storybook/tree/next/examples/html-kitchen-sink) examples (which don't have any MDX stories), and looking lots of previously reported docs issues, I still can't figure out how to configure my setup to allow me to view all the available controls and markdown?

If someone could view my repo above and point me in the right direction, that would be very much appeciated.

**System:**
```
Environment Info:

  System:
    OS: Windows 10 10.0.18362       
    CPU: (12) x64 Intel(R) Core(TM) 
i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 12.14.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.1 - C:\Program Files 
(x86)\Yarn\bin\yarn.CMD
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 84.0.4147.135
    Edge: Spartan (44.18362.449.0)  
  npmPackages:
    @storybook/addon-a11y: ^6.0.20 => 6.0.20
    @storybook/addon-actions: ^6.0.20 => 6.0.20
    @storybook/addon-essentials: ^6.0.20 => 6.0.20
    @storybook/addon-links: ^6.0.20 
=> 6.0.20
    @storybook/html: ^6.0.20 => 6.0.20
```

**Additional context**
- I've not used MDX previously, so am coming into this blind. 
- My current experience of `storybook/html` is by way of using **standalone storybook preview** in v5.3, because I use **Parcel** (not Webpack) to bundle my CSS/JS, and this means that `addon-docs` does not work.
- I currently author template literals containing HTML documentation, which I use in my HTML stories. If need be, I can carry on doing this if MDX doesn't work:
```
const SBdocs1 = `
<div class="sb-docs">
    ...some HTML documentation here...
</div>
`;
```

**Comment by PaulieScanlon** [comment]
Hey @basher not entirely sure if this will help, but i've recently put together a docs site using Storybook v6 and MDX. You can see it here: www.mdx-embed.com. As a reference here is one of the the MDX stories which loads the component and uses the `ArgsTable` to create the props table: https://raw.githubusercontent.com/PaulieScanlon/mdx-embed/main/docs/src/components/codePen.stories.mdx

**Comment by basher** [comment]
Thanks @PaulieScanlon - your repo is a React one, where components are defined separately and imported. I've done this before in React projects.

My setup requires me to build HTML representations of components to be integrated into a .NET environment - i.e. I'm using `storybook/html` as a means to assist .NET devs to create the correct HTML for their view components.

After more Googling, I found [this article on embedding docs](https://stackoverflow.com/questions/60966999/storybook-html-for-addon-docs), which I now have working in my test repo. I can therefore write Markdown to document my HTML stories. 😄 

I've also added `<ArgsTable />` as per your setup - unfortunately, this is not currently supported with `storybook/html`. One step forwards, one step back. 🙄

**Comment by basher** [comment]
I'm closing this issue, as I now have working HTML story examples:
- 1 with MDX docs (albeit without `ArgsTable`).
- 1 with CSF docs.

**Comment by kambanwait** [comment]
@basher Do you have this example setup anywhere at all? I'm trying to do the exact same and need to create docPages to show the components working with their code for the devs

**Comment by basher** [comment]
@kambanwait Yes - see my test repo in my original post. It's not been updated for nearly a year, but should still work.

The buttons story references a buttons MDX file for the docs.
