### ISSUE TITLE
When "checked" prop is set to false, exception throws, when true, no exception.

### ISSUE THREAD

**Issue by BorisL91** [storybookjs/storybook#12354]
**Description**
I have a checkbox component that has a "checked" prop and it toggles the behaviour of a basic `<input type="checkbox"/>` element. When the default value of the prop is set to false, toggling it to true throws a React "uncontrolled" component exception. But when the prop is set to true, there is no exception when toggling it back to false.   

**To Reproduce**
1. Checkbox.stories.tsx
```js
export const argTypes = {
  checked: {
    defaultValue: false,
  },
  disabled: {
    defaultValue: false,
  },
  label: {
    defaultValue: "Checkbox label",
  },
  onChange: {
    action: "onChange",
  },
};
export const Standard = (args: CheckboxProps) => (
  <Checkbox {...args}>Checkbox</Checkbox>
);
```

2.Checkbox.tsx
```js
export const Checkbox = ({
  label,
  onChange,
  ...props
}: PropsWithChildren<CheckboxProps>) => {
  const [checkedState, setCheckedState] = useState(props.checked);
  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setCheckedState(e.target.checked);
    if (onChange) onChange(e);
  };
  return (
    <Label>
      <InputCheckbox
        type="checkbox"
        checked={checkedState}
        onChange={handleChange}
      />
      ...
    </Label>
  );
};
```

**Expected behavior**
Component should be able to  set the default value to false, and not throw an exception.

**Screenshots**
[https://imgur.com/VYoVmFr](url)

**Comment by shilman** [comment]
What version? I think I fixed this in the latest release. Do you have a repro repo?

**Comment by BorisL91** [comment]
"@storybook/addon-essentials": "^6.0.20",
    "@storybook/addon-links": "^6.0.20",
    "@storybook/addons": "^6.0.20",
    "@storybook/node-logger": "^6.0.20",
    "@storybook/react": "^6.0.20",

No I don't, but I can set it up. Thanks for checking this out! Cheers
