### ISSUE TITLE
addon-backgrounds not working on storybooks added throught composition

### ISSUE THREAD

**Issue by luiswouters** [storybookjs/storybook#12359]
**Describe the bug**
When I'm loading other storybooks throught composition, the backgrounds addon only works in the main storybook (the one that is loading the others). If I click to see a story from the storybook loaded, and the story has the ability to change background, the options show in the menu, but when I select an option, nothing occurs.

Debugging, I can see that there are multiple iframes for preview, one for the main storybook and others for each storybook loaded. When I select a background in a storybook loaded, it changes the background color of the main storybook preview.

**To Reproduce**

1 - In a storybook that has backgrounds addon, add another storybook throught composition, that has backgrounds addon as well.

You need to add in the .storybook/main.js:

`refs: {
    "another-storybook": {
      title: "Another storybook",
      url: "http://url-of-the-storybook",
},`

2 - Run the storybook;

3 - Click in a story that has backgrounds options of the added storybook;

4 - Select a background. 

**Expected behavior**
The story should get the background selected.

**Screenshots**
![Captura de tela de 2020-09-02 12-00-05](https://user-images.githubusercontent.com/64574/92001092-a44f2300-ed14-11ea-9793-b8bc5026efe6.png)
![Captura de tela de 2020-09-02 12-00-22](https://user-images.githubusercontent.com/64574/92001091-a44f2300-ed14-11ea-9ea2-ce85860e8477.png)

**System:**
Environment Info:

  System:
    OS: Linux 5.4 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz
  Binaries:
    Node: 12.16.1 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.14.0 - /usr/local/bin/npm
  Browsers:
    Firefox: 79.0
  npmPackages:
    @storybook/addon-actions: ^6.0.21 => 6.0.21 
    @storybook/addon-backgrounds: ^6.0.21 => 6.0.21 
    @storybook/addon-info: ^5.3.21 => 5.3.21 
    @storybook/addon-knobs: ^6.0.21 => 6.0.21 
    @storybook/addon-storysource: ^6.0.21 => 6.0.21 
    @storybook/addons: ^6.0.21 => 6.0.21 
    @storybook/api: ^6.0.21 => 6.0.21 
    @storybook/channels: ^6.0.21 => 6.0.21 
    @storybook/client-logger: ^6.0.21 => 6.0.21 
    @storybook/core-events: ^6.0.21 => 6.0.21 
    @storybook/react: ^6.0.21 => 6.0.21 
    @storybook/router: ^6.0.21 => 6.0.21 
    @storybook/theming: ^6.0.21 => 6.0.21

**Comment by shilman** [comment]
We need to figure out how to properly handle addons across composed storybooks. For now we should update the documentation to reflect that addons in composed storybooks don't work @jonniebigodes

**Comment by shilman** [comment]
Updated the documentation above 👆
