### ISSUE TITLE
Props first tab renamed to `Story` when using args

### ISSUE THREAD

**Issue by CPatchane** [storybookjs/storybook#12357]
**Describe the bug**
When using `args` in a CSF story with subcomponents, the main props table tab is renamed to `Story` instead of using the main component name.

**To Reproduce**
Setup a standard CSF story (no MDX)

```ts
// Tabs.stories.tsx

import React, { useState } from "react"
import { Story, Meta } from "@storybook/react/types-6-0"

import Tabs, { TabsPropsType } from "./"

export default {
  title: "Tabs",
  component: Tabs,
  subcomponents: { "Tabs.Tab": Tabs.Tab },
} as Meta

export const Basic: Story<TabsPropsType> = (args) => {
  return (
    <Tabs myProp={args.myProp}>
      <Tabs.Tab label="hello">Hello world!</Tabs.Tab>
      <Tabs.Tab label="hello2">Hello world 2!</Tabs.Tab>
      <Tabs.Tab label="hello3">Hello world 3!</Tabs.Tab>
    </Tabs>
  )
}
```

When I remove the `args` usage in the story, the tab is back to the right name, `Tabs` here.

**Expected behavior**
Have the first tab named with the component name

**Screenshots**
<img width="1164" alt="Screenshot 2020-09-02 at 16 12 14" src="https://user-images.githubusercontent.com/10224453/91994811-5566b500-ed37-11ea-92a9-3b29f38a9ef2.png">

**System:**
  System:
    OS: macOS 10.15.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 12.5.0 - ~/.nodenv/versions/12.5.0/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nodenv/versions/12.5.0/bin/npm
  Browsers:
    Chrome: 85.0.4183.83
    Safari: 13.1
  npmPackages:
    @storybook/addon-essentials: 6.0.21 => 6.0.21
    @storybook/addon-knobs: 6.0.21 => 6.0.21
    @storybook/addons: 6.0.21 => 6.0.21
    @storybook/react: 6.0.21 => 6.0.21

**Comment by yotavm** [comment]
👍

**Comment by hadnet** [comment]
I confirm this even using last version 6.1. I'm using MDX as a workaround..

**Comment by bigwoof91** [comment]
I too can confirm, this is still an issue in `6.1.2`

**Comment by artmsilva** [comment]
I can confirm still an issue in `6.1.10`.

**Comment by somenickname** [comment]
Hi, @shilman. Could your please review PR #3845?

**Comment by shilman** [comment]
Yippee!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.0-alpha.31 containing PR #13845 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
