### ISSUE TITLE
Can i change Storybook code viewer stlye ?

### ISSUE THREAD

**Issue by SuperWallaby** [storybookjs/storybook#12350]
**I want to change the style of Code Viewer Part **

I followed the document. 

And the result was

![image](https://user-images.githubusercontent.com/46065365/91939400-ba6adc80-ed30-11ea-88cf-3d9ca0090069.png)

I want to change the line spacing and code color to a different theme, but I am not sure how to do it even if I search the documentation.

It is `<Primary  />` tag of '`@storybook/addon-docs/blocks'`
And I am using storybook 6

I hope it's a feature that exists.

**Comment by shilman** [comment]
I would try CSS escape hatches

https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/theming.md#css-escape-hatches
