### ISSUE TITLE
Storyshots: Incorrect typings for method "test"

### ISSUE THREAD

**Issue by nknapp** [storybookjs/storybook#12361]
**Describe the bug**
In the file `StoryshotsOptions.ts` the method [test](https://github.com/storybookjs/storybook/blob/master/addons/storyshots/storyshots-core/src/api/StoryshotsOptions.ts#L15) is defined as 

```ts
(story: any, context: any, renderTree: RenderTree, options?: any) => any;
```
But in the [snapshotsTestTemplate](https://github.com/storybookjs/storybook/blob/master/addons/storyshots/storyshots-core/src/api/snapshotsTestsTemplate.ts#L28-L31), it is called as

```ts
        testMethod({
          story: item,
          context,
          ...testMethodParams,
        }),
```

where `...testMethodParams` is defined in [src/api/index.ts](https://github.com/storybookjs/storybook/blob/f65084dc787f7bd1df8492da22bff34e5262790b/addons/storyshots/storyshots-core/src/api/index.ts#L46-L48) as 

```ts
{
    renderTree,
    renderShallowTree,
    stories2snapsConverter,
  };
```

**To Reproduce**

Create 
1. Create a new project with storybook (usin `sb init` to get some default stories)
2. Add Storyshots
3. Run the following test

```ts
import initStoryshots from "@storybook/addon-storyshots";

describe("test", () => {
  initStoryshots({
    framework: "react",
    suite: "All",
    test: (story, context, renderTree, options): any => {
      console.log({ story, context, renderTree, options });
    }
  });
});

```

**Expected behavior**
Based on the typings, I would have expected an output that matches the types, but the output is 

```
{
   story: {id: 'app--default', kind: ...  },
   context: {...}
   renderTree: [Function: getRenderedTree]
   options: ...
```
The actual output is 

```
 console.log src/inspect.test.ts:8
    { story:
       { story:
          { id: 'app--default',
            kind: 'App',
            name: 'Default',
            story: 'Default',
            hooks: [HooksContext],
            getDecorated: [Function],
            getOriginal: [Function: getOriginal],
            storyFn: [Function: storyFn],
            parameters: [Object],
            args: {},
            argTypes: {},
            initialArgs: {},
            globals: {},
            render: [Function: storyFn],
            fileName: './App.stories.tsx' },
         context:
          { id: 'app--default',
            kind: 'App',
            name: 'Default',
            story: 'Default',
            hooks: [HooksContext],
            getDecorated: [Function],
            getOriginal: [Function: getOriginal],
            storyFn: [Function: storyFn],
            parameters: [Object],
            args: {},
            argTypes: {},
            initialArgs: {},
            globals: {},
            render: [Function: storyFn],
            fileName: './App.stories.tsx',
            framework: 'react' },
         renderTree: [Function: getRenderedTree],
         renderShallowTree: [Function: getRenderedTree],
         stories2snapsConverter:
          Stories2SnapsConverter { getSnapshotExtension: [Function], options: [Object] } },
      context: undefined,
      renderTree: undefined,
      options: undefined }
```

It seems like the of the `test`-method should be something like:

```
 test?: (args: {
    story: any;
    context: any;
    renderTree: RenderTree;
    renderShallowTree: RenderTree;
    stories2SnapsConverter: Stories2SnapsConverter;
  }) => any;
```

**System:**
  System:
    OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i7-3687U CPU @ 2.10GHz
  Binaries:
    Node: 10.18.0 - ~/.nvm/versions/node/v10.18.0/bin/node
    npm: 6.14.5 - ~/.nvm/versions/node/v10.18.0/bin/npm
  Browsers:
    Chrome: 79.0.3945.88
    Firefox: 80.0
  npmPackages:
    @storybook/addon-actions: ^6.0.16 => 6.0.16 
    @storybook/addon-essentials: ^6.0.16 => 6.0.16 
    @storybook/addon-links: ^6.0.16 => 6.0.16 
    @storybook/addon-storyshots: ^6.0.20 => 6.0.20 
    @storybook/node-logger: ^6.0.16 => 6.0.16 
    @storybook/preset-create-react-app: ^3.1.4 => 3.1.4 
    @storybook/react: ^6.0.16 => 6.0.16 

**Additional context**

**Comment by shilman** [comment]
@nknapp any chance you can submit a fix in a PR?

**Comment by shilman** [comment]
ZOMG!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.0-alpha.20 containing PR #12389 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.
