### ISSUE TITLE
Storybook composition: very slow load

### ISSUE THREAD

**Issue by Diokuz** [storybookjs/storybook#12372]
We have two storybooks: first with 150 components (~1000 stories), second with 15 stories.

We tried to add second storybook to the first. As a result, the first storybook starts to load 2 times slower: 4 seconds instead of just 2 seconds (measurements done when both storybooks served from localhost).

What could be done here? Could we postpone to fetch anything from the second storybook (except stories.json, of course) until the initial click to its stories?

**Comment by ndelangen** [comment]
Storybook 7 comes with an storyIndexer, generating a `index.json` both during dev & prod mode.
This solves this issue completely.
