### ISSUE TITLE
typography is undefined

### ISSUE THREAD

**Issue by yoannfleurydev** [storybookjs/storybook#12373]
**Describe the bug**

Blank page on project initialization.

`Uncaught TypeError: typography is undefined`

**To Reproduce**

1. Run `npx -p @storybook/cli sb init` in the [root repository](https://github.com/CodeursEnSeine/codeursenseine-new)
2. Run `yarn storybook`
3. The browser is open on http://localhost:6006/ but is blank.

**Expected behavior**

I should see the UI.

**Screenshots**

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/3920615/92137396-5c5ff700-ee0d-11ea-97bd-196d0d2556f2.png">

**System:**

Environment Info:

  System:
    OS: macOS 10.15.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 12.18.2 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
  Browsers:
    Chrome: 85.0.4183.83
    Edge: 85.0.564.44
    Firefox: 80.0
    Safari: 13.1.2

**Additional context**

I try to run this in a Gatsby repository: https://github.com/CodeursEnSeine/codeursenseine-new

**Comment by Glockenbeat** [comment]
Same error here, after doing the following upgrades in a previously running project:

@storybook/addon-storyshots: 6.0.0-rc.18 -> 6.0.21
@storybook/react: 5.3.19 -> 6.0.21

**Comment by shilman** [comment]
Did you try removing `node_modules` and/or lockfiles and reinstalling?

**Comment by yoannfleurydev** [comment]
Hi, yes, a clean install: `rm -rf node_modules`, `yarn`, `npx -p @storybook/cli sb init`, `yarn storybook` and still experience this issue.

I also did try with `npm` to check, same issue.

**Comment by yoannfleurydev** [comment]
I tried an update of all the dependencies in the project, and it did work for me.

I'm closing this as I opened this one, but feel free to re-open if it is relevant later.

Keep going on the good work on Storybook 👍

**Comment by deterralba** [comment]
FYI I had the same issue on Firefox. The issue was slightly different on chrome: see https://github.com/storybookjs/storybook/issues/12016
Using `npm dedupe` fixed it for me https://docs.npmjs.com/cli/dedupe
