### ISSUE TITLE
Storybook not work in Chrome Version 85.0.4183.83 (Mac)

### ISSUE THREAD

**Issue by josetucuman** [storybookjs/storybook#12384]
** ERROR in ./.storybook/generated-refs.js **

**To Reproduce**

1. I created a new Storybook with 'npx sb init'
2. I try run with yarn storybook (it's my first app)
3. And Not work...

<img width="1348" alt="Screen Shot 2020-09-04 at 11 20 19 AM" src="https://user-images.githubusercontent.com/7595343/92249618-c1b0f800-eea0-11ea-9b8c-c728b5e5b9a7.png">

**System:**
Environment Info:

  System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
  Binaries:
    Node: 12.13.1 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.7 - /usr/local/bin/npm
  Browsers:
    Chrome: 85.0.4183.83
    Firefox: 79.0
    Safari: 13.1.2
  npmPackages:
    @storybook/addon-actions: ^6.0.21 => 6.0.21 
    @storybook/addon-essentials: ^6.0.21 => 6.0.21 
    @storybook/addon-links: ^6.0.21 => 6.0.21 
    @storybook/node-logger: ^6.0.21 => 6.0.21 
    @storybook/preset-create-react-app: ^3.1.4 => 3.1.4 
    @storybook/react: ^6.0.21 => 6.0.21

**Comment by shilman** [comment]
Do you have a repro repo you can share?

**Comment by josetucuman** [comment]
> Do you have a repro repo you can share?

Hi Shilman, thanks, my repo is https://github.com/josetucuman/ejmstorybook

**Comment by shilman** [comment]
@josetucuman storybook is not installed in that repo

**Comment by josetucuman** [comment]
Hi Michael, thanks a los for your response. Now I find this repo and send
again

**Comment by josetucuman** [comment]
> @josetucuman storybook is not installed in that repo

Hi friend, now I send this story, thanks a lot!!!

**Comment by shilman** [comment]
closing as dupe to #11907
