### ISSUE TITLE
Version 6.1.0-alpha.0 doesn’t work in IE11 because of highlight  dependence

### ISSUE THREAD

**Issue by pavel-sindelka** [storybookjs/storybook#12399]
**Describe the bug**

**Stroybook 6.1.0-alpha.0** depends on **react-syntax-highlighter 13.2.1** which depends on **highlight ^10.1.1** and **lowlight ^1.14.0** dependencies but according to the [changelog of highlight](https://github.com/highlightjs/highlight.js/blob/master/VERSION_10_BREAKING_CHANGES.md) IE11 will no longer be supported
> "We're now using ES2015 features in the codebase. Internet Explorer 11 is no longer supported."

**Screenshots**
![image](https://user-images.githubusercontent.com/11405232/92386106-676b9d80-f113-11ea-8862-a70263b0a9f5.png)
![image (1)](https://user-images.githubusercontent.com/11405232/92386110-69cdf780-f113-11ea-9820-95418260c5f4.png)

**Comment by fernandopasik** [comment]
would it be possible to understand if a polyfill is needed for ie11 or something?
Could you post the errors in english as well please?

**Comment by fernandopasik** [comment]
BTW the upgrade was necessary because of a security issue.

**Comment by pavel-sindelka** [comment]
Its syntax error because IE 11 cant interpret classes

**Comment by fernandopasik** [comment]
might need to pass the library by the babel config, maybe there's a place we can add that in storybook babel config

@shilman any hint where that could be?

**Comment by shilman** [comment]
@ndelangen and @tooppaaa worked on recompiling the libraries for IE compatibility. Hopefully they can lend a hand here.

**Comment by tooppaaa** [comment]
If someone has a chance to look at it before me, probably a dependency needs to be added to this regexp:
https://github.com/storybookjs/storybook/blob/next/lib/core/src/server/common/es6Transpiler.js

**Comment by tooppaaa** [comment]
https://github.com/obahareth/are-you-es5/issues/53

**Comment by fernandopasik** [comment]
sounds like from this comment https://github.com/storybookjs/storybook/pull/12811#issuecomment-724982157 this issue was resolved @tooppaaa ?

**Comment by fernandopasik** [comment]
@pavel-sindelka have you tried again with the latest version of storybook?

**Comment by diogofscmariano** [comment]
This introduced a breaking change in a minor version and I think the commit https://github.com/storybookjs/storybook/commit/781c2ae429edb545cb4a5c545b0a5569ddc058a4 should just be reverted and a have a patch release. 
Meanwhile, we will revert to the latest 6.0.x while the is no update on this.

**Comment by tooppaaa** [comment]
> @pavel-sindelka have you tried again with the latest version of storybook?

Same thing @diogofscmariano, it should work without any change on your side.

**Comment by fernandopasik** [comment]
@diogofscmariano it wasn't just because the change, there were security vulnerabilities with the dependencies.

It wasn't a breaking change as the work was done to reach feature parity. There was just an issue with IE11 and from https://github.com/storybookjs/storybook/pull/12811#issuecomment-724982157 looks like it's resolved.

Are you still having problems with it?

**Comment by jackysee** [comment]
The fix mention in #12948 is not on the 6.1.x release branch.

**Comment by shilman** [comment]
@jackysee does 6.2 alpha work for you?

**Comment by jackysee** [comment]
Unfortunately, 6.2 alpha has problem #13562 in IE11. Should be related to addon-docs

**Comment by tooppaaa** [comment]
This issue is now quite old and is fixed if I'm not mistaken.
@jackysee, if there's still something not working with the released 6.2, please create a new issue :)
