### ISSUE TITLE
docs.description.story ="..." not showing up

### ISSUE THREAD

**Issue by florianmatz** [storybookjs/storybook#12397]
**Describe the bug**
The description `docs.description.story` is not showing up on the Docs Page, the deprecated `storyDescription` does.

**To Reproduce**
Use the following config

`
export default {
    title: 'Components / Navigation',
    component: NdNavigation,
    decorators: [storyFn => <div className="nd-mui-navigation-preview do-not-use-this-div">{storyFn()}</div>],
    parameters: {
        componentSubtitle: 'Generates a navigation utilizing MUIs drawer component.',
        docs: {
            description: {
                component: `import { NdNavigation } from 'nd-component-factory'; <br> 
                import { NdNavigation } from 'nd-component-factory/components'; <br> 
                import NdNavigation from 'nd-component-factory/NdNavigation'; <br>`,
                story: 'NEW NEW NEW',
            },
            storyDescription: 'Some Story description',
        },
    }, [..]
`

**Expected behavior**
Parameter should be visible

**Screenshots**
![grafik](https://user-images.githubusercontent.com/4760056/92363415-c15b6b80-f0f1-11ea-8931-ed73d0cc9b17.png)

![Bildschirmfoto 2020-09-07 um 10 10 35](https://user-images.githubusercontent.com/4760056/92363862-71c96f80-f0f2-11ea-9b97-27088f90ed3b.png)

**Code snippets**
See above

**System:**
Environment Info:

  System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
  Binaries:
    Node: 14.9.0 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
  Browsers:
    Chrome: 85.0.4183.83
    Firefox: 80.0
    Safari: 13.1
  npmPackages:
    @storybook/addon-actions: ^6.0.21 => 6.0.21 
    @storybook/addon-essentials: ^6.0.21 => 6.0.21 
    @storybook/addon-links: ^6.0.21 => 6.0.21 
    @storybook/react: ^6.0.21 => 6.0.21 
  npmGlobalPackages:
    @storybook/cli: 6.0.21

**Additional context**
I appreciate your work incredibly, but I find the documentation on how to customize the docs page with parameters rather confusing. I would help just to have a table with all possible parameters. You'lle only find a fraction here, a bit there spreaded all over the docs and some links to github.

**Comment by shilman** [comment]
Working in the monorepo. Do you have a repro repo?

https://github.com/storybookjs/storybook/blob/next/examples/official-storybook/stories/demo/button.stories.js#L42

**Comment by florianmatz** [comment]
@shilman Hi Michael, just created a repo: https://github.com/florianmatz/sb-docs-bug-demo.

Also included the same code you had in your demo.

`Default.parameters = {
    docs: {
        storyDescription: 'Foobar',
        description: {
            story: 'This demonstrates react hooks working inside stories. **Go team!** 🚀',
        },
    },
};`

Also here, storyDescription is displayed, description.story not.

**Comment by shilman** [comment]
@florianmatz thanks for the repro. the bug was actually with `storyDescription`, which shouldn't be shown for the primary (first) story, only for the other stories on the page

**Comment by shilman** [comment]
Ooh-la-la!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.0-alpha.16 containing PR #12563 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
