### ISSUE TITLE
Broken Storyshots with latest jest-preset-angular due to setupJest module being renamed to setup-jest on ^8.3.0

### ISSUE THREAD

**Issue by KostasDimakis** [storybookjs/storybook#12392]
**Describe the bug**

The `jest-preset-angular` library has a breaking change (and the only one that I've come across) introduced on its `v8.3.0` release. They've renamed the `setupJest` file to `setup-jest`. 

This loader `storybook/addons/storyshots/storyshots-core/src/frameworks/angular/loader.ts` is requiring `setupJest`.

**To Reproduce**

Use the latest `storyshots` with `"jest-preset-angular": "^8.3.0"`, run `jest` and you'll get the following

```
Cannot find module 'jest-preset-angular/build/setupJest' from 'node_modules/@storybook/addon-storyshots/dist/frameworks/angular/loader.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:307:11)
      at requireActual (node_modules/@storybook/addon-storyshots/dist/frameworks/angular/loader.js:32:10)
      at Object.setupAngularJestPreset [as load] (node_modules/@storybook/addon-storyshots/dist/frameworks/angular/loader.js:38:5)
      at Object.load [as default] (node_modules/@storybook/addon-storyshots/dist/frameworks/frameworkLoader.js:26:19)
      at testStorySnapshots (node_modules/@storybook/addon-storyshots/dist/api/index.js:60:14)

```

**Expected behavior**

The tests should run normally.

**Screenshots**
N/A

**Code snippets**
N/A

**System:**
N/A

**Additional context**
N/A

Please let me know if it's alright to raise a PR for this.

**Comment by shilman** [comment]
@KostasDimakis PRs very welcome!

**Comment by andyleeboo** [comment]
I got the same error while following the official guide [Learn Storybook](https://www.learnstorybook.com/intro-to-storybook/angular/en/simple-component/). 

● Test suite failed to run

    Cannot find module 'jest-preset-angular/build/setup-jest' from 'node_modules/@storybook/addon-storyshots/dist/frameworks/angular/loader.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)
      at setupAngularJestPreset (node_modules/@storybook/addon-storyshots/dist/frameworks/angular/loader.js:36:14)
      at Object.load (node_modules/@storybook/addon-storyshots/dist/frameworks/angular/loader.js:43:5)
      at Object.loadFramework [as default] (node_modules/@storybook/addon-storyshots/dist/frameworks/frameworkLoader.js:26:19)
      at testStorySnapshots (node_modules/@storybook/addon-storyshots/dist/api/index.js:60:14)

**Comment by marcelobotega** [comment]
Hi,
I got the same error on jest-preset-angular 9+

```
    Cannot find module 'jest-preset-angular/build/setup-jest' from 'node_modules/@storybook/addon-storyshots/dist/ts3.9/frameworks/angular/loader.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/resolver.js:313:11)
      at setupAngularJestPreset (node_modules/@storybook/addon-storyshots/dist/ts3.9/frameworks/angular/loader.js:36:14)
      at Object.load (node_modules/@storybook/addon-storyshots/dist/ts3.9/frameworks/angular/loader.js:43:5)
      at Object.loadFramework [as default] (node_modules/@storybook/addon-storyshots/dist/ts3.9/frameworks/frameworkLoader.js:26:19)
      at Object.testStorySnapshots [as default] (node_modules/@storybook/addon-storyshots/dist/ts3.9/api/index.js:42:14)
```

In version 9+ there's a breaking change where the setup-jest file was changed to the root folder of the library.
[jest-preset-angular changelog](https://github.com/thymikee/jest-preset-angular/blob/master/CHANGELOG.md#900-2021-05-27)

The loader.js should change the import from `jest.requireActual('jest-preset-angular/build/setup-jest');` to `jest.requireActual('jest-preset-angular/setup-jest');`

**Comment by paulo-zacarias** [comment]
> ###
I'm experiencing exactly the same, any developments regarding this issue?

**Comment by paulo-zacarias** [comment]
> Hi, I got the same error on jest-preset-angular 9+
> 
> ```
>     Cannot find module 'jest-preset-angular/build/setup-jest' from 'node_modules/@storybook/addon-storyshots/dist/ts3.9/frameworks/angular/loader.js'
> 
>       at Resolver.resolveModule (node_modules/jest-resolve/build/resolver.js:313:11)
>       at setupAngularJestPreset (node_modules/@storybook/addon-storyshots/dist/ts3.9/frameworks/angular/loader.js:36:14)
>       at Object.load (node_modules/@storybook/addon-storyshots/dist/ts3.9/frameworks/angular/loader.js:43:5)
>       at Object.loadFramework [as default] (node_modules/@storybook/addon-storyshots/dist/ts3.9/frameworks/frameworkLoader.js:26:19)
>       at Object.testStorySnapshots [as default] (node_modules/@storybook/addon-storyshots/dist/ts3.9/api/index.js:42:14)
> ```
> 
> In version 9+ there's a breaking change where the setup-jest file was changed to the root folder of the library. [jest-preset-angular changelog](https://github.com/thymikee/jest-preset-angular/blob/master/CHANGELOG.md#900-2021-05-27)
> 
> The loader.js should change the import from `jest.requireActual('jest-preset-angular/build/setup-jest');` to `jest.requireActual('jest-preset-angular/setup-jest');`

I'm experiencing exactly the same, any developments regarding this issue?

**Comment by paulo-zacarias** [comment]
From the jest-preset-angular [CHANGELOG](https://github.com/thymikee/jest-preset-angular/blob/main/CHANGELOG.md): 

**serializers::** snapshot serializer paths have been changed:
`'jest-preset-angular/build/AngularNoNgAttributesSnapshotSerializer.js'` is changed to `'jest-preset-angular/build/serializers/no-ng-attributes.`
`'jest-preset-angular/build/AngularSnapshotSerializer.js'` is changed to `'jest-preset-angular/build/serializers/ng-snapshot`.
`'jest-preset-angular/build/HTMLCommentSerializer.js'` is changed to `'jest-preset-angular/build/serializers/html-comment`.

**Comment by DSteinmann** [comment]
You can also map the modules until this is fixed in your jest.config.js: 
```  moduleFileExtensions: ['ts', 'js', 'html', 'json', 'mjs'],
  moduleNameMapper: {
    'jest-preset-angular/build/setup-jest': 'jest-preset-angular/setup-jest',
    'jest-preset-angular/build/AngularNoNgAttributesSnapshotSerializer':
      'jest-preset-angular/build/serializers/no-ng-attributes',
    'jest-preset-angular/build/AngularSnapshotSerializer':
      'jest-preset-angular/build/serializers/ng-snapshot',
    'jest-preset-angular/build/HTMLCommentSerializer':
      'jest-preset-angular/build/serializers/html-comment'
  },

**Comment by paulo-zacarias** [comment]
@DSteinmann Thank you, that works!

**Comment by ndelangen** [comment]
The future of storyshots is the test-runner:
https://storybook.js.org/docs/react/writing-tests/test-runner#page-top

And use the play function for expectations:
https://storybook.js.org/docs/react/writing-stories/play-function#page-top

We will not be making any improvement / changes to storyshots.
