### ISSUE TITLE
Storybook/html - unable to fetch external JSON data to build story HTML

### ISSUE THREAD

**Issue by basher** [storybookjs/storybook#12398]
**Describe the bug**
I have an HTML story that needs to fetch JSON data from a different repo.

I get no HTML rendered, and no console errors, just `[object Promise]` as per screenshot below.

Possibly related to [10009](https://github.com/storybookjs/storybook/issues/10009)?

**To Reproduce**
See `FetchData` story in [my simple test repo](https://github.com/basher/storybook-html).

**Expected behavior**
HTML to be rendered, generated from JSON.

**Screenshots**
![FetchData](https://user-images.githubusercontent.com/452809/92362998-b819d100-f0e8-11ea-9cfa-d7f9e6c7a69c.jpg)

**System:**
```
System:
    OS: Windows 10 10.0.18362       
    CPU: (12) x64 Intel(R) Core(TM) 
i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 12.14.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.1 - C:\Program Files 
(x86)\Yarn\bin\yarn.CMD
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 85.0.4183.83
    Edge: Spartan (44.18362.449.0)  
  npmPackages:
    @storybook/addon-a11y: ^6.0.21 => 6.0.20
    @storybook/addon-essentials: ^6.0.21 => 6.0.20
    @storybook/addon-links: ^6.0.21 
=> 6.0.20
    @storybook/html: ^6.0.21 => 6.0.20
```

**Comment by shilman** [comment]
Yup, we're adding async story handling in 6.1

**Comment by basher** [comment]
Excellent. Thanks.

I have a (temporary) workaround while I migrate my Storybook v5.3 to v6... I've added external deps to `public` folder so I can import them directly.

**Comment by basher** [comment]
**UPDATE**: I have now upgraded to Storybook V6.1.8 and have successfully implemented an `async loader`.

For anyone who can't get the [HTML kitchen sink example using async/await](https://github.com/storybookjs/storybook/blob/next/examples/html-kitchen-sink/stories/loaders.stories.js) to work, here's how I did it with regular promises:

```
import fetch from 'node-fetch';

export default {
    title: 'Title',
    loaders: [
        () =>
            fetch('path-to-json')
                .then((r) => r.json())
                .then((json) => json),
    ],
};

export const Story = (args, { loaded }) => `
        ${Object.keys(loaded).map((key) => ...construct HTML here... )}
`
```
