### ISSUE TITLE
Need to refresh browser on story change in build-storybook

### ISSUE THREAD

**Issue by zhigang1992** [storybookjs/storybook#12394]
**Describe the bug**
Everything works in dev mode, but when publish the storybook with build-storybook and serve with http-server

Click on stories at left side bars doesn't update the canvas anymore, would require a browser refresh to see the update.

**To Reproduce**

https://github.com/zhigang1992/storybook-bug-reproduce

1. `yarn && yarn build-storybook && npx http-server storybook-static`
1. Go to 'any store'
2. Click on 'any other story'
4. Canvas doesn't update

**System:**
```
Environment Info:

  System:
    OS: macOS 11.0
    CPU: (20) x64 Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz
  Binaries:
    Node: 14.9.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.7 - /usr/local/bin/npm
  Browsers:
    Chrome: 85.0.4183.83
    Safari: 14.0
```

**Additional context**
The project is initialed with expo, 

https://github.com/expo/examples/tree/master/with-storybook

and then upgrade to latest sb version and also remove react-native.

We have a custom webpack.config

**Comment by zhigang1992** [comment]
Possibly related

https://github.com/storybookjs/storybook/issues/10933#issuecomment-686597438

**Comment by shilman** [comment]
Looks like a duplicate to https://github.com/storybookjs/storybook/issues/11694

**Comment by zhigang1992** [comment]
I don't think it is, we don't have any network errors

![image](https://user-images.githubusercontent.com/1057756/92548996-ea633400-f28a-11ea-887d-30f8cdeec9fe.png)

**Comment by lawnchamp** [comment]
@zhigang1992 did you make any progress on this? I am also having the same problem where you can't switch between stories unless you refresh the browser. Here is my storybook https://chess-timer-storybook.netlify.app/ that is coming from this repo https://github.com/lawnchamp/chesstimer/tree/storybook-upgrade

**Comment by zhigang1992** [comment]
Everything worked for me after I upgraded to expo 39

**Comment by lawnchamp** [comment]
@shilman Do you have any ideas of what I could try that don't involve expo?

**Comment by zhigang1992** [comment]
It's also possible that they might have upgraded their Webpack config during this time.

https://github.com/expo/expo-cli/tree/master/packages/webpack-config

But I don't have a clear idea on what exactly fixes the issue.

**Comment by tmeasday** [comment]
@zhigang1992 so this issue is solved? I'll close it.

@lawnchamp the issue i was thinking of was this one: https://github.com/storybookjs/storybook/issues/11958 -- does that seem more like what you are seeing?
