### ISSUE TITLE
Using optional chaining (.?) to determine if attribute should be applied causes bug with addon-controls

### ISSUE THREAD

**Issue by lukaskoeller** [storybookjs/storybook#12401]
**Describe the bug**
When I use 
```js
const hasIcon = children.type?.name === 'Icon';
``` 
instead of
```js
const childrenTypeName = children.type === undefined ? false : children.type.name;
const hasIcon = childrenTypeName === 'Icon';
```
the Controls Panel in Storybook doesn't show all args / props anymore.

Logging `hasIcon` leads to the same output in both cases (as expected).

**To Reproduce**
Use optional chaining with conditional setting true or false to determine if attribute should be set or not.

**Expected behavior**
Controls Panel shows all Props like it does in the second option shown above.

**Screenshots**

**🚫 Not all Props shown:**
<img width="1226" alt="Bildschirmfoto 2020-09-07 um 15 47 02" src="https://user-images.githubusercontent.com/10390627/92394206-63df1300-f121-11ea-9d50-8ca4e4963fdb.png">

**✅ All Props shown (as expected):**
<img width="1225" alt="Bildschirmfoto 2020-09-07 um 15 48 19" src="https://user-images.githubusercontent.com/10390627/92394281-8ec96700-f121-11ea-8cca-a4d466b9a11b.png">

**Code snippets**
`const hasIcon = children.type?.name === 'Icon';`

**System:**
```
  System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
  Binaries:
    Node: 12.16.2 - /usr/local/bin/node
    npm: 6.14.7 - /usr/local/bin/npm
  Browsers:
    Chrome: 85.0.4183.83
    Firefox: 78.0.1
    Safari: 13.1.2
  npmPackages:
    @storybook/addon-a11y: ^6.0.21 => 6.0.21 
    @storybook/addon-essentials: ^6.0.21 => 6.0.21 
    @storybook/addon-links: ^6.0.21 => 6.0.21 
    @storybook/addons: ^6.0.21 => 6.0.21 
    @storybook/react: ^6.0.21 => 6.0.21 
```

**Comment by shilman** [comment]
closing as dupe to #11883
