### ISSUE TITLE
migrate upgrade-hierarchy-separators - command line is too long

### ISSUE THREAD

**Issue by thany** [storybookjs/storybook#12402]
**Describe the bug**
As per the migration guide, I executed `migrate upgrade-hierarchy-separators` and got:
```
> npx sb@next migrate upgrade-hierarchy-separators --glob="*/**/*.stories.@(tsx|jsx|ts|js)"
=> Applying upgrade-hierarchy-separators: 122 files
The command line is too long.
```

**To Reproduce**

1. Be on SB 5.3
2. Have at least 122 files that need hierarchy separators migrated
2. Follow the migration guide

**Expected behavior**
Should work. If the command line is too long, it should probably be split up into multiple commands or something.

It doesn't say what the command line is that it was trying to execute, so I also can't split it manually.

**System:**
```
  System:
    OS: Windows 10 10.0.19041
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
  Binaries:
    Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 85.0.4183.83
    Edge: Spartan (44.19041.423.0)
  npmPackages:
    @storybook/addon-a11y: 6.0.21 => 6.0.21
    @storybook/addon-actions: 6.0.21 => 6.0.21
    @storybook/addon-docs: 6.0.21 => 6.0.21
    @storybook/addon-knobs: 6.0.21 => 6.0.21
    @storybook/addon-options: 5.3.21 => 5.3.21
    @storybook/react: 6.0.21 => 6.0.21
    @storybook/theming: 6.0.21 => 6.0.21
```

**Comment by shilman** [comment]
The issue is that the glob expansion is too large. Can you upgrade at a finer granularity? E.g. first with `--glob="a/**/*.stories.*"`, then with `--glob="b/**/*.stories.*"`, etc.

**Comment by thany** [comment]
That partically defeats the "automatic" nature of such commands. I would much rather see a command split happening automatically, especially since 122 stories is not that outlandish, I feel.

**Comment by shilman** [comment]
@thany PRs welcome!
