### ISSUE TITLE
Web Components: ArgsTable in Docs addon is missing Methods section

### ISSUE THREAD

**Issue by Shackless** [storybookjs/storybook#12412]
**Describe the bug**
Some web component frameworks like Stencil are able to generate documentation for public `methods` of web components. 
These should be shown in the `ArgsTable` of Storybook next to Attributes, Events, Slots etc. but are currently missing.

**To Reproduce**

Add this to any component in your custom-elements.json file: 
```json
      ...
      "methods": [
        {
          "name": "testMethod",
          "description": "A test method"
        }
      ],
```

Check Storybook - it will not be displayed in the `ArgsTable`

**Expected behavior**
`ArgsTable` should display an extra section for `Methods`.

**Screenshots**

Actual:
![image](https://user-images.githubusercontent.com/306996/92462403-baecf280-f1ca-11ea-8a89-06f54e62c57a.png)

Expected: 
![image](https://user-images.githubusercontent.com/306996/92462530-e243bf80-f1ca-11ea-9478-b3fb432fee94.png)

**Comment by shilman** [comment]
Boo-yah!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.0-alpha.4 containing PR #12413 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
