### ISSUE TITLE
Auto-set a 'STORYBOOK' environment variable to 'true'

### ISSUE THREAD

**Issue by kripod** [storybookjs/storybook#12416]
**Is your feature request related to a problem? Please describe.**

When using different configuration for development, production and Storybook, it’s desirable to know whether we’re in a Storybook environment by querying `process.env.STORYBOOK`. For instance, a `postcss.config.js` file’s excerpt could look as follows:

```js
module.exports = {
  plugins: {
    "postcss-import",
    "tailwindcss",
    "postcss-preset-env",

    // Simulate pseudos (only for Storybook)
    ...(process.env.STORYBOOK && { "postcss-pseudo-classes" })
}
  }
}
```

**Describe the solution you'd like**

Similarly to the [convention of popular CI services](https://docs.travis-ci.com/user/environment-variables/#default-environment-variables), an environment variable for `STORYBOOK` should be set to `true` by default. It seems to blend well with [Storybook’s existing env var handling mechanism](https://storybook.js.org/docs/react/configure/environment-variables).

**Describe alternatives you've considered**

Using [`cross-env`](https://github.com/kentcdodds/cross-env) for scripts defined in `package.json`. It’s error-prone and often forgotten by UNIX-only users who would prefer just `STORYBOOK=true && start-storybook`.

**Are you able to assist bring the feature to reality?**

No, unfortunately, I’m too busy at this time to familiarize myself with the codebase.

**Comment by kripod** [comment]
This is not stale.

**Comment by toshi1127** [comment]
@shilman 
Can I try this?

**Comment by shilman** [comment]
Yo-ho-ho!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.0-beta.3 containing PR #12997 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
