### ISSUE TITLE
addons/docs/README can't be access from Storybook Docs

### ISSUE THREAD

**Issue by ReeceHsu** [storybookjs/storybook#12427]
**Describe the bug**

Hello, hyperlink redirect error as I clicked Storybook Docs on https://storybook.js.org/docs/react/writing-docs/docs-page

**To Reproduce**

1. Go to https://storybook.js.org/docs/react/writing-docs/docs-page
2. Click on Storybook Docs
3. See error

**Expected behavior**

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System:**
Please paste the results of `npx sb@next info` here.

**Additional context**

**Comment by elensalustiano** [comment]
I'll take it :)

**Comment by jonniebigodes** [comment]
@ReeceHsu sorry for not addressing this sooner. But this issue has been on my radar and is something that i'm currently checking and going to fix shortly. I still need to do a little more of research but i think i'm onto something and soon we'll be able to close it. Thank you for bringing this to our attention.

Stay safe

**Comment by jonniebigodes** [comment]
@ReeceHsu just merged a pull request that addresses this. The wording was fine tuned a bit to help new Storybook users and also users that are upgrading Storybook. Going to close this out. Thanks for creating the issue and letting us know about the broken link.

Stay safe
