### ISSUE TITLE
Option for Layout: "none" to remove inline styles on <body>

### ISSUE THREAD

**Issue by johnnybenson** [storybookjs/storybook#12434]
**Is your feature request related to a problem? Please describe.**
Don't make me fight the framework to control the page by making it easy to turn off inline styles created by the default layout.

Using Decorators to unset styles here feels very heavy handed and a "none" optional would be much more ergonomic in this situation, from [Story layout](https://storybook.js.org/docs/react/configure/story-layout)

**Describe the solution you'd like**
I would like to specify `"none"` for the layout and see the inline styles removed from the body.

```js
// .storybook/preview.js

export const parameters = {
  layout: 'none',
};
```

See: https://github.com/storybookjs/storybook/blob/6ecfd495763d6c014598b2915946b6d52e5ec6f7/lib/core/src/client/preview/StoryRenderer.tsx#L24

https://github.com/storybookjs/storybook/blob/6ecfd495763d6c014598b2915946b6d52e5ec6f7/lib/core/src/client/preview/StoryRenderer.tsx#L234

![image](https://user-images.githubusercontent.com/238022/92646133-f3b4c680-f2b3-11ea-990e-095adff8f9e0.png)

**Describe alternatives you've considered**
Right now I can `!important` attributes in a style tag in `preview-head.html`.

**Are you able to assist bring the feature to reality?**
Yep

**Comment by Mortuie** [comment]
This part confuses me too because that's causing me major issues right now. Furthermore if I'm wanting to develop modals which are full body components I can't replicate the actual UX on storybooks due to padding and a random border?

**Comment by shilman** [comment]
@ndelangen @ghengeveld is this a bug?

**Comment by shawn-dll** [comment]
@shilman yes, see also https://github.com/storybookjs/storybook/issues/12041#issuecomment-687051896

**Comment by shilman** [comment]
Yippee!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.0-alpha.31 containing PR #12727 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
