### ISSUE TITLE
Dependency: dequal

### ISSUE THREAD

**Issue by lukeed** [storybookjs/storybook#12433]
**Is your feature request related to a problem? Please describe.**
No problem or issues, merely a dependency suggestion :) (Perhaps this is the wrong template)

**Describe the solution you'd like**
I'm suggesting that you replace use of `fast-deep-equal` with [`dequal`](https://github.com/lukeed/dequal). 
Dequal is a (slightly) smaller and (significantly) faster alternative. Based on your [usage](https://github.com/storybookjs/storybook/search?p=1&q=fast-deep-equal&unscoped_q=fast-deep-equal), it seems you can use the `dequal/lite` mode too, which is even smaller and faster. 😅 

**Describe alternatives you've considered**
Any of the candidates in the benchmark (below) could work, but `fast-deep-equal` and `dequal` are the fastest two.

**Are you able to assist bring the feature to reality?**
Yes, I can PR if requested.

**Additional context**
* [Benchmark](https://github.com/lukeed/dequal#benchmarks)
* [`dequal` vs `dequal/lite`](https://github.com/lukeed/dequal#modes)

Because you're not using `fast-deep-equal/es6`, you can use `dequal/lite` (no Map, Set, or TypedArray support).
Should you decide to start using Maps and Sets, `dequal` handles them correctly – FDE uses referential equality for Set values and Map keys/values.

**Comment by shilman** [comment]
@lukeed would love a PR for this. if you can include some perf numbers in the PR that would be amazing!

**Comment by lukeed** [comment]
Thanks :) PR open~!
But I wasn't sure how to set up performance tracking, sorry 😞
