### ISSUE TITLE
StorybookUI: Opening canvas in new tab should maintain custom properties (such as the background set for the canvas)

### ISSUE THREAD

**Issue by iugabogdan** [storybookjs/storybook#12430]
**Describe the bug**

Opening a canvas in new tab should maintain all the previous properties set on the canvas.

I am not sure if this is a bug or should be a feature. However I expect that if I set a particular background on the canvas, I expect to see it also in the new tab, because I want to see the canvas I edited before, right ?

Also, is there a way to override that background ? Or like providing some parameters ? like knobs. If yes then it would be perfect.

**To Reproduce**

1. Open storybook UI - it should have backgrounds addon.
2. Open any story
3. Change the canvas default background to any other colour (grey for example)
4. Click on: open canvas in new tab
5. Check new tab -> the canvas has the default colour

**Expected behavior**
The canvas opened in new tab should have the background colour I have set in the story

**Screenshots**
How the canvas looks before I open it in new tab:
![image](https://user-images.githubusercontent.com/28590126/92591889-5fdcfd80-f2a7-11ea-8963-e1b632a7d708.png)

How it looks after it is opened in new tab:
![image](https://user-images.githubusercontent.com/28590126/92591959-80a55300-f2a7-11ea-92b7-0143a024c300.png)

**System:**
Environment Info:

  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 12.10.0 - ~/.nvm/versions/node/v12.10.0/bin/node
    Yarn: 1.17.3 - ~/.nvm/versions/node/v12.10.0/bin/yarn
    npm: 6.14.7 - ~/.nvm/versions/node/v12.10.0/bin/npm
  Browsers:
    Chrome: 84.0.4147.89
    Safari: 13.1.2

**Comment by shilman** [comment]
cc @ndelangen @tmeasday

**Comment by tmeasday** [comment]
I think we can (should?) do this for `args` and `globals` via query parameters. I think we've mooted doing it before @shilman? Was there a reason not to do it (beyond time)?

**Comment by shilman** [comment]
I think it's mostly a time constraint. I think we're storing `globals` in session storage now, so we get some of this for free.

I like the knobs solution of "exporting to URL" and "reading from URL" which is related: https://github.com/storybookjs/storybook/issues/12291

**Comment by iugabogdan** [comment]
Thanks guys for looking into this, really appreciated!
Our use case is visual-comparison testing related. We basically want to open a story directly on the canvas parametrised with knobs, thus we will need to set the background of the canvas for some of the use cases, because for example, white components will blend into the white canvas.

**Comment by tmeasday** [comment]
@iugabogdan -- I wonder why you wouldn't create a hardcoded story for the given `args` combinations (I realise you can't set `globals` in a Story, at least at the moment)?

**Comment by shilman** [comment]
Possibly fixed by https://github.com/storybookjs/storybook/pull/13803

**Comment by iugabogdan** [comment]
Yes, thanks a lot guys! Much appreciated! <3
