### ISSUE TITLE
Documentation Enhancement

### ISSUE THREAD

**Issue by rachittshah** [storybookjs/storybook#12441]
**Is your feature request related to a problem? Please describe.**
The recent issue with the not found error in the documentation page

**Describe the solution you'd like**
So,as stated above,I wanted to work upon a gh page.so that the issue is resolved.

**Describe alternatives you've considered**
Jekyll,Github Pages

**Are you able to assist bring the feature to reality?**
 yes, I can...

**Additional context**
Would like to work upon a the migration.

**Comment by jonniebigodes** [comment]
Closing this issue down for lack of further information. Should the author or anyone else provide some context on this I'd gladly re-open and we can work on it for a suitable solution.
