### ISSUE TITLE
Docs isn't documenting children props without a comment

### ISSUE THREAD

**Issue by sfeldkamp** [storybookjs/storybook#12459]
# description
Dependency @styleguidist/react-docgen-typescript has the behavior of not documenting `children` property if it has no comment.  See the linked issue and PR.  It's unclear if it will be fixed in that package, and if so, Storybook may need to either:
1. replace the dependency with another option
2. add the configuration option
3. update documentation to warn users about this behavior

https://github.com/styleguidist/react-docgen-typescript/issues/284
https://github.com/styleguidist/react-docgen-typescript/pull/285

I think this is only effecting users who type their components as below, instead of using React.FC.
```
export interface MyComponentProps {
...
}
export const MyComponent = (props: MyComponentProps): JSX.Element => {
...
}
```

# workaround 
add a comment for the children props that you want documented

# notes
I'm mostly submitting this so you all will be aware of it and to help prevent anyone else from wasting hours of their life to find it.

**Comment by shilman** [comment]
cc @hipstersmoothie

**Comment by hipstersmoothie** [comment]
This is actually the intended behavior. I'd be open to adding a config option for this

**Comment by sfeldkamp** [comment]
Is this because React.FC adds the `children` type automatically, but not all components actually output children?  So not documenting it unless there is a comment is a workaround to provide a way for us to control on a component-by-component basis (when all components are typed with React.FC) whether children is documented or not?

If so, could you limit the application of this rule to only apply when the type actually is React.FC?

I'm happy with configuration and/or documentation too though.

**Comment by hipstersmoothie** [comment]
I've opened a PR to add a config option that would document the "children" even without a jsDoc comment

https://github.com/styleguidist/react-docgen-typescript/pull/305

Should be resolved in around a week! Will post back here once merged + released
