### ISSUE TITLE
Update Theming Docs

### ISSUE THREAD

**Issue by jasonwr** [storybookjs/storybook#12452]
Given this document:

https://storybook.js.org/docs/react/configure/theming

The theming docs are incomplete. I tried the suggestion here:

![image](https://user-images.githubusercontent.com/305999/92820884-b1f55000-f387-11ea-972c-96d9061de0ab.png)

This is not adequate, at least it did nothing for me and I followed this setup. What ended up working for was the following in the **preview.js**:

```
import React from "react";
import { addDecorator } from '@storybook/react';
import { ThemeProvider } from "emotion-theming";
import theme from "../src/theme";

addDecorator(story => (
  <ThemeProvider theme={theme}>
    {story()}
  </ThemeProvider>
));

export const parameters = {
  actions: { argTypesRegex: "^on[A-Z].*" },
}
```

I'm swamped with work. If someone else could add this in that would be great. Thanks.

**Comment by shilman** [comment]
Your code is for theming your components. The documentation is about how to theme Storybook's UI itself

**Comment by jasonwr** [comment]
> Your code is for theming your components. The documentation is about how to theme Storybook's UI itself

Actually my code is for both theming my main components and storybook components. I did find the ThemeProvider documentation but it was a bit out of the way.

**Comment by shilman** [comment]
That code couldn't possibly theme Storybook's UI. It runs in the preview iframe which only applies to rendered stories, not to the surrounding UI.

**Comment by jasonwr** [comment]
> That code couldn't possibly theme Storybook's UI. It runs in the preview iframe which only applies to rendered stories, not to the surrounding UI.

I think you're not understanding my inquiry. That code provides theme based code for my storybook based components and all of my components.
