### ISSUE TITLE
Storybook templates do not handle default prop values correctly if they are objects 

### ISSUE THREAD

**Issue by jorge-fernandes** [storybookjs/storybook#12455]
**Describe the bug**
Storybook templates do not appear to handle props default values correctly if they are complex objects.
The default value using the template bind is yielding the expression as a string instead of evaluating it.

**To Reproduce/Code snippets**

Disclaimer: i really dumbed down the example, so i haven't checked for typos and so on... just to illustrate the problem

Component example
```
import { Option } from "prelude-ts";
import React from "react";

interface InputProps extends React.InputHTMLAttributes<HTMLInputElement> {
  customPlaceholder?: Option<string>;
}

const Input: React.FC<InputProps> = ({
  customPlaceholder = Option.none(),
  ...otherProps
}) => (
  <input placeholder={customPlaceholder.getOrUndefined()} {...otherProps} />
);
export default Input;
```

And the following story:

```
type InputStoryComponentProps = React.ComponentProps<typeof Input> & {
  label: string;
};

const InputTemplate: InputStoryComponentProps = ({ label, ...otherArgs }) => (
  <div>
    <span>{label}</span>
    <Input {...otherArgs} />
  </div>
);

export const DefaultInput = InputTemplate.bind({});
DefaultInput.storyName = "Default input";
```

Opening the story in storybook i get the following:
`customPlaceholder.getOrUndefined is not a function`

Debugging it, i discovered that using the template, the props is being initialized with "Option.none()" instead of the actual evaluated Option.none(), which of course yield the previous error.

If i don't use the template, and just write a story, it works perfectly fine (of course i end up duplicating alot of code between the real case complex stories which was the main point of using the template).

**Expected behavior**
Default prop values are properly initialised as evaluated and not passed as a string

**System:**

```
Environment Info:

  Binaries:
    Node: 14.7.0 - ~/.nvm/versions/node/v14.7.0/bin/node
    npm: 6.14.7 - ~/.nvm/versions/node/v14.7.0/bin/npm
  Browsers:
    Chrome: 85.0.4183.102
    Firefox: 80.0.1
    Safari: 13.1.2
  npmPackages:
    @storybook/addon-actions: ^6.0.21 => 6.0.21
    @storybook/addon-docs: ^6.0.21 => 6.0.21
    @storybook/addon-knobs: ^6.0.21 => 6.0.21
    @storybook/addon-links: ^6.0.21 => 6.0.21
    @storybook/addons: ^6.0.21 => 6.0.21
    @storybook/preset-create-react-app: ^3.1.4 => 3.1.4
    @storybook/react: ^6.0.21 => 6.0.21
```

**Comment by Multihuntr** [comment]
I also have this problem. I want to note that it also happens if you refer to another variable within the file. 

I have exported the default value that I want and then just imported that default value to pass to the templates as a work-around.

**Comment by shilman** [comment]
Args must be data that can be JSON stringified. If you want to use functions/methods you should refer to it directly.

@jonniebigodes Do you think we need to clarify the documentation about this?

**Comment by goranjviv** [comment]
It seems to happen if you reference any object in a defaultProp.

Eg:
`  
orientation: "whatever string" + Orientations.HORIZONTAL + 'jfdkslfj' + `${Orientations.HORIZONTAL}`
`
results in orientation being that entire expression.

**Comment by shilman** [comment]
Ok, how about this as the workaround for the above case:

```ts
const InputTemplate: InputStoryComponentProps = ({ label, ...otherArgs }) => (
  <div>
    <span>{label}</span>
    <Input {...otherArgs} customPlaceholder={Option.none()} />
  </div>
);
```

If you need to select between different options, you can do something hacky like this:

```ts
const PLACEHOLDERS = {
  None: Option.none(),
  Something: () => { whatever complex thing }
  'Something Else': () => { whatever complex thing }
}

export default {
  title: ...,
  argTypes: {
    customPlaceholder: { control: { type: 'select', options: Object.keys(OPTIONS) } }
  }
}

const InputTemplate: InputStoryComponentProps = ({ label, customPlaceholder, ...otherArgs }) => (
  <div>
    <span>{label}</span>
    <Input {...otherArgs} customPlaceholder={PLACEHOLDERS[customPlaceholder]} />
  </div>
);
```

**Comment by KaiVandivier** [comment]
A workaround that I've used that I think is elegant is to apply the component's default props as default args at the component level, e.g.:

```js
export default {
    title: 'Component'
    component: Component,
    // set default args for all stories
    args: { ...Component.defaultProps },
}
```

This correctly applies functions and objects as props. Remember to [configure your JSX addon](https://github.com/storybookjs/addon-jsx#options) (see the [react-element-to-jsx-string](https://github.com/algolia/react-element-to-jsx-string) part) to not show default props 🙂

**Comment by innaditiashova** [comment]
Hey folks :)

Just wanna check if it's going to be solved any time soon? It's not that obvious issue and I guess it becomes really frustrating for lots of people as they don't even have an idea what's broken and how to google about it :)

**Comment by AndrejGajdos** [comment]
It would be nice to mention this somewhere. I didn't know if I am missing something in my configuration.

**Comment by shilman** [comment]
Try upgrading to the latest prerelease:

```
npx sb@next upgrade --prerelease
```

Does that fix it?

**Comment by terrancecorley** [comment]
Does anyone have a good solution for the issue I'm seeing here? #15268

**Comment by paillenapple** [comment]
Is there still no solution about deep merging React defaultProps and Storybook component args ?

**Comment by gcamara** [comment]
Hey guys, any updates on this? I'm still facing the same problem with Angular 12 and SB `6.4.22`

**Comment by ImCheesecake** [comment]
My workaround for now is an extended version of what @KaiVandivier said [here](https://github.com/storybookjs/storybook/issues/12455#issuecomment-781695689)

```ts
// Component.tsx

Component.defaultProps = {
  someProp: "Something",
  someMuiProp: {
    fontSize: 14,
    underline: "hover",
  },
  anotherMuiProp: {
    fontSize: 14,
    textAlign: "center",
  },
  anotherAnotherMuiProp: {
    height: 150,
  },
};


// Component.stories.tsx

export default {
    title: 'Component'
    component: Component,
    // set default args for all stories
   args: {
    // spread default props
    ...Component.defaultProps,

    someMuiProp: {
    // get default props from specific object
      ...Component.defaultProps?.someMuiProp,
    // add storybook specifics
      label: "some label",
    },

    anotherMuiProp: {
    // get default props from specific object
      ...Component.defaultProps?.anotherMuiProp,
    // add storybook specifics
      foo: "bar",
    },
  },
}
```
This works but it looks ugly, especially if you have a lot of stories and using `defaultProps` everywhere

**Comment by Multihuntr** [comment]
I would just fill the args with a deep copy of defaultProps, and modify properties on separate lines. This should work everywhere and without side-effects because defaultProps have to be able to be JSON stringified.

```javascript

const story = {
    title: 'Component',
    component: Component,
    args: JSON.parse(JSON.stringify(Component.defaultProps))
}
story.args.someMuiProp.label = "some label"
story.args.anotherMuiProp.foo = "bar"
export default story

```

If you had lodash and were so inclined, you could also create a function which hid some messiness, allowing you to write your stories like you wanted to in the first place:

```javascript
function mergeStorybookArgs(story) {
    defaultCopy = JSON.parse(JSON.stringify(story.component.defaultProps))
    story.args = _.merge(defaultCopy, story.args)
}

export default mergeStorybookArgs({
    title: 'Component',
    component: Component,
    args: {
        someMuiProp: {
            label: "some label"
        },
        anotherMuiProp: {
            foo: "bar"
        },
    },
})
```

**Comment by nikitaaswani** [comment]
https://github.com/storybookjs/storybook/issues/12455#issuecomment-781695689 worked for me.

**Comment by kylegach** [comment]
I'm fairly sure [args mapping](https://storybook.js.org/docs/react/writing-stories/args#mapping-to-complex-arg-values) is the official solution here, so I'm closing this issue. Please let me know if this was in error.
