### ISSUE TITLE
onChange function not called on theme change

### ISSUE THREAD

**Issue by mamtabisht18** [storybookjs/storybook#12469]
In storybook (Angular) i have checked https://www.npmjs.com/package/storybook-addon-themes and want to perform some action when user select a them but its not firing this onChange

```
  import { addParameters } from '@storybook/angular';

    addParameters({
     themes: {
           list : [
            {name: 'Theme 1', class: ['theme-one'], default: true},
            {name: 'Theme 2', class: ['theme-two']},`
          ],
     onChange: (theme) =>{
         console.log(theme)
    }
    }})

```

Both themes are being displayed on dropdown but on selecting any one onChange function not called which should be called as per documentation

**Comment by shilman** [comment]
I think you'd be better off asking this question on the `addon-themes` repo
