### ISSUE TITLE
start-server-and-test + Storybook 

### ISSUE THREAD

**Issue by PaulieScanlon** [storybookjs/storybook#12463]
**Describe the bug**
When using `start-server-and-test` on Circle CI to run Cypress integration tests `start-server-and-test` should wait for Storybook to respond before running the next task. This is causing my integration tests to fail because the tests start before Storybook is up and running.

This is the error i see in Circle CI when `wait-on` which `start-server-and-test` uses when attempting to wait for Storybook to start. Storybook does indeed start up as expected with no errors, so there's something going on with why `wait-on` can't check if Storybook has completed starting up.

```
HTTP(S) error for http://localhost:6006 Error: connect ECONNREFUSED 127.0.0.1:6006
```
I've raised an issue on the `start-server-and-test` repo which you can see [here](https://github.com/bahmutov/start-server-and-test/issues/250#issuecomment-691315590)

Here's a short screen capture. The tests do pass but it's only because Storybook just about finishes loading before the last time Cypress attempts to run the test: [start-sever-and-test-v1](https://res.cloudinary.com/www-paulie-dev/video/upload/v1599902739/Temp%20Stuff/start-server-and-test-v1_nxz9v5.mov)

**To Reproduce**
This is my Cypress start script

```
"storybook": "yarn workspace docs storybook",
"cy:run": "cypress run",
"cy:pipeline": "start-server-and-test 'yarn storybook' \"http://localhost:6006|http-get://localhost:6006\" 'yarn cy:run'"
```

**Expected behavior**
`start-server-and-test` shouldn't run the `cy:run` script until after `localhost:6006` has responded. When running this in Circle CI both `yarn storybook` and `cy:run` happen at the same time.

**Comment by shilman** [comment]
@ndelangen any ideas?

**Comment by PaulieScanlon** [comment]
False alarm... kind of. Storybook is actually totally fine it was Circle CI that was causing me a problem. Explanation [here](https://github.com/bahmutov/start-server-and-test/issues/250#issuecomment-692129633)
