### ISSUE TITLE
Storysource panel is blank when default export is stored in a variable

### ISSUE THREAD

**Issue by Hypnosphi** [storybookjs/storybook#12467]
Repro: https://github.com/Hypnosphi/storysource-export-default-const

```
const kind = {
  ...
};
export default kind;
```

**Comment by shilman** [comment]
@Hypnosphi that's not supported in CSF. We expect a statically defined default export.

**Comment by Hypnosphi** [comment]
Well, apart from storysource everything works

**Comment by shilman** [comment]
storysource, codemods -- anything that requires static analysis

**Comment by Hypnosphi** [comment]
I see. Can we support at least this trivial case, when `const` value is static?

**Comment by kylegach** [comment]
This is now supported:

```ts
const meta: Meta = {
  ...
};
export default meta;
```

So I'm closing this issue.
