### ISSUE TITLE
export 'usePopper' was not found in 'react-popper'

### ISSUE THREAD

**Issue by lifeiscontent** [storybookjs/storybook#12475]
**Describe the bug**

When using react-popper in my own codebase, storybook seems to try to own it and it's using an older version than my own.

**To Reproduce**

1. Create component using react-popper
2. Add story with said component
3. see `export 'usePopper' was not found in 'react-popper'` in console and potential error in storybook

**Expected behavior**
Ability to use my own deps

**Screenshots**
<img width="1480" alt="Screen Shot 2020-09-14 at 6 15 43 PM" src="https://user-images.githubusercontent.com/180963/93153531-4fb58b80-f6b6-11ea-901e-2241b1a9231b.png">

@shilman idk how you got in here :D (see screenshot)

**Code snippets**
If applicable, add code samples to help explain your problem.

**System:**
Please paste the results of `npx sb@next info` here.

Environment Info:

  System:
    OS: macOS 10.15.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 12.18.3 - ~/n/bin/node
    Yarn: 1.22.5 - ~/Source/trusted-web/node_modules/.bin/yarn
    npm: 6.14.6 - ~/n/bin/npm
  Browsers:
    Firefox: 72.0.2
    Safari: 13.1.2
  npmPackages:
    @storybook/addon-essentials: 6.0.21 => 6.0.21
    @storybook/addon-knobs: 6.0.21 => 6.0.21
    @storybook/addons: 6.0.21 => 6.0.21
    @storybook/cli: 6.0.21 => 6.0.21
    @storybook/react: 6.0.21 => 6.0.21

lifeiscontent@lifeiscontent-MBP

**Additional context**

<3

**Comment by dstaver** [comment]
I've just spent several hours debugging the exact same issue. react-popper works fine in my app, but completely breaks in storybook. Unfortunately I haven't found a solution yet.

**Comment by TanninOne** [comment]
Same. reverting to storybook 5

**Comment by lifeiscontent** [comment]
Looks like this issue has been fixed in the latest alpha release!

**Comment by shilman** [comment]
For those who are experiencing problems, I believe running Storybook with the `--no-dll` should fix it.

**Comment by charlie632** [comment]
@shilman running with `--no-dll` flag works.

**Comment by shilman** [comment]
We no longer use webpack DLLs in storybook, so I'm going to close this for now. LMK if you're still experiencing this problem on 6.1.x or higher and I'll re-open.
