### ISSUE TITLE
Controls were unable to render in Angular 10

### ISSUE THREAD

**Issue by csaicharan** [storybookjs/storybook#12478]
The storybook is unable to render the controls in Angular 10 projects.

"@storybook/angular": "^6.0.21",
"@angular/core": "~10.1.1",

![image](https://user-images.githubusercontent.com/19502287/93179927-a6fb4080-f736-11ea-8adf-cbe967a44641.png)

Even the component has two Input properties, it is shown as no Inputs for this component.

**Comment by shilman** [comment]
Are you running `compodoc` per the setup instructions? What does it produce?

**Comment by csaicharan** [comment]
> Are you running `compodoc` per the setup instructions? What does it produce?

Yes, I am running `compdoc` in setup instructions. But the knots config is working instead of controls.

**Comment by Marklb** [comment]
How is your story defined? 

Are you using the args parameter, like the following:
```ts
export const Example = (args) = ({
	props: { ...args },
	component: MyComponent
})
```

**Comment by csaicharan** [comment]
> How is your story defined?
> 
> Are you using the args parameter, like the following:
> 
> ```ts
> export const Example = (args) = ({
> 	props: { ...args },
> 	component: MyComponent
> })
> ```

This wasn't working for me, so I configured individually for each story.

I checked the args works in v6*beta and in my workspace the version is stable and lower. So I had to fall back to the knobs.

I am using like the following,

```
export const Basic = (args) => ({
  component: ButtonComponent,
  props: {
    text: text('text', 'Basic Button'),
    disabled: boolean('disabled', false)
  },
});
```
