### ISSUE TITLE
Angular 10 Storybook project does not load in IE11

### ISSUE THREAD

**Issue by lagatchell** [storybookjs/storybook#12474]
**Describe the bug**
A new Angular 10 Storybook project does not load in IE11.

**To Reproduce**

1. Create a new Angular 10 CLI project (using `ng new storybook-project`)
2. Initialize it as a storybook project (`npx sb init`)
3. Run `npm run storybook`
4. Open Storybook in IE 11
5. Open dev tools
6. Observe Storybook gets stuck in loading state
6. Observe console error `Syntax error`
7. Or clone pre-configured repo: https://github.com/lagatchell/ie-angular-storybook-issue

**Expected behavior**
A new Angular 10 Storybook project should load in IE11.

**Screenshots**
Browser:
![image](https://user-images.githubusercontent.com/14189842/93128024-dd847d00-f69c-11ea-90b8-334de1db9dab.png)
Console:
![image](https://user-images.githubusercontent.com/14189842/93127499-07896f80-f69c-11ea-882e-b46040f9bf8f.png)

**System:**
  ```
System:
    OS: Windows 10 10.0.17134
    CPU: (8) x64 Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
  Binaries:
    Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 84.0.4147.89
    Edge: Spartan (42.17134.1098.0)
  npmPackages:
    @storybook/addon-actions: ^6.0.21 => 6.0.21
    @storybook/addon-essentials: ^6.0.21 => 6.0.21
    @storybook/addon-links: ^6.0.21 => 6.0.21
    @storybook/angular: ^6.0.21 => 6.0.21
```

**Comment by lagatchell** [comment]
Could be related to https://github.com/storybookjs/storybook/issues/11433

**Comment by antoniosZ** [comment]
could also be related to #12179

**Comment by lacolaco** [comment]
Also maybe related to https://github.com/storybookjs/storybook/issues/8884

**Comment by anwalkers** [comment]
IE11 is headed out the door...

https://techcommunity.microsoft.com/t5/microsoft-365-blog/microsoft-365-apps-say-farewell-to-internet-explorer-11-and/ba-p/1591666

**Comment by ojemuyiwa** [comment]
Any info on if this is ever going to be resolved? Been searching and tinkering for days now

**Comment by shilman** [comment]
Yes this will get resolved, but we don't have an ETA

**Comment by ndelangen** [comment]
Storybook 7.0 won't support IE11 anymore.

6.5 won't receive updates other than critical security issues, this won't get fixed.
