### ISSUE TITLE
"Module not found: Error: Can't resolve.." on an external dynamic import

### ISSUE THREAD

**Issue by DavidLozzi** [storybookjs/storybook#12472]
**Describe the bug**

I am using a dynamic import to download a JSON file from an external host, i.e.: `const navJson = await import('https://domain.com/data.json');`. This does work using a locally hosted JSON file, like `import('../../data.json')`

When I build storybook, I get the error

```
ERROR in ./src/components/Header/Header.js
Module not found: Error: Can't resolve 'https://domain.com/data.json' in '/Users/david.lozzi/git/shared-global-nav/src/components/Header'
```

I added a `.babelrc` file to my `.storybook` folder, per a similar support thread, this didn't change anything

```
{
  "presets": [
    "@babel/preset-env",
    "@babel/preset-react"
  ],
  "plugins": [
    [
      "@babel/plugin-proposal-class-properties"
    ],
    [
      "@babel/plugin-transform-runtime",
      {
        "regenerator": true
      }
    ],
    [
      "@babel/plugin-syntax-dynamic-import"
    ]
  ]
}
```

And my versions:

```
    "@babel/cli": "^7.7.0",
    "@babel/core": "^7.7.2",
    "@babel/plugin-proposal-class-properties": "^7.10.4",
    "@babel/plugin-syntax-dynamic-import": "^7.8.3",
    "@babel/plugin-transform-runtime": "^7.11.5",
    "@babel/preset-env": "^7.11.5",
    "@babel/preset-react": "^7.10.4",
    "@storybook/addon-actions": "^5.2.8",
    "@storybook/addon-knobs": "^5.2.8",
    "@storybook/addon-options": "^5.2.8",
    "@storybook/react": "^5.2.8",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
```

**To Reproduce**

see above

**Expected behavior**

It builds and then will download the file as needed

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System:**
Please paste the results of `npx sb@next info` here.

**Additional context**

**Comment by DavidLozzi** [comment]
I changed my approach to use `fetch` instead since I was just downloading a JSON file, much easier and it works ;)

**Comment by ndelangen** [comment]
As a work around you could use a fetch instead?

**Comment by ndelangen** [comment]
the issue is, storybook relies on webpack to bundle the app. import statements don't make it into the runtime. webpack tries to resolve all dependencies at build-time. In this case it can't.

I'm afraid this is a hard limitation right now (though one with a work-around ( fetch ) )

**Comment by alvesmog** [comment]
> the issue is, storybook relies on webpack to bundle the app. import statements don't make it into the runtime. webpack tries to resolve all dependencies at build-time. In this case it can't.
> 
> I'm afraid this is a hard limitation right now (though one with a work-around ( fetch ) )

Hi, how could I do that? I am facing the same issue. But I don't get how would I import a component via fetch

**Comment by gyto23** [comment]
Have same issue where component contain multiple external files and it cannot import them dynamically on the storybook start.

This is my setup and it also doesnt work

```js
{
  "presets": [
    "@babel/preset-env",
    "@babel/preset-react",
    "@babel/preset-flow"
  ],
  "plugins": [
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-syntax-dynamic-import"
  ]
}
```

**Comment by ndelangen** [comment]
You could try using the vite builder instead?

Webpack just simply does not support this.
