### ISSUE TITLE
Getting Module not found: Error: Can't resolve '@storybook/source-loader/preview' with @storybook/source-loader@6.0.21

### ISSUE THREAD

**Issue by jlabaj** [storybookjs/storybook#12482]
Getting Module not found: Error: Can't resolve '@storybook/source-loader/preview' with @storybook/source-loader@6.0.21

**Comment by shilman** [comment]
Try removing node_modules and reinstalling? Or clearing lockfile and reinstalling?

**Comment by jlabaj** [comment]
Downgrading to 5.3.18 helped, removing the package-lock and reinstalling didn't, I didn't delete the whole node_modules

**Comment by shilman** [comment]
Yeah 6.x and 5.x are not compatible. Downgrade everything or upgrade:

```
yarn sb upgrade
```

**Comment by jlabaj** [comment]
> Yeah 6.x and 5.x are not compatible. Downgrade everything or upgrade:
> 
> ```
> yarn sb upgrade
> ```

upgrated everything now getting Error: Invalid compodoc JSON(Angular):

import { Button } from '@storybook/angular/demo';

export default {
  title: 'Button',
  component: Button,
};

export const Text = () => ({
  component: Button
});

**Comment by shilman** [comment]
@jlabaj compodoc only works for components defined in your project, so you should probably get rid of that story
