### ISSUE TITLE
Addon Controls should add empty option if isRequired is not set for prop-types

### ISSUE THREAD

**Issue by lifeiscontent** [storybookjs/storybook#12486]
**Describe the bug**
if I have a component that defines a prop type such as `PropTypes.oneOf(['top', 'bottom'])` since its not `PropTypes.oneOf(['top', 'bottom']).isRequired` it should add an empty option in docs/controls addons.

**To Reproduce**

1. Create component with PropTypes.oneOf
2. Create a story using said component
3. See that empty option is not available

**Expected behavior**
Explained above

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System:**
Please paste the results of `npx sb@next info` here.

System:
    OS: macOS 10.15.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 12.18.3 - ~/n/bin/node
    Yarn: 1.22.5 - ~/Source/trusted-web/node_modules/.bin/yarn
    npm: 6.14.6 - ~/n/bin/npm
  Browsers:
    Firefox: 72.0.2
    Safari: 13.1.2
  npmPackages:
    @storybook/addon-essentials: 6.1.0-alpha.1 => 6.1.0-alpha.1 
    @storybook/addon-knobs: 6.1.0-alpha.1 => 6.1.0-alpha.1 
    @storybook/addons: 6.1.0-alpha.1 => 6.1.0-alpha.1 
    @storybook/cli: 6.1.0-alpha.1 => 6.1.0-alpha.1 
    @storybook/react: 6.1.0-alpha.1 => 6.1.0-alpha.1 

**Additional context**

**Comment by ndelangen** [comment]
It now features a button to set a value
