### ISSUE TITLE
addon-storysource not producing useful code examples using recommended stories approach

### ISSUE THREAD

**Issue by roblevintennis** [storybookjs/storybook#12495]
**Is your feature request related to a problem? Please describe.**

I've been following the tutorials and docs to create many stories using the props driven pattern described there. I have projects in React, Svelte, and Vue, and each have their own storybook with similar configurations.

Using the prescribed patterns in the featured storybook docs/tutorials this is the approach I've used (it's Svelte based, but I've mostly done the same thing for React and Vue with similar results):

```javascript
import Button from './Button.svelte';

export default {
  title: 'Button',
  component: Button,
  argTypes: {
    label: { control: 'text' },
...and so on
  },
};

const Template = ({ onClick, ...args }) => ({
  Component: Button,
  props: args,
});

export const Primary = Template.bind({});
Primary.args = {
  label: 'Button',
  mode: 'primary',
};
...and so on
```

When I show code or look at the addon-storysource I see the template code which won't be a helpful dev ux for readers of my design system. Note the examples are really showing the `Template` intermediary component and are all the same:

![image](https://user-images.githubusercontent.com/142403/93348092-a6bc7d00-f7ea-11ea-8a19-3c3aec9a5f12.png)

and same for the addon-storysource tab:

![image](https://user-images.githubusercontent.com/142403/93348165-bb991080-f7ea-11ea-8498-a0266db9237d.png)

**Describe the solution you'd like**
I'm listing this as a feature as I believe the addon is working as designed. However, I'm confused on the overall result—if this props driven approach to testing is the recommendation, but the code snippet examples derived are essentially meaningless to the dev users, how am I able to achieve the goal of documenting how to use a component?

As a previous user of react-styleguidist (and other similar tools), getting code snippets was fairly trivial. For styleguidist, it would simply output the code blocks within your markdown giving you some control of what the user would see.

I'm fairly new to storybook but have already written a slew of these stories so I'm hoping I've missed something in the usage somehow.
 
**Describe alternatives you've considered**
I've seen some older storiesOf examples that seem to use the template or jsx more closely and wonder if those output better code examples. However, I've written so many of these stories using the docs recommended way that it would be a bear to refactor them all, especially if I'm using an older less idiomatic approach then the props driven newer one that's clearly being featured on the docs and tutorial pages for storybook.

**Are you able to assist bring the feature to reality?**
no | yes, I can...

**Additional context**

To be clear, I'd expect the source code examples to show something more meaningful like this I've taken from another similar project I've worked on:

![image](https://user-images.githubusercontent.com/142403/93349135-f485b500-f7eb-11ea-8bf5-18651727751d.png)

**Comment by roblevintennis** [comment]
Ok, this may turn into a self resolving issue, but I'll keep my notes for others having same quandary :)

I'm starting to learn more digging deeper into the docs section and considering MDX and other alternatives per your writing docs guides:
https://storybook.js.org/docs/react/writing-docs/introduction, and also looking more closely at some of the examples like https://github.com/storybookjs/design-system/blob/master/src/components/Button.stories.js.

So, it looks for React this approach can work (alongside the more modern props approach I showed above):

```react
export const DisabledAll = () => (
  <>
    <Button label="Default Disabled" isDisabled />
    <Button mode="primary" label="Primary Disabled" isDisabled />
    <Button mode="secondary" label="Secondary Disabled" isDisabled />
    <Button mode="secondary" label="Secondary Bordered Disabled" isBordered isDisabled />
  </>
);
```

I could be wrong, but for Vue and Svelte, it seems I need either some sort of special storybook loader that I'm not aware of, or, I have to just create separate example files and then delegate to those. It seems to kind of resolve my issue and looks like:

```vue
<template>
  <div>
    <AgnosticButton label="Default Disabled" isDisabled />
    <AgnosticButton mode="primary" label="Primary Disabled" isDisabled />
    <AgnosticButton mode="secondary" label="Secondary Disabled" isDisabled />
    <AgnosticButton mode="secondary" label="Secondary Bordered Disabled" isBordered isDisabled />
  </div>
</template>

<script>
//ButtonsDisabled.vue
import AgnosticButton from "./Button.vue";
export default {
  name: "buttons-disabled",
};
</script>
```

And then here it is added to my stories suite alongside the other idiom of using props (I may decide to separate these 🤔 ):

```js
import AgnosticButton from './Button.vue';
import ButtonsDisabled from './ButtonsDisabled.vue';
import { action } from '@storybook/addon-actions';

export default {
  title: 'Button',
  component: AgnosticButton,
  argTypes: {
    label: { control: 'text' },
    mode: { control: 'text' },
    isBordered: { control: 'boolean' },
    isBlock: { control: 'boolean' },
    isDisabled: { control: 'boolean' },
    isRaised: { control: 'boolean' },
    isRounded: { control: 'boolean' },
    isSkinned: { control: 'boolean' },
    size: {
      control: { type: 'select', options: ['small', 'large'] },
    },
  },
};

export const ButtonsDisabledTest = () => ({
  components: { ButtonsDisabled },
  template: '<buttons-disabled />'
});

const Template = (args, { argTypes }) => ({
  props: Object.keys(argTypes),
  components: { AgnosticButton },
  template: '<agnostic-button @click="onClick" v-bind="$props" />',
  methods: {
    onClick: action('onClick'),
  },
});

export const Primary = Template.bind({});
Primary.args = {
  label: 'Primary',
  mode: 'primary',
};

/* many more examples */
```

This seems to get me the code snippets I'm after more or less:

![image](https://user-images.githubusercontent.com/142403/93370450-b1d0d680-f805-11ea-859a-18917fcaa184.png)

**Comment by shilman** [comment]
If you write the code like this:

```js
export const Foo = () => <Button>bar</Button>
```

The source code should show:

```js
() => <Button>bar</Button>
```

In 6.0 we've introduced the [Args](https://medium.com/storybookjs/introducing-storybook-args-2dadcdb777cc) construct, which you're using in the example above.

As the Story function becomes more abstract, it gets further from what you'd want, as you note in the issue.

In React, I've introduced dynamic snippet rendering, so that we render the JSX based on the live values of the args being passed into the function.

So the if `{ children: "bar" }` was passed into this story:

```js
export const Foo = ({ children }) => <Button>{children}</Button>
```

The source block would display:

```js
<Button>bar</Button>
```

This was implemented in https://github.com/storybookjs/storybook/pull/11332. There are followup issues for some of the popular frameworks: https://github.com/storybookjs/storybook/issues/11400, https://github.com/storybookjs/storybook/issues/11588, https://github.com/storybookjs/storybook/issues/10617

If you're interested in contributing an implementation for your favorite framework, I'm happy to help guide. Otherwise, you can either use the non-args stories, or you can manually override the source snippet to be anything you want using the `docs.source.code` story parameter.

**Comment by roblevintennis** [comment]
Thanks for the timely reply sir! I see `addons/docs/src/blocks/SourceContainer.tsx` seems to do a lot of the heavy lifting there. In any event, I think this will work itself out in time esp. with these dynamic snippet rendering things you're starting to add!

I'm not sure I can commit to contributing atm but I'll keep it in mind and can empathize that you'd prefer to shepherd collective ownership and contribution from the community!

**Comment by roblevintennis** [comment]
So I'm confused why React works so well when I do something like this I get the snippet with everything in the react fragment nicely:

```javascript
export const DisabledAll = () => (
  <>
    <Button label="Default Disabled" isDisabled />
    <Button mode="primary" label="Primary Disabled" isDisabled />
    <Button mode="secondary" label="Secondary Disabled" isDisabled />
    <Button mode="secondary" label="Secondary Bordered Disabled" isBordered isDisabled />
  </>
);

```


But in Vue. First, I cannot use JSX within stories.js so I have to utilize a sub-view, but here's what I've tried for that:

```javascript
<template>
  <div>
    <AgnosticButton label="Default Disabled" isDisabled />
    <AgnosticButton mode="primary" label="Primary Disabled" isDisabled />
    <AgnosticButton mode="secondary" label="Secondary Disabled" isDisabled />
    <AgnosticButton mode="secondary" label="Secondary Bordered Disabled" isBordered isDisabled />
  </div>
</template>

<script>
// ButtonsDisabled.vue
import AgnosticButton from "./Button.vue";
export default {
  name: "buttons-disabled",
  components: { AgnosticButton },
};
</script>

```

```javascript
import ButtonsDisabled from './ButtonsDisabled.vue';

export default {
  title: 'Button',
  component: AgnosticButton,
  // etc.
}

export const ButtonsDisabledAll = () => ({
  title: 'Buttons Disabled',
  components: { ButtonsDisabled },
  template: `<buttons-disabled />`,
  parameters: {
    docs: {
      source: {
        code: `
          <AgnosticButton label="Default Disabled" isDisabled />
          <AgnosticButton mode="primary" label="Primary Disabled" isDisabled />
          <AgnosticButton mode="secondary" label="Secondary Disabled" isDisabled />
          <AgnosticButton mode="secondary" label="Secondary Bordered Disabled" isBordered isDisabled />
        `
      }
    }
  }
});
```

![image](https://user-images.githubusercontent.com/142403/93477025-565b2300-f8af-11ea-8934-def0076238d5.png)


![image](https://user-images.githubusercontent.com/142403/93477074-65da6c00-f8af-11ea-9252-b64d5432056e.png)


Is this the expected output?

**Comment by roblevintennis** [comment]
Ok, I'm leaving all my user-land mistakes above in case someone else is having same issues :) Here's what fixed the `docs.source.code` part (my fault for straying from docs in earlier attempts):

```javascript
export const ButtonsDisabledAll = () => ({
  title: 'Buttons Disabled',
  components: { ButtonsDisabled },
  template: `<buttons-disabled />`,
});
ButtonsDisabledAll.parameters = {
  docs: {
    source: {
      code: `
<div>
  <AgnosticButton label="Default Disabled" isDisabled />
  <AgnosticButton mode="primary" label="Primary Disabled" isDisabled />
  <AgnosticButton mode="secondary" label="Secondary Disabled" isDisabled />
  <AgnosticButton mode="secondary" label="Secondary Bordered Disabled" isBordered isDisabled />
</div>
        `
    }
  },
}
```

So this works pretty well for snippet in Docs tab:

![image](https://user-images.githubusercontent.com/142403/93481562-8c020b00-f8b3-11ea-8ee3-efdc8f914241.png)


But for the Story tab:

![image](https://user-images.githubusercontent.com/142403/93481633-9e7c4480-f8b3-11ea-8394-53f8df61f8ee.png)


I suppose I could just go without using the addon-storysource since the Docs is showing the source there 🤔  -- still not ideal to have to manually copy code snippets into `docs.source.code` as those will diverge likely, but at least it's sort of working.

I'm still wondering if there's a more ideal approach that will synchronize what's rendered w/source snippets better for Vue and Svelte. Any ideas or recommendations?

**Comment by netzfluencer** [comment]
yes I would also be really interested in having shown the exact source code of the generated vue-component over the written storysource code. Our developers would prefer to copy the snippet of the component. In the past we used the addon https://github.com/pocka/storybook-addon-vue-info.

**Comment by curtgrimes** [comment]
This issue is still relevant.

**Comment by roblevintennis** [comment]
Yes, it will be nice when we no longer have to hard code the resulting template code which is error prone and tedious. I wish I had time to help with this but still do not. I'll leave it open for now. Thanks for chiming in to confirm it's still relevant @curtgrimes

**Comment by shilman** [comment]
@netzfluencer Dynamic snippet rendering for Vue has been implemented in 6.1 in #12812 using an improvement on `addon-view-info` by @pocka. React is in #11332. NOTE: these are for the Source block in Storybook Docs, not for addon-storysource.

@curtgrimes @roblevintennis if either of you is interested in implementing this for the framework of your choice, I'd be happy to help guide.

**Comment by atflick** [comment]
Does this work or how do you activate?  I'm still getting this in source after updating to latest:
```js
(args, { argTypes }) => ({
  components: { EnDropdown },
  props: Object.keys(argTypes),
  template: `<EnDropdown v-bind="$props"></EnDropdown>`,
})
```

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).

**Comment by raythurnvoid** [comment]
To whoever ends up here without a solution here's mine.

I'm on Storybook 8.4.x and i use Vite with React.

Luckly we have Claude and other LLMs so i was able to make it work. Instead of relying on storybook's source generation i copy-paste the code manually into `docs.source.code` or i ask the LLM to generate it for me and then i've created a custom addon to show the same source component available in the docs, also in the addons panel for each story.

Custom addon file: .storybook/addons/source-tab/manager.tsx
```tsx
import React from "react";
import { addons, types } from "@storybook/manager-api";
import { AddonPanel } from "@storybook/components";
import { Source } from "@storybook/blocks";
import { useStorybookApi, useStorybookState } from "@storybook/manager-api";
import { useTheme } from "@storybook/theming";

const ADDON_ID = "storybook/source-tab";
const PANEL_ID = `${ADDON_ID}/panel`;

const SourcePanel = () => {
	const api = useStorybookApi();
	const state = useStorybookState();
	const theme = useTheme();
	const story = api.getData(state.storyId, state.refId);

	if (!story) {
		return null;
	}

	return (
		<div style={{ padding: "1rem" }}>
			<Source
				code={story.parameters?.docs?.source?.code || "// No source available"}
				language="tsx"
				dark={theme.base === "dark"}
			/>
		</div>
	);
};

addons.register(ADDON_ID, () => {
	addons.add(PANEL_ID, {
		type: types.PANEL,
		title: "Source",
		render: ({ active }) => (
			<AddonPanel active={active || false}>
				<SourcePanel />
			</AddonPanel>
		),
	});
});
```

My .storybook/main.ts

```ts
import type { StorybookConfig } from "@storybook/react-vite";

const config: StorybookConfig = {
	stories: ["../src/**/*.mdx", "../src/**/*.stories.@(js|jsx|mjs|ts|tsx)"],
	addons: [
		"@storybook/addon-onboarding",
		{
			name: "@storybook/addon-essentials",
			options: {
				actions: false,
				interactions: false,
				controls: false,
			},
		},
		"@chromatic-com/storybook",
		"storybook-dark-mode",
		"./addons/source-tab/manager.tsx",
	],
	framework: {
		name: "@storybook/react-vite",
		options: {},
	},
};
export default config;
```

My stories then look like this:

```tsx
export const Primary: Story = {
	args: {
		variant: "primary",
		children: <SybButtonText>Button</SybButtonText>,
	},
	parameters: {
		controls: {
			exclude: [...excluded_controls_non_default_stories, "variant"],
		},
		docs: {
			source: {
				code: source`
					<SybButton variant="primary">
						<SybButtonText>Button</SybButtonText>
					</SybButton>
				`,
			},
		},
	},
};
```

This is the result

![Image](https://github.com/user-attachments/assets/f6dec645-922c-42b6-bb44-95175bcb6a92)


May seem a nightmare to maintain but actually is not, I use cursor and ask it to generate all the stories for me and keep the source up to date.
