### ISSUE TITLE
Storybook not rendering all React props in the controls and docs when using imported types 

### ISSUE THREAD

**Issue by MineiToshio** [storybookjs/storybook#12493]
**Describe the bug**
Storybook is not showing all the props in controls and docs. It happens when I import a Typescript type from another file.

**To Reproduce**

1. Create a file with some typing:
```ts
// colors.ts
export type TextColor = 'red' | 'blue';
```

2. Then use the created type in a component

```ts
// Text.tsx
import React, { FC } from 'react';
import TextColor from './colors';

export type Props = {
  textColor: TextColor;
  text: string;
};

const Text: FC<Props> = ({ textColor, text }) => (
  <div style{{ color: textColor }}>{ text }</div>
)
```

If I do that, only `text` appears in the controls and docs.

**Expected behavior**
All props should appear in the controls and docs panels.

**Screenshots**
This is my props definition:
![image](https://user-images.githubusercontent.com/38053554/93302600-df932c80-f7bf-11ea-96c9-222a86218e4f.png)

This is what appears in controls. It is missing `iconColor` and `color`.
![image](https://user-images.githubusercontent.com/38053554/93302701-05203600-f7c0-11ea-8002-8a53f3101aa6.png)

This is what appears in docs. Also missing `iconColor` and `color` and `icon` has no description.
![image](https://user-images.githubusercontent.com/38053554/93302878-3e58a600-f7c0-11ea-9813-9f605773cb6e.png)

This is the typing of `Icons`, `TextColor` and `ButtonColor`:
![image](https://user-images.githubusercontent.com/38053554/93303098-9394b780-f7c0-11ea-967d-464939386634.png)
![image](https://user-images.githubusercontent.com/38053554/93303063-8972b900-f7c0-11ea-8af5-3c3e2cd96993.png)

**Code snippets**
See to reproduce section

**System:**
  System:
    OS: Windows 10 10.0.19041
    CPU: (4) x64 Intel(R) Core(TM) i7-4500U CPU @ 1.80GHz
  Binaries:
    Node: 12.13.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.12.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 85.0.4183.102
    Edge: Spartan (44.19041.423.0), Chromium (85.0.564.51)
  npmGlobalPackages:
    @storybook/cli: 6.0.21

**Comment by shilman** [comment]
can you share your `.storybook/main.js` configuration?

**Comment by MineiToshio** [comment]
> can you share your `.storybook/main.js` configuration? or, better yet, a public repro repo?

Hey @shilman! This is the `.storybook/main.js`.

```js
module.exports = {
  stories: [
    '../**/*.stories.mdx',
    '../**/*.stories.@(js|jsx|ts|tsx)'
  ],
  addons: ['@storybook/addon-essentials'],
};
```

Sorry the repo is private, but if anything else is needed I'm happy to help.

**Comment by jmpolitzer** [comment]
I am experiencing this same issue, and it looks like others are as well. See https://github.com/storybookjs/storybook/issues/13548. Can we reactivate this?

**Comment by shilman** [comment]
@jmpolitzer Do you have a repro repo you can share?

**Comment by jmpolitzer** [comment]
@shilman Thanks for the response. It turns out that my issue revolved around components imported from an external library, which I found a fix for here. I believe this can be closed.

<img width="1059" alt="Screen Shot 2021-02-25 at 3 41 09 PM" src="https://user-images.githubusercontent.com/5421419/109223209-ed41da80-777f-11eb-9fbd-dd3feceeb9d8.png">

**Comment by gregg-cbs** [comment]
I am having this issue, all my other components work fine, but all of a sudden this new one doesnt? And i cant figure it out.

```javascript
// storybook
import React from 'react'
import { ComponentStory } from '@storybook/react'

import IconText from '../../components/theme/Diageo/DIconText'
import LocationIcon from '../../components/icons/LocationIcon'

// More on default export: https://storybook.js.org/docs/react/writing-stories/introduction#default-export
export default {
  title: 'Base/IconText',
  component: IconText,
}

// More on component templates: https://storybook.js.org/docs/react/writing-stories/introduction#using-args
const Template: ComponentStory<typeof IconText> = (args) => <IconText {...args} />

export const Base = Template.bind({})

Base.args = {
  text: 'hello',
  icon: <LocationIcon />,
}
```

```javascript
// IconText component
import React from 'react'

type IconTextProps = {
  icon: JSX.Element
  text: string
  reversed?: boolean
  className?: string
}

export default function IconText({ icon, text, reversed, className, ...props }: IconTextProps) {
  return (
    <div className={`icon-text ${className} ${reversed ? 'icon-text-reversed' : null}`} {...props}>
      <span className="icon-text-icon">{icon}</span>
      <span className="icon-text-text">{text}</span>
    </div>
  )
}
```

output:
![image](https://user-images.githubusercontent.com/57114335/160598982-8c3b7672-ba5f-4be3-8b80-5b579e06ed2e.png)

**Comment by The-Code-Monkey** [comment]
I think a good fix for this would be possibly having another field in the default export for the story for the props interface to be added to rather than trying to find it from the component itself.

**Comment by stembrino** [comment]
Same with me.
To additionally. the Actions also stopped working: `parameters: { actions: { argTypesRegex: "^on.*" } },`

```ts
import SlotButton from "..";
import type { Meta, StoryObj } from "@storybook/react";

const meta: Meta<typeof SlotButton> = {
  title: "SlotButton",
  component: SlotButton,
  parameters: { actions: { argTypesRegex: "^on.*" } },
};

export default meta;
type Story = StoryObj<typeof SlotButton>;

export const Primary: Story = { args: { label: "BUTTON" } };
```

**Comment by felahgs** [comment]
I was having this issue and couldn't find an answer anywhere. So just in case there's someone who had the same problem that I had.

I found that by altering the way I declare my component, the issue was resolved. It appears that if the component is declared using const, the autodoc is unable to produce anything, changing the declaration to function resolved the problem.
![image](https://github.com/storybookjs/storybook/assets/13948935/1c7f0234-13f4-46c0-b28d-0d009d1112fc)

**Comment by valentinpalkovic** [comment]
We have upgraded react-docgen recently to version 7. You can try to activate it and see whether your issues get resolved. Please make sure to install at least Storybook 7.6.0-alpha.2 and configure using `react-docgen` instead of `react-docgen-typescript`. See the appropriate documentation for more information: https://storybook.js.org/docs/react/api/main-config-typescript#reactdocgen

**Comment by basickarl** [comment]
> I was having this issue and couldn't find an answer anywhere. So just in case there's someone who had the same problem that I had.
> 
> I found that by altering the way I declare my component, the issue was resolved. It appears that if the component is declared using const, the autodoc is unable to produce anything, changing the declaration to function resolved the problem. ![image](https://private-user-images.githubusercontent.com/13948935/260309738-1c7f0234-13f4-46c0-b28d-0d009d1112fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNzYzNzMsIm5iZiI6MTcwNTA3NjA3MywicGF0aCI6Ii8xMzk0ODkzNS8yNjAzMDk3MzgtMWM3ZjAyMzQtMTNmNC00NmMwLWIyOGQtMGQwMDlkMTExMmZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDE2MTQzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwMzEyYjAyMDI0OTU2OGI0YmE1MmQ2NDFjYTE1MTMxODY4MDAzYzgzZjI5MTU3MmU2MzFhZGQ0ZjNlNjI5MzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lRKI_p-ZWONbfRgpwoyqghiwWBkyq4azEZeYdg2ySYc)

This is also the reason why some of my component properties won't display, changing to function declaration fixed it.

**Comment by abbas-quikieapps** [comment]
For those who are using Material UI:

Add the following to your `main.ts` `config`:

```
typescript: {
    reactDocgen: 'react-docgen-typescript',
    reactDocgenTypescriptOptions: {
      // Speeds up Storybook build time
      compilerOptions: {
        allowSyntheticDefaultImports: false,
        esModuleInterop: false,
      },
      // Makes union prop types like variant and size appear as select controls
      shouldExtractLiteralValuesFromEnum: true,
      // Makes string and boolean types that can be undefined appear as inputs and switches
      shouldRemoveUndefinedFromOptional: true,
      // The magic: Filter out third-party props from node_modules except @mui packages
      propFilter: (prop) => true,
    },
  },
```

important line (worked for me since I'm using a monorepo):
`propFilter: (prop) => true` 

It's better to use this if it works for your setup: 
```
propFilter: (prop) =>
        prop.parent ? !/node_modules\/(?!@mui)/.test(prop.parent.fileName) : true,
```

Source: https://storybook.js.org/recipes/@mui/material

**Comment by hosseini44444** [comment]
For those who are using Material UI:

Add the following to your `main.ts` `config`:

```
typescript: {
    reactDocgen: 'react-docgen-typescript',
    reactDocgenTypescriptOptions: {
      // Speeds up Storybook build time
      compilerOptions: {
        allowSyntheticDefaultImports: false,
        esModuleInterop: false,
      },
      // Makes union prop types like variant and size appear as select controls
      shouldExtractLiteralValuesFromEnum: true,
      // Makes string and boolean types that can be undefined appear as inputs and switches
      shouldRemoveUndefinedFromOptional: true,
      // The magic: Filter out third-party props from node_modules except @mui packages
      propFilter: (prop) => true,
    },
  },
```

important line (worked for me since I'm using a monorepo):
`propFilter: (prop) => true` 

It's better to use this if it works for your setup: 
```
propFilter: (prop) =>
        prop.parent ? !/node_modules\/(?!@mui)/.test(prop.parent.fileName) : true,
```

Source: https://storybook.js.org/recipes/@mui/material
