### ISSUE TITLE
storybook args: complex values change but doesn't update in panel.

### ISSUE THREAD

**Issue by lifeiscontent** [storybookjs/storybook#12498]
**Describe the bug**

using the code below, if I select 'center top' the story updates correctly, but the value of the input in the panel doesn't update in controls addon. Might also be in addon-docs as well.

**To Reproduce**

1. Create a story using a complex value of options demonstrated below.
2. Change the value in the controls addon
3. See the story update, but the value in the panel does not.

**Expected behavior**

**Screenshots**

**Code snippets**
```
  anchorOrigin: {
    control: {
      type: 'select',
      options: {
        'left top': { horizontal: 'left', vertical: 'top' },
        'center top': { horizontal: 'center', vertical: 'top' },
        'right top': { horizontal: 'right', vertical: 'top' },
        'left bottom': { horizontal: 'left', vertical: 'bottom' },
        'center bottom': { horizontal: 'center', vertical: 'bottom' },
        'right bottom': { horizontal: 'right', vertical: 'bottom' },
      },
    },
  },
```

**System:**
Latest Alpha

**Additional context**
❤️

**Comment by lifeiscontent** [comment]
CC: @shilman

**Comment by shilman** [comment]
closing as dupe to #12122
