### ISSUE TITLE
Unexpected default export without title: undefined

### ISSUE THREAD

**Issue by rrepala03** [storybookjs/storybook#12506]
### Bug or support request summary
**Experiencing following error while accessing storybook app when story written in mdx:**

Unexpected default export without title: undefined
Error: Unexpected default export without title: undefined
   at Anonymous function (http://localhost:6005/vendors~main.864c9d1b6eda5b78ee86.bundle.js:55889:9)
   at Array.prototype.forEach (native code)
   at Anonymous function (http://localhost:6005/vendors~main.864c9d1b6eda5b78ee86.bundle.js:55882:5)
   at configure (http://localhost:6005/vendors~main.864c9d1b6eda5b78ee86.bundle.js:37288:7)
   at Anonymous function (http://localhost:6005/vendors~main.864c9d1b6eda5b78ee86.bundle.js:56030:7)
   at configure (http://localhost:6005/vendors~main.864c9d1b6eda5b78ee86.bundle.js:56699:3)
   at Anonymous function (http://localhost:6005/main.864c9d1b6eda5b78ee86.bundle.js:23595:2)
   at ./.storybook/generated-stories-entry.js (http://localhost:6005/main.864c9d1b6eda5b78ee86.bundle.js:23589:29)
   at __webpack_require__ (http://localhost:6005/runtime~main.864c9d1b6eda5b78ee86.bundle.js:849:12)
   at fn (http://localhost:6005/runtime~main.864c9d1b6eda5b78ee86.bundle.js:151:13)

Application should render properly with stories.

### Steps to reproduce

main.js:

```
module.exports = {
  "stories": [
    "../stories/**/*Stories.@(js|mdx|jsx|ts|tsx)",
    "../stories/**/*.stories.mdx"
  ],
  addons: [
    '@storybook/addon-essentials',
    '@storybook/addon-links',
    '@storybook/addon-storysource',
    '@storybook/addon-knobs/register'
  ]
}
```

manager.js:

```
import { addons } from '@storybook/addons';
import theme from './customTheme';

addons.setConfig({
  theme: theme
});
```

webpack.config.js:

```
module.exports = ({ config }) => ({
  ...config,
  module: {
    ...config.module,
    rules: [
      {
        test: /\.(stories|story).mdx$/,
        use: [
          {
            loader: 'babel-loader',
            options: {
              babelrc: false,
              configFile: false,
              presets: ["react-app"],
              plugins: [
                [
                  '@babel/plugin-transform-react-jsx'
                ]
              ],
              overrides: [
                {
                  test: /\.(mjs|jsx?)$/,
                  plugins: [
                    [
                      'babel-plugin-react-docgen'
                    ]
                  ]
                }
              ]
            }
          },
          {
            loader: '@mdx-js/loader'
          }
        ]
      },
      {
        test: /\.mdx$/,
        exclude: /\.(stories|story).mdx$/,
        use: [
          {
            loader: 'babel-loader',
            options: {
              babelrc: false,
              configFile: false,
              presets: ["react-app"],
              plugins: [
                [
                  '@babel/plugin-transform-react-jsx'
                ]
              ],
              overrides: [
                {
                  test: /\.(mjs|jsx?)$/,
                  plugins: [
                    [
                      'babel-plugin-react-docgen'
                    ]
                  ]
                }
              ]
            }
          },
          {
            loader: '@mdx-js/loader'
          }
        ]
      },
      {
        test: /\.jsx?$/,
        use: [
          {
            loader: "babel-loader",
            options: {
              sourceType: "unambiguous",
              babelrc: false,
              presets: ["react-app"],
            },
          },
        ],
      }
    ],
  },
});
```

### Please specify which version of Storybook and optionally any affected addons that you're running

```
- "@storybook/react": "^6.0.21"
- "@storybook/addon-actions": "^6.0.21",
    "@storybook/addon-backgrounds": "^6.0.21",
    "@storybook/addon-docs": "^6.0.21",
    "@storybook/addon-essentials": "^6.0.21",
    "@storybook/addon-knobs": "^6.0.21",
    "@storybook/addon-links": "^6.0.21",
    "@storybook/addon-storysource": "^6.0.21",
    "@storybook/addons": "^6.0.21",
    "@storybook/preset-create-react-app": "^3.1.4",
```

### Screenshots / Screencast / Code Snippets (Optional)

```js
Button.js

import React from 'react';
import PropTypes from 'prop-types';
import './button.css';

/**
 * Primary UI component for user interaction
 */
export const Button = ({ primary, backgroundColor, size, label, ...props }) => {
  const mode = primary ? 'storybook-button--primary' : 'storybook-button--secondary';
  return (
    <button
      type="button"
      className={['storybook-button', `storybook-button--${size}`, mode].join(' ')}
      style={backgroundColor && { backgroundColor }}
      {...props}
    >
      {label}
    </button>
  );
};

Button.propTypes = {
  /**
   * Is this the principal call to action on the page?
   */
  primary: PropTypes.bool,
  /**
   * What background color to use
   */
  backgroundColor: PropTypes.string,
  /**
   * How large should the button be?
   */
  size: PropTypes.oneOf(['small', 'medium', 'large']),
  /**
   * Button contents
   */
  label: PropTypes.string.isRequired,
  /**
   * Optional click handler
   */
  onClick: PropTypes.func,
};

Button.defaultProps = {
  backgroundColor: null,
  primary: false,
  size: 'medium',
  onClick: undefined,
};
```

Button.stories.mdx

```
import { Meta, Story, Canvas } from '@storybook/addon-docs/blocks';

import { Button } from './Button';

<Meta title="MDX/Button" component={Button} />

<!--- This is your Story template function, shown here in React -->

export const Template = (args) => <Button {...args } />

# Button

Let's define a story for our `Button` component:

<Story name="positive" args={{
    primary: true, 
    label: 'Positive' 
}}>
  {Template.bind({})}
</Story>

We can drop it in a `Canvas` to get a code snippet:

<Canvas>
  <Story name="negative" args={{
      size: 'large', 
      label: 'Negative'
  }}>
    {Template.bind({})}
  </Story>
</Canvas>

We can even preview multiple Stories in a block. This
gets rendered as a group, but defines individual stories
with unique URLs which is great for review and testing.

<Canvas>
  <Story name="warning" args={{
      size: 'large',
      label: 'Warning' 
  }}>
    {Template.bind({})}
  </Story>
  <Story name="neutral" args={{
      size: 'small', 
      label: 'Neutral' 
  }}>
    {Template.bind({})}
  </Story>
  <Story name="error" args={{
      size: 'small', 
      label: 'Error' 
  }}>
    {Template.bind({})}
  </Story>
</Canvas>

```

![image](https://user-images.githubusercontent.com/65977481/93488174-0e022c00-f8d4-11ea-99ad-a68ee9d4a93d.png)

End bug report support request

**Comment by rterala** [comment]
@shilman  Please look into this. and confirm.

**Comment by shilman** [comment]
```
      {
        test: /\.mdx$/,
        exclude: /\.(stories|story).mdx$/,
        use: [
          {
            loader: 'babel-loader',
            options: {
              babelrc: false,
              configFile: false,
              presets: ["react-app"],
              plugins: [
                [
                  '@babel/plugin-transform-react-jsx'
                ]
              ],
              overrides: [
                {
                  test: /\.(mjs|jsx?)$/,
                  plugins: [
                    [
                      'babel-plugin-react-docgen'
                    ]
                  ]
                }
              ]
            }
          },
          {
            loader: '@mdx-js/loader'
          }
        ]
      },
```

This rule is wrong. It doesn't reference Storybook's MDX compiler. You should probably use the addon-docs preset.

**Comment by rterala** [comment]
@shilman None of the configs work for me please guide me through. Here is my webpack config and main.js
**webpack.config.js**
module.exports = ({ config }) => ({
  ...config,
  module: {
    rules: [
      {
        test: /\.mdx$/,
        use: [
          {
            loader: "babel-loader",
            options: {
              sourceType: "unambiguous",
              babelrc: false,
              presets: ["@babel/env", "@babel/react"],
            },
          },
          {
            loader: '@mdx-js/loader',
          },
          
        ],
        
      },
      {
        test: /\.jsx?$/,
        use: [
          {
            loader: "babel-loader",
            options: {
              sourceType: "unambiguous",
              babelrc: false,
              presets: ["react-app"],
            },
          },
        ],
      },
      {
        test: /\.(css|scss)$/,
        use: [
          "style-loader",
          {
            loader: "css-loader",
            options: {
              importLoaders: 1,
              sourceMap: true,
              modules: {
                localIdentName: '[name]__[local]'
              }
            }
          },
          {
            loader: 'postcss-loader',
            options: {
              sourceMap: true,
              postcssOptions: {
                plugins: [
                  require('cssnano')({
                    preset: 'advanced'
                  })
                ]
              }
            }
          },
          {
            loader: 'sass-loader', options: { sourceMap: true }
          }
        ]
      },
      {
        test: /\.(png|woff|woff2|eot|ttf|svg|jpg)$/,
        loader: "url-loader",
      },
    ],
  },
});


**main.js**
module.exports = {
  "stories": [
    "../stories/**/*Stories.@(js|mdx|jsx)"
  ],
  addons: [
    '@storybook/addon-knobs/register',
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    '@storybook/preset-create-react-app',
    '@storybook/addon-storysource'
  ]
}

**Comment by rterala** [comment]
@shilman Can you please help on this.

**Comment by tangoabcdelta** [comment]
I am not sure if this is the right solution but after arriving at this page I made the following modification:


- I went to `Button.js`
- Instead of `export const Button = ...`, I just wrote `const Button = ...`
- Added `export default Button;` at the bottom of the page

Modern day CRA usually complains that you must define a variable first. You can not define and `export` it on the same line. So, I took a cue from it and prepared this quick workaround by changing the `default export` statement.
 
@rrepala03 let me know if it solved your problem.
