### ISSUE TITLE
Material UI interface props not showing in Docs

### ISSUE THREAD

**Issue by nextglabs** [storybookjs/storybook#12508]
**Describe the bug**
I'm using MaterialUI which I slightly modify (styling/logic) in order to create a custom library.  I'm also using Storybook (with Typescript) to create documentation. 

The problem I'm facing is that the storybook table props are not always automatically generated.  It only shows the props I added, but none of the ones built by material UI. For example:

```typescript
import * as React from "react";
import MuiPaper from "@material-ui/core/Paper";
import clsx from "clsx";

export interface PaperProps extends MuiPaperProps {
    /**
     * If `true`, a darker background will be applied.
     * @default false
     */
    filled?: boolean;
    /**
     * If `true`, the border around the Paper will be removed.
     * @default false
     */
    disableOutline?: boolean;
}

const useStyles = makeStyles((theme: Theme) => ({
	root: {
		borderRadius: "8px",
		border: `1px solid ${theme.palette.grey[200]}`,
		"&$filled": {
			backgroundColor: theme.palette.grey[100],
		},
		"&$disableOutline": {
			border: "none",
		},
	},
	/* Pseudo-class applied to the root element if `disableOutline={true}`. */
	disableOutline: {},
	/* Pseudo-class applied to the root element if `filled={true}`. */
	filled: {},
}));

export const Paper: React.FC<PaperProps> = (props) => {
	const { disableOutline = false, filled = false, ...restProps } = props;
	const classes = useStyles();
	return (
		<MuiPaper
			classes={classes}
			className={clsx(classes.root, {
				[classes.disableOutline]: disableOutline,
				[classes.filled]: filled,
			})}
			{...restProps}
		/>
	);
};
```
 
**Screenshots**
[![missing material-ui table props in storybook canvas][1]][1]

[![missing material-ui table props in storybook docs][2]][2]

On the other hand, it works perfectly with MuiButton which is very strange. I can't figure out why it doesn't work with Paper.

[![material UI interface table props display correctly in storyboard docs][3]][3]

  [1]: https://i.stack.imgur.com/xIF57.png
  [2]: https://i.stack.imgur.com/JIUCv.png
  [3]: https://i.stack.imgur.com/Dmwex.png

**Expected behavior**
Typescript Interfaces from Material UI should be passed to the table props

**System:**
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
  Binaries:
    Node: 10.20.1 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 84.0.4147.125
    Firefox: 64.0.2
    Safari: 13.1.2
  npmPackages:
    @storybook/addon-a11y: ^6.0.21 => 6.0.21 
    @storybook/addon-actions: ^6.0.21 => 6.0.21 
    @storybook/addon-essentials: ^6.0.21 => 6.0.21 
    @storybook/addon-links: ^6.0.21 => 6.0.21 
    @storybook/node-logger: ^6.0.21 => 6.0.21 
    @storybook/preset-create-react-app: ^3.1.4 => 3.1.4 
    @storybook/preset-typescript: ^3.0.0 => 3.0.0 
    @storybook/react: ^6.0.21 => 6.0.21

**Comment by shilman** [comment]
Closing this as duplicate to #12129
