### ISSUE TITLE
Storyshots provide absolute vs relative path when a story is in storiesOf or CSF format when setting up custom directory

### ISSUE THREAD

**Issue by GasimGasimzada** [storybookjs/storybook#12513]
**Describe the bug**

This is related to https://github.com/storybookjs/storybook/issues/10673 and https://github.com/storybookjs/storybook/issues/9084

I have been trying to understand this issue for a while now and finally I think I found the culprit for one of my problems. We have the following structure for saving visual test snapshots relative to components:

```
src/initial.visual.test.ts
src/components/SomeComponent/stories/__image_snapshots__
src/components/AnotherComponent/stories/__image_snapshots__
...
```

In order to achieve that, we are passing `getMatchOptions` function storyshots-puppeteer package's `imageSnapshot` function. This function was very simple:

```ts
const getMatchOptions = ({ context: { fileName }}) => {
  const snapshotPath = path.join(path.dirname(fileName), '__image_snapshots__');
  return { customSnapshotsDir: snapshotPath };
}
```

This used to work fine with `storiesOf` format because the fileName that is provided for `storiesOf` stories are always in absolute format:

```
/app/src/components/SomeComponent/stories/SomeComponent.stories.tsx
```

However, with CSF stories, the path start relative to initial test suite:

```
components/SomeComponent/stories/SomeComponent.stories.tsx
```

This created the problem of stories being written to random location and it was hard to find because we are running our visual tests in a Docker container. Now that we know the reason, we have solved the issue by removing the absolute path ourselves and setting it up:

```ts
const snapshotPath = path.join(__dirname, path.dirname(fileName.replace(__dirname, '')), '__image_snapshots__');
```

**To Reproduce**

1. Create storiesOf and CSF stories
2. Set up a custom `getMatchOptions` function
3. Print fileName from context
4. Run tests

**Expected behavior**

The path should either be consistent for both story formats or documented somewhere; so that, we are aware of it.

**System:**

- Storybook version: `6.0.21`

**Comment by shilman** [comment]
That's pretty tricky and thank you for tracking it down.

@jonniebigodes Unfortunately fixing the problem is probably a breaking change, so I think for now our best bet is to document this, maybe in the Storyshots README or in a section of the official docs that describes the StoryContext (which I don't think exists, but probably should) WDYT?

**Comment by shilman** [comment]
Related: https://github.com/storybookjs/storybook/issues/7109

**Comment by latviancoder** [comment]
We are using both APIs in parallel, so we ended up with the following:

```
path.join(
  fileName.startsWith('./') ? srcDir : '',
  fileName,
  '../__image_snapshots__',
);
```

**Comment by shilman** [comment]
@latviancoder that's a pretty cool ... workaround is a nice way to say it 😄

**Comment by jonniebigodes** [comment]
@shilman like you've mentioned this is a breaking change, we could probably use the workaround supplied by @latviancoder in both the addon Readme and the [workflows/snapshot](https://storybook.js.org/docs/react/workflows/snapshot-testing) page to expand visibility. @latviancoder as you've supplied (at the lack of a better word) a workaround, if you're willing create the pull request and i'll gladly review it and we could merge it. If not i can take care of it. I'll leave it up to you, just let me know.

Also  currently there's no concrete documentation for the StoryContext and it would be on our best interest to give some context to the community on how it works, we have brief references about it through out the documentation, but nothing concrete. I would be more than thankful for your help on this one. I'm going to take a look where we could place it and i'll let you know.

**Comment by latviancoder** [comment]
In the workaround above the `srcDir` variable is specific to our project. I'm not sure I understand how this could be solved on the library level.

**Comment by tmeasday** [comment]
OK, I worked out the source of the problem here. The TLDR is that the issue

**Comment by GriffinSauce** [comment]
This appears to still be an issue. Are there any changes that could help to sidestep it?

**Comment by GasimGasimzada** [comment]
@GriffinSauce the suggested that I provided worked for our scenario really well for us but if you have the capacity, I would **strongly** suggest to migrate to CSF or MDX stories as it solves a lot of incompatibility issues with newer versions of Storybook.

**Comment by GriffinSauce** [comment]
Thanks @GasimGasimzada I was actually migrating to CSF and the problem appeared 😅 

I managed to make it work with two actions:
- we had a separate SB config for Storyshots that was in the old config style (IMO this should just be deprecated and cause an error, it's so easy to migrate), so that needed to be updated to `main`, `preview` etc.
- had to add `fileName: __filename` to the parameters for each story

Not very happy about the last thing... we're not using image snapshots (regular text snapshots) so I couldn't find anything like `getMatchOptions` to adjust and fix things globally.

**Comment by GasimGasimzada** [comment]
> Not very happy about the last thing... we're not using image snapshots (regular text snapshots) so I couldn't find anything like `getMatchOptions` to adjust and fix things globally.

This is a long shot but you might be able to derive a class from [Stories2SnapsConverter](https://github.com/storybookjs/storybook/blob/next/addons/storyshots/storyshots-core/src/Stories2SnapsConverter.ts) and sanitize the filename to your needs. I found it from [their docs reference](https://github.com/storybookjs/storybook/tree/next/addons/storyshots/storyshots-core#stories2snapsconverter) and it is specifically mentioned that:

> This parameter should be an instance of the [Stories2SnapsConverter](https://github.com/storybookjs/storybook/blob/next/addons/storyshots/storyshots-core/src/Stories2SnapsConverter.js) (or a derived from it)

So, it is worth a shot!

**Comment by ndelangen** [comment]
The future of storyshots is the test-runner:
https://storybook.js.org/docs/react/writing-tests/test-runner#page-top

And use the play function for expectations:
https://storybook.js.org/docs/react/writing-stories/play-function#page-top

We will not be making any improvement / changes to storyshots.
