### ISSUE TITLE
Cannot position grouped stories between stories of upper hierarchy level

### ISSUE THREAD

**Issue by diedu89** [storybookjs/storybook#12512]
**Describe the bug**
I'm not able to position a group of stories in a specific position among stories of an upper level in the hierarchy

**To Reproduce**

1. Create file with `default export { title: 'Sorted' }`
2. Defines `A` and `B` stories inside 'Sorted'
3. Create file with `default export { title: 'Sorted/C' }`
4. Define `CA`, `CB` and `CC` stories inside 'Sorted/C'
5. Define the order via `storySort` option trying to position grouped stories inside `C` in between `A` and `B`
`options: {
    storySort: {
      order: ['Sorted', ['B', 'C', 'A']]
    },
  },
`

**Expected behavior**
The menu items in navbar should appear in the defined order in the array: B item first, an expandable C item and A item last.

**Screenshots**
![Selection_003](https://user-images.githubusercontent.com/1129622/93551427-120d6880-f92b-11ea-8748-5b3cf9be8f7f.png)

**Code snippets**
I created a repo from scratch using cra and `sb init` https://github.com/diedu89/sb-sort-stories

**System:**
```
  System:
    OS: Linux 5.4 Ubuntu 18.04.5 LTS (Bionic Beaver)
    CPU: -
  Binaries:
    Node: 12.12.0 - ~/.asdf/installs/nodejs/12.12.0/bin/node
    Yarn: 1.21.1 - /usr/bin/yarn
    npm: 6.11.3 - ~/.asdf/installs/nodejs/12.12.0/bin/npm
  Browsers:
    Chrome: 84.0.4147.125
    Firefox: 80.0.1
  npmPackages:
    @storybook/addon-actions: ^6.0.21 => 6.0.21 
    @storybook/addon-essentials: ^6.0.21 => 6.0.21 
    @storybook/addon-links: ^6.0.21 => 6.0.21 
    @storybook/node-logger: ^6.0.21 => 6.0.21 
    @storybook/preset-create-react-app: ^3.1.4 => 3.1.4 
    @storybook/react: ^6.0.21 => 6.0.21 
```

**Additional context**
I'm upgrading from version 5.2 to 6.0.21, previously we used `configure()` which apparently sort in order of calls to `storiesOf` and allowed us to define the described order above (just my guess though)

**Comment by shilman** [comment]
Ooh-la-la!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.3.0-alpha.17 containing PR #12520 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
