### ISSUE TITLE
improve 'addon background darkmode' by using white color character

### ISSUE THREAD

**Issue by joielee09** [storybookjs/storybook#12525]
**Describe the bug**
When in dark mode I can't read the words because the background color changed to dark color.
This is from tutorial page component.

this is light mode
![lightmode](https://user-images.githubusercontent.com/67178982/93714295-9ca8ce80-fb9c-11ea-9348-19540554c556.PNG)

and this is dark mode
![darkmode](https://user-images.githubusercontent.com/67178982/93714300-9e729200-fb9c-11ea-865c-b92e35cbb1a8.PNG)

**To Reproduce**

**Expected behavior**
I think when we toggle into the dark mode, the word color can change into white.

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System:**
Please paste the results of `npx sb@next info` 

**Additional context**

**Comment by shilman** [comment]
The backgrounds addon is not a theme switcher -- it just changes the background color of the canvas, so what you're seeing is expected behavior. cc @yannbf

**Comment by joielee09** [comment]
> The backgrounds addon is not a theme switcher -- it just changes the background color of the canvas, so what you're seeing is expected behavior. cc @yannbf

**Comment by joielee09** [comment]
@shilman  Thx for your answer! I'll close the issue!

**Comment by yannbf** [comment]
Although you're right @shilman, the background color does give a weird feeling for the user when trying out the example components.. Maybe the default background color could be a little lighter, or rather the text?
