### ISSUE TITLE
Arg `defaultValue` gets set to a stringified version of the object via docgen

### ISSUE THREAD

**Issue by tmeasday** [storybookjs/storybook#12529]
**Describe the bug**

I can make a proper repo but this is in the `PureBuildSummary` of the Chromatic codebase

```js
// in Comp.js:
Comp.defaultProps = {
  obj: { a: 'b' }
}

// in Comp.stories.js:
export const Unset = Template.bind({});
Unset.args = {};

export const Set = Template.bind({});
Set.args = { obj: { has: 'value' } };
```

In `Unset`'s case `args.obj` shows up in the UI / and is passed to the component as a string with value `'{ "a": "b" }'` (i.e. JSON-ified version of `obj`). In `Set`'s case it is what you expect.

**Comment by pixelass** [comment]
I have a similar issue with enums in typescript

```tsx
export enum Size {
	medium = 24,
}

const Icon: React.FC<IconProps> = ({ className, icon, size }) => {
	console.log(size) // 'Size.medium' should be 24 
	return (
		<Svg viewBox={`0 0 ${size} ${size}`} size={size} className={className}>
			<title>{humanize(icon as string)}</title>
			<Path d={icons[size][icon]} />
		</Svg>
	);
};

Icon.defaultProps = {
	size: Size.medium,
};

```

This is the crucial line: `console.log(size) // 'Size.medium' should be 24`

When I set the args in a story everything works fine but relying on the defaultProps causes the error: `'Size.medium' should be 24`

**Comment by shilman** [comment]
Closing as dupe to #12076

**Comment by pixelass** [comment]
I have the same issue with enums (see: https://github.com/storybookjs/storybook/issues/12529#issuecomment-696066753)

So this is not only an issue with objects but in general values getting stringified instead of resolved/computed. 
The defaultProps work everywhere except for storybook.
