### ISSUE TITLE
Stories does not load on Microsoft Edge Canary

### ISSUE THREAD

**Issue by JYC-99** [storybookjs/storybook#12526]
**Describe the bug**
I'm using storybook version 5.3.19. It works well on Google Chrome and Microsoft Edge.
However it loads no stories on Microsoft Edge Canary(Version 87.0.644.0 (Official build) canary (64-bit))

**Screenshots**
![image](https://user-images.githubusercontent.com/5934735/93726847-c5f04b80-fbea-11ea-9711-729ae14fb5a1.png)
![image](https://user-images.githubusercontent.com/5934735/93726858-d6082b00-fbea-11ea-8067-634daae39f26.png)

My .storybook/config.ts

```ts
import { configure } from "@storybook/react";

function loadStories(): void {
  require("../stories");
}

configure(loadStories, module);
```

My .storybook webpack.config.js

```js
const CircularDependencyPlugin = require("circular-dependency-plugin");
const WorkerPlugin = require("worker-plugin");

module.exports = ({ config }) => {
  config.module.rules.push({
    test: /\.(ts|tsx)$/,
    use: [
      {
        loader: require.resolve("ts-loader"),
        options: {
          compilerOptions: {
            rootDir: "."
          }
        }
      }
    ]
  });
  config.resolve.extensions.push(".ts", ".tsx");
  config.plugins.push(new CircularDependencyPlugin());
  config.plugins.push(
    new WorkerPlugin({
      globalObject: "self"
    })
  );
  return config;
};
```

Webpack version: 4.41.2

**Comment by shilman** [comment]
Try upgrading to 6.0?

```
npx sb upgrade
```

[Full migration guide](https://medium.com/storybookjs/storybook-6-migration-guide-200346241bb5)

**Comment by JYC-99** [comment]
@shilman Thanks. Upgrading to 6.x is an ongoing work and it will take some time.
Currently our online demo site is broken on latest Edge Canary, do you can any suggestion to mitigate or workaround that?

BTW I'm seeing there is an "ie11" tag for this issue. Just want to clarify the issue happens on Chromium based Edge (Canary version
): https://www.microsoftedgeinsider.com/en-us/download

**Comment by shilman** [comment]
Ooh didn't realize it was Chromium based. I don't what the problem is, so my only suggestion other than upgrading (which might fix anything) would be to debug it. The 5.3 code is in the `release/5.3` branch and there are dev instructions in `./CONTRIBUTING.md`. With a full stack trace and source map the error might be easy to spot.

**Comment by shilman** [comment]
Possibly related #12677 #12626

**Comment by JYC-99** [comment]
I'm seeing everything is going well with 6.x version. Closing the issue.
