### ISSUE TITLE
Actions Addon: Display action amount in Panel Title

### ISSUE THREAD

**Issue by andre-brdoch** [storybookjs/storybook#12523]
**Is your feature request related to a problem? Please describe.**
If the action panel is not active, it is easy to miss actions that are being logged.

![image](https://user-images.githubusercontent.com/31482129/93692144-ae806800-faef-11ea-81b7-a293be39db78.png)

**Describe the solution you'd like**
Display the amount of actions logged so far in the Title of the panel
![image](https://user-images.githubusercontent.com/31482129/93692161-d243ae00-faef-11ea-834d-030a373a5937.png)

**Describe alternatives you've considered**
Not sure if it makes more sense to always show the total amount of actions logged so far, or only the "unread" ones.

**Are you able to assist bring the feature to reality?**
Possibly, I could give it a shot 😃

**Comment by shilman** [comment]
Closing as dupe to #11124 

Any chance you can pick that up @andre-brdoch ? I think it's a great feature 🙏
