### ISSUE TITLE
viewport change missing part of the page view

### ISSUE THREAD

**Issue by holylander** [storybookjs/storybook#12532]
**Describe the bug**
I noticed that if you story renders a full page, changing the viewport to `small mobile` or other will hide part of the page.

**To Reproduce**
- Create a story that renders some large content ( enough to require you to zoom out or scroll )
- Change the viewport
- Check if iframe still shows all the content ( you may need to use the scroll bar, still wont see the content )

**Expected behavior**
Use should still see the full content of the story, even you have a small viewport

**Additional context**
I solved the issue adding `height:100%` to the `#root` component in storybook.
Later on, I also found that it is pretty usefl to set the `width:100%` to the same `#root` element.

**Screenshots**
###*( without the css tweak )* I cant scroll up to see the top of the content of the story
![imagen](https://user-images.githubusercontent.com/2032683/93988786-6d0ae980-fd89-11ea-8ff3-2ac72b30427b.png)

###*( with the css tweak )* I cant scroll up to see the top of the content of the story
![imagen](https://user-images.githubusercontent.com/2032683/93989124-d2f77100-fd89-11ea-80d8-f73c90cf111c.png)

**Comment by holylander** [comment]
@shilman I have added some extra details. I could put a PR to the code, but I dont know where to locate this file in the repo :_(

**Comment by vanessayuenn** [comment]
Hi! I am going through and cleaning up old issues in the repo. We just shipped a ton of improvements in Storybook 7.0, and I suspect this bug might be fixed already. Can you please try it out? If this issue persists with the latest version, please open a new bug report with a 7.x reproduction. Thank you so much! 🙏🏼
