### ISSUE TITLE
Published Storybook Never Loads (perpetual spinner)

### ISSUE THREAD

**Issue by Jordan-Eckowitz** [storybookjs/storybook#12538]
**Describe the bug** 

When I try and publish my Storybook it builds fine but the deployed site never gets past the loading screen shown below.

It works fine when I run it locally with `npm run storybook`. 
It also works when I build it and run `npx http-server .[build-folder]`.
I, however, get the same error when I serve it `serve -s [build-folder]`.

I'm testing it on a blank CRA project with all the boilerplate stories.
Is anybody else experiencing this problem? 

<img width="1680" alt="Screen Shot 2020-09-22 at 12 11 58 AM" src="https://user-images.githubusercontent.com/19767538/93843687-b283c580-fc68-11ea-9fbf-c1931dc372e1.png">

**System:**  

```
Environment Info:

  System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    npm: 6.14.5 - ~/.nvm/versions/node/v12.16.1/bin/npm
  Browsers:
    Chrome: 85.0.4183.102
    Edge: 84.0.522.63
    Firefox: 78.0.1
    Safari: 14.0
  npmPackages:
    @storybook/addon-actions: ^6.0.21 => 6.0.21 
    @storybook/addon-essentials: ^6.0.21 => 6.0.21 
    @storybook/addon-links: ^6.0.21 => 6.0.21 
    @storybook/node-logger: ^6.0.21 => 6.0.21 
    @storybook/preset-create-react-app: ^3.1.4 => 3.1.4 
    @storybook/react: ^6.0.21 => 6.0.21 
```

**Comment by shilman** [comment]
not seeing this on OS X. @tooppaaa can you test on windows?

**Comment by tooppaaa** [comment]
I can reproduce on my machine.

"GET /iframe.html?id=*&viewMode=story" Error (404): "Not found"

**Comment by shilman** [comment]
Sorry I misread the original issue. `serve` doesn't work with Storybook. It tries to turn the `/iframe.html` request into `/iframe`.

I believe that all the documentation recommends `http-server`. @jonniebigodes perhaps we need to document that `serve` is broken?

**Comment by Jordan-Eckowitz** [comment]
> Sorry I misread the original issue. `serve` doesn't work with Storybook. It tries to turn the `/iframe.html` request into `/iframe`.
> 
> I believe that all the documentation recommends `http-server`. @jonniebigodes perhaps we need to document that `serve` is broken?

Hi @shilman, thanks for the help. The main point of the post was to show that when I deploy a storybook site it doesn’t work. I get the same result as when I serve it. 

So I’m not sure if there’s some sort of bug with the bundling process?

**Comment by shilman** [comment]
@Jordan-Eckowitz Doesn't it work with `http-server`?

**Comment by shilman** [comment]
Ok, I explained why `serve` is broken. Maybe your server also needs to be configured to serve the requested path and not rewrite it? If this is common I'd consider reworking storybook to support `/iframe` as well, but it's worked this way for years and is used by a zillion teams, so I don't think this is standard.

**Comment by Jordan-Eckowitz** [comment]
> Ok, I explained why `serve` is broken. Maybe your server also needs to be configured to serve the requested path and not rewrite it? If this is common I'd consider reworking storybook to support `/iframe` as well, but it's worked this way for years and is used by a zillion teams, so I don't think this is standard.

Okay, I can look into making it work as is. I’m using a very generic deployment method. It’s AWS S3 static hosting via AWS Amplify. So I’d imagine others will run into the same issue though.

**Comment by shilman** [comment]
Hmm maybe someone else can weigh in on this? @ndelangen @tmeasday  thoughts? I don't think anything has changed on our side.

**Comment by tmeasday** [comment]
@Jordan-Eckowitz what is the error you are getting in the browser console above (I assume there is one)?

**Comment by lawnchamp** [comment]
I put storybook on an almost brand new project and I don't get any console or network error https://chess-timer-storybook.netlify.app/

here is the branch where I put the storybook6 upgrade https://github.com/lawnchamp/chesstimer/tree/storybook-upgrade. On storybook 5 i didn't have issues

**Comment by tmeasday** [comment]
@lawnchamp I think your issue is a different one, that I recall seeing before. Perhaps if you search for it there is a workaround or a fix?

**Comment by lawnchamp** [comment]
@tmeasday oh sorry you are right, my issue is related to this https://github.com/storybookjs/storybook/issues/12394. I mixed these two

**Comment by Jordan-Eckowitz** [comment]
@shilman I resolved the problem. It was similar to the `serve` issue you pointed out in that it was related to the `iframe`. I created a generic rule on my backend to catch all `iframe.html` (as well as other) requests and redirect to `index.html`. 

Posted below for future reference to anyone experiencing deployment issues with AWS Amplify / S3 static deployment. 

`SOURCE ADDRESS: </^[^.]+$|\.(?!(html|css|gif|ico|jpg|js|png|txt|svg|woff|ttf)$)([^.]+$)/>`

<img width="1440" alt="Screen Shot 2020-09-29 at 4 37 03 PM" src="https://user-images.githubusercontent.com/19767538/94613689-fc753880-0272-11eb-8eac-0c3767cc96ad.png">

**Comment by shilman** [comment]
Glad to hear you got it sorted @Jordan-Eckowitz 🚀

**Comment by lefebvrecharlie** [comment]
Hi, you can just remove "-s" option on your serve request.

Use : serve [build-folder]

**Comment by callain** [comment]
It is also possible to create a serve.json config file in your public folder and configure rewrites or redirects like this https://github.com/vercel/serve-handler#redirects-array.

**Comment by shilman** [comment]
whoa @lefebvrecharlie 🤯

**Comment by lallenfrancisl** [comment]
> @shilman I resolved the problem. It was similar to the `serve` issue you pointed out in that it was related to the `iframe`. I created a generic rule on my backend to catch all `iframe.html` (as well as other) requests and redirect to `index.html`.
> 
> Posted below for future reference to anyone experiencing deployment issues with AWS Amplify / S3 static deployment.
> 
> `SOURCE ADDRESS: </^[^.]+$|\.(?!(html|css|gif|ico|jpg|js|png|txt|svg|woff|ttf)$)([^.]+$)/>`
> 
> <img alt="Screen Shot 2020-09-29 at 4 37 03 PM" width="1440" src="https://user-images.githubusercontent.com/19767538/94613689-fc753880-0272-11eb-8eac-0c3767cc96ad.png">

There should be another rule which redirects requests to /iframe.html. So the other rule needed is
`Source: /iframe.html` `Target: /iframe.html`

**Comment by Jordan-Eckowitz** [comment]
@lallenfrancisl this fixed it for me - thanks for the input! For anybody else here's my screenshot of Amplify rules. I used `404 redirect` to get it working. 

![image](https://user-images.githubusercontent.com/19767538/147586264-19c33a7f-a132-429d-8975-990986f8e388.png)

**Comment by mswezey23** [comment]
This worked for me:

`SOURCE ADDRESS: </^[^.]+$|\.(?!(html|css|gif|ico|jpg|js|png|txt|svg|woff|ttf)$)([^.]+$)/>` redirects to `/index.html` status: `200 (rewrite)`

So far, I haven't needed to include the iframe rule. I'll monitor and report back.

**Comment by seb-lean** [comment]
fwiw this is still an issue for people deploying via AWS.
