### ISSUE TITLE
Unable to run stroybook due to documentation resolve issue in Angular library project

### ISSUE THREAD

**Issue by MukeshJ2506** [storybookjs/storybook#12543]
**Describe the bug**
Trying to set up an angular library project for reusable components. I cannot seem to run storybook after npx @storybook/cli init and also map the tsconfig to  "extends": "../tsconfig.json",

**To Reproduce**

1. run `npm run storybook`

**Expected behavior**
Launch storybook at http://localhost:6006/ 

**Screenshots**

info @storybook/angular v6.0.21
info
info => Loading presets
info => Loading presets
info => Loading config/preview file in "./.storybook".
info => Loading config/preview file in "./.storybook".
info => Adding stories defined in ".storybook\main.js".
info => Found custom tsconfig.json
info => Using angular project 'button' for configuring Storybook.
info => Loading angular-cli config.
info => Get angular-cli webpack config.
info => Using default Webpack setup.
Starting type checking service...
webpack built e15d142bce9b74beb576 in 7664ms
× ｢wdm｣: Hash: e15d142bce9b74beb576
Version: webpack 4.44.1
Time: 7664ms
Built at: 09/22/2020 6:39:44 PM
                                          Asset      Size        Chunks                                Chunk Names
                                    iframe.html  2.97 KiB                [emitted]
            main.e15d142bce9b74beb576.bundle.js   139 KiB          main  [emitted] [immutable]         main
        main.e15d142bce9b74beb576.bundle.js.map  65.2 KiB          main  [emitted] [dev]               main
    runtime~main.e15d142bce9b74beb576.bundle.js  33.5 KiB  runtime~main  [emitted] [immutable]         runtime~main
runtime~main.e15d142bce9b74beb576.bundle.js.map  34.7 KiB  runtime~main  [emitted] [dev]               runtime~main
        static/media/code-brackets.2e1112d7.svg  1.42 KiB                [emitted]
               static/media/colors.a4bd0486.svg  8.31 KiB                [emitted]
             static/media/comments.a3859089.svg  1.49 KiB                [emitted]
            static/media/direction.b770f9af.svg  1.25 KiB                [emitted]
                 static/media/flow.edad2ac1.svg  1.36 KiB                [emitted]
               static/media/plugin.d494b228.svg  2.12 KiB                [emitted]
                 static/media/repo.6d496322.svg   1.6 KiB                [emitted]
             static/media/stackalt.dba9fbb3.svg  2.49 KiB                [emitted]
    vendors~main.e15d142bce9b74beb576.bundle.js  5.28 MiB  vendors~main  [emitted] [immutable]  [big]  vendors~main
vendors~main.e15d142bce9b74beb576.bundle.js.map   5.3 MiB  vendors~main  [emitted] [dev]               vendors~main
Entrypoint main [big] = runtime~main.e15d142bce9b74beb576.bundle.js runtime~main.e15d142bce9b74beb576.bundle.js.map vendors~main.e15d142bce9b74beb576.bundle.js vendors~main.e15d142bce9b74beb576.bundle.js.map main.e15d142bce9b74beb576.bundle.js main.e15d142bce9b74beb576.bundle.js.map
[0] multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/storybook-init-framework-entry.js ./node_modules/@storybook/addon-docs/dist/frameworks/common/config.js-generated-other-entry.js ./node_modules/@storybook/addon-docs/dist/frameworks/angular/config.js-generated-other-entry.js ./node_modules/@storybook/addon-links/dist/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-actions/dist/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-actions/dist/preset/addArgs.js-generated-other-entry.js ./node_modules/@storybook/addon-backgrounds/dist/preset/defaultParameters.js-generated-other-entry.js ./.storybook/preview.js-generated-config-entry.js ./.storybook/generated-stories-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined 160 bytes {main} [built]
[./.storybook/generated-stories-entry.js] 436 bytes {main} [built]
[./.storybook/preview.js] 213 bytes {main} [built]
[./.storybook/preview.js-generated-config-entry.js] 2.87 KiB {main} [built]
[./.storybook/storybook-init-framework-entry.js] 28 bytes {main} [built]
[./node_modules/@storybook/addon-actions/dist/preset/addArgs.js] 2.41 KiB {vendors~main} [built]
[./node_modules/@storybook/addon-actions/dist/preset/addArgs.js-generated-other-entry.js] 2.29 KiB {vendors~main} [built]
[./node_modules/@storybook/addon-actions/dist/preset/addDecorator.js-generated-other-entry.js] 2.29 KiB {vendors~main} [built]
[./node_modules/@storybook/addon-backgrounds/dist/preset/defaultParameters.js-generated-other-entry.js] 2.3 KiB {vendors~main} [built]
[./node_modules/@storybook/addon-docs/dist/frameworks/angular/config.js-generated-other-entry.js] 2.3 KiB {vendors~main} [built]
[./node_modules/@storybook/addon-docs/dist/frameworks/common/config.js-generated-other-entry.js] 2.29 KiB {vendors~main} [built]
[./node_modules/@storybook/addon-links/dist/preset/addDecorator.js-generated-other-entry.js] 2.29 KiB {vendors~main} [built]
[./node_modules/@storybook/core/dist/server/common/polyfills.js] 120 bytes {vendors~main} [built]
[./node_modules/@storybook/core/dist/server/preview/globals.js] 93 bytes {vendors~main} [built]
[./node_modules/webpack-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined] (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined 7.68 KiB {vendors~main} [built]
    + 680 hidden modules

ERROR in ./.storybook/preview.js
Module not found: Error: Can't resolve '../documentation.json' in 'D:\New folder\work\components\carestack-components\.storybook'
 @ ./.storybook/preview.js 2:0-44 3:16-23
 @ ./.storybook/preview.js-generated-config-entry.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/storybook-init-framework-entry.js ./node_modules/@storybook/addon-docs/dist/frameworks/common/config.js-generated-other-entry.js ./node_modules/@storybook/addon-docs/dist/frameworks/angular/config.js-generated-other-entry.js ./node_modules/@storybook/addon-links/dist/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-actions/dist/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-actions/dist/preset/addArgs.js-generated-other-entry.js ./node_modules/@storybook/addon-backgrounds/dist/preset/defaultParameters.js-generated-other-entry.js ./.storybook/preview.js-generated-config-entry.js ./.storybook/generated-stories-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined
Child HtmlWebpackCompiler:
                          Asset      Size               Chunks  Chunk Names
    __child-HtmlWebpackPlugin_0  6.35 KiB  HtmlWebpackPlugin_0  HtmlWebpackPlugin_0
    Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
    [./node_modules/html-webpack-plugin/lib/loader.js!./node_modules/@storybook/core/dist/server/templates/index.ejs] 2.14 KiB {HtmlWebpackPlugin_0} [built]

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

**Code snippets**
NA

**System:**

Angular :
  "@angular/animations": "~10.1.2",
    "@angular/common": "~10.1.2",
    "@angular/compiler": "~10.1.2",
    "@angular/core": "~10.1.2",
    "@angular/forms": "~10.1.2",
    "@angular/platform-browser": "~10.1.2",
    "@angular/platform-browser-dynamic": "~10.1.2",
    "@angular/router": "~10.1.2",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.2"

  System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
  Binaries:
    Node: 12.16.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 85.0.4183.102
    Edge: Spartan (44.18362.449.0)
  npmPackages:
    @storybook/addon-actions: ^6.0.21 => 6.0.21
    @storybook/addon-essentials: ^6.0.21 => 6.0.21
    @storybook/addon-links: ^6.0.21 => 6.0.21
    @storybook/addon-storysource: ^6.0.21 => 6.0.21
    @storybook/angular: ^6.0.21 => 6.0.21

**Additional context**
Trying to set up a library project and not an application project

**Comment by Marklb** [comment]
Are you generating the `documentation.json` file?

If your `package.json` runs `compdoc` before `storybook` there should be a `documentation.json` file. From the error, it looks like you are not running `compdoc`.

The following is an example of `package.json` Storybook scripts that generate the `documentation.json` before running Storybook.
```json
{
	...,
	"scripts": {
		...,
		"docs:json": "compodoc -p ./tsconfig.json -e json -d .",
		"storybook": "npm run docs:json && start-storybook -p 6006",
		"build-storybook": "npm run docs:json && build-storybook"
	},
	...
}
```

If that isn't the problem, it must be your configuration, which would require more information. A sample repo would probably make it easy to quickly spot that problem.

**Comment by MukeshJ2506** [comment]
@Marklb Thank you for your response. Yeah the package scripts are the same. All I have done is the following
`ng new project-name --create-application=false
ng g lib component-test -p my-prefix
npx @storybook/cli init`

I have updated the storybook tsconfig.json as well to extend the workspace config.

I can also see that compodoc generation runs just fine if i use `npx compodoc -p tsconfig.json -s --port=9000`. Please let me know if you require any further information.

**Comment by MukeshJ2506** [comment]
Sorry for all the trouble, thank you for the help so far. Closing this issue since the culprit is my antivirus. For some reason my antivirus blocks ` npm run docs:json` but not `npm run compodoc -p ./tsconfig.json -e json -d .`
