### ISSUE TITLE
Cannot run later versions of React

### ISSUE THREAD

**Issue by dburles** [storybookjs/storybook#12548]
We've been running React experimental for some time in Storybook 5 with no problem. However on upgrading found that both 6 and 6.1 alpha dump an "Invalid hook call" warning. 

Here's a very simple reproduction with nothing more than the base Storybook installation on React experimental. https://github.com/dburles/sb-react-bug

Related: https://github.com/storybookjs/storybook/issues/11904

```
Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
```

**Comment by tmeasday** [comment]
So it looks to me like the issue here is that some of our manager-side packages are using the experimental React (the "user react") rather than `react@16.13.1` that most of the `@storybook/X` packages use in the UI.

**Comment by ndelangen** [comment]
I think we do alias react in the manager yes, but things might get messed up in the preview with addon-docs.

Also DLL might be a problem.

**Comment by tmeasday** [comment]
It looks like the stack trace is from the manager though, right?

**Comment by ndelangen** [comment]
I haven't taken a look at the stacktrace yet @tmeasday

**Comment by shilman** [comment]
Closing as dupe to #12408
