### ISSUE TITLE
Cannot read property 'debug' of undefined when upgrading from v5.3.x to v6.0.21

### ISSUE THREAD

**Issue by RichardPK** [storybookjs/storybook#12541]
Same bug as detailed here -> https://github.com/storybookjs/storybook/issues/11116

**Describe the bug**
Hi all - did you find a solution for [this](https://github.com/storybookjs/storybook/issues/11116)? Having exactly the same problem with `6.0.21` throwing this error when changing components, or components' knobs:

`@storybook/client-logger/dist/index.js` 
`index.js:47 TypeError: Cannot read property 'debug' of undefined`

Our repo uses Storybook quite extensively, so can't provide a neat snippet. Let me know if you need any specific pieces of code though, the repo is https://github.com/bbc/psammead and our v6 migration PR is (in progress) here https://github.com/bbc/psammead/pull/3728

**To Reproduce**

(Upgrade from `v5.3.21` > `v6.0.21`, run storybook, then:)

1. Go to **any component**
2. Click on **any other component, or any knob**
3. No re-rendering of component, and above error logged in console.

**Expected behavior**
New component to render / existing component to rerender with 

**Screenshots**
<img width="417" alt="Screenshot 2020-09-22 at 12 16 46" src="https://user-images.githubusercontent.com/9042672/93877033-b434a400-fccf-11ea-801b-5dde56937560.png">

**System:**
Environment Info:

  System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 12.18.4 - ~/.nvm/versions/node/v12.18.4/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.4/bin/npm
  Browsers:
    Chrome: 85.0.4183.102
    Firefox: 80.0.1
    Safari: 13.0.3
  npmPackages:
    @storybook/addon-a11y: ^6.0.21 => 6.0.21 
    @storybook/addon-actions: ^6.0.21 => 6.0.21 
    @storybook/addon-knobs: ^6.0.21 => 6.0.21 
    @storybook/addon-notes: ^5.3.21 => 5.3.21 
    @storybook/addon-viewport: ^6.0.21 => 6.0.21 
    @storybook/react: ^6.0.21 => 6.0.21 
    @storybook/theming: ^6.0.21 => 6.0.21

**Comment by shilman** [comment]
Try getting rid of the notes addon

**Comment by RichardPK** [comment]
Thanks for the reply @shilman - I've removed the `@storybook/addon-notes/register` import as well as removing `"@storybook/addon-notes": "^5.3.21"` from package.json & then rebuilt package-lock/node modules

sb@next info is confirming it's gone:

```
  npmPackages:
    @storybook/addon-a11y: ^6.0.21 => 6.0.21 
    @storybook/addon-actions: ^6.0.21 => 6.0.21 
    @storybook/addon-knobs: ^6.0.21 => 6.0.21 
    @storybook/addon-viewport: ^6.0.21 => 6.0.21 
    @storybook/react: ^6.0.21 => 6.0.21 
    @storybook/theming: ^6.0.21 => 6.0.21 
```

I've also experimented with removing imports of `.md` files in a few story components...

...and the error persists.
