### ISSUE TITLE
Storybook Docs: Add new action button to action bar in Docs view?

### ISSUE THREAD

**Issue by smurrayatwork** [storybookjs/storybook#12552]
Is there a recipe or example for how someone could add a new ActionButton to the ActionBar when viewing a story's docs? I'd like to add a button that works similar to the `Show code` button, but for hiding/showing custom content.

**Comment by frassinier** [comment]
@smurrayatwork Do you mean like this? 

https://storybookjs.netlify.app/official-storybook/?path=/story/docs-preview--with-additional-actions

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if this is still relevant in SB 7.x.
