### ISSUE TITLE
addon-storyshots-puppeteer: per story beforeSnapshot function

### ISSUE THREAD

**Issue by danielo515** [storybookjs/storybook#12556]
**Is your feature request related to a problem? Please describe.**
Storyshots-puppeteer is amazing in the sense that I get free test for almost all my components, that is awesome.
However, sometimes I add artificial options to some of my components so I can test them properly. Forcing states like `:hover` or opening modals that are not meant to be controlled can be tricky.

**Describe the solution you'd like**
I would love to be able to define a function per story so I can trigger some states before the snapshot is taken, so I don't need to add unneeded features to my components.

**Describe alternatives you've considered**
Right now, the only option I see fit is to define my own API using the current beforeSnapshot global function

**Are you able to assist bring the feature to reality?**
I can assist, but don't have time to code a solution

**Comment by ndelangen** [comment]
The future of storyshots is the test-runner:
https://storybook.js.org/docs/react/writing-tests/test-runner#page-top

And use the play function for expectations:
https://storybook.js.org/docs/react/writing-stories/play-function#page-top

We will not be making any improvement / changes to storyshots.
