### ISSUE TITLE
Reference to 'component' missing from arguments to makeDecorator wrapper

### ISSUE THREAD

**Issue by olliejm** [storybookjs/storybook#12569]
**Describe the bug**
When creating a custom decorator, a reference to component was expected on `context.parameters.component` of the context argument to `wrapper` function of `makeDecorator`. This reference is missing.

**To Reproduce**

1. Export a decorator like https://github.com/open-wc/open-wc/blob/master/packages/storybook-addon-web-components-knobs/src/withWebComponentsKnobs.js#L167
2. Decorate a story with it like https://github.com/open-wc/open-wc/blob/master/packages/demoing-storybook/demo/stories/withWebComponentsKnobs.stories.mdx#withwebcomponentsknobs
3. Place a breakpoint in the decorator and notice that the expected parameter is missing, so the function exits without doing anything after the check

**Expected behavior**
That the component would be available at the expected location, or at a different location on one of the arguments to the wrapper function.

**System:**
```bash
Environment Info:

  System:
    OS: Windows 10 10.0.17763
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
  Binaries:
    Node: 12.18.4 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 85.0.4183.121
  npmPackages:
    @storybook/addon-actions: ^6.0.21 => 6.0.21
    @storybook/addon-controls: ^6.0.21 => 6.0.21
    @storybook/addon-essentials: ^6.0.21 => 6.0.21
    @storybook/addon-knobs: ^6.0.21 => 6.0.21
    @storybook/addon-links: ^6.0.21 => 6.0.21
    @storybook/addon-storysource: ^6.0.21 => 6.0.21
    @storybook/addons: ^6.0.21 => 6.0.21
    @storybook/web-components: ^6.0.21 => 6.0.21
```

**Additional context**
The custom decorator from the code linked above is from a repo that uses version 5 of Storybook. I'm looking to incorporate the functionality of this custom decorator into my own Storybook. I notice however that the property the decorator relies on is missing - my first guess is this is a change in version 6 of Storybook. As I'm modifying the code anyway, I would simply alter the function, but on inspection I do not see what I assume `component` should be (a reference to the web component element) available anywhere on any of the arguments to the function. Is this expected behaviour in Storybook 6, and is it possible any longer to achieve what I am looking for?

**Comment by shilman** [comment]
@tmeasday could this be a bug introduced by parameter normalization?

**Comment by tmeasday** [comment]
@shilman I wouldn't have guessed so, it is pretty common for decorators to use component-level parameters right?

**Comment by tmeasday** [comment]
This issue seems out of date, closing.
