### ISSUE TITLE
MDX story shows message "This story is not configured to handle controls."

### ISSUE THREAD

**Issue by ullmark** [storybookjs/storybook#12560]
**Describe the bug**
We use "MDX"-style of writing stories, we've created a decorator that takes input from args to setup redux. The component inside doesn't use args but takes all props from redux. It seems a message is always shown stating that the "story isn't configured to handle controls."

**Code snippets**
Created a repro repo: 
https://github.com/ullmark/storybook-mdx-args

It has a VERY simple story structured with decorator and story similar to how we use it (except we have a real component and redux ofc). A "MDX-args-issue" story exists. 

**Screenshot:**
![Example___MDX_-_Args_-_issue_-_issue_⋅_Storybook](https://user-images.githubusercontent.com/48222/94113711-99853b00-fe47-11ea-8d34-3ca7ec3f7046.jpg)

**System:**
```
Environment Info:

  System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 14.4.0 - ~/.nvm/versions/node/v14.4.0/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v14.4.0/bin/npm
  Browsers:
    Chrome: 85.0.4183.121
    Firefox: 79.0
    Safari: 14.0
  npmPackages:
    @storybook/addon-actions: ^6.0.21 => 6.0.21
    @storybook/addon-essentials: ^6.0.21 => 6.0.21
    @storybook/addon-links: ^6.0.21 => 6.0.21
    @storybook/react: ^6.0.21 => 6.0.21
```

**Comment by shilman** [comment]
@ullmark Thanks for the issue and the reproduction! The error message is not a bug. Let me try to explain.

Here's your MDX file:

```jsx
  <Story 
    name="Issue"
    decorators={[(Story, { args }) => (<div>{args.message}{Story()}</div>)]} 
    args={{message: "Hello World"}} 
    argTypes={{message: { control: "text" }}}>
    <h1>Hello</h1>
  </Story>
```

If we strip out all the metadata, this is what that story looks like in CSF:

```
export const Issue = () => <h1>Hello</h1>;
Issue.decorators = ...;
...
```

Notice that this function is not configured to receive args as its input, so when you edit the controls, nothing will happen.

I'd expect the following not to issue a warning:

```jsx
  <Story 
    name="Issue"
    decorators={[(Story, { args }) => (<div>{args.message}{Story()}</div>)]} 
    args={{message: "Hello World"}} 
    argTypes={{message: { control: "text" }}}>
    {(args) => <h1>Hello</h1>}
  </Story>
```

I suspect what you actually want is:

```jsx
  <Story 
    name="Issue"
    args={{message: "Hello World"}} 
    argTypes={{message: { control: "text" }}}>
    {(args) => <h1>{args.message}</h1>}
  </Story>
```

Or, if all your stories receive the same argTypes:

```jsx
  <Meta title="Example/MDX-Args-issue"  argTypes={{message: { control: "text" }}} />

  <Story name="Issue" args={{ message: "Hello World" }}>
    {(args) => <h1>{args.message}</h1>}
  </Story>
```

Hope that helps!

**Comment by shilman** [comment]
There's also this: https://storybook.js.org/docs/react/essentials/controls#hide-nocontrols-warning

**Comment by ullmark** [comment]
Ok, I'm officially blind. 🙈  Had missed that!
Thanks! I'll close the ticket!
