### ISSUE TITLE
Refactor: Split out docs-loader from source-loader

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#12561]
Currently, `source-loader` is used by both `addon-storysource` and `addon-docs`. It supports both `storiesOf` and `CSF` stories.

Until 6.0 the `source-loader` and `CSF` cases were quite similar. Late in the release, these use cases diverged a bit for performance's sake (see . Now, the default `addon-docs` configuration (not required, but recommended) and the required `addon-storysource` configuration don't match.

There are a number of related issues resulting from this mess, including (but not limited to): #12208 #8055 #12065 #12557

To address this, I propose:
- [ ] Splitting out a separate `docs-loader` that ONLY supports CSF.
- [ ] Deprecating `source-loader`.
- [ ] Making a non-deprecated copy of source-loader that lives inside `addon-storysource`.

A cleanroom `docs-loader` would be substantially simpler because it doesn't need to deal with all the `storiesOf` complexity. From there we could easily add stuff like:
- [ ] Descriptions per story #8527

**Comment by shilman** [comment]
More context on the problem: https://github.com/storybookjs/storybook/blob/next/addons/storysource/README.md#displaying-full-source

In a nutshell:
- Storysource uses the full source of the file and a collection of offsets into that source to show highlights
- Docs is able to use the same data as Storysource, but loads much more quickly if the source has already been pre-extracted as small snippets that are annotated onto the stories individually.

We shipped the optimized version as the default in 6.0 because we were pressed for time and we were doing everything we could to make performance acceptable before the release.

**Comment by yuri-scarbaci-lenio** [comment]
Just to add my 2 cents,

Would be nice if we could get a couple of options with the source-code when configuring the parameters globally (let's say in preview.js)

Maybe adding the possibility for `parameters.storySource.source` to either be a string or a function that receives the `finalFormattedSource, rawSource` as parameters so going forward people can configure their own source code easly and/or add their own preamble/post-comments/formatting

if `rawSource` going forward would ALWAYS be the result of ONLY reading the content of the story as a string this could help heavy-customization-user to get a more stable implementation and worry a lot less about breaking changes of configurations when updating/upgrading the versions.

In our specific case that would be more than welcome and more than enough (and to be honest would also be our prefeered way to handle it)

**Comment by yuri-scarbaci-lenio** [comment]
Stale bot just doesn't like this issue and related issues uh? :)

**Comment by shilman** [comment]
Fixed in 7.0 and released as @storybook/csf-plugin
