### ISSUE TITLE
Storybook Control unexpected behaviour for autogen @Input

### ISSUE THREAD

**Issue by scharph** [storybookjs/storybook#12567]
**Describe the bug**

Storybook Control shows dash (**-**) instead of default value.
See screenshots ( min, retract)
for max its ok!
What's the reason?

```
@Input()
  public min = 0;

  @Input()
  public max = 100;
.
.
.
```

**Expected behavior**
default value is shown

**Screenshots**

![storybook](https://user-images.githubusercontent.com/15950114/94143658-70c56b80-fe70-11ea-8239-4c8939fbfe30.png)

**Code snippets**

```
const template: Story = (args) => ({
  component: RetractSliderComponent,
  props: args
})

export const configurable = template.bind({});
configurable.storyName = 'configurable';
```

**System:**
Environment Info:

  System:
    OS: Linux 4.19 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (4) x64 Intel(R) Core(TM) i5-7500T CPU @ 2.70GHz
  Binaries:
    Node: 12.18.4 - /usr/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 6.14.6 - /usr/bin/npm
  npmPackages:
    @storybook/addon-essentials: ^6.0.21 => 6.0.21 
    @storybook/addon-knobs: ^6.0.21 => 6.0.21 
    @storybook/addon-links: ^6.0.21 => 6.0.21 
    @storybook/addon-storysource: ^6.0.21 => 6.0.21 
    @storybook/angular: ^6.0.21 => 6.0.21

**Comment by shilman** [comment]
Looks like a bug where 0 is a falsey value and something in the stack disables the control because of that. Out of curiosity if you hack `min` to be `1` does the controls show up? We'll try to get the bug fixed soon.

**Comment by scharph** [comment]
Yes, it shows up!
