### ISSUE TITLE
Missing configuration files doesn't cause build-storybook to exit with 1

### ISSUE THREAD

**Issue by te-online** [storybookjs/storybook#12564]
**Describe the bug**
When running `build-storybook` without a `.storybook` folder present, a `UnhandledPromiseRejectionWarning` is thrown and the build fails. However, the call to `build-storybook` returns a 0 exit code. Running in a CI step this won't fail the build although the build has indeed failed at the first step.

**To Reproduce**

1. Install storybook to a project, use node version v12.18.1 or similar
2. (Possibly accidentally) remove the `.storybook` folder
2. Run `build-storybook`
3. Run `echo $?`
4. The result is `0`

**Expected behavior**
The process exits with code `1`

**System:**
```
System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
  Binaries:
    Node: 12.18.1 - ~/.nvm/versions/node/v12.18.1/bin/node
    Yarn: 1.6.0 - ~/.yarn/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v12.18.1/bin/npm
  Browsers:
    Chrome: 85.0.4183.121
    Firefox: 80.0.1
    Safari: 14.0
  npmPackages:
    @storybook/addon-actions: 6.0.21 => 6.0.21 
    @storybook/addon-knobs: 6.0.21 => 6.0.21 
    @storybook/addon-links: 6.0.21 => 6.0.21 
    @storybook/react: 6.0.21 => 6.0.21 
```

**Additional context**
If you configure node to throw on `UnhandledPromiseRejectionWarning` it works as expected. Try `node --unhandled-rejections=strict ./node_modules/.bin/build-storybook` and then `echo $?` -> result is `1`, as expected.

A possible solution could be to add a `process.exit(1)` or similare below the place where following warning is thrown: `Error: No configuration files have been found in your configDir...`

**Comment by shilman** [comment]
closing as dupe to #11918

**Comment by te-online** [comment]
Thanks for referencing! Github Search failed on me again 😞
