### ISSUE TITLE
I want to fix the bug in laravel and vue.

### ISSUE THREAD

**Issue by shevchenko-web** [storybookjs/storybook#12574]
Dear Clients.

![image](https://user-images.githubusercontent.com/70866718/94201264-bcbaf380-fef6-11ea-95a3-862dbc29ae55.png)

**Comment by darleendenno** [comment]
@shevchenko-web are you still experiencing this issue with the latest versions [@storybook/vue](https://www.npmjs.com/package/@storybook/vue)? You are welcome to submit a PR to fix this issue 😄
