### ISSUE TITLE
Doc code preview "No display name"

### ISSUE THREAD

**Issue by fcisio** [storybookjs/storybook#12596]
**Describe the bug**
The Doc code preview does not display the component name correctly.

**To Reproduce**
1. Create a component with emotion js "Styled"
2. Create a component with "Theme UI"
3. Use those components in stories
4. Check the doc code preview

**Expected behavior**
The component name should display normally

**Screenshots**
![Shot_0](https://user-images.githubusercontent.com/46095852/94451842-e1280180-017c-11eb-9b25-4d5c74cc3ce3.jpg)
![Shot_0 1](https://user-images.githubusercontent.com/46095852/94451854-e5ecb580-017c-11eb-88ef-39f76728e430.jpg)

**Code snippets**
![Shot_0 2](https://user-images.githubusercontent.com/46095852/94451951-00bf2a00-017d-11eb-96f3-5c8f4081306b.jpg)

**Comment by shilman** [comment]
@fcisio Is this still broken in the latest alpha? We made some improvements in #12638

**Comment by shilman** [comment]
@andezzat any chance you can take a look at this as follow-on to your "exotic components" fix? 🙏

**Comment by fcisio** [comment]
Hi @shilman 
The `[object Object]` seems to be fixed. But still having issues with "No Display Name".

I found a quick fix for now: 
```jsx
Burger.displayName = "Burger"
const Template = (args) => <Burger {...args} />
```

**Comment by andezzat** [comment]
The component not having a displayName doesn't sound like a storybook issue.
The `Burger` component is the product of a styled component, can you confirm how it was created?

**Comment by shilman** [comment]
@andezzat is there any way we can detect that it's a styled component and automatically extract the display name from the wrapped component?

**Comment by zeckdude** [comment]
@shilman I'm experiencing a similar issue, but only when I use a decorator.

Without a decorator, I get this:
```js
<Tooltip title="Hi there!">
  <Button size="small">
    Open based on hover
  </Button>
</Tooltip>
```

With the decorator, I get this:
```js
<div
  style={{
    margin: '3em'
  }}
>
  <No Display Name />
</div>
```

Here's my full story:
```js
export const Minimal = args => {
  return (
    <Tooltip title="Hi there!" placement="top" {...args}>
      <Button type="primary" size="small">
        Open based on hover
      </Button>
    </Tooltip>
  );
};
Minimal.decorators = [
  Story => (
    <div style={{ margin: '3em' }}>
      <Story />
    </div>
  ),
];
```

I doubt it's an issue with the `Tooltip` component, since it works fine without the decorator. Please let me know if you think this is related or if I should create a new issue.

**Comment by gptt916** [comment]
Exact same issue as @zeckdude described, issue only shows when I'm using a decorator.

My story looks like this:

```js
export default {
  title: 'CheckboxTree',
  component: CheckboxTree,
  decorators: [
    withKnobs,
    (Story) => <div style={{ maxWidth: '256px' }}><Story/></div>
  ],
};

export const Valid = (args) => <CheckboxTree {...args} />

Valid.args = {
  nodes: validData
}
```

**Comment by shilman** [comment]
What happens if you use `{Story()}` instead of `<Story />`?

**Comment by gptt916** [comment]
@shilman It works that way, thank you! 

Perhaps the documentation needs to be updated here: https://storybook.js.org/docs/react/writing-stories/decorators

**Comment by shilman** [comment]
cc @tmeasday @jonniebigodes not sure what to do about this 🤦

**Comment by tmeasday** [comment]
Oh man.

**Comment by Naxos84** [comment]
I can confirm that `{Story()}` fixes this issue when using the decorator in Storybook 6.0.27.

I guess that you don't have a solution for that by now?

**Comment by aaronnuu** [comment]
When I use the `{Story()}` solution to fix the `<No display name />` issue then all of my hooks within the story stop working (I assume because my story component is now not being called by `React.createElement`)

**Comment by shilman** [comment]
I will fix this as part of #12022, and the recommendation will be to use `<Story />` for consistency's sake.

**Comment by andykenward** [comment]
This is happening on  `"@storybook/react": "6.3.2"` when using a decorator on an individual story. 
I am using TypeScript `4.3.4`.


```
// .storybook/main.js

module.exports = {
  stories: ["../src/**/*.stories.@(js|jsx|ts|tsx|mdx)"],
  addons: [
    "@storybook/addon-essentials",
    {
      name: "@storybook/preset-scss",
      options: {
        cssLoaderOptions: {
          modules: {
            localIdentName: CSS_MODULE_STORYBOOK_SCOPE_NAME
          }
        }
      }
    }
  ],
  typescript: {
    reactDocgen: "react-docgen-typescript"
  }
};
```

This
```
// component.stories.tsx

 decorators: [
    (Story) => (
      <StoryWrapperDefault>
        <Story />
      </StoryWrapperDefault>
    )
  ]
```
Output in show code docs.
```
<StoryWrapperDefault>
  <No Display Name />
</StoryWrapperDefault>
```

Changing the decorator to the above [fix](https://github.com/storybookjs/storybook/issues/12596#issuecomment-723440097)

```
// Component.stories.tsx

decorators: [(Story) => <StoryWrapperDefault>{Story()}</StoryWrapperDefault>]
```

Output in show code docs
```
<StoryWrapperDefault>
  <VoiceSearch
    onClose={() => {}}
    onSubmit={function noRefCheck() {}}
    open
  />
</StoryWrapperDefault>
```

**Comment by shilman** [comment]
@andykenward if you want to get rid of the decorator you can set the `excludeDecorators` parameter #14652

```
        docs: {
          source: {
            excludeDecorators: true,
          },
        },
      },
```

@jonniebigodes we need to rework the doc blocks documentation soon 🙈

**Comment by jonniebigodes** [comment]
@shilman indeed we do, I'll follow up with you so that we can coordinate how best to document this and move on from there. Sounds good?

**Comment by penx** [comment]
> I will try to fix this as part of #12022, and the recommendation will be to use <Story /> for consistency's sake.

@shilman #12022 is now closed but I still get this issue. It's great that I can use `{Story()}` but I had to come across this issue before I found the workaround. Something in the docs would be great if you don't think this can be fixed?

**Comment by dechamp** [comment]
> What happens if you use `{Story()}` instead of `<Story />`?

Why does this work?

**Comment by dechamp** [comment]
> @andykenward if you want to get rid of the decorator you can set the `excludeDecorators` parameter #14652
> 
> ```
>         docs: {
>           source: {
>             excludeDecorators: true,
>           },
>         },
>       },
> ```
> 
> @jonniebigodes we need to rework the doc blocks documentation soon 🙈

You are so awesome! Thank you! I've be scouring the web for an answer and just found this while i happened to be on the main issue of this thread, thank you!!!!

**Comment by jinyoung4478** [comment]
> What happens if you use `{Story()}` instead of `<Story />`?

Thank you for your help! 😊

**Comment by fishkes** [comment]
> docs: {
>           source: {
>             excludeDecorators: true,
>           },
>         },

Thanks @shilman! for anyone wandering where to add it, you can put it in ./storybook/preview.js

**Comment by bradlocking** [comment]
> > What happens if you use `{Story()}` instead of `<Story />`?
> 
> Why does this work?

Can I also get an answer to this?

**Comment by amitmorade** [comment]
Hello, I am still facing the No-Display-name in place for component Names in storybook 8
