### ISSUE TITLE
Add default/initial property to argTypes control field

### ISSUE THREAD

**Issue by AndrewLeedham** [storybookjs/storybook#12607]
**Is your feature request related to a problem? Please describe**
Currently in order to provide a default value for a control you have to directly pass it as an arg, For example take the "range" type, if you do not pass an arg it displays as:
![image](https://user-images.githubusercontent.com/5557458/94543109-86a4a900-0241-11eb-9585-5fe4050548d2.png)
However if an actual component maps undefined to a default value of 0, you would therefore have to pass 0 in `args` explicitly to make it display as:
![image](https://user-images.githubusercontent.com/5557458/94543259-b9e73800-0241-11eb-8a33-49def46ba033.png)
The problem here is an arg is like passing an actual prop, therefore when using an addon like [storybook-addon-playroom](https://github.com/rbardini/storybook-addon-playroom) all the arg values are passed forward and you end up with a cluttered component as shown below:
![image](https://user-images.githubusercontent.com/5557458/94554128-88766880-0251-11eb-9eaf-6a2903f60a7f.png)

**Describe the solution you'd like**
Add a new field to `control` called default or initial, with the value to display but not to actually pass to the component.

**Describe alternatives you've considered**
I considered inferring the default value from the args table, but I can see that causing a bunch of issues, especially given `defaultValue.summary` can be just a description of the default.

**Are you able to assist to bring the feature to reality?**
Yes if we can nail down the functionality, I can give it a shot.

**Comment by shilman** [comment]
Seems highly related to https://github.com/storybookjs/storybook/issues/11510

Can we coordinate a fix that solves both issues at once @AndrewLeedham ? Would love to help figure this out.

**Comment by AndrewLeedham** [comment]
Actually thinking about this some more, `defaultProps` is a React thing, but storybook is built to run with a bunch of frameworks. So that approach is a little naive, perhaps looking at the `defaultValue` is the way to go?

**Comment by shilman** [comment]
Yup React-specific defaultProps get mapped into framework-independent defaultValues in args-land

**Comment by AndrewLeedham** [comment]
@shilman does doing a diff between args and defaultValues make sense then, perhaps on the update and reset client-api events?

**Comment by AndrewLeedham** [comment]
https://github.com/storybookjs/storybook/pull/13003 Partially fixed this in 6.1, however it is still not possible to provide storybook only defaults and exclude them from the source code. Perhaps a bit of a niche use case though.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
