### ISSUE TITLE
Broken link in docs (Writing docs/mdx)

### ISSUE THREAD

**Issue by domyen** [storybookjs/storybook#12611]
**Describe the bug**

This link is broken on [this docs page](https://storybook.js.org/docs/react/writing-docs/mdx#documentation-only-mdx) 

![image](https://user-images.githubusercontent.com/263385/94588960-a8f2f280-0252-11eb-961a-61eb0ee8e8b3.png)

**To Reproduce**

1. Go to https://storybook.js.org/docs/react/writing-docs/mdx#documentation-only-mdx
2. Scroll down
3. Click on the "CSF stories with MDX docs"

**Expected behavior**
That it links to https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/recipes.md#csf-stories-with-mdx-docs

**OR** that the CSF in MDX recipe is promoted into the official docs

**Comment by jonniebigodes** [comment]
@domyen i've just created a pull request that addresses your issue. I'll merge it shortly. 

Regarding this item:
> OR that the CSF in MDX recipe is promoted into the official docs

We could do better in the future. I'm inclined to create a Recipes page with some of the most used ones and with that start removing references from the READMEs and consolidate all of them in one place, avoiding further issues like this one. More than glad to discuss this further with you and anyone else that is onboard with the idea.

**Comment by jonniebigodes** [comment]
Closing this now as the pull request was merged. But like i've mentioned, would love to hear some thoughts on creating a recipes page.

**Comment by domyen** [comment]
A "recipes" page for common SB docs related issues makes sense to me.
