### ISSUE TITLE
Update axe-core version to 3.5 on v5+

### ISSUE THREAD

**Issue by thbt** [storybookjs/storybook#12616]
**Describe the bug**

Running storybook v5 with the a11y addon is breaking in old version of safari
See dequelabs/axe-core#1764

**Comment by shilman** [comment]
Try upgrading to 6.0

```
npx sb upgrade
```

[Full migration guide](https://medium.com/storybookjs/storybook-6-migration-guide-200346241bb5)

**Comment by thbt** [comment]
Hey @shilman, given the size of our codebase and that we use some specific wrapper around our stories files, the upgrade may not be trivial or straightforward. I created a PR to bump axe-core version (#10375) but it was only released with v6. Would it be possible to release it as a patch of v5.3?

**Comment by thbt** [comment]
Closing the issue since upgrading storybook has fixed it
