### ISSUE TITLE
Error: Can't resolve 'vue-docgen-loader' after upgrading to 6.0.22

### ISSUE THREAD

**Issue by scheinercc** [storybookjs/storybook#12617]
**Describe the bug**
After upgrading from 6.0.21 to 6.0.22 via `yarn upgrade-interactive` I am seeing two errors

No.1
```
ERROR in ./.storybook/preview.js
Module not found: Error: Can't resolve 'style-loader' in '/Users/...'
...
```

No.2 - per story:
```
ERROR in ./stories/[Srotyname].stories.js
Module not found: Error: Can't resolve 'vue-docgen-loader' in '/Users/...'
...
```

**To Reproduce**

1. Upgrading from 6.0.21 to 6.0.22
2. Stop the storybook instance
3. Start the storybook instance (`yarn storybook`)

**System**
Environment Info:

System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  Binaries:
    Node: 12.18.2 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
  Browsers:
    Chrome: 85.0.4183.121
    Firefox: 81.0
    Safari: 14.0
  npmPackages:
    @storybook/addon-actions: ^6.0.10 => 6.0.22
    @storybook/addon-docs: ^6.0.10 => 6.0.22
    @storybook/addon-knobs: ^6.0.17 => 6.0.22
    @storybook/addon-links: ^6.0.10 => 6.0.22
    @storybook/addon-storysource: ^6.0.10 => 6.0.22
    @storybook/addons: ^6.0.10 => 6.0.22
    @storybook/vue: ^6.0.10 => 6.0.22

**Comment by scheinercc** [comment]
Nope, but I just found out something else.

running `yarn upgrade-interactive` gave me this list:
![image](https://user-images.githubusercontent.com/817856/94692935-7b06ce80-0376-11eb-9e89-7f4b571b0b34.png)

after updating them all `yarn upgrade-interactive` output:
![image](https://user-images.githubusercontent.com/817856/94693020-91ad2580-0376-11eb-979a-832fa5eb8dbe.png)

But running `yarn upgrade` makes it work! It changed several additional dependencies:
- @types/express-serve-static-core: "4.17.12" => "4.17.13"
- @vue/babel-plugin-jsx: "1.0.0-rc.2" => "1.0.0-rc.3"
- klona: "2.0.3" => "2.0.4"
- mime-db: "1.44.0" => "1.45.0"
- node-forge: "0.9.0" => "0.10.0"
- selfsigned: "1.10.8" => "1.10.7"
- **vue-loader-v16**: "16.0.0-beta.7" => "16.0.0-beta.8"
- webpack-bundle-analyzer: "3.8.0" => "3.9.0"

That's kinda it. Maybe I missed one or two. I would have expected that these dependencies would get upgrade with `upgrade interactive` just as with `upgrade`. Any idea why they didn't?

**Comment by shilman** [comment]
That's probably a better question for the yarn team. We've had a lot of upgrade issues with both yarn and npm..
