### ISSUE TITLE
[addon-controls] select options object format is reversed

### ISSUE THREAD

**Issue by y-nk** [storybookjs/storybook#12613]
**Describe the bug**

**To Reproduce**

Build any story with addon-controls and :

```
argTypes: {
  prop: {
    control: 'select',
    options: { val1: 'Value 1', val2: 'Value 2' },
  }.
}
```

**Expected behavior**
The `<select>` should display a list of "Value 1, Value 2" and the story should receive "val1, val2" as arg.

**What is happening instead**
The `<select>`displays a list of "val1, val2" and the story receives "Value 1, Value 2" as arg.

**System**

```
Environment Info:

  npmPackages:
    @storybook/addon-a11y: ^6.1.0-alpha.17 => 6.1.0-alpha.17
    @storybook/addon-actions: ^6.1.0-alpha.17 => 6.1.0-alpha.17
    @storybook/addon-backgrounds: ^6.1.0-alpha.17 => 6.1.0-alpha.17
    @storybook/addon-controls: ^6.1.0-alpha.17 => 6.1.0-alpha.17
    @storybook/addon-storysource: ^6.1.0-alpha.17 => 6.1.0-alpha.17
    @storybook/addon-viewport: ^6.1.0-alpha.17 => 6.1.0-alpha.17
    @storybook/addons: ^6.1.0-alpha.17 => 6.1.0-alpha.17
    @storybook/client-api: ^6.1.0-alpha.17 => 6.1.0-alpha.17
    @storybook/react: ^6.1.0-alpha.17 => 6.1.0-alpha.17
    @storybook/theming: ^6.1.0-alpha.17 => 6.1.0-alpha.17
```

**Additional notes**
Current dirty patch involves: 

```
    control: {
      type: 'select',
      options: Object.fromEntries(Object.entries(mockUp).map(arr => arr.reverse())),
    },
```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1199622255231368/1200019560975894) by [Unito](https://www.unito.io/learn-more)

**Comment by shilman** [comment]
Is this actually a bug? Arg names must be strings, but arg values can be anything. So the current schema makes more sense to me than the proposed reversal.

**Comment by bryantee** [comment]
Would be great if the docs showed the `options` list as an object as suggested above, since current examples really only show the array syntax.

<img width="833" alt="image" src="https://user-images.githubusercontent.com/10674447/98750578-8f79b600-237b-11eb-880c-28bcb26aa7bd.png">

**Comment by vladimircores** [comment]
We experience the problem when the selected option does not have "title" (object key) displayed in select field.
![select-field-no-title](https://user-images.githubusercontent.com/442111/98845159-98d35300-244d-11eb-8cd1-0fc433129bfc.gif)
And object defined like this:
![Screenshot 2020-11-11 183728](https://user-images.githubusercontent.com/442111/98845222-b0aad700-244d-11eb-87e4-3da2f545b34b.png)
We assign them like:
![Screenshot 2020-11-11 183716](https://user-images.githubusercontent.com/442111/98845255-bb656c00-244d-11eb-8b89-4a4ab6abe29c.png)

Any ideas why this happens?

**Comment by pavelspichonak** [comment]
I have the same issue as @vladimircores has. @vladimircores did you find out why this happens?

**Comment by pavelspichonak** [comment]
@shilman looks like I found out when we have the issue described by @vladimircores.

When value of option is string it works great. But when the value of option is object it works like @vladimircores described.

this works good:
`
 options: { option1: "option1Value", option2: "option2Value" }
`

but this has issue:
`
 options: { option1: { someProp: "somePropValue" }, option2: { someProp: "somePropValue" } }
`

**Comment by majard** [comment]
We are experiencing the same problem by @vladimircores too.

**Comment by ghengeveld** [comment]
Control options must be simple strings so they can be serialized and synced to the URL. Control options can still be defined as an object, but the only use case is if you want a custom select label that may not be serializable (e.g. outside the [a-z0-9 _-] range). To overcome this limitation, we're working on a new `mapping` feature in https://github.com/storybookjs/storybook/pull/14100 that makes it possible to use anything as the arg value.

It will not fix the bug explained above, but it will provide a workaround.

**Comment by ghengeveld** [comment]
As of Storybook 6.2, `control.options` is deprecated in favor of `options` (one level up), which only accepts an array. With that, we've circumvented the "object format is reversed" problem.

As mentioned before, we've introduced [`mapping`](https://github.com/storybookjs/storybook/blob/next/docs/writing-stories/args.md#mapping-to-complex-arg-values) to allow for complex arg values.

We've also introduced [`control.labels`](https://github.com/storybookjs/storybook/blob/next/docs/essentials/controls.md#dealing-with-complex-values) to allow you to configure custom labels for your checkbox, radio or select input.

**Comment by sparkle32817** [comment]
how can I define dropdown control in story arg, not argTypes in default?
I need only to show dropdown in `Start Icon`. I defined it in default, but it shows all stories. 

![image](https://user-images.githubusercontent.com/54101792/136829822-e3493843-7cf8-4f45-aa32-886dfb2a50e0.png)
