### ISSUE TITLE
Where from the custom scripts should be invoked now? Error:  `configure()` is deprecated

### ISSUE THREAD

**Issue by BiosBoy** [storybookjs/storybook#12618]
**Describe the bug**
Since v.6 I'm getting a warning message about:

```
browser.js:39 `configure()` is deprecated and will be removed in Storybook 7.0. 
Please use the `stories` field of `main.js` to load stories.
```

Besides, I don't need to load stories as they loaded in main.js already. Does it appear we lost the ability to run custom scripts in such a way below?

**To Reproduce**
Just make some `configuration()` invoke in your preview.js file.

**Expected behavior**
Should be some way to run custom scripts as it was in Storybook v.5 inside `config.js (preview.js now)`.
 
**Code snippets**
```
// ./preview.js

function loadStories() {
  addTornsRegularLayout()
  createSVGGeneratorContainerNode()
  webpChecker({ injectBodyClass: true })

  require('glob-loader!./stories.pattern')
}

configure(loadStories, module)

//...

export const parameters = {...}
```

**System**
System:
    OS: macOS 10.15.5
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 12.16.0 - /usr/local/bin/node
    Yarn: 1.18.0 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 85.0.4183.83
    Edge: 79.0.309.65
    Firefox: 81.0
    Safari: 13.1.1
  npmPackages:
    @storybook/addon-actions: ^6.0.22 => 6.0.22 
    @storybook/addon-backgrounds: ^6.0.22 => 6.0.22 
    @storybook/addon-centered: ^5.3.21 => 5.3.21 
    @storybook/addon-knobs: ^6.0.22 => 6.0.22 
    @storybook/addon-links: ^6.0.22 => 6.0.22 
    @storybook/addon-viewport: ^6.0.22 => 6.0.22 
    @storybook/cli: ^6.0.22 => 6.0.22 
    @storybook/react: ^6.0.22 => 6.0.22

**Comment by shilman** [comment]
@ndelangen @tmeasday do you know the answer to this?

@BiosBoy what happens if you put the initialization code at the top level in `.storybook/preview.js`?

**Comment by BiosBoy** [comment]
@shilman can confirm: "this is the way"! Works flawlessly. Thank you
