### ISSUE TITLE
@storybook/addon-essentials breaks eslint and typescript,Parsing error: Cannot read none exist tsconfig.json

### ISSUE THREAD

**Issue by mzvast** [storybookjs/storybook#12623]
**Describe the bug**
@storybook/addon-essentials breaks eslint and typescript

**To Reproduce**

I made a repo to reproduce, just follow my instructions on README.

1. clone https://github.com/mzvast/issue-reproduce-storybook-20200930.git
2. run `yarn`
3. run `yarn run test`
4. see error【Parsing error】
5 yarn remove @storybook/addon-essentials
6 run `yarn run test` again
7 not see error, just see lint results

**Expected behavior**
eslint works

**Screenshots**

- with @storybook/addon-essentials
![image](https://user-images.githubusercontent.com/8097465/94698592-0b8be180-036c-11eb-85be-af0464aff077.png)

- without @storybook/addon-essentials
![image](https://user-images.githubusercontent.com/8097465/94699278-bd2b1280-036c-11eb-86e1-f9dcf0541720.png)

**System**
Please paste the results of `npx sb@next info` here.
```
Environment Info:

  System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
  Binaries:
    Node: 12.18.0 - ~/.nvm/versions/node/v12.18.0/bin/node
    Yarn: 1.21.1 - ~/.nvm/versions/node/v12.18.0/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.18.0/bin/npm
  Browsers:
    Chrome: 84.0.4147.125
    Safari: 14.0
  npmPackages:
    @storybook/addon-actions: ^6.0.0 => 6.0.22 
    @storybook/addon-essentials: ^6.0.0 => 6.0.22 
    @storybook/addon-links: ^6.0.0 => 6.0.22 
    @storybook/react: ^6.0.0 => 6.0.22 
```

**Comment by shilman** [comment]
This looks like it's maybe a bug in `ts-jest`? It's looking for a `tsconfig.json` in the distribution, but we don't publish one, and why should we?

cc @gaetanmaisse @tooppaaa @yannbf who might know more
