### ISSUE TITLE
storybook-build uses development version of React

### ISSUE THREAD

**Issue by iDavidB** [storybookjs/storybook#12620]
**Describe the bug**
When running `storybook-build` or to be exact `storybook-build -o build` it will create a build using the development version of React.

**To Reproduce**
I was not able to figure out what exactly creates this behavior, but I did create a reproduction repository:

1. Clone [https://github.com/iDavidB/storybook-repro](https://github.com/iDavidB/storybook-repro)
2. Run `yarn (install)`
3. Run `yarn build`
4. Serve the build. Ex. `npx http-server /build`

**Expected behavior**
I expect the outputted build to be build as a production React app.

**Screenshots**
N.A.

**Code snippets**
N.A.

**System**
```
System:
    OS: Linux 5.3 Linux Mint 19.3 (Tricia)
    CPU: (12) x64 AMD Ryzen 5 2600 Six-Core Processor
  Binaries:
    Node: 12.18.4 - ~/.nvm/versions/node/v12.18.4/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.4/bin/npm
  Browsers:
    Chrome: 81.0.4044.122
    Firefox: 75.0
  npmPackages:
    @storybook/addon-actions: ^6.0.21 => 6.0.22 
    @storybook/addon-essentials: ^6.0.21 => 6.0.22 
    @storybook/addon-links: ^6.0.21 => 6.0.22 
    @storybook/node-logger: ^6.0.21 => 6.0.22 
    @storybook/preset-create-react-app: ^3.1.4 => 3.1.4 
    @storybook/react: ^6.0.21 => 6.0.22 

```

**Additional context**
N.A.

**Comment by shilman** [comment]
@ndelangen can you explain the rationale?

**Comment by ndelangen** [comment]
probably related to DLLs, I'd say it's a bug

**Comment by iDavidB** [comment]
Any suggestions on how I could debug this further?

**Comment by mrudowski** [comment]
with `build-storybook --no-dll` (as a workaround for other problem) we have the same result: storybook-build uses development version of React

React developer tools for chrome displays:

"This page is using the development build of React. 🚧
Note that the development build is not suitable for production.
Make sure to use the production build before deployment."

the same problem we get on these online examples:
http://storybook.anyvision.co/
https://next--storybookjs.netlify.app/official-storybook/

**Comment by mrudowski** [comment]
after update to new version of Storybook and new CRA (and some serious node modules refresh)
the problem is not longer exist  for me.

Sorry for false alarm flag

**Comment by iDavidB** [comment]
It seems that Storybook 6.1 fixes this issue. Thus closing for now.
