### ISSUE TITLE
addon-storysource does not render mdx

### ISSUE THREAD

**Issue by hok-wtag** [storybookjs/storybook#12636]
**Describe the bug**
I do have 2 types of stories jsx & mdx. all stories with jsx extension show storysource in story tab but none of the mdx shows up. it just shows the previous loaded jsx storysource. here is my main.js file
```
const path = require('path');

module.exports = {
	stories: ['../src/**/*.stories.@(jsx|mdx)'],
	addons: [
		'@storybook/addon-actions',
		'@storybook/addon-links',
		'@storybook/addon-knobs',
		'@storybook/addon-viewport',
		{
      name: '@storybook/addon-storysource',
      options: {
        rule: {
          test: [/\.stories\.(jsx|mdx)$/],
        },
      },
    },
		'@storybook/addon-docs'
	],
};
```

here is my config.js

```
import { configure } from '@storybook/react';
import requireContext from 'require-context.macro';
import '../src/styles/main.scss';
import './storybook.styles.scss';

const req = requireContext('../src/components', true, /\.stories\.(jsx|mdx)$/);

configure(req, module);

```
**To Reproduce**

**Expected behavior**

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
Please paste the results of `npx sb@next info` here.

**Additional context**

**Comment by shilman** [comment]
@hok-wtag what version?

**Comment by shilman** [comment]
closing as dupe to #8157

**Comment by hok-wtag** [comment]
version     "@storybook/addon-storysource": "^5.3.13",
