### ISSUE TITLE
Allow control of the ordering of the essential addons

### ISSUE THREAD

**Issue by kylemh** [storybookjs/storybook#12640]
**Is your feature request related to a problem? Please describe**
I like to have the Controls addon always appear first. I also always use the essential addons.

**Describe the solution you'd like**
Give me the ability to control the order of the addons from the essential addons pack.

**Are you able to assist to bring the feature to reality?**
Definitely! I would just wanna make sure we agree on the interface. My non-breaking change recommendation would be to interface this config similar to disabling individual addons in the pack: https://github.com/storybookjs/storybook/tree/next/addons/essentials#disabling-addons

```js
module.exports = {
  addons: [{
    name: '@storybook/addon-essentials',
    order: ['controls', 'actions', 'docs', 'viewport', 'toolbars'],
    options: {
      backgrounds: false,
    }
  }]
};
```

or, keep the same interface, but hope they remember that order matters with the keys in the object:

```js
module.exports = {
  addons: [{
    name: '@storybook/addon-essentials',
    order: ['controls', 'actions', 'docs', 'viewport', 'toolbars'],
    options: {
      // order matters
      controls: true,
      actions: true,
      backgrounds: false,
      docs: true,
      viewport: true,
      toolbars: true,
    }
  }]
};
```

or, a breaking change: 

```js
module.exports = {
  addons: [{
    name: '@storybook/addon-essentials',
    use: ['controls', 'actions', 'docs', 'viewport', 'toolbars'],
    // no more options key, if the name is missing above, the related addon wont be leveraged
  }]
};
```

**Comment by kylemh** [comment]
Anyways... anybody that wants to do this, here's the workaround: https://github.com/OperationCode/front-end/pull/1235

**Comment by shilman** [comment]
What if we just always made controls come first?

**Comment by kylemh** [comment]
I'd personally be happy with that!

**Comment by shilman** [comment]
Egads!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.0-alpha.19 containing PR #12652 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
