### ISSUE TITLE
Web Components not showing on IE11

### ISSUE THREAD

**Issue by gioschi** [storybookjs/storybook#12649]
### Bug or support request summary

Components not showing on IE11, but we see the list of Stories in the left tab.

### Steps to reproduce

Create a Storybook of Web Components (we made them using Stencil.js) and run it on IE11.

### Please specify which version of Storybook

- @storybook/html ^5.3.19

### Affected platforms 

IE11

### Screenshots / Screencast / Code Snippets (Optional)

Here is my preview-head.html file. Using that polyfills i'd expect the components to be seen.

```html
<!-- preview-head.html -->

<!-- With this instead the Storybook not even load -->
<!-- <script src="https://unpkg.com/@webcomponents/webcomponentsjs@2.2.7/webcomponents-bundle.js"></script> -->

<script type="module">
    import { applyPolyfills, defineCustomElements } from '../loader/index.mjs';
    applyPolyfills().then(() => {
      defineCustomElements();
    });
</script>

<link rel="stylesheet" href="./my-ui-lib/my-ui-lib.css" />
<script type="module" src="./my-ui-lib/my-ui-lib.esm.js"></script>
<script nomodule="" src="./my-ui-lib/my-ui-lib.js"></script>
<script
  src="https://maps.googleapis.com/maps/api/js?key=my-key&libraries=places"
  defer
></script>
```

**Comment by shilman** [comment]
Try upgrading to 6.0?

```
npx sb upgrade
```

[Full migration guide](https://medium.com/storybookjs/storybook-6-migration-guide-200346241bb5)

**Comment by alfbat** [comment]
We tried to update the storybook to the version (@ storybook / html ":" ^ 6.0.26), but on ie11 we still don't see the components in the storybook. 

- The current dependencies of storybook in the file (package.json) are the following:

   ```json 
    @storybook/addon-a11y: ^6.0.26,
    @storybook/addon-actions: ^6.0.26,
    @storybook/addon-docs: ^6.0.26,
    @storybook/addon-knobs: ^6.0.26,
    @storybook/addon-viewport: ^6.0.26,
    @storybook/addons: ^6.0.26,
    @storybook/html: ^6.0.26,
    @storybook/theming: ^6.0.26

- The current file (preview-head.html) is the following:

```ts
import { addParameters } from '@storybook/client-api';

addParameters({
  docs: {
    extractComponentDescription: (component, { notes }) => {
      if (notes) {
        return typeof notes === 'string' ? notes : notes.markdown || notes.text;
      }
      return null;
    },
  },
  options: {
    storySort: (a, b) => (a[1].kind === b[1].kind ? 0 : a[1].id.localeCompare(b[1].id, undefined, { numeric: true }))
  }
});
```

Thank you.

**Comment by giorgiogalassi** [comment]
Hi,

I've the same issue and similar `preview-head.html` file. 
Should i use [this](https://github.com/storybookjs/storybook/blob/release/5.3/examples/web-components-kitchen-sink/.storybook/preview.js) instead?

```typescript
import { setCustomElements } from '@storybook/web-components';
import customElements from '../custom-elements.json';

setCustomElements(customElements);
// deleted code
```

Notice that i'm using `@storybook/html` instead of `@storybook/web-components` and that my components are built with `Stencil.js`, so they're Web Components.

I've tried also [this](https://next--storybookjs.netlify.app/official-storybook/?path=/docs/addons-a11y-basebutton--delayed-render) Storybook and seems to work on IE11.

Any suggestion?

**Comment by giorgiogalassi** [comment]
Hi,

I upgraded to V6 and used the `@storybook/web-components` as i said in the comment above, but still the components do not show on IE11.

Any suggestion, please?

G.

**Comment by shilman** [comment]
@giorgiogalassi is there any error in the browser console?

**Comment by giorgiogalassi** [comment]
> @giorgiogalassi is there any error in the browser console?

Atm i cannont access the Storybook (i'm on a Mac), i will update this answer with a proper screenshot.

In the meantime the current behavior is the following:
We see the list of the Stories (all correct), but the components in the `Canvas` tab are not displayed.

Thanks for the support,
G.

**Comment by ndelangen** [comment]
IE11 is dead to us
