### ISSUE TITLE
Setting up Storybook v6 with Drupal Twig

### ISSUE THREAD

**Issue by dan2k3k4** [storybookjs/storybook#12667]
**Describe the bug**
I'm trying to upgrade a repository which uses Storybook v5, PostCSS, Twig (with Drupal Twig), and a custom webpack config.

**To Reproduce**
I've extracted what I've done so far to upgrade to Storybook v6 and upgrade most of the dependencies into a small repository:

1. Go to 'https://github.com/dan2k3k4/storybook-drupal-twig' and clone the repo
2. Run the steps to reproduce:
-- yarn
-- yarn run build-library // seems to work OK
-- yarn run build-storybook // causes issues with trying to parse Twig files in Storybook

**Expected behaviour**
All yarn run scripts should work fine, CSS should build correctly, and all stories in the Storybook server should load (i.e. imported twig files inside other twig files should load).

**Comment by shilman** [comment]
I hacked the offending line in `twig.js` where the error is occurring:

```js
      console.log({ template, tokens, twig: options.twig })
      output = tokens ? Twig.compiler.module[options.module](id, tokens, options.twig) : '';
```

Sometimes `tokens` is undefined. I don't know enough about twig, but it looks like either there's a bug in Twig, or maybe in one or more of the files:

```
    path: '/Users/shilman/projects/testing/storybook-drupal-twig/twig/components/news/news-teaser/news-teaser.html.twig',
    url: undefined,
    tokens: undefined
```

**Comment by dan2k3k4** [comment]
Thanks @shilman, I'll take a deeper look into the Twig.js module

**Comment by dan2k3k4** [comment]
OK, I updated all dependencies and removed the `trans` function in the Twig templates as that's something only for Drupal and we had created a fork to add that functionality in but it seems to cause issues.

Now I get a different error, both `yarn run build-library` and `yarn run build-storybook` compile fine. However when doing `yarn run storybook`, and then I check the `Components > Accordion` story, I get the following error:

`Unable to find template file @storybook/components/teaser-collection/teaser-collection.html.twig. TypeError: fs.statSync is not a function`

Any pointers on how to debug? I see in the `Actions` that I have:

```
error: (1) [Object]
0: Object
file: "$resolved:0f1e504a6fe91df4d18d11fdf549a6ff4f2821bdcb2390cf31ba49432c1121cc5fce6790a442053607955fb541e2ae6cffc8a263e3d51422d39f03219b033598:accordion.html.twig"
message: "Unable to find template file @storybook/components/teaser-collection/teaser-collection.html.twig. TypeError: fs.statSync is not a function"
name: "TwigException"
type: "TwigException"
warn: (2) ["You tried to add a duplicate decorator, this is not expected", null]
0: "You tried to add a duplicate decorator, this is not expected"
1: null
```

**Comment by TheZanBoy** [comment]
@dan2k3k4 It's an issue with twig-loader namespaces.
You can use a diff repo 'npm i -D https://github.com/fourkitchens/twig-loader' that has a fix for this problem (same config), or I recommend using 'twigjs-loader' which uses webpack aliases instead.

```
config.module.rules.push({
    test: /\.twig$/,
    use: 'twigjs-loader',
});
config.resolve.alias = {
    storybook: path.resolve(__dirname, '../', 'twig'),
};
```

It's also recommended that you update your storybook webpack config. Remove webpack.config.js file and add the following to your main.js

```
module.exports = {
  stories: [
    './styles.css',
    '../**/*.stories.@(ts|js)'
  ],
  addons: [
    '@storybook/addon-a11y',
    '@storybook/addon-actions',
    '@storybook/addon-knobs',
    '@storybook/addon-viewport',
  ],

  // Config Webpack
  webpackFinal: async (config, { configType }) => {

    // Alias
    config.resolve.alias = {
      ...aliases
    }
    // Loaders
    config.module.rules.push(
      ...loaders
    );

    // Plugins
    config.plugins.push(
      ...plugins
    );

    ...etc

    // Return the altered config
    return config;
  },
};
```

**Comment by dan2k3k4** [comment]
@TheZanBoy thanks, I updated the forked `AmazeeLabs` version with latest changes for `twig-loader` then re-added the changes to support namespaces:
`yarn remove twig-loader && yarn add twig-loader@https://github.com/AmazeeLabs/twig-loader#6a45205895e0dc0fcdb028bd58d2bfaa6b5c4c54`

I also updated the `.storybook/main.js` file and removed the `.storybook/webpack.config.js` but I still get the same error:
`Unable to find template file @storybook/components/teaser-collection/teaser-collection.html.twig. TypeError: fs.statSync is not a function`

```
error: (1) [Object]
0: Object
file: "$resolved:cd631aceebd9ef5f0b1cd63f0a8c5c3ae7e40443bc63802f6fb974a0b766f4280e349fece3a3f1198b82f9c4621d514d79296ae17cd3dd50a2938008d32708d8:accordion.html.twig"
message: "Unable to find template file @storybook/components/teaser-collection/teaser-collection.html.twig. TypeError: fs.statSync is not a function"
name: "TwigException"
type: "TwigException"
warn: (2) ["You tried to add a duplicate decorator, this is not expected", null]
0: "You tried to add a duplicate decorator, this is not expected"
1: null
```

**Comment by TheZanBoy** [comment]
@dan2k3k4 I managed to fix it by using `twigjs-loader` instead.

```
const path = require('path');

// Import common configurations.
const common = require('../webpack.common');

module.exports = {
  stories: [
    './styles.css',
    '../**/*.stories.@(ts|js)'
  ],
  addons: [
    '@storybook/addon-a11y',
    '@storybook/addon-actions',
    '@storybook/addon-knobs',
    '@storybook/addon-viewport',
  ],

  // Config Webpack
  webpackFinal: async (config, { configType }) => {

    // Alias
    config.resolve.alias = {
      '@twig': path.resolve(__dirname, '../', 'twig'),  <-- '@storybook' alias created a conflict so I had to change it.
      '@decorators': path.resolve(__dirname, '../', 'utils/storybook/decorators'),
    }
    // Loaders
    config.module.rules.push(
      common.javascript,
      common.assets,
      common.css,
      {
        test: /\.twig$/,
        use: 'twigjs-loader',
      }
    );

    // Add common plugins.
    config.plugins.push(...common.plugins);

    // Support importing typescript files without extension.
    config.resolve.extensions.push('.ts');

    // Return the altered config
    return config;
  },
};
```

Change `{% include '@storybook/...etc' %}`to `{% include '@twig/...etc' %}` or any other alias.

I also forgot to mention that storiesOf, AddParameter, and addDecorator are deprecated so you may need to update your stories.

```
import Wrapper from '@decorators/Wrapper';  <-- using an alias from the config above

import Component from './accordion.html.twig';
import { accordion } from './accordion.data';

export default {
  title: 'Components/Accordion',
  parameters: {
    // options
  },
  decorators: [Wrapper]
};

export const Accordion = () => Component(accordion);
```

And if you want to go the extra step, you can check [emulsify-drupal](https://github.com/emulsify-ds/emulsify-drupal).

**Comment by dan2k3k4** [comment]
@TheZanBoy cool, yeah I just fixed it too with `twigjs-loader` but I used `@/storybook` and then had to update all includes to `@/storybook` - however your `@twig` version seems nicer so I'll try that.

**Comment by dan2k3k4** [comment]
I've updated my [sample repo](https://github.com/dan2k3k4/storybook-drupal-twig), I seem to have issues with `LitElement` not rendering at all on the frontend, and `window.litElementVersions` being undefined, whereas it would display the version on the working (pre-upgrade) version.

However I _think_ that's unrelated to this issue so I'm closing.

**Comment by dan2k3k4** [comment]
Mmm OK I got the `LitElement`s working again:
https://github.com/dan2k3k4/storybook-drupal-twig/commit/3c71c072dee75ac01dcd7bfd346badad0342ae43

I had to remove the `@` which I think Webpack 5 suggested (or perhaps it was Storybook 6).

Now I just get a lot of ESLint warnings which are coming from `node_modules` directory 🤔

**Comment by TheZanBoy** [comment]
@dan2k3k4 You need to exclude `node_modules`.

This is the config I'm using :
```
{
  test: /\.js$/,
  enforce: 'pre',
  exclude: /node_modules/,
  loader: 'eslint-loader',
  options: {
    cache: true,
    failOnWarning: false,
    failOnError: false,
    emitWarning: true,
  }
```
