### ISSUE TITLE
Global decorators can not be overwritten on story level anymore

### ISSUE THREAD

**Issue by andre-brdoch** [storybookjs/storybook#12670]
**Describe the issue**
With the now deprecated context addon, it was possible to define global decorators that can be configured/disabled on story level. 

The addon has been replaced by the [toolbar](https://storybook.js.org/docs/react/essentials/toolbars-and-globals), which uses globals. However, globals can only be adjusted in `preview.js`, not on story level.

I tried an alternative decorator that uses parameters instead of globals. Adding the parameter to a story does rerun the decorator function (console.log statements do show up), however, the component **does not rerender** (Tested with vue).

Therefore, currently I do not see any possibility of achieving the behavior that was possible with the context addon. 

**Expected behavior**
There should be a way to have global decorators, that can be configured on story level. If there is and I just missed it, it would be great to add it to the documentation 😃 I'd be happy to make the PR.

**System**
@storybook/vue: 6.0.21

**Comment by andywd7** [comment]
I'm not sure if this is the same issue but in vue, a global decorator does not update the story in Canvas. It logs the change in console and selecting another story in the sidebar updates the canvas. Also more interestingly selecting an option is reactive and updates stories as expected but in Docs view.

My example scenario is switching a light and dark theme class in a decorator using toolbar and globals. 
Example repo: [https://github.com/andywd7/storybook](https://github.com/andywd7/storybook)
[https://trusting-montalcini-282027.netlify.app](https://trusting-montalcini-282027.netlify.app)

**Comment by mfolnovic** [comment]
👍 

this is also not possible with React

**Comment by k4lu-0p** [comment]
> I'm not sure if this is the same issue but in vue, a global decorator does not update the story in Canvas. It logs the change in console and selecting another story in the sidebar updates the canvas. Also more interestingly selecting an option is reactive and updates stories as expected but in Docs view.
> 
> My example scenario is switching a light and dark theme class in a decorator using toolbar and globals. Example repo: https://github.com/andywd7/storybook https://trusting-montalcini-282027.netlify.app
> 
> I don't think this is the same issue so I have created a new ticket #12840

i've got same behavior but it's reversed. When i update globals with my custom toolbar my MDX Story doesn't refresh. any any help will be welcome  🙏🏻

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).

**Comment by AleferReinert** [comment]
I'm having this same problem in storybook 7.0.

I have a container in the global decorator and a container in some components, this makes it difficult.

**Comment by zeckdude** [comment]
I am experiencing the same issue with v7. Basically the component decorator sits inside the global decorator, but I would expect the component decorator to override the global decorator.

**Comment by KevinGhadyani-Okta** [comment]
Still valid in Storybook v8.

**Comment by shilman** [comment]
A workaround is the following if you can modify the source code of the decorator in question.

```diff
// .storybook/preview.js
- const myDecorator = (story) => <Wrapper>{story()}</Wrapper>;
+ const myDecorator = (story, { parameters }) => (
+   parameters.disableWrapper ? story() : <Wrapper>{story()}</Wrapper>
+ )
export default {
  decorators: [myDecorator]
}
```

Then you can flexibly set `parameters.disableWrapper` at the project, component, or story level. You can use this pattern to make your decorators as smart as you want.

We're also working on a different solution that doesn't require modifying the source code of the decorators, but it is less flexible. In a future version of Storybook you will effectively be able to define multiple project-level settings. For example, if you are building out pages in Storybook, they might require a specific set of decorators, whereas lower-level atomic components might need a different set. Then your page components could extend the page settings, and your atomic components could extend the component settings.

You can read more about the proposal here under the heading "Multiple preview configs":

https://github.com/storybookjs/storybook/discussions/30112
