### ISSUE TITLE
Controls are not ejectable

### ISSUE THREAD

**Issue by raphaellueckl** [storybookjs/storybook#12675]
**Describe the bug**
Storybook-Controls are not transfering the state if you eject the component. We run our UI tests based on knobs, which you can configure and eject (1 page with only this component in it and nothing else), to run tests onto.

**To Reproduce**

1. Go to the official demo example: https://next--storybookjs.netlify.app/official-storybook/?path=/story/addons-controls--basic
1. In the 'Controls' Tab, manipulate the text of the button.
1. Click on the top right "share"-button.
1. A new tab opens with the isolated component, but the state set by the controls is not transferred.

**Expected behavior**
The new page should contain the attributes set by the controls, like with storybook-knobs.

**Screenshots**

![Screen-Recording-2020-10-06-at-1](https://user-images.githubusercontent.com/8248662/95189793-a2262b80-07ce-11eb-8606-c5d645adbe75.gif)

**Comment by shilman** [comment]
Closing this as a dupe to #12291 (it's not quite a dupe, but we'll solve it all at once, as part of 6.1)
