### ISSUE TITLE
Issue with custom html tags

### ISSUE THREAD

**Issue by fcisio** [storybookjs/storybook#12671]
**Describe the bug**
Storybook does not work with custom HTML tags, example: `<x-icon>`, `<x-grid>`, `<x-cell>`.

**To Reproduce**
I'm using Emotion for styling, but I don't think this is an Emotion issue. The components with custom tags are working fine everywhere except on Storybook.

1. Create a working story
2. Change the base tag of the component in that story for a custom tag `<x-someting>`
3. You should see that the component is now broken, styles and props do not work.

**Expected behavior**
The component should work normally regardless of its tag.

**Code snippets**
```js
Container.defaultProps = {
  as: 'm-container',
  variant: 'default',
}
```

**System**
System:
    OS: macOS 10.15
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  Binaries:
    Node: 14.12.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
  Browsers:
    Chrome: 85.0.4183.121
    Firefox: 80.0.1
    Safari: 13.0.2
  npmPackages:
    @storybook/addon-a11y: ^6.0.22 => 6.0.22 
    @storybook/addon-actions: ^6.0.22 => 6.0.22 
    @storybook/addon-docs: ^6.0.22 => 6.0.22 
    @storybook/addon-essentials: ^6.0.22 => 6.0.22 
    @storybook/addon-links: ^6.0.22 => 6.0.22 
    @storybook/addons: ^6.0.22 => 6.0.22 
    @storybook/react: ^6.0.22 => 6.0.22 
    @storybook/theming: ^6.0.22 => 6.0.22 
  npmGlobalPackages:
    @storybook/cli: 6.0.22

**Additional context**
The components with custom tags are working fine everywhere except on Storybook.

**Comment by shilman** [comment]
how are you setting it up "everywhere else"?

**Comment by fcisio** [comment]
Hi @shilman , thanks for the quick response.
While creating the repro I identified the source of the issue.

😅 It was an Emotion.js issue after all!

When using a custom tag the `className` doesn't get transformed into `class`.
Apparently the theming tools I'm using on my projects mitigate this issue, but it doesn't work in SB.
