### ISSUE TITLE
Inconsistent imageSnapshots, how to delay?

### ISSUE THREAD

**Issue by froleo** [storybookjs/storybook#12673]
**Describe the bug**
I use imageSnapshot from addon-storyhots-puppetteer to create visual regression tests for my stories.
I'm having issues with inconsistent screenshots with certain components which has animation on render.
For example a component which has a state that displays a snackbar.

Is there any way to set a timeout for imageSnapshot to delay the screenshot for a second?

Config:
```import initStoryshots from "@storybook/addon-storyshots";
import { imageSnapshot } from "@storybook/addon-storyshots-puppeteer";

initStoryshots({
  suite: "Image storyshots",
  test: imageSnapshot(),
});
```

**Comment by EdenTurgeman** [comment]
Hey @froleo We have the same use case, the way we solve this is by not taking pictures of animated component, this might not be the best solution but it works for our use case and for how we handle animations in our style guide.
Please take a look at our code 😄 

```js
const ignoredPageElements = ['loadingButton', 'fade'];

const disableAnimationElements = pageElementsToIgnore => {
  // we take our Progress bar and add it to the rest of our selectors which we want to hide (in this instance the `ignoredPageElements` array above).
  const animatedPageElementsSelectors = [`[role*="progressbar"]`]
    .concat(pageElementsToIgnore.map(elementSelector => `[data-logz-test-subject*="${elementSelector}"]`))
    .join(',');

  // Select all the elements which we want to hide.
  const animatedPageElements = document.querySelectorAll([animatedPageElementsSelectors]);

  // hide theme using the power of .evaluate 
  animatedPageElements.forEach(pageElement => {
    pageElement.style.visibility = 'hidden';
  });
};

export const storiesToTestRegex = '^((?!.*?(IFrame|Palette|Fade)).)*$';

export const beforeScreenshot = page =>
  new Promise(resolve =>
    page.evaluate(disableAnimationElements, ignoredPageElements).then(() => {
      setTimeout(() => {
        console.log(`Snapping - ${new URL(page.url()).searchParams.get('id')}`);
        resolve();
      }, waitBeforeSnapshotTime);
    }),
  );
```

**Comment by EdenTurgeman** [comment]
@shilman Since i've seen this issue cropping up a few times, I'm wondering if the best temporary solution is adding a param to the `imageSnapshot` method, something along the lines of:
```js
initStoryshots({
  framework: 'react',
  suite: 'Image Storyshots',
  storyKindRegex: storiesToTestRegex,
  test: imageSnapshot({
    storybookUrl,
  **elementsToHide**,
    beforeScreenshot,
    getGotoOptions,
    chromeExecutablePath: '/usr/bin/chromium-browser',
  }),
});
```
elementsToHide will receive an array of valid jquery selectors which puppeteer will try to find and hide inside the internal `beforeScreenshot` method.

@shilman Would love to hear your opinion so i could maybe take a shot at implementing a fix.

**Comment by froleo** [comment]
@EdenTurgeman I was able to get around this issue by setting a timeout in beforeScreenshot. Still having some issue with loading spinners, but I think i'll do e regex not to screenshot stories with loading in the name.

```import initStoryshots from "@storybook/addon-storyshots";
import { imageSnapshot } from "@storybook/addon-storyshots-puppeteer";

const beforeScreenshot = (page, { context: { kind, story }, url }) => {
  return new Promise((resolve) =>
    setTimeout(() => {
      resolve();
    }, 600)
  );
};

initStoryshots({
  suite: "Image storyshots",
  test: imageSnapshot({
    storybookUrl: "http://localhost:6006",
    beforeScreenshot,
  }),
  storyNameRegex: /^/,
});
```
