### ISSUE TITLE
HMR not working in Chrome Canary

### ISSUE THREAD

**Issue by tflx** [storybookjs/storybook#12677]
**Describe the bug**
HMR not working in Chrome Canary (Version 88.0.4283.2 (Official Build) canary (x86_64)) with Storybook 6.0.26 - and most or all of the previous v6'es. 
I'm not getting any errors in the console (except for "DevTools failed to load SourceMap" which I also get in Chrome stable.
I have also tested in Incognito without any plugins active.
This is with storybook/html.

**Expected behavior**
It works in latest stable Chrome version, and FF.

**Environment Info:**
  System:
    OS: macOS 11.0
    CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
  Binaries:
    Node: 12.6.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.12.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 85.0.4183.121
    Edge: 85.0.564.68
    Firefox: 81.0
    Safari: 14.0.1
  npmPackages:
    @storybook/addon-a11y: ^6.0.26 => 6.0.26 
    @storybook/addon-essentials: ^6.0.26 => 6.0.26 
    @storybook/html: ^6.0.26 => 6.0.26

**Comment by tomekkoszykowski** [comment]
I have the same issue

Version 88.0.4287.0 (Official Build) canary (x86_64)
Storybook 6.0.26 

Normal Chrome
Version 86.0.4240.75 (Official Build) (x86_64) is ok

**Comment by shilman** [comment]
Possibly related #12626
