### ISSUE TITLE
Upgrade the dependency from storybook/addon-info on ua-parser-js to fix security exposure

### ISSUE THREAD

**Issue by scottdickerson** [storybookjs/storybook#12678]
**Describe the bug**
According to our security scan tool, the ua-parser-js that storybook/addon-info has a security exposure:
https://snyk.io/vuln/SNYK-JS-UAPARSERJS-610226

Please upgrade the dependency to be  UAPARSER 0.7.22 or later

**Comment by shilman** [comment]
`addon-info` is deprecated and has been superceded by `addon-docs`, which fixes a bunch of bugs and is easier to maintain. Please give it a try! https://medium.com/storybookjs/storybook-docspage-e185bc3622bf

https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-addon-info-addon-notes

**Comment by scottdickerson** [comment]
we can cancel this due to the comment above.
