### ISSUE TITLE
Documentation for api

### ISSUE THREAD

**Issue by softmarshmallow** [storybookjs/storybook#12696]
https://github.com/storybookjs/storybook/tree/master/lib/api

leads to no documentation.

**Comment by jonniebigodes** [comment]
@softmarshmallow sorry for the inconvenience you're experiencing. If you're ok can you give some additional context on this issue? So that when the documentation is updated we can act on it properly.

Let me know when you've updated the description.

Stay safe

**Comment by jonniebigodes** [comment]
Closing this for now! Thanks for raising it. Once we've decided on a good pattern to document the internals of Storybook we'll re-open and follow up with you.
