### ISSUE TITLE
Readonly/plain text control option

### ISSUE THREAD

**Issue by andywd7** [storybookjs/storybook#12693]
**Is your feature request related to a problem? Please describe**
I would like to be able to show all controls for a component in Canvas but make one of them readonly. For example to have a Primary button story and play with it size, disabled etc... but always keep it as the Primary one. I know you can disable an individual prop but this leaves me with a "-" when I would still like to show that the variant prop should be set to "primary".

**Describe the solution you'd like**
Be able to set an individual control as readonly or plain text if readonly attribute is not applicable.

**Describe alternatives you've considered**
Cannot think of any

**Are you able to assist to bring the feature to reality?**
No

**Comment by shilman** [comment]
closing as dupe to #14048 which includes a concrete proposal
