### ISSUE TITLE
Documentation: TypeScript example for "YourComponent" in "Setup Storybook" results in type error

### ISSUE THREAD

**Issue by marko-knoebl** [storybookjs/storybook#12695]
I'm getting an error when using the TypeScript example here: https://storybook.js.org/docs/react/get-started/setup

The source code of the example is here: https://github.com/storybookjs/storybook/blob/next/docs/snippets/react/your-component.ts.mdx

When actually trying this code for any component I get a type error in the editor ("'YourComponent' refers to a value, but is being used as a type here.") and in storybook itself I get the error "Objects are not valid as a React child" when trying to access this story.

This is the critical code in the TypeScript example:

```tsx
const Template = (args: YourComponent) => ({
  component: YourComponent,
  props: args,
});
```

If I replace it with this code the issue is resolved:

```tsx
import { Story } from "@storybook/react/types-6-0";
```

```tsx
const Template: Story<Parameters<typeof YourComponent>[0]> = (args) => (
  <YourComponent {...args} />
);
```

which is actually in line with the JavaScript example in the documentation:

```jsx
const Template = (args) => <YourComponent {...args} />;
```

**To Reproduce**

create a simple component:

```tsx
// YourComponent.tsx
import React from "react";

type Props = { text: string };
export const YourComponent = (props: Props) => <div>{props.text}</div>;
```

and test it according the current documentation:

```tsx
// YourComponent.stories.tsx
import React from 'react';
import { YourComponent } from './YourComponent';

// This default export determines where your story goes in the story list
export default {
  title: 'YourComponent',
  component: YourComponent,
};

const Template = (args: YourComponent) => ({
  component: YourComponent,
  props: args,
});

export const FirstStory = Template.bind({});
FirstStory.args = {
  /* the args you need here will depend on your component */
};
```

**Comment by shilman** [comment]
Should be something like:

```tsx
import React, { ComponentProps } from 'react';

const Template = (args: ComponentProps<typeof YourComponent>) => { ... }
```

**Comment by jonniebigodes** [comment]
@marko-knoebl sorry for the delay in answering and tackling this issue. Thank you for bringing this to our attention. I've just made a pull request where the snippet was adjusted to prevent the misleading. 

Stay safe

**Comment by jonniebigodes** [comment]
Going to close this issue as it's already addressed. @marko-knoebl thank you for your help on this one. 

Stay safe.
