### ISSUE TITLE
Storyshots: Support async loaders

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#12703]
Storybook 6.1 adds support for asynchronous data loading for stories (#12699).

In order to add storyshots support we can either:
- Introduce a breaking change to support async loading
- Introduce a new set of APIs for to handle loading

Filing this as a follow-up issue because either option is going to be a chunk of work and we need to validate the loader stuff first.

**Comment by kevinbarabash** [comment]
I'm not using Storyshots because I have a custom snapshot serializer (it outputs each snapshot to its own SVG file) so I ended up creating a small helper to convert stories to components.  There are some cases it doesn't handle yet, but it meets my current needs.  I thought I'd share in the hope that other may find it useful.
```javascript
const storyToComponent = async function <T>(
    story: Story<T>,
): Promise<React.FC<T>> {
    const loaded = {};

    for (const value of await Promise.all(
        storyMeta.loaders.map((loader) => loader()),
    )) {
        Object.assign(loaded, value);
    }

    return () => {
        const context: StoryContext = {
            id: "",
            kind: "",
            name: "",
            parameters: {},
            args: {},
            argTypes: {},
            globals: {},
            loaded: loaded,
        };
        // @ts-expect-error: story expects T instead of Partial<T> | undefined
        return story(story.args, context);
    };
};
```
Here's an example test using this helper:
```javascript
    test("equation", async () => {
        const Equation = await storyToComponent(stories.Equation);
        expect(<Equation />).toMatchSnapshot();
    });
```

**Comment by ndelangen** [comment]
The future of storyshots is the test-runner:
https://storybook.js.org/docs/react/writing-tests/test-runner#page-top

And use the play function for expectations:
https://storybook.js.org/docs/react/writing-stories/play-function#page-top

We will not be making any improvement / changes to storyshots.
