### ISSUE TITLE
Updating fork-ts-checker-webpack-plugin to v5.x

### ISSUE THREAD

**Issue by maneetgoyal** [storybookjs/storybook#12701]
**Is your feature request related to a problem? Please describe**

Will be great the `fork-ts-checker-webpack-plugin` can be updated to `v5` in the future. It allows a concise way of overriding `include` field in `tsconfig.json` via [`configOverwrite`](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin#typescript-options) to allow easier type-checking of story files (`*.stories.ts`).

**Describe the solution you'd like**

I was hoping to do something like:

```js
// .storybook/main.js
module.exports = {
  ...
  typescript: {
    check: true, // Enabling fork-ts-checker-webpack-plugin for unlocking type-checking
    checkOptions: {
       typescript: {
         configOverwrite: { include: ["./src/**/*.stories.tsx"] }
       }
    }
  },
}
```

**Describe alternatives you've considered**

[Other solutions](https://stackoverflow.com/a/57582925) that I tried seemed a little lengthy. I'd prefer not to modify the default Storybook Webpack config whenever possible.

Another (working) solution I tried is:

```ts
// .storybook/main.js
module.exports = {
  ...
  typescript: {
    check: true, // Enabling fork-ts-checker-webpack-plugin for unlocking type-checking
    checkOptions: {
        checkOptions: {
        tsconfig: "./tsconfig.storybook.json",
      },
    }
  },
}
```

```
// tsconfig.storybook.json
{
  "extends": "./tsconfig.json",
  "include": ["./src/**/*.stories.tsx"]
}
```

**Are you able to assist to bring the feature to reality?**

Can help with testing once it is installed onto `master`.

**Additional context**

https://github.com/storybookjs/storybook/issues/11804#issuecomment-668936341

**Comment by sakito21** [comment]
@shilman 
Can I try this?

**Comment by maneetgoyal** [comment]
Hello all, a little heads up: `fork-ts-checker-webpack-plugin` recently released a **6.x pre-release** (`-alpha.1`) which addresses https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/issues/36 as mentioned here: https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/issues/36#issuecomment-710771939. That fix is quite useful in Storybook's watch (`start-storybook`) mode as it makes the type checking feature more _complete_.

**Comment by gaetanmaisse** [comment]
I will take a look at that in the next couple of days 😉

**Comment by shilman** [comment]
cc @phated

**Comment by gaetanmaisse** [comment]
I think we will need to wait for Storybook 7.0 to be able to update this dependency as the options format changed between `fork-ts-checker-webpack-plugin` 4 and 5, as these options are part of the Storybook configuration via `.storybook/main.js.` it will be a breaking change on Storybook side too.

**Comment by maneetgoyal** [comment]
Hi @shilman, is this being considered for 7.x?

**Comment by shilman** [comment]
@maneetgoyal this is done. Storybook has a builder for webpack4 which is the default and ships with 4.x, and a builder for webpack5 that's currently opt-in and ships with 6.x. In 7.0, either webpack5 will become the default or there will be no default and everything will be opt in. Closing this issue--let me know if there is any follow up needed.
