### ISSUE TITLE
Instant-on manager UI

### ISSUE THREAD

**Issue by ghengeveld** [storybookjs/storybook#12702]
Showing the manager UI instantly on startup will transform Storybook’s out-of-box UX and show existing users a strong commitment to performance.

The following approach would maximally leverage our existing setup:
- Ship a cached version of the bundle, including essential addons
- Load the cached version and show the manager immediately when starting Storybook
- Re-cache the manager bundle on config change (ideally during addon install)
- Show an appealing and useful UI as the preview builds

See Storybook Performance strawman for context.

**Comment by shilman** [comment]
@ghengeveld while you're doing the loading UI can you handle the loading UI for async loaders? 

https://github.com/storybookjs/storybook/pull/12699

**Comment by shilman** [comment]
w00t!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.0-alpha.33 containing PR #12707 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Olé!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.0 containing PR #12707 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```
