### ISSUE TITLE
SB 6.1 Search UX (final rfcs)

### ISSUE THREAD

**Issue by domyen** [storybookjs/storybook#12714]
**Is your feature request related to a problem? Please describe**
This is the follow up work to a recently merged PR #12601 from [this comment](https://github.com/storybookjs/storybook/pull/12601#issuecomment-705050652) targeted for 6.1.

### **How many search results**
> Changed it to show 20 results by default. I picked this number because it means the "Show more" button is visible on most desktop displays, but only at the very bottom. This is useful to gauge the total number of results without having to scroll.

On further thought, I suggest removing the show more altogether (unless there are _significant_ performance benefits). This makes it easier to skim all the results without leaving the search field.

<details>
<summary>More background</summary>

This isn't a typical search where result count is useful for things like pagination or to get a sense of information scale. The pattern here is find/filter. Folks are filtering by changing the query – similar to VSCode `cmd+t` and skimming the results. They're more likely to keep the search field focused and guess different queries than click out to paginate the results. That leads me to suggest showing all the results at once to let users skim the full list instead of making them click more.

iirc, Yann mentioned this behavior while we were researching. Something to the effect of "I only care about the first few results and will keep typing until I see what I want".
</details>

### **Preserve search value**
> Right now "recently viewed" is implemented like they're default search results, so this behavior would also apply there (unless I hack around it). Then there's the issue of focus management and keyboard listeners. When you select a result, we open the component which may claim focus and/or register keyboard listeners. That means we can lose focus on the search field and/or the ability to close the search by pressing Escape. I suggest we gather more feedback before going down this road.

I don't think punting on this workflow makes sense. The current UX is intended for the ideal case: a user knows exactly what they want to click on. But the flow becomes cumbersome for unideal cases. 

Check out this real-life scenario from Chromatic's Storybook:
1. You're working on a `PullRequests` feature
2. Search for `PullRequests` to get a list of components below (there are at least 12 results for this term)
![image](https://user-images.githubusercontent.com/263385/95357616-124bb480-0896-11eb-9679-b3797c90af0a.png)
3. Click on one to see it 
4. Realize that it's not the component you want 🤦‍♀️
5. Now what?

**Option: Leave behavior as is**
Folks will have to type out `PullRequests` again, then click on another result. They'll type `PullRequests` again and again to see the results because clicking on one will clear the search field. 

**Option: Change behavior to preserve search results**
Folks will click again on the search field whose value remains `PullRequests` to see the results. They click the next result to view the component. If that's not the component they're looking for, they can click on the search field again to view the results.

**Comment by shilman** [comment]
Good golly!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.0-alpha.31 containing PR #12765 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
