### ISSUE TITLE
Expose storybook text primitive

### ISSUE THREAD

**Issue by AndrewLeedham** [storybookjs/storybook#12713]
**Is your feature request related to a problem? Please describe**
I am wanting to create components for docs pages for use in a project that have the same theme as storybook. However, there does not seem to be a way to create text nodes without manually specifying the font-family, size etc.

**Describe the solution you'd like**
A `Text` component exposed from `@storybook/components` or `@storybook/addon-docs/blocks`.

**Describe alternatives you've considered**
I tried to use the already exposed `Description` and `Subtitle` components, but I had to override a bunch of their styles, and it just seemed hacky.

**Are you able to assist to bring the feature to reality?**
Yes if someone can point me in the right direction.

**Additional context**
https://discord.com/channels/486522875931656193/551682580941111296/763038988143165520

**Comment by AndrewLeedham** [comment]
CC: @shilman

**Comment by shilman** [comment]
I think `Description` is the closest thing there. It takes markdown and produces consistently styled text. Did you run into problems with that?

**Comment by AndrewLeedham** [comment]
@shilman the problem I am having is with margin etc 
![image](https://user-images.githubusercontent.com/5557458/95571089-cc225c80-0a1f-11eb-87a2-78e91357e84d.png)
I was thinking of a Text component that is purely styling no layout, so I can just drop it in and adjust layout myself. With the `Description` component it is a paragraph with margin. Also passing markdown seems a strange way of doing things.

**Comment by shilman** [comment]
Gotcha. I think they might already be exported here:

https://github.com/storybookjs/storybook/commit/10013736ac64688001ff215a4ca48635c4e4e938

**Comment by AndrewLeedham** [comment]
> Gotcha. I think they might already be exported here: [1001373](https://github.com/storybookjs/storybook/commit/10013736ac64688001ff215a4ca48635c4e4e938)

There is a lot of noise there, which part are you referring to?

> But adding a component/block WFM

I'll see if I can get a PR in for that.

**Comment by shilman** [comment]
https://github.com/storybookjs/storybook/commit/10013736ac64688001ff215a4ca48635c4e4e938#diff-5ea6f3b330e7d9756b8671ac5ecd9db701e1f0f972cebad8da3f2a31d0d16c02R15

**Comment by AndrewLeedham** [comment]
Using `import { Span } from "@storybook/components/html";` works for my needs 👍
