### ISSUE TITLE
Broken build

### ISSUE THREAD

**Issue by pedroapfilho** [storybookjs/storybook#12712]
<img width="1422" alt="Screenshot 2020-10-08 at 21 24 08" src="https://user-images.githubusercontent.com/13142568/95509675-b32c9380-09ac-11eb-81cf-355b4a6b04a5.png">

I just upgraded to the latest version and this error message is appearing when I run storybook.

I upgraded these packages to the latest version:

<img width="970" alt="Screenshot 2020-10-08 at 21 26 19" src="https://user-images.githubusercontent.com/13142568/95509853-f2f37b00-09ac-11eb-87a1-7fcb601033e9.png">

**Comment by pedroapfilho** [comment]
Just rolled back and it works fine now.

**Comment by shilman** [comment]
Did you try removing `node_modules` and/or lockfiles and reinstalling?

**Comment by pedroapfilho** [comment]
I did! and it worked!
