### ISSUE TITLE
Runtime errors during story loading should fail storyshots

### ISSUE THREAD

**Issue by Hypnosphi** [storybookjs/storybook#12729]
Have a story with following defauilt export:

```
export default {
  title: 'Title',

  argTypes: {foo: undefined}
};

```

Run storyshots test
Expected: test fails
Actual: the subset of stories before the broken one runs successfully, others are skipped silently

**Comment by thibaudcolas** [comment]
This is the same issue as https://github.com/storybookjs/storybook/issues/12540.

**Comment by Hypnosphi** [comment]
To be clear, this is not about the error itself, but about the fact that it's swallowed. So let's keep those issues separate

**Comment by Hypnosphi** [comment]
Is P3 high or low? I'd say this one is pretty critical, because it makes it really easy to miss the errors. There are warning messages, but no failed tests

**Comment by shilman** [comment]
P3 is low. We are in the process of creating an alternative to storyshots and are focusing our efforts there (and on other packages). I'd happily accept a PR to fix this issue.

**Comment by robinjoerke** [comment]
I found a way to work around a similar issue. this is most mayby not a solution here but might help for some so i wanted to share my findings. (In my case a missing `moduleNameMapper` created an issue while loading a story in `initStoryshots`. the error was printed to the console, but the snapshot was not initialized properly. the test ran but never took and copared a snapshot. the test was passing) 
so i worked around this issue by spying on the console when running `initStoryshots`
```
const spyError = jest.spyOn(global.console, 'error');
const spyWarn = jest.spyOn(global.console, 'warn');

initStoryshots({ ...yourOptionsHere });

expect(spyError).not.toHaveBeenCalled();
expect(spyWarn).not.toHaveBeenCalled();
```
now when there is a console warn or error during `initStoryshots` the storyshots dont run at all but at least there is a failing test. i know its not perfect but at least there is a failing test

**Comment by ndelangen** [comment]
The future of storyshots is the test-runner:
https://storybook.js.org/docs/react/writing-tests/test-runner#page-top

And use the play function for expectations:
https://storybook.js.org/docs/react/writing-stories/play-function#page-top

We will not be making any improvement / changes to storyshots.
