### ISSUE TITLE
null in args leads to an invalid argType

### ISSUE THREAD

**Issue by Hypnosphi** [storybookjs/storybook#12732]
```js
export default {
  title: 'Title,

  args: {foo: null}
};
```

leads to following error in preview: 
```
Cannot read property 'defaultValue' of undefined
```

This is especially painful in connection with #12729 

It only reproduces if you _don't_ use docs addon

**Comment by thibaudcolas** [comment]
This is (also) the same issue as https://github.com/storybookjs/storybook/issues/12540.

**Comment by thibaudcolas** [comment]
This is the same underlying issue as https://github.com/storybookjs/storybook/issues/12540, although I haven’t tried what would happen to this in the Storybook UI.

**Comment by shilman** [comment]
Gadzooks!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.0-beta.3 containing PR #13029 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Yowza!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.0-beta.6 containing PR #13051 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```
