### ISSUE TITLE
Add option to render stories in React.StrictMode

### ISSUE THREAD

**Issue by oliviertassinari** [storybookjs/storybook#12734]
**Is your feature request related to a problem? Please describe**

I would like to render all my stories in strict mode, to anticipate this mode becoming the default in React.

**Describe the solution you'd like**

I have noticed the global env `XSTORYBOOK_EXAMPLE_APP` but it seems to be private. It's not documented.

**Describe alternatives you've considered**

 Next.js offers interesting options: https://nextjs.org/docs/api-reference/next.config.js/react-strict-mode.

> We strongly suggest you enable Strict Mode in your Next.js application to better prepare your application for the future of React.

**Additional context**

StrictMode is enabled by default in Create React App. I'm opening the issue because we go [a bug reported](https://github.com/mui-org/material-ui-x/issues/177) linked to our workflow where we don't have StrictMode enabled.

**Comment by shilman** [comment]
@oliviertassinari this should be an easy one and worthwhile. PRs welcome and if nothing comes in I'll try to make sure it happens for 6.1.

**Comment by imshubhamsingh** [comment]
Hey @shilman I would like to give it a shot.

**Comment by shilman** [comment]
@imshubhamsingh ok I'm thinking we should add it as an option to `.storybook/main.js`:

```js
module.exports = {
  reactOptions: {
    strictMode: true,
  }
}
```

Like we do for `fastRefresh`: https://github.com/storybookjs/storybook/blob/next/app/react/src/server/types.ts#L6-L11

Is that enough to get you started?

**Comment by imshubhamsingh** [comment]
yeah. This will help. Thanks ✌️, If I have any doubt I'll reach out here or on discord server.

**Comment by imshubhamsingh** [comment]
@shilman I see @tooppaaa has already submitted the PR for this. Please assign the PR to the respective individual so that two people are not working on the same thing at once. Thank you for your time.

**Comment by tooppaaa** [comment]
@imshubhamsingh ohhh I'm so sorry I didn't saw your messages in this issue..

**Comment by imshubhamsingh** [comment]
@tooppaaa no worries. I would request you sincerely that you don't repeat such mistake with others. People put in a lot of effort and time understanding the issue and try to solve it (as you would also have).

**Comment by shilman** [comment]
Huzzah!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.0-alpha.25 containing PR #12781 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Apologies @imshubhamsingh !

**Comment by oliviertassinari** [comment]
Great :)

**Comment by shilman** [comment]
Son of a gun!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.0-alpha.27 containing PR #12810 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

**Comment by shilman** [comment]
Gadzooks!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.0 containing PR #12781 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```
