### ISSUE TITLE
Decorators: Protect id, name, kind and other "core" metadata

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#12737]
_Originally posted by @tmeasday in https://github.com/storybookjs/storybook/pull/12699#discussion_r503046231_

Currently the decorator code disallows the user from overwriting story `parameters` in the story context. This should be updated to include other core metadata including:

```
  id,
  kind,
  name,
  story,
```

**Comment by winnayx** [comment]
I could take a look at this

**Comment by shilman** [comment]
that'd be awesome @winnayx

**Comment by adagar** [comment]
It doesn't seem like this was assigned nor progressed since October. Does it still need support? I could take a crack at it!

**Comment by tmeasday** [comment]
Sure thing @adagar

**Comment by adagar** [comment]
hey @tmeasday thanks for the response, but I'm digging into a different ticket; this one is still up for grabs!

**Comment by apapadopoulou** [comment]
Is this issue still open? A pull request is mentioned above so it is not clear to me whether someone is working on this.

**Comment by shilman** [comment]
Still open. If you're interested in helping please consider reviewing the PR mentioned above. We'll get it merged in SB 7.0 because it's technically a breaking change.

**Comment by apapadopoulou** [comment]
Thank you, I will start off from there!

**Comment by shilman** [comment]
Yay!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.3.0-alpha.17 containing PR #13512 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
