### ISSUE TITLE
The docpage props table can't display when use react and typescript

### ISSUE THREAD

**Issue by gyq348097872** [storybookjs/storybook#12742]
**Describe the bug**
I write the .mdx using react and typescript, and  [babel-plugin-react-docgen-typescript](https://www.npmjs.com/package/babel-plugin-react-docgen-typescript); but the props table in the docpage dit not display, how can I make it display correctly? 
(addition: when I use Class Component or Function Expression , the mistake shows. But when I try to change my coponent to  Function Declaration, it works. So confusing )

**Screenshots**

using Class Component or Function Expression
<img width="1088" alt="截屏2020-10-12 19 45 08" src="https://user-images.githubusercontent.com/24505486/95743867-03fdfe00-0cc5-11eb-88b7-36b6f1d6f389.png">

Function Declaration
<img width="998" alt="截屏2020-10-12 20 00 11" src="https://user-images.githubusercontent.com/24505486/95744216-943c4300-0cc5-11eb-9c65-c9087e297d4a.png">

**Code snippets**
.babelrc.js
``` javascript
module.exports = {
  plugins: [
    'babel-plugin-react-docgen-typescript',
  ],
};
```

storybook main.js
``` javascript
module.exports = {
  stories,
  addons: ['@storybook/addon-viewport/register', '@storybook/addon-storysource', '@storybook/addon-docs', '@storybook/addon-actions'],
  webpackFinal: async (config) => {
    // Make whatever fine-grained changes you need
    config.module.rules.push({
      test: /\.[tj]sx?$/,
      use: ['babel-loader'],
    });

    config.resolve.extensions.push('.ts', '.tsx', '.mdx');

    // Return the altered config
    return config;
  },
};
```
.mdx 
``` javascript
import { Meta, Story, Props } from '@storybook/addon-docs/blocks';
import Component from './index';

<Meta title="Documents|Component" component={Component} />

# QMScrollLoadMore

## Props

<Props of={Component} />
```

**System**
``` javascript
Environment Info:

  System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 12.18.4 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.6 - /usr/local/bin/npm
  Browsers:
    Chrome: 86.0.4240.75
    Firefox: 81.0
    Safari: 14.0
  npmPackages:
    @storybook/addon-actions: ^5.3.18 => 5.3.18 
    @storybook/addon-console: ^1.2.1 => 1.2.1 
    @storybook/addon-docs: ^5.3.14 => 5.3.18 
    @storybook/addon-storysource: ^5.3.18 => 5.3.18 
    @storybook/addon-viewport: ^5.3.14 => 5.3.18 
    @storybook/preset-create-react-app: ^3.1.4 => 3.1.4 
    @storybook/react: ^5.3.14 => 5.3.18 
    @storybook/theming: ^5.3.18 => 5.3.18 
```

**Additional context**

**Comment by shilman** [comment]
what was the solution?

**Comment by gyq348097872** [comment]
> what was the solution?

I found a similar issue, [#8428](https://github.com/storybookjs/storybook/issues/8428). I tried to add
` import React, { Component from 'react';`

and change 
`class component extends React.Component` to `class component extends Component`

It works
