### ISSUE TITLE
Feature: Add ability to display informational texts in Knobs addon

### ISSUE THREAD

**Issue by Knagis** [storybookjs/storybook#1274]
For example, we might want to add some descriptive text informing the user what values should be set in certain scenarios.

Perhaps something like `readonly("Important", "Read this text before changing the value of any knob")`.

**Comment by Gongreg** [comment]
@Knagis ,

Hey, what about using description addon for that? Or that wouldn't work for you?

**Comment by Knagis** [comment]
@Gongreg Did you mean the `notes` addon? I don't see anything named `description` in this repo. It can be used however in our case we would like to have something that can be seen together with a certain knob - basically some instructions or warnings related to a knob.

Very specifically - we have a checkbox (boolean knob) that is handled in a very special way - we want to add instruction next to the checkbox that instructs the person who uses it what other actions must be taken in order for the checkbox to take effect (in our case - reload the page).

**Comment by Gongreg** [comment]
Oh okay.

So I think one solution would be to add this functionality or storybook functionality to be able to show multiple panels at once.

Maybe you could do a small example of how this description could look like? I mean a picture or something like that :)

**Comment by shilman** [comment]
@gongreg awesome. I'm very interested in this direction both for panels and for stories

**Comment by Knagis** [comment]
There are many different ways - one might be adding a "?" icon that show the description on tooltip:

![image](https://user-images.githubusercontent.com/8700285/27239395-60f3bc02-52d9-11e7-8d66-bb1572faf2fa.png)

**Comment by bbecker-te** [comment]
Its too bad this was closed. It would be nice if once could add tooltip text to knobs. Can we just reopen this instead of creating a new issue and linking?

**Comment by Gongreg** [comment]
@bbecker-te, I've reopened it. It would be great if you could create a PR for it :)

**Comment by lukaszrys** [comment]
I second that, it would be really nice to have an ability to add tooltip

**Comment by ananta-dev** [comment]
I agree it would be nice to be able to add some explanatory text next to the knob fields.
For example: "_enter negative value in days to create a past date_"
