### ISSUE TITLE
Support @deprecated jsdoc tag

### ISSUE THREAD

**Issue by StJohn3D** [storybookjs/storybook#12759]
**Is your feature request related to a problem? Please describe**
In my component's props TS interface, I can use JSDoc comments to set the description, and can even use the `@default` tag to describe the default value 💯 
However, nothing happens when I use the [`@deprecated`](https://jsdoc.app/tags-deprecated.html) tag.

**Describe the solution you'd like**
Some ideas:
 - It would be nice if the parent `<tr>` got `required` and `deprecated` classesNames e.g. `<tr className="required">` & `<tr className="deprecated">` so that I can easily apply custom styling to these rows.
 - For deprecated props,  it would be nice if the prop name appeared grayed out, and the word **Deprecated** appeared in bold below it, followed by any description. e.g.
    > _**PropName**_
    > **Deprecated** since version 2.0

**Describe alternatives you've considered**
For now I will simply omit deprecated props manually per story via the meta default export's parameters.
`parameters.docs.page.excludeProps = ['my_depricated_prop_name']`

**Are you able to assist to bring the feature to reality?**
Perhaps in the future but not at this time.

**Additional context**
https://jsdoc.app/tags-deprecated.html

**Comment by kraken-coder** [comment]
Hi, Can i dig into this?

**Comment by shilman** [comment]
@kraken-coder yes please! assigned 🚀

**Comment by mailinh19** [comment]
Very good solution already. Your topic is very good. thank you very much!
https://sudoku247.co

**Comment by leticiavna** [comment]
Hi, I would like to try to fix this issue, but I see someone else already is assigned. Can I try it out still or should I look for another one? Also, is this still a issue, since its from last year?

**Comment by shilman** [comment]
@leticiavna please do! 🙏

**Comment by probablyup** [comment]
If you're interested in fixing this, the root is https://github.com/storybookjs/storybook/blob/main/lib/docs-tools/src/argTypes/jsdocParser.ts#L1. The package "doctrine" used to parse JSDoc tags is abandonware. Will need to switch to something else and update the storybook-side handling to whatever the new AST looks like.

**Comment by probablyup** [comment]
Related: https://github.com/storybookjs/storybook/issues/17458

**Comment by Seminioni** [comment]
What's up guys? Let's finish PR

**Comment by shilman** [comment]
Gadzooks!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.30 containing PR #20154 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Olé!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-rc.9 containing PR #21794 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```
