### ISSUE TITLE
Storybook NPM 

### ISSUE THREAD

**Issue by JohnCasab** [storybookjs/storybook#12751]
Hello Storybook community, 

I have started using Storybook, and the plan is to have Vue, Angular, and React components that my organisation can reuse.

What I want is to be able make these components to npm packages by them self and a large npm package for all Vue, Angular and React components.

I cant really find anything in the documentation beside this page: 
https://www.learnstorybook.com/design-systems-for-developers/react/en/distribute/ 

Cant really find anything relevant on this, page. 

So im not sure it's possible, if its is there any reference, link or anybody that can explain how it can be achieved?

Thank you very much

**Comment by shilman** [comment]
On the storybook side, we support multiple frameworks using composition: https://storybook.js.org/docs/react/workflows/storybook-composition

On the NPM side, we don't really do anything to help you publish your components per se. You could create an NPM package for each framework and then create a fourth package that imports all of those components and re-exports them (tho I'm not sure that's a good idea -- what's wrong with just having three separate packages?)

**Comment by JohnCasab** [comment]
@shilman Thank you for your answer. 

The plan is having 3 packages(Vue, Angular, and React), but would be nice also if some of the more reusable components could be packages using npm or something else.

**Comment by franktopel** [comment]
> I have started using Storybook, and the plan is to have Vue, Angular, and React components that my organisation can reuse.

You might want to consider switching to framework-agnostic web components.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
