### ISSUE TITLE
Official svelte typescript support

### ISSUE THREAD

**Issue by soullivaneuh** [storybookjs/storybook#12754]
As Svelte [does now officially support the typescript language](https://svelte.dev/blog/svelte-and-typescript),
I decided to do the migration by following the linked official guide.

Unfortunately, this creates a crash issue on storybook launch (`npm run storybook`):

```
ERROR in ./src/components/Copy.svelte
Module build failed (from ./node_modules/svelte-loader/index.js):
Error: ParseError: Unexpected token (4:20)
2:   import { createEventDispatcher } from 'svelte';
3: 
4:   export let content: string;
                       ^
5:   export let showContent: boolean = true;
6:   export let title: string = 'Copy content';
    at /home/sullivan/p/gitlab.com/nexylan/svelty/node_modules/svelte-loader/index.js:181:12
 @ ./src/components/Copy.stories.js 65:0-33 69:13-17 73:15-19 98:15-19
 @ ./src/components sync ^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.js)$
 @ ./.storybook/generated-stories-entry.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/storybook-init-framework-entry.js ./node_modules/@storybook/addon-docs/dist/frameworks/common/config.js-generated-other-entry.js ./node_modules/@storybook/addon-actions/dist/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-actions/dist/preset/addArgs.js-generated-other-entry.js ./node_modules/@storybook/addon-backgrounds/dist/preset/defaultParameters.js-generated-other-entry.js ./node_modules/@storybook/addon-a11y/dist/a11yRunner.js-generated-other-entry.js ./node_modules/@storybook/addon-a11y/dist/a11yHighlight.js-generated-other-entry.js ./.storybook/preview.js-generated-config-entry.js ./.storybook/generated-stories-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined
```

It looks like Storybook is not going to interpret typescript as it should.

Maybe I have to change some configuration for Storybook, but I can't found anything about this on the documentation and the issues.

Does Storybook support Svelte with Typescript?

You may test the issue by cloning this branch: https://gitlab.com/nexylan/svelty/-/merge_requests/67

**Comment by soullivaneuh** [comment]
I was able to reproduce with a blank installation:

1. Setup a new svelte project and convert it to typescript following the [blog post](https://svelte.dev/blog/svelte-and-typescript#Try_it_now):

```
npx degit sveltejs/template svelte-typescript-app
cd svelte-typescript-app
node scripts/setupTypeScript.js
```

2. Install storybook following the [official guide]():

```
npx -p @storybook/cli sb init --type svelte
```

3. Edit one story component to add some typescript:

```svelte
<script lang="ts">
  import './button.css';
  import { createEventDispatcher } from 'svelte';
  /**
   * Is this the principal call to action on the page?
   */
  export let primary: boolean = false;

  /**
   * What background color to use
   */
  export let backgroundColor;
  /**
   * How large should the button be?
   */
  export let size = 'medium';
  /**
   * Button contents
   */
  export let label = '';

  let mode = primary ? 'storybook-button--primary' : 'storybook-button--secondary';

  let style = backgroundColor ? `background-color: ${backgroundColor}` : '';

  const dispatch = createEventDispatcher();

  /**
   * Optional click handler
   */
  function onClick(event) {
    dispatch('click', event);
  }
</script>

<button
  type="button"
  class={['storybook-button', `storybook-button--${size}`, mode].join(' ')}
  {style}
  on:click={onClick}>
  {label}
</button>
```

And run `npm run storybook`: Badaboum.

**Comment by ritchieanesco** [comment]
+1. Can also replicate. Guess will need svelte preprocessor to translate to javascript first.

**Comment by ritchieanesco** [comment]
@soullivaneuh  this seemed to work for me.

```js

// .storybook/main.js

module.exports = {
  webpackFinal: async  (config) => {
    const svelteLoader = config.module.rules.find(
      (r) => r.loader && r.loader.includes("svelte-loader"),
    )
    svelteLoader.options.preprocess = require("svelte-preprocess")({})
    return config
  },
  stories: ["../src/**/*.stories.mdx", "../src/**/*.stories.@(js|jsx|ts|tsx)"],
  addons: ["@storybook/addon-links", "@storybook/addon-essentials"],
}
```

**Comment by soullivaneuh** [comment]
@ritchieanesco I took the `webpackFinal` part of your example and this works for me too, thanks!

I suppose adding the `svelte-preprocess` to the storybook configuration as default would solve many issue for svelte integration.

**Comment by soullivaneuh** [comment]
@ritchieanesco Hmm... this is working to launch the storybook but not for the tests:

```
 FAIL  src/components/Copy.test.js
  ● Test suite failed to run

    ParseError: Unexpected token

      at error (node_modules/svelte/src/compiler/utils/error.ts:25:16)
      at Parser$1.error (node_modules/svelte/src/compiler/parse/index.ts:100:3)
      at Parser$1.acorn_error (node_modules/svelte/src/compiler/parse/index.ts:93:8)
      at Object.read_script [as read] (node_modules/svelte/src/compiler/parse/read/script.ts:49:10)
      at tag (node_modules/svelte/src/compiler/parse/state/tag.ts:203:27)
      at new Parser$1 (node_modules/svelte/src/compiler/parse/index.ts:52:12)
      at parse (node_modules/svelte/src/compiler/parse/index.ts:215:17)
      at Object.compile (node_modules/svelte/src/compiler/compile/index.ts:78:14)
      at Object.process (node_modules/jest-transform-svelte/index.js:26:26)
      at ScriptTransformer.transformSource (node_modules/@jest/transform/build/ScriptTransformer.js:463:35)

 PASS  src/storybook.test.js
  ● Console

    console.warn
      Unexpected error: Unexpected token (4:20)
      2:   import { createEventDispatcher } from 'svelte';
      3: 
      4:   export let content: string;
                             ^
      5:   export let showContent: boolean = true;
      6:   export let title: string = 'Copy content';

      at Object.warn (node_modules/@storybook/client-logger/dist/index.js:53:73)
      at node_modules/@storybook/core/dist/client/preview/loadCsf.js:149:34
          at Array.forEach (<anonymous>)
      at node_modules/@storybook/core/dist/client/preview/loadCsf.js:142:20
          at Array.forEach (<anonymous>)
      at node_modules/@storybook/core/dist/client/preview/loadCsf.js:141:12
      at ConfigApi.configure (node_modules/@storybook/client-api/dist/config_api.js:26:7)
      at node_modules/@storybook/core/dist/client/preview/loadCsf.js:326:17
```

Content of `storybook.test.js`:

```javascript
import initStoryshots from '@storybook/addon-storyshots';

initStoryshots();
```

Content of `Copy.test.js`

```javascript
import { render } from '@testing-library/svelte';
import Copy from './Copy.svelte';

test('Copy ', async () => {
  const { container } = await render(Copy, {
    props: {
      content: 'test-copy',
    },
  });
  expect(container.innerHTML.includes('test-copy')).toBe(true);
});
```

Note: The `Copy.test.js` is not related to storybook, but we have the same message as a warning from the storybook test file.

**Comment by ritchieanesco** [comment]
@soullivaneuh check out **svelte jester** and how it uses transforms to run svelte preprocessor

**Comment by jerriclynsjohn** [comment]
> @soullivaneuh this seemed to work for me.
> 
> ```js
> // .storybook/main.js
> 
> module.exports = {
>   webpackFinal: async  (config) => {
>     const svelteLoader = config.module.rules.find(
>       (r) => r.loader && r.loader.includes("svelte-loader"),
>     )
>     svelteLoader.options.preprocess = require("svelte-preprocess")({})
>     return config
>   },
>   stories: ["../src/**/*.stories.mdx", "../src/**/*.stories.@(js|jsx|ts|tsx)"],
>   addons: ["@storybook/addon-links", "@storybook/addon-essentials"],
> }
> ```

Tried this but doesn't work. These are my files

```js
const sveltePreprocess = require('svelte-preprocess');

module.exports = {
    webpackFinal: async config => {
        const svelteLoader = config.module.rules.find(
            r => r.loader && r.loader.includes('svelte-loader'),
        );
        svelteLoader.options = {
            ...svelteLoader.options,
            preprocess: sveltePreprocess({postcss: true}),
        };
        return config;
    },
    stories: [
        '../src/components/**/*.stories.mdx',
        '../src/components/**/*.stories.@(js|jsx|ts|tsx)',
    ],
    addons: ['@storybook/addon-links', '@storybook/addon-essentials'],
};
```

and when you add `export let name: string;` to your svelte component it compiles but can see this in the build messages `SyntaxError: Unexpected token`. This happens right after this in the messages

```bash
68% building 762/782 modules 20 active ...t\WebApp\node_modules\.pnpm\@storybook\addon-docs@6.1.11_72f69c7c8e83b0f7c89a3c7ca1e66c88\node_modules\@storybook\addon-docs\dist\blocks\DocsContainer.js
```

**Comment by kulturbande** [comment]
I can start storybook, but it is resulting a huge amount of error messages during the build:
```bash
68% building 806/826 modules 20 active /project/node_modules/@emotion/is-prop-valid/dist/is-prop-valid.browser.esm.jsSyntaxError: Unexpected token :
    at Espree.raise (/project/node_modules/sveltedoc-parser/node_modules/espree/lib/espree.js:190:25)
    at Espree.unexpected (/project/node_modules/sveltedoc-parser/node_modules/espree/lib/espree.js:235:18)
    at Espree.pp.semicolon (/project/node_modules/acorn/dist/acorn.js:675:66)
    at Espree.pp$1.parseVarStatement (/project/node_modules/acorn/dist/acorn.js:1102:10)
    at Espree.pp$1.parseStatement (/project/node_modules/acorn/dist/acorn.js:851:19)
    at Espree.pp$1.parseExport (/project/node_modules/acorn/dist/acorn.js:1458:31)
    at Espree.pp$1.parseStatement (/project/node_modules/acorn/dist/acorn.js:872:74)
    at Espree.pp$1.parseTopLevel (/project/node_modules/acorn/dist/acorn.js:755:23)
    at Espree.parseTopLevel (/project/node_modules/sveltedoc-parser/node_modules/espree/lib/espree.js:178:26)
    at Espree.parse (/project/node_modules/acorn/dist/acorn.js:555:17)
    at Espree.parse (/project/node_modules/sveltedoc-parser/node_modules/espree/lib/espree.js:144:35)
    at Object.parse (/project/node_modules/sveltedoc-parser/node_modules/espree/espree.js:134:38)
    at Parser.parseScriptBlock (/project/node_modules/sveltedoc-parser/lib/v3/parser.js:551:28)
    at /project/node_modules/sveltedoc-parser/lib/v3/parser.js:72:22
    at Array.forEach (<anonymous>)
    at Parser.__walk (/project/node_modules/sveltedoc-parser/lib/v3/parser.js:71:36) {
  index: 125,
  lineNumber: 6,
  column: 27
}
```
It worked without any error on storybook 6.0.28. Since 6.1.x it is broken, and I havn't found the issue.

**Comment by sidharthramesh** [comment]
> I can start storybook, but it is resulting a huge amount of error messages during the build:
> 
> ```shell
> 68% building 806/826 modules 20 active /project/node_modules/@emotion/is-prop-valid/dist/is-prop-valid.browser.esm.jsSyntaxError: Unexpected token :
>     at Espree.raise (/project/node_modules/sveltedoc-parser/node_modules/espree/lib/espree.js:190:25)
>     at Espree.unexpected (/project/node_modules/sveltedoc-parser/node_modules/espree/lib/espree.js:235:18)
>     at Espree.pp.semicolon (/project/node_modules/acorn/dist/acorn.js:675:66)
>     at Espree.pp$1.parseVarStatement (/project/node_modules/acorn/dist/acorn.js:1102:10)
>     at Espree.pp$1.parseStatement (/project/node_modules/acorn/dist/acorn.js:851:19)
>     at Espree.pp$1.parseExport (/project/node_modules/acorn/dist/acorn.js:1458:31)
>     at Espree.pp$1.parseStatement (/project/node_modules/acorn/dist/acorn.js:872:74)
>     at Espree.pp$1.parseTopLevel (/project/node_modules/acorn/dist/acorn.js:755:23)
>     at Espree.parseTopLevel (/project/node_modules/sveltedoc-parser/node_modules/espree/lib/espree.js:178:26)
>     at Espree.parse (/project/node_modules/acorn/dist/acorn.js:555:17)
>     at Espree.parse (/project/node_modules/sveltedoc-parser/node_modules/espree/lib/espree.js:144:35)
>     at Object.parse (/project/node_modules/sveltedoc-parser/node_modules/espree/espree.js:134:38)
>     at Parser.parseScriptBlock (/project/node_modules/sveltedoc-parser/lib/v3/parser.js:551:28)
>     at /project/node_modules/sveltedoc-parser/lib/v3/parser.js:72:22
>     at Array.forEach (<anonymous>)
>     at Parser.__walk (/project/node_modules/sveltedoc-parser/lib/v3/parser.js:71:36) {
>   index: 125,
>   lineNumber: 6,
>   column: 27
> }
> ```
> 
> It worked without any error on storybook 6.0.28. Since 6.1.x it is broken, and I havn't found the issue.

I have the same issue. Everything works, but the errors still show up on the console.

**Comment by oahehc** [comment]
> > I can start storybook, but it is resulting a huge amount of error messages during the build:
> > ```shell
> > 68% building 806/826 modules 20 active /project/node_modules/@emotion/is-prop-valid/dist/is-prop-valid.browser.esm.jsSyntaxError: Unexpected token :
> >     at Espree.raise (/project/node_modules/sveltedoc-parser/node_modules/espree/lib/espree.js:190:25)
> >     at Espree.unexpected (/project/node_modules/sveltedoc-parser/node_modules/espree/lib/espree.js:235:18)
> >     at Espree.pp.semicolon (/project/node_modules/acorn/dist/acorn.js:675:66)
> >     at Espree.pp$1.parseVarStatement (/project/node_modules/acorn/dist/acorn.js:1102:10)
> >     at Espree.pp$1.parseStatement (/project/node_modules/acorn/dist/acorn.js:851:19)
> >     at Espree.pp$1.parseExport (/project/node_modules/acorn/dist/acorn.js:1458:31)
> >     at Espree.pp$1.parseStatement (/project/node_modules/acorn/dist/acorn.js:872:74)
> >     at Espree.pp$1.parseTopLevel (/project/node_modules/acorn/dist/acorn.js:755:23)
> >     at Espree.parseTopLevel (/project/node_modules/sveltedoc-parser/node_modules/espree/lib/espree.js:178:26)
> >     at Espree.parse (/project/node_modules/acorn/dist/acorn.js:555:17)
> >     at Espree.parse (/project/node_modules/sveltedoc-parser/node_modules/espree/lib/espree.js:144:35)
> >     at Object.parse (/project/node_modules/sveltedoc-parser/node_modules/espree/espree.js:134:38)
> >     at Parser.parseScriptBlock (/project/node_modules/sveltedoc-parser/lib/v3/parser.js:551:28)
> >     at /project/node_modules/sveltedoc-parser/lib/v3/parser.js:72:22
> >     at Array.forEach (<anonymous>)
> >     at Parser.__walk (/project/node_modules/sveltedoc-parser/lib/v3/parser.js:71:36) {
> >   index: 125,
> >   lineNumber: 6,
> >   column: 27
> > }
> > ```
> > 
> > 
> > It worked without any error on storybook 6.0.28. Since 6.1.x it is broken, and I havn't found the issue.
> 
> I have the same issue. Everything works, but the errors still show up on the console.

I have faced a similar error. In my project, it is caused by this line.
```
const arr = new Set<number>([]);
```
Hope the information helpful.

**Comment by ritchieanesco** [comment]
Yeh, looks like the storybook team changed some things around, primarily moving docgen after compilation which @oahehc has referred to. From my understanding, the svelte preprocess has transpiled svelte code therefore breaking svelte-docgen. 

As i'm not using the doc gen feature i've simply removed it from the webpack config... Here's what i did:

```js
module.exports = {
  webpackFinal: async (config) => {
    
   // add preprocess to transpile typescript
    const svelteLoader = config.module.rules.find(
      (r) => r.loader && r.loader.includes("svelte-loader"),
    )
    svelteLoader.options.preprocess = sveltePreprocess({})
    
    // remove docgen 
    const svelteDocGenIndex = config.module.rules.findIndex(
      (r) => r.loader && r.loader.includes("svelte-docgen-loader"),
    )
    config.module.rules.splice(svelteDocGenIndex, 1)
    return config
    },
 }
```

Please note that this is a **hack**, and just a workaround until typescript is supported.

**Comment by j3rem1e** [comment]
You're right, the docgen loader is configured to postprocess the svelte file, but it reads the original file.
svelte-doc-gen doesn't support yet typescript or preprocessor, I assume it fails because of that.

I don't use TS myself but I can try to see how to use svelte preprocessor into the storybook build config.

**Comment by ritchieanesco** [comment]
@j3rem1e that would help a lot, as TS seems to be gaining lots of traction since it’s integration into svelte last may.

**Comment by LBrian** [comment]
> Yeh, looks like the storybook team changed some things around, primarily moving docgen after compilation which @oahehc has referred to. From my understanding, the svelte preprocess has transpiled svelte code therefore breaking svelte-docgen.
> 
> As i'm not using the doc gen feature i've simply removed it from the webpack config... Here's what i did:
> 
> ```js
> module.exports = {
>   webpackFinal: async (config) => {
>     
>    // add preprocess to transpile typescript
>     const svelteLoader = config.module.rules.find(
>       (r) => r.loader && r.loader.includes("svelte-loader"),
>     )
>     svelteLoader.options.preprocess = sveltePreprocess({})
>     
>     // remove docgen 
>     const svelteDocGenIndex = config.module.rules.findIndex(
>       (r) => r.loader && r.loader.includes("svelte-docgen-loader"),
>     )
>     config.module.rules.splice(svelteDocGenIndex, 1)
>     return config
>     },
>  }
> ```
> 
> Please note that this is a **hack**, and just a workaround until typescript is supported.

Same here, I created a separated issue to follow up https://github.com/storybookjs/storybook/issues/13902

**Comment by shilman** [comment]
Yee-haw!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.0-alpha.27 containing PR #13900 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

**Comment by ritchieanesco** [comment]
Great work guys! Will test it out shortly

**Comment by LBrian** [comment]
> Yee-haw!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.0-alpha.27 containing PR #13900 that references this issue. Upgrade today to the `@next` NPM tag to try it out!
> 
> ```
> npx sb upgrade --prerelease
> ```

AWESOME 🎉  can confirm working perfectly

**Comment by ritchieanesco** [comment]
@LBrian @j3rem1e  I've installed this pre-release version on a current project and I was getting parse errors from svelte loader trying to process the typescript. So i tried again with a clean slate and I am still getting the same issues. Here are my steps:
1. Install new svelte project
```
npx degit sveltejs/template my-svelte-project
```
2. Enable Typescript
```
node scripts/setupTypeScript.js
 ```
 3. Install storybook
 ```
 npx sb install
 ```
 4. Upgrade storybook
 ```
 npx sb upgrade --prerelease
 ```
 5. Add a type to src/storiesButton.svelte 
 ```ts
 export let primary: boolean = false; //line 7
 ```
 6. Run storybook
 
**Expected:** 
Storybook initialises with Svelte and Typescript

**Actual:**
```
ERROR in ./src/stories/Button.svelte
Module build failed (from ./node_modules/svelte-loader/index.js):
Error: ParseError: Unexpected token (7:20)
 5:    * Is this the principal call to action on the page?
 6:    */
 7:   export let primary: boolean = false;
                        ^
 8: 
 9:   /**
    at /Users/anescor/Sites/svelte-storybook/node_modules/svelte-loader/index.js:75:12
    ```
This is a fresh install and using everything out of the box, so there are no configuration changes in storybook/main.js. @LBrian  are you able to share your config?

**Comment by j3rem1e** [comment]
You need to : 

- Add a svelteOptions.preprocessor options in .storybook/main.js, please see the svelte-kitchen-sink as an example
- Add `lang=ts`  in the script tag of a component using typescript

**Comment by ritchieanesco** [comment]
Thanks @j3rem1e! Yep, tried it on the new setup and current project and can confirm that its working.

**Comment by shilman** [comment]
@j3rem1e 

> Add a svelteOptions.preprocessor options in .storybook/main.js
> Add lang=ts in the script tag of a component using typescript

should we make this the default generated by `sb init`? easier for people to opt-out rather than figuring this out on their own?

**Comment by j3rem1e** [comment]
The default project template generates a project without typescript. I don't know a library of components which use TS, and I don't use it myself. I don't think it's a good idea to enable by default typescript/preprocessors, but it's a matter a taste.

It should be however documented somewhere, but I don't know if there is a way to add a section specific to a framework in the documentation.

**Comment by sidharthramesh** [comment]
Is it possible to detect a typescript project and then change the default
behaviour? For example by looking at the rollup config and seeing if
svelte-preprocess is present or not. Also, making typescript default is
still compatible with projects using plain javascript right?

**Comment by shilman** [comment]
> It should be however documented somewhere, but I don't know if there is a way to add a section specific to a framework in the documentation.

There is for code snippets. I'm not so sure about the state of the art on docs sections. cc @jonniebigodes

**Comment by ritchieanesco** [comment]
Would it make sense having this documented in the svelte README [here](https://github.com/storybookjs/storybook/tree/master/app/svelte)?

**Comment by jonniebigodes** [comment]
@j3rem1e I'm going to push a pull request later today (Saturday) that among other things focus on this issue. In the Install section (Troubleshooting) should contain some reference to this and of course the README as well.

**Comment by frederikhors** [comment]
> You need to :
> 
> * Add a svelteOptions.preprocessor options in .storybook/main.js, please see the svelte-kitchen-sink as an example
> * Add `lang=ts`  in the script tag of a component using typescript

Are you referring to https://github.com/storybookjs/storybook/blob/master/examples/svelte-kitchen-sink/.storybook/main.js?

I do not see any `svelteOptions.preprocessor` there.

@jonniebigodes did you forget to push? 🤣

**Comment by j3rem1e** [comment]
It's in v6.2, in the next branch : https://github.com/storybookjs/storybook/blob/next/examples/svelte-kitchen-sink/.storybook/main.js

**Comment by shilman** [comment]
to upgrade:

```
npx sb@next upgrade --prerelease
```
