### ISSUE TITLE
Svelte component prop and description inference

### ISSUE THREAD

**Issue by seaneking** [storybookjs/storybook#12760]
**Is your feature request related to a problem? Please describe**
I couldn't find an issue tracking this, but there's currently no support for inferring props/arg and descriptions from Svelte components through the `component` field in CSF stories.

**Describe the solution you'd like**
Storybook should infer exported props and their types (if supplied with typescript) from Svelte components. I'm not sure how Storybook does its props inference, but I imagine it should be possible to parse `.svelte` components for their unique `export let` syntax for props.

**Describe alternatives you've considered**
It's possible to define your own props table with `argTypes`, but it's very cumbersome, especially when already using Typescript and JSDoc style comments in the actual component, to duplicate everything for storybook.

**Are you able to assist to bring the feature to reality?**
I don't think so, I have no idea how Storybook infers props currently. But I'd be happy to help however possible.

**Additional context**
N/A

**Comment by shilman** [comment]
@seaneking I believe that was added by @BlackFenix2 here https://github.com/storybookjs/storybook/pull/12347

**Comment by seaneking** [comment]
Amazing! Thanks I'll try it out
