### ISSUE TITLE
Storybook and a documentation site

### ISSUE THREAD

**Issue by JohnCasab** [storybookjs/storybook#12763]
Hi storybook community,

I have seen couple of examples such as this one: 

https://www.carbondesignsystem.com/components/button/usage 

It's a documentation site of some sort, I was wondering how are they building a website that looks very similar to the way storybook structured. 

Is this some feature storybook has or do they really build it from the bottom? 

I want now if there is some smart way of doing this, so I can apply the same technologies.

Thank you

**Comment by JohnCasab** [comment]
Anyone??

**Comment by shilman** [comment]
I believe it's built form scratch. They also use Storybook to develop their components, but I don't know if any code is shared between their stories and this custom site.

**Comment by tay1orjones** [comment]
The Carbon Design System website source is here: https://github.com/carbon-design-system/carbon-website/

It's built using Gatsby and [`gatsby-theme-carbon`](https://github.com/carbon-design-system/gatsby-theme-carbon)
