### ISSUE TITLE
ArgType defaultValue: 0 returns undefined

### ISSUE THREAD

**Issue by kiastorm** [storybookjs/storybook#12767]
**Describe the bug**

Consider the following code
```
View.argTypes = {
    zoom: {
        defaultValue: 0,
        control: { type: 'number' },
    }
}
```

If I then log the output of `args.zoom` in my story, it returns `undefined` (because it is falsey, I believe)

If I set the defaultValue to 1, when logged it returns `1`

**To Reproduce**

1 - Set argType default value to `0`
2 - Log output inside story

**Expected behavior**

`defaultValue: 0` 

`console.log(args.zoom)` // 0

Is this my own error or is it a bug?

**Comment by tmeasday** [comment]
Ok, I repro-ed this easily and the bug is quite clear on this line:

https://github.com/storybookjs/storybook/blob/60772cbbeb3507831b7f9ce01a2a5e814c03246f/lib/client-api/src/story_store.ts#L460:L460

**Comment by shilman** [comment]
¡Ay Caramba!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.0-alpha.30 containing PR #13919 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
