### ISSUE TITLE
yarn build-storybook creating infinite loop of folders

### ISSUE THREAD

**Issue by AntonioLobo** [storybookjs/storybook#12772]
Hey guys Im using react and when I try to run `yarn build-storybook -o public/storybook` this message appears:

```
info @storybook/react v6.0.26
info
info clean outputDir..
cp: copyFileSync: could not write to dest file (code=ENAMETOOLONG):/Users/felipebraga/atlas/public/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/storybook/manifest.json
cp: cannot create directory '/Users/felipebraga/atlas/public/storybook': No such file or directory
info => Copying static files from: public
info => Copying prebuild dll's..
info => Building manager..
info => Loading manager config..
info => Loading presets
info => Loading custom manager config.
WARN Expected '@storybook/addon-docs' (or essentials) to be listed before '@storybook/addon-controls'. Check your main.js?
WARN
WARN https://github.com/storybookjs/storybook/issues/11442
info => Compiling manager..
```

and then when I check public/storybook folder, there`s  a infinite loop of storybook folder:

![image](https://user-images.githubusercontent.com/52838813/96034282-a9d17a00-0e37-11eb-9479-759ec740409c.png)

I even tried to create the public/storybook folder manually before running the command, but the same thing happens, but when I try to run `yarn build-storybook -o public` it works good, anyone knows why this is happening?

**Settings**
    "@storybook/addon-controls": "^6.0.26",
    "@storybook/addon-docs": "^6.0.26",
    "@storybook/addon-actions": "^6.0.26",
    "@storybook/addon-links": "^6.0.26",
    "@storybook/addons": "^6.0.26",
    "@storybook/react": "^6.0.26",

**Comment by shilman** [comment]
In your `package.json` there's probably a line like this:

```
    "build-storybook": "build-storybook -s public"
```

This causes Storybook to do a deep copy of `public`. However, since you're also writing into `public`, this causes an infinite loop. This is probably a bug in Storybook and could be handled more gracefully, but the TLDR is that you shouldn't be both reading from the directory and writing to it at the same time. Hope that helps!
