### ISSUE TITLE
ES2020 syntax not recognized from import

### ISSUE THREAD

**Issue by cutterbl** [storybookjs/storybook#12778]
I [built a project](https://github.com/cutterbl/date-selector), and used Storybook while building the project. No problems.

I build `es` and `cjs` versions of this project, available via npm. It's intended as part of several larger projects, that I'm breaking down into smaller reusable components.

In project B (where I also use Storybook, to build in isolation), I installed the above package (Project A), and imported the component for use.

```js
import DateSelector from '@cxing/date-selector';
```

Storybook is now attempting to recompile, and pulls, by default, the `es` version, and immediately chokes.

```
Module parse failed: Unexpected token (41:16)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| }
| function getFirstDayOfWeek(fromDate) {
>   if (!fromDate?.isValid) return;
```

This is me using ES2020 optional chaining. While developing project A, Storybook had no issue handling this. But now that it's bundled and packaged, and in the `node_modules` of Project B, Storybook just dies out. (It should be noted that Project B also uses ES2020 syntax, in it's own components, with now issue)

**To Reproduce**

1. Create a simple story that outputs the `<DateSelector />` from `@cxing/date-selector`
2. start Storybook
3. See the console error

**Expected behavior**
I would expect that any third party es component, that I pull into my project, would be properly parsed and rendered.

**Code snippets**
```js
import DateSelector from '@cxing/date-selector';

export default MyComponent = () => <section><DateSelector /></section>;
```

**System**
```
Environment Info:

  System:
    OS: macOS Mojave 10.14.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Binaries:
    Node: 12.18.4 - ~/.nvm/versions/node/v12.18.4/bin/node
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.4/bin/npm
  Browsers:
    Chrome: 86.0.4240.80
    Edge: 86.0.622.38
    Firefox: 81.0.2
    Safari: 14.0
  npmPackages:
    @storybook/addon-actions: ^6.0.26 => 6.0.26 
    @storybook/addon-essentials: ^6.0.26 => 6.0.26 
    @storybook/addon-links: ^6.0.26 => 6.0.26 
    @storybook/node-logger: ^6.0.26 => 6.0.26 
    @storybook/preset-create-react-app: ^3.1.4 => 3.1.4 
    @storybook/react: ^6.0.26 => 6.0.26 
```

**Additional context**

**Comment by cutterbl** [comment]
I wasn't using the 'proposal' plugins in my babel config for project A. Still odd that everything just 'worked' in Storybook, in project A, but not in project B, but me adding those 'proposal' plugins resolved the issue overall.

**Comment by Emiliano-Bucci** [comment]
@cutterbl Hi! Sorry for the trouble but i really don't know where to look. I've also created a library that built for es, but when i try to import the library i've installed via npm, storybook dies with a similar loader error like yours.

This is the library -> https://www.npmjs.com/package/react-spring-carousel

I've also tried to use new babel but nothing, i just don't know where to look. Could you be so gentle, if you have time, to take a look? Thanks :)
