### ISSUE TITLE
Storybook broken with React 16.14.0

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#12787]
_Originally posted by @agrohs in https://github.com/storybookjs/storybook/issues/10009#issuecomment-709568885_:

Had everything working properly yesterday on alpha 23 and woke up this morn to all broken. Tried going back in commits and even everything running against 6.0.26 stable seems to be broken. Getting a very strange set of errors related to react hooks, but what's really bizarre about them is that the webpack'd debug stack seems to be showing URLs similar to: webpack://storybook_ui_dll//Users/shilman/projects/baseline/storybook/node_modules/react/cjs/react.development.js?:1439

This looks potentially related to the fact that storybook does not have pinned versions in its package.json AND a major new update of React went live yesterday (6.14.0) that has broken many projects across the web today: https://github.com/facebook/react/blob/master/CHANGELOG.md.

A similar issue of a dependency of a dependency wreaking havoc on a project happened several months back w/ `moment.js` b/c their versions were not pinned.

I was able to get this back resolved by adding a resolutions node in our projects `package.json` to ensure we don't use the upgraded version until working properly w all third parties:
```
  "resolutions": {
    "**/react": "16.13.1",
    "**/react-dom": "16.13.1",
    "**/react-is": "16.13.1"
  }
```
This will likely kill many hours for people today using `storybook` if it hasn't already. Just sharing to try and save some other people headache - but wondering in general why storybook does not have pinned versions in its package file??

**Comment by shilman** [comment]
For anybody who's experiencing this, does it help to run Storybook with the `--no-dll` flag?

**Comment by Breuls** [comment]
@shilman I was experiencing errors about "breaking the rules of hooks" in the browser console, and adding that flag helped me solve it.

**Comment by dkadrios** [comment]
Running into 
```
Module not found: Error: Can't resolve 'react/jsx-runtime.js'
```
This is happening in a custom addon that uses wrapper component from the main app that have had `import React from 'react'` removed.

I've tried updating storybooks `.babelrc` to be 
```
{
  "presets": [
    "@babel/preset-env",
    ["@babel/preset-react", {
      "runtime": "automatic",
    }],
  ],
```

Using the `--no-dll` flag has no effect on this error.

It's not clear to me why SB would be trying to use `react/jsx-runtime.js` when runtime is set to automatic.  Could there be competing copies of react and/or babel?

**Comment by nathanBrenner** [comment]
`--no-dll` doesn't help. My storybook config doesn't have a babel config. This seems like however storybook renders react components is using the past version of react.

**Comment by KarandikarMihir** [comment]
Stories are running just fine but storybook itself is using an older version of react and I don't know how to make storybook use latest react and jsx transform.

**Comment by mrlubos** [comment]
Same issue here, haven't upgraded to the newest React yet though. `--no-dll` flag helps fix it.

**Comment by platypusrex** [comment]
For those unable to resolve with `--no-dll` flag, I believe the below should do it.

main.js
```
const path = require('path');

module.exports = {
  ...rest of your config
  webpackFinal: async (config) => {
    config.resolve.alias = {
      'react': path.resolve(__dirname, '../node_modules/react'),
    };

    return config;
  },
};

**Comment by dkadrios** [comment]
Unfortunately for me it doesn't seem like the aliases are being applied to the final webpack config.  It executes the method and if I dump the config to console, I can see the aliases I've defined:
```
resolve: {
    extensions: [
      '.mjs', '.js',
      '.jsx', '.ts',
      '.tsx', '.json',
      '.cjs'
    ],
    modules: [ 'node_modules' ],
    alias: {
      '@emotion/core': '/Users/project-path/node_modules/@emotion/core',
      '@emotion/styled': '/Users/project-path/node_modules/@emotion/styled',
      'emotion-theming': '/Users/project-path/node_modules/emotion-theming',
      '@storybook/addons': '/Users/project-path/node_modules/@storybook/addons',
      '@storybook/api': '/Users/project-path/node_modules/@storybook/api',
      '@storybook/channels': '/Users/project-path/node_modules/@storybook/channels',
      '@storybook/channel-postmessage': '/Users/project-path/node_modules/@storybook/channel-postmessage',
      '@storybook/components': '/Users/project-path/node_modules/@storybook/components',
      '@storybook/core-events': '/Users/project-path/node_modules/@storybook/core-events',
      '@storybook/router': '/Users/project-path/node_modules/@storybook/router',
      '@storybook/theming': '/Users/project-path/node_modules/@storybook/theming',
      '@storybook/semver': '/Users/project-path/node_modules/@storybook/semver',
      '@storybook/client-api': '/Users/project-path/node_modules/@storybook/client-api',
      '@storybook/client-logger': '/Users/project-path/node_modules/@storybook/client-logger',
      react: '/Users/project-path/node_modules/react',
      'react-dom': '/Users/project-path/node_modules/react-dom',
      common: '/Users/project-path/src/components/common',
      components: '/Users/project-path/src/components',
      fp: '/Users/project-path/src/core/fp',
      core: '/Users/project-path/src/core',
      hoc: '/Users/project-path/src/hoc',
      hooks: '/Users/project-path/src/hooks',
      images: '/Users/project-path/src/images',
      locale: '/Users/project-path/src/locale',
      projections: '/Users/project-path/src/projections',
      reducers: '/Users/project-path/src/reducers',
      routing: '/Users/project-path/src/routing',
      sagas: '/Users/project-path/src/sagas',
      selectors: '/Users/project-path/src/selectors',
      styles: '/Users/project-path/src/styles',
      views: '/Users/project-path/src/views'
    },
}
```

The errors I receive are 
```
ERROR in ./.storybook/addons/themePicker/themePicker.js
Module not found: Error: Can't resolve 'hooks/useStorage' in '/Users/project-path/.storybook/addons/themePicker'
 @ ./.storybook/addons/themePicker/themePicker.js 5:0-42 26:2-12 76:158-168
 @ ./.storybook/addons/themePicker/register.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./.storybook/manager.js ./node_modules/@storybook/core/dist/client/manager/index.js @storybook/addon-a11y/register @storybook/addon-actions/register ./node_modules/@storybook/addon-docs/dist/register.js @storybook/addon-knobs/register @storybook/addon-links/register ./node_modules/@storybook/addon-storysource/register.js @storybook/addon-viewport/register storybook-addon-sketch/register ./.storybook/addons/themePicker/register.js ./.storybook/generated-refs.js

ERROR in ./.storybook/addons/themePicker/register.js
Module not found: Error: Can't resolve 'react/jsx-runtime.js' in '/Users/project-path/.storybook/addons/themePicker'
 @ ./.storybook/addons/themePicker/register.js 1:0-51
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./.storybook/manager.js ./node_modules/@storybook/core/dist/client/manager/index.js @storybook/addon-a11y/register @storybook/addon-actions/register ./node_modules/@storybook/addon-docs/dist/register.js @storybook/addon-knobs/register @storybook/addon-links/register ./node_modules/@storybook/addon-storysource/register.js @storybook/addon-viewport/register storybook-addon-sketch/register ./.storybook/addons/themePicker/register.js ./.storybook/generated-refs.js

ERROR in ./.storybook/addons/themePicker/themePicker.js
Module not found: Error: Can't resolve 'react/jsx-runtime.js' in '/Users/project-path/.storybook/addons/themePicker'
 @ ./.storybook/addons/themePicker/themePicker.js 1:66-119 1:119-170
 @ ./.storybook/addons/themePicker/register.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./.storybook/manager.js ./node_modules/@storybook/core/dist/client/manager/index.js @storybook/addon-a11y/register @storybook/addon-actions/register ./node_modules/@storybook/addon-docs/dist/register.js @storybook/addon-knobs/register @storybook/addon-links/register ./node_modules/@storybook/addon-storysource/register.js @storybook/addon-viewport/register storybook-addon-sketch/register ./.storybook/addons/themePicker/register.js ./.storybook/generated-refs.js
```

That first one is for an alias to our hooks folder and is like the canary in the coal mine.  If it can't resolve that one, I'm left to confirm that this webpack config is simply not being used.

The other two errors are related to webpack still using the copy of React from `node_modules/@storybook/react`, even though there's an alias to use the one from `node_modules/react/`

Note: storybook itself is working fine, it's only when I include my custom `themePicker` component that things go sideways.  This is an add-on that let's you pick one of our internal themes, and then alters the corresponding `ThemeProvider` that wraps the stories.  It appears to be this usage of code from the main project in an addon that causes the issue.  The stories alone work fine.

**Comment by shilman** [comment]
Closing as dupe to #12408
