### ISSUE TITLE
React console errors appear for every component in Storybook 6.1

### ISSUE THREAD

**Issue by kaiyoma** [storybookjs/storybook#12785]
**Describe the bug**
I tried upgrading from 6.0.26 to 6.1.0-alpha.24 and I'm now seeing lots of React errors in the console. This error message appears once per component:

```
Warning: unmountComponentAtNode(): The node you're attempting to unmount was rendered by another copy of React.
```

**To Reproduce**

1. Open any component
2. Check the console

**Expected behavior**
There shouldn't be any errors.

**System**
```
Environment Info:

  System:
    OS: Windows 10 10.0.19041
    CPU: (4) x64 Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
  Binaries:
    Node: 12.16.1 - C:\Program Files\Node.js\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.4 - C:\Program Files\Node.js\npm.CMD
  Browsers:
    Chrome: 86.0.4240.75
    Edge: Spartan (44.19041.423.0), Chromium (86.0.622.38)
  npmPackages:
    @storybook/addon-actions: 6.0.26 => 6.0.26
    @storybook/addon-knobs: 6.0.26 => 6.0.26
    @storybook/addons: 6.0.26 => 6.0.26
    @storybook/core: 6.0.26 => 6.0.26
    @storybook/react: 6.0.26 => 6.0.26
    @storybook/theming: 6.0.26 => 6.0.26
```

**Comment by shilman** [comment]
Try running Storybook with the `--no-dll` flag?

**Comment by kaiyoma** [comment]
We already specify `--no-dll` when building Storybook, but for this case, I was actually referring to running in dev server mode (i.e. `start-storybook`). Should we be specifying `--no-dll` in that case as well?

BTW, we're not using React 16.14, so I don't think this is related to that other comment. I just ran `yarn why react` in my project and the only version of React here is 16.13.1.

**Comment by shilman** [comment]
Try running with `--no-dll` in dev mode too. Does it help? We're planning to get rid of the webpack DLLs in 6.1 and remove this class of errors.

**Comment by kaiyoma** [comment]
No, doesn't help. Same errors.

**Comment by shilman** [comment]
Do you have a repro repo you can share?

**Comment by kaiyoma** [comment]
No, not at the moment. This is a production project so it would take me some time to whittle it down to a shareable repro.

**Comment by tarikhamilton** [comment]
I had this same issue. I fixed it by reinstalling my project's node_modules. I believe I had updated to React 17.0.1 (silly, but sometimes updates do fix weird things) trying to rule out some other issue. You may need to delete your lock file too. For my case, I confirmed @storybook/react had react@16.13 in its own node_modules folder. I'm pretty sure React is a peer dependency for Storybook, so not sure how this happened, but I'm not a module resolution expert, so I deleted it and the new lock file didn't have a separate React dependency installed for @storybook/react anymore.

I did start using `yarn`, which had a different lock file, so perhaps that is how things got in a screwed up state. Hope this helps you or someone.

**Comment by shilman** [comment]
@tarikhamilton the dependency structure has changed from 6.0 => 6.1. for anybody running into this issue, if you're not on 6.1.x, i'd recommend upgrading and potentially regenerating lockfiles.
