### ISSUE TITLE
Node 14 Circular dependency error due to ShellJS

### ISSUE THREAD

**Issue by clementprevot** [storybookjs/storybook#12793]
_**This is a reopening of https://github.com/storybookjs/storybook/issues/11173**_

**Describe the bug**

When running Storybook with Node 14, there are a lot of "Circular dependencies" error thrown (that doesn't affect the proper working of Storybook though):

![image](https://user-images.githubusercontent.com/6450505/96267470-1b403280-0fc8-11eb-9f0e-a7e1e1f4ef35.png)

When running with `--trace-warning` here is the result:

![image](https://user-images.githubusercontent.com/6450505/96267597-47f44a00-0fc8-11eb-974e-5deda5bae954.png)

So clearly the issue is coming from ShellJS.
And indeed, there are [some](https://github.com/shelljs/shelljs/issues/992) [issues](https://github.com/shelljs/shelljs/issues/991) over there talking about that.

And the solution is simple: update to ShellJS 0.8.4.

AFAIK, `@storybook/root` is using 0.8.4, but not `@storybook/core`.

The [last message of the previous issue](https://github.com/storybookjs/storybook/issues/11173#issuecomment-648704093) suggested to create a PR to upgrade the package but I think that nobody did it.

So I'm reopening this issue and will issue a PR to solve it.

**Comment by shilman** [comment]
Son of a gun!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.0-alpha.26 containing PR #12794 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
