### ISSUE TITLE
Allow wrapping of all available stories

### ISSUE THREAD

**Issue by loberbichler** [storybookjs/storybook#12791]
**Is your feature request related to a problem? Please describe**
As we use storybook for our design system which is framework agnostic, we would like to have an option to display a TabComponent similar to 
![Storybook CodeSnippets Example](https://user-images.githubusercontent.com/16646737/96260452-4ffbbc00-0fbf-11eb-8c67-c722d2170bcd.png) on a `<Canvas />` (or on a Storie**s**) level, to be able to switch between the different framework implementations, technologies (like Pure CSS, SASS, Angular, React).

**Describe the solution you'd like**
We could expand on the decorator functionality [Storybook Decorators Doc](https://storybook.js.org/docs/react/writing-stories/decorators), to provide a decorator function not just on a single story level, but for all defined stories to be able to wrap all of them in e.g a `<TabContainer />` component.
Below is a quick example of how it could look like.

```tsx
 metaDecorators={[stories, context] => {
   return (
      <TabContainer>
         {stories.map(s => <Tab {...}>{s}</Tab>)} 
      </TabContainer>
   );
}}
 decorators={[(Story, context) => {
    return (
      <div style={{margin: "3em"}}>
        <Story />
      </div>
    )
  }]}
```

**Are you able to assist to bring the feature to reality?**
yes

**Comment by shilman** [comment]
Can you achieve the desired result with this existing construct rather than introducing something new?

https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/recipes.md#overwriting-docs-container

**Comment by loberbichler** [comment]
Unfortunately not, as the `docs` container wraps the whole page, which is not granular enough for this specified use case. 

Take the following example `Button.stories.mdx` with two stories defined like:

```jsx
<Canvas>
  <Story name="Primary Typescript" args={{ ...Primary.args }}>
    {(args) => {
      return (
          <div style={{ marginBottom: '1em' }}>
            <Button {...args} >
              <span>primary button</span>
            </Button>
          </div>
      );
    }}
  </Story>
  <Story name="Primary JavaScript {...}>{...}</Story>
</Canvas>

<Canvas>
  <Story name="Secondary Typescript" args={{ ...Secondary.args }}>
    {(args) => {
      return (
          <div style={{ marginBottom: '1em' }}>
            <Button {...args} >
              <span>secondary button</span>
            </Button>
          </div>
      );
    }}
  </Story>
  <Story name="Secondary JavaScript {...}>{...}</Story>
</Canvas>
```

By overwriting the `docs` container I'm not really able to differentiate between the two `<Canvas />` elements. Rather than a decorator for the whole page, I would either need a `<Canvas>` or Stories decorator.

So in this example I want to transform the code above to something like:

```jsx
<Canvas>
  <TabContainer {...props}>
    <Story name="Secondary Typescript" args={{ ...Secondary.args }}>
      {(args) => {
        return (
            <div style={{ marginBottom: '1em' }}>
              <Button {...args} >
                <span>secondary button</span>
              </Button>
            </div>
        );
      }}
    </Story>
    <Story name="Secondary JavaScript {...}>{...}</Story>
  </TabContainer>
</Canvas>
```

Thanks for the suggestion, if I'm missing something here please let me know :)

**Comment by shilman** [comment]
How would the meta decorator know where to apply itself when you can have multiple stories on the page?

**Comment by loberbichler** [comment]
Well, I would choose to have a kind of wrapper element where the meta decorator would always apply itself to. 
In the example above I chose the `<Canvas>` element, but it could also be a new one.
