### ISSUE TITLE
Lots of broken links on addon-docs npm page

### ISSUE THREAD

**Issue by kaiyoma** [storybookjs/storybook#12797]
Not sure if this affects all the npm pages for all the plugins, but every github.com link on this page is broken:

https://www.npmjs.com/package/@storybook/addon-docs

**Comment by jonniebigodes** [comment]
@kaiyoma I would like to thank you for bringing this to our attention and i've just made a pull request that addresses the issue you've encountered. Hopefully once it's merged the links should be working as intended. 


Stay safe

**Comment by darleendenno** [comment]
Closing as this issue is resolved.
