### ISSUE TITLE
Add "Embed" icon to toolbar

### ISSUE THREAD

**Issue by techboyg5** [storybookjs/storybook#12806]
I think that an "Embed" icon should be added to the toolbar.

When clicking on it a modal would open, providing iframe code for the current page. The code would look like this:

    <iframe src="CURRENT_PAGE_URL" height="600" style="border:0;width:100%"></iframe>

**Comment by shilman** [comment]
I believe the "eject" button already does this:

<img width="613" alt="Browse_Stories" src="https://user-images.githubusercontent.com/488689/96363553-bd4a5100-1167-11eb-9754-5c2f84d2948e.png">

cc @jonniebigodes

**Comment by techboyg5** [comment]
> I believe the "eject" button already does this, or something pretty close:
> 
> <img alt="Browse_Stories" width="613" src="https://user-images.githubusercontent.com/488689/96363553-bd4a5100-1167-11eb-9754-5c2f84d2948e.png">
> 
> cc @jonniebigodes

It just copies the link to the story. I think that an embed button `<>` should be provided, which provides:
* Iframe, not a URL
* The src is the Storybook, not just the one Story

**Comment by jonniebigodes** [comment]
@shilman that's pretty much what the eject button does. It opens a new tab/browser window with the component's Story minus the manager related UI elements. It can be embedded inside a iframe (tested it locally) within a new app. @techboyg5 depending on your needs you can use the eject button @shilman pointed out or if you're feeling a bit "adventurous" (pardon the bad pun) create your own addon. Keep checking our documentation as it's being extended to include improvements to the addons ecosystem.

Let us know

Stay safe

**Comment by ghengeveld** [comment]
I imagine we could have a "share" button that provides various ways to share the component, as an HTML iframe, source code snippet, link, MDX, etc. Sounds like a good addon.

**Comment by jonniebigodes** [comment]
Closing this for now. If anyone wants to cycle back to it I'm more than glad to update the docs accordingly.
