### ISSUE TITLE
Allow to configure `argTypes` controls autogeneration for external libraries (e.g. Material UI)

### ISSUE THREAD

**Issue by Carduelis** [storybookjs/storybook#12816]
**Is your feature request related to a problem? Please describe**

There is a [Readme](https://github.com/storybookjs/storybook/blob/next/addons/controls/README.md#my-controls-arent-being-auto-generated-what-should-i-do) where is described why controls isn't generated.

> You're trying to generate controls for a component defined in an external library

It's clear. But how to enhance it? For example, I know, that `propTypes` for Material UI lay in `Component.Naked.propTypes`.
How can I point Storybook to autogenerate constrols from there?

**Describe the solution you'd like**

One of the solution is to expose the path where and how Storybook should pick up argTypes.
For example:
```
<Meta
  title="Material UI/Tabs"
  component={Tabs}
  argTypesLookup={(Component) => ({
      propTypes: Component.Naked.propTypes,
      defaultProps: { color: 'primary' }, // defaultProps are missing in Material UI library
 })}
/>
```

**Comment by Carduelis** [comment]
I discovered, that `defaultProps` are actually there, in Material UI theme. And we can tweak them using `createMuiTheme` and property: `props`, which defines `deftaultProps` for every component.

So, basically, using my proposed syntax, do this:
```
const lookupFunction = (Component, theme) => ({
      propTypes: Component.Naked.propTypes,
      defaultProps: theme.props[Component.displayName],
})

<Meta
  title="Material UI/Tabs"
  component={Tabs}
  argTypesLookup={lookupFunction},
/>
```

**Comment by shilman** [comment]
I've documented the solution in #14092 and am closing this as a duplicate
