### ISSUE TITLE
Storybook does not support custom tsconfig location

### ISSUE THREAD

**Issue by TeoTN** [storybookjs/storybook#12818]
**Describe the bug**
I have `tsconfig.json` file in `src` directory and Storybook v6 is not picking this up.
I noticed the esModuleInterop is disabled despite the flag being set in the config, the browser results in this error (with react):
```
TypeError: Cannot read property 'memo' of undefined
```

**To Reproduce**

It seems it is now impossible to pass the config path. I've been trying with configuring it more or less like in the example below, but without any success:

```
    typescript: {
        check: false, // Or true
        checkOptions: { // Or {}
            context: CONTEXT_PATH,
            tsconfig: TSCONFIG_PATH,
        },
        reactDocgenTypescriptOptions: { // Or without it
            tsconfigPath: TSCONFIG_PATH,
        }
    },
```

The `@storybook/preset-typescript` also stopped working. It emits an error suggesting it's not able to find `typescript`, but in reality that's a result of an error swallowed in `catch`. The preset errors because an object is passed as some `id` instead of string. 

**Expected behavior**
I expect a trivial way to pass path of where the `tsconfig.json` is. It shouldn't take hours to configure it and debug all issues.

**Additional context**
I can't provide any reproduction as the project I'm working on is not public.

**Comment by TeoTN** [comment]
Actually, downgrading `@storybook/preset-typescript` to v2.1 worked. I think though it's still a bug that it doesn't work with v3 and `typescript` config section doesn't have `tsconfig` path configurable

**Comment by shilman** [comment]
@mrmckeb is this something you can take a look at?

**Comment by shilman** [comment]
Do you have a repro repo you can share?

**Comment by TeoTN** [comment]
Unfortunately, I can't share the code
