### ISSUE TITLE
JSDocs don't work when they begin with `@description`

### ISSUE THREAD

**Issue by kylemh** [storybookjs/storybook#12825]
**Describe the bug**
If one leverages JSDocs like so:

```
/**
 * @description This prop does somethiing
 * @see somelink.com
 */
someProp?: true
```

The JSDocs do not render in the description column of the docs table, but with this:

```
/**
 * This prop does somethiing
 * @see somelink.com
 */
someProp?: true
```

There's no issue. Removing `@description` fixes everything.

**Expected behavior**
`@description` can simply be ignored and JSDoc comments will still render in the table.

**Additional context**
I don't think this is a big deal, and I simply removed `@description` from my JSDocs usages, but I figured it was worth documenting in case anybody else runs into this error!

**Comment by kylemh** [comment]
Hmmmm so do we just ignore stalebot or let this close?

**Comment by shilman** [comment]
Stalebot serves a few different functions:
- It closes issues that don't get attention
- It reminds people (issue authors, maintainers) that an issue needs attention.

I typically let stalebot run its course unless there are vociferous objections, or unless I see somebody actively working on an issue.

**Comment by kylemh** [comment]
Well. It's no massive issue which has no work ongoing so, I'll just close it!
