### ISSUE TITLE
preact peerDependencies: Incorrect peer dependency OR syntax 

### ISSUE THREAD

**Issue by germanferrero** [storybookjs/storybook#12868]
**Describe the bug**
running npm install in a project with @storybook/preact@6.0.26 and preact@10.5.5 as dependencies, throws this warning.

 @storybook/preact@6.0.26 requires a peer of preact@^8.0.0|^10.0.0 but none is installed. You must install peer dependencies yourself.

AFAIU the correct syntax for logical or in semver would be preact@^8.0.0||^10.0.0  (do note the double | )

**Expected behavior**
No warning is show up, the peer dependency is correctly stated.

**Comment by shilman** [comment]
Ta-da!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.0-alpha.32 containing PR #12883 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
