### ISSUE TITLE
Invalid Hook Call with create react app & npx sb init

### ISSUE THREAD

**Issue by Rondip** [storybookjs/storybook#12877]
**Describe the bug**
Invalid hook due to invalid peer dependencies of storybook and its default addons with npx sb init

**To Reproduce**
1. npx create-react-app myApp
2. npx sb init
3. yarn storybook or npm run storybook
4. See error in console

**Expected behavior**
Storybook to display set of components

**Screenshots**

<img width="1295" alt="Screenshot 2020-10-23 at 2 15 34 PM" src="https://user-images.githubusercontent.com/17453311/96977103-41bb1c00-153a-11eb-8c07-46508584911e.png">

**System**
```
Environment Info:

  System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    Yarn: 1.3.2 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 86.0.4240.111
    Firefox: 50.0
    Safari: 14.0
  npmPackages:
    @storybook/addon-actions: ^6.0.26 => 6.0.26
    @storybook/addon-essentials: ^6.0.26 => 6.0.26
    @storybook/addon-links: ^6.0.26 => 6.0.26
    @storybook/node-logger: ^6.0.26 => 6.0.26
    @storybook/preset-create-react-app: ^3.1.4 => 3.1.4
    @storybook/react: ^6.0.26 => 6.0.26
```

**Comment by mealeyst** [comment]
Thank the lord I am not the only person encountering this! I've been pulling my hair out for hours. I had this issue when I tried to install `@storybook/addon-knobs` which after doing some digging I noticed that `@storybook/addon-essentials` with `controls` might be the way to go.

**Comment by mealeyst** [comment]
Okay, I think I fixed my issue! I did the following:

```
npx create-react-app example-project
cd example-project
npm install --save styled-components
npm install --save-dev @storybook/addon-essentials
npx sb init
```

I then added the controls addon to `main.js`:

```
//.storybook/main.js
module.exports = {
  stories: ['../src/**/*.stories.js'],
  addons: [
    '@storybook/preset-create-react-app',
    '@storybook/addon-actions',
    '@storybook/addon-links',
    '@storybook/addon-controls',
  ],
};
```

**Comment by shilman** [comment]
closing as dupe to #12408
