### ISSUE TITLE
Automention job issues?

### ISSUE THREAD

**Issue by kaiyoma** [storybookjs/storybook#12892]
Just got a random email from GitHub seemingly related to an issue I filed this morning:

Run failed for next (2536198)
Repository: storybookjs/storybook
Workflow: Automention Issues
Duration: 47.0 seconds
Finished: 2020-10-23 17:17:55 UTC

View results

Jobs:
Automention failed (3 annotations)

**Comment by shilman** [comment]
sorry about that. fixed now 👍
