### ISSUE TITLE
Cannot customize the layout margin with a custom theme

### ISSUE THREAD

**Issue by Titou325** [storybookjs/storybook#12918]
**Is your feature request related to a problem? Please describe**
There is no easy way as of now to customize the layout margin that surrounds the right hand panel of the layout (containing the tools, stories, docs, actions, ...).

**Describe the solution you'd like**
I would like to be able to specify a custom value for the margin, other than the default 10px. I.E. setting it to 0 to remove any margin and make it stand flush against the sides, or tweaking the 10px value to better suit other branding considerations.

**Describe alternatives you've considered**
No easy fix can be considered as part of the layout margin is applied dynamically through JS (I.E. listening to resize events to adapt the container height).

**Are you able to assist to bring the feature to reality?**
Unsure / depends on whether or not other components rely on the layoutMargin value.

Thanks a lot!

**Comment by shilman** [comment]
closing as dupe to #12434 #12041
