### ISSUE TITLE
Storybook build output doesn't navigate when served/hosted

### ISSUE THREAD

**Issue by devjmetivier** [storybookjs/storybook#12911]
**Describe the bug**
When building a storybook project and deploying it, navigating the storybook doesn't work with the left-hand navigation.

**To Reproduce**

1. Create new storybook project (the default init should be fine)
2. Build the storybook project
2. Serve with `npx http-server ./path/to/build`

**Expected behavior**
Left-hand links allow the user to navigate the storybook

**Screenshots**
![video](https://i.gyazo.com/1a68e4ca4016d8b634c45d19e635eb16.gif)

**System**
Environment Info:

  System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 12.18.4 - ~/.nvm/versions/node/v12.18.4/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.4/bin/npm
  Browsers:
    Chrome: 86.0.4240.111
    Safari: 14.0
  npmPackages:
    @storybook/addon-actions: ^6.0.27 => 6.0.27 
    @storybook/addon-controls: ^6.0.27 => 6.0.27 
    @storybook/addon-essentials: ^6.0.27 => 6.0.27 
    @storybook/addon-links: ^6.0.27 => 6.0.27 
    @storybook/addon-storysource: ^6.0.27 => 6.0.27 
    @storybook/react: ^6.0.27 => 6.0.27

**Comment by shilman** [comment]
Closing as dupe to #11958
