### ISSUE TITLE
New JSX Transform in React 17 not working for component stories

### ISSUE THREAD

**Issue by alonfai** [storybookjs/storybook#12920]
## Bug or support request summary
Hey all,

I recently upgraded to latest React 17 with support of new JSX transform. I ran the given code mod  (https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html#removing-unused-react-imports) to remove the default `import React from 'react'` in each of my typescript .tsx files. 

I now run into problems with all my stories .tsx , that complains with an error `ReferenceError: React is not defined` (see attached preview). 

I tried to implement the solution I found here  (https://github.com/jakelazaroff/react-storybook-decorator-background/issues/2#issuecomment-621186348) by inserting the import statement into the preview.js file, but with no success.

If I return the default import into any of the existing stories, then the story component renders successfully.

![Screen Shot 2020-10-27 at 10 37 46 am](https://user-images.githubusercontent.com/11208491/97239735-7a137080-1840-11eb-80e5-0716dfc7c9c0.png)

## Please specify which version of Storybook and optionally any affected addons that you're running

    "@storybook/addon-a11y": "^6.0.27",
    "@storybook/addon-essentials": "^6.0.27",
    "@storybook/addon-jest": "^6.0.27",
    "@storybook/addon-knobs": "^6.0.27",
    "@storybook/addon-links": "^6.0.27",
    "@storybook/addon-storysource": "^6.0.27",
    "@storybook/addons": "^6.0.27",
    "@storybook/preset-scss": "^1.0.3",
    "@storybook/react": "^6.0.27",

**Comment by shilman** [comment]
Closing as dupe to #12881

**Comment by vctqs1** [comment]
Could you share your solution, I meet the same issue, tried (jakelazaroff/react-storybook-decorator-background#2 (comment))  but not work

**Comment by vctqs1** [comment]
I'll temporary copy babel file to bypass
