### ISSUE TITLE
Typescript argType inference only works for .tsx files, not .ts files

### ISSUE THREAD

**Issue by tremby** [storybookjs/storybook#12943]
**Describe the bug**
Typescript argType inference only works if the component file has a `.tsx` extension, not if it is `.ts`.

**To Reproduce**

1. Clone https://github.com/tremby/storybook-ts-tsx-bug
   In this repo we have two almost-identical components, TsComponent and TsxComponent. They export functionally identical components (other than the colour they render in) and identical types. There are corresponding functionally identical stories.
2. Install dependencies with `npm i` or `npm ci`
3. Run `npm run storybook`
4. Compare the two stories. Note that the controls are different for the two different stories.

**Expected behavior**
They look the same other than the text colour, including the controls. The `thing` control should be required, and should be a selectbox. On the "Docs" tab the `thing` control should have the description text "Some thing".

**Screenshots**
.ts component is bad:
![Screen Shot 2020-10-28 at 23 57 20](https://user-images.githubusercontent.com/199635/97535758-5ef84c00-1979-11eb-99b8-36e2ee00594b.png)

.tsx component is good:
![Screen Shot 2020-10-28 at 23 57 23](https://user-images.githubusercontent.com/199635/97535768-628bd300-1979-11eb-94bf-894ad13feb59.png)

**System**
```
Environment Info:

  System:
    OS: Linux 4.15 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz
  Binaries:
    Node: 12.18.1 - /usr/bin/node
    Yarn: 1.19.1 - /usr/bin/yarn
    npm: 6.14.5 - /usr/bin/npm
  Browsers:
    Firefox: 82.0
  npmPackages:
    @storybook/addon-actions: ^6.0.27 => 6.0.27
    @storybook/addon-essentials: ^6.0.27 => 6.0.27
    @storybook/addon-links: ^6.0.27 => 6.0.27
    @storybook/react: ^6.0.27 => 6.0.27
```

**Additional context**
I mentioned this on the Discord server a week or so ago. Someone said they'd note it but I couldn't see an issue in the tracker when I looked today, having come across the bug again.

**Comment by nielsdB97** [comment]
You might have to manually specify `.ts` files to picked up by react-docgen-typescript:

`*main.js*`
```js
module.exports = {
  stories: ["../stories/**/*.stories.@(ts|tsx|js|jsx)"],
  addons: ["@storybook/addon-links", "@storybook/addon-essentials"],
  typescript: {
    reactDocgen: "react-docgen-typescript",
    reactDocgenTypescriptOptions: {
      include: ['**/**.ts', '**/**.tsx']
    },
  },
}
```

https://github.com/hipstersmoothie/react-docgen-typescript-plugin#options

**Comment by tremby** [comment]
That seems like a weird default to have, given that both file extensions are very common for Typescript files.

But that change works; thank you.

Only this addition to `main.js` is needed:

diff`
diff --git a/.storybook/main.js b/.storybook/main.js
index fd48b93..45d9c65 100644
--- a/.storybook/main.js
+++ b/.storybook/main.js
@@ -4,4 +4,9 @@ module.exports = {
     "../components/**/*.stories.@(js|jsx|ts|tsx)",
   ],
   addons: ["@storybook/addon-links", "@storybook/addon-essentials"],
+  typescript: {
+    reactDocgenTypescriptOptions: {
+      include: ["**/*.ts", "**/*.tsx"],
+    },
+  },
 };
```
