### ISSUE TITLE
The styled checkbox used for boolean switches in controls is confusing

### ISSUE THREAD

**Issue by tremby** [storybookjs/storybook#12945]
I repeatedly get confused about whether these are set to true or false. I can't be the only one.

![screen](https://user-images.githubusercontent.com/199635/97546178-50199580-1989-11eb-8a03-1a5a3d7ed509.png)

The grey is a strange choice. I keep thinking the grey-shaded side is the side which is *not* chosen. Why not use the blue instead, which is used as an "active"/"primary" colour elsewhere in the Storybook UI?

**Comment by shilman** [comment]
Fixed in https://github.com/storybookjs/storybook/pull/12515 and available in 6.1-alpha
