### ISSUE TITLE
In Storybook 6, Don't show optional props in code if the prop value is the same as default value

### ISSUE THREAD

**Issue by zeckdude** [storybookjs/storybook#12940]
**Is your feature request related to a problem? Please describe**
Yes, the copied code is bloated with all the default values being set

**Describe the solution you'd like**
I am hoping to be able to omit the optional props from the code sample if they haven't been changed

**Describe alternatives you've considered**
The alternative is to remove the optional props manually from the copied code

**Are you able to assist to bring the feature to reality?**
Yes, if you can point in me in the right direction and advise on best avenue of approach

**Additional context**
So in the below screenshot several of those props are optional and have default values. They really don't need to show in the code since that will be copied and then we will need to manually remove those every time.

So instead of what is seen in the screenshot below, I am hoping for something like this:
```js
<Button>
  Primary Button
</Button>
```
<img width="1034" alt="Screen Shot 2020-10-28 at 2 31 53 PM" src="https://user-images.githubusercontent.com/947856/97499369-fa160500-192a-11eb-803d-1beaed41776c.png">

Only if a prop value is set that is not the same as the default value, would I like the prop to show on the code sample. So if I set it to be disabled, then I would expect the code sample to show this:
```js
<Button isDisabled>
  Primary Button
</Button>
```

**Comment by shilman** [comment]
closing as dupe to #11510
