### ISSUE TITLE
[ issue ] See the blank page when I expect to see welcome page .

### ISSUE THREAD

**Issue by guychienll** [storybookjs/storybook#12951]
**Describe the bug**
hi , 
I got the problem when I using create-react-app to create an project and use the script `npx sb init` at the root of my project , when installed , I open the localhost:6006 , sb default port , but I see the blank page instead of the welcome page.
thank your attention.
**To Reproduce**

Same as above.
I see the error , seems like the sb call the hook Invalid , but I didn't add any hook in my code yet.
I guessed.

**Expected behavior**

I expect to see the welcome page . thanks!

**Screenshots**
![image](https://user-images.githubusercontent.com/63462677/97589719-d640e500-1a38-11eb-81e3-cfc235f6153d.png)

**Code snippets**
none.

**System**
Environment Info:

  System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 12.16.1 - /usr/local/bin/node
    npm: 6.14.5 - /usr/local/bin/npm
  Browsers:
    Chrome: 86.0.4240.111
    Safari: 14.0
  npmPackages:
    @storybook/addon-actions: ^6.0.27 => 6.0.27 
    @storybook/addon-essentials: ^6.0.27 => 6.0.27 
    @storybook/addon-links: ^6.0.27 => 6.0.27 
    @storybook/node-logger: ^6.0.27 => 6.0.27 
    @storybook/preset-create-react-app: ^3.1.4 => 3.1.4 
    @storybook/react: ^6.0.27 => 6.0.27

**Comment by Tawreh** [comment]
I'm seeing the same issue - I created a new React app with `create-react-app`, then added Storybook to it this afternoon using the command `npx sb init`. 

I see the same error in my console when I go to the Storybook welcome page, using Ubuntu. I'm using the latest LTS release for Node and npm.

**Comment by Tawreh** [comment]
Aha, my issue was solved by following the instructions on this issue: https://github.com/storybookjs/storybook/issues/12408#issuecomment-716637427 

I ran: 

```
npx sb upgrade --prerelease
```

And Storybook compiled correctly.

**Comment by guychienll** [comment]
@Tawreh awesome !!! my issue was solved. thank for your help.  seems like the conflict between new version of react and sb.

**Comment by shilman** [comment]
closing as dupe to #12408
