### ISSUE TITLE
@storybook/addons 6.0.28 not published

### ISSUE THREAD

**Issue by justnewbee** [storybookjs/storybook#12962]
**Describe the bug**

other packages of 6.0.28 is published but @storybook/addons which results in install failure

**To Reproduce**

install

**Expected behavior**

OK

**Screenshots**

<img width="1679" alt="image" src="https://user-images.githubusercontent.com/2276086/97705386-f7fca380-1aee-11eb-813f-8fd4fba8f0d4.png">

<img width="1334" alt="image" src="https://user-images.githubusercontent.com/2276086/97705440-11055480-1aef-11eb-83ae-6d5c3de8a15d.png">

**Code snippets**

no code

**System**

mac

**Additional context**

nope

**Comment by shilman** [comment]
Seems like there's some lag in the system. Can you try again & maybe clear your NPM cache?

```
$ npm info @storybook/addons

@storybook/addons@6.0.28 | MIT | deps: 9 | versions: 666
...
```

**Comment by justnewbee** [comment]
now it's OK, thanks
