### ISSUE TITLE
The README file in this repo has some bad links - [404:NotFound]

### ISSUE THREAD

**Issue by MrCull** [storybookjs/storybook#12961]
**Describe the bug**

The README file in this repo has some bad links - [404:NotFound]

Status code [404:NotFound] - Link: https://now-examples-slackin-rrirkqohko.now.sh/
Status code [404:NotFound] - Link: https://github.com/storybookjs/storybook/blob/next/app/react-native
Status code [404:NotFound] - Link: https://github.com/storybookjs/storybook/tree/master/addons/contexts
Status code [404:NotFound] - Link: https://github.com/storybookjs/storybook/tree/master/addons/options/
Status code [404:NotFound] - Link: https://opencollective.com/storybook/sponsor/27/website
Status code [404:NotFound] - Link: https://opencollective.com/storybook/sponsor/28/website
Status code [404:NotFound] - Link: https://opencollective.com/storybook/sponsor/29/website

Status code [406:NotAcceptable] - Link: https://opencollective.com/storybook/sponsor/23/website
Status code [503:ServiceUnavailable] - Link: https://opencollective.com/storybook#backer
Status code [302:Redirect] - Link: https://opencollective.com/storybook/backer/17/website

**To Reproduce**
Navigate to any of the links

**Expected behavior**
The links should work

**Additional context**
Documentation issue only

This was found by an new experimental hobby project that I have just created: https://github.com/MrCull/GitHub-Repo-ReadMe-Dead-Link-Finder
If this has been in any way helpful then please consider giving the above Repo a Star.

**Comment by jonniebigodes** [comment]
@MrCull a pull request addressing this issue was merged. Closing this issue now, thanks for bringing this to our attention.

Stay safe
