### ISSUE TITLE
Arg with cyclical reference causes infinite loop

### ISSUE THREAD

**Issue by adrfoong** [storybookjs/storybook#12974]
**Describe the bug**
If an argument with a cyclical reference is used, the story fails and goes into an infinite loop.

**To Reproduce**
Simple code to repro:

```
import React from 'react';

const Button = ({ text }) => {
	return <button type="button">{text}</button>;
};

export default {
	title: 'Bomb',
	component: Button,
};

const Template = args => <Button {...args} />;

export const Basic = Template.bind({});

let parent = {};
let child = { parent };
parent.child = child;

Basic.args = {
	text: 'Hello',
	bomb: child,
};
```

**Expected behavior**
Either handle the cyclical reference or at least give the user a warning.

**Additional context**
The problem seems to be occuring in `inferArgTypes.js`

**Comment by shilman** [comment]
Duplicate to #13242 and fixed. Sorry this fell through the cracks the first time around!

**Comment by adrfoong** [comment]
No worries, thanks for looking into it!
