### ISSUE TITLE
Unexpected end of JSON input while parsing near '...Cx3YG/5lc4P+NEurdy8JS

### ISSUE THREAD

**Issue by Rob-Page** [storybookjs/storybook#12973]
**Describe the bug**
I have been developing using the create react app with typescript and sass. Just recently I started getting the error:`npm ERR! Unexpected end of JSON input while parsing near '...Cx3YG/5lc4P+NEurdy8JS'` when doing an npm install. I was able to limit it down to the @storybook/addon-docs package.

**To Reproduce**

1. npx create-react-app my-app
2. cd my-app
3. npm i -D @storybook/addon-docs
4. See error : `npm ERR! Unexpected end of JSON input while parsing near '...Cx3YG/5lc4P+NEurdy8JS'
`
**Screenshots**
![image](https://user-images.githubusercontent.com/6818597/97814788-183f7600-1c47-11eb-8fd5-1a3877877047.png)

**System**
  System:
    OS: Windows 10 10.0.19041
    CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor
  Binaries:
    Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 86.0.4240.111
    Edge: Spartan (44.19041.423.0), Chromium (86.0.622.58)

**Comment by droid95** [comment]
Here I'm using `npx sb init` to initialize my storybook setup, when I removed node_modules folder and run `npm i`, I get the same error. 

**Fix**
To fix I ran `npm cache clean --force`. 

**Environment:**
NodeJS v12.16.3
NPM v6.14.4
OS Ubuntu 18.04

**Storybook packages versions:**
@storybook/addon-actions v6.1.5
@storybook/addon-essentials v6.1.5
@storybook/addon-links v6.1.5
@storybook/react v6.1.5

**Comment by shilman** [comment]
This seems more like an intermittent NPM issue than a storybook issue per se. Closing.

**Comment by AndreySukhov** [comment]
removing node_modules folder and installing it again worked for me
