### ISSUE TITLE
Build failing for `examples-v2-yarn-2`

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#12984]
I believe our heuristic for the React JSX transform is failing:

https://github.com/storybookjs/storybook/blob/next/app/react/src/server/framework-preset-react.ts#L25-L29

=>

https://app.circleci.com/pipelines/github/storybookjs/storybook/14433/workflows/b9c53217-9b45-481e-a5d0-8576d5e1c583/jobs/272315

```
Success! Created cra-latest at /tmp/storybook-e2e-testing/cra-latest
...
👷 Building Storybook
...

ERR! src/App.js
ERR!   Line 6:5:    'React' must be in scope when using JSX  react/react-in-jsx-scope
ERR!   Line 7:7:    'React' must be in scope when using JSX  react/react-in-jsx-scope
ERR!   Line 8:9:    'React' must be in scope when using JSX  react/react-in-jsx-scope
ERR!   Line 9:9:    'React' must be in scope when using JSX  react/react-in-jsx-scope
ERR!   Line 10:16:  'React' must be in scope when using JSX  react/react-in-jsx-scope
ERR!   Line 12:9:   'React' must be in scope when using JSX  react/react-in-jsx-scope
```

Tho shouldn't this be using CRA's preset?

**Comment by gaetanmaisse** [comment]
Somehow related to https://github.com/storybookjs/storybook/issues/12928, maybe a duplicate, to investigate

**Comment by shilman** [comment]
Seems to have gone away with #12972. Closing.
