### ISSUE TITLE
Addons using `preview-head.html`

### ISSUE THREAD

**Issue by BeeeQueue** [storybookjs/storybook#12987]
**Is your feature request related to a problem? Please describe**
We need to add a script tag to the header of our previews, but we have many many repos and don't want to force everyone to add it manually in each one.

We have an addon that configures webpack and babel to work without setup, and I'm wondering if it's possible to add something to the head tag with it. I haven't been able to find anything in the docs about it.

**Describe the solution you'd like**
An API to add something to the head a la [`.storybook/preview-{head,body}.html`](https://storybook.js.org/docs/react/configure/story-rendering#adding-to-head)

**Describe alternatives you've considered**
Somehow modifying the HTML Webpack Plugin's setttings to include our tag via those, but that is extremely brittle.

**Are you able to assist to bring the feature to reality?**
I might be able to add something if given pointers where to look

**Comment by shilman** [comment]
Can you use a decorator as a workaround?

https://storybook.js.org/docs/react/writing-stories/decorators

**Comment by BeeeQueue** [comment]
I'll try it and report back

**Comment by BeeeQueue** [comment]
Didn't work, we need the script to load before the story should be accessible.

Does that mean we can't add it in the preview but have to add it to the manager html? Will the script be accessible in the iframe?

**Comment by shilman** [comment]
This is a reasonable feature request and you're not the first person to ask for it. Would you be up for putting together a PR to add this? cc @ndelangen

**Comment by JonathanKolnik** [comment]
@shilman I would be happy to work on a PR, could you point me in the right direction? Any examples or files to familiarize myself with, just to get a starting point.

**Comment by ghengeveld** [comment]
Might this be possible to achieve using a [loader](https://storybook.js.org/docs/react/writing-stories/loaders)? These run before the story is rendered, but after the story file is loaded (I think).

**Comment by shilman** [comment]
@JonathanKolnik @BeeeQueue it was faster to implement it than explain how ☝️  please review the PR for me: #13432

**Comment by shilman** [comment]
Zoinks!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.0-alpha.6 containing PR #13432 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by davidferguson** [comment]
Old discussion, but I need to do the same thing (have an addon to Storybook 6 add something to the preview head). It needs to be an addon because I have many repos, and I don't want to duplicate the head code across them.

I can get this working by putting the code in the exports of each repo individually (ie. `repo-a/.storybook/main.js`), but I'm not sure where I should be putting it in the addon to get it to work. Are you able to help with this @shilman?

**Comment by oskarssylwan** [comment]
> Old discussion, but I need to do the same thing (have an addon to Storybook 6 add something to the preview head). It needs to be an addon because I have many repos, and I don't want to duplicate the head code across them.
> 
> I can get this working by putting the code in the exports of each repo individually (ie. `repo-a/.storybook/main.js`), but I'm not sure where I should be putting it in the addon to get it to work. Are you able to help with this [@shilman](https://github.com/shilman)?

Same issue here. I don't really get where to add it in the addon. It would be great if the https://github.com/storybookjs/addon-kit had an example of it

**Comment by ghengeveld** [comment]
@oskarssylwan In `src/preview.ts` you would add something like this:

```ts
import type { PresetProperty } from 'storybook/internal/types';

export const previewHead: PresetProperty<'previewHead'> = (head) => `
  ${head}
  <style>
    body {
      background: yellow!important;
    }
  </style>
`;
```

I tried it and it works.

**Comment by oskarssylwan** [comment]
> [@oskarssylwan](https://github.com/oskarssylwan) In your addon's `src/preview.ts` you would add something like this:
> 
> import type { PresetProperty } from 'storybook/internal/types';
> 
> export const previewHead: PresetProperty<'previewHead'> = (head) => `
>   ${head}
>   <style>
>     body {
>       background: yellow!important;
>     }
>   </style>
> `;
> I tried it and it works.

Thanks for the quick response, I tried that but no luck :/

Maybe it clashes with the default export? I tried adding it there first, but the type didn't exist on `ProjectAnnotations<Renderer> `

```typescript
const preview: ProjectAnnotations<Renderer> = {
  initialGlobals: {
    [KEY]: false,
  },
};

export const previewHead: PresetProperty<'previewHead'> = (head) => `
  ${head}
  <link href="<redacted>" rel="stylesheet">
  <link href="<redacted>" rel="stylesheet">
`;

export default preview;
```

**Comment by davidferguson** [comment]
I forgot about this thread, but did end up getting it working with my Storybook 6 addon. In the `./preset.js` file (next to the `./package.json`), I have the following, which works for me to add a font to the head of the page.

```tsx
module.exports = {
  managerEntries,
  config,
  // Add the font in
  previewHead: (head) => `
    ${head}
    <link href="https://example.com/font.css" rel="stylesheet" />
  `,
};
```
