### ISSUE TITLE
[Angular] Storybook infers String property with `string.length == 0` as uneditable

### ISSUE THREAD

**Issue by activenode** [storybookjs/storybook#12986]
**Describe the bug**
Most precisely and quickly described in code as follows.

Use an angular component:

```
@Component({...})
export default class SomeComponent {
  @Input()
  label = '';
}
```
^ Using this component within storybook stories will show the label as "private" / uneditable because the string attribute has a preset-value of '' which is `label.length === 0`

![image](https://user-images.githubusercontent.com/9058762/97887204-dfc49880-1d29-11eb-858d-645724e100dc.png)

```
@Component({...})
export default class SomeComponent {
  @Input()
  label = ' ';
}
```
^ However using this component (note the string change!) within storybook stories will show the label as editable - which is the expected behaviour.

![image](https://user-images.githubusercontent.com/9058762/97887432-3500aa00-1d2a-11eb-9d75-3ccebd2559ac.png)

**To Reproduce**

1. Go to https://github.com/activenode-demos/sb-angular-empty-value-inference-bug
2. Follow the README.md steps to provoke/show the bug

**Expected behavior**
Storybook should infer the variable as editable and the value should become an editable field in the Controls Tab.

**System**
```
Environment Info:

  System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
  Binaries:
    Node: 12.18.4 - ~/.nvm/versions/node/v12.18.4/bin/node
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.4/bin/npm
  Browsers:
    Chrome: 86.0.4240.111
    Safari: 14.0
  npmPackages:
    @storybook/addon-actions: ^6.0.28 => 6.0.28 
    @storybook/addon-docs: ^6.0.28 => 6.0.28 
    @storybook/addon-essentials: ^6.0.28 => 6.0.28 
    @storybook/addon-links: ^6.0.28 => 6.0.28 
    @storybook/angular: ^6.0.28 => 6.0.28 
```

**Additional context**
I could not reproduce this behaviour in any way with React but that is also due to the fact that in React the types are differently mapped.

**Comment by activenode** [comment]
Say no more. I think I found the culprit. I will provide a fix soon.

**Comment by shilman** [comment]
Yippee!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.0-beta.2 containing PR #12994 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
