### ISSUE TITLE
Stories click not working in Netlify

### ISSUE THREAD

**Issue by tiavina-mika** [storybookjs/storybook#12993]
Nothing happen when clicking the stories in the left, the page does not change. 
But when I refresh the page it works.

here is the link: https://increzia-storybook.netlify.app/?path=/story/home-main--main-component

here is my ./storybook/main.js

`
const TsconfigPathsPlugin = require('tsconfig-paths-webpack-plugin');

module.exports = {
  stories: [
    '../components/**/**/*.stories.tsx',
  ],
  addons: [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    '@storybook/addon-viewport',
    'storybook-addon-paddings',
    '@storybook/addon-actions',
  ],
  typescript: {
    check: false,
    checkOptions: {},
    reactDocgen: 'react-docgen-typescript',
    reactDocgenTypescriptOptions: {
      shouldExtractLiteralValuesFromEnum: true,
      propFilter: (prop) =>
        prop.parent ? !/node_modules/.test(prop.parent.fileName) : true,
    },
  },
  webpackFinal: async (config) => {
    config.resolve.plugins.push(new TsconfigPathsPlugin());
    return config;
  },
};
`

**Comment by shilman** [comment]
Try upgrading to 6.1?

```
npx sb upgrade --prerelease
```

**Comment by theKashey** [comment]
The same experience with 6.0.26 and 6.0.28 - everything perfect in dev mode, but not able to change a story in a static build.

`6.1.0-beta.1` works perfectly

**Comment by shilman** [comment]
Thanks @theKashey - we're in the process of releasing 6.1 to fix this and a bunch of related problems

**Comment by tiavina-mika** [comment]
![image](https://user-images.githubusercontent.com/42656064/98243681-56a69f00-1f7f-11eb-906f-3dc4e2f169f3.png)

As @shilman suggested, I ugrade to 6.1.0-beta.2 version but have this error in a static build

**Comment by shilman** [comment]
@tiavina-mika can you open a separate issue for this and include a repro repo?

**Comment by tiavina-mika** [comment]
@shilman  , done, here: https://github.com/storybookjs/storybook/issues/13032
