### ISSUE TITLE
Control for file uploads

### ISSUE THREAD

**Issue by Haaxor1689** [storybookjs/storybook#13004]
**Is your feature request related to a problem? Please describe**
Often we want to have components that contain some external images like user avatars, header images etc. like in the example below. This does not need to only concern images, there may be use-cases for other file types as well like loading some sample data from JSON file etc.

**Describe the solution you'd like**

It would be nice to have a control that acts like a file input and allows you to select image (or any other) file from your computer.

**Describe alternatives you've considered**

Right now my solution is to use a text field which accepts a url to online image.

**Are you able to assist to bring the feature to reality?**

Probably yes.

**Additional context**

Example where this would be helpful:

![image](https://user-images.githubusercontent.com/25706343/98038936-357a6d00-1e1e-11eb-999d-12d84e57e075.png)

**Comment by shilman** [comment]
This is one of the data types from addon-knobs that didn't get ported to addon-controls. Any interest in porting it?

https://github.com/storybookjs/storybook/blob/next/addons/knobs/src/components/types/Files.tsx

**Comment by Haaxor1689** [comment]
I probably won't have time to do that right now.

**Comment by dominictwlee** [comment]
Happy to look into this.

**Comment by shilman** [comment]
Ooh-la-la!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.0-alpha.26 containing PR #13544 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
