### ISSUE TITLE
6.1 beta Search and sidebar behavior

### ISSUE THREAD

**Issue by domyen** [storybookjs/storybook#13000]
## RFCs for edge cases

1. Update empty state for search: show a “no results” message. Currently we show no results and no messages which makes the UI appear broken.
![image](https://user-images.githubusercontent.com/263385/97999859-da169380-1db9-11eb-997a-55a48aef4665.png)

2. No recently opened: When there are no recently opened items continue showing the treeview. Currently we show nothing so it looks like the treeview completely disappeared. You can reproduce this state by clearing recently opened.

![image](https://user-images.githubusercontent.com/263385/97999877-de42b100-1db9-11eb-8a2b-dc685b6cab73.png)

3. When you click on the expand all button, keyboard navigation no longer behaves as I'd expect. Every time I press enter the focus returns to the expand all button no matter what I focus on using my keyboard. [Video here](https://www.loom.com/share/f59f0098d78a43f5ae75472b7db4407c)

4. Keyboard navigation skips items when a folder is expanded and collapsed. [Video here](https://www.loom.com/share/d45e6ee827bd41709a4860a5b00e491a). When expanding and collapsing using the right and left arrow keys I expect the focus to start at the very beginning of the list not in the middle.

5. Keyboard navigation focus doesn't transfer to the "folder" items. [Video here](https://www.loom.com/share/b8a81131ceb440bea59ebca5045a5f50)

**Comment by ghengeveld** [comment]
> 1. Update empty state for search: show a “no results” message. Currently we show no results and no messages which makes the UI appear broken.

I added a "No components found" message:

<img width="217" alt="Screenshot 2020-11-05 at 21 12 17" src="https://user-images.githubusercontent.com/321738/98291560-997e6c00-1fab-11eb-8e76-14d97ff6f2c5.png">

> 2. No recently opened: When there are no recently opened items continue showing the treeview. Currently we show nothing so it looks like the treeview completely disappeared. You can reproduce this state by clearing recently opened.

Instead of showing the treeview, I made sure that the history will always show at least one item. After all, you will always have a component selected, so technically that one should always be at the top of the list.

> 3. When you click on the expand all button, keyboard navigation no longer behaves as I'd expect. Every time I press enter the focus returns to the expand all button no matter what I focus on using my keyboard. [Video here](https://www.loom.com/share/f59f0098d78a43f5ae75472b7db4407c)

Fixed this by removing focus from the expand-all button when using the arrow keys to navigate the tree.

> 4. Keyboard navigation skips items when a folder is expanded and collapsed. [Video here](https://www.loom.com/share/d45e6ee827bd41709a4860a5b00e491a). When expanding and collapsing using the right and left arrow keys I expect the focus to start at the very beginning of the list not in the middle.

This was a bug and is fixed now.

> 5. Keyboard navigation focus doesn't transfer to the "folder" items. [Video here](https://www.loom.com/share/b8a81131ceb440bea59ebca5045a5f50)

Fixed. Now when you click a node to expand/collapse it, it will get highlighted as well.

**Comment by shilman** [comment]
ZOMG!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.0-beta.4 containing PR #13027 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
