### ISSUE TITLE
When start script is using NODE_ENV=production , the storybook is not able to navigate between each component 

### ISSUE THREAD

**Issue by stanleyyuenyiu** [storybookjs/storybook#13017]
**Describe the bug**
storybook/react v6.0.28 :  When start script is using NODE_ENV=production , the storybook is not able to navigate between each component 

**To Reproduce**

1. define startup script in package json with below command
```
"scripts": {
 "storybook": "NODE_ENV=production start-storybook  -p 6006"
}
```
2. run below command in terminal 
`yarn run storybook
`
3. open http://localhost:6006 in your browser

4. navigate between each component or different component story by clicking the left menu

**Expected behavior**
Storybook are able to navigate to the target component or the target component's story

**Screenshots**
![image](https://user-images.githubusercontent.com/4983053/98209692-52c44e00-1f7a-11eb-887a-951db8d8dc6d.png)

Above image show that the url has already change to second story, but the screen and the active menu item still keep on the first story

**Comment by shilman** [comment]
If you're running 6.0, try running with `--no-dll`. Otherwise try upgrading to 6.1:

```
npx sb upgrade --prerelease
```

**Comment by stanleyyuenyiu** [comment]
Thanks, --no-dll solve the issue, we can close the issue, but may i know why --no-dll solve the issue?

**Comment by shilman** [comment]
@stanleyyuenyiu The short answer is I don't actually know why `--no-dll` solves it. The long answer is that `--no-dll` disables webpack DLLs, which can sometimes cause library version mismatches (e.g. user code is running React 17 and DLL is running React 16), and this can cause difficult-to-debug runtime errors. We are getting rid of webpack DLLs completely in 6.1: #12637
