### ISSUE TITLE
storybook_docs_dll is not defined after update to 6.1.0-beta.2

### ISSUE THREAD

**Issue by daniloab** [storybookjs/storybook#13023]
**Describe the bug**
After updated the storybook for beta version 6.1.0-beta.2 got the following error:

`external "storybook_docs_dll":1 Uncaught ReferenceError: storybook_docs_dll is not defined`

**To Reproduce**

1. Update to the beta version 6.1.0-beta.2
2. run storybook and try to open the stories page

**Expected behavior**

**Screenshots**
![Screen Shot 2020-11-05 at 14 39 40](https://user-images.githubusercontent.com/19939822/98277370-10990d80-1f76-11eb-8cab-66b51a4a9c28.png)

![Screen Shot 2020-11-05 at 14 49 19](https://user-images.githubusercontent.com/19939822/98277406-1d1d6600-1f76-11eb-969f-e1e546bf4dcd.png)

**System**

```terminal
Environment Info:

  System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz
  Binaries:
    Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.16.3/bin/npm
  Browsers:
    Chrome: 86.0.4240.183
    Firefox: 77.0.1
    Safari: 14.0
  npmPackages:
    @storybook/addon-actions: 6.1.0-alpha.17 => 6.1.0-alpha.17 
    @storybook/addon-console: 1.2.2 => 1.2.2 
    @storybook/addon-docs: 6.1.0-alpha.17 => 6.1.0-alpha.17 
    @storybook/addon-knobs: 6.1.0-alpha.17 => 6.1.0-alpha.17 
    @storybook/addon-links: 6.1.0-alpha.17 => 6.1.0-alpha.17 
    @storybook/addon-storyshots: 6.1.0-alpha.35 => 6.1.0-alpha.35 
    @storybook/addon-storysource: 6.1.0-alpha.32 => 6.1.0-alpha.32 
    @storybook/react: 6.1.0-beta.2 => 6.1.0-beta.2 
    @storybook/storybook-deployer: 2.8.6 => 2.8.6 
```

**Additional context**
The update was made to try to fix the react import bug related here https://github.com/storybookjs/storybook/issues/12881

**Comment by shilman** [comment]
All of your storybook package versions should match.

You can do this automatically (recommended) by:
- stable: `npx sb upgrade`
- prerelease: `npx sb upgrade --prerelease`

**Comment by sibelius** [comment]
fixed for us on v6.1.0-rc.0

**Comment by lcastroemello** [comment]
Hello everyone! I am unfortunately having this issue even after trying both the stable and the prerelease upgrades there. Any other suggestions there?

**Comment by shilman** [comment]
@lcastroemello Did you try removing `node_modules` and/or lockfiles and reinstalling? What's the output of `npx sb info` in your project?

**Comment by sgwanlee** [comment]
> All of your storybook package versions should match.
> 
> You can do this automatically (recommended) by:
> 
> * stable: `npx sb upgrade`
> * prerelease: `npx sb upgrade --prerelease`

Thanks. it solved like a calm
