### ISSUE TITLE
Is there a way to run storybook in a kind of a "dry run", headlessly?

### ISSUE THREAD

**Issue by serguei-at-bemaximus** [storybookjs/storybook#13038]
Hi,

Love storybook. Can't figure out how to achieve this. I'd like to run something that checks that all stories (with all examples) render without errors, and exits with a 0 exit code if that's the case. The idea is to do this in CI (Github actions for example), after the other unit tests, to make sure that new code doesn't break rendering of the stories.

I tried `--smoke-test` and `--docs` but none of that seems to fail if I place an error in the `render` function of the component or the story.

Hope what I'm asking is clear, let me know if need to clarify.

**Comment by shilman** [comment]
Take a look at storyshots: https://github.com/storybookjs/storybook/tree/next/addons/storyshots/storyshots-core

**Comment by serguei-at-bemaximus** [comment]
Thanks @shilman! After having slept on it, I actually realized I can just render the stories using `enzyme` (or whatever testing thing) inside of plain `jest` tests. In the meantime it means I need a "spec" for each story, but I have a feeling I can refactor away that boilerplate at some point. 

Still, I appreciate your reply as now I know about storyshots for when they come in handy.

**Comment by shilman** [comment]
@serguei-at-bemaximus or you can use storyshots and get all that for free 😉

**Comment by serguei-at-bemaximus** [comment]
I'm happy with adding a jest test to check that the stories render without issues. Storyshots look like a potential option too. Closing the issue.
