### ISSUE TITLE
Storybook change logo

### ISSUE THREAD

**Issue by JohnCasab** [storybookjs/storybook#13035]
Hello Storybook community,

I have build my own vue-storybook with couple of stories, but what I really want is change the logo on upper left corner this one: 

<img width="206" alt="Skærmbillede 2020-11-06 kl  16 04 00" src="https://user-images.githubusercontent.com/72789740/98381036-9e91f880-2049-11eb-888c-4a2f5c34767e.png">

Im very new to storybook, so I have tried to find it in my repository, but haven't been able to. It should be fairly easy to find it but no success. 

I hope someone in the community can guide me 👍 

Best reagards,

 John

**Comment by shilman** [comment]
See the logo bit in https://storybook.js.org/docs/react/configure/theming#create-a-theme-quickstart

**Comment by JohnCasab** [comment]
@shilman sorry im not following, where is the logo bit??

**Comment by einarlove** [comment]
@JohnCasab Pass a URL to `brandImage`

**Comment by JohnCasab** [comment]
Thank you @einarlove, I will try to 👍

**Comment by jonniebigodes** [comment]
@JohnCasab i've pushed a pull request to to clarify a bit how theming works in Storybook. It's #13161 , take a look at it and any feedback on it would be more than welcome.

Stay safe

**Comment by JohnCasab** [comment]
@jonniebigodes thank you very much, I will take a look at it! 

Have a good weekend

**Comment by hadnet** [comment]
Ok, but in order to work I had to remove "@storybook/preset-create-react-app" (or comment it out) form main.js. I don't know if this is mentioned in the theme [doc](https://storybook.js.org/docs/react/configure/theming#create-a-theme-quickstart) tho so... I'm using SB v6.1.

**Comment by jonniebigodes** [comment]
@hadnet hum...let me circle back to this and see what could be the issue. The documentation was updated with a reproduction using 6.0.x. 

Stay safe

**Comment by hadnet** [comment]
@jonniebigodes in fact I think it's a problem with `main.js` being "stuck" or something like that because it does not detect the changes in `manager.js`. Running `yarn storybook` without editing anything in main.js nothing happens. When edit `main.js` suddenly works again and detect the changes. Weird..

**Comment by shilman** [comment]
@hadnet we added manager caching in 6.1 and apparently it doesn't work well with themes yet. See https://github.com/storybookjs/storybook/issues/13200

**Comment by jonniebigodes** [comment]
@shilman thanks for the heads up and additional insights. Let me know of any further developments and we'll move from there should the documentation needs further adjustments.

**Comment by roiekoper** [comment]
If you're using `storybook-dark-mode` the `brandImage` property will not work for you (it's not worked for me).
You should add more configuration to your `preview.js` file as:

```
export const parameters = {
  actions: { argTypesRegex: "^on[A-Z].*" },
  controls: {
    matchers: {
      color: /(background|color)$/i,
      date: /Date$/,
    },
  },
  darkMode: {
    // Override the default dark theme
    dark: { ...themes.dark, ...brandImage: "blue-logo.svg" },
    // Override the default light theme
    light: {
      ...themes.normal,
      brandImage: "black-logo.svg",
    },
  },
};

```
