### ISSUE TITLE
Not able to change a story in a static build

### ISSUE THREAD

**Issue by tiavina-mika** [storybookjs/storybook#13032]
Nothing happen when clicking the stories in the side, the page does not change in the static build (after yarn build-storybook).
But when I refresh the page it works.

Here is the 6.0.27 repo: https://github.com/tiavina-mika/nextjs-typescript-storybook-boilerplate-demo/tree/feature/storybook-2.0.27

So I upgraded to 6.1.0-beta.3 with `npx sb upgrade --prerelease` , but it's show a blank page instead
the 6.1.0-beta.3 repo is there : https://github.com/tiavina-mika/nextjs-typescript-storybook-boilerplate-demo/tree/feature/storybook-2.1.beta

>     "typescript": "^4.0.5"
>     "next": "10.0.0",
>     "react": "17.0.1",
>     "@storybook/addon-actions": "^6.1.0-beta.3",
>     "@storybook/addon-essentials": "^6.1.0-beta.3",
>     "@storybook/addon-links": "^6.1.0-beta.3",
>     "@storybook/addon-viewport": "^6.1.0-beta.3",
>     "sb": "^6.0.27",

**Comment by glrodasz** [comment]
I got the same issue upgrading from `6.0.26` to `6.0.28` it only happens with the static build. However, I tried to revert the changes even cleaning my yarn.lock file without any luck.

**Comment by shilman** [comment]
@glrodasz try `yarn build-storybook --no-dll`

**Comment by shilman** [comment]
@tiavina-mika when I use your 6.1-beta branch I see `_jsx is not defined`

Closing this as a duplicate to #12952

**Comment by glrodasz** [comment]
> @glrodasz try `yarn build-storybook --no-dll`

That did the trick! For reference: https://github.com/storybookjs/storybook/blob/ce309e49df65572589598da8738f7284d8ede3eb/MIGRATION.md#deprecated-dll-flags

**Comment by tiavina-mika** [comment]
@glrodasz thanks, it works for me.
But I added this to .storybook/main.js too:

```
  babel: async (options) => ({
   ...options,
    plugins: [
      ...options.plugins,
      '@babel/plugin-transform-react-jsx'
    ]
  }),
```
