### ISSUE TITLE
SCSS vars not recognised in vue component.

### ISSUE THREAD

**Issue by rosshulford** [storybookjs/storybook#13034]
```
_Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined variable: "$light-blue".
        on line 204 of /Users/********/Sites/********/src/components/asset/truck/List.vue
>>   border: 2px solid  $light-blue;_

```

Using the preset scss
**My main.js**

```
// .storybook/main.js
const path = require('path');
module.exports = {
  stories: [
    "../src/**/*.stories.mdx",
    "../src/**/*.stories.@(js|jsx|ts|tsx)"
  ],

  addons: [
    '@storybook/addon-actions',
    '@storybook/addon-docs',
    '@storybook/addon-links',
    '@storybook/addon-controls',
    '@storybook/preset-scss'
  ],

  webpackFinal: async (config, { configType }) => {

    // Use Sass loader for vuetify components
    config.module.rules.push({
      test: /\.scss$/,
      use: ['style-loader', 'css-loader', 'sass-loader'],
      include: path.resolve(__dirname, '../src/scss'),
    });
    config.module.rules.push({
      test: /\.svg$/,
      use: ["@svgr/webpack"],
    });
    config.module.rules.push({
      resolve: {
        alias: {
          '@': path.resolve(__dirname, '../src'),
          vue: 'vue/dist/vue.js',
          'vue$': 'vue/dist/vue.esm.js',
        },
      },
    });

    // Return the altered config
    return config;
  },
};

```

**my list component**

```
<style lang="scss" scoped>
.list {
 // some css
  border: 10px solid $light-blue;
}
```

**preview.js** 

```
import "!style-loader!css-loader!sass-loader!../src/scss/_variables.scss";

**My _variables.scss**

$light-blue: #00acec;
body {
  border: 10px solid red;
}
```

If I remove the reference to it, it renders my **list.stories.js** giving red border on the body, so it seems the problem is specifically with the Scss variable

**Comment by mikestu** [comment]
Mine did this as well, and it seemed to be something in the "@storybook/essentials" addon that mine had.  When I commented that out, it all worked again.  I changed it to use individual addons instead, and I found that the "@storybook/addon-docs" is the one interfering with something.  Hope this helps someone.

**Comment by desiboli** [comment]
Hi! I'm experiencing the same problem. I have a setup of Vue 2 (TS) and Vuetify. 
It doesn't load/recognize the global variables.scss file I want to import.

I tried both importing it like this `import "@/styles/variables.scss";` and like this `import '!style-loader!css-loader!sass-loader!../src/styles/variables.scss';`, I have also tried to import it via webpack in .storybook/main.js with sass-loader and sass-recources-loader without success.

This is my .storybook/preview.js file:
```import Vue from 'vue';
import Vuetify from 'vuetify';
import vuetifyOptions from "../vuetify.options";
import "vuetify/dist/vuetify.css";
import "@/styles/variables.scss";
import { addDecorator } from '@storybook/vue';

Vue.use(Vuetify);

addDecorator(() => ({
  vuetify: new Vuetify(vuetifyOptions),
  template: `
    <v-app>
      <v-main>
        <v-container fluid>
          <story/>
        </v-container>
      </v-main>
    </v-app>
    `
}));

export const parameters = {
  actions: { argTypesRegex: "^on[A-Z].*" }
}

**Comment by jimhug034** [comment]
Hi! I have the same problem.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
