### ISSUE TITLE
Storybook tutorial broken: Error: Can't resolve '/icon/percolate.eot?-5w3um4'

### ISSUE THREAD

**Issue by philipmjohnson** [storybookjs/storybook#13043]
**Describe the bug**
I am following the tutorial. When I get to this page:

https://www.learnstorybook.com/intro-to-storybook/react/en/simple-component/

After updating preview.js to include this line:

```
import '../src/index.css';
```

I get this error in the console:

```
ERROR in ./src/index.css (./node_modules/css-loader/dist/cjs.js??ref--9-oneOf-4-1!./node_modules/postcss-loader/src??postcss!./src/index.css)
Module build failed (from ./node_modules/css-loader/dist/cjs.js):
Error: Can't resolve '/icon/percolate.eot?-5w3um4' in '/Users/philipjohnson/github/philipmjohnson/taskbox/taskbox/src'
    at /Users/philipjohnson/github/philipmjohnson/taskbox/taskbox/node_modules/enhanced-resolve/lib/Resolver.js:209:21
    at /Users/philipjohnson/github/philipmjohnson/taskbox/taskbox/node_modules/enhanced-resolve/lib/Resolver.js:285:5
```

The file public/icon/percolate.eot does exist in my repo:

https://github.com/philipmjohnson/taskbox/blob/main/taskbox/public/icon/percolate.eot

**To Reproduce**

1. Download my repo from: https://github.com/philipmjohnson/taskbox
2. cd into the taskbox directory.
3. npm install
4. npm run storybook

**Expected behavior**

The storybook interface at localhost:6006 should be displayed.

**Screenshots**
N/A

**Code snippets**
See above

**System**

```
$ npx sb@next info

Environment Info:

  System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 12.16.3 - /usr/local/bin/node
    npm: 6.14.8 - /usr/local/bin/npm
  Browsers:
    Chrome: 86.0.4240.183
    Safari: 14.0
  npmPackages:
    @storybook/addon-actions: ^6.0.28 => 6.0.28 
    @storybook/addon-essentials: ^6.0.28 => 6.0.28 
    @storybook/addon-links: ^6.0.28 => 6.0.28 
    @storybook/node-logger: ^6.0.28 => 6.0.28 
    @storybook/preset-create-react-app: ^3.1.4 => 3.1.4 
    @storybook/react: ^6.0.28 => 6.0.28 
```

**Comment by shilman** [comment]
Can you please re-open this issue on the learnstorybook repo? Thanks! https://github.com/chromaui/learnstorybook.com

cc @jonniebigodes

**Comment by jonniebigodes** [comment]
@philipmjohnson there's already an open issue addressing a this item. Take a look at [here](https://github.com/chromaui/learnstorybook.com/issues/403), feel free to comment in there.

Stay safe

**Comment by philipmjohnson** [comment]
Perfect! Thanks for the quick response.
