### ISSUE TITLE
Clean install of Create React App + Storybook broken

### ISSUE THREAD

**Issue by mundizzle** [storybookjs/storybook#13044]
**Describe the bug**
Creating a new Create-React-App then installing Storybook doesn't work

**To Reproduce**

1. `npx create-react-app test`
2. `cd test`
3. `npx sb init`

**Expected behavior**
Storybook install completes successfully

**Screenshots**
<img width="599" alt="CleanShot 2020-11-07 at 12 46 34@2x" src="https://user-images.githubusercontent.com/1226055/98451097-8e385700-20f7-11eb-8e3c-68e0eb50b944.png">

**System**
Please paste the results of `npx sb@next info` here.

```Environment Info:

  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
  Binaries:
    Node: 15.0.1 - /usr/local/bin/node
    npm: 7.0.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 86.0.4240.183
    Edge: 86.0.622.63
    Firefox: 81.0.1
    Safari: 14.0
```

**Comment by shilman** [comment]
closing as dupe to #12408
