### ISSUE TITLE
Deprecated dependencies

### ISSUE THREAD

**Issue by jiheapark** [storybookjs/storybook#13061]
**Describe the bug**

I tried to download `@storybook/addon-storyshots-puppeteer` v6.0.28.
But I failed to download it because`axe-puppeteer` is deprecated.
<img width="1679" alt="스크린샷 2020-11-09 오후 6 01 19" src="https://user-images.githubusercontent.com/26865541/98630466-947c3c80-235e-11eb-9b98-89c2f2b2387a.png">

same as `@storybook/react`.
`d` is deprecated.
<img width="1679" alt="스크린샷 2020-11-10 오후 2 17 08" src="https://user-images.githubusercontent.com/26865541/98630922-8e3a9000-235f-11eb-9a0c-31139298e02d.png">

So what should I do if I want to use `storybook` v6.0.28?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
Please paste the results of `npx sb@next info` here.

**Additional context**

**Comment by shilman** [comment]
Try clearing your cache?

```
$ npm info d

d@1.0.1 | ISC | deps: 2 | versions: 4
Property descriptor factory
https://github.com/medikoo/d#readme

keywords: descriptor, es, ecmascript, ecma, property, descriptors, meta, properties

dist
.tarball: https://registry.npmjs.org/d/-/d-1.0.1.tgz
```

**Comment by jiheapark** [comment]
@shilman 
Yes,

```
yarn cache clean
```

I did.

**Comment by shilman** [comment]
@jiheapark your'e using a different registry. i think that's the problem.

**Comment by jiheapark** [comment]
@shilman 

But npm site saying `axe-puppeteer` will be deprecated.
https://www.npmjs.com/package/axe-puppeteer

is it Okay?

**Comment by shilman** [comment]
Until we have a replacement or can remove the feature it'll have to do. PRs welcome!
