### ISSUE TITLE
applyLoaders is not a function

### ISSUE THREAD

**Issue by hazem3500** [storybookjs/storybook#13062]
**Describe the bug**
when opening up storybook I get an error `applyLoaders is not a function` in every story after updating to `6.1.0-beta.6`

**Screenshots**
![error](https://live.staticflickr.com/65535/50586034626_f14ecb9e0a_o.png)

**System**
System:
    OS: Windows 10 10.0.18362
    CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
  Binaries:
    Node: 14.8.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files\nodejs\yarn.CMD
    npm: 6.14.7 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 86.0.4240.183
    Edge: Spartan (44.18362.449.0)
  npmPackages:
    @storybook/addon-a11y: ^6.1.0-beta.6 => 6.1.0-beta.6
    @storybook/addon-actions: ^6.1.0-beta.6 => 6.1.0-beta.6
    @storybook/addon-console: ^1.2.2 => 1.2.2
    @storybook/addon-essentials: ^6.1.0-beta.6 => 6.1.0-beta.6
    @storybook/addon-links: ^6.1.0-beta.6 => 6.1.0-beta.6
    @storybook/node-logger: ^6.1.0-beta.6 => 6.1.0-beta.6
    @storybook/preset-create-react-app: ^3.1.5 => 3.1.5
    @storybook/react: ^6.1.0-beta.6 => 6.1.0-beta.6

**Comment by shilman** [comment]
Does removing `@storybook/addon-console` help?

**Comment by hazem3500** [comment]
@shilman the error is still there after removing `@storybook/addon-console` 😢

**Comment by shilman** [comment]
@hazem3500 Do you have a repro repo you can share?

**Comment by artmsilva** [comment]
I'm also experiencing this issue in 6.1.0

**Comment by shilman** [comment]
@artmsilva do you have a repro repo?

**Comment by artmsilva** [comment]
> @artmsilva do you have a repro repo?

I'll work on one

**Comment by artmsilva** [comment]
I'm still seeing the issue after updating to 6.1.1 but yes I'll work on a repro repo

**Comment by UX-Unicorn** [comment]
I blew out my node modules and deleted package-lock and reinstalled everything and everything started working for me.

**Comment by hazem3500** [comment]
everything works for me now after reinstalling and updating to the latest version

**Comment by Stupidism** [comment]
I met this bug today and found it's caused by not upgrade the whole @storybook family together.
![image](https://user-images.githubusercontent.com/5801015/110770523-5fdcab00-8294-11eb-985a-55bf8be76447.png)
