### ISSUE TITLE
Clean installation doesn't seem to work

### ISSUE THREAD

**Issue by assafg** [storybookjs/storybook#13064]
**Describe the bug**
When creating a new app with CRA and following the instructions (`npx sb init` and `npm run storybook`), opening localhost:6006 doesn't show anything - the page is blank and stuck in "loading" state.

**To Reproduce**

1. npx create-react-app my-app --typescript
2. cd my-app
3. npx sb init
4. npm run storybook
5. observe browser at http://localhost:6006/ is blank

**Expected behavior**
should open the storybook app

**System**
```
  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
  Binaries:
    Node: 15.0.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.0.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 86.0.4240.183
    Safari: 14.0
  npmPackages:
    @storybook/addon-actions: ^6.0.28 => 6.0.28
    @storybook/addon-essentials: ^6.0.28 => 6.0.28
    @storybook/addon-links: ^6.0.28 => 6.0.28
    @storybook/node-logger: ^6.0.28 => 6.0.28
    @storybook/preset-create-react-app: ^3.1.5 => 3.1.5
    @storybook/react: ^6.0.28 => 6.0.28
```

**Comment by shilman** [comment]
closing as duplicate to #12408 

workarounds:
- run with `--no-dll` OR
- upgrade to 6.1-beta `npx sb upgrade --prerelease`
