### ISSUE TITLE
Core: Hide instant-on manager UI

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#13077]
Update the instant-on manager logic to show the UI after the preview has built.

In its current form, instant-on manager highlights the slow preview build. Once we optimize the preview build in 6.2, we should re-enable the logic.

**Comment by ghengeveld** [comment]
Made a follow-up issue: #13083

**Comment by shilman** [comment]
Son of a gun!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.0-rc.0 containing PR #13084 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
