### ISSUE TITLE
control change props' value, then how to update parameters

### ISSUE THREAD

**Issue by hmleo** [storybookjs/storybook#13079]
First,thanks for this powerful tool!
my env is  mdx + vue
Now i encounter a problem, i want to update parameters to update source code, when update component's props value with control. But i found that compont's props created after parameters updated, so i can't change the source code in parameters before get the newest right props value.
So, is there other minds or api supported by storybook to get current args' value（equal to component props' value）when update story's parameters to dynamical update source code 
![image](https://user-images.githubusercontent.com/16745216/98790097-2eff7d00-243e-11eb-815a-9d2818f0956c.png)
![image](https://user-images.githubusercontent.com/16745216/98790147-4179b680-243e-11eb-834d-62aaefa92fa5.png)

version is:
    "@storybook/addon-docs": "^6.0.28",
    "@storybook/addon-essentials": "^6.0.28",
    "@storybook/addon-links": "^6.0.28",
    "@storybook/vue": "^6.0.5",

**Comment by hmleo** [comment]
version is:
    "@storybook/addon-docs": "^6.0.28",
    "@storybook/addon-essentials": "^6.0.28",
    "@storybook/addon-links": "^6.0.28",
    "@storybook/vue": "^6.0.5",

**Comment by shilman** [comment]
Args are dynamic, parameters are static

**Comment by hmleo** [comment]
@shilman yep, it worked like this
![image](https://user-images.githubusercontent.com/16745216/98811911-8e6c8580-245c-11eb-973c-9fa13286df0a.png)
thanks also for reply!

**Comment by yog3sha** [comment]
> Args are dynamic, parameters are static
can you please elaborate?
what about props when set as follows (with vue):
`props: Object.keys(argTypes),`

How to make props dynamic?

**Comment by shilman** [comment]
@yog3sha 

```
props: Object.keys(argTypes),
```

What's happening here, as I understand it, is that this is producing an array of strings. `@storybook/vue` automatically copies the values of `args` into a reactive store, and then this array of strings tells the component what values to look for in the same store. It's a little bit of magic, but all our examples look like this.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
