### ISSUE TITLE
Getting: - No inputs found for this component.  Read the docs - when using addons-docs

### ISSUE THREAD

**Issue by jalopez526** [storybookjs/storybook#13086]
**Describe the bug**
I've been trying to use addons-docs to display component props and all kind of documentations, but no matter what I do I always get the same error: **No inputs found for this component. Read the docs**. This is using the 6.0.28 version of Storybook and Addon-docs.

Note: A monorepo is being used and storybook is a just a separated package which has it's own dependencies. CRA is not being used here.

**Expected behavior**
Props should be populated in Docs.

**Code snippets**
devDependencies:
![image](https://user-images.githubusercontent.com/8070933/98835901-67d82b80-2417-11eb-8e68-42d8685b2e89.png)

main.js:
![image](https://user-images.githubusercontent.com/8070933/98835946-74f51a80-2417-11eb-9251-4879f9725e20.png)

preview.js:
![image](https://user-images.githubusercontent.com/8070933/98835986-82aaa000-2417-11eb-9535-a0b4c0b1cb0e.png)

avatar.stories.tsx
![image](https://user-images.githubusercontent.com/8070933/98837522-6f003900-2419-11eb-8fd5-b19cbeccd623.png)

ProfileAvatar.tsx.
![image](https://user-images.githubusercontent.com/8070933/98836226-d0270d00-2417-11eb-8ff7-fa0416e1a906.png)

**System**
  System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 12.18.4 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
  Browsers:
    Chrome: 86.0.4240.183
    Firefox: 82.0.2
    Safari: 14.0
  npmPackages:
    @storybook/addon-actions: ^6.0.28 => 6.0.28 
    @storybook/addon-docs: ^6.0.28 => 6.0.28 
    @storybook/addon-knobs: ^6.0.28 => 6.0.28 
    @storybook/addon-notes: ^5.3.21 => 5.3.21 
    @storybook/react: ^6.0.28 => 6.0.28

**Comment by shilman** [comment]
Do you have a repro repo you can share?

Also, please try removing `addon-notes`. It might be bringing in bad dependencies since it is 5.3.

**Comment by jalopez526** [comment]
> Do you have a repro repo you can share?
> 
> Also, please try removing `addon-notes`. It might be bringing in bad dependencies since it is v5.3.

I can't share a repo with you, but I can explain you what I've encounter. So, as I told you I'm currently working on a monorepo which has a package for the component and and separeted package for the storybook. If I create a component in the storybook folder it display props well, the problem comes when I try to use a component from the component package, not sure why is not working. They both are being exported as `export { ComponentName}` any thoughts regarding to this to check out?

**Comment by shilman** [comment]
Currently addon-docs requires that your components be defined in the same package as your storybook

**Comment by jalopez526** [comment]
> Currently addon-docs requires that your components be defined in the same package as your storybook

Okay so that's my issue here, no workarounds available?

**Comment by shilman** [comment]
@jalopez526 it can be worked around, but nobody's come up with the recipe yet. probably amounts to tweaking the docgen loader to run on `node_modules`. here's the default:

https://github.com/storybookjs/storybook/blob/next/lib/core/src/server/config/defaults.ts#L8

cc @jonniebigodes

**Comment by jalopez526** [comment]
It's going to take time to me to learn the codebase and also do the changes, I think this is a needed enhancement, maybe can someone help me with a quick temporal approach? Im looking into the docgec loader but doesn't look like I can find a solution soon.

**Comment by jalopez526** [comment]
Any help with this please? I need it urgently

**Comment by patricklafrance** [comment]
@jalopez526 

Have you tried to add a custom "include" to webpack babel-loader?

Something like:

```js
// main.js

modules.exports = {
    webpackFinal: async config => {
        // Assuming your config is in a ".storybook" folder at the root and your components are in a "/packages" at the root.
        config.module.rules[0].include.push(path.resolve(__dirname, "..", "packages"));
        return config;
    }
};
```

**Comment by jalopez526** [comment]
> /\.(mjs|tsx?|jsx?)$/

@patricklafrance thanks for response, this is why i tried and did not work, still getting **No input found for this component**

Component package path: /monorepo/packages/react-lib/src/components
Storybook path: /monorepo/storybook/.storybook

`
webpackFinal: async (config) => {
    config.module.rules.push({
      test: /\.(mjs|tsx?|jsx?)$/,
      include: path.resolve(__dirname, '../../..', 'packages/react-lib/src/components'),
    });
    return config;
  }
`

**Comment by rmunch** [comment]
I've got a similar monorepo setup - I wasn't able to get props to show until I changed `import React from "react"` to `import * as React from "react"`.

**Comment by jalopez526** [comment]
> I've got a similar monorepo setup - I wasn't able to get props to show until I changed `import React from "react"` to `import * as React from "react"`.

Just tried right now that and didn't work aswell, I don't think is a react issue, maybe is a problem with loading component files because there's not located on the same storybook package.

**Comment by patricklafrance** [comment]
@jalopez526 I don't think you want to push a new rule, whar you want is to update the "include" of the existing one to add your components path

**Comment by jalopez526** [comment]
> @jalopez526 I don't think you want to push a new rule, what you want is to update the "include" paths of the existing one to add your components path

This is how i tried first time and still not working:

![image](https://user-images.githubusercontent.com/8070933/100032711-fa40dd80-2dce-11eb-85b6-7eb8caaf2b25.png)

**Comment by jalopez526** [comment]
@rmunch is your monorepo open to see? I need to see if there's something i'm missing because it's not working for me.

**Comment by jalopez526** [comment]
Justa quick update:

Playing around with react docgen public as debug, I found out that actually the /packages folder is being scanned (where component folder lives). But, the **react-component-lib** folder (where actually component lives) is not being scanned. Others packages are being scanned, such as **navigation**. Any thoughts?

![image](https://user-images.githubusercontent.com/8070933/100299858-1083a080-2f6b-11eb-8b55-3f23809a0809.png)

**Comment by patricklafrance** [comment]
Silly guess... have you tried `**/*.tsx, **/*.js` ? Not a glob expert but this is how I usually do it.

I haven't keep up with the latest config for reactDocgenTypeScript but as far I see remember you don't need to specify `include` ?

**Comment by jalopez526** [comment]
@patricklafrance I followed this docs: https://github.com/hipstersmoothie/react-docgen-typescript-plugin#readme#:~:text=include

**Comment by jalopez526** [comment]
Okay so I solved this. It was an issue with typescript and not with storybook, typescript configuration was using ```module : "commonjs", after switching to this to ```false``` it works.

**Comment by Shyam-kotivada** [comment]
hi @jalopez526 , can you share the exact change which is done in your tsconfig file?

**Comment by poplark** [comment]
> Refere



> hi @jalopez526 , can you share the exact change which is done in your tsconfig file?

use `import React from 'react'` and add those settings in tsconfig
```js
{
  "compilerOptions: {
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    // ...
  },
  // ...
}
```
or, just use `import * as React from 'react'` without changing tsconfig
