### ISSUE TITLE
Angular Storybook: Using a service Dependency Injection in a child component

### ISSUE THREAD

**Issue by misha1109** [storybookjs/storybook#13080]
### Bug or support request summary
Using a service DI in a child component that uses data from the same service that was previously initiated by a parent component.
 
I expected there to be a way in the story of the child component, to initiate the service with the mockup data i want (before the story rendering) so then the child component can use it as happens in my app.

### Steps to reproduce
In my app.component I use the service and send it some data
app.component.ts

```js
  constructor(
    private transferStateService: TransferStateService,
    private pricingService: PricingService,
  ) {
  }
  async ngOnInit(): Promise<void> {
    const state = this.transferStateService.getState();
    this.pricingService.initPricing(state.pricing, state.currency);
  }
```

after using this.pricingService.initPricing(state.pricing, state.currency)  I now have some data in the service.
In a child component I use the same service:

pricing.component.ts
```js
  constructor(
    private pricingService: PricingService
  ) { }

  ngOnInit(): void {
    this.pricing = this.pricingService.getPricing();
  }
```

The reason I can use this.pricingService.getPricing() is only that in app.component I already passed to the service all the needed data by calling this.pricingService.initPricing(state.pricing, state.currency)

In my pricing.component.ts story i want to somehow call the pricingService.initPricing with my mockup data so the when the component story is rendered I can use my service there to receive the data.

Currently my pricing.component story: 
```js
export default {
  title: 'core/pricing',
  component: PricingComponent,
  decorators: [
    moduleMetadata({
      imports: [PipesModule, DirectivesModule, BodyModule],
      declarations: [AppComponent]
    })
  ]
} as Meta;

const Template: Story<PricingComponent> = (args: PricingComponent) => ({
  component: PricingComponent,
  props: args,
});

export const Primary = Template.bind({});
Primary.args = {
};
```

### Version

    "@storybook/addon-actions": "^6.0.26",
    "@storybook/addon-essentials": "^6.0.26",
    "@storybook/addon-links": "^6.0.26",
    "@storybook/angular": "^6.0.26",
    "@storybook/storybook-deployer": "^2.8.7",

    "@angular/common": "~10.0.6",
    "@angular/compiler": "~10.0.6",
    "@angular/core": "~10.0.6",

**Comment by Marklb** [comment]
@misha1109 Will `APP_INITIALIZER` work?

Example:
```ts
export default {
  title: 'core/pricing',
  component: PricingComponent,
  decorators: [
    moduleMetadata({
      imports: [PipesModule, DirectivesModule, BodyModule],
      declarations: [AppComponent]
    })
  ]
} as Meta;

function initPricingFactory(pricingService: PricingService) {
  return () => pricingService.initPricing(mockPricing, mockCurrency)
}

const Template: Story<PricingComponent> = (args: PricingComponent) => ({
  moduleMetadata: {
    providers: [
      {
        provide: APP_INITIALIZER,
        useFactory: initPricingFactory,
        multi: true,
        deps: [PricingService]
      }
    ]
  },
  component: PricingComponent,
  props: args,
});

export const Primary = Template.bind({});
Primary.args = {
};
```

Without knowing more about your data and service, I don't know if the following would work, but could you just inject an alternate class for PricingService? That way you could just avoid the calculations also, since the data is just mocked anyway.

Example:
```ts
export default {
  title: 'core/pricing',
  component: PricingComponent,
  decorators: [
    moduleMetadata({
      imports: [PipesModule, DirectivesModule, BodyModule],
      declarations: [AppComponent]
    })
  ]
} as Meta;

class MockPricingService implements Partial<PricingService> {
  getPricing = () => mockPricingData
}

const Template: Story<PricingComponent> = (args: PricingComponent) => ({
  moduleMetadata: {
    providers: [
      { provide: PricingService, useClass: MockPricingService }
    ]
  },
  component: PricingComponent,
  props: args,
});

export const Primary = Template.bind({});
Primary.args = {
};
```

**Comment by misha1109** [comment]
APP_INITIALIZER works perfectly!

Thank you very much for your reply and for creating such an awesome tool as Storybook. Its a wonder:)

**Comment by ravianand1988** [comment]
@Marklb Awesome stuff, Thanks for the examples. :)
