### ISSUE TITLE
Core: Restore instant-on manager UI

### ISSUE THREAD

**Issue by ghengeveld** [storybookjs/storybook#13083]
Revert #13077 whenever we consider preview compilation to be fast enough to warrant opening the browser "instantly" (i.e. when the manager is done).

`git revert 356d534e3b37ea11f37111b4f330a72e757e10a1` should do the trick.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if this is still relevant in SB 7.x.
