### ISSUE TITLE
Particular story `title` values are able to break @storybook/react@6.1.0-beta.7

### ISSUE THREAD

**Issue by surgeboris** [storybookjs/storybook#13082]
**Describe the bug**
When I use "Foo Bar" as a `title` property of the default export of my story — story doesn't render and storybook UI crashes. If I change `title` property of the default export of the story to "FooBar" or "Foo bar" — my story renders successfully and no crash occurs.

**To Reproduce**

1. Check out [the following commit in my minimal reproduction repo](https://github.com/surgeboris/storybook-bug-repro/commit/ad343986d99b25f607406113e38a8a3f546c8413)
2. Run `npm ci`
3. Run `npx start-storybook`
4. Open storybook server's URL in the browser tab
5. See error in the browser console
5. Change `title` property of the default export of `repro.story.js` to any value other than `Foo Bar`.
6. Reload storybook browser tab
7. See that there's no error and story rendered correctly.

**Expected behavior**
I would expect my story to render without errors regardless of it's title.

Or (in case it is illegal to have default export title colliding with one of the non-default export labels) I would expect to see a clearly worded warning instead of the obscure error I can currently see.

**Code snippets**
https://github.com/surgeboris/storybook-bug-repro/commit/ad343986d99b25f607406113e38a8a3f546c8413

**System**
```
Environment Info:

  System:
    OS: Windows 10 10.0.19041
    CPU: (4) x64 Intel(R) Pentium(R) CPU 4415Y @ 1.60GHz
  Binaries:
    Node: 14.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.8 - ~\AppData\Roaming\npm\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.423.0), Chromium (86.0.622.63)
  npmPackages:
    @storybook/react: ^6.1.0-beta.7 => 6.1.0-beta.7
```

**Comment by shilman** [comment]
Confirmed. @ghengeveld it's a corner case where the "hoisted story" is also a root. Which is weird, but shouldn't crash.

**Comment by shilman** [comment]
Huzzah!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.0-rc.0 containing PR #13089 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
