### ISSUE TITLE
Storybook broken on Angular 11 - SCSS

### ISSUE THREAD

**Issue by bryanrideshark** [storybookjs/storybook#13100]
**Describe the bug**

Loading SCSS files is broken on Angular 11 for some reason - The following is what I get from the console:

````

ERROR in ./libs/driver-booking-components/src/lib/driver-carpool-item-display/driver-carpool-item-display.component.scss
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
ValidationError: Invalid options object. Sass Loader has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'includePaths'. These properties are valid:
   object { implementation?, sassOptions?, additionalData?, sourceMap?, webpackImporter? }
    at validate (D:\rideshark-front-end\rs-frontend\node_modules\schema-utils\dist\validate.js:98:11)
    at Object.loader (D:\rideshark-front-end\rs-frontend\node_modules\sass-loader\dist\index.js:30:28)
 @ ./libs/driver-booking-components/src/lib/driver-carpool-item-display/driver-carpool-item-display.component.ts 36:22-77 36:89-144 36:156-211 36:223-278
 @ ./libs/driver-booking-components/src/lib/driver-booking-components.module.ts
 @ ./libs/driver-booking-components/src/index.ts
 @ ./apps/rs-mobile-new/src/app/carpools/carpools.stories.ts
 @ ./apps/rs-mobile-new/src/app/carpools sync ^\.(?:(?:^|[\\\/]|(?:(?:(?!(?:^|[\\\/])\.).)*?)[\\\/])(?!\.)(?=.)[^\\\/]*?\.stories\.ts)$
 @ ./lib-storybook/mobile-carpool-2.0/generated-stories-entry.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./lib-storybook/mobile-carpool-2.0/storybook-init-framework-entry.js ./lib-storybook/mobile-carpool-2.0/preview.js-generated-config-entry.js ./lib-storybook/mobile-carpool-2.0/generated-stories-entry.js ./node_modules/webpack-hot-middleware/client.js?reload=true&quiet=false&noInfo=true ./apps/rs-mobile-new/src/styles.scss

````

**To Reproduce**
Take an Angular 10 app, update to Angular 11, and then try to run Storybook 6.1.0-rc.0

It appears that the default configuration used by Angular CLI has changed, and Storybook is sending invalid Webpack configuration along.

**Comment by bryanrideshark** [comment]
Looking into this further, this may be related to my not updating `@nrwl/builders`.

**Comment by bryanrideshark** [comment]
I just tried 6.1.0-rc.2 and it works now. Thanks!!!

**Comment by shilman** [comment]
Hooray!! Love it when problems fix themselves ❤️

**Comment by tettusud** [comment]
@shilman storybook build is failing, when I have relative imports in my angular components.
For eg I configured paths in ng-package.json for my. angular library
```
  "styleIncludePaths": [
      "../../node_modules/custom/src/scss"
    ]
```
and am importing the scss file under `node_modules/custom/src/scss/custom.scss` following way,
```
@import 'custom"
```
angular build succeeds, but story book throws error , custom not found.

**Comment by ConstanzaEcheverriaCerda** [comment]
> @shilman storybook build is failing, when I have relative imports in my angular components. For eg I configured paths in ng-package.json for my. angular library
> 
> ```
>   "styleIncludePaths": [
>       "../../node_modules/custom/src/scss"
>     ]
> ```
> 
> and am importing the scss file under `node_modules/custom/src/scss/custom.scss` following way, in my angular components scss.
> 
> ```
> @import "custom"
> ```
> 
> angular build succeeds, but story book throws error , custom not found.

Hi @tettusud , Could you solved the problem ?
