### ISSUE TITLE
Unable to preview Angular Material Components in Stories

### ISSUE THREAD

**Issue by Samoji** [storybookjs/storybook#13109]
**Describe the bug**
Hi everyone,

I've an Angular Library project type and I have implemented Storybook to increase the development speed. I've structured the library as suggested by this [post](https://medium.com/angular-in-depth/improve-spa-performance-by-splitting-your-angular-libraries-in-multiple-chunks-8c68103692d0).
To recap, I have multiple modules that exports some Components and I'm able to import just what I need in my "consumer" applications.

My final goal is to build a custom components library on top of Angular Material library and I've some issues while trying to doing this.

In particular, I have a button component which has the following template:
```html
<button mat-button (click)="hello()">Hi 🎈</button>
```

The story associated is as follow:
```typescript
import { Story, Meta } from '@storybook/angular/types-6-0';
import { ButtonComponent } from './button.component';

export default {
    title: 'MyLib/Button',
    component: ButtonComponent
} as Meta;


const Template: Story<ButtonComponent> = (args: ButtonComponent) => ({
    component: ButtonComponent,
    props: args
});

export const Primary = Template.bind({});
Primary.args = { };
```

This is the module content in which I import the Angular Material Button Module:
```typescript
import { NgModule } from '@angular/core';
import { ButtonComponent } from './button.component';
import { MatButtonModule } from '@angular/material/button';

@NgModule({
  declarations: [ButtonComponent],
  exports: [ButtonComponent],
  imports: [MatButtonModule]
})
export class ButtonModule { }
```

**To Reproduce**

If I run the `"storybook": "npm run docs:json && start-storybook -p 6006 -s ./node_modules --no-dll"` command and then navigate to the Story, this is what I see:
![image](https://user-images.githubusercontent.com/2758928/99090972-897c1300-25cf-11eb-935b-ace1f38956a8.png)

I've also inspected the DOM and what I see is that `mat-button` seems to be not evaluated as an Angular component:
![image](https://user-images.githubusercontent.com/2758928/99091106-b6c8c100-25cf-11eb-9933-88b7c2ad783d.png)

Instead, if I publish my library and use the component in another project, the component renders as expected:
![image](https://user-images.githubusercontent.com/2758928/99091407-2179fc80-25d0-11eb-9ad8-93200758d750.png)

In my opinion seems to be some missing configuration inside the button story, I've tried to import the `MatButton` in the story but without success.

**Expected behavior**
I expect to see the Angular Material button in the preview area (iframe).

**System**
```
Environment Info:

  System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz
  Binaries:
    Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 86.0.4240.193
    Edge: Spartan (44.18362.449.0)
  npmPackages:
    @storybook/addon-actions: ^6.0.28 => 6.0.28
    @storybook/addon-essentials: ^6.0.28 => 6.0.28
    @storybook/addon-links: ^6.0.28 => 6.0.28
    @storybook/angular: ^6.0.28 => 6.0.28
```

**Comment by teastman** [comment]
I've had similar difficulties, you need to import any modules you depend on into the story.  Change your default export to add decorators that import the MatButtonModule.

```
import { moduleMetadata } from '@storybook/angular';
import { MatButtonModule } from '@angular/material/button';

export default {
  title: 'MyLib/Button',
  component: ButtonComponent
  decorators: [
    moduleMetadata({
      declarations: [],
      imports: [MatButtonModule],
    }),
  ]
} as Meta;
```

**Comment by Samoji** [comment]
Thanks @teastman, I have imported my ```ButtonModule``` that rely on ```MatButtonModule``` and it works as expected 😉.

**Comment by Ethan-code** [comment]
Hi, could you tell me how you import Angular Material's scss file?
I can't show material styles in stories.

**Comment by Samoji** [comment]
@Ethan-code I have imported a prebuilt theme css file under build > styles section in angular.json.
