### ISSUE TITLE
Docs addon cant see button text

### ISSUE THREAD

**Issue by JohnCasab** [storybookjs/storybook#13106]
Hello Storybook community,

**Describe the issue**
My issue is when I click on the show code when using the docs addon, I dont see the button text, I have to highlight the code before I can se the text. See the screenshots:  

When I DONT mark the code:
<img width="521" alt="Skærmbillede 2020-11-13 kl  11 29 05" src="https://user-images.githubusercontent.com/72789740/99062482-5d4a9d00-25a3-11eb-9c62-9c3adca25d66.png">

When I mark the code:
<img width="456" alt="Skærmbillede 2020-11-13 kl  11 30 57" src="https://user-images.githubusercontent.com/72789740/99062674-a00c7500-25a3-11eb-9f28-58156246ccef.png">

**My code**
button.stories.js 
<img width="631" alt="Skærmbillede 2020-11-13 kl  11 37 06" src="https://user-images.githubusercontent.com/72789740/99063223-7b64cd00-25a4-11eb-9065-59f07e9b5790.png">

and 
Button.vue
<img width="629" alt="Skærmbillede 2020-11-13 kl  11 39 47" src="https://user-images.githubusercontent.com/72789740/99063477-dc8ca080-25a4-11eb-9a70-5d8acd18e96a.png">

**Expected behavior**
See the element text without highlighting it. 

**System**
```
     OS: MacOS catalina 10.15.6
     2,6 GHz 6-Core Intel Core i7

Binaries:
    Node: 14.11.0 - ~/.nvm/versions/node/v14.11.0/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.11.0/bin/npm

Browsers:
  `Chrome: Version 86.0.4240.193 (Officiel version) (x86_64)`
  
```
**NPM packages:**
 ```
   "@storybook/addon-actions": "^6.0.26",
    "@storybook/addon-docs": "^6.0.28",
    "@storybook/addon-essentials": "^6.0.26",
    "@storybook/addon-links": "^6.0.26",
```

I have tired multiple things for a long time now reading lots of issues, but no luck I would really appriciate the help, and please ask if you need more info.

**Comment by shilman** [comment]
This must be a CSS clash between your styles and the highlight CSS

**Comment by JohnCasab** [comment]
Thank you, this solved my problem 👍
