### ISSUE TITLE
Methods not shown use ArgsTable with vue framework

### ISSUE THREAD

**Issue by hmleo** [storybookjs/storybook#13105]
1、env is vue + mdx 
in a component  vue file , i want to show the methods in ArgsTable
```
 props: {
   testProps: {
     type: String,
     default: ''
   }
 },
 methods: {
    /**
     * @public
     */
    search(){
        //
    }
  },
```
```
    "@storybook/addon-docs": "^6.0.28",
    "@storybook/addon-essentials": "^6.0.28",
    "@storybook/addon-links": "^6.0.28",
    "@storybook/vue": "^6.0.5",
```
result is  Props shows correctly, but doesn't show the Methods,
and i test the vue-docgen-api with version 4.31.1 ,it's work rightly;
so where is the problem?
thanks

**Comment by hmleo** [comment]
```
{
  a:"123"
}
```

**Comment by shilman** [comment]
Any chance you can add it? The code that handles the different sections is here: https://github.com/storybookjs/storybook/blob/next/addons/docs/src/frameworks/vue/extractArgTypes.ts#L6

And you'd need to add an example to `examples/vue-kitchen-sink` to test.

**Comment by Nisgrak** [comment]
Amy updates on this?

**Comment by AidenChen** [comment]
Any updates on this?

**Comment by shilman** [comment]
w00t!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-alpha.6 containing PR #16975 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
