### ISSUE TITLE
Storybook Angular: npx sb init fails with code 1.

### ISSUE THREAD

**Issue by jkimmeyer** [storybookjs/storybook#13117]
**Describe the bug**
I am trying to install storybook in an angular application. The `npx sb init` command fails with the following error message using nodejs 12.18.2:
```
Install for [ 'sb@latest' ] failed with code 1
```
**To Reproduce**

1. Create angular app with `ng new app`
2. Go into app folder
3. Add Storybook with `npx sb init`

**Expected behavior**
Install storybook without any problems.

**System**
- @angular/cli: 10.0.8

`npx sb@next info` Fails with the same error message like npx sb init.

**Comment by shilman** [comment]
I'm unable to reproduce. Can you provide more info about your setup?

**Comment by jkimmeyer** [comment]
Thanks for investigating! I just reinstalled my whole node setup and now it works. I guess it was a problem with my node installation.
