### ISSUE TITLE
storyshots-puppeteer: beforeScreenshot and afterScreenshot return types should be promises

### ISSUE THREAD

**Issue by ignas-sedunovas** [storybookjs/storybook#13116]
**Describe the bug**
I've updated `@storybook/addon-storyshots` and `@storybook/addon-storyshots-puppeteer` from `6.0.28` to `6.1.0-rc.2`.
Unexpectedly, I started getting a TS error that a `Promise` cannot be returned from `beforeScreenshot`.

I seems that [imageSnapshot.ts#L15-L17](https://github.com/storybookjs/storybook/blob/next/addons/storyshots/storyshots-puppeteer/src/imageSnapshot.ts#L15-L17) is awaiting the return values from `beforeScreenshot` and `afterScreenshot`, but these functions are not typed to return a `Promise`: [config.ts#L42-L43](https://github.com/storybookjs/storybook/blob/next/addons/storyshots/storyshots-puppeteer/src/config.ts#L42-L43).
I find it a bit strange that it was working before.

**Screenshots**
![image](https://user-images.githubusercontent.com/3921290/99147285-12528780-2680-11eb-909c-43d068a853b0.png)

**System**
```
Environment Info:

  System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 Intel(R) Core(TM) i5-7440HQ CPU @ 2.80GHz
  Binaries:
    Node: 12.18.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.17.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 86.0.4240.198
    Edge: Spartan (44.18362.449.0)
  npmPackages:
    @storybook/addon-actions: ^6.1.0-rc.2 => 6.1.0-rc.2
    @storybook/addon-storyshots: ^6.1.0-rc.2 => 6.1.0-rc.2
    @storybook/addon-storyshots-puppeteer: ^6.1.0-rc.2 => 6.1.0-rc.2
    @storybook/preset-create-react-app: ^3.1.5 => 3.1.5
    @storybook/react: ^6.1.0-rc.2 => 6.1.0-rc.2
```
TypeScript version: `3.9.7`

**Comment by shilman** [comment]
@ignas-sedunovas any chance you can contribute a PR to fix it?

**Comment by shilman** [comment]
Whoopee!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.2 containing PR #13198 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```

Closing this issue. Please re-open if you think there's still more to do.
