### ISSUE TITLE
Cannot hide the Docs tab of a component

### ISSUE THREAD

**Issue by maeriens** [storybookjs/storybook#13111]
**Describe the bug**
I have a story that we use to showcase a version selector for older versions of our Library. For this one in particular, I don't want the Docs tab to be accessible, but I cannot disable it.

**To Reproduce**
In a CSF page, export it as

```javascript
export default {
  title: 'Versions',
  parameters: {
    docs: { disabled: true }
  }
};
```
Using `docs: { disable: true }` without the last D yields same result. Using `docs: { page: null }` shows an empy Docs page.

**Expected behavior**
The Docs tab should not be displayed in the UI.

**Screenshots**
Not he mos useful one but here it is!
![image](https://user-images.githubusercontent.com/5074186/99123292-a79d3f80-25de-11eb-9e80-ce54d52d80c7.png)

**System**
    Node: 12.18.3
    npm: 6.14.6
  npmPackages:
    @storybook/addon-essentials: ^6.0.28 => 6.0.28 
    @storybook/addon-knobs: ^6.0.28 => 6.0.28 
    @storybook/addon-links: ^6.0.28 => 6.0.28 
    @storybook/addons: ^6.0.28 => 6.0.28 
    @storybook/react: ^6.0.28 => 6.0.28

**Comment by shilman** [comment]
See https://github.com/storybookjs/storybook/pull/9095

**Comment by maeriens** [comment]
For anyone stumbling with this issue, the solution with current Storybook (6.1.1) is
```javascript
export default {
  title: 'Name',
  parameters: {
    previewTabs: {
      'storybook/docs/panel': { hidden: true }
    }
  }
};
```

Marking this as closed. Thank you, as always, @shilman :)
