### ISSUE TITLE
Export SourceContext to enable custom Canvas implementations

### ISSUE THREAD

**Issue by dej611** [storybookjs/storybook#13113]
**Is your feature request related to a problem? Please describe**
I tried to implement a custom `Preview`/`Canvas` component with Storybook but hit a situation as the `SourceContext` is not exported by the `addon-docs` module, preventing external access to the source code of a Story.

Previous related issue: #11498

**Describe the solution you'd like**
I'd like to get access to the `SourceContext` in order to access the source code of a Story in my custom `Canvas` implementation.

The simplest solution I thought would be to export the `SourceContainer` as with the other modules:

```js
...
export * from './Source';
export * from './SourceContainer';
...
```

so that I could be able to get the context with:

```js
import { SourceContext } from '@storybook/addon-docs/blocks'
```

**Describe alternatives you've considered**
.

**Are you able to assist to bring the feature to reality?**
Sure

**Additional context**
I was trying to re-implement the `Canvas` component with a custom extension to have a similar feature as the [remark-codesandbox](https://github.com/kevin940726/remark-codesandbox) plugin. I want to declare `Canvas` Story and grab its source code to expose it somehow, like a button to CodeSandbox.

**Comment by shilman** [comment]
PRs welcome! 🙏

**Comment by shilman** [comment]
Yee-haw!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.0-rc.3 containing PR #13118 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
