### ISSUE TITLE
Upgrade to emotion 11 result in runtime error

### ISSUE THREAD

**Issue by openscript** [storybookjs/storybook#13120]
**Describe the bug**
After I've upgraded to emotion 11 from 10 I received a runtime error pointing to Storybook code.

**To Reproduce**

1. Pull https://github.com/openscript/react-dsv-import/tree/feat/upgrade_emotion
2. Run with `yarn dev`
3. Open http://localhost:6006/
4. See error in the console

**Expected behavior**
The storybook should build and come up.

**Screenshots**
![image](https://user-images.githubusercontent.com/1105080/99182780-5fddfb80-2737-11eb-959f-2136590a9c65.png)

**Code snippets**

**System**
```
Environment Info:

  System:
    OS: Linux 5.9 Arch Linux
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 13.11.0 - ~/.asdf/installs/nodejs/13.11.0/bin/node
    Yarn: 1.22.4 - ~/.asdf/installs/nodejs/13.11.0/.npm/bin/yarn
    npm: 6.13.7 - ~/.asdf/installs/nodejs/13.11.0/bin/npm
  Browsers:
    Firefox: 82.0.3
  npmPackages:
    @storybook/addon-actions: ^6.0.28 => 6.0.28 
    @storybook/addon-docs: ^6.0.28 => 6.0.28 
    @storybook/addon-links: ^6.0.28 => 6.0.28 
    @storybook/addon-storysource: ^6.0.28 => 6.0.28 
    @storybook/addons: ^6.0.28 => 6.0.28 
    @storybook/react: ^6.0.28 => 6.0.28 
```

**Additional context**

**Comment by shilman** [comment]
What happens when you run Storybook with the `--no-dll` flag? Or in 6.1-rc which no longer uses webpack DLLs?

**Comment by openscript** [comment]
Thank you @shilman for taking the time and helping me out. **Both `--no-dll` and upgrading to `Storybook 6.1.0-rc.3` fixed the problem.**
