### ISSUE TITLE
Support Adobe's Design Service Packages

### ISSUE THREAD

**Issue by TGTGamer** [storybookjs/storybook#13124]
So recently Adobe XD released the latest update, which includes some amazing features for Design Systems Package (DSP) integrations into tools such as Figma, Visual Studio Code, and partner platforms. I would really love to see Storybook (all versions) support importing & exporting DSP content. 

_Important links:_
Official Documentation: https://github.com/AdobeXD/design-system-package-dsp
XD Implementation: https://letsxd.com/vscode
Video Explanation: https://vimeo.com/466431987

**Describe the solution you'd like**

1. I would like to import a DSP to StoryBook
   1. Automatically import components
   2. Automatically import documentation
2. I would like to export a DSP from StoryBook
   1. Automatically export components
   2. Automatically export documentation

**Describe alternatives you've considered**
Integration with style dictionary: https://www.npmjs.com/package/style-dictionary
- Might be worth looking at, but Adobe's Design Service Package handles this really well.

**Are you able to assist to bring the feature to reality?**
no. Don't have enough experience with StoryBook's backend

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if this is still relevant in SB 7.x.
