### ISSUE TITLE
Nested decorators can't use parent decorator context

### ISSUE THREAD

**Issue by andyrichardson** [storybookjs/storybook#13130]
**Describe the bug**
There seems to be an issue with context provided by decorators only being consumable by stories, and not child decorators.

**To Reproduce**

Consider the following application code
```tsx
/** Some provider used in the application (not specific to storybook). */
const WeatherProvider = () => {
  const location = useLocationContext(); // Consumes context from a parent

  // ...
}
```

Now consider we want to expose that provider in a story.

```tsx
/** Decorator to mock location */
const locationDecorator: DecoratorFn = (Story, context) => {
  return (
    <Location.Provider value={{ lat: 0, lon: 0 }}>
      <Story {...context} />
    </Location.Provider>
  );
};

/** Decorator to add weather provider */
const weatherDecorator: DecoratorFn = (Story, context) => {
  return (
    <WeatherProvider>
      <Story {...context} />
    </WeatherProvider>
  );
};

addDecorator(locationDecorator) // Set up parent context
addDecorator(weatherDecorator) // Set up child context (dependent on parent)
```

**Expected behavior**

The `weatherDecorator` is able to access the context provided by the `locationDecorator`

**Actual result**

The `weatherDecorator` is not able to access the context provided by the `locationDecorator`.

Moving the provider into the story rather than as a decorator works as expected.

**System**
Tried on both `6.0.21` and `6.1.0-rc.3`

**Comment by shilman** [comment]
@tmeasday you've looked at this recently...

**Comment by tmeasday** [comment]
@andyrichardson this is just standard react context? I can't see why it wouldn't work.

Have you inspected the resulting component heirarchy? Do you have a simple reproduction I can look at?

**Comment by andyrichardson** [comment]
@tmeasday thanks for the response - I managed to get round this issue by changing the order of the decorators.

Before

```tsx
addDecorator(locationDecorator) // Set up parent context
addDecorator(weatherDecorator) // Set up child context (dependent on parent)
```

After

```tsx
addDecorator(weatherDecorator) // Set up child context (dependent on parent)
addDecorator(locationDecorator) // Set up parent context
```

**Comment by tmeasday** [comment]
Ahh, got it. Perhaps there is a documentation issue here cc @jonniebigodes

**Comment by jonniebigodes** [comment]
Going to take a look at it and create a small reproduction to see what's wrong. @andyrichardson if you could instead supply the reproduction materialized in the form of a repo it would help a lot. As to get a more accurate view of the issue and we can document it better.

Let me know

Stay safe
