### ISSUE TITLE
Can't set Component prop default value in metadata/destructured props default

### ISSUE THREAD

**Issue by soulchainer** [storybookjs/storybook#13132]
**Describe the bug**
I created a `<Loading>` functional React component with [styled-components](https://github.com/styled-components/styled-components), with a pair of optional props (`color` and `size`), with default values (declared as destructured object in the function).

Storybook doesn't take/detect the default props that way, so I tried to declare it in the `metadata` object in the `stories.js` file. It isn't detected/shown in any place either.

**To Reproduce**

1. Create a functional component with `styled-components` and typed with flow, with default props, declared like this:

```jsx
// @flow
import styled from 'styled-components'
import type { AbstractComponent } from 'react'

type Props = {
  color?: string,
}

const Box: AbstractComponent<Props> = styled.div.attrs(
  ({ color = 'blue' }) => ({ color })
)`
  background-color: ${({ color }) => color};
  height: 100px;
  width: 100px;
`;

export default Box
```

2. Create a `stories.js` like this, declaring also the `default` value:

```js
// @flow
import type { Element } from 'react'
import Box from '.'
import React from 'react'

const metadata = {
  component: Box,
  title: 'Box',
  argTypes: {
    color: {
      description: 'Background color',
      default: 'blue',
    },
  },
}

export default metadata

export const BlueBox = (): Element<typeof Box> => <Box />
```
3. Run Storybook
4. Go to 'Box' → 'BlueBox` story
5. Check `Docs` tab. Doesn't show anything about the types, description... of the component props. It just renders the components and shows a

> No inputs found for this component. Read the docs

Message. The **Read the docs** message isn't helpful, as it links to the root of the docs.
6. Check `Canvas` tab and `Controls` tab inside it. It shows the **Name** and the **Description** of the props, both especified in the `metadata` object. `Default` is empty.

**Expected behavior**

I expected the props defaults info to be rendered in **Docs** tab, or in the **Controls** tab.

**Screenshots**

![Screenshot_2020-11-16 Box - Blue Box ⋅ Storybook](https://user-images.githubusercontent.com/169524/99260653-f84dac00-281b-11eb-85dd-5bdff1fa6942.png)
![Screenshot_2020-11-16 Box - Blue Box ⋅ Storybook_2](https://user-images.githubusercontent.com/169524/99260717-0ac7e580-281c-11eb-949c-b5ebf1f2905e.png)

**System**

Environment Info:

  System:
    OS: Linux 5.9 Arch Linux
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
  Binaries:
    Node: 12.19.0 - ~/.nvm/versions/node/v12.19.0/bin/node
    Yarn: 1.22.10 - /usr/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v12.19.0/bin/npm
  Browsers:
    Firefox: 82.0.3 (also happens in Chromium, not a Browser issue)
  npmPackages:
    @storybook/addon-actions: ^6.0.28 => 6.0.28 
    @storybook/addon-essentials: ^6.0.28 => 6.0.28 
    @storybook/addon-links: ^6.0.28 => 6.0.28 
    @storybook/node-logger: ^6.0.28 => 6.0.28 
    @storybook/preset-create-react-app: ^3.1.5 => 3.1.5 
    @storybook/react: ^6.0.28 => 6.0.28

**Comment by tema1411** [comment]
I have this problem too. 

my short info about component: 

**Grid.ts**
```typescript
import styled from 'styled-components';

export type GridProps = {
  inline?: boolean;
}

export const Grid = styled.div<GridProps>`
  display: ${({inline}) => inline ? 'inline-grid' : 'grid'};
`
```

**Columns.stories.tsx**
```typescript tsx
import {Grid, GridProps} from "../Grid";
import {Story} from "@storybook/react/types-6-0";

export default {
  title: 'test'
}

export const StringProp:Story<GridProps> = () =>  <Grid />
```

![image](https://user-images.githubusercontent.com/33321841/104632479-6a206580-56a6-11eb-9299-74962417ac35.png)

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
