### ISSUE TITLE
Story source code shows "MDXCreateElement" instead of actual source code

### ISSUE THREAD

**Issue by Yakitrak** [storybookjs/storybook#13134]
When using story templates, the source code of component in docs view shows incorrect code. It shows "MDXCreateElement".

**To Reproduce**
1. Use template method to create story
2. Go to docs tab
3. Click show source code

**Expected behavior**
Expect the actual source code, rather than MDXCreateElement.

**Screenshots**
![image](https://user-images.githubusercontent.com/15147598/99278139-98a8ce00-2826-11eb-8955-26ee595ecdad.png)

**Code snippets**
Source: 

```mdx
import { Meta, Story, Canvas } from "@storybook/addon-docs/blocks";
import Button from "../modules/Button";
import "bootstrap/dist/css/bootstrap.min.css";
import "../modules/Button/style.scss";
export const ButtonStory = ({ ...args }) => <Button {...args}>Button</Button>;
<Canvas>
  <Story name="Primary" args={{ variant: "primary" }}>
    {ButtonStory.bind({})}
  </Story>
</Canvas>
```

Expected docs soure code:
```mdx
<Button variant="primary"> Button </Button>
```

Actual docs source code:
```mdx
<MDXCreateElement
  mdxType="Button"
  originalType={() => {}}
  variant="primary"
>
  Button
</MDXCreateElement>
```

**System**
Environment Info:

  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
  Binaries:
    Node: 15.2.0 - ~/.nvm/versions/node/v15.2.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.0.8 - ~/.nvm/versions/node/v15.2.0/bin/npm
  Browsers:
    Chrome: 86.0.4240.198
    Safari: 14.0
  npmPackages:
    @storybook/addon-actions: ^6.0.28 => 6.0.28 
    @storybook/addon-controls: ^6.0.28 => 6.0.28 
    @storybook/addon-docs: ^6.0.28 => 6.0.28 
    @storybook/addon-essentials: ^6.0.28 => 6.0.28 
    @storybook/addon-links: ^6.0.28 => 6.0.28 
    @storybook/preset-scss: ^1.0.3 => 1.0.3 
    @storybook/react: ^6.0.28 => 6.0.28

**Comment by shilman** [comment]
Closing as duplicate to #11542
