### ISSUE TITLE
argstable can't render for typescript React in CRA

### ISSUE THREAD

**Issue by Hujianboo** [storybookjs/storybook#13147]
### Describe the bug
the argstable not renders correctly when the the story provided the component's props,docs can't show the description and render controls properly.
### Steps to reproduce
1. Create a component written in TypeScript

2. write a story by usring CSF
### version

- @storybook/react @6.0.28

### Code Snippets (Optional)
I remove some unnecessary code such as some classes. 
```js
//Alert.tsx
export interface AlertProps {
  /**
   * title
   */
  title: string;
  /**
   * description
   */
  description?: string;
  /**
   * type
   */
  type?: AlertType;
  /**
   * onClose
   */
  onClose?: () => void;
  /**
   * closable
   */
  closable?: boolean;
}
export type AlertType = "success" | "default" | "danger" | "warning";

const Alert: React.FC<AlertProps> = ({
  title,
  description,
  type,
  onClose,
  closable,
}) => {
  const [hide, setHide] = useState(false);
  const handleClose = () => {
    if (onClose) {
      // onClose();
      setHide(!hide);
    }
  };
  return (
      <div className={classes}>
        <span>{title}</span>
        {description && <p className="bobo-alert-desc">{description}</p>}
        {closable && (
          <span  onClick={handleClose}>
            <Icon></Icon>
          </span>
        )}
      </div>
  );
};
Alert.defaultProps = {
  closable: true,
};
export default Alert; 

//alert.stories.tsx
import React from "react";
import { Story, Meta } from "@storybook/react/types-6-0";
import Alert, { AlertProps } from "./alert";

export default {
  title: "Alert",
  component: Alert,
} as Meta;
const Template: Story<AlertProps> = (args) => <Alert {...args}></Alert>;
export const NormalAlert = Template.bind({});
NormalAlert.args = {
  title: "normal alert",
  type: "success",
  description: "success",
  closable: true,
};


```

### Result
![1605620290694](https://user-images.githubusercontent.com/17348813/99397036-72b22500-291d-11eb-88dd-3c2e5305b452.jpg)
the component has annotations of the props, descirptions are none and also don't show the types of props.which step have i lost ? (I know I can use the argTypes to add the argtables but it's inefficient. )

**Comment by mrdepontes** [comment]
I tried this in mdx and didn't see the table at all. But, when I changed to JSX it worked. 
![image](https://user-images.githubusercontent.com/3287910/150599446-4efbd946-12e0-4acd-a683-289287ed8a44.png)

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
