### ISSUE TITLE
Ability to disable storybook shortcuts

### ISSUE THREAD

**Issue by fippli** [storybookjs/storybook#13146]
**Is your feature request related to a problem? Please describe**
The keyboard shortcut feature makes the UI jump around if I end up typing when for example some input is out of focus or if I want to have custom key events with the same keys as the shortcuts.

**Describe the solution you'd like**
Since I have no interest in the shortcuts whatsoever (and they also limit custom key events) I would suggest have the possibility to disable them entirely. I could be something like a checkbox in the shortcuts menu:
- [ ] disable shortcuts

**Describe alternatives you've considered**
...

**Are you able to assist to bring the feature to reality?**
I'm happy to help in any way I can. 

**Additional context**
...

**Comment by shilman** [comment]
Closing as dupe to #6569

**Comment by mrchantey** [comment]
I don't think this is a dupe, #6569 is about the config, whereas the suggestion here is a checkbox in the menu. 

For live storybook sites we don't have access to the config, ie this [threejs first person controls demo](https://drei.pmnd.rs/?path=/story/controls-firstpersoncontrols--first-person-controls-story) is unsuable.

**Comment by noreff** [comment]
@mrchantey I also don't think closing it is right, as a workaround you can try using query parameter like this - https://drei.pmnd.rs/?path=/story/controls-firstpersoncontrols--first-person-controls-story&shortcuts=false

**Comment by shilman** [comment]
We're not going to implement a UI for that, but we should fix the configuration if it's not currently working
