### ISSUE TITLE
Warning about cross-spawn

### ISSUE THREAD

**Issue by daveisfera** [storybookjs/storybook#13150]
**Describe the bug**
This error recently started showing up when running `yarn install`:
```
warning workspace-aggregator-62eaed5e-52cb-4cd5-8a2a-9d2744bbe06a > test > @storybook/react > @storybook/core > trash > xdg-trashdir > @sindresorhus/df > execa > cross-spawn-async@2.2.5: cross-spawn no longer requires a build toolchain, use it instead
```

**To Reproduce**
1. Run `yarn install` with the `@storybook/react` module in `package.json`
2. See error

**Expected behavior**
Warning would not be issued by `yarn install`

**System**
```
Environment Info:

  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  Binaries:
    Node: 12.19.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
  Browsers:
    Chrome: 86.0.4240.198
    Firefox: 80.0.1
    Safari: 14.0
```

**Comment by razh** [comment]
Should be resolved by https://github.com/sindresorhus/trash/pull/105

**Comment by gaetanmaisse** [comment]
Version 7 of `trash` drops support of Node < 10, @shilman @ndelangen should we wait for Storybook 7.0 to update this dep as the apps currently require `"node": ">=8.0.0"`?

**Comment by shilman** [comment]
I think we're going to get rid of `trash`, see https://github.com/storybookjs/storybook/issues/13168

**Comment by shilman** [comment]
Great Caesar's ghost!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.3 containing PR #13211 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```

Closing this issue. Please re-open if you think there's still more to do.
