### ISSUE TITLE
Instant Manager only working on 3rd build after upgrade

### ISSUE THREAD

**Issue by tooppaaa** [storybookjs/storybook#13156]
**Describe the bug**
Instant manger should be working on 2nd run

**To Reproduce**

1. Clone https://github.com/storybookjs/e2e-testing-starter/tree/master/cra-3.4.1
2. `npx sb init`
3. `yarn storybook`
4. `npx sb@next upgrade`
5. `yarn storybook` => No Cache expected
5. `yarn storybook` => Cache expected but none
6. `yarn storybook`=> Using Cache Manager

**Comment by shilman** [comment]
Ermahgerd!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.0-rc.6 containing PR #13165 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
