### ISSUE TITLE
Centered layout is broken when the rendered preview has vertical scroll

### ISSUE THREAD

**Issue by stof** [storybookjs/storybook#13157]
**Describe the bug**
When the rendered story is bigger than the height of the preview iframe, the `centered` layout is still centering the rendered content vertically inside the body. But this means that the content overflows on the top of the body as well, which cannot be reached with the scrollbar. This also happens if horizontal scrolling is involved instead with a wider content
the old addons-centered addon did not have such issue

**To Reproduce**
this can be reproduced using the `core-scroll--story-4` story of the official storybook (linked https://storybook.js.org/docs/react/get-started/examples) when replacing the `sb-main-padded` class with `sb-main-centered` on the body to change the layout (there is no UI to switch layout AFAICT)

**Expected behavior**
The centering (horizontal or vertical) should happen only when there is remaining space, but not when the content overflows.

**Screenshots**
![image](https://user-images.githubusercontent.com/439401/99547611-046e7080-29b8-11eb-8aef-080eb216c910.png)

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
Environment Info:

  System:
    OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
  Binaries:
    Node: 12.19.0 - /usr/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 6.14.8 - ~/.local/bin/npm
  Browsers:
    Firefox: 82.0.3
  npmPackages:
    @storybook/addon-a11y: ^6.0.13 => 6.0.26 
    @storybook/addon-knobs: ^6.0.13 => 6.0.26 
    @storybook/addon-storysource: ^6.0.13 => 6.0.26 
    @storybook/addon-viewport: ^6.0.13 => 6.0.26 
    @storybook/addons: ^6.0.13 => 6.0.26 
    @storybook/html: ^6.0.13 => 6.0.26 
    @storybook/theming: ^6.0.13 => 6.0.26 

But this also happen in the official storybook example, which uses 6.1.0-rc.4

**Additional context**

**Comment by shilman** [comment]
Yee-haw!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.3 containing PR #13217 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```

Closing this issue. Please re-open if you think there's still more to do.
