### ISSUE TITLE
Document names of icon that can be used in toolbar.

### ISSUE THREAD

**Issue by errnesto** [storybookjs/storybook#13154]
In the documetation for toolbars and globals I have example code for how to set a icon to circlehollow,
but I don't know what other names are available.

Eventually I found this list: https://www.chromatic.com/component?appId=5a375b97f4b14f0020b0cda3&name=Basics%7CIcon&buildNumber=13899

It would be nice if this could be linked in the documentaion :-) under https://storybook.js.org/docs/react/essentials/toolbars-and-globals

**Comment by jonniebigodes** [comment]
@errnesto  going to close this issue if you don't mind. A recent pull request was merged that addressed this.

Feel free to re-open regarding any follow up. 

Stay safe

**Comment by tremby** [comment]
For anyone looking, it's at https://5a375b97f4b14f0020b0cda3-wbeulgbetj.chromatic.com/?path=/story/basics-icon--labels (linked from https://storybook.js.org/docs/react/faq#what-icons-are-available-for-my-toolbar-or-my-addon).

**Comment by AndrewCraswell** [comment]
I am never able to find these in the docs, and always have to go searching until I find this issue and eventually find @tremby'a comment then link to the FAQ. Seems the FAQ was the wrong place for docs about the toolbar icons. Shouldn't it just live under the [toolbars and globals](https://storybook.js.org/docs/react/essentials/toolbars-and-globals) section? This is the first google result when searching for "storybook toolbar icons", and seems the most logical place.

**Comment by Walnussbaer** [comment]
> [@jonniebigodes](https://github.com/jonniebigodes) I am never able to find these in the docs, and always have to go searching until I find this issue and eventually find [@tremby](https://github.com/tremby)'s comment then link to the FAQ. Seems the FAQ was the wrong place for docs about the toolbar icons. Shouldn't it just live under the [toolbars and globals](https://storybook.js.org/docs/react/essentials/toolbars-and-globals) section? This is the first google result when searching for "storybook toolbar icons" and seems the most logical place.
> 
> Edit: Oof, the storybook isn't up to date either. I am often trying to recreate the theme switcher shown in the docs, but none of these icons are documented anywhere anymore. I had to play a name guessing game to get them all working, which I remember also doing a couple of months ago :/
> 
> ![image](https://github.com/storybookjs/storybook/assets/1908292/0d19b74f-48f8-4038-adc5-1cf0791bb957)
> 
> I've got a really bad memory, so I'll probably find myself searching for this again in a couple months. I'll just drop the correct icon names here for myself and others who come back to this issue frequently :P
> 
> ![image](https://github.com/storybookjs/storybook/assets/1908292/0feddc67-9b3e-4dc0-9345-0207ffdc4135)

Thank you so much for sharing this!
