### ISSUE TITLE
DocPages not pulling through DocGen comments on export default components

### ISSUE THREAD

**Issue by tommaton** [storybookjs/storybook#13167]
**Describe the bug**
When I have a component which has been exported as default eg.
``` 
const Button: React.FC<IButtonProps> = ({})

export default Button
```
Then none of the DocGen comments come are show in the DocsPage for the components.

But when they exported as a `const`
``` 
export const Button: React.FC<IButtonProps> = ({})
```

**Expected behavior**
I expect this it to still pull through the DocGen comments into the DocPage whether it be a `export default` or `export const`

**System**
Environment Info:

  System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Binaries:
    Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
    Yarn: 1.22.5 - ~/.yvm/shim/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.3/bin/npm
  Browsers:
    Chrome: 87.0.4280.67
    Edge: 86.0.622.69
    Firefox: 81.0
    Safari: 14.0.1
  npmPackages:
    @storybook/addon-a11y: ^6.0.28 => 6.0.28 
    @storybook/addon-essentials: ^6.0.28 => 6.0.28 
    @storybook/addon-info: ^5.3.21 => 5.3.21 
    @storybook/addon-viewport: ^6.0.28 => 6.0.28 
    @storybook/addons: ^6.0.28 => 6.0.28 
    @storybook/preset-typescript: ^3.0.0 => 3.0.0 
    @storybook/react: ^6.0.28 => 6.0.28 
    @storybook/theming: ^6.0.28 => 6.0.28 

**Additional context**
Using TypeScript and Yarn Workspaces

**Comment by shilman** [comment]
Closing this as a duplicate to #9556
