### ISSUE TITLE
Naming and hierarchy documentation is broken

### ISSUE THREAD

**Issue by mahammedzkhan** [storybookjs/storybook#13169]
**Describe the bug**
The page which displays naming and hierarchy is broken:
https://storybook.js.org/docs/react/writing-stories/naming-components-and-hierarchy

**To Reproduce**

1. Go to https://storybook.js.org/docs/react/writing-stories/naming-components-and-hierarchy
2. See JS error

**Expected behavior**
Ability to read the documentation

**Screenshots**
![image](https://user-images.githubusercontent.com/3067041/99655568-2ae5e780-2a5c-11eb-8343-82217c86e5c8.png)

**System**
N/A

**Additional context**
Shouldn't this be covered through Cypress or something else?
If you disable JS, you can still access it.

**Comment by mahammedzkhan** [comment]
Closed because wrong project.

**Comment by shilman** [comment]
@mahammedzkhan it's actually the right project. found the bug and fixed in db762304c9... deploying now.
