### ISSUE TITLE
Storybook 6.2 Release 🤝

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#13160]
Storybook 6.2 will focus on improved compatibility with the JS ecosystem

## Schedule

- ✅ `6.2.0-alpha.0` 2020-12-01
- ✅ `6.2.0-beta.0` 2021-02-22 
- ✅ `6.2.0-rc.0` 2021-03-15
- 🏁 `6.2.0` 2021-03-30

## Contents

- **Vue 3** - Official support for the latest version of Vue.
- **Webpack 5** - Experimental support for the latest version of Webpack.
- **Angular** - Overhauled Angular support.
- **Svelte** - Overhauled Svelte support.
- **Controls++** - Improvements including URL sync, JSON editor, filtering, sorting, and more.

[🧾 Migration instructions](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#from-version-61x-to-620)

**Comment by bismarkhenao** [comment]
Hi @shilman, can I help with this?

**Comment by shilman** [comment]
@bismarkhenao Absolutely. I'll be organizing some issues for the 6.2 milestone and will post it here for anybody who's interested in contributing. Also, we have a discord chat where the community hangs out, and joining is the best way of getting involved: https://discord.gg/UUt2PJb

**Comment by bismarkhenao** [comment]
> @bismarkhenao Absolutely, thanks so much for your interest! I'll be organizing some issues for the 6.2 milestone and will post it here for anybody who's interested in contributing. Also, we have a discord chat where the community hangs out, and joining is the best way of getting involved: https://discord.gg/UUt2PJb

Got it! Thanks!!

**Comment by VincentLanglet** [comment]
IMHO, as long as the manager builder is using webpack 4, the release should not talk about webpack 5 support.

Having both webpack 4 and webpack 5 in the node modules is really bad practice which can lead to weird behavior.
See https://github.com/storybookjs/storybook/issues/14012 or https://github.com/symfony/webpack-encore/issues/942#issuecomment-785202381.

**Comment by kayue** [comment]
Second @VincentLanglet . Storybook 6.2 is causing error in [symfony/stimulus-bridge](https://github.com/symfony/stimulus-bridge) .

**Comment by VincentLanglet** [comment]
Take a look at https://github.com/storybookjs/storybook/issues/14044, there is a solution to avoid using two different versions of webpack

**Comment by darkowic** [comment]
> DeprecationWarning: Relying on the implicit PostCSS loader is deprecated and will be removed in Storybook 7.0.
If you need PostCSS, include '@storybook/addon-postcss' in your '.storybook/main.js' file

What if not relying on it? How to get rid of the warning?

**Comment by fabian-michael** [comment]
@darkowic 

 Run 

```bash
yarn add -D @storybook/addon-postcss postcss
```

and this to the addons in your main.js

```JavaScript
{
	name: "@storybook/addon-postcss",
	options: {
		postcssLoaderOptions: {
			implementation: require('postcss')
		}
	}
}
```

**Comment by darkowic** [comment]
> @darkowic
> 
> Run
> 
> ```shell
> yarn add -D @storybook/addon-postcss postcss
> ```
> 
> and this to the addons in your main.js
> 
> ```js
> {
> 	name: "@storybook/addon-postcss",
> 	options: {
> 		postcssLoaderOptions: {
> 			implementation: require('postcss')
> 		}
> 	}
> }
> ```

@fabian-michael yeah, but what if **I don't use postcss and don't need this addon?**

**Comment by shilman** [comment]
@darkowic this is a warning for anybody who does use it. we plan to remove it in 7.0, so we want people to switch over now. since you don't use it and don't want the warning, do you have any suggestions on what we can do about it?

**Comment by darkowic** [comment]
> @darkowic this is a warning for anybody who does use it. we plan to remove it in 7.0, so we want people to switch over now. since you don't use it and don't want the warning, do you have any suggestions on what we can do about it?

I prefer to avoid warnings in the console. In this case, I have to add this warning or see a console warning. If right now, I know that I do not use it there is no option to hide this warning without actually installing the not used addon. I can live with the addon and a commend to remove later...

**Comment by shilman** [comment]
@darkowic I understand not wanting to see warnings, especially when they don't apply to you. I'm just not sure there's a lightweight way to fix it other than what you suggested

**Comment by darkowic** [comment]
> @darkowic I understand not wanting to see warnings, especially when they don't apply to you. I'm just not sure there's a lightweight way to fix it other than what you suggested

Well, some option to quiet this warning maybe. Not sure how this could be set tbh. In the main config? Anyways, it's a minor issue.

**Comment by petermikitsh** [comment]
Webpack stats' errors-only option might suppress the deprecation warning:

```tsx
module.exports = {
  //...
  stats: 'errors-only',
};
```

https://webpack.js.org/configuration/stats/

**Comment by matamatanot** [comment]
https://github.com/storybookjs/storybook/releases/tag/v6.2.0
🎉
