### ISSUE TITLE
Cannot read property disable of undefined

### ISSUE THREAD

**Issue by SimonSiefke** [storybookjs/storybook#13173]
**Describe the bug**

**To Reproduce**

1. Upgrade storybook version
2. It shows an error message `Cannot read property disable of undefined`

**Expected behavior**
No error

**Screenshots**
![grid2](https://user-images.githubusercontent.com/23744935/99681409-6396b880-2a7e-11eb-9b3d-356bb136af8a.png)

**Code snippets**
```
// .storybook/preview.js
import { addDecorator } from '@storybook/react';
import { reactRouterWrapper } from './decorators';
import { withKnobs } from '@storybook/addon-knobs';
import { addons } from '@storybook/addons';
import { themes } from '@storybook/theming';
import 'normalize.css';
import '../public/assets/fonts.css';
import '../src/uikit/styles/global.scss';

addDecorator(reactRouterWrapper);
addDecorator(withKnobs);

addons.setConfig({
  theme: themes.dark,
});

/**
 * @type {import('@storybook/react').Parameters}
 */
export const parameters = {
  backgrounds: {
    default: 'default',
    values: [
      { name: 'default', value: '#ffffff' },
      { name: 'light-gray', value: '#F5F5F5' },
      { name: 'primary', value: '#a1028f' },
      { name: 'secondary', value: '#c7105c' },
      { name: 'dark-mode', value: '#333333' },
    ],
  },
  controls: { expanded: true, hideNoControlsWarning: true },
  layout: 'fullscreen',
};
```

**System**
```
Environment Info:

  System:
    OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  Binaries:
    Node: 14.13.1 - ~/.nvm/versions/node/v14.13.1/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.13.1/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.13.1/bin/npm
  Browsers:
    Chrome: 87.0.4280.66
    Firefox: 83.0
  npmPackages:
    @storybook/addon-actions: 6.1.0 => 6.1.0 
    @storybook/addon-backgrounds: 6.1.0 => 6.1.0 
    @storybook/addon-centered: 5.3.21 => 5.3.21 
    @storybook/addon-essentials: ^6.1.0 => 6.1.0 
    @storybook/addon-info: 5.3.21 => 5.3.21 
    @storybook/addon-knobs: ^6.1.0 => 6.1.0 
    @storybook/addon-viewport: 6.1.0 => 6.1.0 
    @storybook/addons: ^6.1.0 => 6.1.0 
    @storybook/react: 6.1.0 => 6.1.0 
    @storybook/theming: ^6.1.0 => 6.1.0 

```

**Comment by shilman** [comment]
Do you have a repro repo you can share?

**Comment by shilman** [comment]
@SimonSiefke what version are you upgrading from?

**Comment by SimonSiefke** [comment]
Thanks for investigating, I will try to make a repro repo

**Comment by shilman** [comment]
Missed the stack trace @SimonSiefke --that's probably enough actually. @yannbf can you investigate?

**Comment by dpouliot** [comment]
I'm getting the same error.

**Comment by artmsilva** [comment]
I'm also experiencing this issue.

**Comment by shilman** [comment]
Jeepers creepers!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.1 containing PR #13175 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by yannbf** [comment]
Hey @dpouliot @artmsilva @SimonSiefke do you have something like this in your main.js?
```
module.exports = {
  addons: [
    '@storybook/addon-backgrounds/register',
  ],
}
```

if so, could you use `'@storybook/addon-backgrounds'` instead (without /register) and report if the addon is working back again? Thanks!

**Comment by dpouliot** [comment]
> Hey @dpouliot @artmsilva @SimonSiefke do you have something like this in your main.js?
> 
> ```
> module.exports = {
>   addons: [
>     '@storybook/addon-backgrounds/register',
>   ],
> }
> ```
> 
> if so, could you use `'@storybook/addon-backgrounds'` instead (without /register) and report if the addon is working back again? Thanks!

It was in my manager.js as an import statement. I upgraded to 6.1.1 and removed /register from addon-backgrounds and the error went away and Storybook is working smoothly. Thanks!
