### ISSUE TITLE
6.1: Storyshot content shifted

### ISSUE THREAD

**Issue by petermikitsh** [storybookjs/storybook#13178]
**Describe the bug**

After upgrading to 6.1, I had to regenerate storyshot baselines because screens shifted a couple pixels.

Example: my chip is slightly lower on the right. Storyshot on left generated with 6.0, right is 6.1.

<img width="851" alt="Screen Shot 2020-11-19 at 9 19 38 AM" src="https://user-images.githubusercontent.com/1571918/99700916-a50c7100-2a48-11eb-94dc-43c420a18690.png">

**To Reproduce**

- Generate baselines with 6.0
- Upgrade to 6.1
- Observe storyshot diff failures

**Expected behavior**

Storyshots should be identical between 6.0 and 6.1

**Screenshots**

Here's another example:

<img width="856" alt="Screen Shot 2020-11-19 at 9 23 30 AM" src="https://user-images.githubusercontent.com/1571918/99701152-eb61d000-2a48-11eb-9374-89cacdf72336.png">

**Code snippets**

Maybe this has something to do with layouts?

`.storybook/preview.tsx`:

```
export const parameters = {
  layout: 'centered',
};
```

**System**

```
$ npx sb@next info

Environment Info:

  System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
  Binaries:
    Node: 12.18.0 - ~/.nvm/versions/node/v12.18.0/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.18.0/bin/npm
  Browsers:
    Safari: 12.1.2
```

**Additional context**

**Comment by shilman** [comment]
Probably related to layout parameter changes @ndelangen @ghengeveld ?

**Comment by ghengeveld** [comment]
Must be this one: https://github.com/storybookjs/storybook/commit/fe0552648ca75efed4c1097bde51f0858fbfa182

**Comment by ghengeveld** [comment]
By the way I don't see a visual difference in the images provided, but I'm not sure what I'm supposed to see. Should certain pixels be highlighted because they changed, or is that not how storyshots works? As far as I'm aware Chromatic hasn't detected any visual differences between 6.0 and 6.1.

**Comment by petermikitsh** [comment]
@ghengeveld I believe it's the the css rule `content: ''`;


Here's 6.0 vs 6.1 (see 6.1 has scrollbar):

<img width="1251" alt="Screen Shot 2020-11-20 at 8 36 00 AM" src="https://user-images.githubusercontent.com/1571918/99825198-8e7b1e00-2b0b-11eb-8346-c53ec334b60b.png">
<img width="1251" alt="Screen Shot 2020-11-20 at 8 36 08 AM" src="https://user-images.githubusercontent.com/1571918/99825203-91760e80-2b0b-11eb-9876-d18b9dd74858.png">

Here's 6.1 with the rule turned off:

<img width="1251" alt="Screen Shot 2020-11-20 at 8 36 15 AM" src="https://user-images.githubusercontent.com/1571918/99825209-92a73b80-2b0b-11eb-85b1-0d23e4b73a9a.png">

**Comment by shilman** [comment]
Ta-da!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.2 containing PR #13192 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```

Closing this issue. Please re-open if you think there's still more to do.
