### ISSUE TITLE
Storybook Docs v6.1.0: Page "Naming components and hierachy" broken (404)

### ISSUE THREAD

**Issue by mayashavin** [storybookjs/storybook#13171]
**Describe the bug**
Page "Naming components and hierachy" broke right after loaded due to React render issue.
Storybook Docs v6.1.0

**To Reproduce**

1. Go to https://storybook.js.org/docs/vue/writing-stories/naming-components-and-hierarchy
2. Open DevTools.

**Expected behavior**
Page loaded normally

**Screenshots**
![Screen Shot 2020-11-19 at 14 49 38](https://user-images.githubusercontent.com/6650139/99668800-dc921200-2a76-11eb-806a-4191c743edae.png)

**Comment by stefanprobst** [comment]
see also: https://github.com/storybookjs/frontpage/issues/187

**Comment by shilman** [comment]
Fixed. Thanks @mayashavin !
