### ISSUE TITLE
Angular material types showing errors in 6 version. 

### ISSUE THREAD

**Issue by dhondiramjawade** [storybookjs/storybook#13188]
**Angular Material type showing like 'export type XYX was not found in '@angular/material/Xyz'**
I am trying to install storybook 6 in NX Angular workspace for a particular library. 
It was successfully installed and also generated .strories.ts files, but while serving that particular library I'm facing lots of errors. 

1. **It will not understand any custom interface.** 
   like. I have created one type for an input i.e  **type KeyValue = interface {[key string : string ]}**
   but when we generate the .stories.ts file it will understand. it will generate input property with text() knob. 
2. **Showing error for material types which is my main question.**
  like. I have created one component ex. app-input-box which has   **appearance** input with type **MatFormFieldAppearance**
  which imported from **'@angular/material/form-field'**.
  EX: **import { MatFormFieldAppearance } from '@angular/material/form-field';**
              **@Input() appearance: MatFormFieldAppearance = 'standard';**
finally it showing error  like 
WARNING in .xyz/xyz.component.ts
"export 'MatFormFieldAppearance' was not found in '@angular/material/form-field'

**To Reproduce**
Could not generate. 

**Expected behavior**
It has to be support types.

**Screenshots**
![image](https://user-images.githubusercontent.com/46644972/99780023-ec275e80-2b3b-11eb-8d46-40a298d06d3a.png)

**Code snippets**
![image](https://user-images.githubusercontent.com/46644972/99780513-9a330880-2b3c-11eb-9972-1a495ba4a46c.png)

**System**
![image](https://user-images.githubusercontent.com/46644972/99780815-031a8080-2b3d-11eb-9048-884a385f8c49.png)
![image](https://user-images.githubusercontent.com/46644972/99780979-44ab2b80-2b3d-11eb-9a4b-d6317b8d3e4b.png)
![image](https://user-images.githubusercontent.com/46644972/99781023-51c81a80-2b3d-11eb-9ac2-d4dc4eb72fe9.png)

**Additional context**

**Comment by Marklb** [comment]
I think this is the same problem as #12900. In the comments of that issue, I described the problem and workarounds.

**Comment by dhondiramjawade** [comment]
Thank you team for your quite reply.
@Marklb thanks, your solution works ..!
Just need to add **type** in the import.
**LIke**` import type from '@package/xzy' `

**Comment by dhondiramjawade** [comment]
Closing this. Once again **Thank you, guys ..!**
