### ISSUE TITLE
ArgsTable won't display info properly

### ISSUE THREAD

**Issue by darklight9811** [storybookjs/storybook#13187]
**Describe the bug**
If I define a meta that contains the argTypes info about the component, it will only display inside canvas controls, but not inside of the docs tab using MDX.

**To Reproduce**

1. Create a component
2. Add *.stories.mdx file for it
3. Create a Meta component describing a argType: name, description, table, etc...
4. Add a ArgsTable of the type of the component
5. Run storybook

**Expected behavior**
It should display all the info about the args.

**Screenshots**
![image](https://user-images.githubusercontent.com/20667774/99761589-3cb7a100-2ad5-11eb-8777-e73dfba6ac8b.png)
![image](https://user-images.githubusercontent.com/20667774/99761661-64a70480-2ad5-11eb-9d3d-9658606d2b61.png)

**System**
```
  System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
  Binaries:
    Node: 14.3.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.14.0 - D:\programas\laragon\bin\yarn\bin\yarn.CMD
    npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 87.0.4280.66
    Edge: Spartan (44.18362.449.0)
  npmPackages:
    @storybook/addon-a11y: ^6.1.1 => 6.1.1 
    @storybook/addon-essentials: ^6.1.1 => 6.1.1 
    @storybook/addon-links: ^6.1.1 => 6.1.1
    @storybook/addons: ^6.1.1 => 6.1.1
    @storybook/react: ^6.1.1 => 6.1.1
    @storybook/theming: ^6.1.1 => 6.1.1
```

**Comment by darklight9811** [comment]
As a bonus, if you update the comments inside of a typescript file, it will only update if you restart the storybook server.

**Comment by shilman** [comment]
@darklight9811 Do you have a repro repo you can share?

**Comment by darklight9811** [comment]
@shilman 
https://github.com/darklight9811/storybook-bug

**Comment by darklight9811** [comment]
@shilman Any updates to this?

**Comment by patrickalima98** [comment]
Hello every one! Same problem here, @shilman any news about this?

**Comment by shilman** [comment]
To get controls you need to target a specific Story ID. Updating your example fixes it:

```
<ArgsTable story="^" />
```

@jonniebigodes we probably need to update the example to distinguish between the two use cases https://storybook.js.org/docs/react/writing-docs/doc-blocks#mdx

As for the HMR refresh bug, I've filed a separate issue and will track it there.

**Comment by darklight9811** [comment]
@shilman shouldn't be the prop `of` be enough for that?

**Comment by shilman** [comment]
What would it control?

**Comment by darklight9811** [comment]
The component to watch the props, because what other use would it have?

**Comment by shilman** [comment]
A component instance doesn't exist without getting instantiated. A story is what instantiates it. Thus ArgsTable can **control** component instances (stories) but can only **display** the props for a component.

**Comment by jonniebigodes** [comment]
@darklight9811 i'm going to clone the repository you included (thank you very much for that 👍 ) and factor in the comment @shilman mentioned to adjust the docs. I'll let you know once the pull request is up.

Stay safe

**Comment by adityaphilips** [comment]
@shilman I used <ArgsTable story="specific-story-id" /> in my mdx file and  am working on lit element  ,but after adding story id it throws error like cannot read properties of undefined (reading id) in my storybook ,I added some dummy set of code here please take a look and tell me how to resolve it.

import {
  Meta,
  Description,
  Canvas,
  Story,
  ArgsTable,
} from '@storybook/addon-docs';
import {html} from 'lit';


<Meta title="XYZ"
argTypes={{
    label: {
      name: 'ABXDE ',
      description: 'XYZ Label',
      control: {
        type: 'text'
      },
      table: {
        type: {
          summary: 'The label contents',
           }
      }
    }
  }}
  />

# XYZ

<ArgsTable story="basic-components-xyz--xyz" />

<Canvas id="canvas">
  <Story id="basic-components-xyz--xyz" />
</Canvas>

**Comment by riotrah** [comment]
> @shilman I used (ArgsTable story="specific-story-id") in angular bracket in my mdx file and am working on lit element ,but after adding story id it throws error like cannot read properties of undefined (reading id) in my storybook ,I added some dummy set of code here please take a look and tell me how to resolve it.
> 
> import {Meta,Description,Canvas,Story, ArgsTable,} from '@storybook/addon-docs'; import {html} from 'lit'; <Meta title="XYZ" argTypes={{ label: { name: 'ABXDE ', description: 'XYZ Label', control: { type: 'text' }, table: { type: { summary: 'The label contents', } } } }} />
> 
> (ArgsTable story="basic-components-xyz--xyz" /) used angular bracket here also

We've been seriously struggling with this for a long time now too. I just cannot find _any_ information on this. I'm not even using MDX. _All_ I want to do is to render an ArgsTable for every story in the page that has them defined, or at least be told it is impossible, and maybe why not, in the context of "remixing" the docs page (per docs within `preview.js`) 

_Anything_ I use for ArgsTable's props (either or both of `of`/`story`), including using the story's ID, name and the component's reference, nothing works. It always simply displays the exact same cryptic, undocumented, stack-traceless error: `"Cannot read properties of undefined (reading id)"`. I'd greatly and desparately appreciate any help on this.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
