### ISSUE TITLE
"Show toolbar -- T" missing from "..." menu

### ISSUE THREAD

**Issue by kirkisrael** [storybookjs/storybook#13182]
**Describe the bug**
"Show toolbar    T" is missing from the "..." menu above the sidebar
"Show sidebar  S" and "Show addons. A" are present, and pressing T toggles the sidebar already
(which is confusing if you don't know about it"

**To Reproduce**
1. Start Storybook
2. Click on "..."
3. Note the lack of "Show toolbar  T"
4. Press T and hide and show the toolbar anyway

**Expected behavior**
"..." menu has "Show toolbar  T" and the keyboard shortcut continues to work

**System**
Environment Info:
  System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Binaries:
    Node: 12.17.0 - /usr/local/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 87.0.4280.67
    Firefox: 80.0.1
    Safari: 14.0
  npmPackages:
    @storybook/addon-a11y: ^6.0.18 => 6.0.21 
    @storybook/addon-essentials: ^6.0.18 => 6.0.21 
    @storybook/addon-links: ^6.0.18 => 6.0.21 
    @storybook/addon-storysource: ^6.0.18 => 6.0.21 
    @storybook/addons: ^6.0.18 => 6.0.21 
    @storybook/react: ^6.0.18 => 6.0.21

**Comment by DallasGale** [comment]
Hey SB, @shilman I can give this one a crack.. happy to contribute to the project.

**Comment by shilman** [comment]
@DallasGale much appreciated! 🙏

**Comment by DallasGale** [comment]
@shilman  here is the PR https://github.com/storybookjs/storybook/compare/next...DallasGale:next

**Comment by shilman** [comment]
@DallasGale looking great. is there a reason you didn't create the PR yourself?

**Comment by DallasGale** [comment]
@shilman PR is here.. https://github.com/storybookjs/storybook/pull/14437

**Comment by DallasGale** [comment]
> @DallasGale looking great. is there a reason you didn't create the PR yourself?

sorry it was a mistake.. i thought it had been created.

**Comment by shilman** [comment]
aha cool, thanks so much for putting this together! really appreciate it! 💯  will approve/merge as soon as we finish stabilizing 6.2, which should be in a week or two.

**Comment by DallasGale** [comment]
Great, looking forward to upgrading existing projects to v6 soon...

**Comment by shilman** [comment]
Shiver me timbers!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.3.0-alpha.3 containing PR #14437 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
