### ISSUE TITLE
Storybook caches failing manager builds

### ISSUE THREAD

**Issue by koop** [storybookjs/storybook#13199]
**Describe the bug**
Storybook caches failing manager builds, which makes build failures difficult to debug.

**To Reproduce**
I ran into this while debugging #12893.

1. Throw an error in a babel plugin used by the manager.
2. Run the storybook dev server, observe the error, and that browser UI fails to load.
3. Restart the dev server. Notice the error is missing, and the that browser UI still fails to load.
4. Remove `./node_modules/.cache`.
5. Restart the dev server again. Notice the error appears again, and that browser UI fails to load.

**Expected behavior**
The manager should not cache failing builds. This will make it easier for users to debug any build issues.

**System**
Please paste the results of `npx sb@next info` here.
```
 System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
  Binaries:
    Node: 10.16.0 - ~/.nodenv/versions/10.16.0/bin/node
    Yarn: 1.19.1 - ~/.yarn/bin/yarn
    npm: 6.9.0 - ~/.nodenv/versions/10.16.0/bin/npm
  npmPackages:
    @storybook/addon-controls: 6.1.1 => 6.1.1
    @storybook/addon-docs: 6.1.1 => 6.1.1
    @storybook/react: 6.1.1 => 6.1.1
```

**Comment by shilman** [comment]
Yee-haw!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.4 containing PR #13230 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```

Closing this issue. Please re-open if you think there's still more to do.
