### ISSUE TITLE
Management of `react` and `react-dom` dependencies

### ISSUE THREAD

**Issue by gaetanmaisse** [storybookjs/storybook#13194]
## What is this?

I want to use this issue to follow and discuss:
 - React as regular/peerDep issue
 - `unmet peer dependency` warnings when running installing deps

## Context

Storybook packages are split into 3 "types":
 - `lib`: these packages contain framework-agnostic code that power Storybook, for instance, webpack config for both server and UI part, React components of Storybook UI, code enabling data exchange between packages, etc. Some of these packages depend on `react` and `react-dom`
 - `app`: these are the app-specific packages, there is one for each framework like React, Angular, Vue, Preact, etc. They contain all the tooling to bridge/integrate user's components in Storybook (via story files). They don't use `react` directly (expect `@storybook/react` of course) but use multiple `lib` packages
 - `addon`: these are extra packages that can be added to enhance Storybook features, for instance: set a11y filters, define a shared background, etc. They are optional, some of them are "official" (developed by the Storybook team) and others come from the community. Some of them include both a UI part and a "server"/processing part. They use `lib` packages, and many of them are also using `react` directly to build UI of new toolbar or pane.

## Current situation

For Storybook to properly work we need to be sure all `libs` and `addons` are using the same version of `react` and `react-dom` as they end up in a single React app. For now:
 - `libs` using React are declaring both `react` and `react-dom` as peerDependencies
 - `addons` have regular dependencies on some `lib` packages and declare both `react` and `react-dom` as peerDependencies:
   - because they use React directly
   - OR to satisfy peerDependencies of `lib` packages (transitive peer deps)
 - `apps` have both `react` and `react-dom` as regular dependencies, except for `@storybook/react` in which they are peerDependencies

To ensure we are using a single version of React, there is a Webpack alias on `react` so all Storybook packages
are requiring/importing the same React package.

## Current issue

As a Storybook user in an Angular project:
 - I bootstrap a new Angular app and add Storybook
 - I have `@storybook/angular` as devDep in my project (added via `sb init` for instance)
 - I run `yarn install` then `yarn storybook`
 - Everything is fine, there are no yarn warning nor Storybook error
 - I add an `addon` (for instance `@storybook/addon-backgrounds`)
 - When I run `yarn install` I get some missing peer dep warnings as the addon have `react` and `react-dom` as peer dep
 - However, `yarn storybook` is working just fine because `@storybook/angular` provided `react` and `react-dom`

With 3+ addons, each `yarn install` results in a flood of warnings leading to a poor UX.

## What we tried

1) Before Storybook 6.0, `react` and `react-dom` were peer dep of all `apps`, so it was to the Storybook user to install them
directly in their project.

--> Cons:
 - Users of non react framework were unhappy because they had to install and update react themselves
 - Some issues were reported by Vue users about TypeScript global types for JSX (conflicting with react ones)

2) In 6.0 we tried to put `react` and `react-dom` as regular deps in all the packages using them directly and counting
on the webpack alias to make everything build with a single version of react. When React 17 was released it was a real
fail, we had to release a version where we soften the version range of `react` deps, hoping yarn and npm will be able
to dedupe react versions and end up with either 16.x or 17. :crossed-finger:

3) In 6.1, the current version (see #Current situation), we tried to work around the warnings by using `peerDependenciesMeta` and setting `react` + `react-dom` as `optional` in all `addons`. We were hoping Yarn will not display any warnings but:
 - There are still a lot of warnings because even if `react` and `react-dom` are optional for `addons`, they are not for
the `libs` required by the addons
 - Optional peer dep is tricking Yarn 1 classic but not Yarn 2

**Comment by shilman** [comment]
> Optional peer dep is tricking Yarn 1 classic but not Yarn 2

Is this a bug in Yarn 2, or a deprecated feature, or are we using it wrong?

**Comment by gaetanmaisse** [comment]
In fact, Yarn 2 is much stricter (and safer) about dependencies you can require in your package. To be able to do so the dependency must be listed as a dep (or peerDep) of your package, otherwise 💥 . In v1 or npm, as long as the dep is here (in `node_modules`, so maybe required by another dep) everything is fine.

**Comment by gaetanmaisse** [comment]
- Runtime issue should be fixed by #13195. TLDR: 
Use `require.resolve` to resolve `react` and `react-dom` from `@storybook/core`, as they are declared as peer dependencies this will get them from the parent which is one of the `apps`, and in the case of `@storybook/react` it will get them from the parent which is usually the user's project.

- About `unmet peer dependency` warnings when running installing deps with some `addons`, the webpack alias will properly work after ⬆️  will be merged so we have the following options to get rid of them: 
  - 1️⃣    Remove `react` and `react-dom` from the dependencies of `addons` 
  - 2️⃣    Move `react` and `react-dom` to a regular dependency again, they'll be aliased to the correct one now. And we can set the version to `*` (i.e. `"react": "*"`) to highlight the fact that React's version set here isn't significant.

@merceyz and I prefer to go with 2️⃣

**Comment by shilman** [comment]
Yowza!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.5 containing PR #13195 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by CyberStrike** [comment]
Was having issues with peer dependencies this was my solution.

### Issue 
Storybook Vue 6.1.x upgrade `'react-dom/package.json'`

### Describe the bug
Upgrading from 6.0.26 to 6.1.11 results in a build failure.

```
WARN Failed to load preset: ".../@storybook/core/dist/server/manager/manager-preset.js"
ERR! Error: Cannot find module 'react-dom/package.json'
```

### Solution

I was able to solve this by removing all the storybook packages.

```
    @storybook/addon-actions
    @storybook/addon-docs
    @storybook/addon-essentials
    @storybook/addon-knobs
    @storybook/addon-viewport
    @storybook/vue
```

and re-installing 

```
   @storybook/vue
   @storybook/addon-essentials
```

By doing this it installs the peer dependencies and Storybook compiles properly.

**Comment by SteveFromAccounting** [comment]
I installed an unrelated package that had `react-dom` and `react` as peer dependencies, and it suddenly triggered warnings from all the storybook dependencies I had about react-dom being a missing peer dep. Except, my project is Vue and so I don't have a reason to install react-dom. Is this expected?

**Comment by shilman** [comment]
@SteveFromAccounting `@storybook/vue` should have `react`/`react-dom` as regular dependencies because storybook's own UI built in React. It's strange that it would warn you about this ... but there's a lot of things that don't make sense in the JS package world... 🤷

**Comment by SteveFromAccounting** [comment]
That does make a lot of sense that `@storybook/vue` would've installed react-dom already, but in fact when I run `npm list`, it's not in the tree at all, nor is it in package-lock.json. However, I do see that `react-dom` is specified as a dependency of `@storybook/vue` in the lock file, so this is all very confusing. I posted it in this issue because it seemed relevant, though I'm still trying to fully understand what the [PR here](https://github.com/storybookjs/storybook/pull/13195) did:

```javascript
// package-lock.json
// ...
"@storybook/vue": {
      "version": "6.2.9",
      "resolved": "https://sinopia.nmlv.nml.com/@storybook%2fvue/-/vue-6.2.9.tgz",
      "integrity": "sha512-mAXY1+/zn5gR+qDr6OzEj5AZgLlsw1qdarvQLf7fFH078oTPTQ7c/WzFUp3TaHd2M+ijGD8lb/HHBZqg37NoJA==",
      "dev": true,
      "requires": {
        "@storybook/addons": "6.2.9",
        "@storybook/core": "6.2.9",
        "@storybook/core-common": "6.2.9",
        "@types/webpack-env": "^1.16.0",
        "core-js": "^3.8.2",
        "global": "^4.4.0",
        "react": "16.14.0",
        "react-dom": "16.14.0",
        "read-pkg-up": "^7.0.1",
        "regenerator-runtime": "^0.13.7",
        "ts-dedent": "^2.0.0",
        "ts-loader": "^8.0.14",
        "vue-docgen-api": "^4.34.2",
        "vue-docgen-loader": "^1.5.0",
        "webpack": "4"
      },
      "dependencies": {
        "core-js": {
          "version": "3.12.1",
          "resolved": "https://sinopia.nmlv.nml.com/core-js/-/core-js-3.12.1.tgz",
          "integrity": "sha1-a1r0/1VhbAikTThvH1EJF/8gQRI=",
          "dev": true
        },
        "global": {
          "version": "4.4.0",
          "resolved": "https://sinopia.nmlv.nml.com/global/-/global-4.4.0.tgz",
          "integrity": "sha512-wv/LAoHdRE3BeTGz53FAamhGlPLhlssK45usmGFThIi4XqnBmjKQ16u+RNbP7WvigRZDxUsM0J3gcQ5yicaL0w==",
          "dev": true,
          "requires": {
            "min-document": "^2.19.0",
            "process": "^0.11.10"
          }
        },
        "process": {
          "version": "0.11.10",
          "resolved": "https://sinopia.nmlv.nml.com/process/-/process-0.11.10.tgz",
          "integrity": "sha1-czIwDoQBYb2j5podHZGn1LwW8YI=",
          "dev": true
        },
        "react-dom": {
          "version": "16.14.0",
          "resolved": "https://sinopia.nmlv.nml.com/react-dom/-/react-dom-16.14.0.tgz",
          "integrity": "sha512-1gCeQXDLoIqMgqD3IO2Ah9bnf0w9kzhwN5q4FGnHZ67hBm9yePzB5JJAIQCc8x3pFnNlwFq4RidZggNAAkzWWw==",
          "dev": true,
          "requires": {
            "loose-envify": "^1.1.0",
            "object-assign": "^4.1.1",
            "prop-types": "^15.6.2",
            "scheduler": "^0.19.1"
          }
        }
      }
    },
// ...
```

**Comment by ndelangen** [comment]
In storybook 7.0 beta we now have all relevant packages have peerDependencies on react.
We couldn't make them optional.. We'll revisit this in 8.0 or later.
