### ISSUE TITLE
6.1 Shortcuts hidden off page

### ISSUE THREAD

**Issue by piemasters** [storybookjs/storybook#13193]
**Describe the bug**
Upgraded from 6.0.28 to 6.1.1 and now the shortcuts button opens the popover above the button rather than below so it's off the page. 

**To Reproduce**
Just click the button. I am using theming via "@storybook/theming/create" but am not using any custom css.

**Expected behavior**
The shortcuts popover should be displayed below the button rather than above.

**Screenshots**
![image](https://user-images.githubusercontent.com/3764650/99831047-6e248100-2b56-11eb-9a2b-68d9d62ce0fa.png)

**Code snippets**
..

**System**
Environment Info:

  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
  Binaries:
    Node: 12.18.3 - /var/folders/2p/z_8gsnzs6z308mdk0l31y5p80000gn/T/fnm-shell-9008488/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.8 - /var/folders/2p/z_8gsnzs6z308mdk0l31y5p80000gn/T/fnm-shell-9008488/bin/npm
  Browsers:
    Chrome: 87.0.4280.67
    Firefox: 79.0
    Safari: 14.0
  npmPackages:
    @storybook/addon-a11y: 6.1.1 => 6.1.1 
    @storybook/addon-cssresources: 6.1.1 => 6.1.1 
    @storybook/addon-essentials: 6.1.1 => 6.1.1 
    @storybook/addon-jest: 6.1.1 => 6.1.1 
    @storybook/addon-links: 6.1.1 => 6.1.1 
    @storybook/addon-storyshots: 6.1.1 => 6.1.1 
    @storybook/addons: 6.1.1 => 6.1.1 
    @storybook/theming: 6.1.1 => 6.1.1 
    @storybook/vue: 6.1.1 => 6.1.1 

**Additional context**
..

**Comment by shilman** [comment]
Do you have a repro repo you can share?

**Comment by piemasters** [comment]
Not right now. If it's not happening for you I'll have a play early next week. I'll either create a new repo and share a link or report back with the issue/fix and close the ticket.

**Comment by piemasters** [comment]
Cleared local storage and that fixed it.
