### ISSUE TITLE
docs.source.type = 'code' possible regression on SB 6.1.1 (React + TS)

### ISSUE THREAD

**Issue by benjamin-schneider** [storybookjs/storybook#13190]
**Describe the bug**
when `docs.source.type` value is set to `code`, storybook says that code is not available. With `dynamic` | `auto` it is fine.

**To Reproduce**
![Peek 20-11-2020 11-34](https://user-images.githubusercontent.com/3585213/99790590-a4e1a380-2b24-11eb-9b6f-8022efae0ee3.gif)

**Expected behavior**
Same behaviour as described here : https://storybook.js.org/docs/react/writing-docs/doc-blocks (To visualize the source as code, you'll need to include the code option in the docs.source.type parameter)

**System**
Ubuntu / SB 6.1.1 / React 17 + TS 4.0.5

**Comment by shilman** [comment]
@benjamin-schneider what version are you upgrading from? Do you have a repro repo you can share?

**Comment by benjamin-schneider** [comment]
Thanks for your answer @shilman  Unfortunately, the repo is private, sorry for for the lack of details.
I was upgrading from 6.0.28 to 6.1.1.
I will do my best to produce a minimalist repo next week, maybe I should investigate first why `userCode` is always undefined in the `getSnippet` function (in addon-blocks). 
Seems that I am the only one who encouters this problem until now.

**Comment by shilman** [comment]
@benjamin-schneider yep it's the first time I'm seeing it reported

**Comment by benjamin-schneider** [comment]
I had a memory from a gist helper you wrote @shilman : https://gist.github.com/shilman/bc9cbedb2a7efb5ec6710337cbd20c0c#notes

If I set `sourceLoaderOptions: null,` in `'@storybook/addon-docs',` , the `docs.source.type = 'code' ` work again.

![Capture d’écran de 2020-11-25 09-00-11](https://user-images.githubusercontent.com/3585213/100199028-e8f5ef00-2efc-11eb-8fa3-c1aca5b172da.png)

Seems weird because the issue is from august 2019 but I wanted to give you some feedback.
Regards, Benjamin

**Comment by shilman** [comment]
@benjamin-schneider URGH it's `addon-docs` and `addon-storysource` stepping on each other.

Probably related: https://github.com/storybookjs/storybook/blob/next/addons/storysource/README.md#displaying-full-source 

Proposed fix: https://github.com/storybookjs/storybook/issues/12561

**Comment by mcookdev** [comment]
I am also having this issue when using addon-storysource along with setting docs > source > type: 'code' on a story. 

I followed the suggestions in the storysource readme, but it did not work.
