### ISSUE TITLE
Request for making the condition more flexible for: `Expected '@storybook/addon-docs' to be listed before '@storybook/addon-essentials'`

### ISSUE THREAD

**Issue by jon301** [storybookjs/storybook#13202]
Hey Storybook team :) Little request here:

**Is your feature request related to a problem? Please describe**
I'm trying to create a private package abstracting all storybook core dependencies (e.g. `@storybook/react`, `@storybook/addon-essentials`, `babel-loader`, etc.) so I would not have to install those manually in each of my projects.
This package would also return a minimal config with some defaults for the consumer. Something like that:
```
function getStorybookConfig(config) {
  return {
    ....
    addons: [
      require.resolve('@storybook/addon-essentials')
    ].concat(config.addons),
    ....
  };
}
module.exports = getStorybookConfig;
```

When starting storybook, essentials addons do not work, and I get the following warning in the console:
```
...
info => Adding stories defined in ".storybook/main.js"
WARN Expected '@storybook/addon-docs' to be listed before '@storybook/addon-controls' (or '@storybook/addon-essentials'). Check your main.js?
WARN
WARN https://github.com/storybookjs/storybook/issues/11442
info => Using custom postcss.config.js
...
```

After digging a bit, I've found the check in `@storybook/addon-controls` ensuring that Docs is placed before `@storybook/addon-essentials` : 
https://github.com/storybookjs/storybook/blob/6dd5e2e56991430004674e25c46c775a08d0d579/addons/controls/src/preset/ensureDocsBeforeControls.ts#L11

The problem is that the condition uses `startsWith('@storybook/addon-essentials')`.
And because my essentials addon is in a subpackage, I had to `require.resolve` it, giving the following path `'/Users/jon301/my-app/node_modules/@jon301/my-storybook-preset/node_modules/@storybook/addon-essentials/dist/index.js'`, which does not satisfy the `startsWith` condition.

**Describe the solution you'd like**
Be more flexible by replacing `name.startsWith(addon)` by `name.includes(addon)`.

Please let me know if you are OK with this and I'll create a PR 🙏
Thanks !

**Comment by shilman** [comment]
@jon301 Sounds good to me! PRs welcome! 🙏

**Comment by shilman** [comment]
Shiver me timbers!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.6 containing PR #13204 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```

Closing this issue. Please re-open if you think there's still more to do.
