### ISSUE TITLE
Core: Theme updates don't invalidate manager caching

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#13200]
6.1 includes manager caching, where the manager UI is only built on changes to the manager config. However, changing the theme doesn't invalidate the cache.

## Reproduction

Set up a fresh CRA install and add a theme to `.storybook/manager.js`:

```js
import { addons } from "@storybook/addons";
import { themes } from "@storybook/theming";

addons.setConfig({
  theme: themes.dark,
});
```

Run `yarn storybook` and cache the manager.

Then update the theme:

```js
addons.setConfig({
  theme: themes.light,
});
```

Observe that it is still using the original cached manager, rather than re-caching to reflect the change.

## Workaround

As a workaround you can run `yarn storybook --no-manager-cache` to manually invalidate.

**Comment by j-norman** [comment]
thank you for the workaround! i thought i was losing my mind.  "glad" to see that someone else ran into this.

**Comment by valentinbourqui** [comment]
To me it continue to not working even if I add --no-manager-cache my file manager.js is never loaded.

**Comment by j-norman** [comment]
@valentinbourqui im on 6.1.1 and this worked fine for me, once i used the --no-manager-cache flag when launching storybook (`yarn storybook --no-manager-cache`):

https://storybook.js.org/docs/react/configure/theming#create-a-theme-quickstart

I hope that helps you some -I'm no expert, I just feel your pain.

**Comment by utkarshabak** [comment]
I am using version 6.1.11

After adding `--no-manager-cache` with start command, it continues to say `info => Using cached manager` and the theme doesn't update.

Does anyone have a viable solution, I have tried everything, clearing storage, hard-refreshing, but the problem seems to be in storybook cache managemnt.

**Comment by kishorekumaru** [comment]
I am still having the same issue, adding --no-manager-cache not updating my theme updates

**Comment by utkarshabak** [comment]
> I am still having the same issue, adding --no-manager-cache not updating my theme updates, I want to update the Logo, is there any other way to replace it?

Delete the `.cache` folder from `node_modules`, run the storybook again, it should solve the problem.

**Comment by AndiBeno86** [comment]
Pada tanggal Jum, 8 Jan 2021 03:07, utkarshabak <notifications@github.com>
menulis:

**Comment by kishorekumaru** [comment]
> > I am still having the same issue, adding --no-manager-cache not updating my theme updates, I want to update the Logo, is there any other way to replace it?
> 
> Delete the `.cache` folder from `node_modules`, run the storybook again, it should solve the problem.

Yes I have Deleted node_modules reinstalled again, cleared .cache in node_modules folder, none my themes changes are reflecting, I am using 

` "@storybook/addon-actions": "^6.1.9",
    "@storybook/addon-backgrounds": "^6.1.10",
    "@storybook/addon-docs": "^6.1.9",
    "@storybook/addon-essentials": "^6.1.9",
    "@storybook/addon-links": "^6.1.9",
    "@storybook/addon-storysource": "^6.1.10",
    "@storybook/preset-create-react-app": "^3.1.5",
    "@storybook/react": "^6.1.9",`

**Comment by kishorekumaru** [comment]
Here is storybook configuration

.storybook/main.js 

```
// your app's webpack.config.js
const path = require('path');
module.exports = {
  webpackFinal: async (config) => {
    config.node  = { fs: 'empty' };
    return config;
  },
  "stories": [
    "../src/**/*.stories.mdx",
    "../src/**/*.stories.@(js|jsx|ts|tsx)"
  ],
  "addons": [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/preset-create-react-app",
    '@storybook/addon-backgrounds',
    'storybook-dark-mode/register',
    { name: '@storybook/addon-storysource',
      options: {
        loaderOptions: {
          injectStoryParameters: false,
        },
      }
    }
  ]
}
```
// .storybook/manager.js

```
import { addons } from '@storybook/addons';
import CustomTheme from './themeOverride';

addons.setConfig({
  theme: CustomTheme,
});
```


// .storybook/preview.js

```
import React from 'react';
import { themes, ThemeProvider } from '@storybook/theming';
import { Theme } from './../src/components/Theme';
import { useDarkMode } from 'storybook-dark-mode';
import CanvasBase from './../src/Stories/CanvasBase';
import addons from '@storybook/addons';

// get channel to listen to event emitter
const channel = addons.getChannel()
let storybookIsDark = false
channel.on('DARK_MODE', () => (storybookIsDark = true))

export const parameters = {
  actions: { argTypesRegex: "^on[A-Z].*" },
  docs: {
    theme: themes.dark,
  },
  layout: 'centered',
  darkMode: {
    // Set the initial theme
    current: 'light',
    // Override the default dark theme
    dark: { ...themes.dark, appBg: '#333' },
    // Override the default light theme
    light: { ...themes.normal, appBg: '#fff' }
  },
  backgrounds: {
    values: [
      {
        name: 'light',
        value: '#fff',
      },
      {
        name: 'dark',
        value: '#212121',
      },
    ],
  },
}



export const decorators = [
  (Story) => {
    return (
      <Theme type={useDarkMode() ? 'dark' : 'light'}>
        <CanvasBase type={useDarkMode()}>
          <Story />
        </CanvasBase>
      </Theme>
  )},
];
```

//.storybook/themeOverride.js

```
import { create } from '@storybook/theming/create';

export default create({
  base: 'dark',
  brandTitle: 'Tabkit Themes',
  brandUrl: 'https://tab.com.au',
  brandImage: 'https://placehold.it/350x150'
});
````

**Comment by utkarshabak** [comment]
@kishorekumaru It may not work for you but can you remove `./src/**/*.stories.mdx` from main.js and then run again.

**Comment by kishorekumaru** [comment]
thanks @utkarshabak for getting back on this, my stories are in mdx, however I deleted the. .cache and also removed  node_modules and re-installed the packages. I still facing the same issue

<img width="580" alt="Screen Shot 2021-01-13 at 3 53 12 pm" src="https://user-images.githubusercontent.com/5929834/104408170-927d6680-55b7-11eb-90ff-9cdf3666bde3.png">

**Comment by Vadorequest** [comment]
Using `--no-manager-cache` with `@storybook/react` v6.1.14 seem to work as expected.

```
$ STORYBOOK=true start-storybook -h localhost -p 6006 --no-manager-cache
info @storybook/react v6.1.14
info 
info => Loading presets
info => Loading presets
info => Loading custom babel config as JS
info => Loading custom babel config as JS
info => Loading 1 config file in "./.storybook"
info => Loading 9 other files in "./.storybook"
WARN unable to find package.json for flatted
info => Loading custom manager config
info => Adding stories defined in ".storybook/main.js"
info => Cleared cached manager config

```

See commit https://github.com/UnlyEd/next-right-now/commit/74e698ef4492ae4f4ea106f9a0c826978a1ba2a8

**Comment by shilman** [comment]
We want to address this in 6.3. If you want to contribute to Storybook, we'll prioritize PR review for any fixes here. And if you'd like any help getting started, please jump into the #support channel on our Discord: https://discord.gg/storybook

**Comment by shilman** [comment]
ZOMG!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.3.0-alpha.44 containing PR #14993 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
@ghengeveld This doesn't seem to be working

```
yarn create react-app cra-test
cd cra-test
npx sb@next init
yarn storybook
```

Results in:

```
...
info => Ignoring cached manager due to change in manager config
```

After the first run, caching seems to be working great with the new changes!!

**Comment by shilman** [comment]
Gadzooks!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.3.0-beta.1 containing PR #15050 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
@ghengeveld still not quite there. same repro as before, diff behavior:

```
yarn create react-app cra-test
cd cra-test
npx sb@next init
yarn storybook
```

Results in:

```
info => Using prebuilt manager
...
│   12 s for manager and 13 s for preview         │
```

**Comment by shilman** [comment]
Per discussion with @ghengeveld this is a separate issue. Closing this and opened #15115

**Comment by mxm-web-develop** [comment]
> 'storybook-dark-mode/register',

.... you can't use dark-mode and customized theme together, i hope that help you.
