### ISSUE TITLE
MobX 5 Unsupported IE11

### ISSUE THREAD

**Issue by shealavington** [storybookjs/storybook#13218]
**Describe the bug**
Appears that in the latest upgrade, **MOBX5 is not supported by IE11** which is really unfortunate.

Error: [mobx] MobX 5+ requires Proxy and Symbol objects. If your environment doesn't support Symbol or Proxy objects, please downgrade to MobX 4. For React Native Android, consider upgrading JSCore.

**To Reproduce**
Upgrade to the latest version,
Attempt to load SB in IE
Receive error

**Expected behavior**
Ideally, IE should work.

**System**
Environment Info:
  System:
    OS: Windows 10 10.0.19041
    CPU: (4) x64 Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz
  Binaries:
    Node: 10.23.0 [OMITTED_FOR_SECURITY]
    npm: 6.14.6 [OMITTED_FOR_SECURITY]
  Browsers:
    Chrome: [OMITTED_FOR_SECURITY]
    Edge: Spartan [OMITTED_FOR_SECURITY]
  npmPackages:
    @storybook/addon-a11y: ^6.1.2 => 6.1.2 
    @storybook/addon-actions: ^6.1.2 => 6.1.2 
    @storybook/addon-console: ^1.2.2 => 1.2.2 
    @storybook/addon-essentials: ^6.1.2 => 6.1.2         
    @storybook/addon-links: ^6.1.2 => 6.1.2
    @storybook/addon-storysource: ^6.1.2 => 6.1.2
    @storybook/addons: ^6.1.2 => 6.1.2
    @storybook/theming: ^6.1.2 => 6.1.2
    @storybook/vue: ^6.1.2 => 6.1.2

**Additional context**
I'm aware that still using IE11 is staying behind the times, however, unfortunately, it's a requirement for me for the time being.

**Comment by shilman** [comment]
Storybook doesn't use MobX, so I'm not sure what's required on our side. WDYT?

**Comment by shealavington** [comment]
Interesting, I tried to upgrade storybook using the command that popped up on the storybook application.

I ran the command (`npx sb update` or something similar), then I begun getting MobX errors in IE... Have you tested the latest update on IE11 yourself? Could confirm that it still works? Perhaps I've missed something (Which I don't _think_ that I have)...

Could it be a dependency?

**Comment by shilman** [comment]
@shealavington we have CI checks running in IE and it's working AFAIK. our CI has been down for a few days, so there's a slim possibility that it broke during that time. There are some other IE-related issues that came up recently, but nothing related to MobX.

**Comment by shealavington** [comment]
Hmm interesting, I've tried again and I'm still not able to get this working on IE, if I get some time, I'll try to debug and figure it out, if you can confirm that IE is working, then the ticket can be closed...

_Perhaps I've changed something? The setup I'm using is somewhat complex, but only seems impacted on update..._

**Comment by tooppaaa** [comment]
Don't worry @shealavington, it's a pain lots of us have to deal with ;)

There's currently an issue https://github.com/storybookjs/storybook/pull/13302 which should be resolved soon but this doesn't break build or manager build in IE. 

If you believe there's anything that can be done on storybook side, please reopen :)

**Comment by Baffour** [comment]
@shealavington did you ever solve this issue? I'm getting the same error after upgrading to 6.1 using `npx sb upgrade`

**Comment by shealavington** [comment]
Nope, I'm still currently using an older version

**Comment by Baffour** [comment]
@shealavington Just tried the prelease version (`npx sb upgrade --prerelease`) and it actually works for me now!

There are a couple of cosmetic UI issues with native IE dropdowns/checkboxes showing on controls, and a couple of console errors about syntax highlighting but I can load stories and play with controls. Worth trying that out, something in 6.2 must have fixed the MobX issue

**Comment by shealavington** [comment]
That's awesome, unfortunately for me I can't love to a prerelease, however I'll keep the next version in mind, thanks for keeping me updated! 🤝

**Comment by shilman** [comment]
@tooppaaa any idea why this is working in 6.2 but not in 6.1?

**Comment by shealavington** [comment]
> @tooppaaa any idea why this is working in 6.2 but not in 6.1?

I'll take this as a "We have no idea"? 😂
