### ISSUE TITLE
`@storybook/addon-jest` does not show results despite using file extension and `result` json 

### ISSUE THREAD

**Issue by RyanPayso13** [storybookjs/storybook#13213]
**Describe the bug**
I have included the `@storybook/addon-jest` with storybook version 6 but it is not showing the results ith the story with the following code snippets.

**Code snippets**
```
import React from 'react';
import { DocumentUploadStatus } from '@/models/document';
import { Meta, Story } from '@storybook/react/types-6-0';
import { withTests } from '@storybook/addon-jest';
import results from '@/test/reports/jest-test-results.json';
import UploadState, { UploadStateProps } from './UploadState';

export default {
  title: 'UploadState',
  component: UploadState,
  decorators: [withTests({ results, filesExt: '.spec.tsx' })],
} as Meta;

const Template: Story<UploadStateProps> = args => <UploadState {...args} />;

export const InProgress = Template.bind({});
InProgress.args = {
  progress: 50,
  filename: 'file.txt',
  status: DocumentUploadStatus.IN_PROGRESS,
};

export const WithTests = (): string =>
  'This story shows test results for <UploadState />';
WithTests.story = {
  parameters: {
    jest: 'UploadState',
  },
};

```

```
{
   "assertionResults":[
      {
         "ancestorTitles":[
            "<UploadState />"
         ],
         "failureMessages":[
            
         ],
         "fullName":"<UploadState /> should render default state",
         "location":null,
         "status":"passed",
         "title":"should render default state"
      },
      {
         "ancestorTitles":[
            "<UploadState />"
         ],
         "failureMessages":[
            
         ]
      ],
      "endTime":1605914342915,
      "message":"",
      "name":"/Users/usr/workspace/project/src/components/Document/UploadList/UploadList.spec.tsx",
      "startTime":1605914342081,
      "status":"passed",
      "summary":""
   }
```
**System**
Please paste the results of `npx sb@next info` here.

**Additional context**

**Comment by shilman** [comment]
Do you have a repro repo you can share?

**Comment by GuilleDF** [comment]
From what I can see, it also doesn't work in the live storybook page linked in `@storybook/addon-jest`'s Readme:
http://storybooks-official.netlify.com/?selectedKind=Addons%7Cjest&selectedStory=withTests&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Ftests%2Fpanel

**Comment by mosherc** [comment]
Sorry to hijack an inactive issue, but I have a similar one, although it was fixed when I added 
```js
FlashStory.parameters = {
  jest: 'Flash'
};
```
Is this required? Is there a way to set this up for every file from preview.js or something, like in the parameters object there? I have this
```js
export const decorators = [
  withTests({
    results,
    filesExt: '.test.tsx'
  })
];
```
but it won't work without the parameters code above.

**Comment by shilman** [comment]
@mosherc i think it needs the `jest` parameter to know what result to include. i'm sure that could be made smarter if it's something you'd be interested in contributing

**Comment by zanona** [comment]
This seems to work on `v6.2.0-rc.10` through `@storybook/addon-jest@next`. I am not sure about the production disclaimer though :wink:  

https://github.com/storybookjs/storybook/blame/next/addons/jest/README.md#L131-L132
