### ISSUE TITLE
Using controls resets story's state

### ISSUE THREAD

**Issue by ogy6** [storybookjs/storybook#13214]
**Describe the bug**
When writing a story with controls and the `useState` hook, the state resets on controls change. (It seems the component isn't re-rendered but instead is re-instantiated from scratch)

**To Reproduce**

1. Running any story that has `useState` and uses the controls from the essential addon.

for example
```
export const Primary: Story<SelectProps> = (args) => {
  const [selected, setSelected] = useState<Displayable>();

  return (
    <Select disabled={args.disabled} options={options} selectedOption={selected} onSelectionChange={setSelected} />
  );
};
```
2. Changing the state (selecting an option in my case).
3. Using a control to change a value.
4. See that the state resets.

**Expected behavior**
The story should keep the state of the component.
problem.

**Code snippets**
See above.

**System**
```
Environment Info:

  System:
    OS: macOS 11.0.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
  Binaries:
    Node: 14.15.1 - /usr/local/bin/node
    npm: 6.14.9 - /usr/local/bin/npm
  Browsers:
    Chrome: 87.0.4280.67
    Safari: 14.0.1
  npmPackages:
    @storybook/addon-actions: ^6.1.2 => 6.1.2 
    @storybook/addon-essentials: ^6.1.2 => 6.1.2 
    @storybook/addon-links: ^6.1.2 => 6.1.2 
    @storybook/node-logger: ^6.1.2 => 6.1.2 
    @storybook/preset-create-react-app: ^3.1.5 => 3.1.5 
    @storybook/react: ^6.1.2 => 6.1.2 
```
**Additional context**

**Workaround**
Possible workaround is to initiate the state from the args, and change the args on selection change as well as the state itself.
Code:
```
export const Primary: Story<SelectProps> = (args) => {
  const [selected, setSelected] = useState(args.selectedOption);

  return (
    <Select
      disabled={args.disabled}
      options={options}
      selectedOption={selected}
      onSelectionChange={(option) => {
        args.selectedOption = option;
        setSelected(option);
      }}
    />
  );
};
```

**Comment by audiolion** [comment]
I came across this today as well, very similar UI component, a select with a useState for selected, with the onSelectionChange handler coded in a similar same way as OP's example `onSelectChange={(option) => args.onSelectionChange(option) && setSelected(option)}`

**Comment by shilman** [comment]
Similar to #13913 @tmeasday and probably a duplicate to some existing issue which I'm unable to find.

**Comment by tmeasday** [comment]
Here's the issue: https://github.com/storybookjs/storybook/issues/12255 -- I think it's a dupe.

**Comment by shilman** [comment]
closing as dupe to #12255
