### ISSUE TITLE
Vue warnings with Storyshots and Jest

### ISSUE THREAD

**Issue by Nakroma** [storybookjs/storybook#13223]
I've been trying to get Storyshots working with Vue.js and Jest. Running the tests results in a lot of Vue warnings and undefined behaviour. Which is weird, because these work when I start them normally with `start-storybook`.

For example, when I use the default `storybook-example` components I get errors like these:
```
 console.error
      [Vue warn]: Property or method "onClick" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

      found in

      ---> <Anonymous>
             <Root>


 console.error
      [Vue warn]: Invalid handler for event "onClick": got undefined

      found in

      ---> <MyButton>
             <Anonymous>
               <Root>
```

Heres my `jest.config.js`:
```js
module.exports = {
  displayName: 'my-project',
  preset: '../../jest.config.js',
  transform: {
    '.*\\.(vue)$': 'vue-jest',
    '^.+\\.ts$': 'ts-jest',
    '^.+\\.jsx?$': 'ts-jest',
    '^.+\\.mdx?$': '@storybook/addon-docs/jest-transform-mdx'
  },
  moduleFileExtensions: ['ts', 'js', 'vue', 'json'],
  coverageDirectory: '../../coverage/apps/my-project',
  collectCoverageFrom: [
    '<rootDir>/components/**/*.vue',
    '<rootDir>/pages/**/*.vue',
  ],
  moduleNameMapper: {
    '^vue$': 'vue/dist/vue.common.js',
  },
  globals: {
    'ts-jest': { babelConfig: '<rootDir>/babel.config.js' },
    'vue-jest': { tsConfig: '<rootDir>/tsconfig.spec.json' },
  },
};
```
The vue-jest config:
```json
// tsconfig.json
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "esModuleInterop": true,
    "allowJs": true,
    "noEmit": true,
    "types": ["node", "@nuxt/types"]
  },
  "include": ["**/*.ts", "**/*.js", "**/*.vue"]
}
// tsconfig.spec.json
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "../../dist/out-tsc",
    "module": "commonjs",
    "types": ["jest", "node"],
    "esModuleInterop": true,
    "allowJs": true,
    "noEmit": true
  },
  "include": ["**/*.spec.ts", "**/*.d.ts", "**/*.spec.js"]
}
```
The storyshot entrypoint is just the default `storybook.test.js`:
```js
import initStoryshots from '@storybook/addon-storyshots';
initStoryshots({
  configPath: 'apps/my-project/.storybook',
});
```

Anybody has an idea what's going wrong here? Reproduction repository: https://github.com/Nakroma/storyshots-reproduction

**Comment by shilman** [comment]
How are you providing the handlers e.g. `onClick`? E.g. is it automatically filled in by `addon-actions`? Or manually hard-coded? Do you have a repro rep you can share?

**Comment by Nakroma** [comment]
These are just the normal storybook examples, so just a method which logs a string:
```vue
<template>
  <button type="button" :class="classes" @click="onClick" :style="style">{{ label }}</button>
</template>

<script>
export default {
  name: 'my-button',

  props: {
    label: {
      type: String,
      required: true,
    },
    primary: {
      type: Boolean,
      default: false,
    },
    size: {
      type: String,
      default: 'medium',
      validator: function (value) {
        return ['small', 'medium', 'large'].indexOf(value) !== -1;
      },
    },
    backgroundColor: {
      type: String,
    },
  },

  computed: {
    classes() {
      return {
        'storybook-button': true,
        'storybook-button--primary': this.primary,
        'storybook-button--secondary': !this.primary,
        [`storybook-button--${this.size}`]: true,
      };
    },
    style() {
      return {
        backgroundColor: this.backgroundColor,
      };
    },
  },

  methods: {
    onClick() {
      this.$emit('onClick');
    },
  },
};
</script>

<style>
.storybook-button {
  font-family: 'Nunito Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif;
  font-weight: 700;
  border: 0;
  border-radius: 3em;
  cursor: pointer;
  display: inline-block;
  line-height: 1;
}
.storybook-button--primary {
  color: white;
  background-color: #1ea7fd;
}
.storybook-button--secondary {
  color: #333;
  background-color: transparent;
  box-shadow: rgba(0, 0, 0, 0.15) 0px 0px 0px 1px inset;
}
.storybook-button--small {
  font-size: 12px;
  padding: 10px 16px;
}
.storybook-button--medium {
  font-size: 14px;
  padding: 11px 20px;
}
.storybook-button--large {
  font-size: 16px;
  padding: 12px 24px;
}
</style>
```
Theres no repro repo that I can share currently as it's a big project. If it would help I can try to set one up though.

**Comment by Nakroma** [comment]
Hello, i've managed to create a reproduction repository: https://github.com/Nakroma/storyshots-reproduction  
Just clone, run `yarn install` and then `nx test my-app` (the first .mdx console.warn can actually be fixed, this issue is about the tons of Vue [warn] console.errors)

**Comment by JDIZM** [comment]
I'm having the same issues in my repo: https://github.com/JDIZM/vue-storybook-library 

As far as I know they worked before, now they are broken. So I've been trying to figure out where the problem was and I've come unstuck. I've tried creating a new project with storybook and here's the steps to reproduce

* install vue project with vue cli include jest, node-sass
* install storybook `npx sb init`
* install preset-css `yarn add -D storybook/preset-scss sass-loader`

preset-css causes issues when `css-loader style-loader` are added as suggested.

* add to .storybook/main.js addons `"@storybook/preset-scss"`
* edit .storybook/preview.js and add `import '../src/theme/main.scss'`
* add @storybook/addon-storyshots
* create storybook.spec.js
```js
// tests/unit/storybook.spec.js
import initStoryshots from '@storybook/addon-storyshots';

initStoryshots();
```
* run a test `npm run test:unit`

The snapshots complete and pass first time but there's a wall of errors such as `[Vue warn]: Invalid handler for event "onLogout": got undefined` 

These are all coming from the default components and I am having similar issues with my own storybook components.

**Comment by cherylcarpenter** [comment]
@JDIZM me too!!
  [Vue warn]: Property or method "onClick" is not defined on the instance but referenced during render.
  
it was fine last time I worked on this!

**Comment by IntusFacultas** [comment]
I'm currently experiencing the same issue. onClick is defined by storybook/actions-addon, and the onClick handler provided by actions addon does work when looking at the story, but Jest and Vue consider it undefined at jest run time.

**Comment by armurei** [comment]
I'm dealing with this issue as well. As @Nakroma said, it is reproducible with the boilerplate stories. From my experience, it seems to be any story that uses the [action argType annotation](https://storybook.js.org/docs/vue/essentials/actions#action-argtype-annotation). 

Obviously not a great solution, but it's possible to suppress these errors by mocking out `console.error` for the storyshot test, for example:
```javascript
// Storyshots.test.js
import initStoryshots from '@storybook/addon-storyshots';

jest.spyOn(console, 'error').mockImplementation(() => {});

initStoryshots();
```
Any updates on this issue would be great.

**Comment by JDIZM** [comment]
> I'm dealing with this issue as well. As @Nakroma said, it is reproducible with the boilerplate stories. From my experience, it seems to be any story that uses the [action argType annotation](https://storybook.js.org/docs/vue/essentials/actions#action-argtype-annotation).
> 
> Obviously not a great solution, but it's possible to suppress these errors by mocking out `console.error` for the storyshot test, for example:
> 
> ```js
> // Storyshots.test.js
> import initStoryshots from '@storybook/addon-storyshots';
> 
> jest.spyOn(console, 'error').mockImplementation(() => {});
> 
> initStoryshots();
> ```
> 
> Any updates on this issue would be great.

Thanks this get's rid of the warnings. I have made a base repo with this fix in place and the tests seem to work fine. https://github.com/JDIZM/vue-sb-jest

**Comment by nemoDreamer** [comment]
Is there any movement on this?
As @armurei pointed out, it has to do with the `action` short-hand in `argTypes` not making it down as a handler to the template. Works fine in Storybook (logs actions in the Actions panel), but breaks in Storyshots.

I've resorted to this, but would ❤️ to avoid making each dev add this boilerplate to each story that needs handlers:
```js
export default {
    title: "Components/SyncButton",
    component: SyncButton,
    argTypes: {
        callback: { action: "clicked!" },
    },
    args:
        // TODO: find a way to avoid this. Storyshots doesn't seem to merge in
        // the `argTypes`?
        process.env.NODE_ENV === "test"
            ? {
                  callback: () => {},
              }
            : undefined,
};
```

**Comment by ndelangen** [comment]
The future of storyshots is the test-runner:
https://storybook.js.org/docs/react/writing-tests/test-runner#page-top

And use the play function for expectations:
https://storybook.js.org/docs/react/writing-stories/play-function#page-top

We will not be making any improvement / changes to storyshots.

**Comment by nemoDreamer** [comment]
Aha, interesting! Thanks for the heads-up, @ndelangen!
