### ISSUE TITLE
Global decorators: missing typescript example

### ISSUE THREAD

**Issue by romanyanke** [storybookjs/storybook#13222]
**Describe the bug**

Wrong code snippet in the docs

**To Reproduce**

1. Go to  https://storybook.js.org/docs/react/writing-stories/decorators#global-decorators
2. Click on Global decorators: TS/JS tabs
3. Tab content is the same

**Additional context**
Wrong file https://github.com/storybookjs/storybook/blob/master/docs/snippets/react/storybook-preview-global-decorator.ts.mdx

**Comment by jonniebigodes** [comment]
@romanyanke thanks for catching this. The snippet was actually introduced incorrectly. Technically when it comes to React Storybook decorators work the same way either with JS or TS. 

Stay safe

**Comment by jonniebigodes** [comment]
@romanyanke going to close this issue if you don't mind. A recent pull request was merged that addressed this.

Feel free to re-open regarding any follow up. 

Stay safe

**Comment by landsman** [comment]
Now I'm looking for the same info. Basically where I can import types of Story etc.
