### ISSUE TITLE
Invalid hook error while using html and addon-docs

### ISSUE THREAD

**Issue by NeOMakinG** [storybookjs/storybook#13221]
**Describe the bug**
This is the exact same bug as #12408 but when using `@storybook/html` and `@storybook/addon-docs`

It create a `Invalid hook` error.

**To Reproduce**

You are able to see the complete project here : https://github.com/PrestaShop/prestashop-ui-kit/pull/108

1. Use storybook/html and addon-docs at the same time
2. Try to use a useEffect hook in order to execute JS on storyload like this :
![image](https://user-images.githubusercontent.com/14963751/99949649-aa84f680-2d7b-11eb-8b1a-d5dceda53f36.png)
![image](https://user-images.githubusercontent.com/14963751/99949966-2a12c580-2d7c-11eb-9ff8-f254ab2dc981.png)

**Expected behavior**
Both canvas and docs tab working fine using hooks

**System**
![image](https://user-images.githubusercontent.com/14963751/99950139-621a0880-2d7c-11eb-8e18-744312949cd3.png)

**Comment by shilman** [comment]
I don't think this is the same problem as #12408. When I install your project, there is only one copy of React that's installed AFAICT:

```
MMBP15:prestashop-ui-kit shilman$ npm list react
prestakit@1.1.0 /Users/shilman/projects/testing/prestashop-ui-kit
└─┬ @storybook/html@6.1.1
  └── react@16.13.1
```

I think the problem here is one we've seen before, which is that there is no react element surrounding the hooks, and that also results in this error.

I tried the following workaround:

```jsx
export const Popovers = () => {
  useEffect(() => {
    window.prestaShopUiKit.init();
  });
  return popoversContent;
};

<Canvas>
  <Story
    name="Popovers"
    parameters={{ docs: { source: { code: popoversContent } } }}
  >
    <Popovers />
  </Story>
</Canvas>
```

This forces a React.createElement. However, when I do that I get this error:

```
Did you forget to return the HTML snippet from the story?
Use "() => <your snippet or node>" or when defining the story.
```

I'm at a bit of a loss. @tmeasday any ideas?

**Comment by tmeasday** [comment]
Did you try 

```jsx
<Story
    name="Popovers"
    parameters={{ docs: { source: { code: popoversContent } } }}
  >
    {() => <Popovers />}
  </Story>
```

**Comment by NeOMakinG** [comment]
> Did you try
> 
> ```js-jsx
> <Story
>     name="Popovers"
>     parameters={{ docs: { source: { code: popoversContent } } }}
>   >
>     {() => <Popovers />}
>   </Story>
> ```

Just tried it, same error as @shilman 

```
Did you forget to return the HTML snippet from the story?
Use "() => <your snippet or node>" or when defining the story.
```

**Comment by tmeasday** [comment]
Oh, wait this is `@storybook/html`. I'm confused about why we are using react hooks inside the story..

**Comment by NeOMakinG** [comment]
> Oh, wait this is `@storybook/html`. I'm confused about why we are using react hooks inside the story..

Do you've another way of executing JS after story loading on `@storybook/html` ? I asked on another issue if it was "the good way", I don't mind using React on these stories, but maybe it can't work like this

**Comment by shilman** [comment]
@NeOMakinG maybe this?  https://github.com/storybookjs/storybook/pull/12089

**Comment by tmeasday** [comment]
We do have storybook hooks!

**Comment by NeOMakinG** [comment]
> @NeOMakinG maybe this? #12089

works like a charm on story page, but not inside a Canvas of docs page!

**Comment by shilman** [comment]
Ugh. Maybe try storybook hooks then?

```
import { useEffect } from '@storybook/client-api';
```

**Comment by NeOMakinG** [comment]
It works perfectly with storybook hooks 🎉 

Thanks a lot!

Is it supposed to work with React hooks inside MDX ? Otherwise we can close the issue!
