### ISSUE TITLE
MDX with args shows incorrect code source in docs tab

### ISSUE THREAD

**Issue by DigTheDoug** [storybookjs/storybook#13228]
**Describe the bug**
When defining a story using MDX with args (according to the docs [here](https://medium.com/storybookjs/introducing-storybook-args-2dadcdb777cc) and [here](https://storybook.js.org/docs/react/writing-docs/mdx)), the "Show code" button within the docs does not show the original code, but a parent storybook element.

**To Reproduce**
1. Create an MDX story with args.
2. On the docs tab, click on the "Show code" button.
3. See the source referring to `MDXCreateElement`

**Expected behavior**
The actual source is used, same as if it were a story created without using args.

**Screenshots**
Top story in the image is with MDX using args, bottom is standard without args:
![Screen Shot 2020-11-23 at 11 54 33 AM](https://user-images.githubusercontent.com/1428256/99991211-c5a73480-2d82-11eb-8678-0f4da272e1c5.png)

**Code snippets**
MDSX with args:
```js
export const ButtonTemplate = (args) => <Button  {...args} >Click Me</Button>;
<Canvas>
  <Story name="TestWithArgs" args={{size: 'small'}}>
    {ButtonTemplate.bind()}
  </Story>
</Canvas>
```
MDX without args:
```js
<Canvas>
  <Story name="Test">
    <Button size="small">Click Me</Button>
  </Story>
</Canvas>
```

**System**
```
  System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
  Binaries:
    Node: 12.18.4 - ~/.nvm/versions/node/v12.18.4/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.4/bin/npm
  Browsers:
    Chrome: 87.0.4280.67
    Edge: 87.0.664.41
    Firefox: 80.0.1
    Safari: 14.0.1
```

**Additional context**
Similar to previously fixed issue #8444

The "Show code" is useful and I would love to be able to use it in conjunction with the new Controls features. Alternatively, what would be even more useful would be being able to copy the code used to generate the current component from the Controls menu. For example, a user could use Controls to control the component as they wish, and then hit a 'copy code' button where the original component code would be displayed or copied to the clipboard.

**Comment by shilman** [comment]
Closing as dupe to #11542
