### ISSUE TITLE
Automatically prefix titles for all stories in a directory

### ISSUE THREAD

**Issue by brybrophy** [storybookjs/storybook#13229]
**Is your feature request related to a problem? Please describe**
In our monorepo, we find it hard to enforce naming conventions for story titles across our many teams.

**Describe the solution you'd like**
We would like to be able to automatically prefix story titles based on a glob pattern. This would allow us to give stories in each of our monorepo packages distinct names, so that our sidebar is organized by package.

**Describe alternatives you've considered**
Currently we are managing naming manually. This is not especially painful, but it can be a hassle working between many teams. We have considered creating a custom lint rule to enforce naming conventions. We have also considered detecting the directory and generating the titles, but we would like an easier API for this.

**Are you able to assist to bring the feature to reality?**
Possibly.

**Comment by ghengeveld** [comment]
You can generate the title based on the file path, if that helps: https://storybook.js.org/docs/react/configure/sidebar-and-urls#generating-titles-based-on-__dirname

What else did you have in mind, can you provide an example?

**Comment by alanhg** [comment]
Any method to append suffix for all stories?

maybe addon?

**Comment by shilman** [comment]
This is now implemented as part of CSF3's auto-title functionality

It needs proper documentation #17596, but you can see examples in the announcement post here https://storybook.js.org/blog/component-story-format-3-0/

It works out of the box in 6.4 and above. Closing this for now!

**Comment by joshuajaco** [comment]
Is there a way to disable this? We would like all our stories to be top level, independent of the file structure of the code.

**Comment by shilman** [comment]
@joshuajaco you can try 6.5, where the [behavior was changed to collapse redundant filenames](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#csf3-auto-title-improvements):

```
npx sb upgrade --prerelease
```

You can also continue to specify the title by hand to customize it to the exact nesting you desire:

```js
export default {
  title: 'Whatever/you/want'
}
```

**Comment by alanhg** [comment]
> Any method to append suffix for all stories?
> 
> not prefix，maybe addon?

I made webpack loader to auto title.


https://github.com/alanhg/storybook-webpack-auto-title-loader


### forexample
```js
const path = require('path');
module.exports = {
    webpackFinal: async (config, {configType}) => {
    config.module.rules.push({
      test: /\.stories\.(jsx?$|tsx?$)/, use: [{
        loader: path.resolve(__dirname, './auto-title.loader.js'), options: {
          appendTitle: ({title, componentName}) => `${title}-${componentName}`
        }
      }], include: path.resolve(__dirname, '../lib'),
    });
    return config;
}
  },
};
```

**Comment by gynekolog** [comment]
https://storybook.js.org/docs/configure/user-interface/sidebar-and-urls#auto-title-prefixes
