### ISSUE TITLE
Replace inquirer with prompts

### ISSUE THREAD

**Issue by thebuilder** [storybookjs/storybook#13226]
To help reduce the size of the Storybook project, removing Inquirer seems to be one step in the right direction. It was removed from `create-react-app` in version 4.0.1, which has drastically reduce the overall install size.

See:
* https://github.com/facebook/create-react-app/pull/10083
* https://twitter.com/Baconbrix/status/1330852677325119493

Implemented in #13225 

There are still dependencies in the project that rely on the package, but removing it from Storybook itself paves the way for others.

See `yarn why inquirer` for other reasons it exists.

**Comment by shilman** [comment]
Great Caesar's ghost!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.0-alpha.3 containing PR #13225 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
ZOMG!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.0-alpha.14 containing PR #13520 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```
