### ISSUE TITLE
Make it easier for us developer to make common configurations

### ISSUE THREAD

**Issue by PaoloDiBello** [storybookjs/storybook#13233]
**Is your feature request related to a problem? Please describe**
A clear and concise description of what the problem is. 

Almost in any project you will need to use svgs eventually which will cause problems with the current default storybook settings, which is not an issue after all as you can configure it to support them if you want. 

The problem is finding a way that works with your current version of storybook which happens to be very confusing and very frustrating, especially when nothing seems to work. I understand that it might be just a leaky abstraction but I really wish this was added to the documentation and updated regularly to avoid the spread of bad practices or just custom configurations that won't work for anyone. 

**Describe the solution you'd like**

I wish we could have instructions on a optimal way to configure it, rather than being forced to follow posts scattered all over the internet and that might not work with your current version or your configurations.  

**Are you able to assist to bring the feature to reality?**
no

**Comment by shilman** [comment]
Hopefully useful: https://github.com/storybookjs/presets/issues/19#issuecomment-612141466
