### ISSUE TITLE
ArgsTable props doesn't respect sorting order for props with control: false

### ISSUE THREAD

**Issue by patricklafrance** [storybookjs/storybook#13237]
**Describe the bug**
In ArgsTable, all props having `control: false` are rendered first.

For:

```js
<Meta
    title="Buttons/ToggleIconButton"
    id="toggle-icon-button"
    component={InnerToggleIconButton}
    argTypes={{
        defaultChecked: {
            control: false
        },
        autoFocusDelay: {
            control: false
        }
    }}
/>
```

The following is rendered:

![image](https://user-images.githubusercontent.com/794579/100042603-cae39e00-2dd9-11eb-9cac-2811eaeac292.png)

**To Reproduce**

**Expected behavior**
Sorting order is not affected by props that doesn,t render control.

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
Please paste the results of `npx sb@next info` here.

**Additional context**

**Comment by shilman** [comment]
w00t!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.0-beta.15 containing PR #13125 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
