### ISSUE TITLE
Update version popup/ballon is not "closable"

### ISSUE THREAD

**Issue by PlayMa256** [storybookjs/storybook#13249]
**Describe the bug**
Popup/overlay that shows storybook has a new version does not have a close button/icon. The only way to close it/make it disappear is to click on it and go to another page.

**Expected behavior**
Allow users to close the upgrade/update balloon without leaving the current page

I'm happy to add it if we all get into a consensus if it is something that the team wants to change! I'm looking more from a UX/DX POV rather than someone that is annoyed by it!

**Comment by shilman** [comment]
That's fixed in 6.1. Closing.

**Comment by shilman** [comment]
https://github.com/storybookjs/storybook/pull/12320
