### ISSUE TITLE
Storybook 6.x crashes with Gatsby 2.27.1

### ISSUE THREAD

**Issue by sklawren** [storybookjs/storybook#13241]
**Describe the bug**
Storybook 6.x is crashing with Gatsby 2.27.1. It works fine with Gatsby 2.26.1.

**To Reproduce**
I've posted this issue on the Gatsby Github because I'm not sure whether the error is Gatsby or Storybook. It might require some collaboration between the teams.

https://github.com/gatsbyjs/gatsby/issues/28253

**Expected behavior**
Check the above ticket.

**System**
```
  System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
  Binaries:
    Node: 12.18.4 - ~/.nvm/versions/node/v12.18.4/bin/node
    npm: 6.14.8 - ~/.nvm/versions/node/v12.18.4/bin/npm
  Browsers:
    Chrome: 87.0.4280.67
    Firefox: 82.0.2
    Safari: 14.0
  npmPackages:
    @storybook/addon-actions: ^6.1.4 => 6.1.4
    @storybook/addon-docs: ^6.1.4 => 6.1.4
    @storybook/addon-essentials: ^6.1.4 => 6.1.4
    @storybook/addon-links: ^6.1.4 => 6.1.4
    @storybook/addons: ^6.1.4 => 6.1.4
    @storybook/react: ^6.1.4 => 6.1.4
```

**Comment by ghengeveld** [comment]
Could you try with the last Storybook 5.x? Would be helpful to know if this is a mutual incompatibility between Gatsby 2.27.1 and Storybook 6.x, specifically.

**Comment by sklawren** [comment]
I used `npx sb init` so I'm not sure what would be required to install SB 5.x, but on the other thread, I uploaded a minimal reproduction project zip file, so you can easily try it out for yourself.

**Comment by sklawren** [comment]
As a quick aside, Gatsby has a bunch of modifications required for Storybook to work with it. 

They're outlined here: https://www.gatsbyjs.com/docs/visual-testing-with-storybook/#reach-skip-nav

- Running `npm install -D babel-preset-react-app`
- adding a complex-looking webpackFinal to main.js
- adding some global variables in preview.js

Do you think `npx sb init` could detect a Gatsby project and include these required modifications automatically or would that be too much to maintain?

**Comment by shilman** [comment]
@sklawren we maintain a preset for create react app that auto-configures storybook for CRA. next.js is working on something similar for next. we'd love to collaborate with the gatsby team on a preset for gatsby

**Comment by shilman** [comment]
sounds like this has been resolved. closing.
