### ISSUE TITLE
Addon-controls: Support undefined option for optional values

### ISSUE THREAD

**Issue by lifeiscontent** [storybookjs/storybook#13259]
**Describe the bug**

should have an option to set an arg to undefined if its optional

**To Reproduce**

1. Create a UI Component + Story
2.Add an optional prop
3. See that there is no option to set the arg to undefined in storybook controls / docs

**Expected behavior**
I'd expect that if an arg is optional, it should have `undefined` as a value in args.

**Screenshots**
![Screen Shot 2020-11-24 at 4 41 54 PM](https://user-images.githubusercontent.com/180963/100167538-25c9d380-2e74-11eb-9edb-63435474074d.png)

![Screen Shot 2020-11-24 at 4 43 19 PM](https://user-images.githubusercontent.com/180963/100167557-2ebaa500-2e74-11eb-8e2a-27c6fed5dbee.png)

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
Please paste the results of `npx sb@next info` here.

**Additional context**
Related bug that was fixed previously: https://github.com/storybookjs/storybook/issues/4487

**Comment by tmeasday** [comment]
@lifeiscontent see https://github.com/storybookjs/storybook/issues/14579.

The TLDR is:

1. In code: You can set an arg to `undefined`, purely by not setting the arg in the story.
2. In controls: You can reset *all* arg values to the story's (so `undefined` if the story didn't set it) with the reset button
3. You cannot set a control to `undefined` if the story set a value.

This was a decision discussed at length with @shilman and @domyen, it seemed a good compromise between over-complicating things and letting a user do what they want to do.
