### ISSUE TITLE
Addon-docs: MDX CSS syntax highlight changed between 5.* and 6.*

### ISSUE THREAD

**Issue by patricklafrance** [storybookjs/storybook#13254]
**Describe the bug**
MDX CSS syntax highlight seems to have changed between 5.* and 6.*

For the following MDX block:

![image](https://user-images.githubusercontent.com/794579/100146878-966af300-2e68-11eb-936d-1e3e131639eb.png)

In 5.* I get:

![image](https://user-images.githubusercontent.com/794579/100146720-5572de80-2e68-11eb-9fa9-b4c6343738b9.png)

In 6.* I get:

![image](https://user-images.githubusercontent.com/794579/100146748-5e63b000-2e68-11eb-8787-0511c82fec2a.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
Please paste the results of `npx sb@next info` here.

**Additional context**

**Comment by shilman** [comment]
Is this happening in 6.0 and 6.1? @patricklafrance

**Comment by patricklafrance** [comment]
@shilman sorry, I took the screenshots with 6.1.4

**Comment by rhahne** [comment]
I'm experiencing a similar issue regarding MDX syntax highlight changes.
In our Storybook we have several code blocks, where we show SCSS specific code within an MDX code block like so:

```scss
// Static path: The directory your static files/assets reside:
$static-directory-path: "../assets";
$fonts-path: "#{$static-directory-path}/fonts";
```

In Storybook v6.0.x the syntax highlight is being rendered correctly like so:
![Screenshot 2021-03-24 at 15 17 14](https://user-images.githubusercontent.com/10713975/112326889-391b6d00-8cb5-11eb-9af5-d3cbc177c7f8.png)

In Storybook v6.1.x / and also in the latest v6.2.x the syntax highlighting is not being rendered as expected:
![Screenshot 2021-03-24 at 15 27 02](https://user-images.githubusercontent.com/10713975/112327072-6700b180-8cb5-11eb-965f-6d10cff884f1.png)

**Comment by timbomckay** [comment]
According to [the documentation](https://storybook.js.org/docs/vue/writing-docs/doc-blocks?_sm_au_=iVVBjjfRn3rjT7W5WTW4vK0p3MfC0#mdx-2), scss syntax highlighting isn't supported.

>You can also use the Source block in MDX. It accepts either a story ID or code snippet. Use the language for syntax highlighting. **It supports the following languages: javascript, jsx, json, yml, ,md, bash, css, html, tsx, typescript, graphql.**

Is there any way to add `scss` support?

**Comment by shilman** [comment]
@timbomckay we have CSS escape hatches all over the place that can be styled with SCSS, but we don't make guarantees about the stability of this API across releases

https://storybook.js.org/docs/react/configure/theming#css-escape-hatches

**Comment by shilman** [comment]
@timbomckay aha gotcha! sorry for the misunderstanding!

**Comment by shilman** [comment]
I think this one has a workaround that probably needs to be documented, where you import the themes directly yourself and it causes them to load properly. cc @jonniebigodes

**Comment by timbomckay** [comment]
@shilman Looking at the [syntax highlighter component](https://github.com/storybookjs/storybook/blob/main/lib/components/src/syntaxhighlighter/syntaxhighlighter.tsx), it looks like `scss` needs to be registered like so:

```tsx
// @ts-ignore
import scss from 'react-syntax-highlighter/dist/esm/languages/prism/scss';

...

ReactSyntaxHighlighter.registerLanguage('scss', scss);
```

Looking at the code as of `6.3.0`, if I put an `scss` code snippet in an `.mdx` file, it doesn't provide the correct token markup, so I don't think importing the theme will help in that regard.

If `scss` support isn't something you want to enable by default, could you provide documentation on how to add extra languages that `react-syntax-highlighter` supports but not included by storybook. There's other syntax highlighting that I'd love such as `diff` but don't know that Storybook needs to provide all possible options out of the box.

I'd also love the ability to change the theme as you previously mentioned, but my first concern is getting `scss` syntax highlighting.

**Comment by timbomckay** [comment]
> @shilman Looking at the [syntax highlighter component](https://github.com/storybookjs/storybook/blob/main/lib/components/src/syntaxhighlighter/syntaxhighlighter.tsx), it looks like `scss` needs to be registered like so:
> 
> ```tsx
> // @ts-ignore
> import scss from 'react-syntax-highlighter/dist/esm/languages/prism/scss';
> 
> ...
> 
> ReactSyntaxHighlighter.registerLanguage('scss', scss);
> ```
> 
> Looking at the code as of `6.3.0`, if I put an `scss` code snippet in an `.mdx` file, it doesn't provide the correct token markup, so I don't think importing the theme will help in that regard.
> 
> If `scss` support isn't something you want to enable by default, could you provide documentation on how to add extra languages that `react-syntax-highlighter` supports but not included by storybook. There's other syntax highlighting that I'd love such as `diff` but don't know that Storybook needs to provide all possible options out of the box.
> 
> I'd also love the ability to change the theme as you previously mentioned, but my first concern is getting `scss` syntax highlighting.

Also, I can create a separate issue for `scss` syntax highlighting if needed since the original comment was regarding `css`. Let me know if I should do that or if this thread is fine.

**Comment by shilman** [comment]
@timbomckay we won't add those to the defaults, but we will make documentation on how to customize the syntax highlighter to your needs
