### ISSUE TITLE
Add `statics` config option to replace `--static-dir`

### ISSUE THREAD

**Issue by ghengeveld** [storybookjs/storybook#13250]
## Context
Currently we have the `-s` or `--static-dir` CLI option to specify one or more directories to be served as static files by Express (or copied over with build-storybook). The option exists on both `start-storybook` and `build-storybook`, and should typically be the same. However, sometimes these two are not the same, leading to inconsistencies between the statically built Storybook and the live Storybook. 

Furthermore, configuring it this way is different from how we tell Storybook where to find stories, even though these two things are very much related.

## Proposal
I propose introducing a `static` config option for `main.js`, right besides and similar to the existing `stories` option. It should take an array of globs, just like `stories` does.

Meanwhile, we should deprecate the `-s` / `--static-dir` CLI option, to be removed in the next major release.

**Comment by ndelangen** [comment]
YES, this would also open up the option for presets to add static files!!!

**Comment by shilman** [comment]
We want to address this in 6.3. If you want to contribute to Storybook, we'll prioritize PR review for any fixes here. And if you'd like any help getting started, please jump into the #support channel on our Discord: https://discord.gg/storybook

**Comment by oscard0m** [comment]
I have close to 0 experience contribyting to `storybook` but with assistance maybe this could be something I could jump and help. Is this ok or is already assigned to somebody else? With my expertise and guidance, do you think is feasable?

**Comment by ndelangen** [comment]
Hey @oscard0m if you'd like, we could schedule a meeting to talk about contributing to storybook:
https://calendly.com/ndelangen/storybook

Feel free to put something in my calendar!

**Comment by oscard0m** [comment]
> Hey @oscard0m if you'd like, we could schedule a meeting to talk about contributing to storybook:
> https://calendly.com/ndelangen/storybook
> 
> Feel free to put something in my calendar!

Hi @ndelangen and sorry for the delay in the response. These days I'm focused on searching for a new job and studying for it, so I don't have the time I would like to work on this. Still interest into it but I don't want to block other interested contributors if there are.

**Comment by ndelangen** [comment]
@oanaOM ready when you are! I send you an email with the zoom link.

**Comment by shilman** [comment]
Good golly!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-beta.27 containing PR #15969 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
