### ISSUE TITLE
Cannot import a TypeScript module named "macro"

### ISSUE THREAD

**Issue by sbj42** [storybookjs/storybook#13258]
**Describe the bug**

In a TypeScript React project, any stories that indirectly use a module named "macro" do not appear.  A "Cannot find module" error appears in the output.

**To Reproduce**

1. Clone https://github.com/sbj42/storybook-macro-issue
2. `npm install`
3. `npm run storybook`

That repo was created with `npx create-react-app storybook-macro-issue --template typescript` and `npx sb init`, and then a simple `macro.ts` file was added and referenced from the "Button" component.

Error message:
```
WARNING in ./src/stories/Button.stories.tsx
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: <storybook-macro-issue>\src\stories\Button.stories.tsx: Cannot find module '../macro' from '<storybook-macro-issue>\src\stories'
    at Function.resolveSync [as sync] (<storybook-macro-issue>\node_modules\resolve\lib\sync.js:89:15)
    at nodeResolvePath (<storybook-macro-issue>\node_modules\babel-plugin-macros\dist\index.js:68:18)
    at applyMacros (<storybook-macro-issue>\node_modules\babel-plugin-macros\dist\index.js:207:23)
    at ImportDeclaration (<storybook-macro-issue>\node_modules\babel-plugin-macros\dist\index.js:114:28)
```

**Expected behavior**

No error and the "Button" component should appear in the storybook.

**Analysis**

I suspect this is ultimately caused by this line in `babel-plugin-macros`: https://github.com/kentcdodds/babel-plugin-macros/blob/master/src/index.js#L6

```js
const macrosRegex = /[./]macro(\.js)?$/
```

It looks like it considers `import ... from '../macro'` to be some kind of special import.  I think that fails and then it falls back to regular module loading, except that in the fallback back it's only looking for `.js` files, so `macro.ts` is not found.

I don't know whether it is an issue with the way storybook is using `babel-plugin-macros`, or an issue in `babel-plugin-macros` itself.

**System**

```
Environment Info:

  System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-3820 CPU @ 3.60GHz
  Binaries:
    Node: 12.16.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 86.0.4240.198
    Edge: Spartan (44.19041.423.0), Chromium (87.0.664.47)
  npmPackages:
    @storybook/addon-actions: ^6.1.5 => 6.1.5
    @storybook/addon-essentials: ^6.1.5 => 6.1.5
    @storybook/addon-links: ^6.1.5 => 6.1.5
    @storybook/node-logger: ^6.1.5 => 6.1.5
    @storybook/preset-create-react-app: ^3.1.5 => 3.1.5
    @storybook/react: ^6.1.5 => 6.1.5
```

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
