### ISSUE TITLE
Emotion CSS stringify errors after upgrading to 6.1.5

### ISSUE THREAD

**Issue by KevinGhadyani-minted** [storybookjs/storybook#13253]
**Describe the bug**
Seeing Emotion CSS stringify object errors on a `css` attribute after upgrading to `6.1.3` or `6.1.5`.

This issue does not occur when using `6.1.0`, `6.1.1`, or `6.1.2`.

**To Reproduce**

1. Upgrade to Storybook `6.1.5` (tested both: `6.1.3`, and `6.1.5`).
1. Open Storybook with something that has Emotion CSS.
1. See error.

**Expected behavior**
I expect this to render CSS classes instead of text in a `class` attribute. The `css` property should not be rendered as an HTML attribute and also does not contain text; it contains the an Emotion CSS class object.

**Screenshots**
![image](https://user-images.githubusercontent.com/45860344/100140352-73cfde80-2e56-11eb-9933-bf455687897c.png)

**Code snippets**
`babel.config.js`

```js
{
  plugins: (
    [
      '@babel/plugin-proposal-object-rest-spread',
      '@babel/plugin-transform-runtime',
      'babel-plugin-emotion',
    ]
      .concat(
        isDevelopment
          ? 'react-hot-loader/babel'
          : []
      )
  ),
  presets: [
    [
      '@babel/preset-env',
      {
        modules: (
          isTest
            ? 'commonjs'
            : false
        ),
        useBuiltIns: false,
      },
    ],
    '@babel/preset-react',
    '@emotion/babel-preset-css-prop',
  ],
}
```

Any React component with Emotion styling:
```jsx
const tabContainerStyles = css`
  width: 100%;
`

const SomeComponent = ({
  children,
}) => {
  <div css={tabContainerStyles}>
     {children}
  </div>
)
```

**System**
Docker container in the working state:
```
  System:
    OS: Linux 5.4 Alpine Linux
    CPU: (4) x64 AMD Ryzen 7 3800X 8-Core Processor
  Binaries:
    Node: 12.19.1 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
  npmPackages:
    @storybook/addon-actions: 6.0.28 => 6.0.28
    @storybook/addon-essentials: 6.0.28 => 6.0.28
    @storybook/addon-links: 6.0.28 => 6.0.28
    @storybook/react: 6.0.28 => 6.0.28
```

**Additional context**
I logged the Babel config and _did_ see `'@emotion/babel-preset-css-prop',` at the bottom in all versions tested.

**Comment by mverissimo** [comment]
What version of **emotion** are you using?

I received the same error using **emotion(11)**, but I think this, not a bug with the storybook and yes with the **emotion**.

**Comment by KevinGhadyani-minted** [comment]
```json
  {
    "@emotion/cache": "^10.0.29",
    "@emotion/core": "^10.0.35",
    "@emotion/babel-preset-css-prop": "^10.0.9",
    "babel-plugin-emotion": "^10.0.33",
    "emotion": "^10.0.27",
  }
```

Strange that this would occur only after updating though.

**Comment by mverissimo** [comment]
Stranger, but I think this is a bug with emotion yet, you can share a repo case?

**Comment by KevinGhadyani-minted** [comment]
I do not sadly.

After some playing around with another Storybook project:
- Storybook v6.1 only works with Emotion v11.
- Storybook v6.0 only works with Emotion v10.

**Comment by mverissimo** [comment]
Ok, maybe import the [jsx pragma](https://5faaafd0bd0f3f0008469537--emotion.netlify.app/docs/css-prop#jsx-pragma) solve this problem!

**Comment by KevinGhadyani-minted** [comment]
You might be onto something with JSX pragma. I've tried a number of things to mess with configurations and found some more info.

I have two projects both with Storybook and with different configurations.

Both showed this error if I only used `@emotion/babel-plugin` along with:
```js
    [
      '@babel/preset-react',
      {
        importSource: '@emotion/react',
        runtime: 'automatic',
      },
    ],
```

Although, using `@emotion/babel-preset-css-prop`, everything works fine. Something about processing React 17 and `@babel/preset-react` may not be working properly with Emotion _or_ that `@emotion/babel-preset` isn't working as intended.

These look like issues unrelated to Storybook, but I'm not certain because I only saw these errors after upgrading Storybook. And it definitely seems fishy when certain versions of Emotion don't work with certain versions of Storybook.

**Comment by mverissimo** [comment]
Recently I set up a storybook and everything works fine, check the [babel](https://github.com/mverissimo/twin.react/blob/develop/babel.config.js) maybe can help you.

**Comment by VivekFitkariwala** [comment]
> Recently I set up a storybook and everything works fine, check the [babel](https://github.com/mverissimo/twin.react/blob/develop/babel.config.js) maybe can help you.

@mverissimo where have you used emotion's css props?

**Comment by mverissimo** [comment]
Hi @VivekFitkariwala some other examples [here](https://github.com/ben-rogerson/twin.examples/tree/master/storybook-emotion)

**Comment by KevinGhadyani-minted** [comment]
Closing this issue as I've already resolved this issue. Certain versions of Storybook only work with certain versions of Emotion. It appears that the Emotion Babel props docs were updated recently to reflect the proper uses cases as well.
