### ISSUE TITLE
Storybook available on custom URL

### ISSUE THREAD

**Issue by CyberHippo** [storybookjs/storybook#13267]
**Is your feature request related to a problem? Please describe**
I can't figure out if I can use the `-h, --host [string]` option to set a custom URL (e.g. `localhost/mystorybook/`) for the storybook or not.

**Describe the solution you'd like**
Be able to specify an URL (e.g. `localhost/mystorybook/`) using the `-h, --host [string]` option or another option for `start-storybook`.

**Describe alternatives you've considered**
Using a proxy (Nginx, etc.).

---
Any help is welcome, thanks !

**Comment by CyberHippo** [comment]
Does not seem possible as of now. C.f. [/lib/core/src/server/dev-server.ts](https://github.com/storybookjs/storybook/blob/9c35dcdad4799b562e6c9bf3680b0652b99047da/lib/core/src/server/dev-server.ts#L389-L392).

**Comment by ndelangen** [comment]
`localhost/mystorybook/` is not a "host".
`example.com` is a host.

It should be usable to set a custom host AFAIK.

**Comment by CyberHippo** [comment]
@ndelangen I updated the description of the issue to avoid confusion.

**Comment by ndelangen** [comment]
I **think** you might be able to achieve this using a publicPath on the storybook config:

```js
// .storybook/main.js

module.exports = {
  managerWebpack: async (config, options) => {
    config.publicPath = '/my-directory/'
    return config;
  },
  webpackFinal: async (config, options) => {
    // change webpack config
    config.publicPath = '/my-directory/'
    return config;
  },
};
```
