### ISSUE TITLE
Controls not's works with angular after change

### ISSUE THREAD

**Issue by ClemThu** [storybookjs/storybook#13264]
If you are reporting a bug or requesting support, start here:
### Bug or support request summary

_Please provide issue details here - What did you expect to happen? What happened instead?_ 
When i change controls my angular components is not update, it works if i set default value but when i use controls to change angular components is not full loaded. I don't understand why ... i think issue is with *ngIf. I don't find doc or github for fix it ? It's works fine with simple html change but not on JS

### Steps to reproduce

import {
  Meta,
  Story,
  ArgsTable,
  Description,
  Canvas,
} from '@storybook/addon-docs/blocks';
import { MyseDatagridModule } from './myse-datagrid.module';
import { MyseDatagridComponent } from './myse-datagrid.component';
import { moduleMetadata } from '@storybook/angular';
import { SeWebModule } from '@se/web-ui-angular';
import { action } from '@storybook/addon-actions';
import { boolean, select, text, date, withKnobs } from '@storybook/addon-knobs';

export const argTypes = {};

<Meta
  title="HOME PAGES/Datagrid"
  component={MyseDatagridComponent}
  argTypes={argTypes}
  decorators={[
    moduleMetadata({
      imports: [MyseDatagridModule, SeWebModule],
    }),
    withKnobs,
  ]}
/>

export const ngModelChange = action('ngModelChange');

# Input component

<Description of={MyseDatagridComponent} />

export const Template = (args) => ({
  component: MyseDatagridComponent,
  props: args,
});

<Canvas>
  <Story
    name="Try component"
    height="200px"
    args={{
      businessUnit: '',
      backendUrl: '',
      countryCode: '',
      languageCode: '',
      type: '',
    }}
  >
    {Template.bind({})}
  </Story>
</Canvas>

## Properties

<ArgsTable of={MyseDatagridComponent} />

### Please specify which version of Storybook and optionally any affected addons that you're running

@storybook/angular v6.0.21
Angular 10

**Comment by Marklb** [comment]
I don't know what is going on, since there isn't any implementation details and only a mention of a `*ngIf` that I assume is somewhere in your component.

My best guess is that it has to do with control changes emitting outside the zone, but I am just guessing, since the problem happens when using a control. If that is the problem, it should be fixed by #12382.

**Comment by ThibaudAV** [comment]
@ClemThu can you test with the latest version of storybook otherwise I think this issue is solved with https://github.com/storybookjs/storybook/pull/12382 🤔 

FYI : 
> Ermahgerd!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.0-alpha.0 containing PR #12382 that references this issue. Upgrade today to the `@next` NPM tag to try it out!
> 
> ```
> npx sb upgrade --prerelease
> ```
> 
> Closing this issue. Please re-open if you think there's still more to do.

**Comment by rdebeasi** [comment]
Hello! I'm experiencing a similar issue with `@storybook/angular` 6.4.19. The controls work with the default components that are created when you initialize Storybook, but they don't work with my own components.

Args set in the story take effect, but args set in the controls do not. Here are a few example snippets:

#### From Button.stories.ts
```ts
export const Primary = Template.bind({});
Primary.args = {
  variant: 'primary',
  id: 'foo'
};
export const Secondary = Template.bind({});
Secondary.args = {
  variant: 'secondary'
};
```

#### From button.component.ts
```ts
export class ButtonComponent {
  @Input() id?: string;
```

#### From button.component.html
```
<button
  [attr.id]="id"
```

The id `foo` is applied to the primary button, but nothing happens when I use the controls to set an id on the primary or secondary button.

**Comment by ndelangen** [comment]
@rdebeasi can you supply a reproduction, so we can investigate?

**Comment by abraham-becker-buildium** [comment]
> Hello! I'm experiencing a similar issue with `@storybook/angular` 6.4.19 and Angular 12. The controls work with the default components that are created when you initialize Storybook, but they don't work with my own components.
> 
> Args set in the story take effect, but args set in the controls do not. Here are a few example snippets:
> 
> #### From Button.stories.ts
> ```ts
> export const Primary = Template.bind({});
> Primary.args = {
>   variant: 'primary',
>   id: 'foo'
> };
> export const Secondary = Template.bind({});
> Secondary.args = {
>   variant: 'secondary'
> };
> ```
> 
> #### From button.component.ts
> ```ts
> export class ButtonComponent {
>   @Input() id?: string;
> ```
> 
> #### From button.component.html
> ```
> <button
>   [attr.id]="id"
> ```
> 
> The id `foo` is applied to the primary button, but nothing happens when I use the controls to set an id on the primary or secondary button.

Did you find a solution @rdebeasi ? I'm having the same issue where args are set, but control modifications are not updating the rendered component..

**Comment by rdebeasi** [comment]
I ended up hiding the controls, so I haven't dug in any further. Sorry about that!

If you could [create a repro](https://storybook.js.org/docs/react/contribute/how-to-reproduce), that would help the Storybook folks troubleshoot. (A repro would also help determine whether the bug still exists in Storybook 7.)
