### ISSUE TITLE
New Zoom component breaks IE11 support in v6.1.x

### ISSUE THREAD

**Issue by stu039** [storybookjs/storybook#13272]
### Bug or support request summary

A function that is part of the new Zoom component that was introduced as part of this PR https://github.com/storybookjs/storybook/pull/12845 , seems to be breaking storybook addon-docs in IE11. (See screenshots below for errors seen)

The issue originates from the function shown in screenshot below
<img width="1205" alt="Screenshot 2020-11-25 at 17 16 49" src="https://user-images.githubusercontent.com/48241332/100261918-59276380-2f43-11eb-9479-eed98e19b7b7.png"> (file lib/components/src/Zoom/Zoom.tsx)

The DOMImplementation.createHTMLDocument() function takes a string as an argument that is the title of the document, however this is non-optional in IE. One can however, pass an empty string to this function which resolves the error.

### Steps to reproduce

Run storybook with addon-docs enabled, load it in IE11.

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react 6.1.5
- @storybook/addons: 6.1.5

### Affected platforms 

Internet Explorer 11

### Screenshots / Screencast / Code Snippets (Optional)
Errors seen in browser:
<img width="785" alt="Screenshot 2020-11-25 at 15 13 26" src="https://user-images.githubusercontent.com/48241332/100263850-f08db600-2f45-11eb-9de9-10d08e113341.png">
<img width="927" alt="Screenshot 2020-11-25 at 15 13 35" src="https://user-images.githubusercontent.com/48241332/100263859-f2f01000-2f45-11eb-9c21-49e04aa08018.png">
Passing an empty string to the function achieves the same result, and will work in IE11. See below for suggested fix:
```js
window.document.implementation.createHTMLDocument("").body.style.zoom !== undefined;
```

**Comment by stu039** [comment]
Also note, this can be reproduced in the live storybook app in IE11 here example page that errors -  https://next--storybookjs.netlify.app/official-storybook/?path=/docs/addons-a11y-basebutton--default

**Comment by tooppaaa** [comment]
@stu039 Awesome detective job ! Thanks

**Comment by shilman** [comment]
Boo-yah!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.8 containing PR #13302 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```

Closing this issue. Please re-open if you think there's still more to do.
