### ISSUE TITLE
Storybook too slow to load in the first page

### ISSUE THREAD

**Issue by Kilims** [storybookjs/storybook#13282]
**Describe the bug**
base on create-react-app, i already successfully integrate storybook with it and build , deploy storybook to server

however i found it quite slow to have initial load, which takes almost 20-30s

check this image out
![image](https://user-images.githubusercontent.com/22916814/100303926-a0abff00-2fd8-11eb-83ee-c3b4af1758e1.png)

**To Reproduce**

1. initial create-react-app
2. have below main.js
```
// .storybook/main.js
module.exports = {
  stories: ['../src/**/*.stories.@(js)'],
  addons: [
    'storybook-mobile',
    '@storybook/preset-create-react-app',
    '@storybook/addon-links',
    '@storybook/addon-knobs',
    'storybook-addon-responsive-views',
    '@storybook/addon-viewport',
    '@storybook/addon-storysource', // a managerEntry
    '@storybook/addon-docs', // a preset
  ]
};
```
3. and it s entry point is quite large
```
WARN asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
WARN This can impact web performance.
WARN Assets: 
WARN   vendors~main.8a60da3d56c60b38c02a.bundle.js (2.61 MiB)
WARN entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
WARN Entrypoints:
WARN   main (2.62 MiB)
WARN       runtime~main.8a60da3d56c60b38c02a.bundle.js
WARN       vendors~main.8a60da3d56c60b38c02a.bundle.js
WARN       main.8a60da3d56c60b38c02a.bundle.js
WARN 
WARN webpack performance recommendations: 
WARN You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
WARN For more info visit https://webpack.js.org/guides/code-splitting/
```

storybook version is 6.1.6 and it is quite large (2.62MB) of the main.js, any chance (like webpack config ?) could split it out ?

**Comment by cherylcarpenter** [comment]
Hi - I have this issue as well. Any attempts at chunking the main.js entry point are not working. 
Storybook version 6.12.1

WARN asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
WARN This can impact web performance.
WARN Assets: 
WARN   vendors~main~542d3772.e8858a0f4832bec18161.bundle.js (449 KiB)
WARN entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
WARN Entrypoints:
WARN   main (2.32 MiB)
WARN       vendors~main~0f485567.e8858a0f4832bec18161.bundle.js
WARN       vendors~main~60b88c48.e8858a0f4832bec18161.bundle.js
WARN       vendors~main~41a6ab2c.e8858a0f4832bec18161.bundle.js
WARN       vendors~main~9ba412a3.e8858a0f4832bec18161.bundle.js
WARN       vendors~main~ba0972d8.e8858a0f4832bec18161.bundle.js
WARN       vendors~main~f4520c04.e8858a0f4832bec18161.bundle.js
WARN       vendors~main~0decbd73.e8858a0f4832bec18161.bundle.js
WARN       vendors~main~483195ab.e8858a0f4832bec18161.bundle.js
WARN       vendors~main~d1288e48.e8858a0f4832bec18161.bundle.js
WARN       vendors~main~e6e6abf1.e8858a0f4832bec18161.bundle.js
WARN       vendors~main~a868a73b.e8858a0f4832bec18161.bundle.js
WARN       vendors~main~68416595.e8858a0f4832bec18161.bundle.js
WARN       vendors~main~cbe0bd4a.e8858a0f4832bec18161.bundle.js
WARN       vendors~main~542d3772.e8858a0f4832bec18161.bundle.js
WARN       vendors~main~0cb12a84.e8858a0f4832bec18161.bundle.js
WARN       vendors~main~1a2928b1.e8858a0f4832bec18161.bundle.js
WARN       vendors~main~e3a01b6a.e8858a0f4832bec18161.bundle.js
WARN       vendors~main~463f1ea5.e8858a0f4832bec18161.bundle.js
WARN       vendors~main~ed17b628.e8858a0f4832bec18161.bundle.js
WARN       vendors~main~44327899.e8858a0f4832bec18161.bundle.js
WARN       vendors~main~54f0c24f.e8858a0f4832bec18161.bundle.js
WARN       vendors~main~df17a77b.e8858a0f4832bec18161.bundle.js
WARN       vendors~main~b1c32265.e8858a0f4832bec18161.bundle.js
WARN       vendors~main~1ac54558.e8858a0f4832bec18161.bundle.js
WARN       vendors~main~0877d030.e8858a0f4832bec18161.bundle.js
WARN       vendors~main~c8b8e4f4.e8858a0f4832bec18161.bundle.js
WARN       vendors~main~5611a721.e8858a0f4832bec18161.bundle.js
WARN       vendors~main~054afb4f.e8858a0f4832bec18161.bundle.js
WARN       vendors~main~a592364b.e8858a0f4832bec18161.bundle.js
WARN       vendors~main~99e3d249.e8858a0f4832bec18161.bundle.js
WARN       vendors~main~89f0f605.e8858a0f4832bec18161.bundle.js
WARN       vendors~main~bc1328b0.e8858a0f4832bec18161.bundle.js
WARN       vendors~main~f9596873.e8858a0f4832bec18161.bundle.js
WARN       vendors~main~d939e436.e8858a0f4832bec18161.bundle.js
WARN       vendors~main~92c00e46.e8858a0f4832bec18161.bundle.js
WARN       vendors~main~85de788a.e8858a0f4832bec18161.bundle.js
WARN       vendors~main~31c671ca.e8858a0f4832bec18161.bundle.js
WARN       vendors~main~216d6f1c.e8858a0f4832bec18161.bundle.js
WARN       vendors~main~2feed8ba.e8858a0f4832bec18161.bundle.js
WARN       vendors~main~b5906859.e8858a0f4832bec18161.bundle.js
WARN       vendors~main~db300d2f.e8858a0f4832bec18161.bundle.js
WARN       vendors~main~a2d4c09c.e8858a0f4832bec18161.bundle.js
WARN       vendors~main~d5f5f962.e8858a0f4832bec18161.bundle.js
WARN       vendors~main~56f7da9c.e8858a0f4832bec18161.bundle.js
WARN       vendors~main~19026fb8.e8858a0f4832bec18161.bundle.js
WARN       vendors~main~1f20a385.e8858a0f4832bec18161.bundle.js
WARN       vendors~main~7d359b94.e8858a0f4832bec18161.bundle.js
WARN       vendors~main~7777d9b4.e8858a0f4832bec18161.bundle.js
WARN       vendors~main~b92ffc84.e8858a0f4832bec18161.bundle.js
WARN       vendors~main~2930ad93.e8858a0f4832bec18161.bundle.js
WARN       vendors~main~2697033a.e8858a0f4832bec18161.bundle.js
WARN       vendors~main~a88fed2c.e8858a0f4832bec18161.bundle.js
WARN       vendors~main~1c2eaadf.e8858a0f4832bec18161.bundle.js
WARN       vendors~main~9c5b28f6.e8858a0f4832bec18161.bundle.js
WARN       vendors~main~f5d2d7da.e8858a0f4832bec18161.bundle.js
WARN       vendors~main~f9ca8911.e8858a0f4832bec18161.bundle.js
WARN       vendors~main~3af8bccc.e8858a0f4832bec18161.bundle.js
WARN       vendors~main~343204d7.e8858a0f4832bec18161.bundle.js
WARN       vendors~main~873a5664.e8858a0f4832bec18161.bundle.js
WARN       vendors~main~678f84af.e8858a0f4832bec18161.bundle.js
WARN       vendors~main~f734b0c6.e8858a0f4832bec18161.bundle.js
WARN       vendors~main~bacacef5.e8858a0f4832bec18161.bundle.js
WARN       vendors~main~f2a41953.e8858a0f4832bec18161.bundle.js
WARN       vendors~main~2169f593.e8858a0f4832bec18161.bundle.js
WARN       vendors~main~1b7a8351.e8858a0f4832bec18161.bundle.js
WARN       vendors~main~0928ebd2.e8858a0f4832bec18161.bundle.js
WARN       vendors~main~98431bb7.e8858a0f4832bec18161.bundle.js
WARN       vendors~main~1631828a.e8858a0f4832bec18161.bundle.js
WARN       vendors~main~628a6172.e8858a0f4832bec18161.bundle.js
WARN       vendors~main~b53625c7.e8858a0f4832bec18161.bundle.js
WARN       vendors~main~cfbf0a2e.e8858a0f4832bec18161.bundle.js
WARN       vendors~main~fdc6512a.e8858a0f4832bec18161.bundle.js
WARN       vendors~main~daa565d3.e8858a0f4832bec18161.bundle.js
WARN       main~24120820.e8858a0f4832bec18161.bundle.js
WARN       main~970f9218.e8858a0f4832bec18161.bundle.js
WARN       main~c119f8d7.e8858a0f4832bec18161.bundle.js
WARN 
WARN webpack performance recommendations: 
WARN You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
WARN For more info visit https://webpack.js.org/guides/code-splitting/
