### ISSUE TITLE
Search keyboard shortcut doesn't work with non-US keyboard layout

### ISSUE THREAD

**Issue by whitezo** [storybookjs/storybook#13296]
**Describe the bug**
Using the Hungarian keyboard layout on a Mac results in some of the shortcuts not functioning.
"/" would be "Shift+6" but that doesn't invoke the search functionality, nor the "original" bottom right key (which is the "-" on a Hun. layout).

**To Reproduce**
1. Switch to Hungarian keyboard layout
2. Press "Shift+6" or "original" slash key

**Expected behavior**
Search input is highlighted

**System**
Mac OS Catalina / Chrome v86 (or any other browser)
Storybook v6.1.5

**Comment by shilman** [comment]
cc @ghengeveld

**Comment by ghengeveld** [comment]
Could you go to https://keycode.info, press the `/` key on your keyboard (or whatever key you expect to focus the search), and post the data it gives here?

**Comment by ghengeveld** [comment]
Do you need to press a modifier key to type a `/` on your keyboard? Right now we disable the keybinding when used with shift/ctrl/alt/cmd, so it'll only work when you can type `/` without one.

**Comment by ghengeveld** [comment]
Based on [this](https://docs.microsoft.com/en-us/globalization/keyboards/kbdhu1.html) it seems you need Shift-6 to type a `/`. I'll update our logic to support this.

**Comment by shilman** [comment]
Boo-yah!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.9 containing PR #13319 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```

Closing this issue. Please re-open if you think there's still more to do.
