### ISSUE TITLE
CLI: Starting with cached manager now shows " for manager" in boot confirmation

### ISSUE THREAD

**Issue by ghengeveld** [storybookjs/storybook#13292]
This is a regression that happened while fixing some types. `managerTotalTime` used to be `0` and thereby falsy, so it wouldn't be printed. Recently this changed to `[0,0]` to be a valid hrtime, but this is truthy, causing an empty string to be printed followed by the `" for manager"` label.

<img width="403" alt="Screenshot 2020-11-26 at 14 12 26" src="https://user-images.githubusercontent.com/321738/100355075-6bf87180-2ff1-11eb-99b0-caf4ccacee0a.png">

**Comment by shilman** [comment]
¡Ay Caramba!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.7 containing PR #13294 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```

Closing this issue. Please re-open if you think there's still more to do.
