### ISSUE TITLE
Controls and props descriptions not working when served as a static app (React)

### ISSUE THREAD

**Issue by IvanMakarovDev** [storybookjs/storybook#13293]
**Describe the bug**
Controls and props descriptions not working when Storybook is served as a static app. Everything is working as expected when run in dev mode (`yarn storybook`)

**To Reproduce**

1. Build the app: `yarn build-storybook`
2. Serve the app `npx http-server ./storybook-static`
3. Go to `localhost:8080`
4. Controls do not get options from components' propTypes definition (e.g. when defined as `oneOf`)
5. In **Docs** section there is no description for props

**Expected behavior**
I can control components' state with selects that get options from propTypes.
I can see props' descriptions based on comments in the components' files

**Screenshots**
When run in dev mode (`yarn storybook`) everything is working as expected:
1. Canvas
![Screenshot from 2020-11-26 16-03-49](https://user-images.githubusercontent.com/51192907/100354374-26dc3b80-3001-11eb-9d7b-b12637d81ce9.png)
2. Docs
![Screenshot from 2020-11-26 16-03-57](https://user-images.githubusercontent.com/51192907/100354394-2d6ab300-3001-11eb-8c8a-8c0f109bbeeb.png)

When served as a static app, controls and props descriptions are not rendered properly
1. Canvas
![Screenshot from 2020-11-26 16-04-10](https://user-images.githubusercontent.com/51192907/100354502-55f2ad00-3001-11eb-8f0f-e549283ba94d.png)
2. Docs
![Screenshot from 2020-11-26 16-04-18](https://user-images.githubusercontent.com/51192907/100354523-5ab76100-3001-11eb-8c7e-5cee7a69a8f6.png)

**Code snippets**
1. Component (this behaviour is the same for all components across the app)
```jsx
import React from 'react';
import PropTypes from 'prop-types';

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import variables, { palette } from 'shared/components/CRM/UI/variables';

const TempIcon = (props) => {
  const {
    size,
    variant,
    inactive,
  } = props;

  const iconColor = !inactive && variant
    ? palette[variant]
    : palette.unchecked;

  return (
    <FontAwesomeIcon
      icon={variables.leadTempIcons[variant]}
      size={size}
      style={{ color: iconColor }}
    />
  );
};

TempIcon.defaultProps = {
  size: 'lg',
  inactive: false,
};

const {
  bool,
  oneOf,
} = PropTypes;

TempIcon.propTypes = {
  /**
   * lead temp variant
   */
  variant: oneOf(['cold', 'warm', 'hot']).isRequired,
  /**
   * icon size
   */
  size: oneOf(['sm', 'lg', 'xl']),
  /**
   * is inactive - if true, the icon will be greyed out
   */
  inactive: bool,
};

export default TempIcon;
```
2. Story
```mdx
import { 
  Meta, 
  Story, 
  Canvas, 
  ArgsTable,
} from '@storybook/addon-docs/blocks';

import TempIcon from './TempIcon';

<Meta 
  title="CRM/UI/TempIcon" 
  component={TempIcon} 
/>

# TempIcon

<ArgsTable of={TempIcon} />

export const Template = (args) => <TempIcon {...args} />

<Canvas>
  <Story 
    name="TempIcon" 
    args={{ 
      variant: 'hot'
    }}
  >
    {Template.bind({})}
  </Story>  
</Canvas>
```

**System**
```
  System:
    OS: Linux 4.15 Ubuntu 16.04.7 LTS (Xenial Xerus)
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
  Binaries:
    Node: 10.17.0 - ~/.nvm/versions/node/v10.17.0/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 6.11.3 - ~/.nvm/versions/node/v10.17.0/bin/npm
  Browsers:
    Chrome: 86.0.4240.198
    Firefox: 83.0
  npmPackages:
    @storybook/addon-actions: ^6.1.1 => 6.1.6 
    @storybook/addon-essentials: ^6.1.1 => 6.1.6 
    @storybook/addon-links: ^6.1.1 => 6.1.6 
    @storybook/react: ^6.1.1 => 6.1.6 
```

**Additional context**
React v16.14.0

**Comment by shilman** [comment]
Do you have a repro repo you can share?

**Comment by IvanMakarovDev** [comment]
@shilman 
It turns out that the problem was with my custom webpack config, namely `babel-loader`:
```js
    config.module.rules.push({
        loader: 'babel-loader',
        exclude: /node_modules/,
        test: /\.(js|jsx)$/,
        options: {
            presets: ['@babel/react'],
            plugins: [
                ['import', {
                    libraryName: 'antd',
                    libraryDirectory: 'es',
                    style: true
                }]
            ]
        },
    });
```
I removed this and simply imported Antd styles in `preview.js`:
```js
import 'antd/dist/antd.css';
```
This seems to solve the problem

**Comment by shilman** [comment]
Glad you figured it out @IvanMakarovDev. Closing.
