### ISSUE TITLE
Core: Manager cache not busted when upgrading Storybook

### ISSUE THREAD

**Issue by ghengeveld** [storybookjs/storybook#13291]
When upgrading Storybook from `6.1.4` to `6.1.6`, I noticed the cached manager would continue to be used after the upgrade. This means the preview would be compiled with `6.1.6`, but the manager would still be the old one compiled with `6.1.4`.

We have to bust the manager cache when we detect a different version number. Probably just appending the version number to the cache key would suffice.

**Comment by shilman** [comment]
Yippee!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.3.0-alpha.44 containing PR #14993 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
