### ISSUE TITLE
`npx sb upgrade` incorrectly Warns about "outdated packages" for @storybook/storybook-deployer

### ISSUE THREAD

**Issue by haysclark** [storybookjs/storybook#13305]
**Describe the bug**
Running `npx sb upgrade` in a project with the latest version of `@storybook/storybook-deployer` will result in an incorrect warning that the package is outdated.

**To Reproduce**

1. Have a project with Storybook as NPM dependency:      
```json
{
  "devDependencies": {
    "@storybook/addon-actions": "^6.0.0",
    "@storybook/addon-essentials": "^6.0.0",
    "@storybook/addon-links": "^6.0.0",
    "@storybook/react": "^6.0.0",
    "@storybook/storybook-deployer": "^2.8.7"
  }
}
```
2. Run `npx sb upgrade`
4. See CLI error
```bash
npx sb upgrade
...
WARN Found 1 outdated packages (relative to '@storybook/core-events@6.1.7')
WARN Please make sure your packages are updated to ensure a consistent experience.
WARN - @storybook/storybook-deployer@2.8.7
```

**Expected behavior**
If the latest version of `@storybook/storybook-deployer` is installed, the `upgrade` command should not warn the user.

**System**
```
Environment Info:

  System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
  Binaries:
    Node: 10.22.0 - ~/.nvm/versions/node/v10.22.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v10.22.0/bin/npm
  Browsers:
    Chrome: 87.0.4280.67
    Firefox: 63.0.3
    Safari: 13.1.2
  npmPackages:
    @storybook/addon-actions: ^6.1.7 => 6.1.7 
    @storybook/addon-essentials: ^6.1.7 => 6.1.7 
    @storybook/addon-links: ^6.1.7 => 6.1.7 
    @storybook/react: ^6.1.7 => 6.1.7 
    @storybook/storybook-deployer: ^2.8.7 => 2.8.7 
```

**Comment by shilman** [comment]
Jeepers creepers!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.8 containing PR #13306 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```

Closing this issue. Please re-open if you think there's still more to do.
