### ISSUE TITLE
ArgsTable: Errors on TS components whose names are keywords

### ISSUE THREAD

**Issue by aricma** [storybookjs/storybook#13301]
### Bug or support request summary

I wrote a functional component with the function name "Switch". The storybook was strating and loading for ever. There was no indicator that somthing went wrong.
As I opened the console I saw an error leading me to fixing the name of my component into something other than switch. 

I am not sure if this is an edge case but if this error would have lead the storybook to crash or there would have been a message in the view, my search wouldn't have taken so long.

### Steps to reproduce

- write a story for a functional component with the name "Switch".
- start the storybook

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react 6.1.2
- @storybook/addon-* 6.1.2

### Affected platforms 

- macOs 11.0.1
- firefox developer edition 84.0b4

### Screenshots / Screencast / Code Snippets (Optional)

<img width="1181" alt="Screenshot 2020-11-26 at 8 45 25 PM" src="https://user-images.githubusercontent.com/22852149/100388122-02488980-302a-11eb-80bc-864e823cd3f4.png">

```js
const Switch: FunctionComponent<Switch> = (props) => {
    return (
        <Wrapper>
             <Knob>
        </Wrapper>
    );
};
```

**Comment by shilman** [comment]
Do you have a repro repo you can share?

**Comment by aricma** [comment]
> Do you have a repro repo you can share?

I will create one

**Comment by aricma** [comment]
@shilman https://github.com/aricma/reproduce-storybook-bug-13301

**Comment by shilman** [comment]
@hipstersmoothie Mind taking a quick look?

<img width="387" alt="Storybook" src="https://user-images.githubusercontent.com/488689/100691660-21497180-33c4-11eb-9418-ecf9de6f5e4b.png">

**Comment by hipstersmoothie** [comment]
Seeing if we can get a fix in https://github.com/styleguidist/react-docgen-typescript/pull/313

**Comment by shilman** [comment]
closing as dupe to #11980
