### ISSUE TITLE
Storyshots: Property 'done' does not exist on type 'TestMethodOptions'.

### ISSUE THREAD

**Issue by Pikachews** [storybookjs/storybook#13307]
**Describe the bug**
After upgrading to the latest of the storyshots addon, I've started to encounter the following Typescript error when performing async snapshot testing using the example:

```
storyshots.spec.ts: error TS2339: Property 'done' does not exist on type 'TestMethodOptions'.
```
![image](https://user-images.githubusercontent.com/5668416/100403142-e71e4f80-3012-11eb-8681-4c3f92a6e078.png)

However, if I cast the arguments to `any` type, the tests work exactly as I expect them to do, which seems to suggest the `done` method is still available, but the typings are inaccurate.

**To Reproduce**

Setup storyshots as per the example presented here with Typescript: https://www.npmjs.com/package/@storybook/addon-storyshots#storyshots-for-async-rendered-components

**Expected behavior**

No Typescript error is expected.

**Comment by Pikachews** [comment]
Bumping to keep stalebot away.

**Comment by ndelangen** [comment]
The future of storyshots is the test-runner:
https://storybook.js.org/docs/react/writing-tests/test-runner#page-top

And use the play function for expectations:
https://storybook.js.org/docs/react/writing-stories/play-function#page-top

We will not be making any improvement / changes to storyshots.
