### ISSUE TITLE
Group name includes leading and trailing whitespace

### ISSUE THREAD

**Issue by x4th** [storybookjs/storybook#13311]
I'm trying to move one component group to the top to have it displayed before all others.

```
// .storybook/preview.tsx

export const parameters = {
  options: {
    storySort: {
      order: ['Line Items'],
    },
  },
}
```

This however has no effect and when I looked inside the related story I see I used:
```
// components/LineItems/SingleLineItems.stories.tsx

export default {
  component: SingleLineItem,
  title: 'Line Items / Single Line Item',
}
```

If I change `order: ['Line Items'],` to `order: ['Line Items '],` in the first file or `title: 'Line Items / Single Line Item',` to `title: 'Line Items/Single Line Item',` the group moves to the top. If there's a reason why whitespace here should matter you should at least make a note in the docs warning users to not have spaces around the slash.

**Comment by ghengeveld** [comment]
Related: https://github.com/storybookjs/storybook/pull/13275

**Comment by x4th** [comment]
Hey, can you tell me how to do that? I tried running `yarn add storybook@6.2.0-alpha.0` but when I run storybook (`yarn storybook`) which is `start-storybook -p 6006` that still calls the old (stable) version. I checked the docs but couldn't find anything on this.

**Comment by ghengeveld** [comment]
@x4th You probably need to run with `--no-manager-cache`.

**Comment by bodograumann** [comment]
I have the exact same issue with storybook v6.2.9.
The only difference is, that I’m defining the stories in mdx format.

**Comment by ghengeveld** [comment]
@bodograumann Can you give an example of such a story file?

**Comment by bodograumann** [comment]
At least it is consistent, so that when I include the trailing space in the sort order, it works. :-D
Here is an example:
```
import { ArgsTable, Meta, Story } from "@storybook/addon-docs/blocks";
import Toast from "@/components/generic/Toast.vue";

<Meta title="Generic / Toast" component={Toast} />

# Toast

<ArgsTable />

Toast messages come in three flavors.

## Information

<Story name="Notice">
  {{
    components: { Toast },
    template: `
    <Toast
      severity="info"
      title="Notice"
      text="An alert has been triggered."
    />
  `,
  }}
</Story>
```

I left away the other two stories for brevity.

Relevant `preview.js` part goes along the lines of:
```
export const parameters = {
  options: {
    storySort: {
      method: "alphabetical",
      order: [
        "Generic ",
        "Section2 ",
        "Section3 ",
        "… ",
      ],
    },
  },
};
```

**Comment by ghengeveld** [comment]
@bodograumann Thanks. I confirmed an fixed the problem: #15038

**Comment by shilman** [comment]
Olé!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.3.0-beta.1 containing PR #15038 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by bodograumann** [comment]
Just upgraded to 6.3-rc.11 and it works very well. Thank you!
