### ISSUE TITLE
Storybook ^6.1.4 is not IE11 compatible

### ISSUE THREAD

**Issue by beckerei** [storybookjs/storybook#13314]
**Describe the bug**
Syntax Error in IE11

**Additional context**
Introduced with https://github.com/storybookjs/storybook/commit/d07c22dc4cfc44eb0d3fe76a15b3383562772a66#diff-1ba439b44eefbba0e96d6d5e3fed47a889b4d5f669a6aa9e6baebedfb7e4dec1

```js
JSON.stringify({ message, source, line, column, error, origin: 'preview' }),
```

IE11 does not understand object shorthand syntax.

**Comment by ghengeveld** [comment]
😓 can't wait to drop IE support.

**Comment by beckerei** [comment]
@ ghengeveld Can relate. 

here is a lot of fun in working enterprise, but supporting IE11 is a downer.
I celebrated hard we were able to drop IE10 a few years ago ...

Let me know if I can help you out by taking this over.

**Comment by shilman** [comment]
Crikey!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.0-alpha.2 containing PR #13348 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
