### ISSUE TITLE
Class attribute stripped from rendered Vue source

### ISSUE THREAD

**Issue by dcrall** [storybookjs/storybook#13326]
I upgraded from 6.0 to 6.1 and noticed the new rendering for Vue stories as described in #11400. First of all, thank you for this work. It is an improvement overall. However, I noticed that both static and dynamic class attributes are being stripped from the source rendering removing important context from the story. Please see the following screenshots and note the two plain divs that start the template. They should both have a class attribute.

<img width="1035" alt="Storybook-6 0" src="https://user-images.githubusercontent.com/42922/100530105-7bbfb380-31b3-11eb-8c5c-11174a718bd1.png">

<img width="1045" alt="storybook-6 1" src="https://user-images.githubusercontent.com/42922/100530107-82e6c180-31b3-11eb-86f7-fbdb1c5ac2dd.png">

The stories are defined in an MDX file. Here is the code for the story:

```MDX
export const formLayoutArgTypes = {
  gridDef: {
    name: 'gridDef',
    type: { name: 'string', required: false },
    defaultValue: 'grid grid-cols-1 gap-4',
    description: 'Tailwind grid definition'
  },
  ...
}

export const GridTemplate = (args, { argTypes }) => ({
  props: Object.keys(argTypes),
  components: { AisInput },
  template: `
    <div class="container mx-auto mt-4">
      <div :class="gridDef">
        <AisInput id="first-1" label="First" description="You can go your own way" :class="firstClass" placeholder="First Name" />
        <AisInput id="last-1" label="Last" description="Don't stop believing" :class="lastClass" placeholder="Last Name" />
        <AisInput id="email-1" label="Email" description="So what, so what, so what you want?" :class="emailClass" />
      </div>
    </div>
  `,
});

<Canvas>
  <Story
    name="Simple Layout"
    args={{
      gridDef: 'grid grid-cols-1 gap-4',
    }}
    argTypes={{...formLayoutArgTypes}}
  >
    {GridTemplate.bind({})}
  </Story>
</Canvas>

<ArgsTable story="Simple Layout" />
```

Am I doing something wrong here?

**Comment by dcrall** [comment]
@pocka, @shilman - I would appreciate your feedback. Thank you.

**Comment by shilman** [comment]
Thanks @dcrall, I'm guessing this is a bug in the vue rendering. As a temporary workaround you can set `docs.source.type` parameter to "code" to restore the old behavior.

**Comment by shilman** [comment]
Yippee!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.9 containing PR #13327 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by dcrall** [comment]
Perfect. I tested with 6.1.9, and everything looks great. Thank you for the quick turnaround.

It was also cool to see that class attributes tied to story args appear dynamically when a value is added.

<img width="1090" alt="Storybook-6 1 9" src="https://user-images.githubusercontent.com/42922/100546073-ee1cac00-3224-11eb-9019-2f8b1059bed5.png">
