### ISSUE TITLE
Using TS 4.1 template literal types break build

### ISSUE THREAD

**Issue by sami616** [storybookjs/storybook#13328]
Does the version of ts that sb uses need upgrading?

https://devblogs.microsoft.com/typescript/announcing-typescript-4-1/#template-literal-types

**Comment by jankoritak** [comment]
@sami616 did you manage to work around this?

I wonder whether this can resolved by feeding Webpack a custom babel config, that includes `@babel/preset-typescript` via `webpackFinal`.

**Comment by codecaaron** [comment]
You can work around this by resolving a different `babel-loader` with webpackFinal

Add `babel-loader` >=8.2.0 (https://github.com/babel/babel-loader/commit/989103c6d5fd644574f8590f8dbaa42adb833f82)

```tsx
webpackFinal: (config) => {
   config.module.rules.find(({ test }) =>
        test.test('example.tsx')
      ).use[0].loader = require.resolve('babel-loader');

  return config;
}
```

If you are not using your own babel config you'll also need to resolve `@babel/preset-typescript` via the webpack or babel  config function.

**Comment by shilman** [comment]
@phated is this something we can upgrade on the storybook side? ☝️

**Comment by logitimate** [comment]
Really would love to see the storybook side fix this for sure.

**Comment by ndelangen** [comment]
This should work in the 7.0 beta release.
