### ISSUE TITLE
MDX docs are blank

### ISSUE THREAD

**Issue by Floffah** [storybookjs/storybook#13321]
**Describe the bug**
When writing an MDX story, the docs tab is completely blank.

**To Reproduce**

use this mdx file: [TextInput.stories.mdx](https://gist.github.com/Floffah/145cad2c75689210d5f885eb333c025b#file-textinput-stories-m-d-x) (filename changes in gist because github's formatting broke)

this is the component: [TextInput.tsx](https://gist.github.com/Floffah/145cad2c75689210d5f885eb333c025b#file-textinput-tsx)

these are my storybook configs: [.storybook/main.js](https://gist.github.com/Floffah/145cad2c75689210d5f885eb333c025b#file-storybook-main-js) [.storybook/manager.js](https://gist.github.com/Floffah/145cad2c75689210d5f885eb333c025b#file-storybook-manager-js) [.storybook/preview.js](https://gist.github.com/Floffah/145cad2c75689210d5f885eb333c025b#file-storybook-preview-js)

**Expected behavior**
The mdx story renders into a proper story with a docs page

**Screenshots**
![image](https://user-images.githubusercontent.com/27270386/100473794-0f6f8200-30d7-11eb-8624-b5bb45ce368f.png)

**Code snippets**
were linked in the reproduce part

[here is the full gist](https://gist.github.com/Floffah/145cad2c75689210d5f885eb333c025b)

**System**
```
Environment Info:

  System:
    OS: Windows 10 10.0.19041
    CPU: (16) x64 AMD Ryzen 7 1700X Eight-Core Processor
  Binaries:
    Node: 15.3.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.0.14 - C:\Program Files\nodejs\npm.CMD
    nvm: 1.1.7 - C:\Users\**\AppData\Roaming\nvm\nvm.EXE
  Browsers:
    Chrome: 87.0.4280.66
    Edge: Spartan (44.19041.423.0), Chromium (87.0.664.47)
```

**Additional context**
happened since storybook 6.1.7 but that was when i started trying to use mdx stories. i am using 6.1.8

If really needed i could temporarily add someone as a collaborator in the repo but it is private

**Comment by Floffah** [comment]
ive found that when building it with build-storybook it doesnt render it at all its just the default docs it just looks like this 
![image](https://user-images.githubusercontent.com/27270386/100474724-32029a80-30d9-11eb-8af2-eb588153cc5d.png)

**Comment by Floffah** [comment]
turns out i just cant read docs apparently \:)

**Comment by paschalidi** [comment]
You saved my life @Floffah !
