### ISSUE TITLE
[Vue] Documentation for Full custom Controls with Vue.js example

### ISSUE THREAD

**Issue by mayashavin** [storybookjs/storybook#13334]
**Is your feature request related to a problem? Please describe**
There is no fully custom args controls documentation for Vue.js - https://storybook.js.org/docs/vue/essentials/controls. It appears with React as default instead.

**Describe the solution you'd like**
Add documentation snippet for Vue.js example in "Fully custom args"
https://storybook.js.org/docs/vue/essentials/controls#fully-custom-args

**Are you able to assist to bring the feature to reality?**
yes, I can make a PR

**Additional context**
N/A

**Comment by shilman** [comment]
hey @mayashavin, thanks for offering to help. we're relying on community contributions to fill out the\ examples for all the different frameworks. contributions are greatly appreciated!

**Comment by jonniebigodes** [comment]
@mayashavin i just pushed a pull request with the missing vue code snippets. Take a look and feel free to provide any feedback. 

Stay safe

**Comment by jonniebigodes** [comment]
Closing this as the snippets were merged. @mayashavin let me know of any issues you run into the snippets.

Stay safe
