### ISSUE TITLE
Storyshot tests give failed prop type warnings when a required prop is an automatically matched action

### ISSUE THREAD

**Issue by uoa-noel** [storybookjs/storybook#13335]
**Describe the bug**
Hi! Thanks for your work on Storybook, it's been a pleasure to use.

Since Storybook 6, actions are [annotated or automatically matched](https://storybook.js.org/docs/react/essentials/actions#automatically-matching-args) with props based on the prop name. This means we don't need to create actions and explicitly pass them as props to components like `<Component onClick={action("Clicked")} />` anymore.

However, when Storyshot snapshot tests are run, `Warning: Failed prop type` would sometimes be printed out. After investigating, I found the warnings are for function props which are marked as `isRequired` in the component's propTypes, but for which actions are automatically generated.

I created [a repo](https://github.com/uoa-noel/storybook-proptypes-warn) to reproduce the bug. I simply generated the project using `create-react-app`, set up Storybook and Storyshots snapshot testing without changing any code, and prop-type warnings appeared when I ran `yarn test`.

This suggests the snapshot tests are rendering components without passing in automatically generated action functions, and there seems no user-accessible ways to fix the issue. Test results are not affected by the warnings so they can still pass, however it doesn't seem like it should be happening.

**To Reproduce**

1. Clone my reproduction repo: https://github.com/uoa-noel/storybook-proptypes-warn
2. Run `yarn`
3. Run `yarn test`

**Expected behavior**
The tests should pass without any warning output.

**Example output**
```
$ yarn test
...
  console.error
    Warning: Failed prop type: The prop `onLogin` is marked as required in `Header`, but its value is `undefined`.
        at Header (/home/.../storybook-proptypes-warn/src/stories/Header.js:7:26)
        at storyFn

       8 | };
       9 | 
    > 10 | const Template = (args) => <Header {...args} />;
         |                            ^
      11 | 
      12 | export const LoggedIn = Template.bind({});
      13 | LoggedIn.args = {

      at printWarning (node_modules/react/cjs/react-jsx-dev-runtime.development.js:117:30)
      at error (node_modules/react/cjs/react-jsx-dev-runtime.development.js:93:5)
      at checkPropTypes (node_modules/react/cjs/react-jsx-dev-runtime.development.js:620:11)
      at validatePropTypes (node_modules/react/cjs/react-jsx-dev-runtime.development.js:1072:7)
      at jsxWithValidation (node_modules/react/cjs/react-jsx-dev-runtime.development.js:1192:7)
      at Object.Template (src/stories/Header.stories.js:10:28)
      at finalStoryFn (node_modules/@storybook/client-api/dist/story_store.js:632:32)
```

**System**
package.json:
```
  "devDependencies": {
    "@storybook/addon-actions": "^6.1.9",
    "@storybook/addon-essentials": "^6.1.9",
    "@storybook/addon-links": "^6.1.9",
    "@storybook/addon-storyshots": "^6.1.9",
    "@storybook/node-logger": "^6.1.9",
    "@storybook/preset-create-react-app": "^3.1.5",
    "@storybook/react": "^6.1.9"
```

Environment Info:

  System:
    OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  Binaries:
    Node: 14.15.1 - /usr/bin/node
    Yarn: 1.12.3 - /usr/bin/yarn
    npm: 6.14.8 - /usr/bin/npm
  Browsers:
    Chrome: 87.0.4280.66
    Firefox: 83.0

**Comment by Varedis** [comment]
Issues still happens in the latest version of storybook (v6.1.21) when using storyshots and automatic matched args for actions

**Comment by cderche** [comment]
Hello - is there any movement on this? Thanks!

**Comment by hutchy2570** [comment]
We see this on Storybook 6.2.8.

**Comment by moeyashi** [comment]
This is a known caveat.

> ### Testing stories that rely on addon-added decorators
> 
> If you have stories in your Storybook that can only render inside a decorator (for instance the [`apollo-storybook-decorator`](https://github.com/abhiaiyer91/apollo-storybook-decorator)), you'll need to ensure those decorators are applied in Storyshots.
> 
> If you export those decorators from your `.storybook/preview.js` then Storyshots will apply those decorators for you in the same way that Storybook does. However if the addon _automatically_ adds the decorator for you (which is a new feature in Storybook 6.0), you will find the decorator does not get added in Storyshots. This is a limitation in Storyshots currently.
> 
> To ensure such decorators get added, export them from `.storybook/preview.js`:
> 
> ```js
> import addonDecorator from 'some-addon';
> 
> export const decorators = [addonDecorator];
> ```

https://github.com/storybookjs/storybook/tree/next/code/addons/storyshots/storyshots-core#testing-stories-that-rely-on-addon-added-decorators

**Comment by ndelangen** [comment]
The future of storyshots is the test-runner:
https://storybook.js.org/docs/react/writing-tests/test-runner#page-top

And use the play function for expectations:
https://storybook.js.org/docs/react/writing-stories/play-function#page-top

We will not be making any improvement / changes to storyshots.
