### ISSUE TITLE
Running or building Storybook fails when a absolute static path is passed.

### ISSUE THREAD

**Issue by Remcoman** [storybookjs/storybook#13336]
**Describe the bug**
I get reports that the build fails on Windows with the following error:
"no such directory to load static files"

If i look at the path that is logged in the terminal than it's clear what the issue is: the drive letter is at the end of the path.

This can be traced back to the following line:
https://github.com/storybookjs/storybook/blob/next/lib/core/src/server/build-static.ts#L106

This code seems to do some magic related to 

**To Reproduce**
Use windows to run or build Storybook. Pass a absolute path (with drive letter) as the static dir option

**Expected behavior**
It should run or build Storybook successfully

**Screenshots**
No need

**Code snippets**
npm run storybook -s C:\Some folder

**System**
N.a. the cause of the error is clear and can be traced back to the line that i reported earlier.

**Comment by ghengeveld** [comment]
Right, this is a Windows compatibility issue. Currently you can set something like `-s foo:bar` to have a directory named `foo` get exposed at `http://localhost:{port}/bar`. Clearly this feature never considered the fact that Windows uses `:` in its disk volume designator (e.g. `C:\`).

**Comment by shilman** [comment]
Crikey!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.0-alpha.5 containing PR #13344 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
