### ISSUE TITLE
Storybook Addon Docs with React 17 gives many peer dependency warnings

### ISSUE THREAD

**Issue by stu039** [storybookjs/storybook#13340]
Using react 17 with storybook addon docs v6.1.0 is giving me the following wall of peer dependency warnings 
<img width="1269" alt="Screenshot 2020-11-30 at 13 41 56" src="https://user-images.githubusercontent.com/48241332/100617171-0ae2dd80-3312-11eb-8cc9-1a487014b417.png">

Is anyone able to give an update on whether this is being looked into? This is non-breaking for me, and I understand that 3rd party packages might not have releases to remove such warnings, but this is creating a lot of noise for my project.

Any insight would be much appreciated!

**Comment by shilman** [comment]
@stu039 The problem here is that Storybook depends on external libraries who have not yet upgraded their peer dependencies to be React 17 compatible. When those libraries get updated, we'll also upgrade Storybook's dependencies.
