### ISSUE TITLE
Unable to run SASS Correctly in Vue SFC Storybook Project

### ISSUE THREAD

**Issue by EricMcWinNer** [storybookjs/storybook#13349]
**Describe the bug**
When I run my code, it spits an error saying the SASS in my code is incorrect and proceeds to suggest CSS syntax for me.
Running something like this throws an error:

```
<template>
  <div :style="cssVars" class="switch">
    <label>
      {{ label }}
      <input :checked="checked" @change="changed" v-bind="$attrs" type="checkbox" />
      <span class="slide"></span>
    </label>
  </div>
</template>

<script>
export default {
  name: "switch",
  inheritAttrs: false,
  model: {
    prop: "checked",
    event: "change",
  },
  computed: {
    cssVars: function() {
      return {
        "--backgroundcolor": this.backgroundColor,
        "--thumbbackground": this.thumbBackground,
      };
    },
  },
  methods: {
    changed: function(e) {
      this.$emit('change', e.target.checked)
    }
  },
  props: {
    label: {
      type: String,
    },
    backgroundColor: {
      type: String,
      default: "#00B46F",
    },
    thumbBackground: {
      type: String,
      default: "radial-gradient(#fff, #fcfcfc)",
    },
    checked: {
      type: Boolean,
      default: false
    }
  },
};
</script>
<style lang="sass" scoped>
@import forms
@import switch
</style>

```

Gives the following error:

> Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
> SassError: @import directive requires a url or quoted path
>         on line 52 of C:\Projects\hybrids\ui-kit-complete\kits\vue\src\forms\swys-switch.vue
> >> @import forms

In order to get it to work, I'll have to surround the import statements with quotes and put a semi-colon behind the first import statement. But even though it works, that's not SASS. 

**To Reproduce**
I'm running the code from a Windows 10 64 bit PC. I'm using the default Storybook configuration after running `npm sb init` in my project directory in a Vue 2 project created with the Vue CLI. 

I initially had issues running it with SASS and I had to edit the webpack config. Here's what the webpack.config.js file in the .storybook folder looks like:

```
module.exports = ({ config }) => {
  config.module.rules.push({
    test: /\.sass$/,
    use: [
      require.resolve("style-loader"),
      require.resolve("css-loader"),
      require.resolve("sass-loader"),
    ],
  });

  return config;
};

```

**Expected behavior**
It's supposed to compile my SASS code. The only way I got it to work is to export all my SASS code to external files and import them in my scoped components using SCSS syntax, running the same code in production or with `npm run serve` throws an error which kind of defeats the purpose of documenting with Storybook.

**Screenshots**
Here's the error I get on running the code snippet above:
![Screenshot (47)](https://user-images.githubusercontent.com/19782345/100729256-cfefb100-33c8-11eb-8525-7859171b8e90.png)

This is the only way it compiles, but I'm sure that isn't SASS:
![Screenshot (48)](https://user-images.githubusercontent.com/19782345/100729457-13e2b600-33c9-11eb-872b-a5d3c5b27a68.png)

**System**
Please paste the results of `npx sb@next info` here.
Error: EPERM: operation not permitted, mkdir 'C:\Users\RiL~1\AppData\Roaming\npm-cache\_npx\19256'
command not found: sb

**Comment by EricMcWinNer** [comment]
Hey guys, I was able to solve the issue. For anybody else who may face this, the issue was from the webpack config. 

In order to get this to work properly with Vue and with SASS, the `webpack.config.js` file in the `.storybook` folder has to look something like this:

```
module.exports = ({ config }) => {
  config.module.rules.push({
    test: /\.sass$/,
    use: [
      require.resolve("vue-style-loader"),
      require.resolve("css-loader"),
      {
        loader: require.resolve("sass-loader"),
        options: {
          sassOptions: {
            indentedSyntax: true
          }
        }
      }
    ],
  });

  return config;
};
```

If you're doing SCSS, then it'd look something like this:

```
module.exports = ({ config }) => {
  config.module.rules.push({
    test: /\.scss$/,
    use: [
      require.resolve("vue-style-loader"),
      require.resolve("css-loader"),
      require.resolve("sass-loader"),
    ],
  });

  return config;
};
```

I was able to figure it out after looking at the [Vue Loader docs](https://vue-loader.vuejs.org/guide/pre-processors.html#sass)

**Comment by Fonteyn94** [comment]
thanks, this is very helpful!
Im using storybook(webpack 5) with Vue 3 components
for a long time I could not figure out how to implement SASS styles, but your advice is working

**Comment by sschneider-ihre-pvs** [comment]
You can also go ahead and use the addon styling
```
{
      name: '@storybook/addon-styling',
      options: {
        sass: {
          implementation: require("sass"),
          indentedSyntax: true,
        },
      },
    },
```
