### ISSUE TITLE
@emotion/core upgrade along with React 17 throws error

### ISSUE THREAD

**Issue by RadhikaJayesh** [storybookjs/storybook#13353]
I recently upgraded Storybook to 6.1.7, React - 17, @emotion/core -  11.0.0, @emotion/react -  11.1.1. I have updated the import like this **`import { jsx } from '@emotion/react'`** in all files. But Storybook is not reflected with the change.
It shows the following error .

![storybookerr](https://user-images.githubusercontent.com/5345747/100764226-671f2d80-33f6-11eb-9d2a-0ff79e829814.png)

**Comment by RadhikaJayesh** [comment]
Hello, Any update on this?

**Comment by michaeljaltamirano** [comment]
@RadhikaJayesh I'm pretty sure Storybook still relies on `@emotion/core^10` so there's a compatibility issue.

**Comment by musab** [comment]
@michaeljaltamirano 
> @RadhikaJayesh I'm pretty sure Storybook still relies on `@emotion/core^10` so there's a compatibility issue.

Does that mean we must wait for Storybook to first upgrade to emotion 11 before upgrading our own apps to emotion 11?

**Comment by michaeljaltamirano** [comment]
> Does that mean we must wait for Storybook to first upgrade to emotion 11 before upgrading our own apps to emotion 11?

Hi @musab, these two issue threads might be helpful:

1. `webpack` config changes: https://github.com/storybookjs/storybook/issues/13145
    - You can see an example commit here: https://github.com/curology/radiance-ui/commit/db37ca22fe53beeaac7213a490e257ce067b9869#diff-2d9ab5214985b9a608b4cd47ed561a301cfd4c7d5352c7a94ee046d4e1f1af10
1. (If you are using TypeScript): https://github.com/emotion-js/emotion/issues/2320#issuecomment-813588758

**Comment by ndelangen** [comment]
This is fixed in storybook 7.0 beta.
