### ISSUE TITLE
Theming. manager.js and themes are seem to be cashing somewhere

### ISSUE THREAD

**Issue by Kirill486** [storybookjs/storybook#13357]
**Describe the bug**
While creating a new theme for ```storybook```, the changes didn't apply to my theme until I manually delete and then reinstall the ```storybook``` package. I also did try the cash clear and hard reset in the browser.

It seems for me that they may are cashed somewhere.

**To Reproduce**

1. [Create a new theme and register in the manager.js](https://storybook.js.org/docs/react/configure/theming)
2. Run storybook to preview changes (changes should apply)
3. Stop storybook
4. Change your theme
5. Start storybook to preview again (no changes in the theme at all)
6. Try hard reset and cash clear in your browser

**Expected behavior**
When the storybook is in the watch mode, I would expect the theme changes to be reflected on the fly the same way changes in stories are reflected.

**System**

System:
    OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz
  Binaries:
    Node: 12.19.0 - ~/.nvm/versions/node/v12.19.0/bin/node
    npm: 6.14.8 - ~/.nvm/versions/node/v12.19.0/bin/npm
  Browsers:
    Chrome: 86.0.4240.75
    Firefox: 83.0

**Comment by shilman** [comment]
You probably shouldn't put `--no-manager-cache` in your `package.json`. Building the manager takes up to 10s and you'll lose that benefit until you remember to remove that flag. I'd run it by hand instead and only when you modify the theme.

This is a duplicate to #13200 which we'll hopefully fix soon.
