### ISSUE TITLE
In the current docs for writing decorators <Story /> will remount story for every change!

### ISSUE THREAD

**Issue by ckwong90** [storybookjs/storybook#13356]
**Describe the bug**
In the docs
https://storybook.js.org/docs/react/writing-stories/decorators
decorators are being advised to be written using `<Story />`
```
decorators: [(Story) => <div style={{ margin: '3em' }}><Story/></div>]
```
However this will REMOUNT your entire story every time, canceling any HMR and react-fast-refresh.  This includes making any changes using the Controls addon will trigger a full remount of your story instead of re-rendering

As seen in https://github.com/storybookjs/storybook/issues/12255

To change this use `Story()` instead of `<Story />`
```
decorators: [(Story) => <div style={{ margin: '3em' }}>{Story()}</div>]
```
Please ether update the docs:
https://storybook.js.org/docs/react/writing-stories/decorators
or patch the decorators such that `<Story />` doesn't trigger a full remount

**To Reproduce**

1) create the default react storybook template
2) add `Story => <Story />` in decorators
3) add `useEffect(() => console.log("REMOUNT"), [])` into the story
4) observe mounting behaviour
5) retry with `Story => Story()`

**Comment by Javimtib92** [comment]
Totally right, I was experiencing this behaviour and I didn't know what was causing the issue, I came up to this thread and applied the suggested fix and now it is working. I think this should be fixed or documented

**Comment by shilman** [comment]
cc @jonniebigodes @tmeasday

**Comment by tmeasday** [comment]
Let's do both (document for now, fix if possible)
