### ISSUE TITLE
argsType should be optionnal for MetaComponent.

### ISSUE THREAD

**Issue by Exalyon** [storybookjs/storybook#13350]
**Describe the bug**
The prop argsType seem mandatory for the Meta component. This is a warning from the MDX plugin in a Jetbrains product.

**To Reproduce**

1. Create a MDX file
2. Insert a Meta component

**Expected behavior**
The warning should not occur

**System**
yarn list v1.22.10
├─ @storybook/addon-actions@6.1.6
├─ @storybook/addon-backgrounds@6.1.6
├─ @storybook/addon-docs@6.1.6
├─ @storybook/addon-knobs@6.1.6
├─ @storybook/addon-links@6.1.6
├─ @storybook/addons@6.1.6
├─ @storybook/api@6.1.6
├─ @storybook/channel-postmessage@6.1.6
├─ @storybook/channels@6.1.6
├─ @storybook/client-api@6.1.6
├─ @storybook/client-logger@6.1.6
├─ @storybook/components@6.1.6
├─ @storybook/core-events@6.1.6
├─ @storybook/core@6.1.6
├─ @storybook/csf@0.0.1
├─ @storybook/node-logger@6.1.6
├─ @storybook/postinstall@6.1.6
├─ @storybook/preset-create-react-app@3.1.5
├─ @storybook/react@6.1.6
├─ @storybook/router@6.1.6
├─ @storybook/semver@7.3.2
├─ @storybook/source-loader@6.1.6
├─ @storybook/theming@6.1.6
├─ @storybook/ui@6.1.6
├─ storybook-addon-intl@2.4.1
├─ storybook-addon-paddings@3.0.0
└─ storybook-react-router@1.0.8

**Additional context**
I think it comes from the `MetaProps` interface in the `Meta.d.ts`. There it misses the `?` before the `:` on the argsType property to make it optionnal.

**Comment by shilman** [comment]
Whoopee!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.0-alpha.1 containing PR #13352 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Olé!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.10 containing PR #13352 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```
