### ISSUE TITLE
Proposition: show errors instead of warnings when story falls during its initialization before it has registered itself

### ISSUE THREAD

**Issue by faiwer** [storybookjs/storybook#13366]
It's not actually a bug, but I think am not the only one who was faced with this problem. I've spent many hours on debugging, but finally I found where the problem was. I hope my experience will help other people. 

### Bug or support request summary

I was faced with the next problem:
- client-side manager app knows about all possible stories files (e.g. list of `*.stories.tsx` files) 
- it `require`-s them one by one
- it's supposed that they should be registered
- but when some of them fails during their initialization it doesn't show any error
- instead it shows a warning (`_client.logger.warn`)
- many developers hide "warnings" by default, because typically it's too verbose information

So when some story fails:
- the developer doesn't see an error in the browser console
- he also doesn't see any error in the terminal
- the only thing that he sees - there's 1 less story in the stories tree

It may be too sophisticated to figure out that there's a problem and how to solve it. I got into such a situation. It looks like everything is perfect, but you know that should be another one story. And you don't know where to dig to find a problem.

### Steps to reproduce

In my case it was the next problem:
- I use a custom webpack config
- One of my stories `import`s a file that throws an error (bug in my app)
- So the story fails with an error right after the storybook code `require`s it
- StoryBook client code ignores the story and doesn't show any error
- But it shows a warning

![Selection_254](https://user-images.githubusercontent.com/744114/101068355-e9dfee00-3598-11eb-8482-f509e3767b98.png)

On the client side there's this code ^. It caught the error. The error contains everything the developer needs to know about the problem and to solve it. But it may be hidden from him because the storybook preview app handles it like it's a warning.

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react 6.1.9

### Work summary

I think there're at least two possible improvements:
- replace `warn` with `error`
- or just make in configurable

In my humble opinion `error` is much better, because those errors are almost ever fatal or the like. But I may not know something important... 

Also may be it's not a bad idea to write something about possible important warnings in the documention in a chapter like "troubleshooting". I tried to google how to troubleshoot storyview but wasn't succced in it.

**Comment by ghengeveld** [comment]
I'm confused. Is this a Storybook warning that you'd like to yield an error? Or just client-side log warnings in general?

**Comment by faiwer** [comment]
Hm. It's an interesting question. I made a better look at the error and... It looks like it's a runtime error on the client-side that occurs during the story initialization process (before the story has registered itself). I will try tomorrow to make some simple example or to narrow the case. 

BTW I'll change the issue's description, because not I figured out that it isn't related to build process, it's in runtime. So the build is done

**Comment by faiwer** [comment]
I have updated the issue's text. I hope it's a bit more clear now. I will prepare more information about it tomorrow after a small investigation.

**Comment by faiwer** [comment]
I reproduced the mini example: https://github.com/faiwer/storybook-13366

It's pretty simple. There're only 2 story-files:
- `./src/a.stories.tsx`
- `./src/b.stories.tsx`

Each of them has one story inside. But the 2nd file (`b`) has an `import './error'` line. This `error.tsx` throws an error. I just immitated my real situation as simple as I could. Of course in the real world code there will be something more complicated than just `throw new Error`.

What do we have in result?

1. UI doesn't have `b` story:
![image](https://user-images.githubusercontent.com/744114/101147162-4a643f00-361c-11eb-9438-f9bd80c46c92.png)

2. Terminal doesn't show any error:
![Selection_257](https://user-images.githubusercontent.com/744114/101147223-623bc300-361c-11eb-86f4-540432fb7bfc.png)

3. Chrome doesn't show any error:
![Selection_259](https://user-images.githubusercontent.com/744114/101147404-9ca56000-361c-11eb-895f-8685d02f2af8.png)

But there's a problem. The story is not shown. And there's no information about what was wrong with it. Hm... 

But actually It is there:
![Selection_260](https://user-images.githubusercontent.com/744114/101147476-b5ae1100-361c-11eb-8ca8-fa8c389ff4ef.png)

Why does it happen? Why does it show a warning instead of an error? Because of this code:
![image](https://user-images.githubusercontent.com/744114/101147549-d1191c00-361c-11eb-9ed1-5253e5ca8992.png)

As you can see it deliberately shows a warning. Not an error. 

Ok. But you may ask - what's the problem? Warning is shown? Hm... I think there're many developers who hides warnings in the applications because there're too many irrelevant information:
- about obsolete libraries (which we can't update or replace right now)
- new cookies policy that is violated by web-counters
- Firefox shows a ton of non-important stuff
- Sometimes CSP violations
- and many other things that may be okay during development process

And the problem is - when you don't know that the error is in "warnings" section - you don't have a clue how to debug this issue :)

So my proposition is: just replace `.warn` with `.error`, at least because it's an error :)

**Comment by MickL** [comment]
Please dont close unresolved issues

**Comment by besimhu** [comment]
@faiwer  did you have any luck with your issue?

I recently ran into something exactly the same, except I get the issues with all files. Any file that has errors will throw the errors in the browser console but not during watch mode. 

The strange part is that when I start up storybook, it will fail to start because of the errors.

**Comment by faiwer** [comment]
@besimhu no, I didn't do anything with it. I just took it into consideration that sometimes I need to manually check for console warnings.

**Comment by shilman** [comment]
I believe this has been fixed in 6.4

```
npx sb@next upgrade --prerelease
```

Can you verify?

**Comment by besimhu** [comment]
@shilman  Right after I made my reply, I also upgraded to the latest beta version `6.4.0-beta.29`. No luck. 

If it matters, I am using the webpack 5 version

**Comment by shilman** [comment]
@tmeasday can you please take a look? pretty sure this is a dupe to the issue you just fixed

**Comment by tmeasday** [comment]
@shilman OK, so this is an artifact of the way we load all the files in the v6 store:

https://github.com/storybooks/storybook/blob/68b3ef639c044facf48eba759750e16315ae2a20/lib/core-client/src/preview/executeLoadable.ts#L25-L35

We load *all* the CSF upfront (of course) and simply warn if any fail to parse. This is code that was duplicated from the way we did it in 6.3:

https://github.com/storybookjs/storybook/blob/7b44fa21f5724f3474e64c1779099b8e14bf1b3b/lib/core-client/src/preview/loadCsf.ts#L51

So, my question is what should we do? We could:

1) Simply `console.error()` rather than `console.warn()`, which I guess would help, but wouldn't mirror the v7 store where such errors would appear in a redbox (but only when you visited the story, rather than on bootup).

2) Rethrow from within that `catch` block, which would result in the whole SB failing to load on an error in a single CSF file.

WDYT @shilman?

**Comment by shilman** [comment]
@tmeasday ideally we could:
- redbox it
- clear the redbox when the user fixes the code

If that's not possible, I think we should just recommend people upgrade to the v7 store, since fixing it in v6 will probably cause a lot of breakages and frustration. WDYT?

**Comment by tmeasday** [comment]
@shilman I think we could do that, the only thing that gives me pause is the (potentially frustrating) difference in behaviour to 6.3: 

 - In 6.3 if you had one broken CSF file, you could continue to use your SB, as the stories from that file would just not show up at all
 - In 6.4 you would have to fix that file before using the SB.

Of course, having stories "silently" disappear has caused  a lot of headaches before so I'd be inclined to be aggressive here.

**Comment by shilman** [comment]
@tmeasday The more I think about it, the more I think we're better off getting people to upgrade to the on-demand store and focusing most of our effort there

**Comment by shilman** [comment]
Yay!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-beta.30 containing PR #16632 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
