### ISSUE TITLE
[5.0.10] When clicking back and forth between substories with the same knobs, incorrect defaults are applied

### ISSUE THREAD

**Issue by Corinos** [storybookjs/storybook#13367]
**Describe the bug**
I have a story that has 2 sub stories.  Each sub story has the same set of knobs. When I click from the first sub story to the second, and back to the first, the defaults from the second sub story are applied to the first.

**To Reproduce**

Click the first sub story
Check the default knob settings
Click the second sub story
Check the default knob settings
Click the first sub story again
Check the default knob settings

**Expected behavior**
The original first sub story's knob settings should still be in tact.

**System**
Environment Info:

  System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 10.19.0 - ~/.nvm/versions/node/v10.19.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v10.19.0/bin/npm
  Browsers:
    Chrome: 87.0.4280.88
    Edge: 87.0.664.47
    Firefox: 83.0
    Safari: 14.0

**Comment by shilman** [comment]
FYI, we’ve released `addon-controls` in Storybook 6.0. Controls are portable, auto-generated knobs that are intended to replace `addon-knobs` long term.

- [Controls documentation](https://storybook.js.org/docs/react/essentials/controls)
- [Migration instructions](https://github.com/storybookjs/storybook/blob/next/addons/controls/README.md#how-do-i-migrate-from-addon-knobs)

Please upgrade and try them out today!

**Comment by Corinos** [comment]
Is this a known issue with v5?

**Comment by Corinos** [comment]
I was able to resolve my issue by re-ordering my stories, and I think it was actually an issue with the stories themselves.  This can be withdrawn. Thanks for your time.
