### ISSUE TITLE
In propTypes, it is shown in the form of variables, while in Controls, it is a string.

### ISSUE THREAD

**Issue by sweet-works** [storybookjs/storybook#13363]
Name | Description | Default | Control
-- | -- | -- | --
component | string | 'span' | -
color | string | Color.Text.base | -
size | number | Font.Size.base | -
lineHeight | number | Font.LineHeight.md | -
weight | stringnumber | 'normal' | -

I want to know how to solve such a problem.In propTypes, it is shown in the form of variables, while in Controls, it is a string.

**Comment by shilman** [comment]
Do you have a repro repo you can share?

**Comment by penx** [comment]
I think this is fixed by @17102
