### ISSUE TITLE
Getting a yellow story icon

### ISSUE THREAD

**Issue by raphaellueckl** [storybookjs/storybook#13364]
I farmed the docs, but I don't find infos on this, just screenshots and gifs. How can I achieve such a yellow story icon?

![image](https://user-images.githubusercontent.com/8248662/101016546-3ca1b180-3569-11eb-9844-84788bf4be46.png)

**Comment by shilman** [comment]
That's documentation-only MDX: https://storybook.js.org/docs/react/writing-docs/mdx#documentation-only-mdx
