### ISSUE TITLE
Storybook not launching in Chrome

### ISSUE THREAD

**Issue by perqa** [storybookjs/storybook#13377]
Storybook builds without errors, starts launching in a browser, and then hangs with the error quoted below.

Combo 1:
- Storybook - ^6.0.28
- Chrome - Version 86.0.4240.193

Combo 2:
- @storybook/react v6.0.16
- Chrome for Mac Version 87.0.4280.67 (Official Build) (x86_64)

Error log in Chrome:
```
Uncaught TypeError: Cannot read property '2' of undefined
    at new ShiftedDate (<anonymous>:48:42)
    at new Date (vendors~main.39af3481098ad3d1e989.bundle.js:117388)
    at Object.<anonymous> (vendors~main.39af3481098ad3d1e989.bundle.js:121814)
    at vendors~main.39af3481098ad3d1e989.bundle.js:118044
    at Object.<anonymous> (vendors~main.39af3481098ad3d1e989.bundle.js:118048)
    at Object../node_modules/es6-shim/es6-shim.js (vendors~main.39af3481098ad3d1e989.bundle.js:121911)
    at __webpack_require__ (runtime~main.39af3481098ad3d1e989.bundle.js:849)
    at fn (runtime~main.39af3481098ad3d1e989.bundle.js:151)
    at Object../node_modules/airbnb-js-shims/target/es2015.js (vendors~main.39af3481098ad3d1e989.bundle.js:43725)
    at __webpack_require__ (runtime~main.39af3481098ad3d1e989.bundle.js:849)
```

Firefox and Safari working as expected.

_Originally posted by @rnanania in https://github.com/storybookjs/storybook/issues/400#issuecomment-724930902_

**Comment by shilman** [comment]
@ndelangen can you confirm that we're still using the same shims from the original issue?

**Comment by moltar** [comment]
Having the same issue

**Comment by ndelangen** [comment]
Could you provide a reproduction @moltar ?

**Comment by JavierMartinz** [comment]
I'm also having this very same issue

```json
    "@storybook/addon-actions": "^6.2.9",
    "@storybook/addon-essentials": "^6.2.9",
    "@storybook/addon-knobs": "^6.2.9",
    "@storybook/addon-links": "^6.2.9",
    "@storybook/addon-postcss": "^2.0.0",
    "@storybook/addon-viewport": "^6.2.9",
    "@storybook/addons": "^6.2.9",
    "@storybook/react": "^6.2.9",
    "@storybook/storybook-deployer": "^2.8.8",
    "@storybook/theming": "^6.2.9",
```

**Comment by kirakishin** [comment]
i have the same issue.
```json
    "@storybook/addon-a11y": "^6.2.9",
    "@storybook/addon-actions": "^6.2.9",
    "@storybook/addon-backgrounds": "^6.2.9",
    "@storybook/addon-console": "^1.2.3",
    "@storybook/addon-controls": "^6.2.9",
    "@storybook/addon-docs": "^6.2.9",
    "@storybook/addon-essentials": "^6.2.9",
    "@storybook/addon-links": "^6.2.9",
    "@storybook/addon-notes": "^5.3.21",
    "@storybook/addon-viewport": "^6.2.9",
    "@storybook/theming": "^6.2.9",
    "@storybook/web-components": "^6.2.9",
```

it seems that using the incognito windows, it works. i don't know why

**Comment by moltar** [comment]
huh ya @kirakishin same here!! so weird

**Comment by moltar** [comment]
Also works fine in Firefox (non private window).

**Comment by ndelangen** [comment]
I suspect you might have some service-worker installed on the same port from some other application?

**Comment by phong-lam** [comment]
I am having the same issue here. Could anyone provide a reason or workaround (outside of using Safari)

**Comment by ndelangen** [comment]
Does a private tab work in Chrome?
Have you tried clearing all application data?

<img width="725" alt="Screenshot 2021-07-02 at 11 54 20" src="https://user-images.githubusercontent.com/3070389/124257062-45248f80-db2c-11eb-9ea3-9d2f1dba0039.png">

**Comment by codewithpassion** [comment]
Same issue. 

I tried the `Clear site data` with no success. 
`Hard reload` and `Empty cache and hard reload` don't help either. 
If I'm opening a incognito window, it loads. Same when I load the page in the same Chrome version with a different profile.

**Comment by phong-lam** [comment]
Hello, can we please resurface this issue. I am still experiencing this issue after updating to all latest versions of everything storybook related

**Comment by caryuval** [comment]
I had the exact same issue and it turns out I had a Chrome extension I was using for time zones modifications that caused it.
I recommend opening it in incognito mode without extensions and to see if it works correctly.
If it does, just try disabling / removing the extensions 1 by 1 until you get it working.
Good luck!

**Comment by arroiz** [comment]
> I had the exact same issue and it turns out I had a Chrome extension I was using for time zones modifications that caused it.
> I recommend opening it in incognito mode (since normally extensions aren't loaded automatically) without extensions and to see if it works correctly.
> If it does, just try disabling / removing the extensions 1 by 1 until you get it working.
> Good luck!

thanks! I installed a Chrome extension to do some testing and forgot about it. After removing everything worked out

**Comment by shees-usman** [comment]
I can confirm this happens when you have a conflicting extension installed. On my system a timezone modifying extension was enabled in incognito aswell as normal windows. As soon as it got disabled from incognito that worked and on disabling it from the main window it begins working on the main window aswell. Conflicting extensions would be one of the first checks if anyone else hits a similar issue with this working on other browsers but not on chrome with a similar error as stated above.

**Comment by quangChe** [comment]
I just ran into the same issue with a timezone extension as well 😆  Blew my mind. Had no idea that chrome extensions could have such an impact. I'm trying to understand why Storybook's esconfig would throw a type error from a Chrome extension (or at least I think that's what the error came from)?
