### ISSUE TITLE
Select control options error: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by graysonhicks** [storybookjs/storybook#13380]
**Describe the bug**
When trying to use the `select` control, with `options`, an error is thrown saying:

`Uncaught TypeError: Cannot convert undefined or null to object`

Putting in a debugger shows this error coming from the `selectedKey` function inside the `SingleSelect` component.  It also does show that `options` is being received as `undefined`.

I have pasted the broken example next to a working example in the same repo, with no discernible difference to me as to why one works and one does not.

This has happened in several other components using the `select` as well.

**Expected behavior**
Options should be passed through to the `select` control.

**Screenshots**
![image](https://user-images.githubusercontent.com/16200795/101216353-5ae0dd80-364d-11eb-92bf-96213e6b9bb7.png)

Canvas crashes to WSOD.

**Code snippets**
**Non working story**
```javascript
import React from 'react';
import ContentTypeIcon from './content-type-icon';

export default {
  title: 'Components/Content Type Icon',
  component: ContentTypeIcon,
  argTypes: {
    contentType: {
      control: 'select',
      options: {
        Article: 'article',
        Toolkit: 'toolkit',
        Video: 'video',
        Webinar: 'webinar',
        Course: 'course',
        'Risk Assessment': 'risk assessment',
        Seminar: 'seminar',
        'Claims lesson': 'Claims Lesson'
      }
    }
  },
  args: {
    light: false,
    className: '',
    contentType: 'article'
  }
};
const Template = (args) => <ContentTypeIcon {...args} />;

export const Default = Template.bind({});
```

**Working story**
```javascript
import React from 'react';
import { action } from '@storybook/addon-actions';
import Button from './button';

const Template = (args) => <Button {...args} />;

export default {
  title: 'Components/Button',
  component: Button,
  argTypes: {
    arrow: {
      control: 'select',
      options: {
        Button: null,
        'Arrow Left': 'left',
        'Arrow Right': 'right'
      }
    },
    color: {
      control: 'select',
      options: {
        Gray: 'gray',
        'Light Gray': 'lightGray',
        Teal: 'teal',
        White: 'whitePrimary',
        'White Arrow': 'whiteArrow',
        'White Secondary': 'whiteSecondary'
      }
    },
    textStyle: {
      control: 'select',
      options: {
        Default: false,
        Uppercase: 'upper'
      }
    }
  },
  args: {
    onClick: action('clicked'),
    onFocus: action('focused'),
    children: 'Button Text'
  }
};

export const Default = Template.bind({});
export const ArrowButton = Template.bind({});

ArrowButton.args = {
  arrow: 'left'
};
```

**System**
```

Environment Info:

  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  Binaries:
    Node: 14.15.1 - ~/.nvm/versions/node/v14.15.1/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.1/bin/npm
  Browsers:
    Firefox: 72.0.2
    Safari: 14.0.1
  npmPackages:
    @storybook/addon-a11y: ^6.1.10 => 6.1.10
    @storybook/addon-essentials: ^6.1.10 => 6.1.10
    @storybook/addon-knobs: ^6.1.10 => 6.1.10
    @storybook/addon-links: ^6.1.10 => 6.1.10
    @storybook/addon-storyshots: ^6.1.10 => 6.1.10
    @storybook/react: 6.1.10 => 6.1.10
```

**Comment by shilman** [comment]
I don't think any of these are correct and the ones that work are probably working for some other reasons, e.g. they are auto-populated by PropTypes or typescript types. Here's the correct syntax for select:

https://storybook.js.org/docs/react/essentials/controls#fully-custom-args

```
  argTypes: {
    propertyA: {
      control: {
        type: 'select',
        options: [
          'Item One', 
          'Item Two', 
          'Item Three'
        ],
      },
    },
```

**Comment by graysonhicks** [comment]
Hm, that's odd that some are objects, but others are string ,e.g. `control: 'color'`. I guess I didn't realize a select is more 'fully-custom' than the background color.  Yea, the working ones must be because of PropTypes.  Thanks @shilman for clearing that up, I can confirm that fixed it!

**Comment by shilman** [comment]
@graysonhicks `control: 'color'` is shorthand for ` control: { type: 'color' }`
