### ISSUE TITLE
Storybook steps on babel-loader version needed by react-scripts

### ISSUE THREAD

**Issue by AskAlice** [storybookjs/storybook#13395]
**Describe the bug**

**To Reproduce**

```json
"dependencies": {
    "@storybook/react": "^6.1.10",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
}
```

```npm run start```

```
The react-scripts package provided by Create React App requires a dependency:
  "babel-loader": "8.1.0"
```

```npm ls babel-loader```

```
+-- @storybook/react@6.1.10
| `-- @storybook/core@6.1.10
|   `-- babel-loader@8.2.2
`-- react-scripts@4.0.1
  `-- babel-loader@8.1.0
```

**Expected behavior**
babel loader version matches react-scripts v4.0.1

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
Please paste the results of `npx sb@next info` here.

**Additional context**

**Comment by shilman** [comment]
closing as duplicate to #4764
