### ISSUE TITLE
Add documentation for keyboard shortcuts

### ISSUE THREAD

**Issue by ratkosolar** [storybookjs/storybook#13409]
**Is your feature request related to a problem? Please describe**
We use Storybook a lot in my team and sometimes we forget the keyboard shortcuts for toggling the sidemenu/addons panels. Last time we did, it took us 10mins googling to find a way to open the addons panel :D so it would be really handy if there was a page in docs that lists all of the keyboard shortcuts.

**Describe the solution you'd like**
Add a "Keyboard shortcuts" page in the documentation that will be very easy to find using the search box
![Screenshot 2020-12-09 at 09 33 10](https://user-images.githubusercontent.com/6464604/101604709-97238d80-3a01-11eb-8d39-7aae6df618fb.png)

**Are you able to assist to bring the feature to reality?**
yes, I can

**Comment by shilman** [comment]
I agree it's probably worth a mention, at least to say that you can find the keyboard shortcuts in the menu UI:

<img width="700" alt="Cursor_and_Addons___A11y___BaseButton_-_Default_⋅_Storybook" src="https://user-images.githubusercontent.com/488689/101632403-d46b3800-3a60-11eb-9aee-8971f880303b.png">

cc @jonniebigodes

**Comment by jonniebigodes** [comment]
@ratkosolar going to close this issue if you don't mind. A recent pull request was merged that addressed this.

Feel free to re-open regarding any follow up. 

Stay safe
