### ISSUE TITLE
ERR! Error: Cannot find module 'vue/dist/vue.esm.js'

### ISSUE THREAD

**Issue by huangyanmei** [storybookjs/storybook#13405]
**Describe the bug**
S D:\practice\my-components> yarn storybook
yarn run v1.22.10
$ start-storybook -p 6006
info @storybook/vue v6.1.10
info 
info => Using prebuilt manager
info => Loading presets
info => Loading 1 config file in "./.storybook"
info => Loading 7 other files in "./.storybook"
info => Adding stories defined in ".storybook\main.js"
ERR! Error: Cannot find module 'vue/dist/vue.esm.js'
ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
ERR!     at Function.resolve (internal/modules/cjs/helpers.js:32:19)
ERR!     at Object.webpack (D:\practice\my-components\node_modules\@storybook\vue\dist\server\framework-preset-vue.js:42:23)
ERR!     at D:\practice\my-components\node_modules\@storybook\core\dist\server\presets.js:259:28
ERR!  { Error: Cannot find module 'vue/dist/vue.esm.js'
ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
ERR!     at Function.resolve (internal/modules/cjs/helpers.js:32:19)
ERR!     at Object.webpack (D:\practice\my-components\node_modules\@storybook\vue\dist\server\framework-preset-vue.js:42:23)
ERR!     at D:\practice\my-components\node_modules\@storybook\core\dist\server\presets.js:259:28
ERR!   stack:
ERR!    'Error: Cannot find module \'vue/dist/vue.esm.js\'\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)\n    at Function.resolve (internal/modules/cjs/helpers.js:32:19)\n    at Object.webpack (D:\\practice\\my-components\\node_modules\\@storybook\\vue\\dist\\server\\framework-preset-vue.js:42:23)\n    at D:\\practice\\my-components\\node_modules\\@storybook\\core\\dist\\server\\presets.js:259:28',
ERR!   code: 'MODULE_NOT_FOUND' }

**Comment by shilman** [comment]
Looks like a configuration settings. Storybook currently uses CJS not ESM. Do you have a repro repo you can share?

**Comment by frankda** [comment]
> Looks like a configuration settings. Storybook currently uses CJS not ESM. Do you have a repro repo you can share?

@shilman Have same issue here. I am using vue3 created by `@vue/cli 4.5.9`, no errors when I ran  `npx sb init`. Then had this issue when I ran `npm run storybook`

**Comment by shilman** [comment]
Storybook isn't vue3 compatible yet. Closing as duplicate to #10654. ETA in 6.2.

**Comment by daniilgri** [comment]
Any update on this issue?
