### ISSUE TITLE
[Question/Feature] Launch default web browers when starting storybook

### ISSUE THREAD

**Issue by thibaultauvray** [storybookjs/storybook#13402]
**Is your feature request related to a problem? Please describe**
When i launch, the command 

```
start-storybook
```
It fail with 
![image](https://user-images.githubusercontent.com/5720128/101512430-4c5f3280-397b-11eb-95f1-b15cd08c9ea6.png)
Because i don't have Google Chrome installed (and don't want it)

**Describe the solution you'd like**
Choose the default browser that user use.

**Describe alternatives you've considered**
Use the --ci options, but i like to have my browser to start with Firefox it work in previous version (5.3) but not anymore with the 6.1.9

**Are you able to assist to bring the feature to reality?**
no

Maybe i have bad shell configruation or webpack but i dont the solution on doc, sorry

**Comment by shilman** [comment]
See workaround here https://github.com/storybookjs/storybook/issues/12206#issuecomment-679013491

Possible documentation update @jonniebigodes ? Maybe it's fine in an issue...

**Comment by jonniebigodes** [comment]
@shilman i've recently created #13415 and i can adjust it to include the issue mentioned here. I'll adjust accordingly tomorrow and we'll take it from there. Sounds good?
