### ISSUE TITLE
[question] example story for vanilla web component

### ISSUE THREAD

**Issue by reno1979** [storybookjs/storybook#13400]
Could someone please post an example for a story for a vanilla web component?

The current stories are all well documented, but I could not figure out how to create a story for a simpele vanilla web component. The stories are all made for frameworks.

Rendering the web component is no problem. But using args and controls seems difficult.

**Comment by shilman** [comment]
https://github.com/storybookjs/storybook/blob/next/examples/web-components-kitchen-sink/stories/addon-controls.stories.js

@jonniebigodes good documentation candidate

**Comment by reno1979** [comment]
@shilman  Thank you, I'll try it using `html` from the `lit-html` library. I have seen similar examples but because of the use of `lit-html` I did not think it would be compatible with a vanilla web component.

**Comment by reno1979** [comment]
Ok I have created multiple stories, but we use plain and simple vanilla web components, no frameworks at all and it seems storybook does really want to support this. 

Now I have to create all controls, docs etc. While the source of the web component gas complete JSDoc tags. 

Am I missing somethings here? Or is there a better solution?

**Comment by reno1979** [comment]
Small update: using the plugin webpack hooks I am able to prebuild the required files (the webcomponent analyzer and the test bundel). 

Evert the HMR process starts the plugin starts a custom script. More details about the plugin: https://github.com/tienne/webpack-hook-plugin

**Comment by shilman** [comment]
@reno1979 sorry for the slow response. i think this is a good question for @daKmoR who implemented `@storybook/web-components`

**Comment by njsokol** [comment]
Would love to see something like this as we are experiencing the same result with args. Was hoping that @storybook/web-components would be using "vanilla" custom elements without the framework ties of lit.

**Comment by doublejosh** [comment]
`index.stories.js`
```javascript
/* eslint-disable import/extensions */
import './index.js';

export default {
    title: 'Section/Component Name',
    component: 'my-component',
};

const Template = ({ myParam }) => `
  <my-component my-param="${myParam}"></my-component>
`;

export const Default = Template.bind({});
Default.args = {
    myParam: 'My Value',
};
```

**Comment by njsokol** [comment]
Thanks @doublejosh, I noticed that this breaks the docs part of storybook though. It's "show code" looks like:
```
({ myParam }) => `
  <my-component my-param="${myParam}"></my-component>
`;
```

**Comment by shilman** [comment]
> But the actions really throws a wrench into the mix

@njsokol what about the actions?

**Comment by reno1979** [comment]
This would be great! Was thIs possible before? 

I thought I did not have anything drawn in the dom using the stories like this, can not wait to test!

Is it still required tot create a custom elements json file? (Properties, Attributes and CSS variables information)
Thx!

**Comment by reno1979** [comment]
@njsokol  You are correct. The docs part of storybook does not render the component anymore. 

And there are some other issues to overcome. Currently I'm not using the actions, but I am curious what is broken. 

The controls etc only work when I supply a web-components.json, but the process is anything but elegant ... 
There were some experiments: https://github.com/runem/web-component-analyzer/issues/1

We don't use any framework and I would like to keep it that way. :)

**Comment by sidharthramesh** [comment]
Any updates on this? I'm using stenciljs and want to use my components in storybook as just web components. Hot module reloading would be awesome too. I think the @storybook/web-components (@daKmoR) should show examples with customElements too. I am currently doing something like this
```js
import { storiesOf } from '@storybook/html';

storiesOf('Button', module)
  .add('Simple', () => `
    <snazzy-button>
      Button text
    </snazzy-button>
  `)
  .add('Large', () => `
    <snazzy-button size='large'>
      Button text
    </snazzy-button>
  `);
```
And I import the webcomponents and define them in the preview.js file. However, if there's a better method, especially using the Component Story Format I'd like to know.

**Comment by sidharthramesh** [comment]
Referenced from this blog: https://paulcpederson.com/articles/stencil-storybook/

**Comment by shilman** [comment]
we just got some new snippets here: https://github.com/storybookjs/storybook/pull/14163

does it help?

**Comment by sidharthramesh** [comment]
All of them use lit-html

**Comment by sidharthramesh** [comment]
> we just got some new snippets here: #14163
> 
> does it help?

All of them use lit-html

**Comment by shilman** [comment]
cc @gaetanmaisse

**Comment by gaetanmaisse** [comment]
@sidharthramesh as you're using `@storybook/html` you have a few example stories in https://github.com/storybookjs/storybook/tree/next/examples/html-kitchen-sink/stories. 

They are all using the new Component Story Format and you should be able to do the same on your side too, it should look like:

```js
// Somehow import your snazzy button
// ...

export const Simple = () => `<snazzy-button>Button text</snazzy-button>`

export const Large = () => `<snazzy-button size='large'>Button text</snazzy-button>`

// And even
export const ArgsBasedLarge = ({ size }) => `<snazzy-button size='${size}'>Button text</snazzy-button>`
ArgsBasedLarge.args = {
  size: 'large'
}
```

**Comment by reno1979** [comment]
@gaetanmaisse the examples work, thanks for that. 

But mentioned before: The docs part of storybook does not render the component anymore. Instead it shows the HTML string.
Some examples stories https://github.com/storybookjs/storybook/tree/next/examples/html-kitchen-sink/stories. return HTMLElements instead of a string, perhaps I could just use a DOMparser.
 
The controls etc only work when I supply a web-components.json, but the process is anything but elegant ...
There were some experiments: runem/web-component-analyzer#1

**Comment by reno1979** [comment]
Ok just tested returning HTML elements, now the docs render the components!! yeah!

But know the canvas is broken..... Message:

Expecting an HTML snippet or DOM node from the story: "Primary" of "Buttons/button"

Sigh... Zucht... 

utility used: 

```js
/**
 * Parses a HTML-like string into HTML.
 * 
 * @param {!string} string The HTML-like string to parse
 * @param {boolean} [returnChildNodes=true] Whether to return the supplied nodes only or a fully fledged document
 * @return {NodeListOf<ChildNode>|Document}
 */
export function parseStringAsHtml(string, returnChildNodes = true) {
    const _parsedHtml = _getDomParser().parseFromString(string, 'text/html');

    // The parsed HTML string is transformed in a fully fledged HTML document, by default we 
    // only return the nodes that are part of the input string
    return returnChildNodes ? _parsedHtml.querySelector('body').childNodes : _parsedHtml;
}
```

**Comment by sidharthramesh** [comment]
> we just got some new snippets here: #14163
> 
> does it help?

Okay. So I just got to using these snippets, and they work great! They work with custom elements out of the box if they are just imported in the preview.js file! I assumed that they were meant for lit-html components only, but it works for anything. Thanks for these snippets!!

One thing that took me a while to figure out was that non-string attributes must be passed in as properties instead with the `.prop=${yourprop}` syntax. Leaving a lit-html [cheatsheet here](https://lit-html.polymer-project.org/guide/writing-templates) for others. Would really help anyone starting out have a good starting point since not everyone uses lit-html.

Otherwise, storybook actually has an excellent development workflow for web components. The hot reloading still needs some work, but otherwise it's solid!

**Comment by gaetanmaisse** [comment]
@reno1979 I'm facing the same limitation in my company Storybook, the need to use web-component-analyzer etc, I hope I will be able to do some improvement on that side, on HMR and add missing features to be aligned with @storybook/angular/react/vue for the next big release of Storybook (6.2 will be out soon so I think it will be 7.0 then).

@sidharthramesh yep `@storybook/web-components` is `lit-html` oriented, I have planned to take a look at that + Stencil integration when I will have a bit more free time.

**Comment by shilman** [comment]
@gaetanmaisse probably 6.3 👍

**Comment by reno1979** [comment]
@gaetanmaisse Any improvement for the vanilla webcomponents is welcome. For now storybook still offers a great workflow. The work arounds kind of work, still I can't wait for future updates.

**Comment by andez2000** [comment]
Fast forward to 2023.

Are there any sample projects anywhere demonstrating how to use Story Book with plain old HtmlElement web components?

Great tool by the way

**Comment by jonniebigodes** [comment]
Closing this for now, as the documentation is now fully featuring Web Components examples, and we've improved the Web Components support as of the recent 7.0 release. 

In case there's something else missing, let me know, and I'll gladly re-open the issue and follow up with you so that we can work towards a suitable solution.

Hope you have a great day.

Stay safe
