### ISSUE TITLE
Storybook only loads when built for production in IE11

### ISSUE THREAD

**Issue by lifeiscontent** [storybookjs/storybook#13418]
**Describe the bug**
Doesn't look like Storybook runs when running `yarn storybook` (dev mode) in IE11. I'm getting errors saying "Syntax error" coming from the Acorns package.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
Please paste the results of `npx sb@next info` here.

**Additional context**

**Comment by tooppaaa** [comment]
Just tried latest 6.1 (6.1.14), working fine with IE 11. Can you confirm @lifeiscontent  ?

**Comment by tooppaaa** [comment]
Closing as it worked - and should work with 6.2.

In any case:
I have added acorn-jsx to https://github.com/storybookjs/presets/pull/197.

If this is still an issue (when it gets out), could you reopen this ?

**Comment by lifeiscontent** [comment]
@tooppaaa still an issue for me running latest in Dev server

**Comment by tooppaaa** [comment]
@lifeiscontent I've pushed this fix: https://github.com/storybookjs/storybook/pull/15770/commits/6ec4d214a171246d05ff6386f6f90e6012d09578

Did you give a try to addon-ie11 ?
I also pushed the commit in the addon - should be released soon.
https://github.com/storybookjs/addon-ie11/pull/5
