### ISSUE TITLE
Type 'JestSerializer' is not assignable to type 'Plugin' when using Enzyme to render/snapshot

### ISSUE THREAD

**Issue by eric-burel** [storybookjs/storybook#13419]
**Describe the bug**

```
Type 'JestSerializer' is not assignable to type 'Plugin'
 ```

**To Reproduce**

Install storyshots in a TS project and follow documentation to use `enzyme` and `enzyme-to-json` to render and serialize.

```ts
import initStoryshots from "@storybook/addon-storyshots";
import { mount } from "enzyme";
import { createSerializer } from "enzyme-to-json";

initStoryshots({
  renderer: mount,
  snapshotSerializers: [createSerializer() as any]
});
```

**Expected behavior**
No type error.

But maybe this cast is necessary because both type describe the same object but with a different wording?

**Comment by ndelangen** [comment]
The future of storyshots is the test-runner:
https://storybook.js.org/docs/react/writing-tests/test-runner#page-top

And use the play function for expectations:
https://storybook.js.org/docs/react/writing-stories/play-function#page-top

We will not be making any improvement / changes to storyshots.
