### ISSUE TITLE
Circular Dependency with Zoom Component

### ISSUE THREAD

**Issue by philipbordallo** [storybookjs/storybook#13437]
**Describe the bug**

The [Zoom component](https://github.com/storybookjs/storybook/blob/next/lib/components/src/Zoom/Zoom.tsx) introduced a circular dependency that [`circular-dependency-plugin`](https://github.com/aackerman/circular-dependency-plugin) started warning about in our Storybook project once we updated to the latest version.

```
WARNING in Circular dependency detected:
node_modules/@storybook/core/node_modules/@storybook/components/dist/Zoom/Zoom.js -> node_modules/@storybook/core/node_modules/@storybook/components/dist/Zoom/ZoomElement.js -> node_modules/@storybook/core/node_modules/@storybook/components/dist/Zoom/Zoom.js

WARNING in Circular dependency detected:
node_modules/@storybook/core/node_modules/@storybook/components/dist/Zoom/ZoomElement.js -> node_modules/@storybook/core/node_modules/@storybook/components/dist/Zoom/Zoom.js -> node_modules/@storybook/core/node_modules/@storybook/components/dist/Zoom/ZoomElement.js

WARNING in Circular dependency detected:
node_modules/@storybook/core/node_modules/@storybook/components/dist/Zoom/ZoomIFrame.js -> node_modules/@storybook/core/node_modules/@storybook/components/dist/Zoom/Zoom.js -> node_modules/@storybook/core/node_modules/@storybook/components/dist/Zoom/ZoomIFrame.js
```

**To Reproduce**
Add [`circular-dependency-plugin`](https://github.com/aackerman/circular-dependency-plugin) to the webpack plugins list and import a component from `@storybook/components` somewhere.

```js
const CircularDependencyPlugin = require('circular-dependency-plugin')


module.exports = {
  webpackFinal: async (config) => {
    config.plugins.push(new CircularDependencyPlugin())

    return config;
  },
 // ...
}

```

Here is an example repo (https://github.com/philipbordallo/eyes-storybook-example) where it occurs.

You also can run `npx madge --circular --extensions ts lib/components` and you will get:
```
✖ Found 2 circular dependencies!

1) src/Zoom/Zoom.tsx > src/Zoom/ZoomElement.tsx
2) src/Zoom/Zoom.tsx > src/Zoom/ZoomIFrame.tsx
```

**Expected behavior**
No circular dependencies.

**Comment by shilman** [comment]
Crikey!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.0-alpha.6 containing PR #13439 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
