### ISSUE TITLE
Using apollo-client useDeepMemo hook in component breaks storyshots test without failing storyshot unit-test

### ISSUE THREAD

**Issue by andoks** [storybookjs/storybook#13435]
**Describe the bug**
When using storyshot to snapshot test a component which internally makes use of [apollo-clients useDeepMemo hook](https://github.com/apollographql/apollo-client/blob/main/src/react/hooks/utils/useDeepMemo.ts), the components' story snapshot is not tested or generated.

**To Reproduce**
https://github.com/andoks/usedeepmemo_breaks_storybook

**Expected behavior**
One of two things preferably:
1. Using useDeepMemo does not affect the test at all, and storyshot test is generated as usual
2. The storyshot unit-test fails so that developer/CI doesn't overlook the issue

**Screenshots**
![image](https://user-images.githubusercontent.com/5228/101932462-18824800-3bdb-11eb-8535-896f25993bf4.png)

**Code snippets**
See repro

**System**
  System:
    OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (16) x64 AMD Ryzen 7 1800X Eight-Core Processor
  Binaries:
    Node: 15.2.1 - ~/.local/lib/node-v15.2.1-linux-x64/bin/node
    npm: 7.0.11 - ~/.local/lib/node-v15.2.1-linux-x64/bin/npm
  Browsers:
    Firefox: 83.0
  npmPackages:
    @storybook/addon-actions: ^6.1.10 => 6.1.10 
    @storybook/addon-essentials: ^6.1.10 => 6.1.10 
    @storybook/addon-links: ^6.1.10 => 6.1.10 
    @storybook/addon-storyshots: ^6.1.10 => 6.1.10 
    @storybook/node-logger: ^6.1.10 => 6.1.10 
    @storybook/preset-create-react-app: ^3.1.5 => 3.1.5 
    @storybook/react: ^6.1.10 => 6.1.10 

**Additional context**
Project create using create-react-app (using latest react 16 ATM) with typescript template. Had to downgrade babel-loader, and force an older version of react-test-renderer (to support React 16)

**Possible workaround**
Mock `useDeepMemo` by adding the following to setupTests.js
```
jest.mock("@apollo/client/react/hooks/utils/useDeepMemo", () => {
        return {
            __esModule: true,
            useDeepMemo: (fn, key) => (fn()),
        }
    }
);
```

**Comment by ndelangen** [comment]
The future of storyshots is the test-runner:
https://storybook.js.org/docs/react/writing-tests/test-runner#page-top

And use the play function for expectations:
https://storybook.js.org/docs/react/writing-stories/play-function#page-top

We will not be making any improvement / changes to storyshots.
