### ISSUE TITLE
Stories not available when file name starts with 'config'.

### ISSUE THREAD

**Issue by MBelniak** [storybookjs/storybook#13445]
I think it's a bug. I have a component called 'ConfigSelector' and few stories in 'config-selector.tsx'. Stories from this file are not visible in storybook. Stories from other files I have work OK. If I change the name of file to sth not starting with 'config', stories are visible.  FYI my storybook configuration files are in separate directory.

1. Create a story of some dummy component in file named "config-whatever.tsx"
2. Run storybook

Result:
No stories from "config-whatever.tsx" available.

Expected behavior
Stories from "config-whatever.tsx" are visible.

This happens with @storybook/react 6.1.10

**Comment by shilman** [comment]
Do you have a repro repo you can share?

**Comment by MBelniak** [comment]
I can't share the one I have, but I'll try to create a small repro repo later. Digging deeper into that I realized that for some names it works, for other it doesn't, with strong no-working correlation for names starting with a letter 'c' (except for 'checkbox.tsx') As soon as I change the first letter to some other it works. Is there any naming convention or something which I'm not aware of?

**Comment by shilman** [comment]
@MBelniak nothing that i know of, and this is the first i'm hearing of it. i suspect it's a configuration issue, but won't know until i see the repro.

**Comment by MBelniak** [comment]
I find it too ridiculous to be a storybook issue too, so let me make a repro repo.

**Comment by MBelniak** [comment]
It turned out to be a problem with style-loader configuration. I had an option `insert: top`, which caused the following error in two of my components: `Unexpected error while loading ./datagrid.tsx: Error: Couldn't find a style target. This probably means that the value for the 'insert' parameter is invalid.` which showed up in static storybook. When developing with webpack-dev-server everything seemed to work fine after the first webpack-dev-server refresh, but before that, the stories didn't show up. Weirdly, that affected the story named 'config-selector', I have no clue why. After removing the aforementioned option from style-loader everything started to work porperly.
