### ISSUE TITLE
Webpack 5

### ISSUE THREAD

**Issue by gcofficial** [storybookjs/storybook#13446]
**Is your feature request related to a problem? Please describe**
@shilman 
Hey guys 👋🏻
Do you have some plans to implement webpack 5 support? I tried to use "exports" (package.json) field but webpack 4 will not resolve it if you want to get some js file from the corresponding package. 

**Describe the solution you'd like**
Update the webpack 4 to webpack 5.

**Comment by mj12albert** [comment]
There’s a PR for this https://github.com/storybookjs/storybook/pull/13392

**Comment by shilman** [comment]
yes we do. closing as duplicate to #9216
