### ISSUE TITLE
Unable to import stories outside of /src

### ISSUE THREAD

**Issue by aelesia** [storybookjs/storybook#13454]
**Describe the bug**

Storybook 6.0 web is unable to load any stories that do not reside within the `./src` folder.

**To Reproduce**

1. Create a new storybook project

2. Create a new sibling folder and name it `stories`, then add a new story

    ```
    - <root>
        - .storybook/
        - src/
        - stories/
            - First.stories.tsx
        - package.json
    ```

3. Change `main.js` to include stories from `../stories/**/*.stories.@(js|jsx|ts|tsx)`

**Expected behavior**

The new story should be imported into storybook. However, no story shows up and no error messages can be found.

**Code snippets**

Directory
<img width="356" alt="Screenshot 2020-12-15 at 17 28 27" src="https://user-images.githubusercontent.com/7008316/102196544-02d29280-3efb-11eb-997c-a104b8dfe155.png">

main.js
```
"stories": [
  "../src/**/*.stories.mdx",
  "../src/**/*.stories.@(js|jsx|ts|tsx)",
  "../stories/**/*.stories.@(js|jsx|ts|tsx)"
]
````

**System**

```
Environment Info:

  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  Binaries:
    Node: 12.6.0 - ~/.nvm/versions/node/v12.6.0/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v12.6.0/bin/npm
  Browsers:
    Chrome: 87.0.4280.88
    Firefox: 83.0
    Safari: 12.1.2
  npmPackages:
    @storybook/addon-actions: ^6.1.9 => 6.1.10 
    @storybook/addon-essentials: ^6.1.9 => 6.1.10 
    @storybook/addon-links: ^6.1.9 => 6.1.10 
    @storybook/node-logger: ^6.1.9 => 6.1.10 
    @storybook/preset-create-react-app: ^3.1.5 => 3.1.5 
    @storybook/react: ^6.1.9 => 6.1.10 
```

**Additional context**

This can be solved by modifiyng webpack with the following code:

```
  "stories": [
    "../src/**/*.stories.mdx",
    "../src/**/*.stories.@(js|jsx|ts|tsx)",
    "../stories/**/*.stories.@(js|jsx|ts|tsx)"
  ]

  webpackFinal: (config) => {
    config.resolve.alias = {
      'react-native': 'react-native-web'
    };
    config.module.rules[5].oneOf[2].include.push(
      path.resolve('stories')
    )
    return config;
  },
```

Apparently there is an additional config in webpack that tells it to only look through the `src` directory. You must manually push in the path of your stories, otherwise storybook will not be able to locate your story even though it is listed under `"stories": []`.

Notes: 
- `path.resolve()` uses the path relative to root, while `"stories": []` uses the path relative to `main.js`
- `config.module.rules[x].oneOf[y].include` varies depending on which storybook version.
    - In `@6.1.9`, it is `config.module.rules[5].oneOf[2].include`
    - In `@6.0.21`, it is `webpackConfig.module.rules[6].oneOf[1].include`

**Comment by amirhosseinak20** [comment]
I face same problem, is there any fix?

**Comment by shilman** [comment]
Closing as duplicate to #11644
