### ISSUE TITLE
AddOn StoryShot errors with "export" unexpected token

### ISSUE THREAD

**Issue by rexkenley** [storybookjs/storybook#13460]
**Describe the bug**
I added StoryShot to my project following the official instructions. However,  I am encountering an "unexpected token" error when I run jest.

**To Reproduce**
1. Clone https://github.com/rexkenley/d365DatetimeFormatBox
2. npm i
3. npm run test

**Expected behavior**
Jest runs the Storybook StoryShot tests

**Screenshots**
![image](https://user-images.githubusercontent.com/10548251/102276336-a0769380-3ef4-11eb-85e4-cf1f57875b29.png)

**System**
![image](https://user-images.githubusercontent.com/10548251/102276555-f6e3d200-3ef4-11eb-9161-4fd1f51e8c0b.png)

**Comment by rexkenley** [comment]
Just for giggles I tried using babel-jest instead of ts-jest (to process both ts and js files). I got past the unexpected token errors, but now got the dreaded "storyshot found 0 stories"
![image](https://user-images.githubusercontent.com/10548251/102542515-ef046900-407f-11eb-83e0-dec36901cc68.png)

**Comment by rexkenley** [comment]
I got past the < token error by adding babel react preset. Now I am back to the export token error
![image](https://user-images.githubusercontent.com/10548251/102551678-e74bc100-408d-11eb-8374-bc375056b3e2.png)

Ps. I updated the repo to where I am now.

**Comment by rexkenley** [comment]
I posted the issue on ts-jest and this is their reply
https://github.com/kulshekhar/ts-jest/issues/2244

**Comment by KirillBudenko** [comment]
Just faced the exact same issue with latest storybook, `.tsx` stories and `ts-jest`. 
Did you find any way to workaround the issue without enabling the ESM Support with huge amount of negative side-effects?

**Comment by rexkenley** [comment]
Unfortunately no

**Comment by KirillBudenko** [comment]
Figured out to workaround my problem by simply replacing brand new `export const parameters` generated by `sb init` with old-fashioned `addParameters` in `.storybook/preview.js`

```
const { addParameters } = require('@storybook/react');

addParameters({
    // any configuration
});
```

**Comment by kevinmpowell** [comment]
@KirillBudenko 's workaround doesn't seem sustainable since addParameters is deprecated right @shilman ?

**Comment by mbhm86** [comment]
Any update on this?

**Comment by ndelangen** [comment]
The future of storyshots is the test-runner:
https://storybook.js.org/docs/react/writing-tests/test-runner#page-top

And use the play function for expectations:
https://storybook.js.org/docs/react/writing-stories/play-function#page-top

We will not be making any improvement / changes to storyshots.
