### ISSUE TITLE
Unable to add @fluentui/jest-serializer-merge-styles as snapshot serializer within storyshot

### ISSUE THREAD

**Issue by fhdsouza** [storybookjs/storybook#13469]
**Describe the bug**
Im trying to have storyshots included within storybook with our fluentUI compoenents. I need to enable snapshotSerializer as a fluent provided serializer but I get the error: Type 'string' is not assignable to type 'Plugin' below.

**To Reproduce**
Here's my setup file:

initStoryshots({
    configPath: 'src/storybook',
    framework: 'react',
    test: multiSnapshotWithOptions({}),
    stories2snapsConverter: new Stories2SnapsConverter({
      snapshotsDirName: '../../../tests/__snapshots__/'
    }),
    snapshotSerializers: [
      "@fluentui/jest-serializer-merge-styles"
    ]
});

**Expected behavior**
No error should be thrown

**Comment by ndelangen** [comment]
The future of storyshots is the test-runner:
https://storybook.js.org/docs/react/writing-tests/test-runner#page-top

And use the play function for expectations:
https://storybook.js.org/docs/react/writing-stories/play-function#page-top

We will not be making any improvement / changes to storyshots.
