### ISSUE TITLE
Storybook Docs 6.1.1 not able to set components to MDXProvider as global scope

### ISSUE THREAD

**Issue by Niznikr** [storybookjs/storybook#13468]
**Describe the bug**
After upgrading from `6.0.25` Storybook Docs no longer recognizes components passed to MDXProvider as global scope. It was working with the following in preview.js:

```
export const parameters = {
  docs: {
    inlineStories: true,
    theme: theme,
    components: {
      SomeComponent: SomeComponent,
    },
  },
};
```

Has the way to configure this changed in `6.1`?

**To Reproduce**

1. Update `preview.js` with a similar config to set SomeComponent with global scope
2. In component mdx docs use SomeComponent
3. Notice warning `Component SomeComponent was not imported, exported, or provided by MDXProvider as global scope`

**Expected behavior**
SomeComponent is available to use in mdx docs on a global level.

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
```
Environment Info:

  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  Binaries:
    Node: 14.15.1 - ~/.nvm/versions/node/v14.15.1/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.1/bin/npm
  Browsers:
    Chrome: 87.0.4280.88
    Edge: 87.0.664.60
    Firefox: 84.0
    Safari: 14.0.2
  npmPackages:
    @storybook/addon-a11y: ^6.1.1 => 6.1.1 
    @storybook/addon-actions: ^6.1.1 => 6.1.1 
    @storybook/addon-controls: ^6.1.1 => 6.1.1 
    @storybook/addon-docs: ^6.1.1 => 6.1.1 
    @storybook/addon-storysource: ^6.1.1 => 6.1.1 
    @storybook/addon-viewport: ^6.1.1 => 6.1.1 
    @storybook/addons: ^6.1.1 => 6.1.1 
    @storybook/react: ^6.1.1 => 6.1.1 
    @storybook/source-loader: ^6.1.1 => 6.1.1 
    @storybook/theming: ^6.1.1 => 6.1.1 
    @storybook/web-components: ^6.1.1 => 6.1.1 
```

**Additional context**

**Comment by shilman** [comment]
One potential culprit is the `@mdx-js/*` dependencies in 6.0:

```
    "@mdx-js/loader": "^1.5.1",
    "@mdx-js/mdx": "^1.5.1",
    "@mdx-js/react": "^1.5.1",
```

And in 6.1:

```
    "@mdx-js/loader": "^1.6.19",
    "@mdx-js/mdx": "^1.6.19",
    "@mdx-js/react": "^1.6.19",
```

It's possible that there was a breaking change without a corresponding major release. Is that something you might be able to experiment with?

**Comment by Niznikr** [comment]
Sure will give that a try!

**Comment by Niznikr** [comment]
Tried installing the `@mdx-js` dependencies with resolutions set to `1.5.1` but Storybook was not building correctly after the install. Perhaps this is because we are using React 17 in our project (hence the upgrade to Storybook `6.1`).

**Comment by Niznikr** [comment]
Any thoughts @shilman? It seems storybookjs/storybook#13605 is related.

**Comment by shilman** [comment]
Do you have a repro repo you can share?

**Comment by Niznikr** [comment]
@shilman I do not as it is a private project. I did update to `6.2.0-beta.1` and things are working as expected again 😄

**Comment by shilman** [comment]
That's great! Closing then... 😅
