### ISSUE TITLE
the background color of the preview is delayed in "Docs" pane

### ISSUE THREAD

**Issue by 3c1u** [storybookjs/storybook#13465]
**Describe the bug**

**To Reproduce**

Set the background and specify the background in `preview.js` in advance.

1. Select a component from the sidebar.
2. Open "Docs".
3. Change props from "Control" section.
4. The background color will change to the specified background.

**Expected behavior**

The background color should be the default when it is loaded, and it should follow the settings at the top bar.

**Screenshots**

https://gyazo.com/89287048da14f697e502c05398f7fd27
https://gyazo.com/a34f20c4c456e899dcbbfac3a6483c3b

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
```
Environment Info:

  System:
    OS: macOS 11.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 15.1.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.0.8 - /usr/local/bin/npm
  Browsers:
    Chrome: 87.0.4280.88
    Edge: 87.0.664.60
    Firefox: 83.0
    Safari: 14.0.2
  npmPackages:
    @storybook/addon-actions: 6.1.11 => 6.1.11 
    @storybook/addon-docs: 6.1.11 => 6.1.11 
    @storybook/addon-essentials: 6.1.11 => 6.1.11 
    @storybook/addon-links: 6.1.11 => 6.1.11 
    @storybook/vue: 6.1.11 => 6.1.11 
```

**Additional context**
I'm using `@nuxtjs/storybook`, so this might be a problem related to it.

**Comment by shilman** [comment]
@3c1u do you have a repro repo you can share?

@yannbf is this something you've run into?

**Comment by 3c1u** [comment]
@shilman Here is the minimal conifiguration with Nuxt and `@nuxtjs/storybook`. https://github.com/3c1u/storybook-nuxt-random-example

**Comment by 3c1u** [comment]
Also tried the plain Storybook and it worked ( https://github.com/3c1u/storybook-nuxt-random-example/tree/storybook ), so `@nuxtjs/storybook` is the culprit?
