### ISSUE TITLE
Can't import/use angular Router stuff in stories

### ISSUE THREAD

**Issue by kkoo95** [storybookjs/storybook#13467]
Describe the bug**
I would like to use [routerLink] in my stories **templates**, but it doesn't work.

Adding (or not) RouterModule to module metadata `imports` array does't solve the issue.
Adding `RouterModule` to it gives:
```console
DynamicComponent.html:1 ERROR NullInjectorError: StaticInjectorError(DynamicModule)[RouterLinkWithHref -> Router]: 
  StaticInjectorError(Platform: core)[RouterLinkWithHref -> Router]: 
    NullInjectorError: No provider for Router!
```
None of the other options like `.forRoot()`, `.forChild()` and `RouterTestingModule` works neither

It's worth mentioning that i _do not_ wish to navigate through storybook pages with these links. It's rather a feature of my directive that i would like to showcase (because it behaves differently when `routerLink` is there or not)

**To Reproduce**
Create a story as simple as:
```ts
import { RouterModule } from '@angular/router';

export default {
  title: 'MyStory'
}

export const primary = () => ({
  moduleMetadata: {imports: [RouterModule]},
  template: '<a [routerLink]="go">goo</a>'
})
```

**System**
>   System:
>     OS: Windows 10 10.0.18363
>     CPU: (4) x64 Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
>   Binaries:
>     Node: 12.16.1 - D:\dev\tools\nodejs\12.16.1\node.EXE
>     Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
>     npm: 6.13.4 - D:\dev\tools\nodejs\12.16.1\npm.CMD
>   Browsers:
>     Chrome: 87.0.4280.88
>     Edge: Spartan (44.18362.449.0)
>   npmPackages:
>     @storybook/addon-actions: ^6.1.0 => 6.1.10
>     @storybook/addon-backgrounds: ^6.1.5 => 6.1.10
>     @storybook/addon-cssresources: ^6.1.0 => 6.1.10
>     @storybook/addon-knobs: ^6.1.0 => 6.1.10
>     @storybook/addon-storyshots: ^6.1.0 => 6.1.10
>     @storybook/addon-storysource: ^6.1.0 => 6.1.10
>     @storybook/addon-toolbars: ^6.1.0 => 6.1.10
>     @storybook/angular: ^6.1.0 => 6.1.10
>

**Comment by yuchuan1** [comment]
How about 
```javascript
export const primary = () => ({
  moduleMetadata: {
    imports: [RouterModule.forRoot([])],
  },
  template: '<a [routerLink]="go">goo</a>',
});
`

**Comment by MickL** [comment]
@yuchuan1 this gives me:

> zone.js:690 Unhandled Promise rejection: No base href set. Please provide a value for the APP_BASE_HREF token or add a base element to the document.

**Comment by temacode** [comment]
@MickL you just need to provide APP_BASE_HREF, as it says

```
decorators: [
		moduleMetadata({
			declarations: [TestComponent],
			imports: [RouterModule.forRoot(routes)],
			providers: [
				{
					provide: APP_BASE_HREF,
					useValue: '/',
				},
			],
		}),
	],

**Comment by valentinpalkovic** [comment]
Closing, as it has a solution.
