### ISSUE TITLE
Storybook-eol org pointing at user rather than this org

### ISSUE THREAD

**Issue by nschonni** [storybookjs/storybook#13462]
![image](https://user-images.githubusercontent.com/1297909/102299941-ee55c080-3f21-11eb-8e68-ae117f179a48.png)
Ended up at one of the packages in https://github.com/storybook-eol and found the URL for this org was wrong when I tried to just edit the URL to come here.
Think on of the org admins there just needs to modify the profile. As I was able to get here by following the link to the main site and end up here.

**Comment by shilman** [comment]
Thanks @nschonni ! Fixed.
