### ISSUE TITLE
Angular: use Docs addon without compodoc

### ISSUE THREAD

**Issue by ThibaudAV** [storybookjs/storybook#13472]
**Is your feature request related to a problem? Please describe**

Can we use the docs addon and to use the mdx files without adding compodoc dependency?

**Describe the solution you'd like**
add doc addon without compodoc dependency

Do not return an error ? 
Disable `extractArgTypes` and `extractComponentDescription` part if compodoc is not present ? [link](https://github.com/storybookjs/storybook/blob/next/addons/docs/src/frameworks/angular/config.ts)
I'm not sure what to do if you have an idea ?

**Describe alternatives you've considered**
 🤷‍♂️ 

**Are you able to assist to bring the feature to reality?**
yes

**Additional context**

Acctually if I test on a project I have this error `Error: Invalid compodoc JSON at checkValidCompodocJson`
extractArgTypes -> getComponentData -> [checkValidCompodocJson](https://github.com/storybookjs/storybook/blob/974fd141f34896d00ed53ecc6fbcb57ee7e3c860/addons/docs/src/frameworks/angular/compodoc.ts#L36)

**Comment by tupcuturan35** [comment]
Topuzlar

**Comment by shilman** [comment]
Crikey!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.0-alpha.9 containing PR #13487 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
