### ISSUE TITLE
Story Docs page does not show the first story

### ISSUE THREAD

**Issue by crobinson42** [storybookjs/storybook#13470]
**Describe the bug**
When clicking on a Story's "Docs" tab, the first story is not shown under the "Stories" section of the Docs page.

**Expected behavior**
I expect the first story in the list to show under the "Stories" section on the docs page

**Screenshots**
![image](https://user-images.githubusercontent.com/5973579/102443838-8adc9900-3fdc-11eb-9547-68989c9eefe8.png)

**Code snippets**

Simple setup and 1 story:

```jsx
// AccessLevel.stories.jsx

import React from 'react'

import AccessLevel from './index'

export default {
  title: 'Example/AccessLevel',
  component: AccessLevel,
}

const Template = args => <AccessLevel {...args} />

export const Level1 = Template.bind({})

Level1.args = {
  accessLevel: 1,
  showAllAccessLevels: true,
}

Level1.storyName = 'Level 1'

export const Level2 = Template.bind({})

Level2.args = {
  accessLevel: 2,
}

Level2.storyName = 'Level 2'

export const Level3 = Template.bind({})

Level3.args = {
  accessLevel: 3,
}

Level3.storyName = 'Level 3'
```

**System**
System:
    OS: macOS 11.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    npm: 6.14.9 - ~/projects/node_modules/.bin/npm
  Browsers:
    Chrome: 87.0.4280.88
    Firefox: 83.0
    Safari: 14.0.2
  npmPackages:
    @storybook/addon-actions: ^6.1.11 => 6.1.11 
    @storybook/addon-essentials: ^6.1.11 => 6.1.11 
    @storybook/addon-links: ^6.1.11 => 6.1.11 
    @storybook/addons: ^6.1.11 => 6.1.11 
    @storybook/react: ^6.1.11 => 6.1.11

**Comment by shilman** [comment]
Closing as duplicate to #8093
