### ISSUE TITLE
Web Components HMR Incompatibility - preview.js Reload config missing in 6.x

### ISSUE THREAD

**Issue by kevinmpowell** [storybookjs/storybook#13484]
**Describe the bug**
When writing stories for a custom element registered with `customElements.define` subsequent changes to the source component file cause HMR to fail and require a manual reload of the page to see the changes made to the component.

**To Reproduce**

1. Create a default install of storybook with WEB_COMPONENTS as the type
2. At the bottom of the initial `Button.js` that's generated add:
```js
class NothingHere extends HTMLElement {
  connectedCallback() {
    this.innerHTML = "<h1>Hello Worlds</h1>";
  }
}

customElements.define("nothing-here", NothingHere);
```
3. Start storybook: `npm run storybook`
4. Make a change to `Button.js`
5. You should see this error when HMR tries to function:
![image](https://user-images.githubusercontent.com/979463/102650545-b2447a80-4130-11eb-87e1-5eb4830f2970.png)

**Expected behavior**
Changing a web component's source should reload storybook so the changes can be seen in stories without having to manually reload the browser.

**Code snippets**
Previously `.storybook/preview.js` contained the following for web components:
```js
import { configure } from "@storybook/web-components";
// force full reload to not re-register web components
const req = require.context("../stories", true, /\.stories\.(js|mdx)$/);

configure(req, module);

if (module.hot) {
  module.hot.accept(req.id, () => {
    const currentLocationHref = window.location.href;
    window.history.pushState(null, null, currentLocationHref);
    window.location.reload();
  });
}
```

That's no longer there. Adding the above to `preview.js` fixes the problem and gives the expected behavior.

**System**
Environment Info:

  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
  Binaries:
    Node: 12.18.4 - /usr/local/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.14.6 - /usr/local/bin/npm
  Browsers:
    Chrome: 88.0.4324.50
    Firefox: 81.0.1
    Safari: 14.0.1
  npmPackages:
    @storybook/addon-actions: ^6.2.0-alpha.8 => 6.2.0-alpha.8
    @storybook/addon-essentials: ^6.2.0-alpha.8 => 6.2.0-alpha.8
    @storybook/addon-links: ^6.2.0-alpha.8 => 6.2.0-alpha.8
    @storybook/web-components: ^6.2.0-alpha.8 => 6.2.0-alpha.8

**Comment by shilman** [comment]
Do you have a repro repo you can share?

Also, do you know when this broke?

**Comment by calebdwilliams** [comment]
Running into this on an internal project. Basically all you need to do is look at the [@storybook/web-components README](https://www.npmjs.com/package/@storybook/web-components), run the command and see that the files that are referenced for don't have the content the README claims.

**Comment by shilman** [comment]
closing this as dupe to #12307
