### ISSUE TITLE
Angular: The background color switch does not work dynamically in docs tabs.

### ISSUE THREAD

**Issue by ThibaudAV** [storybookjs/storybook#13480]
**Describe the bug**

The background color switch does not work dynamically in docs tabs.
Apparently only on Angular

**To Reproduce**

1. Go to 'https://next--storybookjs.netlify.app/angular-cli/?path=/story/welcome--to-storybook'
2. Click on 'Docs' tab
2. Click on 
![image](https://user-images.githubusercontent.com/4974420/102620739-cabb9180-413e-11eb-8db9-384513ffdfeb.png)
And change color 
The background color dose not change.
I have the impression that it is decorators who are not called 🤔 

**Expected behavior**
The background must change as in canvas

**Screenshots**

https://user-images.githubusercontent.com/4974420/102621421-ccd22000-413f-11eb-88ad-0456b89139ef.mp4

It doesn't only work on the docs part

**Code snippets**
🤷‍♂️

**System**
na

**Additional context**
na

**Comment by ThibaudAV** [comment]
This issue seems to have corrected the 🐛 . but only for the React part ?? :note-sure: 
https://github.com/storybookjs/storybook/issues/12305

**Comment by shilman** [comment]
@ThibaudAV I think this might be an issue for stories that run in iframes (angular), but has been fixed for inline stories (most other popular frameworks). @yannbf can you confirm?

**Comment by ThibaudAV** [comment]
@shilman you're right it seems to be related to iframe

So I'm going to propose PR to add "inline" stories support for addon docs with angular.
This is my christmas present 🎁  xD

**Comment by shilman** [comment]
Gadzooks!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.0-alpha.19 containing PR #13525 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
