### ISSUE TITLE
Add support for Custom Element Manifest

### ISSUE THREAD

**Issue by Westbrook** [storybookjs/storybook#13493]
**Is your feature request related to a problem? Please describe**
Currently, the web components build partially supports custom-element.json (which could use a little extra love in relation to Controls, but that's besides the point), and the successor to that specification is being finalized at https://github.com/webcomponents/custom-elements-manifest/blob/master/schema.json presently. The two specification are not compatible and a solution to address either or at least the newer version by default would be appreciated. 

**Describe the solution you'd like**
To support current toolchains, it would likely be best to fork on a signifier in the schemas so that both versions could be supported (possibly with a deprecation notice for the older version) in upcoming releases. Hopefully, the expanded form of CEM can also support a more feature rich marriage with the `argTypes` spec for users looking for pre-populated Controls UIs.

**Describe alternatives you've considered**
We could just support the new version (make a clean break), but I know that a lot of the tooling that I work with includes the old specification by default at current.

**Are you able to assist to bring the feature to reality?**
I've been looking at ways that custom-element.json can be more tightly paired with `argTypes` and can do similar with CEM boosting the capabilities that users acquire by default when leveraging the specifications.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if this is still relevant in SB 7.x. Pretty sure this feature has been around for awhile!
