### ISSUE TITLE
Global types does not work as documented for HTML components

### ISSUE THREAD

**Issue by maslade** [storybookjs/storybook#13495]
**Describe the bug**
The documented examples for exporting `globalTypes` in preview.js do not produce the documented results "you should see a new dropdown in your toolbar". My hunch is this is down to @storybook/html not supporting this feature.

**To Reproduce**
See repro here: https://github.com/maslade/storybook-toolbar-defect

1. Clone above git repo, which is a bare HTML @storybook/html project with the sample code copied into `preview.js`.
2. `npm install && npm start`
3. Wait for Storybook to start

**Expected behavior**
From the documentation:

> When you start your Storybook, you should see a new dropdown in your toolbar with options light and dark.

**Code snippets**
See git.

**System**
Environment Info:

  System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-2700K CPU @ 3.50GHz
  Binaries:
    Node: 14.7.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.7 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 87.0.4280.88
    Edge: Spartan (44.18362.449.0)
  npmPackages:
    @storybook/html: ^6.1.11 => 6.1.11

**Additional context**
The documentation I'm referring to is here: https://storybook.js.org/docs/html/essentials/toolbars-and-globals#global-types-and-the-toolbar-annotation

I see that @storybook/html doesn't support controls - could this be why? If so - what is a good alternative for adding a global configuration?

My use case: my project has multiple SASS entry points, reflecting different brands. At the moment I'm importing one in preview.js, and editing the code (remembering not to commit) when I want to see a different brand. I'd like to put this in the UI so users can swap brands without

**Comment by shilman** [comment]
This is your `main.js`:

```js
module.exports = {
  stories: ['../src/test.stories.ts'],
}
```

It needs an extra field, `addons` that registers the appropriate addons. You can either register essentials (which is what's being documented in your link), or you can just register `@storybook/addon-toolbars` if you just want this functionality:

```js
module.exports = {
  stories: ['../src/test.stories.ts'],
  addons: ['@storybook/addon-essentials'],
}
```

Whatever you register should also be installed in `package.json` and `node_modules`. Hope that helps!

**Comment by maslade** [comment]
Slapping my forehead. That did the trick - thanks for setting me straight. I landed on the docs straight from google and only skimmed the introduction section. I assumed essentials were Just There by way of magic.

Any thoughts on moving "Upgrading from previous versions" up into the configuration heading? I had to follow those steps on a fresh repo. Unless I missed it - that's the only place with explicit instructions to install @storybook/addons-essentials and configure it in main.js.

Happy to submit a PR if you think it's a good suggestion, otherwise this issue is settled for me.

**Comment by shilman** [comment]
@maslade I appreciate the offer to help improve the docs for existing users. @jonniebigodes WDYT?

**Comment by jonniebigodes** [comment]
@maslade we're more than welcome with documentation improvements that help not only but the rest of the community. When you're able make the pull request and tag me in it. And we'll go from there. Tag me in the pull request and link this issue so that we don't loose track of what's being documented.

Stay safe

**Comment by maslade** [comment]
Will do - thanks to you both. I'll send something through this weekend.

**Comment by jonniebigodes** [comment]
Closing this as it's fixed.
