### ISSUE TITLE
@storybook/client-api imports qs incorrectly

### ISSUE THREAD

**Issue by paulbrittain** [storybookjs/storybook#13496]
**Describe the bug**
Compiling a Typescript project with a dependency on storybook produces the following build error:

../node_modules/@storybook/client-api/dist/queryparams.d.ts:1:8 - error TS1259: Module '"..../node_modules/@types/qs/index"' can only be default-imported using the 'allowSyntheticDefaultImports' flag

1 import qs from 'qs';
         ~~

  ../../node_modules/@types/qs/index.d.ts:13:1
    13 export = QueryString;
       ~~~~~~~~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.

**To Reproduce**
Steps to reproduce the behavior:

See above error while compiling a typescript project with @storybook.

**Expected behavior**
The import is correctly used and consuming projects are not asked to add a compiler flag to compensate.

**System**
Environment Info:

  System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz
  Binaries:
    Node: 12.18.3 - ~\AppData\Local\Temp\yarn--1605095997292-0.8697518829893918\node.CMD
    Yarn: 1.22.10 - ~\AppData\Local\Temp\yarn--1605095997292-0.8697518829893918\yarn.CMD
    npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 87.0.4280.88
    Edge: Spartan (44.19041.423.0), Chromium (87.0.664.66), ChromiumDev (89.0.731.0)    

**Additional context**
Add any other context about the problem here.

**Comment by shilman** [comment]
What's the correct way to import it?

**Comment by paulbrittain** [comment]
@shilman Hello! Thank you for reading this issue.

@storybook/client-api/queryparams.ts imports qs to use the func parse. Qs does not have a default export, the following should work fine:

import { parse } from 'qs';   <--- If you want to just use the parse func, as is the case right now. This change requires the usage to change from 'qs.parse(...)' to 'parse(...)'

or

import * as qs from 'qs'; <--- If you want to import all funcs in qs and use qs as-is

**Comment by shilman** [comment]
@paulbrittain Aha, thanks for the clarification, makes snese! Any chance you could submit a small PR with the fix?

**Comment by ryanml** [comment]
@shilman @paulbrittain - I ran in to this issue myself and submitted a fix, hope that's alright!

**Comment by shilman** [comment]
Boo-yah!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.0-alpha.10 containing PR #13518 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

**Comment by shilman** [comment]
¡Ay Caramba!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.14 containing PR #13518 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```
