### ISSUE TITLE
[React / typescript] Empty type definitions and description

### ISSUE THREAD

**Issue by Zealxl** [storybookjs/storybook#13490]
**Describe the bug**
Empty types and description in docs page

**To Reproduce**

1. Declare arrow `Component` (with `interface` or `type` to define the types also)
2. Export component through `export default Component` syntax
3. Import `Component` as `import Component from '...'`
4. Declare some base template
5.  Run storybook
6.  Click on 'docs' tab
7. See no description and no types definitions

**Expected behavior**
Description for `Component` and type definitions

**Screenshots**

![image](https://user-images.githubusercontent.com/68605362/102724227-32303780-431f-11eb-9975-2c9122774e13.png)
![image](https://user-images.githubusercontent.com/68605362/102724262-6ad01100-431f-11eb-9bc2-2668184a88ba.png)

**Main.js config**
```js
module.exports = {
  typescript: {
    check: false,
    checkOptions: {},
    reactDocgen: "react-docgen-typescript",
    reactDocgenTypescriptOptions: {
      shouldExtractLiteralValuesFromEnum: true,
      propFilter: (prop) =>
        prop.parent ? !/node_modules/.test(prop.parent.fileName) : true,
    },
  },
  stories: ["../src/stories/**/*.stories.(ts|tsx|js|jsx|mdx)"],
  addons: [
    "@storybook/addon-actions",
    "@storybook/addon-links",
    "@storybook/preset-create-react-app",
    {
      name: "@storybook/addon-docs",
      options: {
        configureJSX: true,
      },
    },
  ],
};
```

**System**
```md
System:
    OS: Linux 4.19 Ubuntu 20.04 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
Binaries:
    Node: 12.18.2 - /usr/local/bin/node
    npm: 6.14.8 - /usr/local/bin/npm
npmPackages:
    @storybook/addon-actions: ^6.1.11 => 6.1.11 
    @storybook/addon-docs: ^6.1.11 => 6.1.11 
    @storybook/addon-links: ^6.1.11 => 6.1.11 
    @storybook/node-logger: ^6.1.11 => 6.1.11 
    @storybook/preset-create-react-app: ^3.1.5 => 3.1.5 
    @storybook/react: ^6.1.11 => 6.1.11
```

**Additional context**
How to fix: use `export {Component}` instead of `export default Component` and `import {Component} from '...'` instead `import Component from '...'` also

**Comment by shilman** [comment]
closing as duplicate to #9556
