### ISSUE TITLE
Stories don't show up in the sidebar with clean install

### ISSUE THREAD

**Issue by AndrewKiri** [storybookjs/storybook#13494]
**Describe the bug**
I've created a fresh repo with latest storybook based on fresh repository scaffolded with create-react-app and upon loading the stories are missing

**To Reproduce**

1. `npx create-react-app any-app`
2. `cd any-app`
3. `npx sb init`
4. `npm run storybook`
5. See no stories but the Introduction.storeis.mdx file!!!!!

**Expected behavior**
Expected behavior is that stories that aren't MDX are shown too.

**Screenshots**
<img width="1687" alt="Screenshot 2020-12-21 at 09 49 23" src="https://user-images.githubusercontent.com/13384229/102752169-d3e07480-4371-11eb-81a1-f2ec2c91312a.png">
https://www.loom.com/share/fd7be23baaec41c2b3aad515f5aacc3f

**Code snippets**
Link to public git repo - https://github.com/AndrewKiri/copywriters24-components
Link to vercel live version - https://copywriters24-components.vercel.app/

**System**
macOS Catalina 10.15.6

**Additional context**

**Comment by AndrewKiri** [comment]
Here is the commit's [diff](https://github.com/AndrewKiri/copywriters24-components/commit/71fee23d8fb6c5ce0be3d59def0e7d8ae960a309) that is the result of running `npx sb init` and [live vercel url](https://vercel.com/andrewkiri/copywriters24-components/1wkf9zec2)

**Comment by shilman** [comment]
Sorry I missed this first time around. Is it still a problem for you? I can't repro.

**Comment by YPAzevedo** [comment]
Hey, just an update on this, i had the same issue but not on CRA. Stories weren't showing up due to react-fast-refresh. Once i removed it from babel when running storybook everything showed up 😄  Hope this helps anyone that reaches this same issue.
