### ISSUE TITLE
Getting warning "export Props (reexported) was not found in ..." during webpack compilation

### ISSUE THREAD

**Issue by comatory** [storybookjs/storybook#13506]
**Describe the bug**
During the build process, webpack is not able to find exported interface and throws warning:

```
WARNING in ./src/components/index.ts 2:0-31
"export 'Props' (reexported as 'ButtonProps') was not found in './button/button'
 @ ./src/stories/Button.stories.tsx
 @ ./src sync ^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.(js|jsx|ts|tsx))$
 @ ./.storybook/generated-stories-entry.js

```

I have this project structure

```
/src
  components/
    index.ts
    button/
      button.tsx
      button.css
  stories/
     Button.stories.tsx
```

`Button.stories.tsx` contains this import:

```
import { Button, ButtonProps } from '../components'
```

My `src/components/index.ts` files contains this:

```
import Button, { Props as ButtonProps } from './button/button'

export {
  Button,
  ButtonProps,
}
```

And my `src/components/button/button.tsx` has exports like this roughly:

```
export interface Props {}

const Button = (props: Props) => ...

export default Button
```

**To Reproduce**

Use storybook with React template and typescript. Import interface from the same file as component.

**Expected behavior**
No warning in the console.

**Screenshots**
![Screenshot 2020-12-22 at 16 50 24](https://user-images.githubusercontent.com/5990424/102907105-d5936080-4475-11eb-9768-f7de65f87b28.png)

**Code snippets**
See above

**System**
```
Environment Info:

  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
  Binaries:
    Node: 14.15.1 - ~/.nvm/versions/node/v14.15.1/bin/node
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.1/bin/npm
  Browsers:
    Chrome: 87.0.4280.88
    Firefox: 84.0
    Safari: 14.0
  npmPackages:
    @storybook/addon-actions: ^6.1.10 => 6.1.10
    @storybook/addon-essentials: ^6.1.10 => 6.1.10
    @storybook/addon-links: ^6.1.10 => 6.1.10
    @storybook/react: ^6.1.10 => 6.1.10
```

**Additional context**
I do not use "stories" alongside my components (because I don't like it).

**Comment by tommyc38** [comment]
This has to be the same issue as #13504

**Comment by shilman** [comment]
Closing as dupe to #13504
