### ISSUE TITLE
Can't export typescript types for React props - Warning "export 'FooProps' was not found in './Foo'

### ISSUE THREAD

**Issue by AndyOGo** [storybookjs/storybook#13504]
**Describe the bug**

I use typescript interfaces to prop-check my React components and I export them for later usage.

`Foo.ts`
```ts
export interface FooProps {
  bar: string;
}

export function Foo(props: FooProps) {
  return <div>{props.bar}</div>
}
```

`index.ts`
```ts
export { Foo, FooProps } from "./Foo";
```

**Yields:**
```sh
WARNING in ./src/components/Foo.ts 1:0-62
"export 'FooProps' was not found in './Foo'
```

**To Reproduce**

**Expected behavior**

I expect to have all Typescript types available for import.

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
Please paste the results of `npx sb@next info` here.

```sh
Environment Info:

  System:
    OS: Linux 3.10 Red Hat Enterprise Linux Server 7.9 (Maipo)
    CPU: (8) x64 Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz
  Binaries:
    Node: 10.19.0
    npm: 6.13.4
  Browsers:
    Chrome: 81.0.4044.138
  npmPackages:
    @storybook/addon-actions: ^6.1.11 => 6.1.11 
    @storybook/addon-knobs: ^6.1.11 => 6.1.11 
    @storybook/addons: ^6.1.11 => 6.1.11 
    @storybook/react: ^6.1.11 => 6.1.11 
    @storybook/storybook-deployer: ^2.8.7 => 2.8.7 
```

**Additional context**

**Edit:**

Typescript **3.8** released a feature to mark type-only imports/exports by `type` to help the elision process.
https://devblogs.microsoft.com/typescript/announcing-typescript-3-8-beta/#type-only-imports-exports

**Comment by tommyc38** [comment]
I am using the same version of storybook and have this warning with Angular 11.

**Comment by tommyc38** [comment]
@AndyOGo My types are being consumed properly.  In short, this is a really annoying bogus warning.  Can you confirm you types are working correctly?  Also, are you using webpack?

**Comment by tommyc38** [comment]
Here is a repro I created: https://github.com/tommyc38/nx-storybook-nest-repro

After you install all of the packages, run `npm run storybook-core` .  You should see the warning, below, that wasn't there with Storybook 5.3x.  I have a ton of these in my workspace after upgrading to Storybook 6x.

```
WARNING in ./libs/core/src/lib/core/directives/background.directive.ts 21:99-121
"export 'CorColorBackgroundType' was not found in '@umbrelo/data'
...
```

Moreover, the warning goes away if you change:

```
//libs/core/src/lib/core/directives/background.directive.ts --line 11
 @Input('corBackground') set background(bg:CorColorBackgroundType){
```

To:

```
//libs/core/src/lib/core/directives/background.directive.ts --line 11
 @Input('corBackground') set background(bg:CorColorBackgroundType|string){
```

Let me know if you want me to create a separate issue with my repro.

**Comment by tommyc38** [comment]
...possibly related to: https://github.com/webpack/webpack/issues/7378

**Comment by AndyOGo** [comment]
Yes we use webpack.

I migrated from storybook 5 with a custom webpack config using ts-loader to storybook 6 using built-in typescript support.
Since that shift we have these warnings, before there was no such issue and no need to explicitly type imports and exports.

I dont think this is a question/support, but rather a bug, since it was not a problem before.

**Comment by AndyOGo** [comment]
Typescript **3.8** released a feature to mark type-only imports/exports by `type` to help the elision process.
https://devblogs.microsoft.com/typescript/announcing-typescript-3-8-beta/#type-only-imports-exports

**Comment by comatory** [comment]
> Typescript **3.8** released a feature to mark type-only imports/exports by `type` to help the elision process.
> https://devblogs.microsoft.com/typescript/announcing-typescript-3-8-beta/#type-only-imports-exports

Yes using `import type { ... ` fixes this, as well as adjusting exports the same way, e.g. `export type { ....`
