### ISSUE TITLE
Question: why order of style tags in head of story depends on name of the file and not on the order of imports?

### ISSUE THREAD

**Issue by krutoo** [storybookjs/storybook#13515]
Hi, i use `@storybook/react 5.2.6` and in story `<head />` style-elements and they have an order that depends on the name of the component.

files three example:
```
.
└── src
    ├── A-component
    │   ├── a-component.css
    │   ├── index.js
    │   └── index.stories.js
    └── B-component
        ├── b-component.css
        ├── index.js
        └── index.stories.js
```

`B-component` depends on `A-component` and webpack with css-loader and style-loader (plain build, without storybook) outputs classes for css-modules as follows:

```html
<style>
.b-component--f61 {
  width: 100px;
  height: 50px;
  background: #0f0;
}
</style>
<style>
.a-component--10d {
  background: #f00;
}
</style>
```

**But** storybook outputs classes for css-modules like this:

```html
<style>
.a-component--10d {
  background: #f00;
}
</style>
<style>
.b-component--f61 {
  width: 100px;
  height: 50px;
  background: #0f0;
}
</style>
```

It looks like it determines the order *based on the name of the components* or stories and not depending *on the imports*

**Order of style tags affects the specificity of the classes.**

This behavior leads to the fact that when developing components in storybook I see one result and when using them in projects from package (with webpack build) - another.

How can i synchronize the behavior of storybook build and plain webpack build

**Comment by rebelliard** [comment]
Any tips here?

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
