### ISSUE TITLE
Addon-docs: story scrolls unexpectedly

### ISSUE THREAD

**Issue by unknownterritory** [storybookjs/storybook#13517]
**Describe the bug**
When using MDX docs, the first story doesn't have to be at the top of the docs page. When opening the docs the page scrolls to the first story somewhere on the page, which is confusing.

I am reopening a previous issue ( Addon-docs: Disable story scroll #10983) as the workaround offered there doesn't seem to work for me, unless I am missing something (in which case, documentation would be appreciated). I am using Svelte. I consider this a bug as the scrolling is both unexpected and confusing to the user.

**To Reproduce**

1. Add a story preview with the first story to the bottom of a MDX doc page. (see example below)
 2. Open docs page -> Page scroll down till story is in viewport.

**Expected behavior**
It would be nice if the auto scroll could be disabled.

**Code snippets**
```
import {
  Preview,
  Story
} from '@storybook/addon-docs/blocks';

# Button

Longer text …

<Preview>
  <Story id="components-button--default" />
</Preview>
```

**Comment by ndelangen** [comment]
With the changes coming in 7.0 relating to docs, I think this won't be an issue anymore. @shilman
