### ISSUE TITLE
References to separate e2e cli tests should be removed from CONTRIBUTING.md

### ISSUE THREAD

**Issue by ryanml** [storybookjs/storybook#13522]
**Describe the bug**
Per https://github.com/storybookjs/storybook/commit/3d7a024b3cd5433ec8fa59800881dc2752f08c4d#diff-299c7d433484aa19271a1219e3f35af59090987b5530de5ae0ddf12057439489 - CLI tests based on fixtures have been deleted, and the remaining tests are part of core.

**To Reproduce**
A new contributor may be confused, as running the test script per the doc with the suggested `--cli` option renders:

```
Ryans-MacBook-Pro:storybook ryanlanese$ yarn test --cli
yarn run v1.22.4
$ node ./scripts/test.js --cli
error: unknown option '--cli'
error Command failed with exit code 1.
```

**Expected behavior**
Document should not reference the CLI tests

**Comment by saddam1995** [comment]
run stand
