### ISSUE TITLE
Copy -- Cannot read property 'writeText' of undefined

### ISSUE THREAD

**Issue by finfinity** [storybookjs/storybook#13529]
**Describe the bug**
copy code show:
Cannot read property 'writeText' of undefined

**To Reproduce**

1. Click on 'show code'
2. Click on 'copy'

**Comment by wan54** [comment]
It's caused by `navigator.clipboard` is `undefined`

https://stackoverflow.com/questions/51805395/navigator-clipboard-is-undefined

**Comment by njcaballero** [comment]
> It's caused by `navigator.clipboard` is `undefined`
> 
> https://stackoverflow.com/questions/51805395/navigator-clipboard-is-undefined
> 
> Simply launch Storybook with `localhost` instead of ip address which is the default

This worked for me, although since the IP is something that can be used to show others on the same network and a link to it is given in the terminal when storybook is spun up. This should be labeled a bug.

**Comment by j3rem1e** [comment]
This is fixed here: #13776 in v6.1.16 and v6.2.0-alpha.20

**Comment by vuatintac** [comment]
Clipboard feature is available only in secure contexts (HTTPS), in some or all supporting browsers.
You need change protocol to https (SSL)

if (location.protocol !== 'https:') {
    location.replace(`https:${location.href.substring(location.protocol.length)}`);
}
