### ISSUE TITLE
Addon-Docs: Requires Vuejs as peer dependency 

### ISSUE THREAD

**Issue by tommyc38** [storybookjs/storybook#13526]
**Describe the bug**
@storybook/addon-docs requires vuejs.  

**To Reproduce**
install @storybook/addon-docs

**Expected behavior**
I shouldn't have to install vuejs in my Angular application.

**Screenshots**
```
npm WARN @storybook/addon-docs@6.1.11 requires a peer of @storybook/vue@6.1.11 but none is installed. You must install peer dependencies yourself.
npm WARN @storybook/addon-docs@6.1.11 requires a peer of sveltedoc-parser@^3.0.4 but none is installed. You must install peer dependencies yourself.
npm WARN @storybook/addon-docs@6.1.11 requires a peer of vue@^2.6.10 but none is installed. You must install peer dependencies yourself.
```
**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
  System:
    OS: macOS High Sierra 10.13.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 10.14.2 - ~/.nvm/versions/node/v10.14.2/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.14.2/bin/npm
  Browsers:
    Chrome: 87.0.4280.88
    Firefox: 68.0.1
    Safari: 13.1.2
  npmPackages:
    @storybook/addon-docs: ^6.1.11 => 6.1.11 
    @storybook/addon-knobs: ^6.1.11 => 6.1.11 
    @storybook/addons: ^6.1.11 => 6.1.11 
    @storybook/angular: ^6.1.11 => 6.1.11 

**Additional context**

**Comment by merceyz** [comment]
You don't have to, it's an optional peer dependency but your NPM version is too old to understand that

**Comment by tommyc38** [comment]
@merceyz I just upgraded and they went away.  Thank you!
