### ISSUE TITLE
unhandled exception with yarn v2 

### ISSUE THREAD

**Issue by amirhosseinak20** [storybookjs/storybook#13531]
**Describe the bug**
I was trying to implement [storybook tutorial](https://www.learnstorybook.com/intro-to-storybook/react/en/simple-component/) with yarn v2 and pnp, after i run `yarn storybook` or `yarn run storybook` i face this error 
`(node:96483) UnhandledPromiseRejectionWarning: Error: spawn ENOTDIR
    at ChildProcess.spawn (internal/child_process.js:407:11)
    at Object.spawn (child_process.js:553:9)
    at module.exports (/mnt/e/projects/ariana/iapp/.yarn/cache/open-npm-7.3.0-d582d8b42e-a212fc9cf6.zip/node_modules/open/index.js:152:34)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:96483) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4984)
(node:96483) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`
![Screenshot_20201228_170316](https://user-images.githubusercontent.com/44077252/103219024-d9b9f500-4931-11eb-87e9-74f23f811e4b.png)

**To Reproduce**
to reproduce this issue you can clone [this repo](https://github.com/amirhosseinak20/storybook_tutorial) on branch `new` and run
`
yarn install` `
yarn storybook
`

**Expected behavior**
![Screenshot_20201228_172527](https://user-images.githubusercontent.com/44077252/103219002-ca3aac00-4931-11eb-9b5a-5698c14ee55b.png)

**Comment by merceyz** [comment]
You need to unplug `open` by running `yarn unplug -AR open `

**Comment by amirhosseinak20** [comment]
Thanks this solved my problem. 
can you explain why this happened

**Comment by merceyz** [comment]
`open` contains a native binary that is used on macOS but native binaries can't be spawned within zip files so it needs to be unplugged
