### ISSUE TITLE
When I wrote a switch component in storybook. He would report an error

### ISSUE THREAD

**Issue by vayne1Q** [storybookjs/storybook#13546]
**Describe the bug**
When I wrote a switch component in storybook. He would report an error。
Such as:
```
ERROR in ./src/components/Switch/switch.tsx
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /Users/antd-with-ts/src/components/Switch/switch.tsx: Unexpected token, expected "(" (90:10)
catch (__react_docgen_typescript_loader_error) { }try {
  89 |     // @ts-ignore
> 90 |     switch.displayName = "switch";
```
**To Reproduce**

```
interface SwitchProps{}
export const Switch:FC<SwitchProps> = (props) => {
  return <>something</>
}
export default Switch
```

in switch.stories.tsx
```
storiesOf("Switch component", module).add('Switch", () => <Switch />);
```
This component will report errors when used in storybook

**Expected behavior**
Should nothing go wrong

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
Please paste the results of `npx sb@next info` here.

**Additional context**
Version of packages I use
1. "typescript": "4.0.3"
2. "@storybook/react": "^6.1.11",
3. "babel-loader": "8.1.0",

**Comment by radihuq** [comment]
Related: https://github.com/storybookjs/storybook/issues/11419

**Comment by vayne1Q** [comment]
> Related: #11419

thanks

**Comment by shilman** [comment]
closing as dupe to #11980
