### ISSUE TITLE
[examples/official-storybook] InternalError Too Much Recursion in docs tab

### ISSUE THREAD

**Issue by dominictwlee** [storybookjs/storybook#13543]
**Describe the bug**
When visiting docs tab for any of the Controls stories in the official storybook, an InternalError: Too much recursion occurs.

**To Reproduce**
in the `next` branch:
1. yarn bootstrap --core
2. yarn start in examples/official-storybook
3. navigate to any of the stories under Controls
4. Error appears in console and on screen.

**Expected behavior**
There shouldn't be an error.  I think this is related to the CyclicArgs story.

**Screenshots**
![image](https://user-images.githubusercontent.com/34794189/103438441-1126eb00-4c2b-11eb-87f9-c8511452e76d.png)

**System**
System:
    OS: Linux 5.8 Pop!_OS 20.10
    CPU: (4) x64 Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz
  Binaries:
    Node: 14.15.0 - ~/.nvm/versions/node/v14.15.0/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.0/bin/npm
  Browsers:
    Chrome: 87.0.4280.88
    Firefox: 84.0
  npmPackages:
    @storybook/eslint-config-storybook: ^2.4.0 => 2.4.0 
    @storybook/linter-config: ^2.5.0 => 2.5.0 
    @storybook/semver: ^7.3.2 => 7.3.2

**Additional context**

**Comment by shilman** [comment]
Are you still seeing this? Unable to repro on my machine

**Comment by dominictwlee** [comment]
Yep seems to be fine now with the latest next version.
