### ISSUE TITLE
Add-ons panel showing in docsMode on mobile

### ISSUE THREAD

**Issue by sarahbethfederman** [storybookjs/storybook#13547]
**Describe the bug**
The mobile navigation when in docs only mode still includes the addon panel in addition to the canvas and sidebar

**Expected behavior**
I expected the add-ons panel to be excluded in docsMode as it is on desktop

**Screenshots**
![Screenshot_20210104-170351](https://user-images.githubusercontent.com/5673114/103505640-ddf48e00-4eae-11eb-8116-9274efda614d.png)

**System**
Please paste the results of `npx sb@next info` here.

**Comment by Tomastomaslol** [comment]
Hi @sarahbethfederman!

I created a potential fix to this in: https://github.com/storybookjs/storybook/pull/14810.


https://user-images.githubusercontent.com/1872246/117087276-48043d80-ad92-11eb-9d6e-476907f80688.mp4


Please let me know if this is not the behavior you were looking for 🙂
