### ISSUE TITLE
Navigation between stories breaks when hiding 'Docs' Tab on one story.

### ISSUE THREAD

**Issue by seanryanuk** [storybookjs/storybook#13557]
**Describe the bug**
Given a set of basic stories, but one has been passed the following parameters in the default export:

```
parameters: {
  previewTabs: {
    "storybook/docs/panel": {
      hidden: true,
    }
  }
}
```

It is possible to reach the above example story's Docs tab by selecting the Docs tab in a different story then navigating to the above example. 

**To Reproduce**
1. Click on any story with a *Docs* tab.
2. Then, click on the story where the *Docs* tab should be hidden .
3. Note that the *Docs* tab is displayed after navigating to the new story, even though hidden is applied.
4. Hidden now stops the *Canvas* tab from being displayed, preventing changing view on said Story.

**Expected behavior**
When navigating to a story with a hidden *Docs* tab, from a previous story's *Docs* tab, that the *Canvas* is displayed instead of the *Docs* tab that should be hidden and disabled.

**Code snippets**
```
export default {
  title: "UI / Loading",
  component: Primary,
  parameters: {
    previewTabs: {
      "storybook/docs/panel": {
        hidden: true,
      },
    },
  },
};
```

**System**

- Environment Info:
  - Binaries:
    -  Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
    -  npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  -  npmPackages:
     -  @storybook/addon-a11y: ^6.1.11 => 6.1.11
     -  @storybook/addon-essentials: ^6.1.11 => 6.1.11
     -  @storybook/react: 6.1.11 => 6.1.11

**Additional context**
- Only have minimal, basic stories currently. There is only one that has had it's *Docs* tab hidden using the above approach.

**Comment by timesp** [comment]
I have the same problem

**Comment by mrmos** [comment]
in our case, we cannot click to the Canvas view if the Docs tab is the default view. Canvas only works if you select the tab and then hard-refresh the page.

**Comment by ndelangen** [comment]
This will get changed quite in 7.0 beta. The tabs are removed.
