### ISSUE TITLE
Storyshots found 0 stories when following tutorial

### ISSUE THREAD

**Issue by mivd7** [storybookjs/storybook#13550]
I'm following your tutorial on learnstorybook.com to learn how to use Storybook with React. I'm not sure whether this is a bug (though I have seen some issues on your Github here that look similar) or whether it's my own mistake but I don't know where else to ask this. I have followed each step in the tutorial exactly the way it's described and have reached the part about snapshot testing [on this page](https://www.learnstorybook.com/intro-to-storybook/react/en/simple-component/). 

I have a Task component and a Task.stories.js component, copied from the examples in the above mentioned tutorial. However after adding the 'storybook.test.js' file with the provided code and running the test with Jest, it fails with message: 'storyshots found 0 stories'. According to the tutorial the test should pass, with the output looking like this:
![task-testrunner](https://user-images.githubusercontent.com/38442626/103548424-117eea80-4ea6-11eb-90ab-8fcc6e2df514.png)

The code as it is at this point can be found in this repo: https://github.com/mivd7/storybook-tut

**Comment by jonniebigodes** [comment]
@mivd7 let me take a look and see what might be the issue here. Do you mind waiting a bit? Cloning the repo as i type this.

Stay safe

**Comment by mivd7** [comment]
@jonniebigodes thanks for checking it out, but I found it myself already. I forgot to import prop-types in the component itself, and that makes the snapshot test fail. When I fix the prop type error, by importing it, the storyshot test also runs and passes and I'm seeing the expected output. A bit confusing feedback from the test though but anyway I can now continue again. Thanks again and sorry for the trouble.

**Comment by jonniebigodes** [comment]
@mivd7 no worries. I was about to write an issue in your repo. But glad that you solved it. And no need to thank and no trouble at all.

Stay safe
