### ISSUE TITLE
Typo On Decorators Page

### ISSUE THREAD

**Issue by KoltonG** [storybookjs/storybook#13554]
**Describe the bug**
The last sentence of the first paragraph here https://storybook.js.org/docs/react/writing-stories/decorators#context-for-mocking has a typo. "to" is used twice.

**To Reproduce**

1. Go to https://storybook.js.org/docs/react/writing-stories/decorators#context-for-mocking
1. Look at the last sentence of the first paragraph of the `"Context" for mocking` chapter

**Expected behavior**
The removal of the extra "to" word.

**Screenshots**
![Screen Shot 2021-01-04 at 4 33 38 PM](https://user-images.githubusercontent.com/3606121/103577136-9c61e400-4eaa-11eb-9c9f-0cc7cf11835b.png)

**Comment by jonniebigodes** [comment]
@KoltonG thank you for catching the typo. If you're able, could you make a small pull request to address this and ping me and we'll get it fixed in no time.

Stay safe

**Comment by KoltonG** [comment]
Will do!

**Comment by darleendenno** [comment]
Closing this issue as it appears to be fixed ❤️
