### ISSUE TITLE
New Storybook Angular project fails: Could not find a default project in your Angular workspace.

### ISSUE THREAD

**Issue by bradfrost** [storybookjs/storybook#13553]
**Describe the bug**
I receive the following error when creating a new Angular Storybook project: 

```
 Error: Could not find a default project in your Angular workspace.
Set a defaultProject in your angular.json and re-run the installation.
```

**To Reproduce**

1. Run `npx sb init` and choose `ANGULAR` from options, or run `npx -p @storybook/cli sb init --type angular`
2. After the message `Adding Storybook support to your "Angular" app`, see the following error:

```
 Error: Could not find a default project in your Angular workspace.
Set a defaultProject in your angular.json and re-run the installation.
```

**Expected behavior**
The Angular project to be successfully installed

**Screenshots**
<img width="960" alt="Screen Shot 2021-01-04 at 2 10 32 PM" src="https://user-images.githubusercontent.com/383701/103572981-784ad680-4e9b-11eb-9e77-b79cc8e67912.png">

**System**
  System:
    OS: macOS 11.1
    CPU: (4) x64 Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz
  Binaries:
    Node: 14.5.0 - ~/.nvm/versions/node/v14.5.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v14.5.0/bin/npm
  Browsers:
    Chrome: 87.0.4280.88
    Firefox: 84.0.1
    Safari: 14.0.2

**Comment by ThibaudAV** [comment]
I'm not sure but did you execute the command in an existing project ?
https://storybook.js.org/docs/react/get-started/install
> Use the Storybook CLI to install it in a single command. **Run this inside your existing project’s root directory:**

**Comment by bradfrost** [comment]
Ah, thanks @ThibaudAV. I was expecting an empty Angular shell, but it makes sense that isn't Storybook's job.
