### ISSUE TITLE
Angular source code view in Storybook

### ISSUE THREAD

**Issue by SBSB007** [storybookjs/storybook#13555]
Hi storybook team,

I am wondering whether storybook support show the component code on the storybook site for the Angular project?
I want to show template code as well as ts code for a respective component.
I tried to use few add-ons like "addon-storysource" ,it is showing only storybook code but i need to show component code when user click on show code.

Thanks, any help or guidance is welcome.

**Comment by shilman** [comment]
Egads!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.0-alpha.25 containing PR #13740 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
