### ISSUE TITLE
IE11 not working out of the box with Alpha 6.2.10 and Vue 2

### ISSUE THREAD

**Issue by jameskoehlerkilleen** [storybookjs/storybook#13562]
**Describe the bug**
I took an existing project running 6.0.28 that was working with IE11. I updated to the latest alpha, 6.2.10, and used IE11 to test if it was working. The page did not load in IE11 with the latest alpha.

After not being able to figure out why, I created a project from scratch. This project also suffered from a syntax error in IE11.

When looking at vendors~main...bundle.js there is a lot of es6+ syntax in there. I found a lot of arrow functions and ... in the file.

**To Reproduce**
vue create test
cd test
npx sb@next init
npm run storybook

**Expected behavior**
IE11 support out of the box with Vue.

**Screenshots**
![image](https://user-images.githubusercontent.com/77016238/103675236-50b04880-4f45-11eb-9a5f-312d882e301b.png)
![image](https://user-images.githubusercontent.com/77016238/103675316-69206300-4f45-11eb-8f37-0f78b81947b4.png)

**System**
  System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 10.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 87.0.4280.88
    Edge: Spartan (44.19041.423.0), Chromium (87.0.664.66)
  npmPackages:
    @storybook/addon-actions: ^6.2.0-alpha.10 => 6.2.0-alpha.10
    @storybook/addon-essentials: ^6.2.0-alpha.10 => 6.2.0-alpha.10
    @storybook/addon-links: ^6.2.0-alpha.10 => 6.2.0-alpha.10
    @storybook/vue: ^6.2.0-alpha.10 => 6.2.0-alpha.10

**Comment by dutscher** [comment]
arrow funtion wont work in ie11 
![image](https://user-images.githubusercontent.com/14682/104327734-63012800-54eb-11eb-9576-741c9d56fbc0.png)
`var r = e => {}` means `var r = (e) => {}` means `var r = function(e){}` 
and the last is what ie11 can interpret.

cheers

**Comment by jameskoehlerkilleen** [comment]
> arrow funtion wont work in ie11
> ![image](https://user-images.githubusercontent.com/14682/104327734-63012800-54eb-11eb-9576-741c9d56fbc0.png)
> `var r = e => {}` means `var r = (e) => {}` means `var r = function(e){}`
> and the last is what ie11 can interpret.
> 
> cheers

As I stated previously, IE11 is supported and working for me in 6.0.28. If I run the update command to 6.2.0-alpha.10, then it doesn't work anymore for me.

As far as I'm aware, Storybook is still supporting IE11 in 6.2.x and should be working out of the box as it does today.

Is anyone else experiencing this issue? I updated using Windows and Mac OS with the same results.

**Comment by jackysee** [comment]
You can see it's from addon-docs -> prettier/parse-html.js

![image](https://user-images.githubusercontent.com/30516/105136627-f01c3080-5b2c-11eb-8b7d-99c388590285.png)

**Comment by jameskoehlerkilleen** [comment]
> You can see it's from addon-docs -> prettier/parse-html.js
> 
> ![image](https://user-images.githubusercontent.com/30516/105136627-f01c3080-5b2c-11eb-8b7d-99c388590285.png)

Thanks. As an update I tried with 6.2.0-alpha.16 and I am still seeing this issue.

**Comment by OktarinTentakel** [comment]
Exactly the same error for me with 6.1.15.

**Comment by jameskoehlerkilleen** [comment]
> Exactly the same error for me with 6.1.15.

The 6.1.x branch broke IE11 support. IE11 support was scheduled to be restored in 6.2.x branch.

**Comment by OktarinTentakel** [comment]
Alrighty. I' hoping for a near release of 6.2 then, because without ie11 I cannot port the storybook yet for production. Tough luck I guess. :D

**Comment by shilman** [comment]
¡Ay Caramba!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.0-beta.4 containing PR #14047 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Ta-da!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.21 containing PR #14047 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```
