### ISSUE TITLE
@storybook/angular: Cannot read property 'minify' of undefined

### ISSUE THREAD

**Issue by rhutchison** [storybookjs/storybook#13563]
**Describe the bug**

WARN TypeError: Cannot read property 'minify' of undefined
WARN     at getCommonConfig (node_modules\@angular-devkit\build-angular\src\webpack\configs\common.js:299:28)
WARN     at Object.getAngularCliParts (node_modules\@storybook\angular\dist\server\angular-cli_utils.js:83:30)
WARN     at Object.applyAngularCliWebpackConfig (node_modules\@storybook\angular\dist\server\angular-cli_config.js:134:40)
WARN     at Object.webpackFinal (node_modules\@storybook\angular\dist\server\framework-preset-angular-cli.js:10:33)
WARN     at node_modules\@storybook\core\dist\server\presets.js:259:28

Ref: https://github.com/angular/angular-cli/commit/eb30a92e8ad4bf27461010b1917d1fcffd10ff31#diff-f3bcbd6f6b0756d2178dd69396750fa742093fb7f4668ab284463c0ca348b032R393

**To Reproduce**

Install latest version of angular/angular-devkit and run storybook.

**Expected behavior**
Should not throw warning.

**System**
Environment Info:

  System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz   
  Binaries:
    Node: 14.15.3 - C:\Program Files\nodejs\node.EXE       
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.9 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 87.0.4280.88
    Edge: Spartan (44.19041.423.0), Chromium (87.0.664.66) 
  npmPackages:
    @storybook/addon-a11y: ^6.1.11 => 6.1.11 
    @storybook/addon-actions: ^6.1.11 => 6.1.11 
    @storybook/addon-docs: ^6.1.11 => 6.1.11 
    @storybook/addon-essentials: ^6.1.11 => 6.1.11         
    @storybook/addon-viewport: ^6.1.11 => 6.1.11 
    @storybook/angular: ^6.1.11 => 6.1.11 
    @storybook/react: ^6.1.11 => 6.1.11 

**Additional context**
I provided a fix to angular-devkit, but it's not likely to be merged https://github.com/angular/angular-cli/pull/19704 (See comments)

**Comment by ThibaudAV** [comment]
maybe we could complete this object https://github.com/storybookjs/storybook/blob/next/app/angular/src/server/angular-cli_config.ts#L129
with something like that? 
```
optimization: {
styles: {}
},
```

link :
https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_angular/src/webpack/configs/common.ts#L66

**Comment by shilman** [comment]
Jiminy cricket!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.0-alpha.18 containing PR #13704 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by BenLune** [comment]
Hi there,
I had a good experience trying Storybook in an nx workspace yesterday, but today, after upgrading to nx 12.3, I have this error :
ERR! => Could not get angular cli webpack config
Cannot read property 'minify' of undefined

I also created an [issue](https://github.com/nrwl/nx/issues/5657) at nrwl github

**Comment by shaklin-box8** [comment]
I have the same issue with v6.2.9

**Comment by thutinavaneethreddy** [comment]
If something is still looking around, here is what worked for me :

npm install webpack@5.36.2 --save-dev
npm install dotenv-webpack@6.0.4 --save-dev (This fixed "cannot read property 'get' of undefined" but gave a new issue about snapshots)
npm install html-webpack-plugin@5.3.1 --save-dev (This fixed snapshot issue)
In the build config in angular.json, change "optimization" : "false" to
"optimization": {
"styles": false,
"scrypts": false,
"fonts": false
}

This fixed the warning - "Cannot read property 'minify' of undefined"

P.S: I followed all these steps while on storybook 6.2.7 version
