### ISSUE TITLE
Storybook loads all the chunks defined in Webpack config on start, instead loading them on demand

### ISSUE THREAD

**Issue by dkozar** [storybookjs/storybook#13565]
Hi!

I'm not sure if this is a feature or a bug. 😅 

I'm working on a (React) component, using Storybook as environment.

The component I'm building is a large one, which should load some of it's code asynchronously on demand (as chunks).

I've configured the Webpack config in `main.js` by introducing the `webpackFinal` section. I converted the original Webpack entry, which is a simple array, to [advanced entry](https://webpack.js.org/guides/entry-advanced/), which is an object with named chunks:

![image](https://user-images.githubusercontent.com/1078403/103697315-a9103600-4f97-11eb-8d17-5a0a53e5a43f.png)

Please note the 2nd chunk named `foo` I've added.

When I run Storybook using `yarn storybook --debug-webpack`, I'm properly seeing both the `main` and a `foo` chunks defined:

![Snag_715beaa](https://user-images.githubusercontent.com/1078403/103697551-fbe9ed80-4f97-11eb-8081-dbccd461626f.png)

However, in the browser, I'm seeing the `foo` chunk being loaded on start (without my component initiating its load):

![image](https://user-images.githubusercontent.com/1078403/103697651-2045ca00-4f98-11eb-925d-820d95a8a8a8.png)

What I would expect is that only `main` chunk is loaded on start.

I see that Storybook preview iframe actually initiated the chunk to load (by adding the script tag to the end of its body):

![image](https://user-images.githubusercontent.com/1078403/103697826-5edb8480-4f98-11eb-9414-260917ca2979.png)

I'm wondering could this behaviour somehow be prevented, so chunks that are meant to be loaded on demand aren't initially loaded by Storybook?

Thanks! 😄

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
