### ISSUE TITLE
Root .babelrc not being read

### ISSUE THREAD

**Issue by istrupin** [storybookjs/storybook#13577]
**Describe the bug**
Storybook does not seem to respect my `.babelrc` file at the root of my project. When I copy/paste the `.babelrc` into my .storybook folder, it works as expected.

**To Reproduce**

1. Create `.babelrc file in project root`
2. Run `npm run storybook`
3. See output
4. Copy root level ` .babelrc` into `.storybook` directory
5. Run `npm run storybook`
6. See that output differs from step 3

**Expected behavior**
I expect storybook to honor my `.babelrc` file at the project root level.

**Screenshots**
Notice the pink background when `.babelrc` is in `.storybook`:
![image](https://user-images.githubusercontent.com/18174517/103954346-db857480-50f8-11eb-9b18-e2531e9b6779.png)

Notice no pink background and CSS error when `.babelrc` is not present:
![image](https://user-images.githubusercontent.com/18174517/103954438-1e474c80-50f9-11eb-9be1-2d12e32eb090.png)
 

**Code snippets**
contents of .babelrc:

```
{
    "presets": [
        "@babel/preset-env",
        [
            "@babel/preset-react",
            {"runtime": "automatic", "importSource": "@emotion/react"}
        ]
    ],
    "plugins": [
        "@emotion",
        "@babel/plugin-proposal-class-properties",
        "@babel/plugin-proposal-object-rest-spread"
    ]
}
```

contents of main.js from .storybook:

```
const path = require('path');
module.exports = {
    "stories": [
    "../src/**/*.stories.mdx",
    "../src/**/*.stories.@(js|jsx|ts|tsx)"
  ],
  "addons": [
    "@storybook/addon-links",
    "@storybook/addon-essentials"
  ],
  webpackFinal: async (config, { configType }) => {
    console.log(config.module.rules[0].use[0])
    config.module.rules.push({
      test: /\.scss$/,
      use: ['style-loader', 'css-loader', 'sass-loader'],
      include: path.resolve(__dirname, '../'),
    });
    return config;
  },
};


```
**System**
Environment Info:

  System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 15.5.0 - ~/.nvm/versions/node/v15.5.0/bin/node
    npm: 7.3.0 - ~/.nvm/versions/node/v15.5.0/bin/npm
  Browsers:
    Firefox: 84.0.1
    Safari: 14.0.2
  npmPackages:
    @storybook/addon-actions: ^6.2.0-alpha.10 => 6.2.0-alpha.10 
    @storybook/addon-essentials: ^6.2.0-alpha.10 => 6.2.0-alpha.10 
    @storybook/addon-links: ^6.2.0-alpha.10 => 6.2.0-alpha.10 
    @storybook/react: ^6.2.0-alpha.10 => 6.2.0-alpha.10 

**Additional context**

**Comment by shilman** [comment]
sounds like a bug to me. can you try `babel.config.js` or `babel.config.json` and see if either of those work?

**Comment by jbadan** [comment]
I experienced the same issue with storybook@6.2.0-beta.5. I also tried using a `babel.config.json` with the same results.

Relevant section of `main.js`:

```
        config.module.rules.push({
            test: /\.js$/,
            loader: 'babel-loader',
            exclude: /node_modules\/(?!(react-idle-timer)\/).*/,
        });
```

I also tried adding `options: { babelrc: true }` and `options: { babelrc: true, babelrcRoots: ['.', '{various attempts to get to root babelrc}']` without success.

I believe the problem could be due to using the babel-loader from storybook's node_modules instead of from my project's root node_modules.

**Comment by armandabric** [comment]
I'm facing the same problem. My root `babel.config.js` is ignored by storybook. 

As workaround I have merge my babel configuration with the storybook one:

```js
  babel: async (options) => {
    const babelConfig = require("./../babel.config.js");

    return { ...options, ...babelConfig };
  },
```

I'm using storybook v6.3.1.

**Comment by heyheyhello** [comment]
I'm trying to do the _opposite_ and cannot for the life of me get Storybook to only use `./storybook/.babelrc.json` and ignore the root config. I've tried specifying my options directly in `main.js` with `babel: () => ({ ... })` and have used `babelrc: false` and multiple attempts of `babelrcRoots` to no avail. It's stange how difficult it is to tell Babel to use an alternative config... I think I'll settle for a shell script that deletes/renames the root config to something else. Yikes. 

When the situation is better understood it'd be lovely to see https://storybook.js.org/docs/react/configure/babel/ updated with examples

**Comment by ndelangen** [comment]
>  I've tried specifying my options directly in `main.js` with `babel: () => ({ ... })`

@heyheyhello your approach should work, do you have a reproduction you could share?

**Comment by erikpukinskis** [comment]
I'm having the same issue (Storybook 6.4.12). Nothing I do seems to get Storybook to pick up the root babel config.

I put up a branch exhibiting the behavior here: https://github.com/super-project-world/design-system/tree/storybook-with-babel

Weirdly, Storybook _does_ pick up the config if I put it in `.storybook`, and make it a `.babelrc` (json) file instead of a `babel.config.js`.

That's not quite what I want though... I'd like the config to be in the project root so that I can use it for other build steps.

**Comment by shilman** [comment]
@erikpukinskis Have you tried `babelModeV7`? https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#babel-mode-v7

**Comment by erikpukinskis** [comment]
@shilman That did seem to work in my demo repository, thanks!

And for some reason in my working app, it started magically reading the root `.babelrc` even without `babelModeV7` so... I'm not sure what's happening there, but I won't complain!

**Comment by ashblue** [comment]
@erikpukinskis was having trouble with this issue in NX Storybook. Was losing my mind as to why some additional babel plugins weren't being picked up.
