### ISSUE TITLE
Versioned Documentation

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#1357]
## why

We need a way to document preview releases of storybook. We may also want docs for people using old versions.

## what

- [ ] Docs for a preview release, clearly labeled as preview with disclaimers and pointers to the main docs
- [ ] Docs for the latest stable release of Storybook, statically hosted at https://storybook.js.org
- [ ] Docs for previous minor releases of Storybook, with disclaimers and pointers to the main docs

**Comment by shilman** [comment]
Here's a proposal: https://gist.github.com/shilman/6de9d40d9c8fb33d301060b8601b8c36

**Comment by smooJitter** [comment]
You all are moving fast. It would be nice (on the readme.md at statement about upgrading. I have had a fair share of problems with configuring and installing storybook. Now that I have it working. I am afraid to upgrade the cli. Fortunately, Im only using storybook on a ui test app. I found it easier reinstall storybook, start a new project, then copy over the stories. It looks like you are posting new releases ever few days. The version I have works fine. I'd like to keep up with the changes. After more than a year, I've finally gotten storybook to work for me. THANKS!

**Comment by shilman** [comment]
@smoojitter All of the releases since 3.0 have been backwards compatible unless we messed up. Whenever we make changes that require modifications on your side, we have been updating `MIGRATION.md`. But we'll do a better job documenting the changes and all suggestions are welcome. Thanks!

**Comment by danielduan** [comment]
is this still a valid issue @Hypnosphi @ndelangen? wouldn't we be able to deploy branch builds to netlify for each release and keep them versioned?

**Comment by Hypnosphi** [comment]
We already do, but we haven't any links to them
E.g. docs for current alpha (master) https://storybooks.netlify.com/

**Comment by ndelangen** [comment]
As @Hypnosphi describes, this issue has become:
We need a method for users to be able to select an older version of the docs.
We can use netlify links for that purpose. But it needs a UI & links on the docs.

**Comment by tkharuk** [comment]
Oh, I've just faced this, where my org uses **v5** but all I can find is **v6** examples.
Even though I know the same functionality exists in **v5** but I just don't remember how to make it work :(

**Comment by ajbarry** [comment]
Likewise, I am attempting to learn how to use Storybook, but I am limited to the version currently used in my org.
I took a look at the netlify links and while the version in the sidebar header is 5.1 all of the sub pages are currently not found:

https://storybooks.netlify.app/docs/basics/introduction/

@Hypnosphi @ndelangen ... if versioned documentation is already available, could you please provide an example of the netlify link to a *historical* version?

**Comment by jonniebigodes** [comment]
@ajbarry see if [this](https://storybook.js.org/docs/react/workflows/faq#is-it-possible-to-browse-the-documentation-for-past-versions-of-storybook) helps in your case.

**Comment by ajbarry** [comment]
Ah... thank you so much @jonniebigodes ... it does.

**Comment by jonniebigodes** [comment]
Glad that helps out.

**Comment by jonniebigodes** [comment]
@shilman closing this issue as we already have versioned documentation available to the community.
