### ISSUE TITLE
Provide a new theme variable for toolbar icon hover color

### ISSUE THREAD

**Issue by thesobercoder** [storybookjs/storybook#13578]
**Is your feature request related to a problem? Please describe**
Currently, the `ThemeVars` interface accepts a `colorSecondary` parameter which is used to color the selected item on the left sidebar and the toolbar icons hover state. However, in my custom theme I need the toolbar icon hover color to be something diffrerent because I'm using the same color for `barBg` and `colorSecondary`. 

```
export interface ThemeVars { 
   colorSecondary?: string;
   ...
}
```

**Describe the solution you'd like**
Create a new property in `ThemeVars` interface to accept the hover color.

```
export interface ThemeVars { 
   barHover?: string;
   ...
}
```

**Describe alternatives you've considered**
For the time being, I'm using a different color `colorSecondary` as a workaround, but that is not making the theme look nice and what I exactly want.

**Are you able to assist to bring the feature to reality?**
Yes

**Comment by Tomastomaslol** [comment]
Hi @thesobercoder! 

Does it make sense to you to also introduce a variable to control the `barIconActiveColor`? Is this implementation suitable for your use case? 🙂  

**Suggested implementation:**

```js
const EXAMPLE_THEME = create({
  base: 'light',
  barIconHoverColor: 'red',
  barIconActiveColor: 'green',
});

```

**Would result in:**

<img width="283" alt="Screen Shot 2021-05-18 at 1 22 22 pm" src="https://user-images.githubusercontent.com/1872246/118585472-4e57d800-b7dc-11eb-89d7-3337d159442f.png">

**Comment by thesobercoder** [comment]
@Tomastomaslol Yeah this should work.

**Comment by Tomastomaslol** [comment]
Great! I just updated the documentation and requested a PR review. Hopefully, this should be available for you fairly soon! 🙂

**Comment by ndelangen** [comment]
I don't think we should add specific hover colors for specific elements/components to our ThemeVars.

I respect you want to theme storybook and customize it to suit your wishes, but every bit of customization we allow adds complexity for us. In this case, I don't think the costs outweighs the benefits.
