### ISSUE TITLE
Storybook Vue stories don't seem to be transpiled for IE 11

### ISSUE THREAD

**Issue by wesgro** [storybookjs/storybook#13588]
**Describe the bug**
Storybook does not seem to transpile story files themselves which results in broken stories in ie 11.

I've reproduced this using `sb init` in a fresh vue cli project.

**To Reproduce**

1. checkout https://github.com/wesgro/broken-ie11-storybook
2. `yarn install && yarn storybook`
3. Open the resulting server in your favorite Ie 11 environment
4. Go to the `Button Works in Ie 11` story and see the button render
5. Go to the `Button broken in ie 11` story and see IE complain about the destructured object

**Expected behavior**
babel transpiles the stories themselves

**Screenshots**
<img width="1535" alt="broken-button" src="https://user-images.githubusercontent.com/595567/104072280-c9bad480-51bf-11eb-9b7b-696e737a04a9.png">
<img width="1515" alt="working-button" src="https://user-images.githubusercontent.com/595567/104072289-cd4e5b80-51bf-11eb-9211-db11d204909e.png">

**Code snippets**
The stories that are being mounted
```
const Template = (args, { argTypes }) => ({
  props: Object.keys(argTypes),
  components: { MyButton },
  template: `
  <my-button v-bind="$props">
    <template #default=attrs>
    <span v-bind="attrs.attrs">I am not here</span>
    </template>
  </my-button>`,
});

// This breaks because of object destructuring not being transpiled
const TemplateBroken  = (args, { argTypes }) => ({
  props: Object.keys(argTypes),
  components: { MyButton },
  template: `
  <my-button v-bind="$props">
    <template #default={attrs}>
    <span v-bind="{attrs}">I am not here</span>
    </template>
  </my-button>`,
});
```

**System**
```
❯ npx sb@next info

Environment Info:

  System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 14.15.4 - ~/.volta/tools/image/node/14.15.4/bin/node
    Yarn: 1.22.4 - ~/.volta/tools/image/yarn/1.22.4/bin/yarn
    npm: 6.14.10 - ~/.volta/tools/image/node/14.15.4/bin/npm
  Browsers:
    Chrome: 87.0.4280.141
    Safari: 14.0
  npmPackages:
    @storybook/addon-actions: ^6.1.11 => 6.1.11 
    @storybook/addon-essentials: ^6.1.11 => 6.1.11 
    @storybook/addon-links: ^6.1.11 => 6.1.11 
    @storybook/vue: ^6.1.11 => 6.1.11 
```

**Comment by ndelangen** [comment]
Storybook 7.0 won't support IE11 anymore.

6.5 won't receive updates other than critical security issues, this won't get fixed.
