### ISSUE TITLE
Documentation should show all available parameters

### ISSUE THREAD

**Issue by bkjohnson** [storybookjs/storybook#13587]
**Is your feature request related to a problem? Please describe**
Yes. The documentation for how to use/configure storybook can be lacking at times. As an example, imagine that you wanted to set the `Docs` tab to be the default instead of `Canvas`. The solution is to include `viewMode: 'docs'` in the `paramters` object in `.storybook/preview.js`, but I was unable to find this answer in the documentation. Searching for `viewmode` in the Storybook docs yields no results, and the only [documentation on global parameters](https://storybook.js.org/docs/react/writing-stories/parameters#global-parameters) doesn't mention it.

(If I've overlooked documentation for this somewhere, please let me know. I'd love to find it!)

**Describe the solution you'd like**
I think an ideal solution would be an automatically generated list of _all_ available parameters, what values they accept, and a description of what they do.

**Describe alternatives you've considered**
Manually updating a markdown file each time a new parameter is added somewhere.

**Are you able to assist to bring the feature to reality?**
Yes, if the ideal solution I described (or something close to it) can be done in an hour or two in my free time. If this isn't feasible to do by myself, then I'm willing to assist as well.

**Additional context**

Example of the pain point: https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/569#discussion_r554141248

**Comment by tema1411** [comment]
@bkjohnson Totally agree with you. The documentation really doesn't answer a lot of questions

**Comment by tema1411** [comment]
@bkjohnson but i think this problems is know. You can write you propostion in this issue 
https://github.com/storybookjs/storybook/issues/13499

**Comment by treksn** [comment]
An interface, where all available parameters are defined, would already help a lot. `[key: string]: any;` should be avoided if possible.

**Comment by kylegach** [comment]
Closing in favor of #17243. I realize this one came first, but the other is not specific to parameters and thus more in line with our vision. Thanks!
