### ISSUE TITLE
Docs: add a technical reference with types

### ISSUE THREAD

**Issue by kaelig** [storybookjs/storybook#13584]
**Is your feature request related to a problem? Please describe**
When building addons, adding decorators, or toolbars… I always feel like I need to look at Storybook's source or look for how other people have solved it in their projects.

**Describe the solution you'd like**
I'd love to have a technical reference that's very thorough and also contains all types available publicly. Something like TypeDoc would be great (it doesn't have to be pretty, just thorough).

**Are you able to assist to bring the feature to reality?**
I'm happy to review pull requests!

**Comment by jonniebigodes** [comment]
@kaelig sounds good to me. If you don't mind and add the content of this issue to the pinned that i've setup (#13499) we could go from there. Sounds good? Looking forward to work with you on this.

Stay safe

**Comment by kaelig** [comment]
Sounds good, thank you!
