### ISSUE TITLE
Clean CRA chakra-ui typescript template + Storybook broken

### ISSUE THREAD

**Issue by dominictwlee** [storybookjs/storybook#13583]
**Describe the bug**
A clean install of CRA with chakra-typescript template and npx sb init results in build failure on start-storybook.

**To Reproduce**

1. npx create-react-app chakra-cra-storybook --template @chakra-ui/typescript
2. npx sb init
3. rm -rf node_modules && rm yarn.lock && yarn
4. yarn storybook
5. See error below.

**Expected behavior**
Storybook should start without errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/34794189/104052311-6fcb0680-51e1-11eb-868b-b63bc07b066e.png)
![image](https://user-images.githubusercontent.com/34794189/104052349-7eb1b900-51e1-11eb-8330-aabe2bfe1331.png)

**System**
Environment Info:
  System:
    OS: Linux 5.8 Pop!_OS 20.10
    CPU: (4) x64 Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz
  Binaries:
    Node: 14.15.0 - ~/.nvm/versions/node/v14.15.0/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.0/bin/npm
  Browsers:
    Chrome: 87.0.4280.88
    Firefox: 84.0.2
  npmPackages:
    @storybook/addon-actions: ^6.1.11 => 6.1.11 
    @storybook/addon-essentials: ^6.1.11 => 6.1.11 
    @storybook/addon-links: ^6.1.11 => 6.1.11 
    @storybook/node-logger: ^6.1.11 => 6.1.11 
    @storybook/preset-create-react-app: ^3.1.5 => 3.1.5 
    @storybook/react: ^6.1.11 => 6.1.11

**Comment by dominictwlee** [comment]
I think this might be related to `@storybook/preset-create-react-app`. Removing it from addons seems to fix it.

**Comment by michal-kurz** [comment]
I'm running into the same issue, unable to find other fixes. Removing `@storybook/preset-create-react-app` preset did make the errors go away. What are the downsides to not running the preset?

**Comment by TechieQian** [comment]
> I'm running into the same issue, unable to find other fixes. Removing `@storybook/preset-create-react-app` preset did make the errors go away. What are the downsides to not running the preset?

If your build can run without preset that means your project has all the right dependencies to build the project already. The downside is the build may have discrepancy from your apps that may have been created by CRA. If you dont use CRA to bootstrap your apps then its fine.

**Comment by yjkimjunior** [comment]
> I'm running into the same issue, unable to find other fixes. Removing `@storybook/preset-create-react-app` preset did make the errors go away. What are the downsides to not running the preset?

my app is a CRA app and yet this was the solution to my woes...

**Comment by dominictwlee** [comment]
Refer to #13593
