### ISSUE TITLE
Decorators don't work with svelte

### ISSUE THREAD

**Issue by callmeberzerker** [storybookjs/storybook#13598]
**Describe the bug**
Decorators error out and you can not write a story that uses decorators.

**To Reproduce**

1. Write any svelte component.
2. Write the following story

```
import TextField from 'src/shared/forms/TextField.svelte'

export default {
  title: 'TextField',
  component: TextField,
  decorators: [
    (Story) => (
      <div>
        <Story />
      </div>
    ),
  ],
}

const Template = (args) => ({
  Component: TextField,
  props: args,
})

export const Default = Template.bind({})

```
3. Start storybook and see the error which is:

```
You may need an additional loader to handle the result of these loaders.
|   component: TextField,
|   decorators: [function (Story) {
>     return <div>
|         <Story />
|       </div>;
```

**Expected behavior**
Decorators should work.

**Comment by j3rem1e** [comment]
Svelte doesn't support jsx so you can't write decorator like in your example.

See the documentation here on how to write decorator for svelte: https://storybook.js.org/docs/svelte/writing-stories/decorators

**Comment by phated** [comment]
Additionally, new Svelte decorator support was added in https://github.com/storybookjs/storybook/pull/13785 - try it out in the alpha release! `npx sb@next upgrade --prerelease`

**Comment by callmeberzerker** [comment]
Thank you I will try it out asap!
