### ISSUE TITLE
ember: jsondoc extraction does not set 'type' property used for controls-autogeneration/automatic argType inference

### ISSUE THREAD

**Issue by crixx** [storybookjs/storybook#13594]
**Describe the bug**
For ember, the autogeneration of controls does relay on YUI doc producing a jsondoc-json file. During the mapping of the jsondoc-json to the defined structure expected by the automatic argType inference, the type is not set.

**To Reproduce**

1. clone the repo on branch `next`
2. run the bootstrap command `yarn bootstrap --core`
3. cd to ember-cli
4. run `yarn`
5. create a component that uses YUI doc to specify `@type` of a boolean property without `@default` i.e. defaultValue
6. run `yarn storybook`
7. checkout the story with your component, the `controls` tab will no correctly show the types of the arguments although specified in YUI doc

**Expected behavior**
The `controls` tab should show the controls with the correct type

**Actual Structure of the jsondoc-mapping**
````js
return componentDoc.attributes.arguments.reduce((acc, prop) => {
    acc[prop.name] = {
      name: prop.name,
      defaultValue: prop.defaultValue,
      description: prop.description,
      table: {
        defaultValue: { summary: prop.defaultValue },
        type: {
          summary: prop.type,
          required: prop.tags.length ? prop.tags.some((tag) => tag.name === 'required') : false,
        },
      },
    };
    return acc;
  }, {});
````
**Expected Structure of the jsondoc-mapping from the docs**
https://storybook.js.org/docs/react/api/argtypes
````js
const argTypes = {
  label: {
    name: 'label',
    type: { name: 'string', required: false },
    defaultValue: 'Hello',
    description: 'demo description',
    table: {
      type: { summary: 'string' },
      defaultValue: { summary: 'Hello' },
    },
    control: {
      type: 'text'
    }
  }
}
````

thus proposed change:

````js
return componentDoc.attributes.arguments.reduce((acc, prop) => {
    acc[prop.name] = {
      name: prop.name,
      type: { name: prop.type, required: prop.tags.length ? prop.tags.some((tag) => tag.name === 'required') : false },
      defaultValue: prop.defaultValue,
      description: prop.description,
      table: {
        defaultValue: { summary: prop.defaultValue },
        type: {
          summary: prop.type,
        },
      },
    };
    return acc;
  }, {});
````

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid.

Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
