### ISSUE TITLE
Pass action function instead of default value for callback props

### ISSUE THREAD

**Issue by krzempekk** [storybookjs/storybook#13615]
**Is your feature request related to a problem? Please describe**
In React, it is impossible to get Actions addon to work with callback props that have default value set, like in this minimal example:
```js
export const ClickableCard = ({ text, onClick }) => (
    <button onClick={onClick}>{text}</button>
);

ClickableCard.propTypes = {
    text: PropTypes.string,
    onClick: PropTypes.func,
};

ClickableCard.defaultProps = {
    onClick: _.noop,
};
```
Global config for Actions addon is as follows:
```
actions: { argTypesRegex: '^on[A-Z].*' }
```
But action never get passed to component that way, default value defined in PropTypes is passed instead.

Our storybook version is 6.1.11.

**Describe the solution you'd like**
If action is defined, I would expect action function to be passed instead of default value.

**Describe alternatives you've considered**
1. Removing default prop value from component itself - but default value is needed in some cases.
2. Use other way to present callback result - but I would prefer to use Actions addon, since it is created for this use case

**Are you able to assist to bring the feature to reality?**
yes, I can...

**Comment by Sm1t** [comment]
Same issue, version 6.2.0-alpha.20
The solution proposed by the author of the issue looks logical

**Comment by shilman** [comment]
Closing as duplicate to #12120 which is fixed in the latest alpha

**Comment by darkowic** [comment]
@shilman can you actually close this issue? :)
