### ISSUE TITLE
Issue with generated sourcemaps via source-loader

### ISSUE THREAD

**Issue by ashleynolan** [storybookjs/storybook#13616]
**Describe the bug**
We've hit an issue when upgrading our repo to the latest version of `@storybook/vue`. After going through the releases it appears the issue is linked to a [change in source-loader](https://github.com/storybookjs/storybook/pull/12277) which looks like it was [introduced in v6.1.0-alpha.21](https://github.com/storybookjs/storybook/blob/next/CHANGELOG.md#610-alpha21-october-8-2020).

I've pasted the error log below, but essentially it looks like the sourcemap being generated isn't being converted to JSON properly – when logged via `console`, we see a `SourceMapGenerator` object, rather than just a JSON object – which is why we are seeing `"version" is a required argument` – as that argument doesn't exist until the sourcemap is parsed properly into JSON.

**To Reproduce**

I've made a [branch of our repo](https://github.com/justeat/fozzie-components/tree/package-updates) which you can checkout to reproduce the issue.

1. Checkkout 'fozzie-components' repo ([package-updates branch](https://github.com/justeat/fozzie-components/tree/package-updates))
1. Run `yarn` (or NPM) to install packages at the root of the repo.
1. Run `yarn storybook:build` at the root of the repo to build storybook.
1. See error.

Note that if you downgrade to `alpha.20` [in this file](https://github.com/justeat/fozzie-components/blob/package-updates/packages/storybook/package.json#L16-L20), the build successfully completes.

**Expected behavior**
Storybook should build successfully.

**Error log:**

```sh
92% chunk asset optimization TerserPluginERR! => Failed to build the preview                                                                                                                                                               e @justeat/storybook: ERR! "version" is a required argument.                                                                                                                                                                                  e @justeat/storybook: (node:6368) UnhandledPromiseRejectionWarning: Error: "version" is a required argument.                                                                                                                                  n @justeat/storybook:     at Object.getArg (/_je/ui/components/fozzie-components/node_modules/source-map/lib/util.js:24:11)                                                                                                m @justeat/storybook:     at new BasicSourceMapConsumer (/_je/ui/components/fozzie-components/node_modules/source-map/lib/source-map-consumer.js:294:22)                                                                   d @justeat/storybook:     at new SourceMapConsumer (/_je/ui/components/fozzie-components/node_modules/source-map/lib/source-map-consumer.js:22:7)                                                                          = @justeat/storybook:     at SourceMapSource.node (/_je/ui/components/fozzie-components/node_modules/webpack-sources/lib/SourceMapSource.js:32:62)
@justeat/storybook:     at ReplaceSource.node (/_je/ui/components/fozzie-components/node_modules/webpack-sources/lib/ReplaceSource.js:82:27)
@justeat/storybook:     at CachedSource.node (/_je/ui/components/fozzie-components/node_modules/webpack-sources/lib/CachedSource.js:18:24)
@justeat/storybook:     at ReplaceSource.node (/_je/ui/components/fozzie-components/node_modules/webpack-sources/lib/ReplaceSource.js:82:27)
@justeat/storybook:     at /_je/ui/components/fozzie-components/node_modules/webpack-sources/lib/ConcatSource.js:59:50
@justeat/storybook:     at Array.map (<anonymous>)
@justeat/storybook:     at ConcatSource.node (/_je/ui/components/fozzie-components/node_modules/webpack-sources/lib/ConcatSource.js:58:63)
@justeat/storybook:     at ConcatSource.proto.sourceAndMap (/_je/ui/components/fozzie-components/node_modules/webpack-sources/lib/SourceAndMapMixin.js:29:18)
@justeat/storybook:     at CachedSource.sourceAndMap (/_je/ui/components/fozzie-components/node_modules/webpack-sources/lib/CachedSource.js:58:31)
@justeat/storybook:     at TerserPlugin.taskGenerator (/_je/ui/components/fozzie-components/node_modules/@storybook/core/node_modules/terser-webpack-plugin/dist/index.js:198:23)
@justeat/storybook:     at taskGenerator.next (<anonymous>)
@justeat/storybook:     at /_je/ui/components/fozzie-components/node_modules/@storybook/core/node_modules/terser-webpack-plugin/dist/index.js:455:49
@justeat/storybook:     at /_je/ui/components/fozzie-components/node_modules/@storybook/core/node_modules/p-limit/index.js:23:31
@justeat/storybook: (node:6368) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**

```sh
Environment Info:

  System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 12.19.1 - /usr/local/bin/node
    Yarn: 1.19.1 - ~/.npm-packages/bin/yarn
    npm: 6.14.8 - ~/.npm-packages/bin/npm
  Browsers:
    Chrome: 87.0.4280.141
    Firefox: 84.0.1
    Safari: 14.0.2
  npmPackages:
    @storybook/storybook-deployer: 2.8.7 => 2.8.7
```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1199622255231368/1200019872690738) by [Unito](https://www.unito.io/learn-more)

**Comment by ashleynolan** [comment]
Is there any update for this issue? This is currently blocking being able to upgrade, so would be good to get some thoughts (we're happy to raise a PR to help fix the issue too with some help).

**Comment by shilman** [comment]
Sorry for the slow reply. It must be https://github.com/storybookjs/storybook/pull/12277 ... should we just revert it? I don't have time to debug it. Unless you have a fix in mind... 🧐

**Comment by ashleynolan** [comment]
If you could revert it and then we can look to patch the feature in a separate PR if that sounds ok?

**Comment by oliversturm** [comment]
I realize that OP had this issue with Vue, but I thought I'd add some information anyway because I believe I'm encountering the same (or a very similar)  issue with React. This happened after I updated an old project, and I added `@storybook/preset-create-react-app` to my list of addons (I was prompted to do so by a startup warning). Suddenly I saw errors like the following on the console when starting storybook, and no stories were detected.

```
WARNING in ./stories/Test.stories.js
Module build failed (from ./node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js):
Error: "version" is a required argument.
    at Object.getArg (/home/sturm/git/myproject/node_modules/@pmmmwh/react-refresh-webpack-plugin/node_modules/source-map/lib/util.js:24:11)
    at /home/sturm/git/myproject/node_modules/@pmmmwh/react-refresh-webpack-plugin/node_modules/source-map/lib/source-map-consumer.js:207:28
    at async Object._loader (/home/sturm/git/myproject/node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js:81:9)
 @ \.)(?=.)[^/]*?\.stories\.js)$ (./stories sync nonrecursive ^\.\/(?:(?!\.)(?=.)[^/]*?\.stories\.js)$) ./Test.stories.js
 @ ./.storybook/generated-stories-entry.js
 @ multi ./node_modules/@pmmmwh/react-refresh-webpack-plugin/client/ReactRefreshEntry.js ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/storybook-init-framework-entry.js ./node_modules/@storybook/addon-docs/dist/frameworks/common/config.js-generated-other-entry.js ./node_modules/@storybook/addon-docs/dist/frameworks/react/config.js-generated-other-entry.js ./node_modules/@storybook/addon-links/dist/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-actions/dist/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-actions/dist/preset/addArgs.js-generated-other-entry.js ./node_modules/@storybook/addon-backgrounds/dist/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-backgrounds/dist/preset/addParameter.js-generated-other-entry.js ./.storybook/preview.js-generated-config-entry.js ./.storybook/generated-stories-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined ./node_modules/react-dev-utils/webpackHotDevClient.js
```

After some tests, it turned out I was able to work around this problem by removing `@storybook/preset-create-react-app` from the addon list again. Everything seems to work fine without that preset addon - strange but true.

Oh, and in a newly generated test project I don't see the problem at all. That was my first idea - I created that test project with `create-react-app`, added storybook with `sb init`, then carefully compared the configuration, dependency versions and everything else I could think of, with my old existing project. To no avail - the new test project worked fine, my old one didn't.

I hope this information can somehow be useful in tracking down the source of the issue. I'll be working without the preset plugin for the time being.

**Comment by shilman** [comment]
@ankon any thoughts on this? i'm planning to revert the PR for now

**Comment by shilman** [comment]
ZOMG!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.0-beta.14 containing PR #14199 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
