### ISSUE TITLE
Should @storybook/addon-notes and @storybook/addon-info be used?

### ISSUE THREAD

**Issue by Vadorequest** [storybookjs/storybook#13623]
I'm a bit confused regarding the documentation of:
- https://www.npmjs.com/package/@storybook/addon-info
- https://www.npmjs.com/package/@storybook/addon-notes

Their link to github is broken (from npm):
- https://github.com/storybookjs/storybook/tree/master/addons/info

Are they built-in? Do they need to be installed manually? Is there a visual example/demo of how it's displayed?

**Comment by jonniebigodes** [comment]
@Vadorequest those two addons you mentioned are now deprecated and now active development is being done to them. The Storybook [Docs addon](https://github.com/storybookjs/storybook/tree/master/addons/docs) which is part of the [essentials package](https://storybook.js.org/docs/react/essentials/introduction) should be used in favor of them.

Stay safe

**Comment by Vadorequest** [comment]
Thank you!
