### ISSUE TITLE
Styles get applied incorrectly in dev mode when using with monorepo

### ISSUE THREAD

**Issue by dandel10n** [storybookjs/storybook#13620]
When using storybook with monorepo structure (having different packages under one root project) and using different versions of one npm package in different packages, css styles overwrite each other. Styles are getting built as expected in production mode.

1. Clone https://github.com/dandel10n/storybook_monorepo_sample
2. Build the project with `yarn`
3. Run the storybook with `yarn storybook:serve`
4. You should see two components which both use one `@justeat/f-button` npm package/component and should look like this:
![Screen Shot 2021-01-12 at 14 50 40](https://user-images.githubusercontent.com/19548183/104330176-a35da780-54e5-11eb-9d67-166ecd4557f1.png)
![Screen Shot 2021-01-12 at 14 50 47](https://user-images.githubusercontent.com/19548183/104330196-a789c500-54e5-11eb-943f-467380a708d0.png)
5. Go to packages/f-user-message/package.json and change `@justeat/f-button` version to 0.4.1 (the same as in f-alert component)
6. Run `yarn` again to apply the changes
7. Restart storybook with `yarn storybook:serve`
8. Check that styles for button in f-alert now look different:
![Screen Shot 2021-01-12 at 15 07 02](https://user-images.githubusercontent.com/19548183/104332242-e15bcb00-54e7-11eb-9131-ab69705b91dc.png)

**Expected behavior**
Styles from different versions of one npm package  don't interfere with each other in separate components

**System**
Environment Info:

  System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
  Binaries:
    Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v12.14.1/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.14.1/bin/npm
  Browsers:
    Chrome: 87.0.4280.141
    Firefox: 84.0.1
    Safari: 13.1.2

**Comment by dandel10n** [comment]
Hi guys, could somebody advise me on this issue?

**Comment by kevinrodrigues** [comment]
Hi, as @xander-marjoram & @dandel10n mentioned we've still got an issue with this. Could you suggest a work around or point us in the right direction so we can work out a fix for this issue please.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
