### ISSUE TITLE
 not resolving .d.ts files from node_modules 

### ISSUE THREAD

**Issue by TypicalFence** [storybookjs/storybook#13629]
Storybooks weebpack refuses to resolve .d.ts files from the node_modules folder. In my case its a module that is just a d.ts file.
I get the following error:

```
ERROR in ./src/stories/button.component.ts
Module not found: Error: Can't resolve '@fortawesome/fontawesome-common-types' in '/home/fence/code/story-book-test/src/stories'
```

This is probably related to https://github.com/storybookjs/storybook/issues/8961

**To Reproduce**
I tried reproducing the issue in the following minimal example: https://github.com/TypicalFence/storybook-angular-bug-thing

**System**
```
Environment Info:

  System:
    OS: Linux 5.6 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
  Binaries:
    Node: 12.18.4 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.6 - /usr/local/bin/npm
  Browsers:
    Firefox: 84.0.2
  npmPackages:
    @storybook/addon-actions: ^6.1.14 => 6.1.14
    @storybook/addon-essentials: ^6.1.14 => 6.1.14
    @storybook/addon-links: ^6.1.14 => 6.1.14
    @storybook/angular: ^6.1.14 => 6.1.14
```

**Comment by anrusina** [comment]
I have same issue, were flyteidl.d.ts file is refused to be seen by storybook.

    "@storybook/addon-actions": "^6.4.19",
    "@storybook/addon-essentials": "^6.4.19",
    "@storybook/addon-interactions": "^6.4.19",
    "@storybook/addon-links": "^6.4.19",
    "@storybook/react": "^6.4.19",
    "@storybook/testing-library": "^0.0.9",

nodejs 14.18.3
yarn 1.22.17

```
module.exports = {
  stories: [
    "../src/**/*.stories.mdx",
    "../src/**/*.stories.@(js|jsx|ts|tsx)"
  ],
  addons: [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/addon-interactions"
  ],
  framework: "@storybook/react",
  webpackFinal: async (config, { configType }) => {
    config.resolve.modules = [
      "src",
      "node_modules",
    ]
    return config;
  }
}
```

**Comment by xithalius** [comment]
Any updates on this? Still facing the same issue.
