### ISSUE TITLE
Documentation about `argTypes` hard to find

### ISSUE THREAD

**Issue by Vadorequest** [storybookjs/storybook#13636]
I'm haveing a hard time with `argTypes`. I waste a lot of time going through the documentation when I try to do things.

For instance, I wanted to disable a property, I tried:

```tsx

// Worked but I lost the field in the doc and I don't want that
export default {
  title: 'Next Right Now/Form/Btn',
  component: Btn,
  argTypes: {
    children: {
      table: {
        disable: true,
      },
    },
  }
} as Meta;

// Didn't work
export default {
  title: 'Next Right Now/Form/Btn',
  component: Btn,
  argTypes: {
    children: {
      canvas: {
        disable: true,
      },
    },
  }
} as Meta;

// Didn't work
export default {
  title: 'Next Right Now/Form/Btn',
  component: Btn,
  argTypes: {
    /**
     * @readonly
     */
    children: {},
  }
} as Meta;

// Worked and does exactly what I wanted
export default {
  title: 'Next Right Now/Form/Btn',
  component: Btn,
  argTypes: {
    children: {
      control: {
        disable: true,
      },
    },
  }
} as Meta;
```

Is there a single source of truth regarding all options in `argTypes`? It might be complicated due to all the addons having their own property, but an extensive summary would be very user-friendly.

**Comment by jonniebigodes** [comment]
@Vadorequest if you don't mind and add a comment on #13499 we can take it from there. I'm consolidating feedback from you and the community to start the restructure/reorganization and fill in some documentation gaps that are still present. 

Stay safe

**Comment by Vadorequest** [comment]
Done! Feel free to close this if you like to, I'll track #13499 .

**Comment by shilman** [comment]
closing in favor of #13499
