### ISSUE TITLE
Using addon setConfig for theme doesn't work (migration guide v6)

### ISSUE THREAD

**Issue by Vadorequest** [storybookjs/storybook#13649]
**Describe the bug**
When following https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/theming.md#storybook-theming and configuring the theme through the `manager.js`, it doesn't apply the theme.

```js
addons.setConfig({
  theme: themes.dark,
});
``` 

Using `preview.js` `parameters.options.theme = themes.dark` works correctly.

**To Reproduce**

Remove `parameters.options.theme` and add `addons.setConfig` as described above.

**Expected behavior**
Theme should apply in both cases.

**Video**
https://youtu.be/ZvX9KhCNBEc

**Comment by shilman** [comment]
I believe you're seeing https://github.com/storybookjs/storybook/issues/13200

Does `--no-manager-cache` fix it?

**Comment by Vadorequest** [comment]
It does, thank you. Posting there and closing this duplicate.
