### ISSUE TITLE
Description missing in the documentation of a Svelte Component

### ISSUE THREAD

**Issue by j3rem1e** [storybookjs/storybook#13658]
**Describe the bug**

The description of a Svelte component is always missing in the generated documentation.

**To Reproduce**

Create a story with this component : 

```
<script>
  /**
  * Hello World Component
  * @component
  */
</script>

Hello world
```

**Expected behavior**

I am expecting to see "Hello World Component" in the generated documentation or using <Description/> block

**Comment by shilman** [comment]
Boo-yah!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.0-alpha.20 containing PR #13659 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```
