### ISSUE TITLE
NPM readme page for addon-docs contains many broken links

### ISSUE THREAD

**Issue by alexmorleyfinch** [storybookjs/storybook#13654]
**Describe the bug**
The npm page for addon-docs (found here https://www.npmjs.com/package/@storybook/addon-docs) has many links that are not found

**To Reproduce**

1. Go to https://www.npmjs.com/package/@storybook/addon-docs
2. Find and click on "Props documentation" linking to https://github.com/storybookjs/storybook/blob/HEAD/docs/props-tables.md
3. Witness the 404 github page

**Expected behavior**
I expect to be linked to the correct place

**Additional context**
Here are some other instances of broken links:
- The text "dev guide" that links to "https://github.com/storybookjs/storybook/blob/HEAD/docs/multiframework.md" is broken link
- The text "MDX reference" that links to "https://github.com/storybookjs/storybook/blob/HEAD/docs/mdx.md" is a broken link

Note: there may be more broken links, these are the ones I managed to find.

**Comment by jonniebigodes** [comment]
@alexmorleyfinch i think this is an issue with npm and how it resolves the urls. I've created a pr #12801 that addresses this. Still waiting on feedback on it.
