### ISSUE TITLE
defaultProps weird issue when used in storybook

### ISSUE THREAD

**Issue by ErAz7** [storybookjs/storybook#13661]
### **Describe the bug**
when I use an object in defaultProps, object name is stored in default prop as an string instead of object value

### **To Reproduce**
**here is a very simple example:**
1. create this component which imports `Theme` from `config.js`, sets `theme` prop's default value to `THEMES.PRIMARY` and just renders  `theme`:
```js
import PropTypes from 'prop-types';
import React, { PureComponent } from 'react';
import { THEMES } from 'config';

export default class MyComponent extends PureComponent {
    static propTypes = {
        theme: PropTypes.string
    }

    static defaultProps = {
        theme: THEMES.PRIMARY
    }

    render() {
        const { theme } = this.props;

        return (
            <div>
                {theme}
            </div>
        );
    }
}
```
and here is `config.js`:
```js
export const THEMES = {
    PRIMARY: 'primary'
};
```
2. create the story file:
```js
import React from 'react';
import MyComponent from './MyComponent';

export default {
    component: MyComponent,
    title: 'components/MyComponent'
};

const Template = args => <MyComponent {...args} />;

export const Playground = Template.bind({});
```
3. now if you run `yarn storybook` and check the story, you'll see this:
![2021-01-16_19-33-23](https://user-images.githubusercontent.com/46329768/104816644-cbc10b00-5831-11eb-9245-a9de641ff7c3.jpg)
as you see, `"THEMES.PRIMARY"` is stored in `theme` instead of `"primary"` which is the value of `THEMES.PRIMARY`

I think the cause for this is related to [this issue](https://github.com/storybookjs/storybook/issues/13041), except this will result in more serious problems

**Comment by pixelass** [comment]
Duplicate: There is an open issue for this: https://github.com/storybookjs/storybook/issues/12076

**Comment by shilman** [comment]
closing as dupe to #12076
