### ISSUE TITLE
Duplicate story preview in doc panel with svelte

### ISSUE THREAD

**Issue by j3rem1e** [storybookjs/storybook#13662]
**Describe the bug**

Framework Svelte.
Randomly, when using Controls in the doc panel, the story is duplicated in the preview panel. Sometimes, the story is not rendered, or rendered on the wrong canvas.

**To Reproduce**

1. Open the svelte kitchen sink
2. Open the Button Story
3. Click on the rounded control severals times. (It happens more frequently if the change are done fast..)
4. In the preview panel, the story appears twice

**Cause**
The HOC component doesn't destroy the child component.

**Comment by shilman** [comment]
Yo-ho-ho!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.0-alpha.18 containing PR #13663 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Son of a gun!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.15 containing PR #13663 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```
