### ISSUE TITLE
Doc Blocks: Request to export utilities

### ISSUE THREAD

**Issue by cocco3** [storybookjs/storybook#13677]
**Is your feature request related to a problem? Please describe**
My team was hoping to loop though stories for a component and build out some additional documentation with a different layout. I notice Storybook's [Stories.tsx](https://github.com/storybookjs/storybook/blob/next/addons/docs/src/blocks/Stories.tsx#L15) uses [util/getDocsStories](https://github.com/storybookjs/storybook/blob/755832bd11b7bf74d070fa0944a9f819f9b2db2a/addons/docs/src/blocks/utils.ts#L5), and that function has exactly what we would need.

**Describe the solution you'd like**
Would it be possible to export utils [along with everything else](https://github.com/storybookjs/storybook/blob/755832bd11b7bf74d070fa0944a9f819f9b2db2a/addons/docs/src/blocks/index.ts) so others could use `getDocsStories`?

**Describe alternatives you've considered**
Alternative would be to just write that function and maintain it ourselves.

**Are you able to assist to bring the feature to reality?**
No

**Comment by shilman** [comment]
This probably isn't an API we'd want to maintain, tbh. It's a pretty simple piece of code, and I don't expect it to change at all until we make a major update to Storybook Docs.
