### ISSUE TITLE
Filter props table per component

### ISSUE THREAD

**Issue by hazem3500** [storybookjs/storybook#13671]
**Is your feature request related to a problem? Please describe**
We have a component that is based on [Chakra-UI](https://chakra-ui.com/) and we want to show its props in the props table, the problem is we don't want to show all the style and HTML props such as `margin`, `padding` and `onMouseDown`, we want to show only the main props that are specific to that component.

**Describe the solution you'd like**
I want a way to be able to pick or filter the props that should appear in the props table

**Describe alternatives you've considered**
### `propFilter` in `main.js`

I've tried using the `PropFilter` in `main.js` to filter out the style props
```js
const { propNames } = require("@chakra-ui/styled-system")
const excludedPropNames = propNames.concat(["as", "apply", "sx", "__css"])

module.exports = {
    stories: [
        '../src/**/*.stories.mdx',
        '../src/**/*.stories.@(js|jsx|ts|tsx)',
    ],
    addons: [
        '@storybook/addon-essentials',
    ],
    typescript: {
        reactDocgenTypescriptOptions: {
            propFilter: (prop) => {
                const isStyledSystemProp = excludedPropNames.includes(prop.name)
                const isHTMLElementProp =
                    prop.parent?.fileName.includes("node_modules") ?? false

                return !(isStyledSystemProp || isHTMLElementProp)
            },
        },
    },
};
```
But I couldn't filter out the `isHTMLElementProp` since `prop.parent` turns out to be undefined

### Exporting a default component with only the main props

I've tried making another component with the prop types of the main components only
```jsx
import {
    Alert as BaseComponent,
    AlertProps as BaseProps,
} from '@chakra-ui/react';
import React from 'react';

type MainProps = 'variant' | 'CTA';

export type AlertProps = BaseProps;

export type AlertMainProps = Pick<AlertProps, MainProps>;


export const Alert = ({
    children,
    ...props
}: AlertProps) => {
    return (
        <BaseComponent {...props}>
           {children}
        </BaseComponent>
    );
};

export const _Alert: React.FC<AlertMainProps> = Alert;

export default _Alert;

```
Which works but then in the `Docs` page the code snippet appears with the name `_Alert` instead of `Alert`

![image](https://user-images.githubusercontent.com/22430645/105020970-aa8a3580-5a50-11eb-9db7-80704c07ee67.png)

Which isn't that big of a problem until you use a plugin like [storybook-addon-playroom](https://github.com/rbardini/storybook-addon-playroom)

![image](https://user-images.githubusercontent.com/22430645/105021109-d60d2000-5a50-11eb-94f4-2a688337ef84.png)

**Are you able to assist to bring the feature to reality?**
Yeah, I would be happy to assist 😄

**Comment by hazem3500** [comment]
For anyone who is getting `prop.parent` as `undefined` I've fixed it by adding 
```json
"resolutions": {
   "typescript": "4.1.3"
},
```
in `package.json`, it doesn't have to be `4.1.3` it just needs to be the version you are currently using

and to filter out the HTML props you can add in `main.js`

```js
typescript: {
        reactDocgenTypescriptOptions: {
            propFilter: (prop) => {
                const isHTMLElementProp =
                    prop.parent?.fileName.includes("node_modules") ?? false

                return !isHTMLElementProp
            },
        },
    },
```

**Comment by shilman** [comment]
Available in https://github.com/storybookjs/storybook/pull/13898
