### ISSUE TITLE
Pass props to docs page

### ISSUE THREAD

**Issue by hazem3500** [storybookjs/storybook#13688]
**Is your feature request related to a problem? Please describe**
We are currently creating a custom `DocsPage` for our storybook and we would like to set it globally in `preview.js`, but we need to pass component metadata and parameters to that docs page but apparently, the Docs page doesn't get passed any props

**Describe the solution you'd like**
I would imagine the API could look something like this
```jsx
export default {
    title: 'MyComponent',
    parameters: {
        design: {
            URL: 'DESIGN_SCREEN_URL',
        },
        docs: {
            page: ({title, parameters: {design }}) => (
                <>
                    <Title />
                    <Subtitle />
                    <Description />
                    <Primary />
                    <ArgsTable story={PRIMARY_STORY} />
                    <Stories />
                    <Design name={title} src={design.URL}/>
                </>
            ),
        }
    },
};
```

**Describe alternatives you've considered**
We could add the custom docs page individually in each story but it would've been better to be able to set it at a global level

**Are you able to assist to bring the feature to reality?**
Yes

**Comment by jgodi** [comment]
In your `<Design/>` component you can grab the parameters via the contexts.

```
const context = React.useContext(DocsContext);
const sourceContext = React.useContext(SourceContext);
```

The `context` will have `context.parameters` that you can use.

**Comment by shilman** [comment]
Exactly what @jgodi said! ☝️  Closing this.
