### ISSUE TITLE
Dynamic Controls

### ISSUE THREAD

**Issue by amartinez62** [storybookjs/storybook#13681]
As a user 
I want to be able to selectively show/hide controls in the UI based on the value of other controls 
so that I am not confused by controls that are irrelevant to the current state of the component.

There is also a request for dynamic controls ([#11984](https://github.com/storybookjs/storybook/issues/11984)) that are conditional on the values of other controls. The basic use case is having a boolean toggle like “show advanced controls”, which cause a bunch more controls to show when it’s checked.

One approach to this would be to implement grouped controls ([#10979](https://github.com/storybookjs/storybook/issues/10979)), which is also a feature request. The UI for this has already been implemented, although the API has not.

**Comment by johnend** [comment]
OK, so this would be really useful for anyone needing to build an icon component. We have 200+ icons across different categories. If you say wanted to have "Icon Category" and "Icon Name" props, you would want the list of Icon Names to be reduced based on the Icon Category that was selected. I would assume this sort of thing is a reasonably regular occurrence?

**Comment by shilman** [comment]
closing this as dupe to #11984
