### ISSUE TITLE
Deprecate knobs

### ISSUE THREAD

**Issue by amartinez62** [storybookjs/storybook#13682]
As a developer
I want to know that knobs are deprecated 
so that I can know to upgrade to controls.

Knobs can be trivially deprecated by issuing a deprecation warning in its decorator.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if this is still relevant in SB 7.x.
