### ISSUE TITLE
Error on command

### ISSUE THREAD

**Issue by dovehubeng** [storybookjs/storybook#13690]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
Please paste the results of `npx sb@next info` here.

**Additional context**

**Comment by yannbf** [comment]
I'm sorry @dovehubeng but this issue has no description. Could you explain what exactly is the issue you're having as well as the reproduction steps? Thanks!
