### ISSUE TITLE
/sell multipliers with permissions

### ISSUE THREAD

**Issue by Soapiee** [storybookjs/storybook#13694]
**Describe the solution you'd like**
/sell multipliers that are set with permission nodes.
The multipliers are to increase/multiply the sell price that someone can get via the /sell command. It basically multiplies the worth.

**Describe alternatives you've considered**
I could try to make multiple different shops (that have different sell prices per item) with a shop plugin, then apply the shop permission to the player (if there's a plugin like that out there). I would just prefer to use the essentials worth and sell system and allow multipliers through permissions though.

**Are you able to assist to bring the feature to reality?**
Nope

**Additional context**
Example permissions:
essentials.sell.multiplier.0.5 > multiplies the worth/sell price by 0.5
essentials.sell.multiplier.2 > multiplies the worth/sell price by 2
essentials.worth.multiplier.0.5 > multiplies the worth/sell price by 0.5
essentials.worth.multiplier.2 > multiplies the worth/sell price by 2

**Comment by jonniebigodes** [comment]
@Soapiee thank you for the time you put into creating your issue. But based on your description it seems that you opened it in the wrong place. Sorry but i'm going to close this issue.

Stay safe
