### ISSUE TITLE
Angular 11 error being thrown on IE11 with Storybook 6.1 and 6.2@alpha

### ISSUE THREAD

**Issue by thomasoreilly** [storybookjs/storybook#13692]
**Describe the bug**
When bundling for IE11 it appears that code isn't being transpiled. 

Two errors are being thrown. 
"Const must be initialized" 
and
"Syntax error"

**To Reproduce**

1. Create a new application for Angular 11 
2. Integrate Storybook 6.1
3. Update .browserlistrc so IE11 is opt-in  
4. Open on IE11 browser and view error in console

**Expected behavior**
Should run successfully. 

**Screenshots**
Example Repo: 
https://github.com/thomasoreilly/storybook-angular11-ie11-6.1-issue
Deployment of Repo:
https://thomasoreilly.github.io/storybook-angular11-ie11-6.1-issue/?path=/story/example-introduction--page

![image](https://user-images.githubusercontent.com/2962056/105367390-4bffbb80-5bf8-11eb-9c6e-a2e9bf796792.png)

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
Please paste the results of `npx sb@next info` here.

Environment Info:
System:
    - OS: macOS 10.15.7
    - CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    - Node: 12.20.0 - ~/.nvm/versions/node/v12.20.0/bin/node
    - Yarn: 1.22.10 - ~/.nvm/versions/node/v12.20.0/bin/yarn
    - npm: 6.14.8 - ~/.nvm/versions/node/v12.20.0/bin/npm
  Browsers:
    - Chrome: 87.0.4280.141
    - Firefox: 78.6.1
    - Safari: 14.0.1
  npmPackages:
    - @storybook/addon-actions: ^6.1.14 => 6.1.14 
    - @storybook/addon-essentials: ^6.1.14 => 6.1.14 
    - @storybook/addon-links: ^6.1.14 => 6.1.14 
    - @storybook/angular: ^6.1.14 => 6.1.14 
    - @storybook/preset-ie11: 0.0.1 => 0.0.1 

**Additional context**
This issue is also happening on the latest alpha for 6.2.

**Comment by thomasoreilly** [comment]
I've been trying to pin point the issue here on my end and tracked it down to this change. 
https://github.com/storybookjs/storybook/pull/13607/files

Reverting this change locally fixes the babel transpiling for Angular on IE11, however it breaks docs which obviously depends on this change.

**Comment by yannbf** [comment]
cc @tooppaaa

**Comment by thomasoreilly** [comment]
I noticed that undoing this [change](https://github.com/storybookjs/storybook/pull/13607/files) solves the issue. This will obviously undo the fixes that the change solves. Seems to be some kind of Babel resolution issue.

**Comment by thomasoreilly** [comment]
Just tested on the latest version alpha.18 and this issue is resolved.

**Comment by thomasoreilly** [comment]
Hi @shilman. Is there any plan to hotfix 6.1 for this issue? Has our team in a bit of a pickle as we rely on Storybook for testing and IE11 is crucial for us. If there's anything I can do to help out I'd be happy to help. Thanks.

**Comment by shilman** [comment]
@thomasoreilly I'll discuss with @tooppaaa and see what's involved. If it's straightforward and not destabilizing I'd be happy to patch it.

**Comment by thomasoreilly** [comment]
Thanks for the quick response, sounds good.

**Comment by shilman** [comment]
@thomasoreilly can you kick the tires on this for me? https://github.com/storybookjs/storybook/pull/13741

```
yarn bootstrap --core
cd examples/angular-cli
yarn storybook
```

**Comment by thomasoreilly** [comment]
Hey @shilman. 

Just recently installed 6.2 and we are still experiencing this issue with IE11. We are also seeing experiencing this issue on a vanilla Angular setup. Has there been any discussion about IE11 support for Angular and Storybook?
