### ISSUE TITLE
Storybook opens local IP address instead of localhost

### ISSUE THREAD

**Issue by mrlubos** [storybookjs/storybook#13707]
**Describe the bug**
This started happening pretty recently, although I am not sure when I noticed it. When I run `start-storybook -p 8080 -s public --no-dll`, my browser opens `http://192.168.1.100:8080/` instead of `http://localhost:8080/`. It's quite annoying as I usually want to open localhost and I often have that tab already open, so all that should happen is Storybook loads inside that browser tab. It used to work like this until recently.

**To Reproduce**

**Expected behavior**
Browser opens the localhost address

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
Environment Info:

  System:
    OS: macOS 11.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 12.20.1 - ~/.nvm/versions/node/v12.20.1/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 6.14.9 - ~/git/banff/webapp/node_modules/.bin/npm
  Browsers:
    Chrome: 87.0.4280.141
    Firefox: 78.0.2
    Safari: 14.0.2
  npmPackages:
    @storybook/addon-a11y: 6.1.14 => 6.1.14 
    @storybook/addon-actions: 6.1.14 => 6.1.14 
    @storybook/addon-backgrounds: 6.1.14 => 6.1.14 
    @storybook/addon-jest: 6.1.14 => 6.1.14 
    @storybook/addon-knobs: 6.1.14 => 6.1.14 
    @storybook/addon-links: 6.1.14 => 6.1.14 
    @storybook/addon-storysource: 6.1.14 => 6.1.14 
    @storybook/addons: 6.1.14 => 6.1.14 
    @storybook/preset-create-react-app: 3.1.5 => 3.1.5 
    @storybook/react: 6.1.14 => 6.1.14 

**Additional context**

**Comment by shilman** [comment]
@mrlubos can you bisect to find out which version caused it?

**Comment by Tonyhliu** [comment]
Bump - just upgraded from 6.1.10 -> 6.1.15 and this started happening. Downgraded and it's still happening.

**Comment by melvinhernandez** [comment]
Also having the same issue, using `@storybook/react: 6.1.14`. 
Looks like it's a duplicate issue https://github.com/storybookjs/storybook/issues/13619 stemming from this PR: https://github.com/storybookjs/storybook/pull/13521

**Comment by PenguinOfWar** [comment]
I've created a PR to address this issue by providing flexibility based on the provided args: #13812

Advice welcome on how to make sure this is properly covered in tests.

**Comment by shilman** [comment]
Good golly!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.17 containing PR #13812 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Ermahgerd!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.0-alpha.22 containing PR #13812 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```
