### ISSUE TITLE
Theming storybook

### ISSUE THREAD

**Issue by cherylcarpenter** [storybookjs/storybook#13718]
**Describe the bug**
I have implemented a theme for my storybook project following the exact instructions here
https://storybook.js.org/docs/vue/configure/theming

There is no observable change to any colors or logo. No errors in the console or terminal on build.

**Expected behavior**
on storybook serve I expected the colorPrimary in the navbar and storybook UI to be hotpinik, the logo to be changed etc. just like in the demo 

**System**
Environment Info:

  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  Binaries:
    Node: 12.13.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.12.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 88.0.4324.96
    Safari: 14.0.1
  npmPackages:
    @storybook/addon-actions: ^6.1.15 => 6.1.15 
    @storybook/addon-essentials: ^6.1.15 => 6.1.15 
    @storybook/addon-links: ^6.1.15 => 6.1.15 
    @storybook/addons: ^6.1.15 => 6.1.15 
    @storybook/theming: ^6.1.15 => 6.1.15 
    @storybook/vue: ^6.1.15 => 6.1.15 

**Additional context**
Vue-cli  setup

**Comment by jonniebigodes** [comment]
@cherylcarpenter could you check one thing for me? If you don't mind try running storybook with the `--no-manager-cache` flag. Turning your package.json script into `"storybook": "start-storybook -p 6006 --no-manager-cache"` . Let us know if that solved the issue.

Stay safe

**Comment by cherylcarpenter** [comment]
@jonniebigodes  hi, thanks for reply! I had searched for any caching info so this is good to know.
That did indeed do something, but not exactly what we're going for based on the documentation I mentioned here:
https://storybook.js.org/docs/vue/configure/theming

The 'them' is based on 'light' and the colorPrimary is hotpink but now it looks like the dark theme? LOL

![image](https://user-images.githubusercontent.com/13105904/105612033-b8a4c280-5d7e-11eb-8557-d7e43a712971.png)

**Comment by cherylcarpenter** [comment]
@jonniebigodes Thanks for reply! I had looked for caching info so this is good to know.

I'm getting a new error now in the build terminal.
WARNING in ./.storybook/manager.js 5:9-16
"export 'myTheme' was not found in './myTheme'

so my manager has 
import { myTheme } from "./myTheme";

and then in same directory I have myTheme.js with just the 

import { create } from "@storybook/theming/create";

export default create ({
. ..etc...  
});

does this need some further export? 
Sorry I'm a bit new at Vue as well.

**Comment by MrWittman612** [comment]
> @cherylcarpenter could you check one thing for me? If you don't mind try running storybook with the `--no-manager-cache` flag. Turning your package.json script into `"storybook": "start-storybook -p 6006 --no-manager-cache"` . Let us know if that solved the issue.
> 
> Stay safe

That worked for me. Thank you, I have been trying to get this to work for three hours. would be really nice to have this documented. thanks again just made my night a little better!!!!

**Comment by MrWittman612** [comment]
> @jonniebigodes Thanks for reply! I had looked for caching info so this is good to know.
> 
> I'm getting a new error now in the build terminal.
> WARNING in ./.storybook/manager.js 5:9-16
> "export 'myTheme' was not found in './myTheme'
> 
> so my manager has
> import { myTheme } from "./myTheme";
> 
> and then in same directory I have myTheme.js with just the
> 
> import { create } from "@storybook/theming/create";
> 
> export default create ({
> . ..etc...
> });
> 
> does this need some further export?
> Sorry I'm a bit new at Vue as well.

ok I figured it out 
`import { create } from '@storybook/theming';
not ...
import { create } from "@storybook/theming/create";

export default create({
  base: 'dark',
  brandTitle: 'fuk this',
  brandUrl: 'https://example.com',
  brandImage: 'https://placehold.it/350x150',
});`

`import { addons } from '@storybook/addons';
import CustomStoryBookTheme from './CustomStoryBookTheme';
not --- 
import { myTheme } from "./myTheme";
addons.setConfig({
  theme: CustomStoryBookTheme,
});`

**Comment by MrWittman612** [comment]
> [](https://storybook.js.org/docs/vue/configure/theming)
> 
> There is no observable change to any colors or logo. No errors in the console or terminal on bui
ok I figured it out. you do have to put that tag --no-manage-cache in the script the rest looks like this
import { create } from '@storybook/theming';
NOT ----------
import { create } from "@storybook/theming/create";
export default create({
  base: 'dark',
  brandTitle: 'fuk this',
  brandUrl: 'https://example.com',
  brandImage: 'https://placehold.it/350x150',
});



import { addons } from '@storybook/addons';
import CustomStoryBookTheme from './CustomStoryBookTheme';
NOT ----- 
import { myTheme } from "./myTheme";

addons.setConfig({
  theme: CustomStoryBookTheme,
});

**Comment by cherylcarpenter** [comment]
@MrWittman612 That fixes it thank you so much!!!
I hope that they fix the documentation page to reflect this!
:)

**Comment by phated** [comment]
I took a look at the docs and implementation and everything here seems to be covered (including the `--no-manager-cache` suggestion in an aside). I put together #13726 to import the create from `@storybook/theming` to better support typescript and ESM, but I'm going to close this because that's adjacent to this issue and might not get merged. Cheers!
