### ISSUE TITLE
Create a customizable utility to create Vue instanse

### ISSUE THREAD

**Issue by farnabaz** [storybookjs/storybook#13723]
There is multiple Vue instance creation in Storybook source code. I'm suggesting to create a customizable utility to unify these instances.  
- https://github.com/storybookjs/storybook/blob/next/addons/docs/src/frameworks/vue/sourceDecorator.ts#L39
- https://github.com/storybookjs/storybook/blob/next/app/vue/src/client/preview/render.ts#L8
- https://github.com/storybookjs/storybook/blob/next/addons/docs/src/frameworks/vue/prepareForInline.ts#L18

Creating a customizable and unified utility to create instances will help developers extends Storybook power.
Libraries like Nuxt are adding helpers and plugins into Vue context so developers can use these plugins in components. Unfortunately, injecting variables in Vue instances is not possible.

Suggested utility could be like this:
```js
function createVueInstance ({ component, args, context }) {
  return new Vue({
    ...(context || {}),
    // also it will be very useful to extend context using Storybook globalParameters
	...globalParameters.vueContext,
    data() {
      return {
        [COMPONENT]: component,
        [VALUES]: { ...args },
      };
    },
    render(h) {
      const children = this[COMPONENT] ? [h(this[COMPONENT])] : undefined;
      return h('div', { attrs: { id: 'root' } }, children);
    },
  }); 
}
```

**Comment by shilman** [comment]
@farnabaz Closed intentionally?

**Comment by farnabaz** [comment]
Yes.
I'm investigating about improving integration with Vue and Nuxt. Will create an issue with more details afterwards.
