### ISSUE TITLE
Permission to use website assets for conference.

### ISSUE THREAD

**Issue by ssylvia** [storybookjs/storybook#13736]
I'm planning to share our team's development process at a developer conference. Part of the presentation includes showing our use of Storybook to build out our component system. I was hoping to use 1 or 2 of the simple video animations on the [homepage](https://storybook.js.org/) to show visually what Storybook is at a high level. Are you able to provide permission to use assets from your website or do you have any usage restrictions around them?

**Comment by shilman** [comment]
No usage restrictions. Attribution nice but not required AFAIK!

**Comment by ssylvia** [comment]
Great, thank you! Would be happy to add attribution.
