### ISSUE TITLE
v-dialog component pops above everything on docs screen

### ISSUE THREAD

**Issue by K-Schaeffer-LOG** [storybookjs/storybook#13732]
**Describe the bug**
Im using vue + vuetify + storybook, and I do have a component that uses the vuetify's v-dialog. The issue occurs when the dialog  property of the component is true, even with canvas screen working properly, docs screen seems to render the dialog above everything on the page.
Btw, there's no error on the console.

**To Reproduce**

1. Go to [my storybook](https://5fe2254966f2280021ed9e80-wttafljufy.chromatic.com/?path=/story/components-modals-modal--confirmational)
2. Click on the docs page
3. Reload your page
4. See the dialog pops above everything else

**Expected behavior**
It should stay in "preview block"

**Screenshots**
![image](https://user-images.githubusercontent.com/75996650/105884111-64038080-5fe6-11eb-8d15-2470fb38552d.png)

**Code snippets**
```
const Template = (args, { argTypes }) => ({
  vuetify,
  props: Object.keys(argTypes),
  components: { LModal },
  template: `
    <l-modal 
        v-bind="$props" 
        @close="close" 
        @confirm="confirm" 
        @clear="clear" 
    >
        <template #modalTitle>
            <div style="textAlign: center">
                Modal title here!
            </div>
        </template>
        <template #modalContent>
            <div v-for="x in 5" style="textAlign: center;">
                Modal Content here!
            </div>
        </template>
    </l-modal>
  `
});

export const Confirmational = Template.bind({});
Confirmational.args = {
  dialog: true,
  modalType: {confirmational: true},
  confirmText: 'Confirm',
  cancelText: 'Cancel'
};
```
**System**
Environment Info:

```
  System:
    OS: Linux 5.0 Linux Mint 19.3 (Tricia)
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  Binaries:
    Node: 12.9.0 - ~/.nvm/versions/node/v12.9.0/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 6.10.2 - ~/.nvm/versions/node/v12.9.0/bin/npm
  Browsers:
    Chrome: 87.0.4280.88
    Firefox: 82.0.3
  npmPackages:
    @storybook/addon-actions: ^6.1.11 => 6.1.11 
    @storybook/addon-essentials: ^6.1.11 => 6.1.11 
    @storybook/addon-links: ^6.1.11 => 6.1.11 
    @storybook/addons: ^6.1.11 => 6.1.11 
    @storybook/theming: ^6.1.11 => 6.1.11 
    @storybook/vue: ^6.1.11 => 6.1.11 
```

**Comment by tooppaaa** [comment]
You have to use a decorator to wrap your container with anything that will make your component to display as expected.

**Comment by throrin19** [comment]
@tooppaaa have you any more informations to do that ?

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
