### ISSUE TITLE
MDX stories named with a pattern other than *.stories.mdx don't compile correctly

### ISSUE THREAD

**Issue by Prior99** [storybookjs/storybook#13735]
[This issue](https://github.com/storybookjs/storybook/issues/9918) was closed without a fix, however, [the documentation](https://storybook.js.org/docs/react/configure/overview) clearly states this as feature, so I can't see why the issue was closed. I suggest to either update the documentation and get rid of the configuration option, or fix the issue.

**Comment by Prior99** [comment]
This can be used as a temporary workaround:

```
    config.module.rules = config.module.rules.filter(rule => !rule.exclude?.exec("example.stories.mdx"));
    config.module.rules.find(rule => rule.test.exec("example.stories.mdx")).test = /\.mdx$/;
```

**Comment by jonniebigodes** [comment]
@Prior99 could you elaborate what part of the documentation is not clear to you? So that i can take a look at and see how to best address your issue.

**Comment by Prior99** [comment]
@jonniebigodes Of course. If you go to [this anchor link](https://storybook.js.org/docs/react/configure/overview#configure-story-loading) it states that 

```
For example if you wanted to pull both .md and .js files from the my-project/src/components directory, you could write:

    // .storybook/main.js

    module.exports = {
      stories: ['../my-project/src/components/*.@(js|md)'],
    };
```

Which I tried but which doesn't work due to the aforementioned issue.
Which is why I suggested to either re-open the issue or update the documentation.

**Comment by shilman** [comment]
closing as duplicate to #9918, which has been re-opened
