### ISSUE TITLE
Unable to import Svelte files that doesn't start with capital letter

### ISSUE THREAD

**Issue by bluwy** [storybookjs/storybook#13742]
**Describe the bug**
Unable to import Svelte files that doesn't start with capital letter, e.g. `header.svelte`, `_header.svelte`. Webpack compiles fine, but in the browser console, it reports `Unexpected error while loading ./stories/Header.stories.js: ReferenceError: _header is not defined`.

**To Reproduce**
Repo: https://github.com/bluwy/storybook-svelte-import-repro

1. Clone repo
2. `npm install`
3. `npm run storybook`
4. Go to http://localhost:6006 (Storybook page) and open devtools console

**Expected behavior**
Able to import Svelte files regardless of casing.

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
```
Environment Info:

  System:
    OS: Linux 5.8 Ubuntu 20.10 (Groovy Gorilla)
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
  Binaries:
    Node: 12.19.0 - ~/.nvm/versions/node/v12.19.0/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v12.19.0/bin/npm
  Browsers:
    Firefox: 84.0.2
  npmPackages:
    @storybook/addon-actions: ^6.1.15 => 6.1.15 
    @storybook/addon-essentials: ^6.1.15 => 6.1.15 
    @storybook/addon-links: ^6.1.15 => 6.1.15 
    @storybook/svelte: ^6.1.15 => 6.1.15 
```

**Additional context**
This works in v6.1.12, and but fails in v6.1.14 onwards (repo is using v6.1.15 but I've also tested in v6.1.14). 
https://github.com/storybookjs/storybook/pull/13466 seems to be causing the issue since it's introduced in v6.1.14.

**Comment by bluwy** [comment]
Hey @j3rem1e, I would appreciate if you can take a look into this. Your PR fixed the simultaneous render issue (https://github.com/storybookjs/storybook/issues/13351) too, so our team is interested in upgrading to the latest version (currently stuck at v6.1.12). 

Understand if you don't have time to attend this issue. Hopefully it will only be a small fix. Thank you!

**Comment by shilman** [comment]
Jeepers creepers!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.0-alpha.20 containing PR #13760 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

**Comment by shilman** [comment]
Crikey!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.16 containing PR #13760 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```
