### ISSUE TITLE
strictTemplates compiler option in Angular components is ignored

### ISSUE THREAD

**Issue by pf1gura** [storybookjs/storybook#13748]
### **Describe the bug**
Typing errors in Angular component templates are ignored by Storybook. They are correctly thrown by Angular compiler though.
`angularCompilerOptions.strictTemplates = true` option in `tsconfig.json` is responsible for type checking the templates. This option is not used by Storybook.

### **To Reproduce**
1. Create Angular app with strict mode enabled
2. Add storybook to it
3. Try to access possibly undefined property in the template

I created reproduction repo here:
[https://github.com/pf1gura/Storybook-Strict-Templates](https://github.com/pf1gura/Storybook-Strict-Templates)

### **Expected behavior**
Storybook should throw error when development server is used, just like Angular dev server does in that case.

### **System**
```
  System:
    OS: macOS 11.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 15.3.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.11 - /usr/local/bin/npm
  Browsers:
    Chrome: 88.0.4324.96
    Edge: 86.0.622.43
    Firefox: 83.0
    Safari: 14.0.2
```

**Comment by gaetanmaisse** [comment]
I think this is because `strictTemplates` is only available/used when running Ivy (https://angular.io/guide/template-typecheck#strict-mode) and `@storybook/angular` isn't working/running with Ivy yet. @ThibaudAV @kroeder do you agree?

**Comment by kroeder** [comment]
Not yet! But we made progress with the storybook ivy support

https://github.com/storybookjs/storybook/issues/13768#issuecomment-772364369

**Comment by pf1gura** [comment]
Thanks for an update, and for amazing work on the project! 

I wasn't aware that storybook does not use Ivy yet. Looking forward to testing it in the future!

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
