### ISSUE TITLE
Problems with Formik and component from storybook library export

### ISSUE THREAD

**Issue by jeffedsell** [storybookjs/storybook#13751]
### Bug or support request summary

I created a custom form field in storybook using Formik's `useField` and `useFormikContext` for validation. I was able to successfully see the validation working in the story containing the custom field.

However, when the components are exported as a library, and I import that library into another project, using the custom form field component produces the error `TypeError: Cannot read property 'getFieldProps' of undefined`.

Copying the code for the custom form field component into the local project prevents the error, and the component works and validated perfectly. 

### Please specify which version of Storybook and optionally any affected addons that you're running

Storybook 6.1.0-rc.6

### Acceptance criteria

I need to be able to export a library containing custom form element components using Formik, and then be able to use those form elements in a different project without error.

**Comment by tooppaaa** [comment]
Hello @jeffedsell,

Can you provide code samples ? Is your issue related to Storybook ?

I personally use Storybook + Formik and export a library. There should not be anything particular here.

**Comment by stephanrotolante** [comment]
@jeffedsell What versions of Formik are you using to wrap your custom components? I was having issues the past few days.  My custom components were using a different version Formik than the Formik component used to wrap them.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
