### ISSUE TITLE
CSF Story fails (no errors) when importing secondary module

### ISSUE THREAD

**Issue by painedpineapple** [storybookjs/storybook#13750]
**Describe the bug**
When a non-react module is required/imported and used within a CSF story, the story doesn't load. No errors are reported, the story just isn't found or displayed in the UI

**To Reproduce**
Use "not-working" code snippet below

**Expected behavior**
When external modules are required, stories will still build.

**Screenshots**

With working code snippet below: 
![image](https://user-images.githubusercontent.com/5152553/106059208-9cbb5c80-60af-11eb-9dff-5fb67fbffd8e.png)

With "not-working" code snippet below:
![image](https://user-images.githubusercontent.com/5152553/106059332-caa0a100-60af-11eb-9692-51d0db8a50a1.png)

**Code snippets**
Not Working:

```javascript
var Alert$Ui = require("./Alert.bs.js");
var Storybook$Ui = require("../../bindings/Storybook.bs.js");

var setArgs = (function (story, args) {
  story.args = args
});

var success = Alert$Ui.make.bind(Storybook$Ui.emptyObject);

setArgs(success, {
  type_: "success"
});


var template = Alert$Ui.make;

exports.template = template;
exports.success = success;
exports.default = {
  title: "ReScript/Alert",
  excludeStories: new RegExp("\\$\\$default|template|.*Data$"),
  component: Alert$Ui.make
};
```

Working:

```javascript
var Alert$Ui = require("./Alert.bs.js");
// var Storybook$Ui = require("../../bindings/Storybook.bs.js");

var setArgs = (function (story, args) {
  story.args = args
});

var success = Alert$Ui.make.bind({});

setArgs(success, {
  type_: "success"
});


var template = Alert$Ui.make;

exports.template = template;
exports.success = success;
exports.default = {
  title: "ReScript/Alert",
  excludeStories: new RegExp("\\$\\$default|template|.*Data$"),
  component: Alert$Ui.make
};
```

**System**
```unix
Environment Info:

  System:
    OS: Linux 5.8 Pop!_OS 20.10
    CPU: (32) x64 AMD Ryzen 9 3950X 16-Core Processor
  Binaries:
    Node: 12.19.0 - /tmp/fnm_multishell_8742_1611781888569/bin/node
    Yarn: 1.22.10 - ~/code/bidchuck/node_modules/.bin/yarn
    npm: 5.1.0 - ~/code/bidchuck/node_modules/.bin/npm
  Browsers:
    Chrome: 88.0.4324.96
    Firefox: 84.0.2
  npmPackages:
    @storybook/addon-actions: ^6.1.15 => 6.1.15 
    @storybook/addon-essentials: ^6.1.15 => 6.1.15 
    @storybook/addon-links: ^6.1.15 => 6.1.15 
    @storybook/node-logger: ^6.1.15 => 6.1.15 
    @storybook/preset-create-react-app: ^3.1.5 => 3.1.5 
    @storybook/react: ^6.1.15 => 6.1.15 
```

**Comment by phated** [comment]
@thislogancall and `Storybook$Ui.emptyObject` is just bound to `{}`? I remember that objects in BS might get represented differently.

**Comment by thislogancall** [comment]
@phated Yes, but it didn't matter what _value_ I was importing from the Storybook bindings, it still had the same issue.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
