### ISSUE TITLE
Publish components to NPM?

### ISSUE THREAD

**Issue by lmatteis** [storybookjs/storybook#13756]
We're using storybook as a common development platform to showcase our components. However we can't seem to find an easy standard way to publish the components on npm (for other devs to use).

What's the standard way of doing this with a storybook project?

**Comment by gdorsi** [comment]
Have you tried [lerna](https://github.com/lerna/lerna/tree/main/commands/publish#readme)?

What kind of issues have you encoutnered?

**Comment by phated** [comment]
I think that's out of scope for Storybook core/cli/etc. But you could definitely use something like `lerna` 👆 to handle it in a monorepo.
