### ISSUE TITLE
webpackFinal is ignored during build

### ISSUE THREAD

**Issue by hdsand** [storybookjs/storybook#13754]
Hi!

**Bug**

When I use `build-storybook`, my rules in webpackFinal are ignored. However, everything works fine during `npm run storybook`. 

I have an ejected CRA, Storybook, PostcCSS.  

**Steps to reproduce**

It's easier to show. Please check the repo https://github.com/hdsand/cra_storybook_postcss

1. yarn install
2. yarn storybook
3. yarn build storybook

**Versions**
```javascript
    "react": "^17.0.1",
    "@storybook/addon-actions": "^6.1.9",
    "@storybook/addon-essentials": "^6.1.9",
    "@storybook/addon-links": "^6.1.9",
    "@storybook/preset-create-react-app": "^3.1.5",
    "@storybook/react": "^6.1.9",
    "@storybook/cli": "^6.1.9",
    "postcss-loader": "3.0.0",
    "postcss-nested": "4.2.3",
```

I'll be grateful if you help me!

**Comment by shilman** [comment]
When I put a `console.log` in `webpackFinal` in your repro, it's getting logged in both dev and production ... so it's definitely not getting ignored. Perhaps something else is overwriting the results differently in the two modes?
