### ISSUE TITLE
IE11 hangs with addon-actions

### ISSUE THREAD

**Issue by bozdoz** [storybookjs/storybook#13763]
Storybook hangs in IE11 with @storybook/addon-actions

**To Reproduce**

1. include @storybook/addon-actions
2. (just in case) make sure your webpack `config.resolve.mainFields` are `['browser', 'main', 'module']` in `.storybook/webpack.config.js`
3. View in IE11

**Expected behavior**
Storybook to work the same as in Chrome

**Screenshots**
Error in IE11
![Screen Shot 2021-01-28 at 5 27 06 PM](https://user-images.githubusercontent.com/1410985/106202367-31958700-6190-11eb-8e61-cd0967f110e9.png)

No support for default variables in IE11
![Screen Shot 2021-01-28 at 5 40 26 PM](https://user-images.githubusercontent.com/1410985/106202376-35290e00-6190-11eb-94f9-cd9597e4106f.png)

Coming from addon-actions and uuid dependency
![Screen Shot 2021-01-28 at 5 40 46 PM](https://user-images.githubusercontent.com/1410985/106202381-3823fe80-6190-11eb-9381-24aced2ca769.png)

**System**
Environment Info:

  System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 12.16.2 - ~/.nvm/versions/node/v12.16.2/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v12.16.2/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.16.2/bin/npm
  Browsers:
    Chrome: 88.0.4324.96
    Firefox: 84.0.2
    Safari: 14.0.2

**Additional context**

**Comment by bozdoz** [comment]
Actually, this problem ONLY happens when config.resolve.mainFields are set to `['browser', 'main', 'module']` in `.storybook/webpack.config.js`.

I have another package which doesn't work in IE11 unless those fields are set, so I'm not sure how to make this work

**Comment by tooppaaa** [comment]
@bozdoz, I didn't saw any issues with uuid before but in any doubt, I added it to the @storybook/preset-ie11 https://github.com/storybookjs/presets/pull/197

Could you give it a try when it gets out ?

**Comment by ndelangen** [comment]
Storybook 7.0 won't support IE11 anymore.

6.5 won't receive updates other than critical security issues, this won't get fixed.
