### ISSUE TITLE
Addon-docs/Vue: Support @values in ArgsTable

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#13764]
It would be great to support `@values`: https://vue-styleguidist.github.io/docs/Documenting.html#values
In `Vue` `ArgsTable` it's not possible to show a list with the possible values in the type column 😢

_Originally posted by @fallemand in https://github.com/storybookjs/storybook/issues/11655#issuecomment-691663233_

**Comment by HIMISOCOOL** [comment]
Values is available on `docgenInfo` in `addons\docs\src\frameworks\vue\extractArgTypes.ts:17` as an array of values so the hard work is in getting it displayed on the ui.

I had a stab at it but short of adding a column that wont be used by other frameworks I couldnt figure it out.

**Comment by adrianpdm** [comment]
> Values is available on `docgenInfo` in `addons\docs\src\frameworks\vue\extractArgTypes.ts:17` as an array of values so the hard work is in getting it displayed on the ui.
> 
> I had a stab at it but short of adding a column that wont be used by other frameworks I couldnt figure it out.

Hi, i've taken a look at `addons\docs\src\frameworks\vue\extractArgTypes.ts:17`.

It seems that even though values and many docgen-generated info are available within `docgenInfo`, the controls itself are inferred in `lib/client-api/src/inferControls.ts`.

https://github.com/storybookjs/storybook/blob/424bd38c92508223d08d18ec8c013e468d89a913/addons/docs/src/frameworks/vue/extractArgTypes.ts#L11-L30

I think `docgenInfo` should be passed into the results of `extractArgTypes`, so then that information can then be used within `inferControls.ts` by accessing `context` arguments.

https://github.com/storybookjs/storybook/blob/424bd38c92508223d08d18ec8c013e468d89a913/lib/client-api/src/inferControls.ts#L60-L65

Coincidentally, `framework` is also available within `context` object.

I'll try to take a stab on this.

**Comment by shilman** [comment]
@adrianpdm Thank you for helping make Storybook better! 🙏  You shouldn't need to pass the docgenInfo to `inferControls`. You just named to make sure that the `argType.name` is `enum` and `argType.value` is the values you want to see in the dropdown.

https://github.com/storybookjs/storybook/blob/next/lib/client-api/src/inferControls.ts#L47-L50

 Please check out [how to contribute](https://storybook.js.org/docs/react/contribute/how-to-contribute) in our docs and feel free to ask questions in `#contributing` in [our Discord](https://discord.gg/storybook).

**Comment by adrianpdm** [comment]
> @adrianpdm Thank you for helping make Storybook better!  You shouldn't need to pass the docgenInfo to `inferControls`. You just named to make sure that the `argType.name` is `enum` and `argType.value` is the values you want to see in the dropdown.
> 
> https://github.com/storybookjs/storybook/blob/next/lib/client-api/src/inferControls.ts#L47-L50
> 
> Please check out [how to contribute](https://storybook.js.org/docs/react/contribute/how-to-contribute) in our docs and feel free to ask questions in `#contributing` in [our Discord](https://discord.gg/storybook).

Hi, thank you for your suggestion.
I believe what you meant by `argType` is actually the "type" property of `ArgType`, IIRC ?. Since, for example, it seems `argType.name` actually refers to the naming of the leftmost column in the ArgsTable.

**Comment by shilman** [comment]
@adrianpdm You're right -- dashed off a quick & sloppy reply 🤦

**Comment by shilman** [comment]
Hurrah!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-beta.5 containing PR #16019 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by heytheretaylor** [comment]
Has this feature been removed? It doesn't seem to be working in v7.0.2
