### ISSUE TITLE
DocsPage: how to change canvas height without mdx?

### ISSUE THREAD

**Issue by krutoo** [storybookjs/storybook#13765]
Hi. How can i change iframe height in docs page for specific story without mdx?

Currently all iframes with stories in docs page has height `100px`

**Comment by gdorsi** [comment]
I've had a similar issue to yours and I've solved the problem by using the story parameters:

```js
export default {
    title: 'Components/Dialog',
    component: Dialog,
    parameters: {
        layout: 'centered',
        docs: { page: Docs, inlineStories: false, iframeHeight: 600 },
    },
}
```

**Comment by krutoo** [comment]
@gdorsi Thank you, really. But when you find its in docs?

**Comment by shilman** [comment]
It's documented here https://github.com/storybookjs/storybook/blob/master/addons/docs/common/README.md#L67

@jonniebigodes At some point soon we need to find a way to get the relevant docs out of the `addon-docs` README files and into the main documentation.

**Comment by kasparsuvi1** [comment]
As from Storybook v7 use like this:
```
export default {
  parameters: {
    docs: {
      story: {
        inline: false,
        iframeHeight: 700,
      },
    },
  },
} as Meta;

```

**Comment by adnanhamzeh** [comment]
@kasparsuvi1 it seems this is causing the source code not to render as expected when you click "Show code". If you remove the inline prop it renders normally again.

**Comment by jkillian** [comment]
If you are using inline stories, something like this works to change story height in docs:

```
export default {
  parameters: {
    docs: {
      story: {
        height: '700px',
      },
    },
  },
}
```
