### ISSUE TITLE
Why I can't export function call in story file?

### ISSUE THREAD

**Issue by hereiscasio** [storybookjs/storybook#13766]
## Describe the bug
If I use something like `export const aaaa = (() => {})()`  in Button.stories.js
then I can see the warning shown in Chrome DevTool Console as
_**Unexpected error while loading ./Button.stories.js: TypeError: Cannot read property 'parameters' of undefined**_
( and the Button Stories can't be shown on SB UI. please see attached image)

## To Reproduce

1. create project (e.g. `yarn create nuxt-app playground`)
2. after project created, install SB by using `npx sb init`
3. Open Button.stories.js
4. Add some script like below
```js
...
export default {
   ...
   includeStories: /^[A-Z]/
}
export const aaaa = (() => {})()
...
```

**Expected behavior**
* I should see Button story on SB UI 
* and I shouldn't see any warning

**Screenshots**
* Bug
![image](https://user-images.githubusercontent.com/44331046/106279339-3aad5380-6277-11eb-86dd-c9b4b2cd60de.png)

* Normal
![image](https://user-images.githubusercontent.com/44331046/106279372-49940600-6277-11eb-95c4-cb292e215e66.png)

**System**
Please paste the results of `npx sb@next info` here.
```
Environment Info:

  System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Binaries:
    Node: 14.15.4 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.10 - /usr/local/bin/npm
  Browsers:
    Chrome: 88.0.4324.96
    Firefox: 84.0.2
    Safari: 14.0.2
  npmPackages:
    @storybook/addon-actions: ^6.1.15 => 6.1.15 
    @storybook/addon-essentials: ^6.1.15 => 6.1.15 
    @storybook/addon-links: ^6.1.15 => 6.1.15 
    @storybook/vue: ^6.1.15 => 6.1.15 
```

**Comment by gaetanmaisse** [comment]
By default, every named export of a story file is considered as a story, and to be valid a story must be a function, see https://storybook.js.org/docs/react/api/csf#named-story-exports.

However, if `aaaa` isn't intended to be a story you can explicitly exclude it with `excludeStories` in the `default` export, details are here: https://storybook.js.org/docs/react/api/csf#non-story-exports

**Comment by shilman** [comment]
@gaetanmaisse they are using `includeStories` in their example, so that should probably work. perhaps it's a bug in `source-loader`? If you disable `addon-essentials` does it work @hereiscasio ?

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
