### ISSUE TITLE
Optional property with an Enum breaks Controlknobs

### ISSUE THREAD

**Issue by seppzero** [storybookjs/storybook#13770]
**Describe the bug**
_**required OR** | works as expected_ 
```javascript
// Storybook renders RadioButtons as Controls
interface Theme {
    variation: 'primary' | 'secondary';
}

```
_**optional OR** | works as expected_
```javascript
// Storybook renders RadioButtons as Controls
interface Theme {
    variation?: 'primary' | 'secondary';
}

```
_**required Enum** | works as expected_
```javascript
// Storybook renders RadioButtons as Controls
enum Variations {
    Primary = 'primary',
    Secondary = 'secondary'
}

interface Theme {
    variation: Variations;
}
```
**_optional Enum | unexpected behaviour_** <-
```javascript
// Storybook renders a TextField as Controls
enum Variations {
    Primary = 'primary',
    Secondary = 'secondary'
}

interface Theme {
    variation?: Variations;
}
```

**Expected behavior**
using an enum with an optional property should render RadioButtons to control the Story

**Comment by ndelangen** [comment]
I believe this got fixed a while back, could you verify on the `next` branch @seppzero ?

**Comment by seppzero** [comment]
> I believe this got fixed a while back, could you verify on the `next` branch @seppzero ?

That was fixed long time ago. Sorry i missed to close the issue back then.
