### ISSUE TITLE
Story without a component / just html

### ISSUE THREAD

**Issue by MickL** [storybookjs/storybook#13783]
**Is your feature request related to a problem? Please describe**
Not sure if this is a feature request or already possible but I wonder if it is possible to create stories for elements that exist only by the use of html/css but dont have a React/Vue/Angular component. 

If this is already possible the feature request might be to add it to the docs.

E.g. a lot of from Bootstrap elements:

```
<button type="button" class="btn btn-primary">Primary</button>
<button type="button" class="btn btn-secondary">Secondary</button>
<button type="button" class="btn btn-success">Success</button>
<button type="button" class="btn btn-danger">Danger</button>
<button type="button" class="btn btn-warning">Warning</button>
```

```
<span class="badge bg-primary">Primary</span>
<span class="badge bg-secondary">Secondary</span>
<span class="badge bg-success">Success</span>
<span class="badge bg-danger">Danger</span>
<span class="badge bg-warning text-dark">Warning</span>
```

This are elements I would like not create an Angular component for. But I would like to create a story to style them with scss and view and approve them in Storybook and also they might be documented there.

**Comment by firestar300** [comment]
I also looking for a solution. I would like to display plain HTML code in my design system.

**Comment by firestar300** [comment]
@MickL I found the addon : https://storybook.js.org/addons/@whitespace/storybook-addon-html

**Comment by MickL** [comment]
Not a bad addition. Anyway I am not sure how to display html elements in storybook. I came up with some solutions, each not optimal.

Lets say we want to create a page with all the buttons as shown above:

1. We may create a component "Buttons" in stories folder and paste in the html code. But if we then create a story it requires to have at least one state. But actually I dont want any states. In the menu there will be "Buttons -> Buttons".
2. We may create a mdx page. Now I have only one menu item which is great. But unfortunately storybook creates adds its own classes to html elements like h1 etc...
