### ISSUE TITLE
Actions / Controls are missing

### ISSUE THREAD

**Issue by MickL** [storybookjs/storybook#13782]
**Describe the bug**
I followed the docs to create my first Angular project with Storybook but following https://storybook.js.org/docs/angular/get-started/whats-a-story there was just no actions / controls tab. 

I found this issue: https://github.com/storybookjs/storybook/issues/1369

Somehow it is closed, even tho the [workaround](https://github.com/storybookjs/storybook/issues/1369#issuecomment-514337359) to fix it from july 2019 has +26 upvotes.

**Comment by jonniebigodes** [comment]
@MickL i'm going to do you one better as your setting up your first project with Storybook. I'm going to update the tutorial for LearnStorybook and Angular as it needs a bit of a polishing. When it's released i'll let you know and you can take a look at it and see if the issue still persists. Sounds good?

Stay safe

**Comment by MickL** [comment]
Not sure if this is related to Angular. Looks like a UI problem to me. Maybe the initial height/width of the window is calculated wrong so the tabs have a height of 0?

**Comment by jonniebigodes** [comment]
@MickL I'm tested this with various Storybook versions and multiple browsers and I was unable to reproduce this. 

Let me know if the issue still persists and I'll gladly re-open it.

Stay safe
