### ISSUE TITLE
Error: Singleton client API not yet initialized...

### ISSUE THREAD

**Issue by IvanovRoman** [storybookjs/storybook#13793]
This error appears. How to fix it? Could there be a problem in the webpack configuration?
> client_api.js:93 Uncaught Error: Singleton client API not yet initialized, cannot call addParameters
    at addParameters (client_api.js:93)
    at Object../node_modules/@storybook/addon-docs/dist/frameworks/common/config.js-generated-other-entry.js (config.js-generated-other-entry.js:35)
    at __webpack_require__ (bootstrap:848)
    at checkDeferredModules (bootstrap:45)
    at Array.webpackJsonpCallback [as push] (bootstrap:32)
    at 3.8b98ff28180af042f9ee.bundle.js:1
addParameters @ client_api.js:93
./node_modules/@storybook/addon-docs/dist/frameworks/common/config.js-generated-other-entry.js @ config.js-generated-other-entry.js:35
__webpack_require__ @ bootstrap:848
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ 3.8b98ff28180af042f9ee.bundle.js:1
client_api.js:83 Uncaught Error: Singleton client API not yet initialized, cannot call addDecorator
    at addDecorator (client_api.js:83)
    at config.js-generated-other-entry.js:24
    at Array.forEach (<anonymous>)
    at Object../node_modules/@storybook/addon-docs/dist/frameworks/react/config.js-generated-other-entry.js (config.js-generated-other-entry.js:23)
    at __webpack_require__ (bootstrap:848)
    at checkDeferredModules (bootstrap:45)
    at Array.webpackJsonpCallback [as push] (bootstrap:32)
    at 4.8b98ff28180af042f9ee.bundle.js:1
addDecorator @ client_api.js:83
(anonymous) @ config.js-generated-other-entry.js:24
./node_modules/@storybook/addon-docs/dist/frameworks/react/config.js-generated-other-entry.js @ config.js-generated-other-entry.js:23
__webpack_require__ @ bootstrap:848
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ 4.8b98ff28180af042f9ee.bundle.js:1
client_api.js:83 Uncaught Error: Singleton client API not yet initialized, cannot call addDecorator
    at addDecorator (client_api.js:83)
    at addDecorator.js-generated-other-entry.js:24
    at Array.forEach (<anonymous>)
    at Object../node_modules/@storybook/addon-actions/dist/preset/addDecorator.js-generated-other-entry.js (addDecorator.js-generated-other-entry.js:23)
    at __webpack_require__ (bootstrap:848)
    at checkDeferredModules (bootstrap:45)
    at Array.webpackJsonpCallback [as push] (bootstrap:32)
    at 5.8b98ff28180af042f9ee.bundle.js:1
addDecorator @ client_api.js:83
(anonymous) @ addDecorator.js-generated-other-entry.js:24
./node_modules/@storybook/addon-actions/dist/preset/addDecorator.js-generated-other-entry.js @ addDecorator.js-generated-other-entry.js:23
__webpack_require__ @ bootstrap:848
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ 5.8b98ff28180af042f9ee.bundle.js:1
client_api.js:111 Uncaught Error: Singleton client API not yet initialized, cannot call addArgTypesEnhancer
    at addArgTypesEnhancer (client_api.js:111)
    at addArgs.js-generated-other-entry.js:43
    at Array.forEach (<anonymous>)
    at Object../node_modules/@storybook/addon-actions/dist/preset/addArgs.js-generated-other-entry.js (addArgs.js-generated-other-entry.js:42)
    at __webpack_require__ (bootstrap:848)
    at checkDeferredModules (bootstrap:45)
    at Array.webpackJsonpCallback [as push] (bootstrap:32)
    at 6.8b98ff28180af042f9ee.bundle.js:1
addArgTypesEnhancer @ client_api.js:111
(anonymous) @ addArgs.js-generated-other-entry.js:43
./node_modules/@storybook/addon-actions/dist/preset/addArgs.js-generated-other-entry.js @ addArgs.js-generated-other-entry.js:42
__webpack_require__ @ bootstrap:848
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ 6.8b98ff28180af042f9ee.bundle.js:1
client_api.js:83 Uncaught Error: Singleton client API not yet initialized, cannot call addDecorator
    at addDecorator (client_api.js:83)
    at addDecorator.js-generated-other-entry.js:24
    at Array.forEach (<anonymous>)
    at Object../node_modules/@storybook/addon-links/dist/preset/addDecorator.js-generated-other-entry.js (addDecorator.js-generated-other-entry.js:23)
    at __webpack_require__ (bootstrap:848)
    at checkDeferredModules (bootstrap:45)
    at Array.webpackJsonpCallback [as push] (bootstrap:32)
    at 7.8b98ff28180af042f9ee.bundle.js:1
addDecorator @ client_api.js:83
(anonymous) @ addDecorator.js-generated-other-entry.js:24
./node_modules/@storybook/addon-links/dist/preset/addDecorator.js-generated-other-entry.js @ addDecorator.js-generated-other-entry.js:23
__webpack_require__ @ bootstrap:848
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ 7.8b98ff28180af042f9ee.bundle.js:1
client_api.js:83 Uncaught Error: Singleton client API not yet initialized, cannot call addDecorator
    at addDecorator (client_api.js:83)
    at addDecorator.js-generated-other-entry.js:24
    at Array.forEach (<anonymous>)
    at Object../node_modules/@storybook/addon-backgrounds/dist/preset/addDecorator.js-generated-other-entry.js (addDecorator.js-generated-other-entry.js:23)
    at __webpack_require__ (bootstrap:848)
    at checkDeferredModules (bootstrap:45)
    at Array.webpackJsonpCallback [as push] (bootstrap:32)
    at 8.8b98ff28180af042f9ee.bundle.js:1
addDecorator @ client_api.js:83
(anonymous) @ addDecorator.js-generated-other-entry.js:24
./node_modules/@storybook/addon-backgrounds/dist/preset/addDecorator.js-generated-other-entry.js @ addDecorator.js-generated-other-entry.js:23
__webpack_require__ @ bootstrap:848
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ 8.8b98ff28180af042f9ee.bundle.js:1
client_api.js:93 Uncaught Error: Singleton client API not yet initialized, cannot call addParameters
    at addParameters (client_api.js:93)
    at Object../node_modules/@storybook/addon-backgrounds/dist/preset/addParameter.js-generated-other-entry.js (addParameter.js-generated-other-entry.js:35)
    at __webpack_require__ (bootstrap:848)
    at checkDeferredModules (bootstrap:45)
    at Array.webpackJsonpCallback [as push] (bootstrap:32)
    at 9.8b98ff28180af042f9ee.bundle.js:1
addParameters @ client_api.js:93
./node_modules/@storybook/addon-backgrounds/dist/preset/addParameter.js-generated-other-entry.js @ addParameter.js-generated-other-entry.js:35
__webpack_require__ @ bootstrap:848
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ 9.8b98ff28180af042f9ee.bundle.js:1
client_api.js:93 Uncaught Error: Singleton client API not yet initialized, cannot call addParameters
    at addParameters (client_api.js:93)
    at Object../.storybook/preview.js-generated-config-entry.js (preview.js-generated-config-entry.js:35)
    at __webpack_require__ (bootstrap:848)
    at checkDeferredModules (bootstrap:45)
    at Array.webpackJsonpCallback [as push] (bootstrap:32)
    at 10.8b98ff28180af042f9ee.bundle.js:1

**Comment by yngvebn** [comment]
@IvanovRoman could you share some of your config? tsconfig, main.ts/js?

**Comment by IvanovRoman** [comment]
main.js
```
const custom = require('./webpack.config.js');

module.exports = {
  "stories": [
    "../src/**/*.stories.mdx",
    "../src/**/*.stories.@(js|jsx|ts|tsx)"
  ],
  logLevel: 'debug',
  "addons": [
    "@storybook/addon-actions",
    "@storybook/addon-links",
    "@storybook/addon-essentials"
  ],
  typescript: {
    check: false,
    checkOptions: {},
    reactDocgen: 'react-docgen-typescript',
    reactDocgenTypescriptOptions: {
      shouldExtractLiteralValuesFromEnum: true,
      propFilter: (prop) => (prop.parent ? !/node_modules/.test(prop.parent.fileName) : true),
    },
  },
  webpackFinal: (config) => {
    return { ...config, module: { ...config.module, rules: custom.rules } };
  },
}
```
webpack.config.json
```
var path = require('path');
var webpack = require('webpack');

module.exports = ({ config }) => ({
  ...config,
      resolve: {
      extensions: ['.ts', '.tsx', '.js'],
      modules: [
        path.resolve('./src'),
        'node_modules'
      ],
      alias: {
        bluebird: path.resolve('node_modules/bluebird/js/browser/bluebird'),
        html2canvas: path.resolve('node_modules/html2canvas/dist/html2canvas.esm')
      }
    },
    entry: {
      ...config.entry,
      styles: './src/entry/styles-examples.scss'
    },
    module: {
      rules: [
        {
          test: /\.tsx?$/,
          use: [
            {
              loader: 'ts-loader',
              options: {
                configFile: path.resolve(__dirname, '../tsconfig.storybook.json'),
                transpileOnly: true
              }
            }
          ]
        },
        {
          test: /\.ttf$/,
          use: [
            {
              loader: 'file-loader',
              options: {
                esModule: false
              }
            }
          ]
        },
        {
          test: /\.scss$/,
          include: /entry/,
          use: ['style-loader', {
              loader: 'css-loader',
              options: {
                import: false,
                url: false
              }
            },
            'postcss-loader',
            'sass-loader']
        },
        {
          test: /\.scss$/,
          exclude: /entry/,
          use: [
            {
              loader: 'dts-css-modules-loader',
              options: {
                namedExport: true,
                banner: "// This file is generated automatically"
              }
            },
            {
              loader: 'css-loader',
              options: {
                modules: true,
                camelCase: 'only',
                localIdentName: '[local]',
                import: false,
                url: false,
                exportOnlyLocals: true
              }
            },
            'sass-loader'
          ]
        },
        {
          test: /\.css$/,
          use: ['style-loader', 'css-loader']
        },
        {
          test: /\.svg$/,
          use: 'null-loader'
        }
      ]
    },

    plugins: [
      ...config.plugins,
      new webpack.ProvidePlugin({
        Promise: 'bluebird'
      }),
      new webpack.DefinePlugin({
        'process.env.TESTS': JSON.stringify(false)
      }),
    ]
});
```

> @IvanovRoman could you share some of your config? tsconfig, main.ts/js?

**Comment by IvanovRoman** [comment]
main.js
```
const custom = require('./webpack.config.js');

module.exports = {
  "stories": [
    "../src/**/*.stories.mdx",
    "../src/**/*.stories.@(js|jsx|ts|tsx)"
  ],
  logLevel: 'debug',
  "addons": [
    "@storybook/addon-actions",
    "@storybook/addon-links",
    "@storybook/addon-essentials"
  ],
  typescript: {
    check: false,
    checkOptions: {},
    reactDocgen: 'react-docgen-typescript',
    reactDocgenTypescriptOptions: {
      shouldExtractLiteralValuesFromEnum: true,
      propFilter: (prop) => (prop.parent ? !/node_modules/.test(prop.parent.fileName) : true),
    },
  },
  webpackFinal: (config) => {
    return { ...config, module: { ...config.module, rules: custom.rules } };
  },
}
```
webpack.config.json
```
var path = require('path');
var webpack = require('webpack');

module.exports = ({ config }) => ({
  ...config,
      resolve: {
      extensions: ['.ts', '.tsx', '.js'],
      modules: [
        path.resolve('./src'),
        'node_modules'
      ],
      alias: {
        bluebird: path.resolve('node_modules/bluebird/js/browser/bluebird'),
        html2canvas: path.resolve('node_modules/html2canvas/dist/html2canvas.esm')
      }
    },
    entry: {
      ...config.entry,
      styles: './src/entry/styles-examples.scss'
    },
    module: {
      rules: [
        {
          test: /\.tsx?$/,
          use: [
            {
              loader: 'ts-loader',
              options: {
                configFile: path.resolve(__dirname, '../tsconfig.storybook.json'),
                transpileOnly: true
              }
            }
          ]
        },
        {
          test: /\.ttf$/,
          use: [
            {
              loader: 'file-loader',
              options: {
                esModule: false
              }
            }
          ]
        },
        {
          test: /\.scss$/,
          include: /entry/,
          use: ['style-loader', {
              loader: 'css-loader',
              options: {
                import: false,
                url: false
              }
            },
            'postcss-loader',
            'sass-loader']
        },
        {
          test: /\.scss$/,
          exclude: /entry/,
          use: [
            {
              loader: 'dts-css-modules-loader',
              options: {
                namedExport: true,
                banner: "// This file is generated automatically"
              }
            },
            {
              loader: 'css-loader',
              options: {
                modules: true,
                camelCase: 'only',
                localIdentName: '[local]',
                import: false,
                url: false,
                exportOnlyLocals: true
              }
            },
            'sass-loader'
          ]
        },
        {
          test: /\.css$/,
          use: ['style-loader', 'css-loader']
        },
        {
          test: /\.svg$/,
          use: 'null-loader'
        }
      ]
    },

    plugins: [
      ...config.plugins,
      new webpack.ProvidePlugin({
        Promise: 'bluebird'
      }),
      new webpack.DefinePlugin({
        'process.env.TESTS': JSON.stringify(false)
      }),
    ]
});
```

tsconfig.storybook.json
```
{
  "compilerOptions": {
    "target": "esnext",
    "module": "commonjs",
    "allowJs": true,
    "noEmit": true,
    "sourceMap": true,
    "removeComments": false,
    "jsx": "react",
    "moduleResolution": "node",
    "noUnusedLocals": true,
    "noUnusedParameters": false,
    "baseUrl": "./src",
    "importHelpers": true,
    "noEmitHelpers": true,
    "skipLibCheck": true,
    "strict": true,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "suppressImplicitAnyIndexErrors": true,
    "strictBindCallApply": true,
    "isolatedModules": true,
    "experimentalDecorators": true,
    "typeRoots": ["@types","./typings"],
    "types": [
      "bluebird-global",
      "d3",
      "draft-js",
      "facebook-js-sdk",
      "gapi.auth2",
      "gapi",
      "global",
      "jasmine-ajax",
      "jasmine",
      "mathjax",
      "monaco-editor",
      "react-dom",
      "react-transition-group",
      "react",
      "three"
    ]
  },
  "include": [
    "src/**/*"
  ]
}

```

**Comment by IvanovRoman** [comment]
> @IvanovRoman could you share some of your config? tsconfig, main.ts/js?

main.js
```
const custom = require('./webpack.config.js');

module.exports = {
  "stories": [
    "../src/**/*.stories.mdx",
    "../src/**/*.stories.@(js|jsx|ts|tsx)"
  ],
  logLevel: 'debug',
  "addons": [
    "@storybook/addon-actions",
    "@storybook/addon-links",
    "@storybook/addon-essentials"
  ],
  typescript: {
    check: false,
    checkOptions: {},
    reactDocgen: 'react-docgen-typescript',
    reactDocgenTypescriptOptions: {
      shouldExtractLiteralValuesFromEnum: true,
      propFilter: (prop) => (prop.parent ? !/node_modules/.test(prop.parent.fileName) : true),
    },
  },
  webpackFinal: (config) => {
    return { ...config, module: { ...config.module, rules: custom.rules } };
  },
}
```
webpack.config.json
```
var path = require('path');
var webpack = require('webpack');

module.exports = ({ config }) => ({
  ...config,
      resolve: {
      extensions: ['.ts', '.tsx', '.js'],
      modules: [
        path.resolve('./src'),
        'node_modules'
      ],
      alias: {
        bluebird: path.resolve('node_modules/bluebird/js/browser/bluebird'),
        html2canvas: path.resolve('node_modules/html2canvas/dist/html2canvas.esm')
      }
    },
    entry: {
      ...config.entry,
      styles: './src/entry/styles-examples.scss'
    },
    module: {
      rules: [
        {
          test: /\.tsx?$/,
          use: [
            {
              loader: 'ts-loader',
              options: {
                configFile: path.resolve(__dirname, '../tsconfig.storybook.json'),
                transpileOnly: true
              }
            }
          ]
        },
        {
          test: /\.ttf$/,
          use: [
            {
              loader: 'file-loader',
              options: {
                esModule: false
              }
            }
          ]
        },
        {
          test: /\.scss$/,
          include: /entry/,
          use: ['style-loader', {
              loader: 'css-loader',
              options: {
                import: false,
                url: false
              }
            },
            'postcss-loader',
            'sass-loader']
        },
        {
          test: /\.scss$/,
          exclude: /entry/,
          use: [
            {
              loader: 'dts-css-modules-loader',
              options: {
                namedExport: true,
                banner: "// This file is generated automatically"
              }
            },
            {
              loader: 'css-loader',
              options: {
                modules: true,
                camelCase: 'only',
                localIdentName: '[local]',
                import: false,
                url: false,
                exportOnlyLocals: true
              }
            },
            'sass-loader'
          ]
        },
        {
          test: /\.css$/,
          use: ['style-loader', 'css-loader']
        },
        {
          test: /\.svg$/,
          use: 'null-loader'
        }
      ]
    },

    plugins: [
      ...config.plugins,
      new webpack.ProvidePlugin({
        Promise: 'bluebird'
      }),
      new webpack.DefinePlugin({
        'process.env.TESTS': JSON.stringify(false)
      }),
    ]
});
```

tsconfig.storybook.json
```
{
  "compilerOptions": {
    "target": "esnext",
    "module": "commonjs",
    "allowJs": true,
    "noEmit": true,
    "sourceMap": true,
    "removeComments": false,
    "jsx": "react",
    "moduleResolution": "node",
    "noUnusedLocals": true,
    "noUnusedParameters": false,
    "baseUrl": "./src",
    "importHelpers": true,
    "noEmitHelpers": true,
    "skipLibCheck": true,
    "strict": true,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "suppressImplicitAnyIndexErrors": true,
    "strictBindCallApply": true,
    "isolatedModules": true,
    "experimentalDecorators": true,
    "typeRoots": ["@types","./typings"],
    "types": [
      "bluebird-global",
      "d3",
      "draft-js",
      "facebook-js-sdk",
      "gapi.auth2",
      "gapi",
      "global",
      "jasmine-ajax",
      "jasmine",
      "mathjax",
      "monaco-editor",
      "react-dom",
      "react-transition-group",
      "react",
      "three"
    ]
  },
  "include": [
    "src/**/*"
  ]
}

```

**Comment by IvanovRoman** [comment]
> @IvanovRoman could you share some of your config? tsconfig, main.ts/js?

I tried remove node_modules and yarn install. This not helped.

**Comment by jonluca** [comment]
I see you closed this - were you able to figure out what the underlying issue was @IvanovRoman?
