### ISSUE TITLE
Addon-docs doesn't display props when component is defined as a React.ComponentType

### ISSUE THREAD

**Issue by lbonanni** [storybookjs/storybook#13800]
**Describe the bug**
We're using TypeScript and the addon-docs to display some documentation.

The problem we have is that it doesn't display the component props when it is defined as a `React.ComponentType` and displays the following message instead:

> "No inputs found for this component. Read the docs".

**Expected behavior**
It displays the table with all props types.

**Code snippets**

_Footer.gen.tsx_

```tsx
import * as React from 'react';
const FooterBS = require('./Footer.bs');

export type Props = { readonly newsletterRegisterUrl: string; readonly newsletterSource?: string };

export const make: React.ComponentType<{ readonly newsletterRegisterUrl: string; readonly newsletterSource?: string }> = FooterBS.make;
```

_footer.stories.js_

```jsx
import * as React from 'react';
import { make as Footer } from '../../../src/organism/footer/Footer.gen';

export const test = () => <Footer />;

export default {
    title: 'My footer',
    component: Footer,
};
```

**System**
 System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz
  Binaries:
    Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.3/bin/npm
  Browsers:
    Chrome: 88.0.4324.96
    Firefox: 84.0.2
    Safari: 13.1.2
  npmPackages:
    @storybook/addon-actions: ^6.1.16 => 6.1.16 
    @storybook/addon-docs: 6.1.16 => 6.1.16 
    @storybook/addon-viewport: ^6.1.16 => 6.1.16 
    @storybook/addons: 6.1.16 => 6.1.16 
    @storybook/react: 6.1.16 => 6.1.16

**Additional context**
If we replace in the code snippet `React.ComponentType` by `React.FunctionComponent`, it works. 

However, we can't easily do that since the TypeScript file is generated from a tool called [gentype](https://github.com/reason-association/genType) coming from the ReasonML ecosystem. Our project is built in Reason, then compiled to TypeScript to generate the stories.. We don't have control over this compilation process.

**Comment by shilman** [comment]
This is probably a limitation of `react-docgen-typescript`, which we use under the hood. Please consider filing an issue there instead.

**Comment by lbonanni** [comment]
Alright, thank you 🙂 
We finally found another solution using [typedoc](https://typedoc.org/)
