### ISSUE TITLE
Replacment for files knob?

### ISSUE THREAD

**Issue by Tom4U** [storybookjs/storybook#13802]
Because _controls_ are more or less the replacement for _knobs_, I was wondering what the replacement (control type) for the _files_ knob would be!?  And if no replacement exists: Can we use it with _argTypes_?
Couldn't find anything about it in documentation and on the web. Maybe you should suggest which knobs still need to be used and which are replaced or will be replaced in future.

**Comment by shilman** [comment]
Closing as duplicate to #13004
