### ISSUE TITLE
[addon-design-assets]: Update docs

### ISSUE THREAD

**Issue by iwan-uschka** [storybookjs/storybook#13806]
**Is your feature request related to a problem? Please describe**
It's possible to add assets like this

```
Story.parameters = {
  assets: [
    { name: "Mobile", url: require("./path/to/file1.jpg") },
    { name: "Tablet", url: require("./path/to/file1.jpg") },
    {
      name: "Desktop",
      url: require("./path/to/file1.jpg"),
    },
  ],
};
```

which is pretty cool. The documentation tells me nothing about the option of giving the asset a name.

**Comment by shilman** [comment]
we're probably going to deprecate this addon in favor of https://github.com/pocka/storybook-addon-designs
