### ISSUE TITLE
[addon-design-assets]: asset select button is not highlighted automatically

### ISSUE THREAD

**Issue by iwan-uschka** [storybookjs/storybook#13805]
**Describe the bug**
When adding multiple assets the first asset is shown automatically but the related button at the bottom right is not highlighted automatically.

**To Reproduce**
Add some assets like

```
Story.parameters = {
  assets: [
    { name: "Mobile", url: require("./path/to/file1.jpg") },
    { name: "Tablet", url: require("./path/to/file1.jpg") },
    {
      name: "Desktop",
      url: require("./path/to/file1.jpg"),
    },
  ],
};
```

Select "Design Assets" tab in storybook and check it out.

**Expected behavior**
Related button is highlighted.

**Screenshots**
![Bildschirmfoto 2021-02-03 um 19 05 50](https://user-images.githubusercontent.com/2256579/106789656-da415c00-6652-11eb-9556-4b2dc6faefa5.png)

**System**
```
"@storybook/addon-actions": "^6.1.14",
"@storybook/addon-design-assets": "^6.1.16",
"@storybook/addon-essentials": "^6.1.14",
"@storybook/addon-links": "^6.1.14",
"@storybook/addon-viewport": "^6.1.14",
"@storybook/react": "^6.1.14",
```

**Additional context**

**Comment by shilman** [comment]
we're going to deprecate this addon and are recommending https://github.com/pocka/storybook-addon-designs. closing.
