### ISSUE TITLE
Element loses styles when updating the props.

### ISSUE THREAD

**Issue by ysouzas** [storybookjs/storybook#13804]
**Describe the bug**
When I update an input, the component loses all classes and just stays with the class that represents the new input

**To Reproduce**

1. Declare a component
2. Change the input using the addons
3. See error

**Expected behavior**
It was supposed to just update the input that was modified without changing the classes

**Screenshots**
Element in the initial state:

![image](https://user-images.githubusercontent.com/6200092/106784656-7ca61300-6644-11eb-9236-29da85f3ec77.png)

![image](https://user-images.githubusercontent.com/6200092/106784369-2933c500-6644-11eb-9eef-21cb7e93dcf9.png)

After updating fieldSize:
![image](https://user-images.githubusercontent.com/6200092/106784764-9b0c0e80-6644-11eb-9bc7-1397790f2b6b.png)

![image](https://user-images.githubusercontent.com/6200092/106784707-8cbdf280-6644-11eb-81b5-eed812375d26.png)

**Code snippets**

```TypeScript
// storybook
import { Meta, moduleMetadata, Story } from '@storybook/angular';

// component
import { InputComponent } from '../input/input.component';

export default {
  title: 'Components/Input',
  component: InputComponent,
  decorators: [
    moduleMetadata({
      declarations: [InputComponent],
    }),
  ],
} as Meta;

const Story: Story<InputComponent> = (args: InputComponent) => ({
  props: args,
  template: `
          <app-input
            [type]="type"
            [fieldSize]="fieldSize"
            [shape]="shape"
            [status]="status"
            [attributes]="attributes"
            [icon]="icon"
            [iconPack]="iconPack"
            [placeholder]="placeholder"
          >
          </app-input>
       `,
});

export const Info = Story.bind({});
Info.args = {
  type: 'number',
  fieldSize: 'giant',
  shape: 'semi-round',
  status: 'info',
  placeholder: 'Info',
};
```

**System**
```
    OS: macOS 11.2
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 15.7.0 - ~/.nvm/versions/node/v15.7.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.4.3 - ~/.nvm/versions/node/v15.7.0/bin/npm
  Browsers:
    Chrome: 88.0.4324.96
    Safari: 14.0.3
  npmPackages:
    @storybook/addon-actions: ^6.1.15 => 6.1.15 
    @storybook/addon-essentials: ^6.1.15 => 6.1.15 
    @storybook/addon-links: ^6.1.15 => 6.1.15 
    @storybook/angular: ^6.1.15 => 6.1.15 
```

**Additional context**
When i remove ` changeDetection: ChangeDetectionStrategy.OnPush` the component doesn't load the styles from beginning

**Comment by impurity-dev** [comment]
Were you able to find a fix for this or work around?
