### ISSUE TITLE
Storybook does not support `declare` TypeScript interface

### ISSUE THREAD

**Issue by temurih** [storybookjs/storybook#13818]
**Describe the bug**

I get it, Storybook is not meant to support TypeScript. I am ok with it. But it should support basics of TS. One of them is `declare`, all you have to do is ignore it wherever you find. I don't think it should be hard to implement.

![image](https://user-images.githubusercontent.com/3893769/106943027-1e2f7200-66e2-11eb-975c-4182ca0eddf3.png)

**To Reproduce**

Just add the following and try to compile with Storybook,

```
declare global {
    interface Window {
        something?: {
            open: (config: object, id: string) => unknown;
        };
    }
}
```

**Expected behavior**

Just ignore wherever it finds `declare`

**Version**

Storybook 6.1.17
"@storybook/addon-essentials": "^6.1.17",
"@storybook/addon-info": "^5.3.21",
"@storybook/addon-links": "^6.1.17",
"@storybook/addons": "^6.1.17",
"@storybook/preset-create-react-app": "3.1.5",
"@storybook/react": "^6.1.17",

**Comment by phated** [comment]
`declare` syntax can only be used in `.d.ts` files, as per https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html, but you've tried to specify it in a `.tsx` file.

**Comment by temurih** [comment]
@phated, ok!!! I am not sure about that, because I can use it in any file and it compiles just fine. But anyway, let that go. What do you think about `entends`? Where that should be used in your opinion?

![image](https://user-images.githubusercontent.com/3893769/107910576-f3ca8980-6f17-11eb-9481-a75ae47379a2.png)
