### ISSUE TITLE
[addon-storyshots] Warning: DeprecationWarning: \`storyFn\`  is deprecated and will be removed in Storybook 7.0 appears in all storyshots on version 6.1.16

### ISSUE THREAD

**Issue by Kryword** [storybookjs/storybook#13815]
**Describe the bug**
A warning is being shown when using initSnapshots with jest with the following message: Warning: DeprecationWarning: \`storyFn\` is deprecated and will be removed in Storybook 7.0.
With this link as helping message: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-storyfn

Doing a bit of research, I detected this is due to how story.render method is being set by the storyshots addon. It seems that this method is set to story.storyFn instead of the newer API, story.unboundStoryFn. And when story is rendered, that method is executed generating this warning.

**To Reproduce**

1. Create a initStoryshots jest test, with at least one valid story.
2. Execute this initStoryshots jest test.
3. Check terminal, a console.error with the warnings will be shown.

**Expected behavior**
No deprecation warning should appear when running initSnapshots if stories are alright.

**Code snippets**
```
initStoryshots({
  configPath: confDir,
  stories2snapsConverter: new CustomStories2SnapsConverter(),
  // create a snapshot per story instead of one for all of them
  test: ({ story, context, done }) => {
    const filename = converter.getSnapshotFileName(context);

    // Necessary unboundStoryFn to avoid this warning:
    // This shouldn't be necessary once storyFn method is removed in Storybook 7.0
    // When that happens, story.render, should be enough
    const renderContext = await story.applyLoaders();
    const renderer = create(story.unboundStoryFn(renderContext)); // This was previously create(story.render), which failed with that console warning

    // eslint-disable-next-line jest/no-standalone-expect
    expect(renderer.toJSON()).toMatchSpecificSnapshot(filename);
    renderer.unmount();
  }
});
```

**System**
Environment Info:
```
  System:
    OS: Linux 5.8 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
  Binaries:
    Node: 14.15.3 - ~/.nvm/versions/node/v14.15.3/bin/node
    npm: 6.14.9 - ~/.nvm/versions/node/v14.15.3/bin/npm
  Browsers:
    Chrome: 88.0.4324.146
    Firefox: 85.0
```

**Additional context**
Let me know if there's something missing in this bug report and if it is necessary to provide more context. I'm open to help with what I can.

I would also highly recommend start checking here: https://github.com/storybookjs/storybook/blob/next/addons/storyshots/storyshots-core/src/api/index.ts#L61
Where this render = storyFn is set.

**Comment by shilman** [comment]
closing as dupe to #12703
