### ISSUE TITLE
Canvas/Preview blocks have a fixed height in Firefox

### ISSUE THREAD

**Issue by ranmaru22** [storybookjs/storybook#13814]
**Describe the bug**
When wrapping code with a custom web component sample inside a `Canvas` block (using storybook/html), those have some fixed height in Firefox. If the content is larger than that height, Firefox defaults to creating a scrollable frame instead of adjusting the frame height.

Wrapping a `div` with some explicit height around it works, but that's only a half-solution because it prevents using the block with components which change in size.

**To Reproduce**
1. Create an MDX story with a `Canvas` block.
2. Put a custom component that isn't wrapped inside a container with explicit height and will render over multiple lines inside the `Canvas`.
3.  View it in Firefox.

(This also happens when using `Preview` instead of `Canvas`.)

**Expected behavior**
Have the container be the proper size to show all initial contents, plus resize when the contents change.

**Screenshots**
How it looks in Firefox:
![image](https://user-images.githubusercontent.com/16521734/106913477-521b8f00-6704-11eb-80e8-7c15b89c4389.png)

How it looks in Chromium/Edge/Safari:
![image](https://user-images.githubusercontent.com/16521734/106913544-6495c880-6704-11eb-9683-b54cba55f27d.png)

This seems to be related to the `div` that sits above `innerZoomElementWrapper`. In Firefox, it has a set height along with some other props:
![image](https://user-images.githubusercontent.com/16521734/106915598-7e380f80-6706-11eb-994e-59f8b40c318c.png)

... while in Chromium it doesn't:
![image](https://user-images.githubusercontent.com/16521734/106915673-94de6680-6706-11eb-99c1-ed0b6a469485.png)

If I remove the `height` property, it renders as expected.

**Code**:
This does not work, the custom component does not have an explicit height:
```tsx
<Canvas>
  <my-list>
    <my-list-item>Single-line item</my-list-item>
    <my-list-item>Single-line item</my-list-item>
    <my-list-item>Single-line item</my-list-item>
  </my-list>
</Canvas>
```

The `my-list` component has a dynamic height, defined such as:
```css
:host {
    position: relative;
    display: flex;
    flex-direction: column;
    justify-content: start;
    height: var(--client-height, auto);
    transition: height 250ms ease-out;
}
```
... where `--client-height` is calculated depending on how many elements are inside the slot.

This for instance does work correctly, the outermost element now has an explicit height:
```tsx
<Canvas>
<div style={{ height: '168px' }}>
  <my-list>
    <my-list-item>Single-line item</my-list-item>
    <my-list-item>Single-line item</my-list-item>
    <my-list-item>Single-line item</my-list-item>
  </my-list>
</div>
</Canvas>
```

But the aforementioned container still has a fixed height, only this time it's bigger than the `div`'s, so it does show everything.

**System**
```
  System:
    OS: macOS 11.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 15.5.0 - /usr/local/bin/node
    npm: 7.3.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 88.0.4324.96
    Edge: 88.0.705.56
    Firefox: 84.0
    Safari: 14.0.2
  npmPackages:
    @storybook/addon-docs: ^6.1.16 => 6.1.16
    @storybook/addon-viewport: ^6.1.16 => 6.1.16
    @storybook/html: ^6.1.16 => 6.1.16
```

**Comment by Tonyhliu** [comment]
+1

**Comment by shilman** [comment]
Closing as duplicate to #8112

**Comment by shuieryin** [comment]
I had the same issue, this is what I did as workaround in react.

```javascript
useEffect(() => {
    // strangely a fixed height is generated only in Firefox, so unset it to fix the display issue
    const containerElement = document.getElementById(
        "innerZoomElementWrapper"
    )?.parentNode;
    if (containerElement instanceof HTMLDivElement) {
        containerElement.style.height = "unset";
    }
}, []);
```
