### ISSUE TITLE
can't import nested libs

### ISSUE THREAD

**Issue by stewones** [storybookjs/storybook#13829]
**Describe the bug**
Not able to import a local lib that relies on another local lib
ie a component with has story which imports < a lib which imports  < another lib

**To Reproduce**

1. clone this repo https://github.com/stewones/storybug
2. npm install
3. npx nx run ui:storybook
4. See warning
```
WARNING in ./libs/core/src/lib/core.module.ts 22:57-71
"export 'AnotherOptions' was not found in '@org/another'
 @ ./libs/core/src/index.ts
 @ ./libs/ui/src/lib/todos/todos.component.ts
 @ ./libs/ui/src/lib/todos/todos.component.stories.ts
 @ ./libs/ui/src/lib sync ^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.(js|jsx|ts|tsx))$
 @ ./libs/ui/.storybook/generated-stories-entry.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./libs/ui/.storybook/storybook-init-framework-entry.js ./libs/ui/.storybook/preview.js-generated-config-entry.js ./libs/ui/.storybook/generated-stories-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=true ./apps/apper/src/styles.scss

```

**Expected behavior**
sb to build correctly and work without any warning

**Screenshots**
![Screen Shot 2021-02-05 at 19 17 10](https://user-images.githubusercontent.com/719763/107095002-ce869e80-67e6-11eb-8486-e2719e90b3b8.png)

**System**
```
Environment Info:

  System:
    OS: macOS 11.1
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
  Binaries:
    Node: 12.14.0 - ~/.nvm/versions/node/v12.14.0/bin/node
    npm: 6.13.4 - ~/.nvm/versions/node/v12.14.0/bin/npm
  Browsers:
    Chrome: 88.0.4324.150
    Safari: 14.0.2
  npmPackages:
    @storybook/addon-knobs: ^6.1.11 => 6.1.17 
    @storybook/angular: ^6.1.11 => 6.1.17 
```

**Comment by stewones** [comment]
fixed with the new typescript feature `Type-Only Imports and Export`
https://devblogs.microsoft.com/typescript/announcing-typescript-3-8-beta/#type-only-imports-exports

related issue
https://github.com/storybookjs/storybook/issues/13504#issuecomment-752212029

**Comment by shilman** [comment]
This is because Storybook uses `babel` for typescript processing, rather than `tsc`. `tsc` processes the entire project so it can distinguish types even without special imports. `babel`, on the other hand, gets tripped up because the types are stripped from the bundled output and it doesn't have enough info to distinguish between types and non-types in your imports.
