### ISSUE TITLE
Storybook and SystemJs

### ISSUE THREAD

**Issue by MatthijsBe** [storybookjs/storybook#13824]
Hi Everyone, 

For a Single Spa project we added storybook, but we stumble on the fact that we can't/don't know how to use systemJs in storybook to include external components.

I've tried to add systemJs within the preview-head.html and preview-body.html, just like we have in our root-app.

But when I import components from `@projectName/sharedcomponents` inside the story, storybook will give the error:

Module not found: Error: Can't resolve '@projectName/sharedcomponents'.

When I inspect the sources, I see that sharedcomponents.js is loaded successfully, the scripts are also loaded inside the storybook Iframe.

Any of you know what is going wrong? 

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/addon-actions: "^6.2.0-alpha.20",
- @storybook/addon-essentials: "^6.2.0-alpha.20",
- @storybook/addon-links: "^6.2.0-alpha.20",
- @storybook/addon-storysource: "^v6.2.0-alpha.20",
- @storybook/vue3: "^6.2.0-alpha.20",
- "vue-loader": "^16.1.2"

### Screenshots / Screencast / Code Snippets (Optional)

preview-head.html
```html
<meta name="importmap-type" content="systemjs-importmap" />
<script type="systemjs-importmap">
  {
    "imports": {
      "@projectName/sharedcomponents": "[url to sharedcomponents.js]",
      "vue": "https://cdn.jsdelivr.net/npm/vue@3.0.5/dist/vue.runtime.global.prod.js"
    }
  }
</script>
<script src="https://cdn.jsdelivr.net/npm/systemjs@6.8.0/dist/system.js"></script>
````

preview-body.html
```html
<div id="custom-root">
  <script> 
    System.import('@projectName/shared-components')
    System.import('vue') 
  </script>
</div> 
```

**Comment by waterstar** [comment]
Having exactly the same issue. Any luck to work around it?

**Comment by MatthijsBe** [comment]
@waterstar  We created a work around for this, we created an npm package from the "sharedComponents" project mentioned above.

**Comment by nilzona** [comment]
> @waterstar We created a work around for this, we created an npm package from the "sharedComponents" project mentioned above.

how did that help you? did you not include SystemJS in your storybook at all?

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
