### ISSUE TITLE
Docs - Working Example for Angular 

### ISSUE THREAD

**Issue by Carsten750** [storybookjs/storybook#13823]
I always get frustrated when I try to write a story with mdx. On this page, I always get React examples: https://storybook.js.org/docs/angular/api/argtypes

Please provide one or more examples in Angular.

React: 

```
<!--- Checkbox.stories.mdx -->

import { Meta, Story, Canvas } from '@storybook/addon-docs/blocks';
import { Checkbox } from './Checkbox';

<Meta title="MDX/Checkbox" component={Checkbox} />

# Checkbox

With `MDX` we can define a story for `Checkbox` right in the middle of our
Markdown documentation.

<!--- This is your Story template function, shown here in React -->

export const Template = (args) => <Checkbox {...args} />

<Canvas>
  <Story name="Unchecked" args={{ 
      label: 'Unchecked'
    }}>
    {Template.bind({})}
   </Story>
  <Story name="Checked" args={{ 
      label: 'Unchecked', 
      checked: true 
    }}>
    {Template.bind({})}
   </Story>
  <Story name="Secondary" args={{
    label: 'Secondary', 
    checked: true, 
    appearance: 'secondary'
  }}>
    {Template.bind({})}
   </Story>
</Canvas>
```

Angular???

```
import { Meta, Story, Canvas } from '@storybook/addon-docs/blocks';
import { Example } from './Example';

<Meta title="MDX/Example" component={Example} />

# Example

<!--- What should I do? -->

export const Template = () => ({
  template: `
    <div>Example</div>
  `
})

<Canvas>
  <Story name="Example" args={{
    label: 'Example'
  }}>
    {Template.bind({})}
  </Story>
</Canvas>
```

In the best case I get error messages like these:

```
zone.js:690 Unhandled Promise rejection: Cannot read property 'id' of undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'id' of undefined
    at Canvas.js:85
    at Array.map (<anonymous>)
    at getPreviewProps (Canvas.js:84)
```

**Comment by ld210** [comment]
It's very frustrating.  To have a single mdx file for both stories and documentation is an awesome feature, but i can't get it to work properly because of lack of information / code examples.

**Comment by shilman** [comment]
Simple example here: https://github.com/storybookjs/storybook/pull/14597

**Comment by ld210** [comment]
Thanks. This page also helped me a lot : https://github.com/storybookjs/storybook/tree/master/addons/docs/angular#docspage
Using the inline rendering solved a lot of issues...

**Comment by shilman** [comment]
ZOMG!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.3.0-alpha.8 containing PR #14597 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
