### ISSUE TITLE
[addon-docs][source] Support Angular style template syntax in DocsPage source

### ISSUE THREAD

**Issue by CTCTIPragg** [storybookjs/storybook#13839]
Storybook Version: 6.1.14

Syntax highlighting in DocsPage Source is not all the way there for Angular components, it is usable but it would be nice to have the opening tag also detected.

Ideal solutions:
* The ability to detect Angular style syntax
* The ability to turn off syntax highlighting

**Additional context**
![image](https://user-images.githubusercontent.com/38093909/107302436-45bb7b80-6ae2-11eb-9aee-81e012c2b427.png)

**Comment by shilman** [comment]
Great Caesar's ghost!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.0-alpha.25 containing PR #13869 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
