### ISSUE TITLE
Can't get all the controls and docs of third party component

### ISSUE THREAD

**Issue by vitorcamachoo** [storybookjs/storybook#13835]
**Describe the bug**
I'm trying to generate all the available control props of an external library component (`materia-ui`), but somehow, it don't generate the docs and controls.

**To Reproduce**
With the following setup I can't get all the controls:

// Button.stories.tsx
```tsx
import React from 'react'
import Button, { ButtonProps } from '@material-ui/core/Button'

export default {
  component: Button,
  title: 'Button',
}

const Template = (args: ButtonProps) => <Button {...args} />

export const Default = Template.bind({})
Default.args = { children: 'Basic' }
```
<img width="568" alt="Screenshot 2021-02-08 at 12 19 00" src="https://user-images.githubusercontent.com/20595956/107218665-d709ef80-6a07-11eb-8488-b65e8356fc61.png">

But, if I create a component called Button, which the implementation is only spread the props to the material-ui Button, it works:

// Button.tsx
```tsx
import React from 'react'
import Button, { ButtonProps } from '@material-ui/core/Button'

export function App({ children, ...buttonProps }: ButtonProps) {
  return <Button {...buttonProps}>{children}</Button>
}

export default App
```

// Button.stories.tsx
```tsx
import React from 'react'
import Button from './Button'

export default {
  component: Button,
  title: 'Button',
}

const Template = (args) => <Button {...args} />

export const Default = Template.bind({})
Default.args = { children: 'Basic' }
```
<img width="623" alt="Screenshot 2021-02-08 at 12 21 41" src="https://user-images.githubusercontent.com/20595956/107218913-3536d280-6a08-11eb-9552-cfdf4189c796.png">

Am I doing anything wrong? Thanks!

**Comment by shilman** [comment]
closing as dupe to #12185
