### ISSUE TITLE
[Yarn workspace]: Storybook is unresponsive after using the controls inputs

### ISSUE THREAD

**Issue by fcisio** [storybookjs/storybook#13841]
**Describe the bug**
I run Storybook in a yarn workspace, everything is set up right. I have no other issues or console errors.

Whether I use `yarn start-storybook` or serve the build, the app gets unresponsive after only about 6-8 character input in any controls field. I'm unsure yet if this issue comes from my workspace or something else.

Is anyone experiencing this issue?
Anyone as pointers to debug this, as there is not error outputted?

The whole app just freezes and stop responding.

**Expected behavior**
The app should not freeze at any point when playing with the controls fields

**Screenshots**
https://user-images.githubusercontent.com/46095852/107306307-a26f5580-6a52-11eb-812d-738c6e0dbdcc.mov

**System**
System:
    OS: macOS 11.1
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  Binaries:
    Node: 14.15.4 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.10 - /usr/local/bin/npm
  Browsers:
    Chrome: 88.0.4324.150
    Firefox: 85.0
    Safari: 14.0.2

**Comment by fcisio** [comment]
Also noticed that the issue is not present on IOS for some reason

**Comment by fcisio** [comment]
Never mind this issue, I was able to find that this addon was the source of problems:
[Pseudo States](https://github.com/chromaui/storybook-addon-pseudo-states)

**Comment by shilman** [comment]
cc @ghengeveld

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
