### ISSUE TITLE
cjs file extension will be load over js extension even when require is used

### ISSUE THREAD

**Issue by othke** [storybookjs/storybook#13854]
**Describe the bug**
Storybook configuration load the mjs files over js files.
While using a npm module (commonjs), if this module require another dependency that have both js and mjs build, storybook configuration (webpack or ts ?) will make the mjs loaded over the js file.

**To Reproduce**

- use create-react-app with typescript
`npx create-react-app my-app --template typescript
`

- install story book
`npx sb init
`

- Instead of using packages in node_modules, let's create 2 libs foo and bar where foo require bar

```javascript
//lib/foo/index.js
const Bar = require('../bar')
module.exports = function Foo () { console.log("Hey I am Foo in js"); Bar()  }
```

```javascript
//lib/bar/index.js
module.exports = function Bar () { console.log("Hey I am Bar in js") }
```

```javascript
//lib/bar/index.mjs
export default function Bar () { console.log("Hey I am Bar in mjs")}
```

```javascript
//lib/bar/index.mjs
export default function Bar () { console.log("Hey I am Bar in mjs")}
```

```javascript
//src/stories/Button.stories.tsx
// Try to add this code to load lib
import Foo from '../lib/foo'
console.log({Foo})
console.log(Foo())
```

```
Here is the message and error in the console
{Foo: ƒ}Foo: ƒ Foo()__proto__: Object index.js:2 
Hey I am Foo in js  index.js:53 
Unexpected error while loading ./stories/Button.stories.tsx: TypeError: Bar is not a function
```
<img width="830" alt="Screen Shot 2021-02-09 at 3 32 27 PM" src="https://user-images.githubusercontent.com/77992832/107424877-2de8f500-6aec-11eb-86dc-9ac7b3a09df3.png">

**Expected behavior**
When `require` is used we should not load the mjs file but the js file.

**System**
Environment Info:

  System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Binaries:
    Node: 12.20.1 - /usr/local/bin/node
    npm: 6.14.10 - /usr/local/bin/npm
  Browsers:
    Chrome: 88.0.4324.150
    Safari: 14.0.2
  npmPackages:
    @storybook/addon-actions: ^6.1.17 => 6.1.17 
    @storybook/addon-essentials: ^6.1.17 => 6.1.17 
    @storybook/addon-links: ^6.1.17 => 6.1.17 
    @storybook/node-logger: ^6.1.17 => 6.1.17 
    @storybook/preset-create-react-app: ^3.1.5 => 3.1.5 
    @storybook/react: ^6.1.17 => 6.1.17 

The only way to make the **js** extension loaded is to delete the **mjs** extension which is something impossible when dependencies are in node_module.

**Comment by phated** [comment]
Is there a reason you don't use the webpack hook to specify `mjs` as an extension?

**Comment by othke** [comment]
@phated No reason. I use the default configuration and storybook load by default the `mjs` file. This is not what I expect. As my library use `require` to get a dependency I expect that it use the `js` extension.

**Comment by othke** [comment]
@phated 
Just to try and continue investigate do you have a snippet of the webpack hook your are talking about ?

**Comment by phated** [comment]
Yes, the documentation is at https://storybook.js.org/docs/react/addons/writing-presets#presets-api

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
