### ISSUE TITLE
Select text in the search box when using the slash ("/") shortcut

### ISSUE THREAD

**Issue by kylesuss** [storybookjs/storybook#13877]
**Is your feature request related to a problem? Please describe**
i find that most times when i use the keyboard shortcut on SB to search ("/") that i want to override my current search.

**Describe the solution you'd like**
Select the text in the search box when using the "/" shortcut to activate it.

**Describe alternatives you've considered**
N/a

**Are you able to assist to bring the feature to reality?**
Likely yes! But I'm not sure on timing.

**Comment by shilman** [comment]
cc @ghengeveld

**Comment by shilman** [comment]
Ta-da!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.0-beta.4 containing PR #14062 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
