### ISSUE TITLE
Storyshots dont match

### ISSUE THREAD

**Issue by fhdsouza** [storybookjs/storybook#13879]
**Describe the bug**
Im using storyshots to capture snapshots for FluentUI components. Once I generate the snapshots and commit them. If I run the test again at a later point; they fail even if the content is exactly the same.  

I raised an issue with FluentUI: https://github.com/microsoft/fluentui/issues/16267

**Expected behavior**
Tests should pass.

**Screenshots**
<img width="1228" alt="Screenshot 2021-02-11 at 12 53 44 PM" src="https://user-images.githubusercontent.com/25765551/107697517-323a1d00-6c68-11eb-835c-0a4f1436ba01.png">
<img width="1228" alt="Screenshot 2021-02-11 at 12 54 07 PM" src="https://user-images.githubusercontent.com/25765551/107697567-4251fc80-6c68-11eb-9f94-ca7fe8d2510b.png">
<img width="1228" alt="Screenshot 2021-02-11 at 12 54 52 PM" src="https://user-images.githubusercontent.com/25765551/107697651-5ac21700-6c68-11eb-9554-a33552cc7b49.png">

**Code snippets**

initStoryshots({
  configPath: 'src/storybook',
  framework: 'react',
  test: multiSnapshotWithOptions({}),
  stories2snapsConverter: new Stories2SnapsConverter({
    snapshotsDirName: '../../../tests/__snapshots__/'
  }),
  snapshotSerializers: [jestSerializerMergeStyles],
  storyKindRegex: /^((?!.Calendar|ColorPicker|Toggle|SpinButton).)*$/  
});`

**System**

    "@storybook/addon-storyshots": "^6.1.10",
    "@storybook/react": "^6.1.10",
    "@types/storybook__react": "^5.2.1",

**Additional context**

**Comment by shilman** [comment]
Looks like it's some kind of character encoding issue between mac and windows?

I'd suggest:
- Save a copy of the current snapshot
- Update the snapshot to the new version
- Take a look at the output in a hex debugger
  - https://dev.to/matmooredev/i-made-a-tool-for-debugging-character-encoding-problems-4246
  - https://marketplace.visualstudio.com/items?itemName=ms-vscode.hexeditor

**Comment by ndelangen** [comment]
The future of storyshots is the test-runner:
https://storybook.js.org/docs/react/writing-tests/test-runner#page-top

And use the play function for expectations:
https://storybook.js.org/docs/react/writing-stories/play-function#page-top

We will not be making any improvement / changes to storyshots.
