### ISSUE TITLE
Storybook is not opening the browser tab by default

### ISSUE THREAD

**Issue by dons20** [storybookjs/storybook#13880]
**Describe the bug**
When running `start-storybook` it does not automatically open the browser tab anymore.

**To Reproduce**
`yarn start-storybook -p 6006`

**Expected behavior**
When compilation is complete, a browser tab would open to `http://localhost:6006/`

**System**
```
Environment Info:

  System:
    OS: Linux 4.19 Ubuntu 18.04.5 LTS (Bionic Beaver)
    CPU: (6) x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
  Binaries:
    Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v14.15.4/bin/yarn
    npm: 6.14.10 - ~/.nvm/versions/node/v14.15.4/bin/npm
  npmPackages:
    @storybook/addon-actions: 6.1.17 => 6.1.17 
    @storybook/addon-essentials: 6.1.17 => 6.1.17 
    @storybook/addon-graphql: 6.1.17 => 6.1.17 
    @storybook/addon-knobs: 6.1.17 => 6.1.17 
    @storybook/addon-links: 6.1.17 => 6.1.17 
    @storybook/addon-storysource: 6.1.17 => 6.1.17 
    @storybook/addons: 6.1.17 => 6.1.17 
    @storybook/react: 6.1.17 => 6.1.17 
```

**Additional context**
This issue happened after migrating from `5.3.x` to `6.1.17`

I don't know if this is related to #13812

**Comment by phated** [comment]
Hey @dons20! This is working for me on the 6.2-alpha, can you try upgrading with `npx sb@next upgrade --prerelease` and let me know if it still happens?

**Comment by dons20** [comment]
Hi @phated thanks for the suggestion. I attempted it just now but the upgrade failed with this message:

```sh
error An unexpected error occurred: "could not find a copy of @babel/parser to link in /home/<user>/projects/<project-name>/frontend/node_modules/@storybook/addon-docs/node_modules/@babel/core/node_modules/@babel/helper-module-transforms/node_modules/@babel/template/node_modules".
```

**Comment by shilman** [comment]
Did you try removing `node_modules` and/or lockfiles and reinstalling?

**Comment by jtieu-r7** [comment]
I'm able to get this to open in the browser using the latest prerelease, although not providing a ```host``` arg to ```start-storybook``` will default to the machine's ip address instead of localhost when it opens the browser tab on startup.

**Comment by shilman** [comment]
Yo-ho-ho!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.0-beta.2 containing PR #14032 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by dons20** [comment]
I managed to upgrade, but it didn't resolve the issue. I'm wondering if it's because I'm running it in WSL? Perhaps that interferes with the process used to automatically launch the browser. I've seen a similar issue where using a linux command to copy to clipboard fails unless I pipe it to `clip.exe`. Will do some more experimentation, but I think my issue could be my local dev environment.
