### ISSUE TITLE
Wrong version of Storybook is displayed in "About your Storybook"

### ISSUE THREAD

**Issue by dons20** [storybookjs/storybook#13881]
**Describe the bug**
With the storybook page loaded, the wrong version is displayed on the "About your Storybook" page despite being on the latest version.

**To Reproduce**
1. `yarn start-storybook`
2. Click on the `...` button in the top left
3. Click "About your Storybook` option
4. View the version displayed on the page and compare it with the version displayed in the terminal

**Expected behavior**
Displayed version should say `6.1.17` and there shouldn't be a message asking me to upgrade.

**Screenshots**
![image](https://user-images.githubusercontent.com/3958349/107709065-9a055d80-6c92-11eb-9f42-45ecfe9ea1cb.png)
![image](https://user-images.githubusercontent.com/3958349/107709115-ad182d80-6c92-11eb-8e10-aeb75a66ece2.png)

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
```
Environment Info:

  System:
    OS: Linux 4.19 Ubuntu 18.04.5 LTS (Bionic Beaver)
    CPU: (6) x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
  Binaries:
    Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v14.15.4/bin/yarn
    npm: 6.14.10 - ~/.nvm/versions/node/v14.15.4/bin/npm
  npmPackages:
    @storybook/addon-actions: 6.1.17 => 6.1.17 
    @storybook/addon-essentials: 6.1.17 => 6.1.17 
    @storybook/addon-graphql: 6.1.17 => 6.1.17 
    @storybook/addon-knobs: 6.1.17 => 6.1.17 
    @storybook/addon-links: 6.1.17 => 6.1.17 
    @storybook/addon-storysource: 6.1.17 => 6.1.17 
    @storybook/addons: 6.1.17 => 6.1.17 
    @storybook/react: 6.1.17 => 6.1.17 
```

**Additional Details**

I ran `npx sb upgrade` after seeing this message, but it didn't change the result at all.

**Comment by shilman** [comment]
closing as dupe to #12183
