### ISSUE TITLE
auto reloading is not working with webpack configured react

### ISSUE THREAD

**Issue by mdirshaddev** [storybookjs/storybook#13903]
Storybook not working with Webpack react till now I haven't tried the next versions. I am using Webpack 5, with React 17. Please help me out In a moment I will share every last bit of info. 
Thanks
Md Irshad

**Comment by shilman** [comment]
closing in favor of #9216

**Comment by mdirshaddev** [comment]
> closing in favor of #9216

I am using Webpack 5. The mention #9216 says in order to use storybook i need to stick myself with webpack 4. Is that is

**Comment by shilman** [comment]
we currently don't support webpack5, but it's coming soon
