### ISSUE TITLE
UI: Fix toggle button for custom theming

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#13924]
The search input on the left nav is working correctly but I think still some bugs in the custom theme configuration. 

The switch buttons under control it's taking the toolbar background. 

![UI-Elements-Form-Controls-Buttons-Primary-⋅-Storybook](https://user-images.githubusercontent.com/874455/107988701-9299c900-6f9e-11eb-83c4-6a0646c06e16.png)

 The arrows in the left nav on hover, focus, and the active effect are taking the parameters from `barSelectedColor`

<img width="203" alt="left-nav-Storybook" src="https://user-images.githubusercontent.com/874455/107988754-ae04d400-6f9e-11eb-9822-8540691eda6d.png">

_Originally posted by @nerisina in https://github.com/storybookjs/storybook/issues/13388#issuecomment-779424597_

**Comment by cjmcintyre** [comment]
90% sure I've found the cause of this - will get a PR in soon.

**Comment by singharyan1007** [comment]
hey i am new ..can you assign me this issue and help me out with it

**Comment by Nazeeh21** [comment]
I want to give it a try to resolve this issue.

**Comment by shilman** [comment]
Thanks @Nazeeh21!

**Comment by Nazeeh21** [comment]
I am getting this error while running the command ```yarn build```  as specified [heer] (https://storybook.js.org/docs/react/contribute/code#start-developing)

![image](https://user-images.githubusercontent.com/56908732/123918982-11b5f980-d9a2-11eb-83ac-ccd84a384778.png)

Error message displays ```MODULE NOT FOUND```in spite of running ```yarn``` in the root directory.
Do I need to install another package globally or folder specific for this?

![image](https://user-images.githubusercontent.com/56908732/123919468-956fe600-d9a2-11eb-9a7e-c9e7f078ea44.png)
I am able to run storybook locally though.

**Comment by shilman** [comment]
@Nazeeh21 maybe it's having problems with the space in your directory name. can you try it in path that doesn't have a space in the name?

**Comment by shilman** [comment]
Olé!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-alpha.15 containing PR #15449 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
