### ISSUE TITLE
Add automatic ids to all canvas controls for testing purposes

### ISSUE THREAD

**Issue by AndrewGoupil** [storybookjs/storybook#13929]
**Is your feature request related to a problem? Please describe**
I am writing cypress tests for my Storybook documentation, and have leveraged control ids for boolean and radio controls. But I have noticed for other control types these ids are not generated

As an example for radio buttons each input is given the id {controlName-optionName}, which is nice and predictable

A couple of controls that I have noticed do not have this feature are textarea, number, select.

**Describe the solution you'd like**
Would be great to add a simple, predictable id to all controls, for testing purposes

**Describe alternatives you've considered**
Currently targetting these elements by different properties that are available, but would love a consistent approach

**Are you able to assist to bring the feature to reality?**
yes, I can...

**Comment by shilman** [comment]
PRs very welcome @AndrewGoupil -- this seems like a slam dunk

**Comment by keitheric79** [comment]
![tf1577256286299](https://user-images.githubusercontent.com/80196040/110236498-23135b80-7f04-11eb-80db-cc307c7e71db.jpg)

**Comment by YozhEzhi** [comment]
@AndrewGoupil I've made PR for this. Take a look please.

**Comment by antonio-b** [comment]
New to open source, is this issue closed? if not, may i work on this issue?

**Comment by shilman** [comment]
@antonio-b a PR is open here #14296

**Comment by YozhEzhi** [comment]
@antonio-b I have to write test for new logic. I'll try to make it on this week end.

**Comment by shilman** [comment]
Jeepers creepers!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.3.0-alpha.36 containing PR #14296 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
