### ISSUE TITLE
Error: Type TranslateModule does not have 'ɵmod' property.

### ISSUE THREAD

**Issue by jlabaj** [storybookjs/storybook#13958]
no matter what configuration of angular and storybook or ngx-translate I have I always receive this error, no way around it. The app compiles fine without storybook.

Angular 10.2.0

Storybook 6.1.18

ngx-translate 13.0.0

index.js:60 Error: Type TranslateModule does not have 'ɵmod' property.
    at getNgModuleDef (core.js:1855)
    at recurse (core.js:24235)
    at recurse (core.js:24246)
    at recurse (core.js:24246)
    at registerNgModuleType (core.js:24231)
    at new NgModuleFactory$1 (core.js:24345)
    at compileNgModuleFactory__POST_R3__ (core.js:27894)
    at PlatformRef.bootstrapModule (core.js:28132)
    at draw (helpers.js:124)
    at Object.push../node_modules/@storybook/angular/dist/client/preview/angular/helpers.js.exports.renderNgApp (helpers.js:137)

**Comment by rothsandro** [comment]
I had the same error when importing an Angular Material Module. I used Angular 11.2.0 and Angular Material 11.2.1. The error was gone after updating Angular to version 11.2.1. Seems to be related to Angular and not Storybook.

**Comment by IsaacSomething** [comment]
I reported a similar issue here https://github.com/storybookjs/storybook/issues/13628 

I am currently using `"@angular/core": "^11.2.1"` and `"@angular/material": "^11.2.1",` and am still getting the same issue on various modules

**Comment by acramatte** [comment]
I found this thread as I had the same error after having updated from Angular 9 to Angular 10.2.3 with Storybook 6.1.10.

I could solve it by a naive removal of my node_module and npm installing again. 
Note that I am calling "ngcc" in my npm postinstall which is what might have actually fixed the issue here.
Hope that can maybe help some.

**Comment by jlabaj** [comment]
here is my solution, since we have a hybrid app, but it should work in any app:
delete node_modules, delete all storybook entries in package.json, delete npm-cache under your profile, delete lock files. Upgrade to angular 11(11.0.0) upgrade the other angular packages(angular-builders, devkit). Upgrade ngx-translate to newest version(13 in my case). Run **npx sb init**(6.1.19 in my case). Run npm install, not sure about the order. Upgrade the TranslateModule.ForRoot in common storybook module to use withValue instead of useFactory in the loader and use const Loader function.
adjust the paths in tsconfig.json under storybook to exclude everything unnecessary
"exclude": [
"../test.ts",
"../**/*.spec.ts",
"../**/*.po.ts",
"../**/*e2e/**/*.*"
],

const StorybookTranslationLoader: TranslateLoader = {
  getTranslation(lang: string): Observable<undefined> {
    let translations = deConfig;
    if (lang === 'en') {
      translations = enConfig;
    }
    return of(translations);
  },
};

@NgModule({
  imports: [
    BrowserModule,
    SharedFeatureCommonModule.forRoot(),
    TranslateModule.forRoot({
      loader: {
        provide: TranslateLoader,
        useValue: StorybookTranslationLoader,
      },
      defaultLanguage: 'en',
    }),
    TranslateModule,
  ],
  exports: [SharedFeatureCommonModule, TranslateModule],
})

**Comment by IsaacSomething** [comment]
@jlabaj interesting solution, im going to give it a try later today. Unfortunately for me this wont work in the long term as i have 3 other modules ( that i know of `ngx-markdown`, `@angular/flex-layout`, `@ngneat/content-loader` ) that produce the same issue.

**Comment by michal-husak** [comment]
for me `npm ci` resolved the issue

**Comment by noylev** [comment]
@jlabaj can you add your SharedFeatureCommonModule ? I dont have it and id like to see how it's done (does it use a like app.module in a lib project) ?

**Comment by Tim-arts** [comment]
Got the same issue today: 
![image](https://user-images.githubusercontent.com/10064887/135490773-e2c3d2ee-b650-486f-95c2-4b02f0de24d4.png)

Removing node_modules + package.lock.json and reinstalling does not fix it

**Comment by sr9yar** [comment]
simply 
```
rm -rf node_modules && npm i
```
worked for me

**Comment by tsgarcia** [comment]
Im still with this problem, i cant use any npm lib on my own angular lib. 

Angular 12.2
Stotybook 6.4.9

**Comment by fikkatra** [comment]
In my case, the upgrade to angular 13 created a .angular/cache directory. Deleting this directory solved the issue.

**Comment by devsullo** [comment]
I am not using storybook and just upgrading `ngx-translate/core ` worked for me

**Comment by Woogielicious** [comment]
if i write the "scripts": { "postinstall": "ngcc" }
Then i get an error that "The command "ngcc" is either misspelled or
could not be found."

**Comment by maddin79** [comment]
Any news on this error? I'm new to Storybook and have the same problem with 

`Type FormBuilder does not have 'ɵmod' property.`

Angular version:  ^13.3.5
@storybook/angular: ^6.4.22

I tried every workaround here but nothing works.

**Comment by jessewilliams1** [comment]
deleting `node_modules` and redoing `npm i` worked for us

**Comment by kunal00731** [comment]
@maddin79   Any luck for your case ? I am facing similar issues with a different module called : `ngxmyDatepicker` . `postinstall:ngcc` did not work for me .Still trying to figure out a suitable solution.

**Comment by maddin79** [comment]
@kunal00731 No, sorry. We did not try it again because of lack of time. To much effort to get Storybook to run. In my opinion Storybook is something to reduce the development time, but if we have to spent the saved time into get it to run and debug Storybook all the time when we have new libraries, then I do not see the benefit.

**Comment by Tim-arts** [comment]
`Module does not have a ɵmod property` usually means that you're missing a reference to the module in the story you're trying to display. Remember that in the Angular version you need to imports module this way:

```ts
export default {
  title: 'Components/Action Bar',
  component: ActionBarComponent,
  decorators: [
    moduleMetadata({
      imports: [
        CommonModule,
        ActionBarModule,
      ],
    }),
  ],
  ...
} as Meta;
```

**Comment by kmjungersen** [comment]
Bless you @fikkatra - I've been wrestling with this for a half hour and none of the other solutions worked, however removing `.angular/cache` did the trick.  Thank you!

**Comment by thovo** [comment]
Remove node_modules and reinstall worked for me

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).

**Comment by roma2341** [comment]
> In my case, the upgrade to angular 13 created a .angular/cache directory. Deleting this directory solved the issue.

Yes, yes, yes. I'm using PNPM and always had this error for some dependencies and your solution helped me, yeeeah=)
