### ISSUE TITLE
TypeError: Cannot read property 'type' of null when using an export list

### ISSUE THREAD

**Issue by migueloller** [storybookjs/storybook#13965]
Using an export list causes Storybook to fail parsing with a `TypeError: Cannot read property 'type' of null` error. i.e.,

```js
const number = 42

export { number }
```

The offending line of code is right here:
https://github.com/storybookjs/storybook/blob/a0a8d8799d1539642e613c3fbdaf3fbfbf15bb3d/lib/source-loader/src/abstract-syntax-tree/parse-helpers.js#L39

The issue is that `node.declaration` is potentially `null` as shown in the Babylon spec here: https://github.com/babel/babylon/blob/9dd2a5c9fc7b588a96ef8d6439844b43c50c0a6a/ast/spec.md#exportnameddeclaration

**Comment by ndelangen** [comment]
I think this is fixed in 7.0 beta, @migueloller can you confirm?
