### ISSUE TITLE
yarn audit: security vulnerability detected in storybook 6.1.18 -> immer

### ISSUE THREAD

**Issue by binary64** [storybookjs/storybook#13961]
**Describe the bug**
immer, used by many of your packages, has had a new Prototype Pollution vulnerability detected: https://www.npmjs.com/advisories/1603 which is patched upstream in >=8.0.1

**To Reproduce**
yarn install @storybook/react && yarn audit

**Expected behavior**
revved to secure version

**Comment by DrFlink** [comment]
Also reported in [create-react-app](https://github.com/facebook/create-react-app/issues/10578).

While we wait, this may be a temporary solution:
https://github.com/rogeriochaves/npm-force-resolutions

**Comment by peterkimga** [comment]
This is connected to this: https://github.com/ianstormtaylor/slate/pull/4050

And I also have that problem.

**Comment by jgoyer** [comment]
Fixed in [create-react-app](https://github.com/facebook/create-react-app/commit/f92c37a6e6636ed1650ffd976c6881f59b1be803)

**Comment by shilman** [comment]
Ooh-la-la!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.0-beta.1 containing PR #14015 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Boo-yah!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.20 containing PR #14015 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```
