### ISSUE TITLE
Webpack5: Compilation errors getting swallowed

### ISSUE THREAD

**Issue by jdelStrother** [storybookjs/storybook#13976]
**Describe the bug**
I'm experiencing some sort of compilation error trialing the webpack5 prerelease, but the error isn't even printed - the server just exits & tells me to "fix the error above".

```
info @storybook/react v6.2.0-alpha.31
info
info => Loading presets
info => Loading custom babel config as JS
info => Loading 1 config file in "/Users/jon/Developer/web/webpack/.storybook"
info => Loading custom babel config as JS
info => Adding stories defined in "/Users/jon/Developer/web/webpack/.storybook/main.js"
info => Using implicit CSS loaders
info => Loading custom Webpack config (full-control mode).
<i> [webpack-dev-middleware] wait until bundle finished
10% building 0/1 entries 0/0 dependencies 0/0 modulesinfo => Using cached manager
92% sealing asset processing PersistentChildCompilerSingletonPlugin(node:48722) [DEP_WEBPACK_TEMPLATE_PATH_PLUGIN_REPLACE_PATH_VARIABLES_HASH] DeprecationWarning: [hash] is now [fullhash] (also consider using [chunkhash] or [contenthash], see documentation for details)
(Use `node --trace-deprecation ...` to show where the warning was created)
99% done plugins webpack-hot-middlewarewebpack built preview f8f50d8d3f8b9ad955f2 in 6970ms

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.
```

The error is caught here: https://github.com/storybookjs/storybook/blob/next/lib/core-server/src/build-dev.ts#L127-L135 - but it's not an `instanceof Error` (it's a Webpack `Stats` object) so is never printed.

If I call error.toString(), it does return a sensible compilation error message. Perhaps that last console.error line should be outside the `if (error instanceof Error)` block?

**System**
```

Environment Info:

  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  Binaries:
    Node: 14.15.4 - ~/.nix-profile/bin/node
    Yarn: 1.22.0 - ~/.yarn/bin/yarn
    npm: 6.14.10 - ~/.nix-profile/bin/npm
  Browsers:
    Chrome: 88.0.4324.182
    Safari: 14.0.2
  npmPackages:
    @storybook/addon-actions: ^6.2.0-alpha.31 => 6.2.0-alpha.31
    @storybook/addon-essentials: ^6.2.0-alpha.31 => 6.2.0-alpha.31
    @storybook/addon-links: ^6.2.0-alpha.31 => 6.2.0-alpha.31
    @storybook/addon-storyshots: ^6.2.0-alpha.31 => 6.2.0-alpha.31
    @storybook/builder-webpack5: ^6.2.0-alpha.31 => 6.2.0-alpha.31
    @storybook/core: ^6.2.0-alpha.31 => 6.2.0-alpha.31
    @storybook/react: ^6.2.0-alpha.31 => 6.2.0-alpha.31
    @storybook/theming: ^6.2.0-alpha.31 => 6.2.0-alpha.31
```

**Comment by shilman** [comment]
Do you have a repro repo you can share? Tried to force an error on my test project and it worked as expected, so I'm guessing you're seeing a different failure mode. Thanks!

**Comment by mjchang** [comment]
Try this: https://github.com/mjchang/webpack5-error

I removed the css loaders to trigger an error.

**Comment by shilman** [comment]
Gadzooks!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.0-alpha.32 containing PR #13983 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by SkReD** [comment]
Please do this here too https://github.com/storybookjs/storybook/blob/41c4b4a7efa34782e9b8b3a5afc12dbf3d271378/lib/core-server/src/build-static.ts#L107. Error log output is bloated with serialized `compilation` webpack object
