### ISSUE TITLE
Webpack5: Remove outdated types

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#13985]
Thanks for making storybook compatible with webpack 5 web app builds.
I upgraded yesterday to `6.2.0-alpha.30` and run into some typescript issues when type-checking my web app.

Likely you don't need these types for the v5 build `@types/html-webpack-plugin` because `html-webpack-plugin@5.0.0` is shipped with types.
ref: https://github.com/storybookjs/storybook/blob/next/lib/builder-webpack5/package.json#L64
ref: https://github.com/storybookjs/storybook/blob/next/lib/builder-webpack5/package.json#L85

The outdated types end up in my types directory because both `builder-webpack4` and `builder-webpack5` have the dependency. There is no higher version of the types so i couldn't use a resolution to fix it, ended up with a hack to get my typechecking to work for now.

```
// overwrite outdated types with new build-in types
const htmlWebpackPluginTypeSourceFile = './node_modules/html-webpack-plugin/typings.d.ts';
fs.readFile(htmlWebpackPluginTypeSourceFile, 'utf8', (readError, data) => {
    const htmlWebpackPluginTypeTargetFile = './node_modules/@types/html-webpack-plugin/index.d.ts';
    fs.writeFile(htmlWebpackPluginTypeTargetFile, data, 'utf8', (writeError) => {
        if (writeError) {
            console.log(writeError);
            throw writeError;
        }
    });
});
```

_Originally posted by @JochemE in https://github.com/storybookjs/storybook/issues/9216#issuecomment-782822845_

**Comment by JochemE** [comment]
![image](https://user-images.githubusercontent.com/6950373/108627812-ba35d900-7457-11eb-8c42-83335b7b4c2a.png)

Sorry, missed the fact that it's also there as a sub-dependency of `storybook/react`, do you know a way to opt out of installing `builder-webpack4`?

**Comment by shilman** [comment]
@JochemE there isn't one currently. 6.2 is a minor release so we want to make this a non-breaking change. i'm considering making `@storybook/builder-webpack4` an optional peer dependency and making `sb init` and `sb upgrade` smarter to automatically add it for you. if we did that you could opt out, but technically it's still a breaking change I think.

**Comment by shilman** [comment]
Zoinks!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.0-alpha.33 containing PR #13993 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
