### ISSUE TITLE
React: Standalone API is broken

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#13988]
Tried to upgrade in local (`npx sb upgrade --prerelease`) with a small snippet of code:

```js
const storybook = require('@storybook/react/standalone');

storybook({
	mode: 'static',
	outputDir: ''
})
```

And I'm getting the following error:

<details>
<summary>Error: Cannot find module './dist/cjs/server/standalone'</summary>

<code>
Error: Cannot find module './dist/cjs/server/standalone'
Require stack:

* /Users/XXXXXXXXX/dev/experiments/storybook/node_modules/@storybook/core/standalone.js
* /Users/XXXXXXXXX/dev/experiments/storybook/node_modules/@storybook/react/standalone.js
* /Users/XXXXXXXXX/dev/experiments/storybook/src/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/XXXXXXXXX/dev/experiments/storybook/node_modules/@storybook/core/standalone.js:1:15)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/XXXXXXXXX/dev/experiments/storybook/node_modules/@storybook/core/standalone.js',
    '/Users/XXXXXXXXX/dev/experiments/storybook/node_modules/@storybook/react/standalone.js',
    '/Users/XXXXXXXXX/dev/experiments/storybook/src/index.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! storybook-experiment@1.0.0 start: `node ./src/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the storybook-experiment@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/XXXXXXXXX/.npm/_logs/2021-02-21T12_28_01_668Z-debug.log
</code>

</details>

- - -
Checking package versions in node modules, seems like the version has been upgraded properly

Any clue on what could be the issue? Should I create a bug and research on it?

_Originally posted by oscard0m in https://github.com/storybookjs/storybook/issues/13860#issuecomment-782850498_

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1199622255231368/1200021064579616) by [Unito](https://www.unito.io/learn-more)

**Comment by shilman** [comment]
Yay!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.0-beta.9 containing PR #14122 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by jqrun** [comment]
Hi!

I'm using 6.2.0-beta.9 but I'm still running into the exact same error listed here. For reference, these are the settings I'm trying to use with standalone:

```
storybook({
    mode: 'dev',
    configDir,
    port,
    ci: true,
})
```

Error:

```
Error: Cannot find module './dist/cjs/server/standalone'
Require stack:
- <redacted>/node_modules/@storybook/core-server/standalone.js
- <redacted>/node_modules/@storybook/core/standalone.js
- <redacted>/node_modules/@storybook/react/standalone.js
```

**Comment by oscard0m** [comment]
Same here:

<details>
<summary>Error: Cannot find module './dist/cjs/server/standalone'</summary>

<code>
Require stack:
- /Users/XXXXXXX/dev/experiments/storybook/node_modules/@storybook/react/node_modules/@storybook/core-server/standalone.js
- /Users/XXXXXXX/dev/experiments/storybook/node_modules/@storybook/react/node_modules/@storybook/core/standalone.js
- /Users/XXXXXXX/dev/experiments/storybook/node_modules/@storybook/react/standalone.js
- /Users/XXXXXXX/dev/experiments/storybook/src/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/XXXXXXX/dev/experiments/storybook/node_modules/@storybook/react/node_modules/@storybook/core-server/standalone.js:1:15)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/XXXXXXX/dev/experiments/storybook/node_modules/@storybook/react/node_modules/@storybook/core-server/standalone.js',
    '/Users/XXXXXXX/dev/experiments/storybook/node_modules/@storybook/react/node_modules/@storybook/core/standalone.js',
    '/Users/XXXXXXX/dev/experiments/storybook/node_modules/@storybook/react/standalone.js',
    '/Users/XXXXXXX/dev/experiments/storybook/src/index.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! storybook-experiment@1.0.0 start: `node ./src/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the storybook-experiment@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
</code>

</details>

**Comment by shilman** [comment]
Ermahgerd!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.0-beta.10 containing PR #14140 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by jqrun** [comment]
Sorry to bother again 😬 , and thank you for the quick responses! The previous error is gone but now this one has surfaced:

```
Error: Cannot find module './dist/server/options'
Require stack:
- .../node_modules/@storybook/react/standalone.js
```

**Comment by oscard0m** [comment]
> Sorry to bother again 😬 , and thank you for the quick responses! The previous error is gone but now this one has surfaced:
> 
> ```
> Error: Cannot find module './dist/server/options'
> Require stack:
> - .../node_modules/@storybook/react/standalone.js
> ```

Same here

**Comment by shilman** [comment]
Yowza!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.0-beta.13 containing PR #14196 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by oscard0m** [comment]
> Yowza!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.0-beta.13 containing PR #14196 that references this issue. Upgrade today to the `@next` NPM tag to try it out!
> 
> ```
> npx sb upgrade --prerelease
> ```
> 
> Closing this issue. Please re-open if you think there's still more to do.

It works. Nice work @shilman
