### ISSUE TITLE
Webpack5: remove deprecated webpack-filter-warnings-plugin

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#13990]
@shilman i get a peer dependency warning on `6.2.0-alpha.32`
```
warning "@storybook/builder-webpack5 > webpack-filter-warnings-plugin@1.2.1" has incorrect peer dependency "webpack@^2.0.0 || ^3.0.0 || ^4.0.0".
```

`webpack-filter-warnings-plugin` is deprecated now that webpack 5 has a build in feature for suppressing warnings
https://github.com/mattlewis92/webpack-filter-warnings-plugin/pull/26

ref: https://github.com/storybookjs/storybook/blob/next/lib/builder-webpack5/package.json#L105

__Originally posted by @JochemE in https://github.com/storybookjs/storybook/issues/9216#issuecomment-782867590__

**Comment by VincentLanglet** [comment]
Hi @shilman 

On 6.2.0-beta.1, I also get
```
warning "@storybook/react > @storybook/core > dotenv-webpack@1.8.0" has incorrect peer dependency "webpack@^1 || ^2 || ^3 || ^4".
```

It's because of: https://github.com/storybookjs/storybook/blob/next/lib/core-server/package.json#L68

**Comment by shilman** [comment]
Olé!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.0-rc.7 containing PR #14303 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
