### ISSUE TITLE
Docs Page Theming: Table rows have a hardcoded background color

### ISSUE THREAD

**Issue by paulathevalley** [storybookjs/storybook#14029]
**Describe the bug**
When applying a dark theme to the Docs page, the table still has white and light gray background colors. This obviously ruins the readability of the table as the text color is also a light gray. There is a hardcoded `background-color: white;` value applied to the `table tr` element.

**To Reproduce**

1. Use a dark theme for the docs page
  ```jsx 
  // .storybook/preview.js
  import { themes } from '@storybook/theming';
 
  export const parameters = {
    docs: {
      theme: themes.dark
    }
  };
  ``` 
2. Create a `stories.mdx` file and add a table: 
  ```mdx
    <table><tr><th>Header</th></tr><tr><td>Table Cell</td></tr></table> 
  ```
3. Run storybook and view the table's white and gray background colors

**Expected behavior**
I expect the table to inherit the dark theme's colors and retain its readability.

**Screenshots**
<img width="315" alt="Screen Shot 2021-02-23 at 11 11 49 AM" src="https://user-images.githubusercontent.com/768965/108895048-ef613900-75c7-11eb-88f7-295a4c3cdeb3.png">

**Code snippets**
I believe this line to blame: https://github.com/storybookjs/storybook/blob/next/lib/components/src/typography/DocumentFormatting.tsx#L169

I'm unclear how `theme` works in that file as I do not understand where `theme.color.medium` and `theme.color.lighter` are coming from or how `theme.color` should be used (generally speaking). Otherwise I'd PR a fix directly. 

Thanks for reading.

**Comment by TheMightyPenguin** [comment]
@domyen @ndelangen I'd like to give this one a shot!

**Comment by domyen** [comment]
Thanks @TheMightyPenguin 🙇‍♂️ go for it!

**Comment by shilman** [comment]
ZOMG!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.0-rc.3 containing PR #14251 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
