### ISSUE TITLE
layout: 'centered' causes some of my components to look bad

### ISSUE THREAD

**Issue by binary64** [storybookjs/storybook#14028]
Hi, firstly fantastic product, thank you.

**Describe the bug**
I fully expect the problem to reside within my code, not Storybook's, but when I remove layout: 'centered' from my preview.js, all of my components look great. But when I add it, 25% look bad (eg, overlapping text and divs, overflowing containers, etc). My faulty components seem to all have a top-level node with width:100% in css.

**Expected behavior**
I guess I would like a big toggle where I can switch inbetween "min-content", which is what it seems to be with centered mode, and "fill-parent", which is what it seems to be without centered.

**System**
"@storybook/react": "^6.1.18"

How would you solve this problem? Do you use one or the other? Is this problem basically my CSS isnt compatible with a parent using CSS3. Would you make this a prop called fullWidth={true} in jsx? Or should I use a decorator to show both versions as separate stories? Is there a plugin to let me choose between min-content and fill-parent?

If I have a table type component, I'd want it to show at 100% of the parent div
If I have a button type component, I'd want it to show at min-content (width:100%;flex:0; inside a flex?)

Ahh.. do I just have to add flex:1 to my parent node?

**Comment by jemink** [comment]
I also have this problem, I have a few components that should consume the full width, but they seem to be 'collapsed'

**Comment by shilman** [comment]
@ndelangen @ghengeveld any ideas?

**Comment by guipace** [comment]
I also have this issue. Seems like the #root storybook html element no longer has 100% width and limits the size of the nested component.

**Comment by ndelangen** [comment]
The centered layout uses `display: flex`, which makes the content inside it no longer behave as display `block`.

This is the intended purpose of the centered layout.
I guess you want the story to be centered vertically, but preserve the full width?

You could add a `flex: 1` to your story, that should ensure it takes up the full width even when in a container with `display: flex`..
