### ISSUE TITLE
can't convert symbol to string error with React.lazy and Suspense

### ISSUE THREAD

**Issue by JimmyRowland** [storybookjs/storybook#14020]
**Describe the bug**
We are using https://react.i18next.com/ for localization and we are trying to write stories for components that use i18next. Those components need to be wrapped by Suspense as translation files are lazy loaded. However, storybook returns the error `can't convert symbol to string` when we wrap stories with Suspense in decorators.

**To Reproduce**

1. Go to https://codesandbox.io/s/currying-mountain-3y6b3?file=/src/stories/1-Button.stories.js
2. Click on the story Button -> LazyLoad
3. See error `can't convert symbol to string`

I did not set up i18next in the code example. I suspect storybook can't handle lazy load properly

**Expected behavior**
Storybook should render a button with text LazyLoad

**Comment by zdila** [comment]
Same issue if used in decorators:
```javascript
  decorators: [
    (Story) => (
      <Suspense fallback="Loading...">
        <Story />
      </Suspense>
    ),
  ],
```

Maybe related: https://github.com/storybookjs/storybook/issues/11554

**Comment by shilman** [comment]
closing as dupe to #11554
