### ISSUE TITLE
[ component/story name & icon ] there is a story & icon miss-alignment for Firefox after upgrade to 6.1.18

### ISSUE THREAD

**Issue by DlgSHi** [storybookjs/storybook#14025]
**Describe the bug**
There is a story & icon(badge) miss-alignment for Firefox after upgrade storybook to v `6.1.18`

**Browser**
Firefox only

**To Reproduce**

1. Go to [example](https://5ecf782fe724630022d27d7d-ezarrdnppg.chromatic.com/?path=/story/welcome--welcome-page)
2. Expand any of component
3. Check the text alignment (the name of the story / component) and the icon (badge)

**Expected behavior**
The text should be aligned with the icon (as it is on `Chrome`)

**Screenshots**
<img width="207" alt="Screenshot 2021-02-22 at 14 39 29" src="https://user-images.githubusercontent.com/34001198/108830974-fbe69100-75c9-11eb-82a0-9773d5093942.png">

**System**
Environment Info:

  System:
    OS: macOS 11.2
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  Binaries:
    Node: 13.12.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/PGS/Repository/carbon/node_modules/.bin/npm
  Browsers:
    Chrome: 88.0.4324.182
    Firefox: 85.0.2
    Safari: 14.0.3
  npmPackages:
    @storybook/addon-a11y: ^6.1.18 => 6.1.18
    @storybook/addon-actions: ^6.1.18 => 6.1.18
    @storybook/addon-docs: ^6.1.18 => 6.1.18
    @storybook/addon-google-analytics: ^6.1.18 => 6.1.18
    @storybook/addon-knobs: ^6.1.18 => 6.1.18
    @storybook/addon-links: ^6.1.18 => 6.1.18
    @storybook/addon-viewport: ^6.1.18 => 6.1.18
    @storybook/addons: ^6.1.18 => 6.1.18
    @storybook/components: ^6.1.18 => 6.1.18
    @storybook/react: ^6.1.18 => 6.1.18
    @storybook/theming: ^6.1.18 => 6.1.18

**Comment by vanessayuenn** [comment]
Hi! I am going through and cleaning up old issues in the repo. We just shipped a ton of improvements in Storybook 7.0, and I suspect this bug might be fixed already. Can you please try it out? If this issue persists with the latest version, please open a new bug report with a 7.x reproduction. Thank you so much! 🙏🏼
