### ISSUE TITLE
"Clear background" wipes off all default backgrounds

### ISSUE THREAD

**Issue by norin89** [storybookjs/storybook#14030]
**Describe the bug**
I have an issue with `@storybook/addon-backgrounds`.
When "Clear background" is clicked all backgrounds for each components are turned off. When if I'm in some story and test it on various backgrounds and then want to reset it, it clears all default backgrounds of other stories too.

**Expected behavior**
"Clear background" resets backgrounds of all stories to it's default rather than turning it off.

If for some reason it's expected behaviour maybe there could be another option to "Reset background", that would reset all backgrounds to it's default value.

**Screenshots**
![canvas](https://user-images.githubusercontent.com/7902324/108907202-18161c80-7622-11eb-8ba9-34c8286a760f.gif)
![docs](https://user-images.githubusercontent.com/7902324/108907226-219f8480-7622-11eb-9e4c-5b9836e967ea.gif)

**System**
```
  System:
    OS: macOS 11.2.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Binaries:
    Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v14.16.0/bin/npm
  Browsers:
    Chrome: 88.0.4324.182
    Firefox: 85.0.2
    Safari: 14.0.3
  npmPackages:
    @storybook/addon-actions: ^6.1.18 => 6.1.19
    @storybook/addon-essentials: ^6.1.18 => 6.1.19
    @storybook/addon-links: ^6.1.18 => 6.1.19
    @storybook/html: ^6.1.18 => 6.1.19
```

**Comment by cesar-carrera-nutmeg** [comment]
It seems to assign a value `transparent` rather than clearing the value.

I can see this in the URL:
`&globals=backgrounds.value:transparent`
And if I render `context.globals.backgrounds` it prints `{"value":"transparent"}`

**Comment by yannbf** [comment]
Hey everyone, can you verify whether this is an issue in Storybook 8? I can't seem to reproduce it.
Yes, you see `transparent` in the URL but the actual behavior is that the style tag is removed:


https://github.com/storybookjs/storybook/assets/1671563/cc48bd87-254d-4295-bae6-1e01ab511401

You can use this example to check:
https://next--630511d655df72125520f051.chromatic.com/?path=/story/example-button--primary

If you can still reproduce the issue, please create a minimal reproduction so we can take a look. I'll close the issue for now, but if you are able to reproduce and provide a link, we're happy to reopen and take a look into fixing it (we'd also be happy to get a PR!).

**Comment by yannbf** [comment]
Thanks a lot for explaining @WesselKroos, I'll turn this into an issue so we can triage and work on.
