### ISSUE TITLE
Storybook with ngx-bootstrap

### ISSUE THREAD

**Issue by MSultan9** [storybookjs/storybook#14036]
### Summary

I'm using angular and I'm trying to create a storybook for a component that uses a modal using this library: https://valor-software.com/ngx-bootstrap/#/modals
The issue is I can't get the modal to open in storybook
Perhaps because it uses a service provided by the library to show/hide?
(make sure to click on template and component to see the complete code in the link)

### My Code

Here's what I tried to in my .stories.ts

export default {
    ...
    decorators: [
        moduleMetadata({
            declarations: ...
            imports: [ModalModule.forRoot()],
            providers: [BsModalService]
        }),
    ]
} as Meta;

Any help is appreciated thanks.

**Comment by ndelangen** [comment]
Considering upgrading storybook and using this feature:
https://storybook.js.org/docs/react/writing-stories/play-function#page-top
