### ISSUE TITLE
Add `argTypes.<input>.control.readonly` option

### ISSUE THREAD

**Issue by Vadorequest** [storybookjs/storybook#14048]
**Is your feature request related to a problem? Please describe**
Currently, it's possible to `disable` an arg type, or make it disappear. See https://storybook.js.org/docs/react/essentials/controls#disable-controls-for-specific-properties

```tsx
export default {
  component: YourComponent,
  title:'My Story',
  argTypes:{
    // foo is the property we want to remove from the UI
    foo:{
      table:{
        disable:true // Will hide the row in the table
      }
    }
  }
};
```

```tsx
export default {
  component: YourComponent,
  title:'My Story',
  argTypes:{
    // foo is the property we want to remove from the UI
    foo:{
      control:{
        disable:true // Will show the control but display "-" instead of the value and it won't be editable
      }
    }
  }
};
```

It's not possible to display the value while making it readonly, though.

**Describe the solution you'd like**

```tsx
export default {
  component: YourComponent,
  title:'My Story',
  argTypes:{
    // foo is the property we want to remove from the UI
    foo:{
      control:{
        readonly: true // Would show the control and display its value but won't make it editable
      }
    }
  }
};
```

**Describe alternatives you've considered**
None.

**Are you able to assist to bring the feature to reality?**
I could, but never contributed to the base code and don't know where to start.

**Additional context**
The goal is to display the value while disabling the ability to change it.

It'd be useful when we want the user to see the value, but where editing it would be confusing, such as for initial props that are meant to initialize states and won't have any effect if manually updated. In such cases, seeing the actual value is useful, but editing it would be confusing because it wouldn't reflect on the component.

**Comment by shilman** [comment]
Love it. ❤️  If you're interested in contributing we'd be happy to help you get going. https://discord.gg/storybook

**Comment by nayeftechno** [comment]
Awesome👍

**Comment by vvannada** [comment]
Any updates on this?

**Comment by snitin315** [comment]
I'll implement this.

**Comment by StanLaurent** [comment]
Any progress?

**Comment by FRITS-Kh** [comment]
@snitin315 are you working on it or do we need a new volunteer?
