### ISSUE TITLE
Slash "/" hotkey undesirably activates while entering text-based controls

### ISSUE THREAD

**Issue by kevinzang** [storybookjs/storybook#14046]
**Describe the bug**
Slash "/" hotkey undesirably activates while entering text-based controls.

**To Reproduce**

1. Go to https://next--storybookjs.netlify.app/official-storybook/?path=/story/addons-controls--basic.
2. Type "https:/" in one of the text-based Controls.
3. Notice focus goes to the search as soon as you type "/". I have to manually focus back on the Control to finish typing my url.

**Expected behavior**
Hotkeys should not respond when I'm typing in an unrelated input.

**Comment by ghengeveld** [comment]
Duplicate of #13943
