### ISSUE TITLE
Vue3 default prop (string) value is wrapped in quotes

### ISSUE THREAD

**Issue by TheDutchCoder** [storybookjs/storybook#14056]
**Describe the bug**
When using a default value for a string type prop, like the below example, Storybook will wrap it in quotes failing the validation and breaking the component.

```js
    defaultOrder: {
      type: String,
      default: 'desc',
      validator: (value: string) => ['desc', 'asc'].includes(value),
    },
```

This results in the following control:
![image](https://user-images.githubusercontent.com/1668207/109186249-bb6c4c00-775e-11eb-9808-74d35ede95e3.png)

Which is actually the string `"desc"` instead of just `desc`, breaking the component.

**To Reproduce**
Add my prop to a component and create a story for it.

**Expected behavior**
The string value to not be wrapped.

**Screenshots**
See above.

**System**

```
  System:
    OS: macOS 11.2.1
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  Binaries:
    Node: 12.19.0 - ~/.nvm/versions/node/v12.19.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v12.19.0/bin/yarn
    npm: 6.14.10 - ~/.nvm/versions/node/v12.19.0/bin/npm
  Browsers:
    Chrome: 88.0.4324.192
    Edge: 88.0.705.74
    Firefox: 81.0.2
    Safari: 14.0.3
  npmPackages:
    @storybook/addon-actions: ^6.2.0-beta.2 => 6.2.0-beta.2
    @storybook/addon-essentials: ^6.2.0-beta.2 => 6.2.0-beta.2
    @storybook/addon-links: ^6.2.0-beta.2 => 6.2.0-beta.2
    @storybook/vue3: ^6.2.0-beta.2 => 6.2.0-beta.2
```

**Additional context**
We're using MDX files for the stories, not sure if this also happens in regular story JS files.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1199622255231368/1200018881820017) by [Unito](https://www.unito.io/learn-more)

**Comment by TheDutchCoder** [comment]
To add: making a custom `argTypes` control also doesn't solve this issue, it just seems wrongly mapped internally somehow.
Example:

```html
<Meta title="Data/Table" component={ ClTable } argTypes={{
  defaultOrder: {
    control: {
      type: 'select',
      options: ['desc', 'asc'],
    },
  },
}} />
```

**Comment by TheDutchCoder** [comment]
Okay I found that if I strictly type my property it does work, so there must be some TS magic happening:
```ts
    defaultOrder: {
      type: String as PropType<Foo>,
      default: 'desc',
      validator: (value: string) => ['desc', 'asc'].includes(value),
    },
```

**Comment by shilman** [comment]
It's gotta a regression from https://github.com/storybookjs/storybook/pull/13919

**Comment by shilman** [comment]
Olé!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.0-beta.14 containing PR #14200 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by TheDutchCoder** [comment]
Awesome, I'll give it a whirl and let you know if everything works!
Thanks for jumping on this so fast!

**Comment by TheDutchCoder** [comment]
All working, excellent work!
