### ISSUE TITLE
Vue3 addon-controls reactivity

### ISSUE THREAD

**Issue by damiankoper** [storybookjs/storybook#14063]
**Is your feature request related to a problem? Please describe**
In the 6.2 beta release with Vue3 support, I cannot achieve reactivity with args coming from the controls panel. The component is re-rendered completely and its state is lost. Example:
```ts
import { Meta, Story } from "@storybook/vue3";
import { ref } from "vue";
export default {
  title: "Test",
  argTypes: {
    test: {
      control: "number",
    },
  },

  parameters: { grid: { cellSize: 16 } },
} as Meta;

const Template: Story = (args) => ({
  setup() {
    const inc = ref(0);
    return { inc, args };
  },
  template: `
    {{test}}<br>{{inn}}
    <button @click="inc++">Inc</button>
  `,
});

export const DefaultData = Template.bind({});
DefaultData.args = {
  test: 1,
};
```
Setup fn is called on every update and `inc` ref is reset.

**Describe the solution you'd like**
I can see that `Args` coming from the `Template` argument are in the plain object. Is there a way to achieve reactivity and not to have the component lost its state on every controls update?

**Describe alternatives you've considered**
I've achieved this using addon-knobs with Vue2 but I want to use addon-controls now as recommended.

**Comment by shilman** [comment]
closing as dupe to #13913
