### ISSUE TITLE
Storybook Controls : Ability to set controls via query strings to match @storybook/addon-knobs behaviour

### ISSUE THREAD

**Issue by siggerzz** [storybookjs/storybook#14064]
**Is your feature request related to a problem? Please describe**
My team use Storybook as a way to test our VueJS components in isolation within the browser. This capability has been massively beneficial to us, so thanks for that!

Currently, there are two different methods (that I'm aware of) that can be used to change knob values as part of 'test setup'

1 - Interact with the knobs controls directly
2 - Open the component in full-screen mode where you're able to set the knob values based on a query string, for example:

![image](https://user-images.githubusercontent.com/14013357/109287029-f469f680-781a-11eb-9b72-e8acc9db09b7.png)

We opted for this approach within our testing as it's more flexible, reduces test setup code and means we don't have to keep switching in and out of the iframe the component is within.

As far as I'm aware, the knobs addon is getting deprecated in favour of controls, however, it looks like this functionality isn't available?

Is there a mechanism we can use to change the control values, without having to interact with them directly in the browser? Ideally if there was feature parity, that'd be awesome!

**Comment by ghengeveld** [comment]
This was added in https://github.com/storybookjs/storybook/pull/13803 and available from `v6.2.0-beta.0`.

**Comment by ghengeveld** [comment]
Usage details here: https://github.com/storybookjs/storybook/blob/next/docs/writing-stories/args.md#setting-args-through-the-url

**Comment by siggerzz** [comment]
Ah amazing, thank you so much! 🎉
