### ISSUE TITLE
Adding manager.js causes hmr loop in Angular project

### ISSUE THREAD

**Issue by dexster** [storybookjs/storybook#14083]
Bug

Adding the manager.js file causes hmr to constantly refresh the page 

Steps to reproduce

1. Init storybook in a clean angular cli project (Angular v.11.2.3)
2. Add manager.js as per the Theming documentation - [Theming](https://storybook.js.org/docs/angular/configure/theming)
3. You can leave manager.js empty or add the theming config. Just adding the file causes the issue
4. npm run storybook
5. The page will constantly refresh and the dev tools network tab will show 404 errors for hot-update.json

**System**
Environment Info:

  System:
    OS: macOS 11.2.2
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 14.15.5 - ~/.nvm/versions/node/v14.15.5/bin/node
    Yarn: 1.22.5 - ~/.nvm/versions/node/v14.15.5/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v14.15.5/bin/npm
  Browsers:
    Chrome: 88.0.4324.192
    Edge: 88.0.705.81
    Firefox: 86.0
    Safari: 14.0.3
  npmPackages:
    @storybook/addon-actions: ^6.1.20 => 6.1.20 
    @storybook/addon-essentials: ^6.1.20 => 6.1.20 
    @storybook/addon-links: ^6.1.20 => 6.1.20 
    @storybook/angular: ^6.1.20 => 6.1.20

**Comment by shilman** [comment]
Do you have a repro repo you can share?

**Comment by dexster** [comment]
I'd have to set one up but I don't really want to setup a site that constantly refreshes when you load it. As I mentioned it's just a clean install so this is all that is required if you have angular-cli installed
1. `ng new testsb`
2. cd into testsb
3. `npx sb init`
4. add manager.js to .storybook dir
5. `npm run storybook`

I'll see in the meantime if I can repro this somewhere

**Comment by dexster** [comment]
It happened in a previous new project I created but now It's not happening in a new project I just created to repro for you. Aah, the joys the dev. 

Hold off on this while I try narrow it down

**Comment by dexster** [comment]
It must've been conflicting lingering files when I reverted from 6.2-beta back to 6.1. I've deleted all traces of Storybook from my project and reinstalled and the problem went away

**Comment by AlanGreene** [comment]
I just ran into the same issue with `@storybook/react` after switching back and forth between 6.2 and 6.1 recently. Deleting `node_modules/.cache/storybook` seems to have done the trick.
