### ISSUE TITLE
React/TypeScript – Controls & Docs not being generated from components

### ISSUE THREAD

**Issue by GingerSteve** [storybookjs/storybook#14086]
**Describe the bug**
Storybook isn't generating controls or docs correctly from props defined using TypeScript.

Default Button component, using TypeScript:
![typescript](https://user-images.githubusercontent.com/10507796/109532954-4ca13280-7a7f-11eb-84b1-eeab7534bb98.png)

Default Button components, using PropTypes:
![proptypes](https://user-images.githubusercontent.com/10507796/109532962-4e6af600-7a7f-11eb-8e92-8a0012399624.png)

I also tried adding `react-docgen-typescript` and the `main.js` config detailed [here](https://storybook.js.org/docs/react/configure/typescript), but got the same result.

**To Reproduce**
1. Clone [`https://github.com/GingerSteve/sb-ts-docs`](https://github.com/GingerSteve/sb-ts-docs)
2. Run storybook `npm run storybook`

This example project was setup with:
```
npm init
npm i react react-dom
npm i -D typescript
npx sb init
```

**System**
Please paste the results of `npx sb@next info` here.

```
npx sb@next info

Environment Info:

  System:
    OS: macOS 11.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 12.16.2 - /usr/local/bin/node
    npm: 6.14.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 88.0.4324.192
    Firefox: 85.0.1
    Safari: 14.0.2
  npmPackages:
    @storybook/addon-actions: ^6.1.20 => 6.1.20 
    @storybook/addon-essentials: ^6.1.20 => 6.1.20 
    @storybook/addon-links: ^6.1.20 => 6.1.20 
    @storybook/react: ^6.1.20 => 6.1.20 
```

**Comment by shilman** [comment]
I think you need a `tsconfig.json` that tells `react-docgen-typescript` where your components are located. Storybook is meant to be added to an existing working project--it's not intended to be used as a scaffolding tool.

**Comment by GingerSteve** [comment]
Thanks @shilman, that was the problem!
