### ISSUE TITLE
Vue documentation updates

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#14082]
Suggestions from https://twitter.com/3rxck/status/1365329322261680129?s=20

- [ ] Update docs to include more info about the story return value (it's just a vue component and you can use other fields like `data() { ... }`
- [ ] Weird? pattern for overriding data using args in Vue2 (see below)
- [ ] Document that `@storybook/vue` uses `vue-docgen-api` under the hood (and known limitations) -- this would be useful for all frameworks, and is currently included in the `addon-docs` documentation

![image](https://user-images.githubusercontent.com/488689/109444668-b833d180-7a78-11eb-9694-5ad346fb6911.png)

**Comment by jonniebigodes** [comment]
Closing this.
