### ISSUE TITLE
[vue] story with args is rendered without decorators

### ISSUE THREAD

**Issue by bodograumann** [storybookjs/storybook#14109]
**Describe the bug**
Reproduction: https://github.com/bodograumann/storybook-args-and-decorators

I have a story that I want to convert to use story args and the good things that come with it.
The story needs some injections, so I have a global decorator that `provide`s these things.
It seems like the story is displayed properly in the storybook.

At the same time there is a warning, that the injected data was not found.
That seems to suggest that the story is also rendered without the decorator.

> [Vue warn]: Injection "prefix" not found
> [Vue warn]: Property or method "prefix" is not defined on the instance but referenced during render. […]

This seems relatively benign, but in the real project it causes Component Error in chromatic.

**To Reproduce**
1. `vue create -bd  # Create a new vue-cli project with the default preset.`
2. `vue add storybook  # Install storybook plugin.`
3. Add a `provide` - `inject` pair to the `MyButton` example component.
4. Change a story to use story args.

This conforms to the commits in the reproduction.

**Expected behavior**
The story is rendered after step (4) exactly as before.

**Screenshots**
![Screenshot_20210303-125525](https://user-images.githubusercontent.com/1223583/109802203-d0922080-7c1f-11eb-8670-4d45119fd17e.png)

**Code snippets**
*preview.js*
```
const withPrefix = () => ({
  provide: {
    prefix: 'Storybook-Foobar',
  },
  template: "<story />",
});

export const decorators = [
  withPrefix,
];
```
*MyButton.vue* (reduced to important part)
```
<template>
  <button>
    {{ prefix }}:
    <!-- @slot default inner button content -->
    <slot></slot>
  </button>
</template>

<script>
export default {
  name: 'my-button',
  inject: ['prefix'],
}
</script>
```

*story*
```
export const Template = (args, { argTypes }) => ({
  components: { MyButton },
  template: `<my-button>{{ text }}</my-button>`,
  props: Object.keys(argTypes),
});

<Meta title="MDX / Button" component={MyButton} />

<Canvas>
  <Story name="With Some Emoji" args={{
    text: '😀 😎 👍 💯',
  }}>{Template.bind({})}</Story>
</Canvas>
```

**System**
From the reproduction at https://github.com/bodograumann/storybook-args-and-decorators

```
Environment Info:

  System:
    OS: Linux 5.10 Arch Linux
    CPU: (4) x64 Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz
  Binaries:
    Node: 15.9.0 - /usr/bin/node
    Yarn: 1.22.10 - ~/.local/bin/yarn
    npm: 6.14.11 - /usr/bin/npm
  Browsers:
    Firefox: 86.0
  npmPackages:
    @storybook/addon-essentials: ^6.1.20 => 6.1.20 
    @storybook/addon-links: ^6.1.20 => 6.1.20 
    @storybook/vue: ^6.1.20 => 6.1.20 
```

**Comment by atrunelle** [comment]
FYI, We have a very similar issue with providing `i18n` to our components and using story with arguments.

We are using a decorator in our Vue components to provide `i18n` config globally in `preview.js`

```
addDecorator(() => ({
  template: '<story/>',
  i18n
 ));
```

The decorator works great for stories without args. But those with args throw an error: `TypeError: Cannot read property 't' of undefined`

I can provide more info if needed but it seems very similar to the issue described above.

**Comment by bodograumann** [comment]
Now works for me in latest version 6.3.2.
