### ISSUE TITLE
Apostrophes rendered incorrectly

### ISSUE THREAD

**Issue by dexster** [storybookjs/storybook#14116]
Comments generated by compodocs are not translated back to apostrophes in Storybook 

**To Reproduce**

Use a default angular storybook build and add this comment to any of your button component inputs:
`/** element's */`

Viewing the control in the canvas or docs tab shows
![Screenshot 2021-03-03 at 22 40 20](https://user-images.githubusercontent.com/6392334/109869434-833e9f00-7c71-11eb-937b-bd2acf8765bb.png)  

**Expected behavior**
Apostrophes should show correctly 

**System**
  System:
    OS: macOS 11.2.2
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 14.15.5 - ~/.nvm/versions/node/v14.15.5/bin/node
    Yarn: 1.22.5 - ~/.nvm/versions/node/v14.15.5/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v14.15.5/bin/npm
  Browsers:
    Chrome: 88.0.4324.192
    Edge: 88.0.705.81
    Firefox: 86.0
    Safari: 14.0.3
  npmPackages:
    @storybook/addon-actions: ^6.1.20 => 6.1.20 
    @storybook/addon-essentials: ^6.1.20 => 6.1.20 
    @storybook/addon-links: ^6.1.20 => 6.1.20 
    @storybook/angular: ^6.1.20 => 6.1.20

**Comment by shilman** [comment]
w00t!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-alpha.25 containing PR #15774 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
