### ISSUE TITLE
websocket error with CRA 4.0.1 and storybook 6

### ISSUE THREAD

**Issue by travis5491811** [storybookjs/storybook#14114]
**Describe the bug**
plugin.client.js:85 WebSocket connection to 'ws://localhost:3085/_content/ws' failed: Error during WebSocket handshake: Unexpected response code: 404

**To Reproduce**

1. Install `nuxt` (with content module option) and nuxt storybook
2. Add a story (can follow the [usage from nuxt](https://storybook.nuxtjs.org/usage) or directly from [storybook](https://storybook.js.org/docs/vue/get-started/setup))
3. Run storybook with `npx nuxt storybook`
4. See error in console _repeated every second_

**Expected behavior**
No errors

**System**
Environment Info:

  System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz
  Binaries:
    Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.15.4/bin/yarn
    npm: 6.14.10 - ~/.nvm/versions/node/v14.15.4/bin/npm
  Browsers:
    Chrome: 88.0.4324.192
    Firefox: 86.0
    Safari: 14.0.3
  npmPackages:
    @storybook/addon-controls: ^6.1.18 => 6.1.18 

**Additional context**
Similar issue reported [here](https://github.com/storybookjs/presets/issues/177)

**Comment by shilman** [comment]
Yee-haw!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.0-beta.11 containing PR #14165 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
