### ISSUE TITLE
Decorators do not work on Story component in MDX for Web Components

### ISSUE THREAD

**Issue by hasanirogers** [storybookjs/storybook#14120]
**Describe the bug**
I'm probably doing something wrong but I can't seem to get decorators to work in my MDX file. 

**To Reproduce**

1. Go to:  https://github.com/hasanirogers/fds-next-generation
2. Clone repo
3. cd into components and run storybook with `npm run storybook`
4. Go to: http://localhost:6006/?path=/story/primary-button--dark-theme-broke
5. View the error message

**Expected behavior**
Expect my wrapper element to wrap the story.

**Screenshots**
<img width="1310" alt="Screen Shot 2021-03-03 at 6 09 52 PM" src="https://user-images.githubusercontent.com/1185310/109886496-22519f80-7c4e-11eb-83a8-01e07febcbbe.png">

**Code snippets**
[Problem file](https://github.com/hasanirogers/fds-next-generation/blob/main/components/src/fds-primary-button/fds-primary-button.stories.mdx)
Problem story is:

```
<Canvas>
  <Story
    name="Dark Theme (broke)"
    args={{theme: 'dark'}}
    decorators={[(Story) => <div style={{ margin: '3em' }}>{<Story/>}</div>]}
  >
    {Template.bind({})}
  </Story>
  <Source
    language="html"
    code={dedent`
      <fds-primary-button theme="dark">
        Primary Button
      </fds-primary-button
    `}
  />
</Canvas>
```

**System**
`npx sb@next info` doesn't work behind my proxy.

**Comment by shilman** [comment]
This is not how to write decorators for `@storybook/web-components` stories. Unfortunately we don't have any examples in our repo or in our docs.

@jonniebigodes @daKmoR @gaetanmaisse is this something any of you can help out with?

**Comment by gaetanmaisse** [comment]
@hasanirogers I make it work on your repo (thanks by the way, really appreciate not having to fight to reproduce the pb) with the following syntax:

```js
...
    decorators={[(story) => html`<div style="margin: 3em">${story()}</div>`]}
...
```
Can you try and let me know if it behaves like expected? If so I will do a PR to add this is the [doc](https://storybook.js.org/docs/web-components/writing-stories/decorators#wrap-stories-with-extra-markup)

**Comment by hasanirogers** [comment]
@gaetanmaisse That works! Thanks a million.

**Comment by gaetanmaisse** [comment]
Closing as I updated the doc to add snippets about decorators.
