### ISSUE TITLE
Core: Dump webpack stats on build with flag

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#14139]
Use cases:

* [ ] dependencies for build optimizations
* [ ] stats object for perf diagnostics

This should be available on both `start` and `build` (via a flag or main.js `core.x` option?).

It would be nice if it was reported in a standard format that we are willing to support across versions and potentially across different builders.

Apparently we are already dumping a `stats.json` on `--smoke-test` (have not verified this)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1199622255231368/1200021212802543) by [Unito](https://www.unito.io/learn-more)

**Comment by tmeasday** [comment]
So, indeed when we run with `--smoke-test`, we dump the webpack stats object (in JSON form) for preview and manager:

https://github.com/storybooks/storybook/blob/41c4b4a7efa34782e9b8b3a5afc12dbf3d271378/lib/core-server/src/build-dev.ts#L87-L98

Note this stats data is freaking ginormous: for a trivially small SB, it is a 31MB JSON file (for the preview).

> It should be reported in a standard format that we are willing to support across versions and potentially across different builders.

I guess this is the question -- if we are going to pull stats off the huge ball of webpack, we'll need to make some decisions about what we want to include. 

I'm wondering if for now we should just dump the whole thing.

**Comment by shilman** [comment]
ZOMG!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.0-beta.13 containing PR #14186 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
follow-up in #14198

**Comment by shilman** [comment]
Crikey!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.0-beta.14 containing PR #14198 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
