### ISSUE TITLE
Documentation (--docs) mode not running in local development

### ISSUE THREAD

**Issue by starzonmyarmz** [storybookjs/storybook#14148]
**Describe the bug**
According to [Storybook Docs](https://storybook.js.org/docs/react/writing-docs/build-documentation#preview-storybooks-documentation) running `start-storybook --docs` should run a local instance in documentation mode, where the navigation is flattened and the toolbar is removed... similarly to how a public docs would be distributed. However running `start-storybook --docs` appears to run a local instance of Storybook in a normal mode where the navigation is not flattened, and the toolbar is present.

**To Reproduce**

1. In Terminal, run `yarn start-storybook --docs`
2. When everything is compiled, open storybook instance in browser
3. Be sad because its not in docs mode ☹️ 

I've also tried this with a fresh, unedited storybook install, and the results are the same.

**Expected behavior**
I expect that running `start-storybook --docs` to run a local instance of storybook in documentation mode [as described](https://storybook.js.org/docs/react/writing-docs/build-documentation#preview-storybooks-documentation) (flattened navigation and no toolbar).

**Screenshots**
NA

**Code snippets**
NA

**System**
```
❯ npx sb@next info

Environment Info:

  System:
    OS: macOS 11.2.2
    CPU: (4) x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
  Binaries:
    Node: 14.15.4 - ~/.volta/tools/image/node/14.15.4/bin/node
    Yarn: 1.22.10 - ~/.volta/tools/image/yarn/1.22.10/bin/yarn
    npm: 6.14.10 - ~/.volta/tools/image/node/14.15.4/bin/npm
  Browsers:
    Chrome: 88.0.4324.192
    Firefox: 85.0.2
    Safari: 14.0.3
  npmPackages:
    @storybook/addon-a11y: ^6.1.20 => 6.1.20
    @storybook/addon-actions: ^6.1.20 => 6.1.20
    @storybook/addon-docs: ^6.1.20 => 6.1.20
    @storybook/addon-essentials: ^6.1.20 => 6.1.20
    @storybook/addon-links: ^6.1.20 => 6.1.20
    @storybook/react: ^6.1.20 => 6.1.20
```

**Additional context**
I also asked about this in the [Design Systems Slack workspace](https://design-systems.slack.com/archives/CDTMWTTDY/p1614794353024000) (which I realize isn't an official channel for communicating about Storybook). The answer received made it sound like running Storybook in documentation mode isn't intended - in which case the docs I referenced above are severely misleading.

**Comment by starzonmyarmz** [comment]
I was looking at something completely unrelated and saw the `--no-manager-cache` and thought I'd give that a shot:

`yarn start-storybook --docs --no-manager-cache`

and that seemed to do the trick! That said, this doesn't feel like a straight forward solution, so maybe the docs could mention that or maybe functionality can be enhanced 🤷🏻.

I'll leave this open for someone on the Storybook team to review. Feel free to close.

**Comment by shilman** [comment]
This is a bug introduced in 6.1. Thanks for reporting!!

Cc @ghengeveld @jonniebigodes

**Comment by jonniebigodes** [comment]
Closing this issue as the documentation was updated with a pull request to address it. @starzonmyarmz let me know if this is still an issue and I'll gladly re-open it.

Thanks for bringing it to our attention. 

Stay safe
