### ISSUE TITLE
Bug: Controls not properly rendering in Storybook

### ISSUE THREAD

**Issue by jacktraina** [storybookjs/storybook#14158]
When I try to add argTypes to my Storybook components, the controls are not properly rendering. I instead appear to see raw data for the controls. This has only recently begun happening, but has happened with multiple components/controls of various types. Other components that were made earlier did not have this output so I assume it's a big with the new Storybook version.

Below is my code and the output. I have similar issues on other components.

![](https://user-images.githubusercontent.com/31632347/110196343-dea79300-7e11-11eb-9025-4459646f7052.png)
![](https://user-images.githubusercontent.com/31632347/110196344-dea79300-7e11-11eb-9c51-e82cdb862230.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1199622255231368/1200032002692849) by [Unito](https://www.unito.io/learn-more)

**Comment by shilman** [comment]
@jacktraina this indeed looks like a bug. do you have a repro repo you can share?

**Comment by ghengeveld** [comment]
`type: { name: 'theme' }` is not a valid type name, and thus it assumes `'object'`. Previously that would render a string input field, but now that'll render the JSON editor.

What does appear broken is that `control.type` doesn't override `type.name`.

**Comment by jacktraina** [comment]
@shilman I cannot share the repo publicly, but can I provide you with specific files that would be useful?

**Comment by ghengeveld** [comment]
Can you try the following config?

```js
Default.args = {
  theme: {
    name: 'theme',
    options: ['theme-blue', 'theme-orange', 'theme-green'],
    defaultValue: 'theme-orange',
    control: { type: 'radio' }
  }
}
```

**Comment by jacktraina** [comment]
Still having the same issue @ghengeveld 

![Screen Shot 2021-03-17 at 8 45 24 AM](https://user-images.githubusercontent.com/31632347/111469475-20331a80-86fd-11eb-9943-0063a7c66fbb.png)

**Comment by ghengeveld** [comment]
What happens if you click that RAW toggle?

**Comment by jacktraina** [comment]
![Screen Shot 2021-03-17 at 9 27 57 AM](https://user-images.githubusercontent.com/31632347/111475045-114f6680-8703-11eb-8ab9-a06c3d08ec03.png)

**Comment by ghengeveld** [comment]
Oh, I see now. It should be `argTypes`, not `args`. Typically that would be defined on the default export, not on each individual story.

**Comment by ghengeveld** [comment]
@jacktraina can you confirm the above resolved your issue?

**Comment by ghengeveld** [comment]
Closing this now. Please reopen if there's still an issue.
