### ISSUE TITLE
@emotion10 components  cause webpack issue

### ISSUE THREAD

**Issue by lev-savranskiy** [storybookjs/storybook#14150]
**styled component  - webpack issue**

1. Create Gastby  2 project
2. Create a styled component (i use     _"@emotion/core": "^10.0.22"_)
3. Story book fails to run when i use styled component in a story.

<img width="1775" alt="110000927-d6503a80-7ce1-11eb-862f-120a03ae8838" src="https://user-images.githubusercontent.com/7965778/110138987-900de080-7da0-11eb-8e1a-543d20c5dcf3.png">

**main.js**

```
module.exports = {
  "stories": [
    "../src/**/*.stories.mdx",
    "../src/**/*.stories.@(js|jsx|ts|tsx)"
  ],
  "addons": [
    "@storybook/preset-scss",
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "storybook-addon-styled-component-theme/dist/register"
  ]
}
```

package.json https://pastebin.com/P7G1eFuy

**Comment by ndelangen** [comment]
Fixed in 7.0 beta
