### ISSUE TITLE
<em> element (or _italic_) in Controls table should not be "bold"

### ISSUE THREAD

**Issue by fabiradi** [storybookjs/storybook#14155]
The global style defines the HTML elements `b` and `em` both as being **bold**, which is not quite correct.
See https://github.com/storybookjs/storybook/blob/4f5ab9fe9e590da7b841ec37cb1bed8d6327ea4b/lib/theming/src/global.ts#L50

```javascript
fontWeight: typography.weight.bold
```

As written on [MDN: \<em\>: The Emphasis element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/em#usage_notes):
> Typically this element is displayed in italic type.

The problem is: If you want to use _italic_ in the Controls table, you simply cannot. It will turn _**bold italic**_. You can also use plain **bold**, but that may be "too much" in some cases.

**Comment by shilman** [comment]
Yee-haw!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.0-rc.7 containing PR #14290 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```
