### ISSUE TITLE
prepareForInline triggers storyFn deprecation warning

### ISSUE THREAD

**Issue by bmayen** [storybookjs/storybook#14168]
**Describe the bug**

I'm testing 6.2.0 beta 10 with Angular inline support. `prepareForInline` uses `storyFn` which has been deprecated.

```
  | deprecated | @ | browser.js:39
  | storyFn | @ | story_store.js:660
  | _callee$ | @ | prepareForInline.js:76
```

**To Reproduce**

1.` import { prepareForInline } from '@storybook/addon-docs/angular/inline';`
2. add `prepareForInline` to preview.js `docs` config
3. Load a component story and view warning in browser console

**Expected behavior**
No deprecation warning

**System**
Environment Info:

  System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Binaries:
    Node: 14.15.5 - ~/.nvm/versions/node/v14.15.5/bin/node
    npm: 6.14.11 - ---------/node_modules/.bin/npm
  Browsers:
    Chrome: 88.0.4324.192
    Edge: 89.0.774.45
    Firefox: 80.0.1
    Safari: 14.0.3
  npmPackages:
    @storybook/addon-a11y: ^6.2.0-beta.9 => 6.2.0-beta.10
    @storybook/addon-backgrounds: ^6.2.0-beta.9 => 6.2.0-beta.10
    @storybook/addon-docs: ^6.2.0-beta.9 => 6.2.0-beta.10
    @storybook/addon-postcss: ^2.0.0 => 2.0.0
    @storybook/addon-viewport: ^6.2.0-beta.9 => 6.2.0-beta.10
    @storybook/addons: ^6.2.0-beta.9 => 6.2.0-beta.10
    @storybook/angular: ^6.2.0-beta.9 => 6.2.0-beta.10

**Comment by shilman** [comment]
closing as dupe to #13074
