### ISSUE TITLE
Controls: Null control causes crash

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#14175]
@ghengeveld after upgrading to latest beta I'm getting this error: 

_Originally posted by @lifeiscontent in https://github.com/storybookjs/storybook/pull/14100#discussion_r589916421_

@ghengeveld In the docs, we recommend `control: false` as a way to disable controls. However, some users, such as @lifeiscontent were using `control: null` to do the same thing. Interestingly, this variant causes the problem referenced above when combined with your change. Let's discuss when you have a min.

**Comment by ghengeveld** [comment]
I think this has been resolved already as part of the work for #14169
