### ISSUE TITLE
Skip eslint/prettier error in development mode

### ISSUE THREAD

**Issue by ravecat** [storybookjs/storybook#14177]
**Describe the problem**
Default config in dev mode has broken rebuild on every eslint/prettier error

**Expected behavior**
Maybe storybook has config parameter or env variables for skipping eslint error in development mode, like CRA
```
ESLINT_NO_DEV_ERRORS=true
TSC_COMPILE_ON_ERROR=true
```

**Screenshots**
![image](https://user-images.githubusercontent.com/24782863/110455703-cf5a6b00-80d9-11eb-8f3a-8e771209d692.png)

**System**
  System:
    OS: Linux 4.19 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (4) x64 Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz
  Binaries:
    Node: 15.3.0 - ~/.nvm/versions/node/v15.3.0/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 6.14.11 - ~/project/project/node_modules/.bin/npm
  Browsers:
    Chrome: 87.0.4280.141
  npmPackages:
    @storybook/addon-actions: ^6.1.15 => 6.1.15 
    @storybook/addon-docs: ^6.1.15 => 6.1.15 
    @storybook/addon-essentials: ^6.1.15 => 6.1.15 
    @storybook/addon-links: ^6.1.15 => 6.1.15 
    @storybook/addons: ^6.1.15 => 6.1.15 
    @storybook/preset-create-react-app: ^3.1.5 => 3.1.5 
    @storybook/react: ^6.1.15 => 6.1.15 
    @storybook/theming: ^6.1.15 => 6.1.15

**Comment by shilman** [comment]
@mrmckeb is this something we can do by default in the preset?

**Comment by Newbie012** [comment]
This is something that bugs us a lot. Is there a way I could contribute to this? It slows down the hot reload + it's really annoying whenever we refactor stuff :)

**Comment by ravecat** [comment]
Use workaround with `eslint-plugin-only-warn` plugin in dev-mode

`eslintrc.js`

```js
const isDevelopment = process.env.NODE_ENV === "development"

module.exports = {
 ...
  plugins: isDevelopment ? [
    "only-warn"
  ] : [],
  ...
```

**Comment by mrmckeb** [comment]
Are you using CRA in this case? Or a custom Webpack config? 

This should already work with the CRA config from memory... but let me know if it isn't!

**Comment by Newbie012** [comment]
I'm using CRA

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if this is still relevant in SB 7.x.
