### ISSUE TITLE
Storybook does not display images

### ISSUE THREAD

**Issue by nemanjamilosavljevic-newtron** [storybookjs/storybook#14173]
**Describe the bug**
```
// app.tsx
import imgPath from './assets/some-image.png`
<img src={imgPath} />
```
This doesn't get rendered in the storybook

I have tried importing the image directly in the *.stories.tsx as described [here](https://storybook.js.org/docs/react/configure/images-and-assets), however, the image couldn't be found.
![image](https://user-images.githubusercontent.com/77624664/110376589-ad1e0a00-8053-11eb-8788-05305d91751a.png)

When I inspect the source, the path is pointing to the `static/media/error-pages-key-visual.917034d7.png`.

**To Reproduce**
With a fresh NX and Storybook installation add any png image to the component and try to have it rendered in the story.

**Expected behavior**
The images should be displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/77624664/110376102-16e9e400-8053-11eb-862e-d9c2a2ff8faf.png)
Svgs are getting rendered correctly, but not the png images.

**Code snippets**
Default webpack config
```ts
const TsconfigPathsPlugin = require('tsconfig-paths-webpack-plugin');
const rootWebpackConfig = require('../../../.storybook/webpack.config');
/**
 * Export a function. Accept the base config as the only param.
 *
 * @param {Parameters<typeof rootWebpackConfig>[0]} options
 */
module.exports = async ({ config, mode }) => {
  config = await rootWebpackConfig({ config, mode });

  const tsPaths = new TsconfigPathsPlugin({
    configFile: './tsconfig.base.json',
  });

  config.resolve.plugins
    ? config.resolve.plugins.push(tsPaths)
    : (config.resolve.plugins = [tsPaths]);

  // Found this here: https://github.com/nrwl/nx/issues/2859
  // And copied the part of the solution that made it work

  const svgRuleIndex = config.module.rules.findIndex((rule) => {
    const { test } = rule;

    return test.toString().startsWith('/\\.(svg|ico');
  });
  config.module.rules[
    svgRuleIndex
  ].test = /\.(ico|jpg|jpeg|png|gif|eot|otf|webp|ttf|woff|woff2|cur|ani|pdf)(\?.*)?$/;

  config.module.rules.push(
    {
      test: /\.(png|jpe?g|gif|webp)$/,
      loader: require.resolve('url-loader'),
      options: {
        limit: 10000, // 10kB
        name: '[name].[hash:7].[ext]',
      },
    },
    {
      test: /\.svg$/,
      oneOf: [
        // If coming from JS/TS file, then transform into React component using SVGR.
        {
          issuer: {
            test: /\.[jt]sx?$/,
          },
          use: [
            {
              loader: require.resolve('@svgr/webpack'),
              options: {
                svgo: false,
                titleProp: true,
                ref: true,
              },
            },
            {
              loader: require.resolve('url-loader'),
              options: {
                limit: 10000, // 10kB
                name: '[name].[hash:7].[ext]',
                esModule: false,
              },
            },
          ],
        },
        // Fallback to plain URL loader.
        {
          use: [
            {
              loader: require.resolve('url-loader'),
              options: {
                limit: 10000, // 10kB
                name: '[name].[hash:7].[ext]',
              },
            },
          ],
        },
      ],
    }
  );

  return config;
};
```

**System**
Environment Info:

  System:
    OS: Windows 10 10.0.17763
    CPU: (8) x64 Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz
  Binaries:
    Node: 14.15.4 - ~\AppData\Local\Volta\tools\image\node\14.15.4\node.EXE
    Yarn: 1.22.10 - ~\AppData\Local\Volta\tools\image\yarn\1.22.10\bin\yarn.CMD
    npm: 6.14.10 - ~\AppData\Local\Volta\tools\image\node\14.15.4\npm.CMD
  Browsers:
    Chrome: 88.0.4324.190
  npmPackages:
    @storybook/addon-knobs: ^6.1.11 => 6.1.21
    @storybook/react: ^6.1.11 => 6.1.21

**Comment by shilman** [comment]
@mandarini is this something you can help with?

**Comment by nemanjamilosavljevic-newtron** [comment]
@mandarini?
I'd appreciate some hint as to what causes this issue.

**Comment by nemanjamilosavljevic-newtron** [comment]
Well, finally I've figured it out (how to fix the issue).
Removing this part of the webpack config allowed images to be parsed correctly.
```ts
{
      test: /\.(png|jpe?g|gif|webp)$/,
      loader: require.resolve('url-loader'),
      options: {
        limit: 10000, // 10kB
        name: '[name].[hash:7].[ext]',
      },
},
```

Mind you, this configuration was added automatically when generating a library.
