### ISSUE TITLE
Add option to show globalTypes name in toolbar

### ISSUE THREAD

**Issue by mnquintana** [storybookjs/storybook#14187]
**Is your feature request related to a problem? Please describe**
I find it tricky to grok what custom toolbar items are / do just by looking at the icons or menu items alone. You can find out by hovering (assuming you set a `description`), but at least on macOS I find the delay time for a tooltip faaaaar too long to be useful for getting quick feedback about the thing you're hovering over. Even with a better delay time, it adds friction to the discovery process.

**Describe the solution you'd like**
Add an opt-in option to show the `name` of a global defined in `globalTypes` in the toolbar, something like:

```typescript
export const globalTypes = {
  theme: {
    name: 'Theme',
    description: 'Global theme for components',
    defaultValue: 'light',
    toolbar: {
      icon: 'wrench',
      items: ['light', 'dark'],
      
      // Proposed option
      showName: true // defaults to `false`
    },
  },
};

```

**Describe alternatives you've considered**
[Creating a custom toolbar addon](https://storybook.js.org/docs/react/addons/addon-types#toolbars), but that seems like supreme overkill just to render a human-readable name.

**Are you able to assist to bring the feature to reality?**
Probably!

**Additional context**
A quick and dirty mockup:
![image](https://user-images.githubusercontent.com/823545/110574877-ed50bb80-812b-11eb-9813-75ae385af208.png)

**Comment by shilman** [comment]
@mnquintana love it ❤️  PRs welcome -- will merge! @ghengeveld any thoughts on the API?

**Comment by apapadopoulou** [comment]
Hello! Is anyone working on this?

**Comment by shilman** [comment]
@apapadopoulou nobody yet! it's yours if you want it 😄

**Comment by apapadopoulou** [comment]
Thank you, I will look into it!

**Comment by shilman** [comment]
Ta-da!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.3.0-alpha.19 containing PR #14776 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
