### ISSUE TITLE
MDX auto HeaderWithOcticonAnchor links in iframe have incorrect url.

### ISSUE THREAD

**Issue by aharris** [storybookjs/storybook#14188]
**Describe the bug**

When clicking in the Octicon anchor links the query params from the URL are removed and the result is a blank page as no id matches. 

**To Reproduce**

1. Create an MDX Page
2. Add headings that will be autolinked 
3. Click on the  Octicon anchor

**Expected behavior**

Url should append the hash URL to the end of the current url.

**Screenshots**

![image](https://user-images.githubusercontent.com/713398/110583245-64da1700-813b-11eb-89d1-b4208e3b13cb.png)

URL before clicking this icon: 

`http://localhost:6002/?path=/docs/components-accordion--accordion`

URL After clicking the icon

`http://localhost:6002/#options`

The URL should be:

`http://localhost:6002/?path=/docs/components-accordion--accordion#options`

**Code snippets**
If applicable, add code samples to help explain your problem.

Simple example:

test.stories.mdx

```
import { Meta } from '@storybook/addon-docs/blocks';

<Meta title="Components/Test"/>

# Test

## Options
```

I have tracked the issue to:

@storybook/addon-docs/dist/blocks/mdx.js 

Line 101

```
function navigate(url) {
  _addons["default"].getChannel().emit(_coreEvents.NAVIGATE_URL, url);
}
```
If a user is clicking this from inside the component docs iframe it needs to use the referrer URL:

This works:

```
function navigate(url) {
  _addons["default"].getChannel().emit(_coreEvents.NAVIGATE_URL, document.referrer + url);
}
```

But only for iframe component pages. This will not work for a non-iframe docs only page.

Will need to detect the difference of when to use the referrer or not.

**System**
Please paste the results of `npx sb@next info` here.

  System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Binaries:
    Node: 14.15.0 - ~/.nvm/versions/node/v14.15.0/bin/node
    Yarn: 1.18.0 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.0/bin/npm
  Browsers:
    Chrome: 88.0.4324.192
    Edge: 89.0.774.48
    Firefox: 85.0.2
    Safari: 14.0.3
  npmPackages:
    @storybook/addon-actions: 6.1.21 => 6.1.21
    @storybook/addon-essentials: 6.1.21 => 6.1.21
    @storybook/addon-links: 6.1.21 => 6.1.21
    @storybook/addons: 6.1.21 => 6.1.21
    @storybook/preset-scss: 1.0.2 => 1.0.2
    @storybook/theming: 6.1.21 => 6.1.21
    @storybook/web-components: 6.1.21 => 6.1.21

**Additional context**

**Comment by shilman** [comment]
Thanks for tracking this down! Do you happen to have a repro you can share? I'm clicking around in our example storybooks and not seeing it.

https://next--storybookjs.netlify.app/html-kitchen-sink/?path=/docs/addons-docs--heading#story-reference

https://next--storybookjs.netlify.app/official-storybook/?path=/docs/addons-docs-mdx-id--hello-story#this-is-a-markdown-file

**Comment by aharris** [comment]
@shilman thanks for the quick reply. 

I created a simple app from scratch to highlight this bug:

https://github.com/aharris/storybook-hash-anchor-bug-demo

By comparing the default storybook install to mine I was able to find what is causing it to break.

Just the existence of `manager.js` causes this issue.

Create that file in `.storybook` and links no longer work. Even if that file is empty.

**Comment by DrakeLambert** [comment]
Related to #17305?

**Comment by aharris** [comment]
@DrakeLambert yes that looks like a duplicate of this.

**Comment by shilman** [comment]
closing as dupe to #16918
