### ISSUE TITLE
ArgsTable not working for Web Components in MDX

### ISSUE THREAD

**Issue by hasanirogers** [storybookjs/storybook#14180]
**Describe the bug**
Probably doing something wrong again but I'm getting a message "No inputs found for this component." from the ArgsTable while using Web Components. I have the info for the component specified in custom-elements.json at the root of the project. I didn't see any docs on how to include an ArgsTable with components so I assumed you just pass it a string like you did with the former Props component.

**To Reproduce**

1. Clone repo at: https://github.com/hasanirogers/fds-next-generation
2. CD into /components
3. Install then run Storybook with `npm run storybook`
4. Go to: http://localhost:6006/?path=/docs/fds-primary-button--default-story
5. Scroll down and observed the message rather than a ArgsTable.

**Expected behavior**
An ArgsTable to appear.

**Screenshots**
<img width="1050" alt="Screen Shot 2021-03-09 at 1 07 00 PM" src="https://user-images.githubusercontent.com/1185310/110517777-480cf780-80d9-11eb-8ce8-58049299b755.png">

**Code snippets**
Problem Story: https://github.com/hasanirogers/fds-next-generation/blob/main/components/src/fds-primary-button/fds-primary-button.stories.mdx

Custom Elements JSON: https://github.com/hasanirogers/fds-next-generation/blob/main/components/custom-elements.json

**System**
Environment Info:

  System:
    OS: macOS Mojave 10.14.3
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
  Binaries:
    Node: 12.17.0 - ~/.nvm/versions/node/v12.17.0/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.17.0/bin/npm
  Browsers:
    Chrome: 88.0.4324.192
    Firefox: 86.0
    Safari: 12.0.3

**Additional context**
I also tried moving `custom-elements.json` to `.storybook`. Didn't work.

**Comment by brownieboy** [comment]
I've run into this same issue, using Web Components  

The web components support seems to be somehwhat in state of flux at the moment.

If you look at the Addons Readme https://github.com/storybookjs/storybook/tree/next/addons/docs, under the "Be sure to check framework specific installation needs" section, it links to Web Components at https://github.com/storybookjs/storybook/tree/next/addons/docs/web-components, but it's a broken link.  There's nothing there, as you can see if you check the list of folders at the top.

**Comment by hasanirogers** [comment]
Yeah I definitely noticed the state of flux that web components are in too. A lot of the documentation for them uses React examples for example.

@shilman has there been updates on this?

**Comment by shilman** [comment]
The missing web-components README has been restored

**Comment by clukhei** [comment]
I now see the README for web components props table up on https://github.com/storybookjs/storybook/tree/next/code/addons/docs/web-components

however there seem to be no mention about ArgsTable support to autogenerate the apis from the custom-element.json. 

Using storybook 6.5 

I did this
```
<Meta
  title="Components/Accordion"
  component="sgds-accordion-item"
/>


<Canvas>
  <Story name="Basic">
    {Template.bind({})}
  </Story>
</Canvas>


## API

<ArgsTable story="Basic" />
```

but the argstable did not appear. Props table worked tho as specified in the README. 

@shilman any updates on this?

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
