### ISSUE TITLE
Solution for duplicate kinds in a distributed fashion

### ISSUE THREAD

**Issue by daveisfera** [storybookjs/storybook#14189]
**Is your feature request related to a problem? Please describe**
Creating groups like `Atoms`, `Molecules`, `Organisms` currently isn't possible when they all can't be imported into a single location (see [here](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-support-for-duplicate-kinds))

**Describe the solution you'd like**
Ability to specify group/directory in individual files.

**Describe alternatives you've considered**
Use the duplicate keys anyways and deal with the funky hot reloading problems

**Are you able to assist to bring the feature to reality?**
Glad to give it a whirl

**Comment by daveisfera** [comment]
And closely related to this, is what's the recommended solution for single components in a file versus files that export multiple components? Currently, things like `args` and `argTypes` can be put in `export default` and then used/shared by all of the components, but I don't see a way to do that sort of thing with a single file that `export * from` all of the files.

**Comment by shilman** [comment]
There are a few different levels of concern here:
1. How stories are described in files
2. How the data is stored in Storybook
3. What the user sees on the screen

I think we're pretty set on the first two. The recommendation is that each file represent stories for a single component. You can configure stories globally, on a component level, and on individual stories (parameters, decorators, args). I can imagine the desire for more flexibility here, but Storybook is already complex and I don't think we'll want to add more complexity here, though everything's up for discussion.

We've been adding more flexibility on the third level. For example [single-story hoisting](https://storybook.js.org/docs/react/writing-stories/naming-components-and-hierarchy#single-story-hoisting) allows you to collapse away entire components for a more compact navigation structure. We'll also probably add the ability to hide stories from the sidebar #9209.

I guess I'd like to see an example of how you'd like to write your stories and what you'd like the UI to be, and maybe we can discuss that?

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if this is still relevant in SB 7.x.
