### ISSUE TITLE
[6.1] Allow to search by story

### ISSUE THREAD

**Issue by idbartosz** [storybookjs/storybook#14209]
**Is your feature request related to a problem? Please describe**
Storybook 6.1 allows only to search by kind. This means that I can search for a `Button` but I cannot search for the stories associated with it, like `with emoji`.

**Describe the solution you'd like**
I'd like to be able to search by story.

**Describe alternatives you've considered**
If this might cause some performance issues in larger Storybooks then having this as a configuration option would be also good.

**Additional context**
https://user-images.githubusercontent.com/21260478/110845684-367b4980-82ab-11eb-972a-9643996b4a07.mov

**Comment by shilman** [comment]
Already available in 6.2

```
npx sb upgrade --prerelease 
```
