### ISSUE TITLE
MDX fails to render docs with Vue3

### ISSUE THREAD

**Issue by mockingjet** [storybookjs/storybook#14201]
I build components with Vite, Vue3, VueJsx, Typescript, Tailwindcss.

Everything works fine with Storybook in Component Story Format, but MDX Format only render Canvas and no Docs.

```mdx
<-- BaseInput.stories.mdx -->

import { Meta, Story } from "@storybook/addon-docs/blocks";
import BaseInput from "./BaseInput";

<Meta title="Input/BaseInput" component={BaseInput} />

export const Template = (args) => <BaseInput {...args} />;

### Expect To See Some Docs

> But No Results

<Story
  name="Text"
  args={{
    prefix: "Account",
  }}
>
  {Template.bind({})}
</Story>

<Story
  name="Password"
  args={{
    prefix: "Password",
    type: "password",
  }}
>
  {Template.bind({})}
</Story>
```

It works in Canvas
![image](https://user-images.githubusercontent.com/32839503/110760239-77626680-8289-11eb-8f6c-2a964e91f3fc.png)

But it fails in Docs
![image](https://user-images.githubusercontent.com/32839503/110760337-919c4480-8289-11eb-900b-34c66ebc9560.png)

Below is the error message from console
![image](https://user-images.githubusercontent.com/32839503/110760508-bee8f280-8289-11eb-9fbc-4398dc00c335.png)

**Comment by shilman** [comment]
We're waiting for MDX v2 to be released to try addressing stuff like this.

In the meantime you have two options. One is to write your stories using POJO, like this:

https://github.com/storybookjs/storybook/blob/next/examples/vue-3-cli/src/stories/GlobalUsage.stories.js#L9-L18

The second is to use the VueJsx in your story file, and then embed that in MDX using this recipe:

https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/recipes.md#csf-stories-with-mdx-docs

**Comment by mockingjet** [comment]
@shilman Thanks. First option is not what I want. As for the second option, it didn't work.

```js
// BaseInput.stories.js
import BaseInput from "./BaseInput";

export const Normal = (args) => <BaseInput {...args} />;
Normal.args = {
  prefix: 'account',
};

export const Typed = (args) => <BaseInput {...args} />
Typed.args = {
  prefix: 'password',
  type: 'password'
}
```

```mdx
<-- BaseInput.stories.mdx -->
import { Meta, Story } from "@storybook/addon-docs/blocks";
import * as stories from "./BaseInput.stories.js";
import BaseInput from "./BaseInput";

<Meta title="Input/BaseInput" component={BaseInput} />

# see some docs

> still no docs

<Story story={stories.Normal} />

<Story story={stories.Typed} />
```
![image](https://user-images.githubusercontent.com/32839503/110785221-a686d100-82a5-11eb-8aed-a9dcec4986ef.png)
![image](https://user-images.githubusercontent.com/32839503/110785239-ae467580-82a5-11eb-879a-553b08385c95.png)

**Comment by shilman** [comment]
@mockingjet Any Errors in the browser console?

**Comment by mockingjet** [comment]
@shilman The same as the errors in my post

![image](https://user-images.githubusercontent.com/32839503/110785873-6542f100-82a6-11eb-9be0-1f24777ba234.png)

**Comment by shilman** [comment]
do you have a repro repo i could look at?

**Comment by mockingjet** [comment]
@shilman https://github.com/mockingjet/storybook-vite-vue3-vuejsx-demo

**Comment by eXodes** [comment]
@shilman I am having issue with the docs render for MDX as well. But I am using the Vite as the builder. Is it related to this as well?

**Comment by shilman** [comment]
Added working example here https://github.com/storybookjs/storybook/pull/15383

@eXodes all vite-related issues should go to https://github.com/eirslett/storybook-builder-vite
