### ISSUE TITLE
[6.2b] ReferenceError React is not defined

### ISSUE THREAD

**Issue by phaistonian** [storybookjs/storybook#14208]
It seems, at least in my case, that the JSX transform is either ignored or not working (anymore?).

This Reference Error `React is not defined` comes up when removing `React` from the import.

Tried hard to pinpoint to issue, but I failed to.

Any ideas or pointers?:)

**Comment by shilman** [comment]
Do you have a repro repo you can share?

**Comment by phaistonian** [comment]
@shilman  I am afraid not since it's a (huge) private repo.

My guess is that somehow my custom webpack config is causing this, however, all I have tried has failed.

Will get back to you with any additional findings, if any.

**Comment by phaistonian** [comment]
It turns out the issue was a side-effect of me using esbuild (custom webpack config) before. babel-loader.

```js
config.plugins.push(new webpack.ProvidePlugin({
  'React': 'react',
}));
```

fixed it.
