### ISSUE TITLE
Range slider value label changes handle position and causes jittering

### ISSUE THREAD

**Issue by bursik-peter** [storybookjs/storybook#14204]
**Description**
When the range sliders' (most notably with `step` smaller than 1) handle is dragged, the numeric value label changes its size, that causes slider width change, and that causes handle position change to a slightly different value. 

**To Reproduce**

1. Add a range slider to a component story with `step = 0.01`
2. Interact with handle
3. Observe prop value jittering

**Expected behavior**
Slider stays in place while interacting with it

**Screenshots**

https://user-images.githubusercontent.com/6731101/110794202-cb635000-8275-11eb-8780-35a15f401d62.mov

**Comment by DallasGale** [comment]
@shilman i can take a look at this one.

**Comment by DallasGale** [comment]
@shilman  I am going to have to pass on this, my day dev job has been taking up all my time. Hopefully i can jump back into another issue soon though. D

**Comment by shilman** [comment]
@DallasGale No worries! Thanks for offering!

**Comment by Tomastomaslol** [comment]
I created a potential fix for this issue but I'm not sure it is the best way to solve it. I tried to come up with a fix that was only using CSS, but I found it difficult to solve this without calculating the maximum size of the range sliders value.

https://user-images.githubusercontent.com/1872246/120879574-c0675400-c607-11eb-8a6f-b178c342af8f.mp4

If anyone else has a better idea or any ideas on how to improve my solution please let me know 🙂

**Comment by IgorSzyporyn** [comment]
I will make a suggestion - my idea is to just limit and fix the number of decimals which should stop that

So if 2 decimals are chosen and you hit 1.345373 it becomes 1.34 and if you hit 1.3 it becomes 1.30 and 1 becomes 1.00

**Comment by IgorSzyporyn** [comment]
> I will make a suggestion - my idea is to just limit and fix the number of decimals which should stop that
> 
> So if 2 decimals are chosen and you hit 1.348654 it becomes 1.35 and if you hit 1.3 it becomes 1.30 and 1 becomes 1.00 @Tomastomaslol
> 
> In fact, if 2 decimals are chosen, why would the component return anything but 2 decimals as requested? Sounds like a component error to me

Hmm problem will still persist like this since the leading number before the decimal splitter may also increase 0->? number of digits

So probably a width calculation about size of leading numbers may be required in it's max state

**Comment by Tomastomaslol** [comment]
Hi @IgorSzyporyn and thank you for your help! 🙂 

> I will make a suggestion - my idea is to just limit and fix the number of decimals which should stop that
> 
> So if 2 decimals are chosen and you hit 1.348654 it becomes 1.35 and if you hit 1.3 it becomes 1.30 and 1 becomes 1.00 @Tomastomaslol
> 
> In fact, if 2 decimals are chosen, why would the component return anything but 2 decimals as requested? Sounds like a component error to me

Good point! I change the value to `toFixed` with the number decimals in `step`.

I also added:

```js
  fontFeatureSettings: 'tnum',
  fontVariantNumeric: 'tabular-nums',
```

To `RangeLabel` which seems to make it less "jittery". 

> Hmm problem will still persist like this since the leading number before the decimal splitter may also increase 0->? number of digits

This is still an issue in my branch but I almost prefer to reflow on the leading value becoming longer than assigning a fixed width to the label.
https://user-images.githubusercontent.com/1872246/120917648-b458c080-c6f3-11eb-8041-f6bea530c5c4.mp4

I'm going to take another look at this later and see if I can come up with something smarter. 🙂

**Comment by shilman** [comment]
Whoopee!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.3.0-rc.5 containing PR #15145 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
