### ISSUE TITLE
Search input activated when pressing '/' in text knob/control

### ISSUE THREAD

**Issue by dawidzarzycki** [storybookjs/storybook#14207]
**Describe the bug**
When I'm using text knob and then I want to type `/` then `search input` is getting focused. It means that shortcut fires when I'm typing.

**To Reproduce**

1. Create any text knob
2. try to type `/`

**Expected behavior**
I can type `/` in text knob and active element won't change into `input search`

**Additional context**
I'm using component f.e. date input that allows me to type `12/03/2020` and then component is able to format that. Right now When I'm typing `/` then focus moves into storybook `search input`

**Comment by shilman** [comment]
Which version are you using? I believe this was fixed by @ghengeveld

**Comment by dawidzarzycki** [comment]
@shilman 
Hi! Thanks for the respond! :)
My version I'm using right now is 6.1.20

**Comment by shilman** [comment]
Try upgrading to 6.2-rc:

```
npx sb@next upgrade --prerelease
```

**Comment by dawidzarzycki** [comment]
@shilman it works on version you posted above 👍
