### ISSUE TITLE
[6.2b] Issue w

### ISSUE THREAD

**Issue by phaistonian** [storybookjs/storybook#14206]
This is an issue with 6.2b.

<img width="728" alt="CleanShot 2021-03-11 at 17 19 53@2x" src="https://user-images.githubusercontent.com/796530/110810192-3882df80-828e-11eb-8159-3ef438dcc3ff.png">

As a sidenote, when switching to the Docs pane, the knob works fine.

**Comment by shilman** [comment]
did your issue title get cut off?

**Comment by shilman** [comment]
FYI, we’ve released `addon-controls` in Storybook 6.0. Controls are portable, auto-generated knobs that are intended to replace `addon-knobs`, which are slated for deprecation.

- [Controls documentation](https://storybook.js.org/docs/react/essentials/controls)
- [Migration instructions](https://github.com/storybookjs/storybook/blob/next/addons/controls/README.md#how-do-i-migrate-from-addon-knobs)

Please upgrade and try out controls today!

**Comment by phaistonian** [comment]
@shilman Sorry - the title was meant to describe the issue illustrated in the screenshot.

Controls are great - will switch to that — which resolves the issue for me too.

Thank you
