### ISSUE TITLE
Old images for new docs

### ISSUE THREAD

**Issue by YozhEzhi** [storybookjs/storybook#14218]
**Describe the bug**
Images for docs should be updated :)

**To Reproduce**
Where:

1. Go to https://github.com/storybookjs/storybook/blob/master/addons/docs/docs/docspage.md#component-parameter
2. Go to https://github.com/storybookjs/storybook/blob/master/addons/docs/docs/mdx.md

**Expected behavior**

**Screenshots**
1. 
![image](https://user-images.githubusercontent.com/2706062/110910037-df648b80-8321-11eb-8bcd-88525ce0d3db.png)

2. 
![image](https://user-images.githubusercontent.com/2706062/110910126-fb682d00-8321-11eb-8a7e-3f5a42f6e21e.png)

**Additional context**
I can't found relative issue. Sorry if it'll be duplicate.

And I don't know how I could help to update images.

**Comment by jonniebigodes** [comment]
@YozhEzhi thank you for bringing this to our attention, really appreciate it. I've just merged a pull request addressing this issue and going to close this issue. 

Stay safe
