### ISSUE TITLE
Change default main.js config for svelte project

### ISSUE THREAD

**Issue by RemiKalbe** [storybookjs/storybook#14221]
Currently, when installing storybook in a svelte project, it's not possible to import an external svelte component. The following error occurs:

`Module not found: Error: Can't resolve .......`

**To Reproduce**
Just import an external library that relies on the "svelte" entry.
In my situation, I tried to use `svelte-loading-skeleton`

**Additional context**
As mentioned here https://github.com/storybookjs/storybook/issues/9542 the solution is to add this

```js
  webpackFinal(config) {
    return {
      ...config,
      resolve: {
        ...config.resolve,
        mainFields: ['svelte', 'browser', 'module', 'main']
      }
    }
  }

```

to the main.js file.
But it doesn't make sense in my opinion not to have that by default when you use svelte. (I used `npx sb init` to install storybook on my existing project).
So my request is to add that snippet (or something that fix this issue) by default when using `npx sb init` on a svelte project.

**Comment by shilman** [comment]
@j3rem1e What do you think?

**Comment by j3rem1e** [comment]
I agree.

The recommanded webpack configuration is : 

```js
resolve: {
    // see below for an explanation
    alias: {
      svelte: path.resolve('node_modules', 'svelte')
    },
    extensions: ['.mjs', '.js', '.svelte'],
    mainFields: ['svelte', 'browser', 'module', 'main']
  },
  module: {
    rules: [
      ...
      {
        test: /\.(html|svelte)$/,
        exclude: /node_modules/,
        use: 'svelte-loader'
      },
      {
        // required to prevent errors from Svelte on Webpack 5+, omit on Webpack 4
        test: /node_modules\/svelte\/.*\.mjs$/,
        resolve: {
          fullySpecified: false
        }
      }
      ...
    ]
  }
  ...
```

**Comment by shilman** [comment]
@j3rem1e does this belong in:
- the CLI template as suggested above
- the built-in svelte framework preset
- the preset inside https://github.com/storybookjs/addon-svelte-csf

Or somewhere else?

**Comment by j3rem1e** [comment]
this belong to the default svelte webpack preset, imo. It's implemented in the linked PR.

**Comment by shilman** [comment]
Son of a gun!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.0-rc.0 containing PR #14235 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
