### ISSUE TITLE
[6.2.0-beta.14] using asset/source Webpack 5 loader returns export string

### ISSUE THREAD

**Issue by FelixSab** [storybookjs/storybook#14222]
**Describe the bug**

Using the built-in Asset Modules (in my case `asset/source` for loading the svg images directly into the dom) in Webpack 5 results in a string looking like this: `export default __webpack_public_path__ + "static/media/Download.59ef5238.svg";`

**Expected behavior**

The .svg images are loaded into the dom properly

**Code snippets**

config/.storybook/main.ts
```ts
import webpack from 'webpack';
import initLoaders from '../webpack/loaders';
import paths from '../webpack/paths';

const { srcDir, appDir } = paths;

const {
  sassLoader,
  babelLoader,
  sassModuleLoader,
  svgLoader
} = initLoaders(process.env.NODE_ENV === 'development')

export default {
  stories: [`${srcDir}/**/*.stories.@(ts|tsx)`],
  addons: ['@storybook/addon-links', '@storybook/addon-essentials'],
  core: {
    builder: 'webpack5',
  },
  webpackFinal: async (config: webpack.Configuration) => ({
    ...config,
    resolve: {
      ...config.resolve,
      modules: [...(config.resolve?.modules || []), appDir],
      alias: {
        ...config?.resolve?.alias,
        'test': `${srcDir}/test`
      }
    },
    module: {
      ...config.module,
      rules: [
        babelLoader,
        sassLoader,
        sassModuleLoader,
        svgLoader, ...(config.module?.rules || [])]
    }
  }),
};
```

config/webpack/loaders/svg.ts:
```ts
export default function () {
  return {
    test: /\.svg$/,
    type: 'asset/source',
  };
}
```

**System**

  System:
    OS: Linux 4.15 Ubuntu 16.04.6 LTS (Xenial Xerus)
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz

  Binaries:
    Node: 14.16.0 - /usr/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 6.14.11 - /usr/bin/npm

  npmPackages:
    @storybook/addon-actions: ^6.2.0-beta.14 => 6.2.0-beta.14 
    @storybook/addon-essentials: ^6.2.0-beta.14 => 6.2.0-beta.14 
    @storybook/addon-links: ^6.2.0-beta.14 => 6.2.0-beta.14 
    @storybook/addon-storyshots: ^6.2.0-beta.14 => 6.2.0-beta.14 
    @storybook/builder-webpack5: ^6.2.0-beta.14 => 6.2.0-beta.14 
    @storybook/react: ^6.2.0-beta.14 => 6.2.0-beta.14

**Comment by shilman** [comment]
Storybook has a built-in loader for SVG. In order to provide your own you need to remove Storybook's:

https://github.com/storybookjs/storybook/blob/next/lib/builder-webpack5/src/preview/base-webpack.config.ts#L52-L58

**Comment by FelixSab** [comment]
I Want to use the currentColor attribute of the svg files, which only works if they are loaded as a source code and not as an url. This is why I would want to use my own svg loader

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
