### ISSUE TITLE
Object control does not work with value property containing string with commas 

### ISSUE THREAD

**Issue by khats** [storybookjs/storybook#14225]
**Describe the bug**
I have object control for JSON with following JSON:
```
{
  "configPropertyKey": "config,fakevalue"
}
```

Storybook ignores control value and does not append control value to url to  query paratemer`args` when some object property value contains comma. 

**To Reproduce**

1. Go to [https://next--storybookjs.netlify.app/official-storybook/?path=/story/@storybook/design-system_shadowboxcta--default](https://next--storybookjs.netlify.app/official-storybook/?path=/story/@storybook/design-system_shadowboxcta--default)
2. Replace `headerText` control value to  
```
{
  "configPropertyKey": "configfakevalue"
}
```
3.  Url changes to [https://next--storybookjs.netlify.app/official-storybook/?path=/story/@storybook/design-system_shadowboxcta--default&args=headingText.configPropertyKey:configfakevalue](https://next--storybookjs.netlify.app/official-storybook/?path=/story/@storybook/design-system_shadowboxcta--default&args=headingText.configPropertyKey:configfakevalue)
4. Replace control value to 
```
{
  "configPropertyKey": "config,fakevalue"
}
```
4. Url changes to [https://next--storybookjs.netlify.app/official-storybook/?path=/story/@storybook/design-system_shadowboxcta--default](https://next--storybookjs.netlify.app/official-storybook/?path=/story/@storybook/design-system_shadowboxcta--default) and control value ignored by story

**Expected behavior**
I expect control object value applied to story and url is like [https://next--storybookjs.netlify.app/official-storybook/?path=/story/@storybook/design-system_shadowboxcta--default&args=headingText.configPropertyKey:config,fakevalue](https://next--storybookjs.netlify.app/official-storybook/?path=/story/@storybook/design-system_shadowboxcta--default&args=headingText.configPropertyKey:config,fakevalue)

**Comment by khats** [comment]
Also expected to have a way to use object property keys with dot in name:
```
{
  "config.property" : "value"
}
```

**Comment by shilman** [comment]
@ghengeveld can you take a look at this and let me know what you think?

**Comment by ghengeveld** [comment]
A string value with comma should work as an arg, so I'm surprised it doesn't get through to the story. Need to verify that part.

Given that a comma isn't a supported character in URL args, it's correct that it's omitted there. That part works as intended.

**Comment by khats** [comment]
I think the reason with comma is because comma not listed in 
https://github.com/storybookjs/storybook/blob/be1dc2ea07de332cbc710ea8929c01f8b432915a/lib/core-client/src/preview/parseArgsParam.ts#L8

**Comment by ghengeveld** [comment]
Correct, such a value cannot be serialized to the URL (for XSS protection), so "ejecting" the iframe won't work. If this is a deal breaker, you can use a `mapping`: https://github.com/storybookjs/storybook/blob/next/docs/writing-stories/args.md#mapping-to-complex-arg-values

**Comment by ghengeveld** [comment]
Closing this now, please reopen if there's still an issue.

To be clear, commas *should* work as arg value, but will *not* be included in the URL due to security constraints.
