### ISSUE TITLE
[6.2.0-beta.11] MDX Merges Heading Levels 1 and 2

### ISSUE THREAD

**Issue by KenACollins** [storybookjs/storybook#14231]
**Describe the bug**
In a stories file using markdown (*.stories.mdx), if a heading level 1, denoted by a single pound symbol `#` at the beginning of the line, is followed by a heading level 2, denoted by two pound symbols `##`, even if there are multiple blank lines between them, these two headings will be merged onto the same line.

This issue does not occur if heading level 1 is followed a sentence on the next line which is not a heading or if a heading level 1 is followed by any other heading levels such as 3 `###`, 4, `####`, or 5 `#####`.

**To Reproduce**

1. Create a *.stories.mdx file and set it up for a component. Add a heading level 1, press Enter, and add a heading level 2.
2. When you load the *.stories.mdx file in the browser, you will see both headings appear together on the same line, with the text of the level 2 heading slightly smaller (as expected).

This issue occurs in the 6.2.0-beta.11 release but not in the stable 6.0.21 release of Storybook, I presume in the @storybook/addon-essentials package.

**Expected behavior**
Heading level 2 is expected to appear on the line below heading level 1, just as it does in the source *.stories.mdx file.

**Screenshots**
This is the error occurring in the 6.2.0-beta.11 release:

![Storybook 6 2 0-BETA Error with Markdown](https://user-images.githubusercontent.com/51036080/111044267-76f6d680-8415-11eb-9990-24589c95dbe9.png)

For comparison, here are the two headings appearing just fine in 6.0.21 Storybook tutorial:

![Storybook 6 0 21 Markdown Working Fine](https://user-images.githubusercontent.com/51036080/111044315-c1785300-8415-11eb-83ef-b0f5b2a35688.png)

*FYI, the styling of the two headers is a lot nicer in 6.0.21 and quite harsh in 6.2.0-beta.11. I sure hope this changes!*

**Code snippets**
The headings in both *.stories.mdx files are coded identically:

```
# Avatar

## Displays an image that represents a user or organization
```

**Comment by shilman** [comment]
That's pretty bizarre. Do you mind testing the 6.1.x stable release?

**Comment by KenACollins** [comment]
Okay, it took a couple hours to update my local copy of the Storybook tutorial from 6.0.21 to 6.1.21 but now that I have it running, I can report that the issue with the MDX headings 1 and 2 being merged does not occur. Therefore, the only place I am seeing it is in 6.2.0-beta.11 as previously reported.

**Comment by jonniebigodes** [comment]
@shilman it's working in the latest version (6.1.21), got a deployed Storybook [here](https://pedantic-bell-a99307.netlify.app/?path=/docs/design-system-avatar--standard) and code [here](https://github.com/jonniebigodes/design-systems-with-a-template). This issue that @KenACollins brought up I've run into when I migrated the tutorial for 6.0 and last week. From my notes and testing, it only happened once in each iteration. Restarting Storybook seemed to fix it, so I chalked it up as a fluke with MDX and never brought it to your attention. 

If you want I can follow up and test it with 6.2 (latest version) and see if the issue pops up.

**Comment by KenACollins** [comment]
@jonniebigodes -- I have stopped and started my 6.2.0-beta.11 app multiple times and the error never goes away. For now, my workaround is to follow heading 1 with heading 3.

**Comment by jonniebigodes** [comment]
@KenACollins that's a weird one. I've created a branch on my end and bumped the Storybook packages to the quasi latest versions, tested it, and wasn't able to reproduce it. [Here](https://github.com/jonniebigodes/design-systems-with-a-template/pull/3) is the pull request and [here](https://deploy-preview-3--pedantic-bell-a99307.netlify.app/?path=/docs/design-system-avatar--standard) the deployed Storybook.

I tested this before deploying and once again no such luck

**Comment by KenACollins** [comment]
@jonniebigodes, Bummer. Too bad you could not reproduce the error. What I can't tell from your pull request is if it is based off the same version I have, 6.2.0-beta.11.

**Comment by jonniebigodes** [comment]
@KenACollins as a testing measurement I started from Storybook version 6.2.0-beta.9 up to the rc version in the pull request. Each time purging the `node_modules` directory and the associated `yarn.lock` file so that the versions match up. Also, testing was done with a development Storybook build with `yarn storybook` and a production build with `yarn build-storybook && serve-prod` to check if the issue would present itself. But no such luck, I couldn't reproduce it!

**Comment by KenACollins** [comment]
Hi @jonniebigodes and @shilman -- I issued the following command...

```
npx sb@next upgrade --prerelease
```

...and was expecting to land on a later 6.2.0-beta.xx release but was surprised to find my app at a stable 6.2.1 release. The issue with the overlapping headers 1 and 2 does not occur! It was an odd one as neither of you were able to reproduce it but no worries now! I am closing this ticket.

**Comment by jonniebigodes** [comment]
@KenACollins indeed. Storybook 6.2 was just released, check the blog post [here](https://storybook.js.org/blog/storybook-6-2/). I'm glad that the issue is now fixed on your end! 

Let us know of any issues you might encounter with Storybook and good luck with the Design System you're working on!

Stay safe
