### ISSUE TITLE
[Vue 3] Wrong string's default prop formatting

### ISSUE THREAD

**Issue by Tim152** [storybookjs/storybook#14245]
**Describe the bug**
So, when you set up default property as string, it can't be parsed by story in appropriate way. You got this string with extra quotes in template. See the code:

**To Reproduce**
1) set up default prop as string
![Screenshot 2021-03-16 at 11 17 41](https://user-images.githubusercontent.com/14087100/111277639-bc034e80-8649-11eb-9ef4-44ce821df072.png)

2) create a story
![Screenshot 2021-03-16 at 11 12 49](https://user-images.githubusercontent.com/14087100/111277761-d9381d00-8649-11eb-97d8-2185b67b90f6.png)

3) console.log(props)
![Screenshot 2021-03-16 at 11 23 25](https://user-images.githubusercontent.com/14087100/111278081-346a0f80-864a-11eb-8969-8d0e7241756f.png)

**Expected behavior**
But if you define the prop value in the args it works as expected
![Screenshot 2021-03-16 at 11 26 16](https://user-images.githubusercontent.com/14087100/111278320-73986080-864a-11eb-84ab-a750bcd2368e.png)
![Screenshot 2021-03-16 at 11 09 35](https://user-images.githubusercontent.com/14087100/111278327-75faba80-864a-11eb-92f8-24ec90725e51.png)

**Additional context**
Storybook deps:
```
    "@storybook/addon-actions": "^6.2.0-beta.4",
    "@storybook/addon-essentials": "^6.2.0-beta.4",
    "@storybook/addon-links": "^6.2.0-beta.4",
    "@storybook/addon-storysource": "^6.1.10",
    "@storybook/preset-scss": "^1.0.3",
    "@storybook/storybook-deployer": "^2.8.7",
    "@storybook/theming": "^6.1.10",
    "@storybook/vue3": "^6.2.0-beta.4",
```

**Comment by shilman** [comment]
Closing as dupe to https://github.com/storybookjs/storybook/issues/14056

You can upgrade to the latest prerelease with 

```
npx sb upgrade --prerelease
```

Also please make sure your 6.1.x packages are upgraded 👍

**Comment by Tim152** [comment]
thank you!
