### ISSUE TITLE
Improve addons-docs blocks documentation

### ISSUE THREAD

**Issue by Sm1t** [storybookjs/storybook#14244]
**Is your feature request related to a problem? Please describe**
I was inspired by the [color documentation](https://5ccbc373887ca40020446347-qbeeoghter.chromatic.com/?path=/story/colors--page) in the design system, and wanted to do something similar in my project, but could not find documentation about Color, ColorPalette, etc. (of course, I found what I was looking for [after diving into the repository](https://github.com/storybookjs/storybook/blob/master/addons/docs/src/blocks/index.ts))

**Describe the solution you'd like**
I think it will be useful to add information about all components of addons-docs/blocks to the [official documentation](https://storybook.js.org/docs). This can be a simple table with a list of components and a short description, or even better, detailed documentation of the components, including examples.

**Describe alternatives you've considered**
We can also add a description for blocks directly to the addons-docs [readme.md](https://github.com/storybookjs/storybook/blob/master/addons/docs/README.md), and link to this description from the official documentation.

**Are you able to assist to bring the feature to reality?**
Yes, I agree to write the documentation as you see it

**Comment by Sm1t** [comment]
@jonniebigodes hi, what do you think about it?

**Comment by jonniebigodes** [comment]
With the recent pull request that was just merged the documentation was updated to include additional information and examples about the Docs blocks. 

Feel free to raise any additional issues and let me know about improvements to the existing documentation. Would love to hear everyone's thoughts.


Thanks for raising this and sorry for the delayed response.

Hope all of you have a great day and stay safe
