### ISSUE TITLE
[chore, webpack5] Replace hash with [fullhash]

### ISSUE THREAD

**Issue by phaistonian** [storybookjs/storybook#14253]
Webpack5 is _complaining_ about using `[hash]`.

>94% sealing after seal(node:1280) [DEP_WEBPACK_TEMPLATE_PATH_PLUGIN_REPLACE_PATH_VARIABLES_HASH] DeprecationWarning: [hash] is now [fullhash] (also consider using [chunkhash] or [contenthash], see documentation for details)

Changing [this](https://github.com/storybookjs/storybook/blob/cf656ca04d066b1815fa0e9b9be5248adeb80dbe/lib/builder-webpack5/src/preview/base-webpack.config.ts#L56) and [this](https://github.com/storybookjs/storybook/blob/cf656ca04d066b1815fa0e9b9be5248adeb80dbe/lib/builder-webpack5/src/preview/base-webpack.config.ts#L64) to `[fullhash]` will do it.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1199622255231368/1200072777589924) by [Unito](https://www.unito.io/learn-more)

**Comment by shilman** [comment]
@phaistonian Mind making a small PR with the changes? Will merge and release

**Comment by shilman** [comment]
Jeepers creepers!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.0-rc.2 containing PR #14255 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by 7rulnik** [comment]
@shilman @phaistonian it introduced an error in compilation when user has files with the same filename ```ERROR in Conflict: Multiple assets emit different content to the same filename```

Maybe we can use `contenthash`?

**Comment by shilman** [comment]
@phaistonian would you mind looking into this?

**Comment by phaistonian** [comment]
@shilman @7rulnik  We _always_ use `contenthash` in our configs.

The only reason I went for `fullhash` is that that's what Webpack5 suggested we should do.

Do you want me to push a new PR?

**Comment by 7rulnik** [comment]
@phaistonian I can create it :)

**Comment by phaistonian** [comment]
I know this is not the place to raise this issue, but I found a rather simple and elegant _solution_ to [this issue](https://github.com/storybookjs/storybook/issues/5065) but I am not how it should be introduced and where at.

The gains - in terms of performance and DX - is rather important and so, when you plan to visit this (@shilman ) let's sync — if you want to :)

**Comment by shilman** [comment]
Thanks guys 🙏🙏🙏

**Comment by shilman** [comment]
@phaistonian If this has big perf implications let's definitely discuss! Cc @tmeasday

**Comment by shilman** [comment]
Fixed in https://github.com/storybookjs/storybook/pull/14284 and released in 6.2.0-rc.x
