### ISSUE TITLE
Is React.Suspense not supported? Needed for Relay v11.0.0

### ISSUE THREAD

**Issue by H-Huang** [storybookjs/storybook#14265]
**Describe the bug**
Using React.Suspense in a story causes the error `Cannot convert a Symbol value to a string `.

**To Reproduce**
```Javascript
// MainPage.stories.jsx
import React from "react";
import { Story, Meta } from "@storybook/react";
import MainPage from "../pages/MainPage";

export default {
  title: "Example/MainPage",
  component: MainPage,
  decorators: [
    (Story) => (
      <React.Suspense fallback={null}>
        <Story />
      </React.Suspense>
    ),
  ],
} as Meta;

const Template: Story = (args) => <MainPage {...args} />;
export const MyStory= Template.bind({});
```

**Screenshots**
![image](https://user-images.githubusercontent.com/14858254/111578165-d08e3680-8770-11eb-9f99-aa53da312ae5.png)

**System**
<details>
Environment Info:

  System:
    OS: Linux 4.19 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 14.11.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
  npmPackages:
    @storybook/addon-actions: ^6.1.20 => 6.1.21 
    @storybook/addon-essentials: ^6.1.20 => 6.1.21 
    @storybook/addon-links: ^6.1.20 => 6.1.21 
    @storybook/node-logger: ^6.1.20 => 6.1.21 
    @storybook/preset-create-react-app: ^3.1.6 => 3.1.7 
    @storybook/react: ^6.1.20 => 6.1.21 
</details>

**Additional context**
I'm still new to and exploring both Storybook and Relay so if I'm missing something let me know. If there is any additional information about storybook that is specific for Relay would love to know about it!

**Comment by shilman** [comment]
closing as dupe to https://github.com/storybookjs/storybook/issues/11554, which has a workaround
