### ISSUE TITLE
Storybook not showing Radio Button Group for a typescript property

### ISSUE THREAD

**Issue by luisrudge** [storybookjs/storybook#14263]
**Describe the bug**
Hi, there. Storybook is not showing the usual Radio Button Group for my 'variant' props in this case. If I change my `ButtonVariants`  props to `'default' | 'info'` etc, then it works, but I want to have this in a separate file so I can reuse it. Am I missing something? Thanks!

**To Reproduce**
- Declare a type called `DefaultVariants` in a file called `types.ts`
- Import this type in a file called `Button.tsx`
- In the same file, declare a new type called `ButtonVariants` and use the same value as `DefaultVariants`
- Create a component that uses this new type as a prop
- 
**Expected behavior**
I should be able to see a Radio Button Group with all the available options from my typescript type

**Screenshots**

**When we use an imported type, there's no Radio Button Group**
![image](https://user-images.githubusercontent.com/941075/111482579-cb020380-8712-11eb-81ce-08b554458a6f.png)

**When we declare the options in the same file, there's a Radio Button Group**
![image](https://user-images.githubusercontent.com/941075/111483260-68f5ce00-8713-11eb-9721-126915d271d4.png)

**Code snippets**

**This works:**
```ts
type AlertVariants = 'danger' | 'info' | 'warning' | 'success';
export interface AlertProps extends React.HTMLAttributes<HTMLDivElement> {
  variant: AlertVariants;
}
```

**This doesn't work:**
```ts
import { DefaultVariants } from './types';
export type ButtonVariants = DefaultVariants;
export interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: ButtonVariants;
}
```

**System**
```
Environment Info:

  System:
    OS: macOS 11.2.3
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 15.11.0 - ~/.nvm/versions/node/v15.11.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v15.11.0/bin/yarn
    npm: 7.6.1 - ~/.nvm/versions/node/v15.11.0/bin/npm
  Browsers:
    Edge: 89.0.774.48
    Safari: 14.0.3
  npmPackages:
    @storybook/addon-essentials: ^6.1.21 => 6.1.21 
    @storybook/addon-info: ^5.3.21 => 5.3.21 
    @storybook/addon-links: ^6.1.21 => 6.1.21 
    @storybook/addons: ^6.1.21 => 6.1.21 
    @storybook/react: ^6.1.21 => 6.1.21 
```

**Comment by luisrudge** [comment]
Also, I'd love to help fix this, if anyone wants to point me in the right direction 😬

**Comment by shilman** [comment]
@luisrudge would love the help! first step is to see what `react-docgen-typescript` outputs, which is what we use under the hood. if that works, it's a bug in storybook and i can help guide you towards a fix. if not, we'll need to figure out how to fix that library and maybe @hipstersmoothie can help.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid.

Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
