### ISSUE TITLE
[6.2.0-rc.2] problem with resolving imports in development mode

### ISSUE THREAD

**Issue by idbartosz** [storybookjs/storybook#14269]
**Describe the bug**

In Storybook 6.2.0 development mode there's a problem with import resolving. This problem only occurs in the development mode the **builded version works fine**.

**To Reproduce**

1. Bootstrap an example project with `npx -p @storybook/cli@next sb init --type react`
1. Install some packages which support different modules like CJS and ESM
1. In development mode try to import and use that package

* when imported in standard way `import ReactMapboxGl, { Layer, Feature } from "react-mapbox-gl"` package doesn't work correctly in Storybook
* when specifying the import path directly to ESM it works ok `import ReactMapboxGl, { Layer, Feature } from "react-mapbox-gl/lib-esm"`

**Expected behavior**

Imports in development mode should work as they were in Storybook 6.1

**Screenshots**

https://user-images.githubusercontent.com/21260478/111620337-dde60800-87e6-11eb-96de-d28e5f67fa2f.mov

**System**

```
  System:
    OS: macOS 11.2.3
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
  Binaries:
    Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.16.0/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v14.16.0/bin/npm
  Browsers:
    Chrome: 89.0.4389.90
    Firefox: 86.0.1
    Safari: 14.0.3
  npmPackages:
    @storybook/addon-actions: ^6.2.0-rc.2 => 6.2.0-rc.2 
    @storybook/addon-essentials: ^6.2.0-rc.2 => 6.2.0-rc.2 
    @storybook/addon-links: ^6.2.0-rc.2 => 6.2.0-rc.2 
    @storybook/react: ^6.2.0-rc.2 => 6.2.0-rc.2 
```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1199622255231368/1200080906609589) by [Unito](https://www.unito.io/learn-more)

**Comment by shilman** [comment]
Do you have a repro repo you can share?

**Comment by idbartosz** [comment]
@shilman I see there's already a PR with fix, do you still need a reproduction repo?

**Comment by shilman** [comment]
@idbartosz no, i think we figured out the problem and can hopefully get you the fix soon

**Comment by shilman** [comment]
Gadzooks!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.0-rc.4 containing PR #14271 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
