### ISSUE TITLE
Typescript module resolution with `js` extension

### ISSUE THREAD

**Issue by 43081j** [storybookjs/storybook#14274]
Let's say we have sources like this:

```ts
import {foo} from './foo.js';

export const fn = () => foo;
```

This works in production with `tsc` because it is assumed the transpiled output will be alongside this file. `tsc` allows this purposely so you're not writing "fake" import paths in your sources (which means tsc doesn't have to rewrite them).

If we try this through storybook, though, we get:

```
Module not found: Error: Can't resolve './foo.js' 
```

Changing the import to have no extension results in storybook being happy.

Is there a known bit of config im missing for telling storybook (and thus babel-loader/webpack) how to resolve this?

I assumed because the typescript preset has both extensions, webpack would at least resolve it:

https://github.com/storybookjs/presets/blob/adbfff17504021f6bdb4ef9b1232b0533213e4d6/packages/preset-typescript/src/helpers/processConfig.ts#L32

So maybe babel-loader's config is the culprit?

**Comment by Niznikr** [comment]
Would love to know as well where this can be tweaked. We're forced to use a script to insert the `.js` separately for our design system as a result of Storybook not working with it which doesn't feel great. This feature is important for [ES modules and import maps](https://blog.logrocket.com/es-modules-in-browsers-with-import-maps/).

**Comment by razor-x** [comment]
Is this helps anyone, I am using this as a workaround. It's not pretty, but hopefully good enough until we get official support. The original idea is from here: https://github.com/vercel/next.js/issues/41961#issuecomment-1311091390

```ts
{
  webpackFinal: async (config) => {
    if (config?.plugins == null) config.plugins = []

    config.plugins.push(
      new NormalModuleReplacementPlugin(/\.js$/, (resource) => {
        if (resource.request.startsWith('.')) {
          const path = resolve(resource.context, resource.request)

          if (!path.includes('node_modules') && !existsSync(path)) {
            const { dir, name } = parse(path)
            const extensionlessPath = join(dir, name)

            for (const fallbackExtension of ['.tsx', '.ts', '.js']) {
              const fallback = `${extensionlessPath}${fallbackExtension}`
              if (existsSync(fallback)) {
                resource.request = resource.request.replace(
                  /\.js$/,
                  fallbackExtension
                )
                break
              }
            }
          }
        }
      })
    )

    // Handle custom TypeScript paths

    // Handle lib/* alias
    config.plugins.push(
      new NormalModuleReplacementPlugin(/^lib\/.*js$/, (resource) => {
        resource.request = resource.request.replace(/\.js$/, '')
      })
    )
    // Handle index.js alias
    config.plugins.push(
      new NormalModuleReplacementPlugin(/^index\.js$/, (resource) => {
        resource.request = 'src/index.ts'
      })
    )

    if (config?.resolve == null) config.resolve = {}
    if (config?.resolve?.plugins == null) config.resolve.plugins = []
    config.resolve.plugins.push(new TsconfigPathsPlugin({ baseUrl: '.' }))

    return config
  }
}

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
