### ISSUE TITLE
Storybook Init doesn't work with PNPM

### ISSUE THREAD

**Issue by abhijit-kar** [storybookjs/storybook#14275]
Storybook init command results in error: "Cannot read property parent of 'null'", while using pnpm.

**Steps**
1. pnpx -p @storybook/cli sb init
2. Wait an eternity for things to finish.

**Expected behavior**
1. I expect to be able to use Storybook.
2. I wish that the init command for svelte project generated svelte specific example stubs.
3. I expected that Storybook moved on to better bundlers like Snowpack, Vite combined with Rollup by now.

**System**
    OS: Linux 5.4 Zorin OS 15.3
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
  Binaries:
    Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
    npm: 7.6.3 - ~/.nvm/versions/node/v14.16.0/bin/npm
  Browsers:
    Chrome: 88.0.4324.182
    Firefox: 86.0.1

**Additional context**
When I used npm, the initialization worked great, however it failed to start later due to some other issue.

Here's a link to my repo, in case the problem runs deeper: [Quiller Bee GitHub](https://github.com/quillerbee/job-portal)

**Comment by shilman** [comment]
closing as duple to #13428
