### ISSUE TITLE
Support use of updated custom-elements.json file

### ISSUE THREAD

**Issue by brion-fuller** [storybookjs/storybook#14286]
**Is your feature request related to a problem? Please describe**
`custom-elements.json` has changed over the years and currently not integrated with autogenerating of args for web components.  Add support for https://github.com/webcomponents/custom-elements-manifest

**Describe the solution you'd like**
I would like to map the new schema in support for auto generated args.

**Are you able to assist to bring the feature to reality?**
Yes

**Comment by shilman** [comment]
That sounds great. Will the processing be backwards compatible? That's my only concern if we're trying to get this out in 6.3.

**Comment by brion-fuller** [comment]
Yeah I think it should be.  I was planning to add a mapper for different versions because it’s still not a stable spec.

**Comment by Niznikr** [comment]
Could we also add support for the current spec for `@storybook/lit` so we can use something like `setCustomElements` that `@storybook/web-components` uses? Would love to start using `@storybook/lit` but it currently does not generate an API table for components.
