### ISSUE TITLE
Allow enabling compression in development

### ISSUE THREAD

**Issue by kaelig** [storybookjs/storybook#14280]
**Is your feature request related to a problem? Please describe**
In development (when running `start-storybook -s .storybook/public -p 6006`), large bundles are slow to load.

**Describe the solution you'd like**
I'd like assets served by the development server to be compressed (either by default or via a setting). NOT minified, as minification has a significant impact on compilation time.

Gzip compression at a level 1 should provide great client-side performance benefits without hindering server performance.

**Describe alternatives you've considered**
- Our nginx server is proxying requests to a private URL to storybook on localhost:6006 (which is running on a remote, cloud-based container). nginx may allow us to gzip proxied responses, but my early explorations were unsuccessful.
- Turning on compression via a custom webpack config, which was unsuccessful in my attempts (please tell me if I'm missing something!)

**Are you able to assist to bring the feature to reality?**
I can help test PRs and pre releases.

**Additional context**
We're not developing locally, but in the cloud (think: GitHub Codespaces), where bundle size has a significant impact on how fast Storybook can be loaded by the user's browser. Our previewer's bundle size is ~20MB.

**Comment by shilman** [comment]
Egads!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.3.0-alpha.1 containing PR #14459 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
