### ISSUE TITLE
"@storybook/builder-webpack5 > webpack-filter-warnings-plugin@1.2.1" has incorrect peer dependency "webpack@^2.0.0 || ^3.0.0 || ^4.0.0".

### ISSUE THREAD

**Issue by ntucker** [storybookjs/storybook#14294]
**Describe the bug**
`"@storybook/builder-webpack5 > webpack-filter-warnings-plugin@1.2.1" has incorrect peer dependency "webpack@^2.0.0 || ^3.0.0 || ^4.0.0"`

**To Reproduce**

1. Install `@storybook/builder-webpack5` via yarn
2. Observe warning message

**Expected behavior**
No warnings as webpack5 should be expected.

**System**
```bash
  System:
    OS: Linux 5.4 Ubuntu 20.04 LTS (Focal Fossa)
    CPU: (32) x64 AMD Ryzen 9 5950X 16-Core Processor
  Binaries:
    Node: 14.13.1 - ~/.nvm/versions/node/v14.13.1/bin/node
    Yarn: 1.22.5 - /mnt/c/Program Files (x86)/Yarn/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v14.13.1/bin/npm
  npmPackages:
    @storybook/addon-essentials: 6.2.0-rc.6 => 6.2.0-rc.6 
    @storybook/addon-links: 6.2.0-rc.6 => 6.2.0-rc.6 
    @storybook/addons: 6.2.0-rc.6 => 6.2.0-rc.6 
    @storybook/builder-webpack5: 6.2.0-rc.6 => 6.2.0-rc.6 
    @storybook/react: 6.2.0-rc.6 => 6.2.0-rc.6 
```

**Additional context**

**Comment by shilman** [comment]
closing as duplicate to #13990

**Comment by andig** [comment]
I'm still seeing this using 6.5.9 and although https://github.com/storybookjs/storybook/issues/13990 has been merged long time ago.
