### ISSUE TITLE
6.2.0-rc.6 inifite build loop

### ISSUE THREAD

**Issue by ntucker** [storybookjs/storybook#14291]
**Describe the bug**
This makes infinite build loop. I guess the output is also input, triggering rebuild?

**To Reproduce**

1. git clone https://github.com/ntucker/storybook6.2-infiniteloop
2. cd storybook6.2-infiniteloop
3. yarn install
4. yarn storybook

**Expected behavior**
Build finishes and shows storybook

**Code snippets**
https://github.com/ntucker/storybook6.2-infiniteloop

**System**
Environment Info:

  System:
    OS: Linux 5.4 Ubuntu 20.04 LTS (Focal Fossa) - run through WSL2 on Win10
    CPU: (32) x64 AMD Ryzen 9 5950X 16-Core Processor
  Binaries:
    Node: 14.13.1 - ~/.nvm/versions/node/v14.13.1/bin/node
    Yarn: 1.22.5 - /mnt/c/Program Files (x86)/Yarn/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v14.13.1/bin/npm
  npmPackages:
    @storybook/addon-essentials: ^6.2.0-rc.6 => 6.2.0-rc.6 
    @storybook/addon-links: ^6.2.0-rc.6 => 6.2.0-rc.6 
    @storybook/addons: ^6.2.0-rc.6 => 6.2.0-rc.6 
    @storybook/builder-webpack5: ^6.2.0-rc.6 => 6.2.0-rc.6 
    @storybook/react: ^6.2.0-rc.6 => 6.2.0-rc.6 

**Additional context**
Using webpack4 with 6.2.0-rc.6 - there is no problem.

**Comment by ntucker** [comment]
Turns out need the `watchOptions` set. Be sure to include in upgrade guide?

**Comment by shilman** [comment]
@ntucker Can you be more specific? We haven't run into this yet.

**Comment by ntucker** [comment]
https://github.com/ntucker/anansi/commit/19c26dbd7512abad5ddb55dd997cb89d132ce997 was my fix.

- custom webpack config
- needed to add 'watchOptions' for it to work.
- repo included will fail. upgrade the config to beta.6 to see it work.

**Comment by shilman** [comment]
Thanks so much. Will check it out on Monday 🙏
