### ISSUE TITLE
Unexpected 'Compiling RuleSet failed: Properties query are unknown' error with Vue 2 in a Laravel project

### ISSUE THREAD

**Issue by danielbachhuber** [storybookjs/storybook#14300]
**Describe the bug**

After I ran `npx sb init` inside of my Laravel project (which uses Vue 2), running `npm run storybook` produces this error:

```
ERR! Error: Compiling RuleSet failed: Properties query are unknown (at clonedRuleSet-11[0].rules[0]: [object Object])
ERR!     at RuleSetCompiler.error (/Users/danielbachhuber/projects/cedar/node_modules/webpack/lib/rules/RuleSetCompiler.js:373:10)
ERR!     at RuleSetCompiler.compileRule (/Users/danielbachhuber/projects/cedar/node_modules/webpack/lib/rules/RuleSetCompiler.js:196:15)
ERR!     at /Users/danielbachhuber/projects/cedar/node_modules/webpack/lib/rules/RuleSetCompiler.js:154:9
ERR!     at Array.map (<anonymous>)
ERR!     at RuleSetCompiler.compileRules (/Users/danielbachhuber/projects/cedar/node_modules/webpack/lib/rules/RuleSetCompiler.js:153:16)
ERR!     at RuleSetCompiler.compileRule (/Users/danielbachhuber/projects/cedar/node_modules/webpack/lib/rules/RuleSetCompiler.js:184:30)
ERR!     at /Users/danielbachhuber/projects/cedar/node_modules/webpack/lib/rules/RuleSetCompiler.js:154:9
ERR!     at Array.map (<anonymous>)
ERR!     at RuleSetCompiler.compileRules (/Users/danielbachhuber/projects/cedar/node_modules/webpack/lib/rules/RuleSetCompiler.js:153:16)
ERR!     at cloneRule (/Users/danielbachhuber/projects/cedar/node_modules/vue-loader/lib/plugin-webpack5.js:144:33)
ERR!     at /Users/danielbachhuber/projects/cedar/node_modules/vue-loader/lib/plugin-webpack5.js:111:25
ERR!     at Array.map (<anonymous>)
ERR!     at VueLoaderPlugin.apply (/Users/danielbachhuber/projects/cedar/node_modules/vue-loader/lib/plugin-webpack5.js:111:8)
ERR!     at webpack (/Users/danielbachhuber/projects/cedar/node_modules/@storybook/core/node_modules/webpack/lib/webpack.js:51:13)
ERR!     at startPreview (/Users/danielbachhuber/projects/cedar/node_modules/@storybook/core/dist/server/dev-server.js:420:39)
ERR!     at async Promise.all (index 0)
```

Here's my `package.json` https://gist.github.com/danielbachhuber/667f6717d299b23b54bb137aa77e6161

**Comment by shilman** [comment]
Do you have a repro repo you can share?

**Comment by danielbachhuber** [comment]
It's private, unfortunately. I was hoping this was an error someone else had seen before 😄 I might be able to reproduce the issue by copying some of the dependencies into a clean repo.

**Comment by danielbachhuber** [comment]
@shilman Here's a repo that reproduces: https://github.com/danielbachhuber/storybook-js-issue-14300

Notably, I'm using https://github.com/JeffreyWay/laravel-mix for building. The webpack config is in `node_modules/laravel-mix/setup/webpack.config.js`

Although, if they're two separate processes, I'm not sure whether they'd conflict.

**Comment by pocka** [comment]
Maybe incompatible webpack versions? It seems [laravel-mix uses webpack5](https://github.com/JeffreyWay/laravel-mix/blob/467f0c9b01b7da71c519619ba8b310422321e0d6/package.json#L89). If it's the culprit, [the new `webpack5` builder](https://gist.github.com/shilman/8856ea1786dcd247139b47b270912324#upgrade) might solve your problem.

**Comment by danielbachhuber** [comment]
@pocka I think that might be it! Storybook made more progress after running `npx sb@next init --builder webpack5`.

When I try `npm run storybook`, I see a couple of errors:

<img width="1413" alt="image" src="https://user-images.githubusercontent.com/36432/113336078-b0b35280-92da-11eb-9c50-dedeb5111938.png">

```
(node:52491) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'createSnapshot' of undefined
```

```
95% emitting emit(node:52491) UnhandledPromiseRejectionWarning: TypeError: compilation.getAssetPath is not a function
```

It gets stuck here:

<img width="995" alt="image" src="https://user-images.githubusercontent.com/36432/113336137-c6c11300-92da-11eb-9500-35f6dd51c918.png">

However, `npm run build-storybook` runs without error:

<img width="914" alt="image" src="https://user-images.githubusercontent.com/36432/113336176-d5a7c580-92da-11eb-83d2-efa1b3427a4f.png">

The `index.html` doesn't quite work but I'm assuming that's because I need to do some web server configuration:

<img width="1407" alt="image" src="https://user-images.githubusercontent.com/36432/113336228-eeb07680-92da-11eb-8088-cf3c0086f01b.png">

**Comment by pocka** [comment]
@danielbachhuber 
A quick search shows webpack5 users also facing similar errors. Probably no `iframe.html` on `build-storybook` is also due to the same reason (an incompatible `html-webpack-plugin` version).
https://github.com/storybookjs/storybook/issues/13332
https://github.com/storybookjs/storybook/issues/14273

I think [this comment](https://github.com/storybookjs/storybook/issues/13332#issuecomment-808789815) could help you.

**Comment by danielbachhuber** [comment]
@pocka Works great, thank you!
