### ISSUE TITLE
Typescript: Propagate Meta Generic Args type to interface properties

### ISSUE THREAD

**Issue by maxmezzomo** [storybookjs/storybook#14301]
**Is your feature request related to a problem? Please describe**
Specified Generic Type for Meta type is not provided as a generic to properties of the interface, specifically the proprties of the Annotations type. I have some examples in Additional context.

**Describe the solution you'd like**
It would a nice feature to have the Meta type propagate the Args to all relevant interface properties belonging to it. The structure already seems close to a point where it would allow this.

**Describe alternatives you've considered**
For simple cases you can assign an object other than Meta to the default export but doesn't seem constructive.

**Are you able to assist to bring the feature to reality?**
I could make a PR for it.

**Additional context**
Meta is defined as :
```
export declare type Meta<Args = DefaultArgs> = BaseMeta<ReactComponent> & Annotations<Args, ReactReturnType>;
```
Annotations received the Generic Args and only propagates it to its 'args' property:
```
export interface Annotations<Args, StoryFnReturnType> {

    args?: Partial<Args>;

    argTypes?: ArgTypes;

    parameters?: Parameters;

...

}
```
For example, argsTypes could also benefit from receiving the generic Args:

```
export interface Annotations<Args, StoryFnReturnType> {

    args?: Partial<Args>;

    argTypes?: ArgTypes<Args>; 

    parameters?: Parameters;

...

}
```

Then ArgTypes could be defined as:
```
type ArgTypes<Args> = {
    [key in keyof Args]: ArgType;
}
```
instead of :
```
export interface ArgTypes {
    [key: string]: ArgType;
}
```

**Comment by shilman** [comment]
@maxmezzomo this looks like a great enhancement. A PR would be very welcome!

**Comment by maxmezzomo** [comment]
Nice, I'll start in the next few days see what we can get working

**Comment by maxmezzomo** [comment]
Following up, I put in a PR a few months ago.  PR #14356. Is there anything to follow up with.

**Comment by shilman** [comment]
Ta-da!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-alpha.25 containing PR #14356 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
