### ISSUE TITLE
[6.2.0-beta.11] Missing Two html.js Files

### ISSUE THREAD

**Issue by KenACollins** [storybookjs/storybook#14320]
**Describe the bug**
Hi, my 6.2.0-beta.11 installation is missing two `html.js` files (which I only discovered because the storybook-addon-designs add-on version 5.4.5 bombed for this reason). I was able to copy them from a stable 6.1.21 build and I am good now but are these files actually missing from the beta release after all dependencies are installed?

The first `html.js` file is missing at this path: `node_modules\@storybook\components\html.js`

Its content should be:

```
module.exports = require('./dist/esm/html');
```

The second `html.js file` is missing at this path: `node_modules\@storybook\components\dist\esm\html.js`

Its contents are 45 lines so I won't repeat them here.

**To Reproduce**

1. Issue `npx sb@next upgrade --prerelease` to install all Storybook packages at 6.2.0-beta.11 level.
1. Navigate to `node_modules\@storybook\components` folder. It should be missing a one-line `html.js` file.
1. Drill down two more levels to `node_modules\@storybook\components\dist\esm` folder. It should be missing a 45 line `html.js` file.

**Expected behavior**
The beta build should contain two `html.js` files under `node_modules\@storybook\components` folder path.

**Error**
Until I made the configuration changes described above, I was seeing this error:

```
Module not found: Error: Can't resolve '@storybook/components/html'
```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1199622255231368/1200102876009306) by [Unito](https://www.unito.io/learn-more)

**Comment by shilman** [comment]
Ta-da!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.0-rc.11 containing PR #14369 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by KenACollins** [comment]
@shilman,

So don't you mean the command to upgrade would include `@next` as in:

```
npx sb@next upgrade --prerelease
```

**Comment by shilman** [comment]
@KenACollins both commands will work. it's the `--prerelease` flag that's important
