### ISSUE TITLE
🐛 Actions don't work on non-`onClick` functions

### ISSUE THREAD

**Issue by Sawtaytoes** [storybookjs/storybook#14327]
**Describe the bug**
Actions don't work on non-`onClick` functions when a default value is defined in the component.

**To Reproduce**

1. Setup a create-react-app project with `sb init`
2. Edit the `Button` (and its prop types) to use `onClick2`:
```jsx
export const Button = ({
  onClick2 = Function.prototype,
}) => (
  <button
    onClick={onClick2}
    type="button"
  >
    Hello
  </button>
)
```
3. Click on the `Button` in Storybook, actions won't show.

I first noticed this with `onChange` and `onSubmit`; both which had default values.

**Expected behavior**
I expect to see actions logged when I click the button.

**Screenshots**
Working:
![image](https://user-images.githubusercontent.com/3948069/112278367-bf519800-8c50-11eb-9c26-d0f443452393.png)

Not working:
![image](https://user-images.githubusercontent.com/3948069/112278419-cf697780-8c50-11eb-888d-6893431c2793.png)

**Code snippets**
```jsx
export const Button = ({
  onClick2 = Function.prototype,
}) => (
  <button
    onClick={onClick2}
    type="button"
  >
    Hello
  </button>
)
```

**System**
I deleted the clean project I made to for testing, but I've seen the issue in my existing project as well:

```
Environment Info:

  System:
    OS: Windows 10 10.0.19042
    CPU: (16) x64 AMD Ryzen 7 3800X 8-Core Processor
  Binaries:
    Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 89.0.4389.90
    Edge: Spartan (44.19041.423.0), Chromium (89.0.774.57)
  npmPackages:
    @storybook/addon-actions: ^6.1.21 => 6.1.21
    @storybook/addon-controls: ^6.1.21 => 6.1.21
    @storybook/addon-essentials: ^6.1.21 => 6.1.21
    @storybook/addon-links: ^6.1.21 => 6.1.21
    @storybook/node-logger: ^6.1.21 => 6.1.21
    @storybook/react: ^6.1.21 => 6.1.21
```

**Additional context**
`defaultProps` is deprecated (https://github.com/facebook/react/pull/16210).

I don't want to have to depend on it for default values even though I think it's superior to defining ECMAScript default values.

**Comment by lijing666** [comment]
I found actions not work  even with next version `"@storybook/vue": "^6.2.0-rc.8"`, only 'onClick' works, even 'on-click' not works too, I have also turned on argTypesRegex config globally:
```
export const parameters = {
  actions: { argTypesRegex: "^(on.*)" }
}
```

**Comment by shilman** [comment]
What's happening here is that the actions addon is scanning through the existing argTypes and looking for function argTypes whose names matches the regex. When it fails, it's because those argTypes don't exist or because they are not of type function. Perhaps we need to update the design to make it less finicky. Suggestions welcome!!

**Comment by Sawtaytoes** [comment]
Just as a quick update, I did this to fix it locally:
```jsx
export default {
	args: {
		onChange: action(),
		onSubmit: action(),
	},
	argTypes: {
		onChange: 'changed',
		onSubmit: 'submitted',
	},
	component: OneForm,
	title: 'OneForm',
}
```

**Comment by Sawtaytoes** [comment]
@shilman What exactly would need to change to make this work properly in Storybook? It's using `PropTypes.func` in my component.

**Comment by shilman** [comment]
I take it back after reading the code:

https://github.com/storybookjs/storybook/blob/next/addons/actions/src/preset/addArgs.ts#L15-L28

As long as there is an argType that matches the regex, this should add a `defaultValue` which is the action, which should then get passed to the component as an arg. If it's not working and you have a clean repro, I'm happy to take a look.

**Comment by Sawtaytoes** [comment]
I'll remake that `create-react-app` repo again tomorrow and let you look into it.

**Comment by Sawtaytoes** [comment]
@shilman https://github.com/Sawtaytoes/fresh-storybook-click-test

**Comment by shilman** [comment]
@Sawtaytoes you're not binding the `onClick2` handler in your story. When I fix that, it works as expected:

```js
export const Button = ({
  primary,
  backgroundColor,
  size,
  label,
  onClick2 = Function.prototype,
  ...props
}) => {
  const mode = primary
    ? "storybook-button--primary"
    : "storybook-button--secondary";
  return (
    <button
      type="button"
      className={["storybook-button", `storybook-button--${size}`, mode].join(
        " "
      )}
      style={backgroundColor && { backgroundColor }}
      {...props}
      onClick={onClick2} // <<-- NEEDED
    >
      {label}
    </button>
  );
};
```

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).

**Comment by PATWIS** [comment]
Hi,

I've encountered a similar issue with actions in my current demo using @storybook/angular version ^9.1.10. The problem also appears in the React example on StackBlitz provided at new-storybook.netlify.app:

https://stackblitz.com/github/storybookjs/sandboxes/tree/next/react-vite/default-ts/after-storybook

In both cases, the onClick event of the example button (with appropriate binding) does not trigger any visible effects in the Actions panel.
