### ISSUE TITLE
Storybook fails to load story when generated code from @openapitools/openapi-generator-cli is used

### ISSUE THREAD

**Issue by mgansler** [storybookjs/storybook#14346]
**Describe the bug**
Storybook fails to load a story as soon as generated code from @openapitools/openapi-generator-cli is used.
The context is a NX monorepo but there is no issue when self-written code is used. We could not find what exactly breaks storybook. 

**To Reproduce**

I created a minimal example: https://github.com/mgansler/openapi-storybook

1. Clone Repo
2. Install dependencies (`yarn install`)
3. Start Storybook: `nx run react-app:storybook`
4. http://localhost:4400/?path=/story/app--my-app-story should show a story
5. Remove usage of generated code: remove line 9 from `app.tsx` https://github.com/mgansler/openapi-storybook/blob/38517464b39eb781b825bc6c0fc10bf923a4589f/apps/react-app/src/app/app.tsx#L9
6. Story shows up

**Expected behavior**
Story should show up when generated code is used.

**Code snippets**
https://github.com/mgansler/openapi-storybook

**System**
Environment Info:

  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  Binaries:
    Node: 12.19.0 - ~/.nvm/versions/node/v12.19.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v12.19.0/bin/yarn
    npm: 7.5.2 - ~/.nvm/versions/node/v12.19.0/bin/npm
  Browsers:
    Chrome: 89.0.4389.90
    Firefox: 87.0
    Safari: 14.0.3

**Additional context**
I did not try the code "in production" in this example but in our project (which I cannot share) the App itself works without any issues. Only storybook fails to show the story.

**Comment by j3rem1e** [comment]
The storybook fails to load because of : 

```
Cannot read property 'middleware' of undefined
    at Configuration.get (runtime.ts:157)
    at new BaseAPI (runtime.ts:28)
    at PetApi._createSuperInternal (api-client.ts:3)
    at new PetApi (PetApi.ts:66)
    at Module../apps/react-app/src/app/app.tsx (app.tsx:9)
    at __webpack_require__ (bootstrap:848)
    at fn (bootstrap:150)
    at Module../apps/react-app/src/app/app.stories.tsx (app.stories.tsx:1)
    at __webpack_require__ (bootstrap:848)
    at fn (bootstrap:150)
```

The `Configuration` class doesn't seem to be valid : 

```
export class Configuration {
    constructor(private configuration: ConfigurationParameters = {}) {}

    get basePath(): string {
        return this.configuration.basePath != null ? this.configuration.basePath : BASE_PATH;
    }
```

In the constructor, `configuration` is not copied to this. When I add this line, it works : 
```
    constructor(private configuration: ConfigurationParameters = {}) {
        this.configuration = configuration;
    }
```

that's said, I am not an expert of this generator, but the code in this repo doesn't look like the code i am used to.

**Comment by mgansler** [comment]
@j3rem1e thanks! Can confirm, with this change the story does show up in our private repo, there is still another error but we can fix that. How did you get it to print that error though?

**Comment by j3rem1e** [comment]
This kind of errors are catched here, but the original exception is not shown : https://github.com/storybookjs/storybook/blob/next/lib/core-client/src/preview/loadCsf.ts#L60

I used to change this log, but I should maybe make a PR about that :)

When I remove the babel plugin `plugin-transform-class` here, storybook works : https://github.com/storybookjs/storybook/blob/next/lib/core-common/src/utils/babel.ts#L19

However, it's beyond my competence and times to investigate more, debugging babel is... well.
There are probably interactions with the babel preset of your project, too.

**Comment by stu039** [comment]
@j3rem1e  - Did you ever find a solution to this one? Exact same issue over here

**Comment by ndelangen** [comment]
This doesn't seem like a storybook issue to me.
