### ISSUE TITLE
Webpack 4 dependency tree has a High severity vulnerability

### ISSUE THREAD

**Issue by ricoli** [storybookjs/storybook#14347]
If you are reporting a bug or requesting support, start here:
### Bug or support request summary

This repository depends on Webpack 4 and even the latest version of Webpack 4 (v4.46.0) has a High severity vulnerability in its tree which goes like so:
https://github.com/webpack/webpack/blob/v4.46.0/package.json#L28
https://github.com/webpack-contrib/terser-webpack-plugin/blob/v1.4.3/package.json#L40
https://github.com/npm/cacache/blob/v12.0.4/package.json#L74

The vulnerable package in question is ssri, and the vulnerability is at http://cve.mitre.org/cgi-bin/cvename.cgi?name=2021-27290

The latest version of Webpack (v5.28.0) contains the fixed version of ssri in its dependency tree.

### Steps to reproduce
`yarn why ssri`

### Please specify which version of Storybook and optionally any affected addons that you're running
- "@storybook/addon-a11y": "^6.1.21",
- "@storybook/addon-actions": "^6.1.21",
- "@storybook/addon-controls": "^6.1.21",
- "@storybook/addon-essentials": "^6.1.21",
- "@storybook/addon-links": "^6.1.21",
- "@storybook/addon-viewport": "^6.1.21",
- "@storybook/react": "^6.1.21",

### Affected platforms 

latest version (6.1.21)

**Comment by stof** [comment]
ssri has backported the patch into a 6.0.2 release. So this is now solved (run `yarn upgrade` to get the new ssri release)
