### ISSUE TITLE
[6.2.0-rc] Breaks HMR for vue with imported modules

### ISSUE THREAD

**Issue by thomasaull** [storybookjs/storybook#14352]
**Describe the bug**
Using storybook vue and the latest `6.2.0-rc10`. Importing and using a function in a component works on the initial load after starting storybook. However, on changing something in the imported file, storybook breaks with the following error:
`TypeError: options is undefined` (see screenshot below)

**To Reproduce**

1. Clone repository: https://github.com/thomasaull/storybook-hmr-bug
1. `npm run storybook`
1. Visit button story
1. Go to `stories/test.js` and uncomment the last line

**Expected behavior**
HMR should work for imported modules

**Screenshots**
![image](https://user-images.githubusercontent.com/227756/112649871-22a71a00-8e4b-11eb-87c7-b564360535fb.png)

**Code snippets**
Repository: https://github.com/thomasaull/storybook-hmr-bug
Commit which adds the breaking example: https://github.com/thomasaull/storybook-hmr-bug/commit/8bd8f5a134601ec4aedc7cc5e06c049d3cdd90bc

**System**

```
Environment Info:

  System:
    OS: Linux 5.4 elementary OS 5.1.7 Hera
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
    npm: 6.14.11 - ~/.nvm/versions/node/v14.16.0/bin/npm
  Browsers:
    Chrome: 89.0.4389.90
    Firefox: 85.0.1
  npmPackages:
    @storybook/addon-actions: ^6.2.0-rc.10 => 6.2.0-rc.10 
    @storybook/addon-essentials: ^6.2.0-rc.10 => 6.2.0-rc.10 
    @storybook/addon-links: ^6.2.0-rc.10 => 6.2.0-rc.10 
    @storybook/vue: ^6.2.0-rc.10 => 6.2.0-rc.10 
```

**Additional context**

* Does not occur with a `vue-cli` default setup
* Does not occur with storybook `6.1.x`

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1199622255231368/1200120750457358) by [Unito](https://www.unito.io/learn-more)

**Comment by thomasaull** [comment]
I did some more digging and it seems like, this issue does not happen, when I additionally `require` the module:
```
require('./test')
import { testFunction } from './test'
```
even though there is no default export in `test.js` it looks like it's changing something in the behaviour how everything is loaded.

**Comment by shilman** [comment]
Interesting finding. I'm checking out your repro now.

**Comment by shilman** [comment]
I'm not sure this is a bug, but just "proper" HMR.

What I'm seeing in the repro:
- I load up the Storybook
- I edit a story => observe an HMR request in the network tab (`<hash>.hot_update.js`)
- I edit the button component => observe an HMR request
- I edit the test => observe an HMR request

Like you, I didn't observe the `console.log` per your test instructions. So I:
- Added `console.log('mount')` to the mount function
- Edited the Button component:

```
<template>
  <button type="button" :class="classes" @click="onClick" :style="style">TEST {{ label }}</button>
</template>
```

As before I observe the HMR request. The button does not remount, however the TEST string is properly rendered in the UI.

This leads me to believe that the HMR is succeeding. However, it is a proper state-preserving HMR starting in 6.2.

WDYT?

**Comment by thomasaull** [comment]
I think I wasn't precise enough: The HMR itself is working fine, like I see the network request. However it seems like in this particular case the answer causes some problem throwing an error. Additionally after reloading the component does not show up anymore. I made a quick screencast illustrating the issue:

https://user-images.githubusercontent.com/227756/112725537-112c4380-8f19-11eb-8117-0ad4515c58da.mp4

Can you confirm doing those exact steps everything works for you? 

I tried a couple of things, removed all unecessary code from the repo, `rm -rf node_modules`, … but this seems to be consistent for me. It looks like the error message itself has changed, but the overall behaviour is the same.

I also looked at the `.js` responses from the HMR:
- First I changed some value in `testArray` (code on the left)
- Second I uncommented the line with `testArray.includes` (code on the right)

![image](https://user-images.githubusercontent.com/227756/112725758-15a52c00-8f1a-11eb-9e71-46debf64b360.png)

I might be the case, the error is happening when a new module is required (in this case the `es_array_includes` from `core-js`. But what is looking weird to me is the L29, where the method call of `testFunction()` changes to `Object(es_array_includes["testFunction"])();` — I don't know much about the transformation babel or core-js is doing though, so this could be perfectly fine.

Another test I just did was to add 
```js
import pickBy from 'lodash/pickBy`
```

to the top of `test.js`, this is resulting HMR responses before/after, again something weird is going on in L33 where `testFunction()` was before:
![image](https://user-images.githubusercontent.com/227756/112725975-3d48c400-8f1b-11eb-9b3f-35ddb8c7f675.png)

One more test, this is the HMR responses with the `lodash/pickBy` example, but I additionally `require` the file in `Button.vue`:
```js
require('./test')

import { testFunction } from './test'
testFunction()
```
![image](https://user-images.githubusercontent.com/227756/112726107-f3141280-8f1b-11eb-9fa7-cba50c5b4d9d.png)

What's noticeable here, is that the HRM response does not include the Vue component like in the other examples.

**Comment by thomasaull** [comment]
I think I found the setting which is causing the problems, setting `optimization.concatenateModules` in the webpack config to false resolves the error for me:
```js
// .storybook/main.js
webpackFinal: (config) => {
  config.optimization.concatenateModules = false
  return config
}
```
I can confirm that this setting was not set in storybook `6.0.28` and according to the webpack docs is disabled if not building for production: https://webpack.js.org/configuration/optimization/#optimizationconcatenatemodules. I also looks like it's not used in a default project I set up with `vue-cli`

**Comment by shilman** [comment]
@thomasaull great detective work. can confirm that `concatenateModules` was NOT set in 6.1 and is currently being set in 6.2. Will discuss with @ndelangen and report back.

**Comment by shilman** [comment]
Egads!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.0-rc.11 containing PR #14373 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by thomasaull** [comment]
Awesome :) 👍
