### ISSUE TITLE
storySort: support sorting a kind to the bottom of the list

### ISSUE THREAD

**Issue by randak** [storybookjs/storybook#14353]
**Is your feature request related to a problem? Please describe**
We recently upgraded to Storybook 6, and so far it has been a big improvement. The new `storySort` `order` option greatly simplifies our configuration, which is awesome. However, we currently have our component stories sorted like this:

- Guides
- [alphabetical list of all components in our library]
- Internal
- WIP

From what I can tell, in order to get this sorting with the new `order` config, we would need to manually list out every single component in the library.

**Describe the solution you'd like**
The simplest solution would be to support a `*` option in the list which means "anything (at this level) not explicitly listed here," which would make the configuration look like:
```
order: ['Guides', '*', 'Internal', 'WIP']
```
or for second-level ordering:
```
order: ['Components', ['Guides', '*', 'Internal', 'WIP'], 'Pages']
```

**Describe alternatives you've considered**
Another option would be to have some sort of signifier such as `!` in front of the options (to match anything _except_ the specified option). For example:
```
order: ['Guides', '!Internal', '!WIP']
```
but personally I find this syntax might be a bit confusing.

**Are you able to assist to bring the feature to reality?**
I am willing to help contribute this fix to the library.

**Additional context**
N/A

**Comment by shilman** [comment]
I love the `'*'` syntax. Any interest in creating a PR implementing it?

**Comment by randak** [comment]
Yes, I'd be happy to take a stab at this when I get a free moment.

**Comment by randak** [comment]
I've raised a PR for this feature at #14531.

**Comment by shilman** [comment]
Yay!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.3.0-alpha.3 containing PR #14531 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by sarahbethfederman** [comment]
This doesn't seem to work the way that I expected in nested stories. I assumed I would be able to use it like so to say that within Components category, pages named 'Overview' should be sorted first.
```
{ order: [
    'Components', ['*', ['Overview']]
  ] 
}
```
This seems to have no effect?

I was hoping to avoid having to write out every component (which should already be in alphabetical order) in order to sort the pages underneath each component
