### ISSUE TITLE
Using react-scripts 4.0.0 breaks storybook-build fails at 92% of build process on chunk asset optimization TerserPlugin

### ISSUE THREAD

**Issue by jessepinuelas** [storybookjs/storybook#14355]
**Describe the bug**
No longer able to build after updating to react-scripts 4.0.1 Previously I was able to simply run **npm run build-storybook**. Now when running the build command it fails. **It fails at 92% of build process on chunk asset optimization TerserPlugin**.

**To Reproduce**
Use a version of react-scripts below 4.0.0 for **example 3.4.4** running build-storybook will work
Install reacts-scripts 4.0.1 running build-storybook will fail

**Expected behavior**
Successfully builds storybook

**System**
OS: macOS 10.15.6
CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz

**Binaries:**
Node: 12.12.0 - ~/.nvm/versions/node/v12.12.0/bin/node
npm: 6.11.3 - ~/.nvm/versions/node/v12.12.0/bin/npm

**npmPackages:**
@storybook/addon-actions: 6.1.21 => 6.1.21
@storybook/addon-essentials: 6.1.21 => 6.1.21
@storybook/addon-links: 6.1.21 => 6.1.21
@storybook/addons: 6.1.21 => 6.1.21
@storybook/node-logger: 6.1.21 => 6.1.21
@storybook/preset-create-react-app: 3.1.7 => 3.1.7
@storybook/react: 6.1.21 => 6.1.21
@storybook/storybook-deployer: 2.8.7 => 2.8.7
@storybook/theming: 6.1.21 => 6.1.21

**Additional context**
`  _lastActiveSortFn: undefined,
ERR!       _sortFn: undefined,
ERR!       _cache: undefined,
ERR!       _cacheOrderIndependent: undefined
ERR!     },
ERR!     contextDependencies: SortableSet [Set] {
ERR!       '/Users/private-user/private-repo/src',
ERR!       _sortFn: undefined,
ERR!       _lastActiveSortFn: null,
ERR!       _cache: undefined,
ERR!       _cacheOrderIndependent: undefined
ERR!     },
ERR!     missingDependencies: SortableSet [Set] {
ERR!       _sortFn: undefined,
ERR!       _lastActiveSortFn: null,
ERR!       _cache: undefined,
ERR!       _cacheOrderIndependent: undefined
ERR!     }
ERR!   },
ERR!   hash: '82b3f88322128a30b9ea',
ERR!   startTime: 1616717641781,
ERR!   endTime: 1616717683706
ERR! }
`

**Comment by Nautman** [comment]
Did you solve this?

**Comment by jw-miaem** [comment]
not related to CRA but found after upgrading to 6.3.2 terser was breaking CI pipeline ([see here](https://github.com/storybookjs/storybook/issues/6408) setting minimize to false solved it for now

**Comment by macrozone** [comment]
this actually still happens with storybook 6.4.22
