### ISSUE TITLE
[6.2.0-rc] inferActionsFromArgTypesRegex was not supported :( !

### ISSUE THREAD

**Issue by darkowic** [storybookjs/storybook#14350]
**Describe the bug**
After upgrade from 6.1.x to newest 6.2.0-rc.10 version the warning in console appears:

```
inferActionsFromArgTypesRegex was not supported :( !
addActionsFromArgTypes was not supported :( !
```

I found in the source that the log is from `lib/builder-webpack4/src/preview/virtualModuleEntry.template.js`

**To Reproduce**
Not sure how to reproduce it. It appeared after the upgrade.

**Expected behavior**
No warning or docs on how to resolve the warning.

**System**

```
Environment Info:

  System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 14.14.0 - ~/.nvm/versions/node/v14.14.0/bin/node
    Yarn: 1.19.1 - ~/.nvm/versions/node/v14.14.0/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.14.0/bin/npm
  Browsers:
    Chrome: 89.0.4389.90
    Firefox: 85.0
    Safari: 14.0.3
```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1199622255231368/1200117309041037) by [Unito](https://www.unito.io/learn-more)

**Comment by shilman** [comment]
w00t!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.0-rc.11 containing PR #14372 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by darkowic** [comment]
Looks like not everything has been published correctly @shilman :
```
Couldn't find any versions for "@storybook/core" that matches "6.2.0-rc.11"
? Please choose a version of "@storybook/core" from this list: (Use arrow keys)
❯ 6.2.0-rc.10
  6.2.0-rc.9
  6.2.0-rc.8
  6.2.0-rc.7
  6.2.0-rc.6
  6.2.0-rc.5
  6.2.0-rc.4
  6.2.0-rc.3
  ```

**Comment by darkowic** [comment]
ok, looks like the cache issue. Checking: https://www.npmjs.com/package/@storybook/addon-actions
