### ISSUE TITLE
Can we please avoid those redundant Svelte's wrappers?

### ISSUE THREAD

**Issue by frederikhors** [storybookjs/storybook#14366]
_Thanks for your amazing, delicious work on Storybook!!!_

**Is your feature request related to a problem? Please describe**
I'm trying Storybook for the first time and with Svelte.

Using [kitchen-sink example here](https://github.com/storybookjs/storybook/blob/v6.2.0-rc.10/examples/svelte-kitchen-sink/src/stories/button.stories.js) I find it very inconvenient to create "wrappers" (such as `ButtonView.svelte`) because it becomes a tedious repetition of the component itself.

**Example:**

A button has `primary` and `size` (and many other) props and I need to put them both in `ButtonView.svelte` and the real `Button.svelte` component to use it in Storybook.

**Why this?** Could it be because it is complicated to inject slots?

Maybe I'm wrong in using it like this?

**Describe the solution you'd like**
I would like to "directly" use `Button.svelte` in my `button.stories.js` without `ButtonView.svelte` wrapper.

Maybe we can use an object like this:

```js
import DefaultSlot from "./DefaultSlot.svelte"
import FirstSlot from "./FirstSlot.svelte"
{
  slots: {
    default: { component: DefaultSlot }
    first: { component: FirstSlot }
  }
}
```

What do you think, Svelte guys? :smile:

**Comment by j3rem1e** [comment]
Check this plugin: https://www.npmjs.com/package/@storybook/addon-svelte-csf

It allows to write stories directly in svelte syntax.

**Comment by frederikhors** [comment]
@j3rem1e thank you! Interesting! I'm studying...

@shilman, can I ask you to not close this issue until we found a comfortable way to write Svelte stories?

**Comment by shilman** [comment]
@frederikhors sure thing. i'll let you close it when it's answered to your satisfaction

**Comment by frederikhors** [comment]
@j3rem1e, @shilman it works amazing! Thanks!

Is there more extensive documentation?
