### ISSUE TITLE
Improve CSF Docs Description Multiline

### ISSUE THREAD

**Issue by fcisio** [storybookjs/storybook#14365]
**Is your feature request related to a problem? Please describe**

Hi 👋
Currently, the descriptions in the docs parameters only work with single-line strings.

It would be nice to take `array` along with `string` to allow for a more complete `MD` experience.

**Currently**

```js
export const WithStoryDescription = Template.bind({});
WithStoryDescription.parameters = {
  docs: {
    description: {
      story: 'some story **markdown**',
    },
  },
};
```

**Describe the solution you'd like**

The array would be parsed under the hood and each string in the array would then be on a new line.

```js
description: {
  story: [
    'Ut enim ad `minim veniam`, quis nostrud exercitation',
    'nisi ut [aliquip ex](google.com) ea commodo consequat',
    'velit esse cillum dolore eu _fugiat **nulla pariatur**_',
    '> Lorem ipsum dolor sit amet, consectetur **adipiscing** elit',
    //
  ],
},
```

**Here is a working function that I created real quick**

```js
const types = (string) => ({
  heading: string,
  newline: `${string}<br>`,
  blockquote: `<blockquote>${string.replace('>', '')}</blockquote>`,
})

const csfMDX = (array) => {
  const mapped = array.map((str) => {
    let type = 'newline'
    if (str.startsWith('#')) type = 'heading'
    if (str.startsWith('>')) type = 'blockquote'

    return types(str)[type]
  })
  return mapped.join('\n')
}
```

**Describe alternatives you've considered**

Using template literals could also work, but we wouldn't be able to use backticks in MD.

**Are you able to assist to bring the feature to reality?**
Yes

**Comment by shilman** [comment]
Have you considered using template literals? 

```js
export const WithStoryDescription = Template.bind({});
WithStoryDescription.parameters = {
  docs: {
    description: {
      story: `
this is some

multiline

text
`.trim(),
    },
  },
};
```

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#multi-line_strings

**Comment by fcisio** [comment]
I did consider template literals, as it would offer a great MD experience.

But there are two main cons:
- Remove the possibility to use backticks for MD purposes
- Literals syntax would still require some parsing to insert `<br/>` into the string, or Storybook will output a single line.

> Backticks could be preserved with literals syntax if we have a new character that would be replaced. 
Example:  `something` becomes {something}
---
My suggested solution seems to be working pretty well for me so far.

**Comment by yairEO** [comment]
@shilman - it's impossible to write meaningful markdown as per your suggestion because markdown often contains code examples like so:

```js
MyStory.parameters = {
    docs: {
        description: {
            story: `
                # Usage example:
                ```js
		        <MyComp {...props}/>
		        ```
            `,
        },
    },
}
```

The use of code and component reference within `story` description are breaking the build

**Comment by ndelangen** [comment]
We will not implement this.
