### ISSUE TITLE
[6.2.0-rc] Various errors occur when live changing import statements of Svelte component

### ISSUE THREAD

**Issue by jeongtae** [storybookjs/storybook#14364]
**Describe the bug**

Using Storybook `6.2.0-rc10` and Svelte.
If I change import statements on Storybook is running,  The canvas breaks, and sometimes an error occurs.

**To Reproduce**

1. Clone repository: https://github.com/jeongtae/storybook-svelte-import-bug
2. Run Storybook
```bash
npm run storybook
```
3. Open `src/stories/Test.svelte` and uncomment the commented lines below `/* TEST1 */`
4. See the phenomenon that the component does not render in the canvas.

**To Reproduce another problem**

1. Exit Storybook
2. Maintain the uncommented state of the lines below `/* TEST1 */`
3. Run Storybook
4. Comment the lines below `/* TEST1 */`
5. See error `TypeError: switch_value is not a constructor`

**Expected behavior**

The expected behavior is a log message appears at the browser's console.

**System**
```
Environment Info:

  System:
    OS: macOS 11.2.3
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 15.11.0 - /opt/homebrew/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 7.6.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 89.0.4389.90
    Safari: 14.0.3
  npmPackages:
    @storybook/addon-actions: ^6.2.0-rc.10 => 6.2.0-rc.10 
    @storybook/addon-essentials: ^6.2.0-rc.10 => 6.2.0-rc.10 
    @storybook/addon-links: ^6.2.0-rc.10 => 6.2.0-rc.10 
    @storybook/svelte: ^6.2.0-rc.10 => 6.2.0-rc.10
```

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid.

Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
