### ISSUE TITLE
Bug in destructuring of values in 'custom tooltip' storybook under 'Pie'

### ISSUE THREAD

**Issue by gEt-rIgHt-jR** [storybookjs/storybook#14368]
**Describe the bug**
There is a bug in destructuring of `id`, `value`, and `color` values in [custom tooltip](https://nivo.rocks/storybook/?path=/story/pie--custom-tooltip) storybook under Pie. Because of this, if you hover over the pie chart, you don't see the id and its value. It shows `:` (no `id` and `value`) instead of `css:298` for example and the text color is black instead of the color of the section.

**To Reproduce**

1. Go to  [custom tooltip](https://nivo.rocks/storybook/?path=/story/pie--custom-tooltip) storybook under Pie
2. Hover on the Pie chart
3. Observe that the `id` and `value` are missing and the text color is black

**Expected behavior**
`id` and `value` should be shown after hovering over the Pie chart sections. Also, the color shouldn't be black, it should be the one that we send in the `tooltip` prop.

**Screenshots**
The mouse is missing in the screenshot, but I'm hovering over the `css` section. A black colon can be seen in the `css` section:

![image](https://user-images.githubusercontent.com/19431338/112766635-32338800-9030-11eb-9d59-75cc9b904897.png)

**Code snippets**
Actual code: `tooltip={({ id, value, color }) => (`
Expected: `tooltip={({ datum: { id, value, color } }) => (`

**Comment by ndelangen** [comment]
This seems to be a bug report for a component outside of storybook's codebase.
