### ISSUE TITLE
Addon-controls not behaving correctly in docs view

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#14374]
Hey peeps this contribution is super awesome! I wanted to show something I noticed while testing controls on docs page.
[Here's the link to the story](https://next--storybookjs.netlify.app/angular-cli/?path=/docs/basics-component-with-ng-content-button-with-different-contents--always-define-template-or-component)

I hope you don't mind the QA:

1 - the input is not as responsive as it could be, and text is not correctly aligned
2 - when playing with the picker, there's a flicker
3 - the color swatch feature is registering invalid colors as you type them (and says "black" for some reason)

Here's a gif showing these points:
![2021-03-24 at 16 33 24 - Lime Giraffe](https://user-images.githubusercontent.com/1671563/112338401-0ecead00-8cbf-11eb-9ce6-7559d077aafa.gif)

Edit: if you type an invalid color, the swatch allows to play with the hue, resulting in NaN:
![image](https://user-images.githubusercontent.com/1671563/112338752-56553900-8cbf-11eb-82fc-62c77b7270a7.png)

cc ghengeveld EvHaus

_Originally posted by yannbf in https://github.com/storybookjs/storybook/issues/14249#issuecomment-805929284_

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1199622255231368/1200123738036844) by [Unito](https://www.unito.io/learn-more)

**Comment by EvHaus** [comment]
@ghengeveld if you don't get to it this week, I can jump on this by Friday

**Comment by yannbf** [comment]
I also noticed something else related to controls, although not related to the color picker. This might be quite simple so maybe there's no need to add an extra issue, however if you feel there is, I can create the issue!

For numeric enums, controls is identifying as objects and presenting the "RAW" toggle:
![image](https://user-images.githubusercontent.com/1671563/112888892-349bed80-90d5-11eb-997e-c0aefa60a877.png)

Clicking on it does nothing. That can be seen [in next angular cli examples](https://next--storybookjs.netlify.app/angular-cli/?path=/docs/basics-component-with-enum-types--basic)

**Comment by shilman** [comment]
Crikey!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.0-rc.12 containing PR #14382 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by ghengeveld** [comment]
@yannbf I addressed your other issues here: https://github.com/storybookjs/storybook/pull/14392

**Comment by shilman** [comment]
Yo-ho-ho!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.0-rc.13 containing PR #14392 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```
