### ISSUE TITLE
[v6.2.0-rc.11] TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by darkowic** [storybookjs/storybook#14377]
**Describe the bug**
After upgrade from v6.2.0-rc.10 to v6.2.0-rc.11 I got the following error in preview (displayed in UI):

```
Cannot read property 'name' of undefined
TypeError: Cannot read property 'name' of undefined
    at createDefaultValue (http://localhost:6007/vendors~main.iframe.bundle.js:16438:33)
    at createBasicPropDef (http://localhost:6007/vendors~main.iframe.bundle.js:16464:19)
    at javaScriptFactory (http://localhost:6007/vendors~main.iframe.bundle.js:16501:17)
    at extractProp (http://localhost:6007/vendors~main.iframe.bundle.js:16642:19)
    at http://localhost:6007/vendors~main.iframe.bundle.js:16623:33
    at Array.map (<anonymous>)
    at extractComponentSectionObject (http://localhost:6007/vendors~main.iframe.bundle.js:16621:26)
    at extractComponentProps (http://localhost:6007/vendors~main.iframe.bundle.js:16634:87)
    at getPropDefs (http://localhost:6007/vendors~main.iframe.bundle.js:13848:106)
    at extractProps (http://localhost:6007/vendors~main.iframe.bundle.js:13870:11)
```

First of all - **this error is useless. It doesn't point to any place where this occurs.** I spend a lot of time trying to find a place where it happened (we have ~30 components)...

**To Reproduce**

I found it is because of this weird combination of propTypes and defaultProps - happens if default prop is defined but propType is missing

Component: 

```tsx
import React from 'react';
import PropTypes from 'prop-types';

export const DATA_TYPE_STRING = 'string';

// eslint-disable-next-line react/prefer-stateless-function
export class TestComponent extends React.Component {
    static propTypes = {
        // whatever here actually
        test: PropTypes.number,
        // dataType: PropTypes.string,
    };

    static defaultProps = {
        test: [],
        dataType: DATA_TYPE_STRING,
    };

    render() {
        return <div>test</div>;
    }
}
```

Story:

```tsx
import React from 'react';
import PropTypes from 'prop-types';
import { Story, Meta } from '@storybook/react';

import { TestComponent } from './TestComponent';

type TestComponentProps = PropTypes.InferProps<typeof TestComponent.propTypes>;

type TestComponentStory = Story<TestComponentProps>;

export default {
    component: TestComponent,
    title: 'Components/TestComponent',
} as Meta<TestComponentProps>;

const Template: TestComponentStory = args => <TestComponent {...args} />;

export const Basic: TestComponentStory = Template.bind({});
```

In our original component we have:

```tsx
        /**
         * The format of the value
         */
        dataType: dataTypeShape,
```

and the `dataTypeShape` is defined outside so this may be the issue too.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1199622255231368/1200128122964622) by [Unito](https://www.unito.io/learn-more)

**Comment by dptoot** [comment]
Can confirm this is a major issue for us.  I had the reverse issue.  With propTypes defined but defaults missing .  This would seem like a valid syntax pattern as our defaults were defined via destructuring within our functional component.   For documentation I would see a defaultProps would be better but IMO this shouldn't break all the stories  in storybook if missing

**Comment by dptoot** [comment]
After some further investigation it does look like the issue also occurs while there is a default defined in the destructuring of props but is missing from the defined propTypes of the component.

The following looks to throw an error as it is trying to assign the default for `bar` to an unassigned propType

`const MyComponent= ({
    foo= true,
    bar = false,
}) => <div> Hi</div>

MyComponent.propTypes = {
    foo: PropTypes.bool,
}
`

**Comment by shilman** [comment]
Son of a gun!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.0-rc.12 containing PR #14387 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by tmeasday** [comment]
Thanks for the useful reproduction @darkowic! Hopefully the above fix worked ☝️

**Comment by darkowic** [comment]
Thanks! @tmeasday  @shilman Do you have any follow-up to improve the error messages? A better error message which points to the story where the error happened would be really helpful.

**Comment by tmeasday** [comment]
That sounds like a good idea, WDYT @shilman ?

**Comment by shilman** [comment]
Sure, PRs welcome! 🙏

**Comment by darkowic** [comment]
Created another issue to not forgot about it...
