### ISSUE TITLE
jsx.onBeforeRender deprecated in favor of transformSource but there are differences

### ISSUE THREAD

**Issue by CosticaPuntaru** [storybookjs/storybook#14389]
**Describe the bug**
it appears that `transformSource` is called in different life cycle  steps then `onBeforeRender`, when using story decorators, it breaks the `transformSource`

**To Reproduce**
i've added both functions to a story
```
export default {
 .....
parameters: {
    jsx: {
            transformSource: (src) => {
                console.log('transformSource', src);
                return src;
            },
            onBeforeRender: (domString: StoryContext) => {
                console.log('onBeforeRender', domString)
                return domString
            }
        }
},
    decorators: [jsxDecorator, SmallContainerDecorator],
}
```

**Expected behavior**
Expected the same number of logs calls from both function, but my issue is that the source is incorect

**Screenshots**
result with decorators
![image](https://user-images.githubusercontent.com/6418405/112951080-a7dc4880-9143-11eb-84bd-190d2e123dcd.png)

results without story decorators (i was expecting similar results regardless of decorators):

![image](https://user-images.githubusercontent.com/6418405/112952102-cc84f000-9144-11eb-874f-d15fed535aa2.png)

**Code snippets**
```
export default {
 .....
parameters: {
    jsx: {
            transformSource: (src) => {
                console.log('transformSource', src);
                return src;
            },
            onBeforeRender: (domString: StoryContext) => {
                console.log('onBeforeRender', domString)
                return domString
            }
        }
},
    decorators: [jsxDecorator, SmallContainerDecorator],
}
```

**System**
 System:
    OS: macOS 11.2.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 12.21.0 - ~/.nvm/versions/node/v12.21.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v12.21.0/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v12.21.0/bin/npm
  Browsers:
    Chrome: 89.0.4389.90
    Firefox: 87.0
    Safari: 14.0.3
  npmPackages:
    @storybook/addon-docs: 6.1.21 => 6.1.21
    @storybook/addon-essentials: 6.1.21 => 6.1.21
    @storybook/react: 6.1.21 => 6.1.21

**Additional context**
i use a decorator to warp the story in a container for sizing, if i remove the decorators, the code works,
by using jsxDecorator i was actually expecting to see the source code without the wrapping SmallContainerDecorator output, but for my case this is not a big issue

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
