### ISSUE TITLE
addon-viewport: cycling through viewports with keyboard shortcuts

### ISSUE THREAD

**Issue by kaelig** [storybookjs/storybook#14401]
**Is your feature request related to a problem? Please describe**
I often switch between viewports and it requires a lot of clicking around.

**Describe the solution you'd like**
Cycling through the viewports like so would be a nice time saver:

- next viewport: <kbd>V</kbd>
- previous viewport: <kbd>shift</kbd> + <kbd>V</kbd>

**Describe alternatives you've considered**

- A custom addon
- A Chrome extension that adds this functionality

**Are you able to assist to bring the feature to reality?**
Happy to help reviewing a PR!

Related: https://github.com/storybookjs/storybook/issues/9073

**Comment by Dschungelabenteuer** [comment]
Okay, I'm jumping in! I'd like to give it a try @shilman, can't assure I'll be doing good though, this will likely require some feedback ☺

**Comment by jeremyzilar** [comment]
This would be very helpful 🎉

**Comment by shilman** [comment]
Whoopee!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.3.0-alpha.15 containing PR #14658 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
