### ISSUE TITLE
vue2: v-model , @on-change and sibling template disappeared in "show source" panel

### ISSUE THREAD

**Issue by lijing666** [storybookjs/storybook#14404]
**Describe the bug**
In vue2 , when template contains two way binding "v-model" or event listener like "@on-change" with "v-bind=$props", in docs "show source" panel, they get lost;  Some siblings in template also get lost too.

**Expected behavior**
Should keep them always.

**Code snippets**

Story fragment:

```
const tagTemplate=`<Tag v-for="item in actor||[]" :key="item.type+'-'+item.value">
{{actorDetails[item.type]&&actorDetails[item.type][item.value]&&actorDetails[item.type][item.value].name}}
</Tag>`
const coreTemplate=`<f-actor-select v-model="actor" v-bind="$props" @on-change="onChange"></f-actor-select>`;

const template=`<div class="flex-center">
${tagTemplate}
${coreTemplate}
</div>`
const Template = (args, { argTypes }) => {
  let {propTypes}=refinedArgTypes(argTypes);
  return ({
    props: propTypes,
    data(){
      return {
        actor:null,
        actorDetails:{}
      }
    },
    template: template,
    methods:{
      onChange:function(value,details){
        this.actorDetails=details;
      }
    }
  });
}

export const Primary = Template.bind({});
Primary.args={
  multiple:true
}
```

Produced show source:

```
<template>
  <div class="flex-center">
    <f-actor-select
      :modalWidth="650"
      :modalHeight="null"
      :height="370"
      :placeholder="null"
      :limit="50"
      :queryMethods="null"
      labelKey="name"
      valueKey="id"
      orgLabelKey="name"
      orgValueKey="id"
      :disabledValue="null"
      :readonlyValue="null"
      multiple
      :renderFormat="null"
      :disabled="false"
    />
  </div>
</template>
```

We can found:
"v-model" disappeared, "@on-change" disappeared, siblings "<Tag ...." disappeared.

**System**

Environment Info:

  System:
    OS: OS X El Capitan 10.11.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
  Binaries:
    Node: 12.14.0 - ~/.nvm/versions/node/v12.14.0/bin/node
    Yarn: 1.10.0 - /usr/local/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.14.0/bin/npm
  Browsers:
    Chrome: 89.0.4389.90
    Safari: 11.1.2
  npmPackages:
    @storybook/addon-actions: ^6.2.0 => 6.2.0 
    @storybook/addon-essentials: ^6.2.0 => 6.2.0 
    @storybook/addon-links: ^6.2.0 => 6.2.0 
    @storybook/vue: ^6.2.0 => 6.2.0

**Comment by shilman** [comment]
@pocka is this something you've encountered before?

**Comment by pocka** [comment]
Yes and no 🙃 

@lijing666 
The Dynamic Source Rendering for Vue.js does not display both directives (example: `v-model`) and events (example: `@change`) by technical limitation. Directives are lost in VNode so we can't even know the VNode has directives or not. Events are, although I'm not sure it's inspectable via VNode, not supported mostly because we need to serialize the function body in order to show the source code. Maybe we can add support for directives if we got a new implementation in the feature, but probably not for events.

If you want to show directives/events/component options, I recommend you to set [`docs.source.type` parameter to `code`](https://storybook.js.org/docs/react/writing-docs/doc-blocks#docspage-1) so that the Docs Addon displays your story source code as-is.

```js
export default {
  title: "...",
  parameters: {
    docs: {
      source: { type: "code" }
    }
  }
}
```

> Some siblings in template also get lost too.

I've never seen this. Can you provide a simple repro?

**Comment by lijing666** [comment]
> Yes and no 🙃
> 
> @lijing666
> The Dynamic Source Rendering for Vue.js does not display both directives (example: `v-model`) and events (example: `@change`) by technical limitation. Directives are lost in VNode so we can't even know the VNode has directives or not. Events are, although I'm not sure it's inspectable via VNode, not supported mostly because we need to serialize the function body in order to show the source code. Maybe we can add support for directives if we got a new implementation in the feature, but probably not for events.
> 
> If you want to show directives/events/component options, I recommend you to set [`docs.source.type` parameter to `code`](https://storybook.js.org/docs/react/writing-docs/doc-blocks#docspage-1) so that the Docs Addon displays your story source code as-is.
> 
> ```js
> export default {
>   title: "...",
>   parameters: {
>     docs: {
>       source: { type: "code" }
>     }
>   }
> }
> ```
> 
> > Some siblings in template also get lost too.
> 
> I've never seen this. Can you provide a simple repro?

Thanks for your reply! This is the repo [https://github.com/lijing666/storybook-demo](https://github.com/lijing666/storybook-demo) can show the siblings get lost! As my opinion, the reason is `v-for="(items,index) in itemsArray||[]"` cause that bug, first time "itemsArray" is null cause "com-b" renders nothing

**Comment by pocka** [comment]
> Thanks for your reply! This is the repo https://github.com/lijing666/storybook-demo can show the siblings get lost! As my opinion, the reason is `v-for="(items,index) in itemsArray||[]"` cause that bug, first time "itemsArray" is null cause "com-b" renders nothing

Yes, the dynamic source preview renders a resolved component tree: every directive, including `v-if` and `v-for`, are applied at the time already.

Given the below story,

```js
const Template = () => ({
  data() {
    return { visible: false }
  },
  methods: {
    toggle() { this.visible = !this.visible }
  },
  template: `
    <div>
      <button @click="toggle">Toggle</button>
      <p v-if="visible">Hello</p>
    </div>
  `
})
```

The expected result is:

```vue
<template>
  <div>
    <button>Toggle</button>
  </div>
</template>
```

and `<p>Hello</p>` appears only while the `visible` is `true`.
This is same for `v-for` and other directives.
