### ISSUE TITLE
Global args inheritance no longer working

### ISSUE THREAD

**Issue by Ben-Adlington** [storybookjs/storybook#14411]
**Describe the bug**
I've run into issues with global parameter inheritance not working after updating my project to the latest version of storybook.

**To Reproduce**

1. Create a blank Create React App project `npx create-react-app my-app`
2. Install the latest version of storybook `npx sb init`
3. Add in some global arguments into preview.js as per the documentation here https://storybook.js.org/docs/react/writing-stories/parameters#global-parameters

as an example I've below added to my empty project preview.js:
```
export const parameters = {
  actions: { argTypesRegex: '^on[A-Z].*' },
  controls: {
    matchers: {
      color: /(background|color)$/i,
      date: /Date$/,
    },
  },
  args: {
    test: '12345',
  },
};
```
4. I then added a `console.log(props)` to a button component
5. Run storybook and check the console for the component with the `console.log`

**Expected behavior**
I expect the component to have the global props passed down into the story props, meaning the console.log should have the prop `test` having a value of `12345`

**Screenshots**
![image](https://user-images.githubusercontent.com/23053105/113147040-4b068e00-9228-11eb-84b9-c1216ecf5d96.png)

**Snippets**
For reference, this is the button story
```
import React from 'react';

import { Button } from './Button';

export default {
  title: 'Example/Button',
  component: Button,
  argTypes: {
    backgroundColor: { control: 'color' },
  },
};

const Template = (args) => <Button {...args} />;

export const Primary = Template.bind({});
Primary.args = {
  primary: true,
  label: 'Button',
};
```

**System**
``` 
System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
  Binaries:
    Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD      
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.423.0), Chromium (89.0.774.63)
  npmPackages:
    @storybook/addon-actions: ^6.2.1 => 6.2.1
    @storybook/addon-essentials: ^6.2.1 => 6.2.1
    @storybook/addon-links: ^6.2.1 => 6.2.1
    @storybook/node-logger: ^6.2.1 => 6.2.1
    @storybook/preset-create-react-app: ^3.1.7 => 3.1.7
    @storybook/react: ^6.2.1 => 6.2.1
```

**Additional context**
Unless I'm missing an extra step somewhere, I believe this functionality was working in a previous version of storybook as a couple of my projects have a lot of erroring stories because of this.

Hopefully I can have some insight on this?

Cheers

**Comment by ndelangen** [comment]
You've nested your global args inside of global parameters, that's not correct:
https://storybook.js.org/docs/react/writing-stories/args#global-args

```ts
export const parameters = {
  actions: { argTypesRegex: '^on[A-Z].*' },
  controls: {
    matchers: {
      color: /(background|color)$/i,
      date: /Date$/,
    },
  },
}

export const  args = {
  test: '12345',
};
```
