### ISSUE TITLE
Configured `controls.sort` mode is ignored by props table on "Docs" tab

### ISSUE THREAD

**Issue by alexjamesmacpherson** [storybookjs/storybook#14414]
**Describe the bug**
The configured `controls.sort` mode (introduced in Storybook 6.2.x) is not adhered to by the props table on the "Docs" tab. Sort mode has been [configured per the docs](https://storybook.js.org/docs/react/essentials/controls#sorting-controls), with the sort mode defined in `.storybook/preview.js` (as below) to globally set controls sort mode:

```
export const parameters = {
  controls: {
    expanded: true,
    hideNoControlsWarning: true,
    sort: 'requiredFirst',
  },
};
```

Note that setting the sort mode directly within the `*.stories.*` file exhibits the same issue.

Also note I've observed this using TypeScript with React + Storybook; I'm not sure if the same behaviour is exhibited for non-TS component libraries as I haven't tested, but I can't imagine this being a problem specific to TypeScript.

**To Reproduce**
[Reproduction repository](https://github.com/alexjamesmacpherson/storybook-controls-sort-repro)

1. Requires a React Storybook component library with the Docs addon.
1. Create a component or type interface with a mix of required and optional props which are not alphabetically (or otherwise) sorted.
1. Set a `controls.sort` mode either in your stories file or globally using `preview.js`.
1. Observe that the "Canvas" tab presents all props (args/controls) sorted correctly by the given sort mode.
1. Observe that the "Docs" tab presents all props sorted as they are defined in the component, ignoring the specified sort mode.

**Expected behavior**
Args/controls in the props table on the "Docs" tab should adhere to the configured `controls.sort` mode.

**Screenshots**
Controls from "Canvas" tab (correctly sorted using `requiredFirst` sort mode):

![Screenshot 2021-03-31 at 16 30 57](https://user-images.githubusercontent.com/16902219/113170873-df7beb00-923e-11eb-81fb-c50b89991e28.png)

Same controls from "Docs" tab (incorrectly sorted):

![Screenshot 2021-03-31 at 16 31 06](https://user-images.githubusercontent.com/16902219/113170848-dab73700-923e-11eb-975d-d7b9e7c239a6.png)
![Screenshot 2021-03-31 at 16 31 11](https://user-images.githubusercontent.com/16902219/113170865-dd199100-923e-11eb-9ed4-12de4b80e563.png)

**Code snippets**
Please refer to the [reproduction repository](https://github.com/alexjamesmacpherson/storybook-controls-sort-repro) I've provided. It's based on a component library I work with but heavily stripped back to demonstrate the issue clearly.

**System**

```
storybook-controls-sort-repro % npx sb@next info

Environment Info:

  System:
    OS: macOS 11.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 14.5.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
  Browsers:
    Chrome: 89.0.4389.90
    Edge: 89.0.774.63
    Firefox: 86.0
    Safari: 14.0.2
  npmPackages:
    @storybook/addon-a11y: 6.2.1 => 6.2.1
    @storybook/addon-essentials: 6.2.1 => 6.2.1
    @storybook/addon-links: 6.2.1 => 6.2.1
    @storybook/addons: 6.2.1 => 6.2.1
    @storybook/react: 6.2.1 => 6.2.1
    @storybook/theming: 6.2.1 => 6.2.1
```

Let me know if this is expected behaviour, or if there's anything further I can provide to help progress this issue!

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1199622255231368/1200139843121033) by [Unito](https://www.unito.io/learn-more)

**Comment by shilman** [comment]
Zoinks!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.2 containing PR #14422 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by ananuness** [comment]
i'm using this same feature in SB `7.2.1` and is not working 🥲

**Comment by SanderCokart** [comment]
7.4 not working

**Comment by bragaru-i** [comment]
8.0.0 - same issue.
sorting in Docs is not apllied

**Comment by milanbargiel** [comment]
Also, it is not working in 8.6.0-alpha.1.
