### ISSUE TITLE
ModuleNotFoundError @storybook/addon-docs NPM 7

### ISSUE THREAD

**Issue by josias-r** [storybookjs/storybook#14429]
**Describe the bug**
`Can't resolve '@storybook/addon-docs/blocks' in '/Users/me/myproject/path/to/stories'`.
I can't import addon-docs from my stories, after I upgraded to storybook 6.2.1 (from 6.1.17). I have addon-essentials installed.

I suspect this has something to do with incompatibility issues with NPM 7 workspaces. I get this error in a subpackage from a worspace set-up.

A workaround is to install addon-docs explicitly instead of just addon-essentials. But afaik that's should not be the case, since not even `sb init` installs it explicitly.

**To Reproduce**
Install Storybook version 6.2.1 inside a subpackage of an NPM 7 workspaces and try importing something from addon-docs inside an MDX story.

**Screenshots**
<img width="1183" alt="Screenshot 2021-04-01 at 10 04 08" src="https://user-images.githubusercontent.com/11424820/113263255-d425cf80-92d1-11eb-8382-de8bd26ee4ec.png">

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
```
Environment Info:

  System:
    OS: macOS 11.2.3
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  Binaries:
    Node: 15.8.0 - ~/.nvm/versions/node/v15.8.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.15.4/bin/yarn
    npm: 7.6.3 - ~/.nvm/versions/node/v15.8.0/bin/npm
  Browsers:
    Chrome: 89.0.4389.114
    Edge: 89.0.774.63
    Firefox: 86.0
    Safari: 14.0.3
```

**Comment by joycemwang** [comment]
having this same problem

**Comment by hello-astar** [comment]
have you dealt with the problem?

**Comment by hello-astar** [comment]
have you solved the problem ?

**Comment by shilman** [comment]
Please add `@storybook/addon-docs` as a project dependency

**Comment by shilman** [comment]
The issue is that NPM7 has changed the semantics of how dependencies work compared to previous versions of NPM. 

NPM6:

```
[your package] -> addon-essentials -> addon-docs = Referencing `addon-docs` in your package is OK
```

NPM7:

```
[your package] -> addon-essentials -> addon-docs = Referencing `addon-docs` in your package may fail
[your package] -> addon-essentials + addon-docs = Referencing `addon-docs` in your package is OK
```

**Comment by josh-biddick** [comment]
@shilman Is there a proposed solution for NPM 8? I've pulled all storybook dependencies into a separate NPM project and listed `@storybook/addon-docs` as a dependencies:

```
    "@storybook/addon-actions": "^6.3.6",
    "@storybook/addon-docs": "^6.3.12",
    "@storybook/addon-essentials": "^6.3.6",
    "@storybook/addon-links": "^6.3.6",
    "@storybook/builder-webpack5": "^6.3.12",
    "@storybook/cli": "^6.3.6",
    "@storybook/components": "^6.3.0",
    "@storybook/core-events": "^6.3.0",
    "@storybook/manager-webpack5": "^6.3.12",
    "@storybook/react": "^6.3.6",
    "@storybook/theming": "^6.3.0",
```
However, NPM 8 installs this in the packages node_modules. i.e. `<project_root>/node_modules/@my_package/node_modules/@storybook/addon-docs` and Webpack can't find it.

On the other hand, if I install `@storybook/addon-docs` in my project root, it resolves and Webpack builds correctly.

**Comment by shilman** [comment]
@josh-biddick we'll need to address the package structure in a future release. any suggestions? we're still trying to catch up with NPM7 -- haven't even looked at NPM8 yet

**Comment by josh-biddick** [comment]
@shilman I'm not sure I have enough knowledge about the Node resolution strategy to comment but to reproduce I would potentially try to emulate a scenario where you have a separate package containing the Storybook dependencies and install that package as a dependency in your root project. Later, attempt to run `start-storybook` and you may start to see errors.

As for solving the issue, maybe the Node resolution strategy has changed significantly and there maybe someone here who has a deeper understanding as to why this problem occurs?

**Comment by lwpulsifer** [comment]
> @shilman Is there a proposed solution for NPM 8? I've pulled all storybook dependencies into a separate NPM project and listed `@storybook/addon-docs` as a dependencies:
> 
> ```
>     "@storybook/addon-actions": "^6.3.6",
>     "@storybook/addon-docs": "^6.3.12",
>     "@storybook/addon-essentials": "^6.3.6",
>     "@storybook/addon-links": "^6.3.6",
>     "@storybook/builder-webpack5": "^6.3.12",
>     "@storybook/cli": "^6.3.6",
>     "@storybook/components": "^6.3.0",
>     "@storybook/core-events": "^6.3.0",
>     "@storybook/manager-webpack5": "^6.3.12",
>     "@storybook/react": "^6.3.6",
>     "@storybook/theming": "^6.3.0",
> ```
> 
> However, NPM 8 installs this in the packages node_modules. i.e. `<project_root>/node_modules/@my_package/node_modules/@storybook/addon-docs` and Webpack can't find it.
> 
> On the other hand, if I install `@storybook/addon-docs` in my project root, it resolves and Webpack builds correctly.

@josh-biddick did you end up uncovering any potential solutions to this other than the workaround you mentioned here? I'm running into _exactly_ the same issue in a project of mine.

**Comment by josh-biddick** [comment]
@lwpulsifer No nothing yet.

**Comment by zenschematic** [comment]
> @shilman Is there a proposed solution for NPM 8? I've pulled all storybook dependencies into a separate NPM project and listed `@storybook/addon-docs` as a dependencies:
> 
> ```
>     "@storybook/addon-actions": "^6.3.6",
>     "@storybook/addon-docs": "^6.3.12",
>     "@storybook/addon-essentials": "^6.3.6",
>     "@storybook/addon-links": "^6.3.6",
>     "@storybook/builder-webpack5": "^6.3.12",
>     "@storybook/cli": "^6.3.6",
>     "@storybook/components": "^6.3.0",
>     "@storybook/core-events": "^6.3.0",
>     "@storybook/manager-webpack5": "^6.3.12",
>     "@storybook/react": "^6.3.6",
>     "@storybook/theming": "^6.3.0",
> ```
> 
> However, NPM 8 installs this in the packages node_modules. i.e. `<project_root>/node_modules/@my_package/node_modules/@storybook/addon-docs` and Webpack can't find it.
> 
> On the other hand, if I install `@storybook/addon-docs` in my project root, it resolves and Webpack builds correctly.

Was running into the same exact problem, this did the trick. Weird workaround though.

**Comment by cauediademi** [comment]
I fixed this exact same error by removing the following lines from storybook/addons.js:
import '@storybook/addon-actions/manager';
import '@storybook/addon-knobs/manager';
import '@storybook/addon-links/manager';

**Comment by gaurav5430** [comment]
> The issue is that NPM7 has changed the semantics of how dependencies work compared to previous versions of NPM.
> 
> NPM6:
> 
> ```
> [your package] -> addon-essentials -> addon-docs = Referencing `addon-docs` in your package is OK
> ```
> 
> NPM7:
> 
> ```
> [your package] -> addon-essentials -> addon-docs = Referencing `addon-docs` in your package may fail
> [your package] -> addon-essentials + addon-docs = Referencing `addon-docs` in your package is OK
> ```

Is this mentioned somewhere in npm 7 release notes somewhere, would want to understand this a little better 
@shilman

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
