### ISSUE TITLE
Environment variables in HTML files not working anymore

### ISSUE THREAD

**Issue by danielkoch** [storybookjs/storybook#14438]
**Describe the bug**
I upgraded from from 6.1.21 to 6.2.1 and it seems that Environment variables (https://storybook.js.org/docs/react/configure/environment-variables) not working anymore in HTML files. I used one before in preview-head.html

**To Reproduce**
Add environment variable into preview-head.html. Example: %BRAND%. Start Storybook `BRAND=value start-storybook`

**Expected behavior**
Environment variables should be replaced with given value.

**Screenshots**
<img width="854" alt="sb-environment-variable" src="https://user-images.githubusercontent.com/142055/113300048-d4d45b00-92fd-11eb-9ecf-4fc98f99359e.png">

**System**
```
Environment Info:
  System:
    OS: macOS 11.2.3
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  Binaries:
    Node: 14.16.0 - ~/.nvs/node/14.16.0/x64/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.14.11 - ~/.nvs/node/14.16.0/x64/bin/npm
  Browsers:
    Chrome: 89.0.4389.90
    Edge: 89.0.774.63
    Safari: 14.0.3
  npmPackages:
    @storybook/addons: 6.2.1 => 6.2.1 
    @storybook/react: 6.2.1 => 6.2.1 
    @storybook/theming: 6.2.1 => 6.2.1 
```

**Comment by shilman** [comment]
We think this is a bug in 6.1. We explicitly filter out environment variables that don't start with `STORYBOOK_` for security purposes. If you put the variable in a `.env` file, then you don't need to prefix it.

**Comment by danielkoch** [comment]
@shilman: Means the bug is that it worked till 6.1?
Using .env file is not really an option because I need to run the script multiple times with different environment values.

**Comment by shilman** [comment]
@danielkoch yes, I'm surprised it worked at all since the variable is not prefixed with `STORYBOOK_`
