### ISSUE TITLE
addon-controls: Requests multiplying with each change

### ISSUE THREAD

**Issue by boardfish** [storybookjs/storybook#14436]
**Describe the bug**
When I edit a control value, the number of requests made to do so doubles from the previous attempt:

**To Reproduce**

1. Set up a Rails app with Webpack.
2. Configure [`view_component_storybook`](https://github.com/jonspalmer/view_component_storybook) for it by following their Getting Started guide. In addition, configure CORS headers according to my comment [here](https://github.com/jonspalmer/view_component_storybook/pull/27#issuecomment-811810648), configure [asset hosts](https://github.com/jonspalmer/view_component_storybook#configure-asset-hosts), and [change the root to spec/components/stories](https://github.com/jonspalmer/view_component_storybook#configuration).
3. Create a component using `rails generate component Button button_text`. Copy the stories they've written in the `view_component_storybook` README into `spec/components/stories/button_component_stories.rb`, and run `rake view_component_storybook:write_stories_json`.
3. Install Storybook with `npx -p @storybook/cli sb init -t html`
4. Override the configs with those I've left under `Code snippets`.
5. Run `rails s` in one terminal instance and `yarn storybook` in another.
6. The browser should open your Storybook instance. 
7. In either of the stories, change the Button Text control value by adding or removing a character.

**Expected behavior**

One request is made per change to an attribute.

**Screenshots**

![Network traceback with twice the number of requests being sent with each change.](https://user-images.githubusercontent.com/20680337/113292300-38558d00-92ec-11eb-9148-37f0e2097e11.png)

**Code snippets**

<details>
<summary>.storybook/main.js</summary>
<pre>
<code>
module.exports = {
  stories: ["../spec/components/**/*.stories.json"],
  addons: [
    "@storybook/addon-controls",
    "@storybook/addon-links",
    "@storybook/addon-essentials",
  ],
}
</code>
</pre>
</details>

<details>
<summary>.storybook/preview.js</summary>
<pre>
<code>
export const parameters = {
  actions: { argTypesRegex: "^on[A-Z].*" },
  controls: {
    matchers: {
      color: /(background|color)$/i,
      date: /Date$/,
    },
  },
  server: {
    url: `http://localhost:3000/rails/stories`,
  },
}
</code>
</pre>
</details>

<details>
<summary>Generated JSON</summary>
<pre>
<code>
{
  "title": "Button Component",
  "stories": [
    {
      "name": "with_short_text",
      "parameters": {
        "server": {
          "id": "button_component/with_short_text"
        }
      },
      "args": {
        "button_text": "OK"
      },
      "argTypes": {
        "button_text": {
          "control": {
            "type": "text"
          },
          "name": "Button Text"
        }
      }
    },
    {
      "name": "with_long_text",
      "parameters": {
        "server": {
          "id": "button_component/with_long_text"
        }
      },
      "args": {
        "button_text": "Push Me Please!"
      },
      "argTypes": {
        "button_text": {
          "control": {
            "type": "text"
          },
          "name": "Button Text"
        }
      }
    }
  ]
}
</code>
</pre>
</details>

**System**

```
Environment Info:

  System:
    OS: Linux 5.9 Manjaro Linux
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
  Binaries:
    Node: 14.15.5 - ~/.asdf/installs/nodejs/14.15.5/bin/node
    Yarn: 1.22.5 - ~/.asdf/installs/nodejs/14.15.5/.npm/bin/yarn
    npm: 6.14.11 - ~/.asdf/installs/nodejs/14.15.5/bin/npm
  Browsers:
    Firefox: 87.0
  npmPackages:
    @storybook/addon-actions: ^6.2.1 => 6.2.1 
    @storybook/addon-controls: ^6.2.1 => 6.2.1 
    @storybook/addon-essentials: ^6.2.1 => 6.2.1 
    @storybook/addon-links: ^6.2.1 => 6.2.1 
    @storybook/html: ^6.2.1 => 6.2.1 
    @storybook/server: ^6.2.1 => 6.2.1 
```

**Additional context**
I imagine it's probably possible to replicate even without the ViewComponent setup.

The first half of the requests that are sent have this traceback: 
![image](https://user-images.githubusercontent.com/20680337/113294404-d9454780-92ee-11eb-9769-eb11fa27b87c.png)

The second half of the requests call `_renderMain` from `render.js:95` before the first call to `renderMain` in the above traceback.

**Comment by shilman** [comment]
@jonspalmer is this something you can look into?

**Comment by boardfish** [comment]
Would it help you for me to put together a repo to demonstrate the bug, or is there enough info here?

**Comment by shilman** [comment]
@boardfish would definitely help a lot--much appreciated! 🙏

**Comment by boardfish** [comment]
I've just pulled together a [reduced test case](https://github.com/boardfish/storybook-14436) and the bug isn't present. It's not exactly identical at the time of writing because I haven't configured some dependencies like Hotwire and Tailwind, but I'll see if introducing those provokes the bug.

**Comment by jonspalmer** [comment]
I have a demo repo for this combination if it helps track this down: https://github.com/jonspalmer/view_component_storybook_example

I don't remember seeing this problem.

**Comment by boardfish** [comment]
Okay, I've reduced the problem down to my own JS bundle. The only thing that really tampers with the flow to that level is [hotwired/turbo](https://github.com/hotwired/turbo), so I'm willing to bet it'll have been that that's caused the issue.

**Comment by boardfish** [comment]
Yep, the problem is definitely Turbo. I'm loading it once from `application.js` and importing it inside a Stimulus controller. Both of those files are then part of the JS bundle and are getting loaded when the iframe loads, so Turbo is doubly loaded. I assume it's then leaving that callback which is then responsible for duplicating the requests.

I think what I might need to do is look into ways to share the Webpack output between Rails and Storybook.

**Comment by boardfish** [comment]
Okay - I found [this](https://storybook.js.org/docs/react/configure/webpack#using-your-existing-config) in the docs, which fits my use case perfectly. However, 

```js
const path = require("path")

const custom = require("../config/webpack/environment.js")

module.exports = {
  webpackFinal: (config) => {
    return { ...config, module: { ...config.module, rules: custom.rules } }
  },
  stories: ["../spec/components/**/*.stories.json"],
  addons: ["@storybook/addon-controls"],
}
```

Whether I prefix the function with `async` or not, Storybook claims not to be able to find any stories. They're definitely there, and if I start Storybook without `webpackFinal` in the exports, the stories show just fine.

```
ls ../spec/components/**/*.stories.json                                                                                                                                                              
../spec/components/stories/button_component.stories.json
```
