### ISSUE TITLE
6.2.1 Building once and again, all the time.

### ISSUE THREAD

**Issue by hacknlove** [storybookjs/storybook#14431]
**Describe the bug**
After I upgraded from 6.1.21 to 6.2.1 storybook build once and again, all the time

If I downgrade back to 6.1.21 everything it works again as expected.

**Expected behavior**
It should build only when some file changes.

**Screenshots**
https://asciinema.org/a/XMH9ElIyGlywN23sxEW6yrv10

**System**
Please paste the results of `npx sb@next info` here.

Environment Info:

  System:
    OS: Linux 4.19 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (16) x64 Intel(R) Core(TM) i9-10885H CPU @ 2.40GHz
  Binaries:
    Node: 14.15.5 - ~/.nvm/versions/node/v14.15.5/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.7.5 - ~/.nvm/versions/node/v14.15.5/bin/npm
  Browsers:
    Chrome: 89.0.4389.114

**Comment by shilman** [comment]
closing as dupe to #14342
