### ISSUE TITLE
Webpack-loader not working as expected

### ISSUE THREAD

**Issue by CapsE** [storybookjs/storybook#14430]
With version 6.2.1 our twig-loader doesn't work like it used to in version 6.1.21. Instead of getting a function to render the twig-template when importing it into our story we now get a string which is a path to the twig file in a webpack created folder.

I'm no webpack expert but it seems like there some kind of general asset loader that is prioritised over our twig loader.

```js
// .storybook/main.js
const path = require('path');

module.exports = {
    stories: [
        "../stories/**/*.stories.@(js|jsx|mdx)"
    ],
    addons: [
        "@storybook/addon-links",
        "@storybook/addon-essentials",
        "@storybook/preset-create-react-app",
        '@storybook/addon-knobs',
        '@storybook/addon-a11y',
        '@storybook/addon-viewport',
    ],
    webpackFinal: async (config) => {
        // Add twig support
        config.module.rules.unshift({
            test: /\.twig$/,
            use: [
                {loader: 'twigjs-loader'}
            ],

        })

        // Tell Storybook where your components live
        config.resolve.alias['templates'] = path.resolve(
            __dirname,
            '../templates/'
        )

        return config;
    }
}

```

```jsx
// stories/homepage.story.js
import homepage from 'templates/pages/homepage.html.twig';
import {text} from '@storybook/addon-knobs'
import './bootstrap.css';

export default {
    title: 'Homepage'
}
console.log(homepage);

export const normal = () => homepage({
    content: {
        title: text('title', 'Titles'),
        article: text('article', 'Very important text'),
    },
});
```

homepage logs a string like this "static/media/homepage.html.b3f786f4.twig" and when following the URL I get the original unrendered twig file.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1199622255231368/1200143217306180) by [Unito](https://www.unito.io/learn-more)

**Comment by shilman** [comment]
Do you have a repro repo you can share?

**Comment by CapsE** [comment]
Seems to have been in issue with a lot of different moving parts. We started of with a clean new install of the latests version and now everything is working as expected. Sorry for the inconvinience.
