### ISSUE TITLE
Vue 3 default parameter as function for component props work incorrect

### ISSUE THREAD

**Issue by i-kostyakov** [storybookjs/storybook#14434]
**Describe the bug**
I have a component (MyButton) with prop type. That prop has default value and validator. For my internal logic, default value is a function which return string.
And, I have a story for this component which I don't send type prop to component. In this case prop have incorrect value (function as text instead of result of function)

When I load default state in storybook UI, component have got incorrect value to prop 'type'.

**Expected behavior**
The Default parameter should be the result of an expression, not the expression.

**Screenshots**
![image](https://user-images.githubusercontent.com/35257530/113288471-b23f4380-92f7-11eb-90be-7bd8826bce47.png)
![image](https://user-images.githubusercontent.com/35257530/113288554-c6834080-92f7-11eb-8630-848f5e577fd0.png)

**Code snippets**
MyButton component 
```typescript
import { defineComponent, computed } from 'vue';

export enum ButtonTypeKind {
  Primary = 'primary',
  Secondary = 'secondary',
}
const ButtonTypeKinds = Object.values(ButtonTypeKind);

export default defineComponent({
  name: 'my-button',
  props: {
    label: {
      type: String,
      required: true,
    },
    type: {
      default: () => ButtonTypeKind.Primary,
      validator: (value: ButtonTypeKind) => !ButtonTypeKinds.includes(value),
    },
  },
  emits: ['click'],

  setup(props, { emit }) {
    const classSwitcher = () => {
      return {
        button: true,
        [`type--${props.type}`]: true,
      };
    };
    return {
      classes: computed(classSwitcher),
      onClick() {
        emit('click');
      },
    };
  },
});
```

MyButton story
```javascript
import DuButton, { ButtonTypeKind } from '../components/core/DuButton';

export default {
  title: 'Example/Button',
  component: DuButton,
  argTypes: {
    type: { control: { type: 'select' }, options: [ButtonTypeKind.Primary, ButtonTypeKind.Secondary] },
    onClick: {},
  },
};

const Template = (args) => ({
  components: { DuButton },
  setup() { return { args }; },
  template: '<du-button v-bind="args" />',
});

export const DefaultButton = Template.bind({});
DefaultButton.args = {
  label: 'Button',
};
```

**System**
Environment Info:
  System:
    OS: Linux 4.19 Ubuntu 18.04.2 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  Binaries:
    Node: 14.14.0 - ~/.nvm/versions/node/v14.14.0/bin/node
    Yarn: 1.21.1 - ~/node_modules/.bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.14.0/bin/npm

**Comment by lukegravitt** [comment]
This is not an exclusive issue to vue3, this occurs in all versions. Storybook does not set default props correctly if the value is a function (which is required for all arrays and object types) so this results in storybook spewing a lot of errors that don't otherwise exist in your code.

**Comment by shilman** [comment]
@lukegravitt Try upgrading to the latest prerelease:

```
npx sb@next upgrade --prerelease
```

We've changed the way default values are handled and I'm betting this is fixed

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if this is still relevant in SB 7.x.
