### ISSUE TITLE
 On the first load of Docs the component does not show real code of the named story, only args.

### ISSUE THREAD

**Issue by shamilovtim** [storybookjs/storybook#14446]
**Describe the bug**
On the first load of docs the component does not show real code with the selected story. Only args. Any value needs to be clicked on the page in order to get the real source code to show up. I have tried setting different `docs.source.type`, it does not fix the problem which seems to be related to async / ajaxing. I realize that the code is supposed to change with the story, but the story does not even show the initial code, instead showing broken looking `...args` code, which is the problem.

**To Reproduce**

1. Load a component in Docs using ...args
1. The source code will show ...args rather than source code of the highlighted options of the first named story

https://user-images.githubusercontent.com/3495974/113358521-ee809d00-9313-11eb-8350-efe1285cc2ec.mov

**System**

```
  System:
    OS: macOS 11.2.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 14.4.0 - ~/.nvm/versions/node/v14.4.0/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v14.4.0/bin/npm
  Browsers:
    Chrome: 89.0.4389.90
    Firefox: 85.0.2
    Safari: 14.0.3
  npmPackages:
    @storybook/addon-a11y: ^6.1.21 => 6.2.1
    @storybook/addon-essentials: 6.2.0-rc.9 => 6.2.1
    @storybook/react: 6.2.0-rc.9 => 6.2.1
```

**Additional context**

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1199622255231368/1200144880336514) by [Unito](https://www.unito.io)

**Comment by shilman** [comment]
Do you have a repro repo you can share?
