### ISSUE TITLE
Disable PostCSS deprecation warning

### ISSUE THREAD

**Issue by thany** [storybookjs/storybook#14440]
**Describe the bug**
Starting Storybook 6.2+ will trigger a deprecation warning, which will make the console output look quite noisy. The warning is about deprecating the implicit PostCSS loader, which is guess is fine to show... **if** it's actually being used. I'm not using _any_ CSS in our project, and so I don't want such a warning to clutter the console output. My OCD wants to do away with warnings :grinning:, but this one seems to be hardcoded into Storybook.

In the [source](https://github.com/storybookjs/storybook/blob/2d45ee6e7bd889a23834b0d3c5e6b9a257380c0c/lib/builder-webpack4/src/preview/base-webpack.config.ts) I can see that it's _always_ generating that warning for everyone. Except if you explicitly add addon-postcss.

This seems backwards to me. Why should I add an addon that I don't need, in order to hide a warning about its functionality that I wasn't using in the first place??

**To Reproduce**

1. Make sure not to have any CSS in the project
1. Make sure not to accidentally install postcss-addon
1. Start Storybook 6.2
1. Watch the console.

**Expected behavior**
If not using PostCSS: don't bother the console with it.
If using PostCSS: _do_ warn about installing the addon.

**Screenshots**
![image](https://user-images.githubusercontent.com/152227/113304225-1bc44f80-9302-11eb-8d16-98f8044b207a.png)

**System**
Please paste the results of `npx sb@next info` here.

```
Environment Info:

  System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
  Binaries:
    Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 89.0.4389.114
    Edge: Spartan (44.19041.423.0), Chromium (89.0.774.63)
  npmPackages:
    @storybook/addon-docs: 6.2.1 => 6.2.1
    @storybook/addon-links: 6.2.1 => 6.2.1
    @storybook/addons: 6.2.1 => 6.2.1
    @storybook/react: 6.2.1 => 6.2.1
```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1199622255231368/1200147152210816) by [Unito](https://www.unito.io/learn-more)

**Comment by shilman** [comment]
@thany what's your proposed solution?

**Comment by thany** [comment]
I'm not sure. On the one hand, a warning is neccesary for folks relying on postcss. On the other hand it's just noise for folks who don't use it. To them, it might even look like the warning is telling them to install said addon, which shouldn't be the goal of this warning... Isn't there a way to detect if postcss is (going to be) used?

Perhaps it's possible move the warning to trigger at runtime, rather than at build time. That might help to know when it's being used/called.

**Comment by heath-freenome** [comment]
We also do not use postCSS and this warning is more than annoying. How about adding a setting that 1) disables any post-css capabilities in storybook (if any) and as a result stops printing the warning as well?

**Comment by thaoms** [comment]
I actually get this error and I'm not using postcss in our storybook itself, it's actually trying to run a postcss.config.js inside a node module import, while I'm just importing the dist css from that module. Seems like a bug?

**Comment by shilman** [comment]
Crikey!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.3 containing PR #14478 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by kaelig** [comment]
For people who can't upgrade to 6.2.3 yet, this is a workaround:

```
// Silence deprecation warnings about postcss
process.noDeprecation = true;
```

**Comment by JohnCasab** [comment]
If you dont use Postcss you can out this in your `.storybook/main.js`

```
module.exports = {
  features: {
    postcss: false,
  },
};
```
As suggested in the documentation: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-implicit-postcss-loader

**Comment by jdgomezb** [comment]
> If you dont use Postcss you can paste this in your `.storybook/main.js`
> 
> ```
> module.exports = {
>   features: {
>     postcss: false,
>   },
> };
> ```
> 
> As suggested in the documentation: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-implicit-postcss-loader


Yes, adding this property to the exports object fixed the warning issue
