### ISSUE TITLE
Svelte Dynamic snippets doesn't work without user interactions

### ISSUE THREAD

**Issue by j3rem1e** [storybookjs/storybook#14443]
**Describe the bug**

The source dynamically generated for a svelte story isn't show until the user changes an arg or clicks on another story.

This is caused by this commit https://github.com/storybookjs/storybook/commit/5c1e2b458abda5e1740b83de1f2145b99fda86d6

In order to support "async loaders", the function `prepareForInline` is asynchronous. However, the `SourceContainer` doesn't seem to be able to handle asynchronous source events.

**To Reproduce**

1. In svelte-kitchen-sink, open the Button story
1. Click on the "Doc" tab
1. The preview doesn't have any sources attached
1. Change a property
1. The source is updated but show the previous code (change in 4 is not visible)

**Additional context**
Storybook v6.2.1, Svelte addon

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1199622255231368/1200143905279757) by [Unito](https://www.unito.io/learn-more)

**Comment by j3rem1e** [comment]
@shilman I don't know if we should revert the commit or fix the real bug: Today, the doc addon can't handle asynchronous loader. 

The injection of args from the url doesn't seem to work either.

**Comment by shilman** [comment]
@j3rem1e let's revert the async loader support. it doesn't work in other frameworks yet anyways, so we can bring it back later

**Comment by shilman** [comment]
Jeepers creepers!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.2 containing PR #14444 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```
