### ISSUE TITLE
Build breaks if `config.js` is used instead of `main.js`, was working on 6.17.1

### ISSUE THREAD

**Issue by rdsedmundo** [storybookjs/storybook#14458]
**Describe the bug**
After upgrading Storybook to `6.2.2` my build stopped working, without any configuration changes. It was working perfectly on `6.17.1` (downgrading makes it work again).

```
ERR! TypeError: Cannot read property 'endsWith' of undefined
ERR!     at /Users/rdsedmundoxo/redacted/redacted/node_modules/@storybook/core-common/dist/cjs/utils/interpret-files.js:40:24
ERR!     at Array.map (<anonymous>)
ERR!     at getInterpretedFileWithExt (/Users/rdsedmundoxo/redacted/redacted/node_modules/@storybook/core-common/dist/cjs/utils/interpret-files.js:38:29)
ERR!     at getCandidate (/Users/rdsedmundoxo/redacted/redacted/node_modules/@storybook/core-common/dist/cjs/utils/interpret-require.js:72:67)
ERR!     at serverResolve (/Users/rdsedmundoxo/redacted/redacted/node_modules/@storybook/core-common/dist/cjs/utils/interpret-require.js:107:27)
ERR!     at serverRequire (/Users/rdsedmundoxo/redacted/redacted/node_modules/@storybook/core-common/dist/cjs/utils/interpret-require.js:84:23)
ERR!     at getPreviewBuilder (/Users/rdsedmundoxo/redacted/redacted/node_modules/@storybook/core-server/dist/cjs/utils/get-preview-builder.js:25:54)
ERR!     at buildStaticStandalone (/Users/rdsedmundoxo/redacted/redacted/node_modules/@storybook/core-server/dist/cjs/build-static.js:95:71)
ERR!     at async buildStatic (/Users/rdsedmundoxo/redacted/redacted/node_modules/@storybook/core-server/dist/cjs/build-static.js:144:5)
```

I debugged the issue and found that it's erroring out because `getPreviewBuilder` is sending an `undefined` value to `serverRequire` as the `main.js` file does not exist.

**To Reproduce**

1. Configure a project with `config.js` instead of `main.js`. 
1. Run `build-storybook`.

**Expected behavior**
Should still work with the old `config.js` as it's not deprecated yet (?). I couldn't find accurate information on the deprecation\, there's one article saying that it would have been supported up to 6.0 release, but it feels weird that a minor patch is removing the support instead of the major release.

**System**

```
Environment Info:

  System:
    OS: macOS 11.2.3
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  Binaries:
    Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v14.16.0/bin/npm
  Browsers:
    Chrome: 89.0.4389.114
    Firefox: 87.0
    Safari: 14.0.3
```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1199622255231368/1200148234146829) by [Unito](https://www.unito.io/learn-more)

**Comment by renemonroy** [comment]
Getting same error here.

**Comment by fikyair** [comment]
Getting same error here.

**Comment by fikyair** [comment]
Hope to fix it soon
tx~

**Comment by shilman** [comment]
This is a regression in 6.2 and we'll fix this week. That said, `config.js` is deprecated and will be removed in 7.0, so please consider upgrading to `main.js` configuration as a workaround:

https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#to-mainjs-configuration

**Comment by macrozone** [comment]
same happens if you have no main.js. I now just added an empty one with `module.exports = {}`

there are a lot of user who missed the migration of these files, i personally never heard about preview.js, main.js etc.

**Comment by shilman** [comment]
Olé!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.3 containing PR #14479 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```

Closing this issue. Please re-open if you think there's still more to do.
