### ISSUE TITLE
[Feature] Add layout option to toolbar

### ISSUE THREAD

**Issue by SatorCube** [storybookjs/storybook#14456]
**Is your feature request related to a problem? Please describe**
As a user, I enjoy the presentation of a component that is centered in a story. However, I often would like to use the grid to help with designing the layout of a component and the grid is only practical when a component is aligned top and left.

**Describe the solution you'd like**
I would like a button in the toolbar that would allow me to swap between the various layout options of a story as seen [here](https://storybook.js.org/docs/react/configure/story-layout)

**Comment by ghengeveld** [comment]
Would lining up the grid with the centered component make sense here?

**Comment by SatorCube** [comment]
That could work as well. The root of the problem is that the grid isn't very useful if components are centered. So if the grid was aligned with the centered component then that would solve that problem.

You would need to account for the component moving in the following cases:

- The preview is resized when
    - Addon pane is closed
    - Fullscreen is entered
    - Navigation pane is closed/resized
- The component is resized via a prop on the control

I'm not sure how hard it would be to keep the grid centered for these cases but if it isn't an issue than I would be satisfied :)

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if this is still relevant in SB 7.x.
