### ISSUE TITLE
[Lit] Improve page reload setup

### ISSUE THREAD

**Issue by gaetanmaisse** [storybookjs/storybook#14451]
### Work summary

Web components cannot be hot reloaded as `customElement.define` can only be called once per page with a unique string. 

So for now in `@storybook/web-components`, to have a page reload when a component or a story is updated users need to add a specific, dirty config in `preview.js`, see: https://github.com/storybookjs/storybook/tree/master/app/web-components#setup-page-reload-via-hmr

As finding a way to have a proper HMR look to be a non-trivial thing, a good first step would be to move this hacky config inside `@storybook/web-components` and so give it for free to Storybook users. Also, the doc should be updated accordingly.

### Where to start

A PR has already been opened by @brion-fuller: https://github.com/storybookjs/storybook/pull/14445

### Acceptance criteria

 - Bootstrap a simple `lit` project, add and run Storybook without any specific config, any changes on components or stories should trigger a page reload.

### Who to contact

@gaetanmaisse @yannbf @brion-fuller

**Comment by shilman** [comment]
closing as dupe to #12307
