### ISSUE TITLE
@storybook/addon-docs: Yet another "No code available"

### ISSUE THREAD

**Issue by rwieruch** [storybookjs/storybook#14463]
* [Storybook with "No code available"](https://react-table-library.com/)
* [Project on GitHub](https://github.com/table-library/react-table-library)

I am not sure when this happened, but for `@storybook/addon-docs` I get "No code available". It worked some time ago though.

Version: 6.1.21

_main.js_:

```
module.exports = {
  stories: ['./stories/**/*.@(js|mdx)'],
  addons: ['@storybook/addon-docs', '@storybook/addon-storysource'],
};
```

(I tried removing `@storybook/addon-storysource`, [as suggested over here](https://github.com/storybookjs/storybook/issues/10179), but without success.)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1199622255231368/1200157258131398) by [Unito](https://www.unito.io/learn-more)

**Comment by pravbeseda** [comment]
I have the same problem (angular)

1. ng new test-app
2. cd test-app
3. npx -p @storybook/cli sb init
4. npm run storybook

On Docs tab of predefined Stories I see "No code available". The "Show code" button is unlocked after clicking on "Reset controls".

The problem is reproducible on versions 6.2.1-6.2.3.

Please help!

**Comment by shilman** [comment]
@rwieruch was this ever working for this repo? There's a duplicate issue which I'm unable to find right now, which is that addon-docs sets up the source-loader to run on `\.(stories|story).[tj]sx?$`, which your stories don't match:

https://github.com/storybookjs/storybook/blob/next/addons/docs/src/frameworks/common/preset.ts#L54-L63

Ideally it would simply use the `.storybook/main.js` `stories` glob, but that's not the case right now.

**Comment by pravbeseda** [comment]
@shilman Should I create a separate issue? The malfunction in the reference example looks like a bug.

**Comment by shilman** [comment]
@pravbeseda that bug already exists here i think #14193

**Comment by rwieruch** [comment]
> @rwieruch was this ever working for this repo? There's a duplicate issue which I'm unable to find right now, which is that addon-docs sets up the source-loader to run on `\.(stories|story).[tj]sx?$`, which your stories don't match:
> 
> https://github.com/storybookjs/storybook/blob/next/addons/docs/src/frameworks/common/preset.ts#L54-L63
> 
> Ideally it would simply use the `.storybook/main.js` `stories` glob, but that's not the case right now.

Yes, it could be that I changed something in the in my last commits that caused this issue, but I have a hard time narrowing it down. So you are saying that I need to name my stories in a specific way to make it work again? I can look into this!

**Comment by shilman** [comment]
@rwieruch this constraint has been there since v5.3, which is that in order for source-loader to be auto-registered by addon-docs you must name your stories files `*.(story|stories).[tj]sx?`.

**Comment by rwieruch** [comment]
Confirmation: Story needs to be named *.story or *.stories. Thanks @shilman 👍🏽

**Comment by sir-captainmorgan21** [comment]
@shilman should we open a separate issue? I am seeing this similar to @jmtt89 above
