### ISSUE TITLE
Storybook HMR working in windows but not in WSL2 ubuntu

### ISSUE THREAD

**Issue by mdirshaddev** [storybookjs/storybook#14467]
**HMR not working in storybook running on WSL2 ubuntu**
Currently I am using Webpack5 based React the storybook version is 6.2.2 it works very well in windows environment but in WSL2 Ubuntu it does not auto reload changes.

**Comment by TheFirstMe** [comment]
I also noticed this issue. Does not auto reload on changes

**Comment by mdirshaddev** [comment]
> I also noticed this issue. Does not auto reload on changes

Don't know when it will be fixed

**Comment by TheFirstMe** [comment]
It seems to be working now. Don't know what changed.

**Comment by TheFirstMe** [comment]
![image](https://user-images.githubusercontent.com/23120939/114277387-9fcdb400-9a33-11eb-94f7-6210abdd07e0.png)
Seeing that "99% done" is bothering me though 😅

**Comment by mdirshaddev** [comment]
> ![image](https://user-images.githubusercontent.com/23120939/114277387-9fcdb400-9a33-11eb-94f7-6210abdd07e0.png)
> Seeing that "99% done" is bothering me though 😅

Hey I found that what was bothering I was trying to use the windows file system within a Linux environment. After I stopped using the mount drives of windows 10 within the Linux everything went well the HMR is working now and it is superfast really just as was mentioned in the doc of Microsoft WSL2. You should save file in linux drive when working in WSL not in Windows any  drives.
Sorry for my weak english skills.
@shilman @TheFirstMe @Peeja @paulrosania
