### ISSUE TITLE
[React JS] Build error,  NestedError: Cannot copy '@storybook\core-server\diat\node_modules\@storybook\core-server\dist\cjs\public\favicon.ico'' 

### ISSUE THREAD

**Issue by mdminoza** [storybookjs/storybook#14466]
**Describe the bug**
I always encountered this error recently.
Build failed when running `build-storybook` on @storybook/react `6.2.2` & `6,1,1`.
Using create-react-app typescript

**To Reproduce**
Run `build-storybook `

**Expected behavior**
Build should be successful.

**Screenshots**
![err2](https://user-images.githubusercontent.com/31148142/113484690-3b16d480-94dc-11eb-873b-7f13fbcb0f2a.PNG)

**System**
Environment Info:
  System:
    OS: Windows 10 10.0.16299
    CPU: (4) x64 Intel(R) Core(TM) i5 CPU       M 520  @ 2.40GHz
  Binaries:
    Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (41.16299.15.0)
  npmPackages:
    @storybook/react: 6.2.2 => 6.2.2

**Comment by shilman** [comment]
Do you have a repro repo you can share?

**Comment by Shaun-Regenbaum** [comment]
I am also encountering the issue. To reproduce just try building storybook in the default svelte-kit repo.

**Comment by lbouriez** [comment]
Hello, I am having the same issue trying to build storybook in a Docker Dev container

**Comment by enguyen807** [comment]
I am also having the same issue. I was able to build storybook by changing
 `  var defaultFavIcon = require.resolve('./public/favicon.ico');  to  var defaultFavIcon = './public/favicon.ico'` 
but I don't think it's a very viable solution...

**Comment by HexMox** [comment]
+1 and I use `latest` tag version which is 6.3.12

**Comment by jackfrosty908** [comment]
A workaround I'm using to get storybook building locally using "@storybook/react": "^6.5.5", : 

1. In your node_modules go to `@storybook\core\dist\cjs` 
2. Open `build-static.js`
3. Find `await (0, _cpy.default)(defaultFavIcon, options.outputDir);` and comment it out
4. Rerun your storybook build command

Obviously not a long term solution, but may help someone else out.

**Comment by sinoon** [comment]
I have same error, and I found the reason Although I don't know how it happened.

the error occurred in cp-file:
```js
	let updateStats = false;
	try {
		const writePromise = pEvent(write, 'close');
		read.pipe(write);
		await writePromise;
		progressEmitter.written = progressEmitter.size;
		updateStats = true;
	} catch (error) {
		if (options.overwrite || error.code !== 'EEXIST') {
			throw new CpFileError(`Cannot write to \`${destination}\`: ${error.message}`, error);
		}
	}

	if (readError) {
		throw readError;
	}

	if (updateStats) {
		const stats = await fs.lstat(source);

		return Promise.all([
			fs.utimes(destination, stats.atime, stats.mtime),
			fs.chmod(destination, stats.mode),
			fs.chown(destination, stats.uid, stats.gid)
		]);
	}
```
when `fs.utimes(destination, stats.atime, stats.mtime),` will throw error, because the stats is wrong, you can console.log the stats. 

my error stats is:
<img width="662" alt="image" src="https://user-images.githubusercontent.com/6065488/190127618-e0b5c448-5533-4614-8335-4c57d690f357.png">

So the solution is to fix the atime of this file, using touch or other methods.

**Comment by orest22** [comment]
After migration from yarn to pnpm started receiving this error as well.

```
info @storybook/react v6.5.15
info 
info => Cleaning outputDir: <root>/packages/storybook/storybook-static
ERR! NestedError: Cannot copy `<root>/node_modules/.pnpm/@storybook+core-server@6.5.15(@storybook+builder-w_pldnvyes3tzbrbjhdmhffpkmwq/node_modules/@storybook/core-server/public/favicon.ico`: the file doesn't exist
ERR!     at <root>/node_modules/.pnpm/cpy@8.1.2/node_modules/cpy/index.js:96:10
ERR!     at processTicksAndRejections (node:internal/process/task_queues:96:5)
ERR!     at async buildStaticStandalone (<root>/node_modules/.pnpm/@storybook+core-server@6.5.15(@storybook+builder-w_pldnvyes3tzbrbjhdmhffpkmwq/node_modules/@storybook/core-server/dist/cjs/build-static.js:104:3)
ERR!     at async buildStatic (<root>/node_modules/.pnpm/@storybook+core-server@6.5.15(@storybook+builder-w_pldnvyes3tzbrbjhdmhffpkmwq/node_modules/@storybook/core-server/dist/cjs/build-static.js:250:5)
ERR!  NestedError: Cannot copy `<root>/node_modules/.pnpm/@storybook+core-server@6.5.15(@storybook+builder-w_pldnvyes3tzbrbjhdmhffpkmwq/node_modules/@storybook/core-server/public/favicon.ico`: the file doesn't exist
ERR!     at <root>/node_modules/.pnpm/cpy@8.1.2/node_modules/cpy/index.js:96:10
ERR!     at processTicksAndRejections (node:internal/process/task_queues:96:5)
ERR!     at async buildStaticStandalone (<root>/node_modules/.pnpm/@storybook+core-server@6.5.15(@storybook+builder-w_pldnvyes3tzbrbjhdmhffpkmwq/node_modules/@storybook/core-server/dist/cjs/build-static.js:104:3)
ERR!     at async buildStatic (<root>/node_modules/.pnpm/@storybook+core-server@6.5.15(@storybook+builder-w_pldnvyes3tzbrbjhdmhffpkmwq/node_modules/@storybook/core-server/dist/cjs/build-static.js:250:5) {
ERR!   nested: undefined,
ERR!   name: 'CpyError'
ERR! }
info => Loading presets
error Command failed with exit code 1.
```

**Comment by aspirisen** [comment]
Have the same error on PNPM. `"@storybook/react": "^6.5.15",`

**Comment by rmfruit** [comment]
This is an old issue, but I figure I'd post here if this helps. I my case it was parenthesis (`(`, `)`) in the path that made `cpy` fail. Looking back at the previous posts it looks like it could be the same for some of you (perhaps `{` in the initial post). I was able to build I moved everything into a `(test)` directory (a valid directory name in apache linux and many others I'm sure):

```
info => Cleaning outputDir: /home/(test)/sb-test/storybook-static
ERR! NestedError: Cannot copy `/home/(test)/sb-test/node_modules/@storybook/core-server/public/favicon.ico`: the file doesn't exist
ERR!     at /home/(test)/sb-test/node_modules/cpy/index.js:96:10
ERR!     at processTicksAndRejections (internal/process/task_queues.js:93:5)
ERR!     at async buildStaticStandalone (/home/(test)/sb-test/node_modules/@storybook/core-server/dist/cjs/build-static.js:104:3)
ERR!     at async buildStatic (/home/(test)/sb-test/node_modules/@storybook/core-server/dist/cjs/build-static.js:250:5)
ERR!  NestedError: Cannot copy `/home/(test)/sb-test/node_modules/@storybook/core-server/public/favicon.ico`: the file doesn't exist
ERR!     at /home/(test)/sb-test/node_modules/cpy/index.js:96:10
ERR!     at processTicksAndRejections (internal/process/task_queues.js:93:5)
ERR!     at async buildStaticStandalone (/home/(test)/sb-test/node_modules/@storybook/core-server/dist/cjs/build-static.js:104:3)
ERR!     at async buildStatic (/home/(test)/sb-test/node_modules/@storybook/core-server/dist/cjs/build-static.js:250:5) {
ERR!   nested: undefined,
ERR!   name: 'CpyError'
ERR! }
```

In my case I was able to remove the offending characters, but this feels like a bug in `cpy`.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
