### ISSUE TITLE
Docs-only stories

### ISSUE THREAD

**Issue by hazem3500** [storybookjs/storybook#14476]
**Is your feature request related to a problem? Please describe**

I want to make a Documentation-only MDX story of our design tokens.
The problem is that for me to access the `ThemeProvider`'s (which I've added via `decorators`) value, I need to wrap each token section inside a `Story` block.

```jsx
import { Meta, Story } from '@storybook/addon-docs/blocks';
import { BreakPoints } from './DESIGN_TOKENS.examples.tsx';


<Meta title="Design Tokens" />

# Break Points

<Story name="Break Points">
    <BreakPoints />
</Story>
``` 

which makes each token appear as a story in the sidebar.

**Describe the solution you'd like**
I would like to specify to the `Story` block that it should only appear in the docs and not the sidebar.

Or there could be another Block that can provide the value of the `ThemeProvider` without turning it into a story (`View` or `Layer`?).

**Describe alternatives you've considered**
I could leave the stories as is but I wanted to indicate that it would be better to view these tokens on the docs page.

**Are you able to assist to bring the feature to reality?**
Would love to help 😁

**Comment by shilman** [comment]
You probably want this: https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/recipes.md#overwriting-docs-container

**Comment by hazem-osama** [comment]
It works great 👍, thanks @shilman 😄

**Comment by hazem3500** [comment]
It works great 👍, thanks @shilman 😄

**Comment by mathias-falkenberg** [comment]
> You probably want this: https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/recipes.md#overwriting-docs-container

The link above no longer works. It can now be found here: https://github.com/storybookjs/storybook/blob/next/code/addons/docs/docs/recipes.md#overwriting-docs-container
