### ISSUE TITLE
Using decorators causes state to be lost on Controls change

### ISSUE THREAD

**Issue by Sawtaytoes** [storybookjs/storybook#14475]
**Describe the bug**
If you change a control (like typing in a text field) when `decorators` is defined in `.storybook/preview.js`, it completely reloads the component without state.

**To Reproduce**

1. `export` a `decorators` with a function that renders a story.
2. Create a story that sends `children` as a string to `args`.
3. Controls will display a text input which changes the `children` prop.
4. Type in this prop and notice that any state (even refs) are lost in the component.

The way I test this is by console logging a `useRef` which I set after the `console.log`. It should have `current` defined every time `children` is updated, but it's `undefined` unless I remove all functions from the `decorators` export.

**Expected behavior**
I expect it to retain state like it normally does.

**Screenshots**
## Without Decorators
![image](https://user-images.githubusercontent.com/3948069/113541642-446d7300-95a8-11eb-8071-48ef1b1b1b47.png)

## With a single Decorator
![image](https://user-images.githubusercontent.com/3948069/113541591-2c95ef00-95a8-11eb-943d-f8a45e6c0c8a.png)

**Code snippets**
This is all you need to break state in Storybook:
```js
export const decorators = [
  Story => <Story />,
]
```

**System**
```sh
Environment Info:

  System:
    OS: Windows 10 10.0.19042
    CPU: (16) x64 AMD Ryzen 7 3800X 8-Core Processor
  Binaries:
    Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 89.0.4389.114
    Edge: Spartan (44.19041.423.0), Chromium (89.0.774.68)
  npmPackages:
    @storybook/addon-actions: ^6.2.2 => 6.2.2
    @storybook/addon-essentials: ^6.2.2 => 6.2.2
    @storybook/addon-links: ^6.2.2 => 6.2.2
    @storybook/react: ^6.2.2 => 6.2.2
```

**Comment by ghengeveld** [comment]
There must be something special about either your story or your component, because I cannot reproduct. In fact, `official-storybook` uses a bunch of global decorators as well as [controls](https://github.com/storybookjs/storybook/blob/01d3f8f63cc62b8c4b7a498757498604072178e4/examples/official-storybook/stories/addon-controls.stories.tsx#L8) for `children` and other props, and these work as expected. Setting the single decorator you provided does not break it.

Could you provide a minimal reproduction, preferably with a complete story file with embedded component (no import)?

**Comment by Sawtaytoes** [comment]
@ghengeveld 
I see what you're talking about with [global custom decorators](https://github.com/storybookjs/storybook/blob/01d3f8f63cc62b8c4b7a498757498604072178e4/examples/official-storybook/preview.js).

There's also a PR out there to fix this exact issue: https://github.com/storybookjs/storybook/pull/13049, and a bunch of other people have reported similar problems in their PRs. I've also run into this on a couple other Storybook projects at work.

It's great to have a test-case you can use to verify any fixes though.

The current library where I'm seeing these problems is brand new and completely open source: https://github.com/Sawtaytoes/OneForm.

To test:
1. Install `yarn` classic (v1).
2. From the project root, run:
```sh
npx lerna bootstrap
npx lerna run dev:storybook --scope @oneform/react --stream
```
3. Go to http://localhost:6006/?path=/story/components-fieldvalue--text.
4. Type fast in the `message` control and notice flashing.
5. If you log a `ref` at the top of the component definition in `OneForm/packages/react/src/OneForm.jsx`, you'll see the issues I've shown in that screenshot.
