### ISSUE TITLE
Vulnerability on Storybook 6.2.2

### ISSUE THREAD

**Issue by BiancaArtola** [storybookjs/storybook#14487]
I know that it is not a bug, but I need to report a vulnerability that appears when I update to version `6.2.2`

```
Dependabot cannot update ssri to a non-vulnerable version
The latest possible version that can be installed is 6.0.1 because of the following conflicting dependencies:

- @storybook/addon-essentials@6.2.2 requires ssri@^6.0.1 via a transitive dependency on cacache@12.0.4
- @storybook/react@6.2.2 requires ssri@^6.0.1 via a transitive dependency on cacache@12.0.4

The earliest fixed version is 8.0.1.

```

Can you fix this on the next release?? This vulnerability wasn't present on version 6.1.21

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1199622255231368/1200155097096936) by [Unito](https://www.unito.io/learn-more)

**Comment by ajkl2533** [comment]
I also have this issue it's coming from `webpack@4` through `terser-webpack-plugin` :(

**Comment by stof** [comment]
The `ssri` package has released a patched 6.0.2 version. So running `yarn upgrade` will install a patched version thanks to semver ranges.

**Comment by BiancaArtola** [comment]
Thanks!!!!!!!!!

**Comment by astreiten** [comment]
Hello, I ran the `yarn upgrade` command but the vulnerability is still present. Am I missing something? Thanks.
