### ISSUE TITLE
Warning: Encountered two children with the same key, `30-54`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version

### ISSUE THREAD

**Issue by MukeshJ2506** [storybookjs/storybook#14481]
**Describe the bug**
I have a date range picker with two instances of date pickers running in a story

**To Reproduce**

Its within our storybook which is used internally

**Expected behavior**
This is printed as warning but it blocks the functionality in my story and the code i use is an external lib within my component

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
Please paste the results of `npx sb@next info` here.

**Additional context**
Warning: Encountered two children with the same key, `30-54`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version

**Comment by shilman** [comment]
Do you have a repro repo you can share?

**Comment by MukeshJ2506** [comment]
@shilman Apologizing since its behind the orgs walls. But noticed this in storybook/angular with two instances of angular-mydatepicker in the same component

**Comment by MukeshJ2506** [comment]
`angularLegacyRendering: true` currently this helps in functioning as of now. Also could see these errors pop up at some places

`ngOnDestroy is not a function`

**Comment by cbranch101** [comment]
@MukeshJ2506 Do you have the storysource addon installed?  I'm seeing this too, and I think it's an issue related to that

**Comment by Faey2222** [comment]
Definetely has to do with the storysource addon. Just got the same exact error after installing storysource :(

**Comment by shilman** [comment]
I'd recommend removing storysource as a workaround

**Comment by MukeshJ2506** [comment]
@ cbranch101 Apology for the delayed response. Yes we do use storysource in our repo

**Comment by snaka** [comment]
I ran into the same situation today and have confirmed that workaround (removing `@storybook/addon-storysource` from addon) solves the problem.

( For anyone who came to this thread from Google, I just note that this is still happening and that workaround is still in effect )

**Comment by ar4hc** [comment]
Just a me too, with not much more infos:

Similar error in 6.5, two date pickers in same component, but it's  react, not angular,
repeating half a dozen times or so.

and no storysource installed, but it's in a formik  form.

Error in console is:
```
Encountered two children with the same key, `storybook/react-router-v6/story-loaded_0`.
```

<details>

<summary>
i got some sort of stack traces in the console too:
</summary>

```
div
div
div
div
OverlayScrollbarsComponent@http://localhost:6006/vendors-_yarn___virtual___storybook-components-virtual-f6844254b8_5_yarn_berry_cache_storyboo-7d990c.manager.bundle.js:6705:20
Suspense
Scroller
./.yarn/__virtual__/@storybook-theming-virtual-bd9beb37a7/5/.yarn/berry/cache/@storybook-theming-npm-6.5.16-3cd34b3614-8.zip/node_modules/@storybook/theming/dist/esm/index.js/withEmotionCache/<@http://localhost:6006/vendors-_yarn___virtual___bbbtech-storybook-formik-virtual-2e3081453d_5_yarn_berry_cache_bbbt-418317.manager.bundle.js:60170:67
```
going on for a while an then:

```
overrideMethod moz-extension://a05646bc-740e-1a4d-9506-f1a856b9a38c/build/react_devtools_backend.js:4012
    printWarning http://localhost:6006/vendors-_yarn___virtual___bbbtech-storybook-formik-virtual-2e3081453d_5_yarn_berry_cache_bbbt-418317.manager.bundle.js:64555
    error http://localhost:6006/vendors-_yarn___virtual___bbbtech-storybook-formik-virtual-2e3081453d_5_yarn_berry_cache_bbbt-418317.manager.bundle.js:64531
    warnOnInvalidKey http://localhost:6006/vendors-_yarn___virtual___bbbtech-storybook-formik-virtual-2e3081453d_5_yarn_berry_cache_bbbt-418317.manager.bundle.js:78108
    reconcileChildrenArray http://localhost:6006/vendors-_yarn___virtual___bbbtech-storybook-formik-virtual-2e3081453d_5_yarn_berry_cache_bbbt-418317.manager.bundle.js:78139
    reconcileChildFibers http://localhost:6006/vendors-_yarn___virtual___bbbtech-storybook-formik-virtual-2e3081453d_5_yarn_berry_cache_bbbt-418317.manager.bundle.js:78613
    reconcileChildren http://localhost:6006/vendors-_yarn___virtual___bbbtech-storybook-formik-virtual-2e3081453d_5_yarn_berry_cache_bbbt-418317.manager.bundle.js:81485
    updateHostComponent http://localhost:6006/vendors-_yarn___virtual___bbbtech-storybook-formik-virtual-2e3081453d_5_yarn_berry_cache_bbbt-418317.manager.bundle.js:82120
    beginWork http://localhost:6006/vendors-_yarn___virtual___bbbtech-storybook-formik-virtual-2e3081453d_5_yarn_berry_cache_bbbt-418317.manager.bundle.js:83568
```

and more    

</details>

**Comment by danielvinter** [comment]
Encountering this with Storybook 7^
