### ISSUE TITLE
Why my Docs are loading this way?

### ISSUE THREAD

**Issue by ebellumat** [storybookjs/storybook#14483]
My props from components are loading with this annoying MDN references and i don't know why.

Can anyone help me to configure the react-docgen-typescript correctly?

![image](https://user-images.githubusercontent.com/26942680/113595948-0b68e900-9610-11eb-98eb-ccdcfd9a8a0e.png)

**Comment by ghengeveld** [comment]
Can you provide more context such as the source of this story and your Storybook configuration?

**Comment by ebellumat** [comment]
Yes! I will put more context here.

I'm using [@emotion](https://github.com/emotion-js/emotion) to create my components and [styled-system](https://github.com/styled-system/styled-system) to create my design-system.

But, the [@types/styled-system](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/styled-system) of styled-system comes with this huge documentation and generic types.

I'm using MDX to write my stories.

```jsx
<Props of={MyComponent} />
```

I Want to know how can i override this generated types to gain more control of these generated information.

**Comment by ndelangen** [comment]
Here's how you can change it:
https://storybook.js.org/docs/react/api/argtypes#page-top
