### ISSUE TITLE
New version popup disturbs visual regression tests

### ISSUE THREAD

**Issue by albert-schilling** [storybookjs/storybook#14498]
**Describe the bug**
The new version available popup disturbs visual regression tests in CI.

**To Reproduce**
First install a not so recent version of storybook, then start and open it. A message pops up indicating that there is a newer version of storybook available. 

**Expected behavior**
Although, it is nice to be reminded of newer versions, I would suggest to only display this reminder in the console, not the UI.

**Screenshots**
See an excerpt from our image diff:
![Storybook issue](https://user-images.githubusercontent.com/59568178/113832293-c3210680-9788-11eb-980e-27ccdca8625b.png)

**System**
Environment Info:

  System:
    OS: Linux 5.4 Ubuntu 18.04.5 LTS (Bionic Beaver)
    CPU: (6) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Binaries:
    Node: 12.20.1 - ~/.nvm/versions/node/v12.20.1/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 6.14.10 - ~/.nvm/versions/node/v12.20.1/bin/npm
  Browsers:
    Firefox: 87.0
  npmPackages:
    @storybook/addon-actions: ^6.2.1 => 6.1.21 
    @storybook/addon-controls: ^6.2.1 => 6.1.21 
    @storybook/addon-docs: ^6.2.1 => 6.1.21 
    @storybook/addon-essentials: ^6.2.1 => 6.1.21 
    @storybook/addon-knobs: ^6.2.1 => 6.1.21 
    @storybook/addon-links: ^6.2.1 => 6.1.21 
    @storybook/addon-storyshots: ^6.2.1 => 6.1.21 
    @storybook/addons: ^6.2.1 => 6.1.21 
    @storybook/preset-create-react-app: ^3.1.7 => 3.1.7 
    @storybook/react: ^6.2.1 => 6.1.21 
    storybook-addon-kit:  1.0.0

**Comment by shilman** [comment]
@albert-schilling are you running in dev mode? we recommend running production mode, where the popup should not show.

**Comment by albert-schilling** [comment]
> @albert-schilling are you running in dev mode? we recommend running production mode, where the popup should not show.
@shilman Thank you for the quick reply. This makes sense, we'll adjust our CI script. Thanks!
