### ISSUE TITLE
addon-docs: Stories with disabled docs are displayed in --docs mode

### ISSUE THREAD

**Issue by ajkl2533** [storybookjs/storybook#14503]
**Describe the bug**
I have several stories used only for visual testing with the disabled Docs tab. I was expecting that those stories will be hidden in the sidebar when I build a static storybook in docs mode (via `--docs` flag). But when I open build storybook I still can see those stories in the sidebar and when I open any of them it opens the docs page with title and `Cannot read property 'id' of undefined` error.

**To Reproduce**

1. Clone https://github.com/securityscorecard/design-system
2. Build static storybook with `yarn storybook:build --docs`
3. Open build storybook in browser
4. Look for `Datatable/internalComponent` in sidebar

**Expected behavior**
Stories with disabled docs should not be displayed in docs mode

**Screenshots**
<img width="1426" alt="Screenshot 2021-04-07 at 14 14 47" src="https://user-images.githubusercontent.com/18654425/113865517-76e7bd80-97ac-11eb-9bff-a80030b52d07.png">

**Code snippets**
```ts
export default {
  title: 'components/Datatable/internalComponents/Datatable',
  component: Datatable,
  parameters: {
    viewMode: 'story',
    docs: { disable: true },
    previewTabs: { 'storybook/docs/panel': { hidden: true } },
  },
  decorators: [(storyFn) => <MemoryRouter>{storyFn()}</MemoryRouter>],
} as Meta;
```

**System**
```
Environment Info:

  System:
    OS: macOS 11.2.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 7.8.0 - ~/Downloads/design-system/node_modules/.bin/npm
  Browsers:
    Chrome: 89.0.4389.114
    Safari: 14.0.3
  npmPackages:
    @storybook/addon-a11y: ^6.2.3 => 6.2.3 
    @storybook/addon-actions: ^6.2.3 => 6.2.3 
    @storybook/addon-backgrounds: ^6.2.3 => 6.2.3 
    @storybook/addon-controls: ^6.2.3 => 6.2.3 
    @storybook/addon-docs: ^6.2.3 => 6.2.3 
    @storybook/react: ^6.2.3 => 6.2.3 
    @storybook/theming: ^6.2.3 => 6.2.3 
```

**Comment by shilman** [comment]
@ajkl2533 I'm not sure if this is the best fix, but I think you could probably do some kind of early-exit thing here:

https://github.com/storybookjs/storybook/blob/next/lib/core-client/src/preview/loadCsf.ts#L193

And here's how to tell whether you're in docs-mode:

https://github.com/storybookjs/storybook/blob/next/lib/api/src/modules/layout.ts#L1
