### ISSUE TITLE
upgrading from 6.1.17 to 6.2.5 is a breaking change

### ISSUE THREAD

**Issue by chadlavi-casebook** [storybookjs/storybook#14507]
**Describe the bug**

I just ran `npx sb upgrade` on a working storybook app. After the upgrade from 6.1.17 to 6.2.5, I can no longer run storybook, as there seems to be a new babel dependency.

This is the error I get:

```
SyntaxError: /path/to/a/component/file.tsx: Missing class properties transform.
```

Some googling seems to suggest that [installing some other babel plugins](https://github.com/nrwl/nx/issues/3657#issuecomment-698898192) can solve this, but I don't see why that's not documented anywhere.

## Edit: my fix

1. `yarn add --dev @babel/plugin-proposal-class-properties`
2. in `.storybook/main.js`, add:

    ```js
    babel: async (options) => ({
      ...options,
      'plugins': [
        '@babel/plugin-proposal-class-properties'
      ]
    }),
    ```
    to the module exports.

**Comment by shilman** [comment]
closing as dupe to #14197
