### ISSUE TITLE
Typescript constructor arguments get thrown away (with example repo)

### ISSUE THREAD

**Issue by tobyhinloopen** [storybookjs/storybook#14515]
**Describe the bug**

Storybookjs's standard out-of-the-box compiler configuration for react typescript applications incorrectly compile Typescript code by removing some constructor bodies. Specifically, my class:

**my `time.ts` class**
```ts
export class Time {
  constructor(private time = 0) {
  }

  now() {
    this.time = (this.time || 0) + 1;
    return this.time;
  }
}
```

is compiled to:

**BROKEN JS code as generated by storybookjs**
```js
var Time = /*#__PURE__*/function () {
  function Time() {
    var time = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : 0;

    _classCallCheck(this, Time);
  }

  _createClass(Time, [{
    key: "now",
    value: function now() {
      this.time = (this.time || 0) + 1;
      return this.time;
    }
  }]);

  return Time;
}();
```

Note how `this.time = time` is missing. The correct JS code should be something like:

**CORRECT JS code as generated by default typescript compiler**
```js
export class Time {
    constructor(time = 0) {
        this.time = time;
    }
    now() {
        this.time = (this.time || 0) + 1;
        return this.time;
    }
}
```

**To Reproduce**

- Checkout my example repo here: https://github.com/charperbonaroo/sb-breaks-constructor
- `npm run storybook`
- Visit http://localhost:6006/?path=/story/example-now--primary

**Expected behavior**

- The shown source should somehow set `this.time` to `time`
- It should say **This: 9001 should be 9001.**

**System**

Environment Info:

```
  System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
  Binaries:
    Node: 15.11.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.6.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 89.0.4389.114
    Edge: Spartan (44.19041.423.0), Chromium (89.0.774.68)
  npmPackages:
    @storybook/addon-actions: ^6.2.5 => 6.2.5
    @storybook/addon-essentials: ^6.2.5 => 6.2.5
    @storybook/addon-links: ^6.2.5 => 6.2.5
    @storybook/react: ^6.2.5 => 6.2.5
```

**Comment by tannerlyons** [comment]
Seems like a dupe of https://github.com/storybookjs/storybook/issues/12019

**Comment by tobyhinloopen** [comment]
It is.
