### ISSUE TITLE
Global types added to the toolbar are illegible when using OSX dark theme

### ISSUE THREAD

**Issue by randak** [storybookjs/storybook#14513]
**Describe the bug**
The dropdown menu on the global types that are defined in the menu is displayed with black text on a black background when using a Mac with dark theme.

**To Reproduce**

1. Install the Storybook a11y add-on or define a global type
2. Set Mac to dark theme
3. Click on one of the menus in the toolbar
4. See that you cannot read anything

**Expected behavior**

The menu should not change background color when dark theme is set, or at least the text should also change color.

**Screenshots**
<img width="220" alt="Screen Shot 2021-04-05 at 3 26 39 PM" src="https://user-images.githubusercontent.com/2506770/113965625-f383a600-9857-11eb-80f3-30274e7f4f9b.png">

This one struck me as particularly ironic:
<img width="368" alt="Screen Shot 2021-04-08 at 10 49 11 AM" src="https://user-images.githubusercontent.com/2506770/113965702-1615bf00-9858-11eb-9aff-cf024023cf85.png">

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
Please paste the results of `npx sb@next info` here.
```
% npx sb@next info

Environment Info:

  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  Binaries:
    Node: 12.21.0 - /usr/local/opt/node@12/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.11 - /usr/local/opt/node@12/bin/npm
  Browsers:
    Chrome: 89.0.4389.114
    Safari: 13.1.3
  npmPackages:
    @storybook/addon-a11y: 6.2.2 => 6.2.2 
    @storybook/addon-actions: 6.2.2 => 6.2.2 
    @storybook/addon-essentials: 6.2.2 => 6.2.2 
    @storybook/addon-knobs: 6.2.2 => 6.2.2 
    @storybook/addon-links: 6.2.2 => 6.2.2 
    @storybook/addon-postcss: ^2.0.0 => 2.0.0 
    @storybook/addon-storysource: 6.2.2 => 6.2.2 
    @storybook/addons: 6.2.2 => 6.2.2 
    @storybook/react: 6.2.2 => 6.2.2 
    @storybook/source-loader: 6.2.2 => 6.2.2 
    @storybook/storybook-deployer: ^2.8.7 => 2.8.7 
    @storybook/theming: 6.2.2 => 6.2.2 
```

**Additional context**

**Comment by blankwavearcade** [comment]
Hi, I’d like to work this issue.

**Comment by shilman** [comment]
Thanks @blackwavearcade! 🙏

**Comment by randak** [comment]
@blankwavearcade Just want to confirm if you will still have time to work on this. If not, I can take a look over the weekend.

**Comment by tobiasljungstrom** [comment]
I am unable to reproduce this in the local development environment, in the `next` branch. My Mac is set to dark theme, but all the drop-downs are legible. If I switch Storybook itself to dark theme, the menus are black with white text. I tried this in Chrome, Safari, and Firefox.

**Comment by randak** [comment]
We traced this down to an incompatibility outside of the core Storybook project, so I'll close this issue.
