### ISSUE TITLE
Adding `funding` to `package.json`?

### ISSUE THREAD

**Issue by paulrosania** [storybookjs/storybook#14514]
**Is your feature request related to a problem? Please describe**
We use `npm fund` to organize our open source sponsorships. I noticed Storybook accepts funding through Open Collective on GitHub, but not listed in `package.json`, so `npm fund` doesn't turn up Storybook.

**Describe the solution you'd like**
Add a link to Open Collective in packages' `package.json`. (It would need to be in subpackages, I believe, since the root `package.json` isn't installed, unless there's some Lerna magic.)

**Describe alternatives you've considered**
We are considering whether we need to do one-offs when we spot packages looking for funding that aren't listed in `npm fund`. We're worried that it would be very random whether we happen to notice these or not, so out of fairness to all open source builders we're hoping to drive our contributions entirely off `npm fund`.

**Are you able to assist to bring the feature to reality?**
Yes, although given the sensitive nature of money-related stuff I would feel awkward making these particular changes. 😳 

**Additional context**
Our contribution levels are extremely modest right now since we're just getting our company off the ground, but I'm hoping this change would attract other contributors as well.

**Comment by shilman** [comment]
@paulrosania sounds great! can you make a PR for this? would love to get this in.

**Comment by paulrosania** [comment]
PR is up! Sorry for the delay, I was intimidated by the number of packages. 😵

**Comment by shilman** [comment]
Son of a gun!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.3.0-alpha.11 containing PR #14647 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
