### ISSUE TITLE
Missing index.html, only on development mode, after 6.2.5 (had to downgrade to 6.2.3 to work)

### ISSUE THREAD

**Issue by vinpac** [storybookjs/storybook#14510]
**Describe the bug**
The index.html is not created in development mode on version 6.2.5. I had to downgrade to 6.2.3 for it to work. 

**To Reproduce**
1. Start a Typescript project with next.js
2. Run `npx sb init`
3. Run `npm run storybok`
4. Get a 404. If you look at node_modules/.cache ... (where storybook outputs ) you see there's no index.html there.
5. Now build it with `npm run build-storybook`
6. Check the static-storybook to see the index.html there

**Expected behavior**
Don't get a 404

**System**
Environment Info:

  System:
    OS: macOS 11.2.3
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  Binaries:
    Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.16.0/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v14.16.0/bin/npm
  Browsers:
    Chrome: 89.0.4389.114
    Safari: 14.0.3
  npmPackages:
    @storybook/addon-actions: 6.2.5 => 6.2.5 
    @storybook/addon-essentials: 6.2.5 => 6.2.5 
    @storybook/addon-links: 6.2.5 => 6.2.5 
    @storybook/addon-postcss: ^2.0.0 => 2.0.0 
    @storybook/react: 6.2.5 => 6.2.5

**Comment by shilman** [comment]
I wasn't able to repro this following the steps above. I used this typescript setup: https://dev.to/dewaleolaoye/how-to-setup-next-js-with-typescript-8lb

**Comment by cesarp** [comment]
I am getting the same thing, I upgraded a project from 5.x to 6.x and after downgrading to 6.2.3 it works. I can't share the source since it is a private project but I have custom typescript options, not sure if that makes a difference:

```javascript
{
            name: '@storybook/preset-typescript',
            options: {
                tsLoaderOptions: {
                    configFile: path.resolve(__dirname, '../tsconfig.storybook.json'),
                },
                forkTsCheckerWebpackPluginOptions: {
                    tsconfig: path.resolve(__dirname, '../tsconfig.storybook.json'),
                },
            },
        },
}
```
