### ISSUE TITLE
Angular Input setter/getter syntax with default options

### ISSUE THREAD

**Issue by RGunning** [storybookjs/storybook#14520]
**Describe the bug**

Setting a default argument for a component input that uses getter/setter syntax no longer sets the initial view correctly. The internal setter is called correctly, but the view doesn't re-render to match the input. This is despite a changeDetectionRef markForCheck or detectChanges.

However, once the initial render is done toggling the control will render correctly.

Inputs that don't use the getter/setter syntax update correctly and setting `angularLegacyRendering: false` also fixes the issue

**To Reproduce**
Steps to reproduce the behaviour:

See MWE: https://github.com/RGunning/storybook-bug-mwe/blob/master/stories/setter-bug.component.stories.ts

**Expected behaviour**
Default story values render correctly regardless of syntax

**Screenshots**

**Code snippets**
```ts
import { ChangeDetectionStrategy, ChangeDetectorRef, Component, Input } from '@angular/core';

@Component({
  selector: 'app-setter',
  template: `<div *ngIf="isDivShowing">This should show</div>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class SetterComponent {
  constructor(private cdr: ChangeDetectorRef) {}

  isDivShowing = false;

  @Input() set showDiv(value: boolean) {
    this.isDivShowing = !!value;
    this.cdr.detectChanges();
  }
  get showDiv() {
    return this.isDivShowing;
  }
}
```

```ts
import { Meta, Story } from '@storybook/angular/types-6-0';

import { SetterComponent } from './setter-bug.component';

export default {
  title: 'Setter Bug',
  component: SetterComponent,
} as Meta;

const Template: Story<SetterComponent> = (args: SetterComponent) => ({
  moduleMetadata: {
    declarations: [SetterComponent],
  },
  template: ` <app-setter [showDiv]="showDiv"></app-setter>`,
  props: args,
});

export const ShowDiv: Story<SetterComponent> = Template.bind({});
ShowDiv.args = {
  showDiv: true,
};
```

**System**
```
Environment Info:

  System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v14.16.0/bin/npm
  Browsers:
    Chrome: 89.0.4389.114
    Firefox: 87.0
    Safari: 14.0.3
  npmPackages:
    @storybook/addon-actions: ^6.2.5 => 6.2.5 
    @storybook/addon-essentials: ^6.2.5 => 6.2.5 
    @storybook/addon-links: ^6.2.5 => 6.2.5 
    @storybook/angular: ^6.2.5 => 6.2.5 
```

**Additional Context**

This also appears to be an issue when using addon-docs inlineStories. InlineStories also don't seem to respect the `angularLegacyRendering: false` option and need to be disabled separately `docs: { inlineStories: false },` to fix this getter/setter bug.

**Comment by ThibaudAV** [comment]
same 🙈 
@yngvebn what do you think? It's always the same confusion with compodoc -> agrs -> props which overloads angular components?

**Comment by ThibaudAV** [comment]
@RGunning can you try this : 

Make sure that you do not directly pass all `args` in your story `props`
prefer a "destructuring" to control them : 
```
const Template: Story<SampleComp> = (args) => ({
  props: {
  input1: args.input1
  },
});
```

**Comment by RGunning** [comment]
@ThibaudAV that seems to fix it. 

Another fix that works is to add  ` /** @ignore */` to the other properties so that compodoc ignores them

e.g.
```ts
@Component({
  selector: 'app-setter',
  template: `<div *ngIf="showDiv">This should show</div>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class SetterComponent {
  constructor(private cdr: ChangeDetectorRef) {}

  /** @ignore */
  private isDivShowing = false;

  @Input() set showDiv(value: boolean) {
    this.isDivShowing = !!value;
    this.cdr.markForCheck();
  }
  get showDiv() {
    return this.isDivShowing;
  }
}
```

**Comment by ThibaudAV** [comment]
I had also seen this : 
```
"docs:json": "compodoc -p ./src/app/tsconfig.app.json -e json -d . --disablePrivate --disableProtected --disableLifeCycleHooks --disableInternal",
```
> https://discord.com/channels/486522875931656193/490770949910691862/824312399884582942

**Comment by RGunning** [comment]
modifying the docs:json works nicely

**Comment by shilman** [comment]
Yee-haw!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.3.0-alpha.18 containing PR #14769 that references this issue. Upgrade today to the @next NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by RGunning** [comment]
@shilman @ThibaudAV Possibly found a new bug with this fix for a specific setup. When I have a component extending another component with @inputs the parent @inputs are now stripped from the args.

Workaround is to explicitly add the inherited inputs to the argTypes controls. I've not been able to setup a MWE for this though, so might be something specific with our setup.

I'll keep investigating, but in general this fix is an improvement and there is a workaround, so not a blocker.

**Comment by gmfun** [comment]
Using the following script to fix it

```javascript
const fs = require('fs')
const doc = require('./documentation.json');
const comp = doc.components.map((c) => {
    return {
        ...c,
        inputsClass: c.inputsClass.map((i) => {
            if (i.type === '') {
                i.type = c.accessors?.[i.name]?.setSignature?.args?.[0].type || 'any'
            }
            return i
        })
    }
});
const newDoc = {
    ...doc,
    components: comp
}
fs.writeFileSync('./documentation.json', JSON.stringify(newDoc, undefined, 4))
```

**Comment by ThibaudAV** [comment]
@shilman I think we can close this issue
