### ISSUE TITLE
vue-docgen-api: failed to parsed when exported component use "as" with typescript

### ISSUE THREAD

**Issue by mercs600** [storybookjs/storybook#14524]
**Current behavior**
We have exported components this way (for better typing extended components with composition api)
```ts
import { defineComponent } from '@vue/composition-api'
import CeHeader from './CeHeader'

const CeHeaderTheme = defineComponent({
  extends: CeHeader
})

export default CeHeaderTheme as typeof CeHeader
```

But this way of exporting causes warnings in storybook: 
```
[vue-docgen-loader] failed to parse the component file with docgen-api: No suitable component definition found on...
```

**To reproduce**

Just export some component as default and add some as typeof operator:

```ts
export default {
  name: 'Test'
} as {
  name: string
}
```
**Expected behavior**

I would like to use "as" operator without any warnings.

**Comment by shilman** [comment]
Might this issue be better filed here? https://github.com/vue-styleguidist/vue-styleguidist

cc @elevatebart

**Comment by mercs600** [comment]
@shilman I have tried -> https://github.com/vue-styleguidist/vue-styleguidist/issues/1066 -> but I got any help from their side, I'm wondering is it any workaround ?

**Comment by elevatebart** [comment]
Hello @mercs600,

I just answered you ticket on vsg. I know I am not hyper responsive on it. I have been a bit blindsided by parenthood.

I hope you get to send a PR soon. This would help a ton of people.

**Comment by mercs600** [comment]
@elevatebart  I saw your changes in your repository, I have tested it with my current code base and it works great. I have crated PR to storybook to bump your package in this repository. Thank you for your time ❤️

**Comment by shilman** [comment]
Ermahgerd!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.3.0-alpha.6 containing PR #14567 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

**Comment by mercs600** [comment]
@shilman I love open source cooperation like this. It works like a charm.
