### ISSUE TITLE
controls: Boolean props interpreted as strings for radio control

### ISSUE THREAD

**Issue by ajkl2533** [storybookjs/storybook#14521]
**Describe the bug**
After upgrade to v6.2 I started to see warnings in the console `Received illegal value for '{{propName}}'. Supported options: 'false', 'true'`. I was used to that boolean props are interpreted as `radio` control type, but it was using at least real `true` and `false` values (not strings).

**To Reproduce**

1. Clone https://github.com/securityscorecard/design-system
1. Run storybook with `yarn storybook`
1. Open storybook in browser and console
1. Navigate to `http://localhost:8008/?path=/story/components-datatable-internalcomponents-table--with-disabled-selection`

**Expected behavior**
Boolean prop should be interpreted as values not as strings. Also would be nice that boolean props are interpreted as `boolean` control type instead of `radio`.

**Screenshots**
![](https://user-images.githubusercontent.com/18654425/114052593-76bfee80-988e-11eb-858e-81a1975fa9f5.png)

**System**

```
Environment Info:

  System:
    OS: macOS 11.2.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 7.8.0 - ~/Downloads/design-system/node_modules/.bin/npm
  Browsers:
    Chrome: 89.0.4389.114
    Safari: 14.0.3
  npmPackages:
    @storybook/addon-a11y: ^6.2.3 => 6.2.3 
    @storybook/addon-actions: ^6.2.3 => 6.2.3 
    @storybook/addon-backgrounds: ^6.2.3 => 6.2.3 
    @storybook/addon-controls: ^6.2.3 => 6.2.3 
    @storybook/addon-docs: ^6.2.3 => 6.2.3 
    @storybook/react: ^6.2.3 => 6.2.3 
    @storybook/theming: ^6.2.3 => 6.2.3 
```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1199622255231368/1200170832053915) by [Unito](https://www.unito.io)

**Comment by shilman** [comment]
I think what's going on here is an unintentional breaking change in the way argTypes are extracted for React/Typescript. Specifically, there are changes to the default `reactDocgenTypescriptOptions` configuration:

```js
    // NOTE: this default cannot be changed
    savePropValueAsString: true,
```

In your repo, you're overriding the settings so the new 6.2 config changes are not getting applied, and downstream 6.2 code is breaking because of it.

I think we should:
- [ ] Update `MIGRATION.md`
- [ ] Update [the docs](https://storybook.js.org/docs/react/configure/typescript#mainjs-configuration) with the new defaults

@tmeasday WDYT?

**Comment by tmeasday** [comment]
@ajkl2533 - I am not seeing the problem you've outlined -- I followed the steps you mentioned above and I don't see any browser warnings:

<img width="2401" alt="image" src="https://user-images.githubusercontent.com/132554/114119089-585d0000-992d-11eb-9412-9551aca069cd.png">

Perhaps you might try the old blowing away and reinstalling `node_modules`?

**Comment by shilman** [comment]
@tmeasday he probably fixed it already. from discord:

> So i was playing with the docgen options and it's cause by shouldExtractValuesFromUnion, it seems to be working with other options

**Comment by ajkl2533** [comment]
@tmeasday I found the source but I didn't commit it yet. I'll try to refresh node_modules

**Comment by unicornware** [comment]
@shilman presetting `savePropValueAsString` forces me to add extra and in most cases unwanted logic (e.g: converting strings into booleans, functions as `defaultProps` values) to some of my components. is there any way to get around this without me having to mess with my webpack config?

**Comment by Loic57** [comment]
Same here, all my bools props are shown like this in the browser <my-button disabled="false" /> whereas I would like something like <my-button disabled />

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).

**Comment by loremru** [comment]
Same for 8.6.14 with shouldExtractValuesFromUnion

<img width="1093" height="97" alt="Image" src="https://github.com/user-attachments/assets/167f7194-31f7-4465-ab49-39be4d7a6f8f" />

```
typescript: {
    reactDocgen: 'react-docgen-typescript',
    reactDocgenTypescriptOptions: {
      shouldExtractLiteralValuesFromEnum: true,
      shouldExtractValuesFromUnion: true,
      tsconfigPath: './tsconfig.base.json',
    },
  }
```

if I remove `shouldExtractValuesFromUnion ` it become as boolean, but I need that prop too
