### ISSUE TITLE
Provide configuration option to set which stories apply to which storyshots test runs

### ISSUE THREAD

**Issue by Shane32** [storybookjs/storybook#14525]
## Summary
I'm using addon-storyshots with puppeteer to create visual regression tests for a variety of devices/resolutions of a React app.  However, many storyshots do not need to be created for certain resolutions.  For example, a simple component (e.g. a button) need only be rendered once with a predefined viewport, where as the homepage view should be rendered multiple times for multiple devices.  Also some variations of a page are only applicable to a mobile device, and do not need to be rendered at each of several resolutions.

## Describe the solution you'd like
I would like to be able to configure a predicate on the storyshots test runner to check if a given story should be executed, like this:

```typescript
initStoryshots({
  suite: 'iPhone 11',
  // your own configuration
  test: imageSnapshot({
    // invoke the function above here
    getMatchOptions: (arg) => {
        const fileName = (arg.context as any).fileName;
        const snapshotPath = path.join('./_image_snapshots', path.dirname(fileName));
        return { customSnapshotsDir: snapshotPath };
    },
    storybookUrl: `file://${path.resolve(__dirname, '../storybook-static')}`,
    customizePage: (page) => page.emulate(devices['iPhone 11']),
  }),
  // new property here
  testShouldRun: (context) => context.story.parameters.testOn !== 'desktop',
});
```

I would then add a property to the story like this:

```typescript
const Template: Story<{}> = (args) => <App {...args} />;

export const Demo = Template.bind({});
Demo.args = {};
Demo.parameters = { testOn: 'desktop' };
```

## Describe alternatives you've considered
First, I would like to confirm that running `initStoryshots` multiple times in the test runner (for each viewport/device) is correct.  I could not find any documentation to show a recommended approach.

See: https://github.com/Shane32/VisualRegressionTestingSample/blob/master/src/storybook.test.ts

I have been able to successfully create my own workaround in this manner:

```typescript
const imageSnapshotTemp = imageSnapshot({
    // invoke the function above here
    getMatchOptions: (arg) => {
        const fileName = (arg.context as any).fileName;
        const snapshotPath = path.join('./_image_snapshots', path.dirname(fileName));
        return { customSnapshotsDir: snapshotPath };
    },
    storybookUrl: `file://${path.resolve(__dirname, '../storybook-static')}`,
    customizePage: (page) => page.emulate(devices['iPhone 11']),
});
const imageSnapshotTemp2: StoryshotsTestMethod = (context) => {
    if (context.story.parameters.showOn === 'desktop') {
        if (context.done) context.done(); //???
        return Promise.resolve();
    }
    return imageSnapshotTemp(context);
};
imageSnapshotTemp2.afterAll = imageSnapshotTemp.afterAll;
imageSnapshotTemp2.beforeAll = imageSnapshotTemp.beforeAll;
initStoryshots({
    suite: 'iPhone 11',
    // your own configuration
    test: imageSnapshotTemp2,
});
```

It feels like an ugly hack.

## Are you able to assist to bring the feature to reality?
I would be happy to post a PR, but I would need some direction as to where the code changes need to be made.  I'm not familiar at all with the codebase.

## Additional context
I created an entire sample project demonstrating my use case here:

https://github.com/Shane32/VisualRegressionTestingSample

You can view all of my configuration and setup.  It's a React site created with create-react-app which uses lazy loading, sass, and sass modules.  PRs against the repo will automatically run the visual regression tests on a Windows-based GitHub Action workflow.

**Comment by ndelangen** [comment]
The future of storyshots is the test-runner:
https://storybook.js.org/docs/react/writing-tests/test-runner#page-top

And use the play function for expectations:
https://storybook.js.org/docs/react/writing-stories/play-function#page-top

We will not be making any improvement / changes to storyshots.

**Comment by Shane32** [comment]
So just for clarification, is visual regression testing being removed from Storybook?  Your current documentation says:

> For a self-managed alternative to Chromatic, we offer [StoryShots](https://github.com/storybookjs/storybook/tree/main/addons/storyshots). It allows you to run visual tests on stories by integrating with [jest-image-snapshot](https://github.com/storybookjs/storybook/tree/main/addons/storyshots/storyshots-puppeteer#imagesnapshots).

See: https://storybook.js.org/docs/react/writing-tests/visual-testing

Just FYI, we have no need or desire for functional testing.  We only require visual regression testing, and have found StoryShots to work quite well.  Each time code is pushed to our repo, automated CI checks create 200+ visual snapshots which are pushed to the PR, and GitHub then displays the visual differences for any pages visually affected by the PR.

Thanks!!

**Comment by ndelangen** [comment]
No it's not removed, but storyshots is getting replaced by the test-runner.
The docs are just lagging behind a bit.

We'll do easy fixes, low risk changes as they come in, and security patches, but active development on storyshots has stopped.

The test-runner also supports hooks for adding visual regression testing, a11y testing etc.

**Comment by Shane32** [comment]
Thanks for the update.  I'll be looking forward to updated documentation and/or a sample application demonstrating the current recommended pattern for visual regression testing with Storybook.

**Comment by joriswitteman** [comment]
Just want to be sure you're aware that you're dropping the following major functionality that along with StoryShots that is not offered in the test runner: **_Coverage of different Controls settings_** for each Story.

The test runner doesn't offer any kind of functionality around this. I'm spending days now trying to make this work in the test runner and/or via decorators. Others are trying to [create add-ons](https://github.com/daimresearch/sb-addon-permutation-table) for this.

This aside, as long a StoryShots is offered through documentation, I would that it works at least. I [cannot get StoryShots to work](https://github.com/storybookjs/storybook/issues/22142) at all at this time.

**Comment by WouterBos** [comment]
> as long as StoryShots is offered through documentation, I would expect that it works at least. I https://github.com/storybookjs/storybook/issues/22142 at all at this time.

Same here. I have a hard time getting StoryShots to work. Now it looks like it's not maintained anymore. If true, it would be nice that users are warned about this state in the documentation.
