### ISSUE TITLE
Storybook 6.2.7 Unusable with ngOnDestroy takeUntil(this.destroyed$) pattern.

### ISSUE THREAD

**Issue by haileyambition** [storybookjs/storybook#14533]
**Describe the bug**
Existing working stories regress when upgrading to 6.2.7 tracked to 
Storybook 6.2.7 Unusable with ngOnDestroy takeUntil(this.destroyed$) pattern.

**To Reproduce**
1. Create story for simple component referenced in Code snippets section.
2. Click on story and click off story.
3. See error

**Expected behavior**
No failure to unsubscribe errors shall appear and continue to support angular common unsubscribe pattern. 

**Screenshots**

**Code snippets**
`
destroyed$: Subject<boolean> = new Subject<boolean>();
ngOnDestroy(): void {
this.destroyed$.next(true);
}
get something$(): Observable<boolean> {
        return this.facade.condition$.pipe(
            takeUntil(this.destroyed$)
        );
    }
`

**System**
Environment Info:

  System:
    OS: macOS 11.2.2
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
  Binaries:
    Node: 14.16.0 - /usr/local/bin/node
    npm: 6.14.11 - /usr/local/bin/npm
  Browsers:
    Chrome: 89.0.4389.114
    Firefox: 87.0
    Safari: 14.0.3
  npmPackages:
    @storybook/addon-a11y: ^6.1.21 => 6.1.21
    @storybook/addon-actions: ^6.1.21 => 6.1.21
    @storybook/addon-essentials: ^6.1.21 => 6.1.21
    @storybook/addon-links: ^6.1.21 => 6.1.21
    @storybook/angular: ^6.1.21 => 6.1.21

Note: I had reverted the upgrade prior to writing this ticket.

**Additional context**
From my perspective this seems to be related to using get properties that leverage takeUntil in the templates of components that have stories.

**Comment by shilman** [comment]
As a workaround have you tried using the legacy angular renderer?

https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#new-angular-renderer

**Comment by haileyambition** [comment]
That and some import updates takes care of the issue entirely.  Apologies for not seeing it on my own this is not an issue.  Does this however mean that at v7 storybook will no longer work with Angular?

**Comment by haileyambition** [comment]
I am seeing these now though.

`
vendors~main.manager.bundle.js:24664  manager  received storybook/docs/snippet-rendered but was unable to determine the source of the event
vendors~main.manager.bundle.js:24664  manager  received storyRendered but was unable to determine the source of the event
`

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid.

Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
