### ISSUE TITLE
### Storybook did not show the argsTable for my **HOC** propTypes

### ISSUE THREAD

**Issue by nitesh3539** [storybookjs/storybook#14530]
### Storybook did not show the argsTable for my **HOC** propTypes

is there any other approach to do this apart from above approach?

```
Marker.jsx -->

/**
 * A decorative element which can be used to highlight the most important information in a card.
 * It can be used by attaching itself on the any side of the card or in the middle of the card.
 */
export const Marker = withScales(styled(Base)`
  border-radius: ${borderRadiusStyles};
  background: ${appearanceStyles(markerAppearances)};
`);
Marker.defaultProps = {
  componentName: 'Marker',
};
Marker.propTypes = {
  direction: PropTypes.oneOf(directions).isRequired,
  corner: PropTypes.oneOf(corners).isRequired,
  appearance: PropTypes.oneOf(appearances).isRequired,
  height: PropTypes.string.isRequired,
  width: PropTypes.string.isRequired,
};

Marker.stories.js --->

export default {
  title: 'Components/Atoms/Marker',
  component: Marker,
};

```
System:
OS: macOS 11.2.3
Binaries:
Node: 12.7.0
npm: 6.10.0
Browsers:
Chrome: 77.0.3865.120
npmPackages:
"@storybook/addon-links": "^6.0.22",
"@storybook/addon-storysource": "^6.0.22",
"@storybook/addons": "^6.0.22",
"@storybook/react": "^6.0.22",
![077FD762-9F25-49B4-A708-47F15FF00987_1_201_a](https://user-images.githubusercontent.com/29592029/113993076-ad3b4080-9871-11eb-96ba-c4e9dd8f44c3.jpeg)

_Originally posted by @nitesh3539 in https://github.com/storybookjs/storybook/issues/12576#issuecomment-815570979_

**Comment by shilman** [comment]
closing as dupe to  #12576
