### ISSUE TITLE
Support a before method in `axeTest` to allow page customization before the test is run

### ISSUE THREAD

**Issue by coreyjv** [storybookjs/storybook#14536]
**Is your feature request related to a problem? Please describe**

I would like the ability to modify the page before accessibility test is run using `addon-storyshots-puppeteer`. This would allow me to modify the DOM to say add a class that may change the UI prior to test execution.

**Describe the solution you'd like**

`imageSnapshot` has a `beforeScreenshot` callback. I would like the same thing with the appropriate name.

**Describe alternatives you've considered**

None

**Are you able to assist to bring the feature to reality?**

Yes

**Comment by shilman** [comment]
Great Caesar's ghost!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.3.0-alpha.15 containing PR #14563 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
