### ISSUE TITLE
Canvas empty when adding ThemeProvider v6

### ISSUE THREAD

**Issue by ScottAgirs** [storybookjs/storybook#14547]
**Describe the bug**
After following the docs and adding Theme provider via `addDecorator(withThemesProvider(themes), ThemeProvider);` the canvas renders white screen.

**Screenshots**
What happens:
![visual](https://user-images.githubusercontent.com/11737572/114282569-a7c92c00-9a12-11eb-8da9-f8afbce59575.gif)

Browser console:
<img width="1016" alt="browser console output" src="https://user-images.githubusercontent.com/11737572/114282579-b0216700-9a12-11eb-8317-dbe67821667c.png">

Terminal output:
<img width="415" alt="terminal output" src="https://user-images.githubusercontent.com/11737572/114282583-b3b4ee00-9a12-11eb-89c8-fe877e738c2e.png">

**Code snippets**
### preview.js
```javascript
import { addDecorator } from "@storybook/react";
import { withThemesProvider } from "storybook-addon-styled-component-theme";
import { ThemeProvider } from "styled-components";

const theme = {
  name: "default",
}

const themes = [theme];
addDecorator(withThemesProvider(themes), ThemeProvider);

export const parameters = {
  actions: { argTypesRegex: "^on[A-Z].*" },
  controls: {
    matchers: {
      color: /(background|color)$/i,
      date: /Date$/,
    },
  },
}
```

**Comment by ScottAgirs** [comment]
Okay, so this is embarrassing, my apologies, working between multiple projects looks like one of the lines got lost.

### .storybook/main.js
```js
module.exports = {
  ...
  addons: [
    ...
    "storybook-addon-styled-component-theme/dist/preset"
  ]
};
```

Perhaps as a feature request, there's a way to add some sort of warning or check that this addon is present, not sure if possible.

Either way @shilman, thanks for tagging this, since it's solved, closing this.

**Comment by shilman** [comment]
Thanks @ScottAgirs -- I think there is a warning in the CLI if a preset fails to load?

**Comment by ScottAgirs** [comment]
Ahh, fair enough, there are indeed some warning containing this
