### ISSUE TITLE
Add ability to set Vue.js 2 state directly

### ISSUE THREAD

**Issue by doutatsu** [storybookjs/storybook#14544]
**Is your feature request related to a problem? Please describe**
There are many instances, where using props is not enough to set a particular state of the component. For example, if I have a `watcher` that watches a change in a `prop`, let's say visibility of a modal. I can't have the story in a particular state, without manually switching that prop.

Another example, is fetching some data, that is then stored inside the local state. Currently, I have to mock everything in a `loader`, just to add that external data. It would be much easier, to just directly set the state, without having to mock anything.

**Describe the solution you'd like**
I way to directly set the state of the Vue.js component, whatever through `args` or `loaders`. This way, it will be possible to make the component state exactly what you want, when you visit the story, without having to hack things around

**Describe alternatives you've considered**
The only alternative is to make everything a prop and control the component that way. This is not even an alternative, as it completely destroys the purpose of prop and local state separation. Controlling how the component looks just through `args` is extremely limiting at the moment

**Are you able to assist to bring the feature to reality?**
No

**Additional context**

**Comment by shilman** [comment]
@doutatsu If it's an option, the way we handle args in `@storybook/vue3` with Vue 3's `setup` function is a lot more flexible.

**Comment by doutatsu** [comment]
Unfortunately, I am on Vue 2 and unable to upgrade just yet. But I'll keep it in mind, that it is easier to make it happen in Vue 3. Could you point me to an example as to how that is handled in Vue 3?

**Comment by shilman** [comment]
There's an example here. You need to click over to the "Vue 3" tab.

https://storybook.js.org/docs/vue/writing-stories/args#args-can-modify-any-aspect-of-your-component

And I think there might be a typo in that example @jonniebigodes @phated -- it should be `setup() { return args; }`, no?

**Comment by merceyz** [comment]
That should be possible in Vue 2 using https://github.com/vuejs/composition-api as well right?

**Comment by doutatsu** [comment]
@merceyz I am not familiar with composition API, so not sure if I can. But regardless of that, I don't want to rewrite my components to use it, just to make this work I am afraid
