### ISSUE TITLE
ArgsTable Not Rendered For React Class Components

### ISSUE THREAD

**Issue by KenACollins** [storybookjs/storybook#14541]
**Describe the bug**
In a MDX story file (*.stories.mdx) utilizing Storybook Docs in version 6, the ArgsTable will not render at all if the component is coded as a class, even if the PropTypes and defaultProps declarations have been pulled out of the class, where they were defined as static blocks, and placed below the class in the same component file and renamed with the component name preceding them as in ComponentName.propTypes and ComponentName.defaultProps. This issue is related to [this discussion about the controls table](https://github.com/storybookjs/storybook/discussions/14133).

**To Reproduce**

1. Make sure you are running a React application that has been set up with Storybook 6. It does not matter if the release is 6.0.21, 6.1.21, or 6.2.1. *It may not even matter if it is a React app, I suppose pure JavaScript classes are impacted but my focus is on React.*
2. Create a React class component, e.g. MyClass, and define `MyClass.propTypes` and `MyClass.defaultProps` with a few props. At the bottom of the file, `export { MyClass, }`.
2. Create a MyClass.stories.mdx file where you import MyClass and include this line: `<ArgsTable of={MyClass} />`.
3. Start Storybook dev server if not running and refresh the page for the MyClass component.
4. Switch to the **Docs** tab and take note that there is an embedded block with message *No inputs found for this component.* where the args table should appear.

Now, for comparison, repeat the above steps but this time do it for a React functional component. You will find that the args table renders just fine listing all possible props you defined.

**Expected behavior**
ArgsTable should render for a class component just as it does for a function component.

**Additional context**
I provided react-docgen output of two versions of a component, one class and one function, in this aforementioned [discussion about the controls table](https://github.com/storybookjs/storybook/discussions/14133) and the results were not promising so this may be a challenging problem to solve.

**Comment by asso1985** [comment]
We are having the same issue here, any update?

**Comment by asso1985** [comment]
Any news on this?

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
