### ISSUE TITLE
Bind template and arguments helper

### ISSUE THREAD

**Issue by Bram-Zijp** [storybookjs/storybook#14551]
**Is your feature request related to a problem? Please describe**
Most of my stories just need to render with x props, so I've learned using the latest version of storybook 6.2+ (nice!). To save some lines of code, I created this quick and dirty helper. It's not perfect but it works for me now. Perhaps it's an idea to include something like this into storybook.

**Describe the solution you'd like**
```
import { Story } from "@storybook/react";

type BindTemplate<P = any> = <T extends Story<P>>(
  template: T,
  args: T["args"]
) => T & { args: T["args"] };

export const bindTemplate: BindTemplate = (template, args) => {
  const boundTemplate = (template as any).bind({});
  boundTemplate.args = args;
  return boundTemplate;
};


import React from "react";
import { Meta, Story } from "@storybook/react";
import { bindTemplate } from "$utils/stories";
import { Box, BoxProps } from "./";

const config: Meta = {
  title: "Components/Box",
  component: Box,
};

export default config;

const Template: Story<BoxProps> = (args) => <Box {...args}>Box</Box>;

export const Primary = bindTemplate(Template, {
  className: "valid",
});

export const Secondary = bindTemplate(Template, {
  sx: { background: "blue" },
});
```

**Describe alternatives you've considered**

**Are you able to assist to bring the feature to reality?**
yes

**Additional context**

**Comment by shilman** [comment]
We have some other plans for this, outlined in #12654

**Comment by Bram-Zijp** [comment]
Nice, I like those plans. Closing in favor of #12654
