### ISSUE TITLE
Export getBlockBackgroundStyle from @storybook/components

### ISSUE THREAD

**Issue by AndrewLeedham** [storybookjs/storybook#14557]
**Is your feature request related to a problem? Please describe**
We are using `getBlockBackgroundStyle` to create various custom documentation component that fit in with the wider storybook theme. For example this little colour card thingy:
![image](https://user-images.githubusercontent.com/5557458/114381945-ab2ff500-9b83-11eb-9646-423baf6737cc.png)

pre-6.2 we used `import { getBlockBackgroundStyle } from '@storybook/components/dist/blocks/BlockBackgroundStyles';` to import it, and post-6.2 we use `import { getBlockBackgroundStyle } from '@storybook/components/dist/cjs/blocks/BlockBackgroundStyles';` to import it. We therefore don't get any typings and are exporting from dist, which is obviously not the intended API.

**Describe the solution you'd like**
Export `getBlockBackgroundStyle` defined here: https://github.com/storybookjs/storybook/blob/next/lib/components/src/blocks/BlockBackgroundStyles.tsx from the root `@storybook/components` package.

**Describe alternatives you've considered**
Sticking with what we have but given 6.2 required a change for how we do this, going forward a first-class API would be better.

**Are you able to assist to bring the feature to reality?**
Sure I can put a PR in, should the API just look like `import { getBlockBackgroundStyle } from '@storybook/components`;.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
