### ISSUE TITLE
Storybook not loading Browserstack for ie11

### ISSUE THREAD

**Issue by Greenie10** [storybookjs/storybook#14578]
**Describe the bug**
Either locally, or on production, the components within our instance of Storybook (https://www.findmypast.com/canopy) do not load in Browserstack to check ie11.  Other browsers in Browserstack work happily. It's only ie11 that will not load the components. The outer frame of Storybook shows, but the list of components - shown as skeletons - just throb, waiting to load.

**To Reproduce**
1. Either using the chrome extension for Browserstack, or going directly to their website
2. choose ie11 in Browserstack, 
3. try to view our Storybook (https://www.findmypast.com/canopy).
4. Components never load.

**Expected behavior**
I expect to see all components load in Storybook.

**Screenshots**
<img width="907" alt="Screenshot 2021-04-13 at 12 02 03" src="https://user-images.githubusercontent.com/1492173/114542697-22cb5600-9c50-11eb-812b-8e8ae1f85c7d.png">

**System**
  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  Binaries:
    Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
    Yarn: 1.22.10 - ~/GitHub/titan/node_modules/.bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v14.16.0/bin/npm
  Browsers:
    Chrome: 89.0.4389.114
    Firefox: 87.0
    Safari: 14.0.3
  npmPackages:
    @storybook/addon-a11y: 6.2.7 => 6.2.7
    @storybook/addon-essentials: 6.2.7 => 6.2.7
    @storybook/addons: 6.2.7 => 6.2.7
    @storybook/react: 6.2.7 => 6.2.7

**Additional context**
Our last version of Storybook was 6.0.20 and it did render in Browserstack ie11. Just updated to 6.2.7 today.

**Comment by shilman** [comment]
Is there an error in the browser console?

**Comment by Greenie10** [comment]
<img width="1034" alt="Screenshot 2021-04-13 at 16 15 26" src="https://user-images.githubusercontent.com/1492173/114576951-85821900-9c73-11eb-8fc0-cd3b133d89c9.png">

**Comment by Greenie10** [comment]
A colleage tried to load our storybook in real ie11, and this is a screenshot:
![image (6)](https://user-images.githubusercontent.com/1492173/114873423-2ea34d80-9df3-11eb-8fd0-83b88d32c329.png)

**Comment by mt9eet** [comment]
Hey @Greenie10, if you click on the `vendors-main...`, what does the debugger show you?

I'm encountering this issue as well. Mine is something with `acornJSX`, which was reported in https://github.com/storybookjs/storybook/issues/8884, and the error points exactly to [this](https://github.com/storybookjs/storybook/issues/8884#issuecomment-608456104)

The cause is:
> So, it certainly comes from addon-docs which uses acorn-jsx while not transpiling it, despite being written with ES6 classes

---

I will try to dig  deeper a bit and will report back if I can find a fix.

**Comment by mt9eet** [comment]
I found that the issue also comes from `react-refresh-webpack-plugin`.

They have made a fix [here](https://github.com/pmmmwh/react-refresh-webpack-plugin/pull/298), but it doesn't seem to be released yet.

**Comment by tsteuwer-accesso** [comment]
I'm having the same issue. It seems to be that the files are not being compiled into ES5. They're still using fatty arrow functions.

![Screenshot from 2021-08-06 15-40-43](https://user-images.githubusercontent.com/32495798/128563276-690e5d1c-06a1-493e-869f-bcefff4a1340.png)


![Screenshot from 2021-08-06 15-39-45](https://user-images.githubusercontent.com/32495798/128563251-48aff89f-0d2c-4f3a-ba7e-c2ccfd6ffecd.png)

**Comment by shilman** [comment]
If you're using `@storybook/addon-docs` there is a known incompatibility with IE11 there. Otherwise, 6.3.x is compatible as far as I know.

**Comment by shilman** [comment]
perhaps web-components specifically is not compatible. react with webpack4 is and we have tests for it.

**Comment by ndelangen** [comment]
Storybook 7.0 beta no longer supports IE11.
