### ISSUE TITLE
6.2.5 addons-action TypeScript Definitions No Longer Default Import Correctly

### ISSUE THREAD

**Issue by contrast-jeremiahp** [storybookjs/storybook#14571]
**Describe the bug**
When upgrading `@storybook/addons-action` from `6.1.21` to `6.2.5`, imports now result in a TypeScript error:
* E.g. `import { action } from @storybook/addon-actions/`
* Results in `TS2307: Cannot find module '@storybook/addon-actions/'.`
* Documentation used to import actions is based off the legacy usage https://github.com/storybookjs/storybook/blob/HEAD/addons/actions/ADVANCED.md

**To Reproduce**

1. Install @storybook/addon-actions@6.1.21 as a dependency in a TypeScript project
2. Write a simple TypeScript file importing the module. E.g.
![image](https://user-images.githubusercontent.com/51373394/114439918-880f4080-9b97-11eb-9de1-6051f370399a.png)
3. Notice no TypeScript Errors
4. Upgrade dependency to `@storybook/addon-actions@6.2.5`
5. See the TypeScript error
![image](https://user-images.githubusercontent.com/51373394/114440112-c0168380-9b97-11eb-9cc7-80f9f60729a9.png)

**Expected behavior**
TypeScript errors do not error when importing @storybook/addon-actions 

**Additional Context**
* I think this might have something to do with `addon-actions/dist` folder now including multiple dist folders for CommonJS, TS3.4, TS3.9, etc.
* In `@storybook/addon-actions@6.1.21`, the import is being resolved as `node_modules/@storybook/addon-actions/ts3.4/dist/index.d.ts`
* Ideally this work out of the box or additional configuration guidance should be provided in README's
![image](https://user-images.githubusercontent.com/51373394/114440705-72e6e180-9b98-11eb-9ec5-990d99ad26e0.png)

**Comment by shilman** [comment]
In your second snippet (5), there's a trailing slash. What happens if you remove that?

Here is the line that tells Typescript where to look for the types: https://github.com/storybookjs/storybook/blob/next/addons/actions/package.json#L22

**Comment by contrast-jeremiahp** [comment]
@shilman the issue still occurs in 6.2.5 with or without the trailing slash
![image](https://user-images.githubusercontent.com/51373394/114552379-8a72a880-9c32-11eb-9098-b699a99ac619.png)

**Comment by shilman** [comment]
Do you have a repro repo you can share?

**Comment by contrast-jeremiahp** [comment]
I tried reproducing this in a `react-create-app` but wasn't able to successfully create a quick project to share re-creating the issue.

For others who run into this, adding this snippet to `tsconfig.json` as a workaround solved the problem.

```
{
    ...
    "compilerOptions": {
            "@storybook/addon-actions": [
                "node_modules/@storybook/addon-actions/dist/ts3.9"
            ]
    }
```
