### ISSUE TITLE
React runtime automatic breaks MDX

### ISSUE THREAD

**Issue by fcisio** [storybookjs/storybook#14584]
**Describe the bug**
Using React runtime automatic breaks MDX stories.

> Overall the MDX syntax is really buggy on the latest releases.

Some work needs to be done on MDX, for it to remain a viable syntax to use.

**To Reproduce**

1. [Enable automatic runtime](https://github.com/storybookjs/storybook/issues/12881#issuecomment-715401423)
2. Write a MDX story

**Expected behavior**
MDX should still work with runtime automatic

![ScreenShot 2021-04-13 at 12 15 48 PM](https://user-images.githubusercontent.com/46095852/114585838-0defc200-9c52-11eb-84f9-adfdc41d14f3.png)

**System**
broke on all storybook versions

**Comment by shilman** [comment]
Do you have a repro repo you can share?

**Comment by fcisio** [comment]
I wasn't able to reproduce the error with `Title`, `Description` or `@storybook/components/html`

But I did reproduce two things (uncomment to test):
- MDX `argTypes` breaking the stories
- Runtime `importSource` breaking MDX

> The `importSource` is set to React, which is redundant, but it is to illustrate the issue. The issue would happen with anything else, ex: `Emotion JS`

[See Repro](https://github.com/fcisio/repro-storybook-mdx)

**Comment by fcisio** [comment]
Any progress on this?
Right now, I'm resorting to removing my MDX docs until this is supported.

From what I found,  MDX just doesn't support automatic runtime yet.

I did see [this workaround](https://github.com/mdx-js/mdx/issues/1441#issuecomment-786745109), which could work until it is supported on their end.

Thanks

**Comment by ndelangen** [comment]
@shilman I suspect this will be fixed in 7.0 with the MDX upgrade and changes we made.
