### ISSUE TITLE
Encountered two children with the same key on ColorItem 

### ISSUE THREAD

**Issue by pantelispanayiotou** [storybookjs/storybook#14580]
**Describe the bug**
When i pass an array with colors inside <ColorItem  colors={[]} /> and i have two or more identical colors then the error occurs and some values are getting duplicated on rerenders.

**To Reproduce**

1. Use ColorItem with one or more identical colors

**Expected behavior**
ColorItems should not be duplicated or at least provide an option to add keys to those colors

**Comment by shilman** [comment]
¡Ay Caramba!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.3.0-alpha.10 containing PR #14636 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
