### ISSUE TITLE
Ability to display argument as content for component

### ISSUE THREAD

**Issue by wszydlak** [storybookjs/storybook#14596]
**Is your feature request related to a problem? Please describe**
Lets say we have some component named: app-button.
We want content (children) of this component to be displated eg. as label:

```html
<app-button>Hello Button</app-button>
```

```ts
@Component({
  selector: 'app-button',
  template: '<ng-content></ng-content>'
})
export class AppButtonComponent {}
```

How can we pass prop which will correspond with `ng-content` and generate examples as given:

```ts
const Template: Story<ButtonArgs> = (args, context) => {
   return {
     props: {
       content: 'My Button' // how to pass property which will display dynamically as ng-content
     }
  }
}
```

**Describe the solution you'd like**
I would like to have ability to pass content which will be used as ng-content in my component.

**Describe alternatives you've considered**
I know I can create some property in `ButtonComponent` and use it instead of `ng-content`, but this will not give me correct code syntax in `Show code`. I would like to see code:

```html
<app-button>My Button</app-button>
```

**Additional info**
Maybe there exist option to do what i described, but i haven't found it in documentation.

**Comment by ThibaudAV** [comment]
you can use two way to do that : 

1. with template 
```js
const Template: Story<ButtonArgs> = (args, context) => {
   return {
   template: `<app-button>${args.content}</app-button>`,
     props: {
       content: 'My Button' // how to pass property which will display dynamically as ng-content
     }
  }
}
```

2. with `componentWrapperDecorator`
```js

const Template: Story<ButtonArgs> = (args, context) => {
   return {
     template: 'content' // args.content,
     props: {
       content: 'My Button' // how to pass property which will display dynamically as ng-content
     }
  }
}

export MyStory = Template.bind({})
MyStory.decorators = [componentWrapperDecorator(AppButtonComponent)];

```



se more exemple [here](https://github.com/storybookjs/storybook/tree/next/examples/angular-cli/src/stories/basics/component-with-ng-content) or [here](https://github.com/storybookjs/storybook/tree/next/examples/angular-cli/src/stories/core/decorators/componentWrapperDecorator)

**Comment by wszydlak** [comment]
Hi @ThibaudAV, 

1. Firstly - how can i achieve correct "Show code" syntax, cause as You can see in examples:

![image](https://user-images.githubusercontent.com/6583977/115235544-97a00380-a11a-11eb-88a6-bd15c96514cc.png)

I expected "Show code" to show something like:

```html
<parent-component>
  <child-component></child-component>
</parent-component>
```

2. Secondaly - how again can i do same thing assuming parent-component accepts multiple child components, or event nested?:

```html
<parent-component>
  <child-component></child-component>
  <another-child-component></another-child-component>
</parent-component>
```

```html
<parent-component>
  <child-component></child-component>
  <another-child-component-also-with-children>
    <some-nested-component></some-nested-component>
  </another-child-component-also-with-children>
</parent-component>
```

I need to have "Show code" autogenerate such examples without using `docs.source.code` parameter, cause I have components that accepts as children some other components as above, and many examples in my doc should give correct "Show code" snippet.

**Comment by ThibaudAV** [comment]
Hi,

1. 
the generated "Show code" always concerns the component or template of the story (template first) 

so it depends on the `default.component` or the `MyStroy.parameters = {component: MyComponent}` (for an override on a story)

if you want the grandparent to be in the "Show code" it must be part of the story component. you can either make an intermediate component or add it in the template

the `componentWrapperDecorator` is intended to decorate the story and allow it to evolve in different environments. not to complete it, i think

2. 
the safest way is to use a template with the html you want 🤔

**Comment by wszydlak** [comment]
I tried with template, but it is not displayed in "Show code".

It seems that using template have affect only on displaying component example, but "Show code" is not respecting template option, and still showing only component selector and inputs.

Also setting `component` to null in story does not help:

```ts
{
  props: {},
  template: '<my-component>Test</my-component>'
  component: null
}
```

Show code still displays:

```html
<my-component></my-component>
```

**Comment by ThibaudAV** [comment]
@wszydlak do you have a component in `export default` ?

**Comment by wszydlak** [comment]
You mean in story meta? If so then yes i have

**Comment by ThibaudAV** [comment]
yes , 

so it will be taken preferably 
https://github.com/storybookjs/storybook/blob/next/addons/docs/src/frameworks/angular/sourceDecorator.ts#L45

it is on this component that the doc will be targeted and the source code too 

to override it in strory you can try :

```

export MyStory = Template.bind({})
MyStory.parameters = {component: null};
```
:not-sure:

**Comment by wszydlak** [comment]
Works ! Thanks for your help 👍 

It works both with omitting component and when overwrite story parameter.

**Comment by manuelmeister** [comment]
@ThibaudAV wouldn't it make sense to have something like an innerTemplate anyway? Because there is no way to actually use `story.template` and `story.args` together.

**Comment by ThibaudAV** [comment]
@manuelmeister yes, both can be used together. you need to pass agrs to props

like : 
```
const Template = ({ argA }, context) => {
   return {
     template: `{{ propFromArgA }}`,
     props: {
       propFromArgA: argA
     }
  }
}
```

**Comment by manuelmeister** [comment]
But that means this is always included in the template, right? Because if I don't set argA (because for instance it's the default value of argA in the component anyway), then it will be set in the story source regardless?

**Comment by ThibaudAV** [comment]
Do you use compodoc? I recommend not to use it because it does not work well and does not allow to manage the args finely

**Comment by ThibaudAV** [comment]
this not work in angular i think 
```
const Template: Story<AppButton> = (args) => ({
  template: `<button app-button [size]="args.size" [variant]="args.variant">Content</button>`,
});
export const Primary = Template.bind({});
Primary.args = { size: 'large' };
```ts

when you use template for angular you should imagine that you are creating an angular component and props represents the properties of that component


```
const Template: Story<AppButton> = (args) => ({
  template: `<button app-button [size]="_size" [variant]="_variant">Content</button>`,
  props: {
    _size: args.size,
   _variant: args.variant
  }
});
export const Primary = Template.bind({});
Primary.args = { size: 'large' };
```ts

**Comment by manuelmeister** [comment]
@shilman wouldn't it make sense to give Angular Stories a way to add content between component tags without needing a defined `story.template` for it. The foundation for this would already be in place.

I would suggest adding an `innerTemplate` or an `ngContent` to the [StoryFnAngularReturnType](https://github.com/storybookjs/storybook/blob/next/app/angular/src/client/preview/types.ts#L22-L32). This would then replace the empty string in: [decorateStory.ts](https://github.com/storybookjs/storybook/blob/next/app/angular/src/client/preview/decorateStory.ts#L42), [StorybookModule.ts](https://github.com/storybookjs/storybook/blob/ad08d92bc77c5d4a573de07183900d9c778e25f8/app/angular/src/client/preview/angular-beta/StorybookModule.ts#L50), [ComputesTemplateFromComponent.ts](https://github.com/storybookjs/storybook/blob/ad08d92bc77c5d4a573de07183900d9c778e25f8/app/angular/src/client/preview/angular-beta/ComputesTemplateFromComponent.ts#L135).

For components (like buttons) that normally don't use any input for the inner text, but simply phrasing content/ngContent, the computed/args template would be usable this way as well. That would be very cool.

I could try to add this in a PR if you think this a good idea as well.

**Comment by shilman** [comment]
@manuelmeister I'm not knowledgable about Angular. @ThibaudAV @kroeder can hopefully give feedback and help you make that happen!

**Comment by manuelmeister** [comment]
@ThibaudAV & @kroeder what do you think about innerTemplate?

**Comment by manuelmeister** [comment]
@shilman I think this is possible, at least in Angular. Is the "autogeneration" of the code example a feature only angular has or do Vue and React have something like this as well? Because if so the CSF format would need to change.
