### ISSUE TITLE
Possible to add custom source to an inline `<Canvas>`? 

### ISSUE THREAD

**Issue by chadlavi-casebook** [storybookjs/storybook#14599]
**Is your feature request related to a problem? Please describe**

I would like to be able to pass custom source code to display in the `<Source>` for an inline `<Canvas>` used in an MDX document.

This is useful if, for example, you need to use a React Hook in the code that runs in the Canvas, which necessitates defining a separate component to use inside the Canvas. 

Source code like this: 

```tsx
<MyExample />
```

is useless, but if I could pass custom source code (the guts of the definition of `MyExample`) to the `<Canvas>`, that would be great.

I know this is already possible to do with Stories, so I suspect it's possible to do with a one-off inline `<Canvas>` as well, but the documentation for the props of `Canvas` are scant to nonexistent. The only place it's mentioned anywhere in Storybook docs gives only a very facile example with no props at all passed to the Canvas except for children.

Here's a screenshot of the issue I'm experiencing with this currently: 

![image](https://user-images.githubusercontent.com/45078010/114743653-df89e980-9d1a-11eb-8be0-162550edeab0.png)

The source code there being

```mdx
### Breakpoint values

The name of the current breakpoint range of the user's browser window can be accessed in code with the `useBreakpoint()` hook exported in the Design System library.

<Canvas>
  <UseBreakpointExample />
</Canvas>
```

and `UseBreakpointExample` is defined in a separate tsx file as: 
```tsx
export const UseBreakpointExample = () => {
  const breakpoint = useBreakpoint()
  return (
    <Layout display='flex' alignItems='center' justifyContent='center'>
      <Typography>
        Your current browser breakpoint is{' '}
        <Typography inline highlight='active' monospace>
          {breakpoint}
        </Typography>
      </Typography>
    </Layout>
  )
}
```

^ that's the source code I'd prefer to pass to the `<Canvas>`.

**Describe the solution you'd like**
* document the props of Canvas
* if one doesn't already exist, add a prop to allow for passing custom source code to display in the Source block of an inline Canvas

**Comment by as-zlynn-philipps** [comment]
@chadlavi-casebook did you ever figure this out?

**Comment by chadlavi-casebook** [comment]
@as-zlynn-philipps nope! I ended up just turning off the source code for the canvas entirely (by passing `withSource='none'`) and providing source code separately, which is dumb and manual, but works.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).

**Comment by atlj** [comment]
Seems like you can use the `source` prop now

```jsx
<Canvas
  source={{
    code: `// My custom source`
  }}
  of={RadioStories.Default}/>
```

https://storybook.js.org/docs/react/api/doc-block-canvas#source
