### ISSUE TITLE
Storybook 6.2.8 Docs blocks (Description, ArgsTable) not working with React monorepo

### ISSUE THREAD

**Issue by robcaldecott** [storybookjs/storybook#14595]
**Describe the bug**
I am having a problem getting `Description` and `ArgsTable` to work with some of my React components in a `lerna` monorepo (although I am not convinced this is solely a monorepo issue.)

I have created the following repo that exhibits the issue:

https://github.com/robcaldecott/storybook-docs-bug

The project contains two components and although the MDX renders fine the `Description` and `ArgsTable` components don't render anything at all and there are no logs in the console.

I adjusted the `stories` config in `main.js` to just include a single story thinking one was affecting another and it still won't work. I am either doing something monumentally stupid or this is a weird bug.

**To Reproduce**

1. `git clone https://github.com/robcaldecott/storybook-docs-bug`
2. `cd storybook-docs-bug`
3. `npm install`
4. `npm run storybook`
5. Go to the Docs page for either component and notice the lack of description and props.

**Code snippets**
Here's the `AnotherButton` component.

```jsx
import React from "react";
import PropTypes from "prop-types";

/**
 * A magic button that can be used for magic operations.
 */
const AnotherButton = (props) => {
  return <button {...props}>Magic</button>;
};

AnotherButton.propTypes = {
  /** Some prop. */
  disabled: PropTypes.bool,
};

export { AnotherButton };
```

And here's the MDX:

```mdx
import {
  Meta,
  Story,
  Canvas,
  Description,
  ArgsTable,
} from "@storybook/addon-docs/blocks";
import { AnotherButton } from "./AnotherButton";

<Meta title="AnotherButton" component={AnotherButton} />

# AnotherButton

<Description />

<Canvas>
  <Story name="Test">
    <AnotherButton />
  </Story>
</Canvas>

## Props

<ArgsTable of={AnotherButton} />
```

And I end up with this:

![image](https://user-images.githubusercontent.com/796702/114723349-80d06a00-9d32-11eb-8faa-99ad32316227.png)

Any help is welcome as I don't know where to start debugging this issue.

**Comment by shilman** [comment]
I think it's an issue with your custom babel config. I removed `babel.config.json`, and deleted the `node_modules/.cache` and it's working fine now.

**Comment by robcaldecott** [comment]
> I think it's an issue with your custom babel config. I removed `babel.config.json`, and deleted the `node_modules/.cache` and it's working fine now.

Wow, that works @shilman ! Thank you. Any ideas how I can tell Storybook not to use that babel config and instead use whatever the defaults are? I need that config for publishing the components.

**Comment by robcaldecott** [comment]
I tried adding this to my main `main.js` config but it did not make any difference:

```js
babel: async (options) => {
    return { ...options, babelrc: false, configFile: false };
  },
```

**Comment by robcaldecott** [comment]
As an experiment I emptied my `babel.config.json` and the issue persists:

```json
{}
```

I have to remove/rename the file for this to work. 🤔

**Comment by shilman** [comment]
@robcaldecott here's the issue to track https://github.com/storybookjs/storybook/issues/14425

**Comment by gabiseabra** [comment]
This has something to do with `react-docgen` parsing components with the project's main babel options, it affects other addons that use docgen info like `addon-controls` too.
Configuring `react-docgen` not to read babel config files fixes your example, you could add this to `.storybook/main.js` as a quick fix:

```js
{
  webpackFinal(config) {
    const babelDocgenOptions =
      config
      .module
      .rules[0] // js rule
      .use[0]   // babel loader
      .options
      .overrides[0] // jsx override
      .plugins[0][1]
    babelDocgenOptions.babelrc = false
    babelDocgenOptions.configFile = false
    return config
  }
};
```

I'm not sure why your example breaks with an empty config file though.

**Comment by robcaldecott** [comment]
@gabiseabra That did the trick! Thank you so much.
