### ISSUE TITLE
Issue with tabs controlling appearance of the toolbar

### ISSUE THREAD

**Issue by darrenmcc-microfocus** [storybookjs/storybook#14598]
**Is your feature request related to a problem? Please describe**
We discovered this issue when hiding the canvas and only showing the docs tab for a component. The entire top toolbar disappears when only one tab is visible.

I've referenced the related component from the source code below. The logic seems to be controlling the appearance of the entire toolbar and not just the tabs.

https://github.com/storybookjs/storybook/blob/8ffcdda6c944bfeb72359caae2de36590c95fec5/lib/ui/src/components/preview/preview.tsx#L150

**Describe the solution you'd like**
This logic should only control the appearance of the tabs. The appearance of the toolbar should be separate and controlled by the `isToolshown` boolean value.

**Describe alternatives you've considered**
The visibility still needs to be configurable. The logic for tabs doesn't need to be though in my opinion, if it is considered that they only show when there is more than one available. Alternatively the tabs could always show and be disabled in the instance that there is only one available.

**Additional info**
![image](https://user-images.githubusercontent.com/62879374/114740992-4373d880-9d42-11eb-9fd8-626bffe78441.png)
With multiple tabs.

![image](https://user-images.githubusercontent.com/62879374/114740938-37881680-9d42-11eb-991c-b6861da3f371.png)
With single docs tab.

**Comment by Tomastomaslol** [comment]
I created a potential solution that introduces a disabled state if there is a single tab item.

### Scenarios

#### Canvas disabled, docs panels enbaled
<img width="1044" alt="Screen Shot 2021-05-04 at 1 16 16 pm" src="https://user-images.githubusercontent.com/1872246/116958465-1a5dbc80-acde-11eb-8482-67d3b204a23d.png">

#### Canvas enbaled, docs panels disabled
<img width="998" alt="Screen Shot 2021-05-04 at 1 14 55 pm" src="https://user-images.githubusercontent.com/1872246/116958509-3cefd580-acde-11eb-8cda-b3bd9e10c4be.png">


#### Canvas enbaled, docs panels enbaled
<img width="1055" alt="Screen Shot 2021-05-04 at 1 15 49 pm" src="https://user-images.githubusercontent.com/1872246/116958477-277aab80-acde-11eb-812d-3de057044c02.png">

Is this a good idea? or does anyone else have a better solution?

**Comment by shilman** [comment]
@Tomastomaslol looks good to me, but why not show the active tab in the active state (e.g. docs tab blue in the first scenario, canvas blue in the second)?

**Comment by Tomastomaslol** [comment]
@shilman Fair point makes sense to me 🙂.  I will push another update that removes the gray color for the disabled state.

**Comment by darrenmcc-microfocus** [comment]
@Tomastomaslol I agree with @shilman, and the solution looks good to me!

**Comment by Tomastomaslol** [comment]
I had another go at this and I couldn't think of a reason why the links shouldn't be clickable all the time. Not sure why I thought it was a good idea.🥴 I removed the disabled states and any associated styles. 

### **Current suggested implementation is:**

#### Canvas disabled, docs panels enbaled
<img width="1053" alt="Screen Shot 2021-05-04 at 6 20 39 pm" src="https://user-images.githubusercontent.com/1872246/116978347-efd42980-ad06-11eb-90dd-6de834769456.png">

#### Canvas enbaled, docs panels disabled
<img width="746" alt="Screen Shot 2021-05-04 at 6 20 11 pm" src="https://user-images.githubusercontent.com/1872246/116978378-f95d9180-ad06-11eb-9125-af94d04bb7e2.png">

#### Canvas enbaled, docs panels enbaled
<img width="1287" alt="Screen Shot 2021-05-04 at 6 04 09 pm" src="https://user-images.githubusercontent.com/1872246/116978413-08444400-ad07-11eb-9bda-3bdfb55ef534.png">

#### Canvas disabled, docs panels disabled
<img width="946" alt="Screen Shot 2021-05-04 at 6 18 48 pm" src="https://user-images.githubusercontent.com/1872246/116978598-480b2b80-ad07-11eb-83fc-1c7dea816bdf.png">
