### ISSUE TITLE
Storyshots skips some stories

### ISSUE THREAD

**Issue by schontz** [storybookjs/storybook#14607]
**Describe the bug**
Storyshots is skipping some of my stories, even though they show up in the browser. Using CRA.

**Question**
Is it possible to get verbose output to figure out which stories it is processing?

**Comment by erikt9** [comment]
At least for me, I noticed it was skipping the first story file alphabetically.  By placing a dummy story beforehand, storyshots began picking up the previously skipped story again.  The skipping only started when upgrading from storybook 6.1 to 6.2 and continues in 6.3.

**Comment by ndelangen** [comment]
The future of storyshots is the test-runner:
https://storybook.js.org/docs/react/writing-tests/test-runner#page-top

And use the play function for expectations:
https://storybook.js.org/docs/react/writing-stories/play-function#page-top

We will not be making any improvement / changes to storyshots.
