### ISSUE TITLE
Vulnerability on @storybook/addon-docs related with trim

### ISSUE THREAD

**Issue by BiancaArtola** [storybookjs/storybook#14603]
I know that it is not a bug, but I need to report a vulnerability that `@storybook/addon-docs` has.

![image](https://user-images.githubusercontent.com/21174759/114767355-e70eba00-9d3d-11eb-9cfd-18350faf35d3.png)

The following is the related dependencie tree:
`@storybook/addon-docs` -> `@mdx-js/loader` -> `@mdx-js/mdx` -> `remark-mdx` -> `remark-parse` -> `trim 0.0.1`

`trim 0.0.1` has a `ReDoS` vulnerability

Please let me know if you need more information about this. 
Can you fix this vuln?

**Comment by nickiaconis** [comment]
I can add a little data from my experience: specifying `"**/remark-parse": "^9.0.0",` our in package.json did remove the `trim 0.0.1` dependency, but caused all `*.stories.mdx` files—which were previously working—to generate an `Unexpected default export without title: {"includeStories":[],"parameters":{"docs":{}}}` error. So it seems there may be changes needed to accommodate bumping the major version of `remark-parse`. Hope this info proves useful!

**Comment by astreiten** [comment]
Exactly, @nickiaconis. I´m facing the same issue.  Do you know if is there a plan to fix this in the next release?

**Comment by tyro-e** [comment]
Following this.

I am experiencing the same warnings on my side.

**Comment by shilman** [comment]
We are on the most recent version of @mdx-js/loader. Any ideas short of forking it?

**Comment by BiancaArtola** [comment]
@shilman I created an issue on `@mdx-js/loader`: https://github.com/mdx-js/mdx/issues/1531
Let's see if they help us!

**Comment by sfc-gh-acourtney** [comment]
There was a followup comments to the issue @BiancaArtola created: https://github.com/mdx-js/mdx/issues/1531#issuecomment-830108771
Apparently this is fixed in MDX 2 (currently in beta).
Thanks for looking into this, @shilman !

**Comment by shilman** [comment]
Nice. I can't wait for MDX2 -- the original release target was last July so ... 😰

**Comment by RyanMacBern** [comment]
The fix for me was to add to my package.json:
```
"resolutions": {
  "**/trim": "^1.0.0"
}
```

**Comment by AElmoznino** [comment]
@RyanMacBern What version of `npm` are you using? Doesn't work for me 😢

**Comment by ljones-i-nexus** [comment]
@AElmoznino I believe "resolutions" is a Yarn feature.

**Comment by AElmoznino** [comment]
> @AElmoznino I believe "resolutions" is a Yarn feature. Happy to be corrected but I think the "has workaround" is only for Yarn users?

I got the abovee working with https://www.npmjs.com/package/npm-force-resolutions

**Comment by BiancaArtola** [comment]
We used `npm` in our project and the solution with `npm-force-resolution` gives us a lot of trouble when building the code, so sadly this is not a solution for us.

**Comment by JJ** [comment]
> I can add a little data from my experience: specifying `"**/remark-parse": "^9.0.0",` our in package.json did remove the `trim 0.0.1` dependency, but caused all `*.stories.mdx` files—which were previously working—to generate an `Unexpected default export without title: {"includeStories":[],"parameters":{"docs":{}}}` error. So it seems there may be changes needed to accommodate bumping the major version of `remark-parse`. Hope this info proves useful!

That does not work if you specify it in package.json either. The old version is still installed.

**Comment by JJ** [comment]
> We used `npm` in our project and the solution with `npm-force-resolution` gives us a lot of trouble when building the code, so sadly this is not a solution for us.

Plus adding another dependency just to solve a vulnerability introduced by one does not make a whole lot of sense. It's probably OK, if you already use it in your project (slash those troubles building the code, of course)

**Comment by deej-split** [comment]
@sfc-gh-acourtney fwiw, I raised this issue (inadvertently duplicately) at https://github.com/mdx-js/mdx/discussions/1597 .  No idea when 2.0 of mdx-js/mdx@2 will come out... seems there's some dispute (2.x has been in the works for > 1 year).  He does point out that there's another package one could look into using instead... https://github.com/wooorm/xdm. I haven't looked at how api-compatible it is, though.

**Comment by haposan06** [comment]
Using npm force resolutions later will  give me this error when I run `npm ls trim`

```
npm ls trim
ex_proj@0.0.1 /ex_proj
├─┬ @storybook/addon-essentials@6.3.6
│ └─┬ @storybook/addon-docs@6.3.6
│   └─┬ @mdx-js/mdx@1.6.22
│     └─┬ remark-parse@8.0.3
│       └── UNMET DEPENDENCY trim@0.0.3 
└── UNMET DEPENDENCY trim@0.0.3 

npm ERR! missing: trim@0.0.3, required by ex_proj@0.0.1
npm ERR! extraneous: trim@0.0.3 /ex_proj/node_modules/trim
```

Is this safe to ignore?

**Comment by AMartinNo1** [comment]
Running into it either. I am using yarn

```
│  ├─ trim-trailing-lines@^1.0.0
│  ├─ trim@0.0.1
├─ trim-trailing-lines@1.1.4
├─ trim@1.0.1
```

and my package.json

```
  "devDependencies": {
    "@babel/core": "^7.15.0",
    "babel-loader": "^8.2.2",
    "jest": "^27.0.6",
    "normalize-pkg": "^0.5.0",
    "storybook": "^6.3.7",
    "trim": "^1.0.1"
  },
  "resolutions": {
    "**/trim": "^1.0.0",
    "storybook/**/trim": "^1.0.0"
  },
```

Unfortunately `resolutions` do not work for me or I am missing something.

**Comment by ptanaji-cb** [comment]
Will this be fixed or need to use resolutions hack temporarily?

**Comment by j-jmnz** [comment]
Any news on fixing this vulnerability?

**Comment by IuliiaBondarieva** [comment]
Updated to storybook@6.4.8 and facing the same problem. Any news on fixing it?

**Comment by shilman** [comment]
This is an issue with one of our dependencies, MDX, and is fixed in MDXv2 which has not been released yet. When it's released we'll try to upgrade ASAP.

**Comment by quyctd** [comment]
any update?

**Comment by shilman** [comment]
Still waiting on mdx v2

**Comment by shilman** [comment]
Yup. On it!! @charkour

**Comment by shilman** [comment]
I've released experimental MDXv2 support in 6.5--please give it a whirl! I've written up a short migration guide to help get started: https://gist.github.com/shilman/6ff2d7e18db8846e8fc552fb432ae4f6

**Comment by SimenB** [comment]
@shilman will `@storybook/csf-tools` be updated as part of this? We don't even use MDX/CSF, so installing a v2 plugin doesn't really make sense for us 🙂 `6.5.0-alpha.46` depends on v1, so I'm guessing "no" 😅

**Comment by SimenB** [comment]
Yeah 👍 Confirms it doesn't help us avoid the vulnerability report 😀 Of course doesn't matter, but tools are stupid...

**Comment by valentineprojects** [comment]
Same problem as well with glob-parent. Is there a hacky way to get around them?

**Comment by aaschlote** [comment]
Some news about this topic?

**Comment by IuliiaBondarieva** [comment]
storybook 6.4.22 introduces 19 high severity vulnerabilities with 
- glob-parent  <5.1.2
- trim  <0.0.3

Is there any change planned at all??

**Comment by shilman** [comment]
@IuliiaBondarieva  please see my comment above. The opt-in MDXv2 upgrade is available in 6.5. The full upgrade is a breaking change and will come in 7.0 (next release)

**Comment by SimenB** [comment]
@shilman storybook 6.5 has introduced more vulnerabilities via the added `x-default-browser` dep in `@storybook/core-server` (#16844). Ends up loading `trim-newlines@1.0.0`, https://github.com/advisories/GHSA-7p7h-4mm5-852v

**Comment by shilman** [comment]
@SimenB we have a fix here. will get it merged & update with a patch. thanks for the heads up! 🙏 

https://github.com/storybookjs/storybook/pull/18157

**Comment by GuillaumeCisco** [comment]
Following: https://github.com/storybookjs/storybook/issues/18860
Can we update it in the recent alpha/beta version? i.e `7.x.x`?

**Comment by shilman** [comment]
@GuillaumeCisco yes we can, it's on our list!

**Comment by pumano** [comment]
@shilman could you please update @mdx-js/mdx to 2.0.x according to comment above? Looks like in 7 alpha.35 branch it's not updated, I tested it today.

```
  ┬ @storybook/addon-essentials@7.0.0-alpha.35
  └─┬ @storybook/addon-docs@7.0.0-alpha.35
    └─┬ @storybook/mdx1-csf@0.0.5-canary.13.9ce928a.0
      └─┬ @mdx-js/mdx@1.6.22
        └─┬ remark-parse@8.0.3
          └── trim@0.0.1
```

**Comment by shilman** [comment]
Yay!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-alpha.40 containing PR #19495 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by dreampulse** [comment]
This is working for me:
```
"resolutions": {
    "**/trim": "^0.0.3"
  },
```
