### ISSUE TITLE
Storybook fails to load a custom class extending Date

### ISSUE THREAD

**Issue by Mintoo200** [storybookjs/storybook#14618]
**Describe the bug**
I added a custom class extending Date to my project adding some helper functions but storybook considers every occurence where I use it as a simple Date and throws a `<helper function> is not a function`. This problem does not occur when I start the CRA app with the Calendar directly.

**To Reproduce**
1. clone [this repository on Github](https://github.com/Mintoo200/storybook-date-bug)
2. start the storybook with `$ yarn; yarn storybook`
3. navigate to `localhost:6006`
4. go to `Calendar>Default`

You can start the working CRA app with `$ yarn start`

**Expected behavior**
The calendar should be displayed with no error.

**System**
```
Environment Info:

  System:
    OS: macOS 11.2.3
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
  Binaries:
    Node: 12.18.3 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.6 - /usr/local/bin/npm
  Browsers:
    Chrome: 89.0.4389.128
    Safari: 14.0.3
  npmPackages:
    @storybook/addon-actions: ^6.2.8 => 6.2.8 
    @storybook/addon-essentials: ^6.2.8 => 6.2.8 
    @storybook/addon-links: ^6.2.8 => 6.2.8 
    @storybook/node-logger: ^6.2.8 => 6.2.8 
    @storybook/preset-create-react-app: ^3.1.7 => 3.1.7 
    @storybook/react: ^6.2.8 => 6.2.8 
```

**Additional context**

The problem still occurs when the storybook is built and served with `npx serve`. I also tried reinstalling all dependencies.
Also casting the Date to a CustomDate as I call the helper function (with `(new CustomDate(myDate)).helperFunction()` or `(myDate as CustomDate).helperFunction()`) still cause the error to trigger.

**Comment by Mintoo200** [comment]
Hey, any update on this?

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
