### ISSUE TITLE
Provide option to hide default toolbar tools

### ISSUE THREAD

**Issue by krzempekk** [storybookjs/storybook#14617]
**Is your feature request related to a problem? Please describe**
In some storybooks I don't want default tools (zoom, fullscreen, eject or copy) to be visible on toolbar. At the moment those are hardcoded in `lib/ui/src/components/preview/toolbar.tsx` in `defaultTools` and `defaultToolsExtra` arrays.

**Describe the solution you'd like**
It would be nice to be able to set config for toolbar specifying which of the default tools should be hidden, for example:
```js
addons.setConfig({
    toolbar: {
        hiddenDefaultTools: ['zoom', 'fullscreen']
    }
});
```

**Describe alternatives you've considered**
Every solution that will allow overriding default tools somehow will be good.

**Are you able to assist to bring the feature to reality?**
yes, I can...

**Comment by Tomastomaslol** [comment]
I spent some time trying to figure out how this could be implemented. My suggested solution will allow you to exclude tools using the following syntax in the configuration:

```js 
addons.setConfig({
  toolbar: {
    title: { hidden: true },
    zoom: { hidden: true },
    eject: { hidden: true },
    copy: { hidden: true },
    fullscreen: { hidden: true },
    'storybook/background': { hidden: true },
    'storybook/viewport': { hidden: true },
  },
});
```

You should also be able to exclude tools using story parameters: https://github.com/storybookjs/storybook/pull/14897/files#diff-49dbf57f9190dc0ee066badd7466c4ed85ac1797dd09fd0d9a42a86b010be845R76

Please let me know if this is a good idea or if there is a better way to solve this 🙂

**Comment by krzempekk** [comment]
Great, that's exactly what I have expected 😄

**Comment by shilman** [comment]
w00t!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.3.0-alpha.29 containing PR #14897 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
