### ISSUE TITLE
feat(Angular): Support for global styles for individual components

### ISSUE THREAD

**Issue by bjornharvold** [storybookjs/storybook#14612]
**Is your feature request related to a problem? Please describe**
#14549 

**Describe the solution you'd like**
An easy way to apply global styles to an Angular component library in a mono repo with multiple SPA apps / styles.

**Current solution**
When testing individual components, we switch between SPA projects by changing defaultProject in angular.json.

**Are you able to assist to bring the feature to reality?**
No - Have little insight into Angular internals

**Additional context**

**Comment by ThibaudAV** [comment]
IMHO this [PR](https://github.com/storybookjs/storybook/pull/15061) close this.

but if you could test it would be perfect 🙏

**Comment by shilman** [comment]
Boo-yah!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-rc.9 containing PR #16675 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
