### ISSUE TITLE
Using args with Typescript

### ISSUE THREAD

**Issue by jasperdunn** [storybookjs/storybook#14625]
**Describe the bug**
I followed the TS pattern outlined [here.](https://storybook.js.org/docs/react/writing-stories/args#story-args)
Is this documentation already outdated?

I have two errors reported by Typescript:

```
Property 'to' is missing in type . . . . but required in type . . . . 
```

and

```
Property 'args' does not exist on type '(args: Story<{ to: string; }>) => Element'.
```

**Screenshots**
<img width="808" alt="Screen Shot 2021-04-16 at 4 42 33 pm" src="https://user-images.githubusercontent.com/26566353/114982430-c9268e00-9ed2-11eb-8a77-8da917aa7c98.png">

**System**
```
Environment Info:

  System:
    OS: macOS 11.2.3
    CPU: (8) x64 Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz
  Binaries:
    Node: 15.5.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.3.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 89.0.4389.128
    Firefox: 87.0
    Safari: 14.0.3
  npmPackages:
    @storybook/addon-a11y: ^6.2.8 => 6.2.8 
    @storybook/addon-essentials: ^6.2.8 => 6.2.8 
    @storybook/addon-links: ^6.2.8 => 6.2.8 
    @storybook/addons: ^6.2.8 => 6.2.8 
    @storybook/node-logger: ^6.2.8 => 6.2.8 
    @storybook/preset-create-react-app: ^3.1.7 => 3.1.7 
    @storybook/react: ^6.2.8 => 6.2.8 
```

**Comment by shilman** [comment]
That's not what the documentation says. Story is the type of the template, not the type of the argument to the template

**Comment by jasperdunn** [comment]
Thanks shilman, I feel extremely smart 🤣
