### ISSUE TITLE
build-storybook writes to STDERR even when it's successful (causes warnings with Rush.js)

### ISSUE THREAD

**Issue by kaiyoma** [storybookjs/storybook#14621]
**Describe the bug**
build-storybook writes to STDERR even when it's successful. This causes warnings with tools like Rush.js, which monitor STDERR for content and flag the build as "successful with warnings" as a result.

**To Reproduce**

```
$ ./node_modules/.bin/build-storybook -c storybook -o dist-storybook --quiet > stdout.txt 2> stderr.txt
$ ls -l std*
-rw-r--r-- 1 Kyle Getz 197121 703 Apr 15 12:54 stderr.txt
-rw-r--r-- 1 Kyle Getz 197121   0 Apr 15 12:54 stdout.txt
```

**Expected behavior**
build-storybook should be writing normal output to STDOUT.

**System**

```
Environment Info:

  System:
    OS: Windows 10 10.0.19042
    CPU: (4) x64 Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
  Binaries:
    Node: 14.15.0 - C:\Program Files\Node.js\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.8 - C:\Program Files\Node.js\npm.CMD
  Browsers:
    Chrome: 89.0.4389.114
    Edge: Spartan (44.19041.906.0), Chromium (89.0.774.75)
  npmPackages:
    @storybook/addon-actions: 6.2.8 => 6.2.8
    @storybook/addon-docs: 6.2.8 => 6.2.8
    @storybook/addon-knobs: 6.2.8 => 6.2.8
    @storybook/addons: 6.2.8 => 6.2.8
    @storybook/core: 6.2.8 => 6.2.8
    @storybook/react: 6.2.8 => 6.2.8
    @storybook/theming: 6.2.8 => 6.2.8
```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1199622255231368/1200206900418606) by [Unito](https://www.unito.io)

**Comment by shilman** [comment]
Is this a regression in 6.2?

**Comment by kaiyoma** [comment]
@shilman I'm not sure. I can't test earlier versions because they seem to have some kind of core-js dependency problem that causes the build to actually fail. I have to run 6.2 for the build to pass.

**Comment by BorysShulyak** [comment]
any news on this?

**Comment by shilman** [comment]
Yowza!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-alpha.39 containing PR #19434 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by nickiaconis** [comment]
@kaiyoma Can you explain where you added that workaround? That might be my team's best option until we can upgrade to Storybook v7.

Hopefully, v7 will also include storybookjs/react-docgen-typescript-plugin#8 by that time, the underlying issue of which logs actual warnings that likewise cause `rush build` to fail. 🤞😬

**Comment by kaiyoma** [comment]
@nickiaconis We use Rush and Just, so I had worked that logic into our config files for those tools (Just, specifically).
