### ISSUE TITLE
@storybook/vue won`t work when using vue-loader@16.x

### ISSUE THREAD

**Issue by Jogiter** [storybookjs/storybook#14623]
https://github.com/storybookjs/storybook/blob/next/app/vue/src/server/framework-preset-vue.ts#L2

```ts
import VueLoaderPlugin from 'vue-loader/lib/plugin';
```

there is a `lib/plugin.js` file in vue-loader@15.x, but after vue-loader upgrade to 16.x.  `lib/plugin.js` is not exist anymore

see [vue-loader/plugin.ts](https://github.com/vuejs/vue-loader/blob/v16.1.2/src/plugin.ts)

Fix:

```ts
import { VueLoaderPlugin } from 'vue-loader';
```

i`ll do a pr in minutes

**Comment by mchl18** [comment]
I need this! :D

**Comment by shilman** [comment]
Huzzah!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-alpha.7 containing PR #14624 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```
