### ISSUE TITLE
Angular - problems with component using ControlValueAccessor

### ISSUE THREAD

**Issue by wszydlak** [storybookjs/storybook#14627]
**Describe the bug**
I tried to use my own component which is using `ControlValueAccessor` without success. I have many problems.
I prepared example (below as Code Snippet) which seems to not work with Storybook - please use it to reproduce errors.

Problems:

1. Canvas Tab:
    * throwing error: `ERROR TypeError: instance.registerOnChange is not a function` (in legacy renderer)
    * throwing error: `ERROR TypeError: provider.ngAfterViewInit is not a function` (in current renderer)
    * properly formatting input value (change to uppercase)
    * actions - not showing `modelChange`
2. Docs Tab (using `inlineStories: true`):
    * throwing error: `ERROR TypeError: provider.ngAfterViewInit is not a function`
    * formatting doesn't work

What i tried:

1. For Canvas Tab i have no ideas whats going on legacy renderer (probably something related to using ngModel and ControlValueAccessor), but for current renderer:
    * tried to use compodoc with `--disableLifeCycleHooks --disableInternal --disablePrivate`:
         * the error on init disappears
         * action still is not fired
         * formatting stops working, throwing: `ERROR TypeError: this.formatValue is not a function`
2. For Docs Tab:
    * tried to use compodoc with `--disableLifeCycleHooks --disableInternal --disablePrivate`:
        * the error on init disappears
        * formatting still not working, now throwing: `ERROR TypeError: this.formatValue is not a function`

Seems that something is wrong maybe with storybook-wrapper component? Something on bridge between storybook component wrapper and user defined component.

**To Reproduce**

1. Just open storybook with stories and components prepared for this issue

**Expected behavior**
Example from this issue should just work fine

**Code snippets**
```ts
// input.component.ts
import {
  Component,
  Input,
  AfterViewInit,
  HostListener,
  HostBinding,
  ChangeDetectionStrategy,
  ViewEncapsulation,
  ExistingProvider,
  forwardRef,
} from '@angular/core';
import { ControlValueAccessor, NG_VALUE_ACCESSOR } from '@angular/forms';

const INPUT_CONTROL_VALUE_ACCESSOR: ExistingProvider = {
  provide: NG_VALUE_ACCESSOR,
  useExisting: forwardRef(() => StorybookInputComponent),
  multi: true,
};

@Component({
  selector: 'storybook-input',
  template: `<input [placeholder]="label" [(ngModel)]="value" />`,
  providers: [INPUT_CONTROL_VALUE_ACCESSOR],
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
})
export default class StorybookInputComponent
  implements AfterViewInit, ControlValueAccessor {
  private privateValue = '';

  /**
   * @required
   */
  @Input()
  label = '';

  ngAfterViewInit(): void {
    console.log('Init');
  }

  @HostBinding('class.not-empty')
  get notEmpty(): boolean {
    return !!this.value;
  }

  @HostListener('click')
  hostClick(): void {
    this.makeThisCall();
  }

  private makeThisCall(): void {
    console.log(this);
  }

  get value(): string {
    return this.privateValue;
  }

  set value(val: string) {
    const value = this.formatValue(val);
    this.privateValue = value;
  }

  formatValue(s: string): string {
    return s.toUpperCase();
  }

  /**
   *
   * @internal
   */
  writeValue(val: string): void {
    this.value = val;
  }

  /**
   *
   * @internal
   */
  registerOnChange(onChange): void {
    this.onChangeCallback = onChange;
  }

  /**
   *
   * @internal
   */
  registerOnTouched(onTouched): void {
    this.onTouchedCallback = onTouched;
  }

  /**
   * On change
   *
   * @internal
   */
  onChangeCallback = () => {};

  /**
   * On touched
   *
   * @internal
   */
  onTouchedCallback = () => {};
}
```

```ts
// input.stories.ts
import { FormsModule } from '@angular/forms';
import { action } from '@storybook/addon-actions';
import { moduleMetadata, Story, Meta } from '@storybook/angular';
import StorybookInputComponent from './input.component';

export default {
  title: 'Example/StorybookInput',
  component: StorybookInputComponent,
  decorators: [
    moduleMetadata({
      declarations: [StorybookInputComponent],
      imports: [FormsModule],
    }),
  ],
} as Meta;

const Template: Story<StorybookInputComponent> = (
  args: StorybookInputComponent
) => ({
  props: {
    ...args,
    ngModelChange: action('modelChange'),
  },
});

export const Primary = Template.bind({});
Primary.args = {
  label: 'Input',
};
```

**System**
* System: macOS
* Angular version: tried on Angular 9, 10 and 11 (all options with and without Ivy)
* Storybook versions:
    * @storybook/addon-actions: ^6.2.8 => 6.2.8 
    * @storybook/addon-essentials: ^6.2.8 => 6.2.8 
    * @storybook/addon-links: ^6.2.8 => 6.2.8 
    * @storybook/angular: ^6.2.8 => 6.2.8

**Comment by ThibaudAV** [comment]
@wszydlak can you try this ? :

Make sure that you do not directly pass all `args` in your story `props`
prefer a "destructuring" to control them : 
```
const Template: Story<SampleComp> = (args) => ({
  props: {
  input1: args.input1
  },
});
```

**Comment by wszydlak** [comment]
Hi @ThibaudAV, checked it and seems that your solution fixed problems - thank you very much. I prepared quick solution that create props object from args, cutting non-inputs. For me this solution is perfect.

**Comment by shilman** [comment]
Yee-haw!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.3.0-alpha.18 containing PR #14769 that references this issue. Upgrade today to the @next NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
