### ISSUE TITLE
Webpack file-loader error with non-standard file types

### ISSUE THREAD

**Issue by AndrewJSchoen** [storybookjs/storybook#14633]
**Describe the bug**
Adding an additional rule for file-loader of files like `.glb`, and then trying to import them within the javascript source returns an alias file, not the actual file. 

**To Reproduce**
1. Add an additional rule for file-loading of the filetype (`.glb`). 
2. Import the file relative to a javascript file using the `import _ from _` syntax.
3. Console log the value obtained from import.
4. Observe that the value is a `.glb` file, but actually contains javascript exporting a string as a concatenation of __webpack_public_path__ and a different `.glb` file.
5. Load the file as `http://localhost:6009/<path from step 4>`
6. Obtain desired file

**Expected behavior**
The result obtained from importing (step 2 above) returns the result of step 4 directly, so it can be loaded with the needed function. 

**Code snippets**
```
// .storybook.main.js
module.exports = {
  "stories": [
    "../src/**/*.stories.mdx",
    "../src/**/*.stories.@(js|jsx|ts|tsx)"
  ],
  "addons": [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/preset-create-react-app"
  ],
  webpackFinal: async (config, { configType }) => {
    config.module.rules.push({
      test: /\.(glb|gltf)$/,
      use: ['file-loader'],
      include: path.resolve(__dirname, '../'),
    });
    return config;
  },
};
```

```
/ / MeshLoader.jsx
import MyMeshFile from "./meshes/MyMesh.glb";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF(MyMeshFile);
  // Do more stuff with these things
}
```

**System**
 System:
    OS: macOS 11.2.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 12.21.0 - ~/.nvm/versions/node/v12.21.0/bin/node
    npm: 6.14.11 - ~/.nvm/versions/node/v12.21.0/bin/npm
  Browsers:
    Chrome: 90.0.4430.72
    Firefox: 73.0
    Safari: 14.0.3
  npmPackages:
    @storybook/addon-actions: ^6.2.8 => 6.2.8 
    @storybook/addon-essentials: ^6.2.8 => 6.2.8 
    @storybook/addon-links: ^6.2.8 => 6.2.8 
    @storybook/node-logger: ^6.2.8 => 6.2.8 
    @storybook/preset-create-react-app: ^3.1.7 => 3.1.7 
    @storybook/react: ^6.2.8 => 6.2.8 

**Additional context**

**Comment by shilman** [comment]
i'm not sure how `@storybook/preset-create-react-app` deals with these novel files, because it essentially throws away storybook's webpack config and replaces it with CRA's. @mrmckeb might be able to give a more precise description of what's going on here

**Comment by AndrewJSchoen** [comment]
@shilman @mrmckeb Thanks for pointing that out. A quick test of removing the "@storybook/preset-create-react-app" add-on does seem to produce the _expected_ behavior without apparently breaking anything else. I guess I can proceed without that for the time being, and maybe this should be pointed over to [preset-create-react-app](https://github.com/storybookjs/presets/tree/master/packages/preset-create-react-app)?

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
