### ISSUE TITLE
tailwind.css @apply not work in sass mixin when build-storybook

### ISSUE THREAD

**Issue by ljwrer** [storybookjs/storybook#14645]
**Describe the bug**
tailwind.css @apply not work in sass mixin when build-storybook, but works on development mode

**To Reproduce**
<https://github.com/ljwrer/storybook-tailwind-sass-mixin-issue>
when run npm storybook, you'll see a white text with blue  background color in button.stories
when run npm build-storybook, the style of text is disappear due to tailwind.css @apply not compiled
**System**
Environment Info:

  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
  Binaries:
    Node: 12.16.1 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 90.0.4430.72
    Edge: 90.0.818.41
    Firefox: 81.0.2
    Safari: 14.0.3
  npmPackages:
    @storybook/addon-actions: ^6.2.8 => 6.2.8 
    @storybook/addon-essentials: ^6.2.8 => 6.2.8 
    @storybook/addon-links: ^6.2.8 => 6.2.8 
    @storybook/node-logger: ^6.2.8 => 6.2.8 
    @storybook/preset-create-react-app: ^3.1.7 => 3.1.7 
    @storybook/react: ^6.2.8 => 6.2.8 

**Additional context**
I think the problem is the sequence of sass-loader and postcss-loader, how should I config it?

**Comment by diegoaguilar** [comment]
@ljwrer did you figure this out?

**Comment by ljwrer** [comment]
> @ljwrer did you figure this out?

No, I drop all @apply in my sass mixin

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
