### ISSUE TITLE
(Angular) Inject a mock component-level provider in a Story

### ISSUE THREAD

**Issue by mfrancekovic** [storybookjs/storybook#14648]
I can't seem to figure out how to inject a component level provider in a Story. And I would appreciate if somebody can give me an idea.

Here is an example:

```
@Component({
  selector: 'app-some-component',
  templateUrl: './some-component.component.html',
  styleUrls: ['./some-component.component.scss'],
  providers: [SomeService], // <= The provider is on the component level.
})
export class SomeComponent implements OnInit {

  constructor(private someService: SomeService) { }

// some stuff happens here
}
```

Now I want to create a story for this component, by using a mock service instead of the real SomeService.

The story looks something like this:

```
class SomeServiceMock implements Partial<SomeService> {
  doSomething = () => {
    console.log('Do something');
  };
}

export default {
  title: 'SomeComponent',
  component: SomeComponent,
  decorators: [
    moduleMetadata({
     providers: [{ provide: SomeService, useClass: SomeServiceMock }], // <= here I try to provide a mock
    }),
  ],
} as Meta;

const Template: Story<SomeComponent> = () => ({
  component: SomeComponent,
});

export const Base = Template.bind({});

```

With this example, the real SomeService will in fact be used in the Story, and the SomeServiceMock is ignored. This is somewhat clear to me, as the mock service is provided on the module level, and the component itself has the provider on the component level, which takes precedence. 

My question is, how does one mock that component level provider though?

🙏 🙏

**Comment by mfrancekovic** [comment]
The only thing I've found to be working is to extend the component and provide a mock service for that extended component and then create a story for that extended component instead of the original component.

Something like this:

```
const SomeServiceMock =  {
  doSomething: () => {
    console.log('Do something');
  };
}

@Component({
  selector: 'app-some-component',
  templateUrl: './some-component.component.html',
  styleUrls: ['./some-component.component.scss'],
  providers: [{ provide: SomeService, useValue: SomeServiceMock }],
})
class MockSomeComponent extends SomeComponent {}
```

and then create a story for that Mock component instead of the original component.

```
export default {
  title: 'SomeComponent',
  component: MockSomeComponent,
} as Meta;

const Template: Story<MockSomeComponent> = () => ({
  component: MockSomeComponent,
});

export const Base = Template.bind({});
```

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
