### ISSUE TITLE
Why I have a nothing found at the bottom of page

### ISSUE THREAD

**Issue by m17805804790** [storybookjs/storybook#14646]
**What's the problem?**
When I use storiesof to build a componet， there is always have a nothing found render at the bottom of page

**Additional context**
storiesOf("Icon", module)
  .addDecorator((storyFn) => <div>{storyFn()}</div>)
  .add("default", () => (<div>test</div>}
it behaved like this 
![image](https://user-images.githubusercontent.com/38969394/115175286-50574a00-a0fd-11eb-994c-9a355b6db458.png)
![image](https://user-images.githubusercontent.com/38969394/115175293-53ead100-a0fd-11eb-81b9-c8d5680417b7.png)

**Comment by shilman** [comment]
what's the value of `test`?

**Comment by m17805804790** [comment]
> what's the value of `test`?

just a string，now whateve the value test is， there is always have a nothing found render at the bottom of page

**Comment by shilman** [comment]
please read the documentation on writing stories https://storybook.js.org/docs/react/writing-stories/introduction
