### ISSUE TITLE
Docs creating a vue storybook addon seems incorrect or deprecated

### ISSUE THREAD

**Issue by danielgroen** [storybookjs/storybook#14656]
Hi,

I am following the docs which should let me build my own plugin for vue.
However i am following the instructions of [this page](https://github.com/storybookjs/storybook/blob/next/docs/addons/writing-addons.md) but when i follow these instructions, i can't get my "Button.vue" up and running.

i've made myself a [test repo](https://github.com/danielgroen/storybook-vue-addon-test) so you can see what i got so far (it's just the basics)

**Comment by shilman** [comment]
I don't see any `Button.vue` in that repo?

**Comment by danielgroen** [comment]
Inside the stories folder

**Comment by shilman** [comment]
- the `.storybook/main.js` `stories` field is empty
- you've installed `@storybook/react` but you probably need `@storybook/vue` instead

there might be more...

**Comment by danielgroen** [comment]
you were right,

i previously filled the main.js with the stories but later on i deleted it because i wanted to be sure that I 100% followed the docs.

It now works. Can the docs be updated for adding a module for vue?
