### ISSUE TITLE
Error: EMFILE: too many open files

### ISSUE THREAD

**Issue by dep** [storybookjs/storybook#14657]
**Describe the bug**
When my Storybook recompiles, I get the following error:

```
Error: EMFILE: too many open files, open '/Users/dt/sandbox-docker/Tan/applications/storybook/node_modules/.cache/storybook/public/iframe.html'
```

**To Reproduce**

Run storybook

**System**

Environment Info:

  System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 12.18.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.10 - ~/.npm/bin/npm
  Browsers:
    Chrome: 89.0.4389.128
    Edge: 90.0.818.41
    Firefox: 86.0.1
    Safari: 13.1.3

**Additional context**

my `.storybook/main.js`:

```
module.exports = {
    addons: [require.resolve('@cloudvox/storybook-config')],
    stories: ['../node_modules/@cloudvox/tan-*/dist/**/*.stories.js'],
};
```

That grep pattern isn't a ridiculous amount of stories:

```
▶ ls -l node_modules/@cloudvox/tan-*/dist/**/*.stories.js
1511 Apr 19 14:55 node_modules/@cloudvox/tan-account-profile/dist/stories/app.stories.js
2690 Apr 19 14:55 node_modules/@cloudvox/tan-billing-dashboard/dist/stories/app.stories.js
1613 Apr 19 14:55 node_modules/@cloudvox/tan-core-components/dist/components/Forms/Forms.stories.js
5551 Apr 19 14:55 node_modules/@cloudvox/tan-core-components/dist/components/List/List.stories.js
 848 Apr 19 14:55 node_modules/@cloudvox/tan-core-components/dist/components/Modals/Modals.stories.js
2631 Apr 19 14:55 node_modules/@cloudvox/tan-core-components/dist/components/Page/Page.stories.js
2319 Apr 19 14:55 node_modules/@cloudvox/tan-core-components/dist/components/Providers/Providers.stories.js
5982 Apr 19 14:55 node_modules/@cloudvox/tan-core-components/dist/components/Table/Table.stories.js
5741 Apr 19 14:55 node_modules/@cloudvox/tan-core-components/dist/components/Utilities/Utilities.stories.js
 875 Apr 19 14:55 node_modules/@cloudvox/tan-core-components/dist/components/Widgets/Widgets.stories.js
1783 Apr 19 14:59 node_modules/@cloudvox/tan-numbers/dist/stories/app.stories.js
2241 Apr 19 14:55 node_modules/@cloudvox/tan-reporting-groups/dist/stories/app.stories.js
1963 Apr 19 14:55 node_modules/@cloudvox/tan-routes/dist/stories/app.stories.js
1191 Apr 19 14:55 node_modules/@cloudvox/tan-tag-manager/dist/stories/app.stories.js
 859 Apr 19 14:55 node_modules/@cloudvox/tan-universal-tags/dist/stories/app.stories.js
1904 Apr 19 14:55 node_modules/@cloudvox/tan-user-profile/dist/stories/app.stories.js
```

`@cloudvox/storybook-config'`:

```
module.exports = {
    addons() {
        return [
            require.resolve('@storybook/addon-essentials'),
            require.resolve('@cloudvox/theme-addon-storybook/preset'),
        ];
    },
};

````

and `@cloudvox/theme-addon-storybook/preset`:

```
interface PresetOptions {
    addDecorator?: boolean;
}

export function managerEntries(entry: unknown[] = []) {
    return [...entry, require.resolve('../register')];
}

export function config(entry: unknown[] = [], { addDecorator = true }: PresetOptions = {}) {
    const presetConfig = [];

    if (addDecorator) {
        presetConfig.push(require.resolve('./addDecorator'));
    }

    return [...entry, ...presetConfig];
}

```

**Comment by yoavniran** [comment]
I started seeing this error today as well.

Same project Ive been working on for last couple of years but different macbook (pro, 32GB, intel). Just moved to a new one and for some reason node simply isnt able to run SB (with my code) successfully. 
the build seems fine although slow but most times I get in the browser "page cannot load" or I get a blank page but nothing else shows.

Eventually I see the error in the terminal: 

```
Error: EMFILE: too many open files, open '/Users/yoavniran/dev/react-uploady/node_modules/.cache/storybook/public/runtime~main.manager.bundle.js
```

SB: 6.2.2
node: 14.18.2 (also 14.17.6)

**Comment by yoavniran** [comment]
Upgraded both SB to 6.3.12 + _fsevents_ (optionalDependencies) to latest (2.3.2) and the problem went away. Not sure which one had more impact...

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
