### ISSUE TITLE
Storybook doesn't load stories: Cannot set property 'STORYBOOK_REACT_CLASSES' of undefined

### ISSUE THREAD

**Issue by lordVelisch** [storybookjs/storybook#14666]
**What's the problem?**
I initialized Storybook (6.2.7) in an existing Angular project with multiple angular libraries that are built separately. When I start Storybook with ```npm start storybook``` it serves storybook but never loads any story (only loading screen) and displays this error in the console: `Uncaught TypeError: Cannot set property 'STORYBOOK_REACT_CLASSES' of undefined`. In the globals.js file in '@storybook/core-server': global.window.REACT..., window is undefined. 

My storybook related dependencies: 

"@babel/core": "7.13.15",
"@compodoc/compodoc": "1.1.11",
"@storybook/addon-actions": "6.2.7",
"@storybook/addon-docs": "6.2.7",
"@storybook/addon-essentials: "6.2.7",
"@storybook/addon-links": "6.2.7",
"@storybook/addon-controls": "6.2.7",
"@storybook/angular": "6.2.7"

**Comment by lordVelisch** [comment]
Found the issue. There was a library called global in the project so global.window.Story... accessed the wrong object.

**Comment by hiimtmac** [comment]
How did you fix this? Im having the same problem:

```
bootstrap:27 Uncaught TypeError: Cannot set property 'STORYBOOK_REACT_CLASSES' of undefined
    at Object../node_modules/@storybook/core-client/dist/esm/globals/globals.js
```

**Comment by jmduke** [comment]
For anyone still running into this issue in the context of a test: I ran into it by upgrading `jest` and `babel-jest` to `27`, and was able to resolve by shifting the environment of the test to `jsdom`. The core issue appears to be that the runner is assuming `window` is available, since this is the snippet that is failing:

```
var globalWindow = _global.default.window;
globalWindow.STORYBOOK_REACT_CLASSES = {};
```

**Comment by SamHoque** [comment]
having the same issue, and @jmduke's answer doesn't solve it.
