### ISSUE TITLE
barTextColor not applied correctly in unselected tabs in toolbar

### ISSUE THREAD

**Issue by nikosama7** [storybookjs/storybook#14664]
**Describe the bug**
I have noticed that the unselected tabs in toolbar haven't got the same color as the 'Zoom' buttons.

**To Reproduce**
I reproduced it using your example of custom theming [https://storybook.js.org/docs/angular/configure/theming](https://storybook.js.org/docs/angular/configure/theming)

![image_2021_04_20T07_32_14_100Z](https://user-images.githubusercontent.com/47453821/115358052-f2426980-a1c5-11eb-96f1-16c84f03a24c.png)

I also used the following custom theme
```
export default create({
  base: 'light',

  colorPrimary: '#951509',
  colorSecondary: 'deepskyblue',

  // UI
  appBg: '#eee',
  appContentBg: '#dadada',
  appBorderColor: 'grey',
  appBorderRadius: 4,

  // Typography
  fontBase: '"Open Sans", sans-serif',
  fontCode: 'monospace',

  // Text colors
  textColor: 'black',
  textInverseColor: 'rgba(255,255,255,0.9)',

  // Toolbar default and active colors
  barTextColor: 'white',
  barSelectedColor: 'black',
  barBg: '#959ea1',

  // Form colors
  inputBg: 'white',
  inputBorder: 'silver',
  inputTextColor: 'black',
  inputBorderRadius: 4,

  brandTitle: 'Title',
  brandUrl: '#',
  brandImage: 'https://www.example.com',
});
```

![image_2021_04_20T07_33_04_411Z](https://user-images.githubusercontent.com/47453821/115358843-beb40f00-a1c6-11eb-867f-1ecd052e010a.png)

**System**

> Environment Info:
> 
>   System:
>     OS: Windows 10 10.0.19041
>     CPU: (4) x64 Intel(R) Xeon(R) CPU E5-2670 v3 @ 2.30GHz
>   Binaries:
>     Node: 10.14.1 - C:\Program Files\nodejs\node.EXE
>     Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
>     npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
>   Browsers:
>     Chrome: 90.0.4430.72
>     Edge: Spartan (44.19041.906.0), Chromium (90.0.818.41)
>   npmPackages:
>     @storybook/addon-actions: ^6.2.8 => 6.2.8
>     @storybook/addon-controls: ^6.2.8 => 6.2.8
>     @storybook/addon-docs: ^6.2.8 => 6.2.8
>     @storybook/addon-knobs: ^6.2.8 => 6.2.8
>     @storybook/addon-links: ^6.2.8 => 6.2.8
>     @storybook/addon-storysource: ^6.2.8 => 6.2.8
>     @storybook/addon-viewport: ^6.2.8 => 6.2.8
>     @storybook/addons: ^6.2.8 => 6.2.8
>     @storybook/angular: ^6.2.8 => 6.2.8
>     @storybook/source-loader: ^6.2.8 => 6.2.8
>     @storybook/theming: ^6.2.8 => 6.2.8

**Comment by sarahbethfederman** [comment]
Yes, mine seem to be getting all silver since updating to 6.2 as well

**Comment by shilman** [comment]
Yee-haw!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.3.0-alpha.17 containing PR #14308 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
