### ISSUE TITLE
Getting  Error: Can't resolve '@storybook/react/dist/client/preview' in '/builds/StixNext/mojito/.storybook' on build

### ISSUE THREAD

**Issue by renjith-jr** [storybookjs/storybook#14665]
ERR! => Failed to build the preview
ERR! Module not found: Error: Can't resolve '@storybook/react/dist/client/preview' in '/builds/StixNext/mojito/.storybook'
ERR! ModuleNotFoundError: Module not found: Error: Can't resolve '@storybook/react/dist/client/preview' in '/builds/StixNext/mojito/.storybook'

**Comment by ndelangen** [comment]
Without a reproduction there's really nothing we can do to help you.

It would seem a package wasn't installed?
