### ISSUE TITLE
Styling for "Show Code" button and dark mode.

### ISSUE THREAD

**Issue by cmsbased** [storybookjs/storybook#14673]
**What's the problem?**

I have successfully customized my storybook with `addon-themes` and created the dark style for div with a `.docs-story` class.

I tried to style the "show code" button on the docs tab without luck via CSS in preview-head.html. 

The problem is that there is no unique CSS class to scope (only dynamically generated classes):

```
<div class="css-11xgcgt">
<button class="css-1imo1gr">Show code</button>
</div>
```

**Is there documentation on this?**
I checked all customization docs and there are no customization options for the button. I do not expect granular controls, but unique CSS class for a button would be nice.

**Additional context**

![image](https://user-images.githubusercontent.com/5864393/115483914-b9cf7980-a21f-11eb-91e2-05bd8c3ffd2a.png)

**Comment by Ayushsunny** [comment]
Hello @shilman I would like to work on this issue

**Comment by frassinier** [comment]
@Ayushsunny I've already done something, maybe we can work together? Are you available for a review?

**Comment by Ayushsunny** [comment]
> @Ayushsunny I've already done something, maybe we can work together? Are you available for a review?

yes @frassinier

**Comment by shilman** [comment]
Yippee!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.3.0-alpha.17 containing PR #14685 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
