### ISSUE TITLE
Storybook composition won't load

### ISSUE THREAD

**Issue by Sinled** [storybookjs/storybook#14679]
Hi,

**What's the problem?**
i am trying to setup storybook composition, and have strange problems,
everything works fine on local machine, but wouldn't work on gitlab pages, each url from composition configuration is working, and can be opened separately without problems, but when i open root storybook, all composite parts are stuck in loading, without any error in console, network requests to `stories.json` completed.
When i run root storybook locally with urls pointing to gitlab pages - it also works.

Any ideas what might be causing this problem?

**Comment by shilman** [comment]
Is it a CORS issue?

**Comment by Sinled** [comment]
> Is it a CORS issue? Are there any errors in the browser console? What does the network tab show in the devtools?

There are no errors in console, all requests except `metadata.jsons` are completed, requests are made to the same domain, so probably there shouldn't be CORS issues

**Comment by Celos** [comment]
Same exact issue: 2 storybooks on their own paths (`/vue`and `/react`) on the same domain + a third one for composition (also same domain, served from `/`). Composition works locally. When built and served by nginx, both paths load fine with no errors. The composition storybook also shows no errors and all requests (including `stories.json`, but not `metadata.json`, which gets a 404) get a 200 response with seemingly proper content. 

And yet both storybooks just keep loading in the composition view.

**Comment by rschulz-scisys** [comment]
same issue here with sb 6.3.4 in angular, 404 on metadata.json, apart from that no errors. referenced url is behind nginx proxy on same host with different path, stories.json is read fine. 

![image](https://user-images.githubusercontent.com/58476311/125817508-df8f1ec5-7e86-47f5-8ae2-669a147e366b.png)

**Comment by Robbie-Cook** [comment]
I am having the same issue. It seems like storybook composition does not work now if stories.json is not present. Running `npx sb extract` and serving `npm run storybook -s storybook-static` works, but extracting is a fiddly process when using `start-storybook`. Happy to get demo if needed

**Comment by shilman** [comment]
@ssddi456 metadata.json should be optional. i suspect the error is elsewhere! what does `stories.json` contain?

**Comment by cjreysayago** [comment]
Hi @prewk your solution worked for me as well!

**Comment by marksy** [comment]
I was using GitHub Pages to host my Storybook composition and was hardcoding the production URL (http://made-up-url.hash.github.io/react-storybook/).

The main Storybook (Web Components) was composing React Storybook.

In my node scripts I built both Storybook interfaces, then copied the built React Storybook into the Web Component Storybook.

Updating the Storybook composition URL to be root relative (`/react-storybook/`) as @prewk suggested worked perfectly
