### ISSUE TITLE
start-storybook seems to run, but then displays "Cannot GET /" in the browser

### ISSUE THREAD

**Issue by kaiyoma** [storybookjs/storybook#14672]
**Describe the bug**
When I run start-storybook, it seems to work correctly, and prints out this message:

```
╭───────────────────────────────────────────────────╮
│                                                   │
│   Storybook 6.2.8 started                         │
│   1.63 min for preview                            │
│                                                   │
│    Local:            http://localhost:9001/       │
│    On your network:  http://10.95.72.144:9001/    │
│                                                   │
╰───────────────────────────────────────────────────╯
```

However, when I open that link in the browser, I get only this:

```
Cannot GET /
```

**System**
```
Environment Info:

  System:
    OS: Windows 10 10.0.19042
    CPU: (4) x64 Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
  Binaries:
    Node: 14.15.0 - C:\Program Files\Node.js\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 7.10.0 - C:\Program Files\Node.js\npm.CMD
  Browsers:
    Chrome: 90.0.4430.72
    Edge: Spartan (44.19041.906.0), Chromium (89.0.774.77)
  npmPackages:
    @storybook/addon-actions: 6.2.8 => 6.2.8
    @storybook/addon-docs: 6.2.8 => 6.2.8
    @storybook/addon-knobs: 6.2.8 => 6.2.8
    @storybook/addons: 6.2.8 => 6.2.8
    @storybook/core: 6.2.8 => 6.2.8
    @storybook/react: 6.2.8 => 6.2.8
    @storybook/theming: 6.2.8 => 6.2.8
```

**Additional context**
The browser console has only this:

```
GET http://localhost:9001/ 404 (Not Found)
```

There's nothing interesting in the Network tab in devtools and start-storybook itself doesn't print out any errors. build-storybook works just fine and I can open that in my browser and all the stories load correctly, so the problem here seems specific to start-storybook.

**Comment by kaiyoma** [comment]
Oh also, I should add that when I searched for this problem in the other issues, I found a few semi-related posts that mentioned deleting `node_modules` and reinstalling packages. I tried that and nothing changed.

**Comment by kaiyoma** [comment]
Ah, I figured this out! Leaving a comment here in case some other poor soul runs into this in the future. If you've already tried blowing away `node_modules` and reinstalling packages, then you may have an issue with your Storybook cache. To fix this, run `start-storybook` once with the `--no-manager-cache` flag, and hopefully Storybook will work correctly for you. You only need to use this flag once; after that, the cache should be in a good state. The docs advise against using this flag all the time for performance reasons.

Reference: https://storybook.js.org/docs/react/api/cli-options

**Comment by shilman** [comment]
Glad you figured it out! I'm hoping we can do away with the manager caching soon ... it's good for perf but introduces a lot of unfortunate side effects.

**Comment by baticodes** [comment]
I had the same issue with v6.3.8, but @kaiyoma saved my day 🤗.

**Comment by thayna-oliveira** [comment]
thank you @kaiyoma, you saved my day!! :hugs:
