### ISSUE TITLE
Controls filtering doesn't work

### ISSUE THREAD

**Issue by darkowic** [storybookjs/storybook#14674]
**Describe the bug**
The controls filtering feature (https://storybook.js.org/docs/react/essentials/controls#filtering-controls) introduced in issue https://github.com/storybookjs/storybook/issues/11638 (PR https://github.com/storybookjs/storybook/pull/13898) doesn't work at all.

**To Reproduce**
Try this story:
```tsx
import React from 'react';
import PropTypes from 'prop-types';

export const TestComponent = () => <div />;
TestComponent.propTypes = {
    prop1: PropTypes.number,
    prop2: PropTypes.string,
};

export default {
    component: TestComponent,
    title: 'Test',
    args: {},
};

const Template = () => <TestComponent />;

export const ExampleStory = Template.bind({});

ExampleStory.parameters = {
    controls: {
        exclude: ['prop1'],
    },
};
```

![Screenshot 2021-04-21 at 11 35 21](https://user-images.githubusercontent.com/11510581/115532002-a9f27c80-a295-11eb-9e04-5ed0d70df5d6.png)

**System**

Storybook: 6.2.1

Environment Info:

  System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 14.14.0 - ~/.nvm/versions/node/v14.14.0/bin/node
    Yarn: 1.19.1 - ~/.nvm/versions/node/v14.14.0/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.14.0/bin/npm
  Browsers:
    Chrome: 90.0.4430.85
    Firefox: 85.0.1
    Safari: 14.0.3

**Additional context**
Looks like the feature is not tested at all by any unit test etc. It's bad...

**Comment by yannbf** [comment]
Hey @darkowic, thanks for reporting. I tried to reproduce the issue with the code you provided (small fixes as it was not 100% correct) and Storybook 6.2.1, but it was working fine.

Here's a video (click on it if you want to see it bigger):
![controlsworking](https://user-images.githubusercontent.com/1671563/115613063-3e87c980-a2ec-11eb-924f-3079ac60f6df.gif)

Could you provide an example that looks more like the real scenario you're facing?

**Comment by darkowic** [comment]
Hmm. Ok, I tried again and I see where is the difference... This doesn't work:
```tsx
const Template = () => <TestComponent />;

export const ExampleStory = Template.bind({});

ExampleStory.parameters = {
    controls: {
        exclude: ['prop1'],
    },
};
```
This does work:
```tsx
const Template = args => <TestComponent />;

export const ExampleStory = Template.bind({});

ExampleStory.parameters = {
    controls: {
        exclude: ['prop1'],
    },
};
```
This doesn't work:
```tsx
export const ExampleStory = () => <TestComponent />;

ExampleStory.parameters = {
    controls: {
        exclude: ['prop1'],
    },
};
```
This does work:
```tsx
export const ExampleStory = args => <TestComponent />;

ExampleStory.parameters = {
    controls: {
        exclude: ['prop1'],
    },
};
```

Well, it's not easy to catch these kinds of issues... You don't even need to pass the args to the component to make it work. Do you have ideas on how to help us, users, easily find it is the problem? Or maybe it can be done differently?

I see another difference now - if `args` is missing in the story function arguments, there is no option to change the control value. Now I see it and understand but it was not so obvious :)

**Comment by yannbf** [comment]
First thing you should understand is the purpose of controls: a way to manipulate properties of a component. In order for that to be possible, a minimal setup is required, as you can find in the [docs](https://storybook.js.org/docs/react/essentials/controls) (which I hope you checked before opening the issue):
```
To use the Controls addon, you need to write your stories using args. 
Storybook will automatically generate UI controls based on your args and what it can infer about your component; 
but you can configure the controls further using argTypes, see below.
```

If you're not passing args (they can be seen as props), then Storybook is not able to manipulate your component's props. Your example does not make much sense as your TestComponent does not accept any prop as well.

Why? This should help you visualize:

```jsx
// whenever args are changed via controls, they are passed down as props to the component
// which rerenders with new values. Therefore args are needed
const Template = (args) => <MyComponent {...args} /> 
```

In case you do have automatically inferred props but you do not pass args to your template/story, you should see a banner explaining how to enable it:
![image](https://user-images.githubusercontent.com/1671563/115715713-b56aa400-a378-11eb-9698-87100a865f21.png)


Your real use case would be something like:
```jsx
// Component.jsx
export const MyComponent = (props) => (<div>{props.label}</div>)

// Component.stories.jsx
import { MyComponent } from './Component'

export default {
  title: 'MyComponent',
  component: MyComponent,
}

const Template = (args) => <MyComponent {...args} /> // whenever args are changed, they are passed down as props to the component, which rerenders with new values

export const Example = Template.bind({})
Example.args = {
  label: 'hello world'
}
```

If you feel like this is not optimal, feel free to contribute to the docs and help us give a better experience for all users :)

**Comment by darkowic** [comment]
Ah, yes I understand how it works, and thank you for the additional explanation. And indeed the warning should be there if someone did not disable it globally (`hideNoControlsWarning`) as it is in our storybook 🤦  I will revisit and make sure the warning is not disabled globally... Thank you.

Anyways, even if the controls are improperly configured (or we don't want to configure it by purpose but still want to show the properties table) should the properties in the table still be filtered?

**Comment by yannbf** [comment]
Sorry for the late reply! It's certainly something to consider, but currently not implemented.

**Comment by shilman** [comment]
Crikey!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.3.0-alpha.29 containing PR #14684 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
