### ISSUE TITLE
Control nested property moving "Knob" to "Control"

### ISSUE THREAD

**Issue by dohomi** [storybookjs/storybook#14687]
**What's the problem?**
I used knobs and try to get ready for controls of Storybook. For any value where the property value needs to be controlled directly as first level props everything works fine.
But I have a situation where I want to control an object property not as JSON but just one property which represents the value.

**Additional context**
This is my `knob` code:
```ts
import {  color } from '@storybook/addon-knobs'
// old
const getComponentKnob = (values: any) => {
  return {
    color: {
      rgba: color('color', values?.color?.rgba)
    }
  }
}
// new
const getComponentControl = () => {
  return {
     color: {
       // here I want to set the nested property `rgba` to be controlled
       control: { type: 'color' }
     }
  }
}

```
I like to have the control of the color picker on the nested value `color.rgba` instead of `color`. Is this possible with `controls`? Currently I see the JSON editor and I don't find a way to control this nested property value.

**Comment by shilman** [comment]
You can do whatever you want to in your story function. I'm not sure what you're trying to do, but here's an example of doing something weird to control only one component of the color value:

```
argTypes: {
  transparency: { control: 'number' }
}

...

export const Story = ({ transparency, ...}) => {
  const customColor = new Color(baseColor, transparency);
  return <MyComponent color={customColor} ... />
}
```

Hope that helps!

**Comment by dohomi** [comment]
@shilman thanks for your reply.
Currently I do following: 
```ts
const COMPONENT_NAME = 'image'
export default { 
  title: Component_name,
  argTypes: {
    ...getComponentArgTypes(COMPONENT_NAME)
  }
}
// here I have a function to map component props to controls
function getComponentArgTypes(componentName: string){
  const componentStructure = getComponentStructure(componentName)
  const controls = {}
  (...) // logic to map structure to controls based on componentName
  return controls
}
```
I will try to follow your advise thanks!

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
