### ISSUE TITLE
Option to turn off `Show code` & `Hide code` in the preview panel

### ISSUE THREAD

**Issue by MichaelTrilford-Airwallex** [storybookjs/storybook#14686]
**Is your feature request related to a problem? Please describe**

1. I'm creating 'Design Tokens' documentation page on Storybook.
2. I'm creating a story representing a group of 'Design tokens', which isn't the best looking code to preview, as it isn't useful to the consumer to read or consume. See below:

E.g.
`() => {
  return (
    <div css={{ maxWidth: 1080, margin: '20px auto' }}>
      <Table
        heads={Heading}
        rows={Object.keys(weight100).map((key) => ({
          token: `borders.100.${key}`,
          value: weight100[key],
          example: weight100[key],
        }))}
        columnDecorations={{
          example: DecorateSwatch,
          token: DecorateToken,
        }}
        showPagination={false}
      />
    </div>
  );
}`

3. On the 'Docs' tab, I'm displaying the output, however consumers can expand the 'show code' panel, and view the setup code [see above], which isn't required nor helpful to the consumer of the design system.
4. I want to hide the 'show code' & 'hide code' functionality in this instance

**Describe the solution you'd like**

Configuration to hide this panel:

<img width="1039" alt="Screen Shot 2021-04-22 at 10 24 47 am" src="https://user-images.githubusercontent.com/75596057/115638095-0d8faf00-a355-11eb-86af-460880e7ff3b.png">

**Describe alternatives you've considered**
-

**Are you able to assist to bring the feature to reality?**
Most likely not, happy to try.

Any help will be much appreciated.

**Comment by shilman** [comment]
I think this already exists:

https://github.com/storybookjs/storybook/blob/next/examples/official-storybook/stories/addon-docs/addon-docs-mdx.stories.mdx#L198-L208

**Comment by tklives** [comment]
I'll leave this here in case it can be of help to anyone else, because I've been unable to find anything about this.

If you don't want the "Show/Hide Code" button to appear, just don't wrap your `<Story>` in a `<Canvas>` element.  

```jsx
<Story name="Cool bro">
  <RadComponent />
</Story>

Then what renders is just your component without the border/shadow/button/etc., and it is still accessible from the left nav.

Right, wrong, or otherwise, this has worked for me!

**Comment by MichaelTrilford-Airwallex** [comment]
> If you don't want the "Show/Hide Code" button to appear, just don't wrap your `<Story>` in a `<Canvas>` element.

I'm not sure why I didn't try this! Both comments above helped, thanks all.

**Comment by annidavenport** [comment]
I'd like to be able to do this because just displaying the component in the docs page breaks my component due to all the storybook styling that's injected that I can't turn off.  If anyone knows how to get rid of the storybook styling please let me know, otherwise a <Preview> block with no 'show code' function would do me quite nicely!

**Comment by Miguel-Bento-Github** [comment]
Is there a possibility of doing this at `preview.js`?

**Comment by dungle-scrubs** [comment]
In my individual stories, I'm adding

```
parameters: {
    docs: {
      source: {
        code: null,
      },
    },
  },
```

Instead of "Show code" it says "No code available" and is grayed out.

**Comment by dep** [comment]
It would be cool if you could do this within an individual `<Story />` with a prop, for example:

```
This one has a code sample

<Canvas>
  <Story>
   ...
  </Story>
</Canvas>

This one does not

<Canvas>
  <Story code={null}>
   ...
  </Story>
</Canvas>
```

**Comment by robstarbuck** [comment]
My current fix for this is:

```
<Canvas withSource="none">
  ...
</Canvas>
```

@shilman  _Thanks but your link now returns a 404_

**Comment by cseas** [comment]
> My current fix for this is:
> 
> ```
> <Canvas withSource="none">
>   ...
> </Canvas>
> ```
> 
> @shilman _Thanks but your link now returns a 404_

This works perfectly. Thank you!
This really should be in the docs.

We can't write stories in MDX anymore starting from Storybook v7 so this is the only way. Rendering the component directly is a problem because Storybook's CSS styles take precedence over your CSS classes. 

Canvas helps isolate the styles for what you're rendering, but sometimes the source just doesn't make sense because all you're doing is importing the component from another file.

**Comment by rogerprz** [comment]
> I think this already exists:
> 
> https://github.com/storybookjs/storybook/blob/next/examples/official-storybook/stories/addon-docs/addon-docs-mdx.stories.mdx#L198-L208

File not found

**Comment by sergeychumak** [comment]
> withSource="none"

"storybook": "7.6.10",
<Canvas of={ButtonStories.Preview} **sourceState**="none" />

**Comment by ronsims2** [comment]
For storybook 8.3.5, the following story configuration will hide the "show code" button:
```
export const Foobar = {
    // the name below will render as the name of the story instead of "Foobar"
    name: "A name other than Foobar",
    parameters: {
        docs: {
            canvas: {
                // This will remove the "show code" button
                // https://storybook.js.org/docs/api/doc-blocks/doc-block-canvas#sourcestate
                sourceState: "none"
            }
        }
    }
}
```

**Comment by Yoann-CR** [comment]
> For storybook 8.3.5, the following story configuration will hide the "show code" button:
> 
> ```
> export const Foobar = {
>     // the name below will render as the name of the story instead of "Foobar"
>     name: "A name other than Foobar",
>     parameters: {
>         docs: {
>             canvas: {
>                 // This will remove the "show code" button
>                 // https://storybook.js.org/docs/api/doc-blocks/doc-block-canvas#sourcestate
>                 sourceState: "none"
>             }
>         }
>     }
> }
> ```

It works well but there seems to be a side effect :
It hides description and default columns in stories pages. Am I the only one with this problem?
