### ISSUE TITLE
Cannot set property variable of [object Object] which has only a getter (angular-redux)

### ISSUE THREAD

**Issue by adrianiy** [storybookjs/storybook#14680]
**Describe the bug**
I'm using [angular-redux](https://github.com/angular-redux/platform) to manage application state in a multi-framework library. When i try to test a component that uses @select() to get application state (somthing like useSelect in react) i'm getting this error when storybook initialize component:

```
StorybookWrapperComponent_Host.ngfactory.js? [sm]:1 ERROR TypeError: Cannot set property filtersConfig of [object Object] which has only a getter
    at StorybookWrapperComponent.js:85
    at Array.forEach (<anonymous>)
    at StorybookWrapperComponent.ngAfterViewInit (StorybookWrapperComponent.js:84)
    at callProviderLifecycles (core.js:22076)
    at callElementProvidersLifecycles (core.js:22050)
    at callLifecycleHooksChildrenFirst (core.js:22040)
    at checkAndUpdateView (core.js:30642)
    at callWithDebugContext (core.js:31464)
    at Object.debugCheckAndUpdateView [as checkAndUpdateView] (core.js:31206)
    at ViewRef_.detectChanges (core.js:21457)
```

Anyway the state is loading correctly, i guess that this angular-redux selector has no setter so this line is not executable

```js
initialOtherProps.forEach(function (p) {
      _this.storyComponentElementRef[p] = initialProps[p];
 });
```

Could it be possible to ignore some component property in intialization?

**To Reproduce**

create a angular repo that uses angular-redux @select

**System**
  System:
    OS: Windows 10 10.0.19041
    CPU: (4) x64 Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
  Binaries:
    Node: 12.18.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 89.0.4389.128
    Edge: Spartan (44.19041.906.0), Chromium (90.0.818.42)
  npmPackages:
    @storybook/addon-actions: ^6.2.0-rc.11 => 6.2.8
    @storybook/addon-essentials: ^6.2.0-rc.11 => 6.2.8
    @storybook/addon-links: ^6.2.0-rc.11 => 6.2.8
    @storybook/addon-postcss: ^2.0.0 => 2.0.0
    @storybook/addon-viewport: ^6.1.21 => 6.2.8
    @storybook/angular: ^6.2.0-rc.11 => 6.2.8

**Additional context**

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid.

Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
