### ISSUE TITLE
Syntax error in the documentation

### ISSUE THREAD

**Issue by lucapu88** [storybookjs/storybook#14691]
![Schermata da 2021-04-22 10-37-30](https://user-images.githubusercontent.com/56302007/115684214-7710bd00-a357-11eb-89a5-f0aee442fd7b.png)

In your documentation there is an extra brace that gives an error in compilation, and for an inexperienced user, doing a copy and paste, could create problems......

**Comment by shilman** [comment]
I think this belongs on a different repo https://github.com/chromaui/learnstorybook.com

cc @jonniebigodes
