### ISSUE TITLE
Possible to divide an entire Frontend application, including Storybook/Chromatic, into different workspaces?

### ISSUE THREAD

**Issue by bromso** [storybookjs/storybook#14697]
## Sections:
1. [Idea](#history)
2. [Might inspire someone to create something cool.](#infrastructure)
3. [A explanation of the current tech-stack I'm working with.](#applications)
4. [My current problems & errors.](#challenges)

## History
When working in legacy web company & organisations, they usually trying to convert & divide their monolithic code into micro-services.
Coming into a relative new project in NodeJS at a company, it usually consist of a monorepo with ONE package.json file. Scrolling thru it usually takes an entire working day. 😉

## My idea
I've had a thought in regards to try to divide a project, with the same micro-service concept in mind. I'm working with workspaces and trying to separating all different parts of a frontend-based application to make it easier to debug & updating the entire project.

---

###### Infrastructure
```text
🧮  Project
┃
┠── 📁 packages
┃   │
┃   ├┄┄ 📁 api
┃   │   └┄┄ 📦 package.json
┃   ├┄┄ 📁 design
┃   │   └┄┄ 📦 package.json
┃   ├┄┄ 📁 docs
┃   │   └┄┄ 📦 package.json
┃   ├┄┄ 📁 tests
┃   │   └┄┄ 📦 package.json
┃   └┄┄ 📁 www
┃       └┄┄ 📦 package.json
┃
┠┄┄ 🐉 lerna.json
┠┄┄ 📦 package.json
┖┄┄ 🧶 yarn.lock

```

---

###### Applications
| Folder      | Application                                                                                             |
| ----------- | ------------------------------------------------------------------------------------------------------- | 
| API         | [GraphQL](https://graphql.org/), [Apollo](https://www.apollographql.com/), [Relay](https://relay.dev/) | 
| Docs        | [Storybook](https://storybook.js.org/)                                                                  | 
| Design        | [Figma](https://www.figma.com/)                                                                  | 
| WWW         | [Nuxt](https://nuxtjs.org/)                                                                             | 
| Tests       | [Cypress](https://www.cypress.io/), [Chromatic](https://www.chromatic.com/)                                                                      |

---

## Challenges

If someone knows a boilerplate or open-source project that are trying to do something similar to what I'm doing, please share a link to it so I don't have to reinvent the wheel here. 😉 😄  

I've recreated a simplified version of a repo I'm working on here: https://github.com/bromso/monorepo-with-microservices

In the more complexed version, Nuxt isn't working and producing this error:

```text
Error
Module build failed (from /Users/jonasbroms/Sites/monorepo-with-microservices/node_modules/css-loader/dist/cjs.js): ValidationError: Invalid options object. CSS Loader has been initialized using an options object that does not match the API schema. - options.modules has an unknown property 'compileType'. These properties are valid: object { auto?, mode?, exportGlobals?, localIdentName?, localIdentRegExp?, context?, hashPrefix?, getLocalIdent? } at validate (/Users/jonasbroms/Sites/monorepo-with-microservices/node_modules/css-loader/node_modules/schema-utils/dist/validate.js:98:11) at Object.loader (/Users/jonasbroms/Sites/monorepo-with-microservices/node_modules/css-loader/dist/index.js:36:28)
```

When running the simplified repo: https://github.com/bromso/monorepo-with-microservices

It is producing all kinds of errors. But not on Nuxt this time around, but in Storybook. The same type of errors happens in my more complexed version of the repo mention above. Some CSS API Schema errors.

HELP! Where do I start to debug?

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
