### ISSUE TITLE
addon-docs: Docgen component description does not generate anchor links

### ISSUE THREAD

**Issue by randak** [storybookjs/storybook#14709]
**Describe the bug**
I am in the process of converting an existing React Storybook to CSF format, and using `@storybook/addon-docs` to generate the description using the docgen method. Writing markdown inside of docblock comments on the components is working well, and is extracting and rendering headings that look the same as the others on the page—except they don't have anchor links. Since we are using this for testing instructions and usage notes, it would be helpful to be able to link to these sections.

I'm not sure if this is technically a bug or a feature request, but it seems like all headings should be generated using the same method, so I picked "bug".

Expected behavior:

**To Reproduce**
Define a story with a markdown docblock comment such as:
```js
/**
  * ## My heading
  * Some content
  */
const ExampleComponent = () => {
  return <div></div>
}
```

When this renders inside the storybook, `My heading` is not linkable.

**System**
```
Environment Info:

  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  Binaries:
    Node: 12.21.0 - /usr/local/opt/node@12/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.11 - /usr/local/opt/node@12/bin/npm
  Browsers:
    Chrome: 90.0.4430.85
    Safari: 13.1.3
  npmPackages:
    @storybook/addon-a11y: 6.2.2 => 6.2.2 
    @storybook/addon-actions: 6.2.2 => 6.2.2 
    @storybook/addon-docs: 6.2.2 => 6.2.2 
    @storybook/addon-essentials: 6.2.2 => 6.2.2 
    @storybook/addon-knobs: 6.2.2 => 6.2.2 
    @storybook/addon-links: 6.2.2 => 6.2.2 
    @storybook/addon-postcss: ^2.0.0 => 2.0.0 
    @storybook/addon-storysource: 6.2.2 => 6.2.2 
    @storybook/addons: 6.2.2 => 6.2.2 
    @storybook/react: 6.2.2 => 6.2.2 
    @storybook/source-loader: 6.2.2 => 6.2.2 
    @storybook/storybook-deployer: ^2.8.7 => 2.8.7 
    @storybook/theming: 6.2.2 => 6.2.2 
```

**Additional context**
N/A

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid.

Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
