### ISSUE TITLE
Setup fails to install storybook due to missing version

### ISSUE THREAD

**Issue by akita-programs** [storybookjs/storybook#14700]
**Describe the bug**

Unable to use the setup due to missing version of @storybook/addon-actions.

![image_2021-04-23_000944](https://user-images.githubusercontent.com/73960514/115817114-34d39400-a3c8-11eb-93dc-3ea70f0c3436.png)

**To Reproduce**
Link to a reproduction repo that demonstrates the bug, plus instructions on how to trigger it.

- Create any project, regardless of type, and install storybook using the CLI of npx.

**System**
Please paste the results of `npx sb@next info` here.

  System:
    OS: Windows 10 10.0.19042
    CPU: (4) x64 Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz  
  Binaries:
    Node: 14.16.0 - E:\Program Files\nodejs\node.EXE      
    npm: 6.14.11 - E:\Program Files\nodejs\npm.CMD        
  Browsers:
    Edge: Spartan (44.19041.906.0), Chromium (90.0.818.42)

**Comment by shilman** [comment]
Can't repro:

```
MMBP15:storybook shilman$ npm info @storybook/addon-actions

@storybook/addon-actions@6.2.9 | MIT | deps: 17 | versions: 795
```

Try clearing your yarn/npm cache and reinstalling

**Comment by AchilleasMich** [comment]
This is also happening in a clean environment with `@storybook/addon-docs`

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @storybook/core@6.2.9.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of '@storybook/addon-docs'
npm ERR! notarget
```

**Comment by stevendavisfoto** [comment]
I also get this same error just as of today.

**Comment by shilman** [comment]
i've seen this before where it takes time to propagate to different NPM servers around the world. it's definitely published. i'd recommend clearing your cache and trying again. and as a workaround, you can pin your versions to 6.2.8 and wait another few hours. this is an NPM bug, not a storybook one.

**Comment by stevendavisfoto** [comment]
"i'd recommend clearing your cache and trying again"

it's not a cache issue. our gitlab instance is having the same problem.

**Comment by akita-programs** [comment]
It was a problem with either your team not able to push the update to NPM fast enough, or NPM not pushing updates fast enough itself, and since then, has been fixed. Some of your libraries were out of version and do not fallback to prior versions in case. It'd be nice to see a fallback option just in case this happens again. I checked the Storybook libraries, and they're all up to date. It shouldn't happen anymore, but for other instances, it may. It wasn't a cache issue either, last night I checked and it was a version behind on the NPM site with the addons library.

If anything, please add some way to install it manually or a fallback option. I'm leaving it open for at least one more day.

**Comment by shilman** [comment]
> Some of your libraries were out of version and do not fallback to prior versions in case. It'd be nice to see a fallback option just in case this happens again.

Can you elaborate on this? Does NPM have some kind of fallback mechanism built in?

> It was a problem with either your team not able to push the update to NPM fast enough

The release process takes ~2 minutes from the start of pushing the first 6.2.9 package to the end of pushing the last 6.2.9 package. That means there is a 2 minute window where people might legitimately see this kind of problem.

I think this is a package propagation issue on NPM's side, and it's not the first time I've encountered this. If anybody has ideas for how to mitigate the problem on our side I'm all ears.

**Comment by akita-programs** [comment]
> Can you elaborate on this? Does NPM have some kind of fallback mechanism built in?
I have no clue, I wish NPM did if it doesn't. Though, building your own could help with the problem, cause usually updates are made a lot around React framework and others.
> If anybody has ideas for how to mitigate the problem on our side I'm all ears.
Possibly could make a quick package, specifically to fall back on installing if it fails for a version. I have NO clue how that would work, but I bet it would be nice to have a fallback option in place. Maybe NPM could integrate that idea somehow. We'll see.
