### ISSUE TITLE
Angular Material button classes are removed if the HostBinding('class') is used to add a class

### ISSUE THREAD

**Issue by sergey-orlov-arcadia** [storybookjs/storybook#14702]
**Describe the bug**
When Angular Material is used, and there's a directive to add a class to `mat-button` using `HostBinding('class')`, all material classes are removed and replaced with the class set in directive. That happens in Storybook only, not in a regular Angular app.

**To Reproduce**
I've created a repo to reproduce the issue
https://github.com/sergey-orlov-arcadia/angular-storybook-directive
Just run install and start the storybook - story "WithDirective" demonstrates the issue. There is a button with directive and two buttons without, to see the difference.

***To reproduce the issue from scratch***
Create a sample Angular project. Include Angular Material library. Create a following directive:
```
@Directive({
  selector: 'button[color]'
})
export class ColorDirective {
  @HostBinding('class') @Input() color;
}
```
Use the directive in the root component
```
<button mat-button color="custom">Custom button</button>
```
Create a story, that would render the root component
```
const Template: Story<AppComponent> = (args: AppComponent) => ({
  props: args,
  template: '<app-root></app-root>'
});
```
Compare the story with the actual app.

Application:
![image](https://user-images.githubusercontent.com/63732025/115851520-b3175100-a42f-11eb-9caa-718e0d36daea.png)

Story:
![image](https://user-images.githubusercontent.com/63732025/115850487-92023080-a42e-11eb-8fef-7e71f1ae42cb.png)

In devtools we can see that in the Storybook, the button has only one class, that was assigned via the directive: `class="custom"`. In the application, it has multiple classes, including the one that was assigned via the directive: `class="mat-focus-indicator mat-button mat-button-base mat-custom custom"`

**System**
System:
    OS: Windows 10 10.0.19042
    CPU: (4) x64 Intel(R) Core(TM) i5-7600 CPU @ 3.50GHz
  Binaries:
    Node: 14.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files\nodejs\yarn.CMD
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 89.0.4389.128
    Edge: Spartan (44.19041.906.0), Chromium (89.0.774.76)

**Comment by Jakob-em** [comment]
Maybe this is related to the difference between ivy and non ivy. Because storybook doesn't use ivy at the moment, but your application probably does.

**Comment by sergey-orlov-arcadia** [comment]
@Jakob-em You might be right - I've managed to install the Ivy addon from https://github.com/storybookjs/addon-angular-ivy and this issue have disappeared. The addon integration doesn't work seamlessly - or, most probably, I just do it the wrong way - but I guess that after v6.3.0 it would be fine.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid.

Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
