### ISSUE TITLE
How to change Storybook icon and name with custom icon and name ?

### ISSUE THREAD

**Issue by utkarsh22garg** [storybookjs/storybook#14712]
**What's the problem?**
How to change Storybook icon and name with custom icon and name ?

**Is there documentation on this?**
I saw some projects like Reaviz pass their custom icon and name in storybook side panel, but couldn't see any documentation to do it. Please refer to the image below.

![image](https://user-images.githubusercontent.com/31355903/116003828-73ae5780-a61d-11eb-8cd5-7ecd2fa16747.png)

Can someone please tell me how to achieve this ?

**Comment by shilman** [comment]
https://storybook.js.org/docs/react/configure/theming#create-a-theme-quickstart

**Comment by utkarsh22garg** [comment]
Thanks @shilman !
