### ISSUE TITLE
addon-docs: Default code block syntax highlighting has contrast issues

### ISSUE THREAD

**Issue by randak** [storybookjs/storybook#14711]
**Describe the bug**
When writing a code block inside of a Storybook page (in this case, generated from a component description using docgen), the syntax highlighting causes contrast issues that hamper readability of the code example.

<img width="276" alt="Screen Shot 2021-04-25 at 3 19 21 AM" src="https://user-images.githubusercontent.com/2506770/115971918-8bca9c00-a575-11eb-9b8e-9f3605e70542.png">

**To Reproduce**
Include the following in a doc block:
```
/**
 * ```tsx
 * import React from 'react'
 * import { CheckboxGroup } from '../components'
 *
 * interface State {
 *   fruits: {
 *     [key: string]: boolean
 *   }
 * }
 * ```
 */
```

**System**
Please paste the results of `npx sb@next info` here.
```
Environment Info:

  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  Binaries:
    Node: 12.21.0 - /usr/local/opt/node@12/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.11 - /usr/local/opt/node@12/bin/npm
  Browsers:
    Chrome: 90.0.4430.85
    Safari: 13.1.3
  npmPackages:
    @storybook/addon-a11y: 6.2.2 => 6.2.2 
    @storybook/addon-actions: 6.2.2 => 6.2.2 
    @storybook/addon-docs: 6.2.2 => 6.2.2 
    @storybook/addon-essentials: 6.2.2 => 6.2.2 
    @storybook/addon-knobs: 6.2.2 => 6.2.2 
    @storybook/addon-links: 6.2.2 => 6.2.2 
    @storybook/addon-postcss: ^2.0.0 => 2.0.0 
    @storybook/addon-storysource: 6.2.2 => 6.2.2 
    @storybook/addons: 6.2.2 => 6.2.2 
    @storybook/react: 6.2.2 => 6.2.2 
    @storybook/source-loader: 6.2.2 => 6.2.2 
    @storybook/storybook-deployer: ^2.8.7 => 2.8.7 
    @storybook/theming: 6.2.2 => 6.2.2 
```

**Additional context**
N/A

**Comment by shilman** [comment]
I think this is due to conflicts between your project's CSS and the built-in theme.

**Comment by randak** [comment]
@shilman You're right, we are in the process of migrating from storybook-readme and I think the style is coming from there. I initially thought it was from Storybook because it wasn't in our code :) I'll close this, thanks.
