### ISSUE TITLE
Clean install angular and storybook are broken

### ISSUE THREAD

**Issue by NeoSimvolist** [storybookjs/storybook#14716]
**Describe the bug**
Launching a storybook results in an error:
ENOENT: no such file or directory, lstat 'D:/D/src/ng11/tsconfig.app.json'
![image](https://user-images.githubusercontent.com/7588392/116042717-ef99b580-a698-11eb-976c-c77bf90f2f2f.png)

**To Reproduce**
npm install -g @angular/cli
ng new app
npx sb@next init --builder webpack5
npm run storybook

or repo https://github.com/NeoSimvolist/ng-storybook-reproduce

**System**
Environment Info:

  System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-2670QM CPU @ 2.20GHz
  Binaries:
    Node: 14.3.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 90.0.4430.85
    Edge: Spartan (44.19041.906.0), Chromium (90.0.818.46)
  npmPackages:
    @storybook/addon-actions: ^6.3.0-alpha.14 => 6.3.0-alpha.14
    @storybook/addon-essentials: ^6.3.0-alpha.14 => 6.3.0-alpha.14
    @storybook/addon-links: ^6.3.0-alpha.14 => 6.3.0-alpha.14
    @storybook/angular: ^6.3.0-alpha.14 => 6.3.0-alpha.14
    @storybook/builder-webpack5: ^6.3.0-alpha.14 => 6.3.0-alpha.14

**Comment by shilman** [comment]
It works for me when I check out your repro & run

```
npm install
npm run storybook
```

Am I missing something?

**Comment by NeoSimvolist** [comment]
> It works for me when I check out your repro & run
> 
> ```
> npm install
> npm run storybook
> ```
> 
> Am I missing something?

Really. If you just clone a repository and run npm install, npm run storybook, then the build will go further. But if you do everything in steps, then there will be the above error. Perhaps this is not critical, but strange.

However, later on, I still get the error. Maybe that's another story
![image](https://user-images.githubusercontent.com/7588392/116049519-903fa380-a6a0-11eb-8999-1b8bdc2e615d.png)

**Comment by Jakob-em** [comment]
Looks like a duplicate of https://github.com/storybookjs/storybook/issues/14703

**Comment by NeoSimvolist** [comment]
> > It works for me when I check out your repro & run
> > ```
> > npm install
> > npm run storybook
> > ```
> > 
> > 
> > Am I missing something?
> 
> Really. If you just clone a repository and run npm install, npm run storybook, then the build will go further. But if you do everything in steps, then there will be the above error. Perhaps this is not critical, but strange.
> 
> However, later on, I still get the error. Maybe that's another story
> ![image](https://user-images.githubusercontent.com/7588392/116049519-903fa380-a6a0-11eb-8999-1b8bdc2e615d.png)
