### ISSUE TITLE
[Angular] Going back to a component already loaded throws an error

### ISSUE THREAD

**Issue by kanidjar** [storybookjs/storybook#14717]
**Describe the bug**

1. Display Component A
2. Display Component B
3. Display Component A

<img width="1434" alt="Capture d’écran 2021-04-26 à 10 25 18" src="https://user-images.githubusercontent.com/12607242/116052238-b69e1880-a679-11eb-9955-82277987d46d.png">

https://www.loom.com/share/ddb9919ac5604eceac92c3b3a184b370

**System**

`````
Environment Info:

  System:
    OS: macOS 11.0.1
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  Binaries:
    Node: 14.15.1 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.14.13 - /usr/local/bin/npm
  Browsers:
    Chrome: 90.0.4430.85
    Safari: 14.0.1
  npmPackages:
    @storybook/addon-essentials: ^6.2.9 => 6.2.9 
    @storybook/angular: ^6.2.9 => 6.2.9 
`````

**Comment by shilman** [comment]
Do you have a repro repo you can share?

**Comment by kanidjar** [comment]
@shilman 

https://github.com/kanidjar/storybook

````
npm install && nx run extranet:storybook
``````

**Comment by kanidjar** [comment]
hi @shilman, could you reproduce the issue? this is critical here since we have to refresh the page every time we switch from a composant to another one.

**Comment by mangei** [comment]
I could reproduce it here: https://github.com/storybookjs/storybook/issues/14026#issuecomment-827824481

**Comment by shilman** [comment]
closing as duplicate to #14026
