### ISSUE TITLE
Storybook 6 with Typescript, choosing webpack 5 as builder breaks props table generation

### ISSUE THREAD

**Issue by kelly-tock** [storybookjs/storybook#14721]
**Describe the bug**
From a fresh install with just react, react-dom, and typescript, and a tsconfig file generated from `tsc --init`, the default setup is working great! the props table in docs picks up the descriptions on the interface for props, etc. 

choosing webpack 5 as the builder breaks this functionality!

before choosing webpack 5:
![image](https://user-images.githubusercontent.com/39061683/116075655-d113ca00-a658-11eb-92f5-09df6a9fbd3a.png)

after choosing webpack 5:
![image](https://user-images.githubusercontent.com/39061683/116075464-9ca00e00-a658-11eb-8dfc-f98288089542.png)

**To Reproduce**
Link to a reproduction repo that demonstrates the bug, plus instructions on how to trigger it.
https://github.com/kelly-tock/sb-6-repro

**System**
Please paste the results of `npx sb@next info` here.
```
Environment Info:

  System:
    OS: macOS 11.2.3
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  Binaries:
    Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v14.16.0/bin/npm
  Browsers:
    Chrome: 90.0.4430.85
    Edge: 90.0.818.46
    Firefox: 83.0
    Safari: 14.0.3
  npmPackages:
    @storybook/addon-actions: ^6.2.9 => 6.2.9 
    @storybook/addon-essentials: ^6.2.9 => 6.2.9 
    @storybook/addon-links: ^6.2.9 => 6.2.9 
    @storybook/builder-webpack5: ^6.2.9 => 6.2.9 
    @storybook/react: ^6.2.9 => 6.2.9 
```

**Additional context**

**Comment by ulrichgreen** [comment]
Yes! After hours of debugging, I also found this to be the case. Anyone have any idea about how to fix it? Even temporarily is fine, until it gets fixed.

**Comment by shilman** [comment]
closing as dupe to #14118

**Comment by kelly-tock** [comment]
Cool my bad. GitHub search has failed me yet again 😭
