### ISSUE TITLE
Story<MyProps> type is missing `children`

### ISSUE THREAD

**Issue by IronSean** [storybookjs/storybook#14727]
**Describe the bug**
The Story<MyProps> type is missing the children prop, preventing children from being set on the args when binding to a template.

**To Reproduce**
```typescript
import React from 'react';
import { Story, Meta } from '@storybook/react/';

interface BoxProps {
  padding: number;
}

const Box: React.FC<BoxProps> = ({ padding = 0, children }) => (
  <div style={{ padding: `${padding}px` }}>{children}</div>
);

const meta: Meta = {
  title: 'components/Box',
  component: Box,
};

export default meta;

const Template: Story<BoxProps> = (args) => (
  <Box {...args} />
);

export const Default = Template.bind({});
Default.args = {};

export const Padding = Template.bind({});
Padding.args = { padding: 10};

export const Children = Template.bind({});
Children.args = { children: <p>Test</p> };
```

**System**
  System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 7.7.6 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 89.0.4389.128
    Edge: Spartan (44.19041.906.0), Chromium (90.0.818.46)
  npmPackages:
    @storybook/addon-actions: ^6.2.8 => 6.2.8
    @storybook/addon-essentials: ^6.2.8 => 6.2.8
    @storybook/addon-links: ^6.2.8 => 6.2.8
    @storybook/preset-ant-design: 0.0.2 => 0.0.2
    @storybook/react: ^6.2.8 => 6.2.8

**Additional context**
For some UI components like "Stack" or "Box", creating a story it's really logical without setting children. And further, to show things like a stack different stories might need different children. Unfortunately since Story takes the props object directly it doesn't know if it's an `FC` or `VFC` to determine the presence of children, but currently it does not allow setting children in a TypeScript environment.

**Comment by wesleychew** [comment]
Have the same issue as well. Any workaround/fix?

**Comment by IronSean** [comment]
> Have the same issue as well. Any workaround/fix?

One workaround is to manually define the children prop on your props interface..

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid.

Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
