### ISSUE TITLE
include webpack that is being used to the webpackFinal function

### ISSUE THREAD

**Issue by kelly-tock** [storybookjs/storybook#14725]
**Is your feature request related to a problem? Please describe**
it would be nice if when modifying webpack to pass the instance of webpack that is being used in storybook as part of the second parameter to `webpackFinal` so that you can destructure it to be something like:

```
webpackFinal: (config, { configType, webpack }) => {
....do stuff like webpack.DefinePlugin(...
return config;
}

**Describe the solution you'd like**
A clear and concise description of what you want to happen.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.

**Are you able to assist to bring the feature to reality?**
yes, I can...

**Additional context**
Add any other context or screenshots about the feature request here.

**Comment by shilman** [comment]
Good idea. @ndelangen any thoughts on this?

**Comment by ndelangen** [comment]
I understand this API would be convenient, but..

I'd rather keep the StorybookOptions object as is (it's already too many things on it).

I propose we make this 'preset-able':

```js
module.exports {
  webpackFinal: async (config, { presets }) => {
    // presets.apply('webpack-module')
    return config
  }
}
```

**Comment by kelly-tock** [comment]
@ndelangen  not sure I understand. It is common if you are overriding or adding to webpack to require webpack in this file. What can happen is you may end up with 2 different versions of webpack, and it can cause pretty cryptic error messages. So if you are say just adding a variable via define plugin, this won't work if there are multiple versions of webpack. How would the code you suggested help folks to use the webpack that storybook is also using? Can you maybe expand that idea further?

**Comment by ndelangen** [comment]
I updated my proposal, sorry I was a bit brief. I was mainly explaining this to @shilman.

**Comment by kelly-tock** [comment]
Ah ok got it. I'm happy to help with this, is there any existing code that does this style?

**Comment by ndelangen** [comment]
@kelly-tock yeah this style already works, but `'webpack-module'` should be set in the storybook core.

**Comment by gaurav5430** [comment]
it is not clear what the final stance is on this. Can someone clarify?

I have a similar scenario where I am using DefinePlugin for which I need to require my own webpack right now. I would get into the same issues as mentioned above by @kelly-tock, and I would not like to be in a situation where there are 2 separate webpack versions.

**Comment by shilman** [comment]
@wKich you're using this right? https://github.com/storybookjs/storybook/pull/15016

**Comment by shilman** [comment]
closing this as solved in #15016 

```js
await presets.apply('webpackInstance')
```

**Comment by wKich** [comment]
> @wKich you're using this right? https://github.com/storybookjs/storybook/pull/15016

Yep, I'm

**Comment by gaurav5430** [comment]
is there some documentation about how this can be used in a consumer project to get access to the webpack instance used by storybook?

**Comment by shilman** [comment]
@gaurav5430 https://github.com/storybookjs/storybook/pull/15529/files
