### ISSUE TITLE
Accessing args in argTypes

### ISSUE THREAD

**Issue by ankitchouhan1020** [storybookjs/storybook#14722]
**What's the problem?**
I have two props in my react Icon component, theme and iconList. iconList shows a list of valid icons.
If theme is light, then iconList should shows lightIcons list. If it is dark, iconList will show darkIcons list.

User can toggle theme via the storybook control table. Initially, theme is light to we are showing lightIcons list. Now I want to display darkIcons list if theme is switched to dark.

I need to somehow access active args, in argTypes.

```ts
export default {
  title: 'Icon',
  component: Icon,
  argTypes: {
    iconName: {
      control: {
        type: 'select',
        options: LIGHT_ICON_LIST
      }
    }
  }
};


const Template: Story<IconProps> = (args) => {
  return <Icon {...args} />;
}

export const Icon = Template.bind({});

Icon.args = {
 theme: 'dark'
}
```

**Comment by shilman** [comment]
You could have a select called "theme" which can take either "light" or "dark" value (string), and then your story function could map that to a list of icons to pass to your component.

Alternatively you might try the built-in mapping feature in 6.2: https://storybook.js.org/docs/react/writing-stories/args#mapping-to-complex-arg-values

**Comment by ankitchouhan1020** [comment]
@shilman Thanks for your time. You got it a little wrong.

LIGHT_ICON_LIST and DARK_ICON_LIST are arrays of string that I want to show in the storybook table. So that user can select one value from that list and that selected string is passed as iconName prop in the component.

LIGHT_ICON_LIST = ['check', 'circle',.. ]
DARK_ICON_LIST = ['random', 'values', ..]

I need to show these list in the storybook table conditionally based on the selected theme.

**Comment by shilman** [comment]
Aha. Not possible!

**Comment by ankitchouhan1020** [comment]
Thanks for the fast reply though. Closing this issue then.
