### ISSUE TITLE
Is it possible to customize/extend search functionality to more than just names?

### ISSUE THREAD

**Issue by chadlavi-casebook** [storybookjs/storybook#14724]
I'd like to be able to include more than just the page name in search. For example, if I have an MDX page about input usage rules, and one of the sections of that page is about validations, then if a user searches "validation" on my storybook, I want this page to come up as a result.

Is there anything like, the ability to add keywords to a `<Meta>` or something? I can't find anything in the docs about this.

**Comment by shilman** [comment]
We don't currently have any plans for this. In an older version of search it included various extra fields (like `parameters.notes`) but this resulted in a very confusing UX. I think the closest thing to a solution would be #7711, but this isn't implemented yet

**Comment by chadlavi-casebook** [comment]
@shilman thanks. To get these in the search index, is the recommended pattern breaking up larger MDX files into smaller files that are part of the same sub-section instead? Something like a single MDX file `Inputs / Usage guide` moving to `Inputs / Usage Guide / ...` with individual MDX files for each section in the former file?

I wish it were possible to do this while still keeping those individual sections within a single scrollable page.

**Comment by shilman** [comment]
The current search really isn't designed for this use case, so I hesitate to even recommend a workaround. That said, if I wanted to hack the system, I would do something like this in your MDX file:

```md
# Here is my page

<Story name="Page title"></Story>

I'm going to type something here about my page

<Story name="Searchable"></Story>

More text here

<Story name="Another custom term"></Story>

...
```

I tried this and it kind of works. Each story generates a heading under Page title. The canvas for each story is blank. The name of each story is searchable. Clicking on the story scrolls to that part of the page.

**Comment by as-zlynn-philipps** [comment]
@shilman Unfortunately that doesn't work in 6.4.12, I get `render.js:49 Uncaught Error: Unable to render story docs-theme-reference-colors--customizing-colors as the component annotation is missing from the default export`.

I'd love it if there was an option to turn on/off the ability to search by heading. Then clicking a result takes you directly to the anchor link. That workaround would _kind of_ work like you said if it didn't throw an error.

**Comment by as-zlynn-philipps** [comment]
Actually, that does work with an empty fragment:

```jsx
<Story name="Searchable title"><></></Story>
```

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).

**Comment by jrencz** [comment]
@shilman 

I understand the need to reduce the backlog but in here it's not a problem with something working not as expected (which fits into the "reproduce") but rather a request to add something that's missing. Are there recommendations on how to reproduce "lack of something"?
