### ISSUE TITLE
There is a formatting problem with the code in MDX.

### ISSUE THREAD

**Issue by linxianxi** [storybookjs/storybook#14730]
**What's the problem?**
There is a formatting problem with the code in MDX

my mdx
![image](https://user-images.githubusercontent.com/47104575/116224351-24823700-a783-11eb-8afd-594f2165ca99.png)

show code
![image](https://user-images.githubusercontent.com/47104575/116224198-f00e7b00-a782-11eb-91d2-6ce84b2d1b5e.png)

my storybook config
```
export const parameters = {
  viewMode: 'docs',
  docs: { source: { type: 'code' } },
};
```

**Comment by shilman** [comment]
closing as dupe to #8078
