### ISSUE TITLE
`storyFn` is deprecated and will be removed in Storybook 7.0

### ISSUE THREAD

**Issue by BiancaArtola** [storybookjs/storybook#14738]
I am using @storybook/addon-actions @storybook/addon-essentials abd @storybook/react, all of them on version 6.2.9.

Everything is working fine but when I go to the docs tab, the following warning appears:

![image](https://user-images.githubusercontent.com/21174759/116310532-80978c00-a780-11eb-9662-991fc337128a.png)

But the weird thing here is that I am not using storyFn on my code. So I really don't know what does this warning mean.
Is this a bug from Storybook? Is there any way to avoid this warning on my project?

Thanks! Let me know if you need more information

**Comment by shilman** [comment]
There is a new way of rendering stories in Storybook 6.1, but but addon-docs doesn't fully it support yet. There is currently no way to hide the warning. The issue to fix the problem is here #12726
