### ISSUE TITLE
can not use jsx in decorators in preview.js 

### ISSUE THREAD

**Issue by farshidinanloo** [storybookjs/storybook#14742]
in [react-boilerplate](https://github.com/react-boilerplate/react-boilerplate) with storybook when try to add this decorator 

```
export const decorators = [
  (Story) => (
    <div>
      <Story />
    </div>
  )
];
```

it shows this error:
```
ERROR in ./.storybook/preview.js
Module build failed (from ./node_modules/@storybook/builder-webpack4/node_modules/babel-loader/lib/index.js):
SyntaxError:...\.storybook\preview.js: Unexpected token, expected "</>/<=/>=" (21:13)

  19 |   (Story) => (
  20 |     <div>
> 21 |       <Story />
     |              ^
  22 |     </div>
  23 |   )
  24 | ];
```

**Comment by shilman** [comment]
If you have a custom babel config, try deleting it for debugging purposes

**Comment by farshidinanloo** [comment]
@vanyadymousky 
well maybe, I comment babel.config.js when using storybook :)

**Comment by vanyadymousky** [comment]
@farshidinanloo Yes, it was about renaming decorators file preview.js to preview.tsx so jsx is now parsed correctly. 
Looks like I'm forced to do that since I've updated to 6.3.8 - in a case somebody hit same issue.

**Comment by Dreamufor** [comment]
Hi, I encounter the same issue, and I used React.createElement to solve the problem.

Before: 
```
export const decorators = [
  (Story) => (
    <ThemeProvider theme="default">
      <Story />
    </ThemeProvider>
  ),
];
```

Solutions: 
```
export const decorators = [
  (Story) => {
    return React.createElement(ThemeProvider, {
      children: React.createElement(Story),
    });
  },
];
```


Hope this helps! @farshidinanloo

**Comment by calpa** [comment]
@Dreamufor It works, thanks.

**Comment by cjones26** [comment]
Any update on this?  We are encountering the same issue and it's going to be a real pain to have to utilize @Dreamufor's solution for all of our decorators.

**Comment by cjones26** [comment]
For anyone having an issue with this, you need to make sure that Babel is properly transpilling your `preview.js` file or else you will get the above error.  

My `.storybook` directory is a shared config which is symlinked from `node_modules/@myorg/frontend-shared-config/.storybook` -- this symlink in combination with my custom Webpack configuration was causing the file not to be included in the Webpack rule linked to the `babel-loader` with the `preset-react`.  Once I added the Regex (`/@myorg\/frontend-shared-config/`) to the include path on that rule, it properly transpiled the JSX and the error went away.

**Comment by adrxlm** [comment]
I had the same issue, I found a workaround but I'm not sure if is implemented correctly

```
const clientConfig = require('../my-original-webpack.config')

// main.js

module.exports = {
webpackFinal: async (config, {configType}) => {
      config.module = {
        ...clientConfig.module,
        rules: [
          ...clientConfig.module.rules,
          {
            test: /\.(js|jsx)$/,
            loader: 'babel-loader',
            include: [resolve(__dirname, './')]
          }
        ]
      }
      config.context = clientConfig.context
      config.resolve = clientConfig.resolve
      config.externals = clientConfig.externals
      config.plugins = config.plugins.concat(clientConfig.plugins)
      return config
    }
  }
}
```

**Comment by mehmetdemiray** [comment]
change ->
preview.ts to .tsx
or
preview.js to .jsx
