### ISSUE TITLE
Can not change the theme of the "show code" section on the DocPage

### ISSUE THREAD

**Issue by Albert-Gao** [storybookjs/storybook#14740]
## Dependencies
```
    "@storybook/addon-a11y": "^6.2.9",
    "@storybook/addon-actions": "^6.2.7",
    "@storybook/addon-console": "^1.2.3",
    "@storybook/addon-essentials": "^6.2.9",
    "@storybook/addon-info": "^5.3.21",
    "@storybook/addon-knobs": "^6.2.9",
    "@storybook/addon-notes": "^5.3.21",
    "@storybook/addon-storysource": "^6.2.9",
    "@storybook/addon-viewport": "^6.2.7",
    "@storybook/react": "^6.2.9",
    "@storybook/ui": "^6.2.9",
```

## main.js
```javascript
module.exports = {
	stories: ['../src/newStories/**/*.stories.tsx'],
	addons: [
		'@storybook/addon-a11y',
		'@storybook/addon-notes',
		'@storybook/addon-essentials'
	],
	typescript: {
		check: false,
		checkOptions: {},
		reactDocgen: 'react-docgen-typescript',
		reactDocgenTypescriptOptions: {
			shouldExtractLiteralValuesFromEnum: true,
			propFilter: (prop) => (prop.parent ? !/node_modules/.test(prop.parent.fileName) : true)
		}
	}
};
```

## preview.js
```javascript
import { Provider } from 'react-redux';
import React from 'react';
import { ConfigureStore } from '@my-app/core/store/configure-store';
import { addDecorator } from '@storybook/react';
import StoryRouter from 'storybook-react-router';
import { themes } from '@storybook/theming';
import '!style-loader!css-loader!sass-loader!../src/newStories/scss/stories.scss';
import '!style-loader!css-loader!sass-loader!../src/assets/styles/index.scss';

const store = ConfigureStore.init();

addDecorator(StoryRouter());

export const decorators = [(story) => <Provider store={store}>{story()}</Provider>];

export const parameters = {
	docs: {
		source: {
			type: 'code'
		}
	}
};
```

## webpack.config.js
```javascript
const path = require('path');

module.exports = ({config}) => {
	config.module.rules.push(
		{
			test: /\.(ts|tsx)$/,
			loader: require.resolve('babel-loader'),
			options: {
				presets: [require.resolve('babel-preset-react-app')]
			}
		},
		{
			test: /\.scss$/,
			loaders: ['style-loader', 'css-loader', 'sass-loader'],
			include: path.resolve(__dirname, '../')
		}
	);

	config.resolve.extensions.push('.ts', '.tsx');
	config.resolve.alias = {
		'@my-app/core': path.resolve(__dirname, '../src/core/'),
		'@myapp/components': path.resolve(__dirname, '../src/components/'),
	};
	return config;
};
```

## The problem

The highlight of the source code is showing in an unreadable way, and do not seem to have a way to change it, what am I missing here? Thanks

![image](https://user-images.githubusercontent.com/18282328/116343468-94062e00-a838-11eb-8b0d-181b0560b3e5.png)

**Comment by shilman** [comment]
Your components' CSS styles are probably clashing with the styles in the source block. it's a problem with the addon-docs architecture that we hope to address in the next major release. i've heard that addon-readme also clashes.

**Comment by Albert-Gao** [comment]
Thanks, we do have some tag level styling that I am not a big fan of, but this is a legacy project, anyway I can rewrite the style in the `parameters` level? Thanks

**Comment by Albert-Gao** [comment]
Solved by adding some additional styles with `!important`

```css
code {
    border: unset !important;
    background-color: unset !important;
    color: unset !important;
}
```

The problem is with this css selector. `.code-inline code`:
![image](https://user-images.githubusercontent.com/18282328/116346876-31646080-a83f-11eb-8b15-7326bac5f19a.png)

I do not have any `.code-inline` CSS class in my codebase, so, interesting here.
![image](https://user-images.githubusercontent.com/18282328/116346938-535de300-a83f-11eb-80e9-a349e0aef913.png)

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
