### ISSUE TITLE
Preact is missing css modules 

### ISSUE THREAD

**Issue by ThunderArmy** [storybookjs/storybook#14751]
When following the documentation of storybook on preact and installing it, it does not enable css modules, which is very common in preact.

I'm unable to enable css-modules using a custom webpack config
The issue is related to https://github.com/storybookjs/storybook/issues/10140

**Comment by KrofDrakula** [comment]
@ThunderArmy Have you tried modifying the webpack configuration using this guide?

https://storybook.js.org/docs/react/configure/webpack#extending-storybooks-webpack-config

Can you share your example configuration?

**Comment by ThunderArmy** [comment]
@KrofDrakula I removed my custom webpack config and installed

https://github.com/Negan1911/storybook-css-modules-preset

which then worked fine for me

**Comment by KrofDrakula** [comment]
In that case, I'm closing this issue. Glad you found a solution that works for you!
