### ISSUE TITLE
The external imported component's typescript comment don't show in doc page.

### ISSUE THREAD

**Issue by szamosba** [storybookjs/storybook#14755]
**Describe the bug**
When I import a component outer from Storybook project into the Storybook, the Typescript comments do not appear on the doc page.
If I copy the same component into the Storybook project, the Typescript comments are nicely visible on the doc page.

**To Reproduce**
-

**System**
Environment Info:

  System:
    OS: Windows 10 10.0.18362
    CPU: (4) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  Binaries:
    Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 90.0.4430.93
    Edge: Spartan (44.18362.1.0)
  npmPackages:
    @storybook/addon-actions: ^6.1.16 => 6.2.9
    @storybook/addon-essentials: ^6.1.16 => 6.2.9
    @storybook/addon-links: ^6.1.16 => 6.2.9
    @storybook/addons: ^6.2.3 => 6.2.9
    @storybook/node-logger: ^6.1.16 => 6.2.9
    @storybook/preset-create-react-app: ^3.1.5 => 3.1.7
    @storybook/react: ^6.1.16 => 6.2.9
    @storybook/theming: ^6.2.3 => 6.2.9

**Additional context**
-

**Comment by shilman** [comment]
closing as dupe to #12185
