### ISSUE TITLE
Issue with Angular and Storybook

### ISSUE THREAD

**Issue by jonniebigodes** [storybookjs/storybook#14761]
**Describe the bug**
While updating the Intro to Storybook tutorial to reflect the changes introduced in Storybook 6.2 I came across a bit of a weird issue on how Storybook is displaying the stories incorrectly. Following the steps provided in the [Composite Component](https://storybook.js.org/tutorials/intro-to-storybook/angular/en/composite-component/) chapter, starting Storybook me or any other reader should get the following Storybook [state](https://storybook.js.org/tutorials/intro-to-storybook/finished-tasklist-states-6-0.mp4). But in reality, what I got was:

https://user-images.githubusercontent.com/22988955/116573757-ff1d3680-a904-11eb-9584-187b3b02b367.mp4

The Tasklist (default and with pinned tasks) should have rendered the stories correctly but instead, they're showing that there's nothing. Basically treating it as it was empty.

**To Reproduce**
- Clone this [repo](https://github.com/jonniebigodes/intro-storybook-angular-62)
- Install dependencies
- Run `npm run storybook`
- In `.storybook/preview.js` comment out `angularLegacyRendering: true,`
- Start Storybook with `npm run start-storybook``
- Check the Default and With Pinned story under TaskList.

@ThibaudAV could you take a look please and let me know what might be the issue here. As a safeguard, I adjusted the tutorial to mention to the readers that they should add the `angularLegacyRendering: true` to their `preview.js` in order to get the correct stories showing. 

Thanks in advance

**Comment by ThibaudAV** [comment]
yes i'll have a look ;)

**Comment by jonniebigodes** [comment]
Really appreciate it 🙏🏼! Let me know of your findings.

**Comment by ThibaudAV** [comment]
it's the same problem as here with workaround https://github.com/storybookjs/storybook/issues/14732#issuecomment-827674795
I have the impression that 80% of the angular issues are on this problem 😢 

I do not know how to fix in any case it is a breaking changes 🤣

---
You have this private props `tasksInOrder` that will follow these steps
1. is added in the doc of compodoc
2. then in argTypes 
3. then in args with defaultValue found by compodoc (`[]` in your case)
4. and finally Angular allows the override private properties
💥 

If you make the same test by changing the order of the props you will have the same problem 
try this : 
in `pure-task-list.stories.ts`
```
const Template: Story<PureTaskListComponent> = ({ tasks, ...args }: any) => {
  console.log(args);

  return {
    props: {
      tasks: args.tasks,
      ...args,
      onPinTask: TaskStories.actionsData.onPinTask,
      onArchiveTask: TaskStories.actionsData.onArchiveTask,
    },
    //template: `<app-pure-task-list [tasks]="tasks" [loading]="loading" (onPinTask)="onPinTask($event)" (onArchiveTask)="onArchiveTask($event)"></app-pure-task-list>`,
  };
};
```
you will have the same problem whatever the value of `angularLegacyRendering`

so between legacy and non-legacy renderer does not process props in the same order
and even more it depends on the property order of the args object


which is comical ; is that the new renderer uses the Input/Output like a real application. so no more problem of property order 
but as it keeps the ability to override the private properties it prevents a correct working

---
there are several problems already discussed in other issus with @shilman 

IMHO the main ones are : 
- `argTypes` should be able to display some doc without adding a value in `args`

- Angular should not override private properties by default. but do it only if explicitly requested
 (And maybe also change the order of assignment of properties with props)

---

Sources ((so much magic in these lines of code )): 
old :
https://github.com/storybookjs/storybook/blob/a8770a4a8e69b441b56cc3c2a1e906e913e0907c/app/angular/src/client/preview/angular/components/app.component.ts#L89-L91 
new:
https://github.com/storybookjs/storybook/blob/d72337ee78972645a4823030c9a0ad268eccd4fa/app/angular/src/client/preview/angular-beta/StorybookWrapperComponent.ts#L138
https://github.com/storybookjs/storybook/blob/d72337ee78972645a4823030c9a0ad268eccd4fa/app/angular/src/client/preview/angular-beta/StorybookWrapperComponent.ts#L94

**Comment by shilman** [comment]
@ThibaudAV if you have time today let's meet and talk this through and fix it.

**Comment by jonniebigodes** [comment]
@ThibaudAV thank you very much for the help on this and for pointing me in the right direction 🙏🏼. I was able to address the issue with the issue you've mentioned. And just merged an update for the tutorial with this. Really appreciate it.

**Comment by ThibaudAV** [comment]
can we close this issue ? :)
