### ISSUE TITLE
Getting 'Cannot use import statement outside a module' when trying to use StoryShots 

### ISSUE THREAD

**Issue by paezao** [storybookjs/storybook#14764]
**What's the problem?**
I'm trying to generate storyshots using Jest, TypeScript, React-Native and React-Native-Web but I'm getting this error when, apparently, initStoryShots is trying to import my only story.

**Is there documentation on this?**
No, I haven't found anything related.

**Additional context**
My project currently uses:
- typescript
- react-native
- react-native-web
- styled-components/native
- jest
- storybook
- storybook-storyshots

**Comment by jenter** [comment]
bump +

**Comment by codewaseem** [comment]
Same here! I'm using this with the next.js project.

**Comment by ChrisJamesC** [comment]
I've used the following jest config which seems to fix the issue: 

In package.json: 
```
"jest": {
    "transformIgnorePatterns": [
      "node_modules/(?!@storybook|((jest-)?react-native|@react-native(-community)?)|expo(nent)?|@expo(nent)?/.*|@expo-google-fonts/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|native-base|react-native-svg)"
    ]
  }
```
Note the `@storybook` at the beginning of the transformIgnorePatterns regex. 

(I'm using expo, hence the slightly longer regex)

**Comment by ndelangen** [comment]
The future of storyshots is the test-runner:
https://storybook.js.org/docs/react/writing-tests/test-runner#page-top

And use the play function for expectations:
https://storybook.js.org/docs/react/writing-stories/play-function#page-top

We will not be making any improvement / changes to storyshots.
