### ISSUE TITLE
Storybook's webpack4 css-loader errors when using `localsConvention` and other module options

### ISSUE THREAD

**Issue by kintz09** [storybookjs/storybook#14766]
**Describe the bug**
When trying to modify the webpack configuration for .css files, specifically to configure css modules, using either of these two valid module options produces this error: `localsConvention` or `exportLocalsConvention` and `exportNames`.

```
ValidationError: Invalid options object. CSS Loader has been initialized using an options object that does not match the API schema.
 - options.modules has an unknown property 'localsConvention'. These properties are valid:
   object { auto?, mode?, exportGlobals?, localIdentName?, localIdentRegExp?, context?, hashPrefix?, getLocalIdent? }
    at validate (/Users/jordan/VIVEDRepos/storybook-css-loader-bug/node_modules/schema-utils/dist/validate.js:98:11)
    at Object.loader (/Users/jordan/VIVEDRepos/storybook-css-loader-bug/node_modules/@storybook/builder-webpack4/node_modules/css-loader/dist/index.js:36:28)
```

![image](https://user-images.githubusercontent.com/10118752/116634982-76a59280-a912-11eb-8765-3509cef6e39e.png)

**To Reproduce**
Test Repo: https://github.com/kintz09/storybook-css-loader-bug

1. Check out the test repo locally
2.  `npm install`
3. `npm run storybook:debug`
4. View the error in the console or web browser in storybook
5.  Comment out the `localsConvention` option and observe the error doesn't occur

**System**
Environment Info:

  System:
    OS: macOS 11.2.3
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
  Binaries:
    Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.12 - ~/.nvm/versions/node/v14.16.1/bin/npm
  Browsers:
    Chrome: 90.0.4430.93
    Edge: 90.0.818.49
    Firefox: 82.0.3
    Safari: 14.0.3
  npmPackages:
    @storybook/addon-actions: ^6.2.8 => 6.2.9 
    @storybook/addon-essentials: ^6.2.8 => 6.2.9 
    @storybook/addon-links: ^6.2.8 => 6.2.9 
    @storybook/addon-postcss: ^2.0.0 => 2.0.0 
    @storybook/preset-scss: ^1.0.3 => 1.0.3 
    @storybook/react: ^6.2.8 => 6.2.9 

**Additional context**
- Note that the @storyoook/preset-scss options in .storybook/main.js uses `exportLocalsConvention` but doesn't produce an error.
- Error can be traced back to `node_modules/@storybook/builder-webpack4/node_modules/css-loader/dist/index.js:36:28`
- Storybook builder-webpack4 is using [css-loader version 3.4.0](https://www.npmjs.com/package/css-loader/v/3.6.0) which claims to support `localsConvention`

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
