### ISSUE TITLE
Storybook interprets conditional in default argument as literal string

### ISSUE THREAD

**Issue by fast-reflexes** [storybookjs/storybook#14774]
**Describe the bug**
When a property of an argument object to a component has a default value resulting from a ternary `if`, Storybook somehow uses the entire condition as a string. This is not the case when the component is not shown in Storybook.

**To Reproduce**
Consider this simple component:

```
import React, { FC } from "react";

export interface ExampleProps {
    header?: string;
}

export const Example: FC<ExampleProps> = (
    {
        header = Date.now() % 2 === 1 ? "Uneven" : "Even",
    }
) => {

    return <p>{ header }</p>
};

export default Example;
```

And this story:

```
import React from 'react';
import {Meta, Story} from '@storybook/react/types-6-0';
import Example, { ExampleProps } from "./Example";

export default {
    title: 'Example',
    component: Example
} as Meta;

const Template: Story<ExampleProps> = args => <Example {...args}  />;

export const Basic = Template.bind({});
Basic.args = {};
```

Now, if we supply the `header` prop in our story:

    Basic.args = { header: "Header"};

... then the component correctly shows `Header` in Storybook. But when we don't:

    Basic.args = {};

... the component shows the whole default condition as a string: `Date.now() % 2 === 1 ? "Uneven" : "Even"`

This is not the case when the component is used outside of Storybook, like it is in  this [sandbox](https://codesandbox.io/s/storybook-default-params-45j4n).

**System**

```
Environment Info:

  System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 12.16.1 - /usr/local/bin/node
    npm: 6.13.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 90.0.4430.93
    Firefox: 88.0
    Safari: 14.0.3
  npmPackages:
    @storybook/addon-actions: ^6.0.28 => 6.2.7 
    @storybook/addon-controls: ^6.0.28 => 6.2.7 
    @storybook/addon-essentials: ^6.2.9 => 6.2.9 
    @storybook/addon-links: ^6.0.28 => 6.2.7 
    @storybook/node-logger: ^6.0.28 => 6.2.7 
    @storybook/preset-create-react-app: ^3.1.5 => 3.1.7 
    @storybook/react: ^6.2.9 => 6.2.9 

```

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid.

Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
