### ISSUE TITLE
Full page reload when assets change in static folder

### ISSUE THREAD

**Issue by fast-reflexes** [storybookjs/storybook#14771]
**What's the problem?**
Storybook offers the possibility to serve static content from some folder with flag `-s`. However, it seems impossible to configure Storybook to do a full page reload when assets change in this directory, and as a result, it is necessary to  manually refresh the page.

The same behaviour exists in CRA starting with fast refresh whereupon some source files can be modified and result in updated ui whereas other changes to assets requires a manual page refresh. Nonetheless, in CRA, this can be solved by supplying environment variable `FAST_REFRESH=false` whereupon full page reload (hot reload) takes place at all times when any assets change (both static and source files).

**Additional context**
I don't know if the behaviour in Storybook is a result of fast refresh or not (I think I tried to solve this before React 17 came too but with no success).

* I have attempted to turn off fast refresh with both environment variable `FAST_REFRESH=false` and in `main.js` with 

        reactOptions: {
            fastRefresh: false
        }
* I have attempted to modify the Webpack config to make sure that the dev server is watching the static folder in use (seems that some webpack config directives are overwritten or not accepted by Storybook).

None of my attempts have been successful and my question is, **is it possible to have storybook automatically do a full page reload when assets in the static folder are changed?**

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
