### ISSUE TITLE
Storybook Docs default name based on filename / filepath

### ISSUE THREAD

**Issue by TheKnarf** [storybookjs/storybook#14786]
**What's the problem?**
I would like to be able to add documentation to my Storybook setup thats already written in MDX without having to change them. That would mean that I need some way of setting the name that doesn't involve going through each MDX file and adding a storybook import and meta-component.

Would it be possible to activate some option that would let storybook simply use the filename / pathname as it's default title?

**Is there documentation on this?**
Can't find any documentation

**Additional context**
Relates to #14787

**Comment by shilman** [comment]
closing this as dupe to #11186
