### ISSUE TITLE
Custom docs container breaks JSDocs

### ISSUE THREAD

**Issue by DominicTobias** [storybookjs/storybook#14781]
**Describe the bug**
Hey, `storybook-dark-mode` dark mode only half works by itself, we need to override the DocsContainer to have a dark theme there too as far as I can tell:

```js
export const parameters = {
  // ...
  docs: {
    container: DocsContainer,
  },
}
```

And make a DocsContainer:

```tsx
import { DocsContainer as BaseContainer } from '@storybook/addon-docs/blocks'
import { useDarkMode } from 'storybook-dark-mode'

import { sbLightTheme, sbDarkTheme } from './themes'

export function DocsContainer({ children, context }) {
  const dark = useDarkMode()

  return (
    <BaseContainer
      context={{
        ...context,
        parameters: {
          ...context.parameters,
          docs: {
            theme: dark ? sbDarkTheme : sbLightTheme,
          },
        },
      }}
    >
      {children}
    </BaseContainer>
  )
}
```

This works great except the `Description` component stops working. I couldn't get a description to appear from parameter overrides or from JSDocs (preferred).

Eventually I did a minimal repro and realised it stops working as soon as I add the DocsContainer.

**To Reproduce**
- Create a storybook with a custom DocsContainer.

e.g. https://github.com/DominicTobias/storybook-jsdocs-issue

**System**
```text
  System:
    OS: macOS 11.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4960HQ CPU @ 2.60GHz
  Binaries:
    Node: 16.0.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.10.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 90.0.4430.93
    Firefox: 87.0
    Safari: 14.1
  npmPackages:
    @storybook/addon-actions: ^6.2.9 => 6.2.9
    @storybook/addon-essentials: ^6.2.9 => 6.2.9
    @storybook/addon-links: ^6.2.9 => 6.2.9
    @storybook/react: ^6.2.9 => 6.2.9
```

Perhaps this isn't supposed to work but can you advise on how to add a Description component which uses JSDocs to the custom DocsContainer in that case please?

Thanks!

**Comment by shilman** [comment]
Did you try this?

```diff
        parameters: {
          ...context.parameters,
          docs: {
+           ...context.parameters?.docs,
            theme: dark ? sbDarkTheme : sbLightTheme,
          },
        },
```

**Comment by DominicTobias** [comment]
> ```diff
> ...context.parameters?.docs,
> ```

Life saver, copied the code from an Issue and didn't look at it properly thanks it works! 👍
