### ISSUE TITLE
vue3: Using components in decorators, does not render the components

### ISSUE THREAD

**Issue by thomasaull** [storybookjs/storybook#14788]
**Describe the bug**
Using a decorator like this:
```js
import MyButton from './Button.vue'

export default {
  title: "Example/Button",
  component: MyButton,

  decorators: [
    () => ({
      components: {
        MyButton,
      },

      template: `
        <MyButton label="Button from default decorator"/>
        <story/>
      `,
    }),
  ],
};
```

does not render the actual `MyButton` component, but this:
```html
<mybutton label="Button from default decorator"></mybutton>
```

**To Reproduce**
https://github.com/thomasaull/storybook-vue3-decorator-bug
Reproduction repository is a default vue-cli and storybook install, I added the example code in this commit: https://github.com/thomasaull/storybook-vue3-decorator-bug/commit/d3a8899d5d4930df052209120876e99a0f6bd1b7

To reproduce, run `npm run storybook` and navigate to the Button component

**System**
```
Environment Info:

  System:
    OS: Linux 5.4 elementary OS 5.1.7 Hera
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
    npm: 6.14.11 - ~/.nvm/versions/node/v14.16.0/bin/npm
  Browsers:
    Chrome: 89.0.4389.114
    Firefox: 85.0.1
  npmPackages:
    @storybook/addon-actions: ^6.2.9 => 6.2.9 
    @storybook/addon-essentials: ^6.2.9 => 6.2.9 
    @storybook/addon-links: ^6.2.9 => 6.2.9 
    @storybook/vue3: ^6.2.9 => 6.2.9 
```

**Additional context**
When comparing those two files:
- Vue2: https://github.com/storybookjs/storybook/blob/next/app/vue/src/client/preview/index.ts#L38
- Vue3: https://github.com/storybookjs/storybook/blob/next/app/vue3/src/client/preview/index.ts#L36

It looks like, in the vue3 Integration the reference to the `story.components` is missing

**Comment by shilman** [comment]
@thomasaull any chance you can contribute a PR with the fix from above and a simple repro in `examples/vue-3-cli`

**Comment by thomasaull** [comment]
@shilman Yes, I just did that: https://github.com/storybookjs/storybook/pull/14809

**Comment by shilman** [comment]
Zoinks!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.3.0-alpha.20 containing PR #14809 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
