### ISSUE TITLE
react stories doesnt shows font awesome icon

### ISSUE THREAD

**Issue by ooo2003003v2** [storybookjs/storybook#14791]
Hello there. 
I created a component with fontawesome icon. It works fine but it doesnt shows in my stories.
I imported @fortawesome files and added fas to the library in the preview.js. Then my story shows "Cannot read property 'icon' of undefined".
Anyone know why?

preview.js
```
import { library } from "@fortawesome/fontawesome-svg-core";
import { fas } from "@fortawesome/free-solid-svg-icons";
library.add(fas);
export const parameters = {
  actions: { argTypesRegex: "^on[A-Z].*" },
  controls: {
    matchers: {
      color: /(background|color)$/i,
      date: /Date$/,
    },
  },
};

```

**Comment by gabrielurenah** [comment]
We're on the same boat 😞  Trying to get font awesome icons to work on storybook with react. No bueno 😕

**Comment by ooo2003003v2** [comment]
> We're on the same boat  Trying to get font awesome icons to work on storybook with react. No bueno

Actually I figure it out that what you need is import the files inside preview.js/.ts

**Comment by ndquang191** [comment]
Can you show me what should I import? I got the same problem

**Comment by billyliuschill** [comment]
> Can you show me what should I import? I got the same problem

I have an imported icon library and the css is found in the node_modules folder. So I just referenced it in the preview.js.

Notice how I had to include the style loader and css loader. These are found in your `____.config.js` file at your root. You will need sass loader if you are working with .scss files.

So all I had to do was `import '!style-loader!css-loader!../node_modules/<your package name/dir where your css resides>.css'` in your preview.js file and the icons showed up just fine.

**Comment by MarNi-Works** [comment]
> > Can you show me what should I import? I got the same problem
> 
> I have an imported icon library and the css is found in the node_modules folder. So I just referenced it in the preview.js.
> 
> Notice how I had to include the style loader and css loader. These are found in your `____.config.js` file at your root. You will need sass loader if you are working with .scss files.
> 
> So all I had to do was `import '!style-loader!css-loader!../node_modules/<your package name/dir where your css resides>.css'` in your preview.js file and the icons showed up just fine.

Can you show your solutions?

**Comment by billyliuschill** [comment]
> 

Under .storybook/preview.js

`import '!style-loader!css-loader!sass-loader!../src/styles/style.scss';
import '!style-loader!css-loader!../node_modules/@fortawesome/fontawesome-free/css/all.css';

export const parameters = {
  actions: { argTypesRegex: "^on[A-Z].*" },
  controls: {
    matchers: {
      color: /(background|color)$/i,
      date: /Date$/,
    },
  },
}`

**Comment by DarPerry** [comment]
For me, just adding "import `@fortawesome/fontawesome-pro/css/all.css` to my `.storybook/preview.js` file worked.

I'm sure replacing `pro` with `free` or whatever path your FA file lives works too.

**Comment by NiyongaboEric** [comment]
import path to fontawesome library to `preview.js` if you are using story book or to  main`index.tsx`, `index.jsx` if you are using ReactSJ

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
