### ISSUE TITLE
React useState hook stopped working in Storybook Template

### ISSUE THREAD

**Issue by sforehand** [storybookjs/storybook#14795]
**Describe the bug**
We have a private Storybook implementation.  Some of our stories use state in the story template along with a button to perform actions like open a dialog, open a drawer, etc.  Typical code might appear as follows:

<img width="1199" alt="Screen Shot 2021-05-04 at 9 13 37 AM" src="https://user-images.githubusercontent.com/25122876/117008766-0fdcfc00-acb9-11eb-8e2f-c822bfab7219.png">

Until recently, when the button was clicked, the handleOpen() function would set the dialogOpen stateful variable to true allowing the dialog to open.  For reasons unknown to me, when I now click the button, the handleOpen() is called but state is not set properly.

Additionally, in the code above, you will notice the handleClose property on the ModalDialog component.  It is a required property.  However, even though handleClose() function is defined in the Template, the Modal Dialog component is reporting null being passed to the handleDialog property.  This is also a new bug.

**To Reproduce**

Unfortunately I do not have a public repo I can provide to reproduce the issue.  Here is a screenshot of our Storybook implementation.  The button is supposed to (and did until recently) open the dialog when clicked.

<img width="1652" alt="Screen Shot 2021-05-04 at 9 16 22 AM" src="https://user-images.githubusercontent.com/25122876/117009354-a6112200-acb9-11eb-9963-51a4557b48bb.png">

**System**

Environment Info:

  System:
    OS: macOS 11.3
    CPU: (16) x64 Intel(R) Xeon(R) W-2140B CPU @ 3.20GHz
  Binaries:
    Node: 15.14.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.7.6 - /usr/local/bin/npm
  Browsers:
    Chrome: 90.0.4430.93
    Firefox: 76.0.1
    Safari: 14.1
  npmPackages:
    @storybook/addon-a11y: ^6.2.9 => 6.2.9 
    @storybook/addon-actions: ^6.2.9 => 6.2.9 
    @storybook/addon-essentials: ^6.2.9 => 6.2.9 
    @storybook/addon-links: ^6.2.9 => 6.2.9 
    @storybook/node-logger: ^6.2.9 => 6.2.9 
    @storybook/preset-create-react-app: ^3.1.7 => 3.1.7 
    @storybook/react: ^6.2.9 => 6.2.9 

**Additional context**

I also ran a small test where I placed a console log in the story within the handleOpen() function to report the value of the 'dialogOpen' variable.  I also placed a console in the component.  Here is the output

<img width="1382" alt="Screen Shot 2021-05-04 at 9 25 43 AM" src="https://user-images.githubusercontent.com/25122876/117010680-081e5700-acbb-11eb-9a9a-b1b37fd2dfe9.png">

You can see the initial click reported values of 'false' from the story and component.  However, the 8 clicks of the button in the story after the initial click did not pass to the component it seems as the component did not report any clicks.

**Comment by shilman** [comment]
> Until recently,

Did you upgrade Storybook? If so, what was the last version that worked as expected?

**Comment by sforehand** [comment]
Hi.  Thanks for your response. Yes, we upgraded from 6.1.20 to 6.2.9

**Comment by sforehand** [comment]
6.1.20 seemed to work properly

**Comment by mayank99** [comment]
We had a very similar issue when we upgraded from 6.1 to 6.2, so we had to revert.

One interesting observation we found is that if you "save" your code in IDE (to trigger a hot reload), the state starts working again.

**Comment by nessor** [comment]
Using v6.5.13 I don't have this problem anymore. Is it also solved for you?
