### ISSUE TITLE
Toolbar is gone in docs mode

### ISSUE THREAD

**Issue by fallemand** [storybookjs/storybook#14797]
![image](https://user-images.githubusercontent.com/16105726/117013933-98c35a00-acf0-11eb-813f-132419ffbbd6.png)

**What's the problem?**
1- We build the storybook with `build-storybook --docs`
2- After that the Toolbar at the top is gone. 
We need it to switch themes. Is it possible to keep it in docs mode?
Do you know any other work around to be able to switch themes using `--docs`?

Version: `6.2.7`

```
    "@storybook/addon-a11y": "^6.2.7",
    "@storybook/addon-essentials": "^6.2.7",
    "@storybook/vue": "6.2.7",
    "storybook-addon-themes": "^6.1.0",
```

**Comment by digitaltopo** [comment]
I have the same issue/use case. Looking to display a theme switcher tool in built storybook docs.

**Comment by fallemand** [comment]
I found that you can put in `preview.js`

```javascript
export const parameters = {
  options: {
    isToolshown: true,
  },
};
```

And that's keeping the toolbar in docs mode 👍 . 
Tested in 6.2.7 & 6.2.9

**Comment by ZambranoBeicker** [comment]
I have the same issue in development mode (localhost). It seems to scroll down a bit when i click "Docs" button in the toolbar. I tried @fallemand solution but it didn't work for me, maybe i did something wrong but this is my code:

```
export const parameters = {
  actions: { argTypesRegex: "^on[A-Z].*" },
  controls: {
    matchers: {
      color: /(background|color)$/i,
      date: /Date$/,
    },
  },
  options: {
    isToolsShown: true,
  },
};

```

I hope this problem can be fixed soon, this is a annoying bug

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
