### ISSUE TITLE
Angular storybooks crash on double quote input

### ISSUE THREAD

**Issue by prewk** [storybookjs/storybook#14792]
**Describe the bug**
Storybook for Angular renders string inputs into the template in an unescaped way so that adding a double quote crashes the template.   

![Kapture 2021-05-04 at 13 53 57](https://user-images.githubusercontent.com/640102/116999979-b1c40f00-ace0-11eb-92ae-893704806543.gif)

**To Reproduce**
Found the issue own our own Storybook but it's in the official tutorial (see GIF above) so I assume it's everywhere.

Just enter double quotes `"` into an input typed as a `string`.

**System**
```
  System:
    OS: macOS 11.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 14.15.3 - /usr/local/bin/node
    Yarn: 1.21.1 - ~/.yarn/bin/yarn
    npm: 6.14.9 - /usr/local/bin/npm
  Browsers:
    Chrome: 90.0.4430.93
    Safari: 14.1
  npmPackages:
    @storybook/addon-actions: ^6.2.8 => 6.2.9
    @storybook/addon-essentials: ^6.2.8 => 6.2.9
    @storybook/addon-links: ^6.2.8 => 6.2.9
    @storybook/angular: ^6.2.8 => 6.2.9
```

**Comment by valentinpalkovic** [comment]
I am closing this as it seems to be fixed since 6.4
