### ISSUE TITLE
addons-docs: Storybook breaks once addon-docs is added to configuration

### ISSUE THREAD

**Issue by mgolawski** [storybookjs/storybook#14827]
**What's the problem?**
I try to add `addon-docs` to my Storybook. 
Currently we use mostly storiesOf api, but we are migrating to CSF in our components library and we would like to use `addon-docs` to enforce the documentation.

Once I add the addon to my `main.js`
```
  addons: [
    '@storybook/addon-docs',
    '@storybook/addon-knobs',
    '@storybook/addon-actions',
    '@storybook/addon-links',
    '@storybook/addon-a11y',
    '@storybook/addon-backgrounds',
    '@invisionapp/dsm-storybook',
  ],
```

And i disable globally the docs for now
```
export const parameters = {
  ...
  docs: { page: null },
};
```

Storybook build correctly but I get a runtime error inside the `addon-docs` source files
```
mdx.js:67 Uncaught TypeError: Cannot read property 'a' of undefined
    at Module../node_modules/@storybook/addon-docs/dist/esm/blocks/mdx.js (mdx.js:67)
    at __webpack_require__ (bootstrap:848)
    at fn (bootstrap:150)
    at Module../node_modules/@storybook/addon-docs/dist/esm/blocks/Subheading.js (Subheading.js:1)
    at __webpack_require__ (bootstrap:848)
    at fn (bootstrap:150)
    at Module../node_modules/@storybook/addon-docs/dist/esm/blocks/DocsStory.js (DocsStory.js:1)
    at __webpack_require__ (bootstrap:848)
    at fn (bootstrap:150)
    at Module../node_modules/@storybook/addon-docs/dist/esm/blocks/Primary.js (Primary.js:1)
```

Basically the below imports `undefined`
```
import { Source, Code, components } from '@storybook/components';
```

Am I missing something? I tried to play with different loaders in webpack but I am basically stuck with it.
Thanks in advance.

**Is there documentation on this?**
If this is documented at https://storybook.js.org/docs/ but the documentation is incomplete or unclear, link to it here.
I followed below docs
https://storybook.js.org/docs/react/writing-docs/docs-page
https://github.com/storybookjs/storybook/blob/master/addons/docs/docs/recipes.md#csf-stories-with-mdx-docs

**Additional context**
For some deeper context my webpack configuration

```
    rules: [
      {
        test: /\.(js|jsx)$/,
        exclude: [/node_modules/, /coverage/],
        use: 'babel-loader',
      },
      {
        test: /\.s?css$/,
        exclude: [/coverage/],
        sideEffects: true,
        use: [
          { loader: 'style-loader' },
          {
            loader: 'css-loader',
            options: { importLoaders: 2 },
          },
          {
            loader: 'postcss-loader',
            options: {
              plugins: () => [require('autoprefixer'), require('postcss-discard-duplicates')],
            },
          },
          {
            loader: 'fast-sass-loader',
            options: {
              includePaths: [path.resolve(__dirname, '..', 'node_modules')],
            },
          },
        ],
      },
      {
        test: /\.(png|jpe?g|gif)$/,
        use: [
          {
            loader: 'file-loader',
            options: {},
          },
        ],
      },
      {
        test: /\.(eot|woff|woff2|ttf)([\?]?.*)$/,
        use: ['file-loader'],
      },
      {
        test: /\.svg$/,
        use: ['@svgr/webpack', 'url-loader'],
      },
      {
        test: /\.md$/,
        use: [
          {
            loader: 'html-loader',
          },
          {
            loader: 'markdown-loader',
          },
        ],
      },
    ],
  ```

**Comment by shilman** [comment]
Do you have a repro repo you can share? What happens when you disable addon-docs?

**Comment by mgolawski** [comment]
```
    "@storybook/addon-a11y": "^6.1.9",
    "@storybook/addon-actions": "^6.1.9",
    "@storybook/addon-backgrounds": "^6.1.9",
    "@storybook/addon-docs": "^6.2.9",
    "@storybook/addon-info": "^5.3.21",
    "@storybook/addon-knobs": "^6.1.9",
    "@storybook/addon-links": "^6.1.9",
    "@storybook/addons": "^6.1.9",
    "@storybook/react": "^6.1.9",
  ```
  
  Removing different addons does not really help. I even tried to run it with `@storybook/addon-docs` only.
  
  Our repository is private, but I will try extract the configuration and share it on public to help debugging.
  
  Thanks for answer.

**Comment by shilman** [comment]
Try removing `@storybook/addon-info` also. And when I say removing it, I mean not just from `main.js` but also from `package.json`/`node_modules`. I'm worried about the wrong version of libraries getting hoisted due to version conflicts

**Comment by mgolawski** [comment]
I removed both `@storybook/addon-info` and `@invisionapp/dsm-storybook` from the project at all. Unfortunately it does not help.

**Comment by sho-otani-icare** [comment]
Removing `^` from package.json works for me.
In my case, `@storybook/components` was installed in different version.
I just fixed the version and the error has gone.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
