### ISSUE TITLE
Build-storybook breaking html when passing function with quotes

### ISSUE THREAD

**Issue by RGunning** [storybookjs/storybook#14825]
**Describe the bug**
When passing a function as an input to an angular input that contains a quotation mark, building a standalone version of storybook breaks. However, using start-storybook everything works fine.

**start-storybook**:
![Screenshot 2021-05-06 at 11 12 33](https://user-images.githubusercontent.com/4697912/117265390-db09aa00-ae5c-11eb-8da1-4d7f654f9d3c.png)

**build-storybook**:
![Screenshot 2021-05-06 at 11 11 45](https://user-images.githubusercontent.com/4697912/117265384-d9d87d00-ae5c-11eb-9a31-786863fd7928.png)

**To Reproduce**
MWE:
https://github.com/RGunning/storybook-bug-mwe/blob/master/stories/function-passing-bug.component.ts
https://github.com/RGunning/storybook-bug-mwe/blob/master/stories/function-passing-bug.component.stories.ts

```ts
@Component({
  selector: 'app-function-passing',
  template: `<div>{{text}}</div>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class FunctionPassingComponent {
  value = 1000;

  @Input() displayWith: (value: number) => string = (_value) => '';

  get text() {
    return this.displayWith(this.value);
  }
}
```

```ts
const Template: Story<FunctionPassingComponent> = (args: FunctionPassingComponent) => ({
  moduleMetadata: {
    declarations: [FunctionPassingComponent],
  },
  template: ` <app-function-passing [displayWith]="displayWith"></app-function-passing>`,
  props: args,
});

export const DisplayWith: Story<FunctionPassingComponent> = Template.bind({});
DisplayWith.args = {
  displayWith: (value) => `${value} %`,
};
```

**System**

> Environment Info:
> 
>   System:
>     OS: macOS 10.15.7
>     CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
>   Binaries:
>     Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
>     Yarn: 1.22.10 - ~/.nvm/versions/node/v14.16.0/bin/yarn
>     npm: 6.14.11 - ~/.nvm/versions/node/v14.16.0/bin/npm
>   Browsers:
>     Chrome: 90.0.4430.93
>     Firefox: 88.0
>     Safari: 14.0.3
>   npmPackages:
>     @storybook/addon-actions: ^6.2.5 => 6.2.9 
>     @storybook/addon-essentials: ^6.2.5 => 6.2.9 
>     @storybook/addon-links: ^6.2.5 => 6.2.9 
>     @storybook/angular: ^6.2.5 => 6.2.9

**Comment by shilman** [comment]
Typically args need to be JSON-serializable (ish). The fact that it works in dev mode is probably a happy accident. I would suggest using a mapping to solve the problem: https://storybook.js.org/docs/react/writing-stories/args#mapping-to-complex-arg-values

**Comment by RGunning** [comment]
Sort of getting it to work with mappings, but only with storybook 6.3.0--alpha
Issue is still throwing the same error with 6.2.9 even with mapping

```ts
 displayWith: {
            options: ['No Formatting', 'Thousands', 'Percentage'],
            mapping: {
                'No Formatting': null,
                Thousands: (value: number) => (value >= 1000 ? `${Math.round(value / 1000)}k` : value),
                Percentage: (value: number) => `${value} %`,
            },
        },
```

**Comment by RGunning** [comment]
Can probably close this issue once 6.3.0 is released

**Comment by shilman** [comment]
Ok, if it's working in 6.3 I'm going to close it now. I don't know why it's not working in 6.2 -- maybe @ghengeveld has some ideas?
