### ISSUE TITLE
CSS Custom Properties Not Working

### ISSUE THREAD

**Issue by TamaraPK** [storybookjs/storybook#14847]
Hello!

I am using Storybook with React and TailwindCSS. TailwindCSS is working fine, however when I use CSS Custom Properties, it does not seem to work. I am following the method shown here for Tailwind CSS.
https://github.com/adamwathan/theming-tailwind-demo

I have set up the Storybook with Create React App. When I run the React app (yarn start) - which uses the same css file as Storybook (the compiled output from TailwindCSS) - the CSS Custom Properties work fine. When I use the same thing in Storybook, nothing happens (the style is not applied although I can see it in "inspect elements (Chrome dev tools)"). If I use a regular TailwindCSS class (e..g for text color, it works fine but not a class based on CSS Custom Properties).

I hope you can help me out :) Thanks!

P.S. I tried adding the addon below:
https://storybook.js.org/addons/storybook-addon-custom-properties
1. This will force me to redeclare all variables inside Storybook (duplicate).
2. Not sure how to configure this for multiple themes e.g. default, dark.
3. Note sure where to add the code block below (+ 1. It gave me an error. something about addParameters not being a function 2. Will I need to do the same in every story?):
import { withCustomProperties } from 'storybook-addon-custom-properties';

```
addParameters({
  'custom-properties': {
    label: 'Theme',
    list: [
      { '--somekeyword': 'left' },
      { '--somecolor': '#0000ff' },
      { '--somecomplexvalue': '3px 6px rgb(20, 32, 54)' }, 
    ]
  }
});

addDecorator(withCustomProperties);

```

**Comment by TamaraPK** [comment]
Sorry! Turned out to be my mistake! Forgot to put the theme class in a parent container!

**Comment by ibrahimbmohammed** [comment]
@TamaraPK  , please I'm having similar issue, can you show me how you configured yours to work ?, The documentation was not elaborate enough , thanks
