### ISSUE TITLE
addon-backgrounds: background color not being set 

### ISSUE THREAD

**Issue by julesvirallinen** [storybookjs/storybook#14846]
After upgrading storybook, the default background isn't shown automatically. Instead the background is transparent until I turn the grid on (and off). After this the background works normally. See video below. 

I upgraded storybook as below 

```
info  @storybook/addon-actions     6.1.18  →  6.2.9     
info  @storybook/addon-essentials  6.1.18  →  6.2.9     
info  @storybook/addon-links       6.1.18  →  6.2.9     
info  @storybook/react             6.1.18  →  6.2.9     
info  @types/storybook__react       4.0.1  →  5.2.1     
```

My parameters setting: 

```
export const parameters = {
  layout: 'centered',
  backgrounds: {
    default: 'game',
    values: [
      {
        name: 'game',
        value: `#141327`,
      },
    ],
  },
};
```

![Kapture 2021-05-07 at 15 03 22](https://user-images.githubusercontent.com/4622905/117446870-6a8a8800-af45-11eb-8476-f72b12cc00f8.gif)

**Comment by shilman** [comment]
Do you have a repro repo you can share?

**Comment by alexanderniebuhr** [comment]
same issue .. but in docs tab

**Comment by julesvirallinen** [comment]
@alexanderniebuhr able to repro this? Mine is in a huge private repo.

**Comment by alexanderniebuhr** [comment]
https://github.com/frickegroup/ui

**Comment by alexanderniebuhr** [comment]
non repo with an default setup..

**Comment by nickofthyme** [comment]
Same issue, the `context.globals.backgrounds.value` is never set via the `backgrounds.default` value  either. Likely the same issue. I'll look into creating a repro and possibly and PR soon.

**Comment by nickofthyme** [comment]
I couldn’t reproduce this issue locally with `6.3.4` so I opened a new issue for the other issue I mentioned. See #15632

**Comment by nickofthyme** [comment]
Just a thought.... I ran into this case when applying only the `register` part of the addon. @julesvirallinen are you registering the addon like below?

```diff
module.exports = {
  addons: [
+    '@storybook/addon-backgrounds',
-    '@storybook/addon-backgrounds/register',
  ],
};
```
