### ISSUE TITLE
Vue: Show code block doesn't render template

### ISSUE THREAD

**Issue by standbyoneself** [storybookjs/storybook#14853]
I am using Storybook for Vue v6.2.9

I have one component named BaseIcon. It has two props: icon and iconColor.

Why clicking the Show code button doesn't show the actual template, only raw code from Template?

<img width="1440" alt="Screenshot 2021-05-08 at 04 09 51" src="https://user-images.githubusercontent.com/57719759/117520926-a78d6380-afb3-11eb-94cd-6a86e2d9bacc.png">

I wanna it should be like:

`<BaseIcon icon="camera" iconColor="white" />`

My BaseIcon/index.stories.js code:
```
import BaseIcon from './index.vue';
import validIcons from './validIconsList';

export default {
  title: 'Components/BaseIcon',
  component: BaseIcon,
  argTypes: {
    icon: {
      options: validIcons,
      control: {
        type: 'select'
      }
    }
  },
 /*  parameters: {
    docs: {
      source: {
        type: 'code'
      }
    }
  } */ 
};

const Template = (args, { argTypes }) => ({
  components: { BaseIcon },
  props: Object.keys(argTypes),
  template: `<BaseIcon v-bind="$props" />`
});

export const Default = Template.bind({});
Default.args = {
  icon: 'camera'
};

```

Toggling commented `parameters` property in export default {} does nothing.

What did I miss?

**Comment by shilman** [comment]
Do you have a repro repo you can share?

**Comment by standbyoneself** [comment]
I just created it. Link: https://github.com/standbyoneself/storybook. It is a monorepo. I also created new Lerna package named `storybook`. It is super default vue project created by vue-cli that has storybook. You need to type `yarn storybook` and you'll see that default component`s code also doesn't look as I want

**Comment by prinzt** [comment]
We experience this behavior for all of our stories too, after upgrading from 6.1.x to 6.3.7.
We use Vue 2.6.11.

**Comment by standbyoneself** [comment]
@prinzt It works with single repo vue.js project, but not with lerna.js monorepository

**Comment by rextao** [comment]
hello, has this problem been solved?

**Comment by prinzt** [comment]
@standbyoneself We use a single repo and the problem still blocks us from upgrading storybook to 6.3.x

**Comment by standbyoneself** [comment]
@prinzt, Is it ok on down to 6.2 versions? Which framework do you use?

**Comment by FullStackSimon** [comment]
@standbyoneself Did you ever get a resolution on this? Facing the exact same problem.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
