### ISSUE TITLE
Using background addon to set image background

### ISSUE THREAD

**Issue by AlienHeadWars** [storybookjs/storybook#14869]
**What's the problem?**
I want to be able to set an image as a default background used in the background selector.

**Is there documentation on this?**
I can see an example in the official storybook, so I'm sure it's possible
https://next--storybookjs.netlify.app/official-storybook/?path=/story/addons-backgrounds--with-image
Is there a way to see the source for examples in the official storybook that I've missed?

**Additional context**
I'm using react, so any examples using react would be preferable.

Web development is not my strong point by any means, so apologies if I'm missing something really obvious.

**Comment by pocka** [comment]
[Here](https://github.com/storybookjs/storybook/blob/abc74c3f93d48734a7b759e2bec10d234fa81b7e/examples/official-storybook/stories/addon-backgrounds.stories.js#L64-L78). This is done via Parameters, so it's framework agnostic.

The source code for the Official Storybook example sits in [here](https://github.com/storybookjs/storybook/tree/abc74c3f93d48734a7b759e2bec10d234fa81b7e/examples/official-storybook) 📑

**Comment by j0k3r** [comment]
How is it possible to do this using Storybook 9?
