### ISSUE TITLE
CSF linter / sanitizing loader

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#14864]
[CSF](https://storybook.js.org/docs/react/api/csf) is based on ES modules, but Storybook's source tooling, such as loaders and codemods assume certain things about those modules. We should write a linter or sanitizing loader to check for those things.

For example, most tools assume that there is a default export with a title:

```js
export default {
  title: 'Foo/bar/baz'
  ...
}
```

The following code is equivalent at runtime:

```js
const config = {
  title: 'Foo/bar/baz'
  ...
};

export default config;
```

However, because the source (AST) is different, many tools will ignore these files as poorly-formed CSF. We should write a checker to warn users when they don't have well-formed CSF.

- [ ] ESlint module that checks in your code editor
- [ ] Babel/webpack loader that executes at load time

**Comment by benbender** [comment]
@shilman that might also clash with other quite popular eslint-rules (f.e. https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-anonymous-default-export.md) as there may be projects which internally forbid unnamed exports. Would be also nice if this could be a note in the docs. To me it wasn't clear that there might be a difference between both (named / anonymous) default-exports...

**Comment by shilman** [comment]
@benbender yeah. this is in flux --  I've created a shared library for CSF static analysis which fixes the example I gave above. We'll update more tooling to use that, and we should also document its limitations. i suspect any documentation will happen in concert with the linter.

**Comment by Sidnioulz** [comment]
As I understand now, only `component` and `title` must be provided statically for SB7+ to run, is that correct?

I have struggled to find explicit documentation for that limitation, though https://storybook.js.org/docs/7.0/react/writing-stories/naming-components-and-hierarchy could be a good spot. Is it somewhere where I've missed it?

Given that you need statically available titles (or autoTitle?), will we have any leeway in 7.0 to categorise and hierarchise stories without relying on the title? In our current codebase, we generate a title out of a component name (pulled from the component itself when possible) and category (pulled from a TS enum), to ensure consistent formatting. We don't yet understand if we'll be given a way to achieve a similar outcome.

**Comment by shilman** [comment]
@Sidnioulz I believe the default export must have either `component` OR `title`. Any chance you can make a PR to fix the docs?

**Comment by shilman** [comment]
Closing this as finished. Thanks @yannbf 

https://storybook.js.org/blog/how-to-use-storybook-with-eslint/
