### ISSUE TITLE
Webpack5 + type: module = require is not defined

### ISSUE THREAD

**Issue by arty-name** [storybookjs/storybook#14877]
**Describe the bug**
A barebones example with type: module and Webpack5 results in "require is not defined" error in browser:

```
Uncaught ReferenceError: require is not defined
    js generated-stories-entry.js:3
    Webpack 7
        __webpack_require__
        __webpack_exec__
        <anonymous>
        O
        <anonymous>
        webpackJsonpCallback
        <anonymous>
```

**To Reproduce**

`git clone git@github.com:arty-name/storybook-webpack5-module.git && yarn install && npx start-storybook`

Alternatively these simple steps:

1. Create `package.json` containing `{ "type": "module" }`
1. `yarn add react react-dom`
1. `yarn add --dev @storybook/react @storybook/builder-webpack5 @storybook/manager-webpack5`
1. Create `.storybook/main.cjs` containing `module.exports = { core: { builder: 'webpack5' }, stories: ['../test.stories.js'] }`
1. Create `test.stories.js` containing:

```js
export default { title: 'Story' }
export function Story() {
  return 'Pass!'
}
```

1. `npx start-storybook`

**System**

```
Environment Info:

  System:
    OS: Linux 5.8 Ubuntu 21.04 (Hirsute Hippo)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
  Binaries:
    Node: 16.3.0 - /usr/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 7.15.1 - /usr/bin/npm
  Browsers:
    Chrome: 91.0.4472.114
    Firefox: 89.0.1
  npmPackages:
    @storybook/builder-webpack5: ^6.3.0 => 6.3.0 
    @storybook/manager-webpack5: ^6.3.0 => 6.3.0 
    @storybook/react: ^6.3.0 => 6.3.0 
```

**Comment by arty-name** [comment]
Sure, I can create it: https://github.com/arty-name/storybook-webpack5-module

**Comment by arty-name** [comment]
Confirmed the issue with storybook@6.3.0

**Comment by arty-name** [comment]
Confirmed the issue with storybook@6.3.1

**Comment by dimfeld** [comment]
I looked into this a bit, and it's a bit weird since the [file as checked in to Git](https://github.com/storybookjs/storybook/blob/next/lib/builder-webpack5/src/preview/virtualModuleStory.template.js) actually does use the `import` syntax. But it gets transpiled to CommonJS format in the `cjs` build of storybook, which I suppose is being used because we currently have to use `.storybook/main.cjs` instead of just `.storybook/main.js`. 

Not quite sure what the proper solution is for this. One possibility is to maintain two copies of `virtualModuleStory.template.js`, one for CJS and one for ESM, and then keeping them from being processed during the build, would work. Then the template code could use `packageJson.type` to determine which template to use. There might be a better solution though that lets webpack convert the template or something.

**Comment by arty-name** [comment]
The `.storybook/package.json` workaround works indeed, thanks!

**Comment by jpzwarte** [comment]
I can confirm that the workaround does not work for me.

**Comment by jpzwarte** [comment]
I've updated the example repo from above and updated the packages to `6.4.0-beta.33` and added the empty `package.json`, but I *still* get the `require is undefined` error. cc @shilman

**Comment by tmeasday** [comment]
@jpzwarte I think the reason that the `.storybook/package.json` solution doesn't work any more in 6.4 is because we "moved" the location of the virtual module created by the file referenced in @dimfeld's [comment](https://github.com/storybookjs/storybook/issues/14877#issuecomment-881981075) to the root of the project, rather than the `.storybook` directory.

Let me see if I understand this issue correctly:

1. If you specify your project as `{ "type": "module" }`, webpack doesn't want to see `require()` any more
2. The entry point(s) we create on your behalf as SB (generated from `virtualModuleStory.template.js`, which was compiled to CJS) makes use of `require()`
3. In 6.3, as that file was "put" in `./.storybook`, if you put a `package.json` in there declaring a non "module" package, WP is happy again.

I wonder if there is an alternate way to tell WP that the bundle we are create is (to begin with at least) CJS, not ESM, so it doesn't look in `./package.json:type` to figure that out?

We would like to properly sort out this ESM/CJS business in 6.5 so it is possible to actually just use ESM everywhere.

**Comment by tmeasday** [comment]
Can we just make the filename of the virtual module `.cjs` @jpzwarte? 

https://webpack.js.org/api/module-methods/#es6-recommended

You would just change the keys in `virtualModuleMapping` and `entries` here: https://github.com/storybooks/storybook/blob/eb1fcd077dd71d549ba2ed33748aa9e5c122b946/lib/builder-webpack5/src/preview/iframe-webpack.config.ts#L122-L142

**Comment by jpzwarte** [comment]
@tmeasday I've tested it by changing `node_modules/@storybook/builder-webpack5/dist/cjs/preview/iframe-webpack.config.js` in place and the *only* thing that is required is to rename `generated-stories-entry.js` to `generated-stories-entry.cjs`.

I can confirm that with that change, the `require is undefined` error is gone!

**Comment by arty-name** [comment]
Would it make sense to remove the "has workaround" label meanwhile?

**Comment by fernandopasik** [comment]
What's the workaround for storybook 6.4?

**Comment by paulbrimicombe** [comment]
I have a particularly horrible workaround based on https://github.com/storybookjs/storybook/issues/14877#issuecomment-973831859 . In the `main.*(c)js` file you can change the `VirtualModulesPlugin` instance to add the `.cjs` suffix to the appropriate files. This is only likely to work for a specific version of Storybook so I'd suggest that you pin to a specific version if you're going to use it.

```js
const path = require("path");

const replaceFileExtension = (filePath, newExtension) => {
  const { name, root, dir } = path.parse(filePath);
  return path.format({
    name,
    root,
    dir,
    ext: newExtension,
  });
};

module.exports = {
  // Your other configuration.
  core: {
    builder: "webpack5",
  },
  webpackFinal: (config) => {
    // Find the plugin instance that needs to be mutated
    const virtualModulesPlugin = config.plugins.find(
      (plugin) => plugin.constructor.name === "VirtualModulesPlugin"
    );

    // Change the file extension to .cjs for all files that end with "generated-stories-entry.js"
    virtualModulesPlugin._staticModules = Object.fromEntries(
      Object.entries(virtualModulesPlugin._staticModules).map(
        ([key, value]) => {
          if (key.endsWith("generated-stories-entry.js")) {
            return [replaceFileExtension(key, ".cjs"), value];
          }
          return [key, value];
        }
      )
    );

    // Change the entry points to point to the appropriate .cjs files
    config.entry = config.entry.map((entry) => {
      if (entry.endsWith("generated-stories-entry.js")) {
        return replaceFileExtension(entry, ".cjs");
      }
      return entry;
    });
    return config;
  },
};
```

I've tested this with Storybook 6.4.9. It _may_ work for other versions.

**Comment by badsyntax** [comment]
@paulbrimicombe doesn't seem to work for 6.5. what's the status of this in 6.5? i expected ESM to just work in 6.5

**Comment by shilman** [comment]
@badsyntax 6.4 and 6.5 should be pretty much identical at this point since we're still very early in the release cycle. i haven't had time to confirm any of the workarounds yet.

**Comment by philippone** [comment]
Hi @badsyntax and @shilman ,

I can confirm that it's working with version`6.5.0-alpha.5`

**Comment by badsyntax** [comment]
> Hi @badsyntax and @shilman ,
> 
> I can confirm that it's working with version`6.5.0-alpha.5`

can you be specific about what you needed to do to get this to work? any workarounds, or does it "just work"? and if so, can you share en example repo? i'm still getting `require is not defined` with 6.5

**Comment by philippone** [comment]
> > Hi @badsyntax and @shilman ,
> > I can confirm that it's working with version`6.5.0-alpha.5`
> 
> @philippone
> 
> can you be specific about what you needed to do to get this to work? any workarounds, or does it "just work"? and if so, can you share an example repo? i'm still getting `require is not defined` with 6.5

Hi @badsyntax ,

I guess it's the combination of 
- [main.cjs + empty package.json {}](https://github.com/storybookjs/storybook/issues/14877#issuecomment-881981075)
- [Webpack Config Adaptio](https://github.com/storybookjs/storybook/issues/14877#issuecomment-998620943)

I'll try to provide an example repo later.

**Comment by badsyntax** [comment]
Here's an example using 6.5 that shows the error: https://github.com/badsyntax/storybook-webpack5-module

**Comment by philippone** [comment]
> 

Can you try adding a `package.json` file into your `.storybook` folder with the following content:

```
{}
```

**Comment by badsyntax** [comment]
@philippone what we need is a repo that shows the workarounds. Please see previous comment. Please fork that repo and add the workarounds there.

(To everyone else, apologies for the noise.)

**Comment by badsyntax** [comment]
@philippone thanks for adding the workarounds. the workaround work in a simple setup. 

here's a simple reproducible example of the workarounds: https://github.com/philippone/storybook-webpack5-module

things start to fall apart when using typescript unfortunately. i can't seem to be able to use full specified paths. anyone know how i can storybook to work with full specified paths on TS source files? 

Outline of the problem described in this README: https://github.com/badsyntax/storybook-webpack5-module#current-problem

Error here: https://github.com/badsyntax/storybook-webpack5-module/blob/dcb54ced0df94843eba0959007c45e7b7f092af6/src/components/Pass/Pass.tsx#L1

**Comment by philippone** [comment]
> @philippone thanks for adding the workarounds. the workaround work in a simple setup.
> 
> for others, here's a simple reproducible example of the workarounds: https://github.com/philippone/storybook-webpack5-module
> 
> things start to fall apart when using typescript unfortunately. i can't seem to be able to use fully specified paths. anyone know how i can storybook to work with full specified paths on TS source files?
> 
> Outline of the problem described in this README: https://github.com/badsyntax/storybook-webpack5-module#current-problem
> 
> Error here: https://github.com/badsyntax/storybook-webpack5-module/blob/dcb54ced0df94843eba0959007c45e7b7f092af6/src/components/Pass/Pass.tsx#L1

Hi @badsyntax ,

you import a `js` file that does not exist. Remove the `.js` postfix when importing:

```
import { green } from "../../tokens/tokens";
```

**Comment by badsyntax** [comment]
@philippone that's intentional, and that's ESM support works in TypeScript. See: https://www.typescriptlang.org/docs/handbook/esm-node.html#type-in-packagejson-and-new-extensions

**Comment by benjambles** [comment]
@badsyntax - I've had success with adding `resolve-typescript-plugin` to the main.cjs file to get it to correctly load fully specified paths. https://github.com/benjambles/my-own-world/blob/master/packages/ui/.storybook/main.cjs#L33

**Comment by alexgrozav** [comment]
After a few hours of fiddling with it, I found an elegant solution. I've created a PR that replaces `require` with `import`.

Currently, the extensions are not ensured, so you'll probably still need to do some replacements. Here's mine:

```js
    webpackFinal: async (config, { configType }) => {
        const virtualModulesPlugin = config.plugins.find(
            (plugin) => plugin.constructor.name === "VirtualModulesPlugin"
        );

        const storybookConfigEntryKey = Object.keys(virtualModulesPlugin._staticModules)
            .find((key) => key.endsWith('storybook-config-entry.js'))

        virtualModulesPlugin._staticModules[storybookConfigEntryKey] = virtualModulesPlugin._staticModules[storybookConfigEntryKey]
            .replace('config\'', 'config.js\'');

        return config;
    }
```

**Comment by badsyntax** [comment]
@benjambles thanks for the suggestion, that plugin does indeed solve the issue. so as it stands i can get storybook/webpacl5/esm/ts to work with the workarounds mentioned in this issue. i do hope for the future we won't need to provide these workarounds. 

to summarise:

- `package.json` with `{}` contents
- [this workaround](https://github.com/philippone/storybook-webpack5-module/blob/61e62f14be5d4083d40d64de9d09a64830406e8b/.storybook/main.cjs#L1-L47) to fix the `require is not defined` error
- `resolve-typescript-plugin` webpack plugin to allow fully specified paths in typescript (required for ESM support)

**Comment by AMilassin** [comment]
> @benjambles thanks for the suggestion, that plugin does indeed solve the issue. so as it stands i can get storybook/webpack5/esm/ts to work with the workarounds mentioned in this issue. i do hope for the future we won't need to provide these workarounds.
> 
> to summarise:
> 
> * rename `main.js` to `main.cjs`
> * `package.json` with `{}` contents within `.storybook`
> * [this workaround](https://github.com/philippone/storybook-webpack5-module/blob/61e62f14be5d4083d40d64de9d09a64830406e8b/.storybook/main.cjs#L1-L47) to fix the `require is not defined` error
> * `resolve-typescript-plugin` webpack plugin to allow fully specified paths in typescript (required for ESM support)
> 
> here's my updated repo showing the working workarounds: https://github.com/badsyntax/storybook-webpack5-esm-typescript

Just don't use the new on-demand architecture as it will break the workaround, e.g.:
``` 
   features: {
        storyStoreV7: true,
    },

**Comment by shilman** [comment]
If you want this fixed, please upvote by adding a 👍 to the issue description. We use this to help prioritize!

**Comment by shilman** [comment]
Yee-haw!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-alpha.23 containing PR #16727 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by arty-name** [comment]
It works!  Thank you very much for fixing it! :bow:

**Comment by benjambles** [comment]
Thanks @shilman!

**Comment by tmeasday** [comment]
Thanks to @jpzwarte for the fix here!

**Comment by benbender** [comment]
> https://github.com/benjambles/my-own-world/blob/master/packages/ui/.storybook/main.cjs#L33

As this pr is reverted, this should be reopenend, @shilman?

**Comment by benbender** [comment]
As this pr is reverted in https://github.com/storybookjs/storybook/pull/17361, this should be reopenend, @shilman?

**Comment by shilman** [comment]
Good call @benbender -- hopefully we can get a fix that doesn't break CRA this week

**Comment by benbender** [comment]
That would be wonderful news as I simply pinned `"@storybook/builder-webpack5": "6.5.0-alpha.25",` for now as I needed a working setup ;)

**Comment by tmeasday** [comment]
For those following along, the fix in the CRA preset is here: https://github.com/storybookjs/presets/pull/229

**Comment by shilman** [comment]
Released as `@storybook/preset-create-react-app@4.0.1` if somebody can please test it out @benbender @tmeasday

**Comment by benbender** [comment]
@shilman I don't use cra but sveltekit, sorry

**Comment by mynormh** [comment]
Hi! I ran into this issue and none of the workarounds worked for me so I tried `npx sb upgrade --prerelease` but I'm still seeing the same error whenever I try to add a webpack plugin in `main.js`
```
ReferenceError: require is not defined
    at Object.regenerator-runtime/runtime (main.iframe.bundle.js:2217:1)
    at __webpack_require__ (runtime~main.iframe.bundle.js:854:30)
```

**Comment by arty-name** [comment]
This doesn’t seem to be an issue in 6.5.4 anymore :+1: Thank you for fixing it!

**Comment by dgattey** [comment]
Still seeing this as an issue in 6.5.15 with `storyStoreV7` true 😕 with `build-storybook`

**Comment by nickbullock** [comment]
@arty-name hey, could you please reopen it since it's still actual with `storyStoreV7` flag?

**Comment by arty-name** [comment]
Hey folks, in my experience, the developers pay more attention to new issues rather than to ones reopened with additions. Since I haven’t used the `storyStoreV7` myself and have no more details about what you’re seeing, I recommend creating a new issue with the minimal reproduction case. Of course, feel free to link it to this one. I am not a developer of storybook myself, I’m just a user of it, like you.

**Comment by tmeasday** [comment]
Also, could you try with SB7 please? This stuff has changed a lot and we are close to release.

**Comment by arty-name** [comment]
@tmeasday Thank you for checking! My projects seem to run fine with the SB7 prerelease, and I even could remove the workarounds. Well done!

**Comment by valentinpalkovic** [comment]
@tmeasday Couldn't we change the content of the virtual files to use dynamic imports instead, which are supported in ESM and CommonJS environments?

**Comment by tmeasday** [comment]
@valentinpalkovic, naively yes. I don't see any reason that:

https://github.com/storybookjs/storybook/blob/a172e0464faeade5fdb2a9d78dcf2666401b70cf/code/builders/builder-webpack5/templates/virtualModuleModernEntry.js.handlebars#L8-L9

Couldn't be changed to 

```ts
const getProjectAnnotations = async () =>
  composeConfigs(await Promise.all([{{#each previewAnnotations}}import('{{this}}'),{{/each}}]));
```

This issue is closed though. What is the circumstance that cause it to happen again?

Very happy to look at it again together if you like.

**Comment by valentinpalkovic** [comment]
@tmeasday I created a PR last year in July to partially fix this issue, but it was never merged: https://github.com/storybookjs/storybook/pull/18620. I will do some quick testing in the afternoon to determine whether this is still a thing.

**Comment by tmeasday** [comment]
Seems like a step forward.

**Comment by supuwoerc** [comment]
@shilman Our company's project also happened after the execution of the storybook build page error: require is not defined, my colleagues spent a whole day to study the problem, and now the problem is solved, the difference is that we are using vite, but I searched for the problem when I found the issue, I think it should be a class of problems, the root cause of the problem is not defined, the problem is not defined. The root cause is that .storybook/main.js does not read the complete configuration of vite.config.js, I hope that someone later encountered can be solved in this way, or hope to read the complete vite related configuration.

The solution is to manually add the commonjs processing logic like in the image below, which should be a read omission issue?
 
![截图_14e6889f-246e-4dc2-89dd-0ccc9dfac0da_副本](https://github.com/user-attachments/assets/43796e1b-b8f2-42e5-84f6-6bea2c6926d6)

**Comment by abcdmku** [comment]
@supuwoerc Thank you!! This fixed the issue I was having with vite when pushing storybook to chromatic

Heres how I configured `.storybook/main.js`:

```diff
const config: StorybookConfig = {
  stories: [
    '../src/**/*.mdx', 
    '../src/**/*.stories.@(js|jsx|mjs|ts|tsx)',
  ],
  addons: [
    '@storybook/addon-essentials',
    '@storybook/addon-mdx-gfm',
    '@storybook/addon-interactions',
    '@chromatic-com/storybook',
  ],
  framework: {
    name: '@storybook/react-vite',
    options: {},
  },

  viteFinal: async (config) =>
    mergeConfig(config, {
+      build: {
+        commonjsOptions: {
+          transformMixedEsModules: true,
+        }
+      },
      server: { port: 4400 },
      plugins: [react(), nxViteTsPaths()],
    }),
};

```
