### ISSUE TITLE
trim security vulnerability

### ISSUE THREAD

**Issue by sjohnson-sage** [storybookjs/storybook#14886]
`trim` versions less than 0.0.3 are vulnerable as per https://github.com/advisories/GHSA-w5p7-h5w8-2hfq

This is a downstream dependency of `@storybook/addon-docs` - I'm using the latest version (6.2.9)

![image](https://user-images.githubusercontent.com/14963680/117787783-af146d00-b23e-11eb-9c3d-82a9c51914ef.png)

It would be great if this could be updated when the underlying dependencies are patched as well!

Thanks

**Comment by shilman** [comment]
closing as dupe to #14603
