### ISSUE TITLE
Storybook not compiling the React functional default enum value  

### ISSUE THREAD

**Issue by sahanatroam** [storybookjs/storybook#14895]
**Describe the bug**
When an `enum` is used to set default value in React functional component storybook doesn't use the enum value but it uses the full enum that's passed in.

```ts
const IconLink = ({
  variant = IconLinkVariants.Primary,
}: IconLinkProps): JSX.Element => {
  console.log(variant); // prints "IconLinkVariants.Primary"
})
```

**To Reproduce**
Link to a reproduction repo that demonstrates the bug, plus instructions on how to trigger it.
https://github.com/sahanatroam/storybook-bug
```
cd storybook-bug/ui
yarn install
yarn storybook
```
`<img width="1676" alt="Screen Shot 2021-05-12 at 10 52 42" src="https://user-images.githubusercontent.com/29851224/117894303-2fef6980-b310-11eb-8ed8-904654c30e24.png">` 

**System**
Please paste the results of `npx sb@next info` here.

```
System:
    OS: macOS 11.2.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 15.6.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.4.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 90.0.4430.93
    Firefox: 84.0.2
    Safari: 14.0.3
  npmPackages:
    @storybook/addon-actions: ^6.2.5 => 6.2.9 
    @storybook/addon-essentials: ^6.2.5 => 6.2.9 
    @storybook/addon-links: ^6.2.5 => 6.2.9 
    @storybook/addons: ^6.2.5 => 6.2.9 
    @storybook/react: ^6.2.5 => 6.2.9 
    @storybook/theming: ^6.2.5 => 6.2.9 
```

**Additional context**

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid.

Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
