### ISSUE TITLE
Blank page and JS error on navigation when an arg is named "background" and set to true

### ISSUE THREAD

**Issue by phbernard** [storybookjs/storybook#14902]
**Describe the bug**

When a React component has a prop named `background`, and when this prop is set to `true` in a story, navigating to this story fails. Instead, just after the story is displayed, the page becomes blank and there is a JS error:

    Uncaught TypeError: value.replace is not a function
    at parseValue (2.manager.bundle.js:361)
        at 2.manager.bundle.js:416
        at mountState (vendors~main.manager.bundle.js:103296)
        at Object.useState (vendors~main.manager.bundle.js:103918)
        at useState (vendors~main.manager.bundle.js:118346)
        at useColorInput (2.manager.bundle.js:415)
        at ColorControl (2.manager.bundle.js:499)
        at renderWithHooks (vendors~main.manager.bundle.js:102655)
        at updateFunctionComponent (vendors~main.manager.bundle.js:105026)
        at mountLazyComponent (vendors~main.manager.bundle.js:105347)

**To Reproduce - With a demo repo**

You can use the demo repo:

    git clone https://github.com/phbernard/storybook-issue.git
	cd storybook-issue
	npm install
	npm run storybook

Navigate to Button > Primary. The page disappears almost instantly and becomes blank. There is a JS error in the background.

**To Reproduce - From scratch**

To reproduce the issue from scratch, so you clearly see what's going on:

    npx create-react-app demo
    cd demo
    npx sb init
    npm run storybook

In your browser, navigate to Button > Primary. You can see the demo button, as expected.

In `src/stories/Button.js`, `Button.propTypes` hash, add a new prop:

    background: PropTypes.bool

In `src/stories/Button.stories.js`, `Primary.args` hash, add a new prop:

    background: true

Navigate to Button > Primary again (you might need to refresh the page). This time, the page disappears almost instantly and becomes blank. There is a JS error in the background.

**System**

Output of `npx sb@next info`:

    System:
      OS: Windows 10 10.0.19042
      CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Binaries:
      Node: 14.15.3 - C:\PROGRAM FILES\NODEJS\node.EXE
      npm: 6.14.9 - C:\PROGRAM FILES\NODEJS\npm.CMD
    Browsers:
      Chrome: 90.0.4430.93
      Edge: Spartan (44.19041.906.0), Chromium (90.0.818.56)
    npmPackages:
      @storybook/addon-actions: ^6.2.9 => 6.2.9
      @storybook/addon-essentials: ^6.2.9 => 6.2.9
      @storybook/addon-links: ^6.2.9 => 6.2.9
      @storybook/node-logger: ^6.2.9 => 6.2.9
      @storybook/preset-create-react-app: ^3.1.7 => 3.1.7
      @storybook/react: ^6.2.9 => 6.2.9

**Additional context**

The issue *does not happen* when:

- The `background` prop is renamed in `src/stories/Button.js` and `src/stories/Button.stories.js` (e.g. to `background_`)
- The `background` prop is set to `false` in `src/stories/Button.stories.js`

**Comment by shilman** [comment]
Can you please create a reproduction by running `npx sb@next repro`, following the instructions, and linking it in your issue description? We prioritize issues with reproductions over those without. Thank you! 🙏

**Comment by phbernard** [comment]
The repro is available at https://github.com/phbernard/storybook-issue-14902.git

Once you have it:

    yarn install
    yarn storybook

Then, from your browser, navigate to the Button > Primary story. The page becomes blank and there is a JS error.

**Comment by shilman** [comment]
Thank you @phbernard, I'll see if we can get this figured out! You might be the first person to use the new `sb repro` flow -- did you run into any difficulties or find anything that can be improved?

**Comment by phbernard** [comment]
Oh, cool! 😎 Although `sb repro` was not essential for this particular issue (I described how to reproduce the issue from scratch), I definitely understand why you want bug report projects to be built in a predictable way, with git tag and all. To this respect, I think `sb repro` is pretty neat! 👍

There is one thing that caught me while using it. There was no doc, and I didn't understand `repro` created new projects from scratch. So I first though this command was supposed to act on my existing bug report repository (the one I posted in my first message). So I run `npx sb@next repro` here. The questions asked by `repro` made sense, somehow: "Yes, this is a CRA project", I though. But it doesn't work, the process fails while running yarn:

    An error occurred while executing: `yarn install`
    Command output was:
    Usage Error: The nearest package directory (C:\Users\philippe\Documents\Programming\storybook-issue\out) doesn't seem to be part of the project declared in C:\Users\philippe\Documents\Programming\storybook-issue.

    - If the project directory is right, it might be that you forgot to list out as a workspace.
    - If it isn't, it's likely because you have a yarn.lock or package.json file there, confusing the project root detection.

The error message says it all, yet I couldn't figure it out immediately. A quick fix for misled people like me would be to early check that `repro` is not run in an existing project, i.e check `package.json` presence, and fail with an explicit message.

**Comment by phbernard** [comment]
@shilman I noticed you added the addon:backgrounds label to this issue. Actually the addon is not involved. This issue is just a matter of naming a prop "`background`".

**Comment by shilman** [comment]
Thanks so much for the feedback @phbernard --- makes a ton of sense and I'll definitely address it tomorrow in the next iteration of `sb repro`!!!

The workaround to your problem is editing `.storybook/preview.js`:

```diff
export const parameters = {
  actions: { argTypesRegex: "^on[A-Z].*" },
  controls: {
    matchers: {
+      color: /color$/i,
-     color: /(background|color)$/i,
      date: /Date$/,
    },
  },
}
```

@yannbf I'm thinking that we should probably change the defaults to be more conservative. WDYT?

**Comment by phbernard** [comment]
It works! Thank you @shilman!

**Comment by shilman** [comment]
Yowza!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.3.0-alpha.26 containing PR #14924 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by phbernard** [comment]
Perfect! Thank you @shilman. Keep the great work!

**Comment by shilman** [comment]
Yee-haw!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.3.0-alpha.29 containing PR #14684 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
