### ISSUE TITLE
Error `TypeError: event is undefined` in manager.bundle.js after upgrade

### ISSUE THREAD

**Issue by julrich** [storybookjs/storybook#14910]
**Describe the bug**
After updating the vite builder (https://github.com/eirslett/storybook-builder-vite) to `0.0.6`, and updating Storybook to `6.3.0-alpha.25`, we are greeted by the following error in the browser console:
```
TypeError: event is undefined
```

This is the line that triggers the error, because `event` is `undefined`:
https://github.com/storybookjs/storybook/blob/643e7eb011a880e2b4b8d82ad360752aa9461dd6/lib/channel-postmessage/src/index.ts#L176

And the `event` in question is:
```
"message":{
   "target":"Window",
   "isTrusted":true,
   "data":"{\"key\":\"storybook-channel\",\"refId\":\"_undefined_\"}",
   "origin":"http://localhost:3000",
   "lastEventId":"",
   "source":"Window",
   "ports":"Restricted",
   "srcElement":"Window",
   "currentTarget":"Window",
   "eventPhase":2,
   "…"
}
```

**To Reproduce**
Unfortunately this isn't really easy for me to extract from our use-case. If it turns out to be hard to reproduce, I'd try my hand on a smaller repro.

**System**
```
Environment Info:

  System:
    OS: Linux 5.11 Arch Linux
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Binaries:
    Node: 12.22.1 - ~/.nvm/versions/node/v12.22.1/bin/node
    Yarn: 1.22.10 - /usr/bin/yarn
    npm: 6.14.12 - ~/.nvm/versions/node/v12.22.1/bin/npm
  Browsers:
    Firefox: 87.0
```

**Additional context**
Not entirely sure if this error originates in Storybook, the vite builder or the unique combination of both!

Let me know if I can help further!

**Comment by Dschungelabenteuer** [comment]
I hope I'm not completely mistaken but from what I've seen while taking a look at this issue, it seems like [telejson's `stringify` function call in @storybook/channel-postmessage's `send` method](https://github.com/storybookjs/storybook/blob/next/lib/channel-postmessage/src/index.ts#L77) does not apply properly when using the vite-builder (tested against a Vite + Vue 3 + Storybook environment). It show no problem processing the `key` and `refId` keys. However, when processing the `event` key, it looks like it systematically catches a TypeError stating that `isObject is not a function` and returns `undefined`, resulting in @julrich error.

This happens for the following messages: 
* currentStoryWasSet
* docsRendered
* storySpecified
* setStories

And this may be why:

![issue-14910](https://user-images.githubusercontent.com/16818271/118326068-b8366000-b504-11eb-9ae1-77112a209139.png)

**Comment by shilman** [comment]
@Dschungelabenteuer Thanks so much for tracking this down! The only thing you're guilty of is being amazing!!! ❤️

**Comment by shilman** [comment]
@ndelangen @eirslett any idea what could be going on here?

**Comment by julrich** [comment]
And let me know if I can help some way!

**Comment by ndelangen** [comment]
We should update storybook to use the new version of telejson

**Comment by shilman** [comment]
Shiver me timbers!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.3.0-alpha.34 containing PR #14983 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by julrich** [comment]
Can confirm, fixes the issue for us! Thanks a lot for the quick turnaround!
