### ISSUE TITLE
Addons panel does not appear

### ISSUE THREAD

**Issue by michaelaflores** [storybookjs/storybook#14916]
**Describe the bug**

This is duplicating #11670 which was closed for inactivity, as this is still a problem on 6.1.14. Opening storybook for a project, viewport changes from opening DevTools or sometimes no user action at all, the actions addon panel is not visible. Using the "D" shortcut is a known workaround. However this shortcut may not be obvious to non-devs/casual users using the tool as a documentation source. Currently trying to validate if this is only an issue in local environments or if it also affects the static build (a prior bug report indicated it does not affect the static build).

**To Reproduce**

Same as #11670 

1. Open storybook
2. Observe that Addons panel may not be visible (trying to get a more concrete repro than, "this randomly happens")

**System**

```
Environment Info:

  System:
    OS: macOS 11.3.1
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 15.12.0 - ~/.nvm/versions/node/v15.12.0/bin/node
    Yarn: 2.4.1 - /opt/homebrew/bin/yarn
    npm: 7.6.3 - ~/.nvm/versions/node/v15.12.0/bin/npm
  Browsers:
    Chrome: 90.0.4430.212
    Firefox: 87.0
    Safari: 14.1
```

**Additional context**

**Comment by michaelaflores** [comment]
I've tried to find concrete repro steps but this is a pretty random bug it seems. Is there something in Storybook code I could be looking at with regards to the add-on panel and its state that I can keep an eye on so next time the bug appears I can put more info here?

**Comment by ndelangen** [comment]
![Screenshot 2022-12-21 at 13 54 41](https://user-images.githubusercontent.com/3070389/208910233-f4befcda-073f-459c-8ee2-c52e9f3ee685.png)

{
  "resizerPanel": {
    "x": 0,
    "y": -210
  },
  "resizerNav": {
    "x": 358,
    "y": 0
  }
}

**Comment by manavm1990** [comment]
> If your addon in storybook is suddenly not showing, simply execute the following command in your browser console: `localStorage. clear();` Refresh the page and voila!
[Source](https://chsamii.medium.com/storybook-addon-not-showing-bbbcffc40458#:~:text=If%20your%20addon%20in%20storybook%20is%20suddenly%20not%20showing%2C%20simply,Refresh%20the%20page%20and%20voila!)
