### ISSUE TITLE
Storybook is not working with angular 12

### ISSUE THREAD

**Issue by rkanthaliya** [storybookjs/storybook#14915]
I Have updated my project to angular 12 and updated the storybook with webpack-5 (as angular 12 works with webpack-5). But after running the storybook command I am getting the below error.

![image](https://user-images.githubusercontent.com/55477535/118161397-27488180-b43d-11eb-937c-8c80ff20a0d3.png)

**Comment by shilman** [comment]
closing as dupe to #14909
