### ISSUE TITLE
SyntaxError: The requested module '/_snowpack/pkg/global.v4.4.0.js' does not provide an export named 'LOGLEVEL'

### ISSUE THREAD

**Issue by IanVS** [storybookjs/storybook#14913]
**Describe the bug**
I'm running tests against my storybooks, using [web-test-runner](https://modern-web.dev/docs/test-runner/overview/) via snowpack.  When I use `@storybook/addon-actions` in any of my stories that I'm testing, I get an error in the console output:

```
SyntaxError: The requested module '/_snowpack/pkg/global.v4.4.0.js' does not provide an export named 'LOGLEVEL'
```

I believe that's because snowpack is processing `global` at build time, and adding named exports for each of the properties on `window` (since my tests run in a browser environment), and `LOGLEVEL` isn't one of them.

<details>
<summary>This is the file that snowpack is creating</summary>

var commonjsGlobal = typeof globalThis !== 'undefined' ? globalThis : typeof window !== 'undefined' ? window : typeof global !== 'undefined' ? global : typeof self !== 'undefined' ? self : {};

var win;

if (typeof window !== "undefined") {
    win = window;
} else if (typeof commonjsGlobal !== "undefined") {
    win = commonjsGlobal;
} else if (typeof self !== "undefined"){
    win = self;
} else {
    win = {};
}

var window_1 = win;

var __dirname = window_1.__dirname;
var __filename = window_1.__filename;
var clearImmediate = window_1.clearImmediate;
var clearInterval = window_1.clearInterval;
var clearTimeout = window_1.clearTimeout;
export default window_1;
var exports = window_1.exports;
var global$1 = window_1.global;
var module = window_1.module;
var queueMicrotask = window_1.queueMicrotask;
var require = window_1.require;
var setImmediate = window_1.setImmediate;
var setInterval = window_1.setInterval;
var setTimeout = window_1.setTimeout;
export { __dirname, __filename, window_1 as __moduleExports, clearImmediate, clearInterval, clearTimeout, exports, global$1 as global, module, queueMicrotask, require, setImmediate, setInterval, setTimeout };

</details>

**To Reproduce**
https://github.com/IanVS/storybook-snowpack-loglevel-reproduction/tree/main

**System**
```
 System:
    OS: macOS 11.3.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
    Yarn: 2.4.1 - ~/.nvm/versions/node/v14.16.1/bin/yarn
    npm: 7.10.0 - ~/.nvm/versions/node/v14.16.1/bin/npm
  Browsers:
    Firefox: 88.0
    Safari: 14.1
  npmPackages:
    @storybook/addon-actions: ^6.3.0-alpha.25 => 6.3.0-alpha.25
    @storybook/addon-docs: ^6.3.0-alpha.25 => 6.3.0-alpha.25
    @storybook/addon-essentials: ^6.3.0-alpha.25 => 6.3.0-alpha.25
    @storybook/addon-links: ^6.3.0-alpha.25 => 6.3.0-alpha.25
    @storybook/react: ^6.3.0-alpha.25 => 6.3.0-alpha.25
```

**Additional context**
I think it might be possible to solve this by importing the default import and calling it `global` or something, and then pull `console` and `LOGLEVEL` off of that.

**Comment by shilman** [comment]
Olé!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.3.0-beta.1 containing PR #15043 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
