### ISSUE TITLE
Handle `@storybook/lit` in Storybook CLI `init` command

### ISSUE THREAD

**Issue by gaetanmaisse** [storybookjs/storybook#14930]
**Describe**

As the first alpha of `@storybook/lit` is now out it would be great to have it supported in `npx sb@next init` command.
When a user run this command in a project with `lit` as a dependency it should:
 - Add `@storybook/lit` + `@storybook/addon-essential` to the package.json
 - Add a default Storybook configuration
 - Add some example stories (only TS?)

**Comment by shilman** [comment]
Whoopee!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.3.0-alpha.34 containing PR #14962 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
