### ISSUE TITLE
doc: whats-a-story

### ISSUE THREAD

**Issue by hinogi** [storybookjs/storybook#14951]
https://github.com/storybookjs/storybook/blob/next/docs/get-started/whats-a-story.md

The code example does not match with the image. The code says `label: 'Primary',` but the image show `label: 'Button',`.

**Comment by jonniebigodes** [comment]
@hinogi thank you for bringing this to our attention. We really appreciate it 🙏🏼 ! I just pushed a pull request to address and close this issue.

With that in mind, I'm going to close this and soon the documentation will be updated to reflect the changes.


Stay safe
