### ISSUE TITLE
Show parse errors for numbers and objects; style range input

### ISSUE THREAD

**Issue by tmeasday** [storybookjs/storybook#14972]
Following on from #14579 -- some UI changes @domyen wanted to make that aren't crucial to the core feature (so we won't hold up merging).

 - [ ] Show errors (not just red borders) on invalid inputs for `Number` and `Object`.
 - [x] Style the `Range` input w/ green bar.

**Comment by domyen** [comment]
✅ Styled the range input in this commit https://github.com/storybookjs/storybook/pull/14973/commits/6d61470d7ce07987d50a26e0173f037c8daffefb

**Comment by shilman** [comment]
Ta-da!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.3.0-beta.14 containing PR #14973 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by tmeasday** [comment]
Let's sort of out the input errors in 6.4, I guess: https://github.com/storybookjs/storybook/issues/15158
