### ISSUE TITLE
Addon controls: Color control does not reset when clicking on reset controls

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#14978]
**Describe the bug**
When resetting controls, the color control does not go back to its original value.

![controls-bug](https://user-images.githubusercontent.com/1671563/118657616-ec9f6a00-b7eb-11eb-9ca7-f6b0d1dc5b8d.gif)

**To Reproduce**
Access the deployed storybook and try it out like the gif.
https://next--storybookjs.netlify.app/official-storybook/?path=/story/addons-controls--action

**Additional context**

I think the problem happens because `initialValue` is only taken into account when initializing the control, as you can see [here](https://github.com/storybookjs/storybook/blob/next/lib/components/src/controls/Color.tsx#L211), so when the value is reset, the change is not picked up.

**Comment by 88ta** [comment]
Hi. I would like to work on this issue.

**Comment by shilman** [comment]
Jeepers creepers!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.3.0-beta.18 containing PR #15059 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
