### ISSUE TITLE
Storybook documentation stories with filename `.mdx` instead of `.stories.mdx`

### ISSUE THREAD

**Issue by TheKnarf** [storybookjs/storybook#14986]
**Is your feature request related to a problem? Please describe**
While adding a lot of `mdx` documentation to Storybook I would like those files to simply be named `.mdx` and not `.stories.mdx`, but that does not currently seem to work.

**Describe the solution you'd like**
Add support for any filename as long as it matches the glob pattern in `.storybook/main.js`.

**Describe alternatives you've considered**
The alternative is having to either rename a lot fo files, or creating duplicate files importing each other.

**Are you able to assist to bring the feature to reality?**
If possible I'd be happy to try and create a PR if anyone can point me in the right direction to fix this issue.

**Additional context**
I have a lot of documentation thats already `.mdx` or `.md` and I would like to not have to rename files to `.stories.mdx` to add them to Storybook. This relates to issue #14787.

**Comment by YozhEzhi** [comment]
[Here](https://github.com/storybookjs/storybook/blob/483ca6b38303bbd768f66d15e3df2f7a380632d2/addons/docs/src/frameworks/common/preset.ts#L113) Storybook has some customisations for mdx files.

I don't know why. But I think there is no possibility to use `my.mdx` for stories like in your case.

**Comment by shilman** [comment]
You can configure this by hand by updating your webpack config per @YozhEzhi 's snippet above, but including `.mdx` files in the webpack rule.

**Comment by stuffaboutpete** [comment]
This is definitely a point of confusion.

The fact that you can supply an array of globs in `main.js` implies that you can make your own choice. When I moved my `mdx` files to a new directory named `documentation` I update the globs as the `.stories.mdx` extension seemed verbose at this point - and Storybook gave me the message 'nothing found'.

**Comment by shilman** [comment]
We've addressed this in 7.0 but still need to finalize things and update the documentation accordingly.

**Comment by jonniebigodes** [comment]
Closing this issue for now as a recent pull request addressed the changes required for enabling MDX documentation support for Storybook in Storybook 7.0

Feel free to ping me with any additional issues you may encounter, and I'll gladly re-open it as we continue working on the feature.

Hope all of you have a great weekend.

Stay safe
