### ISSUE TITLE
Cannot find module 'rollup'

### ISSUE THREAD

**Issue by machineghost** [storybookjs/storybook#14990]
**Describe the bug**

When I try to start Storybook, I get the following error:

>Cannot find module 'rollup'

**To Reproduce**

1. Install Storybook as per the instructions: `npx sb init`
2. Run Storybook as per the instructions: `npm run storybook`

**System**
Please paste the results of `npx sb@next info` here.

Environment Info:

  System:
    OS: Linux 5.4 Linux Mint 20.1 (Ulyssa)
    CPU: (8) x64 Intel(R) Core(TM) i7-4810MQ CPU @ 2.80GHz
  Binaries:
    Node: 15.10.0 - /usr/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 7.3.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 90.0.4430.93
    Firefox: 86.0
  npmPackages:
    @storybook/addon-actions: ^6.2.9 => 6.2.9 
    @storybook/addon-essentials: ^6.2.9 => 6.2.9 
    @storybook/addon-links: ^6.2.9 => 6.2.9 
    @storybook/node-logger: ^6.2.9 => 6.2.9 
    @storybook/preset-create-react-app: ^3.1.7 => 3.1.7 
    @storybook/react: ^6.2.9 => 6.2.9 

**Additional context**
Obviously I can install rollup, but if it's a dependency of Storybook ... it should be listed as such.

P.S. Installing rollup (`npm i --save-dev rollup`) **does not** fix it; I just get new failing dependencies:

>ERR! Error: Cannot find module 'rollup-plugin-terser'

**Comment by shilman** [comment]
Can you please create a reproduction by running `npx sb@next repro`, following the instructions, and linking it in your issue description? We prioritize issues with reproductions over those without. Thank you! 🙏

**Comment by machineghost** [comment]
Your reproduction program continually crashed, complaining about my output directory whether I put it inside the project folder or above it.  After more than half an hour trying to make it work, I give up.
