### ISSUE TITLE
StoryShots for async rendered components -Angular-

### ISSUE THREAD

**Issue by sharifmacky** [storybookjs/storybook#15000]
Could you provide an example of async rendering for angular? Specifically in StoryShots.test.js how can an angular component be mounted as Enzyme doesn't have an appropriate adaptor?

**Comment by ndelangen** [comment]
We have examples for for how to use storyshots here:
https://github.com/storybookjs/storybook/blob/af0578d99ca3972d01700d7b4aa8c7f2de49ab5e/code/addons/storyshots-core/stories/storyshot.async.test.js#L1-L41
