### ISSUE TITLE
`npx sb extract` returns Error: Browser is not downloaded. Run "npm install" or "yarn install" 

### ISSUE THREAD

**Issue by jeremytenjo** [storybookjs/storybook#15004]
**Describe the bug**
Running `npx extract` returns error: 

```sh
info connecting to: http://localhost:51291/iframe.html
info installing puppeteer...
Error: Browser is not downloaded. Run "npm install" or "yarn install"
    at ChromeLauncher.launch (/Users/jeremytenjo/.npm/_npx/25211/lib/node_modules/sb/node_modules/puppeteer-core/lib/Launcher.js:236:15)
    at async read (/Users/jeremytenjo/.npm/_npx/25211/lib/node_modules/sb/node_modules/@storybook/cli/dist/cjs/extract.js:25:19)
    at async extract (/Users/jeremytenjo/.npm/_npx/25211/lib/node_modules/sb/node_modules/@storybook/cli/dist/cjs/extract.js:81:18)
```

**To Reproduce**
Open terminal and run 
1. `git clone https://github.com/jeremytenjo/sb.git`
2. `cd sb && npm i && npm run build-storybook && npx sb extract`

It works on macOS Mojave, version 10.14.6 but not on a M1 Mac Mini

**System**
Mac Mini M1

**Comment by shilman** [comment]
If you upgrade to the latest alpha, there's an experimental feature to extract stories.json built into Storybook.

First upgrade:
```
npx sb upgrade --prerelease
```

Then update your `.storybook/main.js`:

```
module.exports = {
  features: {
    buildStoriesJson: true
  }
};
```

Then:

```
yarn build-storybook
```

There should be a `stories.json` file in your output folder in addition to the rest of the files. This feature is experimental and subject to change, but I'd love if you could give it a spin and let me know if it works for you!

**Comment by jeremytenjo** [comment]
Works great for JS stories but MDX do not show up. A Regex master could extract the title's value from `<Meta title='Lib/Theme/Start Guide' />` and all its edge case. Sadly I am not that person 😅

I was able to match a couple cases cases.

![image](https://user-images.githubusercontent.com/25231946/119239262-e83dbe80-bb15-11eb-9167-6b5d1156cb7b.png)

I'll keep an eye out hopefully it works with MDX stories by the next release.

Thanks!

**Comment by shilman** [comment]
Yeah, it doesn't support MDX yet, but should soon

**Comment by jeremytenjo** [comment]
Awesome, looking forward to using that feature.
