### ISSUE TITLE
Storybook Controls working with Typescript String Literal Types

### ISSUE THREAD

**Issue by Develliot** [storybookjs/storybook#15009]
**Is your feature request related to a problem? Please describe**
Recognise Typescript string literal types so if you have a prop like 

```
export type Props = {
  appearance: "primary" | "secondary" | "tertiary"
}
```
Currently Storybook controls sees it as string not a string literal type so the data entry input shown as free text field not a select input.

**Describe the solution you'd like**
It wold be awesome if it could understand string literal types and provide a select input with the options specified in the type. 

**Describe alternatives you've considered**
I did consider changing my types to enums but that would mean re-writing
`<Button appearance="primary"> `
wouldn't work I would have to import the enum and use 
`<Button appearance={enumObject.primary}> `
this would be for everything that uses the component library and in loads of places throughout my component library which would be a massive refactor just to get a select box to appear in storybook.

**Are you able to assist to bring the feature to reality?**
no, sorry I don't know how typescript works under the hood 

**Additional context**
n/a

**Comment by Develliot** [comment]
Oooh this does actually work now

It didn't work when I imported the default export which was 

`export default withTheme(Button);`

but as soon as I used the named 

```
export const Button: FunctionComponent<Props> = forwardRef((props: Props, ref?: Ref<HTMLElement>) => {
....

```
export which wasn't wrapped with styled components withTheme everything magically worked, something tells me styled components withTheme might have been breaking the types somehow.

**Comment by shilman** [comment]
SB uses a library called `react-docgen-typescript`, which I'm guessing has problems with `styled-components`. I think the workaround is as good as we're going to get in the short term, so I'm going to close this for now.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if this is still relevant in SB 7.x.
