### ISSUE TITLE
Addon-docs: Support Angular Ivy rendering of multiple stories on a page

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#15017]
Currently, Storybook's Angular Ivy support (via https://github.com/storybookjs/addon-angular-ivy) requires that each story be fully rendered before a new story can be rendered.

In Canvas mode it's not an issue because we are only rendering one story at a time. In Docs mode, we are rendering N stories on a page, and Ivy crashes.

To support Ivy in docs mode:
- [ ] Create a wrapper component that's returned by Angular's `prepareForInline`
- [ ] Each wrapper participates in a global queue. When a it's a component's turn to render, it renders, otherwise, it perform's a no-op

Making this up, so we will probably need @ThibaudAV 's guidance to make this work.

**Comment by ThibaudAV** [comment]
I think I have a solution from this pr https://github.com/storybookjs/storybook/pull/14911
but still need time to finish and clean the code

**Comment by ThibaudAV** [comment]
done : https://github.com/storybookjs/storybook/pull/15002

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if this is still relevant in SB 7.x.
