### ISSUE TITLE
Storybook missing story when component has Typescript Enum as prop

### ISSUE THREAD

**Issue by jonathanhuang13** [storybookjs/storybook#15011]
**Describe the bug**
When a component has a [Typescript Enum](https://www.typescriptlang.org/docs/handbook/enums.html) as a prop, stories don't show up when the story uses that enum with an arg. If you change the enum to a [literal type](https://www.typescriptlang.org/docs/handbook/enums.html), the story shows up.

**To Reproduce**
https://github.com/jonathanhuang13/storybook-repro/tree/ts-enum-bug

```
npm install
npm run storybook
```

There is a component called `GoodComponent` (story is `Works.stories.tsx`) that uses string literals. This will show up in Storybook. There is another component called `BuggyComponent` (story is `Buggy.stories.tsx`). This will _not_ show up in Storybook.

**System**
Please paste the results of `npx sb@next info` here.

```
Environment Info:

  System:
    OS: macOS 11.3.1
    CPU: (8) x64 Apple M1
  Binaries:
    Node: 14.16.1 - ~/.asdf/installs/nodejs/14.16.1/bin/node
    npm: 6.14.12 - ~/.asdf/installs/nodejs/14.16.1/bin/npm
  Browsers:
    Chrome: 90.0.4430.212
    Safari: 14.1
  npmPackages:
    @storybook/addon-actions: ^6.2.9 => 6.2.9
    @storybook/addon-essentials: ^6.2.9 => 6.2.9
    @storybook/addon-links: ^6.2.9 => 6.2.9
    @storybook/react: ^6.2.9 => 6.2.9
```

**Comment by IgorSzyporyn** [comment]
Pulling your repo and branch I get this error spinning up storybook

<img width="1433" alt="Screenshot 2021-06-04 at 11 42 01" src="https://user-images.githubusercontent.com/6172338/120782090-f33b1a80-c529-11eb-8dcd-aa87377d992f.png">

While just reproducing locally in the official-storybook example I get this

<img width="1434" alt="Screenshot 2021-06-04 at 11 44 08" src="https://user-images.githubusercontent.com/6172338/120782330-31383e80-c52a-11eb-9135-52c1cd1942d5.png">

<img width="1432" alt="Screenshot 2021-06-04 at 11 45 40" src="https://user-images.githubusercontent.com/6172338/120782559-6a70ae80-c52a-11eb-9cd9-28a26b9ba6c7.png">


@jonathanhuang13 @shilman

**Comment by jonathanhuang13** [comment]
Thanks for looking at this @IgorSzyporyn. It seems like the error is with how the component is typed:

```
- const TestComponent: (props: Props) => JSX.Element = (props) => {
+ const TestComponent = (props: Props): JSX.Element => {
};
```

Typing it this way actually fixes both the error of Storybook not spinning up and the original Typescript Enum error. Going to close this issue!

**Comment by IgorSzyporyn** [comment]
> Thanks for looking at this @IgorSzyporyn. It seems like the error is with how the component is typed:
> 
> ```
> - const TestComponent: (props: Props) => JSX.Element = (props) => {
> + const TestComponent = (props: Props): JSX.Element => {
> };
> ```
> 
> Typing it this way actually fixes both the error of Storybook not spinning up and the original Typescript Enum error. Going to close this issue!

I prefer inferred types when possible - why not just do

```ts
const TestComponent = (props: TestComponentProps) => {
  return <div>....</div>
}
```
