### ISSUE TITLE
Radio button needs 2 clicks to reflect change in storybook

### ISSUE THREAD

**Issue by JohnCasab** [storybookjs/storybook#15020]
**Describe the bug**
I have 2 radio buttons, one of them by default is selected, when clicking on the other radio button first time nothing is happening, it needs 2 clicks to be selected.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/72789740/119369928-0130a600-bcb5-11eb-81ab-68b92fcb74dd.gif)

The same code in https://jsfiddle.net/1bfjuht4/ works fine. 

** My Code**
This is a very simplified version of my code! If the complex version is needed then I can post that also.  
TestRadioButton.stories.mdx file:

```
import { Meta, Canvas } from '@storybook/addon-docs/blocks';

<Meta title="Building blocks/components/Radiobutton1" />

<Canvas>
      <div>
         <input type="radio" tabindex="0" id="preview1" name="preview"value="SAMPLE" checked/>
         <label for="preview1">Radiobutton1</label>
      </div>
      <div>
          <input type="radio" tabindex="0" id="preview2" name="preview" value="BACKUP"/>
          <label for="preview2">Radiobutton2</label>
      </div>
</Canvas>
```

**System**
Environment Info:
```
  System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 15.9.0 - /usr/local/bin/node
    Yarn: 1.22.10 - ~/Desktop/Design/d-system/node_modules/.bin/yarn
    npm: 7.10.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 90.0.4430.212
    Firefox: 87.0
    Safari: 13.1.3
  npmPackages:
    @storybook/addon-actions: ^6.2.9 => 6.2.9
    @storybook/addon-docs: ^6.2.9 => 6.2.9
    @storybook/addon-essentials: ^6.2.9 => 6.2.9
    @storybook/addon-links: ^6.2.9 => 6.2.9
    @storybook/addons: ^6.2.9 => 6.2.9
    @storybook/client-api: ^6.2.9 => 6.2.9
    @storybook/html: ^6.2.9 => 6.2.9
    @storybook/preset-scss: ^1.0.3 => 1.0.3
    @storybook/theming: ^6.2.9 => 6.2.9
```
**Additional context**
If I remove the `selected` attribute it works fine, but by default it has to be selected.

**Comment by JohnCasab** [comment]
Anyone ideas, why this is not working? Should be very simple. 

I can also see its working for the carbon design-system https://www.carbondesignsystem.com/components/radio-button/code/ .

**Comment by JohnCasab** [comment]
I found a solution, because im using `html-react-parser`, i must use the defaultChecked attribute instead of checked. Like this: 

```
import { Meta, Canvas } from '@storybook/addon-docs/blocks';

<Meta title="Building blocks/components/Radiobutton1" />

<Canvas>
      <div>
         <input type="radio" tabindex="0" id="preview1" name="preview"value="SAMPLE" defaultChecked/>
         <label for="preview1">Radiobutton1</label>
      </div>
      <div>
          <input type="radio" tabindex="0" id="preview2" name="preview" value="BACKUP"/>
          <label for="preview2">Radiobutton2</label>
      </div>
</Canvas>
```
Now im trying to understand, why is it checked attribute is not working? And how do I know when to use a `HTML` attribute like `checked` and when is it I have to use `React` attribute like `defaultChecked`?

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
