### ISSUE TITLE
Story not getting prop correctly?

### ISSUE THREAD

**Issue by hmmChase** [storybookjs/storybook#15023]
**Describe the bug**
The label for the button component is missing on the "primary" story

**To Reproduce**
https://github.com/hmmChase/sbtest

**System**
Environment Info:

  System:
    OS: Windows 10 10.0.19042
    CPU: (16) x64 AMD Ryzen 7 1700X Eight-Core Processor
  Binaries:
    Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
    npm: 7.14.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 90.0.4430.212
    Edge: Spartan (44.19041.964.0), Chromium (90.0.818.66)
  npmPackages:
    @storybook/addon-actions: ^6.2.9 => 6.2.9
    @storybook/addon-essentials: ^6.2.9 => 6.2.9
    @storybook/addon-links: ^6.2.9 => 6.2.9
    @storybook/react: ^6.2.9 => 6.2.9

**Additional context**
High probability of user error.

**Comment by shilman** [comment]
I'm not sure why it's inconsistent between the stories but the story itself is weird:

```
const Template = args => <Button label='Butthjgon' {...args} />;
```

This label is getting overwritten by whatever's in args.

For some reason, label is not present in any of the args stories, except the primary story it's there but it's value is `undefined`. It's a bit strange, but that should be enough to work around it.

**Comment by hmmChase** [comment]
Ok, I understand now.  I thought I was being clever by putting the label in the template, instead of every args object, but that doesn't play well with how SB renders the component and populates the controls values.  Thanks very much for your time.
