### ISSUE TITLE
First-class react-docgen support for Typescript

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#15036]
We should implement first-class ArgType extraction in `react-docgen`. It is faster than `react-docgen-typescript` and also better maintained.

See full background/discussion here: https://gist.github.com/shilman/036313ffa3af52ca986b375d90ea46b0

At the time we decided to favor `react-docgen-typescript`, there was no support for imported types in `react-docgen`. Now there is: https://github.com/reactjs/react-docgen/pull/464

What's involved:
- [ ] Update storybook to provide an "importer" for react-docgen
- [ ] Update test cases to convert to ArgTypes properly
- [ ] Benchmark with importer on a real-world project
- [ ] Consider making this the default in SB7.0

**Comment by valentinpalkovic** [comment]
Done.
