### ISSUE TITLE
Zoom reset improperly sizes body on mobile viewport, in Firefox

### ISSUE THREAD

**Issue by z-svoboda-mob** [storybookjs/storybook#15041]
Resetting with the zoom tool in the mobile viewport simulation does not appropriately reset the body size.
As you can see here, this causes overflow after zooming and resetting that does not occur before using the zoom tool.

https://user-images.githubusercontent.com/77058599/119552907-09e2b400-bd69-11eb-9d9e-2f8d5a0d1443.mov

**To Reproduce**
This works in the default angular storybook repro, there's no special setup required.
Make sure to check in firefox, it is using `transform: scale` instead of `zoom`

**System**
Environment Info:

  System:
    OS: macOS 11.3.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.16.1/bin/yarn
    npm: 6.14.12 - ~/.nvm/versions/node/v14.16.1/bin/npm
  Browsers:
    Chrome: 89.0.4389.114
    Edge: 90.0.818.66
    Safari: 14.1
  npmPackages:
    @storybook/addon-actions: ^6.2.9 => 6.2.9 
    @storybook/addon-essentials: ^6.2.9 => 6.2.9 
    @storybook/addon-links: ^6.2.9 => 6.2.9 
    @storybook/angular: ^6.2.9 => 6.2.9 

**Additional context**
It looks like the zoom fallback just needs to add `box-sizing: border-box` or account for the padding on the body element. `width: 100%` & `padding: 1rem`

![Screen Shot 2021-05-25 at 3 32 17 PM](https://user-images.githubusercontent.com/77058599/119557614-66949d80-bd6e-11eb-8289-8d029f65428c.png)

**Comment by BartJanvanAssen** [comment]
Seems like a good one to start with for a first contribution! let me check it out and come up with an pr 👍

**Comment by shilman** [comment]
Good golly!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.3.0-rc.8 containing PR #15128 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
