### ISSUE TITLE
Add comments to Storybook (à la Figma)

### ISSUE THREAD

**Issue by maya** [storybookjs/storybook#15044]
**Is your feature request related to a problem? Please describe**
My designers would like to leave comments on stories as we're developing

**Describe the solution you'd like**
Ability to leave comments on any location of the component story

**Describe alternatives you've considered**
https://storybook.js.org/addons/storybook-feedback/  but it hasn't been updated in 2 years and doesn't allow location-based comments or threads like Figma does.

**Are you able to assist to bring the feature to reality?**
I can review it

**Additional context**
this but Storybook 😄 

<img width="772" alt="file-eAehcF9dj1" src="https://user-images.githubusercontent.com/5249443/119564745-fda52980-bd5d-11eb-93ef-d5185cb3cd62.png">

**Comment by shilman** [comment]
This needs a hosted service to work well, so I don't anticipate this will ever be part of Storybook itself. However, there are multiple services built for hosting and collaborating on Storybooks that include commenting.

[Chromatic](https://www.chromatic.com/) is made by Storybook maintainers (including me), has a free plan, and includes commenting out of the box.

**Comment by maya** [comment]
Wasn't aware of commenting in Chromatic, that should work, thanks

**Comment by helmutgranda** [comment]
What about projects for Enterprise where we the infrastructure exists to host it and would be faster to deploy than having to get a green light to use Chromatic?
