### ISSUE TITLE
Cannot convert null or undefined to an object

### ISSUE THREAD

**Issue by Krausso** [storybookjs/storybook#15040]
**Describe the bug**
I moved a literal from IconType to IconProps, so that I could use it through `IconProps['name']`. 
However, it does not work and storybook just stops working.
What's interesting, that size is realized in the same way but it's working perfectly.

**System**
```
"@storybook/addon-docs": "^6.2.9"
"@storybook/addon-essentials": "^6.2.9"
"@storybook/react": "^6.2.9"
"@storybook/source-loader": "^6.2.9"
```

**Additional context**
![image](https://user-images.githubusercontent.com/52201020/119555783-ed656c80-bda6-11eb-8e1c-0fa0ec127aab.png)
![image](https://user-images.githubusercontent.com/52201020/119555986-23a2ec00-bda7-11eb-9937-c748d5455d48.png)

**Comment by Krausso** [comment]
Forgot to add. Error appears when I'm adding the following code
```
leadingIcon: {
  control: {
    type: 'select',
  }
}
```
There can be trailingIcon as well, no matter, error is same
![image](https://user-images.githubusercontent.com/52201020/119556310-82686580-bda7-11eb-89dc-bd24f0fd76f4.png)

**Comment by shilman** [comment]
Is it because `name` is required and `size` is optional?

**Comment by Krausso** [comment]
No. I've already tried to make size & name both required or both optional. That doesn't help, although I have another idea.
Pro'lly gonna answer in a few hours, I think.

**Comment by Krausso** [comment]
Solved.
![image](https://user-images.githubusercontent.com/52201020/119618360-7a421180-be0b-11eb-9fd2-90cd5695db20.png)
![image](https://user-images.githubusercontent.com/52201020/119618419-8a59f100-be0b-11eb-853b-dbf1e25255e2.png)
![image](https://user-images.githubusercontent.com/52201020/119618502-a3fb3880-be0b-11eb-9205-68fafd7cea35.png)
And in `argTypes` I've pasted the following code:
```
leadingIcon: {
  control: {
    type: 'select',
    options: Object.keys(icons)
  }
}
```
