### ISSUE TITLE
Permalinking and direct linking to stories is broken

### ISSUE THREAD

**Issue by eranimo** [storybookjs/storybook#15045]
**Describe the bug**
Permalinking to stories (reloading, open in new tab, etc) is broken. The first story is always selected when you visit the page, regardless of the path or id.

Also, when selecting stories it seems like there's a redirect that is very quick. There is a `path` query param that appears for a split second before being replaced with `id`. Not sure if that is related.

**To Reproduce**
NOTE: I tried to make a reproduction but I got an error using your script. Something about yarn workspaces not configured right.

We are using a custom webpack config that adds our own Babel config.

**System**
```
System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 12.21.0 - ~/.nvm/versions/node/v12.21.0/bin/node
    npm: 6.14.11 - ~/.nvm/versions/node/v12.21.0/bin/npm
  Browsers:
    Chrome: 90.0.4430.212
    Firefox: 87.0
    Safari: 13.1.3
```

**Additional context**
Adding an `id` option to enable a permalink is also broken. When you refresh the page the first story is selected. I'm not getting any errors or warnings when building. All of the stories use the new-style syntax grouped into several folders.

This issue happens in both development mode and after being statically built.

**Comment by shilman** [comment]
Can't reproduce this in our example apps, e.g.

https://next--storybookjs.netlify.app/official-storybook/?path=/story/addons-links-button--first

**Comment by eranimo** [comment]
Seems like the problem is the redirect then. Any idea why its redirecting to `id`? We're on 6.2 btw

**Comment by supersnager** [comment]
@shilman The problem is in the docs tab.
Please enter this url: https://next--storybookjs.netlify.app/official-storybook/?path=/docs/addons-backgrounds--with-image

The docs window should be scrolled to the "With Image story", but the scroll stays at the top.

**Comment by theresaluu** [comment]
Question about how this is supposed to work- is clicking on the link icon next to the header to get the id hash link, is it supposed to copy to our clipboard or is it only supposed to scroll on the docs page to place it to the top?

**Comment by supersnager** [comment]
@theresaluu I think copying the link is not related to this issue.  We are considering choosing the menu item, not clicking in the header.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
