### ISSUE TITLE
Assigning args from imported object prevents the story from loading on start-storybook.

### ISSUE THREAD

**Issue by SimeonRolev** [storybookjs/storybook#15069]
Hi, guys!
I have the following issue, I have a component that I want to both test and have a story for. The component has a lot of parameters that I wanted to move to a separate file, so I don't duplicate them in my tests and story. Simplified example:

`Args.default.js`
```js
export const args = {
  first: 1,
  second: 2
}
```

Then I try to load them in my stories by expanding the object from the import statement:

`Example.stories.js`
```javascript
import { args } from './Args.default';

const Template = args => <MyComponent {...args} />;
export const Default = Template.bind({});
Default.args = {
    ...args,
    anotherArg: "example"
};
```

**To Reproduce**
The issue:
- Run `npm run start-storybook`. The story is not showing at all in the Storybook side panel on the first `storybook-start` command. I assume some error occurs, but I didn't find a log.
- Change something in the code, the fast-reload triggers and suddenly the story shows up properly.

Expected:
- The story to show from the first time.

Note:
If I just copy-paste the args instead of importing and spreading them, the story loads properly from the initial start of Storybook

**System**
```
  System:
    OS: Linux 5.8 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  Binaries:
    Node: 15.14.0 - ~/.nvm/versions/node/v15.14.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v15.14.0/bin/yarn
    npm: 7.7.6 - ~/.nvm/versions/node/v15.14.0/bin/npm
  Browsers:
    Chrome: 90.0.4430.93
    Firefox: 88.0.1
  npmPackages:
    @storybook/addon-essentials: ^6.2.9 => 6.2.9 
    @storybook/addon-knobs: ^6.1.21 => 6.2.9 
    @storybook/preset-create-react-app: ^3.1.7 => 3.1.7 
    @storybook/react: ^6.1.21 => 6.2.9 
```

**Comment by shilman** [comment]
Can you please create a reproduction by running `npx sb@next repro`, following the instructions, and linking it in your issue description? We prioritize issues with reproductions over those without. Thank you! 🙏
