### ISSUE TITLE
@storybook/addon-storyshots-puppeteer with puppeteer last version

### ISSUE THREAD

**Issue by vmalay** [storybookjs/storybook#15079]
Hello, 

I was wondering if there is a reason why the @storybook/addon-storyshots-puppeteer is not using the last version of puppeteer. 

I have worked with this addon and the last version of puppeteer without any problem. However with NPM v7 peerDependencies are now considered as error and it's not a warning anymore, making npm install @storybook/addon-storyshots-puppeteer fail with the last version of puppeteer.

Indeed, @storybook/addon-storyshots-puppeteer is using  "puppeteer": "^2.0.0 || ^3.0.0" as peerDependencies.

https://github.com/storybookjs/storybook/blob/next/addons/storyshots/storyshots-puppeteer/package.json#L57
`
"peerDependencies": {
            "@storybook/addon-storyshots": "6.3.0-beta.4",
            "puppeteer": "^2.0.0 || ^3.0.0"
},
`

Is there a reason why it's using only puppeteer 2.0 and 3.0 ? Puppeteer is now at the v9.1.1. I wonder if it's possible to update the dependencies to use the last version.

Thanks,

**Comment by shilman** [comment]
@vmalay any interest in contributing a PR to fix it?

**Comment by vmalay** [comment]
Yes, I've tried it here : https://github.com/storybookjs/storybook/pull/15091

**Comment by shilman** [comment]
ZOMG!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-alpha.10 containing PR #15163 that references this issue. Upgrade today to the `@future` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
