### ISSUE TITLE
Angular: addon-docs: allow multiple components

### ISSUE THREAD

**Issue by adriankremer** [storybookjs/storybook#15076]
**Is your feature request related to a problem? Please describe**
Complex components/modules can consist of multiple components (e.g. tabs: tab-header, tab-content).
See react example: https://workday.github.io/canvas-kit/?path=/docs/labs-tabs-react--alternative-tab-stop
This story documentation shows only the propstable of the main component while the props of Tab.Item are not visible.

**Describe the solution you'd like**
Especially for angular (compodoc) it would be nice to allow an array of components  per story, so that the proptables of the configured components will be shown in the docs.

**Describe alternatives you've considered**
The only way around would be to create a story per component which is hard to maintain.

**Are you able to assist to bring the feature to reality?**
yes, I can...

**Comment by shilman** [comment]
In storybook docs (where this data is used) we force a single primary component. But you can specify multiple `subcomponents` in an object and it will show those in tabs

**Comment by adriankremer** [comment]
This is super awesome!! Thank you.
Have a nice weekend.
