### ISSUE TITLE
Issue with reproduction generator

### ISSUE THREAD

**Issue by jonniebigodes** [storybookjs/storybook#15085]
While working on the documentation to get new contributors onboarded to the reproduction process, I've stumbled into a couple of issues with the generator.

When choosing the react as a framework, followed by the yarn workspaces template it yields the following result:

![error-in-cra-monorepo](https://user-images.githubusercontent.com/22988955/120049540-33723880-c012-11eb-8158-4f97297073b1.png)

Tried a couple of places, tested it in a Windows box, and the same outcome always. Possibly [related comment](https://github.com/storybookjs/storybook/issues/14990#issuecomment-846226273).

Another thing that came into mind when working with the generator was related to [this issue](https://github.com/storybookjs/storybook/issues/4764#issuecomment-849458795). While I'm aware that this is basically an upstream issue, we can probably mitigate this on our end either by:
- Lower the babel version that is being pulled in.
- Add the `SKIP_PREFLIGHT_CHECK=true` environment variable in the same as the `FAST_REFRESH=true` one.

Finally, one thing that we probably need to look into in the future. As of now, the generator works similarly to a one-way street. Basically, if a user starts it, selects a framework by mistake, and decides to go back, he/she will be blocked and will have to restart the whole process once again. Probably not a bad idea to have additional keys mapped and usable.

@shilman and @tmeasday would appreciate your feedback on this.

**Comment by shilman** [comment]
Thanks @jonniebigodes! I agree with adding `SKIP_PREFLIGHT_CHECK=true` to the repro & will add that.

With regards to `react_in_yarn_workspace` can you explain what this is for @gaetanmaisse @tooppaaa? I don't understand why we're giving that option to users.

@jonniebigodes as for improving the ergonomics of the CLI, I personally don't think it's that important--the user can just cancel and start again as far as I'm concerned. However, I'd happily review a PR with any UI improvements you'd like to add.

**Comment by jonniebigodes** [comment]
No problem and thank you for adding the `SKIP_PREFLIGHT_CHECK=true` to the reproduction template. I'll reach out to them on Discord and clarify the issue with the `react_in_yarnworkspace` template.

**Comment by gaetanmaisse** [comment]
`react_in_yarnworkspace` was added in the e2e process after some issue with the CLI, see:  
 - https://github.com/storybookjs/storybook/pull/10985
 - https://github.com/storybookjs/storybook/issues/10915

I'm not sure it makes sense to keep it in the repros but maybe we should find a way to still have it in the e2e.

**Comment by shilman** [comment]
ZOMG!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.3.0-beta.6 containing PR #15114 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
