### ISSUE TITLE
The ability to mock a subcomponent in a story

### ISSUE THREAD

**Issue by dessskris** [storybookjs/storybook#15116]
**Is your feature request related to a problem? Please describe**
I'm always frustrated when my component uses the current date time instead of a mocked date time, and it breaks the GQL mock.

Use case: the current date time is used for a GQL query variable input. Since I need to provide the GQL mock, and `MockedProvider` requires the request to exactly match the query and the variables, it is unable to dynamically match the date in my GQL mock.

This is not an issue in my test file since I can mock the current date there, so this only affects Storybook.

**Describe the solution you'd like**
Being able to do things like `jest.mock` in a story

**Describe alternatives you've considered**
For the specific use case above: generate the date for the GQL mock at the time of story render. However if the user loads the story and spends over a minute on that page, the GQL mock will no longer match the current time.

Copy paste the component implementation but mock the date, or add a `mockDate` prop, but this is not useful for the real business case nor the unit test so this is an unnecessary workaround for just to make the story work.

Use webpack aliasing described [here](https://storybook.js.org/docs/react/workflows/build-pages-with-storybook#mocking-imports), but I have a monorepo so this doesn't seem like a clean solution (especially as this only needs mocked in one story, and the story is not being reused anywhere else)

**Are you able to assist to bring the feature to reality?**
no 

**Additional context**
Another example of a use case for this https://stackoverflow.com/questions/56452973/are-dynamic-mocks-possible-in-storybooks-using-apollos-mockedprovider

**Comment by shilman** [comment]
Is this a dupe to #14873?

**Comment by dessskris** [comment]
> Is this a dupe to #14873?

Interesting! Yes, I would just add that we should also be able to mock a child component that's used in the component we want to showcase in the story

e.g. the story is for `<Parent />`
but the implementation of `Parent` uses `<Child />`
we should be able to mock `Child` in `Parent`'s story

**Comment by shilman** [comment]
@dessskris Thanks, that makes sense. I'm going to close this issue as a duplicate -- could you add that as a comment to #14873 so it doesn't get lost? I'm not sure when we'll get to the feature, but I agree that's an important use case/top-level requirement! 🙏
