### ISSUE TITLE
Error executing the npx sb init command

### ISSUE THREAD

**Issue by claudiodietrich** [storybookjs/storybook#15110]
**Describe the bug**
When trying to install StoryBook through the `npx sb init` command the following error is returned: `sb: cannot open init: No such file or directory`

**To Reproduce**
```
npx create-react-app my-app

cd my-app

npx sb init

sb: cannot open init: No such file or directory
Can't open any requested files.
```

**System**
```
Environment Info:

  System:
    OS: Linux 5.12 Fedora 34 (Workstation Edition) 34 (Workstation Edition)
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
  Binaries:
    Node: 14.17.0 - /usr/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.13 - /usr/bin/npm
  Browsers:
    Firefox: 88.0.1
```

**Comment by shilman** [comment]
I can't reproduce this. Perhaps try `npx sb@latest init` or `npx sb@next init`?

**Comment by claudiodietrich** [comment]
@shilman, it worked using the `npx sb@latest init` command. Thanks!

**Comment by danini-the-panini** [comment]
This happened to me, too. It seems that `sb` on some systems is in the PATH and refers to a completely different tool. I solved it by first running `npm install -g sb` before running `npx sb init`
