### ISSUE TITLE
jest-preset-angular file paths need updated

### ISSUE THREAD

**Issue by RGunning** [storybookjs/storybook#15124]
**Describe the bug**
jest-preset-angular have moved files around in their v9 release. setup-jest should now be imported from` jest-preset-angular/setup-jest` instead of `jest-preset-angular/build/setup-jest`

The import of setup-jest here needs an additional tryCatch block for the new file location/name https://github.com/storybookjs/storybook/blob/next/addons/storyshots/storyshots-core/src/frameworks/angular/loader.ts#L21 

This bug prevents storyshots from running with jest v27 and jest-preset-angular v9

**To Reproduce**
jest-preset-angular >9

**System**
Environment Info:

  System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.17.0/bin/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm
  Browsers:
    Chrome: 91.0.4472.77
    Firefox: 88.0.1
    Safari: 14.1.1
  npmPackages:
    @storybook/addon-a11y: 6.2.9 => 6.2.9 
    @storybook/addon-actions: 6.2.9 => 6.2.9 
    @storybook/addon-essentials: 6.2.9 => 6.2.9 
    @storybook/addon-links: 6.2.9 => 6.2.9 
    @storybook/addon-postcss: 2.0.0 => 2.0.0 
    @storybook/addon-storyshots: 6.2.9 => 6.2.9 
    @storybook/addon-storysource: 6.2.9 => 6.2.9 
    @storybook/angular: 6.2.9 => 6.2.9 

**Additional context**

**Comment by RGunning** [comment]
Additionally, https://github.com/storybookjs/storybook/blob/next/addons/storyshots/storyshots-core/src/frameworks/angular/renderTree.ts#L1-L2 probably needs updated as well as the serialisers have been renamed:

'jest-preset-angular/build/AngularSnapshotSerializer.js' is changed to 'jest-preset-angular/build/serializers/ng-snapshot.

'jest-preset-angular/build/HTMLCommentSerializer.js' is changed to 'jest-preset-angular/build/serializers/html-comment.

not sure if tryCatch here as well works or if the jest-preset-angular peer dependency should be set to > 9

**Comment by RGunning** [comment]
something like this should do it https://github.com/storybookjs/storybook/compare/next...RGunning:fix/jest-preset-angular

but this means losing backwards compatibility

**Comment by cloakedninjas** [comment]
Will this make it to 6.3 or will it have to wait for 6.4? Oris it possible to have `storyshots` at a different version to the core package?

**Comment by shilman** [comment]
I would recommend somebody releases a forked version of storyshots.

**Comment by chief10** [comment]
Im kind of flabberghasted that they just used a glob pattern for the `jest-preset-angular` dependency. I have no way of knowing which version worked for them. 

Unless you already have an old setup of storyshots going with jest-preset-angular, it looks like doing a new setup is next to impossible with the state of the library and documentation.

**Comment by Mickeiik** [comment]
Don't know if someone forked the project but I managed to make things work by using jest config's moduleNameMapper to override the paths : 

```
moduleNameMapper : {
    'jest-preset-angular/build/setupJest': 'jest-preset-angular/setup-jest',
    'jest-preset-angular/build/AngularSnapshotSerializer': 'jest-preset-angular/build/serializers/ng-snapshot',
    'jest-preset-angular/build/HTMLCommentSerializer': 'jest-preset-angular/build/serializers/html-comment'
}
```

**Comment by ndelangen** [comment]
The future of storyshots is the test-runner:
https://storybook.js.org/docs/react/writing-tests/test-runner#page-top

And use the play function for expectations:
https://storybook.js.org/docs/react/writing-stories/play-function#page-top

We will not be making any improvement / changes to storyshots.
