### ISSUE TITLE
How do i specify different entry point/ output asset for multiple sub projects in a single repository?

### ISSUE THREAD

**Issue by facinick** [storybookjs/storybook#15130]
my project structure looks like:

src/events                              (project 1)
src/events_embed                 (project 2)
src/playback                          (project 3)

these 3 projects are very slightly overlapping but different. I need separate storybook commands to build storybook for individual projects, however, in main.js I am not able to specify dynamically the blobs like:

_(for src/events project)_
.storybook/main.js =>

```
"stories": [
            "../src/events/**/*.stories.mdx",
            "../src/events/**/*.stories.@(js|jsx|ts|tsx)"
]
```

and static outputs: `../stories/events`

---------------------------------------

_(for src/playback project)_
.storybook/main.js =>

```
"stories": [
            "../src/playback/**/*.stories.mdx",
            "../src/playback/**/*.stories.@(js|jsx|ts|tsx)"
]

```

and static outputs: `../stories/events`

How can I achieve similar setting? I want all these projects to be able to run storybook separately given their src/[project] blobs.

**Comment by shilman** [comment]
You can have a different `.storybook` folder per project and run storybook with the `--config-dir` option to select which one to run/build. https://storybook.js.org/docs/react/api/cli-options

That would run/build three different storybooks, and you could stitch them together using composition if it was useful https://storybook.js.org/docs/react/workflows/storybook-composition#gatsby-focus-wrapper

**Comment by facinick** [comment]
you mean something like this: 

storybook_configs/project1/.storybook/
storybook_configs/project2/.storybook/
storybook_configs/project3/.storybook/

and supply these .storybook paths with build commands?

**Comment by shilman** [comment]
Aha if you want everything but the globs to be the same, you could do something simpler:


```
// main.js
const globs = {
  project1: [...],
  project2: [...],
  project3: [...]
}
module.exports = {
  stories: globs[process.env.PROJECT || 'project1'],
  ..
}
```

Then: 

```
PROJECT=project2 yarn storybook
```

Or:

```
yarn storybook:project2
```

**Comment by facinick** [comment]
@shilman  thankyou this answer was exactly what I was looking for, also if I want to stitch all of these? 

right now my .storybook/main.js looks like this:

```
const globs = {
    playback: [
        "/tests/playback/**/*.stories.mdx",
        "/tests/playback/**/*.stories.@(js|jsx|ts|tsx)"
    ],
    events: [
        "/tests/events/**/*.stories.mdx",
        "/tests/events/**/*.stories.@(js|jsx|ts|tsx)"
    ],
    meetings: [
        "/tests/meetings/**/*.stories.mdx",
        "/tests/meetings/**/*.stories.@(js|jsx|ts|tsx)"
    ],
    events_embed: [
        "/tests/events_embed/**/*.stories.mdx",
        "/tests/events_embed/**/*.stories.@(js|jsx|ts|tsx)"
    ],
    meetings_embed: [
        "/tests/meetings_embed/**/*.stories.mdx",
        "/tests/meetings_embed/**/*.stories.@(js|jsx|ts|tsx)"
    ],
}


module.exports = (options) => {

    return {
        "stories": globs[process.env.PROJECT || 'playback'],
        "addons": [
            "@storybook/addon-links",
            "@storybook/addon-essentials"
        ]
    }

}
```

acc to the composition docs, where will this code go:

 ```
refs: {
    react: {
      title: 'playback',
      url: 'http://localhost:7007',
    },
    events: {
      title: 'Angular',
      url: 'http://localhost:7008',
    },
  },
```

asin, should I first start some of these projects on different ports and list these here?
