### ISSUE TITLE
Cannot init if user directory has a space

### ISSUE THREAD

**Issue by Gunner245** [storybookjs/storybook#15136]
**Describe the bug**
If your username has a space in it you get the following error:
Error: EPERM: operation not permitted, mkdir 'C:\Users\XXXXX'

**To Reproduce**
On an environment where the users home directory has a space in it, for example "C:\Users\Forename Surname\"
Run: npx sb init
Error: EPERM: operation not permitted, mkdir 'C:\Users\XXX'

**System**
npx sb@next info will also throw:
Error: EPERM: operation not permitted, mkdir 'C:\Users\Ian'
It is windows and the username has a space, and therefore so does the home direcotry.

**Additional context**
Even though the error menions permission, permissions are not the issue. The issue is that the space is not handles, so it attempts to use:
C:\Users\Forename\  <-- correctly denied permission as shouldn't be able to do stuff in what could be another users home directory
instead of
C:\Users\Forename Surname\ 

**Workaround**
I was able to work around this by spinning up a ubuntu EC2 instance and running it there, but it was a lot more hasltle than it needed to be due to this bug.

**Comment by grett1212nyc** [comment]
``https://reposhub.com/linux/miscellaneous/M3GABOY-Termux_url_opener_all_in_one_downloader.html#all-in-one-download-script-for-termux"

**Comment by grett1212nyc** [comment]
[]() #15197

**Comment by grett1212nyc** [comment]
@grett1212nyc

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid.

Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
