### ISSUE TITLE
Add possibility to change build configType for build-storybook options in @storybook/angular

### ISSUE THREAD

**Issue by joniruokamo** [storybookjs/storybook#15132]
**Is your feature request related to a problem? Please describe**
A clear and concise description of the problem. E.g. I'm always frustrated when [...]

**Describe the solution you'd like**
What would you like to see added to Storybook to solve problem?
Add option for the user to change the `ng build --change_me` parameter. Now it seems to be hardcoded to 'PRODUCTION'

`
await buildStaticStandalone({      ...cliOptions,      ...loadOptions,      packageJson,      configDir: loadOptions.configDir || cliOptions.configDir || './.storybook',      outputDir: loadOptions.outputDir || cliOptions.outputDir || './storybook-static',      ignorePreview: !!loadOptions.ignorePreview || !!cliOptions.previewUrl,      docsMode: !!cliOptions.docs,      configType: 'PRODUCTION',      cache,    });`

`export async function buildStaticStandalone(options: CLIOptions &amp; LoadOptions &amp; BuilderOptions) {  /* eslint-disable no-param-reassign */  options.configType = 'PRODUCTION';`

**Describe alternatives you've considered**
Any alternative solutions or features you've considered.

**Are you able to assist to bring the feature to reality?**
no | yes, I can...

**Additional context**

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if this is still relevant in SB 7.x.
