### ISSUE TITLE
undefined is not an object when setting an optional arg to undefined via controls

### ISSUE THREAD

**Issue by jasperdunn** [storybookjs/storybook#15150]
**Describe the bug**
Occurs when setting an arg to undefined for optional props.
![Screen Shot 2021-06-06 at 9 28 51 am](https://user-images.githubusercontent.com/26566353/120907992-a8481100-c6a9-11eb-96c0-53ca7694afdd.JPG)

**To Reproduce**
I am using styled-components and importing my color from an external file.
Varient can be undefined | "success" | "danger" etc.
```
${({ variant }) =>
    variant &&
    css`
      background-color: ${theme.color[variant].light};
      color: ${theme.color[variant].dark};
      `};
```

  System:
    OS: macOS 11.4
    CPU: (8) x64 Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz
  Binaries:
    Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.17.0/bin/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm
  Browsers:
    Chrome: 91.0.4472.77
    Firefox: 88.0.1
    Safari: 14.1.1
  npmPackages:
    @storybook/addon-a11y: ^6.2.8 => 6.2.8 
    @storybook/addon-essentials: ^6.2.8 => 6.2.8 
    @storybook/addon-links: ^6.2.8 => 6.2.8 
    @storybook/addons: ^6.2.8 => 6.2.8 
    @storybook/node-logger: ^6.2.8 => 6.2.8 
    @storybook/preset-create-react-app: ^3.1.7 => 3.1.7 
    @storybook/react: ^6.2.8 => 6.2.8

**Comment by shilman** [comment]
Try upgrading to the latest prerelease:

```
npx sb@next upgrade --prerelease
```

Does that fix it?

**Comment by jasperdunn** [comment]
> Try upgrading to the latest prerelease:
> 
> ```
> npx sb@next upgrade --prerelease
> ```
> 
> Does that fix it?

Forgot to mention. . . I did try that already, thanks for your help.

**Comment by shilman** [comment]
Gotcha. In that case, can you please create a reproduction by running `npx sb@next repro`, following the instructions, and linking it in your issue description? We prioritize issues with reproductions over those without. Thank you! 🙏
