### ISSUE TITLE
Using storybook as module federation host is not possible

### ISSUE THREAD

**Issue by kirill-konshin** [storybookjs/storybook#15177]
**Describe the bug**

If I add Module Federation plugin to webpack config, the storybook breaks with error: `Shared module is not available for eager consumption: webpack/sharing/consume/default/react/react`.

![image](https://user-images.githubusercontent.com/1530410/121264424-f3aa1d00-c86b-11eb-9e93-e61b0b9e6211.png)

This happens when there's no `import('./bootstrap')` in entry point, see webpack docs: https://webpack.js.org/concepts/module-federation/#troubleshooting

**To Reproduce**

Run

```bash
$ yarn add webpack @storybook/builder-webpack5 -D
```

Add following code to `.storybook/main.js`:

```js
const { ModuleFederationPlugin } = require("webpack").container;

module.exports = {
  stories: ["../src/**/*.stories.js"],
  addons: [
    "@storybook/addon-actions",
    "@storybook/addon-links"
  ],
  core: {
    builder: "webpack5"
  },
  webpackFinal: async (config) => {
    config.plugins.push(
      new ModuleFederationPlugin({
        name: "ringcentral_whiteboard_storybook",
        shared: {
          react: {
            import: "react", // the "react" package will be used a provided and fallback module
            shareKey: "react", // under this name the shared module will be placed in the share scope
            shareScope: "default", // share scope with this name will be used
            singleton: true // only a single version of the shared module is allowed},
          },
          "react-dom": { singleton: true }
        }
      })
    );
    return config;
  }
};
```

Here's the codesandbox: https://codesandbox.io/s/storybook-module-federation-5v2n3

**Comment by kirill-konshin** [comment]
Quick tip: setting `eager: true` for both shared dependencies solves the problem, but it's not recommended.

**Comment by ron0115** [comment]
The same problem, how to solve it? anyone give me the suggestions ?

**Comment by PIMBA** [comment]
The same problem, any suggestions?

**Comment by LeoRosse** [comment]
Same for me... any suggestions?

**Comment by richardklotz** [comment]
Not Ideal, but I got around it for now by adding react and react-dom to webpack externals, then loaded them globally in preview-head.html

**Comment by robdonn** [comment]
There is now a library on NPM for enabling module federation for Storybook. The GitHub repo has examples for using Storybook as either a host or a remote.

https://github.com/robdonn/storybook-module-federation

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
