### ISSUE TITLE
Core: Disable sidebar and don't load refs when `singleStory=true`

### ISSUE THREAD

**Issue by ghengeveld** [storybookjs/storybook#15171]
Passing the `singleStory=true` param will [load only a single story](https://5a375b97f4b14f0020b0cda3-wumfmsegja.chromatic.com/?path=/story/addons-a11y-basebutton--label&singleStory=true) in Storybook 6.3+. 

As demonstrated in the above link, any refs (external Storybooks) will still be loaded and be visible in the UI. That's wasteful and against the goal of this flag. Since that means the sidebar will be mostly empty, we should disable/hide the sidebar altogether.

**Comment by shilman** [comment]
Good golly!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.3.0-rc.3 containing PR #15201 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
