### ISSUE TITLE
Core: Set `enableShortcuts` using query param

### ISSUE THREAD

**Issue by ghengeveld** [storybookjs/storybook#15172]
To forcefully disable (or enable) keyboard shortcuts for purposes of embedding, Storybook should accept a `enableShortcuts` query param which overrides the existing `enableShortcuts` config setting.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1199622255231357/1200440908172435) by [Unito](https://www.unito.io)

**Comment by shilman** [comment]
Jiminy cricket!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.3.0-rc.2 containing PR #15192 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
