### ISSUE TITLE
Core-common: babel-plugin-polyfill-corejs3 polluting global scope

### ISSUE THREAD

**Issue by jbadan** [storybookjs/storybook#15176]
**Describe the bug**

By using `usage-global` method of babel-plugin-polyfill-corejs3, storybook is now globally polyfilling from corejs. As a library maintainer, this is problematic as it hides ie11 errors that we need to polyfill in our own code. Could this be changed to `usage-pure` to prevent this?

https://github.com/storybookjs/storybook/blob/next/lib/core-common/src/utils/babel.ts#L37
https://github.com/babel/babel-polyfills/blob/main/docs/usage.md#method

**To Reproduce**
N/A

**System**
Please paste the results of `npx sb@next info` here.
N/A

**Additional context**
N/A

**Comment by shilman** [comment]
Thanks for raising this @jbadan! Short answer: probably. We are in transition about how we implement polyfills, so will discuss with @ndelangen as we push that forward. I'll keep you posted.

**Comment by jbadan** [comment]
@shilman Thanks!

**Comment by shilman** [comment]
@ndelangen wants to follow up! 🙌

**Comment by ndelangen** [comment]
Polyfills (including the need for this package) are completely removed in 7.0 beta
