### ISSUE TITLE
Avoid reinitializing component when resizing pass the 600px width threshold

### ISSUE THREAD

**Issue by pardoman** [storybookjs/storybook#15188]
**Is your feature request related to a problem? Please describe**
When using Storybook in fullscreen mode, with a screen with above 600px, when I resize the screen to less than 600px, the entire Storybook seems to re-initialize, along with the component I'm the fullscreen view. 

The frustrating part is that it resets all the knobs I've manually changed for the story.
It's also frustrating testing components that have some media-query logic built into them.

**Describe the solution you'd like**
I would like for Storybook to not re-initialize when viewport width changes size across the 600px threshold when I'm viewing a story in fullscreen mode. 

Ideally, not re-initialize even outside of fullscreen, but personally I don't need that case to be supported.

**Describe alternatives you've considered**
Preserving Kobs state would be an alternative. However, the visual discontinuity caused by the re-initialization doesn't help, see gifs below.

**Are you able to assist to bring the feature to reality?**
I might be able to assist.

**Additional context**

### Storybook resizing in default mode
![storybook-regular](https://user-images.githubusercontent.com/2985436/121416172-590a1680-c91d-11eb-96a3-26e6fb6970c3.gif)

### Storybook resizing in fullscreen
![storybook-fullscreen](https://user-images.githubusercontent.com/2985436/121416262-750db800-c91d-11eb-9b53-3ca62bdc5ced.gif)

Thank you

**Comment by yannbf** [comment]
Hey @pardoman  I'm not 100% familiar with the specific code for this but I think there are two different components, one to handle desktop and one to handle mobile, and when switching between them it ends up rendering a new iframe instance. I might be wrong though.

Could you please tell me the use cases for using the dev tools? In Storybook 6.3(currently in RC) there is a new addon added to essentials which provides an easy way to  inspect spacings of elements. It also includes addon viewport which provides you a way to emulate responsiveness. Also, knobs are the old way of handling props for components, [addon controls](https://storybook.js.org/docs/ember/essentials/controls/) is the recommended way nowadays, and might actually keep the state of the component while resizing, as the props are saved in the url while you change them. Maybe consider check that as well?

I understand that frustration.. And one way of dealing with stories and easily using the dev tools without that resize restriction is to "eject" your story (click on the share button on top right) and this will open the canvas in a separate window, and there you can focus solely on that component without any distraction from Storybook.

I hope these tips help!

**Comment by pardoman** [comment]
Hey @yannbf thanks for all that info. Thanks for your response. 

I wasn't aware of the viewport addon, nor addon controls controls in general, so I'll be sure to look into those, next.

I'll post back again after I evaluate them. Thank you.

**Comment by pardoman** [comment]
Hey @yannbf , I added `"@storybook/addon-viewport": "^6.2.9"` to my storybook and it's working great for my needs.

I still need to look deeper into `addon controls`, but as far as the issue I reported here, I think we can close it. @shilman 

Thank you.
