### ISSUE TITLE
Stories found according to CLI but no stories found according to UI

### ISSUE THREAD

**Issue by shertu** [storybookjs/storybook#15180]
**Describe the bug**
The UI indicates no stories were found despite the `start-storybook` CLI command and web console indicating that at least one story was found.

![image](https://user-images.githubusercontent.com/7973587/121308315-40f9bd80-c944-11eb-9cbe-827ecfb96541.png)

![image](https://user-images.githubusercontent.com/7973587/121309180-3a1f7a80-c945-11eb-8e63-0a9a02185268.png)

**System**
```
Environment Info:

  System:
    OS: Windows 10 10.0.19043
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
  Binaries:
    Node: 16.0.0 - C:\Program Files\nodejs\node.EXE
    npm: 7.10.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.964.0), Chromium (91.0.864.41)
  npmPackages:
    @storybook/addon-actions: ^6.1.10 => 6.2.9
    @storybook/addon-essentials: ^6.1.10 => 6.2.9
    @storybook/addon-links: ^6.1.10 => 6.2.9
    @storybook/addon-postcss: ^2.0.0 => 2.0.0
    @storybook/react: ^6.2.9 => 6.2.9
```

**Additional context**
This was from an attempt to integrate Storybook into a Next.js application.

**Comment by shilman** [comment]
do you see stories in the left-hand navigation panel?

**Comment by shertu** [comment]
> do you see stories in the left-hand navigation panel?

No. 😢

**Comment by JBallin** [comment]
Are you defining a [default export](https://storybook.js.org/docs/react/writing-stories/introduction#default-export) in your story?

I spent a while with this same issue until I realized it is required. I think the docs should either clarify this or the title should be inferred from the file name (e.g. `MyComponent.stories.js` ➡️  `MyComponent`).

**Comment by shilman** [comment]
@shertu Can you please create a reproduction by running `npx sb@next repro`, following the instructions, and linking it in your issue description? We prioritize issues with reproductions over those without. Thank you! 🙏

**Comment by shertu** [comment]
> Are you defining a [default export](https://storybook.js.org/docs/react/writing-stories/introduction#default-export) in your story?
> 
> I spent a while with this same issue until I realized it is required. I think the docs should either clarify this or the `title` should be inferred from the file name (e.g. `MyComponent.stories.js` ➡️ `MyComponent`), and/or show a warning/error when `title` is undefined.

This was the issue. Thank you for you assistance.

![image](https://user-images.githubusercontent.com/7973587/121470996-546b5e00-ca02-11eb-9167-aeebba47e609.png)

**Comment by JBallin** [comment]
@shilman do you know if the issue I mentioned is known? If not - would you like me to open a new issue with a repro?
