### ISSUE TITLE
add tsx support for <Canvas />

### ISSUE THREAD

**Issue by jantimon** [storybookjs/storybook#15190]
Canvas supports `mdxSource` but does not allow to set a language and always fallsback to `jsx`.
Therefore it is not possible to set it to `tsx`.

**Describe the solution you'd like**
Right now Canvas has only the `mdxSource` prop: 

https://github.com/storybookjs/storybook/blob/0404fa95601dca508812c34db6bc03292461f0e9/addons/docs/src/blocks/Canvas.tsx#L17

This value is handed over to `getSourceProps` without specifying a language:

https://github.com/storybookjs/storybook/blob/0404fa95601dca508812c34db6bc03292461f0e9/addons/docs/src/blocks/Canvas.tsx#L33

`getSourceProps` will use `jsx` as default:

https://github.com/storybookjs/storybook/blob/0404fa95601dca508812c34db6bc03292461f0e9/addons/docs/src/blocks/Source.tsx#L150

It would be cool if `mdxSource` would be an object and allows passing over `SourceProps` or if we could add an optional `mdxSourceLanguage` property

**Are you able to assist to bring the feature to reality?**
yes

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if this is still relevant in SB 7.x.
