### ISSUE TITLE
Inconsistent state of url query params

### ISSUE THREAD

**Issue by radk0s** [storybookjs/storybook#15193]
**Describe the bug**
Switching themes/locale in storybook preview toolbar adds corresponding query params to url. However selecting new story from sidebar removes all of them from url despite of selections in toolbar stays the same. Similar thing happens when you change values in controls add-on - instead of adding query param to existing ones it replaces all of them. As result when you copy link/reload page state of theme/locale is gone.

**To Reproduce**
1.  Go to official [Storybook](https://next--storybookjs.netlify.app/official-storybook/)
2.  Select different theme/locale from preview toolbar (it adds query params like `&globals=theme:dark;locale:es`)
3. Select other story from sidebar / Change some value in controls add-on
4. Url query do not have `&globals=theme:dark;locale:es`

**Comment by shilman** [comment]
Yowza!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.3.0-rc.5 containing PR #15213 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
