### ISSUE TITLE
Storybook only accept an `integer` as port, causing Unix sockets to not work.

### ISSUE THREAD

**Issue by davesnx** [storybookjs/storybook#15202]
**Describe the bug**
The start-storybook CLI and the storybook config only accepts integers as port values. This causes a type-checking problem here: https://github.com/storybookjs/storybook/blob/next/lib/core-server/src/dev-server.ts#L52-L54 but in reality disables a use-case that I'm interested in using: which makes the server listen to a Unix socket instead of a port.

**To Reproduce**
The steps to reproduce are:
```npx start-storybook -p './sock'```

**System**
Have nothing to do with the system as far as I know.

**Additional context**
It's useful to use unix sockets while working thought SSH sessions

Thanks

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if this is still relevant in SB 7.x.

**Comment by davesnx** [comment]
That's still an issue: https://github.com/storybookjs/storybook/blob/next/code/lib/core-server/src/dev-server.ts#L66 
https://github.com/storybookjs/storybook/blob/next/code/lib/core-server/src/utils/server-address.ts#L6-L12
