### ISSUE TITLE
Uncaught Error: Singleton client API not yet initialized, cannot call addParameters after upgraded from 6.3.0-beta.16 to 17

### ISSUE THREAD

**Issue by litan1106** [storybookjs/storybook#15210]
```js
client_api.js:50 Uncaught Error: Singleton client API not yet initialized, cannot call addParameters
    at addParameters (client_api.js:50)
    at vite-app.js:75
    at Array.forEach (<anonymous>)
    at vite-app.js:61
    at Array.forEach (<anonymous>)
    at vite-app.js:60
```

**Comment by litan1106** [comment]
fixed with 6.3.0-rc.4 and vite builder 0.0.8

**Comment by sadir** [comment]
@litan1106 I've just upgraded from `6.2.9` to `6.3.0` and run into this error. What was the issue you fixed? Not seeing anything [here](https://github.com/storybookjs/storybook/compare/v6.3.0-rc.3...v6.3.0-rc.4) that jumps out at me.

We have a custom webpack config so I assume that's got something to do with it?

**Comment by bufordeeds** [comment]
My team is running into the same issue after upgrading today.

**Comment by husayt** [comment]
I am seeing the same issue as well after building with vite-builder and vue3 project.

**Comment by shilman** [comment]
Please file Vite-related issues in https://github.com/eirslett/storybook-builder-vite/

Thank you! 🙏

**Comment by sadir** [comment]
Ours isn't vite related @shilman - can you set my expectations here on what will happen next please?

**Comment by sadir** [comment]
I can post some of our config if that would help? Don't have a repo to share with you.

**Comment by sadir** [comment]
Here's the error we are getting

```
Uncaught Error: Singleton client API not yet initialized, cannot call addParameters
    at addParameters (client_api.js:105)
    at eval (config.js-generated-other-entry.js:41)
    at Array.forEach (<anonymous>)
    at eval (config.js-generated-other-entry.js:15)
    at Module../node_modules/@storybook/addon-docs/dist/esm/frameworks/common/config.js-generated-other-entry.js (main.iframe.bundle.js:2523)
    at __webpack_require__ (main.iframe.bundle.js:836)
    at fn (main.iframe.bundle.js:130)
    at eval (client.js:5)
    at Object.0 (main.iframe.bundle.js:44637)
    at __webpack_require__ (main.iframe.bundle.js:836)
```

**Comment by shilman** [comment]
@sadir Can you please create a reproduction by running `npx sb@next repro`, following the instructions, and linking it in your issue description? We prioritize issues with reproductions over those without. Thank you! 🙏

**Comment by jokull** [comment]
Same here when upgrading to 6.3. Removing all addons makes it work — except the postcss addon, that doesn't trigger this error. The addons I've tried adding that trigger this are links, essentials and docs.

**Comment by sadir** [comment]
Upgrading to 6.3.2 seems to have fixed this issue for us, whatever it was!

**Comment by martinsuba** [comment]
I'm still getting the same error after upgrading from 6.1.11. to 6.3.2. I've also tried upgrading to 6.4.0-alpha.12 (with webpack 5) and the result is same, except now I'm also getting this in console:
`99% done plugins webpack-hot-middlewarewebpack built preview dbb930f7764ba3c321a1 in 1409ms`

**Comment by jaakerisalu** [comment]
Hey I also ran into this issue after upgrading all packages to 6.3.2. This seems to be the same problem as #10887, so I ran

```
> npm ls | grep client-api
│ ├─┬ @storybook/client-api@6.3.2
│ │ ├─┬ @storybook/client-api@6.3.2
│ │ ├─┬ @storybook/client-api@6.3.2
│ │ │ ├─┬ @storybook/client-api@6.3.2
│ │ ├─┬ @storybook/client-api@6.3.2
│ │ ├─┬ @storybook/client-api@6.3.2
│ ├── @storybook/client-api@6.3.2 deduped
│ │ ├─┬ @storybook/client-api@6.3.2

>npm dedupe
removed 27 packages and audited 3738 packages in 7.686s

>
npm ls | grep client-api
│ ├─┬ @storybook/client-api@6.3.2
│ │ ├── @storybook/client-api@6.3.2 deduped
│ │ ├── @storybook/client-api@6.3.2 deduped
│ │ │ ├── @storybook/client-api@6.3.2 deduped
│ │ ├── @storybook/client-api@6.3.2 deduped
│ │ ├── @storybook/client-api@6.3.2 deduped
│ ├── @storybook/client-api@6.3.2 deduped
│ │ ├── @storybook/client-api@6.3.2 deduped
```

And the error is gone (for now).

**Comment by martinsuba** [comment]
Thanks @jaakerisalu but it didn't help my case. I've seen issue #10887 but that didn't help me either.

**Comment by andre-brdoch** [comment]
I encountered this issue (again after several times in the past) after updating to v6.4.1. Removing any webpack modifications fixed the issue. Not sure what caused it to begin with. However, this also made me realize that most of our webpack modifications were unnecessary, since nowadays storybook has many things covered via presets

**Comment by blowsie** [comment]
Im seeing this issue with 
`^6.5.0-alpha.19`

Cleaned node_modules and lock file
