### ISSUE TITLE
@storybook/addon-storyshots-puppeteer@6.3.0-rc.4 requires a peer of @storybook/addon-storyshots@6.3.0-beta.17 

### ISSUE THREAD

**Issue by erikt9** [storybookjs/storybook#15211]
https://github.com/storybookjs/storybook/blob/a2752c20b83025da7b57ecb691ebeea11ab2d247/addons/storyshots/storyshots-puppeteer/package.json#L56

Getting the npm warning:
`npm WARN @storybook/addon-storyshots-puppeteer@6.3.0-rc.4 requires a peer of @storybook/addon-storyshots@6.3.0-beta.17 but none is installed. You must install peer dependencies yourself.`

When installing any of the rc releases.  The line referenced above looks like it should be updated.

Relevant package.json:

```
"@storybook/addon-storyshots": "^6.3.0-rc.0",
"@storybook/addon-storyshots-puppeteer": "^6.3.0-rc.0",
```

**Comment by shilman** [comment]
Yowza!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.3.0-rc.9 containing PR #15277 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by erikt9** [comment]
@shilman The fix only worked for one release.  rc.10 brings the issue back: `npm WARN @storybook/addon-storyshots-puppeteer@6.3.0-rc.10 requires a peer of @storybook/addon-storyshots@6.3.0-rc.8 but none is installed. You must install peer dependencies yourself.`

Whatever you are using to doing to update the other dependencies of `storyshots-puppeteer`  is not getting applied every release (e.g., the `@storybook/node-logger` in the storyshots-puppeteer package.json looks to be getting updated every release, but the `addon-storyshots` dependency stopped getting updated when switching from beta to rc).

**Comment by shilman** [comment]
@erikt9 oops, thanks for letting me know. it looks like i broke the release script at some point. i'll fix it and hopefully put this to bed!

**Comment by shilman** [comment]
Ermahgerd!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.3.0-rc.11 containing PR #15288 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
