### ISSUE TITLE
The Addons section in the readme has several broken links

### ISSUE THREAD

**Issue by corymharper** [storybookjs/storybook#15214]
**Describe the bug**
The [addons](https://github.com/storybookjs/storybook#addons) section of the readme seems to link to several pages that don't exist. Specifically:

[cssresources](https://github.com/storybookjs/storybook/blob/next/addons/cssresources)
[design assets](https://github.com/storybookjs/storybook/blob/next/addons/design-assets)
[events](https://github.com/storybookjs/storybook/blob/next/addons/events)
[google-analytics](https://github.com/storybookjs/storybook/blob/next/addons/google-analytics)
[graphql](https://github.com/storybookjs/storybook/blob/next/addons/graphql)
[query params](https://github.com/storybookjs/storybook/blob/next/addons/query-params)

These aren't marked as deprecated, and don't have any special indications about being under construction, but the links all lead to 404 pages.

**To Reproduce**
Click any of the above links, or head to the addons section of the readme and do the same.

**Additional context**
Ran across this while looking for documentation on the query params addon.

**Comment by jonniebigodes** [comment]
@corymharper thanks for bringing this to our attention. We're aware of it and soon a pull request will be up to address this. This came from #14831. 

Stay safe

**Comment by MathurUtkarsh** [comment]
I want to fix this issue . Please Assign it to me.

**Comment by jonniebigodes** [comment]
@corymharper I've just pushed a pr to address this. 

@MathurUtkarsh I saw your pull request and I left a note why it's closed.

Stay safe both of you
