### ISSUE TITLE
Running Storybook with Webpack 5 and swc-loader results with an error

### ISSUE THREAD

**Issue by dudiharush** [storybookjs/storybook#15224]
**Describe the bug**
I use Storybook for a React application, and it works with babel-loader, but not with swc-loader

**To Reproduce**
in a working Storybook project, change babel-loader to swc-loader in main.js webpackFinal function's config and run Storybook

**System**
 @storybook/builder-webpack5: "6.3.0-rc.4",
 @storybook/manager-webpack5: "6.3.0-rc.4",
 @storybook/react: "6.3.0-beta.4",

**Additional context**
I changed: loader: require.resolve('babel-loader') to loader: require.resolve('swc-loader')
ran: npm run storybook, and got this error:
modulesthread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 0'

**Comment by hamanovich** [comment]
You can try to add parseMap option:
```
{
          test: [/.js$|.ts$/],
          exclude: /node_modules/,
          use: {
            loader: 'swc-loader',
            options: {
              parseMap: true,
            },
          },
        },
```
It runs with no errors but still doesn't work. I see Cannot GET /

**Comment by Karibash** [comment]
It seems that an error occurs when parsing color-convert.
I was able to build with swc by commenting out the following part.
https://github.com/storybookjs/storybook/blob/ca8b0f3ef135ba0b65f313b81d3a9baa7d306865/lib/core-common/src/utils/es6Transpiler.ts#L20

**Comment by Karibash** [comment]
The build passed successfully when the sourceMaps were set in addition to the parseMap option.

```js
{
  test: /\.(jsx?|tsx?)$/,
  use: {
    loader: 'swc-loader',
    options: {
      parseMap: true,
      sourceMaps: true,
    },
  },
},
```

Also, we have created a storybook addon to make it easier to build with swc.
https://github.com/Karibash/storybook-addon-swc
