### ISSUE TITLE
RenderException on Angular

### ISSUE THREAD

**Issue by MuizMahdi** [storybookjs/storybook#15248]
**Describe the bug**
Components do not render on canvas.

**System**
Environment Info:

  System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz   
  Binaries:
    Node: 14.15.4 - C:\Program Files\nodejs\node.EXE       
    npm: 6.14.10 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1.0), Chromium (91.0.864.41)   
  npmPackages:
    @storybook/addon-actions: ^6.3.0-rc.7 => 6.3.0-rc.7    
    @storybook/addon-essentials: ^6.3.0-rc.7 => 6.3.0-rc.7 
    @storybook/addon-links: ^6.3.0-rc.7 => 6.3.0-rc.7      
    @storybook/angular: ^6.3.0-rc.7 => 6.3.0-rc.7 

**Screenshot**
![image](https://user-images.githubusercontent.com/28702994/122060564-02557e80-cdee-11eb-8838-32ad7342d85e.png)

**Log**
`parse@http://localhost:6006/vendors~main.iframe.bundle.js:161533:23
./node_modules/prettier/parser-html.js/</</An</t.parse@http://localhost:6006/vendors~main.iframe.bundle.js:161557:50
Mn@http://localhost:6006/vendors~main.iframe.bundle.js:161599:22
Un@http://localhost:6006/vendors~main.iframe.bundle.js:161788:17
parse@http://localhost:6006/vendors~main.iframe.bundle.js:161834:16
parse@http://localhost:6006/vendors~main.iframe.bundle.js:161899:122705
ts@http://localhost:6006/vendors~main.iframe.bundle.js:161899:138940
us@http://localhost:6006/vendors~main.iframe.bundle.js:161899:141899
eN/<@http://localhost:6006/vendors~main.iframe.bundle.js:161929:42079
format@http://localhost:6006/vendors~main.iframe.bundle.js:161929:42191
prettyUp@http://localhost:6006/vendors~main.iframe.bundle.js:87263:69
sourceDecorator@http://localhost:6006/vendors~main.iframe.bundle.js:87295:98
hookify/<@http://localhost:6006/vendors~main.iframe.bundle.js:99488:21
decorateStory/returnDecorators</<@http://localhost:6006/vendors~main.iframe.bundle.js:102277:39
decorateStory/returnDecorators</</decoratedStory<@http://localhost:6006/vendors~main.iframe.bundle.js:102280:20
wrapper@http://localhost:6006/vendors~main.iframe.bundle.js:97054:12
decorator/<@http://localhost:6006/vendors~main.iframe.bundle.js:99984:14
makeDecorator/<@http://localhost:6006/vendors~main.iframe.bundle.js:99998:26
hookify/<@http://localhost:6006/vendors~main.iframe.bundle.js:99488:21
decorateStory/returnDecorators</<@http://localhost:6006/vendors~main.iframe.bundle.js:102277:39
decorateStory/returnDecorators</</decoratedStory<@http://localhost:6006/vendors~main.iframe.bundle.js:102280:20
wrapper@http://localhost:6006/vendors~main.iframe.bundle.js:83091:12
decorator/<@http://localhost:6006/vendors~main.iframe.bundle.js:99984:14
makeDecorator/<@http://localhost:6006/vendors~main.iframe.bundle.js:99998:26
hookify/<@http://localhost:6006/vendors~main.iframe.bundle.js:99488:21
decorateStory/returnDecorators</<@http://localhost:6006/vendors~main.iframe.bundle.js:102277:39
decorateStory/returnDecorators</</decoratedStory<@http://localhost:6006/vendors~main.iframe.bundle.js:102280:20
withGrid@http://localhost:6006/vendors~main.iframe.bundle.js:83935:10
hookify/<@http://localhost:6006/vendors~main.iframe.bundle.js:99488:21
decorateStory/returnDecorators</<@http://localhost:6006/vendors~main.iframe.bundle.js:102277:39
decorateStory/returnDecorators</</decoratedStory<@http://localhost:6006/vendors~main.iframe.bundle.js:102280:20
withBackground@http://localhost:6006/vendors~main.iframe.bundle.js:83849:10
hookify/<@http://localhost:6006/vendors~main.iframe.bundle.js:99488:21
decorateStory/returnDecorators</<@http://localhost:6006/vendors~main.iframe.bundle.js:102277:39
decorateStory/returnDecorators</</decoratedStory<@http://localhost:6006/vendors~main.iframe.bundle.js:102280:20
withMeasure@http://localhost:6006/vendors~main.iframe.bundle.js:99233:10
hookify/<@http://localhost:6006/vendors~main.iframe.bundle.js:99488:21
decorateStory/returnDecorators</<@http://localhost:6006/vendors~main.iframe.bundle.js:102277:39
decorateStory/returnDecorators</</decoratedStory<@http://localhost:6006/vendors~main.iframe.bundle.js:102280:20
withOutline@http://localhost:6006/vendors~main.iframe.bundle.js:205630:10
hookify/<@http://localhost:6006/vendors~main.iframe.bundle.js:99488:21
decorateStory/returnDecorators</<@http://localhost:6006/vendors~main.iframe.bundle.js:102277:39
applyHooks/</<@http://localhost:6006/vendors~main.iframe.bundle.js:99515:29
unboundStoryFn@http://localhost:6006/vendors~main.iframe.bundle.js:106227:30
storyFn@http://localhost:6006/vendors~main.iframe.bundle.js:124424:26
renderMain/</<@http://localhost:6006/vendors~main.iframe.bundle.js:102524:45
step@http://localhost:6006/vendors~main.iframe.bundle.js:102497:23
verb/<@http://localhost:6006/vendors~main.iframe.bundle.js:102478:53
fulfilled@http://localhost:6006/vendors~main.iframe.bundle.js:102469:58
./node_modules/zone.js/dist/zone.js/</</ZoneDelegate.prototype.invoke@http://localhost:6006/vendors~main.iframe.bundle.js:212168:30
./node_modules/zone.js/dist/zone.js/</</Zone.prototype.run@http://localhost:6006/vendors~main.iframe.bundle.js:211925:47
scheduleResolveOrReject/<@http://localhost:6006/vendors~main.iframe.bundle.js:212673:38
./node_modules/zone.js/dist/zone.js/</</ZoneDelegate.prototype.invokeTask@http://localhost:6006/vendors~main.iframe.bundle.js:212203:35
./node_modules/zone.js/dist/zone.js/</</Zone.prototype.runTask@http://localhost:6006/vendors~main.iframe.bundle.js:211970:51
drainMicroTaskQueue@http://localhost:6006/vendors~main.iframe.bundle.js:212383:39
./node_modules/zone.js/dist/zone.js/</</ZoneTask.invokeTask@http://localhost:6006/vendors~main.iframe.bundle.js:212289:25
invokeTask@http://localhost:6006/vendors~main.iframe.bundle.js:213453:18
globalZoneAwareCallback@http://localhost:6006/vendors~main.iframe.bundle.js:213479:31
EventListener.handleEvent*customScheduleGlobal@http://localhost:6006/vendors~main.iframe.bundle.js:213605:47
./node_modules/zone.js/dist/zone.js/</</ZoneDelegate.prototype.scheduleTask@http://localhost:6006/vendors~main.iframe.bundle.js:212189:30
./node_modules/zone.js/dist/zone.js/</</Zone.prototype.scheduleTask@http://localhost:6006/vendors~main.iframe.bundle.js:212013:47
./node_modules/zone.js/dist/zone.js/</</Zone.prototype.scheduleEventTask@http://localhost:6006/vendors~main.iframe.bundle.js:212039:29
makeAddListener/<@http://localhost:6006/vendors~main.iframe.bundle.js:213762:37
PostmsgTransport@http://localhost:6006/vendors~main.iframe.bundle.js:103528:18
createChannel@http://localhost:6006/vendors~main.iframe.bundle.js:103779:19
getOrCreateChannel@http://localhost:6006/vendors~main.iframe.bundle.js:125303:103
start@http://localhost:6006/vendors~main.iframe.bundle.js:125346:17
./node_modules/@storybook/angular/dist/ts3.9/client/preview/index.js@http://localhost:6006/vendors~main.iframe.bundle.js:102430:20
__webpack_require__@http://localhost:6006/runtime~main.iframe.bundle.js:854:30
fn@http://localhost:6006/runtime~main.iframe.bundle.js:151:20
./node_modules/@storybook/angular/dist/ts3.9/client/index.js/<@http://localhost:6006/vendors~main.iframe.bundle.js:100443:36
./node_modules/@storybook/angular/dist/ts3.9/client/index.js@http://localhost:6006/vendors~main.iframe.bundle.js:100460:30
__webpack_require__@http://localhost:6006/runtime~main.iframe.bundle.js:854:30
fn@http://localhost:6006/runtime~main.iframe.bundle.js:151:20
./.storybook/storybook-init-framework-entry.js@http://localhost:6006/main.iframe.bundle.js:203:95
__webpack_require__@http://localhost:6006/runtime~main.iframe.bundle.js:854:30
fn@http://localhost:6006/runtime~main.iframe.bundle.js:151:20
0@http://localhost:6006/main.iframe.bundle.js:965:20
__webpack_require__@http://localhost:6006/runtime~main.iframe.bundle.js:854:30
checkDeferredModules@http://localhost:6006/runtime~main.iframe.bundle.js:46:23
webpackJsonpCallback@http://localhost:6006/runtime~main.iframe.bundle.js:33:19
@http://localhost:6006/main.iframe.bundle.js:1:57
index.js:56
    error index.js:56
    renderException StoryRenderer.js:476
    _callee3$ StoryRenderer.js:409
    tryCatch runtime.js:63
    invoke runtime.js:293
    defineIteratorMethods runtime.js:118
    asyncGeneratorStep StoryRenderer.js:18
    _throw StoryRenderer.js:20
    Angular 14
    PostmsgTransport index.js:72
    createChannel index.js:323
    getOrCreateChannel start.js:20
    start start.js:63
    js Angular
    Webpack 14
        __webpack_require__
        fn
        js
        js
        __webpack_require__
        fn
        js
        __webpack_require__
        fn
        0
        __webpack_require__
        checkDeferredModules
        webpackJsonpCallback
        <anonymous>`

**Comment by kroeder** [comment]
@MuizMahdi can you try the latest 6.3.0 release, please?
What angular version do you use 

In my case, I had to add this for Angular 12 in my main.js

```
module.exports = {
    core: {
        builder: "webpack5", // <---- this
    },
    stories: [
         // ...
    ],
    addons: [
         // ...
    ],
};
```

Btw. you can post a well-formatted error log with a tripple-backtick
<code>```</code>
