### ISSUE TITLE
`@storybook/react` forces outdated `react-docgen-typescript`, causes TypeError at runtime

### ISSUE THREAD

**Issue by ctjlewis** [storybookjs/storybook#15251]
**Describe the bug**
I created a Storybook project with TSDX, but it fails on `yarn storybook` because `@storybook/react` forces a version of `react-docgen-typescript` which causes a TypeError (but has since been patched, and totally moved to TS).

I am unable to manually override the version in my own package.json because it is resolved within the package itself, you can see that the resolved `node_modules/` is inside the project's `node_modules/@storybook/react` folder, so it's impossible to ask the package manager to override it.

```
node_modules/@storybook/react/node_modules/react-docgen-typescript/lib/parser.js:475
            var trimmedText = (tag.text || '').trim();
```

You can see in `react-docgen-typescript@2.0.0` how the outputted `parser.js` differs:

```
var trimmedText = ts.displayPartsToString(tag.text).trim()
```

The burden of creating a repo for this complicated of a project is too much for me to bother with it. This package is not up-to-date and it needs to be overridden in the `@storybook/react` package.json manually to use `^2.0.0`, currently bundles with `1.22.0`.

**Comment by ctjlewis** [comment]
May need to be moved to https://github.com/styleguidist/react-docgen-typescript, but it's not under the @storybookjs organization.

I updated to 2.0.0 in a local branch and it seems to break the parsing of the props, such that the `@default` JSDoc doesn't get parsed to a proper `defaultValue` and is instead faultily set as `null`. Presumably this is why it has not been updated - I would advise updating it and fixing the logic as needed.

**Comment by shilman** [comment]
Try upgrading to the latest prerelease:

```
npx sb@next upgrade --prerelease
```

**Comment by shilman** [comment]
closing as duplicate to #15067
