### ISSUE TITLE
6.3.0-beta.0 decorator not updating story

### ISSUE THREAD

**Issue by ktmDeveloper** [storybookjs/storybook#15250]
The decorator is not updating the story after I updated to 6.3.0-beta.0. It was working on version @6.2. I can see that my args for the story has changed, but the story is not updated.

![image](https://user-images.githubusercontent.com/8963447/122083133-71fb4780-cdb5-11eb-8722-09b07fd93888.png)

**Comment by erikt9** [comment]
You should probably try one of the release candidate versions and see if it's fixed there (current is 6.3.0-rc.7).

**Comment by ktmDeveloper** [comment]
Thanks for the response. I tried that rc version, but the story is still not updating.

**Comment by shilman** [comment]
Can you please create a reproduction by running `npx sb@next repro`, following the instructions, and linking it in your issue description? We prioritize issues with reproductions over those without. Thank you! 🙏

**Comment by ktmDeveloper** [comment]
That command gives this error `Invalid command: repro.`.  I ran `npx sb@next info` and this is the result:
```
Environment Info:

  System:
    OS: Windows 10 10.0.19043
    CPU: (16) x64 Intel(R) Core(TM) i7-9800X CPU @ 3.80GHz
  Binaries:
    Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 2.4.1 - C:\Program Files\nodejs\yarn.CMD
    npm: 7.8.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 91.0.4472.106
    Edge: Spartan (44.19041.1023.0), Chromium (91.0.864.48)
  npmPackages:
    @storybook/addon-a11y: ^6.2.9 => 6.2.9
    @storybook/addon-docs: ^6.2.9 => 6.2.9
    @storybook/addon-essentials: ^6.2.9 => 6.2.9
    @storybook/cli: ^6.2.9 => 6.2.9
    @storybook/react: ^6.3.0-beta.0 => 6.3.0-rc.5
```

**Comment by ktmDeveloper** [comment]
@shilman do you have any update on this? Basically, the highlighted behavior from the screenshot below is not happening anymore.

![image](https://user-images.githubusercontent.com/8963447/123613578-672eb280-d7b8-11eb-978f-625416abe0dd.png)

**Comment by shilman** [comment]
@ktmDeveloper nope, I don't have a reproduction

**Comment by ktmDeveloper** [comment]
The following PR fixed it.
https://github.com/storybookjs/storybook/pull/15408
Thanks
