### ISSUE TITLE
Toolbars config regression: should fall back to name when no title is present

### ISSUE THREAD

**Issue by kaelig** [storybookjs/storybook#15259]
**Describe the bug**

I noticed that in recent pre-releases of 6.3, toolbars we defined in `globalTypes` stopped appearing unless they had an icon.

I'd expect toolbars without a `title` (new key in 6.3) to still appear, and to see a console deprecation message telling me to specify the title.

(Regression confirmed with @shilman)

**Comment by shilman** [comment]
Ermahgerd!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-alpha.16 containing PR #17430 that references this issue. Upgrade today to the `@future` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
w00t!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.10-alpha.0 containing PR #17430 that references this issue. Upgrade today to the `@prerelease` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

**Comment by shilman** [comment]
Ta-da!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.10 containing PR #17430 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```
