### ISSUE TITLE
Global styles cannot be added via preview.js with Storybook and Angular v12

### ISSUE THREAD

**Issue by joniruokamo** [storybookjs/storybook#15261]
**Describe the bug**
Global styles cannot be added via preview.js with Storybook and Angular v12

**To Reproduce**
Please create a reproduction by running `npx sb@next repro` and following the instructions. Read our [documentation](https://storybook.js.org/docs/react/contribute/how-to-reproduce) to learn more about creating reproductions.
Paste your repository and deployed reproduction here. We prioritize issues with reproductions over those without.

Create a new LIBRARY repo of Angular (v12) and latest rc build of SB6.3. Try to add external styling from root folder. Styles are not added to iframe. 

**System**
Please paste the results of `npx sb@next info` here.

System:
    OS: macOS 11.2.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 14.15.1 - ~/.nvm/versions/node/v14.15.1/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.1/bin/npm
  Browsers:
    Chrome: 91.0.4472.101
    Firefox: 89.0
    Safari: 14.0.3
  npmPackages:
    @storybook/addon-actions: ^6.3.0-rc.7 => 6.3.0-rc.7
    @storybook/addon-controls: ^6.3.0-rc.7 => 6.3.0-rc.7
    @storybook/addon-docs: ^6.3.0-rc.7 => 6.3.0-rc.7
    @storybook/addon-knobs: ^6.2.9 => 6.2.9
    @storybook/addon-links: ^6.3.0-rc.7 => 6.3.0-rc.7
    @storybook/addon-notes: ^5.3.21 => 5.3.21
    @storybook/addon-postcss: ^2.0.0 => 2.0.0
    @storybook/addons: ^6.3.0-rc.7 => 6.3.0-rc.7
    @storybook/angular: ^6.3.0-rc.7 => 6.3.0-rc.7
    @storybook/builder-webpack5: ^6.3.0-rc.7 => 6.3.0-rc.7
    @storybook/manager-webpack5: ^6.3.0-rc.7 => 6.3.0-rc.7
    @storybook/preset-scss: ^1.0.3 => 1.0.3

**Additional context**

Currently the only way to add global styles to the project is to add them to angular.json. This is problematic, since Angular does not support adding global styles to angular.json config for a LIBRARY project.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid.

Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
