### ISSUE TITLE
Properties wont update their value from theme

### ISSUE THREAD

**Issue by pantelispanayiotou** [storybookjs/storybook#15263]
**Describe the bug**
Using Material UI v5 (alpha 34, emotion) and the decorator i wrap my stories inside my theme. The problem is that on the first render of some components the default theme of material ui is used and only on the next refresh or component switch will the component actually inherit from my custom theme.

**To Reproduce**
    1. Click on a component
    2. Wrong theme is used
    3. Refresh website while on this component
    4. Correct theme is used

**Comment by shilman** [comment]
Can you please create a reproduction by running `npx sb@next repro`, following the instructions, and linking it in your issue description? We prioritize issues with reproductions over those without. Thank you! 🙏
