### ISSUE TITLE
Storybook-Expo - Unable to build when referencing @react-navigation

### ISSUE THREAD

**Issue by channelaffairs** [storybookjs/storybook#15271]
**Describe the bug**
I can run storybook locally with no problems, however when I run the command build-storybook, the build fails while attempting to optimise the bundle 
In short it seems that the storybook webpack cannot manage static files coming from react-navigation 

<img width="1268" alt="image" src="https://user-images.githubusercontent.com/61307145/122329809-622a6180-cf75-11eb-8872-ab6e53acd3ac.png">

**To Reproduce**
Please reference in a story @react-navigator/stack and/or @react-navigator/drawer.
**Below the versioning of the libraries involved**

    "@react-navigation/drawer": "5.12.5",
    "@react-navigation/native": "5.8.10",
    "@react-navigation/stack": "5.12.8",
    "@storybook/addon-actions": "6.2.9",
    "@storybook/addon-essentials": "6.2.9",
    "@storybook/addon-links": "6.2.9",
    "@storybook/react": "6.2.9",

Webpack config (Expo)

```
const { withUnimodules } = require("@expo/webpack-config/addons");
module.exports = ({ config }) => {
  return withUnimodules(config); //   {
};
```

**System**
Environment Info:

  System:
    OS: macOS 11.2.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 14.17.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.13 - /usr/local/bin/npm
  Browsers:
    Chrome: 91.0.4472.106
    Safari: 14.0.3

**Additional context**
Once I remove the reference to stack and drawer navigator, the issue does not occur 

Any help would be appreciated 

Thanks!

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid.

Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
