### ISSUE TITLE
Using a Decorator with react-theming/storybook-addon crashes all parameters and other styles

### ISSUE THREAD

**Issue by NitsanCohen770** [storybookjs/storybook#15270]
**Describe the bug**
When I am trying to add a theme provider with react-theming/storybook-addon it all works well and all the themes are shown on the screen but my styles from the parameters variable crashes (are not seen on the screen, even though I can select them) I can't see the background color I set, for example.
**To Reproduce**
Was not able to do it

**System**
Environment Info:

  System:
    OS: Linux 4.19 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 15.10.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /mnt/c/Program Files (x86)/Yarn/bin/yarn
    npm: 7.6.0 - /usr/local/bin/npm
  npmPackages:
    @storybook/addon-actions: ^6.2.9 => 6.2.9 
    @storybook/addon-essentials: ^6.2.9 => 6.2.9 
    @storybook/addon-links: ^6.2.9 => 6.2.9 
    @storybook/react: ^6.2.9 => 6.2.9 

**Additional context**

Ok so basically the problem is that the @react-theming/storybook-addon is clashing with @storybook/addon-backgrounds. Does anyone know how to solve it?

**Comment by shilman** [comment]
Have you tried disabling backgrounds? https://storybook.js.org/docs/react/essentials/introduction#disabling-addons

**Comment by NitsanCohen770** [comment]
The thing is, I want to have the background :)

**Comment by shilman** [comment]
Maybe try filing an issue on react-theming/storybook-addon?

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid.

Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
