### ISSUE TITLE
rc8 fails to install due to peer dependency mismatch

### ISSUE THREAD

**Issue by 43081j** [storybookjs/storybook#15273]
Very simple one here, in the rc8 version bump it seems the docs package didn't have its peers bumped at the same time:

https://github.com/storybookjs/storybook/blob/c59f2136bdd338bd2cf8e28fd6e6d286a5994952/addons/docs/package.json#L140-L143

This means latest npm can't install storybook rc8 without `--force` as `addon-docs` wants the beta version but the user wants the rc version.

**Comment by shilman** [comment]
Yay!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.3.0-rc.9 containing PR #15277 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
