### ISSUE TITLE
Storybook crashes with children.match is not a function when using 6.3.0-rc.9

### ISSUE THREAD

**Issue by wenche** [storybookjs/storybook#15282]
**Describe the bug**
The use of  `6.3.0-rc.9` is causing my Storybook to crash with a runtime error of
![Skjermbilde 2021-06-17 kl  15 37 28](https://user-images.githubusercontent.com/1568252/122407881-3cf02000-cf82-11eb-9dab-38e50744cecd.png)
It seems like it is related to the use of **code** in parameters
```
export default {
  title: 'Components/Eyebrow',
  component: Eyebrow,

  parameters: {
    docs: {
      description: {
        component: `An <code>Eyebrow</code> component is used for text overline.
        `,
      },
    },
  },
} as Meta
```

**System**
Environment Info:

  System:
    OS: macOS 11.2.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Binaries:
    Node: 14.16.1 - ~/.volta/tools/image/node/14.16.1/bin/node
    Yarn: 1.22.10 - ~/.volta/bin/yarn
    npm: 6.14.12 - ~/.volta/tools/image/node/14.16.1/bin/npm
  Browsers:
    Chrome: 91.0.4472.106
    Edge: 91.0.864.48
    Firefox: 88.0.1
    Safari: 14.0.3

**Additional context**
Happens with `6.3.0-rc.9` installed with  `pnpx sb upgrade --prerelease` in[ my repository](https://github.com/equinor/energyvision/commit/bb40c5d882186c20436f9a1151208bf7a3451104)

**Comment by soulfresh** [comment]
I'm seeing this on `6.3.8` as well. Replacing all `<code>` blocks with back ticks in my docs resolves the issue.

**Comment by shilman** [comment]
Egads!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-beta.4 containing PR #15492 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
