### ISSUE TITLE
Vite builder sorting stories alphabetically instead of by export order

### ISSUE THREAD

**Issue by Rixcy** [storybookjs/storybook#15305]
## Describe the bug

It doesn't seem like stories are sorted in the same way as previous versions. Previously it looked like stories were sorted by the order they were exported, so if `Default` was exported first, it'd show first in the sidebar and in the docs page. This doesn't seem to be the case with the new Vite builder, if I create `Default` and `Custom`, even if Custom comes after Default in the order of exports, Custom will show first. Overriding the sortOrder in the `preview.js` file doesn't seem to fix it either.

## Working Example

(This could probably be replicated with other setups too)

- Create a nextjs app with `npx create-next-app`
- Add storybook with npx sb init
- Modify `1-Button.stories.js` to have the following stories:
```jsx
export const Default = () => <Button>Test</Button>
export const Custom = () => <Button>Test</Button>
```
- Open storybook
- Sidebar and canvas/docs (if you add and configure the docs addon) both show the order of [Default, Custom]

## Failing Example (https://github.com/Rixcy/storybook-vite-repro)

- Create a vite app with `yarn create @vitejs/app`
- Add storybook with the vite loader using `npx sb@next init --builder storybook-builder-vite`
- Modify `Button.stories.tsx` to have the following stories:
```jsx
export const Default = Template.bind({})
export const Custom = Template.bind({})
```
- Open storybook
- Sidebar and canvas/docs show an order of [Custom, Default]
_(Expected result: [Default, Custom])_

## System
```
  System:
    OS: macOS 11.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 14.15.0 - ~/.nvm/versions/node/v14.15.0/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.0/bin/npm
  Browsers:
    Chrome: 91.0.4472.106
    Firefox: 88.0.1
    Safari: 14.1.1
  npmPackages:    @storybook/addon-actions: ^6.3.0-rc.11 => 6.3.0-rc.11 
    @storybook/addon-essentials: ^6.3.0-rc.11 => 6.3.0-rc.11 
    @storybook/addon-links: ^6.3.0-rc.11 => 6.3.0-rc.11 
    @storybook/react: ^6.3.0-rc.11 => 6.3.0-rc.11 
```

**Comment by shilman** [comment]
Please file Vite-related issues in https://github.com/eirslett/storybook-builder-vite/

Thank you! 🙏

**Comment by janivo** [comment]
I don't know if this issue is exclusive to the vite-builder. The same happens to me. Weirdly, there seems to be a difference between the start and the build mode of a storybook.

## Dependencies:
```
    "@storybook/addon-actions": "^6.3.2",
    "@storybook/addon-essentials": "^6.3.2",
    "@storybook/addon-links": "^6.3.2",
    "@storybook/addon-viewport": "^6.3.2",
    "@storybook/builder-webpack5": "^6.3.2",
    "@storybook/manager-webpack5": "^6.3.2",
    "@storybook/theming": "^6.3.2",
    "@storybook/web-components": "^6.3.2",
```

## Preview Configuration:
```js
options: {
    storySort: {
      order: [
        'Docs',
        ['Welcome', 'Changelog', 'Framework Integration', 'Styleguide', 'Contributing'],
      ],
    },
  }
```

## Example story
https://github.com/inovex/elements/blob/v4.0.0/packages/storybook/src/stories/ino-button/ino-button.stories.ts

## Expected (working in start mode)
should sort by definition in source code
![image](https://user-images.githubusercontent.com/22963121/124499171-dfe7cd00-ddbd-11eb-8b4d-2df2fa69bd5e.png)

## Actual (not working in build mode)
alphabetical
![image](https://user-images.githubusercontent.com/22963121/124498988-8b445200-ddbd-11eb-9ab7-20d8d356d31c.png)
