### ISSUE TITLE
storyshots and component initialization

### ISSUE THREAD

**Issue by marxsk** [storybookjs/storybook#15313]
**Describe the bug**
When using combo jest/angular/storybook/storyshots there is a problem with initialization of the components. The error does not occurs when using storybook alone (or when 'npm run storybook' is used). But it occurs only when running snapshot testing. 

It looks like that component is initialized without args and they are set later on. There should be a way how to do this at once. 

**To Reproduce**

Let's have angular component template

```
{{ data.name }}
```

Attempt to access property 'name' ends with: TypeError: Cannot read property 'name' of undefined. Workaround is to rewrite the template to use 
```
<ng-container *ngIf="data">
{{ data.name }}
</ng-container>
```
but this change the source code itself what is not correct. The snapshot with ng-container is correct afterwards. 
Test definition is pretty much standard:
```
...
export const SecondaryArgs = Template.bind({});
SecondaryArgs.args = {
  data: {
    name: 'foo',
  }
};
```

**System**
Environment Info:

  System:
    OS: Linux 5.11 Fedora 32 (Workstation Edition) 32 (Workstation Edition)
    CPU: (32) x64 AMD Ryzen Threadripper 1950X 16-Core Processor
  Binaries:
    Node: 12.22.1 - /usr/bin/node
    npm: 6.14.12 - /usr/bin/npm
  Browsers:
    Chrome: 91.0.4472.77
    Firefox: 88.0.1

**Additional context**

**Comment by ndelangen** [comment]
The future of storyshots is the test-runner:
https://storybook.js.org/docs/react/writing-tests/test-runner#page-top

And use the play function for expectations:
https://storybook.js.org/docs/react/writing-stories/play-function#page-top

We will not be making any improvement / changes to storyshots.
