### ISSUE TITLE
[Angular 6.2.x] Cannot find module @storybook/angular

### ISSUE THREAD

**Issue by MathiasOliveira** [storybookjs/storybook#15311]
**Describe the bug**
I am trying to setup Storybook for Angular 8, however when running npm run storybook I am getting the following errors:

```
ERROR in /home/user/dev/storybook/src/stories/Button.stories.ts
ERROR in /home/user/dev/storybook/src/stories/Button.stories.ts(2,29):
TS2307: Cannot find module '@storybook/angular/types-6-0'.

ERROR in /home/user/dev/storybook/src/stories/Header.stories.ts
ERROR in /home/user/dev/storybook/src/stories/Header.stories.ts(1,32):
TS2307: Cannot find module '@storybook/angular'.

ERROR in /home/user/dev/storybook/src/stories/Header.stories.ts
ERROR in /home/user/dev/storybook/src/stories/Header.stories.ts(4,29):
TS2307: Cannot find module '@storybook/angular/types-6-0'.

ERROR in /home/user/dev/storybook/src/stories/Page.stories.ts
ERROR in /home/user/dev/storybook/src/stories/Page.stories.ts(1,45):
TS2307: Cannot find module '@storybook/angular'.
```

**To Reproduce**
Unable to create a reproducible test case as Angular 8 is not listed in `npx sb@next repro` and the node version I am using `node@10.12` does not support the versions listed.

**System**
```
Environment Info:

  System:
    OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (6) x64 Intel(R) Core(TM) i5-9500 CPU @ 3.00GHz
  Binaries:
    Node: 10.12.0 - ~/.nvm/versions/node/v10.12.0/bin/node
    npm: 6.4.1 - ~/.nvm/versions/node/v10.12.0/bin/npm
  npmPackages:
    @storybook/addon-actions: ^6.2.9 => 6.2.9 
    @storybook/addon-essentials: ^6.2.9 => 6.2.9 
    @storybook/addon-links: ^6.2.9 => 6.2.9 
    @storybook/angular: ^6.2.9 => 6.2.9
```

**Additional context**

[My current package.json](https://pastebin.com/JBBGmPc3)

[NPM output while running npm run storybook](https://gist.github.com/MathiasOliveira/b72cbb3014ca6aecd938827e5680bd82)

 Steps I've already tried:
* Importing everything from `@storybook/angular` and not using `@storybook/angular/types-6-0` [Source](https://stackoverflow.com/questions/63462166/angular-8-with-storybook-6)
* Adding `@storybook/angular/types-6-0` to `.storybook/typings.d.ts` [Source](https://stackoverflow.com/questions/60754585/unable-to-start-storybook-with-angular)
* Adding `../src/setupJest.ts` to the exclude array in `.storybook/tsconfig.json` [Source](https://stackoverflow.com/questions/60506073/storybook-not-working-in-angular-intershop-project)
* Adding `"enableIvy": false` to `tsconfig.json` under `"angularCompilerOptions"`

Vscode can see the modules just fine:

![image](https://user-images.githubusercontent.com/67007152/122767505-20513200-d279-11eb-97c9-1698d870fd8c.png)

**Notes**
Although I am sure that Angular 8 is not supported by Storybook, I would still like some help as I am getting a lot of pressure from my bosses to "do the needful and whip up the thing for us" so we can have a components library. Sadly, upgrading Angular or node is not an option at the moment.

[I have also created a question on StackOverflow for this exact situation.](https://stackoverflow.com/questions/68067913/storybook-cannot-find-module-storybook-angular)

**Comment by shilman** [comment]
Have you tried upgrading to the latest prerelease?

```
npx sb@next upgrade --prerelease
```

**Comment by MathiasOliveira** [comment]
@shilman Same error, sadly.

I have included the full npm output when running `npm run storybook` in the original post

**Comment by EliHowey** [comment]
I think this might be related to an issue I wrote a few weeks ago: https://github.com/storybookjs/storybook/issues/15196

For this issue, notice that the Storybook is compiling with TypeScript v3.5.3, but VS Code's Intellisense is pointing to the `ts3.9` types.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid.

Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
