### ISSUE TITLE
Issue with "Controls - Dealing with complex values" guide for Vue

### ISSUE THREAD

**Issue by santiagoarizti** [storybookjs/storybook#15327]
**Describe the bug**
Following [this guide](https://storybook.js.org/docs/vue/essentials/controls#dealing-with-complex-values) for Storybook+vue doesn't produce output expected.

In this guide "dealing with complex values" we find that we can map the value of a control in a story through a complex function to produce some complex prop for a component.

Following the guide, although very closely, doesn't work: the modified "arg"'s properties don't do anything to the rendered component.

**To Reproduce**
https://bitbucket.org/cpsanti/storybook-bug-report1/src/storybook-bug-report1/

**System**
note: I tried to use npx sb@next but it didn't work. I copied the output of system from another issue and altered it to match my team's setup:

    System:
      OS: Windows 10 and MacOS (team uses both and this fails for all of us)
    Binaries:
      Node: 16.3.0
      npm: 7.15.1
    Browsers:
      Chrome: Version 91.0.4472.114 (Official Build) (x86_64)
    npmPackages:
        "@vue/cli": "^4.5.13",
        "core-js": "^3.6.5",
        "vue": "^2.6.11"
        "@babel/core": "^7.14.3",
        "@storybook/addon-actions": "^6.2.9",
        "@storybook/addon-essentials": "^6.2.9",
        "@storybook/addon-links": "^6.2.9",
        "@storybook/vue": "^6.2.9",
        "@vue/cli-plugin-babel": "~4.5.0",
        "@vue/cli-plugin-eslint": "~4.5.0",
        "@vue/cli-service": "~4.5.0",
        "babel-eslint": "^10.1.0",
        "babel-loader": "^8.2.2",
        "eslint": "^6.7.2",
        "eslint-plugin-vue": "^6.2.2",
        "vue-loader": "^15.9.7",
        "vue-template-compiler": "^2.6.11"

**Additional context**
The repo I built was stripped down of any complexity, it contains exactly 1 compoent and 1 story file.
Launching storybook in my repo shows the same explanation of the but I provided here.

**Comment by jonniebigodes** [comment]
@santiagoarizti thanks for bringing this to our attention, let me take a look and see what might be the issue and if need be I'll update the documentation accordingly.

**Comment by santiagoarizti** [comment]
Ok, I upgraded to storybook 6.3 and to builder webpack5 and still have the issue. It would be nice to learn if the documentation works for someone or is this use case broken for everybody

**Comment by willwill96** [comment]
I experienced the same issue when trying to upgrade to v6. @santiagoarizti I was able to resolve the issue by downgrading to 6.1.21 and the following configuration in the story.
```
export const Story = (args, { argTypes }) => {
 const { controlA, controlB } = args
 // calculateValue returns the value of the prop
 args.complexProp = calculateValue(contralA, controlB)
 return {
     components: { MyComponent },
     props: Object.keys(argTypes),
     template: `<my-component v-bind="$props"></my-component>`,
  }
}

Story.argTypes = {
  controlA: {
    control: {
      type: 'text',
    },
    defaultValue: '',
  },
  controlB: {
    control: {
      type: 'text',
    },
    defaultValue: '',
  },
  complexProp: {
    control: {
      type:'object',
      disable: true
    }
  }
}
```

Not ideal, but it gets the job done for now.

**Comment by jonniebigodes** [comment]
@santiagoarizti and @willwill96 indeed that's the case, I tested it with the latest 6.3 version and upon running `yarn storybook` it provides me the following output:

![Storybook-6-3-complex-values-not-working](https://user-images.githubusercontent.com/22988955/127672320-a6c8c45e-b5f3-4c7f-ba35-36dd15e95639.png)

Looking at the devtools I'm getting this:
<img width="1432" alt="Storybook-6-3-complex-values-not-working-dev-tolls" src="https://user-images.githubusercontent.com/22988955/127672414-34ba5aca-0403-4bb9-9144-840cdb31c9a2.png">

As you can see the function is being called and it should have been updated accordingly.

Created a new branch and cleared node_modules and the lock file bumped back to the latest 6.2 version. Ran `yarn` to install the dependencies. 

Issued `yarn storybook` and it yielded the following:
![Storybook-6-2-not-working-complex-values](https://user-images.githubusercontent.com/22988955/127673354-bea75fe3-0aee-4ff4-ad81-f1b511312c05.png)

Checked the devtools while testing and once again the function was being called and it should have updated the story.
<img width="1435" alt="Storybook-6-2-not-working-complex-values-dev-tools" src="https://user-images.githubusercontent.com/22988955/127673555-e6a3bbd8-e521-45e3-bd6f-d238e179c04b.png">


Bumped back to the latest 6.1 version and like @willwill96 mentioned it worked. It seems this is related to how the Story is rendered and updated when modifying args /props. To avoid confusion I'm pushing a pr addressing this situation and link this issue.

Stay safe

**Comment by jonniebigodes** [comment]
Reproduction hosted [here](https://github.com/jonniebigodes/repro-for-sb-issue-15327). The `main` branch is using the latest Storybook stable release. The [`bump_down_sb_6_2`](https://github.com/jonniebigodes/repro-for-sb-issue-15327/tree/bump_down_sb_6_2) the latest 6.2 stable release and [bump_down_sb_6_1](https://github.com/jonniebigodes/repro-for-sb-issue-15327/tree/bump_down_sb_6_1) the latest 6.1 release.

**Comment by jonniebigodes** [comment]
Closing this for now. As the changes required need a bit of work upstream. If anyone in the community is willing to help us with this issue and Vue 2 in general ping me and we can cycle back to this issue.
