### ISSUE TITLE
Story parameters do not update when they are based on story args

### ISSUE THREAD

**Issue by jamesonhill** [storybookjs/storybook#15325]
**Describe the bug**
If a story has a parameter set based off another arg of the story, changing the arg control does not update the parameters that depend on it.

Before upgrading from version `5.3.x`, we could control parameters (like graphQL query mocks) using knobs like below (simplified example).
```
import { boolean } from '@storybook/addon-knobs;
import { useQuery } from 'apollo-client';
import { gql } from 'graphql-tag';

const query = gql`query GetUser() users() { name }`;

const UserProfile = () => {
  const { data, error, loading } = useQuery(query);

  return data ? <div>{data.users.name}</div> : <div>error</div>;
}

export const BasicStory = () => <UserProfile />;

BasicStory.story = {
  parameters: {
    apolloMocks: () => ({ Query: () => ({ users:  boolean('Error', false) ? () => throw new Error() : { name: 'joe' } }) })
  }
}
```

However, what seems like the "args" equivalent after updating to version `6.3` does not work after the knob changes. The initial value is always used when determining the parameter.

```
const Template = () => <UserProfile />;
const BasicStory = Template.bind({});

BasicStory.args = { error: false } ;
BasicStory.parameters = {
    apolloMocks: () => ({ Query: () => ({ users:  BasicStory.args.error ? () => throw new Error() : { name: 'joe' } }) })
  }
// BasicStory.args.error is always false
```

Is the above not the correct way to control parameters using the new args approach?

**To Reproduce**
The repro command failed w/ this error: 
```
An error occurred while executing: `yarn set version berry && yarn config set enableGlobalCache true && yarn config set nodeLinker node-modules`
```

**System**
Environment Info:

  System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 10.24.1 - /usr/local/opt/node@10/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.12 - /usr/local/opt/node@10/bin/npm
  Browsers:
    Chrome: 91.0.4472.106
    Firefox: 88.0.1
    Safari: 14.1
  npmPackages:
    @storybook/addon-actions: ^6.3.0-rc.11 => 6.3.0-rc.11 
    @storybook/addon-docs: ^6.3.0-rc.11 => 6.3.0-rc.11 
    @storybook/addon-essentials: ^6.2.9 => 6.2.9 
    @storybook/addon-knobs: ^6.3.0-next.2 => 6.3.0-next.2 
    @storybook/addon-links: ^6.3.0-rc.11 => 6.3.0-rc.11 
    @storybook/addon-viewport: ^6.3.0-rc.11 => 6.3.0-rc.11 
    @storybook/addons: ^6.3.0-rc.11 => 6.3.0-rc.11 
    @storybook/preset-create-react-app: ^3.1.7 => 3.1.7 
    @storybook/react: ^6.3.0-rc.11 => 6.3.0-rc.11 

**Additional context**

**Comment by tmeasday** [comment]
Hey @jamesonhill, this is an interesting use case.

Just to be clear: you are not **changing** the parameter when the knob value changes. The parameter is a function that reads the value of the knob **at runtime.**

So to replicate the same idea in args, you would need some way to read the value of the arg **at runtime**. `BasicStory.args.error` is not going to give you that -- that's the value of the arg set on the story, you could think of that as the initial value of the arg.

Typically in a decorator, you'd read the current value of the arg off of the context:

```js
const myDecorator = (storyFn, context) => {
  const { error } = context.args;
}
```

The addon that does the query mocks is writing the above decorator; so the key piece here would be for it to pass that context into your mocked resolvers. I'm not sure what addon you are using or whether it does this, but I think it would totally make sense for the SB context to be available on the GraphQL resolver context. In fact it might even make sense to put the args as a first class citizen on the GQL context 🤔 .

So your resolver mock would look something like:

```js
    apolloMocks: () => ({ Query: (root, args, context) => ({ users:  context.sbContext.args.error ? () => throw new Error() : { name: 'joe' } }) })
```

Does that makes sense?

**Comment by jamesonhill** [comment]
@tmeasday  Yea, that approach does make sense. I'll give it a shot. Thanks for the explanation.

**Comment by jamesonhill** [comment]
@tmeasday That worked perfectly. Thanks again. I'll close the issue.

**Comment by tsaiDavid** [comment]
> @tmeasday That worked perfectly. Thanks again. I'll close the issue.

@jamesonhill - I was wondering if you could provide an example of how it ended up working for you? I'm digging into how to get this same issue resolved but in using `storybook-addon-apollo-client` ([here](https://storybook.js.org/addons/storybook-addon-apollo-client))

Sample contents of `preview.js`:
```ts
export const parameters = {
  apolloClient: {
    MockedProvider,
    name: 'storybook-mock-apollo-client',
    addTypename: false,
  },
};
```

And the actual story might look like:
```ts
export default {
  title: 'FooBar',
  component: FooBar,
  decorators: [
    (MyStory) => (
      <ViewState.Provider>
        {MyStory()}
      </ViewState.Provider>
    ),
  ],
} as Meta;

const FooBarTemplate: Story = (args) => <FooBar {...args} />;

export const BasicStory = FooBarTemplate.bind({});
BasicStory.parameters = {
  apolloClient: {
    mocks: [
      {
        request: {
          query: GetUserDetailsDocument,
          variables: { id: 123 },
        },
        result: {
          data: {
            name: 'John Smith',
            age: 30
          },
        },
      }
    ],
  },
}
```

**Comment by jamesonhill** [comment]
@tsaiDavid Sure, i'll give it a try. tl;dr we're using a decorator and passing the storybook context from the decorator function to an apollo mock provider. 

```
import {
  ApolloClient,
  ApolloProvider,
  InMemoryCache,
} from '@apollo/client';
import { StoryContext } from '@storybook/react';
import { addMockFunctionsToSchema, IMocks, makeExecutableSchema } from 'graphql-tools';
import React from 'react';
import fragmentMatcher from '../../__generated__/fragmentMatcher';
import defaultOptions from '../apollo/defaultOptions';
import { mocks as defaultMocks, typeDefs, typeResolvers } from './graphql';

// Create apollo mock provider 

const MockStorybookApolloProvider = ({
  children,
  context: storyBookContext
}) => {
  const schema = makeExecutableSchema({ typeDefs, resolvers: typeResolvers });

  let mockDefaults = defaultMocks as IMocks;
  let mockOverrides = overrides as IMocks;

// Here is important part; take storybook context and merge it with graphql context
  const mocks: IMocks = {
    ...defaultMocks,
    Query: (source, args, context, info) => ({
      ...mockDefaults.Query(source, args, context, info),
      ...(mockOverrides.Query
        ? mockOverrides.Query(source, args, { ...context, ...storyBookContext }, info)
        : {})
    }),
    Mutation: (source, args, context, info) => ({
      ...mockDefaults.Mutation(source, args, context, info),
      ...(mockOverrides.Mutation
        ? mockOverrides.Mutation(source, args, { ...context, ...storyBookContext }, info)
        : {})
    })
  };

  addMockFunctionsToSchema({
    schema,
    mocks,
    preserveResolvers: true
  });

  // ... more setup / error handling

  const client = new ApolloClient({
    cache: new InMemoryCache({
      possibleTypes: fragmentMatcher.possibleTypes,
      typePolicies
    }),
    connectToDevTools: true,
    defaultOptions
  });

  return <ApolloProvider client={client}>{children}</ApolloProvider>;
};

// Create storybook decorator function and pass in the storybook context

const apolloDecorator = (): DecoratorFn => {
  return (story, context) => {
    let overrides;
    if (isFunction(context.parameters.apolloMocks)) {
      overrides = context.parameters.apolloMocks();
    }

    return (
      <MockApolloProvider overrides={overrides} context={context}>
        {story()}
      </MockApolloProvider>
    );
  };
};

// preview.js
export const decorators = [apolloDecorator()];

// usage in storybook component; 
// assume this component fires query that returns `user | undefined` depending on auth state

export default {
  component: UserProfile
  args: { isLoggedIn: true },
  parameters: { 
    apolloMocks: () => ({ 
      Query: (_, _, { args } ) => ({ 
         users: () => args.isLoggedIn ? [{ name: 'joe' }] : undefined  
        }),
      Mutation: () => ({ 
           // same usage as query
         })
      })
  }
}
```

Hope that helps!
