### ISSUE TITLE
Action output is an object like {name: 'example', args: ''} instead of ''

### ISSUE THREAD

**Issue by ihodex** [storybookjs/storybook#15322]
**Describe the bug**

I have a story with a simple text input component. It has a `valueChange` event that returns string value on change. After upgrade to 6.3 I've noticed that empty string value is displayed like `{name: "valueChange", args: ""}` instead of just `""`. The same thing is with an `undefined` value.

Is possible to change this behavior? :)

**System**

```
  System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 14.17.0
    npm: 7.18.1
  Browsers:
    Edge: Spartan (44.19041.1023.0), Chromium (91.0.864.54)
  npmPackages:
    @storybook/addon-actions: ~6.3.0-rc.11 => 6.3.0-rc.11
    @storybook/addon-controls: ~6.3.0-rc.11 => 6.3.0-rc.11
    @storybook/addon-docs: ~6.3.0-rc.11 => 6.3.0-rc.11
    @storybook/addon-essentials: ~6.3.0-rc.11 => 6.3.0-rc.11
    @storybook/addon-links: ~6.3.0-rc.11 => 6.3.0-rc.11
    @storybook/angular: ~6.3.0-rc.11 => 6.3.0-rc.11
    @storybook/builder-webpack5: ^6.3.0-rc.11 => 6.3.0-rc.11
    @storybook/manager-webpack5: ^6.3.0-rc.11 => 6.3.0-rc.11
```

Thanks ;)

**Comment by ihodex** [comment]
It's too minor to create a reproduction, you can close it if @solidevolution don't mind :)

**Comment by solidevolution** [comment]
Don't mind, too. Close it, if you can ignore the bug.
