### ISSUE TITLE
New Angular render filters out input/output props from extended Component Classes

### ISSUE THREAD

**Issue by EvtK** [storybookjs/storybook#15330]
**Describe the bug**
In the new Angular renderer, the storybook input and output properties are filtered against the input and output properties defined on the component.

https://github.com/storybookjs/storybook/blob/c5749b0b640fcc2e1e27c04206c8a46418f7a34c/app/angular/src/client/preview/angular-beta/ComputesTemplateFromComponent.ts#L10

We have multiple Angular components that extend from a base class or base Angular Component. Because of the filtering, we now loose the @Input and @Output bindings defined on the base classes or components. 

There is defined an 'otherProps' return value, but I cannot find any reference in the source code of this otherProps value beiing used. 

I have tried to disable the new Angular Rendering following this [configuration](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#new-angular-renderer), but this configuration doesn't prevent that the newly added [decorateStory.ts](https://github.com/storybookjs/storybook/blob/c5749b0b640fcc2e1e27c04206c8a46418f7a34c/app/angular/src/client/preview/decorateStory.ts) will trigger the ComputesTemplateFromComponent method from the new Angular render.

**UPDATE**
After creating the reproduction, at first I couldn't re-create the problem. As it turns out, the above issue only appear when the @Input bindings from the base class/component are NOT initialized.

**To Reproduce**
https://github.com/EvtK/storybook-angular-renderer-issue

I have extended the Page Component from an abstract BasePage class and added an Input binding to this class. 

```
@Directive()
export abstract class BasePageComponent {
  @Input() inputFromBasePage: any;
}
```

In the Pages story I have added an args prop for this input:

```
const args = {
  user: {},  
  inputFromBasePage: {newValue: 'myNewValue'}
};

```

In the html template of the Page Component, I have added:

```
      <p> {{inputFromBasePage.newValue}}</p>
```

Results into:

```
core.js:6210 ERROR TypeError: Cannot read property 'newValue' of undefined
    at PageComponent_Template (VM409 PageComponent.js:82)
    at executeTemplate (core.js:9614)
    at refreshView (core.js:9480)
    at refreshComponent (core.js:10651)
    at refreshChildComponents (core.js:9277)
    at refreshView (core.js:9530)
    at detectChangesInternal (core.js:10833)
    at ViewRef.detectChanges (core.js:22818)
    at SafeSubscriber._next (StorybookWrapperComponent.js:74)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:183)
    
```

If I initialize the Input, the error is gone, and template reflectes args value.

```
@Directive()
export abstract class BasePageComponent {
  @Input() inputFromBasePage = { };
}
```

**System**
  npmPackages:
    @storybook/addon-essentials: 6.2.9 => 6.2.9 
    @storybook/addons: 6.2.9 => 6.2.9 
    @storybook/angular: 6.2.9 => 6.2.9 
    @storybook/theming: 6.2.9 => 6.2.9 
**Additional context**

**Comment by shilman** [comment]
closing as dupe to #14968
