### ISSUE TITLE
Storybook 6.4 release 🏗

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#15355]
SB6.4 adds interaction testing and performance re-architecture in preparation for a huge 7.0 release.

## Schedule

- ✅ `6.4.0-alpha.0` 2021-06-24
- ✅ `6.4.0-beta.0` 2021-09-22
- ✅  `6.4.0-rc.0` 2021-11-12
- ✅ `6.4.0` 2021-11-26

## Contents

Storybook 6.4 contains hundreds of features and bugfixes. For a full list, see [CHANGELOG.md](https://github.com/storybookjs/storybook/blob/next/CHANGELOG.md). Some highlights:

### Core

- CSF3: Generate default titles based on file path #15376
- Core: Add Babel mode v7 #15928
- Core: Add MDX support to built-in stories.json generation #15808 
- Core: Add globals URL param and remove from sessionStorage #15056

### UI

- UI: Display menu icon on the toolbar when the sidebar is collapsed #15369 
- UI: Add skip to canvas/sidebar links #15740

### Frameworks

- Angular: Add global CSF3 renderer #15774
- HTML: Dynamic source snippets #15748
- Web-components: Dynamic source snippets #15337 
- Web-components: Custom Elements Manifest v1 support #15138
- Server: Upgrade to CSF3 #15698 

## Testing

To install in a project:

```
npx sb init
```

To upgrade an existing project to a 6.4:

```
npx sb@next upgrade
```

**Comment by kevincam3** [comment]
I did an upgrade from 6.3 to 6.4.0-alpha.25 but removing the title gives me an error. See attached. I changed the stories property in main.js to ["../src"] and also enabled it in main.js with features: {previewCsfV3: true}.

See attached error I see if I don't add a title
![image](https://user-images.githubusercontent.com/870934/128633244-abdb6136-afb3-4bfc-829a-14ba8e774119.png)

**Comment by stefan-schweiger** [comment]
Somewhere between alpha.24 and alpha.29 there was a massive performance regression for me. Before starting storybook took about 10-20 seconds now its more up to 1-2 minutes.

**Comment by soilSpoon** [comment]
In the Contents section, what is written as 6.3 should be changed to 6.4

**Comment by yannbf** [comment]
> Somewhere between alpha.24 and alpha.29 there was a massive performance regression for me. Before starting storybook took about 10-20 seconds now its more up to 1-2 minutes.

Hey @stefan-schweiger thanks for sharing that info! Could you try again now that the RC is out?

**Comment by kdembler** [comment]
Hey @shilman, any update on separating docgen functionality from Webpack (what you mentioned in https://github.com/eirslett/storybook-builder-vite/issues/46#issuecomment-869284292), is this no longer in scope for 6.4?

**Comment by darkowic** [comment]
> Linter to enforce Storybook best practices

Do you have any docs for it? How does it work?

**Comment by yannbf** [comment]
> > Linter to enforce Storybook best practices
> 
> Do you have any docs for it? How does it work?

Hey @darkowic, you can find the eslint-plugin and its docs over this repository: https://github.com/storybookjs/eslint-plugin-storybook

Thanks for your interest!
