### ISSUE TITLE
children.match is not a function when using HTML entity numbers inside <code> inside markdown table

### ISSUE THREAD

**Issue by netcoding87** [storybookjs/storybook#15359]
**Describe the bug**
When using an HTML entity number inside a `<code>` element inside a markdown table the storybook crashes with `Uncaught TypeError: children.match is not a function at Code`

**To Reproduce**
GitHub Repo: https://github.com/netcoding87/storybook-html-entity

* Start storybook
* Open Story 1 => code is shown
* Open Story 2 => Exception occurs

**System**

* System:
  * OS: Windows 10 10.0.19042
  *  CPU: (8) x64 Intel(R) Core(TM) i5-10400H CPU @ 2.60GHz
* Binaries:
  * Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
  * Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
  * npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
* Browsers:
  *  Edge: Spartan (44.19041.964.0), Chromium (91.0.864.54)

**Additional context**
This problem arose with updating from 6.2.9 to 6.3.0

**Comment by codylindley** [comment]
I'm seeing this as well when I moved from 6.2.9 to 6.3.1.

**Comment by literalpie** [comment]
I'm seeing this, but I'm not sure the exact pattern of what causes it. We don't have any HTML entity numbers, but we are seeing it when using a `code block` in the description of an angular directive (which gets displayed outside any tables). However, we are _not_ seeing the issue when there is code within the comment of an input on a component (which gets displayed inside a table).

Hopefully that helps narrow down the issue somehow :-)

**Comment by literalpie** [comment]
I don't have time to test it, but I think making children optional [here](https://github.com/storybookjs/storybook/blob/next/lib/components/src/typography/DocumentFormatting.tsx#L339) might fix the issue

**Comment by shilman** [comment]
Egads!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-beta.4 containing PR #15492 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
