### ISSUE TITLE
Unable to run Storybook after installing TailwindCSS [Stack: NextJS11, PrismicCMS with Slice Machine, Storybook]

### ISSUE THREAD

**Issue by nathansom** [storybookjs/storybook#15381]
### Bug:

- Failing to run Storybook (command: `yarn run storybook`) after TailwindCSS was installed on a NextJS project with Prismic CMS [with Slice Machine]. The console shows the following error:

`ModuleBuildError: Module build failed (from ./node_modules/@storybook/addon-postcss/node_modules/postcss-loader/dist/cjs.js):

TypeError: Cannot read property 'query' of undefined

    at getOptions (~/my-repo/node_modules/loader-utils/lib/getOptions.js:6:31)

    at loader ((~/my-repo/node_modules/@storybook/addon-postcss/node_modules/postcss-loader/dist/index.js:42:47)

    at LazyResult.runOnRoot ((~/my-repo/node_modules/postcss/lib/lazy-result.js:339:16)

    at LazyResult.runAsync ((~/my-repo/node_modules/postcss/lib/lazy-result.js:391:26)

    at async Object.loader ((~/my-repo/node_modules/@storybook/addon-postcss/node_modules/postcss-loader/dist/index.js:95:14)

    at processResult ((~/my-repo/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/NormalModule.js:701:19)

    at (~/my-repo/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/NormalModule.js:807:5

    at (~/my-repo/node_modules/@storybook/builder-webpack5/node_modules/loader-runner/lib/LoaderRunner.js:399:11

    at (~/my-repo/node_modules/@storybook/builder-webpack5/node_modules/loader-runner/lib/LoaderRunner.js:251:18

    at context.callback ((~/my-repo/node_modules/@storybook/builder-webpack5/node_modules/loader-runner/lib/LoaderRunner.js:124:13)

    at Object.loader (~/my-repo/node_modules/@storybook/addon-postcss/node_modules/postcss-loader/dist/index.js:104:7)`

### How to reproduce the bug:

1. Clone the following NextJS-PrismicCMS (with Slice Machine) starter

`prismic theme --theme-url https://github.com/prismicio-community/slice-library-starter-next --conf sm.json`

2. Add some UI components to the project. Sample components can be copied from [the official tutorial by Prismic](https://prismic.io/docs/technologies/create-homepage-banner-nextjs)

3. Replace the code in **package.json** file with the following then run `yarn install` one more time.

`{
  "name": "slice-library-starter-next",
  "version": "0.0.0",
  "description": "An awesome Slice Library made with Next.js",
  "author": "<author>",
  "license": "MIT",
  "main": "slices/index.js",
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "export": "next export",
    "prepublishOnly": "node ./node_modules/sm-commons/scripts/bundle",
    "slicemachine": "start-slicemachine --port 9999",
    "storybook": "start-storybook -p 8888",
    "build-storybook": "build-storybook"
  },
  "dependencies": {
    "algoliasearch": "^4.10.2",
    "instantsearch.js": "^4.24.1",
    "next": "^11.0.1",
    "next-compose-plugins": "^2.2.1",
    "next-pwa": "^5.2.21",
    "next-seo": "^4.26.0",
    "next-slicezone": "^0.1.0",
    "next-transpile-modules": "^8.0.0",
    "prismic-javascript": "^3.0.2",
    "prismic-reactjs": "^1.3.4",
    "react": "^17.0.2",
    "react-dom": "^17.0.2"
  },
  "devDependencies": {
    "@storybook/addon-actions": "^6.4.0-alpha.3",
    "@storybook/addon-essentials": "^6.4.0-alpha.3",
    "@storybook/addon-links": "^6.4.0-alpha.3",
    "@storybook/addon-postcss": "^2.0.0",
    "@storybook/builder-webpack5": "^6.4.0-alpha.3",
    "@storybook/manager-webpack5": "^6.4.0-alpha.3",
    "@storybook/react": "^6.4.0-alpha.3",
    "autoprefixer": "^10.2.6",
    "babel-loader": "^8.2.2",
    "babel-plugin-react-require": "^3.1.3",
    "postcss": "^8.3.5",
    "postcss-100vh-fix": "^1.0.2",
    "postcss-flexbugs-fixes": "^5.0.2",
    "postcss-import": "^14.0.2",
    "postcss-loader": "^6.1.0",
    "postcss-preset-env": "^6.7.0",
    "shx": "^0.3.3",
    "slice-machine-ui": "^0.0.46",
    "sm-commons": "^0.0.23",
    "tailwindcss": "^2.2.4"
  }
}
`

4. Replace the code in **.storybook/main.js** file with the following to make Storybook run on Webpack 5 and Postcss 8.x.x:

`module.exports = {
  core: {
    builder: 'webpack5',
  },
  stories: ["../slices/**/*.stories.[tj]s", "../styles/globals.css"],
  addons: [
    "@storybook/addon-actions",
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    {
      name: '@storybook/addon-postcss',
      options: {
        postcssLoaderOptions: {
          implementation: require('postcss'),
        },
      },
    }
  ]
}
`
5. Install TailwindCSS by running the command: `yarn add tailwindcss@latest postcss@latest autoprefixer@latest --dev`

Then, generate the configuration files using the command: `npx tailwindcss init -p`

6. Replace the code in the **postcss.config.js** file with the following:

`module.exports = {
  plugins: [
    'tailwindcss',
    'postcss-import',
    'postcss-100vh-fix',
    'postcss-loader',
    "postcss-flexbugs-fixes",
    [
      "postcss-preset-env",
      {
        "autoprefixer": {
          "flexbox": "no-2009",
          "grid": "autoplace"
        },
        "stage": 3,
        "features": {
          "custom-properties": false
        }
      }
    ]
  ]
}
`

7. Run `yarn run storybook`

**System**

Environment Info:

  System:
    OS: macOS 11.4
    CPU: (8) x64 Apple M1
  Binaries:
    Node: 14.16.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.11.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 91.0.4472.114
    Firefox: 80.0.1
    Safari: 14.1.1
  npmPackages:
    @storybook/addon-actions: ^6.4.0-alpha.3 => 6.4.0-alpha.3 
    @storybook/addon-essentials: ^6.4.0-alpha.3 => 6.4.0-alpha.3 
    @storybook/addon-links: ^6.4.0-alpha.3 => 6.4.0-alpha.3 
    @storybook/addon-postcss: ^2.0.0 => 2.0.0 
    @storybook/builder-webpack5: ^6.4.0-alpha.3 => 6.4.0-alpha.3 
    @storybook/manager-webpack5: ^6.4.0-alpha.3 => 6.4.0-alpha.3 
    @storybook/react: ^6.4.0-alpha.3 => 6.4.0-alpha.3 

**Thank you for any advice!**

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
