### ISSUE TITLE
The above error occurred in one of React components 

### ISSUE THREAD

**Issue by nodir-sulaymonov** [storybookjs/storybook#15384]
I have updated Storybook to version 6.3.0 I got a weird error in the browser console, but no errors in the IDE console
![image](https://user-images.githubusercontent.com/20314452/123544363-9ebb4180-d75b-11eb-96c2-9047bb52236f.png)

These components are not in our project, most likely they are inside the storybook

Additional context

"addons": [
"@storybook/addon-docs",
"@storybook/addon-links",
"@storybook/addon-essentials",
"@storybook/addon-actions",
"@storybook/addon-backgrounds",
"@storybook/addon-knobs",
"@storybook/addon-viewport",
"storybook-addon-designs",
"storybook-addon-i18next",
"@storybook/addon-postcss",
]

System
OS: macOS 11.3
CPU: (8) arm64 Apple 2019 core i 9
Binaries:
Node: 12.16.2
yarn: 1.22.5
Browsers:
Chrome: 90.0.4430.212
Firefox: 88.0.1
Safari: 14.1.1

**Comment by maeriens** [comment]
Without any actual repro it will be hard to debug what is happening. Can you run and paste the results of `npx sb@next info`? Did it work with previous storybook integrations? Does any warning appear in the storybook build? How are the stories written?
Also, would this ticket close #15098?

**Comment by nodir-sulaymonov** [comment]
@maeriens 

https://user-images.githubusercontent.com/20314452/126905044-adeabba5-1be5-4601-a089-0c70daf0788d.mp4

#main.js 

const path = require('path');

module.exports = {
  "stories": [
    "../stories/**/*.stories.mdx",
    "../stories/**/*.stories.@(js|jsx|ts|tsx)"
  ],
  "addons": [
    "@storybook/addon-docs",
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/addon-actions",
    "@storybook/addon-backgrounds",
    "@storybook/addon-knobs",
    "@storybook/addon-viewport",
    "storybook-addon-designs",
    "storybook-addon-i18next",
    {
      name: '@storybook/addon-postcss',
      options: {
        postcssLoaderOptions: {
          implementation: require('postcss'),
        }
      }
    }
  ],
  webpackFinal: async (config, { configType }) => {
    // `configType` has a value of 'DEVELOPMENT' or 'PRODUCTION'
    // You can change the configuration based on that.
    // 'PRODUCTION' is used when building the static version of storybook.

    // Make whatever fine-grained changes you need

    config.module.rules.push({
      test: /\.scss$/,
      exclude: /\.module\.scss$/,
      loaders: [
        require.resolve('style-loader'),
        {
          loader: require.resolve('css-loader'),
          options: {
            importLoaders: 2,
            modules: false
          }
        },
        require.resolve('sass-loader'),
      ]
    });

    config.module.rules.push({
      test: /\.module\.scss$/,
      loaders: [
        require.resolve('style-loader'),
        {
          loader: require.resolve('css-loader'),
          options: {
            importLoaders: 2,
            modules: {
              localIdentName: "[name]__[local]___[hash:base64:5]",
            },
          },
        },
        require.resolve('sass-loader'),
      ],
    });

    config.resolve.alias = {
      'app': path.resolve(__dirname, '../src/'),

      'lodash': 'lodash-es',
      'lodash.debounce': 'lodash-es/debounce',
      'lodash.throttle': 'lodash-es/throttle',

      'react-dom': configType === 'DEVELOPMENT' ? '@hot-loader/react-dom' : 'react-dom'
    };

    // Return the altered config
    return config;
  },
};

## index.stories.tsx 

import React from 'react';

import { Story, Meta } from '@storybook/react';

import RadioButton, { RadioButtonProps } from 'app/design-system/components/RadioButton';

import { LabelSize } from 'app/design-system/types/Label';

import StoryContainer, { SANDBOX_WIDTH_OPTIONS } from '../../../helpers/StoryContainer';


export default {
  title: 'Дизайн-система / Атомы / РадиоКнопка',
  component: RadioButton,
  argTypes: {
    labelSize: {
      defaultValue: LabelSize.DEFAULT,
      control: {
        type: 'select',
        options: LabelSize,
      },
    },
    label: {
      name: 'текст РадиоКнопки',
    },
    disabled: {
      defaultValue: false,
      control: {
        type: 'boolean',
      },
    },
    checked: {
      defaultValue: false,
      control: {
        type: 'boolean',
      },
    },
    onChange: {
      table: {
        disable: true,
      },
      action: 'changed',
    },
  },
} as Meta;

const Sandbox: Story<RadioButtonProps> = (args) => (
  <RadioButton { ...args } />
);

export const Template = Sandbox.bind({});
Template.storyName = 'Песочница';

Template.args = {
  label: 'teams',
};

Template.decorators = [(Story) => (
  <StoryContainer widthOptions={SANDBOX_WIDTH_OPTIONS}>
    {Story()}
  </StoryContainer>
)];

**Comment by maeriens** [comment]
You did not provide the `npx sb@next info` output so I don't know the versions you are using. But I run `npm init -y && npm i react@16 react-dom@16 && npx sb init`, copied both your `main.js` and `index.stories.tsx`; commented all the component imports and did a simple radio button that received the props (in plain js, I don't know much about ts) and it works.

The issue seems to be in the used components, not in storybook. Attached gif to show the outcome.
![Kapture 2021-07-25 at 15 00 20](https://user-images.githubusercontent.com/5074186/126908827-c082fc63-16d2-43b0-8b50-6125ccb0c5d2.gif)

**Comment by nodir-sulaymonov** [comment]
@maeriens 
![image](https://user-images.githubusercontent.com/20314452/126909915-86e44ed8-fb23-4036-a466-2d5a17e7ec73.png)

**Comment by maeriens** [comment]
Please check the components. I tried with a simple toggle and it worked ok.

**Comment by shilman** [comment]
@nodir-sulaymonov here's the right way to provide a reproduction: https://storybook.js.org/docs/react/contribute/how-to-reproduce

**Comment by nodir-sulaymonov** [comment]
@maeriens This is my toggle component 

import React, { FC, ChangeEvent } from 'react';
import classNames from 'classnames';

import withMouseDownCb, { PreventDefaultMouseDownProps } from '../withMouseDownCbHoc';

import { ToggleSize } from '../../types/Toggle';

import styles from './Toggle.module.scss';

// --

export { ToggleSize };

// --

export type ToggleProps = {
  active: boolean;
  onChange: (event: ChangeEvent<HTMLInputElement>) => void;
  disabled?: boolean;
  className?: string;
  name?: string;
  size?: ToggleSize;
};

const Toggle: FC<ToggleProps & PreventDefaultMouseDownProps> = ({
  active = false,
  disabled = false,
  size = ToggleSize.LARGE,
  className,
  name,
  onChange,
  onMouseDown,
}) => {
  const _className = classNames(
    styles.container,
    styles[`${size}Container`],
    {
      [styles.active]: active,
      [styles.disabled]: disabled,
    },
    className,
  );

  return (
    <div className={_className}
         onMouseDown={onMouseDown}>
      <input type="checkbox"
             name={name}
             disabled={disabled}
             className={styles.input}
             onChange={onChange} />
      <span className={`${styles.button} ${styles[`${size}Button`]}`} />
    </div>
  );
};

export default withMouseDownCb(Toggle);

**Comment by nodir-sulaymonov** [comment]
@maeriens 
    I removed these addons  the storybook started, but when I add them, this error appears. (The above error occurred in one of React components).
    "@storybook/addon-docs",
    "@storybook/addon-actions",
    "@storybook/addon-backgrounds",
    "@storybook/addon-knobs",
    "@storybook/addon-viewport",
    "storybook-addon-designs",
    "storybook-addon-i18next",
    
  It is now launched with these addons.
  
     "@storybook/addon-links",
    "@storybook/addon-essentials",
    

https://user-images.githubusercontent.com/20314452/126971709-293edd13-c3f7-4f0a-81ff-0251f8fa2b62.mp4

**Comment by nodir-sulaymonov** [comment]
I solved the problem. It was necessary to update the react-dom:"17.0.2". Remove node-modules and do yarn-install.
