### ISSUE TITLE
Storybook 6.3 stopped respecting some custom reactDocgenTypescriptOptions

### ISSUE THREAD

**Issue by zhzz** [storybookjs/storybook#15392]
Hello.

I've discovered that after updating from 6.2.9 to 6.3.0.

**Describe the bug**
Specifing custom values for some docgen options (according to the [docs](https://github.com/storybookjs/storybook/blob/next/docs/configure/typescript.md#mainjs-configuration)) isn't working any more. E.g. `setDisplayName: false` has no effect. 

**To Reproduce**
Sorry, I don't know how to reproduce it outside of my project. But you can see in the [storybook's code](https://npmfs.com/package/@storybook/react-docgen-typescript-plugin/1.0.2-canary.f7e28c0.0/dist/plugin.js#L215-L217) that some values are hardcoded now. Changing these lines fixes my issue.

**System**
```
  System:
    OS: Linux 4.19 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  Binaries:
    Node: 14.15.3 - ~/.config/nvm/14.15.3/bin/node
    Yarn: 1.22.4 - /mnt/c/Program Files (x86)/Yarn/bin/yarn
    npm: 6.14.9 - ~/.config/nvm/14.15.3/bin/npm
```

**Additional context**
The bug has two levels: these hardcoded values and another bug with custom options in [react-docgen-typescript-plugin@1.0.0](https://github.com/hipstersmoothie/react-docgen-typescript-plugin/pull/49). Since 6.3 uses the fork `@storybook/react-docgen-typescript-plugin`, it has to address both of them. 

BTW, can't find the source of `@storybook/react-docgen-typescript-plugin` to send a PR.

**Comment by Naoto-Ida** [comment]
I noticed this too. Going from `6.2.9` to `6.3.0`, the `setDisplayName` seems to not work.

In our case, we have compound components like this:
```
<Card>
  <Card.Header>I'm a header</Card.Header>
</Card>
```

where a `Header` component set as `Card.Header` has an explicit displayName set as `Card.Header`.

Now the code tab started showing:
```
<Card>
  <Header>I'm a header</Header>
</Card>
```

**Comment by shilman** [comment]
Please PR a fix to `react-docgen-typescript-plugin` if you have one. `@storybook/react-docgen-typescript-plugin` is a temporary fork until a new version of `react-docgen-typescript-plugin` gets released with some of our fixes included.

**Comment by zhzz** [comment]
@shilman have already done! https://github.com/hipstersmoothie/react-docgen-typescript-plugin/pull/49

**Comment by shilman** [comment]
@zhzz Nice! I don't know when that will be released, but when it is we'll upgrade our dependency. Thanks!!!

**Comment by zhzz** [comment]
Hi, @shilman, the PR has been [merged and released](https://github.com/hipstersmoothie/react-docgen-typescript-plugin/pull/49#issuecomment-1074094056)!
