### ISSUE TITLE
Storybook doesn't recognize what's new in next/image.

### ISSUE THREAD

**Issue by soulcactus** [storybookjs/storybook#15407]
**Describe the bug**
The next/image no longer requires width, height, layout="fill" when accessing the public directory. (next 11) But the storybook doesn't seem to recognize this.

`Image with src "..." must use "width" and "height" properties or "layout='fill'" property.`

**System**
Environment Info:

  System:
    OS: macOS 11.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 14.15.4 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.10 - /usr/local/bin/npm
  Browsers:
    Chrome: 91.0.4472.114
    Firefox: 87.0
    Safari: 14.1.1
  npmPackages:
    @storybook/addon-actions: ^6.4.0-alpha.5 => 6.4.0-alpha.5 
    @storybook/addon-essentials: ^6.4.0-alpha.5 => 6.4.0-alpha.5 
    @storybook/addon-links: ^6.4.0-alpha.5 => 6.4.0-alpha.5 
    @storybook/react: ^6.4.0-alpha.5 => 6.4.0-alpha.5

**Comment by shilman** [comment]
@eric-burel any idea what it would take to provide this support?

**Comment by eric-burel** [comment]
As next/image is a component that rely on a Next server running it should always be mocked in Storybook imo, you cannot really have it to work normally in Storybook.

Regarding this specific issue, are you sure of your app setup? Is the Next version right? Do you have TypeScript warnings etc.?

**Comment by soulcactus** [comment]
The next version of the project is as follows:
"next": "11.0.1"


I didn't use next/image often before because I didn't think next/image was a usable feature.
However, this version of next/image has improved significantly.
After reading this comments, I tested how Storybook renders the next/image of the previous version of the next project, just in case.
With next/image(major version 10), only alt messages are rendered in the storybook, but at least the error log does not appear.
However, the error log is being rendered in version 11.
Please refer to the screen capture image.

- next v10.1.3

```
/* ... */
import Image from 'next/image';
/* ... */
 <Image
    alt="test"
    src="/static/icons/buttons/delete.png"
    layout="fill"
 />
```

![스크린샷 2021-06-29 오후 10 31 05](https://user-images.githubusercontent.com/44562005/123807284-b0067880-d92a-11eb-8e74-4cbdf9e40d8f.png)



- next v11.0.1

```
/* ... */
import Image from 'next/image';
import Item from '../../public/static/icons/buttons/delete.png';
/* ... */
<Image alt="test" src={Item} />
```

![스크린샷 2021-06-29 오후 10 40 30](https://user-images.githubusercontent.com/44562005/123808623-e09ae200-d92b-11eb-888f-fc0c4ac67c2b.png)

**Comment by eric-burel** [comment]
As far as I can tell it's just Next doc that is not totally up to date so maybe it shows a non-working example (`<Image src={profilePic} alt="Picture of the author" />` without fill/width/height). 
You should trust the error message and define those props accorded. Don't you have the same error in your Next app?

I am going to close because that's most probably just a small documentation issue from Next side, but we can keep discussing.

**Comment by soulcactus** [comment]
This is not a documentation issue. It works well on Next app. This is a new feature.

![스크린샷 2021-06-30 오전 9 10 36](https://user-images.githubusercontent.com/44562005/123883135-58482b80-d983-11eb-996d-6e61cde15bca.png)

**Comment by shilman** [comment]
@soulcactus agreed. this is a nextjs feature, so ideally the nextjs integration for storybook provides this feature somehow. i can imagine a webpack loader/plugin that implements this somehow--not sure how it's implemented inside nextjs

**Comment by David-Rickard** [comment]
@eric-burel Could we reopen this since it's not a documentation issue? Ideally we would have storybook entries for all our components but that means it's impossible to make use of this new NextJS feature to leave off the image width/height/

**Comment by David-Rickard** [comment]
Issue on NextJS side https://github.com/vercel/next.js/discussions/33010

**Comment by David-Rickard** [comment]
Nevermind, this addon fixes it: https://storybook.js.org/addons/storybook-addon-next
