### ISSUE TITLE
Storybook adds actionHandler function to every function prop

### ISSUE THREAD

**Issue by allangrds** [storybookjs/storybook#15421]
**Describe the bug**
I have the following component:
```js
const Footer = ({ onBack, onFinish, onNext }: FooterProps) => {  
    return (
      <S.Wrapper>
        {onBack && (
          <div>
            <SecondaryButton
              backgroundColor="#fff"
              onClick={onNext}
              text="Voltar"
            />
          </div>
        )}
        {onNext && (
          <div>
            <Button onClick={onNext} text="Avançar" />
          </div>
        )}
        {onFinish && (
          <div>
            <Button onClick={onFinish} text="Finalizar" />
          </div>
        )}
      </S.Wrapper>
    );
  };
```

and my `Footer.stories.tsx`:
```js
import React from 'react';
import { Meta, Story } from '@storybook/react';

import Footer from '~/components/Footer';

export default {
  title: 'components/Footer',
  component: Footer,
} as Meta;

const Template: Story<any> = (args) => <Footer {...args} />

export const OnlyNext = Template.bind({})

OnlyNext.args = {
  onNext: () => null,
}
```

The problemn here is: I'm always seeing the 3 buttons, not just the button I prop in the story.

**System**
Environment Info:
  System:
    OS: macOS 11.4
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  Binaries:
    Node: 14.17.1 - ~/.nvm/versions/node/v14.17.1/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.17.1/bin/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.1/bin/npm
  Browsers:
    Chrome: 91.0.4472.114
    Firefox: 89.0.2
    Safari: 14.1.1
  npmPackages:
    @storybook/addon-actions: 6.3.0 => 6.3.0 
    @storybook/addon-essentials: 6.3.0 => 6.3.0 
    @storybook/addon-links: 6.3.0 => 6.3.0 
    @storybook/node-logger: 6.3.0 => 6.3.0 
    @storybook/preset-create-react-app: 3.1.7 => 3.1.7 
    @storybook/react: 6.3.0 => 6.3.0

**Comment by shilman** [comment]
Closing as dupe to https://github.com/storybookjs/storybook/issues/15370 which has been fixed in 6.3.1

**Comment by slinkardbrandon** [comment]
This appears to be broken again in 6.3.12

**Comment by brandonthomas** [comment]
Yah I'm still seeing this
