### ISSUE TITLE
Incremental build time increased drastically since v6.3

### ISSUE THREAD

**Issue by irudoy** [storybookjs/storybook#15423]
**Describe the bug**
Incremental build time was increased after updating to v6.3. It was about 4s and becomes about 15s.

**To Reproduce**
TBD

**System**
```
Environment Info:

  System:
    OS: macOS 11.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 14.17.0 - /usr/local/bin/node
    Yarn: 2.4.2 - /usr/local/bin/yarn
    npm: 6.14.13 - /usr/local/bin/npm
  Browsers:
    Chrome: 93.0.4549.4
    Edge: 91.0.864.59
    Safari: 14.1.1
```

**Additional context**
I can't create a reproduction for now, because it's quite tricky. But I'll try to describe the investigation that was done.

First of all, using SpeedMeasureWebpackPlugin was determined, that the culprit is [DocgenPlugin](https://github.com/hipstersmoothie/react-docgen-typescript-plugin):
```
 SMP  ⏱  Plugins
DocgenPlugin took 10.71 secs
```
Then I excluded it from the preview build, and incremental build time returned to normal ~4s. Great.

`react-docgen-typescript-plugin` [v0.6.2](https://github.com/storybookjs/storybook/blob/v6.2.9/lib/core-common/package.json#L92) was used in Stoybook v6.2.9. Storybook v6.3 depends on [v1.0.2-canary.XXX](https://github.com/storybookjs/storybook/blob/v6.3.1/lib/core-common/package.json#L93).

Running Storybook with `DEBUG=docgen:*` variable, I saw that it tries to match all 3000+ modules on each rebuild:
```
webpack building...
  docgen:exclude Module not matched in "include": /XXX/.yarn/$$virtual/XXX-0.0.0.zip/node_modules/main.js +0ms
  docgen:exclude Module not matched in "include": /XXX/.yarn/$$virtual/XXX-0.0.0.zip/node_modules/main.js +0ms
  docgen:exclude Module not matched in "include": /XXX/.yarn/cache/XXX-0.0.0.zip/node_modules/main.js +0ms
  ...
  docgen:exclude Module not matched in "include": /XXX/.yarn/$$virtual/XXX-0.0.0.zip/node_modules/main.js +0ms
  docgen:exclude Module not matched in "include": /XXX/.yarn/cache/XXX-0.0.0.zip/node_modules/main.js +0ms
  docgen:exclude Module not matched in "include": /XXX/.yarn/$$virtual/XXX-0.0.0.zip/node_modules/main.js +0ms
  docgen:exclude Module not matched in "include": /XXX/.yarn/unplugged/XXX-0.0.0.zip/node_modules/main.js +2ms
  ...
  docgen:exclude Module not matched in "include": /XXX/some/local/module/XXX +0ms
  docgen:exclude Module not matched in "include": /XXX/some/local/module/XXX +1ms
  docgen:exclude Module not matched in "include": /XXX/some/local/module/XXX +0ms
  ...
```

Downgraded to `react-docgen-typescript-plugin` and ran again with DEBUG option. It logs the same modules, but with other "reasons". And it goes fast (incremental build time is normal).
```
  docgen:exclude Ignoring un-built module: /XXX/.yarn/$$virtual/XXX-0.0.0.zip/node_modules/main.js +0ms
  ...
  docgen:exclude Ignoring un-built module: /XXX/.yarn/unplugged/XXX-0.0.0.zip/node_modules/main.js +2ms
  docgen:exclude Ignoring un-built module: /XXX/some/local/module/XXX +0ms
  ...
```

Seems like the reason is in this PR https://github.com/hipstersmoothie/react-docgen-typescript-plugin/pull/33
Prior to that, the iteration over modules was with a simple check for `!module.built`, and goes very fast. For now, it always matches with `micromatch`. I couldn't understand why those checks were removed, but maybe @bebraw help with it.

Hope this info will help. I can create a separate issue in the `react-docgen-typescript-plugin` repo if it needs to.

**Comment by bebraw** [comment]
> Prior to that, the iteration over modules was with a simple check for !module.built, and goes very fast. For now, it always matches with micromatch. I couldn't understand why those checks were removed, but maybe @bebraw help with it.

Ah, I see now. I missed that check for the new webpack 5 portion. Thanks for bringing this up, I'll add the check there.

**Comment by irudoy** [comment]
![image](https://user-images.githubusercontent.com/5372690/123844247-21a7ec00-d956-11eb-9137-0266e2f0e92b.png)

It turned out not so optional 😄

**Comment by bebraw** [comment]
> It turned out not so optional 😄

Yeah. That said, testing recompilation time is tough.

The problem here is that the checks in code are webpack 4 specific so we'll need to find a way to do the same for webpack 5 to maintain compatibility. I found an easy fix for webpack 4 but webpack 5 is unclear at the moment.

**Comment by bebraw** [comment]
It looks like [module.built was removed in webpack 5](https://webpack.js.org/blog/2020-10-10-webpack-5-release/#other-minor-changes) so we cannot use that anymore. If someone knows what replaced it, please let me know.

**Comment by irudoy** [comment]
> I found an easy fix for webpack 4 but webpack 5 is unclear at the moment.

Totally agree. Low-level webpack API have a lack of documentation. And this kind of task always requires deep dive into webpack sources, unfortunately.

**Comment by irudoy** [comment]
> It looks like module.built was removed in webpack 5 so we cannot use that anymore. If someone knows what replaced it, please let me know.

Maybe @alexander-akait can point out how to do this with webpack 5

**Comment by alexander-akait** [comment]
https://github.com/webpack/webpack/pull/7933

> module.built has be removed in favor of Compilation.builtModules

:star:

**Comment by bebraw** [comment]
Ok, here's a PR to test: https://github.com/hipstersmoothie/react-docgen-typescript-plugin/pull/50 .

**Comment by irudoy** [comment]
Confirmed, it works as expected, in case of "un-built modules". Thanks, @bebraw!
Got [this](https://github.com/hipstersmoothie/react-docgen-typescript-plugin/issues/42) issue while testing, and updating `react-docgen-typescript` to v2.0.0 helped.

What do you think about other cases (`module.external`, `module.rawRequest`)? Maybe it should be handled as well for webpack 5?

**Comment by bebraw** [comment]
> What do you think about other cases (module.external, module.rawRequest)? Maybe it should be handled as well for webpack 5?

That's a good point.

@alexander-akait Do you know the webpack 5 equivalents for these two? It's probably best I add webpack 5 specific checks for these two to be complete.

**Comment by alexander-akait** [comment]
hm, I think they are same for webpack v5

**Comment by bebraw** [comment]
Ok, I'll keep the code as it is then. Maybe it's just the `Module` type that's missing these two.
