### ISSUE TITLE
Toolbar decorator remounts component when dismiss

### ISSUE THREAD

**Issue by y-nk** [storybookjs/storybook#15429]
**Describe the bug**
Story gets unmounted/remounted even **when dismissing** the pick of a choice in the toolbar addon

![Screen Recording 2021-06-30 at 09 43 13 AM](https://user-images.githubusercontent.com/411625/123894236-0524a780-d988-11eb-80fc-e50ea5c82759.gif)

**To Reproduce**

- Create a new storybook instance
- Add the code related to language selection as provided in the docs
- Add a console.log in your component or story

**System**
```
Environment Info:

  System:
    OS: macOS 11.4
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
  Binaries:
    Node: 16.4.0 - ~/.nvm/versions/node/v16.4.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 7.18.1 - ~/.nvm/versions/node/v16.4.0/bin/npm
  Browsers:
    Chrome: 91.0.4472.114
    Firefox: 88.0.1
    Safari: 14.1.1
```

**Additional context**
Probably related to #15416

**Comment by shilman** [comment]
@IgorSzyporyn can you please take a quick look at this one? 🙏

**Comment by IgorSzyporyn** [comment]
> @IgorSzyporyn can you please take a quick look at this one? 🙏

Will do first thing in the morning

**Comment by IgorSzyporyn** [comment]
@y-nk 

Can you share your component and story - testing in official-storybook I am not getting my console logged out

**Comment by IgorSzyporyn** [comment]
https://user-images.githubusercontent.com/6172338/124085273-2650cb00-da50-11eb-907d-0f265468536f.mp4

**Comment by IgorSzyporyn** [comment]
@y-nk 

I have written you on discord also
