### ISSUE TITLE
storybook/html is using an outdated version of React

### ISSUE THREAD

**Issue by stof** [storybookjs/storybook#15437]
**Is your feature request related to a problem? Please describe**
the `@storybook/html` package depends on react 16.14.0, while the latest version is react 17

**Describe the solution you'd like**
It would be great if react 17 could be used here, to be on a maintained version

**Describe alternatives you've considered**

**Are you able to assist to bring the feature to reality?**

**Additional context**

**Comment by ndelangen** [comment]
Fixed in 7.0 beta
