### ISSUE TITLE
Automatically exposing stories problem

### ISSUE THREAD

**Issue by mitow7821** [storybookjs/storybook#15435]
**Describe the bug**
I have chart story where I want to dynamically get args and file names from other folder and then I create story for each of them. Here is my code:

![image](https://user-images.githubusercontent.com/34492112/123933693-e677de00-d992-11eb-9a82-51f1d8fd675d.png)

When I run storybook localy everything works fine, but while trying to build with chromatic I am getting this message: 

![image](https://user-images.githubusercontent.com/34492112/123934010-2ccd3d00-d993-11eb-81bc-c475f4eea1bc.png)

The problem is related to export part.
Is it beacuse of destructuring assigment? How could I export stories to make it work on production?

**To Reproduce**
Use one of expample stories.
Extract args to separated file, export them and import in story.
Create stories and assign them in object.
Use that object to export destructuring assigment.

**System**
Windows 10
NPM VERSION: 
6.14.13
NODE VERSION:
14.17
"@storybook/addon-actions": "^6.3.1",
"@storybook/addon-essentials": "^6.3.1",
"@storybook/addon-links": "^6.3.1",
"@storybook/vue3": "^6.3.1",
vite-storybook-builder - 0.0.10

**Comment by angelov-a** [comment]
Hello, @mitow7821!

Have you managed to fix it? I'm facing the same issue.

**Comment by shilman** [comment]
Duplicate to #9828
