### ISSUE TITLE
A11y addon: Reverse the label and description content in the Accordion

### ISSUE THREAD

**Issue by MichaelArestad** [storybookjs/storybook#15445]
## Problem
1. The most clear and concise description of an A11y test is hidden until the accordion is open.
1. Many, if not all, of the current labels in the AccordionHeader start with "Ensures" making it more difficult to scan and is slightly confusing.

## Proposal
I believe both the AccordionHeader content and the description content are provided via an API so I don't want to edit the copy. Instead, I propose we swap where each bit of copy is located. You can see my proposal in the above image.

![A11y - labels](https://user-images.githubusercontent.com/1123119/124010282-df090280-d99b-11eb-8c92-26c25b1f56c9.jpg)

**Are you able to assist to bring the feature to reality?**
Yep!

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200539748475788/1200550414109775) by [Unito](https://www.unito.io)

**Comment by harshsingh941** [comment]
I like to work on this project .So can i start ??

**Comment by MichaelArestad** [comment]
@harshsingh941 Please! I will be happy to review.

**Comment by harshsingh941** [comment]
I am working on this for the first time . So I am not able to locate where this labels are in the code can you help me?

**Comment by MichaelArestad** [comment]
@harshsingh941 I'm sorry for the slow response. There is a PR open that you can look at to see where the labels are: https://github.com/storybookjs/storybook/pull/15466

**Comment by MichaelArestad** [comment]
Fixed in #15466

**Comment by shilman** [comment]
Jiminy cricket!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-alpha.11 containing PR #15466 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
