### ISSUE TITLE
Cannot run Storybook in 6.3.2

### ISSUE THREAD

**Issue by kaili-kameoka** [storybookjs/storybook#15447]
**Describe the bug**
Running `npm run storybook` opens to a blank page with 3 initial 404 errors. A refresh shows that the missing files are a main and vendor js file.

**To Reproduce**
```(shell)
npx create-react-app storybook-test
cd storybook-test
npx sb init
npm run storybook
```
I didn't touch any code.
 
**System**
System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-4288U CPU @ 2.60GHz
  Binaries:
    Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
    npm: 7.16.0 - ~/.nvm/versions/node/v14.16.0/bin/npm
  Browsers:
    Chrome: 91.0.4472.114
    Safari: 14.1.1
  npmPackages:
    @storybook/addon-actions: ^6.3.2 => 6.3.2
    @storybook/addon-essentials: ^6.3.2 => 6.3.2
    @storybook/addon-links: ^6.3.2 => 6.3.2
    @storybook/node-logger: ^6.3.2 => 6.3.2
    @storybook/preset-create-react-app: ^3.1.7 => 3.1.7
    @storybook/react: ^6.3.2 => 6.3.2

**Additional context**
I noticed the bug earlier today when working on a client's project and was able to reproduce a simpler version of the project described above.

**Comment by mitow7821** [comment]
Changing port is temporary solve of this issue.
Idk why after each update I cant use previously used ports eg. 6006, 6007 ...

**Comment by shilman** [comment]
Can't reproduce. Is there something else running on those ports on your machine?

**Comment by mitow7821** [comment]
Ports are not used, this bug is unpredictable sometimes default port 6006 work and other times it isn't.
Doesn't have clue how to reproduce this :o

**Comment by shilman** [comment]
@mitow7821 what happens when you browse in incognito mode?

**Comment by mitow7821** [comment]
@shilman then it works, i've checked other browser and it runs too. In my case this problem is related only to chrome

**Comment by steve-taylor-medirecords** [comment]
It randomly stopped working for me. The `Content-Length` of the request to `/` is `0`. I hadn't changed any dependencies. I tried deleting all browser storage, running in incognito, changing ports, etc., rolling back to previous commits, rebooting my machine. All to no avail. Does it have a dependency on a web service that's currently down? That's the only thing I can think of to explain it.

**Comment by steve-taylor** [comment]
It randomly stopped working for me. The `Content-Length` of the request to `/` is `0`. I hadn't changed any dependencies. I tried deleting all browser storage, running in incognito, changing ports, etc., rolling back to previous commits, rebooting my machine. All to no avail. Does it have a dependency on a web service that's currently down? That's the only thing I can think of to explain it.

**Comment by hypervillain** [comment]
@steve-taylor `--no-manager-cache` fixed it for me!
