### ISSUE TITLE
Error: Node TemplateLiteralType was unexpected

### ISSUE THREAD

**Issue by DerZyklop** [storybookjs/storybook#15454]
**Describe the bug**
As soon as i use a so-called [Template Literal Type](https://www.typescriptlang.org/docs/handbook/2/template-literal-types.html) (a TypeScript 4.2 feature) in one of my components, storybook can not load it and gets errors.

**To Reproduce**
Create project.
- Angular 12.1.1
- TS 4.2.4
- Storybook 6.3.2

Write this in any component:

```
enum ThemeEnum {
  DANGER = 'danger',
  SUCCESS = 'success',
}
const theme : ThemeEnum | `${ThemeEnum}` = 'danger';
```

**Additional context**
Errors look like this: 
```
Unexpected error while loading ./path/foo.component.stories.ts: Error: Module build failed (from ./node_modules/ts-loader/index.js):
Error: Debug Failure. Unexpected node.
Node TemplateLiteralType was unexpected.
```

**Comment by ndelangen** [comment]
Do you have more info on the error? A stack trace?

The more you can share about your setup and what you did that resulted in this the better we're able to assist.

**Comment by shilman** [comment]
I'm guessing that we need to do some dependency upgrades on our side since this is a brand new feature  in Typescript and I don' think we're up to date.

**Comment by JSMike** [comment]
@shilman looks like storybook is still using `"typescript": "^3.9.7"` this feature came out in TypeScript 4.1 https://devblogs.microsoft.com/typescript/announcing-typescript-4-1/ 
Do you have a timeline on updating the TypeScript version?

**Comment by JSMike** [comment]
Ok, FYI, Angular 12 requires TypeScript 4.2, and Angular 13 requires TypeScript 4.4. Anyone looking to take advantage of new TypeScript features in their Angular projects will run into this type of issue when Storybook builds.
