### ISSUE TITLE
Controls: type function is not infered when using imported types

### ISSUE THREAD

**Issue by MarcusNotheis** [storybookjs/storybook#15452]
**Describe the bug**
We are using TypeScript and MDX Stories in our React project. Our event handlers are typed as `MouseEventHandler` (imported from `@types/react`). I would expect, that the controls for those handlers are disabled.

Button.tsx:
```tsx
import React, { MouseEventHandler } from 'react';

interface ButtonPropTypes {
  /**
   * Optional click handler. Control is not infered
   */
  onClick: MouseEventHandler<HTMLButtonElement>;

  /**
   * Another handler, control is infered correctly
   */
  onAnotherThing?: () => void;
}

export const Button = (props : ButtonPropTypes) => {
// ....
```

Story:
![image](https://user-images.githubusercontent.com/8775211/124132691-5d8ba000-da81-11eb-8b2a-8c3af0f59897.png)

**To Reproduce**
https://github.com/MarcusNotheis/storybook-infer-control-repro

**System**
```
Environment Info:

  System:
    OS: macOS 11.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 16.4.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.18.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 91.0.4472.114
    Edge: 91.0.864.59
    Firefox: 88.0.1
    Safari: 14.1.1
  npmPackages:
    @storybook/addon-actions: ^6.3.2 => 6.3.2 
    @storybook/addon-essentials: ^6.3.2 => 6.3.2 
    @storybook/addon-links: ^6.3.2 => 6.3.2 
    @storybook/node-logger: ^6.3.2 => 6.3.2 
    @storybook/preset-create-react-app: ^3.1.7 => 3.1.7 
    @storybook/react: ^6.3.2 => 6.3.2 
```
**Additional Context**
Maybe this is related to https://github.com/storybookjs/storybook/issues/12558?

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid.

Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
