### ISSUE TITLE
Incorrect formatting of single line code blocks since 6.3

### ISSUE THREAD

**Issue by pouretrebelle** [storybookjs/storybook#15458]
**Describe the bug**

Since 6.3, when adding a code block in a React component description it's only formatted if it contains more than one line of code.

**To Reproduce**

https://github.com/pouretrebelle/sb-syntax-highlight-bug-repro/commit/a9f5f9cac71129a244d9e6d5f0716f7c3f603b7d
Branches for 6.2.9 and 6.3.0

## 6.2.9
![image](https://user-images.githubusercontent.com/1901935/124157658-e958f880-da90-11eb-91b8-e3dfc9327e68.png)

## 6.3.0
![image](https://user-images.githubusercontent.com/1901935/124157920-38069280-da91-11eb-8d84-d3f6fd8a6915.png)

In an .mdx file it formats and highlights as expected:

![image](https://user-images.githubusercontent.com/1901935/124158425-ced34f00-da91-11eb-86fd-79288152d9e6.png)

**System**

Environment Info:

  System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
  Binaries:
    Node: 12.20.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 2.4.2 - C:\Program Files\nodejs\yarn.CMD
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1023.0), Chromium (91.0.864.59)
  npmPackages:
    @storybook/addon-actions: 6.3.0 => 6.3.0
    @storybook/addon-docs: 6.3.0 => 6.3.0
    @storybook/addon-essentials: 6.3.0 => 6.3.0
    @storybook/addon-links: 6.3.0 => 6.3.0
    @storybook/node-logger: 6.3.0 => 6.3.0
    @storybook/preset-create-react-app: ^3.1.7 => 3.1.7
    @storybook/react: 6.3.0 => 6.3.0
  npmGlobalPackages:
    @storybook/codemod: 6.2.9

**Additional context**

Issue still present in 6.3.2

**Comment by alk-mandrianarijaona** [comment]
Hello, I can take this one

**Comment by alk-mandrianarijaona** [comment]
I see this is related ti changes on https://github.com/storybookjs/storybook/pull/14495

**Comment by shilman** [comment]
@TheMightyPenguin is this something you can take a look at? ☝️

**Comment by TheMightyPenguin** [comment]
@shilman definitely, I can take this one

**Comment by alk-mandrianarijaona** [comment]
@TheMightyPenguin I have made a PR for this, wdyt https://github.com/storybookjs/storybook/pull/15554 ?

**Comment by TheMightyPenguin** [comment]
@alk-mandrianarijaona ah great, let me take a look!

**Comment by DaveLak** [comment]
FYI @shilman [it looks like this issue was resolved](https://github.com/storybookjs/storybook/pull/15554#discussion_r791936330) by some other changes while #15554 was in progress. This can probably be closed as completed.

**Comment by shilman** [comment]
Thanks @DaveLak I think you're right. Closing!
