### ISSUE TITLE
Angular example stories seems not like real Angular examples

### ISSUE THREAD

**Issue by kbrilla** [storybookjs/storybook#15469]
Right now Angular stories and especially ng-content example like list story seems like they are not real world examples.
For example here we have example how to use props form other stories, it makes sense for React where you just spread arguments or in Vue where it will auto bind those to correct inputs. But in Angular You have to go and bind those individually so story like this:
```typescript
// List.stories.ts

//👇 We're importing the necessary stories from ListItem
import { Selected, Unselected } from './ListItem.stories';

export const ManyItems: Story<List> = (args) => ({
  props: args,
  template: `
    <app-list>
      <app-listitem [itemProperty]="Selected"></app-listitem>
      <app-listitem [itemProperty]="Unselected"></app-listitemm>
      <app-listitem[itemProperty]="Unselected"></app-listitem>
    </app-list>`,
});
ManyItems.args= {
  Selected: Selected.args.itemProperty,
  Unselected: Unselected.args.itemProperty,
};
```

should look more like this:
```typescript
// List.stories.ts

//👇 We're importing the necessary stories from ListItem
import { Selected, Unselected } from './ListItem.stories';

export const ManyItems: Story<List> = (args) => ({
  props: args,
  template: `
    <app-list>
      <app-listitem [itemProperty1]="Selected.itemProperty1 [itemProperty2]="Selected.itemProperty2"></app-listitem>
      <app-listitem [itemProperty1]="Unselected.itemProperty1 [itemProperty2]="Unselected.itemProperty2"></app-listitemm>
      <app-listitem [itemProperty1]="Unselected.itemProperty1 [itemProperty2]="Unselected.itemProperty2"></app-listitem>
    </app-list>`,
});
ManyItems.args= {
  Selected: Selected.args.itemProperties,
  Unselected: Unselected.args.itemProperties,
};
```

Also if storybook documentation is written to use stories, why not embed working stories in there? So we would have actual working stories as examples.

**Comment by jonniebigodes** [comment]
@criskrzysiu going to break down your question into two parts, starting with the question about the story and args.
I've set up a simple demonstration to provide you with some context. Here's what I did:
- Ran `npx degit chromaui/intro-storybook-angular-template example-angular`, to generate a simple Angular application with Storybook (running the latest stable version of Storybook).
- Cleaned up `src/styles.css` to get rid of the provided styles.
- Ran `npm install` to install the dependencies.
- While it was running the installation process, I created a couple of components. More specifically `list.component.ts` with the following inside:
```ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-list',
  template: ` <div>
    <h1>I'm the list</h1>
    <ng-content></ng-content>
  </div>`,
})
export default class List {}
```
And `list-item.component` with the following:
```ts
import { Component, Input } from '@angular/core';
@Component({
  selector: 'app-listitem',
  template: ` <div>
    <h1>I'm a list Item</h1>
    <h2>Am i selected?</h2>
    <h3>{{ itemProperty ? 'yes' : 'no' }}</h3>
  </div>`,
})
export default class ListItem {
  @Input()
  itemProperty = false;
}
```

Both components are simple extrapolations to follow up on the documentation and provide some context.

Moving on.


- Created associated stories for both components. Starting with `list-item.stories.ts`:
```ts
import { moduleMetadata, Story, Meta } from '@storybook/angular';

import { CommonModule } from '@angular/common';

import ListItem from './list-item.component';

export default {
  component: ListItem,
  decorators: [
    moduleMetadata({
      declarations: [ListItem],
      imports: [CommonModule],
    }),
  ],
  title: 'ListItem',
} as Meta;

const Template: Story<ListItem> = (args) => ({
  props: {
    ...args,
  },
});

export const Selected = Template.bind({});
Selected.args = {
  itemProperty: true,
};

export const Unselected = Template.bind({});
Unselected.args = {
  itemProperty: false,
};
```
And `list.stories.ts` with the following:
```ts
import { moduleMetadata, Story, Meta } from '@storybook/angular';

import { CommonModule } from '@angular/common';

import List from './list.component';
import ListItem from './list-item.component';

import { Selected, Unselected } from './list-item.stories';

export default {
  component: List,
  decorators: [
    moduleMetadata({
      declarations: [List, ListItem],
      imports: [CommonModule],
    }),
  ],
  title: 'List',
} as Meta;

export const Empty: Story<List> = (args) => ({
  props: args,
  template: `<app-list></app-list>`,
});

export const OneItem: Story<List> = (args) => ({
  props: args,
  template: `
    <app-list>
      <app-listitem></app-listitem>
    </app-list>`,
});

export const ManyItems: Story<List> = (args) => ({
  props: args,
  template: `
    <app-list>
      <app-listitem></app-listitem>
      <app-listitem></app-listitem>
      <app-listitem></app-listitem>
    </app-list>`,
});

export const VariousArgItems: Story<List> = (args) => ({
  props: args,
  template: `
    <app-list>
      <app-listitem [itemProperty]="Selected"></app-listitem>
      <app-listitem [itemProperty]="Unselected"></app-listitem>
      <app-listitem [itemProperty]="Unselected"></app-listitem>
    </app-list>`,
});
VariousArgItems.args = {
  Selected: Selected.args.itemProperty,
  Unselected: Unselected.args.itemProperty,
};
```
- Ran `npm run storybook` to spin up Storybook in development mode and it yielded the following:


https://user-images.githubusercontent.com/22988955/127717065-c2e60139-cce4-4c81-aa19-dafcbd63c81e.mp4

As you can see the intended behavior is applied. We're using a custom template to render not only the list component but also a list-item component that contains a property (i.e., itemProperty, which could be called something entirely differently). Which is supplied to the story by importing them from another separate story,  injected as props in the component. Allowing you to keep a bit of a clean separation of code and avoiding having to write down similar code.

- Went a little further and adjusted the `list-item.component.ts`, `list-item.stories.ts` and `list.stories.ts` to the following:
```ts
import { Component, Input } from '@angular/core';
@Component({
  selector: 'app-listitem',
  template: ` <div>
    <h1>I'm a list Item</h1>
    <h2>Am i selected?</h2>
    <h3>{{ itemProperty ? 'yes' : 'no' }}</h3>
    <h3>The value of someOtherProperty is </h3>
    <h4>{{someOtherProperty}}</h4>
  </div>`,
})
export default class ListItem {
  @Input()
  itemProperty = false;
 
  @Input()
  someOtherProperty= 'Something else';
}
```
```ts
import { moduleMetadata, Story, Meta } from '@storybook/angular';

import { CommonModule } from '@angular/common';

import ListItem from './list-item.component';

export default {
  component: ListItem,
  decorators: [
    moduleMetadata({
      declarations: [ListItem],
      imports: [CommonModule],
    }),
  ],
  title: 'ListItem',
} as Meta;

const Template: Story<ListItem> = (args) => ({
  props: {
    ...args,
  },
});

export const Selected = Template.bind({});
Selected.args = {
  itemProperty: true,
  someOtherProperty:'One'
};

export const Unselected = Template.bind({});
Unselected.args = {
  itemProperty: false,
  someOtherProperty:'Two'
};
```
```ts
import { moduleMetadata, Story, Meta } from '@storybook/angular';

import { CommonModule } from '@angular/common';

import List from './list.component';
import ListItem from './list-item.component';

import { Selected, Unselected } from './list-item.stories';

export default {
  component: List,
  decorators: [
    moduleMetadata({
      declarations: [List, ListItem],
      imports: [CommonModule],
    }),
  ],
  title: 'List',
} as Meta;

export const Empty: Story<List> = (args) => ({
  props: args,
  template: `<app-list></app-list>`,
});

export const OneItem: Story<List> = (args) => ({
  props: args,
  template: `
    <app-list>
      <app-listitem></app-listitem>
    </app-list>`,
});

export const ManyItems: Story<List> = (args) => ({
  props: args,
  template: `
    <app-list>
      <app-listitem></app-listitem>
      <app-listitem></app-listitem>
      <app-listitem></app-listitem>
    </app-list>`,
});

export const VariousArgItems: Story<List> = (args) => ({
  props: args,
  template: `
    <app-list>
      <app-listitem [itemProperty]="Selected" [someOtherProperty]="AnotherProperty"></app-listitem>
      <app-listitem [itemProperty]="Unselected"></app-listitem>
      <app-listitem [itemProperty]="Unselected"></app-listitem>
    </app-list>`,
});
VariousArgItems.args = {
  Selected: Selected.args.itemProperty,
  Unselected: Unselected.args.itemProperty,
  AnotherProperty:Selected.args.someOtherProperty
};
```
With this update Storybook now yields:
![Storybook-angular-twoprops](https://user-images.githubusercontent.com/22988955/127718052-9c6cf11e-5ff3-4dbd-87b9-0a2d8c4f2f64.png)


For this particular case, as we're using `ng-content` with child items, I'm well aware that this can easily get out of hand easily. When applying to your own Storybook, be mindful of the component's inputs to avoid this type of scenario. Probably use some type of structure for it. 


Regarding your other question, more specifically:
>Also if storybook documentation is written to use stories, why not embed working stories in there? So we would have actual working stories as examples.

This is something that I've been trying to set up with the documentation and tutorials, allowing you to see not only the story and the component as well. Did some preliminary tests with a couple of services but with each approach came some issues associated with it. Hopefully, somewhere down the line, we can provide you and the rest of the community with a good approach to this item. 

Feel free to provide feedback on this issue if you have further questions and I'll gladly follow up with you.

Stay safe.

**Comment by joshharbaugh** [comment]
@jonniebigodes I'm following the examples I've found with regard to using `ng-content`, but when my component renders in Storybook, the Canvas is blank until I change one of the properties in the Controls below (then the component renders as expected).

`
import { Story, Meta } from '@storybook/angular/types-6-0';
import { componentWrapperDecorator, moduleMetadata } from '@storybook/angular';

import { DefinitionRowComponent } from './definition-row.component';
import { CommonModule } from '@angular/common';

export default {
  component: DefinitionRowComponent,
  decorators: [
    moduleMetadata({
      declarations: [DefinitionRowComponent],
      imports: [CommonModule],
    }),
  ],
  title: 'Components/Definition Row',
} as Meta;

export const WithContent: Story<DefinitionRowComponent> = (args) => ({
  props: args,
  template: `
    <app-definition-row>
      should render in ng-content
    </app-definition-row>`,
});
WithContent.args = {
  definition: {
    id: 1,
    name: 'gender',
    guid: 'gender-guid-1',
    type: 'datum',
  },
  selected: false,
};
`

Any idea why this is the case. Appears tied to `template`. If I exclude it, I do see the component rendered (without having to change a property first), but obviously, the `ng-content` within the Angular component is ignored completely.

**Comment by jonniebigodes** [comment]
@joshharbaugh no worries. Glad that you managed to solve it. Feel free to reach out to us with any issues with Storybook. Either here in the issue tracker or on our Discord Server.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if this is still relevant in SB 7.x.
