### ISSUE TITLE
@addon/docs: Angular numeric property with default value 0 is undefined and can't be changed

### ISSUE THREAD

**Issue by stefan-schweiger** [storybookjs/storybook#15490]
**Describe the bug**
If you have a numeric input with the default value 0 `@Input() value = 0` and use compodoc to generate your docs the value is set to `undefined` and you can't change it anymore.

![image](https://user-images.githubusercontent.com/3532342/124571012-b1163900-de47-11eb-9b5a-5c89576b4d95.png)

I already have a fix for this and I'm going to make a PR right after filing this issue. It just adds this addtional check in `extractTypeFromValue` in the file `compodoc.ts`.

```
// current main
return defaultValue || valueType === 'boolean' || valueType === 'string' ? valueType : null;
// my PR
return defaultValue || valueType === 'number' || valueType === 'boolean' || valueType === 'string' ? valueType : null;
```

**To Reproduce**
Just add `@Input() value = 0` to the doc-button in the example angular project.

**Comment by shilman** [comment]
Boo-yah!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-alpha.12 containing PR #15491 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Shiver me timbers!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.3.3 containing PR #15491 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```
