### ISSUE TITLE
Cannot remove controls from Canvas but keep property in Docs Page.

### ISSUE THREAD

**Issue by scotch115** [storybookjs/storybook#15493]
I am working with a component that has quite a few properties, most of which do not need to have controls, but there doesn't seem to be a way to remove the row from the canvas without also removing the property from the docs page.

Steps to Reproduce:
1. Set a specific property's control to false: `foo: { control: false } }` (according to [documentation](https://storybook.js.org/docs/react/essentials/controls#disable-controls-for-specific-properties) )
2. Property still exists in row of controls but with a '-' instead of a control
3. Use `foo: { table: { disable: true } }` instead to try to remove the control from the Canvas
4. Property _is_ removed but it loses its documentation

Setting the control to false (or some other method) should hide it from the Canvas UI, but keep it in the docs for developers to access, instead of only removing the control itself or removing the entire row.

**Comment by shilman** [comment]
Pretty sure you can just disable the controls addon entirely and it will remove controls from the canvas and keep them in the Docs tab:  https://storybook.js.org/docs/riot/essentials/introduction#disabling-addons

**Comment by scotch115** [comment]
@shilman That works to remove all the controls, but I only need to remove some of them. There are some properties in the component that are inherited and not configured by the user, so I want to hide specific controls, but not all of them.

**Comment by jaguadoarias** [comment]
@scotch115 @shilman We have the same issue. We want to remove specific props from controls panel but keep them inside the documentation table. We also tried with `foo: { control: false } }`, with this, I can disable the prop in controls but it is still visible in the panel.

**Comment by scotch115** [comment]
What we ended up doing was remixing the Docs Page code to build what we needed using Docs Blocks: https://storybook.js.org/docs/react/writing-docs/docs-page/#remixing-docspage-using-doc-blocks .

This worked perfectly for me!

**Comment by scotch115** [comment]
This works alongside the `table: { disable: true }` code

**Comment by jaguadoarias** [comment]
Thanks @scotch115 we will try remixing the Docs Page.

**Comment by sonikasharma1403** [comment]
@jaguadoarias , @scotch115  - unable to get this up and working with Angular + Storybook. Could you please suggest how we can achieve this with Angular?

**Comment by sonikasharma1403** [comment]
Thanks @scotch115, will try it out.
