### ISSUE TITLE
CSF3: Default render functions for non-React frameworks

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#15498]
CSF3.0 introduces default render functions, making it possible to remove lots of boilerplate in your stories. The initial implementation is for React, and we still need to add this for other popular frameworks.

- [x] Vue
- [x] Vue3
- [x] Angular
- [x] Web-components
- [x] Svelte

Here's a React example:

```js
// CSF 2.0
export const Primary = (args) => <Button {...args} />
Primary.args = { primary: true };

// CSF 3.0
export const Default = { args: { primary: true } }
```

And here's the React implementation:

https://github.com/storybookjs/storybook/blob/next/app/react/src/client/preview/index.tsx#L22-L28

**Comment by gossi** [comment]
Default render function for ember is not possible. But I already asked for a `render()` function in the `default` export of a stories file, which @shilman mentioned is possible? That's what ember would go for here, needs to be documented then.

My suggestions:
- Create a ticket for that doc task
- Link it to ember
- Check off ember from the list =)

**Comment by shilman** [comment]
Son of a gun!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-alpha.25 containing PR #15742 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by benbender** [comment]
@shilman I did a bit of experimentation on adding csf3-support to @storybook/svelte based on the work done on @storybook/angular-cli. I'm not very familiar with the internals of storybook and therefor I would like to ask some questions:

 * why do we have two packages for svelte (@storybook/svelte & @storybook/addon-svelte-csf) and what are the plans on those?
 * I could get the general csf3-support in a working state quite easily but struggled on the render-part for individual stories. It seemed like I would need to use addon-svelte-csf on that. As the relation between those and reasoning for this division is quite unclear to me, I wanted to clearify before investing additional work.

**Comment by shilman** [comment]
Zoinks!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-alpha.6 containing PR #17068 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by yannbf** [comment]
I'm not sure if web-components default render would be possible without the feature from this PR:
https://github.com/lit/lit/pull/1960

**Comment by shilman** [comment]
Shiver me timbers!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-alpha.22 containing PR #17276 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Ermahgerd!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-alpha.23 containing PR #17279 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
@yannbf This is also an option for lit https://github.com/open-wc/open-wc/pull/2398

**Comment by yannbf** [comment]
> @yannbf This is also an option for lit [open-wc/open-wc#2398](https://github.com/open-wc/open-wc/pull/2398)

I wonder if we'll need to do something regarding the names of the args, given that we'd be spreading a mix of events, props and booleans and according to the docs, in that case, they'll have to be branded:

> Attributes require no sigil, boolean attributes require a `?`, events a `@`, and properties the `.` sigil.

Example:
```js
import { spread } from '@open-wc/lit-helpers';
const elementTemplate = (
  obj = {
    'my-attribute': 'foo',
    '?my-boolean-attribute': true,
    '@my-event': () => console.log('my-event fired'),
    '.myProperty': { foo: 'bar' },
  },
) => html` <custom-element ${spread(obj)}></custom-element> `;
```

**Comment by shilman** [comment]
Web-components fixed in https://github.com/storybookjs/storybook/pull/19164 and released in https://github.com/storybookjs/storybook/releases/tag/v7.0.0-alpha.37 🎉
