### ISSUE TITLE
Support `babel.config.ts`

### ISSUE THREAD

**Issue by EvanPurkhiser** [storybookjs/storybook#15502]
**Is your feature request related to a problem? Please describe**
Storybook is unable to load `babel.config.ts` (note `ts`, not `js`). It looks like it's explicitly not included here https://github.com/storybookjs/storybook/blob/7064642e1aee7786c77fe735c064c0c29dbcee01/lib/core-common/src/utils/load-custom-babel-config.ts#L80-L84

I've 

**Describe the solution you'd like**
Support automatic discovery of `babel.config.ts` and `.babelrc.ts`

**Describe alternatives you've considered**
Currently I load the babel config in my `main.ts` using the `babel` prop.

Which also I've noticed, is [documented here](https://storybook.js.org/docs/react/configure/babel), but is not included in the [`StorybookConfig`](https://github.com/storybookjs/storybook/blob/ad2172e651af02028721dd06cf65e922220e3141/lib/core-common/src/types.ts#L224) type, so I end up with a `// @ts-expect-error`.

**Are you able to assist to bring the feature to reality?**
If it makes sense to add to the aforementioned list, I can open a PR.

**Additional context**
The PR where I ran into this issue: https://github.com/getsentry/sentry/pull/26918

**Comment by shilman** [comment]
I think we're going the other way towards forcing everybody to use the `.storybook/main.js` babel configuration instead (which should support this usage but requires a line of configuration on the user's part). @ndelangen should be able to share more.

**Comment by EvanPurkhiser** [comment]
That sounds good.

> which should support this usage

It does work right now, but the type is missing for the `babel` option in `main` and requires as `@ts-expect-error`.

**Comment by shilman** [comment]
Jiminy cricket!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-alpha.33 containing PR #15928 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
