### ISSUE TITLE
The "Copy Canvas Link" leaves out the base url and only gives the iframe information making it useless

### ISSUE THREAD

**Issue by TonyHoanTrinh** [storybookjs/storybook#15509]
**Describe the bug**
It appears the "Copy Canvas Link" on the top right side of the Canvas tab adds to the clipboard only part of the url, it only gives you the iframe part of the url but misses the main base url.

For example if I had my story on this url:
`http://localhost:6006/?path=/story/example-button--large`

And then I clicked on the "Copy Canvas Link" on the top right (The clipboard on the furthest right):
![image](https://user-images.githubusercontent.com/26545361/124787630-9fe82d80-df16-11eb-9fd5-f7d5ad224ddc.png)

Then when you go over to a new tab and try to copy and paste what you just "Copied" you will get:
`iframe.html?id=example-button--large&args=`

When it should be instead
`http://localhost:6006/iframe.html?id=example-button--large&args=&viewMode=story`

You are essentially missing the base part of the url.

I'm not sure if this is intentional or not.

Is this a bug or is this something on my end? If so is there a working solution or a wide to "hide" the "Copy Canvas Link" option on the top right?

Can you easily see this by doing `create-react-app new_project` and then `npx sb init`. You can reproduce this issue.

Thanks!

**Comment by nishit-prasad** [comment]
Hello I'm new and would like to take this up if it's available. This will get me started to explore more!

**Comment by shilman** [comment]
@nishit-prasad Thank you for helping make Storybook better! 🙏  Please check out [how to contribute](https://storybook.js.org/docs/react/contribute/how-to-contribute) in our docs and feel free to ask questions in `#contributing` in [our Discord](https://discord.gg/storybook).

**Comment by nishit-prasad** [comment]
Sounds good! Thank you. In the meantime, can this be assigned to me?

**Comment by nishit-prasad** [comment]
The PR is up and ready! 😄

**Comment by RabbitEarsDesign** [comment]
Is this still outstanding? I am interested in looking into this fix if we still have not solved it yet.

**Comment by soso-15315** [comment]
I haven't seen any activity for a while, so I made a pull request.
I am new to contributing, so please let me know if there is anything I missed.

**Comment by AakashRaj20** [comment]
> @nishit-prasad Thank you for helping make Storybook better! pray Please check out [how to contribute](https://storybook.js.org/docs/react/contribute/how-to-contribute) in our docs and feel free to ask questions in `#contributing` in [our Discord](https://discord.gg/storybook).

Hey is this issue still open then I would like to try it

**Comment by shilman** [comment]
Yay!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-alpha.16 containing PR #17498 that references this issue. Upgrade today to the `@future` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
