### ISSUE TITLE
Research limitations of testing-library

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#15518]
What are the exact limitations of Testing Library vs an approach based on the DevTools Remote protocol? (E.g. hover pseudostate, drag & drop?)

* [ ] Research puppeteer feature set as a proxy for what's possible
* [ ] Prototype interactions using testing library in `play` functions
* [ ] Document limitations
* [ ] Recommend workarounds if we know of any

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200510412866230/1200579873629913) by [Unito](https://www.unito.io)

**Comment by ghengeveld** [comment]
@shilman Do we still need this? I think we're not going to change course on the browser-native approach, so what's the point in researching this further? I guess we can have a paragraph or two about focus management in the docs, but beyond that we should defer to Testing Library's docs.
