### ISSUE TITLE
CSF3: Can't reuse stories in DocsContainer 

### ISSUE THREAD

**Issue by frassinier** [storybookjs/storybook#15510]
**Is your feature request related to a problem? Please describe**
I've switched stories for using [CSF 3.0](https://storybook.js.org/blog/component-story-format-3-0/)
I'm struggling while reusing stories from an external file with the addon-docs

I have a first file describing stories using CSF3

```javascript
export const Default = {
	href: '#',
	children: 'Link example',
};
```

And I would like to reuse them that way:

```js
import { ArgsTable, Meta, Canvas, Story } from '@storybook/addon-docs';

import Link from '../';
import * as Stories from '../Link.stories';

<Meta title="Components/Link" component={Link} />

<Canvas>
	<Story
		story={Stories.Default}
		args={{
			children: 'Help',
			href: 'https://help.talend.com',
			disabled: false,
			hideExternalIcon: false,
		}}
		argTypes={{
			href: {
				description: 'Link reference',
				control: {
					type: 'text',
				},
			},
		}}
	/>
</Canvas>

<ArgsTable story="usage" />
```

**Describe the solution you'd like**
Be able to don't have to maintain the template while using MDX

**Describe alternatives you've considered**
I can still define a template 

```js
import { ArgsTable, Meta, Canvas, Story } from '@storybook/addon-docs';

import Link from '../';
import * as Stories from '../Link.stories';

<Meta title="Components/Link" component={Link} />

<Canvas>
	<Story
		name="usage"
		args={{
			children: 'Help',
			href: 'https://help.talend.com',
			disabled: false,
		}}
		argTypes={{
			href: {
				description: 'Link reference',
				control: {
					type: 'text',
				},
			},
		}}
	>
		{props => <Link {...props} />}
	</Story>
</Canvas>

<ArgsTable story="usage" />
```

**Are you able to assist to bring the feature to reality?**
yes, sure

**Additional context**
—

**Comment by shilman** [comment]
Shiver me timbers!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-alpha.15 containing PR #15533 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
