### ISSUE TITLE
Named slots in Vue2

### ISSUE THREAD

**Issue by LongJinCen** [storybookjs/storybook#15536]
**Describe the bug**
Named slots are used in Vue2, but if a slot is not provided when a component is used, rendering content is missing

**To Reproduce**
Here is a component named `Test`
```
    <div>
      <slot name="header">
        this is a back content
      </slot>
      <div>this is a test</div>
    </div>
````
If I use this component without providing a named slot, the back content will not be rendered。And nothing beyond the slot is rendered。
```
import Test from './Test.vue'

export default {
  title: 'Test',
  component: Test,
}

const Template = (args, { argTypes }) => ({
  props: Object.keys(argTypes),
  components: { Test },
  template: '<Test v-bind="$props"/>',
});

export const Primary = Template.bind({})

```

**Version**

- @storybook/vue": "^6.2.9"
- "vue": "^2.6.14"

**Comment by LongJinCen** [comment]
solve this problem by decrease vue and vue-template-complier to 2.6.11

**Comment by Cubid** [comment]
I have the same issue ("vue": "^2.6.14",  "@storybook/vue": "^6.3.7") but downgrading to 2.6.11 does not solve the issue.
I
