### ISSUE TITLE
Storybook doesn't work with gatsby

### ISSUE THREAD

**Issue by moose96** [storybookjs/storybook#15538]
**Describe the bug**
When I want to run Storybook with Gatsby following by these instructions: [https://www.gatsbyjs.com/docs/how-to/testing/visual-testing-with-storybook/#setting-up-your-environment](https://www.gatsbyjs.com/docs/how-to/testing/visual-testing-with-storybook/#setting-up-your-environment), the Storybook is running but I see only a loader and I get this error in dev tools:
![image](https://user-images.githubusercontent.com/47902696/125054651-bd4c0180-e0a6-11eb-9538-d3b64cb4769a.png)
error:
![image](https://user-images.githubusercontent.com/47902696/125054568-a4dbe700-e0a6-11eb-99e2-8d19cb1785d7.png)

When I comment this line
```
config.module.rules[0].exclude = [/node_modules\/(?!(gatsby)\/)/]
```
Storybook runs, but I can't use Gatsby components. The problem exist even with default stories that came from Storybook init.

**To Reproduce**
This is the link to repo where problem exists: [https://github.com/moose96/gatsby-storybook-test](https://github.com/moose96/gatsby-storybook-test).

**System**
Environment Info:

  System:
    OS: Windows 10 10.0.19041
    CPU: (8) ia32 Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz
  Binaries:
    Node: 14.17.0 - C:\Program Files (x86)\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.13 - C:\Program Files (x86)\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1023.0), Chromium (91.0.864.64)
  npmPackages:
    @storybook/addon-actions: ^6.3.4 => 6.3.4
    @storybook/addon-essentials: ^6.3.4 => 6.3.4
    @storybook/addon-links: ^6.3.4 => 6.3.4
    @storybook/builder-webpack5: ^6.3.4 => 6.3.4
    @storybook/manager-webpack5: ^6.3.4 => 6.3.4
    @storybook/react: ^6.3.4 => 6.3.4.

**Additional Context**
* Gatsby version: 3.9.0
* React version: 17.0.1
* Storybook version: 6.3.4

**Comment by shilman** [comment]
Did you try adding webpack@5 as a dev dependency? Per https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#webpack-5-manager-build

**Comment by moose96** [comment]
I've added it already, and it's still not working.

**Comment by dictyo** [comment]
Same problem here... same deps.
Cryptic message from Debugger: "Error: Promised response from onMessage listener went out of scope"
No clue how to solve that.

**Comment by shilman** [comment]
closing as dupe to #15820

**Comment by usrrname** [comment]
I got Storybook 6.3.7  to work with Gatsby 3 last weekend. What I did was to follow the [Gatsby install instructions ](https://www.gatsbyjs.com/docs/how-to/testing/visual-testing-with-storybook/) and introduced the following `config.resolve.alias` block into my `main.ts` : 

```
module.exports = {
  stories: ['../src/**/*.stories.@(jsx|tsx|mdx)'],
  addons: [
    '@storybook/addon-links',
    '@storybook/addon-docs',
    '@storybook/addon-essentials',
  ],
  typescript: {
    check: true,
  },
  core: {
    builder: 'webpack5',
  },
  webpackFinal: async (config: any) => {
    // Transpile Gatsby module because Gatsby includes un-transpiled ES6 code.
    config.module.rules[0].exclude = [/node_modules\/(?!(gatsby)\/)/];
    // Use babel-plugin-remove-graphql-queries to remove static queries from components when rendering in storybook
    config.module.rules[0].use[0].options.plugins.push(
      require.resolve('babel-plugin-remove-graphql-queries')
    );
    config.resolve.alias = {
      ...config.resolve.alias,
      path: require.resolve('path-browserify'),
      crypto: require.resolve('crypto-browserify'),
      stream: require.resolve('stream-browserify'),
    };
    return config;
  },
};

```
