### ISSUE TITLE
Webpack5: latest addon-docs uses webpack 4

### ISSUE THREAD

**Issue by rgoldfinger-quizlet** [storybookjs/storybook#15544]
**Describe the bug**
`addon-docs` requires `@storybook/builder-webpack4`, which causes webpack 4, webpack 4 typings, and a whole host of other, older dependencies to be installed. 

https://github.com/storybookjs/storybook/blob/4bd2fc9b0677190c59e60fd63841294ab88e80c5/addons/docs/package.json#L68

This is a duplicate of https://github.com/storybookjs/storybook/issues/15474, refiling in order to get the proper tagging.

**Comment by shilman** [comment]
closing as dupe to #15474
