### ISSUE TITLE
Hide menu toggle and toggle panel when toggling fullscreen in singleStory mode

### ISSUE THREAD

**Issue by ghengeveld** [storybookjs/storybook#15553]
When using `singleStory=true` (query param), there should be no way to bring up the sidebar. Currently there's two icons to toggle it:

<img width="1200" alt="Screenshot 2021-07-12 at 13 52 47" src="https://user-images.githubusercontent.com/321738/125283868-2044cf00-e319-11eb-85f8-2fcfed54d6fc.png">

The menu toggle should be hidden in singleStory mode. The fullscreen toggle should toggle the addon panel if there are any, or not be displayed either.

**Comment by domyen** [comment]
Related UX changes for the toolbar + sidebar + addon panel toggles [here](https://github.com/storybookjs/storybook/issues/13799#issuecomment-878605335)

**Comment by alk-mandrianarijaona** [comment]
hey, I can take this one

**Comment by shilman** [comment]
@alk-mandrianarijaona Thank you for helping make Storybook better! 🙏  Please check out [how to contribute](https://storybook.js.org/docs/react/contribute/how-to-contribute) in our docs and feel free to ask questions in `#contributing` in [our Discord](https://discord.gg/storybook).

**Comment by alk-mandrianarijaona** [comment]
> The fullscreen toggle should toggle the addon panel if there are any, or not be displayed either.
@shilman @domyen  @ghengeveld can you guys tell me what's the way to check if there is an addon panel to display?

**Comment by alk-mandrianarijaona** [comment]
> > The fullscreen toggle should toggle the addon panel if there are any, or not be displayed either.
> 
> @shilman @domyen @ghengeveld can you guys tell me what's the way to check if there is an addon panel to display?

OK I just found it, I need to check `showPanel`

**Comment by ghengeveld** [comment]
See https://github.com/storybookjs/storybook/blob/8c326620fe0d0d413e0b365ecc1cdf1f4dfc65b2/lib/ui/src/index.tsx#L49

**Comment by shilman** [comment]
Ta-da!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-beta.24 containing PR #15755 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Jeepers creepers!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-beta.25 containing PR #15755 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```
