### ISSUE TITLE
Controls Addon - Vue - Update property without re-rendering story

### ISSUE THREAD

**Issue by rtrap-rsi** [storybookjs/storybook#15567]
**Describe the bug**
When updating vue props thorugh Controls the component remount (mounted lifecycle method relaunched)

**To Reproduce**
https://github.com/rtrap-rsi/vue-storybook-remount-issue

**Comment by tmeasday** [comment]
That repository doesn't appear to include Storybook, did you forget to check something in?

**Comment by rtrap-rsi** [comment]
Ops sorry, pushed right version

**Comment by tmeasday** [comment]
It does seem like vue3 isn't behaving as it "should" here @shiman.

**Comment by mirabledictu** [comment]
Can confirm this

**Comment by wobsoriano** [comment]
Can I add that the source code block in the docs tab doesn't appear automatically?

**Comment by bisubus** [comment]
Are there any workarounds currently for this? Sadly, this makes controls much less unusable.

**Comment by daniellacosse** [comment]
Encountering this as well. It breaks any reactivity related to props changes.
