### ISSUE TITLE
Toolbar UX for different modes (fullscreen, singleStory)

### ISSUE THREAD

**Issue by domyen** [storybookjs/storybook#15560]
This is a master list of Toolbar UX bugfixes and enhancements. It's a combination of tiny, interrelated issues that make sense to develop and QA together.

### Use tooltip instead of `title` attribute for icon helper text
Use the [TooltipNote](https://5ccbc373887ca40020446347-qvjajxnkih.chromatic.com/?path=/story/tooltip-tooltipnote--default-story) in place of `title` attribute so that the title appears faster when hovering over icons. This wasn't a big problem when Storybook had fewer icons. But now that addons can add icons and we have a lot of icons ourselves it makes sense to use our own tooltips for this.

![image](https://user-images.githubusercontent.com/263385/125370341-129c4300-e333-11eb-890e-9664d3f44dc6.png)

### Change behavior of link icon
The link icon should copy the URL to clipboard (we have a [Clipboard component](https://5ccbc373887ca40020446347-qvjajxnkih.chromatic.com/?path=/story/clipboard-clipboard--default) in the design system) 
 ![image](https://user-images.githubusercontent.com/263385/125362481-d57c8480-e323-11eb-85e6-efd0c9666c0b.png)

iirc, this used to add extra query params to allow you to link to the specific Storybook state that you were currently viewing. That functionality has been built into Storybook thanks to @ghengeveld. Instead it should be used to copy the permalink to the specific component story in Storybook (wherever its hosted). This should work for embedded Storybooks as well.

**Nice to have:** When clicking on the Link icon show a tooltip with options to 1. copy url and 2. get an embed url.

### Remove fullscreen mode from UX (keep singleStory) 
Currently, fullscreen mode adds an extra layer of complexity that we keep getting bug reports for whenever we make changes to the UI.  Fullscreen mode is just a shortcut for `hiding sidebar && hiding addons`. It saves you one click when you'd have to do two. The idea behind it is to help developers focus on building the UI without the extra Storybook chrome. 

But the use case for fullscreen mode and "open canvas in new tab" mode is similar when in development. In many ways, opening the canvas iframe is superior because it eliminates the Storybook DOM entirely.

The other use case for a fullscreen-like mode is when you embed a story via `singleStory=true` query param. We offer this UX for Storybooks that are embedded. `singleStory` hides the sidebar permanently and allows the addon panel to be toggle-able. We should preserve this behavior as is.

![image](https://user-images.githubusercontent.com/263385/125370401-3b243d00-e333-11eb-8f86-c1ef8d23dd75.png)

### Add button to toggle addon panel when it's hidden 
It's hard to discover how to view the addon panel once it's hidden. Add a button when the addon panel is hidden that reveals it again.

![outline-addon](https://user-images.githubusercontent.com/263385/125357414-7a935f00-e31c-11eb-933c-b9bdb85b60b6.png)

- Display this icon in the toolbar and swap which one is shown depending on orientation. 
  - ![image](https://user-images.githubusercontent.com/263385/125356082-985fc480-e31a-11eb-9ffa-320fa456f323.png) 
  - ![image](https://user-images.githubusercontent.com/263385/125356123-a4e41d00-e31a-11eb-91c8-4ed42a6af2c7.png)

### Change icon that toggles the sidebar
Thanks to @apapadopoulou we now have an icon to reveal the sidebar when it is closed. Update this icon to the new panel show and hide icons.
  - Old ![image](https://user-images.githubusercontent.com/263385/125356384-ff7d7900-e31a-11eb-868e-dc9dea619dd8.png)
  - New ![image](https://user-images.githubusercontent.com/263385/125356372-fbe9f200-e31a-11eb-84c1-12ca08a54942.png)

Related: #15553, https://github.com/storybookjs/storybook/issues/13799#issuecomment-878605335

**Comment by apapadopoulou** [comment]
Hello, is anyone working on this?

**Comment by domyen** [comment]
Not yet! Stoked if you take it on @apapadopoulou

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
