### ISSUE TITLE
update react-dev-utils to 11.0.4 to fix security warning

### ISSUE THREAD

**Issue by michaelfarrell76** [storybookjs/storybook#15566]
**Describe the bug**

There is a vulnerability with react-dev-utils that can be fixed by upgrading up 11.0.4
<img width="1023" alt="Screen Shot 2021-07-13 at 11 47 17 AM" src="https://user-images.githubusercontent.com/10264973/125508310-e6960ed9-9833-4520-a05c-beae8352d225.png">

currently this is set to [11.0.3](https://github.com/storybookjs/storybook/blob/main/lib/builder-webpack5/package.json#L89). should be a quick bump

**Comment by alk-mandrianarijaona** [comment]
@michaelfarrell76 there is already a merged PR for that : https://github.com/storybookjs/storybook/pull/14210

**Comment by shilman** [comment]
closing this as fixed. thanks!
