### ISSUE TITLE
Test runner: Benchmark playwright vs JSDOM

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#15570]
We need to understand the performance difference between JSDOM and Playwright on a real-world Storybook to test the feasibility of the test runner overall and also to help select our default recommendation.

We know from experience that JSDOM will lead to lots of browser compatibility issues. Playwright runs real browser and will not have these issues, but will run slower. We need to understand how much slower to help with the decision process.

- [ ] Chromatic
- [ ] Storybook design system
- [ ] Other real-world storybooks TBD

**Comment by burhanuday** [comment]
Hi @shilman, were the results from your research documented somewhere I can read?

**Comment by shilman** [comment]
@yannbf can you share?

My recollection was that JSDOM took roughly 60% of the time compared to Playwright in most cases. But there were a few cases where Playwright was as fast or even slightly faster.

In the end we went with Playwright-only to simplify things and to get the benefits of running in a real browser.
