### ISSUE TITLE
puppeteer-core version in @storybook/cli

### ISSUE THREAD

**Issue by Celos** [storybookjs/storybook#15585]
`@storybook/cli` uses a fairly old version of `puppeteer-core`, `^2.1.1`. The current version is `^10`.

The concrete issue that I'm hitting and that the later versions fix is [PR#6555](https://github.com/puppeteer/puppeteer/pull/6555). Basically trying to run `npx sb extract` with node@16 and using an http proxy throws an ERR_INVALID_PROTOCOL exception.

**Comment by vanessayuenn** [comment]
This has been removed from the CLI
