### ISSUE TITLE
Angular: "Show code" shows some weird looking code 

### ISSUE THREAD

**Issue by tsmolj** [storybookjs/storybook#15598]
**Describe the bug**
When I try to "show code" of any component the formatting looks really weird (see pic).

![image](https://user-images.githubusercontent.com/87479619/125789984-067330d9-4b51-4f8d-8609-e5d0775ae2b4.png)

**Neo-input story code**

```
import { Meta, Story } from '@storybook/angular/types-6-0';
import { NeoFormInputComponent } from '@shared/form-elements/neo-form-input/neo-form-input.component';
import { NeoFormElementsModule } from '@shared/form-elements/neo-form-elements.module';
import {
  FormControl,
  FormsModule,
  ReactiveFormsModule,
  Validators,
} from '@angular/forms';
import { NeoFormElementComponent } from '@shared/form-elements/neo-form-element/neo-form-element.component';
import { createTouchedFormControl } from 'src/stories/helper_functions/formControl';


export default {
  title: 'UI pattern library/ Form elements/ Neo-form-input',
  component: NeoFormInputComponent,
  subcomponents: { NeoFormElementComponent },
} as Meta;

const Template: Story<NeoFormInputComponent> = (
  args: NeoFormInputComponent
) => ({
  props: args,
  moduleMetadata: {
    imports: [NeoFormElementsModule, FormsModule, ReactiveFormsModule],
  },
});

export const Default = Template.bind({});
Default.args = {
  formControl: new FormControl(),
  disable: false,
};

Default.parameters = {
  docs: {
    source: {
      code: `
      <neo-input></neo-input>
      `,
    },
  },
};
```

**System**
  System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-3840QM CPU @ 2.80GHz 
  Binaries:
    Node: 14.17.0 - C:\Program Files\nodejs\node.EXE       
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1023.0), Chromium (91.0.864.67)
  npmPackages:
    @storybook/addon-a11y: ^6.3.2 => 6.3.2
    @storybook/addon-actions: ^6.3.2 => 6.3.2
    @storybook/addon-essentials: ^6.3.2 => 6.3.2
    @storybook/addon-links: ^6.3.2 => 6.3.2
    @storybook/angular: ^6.3.2 => 6.3.2
  npmGlobalPackages:
    @storybook/cli: 6.2.9

**Additional context**
The problem occurs on the example components that come with storybook as well. 

![image](https://user-images.githubusercontent.com/87479619/125795599-bb18e1cf-b227-44ee-8ff3-d2201d7ef504.png)

**Comment by alk-mandrianarijaona** [comment]
I had a similar issues a few days ago. It turns out my `bootstrap` styles override the storybook one for `code .token.tag` selector. Can you check which CSS rules are applied to the code block? (by right clicking and inspecting one of your code line)

**Comment by tsmolj** [comment]
You may be right. The projcet I'm working on uses bootstrap for some of it's components so I'm guessing our 2 situations are similar in nature. I've checked the css rules on the code block and every line has "token tag" classes applied to them.

![image](https://user-images.githubusercontent.com/87479619/126650429-ecef7808-1ee5-473d-a449-989e3486973c.png)

Once I de-select every property from the tag class things started looking good.

![image](https://user-images.githubusercontent.com/87479619/126651013-89d6a8d7-80da-4882-bb8b-9639a696aa57.png)

So I guess the question remains. How do I remowe the "tag" class from the "show code" code block? Or better yet,
how do I make storybook ovveride bootstrap's styles and use it's own?

**Comment by yaldram** [comment]
Thanks @alk-mandrianarijaona I saw the styles that were broken in my dev tools and under the `preview-body.html`, I have the following styles - 
```javascript
code[class*='language-'],
  pre[class*='language-'] {
    color: white;
    text-shadow: none;
  }
```

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
