### ISSUE TITLE
Composition sidebar menu incorrect for title items with no grouping

### ISSUE THREAD

**Issue by dexster** [storybookjs/storybook#15597]
**Describe the bug**
Composition menu items for referenced storybooks are displayed incorrectly when the title has no grouping ("/" separator). Instead of showing the menu item directly, the composition menu has an expansion icon and then shows 'Page'. In this image the composition menu is on the left and the referenced storybook menu is on the right. 

![Screenshot 2021-07-15 at 14 18 01](https://user-images.githubusercontent.com/6392334/125786984-a46c8134-905f-449c-857a-29d61119b576.png)
   
**To Reproduce**
Create a composition storybook and have a ref to a storybook containing a story with a title with no "/"
```
export default {
  title: 'Getting Started System',
};
```
**System**
 System:
    OS: macOS 11.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 14.15.5 - ~/.nvm/versions/node/v14.15.5/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.15.5/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v14.15.5/bin/npm
  Browsers:
    Chrome: 91.0.4472.114
    Edge: 91.0.864.67
    Firefox: 89.0.2
    Safari: 14.1.1
  npmPackages:
    @storybook/addon-a11y: ^6.4.0-alpha.14 => 6.4.0-alpha.14 
    @storybook/addon-actions: ^6.4.0-alpha.14 => 6.4.0-alpha.14 
    @storybook/addon-essentials: ^6.4.0-alpha.14 => 6.4.0-alpha.14 
    @storybook/addon-links: ^6.4.0-alpha.14 => 6.4.0-alpha.14 
    @storybook/angular: ^6.4.0-alpha.14 => 6.4.0-alpha.14 
    @storybook/builder-webpack5: ~6.4.0-alpha.14 => 6.4.0-alpha.14 
    @storybook/manager-webpack5: ~6.4.0-alpha.14 => 6.4.0-alpha.14

**Comment by passbyval** [comment]
I'm seeing this issue as well on `6.5.0-alpha.47`.

**Comment by passbyval** [comment]
Fixed by https://github.com/storybookjs/storybook/pull/17726.
