### ISSUE TITLE
Angular: Compodoc character issues

### ISSUE THREAD

**Issue by dexster** [storybookjs/storybook#15591]
**Describe the bug**
Certain characters are not translated correctly. See image below of a Controls description.
![Screenshot 2021-07-14 at 23 10 00](https://user-images.githubusercontent.com/6392334/125693521-5f628748-d25a-4f0f-afc8-ecf3f7079b11.png)

This issue above is caused by an apostrophe in the jsdoc comment 

This is because Compodoc does some parsing of the jsdoc when generating the `description` property. It also adds HTML tags to this `description` property

Compodoc 1.1.14 has a new property called `rawdescription` which does not encode characters or add HTML tags. The difference looks like this

![Screenshot 2021-07-14 at 23 21 00](https://user-images.githubusercontent.com/6392334/125694662-91fe5368-7c97-49c2-a88c-7a635425cf22.png)

 I propose we move from using the `description` property to the `rawdescription` property.  I can make the change if you're happy to go ahead with this?

**Comment by dexster** [comment]
@shilman Is there someone who could give some feedback on this?

**Comment by shilman** [comment]
Thanks for the nudge @dexster -- sorry I missed this first time around.

That change sounds reasonable to me, and I think I wrote the original buggy code 😉

**Comment by shilman** [comment]
Zoinks!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-alpha.25 containing PR #15774 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```
