### ISSUE TITLE
Addons panel no longer working

### ISSUE THREAD

**Issue by thany** [storybookjs/storybook#15606]
**Describe the bug**
Updated every Storybook package from 6.2.9 to 6.3.4.
Except addon-knobs, which doesn't go higher than 6.3.0 so that's where it's at.

Addons panel is no longer showing. Whether I press A or select it from the menu, it just doesn't work. It never shows.

**To Reproduce**
Please create a reproduction by running `npx sb@next repro` and following the instructions. Read our [documentation](https://storybook.js.org/docs/react/contribute/how-to-reproduce) to learn more about creating reproductions.
Paste your repository and deployed reproduction here. We prioritize issues with reproductions over those without.

```
🏗 Bootstrapping cra project (this might take a few minutes)
npx create-react-app@latest repro --use-npm && cd repro && echo "FAST_REFRESH=true" > .env && echo "SKIP_PREFLIGHT_CHECK=true" > .env

🧶 Installing Yarn 2
yarn set version berry && yarn config set enableGlobalCache true && yarn config set nodeLinker node-modules
An error occurred while executing: `yarn set version berry && yarn config set enableGlobalCache true && yarn config set nodeLinker node-modules`
Command output was:

'yarn' is not recognized as an internal or external command,
operable program or batch file.

🚨 Installing Yarn 2 failed
🚨 Failed to create repro
```

No offense, but maybe don't install software on my system?! Thank you 😘
So that repro script is not working. I really don't have time to create an entire repro just for a seemingly small bug. Maybe if it's really really really really neccesary, I'll consider it.

**System**
```
Environment Info:

  System:
    OS: Windows 10 10.0.19043
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
  Binaries:
    Node: 14.17.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 91.0.4472.124
    Edge: Spartan (44.19041.1023.0), Chromium (91.0.864.67)
  npmPackages:
    @storybook/addon-a11y: 6.3.4 => 6.3.4
    @storybook/addon-actions: 6.3.4 => 6.3.4
    @storybook/addon-docs: 6.3.4 => 6.3.4
    @storybook/addon-knobs: 6.3.0 => 6.3.0
    @storybook/addons: 6.3.4 => 6.3.4
    @storybook/preset-create-react-app: 3.2.0 => 3.2.0
    @storybook/react: 6.3.4 => 6.3.4
    @storybook/theming: 6.3.4 => 6.3.4
```
Still not detecting Firefox 90.

**Additional context**
I know addon-knobs is deprecated in favour of addon-controls, but we don't really have time to migrate hundreds of components right now, and we might never. So unfortunately addon-knobs will have to keep working.

**Comment by shilman** [comment]
What happens when you open it in an incognito browser?

**Comment by thany** [comment]
Sorry, I got it working in the mean time. Incognito wouldn't work either.

The "problem" was that I had to implement a workaround for [this bug in addon-knobs](https://github.com/storybookjs/addon-knobs/issues/19) which now breaks it. So all I had to do is revert that workaround, back to the recommended implementation (so no `/register`) and it worked again.

I suppose this once again confirms the danger of workarounds: they might stop working at some point, and/or one might forget they existed at all.

So if anyone else stumbles upon this problem, there's a possible solution for you.
Sorry I jumped right into the issue tracker and took some of your time.

**Comment by thany** [comment]
Well, as it turns out, [that bug](https://github.com/storybookjs/addon-knobs/issues/19) is back, and its workaround no longer works either, and was discovered above.

I've commented over there, because there seems a better place to discuss any workarounds of fixes to be done.

**Comment by nelsieborja** [comment]
> What happens when you open it in an incognito browser?

Works only in Incognito.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
