### ISSUE TITLE
Id generation not working as documented

### ISSUE THREAD

**Issue by pladaria** [storybookjs/storybook#15605]
**Describe the bug**
Id generation not working as documented

**To Reproduce**
Documentations says:
> Storybook will prioritize the id over the title for ID generation, if provided, and will prioritize the story.name over the export key for display.

https://storybook.js.org/docs/react/configure/sidebar-and-urls#permalinking-to-stories

So for this story:
```js
export default { title: 'Foo/Bar' };
export const Baz = BarStory.bind({});
```
The id would be: `foo-bar--baz` (which is correct).

And for this other story:
```js
export default { title: 'Foo/Bar' };
export const Baz = BarStory.bind({});
Baz.storyName = 'Moo';
```
I'd expect the id to be: `foo-bar--moo`, but the id is still `foo-bar--baz`.

This can be seen in storybook examples:
https://github.com/storybookjs/storybook/blob/next/examples/html-kitchen-sink/stories/addon-actions.stories.js#L10
```js
export default {
  title: 'Addons/Actions',
};

export const Story1 = buttonStory();
Story1.storyName = 'Hello World';
```
Generated id is: `addons-actions--story-1`, as seen here: https://next--storybookjs.netlify.app/html-kitchen-sink/?path=/story/addons-actions--story-1 but I think it should be: `addons-actions--hello-world`

Is this the expected behavior?

**Comment by gpsarkar** [comment]
This issue is present in version 6.5.10. It doesn't help in creating a permalink to the story.
