### ISSUE TITLE
Accessibility: 'Clear text' button in search field is defined as image

### ISSUE THREAD

**Issue by tylerbutler** [storybookjs/storybook#15601]
**Repro-Steps:**

1.  Open the URL with valid credentials
2.  Navigate to 'search field' under 'Fluid playground' link.
3.  Type any letter and navigate to 'clear text' button and then listen to narrator announcement.

**Actual Result:**

While navigating with caps-right arrow key in Scanoff mode to clear text button, Screen reader is announcing as 'image' and while navigating with 'right arrow' keys it is announcing as 'end of line'.

'clear text' Button is defined as image i.e, role is defined as 'SvgRoot' 

  

**Expected Result:**

Clear text button role should be defined as 'button' and Name should be defined as 'Clear text'.

All components need an accessible name and role, ideally with semantic elements and attributes. In rare cases, aria-label or aria-labelled by may be needed to alter the name, or a role  

**Describe the bug**

Screen readers are not announcing the "clear text" element in the search box. It is read as "image" in some cases and "enf of line" in others.

When interactive elements have an incorrect name and role, it is difficult for people using assistive technology (like screen readers) to understand the purpose of control and its relationship to other content. Knowing the role for a control helps users know what will happen when that object has focus and is selected, as well as what keyboard shortcuts to use when interacting with the control.

**To Reproduce**

1. Enable a screen reader like Windows Narrator.
2. Enter the search box.
3. Type any letter and navigate to 'clear text' button and then listen to narrator announcement.

No additional Storybook configuration is needed.

**System**

```
Environment Info:

  System:
    OS: Linux 5.4 Ubuntu 20.10 (Groovy Gorilla)
    CPU: (12) x64 Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz
  Binaries:
    Node: 16.0.0 - ~/.nvm/versions/node/v16.0.0/bin/node
    Yarn: 2.4.2 - ~/.nvm/versions/node/v16.0.0/bin/yarn
    npm: 7.10.0 - ~/.nvm/versions/node/v16.0.0/bin/npm
  npmPackages:
    @storybook/addon-actions: ^6.4.0-alpha.17 => 6.4.0-alpha.17
    @storybook/addon-docs: ^6.4.0-alpha.17 => 6.4.0-alpha.17
    @storybook/addon-essentials: ^6.4.0-alpha.17 => 6.4.0-alpha.17
    @storybook/addon-links: ^6.4.0-alpha.17 => 6.4.0-alpha.17
    @storybook/react: ^6.4.0-alpha.17 => 6.4.0-alpha.17
```

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid.

Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
