### ISSUE TITLE
addon-storyshots can't fetch stories using new directory-syntax in @next

### ISSUE THREAD

**Issue by benbender** [storybookjs/storybook#15609]
**Describe the bug**
Upgrading a comprehensive storybook-setup to **6.4.0-alpha.18** to test CSF3 breaks `@storybook/addon-storyshots`.
`addon-storyshots` expects a regexp to load the stories itself - and breaks if you use the new syntax like:

````
    {
      directory: '[redacted]/src',
      files: '*.stories.@(mdx|tsx|ts|jsx|js)'
    }
    
````

With the following error:
`````
    TypeError: val.match is not a function

       8 |
       9 | // This will automate snapshot testing for all stories
    > 10 | initStoryshots({
         | ^
      11 |   renderer: render,
      12 |   snapshotSerializers: [reactTestingLibrarySerializer],

      at detectBadGlob (node_modules/.pnpm/@storybook+core-common@6.4.0-alpha.18_f31b35bdaa3b7c2fce82404f09d2dac4/node_modules/@storybook/core-common/dist/cjs/utils/to-require-context.js:27:19)
````

**Comment by ndelangen** [comment]
The future of storyshots is the test-runner:
https://storybook.js.org/docs/react/writing-tests/test-runner#page-top

And use the play function for expectations:
https://storybook.js.org/docs/react/writing-stories/play-function#page-top

We will not be making any improvement / changes to storyshots.
