### ISSUE TITLE
Angular MDX component template override

### ISSUE THREAD

**Issue by gabriel-gn** [storybookjs/storybook#15608]
**Is your feature request related to a problem? Please describe**
Angular has a tag "ng-content" which can put inside components some other resources. I can use typescript to override default template, but not on mdx stories.

Example in ts:
```
const Template: Story<ButtonComponent> = (args: ButtonComponent) => ({
  component: ButtonComponent,
  props: args,
  template: `
    <pm-button
        [label]="label"
        [type]="type"
        [busy]="busy"
        [busyText]="busyText"
        [iconClass]="iconClass"
        [outline]="outline"
        [disabled]="disabled"
    >
        **button content here**
    </pm-button>`
});

export const DefaultButton = Template.bind({});
DefaultButton.args = {
  type: 'default'
};
```

on MDX stories, its not possible to override it.
_____

**Describe the solution you'd like**

Adding the template as component parameter, or story parameter.
Something like:

```
export const htmlTemplate: `
<some-button>
    **button content here**
</some-button>
`;
export const Template = (args) => <ButtonComponent {{...args}, ...{template: htmlTemplate}} />

<Story
    name='default'
    args={defaultArgs}
    argTypes={defaultControls}
 >
    {Template.bind({})}
 </Story>
```

______

**Describe alternatives you've considered**
```
export const htmlTemplate: `
<some-button>
    **button content here**
</some-button>
`;
export const Template = (args) => <ButtonComponent {...args} />

<Story
    name='default'
    args={defaultArgs}
    argTypes={defaultControls}
   template={htmlTemplate}
 >
    {Template.bind({})}
 </Story>
```
______

**Are you able to assist to bring the feature to reality?**
no
______

**Additional context**
No aditional context, I just couldn't find any way to solve this issue.
A possible "workaround" (not tested) could be to design stories in ts files and embedding it on mdx files.

**Comment by shilman** [comment]
I'm surprised that the solution you'd like doesn't already work as is. What happens when you try that?

**Comment by gabriel-gn** [comment]
> I'm surprised that the solution you'd like doesn't already work as is. What happens when you try that? MDX is fussy about whitespace, so you might have to put an extra newlines between the two "export const" statements.

I tried to add whitespace, but nothing happens right.

when I try:
```
export const Template = (args) => <ButtonComponent {{...args, template: defaultTemplate}} />
```
I get the following result, and the story doesn't get rendered.
![image](https://user-images.githubusercontent.com/30876329/126343002-bdaa69bb-bc35-4fa2-8580-ac690bef101b.png)


When I try:
```
<Story
    name='default'
    args={defaultArgs}
    argTypes={defaultControls}
    template={defaultTemplate}
  >
    {Template.bind({})}
  </Story>
```
The story still get rendered, but do not override template.

As I found, the Meta type does not support "template" attribute

```
export declare const Meta: FC<MetaProps>;
declare type MetaProps = BaseMeta<Component> & BaseAnnotations<Args, any>;
export interface BaseAnnotations<Args, StoryFnReturnType> {
    args?: Partial<Args>;
    argTypes?: ArgTypes;
    parameters?: Parameters;
    decorators?: BaseDecorators<StoryFnReturnType>;
}
```

**Comment by gabriel-gn** [comment]
I have "bypassed" it changing all my "main stories" to mdx, using them as

```
<Canvas>
  <Story name='Default' story={DefaultButton}></Story>
</Canvas>
```

and disabling non .mdx stories on main.js
```
module.exports = {
  "stories": [
    // "../stories/**/*.stories.@(js|jsx|ts|tsx|mdx)",
    "../stories/**/*.stories.@(mdx)"
  ],
...
```
