### ISSUE TITLE
Changing controls in storybook for angular components does not trigger ngOnChanges

### ISSUE THREAD

**Issue by aavelyn** [storybookjs/storybook#15610]
**Describe the bug**

I've followed the angular tutorial and created a test component.
When I change the controls in storybook, which are wired to trigger changes in angulars `ngOnChanges` lifecycle hook, nothing happens.

**To Reproduce**

- Create angular storybook setup
- Create an angular component with `@Input` and implement the `ngOnChanges` lifecycle hook in that component and console.log `simpleChanges`
- Change in storybook that control
- nothing happens

**System**
Environment Info:

  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
  Binaries:
    Node: 16.3.0 - /usr/local/bin/node
    npm: 7.15.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 91.0.4472.114
    Firefox: 89.0.2
    Safari: 14.0.3
  npmPackages:
    @storybook/addon-actions: 6.3.4 => 6.3.4 
    @storybook/addon-controls: 6.3.4 => 6.3.4 
    @storybook/addon-docs: 6.3.4 => 6.3.4 
    @storybook/addon-essentials: ~6.3.0 => 6.3.4 
    @storybook/addon-jest: 6.3.4 => 6.3.4 
    @storybook/addon-knobs: ~6.3.0 => 6.3.0 
    @storybook/addon-storysource: 6.3.4 => 6.3.4 
    @storybook/addon-viewport: 6.3.4 => 6.3.4 
    @storybook/angular: ~6.3.0 => 6.3.4 
    @storybook/builder-webpack5: ~6.3.0 => 6.3.4 
    @storybook/manager-webpack5: ~6.3.0 => 6.3.4 

Other relevant dependencies

		"@angular-devkit/build-angular": "12.1.1",
		"@angular/cli": "12.1.1",
		"@angular/compiler-cli": "12.1.1",
		"@angular/language-service": "12.1.1",
		"@compodoc/compodoc": "^1.1.11",
		"@nrwl/cli": "12.5.8",
		"@nrwl/cypress": "12.5.8",
		"@nrwl/jest": "12.5.8",
		"@nrwl/storybook": "12.5.8",
		"@nrwl/tao": "12.5.8",
		"@nrwl/workspace": "12.5.8",

**Additional context**

**Comment by Marklb** [comment]
In case someone wants to attempt this, here are the files I think are relevant:

Method in legacy renderer that called `ngOnChanges`: https://github.com/storybookjs/storybook/blob/next/app/angular/src/client/preview/angular/components/app.component.ts#L117

General location this probably needs to be added to: https://github.com/storybookjs/storybook/blob/next/app/angular/src/client/preview/angular-beta/StorybookWrapperComponent.ts#L136


I think I remember discussions from when the new rendering changes were starting that didn't think manually calling `ngOnChanges` would be necessary. When the changes got implemented, it probably got overlooked that it seems to still need to handle that lifecycle hook manually.

I know I hadn't noticed it being missing or thought to check for it, because I try to avoid `ngOnChanges` by using setters, whenever I can, for inputs that I need to do something on change.

**Comment by Marklb** [comment]
I think I found the problem and why it is happening, but still need to fix it.

@aavelyn Just to confirm that what I am seeing is correct for you also, is your story passing a `template`?

---

For the following component:
```ts
@Component({ selector: 'foo', template: '{{bar}}' })
class FooComponent implements OnChanges {
  @Input() bar: string;

  ngOnChanges(changes: SimpleChanges) { }
}
```

I have a test spying on `ngOnChanges` to be called, that is passing for a story like:
```ts
export const Ex = () => ({
	props: { bar: '' }
})
```

Then fails for a story like:
```ts
export const Ex = () => ({
	props: { bar: '' },
	template: `<foo></foo>`
})
```

**Comment by aavelyn** [comment]
Hi @Marklb, 
my components all use the `templateUrl` property in the decorator, which links to an html file (as it is typical in angular).

**Comment by david-dlc-cerezo** [comment]
It also happens to me.

I'm migrating from 6.1.21 to 6.3.6 and that feature broke (along with many others)

Before, if I change a value in controls it will be updating the component, now... it do nothing.

I checked that the ngOnChanges is not fired.

**Comment by newmankyle** [comment]
I've got a mostly similar problem. Storybook controls don't update the component's inputs.

* I'm using nrwl to scaffold storybook, building with the latest storybook (6.3.8)
* The component has a single @Input(). It's a setter like so: 
```typescript
@Input() set inputArg(arg: string) { 
    console.log(arg);
    this.service.arg = arg;
}
```
* Story is setup precisely like to [docs](https://storybook.js.org/docs/angular/essentials/controls#choosing-the-control-type)

The component will have it's input set initially if the arg is hard-coded in the doc, however subsequent updates never reach the component instance.

I see similar behavior if I load the story in an iframe and use the [url-arg method](https://storybook.js.org/docs/react/writing-stories/args#setting-args-through-the-url)

**Comment by DanaCoding** [comment]
@shilman 
### I have a similar problem. In the React application, Actions are not triggered.

![image](https://user-images.githubusercontent.com/93444868/143620652-87c8fbc4-2e03-4cdc-9e5b-53d8fe67c00c.png)
![image](https://user-images.githubusercontent.com/93444868/143620736-532da5cf-feb7-4085-bce2-62d6077b1886.png)

**Comment by aavelyn** [comment]
bump

**Comment by costalvaro** [comment]
Had the same issue, but it's actually resolved since version 6.3.16 (https://github.com/storybookjs/storybook/pull/17156).

Try an update, I'm currently on 6.3.18 and it works fine. 👍

**Comment by shilman** [comment]
Shiver me timbers!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-alpha.52 containing PR #17633 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Egads!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.20 containing PR #17633 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```

**Comment by dionatan-g** [comment]
Up, this is not working in version 6.5.10. Can someone confirm it works on @latest?

**Comment by micheljung** [comment]
> With 8.3.3 it's never called

It turned out that it's not called if no `selector` is set. If one is set, it is called.
