### ISSUE TITLE
Storybook React, breaking on react version 17 and higher

### ISSUE THREAD

**Issue by akshayr20** [storybookjs/storybook#15617]
**Describe the bug**
Recently we updated react to version 17 and storybook started breaking with error attached below:
Sharing dependencies from package.json
kindly help us fix above issue, also do let us know if we are missing something 

**To Reproduce**
Using below dependency start storybook server: Works on react v16+ but breaks on react 17+with below error:

**Error:** 

![image](https://user-images.githubusercontent.com/31228247/126068596-4a9d1b2d-449f-4878-92e6-25ca9a76f246.png)

**Dependencies:**

```
    "react": "^17.0.2",
    "@storybook/addon-a11y": "^6.3.0",
    "@storybook/addon-actions": "^6.3.0",
    "@storybook/addon-docs": "^6.3.0",
    "@storybook/addon-knobs": "^6.3.0",
    "@storybook/addon-viewport": "^6.3.0",
    "@storybook/addons": "^6.3.0",
    "@storybook/cli": "^6.3.0",
    "@storybook/react": "^6.3.0"
```

Node version: [12, 14]
npm: [6, 7]

Tested with above configuration.

**System**
Please paste the results of `npx sb@next info` here.
![image](https://user-images.githubusercontent.com/31228247/126068831-f8ad9ea7-7164-48ed-8e16-fb4476014f9e.png)

**Additional context**

Sharing main.js for storybook config:
```
  module.exports = {
    stories: [
      '../src/**/*.stories.@(ts|tsx|js|jsx|mdx)',
      '../packages/**/*.stories.@(ts|tsx|js|jsx|mdx)',
    ],
    addons: [
      '@storybook/addon-knobs',
      '@storybook/addon-viewport',
      '@storybook/addon-a11y',
      {
        name: '@storybook/addon-docs',
        options: {
          configureJSX: true,
        },
      },
    ],
    typescript: {
      reactDocgen: false,
    },
    webpackFinal: async (config) => {
      return config;
    },
  };
```

**Comment by shilman** [comment]
Did you try removing `node_modules` and/or lockfiles and reinstalling?

**Comment by akshayr20** [comment]
Yes I did cleared packages multiple times (node modules and lock file)

**Comment by shilman** [comment]
@akshayr20 Can you please create a reproduction by running `npx sb@next repro`, following the instructions, and linking it in your issue description? We prioritize issues with reproductions over those without. Thank you! 🙏

**Comment by akshayr20** [comment]
Tried reproduce the issue and in the process got the fix.
The issue was we update react to version 17 but react-dom was still pointing at 16.8.6, after upgrading it to version 17.0.2 the issue got auto resolved. 

Thanks, closing the issue
