### ISSUE TITLE
Support for handle bar code in docs

### ISSUE THREAD

**Issue by TheLooseCannon** [storybookjs/storybook#15619]
**Is your feature request related to a problem? Please describe**
I am unable to find a proper method to display the code for a component with proper highlighting in the case of handlebar component(ember-octane syntax)

**Describe the solution you'd like**
It would be better to have a method to display ember octane hbs syntax

**Are you able to assist to bring the feature to reality?**
yes, I can...if no easy solutions exist

**Additional context**
![image](https://user-images.githubusercontent.com/39756225/126080198-ae8d1512-b62a-4125-ae28-9744224f7953.png)

this is not good enough

**Comment by shilman** [comment]
here's the workaround https://github.com/storybookjs/storybook/issues/14605

@jonniebigodes we should document this properly

**Comment by jonniebigodes** [comment]
Thanks for pointing this on my radar @shilman. Let me add it to my to-do list and adjust accordingly.

**Comment by TheLooseCannon** [comment]
> we're not going to add `.hbs` syntax highlighting out of the box. you need to manually import the HBS syntax highlighter yourself to activate it. here's the workaround: #14605
> 
> @jonniebigodes we should document this properly since this comes up fairly often

could you recommend any good hbs syntax highlighter? 
I'm using ember with glimmer components, so instead of the handle bar mustaches, we are using Angle brackets but with mustaches for arguments

**Comment by jonniebigodes** [comment]
@TheLooseCannon I've searched and come up dry, but technically prism and react-syntax-highlighter allow you to do it. As @shilman mentioned above, you could use the workaround mentioned in the issue, more specifically [here](https://github.com/storybookjs/storybook/issues/14605#issuecomment-885887417) and include ember glimmer components. 

As an example for you, I've adjusted the comment I've mentioned previously and included a sample from the Intro to Storybook tutorial. Turning the story into:
```md

import { Meta } from "@storybook/addon-docs";
import { Prism as SyntaxHighlighter } from "react-syntax-highlighter";
import { dark } from "react-syntax-highlighter/dist/esm/styles/prism";

<Meta title="Testing Syntax Highlight" />

# Diff example

This is a sample Git diff snippet example with Storybook docs.

"diff
- import { OldComponent } from 'my-package'
+ import { NewComponent } from 'my-package'
"

# Handlebars example
This is a sample ember snippet example with Storybook docs

"handlebars
<div class="list-item {{@task.state}}" data-test-task>
  <label class="checkbox">
    <input
      type="checkbox"
      disabled
      name="checked"
      checked={{this.isArchived}}
    />
    <span
      class="checkbox-custom"
      data-test-task-archive
      {{on "click" this.archive}}
    ></span>
  </label>
  <div class="title">
    <input
      type="text"
      readonly
      value={{@task.title}}
      placeholder="Input title"
    />
  </div>
  <div class="actions">
    {{#unless this.isArchived}}
      <span data-test-task-pin {{on "click" this.pin}}>
        <span class="icon-star"></span>
      </span>
    {{/unless}}
  </div>
</div>
"

export const Component = () => {
  const codeString = "(num) => num + 1";
  return (
    <SyntaxHighlighter language="javascript" style={dark}>
      {codeString}
    </SyntaxHighlighter>
  );
};
```

Once again, the usage of quotes (") is intended for proper parsing of the code here.


I started Storybook and it yielded the following:
![Storybook-hbs](https://user-images.githubusercontent.com/22988955/126874008-20ef00c5-2c90-4bfc-a95b-2c7b1a22b129.png)

As you can see, it's properly highlighted. I know this is not ideal, but more of a compromise. But if you adjust your implementation following up the instructions mentioned, you can add into your Storybook the component's implementation fully highlighted. 

Stay safe

**Comment by eric-helier** [comment]
For anyone looking for a nowadays approach on this, here is how we made it work with @storybook/html and @storybook/html-vite v8
- in your csf stories file, just import hbs files like this : `import Template from "./template.hbs?raw`
- in render method, `return handlebars.compile(Template)(parameters)`

Works like a charm, no need for any additional setup or dependency.
I found this approach much more powerful than the documented way of building html stories templates with dom API (createElement, appendChild, etc.)
Handlebars templates support conditions, for loops, and imports, that's very useful for non atomic components.
Could work with any templating engine of your preference also.

**Comment by McGern** [comment]
@eric-helier thanks for the info. Is there any chance you would be able to post a full sample story file please? I'm struggling with where to put the parts you mentioned in your post.

**Comment by eric-helier** [comment]
@McGern here is a full example

Button.hbs
```
<button class="ds-button ds-button--{{size}} ds-button--{{variant}}" {{#if disabled}}disabled{{/if}}>
  {{label}}
</button>
```

Button.stories.js
```
import Handlebars from "handlebars";
import Template from "./Button.hbs?raw";

// render button html template with handlebars
const renderButton = ({ disabled = false, size = "md", variant = "secondary", ...args }) =>
  Handlebars.compile(Template)({
    disabled,
    size,
    variant,
    ...args,
  });

// More on how to set up stories at: https://storybook.js.org/docs/writing-stories
export default {
  title: "Components/Button",
  tags: ["autodocs"],
  render: renderButton,
  argTypes: {
    label: { control: "text" },
    variant: {
      control: { type: "select" },
      options: ["primary", "secondary"],
    },
    size: {
      control: { type: "select" },
      options: ["xs", "sm", "md", "lg", "xl"],
    },
    disabled: { control: "boolean" },
  },
};

// More on writing stories with args: https://storybook.js.org/docs/writing-stories/args
export const Primary = {
  args: {
    variant: "primary",
    label: "Button",
  },
};

export const Variants = {
  argTypes: { variant: { table: { disable: true } } },
  render: (args) => {
    return [
      renderButton({
        ...args,
        variant: "primary",
        label: args.label || "Primary",
      }),
      renderButton({
        ...args,
        variant: "secondary",
        label: args.label || "Secondary",
      }),
    ].join("\n&nbsp;\n");
  },
};

export const Sizes = {
  argTypes: { size: { table: { disable: true } } },
  render: (args) => {
    return [renderButton({
      ...args,
      label: args.label || "Extra large",
      size: "xl",
    }),
    renderButton({
      ...args,
      label: args.label || "Large",
      size: "lg",
    }),
    renderButton({
      ...args,
      label: args.label || "Medium",
      size: "md",
    }),
    renderButton({
      ...args,
      label: args.label || "Small",
      size: "sm",
    }),
    renderButton({
      ...args,
      label: args.label || "Extra small",
      size: "xs",
    })].join("\n&nbsp;\n");
  },
};
```

**Comment by McGern** [comment]
@eric-helier Thank you so much for this. I had stumbled across something similar by accident, but the additional renderFunction  and setup is handy. 

Wondering how you dealt with adding partials? I ended up just putting them into the preview.js something like this

```
import handlebars from 'handlebars';
import button from '../src/components/core-components/button/button.hbs?raw';

handlebars.registerPartial('button', button);
```

**Comment by eric-helier** [comment]
> @eric-helier Thank you so much for this. I had stumbled across something similar by accident, but the additional renderFunction and setup is handy.
> 
> Wondering how you dealt with adding partials? I ended up just putting them into the preview.js something like this
> 
> ```
> import handlebars from 'handlebars';
> import button from '../src/components/core-components/button/button.hbs?raw';
> 
> handlebars.registerPartial('button', button);
> ```

Honestly we did not go more far than just testing with this simple button component as of today.
I imagine partials would be interesting once you start to build more complex components that include other components right ?
Did not think about how to best manage this but I'm very interested if you come up with an elegant approach without duplicating the html templates of child components in complex components templates.
