### ISSUE TITLE
Storybook Theming: Remove use of "normal" theme and language

### ISSUE THREAD

**Issue by darleendenno** [storybookjs/storybook#15631]
**Is your feature request related to a problem? Please describe**
The [language surrounding theme configuration](https://storybook.js.org/docs/react/configure/theming) is extremely bothersome -- "normal" for light theme and "dark" for dark.

**Describe the solution you'd like**
I propose we use "light" for light themes, and "dark" for dark themes. I understand this could be a breaking change, but it's worthwhile, or could maybe be coded to be backwards-compatible.

**Are you able to assist to bring the feature to reality?**
😄 ❤️ 🚀  absolutely, but I highly encourage someone to grab it 🚀 ❤️ 😄  

**Additional context**
![image](https://user-images.githubusercontent.com/17681528/126242303-1fcb87f4-a73a-46a5-8eae-0d7f754faaed.png)

**Comment by mairagee524** [comment]
Hey, I would be down to take this issue! This would be my first time being part of an open-source project :)

**Comment by darleendenno** [comment]
@mairagee524 take it! ❤️ ❤️ ❤️  [Here is some helpful information](https://storybook.js.org/docs/react/contribute/code) for your first contribution. This issue focuses on two areas: documentation and implementation of the "normal" theme. Let us know if you get stuck or have questions!

**Comment by mairagee524** [comment]
Thank you, @darleendenno! How do I assign this issue to myself? :)

**Comment by darleendenno** [comment]
Hi @mairagee524 👋 Are you still working on this issue? Feel free to reach out if you have questions or get stuck! If you don't have availability, that's ok! Just let us know ❤️

**Comment by mairagee524** [comment]
Hi @darleendenno, yes I am still working on it! Thank you for checking in 😄

**Comment by mairagee524** [comment]
Just to be clear - am I just editing the word "normal" to say "light" on the theme documentation or are there other components that I would need to look at? Apologies if this sounds like a newbie question. Just FYI, I already have the app running locally on my machine (just need a bit of guidance on where to go) 😃

**Comment by darleendenno** [comment]
@mairagee524 that's great! I think this issue could turn into a larger feature request to entirely deprecate the "normal" theme in favor of better naming. That will be a large refactor over many codebases (search for `theme.normal` within storybook to see how frequently it's used). 

Let's keep this issue simple and update the language for the documentation 👍 @shilman @jonniebigodes do you agree? 

You can find the docs at `docs/configure/theming.md`. Thanks again for working on this ❤️

**Comment by jonniebigodes** [comment]
@darleendenno sounds good to me! @mairagee524 let me know once the pull request is up and I'll gladly follow up with you on it.

Sounds good?

**Comment by mairagee524** [comment]
Sounds good - I'll update only the documentation. Perhaps down the road, I could change the naming across the whole app (hopefully 🙏🏽)

**Comment by Abhishek-90** [comment]
@darleendenno will it be okay if while @mairagee524 is working on changing the documentation, I can  change the naming across the whole application. This can be my very first contribution to an open source project :smiley:

**Comment by RabbitEarsDesign** [comment]
Is this still outstanding? I am interested in tackling if need be!

**Comment by richorrichard** [comment]
I saw that that the previous assignee had been removed and created a quick PR to solve this issue. I also took a first look through the codebase to try and find instances where themes.default were used, and it doesn't look like it's as pervasive as it was previously. I'll open a new issue to replace the wording in the codebase per @darleendenno 's recommendation. Please let me know if you need anything else!

**Comment by darleendenno** [comment]
That sounds great @richorrichard -- I'll consider this issue closed in favor of another issue that directly references the required work. Thanks for all of your hard work!
