### ISSUE TITLE
Error: Compiling RuleSet failed: Unexpected property test in condition with fresh install of vue 2 with cli and storybook webpack5 builder

### ISSUE THREAD

**Issue by jordangunther** [storybookjs/storybook#15641]
**Describe the bug**
Using Vue CLI to generate a new vue2 project and then installing storybook with webpack 5 (npx sb init --builder webpack5) results in the below error when running npm run storybook

3% setup runERR! Error: Compiling RuleSet failed: Unexpected property test in condition (at ruleSet[1].rules[1].resource.test: resource => {
ERR!         currentResource = resource
ERR!         return true
ERR!       })

Here is my package.json:
{
  "name": "app",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "test:unit": "vue-cli-service test:unit",
    "lint": "vue-cli-service lint",
    "storybook": "start-storybook -p 6006",
    "build-storybook": "build-storybook"
  },
  "dependencies": {
    "core-js": "^3.6.5",
    "vue": "^2.6.11"
  },
  "devDependencies": {
    "@babel/core": "^7.14.8",
    "@storybook/addon-actions": "^6.3.4",
    "@storybook/addon-essentials": "^6.3.4",
    "@storybook/addon-links": "^6.3.4",
    "@storybook/builder-webpack5": "^6.3.4",
    "@storybook/manager-webpack5": "^6.3.4",
    "@storybook/vue": "^6.3.4",
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-plugin-unit-jest": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "@vue/eslint-config-prettier": "^6.0.0",
    "@vue/test-utils": "^1.0.3",
    "babel-eslint": "^10.1.0",
    "babel-loader": "^8.2.2",
    "eslint": "^6.7.2",
    "eslint-plugin-prettier": "^3.3.1",
    "eslint-plugin-vue": "^6.2.2",
    "prettier": "^2.2.1",
    "sass": "^1.26.5",
    "sass-loader": "^8.0.2",
    "vue-loader": "^15.9.7",
    "vue-template-compiler": "^2.6.11"
  }
}

**To Reproduce**
Please create a reproduction by running `npx sb@next repro` and following the instructions. Read our [documentation](https://storybook.js.org/docs/react/contribute/how-to-reproduce) to learn more about creating reproductions.
Paste your repository and deployed reproduction here. We prioritize issues with reproductions over those without.

https://github.com/jordangunther/vue2-storybook-webpack5-reproduction is the link to the reproduction repo. This is working but it looks like it isn't using webpack 5.

**System**
Please paste the results of `npx sb@next info` here.

Environment Info:

  System:
    OS: macOS 11.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.16.1/bin/yarn
    npm: 7.20.0 - ~/.nvm/versions/node/v14.16.1/bin/npm
  Browsers:
    Chrome: 91.0.4472.164
    Firefox: 89.0.2
    Safari: 14.1.1
  npmPackages:
    @storybook/addon-actions: ^6.3.4 => 6.3.4 
    @storybook/addon-essentials: ^6.3.4 => 6.3.4 
    @storybook/addon-links: ^6.3.4 => 6.3.4 
    @storybook/builder-webpack5: ^6.3.4 => 6.3.4 
    @storybook/manager-webpack5: ^6.3.4 => 6.3.4 
    @storybook/vue: ^6.3.4 => 6.3.4 

**Additional context**

**Comment by shilman** [comment]
I've added a PR to your reproduction that adds webpack5 support and seems to work fine: https://github.com/jordangunther/vue2-storybook-webpack5-reproduction/pull/1

**Comment by K3TH3R** [comment]
> I've added a PR to your reproduction that adds webpack5 support and seems to work fine: [jordangunther/vue2-storybook-webpack5-reproduction#1](https://github.com/jordangunther/vue2-storybook-webpack5-reproduction/pull/1)

I was still seeing this error after following the PR and making sure all my dependencies highlighted there were updated. It turned out that my `vue-loader` dependency was `@15.9.3`. When I upgraded that to the most recent version (`15.9.8`) it fixed the RuleSet error and allowed me to run Storybook again.
