### ISSUE TITLE
Docs stories.mdx format from version 6.3.3 does not work with Angular

### ISSUE THREAD

**Issue by ardentia** [storybookjs/storybook#15648]
**Describe the bug**
I recently had to update Storybook to work with Angular 12. I used `.stories.mdx` to document the components and the storybook project doesn't compile due to this:

```
99% done plugins webpack-hot-middlewarewebpack built preview dedbda1db705c5c855a2 in 16124ms
ModuleBuildError: Module build failed (from ./node_modules/@mdx-js/loader/index.js):
SyntaxError: D:\Work\storybook\reproduction\src\app\test\test.component.stories.mdx: Missing semicolon. (9:1)

  7 |     }),
  8 |   ],
> 9 | } as Meta;
    |  ^
    at Object._raise (D:\Work\storybook\reproduction\node_modules\@babel\parser\lib\index.js:788:17)
    at Object.raiseWithData (D:\Work\storybook\reproduction\node_modules\@babel\parser\lib\index.js:781:17)
    at Object.raise (D:\Work\storybook\reproduction\node_modules\@babel\parser\lib\index.js:742:17)
    at Object.semicolon (D:\Work\storybook\reproduction\node_modules\@babel\parser\lib\index.js:9899:10)
    at Object.parseExportDefaultExpression (D:\Work\storybook\reproduction\node_modules\@babel\parser\lib\index.js:13795:12)
    at Object.parseExport (D:\Work\storybook\reproduction\node_modules\@babel\parser\lib\index.js:13704:31)
    at Object.parseStatementContent (D:\Work\storybook\reproduction\node_modules\@babel\parser\lib\index.js:12686:27)
    at Object.parseStatement (D:\Work\storybook\reproduction\node_modules\@babel\parser\lib\index.js:12580:17)
    at Object.parseBlockOrModuleBlockBody (D:\Work\storybook\reproduction\node_modules\@babel\parser\lib\index.js:13169:25)
    at Object.parseBlockBody (D:\Work\storybook\reproduction\node_modules\@babel\parser\lib\index.js:13160:10)
    at Object.parseProgram (D:\Work\storybook\reproduction\node_modules\@babel\parser\lib\index.js:12501:10)
    at Object.parseTopLevel (D:\Work\storybook\reproduction\node_modules\@babel\parser\lib\index.js:12492:25)
    at Object.parse (D:\Work\storybook\reproduction\node_modules\@babel\parser\lib\index.js:14223:10)
    at parse (D:\Work\storybook\reproduction\node_modules\@babel\parser\lib\index.js:14275:38)
    at parser (D:\Work\storybook\reproduction\node_modules\remark-mdx\node_modules\@babel\core\lib\parser\index.js:54:34)
    at parser.next (<anonymous>)
    at processResult (D:\Work\storybook\reproduction\node_modules\@storybook\builder-webpack5\node_modules\webpack\lib\NormalModule.js:701:19)
    at D:\Work\storybook\reproduction\node_modules\@storybook\builder-webpack5\node_modules\webpack\lib\NormalModule.js:807:5
    at D:\Work\storybook\reproduction\node_modules\loader-runner\lib\LoaderRunner.js:399:11
    at D:\Work\storybook\reproduction\node_modules\loader-runner\lib\LoaderRunner.js:251:18
    at context.callback (D:\Work\storybook\reproduction\node_modules\loader-runner\lib\LoaderRunner.js:124:13)
    at Object.loader (D:\Work\storybook\reproduction\node_modules\@mdx-js\loader\index.js:20:12)

WARN Broken build, fix the error above.
```

**To Reproduce**
https://github.com/ardentia/storybook-mdx-issue
More specifically, look at this: https://github.com/ardentia/storybook-mdx-issue/edit/main/src/app/test/test.component.stories.mdx

I am aware that the `.stories.mdx` files require a `<Meta ...>` tag but following the docs, this didn't compile also:
```typescript
import { Story } from '@storybook/angular';
import { Meta } from '@storybook/addon-docs';
import { TestComponent } from './test.component';

<Meta title="Preview/Test" component = { TestComponent } />

const Template: Story<TestComponent> = (args) => ({
  template: `
    <app-test></app-test>
    `,
  props: args
});

export const Default = Template.bind({});
```

**System**
```
Environment Info:

  System:
    OS: Windows 10 10.0.19043
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 91.0.4472.124
    Edge: Spartan (44.19041.1023.0), Chromium (91.0.864.71)
  npmPackages:
    @storybook/addon-actions: ^6.3.3 => 6.3.3
    @storybook/addon-docs: ^6.3.3 => 6.3.3
    @storybook/addon-essentials: ^6.3.3 => 6.3.3
    @storybook/addon-links: ^6.3.3 => 6.3.3
    @storybook/angular: ^6.3.3 => 6.3.3
    @storybook/builder-webpack5: ^6.3.3 => 6.3.3
    @storybook/manager-webpack5: ^6.3.3 => 6.3.3
```

**Comment by jonniebigodes** [comment]
@ardentia I've picked up on your issue and I'm going to detail the steps I took to triage this:
- Cloned the repo you've mentioned.
- Ran `yarn` to install dependencies. 
- Checked the mdx story you've mentioned and adjusted it to the following:
   ```md
     import { Meta, Story, Canvas } from "@storybook/addon-docs";
     import { TestComponent } from "./test.component";

     <Meta title="Preview/Test" component={TestComponent} />

     # TestComponent

    Test component running inside `MDX` and Canvas with Storybook 6.4 alpha

    export const Template = (args) => ({ props: args });

    <Canvas withToolbar>
      <Story name="test-component-with-canvas">{Template.bind({})}</Story>
    </Canvas>

    ## Another Test

   Test component running inside `MDX` without `Canvas` block with Storybook 6.4 alpha

   <Story name="test-component-without-canvas">{Template.bind({})}</Story>
   ```
 - Ran `yarn storybook` and it yielded the following:
   

https://user-images.githubusercontent.com/22988955/127575091-84a78720-c026-4188-a301-17a2f62a373b.mp4

As you can see Storybook and Angular 12 are working ok. No issues there. Ran a production build with `yarn build-storybook` same result.

I saw that in your description you were mentioning Angular 12 and 6.3 and I adjusted accordingly.
- Created a new branch called `downgrade_to_6_3`.
- Deleted `node_modules` and `yarn.lock`.
- Adjusted the Storybook dependencies to the latest stable release, and minor tweaks to the story, turning `package.json` and the story into:
![Angular-12-stable](https://user-images.githubusercontent.com/22988955/127575491-aa623727-868e-48ca-98b0-2d58d5bb3eb3.png)
- Ran `yarn` once more to install the dependencies. No issues there whatsoever.
- Ran `yarn storybook` to start Storybook and as you can see it's now running with 6.3.6
![cli-output-stable](https://user-images.githubusercontent.com/22988955/127575638-b78379b5-84b7-48b4-9745-da4cf9aeb086.png)
- Checked the browser and it yielded the following:

https://user-images.githubusercontent.com/22988955/127575883-b3342993-4d5d-4397-be7e-3c392ee0fd93.mp4



Let me know and I'll gladly push what's documented here into a pr in your reproduction. Let me know and we'll go from there. 

Stay safe

**Comment by ardentia** [comment]
Hello, @jonniebigodes, thank you for taking this on. If possible, could you please push the changes to the mdx story, along with the downgrade?

**Comment by jonniebigodes** [comment]
@ardentia no need to thank whatsoever, if you check your reproduction repository you should see a couple of pull requests that I've made! One is based on 6.4 alpha release and the other one is for the latest stable release of Storybook!

I left your original approach, but renamed the file "test.component.boop.mdx" so it doesn't interfere with Storybook. 

Let me know of any further developments to your question so that we can continue to work on it or we're good to close the issue.

Stay safe

**Comment by jonniebigodes** [comment]
@ardentia I saw that you merged the pull request that I made in your reproduction repository. I'm assuming that it helped you get unblocked and able to write stories for your components, more even with the explanation mentioned above. Hope you don't mind I'm going to close this issue. 

Feel free to reach out to me if you run into any problems and I'll gladly re-open and continue to work with you on it, until we find a suitable solution. Sounds good?

Stay safe

**Comment by ardentia** [comment]
Hello again, @jonniebigodes . I merged your PR to test it out. As you mentioned, I deleted node_modules and and I ran a fresh `npm install`. I then deleted my old `test.component.stories.mdx` file and used the `test.component.boop.mdx` file instead by replacing the "boop" with "stories". I ran `npm run storybook` and this time I got the following error:
```
ModuleBuildError: Module build failed (from ./node_modules/@mdx-js/loader/index.js):
SyntaxError: D:\Work\storybook\reproduction\src\app\test\test.component.stories.mdx: Missing semicolon. (9:1)

  7 |     }),
  8 |   ]
> 9 | } as Meta;
```

It is still unclear to me what I did wrong and I would appreciate your help.

**Comment by jonniebigodes** [comment]
Hi @ardentia. I got the notification and was glad that you'd merged the pull request. And let me start by apologizing if I wasn't clear with my explanation and the pull request that I've made into your reproduction. 

To give you more context on how to write stories, in this case for Angular and MDX.
If you want to write your stories as TypeScript files, you're more than welcome, and you should use the approach used in the file, which I renamed to `test.component.boop.mdx`, naming it `test.component.ts`. In that case, when you start Storybook, you'll see the component's stories you've defined, inputs if present, and generate automatic documentation for it. 

With MDX, the recommended way is a bit different. If you want to write your stories with that format, you should use the approach implemented in `test.component.stories.mdx`. When you start Storybook, you'll see almost the same. In your Canvas tab, you'll see that the component's stories are rendered, its inputs displayed as they should. But with a small difference once you check the Docs tab. There you'll see that the documentation is expanded a bit more. 

That's the beauty of Storybook. As you're not bound to a specific writing format, you can use the "traditional way" (pardon the bad pun) and use TypeScript and get your stories rendered and the essential documentation displayed. Or you can write your own markdown, customize it as you wish, add a couple of imports, and you should see your component's stories rendered as they normally would with TypeScript and your documentation customized to your needs.

It's up to you. 

I left the `.boop.mdx` to provide you with a baseline comparison on writing the stories for the component. 

Let me know if you have any more questions, and we'll go from there.

I'm more than happy to follow up on this and get you unblocked as soon as possible for you to start writing your stories.

Stay safe.

**Comment by ardentia** [comment]
Hello @jonniebigodes! Thank you again for the quick response and also for the thorough explanation.
I think I understand the differences now. I also saw that the Angular docs have been updated with more information on how to write stories in `.mdx` format which is great! I don't have anymore questions :)

**Comment by jonniebigodes** [comment]
@ardentia no need to thank! Glad that I was able to provide you with some context on your issue. Indeed the documentation was recently updated to contain MDX examples for some of the frameworks. Feel free to reach out to us if you have any further issues with Storybook!

Stay safe
