### ISSUE TITLE
Feature request: Adding mdx blocks documentation

### ISSUE THREAD

**Issue by pfmartins4** [storybookjs/storybook#15653]
**Is your feature request related to a problem? Please describe**
The MDX blocks provided are poorly documented. Frequently i have to browse in the source code to find out how to get one of them working

**Describe the solution you'd like**
Would be great to have a documentation of each Block provided by storybook. I is specially helpfull when documenting hooksor helpers 

**Describe alternatives you've considered**
I didn't. Tho, the code is very readable and clean. 

**Are you able to assist to bring the feature to reality?**
yes, I can help to document some of them, but it's hard for me to document a large number.

**Comment by shilman** [comment]
Have you checked out these docs? https://storybook.js.org/docs/react/writing-docs/doc-blocks

Improvements are always very welcome! 🙏

**Comment by pfmartins4** [comment]
Yes I have, but they are far from complete. They don't mention a lot of block and they props. I struggled a lot to use do `<Source/>` block to document a hook.

**Comment by pfmartins4** [comment]
I never contributed to opensource. Whta's the path to improve the documentation?

**Comment by jonniebigodes** [comment]
@pfmartins4 we have documentation on how to get you started contributing to Storybook. See [here](https://storybook.js.org/docs/react/contribute/how-to-contribute).

**Comment by alvis** [comment]
I agree there are some documentation issues. It's the reason I'm here while I'm looking for a reason why my storybook looks different from others. Let's improve it.

**Comment by jonniebigodes** [comment]
With the recent pull request that was just merged the documentation was updated to include additional information and examples about the Docs blocks. 

Feel free to raise any additional issues and let me know about improvements to the existing documentation. Would love to hear everyone's thoughts.


Thanks for raising this and sorry for the delayed response.

Hope all of you have a great day and stay safe
