### ISSUE TITLE
Syntax Error and Type Error after installing jest and addon-storyshots

### ISSUE THREAD

**Issue by rexkenley** [storybookjs/storybook#15667]
**Describe the bug**
Running npm test results in Syntax Error and Type Error. I followed the instructions in the [documentation](https://www.npmjs.com/package/@storybook/addon-storyshots)

![image](https://user-images.githubusercontent.com/10548251/126810664-a70c775b-806d-4808-8a63-aa6b30374821.png)
![image](https://user-images.githubusercontent.com/10548251/126810676-24a0b6c1-6979-47e6-b382-3cd4da417eda.png)

**To Reproduce**
Download my [repo](https://github.com/rexkenley/jestTest) and run npm test

**System**
System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
  Binaries:
    Node: 14.17.1 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 91.0.4472.164
    Edge: Spartan (44.19041.1023.0), Chromium (91.0.864.71)
  npmPackages:
    @storybook/addon-actions: ^6.3.5 => 6.3.5
    @storybook/addon-essentials: ^6.3.5 => 6.3.5
    @storybook/addon-links: ^6.3.5 => 6.3.5
    @storybook/addon-storyshots: ^6.3.5 => 6.3.5
    @storybook/react: ^6.3.5 => 6.3.5

**Comment by rexkenley** [comment]
Marcuse7 suggested that I use jest 26, jest-svg-transformer and jest-css-modules-transform. It seems to help get past the first couple of issue, but I am getting some new ones.

![image](https://user-images.githubusercontent.com/10548251/127701928-4a2e6382-8d83-4af4-9c0c-12d316fb6899.png)

![image](https://user-images.githubusercontent.com/10548251/127701940-55e8195f-072b-4707-b441-cefa9a480949.png)

I have updated my repo that will reproduce the error.

**Comment by ndelangen** [comment]
The future of storyshots is the test-runner:
https://storybook.js.org/docs/react/writing-tests/test-runner#page-top

And use the play function for expectations:
https://storybook.js.org/docs/react/writing-stories/play-function#page-top

We will not be making any improvement / changes to storyshots.
