### ISSUE TITLE
Vue packages version mismatch

### ISSUE THREAD

**Issue by robertskovacs** [storybookjs/storybook#15677]
I tried to use custom svg icons in vue3 + storybook project. I added vue-svg-loader to the webpack config and modified the regex of file loader, however i got now the following error:

ERROR in ./src/assets/svg/paypal.svg
Module build failed (from ./node_modules/vue-svg-loader/index.js):
Error:

Vue packages version mismatch:

- vue@3.1.5 (C:\Users\rober\Documents\GitHub\ecommerce-design-system\node_modules\vue\index.js)
- vue-template-compiler@2.6.14 (C:\Users\rober\Documents\GitHub\ecommerce-design-system\node_modules\vue-template-compiler\package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

The .storybook/main.js includes the following part:

```
config.module.rules = config.module.rules.map(rule => {
      {
          if (String(rule.test) === String(/\.(svg|ico|jpg|jpeg|png|gif|eot|otf|webp|ttf|woff|woff2|cur|ani)(\?.*)?$/)) {
              return {
                  ...rule,
                  test: /\.(ico|jpg|jpeg|png|gif|eot|otf|webp|ttf|woff|woff2|cur|ani)(\?.*)?$/,
              };
          }

          return rule;
      }
  });

    // Make whatever fine-grained changes you need
    config.module.rules.push(
      {
        test: /\.svg$/,
        use: ['vue-svg-loader']
      },
      {
        test: /\.scss$/,
        use: ['style-loader', 'css-loader', 'sass-loader'],
        include: path.resolve(__dirname, '../'),
      }
    );
```

Dependencies:
"vue": "^3.1.5",
"vue-loader": "^16.3.3",
"vue-template-compiler": "^2.6.14"
"@storybook/vue3": "^6.3.5",

**Comment by shilman** [comment]
@robertskovacs what's the fix?

**Comment by robertskovacs** [comment]
I tried the suggestions from this post, but nothing worked.
https://stackoverflow.com/questions/64868632/vuejs-3-problem-with-vue-template-compiler
