### ISSUE TITLE
Storybook doc shows source code inside <template> tag

### ISSUE THREAD

**Issue by ranjanngc** [storybookjs/storybook#15681]
**Describe the bug**
Storybook Docs displays a story’s source code using the Source block. The snippet has built-in syntax highlighting and can be copied with the click of a button.
But, with VueJS unnecessary <template> tag is wrapped around.
`
<template>
  <asi-button size="" :outline="false" icon="" label="Button" type="button" />
</template>
` 

**To Reproduce**
This is how I am writing storybook
`
import AsiButton from '../../controls/button/button.vue';

export default {
  title: 'Controls/Form/Button',
  component: AsiButton,
  argTypes: {
    variant: { control: {type: 'select', options: ['primary', 'secondary']} },

  }
};

const Template = (args, { argTypes }) => ({
  props: Object.keys(argTypes),
  components: { AsiButton },
  template: '<asi-button @onClick="onClick" v-bind="$props"></asi-button>',
});

export const Primary = Template.bind({});
Primary.args = {
  label: 'Button',
  type: 'button'
};
`
**System**
    "@storybook/addon-actions": "^6.3.2",
    "@storybook/addon-essentials": "^6.3.2",
    "@storybook/addon-links": "^6.3.2",
    "@storybook/theming": "^6.3.2",
    "@storybook/vue": "^6.3.2",

**Additional context**

**Comment by prinzt** [comment]
Also mentioned here: https://github.com/storybookjs/storybook/issues/14853

**Comment by vandor** [comment]
I'm running into this as well. Here's a workaround:

In preview.js
```js
export const parameters = {
  docs: {
    transformSource(src) {
      const match = /^<template>(.*)<\/template>/.exec(src)
      if(match) {
        return match[1]
      }
      return src
    }
  }
}
```

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
