### ISSUE TITLE
ModuleNotFoundError: Module not found: Error: Can't resolve 'core-js/modules/es6.promise.js' in '/Users/<USER>/<PROJECT_DIR>/<PROJECT/node_modules/@storybook/addon-docs/node_modules/prettier'

### ISSUE THREAD

**Issue by sha256rma** [storybookjs/storybook#15683]
**Describe the bug**

After running `npx sb init` and then `yarn storybook`, I get a bunch of `ModuleNotFoundError`s. If it helps, I am using:

    "@babel/core": "^7.14.3",
    "@babel/preset-env": "^7.14.4",
    "babel-core": "^7.0.0-bridge.0",
    "babel-jest": "^27.0.2",

**To Reproduce**

I am using `vue 2.6.14`
After running `npx sb init`, I got:

```
    "@storybook/addon-actions": "^6.3.6",
    "@storybook/addon-essentials": "^6.3.6",
    "@storybook/addon-links": "^6.3.6",
    "@storybook/vue": "^6.3.6",
```

Then I ran `yarn storybook` and that is when tons of errors came of the type: `ModuleNotFoundError: Module not found: Error: Can't resolve 'core-js/modules/...'`

**System**

Environment Info:

```
  System:
    OS: macOS 11.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Binaries:
    Node: 14.17.3 - ~/.nvm/versions/node/v14.17.3/bin/node
    Yarn: 1.22.11 - ~/<PROJECT_DIR>/<PROJECT>/node_modules/.bin/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.3/bin/npm
  Browsers:
    Chrome: 92.0.4515.107
    Safari: 14.1.2
  npmPackages:
    @storybook/addon-actions: ^6.3.6 => 6.3.6 
    @storybook/addon-essentials: ^6.3.6 => 6.3.6 
    @storybook/addon-links: ^6.3.6 => 6.3.6 
    @storybook/vue: ^6.3.6 => 6.3.6 
```

**Additional context**

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
