### ISSUE TITLE
When using the controls addon - add id to the 'Set' button displayed when an arg value is undefined

### ISSUE THREAD

**Issue by revik** [storybookjs/storybook#15690]
**Is your feature request related to a problem? Please describe**
We rely on storybook for our automation testing - we need to be able to select the controls and interact with them by id or some other deterministic way. (also the 'Set' button for undefined args)

**Describe the solution you'd like**
Add an id to the 'Set' button (can be `set-propName` or any other deterministic id)

**Describe alternatives you've considered**
Any alternative solutions or features you've considered.

**Are you able to assist to bring the feature to reality?**
Yes I can

**Additional context**
This a screenshot of a control that has a value, with a deteministic id of `control-someBoolean`,
and the 'Set' button of the control with no value has no id, in this example it would be `set-isDisabled`
<img width="890" alt="Screen Shot 2021-07-27 at 12 53 10" src="https://user-images.githubusercontent.com/7070004/127134805-f0163ce2-5ec1-4800-aee3-9f2edccf0dc3.png">

**Comment by shilman** [comment]
@revik this looks good! any interest in contributing a PR to make this happen? We've documented [how to contribute](https://storybook.js.org/docs/react/contribute/code) and there's also a `#contributing` channel on the [Storybook discord](https://discord.gg/storybook) if you have questions.

**Comment by revik** [comment]
Sure. Would love to give it a try 🙂

**Comment by shilman** [comment]
Hurrah!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-alpha.31 containing PR #15729 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
