### ISSUE TITLE
Angular i18n plurals fails with "Unable to parse ICU expression" error

### ISSUE THREAD

**Issue by david-dlc-cerezo** [storybookjs/storybook#15703]
**Describe the bug**
I trying to upgrade from version 6.1.21 to latest stable 6.3.6 maintaining every other version untouched (Angular 11.1.1)
After upgrading the stories to adapt to the changes between this two versions I got most of them working, but in that ones that use angular i18n plurals (https://angular.io/guide/i18n#mark-plurals) errors displaying a console.error like this one:
`ERROR Error: Unable to parse ICU expression in "Updated {VAR_PLURAL, plural, =0 {just now} =1 {one minute ago} other {{INTERPOLATION} minutes ago}}" message.`
![image](https://user-images.githubusercontent.com/727260/127345048-070e0866-e50b-405f-9d13-cc60e8f8b3a3.png)

**To Reproduce**
Simple story as this one: 
```typescript
import { Component, Input } from '@angular/core';
import { Meta, Story, StoryContext } from '@storybook/angular';
import { StoryFnAngularReturnType } from '@storybook/angular/dist/ts3.9/client/preview/types';

@Component({
  template: `<h1>Sample Plurals</h1>
    <p><span i18n>minutes</span>: {{ minutes }}</p>
    <p i18n>Updated {minutes, plural, =0 {just now} =1 {one minute ago} other {{{minutes}} minutes ago}}</p>`,
})
class SamplePluralsComponent {
  @Input() minutes = 10;
}

export default {
  title: 'Sample/Plurals',
  component: SamplePluralsComponent,
  parameters: { controls: { hideNoControlsWarning: true } },
} as Meta;

const Template: Story<SamplePluralsComponent> = (args: SamplePluralsComponent, context: StoryContext): StoryFnAngularReturnType =>
  ({
    moduleMetadata: {
      declarations: [SamplePluralsComponent],
      entryComponents: [SamplePluralsComponent],
      exports: [SamplePluralsComponent],
    },
    props: args,
  } as StoryFnAngularReturnType);

export const Default: Story<SamplePluralsComponent> = Template.bind({});
```

If you remove the line `<p i18n>Updated {minutes, plural, =0 {just now} =1 {one minute ago} other {{{minutes}} minutes ago}}</p>` the story works. 
This story is also useful to test #15610 (`ngChanges` does not trigger): Changing the minutes value won't change it in the displayed story

**System**
  System:
    OS: Linux 5.10 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
  Binaries:
    Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
    npm: 6.14.12 - ~/.nvm/versions/node/v14.16.1/bin/npm

**Additional context**
On storybook version 6.1.21 this worked fine, and didn't error.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid.

Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
