### ISSUE TITLE
build-storybook throws `esm is not defined` after successful build

### ISSUE THREAD

**Issue by KL13NT** [storybookjs/storybook#15710]
### Discussed in https://github.com/storybookjs/storybook/discussions/15704

<div type='discussions-op-text'>

<sup>Originally posted by **KL13NT** July 28, 2021</sup>
Hi! 

I have a project in which I'm using Storybook, TypeScript, and React. Storybook works wonders in development, but doesn't after building. Once I build and try to `http-server` the output directory, I navigate to the storybook and it seems to be loading but then goes completely blank and throws `esm is not defined` in the console. 

![image](https://user-images.githubusercontent.com/20807178/127348743-cbfb18ce-e1b2-4598-b97e-77e2943a21d5.png)

Everything works fine in development, though. 

---

```json
// tsconfig.json
{
	"jsx": "react",
	"rootDirs": [
		"src"
	],
	"allowJs": false,
	"include": [
		"./src/**/*"
	],
	"compilerOptions": {
		"allowSyntheticDefaultImports": true,
		"moduleResolution": "node",
		"module": "es6",
		"target": "es6",
		"baseUrl": "./",
		"paths": {
			"@qalam/*": ["src/*"],
		},
		"resolveJsonModule": true,
		"noFallthroughCasesInSwitch": true,
		"allowUnusedLabels": false,
		"noImplicitOverride": true,
		"noImplicitReturns": true,
		"noPropertyAccessFromIndexSignature": true,
		"strict": true,
		"esModuleInterop": true,
		"lib": [
			"dom",
			"es2021"
		],
		"jsx": "react-jsx"
	},
	"exclude": [
		"node_modules",
		"dist"
	]
}
```

```js
// babel.config.js
module.exports = {
	sourceType: 'unambiguous',
	presets: [
		[
			'@babel/preset-env',
			{
				targets: {
					node: 'current',
				},
			},
		],
		[
			'@babel/preset-react',
			{
				runtime: 'automatic',
			},
		],
		'@babel/preset-typescript',
	],
	env: {
		test: {
			plugins: ['require-context-hook'],
		},
	},
};
```

```js
// webpack.config.js that I merge with Storybook's

const path = require('path');

module.exports = {
	resolve: {
		alias: {
			'@qalam': path.resolve(__dirname, 'src/'),
		},
	},
	module: {
		rules: [
			{
				test: /\.sass$/,
				exclude: /\.module\.sass$/,
				use: [
					'style-loader',
					{
						loader: 'css-loader',
						options: {
							url: false,
						},
					},
					// 'resolve-url-loader',
					{
						loader: 'sass-loader',
						options: {
							sassOptions: {
								sourceMap: true,
								sourceMapContents: false,
							},
						},
					},
				],
				include: path.resolve(__dirname, './'),
			},
			{
				test: /\.module\.sass$/,
				use: [
					'style-loader',
					{
						loader: 'css-loader',
						options: {
							url: false,
							modules: {
								mode: 'local',
								localIdentName: '[local]--[hash:base64:5]',
							},
						},
					},
					// 'resolve-url-loader',
					{
						loader: 'sass-loader',
						options: {
							sassOptions: {
								sourceMap: true,
								sourceMapContents: false,
							},
						},
					},
				],
				include: path.resolve(__dirname, './'),
			},
			// {
			// 	test: /\.(woff(2)?|ttf|eot)$/,
			// 	use: [
			// 		{
			// 			loader: 'file-loader',
			// 		},
			// 	],
			// },
			{
				test: /\.svg$/,
				use: [
					{
						loader: '@svgr/webpack',
					},
					{
						loader: 'file-loader',
					},
				],
				type: 'javascript/auto',
				issuer: {
					and: [/\.(ts|tsx|js|jsx|md|mdx)$/],
				},
			},
		],
	},
};
```

Any suggestions?

---

I just changed the glob to prevent it from seeing any stories; it still built successfully, and still threw the error. 

---

I removed all custom decorators, globalTypes, and some plugins. It works now. This probably means it's more of a problem in my code. Investigating.

---

This seems to happen with specific components only. 

---

What seems to throw the error is having the `Controls` tab open when browsing these specific components. I don't even know.</div>

**Comment by KL13NT** [comment]
Turns out I had `@storybook/builder-webpack^6.4.0-alpha.20` and `@storybook/manager-webpack^6.4.0-alpha.20`. Downgrading to `6.3.4` fixed it.

**Comment by shilman** [comment]
Sorry I missed this the first time around! 🤦‍♂️ 

I'm closing it as a dupe to #15773, which I believe is the same issue

**Comment by KL13NT** [comment]
I believe it is the same, yes. But the title seems rather misleading. It wasn't specifically a problem with `addon-controls` per se, but rather the builder itself.

**Comment by shilman** [comment]
@gaetanmaisse and I were looking at this before and we think it's related to controls
