### ISSUE TITLE
Typescript errors when using template.bind() with Story type

### ISSUE THREAD

**Issue by dexster** [storybookjs/storybook#15711]
**Describe the bug**

New typings in this commit cause typescript errors when using bind() as Story can now be a function or an object

https://github.com/storybookjs/storybook/commit/70888b3747c6d1d270f53a44183df389a029a1e7#diff-c1c2ef0d3d6300dc7fbb01f6c686034508ebdec1b5ebe6e657ba6a5f0b037f6c

TS2339: Property 'bind' does not exist on type 'Story<any>'.   Property 'bind' does not exist on type 'BaseStoryObject<any, StoryFnAngularReturnType> & Annotations<any, StoryFnAngularReturnType>'.

`export declare type BaseStory<Args, StoryFnReturnType> = BaseStoryFn<Args, StoryFnReturnType> | BaseStoryObject<Args, StoryFnReturnType>;`

When I remove the BaseStoryObject the error goes away 

`export declare type BaseStory<Args, StoryFnReturnType> = BaseStoryFn<Args, StoryFnReturnType>;`

**To Reproduce**

My template is in a helper class like so.

```
class Utils {
    template: Story = () => ({});
}

let utils = new Utils();
utils.bar.bind({});
```

Issue screenshot
![Screenshot 2021-07-29 at 15 32 55](https://user-images.githubusercontent.com/6392334/127501161-401f162f-a013-483f-9155-9104f3bfb994.png)

What is strange is that this only happens when my template is in a class, This code below does not have the error
```
const baz: Story = () => ({});
baz.bind({})
``` 

**System**

Angular 12.1.4

Environment Info:

  System:
    OS: macOS 11.5
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 14.15.5 - ~/.nvm/versions/node/v14.15.5/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.15.5/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v14.15.5/bin/npm
  Browsers:
    Chrome: 92.0.4515.107
    Edge: 92.0.902.55
    Firefox: 89.0.2
    Safari: 14.1.2
  npmPackages:
    @storybook/addon-a11y: ^6.4.0-alpha.22 => 6.4.0-alpha.22 
    @storybook/addon-actions: ^6.4.0-alpha.22 => 6.4.0-alpha.22 
    @storybook/addon-essentials: ^6.4.0-alpha.22 => 6.4.0-alpha.22 
    @storybook/addon-links: ^6.4.0-alpha.22 => 6.4.0-alpha.22 
    @storybook/angular: ^6.4.0-alpha.22 => 6.4.0-alpha.22 
    @storybook/builder-webpack5: ^6.4.0-alpha.22 => 6.4.0-alpha.22 
    @storybook/manager-webpack5: ^6.4.0-alpha.22 => 6.4.0-alpha.22

**Comment by dexster** [comment]
According to the TS docs, I'm wondering why it even works when not in a class

"TypeScript will only allow you to do things with the union if that thing is valid for every member of the union. For example, if you have the union string | number, you can’t use methods that are only available on string:"

**Comment by shilman** [comment]
@yannbf can you please take a look at this one?

**Comment by yannbf** [comment]
Hey @dexster, could you provide a sample repo or snippet with your real use case? That will help understand the situation a bit better.

Overall, it's not recommended to create wrapper/utilities to create stories. As Storybook evolves, we provide codemods for automated migrations (there's one for CSF3!), and also we can't really know all possible custom solutions people create, so it could happen that users that create custom utilities face some challenges.

**Comment by dexster** [comment]
@yannbf You can do this

1. ng new testsb
2. npx sb@next init in the new ng project

Then take the automatically generated button story that looks like this:
```
const Template: Story<Button> = (args: Button) => ({
  props: args,
});

export const Primary = Template.bind({});
Primary.args = {
  primary: true,
  label: 'Button',
}; 
```

and change it to this
```
class Utils {
  template: Story<Button> = (args: Button) => ({
    props: args,
  });
}

const utils = new Utils()

export const Primary = utils.template.bind({});
Primary.args = {
  primary: true,
  label: 'Button',
}; 
```

**Comment by yannbf** [comment]
Thanks a lot for your example! I'll be working on a possible solution to this, however I'm still puzzled as to why you would use this Utils in your project rather than just using a template function. I'm genuinely curious about the reason behind it, could you elaborate just a bit? 😄

**Comment by dexster** [comment]
I agree that a Utils class with just a template function would make no sense but my Utils class has other goodies in it as well. For example, boilerplate to set code for each story so I don't have to write this in each story
```
setCode(ctx, code) {
        ctx.parameters = {
            docs: {
                source: {
                    code: code
                }
            }
        };
    };
``` 

I also have other helpers to hide, disable Controls etc..

So I decided to add the template function here as well. I could definitely move it out the class if I need to. 

btw, my real template function also caters for templates and globals and loaders so it's more complex than this simple repro. This is my template signature

`template = (args: T & { template?: string }, {globals, loaded})   `

**Comment by yannbf** [comment]
Hey @dexster thanks for giving much more context, that was super helpful! 

Still I gotta say, as much as a custom utility class looks nice, you unfortunately lose a few perks of writing stories in the recommended way, such as automatic migration from our codemods, and you might have a less standard codebase in comparison to tutorials/docs/blog posts. There might be some complications down the line as your code stops being statically analyzable and that might affect Storybook in the upcoming versions.

I believe the only way to make it work in your use case is if we export the base type `BaseStoryFn` used to compose `Story` from `@storybook/angular`. I'll be working on it soon and will let you know!

**Comment by dexster** [comment]
I've taken a look at CSF3 and I'm happy to manually migrate. CSF3 gets rid of a lot of repetition that will probably remove the need for my utility class.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid.

Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
