### ISSUE TITLE
Failed to compile cra-kitchen-sink example

### ISSUE THREAD

**Issue by andrewluetgers** [storybookjs/storybook#15726]
**Describe the bug**
Failed to compile.

Error while loading rule '@typescript-eslint/dot-notation': You have used a rule which requires parserServices to be generated. You must therefore provide a value for the "parserOptions.project" property for @typescript-eslint/parser.
Occurred while linting /Users/andrewluetgers/Downloads/storybook-next/examples/cra-kitchen-sink/src/index.js

**To Reproduce**
download project
cd examples/cra-kitchen-sink
yarn install
yarn run start

**System**
  System:
    OS: macOS 11.5
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
    Yarn: 3.0.0-git.20210727.hash-3cbbb672 - ~/.nvm/versions/node/v12.13.0/bin/yarn
    npm: 6.12.0 - ~/.nvm/versions/node/v12.13.0/bin/npm
  Browsers:
    Chrome: 92.0.4515.107
    Firefox: 89.0.2
    Safari: 14.1.2
  npmPackages:
    @storybook/eslint-config-storybook: ^3.1.2 => 3.1.2 

**Additional context**
While attempting to file another bug I ran into this while trying to come up with a simple way to reproduce the issue.

**Comment by andrewluetgers** [comment]
I have tried other examples and have run into a range of issues, seems like an area that could use some love. ideally it should only require an install and start command for each example to work, perhaps I am doing something wrong?

**Comment by shilman** [comment]
See instructions for how to run examples here https://storybook.js.org/docs/react/contribute/code#run-tests--examples
