### ISSUE TITLE
❗ npx sb@latest upgrade not currently working

### ISSUE THREAD

**Issue by kaitlynhova** [storybookjs/storybook#15728]
**Describe the bug**
When upgrading from StorybookUI 6.2.9 you get this error:

![Screen Shot 2021-07-30 at 3 57 27 PM](https://user-images.githubusercontent.com/5474124/127719434-4bcdef29-1a2c-4b1c-842c-a5281f88f95c.png)
 

**To Reproduce**
- have a storybook version earlier than 6.3.6 (I have 6.2.9)
- run ``npx sb@latest upgrade``
- See error

**System**
```
Environment Info:

  System:
    OS: macOS 11.5.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Binaries:
    Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.12 - ~/.nvm/versions/node/v14.16.1/bin/npm
  Browsers:
    Chrome: 92.0.4515.107
    Firefox: 90.0.2
    Safari: 14.1.2
```

**Comment by shilman** [comment]
Do you a have a reproduction repo you can share? If not, can you create one? See [how to create a repro](https://storybook.js.org/docs/react/contribute/how-to-reproduce). We prioritize issues with reproductions over those without. Thank you! 🙏
