### ISSUE TITLE
Use better icon for "Reset Controls" button

### ISSUE THREAD

**Issue by jorisw** [storybookjs/storybook#15734]
**Is your feature request related to a problem? Please describe**

The Reset button in the top right of Controls, looks like a Refresh button. It made me think it would refresh code, or Controls defaults.
![image](https://user-images.githubusercontent.com/30017/127832425-84e81b7c-90dd-4a1f-99bc-e1540e5a77f4.png)

**Describe the solution you'd like**

Better would be to use a 'reset' icon, i.e. something that conveys Undo or Rewind. Example:
![image](https://user-images.githubusercontent.com/30017/127832624-d3f30a0d-b56b-40db-b771-f6b7c176ac74.png)

**Are you able to assist to bring the feature to reality?**

Assuming you are using an icon set font for this, I'm hoping it will be easy for you to change to an icon that resembles the suggested example.

**Comment by shilman** [comment]
@MichaelArestad WDYT?

**Comment by MichaelArestad** [comment]
The closest we have to that is an `undo` icon in the Design System. It would be a slight improvement over the sync icon.

<img width="106" alt="image" src="https://user-images.githubusercontent.com/1123119/127885510-7358c711-60be-425d-a4e3-19ccce95d2cb.png">

**Comment by jorisw** [comment]
Agreed!

**Comment by awesome31** [comment]
Hi! I have not explored the storybook repository and would love to take the first step and take this issue up. Is that okay? :t-rex:

**Comment by shilman** [comment]
That would be great @awesome31--thank you for helping make Storybook better! 🙏  Please check out [how to contribute](https://storybook.js.org/docs/react/contribute/how-to-contribute) in our docs and feel free to ask questions in `#contributing` in [our Discord](https://discord.gg/storybook).

**Comment by awesome31** [comment]
Hi! I did create a PR and tested it as per the contribution guidelines. Do test and let me know! Here is the PR: https://github.com/storybookjs/storybook/pull/15737

Also, I am not sure who I should add as a reviewer?

**Comment by MichaelArestad** [comment]
@awesome31 Thanks! I'm reviewing it now.

**Comment by shilman** [comment]
Ooh-la-la!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-alpha.29 containing PR #15737 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
