### ISSUE TITLE
ModuleNotFoundError with typescript modules

### ISSUE THREAD

**Issue by rmnbod** [storybookjs/storybook#15735]
**Describe the bug**
ModuleNotFoundError: Module not found: Error: Can't resolve  './Button' in '{...}/src/stories', compilation error on React + Typescript project.
 
**System**
System:
    OS: macOS 11.5
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 14.17.0 - /usr/local/bin/node
    npm: 6.14.13 - /usr/local/bin/npm
  Browsers:
    Chrome: 92.0.4515.107
    Safari: 14.1.2
  npmPackages:
    @storybook/addon-actions: ^6.3.6 => 6.3.6 
    @storybook/addon-essentials: ^6.3.6 => 6.3.6 
    @storybook/addon-knobs: ^6.2.9 => 6.3.0 
    @storybook/addon-links: ^6.3.6 => 6.3.6 
    @storybook/builder-webpack5: ^6.3.6 => 6.3.6 
    @storybook/manager-webpack5: ^6.3.6 => 6.3.6 
    @storybook/react: ^6.3.6 => 6.3.6 

**Additional context**
ModuleNotFoundError: Module not found: Error: Can't resolve './Button' in '{...}/src/stories'
at {...}/node_modules/webpack/lib/Compilation.js:1771:28
at {...}/node_modules/webpack/lib/NormalModuleFactory.js:742:13
at eval (eval at create ({...}/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
  at {...}/node_modules/webpack/lib/NormalModuleFactory.js:276:22
  at eval (eval at create ({...}/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at {...}/node_modules/webpack/lib/NormalModuleFactory.js:405:22
    at {...}/node_modules/webpack/lib/NormalModuleFactory.js:119:11
    at {...}/node_modules/webpack/lib/NormalModuleFactory.js:650:24
    at {...}/node_modules/webpack/lib/NormalModuleFactory.js:813:8
    at {...}/node_modules/webpack/lib/NormalModuleFactory.js:933:5
    at {...}/node_modules/neo-async/async.js:6883:13
    at Array.<anonymous> ({...}/node_modules/webpack/lib/NormalModuleFactory.js:908:14)
      at arrayEachFunc ({...}/node_modules/neo-async/async.js:2517:19)
      at Object.parallel ({...}/node_modules/neo-async/async.js:6858:9)
      at NormalModuleFactory._resolveResourceErrorHints ({...}/node_modules/webpack/lib/NormalModuleFactory.js:831:12)
      at {...}/node_modules/webpack/lib/NormalModuleFactory.js:792:18
      resolve './Button' in '{...}/src/stories'
      using description file: {...}/package.json (relative path: ./src/stories)
      Field 'browser' doesn't contain a valid alias configuration
      using description file: {...}/package.json (relative path: ./src/stories/Button)
      no extension
      Field 'browser' doesn't contain a valid alias configuration
      {...}/src/stories/Button doesn't exist
      .js
      Field 'browser' doesn't contain a valid alias configuration
      {...}/src/stories/Button.js doesn't exist
      .json
      Field 'browser' doesn't contain a valid alias configuration
      {...}/src/stories/Button.json doesn't exist
      .wasm
      Field 'browser' doesn't contain a valid alias configuration
      {...}/src/stories/Button.wasm doesn't exist
      as directory
      {...}/src/stories/Button doesn't exist

**Comment by shilman** [comment]
Do you a have a reproduction repo you can share? If not, can you create one? See [how to create a repro](https://storybook.js.org/docs/react/contribute/how-to-reproduce). We prioritize issues with reproductions over those without. Thank you! 🙏

**Comment by akhmadullin** [comment]
@rmnbod, I had the same problem.

Changing of ``'@storybook/addon-knobs/register'`` to ``'@storybook/addon-knobs'`` in ``.storybook/main.js`` fixed this bug:

```js
module.exports = {
    addons: ['@storybook/addon-knobs'],
}
```

**Comment by johan44co** [comment]
On projects using `create-react-app` projects, remove `"@storybook/preset-create-react-app"` from add-ons in `.storybook/main.js`

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
