### ISSUE TITLE
Single story hoisting when only one named export

### ISSUE THREAD

**Issue by devmattrick** [storybookjs/storybook#15736]
**Is your feature request related to a problem? Please describe**
One small thing that bugs me about single story hoisting is that the named export needs to be the same name as the component. Because of this, you can't use the component's name as an import and instead need to alias it. The example in the docs demonstrate this well:

```jsx
import { Button as ButtonComponent } from './Button';

export default {
  title: 'Design System/Atoms/Button',
  component: ButtonComponent,
};

// This is the only named export in the file, and it matches the component name
export const Button = (args) => <ButtonComponent {...args} />;
```

**Describe the solution you'd like**
I think its desirable to hoist single story components, regardless of the name of the export. This would allow for a slight ergonomic improvement, in my opinion. The above example could be rewritten as:

```jsx
import { Button } from './Button';

export default {
  title: 'Design System/Atoms/Button',
  component: Button,
};

// This is the only named export in the file, and it doesn't need to match the component name
export const Single = (args) => <Button {...args} />;
```
I think it's a small improvement over the above, but definitely a nice quality of life feature. I think this may be a breaking change due to how it may change how people expect stories to be laid out but its definitely minor. It could also be made non-breaking through a configuration option.

**Describe alternatives you've considered**

**Are you able to assist to bring the feature to reality?**
I'd love to help 😄 

**Additional context**
N/A

**Comment by shilman** [comment]
https://storybook.js.org/docs/react/writing-stories/naming-components-and-hierarchy#single-story-hoisting
