### ISSUE TITLE
Ability to provide name generators manually

### ISSUE THREAD

**Issue by max-prtsr** [storybookjs/storybook#15741]
**Is your feature request related to a problem? Please describe**
I'm frustrated with named const names generation. 
1. It adds spaces which I don't need since I'm using component names like `export const TextInput = ....` produces `Text Input`
2. I have to write weird hacks like `import { Button as ButtonComponent } from './Button';` to be able to set name clashed with import

**Describe the solution you'd like**
I would like to define name generator in `main.js` like
```js
module.exports = {
  nameGenerator: (name) => {
    return doSomething(name).replace(/Story$/, '')
  }
}
```

**Describe alternatives you've considered**
Haven't find one

**Are you able to assist to bring the feature to reality?**
yes

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if this is still relevant in SB 7.x.
