### ISSUE TITLE
When adding addons array in .storybook/main.ts this error is thrown 

### ISSUE THREAD

**Issue by AbhiPanseriya** [storybookjs/storybook#15752]
I've setup Storybook in my angular project when I tried to run it throws this error
```
Error: Zone.js has detected that ZoneAwarePromise `(window|global).Promise` has been overwritten.
Most likely cause is that a Promise polyfill has been loaded after Zone.js (Polyfilling Promise api is not necessary when zone.js is loaded. If you must load one, do so before loading zone.js.)
    at Function.push../node_modules/zone.js/dist/zone.js.Zone.assertZonePatched (zone.js:58)
    at new NgZone (core.js:39456)
    at getNgZone (core.js:40707)
    at PlatformRef.bootstrapModuleFactory (core.js:40522)
    at core.js:40603
    at es.promise.js:118
``` 
I researched a bit and found out that array of addons in .storybook/main.ts is somehow causing the issue, I tried removing the default addons `@storybook/addon-links`, `@storybook/addon-essentials` and without it worked just fine (it just rendered the component though, without the controls and action tab).

> Can anyone help me solve the error?

I'm working on a commercial project so couldn't share much of the code.
I'm using angular **8.3.23**, node **10.16.3** and storybook **6.3.6**

**To Reproduce**
these are the files I've created to install the storybook
```javascript
// .storybook/main.js
module.exports = {
  "stories": [
    "../src/**/*.stories.mdx",
    "../src/**/*.stories.@(js|jsx|ts|tsx)"
  ],
  "addons": [
    "@storybook/addon-actions",
    "@storybook/addon-links",
    "@storybook/addon-essentials"
   ]
}
```
```javascript
//.storybook/preview.js
export const parameters = {
  actions: { argTypesRegex: "^on[A-Z].*" },
  controls: {
    matchers: {
      color: /(background|color)$/i,
      date: /Date$/,
    },
  },
  docs: { inlineStories: true },
```
```json
//.storybook/tsconfig.json
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "types": [
      "node"
    ]
  },
  "exclude": [
    "../src/test.ts",
    "../src/**/*.spec.ts"
  ],
  "include": [
    "../src/**/*"
  ],
  "files": [
    "./typings.d.ts"
  ]
}
```
```typescript
//.storybook/typing.d.ts
declare module '*.md' {
  const content: string;
  export default content;
}
declare module '@storybook/angular/types-6-0';
declare module '@storybook/angular';
```
I've added these packages to my package.json
```
"@storybook/addon-actions": "^6.3.6",
"@storybook/addon-essentials": "^6.3.6",
"@storybook/addon-links": "^6.3.6",
"@storybook/angular": "^6.3.6",
```
I've modified the `tsconfig.app.json` -> `exclude` array to this: 
```
"exclude": [
    "src/**/*.spec.ts",
    "e2e/**/*.ts",
    "**/*.stories.*"
  ]
```

**Comment by shilman** [comment]
looks like there's a workaround here. closing as duplicate https://github.com/storybookjs/storybook/issues/7318#issuecomment-889707645

**Comment by AbhiPanseriya** [comment]
> looks like there's a workaround here. closing as duplicate [#7318 (comment)](https://github.com/storybookjs/storybook/issues/7318#issuecomment-889707645)

Hey, @shilman I've tried all the steps suggested in the thread [#7318](https://github.com/storybookjs/storybook/issues/7318#issuecomment-889707645) but couldn't able to resolve the issue.

**Comment by AbhiPanseriya** [comment]
Hey @shilman, I tried creating a new angular app with angular/cli v8.3.23 with node v10.16.3 and set up the storybook v6.3.6 and got the same error when running the storybook.
![image](https://user-images.githubusercontent.com/42121122/128313567-8d989f61-c08f-415a-b25b-1b2a8a14d6cf.png)
you can view the code at this [github link](https://github.com/AbhiPanseriya/test-storybook).

**Comment by AbhiPanseriya** [comment]
Resolved it by upgrading the zone.js to the latest stable version.
