### ISSUE TITLE
Decorators execution order is not respected

### ISSUE THREAD

**Issue by FezVrasta** [storybookjs/storybook#15767]
**Describe the bug**
I have two decorators, one depends on the other, I define them in a specific order so that the dependency is satisfied but the result is not as expected, the decorators are applied in seemingly random order.

**To Reproduce**
Add a few decorators to your `preview.js` export and notice they don't run in the order defined in the decorators array.

**System**
Environment Info:

  System:
    OS: macOS 11.4
    CPU: (4) x64 Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz
  Binaries:
    Node: 14.17.4 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.14 - /usr/local/bin/npm
  Browsers:
    Chrome: 91.0.4472.101
    Edge: 87.0.664.47
    Firefox: 90.0.2

**Comment by FezVrasta** [comment]
Oh, I realized you must provide the decorators in inverse order, because the one on the bottom will wrap the one above.

**Comment by pkyeck** [comment]
🤯 who came up with this!?

and is this documented somewhere? ... ok, I just re-read the decorators page and it says the opposite (which would kind of make sense) ... https://storybook.js.org/docs/writing-stories/decorators#decorator-inheritance

but I could also only get my decorators to work in the reverse order.

what is correct? and if reverse order is correct, please update the docs and add a big red exclamation mark ‼️
