### ISSUE TITLE
npx sb init broken with cra typescript projects

### ISSUE THREAD

**Issue by Roger-Heathcote** [storybookjs/storybook#15761]
**Describe the bug**

Create-react-app app dies with complaint about babel-loader after installing storybook with `npx sb init`.

**To Reproduce**

yarn create react-app wevs --template typescript (same result with npm create-react-app, with or without @latest)
cd wevs
yarn start (works fine)
npm sb init (displays a couple of dozen warnings about unmet peer dependencies but completes)
yarn storybook (starts just fine but now...)
yarn start (fails with the following message...)

```
There might be a problem with the project dependency tree.
It is likely not a bug in Create React App, but something you need to fix locally.

The react-scripts package provided by Create React App requires a dependency:

  "babel-loader": "8.1.0"

Don't try to install it manually: your package manager does it automatically.
However, a different version of babel-loader was detected higher up in the tree:

  /home/user/code/foo/node_modules/babel-loader (version: 8.2.2) 

Manually installing incompatible versions is known to cause hard-to-debug issues.

If you would prefer to ignore this check, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
That will permanently disable this message but you might encounter other issues.

```

Reproduction here: https://github.com/Roger-Heathcote/storybook_cra_problem

**System**
  System:
    OS: Linux 5.8 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-3820QM CPU @ 2.70GHz
  Binaries:
    Node: 14.17.1 - ~/.nvm/versions/node/v14.17.1/bin/node
    Yarn: 3.0.0 - /usr/bin/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.1/bin/npm
  Browsers:
    Firefox: 90.0.2
  npmPackages:
    @storybook/addon-actions: ^6.4.0-alpha.24 => 6.4.0-alpha.24 
    @storybook/addon-docs: ^6.4.0-alpha.24 => 6.4.0-alpha.24 
    @storybook/addon-essentials: ^6.4.0-alpha.24 => 6.4.0-alpha.24 
    @storybook/addon-links: ^6.4.0-alpha.24 => 6.4.0-alpha.24 
    @storybook/node-logger: ^6.4.0-alpha.24 => 6.4.0-alpha.24 
    @storybook/preset-create-react-app: ^3.2.0 => 3.2.0 
    @storybook/react: ^6.4.0-alpha.24 => 6.4.0-alpha.24

**Comment by hoicking** [comment]
same

**Comment by timmydoza** [comment]
I'm also seeing this. Any updates?

I'm finding that adding this to my package.json file serves as a temporary workaround:
```
  "resolutions": {
    "babel-loader": "8.1.0"
  }
```
This does result in the following warning being emitted, but `npm start` and `npm run build` to seem to function correctly in CRA: 
```
warning Resolution field "babel-loader@8.1.0" is incompatible with requested version "babel-loader@^8.2.2"
```

This only works with yarn, but it may be possible to get this to work with npm with the [npm-force-resolutions](https://github.com/rogeriochaves/npm-force-resolutions) package.

**Comment by shilman** [comment]
closing as dupe to #5183
