### ISSUE TITLE
Add PNPM Workspace Support

### ISSUE THREAD

**Issue by fdc-viktor-luft** [storybookjs/storybook#15764]
**Is your feature request related to a problem? Please describe**
I'm working with a `pnpm` workspace. When using the `@storybook/cli` the dependencies of my workspace root were ignored and even the package manager was not correctly detected. Added workspace modules in the `package.json` were even causing the the `sb init` to crash with `Unsupported URL Type "workspace:": workspace:*`.

**Describe the solution you'd like**
Please add a workspace awareness by looking up the file system tree for workspace configurations of different package managers. Detect the package managers correctly instead of falling back too quickly on `npm`. Read e.g. from the workspace packages if `typescript` is available.

**Describe alternatives you've considered**
To work-around the problem I had to manually pull in all required workspace dependencies into the `package.json`. Remove temporarily the installed workspace packages. And after executing `sb init` clear my `node_modules`. Revert all `package.json` work-around changes, and finally run `pnpm i` again to re-install all packages correctly.

UPDATE: I couldn't get it to work so far since I'm using a custom configuration on top of CRA that allows me transpile code of workspace packages on build. Maybe it would've worked solely with CRA and without any further adjustments to it. Will try to investigate for some time.

UPDATE 2: I finally got everything to work but encountered several other issues since I needed the storybook to be also hosted on a subpath. I had to remove the injected `@storybook/preset-create-react-app` since this didn't work at all with `react-scripts`. Then things got a little easier and more reliable. And I had to add `--no-manager-cache` for starting the storybook locally since the manager cache was very often wrong configured when using custom overrides on subsequent restarts.

**Are you able to assist to bring the feature to reality?**
I'll answer questions and discuss upon solutions, but don't have the capacity to do it myself.

**Comment by shikelong** [comment]
same issue.

**Comment by wwglala** [comment]
+1

**Comment by moglerdev** [comment]
+1

**Comment by IanVS** [comment]
This has been fixed in the latest storybook 7.0 beta versions. As long as you have a pnpm-lock.yml file, we will detect that you are using pnpm, and use that to install / upgrade Storybook. Or, you can force pnpm to be used with a --package-manager=pnpm flag.

Please let us know if you still have any issues installing storybook 7.0 using pnpm.  You can use `pnpx sb@next init` to add Storybook, or `pnpx sb@next upgrade --prerelease` to upgrade an existing installation.
