### ISSUE TITLE
Improve Args API for non-optional fields for TypeScript users

### ISSUE THREAD

**Issue by donaldpipowitch** [storybookjs/storybook#15763]
**Is your feature request related to a problem? Please describe**
I recently used the Args API with non-optional fields and this led to some problems. I'm also not sure if this pattern is supported or not. The full background with code examples can be found [here](https://twitter.com/PipoPeperoni/status/1422449385376526348).

![image](https://user-images.githubusercontent.com/1152805/128288523-291138ac-6455-4186-9f6c-0c693a123306.png)

**Describe the solution you'd like**
1. Clarify if non-optional fields in the Args API are allowed or not.
2. If non-optional fields **are allowed** the `Partial<>` on `args` should IMHO be removed.
3. If non-optional fields **are not allowed** such a usage should be _forbidden_ or raise warnings. (Maybe this can be raised on the type level already - basically disallowing fields which don't allow `undefined` - or one could start creating officially baked Storybook ESLint rules - I don't think they already exist or?)

**Describe alternatives you've considered**
The solution contains alternatives.

**Are you able to assist to bring the feature to reality?**
Yes.

**Additional context**
-

**Comment by shilman** [comment]
closing as duplicate to #13747
