### ISSUE TITLE
Addon-controls: `esm is not defined` error

### ISSUE THREAD

**Issue by dexster** [storybookjs/storybook#15773]
**Describe the bug**
Site breaks when navigating to https://next--storybookjs.netlify.app/angular-cli/?path=/story/addons-controls--basic

Check the Console
vendors~main.329f7787c62cee5c3a74.manager.bundle.js:2 ReferenceError: esm is not defined

**Comment by khylerlin** [comment]
We are facing the same issue from some of our stories.

**Comment by shilman** [comment]
@khylerlin which version are you using, and do you happen to know which version the issue started to appear in?

**Comment by khylerlin** [comment]
@shilman We are now using 6.4.0-alpha.20, and not sure what version started to appear this issue. I encountered this issue almost the issue has been created on Aug 6.

**Comment by w-p** [comment]
```
node: 14.17
npm: 7.17
angular: 12.1
storybook: 6.4.0-alpha.28
```
This issue occurs on a variety of alpha builds. Moreover, it works fine when running Storybook locally via `start-storybook`. When performing a build via `build-storybook` the build completes successfully but, when viewed in a browser, produces the below output on all but the most simplistic components.

![image](https://user-images.githubusercontent.com/8106907/128778575-47a62ce0-fd1d-448e-82c1-5967ec3368fd.png)

**Comment by w-p** [comment]
Update. After refreshing the page on a component that causes the issue about, the below additional errors are logged.

![image](https://user-images.githubusercontent.com/8106907/128862019-834670af-4231-41a1-95e7-540b339b304b.png)

**Comment by w-p** [comment]
Additionally, #15710 is correct. Load the page, navigate to a component that works, click the actions tab, navigate to a component that previously failed and the component is rendered. However, some additional deprecation warnings are emitted.

Interestingly, the components which appear to cause the failure also have Angular `@Output` event emitters.

![image](https://user-images.githubusercontent.com/8106907/128864715-0956711b-638f-4980-aab3-22bdce610c26.png)

**Comment by gaetanmaisse** [comment]
I found the guilty commits, investigation in progress in https://github.com/storybookjs/storybook/pull/15812.

**Comment by ld210** [comment]
Same here, we're facing the same issue (except on local server).
```json
storybook: 6.3.6
storybook/builder-webpack5: 6.4.0-alpha.1
angular: 12.1.0

node: 14.17.4
npm: 6.14.14
```

**Comment by navin-moorthy** [comment]
Works for me till v6.4.0-alpha.16

```
"@storybook/addon-a11y": "6.4.0-alpha.16",
"@storybook/addon-actions": "6.4.0-alpha.16",
"@storybook/addon-essentials": "6.4.0-alpha.16",
"@storybook/addon-postcss": "^2.0.0",
"@storybook/react": "6.4.0-alpha.16",
```

**Comment by shilman** [comment]
Egads!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-alpha.30 containing PR #15812 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by maikenmadsen92** [comment]
I'm having the same issue and using 6.4.0-alpha.29. I don't know how to reopen the issue

**Comment by brizer** [comment]
> npx sb upgrade --prerelease

It is not work. This bug is still exists.
