### ISSUE TITLE
ERESOLVE unable to resolve dependency tree Could not resolve dependency: npm ERR! peer react@"17.0.2" from react-dom@17.0.2

### ISSUE THREAD

**Issue by DeveloperAspire** [storybookjs/storybook#15785]
**Describe the bug**
Whenever I try to create a new react app using `npx create-react-app` or try `npm install` I get the error below

`npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: custom-hooks@0.1.0
npm ERR! Found: react@undefined
npm ERR! node_modules/react
npm ERR!   react@"*" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"17.0.2" from react-dom@17.0.2
npm ERR! node_modules/react-dom
npm ERR!   react-dom@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/franklin/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/franklin/.npm/_logs/2021-08-07T14_32_31_177Z-debug.log

Aborting installation.
  npm install --save --save-exact --loglevel error react react-dom react-scripts cra-template has failed.
`

**Comment by DeveloperAspire** [comment]
I really need help on this

**Comment by shilman** [comment]
closing as dupe to #15776
