### ISSUE TITLE
Error on starting storybook with 6.3.6 and 6.4.0-alpha.24

### ISSUE THREAD

**Issue by challengy1** [storybookjs/storybook#15783]
**Describe the bug**
Following the instruction, I tried to update the Webpack from 4 to 5. After yarning add as follows, and attempted to start storybook, I witnessed error message and couldn't be started.

yarn add @storybook/builder-webpack5 @storybook/manager-webpack5 webpack --dev

**To Reproduce**
Please refer the GitHub repository as follows:

https://github.com/challengy1/sbrepro.git

**System**
{
  name: 'cra_typescript',
  version: 'latest',
  appName: 'sbrepro',
  creationPath: '/Users/koichi/JS',
  cwd: '/Users/koichi/JS/sbrepro',
  e2e: false,
  pnp: false,
  framework: 'react',
  generator: 'npx create-react-app@{{version}} {{appName}} --template typescript --use-npm'
}

🏗 Bootstrapping cra_typescript project (this might take a few minutes)
npx create-react-app@latest sbrepro --template typescript --use-npm

🧶 Installing Yarn 2
yarn set version berry && yarn config set enableGlobalCache true && yarn config set nodeLinker node-modules

rm: no such file or directory: /Users/koichi/JS/sbrepro/yarn.lock
🌍 Adding needed deps & installing all deps
yarn install

🎨 Initializing Storybook with @storybook/cli
node /Users/koichi/.npm/_npx/eebb2d3a7d26a7f1/node_modules/@storybook/cli/dist/esm/generate init --yes  --linkable

git init
echo "node_modules" >> .gitignore
git add --all
git commit -am "added storybook"
git tag repro-base

**Additional context**
Nothing more.

hope the issue is resolved.

**Comment by challengy1** [comment]
System Information is as follows:

>>> npx sb@next info 

Environment Info:

  System:
    OS: macOS 11.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 14.15.3 - ~/.nodenv/versions/14.15.3/bin/node
    Yarn: 3.0.0 - ~/.nodenv/versions/14.15.3/bin/yarn
    npm: 7.20.3 - ~/.nodenv/versions/14.15.3/bin/npm
  Browsers:
    Chrome: 92.0.4515.131
    Safari: 14.1.2
  npmPackages:
    @storybook/addon-actions: ^6.4.0-alpha.24 => 6.4.0-alpha.24 
    @storybook/addon-docs: ^6.4.0-alpha.24 => 6.4.0-alpha.24 
    @storybook/addon-essentials: ^6.4.0-alpha.24 => 6.4.0-alpha.24 
    @storybook/addon-links: ^6.4.0-alpha.24 => 6.4.0-alpha.24 
    @storybook/builder-webpack5: ^6.3.6 => 6.3.6 
    @storybook/manager-webpack5: ^6.3.6 => 6.3.6 
    @storybook/node-logger: ^6.4.0-alpha.24 => 6.4.0-alpha.24 
    @storybook/preset-create-react-app: ^3.2.0 => 3.2.0 
    @storybook/react: ^6.4.0-alpha.24 => 6.4.0-alpha.24 

--

**Comment by shilman** [comment]
CRA doesn't work with webpack5 (yet) and storybook uses CRA's webpack config, therefore Storybook does not with webpack5 when the app is CRA. Closing this for now!
