### ISSUE TITLE
@storybook/html stories written solely in MDX

### ISSUE THREAD

**Issue by thomasdahlberg** [storybookjs/storybook#15801]
**Is your feature request related to a problem? Please describe**
I work with a repo that uses @storybook/html to construct/share components built purely with HTML elements (not Angular or React) and styles them with css. I want a method to write stories solely in MDX (rather than in CSF format), but it seems as though I can only write stories in CSF and add docs to them via an accompanying MDX docs file.

**Describe the solution you'd like**
I would like to be able to write a ****.stories.mdx file like so:

```
import { Meta, Story } from '@storybook/addon-docs/'
import exampleHTML from ./example.html;

<Meta title="Example HTML Component" />

# This is an example HTML Component

<Story title="Basic Example HTML">{ exampleHTML }</Story>

...
```

Is that a possibility?

**Comment by CodeByAlex** [comment]
@shilman Any thoughts here? Has the HTML project been built out to support MDX intuitively like the other frameworks?

**Comment by thomasdahlberg** [comment]
Found the syntax to make this possible, closing this issue:

```
import { Meta, Story } from '@storybook/addon-docs/'
import exampleHTML from ./example.html;

<Meta title="Example HTML Component" />

# This is an example HTML Component

<Story name="Basic Example HTML">{() => {
    return `${exampleHTML}` 
}}</Story>

```
