### ISSUE TITLE
sb init on lerna root can't load stories written in tsx or jsx

### ISSUE THREAD

**Issue by Psidium** [storybookjs/storybook#15803]
First and foremost, thanks for such an awesome project. Also thanks for being so approachable, I wasn't going to raise any issues, but the maintainers seem really understanding and that helps, so here I am.

**Describe the bug**

The example stories for `Page`, `Button` and `Header` are not loaded when creating a new storybook with `npx sb init` inside a `lerna` monrepo with a typescirpt Create React App in the packages. The browser's  console shows it is trying to load the typescript files themselves, causing parsing errors. I tried a lot of things but to no avail, even `.jsx` stories are broken.

I expected to see the image shown on https://storybook.js.org/docs/react/get-started/install (with `Introduction`, `Page`, `Button`, and `Header`), but instead I only have the `Introduction` (in `mdx`):
<img width="1596" alt="Screen Shot 2021-08-09 at 21 54 28" src="https://user-images.githubusercontent.com/2848323/128796066-cbda4667-d263-4b9d-a7b3-e6f53a28cb34.png">

<details>
<summary>click to see the chromium logs trying to load the `tsx` files</summary>

```
index.js:49 Unexpected error while loading ./Button.stories.tsx: Error: Module parse failed: Unexpected token (23:2)
File was processed with these loaders:
 * ./node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js
 * ./node_modules/@storybook/source-loader/dist/cjs/index.js
You may need an additional loader to handle the result of these loaders.
|     backgroundColor: { control: 'color' },
|   },
> } as ComponentMeta<typeof Button>;
| 
| const Template: ComponentStory<typeof Button> = (args) => <Button {...args} />;
warn @ index.js:49
(anonymous) @ loadCsf.js:63
(anonymous) @ loadCsf.js:56
(anonymous) @ loadCsf.js:55
ConfigApi.configure @ config_api.js:19
(anonymous) @ loadCsf.js:223
configure @ index.js:28
(anonymous) @ generated-stories-entry.js:6
./.storybook/generated-stories-entry.js @ generated-stories-entry.js:7
__webpack_require__ @ bootstrap:856
fn @ bootstrap:150
0 @ stackalt.svg:1
__webpack_require__ @ bootstrap:856
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.iframe.bundle.js:1
index.js:49 Unexpected error while loading ./Header.stories.tsx: Error: Module parse failed: Unexpected token (20:2)
File was processed with these loaders:
 * ./node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js
 * ./node_modules/@storybook/source-loader/dist/cjs/index.js
You may need an additional loader to handle the result of these loaders.
|   title: 'Example/Header',
|   component: Header,
> } as ComponentMeta<typeof Header>;
| 
| const Template: ComponentStory<typeof Header> = (args) => <Header {...args} />;
warn @ index.js:49
(anonymous) @ loadCsf.js:63
(anonymous) @ loadCsf.js:56
(anonymous) @ loadCsf.js:55
ConfigApi.configure @ config_api.js:19
(anonymous) @ loadCsf.js:223
configure @ index.js:28
(anonymous) @ generated-stories-entry.js:6
./.storybook/generated-stories-entry.js @ generated-stories-entry.js:7
__webpack_require__ @ bootstrap:856
fn @ bootstrap:150
0 @ stackalt.svg:1
__webpack_require__ @ bootstrap:856
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.iframe.bundle.js:1
index.js:49 Unexpected error while loading ./Page.stories.tsx: Error: Module parse failed: Unexpected token (21:2)
File was processed with these loaders:
 * ./node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js
 * ./node_modules/@storybook/source-loader/dist/cjs/index.js
You may need an additional loader to handle the result of these loaders.
|   title: 'Example/Page',
|   component: Page,
> } as ComponentMeta<typeof Page>;
| 
| const Template: ComponentStory<typeof Page> = (args) => <Page {...args} />;
```

</details>

**To Reproduce**

I was not able to reproduce the issue with `npx sb@next repro`, maybe because this issue has to do with lerna/monorepo and it creates a vanilla CRA app.

Nevertheless, you can find a repository with the resulting storybook at https://github.com/Psidium/storybook-init-script-typescript--bug, just clone and `yarn install`.

I generated the repository with the following commands:

```bash
# this is an excerpt of my `history -1 -30`
mkdir repro-storybook-bug
cd repro-storybook-bug
lerna init
cd packages
npx create-react-app new-app --template typescript
cd new-app/
yarn install
yarn start # useless
cd ..
npx sb init
yarn add -W -D typescript
npx sb init # useless, having issue with detection
npx sb init --type typescript # useless...
npx sb init --type react_scripts 
yarn storybook # did not work ctrl-c
yarn install
yarn add react
yarn install
yarn storybook # ctrl-c did not work
yarn add react-dom
yarn storybook # ctrl-c did not work
yarn add -D react-scripts
yarn storybook # done, but cant find typescript pages
git init
gi node > .gitignore
git add .
git status
git commit -m "initial commit"
```

<details>
<summary>
click here to see my <b>System</b>
</summary>

```
Environment Info:

  System:
    OS: macOS 11.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 16.6.1 - ~/.nvm/versions/node/v16.6.1/bin/node  (also tested on 14.16.0)
    Yarn: 1.22.11 - ~/.nvm/versions/node/v16.6.1/bin/yarn 
    npm: 7.20.3 - ~/.nvm/versions/node/v16.6.1/bin/npm (also tested on 6.14.11)
  Browsers:
    Firefox: 90.0.2
    Safari: 14.1.2
 Chromium: 92.0.4515.107 (Official Build, ungoogled-chromium) (x86_64) -- (script did not find this, i have it from brew install eloston-chromium)
  npmPackages:
    @storybook/addon-actions: ^6.3.7 => 6.3.7
    @storybook/addon-essentials: ^6.3.7 => 6.3.7
    @storybook/addon-links: ^6.3.7 => 6.3.7
    @storybook/node-logger: ^6.3.7 => 6.3.7
    @storybook/preset-create-react-app: ^3.2.0 => 3.2.0
    @storybook/react: ^6.3.7 => 6.3.7
```
</details>

**Additional context**

Initially I believed this issue was due to my actual repo, but as you can see I can reproduce it from scratch without any issues.

I really tried to find a duplicate issue here, but I guess I'm missing a keyword if this was already raised here, as I couldn't find it.

**Comment by shilman** [comment]
Hi @Psidium - thanks for the report! I don't think this is actually a bug, but maybe you can correct me if I got it wrong. 

Storybook is not meant to stand alone, i.e. if you go to an empty project and run `sb init`, we don't expect it to work. Instead, it's meant to be used **ON TOP** of existing apps or component libraries. So if you're in a CRA project and run `sb init`, we expect it to install itself alongside your app.

I believe when you're installing at the root of a lerna monorepo, there's no real app/library for Storybook to install itself on. If you installed it INSIDE the CRA sub-directory in the monorepo, I would expect it to work as advertised.

WDYT?

**Comment by Khushi1706** [comment]
Hi @shilman , I am facing the exact same issue. I am using storybook alongside react boilerplate. This is my folder structure. I have these under frontend folder.  I
![image](https://user-images.githubusercontent.com/27494347/133217063-411766da-bd47-434a-8092-ebc0b6b6ed72.png)
 On my local everything works perfectly, but when i serve this using npx http-server ./path. I get only introduction page and same errors as mentioned above get displayed in console. Please help!

**Comment by Khushi1706** [comment]
Can i please get an update on this

**Comment by clothoo** [comment]
> First and foremost, thanks for such an awesome project. Also thanks for being so approachable, I wasn't going to raise any issues, but the maintainers seem really understanding and that helps, so here I am.
> 
> **Describe the bug**
> 
> The example stories for `Page`, `Button` and `Header` are not loaded when creating a new storybook with `npx sb init` inside a `lerna` monrepo with a typescirpt Create React App in the packages. The browser's console shows it is trying to load the typescript files themselves, causing parsing errors. I tried a lot of things but to no avail, even `.jsx` stories are broken.
> 
> I expected to see the image shown on https://storybook.js.org/docs/react/get-started/install (with `Introduction`, `Page`, `Button`, and `Header`), but instead I only have the `Introduction` (in `mdx`):
> <img alt="Screen Shot 2021-08-09 at 21 54 28" width="1596" src="https://user-images.githubusercontent.com/2848323/128796066-cbda4667-d263-4b9d-a7b3-e6f53a28cb34.png">
> click to see the chromium logs trying to load the `tsx` files
> 
> **To Reproduce**
> 
> I was not able to reproduce the issue with `npx sb@next repro`, maybe because this issue has to do with lerna/monorepo and it creates a vanilla CRA app.
> 
> Nevertheless, you can find a repository with the resulting storybook at https://github.com/Psidium/storybook-init-script-typescript--bug, just clone and `yarn install`.
> 
> I generated the repository with the following commands:
> 
> ```shell
> # this is an excerpt of my `history -1 -30`
> mkdir repro-storybook-bug
> cd repro-storybook-bug
> lerna init
> cd packages
> npx create-react-app new-app --template typescript
> cd new-app/
> yarn install
> yarn start # useless
> cd ..
> npx sb init
> yarn add -W -D typescript
> npx sb init # useless, having issue with detection
> npx sb init --type typescript # useless...
> npx sb init --type react_scripts 
> yarn storybook # did not work ctrl-c
> yarn install
> yarn add react
> yarn install
> yarn storybook # ctrl-c did not work
> yarn add react-dom
> yarn storybook # ctrl-c did not work
> yarn add -D react-scripts
> yarn storybook # done, but cant find typescript pages
> git init
> gi node > .gitignore
> git add .
> git status
> git commit -m "initial commit"
> ```
> 
> click here to see my System
> 
> **Additional context**
> 
> Initially I believed this issue was due to my actual repo, but as you can see I can reproduce it from scratch without any issues.
> 
> I really tried to find a duplicate issue here, but I guess I'm missing a keyword if this was already raised here, as I couldn't find it.

I'm facing the same problem. I have the exact same setup. Did you find a solution for this?
