### ISSUE TITLE
Classnames are gone from MDX elements after upgrading from 6.2 beta to 6.3.0

### ISSUE THREAD

**Issue by christopher-francisco** [storybookjs/storybook#15800]
**Describe the bug**
The docs don't have styles anymore. It is the exact same issue as #14315, except what I did before to fix does not apply.

## Expected
<img width="815" alt="Screenshot 2021-08-09 at 18 33 02" src="https://user-images.githubusercontent.com/22173137/128748790-469579ed-92ee-45a5-8839-a28cc4b4ba37.png">

## Actual

<img width="553" alt="Screenshot 2021-08-09 at 18 32 46" src="https://user-images.githubusercontent.com/22173137/128748765-877851f1-a32c-441c-8b99-b074d8444482.png">

**System**

```
Environment Info:

  System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
  Binaries:
    Node: 14.17.1 - ~/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.13 - ~/bin/npm
  Browsers:
    Chrome: 92.0.4515.131
    Safari: 14.1.2
  npmPackages:
    @storybook/addon-actions: ^6.3.0 => 6.3.6
    @storybook/addon-contexts: 5.3.21 => 5.3.21
    @storybook/addon-docs: ^6.3.0 => 6.3.6
    @storybook/addon-essentials: ^6.3.0 => 6.3.6
    @storybook/addon-knobs: ^6.3.0 => 6.3.0
    @storybook/addon-links: ^6.3.0 => 6.3.6
    @storybook/addon-options: 5.3.21 => 5.3.21
    @storybook/addon-storyshots: ^6.3.0 => 6.3.6
    @storybook/addons: ^6.3.0 => 6.3.6
    @storybook/core: ^6.3.0 => 6.3.6
    @storybook/react: ^6.3.0 => 6.3.6
```

**Additional context**
It's a `pnpm` monorepo with a  bunch of storybook instances. The problem is most likely that my Storybook is loading a package from one of the many others, instead of loading from my directory.

I am more than happy to try fixing it myself as this have been a problem for me for over a year now, but I need directions as I'm not familiar with how storybook does loading. Any guidance?

Also, the problem will most likely be fixed if I update all storybooks in my monorepo, but that's not a feasible solution.

**Comment by shilman** [comment]
I would def recommend getting rid of old addons, specifically `addon-contexts` and `addoon-options` that are still on 5.3.  Combining packages across major versions is a recipe for disaster. It might not fix this issue, but it's good hygiene.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
