### ISSUE TITLE
Global parameter to disable controls creates Hooks error (Vue3)

### ISSUE THREAD

**Issue by fosterdouglas** [storybookjs/storybook#15802]
Using a global parameter to disable controls in the Addons panel causes a 

_"Warning: React has detected a change in the order of Hooks called by null."_

in **preview.js**:
```
export const parameters = {
   //
  controls: {
    disable: true,
  },
  //
}
```
Using Vue3, and .mdx for my story files. Minimal other package dependencies, just bootstrap, eslint, fontawesome.

**Removing the parameter solves the error for me**.  The error itself was not breaking Storybook in any noticeable way, although I'm obviously not sure of that, since my project is relatively simple.

Repro:
Would love to provide this but, when using the sb command to generate a repro, I got this error:
```
Bootstrapping vue3 project (this might take a few minutes)
echo '{"useTaobaoRegistry": false}' > ~/.vuerc && npx -p @vue/cli@^4 vue create repro' --preset=__default_vue_3__ --packageManager=npm --no-git --force
An error occurred while executing: `echo '{"useTaobaoRegistry": false}' > ~/.vuerc && npx -p @vue/cli@^4 vue create repro' --preset=__default_vue_3__ --packageManager=npm --no-git --force`
🚨 Bootstrapping vue3 failed
🚨 Failed to create repro
```
(note: I haven't used this repro function before, could possibly be my system or setup that's preventing this working properly)

```
  System:
    OS: macOS 11.5
    CPU: (8) x64 Apple M1
  Binaries:
    Node: 14.17.3 - /usr/local/bin/node
    npm: 6.14.13 - /usr/local/bin/npm
  Browsers:
    Chrome: 92.0.4515.131
    Safari: 14.1.2
  npmPackages:
    @storybook/addon-a11y: ^6.3.6 => 6.3.6 
    @storybook/addon-actions: ^6.3.6 => 6.3.6 
    @storybook/addon-docs: ^6.3.6 => 6.3.6 
    @storybook/addon-essentials: ^6.3.6 => 6.3.6 
    @storybook/addon-links: ^6.3.6 => 6.3.6 
    @storybook/addon-measure: ^2.0.0 => 2.0.0 
    @storybook/addon-postcss: ^2.0.0 => 2.0.0 
    @storybook/addon-storysource: ^6.3.6 => 6.3.6 
    @storybook/client-logger: ^6.3.6 => 6.3.6 
    @storybook/node-logger: ^6.3.6 => 6.3.6 
    @storybook/preset-scss: ^1.0.3 => 1.0.3 
    @storybook/theming: ^6.3.6 => 6.3.6 
    @storybook/vue3: ^6.3.6 => 6.3.6 
```

Hopefully this is helpful to somebody! I spent too many hours of time trying to diagnose this, I'd hate for somebody else to have to do that.

The console error also includes this detail:
`Previous render: useContext, Next render: useState`

**Comment by shilman** [comment]
What happens if you uninstall the controls addon? Or disable controls from addon-essentials like this in `.storybook/main.js`:

```js
module.exports = {
  addons: [{
    name: '@storybook/addon-essentials',
    options: {
      controls: false,
    }
  }]
};
```

**Comment by fosterdouglas** [comment]
Disabling from main.js works swimmingly @shilman, thank you! 

It wasn't clear which UI elements are to be disabled from main.js on the addon and which are from preview.js in the parameters. I think I was finding instances of both in the documentation or in others' examples.

Maybe the error was thrown because of using both of these at the same time? As in, "controls" was being disabled in preview.js, while "measure" was being disabled in main.js? But maybe most likely due to me being a newer Storybook user :)

Thank you!
