### ISSUE TITLE
Missing Docs panel on SB 6.3.7 with React + TypeScript + Webpack

### ISSUE THREAD

**Issue by alexandreabeh** [storybookjs/storybook#15814]
**Describe the bug**
The Docs panel is not showing next to the Canvas panel. I'm unsure if this is a configuration error or bug, but I've been able to create a repro repo (see steps below). I am not trying or wanting to override the default docs behavior.

<img width="550" alt="Screen Shot 2021-08-10 at 1 54 10 PM" src="https://user-images.githubusercontent.com/8680662/128939381-13c9ade6-6f36-4b20-a40b-123b8d215eb5.png">

**To Reproduce**
- clone this repro repo: https://github.com/alexandreabeh/missing_docs
- run `yarn storybook`

**System**

  System:
    OS: macOS 11.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 16.2.0 - /usr/local/bin/node
    Yarn: 3.0.0 - /usr/local/bin/yarn
    npm: 7.13.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 92.0.4515.131
    Safari: 14.1.1
  npmPackages:
    @storybook/addon-essentials: 6.3.7 => 6.3.7
    @storybook/addon-links: 6.3.7 => 6.3.7
    @storybook/addons: 6.3.7 => 6.3.7
    @storybook/react: 6.3.7 => 6.3.7

**Comment by shilman** [comment]
You had a typo in your `.storybook/main.js` config: `addOns` => `addons`
