### ISSUE TITLE
Bug with `addon-docs` and `<code>` HTML element

### ISSUE THREAD

**Issue by dbendaou** [storybookjs/storybook#15810]
**Describe the bug**
Seems that, when using `<code>foo</code>` in a `.mdx` file, addon-docs is unable to compile/parse it 

**To Reproduce**

- Create a `.mdx` file 
- Import it in your story like so 
```
import page from './Security.mdx';

export default {
  title: 'Components/Popup/Security',

  parameters: {
    docs: {
      page,
    },
  },
};
```

**System**
```
Environment Info:

  System:
    OS: macOS 11.2.2
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 14.17.0 - /opt/homebrew/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 6.14.13 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 92.0.4515.131
    Firefox: 86.0
    Safari: 14.0.3
  npmPackages:
    @storybook/addon-a11y: 6.3.7 => 6.3.7
    @storybook/addon-actions: 6.3.7 => 6.3.7
    @storybook/addon-centered: 5.3.21 => 5.3.21
    @storybook/addon-docs: 6.3.7 => 6.3.7
    @storybook/addon-knobs: 6.2.9 => 6.2.9
    @storybook/addon-links: 6.3.7 => 6.3.7
    @storybook/addon-notes: 5.3.21 => 5.3.21
    @storybook/addon-storysource: 6.3.7 => 6.3.7
    @storybook/addons: 6.3.7 => 6.3.7
    @storybook/ember: 6.3.7 => 6.3.7
    @storybook/ember-cli-storybook: 0.4.0 => 0.4.0
```

**Additional context**
<img width="843" alt="Screenshot 2021-08-10 at 16 39 00" src="https://user-images.githubusercontent.com/15218861/128889373-1de04d91-685f-4ab1-80ab-0b7af83b842e.png">

**Comment by dbendaou** [comment]
Will try to add a repro repo later

**Comment by lxtlxy** [comment]
I met the same question as your's
using ``` also has the bug

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
