### ISSUE TITLE
Error: Cannot find module react/package.json

### ISSUE THREAD

**Issue by aaronbalthaser** [storybookjs/storybook#15821]
Hello, I am getting this Error: Cannot find module 'react/package.json' when trying to run storybook. I am not using create-react-app and it seems like your docs assume that is what everyone uses. I am using react but I have a custom setup. How can I get storybook to work. I am assuming this issue is because I am not using create-react-app.

**Comment by ekeijl** [comment]
I'm pretty sure I had the same issue. In my case I have the `.storybook` config directory at the root of the project and my client code and its `package.json` in some other directory (`/src/client`).

Does it help to add `react` and `react-dom` to `devDependencies` in your root `package.json`?

**Comment by jackason** [comment]
I also encounter such problems. What should I do to start the project

**Comment by jackason** [comment]
> 你有可以分享的复制回购吗？如果没有，你能创建一个吗？了解[如何创建再现](https://storybook.js.org/docs/react/contribute/how-to-reproduce)。我们优先考虑复制问题而不是没有问题的问题。谢谢！🙏

I also encounter such problems. What should I do to start the project

**Comment by jackason** [comment]
> 你有可以分享的复制回购吗？如果没有，你能创建一个吗？了解[如何创建再现](https://storybook.js.org/docs/react/contribute/how-to-reproduce)。我们优先考虑复制问题而不是没有问题的问题。谢谢！🙏
npx sb init --type react_scripts
