### ISSUE TITLE
Storybook font replaces custom font

### ISSUE THREAD

**Issue by JacobWeinbren** [storybookjs/storybook#15826]
**Describe the bug**
The storybook font overrides any css properties you pass for the body/html font with `"Nunito Sans", -apple-system, ".SFNSText-Regular", "San Francisco", BlinkMacSystemFont, "Segoe UI", "Helvetica Neue", Helvetica, Arial, sans-serif;`', except for when you pass to a specific tag such as `h1`, `h2` or `p`. Then pass the font to be added as to the static folder.

If you want more details on the broader setup, it is on the [public repo](https://github.com/JacobWeinbren/miliband-components). 

**To Reproduce**
In `manager.head` and `preview.head` put the font face. Then add the `<style>` tag 

```css
body { /*This tag determines if it will pass to the element or not*/
    font-family: "Libre Franklin", sans-serif;
}
```

Under theme, pass 
```js
{
    base: "light",
    fontBase: '"Libre Franklin", sans-serif',
}
```

**Additional context**
This shows the font working with tags but not body or HTML. Also, it requires you to use !important, which is generally not good practice. Alternatively, you could use the * selector which is also not good practice.

**With the tag**
<img src="https://user-images.githubusercontent.com/5209161/129080064-7ac74e1b-cf27-4820-a137-959495b31d64.png" height="400">

**Without the tag**
<img src="https://user-images.githubusercontent.com/5209161/129080072-60b11df2-c635-40a4-a4ff-369fecab69df.png" height="400">

**Comment by Rusl10** [comment]
@JacobWeinbren Have you found any solution for this?

**Comment by JacobWeinbren** [comment]
I didn't at the end, if you have this problem my suggestion is the Storybook Discord is very helpful.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
