### ISSUE TITLE
Feature: Addon Outline keyboard shortcut

### ISSUE THREAD

**Issue by Andjag** [storybookjs/storybook#15831]
Outline addon does not seem to have a dedicated shortcut key to toggle the feature. It would be awesome to have it, just like Measure addon has a shortcut key "m", which makes using it a breeze 💨

**Comment by shilman** [comment]
Good golly!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-alpha.41 containing PR #17530 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
