### ISSUE TITLE
Lit - Story format error and ArgsTable support

### ISSUE THREAD

**Issue by JacobWeinbren** [storybookjs/storybook#15848]
In setting up lit.dev for Storybook, I am running into a lot of errors. Storybook is well suited for React, but using web components throws a lot of errors and I am not sure of many examples available - would you be able to point me in the right direction?

To create an element in a story, the [web-components documentation](https://storybook.js.org/docs/web-components/writing-stories/introduction) suggests having this for the button.stories.js

```js
import { html } from "lit-html";

const Template = ({ kind, icon }) => {
    return html`
        <mili-button .kind=${kind} .icon=${icon}></mili-button>
    `;
};

export const Primary = Template.bind({});
Primary.args = { kind: "Primary", icon: "" };
```

However, running this returns `'Expecting an HTML snippet or DOM node from the story: "Primary" of "Components / Button".`

To create an ArgTable, you can run the following
```html
<Canvas>
	<Story name="Primary Icon" id="components-button--primary" />
</Canvas>
<ArgsTable story="Primary Icon" />
```

But this returns the `Cannot read property 'id' of undefined`

Does documentation for lit.dev storybook exist? Is lit well supported or is this not the best route to go down?

**Comment by akhilmhdh** [comment]
Yes, i am also facing the same situation.

 I think storybook team is working on [storybook/lit](https://www.npmjs.com/package/@storybook/lit) which is in pre-release stage. 
 
 So one workaround for time being is i am using render function of lit, directly rendering it in dom

**Comment by CodeByAlex** [comment]
I am also facing this issue. Has anyone heard when @storybook/lit will be available?

**Comment by iameduardod** [comment]
Following up @shilman

**Comment by shilman** [comment]
@Westbrook @gaetanmaisse is this something you can help with?

**Comment by gaetanmaisse** [comment]
The story format looks good and is similar to what we have in [Storybook monorepo](https://github.com/storybookjs/storybook/blob/next/examples/web-components-kitchen-sink/src/components/sb-button.stories.ts) or in [Storybook repro example](https://github.com/storybookjs/repro-templates/blob/main/web_components_typescript/stories/Button.stories.ts).

So I'm not sure where the `Expecting an HTML snippet or DOM node from the story: "Primary" of "Components / Button"` can come from. Maybe multiple versions of `lit` and `lit-html` in your `node_modules` structure, can you try again with the latest rc (in which I updated Lit peerDep and so) and let me know if you're still facing this? 

Regarding the `ArgsTable` I tried something similar but get a different error: 

```jsx
<Canvas>
  <Story name="Primary" id="example-button--primary" />
</Canvas>

<ArgsTable story="Primary" />
```

![image](https://user-images.githubusercontent.com/4112568/142988026-63a2edf1-9725-4955-9811-016fbac374b7.png)


I will try to investigate and find out why the story name isn't properly forwarded.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
