### ISSUE TITLE
[Docs] expand docs  to discuss Tailwind integration when using Vite with React

### ISSUE THREAD

**Issue by pdevito3** [storybookjs/storybook#15849]
**Is your feature request related to a problem? Please describe**
-

**Describe the solution you'd like**
Similar to #14929, given tailwind css being the most popular css framework of 2019 and 2020, it would be highly appreciated if you could [expand the docs](https://storybook.js.org/blog/storybook-for-vite/) to go into how you can add tailwind to a project using react and Vite with storybook.

I personally have a newer project with postcss 8+, but having content go over both <=7 and 8+ would be useful. 

**Describe alternatives you've considered**
I've tried using all the `next` builds as well as the postcss plugin, but could be missing something with the syntax. 

**Are you able to assist to bring the feature to reality?**
I'm happy to try it out and confirm working builds, but I don't have enough depth in this domain to have a meaningful contribution.

**Comment by shilman** [comment]
Please file Vite-related issues in https://github.com/eirslett/storybook-builder-vite/

Closing this for now--please let me know if you think this ISN'T Vite-related and I'll reopen. Thank you! 🙏
