### ISSUE TITLE
build-storybook fails only when NODE_ENV is set to production

### ISSUE THREAD

**Issue by samesfahani-tuplehealth** [storybookjs/storybook#15846]
**Describe the bug**
This bug arose in CI and the issue seems to be related to `NODE_ENV` being set to production being the only difference. The actual error is not helpful as it is built code: `Error: Evaluation failed: TypeError: Cannot read property 'a' of undefined`. However, when storybook is built with NODE_ENV being set to development, it works just fine.

How does one even go about debugging this?
What is build-storybook doing in production mode that's different?

**System**
Environment Info:

  System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
    Yarn: 1.18.0 - ~/.nvm/versions/node/v12.18.3/bin/yarn
    npm: 7.7.5 - ~/.nvm/versions/node/v12.18.3/bin/npm
  Browsers:
    Chrome: 92.0.4515.131
    Edge: 92.0.902.67
    Firefox: 77.0.1
    Safari: 14.1.2
  npmPackages:
    @storybook/addon-actions: 6.3.7 => 6.3.7 
    @storybook/addon-links: 6.3.7 => 6.3.7 
    @storybook/addon-postcss: ^2.0.0 => 2.0.0 
    @storybook/addon-storyshots: 6.3.7 => 6.3.7 
    @storybook/addons: 6.3.7 => 6.3.7 
    @storybook/core: 6.3.7 => 6.3.7 
    @storybook/react: 6.3.7 => 6.3.7 

**Additional context**

**Comment by shilman** [comment]
The easiest thing is to spelunk into `node_modules` and log things out. I believe it's also possible to run Storybook in the node debugger, tho I haven't tried it https://github.com/storybookjs/storybook/issues/1754
