### ISSUE TITLE
Components inconsistency between storybook and a regular webpage

### ISSUE THREAD

**Issue by Zombobot1** [storybookjs/storybook#15847]
**Describe the bug**
I render the same component in a story and as a root of react application. I get different results

![image](https://user-images.githubusercontent.com/48030070/129419457-b8f0f068-e1e7-409f-b8b6-c25fea687d3f.png)

**To Reproduce**
1. Clone [repo ](https://github.com/Zombobot1/storybook-repro) with reproduction
2. yarn install
3. yarn start
4. yarn storybook
5. Compare resulting component look of both commands above

**System**
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  Binaries:
    Node: 16.0.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.0.0 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.20.6 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 92.0.4515.131
    Edge: Spartan (44.19041.1023.0), Chromium (92.0.902.73)
  npmPackages:
    @storybook/addon-actions: ^6.4.0-alpha.29 => 6.4.0-alpha.29
    @storybook/addon-docs: ^6.4.0-alpha.29 => 6.4.0-alpha.29
    @storybook/addon-essentials: ^6.4.0-alpha.29 => 6.4.0-alpha.29
    @storybook/addon-links: ^6.4.0-alpha.29 => 6.4.0-alpha.29
    @storybook/react: ^6.4.0-alpha.29 => 6.4.0-alpha.29

**Comment by shilman** [comment]
I'm pretty sure this is an issue with Storybook's dependency on emotion 10, while MUI theming depends on emotion 11. I tried a few workarounds (yarn resolutions, installing direct dependency on emotion 11), but couldn't get it working. Closing this as dupe to #13145 to help keep our issues under control.
