### ISSUE TITLE
typescript `declare` keyword breaks story compilation w/ babel >= 7.14

### ISSUE THREAD

**Issue by leevigraham** [storybookjs/storybook#15840]
**Describe the bug**

If any class in your project uses the `declare` keyword compilation breaks with the following error:

```
If you have already enabled that plugin (or '@babel/preset-typescript'), make sure that it runs before any plugin related to additional class features:
 - @babel/plugin-proposal-class-properties
 - @babel/plugin-proposal-private-methods
 - @babel/plugin-proposal-decorators
  15 | class ExampleClass {  16 |     // This line throws an error> 17 |     declare foo: string;     |     ^^^^^^^^^^^^^^^^^^^^  18 |     render() {  19 |         return `<div>Lorem</div>`;  20 |     }
```

**To Reproduce**

Repro: https://github.com/leevigraham/storybook-declare-test
Chromatic: https://www.chromatic.com/setup?appId=6115bd3f7dff2e003c1c495d

This story is compiling: https://github.com/leevigraham/storybook-declare-repro/blob/main/stories/working.stories.ts

This story is not compiling: https://github.com/leevigraham/storybook-declare-repro/blob/main/stories/failing.stories.ts

The difference between the two stories is this line: https://github.com/leevigraham/storybook-declare-repro/blob/main/stories/failing.stories.ts#L9

Babel 7.14 enabled `@babel/plugin-proposal-class-properties`, `@babel/plugin-proposal-private-methods` by default in `@babel/preset-env`. https://babeljs.io/blog/2021/04/29/7.14.0#highlights

It looks like storybook is pushing these plugins in which is no longer needed:

* https://github.com/storybookjs/storybook/blob/next/lib/core-common/src/utils/babel.ts#L11

The issue is caused by plugins being called before presets. `@babel/plugin-proposal-class-properties` is being called before `@babel/preset-typescript`.

One way I have seen this fixed is by adding the `@babel/plugin-transform-typescript` plugin manually in a custom `babel.rc` but this is not the right approach becuase `@babel/plugin-transform-typescript` will be called twice.

**System**

```
Environment Info:

  System:
    OS: macOS 11.5.1
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  Binaries:
    Node: 12.22.4 - /usr/local/bin/node
    Yarn: 3.0.0 - ~/.npm-packages/bin/yarn
    npm: 7.10.0 - ~/.npm-packages/bin/npm
  Browsers:
    Chrome: 92.0.4515.131
    Edge: 90.0.818.56
    Firefox: 88.0
    Safari: 14.1.2
  npmPackages:
    @storybook/addon-actions: ^6.4.0-alpha.29 => 6.4.0-alpha.29 
    @storybook/addon-docs: ^6.4.0-alpha.29 => 6.4.0-alpha.29 
    @storybook/addon-essentials: ^6.4.0-alpha.29 => 6.4.0-alpha.29 
    @storybook/addon-links: ^6.4.0-alpha.29 => 6.4.0-alpha.29 
    @storybook/html: ^6.4.0-alpha.29 => 6.4.0-alpha.29 
```

**Comment by viditganpi** [comment]
@leevigraham I am facing a similar issue. Were you able to solve this, without generating a `.babelrc` and adding the plugin?

**Comment by leevigraham** [comment]
@viditganpi Sorry mate, moved on from storybook so I can't remember 😕
