### ISSUE TITLE
Bug with measure tool: measure is shown under elements with really high z-index

### ISSUE THREAD

**Issue by Aarbel** [storybookjs/storybook#15859]
**Describe the bug**
As you can see radix-ui sets really high z-index, that causes the ruler to be show under the drawer
![image](https://user-images.githubusercontent.com/25119847/129729960-20a8498b-d75b-4aa9-b847-dceede404052.png)

**To Reproduce**
Just try the measure tool with a high index component

**Comment by Aarbel** [comment]
Cf #15860

**Comment by MichaelArestad** [comment]
I don't think it's a good idea to max out the z-index. Most browsers limit the maximum value for `z-index` to `2147483647`. You can see the element in your screenshot has maxed it out. That said, this might be our only option here. 

@winkerVSbecks do you have any other ideas? Outside of moving the canvas overlay outside of the iframe, I don't know that we have an alternative option.

**Comment by winkerVSbecks** [comment]
z-index seems like a reasonable compromise for now. 
I'm not sure what else we can do. It's in the iframe because it has to measure the DOM nodes, etc. We could potentially move rendering out of the iframe but, that'll require a lot more work. Potential v2 option.

**Comment by shilman** [comment]
Huzzah!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-alpha.7 containing PR #15860 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
