### ISSUE TITLE
UI: Single Story Hoisting does not work for components with multi-word names

### ISSUE THREAD

**Issue by johnnybenson** [storybookjs/storybook#15876]
**Describe the bug**

![image](https://user-images.githubusercontent.com/238022/129960563-6da39f97-963f-4bfe-b5d9-7d84760d0a00.png)

When a component has two words in its name, e.g. **`WorkspaceControl`** using PascalCase, it does not hoist the single story up, and instead creates the nesting originally mentioned here: https://github.com/storybookjs/storybook/issues/8255.

**To Reproduce**

```ts
import { Meta, Story } from '@storybook/react/types-6-0';
import { WorkspaceControl as Component, WorkspaceControlProps } from './WorkspaceControl';

export default {
    title: 'Builder/WorkspaceControl',
    component: Component,
    argTypes: {},
} as Meta;

const Template: Story<WorkspaceControlProps> = (args) => <Component {...args} />;

export const WorkspaceControl = Template.bind({});
WorkspaceControl.args = {} as const;
```

**System**

```
  System:
    OS: macOS 11.4
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
  Binaries:
    Node: 14.17.3 - ~/.nvm/versions/node/v14.17.3/bin/node
    Yarn: 1.22.11 - ~/.nvm/versions/node/v14.17.3/bin/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.3/bin/npm
  Browsers:
    Chrome: 92.0.4515.131
    Firefox: 76.0.1
    Safari: 14.1.1
  npmPackages:
    @storybook/addon-actions: ^6.3.6 => 6.3.6
    @storybook/addon-essentials: ^6.3.6 => 6.3.6
    @storybook/addon-links: ^6.3.6 => 6.3.6
    @storybook/node-logger: ^6.3.6 => 6.3.6
    @storybook/preset-create-react-app: ^3.2.0 => 3.2.0
    @storybook/react: ^6.3.6 => 6.3.6
```

**Additional context**

Related Pull Request: https://github.com/storybookjs/storybook/pull/13039
Original Issue: https://github.com/storybookjs/storybook/issues/8255
Other Related Issue: https://github.com/storybookjs/storybook/issues/10107

**Comment by ekeijl** [comment]
Can confirm.

Two ways to "fix" it, but it would be nice if it works out of the box:

A) **Name the export after the displayed story name:**
  ```
  WorkspaceControl.name = 'WorkspaceControl';
  ```

B) **Use a space in the Story title:**
  ```
  export default {
      title: 'Builder/Workspace Control',
  ```

Option B looks better in the UI.

**Comment by johnnybenson** [comment]
Thank you @ekeijl **Option B** works for me!

Typescript doesn't seem to like **Option A** with `TS2540: Cannot assign to 'name' because it is a read-only property.`

![image](https://user-images.githubusercontent.com/238022/130456706-6b07095d-46ef-4334-a818-2eb9b047c9ca.png)
