### ISSUE TITLE
Addons tool not showing on Google Chrome 92 (localhost only)

### ISSUE THREAD

**Issue by rogersampaio** [storybookjs/storybook#15880]
**The bug**
Addons toolbar is not showing on Google Chrome 92 when I run localhost. But it does appear on Chrome Canary v95

![image](https://user-images.githubusercontent.com/21226627/130030493-023c8809-5d4d-48dd-b7b4-b58d3d22141e.png)

**Comment by shilman** [comment]
probable dupe to https://github.com/storybookjs/storybook/issues/14916
