### ISSUE TITLE
From docs "Using children as an arg" seems like does not take stories.. 

### ISSUE THREAD

**Issue by androidsdreamofelectricsheep** [storybookjs/storybook#15893]
**Describe the bug**
I guess my code follows the "Using children as an arg" in the doc:
https://storybook.js.org/docs/react/workflows/stories-for-multiple-components

Please check mine below:

```
// checkFormField.stories.tsx

import { Meta, Story } from '@storybook/react';
import CheckFormField from '@components/old/signup/organisms/checkFormField/index';
import { CheckboxProps } from '@components/old/signup/molecules/checkbox/interfaces';

//👇 Instead of importing ListItem, we import the stories
import {DefaultCheckbox} from '@components/old/signup/molecules/checkbox/checkbox.stories';

export default {
  title: 'checkFormField',
  component: CheckFormField,
} as Meta;

const Template: Story = (args) => <CheckFormField {...args}/>

export const OneItem = Template.bind({})
OneItem.args = {
  children: [<DefaultCheckbox {...DefaultCheckbox.args as CheckboxProps}/>]
}
```

```
// checkbox.stories.tsx

import { Meta, Story } from '@storybook/react';
import Checkbox from '@components/old/signup/molecules/checkbox/index';
import { CheckboxProps } from '@components/old/signup/molecules/checkbox/interfaces';

export default {
  title: 'checkbox',
  component: Checkbox,
} as Meta;

const Template: Story<CheckboxProps> = (args) => <Checkbox {...args} />;

export const DefaultCheckbox = Template.bind({});

DefaultCheckbox.args = {
  id: 'test',
  labelText: 'Default Checkbox',
  tabIndex: 0,
  checked: false,
  isDiners: false,
};
```

But it throws error saying `bound Template cannot be used as component.`

I'm assuming literally `Template.bind({})` it's bound so error says as it is.

so I tried changing
```
// from
const Template: Story<CheckboxProps> = (args) => <Checkbox {...args} />;

// to
export const CheckboxTemplate: Story<CheckboxProps> = (args) => <Checkbox {...args} />;

export const OneItem = CheckboxTemplate.bind({})
OneItem.args = {
  children: [<CheckboxTemplate {...CheckboxTemplate .args as CheckboxProps}/>]
}
```
then, it eventually renders fine but cannot use Controls panel just like Checkbox story meaning it's lost functions by managing Control panel.

I'm kind of confused that `//👇 Instead of importing ListItem, we import the stories` meaning the stories reuses the template such as Primary, Secondary, Tertiary(code below) or `const Template: Story<ButtonProps> = (args) => <Button {...args} />;`

```
//👇 We create a “template” of how args map to rendering
const Template: Story<ButtonProps> = (args) => <Button {...args} />;

//👇 Each story then reuses that template
export const Primary = Template.bind({});
Primary.args = { background: '#ff0', label: 'Button' };

export const Secondary = Template.bind({});
Secondary.args = { ...Primary.args, label: '😄👍😍💯' };

export const Tertiary = Template.bind({});
Tertiary.args = { ...Primary.args, label: '📚📕📈🤓' };
```

If it means to import `Template`, is there a way to import each story?

**System**
    "react": "^17.0.2",
    "@emotion/react": "^11.4.0",
    "@storybook/addon-actions": "^6.3.6",
    "@storybook/addon-essentials": "^6.3.6",
    "@storybook/addon-links": "^6.3.6",
    "@storybook/addon-postcss": "^2.0.0",
    "@storybook/react": "^6.3.6",

**Additional context**

**Comment by shilman** [comment]
@jonniebigodes can you please take a look at this one?

**Comment by jonniebigodes** [comment]
Will do! @androidsdreamofelectricsheep if you could create a small reproduction following [these instructions](https://storybook.js.org/docs/react/contribute/how-to-reproduce) it would help out a lot! Let me know and we'll go from there. Sounds good?

**Comment by jonniebigodes** [comment]
Closing this for now! The documentation already contains this caveat. Hopefully, in the near future, we'll improve on the feature and be able to properly reference it. Once it's done the documentation will be updated accordingly.


Thanks for raising this issue with us and sorry for the delayed response.

Hope you have a great week!

Stay safe
