### ISSUE TITLE
Storybook Controls broken after 6.2 to 6.3 upgrade (and Webpack 4 to 5).

### ISSUE THREAD

**Issue by seanmcintyre** [storybookjs/storybook#15896]
## Description
Storybook controls are no longer being created correctly (or at all) after updating from 6.2 to 6.3. I also made moderate changes to the config as part of the update, including forcing the use of Webpack 5.

You can view the correct output on the stories here (`main` branch):
https://vimeo.github.io/iris/sb/main/?path=/story/components-buttons-button--button

You can view the faulty output on the stories here (`refactor` branch):
https://vimeo.github.io/iris/sb/refactor/?path=/story/components-button--button

Here's the current config files:
https://github.com/vimeo/iris/tree/main/.storybook

And the new config for the `refactor` branch:
https://github.com/vimeo/iris/tree/refactor/.storybook

## Reproduction
You can view this issue at https://github.com/vimeo/iris/tree/refactor.
1. Clone/pull and check out the `refactor` branch
2. Run `yarn`
3. Run `yarn storybook`

## System

Environment Info:
```
  System:
    OS: macOS 11.5.2
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Binaries:
    Node: 14.17.3 - ~/.nvm/versions/node/v14.17.3/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.3/bin/npm
  Browsers:
    Chrome: 92.0.4515.159
    Firefox: 90.0.2
    Safari: 14.1.2
  npmPackages:
    @storybook/addon-a11y: ^6.3.7 => 6.3.7 
    @storybook/addon-design-assets: ^6.2.9 => 6.2.9 
    @storybook/addon-essentials: ^6.3.7 => 6.3.7 
    @storybook/addon-knobs: ^6.3.0 => 6.3.0 
    @storybook/addon-links: ^6.3.7 => 6.3.7 
    @storybook/addon-storysource: ^6.3.7 => 6.3.7 
    @storybook/addons: ^6.3.7 => 6.3.7 
    @storybook/builder-webpack5: ^6.4.0-alpha.31 => 6.4.0-alpha.31 
    @storybook/components: ^6.3.7 => 6.3.7 
    @storybook/core-events: ^6.3.7 => 6.3.7 
    @storybook/manager-webpack5: ^6.4.0-alpha.31 => 6.4.0-alpha.31 
    @storybook/react: ^6.3.7 => 6.3.7 
    @storybook/theming: ^6.3.7 => 6.3.7 
```

## Screenshots
**before**
<img width="600" alt="Screen Shot 2021-08-23 at 1 20 20 PM" src="https://user-images.githubusercontent.com/319302/130489835-40fb7f78-b762-4787-8f90-85bcefc0749c.png">

**after**
<img width="600" alt="Screen Shot 2021-08-23 at 1 20 18 PM" src="https://user-images.githubusercontent.com/319302/130489875-ac57005b-7325-4fa9-9ee5-a78edc2de870.png">

**Comment by seanmcintyre** [comment]
I may have isolated the issue to setting `docs: false` for `addon-essentials`. Controls show up when `docs: true`. Is this intended?

**Comment by shilman** [comment]
Yes that's intended (although suboptimal). There should be a warning in the CLI output saying that you should run `addon-docs` before `addon-controls` -- this is why.

We're planning a big refactor to decouple the two addons, so that controls and docs can function independently from one another. In the meantime, `addon-docs` is required for auto-generated controls.

**Comment by seanmcintyre** [comment]
A warning would be much appreciated! As would a different output to the controls addon panel when addon-docs is disabled!

**Comment by shilman** [comment]
I meant you should see a warning today--tho I realize that the warning heuristic is incomplete and doesn't handle your use case. Hopefully we can solve this strange interdependency soon!

**Comment by scott-thrillist** [comment]
@seanmcintyre did you ever get this fixed? We need docs for our Storybook instance to function. Also having issues with Storybook 6.3.8 + webpack 5 using addon-essentials.  Not getting anything to render:

`TypeError: Parameter 'url' must be a string, not undefined`

Most likely something we're doing but wanted to publish here in case anyway ran into a similar issue.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
