### ISSUE TITLE
Angular's ngNonBindable throws an error on content tags

### ISSUE THREAD

**Issue by artaommahe** [storybookjs/storybook#15905]
**Describe the bug**
Angular has a [ngNonBindable](https://angular.io/guide/attribute-directives#deactivating-angular-processing-with-ngnonbindable) 'directive' that deactivates parsing of this tag's content by angular and treats it as a raw html. With the last versions of storybook it is broken in the stories templates.

**To Reproduce**
- git clone https://github.com/artaommahe/storybook-angular-ng-non-bindable
- yarn install
- yarn storybook
- open `/?path=/story/example-nonbindable--primary` story (https://github.com/artaommahe/storybook-angular-ng-non-bindable/blob/main/src/stories/NonBindable.stories.ts#L20)
- see an error
  ```
  core.js:14966 NG0304: 'storybook-button' is not a known element:
  ```

Expected behavior is just ignoring everything inside `ngNonBindable` tag and insert it just as plain html.

**System**

```
PS D:\projects\tests\storybook-angular-ng-non-bindable> npx sb@next info

Environment Info:

  System:
    OS: Windows 10 10.0.19043
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 14.17.4 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.0.1 - C:\Program Files\nodejs\yarn.CMD
    npm: 6.14.14 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 92.0.4515.159
    Edge: Spartan (44.19041.1023.0), Chromium (92.0.902.78)
  npmPackages:
    @storybook/addon-actions: ^6.4.0-alpha.32 => 6.4.0-alpha.32
    @storybook/addon-docs: ^6.4.0-alpha.32 => 6.4.0-alpha.32
    @storybook/addon-essentials: ^6.4.0-alpha.32 => 6.4.0-alpha.32
    @storybook/addon-links: ^6.4.0-alpha.32 => 6.4.0-alpha.32
    @storybook/angular: ^6.4.0-alpha.32 => 6.4.0-alpha.32
    @storybook/builder-webpack5: ^6.4.0-alpha.32 => 6.4.0-alpha.32
    @storybook/manager-webpack5: ^6.4.0-alpha.32 => 6.4.0-alpha.32
```

**Additional context**

This thing worked fine in storybook's templates before some storybook version (i think it was update to the 6.3+ that broke this behaviour).
We use templates + ngNonBindable for some complex cases when we have to emulate html string passing to the component that renders this html with angular components resolving and having this html inside html file for proper formatting and highlighting. It looks like this
```html
<!-- some-story-template.html -->
<sky-block-dev-platform ngNonBindable>
  <vim-dnd-text>
    <vim-dnd-text-drags>
      <vim-dnd-text-drag answer-id="1">a lot of</vim-dnd-text-drag>
      <vim-dnd-text-drag answer-id="2">in</vim-dnd-text-drag>
      <vim-dnd-text-drag answer-id="3">is</vim-dnd-text-drag>
      <vim-dnd-text-drag answer-id="4">are</vim-dnd-text-drag>
      <vim-dnd-text-drag answer-id="5">some</vim-dnd-text-drag>
    </vim-dnd-text-drags>
  </vim-dnd-text>
</sky-block-dev-platform>
```

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
