### ISSUE TITLE
--story-format option has no effect

### ISSUE THREAD

**Issue by sharebear** [storybookjs/storybook#15908]
**Describe the bug**
When running `npx sb init` the `--story-format` option does not override the language detection.

I just tried adding storybook to a project that that I'm about to start working on and, for some reason I've yet to understand, package.json declares a dependency on typescript even though the project doesn't appear to use typescript. This resulted in `npx sb init` generating typescript and tsx files that weren't detected when running `npm run storybook`. Looking at the output of `npx sb init --help` I found that there is a parameter `--story-format <csf | csf-ts | mdx >             Generate stories in a specified format` that one would assume allows you to force which format is generated.

Unfortunately it seems that the generator doesn't even unpack the storyFormat Option from the `GeneratorOptions` here https://github.com/storybookjs/storybook/blob/next/lib/cli/src/generators/baseGenerator.ts#L66 rendering the storyFormat option useless.

**System**
```
Environment Info:

  System:
    OS: Linux 4.15 Ubuntu 18.04.5 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  Binaries:
    Node: 14.17.5 - /usr/bin/node
    npm: 7.5.2 - ~/.node/bin/npm
  Browsers:
    Chrome: 91.0.4472.114
    Firefox: 90.0.2
  npmPackages:
    @storybook/addon-actions: ^6.3.7 => 6.3.7 
    @storybook/addon-essentials: ^6.3.7 => 6.3.7 
    @storybook/addon-links: ^6.3.7 => 6.3.7 
    @storybook/builder-webpack5: ^6.3.7 => 6.3.7 
    @storybook/manager-webpack5: ^6.3.7 => 6.3.7 
    @storybook/react: ^6.3.7 => 6.3.7 

```

**Comment by shilman** [comment]
This is an old option that should be deleted from the code and the documentation. Can anybody give a hand and create a PR for that? 🙏

**Comment by shilman** [comment]
Huzzah!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-beta.5 containing PR #16233 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
