### ISSUE TITLE
[addon-storyshots] storyshots found 0 stories: TypeError: Cannot destructure property 'instrument' of 'undefined' as it is undefined.

### ISSUE THREAD

**Issue by ldeveber** [storybookjs/storybook#15916]
**Describe the bug**

I upgraded `jest` from `26.6.3` to `27.0.6`. All other tests are passing (after adding `testEnvironment: 'jest-environment-jsdom',` to my `jest.config.js`), its only the storybook snapshots that are failing.

```bash
 FAIL  tests/Storyshots.test.js
  ● Test suite failed to run

    storyshots found 0 stories

      18 | });
      19 |
    > 20 | initStoryshots({
         | ^
      21 |   configPath: path.resolve(__dirname, '../.storybook'),
      22 |   framework: 'react',
      23 |   // integrityOptions: { cwd: path.resolve(__dirname, '../stories') },

      at testStorySnapshots (node_modules/@storybook/addon-storyshots/dist/ts3.9/api/index.js:86:15)
      at Object.<anonymous> (tests/Storyshots.test.js:20:1)

  console.warn
    Unexpected error while loading ./components/Alert.stories.js: TypeError: Cannot destructure property 'instrument' of 'undefined' as it is undefined.

      at Object.warn (node_modules/@storybook/client-logger/dist/cjs/index.js:67:65)
      at node_modules/@storybook/core-client/dist/cjs/preview/loadCsf.js:92:34
          at Array.forEach (<anonymous>)
      at node_modules/@storybook/core-client/dist/cjs/preview/loadCsf.js:85:20
          at Array.forEach (<anonymous>)
      at node_modules/@storybook/core-client/dist/cjs/preview/loadCsf.js:84:12
      at ConfigApi.configure (node_modules/@storybook/client-api/dist/cjs/config_api.js:26:7)
```

**To Reproduce**
Please create a reproduction by running `npx sb@next repro` and following the instructions. Read our [documentation](https://storybook.js.org/docs/react/contribute/how-to-reproduce) to learn more about creating reproductions.
Paste your repository and deployed reproduction here. We prioritize issues with reproductions over those without.

**System**
Please paste the results of `npx sb@next info` here.

```bash
=^.^= npx sb@next info

Environment Info:

  System:
    OS: macOS 11.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 14.17.1 - ~/.nvm/versions/node/v14.17.1/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.17.1/bin/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.1/bin/npm
  Browsers:
    Chrome: 92.0.4515.159
    Safari: 14.1.1
  npmPackages:
    @storybook/addon-a11y: ^6.3.7 => 6.3.7 
    @storybook/addon-essentials: ^6.3.7 => 6.3.7 
    @storybook/addon-links: ^6.3.7 => 6.3.7 
    @storybook/addon-storyshots: ^6.3.7 => 6.3.7 
    @storybook/addon-storysource: ^6.3.7 => 6.3.7 
    @storybook/addons: ^6.3.7 => 6.3.7 
    @storybook/builder-webpack5: ^6.3.7 => 6.3.7 
    @storybook/core: ^6.3.7 => 6.3.7 
    @storybook/manager-webpack5: ^6.3.7 => 6.3.7 
    @storybook/react: ^6.3.7 => 6.3.7 
    @storybook/source-loader: ^6.3.7 => 6.3.7 

=^.^= 
```

**Additional context**

I tried to reproduce it with the new repo but I'm going to have to come back to that in a bit >_<

**Comment by cloakedninjas** [comment]
Just ran into this with `6.4.0-alpha.30` in our Angular app, (we are also using `addon-storyshots`) so I wonder if it's related to [this line](https://github.com/storybookjs/storybook/blob/7064642e1aee7786c77fe735c064c0c29dbcee01/addons/storyshots/storyshots-core/injectFileName.js#L12)

**Comment by Kathuria** [comment]
Facing similar issue with mdx stories as well. I am using latest stable storybook version i.e. `6.3.8`.

**Comment by ArvinH** [comment]
> Just ran into this with `6.4.0-alpha.30` in our Angular app, (we are also using `addon-storyshots`) so I wonder if it's related to [this line](https://github.com/storybookjs/storybook/blob/7064642e1aee7786c77fe735c064c0c29dbcee01/addons/storyshots/storyshots-core/injectFileName.js#L12)

I looked into the issue a bit more...after Jest 27, the API of `process` [changed](https://github.com/facebook/jest/pull/10834), `instrument` is in the `TransformOptions` [now](https://github.com/facebook/jest/pull/10834/files#diff-e49fa57ed2b34a574ee701513c588dd93fa7b264591c236ef9a445803a894894R21).

Also, Jest don't export `ScriptTransformer` class anymore, instead they export async function `createScriptTransformer`.
https://github.com/facebook/jest/pull/11163

But if we change to use `createScriptTransformer`, the `process` function needs to be `processAsync`, which requires [ESM](https://jestjs.io/docs/ecmascript-modules) 🤔  ... I don't have a solution yet, just put my observation to the table and see if someone can help.

**Comment by ArvinH** [comment]
Hi @Hypnosphi could you take a look of this issue? consider the `injectFileName` are written by you in https://github.com/storybookjs/storybook/pull/8000

I'm happy to help fix this issue but I'm having trouble on understand the logic in `injectFileName`, especially on why exactly do we need to chain the transformer, would you please shed some light on this?

**Comment by Tiberriver256** [comment]
Any workaround for getting Jest 27 to work with mdx stories?

**Comment by eiel** [comment]
I wrote a makeshift jest-transform to get around it.

```javascript
// https://github.com/storybookjs/storybook/blob/v6.4.14/addons/storyshots/storyshots-core/injectFileName.js#L12
function findTransform(transform, fileName) {
  const self = transform.find(([pattern]) =>
    new RegExp(pattern).test(fileName),
  );
  const transformExcludeSelf = transform.filter(t => t !== self);
  return transformExcludeSelf.find(([pattern]) => new RegExp(pattern).test(fileName));
}

function generateCJS(fileName, { code }) {
  return `${code};
if(exports.default != null) {
  exports.default.parameters = exports.default.parameters || {};
  exports.default.parameters.fileName = '${fileName.replace(/\\/g, '\\\\')}';
}
`;
}

module.exports = {
  process(src, fileName, config) {
    const [,transformFileName] = findTransform(config.config.transform, fileName);
    const processed = require(transformFileName).default.process(src, fileName, config);
    return generateCJS(fileName, processed);
  },
};
```

jest.config.js:
```javascript
  transform: {
    '^.+\\.stories\\.tsx?$': '<rootDir>/injectFileName.js',
    // '^.+\\.stories\\.tsx?$': '@storybook/addon-storyshots/injectFileName',
    '^.+\\.[jt]sx?$': 'babel-jest',
  },
```

**Comment by matthew-dean** [comment]
@eiel That definitely did not work for me and just caused more errors. :/

**Comment by aendra-rininsland** [comment]
I've created a basic repro using 6.4.22 + the Vite builder here: https://github.com/aendra-rininsland/storybook-vite-storyshots-react-repro

**Comment by SimenB** [comment]
https://www.npmjs.com/package/jest-chain-transform is a better approach than trying to do it inside of another transformer that has logic.

Note that it won't work with ESM transformers (but `injectFilename` doesn't either)

```js
'use strict';

const dedent = require('dedent');

// simplified version of https://github.com/storybookjs/storybook/blob/82696f194790378720ecb5e946f4bb3636a9e0df/addons/storyshots/storyshots-core/injectFileName.js
module.exports = {
  process(src, fileName) {
    return {
      code: dedent`${src};
if(exports.default != null) {
  exports.default.parameters = exports.default.parameters || {};
  exports.default.parameters.fileName = '${fileName.replace(/\\/g, '\\\\')}';
}
`,
    };
  },
};
```

**Comment by FlorianBurgevin** [comment]
Hello.

Same problem for me with jest 28 and storybook 6.5 with MDX stories

**Comment by glrodasz** [comment]
Ok, I go this issue a few days back when I try to update all my dependencies, looks like StoryShots is not compatible with  Jest 27 and beyond.

But because of [this](https://discord.com/channels/486522875931656193/505590669549633536/940639784056000552) answer 
![image](https://user-images.githubusercontent.com/1431663/183114229-0bcec843-438d-4d49-9a30-68b0302845bf.png)
 and this discussion https://github.com/storybookjs/storybook/discussions/18119 I wanted to try the approach of using` `@storybook/react-testing` to bring the composed stories and "manually" create DOM snapshots with Jest.

It went well but still required to create a test file per component, so I refactored my approach and manage to have similar result as StoryShots and this is my final file:  https://github.com/glrodasz/cero-components/blob/master/storybook.test.js

*The config is still specified for my project but maybe can help you*

What I'm doing is the following:

1. [Load all the story files and resolved their modules import](https://github.com/glrodasz/cero-components/blob/master/storybook.test.js#L42 )
2. [Loop over the stories  of each component and take the CSF stories](https://github.com/glrodasz/cero-components/blob/master/storybook.test.js#L47) to use `composeStories` from `@storybook/testing-react`
3. [Create individual snapshot files](https://github.com/glrodasz/cero-components/blob/master/storybook.test.js#L55) using `jest-specific-snapshot`

If you were using StoryShots only to create DOM snapshots this will do the same for you without StoryShots addon.

**Comment by ndelangen** [comment]
The future of storyshots is the test-runner:
https://storybook.js.org/docs/react/writing-tests/test-runner#page-top

And use the play function for expectations:
https://storybook.js.org/docs/react/writing-stories/play-function#page-top

We will not be making any improvement / changes to storyshots.
