### ISSUE TITLE
Global decorators not applied to MDX docs

### ISSUE THREAD

**Issue by Alphy11** [storybookjs/storybook#15912]
**Describe the bug**
I was toying around with MDX based stories, and discovered that global decorators are not applied to stories rendered in MDX in the docs pane (but are applied to them in the canvas pane).
In the example, you'll see I add a global decorator in preview.js:
```js
export const decorators = [
  (Story) => (
    <div>
      <div>This is content in the decorator!</div>
      <Story />
    </div>
  ),
]
```
and define a story:
```
<Meta title="Introduction" component={() => {}} />

<Story name="SomeStory">
  <div>I am a story!</div>
</Story>
```
Canvas page (extra content appears):
![image](https://user-images.githubusercontent.com/18182784/130713408-ea4fb2ae-1b74-446a-ad50-aca2ac0f9d19.png)

Docs page (no extra content from decorator):
![image](https://user-images.githubusercontent.com/18182784/130713433-e67f4353-9a36-43f9-838a-2ef860f991f4.png)

**To Reproduce**
[REPO](https://github.com/Alphy11/StorybookMDXDecoratorBug/tree/master)
[STORYBOOK](https://alphy11.github.io/StorybookMDXDecoratorBug/?path=/story/introduction--some-story)

**System**
```
Environment Info:

  System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 12.22.1 - /usr/local/bin/node
    Yarn: 3.0.1 - /usr/local/bin/yarn
    npm: 6.14.12 - /usr/local/bin/npm
  Browsers:
    Chrome: 92.0.4515.159
    Firefox: 78.10.1
    Safari: 14.1.1
  npmPackages:
    @storybook/addon-actions: ^6.4.0-alpha.32 => 6.4.0-alpha.32 
    @storybook/addon-docs: ^6.4.0-alpha.32 => 6.4.0-alpha.32 
    @storybook/addon-essentials: ^6.4.0-alpha.32 => 6.4.0-alpha.32 
    @storybook/addon-links: ^6.4.0-alpha.32 => 6.4.0-alpha.32 
    @storybook/react: ^6.4.0-alpha.32 => 6.4.0-alpha.32 
    @storybook/storybook-deployer: ^2.8.10 => 2.8.10 
```

**Comment by Alphy11** [comment]
The issue ended up being that I was not importing `Story` before using it, and that apparently makes it just skip over that line.  I wonder if MDX should fail on undefined components?

**Comment by shilman** [comment]
@Alphy11 there are a lot of issues in MDX handling and better error handling is one of them. I'm waiting for MDX v2 to become available before I try to hunt this down. Hopefully they have fixed it, or provide better options for clients to intercept errors!

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
