### ISSUE TITLE
Blocked a frame with origin "null" from accessing a cross-origin frame.

### ISSUE THREAD

**Issue by godfreyd** [storybookjs/storybook#15926]
**Describe the bug**
After  `build-storybook` I get this error:
<img width="1437" alt="Screenshot 2021-08-27 at 11 39 28" src="https://user-images.githubusercontent.com/6197968/131105764-68747827-3684-4195-967b-5a210b501685.png">

**System**
```
System:
    OS: macOS 11.2.3
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 16.4.2 - ~/.nvm/versions/node/v16.4.2/bin/node
    npm: 7.18.1 - ~/.nvm/versions/node/v16.4.2/bin/npm
  Browsers:
    Chrome: 92.0.4515.159
    Firefox: 91.0
    Safari: 14.0.3
  npmPackages:
    @storybook/addon-actions: ^6.3.7 => 6.3.7
    @storybook/addon-controls: ^6.3.7 => 6.3.7
    @storybook/addon-docs: ^6.3.7 => 6.3.7
    @storybook/addon-essentials: ^6.3.7 => 6.3.7
    @storybook/addon-links: ^6.3.7 => 6.3.7
    @storybook/addon-postcss: ^2.0.0 => 2.0.0
    @storybook/react: ^6.3.7 => 6.3.7
```

**Comment by shilman** [comment]
Do you a have a reproduction repo you can share? If not, can you create one? See [how to create a repro](https://storybook.js.org/docs/react/contribute/how-to-reproduce). We prioritize issues with reproductions over those without. Thank you! 🙏
