### ISSUE TITLE
DefinePlugin: "Conflicting values for 'process.env'" if you have a .env file

### ISSUE THREAD

**Issue by jdelStrother** [storybookjs/storybook#15927]
**Describe the bug**
If you have a .env file present in the cwd, it causes a warning to be emitted:

```
WARNING in DefinePlugin
Conflicting values for 'process.env'
```

**To Reproduce**
Checkout https://github.com/jdelStrother/conflicting-process-env
Run `yarn`
Run `yarn start-storybook --smoke-test`

**System**

```
Environment Info:

  System:
    OS: macOS 11.5.2
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 16.2.0 - ~/.nix-profile/bin/node
    Yarn: 1.22.10 - ~/.nix-profile/bin/yarn
    npm: 7.13.0 - ~/.nix-profile/bin/npm
  npmPackages:
    @storybook/addon-actions: ^6.3.7 => 6.3.7
    @storybook/addon-essentials: ^6.3.7 => 6.3.7
    @storybook/addon-links: ^6.3.7 => 6.3.7
    @storybook/addon-storyshots: ^6.3.7 => 6.3.7
    @storybook/builder-webpack5: ^6.3.7 => 6.3.7
    @storybook/core: ^6.3.7 => 6.3.7
    @storybook/manager-webpack5: ^6.3.7 => 6.3.7
    @storybook/react: ^6.3.7 => 6.3.7
    @storybook/theming: ^6.3.7 => 6.3.7
```

**Additional context**

When running storybook interactively, one can just ignore this warning. However, it does cause `start-storybook --smoke-test` to fail, which is annoying for CI purposes. I don't actually want my .env file loaded in storybook, but can't see a good way of preventing the automatic detection.

**Comment by shilman** [comment]
Ta-da!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-alpha.34 containing PR #15925 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
