### ISSUE TITLE
Storybook when implemented with angular project stops at 99% done plugins webpack-hot-middlewarewebpack built preview 9274e59d341ad7e42dee in 1122ms

### ISSUE THREAD

**Issue by suhas-007** [storybookjs/storybook#15922]
**Describe the bug**
Storybook when implemented with angular project stops at 99% done plugins webpack-hot-middlewarewebpack built preview 9274e59d341ad7e42dee in 1122ms

**To Reproduce**
Run the following commands :
      mkdir emptyangularapp  -- create a directory.
      cd emptyangularapp/      -- move inside the directory.
      ng new test                      -- create a new angular project.
       cd test/                           -- move inside the project.
      npx sb init                        -- Install storybook.
      npm run storybook          -- run storybook.

**System**
npm run storybook stops at this :
99% done plugins webpack-hot-middlewarewebpack built preview 9274e59d341ad7e42dee in 1122ms

**Comment by shilman** [comment]
closing as dupe to #14405
