### ISSUE TITLE
‼️ 🛑 Composition is broken in Safari (desktop and mobile)

### ISSUE THREAD

**Issue by tim-mukhin** [storybookjs/storybook#15920]
Hi!
Could you please fix this issue. It's blocker for us. Most of our developers in company use Macbooks and many of them use Safari.

**Describe the bug**
The Composition on Safari browser (desktop and mobile) is broken. See the reproducing steps.

**To Reproduce**
1. First option with official storybook
Steps:
- Open [official storybook](https://next--storybookjs.netlify.app/official-storybook) from the docs.
- Scroll down on the left panel to external storybook, open any story, wait until it loads and select the Docs tab

![image](https://user-images.githubusercontent.com/8345600/130849984-8284c151-87a7-411f-82b9-925fde6af933.png)

- Scroll stories back to top and choose any story from the current storybook
- Now the docs tab will stuck with docs from external storybook

![image](https://user-images.githubusercontent.com/8345600/130850051-4a380fcd-ca59-40d4-8b13-e877dc598527.png)

2. Second option with [repro repository](https://github.com/tim-mukhin/sb-safari-repro)
- Clone this repo
- Install dependencies
- Start storybook with `yarn storybook`
- Scroll down on the left panel to external storybook `sample2`, open any story, wait until it loads and select the Docs tab

![image](https://user-images.githubusercontent.com/8345600/130850096-62fde0ed-b15a-496b-9e90-7189607856d0.png)

- Scroll stories back to top and choose any story from the current storybook
- Now you can see "No docs" block on any docs page

![image](https://user-images.githubusercontent.com/8345600/130850151-c713131f-336b-43a6-b0a7-a38007ead2d0.png)

- And after that you can also reproduce the issue from first oprion if you open external 'Official storybook'

**System**
```
System:
    OS: macOS 11.5
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 14.17.4 - ~/.nvm/versions/node/v14.17.4/bin/node
    Yarn: 3.0.1 - ~/.nvm/versions/node/v14.17.4/bin/yarn
    npm: 6.14.14 - ~/.nvm/versions/node/v14.17.4/bin/npm
  Browsers:
    Edge: 92.0.902.78
    Firefox: 90.0.2
    Safari: 14.1.2
  npmPackages:
    @storybook/addon-actions: ^6.4.0-alpha.32 => 6.4.0-alpha.32 
    @storybook/addon-docs: ^6.4.0-alpha.32 => 6.4.0-alpha.32 
    @storybook/addon-essentials: ^6.4.0-alpha.32 => 6.4.0-alpha.32 
    @storybook/addon-links: ^6.4.0-alpha.32 => 6.4.0-alpha.32 
    @storybook/node-logger: ^6.4.0-alpha.32 => 6.4.0-alpha.32 
    @storybook/preset-create-react-app: ^3.2.0 => 3.2.0 
    @storybook/react: ^6.4.0-alpha.32 => 6.4.0-alpha.32 
```

**Additional context**
The issue also reprodusable on MacOS Catalina and iOS 14

**Comment by shilman** [comment]
@tim-mukhin we're looking at composition again as part of a giant performance refactor that's happening in 6.4, so I'll try to squeeze this in.

**Comment by shilman** [comment]
Boo-yah!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-alpha.49 containing PR #17679 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Crikey!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.20 containing PR #17679 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```

**Comment by tim-mukhin** [comment]
Yay! Many thanks! Already upgrading and testing 🥳🥳🥳
