### ISSUE TITLE
How to deep link to a Tab I've generated via addon

### ISSUE THREAD

**Issue by steffchep** [storybookjs/storybook#15942]
### Discussed in https://github.com/storybookjs/storybook/discussions/15931

<div type='discussions-op-text'>

<sup>Originally posted by **steffchep** August 27, 2021</sup>
So, I've created a custom addon to display an additional tab next to Canvas and Docs which will hold additional information for Designers. 
This works nicely including updating my URL to 
http://localhost:3333/?path=/design/components-example

However, when I copy and paste this link into a new tab, I get forwarded to the canvas tab of that story (address bar link gets changed accordingly)

What do I have to do to make my new tab show up first if it is in the path?

Also, when Canvas or Docs is selected and I click on another story, the new story opens to that same tab. This doesn't happen when I have my custom tab open - new stories will open to the Canvas tab

I followed the instructions for [UI-based-addons](https://storybook.js.org/docs/react/addons/addon-types#ui-based-addons) to create my addon.</div>

**Comment by shilman** [comment]
closing as dupe to #15931

**Comment by steffchep** [comment]
I was hoping my question would get more attention here, since I had no replies on the forum for several days, at which time I don't really expect anyone to still notice the question. So I used the "create issue from discussion" button that was so conveniently there. Sorry if that was out of line.
