### ISSUE TITLE
Unable to write Pug in Storybook's template

### ISSUE THREAD

**Issue by sergiocastrovale** [storybookjs/storybook#15949]
### Discussed in https://github.com/storybookjs/storybook/discussions/15948

<div type='discussions-op-text'>

<sup>Originally posted by **sergiocastrovale** August 31, 2021</sup>
I have a Vue project who uses Pug templates. They **compile** just fine, however I'd like to use Storybook so that our team could just copy and past each component example into their code.

The thing is, I'm unable to compile **storybook's** templates in Pug.

This works:
```
const Template = (_, { argTypes }) => ({
  props: Object.keys(argTypes),
  components: { AppPagination },
  template: `
      <AppPagination v-bind="$props" />
  `,
});
```

but this doesn't:

```
const Template = (_, { argTypes }) => ({
  props: Object.keys(argTypes),
  components: { AppPagination },
  template: `
    AppPagination(v-bind="$props")
  `,
});
```

Any idea how to make this work?</div>

**Comment by shilman** [comment]
closing as dupe to #15948
