### ISSUE TITLE
reduce unecessary transitive dependencies: @icons/material

### ISSUE THREAD

**Issue by raDiesle** [storybookjs/storybook#15943]
**Describe the bug**
- when working on multiple web projects at the same time, a typical issue is performance on huge load of files in node_modules.
- most related issue is the number of fileWatchers of the underlying file-storage-system
- analysis shows that storybook dependency is by far the most files to download by transitive dependency files in our projects
- especial @icons/material has 4500 files, which is next biggest provider after @babel dependency
- when deleting the folder from node_modules, storybook seems still to render, so icons seem to be unused

| +-- @storybook/components@6.0.22
...
| | | +-- @icons/material@0.2.4

**To Reproduce**
see above

**Comment by shilman** [comment]
We're addressing the file watching issue with an overhaul of the core architecture. To be merged in the next few weeks: https://github.com/storybookjs/storybook/pull/15871

**Comment by raDiesle** [comment]
awesome!

**Comment by stof** [comment]
`@icons/material` is not a dependency of Storybook, so the initial report looks suspicious to me.

**Comment by shilman** [comment]
Indeed @stof 🤦‍♂️  -- closing this

**Comment by LuisReinoso** [comment]
Storybook version: 6.1.21

`@icons/material` is a dependency of `react-color` and `react-color` is part of `@storybook/components`
