### ISSUE TITLE
CLI: Add framework info in banner

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#15951]
**Is your feature request related to a problem? Please describe**
I recently spent some time trying to figure out why a Storybook in my project was not working correctly.
The project I'm working on is a monorepo that contains roughly 12 storybook instances. In the end, the problem was happening because an HTML storybook was running with @storybook/react instead of @storybook/html.

Storybook provides the info about which package is being run as the very first log in the CLI, however that can easily be missed because the following logs (e.g. webpack) can add a lot of clutter.

**Describe the solution you'd like**

It would be pretty great if there was some info in the CLI banner which would mention the framework, like you can see in these concepts:

**Before:**
![image](https://user-images.githubusercontent.com/1671563/131527394-4793151f-25ac-4901-895d-15b3bfd787cb.png)

**After:**
![image](https://user-images.githubusercontent.com/1671563/131526701-07dbbf8b-43bc-40c7-ad8b-2471d2a5b59b.png)

![image](https://user-images.githubusercontent.com/1671563/131526656-8604d8bc-2d9e-48ff-a206-c57742c51112.png)

**Are you able to assist to bring the feature to reality?**
yup!

**Comment by domyen** [comment]
Sounds like a good idea to me

**Comment by shilman** [comment]
Love this @yannbf ❤️

**Comment by shilman** [comment]
Ta-da!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-alpha.34 containing PR #15966 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
