### ISSUE TITLE
addon-docs angular has import and type definition issues

### ISSUE THREAD

**Issue by pfeileon** [storybookjs/storybook#15959]
Because imports from `@storybook/addon-docs/angular` default to any, importing modules leads to `@storybook/addon-docs/dist/ts3.x/frameworks/angular/...`  which seems super ugly. If the ts compiler is in strict mode implicit `any` is not allowed. (The storybook build still works because unfortunately, it seems to ignore custom tsconfig settings in this respect. But it's still super annoying in the IDE.)

Further, some of the interfaces are too restrictive.

```typescript
// @storybook/addon-docs/dist/ts3.9/frameworks/angular/types/types.d.ts

interface Property {
  ...
  optional: boolean; // should not be required
}

interface Class {
  ...
  ngname: string; // should not be required
}
```

### Actual

```typescript
// preview.ts

import { setCompodocJson } from '@storybook/addon-docs/dist/ts3.9/frameworks/angular';
import { CompodocJson } from '@storybook/addon-docs/dist/ts3.9/frameworks/angular/types';
import compodocJson from 'path/to/compodoc/documentation.json';

setCompodocJson(compodocJson as unknown as CompodocJson);
```

### Expected

```typescript
// preview.ts

import { setCompodocJson, CompodocJson } from '@storybook/addon-docs/angular';
import compodocJson from 'path/to/compodoc/documentation.json';

setCompodocJson(compodocJson);
// or at least
setCompodocJson(compodocJson as CompodocJson);
```

### Proposal

Actually, it would be better if `setCompodocJson` wasn't part of the public API at all:

```typescript
// preview.ts

import compodocJson from 'path/to/compodoc/documentation.json';

export const parameters = {
  docs: {
    documentation: compodocJson
  }
}
```

**Comment by ChazUK** [comment]
This proposed solution seems like a better idea to me. Also very frustrating that this information is hidden away in the github docs instead of being on storybooks main site https://github.com/storybookjs/storybook/tree/next/addons/docs/angular

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
