### ISSUE TITLE
Storybook building hangs randomly in github actions with ubuntu-latest.

### ISSUE THREAD

**Issue by ihor-panasiuk95** [storybookjs/storybook#15957]
**Describe the bug**
It caused builds to be in process for more than 1 hour and then it fails by timeout.
It happens randomly meaning that sometimes it gets built sucessfully and quite fast, sometimes it freezes forever.
Locally, everything works fine (storybook building and storybook running).
Screenshot of the Error:
![image](https://user-images.githubusercontent.com/69238797/131639261-41d675d0-d66c-497d-bb33-a26bca4c2a78.png)

**Project technologies:**
Angular 12
Webpack 5
Storybook 6.3.7

**Environment:**
Github actions with ubuntu-latest and Node 12.14

**Update 9.07.2021:** Also reproduces with storybook 6.3.8. It reproduces the way it's described here: https://github.com/webpack/webpack-sources/issues/131

**Update 9.08.2021:** Disabled sourcemaps and it seems like it fixed the issue
![image](https://user-images.githubusercontent.com/69238797/132479536-56e10af9-c03e-43fb-886d-b2b2374af6c0.png)

**Comment by ihor-panasiuk95** [comment]
![image](https://user-images.githubusercontent.com/69238797/132236108-72512f9b-9597-4993-971f-6d22366ae2f6.png)
I got more logs

**Comment by ihor-panasiuk95** [comment]
Update: If I put app build after storybook build, it goes well and without any errors. If storybook build goes after app build (after npm run build) it fails with the described error.
Will try to create a reproduction repo.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
