### ISSUE TITLE
Updating Slot value loses styling

### ISSUE THREAD

**Issue by A143447** [storybookjs/storybook#15963]
**Describe the bug**
Navigate to a component in Storybook that accepts updates in a slot
Updating the Slot value
Note that the styling on the component has disappeared
An example of this can be found here: https://agldesignsystem.digital.agl.com.au/?path=/story/components-button--button

**System**
Environment Info:

  System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz
  Binaries:
    Node: 14.17.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.11 - C:\Program Files\nodejs\yarn.CMD
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 92.0.4515.159
    Edge: Spartan (44.18362.1593.0)
  npmPackages:
    @storybook/addon-a11y: ^6.3.4 => 6.3.6
    @storybook/addon-docs: ^6.3.6 => 6.3.6
    @storybook/addon-essentials: ^6.3.4 => 6.3.6
    @storybook/addon-storyshots: ^6.3.4 => 6.3.6
    @storybook/addon-storyshots-puppeteer: ^6.3.6 => 6.3.6
    @storybook/react: ^6.3.7 => 6.3.7
    @storybook/web-components: ^6.3.7 => 6.3.7

**Additional context**
Using Stencil 2.6.0 to build the components. 
The issue disappears when the page is refreshed
The issue also disappears when the component is set to having the shadow flag set to true (this is not something that we would like to do in my project)

Any assistance would be greatly appreciated

**Comment by FDX-Spence** [comment]
Hi, I have also noticed this. A (bad) workaround is adding a react fragment as a sibling to the content, this seems to preserve the DOM.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
