### ISSUE TITLE
npx sb init (vue) doesn't work

### ISSUE THREAD

**Issue by RaulGF92** [storybookjs/storybook#15964]
With a empty project and a new version of node:
> ` npx sb init`

In the project type section select vue, you let install the program and when you run 

> `npm run storybook`

This error appear:
> `ERR! Error: Cannot find module 'vue/dist/vue.esm.js'`
![image](https://user-images.githubusercontent.com/9384625/131809541-d679181e-152a-4ffd-b81d-2ca927b12ef0.png)

Actually the storybook package is the next:
![image](https://user-images.githubusercontent.com/9384625/131809662-f6445399-f007-4925-86ba-53026cc5bae9.png)

And my node is in the latest version:
![image](https://user-images.githubusercontent.com/9384625/131809995-a1c22d9b-1080-4c4b-b6f6-749f90e1d572.png)

PD: I tried in an Ubuntu SO and in an Windows SO with the same bug.

**Comment by RaulGF92** [comment]
Posible fixed in this PR [#15965](https://github.com/storybookjs/storybook/pull/15965)

**Comment by shilman** [comment]
Fixed in #14624 which was released in https://github.com/storybookjs/storybook/releases/tag/v6.5.0-alpha.7

**Comment by alessandro-aglietti** [comment]
Hi @shilman, using

`npx sb@6.5.0-alpha.7 init` and then `npm run storybook`  using node LTS 16.15.0

I got the same error described by @RaulGF92 :(
