### ISSUE TITLE
Angular selector: Class selector causes error

### ISSUE THREAD

**Issue by mhulse** [storybookjs/storybook#15975]
**Describe the bug**

Storybook throws error when selector contains a class.

**To Reproduce**

Source code:

https://github.com/mhulse/sbtest/blob/master/src/stories/button.component.ts#L4

Demo:

https://6131a583818144003a46d024-gjhfduphnd.chromatic.com/?path=/story/example-button--primary

Error:

> Failed to execute 'setAttribute' on 'Element': 'foo,' is not a valid attribute name.

When I move `.button[foo]` to end of selector list, it doesn't break. If I just use `.button[foo]`, it doesn't break.

**System**

```
Environment Info:

  System:
    OS: macOS 11.5.2
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
  Binaries:
    Node: 16.3.0 - ~/.nvm/versions/node/v16.3.0/bin/node
    Yarn: 3.0.1 - ~/.nvm/versions/node/v16.3.0/bin/yarn
    npm: 7.21.1 - ~/.nvm/versions/node/v16.3.0/bin/npm
  Browsers:
    Chrome: 93.0.4577.63
    Edge: 92.0.902.84
    Firefox: 91.0.1
    Safari: 14.1.2
  npmPackages:
    @storybook/addon-actions: ^6.4.0-alpha.33 => 6.4.0-alpha.33
    @storybook/addon-docs: ^6.4.0-alpha.33 => 6.4.0-alpha.33
    @storybook/addon-essentials: ^6.4.0-alpha.33 => 6.4.0-alpha.33
    @storybook/addon-links: ^6.4.0-alpha.33 => 6.4.0-alpha.33
    @storybook/angular: ^6.4.0-alpha.33 => 6.4.0-alpha.33
```

**Comment by shilman** [comment]
Crikey!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-alpha.38 containing PR #15976 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```
