### ISSUE TITLE
There seems to be a problem with addon-docs Canvas.

### ISSUE THREAD

**Issue by eungyeole** [storybookjs/storybook#15974]
**Describe the bug**
It's not a serious bug, but I got annoyed and reported it.
This issue occurred when the canvas was used in safari.

| Safari | Chrome |
|----------|----------|
| ![image](https://user-images.githubusercontent.com/66717787/131939603-a19fc25b-4aab-4682-a8f9-37d7fbe4744b.png) | ![image](https://user-images.githubusercontent.com/66717787/131939809-5edac710-1271-49d3-b036-61084c42ad94.png)

As you can see in the picture above, Safri's Hide code or Copy button seems to be slightly out of position because the margin is not initialized.

So I added the `margin: 0` attribute and found out that the problem was solved.
I want you to fix it 😂. 
Or I'll send you a PR 😡.

![image](https://user-images.githubusercontent.com/66717787/131940084-2c2ab105-183a-4760-b0e4-003f55db269c.png)

**System**
```shell
Environment Info:

  System:
    OS: macOS 11.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 16.2.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.20.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 93.0.4577.63
    Safari: 14.1.1
  npmGlobalPackages:
    @storybook/cli: 6.3.2
```

**Comment by eungyeole** [comment]
Other than this, there seems to be a lot of UI problems that occur because the style is not initialized.

**Comment by shilman** [comment]
Whoopee!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-alpha.35 containing PR #15981 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```
