### ISSUE TITLE
[React] Returning a variable instead JSX breaks Storybooks

### ISSUE THREAD

**Issue by RodrigoTomeES** [storybookjs/storybook#16014]
## Describe the bug
The bug is simple but very frustrating. When in react (I haven't tested on other enviroments) you return a variable instead of JSX the default values and description don't appear in Storybook.

## To Reproduce
To reproduce it, you just have to return a variable instead of JSX code.

### System:

- OS: Windows 10 10.0.19043
- CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor

### Binaries:

- Node: 12.22.1 - C:\Program Files\nodejs\node.EXE
- Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD      
- npm: 6.14.12 - C:\Program Files\nodejs\npm.CMD

### Browsers:

- Edge: Spartan (44.19041.1023.0), Chromium (93.0.961.44)        

### npmPackages:

- @storybook/addon-actions: ^6.3.7 => 6.3.7
- @storybook/addon-docs: ^6.3.7 => 6.3.7
- @storybook/addon-essentials: ^6.3.7 => 6.3.7
- @storybook/addon-links: ^6.3.7 => 6.3.7
- @storybook/addons: ^6.3.7 => 6.3.7
- @storybook/builder-webpack5: ^6.4.0-alpha.33 => 6.4.0-alpha.33 
- @storybook/manager-webpack5: ^6.4.0-alpha.33 => 6.4.0-alpha.33 
- @storybook/preset-scss: ^1.0.3 => 1.0.3
- @storybook/react: ^6.3.7 => 6.3.7
- @storybook/theming: ^6.3.7 => 6.3.7

### Returning a variable:
![imagen](https://user-images.githubusercontent.com/13077343/132944375-e35d01eb-6a52-478a-accd-0d573222badb.png)
![imagen-2](https://user-images.githubusercontent.com/13077343/132944379-cd851f66-ad11-45d4-9c20-b34297e4c4ec.png)

### Returning JSX:
![imagen-1](https://user-images.githubusercontent.com/13077343/132944393-75c1a578-764c-43b1-970a-a05e23e263f6.png)
![imagen](https://user-images.githubusercontent.com/13077343/132944394-f02c0e77-b59a-4ecc-b851-5e50bbf32f8e.png)

**Comment by shilman** [comment]
Is this using typescript types or proptypes?

**Comment by RodrigoTomeES** [comment]
> 
> 
> Is this using typescript types or proptypes?

This is using proptypes

**Comment by RodrigoTomeES** [comment]
Hi,

I have an update about this issue. This error also occurs when you return an expression like `isActive? children: null` instead of JSX. So I think that it only works if you return JSX.

**Comment by RodrigoTomeES** [comment]
The problem still continues

**Comment by RodrigoTomeES** [comment]
Hi,

Any update about this?

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
