### ISSUE TITLE
builder-webpack5 always emits stats on error with build-storybook

### ISSUE THREAD

**Issue by develra** [storybookjs/storybook#16029]
**Describe the bug**
When using builder-webpack5 with build-storybook, if the build encounter type errors it correctly fails out with the type errors, but also prints out the entire JSONified stats block. This is annoying on CI builds as it adds many thousands of lines to the log for no reason/expected behavior.

**To Reproduce**
https://github.com/develra/webpack5-storybook-stats-emit
Steps:
yarn && yarn build-storybook

**System**
```Environment Info:

  System:
    OS: Linux 5.10 Debian GNU/Linux rodete 11 (rodete)
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  Binaries:
    Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
    Yarn: 3.0.2 - ~/.nvm/versions/node/v14.16.0/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v14.16.0/bin/npm
  Browsers:
    Chrome: 93.0.4577.63
    Firefox: 78.13.0esr
  npmPackages:
    @storybook/addon-actions: ^6.4.0-alpha.34 => 6.4.0-alpha.34 
    @storybook/addon-docs: ^6.4.0-alpha.34 => 6.4.0-alpha.34 
    @storybook/addon-essentials: ^6.4.0-alpha.34 => 6.4.0-alpha.34 
    @storybook/addon-links: ^6.4.0-alpha.34 => 6.4.0-alpha.34 
    @storybook/builder-webpack5: ^6.3.8 => 6.3.8 
    @storybook/manager-webpack5: ^6.3.8 => 6.3.8 
    @storybook/react: ^6.4.0-alpha.34 => 6.4.0-alpha.34 
```

**Additional context**
It would be nice to have the ability to enable the stats block via an option.

**Comment by develra** [comment]
@shilman - I have some time today to take a crack at a PR if y'all accept outside PRs. Let me know.

**Comment by shilman** [comment]
We love PRs! 🙏


We've documented [how to contribute](https://storybook.js.org/docs/react/contribute/code) and there's also a `#contributing` channel on the [Storybook discord](https://discord.gg/storybook) if you have questions.

**Comment by develra** [comment]
https://github.com/storybookjs/storybook/pull/16132
