### ISSUE TITLE
MDX: Custom <Story /> component does not render in canvas

### ISSUE THREAD

**Issue by mattgreenfield** [storybookjs/storybook#16026]
**Describe the bug**
I am using a custom <Story /> component to render stories written in MDX. It works on the 'Docs' tab but not the 'Canvas' tab.

**To Reproduce**
Example repo: https://github.com/mattgreenfield/storybook-mdx-issue

- Create a custom Story component and point to it in `preview.js`
```
 docs: {
    components: {
      Story: HTMLStory,
    },
  }
```
- Use that `<Story />` component in a `.mdx` file, wrap it in a `<Canvas />`
- Observe it rendering correctly in the 'Docs' tab of storbook
- Observe how nothing renders in the 'Canvas' tab

<img width="1227" alt="Screenshot 2021-09-13 at 12 01 33" src="https://user-images.githubusercontent.com/7290654/133073703-be932db8-fc01-4c71-ac65-e8518ad40fc7.png">
<img width="1229" alt="Screenshot 2021-09-13 at 12 01 54" src="https://user-images.githubusercontent.com/7290654/133073709-7ecb03ff-2d55-4694-aa56-7cded27cc175.png">

**System**

Environment Info:

  System:
    OS: macOS 11.3.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 14.17.5 - /usr/local/bin/node
    Yarn: 3.0.2 - /usr/local/bin/yarn
    npm: 6.14.14 - /usr/local/bin/npm
  Browsers:
    Edge: 92.0.902.84
    Safari: 14.1
  npmPackages:
    @storybook/addon-actions: ^6.4.0-alpha.34 => 6.4.0-alpha.34 
    @storybook/addon-docs: ^6.3.8 => 6.3.8 
    @storybook/addon-essentials: ^6.4.0-alpha.34 => 6.4.0-alpha.34 
    @storybook/addon-links: ^6.4.0-alpha.34 => 6.4.0-alpha.34 
    @storybook/html: ^6.4.0-alpha.34 => 6.4.0-alpha.34 

**Additional context**
It could be that this is component mis-use rather than a bug? Here's my use case:
I have a folder full of HTML snippets, each one containing a single component in HTML.
I want to import and render each one as a story and also in an MDX file.
I've managed to get this working in the 'Docs' tab using a custom `<Story /> component that imports and renders the HTML file but it's a shame it doesn't also give me the canvas view (so that I can see each story on its own).

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
