### ISSUE TITLE
Ability to escape slashes in story names

### ISSUE THREAD

**Issue by tgelu** [storybookjs/storybook#16038]
Seems like the assumption about `/` being an inescapable hierarchy separator [doesn't quite hold](https://github.com/storybookjs/storybook/issues/9761). The only alternative one can opt for is to use a homoglyph instead of `/`. That is ugly and makes the urls even uglier.

In any case, I don't want to suggest we should go back to configuring the separator. I only want to suggest a way to escape the `/`, like one would in a regex, for example `Components\/Button`. Or to change the type of `title` from `string` with a special convention to `Array<string>` which seems to describe the intent more precisely and clearly.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if this is still relevant in SB 7.x.

**Comment by SkReD** [comment]
Figured out that combination of replacing `/` with `##` for example and adding manager config with `renderLabel` do the trick
```ts
import { addons } from '@storybook/manager-api';

addons.setConfig({
sidebar: {
    showRoots: false,
    renderLabel(item) {
        return item.name.replace(/##/g, '/')
    }
}
});
```
