### ISSUE TITLE
Incorrect code snippet within Source in DocsPage for Vue2 named slots

### ISSUE THREAD

**Issue by adrianpdm** [storybookjs/storybook#16030]
**Describe the bug**
Named slots defined in stories are not rendered as snippet within `Source` in `DocsPage`.

**To Reproduce**
1. Fork this repository
2. Open project in IDE
3. Make changes to `examples/vue-cli/src/button/Button.vue`
```diff
  <template>
    <div class="button" :class="`size-${size}`">
      <!-- @slot Button content, e.g. label text -->
-      <slot></slot>
+      <slot name="label"></slot>
    </div>
  </template>
```
4. Make changes to `examples/vue-cli/src/button/Button.stories.ts`
```diff
  export const ButtonWithProps: Story = (args, { argTypes }) => ({
    components: { Button },
-    template: '<Button :size="size">Button text</Button>',
+    template: '<Button :size="size"><template #label>Button text</template></Button>',
    props: Object.keys(argTypes),
  });
```

5. Run storybook
```
cd examples/vue-cli
yarn storybook
```

**Expected Result**
Code snippet within `Source` in `DocsPage` matches with code written in `ButtonWithProps#template`.

**Actual Result**
Code snippet only shows root element, without corresponding `<template #label/>` and its inner content.

![image](https://user-images.githubusercontent.com/20709202/133120657-1cb08431-d094-4eb5-8ae8-69f6bd54a3dd.png)

**System**
```
System:
    OS: Linux 5.4 elementary OS 5.1.7 Hera
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
  Binaries:
    Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
    Yarn: 3.0.0-git.20210727.hash-3cbbb672 - ~/.nvm/versions/node/v14.16.0/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v14.16.0/bin/npm
  Browsers:
    Chrome: 91.0.4472.77
```

**Additional context**
None

**Comment by adrianpdm** [comment]
It seems that since Vue@^2.6.0, `<template />` with `v-slot` or `#` directive is treated differently, of which it doesnt exist as VNode under `children` or `componentOptions.children`. Resulting in incorrect value returned by `vnodeToString` .

https://github.com/storybookjs/storybook/blob/68e638a09eaad8e543dc2640ebd40894371266b1/addons/docs/src/frameworks/vue/sourceDecorator.ts#L93-L95

https://github.com/storybookjs/storybook/blob/68e638a09eaad8e543dc2640ebd40894371266b1/addons/docs/src/frameworks/vue/sourceDecorator.ts#L119-L122

This can be solved by using the old `<template slot="" slot-scope="" />`. If that was expected, it'd be nice for Storybook to mention that caveats in the docs.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
