### ISSUE TITLE
yarn build-storybook 95% emitting fork-ts-checker-webpack-plugin

### ISSUE THREAD

**Issue by takeaways** [storybookjs/storybook#16040]
**Describe the bug**
when I tried to build my storybook on react project, It always stop 95% progress with "95% emitting fork-ts-checker-webpack-plugin"

![image](https://user-images.githubusercontent.com/52693107/133246181-0c64fd69-3991-49d6-9938-369ba8bbdf22.png)

**Comment by shilman** [comment]
closing as dupe to #12311
