### ISSUE TITLE
Storybook build is not working after upgrading lit element to 2.0.0-rc.4

### ISSUE THREAD

**Issue by martinagrbic** [storybookjs/storybook#16062]
The storybook build is breaking with error message 
```
ERR! Module not found: Error: Package path ./directives/style-map is not exported from package /node_modules/lit-html (see exports field in /node_modules/lit-html/package.json)
ERR! ModuleNotFoundError: Module not found: Error: Package path ./directives/style-map is not exported from package node_modules/lit-html (see exports field in /node_modules/lit-html/package.json)
ERR!     at /node_modules/webpack/lib/Compilation.js:1773:28
ERR!     at node_modules/webpack/lib/NormalModuleFactory.js:814:13
ERR!     at eval (eval at create (/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
ERR!     at /node_modules/webpack/lib/NormalModuleFactory.js:286:22
ERR!     at eval (eval at create (/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
ERR!     at /node_modules/webpack/lib/NormalModuleFactory.js:442:22
ERR!     at /node_modules/webpack/lib/NormalModuleFactory.js:124:11
ERR!     at //node_modules/webpack/lib/NormalModuleFactory.js:676:25
ERR!     at /node_modules/webpack/lib/NormalModuleFactory.js:885:8
ERR!     at /node_modules/webpack/lib/NormalModuleFactory.js:1005:5
ERR!     at /node_modules/neo-async/async.js:6883:13
ERR!     at /node_modules/webpack/lib/NormalModuleFactory.js:988:45
ERR!     at finishWithoutResolve (/node_modules/enhanced-resolve/lib/Resolver.js:296:11)
ERR!     at /node_modules/enhanced-resolve/lib/Resolver.js:362:15
ERR!     at /node_modules/enhanced-resolve/lib/Resolver.js:410:5
ERR!     at eval (eval at create (/node_modules/enhanced-resolve/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
error Command failed with exit code 1.
```

**To Reproduce**
upgrade lit version to 2.0.0-rc.4 run storybook build.

**System**

Environment Info:

  System:
    OS: Linux 5.11 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
  Binaries:
    Node: 14.17.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.13 - /usr/local/bin/npm
  Browsers:
    Chrome: 92.0.4515.131
    Firefox: 91.0.2
  npmPackages:
    @storybook/addon-a11y: ^6.3 => 6.3.8 
    @storybook/addon-actions: ^6.3 => 6.3.8 
    @storybook/addon-controls: ^6.3 => 6.3.8 
    @storybook/addon-docs: ^6.3 => 6.3.8 
    @storybook/addon-essentials: ^6.3 => 6.3.8 
    @storybook/addon-links: ^6.3 => 6.3.8 
    @storybook/builder-webpack5: ^6.3 => 6.3.8 
    @storybook/manager-webpack5: ^6.3 => 6.3.8 
    @storybook/web-components: ^6.3 => 6.3.8

**Comment by gaetanmaisse** [comment]
@martinagrbic I wasn't able to reproduce any issue with Lit `2.0.0-rc.4`, are you able to create a repro based on https://stackblitz.com/github/storybookjs/repro-templates/tree/main/web_components_lit2?file=package.json&preset=node?

**Comment by andrewlevada** [comment]
This error occurs because from lit 2.0.0-rc.4 `./directives/style-map` has to be imported as `./directives/style-map.js` due to [this change](https://github.com/lit/lit/issues/1986).

**Comment by Th3S4mur41** [comment]
I'm still facing the issue after the upgrade
Node: 16.13.0
NPM: 8.1.0
NPM packages:

"@babel/core": "^7.16.0",
"@storybook/addon-actions": "^6.4.0-rc.8",
"@storybook/addon-docs": "^6.4.0-rc.8",
"@storybook/addon-essentials": "^6.4.0-rc.8",
"@storybook/addon-links": "^6.4.0-rc.8",
"@storybook/builder-webpack5": "^6.4.0-rc.8",
"@storybook/manager-webpack5": "^6.4.0-rc.8",
"@storybook/web-components": "^6.4.0-rc.8",
"babel-loader": "^8.2.3",
"lit": "^2.0.2",
"lit-html": "^2.0.2"

```
$ npm -w=storybook run storybook

> storybook@0.0.1-alpha.1 storybook
> start-storybook -p 6006

info @storybook/web-components v6.4.0-rc.8
info
info => Loading presets
info => Using implicit CSS loaders
info => Using default Webpack5 setup
1% setup initializeinfo => Using prebuilt manager
<i> [webpack-dev-middleware] wait until bundle finished
16% building 2/16 entries 3292/3400 dependencies 439/682 modules[BABEL] Note: The code generator has deoptimised the styling of ...\packages\storybook\node_modules\react-dom\cjs\react-dom.development.js as it exceeds the max of 500KB.
99% done plugins webpack-hot-middlewarewebpack built preview 6c3a27cb9936cf6b6fda in 15462ms
ModuleNotFoundError: Module not found: Error: Package path ./directives/style-map is not exported from package ...\packages\storybook\node_modules\lit-html (see exports field in ...\packages\storybook\node_modules\lit-html\package.json)

```

**Comment by shilman** [comment]
@Th3S4mur41 can you provide a reproduction we can look at?

**Comment by Th3S4mur41** [comment]
Yep, I manage to make a skeleton of the project where I still face the issue:
https://github.com/Th3S4mur41/storybook-lit-workspace-bug/runs/4333400192?check_suite_focus=true

**Comment by gaetanmaisse** [comment]
Ok, I tested it locally and it looks like the issue is now coming from `@storybook/builder-webpack5`. I will try to investigate a bit but I'm not a webpack expert so I can't promise anything

**Comment by shilman** [comment]
@gaetanmaisse lmk if you want to pair on this

**Comment by ThibaudAV** [comment]
It's my turn to have this one 😁 . I'm with Angular so Webpack 5 is required and we also want to have lit 2 dependency
