### ISSUE TITLE
Security Vulnerabilities

### ISSUE THREAD

**Issue by cimbis** [storybookjs/storybook#16063]
Hi there!

`npm audit` reports a ton of vulnerabilities with `@storybook/*` packages.

This is already mentioned in #15173 #15174 #15175 .

By judging https://github.com/storybookjs/storybook/issues/15174#issuecomment-885783329 `glob-parent` issue will be solved on next minor version release.

However, others related to mdx parsing still would persist.

One possible solution, at least to my understanding, would be to bump mdx-js/mdx version https://github.com/mdx-js/mdx/issues/1041, which not only would fix some of the issues but also add few more features for those writing mdx docs.

**Comment by shilman** [comment]
Given that https://github.com/mdx-js/mdx/issues/1041 is a major version bump, I think upgrading would be a breaking change that would necessitate a major version bump in Storybook as well.

**Comment by Jackques** [comment]
I tried 6.5.0-alpha.4 but it seems to use the same packages which cause issues. Anyone know when or if this will be fixed?

**Comment by asvetlenko** [comment]
Hi there!

We have some **vulnerabilities** issues related with **storybook**. 

<img width="1243" alt="image" src="https://user-images.githubusercontent.com/9693052/153560794-719a4cc7-a368-4159-8691-dbcd2cf2d9c7.png">

Other one:
<img width="1256" alt="image" src="https://user-images.githubusercontent.com/9693052/153560899-50edacad-15ab-4d61-b5b5-9303d5d5314c.png">

Could your please update your packages dependencies ?

**Comment by vish01** [comment]
Is there any update on this? I'm seeing this security issue when I run `npm run audit` as well.

**Comment by ndelangen** [comment]
Fixed in 7.0 where we've updated to MDX2
