### ISSUE TITLE
`toImportFn` doesn't work with `..` paths

### ISSUE THREAD

**Issue by tmeasday** [storybookjs/storybook#16069]

**Comment by IanVS** [comment]
I believe this issue is causing the error I'm seeing when enabling `storyStoreV7`.

```
TypeError: Cannot read properties of undefined (reading 'default')
    at processCSFFile (processCSFFile.js:43)
    at StoryStore.memoizerific [as processCSFFileWithCache] (memoizerific.js:170)
    at StoryStore.js:261
```

_This comment added to help others search if they have this same error_

**Comment by tmeasday** [comment]
Correct, thanks @IanVS

**Comment by shilman** [comment]
Crikey!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-alpha.38 containing PR #16078 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```
