### ISSUE TITLE
Fix dotenv resolution

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#16067]
There's a bug in a new NextJS project where `assert` tries to access `process.env` and fails due to #15925

Proposed fix:

- Read in dotenv
- Merge with `STORYBOOK_x`
- Define with the webpack define plugin
- Define `process.env` as well for compatibility with NextJS

Workaround: create an empty `.env` file to get NextJS unstuck

**Comment by shilman** [comment]
w00t!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-alpha.41 containing PR #16105 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by kylemh** [comment]
FWIW, updated to latest beta with latest Next and my Storybook won't build!

https://github.com/OperationCode/front-end/pull/1435

**Comment by shilman** [comment]
@kylemh haven't had a chance to check out your storybook but i just created a fresh next app and `npx sb@next init --builder webpack5` on it and don't see the problem FWIW

**Comment by anilanar** [comment]
@shilman I think this PR broke the case when `process.env` is used in an arrow function such as:

```
const getFoo = () => process.env.FOO
```

which becomes

```
const getFoo = () => { FOO: "\"whatever\"" }.FOO
```

which is invalid syntax.

Also I'm not sure about how values are double stringified, but that's another issue.

**Comment by kylemh** [comment]
I've given this another go and just want to outline my steps:
- Use `npx sb upgrade --prerelease`
- Use yarn's resolutions to force `webpack@5`
- Installed the new builders (`@storybook/builder-webpack5@next` & `@storybook/manager-webpack5@next`)
- Added `core: { builder: 'webpack5' }` to my config in `.storybook/main.js`

Dev server seems to build, but the runtime has an error saying that "process is undefined" (among other errors)

<img width="484" alt="Screen Shot 2021-10-04 at 11 52 54 PM" src="https://user-images.githubusercontent.com/9523719/135957451-8540285c-4f84-49f6-b961-773168064a31.png">

**Comment by shilman** [comment]
@kylemh does it change anything if instead of using yarn resolutions, you install `webpack@5` as a project dependency? I don't see why it would, but I'm at a loss for why you're still seeing this error.

One idea, can you do:

```
yarn why @storybook/react 
yarn why @storybook/core-server
```

And see if there are any old versions lying around?

**Comment by kylemh** [comment]
![Screen Shot 2021-10-05 at 3 13 39 PM](https://user-images.githubusercontent.com/9523719/136087994-9a51ee11-f1a1-48f7-a2b9-d67d0cdd856b.png)

Nothing.

And just in case...
![Screen Shot 2021-10-05 at 3 14 20 PM](https://user-images.githubusercontent.com/9523719/136088098-7d1ae3ab-a2c1-4dbd-a54d-332a0be561b5.png)

I redid the work in a smaller PR, if it helps: https://github.com/OperationCode/front-end/pull/1507

**Comment by shilman** [comment]
Great Caesar's ghost!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-rc.4 containing PR #16725 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by tylerjlawson** [comment]
@shilman is it possible that this issue was reintroduced with v6.4.10? I am getting the process is not defined error on 6.4.10 when I was not getting it on 6.4.9. 

![image](https://user-images.githubusercontent.com/26290074/148808037-b7ec39fc-4e27-4722-bad5-1eced6ba0cc6.png)

This is a chunk I have had with each SB version to attempt to resolve this issue. It worked before but no longer works:

```js
webpackFinal: (config) => {
  config.plugins = [
      ...config.plugins,
      new webpack.ProvidePlugin({
        process: 'process/browser',
      }),
    ];

  return config;
}

**Comment by shilman** [comment]
@tylerjlawson do you have a reproduction i can look at?

**Comment by tylerjlawson** [comment]
@shilman Here is a reproduction: https://github.com/tylerjlawson/sb-issue-repro

I assumed the issue was simpler than it is, but the issue I am having seems to occur specifically when the `manager.js` file imports a file that references `process`. You should be able to just install and run storybook to see the issue in the browser console. Let me know if that still doesn't throw the error.

**Comment by shilman** [comment]
Zoinks!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-alpha.15 containing PR #17213 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Good golly!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.13 containing PR #17213 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```

**Comment by curtvict** [comment]
Egad!! I just recently started getting this error in my production builds as well (running v6.5.9):

```
main.2a50b8f3.iframe.bundle.js:1 Uncaught ReferenceError: process is not defined
    at ./.storybook/preview.js-generated-config-entry.js (main.2a50b8f3.iframe.bundle.js:1:232565)
    at __webpack_require__ (runtime~main.d50f313e.iframe.bundle.js:1:387)
    at __webpack_exec__ (main.2a50b8f3.iframe.bundle.js:1:668989)
    at main.2a50b8f3.iframe.bundle.js:1:670503
    at __webpack_require__.O (runtime~main.d50f313e.iframe.bundle.js:1:1048)
    at main.2a50b8f3.iframe.bundle.js:1:670646
    at webpackJsonpCallback (runtime~main.d50f313e.iframe.bundle.js:1:6536)
    at main.2a50b8f3.iframe.bundle.js:1:59
```

**Comment by curtvict** [comment]
Ah, found out this was my own dang fault. In a previous commit in my project I had refactored calls like

```js
const config = {
  whatever: process.env.SOMETHING,
}
```

into 

```js
import { SOMETHING } = process.env;

const config {
  whatever: SOMETHING,
}
```

Reverting that fixed this error for me. Thanks for coming to my TED talk.

**Comment by punkpeye** [comment]
How to disable dotenv loading?

It keeps loading my `.env.production`, but I don't want storybook to use it.
