### ISSUE TITLE
Extend class from the lib: inputs\outputs does not work correctly

### ISSUE THREAD

**Issue by GupCa** [storybookjs/storybook#16068]
**Describe the bug**
When using storybook with angular lib, and extending testing component with classes from the library, inputs are undefined onInit hook and actions are not emitting.

**To Reproduce**
Go to https://gupca.github.io/storybook-lib-example/ and check the console after updating grandParentInput:
![image](https://user-images.githubusercontent.com/27829885/133414566-b35f75c8-c0a0-4a2b-8ce2-ec3bf1cf0dd4.png)
The input of grandParent is undefined on the init hook and no actions are emitted, instead, there is a console log error.
Source code: https://github.com/GupCa/storybook-lib-example.

**System**
  System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i5-1035G4 CPU @ 1.10GHz 
  Binaries:
    Node: 14.15.5 - C:\Program Files\nodejs\node.EXE       
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1023.0), Chromium (93.0.961.47)
  npmPackages:
    @storybook/addon-actions: ^6.4.0-alpha.34 => 6.4.0-alpha.35
    @storybook/addon-essentials: ^6.4.0-alpha.34 => 6.4.0-alpha.35
    @storybook/addon-links: ^6.4.0-alpha.34 => 6.4.0-alpha.35
    @storybook/angular: ^6.4.0-alpha.34 => 6.4.0-alpha.35

**Additional context**
This issue appeared to happen after Angular 10 -> 11 migration with storybook 6.1 -> 6.2-3-4 upgrade. Currently, I need to duplicate all of the inputs\outputs of the grand parent class in the child to make everything work, but this is just a workaround.

**Comment by willyboy** [comment]
We're seeing the same issue
