### ISSUE TITLE
Webpack5: Use filesystem cache

### ISSUE THREAD

**Issue by literalpie** [storybookjs/storybook#16072]
**Is your feature request related to a problem? Please describe**
Webpack 5 allows a "filesystem cache" option. Enabling it in both Webpack and manager webpack configs cuts my initial build time in half. (manager: 25s to 9s, preview: 60s to 24s) (I'm not using storybook manager cache because of #15993 but maybe this could replace the storybook manager cache?)
While it's not terrible to do this myself, and I could easily make an addon that adds this config, I don't know of any downsides of enabling this by default in the webpack5 storybook builders.

**Describe the solution you'd like**
This is the config I add. I think it could be added to the default webpack5 config.
```
exports.webpack = (config) => {
  config.cache = {
    type: 'filesystem'
  }

  return config;
};

exports.managerWebpack = (config) => {
  config.cache = {
    type: 'filesystem'
  }

  return config;
}
```

**Describe alternatives you've considered**
Any alternative solutions or features you've considered.

**Are you able to assist to bring the feature to reality?**
Yes, if people think it's a good idea, and don't know of any down sides, I'd be willing to contribute.

**Additional context**
* [Webpack cache docs](https://webpack.js.org/configuration/cache/)
* Angular has had this as an opt-in feature ([initial PR](https://github.com/angular/angular-cli/pull/20756)), but is [planning to make it default](https://github.com/angular/angular-cli/issues/21545).
* I think the biggest risk of enabling this is the possibility that stale caches will be used and prevent code from updating. Angular creates a cache from webpack config options and other parameters. I don't know if this would be necessary for storybook or not.

**Comment by shilman** [comment]
@tmeasday @bebraw how does this align with your work on code splitting?

**Comment by bebraw** [comment]
@shilman It's orthogonal to the work. I would add the config first behind a feature flag as there's a nice speedup but also some risk (stale caches) as mentioned by the OP.

**Comment by tmeasday** [comment]
I think we could/should definitely add this behind a flag in 6.4, with a view to making it the default for WP5 in 6.5, once we ironed out the kinks. WDYT @shilman? Where would the flag live?

**Comment by shilman** [comment]
> Where would the flag live?

@tmeasday It depends on whether the flag was for configuration or for migration.

If it's for migration, i.e. we plan to make it opt-in in 6.4 and eventually the default with no way to opt out, I'd say we could have a feature flag `features.webpack5FSCache` or so.


If the plan is to make it configurable in the future, maybe I'd configure it like:

```js
export const core = {
  builder: {
    name: 'webpack5',
    options: { fsCache: true }
  }
}
```

WDYT?

**Comment by tmeasday** [comment]
I was thinking it'd be be configurable but we'd change the default to true in the future, so I prefer the second option.

**Comment by tmeasday** [comment]
@literalpie's PR for this seems great. WDYT @shilman?

**Comment by shilman** [comment]
Olé!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-rc.2 containing PR #16219 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
