### ISSUE TITLE
Addon-docs: wrong component is shown when switching stories in docs mode (6.4-alpha)

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#16082]
**Describe the bug**

When switching stories, it seems like the main story in docs mode is cached from the previous story until you switch to canvas, and then the issue happens again with a different component:
![sb-regression](https://user-images.githubusercontent.com/1671563/133610269-a9c9ac87-deab-42df-81c0-fae9296be455.gif)

**To Reproduce**

1 - Run storybook locally in `next` with `yarn start`
2 - Follow the steps from the gif

**Additional context**
1 - This does not seem to happen in deployed storybooks. I tried out in [next](https://next--storybookjs.netlify.app/official-storybook/?path=/docs/addons-a11y-button--default) and the issue did not happen.
2 - I believe this might be related to the on-demand store work @shilman @tmeasday

**Comment by yannbf** [comment]
> @yannbf Not seeing this on my local machine. Can you pull the latest & bootstrap & try again?

I updated to alpha 38 and the problem is fixed! I also tried in my personal project which had the same issue when I tested alpha 34 and the problem went away.

Thanks!

**Comment by tmeasday** [comment]
This was a bug we fixed @shilman -- the thing with the `useStory` hook in docs.
