### ISSUE TITLE
MUI5 and storybook mixes the `theme` if rendering Docs - which cause an exception

### ISSUE THREAD

**Issue by uwinkler** [storybookjs/storybook#16099]
**Describe the bug**
Material 5 (https://mui.com/core/) uses emotion to style its components. This clashes with storybook and the storybook `theme` pollutes and wipes out the  MUI theme.

**To Reproduce**

Checkout https://github.com/uwinkler/storybook-problem
Execute `yarn && yarn run storybook`
Go to a 'Doc' page 

See screenshot

**System**
  System:
    OS: macOS 11.5.2
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
  Binaries:
    Node: 16.3.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.15.1 - /usr/local/bin/npm
  Browsers:
    Firefox: 91.0
    Safari: 14.1.2
  npmPackages:
    @storybook/addon-actions: ^6.3.8 => 6.3.8
    @storybook/addon-essentials: ^6.3.8 => 6.3.8
    @storybook/addon-links: ^6.3.8 => 6.3.8
    @storybook/node-logger: ^6.3.8 => 6.3.8
    @storybook/preset-create-react-app: ^3.2.0 => 3.2.0
    @storybook/react: ^6.3.8 => 6.3.8
**Additional context**

Add any other context about the problem here

.
<img width="756" alt="Screenshot 2021-09-18 at 14 51 35" src="https://user-images.githubusercontent.com/582533/133889417-ace4b915-c010-4db6-9057-a7c9785fbbb1.png">

**Comment by shilman** [comment]
There are a few different possible workarounds:

1) Disable docs https://storybook.js.org/docs/react/essentials/introduction#disabling-addons

2) Render docs in iframe mode (`docs: { inlineStories: false }`): https://storybook.js.org/docs/react/writing-docs/doc-blocks#inline-rendering

3) Try out a fix in 6.4:

```
npx sb@next upgrade --prerelease
```

Then in `.storybook/main.js` set:

```js
module.exports = {
  features: { modernInlineRendering: true }
};
```

**Comment by uwinkler** [comment]
Thank you @shilman for the quick response and for your help. 

Unfortunately disabling docs is not an option for us, as most of our documentation is written in `mdx` files.

I tried option 2) and 3) but none of them did the trick :/

Any other options?

**Comment by shilman** [comment]
Do you a have a reproduction repo you can share? If not, can you create one? See [how to create a repro](https://storybook.js.org/docs/react/contribute/how-to-reproduce).

**Comment by uwinkler** [comment]
I will go through this process. 

However, you may have a look at https://github.com/uwinkler/storybook-problem
This is a minimal storybook project that showcases the problem.

**Comment by uwinkler** [comment]
The repro is here: https://github.com/uwinkler/storybook-16099-issue

You can reproduce the problem yourself:

- Try to add material-ui: yarn add @mui/material @emotion/react @emotion/styled
- Add a <Button/> to the `introduction.stories.mdx` file

This should trigger some problems

Thxs again for your help. This is much appreciated.

**Comment by shilman** [comment]
Thanks @uwinkler--I'll take a look today 🙏

**Comment by maxquinn** [comment]
Also experiencing this issue. None of the suggested workarounds fix the issue for me.

**Comment by shilman** [comment]
Egads!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-beta.31 containing PR #16613 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by ar7casper** [comment]
> Invalid build with vite.
> 
> Does anyone solve this problem with ` "storybook-builder-vite": "^0.1.3"` ?

Did you manage to find a solution?
