### ISSUE TITLE
Security warning on react-dev-utils that depends on immer

### ISSUE THREAD

**Issue by erbunao** [storybookjs/storybook#16093]
**Describe the bug**

I noticed from our pipeline that a critical vulnerability has been raised stemming from `immer` not on the latest version `9.0.6`. `immer` is a dependency of `react-dev-utils`.

![Alerts · wrapbookapp 2021-09-17 at 11 34 21 AM](https://user-images.githubusercontent.com/4653624/133815469-e63dc4ea-fdfe-471e-9434-fda415c4c3ed.jpg)

At the moment, `react-dev-utils` is being updated to use `immer`'s latest version.https://github.com/facebook/create-react-app/pull/11364.

Happy to upgrade this once the PR above has been merged.

**Comment by snjnlsn** [comment]
That PR has been merged, storybook can now depend on 11.0.4 to resolve this security vulnerability

**Comment by shilman** [comment]
Crikey!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-beta.2 containing PR #16196 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by hawkticehurst** [comment]
I'm unfortunately still getting a critical severity warning despite having `6.4.0-beta.4` installed.

<img width="866" alt="Screen Shot 2021-10-04 at 6 45 39 PM" src="https://user-images.githubusercontent.com/39639992/135947447-8878b0ac-4811-4d17-85eb-9c73ae678433.png">

After some snooping, it looks like despite having bumped `immer` to the correct version in [this PR](https://github.com/facebook/create-react-app/pull/11364), `react-dev-utils` has not yet actually published this change in a new package version (i.e. `v11.0.4` is the latest release, but seemingly does not contain the security fix).

I would suggest potentially reopening this issue and tracking the aforementioned PR until a published change comes down the line.

**Comment by simonsmith** [comment]
Are you planning to release a new version of `5.x` to address this?

**Comment by shilman** [comment]
@simonsmith No, Storybook 5.3 is almost 2 years old now and I'd strongly prefer if people upgrade to the latest

https://storybook.js.org/blog/storybook-6-migration-guide/

**Comment by mukundkatpatal** [comment]
Any update on this guys?

**Comment by erbunao** [comment]
Is there a temporary workaround to use the version `"react-dev-utils": "12.0.0-next.47"`?

**Comment by fernandopasik** [comment]
you could try yarn resolutions in `package.json`

```
{
  "react-dev-utils": "^12.0.0-next.47"
}
```

**Comment by jonsalvas** [comment]
got it working this way: https://github.com/facebook/create-react-app/issues/11660#issuecomment-988177029

**Comment by robertwbradford** [comment]
[react-dev-utils](https://www.npmjs.com/package/react-dev-utils) has published v12. Could `@storybook/react` now be updated to use it?

**Comment by andig** [comment]
Since vulnerability has been solved- could this be released?

**Comment by furdzik** [comment]
`react-dev-utils` has been published to version 12. Could @storybook/angular be updated?

**Comment by shilman** [comment]
Jiminy cricket!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-alpha.6 containing PR #17022 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Yo-ho-ho!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.13 containing PR #17022 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```
