### ISSUE TITLE
Missing preset code in the preset docs

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#16094]
This page: https://storybook.js.org/tutorials/create-an-addon/react/en/preset/

Is missing this code to tie manager/preview into the preset: https://github.com/storybookjs/addon-kit/blob/main/preset.js

As a result the page is confusing/misleading. cc @jonniebigodes @winkerVSbecks

**Comment by winkerVSbecks** [comment]
That's cause it comes from the addon-kit by default. I'll add that explanation in.
