### ISSUE TITLE
SCSS support and SCSS module support with typescript

### ISSUE THREAD

**Issue by jaisonka91** [storybookjs/storybook#16115]
ModuleBuildError: Module build failed (from ./node_modules/style-loader/dist/cjs.js):
TypeError: this.getOptions is not a function

getting this error while trying to import scss file. Tried the same thing which is mentioned [here](https://storybook.js.org/docs/react/addons/install-addons#using-preset-addons)

**Comment by CodeguruEdison** [comment]
Same issue, I have any help?

**Comment by danielpickett** [comment]
I just had the same issue when setting storybook up in a brand new project. I followed the steps from the exactly as specified in [the documentation](https://storybook.js.org/docs/react/addons/install-addons#using-preset-addons) and could not get it to work. It took me quite some time to come to the same conclusion @OriAmir linked to. It seems the docs either need to be updated or the new packages need to be supported so more people aren't let astray by the docs.

**Comment by gabrielgaraujo** [comment]
I just had the same problem and did what @danielpickett and @OriAmir shared!

Step by Step:

1. Run 
```sh
yarn add -D @storybook/preset-scss \
  sass \
  css-loader@5 \
  sass-loader@10 \
  style-loader@2
```
2. Add the following to `.storybook/main.js`:
```js
module.exports = {
  addons: ['@storybook/preset-scss'],
};
```

**Comment by jonniebigodes** [comment]
I was able to confirm this and made a small pull request to address this issue. Thanks everybody for all the insights and for letting us know of the issue. We appreciate it. 

Have a great day all. Stay safe
