### ISSUE TITLE
[Version Document] Can we control our version document?

### ISSUE THREAD

**Issue by JokerDang** [storybookjs/storybook#16118]
**Is your feature request related to a problem? Please describe**
I want to control version whenever I build storybook and user can select one of list version which I deployed and created before to navigate to page fit with version selected.

**Describe the solution you'd like**
Example:
- Sprint 1: I deployed 3 components A, B & C with version number is 1.0.0
- Sprint 2: I deployed extra 3 components D, E & F with version number is 1.0.1

After that, I want to have a Select contains 2 options are: current(1.0.1) and 1.0.0 and then when user select version, the storybook will render those component fit to version

**Are you able to assist to bring the feature to reality?**
no

**Additional context**
I saw the same feature on storybook example. I guess it's custom private by storybook's team!
![image](https://user-images.githubusercontent.com/26645648/134195158-e619795b-dee5-40a2-a87c-285b63932e2e.png)

**Comment by shilman** [comment]
Yes you can. If you provide a `metadata.json` file whose keys are versions and whose values are storybook URLs, it should work fine. Example: https://638db5bf49adfdfe8cf545e0-lacfclthaa.chromatic.com/metadata.json
