### ISSUE TITLE
[Angular] Support `TemplateRef` as args to a Story

### ISSUE THREAD

**Issue by snebjorn** [storybookjs/storybook#16119]
**Is your feature request related to a problem? Please describe**
I have an Angular Component that takes a `TemplateRef` as an `@Input` and I cannot figure out how to setup my Story to call it with a `TemplateRef` arg.

The component I'm trying to write a story for:
```ts
@Component({
  selector: 'test',
  templateUrl: './test.component.html',
})
export class TestComponent {
  @Input() public set value(value: TemplateRef<void>) {
    // ...
  }
}
```

**Describe the solution you'd like**
Somehow be able to supply a `TemplateRef` to a Story's args

**Describe alternatives you've considered**
I tried using `moduleMetadata` and `componentWrapperDecorator` to achieve this. But I couldn't figure out how to pass the `#hello` template to my `TestComponent` args

```ts
// TestComponent.stories.ts
@Component({
  template: `<ng-template #hello>Hello</ng-template>`,
})
class FakeComponent {
  @ViewChild('hello', { static: true }) hello;
}

export const TemplateRefStory: Story<TestComponent> = () => ({});

TemplateRefStory.decorators = [
  moduleMetadata({
    declarations: [FakeComponent],
    imports: [CommonModule],
  }),
  componentWrapperDecorator(FakeComponent),
];
```

**Are you able to assist to bring the feature to reality?**
no

**Comment by shilman** [comment]
This should be possible using args mapping https://storybook.js.org/docs/react/writing-stories/args#mapping-to-complex-arg-values

Closing this for now. Please let me know if there's more to be done here!

**Comment by ChrTall** [comment]
@shilman 
I don´t think that approach will work you normally pass a templateRef as an input by referencing that input.

The answer on Stackoverflow is working for my setup. I have an input that gets a complex object with a templateRef key.
[https://stackoverflow.com/a/73741844](https://stackoverflow.com/a/73741844)

The solution works for me but in the control pannel that Input is not shown with the correct value from the template.
In the control pannel steps should show at least: [{stepName: 'Connectivity Type', stepTemplate: step1Template}, {stepName: 'Database Authentication', stepTemplate: step2Template}]
You would still have to look at the template to know what step1Template and step2Template is though.
