### ISSUE TITLE
Does not work with ViteJS (React TS)

### ISSUE THREAD

**Issue by jon301** [storybookjs/storybook#16112]
**Describe the bug**
Tried to bootstrap a new ViteJS React TS project + Storybook

After running `npm run storybook`, I'm getting the following error in the Chrome DevTools:
`Uncaught SyntaxError: The requested module '/node_modules/slash/index.js?v=2394d43d' does not provide an export named 'default'`

<img width="1381" alt="CleanShot 2021-09-20 at 22 39 54@2x" src="https://user-images.githubusercontent.com/122108/134072500-8fb5914d-11db-4561-b5d7-b78abd2c736c.png">

**To Reproduce**

https://github.com/jon301/vite-storybook

```bash
$ npm init vite@latest
Need to install the following packages:
  create-vite@latest
Ok to proceed? (y) 
✔ Project name: … vite-storybook
✔ Select a framework: › react
✔ Select a variant: › react-ts

Scaffolding project in /Users/jonjon/work/vite-storybook...

Done. Now run:

  cd vite-storybook
  npm install
  npm run dev


$ cd vite-storybook/
$ npm i
...


$ npx sb@next init --builder storybook-builder-vite

 sb init - the simplest way to add a Storybook to your project. 

 • Detecting project type. ✓
 • Adding Storybook support to your "React" app. ✓
 • Preparing to install dependencies. ✓


$ npm run storybook
```

**System**

Environment Info:

  System:
    OS: macOS 11.5.2
    CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
  Binaries:
    Node: 16.2.0 - ~/.nvm/versions/node/v16.2.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.15.0 - ~/.nvm/versions/node/v16.2.0/bin/npm
  Browsers:
    Chrome: 93.0.4577.82
    Firefox: 92.0
    Safari: 14.1.2
  npmPackages:
    @storybook/addon-actions: ^6.4.0-alpha.40 => 6.4.0-alpha.40 
    @storybook/addon-essentials: ^6.4.0-alpha.40 => 6.4.0-alpha.40 
    @storybook/addon-links: ^6.4.0-alpha.40 => 6.4.0-alpha.40 
    @storybook/react: ^6.4.0-alpha.40 => 6.4.0-alpha.40

**Comment by sumitduggal** [comment]
i had the same issue but was able to make it work by commenting out the `core` property in `main.js`
```js
module.exports = {
  stories: ["../src/**/*.stories.mdx", "../src/**/*.stories.@(js|jsx|ts|tsx)"],
  addons: ["@storybook/addon-links", "@storybook/addon-essentials"],
  // "core": {
  //   "builder": "storybook-builder-vite"
  // }
};

```

**Comment by jon301** [comment]
@sumitduggal This will make Storybook fallback to Webpack builder. My goal is to use Vite here

**Comment by sumitduggal** [comment]
@jon301 downgrading to `6.3.8` seems to work for me
```js
"@storybook/addon-actions": "6.3.8",
"@storybook/addon-essentials": "6.3.8",
"@storybook/addon-links": "6.3.8",
"@storybook/react": "6.3.8",
 ```

Storybook `v6.4.0-alpha.41` seems to note it has solved the issue, but it didn't worked for me.
https://github.com/storybookjs/storybook/releases/tag/v6.4.0-alpha.41

**Comment by jon301** [comment]
@sumitduggal Thanks for helping 👍 
✅ I confirm`storybook-builder-vite` works with Storybook `6.3.8`
❌ But does not work with Storybook `6.4.0-alpha.40` and `6.4.0-alpha.41`

**Comment by camiloforero** [comment]
This also happens with Vue when using it with Vite.
The reason is that `@storybook/store` depends on `slash` v3, which is in CommonJS format, and vite doesn't play nice with that format.
Updating to [slash v4](https://github.com/sindresorhus/slash/commits?author=sindresorhus) should have worked, but it breaks some Jest unit tests in turn.

**Comment by jdhaines** [comment]
I've found `6.4.0-alpha.36` will run with vite but it required removing my `node_modules` folder and deleting my `yarn.lock` file (sometimes a couple times).  I'm not really sure why or how.   Dropping back to Webpack per the [post above](https://github.com/storybookjs/storybook/issues/16112#issuecomment-923939893) seems to give a webpack error that wasn't there before.  I might raise another issue if I can't find one already.  I'll add it below in case they end up related... but I don't want to sidetrack this issue.

```bash
ERR! Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './dist/vue.esm-bundler.js' is not defined by "exports" in C:\git\VueCobalt\node_modules\vue\package.json
```

**Comment by shilman** [comment]
Please file Vite-related issues in https://github.com/eirslett/storybook-builder-vite/

Closing this for now--please let me know if you think this ISN'T Vite-related and I'll reopen. Thank you! 🙏
