### ISSUE TITLE
[beta] Unexpected closing tag in Angular storybook 

### ISSUE THREAD

**Issue by vadjs** [storybookjs/storybook#16126]
**Describe the bug**
Some components (sometimes really simple) has next error in storybook v6.4.0-beta.0 have next errors:

```
Unexpected closing tag "stb-input-number-control". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (1:161)
> 1 | <stb-input-number-control [isDisabled]="false" range="[]" placeholder="""" [step]="5" [min]="0" max="Number.MAX_SAFE_INTEGER" [showSteppers]="false" label=""""></stb-input-number-control>
```

In v6.3.8 the same component and stories works perfect.

**To Reproduce**
Not sure how to reproduce this bug exactly but it happens in lines of code like next:
`@Input() public daysPrefix = "";` or `@Input() public daysPrefix: string = "";`

Below is more context about this story.

**System**
Environment Info:

  System:
    OS: macOS 11.4
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 14.17.6 - ~/.nvm/versions/node/v14.17.6/bin/node
    npm: 6.14.15 - ~/.nvm/versions/node/v14.17.6/bin/npm
  Browsers:
    Chrome: 94.0.4606.54
    Firefox: 92.0
    Safari: 14.1.1
  npmPackages:
    @storybook/addon-actions: ~6.4.0-beta.0 => 6.4.0-beta.0
    @storybook/addon-controls: ~6.4.0-beta.0 => 6.4.0-beta.0
    @storybook/addon-docs: ~6.4.0-beta.0 => 6.4.0-beta.0
    @storybook/addon-essentials: ~6.4.0-beta.0 => 6.4.0-beta.0
    @storybook/addon-links: ~6.4.0-beta.0 => 6.4.0-beta.0
    @storybook/angular: ~6.4.0-beta.0 => 6.4.0-beta.0

**Additional context**
Code of the story is next:

```
import { Meta, Story, moduleMetadata } from "@storybook/angular";
import { InputNumberComponent, InputNumberModule } from ".";

export default {
  title: "Simple elements/Input Number",
  component: InputNumberComponent,
  decorators: [
    moduleMetadata({
      imports: [InputNumberModule],
    }),
  ],
  parameters: {
    backgrounds: { default: "dark" }
  }
} as Meta;


const Template: Story<InputNumberComponent> = (args: InputNumberComponent) => ({
  props: args
});

export const Default = Template.bind({});
```

It happens in lines of code like next:
`@Input() public daysPrefix = "";` or `@Input() public daysPrefix: string = "";`

Component template code doesn't matter. It could be super simple but bug still persist.

**Comment by VitaliyOnRule** [comment]
@vadjs any solutions till now?

**Comment by VitaliyOnRule** [comment]
also reproduced with 6.3.8

**Comment by vadjs** [comment]
@VitaliyOnRule i have such problem only in 6.4.0-beta. I have no any problems in 6.3.8.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
