### ISSUE TITLE
Could not find a declaration file for module '@storybook/addon-docs/angular'.

### ISSUE THREAD

**Issue by stefan-schweiger** [storybookjs/storybook#16122]
**Describe the bug**
When I try to import `setCompodocJson` in a `main.ts` file I get this error.

`Could not find a declaration file for module '@storybook/addon-docs/angular'.`

This issue also existed for `@storybook/addon-docs/blocks` https://github.com/storybookjs/storybook/issues/8183 and was fixed via https://github.com/storybookjs/storybook/pull/10441.

So I think I will just replicate this fix for the angular part and create a PR.

**Comment by shilman** [comment]
Olé!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-beta.1 containing PR #16123 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
