### ISSUE TITLE
Restore focus after specific interaction events

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#16139]
> As a user I want to be able to navigate through stories by keyboard (without the keyboard losing focus), so that I can quickly browse through a Storybook.

Patch certain methods that we know grab focus to transfer focus back to the previous location upon completion.

- [ ] `userEvent.type`
- [ ] ... more TBD

NOTE: Also possibly an a11y issue

**Comment by vanessayuenn** [comment]
Dupe of #16143 ?
