### ISSUE TITLE
Lit decorators don't work

### ISSUE THREAD

**Issue by kaifaty** [storybookjs/storybook#16135]
A Lit component dosen't rerender with args when I use @property decorator. If import to story file compiled JS file or use static properties it work fine. 
I suppose  problem is in building process, can you help please?

**Comment by lucianiz** [comment]
Same here,  @Query @queryall just don't work. If I build the same project using vite the decorators work no problem.

**Comment by brion-fuller** [comment]
I may get some time to look into this in a couple weeks.  Sorry for the delay.

**Comment by gaetanmaisse** [comment]
@CodeByAlex faced the same issue and was able to work around it by adding a custom babel config file in `.storybook`, see https://github.com/CodeByAlex/code-by-alex-ds/commit/ab205900e07f37103d032b576828bf048d2e2b09

I started to take a look at how it could be integrated directly in `@storybook/web-components` but no luck, for now, will try one more time in the next days.

**Comment by kaifaty** [comment]
it work's with *babel* `plugin-proposal-decorators`:

```
//.storybook/main.js

module.exports = {
  "stories": [
    "../src/**/*.stories.mdx",
    "../src/**/*.stories.@(js|jsx|ts|tsx)"
  ],
  "addons": [
    "@storybook/addon-links",
    "@storybook/addon-essentials"
  ],
  babel: async (options) => {
    Object.assign(options.plugins.find((plugin) => plugin[0].includes('plugin-proposal-decorators'))[1], {
      decoratorsBeforeExport: true,
      legacy: false
    })
    return options;
  }
}

```

**Comment by IanVS** [comment]
Is anyone still having this issue with the latest Storybook 7.0 beta versions?  If so, can someone share a reproduction that we can look into?  I'll close this for now until we hear back.

**Comment by andeeplus** [comment]
`storybook 7` Just in case somebody wants  to check all the steps to fix this, following the complete answer:

```ts
// tsconfig.json
"experimentalDecorators": true,
"useDefineForClassFields": false // If you do not set this @property works but @query do not
```

```ts
// main.ts
babel: async (options) => {
	return {
		...options,
		assumptions: {
			setPublicClassFields: true,
		},
		plugins: [
			['@babel/plugin-transform-typescript', {
				'allowDeclareFields': true
			}],
			[
				'@babel/plugin-proposal-decorators',
				{
					decoratorsBeforeExport: true,
					version: '2018-09',
				},
			],
			['@babel/plugin-proposal-class-properties', { loose: false }],
			['@babel/plugin-proposal-private-methods', { loose: false }],
			['@babel/plugin-proposal-private-property-in-object', { loose: false }],
		],
	};
},
```

docs:
- https://lit.dev/docs/components/decorators/#decorators-typescript
-  https://lit.dev/docs/components/decorators/#decorators-babel
