### ISSUE TITLE
Args and Globals broken in docs viewMode [6.4-beta]

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#16154]
Globals get updated on canvas but not on docs tab

Reproduction: https://github.com/Talend/design-system

1. Use the theme switcher on any component in canvas/docs
2. Then upgrade to `6.4.0-beta.0` and do the same

Thanks @frassinier for the report 🙏

**Comment by frassinier** [comment]
As I said in #16243, there is no re-render of `DocsContainer` when we change an option from the toolbar and we can deal with it, but its `Canvas` are not re-rendered too.
You can't apply globals or parameters anymore in docs view mode.

**Comment by frassinier** [comment]
Thank you @tmeasday and @shilman, now it's OK! 💯
