### ISSUE TITLE
story not display after restart my code

### ISSUE THREAD

**Issue by sagacity-samiksha-wakode** [storybookjs/storybook#16164]
**Describe the bug**

**To Reproduce**
Please create a reproduction by running `npx sb@next repro` and following the instructions. Read our [documentation](https://storybook.js.org/docs/react/contribute/how-to-reproduce) to learn more about creating reproductions.
Paste your repository and deployed reproduction here. We prioritize issues with reproductions over those without.

**System**
Please paste the results of `npx sb@next info` here.

**Additional context**

**Comment by kylegach** [comment]
Please provide a reproduction or at least steps to reproduce the issue.
