### ISSUE TITLE
Cannot extend Date class in Angular

### ISSUE THREAD

**Issue by salmoro** [storybookjs/storybook#16168]
**Describe the bug**
The following 
```
class MyDate extends Date {
    constructor(...args) {
        super(...args);
        this.doSomething();
    }
    doSomething() {}
}

new MyDate();
````
will throw a runtime error of 
```
ERROR TypeError: this.doSomething is not a function
    at new MyDate
```

The above does not get thrown in the typescript-compiled (Angular) app as it's considered valid Typescript code.

**To Reproduce**
copy the above code into any Angular/TS story

**System**
    OS: Windows 10 10.0.19043
    CPU: (12) x64 Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz
  Binaries:
    Node: 14.15.4 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.10 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1023.0), Chromium (94.0.992.31)
  npmPackages:
    @storybook/addon-a11y: ^6.4.0-beta.1 => 6.4.0-beta.1
    @storybook/addon-actions: ^6.4.0-beta.1 => 6.4.0-beta.1
    @storybook/addon-essentials: ^6.4.0-beta.1 => 6.4.0-beta.1
    @storybook/addon-links: ^6.4.0-beta.1 => 6.4.0-beta.1
    @storybook/angular: ^6.4.0-beta.1 => 6.4.0-beta.1
    @storybook/builder-webpack5: ^6.4.0-beta.1 => 6.4.0-beta.1
    @storybook/manager-webpack5: ^6.4.0-beta.1 => 6.4.0-beta.1

**Additional context**
After some digging it seems like Babel adds a Shim to the native Date which causes this issue.
This Shim is applied on Chrome (93) but not on Firefox (92) nor is this issue reproduceable on Firefox.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
