### ISSUE TITLE
Vulnerability fix on prismjs package

### ISSUE THREAD

**Issue by dkvoda** [storybookjs/storybook#16163]
Regular Expression Denial of Service
https://www.npmjs.com/advisories/1762   

pls update the prismjs@1.24.0

**Comment by shilman** [comment]
w00t!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-alpha.11 containing PR #17127 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
