### ISSUE TITLE
Unable to load stories due to injecting angular services 

### ISSUE THREAD

**Issue by YazeedFares** [storybookjs/storybook#16171]
**Describe the bug**
We have an existing angular 12 project, we installed a storybook on it and was able to create stories for simple components that doesn't load any services in the constructor, however when we add services to the component constructor we keep getting the following error as a warning in the browser console and our component doesn't get loaded in stories explorer on the left side of the screen (it is good to mention that the service name in the error is not loaded in the constructor, we use different services).

Unexpected error while loading ./app/system/pages/-search-result/search-card.component/search-card.stories.ts: TypeError: Cannot read property 'StoreService' of undefined

We simply see only the examples provided by storybook and zero of our components are loaded 

**To Reproduce**
Simply create a new component then inject services in the component constructor 

**System**
 System:
    OS: macOS 11.5.2
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 14.15.4 - /usr/local/bin/node
    npm: 7.21.1 - ~/git/mt-frontend-new/node_modules/.bin/npm
  Browsers:
    Chrome: 93.0.4577.82
    Edge: 94.0.992.31
    Firefox: 90.0.2
    Safari: 14.1.2
  npmPackages:
    @storybook/addon-actions: ^6.3.8 => 6.3.8 
    @storybook/addon-essentials: ^6.3.8 => 6.3.8 
    @storybook/addon-links: ^6.3.8 => 6.3.8 
    @storybook/angular: ^6.3.8 => 6.3.8 
    @storybook/builder-webpack5: ^6.3.8 => 6.3.8 
    @storybook/manager-webpack5: ^6.3.8 => 6.3.8

**Comment by ktschmincke** [comment]
@hiepxanh how did you figure out where the incorrect file import was? I'm having this exact same problem and i'm having a lot of trouble tracking it down. the component called out in the error message is used a ton throughout our app

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
