### ISSUE TITLE
Angular - JSX and Docs code snippet automatically generated don't reflect the right information

### ISSUE THREAD

**Issue by Tim-arts** [storybookjs/storybook#16189]
**Issue**
The docs code snippet doesn't reflect the right information, at the same time the JSX Addon display the exact same result:

Docs code snippet
![image](https://user-images.githubusercontent.com/10064887/135267383-948414eb-8d39-4530-a176-d120a00fbb04.png)
JSX addon result
![image](https://user-images.githubusercontent.com/10064887/135264897-5221cfcc-14eb-4a11-b659-7150f3a10bfc.png)

While we have defined our story this way:
![image](https://user-images.githubusercontent.com/10064887/135264860-1a36ded1-2be5-4ccf-acdc-730e1ef63d08.png)

- `label` value should be `Button`
- `color` prop should be listed with the value `primary`

**To Reproduce**
To reproduce the issue, start a fresh Angular project, set up the JSX addon into it and check your result. The issue is still present in the latest version of SB: `6.4.0-beta.1`

**System**
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
  Binaries:
    Node: 16.9.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.23.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1023.0), Chromium (94.0.992.31)
  npmPackages:
    @storybook/addon-a11y: ^6.4.0-beta.1 => 6.4.0-beta.1
    @storybook/addon-actions: ^6.4.0-beta.1 => 6.4.0-beta.1
    @storybook/addon-docs: ^6.4.0-beta.1 => 6.4.0-beta.1
    @storybook/addon-essentials: ^6.4.0-beta.1 => 6.4.0-beta.1
    @storybook/addon-links: ^6.4.0-beta.1 => 6.4.0-beta.1
    @storybook/addon-storysource: ^6.4.0-beta.1 => 6.4.0-beta.1
    @storybook/angular: ^6.4.0-beta.1 => 6.4.0-beta.1
    @storybook/builder-webpack5: ^6.4.0-beta.1 => 6.4.0-beta.1
    @storybook/manager-webpack5: ^6.4.0-beta.1 => 6.4.0-beta.1
    @storybook/preset-scss: ^1.0.3 => 1.0.3

It has not been listed while running `npx sb@next info` but the JSX dependency is referenced in the package.json as this: `"storybook-addon-jsx": "^7.3.15-canary.162.1301.0"`

**Additionnal information**
The JSX is an addon to use inside a React environment, still, with the CSF format it doesn't matter anymore since it can be used into different environments. If that's intended to not work inside Angular projects, users should have at least a warning. If that's not, JSX Addon should be probably renamed to something else and support different environments

Edit : The issue is still present in the latest version of SB (currently 6.4.4)

**Comment by Tim-arts** [comment]
Seems to be a duplicate of https://github.com/storybookjs/storybook/issues/15575

**Comment by Tim-arts** [comment]
It has a workaround:
```
export const Default: Story<ButtonComponent> = (args: ButtonComponent) => ({
  props: args,
  template: `<ui-kit-button color="primary" label="Button" disableRipple="false" disabled="false"></ui-kit-button>`
})
```

Gives this result in the JSX tab:
![image](https://user-images.githubusercontent.com/10064887/135537701-cc3ab1be-6222-450e-82ae-bfe7773824b8.png)

And in the docs:
![image](https://user-images.githubusercontent.com/10064887/135537731-c6c6cbdf-bf68-489b-b84d-9c89954157c8.png)

**Comment by manuelmeister** [comment]
@shilman I don't think this is a real workaround, as it would have to be added to every story, thus making the "without template" mode pointless.

**Comment by manuelmeister** [comment]
Also I think that if the default-args-value (as defined in the component) is not set in the args, then it should not be set:

component:
```ts
@Component({
  selector: 'button[app-button]
  template: `{{ label }}`
})
class Button {

  @Input()
  variant: "primary" | "secondary" = "primary";

  @Input()
  label = "";

}
```

story:
```ts
export default {
  title: 'Example/Button',
  component: Button
} as Meta;

const Template: Story<Button> = (args: Button) => ({
  props: args,
});

export const Primary = Template.bind({});
Primary.args = {
  label: "Primary Button",
};

export const Secondary = Template.bind({});
Primary.args = {
  label: "Secondary Button",
  variant: "secondary"
};

export const ForceVariant = Template.bind({});
Primary.args = {
  label: "Force all Args",
  variant: "primary"
};
```

story source
```html
<button app-button
  label="Primary Button"
></button>

<button app-button
  label="Secondary Button"
  variant="secondary"
></button>

<button app-button
  label="Force all Args"
  variant="primary"
></button>
````

**Comment by manuelmeister** [comment]
This is still relevant

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
