### ISSUE TITLE
Package subpath './dist/vue.esm-bundler.js' is not defined

### ISSUE THREAD

**Issue by pberoy** [storybookjs/storybook#16180]
**Describe the bug**
`npm run storybook` cannot run due to the following error:
`Package subpath './dist/vue.esm-bundler.js' is not defined`

**To Reproduce**
I made a reproduction repo here.
The following was done:
```
vue create
npx sb init
```

https://github.com/pberoy/storybook-vue3-bug-repro

**System**
Environment Info:

  System:
    OS: Linux 4.19 Ubuntu 20.04 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i5-8400H CPU @ 2.50GHz
  Binaries:
    Node: 14.5.0 - ~/.nvm/versions/node/v14.5.0/bin/node
    npm: 7.19.1 - ~/.nvm/versions/node/v14.5.0/bin/npm
  npmPackages:
    @storybook/addon-actions: ^6.3.8 => 6.3.8
    @storybook/addon-essentials: ^6.3.8 => 6.3.8
    @storybook/addon-links: ^6.3.8 => 6.3.8
    @storybook/vue3: ^6.3.8 => 6.3.8

**Additional context**
I did some digging and found that vue 3.2.18 has been causing issues.
Using <3.2.17 works for storybook.

**Comment by m-demydiuk** [comment]
After an update to storybook 6.3.8, when I do `npm run storybook`, the storybook is launched but in the browser opens URL `http://localhost:6006/`, and I see a blank white screen. In the console, I got this error
`Failed to load resource: the server responded with a status of 404 (Not Found)`
and in the network tab I see
![image](https://user-images.githubusercontent.com/2910327/135281009-20c3acfe-c26f-4090-b2b5-ad3ca32a9723.png)

However, this URL `http://localhost:6006/?path=` runs storybook, and it works then as expected.

**Comment by alessandro-aglietti** [comment]
@scottnath fyi the error is present also on node v16.15.0 LTS as shown there https://github.com/storybookjs/storybook/issues/15964#issuecomment-1122707773

btw as you suggest, on a empty project the following works
- `npm init`
- `npm install vue@3.2.17`
- `npx sb init`
- `npm run storybook`

:rocket: :rocket: :rocket: :rocket: :rocket: :rocket:
