### ISSUE TITLE
Command prompt title changes into `Windows PowerShell`

### ISSUE THREAD

**Issue by thany** [storybookjs/storybook#16192]
**Describe the bug**
Command prompt title changes into `Windows PowerShell` exactly when the server starts and the SB URL is opened in the browser.

**To Reproduce**
No need, this should happen with any SB project, as long as you run it in a **command prompt** in Windows. You should see the title change from "Command Prompt" or "cmd.exe" or similar, to "Windows PowerShell".

**System**
```
Environment Info:

  System:
    OS: Windows 10 10.0.19043
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
  Binaries:
    Node: 14.17.6 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 94.0.4606.61
    Edge: Spartan (44.19041.1023.0), Chromium (94.0.992.31)
  npmPackages:
    @storybook/addon-docs: 6.3.7 => 6.3.7
    @storybook/addon-links: 6.3.7 => 6.3.7
    @storybook/addons: 6.3.7 => 6.3.7
    @storybook/react: 6.3.7 => 6.3.7

```
Still fails to detect Firefox...

**Additional context**
Our project consists of two packages, both using Storybook, which is why both are given their own title before compilation starts using this piee of code:
```javascript
(title => {
  if (process.platform == 'win32') {
    process.title = title;
  } else {
    process.stdout.write('\x1b]2;' + title + '\x1b\x5c');
  }
})('Project 1');
```
But now that Storybook changes it to PowerShell, the two command prompt windows have become indistinguishable. This used to work fine until maybe a few months ago.

It *appears* that this is due to the `open` package, which is used by the `better-opn` package, which is used by `core-server` to open a browser tab. Maybe not so "better" after all.

In a task manager that is fast enough to respond to spawning and despawning processes, you can see powershell.exe being brought into existense for a split second. I used Process Hacker 2 to drill down to it, and because it responds quite quickly.

**Possible workaround?**
If there's something to hook onto *after* opening a browser tab, so that title setting script can (re)run itself there, I'd be all for it. But I'm completely in the dark as to how/where I would hook on to an event from `core-server` like that, if any.

If this is possible, then we can use this before `open` is fixed or replaced.

**Comment by shilman** [comment]
The primary benefit of `better-opn` is that it reuses browser tabs when launching Storybook. IMO this is the difference between a useful feature and an annoyance.

Does storybook also change your prompt if you remove your code snippet?

**Comment by thany** [comment]
@shilman 
> The primary benefit of `better-opn` is that it reuses browser tabs when launching Storybook. IMO this is the difference between a useful feature and an annoyance.

Are you sure? Well maybe in theory, but for me it always opens a new tab...

> Does storybook also change your prompt if you remove your code snippet?

Yes it does. It goes from `cmd.exe` to `npm` when the build process starts, to `Windows PowerShell` when it opens a browser tab.

**Comment by thany** [comment]
Without any progress so far and the root cause likely to be somewhere in `better-opn`, I decided to open an issue there. Perhaps they can get to the bottom of this.

**Comment by shilman** [comment]
@thany this might help if your default browser is not chrome

**Comment by thany** [comment]
If it's just to reuse an existing browser tab, seems like a bit of a faff just for that.

If there would be a big demand for this, which there isn't, there would be a universal API for it in every OS, which there isn't. And by that measure, to me at least, it seems like a bad idea to try and achieve this anyway.

**Comment by michaellzc** [comment]
Hey there, coming from https://github.com/michaellzc/better-opn/issues/36

I am not sure how storybook used to open stuff in browser before integrating `better-opn`.

If you're not running on macOS, regardless of the browser, `better-opn` will always fallback to the upstream https://github.com/sindresorhus/open.

**Comment by thany** [comment]
Ok. And who is going to do that? Or what's next otherwise?

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
