### ISSUE TITLE
Updating /rendering CANVAS isn't working for STORYBOOK VUE JS. Specifically when changing text & select. only boolean works. Docs are working

### ISSUE THREAD

**Issue by konstantina89f** [storybookjs/storybook#16199]
**Describe the bug**
Updating /rendering CANVAS isn't working for text and select. only booleans work. Docs are working.also
ISNT A BROWSER PROB

Example: I have a button, when I choose between icons or I simply change the text, the canvas won't update. I have to go to docs or other components, and then when I come back it will be updated.

**System**
 System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
  Binaries:
    Node: 14.17.6 - /usr/local/bin/node
    npm: 7.24.1 - ~/devProjects/kheops-ui-lib/node_modules/.bin/npm
  Browsers:
    Chrome: 94.0.4606.61
    Firefox: 89.0
    Safari: 15.0
  npmPackages:
    @storybook/addon-docs: ^6.3.8 => 6.3.8 
    @storybook/addon-essentials: ^6.3.6 => 6.3.8 
    @storybook/addon-links: ^6.3.6 => 6.3.8 
    @storybook/vue: ^6.3.6 => 6.3.8 

It is annoying for daily use, to have a playground to play with components and their props and to don't be able to update the view and have to shift between components every time, to see the results.

**Comment by shilman** [comment]
I'm not seeing this in our sample app:

https://storybookjs.netlify.app/vue-kitchen-sink/?path=/story/addon-controls

Do you a have a reproduction repo you can share? If not, can you create one? See [how to create a repro](https://storybook.js.org/docs/react/contribute/how-to-reproduce). We prioritize issues with reproductions over those without. Thank you! 🙏

**Comment by konstantina89f** [comment]
Hello.
Thank you so much for the answer.
I tried many times to repro. but it was failing.
After i made it work, i cannot make it run. 
So basically i would like to send a screenshot to you: 

<img width="1044" alt="Screenshot 2021-10-04 at 17 55 00" src="https://user-images.githubusercontent.com/11364614/135884481-d4d132fc-b81f-4154-ada8-8ca69affa21c.png">
<img width="1239" alt="Screenshot 2021-10-04 at 17 55 07" src="https://user-images.githubusercontent.com/11364614/135884530-dfe6b1d7-1d7d-4350-bc1a-75745cf7e83c.png">

and here are the important code:
preview.js
export const parameters = {
    controls: {
        matchers: {
            color: /(background|color)$/i,
            date: /Date$/
        }
    },
    actions: { argTypesRegex: "^on[A-Z].*" },
    docs: { iframeHeight: '200px' },
}

the height of the frame it wont work if i dont add : inlinestories: false  but once i do that after neither the docs update their compoents values nor the canva.

MAIN.js
module.exports = {
    stories: [
        "../../src/**/*.stories.mdx",
        "../../src/**/*.stories.@(js|jsx|ts|tsx)"
    ],
    logLevel: 'debug',
    addons: [
        {
            name: "@storybook/addon-docs",
            options: { configureJSX: true }
        },
        '@storybook/addon-controls',
        '@storybook/addon-actions',
        '@storybook/preset-scss',
        '@storybook/addon-essentials',
    ]
};

khButton:
const Template = (args, { argTypes }) => ({
    components: { KhButton },
    props: Object.keys(argTypes),
    // Storybook provides all the args in a $props variable.
    // Each arg is also available as their own name.
    template: `<KhButton v-bind="$props" v-on="$listeners" :iconName="iconName">
                   <kh-icon icon="${args.iconName}"></kh-icon>${args.label}&nbsp;
               </KhButton>`
})

 argTypes: {
        label: {
            description: 'Button text',
            control: {
                type: 'text'
            },
            table: {
                type: {
                    summary: 'more info',
                    detail: 'The text which is displayed inside the button.'
                }
            }
        },
}

PLEASE LET ME KNOW what it may be happening because the canvas isnt updating when the text changes and is really something annoying to work with!!

Thank you
