### ISSUE TITLE
Add parameter `storyFilter` to hide stories from sidebar.

### ISSUE THREAD

**Issue by michaltaberski** [storybookjs/storybook#16191]
**Is your feature request related to a problem? Please describe**
I am using storybook for 2 purposes:
1) Document Design System and / or components library
2) Use stories as a test input source for visual testing

The problem is that I am creating dozens of stories for tests which are making the design system documentation simply a mess. I would like to hide those stories from the sidebar to keep it clean and minimal.

**Describe the solution you'd like**
Minimal workable solution to match my need is to add a function `storyFilter` into the `parameters` defined in `preview.js`. Just like we do now with `storySort`.

This way I could do:

```
// run SB
STORYBOOK_VIEW_MODE=design_system npm run storybook

// in preview.js

export parameters = {
  storyFilter: (storyData) => {
    if (process.env.STORYBOOK_VIEW_MODE)  { ... } else { ... } // etc.
  }
}

```

**Describe alternatives you've considered**
I have been "googling" for the solution for quite a bit and the only thing I can say is that I am not the only one having similar issue. It is a tiny enhancement that can help a lot I think.

**Are you able to assist to bring the feature to reality?**
I can try to contribute to the project, but I would need a couple of hints where to start in order to prepare PR.

**Comment by shilman** [comment]
closing this as dupe to #9209, please add your suggested fix there! 🙏
