### ISSUE TITLE
Upgrade babel-plugin-htmlbars-inline-precompile to avoid npm error

### ISSUE THREAD

**Issue by javve** [storybookjs/storybook#16205]
We're getting this error when we're trying to `npm install` our Ember app. It works when we're writing 
```npm install --legacy-peer-deps``` 
or
```npm install --force``` 
But it feels like that shouldn't be needed. Is it possible to upgrade the `babel-plugin-htmlbars-inline-precompile` package?

https://github.com/storybookjs/storybook/blob/28d248034f83f020399d702763c5f7dea8cc1746/app/ember/package.json#L60

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: confetti-app@0.0.0
npm ERR! Found: babel-plugin-htmlbars-inline-precompile@5.3.0
npm ERR! node_modules/babel-plugin-htmlbars-inline-precompile
npm ERR!   babel-plugin-htmlbars-inline-precompile@"^5.3.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer babel-plugin-htmlbars-inline-precompile@"2 || 3" from @storybook/ember@6.3.8
npm ERR! node_modules/@storybook/ember
npm ERR!   @storybook/ember@"^6.3.8" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by javve** [comment]
Seems like it exists an unmerged PR that'll solve this issue: https://github.com/storybookjs/storybook/pull/13142

**Comment by ndelangen** [comment]
Ember is no longer in this repository, therefore I'm closing this issue
