### ISSUE TITLE
Expand & Collapse of component is not working properly on storybook

### ISSUE THREAD

**Issue by harshalpatel91** [storybookjs/storybook#16203]
**Describe the bug**
When we try to collapse or expand the component to see the stories, it not working properly. Once it expands it can't be collapse unless another component is not expanded.

**System**
System:
    OS: macOS 10.15.3
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  Binaries:
    Node: 14.16.1 - /usr/local/bin/node
    npm: 7.19.1 - ~/Documents/harshal/contentstack/react/venus-components/node_modules/.bin/npm
  Browsers:
    Chrome: 94.0.4606.61
    Safari: 13.0.5
  npmPackages:
    @storybook/addon-a11y: ^6.3.7 => 6.3.7 
    @storybook/addon-actions: ^6.0.12 => 6.0.12 
    @storybook/addon-controls: ^6.3.7 => 6.3.7 
    @storybook/addon-docs: ^6.0.12 => 6.0.12 
    @storybook/addon-info: ^5.3.19 => 5.3.19 
    @storybook/addon-knobs: ^6.3.0 => 6.3.0 
    @storybook/addon-links: ^6.0.12 => 6.0.12 
    @storybook/addon-notes: ^5.3.19 => 5.3.19 
    @storybook/addon-storysource: ^6.0.12 => 6.0.12 
    @storybook/addons: ^6.0.12 => 6.0.12 
    @storybook/preset-create-react-app: ^3.1.4 => 3.1.4 
    @storybook/react: ^6.0.12 => 6.0.12 
    @storybook/theming: ^6.0.12 => 6.0.12 

![image](https://user-images.githubusercontent.com/17699720/135497810-e793c3cc-3bf7-4d79-8d84-4b64c8392298.png)

**Comment by shilman** [comment]
Not related to this issue, but all of your storybook package versions should match.

You can do this automatically (recommended) by:
- stable: `npx sb upgrade`
- prerelease: `npx sb upgrade --prerelease`

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
