### ISSUE TITLE
eslint-plugin-prettier packages removed when install @storybook/addons-docs

### ISSUE THREAD

**Issue by eomttt** [storybookjs/storybook#16204]
**Describe the bug**
Hello, i'm install `custom-eslint-config` like this package.json
```json
{
  "dependencies": {
    "@typescript-eslint/eslint-plugin": "^4.29.3",
    "@typescript-eslint/parser": "^4.29.3",
    "eslint-config-airbnb": "^18.2.1",
    "eslint-config-airbnb-base": "^14.2.1",
    "eslint-config-airbnb-typescript": "^14.0.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-import": "^2.24.2",
    "eslint-plugin-jsx-a11y": "^6.4.1",
    "eslint-plugin-prettier": "^4.0.0",
    "eslint-plugin-react": "^7.25.1",
    "eslint-plugin-react-hooks": "^4.2.0",
    "prettier": "^2.4.1"
  },
  "devDependencies": {
    "eslint": "^7.32.0",
    "husky": "^7.0.2",
    "lint-staged": "^11.1.2"
  },
  "peerDependencies": {
    "eslint": "^7.32.0"
  }
}
```
so when i install this package my node_modules like this because of my `custom-eslint-config` dependencies
![Screen Shot 2021-10-01 at 12 16 57 PM](https://user-images.githubusercontent.com/22593217/135560043-b830746f-f568-4466-bfa1-c591d654c939.png)

!but when i install `@storybook/addon-docs`, `eslint-pluin-prettier` deleted from my node_modules
![Screen Shot 2021-10-01 at 12 18 11 PM](https://user-images.githubusercontent.com/22593217/135560135-109d2b16-d1ae-480e-af3c-7f7a01d779fe.png)
of course my `custom-eslint-config` is already installed
so when in `yarn lint` eslint couldn't find the `eslint-plugin-prettier` but when i delete `@storybook/addon-docs` it works very well
![Screen Shot 2021-10-01 at 12 19 38 PM](https://user-images.githubusercontent.com/22593217/135560253-e6a0b5b0-b7f0-4aca-8f24-1b12ace4ae8d.png)

so why this situation fire? do you have any idea?

i think this is `@storybook/addon-docs` bug so i report this issue

**Comment by darrenkeen** [comment]
Facing a similar issue but with @storybook/addon-essentials instead.

Any solutions?

**Comment by ndelangen** [comment]
I don't see how what could possibly cause this. Without a reproduction, there's very little we can do to help.

If you have a reproduction for this issue, please re-open 👍
