### ISSUE TITLE
moduleMetadata decorator incompatible with Meta type with generic type

### ISSUE THREAD

**Issue by literalpie** [storybookjs/storybook#16212]
**Describe the bug**
When creating a `Meta` object that includes a generic parameter, adding the `moduleMetadata` method from `@storybook/angular` causes a type error:

> Conversion of type '{ title: string; component: typeof Button; argTypes: { backgroundColor: { control: string; }; }; decorators: DecoratorFunction<AngularFramework, Args>[]; }' to type 'Meta<StoryArgs>' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
>   Type '{ title: string; component: typeof Button; argTypes: { backgroundColor: { control: string; }; }; decorators: DecoratorFunction<AngularFramework, Args>[]; }' is not comparable to type 'BaseAnnotations<AngularFramework, StoryArgs>'.
>     Types of property 'decorators' are incompatible.
>       Type 'DecoratorFunction<AngularFramework, Args>[]' is not comparable to type 'DecoratorFunction<AngularFramework, StoryArgs>[]'.
>         Type 'DecoratorFunction<AngularFramework, Args>' is not comparable to type 'DecoratorFunction<AngularFramework, StoryArgs>'.
>           Property 'disabled' is missing in type 'Args' but required in type 'StoryArgs'.ts(2352)

**To Reproduce**
[reproduction repo/branch](https://github.com/literalpie/sb-ng-performance/blob/moduleMetadata-type/src/stories/Button.stories.ts#L18).
In `Button.stories.ts`, the type `Meta<StoryArgs>` used to work, but causes type errors in SB6.4. Changing it to `Meta<Partial<StoryArgs>>` works around the issue.

**System**
> System:
>     OS: macOS 11.6
>     CPU: (12) x64 Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz
>   Binaries:
>     Node: 16.6.1 - ~/.nvm/versions/node/v16.6.1/bin/node
>     Yarn: 3.0.1 - /usr/local/bin/yarn
>     npm: 7.20.3 - ~/.nvm/versions/node/v16.6.1/bin/npm
>   Browsers:
>     Chrome: 94.0.4606.61
>     Firefox: 92.0.1
>     Safari: 15.0
>   npmPackages:
>     @storybook/addon-actions: ^6.4.0-beta.3 => 6.4.0-beta.3 
>     @storybook/addon-docs: ^6.4.0-beta.3 => 6.4.0-beta.3 
>     @storybook/addon-essentials: ^6.4.0-beta.3 => 6.4.0-beta.3 
>     @storybook/addon-links: ^6.4.0-beta.3 => 6.4.0-beta.3 
>     @storybook/angular: ^6.4.0-beta.3 => 6.4.0-beta.3 
>     @storybook/builder-webpack5: ^6.4.0-beta.3 => 6.4.0-beta.3 
>     @storybook/manager-webpack5: ^6.4.0-beta.3 => 6.4.0-beta.3 

**Additional context**

I think this is an unintentional breaking change. I think it should either be fixed or documented before 6.4 is fully released.

Maybe it's as easy as changing the type of BaseAnnotations.decorators from `DecoratorFunction<TFramework, TArgs>[]` to `DecoratorFunction<TFramework, Partial<TArgs>>[]`?

**Comment by shilman** [comment]
cc @tmeasday

**Comment by tmeasday** [comment]
Hmm, I wonder how this has changed. Where did we get stricter on the types here? Perhaps we can back that out for now.

> Maybe it's as easy as changing the type of BaseAnnotations.decorators from DecoratorFunction<TFramework, TArgs>[] to DecoratorFunction<TFramework, Partial<TArgs>>[]?

I guess that would work. What exactly does it all mean though? I am a bit puzzled. 

I'm trying to understand it here. It seems like:

 1. You are providing a `DecoratorFunction<AngularFramework, Args>` where `Args` is a very permissive type
 2. The `Meta` type expects its decorators to be `DecoratorFunction<AngularFramework, StoryArgs>` where `StoryArgs` is a more specific version of `Args`.

Is the problem here is that theoretically the `moduleMetadata` function could access other fields on `context.args` when we know they won't be there? Do we need instead to pass `moduleMetadata<StoryArgs>` which is properly parameterised on `StoryArgs`?

I guess that would be a breaking change so we shouldn't change it in 6.4 but do you think that would be the correct thing to do in 7.0 @literalpie?

**Comment by literalpie** [comment]
I'm not really sure. My understanding is that in 6.3, the `BaseDecorator` type didn't have anything to do with args, but now, `DecoratorFunction` does.

We could let `moduleMetadata` take a type parameter. Maybe it could take an optional parameter that defaults to `any`? So someone can add the more accurate type if they want the return type to be more specific, but it would avoid the breaking change.

This would only solve the `moduleMetadata` case though. I wonder if there are other decorators that may have similar problems?

**Comment by tmeasday** [comment]
I'll think about it some more and try and figure out what's changed here.
