### ISSUE TITLE
Storybook Docs container context has changed its API

### ISSUE THREAD

**Issue by frassinier** [storybookjs/storybook#16243]
**Describe the bug**
Storybook Docs container context has changed since `6.4.0-alpha.33`
I used to rely on its context to deal with the property `kind` or gets updated `globals`.
Now, these properties have disappeared and `kind` seems to be replaced by `title` instead.
But nothing about that into the changelog.

```javascript
export const parameters = {
  docs: {
    container: props => {
      console.log(props.context);
      return (<DocsContainer {...props} />);
    },
  },
};
```

**Comment by shilman** [comment]
@tmeasday we probably need to restore this, or at least document it in `MIGRATION.md`

**Comment by frassinier** [comment]
If we go with it, at least having a workaround to access globals and parameters could be nice IMHO!

Because, right now, changing any option on the toolbar using plugins has no more effect 🤷🏻

**Comment by tmeasday** [comment]
@frassinier: there is a `getStoryContext()` function with `globals` available on it. However the docs container may not re-render when the globals change... can you tell me a little more about your use case?

> we probably need to restore this,

@shilman I'm pretty sure we decided this was internal API. I think we can put the old fields back on here, probably using the `breakingChangesV7` flag, but I am not sure if we want to exactly mirror the old semantics of when the docs page is re-rendered.

**Comment by frassinier** [comment]
> each individual story will re-render
It should be enough TBH
I will check tomorrow, but feel free to reject.

**Comment by shilman** [comment]
Re-openening. We should make this backwards compatible unless the `breakingChangesV7` flag is specified.
