### ISSUE TITLE
Loading css breaks in Angular 12.2

### ISSUE THREAD

**Issue by fikkatra** [storybookjs/storybook#16256]
**Bug description**
When upgrading to Angular 12.2 (currently latest stable version), stylesheets are not loaded anymore.

**To Reproduce**
https://github.com/fikkatra/storybook-repro

When running `npx sb@next repro` and choosing 'angular', angular version 12.2 is installed and the issue can be reproduced as is, without any alterations to the code (except for adding a stylesheet).

**Manual repro steps**

Create a new Angular app:
`npx ng new taskbox`

This currently installs v12.1.1 (unlike `npx sb@next repro`, which installs 12.2).

Add storybook to the app:
`cd taskbox`
`npx sb init`

Add a stylesheet to preview.js:
`import "!style-loader!css-loader!./styles.css";`

Add `styles.css` to the `.storybook` directory and add the following styling:
```
body {
  background-color: yellow;
}
```

Run storybook:
`npm run storybook`

Result: styles are loaded:
![image](https://user-images.githubusercontent.com/8104336/136157209-73ea8e87-b291-46ac-9c64-e456b5792721.png)

Now upgrade Angular:
`npx ng update @angular/cli @angular/core`

and run again:
`npm run storybook`

Result: styles are not loaded:
![image](https://user-images.githubusercontent.com/8104336/136155717-1e6cbf0f-9d65-4af7-b7ae-63976bce792b.png)

The following Github repository demonstrates these repro steps. [This commit](https://github.com/fikkatra/storybook-repro-manual/commit/0a0700913b65876c51887169ff9a3118f6e00906) breaks the loading of the style sheet:
https://github.com/fikkatra/storybook-repro-manual

**System**
Environment Info:

  System:
    OS: macOS 11.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
  Binaries:
    Node: 14.17.3 - /usr/local/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 6.14.13 - /usr/local/bin/npm
  Browsers:
    Chrome: 94.0.4606.71
    Firefox: 91.0.2
    Safari: 15.0

**Additional context**
Initial (working) version of (relevant) installed packages:
@angular/core: ~12.1.1
@angular-devkit/build-angular: ~12.1.1
css-loader: 5.2.6
style-loader: 2.0.0

Updated (not working) version of installed packages:
@angular/core: ~12.2.8
@angular-devkit/build-angular: ~12.2.8
css-loader: 5.2.6
style-loader: 2.0.0

**Comment by archfisv** [comment]
I can confirm, we have the same problem.

**Comment by vlautac** [comment]
I run into the same problem when trying to upgrade on Angular v12.2.11 + Storybook v6.3.12.
Global styles are not loaded anymore

**Comment by archfisv** [comment]
Any suggestions @shilman? Would appreciate it.

**Comment by xXCalleManXx** [comment]
I also have some problem with Angular 13 and storybook ^6.4.0-rc.2

**Comment by ThibaudAV** [comment]
we have juste discuss about this issue on discord [here](https://discord.com/channels/486522875931656193/855364585632038913/910197397886480434)

With this PR : https://github.com/storybookjs/storybook/issues/16256


For angular 2.2.x and higher you can fix it by this way
- remove `import "!style-loader!css-loader!./styles.css";` from `preview.js`
- use builder to start/build storybook : 
add this "architect" in your angular.json
```json

      "architect": {
...
        "start-storybook": {
          "builder": "@storybook/angular:start-storybook",
          "options": {
            "tsConfig": ".storybook/tsconfig.json",
            "styles": ["src/styles.scss", ".storybook/index.css"],
            "compodoc": true,
            "port": 9008
          }
        },
        "build-storybook": {
          "builder": "@storybook/angular:build-storybook",
          "options": {
            "tsConfig": ".storybook/tsconfig.json",
            "styles": ["src/styles.scss", ".storybook/index.css"],
            "compodoc": true
          }
        }
...
```

change script in your package.json
```json
...
    "storybook": "ng run storybook-repro:start-storybook",
    "build-storybook": "ng run storybook-repro:build-storybook",
...
```

**Comment by xXCalleManXx** [comment]
I tried this with Angular 13.0.2 and Storybook 6.4.0-rc.4 and getting this error
```
chema validation failed with the following errors:
  Data path "" must NOT have additional properties(styles).
```

How to reproduce:
Install angular cli version 13.0.2
```
$ ng new angular-storybook (I chose angular routing and scss as styling)
$ cd angular-storybook
$ npx sb@next init
```

I then put in the architects that @ThibaudAV written.
I change the start scripts in package.json
```
...
    "storybook": "ng run angular-storybook:start-storybook",
    "build-storybook": "ng run angular-storybook:build-storybook",
...
```

And then if I run `npm run storybook`, I recieve the error message.

**Comment by ThibaudAV** [comment]
yes it doesn't work for the moment it is necessary that the PR (#16256) is merge before and that there is a release.

but you can test with a storybook build on this branch and copy the angular app dist into your node_modules. If you do it don't hesitate to give me feedback 🙏  for the moment I have uniquely tested on 2 of my projects and it works very well

for the moment this pr is waiting for a feedback from @Marklb which should be tested soon on one of these projects. Then I would take into account the feedback. And then @shilman is in charge of the merge and release.

**Comment by shilman** [comment]
@ThibaudAV happy to merge/release as soon as you're ready

**Comment by ThibaudAV** [comment]
I am waiting for the return of @Marklb and if this feature seems to be enough for a first step for him too. I'll let you know :)

**Comment by tscislo** [comment]
Unfortunatelly this issue still exists with ng 12.2.x and storybook 6.4

**Comment by archfisv** [comment]
I can confirm, I visit this issue frequently ;). I think it's about `@angular-devkit/build-angular` (@ v12.0.3 works well).
