### ISSUE TITLE
I need some help please!!

### ISSUE THREAD

**Issue by TonyLau00** [storybookjs/storybook#16258]
**Framework**
Vue

Why my click1's value can not change synchronously when I am typing. I have to refresh the page to update it. Can anyone help??

![image](https://user-images.githubusercontent.com/83462536/136183844-bdb90e91-5f7b-4606-b562-42b53f7944e2.png)

![image](https://user-images.githubusercontent.com/83462536/136184017-e55127aa-6190-4777-9283-64eabb6c8fb7.png)

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if this is still relevant in SB 7.x.
