### ISSUE TITLE
Undocumented addon-api methods

### ISSUE THREAD

**Issue by kylegach** [storybookjs/storybook#16262]
[_Originally reported on Discord_](https://discord.com/channels/486522875931656193/490822681307119618/895097562489565225)

The following methods are undocumented:

- [ ] ready(),
- [ ] hasChannel(channel),
- [ ] setChannel(),
- [ ] getElements(),
- [ ] addPanel(),
- [ ] setConfig(),
- [ ] loadAddons()

**Comment by ndelangen** [comment]
setConfig is a public API
it IS documented in a few places
https://github.com/storybookjs/storybook/blob/f3e77d166b34398ce97b2cead16a9cb715f7f260/examples/cra-kitchen-sink/.storybook/manager.js#L4-L14
https://github.com/storybookjs/storybook/blob/0778094329002043632122bb551e2f61c66e9a6c/addons/docs/docs/theming.md#L10-L24
https://github.com/storybookjs/storybook/blob/62f7253dfd43e292ae82d0dab2734cc85e18753e/docs/snippets/common/storybook-config-layout.js.mdx#L1-L28

addPanel is a "deprecated" API shorthand for `addons.add`

everything else is internal
