### ISSUE TITLE
Documentation for Controls is fragmented and incomplete

### ISSUE THREAD

**Issue by thany** [storybookjs/storybook#16272]
**Is your feature request related to a problem? Please describe**
Yes, it's hard to ascertain what exactly is the entire set of features for addon-controls. As a result, I cannot easily get an overview of what I'm expected to put in a story, where to put it, and what options I have there.

The documentation also lists many different ways to do the same thing, without explaining why "this time we're doing it yet another way". Sometimes it's doing an `export default { ... }`, Another time it's exporting a named story, yet another time it'll do a `Template.bind({})` that I've never seen and isn't explaining anywhere. Sometimes it'll suggest `StoryName.args`, but I've also seen `StoryName.parameters` being used. It's *all over the place*.

Please just use *one style* and folks using a different style can translate to it, in their heads. Or, use tabs, like you already do between JSX and MDX. This will make it *so much* less confusing. It's impossible to extract any kind of best practice right now.

**Describe the solution you'd like**
A reference to Controls features and possibilities, in addition to the already existing task-based documentation. The latter is very useful to get things set up, but after that, when writing more and more complex things, one will need detailed information. The current documentation keeps things very much on the surface, even if it does touch on the important bits.

Also, writing style of stories needs to match, to make it less confusing and a hundred times more productive to read through.

**Describe alternatives you've considered**
I'm not going to dive into the source code. And guessing what might and might not work, doesn't seem quite productive.

**Are you able to assist to bring the feature to reality?**
I'm probably not proficient enough with Controls just yet.

**Comment by kylegach** [comment]
I believe [CSF 3](https://storybook.js.org/blog/storybook-csf3-is-here/) helps clarify a lot of the confusion here.
