### ISSUE TITLE
Double quotes in input function lead to Unexpected closing tag error.

### ISSUE THREAD

**Issue by GaetanRdn** [storybookjs/storybook#16293]
**Describe the bug**
I'm trying to given a function as an Angular input with using the template props. When I have string surrounded by double quote I get this error. 

**To Reproduce**
Cannot do it because I cannot install yarn on my computer. But to reproduce you can get my repo: https://github.com/GaetanRdn/atomic-design

Open the file: src/components/atoms/forms/autocomplete/autocomplete.stories.ts
look for "createOptionFn" function in addOption args.
Transform single quote into double quotes.
Run storybook.
find Add Option story and you will got it.

**Additional context**
My dependencies:
"dependencies": {
    "@angular/animations": "~12.2.8",
    "@angular/common": "~12.2.8",
    "@angular/compiler": "~12.2.8",
    "@angular/core": "~12.2.8",
    "@angular/forms": "~12.2.8",
    "@angular/platform-browser": "~12.2.8",
    "@angular/platform-browser-dynamic": "~12.2.8",
    "@angular/router": "~12.2.8",
    "rxjs": "~6.6.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~12.2.8",
    "@angular-eslint/builder": "^12.5.0",
    "@angular-eslint/eslint-plugin": "^12.5.0",
    "@angular-eslint/eslint-plugin-template": "^12.5.0",
    "@angular-eslint/schematics": "12.5.0",
    "@angular-eslint/template-parser": "^12.5.0",
    "@angular/cli": "~12.2.8",
    "@angular/compiler-cli": "~12.2.8",
    "@angular/elements": "^12.2.8",
    "@babel/core": "^7.15.5",
    "@compodoc/compodoc": "^1.1.15",
    "@storybook/addon-actions": "^6.3.9",
    "@storybook/addon-essentials": "^6.3.9",
    "@storybook/addon-links": "^6.3.9",
    "@storybook/angular": "^6.3.9",
    "@storybook/builder-webpack5": "^6.3.9",
    "@storybook/manager-webpack5": "^6.3.9",
    "@types/jest": "^27.0.2",
    "@types/node": "^12.20.27",
    "@typescript-eslint/eslint-plugin": "4.28.2",
    "@typescript-eslint/parser": "4.28.2",
    "@webcomponents/custom-elements": "^1.5.0",
    "babel-loader": "^8.2.2",
    "eslint": "^7.26.0",
    "gh-pages": "^3.2.3",
    "jest": "^27.2.4",
    "jest-preset-angular": "^10.0.1",
    "typescript": "~4.3.5"
  }

I'm available in your discord, my ID: gr#0191

**Comment by GaetanRdn** [comment]
Not reproduced in 6.5.alpha-32

**Comment by Nodejs-connectmedium-siz** [comment]
@GaetanRdn https://adnanunaccustomed.github.io/WeuLYPA/
