### ISSUE TITLE
Angular component method call on storybook fails with the new renderer 6.2.x

### ISSUE THREAD

**Issue by meyacine** [storybookjs/storybook#16313]
I'm writing an Angular component with a simple input. When (keyup) i call a method defined in the component. On storybook it fails with `bug-text.component.html: ERROR TypeError: _co.customMethod is not a function`

**To Reproduce**
bug-text.component.ts
```
@Component({
  selector: 'bug-text',
  templateUrl: './bug-text.component.html',
  ],
})
export class BugTextComponent {
  ctrl = new FormControl();
  customMethod($event: KeyBoardEvent): void {
     console.log($event.key);
  }
}
```

bug-text.component.html
```
<input type="text" [formControl]="ctrl" (keyup)="customMethod($event)">
```

bug.stories.ts
```
export default {
  title: 'Form/BugText',
  component: BugTextComponent ,
  decorators: [
    moduleMetadata({
      imports: [BugTextModule],
    }),
  ],
} as Meta;

const Template: Story<BugTextComponent > = (args: BugTextComponent ) => ({
  props: {
    ...args,
  },
});

export const Textfield = Template.bind({});
Textfield.args = {
  ctrl: new FormControl('bug'),
};
```
**System**

Environment Info:

  System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz
  Binaries:
    Node: 14.16.0 - C:\dev\tools\nodejs\node.EXE
    Yarn: 1.22.10 - C:\var\cache\jenkins\nodejs\.global-modules\yarn.CMD
    npm: 6.14.11 - C:\dev\tools\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1023.0), Chromium (94.0.992.38)
  npmPackages:
    @storybook/addon-actions: 6.2.9 => 6.2.9
    @storybook/addon-essentials: 6.2.9 => 6.2.9
    @storybook/addon-links: 6.2.9 => 6.2.9
    @storybook/addons: 6.2.9 => 6.2.9
    @storybook/angular: 6.2.9 => 6.2.9
    @storybook/theming: 6.2.9 => 6.2.9

**Additional context**

I'm on storybook `6.2.9` with angular `11.2.11`.
I've tried to enable legacy renderer and it works with it using the parameter `angularLegacyRendering: true` in `preview.js`. But, it causes other problem (form binding, etc).

**Comment by meyacine** [comment]
I found a workaround, using inheritance. If the method is declared in the top class it works ¯\_(ツ)_/¯

**Comment by meyacine** [comment]
@ThibaudAV thanks for the suggestion for the args, but it does not resolve the problem of the component method that is not a function for the renderer

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
