### ISSUE TITLE
Incorrect control type inferred when there is a union of literals

### ISSUE THREAD

**Issue by pahan35** [storybookjs/storybook#16321]
**Labels (for improving triaging)** 
`addon: controls`

**Describe the bug**
If a property type is any kind of union, it turns into an object by default, when it's not always applicable.

For example, here https://github.com/mui-org/material-ui/blob/24015d1e4bdf135ba6c6091141cab2299d824be5/packages/mui-material/src/ButtonBase/ButtonBase.d.ts#L78 it transforms into 
```
    tabIndex?: string | number;
```
when released.

I expect it to be either number or string, but got object.
```
  describe('for unions', () => {
    it("should process 'string | number'", () => {
      // passing a 'string | number', should return control type string
      const inferredControls = inferControls(
        getStoryContext({
          argTypes: {
            tabIndex: {
              type: {
                name: 'string | number',
              },
              name: 'tabIndex',
            },
          },
        })
      );

      expect(inferredControls.tabIndex.control.type).toEqual('string');
    });
  });
```

**To Reproduce**
[Repo](https://github.com/pahan35/storybook-repro/tree/better-union-handling) with storybook and story where it's possible to reproduce a bug.

Also, you can reproduce a bug, pasting test suite into http://github.com/storybookjs/storybook/blob/ea631b79491d2400c96550ee0a37543f203013a6/lib/store/src/inferControls.test.ts#L130

**Note**: make sure to switch to the appropriate branch after cloning repo locally.

**System**

> Environment Info:
> 
>   System:
>     OS: macOS 11.6
>     CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
>   Binaries:
>     Node: 14.17.6 - /usr/local/opt/node@14/bin/node
>     Yarn: 3.0.2 - /usr/local/bin/yarn
>     npm: 6.14.15 - /usr/local/opt/node@14/bin/npm
>   Browsers:
>     Chrome: 94.0.4606.81
>     Safari: 15.0
>   npmPackages:
>     @storybook/addon-actions: ^6.4.0-beta.9 => 6.4.0-beta.9 
>     @storybook/addon-docs: ^6.4.0-beta.9 => 6.4.0-beta.9 
>     @storybook/addon-essentials: ^6.4.0-beta.9 => 6.4.0-beta.9 
>     @storybook/addon-links: ^6.4.0-beta.9 => 6.4.0-beta.9 
>     @storybook/react: ^6.4.0-beta.9 => 6.4.0-beta.9 
> 

**Additional context**
The problem is actual for components, created from [Material UI button](https://github.com/mui-org/material-ui/blob/master/packages/mui-material/src/Button/Button.d.ts).

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
