### ISSUE TITLE
False-positive wrong color 

### ISSUE THREAD

**Issue by pahan35** [storybookjs/storybook#16322]
**Labels (for improving triaging)** 
`addon: controls`

**Describe the bug**
There is a bug for a false-positive color prop while actually it's expected.
If you open a console, you'll see 

> Addon controls: Control of type color only supports string, received "enum" instead

produced by http://github.com/storybookjs/storybook/blob/ea631b79491d2400c96550ee0a37543f203013a6/lib/store/src/inferControls.ts#L27

for `color` property, [specified as a list](https://github.com/mui-org/material-ui/blob/master/packages/mui-material/src/Button/Button.d.ts#L32) of allowed values.

**To Reproduce**
1. Clone  [repo](https://github.com/pahan35/storybook-repro/tree/false-positive-unexpected-color).
2. Switch to branch `false-positive-unexpected-color`.
3. Open specified in Story component.
4. Open console.

**System**

> Environment Info:
> 
>   System:
>     OS: macOS 11.6
>     CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
>   Binaries:
>     Node: 14.17.6 - /usr/local/opt/node@14/bin/node
>     Yarn: 3.0.2 - /usr/local/bin/yarn
>     npm: 6.14.15 - /usr/local/opt/node@14/bin/npm
>   Browsers:
>     Chrome: 94.0.4606.81
>     Safari: 15.0
>   npmPackages:
>     @storybook/addon-actions: ^6.4.0-beta.9 => 6.4.0-beta.9 
>     @storybook/addon-docs: ^6.4.0-beta.9 => 6.4.0-beta.9 
>     @storybook/addon-essentials: ^6.4.0-beta.9 => 6.4.0-beta.9 
>     @storybook/addon-links: ^6.4.0-beta.9 => 6.4.0-beta.9 
>     @storybook/react: ^6.4.0-beta.9 => 6.4.0-beta.9 
> 

**Additional context**
The bug happens for [Material UI Button component](https://github.com/mui-org/material-ui/blob/master/packages/mui-material/src/Button/Button.d.ts#L32).

**Comment by pahan35** [comment]
Same color usage here https://github.com/victor-grajski/storybook-object-object-repro/blob/main/src/stories/Badge.tsx#L10

Maybe it's better to just not push that warning if there is a enum control type?

**Comment by shilman** [comment]
Did you try removing this line?

https://github.com/pahan35/storybook-repro/blob/false-positive-unexpected-color/.storybook/preview.js#L5

**Comment by shilman** [comment]
w00t!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-alpha.10 containing PR #16334 that references this issue. Upgrade today to the `@future` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by rechun** [comment]
> 

thanks

**Comment by rj-wowza** [comment]
I get this warning for any prop named "color"; but in my case, it is an enum (from MUI theme palette). 

Changing the prop name (e.g. "foo") makes the warning go away, but obviously that's not a resonable solution.
