### ISSUE TITLE
sb upgrade --prerelease doesn't work on windows

### ISSUE THREAD

**Issue by yngvebn** [storybookjs/storybook#16335]
**Describe the bug**
When using the --prerelease flag on `sb upgrade` the upgrader doesn't look for prerelease-versions

**To Reproduce**
run `npx sb@next upgrade --prerelease` on an outdated Storybook project

**System**
Environment Info:

  System:
    OS: Windows 10 10.0.22000
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 94.0.4606.81
    Edge: Spartan (44.22000.120.0), Chromium (94.0.992.38), ChromiumDev (96.0.1032.0)
  npmPackages:
    @storybook/addon-essentials: 6.3.1 => 6.3.1
    @storybook/addon-links: 6.3.1 => 6.3.1
    @storybook/addon-measure: ^2.0.0 => 2.0.0
    @storybook/addon-storysource: 6.3.1 => 6.3.1
    @storybook/addons: 6.3.1 => 6.3.1
    @storybook/angular: 6.3.1 => 6.3.1
    @storybook/builder-webpack5: ^6.3.1 => 6.3.1
    @storybook/cli: 6.3.1 => 6.3.1
    @storybook/manager-webpack5: ^6.3.1 => 6.3.1
    @storybook/preset-typescript: ^3.0.0 => 3.0.0

**Additional context**
The issue is identified in code, and PR will be created shortly

**Comment by shilman** [comment]
¡Ay Caramba!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-beta.11 containing PR #16336 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Gadzooks!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.3.12 containing PR #16336 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```
