### ISSUE TITLE
No possibility to disable control if it's populated from inferControl()

### ISSUE THREAD

**Issue by pahan35** [storybookjs/storybook#16340]
**Describe the bug**
It's impossible to disable control if it is inferred from component props.

**To Reproduce**
https://github.com/pahan35/storybook-repro/tree/cant-disable-control-for-inferred

**System**

> Environment Info:
> 
>   System:
>     OS: macOS 11.6
>     CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
>   Binaries:
>     Node: 14.17.6 - /usr/local/opt/node@14/bin/node
>     Yarn: 3.0.2 - /usr/local/bin/yarn
>     npm: 6.14.15 - /usr/local/opt/node@14/bin/npm
>   Browsers:
>     Chrome: 94.0.4606.81
>     Safari: 15.0
>   npmPackages:
>     @storybook/addon-actions: ^6.4.0-beta.9 => 6.4.0-beta.9 
>     @storybook/addon-docs: ^6.4.0-beta.9 => 6.4.0-beta.9 
>     @storybook/addon-essentials: ^6.4.0-beta.9 => 6.4.0-beta.9 
>     @storybook/addon-links: ^6.4.0-beta.9 => 6.4.0-beta.9 
>     @storybook/react: ^6.4.0-beta.9 => 6.4.0-beta.9 
> 

**Additional context**
The possibility itself mentioned in the official doc https://storybook.js.org/docs/react/essentials/controls#disable-controls-for-specific-properties
![image](https://user-images.githubusercontent.com/13823215/137170506-7dd0a4f9-b570-4535-bc80-525cf592049e.png)

**Comment by shilman** [comment]
Yay!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-beta.13 containing PR #16366 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```
