### ISSUE TITLE
Storyshots expects stories to be an array, but stories can also be a function

### ISSUE THREAD

**Issue by mlshv** [storybookjs/storybook#16349]
**Describe the bug**
According to [docs](https://storybook.js.org/docs/react/configure/overview#configure-story-loading), there is a way to configure logic for loading stories by passing a function instead of an array of globs in `main.js`.

However, storyshots addon [expects stories to be an array and not anything else.](https://github.com/storybookjs/storybook/blob/next/addons/storyshots/storyshots-core/src/frameworks/configure.ts#L53)

<img width="821" alt="Снимок экрана 2021-10-14 в 16 43 18" src="https://user-images.githubusercontent.com/16861579/137330234-3cb2fc6c-6fc0-483d-9dab-e2348e30a96e.png">

**To Reproduce**
Clone the reproduction repo, install deps and run `yarn test`: https://github.com/mlshv/storyshots-array-bug-reproduction

**Comment by mlshv** [comment]
For anyone facing this issue, I've found a temporary workaround:
```js
// main.js

function findStories() {
  // sync function that returns an array of stories paths
}

findStories.map = (...args) => {
  const stories = findStories()

  return stories.map(...args)
}

module.exports = {
  stories: findStories
  // ...
}
```

**Comment by hedgepigdaniel** [comment]
Another symptom is that when `stories` is a function that returns a promise (which is also allowed), then it breaks in the same way. In this case, that workaround is not sufficient.

**Comment by ndelangen** [comment]
The future of storyshots is the test-runner:
https://storybook.js.org/docs/react/writing-tests/test-runner#page-top

And use the play function for expectations:
https://storybook.js.org/docs/react/writing-stories/play-function#page-top

We will not be making any improvement / changes to storyshots.
