### ISSUE TITLE
useArgs are not testable in jest

### ISSUE THREAD

**Issue by softwaretop** [storybookjs/storybook#16344]
**Describe the bug**
I've created the storybook story like this:

`const InteractiveTemplate: Story<ICheckboxProps> = ({
  onChange,
  ...args
}: ICheckboxProps): JSX.Element => {
  const [{ isChecked }, updateArgs] = useArgs();
  const handleChange = () => updateArgs({ isChecked: !isChecked });

  return (
    <Checkbox {...args} isChecked={isChecked} onChange={handleChange} />
  );
};

export const Interactive = InteractiveTemplate.bind({});
Interactive.args = {
  isChecked: true,
  label: 'Interactive',
};`

And I create unit test like this:
`
test('should handle change', () => {
    const handleChange = jest.fn();

    render(<Interactive />);

    const linkElement = screen.getByRole('checkbox');

    expect(linkElement).toBeInTheDocument();
});
`

When running the unit test, I got this error message always:
**Storybook preview hooks can only be called inside decorators and story functions.**

**System**
Environment Info:

  System:
    OS: macOS 11.1
    CPU: (4) x64 Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
  Binaries:
    Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
    Yarn: 1.22.11 - ~/.nvm/versions/node/v14.16.0/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v14.16.0/bin/npm
  Browsers:
    Chrome: 94.0.4606.81
    Safari: 14.0.2
  npmPackages:
    @storybook/addon-actions: ^6.3.4 => 6.3.4
    @storybook/addon-essentials: ^6.3.4 => 6.3.4
    @storybook/addon-links: ^6.3.4 => 6.3.4
    @storybook/builder-webpack5: ^6.3.4 => 6.3.4
    @storybook/client-api: ^6.3.4 => 6.3.4
    @storybook/manager-webpack5: ^6.3.4 => 6.3.4
    @storybook/react: ^6.3.4 => 6.3.4

**Comment by tmeasday** [comment]
Haha @yannbf we were just talking about hooks the other day right? My proposal would be the `prepareStoryForExternalUse` (or whatever a better name would be) would add a version of hooks to the story context[1].

[1] Thinking about it a touch more the `useEffect` hook relies on listening on the channel for the `STORY_RENDERED` event. The channel and the event (which is emitted by `PreviewWeb`, not relevant in this context) won't exist in this case. So to make it work we'd need an alternate way to tell the `HooksContext` that the rendering is done. The `prepareStoryForExternalUse` function could easily do that though. Just one more thing to think about.

**Comment by muffinfaery** [comment]
I just encountered this when diving into storybook for the first time. I understand the limitation presented just want to know what a best practice option might be moving forward. 

The goal being to have jest tests run on the stories without duplicating a story just to make it nicer for Stakeholders to view and play with (controls be in sync with user actions on a page, ie clicks to open a modal and the isOpen prop updates real time). I can't have this in storybook and test it as a default without duplication or weird pass through args to do state manipulation on a template. 

I could be extremely naive as I am just a beginner in the storybook flow but what is expected for this workflow? Is this viable? Any guidance here outside direct PR to address potentially a non problem would be helpful. Possibly even for the OP

`
const Template: Story<typeof Modal> = (args) => {
    const [{ isOpen }, updateArgs] = useArgs();
    const handleStorybookArgsClose = (e) => {
        action('Close The Modal')(e);
        updateArgs({ isOpen: !isOpen });
    };

    const handleStorybookArgsOpen = (e: PressEvent) => {
        action('Open The Modal')(e);
        updateArgs({ isOpen: true });
    };

    return (
            <Button onPress={handleStorybookArgsOpen}>
                Open Dialog
            </Button>
            <Modal onClose={handleStorybookArgsClose} {...args}>
                <form>
                    <Button onPress={handleStorybookArgsClose}>
                        Close The Modal
                    </Button>
                </form>
            </Modal>
    );
};
`

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).

FWIW we added methods for this first in https://www.npmjs.com/package/@storybook/testing-react and then in `@storybook/react` in 7.0
