### ISSUE TITLE
Interactions: Add stories for the Panel component

### ISSUE THREAD

**Issue by MichaelArestad** [storybookjs/storybook#16358]
Please add stories for the Panel component. I understand the component is a bit complex to mock. Perhaps it might make sense to break it up into multiple components. Really, I would like stories for various states of the Interactions in the panel. Currently, I have to create errors to see the error states, which is not easy to review or work on.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200510412866230/1201198989547238) by [Unito](https://www.unito.io)

**Comment by ghengeveld** [comment]
This was done by @yannbf a while ago 👍
