### ISSUE TITLE
In CSF3, expose story-object to loaders and custom render-functions

### ISSUE THREAD

**Issue by MichaelAllenWarner** [storybookjs/storybook#16352]
**Is your feature request related to a problem? Please describe**
With the story-function format, we can refer to the story itself in the body of a loader (it gets passed in as the `originalStoryFn`). With CSF3's new story-object format, the story itself does not seem to get passed in to loaders or custom render-functions, making it impossible to access arbitrary properties of the story-object.

**Describe the solution you'd like**
I'd like the story-object itself to get passed to loaders and custom render-functions when using the new story-object format.

**Describe alternatives you've considered**
A current workaround is to put properties you want access to in the story's `parameters`, since the parameters object already gets passed to loaders and custom render-functions. But A) I think this violates the spirit of what the parameters object is for; and B) it's inconvenient, particularly if you _also_ want access to those properties elsewhere (i.e., you'd have to do `Story.parameters.property` instead of `Story.property` everywhere).

**Are you able to assist to bring the feature to reality?**
Possibly, but I'm not really familiar with the relevant codebase, so probably not any time soon.

**Comment by tmeasday** [comment]
@shilman I wonder if taking `originalStoryFn` away is a breaking change though? We might need to re-add it unless you pass the `breakingChangesV7` flag.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if this is still relevant in SB 7.x.
