### ISSUE TITLE
Interactions: Update the logic of the Interactions tab icon

### ISSUE THREAD

**Issue by MichaelArestad** [storybookjs/storybook#16359]
The logic for Interactions addon tab icon needs to be modified to display as follows: 

1. If there are Interactions, show the play icon.
1. If there is an error, show the stop icon.
1. When there are no interactions, show nothing.

I also tried to modify the space between the icon and the tab label without success. I would like it to look like this:

![](https://user-images.githubusercontent.com/1123119/137395420-9c9645c7-e5c6-4fb9-a01f-46204bdb04d3.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200510412866230/1201199060265950) by [Unito](https://www.unito.io)

**Comment by shilman** [comment]
Olé!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-beta.27 containing PR #16578 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
