### ISSUE TITLE
Changes with the new "Story" type

### ISSUE THREAD

**Issue by ThibaudAV** [storybookjs/storybook#16360]
**Describe the bug**

After the update I have this error:
```
TS2322: Type '{}' is not assignable to type 'Story<Args>'.
  Type '{}' is not assignable to type 'ArgsStoryFn<AngularFramework, Args>'.
    Type '{}' provides no match for the signature '(args: Args, context: StoryContext<AngularFramework, Args>): StoryFnAngularReturnType'.
```
Because all the type Sotry has changed. 

We now need to use the Story type present in `types-7-0'`. right ? 

I would expect to be able to make an import of the type with : 
`import { Story } from '@storybook/angular/types-7-0';`
but i can't i need to use : 
`import { Story } from '@storybook/angular/dist/ts3.9/client/preview/types-7-0';`

don't you need to add something in MIGRATION.md ? 

**To Reproduce**

- Upgrade to 6.4.0-beta.11
- Try to use CSF3 with Story type

**System**

```
  System:
    OS: macOS 11.5.2
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Binaries:
    Node: 14.15.5 - ~/.nvm/versions/node/v14.15.5/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v14.15.5/bin/npm
  Browsers:
    Chrome: 94.0.4606.81
    Safari: 14.1.2
  npmPackages:
    @storybook/addon-essentials: ^6.4.0-beta.11 => 6.4.0-beta.11
    @storybook/angular: ^6.4.0-beta.11 => 6.4.0-beta.11


and this : 

  features: {
    previewCsfV3: true,
    storyStoreV7: true,
  },
```

**Additional context**
Link : https://github.com/storybookjs/storybook/pull/16107

Maybe wee can fix it by adding a types-7-0.d.ts as for the types-6-0.d.ts ?

**Comment by shilman** [comment]
@ThibaudAV Does it work if you type it with `StoryObj`?

@tmeasday Since CSF3 is experimental I'm fine with a breaking change on its types, but we should probably add a migration note in `MIGRATION.md`

**Comment by shilman** [comment]
Yowza!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-beta.24 containing PR #16466 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Whoopee!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-beta.25 containing PR #16466 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```
