### ISSUE TITLE
'Timeout' is not assignable to type 'number'

### ISSUE THREAD

**Issue by MickL** [storybookjs/storybook#16368]
**Describe the bug**
Storybook is messing up setTimeout and using types from Node instead ob lib.dom

**To Reproduce**
Code to reproduce the error:
```ts
export class DataService {
    timer: number;

    constructor() {
         this.timer = setTimeout(() => {
                  // ...
         }, 1000);
    }
}
```

Results in:
> 'Timeout' is not assignable to type 'number'

**System**
```
  System:
    OS: macOS 11.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 16.8.0 - ~/.nvm/versions/node/v16.8.0/bin/node
    Yarn: 1.22.11 - ~/.nvm/versions/node/v16.8.0/bin/yarn
    npm: 7.21.1 - ~/.nvm/versions/node/v16.8.0/bin/npm
  Browsers:
    Chrome: 94.0.4606.81
    Safari: 15.0
  npmPackages:
    @storybook/addon-actions: ^6.4.0-beta.7 => 6.4.0-beta.7 
    @storybook/addon-essentials: ^6.4.0-beta.7 => 6.4.0-beta.7 
    @storybook/addon-links: ^6.4.0-beta.7 => 6.4.0-beta.7 
    @storybook/angular: ^6.4.0-beta.7 => 6.4.0-beta.7 
    @storybook/builder-webpack5: ^6.4.0-beta.7 => 6.4.0-beta.7 
    @storybook/manager-webpack5: ^6.4.0-beta.7 => 6.4.0-beta.7 
```

**Workaround**
As a workaround one could use `window.setTimeout` instead of `setTimeout` but actually I dont want to put code into my application that exists just to fix Storybook build.

**Comment by MickL** [comment]
Storybook should not node types. I tried to remove von tsconfig.json but the error still occurs. Also I read in another issue that node types were required for Angular, not sure if this is still current.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
