### ISSUE TITLE
Interactions: Sometimes interaction rows duplicate

### ISSUE THREAD

**Issue by MichaelArestad** [storybookjs/storybook#16362]
**Describe the bug**
When clicking through interactions on the Interactions > AccountForm > Standard Email Success story, interaction rows occasionally duplicate.

https://user-images.githubusercontent.com/1123119/137402260-194ccf32-a256-40f2-8532-7f47db221220.mp4

**To Reproduce**

1. In Storybook Official, navigate to Interactions > AccountForm > Standard Email Success.
1. Quickly click through interactions. You will notice some occasionally duplicate.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200510412866230/1201199533116379) by [Unito](https://www.unito.io)

**Comment by ghengeveld** [comment]
Closing as duplicate of #16426
