### ISSUE TITLE
6.4.0-beta.12: Addon interactions — can't jump to step

### ISSUE THREAD

**Issue by winkerVSbecks** [storybookjs/storybook#16376]
**Describe the bug**
When I click on a specific step the story crashes or the interaction fails

**To Reproduce**
Tried two options:

```js
UpdateTasks.play = async ({ canvasElement }) => {
  const canvas = within(canvasElement);
  await waitForElementToBeRemoved(canvas.queryByText('You have no tasks'));
  const getTask = (name) => canvas.getByRole('listitem', { name });

  // Pin
  const pinButton = within(getTask('Export logo')).getByRole('button', {
    name: 'pin',
  });
  await fireEvent.click(pinButton);

  // Archive
  const archiveCheckbox = await within(getTask('QA dropdown')).getByRole(
    'checkbox'
  );
  await fireEvent.click(archiveCheckbox);

  // Edit
  const taskInput = await within(
    getTask('Fix bug in input error state')
  ).getByRole('textbox');
  await fireEvent.change(taskInput, {
    target: { value: 'Fix bug in the textarea error state' },
  });

  // Delete
  const deleteButton = await await within(
    getTask('Build a date picker')
  ).getByRole('button', {
    name: 'delete',
  });
  await fireEvent.click(deleteButton);
};
```

This one crashes the story:
![Kapture 2021-10-16 at 11 09 44](https://user-images.githubusercontent.com/42671/137592659-bc97b441-bf37-4050-8461-db132f86da02.gif)

The second approach, which is much cleaner IMO:

```js
UpdateTasks.play = async ({ canvasElement }) => {
  const canvas = within(canvasElement);
  const getTask = (name) => canvas.findByRole('listitem', { name });

  // Pin
  const itemToPin = await getTask('Export logo');
  const pinButton = await findByRole(itemToPin, 'button', { name: 'pin' });
  await fireEvent.click(pinButton);

  // Archive
  const itemToArchive = await getTask('QA dropdown');
  const archiveCheckbox = await findByRole(itemToArchive, 'checkbox');
  await fireEvent.click(archiveCheckbox);

  // Edit
  const itemToEdit = await getTask('Fix bug in input error state');
  const taskInput = await findByRole(itemToEdit, 'textbox');
  await fireEvent.change(taskInput, {
    target: { value: 'Fix bug in the textarea error state' },
  });

  // Delete
  const itemToDelete = await getTask('Build a date picker');
  const deleteButton = await findByRole(itemToDelete, 'button', {
    name: 'delete',
  });
  await fireEvent.click(deleteButton);
};
```

This one shows the interaction as failing. But if I go back to the start and step forward then that works. 

![Kapture 2021-10-16 at 11 03 45](https://user-images.githubusercontent.com/42671/137592405-7afd327d-3225-47e8-b7af-03de020010fe.gif)

Full code available here: https://github.com/chromaui/ui-testing-guide-code/tree/interactive-stories

**Comment by pahan35** [comment]
Also, you just don't have options when your interaction is run.

It's something related to https://testing-library.com/docs/guide-disappearance/

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
