### ISSUE TITLE
Spread propTypes aren't included in ArgsTable

### ISSUE THREAD

**Issue by IPWright83** [storybookjs/storybook#16402]
**Describe the bug**
The `<ArgsTable/>` component does not correctly detect inherited/spread props.

**To Reproduce**
I'll try and put together a reproduction later, but this is a really simple example. Within an `mdx` file the following in my case displays just a single prop called `useCanvas`.

`<ArgsTable of={Scatter} />`

**Scatter.js**
```
Scatter.propTypes = {
    ...ScatterBase.propTypes,

    /**
     * Should this plot use an HTML Canvas instead of SVG?
     * @type {Boolean}
     */
    useCanvas: PropTypes.bool,
};
```

**ScatterBase.js**
```
ScatterBase.propTypes = {
    ...plotPropTypes,
    ...eventPropTypes,

    /**
     * The optional key of the field used for the relative z size. This overrides the radius
     * @type {String}
     */
    z: PropTypes.string,

    /**
     * The fixed radius to use for points. This is ignored if z is provided
     * @type {Number}
     */
    radius: PropTypes.number,
};
```

**System**
```
Environment Info:

  System:
    OS: Linux 5.11 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (12) x64 AMD Ryzen 5 3600X 6-Core Processor
  Binaries:
    Node: 12.22.7 - /usr/bin/node
    Yarn: 3.0.2 - /usr/bin/yarn
    npm: 6.14.15 - /usr/bin/npm
  Browsers:
    Chrome: 94.0.4606.81
    Firefox: 93.0
```

**Additional context**
The interesting this is `defaultProps` does inherit correctly. In my example the `defaultProps` for `<Scatter />` are defined as follows. If I manually re-define `radius` in the `<Scatter>` rather than relying on the spread operator, it does correctly pull out the default value from `ScatterBase`.

```
Scatter.defaultProps = {
    ...ScatterBase.defaultProps,
    useCanvas: false,
};
```

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
