### ISSUE TITLE
Documentation on configs for addon-docs when using it from addons-essentials

### ISSUE THREAD

**Issue by manufabri91** [storybookjs/storybook#16419]
**Is your feature request related to a problem? Please describe**
I wasn't able to configure MDX to use it from Addon-essentials. I had to install addon-docs separately

**Describe the solution you'd like**
An example among the Essentials section on how to configure addons when using it from the essential package

**Describe alternatives you've considered**
Adding a key to the preset of addon-essentials that allows to use MDX

**Are you able to assist to bring the feature to reality?**
Yes, with some help maybe.

**Additional context**
N/A

**Comment by jonniebigodes** [comment]
A pull request was just introduced to address this issue. With it, the documentation was updated to add some clarity on how to add and how to set up each individual Essential addon.

@manufabri91 if this is still an issue, let me know and I'll gladly re-open it. Also regarding the MDX issue you were experiencing if you're still having it, I'd appreciate it if you provide some additional context on it and if possible a [reproduction](https://storybook.js.org/docs/react/contribute/how-to-reproduce). 

We're sorry for the delayed response on this issue and that no one followed up with you on this 🙏 !


Hope you have a great day!

Stay safe

**Comment by manufabri91** [comment]
Hi Jonnie! 

Not a problem! This was more a "nice to have" since, as I mentioned, I was able to configure it adding it separately. I will take a look at that change you just did and, in case I need it I will come back again.

Thank you so much!
