### ISSUE TITLE
StoryStore v7: CSF + MDX stories throws error

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#16421]
**Describe the bug**

When using the `storyStoreV7` flag, Storybook complains when loading a story that is a mix of CSF + MDX (following [this recipe](https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/recipes.md#csf-stories-with-mdx-docs))
![image](https://user-images.githubusercontent.com/1671563/138098761-9b10d0f0-7343-48f2-85b4-dc8f9d5ac6dc.png)

The issue is that in order to use the CSF in MDX, the `.stories.js` file should not have a default export, however the new logic in storyStoreV7 requires stories to have a default export.

![image](https://user-images.githubusercontent.com/1671563/138098788-988ccb91-cd30-41b4-a229-c657791a4203.png)

**To Reproduce**

1 - open the `official-storybook` example
2 - change the `stories` field to:
```js
  stories: [
    './stories/addon-docs/csf-with-mdx-docs.stories.@(js|ts|tsx|mdx)',
  ],
```
3 - change the `storySort` parameter in `preview.js`:
```
  options: {
    storySort: (a, b) =>
      a.title === b.title ? 0 : a.id.localeCompare(b.id, undefined, { numeric: true }),
  },
```
4 - add the `storyStoreV7` flag to `main.js`
5 - run Storybook

**Comment by shilman** [comment]
Olé!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-beta.29 containing PR #16606 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
