### ISSUE TITLE
Addon-interactions: Panel is showing more steps than the actual count in async tests

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#16426]
**Describe the bug**

Best way to describe is via this video (commented)

https://user-images.githubusercontent.com/1671563/138130517-af294533-c317-4cf4-8946-533d2990bb04.mov

**To Reproduce**

* Open [official-storybook interaction live demo](https://next--storybookjs.netlify.app/official-storybook/?path=/story/addons-interactions-accountform--wait-for)
* Interact with the steps like in the video

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200510412866230/1201237569129111) by [Unito](https://www.unito.io)

**Comment by ghengeveld** [comment]
I can reproduce this even without debugging, using the following play function:

```js
WaitFor.play = async ({ args, canvasElement }) => {
  await userEvent.click(await within(canvasElement).findByText('Click'));
  await waitFor(async () => {
    await expect(args.onSubmit).toHaveBeenCalledWith(expect.stringMatching(/([A-Z])\w+/gi));
    await expect(true).toBe(false);
  });
};
```

Obviously the 2nd assertion will always fail. The first one will fail at the first attempt, and then pass.

<img width="921" alt="Screenshot 2021-11-12 at 11 13 17" src="https://user-images.githubusercontent.com/321738/141450251-f3ccec2e-4025-4ee4-82a2-51052a4eadd4.png">

**Comment by shilman** [comment]
Ermahgerd!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-rc.8 containing PR #16465 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
