### ISSUE TITLE
Tsx story file not getting transformed to csf format

### ISSUE THREAD

**Issue by viditganpi** [storybookjs/storybook#16436]
@storybook/codemod version `@storybook/codemod@6.4.0-alpha.30`

I am trying to transform a file with `.stories.tsx` extension to csf format.  When I run the command only the import statement  for `storiesof` gets removed, rest of the file maintains it state and there is no transformation for the actual stories of part. 

Command used ``` 
./node_modules/.bin/jscodeshift --parser="tsx" -t ./node_modules/@storybook/codemod/dist/modern/transforms/storiesof-to-csf.js <path to tsx file> ```

Also the story is in the old format, as is mentioned in the readme for codemod.

**Comment by shilman** [comment]
Can you share the file you are trying to transform? I just ran that exact command (with --parser=ts) and it worked fine for me on https://github.com/storybookjs/storybook/blob/next/examples/angular-cli/src/stories/legacy/storiesOf.stories.ts
