### ISSUE TITLE
On-demand store: User has to reload browser after fixing issues in story

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#16449]
**Describe the bug**

When using `storyStoreV7` and there's an error in a story that breaks preview, even after fixing it, the user has to reload the browser to keep using Storybook. Before that was not the case.

https://user-images.githubusercontent.com/1671563/138484352-3902d147-0b4f-4b6a-98b5-51aa04bf3c83.mov

**To Reproduce**

- Run storybook in `react-ts`
- Make a story break (see video)
- Fix the story

**Comment by shilman** [comment]
Gadzooks!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-beta.27 containing PR #16537 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
