### ISSUE TITLE
Add global variable that makes it easy to check if code is running in Storybook

### ISSUE THREAD

**Issue by srmagura** [storybookjs/storybook#16485]
This is just a placeholder issue to remind me to implement the `window.IS_STORYBOOK` feature that I discussed with the team on PR #16379. This feature will provide a safer and more convenient method of detecting if code is running within Storybook. 🙂

**Comment by shilman** [comment]
ZOMG!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-alpha.19 containing PR #16676 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
