### ISSUE TITLE
v7 Store: Storybook hangs if too many browser tabs are open

### ISSUE THREAD

**Issue by tmeasday** [storybookjs/storybook#16489]
**Describe the bug**
Due to the use of open requests (SSE), there is a limit on the number of tabs you can have open to a given local storybook.

**To Reproduce**
Open `react-ts` 3 times.

**Comment by shilman** [comment]
Egads!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-beta.26 containing PR #16504 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
