### ISSUE TITLE
Zone.js not loaded for Angular in storyStoreV7

### ISSUE THREAD

**Issue by literalpie** [storybookjs/storybook#16499]
**Describe the bug**
When an Angular storybook is opened with storyStoreV7 turned on, the following error is shown:
> In this configuration Angular requires Zone.js

**To Reproduce**
In the angular-cli demo in the storybook repo, turn on storyStoreV7 (and delete the legacy folder so it builds properly)

**System**
Environment Info:

  System:
    OS: macOS 11.6
    CPU: (12) x64 Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz
  Binaries:
    Node: 16.11.1 - ~/.nvm/versions/node/v16.11.1/bin/node
    Yarn: 3.0.0-git.20210727.hash-3cbbb672 - /usr/local/bin/yarn
    npm: 8.0.0 - ~/.nvm/versions/node/v16.11.1/bin/npm
  Browsers:
    Chrome: 95.0.4638.54
    Firefox: 93.0
    Safari: 15.0
  npmPackages:
    @storybook/addon-docs: 6.4.0-beta.21 => 6.4.0-beta.21 
    @storybook/addon-storyshots: 6.4.0-beta.21 => 6.4.0-beta.21 
    @storybook/angular: 6.4.0-beta.21 => 6.4.0-beta.21

**Additional context**
I think angular/src/client/preview/globals.ts, which imports './angular-polyfills' is related to this somehow, but may not be getting called any more.

**Comment by shilman** [comment]
Huzzah!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-beta.30 containing PR #16631 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
