### ISSUE TITLE
Unable to find an option to convert setAddon() to latest Storybook compatible functionality.

### ISSUE THREAD

**Issue by vinodkumarsharma276** [storybookjs/storybook#16491]
**Describe the bug**
We are moving from Storybook 5.* to Storybook 6.3.7 along with converting stories from storiesOf() to CSF. We are currently using setAddon() in config.js to produce RTL version of a story if config with {rtl: true} is passed. To carry out this operation we have used a function "addStory()" as a wrapper over add(). Below is the exlanation in code:

Component to test --> X

In config.js we have defined -->

```js
storybook.setAddon({
  addStory(storyName, storyFn, config = defaultConfig) {
    this.add(storyName, context => {
      setRTL(false);
      var mergedAppSettings = Object.assign({}, defaultConfig.appSettings, config.appSettings);
      setAppSettings(mergedAppSettings);
      initializeTheme(mergedAppSettings);
      return storyFn(context);
    });
    if (config.rtl) {
      this.add(storyName + ' - RTL', context => {
        setRTL(true);
        var mergedAppSettings = Object.assign({}, defaultConfig.appSettings, config.appSettings);
        setAppSettings(mergedAppSettings);
        initializeTheme(mergedAppSettings);
        return storyFn(context);
      });
    }
  },
});
```

and we use _**"addStory("storyName", <X />, {rtl: true})**_ to write a story. This produces/renders two stories in Storybook ---> X and X - RTL and we see two stories in browser.

I need to achieve the same in CSF format. I've moved config.js content to main.js but don't know how to move _**setAddOn()**_ to main .js

Please help!!!

**To Reproduce**
Please create a reproduction by running `npx sb@next repro` and following the instructions. Read our [documentation](https://storybook.js.org/docs/react/contribute/how-to-reproduce) to learn more about creating reproductions.
Paste your repository and deployed reproduction here. We prioritize issues with reproductions over those without.

**System**
Please paste the results of `npx sb@next info` here.

**Additional context**

**Comment by vinodkumarsharma276** [comment]
Thanks for the reply @shilman . This didn't resolve our issue. As I've mentioned that we are wrapping add() function inside addStory() and addStory() definition is not there after converting to CSF. So, we are not sure how we can achieve the same behavior with CSF

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
