### ISSUE TITLE
Allow other viewModes to be sticky

### ISSUE THREAD

**Issue by chee** [storybookjs/storybook#16518]
## my problem
I have a couple of custom tabs in my storybook, and I want to be able to link to them directly, but when i do it pushes me back to /story.
And i'd also like to be able to keep the tab as the focused tab as i switch between stories, but I am pushed back to /story.

## my dream
I think it's this bit of code that's responsible? https://github.com/storybookjs/storybook/blob/79bb67677429b6c46b1a3fc052f052896fd10b14/lib/api/src/modules/stories.ts#L298-L307

it would be cool if an addon could add its `viewMode` to the list of persistent tabs, so i could link directly to my own tab's view for a story.

### make it exclusionary instead

the comment says it is to avoid keeping the `viewMode` when it's "'settings', for example". maybe could collect together the other examples of undesirable sticky views and invert the logic to push to /story when it's one of them

### do nothing

i would continue to be sad

## can i assist
if you wanna go the route of making it exclusive, and specifically hopping out when `viewMode` is "settings", then yes! that seems like a PR i am capable of

the other route of making it a list that addons can add themselves to sounds very hard and i would not like to help with that

thanks
- chee rabbits

**Comment by zolk** [comment]
> just noticed this problem of being unable to link to a tab doesn't happen in the compiled deployed static storybook, so this is now less important

I'm currently running into this same problem, but still can't link directly to custom tabs even in the deployed version.

**Comment by shilman** [comment]
@chee i'd def accept a PR for this. @ndelangen WDYT?

**Comment by ndelangen** [comment]
What if this:

```suggestion
if (viewMode.match(/about|settings|release/)) { 
  viewMode = 'story'; 
} 
 ```

**Comment by shilman** [comment]
Ermahgerd!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-alpha.2 containing PR #16943 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
