### ISSUE TITLE
I get build fails when I have the @storybook/addon-docs plugin installed and I delete & reinstall npm modules.

### ISSUE THREAD

**Issue by robrich** [storybookjs/storybook#16530]
**Describe the bug**
I get build fails when I have the @storybook/addon-docs plugin installed and I delete & reinstall npm modules.

**To Reproduce**
npm install -g @vue/cli
vue create myapp
cd myapp
npx sb init
npm install --save-dev @storybook/addon-docs
npm run serve
**note it works as expected**
rm -rf node_modules
rm -rf package-lock.json
npm install
**note the webpack failure:**
```
 INFO  Starting development server...
 ERROR  Error: Rule can only have one resource source (provided resource and test + include + exclude) in {
  "type": "javascript/auto",
  "include": [
    {}
  ],
  "use": []
}
Error: Rule can only have one resource source (provided resource and test + include + exclude) in {
  "type": "javascript/auto",
  "include": [
    {}
  ],
  "use": []
}
    at checkResourceSource (...\myapp\node_modules\@vue\cli-service\node_modules\webpack\lib\RuleSet.js:167:11)
    at Function.normalizeRule (...\myapp\node_modules\@vue\cli-service\node_modules\webpack\lib\RuleSet.js:198:4)
    at ...\myapp\node_modules\@vue\cli-service\node_modules\webpack\lib\RuleSet.js:110:20
    at Array.map (<anonymous>)
    at Function.normalizeRules (...\myapp\node_modules\@vue\cli-service\node_modules\webpack\lib\RuleSet.js:109:17)
    at new RuleSet (...\myapp\node_modules\@vue\cli-service\node_modules\webpack\lib\RuleSet.js:104:24)
    at new NormalModuleFactory (...\myapp\node_modules\@vue\cli-service\node_modules\webpack\lib\NormalModuleFactory.js:115:18)
    at Compiler.createNormalModuleFactory (...\myapp\node_modules\@vue\cli-service\node_modules\webpack\lib\Compiler.js:636:31)
    at Compiler.newCompilationParams (...\myapp\node_modules\@vue\cli-service\node_modules\webpack\lib\Compiler.js:653:30)
    at Compiler.compile (...\myapp\node_modules\@vue\cli-service\node_modules\webpack\lib\Compiler.js:661:23)
    at ...\myapp\node_modules\@vue\cli-service\node_modules\webpack\lib\Watching.js:77:18
    at AsyncSeriesHook.eval [as callAsync] (eval at create (...\myapp\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (...\myapp\node_modules\tapable\lib\Hook.js:154:20)
    at Watching._go (...\myapp\node_modules\@vue\cli-service\node_modules\webpack\lib\Watching.js:41:32)
    at ...\myapp\node_modules\@vue\cli-service\node_modules\webpack\lib\Watching.js:33:9
    at Compiler.readRecords (...\myapp\node_modules\@vue\cli-service\node_modules\webpack\lib\Compiler.js:529:11)
```

**System**
```
>npx sb info

Environment Info:

  System:
    OS: Windows 10 10.0.19043
    CPU: (4) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
  Binaries:
    Node: 16.13.0 - C:\nodist\bin\node.EXE
    Yarn: 1.22.17 - C:\nodist\bin\yarn.CMD
    npm: 8.1.2 - C:\nodist\bin\npm.CMD
  Browsers:
    Chrome: 95.0.4638.54
    Edge: Spartan (44.19041.1266.0), Chromium (95.0.1020.30)
  npmPackages:
    @storybook/addon-a11y: ^6.3.12 => 6.3.12
    @storybook/addon-actions: ^6.3.12 => 6.3.12
    @storybook/addon-docs: ^6.3.12 => 6.3.12
    @storybook/addon-essentials: ^6.3.12 => 6.3.12
    @storybook/addons: ^6.3.12 => 6.3.12
    @storybook/vue: ^6.3.12 => 6.3.12
```

**Additional context**
Note that this failure is both in Storybook and in Vue.  The @storybook/addon-docs depends on Webpack 4, and because "@storybook/…" is alphabetically before "@vue/…" then Webpack 4 gets installed in the root of the project, not Webpack 5.

**Comment by shilman** [comment]
Can you add webpack5 as a direct project dependency to force it to be hoisted?

**Comment by robrich** [comment]
I definitely /can/ but should I? For the novice user to Storybook, this seems an unnecessary and undocumented burden.

**Comment by shilman** [comment]
It's documented in MIGRATION.md. We still need to add proper webpack5 docs to storybook.js.org

**Comment by domyen** [comment]
The community is still migrating from webpack 4 to 5 with many projects on 4 still. That means Storybook has to support both while also transitioning ourselves.

It's going to take time/work, thanks for your patience. The dep recommendation from @shilman  seems like solid workaround for now (thanks!). 

I think we'd be open to making it more automated if you're interested in helping out?

**Comment by shilman** [comment]
I think at this point it's entirely a documentation issue. https://storybook.js.org/docs/react/contribute/documentation-updates

As far as I know we're hamstrung until 7.0. In 7.0, we should either make webpack5 the default or better yet make NO default and force the user to select a builder ("pay for exactly what you use"). In the meantime, any change to the "default to webpack4" setup is a breaking change. If there is a clever way to get to the desired state without a breaking change, I am very open to it. At the moment the plan is to release 6.4, followup in 6.5, and then 7.0 with 1.5 years worth of breaking changes, so it's not an ideal situation.

Happy to discuss ideas here or in Discord https://discord.gg/storybook

**Comment by ejpg** [comment]
Any updates on this? or any workaround? I just updated my Storybook and my dependencies, and Im having the same error 😓

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
