### ISSUE TITLE
Control labels as a function

### ISSUE THREAD

**Issue by Bilge** [storybookjs/storybook#16536]
**Is your feature request related to a problem? Please describe**
When there is a clear pattern-based mapping between a control's value and its label, it makes sense to apply a function to transform the value to the label, rather than specifying the literal mapping manually.

**Describe the solution you'd like**
```ts
export default {
    argTypes: {
        tier: {
            control: {
                type: 'inline-radio',
                labels: (value: string) => 'Tier ' + value,
            },
            options: [1, 2, 3],
        },
    },
} as Meta;
```

**Describe alternatives you've considered**
Manual mapping is less than ideal since labels have to be updated in addition to options, creating unnecessary work.

**Are you able to assist to bring the feature to reality?**
no

**Comment by shilman** [comment]
Storybook stringifies args/argTypes over a channel, so we prefer not to use functions. You should be able to implement this yourself as values using:

```js
const options = [1, 2, 3];
const labels = options.map((value: string) => 'Tier ' + value);

export default {
    argTypes: {
        tier: {
            control: {
                type: 'inline-radio',
                labels
            },
            optionsk 
        },
    },
} as Meta;
```
