### ISSUE TITLE
Disabling "Show Code" in CSF story does not work

### ISSUE THREAD

**Issue by neldeles** [storybookjs/storybook#16533]
**Describe the bug**
Setting `parameters.docs.source.code` to `null` or `''` does not disable the "Show code" source block in a Component Story Format story.

**To Reproduce**
Create story in CSF:
```
export default {
  title: "components/Test",
  component: Test,
  parameters: {
    docs: {
      source: {
        code: null,
      },
    },
  },
```

**System**
System:
    OS: macOS 11.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  Binaries:
    Node: 14.15.4 - /usr/local/bin/node
    Yarn: 3.1.0 - /usr/local/bin/yarn
    npm: 7.21.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 95.0.4638.54
    Edge: 95.0.1020.40
    Firefox: 79.0
    Safari: 15.0
  npmPackages:
    @storybook/addon-actions: ^6.4.0-beta.23 => 6.4.0-beta.23 
    @storybook/addon-docs: ^6.4.0-beta.23 => 6.4.0-beta.23 
    @storybook/addon-essentials: ^6.4.0-beta.23 => 6.4.0-beta.23 
    @storybook/addon-links: ^6.4.0-beta.23 => 6.4.0-beta.23 
    @storybook/node-logger: ^6.4.0-beta.23 => 6.4.0-beta.23 
    @storybook/preset-create-react-app: ^3.2.0 => 3.2.0 
    @storybook/react: ^6.4.0-beta.23 => 6.4.0-beta.23

**Additional context**
Discord discussion of the issue:
https://discord.com/channels/486522875931656193/604333220703633427/900266481756016690

**Comment by shilman** [comment]
Gadzooks!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-beta.29 containing PR #16615 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
