### ISSUE TITLE
Code snippet in Source block returns `<bound Template />` instead of the nested Story.

### ISSUE THREAD

**Issue by neldeles** [storybookjs/storybook#16534]
**Describe the bug**
For Stories with multiple components, the docs recommends re-using stories. However following this method, the rendered code snippet in the Source block becomes `<bound Template />`.  

<img width="1045" alt="CleanShot-2021-10-31-at-15 46 20@2x" src="https://user-images.githubusercontent.com/14298160/139573454-474d4fa0-845f-49cf-a1b0-fbf677901b82.png">

The expected output is:

<img width="1024" alt="CleanShot-2021-10-31-at-15 47 20@2x" src="https://user-images.githubusercontent.com/14298160/139573478-b0237a5c-132a-4aa3-b839-dc2fb9b24197.png">

**To Reproduce**
Repository: https://github.com/neldeles/sb-bound-issue

Deployed reproduction: https://617e455ce88637004aa0bec7-xasjwxlcue.chromatic.com/?path=/docs/components-molecules-navigation--using-story-args-only

**System**
System:
    OS: macOS 11.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  Binaries:
    Node: 14.15.4 - /usr/local/bin/node
    Yarn: 3.1.0 - /usr/local/bin/yarn
    npm: 7.21.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 95.0.4638.54
    Edge: 95.0.1020.40
    Firefox: 79.0
    Safari: 15.0
  npmPackages:
    @storybook/addon-actions: ^6.4.0-beta.23 => 6.4.0-beta.23 
    @storybook/addon-docs: ^6.4.0-beta.23 => 6.4.0-beta.23 
    @storybook/addon-essentials: ^6.4.0-beta.23 => 6.4.0-beta.23 
    @storybook/addon-links: ^6.4.0-beta.23 => 6.4.0-beta.23 
    @storybook/node-logger: ^6.4.0-beta.23 => 6.4.0-beta.23 
    @storybook/preset-create-react-app: ^3.2.0 => 3.2.0 
    @storybook/react: ^6.4.0-beta.23 => 6.4.0-beta.23

**Additional context**
I've found that the problem shows up when you re-use/render the story as you would a React component: 

```jsx
import {ImportedStory} from '../SomeComponent/SomeComponent.stories.js'

export const ReusedStoryAsComponent = Template.bind({});
ReusedStoryAsComponent.args = {
  children: <ImportedStory {...ImportedStory.args} />,
};
``` 

My current workaround is to use the Story's args as props, and import the actual component. This seems to render the expected code snippet:

```jsx
import {SomeComponent} from '../SomeComponent'
import {ImportedStory} from '../SomeComponent/SomeComponent.stories.js'

export const UsingStoryArgsOnly = Template.bind({});
UsingStoryArgsOnly.args = {
  children: <SomeComponent {...ImportedStory.args} />,
};
``` 

The above seems to explains why following both [Reusing subcomponent stories
](https://storybook.js.org/docs/react/workflows/stories-for-multiple-components#reusing-subcomponent-stories) and [Using children as an arg](https://storybook.js.org/docs/react/workflows/stories-for-multiple-components#using-children-as-an-arg) reproduce the bug. Whereas [Creating a Template Component](https://storybook.js.org/docs/react/workflows/stories-for-multiple-components#creating-a-template-component) returns the expected results. The former rendering the story as component and the latter using story args only.

**Comment by D1no** [comment]
Exact same problem. Following [the documentation](https://storybook.js.org/docs/react/writing-stories/stories-for-multiple-components). 
![image](https://user-images.githubusercontent.com/2397125/162843594-329df969-973e-42fe-b3e0-3cdfa601b605.png)

### Providing Story `Record`
```typescript
import { ComponentMeta, ComponentStory } from "@storybook/react";

import Component from "./index";

export default {
  component: Component,
} as ComponentMeta<typeof Component>;

const Template: ComponentStory<typeof Component> = (args) => (
  <Component {...args} />
);

export const Index = Template.bind({});
Index.args = { title: "Example Inc." };
```

### Consuming Story `Section`
```typescript
import { ComponentMeta, ComponentStory } from "@storybook/react";

import Record from "@cv/containers/facets/Record";
import { Index as RecordStory } from "@cv/containers/facets/Record/index.stories";

import { default as Component } from "./index";

export default {
  component: Component,
  subcomponents: { Record },     // <----------------------------------------- 👋  Here
} as ComponentMeta<typeof Component>;

const Template: ComponentStory<typeof Component> = (args) => (
  <Component {...args}>
    <RecordStory {...RecordStory.args} />     // <---------------------------- 👋  Here
  </Component>
);

export const Index = Template.bind({});
Index.args = {
  heading: "Honours & Media",
};
```

### Storybook Version (latest)
```package.json
    "react": "18.0.0",
    "react-dom": "18.0.0",

    "@storybook/addon-actions": "6.4.21",
    "@storybook/addon-docs": "6.4.21",
    "@storybook/addon-essentials": "6.4.21",
    "@storybook/addon-interactions": "6.4.21",
    "@storybook/addon-links": "6.4.21",
    "@storybook/builder-webpack5": "6.4.21",
    "@storybook/core-common": "6.4.21",
    "@storybook/manager-webpack5": "6.4.21",
    "@storybook/node-logger": "6.4.21",
    "@storybook/preset-create-react-app": "4.1.0",
    "@storybook/react": "6.4.21",
    "@storybook/testing-library": "0.0.9",
```

### Result
![image](https://user-images.githubusercontent.com/2397125/162844404-4b5eb61e-36df-492a-b757-889f7a35eb9c.png)

**Comment by marckraw** [comment]
Also looking forward to solution to that problem. That's great that we can compose component stories from other stories, but if we can't really show "real" code, that some other would like to use, than it's kinda useless imho.

**Comment by katzila** [comment]
Hello, guys! Exact same problem. Anyone found the solution? I also have tried to use some non-story template components but still to no avail

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
