### ISSUE TITLE
react-router broken in angular12

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#16552]
**Describe the bug**

Running an angular repro with 6.4.0-beta.25 results in the error:

```
{
  rawMessage: `ERROR TS2305: Module '"history"' has no exported member 'State'.`,
  message: '\x1B[1m\x1B[31mERROR in \x1B[39m\x1B[22m\x1B[1m\x1B[36m/Users/shilman/projects/testing/angular-error/node_modules/react-router-dom/index.d.ts(3,15)\x1B[39m\x1B[22m\x1B[1m\x1B[31m:\x1B[39m\x1B[22m\n' +
    `\x1B[90mTS2305: \x1B[39mModule '"history"' has no exported member 'State'.`,
  location: { line: 3, character: 15 },
  file: '/Users/shilman/projects/testing/angular-error/node_modules/react-router-dom/index.d.ts'
}
```

I believe this is a result of https://github.com/storybookjs/storybook/pull/16440

This is NOT a problem in a `react` or `vue3` project (didn't try others).

**To Reproduce**

```
npx sb@next repro -t angular angular-error
```

or 

https://stackblitz.com/github/storybookjs/repro-templates/tree/next/angular?preset=node

**Comment by ndelangen** [comment]
arg... it's been removed in a patch version...

![Screenshot 2021-11-02 at 11 58 04](https://user-images.githubusercontent.com/3070389/139834317-256f688e-723d-4006-83aa-6e07c0ef4fa2.png)

**Comment by ndelangen** [comment]
A issue has been created:
https://github.com/remix-run/history/issues/903

**Comment by ndelangen** [comment]
upgrading to ^6.0.0-beta.8 should fix this...

**Comment by shilman** [comment]
Hurrah!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-beta.26 containing PR #16554 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by bmayen** [comment]
can confirm that reverting to beta.18 works in the meantime

**Comment by ndelangen** [comment]
Damnit, I guess I have to version lock the version of `history` to `5.0.0` exactly then?

**Comment by ndelangen** [comment]
```
➤ YN0018: │ react-router-dom@npm:6.0.0-beta.8: The remote archive doesn't match the expected checksum
➤ YN0018: │ react-router@npm:6.0.0-beta.8: The remote archive doesn't match the expected checksum
```

???

**Comment by shilman** [comment]
Shiver me timbers!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-beta.27 containing PR #16560 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by bmayen** [comment]
Thank you!
