### ISSUE TITLE
When using an `.mdx` file along a `.stories.tsx` file, can't link  `<ArgsTable/>` to component or stories.

### ISSUE THREAD

**Issue by gurdilou** [storybookjs/storybook#16569]
**Describe the bug**
When using an `.mdx` file along a `.stories.tsx` file, can't link  `<ArgsTable/>` to component or stories.

**To Reproduce**
I created a simple repo containing an single story that illustrate the bug: https://github.com/gurdilou/storybook-repro

- Run `yarn storybook`
- Open [storybook in a browser](http://localhost:6006/?path=/docs/example-button--primary)
- Go to "Docs" tab

=> Page describes the problem

**System**
  System:
    OS: Linux 5.13 Ubuntu 21.10 21.10 (Impish Indri)
    CPU: (16) x64 Intel(R) Core(TM) i9-10885H CPU @ 2.40GHz
  Binaries:
    Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
    Yarn: 3.1.0 - ~/.nvm/versions/node/v14.17.0/bin/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm
  Browsers:
    Chrome: 94.0.4606.61
    Firefox: 93.0
  npmPackages:
    @storybook/addon-actions: ^6.4.0-beta.26 => 6.4.0-beta.26 
    @storybook/addon-docs: ^6.4.0-beta.26 => 6.4.0-beta.26 
    @storybook/addon-essentials: ^6.4.0-beta.26 => 6.4.0-beta.26 
    @storybook/addon-links: ^6.4.0-beta.26 => 6.4.0-beta.26 
    @storybook/node-logger: ^6.4.0-beta.26 => 6.4.0-beta.26 
    @storybook/preset-create-react-app: ^3.2.0 => 3.2.0 
    @storybook/react: ^6.4.0-beta.26 => 6.4.0-beta.26 

**Additional context**
It is linked to deeper investigation I made to resolve: #16494

**Comment by tigfamon** [comment]
Same problem here

**Comment by poolyumlim** [comment]
Same problem here too

**Comment by shilman** [comment]
Please try upgrading to the latest prerelease. We've updated the way docs linking dramatically in 7.0.

- Migration guide: https://storybook.js.org/migration-guides/7.0
- 7.0 docs documentation: https://storybook.js.org/docs/7.0/react/writing-docs/introduction

Closing this for now. If you are still unable to get it working in the new structure, please open an issue or chat us in Discord https://discord.gg/storybook and we'd be happy to help out.
