### ISSUE TITLE
Provide an option in the controls addon to hide the dynamic controls

### ISSUE THREAD

**Issue by phunkren** [storybookjs/storybook#16579]
**Is your feature request related to a problem? Please describe**
I do not want the user to have access to dynamic controls. 
I only want to showcase the prop name, type, default value, etc.

**Describe the solution you'd like**
What would you like to see added to Storybook to solve problem?
I would like an option to exist that hides the dynamic controls from the ArgsTable.

**Are you able to assist to bring the feature to reality?**
Sure!

**Additional context**
https://discord.com/channels/486522875931656193/549981762416017426/905509656938561626

**Comment by shilman** [comment]
Hey @phunkren sorry I've been totally slammed with the 6.4 release. Can you propose an API that I can react to?

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if this is still relevant in SB 7.x.
