### ISSUE TITLE
node v17.0.1 react@next [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports"

### ISSUE THREAD

**Issue by calbrecht** [storybookjs/storybook#16623]
Similar to https://github.com/storybookjs/storybook/issues/16180 there is a problem with `react@next` a.k.a. (`react@18.0.0-alpha-...`), where the `"exports"` field was added to the `package.json`.

Storybook tries to resolve `react/package.json` in [lib/ui](https://github.com/storybookjs/storybook/blob/main/lib/ui/paths.js), [builder-webpack5](https://github.com/storybookjs/storybook/blob/main/lib/builder-webpack5/src/preview/iframe-webpack.config.ts#L200) and [builder-webpack4](https://github.com/storybookjs/storybook/blob/main/lib/builder-webpack4/src/preview/iframe-webpack.config.ts#L203)

`node v12.22.7` is fine.
`node v14.18.1` is fine.
`node v16.13.0` succeed with a warning.
```
node16 --eval 'require.resolve("react/package.json")'
(node:624999) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at ...
```

`node v17.0.1` throws an error.
```
node17 --eval 'require.resolve("react/package.json")'
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in  ...
```

A possible solution for this specific `react/package.json` problem could be to just resolve the pkg name as in `react` instead of `react/package.json`.
```
node17 --eval 'require.resolve("react")'
// no error
```
Allthough this still might be broken should `react` choose to export a different subdirectory as its main entry.

Further context is available at https://github.com/nodejs/node/issues/33460

**Comment by Jack-Works** [comment]
Hi this need to be fixed because it's no longer a warning but an fatal error in Node 17

**Comment by laurenthiernard** [comment]
still happening, I'm running the demo proejct https://storybook.js.org/tutorials/intro-to-storybook/react/en/get-started/
node v17.3.0

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
