### ISSUE TITLE
Settings from localStorage/sessionStorage override setConfig() options

### ISSUE THREAD

**Issue by TrevorBurnham** [storybookjs/storybook#16627]
**Describe the bug**
In my Storybook, I try to set the panel position to `'right'` on pageload using `addons.setConfig()`, as [documented](https://storybook.js.org/docs/react/configure/features-and-behavior):

```js
// .storybook/manager.js

import { addons } from '@storybook/addons';

addons.setConfig({
  panelPosition: 'right',
});
```

However, this is a no-op if the user changed the user's `localStorage` or `sessionStorage` contains a `panelPosition` value, as is very likely the case if they've interacted with a Storybook on the same domain.

**To Reproduce**
1. Clone https://github.com/TrevorBurnham/sb-localstorage-setconfig
2. `yarn && yarn storybook`
3. Navigate to http://localhost:6006/?path=/story/example-button--primary

Notice that the panel appears on the bottom, even though `addons.setConfig({panelPosition: 'right'})` runs, because the value in `sessionStorage` (also set in `manager.js` for the sake of demonstration) takes precedence.

**System**
Environment Info:

  System:
    OS: macOS 12.0.1
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 17.0.1 - ~/.volta/tools/image/node/17.0.1/bin/node
    npm: 8.1.3 - ~/.volta/tools/image/npm/8.1.3/bin/npm
  Browsers:
    Chrome: 95.0.4638.69
    Safari: 15.1

**Additional context**
(I'm not 100% sure, but I think the relevant line where the config is loaded from `localStorage`/`sessionStorage` (via [store2](https://github.com/nbubna/store)) is [here](https://github.com/storybookjs/storybook/blob/7064642e1aee7786c77fe735c064c0c29dbcee01/lib/api/src/store.ts#L58-L65).)

In ordinary usage, this behavior is probably fine, but there are special cases where it's undesirable. For example, when a Storybook is loaded in an iframe, it's important to be able to control the panel position (and other settings), regardless of the contents of `localStorage`/`sessionStorage`.

I think the ideal fix here would be to add a config flag that would prevent any config from being loaded from, or saved to, `localStorage`/`sessionStorage`. I've filed an issue with store2 to add a "fake mode" that would make this straightforward: https://github.com/nbubna/store/issues/94

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
