### ISSUE TITLE
Unable to Serve Static StoryBook Build Files on NextJS Production Build

### ISSUE THREAD

**Issue by ardiansyaherwin** [storybookjs/storybook#16625]
Currently I have an existing NextJS app running and I'd like to install the storybook within the existing app, so it will be accessed through https://myadomain.com/documentation. 

I've successfully set the build path to `./public/static/documentation` and it also can be accessed with https://myadomain.com/documentation, but the relative assets path is not working, it keeps showing errors that the js files is not loaded due to incorrect file path.

Here's my SB build script:
```
"build-storybook -c .storybook -o ./public/static/documentation"
```

and here's the error when I load https://myadomain.com/documentation.
<img width="544" alt="Screen Shot 2021-11-06 at 22 42 18" src="https://user-images.githubusercontent.com/2732220/140615374-e43cb6e1-7342-43c0-a6a0-6867a13f98d8.png">

Did I miss something? pls help

**Comment by meyer-mcmains** [comment]
@ardiansyaherwin In your webpack config for production try setting the `config.output.publicPath` to `/documentation/`

For example:
```javascript
const PUBLIC_PATH = '/documentation/';

module.exports = {
  managerWebpack: async (config, { configType }) => {
      // Set the publicPath for the static production build
      if (configType === 'PRODUCTION') config.output.publicPath = PUBLIC_PATH;
      // ... other stuff
      return config;
    },
  
  webpackFinal: async (config, { configType }) => {
      // `configType` has a value of 'DEVELOPMENT' or 'PRODUCTION'
  
      // Set the publicPath for the static production build
      if (configType === 'PRODUCTION') {
        config.output.publicPath = PUBLIC_PATH;
      }
     // ...other stuff
     return config;
  }
}
```

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
