### ISSUE TITLE
storySort does use V6 compatibility mode for both build and dev

### ISSUE THREAD

**Issue by seanmcintyre** [storybookjs/storybook#16638]
Using `6.4.0-beta.30`.

<hr />

**To Reproduce**

Using in `main.js`:
```
  features: {
    postcss: false,
    previewCsfV3: false,
    buildStoriesJson: true,
    storyStoreV7: false,
  }
```
running storybook dev with a `storySort` function that is written in V7 style yields this console error:
`Are you using a V7-style sort function in V6 compatibilty mode?`

building storybook with a `storySort` function that is written in V6 style yields this CLI error:
`Are you using a V6-style sort function in V7 mode?`

<hr />

**System**
```
  System:
    OS: macOS 11.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Binaries:
    Node: 14.17.3 - ~/.nvm/versions/node/v14.17.3/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.3/bin/npm
  Browsers:
    Chrome: 95.0.4638.69
    Firefox: 93.0
    Safari: 15.0
  npmPackages:
    @storybook/addon-a11y: 6.4.0-beta.30 => 6.4.0-beta.30 
    @storybook/addon-essentials: 6.4.0-beta.30 => 6.4.0-beta.30 
    @storybook/addon-postcss: ^2.0.0 => 2.0.0 
    @storybook/addon-storysource: 6.4.0-beta.30 => 6.4.0-beta.30 
    @storybook/builder-webpack5: 6.4.0-beta.30 => 6.4.0-beta.30 
    @storybook/components: 6.4.0-beta.30 => 6.4.0-beta.30 
    @storybook/manager-webpack5: 6.4.0-beta.30 => 6.4.0-beta.30 
    @storybook/react: 6.4.0-beta.30 => 6.4.0-beta.30 
    @storybook/theming: 6.4.0-beta.30 => 6.4.0-beta.30 

```

<hr />

**Minor aside!**

The console error: `Are you using a V7-style sort function in V6 compatibilty mode?` has a typo. "compatibilty" is misspelled.

**Comment by seanmcintyre** [comment]
Setting `buildStoriesJson: false` helped resolve the error, but my `storySort` function is now being ignored.

**Comment by shilman** [comment]
@seanmcintyre do you happen to have a reproduction handy?  If not, can you create one? See [how to create a repro](https://storybook.js.org/docs/react/contribute/how-to-reproduce). Thank you! 🙏

**Comment by shilman** [comment]
Boo-yah!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-rc.4 containing PR #16724 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
