### ISSUE TITLE
MDX Story copy button leads to DOMExeption when using Composition

### ISSUE THREAD

**Issue by SeverinFriede** [storybookjs/storybook#16642]
**Describe the bug**
We are using the `<Story>` tag in MDX stories. This offers the possibility to copy data by clicking on the copy-button in the lower right corner of the storybox. We are hosting our storybooks on Chromatic and using composition to combine them.
In the main storybook the copying works fine but in the other "composed" storybook you get a DOMException:
`DOMException: The Clipboard API has been blocked because of a permissions policy applied to the current document. See https://permanently-removed.invalid for more details.`

**To Reproduce**
Navigate to our storybook and click on the copy link: https://610a4178d778290041e02a3c-iscntexnqi.chromatic.com/?path=/docs/angular_content-icon--angular

**System**
    @storybook/addon-actions: ^6.3.9 => 6.3.9 
    @storybook/addon-docs: ^6.3.8 => 6.3.9 
    @storybook/addon-essentials: ^6.3.8 => 6.3.9 
    @storybook/addon-knobs: ~6.3.0 => 6.3.1 
    @storybook/addons: ^6.3.0 => 6.3.9 
    @storybook/angular: ~6.3.0 => 6.3.9 
    @storybook/builder-webpack5: ^6.3.4 => 6.3.9
    @storybook/html: ^6.3.0 => 6.3.9
    @storybook/manager-webpack5: ^6.3.4 => 6.3.9
    @storybook/preset-scss: ^1.0.3 => 1.0.3
    @storybook/react: ~6.3.0 => 6.3.9
    @storybook/theming: ^6.3.0 => 6.3.9

**Comment by jeco123** [comment]
Hi i have the same bug using the composition storybook (1 storybook composed by other storybook). When i open explicitly one of them it works independently.
```
DOMException: The Clipboard API has been blocked because of a permissions policy applied to the current document. See https://goo.gl/EuHzyv for more details.
```

my storybook verssion is ^6.4.19

**Comment by jamesmsk** [comment]
is there any updates on this? We have 3 setups (HTML, Vue, React) setup via Compositions. We have complaints for not functioning copy buttons on codeblocks outside the main storybook. 

Alternative: We currently are just hiding those buttons, but we had to do it at each storybook level's preview-head. It would be great to be able to effect the css from the top level storybook, but it doesn't seem to be that way.

**Comment by shilman** [comment]
Yippee!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-alpha.34 containing PR #18999 that references this issue. Upgrade today to the `@future` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by Nxtivision** [comment]
Hello @shilman ,

Is it possible to cherry-pick this PR #18999 to the next patch version of 6.5 ? 😄 Because my team is not ready for v7 and we use a lot of referenced Storybook with Chromatic and Nx. Or a possible workaround until v7 is stable ?

have a nice day !
