### ISSUE TITLE
Error: Conflict when trying to read staticDirs

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#16646]
On a fresh CRA install with the latest beta (caused by #15969):

```
ERR! Error: Conflict when trying to read staticDirs:
ERR! * Storybook's configuration option: 'staticDirs'
ERR! * Storybook's CLI flag: '--staticDir' or '-s'
```

**Comment by shilman** [comment]
Yee-haw!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-beta.31 containing PR #16649 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by ivanbanov** [comment]
Im using 

```
// main.js
module.exports = {
  staticDir: ['./static']
}
```

but the files are not loading :/ the CLI flag is still working as expected

**Comment by ivanbanov** [comment]
nevermind, it's typo
```diff
-  staticDir: ['./static']
+  staticDirs: ['./static']
```
