### ISSUE TITLE
Build generate files with old date - Oct 26, 1985

### ISSUE THREAD

**Issue by davidglezz** [storybookjs/storybook#16648]
### Discussed in https://github.com/storybookjs/storybook/discussions/15236

<div type='discussions-op-text'>

<sup>Originally posted by **ivansvlv** June 14, 2021</sup>
Hi 👋

While investigating errors with storybook deployment to S3, I've noticed that building Storybook produced files with an odd old date - Oct 26, 1985. It's caused a problem when deploying static files to AWS S3 with `aws s3 sync` because these files are not getting update, thus not being deployed, leaving the old ones.

<img width="1082" alt="storybook_build" src="https://user-images.githubusercontent.com/16175855/121913282-ee504500-cd39-11eb-8c36-41811cb39a89.png">

I'm using:
    **Node 16.3.0**

    "@storybook/addon-actions": "^6.3.0-beta.17",
    "@storybook/addon-essentials": "^6.3.0-beta.17",
    "@storybook/addon-links": "^6.3.0-beta.17",
    "@storybook/builder-webpack5": "^6.3.0-beta.17",
    "@storybook/manager-webpack5": "^6.3.0-beta.17",
    "@storybook/react": "^6.3.0-beta.17",
    "webpack": "^5.38.1"
</div>

**Comment by skysantalucial** [comment]
I'm having the same problem

**Comment by ndelangen** [comment]
@davidglezz can you verify this is still and issue?

Could you try the latest 7.0 beta?

**Comment by davidglezz** [comment]
I have not been able to reproduce the issue with the latest version 6. With v7 I have not tried it.
