### ISSUE TITLE
JSX story performance is significantly slower than MDX story

### ISSUE THREAD

**Issue by IPWright83** [storybookjs/storybook#16651]
I'm not 100% certain if you'd consider this a bug, but it doesn't feel like a question either so I thought I'd log it and see where we get to with a discussion about it.

**Describe the bug**
Essentially the performance of a JSX based story is significantly worse than an MDX based story. I have tested basically the same story, and the time for the page to load and render is as follows:

**MDX** file: 3.39s 
**JSX** file: 29.14s

I'm going to caveat this with, I expect this to be a CPU intensive story. I'm trying to render 100k data points onto a chart so there's a large data load happening, and then a fairly intensive render loop (however it's designed to keep the browser responsive). The performance of the first story feels ok, the latter however does not :(

**To Reproduce**
This is going to be really hard for me to reproduce, but I'm going to share a deployed example and link off to the stories to show their relative setup.

MDX story: https://ipwright83.github.io/chart-it/?path=/story/xycharts-progressive-rendering--progressive-rendering&args=width:500;height:500
JSX story: https://ipwright83.github.io/chart-it/?path=/story/xycharts-scatter--progresssive-rendering&args=width:500;height:500

Please create a reproduction by running `npx sb@next repro` and following the instructions. Read our [documentation](https://storybook.js.org/docs/react/contribute/how-to-reproduce) to learn more about creating reproductions.
Paste your repository and deployed reproduction here. We prioritize issues with reproductions over those without.

**System**
```
Environment Info:

  System:
    OS: Linux 5.11 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (12) x64 AMD Ryzen 5 3600X 6-Core Processor
  Binaries:
    Node: 12.22.7 - /usr/bin/node
    Yarn: 1.22.11 - /usr/bin/yarn
    npm: 6.14.15 - /usr/bin/npm
  Browsers:
    Chrome: 95.0.4638.69
    Firefox: 94.0
  npmPackages:
    @storybook/addon-actions: ^6.1.9 => 6.3.10 
    @storybook/addon-essentials: ^6.1.9 => 6.3.10 
    @storybook/addon-links: ^6.1.9 => 6.3.10 
    @storybook/react: ^6.1.9 => 6.3.10 
    @storybook/storybook-deployer: ^2.8.10 => 2.8.10
```

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
