### ISSUE TITLE
Copy canvas link does not copy the whole URL

### ISSUE THREAD

**Issue by domyen** [storybookjs/storybook#16668]
**Describe the bug**
In Storybook's UI, the copy canvas link does not copy the whole URL. It only copies this `iframe.html?id=avatar--large&args=`

 ![image](https://user-images.githubusercontent.com/263385/141313245-6da8ce1d-8104-4405-aa02-93251a332751.png)

**To Reproduce**
1. Navigate to a [published Storybook](https://5ccbc373887ca40020446347-zpudtxvobv.chromatic.com/?path=/story/avatar--large)
2. Click copy link
3. Paste into the browser address bar
4. See that the link is not whole

**Comment by shilman** [comment]
closing as dupe to #15604
