### ISSUE TITLE
Discord channel - invite invalid

### ISSUE THREAD

**Issue by gnesher** [storybookjs/storybook#16679]
**Describe the bug**
The link to the discord channel within github/the storybook documentation (https://storybook.js.org/support/) no longer works.

[screen shot of the error](https://ibb.co/VVQh13S) 

**To Reproduce**
Simply try to follow the link to the discord chat.

**System**
N/A

**Additional context**
I realize this isn't the best place for this - but the link isn't part of the documentation site (so can't be edited) and there's also a link on the github bug page

**Comment by jonniebigodes** [comment]
Thanks for bringing this to our attention @gnesher I've been testing this and it seems that the issue was upstream and is now fixed. Closing this for now. Let me know if the issue surfaces again. 

Have a great week!

Stay safe
