### ISSUE TITLE
Docs code snippet not working properly with vue on 6.3.x

### ISSUE THREAD

**Issue by kauanschaeffer** [storybookjs/storybook#16674]
**Describe the bug**
All docs code snippets are showing the whole export function istead of the component code preview. 
Example: 
![image](https://user-images.githubusercontent.com/75996650/141488077-7f3e03b1-7c4e-4ae1-8396-f83f73920906.png)

I noticed that other project with a previous version of storybook (6.1.x) is working properly.
Example:
![image](https://user-images.githubusercontent.com/75996650/141488209-35f5fbbe-83c5-49bc-a403-77a122cbe1c0.png)

I'm not quite sure why this is happening since the config on both projects are pretty much the same.

**To Reproduce**
I do have both projects deployed on netlify, the one with the newer version is [this](https://ayla-design-system.netlify.app/?path=/docs/components-base-button--primary-default) and the one with the older is [this](https://shared-components.netlify.app/?path=/docs/components-buttons-lsbuttontoggle--default)

**System**
```
Environment Info:
  System
    OS: Linux 5.4 Linux Mint 20 (Ulyana)
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
  Binaries:
    Node: 12.9.0 - ~/.nvm/versions/node/v12.9.0/bin/node
    Yarn: 1.22.15 - ~/.yarn/bin/yarn
    npm: 6.10.2 - ~/.nvm/versions/node/v12.9.0/bin/npm
  Browsers:
    Chrome: 95.0.4638.69
    Firefox: 88.0.1
  npmPackages:
    @storybook/addon-actions: ^6.3.12 => 6.3.12 
    @storybook/addon-essentials: ^6.3.12 => 6.3.12 
    @storybook/addon-links: ^6.3.12 => 6.3.12 
    @storybook/addons: ^6.3.12 => 6.3.12 
    @storybook/testing-vue: ^0.0.2 => 0.0.2 
    @storybook/theming: ^6.3.12 => 6.3.12 
    @storybook/vue: ^6.3.12 => 6.3.12 
```

**Comment by shilman** [comment]
Do you a have a reproduction repo you can share? If not, can you create one? See [how to create a repro](https://storybook.js.org/docs/react/contribute/how-to-reproduce). Thank you! 🙏

**Comment by kauanschaeffer** [comment]
I couldn't reproduce the issue on a repro project, not sure why. The repro project is using the beta version 6.4.0-rc.3, not sure if this is fixed in this one.

By the way, I updated the project I'm using the previous version of storybook to the current one, just to see if the issue would happen, and it did.

**Comment by awacode21** [comment]
i am experiencing the same problem.
