### ISSUE TITLE
Module not found: Can't resolve '@storybook/react/types-6-0'

### ISSUE THREAD

**Issue by gvocale** [storybookjs/storybook#16672]
**Describe the bug**
After upgrading to Next 12, when running Cypress component tests I get the following error. This only happens during Cypress component test. Cypress component test is using `import { composeStories } from "@storybook/testing-react";` to import and test the story. Has anyone run into this issue before?

Downgrading to Next 11 solves the issue.

```tsx
Module not found: Can't resolve '@storybook/react/types-6-0'
```

**Comment by yannbf** [comment]
Hey @gvocale thanks for opening this issue. I'll close it since it really belongs to storybookjs/testing-react. I answered you there!
