### ISSUE TITLE
Complex object arg can cause cyclic structures JSON.serialize error

### ISSUE THREAD

**Issue by literalpie** [storybookjs/storybook#16688]
**Describe the bug**
Passing certain kinds of objects as args can cause the error:

> JSON.stringify cannot serialize cyclic structures

I am specifically seeing this when passing an object that has an observable that has been subscribed to.

**To Reproduce**
See [this minimal repro](https://github.com/literalpie/sb-ng-performance/tree/object-arg)
The important part is that I made a `SelectionModel` object, subscribed to changes in the object, then passed the object as an arg for a story:
```
const selectionModel = new SelectionModel();
selectionModel.changed.subscribe(_ => {
  console.log('selection model change');
})

export const LoggedIn = Template.bind({});
LoggedIn.args = {
  user: {},
  selection: selectionModel,
};
```
You will only see the issue if you open the story in the storybook canvas, then change to the docs tab or change an arg. This causes the page to go white and the error will be thrown.

**System**
System:
    OS: macOS 11.6.1
    CPU: (12) x64 Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz
  Binaries:
    Node: 16.11.1 - ~/.nvm/versions/node/v16.11.1/bin/node
    Yarn: 3.0.1 - /usr/local/bin/yarn
    npm: 8.0.0 - ~/.nvm/versions/node/v16.11.1/bin/npm
  Browsers:
    Chrome: 95.0.4638.69
    Firefox: 94.0.1
    Safari: 15.1
  npmPackages:
    @storybook/addon-a11y: ^6.4.0-rc.1 => 6.4.0-rc.1 
    @storybook/addon-actions: ^6.4.0-rc.1 => 6.4.0-rc.1 
    @storybook/addon-docs: ^6.4.0-rc.1 => 6.4.0-rc.1 
    @storybook/addon-essentials: ^6.4.0-rc.1 => 6.4.0-rc.1 
    @storybook/addon-links: ^6.4.0-rc.1 => 6.4.0-rc.1 
    @storybook/angular: ^6.4.0-rc.1 => 6.4.0-rc.1 
    @storybook/builder-webpack5: ^6.4.0-rc.1 => 6.4.0-rc.1 
    @storybook/manager-webpack5: ^6.4.0-rc.1 => 6.4.0-rc.1 
    @storybook/preview-web: ^6.4.0-rc.1 => 6.4.0-rc.1

I also confirmed that this is an issue in the stable version of storybook in my minimal repro (6.3.12). 

**Additional context**
* On the large storybook project where I originally found this issue, it is only a problem when storyStoreV7 turned on. Not sure why since the minimal reproduction does _not_ require storyStoreV7 to be turned on to see the error.
* It's probably not a best practice to pass a complex object like this as an arg. But I think this is the only way to reference an object in a story template. (We may work around this by making a demo component that declares the object)

**Comment by literalpie** [comment]
Another workaround:
```
  argTypes: {
    selection: { table: { disable: true } },
  },
```
This is probably what we will do for now.

**Comment by shilman** [comment]
Check out the mapping feature which is designed for this kind of use case

https://storybook.js.org/docs/react/writing-stories/args#mapping-to-complex-arg-values

**Comment by literalpie** [comment]
Nice, That's even better!

I'm happy with closing this issue if you want since the error was only caused by us doing non-recommended patterns. Maybe the existence of this issue will help others in the future.

On the other hand, it might be worth considering handling this case better. Maybe showing 'complex object', 'circular object' or 'invalid value' in the panel where the object value would normally be shown. Or just having a nicer error that tells the user "You may have tried to pass a complex object as an arg for one of your stories. Consider using argTypes.mapping to set the value"
