### ISSUE TITLE
CLI: Automigrate breaks eslintrc if "extends" is a string

### ISSUE THREAD

**Issue by dannyhw** [storybookjs/storybook#16686]
**Describe the bug**

in my project I have `extends: '@react-native-community',` when automatically adding the eslint plugin the string is split into individual characters
like this:
```
extends: ["@", "r", "e", "a", "c", "t", "-", "n", "a", "t", "i", "v", "e", "-", "c", "o", "m", "m", "u", "n", "i", "t", "y", "plugin:storybook/recommended"]
```

**To Reproduce**

`npx sb@next upgrade -p` on a project with a string in extends field of eslint config.

**System**

Environment Info:

  System:
    OS: macOS 11.5.2
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v14.18.1/bin/yarn
    npm: 8.1.1 - ~/.nvm/versions/node/v14.18.1/bin/npm
  Browsers:
    Chrome: 95.0.4638.69
    Safari: 14.1.2
  npmPackages:
    @storybook/addon-actions: ^6.4.0-rc.1 => 6.4.0-rc.1 
    @storybook/addon-essentials: 6.4.0-rc.1 => 6.4.0-rc.1 
    @storybook/addon-links: ^6.4.0-rc.1 => 6.4.0-rc.1 
    @storybook/react: 6.4.0-rc.1 => 6.4.0-rc.1 

**Additional context**

Seems like the auto upgrade thing is expecting an array, just need to check if its a string probably.

**Comment by yannbf** [comment]
Thanks for reporting this @dannyhw ! I opened a PR to fix it :)

**Comment by shilman** [comment]
Ooh-la-la!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-rc.2 containing PR #16687 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
