### ISSUE TITLE
Storybook UI unable to pickup Lit library's changes made during @slotchange

### ISSUE THREAD

**Issue by amitshaiwale** [storybookjs/storybook#16682]
**Describe the bug**

- We are working on building web components using Lit library.
- We have a component, which has flags, which are toggled between true and false on @slotchange event. This event in addition decides whether or not certain CSS classes to be applied on an element.
- This behavior works well in local instance, however when the same is rendered in Storybook UI, the CSS classes which are expected to be applied on an element on @slotchange are not applied. 

Expected : `<div class="some-class"> . . .</div>` [.some-class is defined in CSS file]
Actual : `<div class> . . . </div>`

**System**
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz
  Binaries:
    Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (95.0.1020.53)
  npmPackages:
    @storybook/addon-actions: ^6.3.1 => 6.3.1
    @storybook/addon-controls: ^6.3.1 => 6.3.1
    @storybook/addon-docs: ^6.3.1 => 6.3.1
    @storybook/addon-essentials: ^6.3.1 => 6.3.1
    @storybook/addon-links: ^6.3.1 => 6.3.1
    @storybook/addon-postcss: ^2.0.0 => 2.0.0
    @storybook/builder-webpack5: ^6.4.0-alpha.7 => 6.4.0-alpha.7
    @storybook/manager-webpack5: ^6.4.0-alpha.7 => 6.4.0-alpha.7
    @storybook/preset-scss: ^1.0.3 => 1.0.3
    @storybook/semver: ^7.3.2 => 7.3.2
    @storybook/theming: ^6.3.4 => 6.3.4
    @storybook/web-components: ^6.3.1 => 6.3.1

**Additional context**
This issue has blocked us from further progress with Storybook.
Any kind of support here would help us make further progress.

**Comment by shilman** [comment]
Unrelated to this issue but FYI all of your storybook package versions should match.

You can do this automatically (recommended) by:
- stable: `npx sb upgrade`
- prerelease: `npx sb upgrade --prerelease`

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
