### ISSUE TITLE
Storyshoot + NextJs + multiSnapshotWithOptions

### ISSUE THREAD

**Issue by smigfu** [storybookjs/storybook#16692]
**Is your feature request related to a problem? Please describe**
I am using nextjs's default folder structure (components, pages, ..) with storyshoot and `multiSnapshotWithOptions`. The created snapshot files end up in wrong directory (parent directory). I.e. I have a story in `./components/auth/login.stories.tsx` and the corresponding snapshot ends up in `./auth/login.stories.tsx`. I tried the `Stories2SnapsConverter` but the `context`'s `fileName` points to `./auth/login.stories.tsx`.

**Describe the solution you'd like**
The snapshots should show up side by side with the story in the right directory.

**Describe alternatives you've considered**
N/A

**Are you able to assist to bring the feature to reality?**
No

**Additional context**
N/A

**Comment by patrick-mcdougle** [comment]
I ran into this today. The problem is that the story path is generated from the jest rootDir, but the snapshot directory becomes the root of where the snapshots are placed, so you end up getting extra (overlapping) pathing.

I "solved" this by hacking the initStoryshots test option to resolve the paths relative to the correct directory. Someone who has more time could solve this more generally / sustainably (and let me know, because I'd also like to know).

```
const path = require('path');
initStoryshots({
  test: (story) => {
    // This adjusts for the fact that the story path is jest config relative,
    // but the storyshot write path is relative to where this file is.
    const snapshotFileName = path.resolve(
      __dirname,
      "../..", // go backwards so when we go forwards again we end up in the right place.
      story.stories2snapsConverter.getSnapshotFileName(story.context)
    );
    return snapshotWithOptions()({ ...story, snapshotFileName });
  },
});
```
Others using this hack might need to alter the number of `..`s to reflect the number of directories your file is nested relative to the jest rootDir.

**Comment by marek-saji** [comment]
A workaround not dependent on your storyshots test location:

```js
import path from 'path'

import initStoryshots, {
  multiSnapshotWithOptions,
} from '@storybook/addon-storyshots'

initStoryshots({
  test: (story) => {
    // FIXME Workaround for https://github.com/storybookjs/storybook/issues/16692
    const fileName = path.resolve(__dirname, '..', story.context.fileName)
    return multiSnapshotWithOptions()({
      ...story,
      context: { ...story.context, fileName },
    })
  },
})
```

**Comment by patrick-mcdougle** [comment]
^ this could probably be the fix in the actual code.

**Comment by jmatsuzaki** [comment]
I encountered the same error today and this @marek-saji 's answer fixed it for me. Thank you.

**Comment by ndelangen** [comment]
The future of storyshots is the test-runner:
https://storybook.js.org/docs/react/writing-tests/test-runner#page-top

And use the play function for expectations:
https://storybook.js.org/docs/react/writing-stories/play-function#page-top

We will not be making any improvement / changes to storyshots.
