### ISSUE TITLE
storybook using older version of react-dev-utils i.e, 11.0.3

### ISSUE THREAD

**Issue by nikhitha1206** [storybookjs/storybook#16700]
Hi
when I used storybook , the version of react-dev-utils which I got is v11.0.3  , as the older version of react-dev-utils uses immer of version 8.0.1 which has type confusion vulnerability , it is effecting my work kindly resolve this issue.

**Comment by shilman** [comment]
Try upgrading to the latest prerelease:

```
npx sb@next upgrade --prerelease
```

Does that fix it?

**Comment by nikhithabaker** [comment]
After running "npx sb@next upgrade --prerelease" , react-dev-utils updated to 11.0.4 but it using immer of v8.0.1 instead of v9.0.6

**Comment by nikhitha1206** [comment]
After running "npx sb@next upgrade --prerelease" , react-dev-utils updated to 11.0.4 but it using immer of v8.0.1 instead of v9.0.6.

**Comment by shilman** [comment]
that's the latest release of `react-dev-utils` unfortunately

**Comment by PeteMac88** [comment]
I have the same vulnerability alert. What I dont get is that in react-dev-utils@11.0.4 the immer version is 9.0.6.

**Comment by nikhitha1206** [comment]
Our organization doesn't allow us to work with pre-release version. when are you planning to release latest version of storybook

**Comment by shilman** [comment]
In the next couple weeks

**Comment by JoeImpact** [comment]
Would it be safe to say that this vulnerability only exists in Storybook and that an app that only has Storybook in devDependencies would not be vulnerable?

**Comment by shilman** [comment]
@JoeImpact My recollection is that it's not even a true vulnerability in storybook based on how it's used, but I'm not 100% on that

**Comment by bdefore** [comment]
PR to follow for react-dev-utils to resolve this https://github.com/facebook/create-react-app/issues/11701

**Comment by robertwbradford** [comment]
[react-dev-utils](https://www.npmjs.com/package/react-dev-utils) has published v12. Could `@storybook/react` now be updated to use it?

**Comment by shilman** [comment]
closing as dupe to #16093
