### ISSUE TITLE
Arrow keys don't work on number controls

### ISSUE THREAD

**Issue by andrewplummer** [storybookjs/storybook#16701]
It seems that the manager app calls `preventDefault` on arrow key events (for tree navigation), however this breaks key events on number inputs inside the controls. Presumably a simple `stopPropagation` on these inputs would fix the issue.

For now here's a workaround in `manager-head.html`:

```html
<script>
  // Hack to prevent key events not working on number controls
  document.documentElement.addEventListener('keydown', (evt) => {
    const { key } = evt;
    const { tagName, type } = evt.target;
    if (tagName === 'INPUT' && type === 'number') {
      const isArrow = key === 'ArrowDown' || key === 'ArrowUp';
      if (isArrow) {
        evt.stopPropagation();
      }
    }
  });
</script>
```

In `storybook-react@6.3.12`

**Comment by aritrakoley** [comment]
Hi, I would like to work on this. Which files should I be looking into?

**Comment by BikashSah999** [comment]
Hi @shilman @ndelangen , Can I work in this issue and what would be the desired behavior?

**Comment by shilman** [comment]
Good golly!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.0 containing PR #19954 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
