### ISSUE TITLE
Support Angular DevTools extension

### ISSUE THREAD

**Issue by archfisv** [storybookjs/storybook#16704]
**Is your feature request related to a problem? Please describe**
Angular DevTools is a nice tool delivered by Angular Team :). Can't use it now with Storybook! At least with 6.3.12.
Docs: https://angular.io/guide/devtools

**Describe the solution you'd like**
Add support :)

**Describe alternatives you've considered**
None.

**Are you able to assist to bring the feature to reality?**
Yes, I'll be able to confirm it works :)

**Additional context**
![image](https://user-images.githubusercontent.com/84845637/142051716-3b801737-e2ba-4afe-8956-c390cbee281a.png)

**Comment by literalpie** [comment]
Hi, can you try opening the story in a standalone tab (the middle icon in the top right of storybook)?
![image](https://user-images.githubusercontent.com/20398475/142919039-8d957a9e-b091-430f-8916-ce7290867037.png)
In the "full" storybook, Angular is run in an iframe, so the extension won't detect it.

**Comment by archfisv** [comment]
Hey @literalpie, thanks, works well.

**Comment by snortblt** [comment]
This solution doesn't seem to be working with Angular 19. All options are enabled in DevTools extension.
