### ISSUE TITLE
White overlay after upgrading from beta.32->beta.33

### ISSUE THREAD

**Issue by bmayen** [storybookjs/storybook#16717]
After upgrading past beta.32, my Docs initially load fine but are then covered by a white overlay a few seconds after rendering. If I inspect the DOM I see that #docs-root is set to display:none, but all of the expected content is in there. If I set it to display:block and manually delete sb-errordisplay, sb-nopreview, sb-preparingdocs, and sb-preparingstory divs above it, it displays as it should. 

This is introduced in beta.33 but exists through latest rc.3.

Environment Info:

  System:
    OS: macOS 11.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 14.17.6 - ~/.nvm/versions/node/v14.17.6/bin/node
    Yarn: 1.22.15 - ~/.nvm/versions/node/v14.17.6/bin/yarn
    npm: 7.24.2 - ~/XXXXXX/node_modules/.bin/npm
  Browsers:
    Chrome: 96.0.4664.45
    Firefox: 93.0
    Safari: 15.0
  npmPackages:
    @storybook/addon-a11y: 6.4.0-beta.33 => 6.4.0-beta.33
    @storybook/addon-backgrounds: 6.4.0-beta.33 => 6.4.0-beta.33
    @storybook/addon-docs: 6.4.0-beta.33 => 6.4.0-beta.33
    @storybook/addon-postcss: ^2.0.0 => 2.0.0
    @storybook/addon-viewport: 6.4.0-beta.33 => 6.4.0-beta.33
    @storybook/addons: 6.4.0-beta.33 => 6.4.0-beta.33
    @storybook/angular: 6.4.0-beta.33 => 6.4.0-beta.33
    @storybook/builder-webpack5: 6.4.0-beta.33 => 6.4.0-beta.33
    @storybook/manager-webpack5: 6.4.0-beta.33 => 6.4.0-beta.33
    @storybook/theming: 6.4.0-beta.33 => 6.4.0-beta.33

**Comment by shilman** [comment]
Try upgrading to the latest prerelease:

```
npx sb@next upgrade --prerelease
```

Does that fix it?

**Comment by bmayen** [comment]
Just tried rc.5. Same result. 
Seems to only happen on the initial page load. If I navigate to another story, everything displays as expected. If I refresh the page though, I get the white overlay again.

**Comment by shilman** [comment]
Do you a have a reproduction repo you can share? If not, can you create one? See [how to create a repro](https://storybook.js.org/docs/react/contribute/how-to-reproduce). Thank you! 🙏

**Comment by bmayen** [comment]
I should note, this is an Angular project. Didn't realize that wasn't included in the environment info above.

**Comment by bmayen** [comment]
Unfortunately, I can't share the source for the project I'm seeing this on. Will try to create a separate repro this weekend though

**Comment by bmayen** [comment]
Found the problem. In preview-head.html, I was setting additional classes on the body element. I was taking a naive approach to this using `document.body.className = ...`. I guess this was overwriting other required classes set by Storybook. Changing this to `document.querySelector('body').classList.add(...)` fixes it. Might want to make a note of this in the docs if this isn't already noted somewhere.
