### ISSUE TITLE
If only one component has issues displaying, only that should display an error and not all components

### ISSUE THREAD

**Issue by Braweria** [storybookjs/storybook#16720]
**Is your feature request related to a problem? Please describe**
While working with Storybook and creating new components, it often displays an error like this one:  

```
Unexpected default export without title: {"includeStories":[],"parameters":{"docs":{}}
```

Usually, because I haven't finished writing it. Now I wanted to go check another component's docs out, so I can see what props I need to pass, but the same error message appears. So I am unable to use Storybook unless this one story works perfectly as well.   

Personally, I find that annoying to work with because it means I have to either ditch the new component or just write correctly from the get-go without looking at the documentation.

**Describe the solution you'd like**
If there is only one story that has something wrong with it, then only this story should display an error and not every other component as well.

**Describe alternatives you've considered**
Right now I need to check the component in my code to see the props.

**Are you able to assist to bring the feature to reality?**
I am not familiar enough with Storybook to help in such a manner. I can test it, though.

**Additional context**
![image](https://user-images.githubusercontent.com/62669899/142375419-07b5ede5-a009-4f61-9772-ebebc9f96a07.png)

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if this is still relevant in SB 7.x.
