### ISSUE TITLE
Storybook 6.4.0-rc.5 Cannot use with react-router 5 - TypeError: pathname.match is not a function

### ISSUE THREAD

**Issue by VickyKoblinski** [storybookjs/storybook#16739]
**Describe the bug** 
react-router 6.x changes the `matchPath` function. This isn't really documented in their breaking changes or migration docs, but I ran into this same issue when trying to upgrade our codebase to react-router 6. It appears that using Storybook 6.4.0-rc.5 is causing my app to use the "new" matchPath from react-router 6. I don't experience this issue on Storybook 6.3.12 or lower.

![image](https://user-images.githubusercontent.com/2954384/142752026-807bb816-167f-4bd5-ae6a-e2a48c09498c.png)

**To Reproduce**
Create a `create-react-app` project with `react-router 5.x`. Use the `matchPath` utility function. Pass a string (path) in for the first argument, and an object `{ path: "/my/path" }` as the second argument. Start app and ensure it works. Install Storybook 6.4.0-rc.5. Start app and notice that the app no longer works.

**System**
```
Environment Info:

  System:
    OS: macOS 12.0.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 14.15.0 - ~/.nvm/versions/node/v14.15.0/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.0/bin/npm
  Browsers:
    Chrome: 96.0.4664.55
    Firefox: 84.0
    Safari: 15.1
  npmPackages:
    @storybook/addon-actions: ^6.4.0-rc.5 => 6.4.0-rc.5 
    @storybook/addon-essentials: ^6.4.0-rc.5 => 6.4.0-rc.5 
    @storybook/addon-links: ^6.4.0-rc.5 => 6.4.0-rc.5 
    @storybook/node-logger: ^6.4.0-rc.5 => 6.4.0-rc.5 
    @storybook/preset-create-react-app: ^3.2.0 => 3.2.0 
    @storybook/react: ^6.4.0-rc.5 => 6.4.0-rc.5 
```

**Additional context**
I'm so excited for the 6.4 goodies!!!!!!

**Comment by shilman** [comment]
This sounds like a yarn/npm hoisting issue. If you install React-router 5 as a direct dependency in your project root, does that fix things?

**Comment by VickyKoblinski** [comment]
That did the trick, thank you! I'm not sure why we didn't have that as a direct dependency to begin with. 🙃

**Comment by shilman** [comment]
Ok glad I could help. I'm going to close this then!
