### ISSUE TITLE
[Storybook 6.4] angular 13 uses rxjs7 for new projects (invalid peer dependency)

### ISSUE THREAD

**Issue by SnakeSVx** [storybookjs/storybook#16749]
### Describe the bug

Angular 13 now has support for both rxjs6 and rxjs 7 and default to 7 for new projects.
When adding storybook to the workspace an error pops up about incompatible peer dependencies.

![image](https://user-images.githubusercontent.com/271542/142847038-ecd8a691-f450-4386-9670-9f301af154e9.png)

![image](https://user-images.githubusercontent.com/271542/142847872-83cf252a-4458-4aaf-ad41-14213957d8e5.png)

### To Reproduce

Create an angular 13 project and add storybook.

**Comment by shilman** [comment]
Would updating the peer dependencies to include 7.x be sufficient to fix this?

**Comment by SnakeSVx** [comment]
From what I can tell everything in rxjs6 should keep working in 7. So it might be enough to just update the peer dependencies.

> There are many deprecations in RxJS 7, but, to make the upgrade easy, they haven’t deleted anything.

https://medium.com/volosoft/whats-new-in-rxjs-7-a11cc564c6c0

**Comment by shilman** [comment]
@SnakeSVx any chance you can submit a PR with that change?

**Comment by SnakeSVx** [comment]
@shilman I'll see what I can do and submit a PR if possible.

**Comment by literalpie** [comment]
Some testing may be needed to make sure the breaking changes in rxjs 7 don't break anything in the storybook code. For example, in our project, we had to update `let something = new Subject()` to `let something = new Subject<void>()` in a few places because the types of rxjs 7 are more strict. 
[rxjs 7 breaking changes](https://rxjs.dev/deprecations/breaking-changes)

**Comment by shilman** [comment]
w00t!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-rc.7 containing PR #16758 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by SnakeSVx** [comment]
Works like it should now. No peer dependency issues anymore.

**Comment by shilman** [comment]
Thanks so much for the fix & the verification @SnakeSVx !! 🙏
