### ISSUE TITLE
[Storybook 6.4] argTypeTargetsV7 breaks on stories without args

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#16743]
**Describe the bug**
![image](https://user-images.githubusercontent.com/1671563/142865043-c7eb201f-2aba-4747-80f3-da23b05f5ebb.png)

**To Reproduce**
1 - Go to `react-ts`

2 - Enable argTypeTargetsV7:
```js
  features: {
    argTypeTargetsV7: true,
  },
```

3 - Run react-ts storybook

3 - Go to http://localhost:9011/?path=/story/examples-emoji-button--basic

4 - Get the error. This is the story that causes the error:
```jsx
export const Basic = () => <EmojiButton label="Click me" />;
```

It actually happens with any story that does not define args or argTypes, be it CSF1 2 or 3.

Things should break because `context.args` is undefined here:
https://github.com/storybookjs/storybook/blob/next/lib/store/src/prepareStory.ts#L169

**Comment by tmeasday** [comment]
🤔 hmm, why would `context.args` be undefined. I think it should always be defined... Will see if I can repro @yannbf

**Comment by tmeasday** [comment]
@yannbf is there something different you are doing here? I am not seeing it:

```js
export const CSF1 = (args, context) => console.log(args, context) || <div>Hello</div>
```

![image](https://user-images.githubusercontent.com/132554/142802206-6ec2b9d1-74b8-44c7-a3d9-0edeae170257.png)

**Comment by yannbf** [comment]
Hey @tmeasday I've got a simple way to reproduce it in the monorepo, I updated the steps in the issue description. Hope it helps!

**Comment by tmeasday** [comment]
Ahh, got it, the component I was testing had some auto-generated `argTypes` 🤦

**Comment by shilman** [comment]
Jiminy cricket!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-rc.10 containing PR #16790 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
