### ISSUE TITLE
 HookWebpackError: ENOENT: no such file or directory, scandir at makeWebpackError while trying to run storybook

### ISSUE THREAD

**Issue by innoveltec** [storybookjs/storybook#16755]
Upgraded my angular nx repo(v13.2.1) to the newest version which is using storybook 6.4.0-rc.3. After that i have run the npx sb@next automigrate command which suggests me to install some webpack-5 dependencies and i also added the core builder property to webpack5 in my main.js file. Now when i try to run my storybook i am getting an error with the following stacktrace: 

[webpack-dev-middleware] HookWebpackError: ENOENT: no such file or directory, scandir
at makeWebpackError (C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\webpack\lib\HookWebpackError.js:48:9)
<e>     at C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\webpack\lib\Compilation.js:3055:12
<e>     at eval (eval at create (C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:31:1)
<e>     at fn (C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\webpack\lib\Compilation.js:478:17)
<e>     at _next5 (eval at create (C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:28:1)
<e>     at eval (eval at create (C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:46:1)
<e>     at fn (C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\webpack\lib\Compilation.js:490:9)
<e>     at _next4 (eval at create (C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:41:1)
<e>     at eval (eval at create (C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:59:1)
<e>     at eval (eval at create (C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:11:1)
<e>     at C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\webpack\lib\SourceMapDevToolPlugin.js:549:10
<e>     at C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\neo-async\async.js:2830:7
<e>     at Object.each (C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\neo-async\async.js:2857:9)
<e>     at C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\webpack\lib\SourceMapDevToolPlugin.js:384:17
<e>     at C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\neo-async\async.js:2830:7
<e>     at Object.each (C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\neo-async\async.js:2857:9)
<e> -- inner error --
<e> Error: ENOENT: no such file or directory, scandir
<e>     at Object.readdirSync (fs.js:1021:3)
<e>     at CacheBackend.provideSync (C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:233:32)
<e>     at WebpackFileSystem.listPaths (C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\license-webpack-plugin\dist\WebpackFileSystem.js:78:24)
<e>     at LicenseTextReader.readLicense (C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\license-webpack-plugin\dist\LicenseTextReader.js:37:54)
<e>     at PluginChunkReadHandler.processModule (C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\license-webpack-plugin\dist\PluginChunkReadHandler.js:46:62)
<e>     at C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\license-webpack-plugin\dist\PluginChunkReadHandler.js:22:23
<e>     at WebpackModuleFileIterator.internalCallback (C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\license-webpack-plugin\dist\WebpackModuleFileIterator.js:25:13)
<e>     at WebpackModuleFileIterator.iterateFiles (C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\license-webpack-plugin\dist\WebpackModuleFileIterator.js:10:9)
<e>     at C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\license-webpack-plugin\dist\PluginChunkReadHandler.js:20:32
<e>     at WebpackChunkModuleIterator.iterateModules (C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\license-webpack-plugin\dist\WebpackChunkModuleIterator.js:42:21)
<e>     at PluginChunkReadHandler.processChunk (C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\license-webpack-plugin\dist\PluginChunkReadHandler.js:19:29)
<e>     at _loop_1 (C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\license-webpack-plugin\dist\WebpackCompilerHandler.js:135:37)
<e>     at WebpackCompilerHandler.iterateChunks (C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\license-webpack-plugin\dist\WebpackCompilerHandler.js:160:17)
<e>     at C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\license-webpack-plugin\dist\WebpackCompilerHandler.js:50:31
<e>     at fn (C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\webpack\lib\Compilation.js:476:10)
<e>     at _next5 (eval at create (C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:28:1)
<e> caused by plugins in Compilation.hooks.processAssets
<e> Error: ENOENT: no such file or directory, scandir
<e>     at Object.readdirSync (fs.js:1021:3)
<e>     at CacheBackend.provideSync (C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:233:32)
<e>     at WebpackFileSystem.listPaths (C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\license-webpack-plugin\dist\WebpackFileSystem.js:78:24)
<e>     at LicenseTextReader.readLicense (C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\license-webpack-plugin\dist\LicenseTextReader.js:37:54)
<e>     at PluginChunkReadHandler.processModule (C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\license-webpack-plugin\dist\PluginChunkReadHandler.js:46:62)
<e>     at C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\license-webpack-plugin\dist\PluginChunkReadHandler.js:22:23
<e>     at WebpackModuleFileIterator.internalCallback (C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\license-webpack-plugin\dist\WebpackModuleFileIterator.js:25:13)
<e>     at WebpackModuleFileIterator.iterateFiles (C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\license-webpack-plugin\dist\WebpackModuleFileIterator.js:10:9)
<e>     at C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\license-webpack-plugin\dist\PluginChunkReadHandler.js:20:32
<e>     at WebpackChunkModuleIterator.iterateModules (C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\license-webpack-plugin\dist\WebpackChunkModuleIterator.js:42:21)
<e>     at PluginChunkReadHandler.processChunk (C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\license-webpack-plugin\dist\PluginChunkReadHandler.js:19:29)
<e>     at _loop_1 (C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\license-webpack-plugin\dist\WebpackCompilerHandler.js:135:37)
<e>     at WebpackCompilerHandler.iterateChunks (C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\license-webpack-plugin\dist\WebpackCompilerHandler.js:160:17)
<e>     at C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\license-webpack-plugin\dist\WebpackCompilerHandler.js:50:31
<e>     at fn (C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\webpack\lib\Compilation.js:476:10)
<e>     at _next5 (eval at create (C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:28:1)

**Comment by shilman** [comment]
I wonder if this has to do with the fact that you're running `nx`. @juristr @mandarini is this anything that looks familiar to you?

**Comment by juristr** [comment]
Hey @innoveltec 👋 

Which version of Nx did you upgrade from? Did you use `nx migrate`? Also, can you send me an excerpt of running `nx report` and paste it here? Thank you :)

**Comment by innoveltec** [comment]
Hey @juristr 
Thanks for the help :-) I have used the nx migrate and was coming from the nx version 13.1.4.
Here is the report:

  Node : 14.15.4
  OS   : win32 x64
  npm  : 6.14.10

  nx : 13.1.4
  @nrwl/angular : 13.1.4
  @nrwl/cli : 13.1.4
  @nrwl/cypress : 13.1.4
  @nrwl/devkit : 13.1.4
  @nrwl/eslint-plugin-nx : 13.1.4
  @nrwl/express : Not Found
  @nrwl/jest : 13.1.4
  @nrwl/linter : 13.1.4
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/nx-cloud : 12.5.2
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 13.1.4
  @nrwl/web : Not Found
  @nrwl/workspace : 13.1.4
  @nrwl/storybook : 13.1.4
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
  
  Kind regards, Gerry

**Comment by innoveltec** [comment]
hey @juristr looking at the report above i think there was something gone wrong :-) the correct report of the branch is the following:

Node : 14.15.4
  OS   : win32 x64
  npm  : 6.14.10

  nx : 13.2.1
  @nrwl/angular : 13.2.1
  @nrwl/cli : 13.2.1
  @nrwl/cypress : 13.2.1
  @nrwl/devkit : 13.2.1
  @nrwl/eslint-plugin-nx : 13.2.1
  @nrwl/express : undefined
  @nrwl/jest : 13.2.1
  @nrwl/linter : 13.2.1
  @nrwl/nest : undefined
  @nrwl/next : undefined
  @nrwl/node : undefined
  @nrwl/nx-cloud : 12.5.4
  @nrwl/react : undefined
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.2.1
  @nrwl/web : undefined
  @nrwl/workspace : 13.2.1
  @nrwl/storybook : 13.2.1
  @nrwl/gatsby : undefined
  typescript : 4.4.4
  rxjs : 6.6.7
  ---------------------------------------
  Community plugins:
         @angular/animations: 13.0.0
         @angular/common: 13.0.0
         @angular/compiler: 13.0.0
         @angular/core: 13.0.0
         @angular/elements: 13.0.0
         @angular/forms: 13.0.0
         @angular/platform-browser: 13.0.0
         @angular/platform-browser-dynamic: 13.0.0
         @angular/router: 13.0.0
         devextreme-angular: 21.2.3
         ngx-bootstrap: 7.1.0
         @angular-devkit/build-angular: 13.0.3
         @angular/cli: 13.0.3
         @angular/compiler-cli: 13.0.0
         @angular/language-service: 13.0.0
         @storybook/angular: 6.4.0-rc.3

**Comment by shilman** [comment]
Closing this under the assumption that it's an `nx` issue -- if that turns out not to be the case, please let me know and I'll happily re-open!

**Comment by juristr** [comment]
@innoveltec sorry haven't been able to check this out last week. Could you reopen the issue on the Nx repo? And ping me there, so I can keep track of it. Thank you
