### ISSUE TITLE
htmlWebpackPlugin is not defined

### ISSUE THREAD

**Issue by avergos29** [storybookjs/storybook#16753]
**Describe the bug**
Storybook does not start any more after upgrading to 6.4.0-rc.6 and Webpack 5

I get this in the logs when starting storybook 

`ERROR in   ReferenceError: htmlWebpackPlugin is not defined`
 ` - index.ejs:15`
`    [web-library]/[@storybook]/core-common/dist/cjs/templates/index.ejs:15:11`
`  - index.ejs:65 module.exports`
`    [web-library]/[@storybook]/core-common/dist/cjs/templates/index.ejs:65:3`
`  - index.js:450`
`    [web-library]/[manager-webpack5]/[html-webpack-plugin]/index.js:450:16`
`  - runMicrotasks`
`  - task_queues.js:93 processTicksAndRejections`
`    internal/process/task_queues.js:93:5`
`  - async Promise.all`

**System**
Environment Info:

  System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
  Binaries:
    Node: 14.15.5 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.13.0 - D:\Yarn\bin\yarn.CMD
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (96.0.1054.29)
  npmPackages:
    @storybook/angular: ^6.4.0-rc.6 => 6.4.0-rc.6

**Comment by MilosRasic** [comment]
Still happening with 6.4.9 and webpack 5.

The error message means compilation of the ejs template is failing because `htmlWebpackPlugin` is undefined (obviously).

The reason is webpack config from manager-webpack5 package is providing a function with wrong signature as `templateParameters` option to html-webpack-plugin in its webpack config.

The function from cjs manager-webpack.config.js:
```
                templateParameters: function templateParameters(compilation, files, options) {
                  return {
                    compilation: compilation,
                    files: files,
                    options: options,
                    version: version,
                    globals: {
                      CONFIG_TYPE: configType,
                      LOGLEVEL: logLevel,
                      VERSIONCHECK: JSON.stringify(versionCheck),
                      RELEASE_NOTES_DATA: JSON.stringify(releaseNotesData),
                      DOCS_MODE: docsMode,
                      // global docs mode
                      PREVIEW_URL: previewUrl // global preview URL

                    },
                    headHtmlSnippet: headHtmlSnippet
                  };
                },
```

How the function is called in html-webpack-plugin version 5.5.0:
```
    return Promise
      .resolve()
      .then(() => console.log('CALLING TEMPLATE PARAMS FUNC') || templateParameterFunction(compilation, assets, preparedAssetTags, options));
```

Default function from html-webpack-plugin, used if no option is provided:
```
function templateParametersGenerator (compilation, assets, assetTags, options) {
  return {
    compilation: compilation,
    webpackConfig: compilation.options,
    htmlWebpackPlugin: {
      tags: assetTags,
      files: assets,
      options: options
    }
  };
}
```

Obviously `assetTags` param is omitted in storybook config, causing the object that's passed to be forwarded as `options` object instead of the original `options` object.

**Comment by shilman** [comment]
@MilosRasic are you also using angular?

**Comment by MilosRasic** [comment]
No, React, but you just fixed my problem by making me look at the dependency versions again :slightly_smiling_face: 

We have webpack 5 builder and manager pinned to 6.3.8 but the rest of Storybook packages are caret deps so they went to latest. Unpinning removes the problem.

Sorry for the false alarm.

**Comment by shilman** [comment]
@MilosRasic glad you got it sorted and thanks for reporting back!

@avergos29 can you check your dependencies too to see if there are any version mismatches?
