### ISSUE TITLE
Angular 13 build fails - `stylePreprocessorOptions` no more applied

### ISSUE THREAD

**Issue by MickL** [storybookjs/storybook#16763]
**Describe the bug**
I just upgraded to Angular 13 and Storybook now fails to build:

```
ERR! Module build failed (from ./node_modules/@angular-devkit/build-angular/node_modules/sass-loader/dist/cjs.js):
ERR! SassError: Can't find stylesheet to import.
ERR!   ╷
ERR! 2 │ @import "app-globals";
ERR!   │         ^^^^^^^^^^^^^
ERR!   ╵
```

I do have `stylePreprocessorOptions` in my angular.json:
```
            "stylePreprocessorOptions": {
              "includePaths": [
                "src/styles"
              ]
            },

```

And then I import app-globals.scss in all my Stylesheets to be able to access my global variables.

**To Reproduce**
Please dont force me to create reproduction repo again. I only have problems with Storybook and wasted SO much time. I created so many issues already and [another open issue](https://github.com/storybookjs/storybook/issues/16386), which makes Storybook totally useless, is still open, too. Now Storybook is, one more time, unusable even tho Angular 13 is officially out for 20 days.

**System**
```
Environment Info:

  System:
    OS: macOS 12.0.1
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.0/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Chrome: 96.0.4664.55
    Safari: 15.1
  npmPackages:
    @storybook/addon-actions: ^6.4.0-rc.6 => 6.4.0-rc.6 
    @storybook/addon-essentials: ^6.4.0-rc.6 => 6.4.0-rc.6 
    @storybook/addon-links: ^6.4.0-rc.6 => 6.4.0-rc.6 
    @storybook/angular: ^6.4.0-rc.6 => 6.4.0-rc.6 
    @storybook/builder-webpack5: ^6.4.0-rc.6 => 6.4.0-rc.6 
    @storybook/manager-webpack5: ^6.4.0-rc.6 => 6.4.0-rc.6 

```

**Comment by Dimoner** [comment]
I faced this problem too!

**Comment by Tim-arts** [comment]
Angular 13 out does not mean Storybook should support it right away, they have both their own road map. Plus SB core has been planned to be rewritten in the 6.4 which means a lot of changes and probably some regressions as well so you can't expect Angular 13 to be supported right away.

That said, I agree with you on the fact that SB is lacking a lot of support about Angular in general. I've been facing way too many issues on basic functionalities in the past and still am, that's quite sad.

**Comment by MickL** [comment]
This is super offtopic but since Angular has a roadmap with alpha, beta, and release candidates I would expect Storybook to support it even before the official release tbh. 90% there are breaking changes anyway.

**Comment by shilman** [comment]
@MickL storybook for angular is maintained by a small team of volunteers in their spare time and out of the goodness of their hearts. the best way to ensure that storybook supports the next major version of angular before it's released is to test it early and file bugs with reproductions. and if you want to guarantee that those bugs are fixed, we also welcome PRs.

perhaps your previous experience is that the more obnoxiously you complain, the faster things get fixed. but that's not the case here. i guarantee that we're doing our best to get things fixed no matter how insufferable the comments are.

**Comment by shilman** [comment]
Egads!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-rc.9 containing PR #16675 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
