### ISSUE TITLE
Component variable name must match filename in order for Controls to generate properly using `react-docgen-typescript`

### ISSUE THREAD

**Issue by michal-kurz** [storybookjs/storybook#16769]
**Describe the bug**
In order for Controls to auto-generate properly for a component using `react-docgen-typescript`, the name of a variable to which the component is assigned must match the name of the file in which it is defined.

**To Reproduce**
I created a repro repo here: https://github.com/michal-kurz/storybook-controls-bug-reporuction-repo

There are two stories there, demonstrating the fact that Controls only get auto-generated when filename matches Component variable name.

**System**
Environment Info:

  System:
    OS: Linux 5.10 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (16) x64 Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz
  Binaries:
    Node: 12.22.3 - ~/.nvm/versions/node/v12.22.3/bin/node
    Yarn: 1.22.11 - ~/.nvm/versions/node/v12.22.3/bin/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v12.22.3/bin/npm
  Browsers:
    Chrome: 95.0.4638.54
    Firefox: 78.15.0esr
  npmPackages:
    @storybook/addon-actions: ^6.3.12 => 6.3.12 
    @storybook/addon-essentials: ^6.3.12 => 6.3.12 
    @storybook/addon-links: ^6.3.12 => 6.3.12 
    @storybook/cli: ^6.3.12 => 6.3.12 
    @storybook/node-logger: ^6.3.12 => 6.3.12 
    @storybook/preset-create-react-app: ^3.2.0 => 3.2.0 
    @storybook/react: ^6.3.12 => 6.3.12 

**Additional context**
Not sure if this is an issue with  `react-docgen-typescript` or `Storybook`, but either way it would be nice to have consistent Controls generation, if it's something that can be achieved on SB side of things

**Comment by michal-kurz** [comment]
I'm not sure that debugging/fixing this issue is worth the effort, but I suggest it would be nice to at least document this behaviour, as it took me hours to find out what's going on (why some stories generate the Controls for me and other don't).

**Comment by shilman** [comment]
closing as dupe to #15401
