### ISSUE TITLE
Story order changes after enabling storyStoreV7

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#16767]
**Describe the bug**
Here's the before/after setting the `storyStoreV7` flag:
![image](https://user-images.githubusercontent.com/1671563/143063325-797bacd4-8fca-41e5-953e-40f286f79415.png)

There is no storySorts defined in preview.js. Here's how the stories globs look like:
```
  stories: [
    '../src/docs/Introduction.stories.mdx',
    '../src/docs/*.stories.mdx',
    '../src/**/*.stories.@(js|jsx|ts|tsx)',
  ],
```

**To Reproduce**
Access this repo and set the flag:
https://github.com/yannbf/mealdrop/blob/feat/sb-6.4/.storybook/main.ts

**Comment by shilman** [comment]
Jiminy cricket!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-rc.10 containing PR #16788 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
