### ISSUE TITLE
[Storybook 6.4] moderInlineRenderer does not respect iframed stories

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#16768]
**Describe the bug**

Here's a story that has a modal. In order for it to work correctly in docs, I set it as an iframed story in docs with the following parameters:
```
  parameters: {
    docs: { inlineStories: false, iframeHeight: 600 },
  },
```

Here is how it looks like:
![image](https://user-images.githubusercontent.com/1671563/143074771-7c4727ae-a2e0-4229-b30a-0f3ae831444d.png)

And here is how it looks like with `FEATURES.modernInlineRenderer` set to true:
![image](https://user-images.githubusercontent.com/1671563/143074781-bb169d17-1ab5-490f-9617-596ca8aea9d8.png)

**To Reproduce**

You can access the `feat/sb-6.4` repo here and the story from the picture:
https://github.com/yannbf/mealdrop/blob/feat/sb-6.4/src/pages/RestaurantDetailPage/components/FoodItemModal/FoodItemModal.stories.tsx

Then go to main.ts and set `moderInlineRenderer` to test

**Comment by shilman** [comment]
Jeepers creepers!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.3 containing PR #16853 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```

Closing this issue. Please re-open if you think there's still more to do.
