### ISSUE TITLE
docs: honor PREVIEW_URL in non-inlined stories

### ISSUE THREAD

**Issue by ittaibaratz** [storybookjs/storybook#16775]
**Is your feature request related to a problem? Please describe**

For our internal build system, we need PREVIEW_URL to be honored not just for normal stories, but also for non-inlined stories, as we use the docs add-on in some of our newer stories.

**Describe the solution you'd like**

non-Inline stories in docs (inlineStories = false) should respect PREVIEW_URL as they iframe the stories.

**Describe alternatives you've considered**

The only alternative is to inline our stories, but this is impossible because of their styles.

**Are you able to assist to bring the feature to reality?**
Yes! I've made this simple PR to enable this feature: https://github.com/storybookjs/storybook/pull/16773 , if someone can review it we can continue the conversation there. I've tested this PR locally against my project and it works well.

**Additional context**

**Comment by shilman** [comment]
Jiminy cricket!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-alpha.3 containing PR #16773 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
