### ISSUE TITLE
Please get your dependencies correct and non breaking between the same version of main packages

### ISSUE THREAD

**Issue by dietergeerts** [storybookjs/storybook#16776]
**Describe the bug**
Again, I get a similar error where dependencies are incorrect, partly due to incorrect usage of peer vs direct dependencies, and by breaking path/minor releases in internal packages. I already have so many fixes in my `pnpmfile` in order to correct all these mistakes, but this madness has to stop. I know that dependencies aren't always easy, but if you follow the specs correctly, you will have correct ones, and yes, the user might need to add a dependency more, but that's for the better.

Take note that the below error is solely due to `storybook` packages. After investigating, it's the `storybook` package itself that has the version set to `8`, while another of its dependencies needs `7`....

```
 ERROR  @rush-temp/tools-docs-storybook > @storybook/addon-essentials > @storybook/addon-docs > @storybook/builder-webpack4 > terser-webpack-plugin: terser@5.10.0 requires a pee
r of acorn@^8.5.0 but version 7.4.1 was installed.
```

**To Reproduce**
Install the package through pnpm/rush monorepo, which checks on correct peerDependencies.

**System**
See error above

**Additional context**
N/A

**Comment by dietergeerts** [comment]
Even though this time it's not Storybook itself, my statement still stands, in that Storybook does dependencies in not such a correct way, breaking builds from time to time, and needing to fix them through an pnpm file.

As an example of this:

```
      /**
       * @rush-temp/tools-docs-storybook
       * > @storybook/addons
       *  > @storybook/api:
       * @reach/router@1.3.4 requires a peer of react@15.x || 16.x || 16.4.0-alpha.0911da3 but version 17.0.2 was installed.
       * @reach/router@1.3.4 requires a peer of react-dom@15.x || 16.x || 16.4.0-alpha.0911da3 but version 17.0.2 was installed.
       *
       * The "@reach/router" package has a peer on react(-dom), but only up to v16.
       * We already use v17, and Storybook itself also states a peer of at most v17.
       */
      if (pkg.name === '@reach/router') {
        if (pkg.version !== '1.3.4') {
          throw outOfDateFixesError(pkg);
        }
        pkg.peerDependencies['react'] = '^17';
        pkg.peerDependencies['react-dom'] = '^17';
        context.log(
          `[${pkg.name}]: Set peer dependency of "react" and "react-dom" to "^17"`,
        );
      }
```

**Comment by shilman** [comment]
@dietergeerts storybook currently doesn't support pnpm. if you're interested in helping get it pnpm-ready and we can figure out some CI checks, that will go a long way towards helping make sure these issues stay fixed.

**Comment by dietergeerts** [comment]
@shilman , pnpm just checks if dependencies are correct and installs them in such a way that packages can only use what the state. This means that there is nothing specific about pnpm that packages should know. If dependencies are stated and used correctly, then it will just work on pnpm, and any other package manager installer out there.

From what I see in the storybook packages, dependencies aren't used correctly, and that's probably due to how the whole system works with a combination of packages created to make it easy to setup a storybook, but although they make setup easier, dependencies are not handled correctly, and thus they can cause problems.

**Comment by shilman** [comment]
@dietergeerts Different package managers behave differently when it comes to how strict they enforce dependencies. It seems as if pnpm is especially strict. We've already upgraded from reach router to react router in 6.4, and I'm sure there are more maintenance tasks like this that can be identified and/or executed. This is an open source project and if you'd like to help make storybook pnpm-ready, any contributions would be much appreciated.

**Comment by dietergeerts** [comment]
@shilman , ok, let me check our fixes we had to do in our pnpmfile for storybook, and maybe raise a ticket for each one, or should I use this one to list them? I think it's important first to find out the exact problem for each "error", and then discuss it, as some might need some bigger changes. For some other packages more related to react, I got shout out for raising these problems, and there they stay with their point that adding dependencies which should be a peer, MUST be listed as internal ones, just for the sake of the consumer package to have to install less dependencies. 🤦 . So I'm always a bit hesitant to discuss these issues.

**Comment by shilman** [comment]
@dietergeerts that would be fantastic. since each issue may have its own subtleties, if it's not too much work can you file a separate issue for each one and we can discuss the fixes there?

there has also been a recent suggestion to start pre-bundling pieces of storybook: https://github.com/storybookjs/storybook/issues/16532 

if we go that route, it might also solve some of the issues like the acorn issue identified in the original issue description.

**Comment by IanVS** [comment]
Storybook 7.0 has good pnpm support now, without workarounds or hacks.  Please try upgrading with `pnpx sb@next upgrade --prerelease`.  As long as you have a pnpm lockfile, it will be used to install the dependencies, or you can force it with `--package-manager=pnpm`.

**Comment by dietergeerts** [comment]
> Storybook 7.0 has good pnpm support now, without workarounds or hacks. Please try upgrading with `pnpx sb@next upgrade --prerelease`. As long as you have a pnpm lockfile, it will be used to install the dependencies, or you can force it with `--package-manager=pnpm`.

Thx! We'll try it out as soon as I can.
