### ISSUE TITLE
Storybook webcomponent show "no code available" in docs tab

### ISSUE THREAD

**Issue by yhjhoo** [storybookjs/storybook#16779]
Source code here:
https://github.com/yhjhoo/init-open-wc/tree/main/app-wc-storybook

Checked storybook offical document related to web component, doesn't find any useful information.

**Comment by shilman** [comment]
¡Ay Caramba!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-rc.10 containing PR #16792 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
