### ISSUE TITLE
Addon:Docs hide zoom feature for Primary story

### ISSUE THREAD

**Issue by idesigncode** [storybookjs/storybook#16771]
**Is your feature request related to a problem? Please describe**
Unable to hide the zoom feature for the `Primary` component (without hiding the whole toolbar).

**Describe the solution you'd like**
Hide the zoom buttons on the `Primary` component with:
- The existing `toolbar.zoom.hidden: true` config (for global/story parameters).
- A new `Primary` component prop.

**Describe alternatives you've considered**
- Using MDX `Canvas` component to display the primary story with the prop `withToolbar={false}`.
- Using MDX `Story` component to display the primary story + `toolbar.zoom.hidden: true` configuration(s).

**Are you able to assist to bring the feature to reality?**
I can test but not familiar with the source code.

**Additional context**
Using v6.3.4 of `@storybook/addon-docs`, `@storybook/addons` & `@storybook/react`

**Comment by shilman** [comment]
This is the recommended workaround: https://storybook.js.org/docs/react/writing-docs/docs-page#remixing-docspage-using-doc-blocks

You could replace `<Primary />` with `<Story id="^" />` which is the first story

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if this is still relevant in SB 7.x.
