### ISSUE TITLE
Logo link allow for the removal of target="_blank"

### ISSUE THREAD

**Issue by dimitrieh** [storybookjs/storybook#16782]
**Is your feature request related to a problem? Please describe**

Currently, when configuring a URL for the logo in the top part of the sidebar it always opens up a new tab. Ideally, this should just take you to the page you configured it for without opening a new tab, especially when it is a page that has been configured as a home page.

**Describe the solution you'd like**

I would like to be able to flag the URL not to open a new tab, for example in the theming options.

**Describe alternatives you've considered**

There is currently no workaround, except for accepting the situation as is. Opening a new tab, closing the old one.

**Are you able to assist to bring the feature to reality?**
Potentially, if pointers are given.

**Additional context**
This is related to the comment at this issue https://github.com/storybookjs/storybook/issues/10647#issuecomment-671870807

**Comment by waseemahmad31** [comment]
Hi 

I can look into this issue. Just wanted to confirm before I make changes in the code, do we really want to remove target="_blank"? I can see this change was done as part of the pull request https://github.com/storybookjs/storybook/pull/6106/files.

**Comment by dimitrieh** [comment]
@waseemahmad31 I would say "provide a configuration". 

> I can see this change was done as part of the pull request https://github.com/storybookjs/storybook/pull/6106/files[](https://github.com/marketplace/stale).

From which version of Storybook would this new config be accessible?

**Comment by drcobel** [comment]
We have the same issue, running SB 6.5.9 React.
As UX designer the expected behavior when clicking the site logo is to return to the homepage without opening a new tab.
We should be able to configure it, but by default open the defined homepage on the same tab at least (it is really annoying to open a new tab each time)

**Comment by paulshryock** [comment]
I feel that `target="_blank"` should be removed (as opposed to adding an override flag). I can't think of any benefit to having the logo hyperlink open in a new tab.

If it's a normal hyperlink (without `target="_blank"`), then the user can choose to either click and navigate in the same tab, or right click and "open in a new tab" if they want to. I feel the user should get to make that choice, not the application.

**Comment by paulshryock** [comment]
It's a shame to see this issue closed. Defaulting to an experience with both security and performance issues is a poor user experience.

It may be possible to find a "workaround" by opting-in to using `brandTarget`, but by default most users are getting a worse user experience than they could be. 🤷
