### ISSUE TITLE
🔥 sb repro overwrites .vuerc🔥 

### ISSUE THREAD

**Issue by bodograumann** [storybookjs/storybook#16787]
**Describe the bug**
When creating a bug report, I was asked to run `npx sb@next repro` (I ran it with `npm install -g sb@next && sb repro`).
I chose `vue3` as my framework and it ran the following command:
```
echo '{"useTaobaoRegistry": false}' > ~/.vuerc && npx -p @vue/cli@^4 vue create {{appName}} --preset=__default_vue_3__ --packageManager=npm --no-git --force
```

Effectively overwriting my `~/.vuerc` config file :rage: 
Luckily I had no custom setup there, but for other users this might easily be fatal :skull: 
Please don’t do this!

**To Reproduce**
## 💣 Please only run this if you don’t have anything configured in ~/.vuerc! 💣
Run `npx sb@next repro` and select vue3.

**System**
```
Environment Info:

  System:
    OS: Linux 5.15 Arch Linux
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
  Binaries:
    Node: 17.1.0 - /usr/bin/node
    Yarn: 3.0.0-git.20210727.hash-3cbbb672 - /usr/bin/yarn
    npm: 8.1.3 - /usr/bin/npm
  Browsers:
    Firefox: 94.0.2
```

**Comment by shilman** [comment]
Ouch. Will try to get that fixed ASAP!

**Comment by shilman** [comment]
Ermahgerd!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.8 containing PR #16897 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Good golly!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-alpha.2 containing PR #16897 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```
