### ISSUE TITLE
Use a standard way of configuring

### ISSUE THREAD

**Issue by fvanwijk** [storybookjs/storybook#16781]
As discussed with @ghengeveld today 📞 

**Is your feature request related to a problem? Please describe**

The config files for Storybook have magic names, so you have to know [how to name them](https://storybook.js.org/docs/react/configure/overview#configure-story-rendering). In other words, the files names are part of your API.
If you define preview.js, you setup how stories render, and if you rename the file to whatever.js, it is ignored silently.

In understand that you need at least multiple files, a main file, one for the manager and for the preview, but I like to have the relation between these more explicit. 

**Describe the solution you'd like**

- Get rid of the .storybook dir and support the [rc file formats](https://github.com/davidtheclark/cosmiconfig) (storybook.rc.js, storybook.config.js, etc), like all the other tools (jest, prettier, eslint, etc). As a bonus you don't have `../` paths anymore because all paths become relative to the project root.
- The path of the preview file could be explicitely defined in storybook.config.js. This is similar to `globalSetup` and `setupFiles` in Jest config. Use default paths as fallback (like you currently do). Same for header.html etc
- Add an config file API page in the docs with all the configuration keys. The options probably overlap with many of the CLI options, so these pages could be merged.

**Describe alternatives you've considered**

The way you configure and setup Storybook has changed over the years. Although it has been improved and there is more configuration flexibility, to me it feels like a ducttape solution with more parts and duct tapes added over the years. The proposed solution still allows for flexibility, but is more inuitive because other tools in the JS ecosystem are configured the same way.

**Are you able to assist to bring the feature to reality?**

I have not yet looked into Storybook internals, so probably no.

**Comment by ghengeveld** [comment]
To note: it's already currently possible to put your config files in an alternative directory by passing the `-c` or `--config-dir` flag. You can even set it to `.` to have it look for `main.js` etc. in your project root directory. [`official-storybook`](https://github.com/storybookjs/storybook/tree/next/examples/official-storybook) does this.

Regardless, I'm open to the idea of supporting an rc file / config.js file at the root, as it could make things cleaner for simple projects and newcomers.

**Comment by shilman** [comment]
Why is renaming a file from `.storybook/preview.js` to `.storybook/foo.js` and having that be ignored any different from renaming a file from `babel.config.js` to `foo.js` and having that be ignored?

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if this is still relevant in SB 7.x.
