### ISSUE TITLE
Storybook 6.5 release 👟

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#16797]
SB6.5 adds new testing and design review workflows while improving core performance and compatibility

## Schedule

- ✅ `6.5.0-alpha.0` 2021-12-01
- ✅ `6.5.0-beta.0` 2022-04-24
- ✅ `6.5.0-rc.0` 2022-05-17
- 🏁 `6.5.0` 2022-05-18 

## Contents

Storybook 6.5 contains hundreds of features and bugfixes. For a full list, see [CHANGELOG.md](https://github.com/storybookjs/storybook/blob/next/CHANGELOG.md). Some highlights:

- [Webpack5 lazy compilation](https://github.com/storybookjs/storybook/pull/17501)
- [UI for toggling the addons panel](https://github.com/storybookjs/storybook/pull/17714)
- [Support React 18 new root API](https://github.com/storybookjs/storybook/pull/17215)
- [Opt-in MDXv2 support](https://github.com/storybookjs/storybook/pull/17515)
- [Conditional controls](https://github.com/storybookjs/storybook/pull/17883) 
- [CSF3 auto-title improvements](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#csf3-auto-title-improvements)
- [Default render functions for new frameworks](https://github.com/storybookjs/storybook/issues/15498)
- [Vite project autodetection in CLI](https://github.com/storybookjs/storybook/pull/17860)

**Comment by phaistonian** [comment]
Any sharable planned "stuff" for 7.0?:)

**Comment by JohnAlbin** [comment]
@phaistonian Watch https://github.com/storybookjs/storybook/milestone/28 and https://storybook.js.org/releases/7.0 Also, there is a bunch of good stuff on the migration guide about upcoming features. https://github.com/storybookjs/storybook/blob/next/MIGRATION.md

**Comment by Methuselah96** [comment]
https://github.com/storybookjs/storybook/issues/13491 has the most info at the moment on the planned stuff for 7.0.

**Comment by bobaekang** [comment]
What's the current plan for 6.5-beta, RC, and stable releases in terms of timing?

**Comment by shilman** [comment]
@bobaekang updated the description with latest time estimates

**Comment by bobaekang** [comment]
Congrats on 6.5 beta release!

**Comment by marksy** [comment]
Hey @shilman just wondering if there's an update to the release date of 6.5 (stable)?

The beta is looking great so far, thanks 👍🏼

**Comment by marko-hologram** [comment]
> Hey @shilman just wondering if there's an update to the release date of 6.5 (stable)?
> 
> The ~beta~ alpha is looking great so far, thanks 👍🏼

I guess you are lucky because 6.5 was released just few hours ago 😄  https://github.com/storybookjs/storybook/releases/tag/v6.5.0

**Comment by lordvins226** [comment]
> > Hey @shilman just wondering if there's an update to the release date of 6.5 (stable)?
> > The ~beta~ alpha is looking great so far, thanks 👍🏼
> 
> I guess you are lucky because 6.5 was released just few hours ago 😄 https://github.com/storybookjs/storybook/releases/tag/v6.5.0

I love it

**Comment by brightsider** [comment]
I have problems with 6.5.0 too

**Comment by symmetriq** [comment]
Doesn't seem to work with Vue 3. Issue: #18264

**Comment by marksy** [comment]
> > > Hey @shilman just wondering if there's an update to the release date of 6.5 (stable)?
> > > The ~beta~ alpha is looking great so far, thanks 👍🏼
> > 
> > 
> > I guess you are lucky because 6.5 was released just few hours ago 😄 https://github.com/storybookjs/storybook/releases/tag/v6.5.0
> 
> I love it

haha amazing timing

Thanks storybook team ❤️

**Comment by brightsider** [comment]
6.5.3 not working too
<img width="1225" alt="image" src="https://user-images.githubusercontent.com/4996231/169466888-a97143b5-7c98-4880-9c5f-66b0196bd39d.png">

**Comment by shilman** [comment]
@brightsider Please create a separate issue [with a reproduction](https://storybook.js.org/docs/react/contribute/how-to-reproduce). Thanks! 🙏.

**Comment by ksdc-grantw** [comment]
The blog post explaining the update the CSF3.0 is here, [Component Story Format 3.0](https://storybook.js.org/blog/component-story-format-3-0/)

**Comment by shilman** [comment]
@ksdc-grantw FYI, we are not pushing people to upgrade to CSF3 until 7.0. I the meantime you're welcome to use it -- t's fairly stable, usable, etc. but we thought introducing a whole new format in a minor release is too much to swallow. In 7.0, we'll update all the docs with CSF3 examples etc. and encourage people to start upgrading.

**Comment by shilman** [comment]
@ksdc-grantw By fairly stable, I didn't mean bugs (though those may exist as well) but rather that we are continuing to make small refinements to CSF3 outside of semver since it's still experimental. For example: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#csf3-auto-title-improvements
