### ISSUE TITLE
Angular 13 support?

### ISSUE THREAD

**Issue by jon9090** [storybookjs/storybook#16794]
Storybook support Angular 13?

**Comment by shilman** [comment]
Yes, Storybook 6.4 supports Angular 13.

If you're upgrading your storybook:

```
npx sb@next upgrade --prerelease
```

For a fresh install:

```
npx sb@next init
```

Or wait a few days and the final release should be out by then

**Comment by criskrzysiu** [comment]
it does, bot not with monorepo for now - if You are using "paths" configuration in tsconfig then You need to wait for fix
