### ISSUE TITLE
Classes leaking into story

### ISSUE THREAD

**Issue by dasDaniel** [storybookjs/storybook#16803]
**Describe the bug**
It appears that some classes are leaking into the story,

**To Reproduce**
Use a component with a `loader` class

**System**
```
Environment Info:

  System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz  
  Binaries:
    Node: 14.17.3 - C:\Program Files\nodejs\node.EXE        
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (96.0.1054.34)
  npmPackages:
    @storybook/addon-actions: ^6.4.0 => 6.4.0
    @storybook/addon-essentials: ^6.4.0 => 6.4.0
    @storybook/addon-links: ^6.4.0 => 6.4.0
    @storybook/addon-postcss: ^2.0.0 => 2.0.0
    @storybook/addon-svelte-csf: ^1.1.0 => 1.1.0
    @storybook/svelte: ^6.4.0 => 6.4.0
```

**Comment by shilman** [comment]
@tmeasday @MichaelArestad  is it possible that this is a bug introduced in the docs loading PR?

https://github.com/storybookjs/storybook/commit/90d797808b61c858a859d1bd57a219e7b8f93ec0#r60943719

Repro available https://github.com/storybookjs/storybook/issues/16545#issuecomment-980319286

**Comment by dasDaniel** [comment]
re #16545 
Even though the `.loader` class stems from a more recent commit, it appears that the underlying issue may be the same, so this can probably be closed.

**Comment by shilman** [comment]
Closing as dupe to #16545
