### ISSUE TITLE
Angular 13. Global styles no longer work in SB 6.4 (CSS or SCSS)

### ISSUE THREAD

**Issue by 8thblock** [storybookjs/storybook#16802]
**Describe the bug**
----------------------
1. Clean NG 13 project + SB 6.4.0
2. Added global plain old CSS style as described in https://storybook.js.org/docs/angular/configure/styling-and-css#importing-css-files
3. Result. No global styles applied. 

**To Reproduce**
----------------------
 Attaching a minimal reproduction generated myself as npx sb@next repro fails.
[styles_issue_repro.zip](https://github.com/storybookjs/storybook/files/7610735/styles_issue_repro.zip)

Just run the below to see the reproduction of the issue
```
npm i && npm run storybook
```

**Expected result**
----------------------
Global styles should apply, i.e.
- All divs must have a red background
- A top div in http://localhost:6006/?path=/story/example-introduction--page must have a blue background

**System**
----------------------
macOS Monterey
OS Version 12.0.1
npm 6.14.15
node v14.18.1

**Additional context**
n/a

**Comment by wizardnet972** [comment]
+1 
For nx:
https://github.com/nrwl/nx/issues/7908

For angular:
```
$ ng new ng-app
$ npx sb@next init
$ npm run storybook
```

And I add `process.exit()` to make sure storybook read the `preview.js` but storybook ignores that :
```
import { setCompodocJson } from "@storybook/addon-docs/angular";
import docJson from "../documentation.json";
setCompodocJson(docJson);
console.log('***********************************************************');

process.exit();

export const parameters = {
  actions: { argTypesRegex: "^on[A-Z].*" },
  controls: {
    matchers: {
      color: /(background|color)$/i,
      date: /Date$/,
    },
  },
  docs: { inlineStories: true },
}
```

**Comment by shilman** [comment]
`preview.js` runs in the browser, so `process.exit` isn't meaningful there

**Comment by 8thblock** [comment]
Also to add. The default global styles that generate by angular gets ignore as well.

1. In my attached project open src/styles.scss
2. Add same CSS as in the sample global CSS from before, i.e.
```
div {
  background-color: red !important;
}

.test {
  background-color: blue !important;
}
```
3. Compare storybook vs angular output by running respectively `npm run storybook` & `npm start`

Let me know if  I can be of any help!

**Comment by 8thblock** [comment]
While we are waiting for a resolution may be @ThibaudAV could point us in a direction to a potential workaround for this issue? Noticed you are fairly active in this area so thought I'd ping you. Cheers

**Comment by 8thblock** [comment]
Found a work-around.

1. Take my attached project
2. Add the following builder into angular.json under test project section
```
,
        "storybook": {
          "builder": "@storybook/angular:start-storybook",
          "options": {
            "browserTarget": "test:build:development",
            "port": 6006,
            "compodoc": false,
            "styles": [
              "src/styles.scss"
            ]
          }
        },
        "build-storybook": {
          "builder": "@storybook/angular:build-storybook",
          "options": {
            "browserTarget": "test:build:development",
            "compodoc": false,
            "styles": [
              "src/styles.scss"
            ]
          }
        }
```

3. Then run storybook as `ng run test:storybook`
4. You should see global styles applied.

h/t @ThibaudAV for pointers in his repos

Should probably be fixed in the upcoming releases of SB

**Comment by ThibaudAV** [comment]
yes exactly. 

but you don't have to add `"styles": ["src/styles.scss"]`if you want to add the same as the `browserTarget` 
The `styles` options in storybook builder is to override all styles form `browserTarget`

There are still 2 points to do to improve storybook on this subject.
- fix the @sb init for angular with this builder 
- change the documentation 
For the moment I did not have time to do it yet. 

but the idea was to have this workaround quickly to avoid loss of functionality. 
I also hope it will make easier the maintenance during angular version upgrades 🤞

**Comment by 8thblock** [comment]
@shilman Could you label this issue as "has workaround"? it will help others to stop digging :-)

**Comment by avergos29** [comment]
hi,

is there a workaround for "global styles" coming from an npm package ? They are ignored as  well

**Comment by Flusinerd** [comment]
Looks like there is a fix already available in storybook
https://github.com/storybookjs/storybook/pull/16675

But this does not seem to work with ``@nrwl/storybook:storybook`` builder

**Comment by 8thblock** [comment]
> hi,
> 
> is there a workaround for "global styles" coming from an npm package ? They are ignored as well

You have to add them in angular.json. Refer to angular docs not an SB "issue"
```
"stylePreprocessorOptions": {
              "includePaths": [
                "node_modules/@gore/common-ui/assets/styles"
              ]
            },
```

**Comment by avergos29** [comment]
> 

It cannot be used for a angular library, right ?

**Comment by nicolae536** [comment]
Any news when this will be fixed ? I tried the workaround and it doesn't seem to work.

**Comment by wizardnet972** [comment]
preview.scss:
```
body { border:5px solid red!important; }
```

preview.js:
```
import '!style-loader!css-loader!sass-loader!./preview.scss';
```

Does not work.

**Comment by nicolae536** [comment]
I tracked the issue a bit and it seems for my project I can update to latest `@angular` version if you release this fix https://github.com/storybookjs/storybook/commit/3dbfa80f500211febbf926ca116b1d38ffa7eab0 
Can you please release this asap ? @ThibaudAV @shilman 
This are the versions which I used
```
 "@storybook/addon-actions": "~6.4.5",
    "@storybook/addon-docs": "~6.4.5",
    "@storybook/addon-essentials": "~6.4.5",
    "@storybook/addon-links": "~6.4.5",
    "@storybook/angular": "~6.5.0-alpha.1",
    "@storybook/builder-webpack5": "~6.4.5",
    "@storybook/manager-webpack5": "~6.4.5",
    ```
and I went and manually changed the log like in this commit and than everything started to work since storybook used my angular.json config.

**Comment by shilman** [comment]
@nicolae536 released as 6.4.6

**Comment by 8thblock** [comment]
Thank you.
Issues resolved:
- Styles in Angular project are now included into the SB build and it is working

Issues still to be resolved:
- External static styles, i.e. the original issue when we use 
```
import '!style-loader!css-loader!sass-loader!./styles.scss';
```

**Comment by nicolae536** [comment]
@shilman 
![image](https://user-images.githubusercontent.com/9453094/144664785-e5cd9f5f-3d0e-47a9-a8a3-81127b455a9f.png)
Thanks very much the main issue for me seems to be fixed and everything is back to normal

**Comment by shilman** [comment]
Thanks for your patience everybody! Closing this.

**Comment by 8thblock** [comment]
It is not resolved though!

**Comment by ChazUK** [comment]
Probably a bit of cross contamination here, but does anyone have a workaround for using this in an nx monorepo?
