### ISSUE TITLE
Add typescript types to the new interaction testing addon (addon-interactions)

### ISSUE THREAD

**Issue by AndysonDK** [storybookjs/storybook#16808]
Currently installed storybook packages:
```JSON
"@storybook/addon-a11y": "^6.4.0",
"@storybook/addon-essentials": "^6.4.0",
"@storybook/addon-interactions": "^6.4.0",
"@storybook/addon-postcss": "^2.0.0",
"@storybook/jest": "^0.0.5",
"@storybook/react": "^6.4.0",
"@storybook/testing-library": "^0.0.7",
```
I have a pretty strict typescript setup, these are the typescript errors I'm receiving when using the code from this [usage example](https://github.com/storybookjs/storybook/tree/next/addons/interactions#usage)

<img width="604" alt="image" src="https://user-images.githubusercontent.com/28491857/143763802-9301fc2f-2da6-41a8-ba0c-fb75da86c305.png">

Would be nice to have types for the play function as well as the other utilities like `expect()` etc., and if the types already exists where can I import them from? Thanks!

**Comment by AndysonDK** [comment]
Okay I just found out you can do something like this to get proper types, this Is what I'm going to do for now:
```TypeScript
import { expect } from "@storybook/jest";
import { userEvent, within } from "@storybook/testing-library";
import { Button } from "./Button";
import type { ComponentMeta, ComponentStory } from "@storybook/react";

export default {
  title: "Button",
  component: Button,
  argTypes: { onClick: { action: true } },
  args: {
    label: "Button",
  },
} as ComponentMeta<typeof Button>;

const Template: ComponentStory<typeof Button> = (args) => <Button {...args} />;

export const Primary = Template.bind({});
Primary.play = async ({ args, canvasElement }) => {
  const canvas = within(canvasElement);
  await userEvent.click(canvas.getByRole("button"));
  await expect(args.onClick).toHaveBeenCalled();
}
```

**Comment by OFranke** [comment]
@AndysonDK I worked around the missing expect types by just installing jest `yarn add jest` and it seems to work. Don't know if this will cause any trouble yet.

**Comment by dmb-2222** [comment]
I solved:
({ canvasElement }: { canvasElement: HTMLElement })
