### ISSUE TITLE
 No source code available when i use typescript

### ISSUE THREAD

**Issue by 757566833** [storybookjs/storybook#16819]
**Describe the bug**
 No code available when i use typescript

**To Reproduce**
1. mkdir demo && cd demo
2. npx sb init --builder webpack5
3. choose  webpack_react
4. yarn add react react-dom typescript webpack 
5. npx typescript --init
6. tsconfig.json => jsx:react
7. preview.js 
```
...
docs: {
    source: {
      type: 'code',
    },
  },
```

**System**

  System:
    OS: macOS 12.0.1
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
  Binaries:
    Node: 14.17.3 - ~/.nvm/versions/node/v14.17.3/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v14.17.3/bin/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.3/bin/npm
  Browsers:
    Chrome: 96.0.4664.55
    Firefox: 93.0
    Safari: 15.1

**Additional context**
add component 
```
// index.tsx


import React, {cloneElement, ReactElement, useCallback, useMemo, useRef, useState} from 'react';
export interface ColorPickerProps{
  value?:string;
  defaultValue?:string;
  onChange?:(value:string)=>void;
  children?:ReactElement
}
export const ColorPicker:React.FC<ColorPickerProps>=(props)=>{
  const {value, defaultValue, onChange, children} = props;
  const [_value, set_value] = useState<string|undefined>(defaultValue);
  const currentValue = useMemo(()=>value||_value, [value, _value]);
  const handleChange = useCallback((e:React.ChangeEvent<HTMLInputElement>)=>{
    set_value(e.target.value);
    onChange&&onChange(e.target.value);
  }, [onChange]);
  const display = useMemo(()=>children?{display: 'none'}:{display: 'block'}, [children]);

  const colorRef = useRef<HTMLInputElement>(null);
  const childrenClick = useCallback(()=>{
    colorRef.current?.click();
  }, []);
  const memoChildren = useMemo(()=>children?cloneElement(children, {onClick: childrenClick}):undefined, [children, childrenClick]);
  return <>
    <input ref={colorRef} type={'color'} style={display} value={currentValue} onChange={handleChange}/>
    {memoChildren}
  </>;
};
export default ColorPicker;

```
add story
```
// index.stories.tsx

import React from 'react';
import ColorPicker from './index';
import {ComponentMeta, ComponentStory} from '@storybook/react';

const componentMeta:ComponentMeta<typeof ColorPicker> = {
  title: 'Components/common/ColorPicker',
  component: ColorPicker,
};
export default componentMeta;
export const Demo: ComponentStory<typeof ColorPicker> = (args)=>{
  const [color, setColor] = React.useState('#000000');
  return (<div>
    <ColorPicker {...args} value={color} onChange={setColor} >
      <svg
        viewBox="0 0 1024 1024"
        version="1.1"
        xmlns="http://www.w3.org/2000/svg"
        p-id="45653"
        xmlnsXlink="http://www.w3.org/1999/xlink"
        width="14"
        height="14"
      >
        <defs>
          <style type="text/css"></style>
        </defs>
        <path
          d="M904 816H120c-4.4 0-8 3.6-8 8v80c0 4.4 3.6 8 8 8h784c4.4 0 8-3.6 8-8v-80c0-4.4-3.6-8-8-8zM253.7 736h85c4.2 0 8-2.7 9.3-6.8l53.7-166h219.2l53.2 166c1.3 4 5 6.8 9.3 6.8h89.1c1.1 0 2.2-0.2 3.2-0.5 5.1-1.8 7.8-7.3 6-12.4L573.6 118.6c-1.4-3.9-5.1-6.6-9.2-6.6H462.1c-4.2 0-7.9 2.6-9.2 6.6L244.5 723.1c-0.4 1-0.5 2.1-0.5 3.2-0.1 5.3 4.3 9.7 9.7 9.7z m255.9-516.1h4.1l83.8 263.8H424.9l84.7-263.8z"
          p-id="45654"></path>
      </svg></ColorPicker>
  </div>
  );
};

```
![image](https://user-images.githubusercontent.com/25276557/143851901-1fc2b09b-6a63-4ab0-b58a-147fa85ff1f1.png)

if i remove type:code  it will work well
```
export const parameters = {
  actions: { argTypesRegex: "^on[A-Z].*" },
  controls: {
    matchers: {
      color: /(background|color)$/i,
      date: /Date$/,
    },
  },
  // docs: {
  //   source: {
  //     type: 'code',
  //   },
  // },
}

```
![image](https://user-images.githubusercontent.com/25276557/143852349-b1f5c566-d2d6-41b8-b952-ebcf7e9687b9.png)

**Comment by shilman** [comment]
Do you a have a reproduction repo you can share? If not, can you create one? See [how to create a repro](https://storybook.js.org/docs/react/contribute/how-to-reproduce).

I tried to run your reproduction steps but it showed the source code of the story as expected

**Comment by 757566833** [comment]
I changed a computer

  System:
    OS: Windows 10 10.0.19042
    CPU: (4) x64 Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.1.1 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (96.0.1054.34)
  npmPackages:
    @storybook/addon-actions: ^6.4.0 => 6.4.0
    @storybook/addon-docs: ^6.4.0 => 6.4.0
    @storybook/addon-essentials: ^6.4.0 => 6.4.0
    @storybook/addon-links: ^6.4.0 => 6.4.0
    @storybook/react: ^6.4.0 => 6.4.0
 
I never used repro before asking this question

Looks like

https://github.com/757566833/storybook-demo   

https://61a4eda0f3a2ee003aa1d1ed-sfosjjqspk.chromatic.com/?path=/docs/components-common-colorpicker--demo

What else do i need to provide？

**Comment by reywright** [comment]
@shilman how about this one? 

https://github.com/cbinsights/form-design-system
https://cbinsights.github.io/form-design-system/?path=/docs/components-button--breakout

**Comment by dev-nicolaos** [comment]
Is fixing this on the roadmap? I'm also seeing "No code available" when specifying `type: "code"` for my source block and am wondering if this bug is why. I tried rewriting the story with JS in a _.jsx_ file rather than a _.tsx_ one but got the same result. 

For context, I'm writing the story in CSF and then referencing it in MDX docs. Using React with the Vite builder.

I've also tried specifying `type: "code:` using the `<Source>` doc block directly in the MDX, but this seems to have no effect on the output compared to specifying `type: "dynamic"` or not specifying `type` at all.

**Comment by shilman** [comment]
@dev-nicolaos have you tried Storybook 6.5? I tried @757566833 's reproduction and it shows the error, but when I upgraded the storybook to 6.5, it shows the source correctly.

Closing this for now and will re-open with a 6.5 reproduction. Thanks for everybody's patience on this!
