### ISSUE TITLE
How to disable a specific addon for a specific story (not just hide it)

### ISSUE THREAD

**Issue by Simonwep** [storybookjs/storybook#16822]
**Describe the bug**

We're using the [@storybook/addon-a11y](https://storybook.js.org/addons/@storybook/addon-a11y) for accessibility testing - among simple components we also have a Story which is more or less a tool to find assets (icons / images) with a rather large amount of elements. Controls and everything else is disabled for this story. The problem is, switching to this large story (which does not need any plugins) takes a rather long time because of `axe.js` which is coming from `@storybook/addon-a11y)`:

#### Switch from normal component to a large story:

![image](https://user-images.githubusercontent.com/30767528/143863095-47d77be9-14f1-4dd6-b03c-e788658a831f.png)

A solution to this is to be able to disable an addon for a specific story.

**To Reproduce**
Please create a reproduction by running `npx sb@next repro` and following the instructions. Read our [documentation](https://storybook.js.org/docs/react/contribute/how-to-reproduce) to learn more about creating reproductions.
Paste your repository and deployed reproduction here. We prioritize issues with reproductions over those without.

Left out since my main question is about disabling an addon per story :)
I can create a reproduction upon request, but I feel like, since the large story is not really something you'd have tested, it's not necessary to improve the performance of axe.js but instead just being able to disable this addon for just one story in particular.

**System**
```
Environment Info:

  System:
    OS: Linux 5.13 Ubuntu 21.10 21.10 (Impish Indri)
    CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
  Binaries:
    Node: 16.11.0 - /usr/local/bin/node
    npm: 8.1.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 96.0.4664.45
  npmPackages:
    @storybook/addon-a11y: 6.3.12 => 6.3.12 
    @storybook/addon-essentials: 6.3.12 => 6.3.12 
    @storybook/vue3: 6.3.12 => 6.3.12 
```

**Comment by shilman** [comment]
You can disable `addon-a11y` for a story, component, or globally, by setting this parameter

```
a11y: { disable: true }
```

More info on parameters https://storybook.js.org/docs/react/writing-stories/parameters

**Comment by binomialstew** [comment]
For anyone interested in disabling your own addon:
https://storybook.js.org/docs/react/addons/addon-knowledge-base#disable-the-addon-panel
