### ISSUE TITLE
Custom browserslist leads to ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by Th3S4mur41** [storybookjs/storybook#16824]
**Describe the bug**
Storybook works fine until I add a custom `.browserslistrc` to the root of the project.
When I do, sb does compile and start but the page in the browser doesn't load properly (see screenshot below) and I get a `Custom browserslist leads to ReferenceError: regeneratorRuntime is not defined` in the DevTools

![image](https://user-images.githubusercontent.com/5543595/143894397-622dffc0-f009-46c2-8947-b371c4c8a4e2.png)

**To Reproduce**
The issue is reproducible with https://github.com/Th3S4mur41/storybook-lit-workspace-bug/tree/custom-browserslist
To fix the issue, just rename `.browserslistrc` in the root path to e.g. `_.browserslistrc`

**System**
  System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (96.0.1054.34)

```
	"dependencies": {
		"lit": "^2.0.2",
		"lit-html": "^2.0.2"
	},
	"devDependencies": {
		"@babel/core": "^7.16.0",
		"@storybook/addon-actions": "^6.4.0",
		"@storybook/addon-docs": "^6.4.0",
		"@storybook/addon-essentials": "^6.4.0",
		"@storybook/addon-links": "^6.4.0",
		"@storybook/builder-webpack5": "^6.4.0",
		"@storybook/manager-webpack5": "^6.4.0",
		"@storybook/web-components": "^6.4.0",
		"babel-loader": "^8.2.3"
	}
```

**Comment by Th3S4mur41** [comment]
Issue is still reproducible after updating to Storybook 6.4.14
https://github.com/Th3S4mur41/bug-storybook/pull/36

**Comment by stramel** [comment]
I also just ran into this issue. Once I removed the `.browserslistrc` file, everything worked properly.

**Comment by tonjohn** [comment]
I hit this issue too. Here is the browserlist in the package.json:
```
"browserslist": [
		"last 1 Chrome version",
		"last 1 Firefox version",
		"last 1 Edge major versions",
		"last 1 Safari major versions",
		"last 1 iOS major versions",
		"not IE 9-11"
	],
```

If I remove the browserslist, everything works. What's odd is that other team members don't hit this issue.

**Comment by shilman** [comment]
Is this still a problem in 7.0? Migration guide: https://storybook.js.org/migration-guides/7.0

**Comment by tflx** [comment]
I have a 7 alpha 37 running web-components-vite with no issues with browserslist in package.json

**Comment by Th3S4mur41** [comment]
@shilman I'm no longer able to reproduce the issue after upgrading to Storybook 7.
Closing the issue
