### ISSUE TITLE
Can't resolve fs, nothing helps

### ISSUE THREAD

**Issue by Apoerin** [storybookjs/storybook#16833]
I'm installing the latest version of Storybook to my existing project.
With initial templates which are coming with the install, everything's ok.
But when I'm trying to create a new story with one of my components it throws `Can't resolve fs...` 
Here's my package.json
 ```
 "dependencies": {
    "@date-io/core": "^1.3.6",
    "@date-io/date-fns": "^1.3.11",
    "@loadable/component": "^5.12.0",
    "@material-ui/core": "^4.11.2",
    "@material-ui/icons": "^4.9.1",
    "@material-ui/lab": "^4.0.0-alpha.55",
    "@material-ui/pickers": "^3.2.8",
    "axios": "^0.21.1",
    "axios-cancel": "^0.2.2",
    "chart.js": "^2.7.3",
    "chartjs-plugin-datasource-prometheus": "^1.0.6",
    "classnames": "^2.2.6",
    "connected-react-router": "^6.5.2",
    "date-fns": "^2.4.1",
    "file-saver": "^2.0.0",
    "google-libphonenumber": "^3.2.25",
    "history": "^4.7.2",
    "is-ip": "^3.1.0",
    "is-valid-hostname": "^1.0.1",
    "lodash-es": "^4.17.11",
    "material-table": "^1.69.3",
    "material-ui-phone-number": "^2.2.6",
    "moment": "^2.29.1",
    "object-hash": "^2.0.3",
    "password-generator": "^2.2.3",
    "prop-types": "^15.7.1",
    "react": "^16.8.6",
    "react-chartjs-2": "^2.8.0",
    "react-color": "^2.18.0",
    "react-confirm": "^0.1.18",
    "react-csv": "^2.0.3",
    "react-custom-scrollbars": "^4.2.1",
    "react-dom": "^16.8.6",
    "react-dropzone": "4.2.11",
    "react-flag-icon-css": "^1.0.25",
    "react-google-recaptcha-v3": "^1.7.0",
    "react-intl": "^2.8.0",
    "react-loading-overlay": "^1.0.1",
    "react-material-ui-form-validator": "^2.0.3",
    "react-redux": "^6.0.0",
    "react-router": "^5.1.0",
    "react-router-dom": "^5.1.0",
    "react-router-redux": "^4.0.8",
    "react-scripts": "3.4.4",
    "react-scrollable-feed": "^1.2.0",
    "react-select": "^3.0.5",
    "react-spinners": "^0.5.1",
    "react-stomp": "^5.0.0",
    "react-swipeable-views": "^0.13.9",
    "react-web-notification": "^0.8.0",
    "recompose": "latest",
    "redux": "^4.0.1",
    "redux-devtools-extension": "^2.13.8",
    "redux-form": "^8.1.0",
    "redux-localstorage": "^0.4.1",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.3.0",
    "split-sms": "^0.1.7",
    "typeface-roboto": "^0.0.54",
    "validatorjs": "^3.15.1",
    "webstomp-client": "^1.2.6"
  },
  "devDependencies": {
    "@storybook/addon-actions": "^6.4.1",
    "@storybook/addon-essentials": "^6.4.1",
    "@storybook/addon-links": "^6.4.1",
    "@storybook/node-logger": "^6.4.1",
    "@storybook/preset-create-react-app": "^3.2.0",
    "@storybook/react": "^6.4.1",
    "env-cmd": "^10.1.0",
    "rimraf": "^2.6.3"
  },
  "browser": {
    "fs": false,
    "path": false,
    "os": false
  },
```
I tried to add this to `webpack.config.js`
```
const path = require('path');

module.exports = (storybookBaseConfig, configType) => {
  storybookBaseConfig.resolve.alias = {
    ...storybookBaseConfig.resolve.alias,
    'fs': path.resolve(__dirname, 'fsMock.js')
  };

  return storybookBaseConfig;
};
```

And this to `fsMock.js`
```
module.exports = {
  readFileSync: () => 'mock',
  // other things in fs that you are using
}
```

And this to `main.js`
```
webpackFinal: async (config, { configType }) => {
  config.resolve.alias = {
    ...config.resolve.alias,
    'fs': path.resolve(__dirname, 'fsMock.js')
  };
  return config
}
```
Yet still, nothing helps. With the previous version, everything worked fine, but the project had updates for dependencies so the storybook upgraded as well and since then nothing works.
How to resolve it?

**Comment by shilman** [comment]
Do you a have a reproduction repo you can share? If not, can you create one? See [how to create a repro](https://storybook.js.org/docs/react/contribute/how-to-reproduce). Thank you! 🙏

**Comment by Apoerin** [comment]
ok, I'll create one, though the project I'm working on is complex and might be hard to reproduce

**Comment by Apoerin** [comment]
@shilman this one I can't reproduce in different repo cause the project is big, but along with `fs` I have the following
`Uncaught SyntaxError: Unexpected token ':' vendors~main.iframe.bundle.js:81304`

**Comment by shilman** [comment]
@Apoerin We can't help solve the problem if we can't reproduce it 🤷‍♂️

**Comment by Apoerin** [comment]
@shilman I understand, but I can't reproduce the entire project with the backend and database, and on a small part from scratch I couldn't catch error
downgrade to `~6.3.12` did the trick for now

**Comment by shilman** [comment]
@Apoerin if you do manage to find out more or have a repro, please let me know. if it's affecting your project i'm sure it will affect other users as well and i'd love to track it down and fix! in the meantime, glad you have a workaround (even if it's a pretty unsatisfying one!) 💯

**Comment by bonesoul** [comment]
same issue here..

**Comment by shilman** [comment]
@bonesoul do you have a reproduction you can share?

**Comment by Apoerin** [comment]
@shilman 
`Uncaught SyntaxError: Unexpected token ':' vendors~main.iframe.bundle.js:128712 `

and `vendors~main.iframe.bundle.js` points to this line

```
        { "NODE_ENV":"development","NODE_PATH":[],"STORYBOOK":"true","PUBLIC_URL":".","...  } 
```

full erros

```
DevTools failed to load source map: Could not load content for http://localhost:6006/index.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:6006/react-popper-tooltip.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
vendors~main.iframe.bundle.js:128712 Uncaught SyntaxError: Unexpected token ':'
iframe.html?id=*&viewMode=story:315 POST http://localhost:6006/runtime-error 404 (Not Found)
onerror @ iframe.html?id=*&viewMode=story:315
error (async)
(anonymous) @ iframe.html?id=*&viewMode=story:309
```

**Comment by essential-randomness** [comment]
> @shilman `Uncaught SyntaxError: Unexpected token ':' vendors~main.iframe.bundle.js:128712 `
> 
> and `vendors~main.iframe.bundle.js` points to this line
> 
> ```
>         { "NODE_ENV":"development","NODE_PATH":[],"STORYBOOK":"true","PUBLIC_URL":".","...  } 
> ```

Same issue! I also have a pretty big codebase and it's going to be hard to create a minimal reproduction, but I do also have the same warning about react-popper-tooltip:
> DevTools failed to load source map: Could not load content for http://localhost:6006/react-popper-tooltip.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE 

Another thing we have in common is that we're both modifying `config.resolve.alias` in our webpack config.

Not sure if any of this helps track this down. It worked at 6.3.9.

**Comment by shilman** [comment]
@essential-randomness Seems like a common one. I'll take a look at it tomorrow when I'm back from vacation. I'll create a repro myself, thanks! 🙏

**Comment by essential-randomness** [comment]
Thank you! I did a little bit more investigating and realized that I get this error when one of my stories uses "styled-jsx/css". If I remove the following import, it works:

```
import css from "styled-jsx/css";
```

my version of styled-jsx is 3.3.0. I don't know that it's the same library that's causing issues in other cases, but that's where I got. 

Here's the repo in question and the file: https://github.com/essential-randomness/bobaboard-ui/blob/master/src/buttons/PopupButtons.tsx#L7

I have tested that by changing the export in main.cjs to `stories: ["../stories/02-Buttons/10-PopupButtons.stories.tsx"]` then the removal of the above import stops triggering the issue. Whether that's a root cause or not I can't tell.

**Comment by essential-randomness** [comment]
I tried again with the latest version and the issue seems resolved on my side.

**Comment by HuyAms** [comment]
Hi, I got the same issue with version 6.4.19 `Can't resolve fs...`. I am using Storybook with RemixJS

Also tried the solutions with fsMock and with webpackFinal as the OP mentioned but nothing works. I got this suggestion

Looks like storybook isn't treeshaking out the node portions that are exported from "remix". Since it's webpack based you could look at setting the resolution of the node modules to "false".

```
{
  resolve: {
    fallback: {
      fs: false
    }
  }
}
```

Do you know where I could set it in storybook?

**Comment by ValentinH** [comment]
@HuyAms Thanks for the hint, setting the fallback did it for me!

You can set it in the `.storybook/main.js` file in the `webpackFinal` property, see https://storybook.js.org/docs/react/configure/webpack#extending-storybooks-webpack-config

For example:
```js
module.exports = {
  stories: ['../src/**/*.stories.mdx', '../src/**/*.stories.@(js|jsx|ts|tsx)'],
  addons: [
    '@storybook/addon-links',
    '@storybook/addon-essentials',
  ],
  framework: '@storybook/react',
  webpackFinal: (config) => {
    config.resolve.fallback.fs = false;

    return config;
  },
};
```

**Comment by es-lynn** [comment]
I tried `config.resolve.fallback.fs = false`, but it kept telling me that `fallback` was an invalid option.

This worked for me instead:

```
module.exports = {
  stories: ["../../src/directory/**/*.stories.tsx", "../../src/commons/**/*.stories.tsx"],
  addons: [
    "@storybook/addon-essentials",
    "@storybook/addon-a11y",
    "@storybook/preset-create-react-app"
  ],
  webpackFinal: (config) => {
    config.node = { fs: 'empty' }
    return config;
  },
};
```

**Comment by ValentinH** [comment]
This is probably because I'm using webpack 5.

**Comment by piyushkmr** [comment]
Facing the same issue, using storybook 6.5
```
    "@storybook/addon-a11y": "^6.5.9",
    "@storybook/addon-actions": "^6.5.9",
    "@storybook/addon-essentials": "^6.5.9",
    "@storybook/addon-knobs": "^6.1.15",
    "@storybook/addon-viewport": "^6.5.9",
    "@storybook/react": "^6.5.9",
```

Using webpack4 (Version: webpack 4.46.0).
Did, `config.node = { fs: 'empty' }`, gave invalid config error. `config.node = { fs: false }`, config valid, but no effect on error.

**Comment by aquinoWill** [comment]
I crreate storybook with Webcomponents and lerna, this config doens´t work for me.
`
import fs from 'fs'
....

protected render() {
    console.log(fs)
}
`

`TypeError: Cannot set property 'fs' of undefined`

main.js

`
webpackFinal: async (config, { configType }) => {
    // config.node = { fs: false }
    config.resolve.fallback.fs = false
    config.resolve.modules = [
      path.resolve(__dirname, '../node_modules'),
    ]
    return config;
  }
`

**Comment by aquinoWill** [comment]
This work for me

`webpackFinal: (config) => {
    config.node = { fs: 'empty' }
    return config;
  },`

**Comment by Frans06** [comment]
If you have Issues with typescript use 
`  webpackFinal: async (config) => {
    if (config.resolve?.fallback)
      config.resolve.fallback = { ...config.resolve.fallback, fs: false };
    return config;
  },`

**Comment by ackvf** [comment]
Not sure what were the reasons, maybe we were just copying over webpack config from another project, or just misunderstood things 6 months ago, but we ended up in a really difficult place with 
```
    config.resolve.alias = {
      ...config.resolve.alias,
      fs: path.resolve(__dirname, '../node_modules/fs-extra')
    }
```
, which really obfuscated the real issue here with:

```
TypeError: Cannot read properties of undefined (reading 'native')
```
which was coming from https://github.com/jprichardson/node-fs-extra/blob/cc7b3b22a984de5124131c7897574091c9df00e1/lib/fs/index.js#L132-L134

```
// fs.realpath.native sometimes not available if fs is monkey-patched
if (typeof fs.realpath.native === 'function') {
  exports.realpath.native = u(fs.realpath.native)
}
```

I am documenting all of it here, because believe it or not, there were more people with this kind of convoluted setup. My hope is that somebody will find this and it will save them.
