### ISSUE TITLE
"Module './types' has already exported a member named XYZ" after updating to Storybook v6.4.0

### ISSUE THREAD

**Issue by wessel-s** [storybookjs/storybook#16839]
**Describe the bug**
We are working with a monorepo and make use of Stencil.js (v2.10.0) and Storybook (v6.3.12). 
We recently updated the following Storybook dependencies from "6.13.2" to "6.4.0":
`"@storybook/html"`, `"@storybook/addon-viewport"`, `"@storybook/addon-docs"`, `"@storybook/addon-controls"`.

Now every time we run `stencil build` to build the Stencil project, we get TypeScript-related errors that prevent us from either starting up our Stencil app or Storybook.

The errors are as follows:
```
[ ERROR ]  TypeScript: ../../node_modules/@storybook/client-api/dist/ts3.9/index.d.ts:4:1
           Module './types' has already exported a member named 'RenderContext'. Consider explicitly re-exporting to
           resolve the ambiguity.

      L3:  export * from './queryparams';
      L4:  export * from '@storybook/store';
      L5:  export { addArgsEnhancer, addArgTypesEnhancer, addDecorator, addLoader, addParameters, setGlobalRender, ClientApi, };

[ ERROR ]  TypeScript: ../../node_modules/@storybook/client-api/dist/ts3.9/index.d.ts:4:1
           Module './types' has already exported a member named 'StorySpecifier'. Consider explicitly re-exporting to
           resolve the ambiguity.

      L3:  export * from './queryparams';
      L4:  export * from '@storybook/store';
      L5:  export { addArgsEnhancer, addArgTypesEnhancer, addDecorator, addLoader, addParameters, setGlobalRender, ClientApi, };
```

**Reproduction**
I tried to create a reproduction as suggested, but in the end, didn't succeed in creating one. 
Wherever I try to create this reproduction, I always run into the issue that package.json does not seem to be installed (even though it is).

**System**

Environment Info:
  System:
    OS: Windows 10 10.0.19043
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - C:\Program Files\nodejs\yarn.CMD
    npm: 7.24.2 - ~\project\node_modules\.bin\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (96.0.1054.34)
  npmPackages:
    @storybook/addon-docs: 6.3.12 => 6.4.0

**Additional Info**
From what I could see, my issue has not been submitted previously.
I couldn't create a reproduction as I mentioned, but in case you have a tip for us to fix this issue, it would be greatly appreciated.

**Comment by shilman** [comment]
Are all of your `@storybook/*` packages updated to 6.4.0?

**Comment by wessel-s** [comment]
Yes, all of them are updated to 6.4.0!

**Comment by shilman** [comment]
@tmeasday  does this ring any bells?

**Comment by tmeasday** [comment]
Haven't seen it before, I guess maybe there are strict TS rules going on here than we compiled things with?

**Comment by deek87** [comment]
I was having the same issue with a vite based storybook repo (going from 6.3.9 to 6.4.1) 

Though I was able to create a reproduction using a clean install of storybook/html 6.4.1
https://github.com/deek87/storybook-ts-error-repro

You can reproduce by running yarn build or yarn lint (just run tsc)

My guess is that it was introduced with this a09a5317a96311b0188e30ce974f715b4ed9c28d commit and semi-fixed by 922e5ee802aba48a08d7e931791201c21be1057e however the vite/rollup configs are probably stricter about conflicting namespaces.

Maybe if its more explicit about what its exporting it might fix it

**Comment by shilman** [comment]
@yannbf is this something you can follow up on?

**Comment by tmeasday** [comment]
Right:

https://github.com/storybookjs/storybook/blob/922e5ee802aba48a08d7e931791201c21be1057e/lib/client-api/src/index.ts#L13-L15

Was probably a hint, thanks @deek87

**Comment by kliehm** [comment]
@tmeasday Please have a look at the duplicate report, where I analyzed the problem.

**Comment by shilman** [comment]
Egads!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.9 containing PR #16917 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Yowza!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-alpha.2 containing PR #16917 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```
