### ISSUE TITLE
Font family changed after upgrading to 6.4.x

### ISSUE THREAD

**Issue by ashalfarhan** [storybookjs/storybook#16835]
**Describe the bug**
Previously it was just fine when using v6.1, but after upgraded to 6.4, it seems like my project is broken. The font family of some component has changed from previous version that i've been. 

Before (6.1):
![Screenshot 2021-11-30 112307](https://user-images.githubusercontent.com/70800415/144044439-b843a85c-6990-4e2b-96dc-a6ab5c05de8c.jpg)

After (6.4):
![image](https://user-images.githubusercontent.com/70800415/144085315-f5f64228-794f-41a4-a0e1-5dfb76f3a0d6.png)

**To Reproduce**
I'm not sure how to create a repro for this issue

**System**
Environment Info:

  System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
  Binaries:
    Node: 12.22.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - C:\Program Files\nodejs\yarn.CMD
    npm: 6.14.12 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (96.0.1054.34)

**Additional context**
I've also added my custom font rules to the `preview-head.html`, `manager-head.html`, and this still can't help. I don't know if this only happens to some elements that has `token` class, but in `ArgsTable` the description is also changed.
If this is the new behaviour, is there any way to customize those font?

**Comment by MichaelArestad** [comment]
Howdy @ashalfarhan. Can you describe what is broken or share more screenshots of the components that feel broken to you? All that changed was the font stack (unless I am missing something), which does not increase the specificity of the styles or the token.

**Comment by shilman** [comment]
@ashalfarhan can you screenshot the selection of the same text in 6.4? the current screenshot is of two different styles and i'd like to see the exact same style in each version

**Comment by ashalfarhan** [comment]
@shilman sure, sorry fot that, i've updated the screenshots,

@MichaelArestad Actually it just change the font family and i can't customize it, here's another screenshots. 

`ArgsTable`
Before (6.1):
![Screenshot 2021-11-30 230937](https://user-images.githubusercontent.com/70800415/144085524-fe42d26a-eb21-41e8-b5b9-138b861f13f6.jpg) 

After (6.4):
![Screenshot 2021-11-30 231428](https://user-images.githubusercontent.com/70800415/144085516-cc330b27-02f1-4122-9f4b-b98b0964e25d.jpg)

**Comment by MichaelArestad** [comment]
Thank you. You can change the font back by changing the font value in a custom Storybook theme. [Read more about it here](https://storybook.js.org/docs/react/configure/theming#create-a-theme-quickstart).

It might look something like this:

```js
import { create } from '@storybook/theming';

export default create({
  base: 'light',

  // Typography
  fontBase: '"Open Sans", sans-serif',
  fontCode: 'monospace', // Whatever your preferred font stack is should go here
});
```

**Comment by ashalfarhan** [comment]
@MichaelArestad I've added that custom theme, but it also doesn't work anyway. The font isn't changed, i've been folowing [this guide](https://storybook.js.org/docs/react/configure/theming#create-a-theme-quickstart).

**Comment by shilman** [comment]
@ashalfarhan can you share a reproduction repo?

**Comment by MichaelArestad** [comment]
@ashalfarhan I think I have a solution for you. Docs has its own theming and needs to have its theme set like [shown in the documentation](https://storybook.js.org/docs/react/configure/theming#theming-docs).

```js
import { themes } from '@storybook/theming';

// or global addParameters
export const parameters = {
  docs: {
    theme: YourTheme,
  },
};
```

If you create your own theme with your preferred monospace typeface and then set it as the theme for both Docs and Storybook, you should be good to go!

**Comment by ashalfarhan** [comment]
@MichaelArestad Thank you for your solution 🙏, but I'll try to investigate with my coworker, and discuss this issue if it's fine or not. Closing.
