### ISSUE TITLE
Question/Issue around hierarchy separators

### ISSUE THREAD

**Issue by MMT-LD** [storybookjs/storybook#16845]
**Describe the bug** **(Might not be a bug)**

Version we are on... **6.1.7** (for reference)

This refers to the change - **The default hierarchy separators changed in Storybook 6.0.**

What i'm trying to do is to show the latest version of some packages within the link of a story. For example: 
```tsx
import { Description, Meta } from '@storybook/addon-docs/blocks';
import ChangeLog from '../CHANGELOG.md';
import info from '../package.json';

<Meta title={`Changelogs/Components: [${info.version}]`} id="Changelogs/Components" />

<Description markdown={ChangeLog} />
```

This renders in the nav like so (for example): **Components: [0.0.0]**

This works and the id changes the link so it does not include the version and enables it to be copy/pasted around. This is great. However, because version contains a '.' i see this warning:

`react_devtools_backend.js:2540 The default hierarchy separators changed in Storybook 6.0.
'|' and '.' will no longer create a hierarchy, but codemods are available.
Read more about it in the migration guide: https://github.com/storybookjs/storybook/blob/master/MIGRATION.md`

Is there a way for me to do this? Or can i remove this warning?

**Comment by shilman** [comment]
We can probably remove the warning or create a setting to disable the warning.

**Comment by MMT-LD** [comment]
> We can probably remove the warning or create a setting to disable the warning.

Either would be great.

**Comment by shilman** [comment]
Ermahgerd!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.8 containing PR #16915 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Egads!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-alpha.2 containing PR #16915 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```
