### ISSUE TITLE
Stories without root are skipped when selecting initial story

### ISSUE THREAD

**Issue by ghengeveld** [storybookjs/storybook#16859]
**Describe the bug**
When opening the root Storybook URL, you are redirected to the first story. However, any stories that are not part of a "root" are disregarded, and so it will redirect to the first story that has a root, rather than whichever story is displayed at the top.

The discrepancy exists because the sidebar UI hoists stories without a root to the top, regardless of their position in the `stories` array (which is determined by `storySort`). `StoryIndexStore` simply [selects the first story](https://github.com/storybookjs/storybook/blob/3c56e1c7e8ff7559c0eec374f2bfb71484e83c3d/lib/store/src/StoryIndexStore.ts#L18-L21) when no story is selected.

**To Reproduce**
This happens on [official-storybook](https://next--5a375b97f4b14f0020b0cda3.chromatic.com/).

<img width="228" alt="Screenshot 2021-12-01 at 15 59 58" src="https://user-images.githubusercontent.com/321738/144258076-97337309-29b5-4830-b9b2-db479fd5d756.png">

**Expected behavior**
Upon opening the [base Storybook URL](https://next--5a375b97f4b14f0020b0cda3.chromatic.com/) it should show:

<img width="228" alt="Screenshot 2021-12-01 at 16 03 03" src="https://user-images.githubusercontent.com/321738/144258699-73de2608-4df2-4a15-bfe3-41cba4177e24.png">
 
Using `storySort` to put "csf3" first works around the problem because it ensures `stories[0]` is the "Inherited Render" story.

**Proposed solution**
We have two options:
1. Sort the stories array to hoist "unrooted" stories, like the sidebar does (subsequently this behavior can be removed from the sidebar).
2. When selecting the initial story, select the first unrooted story if there is one, else select the first in the array (like it does now).

Option 1 is probably best for the sake of consistency with other tools that may extract the list of stories (e.g. Chromatic). This may be considered a breaking change though.

We may also want to provide a way to specify the initial story (e.g. `parameters.options.initialStoryId` in `preview.js`).

**Comment by ndelangen** [comment]
1. is the clear winner for me..
> Sort the stories array to hoist "unrooted" stories, like the sidebar does (subsequently this behaviour can be removed from the sidebar).

**Comment by ghengeveld** [comment]
Should we consider this a breaking change (major release) or a bugfix?

**Comment by tmeasday** [comment]
Could do this now behind the `breakingChangesV7` flag

**Comment by ndelangen** [comment]
Can you explain why exactly this is breaking? This would just change which story is initially selected if no ID was present in the URL? I find that hardly a breaking change. I'd argue it's a simple bugfix that could be part of a minor release.

**Comment by tmeasday** [comment]
@ndelangen for instance you might have an E2E test setup that browses to the SB and makes assertions about the rendered story. Or it might conceivably break a tool like Chromatic (I'm pretty sure it wouldn't but 🤷 )
