### ISSUE TITLE
Storybook breaks in hybrid angular application with Webpack 5

### ISSUE THREAD

**Issue by pramodx** [storybookjs/storybook#16851]
**Describe the bug**
I have a hybrid angularjs + angular application which "requires" templates in its components e.g 

```
template: require('./phone-number.component.html'),
 styles: [String(require('./phone-number.component.scss'))]
```
Everything worked fine on webpack 4 with storybook 5, but with the upgrade to webpack 5 and storybook 6, the stories fail with the error

`TypeError: this.input.charCodeAt is not a function`. 

Most of the stories work when I refer to the templates using templateUrl and styleUrls but then that breaks my main application. Could you provide me with some direction on how I could get around this?

**To Reproduce**
Please create a reproduction by running `npx sb@next repro` and following the instructions. Read our [documentation](https://storybook.js.org/docs/react/contribute/how-to-reproduce) to learn more about creating reproductions.
Paste your repository and deployed reproduction here. We prioritize issues with reproductions over those without.

**System**
Please paste the results of `npx sb@next info` here.

```
Environment Info:

  System:
    OS: macOS 11.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 14.17.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.13 - /usr/local/bin/npm
  Browsers:
    Chrome: 96.0.4664.55
    Edge: 96.0.1054.34
    Firefox: 93.0
    Safari: 15.0
  npmPackages:
    @storybook/addon-a11y: 6.3.8 => 6.3.8 
    @storybook/addon-actions: 6.3.8 => 6.3.8 
    @storybook/addon-docs: 6.3.8 => 6.3.8 
    @storybook/addon-knobs: 6.3.1 => 6.3.1 
    @storybook/addon-links: 6.3.8 => 6.3.8 
    @storybook/addon-notes: 6.0.0-alpha.6 => 6.0.0-alpha.6 
    @storybook/addon-storysource: 6.3.8 => 6.3.8 
    @storybook/addon-viewport: 6.3.8 => 6.3.8 
    @storybook/addons: 6.3.8 => 6.3.8 
    @storybook/angular: 6.3.8 => 6.3.8 
    @storybook/builder-webpack5: 6.4.0-alpha.34 => 6.4.0-alpha.34 
    @storybook/manager-webpack5: 6.4.0-alpha.34 => 6.4.0-alpha.34 
```

**Additional context**

![image](https://user-images.githubusercontent.com/2028580/144174733-d416b1e0-6e3f-4ea3-ac7a-c693bda4f3c2.png)

**Comment by shilman** [comment]
This probably doesn't solve your problem but you shouldn't be mixing 6.3 and 6.4 packages. Try downgrading builder/manager-webpack5 to 6.3.x to make it consistent with your other packages

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
