### ISSUE TITLE
Storybook cannot find components 404

### ISSUE THREAD

**Issue by Miguel-Bento-Github** [storybookjs/storybook#16860]
**Describe the bug**
Dev server works with the exact same config but Storybook seems to struggle.

Strange log as I don't use JSX or TSX
```
Plugin: vite:import-analysis
16:13:41 [vite] Internal server error: Failed to parse source for import analysis because the content contains invalid JS syntax. If you are using JSX, make sure to name the file with the .jsx or .tsx extension.
  Plugin: vite:import-analysis
```

and the browser console logs 404
```
GET http://localhost:6006/src/stories/BasicHeader.vue?vue&type=div&index=0&lang.div net::ERR_ABORTED 404 (Not Found)
```

**To Reproduce**
Please create a reproduction by running `yarn && yarn storybook`
Repo can be found at https://github.com/Miguel-Bento-Github/vite-vue-ts-storybook

**Environment Info:**
```
  System:
    OS: macOS 12.0.1
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 16.9.1 - /usr/local/bin/node
    Yarn: 1.22.15 - /opt/homebrew/bin/yarn
    npm: 7.21.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 96.0.4664.55
    Firefox: 94.0.2
    Safari: 15.1
  npmPackages:
    @storybook/addon-a11y: ^6.4.3 => 6.4.3 
    @storybook/addon-actions: ^6.4.3 => 6.4.3 
    @storybook/addon-essentials: ^6.4.3 => 6.4.3 
    @storybook/addon-links: ^6.4.3 => 6.4.3 
    @storybook/vue3: ^6.4.3 => 6.4.3 
```

Help is appreciated in advance.

**Comment by shilman** [comment]
Please file Vite-related issues in https://github.com/eirslett/storybook-builder-vite/

Closing this for now--please let me know if you think this ISN'T Vite-related and I'll reopen. Thank you! 🙏
