### ISSUE TITLE
Args is creating a actionHandler() method when onClick is added as a prop but isn't required

### ISSUE THREAD

**Issue by nicdford** [storybookjs/storybook#16867]
**Describe the bug**
Currently when you write a story for a component that has an optional onClick prop, it doesn't define that method as undefined when values are passed as an arg. It instead returns an "actionHandler()" method. You can even go as far to explicitly define the method as undefined and this doesn't work either.

```JS
Default.args = {
	onClick: undefined
};
``` 

**To Reproduce**
Create story for component that has `onClick` prop. 

```JS
export const Default = (args: ChipProps): JSX.Element => <Chip {...args} />;

Default.args = {
	children: "Exercitation quis",
};
```

```JS
export interface ChipProps {
	onClick?: VoidFunction;
}

export const Chip: React.FC<ChipProps> = ({
	onClick,
	...props
}: ChipProps) => {
	console.log(onClick); // returns actionHandler() instead of undefined
	... rest of code
}
```

**System**
```
Environment Info:

  System:
    OS: macOS 11.5.1
    CPU: (8) x64 Apple M1
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Chrome: 96.0.4664.55
    Edge: 96.0.1054.41
    Firefox: 86.0.1
    Safari: 14.1.2
  npmPackages:
    @storybook/addon-actions: ^6.4.0 => 6.4.0 
    @storybook/addon-controls: ^6.4.0 => 6.4.0 
    @storybook/addon-docs: ^6.4.0 => 6.4.0 
    @storybook/addon-essentials: ^6.4.0 => 6.4.0 
    @storybook/addon-jest: ^6.4.0 => 6.4.0 
    @storybook/addon-links: ^6.4.0 => 6.4.0 
    @storybook/addon-postcss: ^2.0.0 => 2.0.0 
    @storybook/addons: ^6.4.0 => 6.4.0 
    @storybook/react: ^6.4.0 => 6.4.0 
    @storybook/theming: ^6.4.0 => 6.4.0 
```

**Additional context**
My current workaround is to avoid using args for those stories:
```JS
export const Default = (): JSX.Element => <Chip>Exercitation quis</Chip>;
```

**Comment by shilman** [comment]
Great Caesar's ghost!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-alpha.41 containing PR #17505 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by johan44co** [comment]
Better understanding here; https://github.com/storybookjs/addon-smart-knobs/issues/63#issuecomment-995798227
