### ISSUE TITLE
Vue: context.viewMode comes as "docs" initially in a decorator, even though selected viewMode is "story"

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#16862]
**Describe the bug**
When using addon-backgrounds, which relies on `context.viewMode` to apply styles either to the preview or docs stories, it does not work in Vue projects. The reason seems to be that viewMode is wrong initially.

Here's a video explaining and comparing fresh Vue/React projects:

https://user-images.githubusercontent.com/1671563/144272490-d3277231-2bf7-45e0-a032-36bf76d614f0.mov

**To Reproduce**
1 - `npx sb repro` and select vue or sfcVue
2 - yarn storybook

**Additional context**
This is the reason our pipeline keeps failing.

**Comment by shilman** [comment]
Ermahgerd!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.9 containing PR #16919 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Yee-haw!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-alpha.2 containing PR #16919 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```
