### ISSUE TITLE
Story titles no longer converted from camelCase to Capital Case with storyStoreV7 enabled

### ISSUE THREAD

**Issue by JoshTumath** [storybookjs/storybook#16877]
**Describe the bug**
After enabling the `storyStoreV7` feature flag, story titles are no longer converted from camelCase to Capital Case.

![Story_titles](https://user-images.githubusercontent.com/1760227/144473264-6c859852-4821-40b8-8558-6f95c1abd3e7.png)

**To Reproduce**
I have not been able to reproduce in a test case. Any advice on what I could try would be appreciated.

It happened since upgrading to 6.4.4 and enabling the following feature flags:

```js
  framework: '@storybook/react',
  features: {
    postcss: false,
    babelModeV7: true,
    storyStoreV7: true
  }
```

**System**
```
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/tumatj01/.nvm/versions/node/v14.18.1/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
gyp ERR! System Darwin 20.6.0
gyp ERR! command "/Users/tumatj01/.nvm/versions/node/v14.18.1/bin/node" "/Users/tumatj01/.nvm/versions/node/v14.18.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/tumatj01/.npm/_npx/28151/lib/node_modules/sb/node_modules/watchpack-chokidar2/node_modules/fsevents
gyp ERR! node -v v14.18.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok

Environment Info:

  System:
    OS: macOS 11.6.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Binaries:
    Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
  Browsers:
    Chrome: 96.0.4664.55
    Safari: 15.1
```

**Additional context**

**Comment by shilman** [comment]
Hey @JoshTumath. I'm not able to reproduce this. Is it possible that you're running an older version of one of the packages, esp `@storybook/csf-tools`?

- `yarn why @storybook/csf-tools`
- `npm list @storybook/csf-tools`

**Comment by JoshTumath** [comment]
> Hey @JoshTumath. I'm not able to reproduce this. Is it possible that you're running an older version of one of the packages, esp `@storybook/csf-tools`?
> 
>     * `yarn why @storybook/csf-tools`
>     * `npm list @storybook/csf-tools`

No it looks as though I'm on the latest version.

```
yarn why v1.22.17
[1/4] 🤔  Why do we have the module "@storybook/csf-tools"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "@storybook/csf-tools@6.4.4"
info Reasons this module exists
   - "_project_#@bbc#web-tooling-storybook#@storybook#addon-docs" depends on it
   - Hoisted from "_project_#@bbc#web-tooling-storybook#@storybook#addon-docs#@storybook#csf-tools"
   - Hoisted from "_project_#@bbc#web-tooling-storybook#@storybook#addon-docs#@storybook#core#@storybook#core-server#@storybook#csf-tools"
```

**Comment by shilman** [comment]
Do you a have a reproduction repo you can share? If not, can you create one? See [how to create a repro](https://storybook.js.org/docs/react/contribute/how-to-reproduce). Thank you! 🙏

**Comment by JoshTumath** [comment]
> Do you a have a reproduction repo you can share? If not, can you create one? See [how to create a repro](https://storybook.js.org/docs/react/contribute/how-to-reproduce). Thank you! 🙏

I've not been able to reproduce it so far, but I can keep trying. In the meantime, I can privately send you a Chromatic preview build of our Storybook, if that helps?

**Comment by shilman** [comment]
@JoshTumath is the error present in both `start-storybook` and `build-storybook`?

**Comment by JoshTumath** [comment]
> @JoshTumath is the error present in both `start-storybook` and `build-storybook`?

Yeah I can reproduce it on our actual project's Storybook on both.

I just noticed on Chromatic when it was verifying the storybook build, it gave this error:

```
Verifying your Storybook
→ This may take a few minutes 
→ Evaluation failed: TypeError: Cannot read property 'stories' of undefined 

at StoryStore.loadAllCSFFiles (https://5d02576173cf8b00202bda0e-yggmnuoqmb.chromatic.com/vendors~main.66e234e5.iframe.bundle.js:2:2851630)

at StoryStore.cacheAllCSFFiles (https://5d02576173cf8b00202bda0e-yggmnuoqmb.chromatic.com/vendors~main.66e234e5.iframe.bundle.js:2:2852381)

at __puppeteer_evaluation_script__:80:27 


✖ Failed to verify your Storybook 

Evaluation failed: TypeError: Cannot read property 'stories' of undefined 

at StoryStore.loadAllCSFFiles (https://5d02576173cf8b00202bda0e-yggmnuoqmb.chromatic.com/vendors~main.66e234e5.iframe.bundle.js:2:2851630)

at StoryStore.cacheAllCSFFiles (https://5d02576173cf8b00202bda0e-yggmnuoqmb.chromatic.com/vendors~main.66e234e5.iframe.bundle.js:2:2852381)
 at __puppeteer_evaluation_script__:80:27
```

I don't know if that helps. I'll try and dig into it more.

**Comment by shilman** [comment]
@JoshTumath thanks so much for the extra info!

@tmeasday does that stack trace mean anything to you?

**Comment by tmeasday** [comment]
I'd guess that's coming from this line: https://github.com/storybookjs/storybook/blob/1eb8aa10da68791321629c28d3e286df5071ed6a/lib/store/src/StoryStore.ts#L158

**Comment by tmeasday** [comment]
That's pretty odd. [The `stories.json` is there](https://5d02576173cf8b00202bda0e-yggmnuoqmb.chromatic.com/stories.json). Also it includes this @shilman:

> {"id":"web-core-components-figure--basic","title":"Web Core/Components/Figure","name":"basic","importPath":"../../website/components/figure/figure.stories.jsx"}

**Comment by tmeasday** [comment]
OK, I figured out the Chromatic extract error ("Failed to verify your Storybook"). I'm pretty sure it is unrelated to the original issue on this ticket though, as the `name` === `basic` in the `stories.json` @shilman.

**Comment by shilman** [comment]
Jiminy cricket!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.9 containing PR #16947 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Shiver me timbers!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-alpha.2 containing PR #16947 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

**Comment by tmeasday** [comment]
I don't believe the original issue here is fixed by that PR.

**Comment by JoshTumath** [comment]
Thanks for fixing the Chromatic issue, @tmeasday. I can now show you a preview build of our project's Storybook with a reproduction of the bug. https://5d02576173cf8b00202bda0e-kvqojunzbo.chromatic.com/

**Comment by shilman** [comment]
Discussed this with @JoshTumath today. Josh will get their design system updated to the latest 6.5.x and verify that the problem is still happening. At that point, I'll dig in and see if I can figure out what's going on. I'm still unable to reproduce.
