### ISSUE TITLE
Interactions: assertions fail on first load

### ISSUE THREAD

**Issue by bodograumann** [storybookjs/storybook#16872]
**Describe the bug**
The `expect` assertion in a play function can fail, when it is run too early (I think).
In particular, when the storybook is just loaded.

**To Reproduce**
Go to https://next--storybookjs.netlify.app/official-storybook/?path=/story/addons-interactions-accountform--find-by

You will find, that the story fails. Due to being
> Unable to find role="button"

If you rerun the play function, or already had the storybook loaded and just navigate to this specific story, everything is green however.

**Comment by shilman** [comment]
Sorry I missed this the first time around. Is it still a problem? Story looks like it's loading fine to me now.

**Comment by bodograumann** [comment]
Yes, unfortunately it still fails on Firefox 95.0.2, Chromium 97.0.4692.71 and QtWebEngine 5.15.8 based on Chromium 87.

The console does not show much:
![Screenshot_20220111-081839](https://user-images.githubusercontent.com/1223583/148898084-33c13b0e-22bf-4fe8-ba8f-358207a5f540.png)

In firefox it shows a lengthy manager log, probably because I have the react devtools installed. No errors though.

This is on Arch Linux with linux kernel 5.15.13-arch1-1

**Comment by shilman** [comment]
Thanks, got it to repro in Firefox 🙏

**Comment by lonyele** [comment]
I looked at it and observed that if the code is using some `waitFor`, `findBy*` to wait for something, it can fail the test. Not only this `FindBy` but all other stories that use it.

some observations
- bigger the difference between story's `setTimeout`'s time and `waitFor`, `findBy*`'s time, the more possibility to pass the test. For this issue's `FindBy` case, if the code is `setTimeout(() => setIsLoading(false), 10);` it passes most of the time. if is something like 500ms or 800ms that is near to `findBy*`'s default timeout 1000ms, then it fails most of the time.

I feel like this issue can be revisited later after #16492 is fixed. I suspect the current behavior that WAI examples(passing the test) all `fails at first load` -> `flickers` -> `pass the test`. Just my guess

**Comment by shilman** [comment]
Yo-ho-ho!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-alpha.3 containing PR #18460 that references this issue. Upgrade today to the `@future` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
