### ISSUE TITLE
MDX third-level story name crashes

### ISSUE THREAD

**Issue by mogrim90** [storybookjs/storybook#16889]
When you add some components with 3-rd level you can't access them in MDX format.
1. Create a story (*.stories.tsx) component with a 
```tsx
export default {
  title: "LevelOne/LevelTwo/LevelThree",
....
}
```
and at least one story (for example, "Basic").

2. Access to it in sidedar of storybook, in URL we have `levelone-leveltwo-levelthree--basic`

3. Create an *.stories.mdx file with the url from previous step.
```mdx
<Anchor storyId="levelone-leveltwo-levelthree--basic" />
```

4. An error is shown:

```js
Unexpected default export without title: {"includeStories":[],"parameters":{"docs":{}}}
```

**Comment by shilman** [comment]
Does mdx file contain a `Meta` element? If not, you probably need to add one

**Comment by mogrim90** [comment]
Problem was with file extension

`*.stories.mdx `
awaits for a Meta / declaration of story root

`*.mdx`
- does not, and so can be easely embedded into 

```js
parameters: {
    docs: {
      page: MdxFile,
}
```

to override the default generated `docs` tab.
