### ISSUE TITLE
Storybook cannot find angular project for angular 13 with legacy angular.json

### ISSUE THREAD

**Issue by avergos29** [storybookjs/storybook#16884]
**Describe the bug**
When starting angular I got this error 
ERR! => Could not find angular project: Cannot convert object to primitive valueTypeError: Cannot convert object to primitive value
info => Fail to load angular-cli config. Using base config

Origin is in framework-preset-angular-cli.ts l.175.
This line 
`logger.info(`=> Using angular project "${project}:${target}" for configuring Storybook`);`
should be replaced by
`logger.info(`=> Using angular project "${project}:${browserTarget.target}" for configuring Storybook`);`

Because target is an object, it cannot be used in the logger

**Comment by shilman** [comment]
Ooh-la-la!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.7 containing PR #16885 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Yippee!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-alpha.2 containing PR #16885 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```
