### ISSUE TITLE
[v6.4.7] Docs shows empty code blocks (placeholders) for disabled stories

### ISSUE THREAD

**Issue by mgameover** [storybookjs/storybook#16895]
**Describe the bug**
Storybook v6.4 displays empty code blocks even for disabled docs ( `docs: { disable: true, }`). That was not a case in v6.3 and earlier versions.

**To Reproduce**
The issue is reproduced in this [repo](https://github.com/mgameover/sb-md-relative-links/blob/docs-disable/src/stories/disable-docs.stories.ts).
Here is a code snippet:
```
storiesOf('Disabled docs', module)
    .add('Primary', () => ({
        template: 'see docs tab',
    }),
        {
            notes: { markdown: markdownNotes },
            docs: { disable: true, }
        }
    )
```
Steps:
1. Clone the [repo](https://github.com/mgameover/sb-md-relative-links/blob/docs-disable/src/stories/disable-docs.stories.ts).
2. Install dependencies and run storybook. `npm i`, `npm run storybook`  
2. Go to 'Disabled docs' story e.g. http://localhost:6006/?path=/docs/disabled-docs--primary 
3. Open docs tab, the following empty blocks are displayed
![image](https://user-images.githubusercontent.com/62712576/144647047-71a48f32-ac4b-4a8e-81b4-3f17858f1d07.png)

**System**
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-4940MX CPU @ 3.10GHz
  Binaries:
    Node: 14.18.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 96.0.4664.45
    Edge: Spartan (44.19041.1266.0), Chromium (96.0.1054.43)
  npmPackages:
    @storybook/addon-a11y: 6.4.7 => 6.4.7
    @storybook/addon-actions: 6.4.7 => 6.4.7
    @storybook/addon-docs: 6.4.7 => 6.4.7
    @storybook/addon-essentials: 6.4.7 => 6.4.7
    @storybook/addon-knobs: 6.3.1 => 6.3.1
    @storybook/addon-links: 6.4.7 => 6.4.7
    @storybook/addon-viewport: 6.4.7 => 6.4.7
    @storybook/addons: 6.4.7 => 6.4.7
    @storybook/angular: 6.4.7 => 6.4.7
    @storybook/source-loader: 6.4.7 => 6.4.7

**Comment by b0g3r** [comment]
I also faced up with the same issue. Tracked it down to the https://github.com/storybookjs/storybook/commit/bb9f36e9b4b4ae59ff84811f37a25db117d4ea6d#diff-6d3ed270e397673b621912f5bbd87be6fb773596b5557124f9c26ece73f481f2 commit, where getDocsStories with related logic was deleted.

**Comment by shilman** [comment]
Good golly!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-alpha.19 containing PR #17256 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Shiver me timbers!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.14 containing PR #17256 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```
