### ISSUE TITLE
Single Story Hoisting doesn't work if component's display name is PascalCased

### ISSUE THREAD

**Issue by sarthikg** [storybookjs/storybook#16900]
**Describe the bug**
According to the storybook docs (https://storybook.js.org/docs/react/writing-stories/naming-components-and-hierarchy), single-story hoisting works if the component has a single story. To make this work, one has to export the story with the exact same name as the component (the one that's the last part of the title).
This behavior works flawlessly if the component name is a single word, like `Button` in the docs, and the exported story is also named `Button`.
The case where this fails is when the component name is like a multiple-worded name is PascalCased.

**To Reproduce**
Alter the example in docs by making some following changes.

```javascript
// InputField.stories.js|jsx|ts|tsx

import { InputField as InputFieldComponent } from './InputField';

export default {
  /* 👇 The title prop is optional.
  * See https://storybook.js.org/docs/react/configure/overview#configure-story-loading
  * to learn how to generate automatic titles
  */
  title: 'Design System/Atoms/InputField',
  component: InputFieldComponent,
};

// This is the only named export in the file, and it matches the component name
export const InputField = (args) =>({
  //👇  Your story implementation goes here
});
```

**System**
There are no errors thrown by the storybook, it's just that it created a separate story with a space-separated name, Input Field in this case under the InputField Component.

**Comment by shilman** [comment]
It's a little funky. "Exact same" as in what's displayed on the screen. So in your example above you could do this in one of two ways:

```js
export default { title: 'Design System/Atoms/InputField' }
export const InputField = (args) =>({ ... })
InputField.storyName = 'InputField'
```

OR

```js
export default { title: 'Design System/Atoms/Input Field' }
export const InputField = (args) =>({ ... })
```

**Comment by sarthikg** [comment]
Ohh! I didn't think it that way! That definitely works like a charm.

Just a small suggestion may be, of course not required (as you already shared how to go about this), but can storybook have a check for storyName where it could check if the storyName matches the last part of the title before the step where storyName is transformed from PascalCase or camelCase into one with spaces between the words?

I don't really feel like someone would want to split up the cases where the component name is set to "InputField", and they want the story name to be "Input Field".

**Comment by shilman** [comment]
Closing this for now. Please let me know if there's more to be done here!

**Comment by iambumblehead** [comment]
related https://github.com/storybookjs/storybook/issues/16900 maybe I should remove my comment from this other issue...

**Comment by iambumblehead** [comment]
@shilman you're awesome and I like storybook because you part of it :)
