### ISSUE TITLE
React Storybook cannot load in IE11

### ISSUE THREAD

**Issue by helabenkhalfallah** [storybookjs/storybook#16911]
**Describe the bug**
I just started a new storybook project using `npx sb init` and `webpack-react`.
I have this issue on IE11 : 
![image](https://user-images.githubusercontent.com/1331451/144755165-6aa6409f-9ecd-41f2-8215-e97991f7feff.png)

**To Reproduce**
I don't have any special code, just the default generated repo (without any change).
![image](https://user-images.githubusercontent.com/1331451/144755174-3e31aa75-1356-420f-9c63-16739623bb28.png)

**System**
```js
Environment Info:

  System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
  Binaries:
    Node: 10.13.0 -
    Yarn: 1.22.10 - 
    npm: 6.4.1 - 
  Browsers:
    Chrome: 92.0.4515.107
    Edge: Spartan (44.18362.1593.0)
  npmPackages:
    @storybook/addon-actions: ^6.4.7 => 6.4.7
    @storybook/addon-essentials: ^6.4.7 => 6.4.7
    @storybook/addon-links: ^6.4.7 => 6.4.7
    @storybook/react: ^6.4.7 => 6.4.7
```

**Additional context**
I tried some solutions like : 
* disable `@storybook/addon-essentials`.
* adding https://storybook.js.org/addons/@storybook/addon-ie11.
* disable `FAST_REFRESH`.

However the issue still the same.

Thank you for your help :)

**Comment by shilman** [comment]
Try removing `Introduction.stories.mdx` from the bundle. There's a known issue where MDX breaks IE11 compatibility

**Comment by helabenkhalfallah** [comment]
Hello, thank you for your answer, I tried but I have the same issue (I clear IE cache) :

![image](https://user-images.githubusercontent.com/1331451/144795778-00c99159-a35b-4850-b138-632abdc6cf51.png)
![image](https://user-images.githubusercontent.com/1331451/144795814-fa0d9859-f97a-4f70-a965-606d17b36bf3.png)

Thank you :)

**Comment by shilman** [comment]
Do you a have a reproduction repo you can share? If not, can you create one? See [how to create a repro](https://storybook.js.org/docs/react/contribute/how-to-reproduce).

**Comment by shilman** [comment]
closing as dupe to  #17057 (which has been fixed)
