### ISSUE TITLE
Latest versions of Storybook packages yield a TypeScript error: Namespace 'React' has no exported member 'HTMLAttributeAnchorTarget'

### ISSUE THREAD

**Issue by kaiyoma** [storybookjs/storybook#16925]
**Describe the bug**
After upgrading to the latest versions of all Storybook packages in our project, type checking has now started failing:

```
../../common/temp/node_modules/.pnpm/react-router-dom@6.0.2_react-dom@16.14.0+react@16.14.0/node_modules/react-router-dom/index.d.ts(57,20): error TS2694: Namespace 'React' has no exported member 'HTMLAttributeAnchorTarget'.
```

**To Reproduce**
Install the latest Storybook packages alongside version 16.14.0 of `react` and `react-dom`, then try to run TypeScript.

**System**
```
Environment Info:

  System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
  Binaries:
    Node: 16.13.0 - C:\Program Files\Node.js\node.EXE
    npm: 8.1.4 - C:\Program Files\Node.js\npm.CMD
  Browsers:
    Chrome: 96.0.4664.45
    Edge: Spartan (44.19041.1266.0), Chromium (96.0.1054.41)
  npmPackages:
    @storybook/addon-actions: 6.4.8 => 6.4.8
    @storybook/addon-docs: 6.4.8 => 6.4.8
    @storybook/addon-knobs: 6.4.0 => 6.4.0
    @storybook/addons: 6.4.8 => 6.4.8
    @storybook/api: 6.4.8 => 6.4.8
    @storybook/components: 6.4.8 => 6.4.8
    @storybook/core: 6.4.8 => 6.4.8
    @storybook/core-events: 6.4.8 => 6.4.8
    @storybook/react: 6.4.8 => 6.4.8
    @storybook/theming: 6.4.8 => 6.4.8
```

**Comment by shilman** [comment]
Do you a have a reproduction repo you can share? If not, can you create one? See [how to create a repro](https://storybook.js.org/docs/react/contribute/how-to-reproduce). I tried to reproduce the problem but it's working fine for me.

**Comment by kaiyoma** [comment]
> Do you a have a reproduction repo you can share? If not, can you create one? See [how to create a repro](https://storybook.js.org/docs/react/contribute/how-to-reproduce). I tried to reproduce the problem but it's working fine for me.

The tool referenced on that page (`npx sb@next repro`) is pretty annoying to use on Windows 10. The output/interaction don't work correctly in git bash, and even after working around that, this tool relies on yarn, which is kind of antiquated at this point.

**Comment by kaiyoma** [comment]
I dug into this a bit more and tracked it down to an outdated version of `@types/react`. Confusingly, versions `17.x.x` of that package are for React 16, not React 17. Once I upgraded to the latest version, then the TS errors went away.

**Comment by simonsmith** [comment]
I'm still encountering this. Seems to be caused by `react-router`

```
node_modules/react-router-dom/index.d.ts:82:20 - error TS2694: Namespace 'React' has no exported member 'HTMLAttributeAnchorTarget'.

82     target?: React.HTMLAttributeAnchorTarget;
                      ~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error in node_modules/react-router-dom/index.d.ts:82
```

https://github.com/remix-run/react-router/issues/8807

I can't compile Storybook with this error. Any idea on workarounds would be appreciated!
