### ISSUE TITLE
`Unable to find storybook main.js config, skipping` error after running `npx sb@next automigrate`

### ISSUE THREAD

**Issue by jeremytenjo** [storybookjs/storybook#16920]
Getting `Unable to find storybook main.js config, skipping` error after running `npx sb@next automigrate` when my storybook folder is located in a different location. ideally `npx sb@next automigrate` would accept the `-c` option.

**To Reproduce**
1. run `npx sb init` 
2. move `.storybook` folder to `devtools/storybook`
3. run `npx sb@next automigrate`

**System**

  System:
    OS: macOS 12.0.1
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 15.14.0 - ~/.nvm/versions/node/v15.14.0/bin/node
    npm: 6.14.13 - ~/.nvm/versions/node/v15.14.0/bin/npm
  Browsers:
    Chrome: 96.0.4664.55
    Firefox: 93.0
    Safari: 15.1
  npmPackages:
    @storybook/addon-actions: ^6.4.8 => 6.4.8 
    @storybook/addon-essentials: ^6.4.8 => 6.4.8 
    @storybook/addon-links: ^6.4.8 => 6.4.8 
    @storybook/react: ^6.4.8 => 6.4.8

**Comment by shilman** [comment]
@jeremytenjo does your `package.json` include a script called `storybook` with that uses `-c devtools/storybook`? if so, i believe it should infer the config directory automatically based on that

**Comment by jeremytenjo** [comment]
Hi @shilman, my script is called `storybook:dev` but I changed it to run the command and it worked.

Thanks!

**Comment by endreujhelyi** [comment]
@shilman, could you please provide the script you are using? When attempting to run a command like `npx storybook@latest migrate mdx-to-csf --glob "src/**/*.stories.mdx" --config-dir "devtools/storybook"`, the following error message is shown: `error: unknown option '--config-dir'` (the same occurs with `-c`).

**Comment by endreujhelyi** [comment]
@jeremytenjo what was the whole script you were running?

**Comment by lwkchan** [comment]
Hey @endreujhelyi - I was having a similar issue as you and came across this thread.

I've managed to run the `mdx-to-csf` migration in my monorepo by running `npx storybook automigrate -c packages/path/to/.storybook`. The wizard will ask if you want to run the migration
