### ISSUE TITLE
[Storybook 6.4] - Enforce usage of the framework field

### ISSUE THREAD

**Issue by bebraw** [storybookjs/storybook#16921]
**Is your feature request related to a problem? Please describe**

I came by a small problem in 6.3 to 6.4 work in a client project. As it's a private repository, I've described my problem below.

At first after updating dependencies, I set `addons` as follows:

**.storybook/main.js**

```js
module.exports = {
  ...
  addons: [
    ...
    '@storybook/react'
  ]
};
```

As it turns out, it yielded the following:

```
...
ERR! ValidationError: Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
ERR!  - configuration.entry should not contain the item '/client/node_modules/@storybook/react/dist/esm/client/preview/config-generated-config-entry.js' twice.
...
```

I checked the code in detail and found out it's pulling configuration from `@storybook/react` twice. After changing the configuration like this, it began to work again:

```js
module.exports = {
  framework: '@storybook/react',
  ...
}
```

The [migration documentation](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#using-the-v7-store) seems confirm this usage and that's where I got the idea to try the alternative. Note that I ran the migration tool before doing my changes so maybe it missed the change or I did something wrong.

**Describe the solution you'd like**

Given the error seems fatal and tricky to debug based on the error alone, maybe it would make sense to check `addons` against packages like `@storybook/react` and then give a nice error that tells how to fix the situation. I imagine there are other cases beyond this where the same field should be used.

**Describe alternatives you've considered**

I guess fixing this at the migration tool would be an option but showing a good error is nice regardless as not everyone will use the tool.

**Are you able to assist to bring the feature to reality?**

Potentially.

**Additional context**

Storybook 6.4.

**Comment by shilman** [comment]
@bebraw did you add `@storybook/react` based on your side-knowledge of the on-demand store, or due to some earlier alpha/beta documentation? i'm just wondering how many users this affects, since AFAIK the release version works in "legacy" mode with  no `framework` specified, or in v7 mode with `framework` specified, and adding the framework to `addons` was something that only existed for a few weeks during the prerelease period

**Comment by bebraw** [comment]
For reference, here's the full config (working):

```js
/// <reference types="node" />

module.exports = {
  staticDirs: ['./assets', '../test-data/data'],
  framework: '@storybook/react',
  features: {
    babelModeV7: true,
    emotionAlias: false,
    // For this to work, storiesOf cannot be used anymore
    // Use https://storybook.js.org/docs/react/api/csf instead
    // storyStoreV7: true,
  },
  core: {
    builder: 'webpack5',
  },
  stories: [
    '../packages/**/stories/*.stories.tsx',
    '../analytics/**/stories/*.stories.tsx',
  ],
  addons: [
    '@storybook/addon-essentials',
    '@storybook/addon-a11y',
    // It's not clear if this works with Storybook 6.4
    // 'storybook-addon-performance/register',
  ],
  managerWebpack: (config) => {
    // This feels like a bug in Storybook. @storybook/store depends
    // on path but manager config doesn't have a shim for it!
    config.resolve = {
      ...config.resolve,
      fallback: {
        ...config.resolve.fallback,
        path: require.resolve('path-browserify'),
      },
    };

    return config;
  },
};
```

I haven't enabled on-demand store as I'll have to port the project to use CSF first so it seems unrelated.

Earlier in 6.3, `@storybook/react` was in `addons` in this particular project but as mentioned above, it was giving a cryptic crash from Storybook internals that I resolved by moving to use the `framework` field.

**Comment by shilman** [comment]
I'm surprised `@storybook/react` was added in a 6.3 project and that it worked. Do you happen to know where that came from?

**Comment by bebraw** [comment]
It seems `@storybook/react` was used in `addons` with the following version `"@storybook/react": "^6.3.12",` before I did the update.

**Comment by shilman** [comment]
@ndelangen you made a great suggestion about this in the triage meeting, which is to catch the error when the preset is applied and display a well-formatted message. however, re-reading this issue, the error occurs in webpack after the preset is run so i'm not sure it applies. WDYT?

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if this is still relevant in SB 7.x.
