### ISSUE TITLE
HTML: Format/prettify dynamic source snippets

### ISSUE THREAD

**Issue by archfisv** [storybookjs/storybook#16926]
**Is your feature request related to a problem? Please describe**
According to https://github.com/storybookjs/storybook/pull/15748 - that works well, but the code is not formatted/prettified (always one-liner).

**Describe the solution you'd like**
Add a configuration option like `prettierEnabled` (with true by default)

**Describe alternatives you've considered**
None

**Are you able to assist to bring the feature to reality?**
I can be a tester

**Additional context**
![image](https://user-images.githubusercontent.com/84845637/144895948-60ae9a3f-3075-4c7f-b9e8-7ac992ca01c1.png)

**Comment by shilman** [comment]
closing as dupe to #8078
