### ISSUE TITLE
Codemods can fail to run if there's Babel configuration in project root

### ISSUE THREAD

**Issue by bebraw** [storybookjs/storybook#16933]
**Is your feature request related to a problem? Please describe**

I have a project I am upgrading from `storiesOf` to CFP.  It's a monorepo with many stories and initially I ran `node_modules/.bin/sb migrate storiesof-to-csf --glob="packages/**/*.stories.tsx"`. This yielded a Babel error about `regeneratorRuntime` and failed.

After a while, I realized the issue was caused by **babel.config.js** that was set at the project root for compilation purposes. Renaming that file temporarily let the codemod run successfully but it wasn't obvious to figure out.

**Describe the solution you'd like**

When running a codemod, it might be a good idea to perform a check against possibly existing Babel configuration and then at least warn the user so they understand that execution might fail because of this.

**Describe alternatives you've considered**

I suppose another alternative would be to skip existing Babel configuration somehow as now it seems to be picking it up no matter what.

**Are you able to assist to bring the feature to reality?**

Potentially.

**Additional context**

Storybook 6.4.

**Comment by shilman** [comment]
This seems like a double-edged sword. If we use the user's babel config and it causes things to fail, that's no good. If we don't use the user's config and they are using language features that require the config, that's no good either.

I think the best bet here is to detect the user's config and warn them about what's going on with instructions on how to configure. How about something like:

> We've detected a custom babel config in your project `/path/to/config`
> By default Storybook ignores user babel config. To opt-in, run the same migrate command with
>
> `sb migrate --custom-babel-config [args]

**Comment by texpert** [comment]
In my case, on Storybook 6.2.9, the storiesof-to-csf was failing with a `prettier` error:

```
TypeError: Patterns must be a string or an array of strings
    at assertPatternsInput$1 (/Users/thunder/dev/holacracyone/glassfrog/node_modules/prettier/index.js:37304:11)
    at generateGlobTasks (/Users/thunder/dev/holacracyone/glassfrog/node_modules/prettier/index.js:37330:3)
    at Function.sync (/Users/thunder/dev/holacracyone/glassfrog/node_modules/prettier/index.js:37422:21)
    at apply (/Users/thunder/dev/holacracyone/glassfrog/node_modules/prettier/index.js:57508:43)
    at memoizedSearch (/Users/thunder/dev/holacracyone/glassfrog/node_modules/prettier/index.js:16612:23)
    at map (/Users/thunder/dev/holacracyone/glassfrog/node_modules/prettier/index.js:57494:12)
    at Array.map (<anonymous>)
    at Object.apply (/Users/thunder/dev/holacracyone/glassfrog/node_modules/prettier/index.js:57484:56)
    at Object.loadPlugins (/Users/thunder/dev/holacracyone/glassfrog/node_modules/prettier/index.js:16612:23)
    at /Users/thunder/dev/holacracyone/glassfrog/node_modules/prettier/index.js:57540:28
```

Temporarily removing `babel.config.js` also has helped.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
