### ISSUE TITLE
Breaking change in @storybook/router from 6.3.x to 6.4.x

### ISSUE THREAD

**Issue by floyd-may** [storybookjs/storybook#16936]
**Describe the bug**
Version 6.3.x of `@storybook/router` depends on `react-router-dom` version 5.x. However, version 6.4.x depends on `react-router-dom` at version 6, causing version conflicts. Therefore the default behavior of installing via semver-compatible specification introduces breaking changes from 6.3.x to 6.4.x.

For instance, my app uses `react-router-dom` at version 5.x. Upgrading `@storybook/router` from 6.3.x to 6.4.x installs `react-router-dom` at 6.x, causing two copies of it in my dependency tree. Then, my stories break, since `react-router-dom` 5.x to 6.x introduces breaking changes (as is allowed in major upgrades).

This seems like something that may be better handled via peerDependencies than a direct dependency possibly? That way you create the option to allow either version of `react-router-dom`.

**Comment by shilman** [comment]
closing as dupe to #16837

**Comment by floyd-may** [comment]
@shilman apologies for the dupe, I didn't see it in my search before making a new issue.

**Comment by shilman** [comment]
@floyd-may no worries -- probably because it was closed!
