### ISSUE TITLE
storyStoreV7 feature is not compatible with addon-storyshots

### ISSUE THREAD

**Issue by monachilada** [storybookjs/storybook#16939]
**Describe the bug**
When enabling the `storyStoreV7` option in 6.4, previously working `@storybook/addon-storyshots` configurations return a message of "Your test suite must contain at least one test." when attempting to creating the storyshots in the test suite.

**To Reproduce**
The following is included in `.storybook/main.js`

```
features: {
    storyStoreV7: true,
}
```

and `@storybook/addon-storyshots` is configured with default settings.

**System**
  System:
    OS: macOS 11.5.1
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 15.14.0 - ~/.nvm/versions/node/v15.14.0/bin/node
    Yarn: 1.22.15 - ~/.yarn/bin/yarn
    npm: 7.7.6 - ~/.nvm/versions/node/v15.14.0/bin/npm
  Browsers:
    Chrome: 96.0.4664.55
    Firefox: 93.0
    Safari: 14.1.2
  npmPackages:
    @storybook/addon-storyshots: ^6.4.8 => 6.4.8
    @storybook/builder-webpack5: ^6.4.8 => 6.4.8
    @storybook/manager-webpack5: ^6.4.8 => 6.4.8
    @storybook/react: ^6.4.8 => 6.4.8

**Comment by shilman** [comment]
See the following workaround https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#storyshots-compatibility-in-the-v7-store

**Comment by monachilada** [comment]
Missed that one, thanks for the tip! This can be closed in that case.
