### ISSUE TITLE
Replace all references to "normal" style with "light" style in codebase

### ISSUE THREAD

**Issue by richorrichard** [storybookjs/storybook#16937]
**Is your feature request related to a problem? Please describe**
The documentation has been updated to reference Storybook's built-in "light" theme instead of a "normal" theme, but there is currently mixed use of "normal" and "light" themes in the codebase.  

**Describe the solution you'd like**
1. Find all named references to the "normal" theme.
2. Replace all with references to the "light" theme.
3. Update tests and snapshots as needed.
3. Verify that end-user installs that override/modify the "normal" theme continue to work as expected.

**Describe alternatives you've considered**
n/a

**Are you able to assist to bring the feature to reality?**
Yes please! I'd love to take on this issue. I might need some help from a core team member to make sure that changes I make don't cause unforseen issues 

**Additional context**
n/a

**Comment by shilman** [comment]
Shiver me timbers!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-alpha.10 containing PR #17034 that references this issue. Upgrade today to the `@future` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Gadzooks!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.10-alpha.0 containing PR #17034 that references this issue. Upgrade today to the `@prerelease` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

**Comment by shilman** [comment]
Ta-da!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.10 containing PR #17034 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```
