### ISSUE TITLE
Expose `qs`' `depth` configuration option for the Manager

### ISSUE THREAD

**Issue by jam-awake** [storybookjs/storybook#16930]
**Is your feature request related to a problem? Please describe**

Storybook uses `qs` to encode/decode a story's `args` to the URL's corresponding query parameter. However, `qs` by default stops decoding nested objects once it hits a depth of 5. [Per their docs](https://github.com/ljharb/qs#parsing-objects),

> By default, when nesting objects qs will only parse up to 5 children deep. 
> This means if you attempt to parse a string like 'a[b][c][d][e][f][g][h][i]=j' your resulting object will be:
>
> `{ a: { b: { c: { d: { e: { f: { "[g][h][i]": "j" } } } } } } }`
>
> This depth can be overridden by passing a depth option to `qs.parse(string, [options])`:
> The depth limit helps mitigate abuse when qs is used to parse user input, and it is recommended to keep it a reasonably small number.

**Describe the solution you'd like**

I would like Storybook to expose a configuration value that allows a user of this library to set `qs`' `depth` option to something higher than 5. I'd guess that this config value could be set in the `manager.js` file.

**Describe alternatives you've considered**

The first alternative I have found is to change what value I use for a story's `args` value, so that the object's number of levels is always less than 5. For my particular use case, this is harder then the otherwise "easy" fix to support the `depth` config value directly. 

The second alternative is to use a local fork of Storybook with the requested changes. That's not ideal.

**Are you able to assist to bring the feature to reality?**

I might.

**Additional context**

Let's say a coworker wants to discuss a story that has a particular state with me. That coworker might send me the URL of the story after using the Controls addon to set the state. I would receive the URL, paste it into my browser, and then see the story in the same state as my coworker. At least, that's what should happen.

Due to the `qs` limit above, that's not what happens for objects with a nesting level greater than 5. Rather, the page will load, `qs` will stop parsing the object prematurely, and the story will revert to its default state. So, I'll have to ask my coworker what changes were made.

For a reproducible example, using [Storybook's 'Basic' Controls page](https://next--storybookjs.netlify.app/official-storybook/?path=/story/addons-controls--basic), I can edit the `JSON` arg as a raw string and paste the below content into it:

```
{
  "1": {
    "2": {
      "3": {
       "4": {
         "5": {
          "6": true
          }
        }
     }
   }
  }
}
```

Once edited, the URL will change to include the object's parameters. If I copy that URL and paste it into a new tab, Storybook will reset the story back to its default state rather than keeping the value I originally inputted.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if this is still relevant in SB 7.x.

**Comment by jam-awake** [comment]
I ended up creating a custom addon to workaround this problem.
