### ISSUE TITLE
addon/a11y throw error  globalWindow.__STORYBOOK_STORY_STORE__.loadStory is not a function

### ISSUE THREAD

**Issue by iroy2000** [storybookjs/storybook#16944]
**Describe the bug**

I'm using 
`"@storybook/addon-a11y": "^6.1.21"` 
with
`"@storybook/react": "^6.1.21"`

And it is my adds on

```
  addons: [
    '@storybook/addon-docs',
    '@storybook/addon-controls',
    '@storybook/addon-essentials',
    '@storybook/addon-a11y',
    '@storybook/addon-knobs'
  ],
```

When I start clicking on Accessibility tab of the storybook, I only see this

![Screen Shot 2021-12-07 at 4 39 41 PM](https://user-images.githubusercontent.com/487520/145127807-34d3b319-7702-4d59-911d-f9e179364aab.png)

When I look at the console, I saw the following

![Screen Shot 2021-12-07 at 4 35 33 PM](https://user-images.githubusercontent.com/487520/145127602-4cf4f367-33fe-4ee3-a0f5-298cefab4d23.png)

**To Reproduce**

1) Install version `^6.1.21` of the above
2) Click on the Accessibility tab
3) Observe your console, it will show the error mentioned

**System**

```
  System:
    OS: macOS 11.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Binaries:
    Node: 14.15.4 - ~/.volta/tools/image/node/14.15.4/bin/node
    Yarn: 1.22.10 - ~/.volta/tools/image/yarn/1.22.10/bin/yarn
    npm: 6.14.10 - ~/.volta/tools/image/node/14.15.4/bin/npm
  Browsers:
    Chrome: 96.0.4664.93
    Edge: 96.0.1054.43
    Safari: 15.0
  npmPackages:
    @storybook/addon-a11y: ^6.1.21 => 6.4.8
    @storybook/addon-actions: ^6.1.21 => 6.3.12
    @storybook/addon-essentials: ^6.1.21 => 6.3.12
    @storybook/addon-knobs: ^6.1.21 => 6.3.1
    @storybook/addon-links: ^6.1.21 => 6.3.12
    @storybook/react: ^6.1.21 => 6.3.12
```

**Comment by zesu22** [comment]
Did you find any workaround for this? @iroy2000

**Comment by iroy2000** [comment]
Yes it is resolved , it you look at my npmPackages below, I just downgrade my version to 6.3.12 and it solved the issue.

```
  npmPackages:
    @storybook/addon-a11y: ^6.1.21 => 6.4.8
    @storybook/addon-actions: ^6.1.21 => 6.3.12
    @storybook/addon-essentials: ^6.1.21 => 6.3.12
    @storybook/addon-knobs: ^6.1.21 => 6.3.1
    @storybook/addon-links: ^6.1.21 => 6.3.12
    @storybook/react: ^6.1.21 => 6.3.12
```

**Comment by existe-deja** [comment]
That's not a solution! It still happening in 6.4.9

**Comment by shilman** [comment]
@existe-deja have you updated all your storybook packages to 6.4.x? this error looks like it is due to a mixture of 6.4 and 6.3 packages, which is not expected to work.
