### ISSUE TITLE
How can I have my `Primary` and `ArgsTable` components refer to a different component in a non MDX page?

### ISSUE THREAD

**Issue by jimmy-e** [storybookjs/storybook#16958]
**Is your feature request related to a problem? Please describe**
I am trying to create a story for a component. For example:

Button.stories.tsx:
```js
import React from 'react';
import {
  ArgsTable,
  Description,
  Primary,
  Title,
} from '@storybook/addon-docs';
import { Meta, Story } from '@storybook/react/types-6-0';
import { Button as ButtonComponent, ButtonProps } from './Button';

export default {
  argTypes: {
    backgroundColor: { control: 'color' },
  },
  component: ButtonComponent,
  parameters: {
    docs: {
      page: () => (
        <>
          <Title />
          <Description />
          <Primary />
          <ArgsTable />
        </>
      ),
    },
  },
  title: 'Example/Button',
} as Meta;

export const ButtonParentComponent: Story<ButtonProps> = (args) => (
  <>
    <h1>hello world</h1>
    <ButtonComponent {...args} />
  </>
);
```

However, I want to be able to have the `Primary` and `ArgsTable` addon-blocs not refer to `ButtonParentComponent` but instead refer to `ButtonComponent`. However, I still need `ButtonParentComponent` to be the component that is shown in my canvas.

The documentation currently seems unclear on how I can do this. It looks like I can refer to the story's name when using MDX, as mentioned [here](https://storybook.js.org/docs/react/writing-docs/doc-blocks#for-stories), but it is unclear how I can do this for a non MDX file.

**Describe the solution you'd like**
How can I have my `Primary` and `ArgsTable` components refer to a different component in a non MDX page?

**To reproduce:**
1. Clone [this repo](https://github.com/jimmy-e/storybook-debug-v2)
2. Run `yarn && yarn storybook`

**Comment by shilman** [comment]
The `component` field that you add to the default export is what's used to generate `ArgTypes` that are associated with each story in the file. So you can make that `ButtonComponent` as you've done above.

As for referencing something other than the first story in the file, if you want to remix the DocsPage that's an option:

https://storybook.js.org/docs/react/writing-docs/docs-page#remixing-docspage-using-doc-blocks

However, if it was me I'd probably just re-order the stories and use the `DocsPage` that ships with Storybook

**Comment by jimmy-e** [comment]
> The `component` field that you add to the default export is what's used to generate `ArgTypes` that are associated with each story in the file. So you can make that `ButtonComponent` as you've done above.
> 
> As for referencing something other than the first story in the file, if you want to remix the DocsPage that's an option:
> 
> https://storybook.js.org/docs/react/writing-docs/docs-page#remixing-docspage-using-doc-blocks
> 
> However, if it was me I'd probably just re-order the stories and use the `DocsPage` that ships with Storybook

Thank you @shilman but that does not appear to be the case. In the above example, the `Primary` and `ArgsTable` components are being derived from `ButtonParentComponent`, not `ButtonComponent`. If you want, you can reproduce the problem here:

1. Clone [this repo](https://github.com/jimmy-e/storybook-debug-v2)
2. Run `yarn && yarn storybook`

**Comment by jimmy-e** [comment]
@shilman when you have a chance can you please take a look at the reproduce-able example? This is an important issue that our company is trying to resolve in order to use Storybook. Thanks!

**Comment by shilman** [comment]
Thanks for the reproduction. I was able to get it working through several changes:

Updating the custom DocsPage to use:

```
<ArgsTable story="^" />
```

Adding `typescript`, which is a required peer dependency of `react-docgen-typescript`:

```
yarn add typescript -D
```

Updating the type signature of your component from:

```
export const Button: FC<ButtonProps> = ...
```

To:

```
export const Button = ({ ... }: ButtonProps) => ...
```

I didn't have time to figure out which are issues with Storybook itself vs. which are problems with `react-docgen-typescript`. Any help further debugging or improving documentation would be much appreciated!

**Comment by jimmy-e** [comment]
Thanks @shilman for the quick response!

I believed I followed your instructions on [this branch](https://github.com/jimmy-e/storybook-debug-v2/pull/1/files), however, when I run storybook, I still see the "hello world" title in the docs component (see below gif). Was there something I did wrong to reproduce this?

![storybookBug](https://user-images.githubusercontent.com/25621956/148834392-17183006-fe73-4e9e-8fa6-188f0746f5e7.gif)

**Comment by jimmy-e** [comment]
Issue resolved: The additional thing that was needed was to provide an extra component and reference it's name in the `PrimaryComponent`. Please see [this pr](https://github.com/jimmy-e/storybook-debug-v2/pull/1).

```js
import React from 'react';
import {
  ArgsTable,
  Description,
  Primary,
  Title,
} from '@storybook/addon-docs';
import { Meta, Story } from '@storybook/react/types-6-0';
import { Button as ButtonComponent, ButtonProps } from './Button';

export const Btn: Story<ButtonProps> = (args) => <ButtonComponent {...args} />;

export default {
  argTypes: {
    backgroundColor: { control: 'color' },
  },
  component: ButtonComponent,
  parameters: {
    docs: {
      page: () => (
        <>
          <Title />
          <Description />
          <Primary name="Btn"/>
          <ArgsTable story="^" />
        </>
      ),
    },
  },
  title: 'Example/Button',
} as Meta;

export const ButtonParentComponent: Story<ButtonProps> = (args) => (
  <>
    <h1>hello world</h1>
    <ButtonComponent {...args} />
  </>
);
```
