### ISSUE TITLE
Storybook & Appetize.io integration issue

### ISSUE THREAD

**Issue by smgv** [storybookjs/storybook#16994]
### Discussed in https://github.com/storybookjs/storybook/discussions/16993

<div type='discussions-op-text'>

<sup>Originally posted by **smgv** December 13, 2021</sup>
Hi,

We are creating one project in react native cli and we are trying to integrate the storybook in it with the Appetize.io. To get the storybook along with the respective device emulator in it. So we can test our components in a web browser.

We are actually trying to set up the project as per the given document link provided from appetize.io website but we are finding difficulties to set up the project . 

Below are the challenges: 
1. What folders to create?
2. What path of storybook to set in index.js ? (bcoz when we run $ npm run storybook how it will know to run which file)
3. How to write the stories for each component so that it can be rendered in the storybook ?
4. What will be the deployment steps?
5. How to get both the type of emulators i.e. ios and android for comparison ?

we are referring the below link:
https://medium.com/storybookjs/storybook-for-mobile-applications-97e3a229fb3c

appetize.io -> https://appetize.io/

So I kindly request you to provide your assistance or implementation guide.</div>

**Comment by dannyhw** [comment]
@smgv appetize support with react is already possible with @storybook/native, I recommend checking out that package.

it's been discussed here in this issue also:


https://github.com/storybookjs/native/issues/66

**Comment by shilman** [comment]
Closing this for now. Please let me know if there's more to be done here!
