### ISSUE TITLE
Adding storybook shows Type '{ class: string; }' is not assignable to type error

### ISSUE THREAD

**Issue by abhic91** [storybookjs/storybook#16998]
**Describe the bug**
I am using vue3/ts/vite/volar. When I add storybook to the app either using `npx sb init` or `npx sb@next init --builder storybook-builder-vite`, vs code assumes I am using react.

For eg:

When I do `<div class=""></div>` I get 

```
Type '{ class: string; }' is not assignable to type 
'DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>'.
  Property 'class' does not exist on type 'DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>'. 
Did you mean 'className'?ts(2322)

```
When I hover over a `div`, I see 

```
(property) div: React.DetailedHTMLProps<React.HTMLAttributes<HTMLDivElement>, HTMLDivElement>
```
in vs code.

This is not a React app. This is a vue project with `.vue` file.  Also, I don't see any errors when I send wrong data type as props.

This happens only when I add storybook.

**To Reproduce**
 - Create app using vite `npm init vite@latest` -> vue with ts
 - Add storybook using `npx sb init` or `npx sb@next init --builder storybook-builder-vite`. This happens for both commands.

**System**
```
Environment Info:

  System:
    OS: macOS 11.6
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 14.17.2 - ~/.nvm/versions/node/v14.17.2/bin/node
    npm: 8.1.2 - ~/.nvm/versions/node/v14.17.2/bin/npm
  Browsers:
    Chrome: 96.0.4664.93
    Firefox: 94.0.1
    Safari: 15.0
  npmPackages:
    @storybook/addon-actions: ^6.4.9 => 6.4.9
    @storybook/addon-essentials: ^6.4.9 => 6.4.9
    @storybook/addon-links: ^6.4.9 => 6.4.9
    @storybook/vue3: ^6.4.9 => 6.4.9
```

**Comment by shilman** [comment]
Please file Vite-related issues in https://github.com/eirslett/storybook-builder-vite/

Closing this for now--please let me know if you think this ISN'T Vite-related and I'll reopen. Thank you! 🙏

**Comment by abhic91** [comment]
@shilman This isn't storybook-builder-vite related. https://github.com/eirslett/storybook-builder-vite/issues/178

Adding this fixed it. See here(https://github.com/johnsoncodehk/volar/discussions/592)

```
// tsconfig.json
{
  "compilerOptions": {
    // ...
    "types": [
      "vite/client", // if using vite
      // ...
    ]
  }
}
```

**Comment by shilman** [comment]
@abhic91 Should I reopen? Is there a fix for Storybook or is it more of a documentation issue?
