### ISSUE TITLE
Story source incorrectly rendered as "MDXCreateElement"

### ISSUE THREAD

**Issue by robcaldecott** [storybookjs/storybook#16999]
**Describe the bug**
Note that this issue relates to https://github.com/storybookjs/storybook/issues/12596 (which has been closed.)

When using an MDX story, certain decorators will incorrectly render the template component as `MDXCreateElement`.

![image](https://user-images.githubusercontent.com/796702/145806272-01122aac-f772-4e54-a511-7af8c07780af.png)

```mdx
import { Meta, Story, Canvas } from "@storybook/addon-docs";
import { IntlProvider } from "react-intl";
import { Button } from "./Button";

<Meta title="Button MDX" component={Button} />

export const Template = (args) => <Button {...args} />;

<Canvas withSource="open">
  <Story name="Works" args={{ primary: true, label: "Code example works" }}>
    {Template.bind({})}
  </Story>
</Canvas>

<Canvas withSource="open">
  <Story
    name="No Display Name"
    args={{ primary: true, label: "No Display Name" }}
    decorators={[
      (Story) => (
        <IntlProvider locale="en">
          <Story />
        </IntlProvider>
      ),
    ]}
  >
    {Template.bind({})}
  </Story>
</Canvas>

<Canvas withSource="open">
  <Story
    name="Story function"
    args={{ primary: true, label: "MDXCreateElement" }}
    decorators={[(Story) => <IntlProvider locale="en">{Story()}</IntlProvider>]}
  >
    {Template.bind({})}
  </Story>
</Canvas>
```

In this example I am using `react-intl` `IntlProvider` as a decorator. Without this it works (i.e. using a `div` is fine as long as you call `Story()` instead of rendering as `<Story />`.

**To Reproduce**
https://github.com/robcaldecott/storybook-display-name

**System**
```
Environment Info:

  System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v14.17.0/bin/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm
  Browsers:
    Chrome: 96.0.4664.93
    Firefox: 92.0.1
    Safari: 14.1.2
  npmPackages:
    @storybook/addon-actions: ^6.4.9 => 6.4.9 
    @storybook/addon-essentials: ^6.4.9 => 6.4.9 
    @storybook/addon-links: ^6.4.9 => 6.4.9 
    @storybook/node-logger: ^6.4.9 => 6.4.9 
    @storybook/preset-create-react-app: ^3.2.0 => 3.2.0 
    @storybook/react: ^6.4.9 => 6.4.9
```

**Comment by Ponjimon** [comment]
Bump

**Comment by maneike** [comment]
Excluding decorators from the source code did it for me.
```
 docs: {
          source: {
            type: 'dynamic',
            excludeDecorators: true,
          },
        },
```
https://github.com/storybookjs/storybook/issues/12022#issuecomment-859540813

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
