### ISSUE TITLE
Generate `storybook-report.json` in static builds

### ISSUE THREAD

**Issue by ghengeveld** [storybookjs/storybook#16990]
**Is your feature request related to a problem? Please describe**

Since the `--static-dir` CLI flag was superseded in 6.4 by the `staticDirs` option in `.storybook/main.js`, there is no simple way to determine which static directories were used, making it harder to do automatic change detection for e.g. Chromatic's TurboSnap. An additional complication is that the original source code (including the Storybook config dir) might not be available, but only the statically built Storybook.

**Describe the solution you'd like**

I would like to add a new `--report` flag to the `build-storybook` CLI which writes a `storybook-report.json` file to the output directory (e.g. `storybook-static`). This file would contain a JSON dump of all contextual values processed by the CLI, including things like configuration values, file sizes and whatnot. This would be similar to the [`--report` flag](https://github.com/chromaui/chromatic-cli/pull/475) in the Chromatic CLI.

**Describe alternatives you've considered**

There’s a static analysis called `ConfigFile` in `@storybook/csf-tools` that could pull out the `staticDirs` value. We could pipe that to a file instead.

**Are you able to assist to bring the feature to reality?**

Of course.

**Comment by shilman** [comment]
I believe this was fixed with the `--webpack-stats-json` option. Closing this for now. Please let me know if there's more to be done here!
