### ISSUE TITLE
The addons-darwin-arm64.tgz file was not found

### ISSUE THREAD

**Issue by 7zf001** [storybookjs/storybook#16991]
**Is your feature request related to a problem? Please describe**

when I use Apple M1 Pro to install `@storybook/addon-actions`, that will report an error:

![image](https://user-images.githubusercontent.com/24474049/145745449-c307daf4-d478-497b-b10e-945300ea319f.png)

**Describe the solution you'd like**
Are M1 systems not supported yet?

**Describe alternatives you've considered**
no.

**Are you able to assist to bring the feature to reality?**
no

**Additional context**
Chip: Apple M1 Pro

**Comment by PatrickBenz09** [comment]
For anyone having this same problem, install nvm and run `arch -x86_64 zsh` this should fix your problem. [ref](https://stackoverflow.com/questions/68896696/having-trouble-installing-npm-on-mac-m1)

**Comment by ronaatxendit** [comment]
will it also solves people with M1 workstation? @PatrickBenz09
