### ISSUE TITLE
Angular: Component Property Value rendered as code (with new renderer)

### ISSUE THREAD

**Issue by rothsandro** [storybookjs/storybook#17001]
**Describe the bug**
I have an Angular Component with a property that has a calculated value that is used in the template.
When starting Storybook with a story for that component it will generate controls for all inputs, properties, etc.

```ts
class ButtonComponent {
  text = "Hello " + "World";
}
```

Instead of rendering "Hello World" as the button text it renders the actual code and also shows that code as the control value:
<img width="876" alt="sb-btn" src="https://user-images.githubusercontent.com/16229645/145819004-9b8b3c58-1111-4ae8-842d-0d9199e532ec.png">

I would expect to see "Hello World" rendered by default. Disabling the control does not help, the rendering is still broken:

```ts
export default {
  // ...
  argTypes: {
    text: { control: { disable: true } },
  },
} as Meta;
```

The bug does not occur when enabling the Storybook Angular Legacy Rendering (but changing the value in the control input will not rerender the component).

**To Reproduce**
Repo: https://github.com/rothsandro/sb-ng-args-issue
Deployment: https://jovial-brown-2e9715.netlify.app/?path=/story/example-button--primary

**System**
```
  System:
    OS: macOS 12.0
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 3.1.1 - ~/.nvm/versions/node/v16.13.0/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Safari: 15.0
  npmPackages:
    @storybook/addon-actions: ^6.5.0-alpha.3 => 6.5.0-alpha.3 
    @storybook/addon-docs: ^6.5.0-alpha.3 => 6.5.0-alpha.3 
    @storybook/addon-essentials: ^6.5.0-alpha.3 => 6.5.0-alpha.3 
    @storybook/addon-links: ^6.5.0-alpha.3 => 6.5.0-alpha.3 
    @storybook/angular: ^6.5.0-alpha.3 => 6.5.0-alpha.3 
    @storybook/builder-webpack5: ^6.5.0-alpha.3 => 6.5.0-alpha.3 
    @storybook/manager-webpack5: ^6.5.0-alpha.3 => 6.5.0-alpha.3 
```

**Comment by rothsandro** [comment]
I just found #16865, seems to be the same problem.

**Comment by ChristopherSO** [comment]
If anyone reaches here looking for a solution, I discovered the workaround of placing all the property initializations that require to be evaluated in the constructor. This may look like unset properties in the doc addon but at least will allow continuing working.

**Comment by shilman** [comment]
Yee-haw!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-alpha.57 containing PR #19935 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
