### ISSUE TITLE
Missing favicon when using staticDirs configuration option

### ISSUE THREAD

**Issue by dzwarg** [storybookjs/storybook#17008]
**Describe the bug**
I have a storybook that contains a file: `favicon.ico`, and it is served with my running storybook when the `-s public` CLI option is provided. When I update the configuration to use `staticDirs: [ '../public' ]`, and remove the `-s public` CLI option, my favicon is not loaded, and the default storybook favicon is served instead.

I would expect the favicon.ico file to be served when using the `staticDirs` configuration option.

**To Reproduce**
 - Add a custom `favicon.ico` to any version of storybook running 6.4.9. 
 - Run the storybook in the CLI with `staticDirs` set to the folder containing the `favicon.ico`.
 - Observe the default Storybook favicon served.

**System**
```
Environment Info:

  System:
    OS: Linux 5.10 Alpine Linux
    CPU: (6) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 12.22.5 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.14 - /usr/local/bin/npm
```

**Additional context**
It looks like favicons are only processed in the branch that uses `options.staticDir`, based on [server-static.ts L54](https://github.com/storybookjs/storybook/blob/next/lib/core-server/src/utils/server-statics.ts#L54)

**Comment by shilman** [comment]
@oscard0m Is this something you can take a look at? 🙏

**Comment by michaelfaith** [comment]
I'm experiencing this as well. Glad it's not just me.

**Comment by dzwarg** [comment]
This is only a problem when running the storybook in development mode. When the static assets are compiled and served statically, the favicon is correct.

**Comment by cakeinpanic** [comment]
Experiencing the same, annoying :(
Switched to base64 for now, waiting for the fix

**Comment by shilman** [comment]
Yo-ho-ho!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-alpha.17 containing PR #17241 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Yowza!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.13 containing PR #17241 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```
