### ISSUE TITLE
Vue3 Storyshots are not accurately recorded in v6.4 and v6.5

### ISSUE THREAD

**Issue by damwhit** [storybookjs/storybook#17005]
**Describe the bug**
app: vue3
addon: storyshots

After upgrading storyshots from `v6.3.7` to `v6.4.0-beta.14` in order to fix [#14655](https://github.com/storybookjs/storybook/issues/14655), the snapshots are no longer accurate.

Notice in this screenshot that `Delete` and `Transfer Ownership` do not have accurate markup (the markup was correct in `6.3.7`)
* the markup for `Delete` has been replaced with the markup from `Reload`
* the markup for `Transfer Ownership` has been replaced with the markup from `Delete`

<img width="1645" alt="Screen Shot 2021-12-13 at 12 02 45 PM" src="https://user-images.githubusercontent.com/13105577/145856610-d8a4aa0d-74e5-4fc2-bac0-a2414071c50e.png">

**Additional context**
* also tested in `v6.5.0-alpha.3` and `v6.4.1` and got the same incorrect snapshots
* double checked that all directions for vue 3 were followed here: https://storybook.js.org/addons/@storybook/addon-storyshots 

Relevant dependencies and scripts in `package.json`:
```json
{
  "devDependencies": {
    "@storybook/addon-storyshots": "^6.4.0-beta.14",
    "@storybook/vue3": "^6.4.0-beta.14",
    "jest": "^26",
    "jest-css-modules-transform": "^4.3.0",
    "vue-jest": "5.0.0-alpha.10"
  },
  "dependencies": {
    "vue": "^3.2.2",
    "vuex": "^4.0.2"
  },
  "scripts": {
    "storybook": "start-storybook -p 6006",
    "build-storybook": "build-storybook",
    "test": "jest"
  }
}
```

`Storyshots.test.js`
```js
import initStoryshots from '@storybook/addon-storyshots';

initStoryshots();
```

`jest.config.js`:
```js
module.exports = {
  moduleNameMapper: {
    '\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$': '<rootDir>/__mocks__/fileMock.js',
  },
  transform: {
    '^.+\\.js?$': 'babel-jest',
    '^.+\\.(vue)$': '<rootDir>/node_modules/vue-jest',
    '.+\\.(css|styl|less|sass|scss)$': '<rootDir>/node_modules/jest-css-modules-transform',
  },
  transformIgnorePatterns: ['/node_modules/(?!(@storybook/.*\\.vue$))'],
  moduleFileExtensions: ['vue', 'js', 'json', 'node'],
  modulePathIgnorePatterns: ["vendor", "cypress"],
};
```

Please let me know if any additional context would be helpful. This is in a private repo run on docker (ruby:2.6 image which is linux/debian).

**Comment by jnorris-cs** [comment]
This is how I got around this issue.

import initStoryshots, { Stories2SnapsConverter } from '@storybook/addon-storyshots'
import { mount } from '@vue/test-utils'
import { resolve } from 'path'

initStoryshots({
 ...
  test: ({ story, context, stories2snapsConverter }) => {
    const snapshotFileName = resolve(
      __dirname,
      stories2snapsConverter.getSnapshotFileName(context)
    )

    const storyElement = story.render()
    const wrapper = mount(storyElement)
    expect(wrapper.element).toMatchSpecificSnapshot(snapshotFileName)
  },
})

**Comment by jnorris-cs** [comment]
@kennyyS The solution I posted is working for me, why did it not work for you? I can send you my whole test file if that is helpful.

**Comment by jagoncalves14** [comment]
@jnorris-cs , your solution indeed fixes the issue. Although, my snapshots are being renamed to a *.storyshot extension while I wanted them to be *.snap.
Do you by any chance now to do this?

Thank you

**Comment by budet-b** [comment]
> @kennyyS The solution I posted is working for me, why did it not work for you? I can send you my whole test file if that is helpful.

Yes I think that would be helpful to have the whole file if possible 🙏 @jnorris-cs

**Comment by jnorris-cs** [comment]
@budet-b Here is my whole file.

```
import initStoryshots, { Stories2SnapsConverter } from '@storybook/addon-storyshots'
import { mount } from '@vue/test-utils'
import { resolve } from 'path'

initStoryshots({
  suite: 'Automated Storybook Snapshots',
  configPath: '.config/storybook',
  stories2snapsConverter: new Stories2SnapsConverter({
    snapshotExtension: '.storyshot',
    storiesExtensions: ['.js', '.ts', '.mdx'],
  }),
  storyKindRegex: /^Component/,
  test: ({ story, context, stories2snapsConverter }) => {
    const snapshotFileName = resolve(
      __dirname,
      stories2snapsConverter.getSnapshotFileName(context).replace('src/components/', 'stories/')
    )

    const storyElement = story.render()
    const wrapper = mount(storyElement)
    expect(wrapper.element).toMatchSpecificSnapshot(snapshotFileName)
  },
})

```

@jagoncalves14 
This part determines where the file goes. You can adjust as desired.
```
 const snapshotFileName = resolve(
      __dirname,
      stories2snapsConverter.getSnapshotFileName(context).replace('src/components/', 'stories/')
    )
    ```
    
    This part determines the file extension. changing to .snap would give you the result you want.
    ```
        snapshotExtension: '.storyshot',
```

**Comment by jnorris-cs** [comment]
@jagoncalves14 Glad you are making some process. I agree that this should work out of the box and not need some elaborate workaround.

**Comment by jagoncalves14** [comment]
I have just updated Storybook and all its addons/plugins this morning from 6.5.0-alpha.39 to version 6.5.0-alpha.41. 
Looks like the main issue in the thread got fixed. 🙌

**Comment by thedamon** [comment]
> @budet-b Here is my whole file.
> 
> ```

This worked for me in that it got the correct output in the correct files, but it's not including some decorators that I specifically made for testing. Is that expected? is there a way to include decorators?

**Comment by ndelangen** [comment]
The future of storyshots is the test-runner:
https://storybook.js.org/docs/react/writing-tests/test-runner#page-top

And use the play function for expectations:
https://storybook.js.org/docs/react/writing-stories/play-function#page-top

We will not be making any improvement / changes to storyshots.
