### ISSUE TITLE
@storybook/addon-docs relies on deprecated packages

### ISSUE THREAD

**Issue by vdhpieter** [storybookjs/storybook#17019]
**Describe the bug**

`@storybook/addon-docs` relies on `@jest/transform@26` which relies on `jest-haste-map@26` which relies on `fsevents@2.1` which is [deprecated](https://www.npmjs.com/package/fsevents/v/2.1.3). Updating to `@jest/transform@27` will solve this problem.

EDIT another deprecated package was found:

`@storybook/builder-webpack4` relies on `webpack-dev-middleware@3.7.3` which relies on `webpack-log@2.0.0` which relies on `uuid@3.3.2` which is [deprecated](https://www.npmjs.com/package/uuid/v/3.3.2). Updating `webpack-dev-middleware` to version 4 or later (newest is `5.2.2`) will solve this problem.

EDIT 2:

`@storybook/builder-webpack4` & `@storybook/builder-webpack5` rely on `react-dev-utils@11.0.4` which relies on `browserslist@4.14.2` which has a [security issue](https://github.com/advisories/GHSA-w8qv-6jwh-64r5). Updating `react-dev-utils` to version 12.0.0 will solve this problem. (It wil also solve a security issue with [immer](https://github.com/advisories/GHSA-33f9-j839-rf8h))

**To Reproduce**
Not relevant

**System**
Not relevant

**Comment by chyzwar** [comment]
For our project bigger problem is that our project use webpack5, jest27, emotion11 but storybook still use older versions. This almost double our dev dependencies and sometimes lead to hoisting problems. 

I think it would be great if @storybook/builder-webpack4 and @storybook/builder-webpack5 (webpack4/webpack5) are peer dependencies then project can choose one based on webpack version in project instead of installing it twice.

**Comment by shilman** [comment]
@chyzwar that's the plan. however it's a breaking change so we can't make the move until SB 7.0

**Comment by bdashrad** [comment]
@shilman just to clarify, are the peer dependencies not coming until SB 7.0 or the react-dev-utils update? Just looking for some clarification as we attempt to resolve the immer security issue.

**Comment by shilman** [comment]
@bdashrad I think the immer problem is fixed in 6.5 and i can patch back the fix to 6.4 if somebody verifies (hint hint)

**Comment by mikaelkarlsson-se** [comment]
@shilman I can confirm that the problem with immer is solved in SB 6.5.0-alpha.7.  After upgrading all SB dependencies in my repository I can see in package lock that`react-dev-utils` (v11) has been removed and therefore also immer.
If it's not possible to remove `react-dev-utils` in SB 6.4 then upgrading `react-dev-utils` to v12 would be an option to solve the issue as well, see [this thread](https://github.com/facebook/create-react-app/issues/11660).

**Comment by shilman** [comment]
@ricardo-fnd we're in the process of cleaning all this up for SB7. hopefully we'll get the first alphas out in a month or so.

**Comment by dartess** [comment]
@shilman hi! 
I see improvements in version 7.
It seems that there are two packages left with warnings: `jest` (rather a lot of jest packages) and `stable`.
Are there any plans to upgrade/replace them?

I tried removing `stable` and it seems to work, but the list of browsers that support stable sorting is limited: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility . And I don't know if this list is satisfactory for a storybook.

**Comment by mogsdad** [comment]
I note that V7 (specifically `@storybook/addon-docs@7.0.0-alpha.48`) is still dependent on `@jest/transform@26`. Is this a work-in-progress?

**Comment by ndelangen** [comment]
This is fixed in 7.0 beta
