### ISSUE TITLE
Add documentation for CSF 3.0 story objects

### ISSUE THREAD

**Issue by Fredx87** [storybookjs/storybook#17012]
CSF 3.0 is really nice and it is useful to reduce the boilerplate needed to write stories. The [announcement blog post](https://storybook.js.org/blog/component-story-format-3-0/) explains in the detail the new "Spreadable story objects" syntax. However, this explanation is not present in the documentation: I didn't find any mention of it on the https://storybook.js.org/docs/react/writing-stories/introduction page or on the https://storybook.js.org/docs/react/get-started/whats-a-story page. All the examples use the more "boilerplately"  `Template` syntax.

I think that this syntax should be documented properly somewhere, without forcing people to search for the CSF 3.0 blog post.

**Comment by kylegach** [comment]
> I think that this syntax should be documented properly somewhere, without forcing people to search for the CSF 3.0 blog post.

We agree! This was the primary factor in us deciding to take the time to add versions to the documentation site.

You can find CSF3 examples[^1] in the docs for `7.0`: https://storybook.js.org/docs/7.0/react/writing-stories/introduction, which is when CSF3 will be considered "default". Until that release, we believe it to be more helpful to keep the examples in the more (currently) common format, CSF2.

[^1]: Not all examples are updated yet. It's an ongoing effort, and we'd greatly appreciate contributions, if this is something you care strongly about. 🙏
