### ISSUE TITLE
Background flashing when navigate to different page

### ISSUE THREAD

**Issue by vincentleekp** [storybookjs/storybook#17010]
**Describe the bug**
Navigation to the different paths will have a minor flash in background

**To Reproduce**
1. Select color from the background (i.e. Dark)
2. Navigate to the page that have the same background option
3. Notice page will have minor flash on background
4. This doesn't happen on v6.3.12 but v6.4.9

**System**
```
Environment Info:

  System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  Binaries:
    Node: 14.17.0 - ~/.volta/tools/image/node/14.17.0/bin/node
    Yarn: 1.22.10 - ~/.volta/tools/image/yarn/1.22.10/bin/yarn
    npm: 6.14.13 - ~/.volta/tools/image/node/14.17.0/bin/npm
  Browsers:
    Chrome: 96.0.4664.93
    Firefox: 94.0.2
    Safari: 15.1
  npmPackages:
    @storybook/addon-a11y: ^6.4.9 => 6.4.9 
    @storybook/addon-backgrounds: ^6.4.9 => 6.4.9 
    @storybook/addon-notes: ^5.3.21 => 5.3.21 
    @storybook/addon-postcss: ^2.0.0 => 2.0.0 
    @storybook/addon-storysource: ^6.4.9 => 6.4.9 
    @storybook/addon-viewport: ^6.4.9 => 6.4.9 
    @storybook/addons: ^6.4.9 => 6.4.9 
    @storybook/react: ^6.4.9 => 6.4.9 
    @storybook/storybook-deployer: ^2.8.10 => 2.8.10 
    @storybook/theming: ^6.4.9 => 6.4.9 
```

**Additional context**
Simulate in example provided: https://next--storybookjs.netlify.app/official-storybook/?path=/story/addons-a11y-basebutton--default&globals=backgrounds.value:!hex(333333) 
![Profile-20211214T121307](https://user-images.githubusercontent.com/8315367/145931990-1768722f-fa0c-4377-96a9-25fa38f35cfb.gif)

**Comment by AndysonDK** [comment]
I have the exact same issue, take a look at my storybook library and switch components to see the bug in action:
https://619aa417876c17003a24f46a-hwutncibag.chromatic.com/?path=/story/button--primary

**Comment by shilman** [comment]
closing as dupe to #17122
