### ISSUE TITLE
storyStoreV7 don't work with vue 2 and webpack 5

### ISSUE THREAD

**Issue by s-sasaki-0529** [storybookjs/storybook#17011]
**Describe the bug**

I tried to enable `storyStoreV7` in my Vue 2 and webpack 5 project but when I open my Storybook, I get an error like "Cannot read properties of undefined (reading 'STORYBOOK_VALUES')".

After disabling storyStoreV7, the storybook will open normally.

Please let me know if there are any errors in my setup or usage.

**To Reproduce**

1. Setup Vue2 project with webpack 5.
2. Setup Storybook 6.4.9 by `npx sb init`
3. Run `yarn storybook`
4. Open `localhost:6006`

[Repository](https://github.com/s-sasaki-0529/storybook-vue-webpack-5-sample) (Sorry, I don't use `npx sb@next repro` because of other problem.)

**System**

```
Environment Info:

  System:
    OS: macOS 11.5.2
    CPU: (4) x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
  Binaries:
    Node: 16.12.0 - /usr/local/bin/node
    Yarn: 1.19.2 - /usr/local/bin/yarn
    npm: 8.1.0 - /usr/local/bin/npm
  npmPackages:
    @storybook/addon-actions: ^6.4.9 => 6.4.9 
    @storybook/addon-essentials: ^6.4.9 => 6.4.9 
    @storybook/addon-links: ^6.4.9 => 6.4.9 
    @storybook/builder-webpack4: ^6.4.9 => 6.4.9 
    @storybook/builder-webpack5: ^6.4.9 => 6.4.9 
    @storybook/manager-webpack4: ^6.4.9 => 6.4.9 
    @storybook/manager-webpack5: ^6.4.9 => 6.4.9 
    @storybook/vue: ^6.4.9 => 6.4.9 
```

**Additional context**

![スクリーンショット 2021-12-14 13 29 36](https://user-images.githubusercontent.com/16274215/145933239-90a93526-6f15-4f09-bd53-847815439fa1.png)

**Comment by shilman** [comment]
This looks like it's generally a problem with `storyStoreV7`, also in webpack4 mode. Closing as dupe to #16985
