### ISSUE TITLE
CSF Story with arbitrary MDX docs – no source code in non-story content Canvas

### ISSUE THREAD

**Issue by yournatalita** [storybookjs/storybook#17020]
_**Describe the bug**_
When you're using mdx docs as described in "CSF Story with arbitrary MDX" [docs](https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/recipes.md#csf-stories-with-arbitrary-mdx) and writing non-story content examples inside `<Canvas />`, there is no code snippet block, with "No code available" sign.

![image](https://user-images.githubusercontent.com/25444749/146187118-255734be-89be-4989-a922-5d0c9f637551.png)

However, Story's links are still imported with source code in arbitrary MDX.

_**To Reproduce**_
Create a CSF Story with arbitrary MDX and place non-story content inside a Canvas block as showed in [docs](https://storybook.js.org/docs/react/writing-docs/doc-blocks#source)

Expected behaviour: You can see source code of Canvas' example
Current behaviour: No code available

Repro: https://github.com/yournatalita/storybook-canvas-repro
Online: https://61b9d8cd3f45a1003a2324d7-nvxpctcfhc.chromatic.com/?path=/docs/example-button--primary

Example with bug at the Button's story and a repro without this bug at the Introduction page.

_**System**_
``` System:
    OS: macOS 11.2.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 14.15.0 - /usr/local/bin/node
    Yarn: 3.1.1 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
  Browsers:
    Chrome: 96.0.4664.110
    Safari: 14.0.3
  npmPackages:
    @storybook/addon-actions: ^6.5.0-alpha.3 => 6.5.0-alpha.3 
    @storybook/addon-docs: ^6.5.0-alpha.3 => 6.5.0-alpha.3 
    @storybook/addon-essentials: ^6.5.0-alpha.3 => 6.5.0-alpha.3 
    @storybook/addon-links: ^6.5.0-alpha.3 => 6.5.0-alpha.3 
    @storybook/react: ^6.5.0-alpha.3 => 6.5.0-alpha.3 
```

_**Additional context**_
Having an ability to write non-story content is pretty important for CSF Story with arbitrary MDX case. You are still can make complex examples of components in CSF with a varied opportunity to play with controls and make description articles with recipes and examples. 

You can still place custom source with `mdxSource` prop, but duplicating code is pretty depressing when you need to edit it twice.

If this is expected behaviour please add it to docs to make it clear. It may save someone's time. Thank you!

**Comment by Ghazaleh-Graziella** [comment]
hi #yournatalita
Regarding the question you asked, you can use <Source/> tag with code property for showing code snippet.
Please don't forget to import it first from docs.
`import { Source} from '@storybook/addon-docs';`
`<Source language="js" code="your code"/>`

and don't forget to delete all the spaces in the <Source/> tag.

**Comment by yournatalita** [comment]
> hi #yournatalita Regarding the question you asked, you can use tag with code property for showing code snippet. Please don't forget to import it first from docs. `import { Source} from '@storybook/addon-docs';` `<Source language="js" code="your code"/>`
> 
> and don't forget to delete all the spaces in the tag.

You can place custom made source with `mdxSource` prop which will work as in common mdx-story, with toggle show/hide source button.

```tsx
<Canvas
  mdxSource={`
   <Loader size={"small"} />
`}>
  <Loader size={'small'} />
</Canvas>
```

Your way to make Source block is the other way to create it, without toggle button and it's good too. But it's not resolving the issue itself.

Documentation says,

> You can also place non-story content inside a Canvas block. This renders the JSX content exactly as it would if you’d placed it directly in the MDX, but it also inserts the source snippet in a Source block beneath the block.

And since the source block is not placed and I couldn't find any documentation regarding this limitation in arbitrary mdx, this is mostly looks like an unexpected behaviour. 

I've spent some time trying to figure out where my settings are wrong before trying it in a clean storybook.

If it's just a limitation, it should've been written somewhere so someone will save his time in future.

**Comment by LongLiveCHIEF** [comment]
> You also can place custom made source with mdxSource prop which will work as in common mdx-story, with toggle show/hide source button.

> Still, this limitations on arbitrary MDX's source code should've been described somewhere.

Any docs around the `<Canvas>` api at all would be helpful. Even comments in the code.  It's actually quite ironic that the only way I knew to look for this feature was by reading the source code to see if this option existed and found that it did.

I want the `<Canvas>` element to show a rendered component, but the `show code` to show the code for that rendered component. Figured that would be something that was documented in the API docs on the website.

**Comment by shilman** [comment]
@LongLiveCHIEF source block is documented here https://storybook.js.org/docs/react/writing-docs/doc-blocks#source

**Comment by LongLiveCHIEF** [comment]
That's not documentation. that's just acknowledgement that the component exists.  
- What parameters does it take? 
- Does it only work inside `<Story>`?


Let's say I have a `CustomButton.js` file, and inside my story, I use `<CustomButton>`.  Is it going to render that source as `<CustomButton />` or will it render the:

```
const CustomButton = (props) => <Button>{children}</Button>
```

It seems that the params I've been finding in the source indicate the latter is possible, but i'm having a hard time getting there based on the docs and lack of comments in the source code.

I'd love to contribute and improve on that... just need somewhere to start that identifies what the intent is.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
