### ISSUE TITLE
[Addon Docs] [MDX] Anchors for headings are broken in Storybook 6.4.3

### ISSUE THREAD

**Issue by Celentia** [storybookjs/storybook#17030]
**Describe the bug**
MDX anchors in markdown for headings aren't scrolling to the relevant section in Storybook 6.4.3.

**To Reproduce**

1. Create new or open existing .mdx story;
2. Add an anchor for heading to some docs section, for example:
  ```
 ## Table of Contents
     - [Overview](#overview)
     ...

 ## Overview
```
3. Click on "Overview" in the Table of Contents section.

**Expected result:**
Docs page should scroll to Overview section.

**Actual result:**
The blank page is shown.

**Additional context**
This issue is reproducible in Storybook 6.4.3 and Storybook 6.4.0-beta.20. In Storybook 6.3 it has worked fine.

**Comment by shilman** [comment]
closing as dupe to #16918
