### ISSUE TITLE
"Couldn't find any stories in your Storybook." after upgrade to 6.4.9

### ISSUE THREAD

**Issue by Domiii** [storybookjs/storybook#17038]
**Describe the bug**

This worked before, but now complains it cannot find any stories anymore:

```js
{
  stories: [
    // stories folder: ignore 'components/', `data/`, `*.Template.js` files; `.stories` suffix is optional.
    `../packages/theproject-*/**/stories!(/components|/data|.*Template.js)/*?(.stories).js`,

    // src folder: `.stories` files
    `../packages/theproject-*/src/**/*.stories.js`,

    // only get the index file for nested story folders
    `../packages/theproject-*/src/**/stories/index.js`,
  ]
}
```

I tried simplifying, and this still does not find anything: 

```js
{
  stories: ['../packages/theproject-*/src/**/stories/index.js']
}
```

Explicit paths without any wildcards work though:

```js
{
  stories: ['C:/Users/me/code/repo/packages/theproject-frontend-common/src/features/table/stories/index.js']
}
```

**System**
```
Environment Info:

  System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
  Binaries:
    Node: 16.13.0 - ~\AppData\Local\Volta\tools\image\node\16.13.0\node.EXE
    Yarn: 1.22.17 - ~\AppData\Local\Volta\tools\image\yarn\1.22.17\bin\yarn.CMD
    npm: 8.1.0 - ~\AppData\Local\Volta\tools\image\node\16.13.0\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (96.0.1054.57)
  npmPackages:
    @storybook/addon-actions: ^6.4.9 => 6.4.9
    @storybook/addon-essentials: ^6.4.9 => 6.4.9
    @storybook/addon-links: ^6.4.9 => 6.4.9
    @storybook/addon-postcss: ^2.0.0 => 2.0.0
    @storybook/builder-webpack5: ^6.4.9 => 6.4.9
    @storybook/manager-webpack5: ^6.4.9 => 6.4.9
    @storybook/react: ^6.4.9 => 6.4.9
```

**Additional context**

I realized that [the context builder code](https://github.com/storybookjs/storybook/blob/next/lib/core-common/src/utils/to-require-context.ts#5) has changed a lot since the last version.

The final `require` string of the pattern  looks like this:

```js
 "use strict";

var _frameworkImportPath = require("@storybook/react");

/* eslint-disable import/no-unresolved */
(0, _frameworkImportPath.configure)([require.context('./packages', false, /^\.[\\/](?:theproject-[^\\/]*?[\\/]src(?:[\\/](?!\.)(?:(?:(?!(?:^|[\\/])\.).)*?)[\\/]|[\\/]|$)stories[\\/]index\.js)$/)], module, false);
```

It looks like `recursive = false` seems wrong here.

# Update

I did some more experimentations and I found the `recursive` flag is indeed incorrect and makes zero sense. This worked fine before, so not sure what you changed, but it certainly messes with the `stories` globs.

This works:

```js
{
  stories: ['../packages/theproject-frontend-common/src/features/**/stories/index.js']
}
```

In `@storybook/core-common/dist/cjs/utils/to-require-context.js` it now becomes:

```
 {
  "path": "./packages/theproject-frontend-common/src/features",
  "files": "**/stories/index.js",
  "recursive": true,
  "match": {}
}
```

# Conclusion

This worked before, but since latest update does not anymore - 

```js
'a-*/b/**/c'
```

However, this still works:

```js
'a/b/**/c'
```

=> Since the upgrade, a double-star glob must always be the first, apparently. (But I'm not sure. I have not spent more time to find out, where it breaks off pattern and directory.)

This regression might not be intended, or maybe it is. Either way, it SHOULD be mentioned in the [migration guide](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#from-version-63x-to-640).

## Workaround

```js
const packages = [
  // ...
];

function s(pattern) {
  return packages.map(p => `../packages/${p}/${pattern}`);
}

module.exports = {
  stories: [
    // stories folder: ignore 'components/', `data/`, `*.Template.js` files; `.stories` suffix is optional.
    s(`stories!(/components|/data|.*Template.js)/*?(.stories).${exts}`),

    // src folder: `.stories` files
    s(`src/**/*.stories.${exts}`),

    // only get the index file for nested story folders
    s(`src/**/stories/index.${exts}`)
  ].flat()
};
```

**Comment by Domiii** [comment]
Still a regression/bug

**Comment by tmeasday** [comment]
Apologies about the delay here, you were quite right about the recursive flag: https://github.com/storybookjs/storybook/pull/17252/files

**Comment by shilman** [comment]
¡Ay Caramba!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-alpha.19 containing PR #17252 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Yippee!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.14 containing PR #17252 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```
