### ISSUE TITLE
Button Explicit Props - issue when removing implicit (Typescript)

### ISSUE THREAD

**Issue by konsalex** [storybookjs/storybook#17052]
**Describe the bug**
I have an issue with auto-generated controls from Typescript types. In the Additional Context I have attached images and code snippets.

The issue is with explicit vs implicit props for Button in my case `React.HTMLProps<HTMLButtonElement>`.

When I extend the `React.HTMLProps<HTMLButtonElement>` interface everything seems to be working as expected, and `disabled` appears in the controls, as I am explicit with this prop.

```ts
interface ButtonProps extends React.HTMLProps<HTMLButtonElement> {
  /** If the button is in disabled state */
  disabled?: boolean;
}
```

When I switch to **type** instead of an **interface** extension, then `disabled` disappears from the control panel.

Any clue why and how to resolve this? Although now it is working with an interface, it would be nice to know the logic behind this, so I can avoid headaches in the future.

**To Reproduce**

**System**

```bash
Environment Info:

  System:
    OS: macOS 11.5.2
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Chrome: 96.0.4664.110
    Firefox: 94.0.2
    Safari: 14.1.2
```

**Additional context**

Working with using **interface**
```ts
interface ButtonProps extends React.HTMLProps<HTMLButtonElement> {
  /** If the button is in disabled state */
  disabled?: boolean;
}
```
![image](https://user-images.githubusercontent.com/12672541/146955575-f0329d43-e8e7-4bc8-afe1-e1422d105e56.png)

Stops inferring properly with type instead of interface
```ts
type ButtonProps = React.HTMLProps<HTMLButtonElement> & {
  /** If the button is in disabled state */
  disabled?: boolean;
}
```
![image](https://user-images.githubusercontent.com/12672541/146955390-60547b8a-3c54-406a-a839-7768804a756f.png)

 
Working `disabled` prop when renaming it to `disabled2` (using type not interface).
```ts
type ButtonProps = React.HTMLProps<HTMLButtonElement> & {
  /** If the button is in disabled state */
  disabled2?: boolean;
}
```
![image](https://user-images.githubusercontent.com/12672541/146954227-b233c9bc-16de-4e5b-913e-6ce3575bb7fd.png)

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
