### ISSUE TITLE
StoryShots web-components fails to run with error: Cannot set properties of undefined (setting 'STORYBOOK_ENV')

### ISSUE THREAD

**Issue by TommasoAmici** [storybookjs/storybook#17053]
**Describe the bug**
I'm trying to set up the StoryShots addon in Storybook with web-components, but it fails with this error:

```
Test suite failed to run

    TypeError: Cannot set properties of undefined (setting 'STORYBOOK_ENV')

      at Object.<anonymous> (node_modules/@storybook/web-components/dist/cjs/client/preview/globals.js:8:28)
      at Object.<anonymous> (node_modules/@storybook/web-components/dist/cjs/client/preview/index.js:12:1)
      at Object.<anonymous> (node_modules/@storybook/web-components/dist/cjs/client/index.js:106:16)
      at Object.load (node_modules/@storybook/addon-storyshots/dist/ts3.9/frameworks/web-components/loader.js:24:26)
```

**To Reproduce**
https://github.com/TommasoAmici/storybook-storyshots-webecomponents-repro

**System**
Environment Info:

  System:
    OS: macOS 11.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 16.13.1 - /usr/local/Cellar/node@16/16.13.1/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.2 - /usr/local/Cellar/node@16/16.13.1/bin/npm
  Browsers:
    Chrome: 96.0.4664.110
    Edge: 96.0.1054.62
    Safari: 15.2
  npmPackages:
    @storybook/addon-a11y: ^6.4.9 => 6.4.9 
    @storybook/addon-actions: ^6.4.9 => 6.4.9 
    @storybook/addon-docs: ^6.4.9 => 6.4.9 
    @storybook/addon-essentials: ^6.4.9 => 6.4.9 
    @storybook/addon-links: ^6.4.9 => 6.4.9 
    @storybook/addon-storyshots: ^6.4.9 => 6.4.9 
    @storybook/addon-storyshots-puppeteer: ^6.4.9 => 6.4.9 
    @storybook/web-components: ^6.4.9 => 6.4.9

**Comment by TommasoAmici** [comment]
This seems to happen in this line: https://github.com/storybookjs/storybook/blob/next/app/web-components/src/client/preview/globals.ts#L5

**Comment by muinmomin** [comment]
@TommasoAmici I'm also running into this with the web components set up - did you end up finding a solution for this?

**Comment by jelche** [comment]
I also am seeing this trying to set up StoryShots for web-components.

**Comment by TommasoAmici** [comment]
> @TommasoAmici I'm also running into this with the web components set up - did you end up finding a solution for this?

No, unfortunately I didn't

**Comment by enriquemontielids** [comment]
Storybook for HTML seems to have the same issue.

**Comment by ziyafenn** [comment]
I have the same problem with HTML set up. Opened another issue: https://github.com/storybookjs/storybook/issues/19175

**Comment by uzairfarooq** [comment]
Facing same issue with html setup

**Comment by matthew-dean** [comment]
I've run into this with Vue when trying:
```ts
import { setup } from '@storybook/vue3'
import PrimeVue from 'primevue/config'

setup(app => {
  app.use(PrimeVue)
})
```

**Comment by jonniebigodes** [comment]
The Storyshots addon is officially deprecated and will be removed in a future release of Storybook. To help with the transition process, we've created a [migration guide](https://storybook.js.org/docs/writing-tests/storyshots-migration-guide) for the available options and common use cases.
