### ISSUE TITLE
Mock GET Request Error

### ISSUE THREAD

**Issue by singsad** [storybookjs/storybook#17055]
hi, when i use 'storybook-addon-mock' to mock, I found 'GET' request url must be write query params. like this
```
    url: `${apiPrefix}/common/action_log/list?page_no=1&count=10&main_type=user_management&sub_type=role+info&object_id=1`,

```
if i only write `${apiPrefix}/common/action_log/list` ,this request code will be 404,It seems that the request was not hijacked

 What shall I do?

**Comment by shilman** [comment]
Please file an issue on the `storybook-addon-mock` repo
