### ISSUE TITLE
Embedding stories in MDX with URL args breaks in 6.4.

### ISSUE THREAD

**Issue by jgerigmeyer** [storybookjs/storybook#17054]
**Describe the bug**

In Storybook 6.3, it was possible to [embed stories in MDX](https://storybook.js.org/docs/react/writing-docs/mdx#embedding-stories) with [specific args in the URL](https://storybook.js.org/docs/react/writing-stories/args#setting-args-through-the-url), e.g.:

```jsx
<Story id="components--my-story&args=style:rounded" />
```

Since upgrading to Storybook 6.4, this usage (with `&args`) breaks:

```bash
Uncaught (in promise) Error: Couldn't find story matching 'components--my-story&args=style:rounded' after HMR.
- Did you remove it from your CSF file?
- Are you sure a story with that id exists?
- Please check your stories field of your main.js config.
- Also check the browser console and terminal for error messages.
    storyIdToEntry StoryIndexStore.js:95
    loadCSFFileByStoryId StoryStore.js:220
    _callee2$ StoryStore.js:289
    tryCatch runtime.js:63
    invoke runtime.js:294
```

**To Reproduce**

- https://github.com/jgerigmeyer/sb-repro
- https://61c22ea28dc00c003a4691e6-zqvojybbgk.chromatic.com/?path=/story/example-button-docs--page

**System**

```
Environment Info:

  System:
    OS: macOS 12.1
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 3.1.1 - /opt/homebrew/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
  Browsers:
    Chrome: 96.0.4664.110
    Firefox: 95.0
    Safari: 15.2
  npmPackages:
    @storybook/addon-actions: ^6.5.0-alpha.4 => 6.5.0-alpha.4
    @storybook/addon-docs: ^6.5.0-alpha.4 => 6.5.0-alpha.4
    @storybook/addon-essentials: ^6.5.0-alpha.4 => 6.5.0-alpha.4
    @storybook/addon-links: ^6.5.0-alpha.4 => 6.5.0-alpha.4
    @storybook/react: ^6.5.0-alpha.4 => 6.5.0-alpha.4
```

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
