### ISSUE TITLE
Storybook 6.4 injects HTML into preview iframe that was not there

### ISSUE THREAD

**Issue by cellog** [storybookjs/storybook#17064]
**Describe the bug**
The rendered pane for opening a preview in a new window is injecting an `ArgsTable` in version 6.4, which was not happening with 6.3. This is causing our Cypress selectors that are assuming the iframe is just the story to fail. The reason is that this ArgsTable has buttons in it (as well as a table) so selectors like `cy.get("button").eq(0)` selects the hidden elements instead of the visible ones.

The table will literally never be used in the separate window, so it should not be rendered.

**To Reproduce**

open any story with controls in the new window, and inspect the DOM.

**System**
➜  beacon git:(upgrade-storybook) ✗ npx sb@next info

Environment Info:

  System:
    OS: macOS 11.6.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 14.18.2 - ~/.nvm/versions/node/v14.18.2/bin/node
    Yarn: 1.19.1 - ~/.yvm/shim/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.2/bin/npm
  Browsers:
    Chrome: 96.0.4664.110
    Firefox: 95.0.2
    Safari: 15.1

**Additional context**

**Comment by shilman** [comment]
@cellog I tried to reproduce but no success. Do you a have a reproduction repo you can share? If not, can you create one? See [how to create a repro](https://storybook.js.org/docs/react/contribute/how-to-reproduce). 🙏

**Comment by cellog** [comment]
This does it for me:

```ts
import React from "react";

// eslint-disable-next-line import/no-default-export
export default {
  title: "Core/Repro",
  component: Repro,
  argTypes: {
    bool: {
      control: {
        type: "checkbox",
      },
    },
    another: {
      control: {
        type: "text",
      },
    },
  },
};

interface ReproProps {
  another: string;
}

function Repro({ another }: ReproProps): React.ReactElement {
  return <div>{another}</div>;
}

export const ControlsBug = (args: ReproProps): React.ReactElement => {
  return <Repro {...args} />;
};

ControlsBug.storyName = "controls bug";
```

addon-docs should be installed.  Resulting DOM is:

![Screen Shot 2021-12-23 at 10 14 19 AM](https://user-images.githubusercontent.com/98250/147259399-acebd80c-ce57-49b5-b5c0-d17261dfa29a.png)

**Comment by shilman** [comment]
Are you using the `storyStoreV7` feature flag?

**Comment by cellog** [comment]
we are not using any feature flags

**Comment by shilman** [comment]
Thanks for the clarification. I was looking under `#root` before since that's where the story is rendered.

@tmeasday I wonder whether this is technically a breaking change or whether an addition to `MIGRATION.md` is sufficient. My recollection is that this was the easiest way to get the loading behavior we were looking for...

**Comment by cellog** [comment]
I am not sure how common what we are doing with storybook is, but I would argue that supporting running integration tests against the storybook iframe will become increasingly common as folks realize the benefits.

However, I think it's kind of an anti-pattern to render hidden elements that will never display just for the side effects - why does markup need to be rendered to get behavior?

**Comment by tmeasday** [comment]
The elements are displayed during the loading state for the docs page. This doesn't really show up in the v6 store however. I am not sure what the "side effects" you are referring to are @cellog?

> I wonder whether this is technically a breaking change or whether an addition to MIGRATION.md is sufficient. My recollection is that this was the easiest way to get the loading behavior we were looking for...

@shilman I wouldn't call this a breaking change myself, I think the internals of what Storybook renders outside of the `#root` element are in no way documented / expected not to change. Can appreciate it is annoying.

I would suggest targeting any selectors at `#root > ...` would be a sensible way to proceed with this kind of test.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
