### ISSUE TITLE
Controls not auto generating

### ISSUE THREAD

**Issue by rexkenley** [storybookjs/storybook#17073]
**Describe the bug**
The controls are not autogenerating properties from interface.
![image](https://user-images.githubusercontent.com/10548251/147268386-a3a578ab-8a9a-499c-8224-a306c163954f.png)

**To Reproduce**
https://github.com/rexkenley/rollupError

**System**
  System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
  Binaries:
    Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 96.0.4664.110
    Edge: Spartan (44.19041.1266.0), Chromium (96.0.1054.62)
  npmPackages:
    @storybook/addon-actions: ^6.4.8 => 6.4.9
    @storybook/addon-essentials: ^6.4.8 => 6.4.9
    @storybook/addon-interactions: ^6.4.8 => 6.4.9
    @storybook/addon-jest: ^6.4.8 => 6.4.9
    @storybook/addon-links: ^6.4.8 => 6.4.9
    @storybook/jest: ^0.0.5 => 0.0.5
    @storybook/react: ^6.4.8 => 6.4.9
    @storybook/testing-library: ^0.0.7 => 0.0.7
    @storybook/testing-react: ^1.2.2 => 1.2.2

**Comment by shilman** [comment]
This looks like it could be an issue with `react-docgen-typescript`, which is the library we use to extract argTypes automatically. 

If you log out `TimesheetSummary` and `TimesheetDetails` in their respective story files like this:

```js
console.log({ TimesheetSummary });
console.log({ TimesheetDetails });
```

You'll see that the former has `__docgenInfo` hanging off it, whereas the latter does not. I hope that's a good starting point to debug.

**Comment by rexkenley** [comment]
Well the fix is to separate the export default from the function. 

`export default function TimeSheetDetails() {}`

to 

`function TimeSheetDetails() {}`
`export default TimeSheetDetails;`

**Comment by christophermiles** [comment]
This workaround is going to be painful to implement for a large Storybook that currently uses `export const Component = ComponentTemplate.bind({})`. I currently have 24 `.stories.js`, many with multiple components.

Is there any plan to fix the issue with `argTypes` not being extracted automatically? If not, might I suggest updating the docs? https://storybook.js.org/docs/react/essentials/controls

**Comment by christophermiles** [comment]
Actually I tried the fix mentioned above but it's not working for me. I'm creating my Stories exactly as described in the docs https://storybook.js.org/docs/react/essentials/controls

Unlike the fix above, I'm not exporting default functions, I'm exporting `const` as in the docs:

```
import { Button } from './Button';

export default {
  /* 👇 The title prop is optional.
  * See https://storybook.js.org/docs/react/configure/overview#configure-story-loading
  * to learn how to generate automatic titles
  */
  title: 'Button',
  component: Button,
};

const Template = (args) => ({
  //👇 Your template goes here
});

export const Primary = Template.bind({});
Primary.args = {
  variant: 'primary',
};

export const Primary = {
  args: {
    variant: 'primary',
  },
};
```

**Comment by rexkenley** [comment]
@christophermiles 

It's not the stories that is the issue, but the actual component itself. And it's not always the case. I would try 

`export default function Component` 

first and if it doesn't work then use 

`function Component() {}
export default Component;`

**Comment by christophermiles** [comment]
@rexkenley Do you mean the component I'm rendering in Storybook? So in the example from the Storybook docs posted above, I would need to make the change in the `Button` component?

I'm afraid this is an even worse imposition on developers, since it would mean changing the syntax in every Vue component we render in Storybook to a syntax that is not recommended by the Vue docs.

Every official example of a Vue single-file component I've seen uses:

```
<template>
  <button/>
</template>

<script>
export default {
  name: 'Button',
  // Other properties
}
</script>
```

**Comment by rexkenley** [comment]
What I am saying is that if the auto prop generation is not working with the first method (export default function), then use the second method (separate export default from function).

If you are using Vue, then you are experiencing something completely different. My issue and workaround is react specific.

**Comment by christophermiles** [comment]
I'm afraid I don't really follow but thanks for attempting to help re. the workaround.

Hopefully the Storybook team can address this, because at the moment, the controls do not work as outlined in the official docs. I am going to try to revert back to a previous version of Storybook (which was working exactly as documented) and perhaps add a resolution for `react-docgen-typescript` if it is indeed an issue with that library.

**Comment by vipin-nimble** [comment]
Hmm, so this is the closest issue that might describe what I am facing in my repo. Mine is a older repo (think webpack 3.*). I added storybook to the repo and modified a few of the webpack rules for my `.scss` files to load properly.

I can get the controls to load properly. But the `ArgsTable` does not respect my comments in `propTypes`.

Here is my component - `NewPill.js`

```
import styles from './NewPill.scss';

const NewPill = props => {
	const { text, color } = props;
	return <span className={`${styles.newPill} ${color}`}> {text} </span>;
};

NewPill.propTypes = {
	/**
	 * Denotes the text of the pill
	 */
	text: PropTypes.string,
	/**
	 * Denotes the color of the pill
	 */
	color: PropTypes.string,
};

export default NewPill;
```

Here is my story - `NewPill.stories.js`

```
import NewPill from './NewPill';

export default {
	title: 'Components/NewPill',
	component: NewPill,
};

const Template = args => {
        console.log(NewPill.__docgenInfo); // Gives me undefined
	return <NewPill {...args} />;
};

export const FirstStory = Template.bind({});
FirstStory.args = {
	text: 'Pill Text',
	color: 'blue',
};
```
And this is the output,

![image](https://user-images.githubusercontent.com/102994748/161625548-f3b5c67c-3193-4804-9258-8afeeb44ab70.png)

The workaround is obviously to add `argTypes` to the story itself.

```
FirstStory.argTypes = {
	text: {
           control: { type: 'text' },
           description: 'Denotes the text of the pill',
        }
	color: 'blue',
};

```

 But it'd be nice if the storybook system grabs that info from the original component itself. Is there a way to see if the `babel-plugin-react-docgen` worked? I followed their instructions [here](https://www.npmjs.com/package/babel-plugin-react-docgen) with no luck

**Comment by alexsurelee** [comment]
Just want to add a comment that I was facing the same issue with a setup that uses babel, but simply installing and adding the [`babel-plugin-react-docgen`](https://www.npmjs.com/package/babel-plugin-react-docgen) that you just mentioned fixed it for me!

**Comment by myyellowshoe** [comment]
why was this closed? this still seams like an issue folks are facing, myself included

**Comment by sohamnandi77** [comment]
@shilman please reopen this, it seems to a issue now as well
