### ISSUE TITLE
Cannot load custom ant design theme in Storybook

### ISSUE THREAD

**Issue by raph90** [storybookjs/storybook#17072]
**Describe the bug**
I'm using Ant Design in a React project with a custom webpack config (no CRA or anything). I am using less to have a theme as per the ant design docs (https://ant.design/docs/react/customize-theme). I have created a theme which simply replaces the primary colour with 'green'. When I run my app in dev (yarn start), primary buttons are rendered in green. However, when I run storybook, they are rendered in Ant Design's default blue. If I look at the css in the dev tools, I can see that my theme is being included in the stylesheet, but it is being overridden by the default styles. This is pretty mysterious to me, and I've spent a couple of days trying to fix it, but to no avail. 

**To Reproduce**
Please clone from here to see the issue: https://github.com/raph90/personal-react-boilerplate

**System**
Please paste the results of `npx sb@next info` here.
Environment Info:

  System:
    OS: macOS 12.0.1
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.11 - /opt/homebrew/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
  Browsers:
    Chrome: 96.0.4664.110
    Safari: 15.1
  npmPackages:
    @storybook/addon-actions: ^6.4.9 => 6.4.9 
    @storybook/addon-essentials: ^6.4.9 => 6.4.9 
    @storybook/addon-links: ^6.4.9 => 6.4.9 
    @storybook/builder-webpack5: ^6.4.9 => 6.4.9 
    @storybook/manager-webpack5: ^6.4.9 => 6.4.9 
    @storybook/react: ^6.4.9 => 6.4.9 

**Additional context**
The finalWebpack function in my main.js is a little messy, that's because I've been trying every different config under the sun to try and get this working. It would be great to have any help with it.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
