### ISSUE TITLE
React | Unable to use "useSetRecoilState" in story

### ISSUE THREAD

**Issue by ggustav1** [storybookjs/storybook#17082]
**Describe the problem**
When creating stories  with components that use Recoil state, I am unable to change states from my .stories.js file.

Example:

I have a Date Input Field component that takes a "reference" name as its prop, in order to access states from the parent component. 

**DateInputField.jsx**

```
export const DateInputField = ({recoilStateName}) => {
const isDisabled = useRecoilValue(disabledState(recoilStateName));

  return (
<>
<input disabled={isDisabled } />
</>

}
```

Now, I would like to be able form my stories file to access the recoil state.

What I have tried so far:

**DateInputField.stories.js**

```
const stories = {
    title: 'Atoms/Input Fields',
    decorators: [(storyFn) => <RecoilRoot>{storyFn()}</RecoilRoot>],
    component: DateInputField
};

export default stories;

export const Template = (args) => {


    const setDateDisabled = useSetRecoilState(disabledState('storybookStartDate'));

    // Set to false right away
    setDateDisabled(false)
    
    return <DateInputField {...args}/>

}

export const DateInput = Template.bind({});

DateInput.args = {
   recoilStateName: 'storybookStartDate',
};
```

The error I'm getting when using the "setDateDisabled(false)" from Storybook is "This component must be used inside a <RecoilRoot> component.". 

I have tried multiple things in order to get things to work.

Is it even possible to implement components using recoil states in storybook at all? 

**System**
Running on Windows 10 in React

**Additional context**
The recoil state opreations work in the actual project, just not in story book.

**Comment by tomgalpin** [comment]
I've been trying to do the same thing.  This is as far as I've gotten (which has the same issue):

```
const Template: Story = (args) => {
  return (
    <RecoilRoot>
      <MyComponent {...args} />
    </RecoilRoot>
  );
};

// DEFAULT COMPONENT
export const defaultComponent = Template.bind({});
defaultComponent.args = {
  // IIFE
  test: (() => {
    const { name } = useRecoilValue(nameAtom);
    console.log(34, name);
    console.log(35, nameAtom);
  })(),
};
```

**Comment by tomgalpin** [comment]
I found a workaround (kind of hacky) to use Recoil hooks, and dynamically update in the Storybook args:

```
const MockedComponent = (args) => {
  const setName = useSetRecoilState(nameAtom);

  useEffect(() => {
    setName({ name: args.name });
  }, [args.name, setName]);

  return <MyComponent {...args} />;
};

const Template: Story = (args) => {
  return (
    <RecoilRoot>
      <MockedComponent {...args} />
    </RecoilRoot>
  );
};

// DEFAULT COMPONENT
export const defaultComponent = Template.bind({});
defaultComponent.args = {
  name: "Peppa Pig",
};
```

**Comment by steveetm** [comment]
Hey, any update on this? Really frustrating as adding `<RecoilRoot>` from decorator isn't working, have to manually wrap every exported story.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
