### ISSUE TITLE
Reproduction steps have an undeclared yarn dependency

### ISSUE THREAD

**Issue by tomjn** [storybookjs/storybook#17083]
**Describe the bug**

The reproduction steps use `npm sb@next repro` but then try to use Yarn, which is not mentioned anywhere until you've filled out all the questions and it errors out. This is not mentioned in the linked doc, and since `npx` is used it's assumed `npm` is all that's necessary on the package management side.

Ironically the steps to reproduce this are.. the steps to create a reproduction:

> **To Reproduce**
> Please create a reproduction by running `npx sb@next repro` and following the instructions. Read our [documentation](https://storybook.js.org/docs/react/contribute/how-to-reproduce) to learn more about creating reproductions.
Paste your repository and deployed reproduction here. We prioritize issues with reproductions over those without.

**System**

```
❯ npx sb@next info 

Environment Info:

  System:
    OS: macOS 12.1
    CPU: (8) arm64 Apple M1 Pro
  Binaries:
    Node: 14.18.2 - ~/.nvm/versions/node/v14.18.2/bin/node
    npm: 7.24.2 - ~/.nvm/versions/node/v14.18.2/bin/npm
  Browsers:
    Chrome: 96.0.4664.110
    Safari: 15.2

```

**Additional context**

Ideally it would be mentioned in the doc that yarn is necessary

```

🏗 Bootstrapping react project (this might take a few minutes)
mkdir react && cd react && touch yarn.lock && yarn init --yes && yarn add react react-dom
An error occurred while executing: `mkdir react && cd react && touch yarn.lock && yarn init --yes && yarn add react react-dom`
Command output was:

/bin/sh: yarn: command not found

🚨 Bootstrapping react failed
🚨 Failed to create repro

```

**Comment by tomjn** [comment]
of note, I installed yarn then nuked the folder and retried, but I should not have had to, I should have been told Yarn was a hard requirement beforehand. I was not told this.

To fix this issue one of the following is necessary either this screenshot needs to change:

<img width="795" alt="Screenshot 2021-12-27 at 18 12 20" src="https://user-images.githubusercontent.com/58855/147497103-b33874ad-eeca-42f4-9e11-5f62c4baf696.png">

Or running the command needs to do one of the following:

 - tell you yarn is needed
 - install yarn
 - not require yarn

**Comment by jonniebigodes** [comment]
@tomjn thanks for reaching out to us with your issue, we appreciate it. I was able to reproduce and confirm your issue and pushed a pull request to address this. It will be merged shortly and available to the rest of the community.

Have a great day!

Stay safe.
