### ISSUE TITLE
CSF documentation has redundant code

### ISSUE THREAD

**Issue by willyrk1** [storybookjs/storybook#17092]
**Describe the bug**
The CSF API documentation (https://storybook.js.org/docs/react/api/csf) has redundant code blocks:

> Now consider the same example, re-written with args:
>
> <Code snippet 1>
>
>  At first blush, this might seem no better than the original example. However, if we add the Docs addon and configure the Actions addon appropriately, we can write:
>
> <Code snippet 2>
> 

...except that Code snippet 1 and Code snippet 2 are exactly identical. This doesn't seem like the intention.

**Comment by jonniebigodes** [comment]
@willyrk1 thanks for bringing this to our attention. This section is indeed a bit redundant and was left in during the updates for 6.4. I've pushed a pull request that fixes this issue.

Have a great day!
Stay safe
