### ISSUE TITLE
Auto generated ArgsTable in CSF does not affect the component if inlineStories is set to false

### ISSUE THREAD

**Issue by mateusvini13** [storybookjs/storybook#17097]
**Describe the bug**
When using `parameters: { docs: { inlineStories: false } },` being used in this case due to the component being a Modal, the ArgsTable renders correctly and and shows the controls and props, but changing them does not affect the component inside the iframe.

**To Reproduce**
Just set `parameters: { docs: { inlineStories: false } }` in a Story.

**System**
```
  System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
  Binaries:
    Node: 14.15.4 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - C:\Program Files\nodejs\yarn.CMD
    npm: 6.14.10 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (96.0.1054.62)
  npmPackages:
    @storybook/addon-actions: ^6.4.9 => 6.4.9
    @storybook/addon-essentials: ^6.4.9 => 6.4.9
    @storybook/addon-links: ^6.4.9 => 6.4.9
    @storybook/builder-webpack5: ^6.4.9 => 6.4.9
    @storybook/manager-webpack5: ^6.4.9 => 6.4.9
    @storybook/preset-create-react-app: ^4.0.0 => 4.0.0
    @storybook/react: ^6.4.9 => 6.4.9
```

**Additional context**
I suspect this is related to the nature itself of iframe rendering and think it may be quite problematic to solve, so any workarounds would be appreciated.

**Comment by shilman** [comment]
closing as dupe to #11908
