### ISSUE TITLE
Show code displaying <No> for all component code

### ISSUE THREAD

**Issue by codersbet** [storybookjs/storybook#17099]
Clicking on show code always show:

`<No Display Name disabled label="Do Somthing" onClick={function noRefCheck(){}} size="medium" />`

**System**
Please paste the results of `npx sb@next info` here.
`Environment Info:

  System:
    OS: macOS 11.6.1
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
  Binaries:
    Node: 14.15.1 - /usr/local/bin/node
    npm: 7.18.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 96.0.4664.110
    Safari: 14.1.2
  npmPackages:
    @storybook/addon-essentials: ^6.4.9 => 6.4.9
    @storybook/addon-info: ^5.3.21 => 5.3.21
    @storybook/addon-links: ^6.4.9 => 6.4.9
    @storybook/addons: ^6.4.9 => 6.4.9
    @storybook/react: ^6.4.9 => 6.4.9`

**Comment by shilman** [comment]
Do you a have a reproduction repo you can share? If not, can you create one? See [how to create a repro](https://storybook.js.org/docs/react/contribute/how-to-reproduce).
