### ISSUE TITLE
build-storybook gets stuck on "Generating browser application bundles (phase: setup)" for Angular v12 on sb 6.4

### ISSUE THREAD

**Issue by DigiBanks99** [storybookjs/storybook#17107]
**Describe the bug**

Since upgrading to Storybook v6.4 with Angular v12, when running `npm run build-storybook` the generation completes successfully, but the command doesn't complete and gets stuck in the console with the message: _Generating browser application bundles (phase: setup)_.

The problem seems to be setting `progress: true` in _angular.json:projects/{{my-project}}/architect/build/options_. Removing `progress: true` bypasses the issue, but this also makes running `ng build` not report progress which sucks.

**To Reproduce**

I've created a minimal repro at [here](https://github.com/DigiBanks99/ng-sb).

1. Create a new Angular app on v12: `ng new ng-sb --strict`
2. Add Storybook using `npx sb init`
3. Modify angular.json to produce progress status when building by adding `progress: true` to _projects/ng-sb/architect/build/options_

**System**

```
Environment Info:

  System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz
  Binaries:
    Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.1.1 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.1.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 96.0.4664.110
    Edge: Spartan (44.19041.1266.0), Chromium (96.0.1054.62)
  npmPackages:
    @storybook/addon-actions: ^6.4.9 => 6.4.9
    @storybook/addon-docs: ^6.4.9 => 6.4.9
    @storybook/addon-essentials: ^6.4.9 => 6.4.9
    @storybook/addon-links: ^6.4.9 => 6.4.9
    @storybook/angular: ^6.4.9 => 6.4.9
    @storybook/builder-webpack5: ^6.4.9 => 6.4.9
    @storybook/manager-webpack5: ^6.4.9 => 6.4.9
```

**Additional context**

N/A

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
