### ISSUE TITLE
Unable to use babel non legacy decorators with webpack5 in v6.4/6.5 (v6.3 works fine)

### ISSUE THREAD

**Issue by blikblum** [storybookjs/storybook#17101]
**Describe the bug**
When trying to use  @babel/plugin-proposal-decorators with {legacy: false} and  using webpack5 an error occurs while building: Error: Cannot use the decorators and decorators-legacy plugin together

**To Reproduce**
The  https://github.com/blikblum/nextbone-bootstrap-starter shows the issue, specifically the storybook6.4 branch: https://github.com/blikblum/nextbone-bootstrap-starter/tree/storybook6.4

The master branch i downgraded to 6.3.8 and works fine

**System**

System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
  Binaries:
    Node: 14.18.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.1.1 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (96.0.1054.62)
  npmPackages:
    @storybook/addon-essentials: ^6.4.9 => 6.4.9
    @storybook/builder-webpack5: ^6.4.9 => 6.4.9
    @storybook/manager-webpack5: ^6.4.9 => 6.4.9
    @storybook/web-components: ^6.4.9 => 6.4.9

**Additional context**
Adding  `features: {  babelModeV7: true,  },` does not have influence

**Comment by shilman** [comment]
Are there conditions under which this work (e.g. older versions of storybook, webpack4, etc.)?

**Comment by blikblum** [comment]
> [](https://github.com/blikblum/nextbone-bootstrap-starter/tree/storybook6.4)
> 
> The master branch i downgraded to 6.3.8 and works fine

Version 6.3.8 works fine. In the repro repository the master branch uses 6.3.8. Currently i am using this version in my projects.

**Comment by blikblum** [comment]
I will test with webpack4 but ifair it works fine

**Comment by blikblum** [comment]
I did further investigation and found that the issue was introduced in version 6.4.0-alpha.31. Versions 6.3.13 up to 6.4.0-alpha.30 works fine.

Looking at the alpha.31 commits the only culprit candidate seems to be https://github.com/storybookjs/storybook/commit/6ec4d214a171246d05ff6386f6f90e6012d09578

Version 6.5.10 have the same issue.

I fixed by patching the babel loader options in webpack config to use decorator legacy: false option: https://github.com/blikblum/nextbone-bootstrap-starter/commit/11de073ba384e47742fdf99bde412a960a0349c0

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
