### ISSUE TITLE
addon-storyshots 6.0.21 - expo 44 - react 17 - pragma and pragmaFrag cannot be set when runtime is automatic

### ISSUE THREAD

**Issue by abdullahbayram** [storybookjs/storybook#17115]
**The bug**
I upgraded a project from 42 to expo 44. When I ran the storyshot tests the following error occurred:
node_modules/@storybook/addon-storyshots/dist/frameworks/preact/loader.js: pragma and pragmaFrag cannot be set when runtime is automatic. At version 42(expo) the storyshots were working fine.
Some other upgraded dependencies:
react: 16.13.1 => 17.0.1
react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.64.3
babel-core: ~7.9.0 => ^7.12.9
babel-preset-expo: ^8.5.1 => 9.0.1
jest: ^26.4.2 => ^26.6.3
jest-expo: ^42.0.0=>^44.0.0
react-test-renderer: ^16.13.1 => ^17.0.2

**Reproducible Example**
https://github.com/abdullahbayram/storybook-sample-pragma-error 

**System**
  System:
    OS: macOS 11.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 14.17.3 - ~/.nvm/versions/node/v14.17.3/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.3.0 - ~/.nvm/versions/node/v14.17.3/bin/npm
  Browsers:
    Chrome: 96.0.4664.110
    Safari: 14.1.1
  npmPackages:
    @storybook/addon-actions: ^6.0.20 => 6.0.20 
    @storybook/addon-essentials: ^6.0.20 => 6.0.20 
    @storybook/addon-knobs: ^6.0.18 => 6.0.18 
    @storybook/addon-links: ^6.0.20 => 6.0.20 
    @storybook/addon-ondevice-actions: ^5.3.23 => 5.3.23 
    @storybook/addon-ondevice-knobs: ^5.3.19 => 5.3.19 
    @storybook/addon-storyshots: ^6.0.21 => 6.0.21 
    @storybook/react-native: ^5.3.21 => 5.3.21 
    @storybook/react-native-server: ^5.3.21 => 5.3.21 

**Additional context**
This situation may be related https://github.com/facebook/jest/issues/11394 or https://github.com/storybookjs/storybook/issues/13422

**Comment by abdullahbayram** [comment]
Any suggestion or comment?

**Comment by abdullahbayram** [comment]
Hi again! I have tried a couple of workarounds. When I remove a line from the @storybook/addon-storyshots/dist/frameworks/preact/loader.js file, the storyshots work: https://github.com/abdullahbayram/storybook-sample-pragma-error/blob/solution-trial/patches/%40storybook%2Baddon-storyshots%2B6.0.21.patch

Working example: https://github.com/abdullahbayram/storybook-sample-pragma-error/tree/solution-trial

I removed this:
`/** @jsx h */`

**Comment by konstantin-shkel** [comment]
I'm experiencing the same problem after migration to expo 44.

I changed `babel-preset-expo` in babel.config.js to  `['babel-preset-expo', { jsxRuntime: 'classic' }]`

Potentially it should help, but now I see the next error ` TypeError: Cannot read property 'addEventListener' of undefined`

At least it looks like smth local.

**Comment by abdullahbayram** [comment]
@konstantin-shkel it worked on repro(https://github.com/abdullahbayram/storybook-sample-pragma-error/tree/solution_trial_II) and my app. Thanks!
