### ISSUE TITLE
Update @jest/transform

### ISSUE THREAD

**Issue by 1Jesper1** [storybookjs/storybook#17112]
https://github.com/storybookjs/storybook/blob/239687e9dc27cac852583fc66472e2d3cc81a570/addons/docs/package.json#L62

To fix _sane_ deprecated error: `sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added` in _jest-haste-map_

**Comment by dartess** [comment]
Duplicated: https://github.com/storybookjs/storybook/issues/17019 , should be fixed in 7.0

**Comment by mogsdad** [comment]
Not fixed as of `@storybook/addon-docs@7.0.0-alpha.48`.

**Comment by ndelangen** [comment]
Fixed: https://github.com/storybookjs/storybook/blob/ae3640239c00bb95c398ea793d9ab6080e3a0682/code/addons/docs/package.json#L104
