### ISSUE TITLE
Background is flashing when switching stories

### ISSUE THREAD

**Issue by Mikilll94** [storybookjs/storybook#17122]
**Describe the bug**
When switching stories, the background is flashing which is really annoying.

![Screen Recording 2022-01-04 at 20 51 32](https://user-images.githubusercontent.com/17653648/148115987-7ce6bfa3-635f-4a42-99bf-21cf389fe00a.gif)

**To Reproduce**

https://github.com/Mikilll94/storybook-flash

**System**
```
Environment Info:

  System:
    OS: macOS 11.6.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Binaries:
    Node: 16.13.0 - /usr/local/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 8.1.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 96.0.4664.110
    Firefox: 95.0.2
    Safari: 14.1.2
```

**Additional context**
This flashing background behavior was not present in Storybook 6.4.0-beta.15. I don't know exactly which Storybook version introduced this annoying behavior.

**Comment by shilman** [comment]
Does this help? cc @yannbf https://github.com/storybookjs/storybook/pull/13711

**Comment by Mikilll94** [comment]
@shilman 
Yeah, this works. But this is not a solution. In my app there is only a black background and I don't want this transition effect by default when switching stories. I don't want to instruct developers to change something in Mac settings. And what if they are working on Windows?

I think this transition effect only makes sense when switching backgrounds, not when switching stories.

**Comment by buondevid** [comment]
Having the same problem... I have a default `white` background and when I switch stories it briefly goes to grey to become `white` right after. It's a bit annoying.

**Comment by Mikilll94** [comment]
@shilman 
Is it going to be fixed? For me it's a major blocker and I cannot update to the latest Storybook version.

You can also remove "needs triage".

**Comment by yannbf** [comment]
I found the version which introduced the bug but I'm not sure what's causing it exactly:

https://github.com/storybookjs/storybook/releases/tag/v6.4.0-beta.33

@tmeasday @shilman do you think it could be related to the changes for the [new loading state](https://github.com/storybookjs/storybook/pull/16666/files#diff-fb1e27e4b4711b3a05ab3649bf1788a5406600d764ae0e1a4ffcedf1e7b58726R115)?

**Comment by tmeasday** [comment]
@yannbf I guess it is likely because the "story loading" spinner is ever so briefly appearing. Probably wouldn't be an issue (?) if there wasn't the animation when the background comes back -- is that right?

I don't really have good context on the backgrounds addon @yannbf but I wonder if there is some way to do this:

> I think this transition effect only makes sense when switching backgrounds, not when switching stories.

**Comment by AndysonDK** [comment]
Here is a duplicate issue I think:
https://github.com/storybookjs/storybook/issues/17010

**Comment by dsk90it** [comment]
I also found a workaround, the flickering issue occurs due to` transition` property by default storybook comes with transitioned background (Pls check attached screenshot).

![Annotation 2022-02-07 134059](https://user-images.githubusercontent.com/57409886/152787450-60d86501-5aec-482f-afb0-2957f0640760.png)

**Solution : Turning off transition property works** 

1. Add `preview-body.html` inside `.storybook` folder
2. Override CSS 
```
<!-- .storybook/preview-body.html -->
<style>
  body {
    transition: none !important;
  }
</style>
```

**Comment by AndysonDK** [comment]
@dsk90it Thanks your workaround works for me! I'll be using this until this gets fixed

**Comment by shilman** [comment]
Hurrah!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-alpha.52 containing PR #17753 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by Nabil-MEDIOUNI** [comment]
Hi @shilman I'm using **Storybook V8.0.10 along with storybook-dark-mode v4.0.0.** 

Here's the present scenario: upon initially navigating to a story after clearing the cache, the screen flickers between dark and light modes. However, if I've previously visited that particular story, this flashing behavior doesn't occur.

[Untitled_ May 9, 2024 10_19 PM.webm](https://github.com/storybookjs/storybook/assets/54674189/00bc7e28-c404-402c-a529-9e29d02ee6f3)

```js
main.ts
```
![code](https://github.com/storybookjs/storybook/assets/54674189/486062e6-4315-41c8-b5b7-3518792d0c5f)

```js
preview.jsx
```
![code](https://github.com/storybookjs/storybook/assets/54674189/3ba763d5-ffbf-406e-9fcd-e2b135a9c71d)
