### ISSUE TITLE
Allow the user to default the visibility of the grid

### ISSUE THREAD

**Issue by paullewisn** [storybookjs/storybook#17120]
**Is your feature request related to a problem? Please describe**
When loading a component that has a transparent background I would like the grid to be displayed when the story loads, so that it is possible to immediately see that something is transparent.

**Describe the solution you'd like**
The ability to set the grid visibility programmatically.

**Describe alternatives you've considered**

This snippet is mentioned in the docs, but it only allows customisation, and not toggling of visibility:
````
        backgrounds: {
            grid: {
                cellSize: 20,
                opacity: 0.5,
                cellAmount: 5,
                offsetX: 16, // default is 0 if story has 'fullscreen' layout, 16 if layout is 'padded'
                offsetY: 16, // default is 0 if story has 'fullscreen' layout, 16 if layout is 'padded'
            },
        },
````
I currently use the following workaround to indicate transparency, but I would prefer to use the inbuilt grid:

````
    backgrounds: {
        default: 'light',
        values: [
            {
                name: 'light',
                value: '#ffffff center/8px 8px repeating-linear-gradient(45deg,#f6f6f6 0,#f6f6f6 0.8px,#ffffff 0,#ffffff 50%)',
            },
            {
                name: 'dark',
                value: '#000000 center/8px 8px repeating-linear-gradient(45deg,#1e1e1e 0,#1e1e1e 0.8px,#000000 0,#000000 50%)',
            },
        ],
    },
````

![image](https://user-images.githubusercontent.com/15159310/148075667-303ab489-9a7c-4b0d-9328-a07404eafc4d.png)
![image](https://user-images.githubusercontent.com/15159310/148075747-62cf7695-a666-45db-9648-cd4962a11199.png)

**Are you able to assist to bring the feature to reality?**
Yes

**Comment by shilman** [comment]
closing as dupe to #7367
