### ISSUE TITLE
(dependencies) Update @mdx-js/mdx once a stable new version is released in csf-tools

### ISSUE THREAD

**Issue by VanessaHenderson** [storybookjs/storybook#17137]
**Describe the bug**
The library currently used in @storybook/csf-tools v6.4.9 uses @mdx-js/mdx ^1.6.22. This version of mdx ultimately uses version 0.0.1 of the trim dependency which has a vulnerability (when using npm at least).
Right now the transitive path is 
<img width="234" alt="Screen Shot 2022-01-06 at 8 46 35 AM" src="https://user-images.githubusercontent.com/5092286/148279948-d73c5b3a-971f-44de-b48c-0a3dad79a89e.png">

Remark-parse stops using trim in [version 9.0.0](https://github.com/remarkjs/remark/commit/6b42465526bb15f70d98a0ea0daccea01ffb8004#diff-0828111e0233dec7891d8f0d6a9f496957215446a0935a1c71e22cc6c6c1760cL51). mdx-js updates to 9.0.0 in [this commit](https://github.com/mdx-js/mdx/commit/3080444e2a40d79e3a3ac61ec1266154f95f77bf#diff-ac3b342159924758a87a5f7b5a48087ee29bb461797aa51de76b33c87aab87a2R58). However, the only versions of mdx-js that have been released since this update are release candidates and not a stable version.

When @mdx-js/mdx releases a stable new version, @storybook/csf-tools should upgrade to avoid having the transitive trim vulnerability

**To Reproduce**
 Run `npm ls trim` on a project using @storybook/csf-tools

**System**
Please paste the results of `npx sb@next info` here.

**Additional context**
:)

**Comment by VanessaHenderson** [comment]
A new version of mdx has been released, https://github.com/mdx-js/mdx/releases/tag/2.0.0 This contains the fix for the trim vulnerability

**Comment by shilman** [comment]
Filed https://github.com/mdx-js/mdx/issues/1945

**Comment by shilman** [comment]
Yee-haw!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-alpha.43 containing PR #17515 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Short migration guide here https://gist.github.com/shilman/6ff2d7e18db8846e8fc552fb432ae4f6
