### ISSUE TITLE
docs: `ADDONS_SUPPORT.md` is out of date

### ISSUE THREAD

**Issue by Fullchee** [storybookjs/storybook#17150]
**Describe the bug**
The file `ADDONS_SUPPORT.md` file seems to be out of date and hasn't been updated in 2 years

https://github.com/storybookjs/storybook/blob/main/ADDONS_SUPPORT.md

This page seems to be the up to date version of that file

https://storybook.js.org/docs/react/api/frameworks-feature-support

**To Reproduce**
1. Go to https://github.com/storybookjs/storybook/blob/main/ADDONS_SUPPORT.md
2. Click on cssresources

### Next steps

1. Can this file's content be deleted or replaced with just a link to https://storybook.js.org/docs/react/api/frameworks-feature-support?
2. Any links to https://github.com/storybookjs/storybook/blob/main/ADDONS_SUPPORT.md should be updated to point to
   3. https://storybook.js.org/docs/react/api/frameworks-feature-support

**Comment by Fullchee** [comment]
I can make a PR but I don't know if `ADDONS_SUPPORT.md` is still necessary or if it can be deleted

**Comment by shilman** [comment]
@Fullchee Great catch. A PR would be much appreciated. Can you delete `ADDONS_SUPPORT.md` and update the links to point to the docs site, per your suggestion? Thanks so much! 🙏

**Comment by jonniebigodes** [comment]
@Fullchee Thanks for bringing this to our attention and your willingness to help us fix this issue. Hope you don't mind but I've pushed a pull request addressing this issue. Nonetheless, we're truly thankful for your interest in addressing this issue. Please let us know of any other issues with the docs, or if you've already spotted one, and you need help contributing.

Have a fantastic day!

Stay safe.
