### ISSUE TITLE
Single story hoisting in sidebar for MDX

### ISSUE THREAD

**Issue by juzser** [storybookjs/storybook#17157]
I'm trying to create a Single Story with many variants inside, but I don't want to show the substories on sidebar. 
I see with CSF we have `storyName` to define stories name the same with root Story, so all substories will not be shown on sidebar. 

But with MDX, I cannot do that. Do you have any solution for this? 
Please advice. Thank you

**Comment by shilman** [comment]
AFAIK single-story hoisting is only possible when there's a single story, so i'm closing as dupe to https://github.com/storybookjs/storybook/issues/9209, which is on our radar
