### ISSUE TITLE
builder-webpack4 has vulnerable postcss and is included even after updating to webpack5

### ISSUE THREAD

**Issue by mayank99** [storybookjs/storybook#17172]
Following the instructions at [`storybook-webpack5-experimental.md`](https://gist.github.com/shilman/8856ea1786dcd247139b47b270912324#upgrade), I upgraded to `webpack@5` and use `builder-webpack5` and `manager-webpack5`. While it does work correctly, I noticed that addon-docs still brings in `builder-webpack4` even in the latest version.
https://github.com/storybookjs/storybook/blob/719ccd317e1f5760b73f966534867f8fd74414c6/addons/docs/package.json#L68

This is especially a problem because `builder-webpack4` depends on postcss 7 which has this vulnerability (fixed in postcss 8): https://github.com/advisories/GHSA-566m-qj78-rww5

Dependency path:
```
@storybook/addon-essentials > @storybook/addon-docs > @storybook/builder-webpack4 > autoprefixer > postcss
```

What is the recommended path forward here? Will force-resolving postcss to v8 have any side effects?

**Comment by shilman** [comment]
The plan is to make `builder-webpack4` an optional install in 7.0, when it won't be a breaking change. In the meantime, you'll just have to live with some UNUSED dev dependencies that have vulnerabilities.

To use `postcss@8` see https://storybook.js.org/addons/@storybook/addon-postcss

**Comment by mayank99** [comment]
Makes sense, thanks for clarifying it's unused.
