### ISSUE TITLE
Storybook integration with ASP Core 

### ISSUE THREAD

**Issue by papyr** [storybookjs/storybook#17175]
Hello, can you share some Guidance documentation or sample on how to integrate storybook with asp core, there are several unanswered questions for years on [Stackoverflow 1](https://stackoverflow.com/questions/67217492/can-storybook-6-2-work-with-angular-11-in-an-asp-net-core-5-solution) or [here ](https://stackoverflow.com/questions/59938939/is-there-a-storybook-js-for-net-razor)

There is not much information at all, please help.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if this is still relevant in SB 7.x.
