### ISSUE TITLE
Integration tests failing due to hidden elements in the preview

### ISSUE THREAD

**Issue by yoavniran** [storybookjs/storybook#17188]
Just upgraded [React-Uploady](https://github.com/rpldy/react-uploady/pulls) to SB 6.4.10 from 6.3 and when I ran my cypress tests, many failed.
They fail because they look for a single "button" element in the story but now it complains there are 4.
When I inspect the story's HTML I see there are now hidden elements that were not there before:

  
<img width="2011" alt="Screen Shot 2022-01-10 at 19 18 47" src="https://user-images.githubusercontent.com/1102278/148809570-03aac74b-3760-4722-850f-51452390b4c5.png">

specifically, the `.sb-preparing-story` and `.sb-preparing-doc` hidden divs that inside contain buttons.

I see this is case also in another repo with SB 6.4.9

I know I can change my tests to use a more specific selector and avoid the issue but I just wonder if this was intended change or result of bug/oversight?  I will probably have to change them to get this to work but on the chance that its unintended I wanted to report here.

**Comment by shilman** [comment]
closing as dupe to #17064
