### ISSUE TITLE
Garbage printed to console

### ISSUE THREAD

**Issue by tamis-laan** [storybookjs/storybook#17191]
Just installed storybook into my project and I'm getting garbage when I run the command `yarn storybook`:

![screenshot](https://user-images.githubusercontent.com/3178666/148826177-507e58e6-f719-4dae-9d7c-b85a24f7c8d7.png)

**Comment by tamis-laan** [comment]
Could it be related to this:
https://newsaxes.com/the-npm-libraries-colours-and-faker-corrupted/ 

![screenshot](https://user-images.githubusercontent.com/3178666/148827562-f1ce546f-65ec-490a-bf38-6239bdb3537a.png)

**Comment by shilman** [comment]
closing as dupe to #17179
