### ISSUE TITLE
Enhanced webpack configuration modification capabilities  

### ISSUE THREAD

**Issue by longshihui** [storybookjs/storybook#17209]
**Is your feature request related to a problem? Please describe**

I'm always frustrated when modify webpack config.
Such as i want to append compile scoped of ts-loader and reserve other config, but modify webpack config object always diffcult.
I want to inspect stroybook used webpack config, but is diffcult.

```js
module.exports = {
  webpackFinal: function (config) {
    config.module.rules.filter(rule => {
       // The ts-loader rule cannot be filtered.
    })
    return config.
  }
}
```

**Describe the solution you'd like**

use **[webpack-chain](https://www.npmjs.com/package/webpack-chain)** to enhance modification capabilities , like vue-cli.

**Describe alternatives you've considered**

1. use webpack-chain to create initial webpack config
2. reserve **webpackFinal** option
3. add **chainWebpack** option to do more detail modify action.
4. merge **webpackFinal** return value and **chainWebpack**.
5. storybook use **webpack-chain** return value.

**Are you able to assist to bring the feature to reality?**

yes, but i need the time.

**Additional context**

nothing

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if this is still relevant in SB 7.x.
