### ISSUE TITLE
Addon panel resize functionality disrupts usage of the vertical scrollbar

### ISSUE THREAD

**Issue by kaiyoma** [storybookjs/storybook#17202]
**Describe the bug**
Trying to use the vertical scrollbar of a story is blocked by the resize functionality.

**To Reproduce**

1. Move the addon panel to the right
2. Open a story that is tall enough to create a vertical scrollbar
3. Try to use the vertical scrollbar

Here's a screenshot showing how the resize functionality is interfering with the scrolling. The only way to capture the mouse pointer is to take a photo of my screen, so I apologize for the jankiness here:

![PXL_20220111_185126466_2](https://user-images.githubusercontent.com/10719780/149003899-9685cb94-3b87-4d97-8e4b-4ff4cf0b31f4.jpg)

**System**
```
Environment Info:

  System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
  Binaries:
    Node: 16.13.0 - C:\Program Files\Node.js\node.EXE
    npm: 8.1.4 - C:\Program Files\Node.js\npm.CMD
  Browsers:
    Chrome: 96.0.4664.110
    Edge: Spartan (44.19041.1266.0), Chromium (97.0.1072.55)
  npmPackages:
    @storybook/addon-actions: 6.4.9 => 6.4.9
    @storybook/addon-controls: 6.4.9 => 6.4.9
    @storybook/addon-docs: 6.4.9 => 6.4.9
    @storybook/addon-knobs: 6.4.0 => 6.4.0
    @storybook/addons: 6.4.9 => 6.4.9
    @storybook/api: 6.4.9 => 6.4.9
    @storybook/components: 6.4.9 => 6.4.9
    @storybook/core: 6.4.9 => 6.4.9
    @storybook/core-events: 6.4.9 => 6.4.9
    @storybook/react: 6.4.9 => 6.4.9
    @storybook/theming: 6.4.9 => 6.4.9
```

**Comment by shilman** [comment]
Yay!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-alpha.10 containing PR #17663 that references this issue. Upgrade today to the `@future` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
