### ISSUE TITLE
Error: Can't import the named export '******' from non EcmaScript module (only default export is available)

### ISSUE THREAD

**Issue by Anastasia226** [storybookjs/storybook#17200]
Im use vue3/typescript and plugin element-plus, after update element-plus I got a error  Can't import the named export '******' from non EcmaScript module (only default export is available) when run storybook/ 
My configiration storybook/main.js
const path = require('path');
const TsconfigPathsPlugin = require('tsconfig-paths-webpack-plugin');

module.exports = {
    stories: ['../src/**/*.stories.mdx', '../src/**/*.stories.@(js|jsx|ts|tsx)'],

    addons: ['@storybook/addon-links', '@storybook/addon-essentials', '@storybook/addon-knobs'],

    babel: async (options) => ({
        ...options,
        targets: {
            chrome: '81',
            firefox: '53',
        },
    }),
    webpackFinal: async (config) => {   
        (function handleScss() {
            config.module.rules.push({
                test: /\.scss$/,
                use: [
                    'style-loader',
                    'css-loader',
                    {
                        loader: 'sass-loader',
                        options: {
                            prependData: `
    
                      @import 'src/assets/scss/vars/style/colors.scss';
                      @import 'src/assets/scss/vars/style/shadows.scss';
                      @import 'src/assets/scss/vars/style/spacing.scss';
                      @import 'src/assets/scss/vars/style/typography.scss';
                      @import 'src/assets/scss/mixins';
                      @import 'src/assets/scss/default-override.scss';
    
                      `,
                        },
                    },
                ],
                include: path.resolve(__dirname, '../'),
            });
        })();  
        
        config.resolve.plugins = config.resolve.plugins || [];
        config.resolve.plugins.push(new TsconfigPathsPlugin({}));
        return config;
    },
};
Before add this --> 
 config.module.rules.push({
                test: /\.mjs$/,
                include: /node_modules/,
                type: "javascript/auto",
                loader: 'ts-loader',
                options: { appendTsSuffixTo: [/\.vue$/] },
    
            });
in file storybook/main.js storybook is going, but components from element-plus dont import/ Please help me.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
