### ISSUE TITLE
Angular - fresh project, cannot add storybook: favicon.ico asset path must start with project source root

### ISSUE THREAD

**Issue by DinoSourcesRex** [storybookjs/storybook#17217]
**Describe the bug**

When trying to run `npm run build-storybook` I am presented with an error telling me that the `favicon.ico` asset path must start with the project source root, which it does.

You can find a minimal reproducible project [here](https://github.com/DinoSourcesRex/storybook-minimal).

I have also tried moving the `favicon.ico` into the `/assets` folder and removing the reference in the `angular.json` however the issue then just gets pushed down to the entire `/assets` folder.

**To Reproduce**

Using my repo:

1. Go [here](https://github.com/DinoSourcesRex/storybook-minimal) and clone the repo
2. `npm install`
3. `npm run build-storybook`
4. Observe the error

From scratch:

1. Install Angular 13
2. run `ng new myworkspace --create--application false`
3. `cd myworkspace`
4. `ng generate application myapplication --routing --styles scss`
5. Install storybook using `npx -p @storybook/cli sb init --type angular`
6. Update `angular.json` to add
```
        "storybook": {
          "builder": "@storybook/angular:start-storybook",
          "options": {
            "browserTarget": "angular-cli:build",
            "port": 4400
          }
        },
        "build-storybook": {
          "builder": "@storybook/angular:build-storybook",
          "options": {
            "browserTarget": "angular-cli:build"
          }
        }
```
7. Run `npm install`
8. Run `npm run build-storybook` 
9. Observe the error

**System**
Environment Info:

  System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
  Binaries:
    Node: 16.13.2 - U:\Program Files\nodejs\node.EXE
    npm: 8.1.2 - U:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (97.0.1072.55)
  npmPackages:
    @storybook/addon-actions: ^6.4.12 => 6.4.12
    @storybook/addon-essentials: ^6.4.12 => 6.4.12
    @storybook/addon-links: ^6.4.12 => 6.4.12
    @storybook/angular: ^6.4.12 => 6.4.12
    @storybook/builder-webpack5: ^6.4.12 => 6.4.12
    @storybook/manager-webpack5: ^6.4.12 => 6.4.12

**Additional context**
I also get a comment regarding how the setup will not work with Storybook version 7.0.0, any advice regarding this would also be welcome.

**Comment by Itrulia** [comment]
Yes thats exactly what I meant. This will solve the storybook error but the Angular build will fail.

**Comment by DinoSourcesRex** [comment]
What is the recommended solution to this problem? Is it documented somewhere? Is there a read me / guide that explains how to set this up for Angular 13?

**Comment by grantweeks** [comment]
I was able to fix this by changing the assets to use the object format. Using that bypasses the source root path.

`            "assets": [
              {
                "glob": "**/favicon.ico",
                "input": "client/src",
                "output": ""
              },
              {
                "glob": "**/*",
                "input": "client/src/assets",
                "output": "assets"
              },
              {
                "glob": "**/manifest.webmanifest",
                "input": "client/src",
                "output": ""
              }
            ],`

**Comment by marakoss** [comment]
> @grantweeks Angular builds with this, but unfortunately Storybook has led me to another error.
> 
> ```
> ERR! => Failed to build the preview
> ERR! Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
> ERR! Error: F:\repos\.play\storybook-minimal\stories\Button.stories.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
> ERR!     at F:\repos\.play\storybook-minimal\node_modules\@ngtools\webpack\src\ivy\loader.js:60:26
> ERR! Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
> ERR! Error: F:\repos\.play\storybook-minimal\stories\Header.stories.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
> ERR!     at F:\repos\.play\storybook-minimal\node_modules\@ngtools\webpack\src\ivy\loader.js:60:26
> ERR! Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
> ERR! Error: F:\repos\.play\storybook-minimal\stories\Page.stories.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
> ERR!     at F:\repos\.play\storybook-minimal\node_modules\@ngtools\webpack\src\ivy\loader.js:60:26
> ERR! F:/repos/.play/storybook-minimal/projects/squads/src/app/app-routing.module.ts is part of the TypeScript compilation but it's unused.
> ERR! Add only entry points to the 'files' or 'include' properties in your tsconfig.
> ERR! F:/repos/.play/storybook-minimal/projects/squads/src/app/app.component.ts is part of the TypeScript compilation but it's unused.
> ERR! Add only entry points to the 'files' or 'include' properties in your tsconfig.
> ERR! F:/repos/.play/storybook-minimal/projects/squads/src/app/app.module.ts is part of the TypeScript compilation but it's unused.
> ERR! Add only entry points to the 'files' or 'include' properties in your tsconfig.
> ERR! F:/repos/.play/storybook-minimal/projects/squads/src/environments/environment.ts is part of the TypeScript compilation but it's unused.
> ERR! Add only entry points to the 'files' or 'include' properties in your tsconfig.
> ERR! F:/repos/.play/storybook-minimal/projects/squads/src/main.ts is part of the TypeScript compilation but it's unused.
> ERR! Add only entry points to the 'files' or 'include' properties in your tsconfig.
> <s> [webpack.Progress] 99% cache shutdown
> <s> [webpack.Progress] 99% cache shutdown
> <s> [webpack.Progress] 100%
> 
> ERR! Error: => Webpack failed, learn more with --debug-webpack
> ERR!     at F:\repos\.play\storybook-minimal\node_modules\@storybook\builder-webpack5\dist\cjs\index.js:200:62
> ERR!     at F:\repos\.play\storybook-minimal\node_modules\webpack\lib\HookWebpackError.js:68:3
> ERR!     at Hook.eval [as callAsync] (eval at create (F:\repos\.play\storybook-minimal\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:11:1)
> ERR!     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (F:\repos\.play\storybook-minimal\node_modules\tapable\lib\Hook.js:18:14)
> ERR!     at Cache.shutdown (F:\repos\.play\storybook-minimal\node_modules\webpack\lib\Cache.js:150:23)
> ERR!     at F:\repos\.play\storybook-minimal\node_modules\webpack\lib\Compiler.js:1158:15
> ERR!     at Hook.eval [as callAsync] (eval at create (F:\repos\.play\storybook-minimal\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
> ERR!     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (F:\repos\.play\storybook-minimal\node_modules\tapable\lib\Hook.js:18:14)
> ERR!     at Compiler.close (F:\repos\.play\storybook-minimal\node_modules\webpack\lib\Compiler.js:1151:23)
> ERR!     at F:\repos\.play\storybook-minimal\node_modules\@storybook\builder-webpack5\dist\cjs\index.js:199:20
> ERR!     at finalCallback (F:\repos\.play\storybook-minimal\node_modules\webpack\lib\Compiler.js:436:32)
> ERR!     at F:\repos\.play\storybook-minimal\node_modules\webpack\lib\Compiler.js:453:13
> ERR!     at Hook.eval [as callAsync] (eval at create (F:\repos\.play\storybook-minimal\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:23:1)
> ERR!     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (F:\repos\.play\storybook-minimal\node_modules\tapable\lib\Hook.js:18:14)
> ERR!     at onCompiled (F:\repos\.play\storybook-minimal\node_modules\webpack\lib\Compiler.js:451:21)
> ERR!     at F:\repos\.play\storybook-minimal\node_modules\webpack\lib\Compiler.js:1129:17
> ERR!  Error: => Webpack failed, learn more with --debug-webpack
> ERR!     at F:\repos\.play\storybook-minimal\node_modules\@storybook\builder-webpack5\dist\cjs\index.js:200:62
> ERR!     at F:\repos\.play\storybook-minimal\node_modules\webpack\lib\HookWebpackError.js:68:3
> ERR!     at Hook.eval [as callAsync] (eval at create (F:\repos\.play\storybook-minimal\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:11:1)
> ERR!     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (F:\repos\.play\storybook-minimal\node_modules\tapable\lib\Hook.js:18:14)
> ERR!     at Cache.shutdown (F:\repos\.play\storybook-minimal\node_modules\webpack\lib\Cache.js:150:23)
> ERR!     at F:\repos\.play\storybook-minimal\node_modules\webpack\lib\Compiler.js:1158:15
> ERR!     at Hook.eval [as callAsync] (eval at create (F:\repos\.play\storybook-minimal\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
> ERR!     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (F:\repos\.play\storybook-minimal\node_modules\tapable\lib\Hook.js:18:14)
> ERR!     at Compiler.close (F:\repos\.play\storybook-minimal\node_modules\webpack\lib\Compiler.js:1151:23)
> ERR!     at F:\repos\.play\storybook-minimal\node_modules\@storybook\builder-webpack5\dist\cjs\index.js:199:20
> ERR!     at finalCallback (F:\repos\.play\storybook-minimal\node_modules\webpack\lib\Compiler.js:436:32)
> ERR!     at F:\repos\.play\storybook-minimal\node_modules\webpack\lib\Compiler.js:453:13
> ERR!     at Hook.eval [as callAsync] (eval at create (F:\repos\.play\storybook-minimal\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:23:1)
> ERR!     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (F:\repos\.play\storybook-minimal\node_modules\tapable\lib\Hook.js:18:14)
> ERR!     at onCompiled (F:\repos\.play\storybook-minimal\node_modules\webpack\lib\Compiler.js:451:21)
> ERR!     at F:\repos\.play\storybook-minimal\node_modules\webpack\lib\Compiler.js:1129:17
> ```

I can confirm this. Look like related to this commit: 
https://github.com/angular/angular-devkit-build-angular-builds/commit/593ee097c38557ca10c0aea5f4d03359be7195c1

**Comment by DinoSourcesRex** [comment]
Any update on this?

**Comment by trytuna** [comment]
I am also having the same problem

**Comment by DinoSourcesRex** [comment]
Hey there. So I've pushed an update to the repo I linked which has fixed the issue. You can see the commit [here](https://github.com/DinoSourcesRex/storybook-minimal/commit/65ad5d1e34990b7bbccc125d706cb728e88857a4).

The highlights are the following:

1) Updating the `.storbook/tsconfig.json` to include `"../stories/**/*",`. [See here](https://github.com/DinoSourcesRex/storybook-minimal/commit/65ad5d1e34990b7bbccc125d706cb728e88857a4#diff-ece0ba7236b1d0ffa7830b756cc5a6a9fdcf0a405286086f55bd5f6273239b55R13).
2) Updating `angular.json` to include the correct configuration for Angular 13. [See here](https://github.com/DinoSourcesRex/storybook-minimal/commit/65ad5d1e34990b7bbccc125d706cb728e88857a4#diff-2d2675bb4687601a5c7ccf707455132f90f3516a33716185687e5c41df59ac7dR105).

```
    "storybook": {
      "projectType": "application",
      "root": "stories",
      "sourceRoot": "stories",
      "architect": {
        "build": {
          "options": {
            "tsConfig": ".storybook/tsconfig.json",
            "styles": ["projects/squads/src/styles.scss"],
            "scripts": []
          }
        }
      }
    }
```

---

I cannot take full credit for this as another user pointed me in the right direction via email. Unfortunately they never commented here so I can't credit them! But thank you secret helper.
