### ISSUE TITLE
UI for toggling addons panel

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#17227]
Currently it's possible to show and hide the sidebar with a UI thanks to https://github.com/storybookjs/storybook/pull/15369

Among other things, this makes the sidebar discoverable if it gets accidentally collapsed via a toolbar shortcut.

We should have the same thing for the addons panel, esp. since there might be a long-standing bug that hides the addon panel

**Comment by Tomastomaslol** [comment]
Hi @shilman!

Would something like this work?

https://user-images.githubusercontent.com/1872246/149897087-db2540dc-a5ec-40e8-bd9e-d2a83abb67eb.mp4

Is there any icon that is used to describe the addons panel?

**Comment by shilman** [comment]
@Tomastomaslol I think we have a design in mind for this. @MichaelArestad can you share a screenshot?

**Comment by Pepijnk12** [comment]
I would like to work on this. Is the design ready?

**Comment by MichaelArestad** [comment]
Alrighty. Sorry for the delay.

Let's add an `IconButton` to the toolbar just to the left of the full screen icon. 

1. The icon should only be visible when the addon panel is closed.
2. The specific icon change to reflect that last known dock state of the addon panel (right or bottom). If we don't know the last state, it should default to the bottom.

### Screenshot

<img width="1202" alt="image" src="https://user-images.githubusercontent.com/1123119/158212359-a505ca2d-bb7a-4e92-a04e-6103bd69a8d3.png">


### Icons proposed

1. [bottombartoggle](https://master--5ccbc373887ca40020446347.chromatic.com/?path=/story/icon--basic&args=icon:bottombartoggle)
3. [sidebaralttoggle](https://master--5ccbc373887ca40020446347.chromatic.com/?path=/story/icon--basic&args=icon:sidebaralttoggle)

**Comment by Tomastomaslol** [comment]
Thanks, @MichaelArestad! I should be able to PR this fairly soon.

**Comment by Tomastomaslol** [comment]
@MichaelArestad @shilman 

I just opened https://github.com/storybookjs/storybook/pull/17714. Please let me know if you like the implementation and if there anything i can do to improve the code! :)

https://user-images.githubusercontent.com/1872246/158329388-f37cf1aa-c783-431b-8ddb-9dc7fd3b20e4.mp4

**Comment by shilman** [comment]
Egads!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-alpha.50 containing PR #17714 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
