### ISSUE TITLE
Date control in addon-controls isn't wide enough when the addon panel is docked to the right

### ISSUE THREAD

**Issue by kaiyoma** [storybookjs/storybook#17225]
**Describe the bug**
The date control in addon-controls isn't wide enough when the addon panel is docked to the right.

**To Reproduce**

1. Open a story with a date control
2. Dock the addon panel to the right

**System**
```
Environment Info:

  System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
  Binaries:
    Node: 16.13.0 - C:\Program Files\Node.js\node.EXE
    npm: 8.1.4 - C:\Program Files\Node.js\npm.CMD
  Browsers:
    Chrome: 96.0.4664.110
    Edge: Spartan (44.19041.1266.0), Chromium (97.0.1072.55)
  npmPackages:
    @storybook/addon-actions: 6.4.9 => 6.4.9
    @storybook/addon-controls: 6.4.9 => 6.4.9
    @storybook/addon-docs: 6.4.9 => 6.4.9
    @storybook/addon-knobs: 6.4.0 => 6.4.0
    @storybook/addons: 6.4.9 => 6.4.9
    @storybook/api: 6.4.9 => 6.4.9
    @storybook/components: 6.4.9 => 6.4.9
    @storybook/core: 6.4.9 => 6.4.9
    @storybook/core-events: 6.4.9 => 6.4.9
    @storybook/react: 6.4.9 => 6.4.9
    @storybook/theming: 6.4.9 => 6.4.9
```

**Additional context**
No matter how wide I make the panel, the date never fits:

![image](https://user-images.githubusercontent.com/10719780/149233644-b2f9f64e-99fd-45d5-a1c8-cb03721d9b32.png)

**Comment by shilman** [comment]
Crikey!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-alpha.56 containing PR #17780 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Boo-yah!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.21 containing PR #17780 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```
