### ISSUE TITLE
addon-storysource not working with Angular

### ISSUE THREAD

**Issue by dams-dev** [storybookjs/storybook#17233]
**Describe the bug**
addon-storysource not working with angular 13.1 and always display "loading source..."

**To Reproduce**
npm un -g @angular/cli 
npm un -g @storybook/cli 

npm i -g @angular/cli
npm i -g @storybook/cli@6.5.0-alpha.16 (angular 13.1 support added in alpha15)

ng new test-storybook (with default options)
cd test-storybook
sb init
npm i @storybook/addon-storysource --save-dev

-> update .storybook/main.js file to add   "@storybook/addon-storysource" in addons

npm run storybook

open http://localhost:6006/?path=/story/example-button--primary

the "Story" panel show : loading source...

**System**
Windows npm 6.14.14

![Capture](https://user-images.githubusercontent.com/2027665/149344205-2e152bb8-f0ab-4f01-b163-e9e7c1172aa2.JPG)

**Comment by jkirch57** [comment]
Hello,

I'm having the same issue, could we have some feedback on this issue ?

Regards.

**Comment by Silvere112** [comment]
Hello,

I have the same issue too

**Comment by Stusaw** [comment]
Same issue here aswell. I have tried also tried adding @storybook/source-loader and configuring webpack, still no luck?

```
module.exports = {
  stories: [],
  addons: ['@storybook/addon-essentials', '@storybook/addon-a11y',
    {
      name: '@storybook/addon-storysource',
      options: {
        rule: {
          test: [/\.stories\.ts?$/]
        },
        loaderOptions: {
          prettierConfig: { printWidth: 80, singleQuote: false },
        },
      },
    },
  ],
  staticDirs: [{ from: "./public", to: "assets" }],
  // uncomment the property below if you want to apply some webpack config globally
  webpackFinal: async (config, { configType }) => {
    // Make whatever fine-grained changes you need that should apply to all storybook configs
    config.module.rules.push({
      test: /\.stories\.ts?$/,
      use: [
        {
          loader: require.resolve('@storybook/source-loader'),
          options: { parser: 'typescript' },
        },
      ],
      enforce: 'pre',
    });

    // Return the altered config
    return config;
  },
};
```

**Comment by ydmitry** [comment]
The same issue

**Comment by SarcevicAntonio** [comment]
We are also having this issue.
Using Angular 13 and 6.4.18 of addon-storysource.

**Comment by while1618** [comment]
Had the same problem, updating addon-storysource to 6.4.19 fix it for me.

**Comment by sir-captainmorgan21** [comment]
I am having the same issue.

**Comment by netdjw** [comment]
+1

**Comment by stirelli** [comment]
+1

**Comment by q525828313** [comment]
+1

**Comment by dimamarksman** [comment]
+1

**Comment by CarstenTornow** [comment]
+1

**Comment by mmasterson-extron** [comment]
+1
NG: 13.3.6s
SB 6.5.9
storysource: 6.5.9
Webpack 5

**Comment by JijiyaT** [comment]
Hi Team,

Even after tried the workaround mentioned in https://storybook.js.org/addons/@storybook/addon-storysource.
Still we are facing this issue.

Do we have any other add ons which can be used to check the source code.

Thanks.

**Comment by certainlyakey** [comment]
Not working with Storybook 6.5.10 and Angular 14 too.

**Comment by dpeese** [comment]
@shilman Could you please help us here? Even with 6.5.10 we are facing same issue.

**Comment by Akshat55** [comment]
Also ran into this issue in Angular 12 with Storybook@6.5.10.

What I found interesting was that when running `start-storybook` directly from `package.json`, the story source loaded correctly.

But there were some complications, styles didn't load for me (I don't use `styles.scss` to add styles, I use `preview.scss` for my use case).

If I want to have styles working, I need to start/build via script in angular.json architect object & is the approach used in [documentation](https://storybook.js.org/docs/angular/get-started/install).

```json
...
"scripts": {
    "storybook": "start-storybook -p 3000" // Loads story source, but not styles
    "ng-storybook": "ng run project:storybook" // Loads styles, but not story source
}
...
```

**Comment by maertz** [comment]
Doesn't work with angular 14 either. After some deeper dive it looks like the addon doesn't register itself into the state of storybook from where it tries to pull the "locationMap". Tried to fix it but with no luck.

**Comment by byjokese** [comment]
Same problem, tried several configs and options for the loader.
* NX workspace `15.0.1`
* Angular `14.2,0`
* @storybook/addon-storysource: `6.5.12`

**Comment by vinod-amt** [comment]
facing the same in angular 16 version.

**Comment by alexcza** [comment]
I have the same issue 
Angular 15 
SB 7.4.5

**Comment by obar-zik** [comment]
Same issue:
Angular 16, @storybook/addon-storysource `7.4.5`

**Comment by breity** [comment]
+1

Just wondering if a fix is planned for this. Sad that @storybook/addon-storysource doesn't work with Angular. Thanks!

**Comment by Moutah** [comment]
Same issue
Angular 14, @storybook/addon-storysource 7.5.2

**Comment by RomainFALLER** [comment]
Same with angular 15...
