### ISSUE TITLE
StoryContextForLoaders not exported by @storybook/html

### ISSUE THREAD

**Issue by Bilge** [storybookjs/storybook#17263]
**Describe the bug**
A typed loader cannot be constructed in TypeScript's strict mode, because the first argument has type `StoryContextForLoaders` that is not exported by the `@storybook/html` library.

**To Reproduce**
```ts
import {StoryContextForLoaders, StoryObj} from '@storybook/html';

export const Test: StoryObj = {
    loaders: createLoaders(),
};

const createLoaders = () => [
    async (ctx: StoryContextForLoaders) => {
        return {
            html: 'foo',
        }
    },
];
```

>TS2304: Cannot find name 'StoryContextForLoaders'.
>TS2305: Module '"@storybook/html"' has no exported member 'StoryContextForLoaders'.

**System**
```
  System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
  Binaries:
    Node: 14.15.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.9 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 97.0.4692.71
    Edge: Spartan (44.19041.1266.0), Chromium (97.0.1072.62)
  npmPackages:
    @storybook/addon-actions: ^6.4.13 => 6.4.13
    @storybook/addon-essentials: ^6.4.13 => 6.4.13
    @storybook/addon-links: ^6.4.13 => 6.4.13
    @storybook/html: ^6.4.13 => 6.4.13
```

**Additional context**
* `StoryContext` is available, but not compatible with `StoryContextForLoaders`.
* It is not valid to omit the type i.e. `async (ctx) => {}` when TypeScript is in strict mode because it emits an error similar to the following: `TS7006: Parameter 'ctx' implicitly has an 'any' type.`

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
