### ISSUE TITLE
Colors JS vulnerability when running sb migrate

### ISSUE THREAD

**Issue by oriooctopus** [storybookjs/storybook#17261]
**Describe the bug**
<img width="1182" alt="Screen Shot 2022-01-17 at 3 29 37 PM" src="https://user-images.githubusercontent.com/20331238/149821892-d2a0d4d7-346d-4d23-bf77-7e28e5ca9d79.png">

**To Reproduce**
- npx sb init
- npx sb migrate storiesof-to-csf -g **/*.tsx

**System**
Environment Info:

  System:
    OS: macOS 11.2.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
  Browsers:
    Chrome: 97.0.4692.71
    Firefox: 94.0.2
    Safari: 14.0.3
  npmPackages:
    @storybook/addon-actions: ^6.4.13 => 6.4.13 
    @storybook/addon-essentials: ^6.4.13 => 6.4.13 
    @storybook/addon-links: ^6.4.13 => 6.4.13 
    @storybook/builder-webpack5: ^6.4.13 => 6.4.13 
    @storybook/manager-webpack5: ^6.4.13 => 6.4.13 
    @storybook/node-logger: ^6.4.13 => 6.4.13 
    @storybook/preset-create-react-app: ^4.0.0 => 4.0.0 
    @storybook/react: ^6.4.13 => 6.4.13

**Comment by shilman** [comment]
Yo-ho-ho!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.14 containing PR #17266 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```
