### ISSUE TITLE
Asking for a chance to translate official Storybook docs in English to Korean

### ISSUE THREAD

**Issue by lisohh** [storybookjs/storybook#17287]
Hello Storybook, 
I am a student studying to become a front-end developer in Korea. 
Recently, as I came across Storybook, I was reading the official documents in English. There are many sentences that the translation program does not understand correctly, **so if there is an opportunity, I and my friends would like to contribute to translating official documents (https://storybook.js.org/) from English to Korean.** 

From what I found on Git-hub, there doesn't seem to be an issue or PR 
that the official document has been translated from English to another language. **May I open a PR that translates the official document into Korean?** 

Thank you for reading! 😀
(I posted the same question on Discord :) )

**Comment by shilman** [comment]
Hi @lisohh thanks for your enthusiasm on translating. 감사합니다!!! As I mentioned in Discord we are currently only translating the tutorials, not the official documentation at this time. Closing this for now!
