### ISSUE TITLE
storySort: allow `method` to be a function

### ISSUE THREAD

**Issue by benface** [storybookjs/storybook#17298]
**Is your feature request related to a problem? Please describe**
I would like the benefits of the `order` parameter, that is, to define a custom order for top-level groups, _and_ the benefits of using a function for `storySort`, that is, order the stories in these groups according to a custom algorithm that is not just `alphabetical`.

**Describe the solution you'd like**
I would like this config to be supported:
```js
export const parameters = {
  options: {
    storySort: {
      order: ['Tokens', 'Atoms', 'Molecules', 'Organisms'],
      method: (a, b) => a[1].kind === b[1].kind ? 0 : a[1].id.localeCompare(b[1].id, undefined, { numeric: true }) * -1,
    },
  },
};
```

**Describe alternatives you've considered**
It is currently possible to achieve that by using a function for `storySort` and basically re-implementing the `order` functionality, but it requires writing and maintaining a considerable amount of code for a config option, and it is not as clear/declarative.

**Are you able to assist to bring the feature to reality?**
Yes, I will gladly make a PR if you think it's a good idea.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if this is still relevant in SB 7.x.
