### ISSUE TITLE
Composition in Docs mode

### ISSUE THREAD

**Issue by frassinier** [storybookjs/storybook#17291]
**Describe the bug**

When you build (or start) Storybook with Docs mode `--docs`, the composition will not handle the stories in the sidebar correctly.
You expect to get your story explorer in docs mode too. 
Each page must be a leaf.

**To Reproduce**

Take a look at https://design.talend.com which has a ref to https://design.talend.com/design-tokens

**Comment by shilman** [comment]
Whoopee!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-alpha.35 containing PR #17292 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
