### ISSUE TITLE
configuration discrepancies Angular 13.1

### ISSUE THREAD

**Issue by jasonhodges** [storybookjs/storybook#17305]
**Describe the bug**
I've created a new Angular v13 project and added Storybook. The standard configuration that Storybook adds to the project creates warnings yet following the documentation for correction isn't working. 

The following script is added to package.json
`"storybook": "npm run docs:json && start-storybook -p 6006",`
but when running it you are presented with warning about the startup solution not being supported in the upcoming version 7 and having to use angular builder. However, this script does not seem to respect having a configuration for Storybook inside the angular.json file. 

In the [reproduction repo](https://github.com/jasonhodges/storybook-angular13) I added an additional startup script: 
`"storybook:ng": "npm run docs:json && ng run storybook-angular13:storybook"` which does respect the angular.json storybook configuration. 

The default startup compilation processing seems different from the one based on the angular.json config looking at the console logs with both being served at the same time:

default:
![image](https://user-images.githubusercontent.com/1988476/150402384-fcc12f56-ce55-48ff-a8d2-cb4ce0f3649a.png)

angular.json config:
![image](https://user-images.githubusercontent.com/1988476/150402329-5d1c5a4c-c61d-4526-ae7c-a760d0861bf0.png)

**To Reproduce**
[reproduction repo](https://github.com/jasonhodges/storybook-angular13) 
Pull the repo and run the `storybook` and `storybook:ng` scripts

**System**

System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Binaries:
    Node: 14.15.3 - ~/.nvm/versions/node/v14.15.3/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.9 - ~/.nvm/versions/node/v14.15.3/bin/npm
  Browsers:
    Chrome: 97.0.4692.71
    Firefox: 84.0
    Safari: 15.2
  npmPackages:
    @storybook/addon-actions: ^6.4.13 => 6.4.13 
    @storybook/addon-essentials: ^6.4.13 => 6.4.13 
    @storybook/addon-links: ^6.4.13 => 6.4.13 
    @storybook/angular: ^6.4.13 => 6.4.13 
    @storybook/builder-webpack5: ^6.4.13 => 6.4.13 
    @storybook/manager-webpack5: ^6.4.13 => 6.4.13 

**Additional context**

**Comment by jonniebigodes** [comment]
@jasonhodges thanks for reaching out to us with your issue. As you may or may not have seen a pull request was pushed by me to address your issue. We're aware of this and currently working on updating our documentation and workflow for a better experience.

Hope you have a good day!

Stay safe

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
