### ISSUE TITLE
Angular output events throw error in fresh Storybook 6.5.0-alpha.22 installation

### ISSUE THREAD

**Issue by decline** [storybookjs/storybook#17302]
In a fresh Storybook 6.5.0-alpha.22 installation, when you type an Angular `@Output()` event emitter with a generic type - like this:

```ts
@Output() onClick: EventEmitter<Event> = new EventEmitter<Event>();
```

then this output event will throw an error when the Storybook action is dispatched:

```
ERROR TypeError: ctx.onClick is not a function`
```

This seems to be related to the generic type of the `EventEmitter`, for example:

```ts
/** Omitting the type => will work */
@Output() onClick = new EventEmitter<Event>();

/** Ignoring the generic type => will work */
// @ts-ignore
@Output() onClickWithType: EventEmitter = new EventEmitter<Event>();

/** Using a generic type => will throw error */
@Output() onClickWithGenericType: EventEmitter<Event> = new EventEmitter<Event>();
```

**Important:** Compodoc `documentation.json` needs to be generated for this.

**To Reproduce**
Repository: https://github.com/decline/storybook-angular-event-emitter-issue

Checkout the repository and run `yarn && yarn storybook` and then go to the Story for the button: http://localhost:6006/?path=/story/example-button--primary

Clicking the first 2 buttons will show an output in the "Actions" tab, but the last button will throw an error in the console:

<img width="1692" alt="error-screenshot" src="https://user-images.githubusercontent.com/5609744/150381863-cd934527-ff15-49f1-8961-ef0141dc6101.png">

**System**
```
Environment Info:

  System:
    OS: macOS 11.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Binaries:
    Node: 14.17.5 - ~/.nvm/versions/node/v14.17.5/bin/node
    Yarn: 3.1.1 - /usr/local/bin/yarn
    npm: 6.14.14 - ~/.nvm/versions/node/v14.17.5/bin/npm
  Browsers:
    Chrome: 97.0.4692.71
    Firefox: 96.0.1
    Safari: 15.1
  npmPackages:
    @storybook/addon-actions: ^6.5.0-alpha.22 => 6.5.0-alpha.22 
    @storybook/addon-docs: ^6.5.0-alpha.22 => 6.5.0-alpha.22 
    @storybook/addon-essentials: ^6.5.0-alpha.22 => 6.5.0-alpha.22 
    @storybook/addon-links: ^6.5.0-alpha.22 => 6.5.0-alpha.22 
    @storybook/angular: ^6.5.0-alpha.22 => 6.5.0-alpha.22 
    @storybook/builder-webpack5: ^6.5.0-alpha.22 => 6.5.0-alpha.22 
    @storybook/manager-webpack5: ^6.5.0-alpha.22 => 6.5.0-alpha.22 

```

**Comment by decline** [comment]
Closing this in favour of https://github.com/storybookjs/storybook/issues/17362

**Comment by RAJEEV2510** [comment]
How to solve this issues
