### ISSUE TITLE
Vite + Storybook = spins with an acorn-jsx error

### ISSUE THREAD

**Issue by gavula** [storybookjs/storybook#17314]
**Description:**
New install of Vite + Storybook fails to load beyond skeleton state.

**Steps to reproduce**
New project start with:

`yarn init`
`yarn add -D vite`
`npx sb@next init --builder storybook-builder-vite`
`yarn add -D react react-dom`
`yarn storybook`
> _per https://divotion.com/blog/creating-a-component-library-with-vite-and-storybook_

or 

`npm init vite`
`npx sb@next init --builder storybook-builder-vite`
`npm run storybook`
> _per https://storybook.js.org/blog/storybook-for-vite/_

In both instances the storybook page renders in skeleton mode with the progress spinner, and stays that way forever.

The console logs this error:

```Uncaught SyntaxError: The requested module '/node_modules/@storybook/addon-docs/node_modules/acorn-jsx/index.js?v=80284aab' does not provide an export named 'default'```

The former install package.json look like this:
``` "devDependencies": {
    "@babel/core": "^7.16.10",
    "@storybook/addon-actions": "^6.5.0-alpha.22",
    "@storybook/addon-essentials": "^6.5.0-alpha.22",
    "@storybook/addon-links": "^6.5.0-alpha.22",
    "@storybook/react": "^6.5.0-alpha.22",
    "babel-loader": "^8.2.3",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "storybook-builder-vite": "^0.1.13",
    "vite": "^2.7.13"
  },
  "dependencies": {},
  "scripts": {
    "storybook": "start-storybook -p 6006",
    "build-storybook": "build-storybook"
  }
  ```

**System**
Environment Info:

 ``` System:
    OS: macOS 10.15.7
    CPU: (24) x64 Intel(R) Xeon(R) CPU E5-2697 v2 @ 2.70GHz
  Binaries:
    Node: 17.2.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 97.0.4692.99
    Firefox: 95.0.2
    Safari: 15.2
  npmPackages:
    @storybook/addon-actions: ^6.5.0-alpha.22 => 6.5.0-alpha.22 
    @storybook/addon-essentials: ^6.5.0-alpha.22 => 6.5.0-alpha.22 
    @storybook/addon-links: ^6.5.0-alpha.22 => 6.5.0-alpha.22 
    @storybook/react: ^6.5.0-alpha.22 => 6.5.0-alpha.22 ```
    

    Thank you!

**Comment by christian-gama** [comment]
I can also relate this same issue. Using pnpm or yarn gives me this exactly same error. However if I use npm, everything works fine...

**Comment by gavula** [comment]
I can confirm installing with `npm` works as expected. Thanks @christian-gama.

**Comment by shilman** [comment]
Please file Vite-related issues in https://github.com/eirslett/storybook-builder-vite/

Closing this for now--please let me know if you think this ISN'T Vite-related and I'll reopen. Thank you! 🙏
