### ISSUE TITLE
React warning appearing in the console

### ISSUE THREAD

**Issue by AdamPawlinski** [storybookjs/storybook#17337]
**Describe the bug**
When loading/refreshing Storybook I receive following error in the console: 
```
Warning: Each child in a list should have a unique "key" prop.
Check the top-level render call using <Styled(div)>. See https://fb.me/react-warning-keys for more information.
```

![Screenshot from 2022-01-26 12-05-22](https://user-images.githubusercontent.com/32042425/151152352-8c34ecc0-7cfd-419e-8ad3-d399790d4871.png)

I know that there have been similar errors resolved before, but this one looks like it is caused by sth else. 
Could you, please provide any solution for it?

**System**
 System:
    OS: Linux 5.13 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
  Binaries:
    Node: 16.13.2 - /usr/bin/node
    Yarn: 1.22.17 - /usr/bin/yarn
    npm: 8.1.2 - /usr/bin/npm
  Browsers:
    Chrome: 97.0.4692.71
    Firefox: 96.0

   "@storybook/addon-a11y": "6.4.14",
    "@storybook/addon-actions": "6.4.14",
    "@storybook/addon-backgrounds": "6.4.14",
    "@storybook/addon-essentials": "6.4.14",
    "@storybook/addon-links": "6.4.14",
    "@storybook/addon-notes": ">=5.3.21",
    "@storybook/addon-storysource": "6.4.14",
    "@storybook/addon-viewport": "6.4.14",
    "@storybook/addons": "6.4.14",
    "@storybook/api": "6.4.14",
    "@storybook/components": "6.4.14",
    "@storybook/preset-scss": "^1.0.3",
    "@storybook/vue": "6.4.14",
    "@ljcl/storybook-addon-cssprops"

**Additional context**

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
