### ISSUE TITLE
Values set in `addons.setConfig` get ignored once the storybook is uploaded to S3

### ISSUE THREAD

**Issue by neil-morrison44** [storybookjs/storybook#17335]
**Describe the bug**
Weird one - I've got a `manager.js` file like
```js
import { addons } from "@storybook/addons"

console.log("addons.setConfig")
addons.setConfig({
  showNav: false,
  panelPosition: "bottom",
})
```
When the storybook is deployed to S3 I get the console.log but the nav is shown and the `panelPosition` is on the right, but the _exact same_ storybook build running in a local HTTP server will hide the nav & show the panel at the bottom.

**To Reproduce**

I've attempted to reproduce without uploading to S3 but I've failed to get it not working locally, I can probably DM an S3 link to one of our less-populated storybooks though.

**System**
```
Environment Info:

  System:
    OS: Linux 5.10 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (8) arm64 unknown
  Binaries:
    Node: 16.13.0 - /usr/bin/node
    Yarn: 1.22.15 - /usr/bin/yarn
    npm: 8.1.0 - /usr/bin/npm
  npmPackages:
    @storybook/addon-a11y: ^6.4.14 => 6.4.14 
    @storybook/addon-actions: ^6.4.13 => 6.4.14 
    @storybook/addon-essentials: ^6.4.14 => 6.4.14 
    @storybook/addon-jest: ^6.4.14 => 6.4.14 
    @storybook/addon-links: ^6.4.14 => 6.4.14 
    @storybook/addon-postcss: ^2.0.0 => 2.0.0 
    @storybook/builder-webpack5: ^6.4.14 => 6.4.14 
    @storybook/manager-webpack5: ^6.4.14 => 6.4.14 
    @storybook/react: ^6.4.14 => 6.4.14 
    @storybook/testing-react: ^1.2.3 => 1.2.3 
```

**Additional context**
The actual build happens via a github workflow, the S3 bucket is visited using its long name & over `https`.
Sorry I can't be of more help - it's a weird issue that's been effecting us for a while now across a few different storybooks.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
