### ISSUE TITLE
Svelte  using webpack5 causes error - Function called outside component initialization

### ISSUE THREAD

**Issue by dave11mj** [storybookjs/storybook#17346]
**Describe the bug**
When using `webpack5` as the builder for svelte projects stories have the following error `Function called outside component initialization`

**To Reproduce**

1. Follow steps from https://storybook.js.org/docs/react/contribute/how-to-reproduce to set up a new  project  by running `npx sb@next repro`  and selecting svelte
2. Run `yarn storybook`  verify everything works as expected
![image](https://user-images.githubusercontent.com/6619371/151269669-48ed298c-9683-451c-9366-81523dc45a5f.png)
3. Because this is an existing project follow steps below from https://gist.github.com/shilman/8856ea1786dcd247139b47b270912324
4. run `yarn add -D @storybook/builder-webpack5@next @storybook/manager-webpack5@next webpack@5`
5. Then update your `.storybook/main.js` with:
```javascript
module.exports = {
  core: {
    builder: "webpack5",
  },
};
```
6. Run `yarn storybook` notice all stories are gone
7. Open developer tools console and observe error `Function called outside component initialization`
![image](https://user-images.githubusercontent.com/6619371/151274392-3482f382-d0cc-4e83-8284-7d522333db1f.png)

**System**

```bash
Environment Info:

  System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
  Binaries:
    Node: 14.18.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.1.1 - C:\Program Files\nodejs\yarn.CMD
    npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (97.0.1072.69)
  npmPackages:
    @storybook/addon-actions: ^6.5.0-alpha.23 => 6.5.0-alpha.23
    @storybook/addon-docs: ^6.5.0-alpha.23 => 6.5.0-alpha.23
    @storybook/addon-essentials: ^6.5.0-alpha.23 => 6.5.0-alpha.23
    @storybook/addon-links: ^6.5.0-alpha.23 => 6.5.0-alpha.23
    @storybook/addon-svelte-csf: ^1.1.0 => 1.1.0
    @storybook/builder-webpack5: next => 6.5.0-alpha.23
    @storybook/manager-webpack5: next => 6.5.0-alpha.23
    @storybook/svelte: ^6.5.0-alpha.23 => 6.5.0-alpha.23
```

**Additional context**

This issue was first discovered on a MAC computer following https://storybook.js.org/blog/storybook-for-webpack-5/ and running `npx sb init --builder webpack5` on an empty directory.

Repro  with `npx sb@next repro` can be  found at https://github.com/dave11mj/storybook-svelte-webpack5-issue

**Comment by j3rem1e** [comment]
Probably related to https://github.com/storybookjs/addon-svelte-csf/issues/23#issuecomment-821541653

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
