### ISSUE TITLE
Using default Webpack5 setup ERR! ValidationError: Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.

### ISSUE THREAD

**Issue by ShomaGujjar** [storybookjs/storybook#17357]
Hello,

I keep getting the error when I try to run storybook within my typescript project.Below are my version numbers 
@storybook/addon-actions": "^6.4.14",
    "@storybook/addon-essentials": "^6.4.14",
    "@storybook/addon-links": "^6.4.14",
    "@storybook/builder-webpack5": "^6.4.14",
    "@storybook/manager-webpack5": "^6.4.14",
    "@storybook/node-logger": "^6.4.14",
    "@storybook/preset-create-react-app": "^3.2.0",
    "@storybook/react": "^6.4.14",
    "react-scripts": "^5.0.0",
    "webpack": "5"
Can somebody please help?

**Comment by n00el** [comment]
Same

- configuration.module.rules[5].oneOf[9].type should be one of these:
ERR!    "javascript/auto" | "javascript/dynamic" | "javascript/esm" | "json" | "webassembly/experimental"

**Comment by WangShuXian6** [comment]
remove @storybook/preset-create-react-app from addons

**Comment by aso1datov** [comment]
Updating @storybook/preset-create-react-app helped

**Comment by mmirus** [comment]
Yep, if you update `@storybook/preset-create-react-app` it should work:

```sh
npm install @storybook/preset-create-react-app@"^4.0.0"
```

**Comment by mcrowder65** [comment]
Updating to preset-create-react-app 4.0.0 did not work for me unfortunately. I had to apply a patch-package to preset-create-react-app to resolve a different version of react-scripts

**Comment by Kenny-Gin1** [comment]
Updating to the latest `@storybook/preset-create-react-app`^4.1.2 and then removing `@storybook/preset-create-react-app from addons worked for me!

**Comment by abencun-symphony** [comment]
Can confirm that updating to 4.1.2 works without the need to remove the preset from config.

**Comment by bmitchinson** [comment]
Getting the error with the following. Didn't have this error prior to an `npx storybook upgrade`

```
"@babel/core": "^7.18.6",
        "@storybook/addon-actions": "^6.5.13",
        "@storybook/addon-essentials": "^6.5.13",
        "@storybook/addon-interactions": "^6.5.13",
        "@storybook/addon-links": "^6.5.13",
        "@storybook/builder-webpack5": "^6.5.13",
        "@storybook/manager-webpack5": "^6.5.13",
        "@storybook/storybook-deployer": "^2.8.16",
        "@storybook/svelte": "^6.5.13",
        "@storybook/testing-library": "^0.0.13",
        "babel-loader": "^8.2.5",
        "css-loader": "^5.2.7",
        "eslint-plugin-storybook": "^0.6.7",
        "husky": "^7.0.0",
        "jest": "^28.1.2",
        "sass": "^1.53.0",
        "sass-loader": "^10.1.1",
        "storybook-addon-mock": "^3.2.0",
        "storybook-dark-mode": "^1.1.2",
        "string-replace-loader": "^3.1.0",
        "style-loader": "^2.0.0",
        "svelte-loader": "^3.1.3",
        "svelte-preprocess": "^4.10.7",
        "ts-jest": "^28.0.5"
````

**Comment by bohdan-sharkz** [comment]
Updating  `@storybook/preset-create-react-app` to `^4.1.2` didn't work in my case, but fully migrating storybook to use Webpack 5 resolved the issue. I've followed manual steps in [migration guide](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#webpack-5) 🖖

**Comment by fabpico** [comment]
Fresh install on very small React app, and it's still happening on `npm run storybook`.

```
  "dependencies": {
    "@babel/cli": "^7.20.7",
    "@babel/core": "^7.20.12",
    "babel-plugin-transform-scss": "^1.1.0"
  },
  "devDependencies": {
    "@storybook/addon-actions": "^6.5.16",
    "@storybook/addon-essentials": "^6.5.16",
    "@storybook/addon-interactions": "^6.5.16",
    "@storybook/addon-links": "^6.5.16",
    "@storybook/builder-webpack5": "^6.5.16",
    "@storybook/manager-webpack5": "^6.5.16",
    "@storybook/node-logger": "^6.5.16",
    "@storybook/preset-create-react-app": "^3.2.0",
    "@storybook/react": "^6.5.16",
    "@storybook/testing-library": "^0.0.13",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-scripts": "5.0.1",
    "sass": "^1.57.1"
  },
```

**Comment by shilman** [comment]
@fabpico `builder-webpack5` and `preset-create-react-app@3.x` are incompatible. please upgrade to 4.x if you're using webpack5/CRA5.

**Comment by fabpico** [comment]
@shilman Can't this be detected from `npx storybook init` before the dependencies are being placed through `npx storybook init`?

**Comment by shilman** [comment]
@fabpico AFAIK this is already detected and handled in both `init` and `upgrade`.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
