### ISSUE TITLE
Docs tab is not working in Storybook with Vite.js

### ISSUE THREAD

**Issue by yushanwebdev** [storybookjs/storybook#17366]
**Describe the bug**
I have set up the Storybook in my vite.js project as per the instructions provided in [this official article](https://storybook.js.org/blog/storybook-for-vite/). Storybook started perfectly in 6006 port. But the problem is the Docs tab throws me this error when I switch to it.

<img width="1440" alt="Screenshot 2022-01-29 at 14 14 01" src="https://user-images.githubusercontent.com/25406148/151654730-637261d3-a148-494b-8eff-65127176371e.png">

**To Reproduce**
You can use this to reproduce that issue. 
https://github.com/yushanwebdev/storybook-with-vite/tree/storybook-issue

**Steps to Reproduce**

1. Clone the repo.
2. Switch to the `storybook-issue` branch.
3. Run `yarn`
4. Run `yarn run storybook`
5. Select the *Primary* story in the *Button*
6. Select the *Docs tab*

**System**
```
Environment Info:
  System:
    OS: macOS 12.1
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 17.2.0 - /opt/homebrew/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.1.4 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 97.0.4692.99
    Firefox: 96.0.2
    Safari: 15.2
  npmPackages:
    @storybook/addon-actions: ^6.4.15 => 6.4.15 
    @storybook/addon-essentials: ^6.4.15 => 6.4.15 
    @storybook/addon-links: ^6.4.15 => 6.4.15 
    @storybook/react: ^6.4.15 => 6.4.15
```

**Additional context**
I have tried the solutions mentioned in https://github.com/storybookjs/storybook/issues/10982 also. But didn't work out.

**Comment by shilman** [comment]
Please file Vite-related issues in https://github.com/eirslett/storybook-builder-vite/

Closing this for now--please let me know if you think this ISN'T Vite-related and I'll reopen. Thank you! 🙏
