### ISSUE TITLE
Svelte-Templates in @storybook/svelte missing in v6.5.0-alpha.25

### ISSUE THREAD

**Issue by benbender** [storybookjs/storybook#17360]
**Describe the bug**
The changes in `6.5.0-alpha.25` in the build-infrastructure are leading to missing Svelte-templates in `@storybook/svelte`.

6.5.0-alpha.25:
````
/node_modules/@storybook/svelte/dist/cjs/client/preview/
.rw-r--r-- bb staff 660 B  Wed Jan 26 21:33:54 2022  config.js
.rw-r--r-- bb staff 2.8 KB Fri Jan 28 12:18:36 2022  decorators.js
.rw-r--r-- bb staff 251 B  Tue Jul 20 19:44:11 2021  globals.js
.rw-r--r-- bb staff 1.5 KB Wed Jan 26 21:33:54 2022  index.js
.rw-r--r-- bb staff 1.5 KB Fri Jan 28 12:18:36 2022  render.js
.rw-r--r-- bb staff  13 B  Fri Jul 16 16:27:46 2021  types.js
````

vs
6.5.0-alpha.24:

````
/node_modules/@storybook/svelte/dist/cjs/client/preview/
.rw-r--r-- bb staff 660 B  Wed Jan 26 21:33:54 2022  config.js
.rw-r--r-- bb staff 2.7 KB Wed Jan 26 21:33:54 2022  decorators.js
.rw-r--r-- bb staff 251 B  Tue Jul 20 19:44:11 2021  globals.js
.rw-r--r-- bb staff 1.5 KB Wed Jan 26 21:33:54 2022  index.js
.rw-r--r-- bb staff 886 B  Tue Jul 20 19:44:11 2021  PreviewRender.svelte
.rw-r--r-- bb staff 1.4 KB Wed Jan 26 21:33:54 2022  render.js
.rw-r--r-- bb staff 821 B  Tue Jul 20 19:44:11 2021  SlotDecorator.svelte
.rw-r--r-- bb staff  13 B  Fri Jul 16 16:27:46 2021  types.js
````

**Comment by benbender** [comment]
@shilman 👁️

**Comment by shilman** [comment]
That was fast!! @ndelangen  is on the case 🕵️‍♂️

**Comment by ndelangen** [comment]
@benbender how are these files referenced / used?

I'd like to move them out of the `dist` directory, and into `@storybook/svelte/templates`.

**Comment by benbender** [comment]
@ndelangen They are used to handle svelte "Slots" in js-land. And they need to be importable. `v6.5.0-alpha.26` breaks with 
`"ModuleNotFoundError: Module not found: Error: Can't resolve '@storybook/svelte/templates/SlotDecorator.svelte' in '[…]/node_modules/.pnpm/@storybook+svelte@6.5.0-alpha.26_49170c3e2c121add69f6e6d50372286d/node_modules/@storybook/svelte/dist/esm/client/preview'`

Which is called by `node_modules/@storybook/addon-docs/dist/cjs/frameworks/svelte/svelte-docgen-loader.js`

Afaik they need to be in `dist` as they are directly (indirectly) referenced by other packages.

**Comment by ndelangen** [comment]
Owh I think I see. This seems a limitation of pnpm? a modules can't resolve itself?

**Comment by benbender** [comment]
No, they are simply not exported and not included in the published package. No package-manager can import whats not even there in the first place ;) It may work if you add `"templates/**/*"` to `files` in `package.json`.

**Comment by ndelangen** [comment]
ow, did I forgot to do that for this package?!

**Comment by ndelangen** [comment]
if so that's an easy fix!

**Comment by shilman** [comment]
Ooh-la-la!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-alpha.28 containing PR #17367 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
