### ISSUE TITLE
tailwindscs v3 spport

### ISSUE THREAD

**Issue by kr-anurag** [storybookjs/storybook#17374]

**Comment by HIMISOCOOL** [comment]
tailwind works fine as long as you use postcss, you just need to add this package:
`@storybook/addon-postcss`
and then modify your main.js to use the addon:
![image](https://user-images.githubusercontent.com/1725300/151885318-30812004-c4be-44cf-ad49-a45d94485e66.png)

**Comment by kr-anurag** [comment]
Can you share a codebase in the form of a github repo where tailwindcss v3 is being used?

**Comment by kr-anurag** [comment]
> tailwind v3 works fine as long as you use postcss8, you just need to add this package: `@storybook/addon-postcss` and then modify your main.js to use the addon: ![image](https://user-images.githubusercontent.com/1725300/151885318-30812004-c4be-44cf-ad49-a45d94485e66.png)

hey, can you share a codebase in the form of a github repo where tailwindcss v3 with react is being used
