### ISSUE TITLE
[REGRESSION] Storybook adds displayName and __docgenInfo in TS enum

### ISSUE THREAD

**Issue by totszwai** [storybookjs/storybook#17407]
**Describe the bug**
Regression of https://github.com/storybookjs/storybook/issues/9832

The enum, typical normal enum:
```
/**
 * Supported ColumnLayout, refer to UX documentation for their naming and styling
 */
export enum SupportedColumnLayout {
  XXLarge = 'xxlarge',
  XLarge = 'xlarge',
  Large = 'large',
  Medium = 'medium',
  Small = 'small'
}
```
The code in story:
```
  const entries = _.entries(SupportedColumnLayout);
  console.log(SupportedColumnLayout);
  const options = entries.map(([label, value]) => {
    return { label, value };
  });
```
![image](https://user-images.githubusercontent.com/4440365/152356045-bb2e0338-fb13-4c17-a487-e2a5f513a00b.png)

![image](https://user-images.githubusercontent.com/4440365/152355701-2935dc35-ec10-4d67-8f3a-b4734c70b8d3.png)

**To Reproduce**

1. Use latest Storybook
2. Start storybook

**System**
npx sb@next info

Environment Info:

  System:
    OS: Linux 5.13 Ubuntu 21.10 21.10 (Impish Indri)
    CPU: (16) x64 Intel(R) Xeon(R) Silver 4108 CPU @ 1.80GHz
  Binaries:
    Node: 12.22.9 - ~/.config/nvm/versions/node/v12.22.9/bin/node
    npm: 6.14.16 - ~/projects/gravity/ui-components/packages/ui-components/node_modules/.bin/npm
  Browsers:
    Chrome: 97.0.4692.99
    Firefox: 96.0
  npmPackages:
    @storybook/addon-actions: 6.4.18 => 6.4.18 
    @storybook/addon-essentials: 6.4.18 => 6.4.18 
    @storybook/addon-knobs: ^6.3.1 => 6.4.0 
    @storybook/addon-links: 6.4.18 => 6.4.18 
    @storybook/react: 6.4.18 => 6.4.18

**Comment by totszwai** [comment]
Knock knock? Still there in `6.4.19`

**Comment by evont** [comment]
Same here, any idea now?

**Comment by totszwai** [comment]
Is there a workaround on this issue?

**Comment by shilman** [comment]
Do you a have a reproduction repo you can share? If not, can you create one? See [how to create a repro](https://storybook.js.org/docs/react/contribute/how-to-reproduce). Thank you! 🙏

**Comment by totszwai** [comment]
@shilman this is literally #9832 which was never fixed and was closed @lgraziani2712 for no reason. These a reproduction repo there.

**Comment by shilman** [comment]
@totszwai there is no repo there, just a code snippet. the issue was closed because @lgraziani2712 said switching to `react-docgen` fixed it for him. what am i missing?

**Comment by benmcginnis** [comment]
This also is happening for me in storybook 7 using this setup:

``` ts
import { StorybookConfig } from "@storybook/react-vite";

const config: StorybookConfig = {
  stories: ["../src/**/*.mdx", "../src/**/*.stories.@(js|jsx|mjs|ts|tsx)"],
  core: {
    builder: "@storybook/builder-vite",
  },
  addons: [
    "@storybook/addon-a11y",
    "@storybook/addon-coverage",
    "@storybook/addon-essentials",
    "@storybook/addon-interactions",
    "@storybook/addon-links",
    "@storybook/addon-designs",
  ],
  framework: {
    name: "@storybook/react-vite",
    options: {},
  },
  staticDirs: ["./static"],
  docs: {
    autodocs: "tag",  // turning on autodocs is what adds displayName and __docGenInfo to my stories
  },
  features: {},
};
export default config;
```

**Comment by xander-marjoram** [comment]
In case anyone else comes across this issue and is having similar problems to me (`__docgenInfo` is null), I noticed that I wasn't using `@storybook/addon-docs` or `@storybook/addon-essentials`. Installing the docs addon fixed the error.
