### ISSUE TITLE
Addon-interactions: Not reporting all fields

### ISSUE THREAD

**Issue by bodograumann** [storybookjs/storybook#17400]
**Describe the bug**
When using an assertion in a play function of the form
```
expect(args.onInput).toHaveBeenCalledWith({
  foo: 42,
  bar: 99,
});
```

The output in the ui only contains the first field `foo`. E.g. it reads
> expect(action(onInput)).toHaveBeenCalledWith({  foo: 42 })

**To Reproduce**
Will have to see when I have time to do a reproduction.

**System**
```
Environment Info:

  System:
    OS: Linux 5.16 Arch Linux
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
  Binaries:
    Node: 17.3.0 - ~/.asdf/shims/node
    Yarn: 1.22.17 - /usr/bin/yarn
    npm: 8.3.2 - ~/.asdf/shims/npm
  Browsers:
    Firefox: 96.0.3
  npmPackages:
    @storybook/addon-docs: ^6.4.12 => 6.4.17 
    @storybook/addon-essentials: ^6.4.12 => 6.4.17 
    @storybook/addon-interactions: ^6.4.12 => 6.4.17 
    @storybook/jest: ^0.0.5 => 0.0.5 
    @storybook/testing-library: ^0.0.8 => 0.0.8 
    @storybook/vue3: ^6.4.12 => 6.4.17 
```

**Comment by bodograumann** [comment]
An example can be found here: https://github.com/bodograumann/storybook-play-called-with

When only having one field in the object it is displayed ok and when having three or more fields, only the first field is displayed while all others are hidden with ellipsis and the count is displayed correctly. Only when there are exactly two fields in the object, the displayed value is incorrect.

**Comment by shilman** [comment]
Hurrah!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-alpha.64 containing PR #17649 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by yannbf** [comment]
Hey @bodograumann thanks for opening this issue! We ended up improving the addon interactions to provide an object inspector of which you can visualize the entire object if you want to. However this is just visible in case of errors. 

The text for the interaction remains the same and the rationale is that as long as the interactions are passing, the users might not care that much about the object shape, but they will definitely care in case there are failures, so even though the interaction text will look like this:

<img width="1379" alt="image" src="https://user-images.githubusercontent.com/1671563/164012026-f1f3ba2b-0620-4c0f-b1f1-ce050b6f4a07.png">

You will get an inspector like this:

![](https://user-images.githubusercontent.com/1671563/163226512-5b2f263c-9b6d-4d54-8089-0d34f0b07b46.gif)
