### ISSUE TITLE
Links Addon | linkTo didn't handle second parameter as expected with UpperCamelCase

### ISSUE THREAD

**Issue by vaxul** [storybookjs/storybook#17414]
**Describe the bug**
The second parameter of the linkTo()-function within the Links Addon didn't handle UpperCamelCase as expected.

**To Reproduce**
Tested within the default example Header component of Storybook:
```tsx
import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';

import { Header } from './Header';
import { linkTo } from "@storybook/addon-links";

export default {
  title: 'Header',
  component: Header,
} as ComponentMeta<typeof Header>;

const Template: ComponentStory<typeof Header> = (args) => <Header {...args} />;

export const LoggedIn = Template.bind({});
LoggedIn.args = {
  user: {},
  onLogout: linkTo('Header', 'LoggedOut'), // <= Don't work - 'Logged Out' will do
};

export const LoggedOut = Template.bind({});
LoggedOut.args = {
  onLogin: linkTo('Header', 'Logged In'), // <= Do work
};

```

The example exports are `LoggedIn` and `LoggedOut`. If I put them into the second parameter it will not work. As workaround I have to add a Space between the words, so the linkTo generates a minus (-) within the URLs.

**System**
```
  System:
    OS: Windows 10 10.0.19043
    CPU: (16) x64 Intel(R) Core(TM) i9-10885H CPU @ 2.40GHz
  Binaries:
    Node: 12.19.0 - ~\nvm\nodejs\bin\node.EXE
    Yarn: 1.22.17 - ~\nvm\nodejs\bin\yarn.CMD
    npm: 6.14.8 - ~\nvm\nodejs\bin\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (97.0.1072.76)
  npmPackages:
    @storybook/addon-a11y: ^6.4.18 => 6.4.18
    @storybook/addon-actions: ^6.4.18 => 6.4.18
    @storybook/addon-essentials: ^6.4.18 => 6.4.18
    @storybook/addon-links: ^6.4.18 => 6.4.18
    @storybook/builder-webpack5: ^6.4.18 => 6.4.18
    @storybook/manager-webpack5: ^6.4.18 => 6.4.18
    @storybook/node-logger: ^6.4.18 => 6.4.18
    @storybook/preset-create-react-app: ^4.0.0 => 4.0.0
    @storybook/react: ^6.4.18 => 6.4.18
```

**Additional context**
The docs says:
> Second (optional) parameter is the story name (what you named with exported name)

In this case the second parameter must not be the exact exported name.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
