### ISSUE TITLE
"Unexpected default export without title" using Svelte CSF format

### ISSUE THREAD

**Issue by pzuraq** [storybookjs/storybook#17427]
**Describe the bug**

After updating to the latest Storybook and `storybook-builder-vite`, none of my stories are detected, and all log something like the following:

```
Unexpected default export without title in './src/lib/components/Auth.stories.svelte': undefined
```

Every story has a title set explicitly with the `<Meta>` tag from `addon-svelte-csf`. `addon-svelte-csf` has not updated recently, so the bug is unrelated.

**To Reproduce**
TODO, don't have time today but will do this as soon as I can

**System**

  System:
    OS: macOS 11.3.1
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 16.13.1 - ~/.volta/tools/image/node/16.13.1/bin/node
    Yarn: 1.22.11 - ~/.volta/tools/image/yarn/1.22.11/bin/yarn
    npm: 8.1.2 - ~/.volta/tools/image/node/16.13.1/bin/npm
  Browsers:
    Chrome: 98.0.4758.80
    Firefox: 96.0.2
    Safari: 14.1

**Additional context**
Also fails this way on CI so does not appear to be machine specific

**Comment by shilman** [comment]
Please file Vite-related issues in https://github.com/eirslett/storybook-builder-vite/

Closing this for now--please let me know if you think this ISN'T Vite-related and I'll reopen. Thank you! 🙏
