### ISSUE TITLE
Interactions: React hooks explodes with a11y

### ISSUE THREAD

**Issue by matheo** [storybookjs/storybook#17428]
**Describe the bug**

Today I've tried to install `@storybook/addon-interactions` (refreshing my whole lock file so I'm sure that my dependencies are aligned and ok) and then adding it to the `addons` array thrown a runtime exception:

![image](https://user-images.githubusercontent.com/260185/152619572-cfc67c96-e068-4b76-bd64-d95e986edbfb.png)

Then I've tried removing all the configured addons and leaving the basic ones to get storybook running without build exceptions, and I've found that something trycky is happening in `addons-a11y` because the if I remove it I get storybook running, and the exception points to its bundle:

![image](https://user-images.githubusercontent.com/260185/152619930-57f041f7-c303-45b6-9a7a-3137a6a44d1d.png)

Also, I had to comment out some addons that seems to include the `addon-a11y` package in some way and throw the runtime exception back, like `addon-actions` and `storybook-addon-designs` :thinking: 

My final addons list to run storybook successfully is:
```
  addons: [
    // '@storybook/addon-actions',
    '@storybook/addon-docs',
    '@storybook/addon-backgrounds',
    '@storybook/addon-viewport',
    '@storybook/addon-toolbars',
    '@storybook/addon-measure',
    '@storybook/addon-outline',
    // '@storybook/addon-a11y',
    '@storybook/addon-interactions',
    // 'storybook-addon-designs',
    // 'storybook-addon-angular-ivy',
  ],
```
ignoring this warning:
```
WARN Expected '@storybook/addon-actions' (or '@storybook/addon-essentials') to be listed before '@storybook/addon-interactions' in main Storybook config.
```

I'd like to know if there's something I can do to have all of them working armoniously.
I've tried upgrading `react` to `v17` (`@storybook/angular` has `v16.14.0`) as dependency, but I got the same issue.

**System**
```
System:
    OS: Linux 5.4 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 14.18.2 - ~/.nvm/versions/node/v14.18.2/bin/node
    Yarn: 1.22.17 - /usr/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.2/bin/npm
  Browsers:
    Chrome: 98.0.4758.80
    Firefox: 96.0
  npmPackages:
    @storybook/addon-a11y: ~6.4.0 => 6.4.18 
    @storybook/addon-essentials: ~6.4.0 => 6.4.18 
    @storybook/addon-interactions: ~6.4.0 => 6.4.18 
    @storybook/angular: ~6.4.0 => 6.4.18 
    @storybook/builder-webpack5: ~6.4.0 => 6.4.18 
    @storybook/manager-webpack5: ~6.4.0 => 6.4.18 
    @storybook/testing-library: 0.0.9 => 0.0.9
```

**Additional context**
```
I'm using `@nrwl/nx: 13.1.4`
```

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
