### ISSUE TITLE
With defaultValue being deprecated can you add a value field to table for display purposes?

### ISSUE THREAD

**Issue by JoshBowdenConcepts** [storybookjs/storybook#17438]
I noticed that default value is being deprecated which I assume is to show the native functionality of the code. I like this in practice but when I want to display something to my users for a field that is required but has no default then I have an issue. Ideally there should be some way to assume the input of the user as a test so that they can see a fully rendered component with example information.

**Comment by shilman** [comment]
Yes, you can document this with the `table.defaultValue` property

https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#no-longer-inferring-default-values-of-args

**Comment by JoshBowdenConcepts** [comment]
That doesn't render the default value that you set in the canvas though. Also from a UX perspective that looks like what the component natively sets. If anything that should either render in the canvas or be reversed in the table itself to make sense to the user.
