### ISSUE TITLE
Storybook adding webpack 4 (and other older dependencies) on a webpack 5 install.

### ISSUE THREAD

**Issue by SnakeSVx** [storybookjs/storybook#17436]
**Describe the bug**

Storybook seems to be added webpack 4 as dependency even though webpack 5 is being used.

npm install warnings: 

- npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
- npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

![image](https://user-images.githubusercontent.com/271542/152745608-4a19a127-91b5-489b-b785-d0466c26f63b.png)
![image](https://user-images.githubusercontent.com/271542/152745685-58d6bf48-7a9a-4c46-8f3d-9215fa31b5f2.png)

**To Reproduce**

Latest nx version workspace with  storybook installed. 

![image](https://user-images.githubusercontent.com/271542/152745832-3aa752b3-e3f8-4aff-ba53-e10cff53a6fd.png)

**System**
Please paste the results of `npx sb@next info` here.

**Additional context**

Remove the webpack 4 dependency or make it optional. So that you can either pick webpack 4 or webpack 5.

**Comment by shilman** [comment]
@SnakeSVx this is planned for 7.0 since it's a breaking change. we've also started prebundling some of our dependencies to avoid conflicts with user dependencies, and this change will hopefully make it into 6.5.

**Comment by BenRacicot** [comment]
Just to clarify, Storybook is not compatible with Angular 13+ until V7?

**Comment by shilman** [comment]
@BenRacicot storybook is compatible with Angular 13

**Comment by SnakeSVx** [comment]
> @SnakeSVx this is planned for 7.0 since it's a breaking change. we've also started prebundling some of our dependencies to avoid conflicts with user dependencies, and this change will hopefully make it into 6.5.

After upgrading to npm 8 there is a workaround that can be done for this as well by forcing the webpack version. This prevents the old webpack and it's dependencies to be added to the node_modules. (cleans up about 200 dependencies).

**Comment by BenRacicot** [comment]
@shilman thanks for responding. Is there a demo project available to reference? I've ran through all the docs and have errors everywhere when adding SB to my project.

**Comment by BenRacicot** [comment]
@shilman I don't want to hijack this issue but no it's still not clear. That demo has no angular.json file so not sure what purpose that project serves. Perhaps the answer is there but I can't see it.

Looking at [storybook.js.org/docs/angular/get-started/install](https://storybook.js.org/docs/angular/get-started/install) it seems there is an issue with the instructions. 

`npx storybook init` installs SB into your projects root. I don't think this is what the author is saying to do but please correct me.

Further down the page it seems to be saying that SB must be installed in its own Angular workspace? If so maybe the docs can be updated to explain that SB cannot be simply added to your project with `npx storybook init`?

**Comment by shilman** [comment]
@BenRacicot there's an angular.json file right here https://github.com/storybookjs/repro-templates/blob/next/angular/angular.json

**Comment by BenRacicot** [comment]
My apologies, yes that exists, but it does not match the docs instructions.
