### ISSUE TITLE
How to define a storybook framework?

### ISSUE THREAD

**Issue by melishev** [storybookjs/storybook#17432]
### Discussed in https://github.com/storybookjs/storybook/discussions/17431

<div type='discussions-op-text'>

<sup>Originally posted by **melishev** February  6, 2022</sup>
I have a repository that has both react and vue installed. When I run start-storybook -c .storybook-vue the console gives me the following message:
![Снимок экрана 2022-02-06 в 20 26 01](https://user-images.githubusercontent.com/58311421/152693062-4ceae4d7-353e-48a5-ae4e-5a6ab2c4632d.png)
In this example, I'm starting a Storybook and passing it the configuration for a Vue3 project.

When I try to run the same command on the React config, it gives me the same message that "@storybook/react" was run - and that's the **problem**.
My project has "@storybook/vue3" and "@storybook/react" installed at the same time. Most likely the Storybook is trying to guess which framework I'm using.

How can I specify start-storybook or anywhere so that it uses the framework I need?
</div>

**Comment by Tim-arts** [comment]
https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#story-store-v7

**Comment by ndelangen** [comment]
This should be fixed in 7.0 beta.

The storybook bins have been separated into a `@storybook/cli` package, which read the main.js files where the framework is defined.
