### ISSUE TITLE
Can't open storybook in IE11 when using webpack5

### ISSUE THREAD

**Issue by jhrinoa** [storybookjs/storybook#17459]
**Describe the bug**
Storybook with webpack5 doesn't work in IE11

**To Reproduce**
I created https://github.com/jhrinoa/sb-repro using `npx sb@next repro`.
I only updated browserslist for development to include IE11.
After cloning my repo, just do `yarn storybook` and open storybook using IE11.

**System**
Environment Info:

  System:
    OS: macOS 11.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 3.1.1 - /usr/local/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
  Browsers:
    Chrome: 98.0.4758.80
    Firefox: 96.0.3
    Safari: 15.0
  npmPackages:
    @storybook/addon-actions: ^6.5.0-alpha.38 => 6.5.0-alpha.38 
    @storybook/addon-docs: ^6.5.0-alpha.38 => 6.5.0-alpha.38 
    @storybook/addon-essentials: ^6.5.0-alpha.38 => 6.5.0-alpha.38 
    @storybook/addon-interactions: ^6.5.0-alpha.38 => 6.5.0-alpha.38 
    @storybook/addon-links: ^6.5.0-alpha.38 => 6.5.0-alpha.38 
    @storybook/builder-webpack5: ^6.5.0-alpha.38 => 6.5.0-alpha.38 
    @storybook/manager-webpack5: ^6.5.0-alpha.38 => 6.5.0-alpha.38 
    @storybook/node-logger: ^6.5.0-alpha.38 => 6.5.0-alpha.38 
    @storybook/preset-create-react-app: ^4.0.0 => 4.0.0 
    @storybook/react: ^6.5.0-alpha.38 => 6.5.0-alpha.38 
    @storybook/testing-library: ^0.0.9 => 0.0.9 

**Additional context**
IE11 fails because manager bundle is still using arrow function. It didn't get transpiled to ES5. 
iframe bundle gets transpiled to support ES5 but manager bundle doesn't.

![Screen Shot 2022-02-09 at 10 33 37 AM](https://user-images.githubusercontent.com/6693932/153289209-d9292462-e7e8-472d-87d8-e08351d94c59.png)
![Screen Shot 2022-02-09 at 10 34 20 AM](https://user-images.githubusercontent.com/6693932/153289216-dadf573a-a456-456f-b092-bda7e3bb0115.png)

I tried using webpack.config and added "target: ['web', 'es5']" as mentioned here (https://webpack.js.org/migrate/5/#need-to-support-an-older-browser-like-ie-11),
but still no luck. This setting only works for iframe bundle as well. (I checked the config using --debug-webpack option when running storybook)
I think this is because builder-webpack5 and manager-webpack5 works different way.

**Comment by burhanuday** [comment]
This might have to do with the browserslist config. From their docs, when not set in package json, it results in
```
defaults: Browserslist’s default browsers (> 0.5%, last 2 versions, Firefox ESR, not dead).
```
This might be why IE 11 is not supported

We can counteract it by setting the `targets` property in the webpack config for the manager to
```
target: ['web', 'es5']
```
as suggested by the author

@shilman what is your take on this? are we looking to support IE 11 at all? Or is it possible for the consumer to configure manager's webpack?

**Comment by shilman** [comment]
@burhanuday Ideally we support IE11 in Storybook 6.x. We'll most likely drop support in 7.0.

**Comment by ndelangen** [comment]
Storybook 7.0 won't support IE11 anymore.

6.5 won't receive updates other than critical security issues, this won't get fixed.
