### ISSUE TITLE
Storybook 6.4.18 + Angular 11.2.18, unable to update component attributes in ngOnChanges

### ISSUE THREAD

**Issue by akhileshThapliyal** [storybookjs/storybook#17492]
### **Describe the bug**
Unable to set/update component attributes in ngOnChanges

### **To Reproduce**
The complete source code and story sample are deployed on chromatic.
**Repro repository**
https://github.com/akhileshThapliyal/storybook-playground/blob/storybook-6.4.18/src/stories/button.component.ts
**Deployed bug story on chromatic**
https://62075591ca459c003a9554cc-qlexhzbypu.chromatic.com/?path=/story/example-button--primary

### **System**
Environment Info:
  System:
    OS: macOS 11.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Binaries:
    Node: 14.15.0 - /usr/local/bin/node
    npm: 6.14.8 - /usr/local/bin/npm
  Browsers:
    Chrome: 98.0.4758.80
    Safari: 14.1.1
  npmPackages:
    @storybook/addon-actions: ^6.4.18 => 6.4.18 
    @storybook/addon-essentials: ^6.4.18 => 6.4.18 
    @storybook/addon-links: ^6.4.18 => 6.4.18 
    @storybook/angular: ^6.4.18 => 6.4.18

### **Additional context**
In my application, there are many logical handling for CSS and show hide elements in ngOnChanges to update the Html attributes such as class, custom directives, style attributes etc.. Refer to the button component example in the git hub and chromatic. In spite of altering the component attributes and triggering Change detection on OnChanges the updated values are not reflected in the UI. For Instance, when we change the size attribute controls neither label2 nor labelClass is updated.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
