### ISSUE TITLE
Uncaught Error: Singleton client API not yet initialized, cannot call `addArgTypesEnhancer`. with 6.5.0-alpha.39

### ISSUE THREAD

**Issue by francoisromain** [storybookjs/storybook#17504]
**Describe the bug**
When I updated to stroybook v.6.5.0-alpha.39 and run `npm run stroybook`, there is this error: 

```
Uncaught Error: Singleton client API not yet initialized, cannot call `addArgTypesEnhancer`.
```

**System**
Please paste the results of `npx sb@next info` here.

```
  System:
    OS: Linux 5.13 Ubuntu 21.10 21.10 (Impish Indri)
    CPU: (8) x64 Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz
  Binaries:
    Node: 17.5.0 - /usr/bin/node
    Yarn: 1.22.17 - /usr/bin/yarn
    npm: 8.4.1 - /usr/bin/npm
  Browsers:
    Firefox: 96.0
  npmPackages:
    @storybook/addon-actions: ^6.5.0-alpha.39 => 6.5.0-alpha.39 
    @storybook/addon-docs: ^6.5.0-alpha.39 => 6.5.0-alpha.39 
    @storybook/addon-essentials: ^6.5.0-alpha.39 => 6.5.0-alpha.39 
    @storybook/addon-links: ^6.5.0-alpha.39 => 6.5.0-alpha.39 
    @storybook/addon-svelte-csf: ^1.1.0 => 1.1.0 
    @storybook/svelte: ^6.5.0-alpha.39 => 6.5.0-alpha.39 
```

**Comment by geisterfurz007** [comment]
Hitting the same thing after upgrading from 6.3.12 to 6.4.19. My understanding is that this is caused by multiple `@storybook/client-api` instances in the node_modules directory however going back to a working state I found that this was the case in both the working as well as the broken state. I have `node_modules/@storybook/client-api` as well as `node_modules/@storybook/preact/node_modules/@storybook/client-api` and no idea why the packages of the preact package aren't hoisted.

Before I go down that rabbit hole any further, could someone confirm that this is indeed the culprit (in that case I would be curious why it worked with 6.3.12 before)?

**Comment by jaminellis** [comment]
I have had the same thing here. Let me know if you workout what is interfering. I have my suspicious it is addon-storyshots

**Comment by francoisromain** [comment]
I updated storybook and don't have the problem anymore : 
```
Environment Info:

  System:
    OS: Linux 5.13 Ubuntu 21.10 21.10 (Impish Indri)
    CPU: (8) x64 Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz
  Binaries:
    Node: 17.7.0 - /usr/bin/node
    Yarn: 1.22.17 - /usr/bin/yarn
    npm: 8.5.3 - /media/fr/fr-work/Sites/dora/dora-front/node_modules/.bin/npm
  Browsers:
    Firefox: 97.0.2
  npmPackages:
    @storybook/addon-docs: ^6.5.0-alpha.46 => 6.5.0-alpha.46 
    @storybook/addon-essentials: ^6.5.0-alpha.46 => 6.5.0-alpha.46 
    @storybook/addon-links: ^6.5.0-alpha.46 => 6.5.0-alpha.46 
    @storybook/addon-svelte-csf: ^1.1.0 => 1.1.0 
    @storybook/svelte: ^6.5.0-alpha.46 => 6.5.0-alpha.46
```

```
"storybook-builder-vite": "^0.1.18",
```

and my `./storybook/main.cjs` file. : 
look at the 
```
const preprocess = require("svelte-preprocess");

module.exports = {
  stories: [
    "../src/**/*.stories.mdx",
    "../src/**/*.stories.@(js|jsx|ts|tsx|svelte)",
  ],
  addons: ["@storybook/addon-essentials", "@storybook/addon-links"],
  framework: "@storybook/svelte",
  core: {
    builder: "storybook-builder-vite",
  },
  staticDirs: ["../static"],
  svelteOptions: {
    preprocess: [preprocess({ postcss: true, sourceMap: true })],
  },

  async viteFinal(config, { configType }) {
    // github.com/storybookjs/storybook/discussions/17433
    // BASE_URL est définie dans `.github/workflows/storybook.yml`
    const baseUrl = process.env.BASE_URL;

    if (baseUrl) {
      config.base = `${baseUrl}/`;
    }

    // `Uncaught Error: Singleton client API not yet initialized, cannot call addParameters`
    // github.com/storybookjs/storybook/issues/10887#issuecomment-901109891
    config.resolve.dedupe = ["@storybook/client-api"];

    return config;
  },
};
```

**Comment by IanVS** [comment]
Thanks for reporting back!

**Comment by geisterfurz007** [comment]
Figured I would report back as well; I am not using vite but after starting from scratch again, I cannot reproduce this anymore either. This attempt I haven't tried to move to webpack 5 though, which *may* have been an issue before considering this appears to have been solved for vite with a dedupe option. If I move on from webpack 4, I will probably try to jump straight to vite though so hopefully I won't see this again!

Thanks for the vite-fix!

**Comment by gwvt** [comment]
I just migrated from storybook-builder-vite 0.1.23 to @storybook/builder-vite 0.1.28 and got this error. (Tried removing `node_modules` and `package-lock.json` and reinstalling dependencies but no luck.)

**Comment by IanVS** [comment]
@gwvt are you able to create a reproduction that I can take a look at?  That would be super-helpful, since you've already ruled out a stale cache / version mismatch problem.

**Comment by gwvt** [comment]
Thanks @IanVS ! Shell output looks normal...
<img width="849" alt="Screen Shot 2022-04-13 at 4 27 13 PM" src="https://user-images.githubusercontent.com/17604801/163264820-addff268-2fd2-4214-b946-e365eb8cccda.png">
But the page load hangs...
<img width="1031" alt="Screen Shot 2022-04-13 at 4 25 49 PM" src="https://user-images.githubusercontent.com/17604801/163264926-8e84d42d-4c52-44b3-9480-856450f7496a.png">
With this error in the console...
<img width="400" alt="Screen Shot 2022-04-13 at 4 26 13 PM" src="https://user-images.githubusercontent.com/17604801/163264985-db48bf42-778a-4ee1-baab-ab27c6976b1b.png">
Please let me know if I can provide anything further.

**Comment by IanVS** [comment]
Hi thanks, yes if you're able to either share a link to the repository where this is occurring (if it is open source) or create a new repository and get it into this same state, that's going to be the best way for me to dig into this.

**Comment by thadeucity** [comment]
@IanVS 

I'm having the same issue, and managed to duplicate it at https://github.com/thadeucity/storybook-vite-bug

**Comment by thadeucity** [comment]
@IanVS 

Following these steps I was able to run the Storybook itself, but I got errors loading the components

 ```bash
 // Setup a project
yarn init

// Add Vite
yarn add -D vite

// Setting up the storybook (Selected - y -> react)
npx sb@next init --builder storybook-builder-vite

// Installing React
yarn add -D react react-dom

// Trying to run storybook
yarn storybook
 ```
 
 storybook ends up in an endless loop (missing global), so I created the file:
 
 ```js
// .storybook\preview-head.html

<script>
  // Fix: add `jest` to global
  window.global = window;
</script>
 ```
 
 Now storybook runs, but when I try to open any of the sample components I get the error: 
 `TypeError: reactDomClient.createRoot is not a function`

**Comment by IanVS** [comment]
`TypeError: reactDomClient.createRoot is not a function` happens when there's a mismatch somewhere between react 18 and a version less than that.  

It looks like you're using the older `storybook-builder-vite` command, so you won't have the fix.  Try leaving off the `--builder`, it'll be set automatically.  Or, use `--builder @storybook/builder-vite`.

**Comment by thadeucity** [comment]
Tried as suggested but I'm receiving the same error

```
yarn init
yarn add -D vite react react-dom
npx sb@next init --builder @storybook/builder-vite

yarn storybook
```

```json
//package.json


{
  "name": "vite-storybook",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "devDependencies": {
    "@babel/core": "^7.17.9",
    "@storybook/addon-actions": "^6.5.0-alpha.62",
    "@storybook/addon-essentials": "^6.5.0-alpha.62",
    "@storybook/addon-interactions": "^6.5.0-alpha.62",
    "@storybook/addon-links": "^6.5.0-alpha.62",
    "@storybook/builder-vite": "^0.1.28",
    "@storybook/react": "^6.5.0-alpha.62",
    "@storybook/testing-library": "^0.0.9",
    "babel-loader": "^8.2.4",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "vite": "^2.9.4"
  },
  "dependencies": {},
  "scripts": {
    "storybook": "start-storybook -p 6006",
    "build-storybook": "build-storybook"
  }
}
```

**Comment by IanVS** [comment]
Thanks for the reproduction, @thadeucity.  Using it, I've traced this down to 6.4 not including a fix that is in the 6.5 alphas: https://github.com/storybookjs/storybook/pull/17875.

One workaround you can use for now, is to enable `storyStoreV7`, which won't have this problem, and honestly is better to use anyway.  One other thing I noticed is that your story is named `Button.story.tsx`, which won't match the glob you have set up in `main.js`.

**Comment by IanVS** [comment]
@gwvt @thadeucity, can you please try upgrading to storybook 6.4.22?  (`npx sb@next upgrade`).  It does the trick in the reproduction, so I think you should be good to go now.  Let me know if you still have any trouble.

**Comment by IanVS** [comment]
Oh, and to create a new project, instead of manually installing vite and react separately as you show above, you can use:

```
 npm create vite@latest
```

Then, follow the prompts, and when done, you can

```
npx sb@next init
```

Which should get you up-and-running with a 6.5.0-alpha (or beta soon) version of storybook.

**Comment by thadeucity** [comment]
Thank you for your help @IanVS

For the sample project just updating the dependencies with `npx sb@next upgrade` worked for me! Thank you!!

But, for creating a new project I'm getting the same error I listed before (`TypeError: reactDomClient.createRoot is not a function`)

```
npm create vite@latest

// Project-name: vite-project
// Select a framework: react
// Select a variant: react-ts
```

```
npx sb@next init
```

```
yarn install
```

```
yarn storybook
```

I was able to solve the error downgrading storybook from `6.5.0-alpha.63` to `6.4.22` I seems that 6.5.0-alpha.60 or higher doesn't have the react 18 fix

Thank you again for the help

**Comment by thadeucity** [comment]
Updated the bug repo with the bug described above:
https://github.com/thadeucity/storybook-vite-bug

**Comment by gwvt** [comment]
@IanVS `npx sb@next upgrade` works! Thank you very much for your help.

**Comment by IanVS** [comment]
@thadeucity thanks for reporting the error.  I have a PR up which should fix it. https://github.com/storybookjs/storybook/pull/17987

**Comment by joungskim** [comment]
I'm not sure if this will help anyone, but I spent a day with this exact same issue.  I believe if you are on a Windows machine the case sensitivity of the path in your command prompt/command shell matters.  This caused the issue where the casing was mismatched and gave me this error.  When I went back and tabbed through each of the folders within the path it fixed the issue.

**Comment by RodneyReid** [comment]
Thanks @joungskim - that worked!   And yes, I was tearing my hair out all day with this issue (it's 11pm here and just got it working)
