### ISSUE TITLE
titlePrefix usage without auto titles

### ISSUE THREAD

**Issue by pascalduez** [storybookjs/storybook#17508]
**Describe the bug**
I'm trying to use stories configuration objects and the `titlePrefix` key. 
I would have expected that it could be prepended to any story title and in such able to create a root grouping item in navigation, without the need to manually add that prefix to every stories (doesn't scale). 

For instance with this config:
```js
 stories: [
    {
      directory: '../Foo',
      titlePrefix: 'Foo',
      files: '**/*.stories.*',
    },
    {
      directory: '../Bar',
      titlePrefix: 'Bar',
      files: '**/*.stories.*',
    },
  ],
```
And two stories as such:
```js
// ./Foo/Button.stories.js
export default {
  title: 'Button',
};
export const Button = () => <p>Foo/Button</p>;

// ./Bar/Switch.stories.js
export default {
  title: 'Switch',
};

export const Switch = () => <p>Bar/Switch</p>;
```
I have the following result:
![Screenshot from 2022-02-15 11-19-16](https://user-images.githubusercontent.com/335467/154041847-cd1a7b91-2bec-4647-99d8-66911a4a34d3.png)

Whereas I would expect:
![Screenshot from 2022-02-15 11-20-34](https://user-images.githubusercontent.com/335467/154042031-fd75b861-a337-4ca1-bb96-a8a33db4f7ab.png)

Which can be achieved by not providing a `title` in stories (auto titles), but that's not a viable option for me on a large component libraries and design system I need a bit more flexibility.

Is that the intended behaviour or is there any change to be able to do that?

**To Reproduce**
https://github.com/pascalduez/storybook-repro-titleprefix

**System**
```
Environment Info:

  System:
    OS: Linux
  Binaries:
    Node: 14.17.3 
    Yarn: 3.1.1
    npm: 6.14.13 
  Browsers:
    Firefox: 96.0
  npmPackages:
    @storybook/addon-actions: ^6.5.0-alpha.39 => 6.5.0-alpha.39 
    @storybook/addon-docs: ^6.5.0-alpha.39 => 6.5.0-alpha.39 
    @storybook/addon-essentials: ^6.5.0-alpha.39 => 6.5.0-alpha.39 
    @storybook/addon-interactions: ^6.5.0-alpha.39 => 6.5.0-alpha.39 
    @storybook/addon-links: ^6.5.0-alpha.39 => 6.5.0-alpha.39 
    @storybook/react: ^6.5.0-alpha.39 => 6.5.0-alpha.39 
    @storybook/testing-library: ^0.0.9 => 0.0.9 
```

**Comment by LucaCras** [comment]
Hi @shilman, I wouldn't mind picking this up today if that is okay? I have only one question, and that is where should I start looking (aka where is this functionality implemented)?

**Comment by shilman** [comment]
Hi @LucaCras it's implemented here

https://github.com/storybookjs/storybook/blob/next/lib/store/src/autoTitle.ts#L68

And you'll probably need to look at a couple places this is called in the codebase to see how the manually specified title is handled.

**Comment by shilman** [comment]
<img width="1046" alt="component-story-format_-_Discord" src="https://user-images.githubusercontent.com/488689/158206981-e74586fe-63cf-49f3-9dfd-7ad37e0e50ef.png">

**Comment by shilman** [comment]
w00t!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-beta.7 containing PR #17724 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
