### ISSUE TITLE
Controls not correctly set on initialisation (and change when clicking)

### ISSUE THREAD

**Issue by Hypenate** [storybookjs/storybook#17509]
**Describe the bug**
![2022-02-15_18-10-11](https://user-images.githubusercontent.com/7478681/154113911-8d462dce-e33b-41a0-a1f4-d399020e4aab.gif)

**To Reproduce**
```
declare type StoryArgs = GridLayoutComponent & { content: string, storyBookShowRightTop: boolean };

const argTypes = {
  showBackButton: {
    control: {
      type: 'boolean',
    },
  },
  showAddButton: {
    control: {
      type: 'boolean',
    },
  },
};

export default {
  id: 'TableLayout',
  title: 'Layout/Table',
  component:GridLayoutComponent,
  decorators: [
    moduleMetadata({
      imports: [RouterTestingModule, ButtonModule, ToolbarModule, GridLayoutModule],
    }),
  ],
  argTypes,
} as Meta<StoryArgs>;

const template: Story<StoryArgs> = ({ content, ...args }) => ({
  props: {
    ...args,
    content,
  },
  template: `
  <div *transloco="let t">
    <grid-layout [showBackButton]="showBackButton" [showAddButton]="showAddButton">
      ${content}
      <p>A table can be placed here</p>
    </grid-layout>
  </div>`,
});

/***********************************************************************************************************/

/** Default story */
export const defaultStory: Story<StoryArgs> = template.bind({});
defaultStory.parameters = {
  docs: {
    description: {
      story: 'Shows the component with all features.',
    },
  },
};
```

**System**
Using
"@nrwl/storybook": "13.8.1",
"@storybook/addon-essentials": "~6.4.19",
"@storybook/angular": "~6.4.19",
"@storybook/builder-webpack5": "~6.4.19",
"@storybook/manager-webpack5": "~6.4.19",

**Additional context**

**Comment by Hypenate** [comment]
Maybe related to #16865 ?

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
