### ISSUE TITLE
Add deprecation message to knobs Readme

### ISSUE THREAD

**Issue by scheinercc** [storybookjs/storybook#17506]
Add deprecation message to https://github.com/storybookjs/storybook/blob/master/addons/knobs/README.md, similar to https://classic.yarnpkg.com/en/package/@storybook/addon-knobs#readme

**Are you able to assist to bring the feature to reality?**
yes

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if this is still relevant in SB 7.x.
