### ISSUE TITLE
MDX webpack issue

### ISSUE THREAD

**Issue by eascan** [storybookjs/storybook#17502]
Attempting to write an MDX documentation file for a component, but receiving an error and can't find any similar issues online. This is the error I receive on storybook:
![Screenshot 2022-02-14 at 12 56 31](https://user-images.githubusercontent.com/72176254/153869281-ad11a4d5-3236-4f1f-8452-8c198b17b486.png)

To reproduce:
Just adding simple MDX from the docs:

![Screenshot 2022-02-14 at 13 01 46](https://user-images.githubusercontent.com/72176254/153869068-2ea58641-b08b-4ca0-9b3d-6dea3c4c6f5e.png)

Dependencies:
![Screenshot 2022-02-14 at 13 02 06](https://user-images.githubusercontent.com/72176254/153869110-bc29d8e1-dde1-4884-8d40-5023629fbc82.png)

Storybook main.js:
![Screenshot 2022-02-14 at 13 02 30](https://user-images.githubusercontent.com/72176254/153869169-97a0967c-26f0-4c87-8f1b-0ffcf41200ee.png)

Would anyone know what the issue is? I haven't found any similar issues/answers online so far.

**Comment by kulchenkod** [comment]
I too have this problem ((

**Comment by kulchenkod** [comment]
It worked for me to downgrade `@mdx-js/react to 1.6.22`

**Comment by shilman** [comment]
MDX2 has opt-in support in 6.5: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#opt-in-mdx2-support

To use it, upgrade to 6.5 and then follow the instructions in the MIGRATION doc above
```
npx sb upgrade --prerelease
```

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
