### ISSUE TITLE
Keyboard shortcuts getting reset and "Reset Viewport" hotkey doesn't work

### ISSUE THREAD

**Issue by EloB** [storybookjs/storybook#17519]
**Describe the bug**
There are 2 bugs with Keyboard shortcuts.
1. Every time you reload the browser it can't reload last shortcuts from localStorage. They are getting reset.
2. The default "Reset viewport" hotkey doesn't work on Mac.

**To Reproduce**
This is a super simple example. Just creating a CRA app and installing Storybook. Have the same issue in my big app as well and that is a Next.js app.
```bash
npx create-react-app my-app
cd my-app
npx sb init
npm run storybook

# Open any story canvas
open "http://localhost:6006/?path=/story/example-button--primary"

# Press "V" to change into any "Viewport".
# Press "Alt + V" to try to reset "Viewport".
```

**System**
```
Environment Info:

  System:
    OS: macOS 11.6.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.2/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
  Browsers:
    Chrome: 98.0.4758.102
    Safari: 15.3
  npmPackages:
    @storybook/addon-actions: ^6.4.19 => 6.4.19
    @storybook/addon-essentials: ^6.4.19 => 6.4.19
    @storybook/addon-interactions: ^6.4.19 => 6.4.19
    @storybook/addon-links: ^6.4.19 => 6.4.19
    @storybook/builder-webpack5: ^6.4.19 => 6.4.19
    @storybook/manager-webpack5: ^6.4.19 => 6.4.19
    @storybook/node-logger: ^6.4.19 => 6.4.19
    @storybook/preset-create-react-app: ^4.0.1 => 4.0.1
    @storybook/react: ^6.4.19 => 6.4.19
    @storybook/testing-library: ^0.0.9 => 0.0.9
```

**Comment by EloB** [comment]
I've tried Safari and Chrome. None worked. Also went into Application tab in Chrome devtool and reset everything. Still doesn't work.

![storybook-bug](https://user-images.githubusercontent.com/476567/154281584-d47f6eda-6456-45f5-accb-b88c77f13d37.gif)

**Comment by EloB** [comment]
Seems like it can't reload previous shortcuts and the shortcut for "Reset viewport" is kind of broken.

**Comment by EloB** [comment]
Might have something todo with keyboard layout too. I'm using Swedish keyboard layout.

**Comment by EloB** [comment]
## Event.key turns into some weird symbol when pressing option
Option (⌥) + "V" (OS X)
<img width="462" alt="image" src="https://user-images.githubusercontent.com/476567/154359545-3e7a8ea0-e80c-4353-91d8-4edad6d7ff92.png">

## Behaves the same
"V"
<img width="462" alt="image" src="https://user-images.githubusercontent.com/476567/154359113-d79a7ebe-cb13-431c-ab94-5f4deab27607.png">

Shift + "V"
<img width="462" alt="image" src="https://user-images.githubusercontent.com/476567/154359197-8bb5e2dc-4c90-4ab7-b55b-61517890a7eb.png">

Ctrl + "V"
<img width="462" alt="image" src="https://user-images.githubusercontent.com/476567/154359286-d1e31165-fc86-43d2-a475-c779b6f6b178.png">

Meta (⌘) + "V" (OS X)
<img width="462" alt="image" src="https://user-images.githubusercontent.com/476567/154359688-e5e06eb5-8fc5-4937-aeb9-ba4d2aad99fa.png">

**Comment by EloB** [comment]
Here is the problem. The `keys` array will be `["alt", "‹"]`. So trying to pressing `⌥ + V` won't his default hotkey.

https://github.com/storybookjs/storybook/blob/a8db9585f07d8cfc7354e68f6b780a6ff6536b38/lib/api/src/lib/shortcut.ts#L40

https://github.com/storybookjs/storybook/blob/a8db9585f07d8cfc7354e68f6b780a6ff6536b38/addons/viewport/src/shortcuts.ts#L50

**Comment by EloB** [comment]
Maybe use `.code` instead and use something like that `/^(?:Key|Digit)(.+)$/` to grab the character? Then maybe have a else statement on the other keys.

Keyboard layout is not stable.
https://developer.mozilla.org/en-US/docs/Web/API/Keyboard_API

**Comment by shilman** [comment]
Great Caesar's ghost!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.30 containing PR #20167 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
