### ISSUE TITLE
Args (controls) of enum/array type are not being passed to "open in new tab" (canvas in iframe)

### ISSUE THREAD

**Issue by toli444** [storybookjs/storybook#17517]
I get a lot of use out of opening a canvas in a new tab in my storybook for React app. However, I find that args are not passed to the component in the new tab if the component's prop-types are `PropTypes.oneOf`, `PropTypes.oneOfType`. According to docs, `argTypes` for Rect components can be generated from `docgen` info. For the component in which I see the problem:
* `__docgenInfo` looks like this: 
```js
"colour": {
  "type": {
    "name": "enum",
    "value": [{
      "value": "'orange'",
      "computed": false
    }, {
      "value": "'blue'",
      "computed": false
    }]
  },
  "required": false,
  "description": ""
},
```

* `PropTypes` looks like this:

```js
ColouredBox.propTypes = {
    colour: PropTypes.oneOf(['orange', 'blue', 'green', 'purple']),
};
```

* Story looks like this:
```js
export default {
    title: 'Atoms/ColouredBox',
    component: ColouredBox,
    parameters: { layout: 'centered' }
};

export const WithExampleProps = args => (
    <ColouredBox {...args} />
);

WithExampleProps.args = {
    colour: 'blue'
};
```

With all the above, `colour` prop is not applied on the component if it is opened in canvas in new tab.

If I change `PropTypes`: 
```diff
ColouredBox.propTypes = {
-    colour: PropTypes.oneOf(['orange', 'blue', 'green', 'purple']),
+    colour: PropTypes.string
};
```

Or directly replace `__docgenInfo` with:
```diff
"colour": {
  "type": {
-    "name": "enum",
-    "value": [{
-      "value": "'orange'",
-      "computed": false
-    }, {
-      "value": "'blue'",
-      "computed": false
-    }]
+    "name": "string"
  },
  "required": false,
  "description": ""
},
```

`Colour` prop applied as expected

It would be great to have `new tab` mode work with complex `argTypes` as it used to

**System**
everything worked fine on Storybook `v16.3.12`. The problem appeared after `v16.4.0` update (tested on `v16.4.19` as well).

**Additional Info**
Might be connected with https://github.com/storybookjs/storybook/issues/17413

**Comment by toli444** [comment]
any updates on this one?

**Comment by msDestiny14** [comment]
Hello there. Is there any update or ETA on this? :)

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
