### ISSUE TITLE
Addon-docs: MDX2 support

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#17514]
MDX has released version 2 with better parsing, improved speed, and security fixes. 

We should provide opt-in support for MDXv2 in SB6.5 and completely move to MDXv2 in SB7.0.

**Comment by shilman** [comment]
closing as dupe to #17137 17137

**Comment by shilman** [comment]
Olé!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-alpha.43 containing PR #17515 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

**Comment by shilman** [comment]
Short migration guide here https://gist.github.com/shilman/6ff2d7e18db8846e8fc552fb432ae4f6

**Comment by julrich** [comment]
> Hey gang! A lot of you have been waiting a long time for MDXv2. I've released experimental support in Storybook 6.5 and would love your help to kick the tires. I've written up a short guide here and will update it with the latest as it stabilizes:
> 
> https://gist.github.com/shilman/6ff2d7e18db8846e8fc552fb432ae4f6

This sounds great. Maybe the timing aligns, could really use that for documenting a major upcoming migration of our component library. Would love to use https://codehike.org/ for their great code sample components... but it's only MDXv2.
Will let you know if there's any feedback (not sure at what timeline you're looking at for feedback).
