### ISSUE TITLE
Invalid Version in Angular App

### ISSUE THREAD

**Issue by ajay312** [storybookjs/storybook#17521]
![153428267-79009539-f0d1-4fec-b823-261ab3d4173d](https://user-images.githubusercontent.com/4881209/154318822-9f85756c-5111-4d30-b2f1-11560a989369.jpg)
When I used Angular core packages with different versions in package.json .There is invalid version  error .Any restriction in package.json for versioning

**Comment by Stoffel-KT** [comment]
any updates on this?
I still seem to have the same issues as seem to have been reported 4 years ago
