### ISSUE TITLE
CSF3: Auto-title should respect file system capitalization

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#17538]
Hey @shilman, it's very cool that you added auto-generation of titles, but I think that it shouldn't modify parts of its path.

I've added config in my `main.js`:
```javascript
stories: [{ directory: "../src", files: "**/*.stories.*" }]
```

I have a story in the path: `src/pages/app/BuildScreen/components/ScreenList/components/ScreenListItem.stories.tsx`

And Storybook generates path like:
<img width="263" alt="image" src="https://user-images.githubusercontent.com/7023167/154029108-91a9bb8e-2e52-4c35-aff4-1b0f02c3e30d.png">

Instead of this, I would like it to generate path **without** capitalization and spacing so it would look like:
<img width="255" alt="image" src="https://user-images.githubusercontent.com/7023167/154030988-a66c14a2-38c9-4416-830d-b8a2ba26bc22.png">

Could you please change this behavior or add some flag to not modify parts of the output path?

_Originally posted by @dawidk92 in https://github.com/storybookjs/storybook/issues/15534#issuecomment-1040041210_

**Comment by shilman** [comment]
@tmeasday @yannbf This isn't the first time I've heard this criticism. I wouldn't add a flag to configure this, but I would consider making this a breaking change in 7.0. WDYT?

**Comment by elektronik2k5** [comment]
I'm in favor of this change as well. Rationale: if titles are meant to represent the filesystem path then they should reflect it without any transformations.

**Comment by tmeasday** [comment]
I agree with this change.

**Comment by dawidk92** [comment]
Also, another issue I have with the auto-title is that it unnecessarily repeats the component's name in the final path.

I have my stories in paths like:
```
components/
├─ atoms/
│  ├─ Image/
│  │  ├─ Image.stories.tsx
│  │  ├─ Image.tsx
│  │  ├─ index.ts
```

And auto-title generates paths like:
<img width="227" alt="Screenshot 2022-02-21 at 11 30 45" src="https://user-images.githubusercontent.com/7023167/154938817-6c4d6028-8683-4246-b3b9-a875ae0086c1.png">

I would like it to generate paths like:
<img width="226" alt="Screenshot 2022-02-21 at 11 28 02" src="https://user-images.githubusercontent.com/7023167/154938911-c076a38d-2855-41bc-8a65-f8f5c84581d8.png">

Maybe we could check if the story file has the same name as its directory and then don't print this name once again?

**Comment by shilman** [comment]
@dawidk92 the redundant filename issue has already been fixed in https://github.com/storybookjs/storybook/pull/17421

```
npx sb upgrade --prerelease
```

**Comment by shilman** [comment]
Leaning towards doing this in 6.5 since auto-title is an experimental feature and we can afford to make breaking changes here. The biggest impact is that story ID's will change unless we're careful. So `BigButton` would go from`big-button` to `bigbutton`. We could potentially do some monkeying in the code to preserve the IDs, but we can't change the IDs generated from manual ID's.

**Comment by tmeasday** [comment]
Hmmm, that is an issue. Thinking about it quickly I think trying to preserve the id would be quite tricky (we'd have to pass both an id and a title around where now we just pass a title). 

Also in 7.0 I think we'd definitely want to be consistent and map ids in the same way the would be if you had manually specified that title (ie `bigbutton`). 

So I would say either we do a breaking change (for ids) in 6.5 or we wait for 7.0 for the whole thing.

**Comment by shilman** [comment]
Gadzooks!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-alpha.45 containing PR #17574 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
