### ISSUE TITLE
This story is not configured to handle controls.

### ISSUE THREAD

**Issue by bhargavAtgithub** [storybookjs/storybook#17539]
Controls are missing for the styled component. I create two components. But the regular react component is getting controls, whereas the styled component is not getting any controls. 

<img width="693" alt="Screenshot 2022-02-20 at 12 20 56 AM" src="https://user-images.githubusercontent.com/39086949/154814894-cb01659b-e470-43c2-a00c-e104a0c71195.png">
<img width="701" alt="Screenshot 2022-02-20 at 12 21 17 AM" src="https://user-images.githubusercontent.com/39086949/154814896-2a5b03c8-1b85-4d17-9ff5-e9832754cb88.png">
<img width="555" alt="Screenshot 2022-02-20 at 12 21 49 AM" src="https://user-images.githubusercontent.com/39086949/154814898-585a6327-fb50-41b8-992d-e8c0e1a96049.png">
<img width="497" alt="Screenshot 2022-02-20 at 12 24 37 AM" src="https://user-images.githubusercontent.com/39086949/154814923-13f244d8-8976-4b61-acff-5cfafb061574.png">
<img width="674" alt="Screenshot 2022-02-20 at 12 25 05 AM" src="https://user-images.githubusercontent.com/39086949/154814958-64c88cd5-8f5d-4b0a-b3f3-ebb712aca343.png">
<img width="969" alt="Screenshot 2022-02-20 at 12 25 17 AM" src="https://user-images.githubusercontent.com/39086949/154814960-a82dbc1c-af21-422e-b6e5-10b4e4bb806d.png">
<img width="385" alt="Screenshot 2022-02-20 at 12 23 05 AM" src="https://user-images.githubusercontent.com/39086949/154814899-da3e6242-ae3d-41a7-9fb9-ed92d222046d.png">

Unable to find out the reason for this issue.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
