### ISSUE TITLE
ESLint is not actually running against anything

### ISSUE THREAD

**Issue by IanVS** [storybookjs/storybook#17542]
**Describe the bug**
I found that VS Code was reporting a linting failure in a storybook file, but running `yarn lint:js` did not.  Then I realized that my `.cache/eslint` file was way too small, and found that nothing is actually being linted.  😱 

**To Reproduce**
To verify, try running `yarn lint:js --debug`, and you'll see only something like this:

```
yarn lint:js --debug
  eslint:cli CLI args: [ '--cache', '--cache-location=.cache/eslint', '--ext', '.js,.jsx,.json,.html,.ts,.tsx,.mjs', '--report-unused-disable-directives', '--debug' ] +0ms
  eslint:cli Running on files +4ms
  eslintrc:config-array-factory Loading .eslintignore file: /Users/ianvs/code/storybook/storybook/.eslintignore +0ms
  eslintrc:ignore-pattern Create with: [ IgnorePattern { patterns: [ '/**/node_modules/*' ], basePath: '/Users/ianvs/code/storybook/storybook', loose: false } ] +0ms
  eslintrc:ignore-pattern   processed: { basePath: '/Users/ianvs/code/storybook/storybook', patterns: [ '/**/node_modules/*' ] } +1ms
  eslint:lint-result-cache Caching results to /Users/ianvs/code/storybook/storybook/.cache/eslint +0ms
  eslint:lint-result-cache Using "metadata" strategy to detect changes +0ms
  eslintrc:ignore-pattern Create with: [ IgnorePattern { patterns: [ '/**/node_modules/*' ], basePath: '/Users/ianvs/code/storybook/storybook', loose: false } ] +8ms
  eslintrc:ignore-pattern   processed: { basePath: '/Users/ianvs/code/storybook/storybook', patterns: [ '/**/node_modules/*' ] } +0ms
  eslint:file-enumerator Start to iterate files: [] +0ms
  eslint:file-enumerator Complete iterating files: [] +0ms
  eslint:lint-result-cache Persisting cached results: /Users/ianvs/code/storybook/storybook/.cache/eslint +7ms
  eslint:cli-engine Linting complete in: 0ms +0ms
```

Furthermore, if you delete `.cache/eslint`, it isn't even re-created, because nothing is being linted.  

**System**
Please paste the results of `npx sb@next info` here.

**Additional context**
I added a `.` to the command, like `cross-env NODE_ENV=production eslint . --cache -...`, and got this result:

```
✖ 716 problems (1 error, 715 warnings)
```

I can put up a PR a little later if nobody beats me to it, but actually fixing the warnings might take a fair bit of work.

**Comment by shilman** [comment]
w00t!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-alpha.47 containing PR #17545 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
