### ISSUE TITLE
Pre-bundle prettier to avoid conflicts with user versions

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#17553]
See https://github.com/storybookjs/storybook/pull/17550

**Comment by ShaunLloyd** [comment]
Thank you for adding that 🙏 👀

**Comment by kedarv** [comment]
hey @shilman - curious if you can outline the work required to make this happen so potentially external folks can pick it up. we're running into some large-ish issues depping storybook due to storybook requiring >=2.x prettier

**Comment by shilman** [comment]
Try upgrading to the latest prerelease:

```
npx sb@next upgrade --prerelease
```

@kedarv

**Comment by ndelangen** [comment]
Fixed in 7.0 beta
