### ISSUE TITLE
Stories stay "mounted" when not visible

### ISSUE THREAD

**Issue by Arjan-Zuidema** [storybookjs/storybook#17568]
**Describe the bug**
A story does not get hidden when in not in "Canvas" panel. 

**To Reproduce**
Render a component which has `position: fixed` style

**System**
System:
    OS: macOS 12.2.1
    CPU: (4) x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
  Binaries:
    Node: 16.12.0 - ~/.nvm/versions/node/v16.12.0/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.12.0/bin/npm
  Browsers:
    Chrome: 98.0.4758.109
    Firefox: 88.0.1
    Safari: 15.3
  npmPackages:
    @storybook/addon-actions: ^6.4.19 => 6.4.19 
    @storybook/addon-essentials: ^6.4.19 => 6.4.19 
    @storybook/addon-links: ^6.4.19 => 6.4.19 
    @storybook/addon-postcss: ^2.0.0 => 2.0.0 
    @storybook/builder-webpack5: ^6.4.19 => 6.4.19 
    @storybook/manager-webpack5: ^6.4.19 => 6.4.19 
    @storybook/react: ^6.4.19 => 6.4.19 

**Additional context**
This causes problems with stories that render `position: fixed` components. In our case: context menu's which are positioned using an x/y position.

<img width="1137" alt="image" src="https://user-images.githubusercontent.com/30040390/155501035-8f41d821-dae9-4a4d-bf42-adbbfa2bdc73.png">

**Comment by yannbf** [comment]
Hey @Arjan-Zuidema, this is a known limitation of docs because the elements are inline rendered so they will share the same parent container.

You can use iframe stories instead: https://github.com/storybookjs/storybook/blob/next/docs/writing-docs/docs-page.md#inline-stories-vs-iframe-stories

**Comment by Arjan-Zuidema** [comment]
Alright, that seems like an ok workaround for our problem. Why is it not the default anyway? You always want to isolate the component in my opinion, so you wont get problems like this.
