### ISSUE TITLE
Svelte template don't render code attributes

### ISSUE THREAD

**Issue by Tlahey** [storybookjs/storybook#17560]
**Describe the bug**
Hello, I try my luck here.

Since Storybook ^6.4.0, svelte code doc doesn't render the parameters.

![Capture d’écran 2022-02-23 à 18 28 06](https://user-images.githubusercontent.com/2856778/155376188-029fc378-ece0-4bf7-963b-a7146fb73a4a.png)

**To Reproduce**
- Create a svelte project with `npx sb init` and run it.
- Go to your `localhost` and `Button` component. On the `Docs` tab, you can click on `show code` and you will see this
![Capture d’écran 2022-02-23 à 18 28 06](https://user-images.githubusercontent.com/2856778/155376188-029fc378-ece0-4bf7-963b-a7146fb73a4a.png)
- But if you rollback to the v6.3.13 on your `package.json` + `npm i`, you don't have any troubles.
![Capture d’écran 2022-02-23 à 18 30 11](https://user-images.githubusercontent.com/2856778/155377769-a28aefa2-951d-4f7f-b196-d7f1d23c351c.png)

**Additional context**
I don't know if it is a new feature of `@storybook/svelte` that causes this regression or the addon `@storybook/addon-svelte-csf` need an issue. 

Thanks.

**Comment by lauthieb** [comment]
Hi @shilman, we have this bug on https://github.com/Decathlon/vitamin-web/issues/990 reported by @gaspardmathon thanks to the work of @Tlahey.
Can you please help us? Thanks a lot in advance 🙏

**Comment by lauthieb** [comment]
Hi @shilman & all core contributors, we have this bug on https://github.com/Decathlon/vitamin-web/issues/990 reported by @gaspardmathon thanks to the work of @Tlahey.
Can you please help us? Thanks a lot in advance 🙏

**Comment by lauthieb** [comment]
Hi, do you have an idea please?

**Comment by lauthieb** [comment]
Hi Storybook team. Can you please help us? Thanks a lot :)

**Comment by shilman** [comment]
Zoinks!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-alpha.57 containing PR #17866 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
