### ISSUE TITLE
Puppeteer dep for storybook snaphots puppeteer is outdated

### ISSUE THREAD

**Issue by myufa** [storybookjs/storybook#17561]
**Describe the bug**
The dependency lock on storybook snapshots puppeteer keeping it at 3.3.0 and below keeps it a very old version of chromium (83.0.4103.0) that does not support common new features such as CSS flex gap. It requires one to force install with a higher version of puppeteer.

**To Reproduce**
Create a story with CSS flex gap

**System**
The gaps disappear

Please update to the latest puppeteer, having a dependency lock that is 10 versions behind makes this very unstable

**Comment by myufa** [comment]
https://github.com/storybookjs/storybook/pull/17562

**Comment by shilman** [comment]
Storyshots is EOL
