### ISSUE TITLE
Composition fails if previewTabs indices are different

### ISSUE THREAD

**Issue by tobi1220** [storybookjs/storybook#17575]
**Describe the bug**
Let's say I have two Storybooks: Storybook A and Storybook B, and they are in composition: Storybook A is being referenced in Storybook B through the `refs` field in Storybook B's `main.js`.
If the indices of the tabs aren't the same in both Storybooks, e.g. if Storybook A has a different index for the _docs_ tab than Storybook B, then Storybook will always jump back to the first story of Storybook B every time you click on a story from the referenced Storybook (hard to describe, please refer to the following gif):

![composition](https://user-images.githubusercontent.com/19271330/155601293-4de76930-6557-4f18-ba3e-2ea99cd57061.gif)

 ```js
previewTabs: {
  'storybook/docs/panel': { 
    index: -1,
  },
}
```

**To Reproduce**
I've created a repo consisting of two Storybook instances. The first has the `index` of the docs tab set to -1. The second is composing the first by referencing it (assuming they're both run locally). This repo can be viewed here: https://github.com/tobi1220/sbCompositionTest

1. Clone the repo
2. Run `npm run installs` (this will install the dependencies of both Storybook instances)
3. Run `npm run first`
4. Run `npm run second` in another terminal
5. Go to http://localhost:6007
6. Click on any story of the referenced Storybook

**System**
Storybook 6.4.19
Angular 13.2.4

```
System:
  OS: Windows 10 10.0.19042
Browsers:
  Chrome: 98.0.4758.102
npmPackages:
  @storybook/addon-actions: ^6.4.19 => 6.4.19
  @storybook/addon-essentials: ^6.4.19 => 6.4.19
  @storybook/addon-interactions: ^6.4.19 => 6.4.19
  @storybook/addon-links: ^6.4.19 => 6.4.19
  @storybook/angular: ^6.4.19 => 6.4.19
  @storybook/builder-webpack5: ^6.4.19 => 6.4.19
  @storybook/manager-webpack5: ^6.4.19 => 6.4.19
  @storybook/testing-library: ^0.0.9 => 0.0.9
```

**Additional context**
- this is not restricted to the docs tab only (also happens with canvas)
- also occurred with Angular 12

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
