### ISSUE TITLE
Strange problem with `<input>` that has a `list` attribute.

### ISSUE THREAD

**Issue by alexschrod** [storybookjs/storybook#17586]
**Describe the bug**
I have two nearly identical React components; the only difference between them is that the second one has a `list` property that accepts `string[]`, and that it adds a `list="dataList"` property on the `<input>` along with a `<datalist id="dataList">...</datalist>` to go with it.

Everything works as expected when using these components in the regular React app. (Try running `npm start` in the repo to see that in action) In Storybook, however, the one using the `datalist` is misbehaving.

The first odd thing is that the component doesn't get handed a mock fn for its `onValueChange` property. You can verify this in the console as I print "No args.onValueChange" there if `!args.onValueChange` is true.

The second thing is that whenever you type something in the textbox, the suggestion datalist gets closed. Again, this does not happen in the regular React app.

(In my non-reproduction project that inspired me to create this reproduction and bug report, I'm also having an issue where the arg doesn't get updated (again, only a problem for a component using this datalist thing; works fine in all my other components), but I can't get this specific behavior to occur in the reproduction repo.)

**To Reproduce**
I didn't use `npx sb@next repro` to set up my reproduction because I made my reproduction repo before coming here, but hopefully it's still good enough for you to validate the problem; the repo is at <https://github.com/alexschrod/storybook-issue-example> and the deployed reproduction is at <https://621a3b8e2762a4003ac6125b-pxrdxhkijr.chromatic.com/>.

**System**
```
❯ npx sb info

Environment Info:

  System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
  Binaries:
    Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 98.0.4758.102
    Edge: Spartan (44.19041.1266.0), Chromium (98.0.1108.62)
  npmPackages:
    @storybook/addon-actions: ^6.4.19 => 6.4.19
    @storybook/addon-essentials: ^6.4.19 => 6.4.19
    @storybook/addon-interactions: ^6.4.19 => 6.4.19
    @storybook/addon-links: ^6.4.19 => 6.4.19
    @storybook/builder-webpack5: ^6.4.19 => 6.4.19
    @storybook/manager-webpack5: ^6.4.19 => 6.4.19
    @storybook/node-logger: ^6.4.19 => 6.4.19
    @storybook/preset-create-react-app: ^4.0.1 => 4.0.1
    @storybook/react: ^6.4.19 => 6.4.19
    @storybook/testing-library: ^0.0.9 => 0.0.9
```

**Additional context**
N/A

**Comment by alexschrod** [comment]
I suspect the issue might be due to #11657. Worth revisiting once it is resolved.

Still often running into issues where `useArgs` doesn't update the control panel in my real project, though; and I've found that I can force it to update by going to the Actions or Interactions tab and then back to the Controls tab, so there's potentially some memoization with missing dependencies going on there.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
