### ISSUE TITLE
Only one `Story` is displayed, but multiple are exported

### ISSUE THREAD

**Issue by Domiii** [storybookjs/storybook#17588]
**Describe the bug**

After upgrading to latest, I only see one story per story file. Did not change anything in `main.js`, `preview.js` etc.

Specifically: A story file exports many named exports (stories), but only the first one shows up.
No warnings. No errors.

* → Probably to do with my [previous bug report](https://github.com/storybookjs/storybook/issues/17587), leading to those `__namedExportsOrder` props getting picked up by the story loader which cannot make sense of string arrays and then silently stops trying?

E.g., the result of the story code below is only the first story:
![image](https://user-images.githubusercontent.com/282899/155848620-ad73e675-364c-49ef-92dc-eb4d8b904232.png)

**To Reproduce**
Example (but it happens to all my stories):

```js
import Modal from '../components/Modal';

export default {
  title: 'common/Modal',
  component: Modal,
  argTypes: {
    // backgroundColor: { control: 'color' },
  },
};

export * from './ConfirmBasic';
export * from './ConfirmMulti';
export * from './FormBasic';
export * from './Blocking';
```

**System**

Same as my last bug report:
```
  System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
  Binaries:
    Node: 16.13.1 - ~\AppData\Local\Volta\tools\image\node\16.13.1\node.EXE
    Yarn: 1.22.17 - ~\AppData\Local\Volta\tools\image\yarn\1.22.17\bin\yarn.CMD
    npm: 8.1.2 - ~\AppData\Local\Volta\tools\image\node\16.13.1\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (98.0.1108.56)
  npmPackages:
    @storybook/addon-actions: ^6.5.0-alpha.41 => 6.5.0-alpha.42       
    @storybook/addon-essentials: ^6.5.0-alpha.41 => 6.5.0-alpha.42    
    @storybook/addon-links: ^6.5.0-alpha.41 => 6.5.0-alpha.42
    @storybook/addon-postcss: ^2.0.0 => 2.0.0
    @storybook/builder-webpack5: ^6.5.0-alpha.41 => 6.5.0-alpha.42    
    @storybook/manager-webpack5: ^6.5.0-alpha.41 => 6.5.0-alpha.42    
    @storybook/react: ^6.5.0-alpha.41 => 6.5.0-alpha.42
```

PS: Every time I upgrade, I come across more bugs. I'll look forward to the `emotion` diamond dependency conflict to fully be resolved, and I can finally stop upgrading to unstable pre-release versions...

**Comment by shilman** [comment]
Do you a have a reproduction repo you can share? If not, can you create one? See [how to create a repro](https://storybook.js.org/docs/react/contribute/how-to-reproduce). Thank you! 🙏

**Comment by Domiii** [comment]
As discussed in #17587: I was re-exporting stories. Not re-exporting anymore, solved this.
