### ISSUE TITLE
run npx sb init error

### ISSUE THREAD

**Issue by yuzhanglong** [storybookjs/storybook#17593]
**Describe the bug**
run npx sb init error
<img width="742" alt="image" src="https://user-images.githubusercontent.com/56540811/155979449-f8af030e-126f-419a-8422-e8bbe2455ca0.png">

Environment Info:

  System:
    OS: macOS 12.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.1/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
  Browsers:
    Chrome: 98.0.4758.109
    Firefox: 96.0.1
    Safari: 15.2

**Comment by Tejas-Ladhani** [comment]
Any temporary solution for this ??

**Comment by yuzhanglong** [comment]
> Any temporary solution for this ??

Yes, but not completely solved, I used our company's package management tool, the above error occurred, I tried to change to PNPM or YARN, there is no error~

**Comment by Tejas-Ladhani** [comment]
I guess, I found the cause, the error shows the absence of the storybook CLI: https://www.npmjs.com/package/@storybook/cli

**Comment by Tejas-Ladhani** [comment]
> > Any temporary solution for this ??
> 
> Yes, but not completely solved, I used our company's package management tool, the above error occurred, I tried to change to PNPM or YARN, there is no error~

I guess, I found the cause, the error shows the absence of the storybook CLI: https://www.npmjs.com/package/@storybook/cli
