### ISSUE TITLE
ESM/ES Module project support

### ISSUE THREAD

**Issue by psychobolt** [storybookjs/storybook#17591]
**Is your feature request related to a problem? Please describe**
Storybook currently fails to require main.mjs or main.js if projects are configured to use `{ "type": "modules" }`

`ES Modules. E.g. ERR! Error [ERR_REQUIRE_ESM]: require() of ES Module <some_project_path>/.storybook/main.js not supported.`

**Describe the solution you'd like**
Storybook can build and run without any problems for projects with ESM formated config.

**Describe alternatives you've considered**
Just sticking with commonJS... https://github.com/storybookjs/storybook/issues/16181

**Are you able to assist to bring the feature to reality?**
No, I am hoping someone can chime in. For now I am using the workaround. Just creating this feature request for future work tracking...

**Comment by psychobolt** [comment]
Closing since its being worked on and tracking release for 7: https://storybook.js.org/blog/storybook-6-2/

**Comment by CarlosBalladares** [comment]
same on 6.5
![image](https://user-images.githubusercontent.com/14811752/177026412-833a49a0-ede7-4184-acbf-d2b7fd1d332b.png)
