### ISSUE TITLE
Document CSF3 auto-title

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#17596]
AFAICT this is the current documentation for auto-generating titles

https://storybook.js.org/docs/7.0/react/configure/sidebar-and-urls#generating-titles-based-on-__dirname

This is incompatible with the static analysis that we're doing for `stories.json` generation, which is the basis for `storyStoreV7`, so it should be removed from the docs.

Instead we should document CSF3 auto-title, which is experimental but enabled out of the box in 6.4.

**Comment by LucaCras** [comment]
Hi @shilman, I would like to make my first contribution to the project! Would this be a suitable issue to pick up if it's not already being worked on?

**Comment by shilman** [comment]
Hi @LucaCras indeed, that would be wonderful. Perhaps @jonniebigodes can help guide your contribution here!

**Comment by LucaCras** [comment]
I have created a PR with changes to the documentation, mainly basing my information on the following blog: https://storybook.js.org/blog/component-story-format-3-0/

Please let me know if there is anything I can do to improve and/or fix :)

**Comment by jonniebigodes** [comment]
@LucaCras thanks for taking the time to address this we appreciate it! I've seen the notification and saw the pull request. I'll take a look at it and follow up with you for feedback? Sounds good?

Have a great weekend!

Stay safe.

**Comment by jonniebigodes** [comment]
Closing this issue as the documentation was already updated thanks to the amazing contribution by @LucaCras!
