### ISSUE TITLE
Storybook Styling Issues

### ISSUE THREAD

**Issue by vinceclicks** [storybookjs/storybook#17600]
I'm using Angular Storybook.

I'm having an issue where when I add a story to my reusable components, the styling doesn't look at all like the the styling of a component used in a project.

For example, I have an Icon Description component that contains an icon, a description, and a background circle. Here's what it looks like in project: 
![image](https://user-images.githubusercontent.com/88698698/156193426-fc54ac70-4113-4486-9d77-4da95ec3deba.png)

and here's what it looks like in Storybook:
![image](https://user-images.githubusercontent.com/88698698/156193571-4e4e2caa-2d25-4a81-82ac-c035b68e9eaa.png)

Many of the stories do work as they should while a few these styling issues don't resolve well. As a separate issue I've also come to the occurrence where Storybook is unable to resolve certain stylesheets even though they work on projects.

**Comment by vinceclicks** [comment]
One of the things Storybook is not resolving here is calc() functions in SCSS, as well as Storybook having an issue with Scss imports like "sass:math"

**Comment by ndelangen** [comment]
You'll might have to setup CSS loading or SASS loading for your builder?

Without a reproduction there's nothing we can do.
We have no way of knowing how your project is setup. I suggest reading this:
https://storybook.js.org/docs/react/builders/webpack#extending-storybooks-webpack-config
