### ISSUE TITLE
Global styles are not getting applied by storybook

### ISSUE THREAD

**Issue by duxard** [storybookjs/storybook#17617]
Hi Team,
I have the following issue on my Storybook site.

I have a simple Angular app with a regular project structure, e.g.:

test component 
  - test.component.ts
  - test.component.less
  - test.component.html

...each of components has it's own encapsulated styles, e.g. test.component.less :

:host {
  // ...styles
}

Apart from that I also have a .less file with global styles [global.less] and, let's say, it lives in the same folder as 'preview.js'.
I added it to storybook configuration (preview.js):

`import '!style-loader!css-loader!less-loader!./global.less';`

-------------

Now I see that only encapsulated styles are getting applied in full. As for global styles - they are not being applied, though I'm 100% sure that global.less has been imported successfully. Do you have any ideas why  the absolute majority of global styles are not getting applied?

Thanks,
Aleksandr

**Comment by hansireit** [comment]
From angular version 13 the style loader in the _preview.js_ is not needed any more.
You need to included your global styles in your storybook-builder inside the **angular.json**.
Like shown in the answer of this [stackoverflow-question.](https://stackoverflow.com/questions/71073685/setting-storybook-scss-import-paths-for-angular-library/71103186#71103186)

**Comment by duxard** [comment]
@hansireit thank you man for the advice!
