### ISSUE TITLE
***URGENT - Potential security vulnerabilities***

### ISSUE THREAD

**Issue by smo043** [storybookjs/storybook#17648]
Hello Team,

Could you please bump the below dependencies version to the latest?

1. **glob-parent:**

### Remediation
Upgrade glob-parent to version 5.1.2 or later. For example:
```
glob-parent@^5.1.2:
  version "5.1.2"
```
_Always verify the validity and compatibility of suggestions with your codebase._

@storybook/react@6.4.19
│ ├─┬ @storybook/core@6.4.19
│ │ └─┬ @storybook/core-server@6.4.19
│ │   └─┬ cpy@8.1.2
│ │     └─┬ globby@9.2.0
│ │       └─┬ fast-glob@2.2.7
│ │         └── glob-parent@3.1.0

2. **trim:**

### Remediation
Upgrade trim to version 0.0.3 or later. For example:

```
trim@^0.0.3:
  version "0.0.3"
```

└─┬ @storybook/addon-essentials@6.4.19
  └─┬ @storybook/addon-docs@6.4.19
    └─┬ @mdx-js/mdx@1.6.22
      └─┬ remark-parse@8.0.3
        └── trim@0.0.1

**Comment by farideliyev** [comment]
@smo043 issue related with trim is fixed, look at #14603. 
I have the same issue with  glob-parent

**Comment by mxpaspa** [comment]
@farideliyev Any idea when the `glob-parent` vulnerability will be remediated? Thank you,.

**Comment by smo043** [comment]
Pls release a patch version to fix the vulnerabilities. Security team is behind us.

**Comment by marcoaring** [comment]
Pls release a patch version to fix the vulnerabilities. Security team is behind us ².

**Comment by shilman** [comment]
closing as dupe to https://github.com/storybookjs/storybook/issues/15174 and https://github.com/storybookjs/storybook/issues/14603
