### ISSUE TITLE
No control init when using componentWrapperDecorator in Angular

### ISSUE THREAD

**Issue by Noeldeveloper** [storybookjs/storybook#17660]
When using componentWrapperDecorator, stories don't initialize with defined configuration, until a @input control was clicked.

It could be reproduced with Angular v11.2.18, and storybook v6.4.19 

![image](https://user-images.githubusercontent.com/15780540/157245494-10647693-7239-4209-88d9-cda87a5d3ed4.png)

![image](https://user-images.githubusercontent.com/15780540/157245593-353341f8-0390-4c26-b381-21af533b3c82.png)

**Comment by ThibaudAV** [comment]
👋  Can you give a simple example of a story representing the problem ? (The ideal would be with the last version of storybook. to be sure that the problem is always present)

You could pass second param to `componentWrapperDecorator` to config this props

```
componentWrapperDecorator(ParentComponent, ({ args }) => ({
    parentText: args.parentText,
    onClickParent: args.onClickParent,
  }))
```

**Comment by Noeldesarrollo** [comment]
I was tried that, but not luck.
This is my component code.
`import { Component, EventEmitter, Input, Output } from '@angular/core';

@Component({
  selector: 'lib-radio-button',
  templateUrl: './radio-button.component.html'
})

export class RadioButtonComponent {
  @Output() radioSelected = new EventEmitter<{}>();
  /**
   * Nombre del controlador dentro del formGroup.
   */
  @Input() formControlRadioName = '';
  /**
   * Setea el estado desactivado del elemento.
   */
  @Input() disabled?: boolean;
  /**
   * Setea el estado marcado del elemento.
   */
  @Input() checked = false;
  /**
   * Nombre de clase del elemento.
   */
  @Input() classList?: string;
  /**
   * Nombre de clase del label del elemento.
   */
  @Input() labelClassList?: string;
  /**
   * Valor del elemento.
   */
  @Input() value: string | boolean = false;
  /**
   * Identificador único del input[radio].
   */
  @Input() idRadio?: string;

  onRadioChecked() {
    if (!this.disabled) {
      this.checked = !this.checked;
      this.radioSelected.emit({
        value: this.value,
        checked: this.checked
      });
    }
  }
}`

This is my component html
`<div [ngClass]="classList">
  <div
    appClickStopPropagation
    class="radio">
    <input
      type="radio"
      [id]="idRadio"
      [value]="value"
      [checked]="checked ? true : null"
      [attr.disabled]="disabled || disabled ? true : null"
      (click)="onRadioChecked()"
      tabindex="0"
    />
    <label [for]="idRadio" class="text" [ngClass]="labelClassList">
      <ng-content></ng-content>
    </label>
  </div>
</div>`

This is my component story
`
import { componentWrapperDecorator, moduleMetadata } from '@storybook/angular';
import { Meta, Story } from '@storybook/angular/types-6-0';
import { RadioButtonComponent } from 'src/app/radio-button/radio-button.component';

export default {
  title: 'Example/Radio',
  component: RadioButtonComponent,
  decorators: [componentWrapperDecorator((story) => `<lib-radio-button>Label</lib-radio-button>`, ({ args }) => ({
    parentText: args.parentText,
    onClickParent: args.onClickParent,
  }))]
} as Meta;

const Template: Story<RadioButtonComponent> = (args: RadioButtonComponent) => ({
  props: args
});

export const groupedRadio = Template.bind({});

groupedRadio.args = {
  checked: false,
  idRadio: '',
  value: 'val',
  disabled: false,
  classList: '',
  labelClassList: '',
  formControlRadioName: 'name'
};

export const groupedRadioChecked = Template.bind({});
groupedRadioChecked.args = {
  checked: true,
  idRadio: '',
  value: 'val',
  disabled: false,
  classList: '',
  labelClassList: '',
  formControlRadioName: 'name'
};

export const groupedRadioDisabled = Template.bind({});
groupedRadioDisabled.args = {
  checked: false,
  idRadio: '',
  value: 'val',
  disabled: true,
  classList: '',
  labelClassList: '',
  formControlRadioName: 'name'
};

export const WithLabelClass = Template.bind({});
WithLabelClass.args = {
  checked: false,
  idRadio: '',
  value: 'val',
  disabled: false,
  classList: '',
  labelClassList: 'hidden',
  formControlRadioName: 'name'
};

export const separatedRadio = Template.bind({});
separatedRadio.args = {
  checked: false,
  idRadio: '',
  value: 'val',
  disabled: false,
  classList: '',
  labelClassList: '',
  formControlRadioName: ''
};

export const groupedRadioClassList = Template.bind({});
groupedRadioClassList.args = {
  checked: false,
  idRadio: '',
  value: 'val',
  disabled: false,
  classList: 'class1',
  labelClassList: '',
  formControlRadioName: 'name'
};

export const groupedRadioCheckedDisabled = Template.bind({});
groupedRadioCheckedDisabled.args = {
  checked: true,
  idRadio: '',
  value: 'val',
  disabled: true,
  classList: '',
  labelClassList: '',
  formControlRadioName: 'name'
};
`

**Comment by nvytychakdev** [comment]
`componentWrapperDecorator(story => {})` usually used to wrap your story with additional components/templates.
In your case seems like it used to provide `ng-content` inside the component.

Consider using the `template` property of the story for that instead:
```
const Template: Story = (args: RadioButtonComponent) => ({
  props: args,
  template: `<lib-radio-button 
     [checked]="checked" 
     [idRadio]="idRadio" 
     [value]="value"
     [disabled]="disabled"
     [classList]="classList"
     [labelClassList]="labelClassList">Label</lib-radio-button>`
});
``` 
Please take note that inputs should be provided there as well.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
