### ISSUE TITLE
Cannot `npm run storybook`. Getting Cannot find module 'core-js/modules/es.weak-map.js' error

### ISSUE THREAD

**Issue by aquanow-eric** [storybookjs/storybook#17678]
**Describe the bug**
Cannot `npm run storybook`. Getting Cannot find module 'core-js/modules/es.weak-map.js' error

**To Reproduce**
Existing react project, node v14.19, npm 6.14.16, storybook 6.4.19 --- run `npx sb init --type react` to install, then `npm run storybook`

**System**
ERR! Error: Cannot find module 'core-js/modules/es.weak-map.js'
ERR! Require stack:
ERR! - /Users/ericlau/WebstormProjects/coinsquare-trader-webapp/node_modules/@storybook/addon-interactions/dist/cjs/preset/checkActionsLoaded.js
ERR! - /Users/ericlau/WebstormProjects/coinsquare-trader-webapp/node_modules/@storybook/addon-interactions/preset.js
ERR! - /Users/ericlau/WebstormProjects/coinsquare-trader-webapp/node_modules/@storybook/core-common/dist/cjs/presets.js
ERR! - /Users/ericlau/WebstormProjects/coinsquare-trader-webapp/node_modules/@storybook/core-common/dist/cjs/index.js
ERR! - /Users/ericlau/WebstormProjects/coinsquare-trader-webapp/node_modules/@storybook/core-server/dist/cjs/index.js
ERR! - /Users/ericlau/WebstormProjects/coinsquare-trader-webapp/node_modules/@storybook/core/dist/cjs/server.js
ERR! - /Users/ericlau/WebstormProjects/coinsquare-trader-webapp/node_modules/@storybook/core/server.js
ERR! - /Users/ericlau/WebstormProjects/coinsquare-trader-webapp/node_modules/@storybook/react/dist/cjs/server/index.js
ERR! - /Users/ericlau/WebstormProjects/coinsquare-trader-webapp/node_modules/@storybook/react/bin/index.js
ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:746:27)
ERR!     at Module.require (internal/modules/cjs/loader.js:974:19)
ERR!     at require (internal/modules/cjs/helpers.js:101:18)
ERR!     at Object.<anonymous> (/Users/ericlau/WebstormProjects/coinsquare-trader-webapp/node_modules/@storybook/addon-interactions/dist/cjs/preset/checkActionsLoaded.js:5:1)
ERR!     at Module._compile (internal/modules/cjs/loader.js:1085:14)
ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
ERR!     at Module.load (internal/modules/cjs/loader.js:950:32)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
ERR!     at Module.require (internal/modules/cjs/loader.js:974:19)
ERR!     at require (internal/modules/cjs/helpers.js:101:18)
ERR!     at Object.managerEntries (/Users/ericlau/WebstormProjects/coinsquare-trader-webapp/node_modules/@storybook/addon-interactions/preset.js:7:34)
ERR!     at /Users/ericlau/WebstormProjects/coinsquare-trader-webapp/node_modules/@storybook/core-common/dist/cjs/presets.js:279:28

**Additional context**
Existing project, node v14.19, npm 6.14.16, storybook 6.4.19

**Comment by ewolfe** [comment]
Try the directions here https://github.com/storybookjs/storybook/blob/main/MIGRATION.md#core-js-dependency-errors
