### ISSUE TITLE
storyStoreV7 not compatible with IE11 due to missing fetch polyfill

### ISSUE THREAD

**Issue by jpveooys** [storybookjs/storybook#17677]
**Describe the bug**

Using `storyStoreV7` breaks IE11. I tracked this down to `fetch` being undefined (in both the root URL and the iframe).

**To Reproduce**

Example repo:

https://github.com/jpveooys/storybook-storystorev7-ie11

Deployed at:

https://ie11-storystorev7.netlify.app

**System**

```
Environment Info:

  System:
    OS: Linux 5.13 Ubuntu 21.10 21.10 (Impish Indri)
    CPU: (16) x64 AMD Ryzen 7 PRO 5850U with Radeon Graphics
  Binaries:
    Node: 16.14.0 - /usr/bin/node
    Yarn: 3.2.0 - /usr/bin/yarn
    npm: 8.3.1 - /usr/bin/npm
  Browsers:
    Chrome: 99.0.4844.51
    Firefox: 97.0.2
  npmPackages:
    @storybook/addon-actions: ^6.5.0-alpha.46 => 6.5.0-alpha.46 
    @storybook/addon-docs: ^6.5.0-alpha.46 => 6.5.0-alpha.46 
    @storybook/addon-essentials: ^6.5.0-alpha.46 => 6.5.0-alpha.46 
    @storybook/addon-interactions: ^6.5.0-alpha.46 => 6.5.0-alpha.46 
    @storybook/addon-links: ^6.5.0-alpha.46 => 6.5.0-alpha.46 
    @storybook/react: ^6.5.0-alpha.46 => 6.5.0-alpha.46 
    @storybook/testing-library: ^0.0.9 => 0.0.9 
```

**Screenshot**

![Screenshot from 2022-03-09 15-39-39](https://user-images.githubusercontent.com/66470099/157477899-12914f70-4ad0-4682-9983-35831c7d6d7e.png)

**Additional context**

Adding a fetch polyfill fixes this, but it's difficult to do this cleanly and early enough on the app side in both contexts.

I can also see [there is already some code to load a fetch polyfill](https://github.com/storybookjs/storybook/blob/a8db9585f07d8cfc7354e68f6b780a6ff6536b38/lib/core-client/src/manager/conditional-polyfills.ts), so either this is not loading or isn't loading early enough.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
