### ISSUE TITLE
[Bug in @storybook/vue3] some actions trigger behavior not work suit with vue3 best practice.

### ISSUE THREAD

**Issue by Matrixbirds** [storybookjs/storybook#17671]
**Describe the bug**
I got this warning, when i am integrate [element-plus](https://github.com/element-plus/element-plus) into storybook,
I was set on the `parameters` option with below script
```javascript
export default {
    parameters: {
        handles: ['click button']
    }
}
```
And then click the `el-button` on the page of stories will trigger click event succeed, but i will got many warnings.
If i used another way to bind events manually, the warning log will dismiss.

**To Reproduce**
* manually trigger click in this stories you will see the log stack as below
```javascript
runtime-core.esm-bundler.jss:38 [Vue warn]: Avoid app logic that relies on enumerating keys on a component instance. The keys will be empty in production mode to avoid performance overhead.
warn @ runtime-core.esm-bundler.jss:38
PublicInstanceProxyHandlers.ownKeys @ runtime-core.esm-bundler.jss:6817
stringify @ index.jss:401
send @ index.jss:159
handler @ index.jss:90
emit @ index.jss:100
actionHandler @ action.jss:81
handler @ withActions.jss:92
vendors-node_modules_storybook_addon-actions_6_4_19_node_modules_storybook_addon-actions-258cbc.manager.bundle.js:118891 [Violation] 'setTimeout' handler took 124ms
[Violation] Forced reflow while executing JavaScript took 48ms
```
**System and environments**
* MacOS
* Node dependencies
```javascript
      '@storybook/addon-actions': ^6.4.19
      '@storybook/addon-essentials': ^6.4.19
      '@storybook/addon-links': ^6.4.19
      '@storybook/builder-webpack5': ^6.4.19
      '@storybook/manager-webpack5': ^6.4.19
      '@storybook/vue3': ^6.4.19
```

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
