### ISSUE TITLE
ArgTypes documentation

### ISSUE THREAD

**Issue by thany** [storybookjs/storybook#17681]
**Is your feature request related to a problem? Please describe**
Missing ArgTypes documentation. [There's only this](https://storybook.js.org/docs/react/api/argtypes) which is a brief summary with some examples that don't even appear to match the screenshot. Confusing at best, iyam. 

**Describe the solution you'd like**
A full reference of ArgTypes. What *exactly* can I do with them? A full API reference, not a bunch of examples.

**Describe alternatives you've considered**
Currently, I have to look at examples and combine code snippets from all over the place to hopefully be able to give Storybook an argType that it understands. Or, I have to look at the source code to see how they are parsed, in order to know what the capabilities are exactly. Other than that, we have no way to know for sure what the capabilities of ArgTypes are, given a single source of truth (i.e. official documentation).

**Are you able to assist to bring the feature to reality?**
No, I haven't built it, so I cannot know how exactly it works.

**Additional context**
It's important to realise that however awesome something is, if it's not made clear how to use it, it will eventually be percieved as confusing or difficult. With proper full documentation and API reference, this could be prevented. I know writing documentation is hard and boring and whatall, but it has to be done.

**Comment by jblevins1991** [comment]
Yeah, I honestly hated how verbose the thing that came before controls, but at least I knew how to use it. This is a painful at best dev experience. At worst, I am considering moving back to a deprecated plugin because it allows me perform the job my employer is paying me to do.

**Comment by jonniebigodes** [comment]
We're aware of the fragmentation of the documentation and it's already being tracked. We're planning on getting consolidated, updated in one place similar to other parts of the documentation that were already redone.

Nonetheless thanks for bringing this to our attention we appreciate it.

Hope you all have a great weekend!

Stay safe

**Comment by avi5079** [comment]
Hello @jonniebigodes,
I am a beginner to open source. I would like to learn by contributing to this repo. Can you please guide me in this project like how to get started?

**Comment by kylegach** [comment]
Related discussion: https://github.com/storybookjs/storybook/discussions/22495#discussioncomment-5859676
