### ISSUE TITLE
Update the `title` when Storybook is loading from "Webpack app" to "Storybook loading..."

### ISSUE THREAD

**Issue by MichaelArestad** [storybookjs/storybook#17709]
**Describe the bug**
When building storybook, the title shows "Webpack App". Can we change it to "Storybook loading..."?

I found the title referenced in these files, but they are untracked so are likely not where the change needs to be made:

`lib/manager-webpack4/prebuilt/index.html`
`lib/manager-webpack5/prebuilt/index.html`

**Comment by pmcelhaney** [comment]
Looks like it's configured here. 

https://github.com/jantimon/html-webpack-plugin#options

**Comment by MichaelArestad** [comment]
@pmcelhaney Thanks! I will take care of this sometime this week!

**Comment by shilman** [comment]
w00t!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-alpha.10 containing PR #17935 that references this issue. Upgrade today to the `@future` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
