### ISSUE TITLE
PR Template Requests Running Tests But Gives No Instruction

### ISSUE THREAD

**Issue by tacc-wbomar** [storybookjs/storybook#17703]
**Is your feature request related to a problem? Please describe**
Yes. My PR is #17702, but [anyone opening a PR for a UI change may be requested to run Jest or Chromatic tests](https://github.com/storybookjs/storybook/blob/149bb74/.github/PULL_REQUEST_TEMPLATE.md?plain=1#L11).

There is no instruction for testing, and the process was too much for so small a change, yet the request was still made.

**Describe the solution you'd like**
A link in the Pull Request template to instructions for how to perform tests requested.

_I support requesting testing, but I do not support the unexpected trouble when trying to test. See "Additional context"._

**Describe alternatives you've considered**
1. Researching on my own how to run the requested tests. See "Additional context".
2. Improving the wording of the PR template to disregard testing for a minuscule changes.

**Are you able to assist to bring the feature to reality?**
Yes, but I am too angry at the moment to promise to assist beyond creating this ticket.

**Additional context**

<details><summary>I took many steps to run the test suite, but eventually failed. <sub>Click for details.</sub></summary>

1. Clone my fork of the repo.
3. Run `yarn install`.
4. Run `yarn jest`.
5. See tests fail because dev dependencies were not installed.
6. Fail to install all dependencies because I was using a command for Yarn Classic.
7. Determine my yarn version... version 3.
8. Fail to learn how to install all dev dependencies with Yarn 3.
9. Learn how to downgrade to Yarn Classic.
10. Install all dev dependencies.
11. Be asked for which version to use for __every__ `@storybook/...` dev dependency! [^1]
    ```
    Couldn't find any versions for "@storybook/svelte" that matches "workspace:*"
    ? Please choose a version of "@storybook/svelte" from this list: 
    ```

    I chose `6.5.0-alpha.47` for every options, because I am impatient and annoyed.
12. Be lambasted with [many warnings](https://github.com/storybookjs/storybook/files/8240596/storybook-isntall-deps-warnings.log).
13. Receive one error:
    `error An unexpected error occurred: "expected workspace package to exist for \"react-router-dom\"".`
14. Run `yarn jest`.
15. Receive more reports of missing dependencies. See [snippet](https://github.com/storybookjs/storybook/files/8240612/storybook-jest-run-errors.log).
17. **Give up!**

</details>

[^1]: Why is a known working version of each dependency not pinned?!

**Comment by tacc-wbomar** [comment]
I see now that Chromatic tests run automatically. Super, thanks for that unnecessary workout (see "Additional context" in issue description). I still suggest some instruction. I tried to be a good FOSS citizen, but now feel like a disenchanted consumer.

**Comment by yannbf** [comment]
Hey @tacc-wbomar, I greatly appreciate your contribution to this project and I'm sorry you went through a bad experience with testing.

We have a contributor's guide of which you can find linked in our [CONTRIBUTING.md](https://github.com/storybookjs/storybook/blob/next/CONTRIBUTING.md) file and that ends up pointing to [this page](https://storybook.js.org/docs/react/contribute/code). Did you see that before? That page contains instructions to properly install and test the repository. We use yarn workspaces and the dependencies are locally built and mapped, so you shouldn't have to select any of our dependency versions from the npm registry.

Unfortunately the monorepo has quite some complexity so it's not that trivial to find out how to test certain changes based on what files you touched. In your case, the CLI templates are only used in the E2E tests, which we have instructions for [here](https://storybook.js.org/docs/react/contribute/code#end-to-end-tests-e2e).

I'm sure the PR template could be improved, and I'd love to hear your thoughts to avoid having other contributors going through similar frustrations. Thank you!

**Comment by yannbf** [comment]
No worries @tacc-wbomar! I totally understand your frustration and I hope others don't go through similar experience.

I see value in improving the PR template and I'm looking forward to seeing yet another contribution from you!

**Comment by shilman** [comment]
Jeepers creepers!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-alpha.52 containing PR #17713 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```
