### ISSUE TITLE
Nested Router error after upgrading to Storybook v6.4 from v6.3

### ISSUE THREAD

**Issue by wellyshen** [storybookjs/storybook#17712]
Thank you for this great platform. We're using react-router v6 in our project and some of our storybook components are using the `useLoaction()` hook of react-router. So we provide a location for the components by a decorator [like this](https://github.com/storybookjs/storybook/issues/14667#issuecomment-823738232). After we upgrade Storybook from v6.3 to v6.4 we encounter the following error. So now we have to lock the minor version as `~6.3.8`. Do you have any suggestions for that? Thank you.

<img width="1484" alt="截圖 2022-03-14 下午3 38 48" src="https://user-images.githubusercontent.com/21308003/158278431-90fc8260-dc26-4ba7-8c89-f1c7dad57a4c.png">

**Comment by shilman** [comment]
We've updated the way we handle `react-router` in 6.5. Try upgrading to the latest prerelease:

```
npx sb@next upgrade --prerelease
```

Does that fix it?

**Comment by karsai5** [comment]
I still get the error when running `v6.5.0-alpha.51`. I'm using a `MemoryRouter` in a decorator, similar to what @wellyshen described

<img width="922" alt="Screen Shot 2022-03-29 at 3 17 49 pm" src="https://user-images.githubusercontent.com/4230159/160532208-db60f895-1db3-4d34-bce9-2b9964e18be3.png">

**Comment by shilman** [comment]
@karsai5 can you do an `npm ls` or `yarn why` to make sure you're running the 6.5 version of all storybook packages?

**Comment by karsai5** [comment]
I get the following result for @storybook/react
<img width="999" alt="Screen Shot 2022-03-29 at 3 27 06 pm" src="https://user-images.githubusercontent.com/4230159/160533260-8e059cf8-0817-4a8a-a78e-0ff3f5e86992.png">

**Comment by karsai5** [comment]
After doing some more reading I found this comment which seems to work in case anyone else runs into the same issue https://github.com/remix-run/react-router/issues/7375#issuecomment-975431736.

My decorator now looks like this: 
```jsx
(Story) => (
  <UNSAFE_LocationContext.Provider value={null}>
    <MemoryRouter>
      <Story />
    </MemoryRouter>
  </UNSAFE_LocationContext.Provider>
),
```

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
