### ISSUE TITLE
Elements lose focus when manually stepping through interactions in interactionsDebugger

### ISSUE THREAD

**Issue by Gilstroem** [storybookjs/storybook#17743]
Hello 👋

**Describe the bug**
Stories which rely on an element being focused do not work when manually stepped through, because the *Go forward* button in the `interactionsDebugger` steals focus. This causes subsequent keyboard events to not work.

e.g. in:
```tsx
await userEvent.tab();
await userEvent.keyboard("{Enter}");
```
focus is lost before the keyboard event is called.

**To Reproduce**
https://github.com/Gilstroem/sb-focus-bug-repro
https://gilstroem.github.io/sb-focus-bug-repro/?path=/story/example-button--primary

**System**
Environment Info:

  System:
    OS: macOS 12.0
    CPU: (8) arm64 Apple M1 Pro
  Binaries:
    Node: 17.0.1 - /opt/homebrew/bin/node
    Yarn: 3.2.0 - /opt/homebrew/bin/yarn
    npm: 8.1.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 99.0.4844.74
    Safari: 15.0
  npmPackages:
    @storybook/addon-actions: ^6.5.0-alpha.49 => 6.5.0-alpha.49 
    @storybook/addon-docs: ^6.5.0-alpha.49 => 6.5.0-alpha.49 
    @storybook/addon-essentials: ^6.5.0-alpha.49 => 6.5.0-alpha.49 
    @storybook/addon-interactions: ^6.4.19 => 6.4.19 
    @storybook/addon-links: ^6.5.0-alpha.49 => 6.5.0-alpha.49 
    @storybook/builder-webpack5: ^6.5.0-alpha.49 => 6.5.0-alpha.49 
    @storybook/jest: ^0.0.9 => 0.0.9 
    @storybook/manager-webpack5: ^6.5.0-alpha.49 => 6.5.0-alpha.49 
    @storybook/node-logger: ^6.5.0-alpha.49 => 6.5.0-alpha.49 
    @storybook/preset-create-react-app: ^4.1.0 => 4.1.0 
    @storybook/react: ^6.5.0-alpha.49 => 6.5.0-alpha.49 
    @storybook/test-runner: ^0.0.4 => 0.0.4 
    @storybook/testing-library: ^0.0.9 => 0.0.9 

**Additional context**
- The test passes when run in one go, it is only when stepping through.
- Might be related to: https://github.com/storybookjs/storybook/issues/16139

Please let me know if you need any more information

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
