### ISSUE TITLE
running npm run storybook angular --> searches for files that do not exist

### ISSUE THREAD

**Issue by NSTSA1** [storybookjs/storybook#17741]
running npm run storybook in my angular application results to the following error:
![image](https://user-images.githubusercontent.com/60392882/158789324-03ac8b4f-bf3d-4e32-8802-3ab8477e52c4.png)
![image](https://user-images.githubusercontent.com/60392882/158789488-7481d85f-dd86-4983-8029-d55b4de352c0.png)

As I see, it searches for files in file-paths and actual files, which do not exist - in the given example it searches for src/app/features/products/details/product-details.ts.

But my structure looks like that:

![image](https://user-images.githubusercontent.com/60392882/158789852-c3e0a86f-b825-4fc5-b587-060933b7eba3.png)

src/app/features/products/... --> without the file "product-details.ts" which is being searched for - as I dont have this file in my project.

repro and next info sadly also doesnt work .. 

all my .ts files strictly follows the naming convention of component-name.component.ts

do I need to set a certain configuration? why is it searching for files, which do not exist ? 

**To Reproduce**
reproducing sadly doesnt worj
**System**
```
Environment Info:

  System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz
  Binaries:
    Node: 14.17.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (99.0.1150.39)
  npmPackages:
    @storybook/addon-actions: ^6.4.19 => 6.4.19
    @storybook/addon-essentials: ^6.4.19 => 6.4.19
    @storybook/addon-interactions: ^6.4.19 => 6.4.19
    @storybook/addon-links: ^6.4.19 => 6.4.19
    @storybook/angular: ^6.4.19 => 6.4.19
    @storybook/builder-webpack5: ^6.4.19 => 6.4.19
    @storybook/manager-webpack5: ^6.4.19 => 6.4.19
    @storybook/testing-library: 0.0.9 => 0.0.9
```

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
