### ISSUE TITLE
@storybook/react forces a typescript version peer dependency via docgen dependency

### ISSUE THREAD

**Issue by dsanders1234** [storybookjs/storybook#17757]
**Describe the bug**
@storybook/react forces a version of typescript via its docgen canary version dependency.  That docgen package has a peerDependency on a specific version of typescript.  If this is intentional, then the @storybook/react documentation should mention this up front, otherwise this should be fixed.

**To Reproduce**
Try to upgrade storybook 6.1.21 that uses typescript 3.9.7 to a newer version of storybook (>= 6.3).  We are not ready to upgrade our component library and apps to a newer version of typescript (although we are working on it), but we wanted to take advantage of newer storybook and are unable to upgrade.  We do not use the docgen feature.  As a side note, we use rushjs with pnpm for our monorepo (I actually suggest the storybook team adopt this stack, as it gets rid of dependency hoisting issues, etc.).

**System**
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
  Binaries:
    Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.17.3 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.7 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 99.0.4844.74
    Edge: Spartan (44.19041.1266.0), Chromium (99.0.1150.39)

**Additional context**
We don't use yarn.

**Comment by IanVS** [comment]
@dsanders1234 could you share the output of `npm why typescript`?

**Comment by dsanders1234** [comment]
This project uses rushjs with pnpm.  Our npm projects are currently on 6.14.7 (will be upgraded soon) and that version does not have the 'why' command.  I am getting this issue when doing a 'rush update':

ERROR  @storybook/react > @storybook/react-docgen-typescript-plugin: react-docgen-typescript@2.2.2 requires a peer of typescript@>= 4.3.x but version 3.9.7 was installed.

The problem appears to be here:  https://github.com/storybookjs/storybook/blob/main/app/react/package.json#L57

**Comment by dsanders1234** [comment]
It seems like storybook is using [react-docgen-typescript](https://github.com/styleguidist/react-docgen-typescript)
2.2.2, which forces typescript 4.3.x: https://github.com/styleguidist/react-docgen-typescript/blob/v2.2.2/package.json

**Comment by IanVS** [comment]
I wonder if you could use something like https://www.npmjs.com/package/npm-force-resolutions as a temporary measure until you're able to update your typescript version.

**Comment by dsanders1234** [comment]
I attempted to use pnpm overrides feature, but that didn't seem to work.  It could be because its a rushjs monorepo setup.  We don't even use the docgen feature, we use @microsoft/api-extractor and @uifabric/api-docs (fluentui).  The docgen package wasn't mature enough when we started.

**Comment by IanVS** [comment]
This has been fixed in https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.14
