### ISSUE TITLE
Storybook measure does not work on button buttons

### ISSUE THREAD

**Issue by RubyHuntsman** [storybookjs/storybook#17762]
**Describe the bug**
Storybook measure does not work on button buttons

**To Reproduce**
Add this following buttons to storybook story

`<button>Measure will work on this button</button>`
`<button disabled>Measure won't work on this button</button>`

**Comment by BikashSah999** [comment]
Hi @shilman @ndelangen  , the PR for this issue is ready for review. Could you please review it?

**Comment by shilman** [comment]
Boo-yah!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.3 containing PR #19985 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
