### ISSUE TITLE
isToolshown does not work in manager.js but works in preview.js for start-storybook

### ISSUE THREAD

**Issue by dsanders1234** [storybookjs/storybook#17760]
**Describe the bug**
The example on this page: https://storybook.js.org/docs/react/configure/features-and-behavior
shows isToolsshown, and this works when I build the storybook, but not when I run start-storybook (npm run).  When I move it to the preview.js parameters/options, it works.

**To Reproduce**
See above

**System**
 System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
  Binaries:
    Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.17.3 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.7 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 99.0.4844.74
    Edge: Spartan (44.19041.1266.0), Chromium (99.0.1150.39)

**Additional context**
We don't use yarn

**Comment by jonniebigodes** [comment]
@dsanders1234 thanks for reaching out to us with your issue. We appreciate it 🙏 ! I hope you don't mind, but I'm closing this issue as with the 7.0 release, the API option you've mentioned was officially deprecated, and we're no longer referencing it in the documentation.

Have a fantastic week.

Stay safe
