### ISSUE TITLE
React + Storybook + SCSS modules not working

### ISSUE THREAD

**Issue by FelipeZNascimento** [storybookjs/storybook#17768]
**Describe the bug**
Storybook doesn't build/run with suggested changes for SCSS compatibility with modules.
Edit: Just tested without modules and changing file extension from `css` to `scss` also breaks it

**To Reproduce**
Create a new React app with Typescript ([per React](https://create-react-app.dev/docs/adding-typescript/))
`npx create-react-app my-app --template typescript`

Add Storybook ([per Storybook](https://storybook.js.org/docs/react/get-started/install))
`npx sb init`

Add SCSS compatibility ([per Storybook](https://storybook.js.org/docs/react/configure/styling-and-css)) by using [SCSS preset](https://github.com/storybookjs/presets/tree/master/packages/preset-scss)

Here's the [repository](https://github.com/FelipeZNascimento/storybook-components).
After `npm run storybook`, this is the error I get:
```99% done plugins webpack-hot-middlewarewebpack built preview a32ead7bbf97dc5f4d7c in 8018ms
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: expected "{".
  ╷
2 │       import API from "!../../node_modules/style-loader/dist/runtime/injectStylesIntoStyleTag.js";
  │                                                                                                  ^
  ╵
  src\stories\button.module.scss 2:98  root stylesheet
    at processResult (C:\workspace\omegafox-components\node_modules\webpack\lib\NormalModule.js:758:19)
    at C:\workspace\omegafox-components\node_modules\webpack\lib\NormalModule.js:860:5
    at C:\workspace\omegafox-components\node_modules\loader-runner\lib\LoaderRunner.js:399:11
    at C:\workspace\omegafox-components\node_modules\loader-runner\lib\LoaderRunner.js:251:18
    at context.callback (C:\workspace\omegafox-components\node_modules\loader-runner\lib\LoaderRunner.js:124:13)
    at Object.loader (C:\workspace\omegafox-components\node_modules\sass-loader\dist\index.js:69:5)
    at runNextTicks (node:internal/process/task_queues:61:5)
    at processImmediate (node:internal/timers:437:9)
```

I've tried  `npx sb@next repro` but it didn't work:
![image](https://user-images.githubusercontent.com/24943990/159189987-6143ceef-11ab-49f5-a457-a40640490606.png)

**Comment by auri179** [comment]
Actually I have the 
    "ng-packagr": "^12.1.1",
    "sass": "^1.49.9",
    "sass-loader": "^12.6.0",
    "style-loader": "^3.3.1",
    "typescript": "~4.3.5"

I will try to downgrade the sass loader and keep you in touch... Thanks for the reply ;)

**Comment by auri179** [comment]
"sass": "^1.49.9",
    "sass-loader": "^10.2.1",
    "style-loader": "^3.3.1",
    "typescript": "~4.3.5"

After downgrade still same error

**Comment by Tino-F** [comment]
I'm also having this issue, was anyone able to figure out a solution?

**Comment by XavierOlland** [comment]
Similar issue around here...

**Comment by DisruptiveMind** [comment]
I have a workaround that may help until this is resolved. My project was bootstrapped with create react.

In your package.json add a script for `sass`
```javascript
{
  ...
  scripts: {
    "sass": "sass --watch ./src/styles/_index.scss ./.storybook/main.css"
  }
}
```

Then add `main.css` to `.storybook/preview.js`

```scss
import './main.css';
```

Run both `npm run sass` and `npm run storybook` or `yarn` appropriately in separate terminals.

**Comment by xiaozhiwen1998** [comment]
Similar issue around here...

**Comment by Urbana28** [comment]
@FelipeZNascimento @XavierOlland @xiaozhiwen1998 fixed this way ( .storybook/main.js ). The main point is that you have to setup webpackFinal inside of core object. I've tried with '@storybook/preset-scss' - no luck :( Hope that it'll help you
```
module.exports = {
  "stories": [
    "../src/**/*.stories.mdx",
    "../src/**/*.stories.@(js|jsx|ts|tsx)",
    "../src/core/components/**/*.stories.@(js|jsx|ts|tsx)"
  ],
  "addons": [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/addon-interactions",
    "@storybook/preset-create-react-app",
    "@storybook/preset-ant-design",
  ],
  "framework": "@storybook/react",
  "core": {
    "builder": "@storybook/builder-webpack5",
    webpackFinal: async (config, { configType }) => {
      // `configType` has a value of 'DEVELOPMENT' or 'PRODUCTION'
      // You can change the configuration based on that.
      // 'PRODUCTION' is used when building the static version of storybook.
  
      // Make whatever fine-grained changes you need
      config.module.rules.push({
        test: /\.scss$/,
        use: ['style-loader', 'css-loader', 'sass-loader'],
        include: path.resolve(__dirname, '../'),
      });
  
      // Return the altered config
      return config;
    },
  }
}
```

**Comment by PaulHaze** [comment]
Adding my voice to the discussion to say that I am also having pretty much the same issue with Nextjs/Tailwind. global Scss files are working fine, modules are not....

**Comment by spaceflora** [comment]
Similar problem here.
Setup project.
```
npx create-next-app@latest --typescript
cd app
npx storybook init
yarn run storybook
```
OK! Storybook starts normally.
Now let's config Sass.
```
yarn add --save-dev sass
yarn add --dev storybook-addon-next
yarn run storybook
```
OK! Storybook starts normally.
Now let's change our .css files to .scss files.
```
yarn run storybook
```
Not OK, errors!
```
ModuleParseError: Module parse failed: Unexpected token (2:5)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| html,
> body {
|   padding: 0;
|   margin: 0;
    at handleParseError
```
However:
```
npx next dev
```
OK, no problems and with working Sass (.scss)!

I've tried various configurations, also without the storybook-addon-next package, but the same errors remain.
I think I'm using webpack 5 in all cases. Please let me know if it's just me missing something.

**Comment by evan-colorkrew** [comment]
I'm sorry, I solved my issue by following the instructions on:
https://storybook.js.org/docs/react/builders/webpack#extending-storybooks-webpack-config

**Comment by spaceflora** [comment]
I changed the main.js configuration to use the webpackFinal found here. It's working!
https://storybook.js.org/docs/react/builders/webpack#extending-storybooks-webpack-config
I'm sorry for bothering, maybe someone can use it.

**Comment by PaulHaze** [comment]
@spaceflora After dicking around with this for what felt like eternity I came across this plugin:

https://github.com/RyanClementsHax/storybook-addon-next

and it solved EVERY problem I was having. It literally works right out the box, with css/scss/global styles AND modules. My main.js file now looks like this:

```
const path = require('path');

module.exports = {
  stories: ['../src/**/*.stories.mdx', '../src/**/*.stories.@(js|jsx|ts|tsx)'],
  staticDirs: ['../public'],
  addons: [
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    '@storybook/addon-interactions',
    'storybook-addon-next',
    '@storybook/addon-a11y',
  ],
  framework: '@storybook/react',
  core: {
    builder: '@storybook/builder-webpack5',
  },
  webpackFinal: (config) => {
    config.resolve.alias = {
      ...config.resolve?.alias,
      '@': [path.resolve(__dirname, '../src/'), path.resolve(__dirname, '../')],
    };
    config.resolve.roots = [
      path.resolve(__dirname, '../public'),
      'node_modules',
    ];
    return config;
  },
};
```

So if anyone is having trouble getting scss modules and tailwind working with Storybook then give this plugin a go...

**Comment by taw1313** [comment]
@Urbana28 
With your success in using SCSS what version of react are you using? 

Just a note in your main.js example looks like you have a cut and paste issue...
```
  "core": {
    "builder": "@storybook/builder-webpack5",
    webpackFinal: async (config, { configType }) => {
 ```
 shouldn't it be
 ```
   "core": {
      "builder": "@storybook/builder-webpack5",
    },
    webpackFinal: async (config, { configType }) => {
 ```

**Comment by assentorp** [comment]
Running Node 16.5.0 + Npm 7.19.1

I followed this step by step: https://github.com/storybookjs/presets/tree/master/packages/preset-scss but it didn't work. Only after I removed the line `"@storybook/preset-scss"`, from my `main.js` it worked. Really weird as it's what it says in the documentation...

My main.js now looks like this:
`module.exports = {
  stories: ["../src/**/*.stories.mdx", "../src/**/*.stories.@(js|jsx|ts|tsx)"],
  addons: [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/addon-interactions",
    "@storybook/preset-create-react-app",
  ],
  framework: "@storybook/react",
  core: {
    builder: "@storybook/builder-webpack5",
  },
};
`

My file is located in stories and is called `mycomp.scss` and is imported in `MyComp.jsx` as `import "./mycomp.scss";`

**Comment by MONTYYYYY** [comment]
I'm also having this issue, was anyone able to find a solution? I am using next js 12.

**Comment by xiaozhiwen1998** [comment]
> 
in preview.js add:
import '../src/styles/index.scss';

**Comment by MONTYYYYY** [comment]
> > 
> 
> in preview.js add: import '../src/styles/index.scss';

nope, does not work.

**Comment by MONTYYYYY** [comment]
this article helped: https://bitcoden.com/answers/using-kebab-case-css-classnames-in-css-or-sass-modules-when-using-next-js

**Comment by royrimachi** [comment]
I solved removing the configuration of package `storybook-addon-sass-postcss` in main.js.

**Comment by StillScripts** [comment]
> @spaceflora After dicking around with this for what felt like eternity I came across this plugin:
> 
> https://github.com/RyanClementsHax/storybook-addon-next
> 
> and it solved EVERY problem I was having. It literally works right out the box, with css/scss/global styles AND modules. My main.js file now looks like this:
> 
> ```
> const path = require('path');
> 
> module.exports = {
>   stories: ['../src/**/*.stories.mdx', '../src/**/*.stories.@(js|jsx|ts|tsx)'],
>   staticDirs: ['../public'],
>   addons: [
>     '@storybook/addon-links',
>     '@storybook/addon-essentials',
>     '@storybook/addon-interactions',
>     'storybook-addon-next',
>     '@storybook/addon-a11y',
>   ],
>   framework: '@storybook/react',
>   core: {
>     builder: '@storybook/builder-webpack5',
>   },
>   webpackFinal: (config) => {
>     config.resolve.alias = {
>       ...config.resolve?.alias,
>       '@': [path.resolve(__dirname, '../src/'), path.resolve(__dirname, '../')],
>     };
>     config.resolve.roots = [
>       path.resolve(__dirname, '../public'),
>       'node_modules',
>     ];
>     return config;
>   },
> };
> ```
> 
> So if anyone is having trouble getting scss modules and tailwind working with Storybook then give this plugin a go...

This solved my issues after 4 hours of pain. Unbelievable how badly documented Storybook is when it comes to Sass.

**Comment by zalash333** [comment]
`// .storybook/main.js

const path = require('path');

module.exports = {
  ...
  webpackFinal: async (config) => {
    config.module.rules.push(
      {
        test: /\.s(a|c)ss$/,
        include: path.resolve(__dirname, '../'),
        use: [
          'style-loader',
          {
            loader: 'css-loader',
            options: {
              modules: {
                auto: true,
                localIdentName: '[name]__[local]--[hash:base64:5]',
              },
            },
          },
          'sass-loader'
        ],
      },
    );
    return config;
  },
  ...
};`

works for me

**Comment by ArnaudGathy** [comment]
> 



> ```js
> // .storybook/main.js
> 
> const path = require('path');
> 
> module.exports = {
>   ...
>   webpackFinal: async (config) => {
>     config.module.rules.push(
>       {
>         test: /\.s(a|c)ss$/,
>         include: path.resolve(__dirname, '../'),
>         use: [
>           'style-loader',
>           {
>             loader: 'css-loader',
>             options: {
>               modules: {
>                 auto: true,
>                 localIdentName: '[name]__[local]--[hash:base64:5]',
>               },
>             },
>           },
>           'sass-loader'
>         ],
>       },
>     );
>     return config;
>   },
>   ...
> }; 
> ```
> 
> works for me

Can you detail your configuration please ? Do you use any storybook presets / addon ?

**Comment by zalash333** [comment]
> > 
> 
> > ```js
> > // .storybook/main.js
> > 
> > const path = require('path');
> > 
> > module.exports = {
> >   ...
> >   webpackFinal: async (config) => {
> >     config.module.rules.push(
> >       {
> >         test: /\.s(a|c)ss$/,
> >         include: path.resolve(__dirname, '../'),
> >         use: [
> >           'style-loader',
> >           {
> >             loader: 'css-loader',
> >             options: {
> >               modules: {
> >                 auto: true,
> >                 localIdentName: '[name]__[local]--[hash:base64:5]',
> >               },
> >             },
> >           },
> >           'sass-loader'
> >         ],
> >       },
> >     );
> >     return config;
> >   },
> >   ...
> > }; 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > works for me
> 
> Can you detail your configuration please ? Do you use any storybook presets / addon ?

```jsx 
const path = require('path');

module.exports = {
  "stories": [
    "../src/**/*.stories.mdx",
    "../src/**/*.stories.@(js|jsx|ts|tsx)"
  ],
  "addons": [
    "@storybook/addon-links",
    "@storybook/addon-essentials"
  ],
  webpackFinal: async (config, { configType }) => {
    config.module.rules.push(
      {
        test: /\.s(a|c)ss$/,
        include: path.resolve(__dirname, '../'),
        use: [
          'style-loader',
          {
            loader: 'css-loader',
            options: {
              modules: {
                auto: true,
                localIdentName: '[name]__[local]--[hash:base64:5]',
              },
            },
          },
          'sass-loader'
        ],
      },
    );

    return config;
  },
}
```
This is how my main.js file looks like. Nothing special

```jsx
import cls from './index.module.scss';
...
return (
    <div className={clsx(cls.wrapper, isError && cls.wrapper_error)}>
...
```
so I use

**Comment by rkrishnasanka** [comment]
Anything I can do here, even the next plugin isn't working for me

**Comment by mateuspiresl** [comment]
@assentorp's solution worked for me: I removed the `@storybook/preset-scss` addon from `main.js`.

**Comment by gabyrfp** [comment]
The above solution also worked for me!

**Comment by gabyrfp** [comment]
I however, need both `@storybook/preset-scss` and `storybook-addon-next`. Is there any workaround to get these both to work together?

**Comment by rkrishnasanka** [comment]
So I completely skipped over to the nextjs with the latest beta versions of storybook. Its all going good now with the framework rewrite. Here's a [template](https://github.com/rkrishnasanka/nextjs-template) with the [instructions](https://github.com/rkrishnasanka/nextjs-template#temaplate-setup-instructions)

**Comment by Ronald-13** [comment]
For webpack 4, downgrade the versions to,

yarn add -D @storybook/preset-scss css-loader@5.2.6 sass sass-loader@10.1.1 style-loader@2.0.0

This worked for me

**Comment by shilman** [comment]
@Integrayshaun is this something you can help resolve?

**Comment by Integrayshaun** [comment]
To solve @FelipeZNascimento's original issue.

If you're using create-react-app with `@storybook/preset-create-react-app` you should be able remove preset-sass all together as `react-scripts@2.0.0` and higher can handle SCSS out of the box which `@storybook/preset-create-react-app` replicates

**Comment by DEBorodina** [comment]
I had the same issue with "next": "13.4.4", and  "storybook": "^7.0.18"  while using scss modules
What helped me:
1) remove ALL styles addons and loaders ('style-loader', 'css-loader', 'sass-loader',@storybook/preset-scss, etc.)
2) delete node_modules and yarn.lock
3) install all dependensies again (yarn install)
I have no clue why it worked but it did.

**Comment by shilman** [comment]
For anybody coming to this issue on 7.0+, please take a look at https://storybook.js.org/addons/@storybook/addon-styling which is our recommended way to deal with styling integrations.

**Comment by Kris-AD** [comment]
FWIW, I discovered that in my codebase this error was being caused by multiple `style-loader`s being applied in the webpack config. This was due to me adding a custom css rule using `style-loader` without considering that there were default rules setup by storybook. The fix was to modify the existing rule so that it's mutually exclusive:

```
// in .storybook/webpack.config.js
module.exports = function ({ config }) {

  // modify existing storybook CSS rule to exclude our lazy loaded CSS
  config.module.rules.find(({ test }) => test.toString() === "/\\.css$/").exclude = /\.lazy\.css$/;
  
  // add storybook support for lazy loaded css styles
  config.module.rules.push({
    test: /\.lazy\.css$/,
    use: [
      {
        loader: "style-loader",
        options: {
          injectType: "lazyStyleTag"
        },
      },
      "css-loader",
    ],
  });

  return config;
};
```

**Comment by MKhodagholi** [comment]
most of the comments I saw used @storybook/preset-scss as scss-loader, please note that you should not use this with your custom loader, In Summary main.js should like this 

const path = require("path");

function getAbsolutePath(value) {
  return path.dirname(require.resolve(path.join(value, "package.json")));
}

const toPath = (_path) => path.join(process.cwd(), _path);

module.exports = {
  stories: ["../src/**/*.stories.mdx", "../src/**/*.stories.@(js|jsx|ts|tsx)"],
  addons: [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/addon-interactions",
    "@storybook/addon-styling-webpack",
    "@storybook/manager-api",
    "@storybook/theming",
    "storybook-dark-mode",
  ],
  framework: getAbsolutePath("@storybook/react"),
  core: {
    builder: "@storybook/builder-webpack5",
  },
  webpackFinal: async (config, { configType }) => {
    config.module.rules.push({
      test: /\.module\.s(a|c)ss$/,
      use: [
        "style-loader",
        {
          loader: "css-loader",
          options: {
            modules: {
              localIdentName:
                configType === "PRODUCTION"
                  ? "[local]__[hash:base64:5]"
                  : "[name]__[local]__[hash:base64:5]",
              exportLocalsConvention: "camelCase",
            },
            sourceMap: true,
          },
        },
        {
          loader: "sass-loader",
          options: {
            sourceMap: true,
          },
        },
      ],
      include: path.resolve(__dirname, "../"),
    });

    return config;
  },
};

**Comment by mrbinky3000** [comment]
For what it's worth... I read here https://github.com/storybookjs/storybook/issues/11663#issuecomment-666228381 that one solution is to make sure you don't install a different version of css-loader than the one storybook uses.   Storybook already has a loader set up for css.  If you install a different version of css-loader, and use that version in your customized webpack config,  the two css-loaders sometimes conflict.  

I updated my config to look like.

```javascript
config.module.rules.push({
  test: /\.scss$/,
  use: ['style-loader', 'css-loader', 'sass-loader'],
  include: path.resolve(__dirname, '../'),
});
```

Then I uninstalled my `css-loader` and ran the command `npm ls css-loader` to see the version(s) of css-loader in the project.

```
├─┬ @storybook/react-webpack5@8.3.6
│ └─┬ @storybook/builder-webpack5@8.3.6
│   └── css-loader@6.11.0
```

I tried running it without installing css-loader but webpack complained that it could not be found... even though it definitely is in the node_modules folder.  So I installed the same version as the one used by storybook.

```
├─┬ @storybook/react-webpack5@8.3.6
│ └─┬ @storybook/builder-webpack5@8.3.6
│   └── css-loader@6.11.0 deduped
└── css-loader@6.11.0
```

And that worked for me.

**Comment by TommyR22** [comment]
@retrofox this issue seems a breaking change of `css-loader`. I resolved using the 6.x behavior [here](https://github.com/webpack-contrib/css-loader/blob/master/CHANGELOG.md#-breaking-changes).
```
namedExport: false,
exportLocalsConvention: 'as-is',
```
