### ISSUE TITLE
Very slow and regular double builds, how to debug?

### ISSUE THREAD

**Issue by dietergeerts** [storybookjs/storybook#17772]
**Describe the bug**
Our storybook only has like 20 stories, and is becoming very slow, and we regularly see double builds:
![image](https://user-images.githubusercontent.com/7393706/159255368-b44133db-1cc0-401d-9229-a4d692eb1a95.png)
The `webpack building...` comes up as soon as we save a file, then it stays like that for at least 20seconds before the next line is given, which seems like the actual building. So it seems like there is something that is taking lots of time before the actual build. Sometimes, this step happens twice. I would like to debug this more and see more logging of what's going on, but the webpack `stats.logging` and the Storybook `--loglevel` doesn't do anything for this.

**To Reproduce**
Please create a reproduction by running `npx sb@next repro` and following the instructions. Read our [documentation](https://storybook.js.org/docs/react/contribute/how-to-reproduce) to learn more about creating reproductions.
Paste your repository and deployed reproduction here. We prioritize issues with reproductions over those without.

I would like to debug first myself a bit more, to understand more of what is going on under the hood before creating a repro. I can then update this ticket with my findings, and maybe I can get it solved, maybe not, but the info can be valuable to others.

**System**
Please paste the results of `npx sb@next info` here.

**Additional context**

I worked with several versions of storybook now, and I have to say that all version have this problem, a few stories are OK, but when you add more stories, like 10-20, or even more, it becomes sooooo slow, slower than you would just configure webpack yourself to run all the stories. I know that Storybook does some extra things around webpack, and probably, this reduces performance, or it's build in such a way that stories should be written in a certain way to have good performance, and we are not doing this? I also don't find anything in the docs about this, so it should not matter?

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
