### ISSUE TITLE
Update react-syntax-hightlighter to v15.5.0 for fixing XSS vulnerability issue by prismjs

### ISSUE THREAD

**Issue by oti** [storybookjs/storybook#17784]
**Is your feature request related to a problem? Please describe**

@storybook/components which depends on react-syntax-highlighter has a XSS vulnerability issue by prismjs.
It was resolved in react-syntax-highlighter v15.5.0
https://github.com/react-syntax-highlighter/react-syntax-highlighter/releases/tag/15.5.0

**Describe the solution you'd like**

Update react-syntax-hightlighter to v15.5.0

**Comment by curtvict** [comment]
It would be great if this could be included in the next minor.

https://github.com/PrismJS/prism/pull/3341 was included in their v1.27.0 release.

**Comment by tkdphoenix** [comment]
It seems that prismjs is a devDependency. Is that correct? If so, you can move it to devDependencies in package.json and it wouldn't be a security vuln for everyone, but you would want to update it ASAP, of course.

**Comment by curtvict** [comment]
Seemed like less work to just bump the version, so I did.

**Comment by shilman** [comment]
Ooh-la-la!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-alpha.10 containing PR #18009 that references this issue. Upgrade today to the `@future` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by curtvict** [comment]
Thanks @shilman!
