### ISSUE TITLE
Story hoisting is not working for docs page when Title and Default export name are same

### ISSUE THREAD

**Issue by rishabh1403** [storybookjs/storybook#17792]
**Describe the bug**
According to the storybook docs (https://storybook.js.org/docs/react/writing-stories/naming-components-and-hierarchy), story hoisting works if the component has the same name as the title. To make this work, one has to export the story with the exact same name as the component (the one that's the last part of the title).
However, the current story described in following code isn't hoisting the default story named `Icon` but is hoisting the `Colors` story in the docs page

**To Reproduce**
Consider the following storybook file
```
import { Story, Meta } from "@storybook/react/types-6-0";
import React from "react";

import IconComponent, { Props } from "ui/Icon";

export default {
  title: "ui/Icon",
  component: IconComponent,
} as Meta;

const Template: Story<Props> = (args) => <IconComponent {...args} />;

export const Icon = Template.bind({});
Icon.args = {
  name: "search",
  size: "2xl",
};

export const Colors: () => JSX.Element = () => {
  return (
    <div>
      <Icon {...(Icon.args as Props)} color="green" />
      <Icon {...(Icon.args as Props)} color="red" />
      <Icon {...(Icon.args as Props)} color="yellow" />
      <Icon {...(Icon.args as Props)} color="indigo" />
      <Icon {...(Icon.args as Props)} color="white" />
    </div>
  );
};

```

This should have the default Icon story at the top in the docs page, but currently the Colors story is hoisted in the docs page.

![image](https://user-images.githubusercontent.com/10906358/159883265-0a89688c-eaaa-4ac5-97a5-28baa7c492fe.png)

**System**
```
  System:
    OS: macOS 12.0.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Binaries:
    Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm
  Browsers:
    Chrome: 99.0.4844.83
    Safari: 15.1
  npmPackages:
    @storybook/addon-essentials: ^6.4.19 => 6.4.19
    @storybook/builder-webpack5: ^6.4.19 => 6.4.19
    @storybook/manager-webpack5: ^6.4.19 => 6.4.19
    @storybook/react: ^6.4.19 => 6.4.19
```

**Additional context**
I have a similar story for Badge component and the doc hoisting works perfectly there. Not sure if I am missing something related to hoisting here.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
