### ISSUE TITLE
Toolbar - Display value of selected item

### ISSUE THREAD

**Issue by cocco3** [storybookjs/storybook#17790]
**Is your feature request related to a problem? Please describe**
- Easily be able to tell what values are selected 

**Describe the solution you'd like**
- Add a `dynamicTitle` config for globalTypes toolbar to enable this feature

**Describe alternatives you've considered**
- N/A

**Are you able to assist to bring the feature to reality?**
- Yes

**Comment by jbarreiros** [comment]
Extending this to other standard toolbar buttons, like Background, would be really useful too.

**Comment by shilman** [comment]
Huzzah!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-beta.1 containing PR #17789 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
