### ISSUE TITLE
Addon: storysource won't load unless user click on the tab first

### ISSUE THREAD

**Issue by totszwai** [storybookjs/storybook#17802]
**Describe the bug**
If you disable all the tabs by default and only have the Story (storysource) tab shown, storysource will **not** load/show the story unless you manually click on the tab first.

**To Reproduce**
Create any story, put the following in the `parameters`

```
  actions: {
    disable: true
  },
  controls: {
    disable: true
  },
```

I'm not sure if this has anything to do with the addon loading order, but this is my loading order:

```
module.exports = {
  stories: ['../src/**/*.stories.mdx', '../src/**/*.stories.@(js|jsx|ts|tsx)'],
  addons: [
    '@storybook/preset-create-react-app',
    '@storybook/addon-essentials',
    {
      name: '@storybook/addon-storysource',
      options: {
        loaderOptions: {
          injectStoryParameters: false
        }
      }
    },
    '@storybook/addon-toolbars',
    '@storybook/addon-links',
    'storybook-addon-designs',
    'storybook-react-i18next'
  ],
```

**System**

Environment Info:

  System:
    OS: Linux 5.13 Ubuntu 21.10 21.10 (Impish Indri)
    CPU: (16) x64 Intel(R) Xeon(R) Silver 4108 CPU @ 1.80GHz
  Binaries:
    Node: 14.19.1 - ~/.config/nvm/versions/node/v14.19.1/bin/node
    npm: 6.14.16 - ~/.config/nvm/versions/node/v14.19.1/bin/npm
  Browsers:
    Chrome: 99.0.4844.82
    Firefox: 98.0.2
  npmPackages:
    @storybook/addon-actions: ^6.4.19 => 6.4.19 
    @storybook/addon-essentials: ^6.4.19 => 6.4.19 
    @storybook/addon-interactions: ^6.4.19 => 6.4.19 
    @storybook/addon-links: ^6.4.19 => 6.4.19 
    @storybook/addon-storysource: ^6.4.19 => 6.4.19 
    @storybook/preset-create-react-app: ^3.2.0 => 3.2.0 
    @storybook/react: 6.4.19 => 6.4.19 
    @storybook/testing-library: 0.0.9 => 0.0.9

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
