### ISSUE TITLE
UI: Fix fullscreen mobile mode

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#17808]
As of SB6.4, Storybook's "fullscreen" UI (specified by the [`full` URL parameter](https://storybook.js.org/docs/react/configure/features-and-behavior#configuring-through-url-parameters)) for desktop looks like this:

<img width="784" alt="Demo___AccountForm_-_Standard_⋅_Storybook" src="https://user-images.githubusercontent.com/488689/160384174-46b36a75-c037-4502-9668-6b698fe9cc7f.png">

In contrast, the mobile view (600px or narrower) looks like this:

<img width="584" alt="Demo___AccountForm_-_Standard_⋅_Storybook" src="https://user-images.githubusercontent.com/488689/160384853-626b8565-75a9-45b1-8ca0-b622f2c6f37f.png">

This contains two bugs:
- [ ] The "X" toolbar UI is missing
- [ ] The sidebar/canvas/addons nav UI is added

**Comment by LucaCras** [comment]
Hey @shilman, could I pick this one up?

**Comment by shilman** [comment]
@LucaCras absolutely. we need to get this going in the next week or two, are you ok with that? @JonathanKolnik can help expedite if needed. thanks so much! 🙏

**Comment by shilman** [comment]
Olé!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-alpha.58 containing PR #17873 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
