### ISSUE TITLE
argTypes table doesn't display single action unless accompanied by another control

### ISSUE THREAD

**Issue by zoharlevin** [storybookjs/storybook#17805]
When argTypes contains only a single action the table is not displayed, unless another control is added to the argTypes.

for this code:
```
export default {
  title: 'Components/Accordion',
  component: Accordion,
  argTypes: {
    onChange: {
      action: 'changed',
      description: 'The callback invoked when accordion items are expanded or collapsed',
      type: {
        summary: '(expandedIndex: number) => void',
      },
      table: {
        category: 'Events',
      },
    },
  },
  args: {
    onChange: () => null,
  },
} as Meta<typeof Accordion>;
```
the table is empty:
<img width="1061" alt="screenshot_no_args" src="https://user-images.githubusercontent.com/16067177/160274146-94aa5bfd-c116-4c5e-9ce0-c093d2d113bd.png">

but for this code - added the `something` arg:
```
export default {
  title: 'Components/Accordion',
  component: Accordion,
  argTypes: {
    something: {
      control: 'number'
    },
    onChange: {
      action: 'changed',
      description: 'The callback invoked when accordion items are expanded or collapsed',
      type: {
        summary: '(expandedIndex: number) => void',
      },
      table: {
        category: 'Events',
      },
    },
  },
  args: {
    something: 1,
    onChange: () => null,
  },
} as Meta<typeof Accordion>;
```
the table displays both args:
<img width="1054" alt="screenshot_shows_args" src="https://user-images.githubusercontent.com/16067177/160274196-432b1663-f9eb-446c-a537-a0d352b14ff0.png">

**System**
```
Environment Info:

  System:
    OS: macOS 12.3
    CPU: (10) x64 Apple M1 Max
  Binaries:
    Node: 14.18.2 - ~/.nvm/versions/node/v14.18.2/bin/node
    Yarn: 1.22.18 - ~/.nvm/versions/node/v14.18.2/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.2/bin/npm
  Browsers:
    Chrome: 99.0.4844.84
    Safari: 15.4
```

**Comment by AmirTugi** [comment]
I'm having the same issue :/
Only workaround for now is indeed to coerce another prop with a control.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
