### ISSUE TITLE
`Interactions`-panel breaks styling on subsequent panels

### ISSUE THREAD

**Issue by Gilstroem** [storybookjs/storybook#17818]
**Describe the bug**
When rendering any custom addon _after_ the interactions panel, they are not styled appropriately. Examples:

### Pictures

When the interaction panel is _before_ other addons (it is **not** styled appropriately):
<img width="1003" alt="Screenshot 2022-03-29 at 10 41 08" src="https://user-images.githubusercontent.com/16057281/160584183-af357507-54e7-4670-8a83-fe8c8d7445e3.png">

When the interaction panel is _after_ other addons (it is styled appropriately):
<img width="1005" alt="Screenshot 2022-03-29 at 10 36 59" src="https://user-images.githubusercontent.com/16057281/160584458-5a3e8eee-b04a-416b-879d-4169e195cae0.png">

The ordering is determined by the order in `main.js -> addons: []`.

### DOM 

It seems that the issue stems from the `panel-tab-content` styling its first-child, however, the interactions panel is not removed when it is not active, thereby staying the first child. This is the relevant part of the DOM when it is not rendering correctly - i.e. when another panel is selected/active, but interactions lingers:

```html
<div id="panel-tab-content" class="css-1fst6u6">
  <div style="transform: translateX(0px)" hidden="">
    <div></div>
    <div class="css-ic55a0">
      <div class="css-1vg6q84">No interactions found</div>
      <div class="css-0">
        <a
          href="https://github.com/storybookjs/storybook/blob/next/addons/interactions/README.md"
          target="_blank"
          class="css-1fdob6g"
          ><span class="css-1mjgzsp"
            >Learn how to add interactions to your story<svg
              viewBox="0 0 1024 1024"
              class="css-ha8kg"
            >
              <path
                d="M768.072 514.022c0 10.236-3.904 20.47-11.712 28.282l-344.098 344.156c-15.62 15.624-40.946 15.624-56.568 0.006-15.622-15.622-15.624-40.948-0.006-56.568l315.82-315.876-315.868-315.922c-15.618-15.624-15.618-40.952 0.004-56.568 15.624-15.62 40.95-15.618 56.57 0.006l344.144 344.204c7.81 7.81 11.714 18.044 11.714 28.28z"
                class="css-kqzqgg"
              ></path></svg></span
        ></a>
      </div>
    </div>
  </div>
  <div style="transform: translateX(0px)">
    <textarea
      style="
        width: 100%;
        height: 100%;
        border: 2px solid green;
        outline: currentcolor none medium;
        resize: none;
        overflow: scroll;
      "
    >
{
    <!-- my data here -->
  }</textarea
    >
  </div>
</div>
```

**Additional context**
- Other panels do not cause this issue,
- It seems that the interactions panel is rendered differently from other addon panels, with [`match`, see here](https://github.com/storybookjs/storybook/blob/f09053cd8f28737e7b278ac80da6bb76e970ac63/addons/interactions/src/register.tsx#L18). Other addons (and our custom addons) are rendered via the [`render`-attribute, see here](https://github.com/storybookjs/storybook/blob/f09053cd8f28737e7b278ac80da6bb76e970ac63/addons/jest/src/register.tsx#L10).

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).

**Comment by Kamilius** [comment]
@Gilstroem 
In case someone will need this.
Had the same issue in Storybook 6.5. When rendering a custom panel with `render`, it accepts `props.active`. So you can then decide either to return a component when it's `true` or a `null` when it's `false.
