### ISSUE TITLE
Docs Page does not render primary story by order

### ISSUE THREAD

**Issue by mockingjet** [storybookjs/storybook#17824]
**Describe the bug**

I use CSF to write stories, and start with `Default` story, and then `Dark` story as the picture shows

![image](https://user-images.githubusercontent.com/32839503/160801518-d913c607-cb77-4b0a-b8e1-cfeacd2ce4bc.png)

You can see it has correct order in the left navigation, but wrong order in the docs page ( it should use `Default` story as the first showcase )

I use Vue3 with Vite-builder:

"@storybook/vue3": "^6.4.19"
"storybook-builder-vite": "^0.1.21"
"vite": "^2.8.4"
 "vue": "^3.2.31"

**Comment by awacode21** [comment]
i am experiencing the same issue

**Comment by mockingjet** [comment]
> i am experiencing the same issue

I found it's been fixed with version 6.4.20
