### ISSUE TITLE
Replacing DocsPage doesn't work

### ISSUE THREAD

**Issue by younho9** [storybookjs/storybook#17836]
**Describe the bug**

Version: 6.4(latest)
Framework: React, Vue

Cannot [Replacing DocsPage](https://storybook.js.org/docs/react/writing-docs/docs-page#replacing-docspage)
- Cannot [remove `docsPage`](https://storybook.js.org/docs/react/writing-docs/docs-page#with-null-to-remove-docs)
- Cannot [use MDX for documentation](https://storybook.js.org/docs/react/writing-docs/docs-page#with-mdx-documentation)

**To Reproduce**
Please create a reproduction by running `npx sb@next repro` and following the instructions. Read our [documentation](https://storybook.js.org/docs/react/contribute/how-to-reproduce) to learn more about creating reproductions.
Paste your repository and deployed reproduction here. We prioritize issues with reproductions over those without.

Repository : https://github.com/younho9/reproduce-storybook-replace-docs-page/tree/main
Deployed reproduction : https://6245706c96372a004ad376ea-gifzirwnar.chromatic.com/

**System**
Please paste the results of `npx sb@next info` here.

```
Environment Info:

  System:
    OS: macOS 12.2.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 3.2.0 - /usr/local/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
  Browsers:
    Chrome: 99.0.4844.84
    Edge: 99.0.1150.55
    Firefox: 93.0
    Safari: 15.3
  npmPackages:
    @storybook/addon-actions: ^6.5.0-alpha.52 => 6.5.0-alpha.52 
    @storybook/addon-docs: ^6.5.0-alpha.52 => 6.5.0-alpha.52 
    @storybook/addon-essentials: ^6.5.0-alpha.52 => 6.5.0-alpha.52 
    @storybook/addon-interactions: ^6.5.0-alpha.52 => 6.5.0-alpha.52 
    @storybook/addon-links: ^6.5.0-alpha.52 => 6.5.0-alpha.52 
    @storybook/react: ^6.5.0-alpha.52 => 6.5.0-alpha.52 
    @storybook/testing-library: ^0.0.9 => 0.0.9 
```

**Additional context**

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
