### ISSUE TITLE
After a new build, I see a loading spinner

### ISSUE THREAD

**Issue by rwieruch** [storybookjs/storybook#17838]
It happens quite often for my [Storybook](https://react-table-library.com/) to show a loading spinner in the browser whenever there is a new build:

![Screenshot 2022-03-31 at 12 44 30](https://user-images.githubusercontent.com/2479967/161037788-4c9914ab-713c-49b1-9fb4-dedeb59ace50.jpg)

Only when I change browser or open the browser in incognito it goes away. So it may be some caching issue, but I am not sure where and how to fix it.

On my Linux machine, I built storybook the following way:

```
"storybook:build": "build-storybook .storybook .storybook/static -o dist",
```

Here you can access the source code too: https://github.com/table-library/react-table-library

I am using `"6.5.0-alpha.41` but I noticed this behavior in a previuous stable version too.

--------

When I check the network tab, I can see that some hashed vendor files are returned with a 404 HTTP. 

![Screenshot 2022-03-31 at 12 51 02](https://user-images.githubusercontent.com/2479967/161039205-76a57bf0-1368-41c2-ac46-7ee89148258b.jpg)

When I disable the cache via the network tab, the (new?) file gets loaded properly:

![Screenshot 2022-03-31 at 12 51 25](https://user-images.githubusercontent.com/2479967/161039275-aeb71b10-3c11-4bef-b48b-734fdeae61f9.jpg)

When I uncheck the box again, I get the 404 with the loading spinner again.

-------

FWIW I serve Storybook via nginx on a Linux machine with the following configuration:

```
server {
	root /var/www/react-table-library.com/html/dist;

	# Add index.php to the list if you are using PHP
	index index.html index.htm index.nginx-debian.html;

	server_name react-table-library.com www.react-table-library.com;

	location / {
		# First attempt to serve request as file, then
		# as directory, then fall back to displaying a 404.
		try_files $uri $uri/ =404;
	}

    listen [::]:443 ssl; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/react-table-library.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/react-table-library.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
    if ($host = www.react-table-library.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = react-table-library.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


	listen 80;
	listen [::]:80;

	server_name react-table-library.com www.react-table-library.com;
    return 404; # managed by Certbot
}
```

**Comment by rwieruch** [comment]
When I check the network tab, I can see that some hashed vendor files are returned with a 404 HTTP. 

![Screenshot 2022-03-31 at 12 51 02](https://user-images.githubusercontent.com/2479967/161039205-76a57bf0-1368-41c2-ac46-7ee89148258b.jpg)

When I disable the cache via the network tab, the (new?) file gets loaded properly:

![Screenshot 2022-03-31 at 12 51 25](https://user-images.githubusercontent.com/2479967/161039275-aeb71b10-3c11-4bef-b48b-734fdeae61f9.jpg)

When I uncheck the box again, I get the 404 with the loading spinner again.

**Comment by ruoqianfengshao** [comment]
@rwieruch maybe fix your nginx conf leading to work

from
```txt
root /var/www/react-table-library.com/html/dist;
```

to 

```txt
root /var/www/react-table-library.com/html/dist/;
```

the `iframe.html` need to specify the root path.


And this conf worked for me:

```conf
server {
    listen       80;
    server_name  localhost;
    root   /usr/share/nginx/html/storybook-static/;

    gzip on;
    gzip_min_length   2k;
    gzip_buffers      4 16k;
    gzip_http_version 1.0;
    gzip_comp_level   3;
    gzip_types        text/plain application/javascript application/x-javascript text/css application/xml text/javascript application/x-httpd-php image/jpeg image/gif image/png;
    gzip_vary on;

    client_max_body_size 50m;

    location ~ ^.*\.(html|css|js|png|jpg|jpeg) {
    }

    location = / {
       index /index.html;
       try_files /index.html = 404;
    }
}

```

**Comment by rwieruch** [comment]
Thanks @ruoqianfengshao I will check that out!

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
