### ISSUE TITLE
Storybook-6.5.0-alpha.54 Docs Not Working

### ISSUE THREAD

**Issue by HamSungJun** [storybookjs/storybook#17857]
**Describe the bug**
<img width="2558" alt="image" src="https://user-images.githubusercontent.com/26132543/161377254-bf911fc8-fc9e-4810-8d01-6b4a12b274b0.png">

```
Uncaught TypeError: includeConditionalArg is not a function
    at index-7209f724.js?v=dc5d38ca:2073:761
    at index-7209f724.js?v=dc5d38ca:1639:231
    at basePickBy$1 (index-7209f724.js?v=dc5d38ca:1573:167)
    at pickBy (index-7209f724.js?v=dc5d38ca:1639:179)
    at ArgsTable (index-7209f724.js?v=dc5d38ca:2073:631)
    at renderWithHooks (react-dom.development.js:14985:18)
    at mountIndeterminateComponent (react-dom.development.js:17811:13)
    at beginWork (react-dom.development.js:19049:16)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:3945:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:16)
```

**To Reproduce**
Please create a reproduction by running `npx sb@next repro` and following the instructions. Read our [documentation](https://storybook.js.org/docs/react/contribute/how-to-reproduce) to learn more about creating reproductions.
Paste your repository and deployed reproduction here. We prioritize issues with reproductions over those without.

**System**
Please paste the results of `npx sb@next info` here.
```
Environment Info:

  System:
    OS: macOS 12.3.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.18 - ~/.yarn/bin/yarn
    npm: 8.3.0 - ~/.nvm/versions/node/v16.13.1/bin/npm
  Browsers:
    Chrome: 99.0.4844.84
    Edge: 100.0.1185.29
    Firefox: 96.0.2
    Safari: 15.4
  npmPackages:
    @storybook/addon-actions: ^6.5.0-alpha.54 => 6.5.0-alpha.54 
    @storybook/addon-essentials: ^6.5.0-alpha.54 => 6.5.0-alpha.54 
    @storybook/addon-interactions: ^6.5.0-alpha.54 => 6.5.0-alpha.54 
    @storybook/addon-links: ^6.5.0-alpha.54 => 6.5.0-alpha.54 
    @storybook/addon-postcss: ^2.0.0 => 2.0.0 
    @storybook/builder-vite: ^0.1.22 => 0.1.22 
    @storybook/react: ^6.5.0-alpha.54 => 6.5.0-alpha.54 
    @storybook/testing-library: ^0.0.9 => 0.0.9 
```

**Additional context**

**Comment by IanVS** [comment]
The function seems to be added in this draft PR: https://github.com/ComponentDriven/csf/pull/36.  Because of the various canary versions of @storybook/csf, I have a hard time determining what needs to be done to actually fix the issue (I'm seeing a similar problem in a repo I'm working in).

**Comment by IanVS** [comment]
@HamSungJun I was able to resolve this by deleting my `package-lock.json` and installing the latest alpha versions of storybook.  I think I just had a version mismatch somewhere, and I bet you might as well.

**Comment by HamSungJun** [comment]
@IanVS I'll Try It, Thanks.

**Comment by HamSungJun** [comment]
Storybook Docs Working in `^6.5.0-alpha.59` Closed Issue
