### ISSUE TITLE
Documentation for Web Components is missing its `FeatureSnippets`

### ISSUE THREAD

**Issue by Peeja** [storybookjs/storybook#17856]
**Describe the bug**
On the documentation pages which are customized per framework, the `FeatureSnippets` includes aren't working for `web-components`. See:

* Install Storybook
  * [Installation Command](https://storybook.js.org/docs/web-components/get-started/install)
  * [Troubleshooting](https://storybook.js.org/docs/web-components/get-started/install#troubleshooting)
* Controls
  * [Choosing the control type](https://storybook.js.org/docs/web-components/essentials/controls#choosing-the-control-type)

**To Reproduce**

1. Open the pages linked above.
2. See that the framework-specific documentation sections are missing from the page.

**System**
N/A

**Additional context**

It looks like `web-components` is the only framework with a dash in its name. Perhaps that's what's causing it to fail to match?

**Comment by jonniebigodes** [comment]
@Peeja thanks for bringing this to our attention, but we're aware of it and I've created an issue in the [frontpage repo](https://github.com/storybookjs/frontpage/issues/228) to address it. Sorry if it hasn't been addressed yet 🙏 , we'll be looking into it and see what's happening!

Hope you have a great weekend!

Stay safe

**Comment by kylegach** [comment]
This has been fixed.
