### ISSUE TITLE
Storybook CLI uses yarn to install eslintPlugin, even when --use-npm is used

### ISSUE THREAD

**Issue by bartenra** [storybookjs/storybook#17870]
When I run 

```
npx sb init --builder @storybook/builder-vite --use-npm
```

At some point I get this question:

```
✔ Do you want to run the 'eslintPlugin' fix on your project? … 
```

However, when I choose 'yes', it uses yarn to install it.

**Comment by shilman** [comment]
Zoinks!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.19 containing PR #20428 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
