### ISSUE TITLE
opening static storybook does not load stories

### ISSUE THREAD

**Issue by yoanne2x** [storybookjs/storybook#17884]
**Describe the bug**

- build storybook statically, 
- open index.html and an error is displayed in left-hand column: "Oh no! Something went wrong loading this Storybook. [View error ]() [View docs](https://storybook.js.org/docs)"

**To Reproduce**

- npm init vite@latest sb-static --template react-ts
- cd sb-static
- npm install
- npx sb init --builder @storybook/builder-vite
- apply workaround for: https://github.com/storybookjs/storybook/issues/17852 and set "features: { storyStoreV7: true }" in main.js
- npm run build-storybook
- open generated index.html in storybook-static using chrome

the error above will be displayed, the console log will have:

Access to fetch at 'file:///Users/yoann/workspace/projects/gw/new-web/gw-web-ui/packages/sb-static/storybook-static/stories.json' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, chrome-untrusted, https.
stories.json:1          Failed to load resource: net::ERR_FAILED
iframe.html?id=*&viewMode=story:333 unable to connect to top frame for connecting dev tools
(anonymous) @ iframe.html?id=*&viewMode=story:333
iframe.html:425 Access to script at 'file:///assets/iframe.0a7c9221.js' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, chrome-untrusted, https.
/assets/iframe.0a7c9221.js:1          Failed to load resource: net::ERR_FAILED
/assets/iframe.7ee421ea.css:1          Failed to load resource: net::ERR_FILE_NOT_FOUND

**System**

Environment Info:

  System:
    OS: macOS 12.3.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Binaries:
    Node: 14.19.1 - ~/.nvm/versions/node/v14.19.1/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.16 - ~/.nvm/versions/node/v14.19.1/bin/npm
  Browsers:
    Chrome: 100.0.4896.75
    Safari: 15.4

**Additional context**

**Comment by fox-john** [comment]
I have same problem, with vite and storybook for vue3.
![image](https://user-images.githubusercontent.com/1273438/164251265-bb250b6f-7904-4f67-be57-43437cbf8a75.png)

**Comment by IanVS** [comment]
>open generated index.html in storybook-static using chrome

You cannot just open the files directly, they need to be served by a webserver.  Try using:

```
npx http-server storybook-static
```

**Comment by Pickra** [comment]
@IanVS 
`npx http-server storybook-static` worked like a charm, THANK YOU!

Any chance of adding this to the docs?
