### ISSUE TITLE
Dynamic story args are not working as expected

### ISSUE THREAD

**Issue by theolavaux** [storybookjs/storybook#17900]
**Describe the bug**
Dynamic story args are not found

I recently upgraded my Nuxt 2 project to use Yarn 2 and tweak some dependencies and I looks like Storybook doesn't work with dynamic props as it used to.

Here are the packages that I have installed

    "@storybook/addon-essentials": "6.4.19",
    "@storybook/addon-postcss": "2.0.0",
    "@nuxtjs/storybook": "4.3.0",

**LayoutFooter.stories.mdx**

    import { Meta, Story, Canvas } from '@storybook/addon-docs';
    import LayoutFooter from '~/components/layout/LayoutFooter';
    
    <Meta title="Layout/LayoutFooter" component="{LayoutFooter}" />
    
    # Footer
    
    `Footer` component
    
    ## Props
    
    <ArgsTable of={LayoutFooter} />
    
    ## Example
    
    export const Template = (_args, { argTypes }) => ({
      props: Object.keys(argTypes),
      template: `<LayoutFooter :logo="logo" />`,
      components: { LayoutFooter },
    });
    
    Footer
    
    <Canvas>
      <Story name="Default" args={{ logo: 'img/logo.svg' }}>
        {Template.bind({})}
      </Story>
    </Canvas>

Also tried

```
export const Template = (_args, { argTypes }) => ({
  props: Object.keys(argTypes),
  template: `<LayoutFooter v-bind="$props" />`,
  components: { LayoutFooter },
});
```

I get this error

    vue.js:634 [Vue warn]: Invalid prop: type check failed for prop "logo". Expected String, got Undefined 
    
    found in
    
    ---> <LayoutFooter> at components/layout/LayoutFooter.vue
           <Anonymous>
             <Anonymous>
               <Root>

Am I doing something wrong with the syntax?

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
