### ISSUE TITLE
Typings of `instrument` function in `@storybook/instrumenter` are incorrect

### ISSUE THREAD

**Issue by bilalq** [storybookjs/storybook#17925]
**Describe the bug**
The [`instrument` function](https://github.com/storybookjs/storybook/blob/next/lib/instrumenter/src/instrumenter.ts#L541) currently claims to return the same type as it receives. However, that's not the case when `intercept` is set to `true` and a `Promise` is returned instead. 

This causes issues when trying to `await` things like `userEvent.click(...)` in `@storybook/testing-library`, as reported in storybookjs/testing-library#10.

I believe the typings here could be improved by defining a recursive conditional type. That would look something like this:

```typescript
/**
 * A utility type that transforms a function type into one that returns a
 * Promise type of the existing value type.
 */
type PromisifiedReturn<T extends (...args: any) => any> =
  ReturnType<T> extends PromiseLike<unknown>
    ? T
    : (...a: Parameters<T>) => Promise<ReturnType<T>>

/**
 * A recursive utility type that transforms all functions types nested within
 * the object to return Promises instead of their existing value types.
 */
type InstrumentedObject<T> = {
  [K in keyof T]: 
    // If the value is a function, we transform its type to be one that returns a Promise
    T[K] extends (...args: any) => any 
    ? PromisifiedReturn<T[K]>
    // If it's an Array, we recursively transform its elements' types
    : T[K] extends (infer U)[]
    ? InstrumentedObject<U>[]
    // If it's an Object, we recursively transform its properties' types
    : T[K] extends object
    ? InstrumentedObject<T[K]>
    // Otherwise, we just keep the type as it is
    : T[K]
}
```

You can explore the proposed solution at [this TypeScript playground link](https://www.typescriptlang.org/play?#code/PQKhCgAIUhBSCuAXAlgGxUgnpbAHAU1wAsBDJXAJ1IDsBnAMwHtKBbOyUyBhGgY1RMauLIUgoaSJpCFEkZCpQJIElepygwACpSasUdOaKJMGJIgQAeB1DQDmkAG6k0CI4QB0m4OHxEdegYoDCgEACYASsqqNAA8ACqQVkgENGEcABQe2aSUdnQAXJw0WACUkAC8AHzFWDUVUJBRKmrxxgk1yanpkAH6hgAyKADWBLG8wzRMAO40VY2QkAD8kPELkEVZOUVauaSsygSUdB3l1b26-WPNMW2EHfPgoBDQcJBKfKp0KI5EyOiYHB+EjkKi0RgsdicNBobi8AQoIQcPwcGgEOgpMKQaaYYgSTTmGQAIwAVgQBLhpEoWsI+gZ0eJ6ClSFjTOYUJQktYMRIHM5XO50V5oD5gQBJJmUBAHSThADypPJSA6lUgAG9GgBtADSjMgoywbPiAF0iutgMBIGKzPIiPy3OIOFwePxBDQADTYuTUejMNjiJDI4yUyBEkxokGKaJqJ0XQKGdbxHXGrkpNKZbIeXL5Iq0MqVGp5yDrFZ074hcI3NQJZPzRaLC1WsyYADkTuEsEo1CwnumRA+Xx+BDQQJ9EP9mA4w4IMsD6yKSe1Ka66cgGQkDCOkAAqqVNcaS1bJdLUpiFWSBLFt1V9+bLdaA23ipBz0re-3yYPfiOwb7IQGODwXRCEoVB0XnVZk1TboOCYRUBEPCUMSlWd5Xg5VF2NOt60bOVbUoHFDHfSASQQDF9QIAg8EJYFSA4TBHQgzDwAAX3AJ5LQAKTIig6D0IgQhhLcXQRJFID4r1ID4WhIDIX5nwkFIlB5exGTwZBiQvCg0HII5wD4JEKD4DA+GGVUMmnWcigAUTQGdT09AB9CRMCWIoAFkmDIghrN+SQJQYgAfRA0gIEI0TCUoikcJgUCxapGgM+gmDsjw0CYOwLLs2dSn0wzIDCchSCrGheQAMXhN1zJoaUihq1gw0oM4anq14ACY8qZTg6CwfgADVYrCCrXURYQKjXeq6ulRqorjK5YhiuL6mwtFpjm+kMgyZSUt+ZrxOUeIUAOLykC29EdoIT16tKXKkvIujer4AARIqSvKyrRvM5CimQ3lZrLMYiSYFKCFoZbGgBjxtrQX4MmQjwMVyQMAHVcQyFtgBbG72MbazLH2PA7LUjS4K0kMJGQk9JE68iJHUpBz1VDVFiBkHaHiBQxToAA5JgkFgYbRJoIokClS7GnqjnyC53n+cFt0igARgABmV91EpM4Z1cWCQMDRMrhbXPaVeV7qpMM7Xusega4vl0bLbRDE0JJIpmfrZJqG59FMSGDEik1dZFjd+t61oPniCOA3NmNtXA9DqZ8NgHr+Cjo2C3WwwofOmGCAyBgXEMUpLZDlji-rDI9pbWRIFYFgBJoFsy8WNtRd5SNHUgBPODhEahBbdZjTLwqkGK6NSvsO2hDLh7+Beke3onj6p8aUvWLNu6kBxy0tB0vgCGIFKwi3I7CfsyRyE+tkKdFqmKCkAqZ0M6gUkQOhSDsAgaYoa+UNPVUEmgquUmSoqgZEcqTBcs0kI31QmEV8l54jLXVI0eQug1qrUgNZLsLB0ay3EKwU+s427yAMLJI4BAsasXYhvRklNYGM3Gj-W+64aD03PLdfKEgk6PW3G-D+qoZ58DTucN2pBpikAYkw+hpIPDGRQKZDIYQmCfFnB4AAjm4SgWAADK04BAsFgDCdGIAsaamVoPdULFyiNhKiIMQpCphrQBgtQa2ExESO-seaRJIszJz4DbIaS8aAZBVtYy0tjgRKFYBI9QzjFphDceIyRXjTzOw8I7M8MiPakC9k7MIvskBmONFmBOEdKAGwrpAGxY87FEAcTMDOYx6qNUSR42hMDUlwJkRktJ2Tck+xsJqRWxpKnVJpLUjujjGmxF+vYbCUjOnng8KzOy7NOY8z5gLIJVTLQc1ISs0GwgokxNjAAIWBqsmgjQFmyi6T4yW6zZZbN7jQDwUgyooEsOEDIyswmrDxKiaaW5jkU27s0vSOsUm3KWT0u5Hg+ne3CAUzUbVilSG3HgECABhOiuc-l7I4LMhwIL1BcCJVQoAA) and hover over the instrumented object's properties to see what there types look like after instrumentation.

Note that if the behavior should be that the return type should remain `TObj` if `instrument` is not set to `true`, that can be achieved by a discriminant function signature that returns a different type depending on the input. 

**To Reproduce**
1. Try to `await userEvent.click(...)` in a story and see linter warnings that you are awaiting a non-promise.
2. To experiment with the proposed solution, see [this TypeScript playground link](https://www.typescriptlang.org/play?#code/PQKhCgAIUhBSCuAXAlgGxUgnpbAHAU1wAsBDJXAJ1IDsBnAMwHtKBbOyUyBhGgY1RMauLIUgoaSJpCFEkZCpQJIElepygwACpSasUdOaKJMGJIgQAeB1DQDmkAG6k0CI4QB0m4OHxEdegYoDCgEACYASsqqNAA8ACqQVkgENGEcABQe2aSUdnQAXJw0WACUkAC8AHzFWDUVUJBRKmrxxgk1yanpkAH6hgAyKADWBLG8wzRMAO40VY2QkAD8kPELkEVZOUVauaSsygSUdB3l1b26-WPNMW2EHfPgoBDQcJBKfKp0KI5EyOiYHB+EjkKi0RgsdicNBobi8AQoIQcPwcGgEOgpMKQaaYYgSTTmGQAIwAVgQBLhpEoWsI+gZ0eJ6ClSFjTOYUJQktYMRIHM5XO50V5oD5gQBJJmUBAHSThADypPJSA6lUgAG9GgBtADSjMgoywbPiAF0iutgMBIGKzPIiPy3OIOFwePxBDQADTYuTUejMNjiJDI4yUyBEkxokGKaJqJ0XQKGdbxHXGrkpNKZbIeXL5Iq0MqVGp5yDrFZ074hcI3NQJZPzRaLC1WsyYADkTuEsEo1CwnumRA+Xx+BDQQJ9EP9mA4w4IMsD6yKSe1Ka66cgGQkDCOkAAqqVNcaS1bJdLUpiFWSBLFt1V9+bLdaA23ipBz0re-3yYPfiOwb7IQGODwXRCEoVB0XnVZk1TboOCYRUBEPCUMSlWd5Xg5VF2NOt60bOVbUoHFDHfSASQQDF9QIAg8EJYFSA4TBHQgzDwAAX3AJ5LQAKTIig6D0IgQhhLcXQRJFID4r1ID4WhIDIX5nwkFIlB5exGTwZBiQvCg0HII5wD4JEKD4DA+GGVUMmnWcigAUTQGdT09AB9CRMCWIoAFkmDIghrN+SQJQYgAfRA0gIEI0TCUoikcJgUCxapGgM+gmDsjw0CYOwLLs2dSn0wzIDCchSCrGheQAMXhN1zJoaUihq1gw0oM4anq14ACY8qZTg6CwfgADVYrCCrXURYQKjXeq6ulRqorjK5YhiuL6mwtFpjm+kMgyZSUt+ZrxOUeIUAOLykC29EdoIT16tKXKkvIujer4AARIqSvKyrRvM5CimQ3lZrLMYiSYFKCFoZbGgBjxtrQX4MmQjwMVyQMAHVcQyFtgBbG72MbazLH2PA7LUjS4K0kMJGQk9JE68iJHUpBz1VDVFiBkHaHiBQxToAA5JgkFgYbRJoIokClS7GnqjnyC53n+cFt0igARgABmV91EpM4Z1cWCQMDRMrhbXPaVeV7qpMM7Xusega4vl0bLbRDE0JJIpmfrZJqG59FMSGDEik1dZFjd+t61oPniCOA3NmNtXA9DqZ8NgHr+Cjo2C3WwwofOmGCAyBgXEMUpLZDlji-rDI9pbWRIFYFgBJoFsy8WNtRd5SNHUgBPODhEahBbdZjTLwqkGK6NSvsO2hDLh7+Beke3onj6p8aUvWLNu6kBxy0tB0vgCGIFKwi3I7CfsyRyE+tkKdFqmKCkAqZ0M6gUkQOhSDsAgaYoa+UNPVUEmgquUmSoqgZEcqTBcs0kI31QmEV8l54jLXVI0eQug1qrUgNZLsLB0ay3EKwU+s427yAMLJI4BAsasXYhvRklNYGM3Gj-W+64aD03PLdfKEgk6PW3G-D+qoZ58DTucN2pBpikAYkw+hpIPDGRQKZDIYQmCfFnB4AAjm4SgWAADK04BAsFgDCdGIAsaamVoPdULFyiNhKiIMQpCphrQBgtQa2ExESO-seaRJIszJz4DbIaS8aAZBVtYy0tjgRKFYBI9QzjFphDceIyRXjTzOw8I7M8MiPakC9k7MIvskBmONFmBOEdKAGwrpAGxY87FEAcTMDOYx6qNUSR42hMDUlwJkRktJ2Tck+xsJqRWxpKnVJpLUjujjGmxF+vYbCUjOnng8KzOy7NOY8z5gLIJVTLQc1ISs0GwgokxNjAAIWBqsmgjQFmyi6T4yW6zZZbN7jQDwUgyooEsOEDIyswmrDxKiaaW5jkU27s0vSOsUm3KWT0u5Hg+ne3CAUzUbVilSG3HgECABhOiuc-l7I4LMhwIL1BcCJVQoAA).

**System**
```
  System:
    OS: macOS 12.0.1
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 16.14.2 - ~/.n/bin/node
    npm: 8.5.0 - ~/.n/bin/npm
  Browsers:
    Chrome: 100.0.4896.75
    Firefox: 99.0
    Safari: 15.1
  npmPackages:
    @storybook/addon-actions: ^6.5.0-alpha.60 => 6.5.0-alpha.60
    @storybook/addon-essentials: ^6.5.0-alpha.60 => 6.5.0-alpha.60
    @storybook/addon-interactions: ^6.5.0-alpha.60 => 6.5.0-alpha.60
    @storybook/addon-links: ^6.5.0-alpha.60 => 6.5.0-alpha.60
    @storybook/addons: ^6.4.21 => 6.4.21
    @storybook/builder-vite: ^0.1.26 => 0.1.26
    @storybook/react: ^6.5.0-alpha.60 => 6.5.0-alpha.60
    @storybook/testing-library: ^0.0.9 => 0.0.9
    @storybook/theming: ^6.4.21 => 6.4.21
```

**Additional context**
N/A

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).

**Comment by kasperpeulen** [comment]
We fixed part of this in
https://github.com/storybookjs/jest/pull/34
and other parts of this in
https://github.com/storybookjs/testing-library/pull/43
