### ISSUE TITLE
Storybook doesn't remember the addon orientation

### ISSUE THREAD

**Issue by kaiyoma** [storybookjs/storybook#17938]
**Describe the bug**
Storybook doesn't remember the addon orientation.

**To Reproduce**

1. Open a Storybook URL
2. Change the addon orientation (dock to the right)
3. Close the browser tab
4. Open the same Storybook URL

**System**
```
Environment Info:

  System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
  Binaries:
    Node: 16.13.0 - C:\Program Files\Node.js\node.EXE
    npm: 8.6.0 - C:\Program Files\Node.js\npm.CMD
  Browsers:
    Chrome: 100.0.4896.75
    Edge: Spartan (44.19041.1266.0), Chromium (100.0.1185.36)
  npmPackages:
    @storybook/addon-actions: 6.4.19 => 6.4.19
    @storybook/addon-controls: 6.4.19 => 6.4.19
    @storybook/addons: 6.4.19 => 6.4.19
    @storybook/api: 6.4.19 => 6.4.19
    @storybook/components: 6.4.19 => 6.4.19
    @storybook/core: 6.4.19 => 6.4.19
    @storybook/core-events: 6.4.19 => 6.4.19
    @storybook/react: 6.4.19 => 6.4.19
    @storybook/theming: 6.4.19 => 6.4.19
```

**Comment by valentinpalkovic** [comment]
Layout changes are saved within the Session Storage, rather than in the Local Storage. Therefore, closing the browser tab and using a new one triggers a new Session. I don't think it is a bug but rather than a feature request to make layout changes also available after the current Session has ended. I could image, that using the Session Storage was done on purpose. 

@shilman Should we add a flag/option to also allow to save the changes in the Localstorage instead?

**Comment by kaiyoma** [comment]
I don't quite understand the reasoning here, since other layout changes *are* preserved. For instance, if you resize the sidebar, close the tab, and reopen Storybook, that setting is preserved. If you're going to preserve that, why not preserve the addon orientation too? Seems very equivalent to me.

**Comment by MichaelArestad** [comment]
@shilman I would expect layout info like this to be retained in local storage.

**Comment by burhanuday** [comment]
I created a PR for the above change. We might also want to take a look at the other ui preferences and see if we want to make them persistent
1. fullscreen: session
2. panel: session
3. nav: session
4. toolbar: session

**Comment by shilman** [comment]
w00t!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-beta.2 containing PR #18036 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
