### ISSUE TITLE
Docs: Update CLI docs from `sb` to `storybook`

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#17934]
We use `npx sb init/upgrade/etc.` in all our docs. Unfortunately this fails if the user has a program called `sb` installed. This feels like a deficiency of `npx`, but it is what it is.

We should switch to `npx storybook` instead:
- [ ] In the docs
- [ ] In blog posts
- [ ] In the code (if applicable)

See full discussion here https://github.com/storybookjs/storybook/issues/17923

**Comment by SulthanNK** [comment]
I would like to take this issue If no one started working already. 

I read the discussion mentioned in this issue. I noticed the places to change in docs. But, I would like to know about the blog posts and code.

**Comment by shilman** [comment]
@SulthanNK thanks so much for taking this on!

re: blog posts, you can't update the blog posts, so don't worry about that.
re: code, i did a search for `npx sb` in `*.ts` and found two hits

https://github.com/storybookjs/storybook/blob/next/lib/cli/src/automigrate/index.ts#L55

https://github.com/storybookjs/storybook/blob/next/lib/cli/src/automigrate/fixes/webpack5.ts#L55

https://github.com/storybookjs/storybook/blob/next/lib/core-server/src/utils/update-check.ts#L41

**Comment by SulthanNK** [comment]
Hi @shilman, When I try to run the "yarn bootstrap --core" command from the initial setup of code contributions. I'm getting these error messages. Did I miss anything?

![image](https://user-images.githubusercontent.com/32130871/163815929-82240ad2-2fbd-4338-ab37-e7684953ff98.png)

**Comment by SulthanNK** [comment]
Hello @shilman

I made the required changes in the code and docs based on this issue and The PR is #18022.

**Comment by jonniebigodes** [comment]
Closing this as the documentation is already featuring the mentioned command as default.
