### ISSUE TITLE
React - Story template pattern typo errors are frequent, common props to all stories, difficult - and here's a fix

### ISSUE THREAD

**Issue by ddfridley** [storybookjs/storybook#17936]
**The Problem**
The story pattern:
```JS
const NewStory=Template.bind({})
NewStory.args={prop1: 1}
```

1. Frequently incurs errors that are difficult to find when the constant name isn't spelled the same in the first line, and the second line.   This is especially true when people are new to storybook.

```JS
const NewStory=Template.bind({})
NewStroy.args={prop1: 1}
```

2. Another frequent problem is that you copied the two lines from a previous story and then forgot to change the constant name in the second line.

```JS
const NewStory=Template.bind({})
NewStory.args={prop1: 1}

const NewStory2=Template.bind({})
NewStory.args={prop1: 2}
```
3. Another problem is that when you have many story files where you want to pass a common prop from context, you end up having to repeat the code in every file.
```JS
import Component from '../app/component-under-test'
const Template= (args, context) =>{
    const {onDone}=context
    return <Component onDone={onDone} {...args}>
}
```

**Solution**
Here is a solution, it's a pattern that could be added to the documentation.  I'm happy to help with that, but want to share this here for public discussion and improvement.

`stories/make-chapter.js:`
```JS
import React from 'react'

// return a function that binds the args passed to a new instance of the Component being tested
export default function makeChapter(Component) {
    return args => {
        const test = args => <Component {...args} />
        test.args = args
        return test
    }
}
```

`stories/example.stories.js`
```JS
// do not change the name 'component' to any other name, just change the file being imported from
// it's ok that it's lower case in this file, it's just being passed through this file without JSX syntax
import component from '../app/components/example'
import makeChapter from './make-chapter'
const mC = makeChapter(component) // do not change

export default {
    title: 'Example Title', // This is the Story title that will be displayed in the left column list of stories
    argTypes: {}, // change as appropriate
    component, // do not change
}

export const Normal = mC({
    defaultValue: 1,
})

export const Different = mC({
    defaultValue: 2,
})
```
Every story would include makeChapter.  
1. The variable name for the 'Chapter' only has to be typed in once, so there is no mistake to make with the second name.
2. The what's rendered in makeChapter can take things out of context, and/or apply other props or html around the component being tested.
```JS
export default function makeChapter(Component) {
    return args => {
        const test = (args, context) => {
        const {onDone}=context
        return (
            <div style={{backgroundColor: 'gray'}}>
                <Component onDone={onDone} {...args} />
             </div>
        )
    }
    test.args = args
    return test
}
```

If there is some other way to do this, or other ideas, I'm interested.

**Comment by shilman** [comment]
We'll be switching to CSF3 in Storybook 7.0 that addresses this in a different way https://storybook.js.org/blog/component-story-format-3-0/

closing this for now. thank you!
