### ISSUE TITLE
Storybook Vue 3 TypeScript args types

### ISSUE THREAD

**Issue by SoetZombie** [storybookjs/storybook#17932]
**Describe the bug**
Having story.ts the compiler cannot resolve the type of args. 
**To Reproduce**
```
const Template = (args) => ({
    // Components used in your story `template` are defined in the `components` object
    components: { UButton },
    // The story's `args` need to be mapped into the template through the `setup()` method
    setup() {
        return { args };
    },
    // And then the `args` are bound to your component with `v-bind="args"`
    template: '<u-button v-bind="args"/>',
});

export const Test = Template.bind({});
Test.args = {text: "Test"}; 
```
The compiler throws error as following:

`TS2339: Property 'args' does not exist on type '(args: any) => { components: { UButton: DefineComponent{ theme: { type: StringConstructor; default: string; }; text: { type: StringConstructor; required: true; }; disabled: { ...; }; }, ... 10 more ..., { ...; }>; }; setup(): { ...; }; template: string; }'.`

Is there a type available we can use? I can see there are types for React already, how about Vue?

**Comment by valentinpalkovic** [comment]
Something like this should theoretically work:

```ts
import type { Meta, StoryFn } from '@storybook/vue3';

import UButton from './UButton';

export default {
  component: UButton,
} as Meta<typeof UButton>;

const Template: StoryFn<typeof UButton> = (args) => ({
  components: { UButton },
  setup() {
    return { args };
  },
  template: '<u-button v-bind="args"/>',
});

export const Test = Template.bind({});
Test.args = {text: "Test"}; 
```

**Comment by SoetZombie** [comment]
> @SoetZombie Does it work? If so, I will close the issue :)

Yes, it does, thank you. Would be cool if we could get it into the snippets just like for the react!. Thanks for the prompt reply.
