### ISSUE TITLE
next.js NextImage's broken

### ISSUE THREAD

**Issue by bonesoul** [storybookjs/storybook#17950]
I've been using the trick here to fix optimized next.js image components:

https://storybook.js.org/blog/get-started-with-storybook-and-next-js/

```
// .storybook/preview.js
import * as NextImage from "next/image";

const OriginalNextImage = NextImage.default;

Object.defineProperty(NextImage, "default", {
  configurable: true,
  value: (props) => <OriginalNextImage {...props} unoptimized />,
});
```

though with latest builds, it seems to be broken. any fixes?

**Comment by optimista** [comment]
Encountered same issue. It seems the solution through `defineProperty` is broken for also Storybook 6.5, and might not be working for new versions neither. I did resolve the issue with creating `./.storybook/NextImage.js` as following:

```
import Image from '../node_modules/next/image';
const NextImage = props => <Image unoptimized {...props} />
export default NextImage;
```

and then creating an alias for `next/image` by putting this line into `webpackFinal` function within `./.storybook/main.js`

```
module.exports = {
  webpackFinal: async (config) => {
    config.resolve.alias["next/image"] = require.resolve("./.storybook/NextImage.js");
  }
}
```

Note: The `import` through `../node_modules` is necessary not to create a cyclically resolving alias.

**Comment by michalkleiner** [comment]
Thanks for the workaround @optimista, it worked a charm for us!

**Comment by knaot0** [comment]
Thank you @optimista!

it worked by changing the following two points!

1. `webpackFinal` returns the altered `config`
2. Change the path of `"./.storybook/NextImage.js"` to `"./NextImage.js"`

```diff
  webpackFinal: async (config) => {
-     config.resolve.alias["next/image"] = require.resolve("./.storybook/NextImage.js");
+      config.resolve.alias["next/image"] = require.resolve("./NextImage.js");
+     return config;
    },
```

**Comment by iamgoddog** [comment]
This didn't work for me at storybook@6.5.0
I found this at nextjs repo https://github.com/vercel/next.js/issues/36417#issuecomment-1117360509 and that fixed it for me if I use storybook@6.4.x

**Comment by souppower** [comment]
@bonesoul @iamgoddog I'm still @6.4, but this worked for me.

https://github.com/vercel/next.js/issues/36417#issuecomment-1117360509

**Comment by iamgoddog** [comment]
> @bonesoul @iamgoddog I'm still @6.4, but this worked for me.
> 
> https://github.com/vercel/next.js/issues/36417#issuecomment-1117360509

Yes it worked @6.4 for me also.

**Comment by shilman** [comment]
@iamgoddog the `push of undefined` error was fixed in https://github.com/storybookjs/storybook/releases/tag/v6.5.4 by this PR https://github.com/storybookjs/storybook/pull/18284

**Comment by cslegany** [comment]
Is there any working solution with storybook 6.5.10? Previous hacks seem to be broken by now.

**Comment by clodal** [comment]
Had this issue. Can confirm that this works in 6.5. Thanks!

**Comment by Guilherme-Farias** [comment]
Anyone using version "^6.5" managed to solve it?

**Comment by jakapatb** [comment]
It worked on v6.5

```jsx
// .storybook/preview.js

import * as NextImage from 'next/image';
import React from 'react';

const OriginalNextImage = NextImage.default;

Object.defineProperty(NextImage, 'default', {
  configurable: true,
  value: (props) =>
    React.createElement(OriginalNextImage, { ...props, unoptimized: true }),
});

Object.defineProperty(NextImage, '__esModule', {
  configurable: true,
  value: true,
});
```

**Comment by shilman** [comment]
Jeepers creepers!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-alpha.57 containing PR #20028 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
