### ISSUE TITLE
Storyshots breaks Jest tests

### ISSUE THREAD

**Issue by bengalley-e2x** [storybookjs/storybook#17952]
**Describe the bug**

Trying to add storyshots to our ui-library repo to run unit tests, but it breaks Jest.

I initially followed the steps on https://storybook.js.org/docs/react/writing-tests/snapshot-testing.

After receiving the following import error I then tried to use the react-testing-library configuration as suggested in https://storybook.js.org/addons/@storybook/addon-storyshots.

In an attempt to implement several workarounds found on various threads, I added the transform configuration to the `jest.config.js`, added a `babel.config.js` with the jest preset. None worked.

The main issue is Jest tests work when not attempting to use snapshots, using initStoryshots() is the cause of the issue, leading me to believe it is misconfigured.

Error:

![Screenshot 2022-04-13 at 14 49 00](https://user-images.githubusercontent.com/80111772/163195247-e4f11233-bda3-44fe-a57e-bfa30f2e3894.png)

**To Reproduce**

Our project is a ui-library published to a private npm registry using:

- Lerna
- TypeScript
- Storybook
- Vite
- Jest / React Testing Library

Add the `storyshots` addon

`yarn add --dev @storysbook/addon-storyshots`

`Stories.test.ts`

```
import { render } from '@testing-library/react';
import initStoryshots from '@storybook/addon-storyshots';

const reactTestingLibrarySerializer = {
    print: (val: any, serialize: any, indent: any) => serialize(val.container.firstChild),
    test: (val: any) => val && val.hasOwnProperty('container'),
};

initStoryshots({
    configPath: '.storybook',
    renderer: render,
    snapshotSerializers: [reactTestingLibrarySerializer],
});
```

Configuration files:

`jest.config.js`

```
module.exports = {
  transformIgnorePatterns: [
    "node_modules/(?!(@storybook/addon-contexts)/)"
  ],
  coverageThreshold: {
    global: {
      statements: 74,
      branches: 74,
      lines: 74,
      functions: 74,
    },
  },
  preset: "ts-jest",
  testEnvironment: "node",
  setupFiles: ["dotenv/config"],
  collectCoverage: true,
  coverageDirectory: 'coverage',
  coveragePathIgnorePatterns: ['/node_modules/'],
  coverageProvider: 'v8',
  moduleFileExtensions: ['js', 'json', 'jsx', 'ts', 'tsx', 'node'],
  transform: {
    '^.+\\.(ts|tsx)?$': 'ts-jest',
    "^.+\\.(js|jsx)$": "babel-jest",
  },
  testEnvironment: 'jsdom',
  testMatch: [
    '**/?(*.)+(spec|test).[tj]s?(x)',
  ],
};
```

`tsconfig.json`

```
{
  "compilerOptions": {
    "target": "ESNext",
    "useDefineForClassFields": true,
    "lib": [
      "DOM",
      "DOM.Iterable",
      "ESNext"
    ],
    "allowJs": false,
    "skipLibCheck": false,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "ESNext",
    // will not work if not in node resolution
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",
    // required to output types
    "declaration": true,
    "baseUrl": ".",
  },
  "paths": {
    "@/*": [
      "src/*"
    ]
  },
  "include": [
    "src",
    "*.d.ts"
  ],
  "exclude": [
    "node_modules",
    "dist"
  ],
  "references": [
    {
      "path": "./tsconfig.node.json"
    }
  ]
}
```

`vite.config.ts`

```
import { defineConfig } from 'vite';
import reactRefresh from '@vitejs/plugin-react-refresh';
import dts from 'vite-plugin-dts';

// eslint-disable-next-line @typescript-eslint/no-var-requires
const path = require('path');

export default defineConfig({
  // dts to automatically output types in dist
  plugins: [reactRefresh(), dts()],
  resolve: {
    alias: {
      '@/': new URL('./src/', import.meta.url).pathname,
    },
  },
  build: {
    lib: {
      entry: path.resolve(__dirname, 'src/index.ts'),
      name: '$PROJECT_NAME',
      fileName: (format) => `react-ui-lib.${format}.js`,
    },
    rollupOptions: {
      // make sure to externalize deps that should not be bundled into your library
      external: ['react', 'react-dom'],
    },
  },
});
```

It would be great to understand both what the root cause of this error is and also what needs to be configured, where in order to get storyshots working for snapshot tests.

**Comment by alaanescobedo** [comment]
Hello, I also had similar problems installing storyshot yesterday, I solved this problem when I changed the extension from `preview.js `to `preview.ts`, but I would also like to better understand this problem and how jest's transform works

**Comment by bengalley-e2x** [comment]
Thanks @alaanescobedo - I have mine as `preview.tsx`. Have tried so many things now but no joy.

**Comment by demian-licht-hs** [comment]
Has there been any progress in fixing this? I ran into a similar situation: needed to change my jsxRuntime for storybook to run; but that broke storyshots.

**Comment by ndelangen** [comment]
The future of storyshots is the test-runner:
https://storybook.js.org/docs/react/writing-tests/test-runner#page-top

And use the play function for expectations:
https://storybook.js.org/docs/react/writing-stories/play-function#page-top

We will not be making any improvement / changes to storyshots.
