### ISSUE TITLE
Storybook/addon-storyshots support capturing CSS styles

### ISSUE THREAD

**Issue by zhixuan-loh** [storybookjs/storybook#17960]
**Is your feature request related to a problem? Please describe**
I am using this feature to work together with non technical stakeholders. I want to make sure snapshots capture 100% of what my stories show, including CSS styles. Currently, when I change a style attribute, the snapshot tests still pass, but the component looks very different (I changed the width from `430px` to `4300px` but its class is not changed, probably that's why)

My stack:
- Vue 3
- Vite

**Describe the solution you'd like**
What would you like to see added to Storybook to solve problem?
`initStoryshots()` to somehow capture the scoped CSS for my components and throw errors when I change any CSS.

**Describe alternatives you've considered**
Any alternative solutions or features you've considered.
Using Jest directly to check the CSS, but that defeats the purpose of using storyshots.

**Are you able to assist to bring the feature to reality?**
I'm sorry, no...

**Additional context**

**Comment by jonniebigodes** [comment]
The Storyshots addon is officially deprecated and will be removed in a future release of Storybook. To help with the transition process, we've created a [migration guide](https://storybook.js.org/docs/writing-tests/storyshots-migration-guide) for the available options and common use cases.
