### ISSUE TITLE
Web workers are getting rebuilt on every file change, even for unrelated files

### ISSUE THREAD

**Issue by kaiyoma** [storybookjs/storybook#17980]
**Describe the bug**
Whenever I save a change to a file, even a stylesheet, the web workers in my project all get rebuilt. I'm using a custom webpack configuration with Storybook that uses `worker-loader` to load the workers. Has anyone else run into this?

**To Reproduce**
Can't provide a repro right now (too much proprietary code).

**System**
```
Environment Info:

  System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
  Binaries:
    Node: 16.13.0 - C:\Program Files\Node.js\node.EXE
    npm: 8.6.0 - C:\Program Files\Node.js\npm.CMD
  Browsers:
    Chrome: 100.0.4896.127
    Edge: Spartan (44.19041.1266.0), Chromium (100.0.1185.39)
  npmPackages:
    @storybook/addon-actions: 6.4.22 => 6.4.22
    @storybook/addon-controls: 6.4.22 => 6.4.22
    @storybook/addon-docs: 6.4.22 => 6.4.22
    @storybook/addons: 6.4.22 => 6.4.22
    @storybook/api: 6.4.22 => 6.4.22
    @storybook/components: 6.4.22 => 6.4.22
    @storybook/core: 6.4.22 => 6.4.22
    @storybook/core-events: 6.4.22 => 6.4.22
    @storybook/react: 6.4.22 => 6.4.22
    @storybook/theming: 6.4.22 => 6.4.22
```

**Additional context**
The build of the workers happens relatively quickly (either because we're using esbuild or because Storybook has a cache), but it's still 2-3 seconds of wasted effort on every rebuild.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
