### ISSUE TITLE
No changes show after change and refresh. (i.e. Stories and Controls and Arguments and Styles, etc...)

### ISSUE THREAD

**Issue by jb-207** [storybookjs/storybook#17981]
Hi! 

I'm running MacOS BigSur 11.6.5. and Monterey 12.3.1
Storybook version: 6.4.18
npm version: 6.14.15
node version: 14.17.6

Every time I update anything after running the server on localhost:6006/ I have output in the terminal stating for example: "webpack building...
webpack built preview e960d3835ad091dfe1c9 in 364ms"

but the changes never show. I have to shut down the server and rebuild and also restart the server. 

Any thoughts? Thanks!

**Comment by ndelangen** [comment]
Please create a reproduction.

It sounds like HMR isn't working client-side.
Sounds like you likely made webpack config modifications that broke it.

Without a reproduction, there's nothing we can do.
