### ISSUE TITLE
Setting up a vue project with tilwind and storybook

### ISSUE THREAD

**Issue by MidoDomy** [storybookjs/storybook#17990]
**Describe the bug**
I tried to set up a vue project with tilwind and storybook but that tailwind also works in storybook and I got this error for which I can't find a solution anywhere

99% done plugins webpack-hot-middlewarewebpack built preview d4ac54f94c56a6e7ddbf in 5422ms
ModuleNotFoundError: Module not found: Error: Can't resolve './stories' in '/home/domy/projects/vue-tailwind'
    at /home/domy/projects/vue-tailwind/node_modules/webpack/lib/Compilation.js:2016:28
    at /home/domy/projects/vue-tailwind/node_modules/webpack/lib/ContextModuleFactory.js:214:15
    at /home/domy/projects/vue-tailwind/node_modules/neo-async/async.js:2830:7
    at /home/domy/projects/vue-tailwind/node_modules/neo-async/async.js:6877:13
    at /home/domy/projects/vue-tailwind/node_modules/webpack/lib/ContextModuleFactory.js:184:26
    at finishWithoutResolve (/home/domy/projects/vue-tailwind/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:312:11)
    at /home/domy/projects/vue-tailwind/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:386:15
    at /home/domy/projects/vue-tailwind/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/home/domy/projects/vue-tailwind/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /home/domy/projects/vue-tailwind/node_modules/webpack/lib/cache/ResolverCachePlugin.js:257:15
    at /home/domy/projects/vue-tailwind/node_modules/webpack/lib/cache/ResolverCachePlugin.js:177:36
    at /home/domy/projects/vue-tailwind/node_modules/webpack/lib/HookWebpackError.js:68:3
    at Hook.eval [as callAsync] (eval at create (/home/domy/projects/vue-tailwind/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at Cache.store (/home/domy/projects/vue-tailwind/node_modules/webpack/lib/Cache.js:107:20)
    at ItemCacheFacade.store (/home/domy/projects/vue-tailwind/node_modules/webpack/lib/CacheFacade.js:137:15)
    at /home/domy/projects/vue-tailwind/node_modules/webpack/lib/cache/ResolverCachePlugin.js:173:18

**To Reproduce**
clone repo and start `yarn storybook`
https://github.com/MidoDomy/vue-tailwind-storybook

**System**
Environment Info:
  System:
    OS: Linux 5.13 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
  Binaries:
    Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v14.18.1/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
  Browsers:
    Chrome: 100.0.4896.60
    Firefox: 99.0
  npmPackages:
    @storybook/addon-actions: ^6.4.22 => 6.4.22 
    @storybook/addon-essentials: ^6.4.22 => 6.4.22 
    @storybook/addon-links: ^6.4.22 => 6.4.22 
    @storybook/addon-postcss: ^2.0.0 => 2.0.0 
    @storybook/builder-webpack5: ^6.4.22 => 6.4.22 
    @storybook/manager-webpack5: ^6.4.22 => 6.4.22 
    @storybook/preset-scss: ^1.0.3 => 1.0.3 
    @storybook/vue3: ^6.4.22 => 6.4.22 

**Additional context**

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).

Also, please check out https://storybook.js.org/addons/@storybook/addon-styling
