### ISSUE TITLE
ArgsTable tab displays component name as `Story` when __docgen is not available

### ISSUE THREAD

**Issue by siminino** [storybookjs/storybook#18029]
**Describe the bug**

There are a few cases where react-docgen is not capable of processing the component source code. In my case, my components are implemented as Styled Components and there is a known issue on the detection of props #11933. To overcome this issue, I am defining all the ArgTypes on the component Story.

Even so, I found an issue on the label of ArgTable's tabs where the `__docgen` property of the component is empty, it is displaying `Story` as default label, even when the component as a `displayName` property that could be used on the tab. I have checked ArgsTable source and noticed the fallback name for this situation is `Component.name` (line 70). 
https://github.com/storybookjs/storybook/blob/2262d27e246ddc868545b98746e808039313aac5/app/svelte/src/client/docs/sourceDecorator.ts#L61-L77

**To Reproduce**

Button.js
```js
import React from 'react'
import styled from 'styled-components'

export const Button = styled.button`
  border-radius: 4px;
`
Button.displayName = 'Button'

export const ButtonLink = props => <Button as='a' {...props} />
ButtonLink.displayName = 'ButtonLink'
```

Button.story.js
```js
import React from 'react'

import { Button, ButtonLink } from './Button'

export default {
  title: 'Button',
  component: Button,
  subcomponents: { ButtonLink },
}

export const Default = agrs => <Button {...args}>This is a button</Button>

export const Anchor = args => <ButtonLink {...args}>This is an anchor</ButtonLink>
Anchor.args = { href: '/' }
```

**Workaround**

Adding this line on the story file will fix the tab.
```js
Button.name = Button.displayName
```

Does have any reason for not using `Component.displayName` as fallback by default?

**Screenshot**
<img width="1074" alt="Screenshot 2022-04-22 at 19 44 23" src="https://user-images.githubusercontent.com/632044/164766828-3cdbdb2f-d620-4644-bb3b-48f50de77274.png">

**Comment by zackphilipps** [comment]
👋  Hello there! I've written a blog post that references this issue! You can view the applicable excerpt/code snippet here: [Styled Components + TypeScript: The main component name will show up as “Story” or “undefined” unless the component is a named export in a .tsx file](https://zackphilipps.dev/posts/storybook-csf-mdx-known-issues-typescript-styled-components#styled-components--typescript-the-main-component-name-will-show-up-as-story-or-undefined-unless-the-component-is-a-named-export-in-a-tsx-file---18029)

GitHub discussion: https://github.com/storybookjs/storybook/discussions/18915

✌️

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
