### ISSUE TITLE
CSF3: Auto-title regression for PascalCase filenames

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#18039]
> @spacecakes fixed in 6.5

Wow, that is convenient. Thank you very much!

The only issue I noticed with this is that story hoisting does not work for multi-word component names, because, say, `CheckboxGroup.stories.js` is gets processed into `Checkbox Group` for the story name, while the path remains as-is so they no longer match. So we get this:

<img width="198" alt="Screenshot 2022-04-22 at 18 58 16" src="https://user-images.githubusercontent.com/15325145/164760370-4fb7dc0e-7f0f-467b-b0d2-a6552fe4e34f.png">

Not a dealbreaker by any means and I realise it's prelease software, but it would be nice if this worked to avoid nesting single-story components with this setup.

_Originally posted by @spacecakes in https://github.com/storybookjs/storybook/issues/15376#issuecomment-1106696896_

**Comment by shilman** [comment]
Thanks @spacecakes I must have broken this when I changed how auto-title handles file paths. Will fix before the release.

**Comment by shilman** [comment]
@valentinpalkovic These are the relevant PRs: https://github.com/storybookjs/storybook/pull/17597 https://github.com/storybookjs/storybook/pull/17574 https://github.com/storybookjs/storybook/pull/17421

**Comment by shilman** [comment]
Good golly!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-beta.1 containing PR #18052 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by spacecakes** [comment]
Huge thanks for this @shilman 🙏
