### ISSUE TITLE
Installing dependenciesnpm ERR! code ENOENT

### ISSUE THREAD

**Issue by zjjjjjjjjjjd** [storybookjs/storybook#18047]
<img width="754" alt="image" src="https://user-images.githubusercontent.com/32830366/165054419-a7a13aad-ab87-4b09-9427-0d08c026a1d9.png">

i don't know why, os is mac

**Comment by budiirawanrapid** [comment]
The error said

![Image 2022-04-26 at 07 08 52@2x](https://user-images.githubusercontent.com/85203411/165175420-2823844b-f247-41fc-93ea-83c3397053fc.jpg)

@zjjjjjjjjjjd do you have `package.json` inside `anze-components` folder?

**Comment by deerawan** [comment]
The error said

![Image 2022-04-26 at 07 08 52@2x](https://user-images.githubusercontent.com/85203411/165175420-2823844b-f247-41fc-93ea-83c3397053fc.jpg)

@zjjjjjjjjjjd do you have `package.json` inside `anze-components` folder?

**Comment by zjjjjjjjjjjd** [comment]
> The error said
> 
> ![Image 2022-04-26 at 07 08 52@2x](https://user-images.githubusercontent.com/85203411/165175420-2823844b-f247-41fc-93ea-83c3397053fc.jpg)
> 
> @zjjjjjjjjjjd do you have `package.json` inside `anze-components` folder?


no `package.json`, only have `package-lock.json`.
Thank for you reply! maybe is my network bad, it is working now :)
