### ISSUE TITLE
Source component throws TypeError

### ISSUE THREAD

**Issue by mat100payette** [storybookjs/storybook#18056]
**Describe the bug**
Any use of a `<Source code={'...'} />` component from `@storybook/component` throws the following error at runtime:

> TypeError: Cannot read properties of undefined (reading 'size')
    at http://localhost:6006/vendors~main.iframe.bundle.js:20145:42
    at handleInterpolation (http://localhost:6006/vendors~main.iframe.bundle.js:1563:24)
    at serializeStyles (http://localhost:6006/vendors~main.iframe.bundle.js:1683:15)
    at http://localhost:6006/vendors~main.iframe.bundle.js:2026:108
    at updateContextConsumer (http://localhost:6006/vendors~main.iframe.bundle.js:135497:19)
    at beginWork (http://localhost:6006/vendors~main.iframe.bundle.js:135864:14)
    at HTMLUnknownElement.callCallback (http://localhost:6006/vendors~main.iframe.bundle.js:120695:14)
    at Object.invokeGuardedCallbackDev (http://localhost:6006/vendors~main.iframe.bundle.js:120744:16)
    at invokeGuardedCallback (http://localhost:6006/vendors~main.iframe.bundle.js:120806:31)
    at beginWork$1 (http://localhost:6006/vendors~main.iframe.bundle.js:140709:7)

**To Reproduce**
1. `npx sb init`, using `react` framework for project
2. Use the following `package.json`:
```json
    {
  "name": "untitled",
  "version": "1.0.0",
  "devDependencies": {
    "@babel/core": "^7.17.9",
    "@storybook/addon-actions": "^6.4.22",
    "@storybook/addon-essentials": "^6.4.22",
    "@storybook/addon-interactions": "^6.4.22",
    "@storybook/addon-links": "^6.4.22",
    "@storybook/react": "^6.4.22",
    "@storybook/testing-library": "^0.0.11",
    "babel-loader": "^8.2.5",
    "react": "^17.0.1",
    "react-docgen-typescript-loader": "^3.7.2",
    "react-dom": "^17.0.1",
    "react-is": "^17.0.2"
  },
  "dependencies": {},
  "scripts": {
    "storybook": "start-storybook -p 6006",
    "build-storybook": "build-storybook"
  }
}
 ```
3. Append the following at the end of the `Button.stories,js` file:
```jsx
const TemplateSource = (args) => <Source code={`<></>`} language={'tsx'} />;
export const SourceCode = TemplateSource.bind({});
```
4. Run the storybook and go to the `SourceCode` story, the error should appear.

**System**
> Environment Info:

    System:
      OS: Windows 10 10.0.22000
      CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700H
    Binaries:
      Node: 14.19.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.15 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 8.7.0 - C:\Program Files\nodejs\npm.CMD
    Browsers:
      Edge: Spartan (44.22000.120.0), Chromium (100.0.1185.50)
    npmPackages:
      @storybook/addon-actions: ^6.4.22 => 6.4.22
      @storybook/addon-essentials: ^6.4.22 => 6.4.22
      @storybook/addon-interactions: ^6.4.22 => 6.4.22
      @storybook/addon-links: ^6.4.22 => 6.4.22
      @storybook/react: ^6.4.22 => 6.4.22
      @storybook/testing-library: ^0.0.11 => 0.0.11

**Comment by shilman** [comment]
Doc blocks are only usable on the docs tab, not in stories. I'm working on moving it into an addon here: https://github.com/storybookjs/storybook/pull/18040
