### ISSUE TITLE
Stuck at "70% sealing finish module graph ESLintWebpackPlugin_1"

### ISSUE THREAD

**Issue by agjs** [storybookjs/storybook#18051]
**Describe the bug**
yarn storybook is stuck at "70% sealing finish module graph ESLintWebpackPlugin_1"

![Screenshot 2022-04-25 at 12 33 13](https://user-images.githubusercontent.com/7226555/165072683-0bf525a5-a6e0-414e-a7c1-5fc9a0123c68.png)

Storybook was freshly generated by running *npx sb init*. 

I've tried removing node_modules and yarn lock file, but no success.

**System**
Relevant dependencies. 
```
    "react": "18.0.0",
    "@storybook/addon-actions": "^6.4.22",
    "@storybook/addon-essentials": "^6.4.22",
    "@storybook/addon-interactions": "^6.4.22",
    "@storybook/addon-links": "^6.4.22",
    "@storybook/builder-webpack5": "^6.4.22",
    "@storybook/manager-webpack5": "^6.4.22",
    "@storybook/node-logger": "^6.4.22",
    "@storybook/preset-create-react-app": "^4.1.0",
    "@storybook/react": "^6.4.22",
    "@storybook/testing-library": "^0.0.11",
    "webpack": "^5.72.0"
```

Node.js version: 17.8.0

**Comment by agjs** [comment]
The issue was caused by *eslint-plugin-storybook* plugin. After removing it, the build worked.

**Comment by volodymyr-strilets-mindcurv** [comment]
Same here +1

**Comment by jeggy** [comment]
I also got this, and after around 5-10minutes it crashed because of no memory left. 
After providing `--max-old-space-size=4096` to the node arguments, I got it running smoothly again

**Comment by AnyaParry** [comment]
![image](https://user-images.githubusercontent.com/60728866/188819703-fb37750d-4ef0-4da3-9a8a-50db3e705159.png)
Same Here +1.

**Comment by laurent-brisbois** [comment]
I have the same problem. I have to wait an inconvenient time.

**Comment by noveo-greshilov-vlad** [comment]
+1
Any solutions so far?

**Comment by alexgorbatchev** [comment]
Also started happening for me, using version `6.5.12`. Tried with `--max-old-space-size=4096` with no observable difference. In my case storybook is stuck at 57% seemingly forever. I waited an hour and it made no progress.

**Comment by kindermax** [comment]
+1 same problem

**Comment by ajay-sainy** [comment]
Same problem

**Comment by tseringn** [comment]
same here

**Comment by kaouthar1abouayad** [comment]
> I also got this, and after around 5-10minutes it crashed because of no memory left. After providing `--max-old-space-size=4096` to the node arguments, I got it running smoothly again

where should I implement this?

**Comment by jadiaheno** [comment]
> > I also got this, and after around 5-10minutes it crashed because of no memory left. After providing `--max-old-space-size=4096` to the node arguments, I got it running smoothly again
> 
> where should I implement this?
`NODE_OPTIONS='--max-old-space-size=8192'`
