### ISSUE TITLE
Make `export default` work in `main.ts`

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#18063]
works:

```ts
const config: StorybookConfig = { };
module.exports = config;
```

fails:

```ts
const config: StorybookConfig = { };
export default config;
```

**Comment by eddiemonge** [comment]
Preferably without having to configure Babel just to load things in the `.storybook` folder

**Comment by prashantpalikhe** [comment]
@shilman this should also be taken care of if we use JITI or esbuild-require in the serverRequire. I will shoot out a PR soon with a fix.

**Comment by shilman** [comment]
Happy to report that this is fixed in SB7!

Migration guide: https://storybook.js.org/migration-guides/7.0
