### ISSUE TITLE
[Bug] After clicking "show code" first time Object Object is shown

### ISSUE THREAD

**Issue by MarkiyanPyts** [storybookjs/storybook#18079]
After running build-storybook and serving it in the production "show code" the button displays "Object object" instead of code.

![image](https://user-images.githubusercontent.com/6214703/165566980-df7f5f80-ca5f-4210-8aae-4a48bc453e06.png)

I created a project using
npm create vite@latest

Then installed story book there
npx sb init --builder @storybook/builder-vite

No additional changes were needed to reproduce this.

Note: this will work properly during npm run storybook breaks only for prod

**To Reproduce**
1) Clone reproduction repo
Reproduction Repo: https://github.com/MarkiyanPyts/story-book-vite-object-object-issue
1) `run npm i`
2) `npm run build-storybook`
3) Serve storybook production somewhere, you can use https://www.npmjs.com/package/http-server install it globally then navigate to this project root and run http-server storybook-static
4) Open storybook production in the browser and go to button docs
5) Click "Show Code" the first time, observe "Object object" instead of component code, if you close the preview and click "Show Code" the second time this will work properly

Note: It is not reproducible on localhost with npm run storybook

**System**
Environment Info:

  System:
    OS: macOS 12.2.1
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 16.14.0 - /usr/local/bin/node
    npm: 8.3.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 101.0.4951.41
    Firefox: 98.0.1
    Safari: 15.3

**Additional context**
Also opened issue in story-book-vite repo https://github.com/storybookjs/builder-vite/issues/355 was directed here

**Comment by irudoy** [comment]
Seems like it's related to https://github.com/storybookjs/storybook/issues/18012

**Comment by IanVS** [comment]
This is working correctly in Storybook 7.0 betas.  Please let us know if you continue to experience this, with details on the versions you are using.
