### ISSUE TITLE
buildStoriesJson should add stories.json entries for .svelte stories

### ISSUE THREAD

**Issue by IanVS** [storybookjs/storybook#18081]
**Is your feature request related to a problem? Please describe**
I was trying to enable the test-runner for svelte-native story files using stories.json mode as suggested in https://github.com/storybookjs/test-runner/issues/80#issuecomment-1107361737, but I found that stories.json is not generated for `.svelte` stories, see https://github.com/storybookjs/storybook/blob/552b0d3f6c23486e603a304439639f69facad40d/lib/core-server/src/utils/StoryIndexGenerator.ts#L51-L54.

**Describe the solution you'd like**
It would be cool if stories.json included .svelte files.  Or, if that's not feasible, we should document it.

**Are you able to assist to bring the feature to reality?**
I doubt it.

**Comment by dimfeld** [comment]
I looked into this a bit, and to make this work, at a minimum the `StoryIndexGenerator` needs a way to use the CSF parser that currently lives in `addon-svelte-csf` instead of the normal CSF parser built into core.

**Comment by shilman** [comment]
Egads!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-alpha.0 containing PR #18355 that references this issue. Upgrade today to the `@future` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by IanVS** [comment]
This has been addressed in 7.0, which allows indexing svelte files. The latest 3.0.0 prerelease versions of @storybook/addon-svelte-csf use the new story indexer added in 7.0.
