### ISSUE TITLE
Storybook build fails due to scss import, but run storybook works

### ISSUE THREAD

**Issue by ptoly** [storybookjs/storybook#18104]
**Describe the bug**
I have a React app that uses SCSS. When I run npm run storybook, it works fine. However, when I run npm run build-storybook I get an error:
`ERR! TypeScript error in Sites/sbworking/src/stories/Design System/Colors/Colors.tsx(1,20):
ERR! Cannot find module '../../../theme/scss/_variables.scss' or its corresponding type declarations.  TS2307`

I have:
- Added a global.d.ts inside the /src with `declare module '*.scss';`
- tsconfig.json contains `"include": ["src"]`

**To Reproduce**
`npx sb@next repro` fails with:
`$ yarn install [--json] [--immutable] [--immutable-cache] [--check-cache] [--inline-builds] [--mode #0]
An error occurred while executing: `yarn install`
🚨 Dependencies installation failed
🚨 Failed to create repro`

This is a Material UI with typescript. I chose the cra_typescript option.

**System**
Environment Info:

  System:
    OS: macOS 12.3.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 14.19.0 - ~/.nvm/versions/node/v14.19.0/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 6.14.16 - ~/.nvm/versions/node/v14.19.0/bin/npm
  Browsers:
    Chrome: 100.0.4896.127
    Edge: 101.0.1210.32
    Firefox: 99.0.1
    Safari: 15.4
  npmPackages:
    @storybook/addon-a11y: ^6.4.22 => 6.4.22
    @storybook/addon-actions: ^6.4.22 => 6.4.22
    @storybook/addon-console: ^1.2.3 => 1.2.3
    @storybook/addon-essentials: ^6.4.22 => 6.4.22
    @storybook/addon-interactions: ^6.4.22 => 6.4.22
    @storybook/addon-links: ^6.4.22 => 6.4.22
    @storybook/node-logger: ^6.4.22 => 6.4.22
    @storybook/preset-create-react-app: ^3.2.0 => 3.2.0
    @storybook/preset-scss: ^1.0.3 => 1.0.3
    @storybook/react: ^6.4.22 => 6.4.22
    @storybook/testing-library: 0.0.11 => 0.0.11

**Additional context**
My main.js file:

`const path = require('path');

module.exports = {
  stories: ['../src/stories/*.stories.mdx', '../src/stories/**/*.stories.mdx', '../src/stories/**/*.stories.@(js|jsx|ts|tsx)'],
  staticDirs: ['../public', '../src/stories/assets', '../src/theme/assets'],
  addons: [
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    '@storybook/preset-create-react-app',
    '@whitespace/storybook-addon-html',
  ],
  webpackFinal: async (config, { configType }) => {
    config.module.rules.push({
      test: /\.scss$/,
      use: ['sass-loader'],
      include: path.resolve(__dirname, '../'),
      resolve: {
        alias: {
          '@': path.resolve(__dirname, '../src/'),
          '~': path.resolve(__dirname, '../src/theme/'),
        },
      },
    });

    return config;
  },

  framework: '@storybook/react',
};`

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).

Also check out https://storybook.js.org/addons/@storybook/addon-styling
