### ISSUE TITLE
Render error with react markdown

### ISSUE THREAD

**Issue by DawnMD** [storybookjs/storybook#18112]
**Describe the bug**
Storybook throws an error when a component with [react-markdown](https://www.npmjs.com/package/react-markdown) is being rendered. It just shows an error message of `vfile__WEBPACK_IMPORTED_MODULE_1__.VFile is not a constructor`, But when storybook is removed the story file is being rendered.

**To Reproduce**
- None

**System**
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 AMD Ryzen 5 1600 Six-Core Processor
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.18 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (101.0.1210.32)
  npmPackages:
    @storybook/addon-actions: 6.5.0-beta.0 => 6.5.0-beta.0
    @storybook/addon-essentials: 6.5.0-beta.0 => 6.5.0-beta.0
    @storybook/addon-links: 6.5.0-beta.0 => 6.5.0-beta.0
    @storybook/addon-postcss: ^2.0.0 => 2.0.0
    @storybook/addon-viewport: 6.5.0-beta.0 => 6.5.0-beta.0
    @storybook/builder-webpack5: 6.5.0-beta.0 => 6.5.0-beta.0
    @storybook/core-client: 6.5.0-beta.0 => 6.5.0-beta.0
    @storybook/manager-webpack5: 6.5.0-beta.0 => 6.5.0-beta.0
    @storybook/react: 6.5.0-beta.0 => 6.5.0-beta.0

**Additional context**
![image](https://user-images.githubusercontent.com/34785917/166185924-7f4a5770-be2c-4c19-a187-ab7ad42a36c4.png)

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
