### ISSUE TITLE
Canvas doc block crashes when child Story uses CURRENT_SELECTION

### ISSUE THREAD

**Issue by quickgiant** [storybookjs/storybook#18128]
**Describe the bug**
If a Canvas doc block includes a Story element child with an ID using the `CURRENT_SELECTION` token (so "."), the canvas crashes when trying to load the story. In MDX, this would look like:
```
import { Story, Canvas, CURRENT_SELECTION } from '@storybook/addon-docs';

<Canvas>
  <Story id={CURRENT_SELECTION} />
</Canvas>
```

**To Reproduce**
The issue is reproducible in the current `official-storybook`, see: https://storybookjs.netlify.app/official-storybook/?path=/docs/addons-docs-mdx-id--hello-story

The "Selected" section includes a canvas that never loads, with the following error appearing in the console:
```
Uncaught (in promise) Error: Couldn't find story matching '.' after HMR.
- Did you remove it from your CSF file?
- Are you sure a story with that id exists?
- Please check your stories field of your main.js config.
- Also check the browser console and terminal for error messages.
    at StoryIndexStore.storyIdToEntry (main.9d9c372f.iframe.bundle.js:1:2370011)
    at StoryStore.loadCSFFileByStoryId (main.9d9c372f.iframe.bundle.js:1:2410935)
    at StoryStore._callee2$ (main.9d9c372f.iframe.bundle.js:1:2412535)
    at tryCatch (vendors~main.2a3d0c3f.iframe.bundle.js:2:2677990)
    at Generator.invoke [as _invoke] (vendors~main.2a3d0c3f.iframe.bundle.js:2:2677613)
    at Generator.next (vendors~main.2a3d0c3f.iframe.bundle.js:2:2678756)
    at StoryStore_asyncGeneratorStep (main.9d9c372f.iframe.bundle.js:1:2404550)
    at _next (main.9d9c372f.iframe.bundle.js:1:2404862)
```

**Additional context**
It appears the issue was introduced in this commit: https://github.com/storybookjs/storybook/commit/094089eea986fc345cbe692fbc229757670e2226, in which a `useStories` hook call was added without handling the `CURRENT_SELECTION` token like is the case with other blocks, for example:
https://github.com/storybookjs/storybook/blob/114a77cf70ea3db5b843caf88c3ebe7ef5933dba/addons/docs/src/blocks/Source.tsx#L107-L109

The fix is pretty straightforward, just need to add similar handling to fallback to the context story ID.

**Comment by shilman** [comment]
Hurrah!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-beta.4 containing PR #18130 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
