### ISSUE TITLE
Changes made to controls and args doesn't reflect in Storybook UI

### ISSUE THREAD

**Issue by vish01** [storybookjs/storybook#18139]
**Describe the bug**
As mentioned in [Issue#52](https://github.com/storybookjs/builder-vite/issues/52#issuecomment-1116904796) If you make a change to a control, and then try to also change the arg in the story file, then you'll see the changes doesn't reflect in Storybook. This happens in both `vite-builder` and `webpack-builder`.

**To Reproduce**
[Reproduction](https://github.com/vish01/svelte-storybook)

**System**
``` Environment Info:

  System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  Binaries:
    Node: 14.19.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.1.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: master_preferences.txt
    Edge: Spartan (44.18362.449.0)
  npmPackages:
    @storybook/addon-actions: ^6.4.22 => 6.4.22
    @storybook/addon-essentials: ^6.4.22 => 6.4.22
    @storybook/addon-links: ^6.4.22 => 6.4.22
    @storybook/addon-postcss: ^2.0.0 => 2.0.0
    @storybook/addon-svelte-csf: ^2.0.3 => 2.0.3
    @storybook/builder-vite: ^0.1.30 => 0.1.33
    @storybook/svelte: ^6.4.22 => 6.4.22```

**Additional context**
When you serve Storybook, open `Card.stories.svelte` file, modify any of the controls, for example `justifyHeader` and then change the args value for it and you'll see the changes doesn't reflect in the UI, but if you make a change in controls from Storybook UI, it'll work fine.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
