### ISSUE TITLE
Controls: Reset button broken for `!undefined` URL values

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#18143]
When you set the value to an arg as `!undefined` in the URL, e.g. by following the reproduction steps in https://github.com/storybookjs/storybook/pull/18135, then hit the "reset" button in the controls UI, you would expect the story to return to its original state (equivalent of deleting `args=xxx` from the URL). However it retains the `!undefined` value.

<img width="1085" alt="Mouse_Highlight_Overlay" src="https://user-images.githubusercontent.com/488689/166884481-7671b945-f6e4-493a-8f5c-5b9c19456782.png">

**Comment by Tomastomaslol** [comment]
https://storybook.js.org/docs/react/writing-stories/args#setting-args-through-the-url

It looks like `!` was a feature that was documented and intended to be used by passing values through the URL as prameters. 

I opened PR https://github.com/storybookjs/storybook/pull/18231 which fixes the issue by resetting all args to their initial value. Please let me know if this is a suitable fix! 🙂
