### ISSUE TITLE
Snapshot test are failing in components with redux-tool

### ISSUE THREAD

**Issue by xavigimenezsanchez** [storybookjs/storybook#18163]
**Describe the bug**
Snapshot test are failing in components that are using redux-tool "dispatch" with this error: "Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops."

**To Reproduce**
You must to run the tests: react-scripts test

**System**
Environment Info:

  System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (101.0.1210.32)
  npmPackages:
    @storybook/addon-actions: ^6.5.0-beta.1 => 6.5.0-beta.1
    @storybook/addon-essentials: ^6.5.0-beta.1 => 6.5.0-beta.1
    @storybook/addon-interactions: ^6.5.0-beta.1 => 6.5.0-beta.1
    @storybook/addon-links: ^6.5.0-beta.1 => 6.5.0-beta.1
    @storybook/addon-storyshots: ^6.5.0-beta.1 => 6.5.0-beta.1
    @storybook/builder-webpack5: ^6.5.0-beta.1 => 6.5.0-beta.1
    @storybook/manager-webpack5: ^6.5.0-beta.1 => 6.5.0-beta.1
    @storybook/node-logger: ^6.5.0-beta.1 => 6.5.0-beta.1
    @storybook/preset-create-react-app: ^4.1.0 => 4.1.0
    @storybook/react: ^6.5.0-beta.1 => 6.5.0-beta.1
    @storybook/testing-library: ^0.0.11 => 0.0.11

**Additional context**
the storybook.test.js has this code:
```
import initStoryshots from "@storybook/addon-storyshots";
import { render } from "@testing-library/react";

const reactTestingLibrarySerializer = {
  print: (val, serialize, indent) => serialize(val.container.firstChild),
  test: (val) => val && val.hasOwnProperty("container"),
};

initStoryshots({
  renderer: render,
  snapshotSerializers: [reactTestingLibrarySerializer],
});
```

**Comment by xavigimenezsanchez** [comment]
Yes, it is, with the 6.4 version is working. However, we want to migrate to react 18 and we have just started to test all our apps and components with the react 18. One thing we did in this test environment was an upgrade to storybook to a 15-beta version. With this 15-beta version, all is ok except the storyshots.

**Comment by ndelangen** [comment]
The future of storyshots is the test-runner:
https://storybook.js.org/docs/react/writing-tests/test-runner#page-top

And use the play function for expectations:
https://storybook.js.org/docs/react/writing-stories/play-function#page-top

We will not be making any improvement / changes to storyshots.
