### ISSUE TITLE
Storybook loops when component uses `ref` and `lodash/get`

### ISSUE THREAD

**Issue by 30simo** [storybookjs/storybook#18161]
Hi 😊

I'm facing an issue when trying to interact with a story. The components used in the story work fine in our production environment.

**Describe the bug**
When trying to interact with the story using its buttons, no action is performed and Storybook starts looping.

**To Reproduce**
Repository: https://github.com/30simo/my-storybook-reproduction
Reproduction: https://www.chromatic.com/builds?appId=62751e3a7ae4db004a2440e7

**System**

```bash
Environment Info:

  System:
    OS: macOS 12.3.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 16.7.0 - ~/.nvm/versions/node/v16.7.0/bin/node
    Yarn: 3.2.0 - ~/.nvm/versions/node/v17.4.0/bin/yarn
    npm: 7.20.3 - ~/.nvm/versions/node/v16.7.0/bin/npm
  Browsers:
    Chrome: 101.0.4951.54
    Firefox: 97.0
    Safari: 15.4
  npmPackages:
    @storybook/addon-actions: ^6.5.0-beta.6 => 6.5.0-beta.6 
    @storybook/addon-docs: ^6.5.0-beta.6 => 6.5.0-beta.6 
    @storybook/addon-essentials: ^6.5.0-beta.6 => 6.5.0-beta.6 
    @storybook/addon-interactions: ^6.5.0-beta.6 => 6.5.0-beta.6 
    @storybook/addon-links: ^6.5.0-beta.6 => 6.5.0-beta.6 
    @storybook/builder-webpack4: ^6.5.0-beta.6 => 6.5.0-beta.6 
    @storybook/manager-webpack4: ^6.5.0-beta.6 => 6.5.0-beta.6 
    @storybook/react: ^6.5.0-beta.6 => 6.5.0-beta.6 
    @storybook/testing-library: ^0.0.11 => 0.0.11
```

Let me know if there is any additional information I can provide you with, and thank you for your time!

**Comment by kibs** [comment]
Same issue in my storybook, when using react-hook-form, storybook loops / freezes when using controls

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
