### ISSUE TITLE
Add managerWebpack/managerBabel... types

### ISSUE THREAD

**Issue by dohooo** [storybookjs/storybook#18171]
**Describe the solution you'd like**
Add managerWebpack/managerBabel types to StorybookConfig interface.

**Are you able to assist to bring the feature to reality?**
yes, I can.

**Additional context**
Why managerWebpack/managerBabel... types are not included? Is there have any other plan?

**Comment by MichaelArestad** [comment]
Thanks @dohooo. We have plans to prebundle the manager in the next major release and are removing the corresponding configurations. I am going to close this for now.

For now, you can augment the Storybook config type or ignore the TS issues.
