### ISSUE TITLE
>= v6.5.0-beta.2 breaks on build-storybook; looking for package.json in wrong directory

### ISSUE THREAD

**Issue by stephenhebert** [storybookjs/storybook#18189]
**Describe the bug**
After updating storybook packages from v6.5.0-beta.1 to v6.5.0-beta.2, I receive this error when running `build-storybook`:
```
ERR! Error: /Users/stephenhebert/source/repos/teamup_all/package.json: ENOENT: no such file or directory, open '/Users/stephenhebert/source/repos/teamup_all/package.json'
```

My repo is a monorepo and this project/storybook/package.json are located in a subdirectory of the one referenced in the error.

**System**
Environment Info:

  System:
    OS: macOS 11.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 14.17.3 - ~/.nvm/versions/node/v14.17.3/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.3/bin/npm
  Browsers:
    Chrome: 101.0.4951.54
    Safari: 15.1
  npmPackages:
    @storybook/addon-a11y: 6.5.0-beta.2 => 6.5.0-beta.2 
    @storybook/addon-actions: 6.5.0-beta.2 => 6.5.0-beta.2 
    @storybook/addon-essentials: 6.5.0-beta.2 => 6.5.0-beta.2 
    @storybook/addon-storysource: 6.5.0-beta.2 => 6.5.0-beta.2 
    @storybook/addons: 6.5.0-beta.2 => 6.5.0-beta.2 
    @storybook/api: 6.5.0-beta.2 => 6.5.0-beta.2 
    @storybook/builder-vite: ^0.1.28 => 0.1.28 
    @storybook/components: 6.5.0-beta.2 => 6.5.0-beta.2 
    @storybook/core-common: 6.5.0-beta.2 => 6.5.0-beta.2 
    @storybook/core-events: 6.5.0-beta.2 => 6.5.0-beta.2 
    @storybook/theming: 6.5.0-beta.2 => 6.5.0-beta.2 
    @storybook/vue3: 6.5.0-beta.2 => 6.5.0-beta.2

**Comment by aneesijaz** [comment]
Same issue for me ...
and yes the storybook is not in the root of repo but in a sub directory ..

**Comment by wesley-at-hl** [comment]
Same issue, and this only happens in `6.5.0-beta.2`. `6.5.0-beta.1` works.

**Comment by mrkiffie** [comment]
Linking my [comment](https://github.com/storybookjs/storybook/issues/18229#issuecomment-1130572027) and  [reproduction repo that uses git submodules](https://github.com/mrkiffie/storybook-parent-repo#storybook-submodule-repo-issue) that encounters this issue too.

**Comment by IanVS** [comment]
This is fixed in https://github.com/storybookjs/storybook/pull/18259.  Please try out [6.5.2](https://github.com/storybookjs/storybook/releases/tag/v6.5.2) and let us know if you're still having problems.
