### ISSUE TITLE
Storyshots fail on Node 18

### ISSUE THREAD

**Issue by chrischen** [storybookjs/storybook#18188]
**Describe the bug**
Storyshots no longer work due to an error when calling initStoryshots().

```
 TypeError: Cannot redefine property: onkeydown

      18 | };
      19 |
    > 20 | initStoryshots(...
```

**To Reproduce**
[ I'm currently doing the repro]

Upgrade to Node 18.0.0. Call initStoryshots(). Works if Node downgraded < 18.0.0.

**System**
  System:
    OS: macOS 12.3.1
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 18.0.0 - /opt/homebrew/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 8.6.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 101.0.4951.54
    Firefox: 97.0.2
    Safari: 15.4

**Additional context**

**Comment by bkinsey808** [comment]
I'm getting this error too.

**Comment by ModestFun** [comment]
+1

**Comment by nipendraaristeiaservices** [comment]
I'm also getting same error with 
node 18.0.0. 
Mac OS: 12.6
CPU: Apple M1

**Comment by antonstagge** [comment]
Same here. 
Any plans on adding support for node 18?

**Comment by yamamotoa-lvgs** [comment]
same error too

**Comment by jonniebigodes** [comment]
The Storyshots addon is officially deprecated and will be removed in a future release of Storybook. To help with the transition process, we've created a [migration guide](https://storybook.js.org/docs/writing-tests/storyshots-migration-guide) for the available options and common use cases.
