### ISSUE TITLE
Number precision lost when parsing args param

### ISSUE THREAD

**Issue by evont** [storybookjs/storybook#18190]
**Describe the bug**
When parsing args param from url, if the value str is larger than `Number.MAX_SAFE_INTEGER`, it will lost it's precision, for example, `12345678912345678911 ` will be changed to `12345678912345680000`.

The reason is that the `QS_OPTIONS`'s decoder in `parseArgsParam` (the code is in `@storybook/preview-web` package) use `NUMBER_REGEXP` to test the value and then use `Number` to transform it.

**To Reproduce**
Reproduction deployed with Chromatic: (https://6278daae5c4c08004af772e2-pwgaxlawbd.chromatic.com/?path=/story/bigint--template

type `12345678912345678911` in `num`, then refresh the page, the number will be changed to `12345678912345680000 `

The reproduction can be cloned from the following repo:
https://github.com/evont/my-storybook-reproduction

**System**
OS: macOS 12.2.1
CPU: (10) arm64 Apple M1 Pro
Binaries:
Node: 17.4.0 - /opt/homebrew/bin/node
Yarn: 3.2.0 - /opt/homebrew/bin/yarn
npm: 8.3.1 - /opt/homebrew/bin/npm
Browsers:
Chrome: 101.0.4951.54
Safari: 15.3
npmPackages:
@storybook/addon-actions: ^6.5.0-beta.7 => 6.5.0-beta.7
@storybook/addon-docs: ^6.5.0-beta.7 => 6.5.0-beta.7
@storybook/addon-essentials: ^6.5.0-beta.7 => 6.5.0-beta.7
@storybook/addon-interactions: ^6.5.0-beta.7 => 6.5.0-beta.7
@storybook/addon-links: ^6.5.0-beta.7 => 6.5.0-beta.7
@storybook/builder-webpack4: ^6.5.0-beta.7 => 6.5.0-beta.7
@storybook/manager-webpack4: ^6.5.0-beta.7 => 6.5.0-beta.7
@storybook/react: ^6.5.0-beta.7 => 6.5.0-beta.7
@storybook/testing-library: ^0.0.11 => 0.0.11

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
