### ISSUE TITLE
react-query-devtools

### ISSUE THREAD

**Issue by haticecs** [storybookjs/storybook#18219]
I want to use react-query-devtools with some of the stories. I tried using it inside example with decorator. It didn't work.

```
export default {
  component: BasicComponent,
  decorators: [withQueryDevTools]
};

export const Basic = () => <BasicComponent />;
```

The error is Unable to render story examples--basic as the component annotation is missing from the default export.
Is there ayn way to use react-query-devtools with storybook?

**Comment by Mexflubber** [comment]
@haticecs where did you get "withQueryDevTools" decorator from ?
