### ISSUE TITLE
Storybook is loading forever (CRA@4)

### ISSUE THREAD

**Issue by johannespein** [storybookjs/storybook#18221]
**Describe the bug**
I'm trying to get storybook running for a CRA project with `react-scripts v4.0.3`.
When I access the browser page, the storybook loading spinner is shown forever. 
On the network I can see `GET` to `https://storybook.chakra-ui.com/metadata.json?version=1.8.3` failing. But even when using 
```
refs: {
    '@chakra-ui/react': {
      disable: true,
    },
  },
```
the behavior is the same. The EventStream of the `http://localhost:9009/progress` request does not show anything.
 
![image](https://user-images.githubusercontent.com/6628527/168279147-004be602-9e3e-4e7d-9561-777af1cde1fb.png)

 I tried many different versions (including `storybook v6.5.0-beta.8`), but none worked for my project. 

```
**System**
    OS: Linux 5.15 Ubuntu 22.04 LTS 22.04 LTS (Jammy Jellyfish)
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
  Binaries:
    Node: 14.19.0 - ~/.nvm/versions/node/v14.19.0/bin/node
    Yarn: 1.22.17 - /home/linuxbrew/.linuxbrew/bin/yarn
    npm: 6.14.16 - ~/.nvm/versions/node/v14.19.0/bin/npm
  Browsers:
    Chrome: 101.0.4951.54
    Firefox: 100.0
  npmPackages:
    @storybook/addon-actions: ^6.4.22 => 6.4.22 
    @storybook/addon-essentials: ^6.4.22 => 6.4.22 
    @storybook/addon-interactions: ^6.4.22 => 6.4.22 
    @storybook/addon-links: ^6.4.22 => 6.4.22 
    @storybook/node-logger: ^6.4.22 => 6.4.22 
    @storybook/preset-create-react-app: ^3.2.0 => 3.2.0 
    @storybook/react: ^6.4.22 => 6.4.22 
    @storybook/testing-library: ^0.0.11 => 0.0.11 
```

**Comment by srmagura** [comment]
I started experiencing the infinite loading indicator after upgrading my react-scripts 4 project from React 16 to React 18. I got the same behavior even after upgrading Storybook to the latest prerelease version, `6.5.0-beta.8`.

**I've created a minimal repro of the problem here: https://github.com/srmagura/sb-react18-repro.** The repository's README contains instructions for running the code.

**Comment by tmeasday** [comment]
Thanks for the reproduction @srmagura I appreciate it. What I am seeing here is that `/iframe.html` simply serves: 

```
static/media/index.bfaa82af.ejs%
```

**Comment by tmeasday** [comment]
So the issue here is that you are using `@storybook/preset-create-react-app@4.x` which is only compatible with CRA@5. If you downgrade to `@storybook/preset-create-react-app@3.x` you'll see the problem is resolved.

I'll update the preset docs to make this more clear.
