### ISSUE TITLE
Emotion `:first-child` console errors: `ArgsTable` component

### ISSUE THREAD

**Issue by m7kvqbe1** [storybookjs/storybook#18232]
Storybook version: `6.5.0-beta.6`

The docs addon (specifically the [`ArgsTable` `TableWrapper` component](https://github.com/storybookjs/storybook/blob/783e5aaf26dc4c5312133dffca29caa543abad7c/lib/components/src/blocks/ArgsTable/ArgsTable.tsx#L14)) is causing Emotion to issue the dreaded `:first-child` console error for us. This is despite the `ignoreSsrWarning` work around supposedly appearing to have been applied in the source for that component.

Is it possible the comment is being stripped or something? I can see it in other places.

![Screenshot 2022-05-16 at 11 09 10](https://user-images.githubusercontent.com/48086589/168570286-22e5a7c1-6145-42bb-9a6b-99f09cd8f602.png)

**Comment by gregorybolkenstijn** [comment]
Getting this on both 6.5.0 and 6.5.3 as well.

**Comment by symmetriq** [comment]
Still happening in 6.5.5.

**Comment by xxxKOTxxx** [comment]
Same problem in 6.5.7
