### ISSUE TITLE
Using conditional statements in the default export CSF format.

### ISSUE THREAD

**Issue by mikokofuyu** [storybookjs/storybook#18233]
**Describe the bug**

I am trying to use an environment variable to change the `excludedStories` property in the default export. But it causes the story to fail to build.

The following solutions do not work.

```js

// handling the conditional in-line

export default {
    title: 'Atoms/Button',
    component: Button,
    excludeStories: isVisualTestingMode ? ['SecondaryButton', 'PlayButton'] : [];
};
```

```js
// Handling the conditional in a const

const excludeStories = isVisualTestingMode ? ['SecondaryButton', 'PlayButton'] : [];

export default {
    title: 'Atoms/Button',
    component: Button,
    excludeStories: excludeStories
};
```

However I did manage to get a very odd solution to work (see below) this leads me to believe there is some issue with how the default export handles conditionals?

```js
const objectOfStuff = { title: 'Atoms/Button', component: Button };

if (isVisualTestingMode) {
    objectOfStuff.excludeStories = ['SecondaryButton', 'PlayButton'];
}

export default objectOfStuff;
```

**Comment by mikokofuyu** [comment]
**Update** I think upgrading to v6.5 actually breaks the hacky workaround solution I found too. So it would be really good to get this looked into.

**Comment by shilman** [comment]
RFC here: https://github.com/storybookjs/storybook/discussions/25535

Implementation here: https://github.com/storybookjs/storybook/pull/25328

You can use two different config files depending on which environment you're in
