### ISSUE TITLE
Controls are not changing templates in Docs

### ISSUE THREAD

**Issue by DzmVasileusky** [storybookjs/storybook#18236]
**Describe the bug**
Customizable controls are perfectly changing a look of the component in Canvas but it is not working for Docs addon.
Without that developers can't look how code example with changed property is looking like.

**To Reproduce**
```
import { MatButtonModule } from '@angular/material/button';
import { Meta, moduleMetadata, Story } from '@storybook/angular';

export default {
    argTypes: {
        disabled: {
            defaultValue: '',
            description: 'Disabled state',
            options: ['', 'disabled'],
            control: {
                labels: {
                    '': 'Active',
                    'disabled': 'Disabled'
                },
                type: 'radio'
            }
        }
    },
    decorators: [
        moduleMetadata({
            imports: [MatButtonModule]
        })
    ]
} as Meta;

export const Primary: Story = (args) => ({
    props: args,
    template: `<button mat-button ${args.disabled}>Button</button>`
});
Primary.args = {
    disabled: ''
}
```

**System**
Please paste the results of `npx sb@next info` here.

**Additional context**
Screenshots of the following behaviour for Canvas and Docs

<img width="1182" alt="1" src="https://user-images.githubusercontent.com/10651174/168655591-4b443d9f-913e-4bcb-bd39-5073671864cf.png">
<img width="1201" alt="2" src="https://user-images.githubusercontent.com/10651174/168655642-eefe8468-4f5c-468c-8e28-8e1112450540.png">

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
