### ISSUE TITLE
[controls] Story title is deeper than 2 levels, controls only show in docs tab

### ISSUE THREAD

**Issue by fredboyle** [storybookjs/storybook#18239]
**Describe the bug**
When story has a title that goes beyond 2 levels of depth (i.e. 'Components/Nav/Global') then controls don't show in the canvas tab, only in the docs tab.

**To Reproduce**
1. Create a story with a `title:` value of `Components/Nav/Global`
2. Ensure the story has args
3. Start Storybook to see the controls don't show in the "Canvas" tab
4. Edit the story to have a `title:` value of `Components/Nav`
5. View the story with controls

**System**
```
Environment Info:

  System:
    OS: macOS 12.3.1
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.15 - ~/.nvm/versions/node/v16.13.1/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
  Browsers:
    Chrome: 101.0.4951.64
    Safari: 15.4
  npmPackages:
    @storybook/addon-a11y: ~6.4.22 => 6.4.22 
    @storybook/addon-essentials: ~6.4.22 => 6.4.22 
    @storybook/addon-knobs: ~6.4.0 => 6.4.0 
    @storybook/addon-links: ~6.4.22 => 6.4.22 
    @storybook/addon-postcss: ~2.0.0 => 2.0.0 
    @storybook/builder-webpack5: ~6.4.22 => 6.4.22 
    @storybook/manager-webpack5: ~6.4.22 => 6.4.22 
    @storybook/react: ~6.4.22 => 6.4.22 
    @storybook/storybook-deployer: ~2.8.11 => 2.8.11
```

**Additional context**
Controls don't show:
```js
export default {
  title: 'Components/Navigations/Side',
  component: SideNavigation,
}
```

Controls do show:
```js
export default {
  title: 'Components/Navigations',
  component: SideNavigation,
}
```

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
