### ISSUE TITLE
TypeScript checking for the monorepo during development

### ISSUE THREAD

**Issue by okonet** [storybookjs/storybook#18249]
**Is your feature request related to a problem? Please describe**

While working on some PRs I've noticed that there is no type checks in place between packages. 

For example, while having https://github.com/storybookjs/storybook/blob/ca2441260bdf2eaf29e6cf58d34bde60856ca7e9/lib/components/src/syntaxhighlighter/syntaxhighlighter.tsx open and removing https://github.com/storybookjs/storybook/blob/62439ad2a2810876a7fd48e5ed691dbcb79d21a0/lib/theming/src/types.ts#L89
I would expect `syntaxhighlighter.tsx` to get a TS error but it doesn't.

This is happening because the bootstrap script pre-builds all the packages and later on, other packages depend on the compiled code. So there is no static analysis outside of the package being currently edited.

**Describe the solution you'd like**

One of the main benefits of the monorepo is to get integrated code earlier on. Type checking is the crucial part of it and the shorter the feedback loop is the better. While working on https://github.com/storybookjs/storybook/pull/18146 I was certain I'm done with the refactoring only to realize I broke a lot of usages after I pushed my code to GitHub and waited for CI to finish. 

I would define the requirements as follows:

- Type checking of the whole monorepo (or at least major parts of it) while working locally
- IDEs should be able to resolve to proper packages not `/dist` when "Go to declaration" is used
- Refactorings in editors should work across all packages 
- Ideally, without the need to re-compile the whole project's source code
- Faster compilation times of packages (probably out of scope but who knows)

**Describe alternatives you've considered**

See https://github.com/storybookjs/storybook/pull/18194 after reading the following:

- https://nx.dev/migration/adding-to-monorepo#enabling-js-analysis
- https://www.typescriptlang.org/tsconfig/#paths
- https://maxrohde.com/2021/11/20/the-ultimate-guide-to-typescript-monorepos/
- https://www.typescriptlang.org/docs/handbook/project-references.html
- https://www.typescriptlang.org/tsconfig#composite
- https://github.com/jaimesangcap/lerna-ts-monorepo

but I didn't succeed to make it work.

**Are you able to assist to bring the feature to reality?**

Yes

**Comment by Andarist** [comment]
> This is happening because the bootstrap script pre-builds all the packages and later on, other packages depend on the compiled code. So there is no static analysis outside of the package being currently edited.

This should be solvable with project references - in fact with them you shouldn't even have to prebuild anything to get a good IDE experience. However, prebuilding + recompiling on watch might be better for startup times and overall performance. YMMV, it depends on the size of the monorepo in question

**Comment by Andarist** [comment]
@ndelangen out of curiosity - what did you end up with? I couldn't quickly find a related PR

**Comment by okonet** [comment]
I’m also curious! 😁
