### ISSUE TITLE
Cannot read properties of undefined (reading 'isBatchingLegacy')

### ISSUE THREAD

**Issue by jonsoku2** [storybookjs/storybook#18240]
**Describe the bug**
occurred error, when installed`@emotion/styled` and `@emotion/react`
repo: https://github.com/jonsoku2/turbo-tsdx-emotion-storybook

**To Reproduce**
Please create a reproduction by running `npx sb@next repro` and following the instructions. Read our [documentation](https://storybook.js.org/docs/react/contribute/how-to-reproduce) to learn more about creating reproductions.
Paste your repository and deployed reproduction here. We prioritize issues with reproductions over those without.

**System**
Please paste the results of `npx sb@next info` here.

Environment Info:

  System:
    OS: macOS 12.2
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
  Browsers:
    Chrome: 101.0.4951.64
    Safari: 15.3
  npmPackages:
    @storybook/addon-actions: ^6.4.22 => 6.4.22 
    @storybook/addon-docs: ^6.4.22 => 6.4.22 
    @storybook/addon-essentials: ^6.4.22 => 6.4.22 
    @storybook/addon-info: ^5.3.21 => 5.3.21 
    @storybook/addon-interactions: ^6.4.22 => 6.4.22 
    @storybook/addon-links: ^6.4.22 => 6.4.22 
    @storybook/builder-webpack5: ^6.4.22 => 6.4.22 
    @storybook/manager-webpack5: ^6.4.22 => 6.4.22 
    @storybook/react: ^6.4.22 => 6.4.22 

**Additional context**
<img width="860" alt="image" src="https://user-images.githubusercontent.com/51524954/168727771-1d66bb4c-106f-40c2-9182-27615ff3df11.png">

Please help me...

**Comment by hyochan** [comment]
Same problem here

**Comment by lauthieb** [comment]
Same here

**Comment by RebeccaWangCM** [comment]
same problem here

**Comment by DannyClaydenChambers** [comment]
Same

**Comment by alex-medgrupo** [comment]
same

**Comment by CIDBerlin** [comment]
Same problem here

**Comment by pakholeung37** [comment]
same

**Comment by pakholeung37** [comment]
Maybe it's not a storybook bug. I found out I have React 16.8 and react-dom 18.2 installed

**Comment by adiusz** [comment]
same

**Comment by wavinginspace** [comment]
same

**Comment by mmmpop** [comment]
I've encountered this issue while upgrading to ^7.0.0-alpha.23. It seems that the Storyshots add-on is throwing the error.

**Comment by YoanDo** [comment]
same issue

**Comment by bralandealmeida** [comment]
same here

**Comment by mynameisgenesis** [comment]
I ended up going back to react-test-renderer@16.14.0 and the tests worked for me. This is what my dependencies look like now:
`  },
  "dependencies": {
    "expo": "44.0.0",
    "expo-linear-gradient": "11.0.3",
    "expo-status-bar": "1.2.0",
    "jest": "29.1.2",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-native": "0.64.3",
    "react-native-web": "0.17.1",
    "react-test-renderer": "16.14.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9"
  },`

**Comment by ndelangen** [comment]
This is fixed in storybook 7.0 beta.
