### ISSUE TITLE
Storybook 6.5 does not work with vue 3

### ISSUE THREAD

**Issue by bodograumann** [storybookjs/storybook#18264]
**Describe the bug**
When trying to create a storybook reproduction setup, even the default vue 3 configuration does not work. It shows the following error:

```
ERR! TypeError: Cannot read properties of undefined (reading 'NormalModule')
ERR!     at VueLoaderPlugin.apply (/home/bodo/Experiments/storybook-6.5-vue3/node_modules/@storybook/vue3/node_modules/vue-loader/dist/pluginWebpack5.js:44:47)
ERR!     at webpack (/home/bodo/Experiments/storybook-6.5-vue3/node_modules/webpack/lib/webpack.js:51:13)
ERR!     at starterGeneratorFn (/home/bodo/Experiments/storybook-6.5-vue3/node_modules/@storybook/builder-webpack4/dist/cjs/index.js:137:18)
ERR!     at starterGeneratorFn.next (<anonymous>)
ERR!     at Object.start (/home/bodo/Experiments/storybook-6.5-vue3/node_modules/@storybook/builder-webpack4/dist/cjs/index.js:275:34)
ERR!     at async Promise.all (index 0)
ERR!     at async storybookDevServer (/home/bodo/Experiments/storybook-6.5-vue3/node_modules/@storybook/core-server/dist/cjs/dev-server.js:207:28)
ERR!     at async buildDevStandalone (/home/bodo/Experiments/storybook-6.5-vue3/node_modules/@storybook/core-server/dist/cjs/build-dev.js:120:31)
ERR!     at async buildDev (/home/bodo/Experiments/storybook-6.5-vue3/node_modules/@storybook/core-server/dist/cjs/build-dev.js:174:5)
ERR!  TypeError: Cannot read properties of undefined (reading 'NormalModule')
ERR!     at VueLoaderPlugin.apply (/home/bodo/Experiments/storybook-6.5-vue3/node_modules/@storybook/vue3/node_modules/vue-loader/dist/pluginWebpack5.js:44:47)
ERR!     at webpack (/home/bodo/Experiments/storybook-6.5-vue3/node_modules/webpack/lib/webpack.js:51:13)
ERR!     at starterGeneratorFn (/home/bodo/Experiments/storybook-6.5-vue3/node_modules/@storybook/builder-webpack4/dist/cjs/index.js:137:18)
ERR!     at starterGeneratorFn.next (<anonymous>)
ERR!     at Object.start (/home/bodo/Experiments/storybook-6.5-vue3/node_modules/@storybook/builder-webpack4/dist/cjs/index.js:275:34)
ERR!     at async Promise.all (index 0)
ERR!     at async storybookDevServer (/home/bodo/Experiments/storybook-6.5-vue3/node_modules/@storybook/core-server/dist/cjs/dev-server.js:207:28)
ERR!     at async buildDevStandalone (/home/bodo/Experiments/storybook-6.5-vue3/node_modules/@storybook/core-server/dist/cjs/build-dev.js:120:31)
ERR!     at async buildDev (/home/bodo/Experiments/storybook-6.5-vue3/node_modules/@storybook/core-server/dist/cjs/build-dev.js:174:5)
```

**To Reproduce**
Execute `npx "sb@^6.5" repro` to create a storybook 6.5 and select the vue 3 template.
Start the storybook server with `yarn storybook`.

I have published such an example here: https://github.com/bodograumann/storybook-6.5-vue3

**System**
```
> npx sb@next info
Need to install the following packages:
  sb@next
Ok to proceed? (y)
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.

Environment Info:

  System:
    OS: Linux 5.17 Arch Linux
    CPU: (4) x64 Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz
  Binaries:
    Node: 16.15.0 - /usr/bin/node
    Yarn: 3.2.1 - ~/.local/bin/yarn
    npm: 8.5.5 - /usr/bin/npm
  Browsers:
    Firefox: 100.0
  npmPackages:
    @storybook/addon-actions: ^6.5.0 => 6.5.0
    @storybook/addon-docs: ^6.5.0 => 6.5.0
    @storybook/addon-essentials: ^6.5.0 => 6.5.0
    @storybook/addon-interactions: ^6.5.0 => 6.5.0
    @storybook/addon-links: ^6.5.0 => 6.5.0
    @storybook/builder-webpack4: ^6.5.0 => 6.5.0
    @storybook/manager-webpack4: ^6.5.0 => 6.5.0
    @storybook/testing-library: ^0.0.11 => 0.0.11
    @storybook/vue3: ^6.5.0 => 6.5.0
  npmGlobalPackages:
    @storybook/cli: 6.5.0
```

**Comment by symmetriq** [comment]
I'm seeing exactly the same error here after upgrading to Storybook 6.5.0 in a Vue 3 project.

**Comment by xorinzor** [comment]
Any chance my issue might be related? https://github.com/storybookjs/storybook/discussions/18271

**Comment by Simolation** [comment]
When using https://github.com/storybookjs/builder-vite the issue is gone, and it works, but also had the same crash when upgrading from 6.4 to 6.5. Luckily, I already intended to move to Vite, as everything else in the project is using Vite.

**Comment by shilman** [comment]
@yannbf looks like perhaps the last-minute webpack5 autodetection code broke vue3. you can see that @bodograumann 's repro is using builder/manager-webpack4. can you please look into this today? thanks! 🙏

**Comment by yannbf** [comment]
Hey @bodograumann thank you so much for opening this issue, even more for providing a repro. I'm on it!

**Comment by yannbf** [comment]
Alright so the reason this is happening is because vue-loader provides both webpack4Plugin and webpack5Plugin, then [checks the version of webpack](https://github.com/vuejs/vue-loader/blob/next/src/plugin.ts#L1) to know which plugin to use. When requiring webpack, it will get it from `<rootDir>/node_modules/@storybook/vue3/node_modules/webpack`, and because the [dependency version range for webpack was expanded](https://github.com/storybookjs/storybook/pull/17834/files#diff-e9d8ce3cbfc2f9480e4bc98575d34b8e7979d871be192743c1a7705f5a15a5f4R67), the webpack installed under @storybook/vue3 will be the latest (5.72.1 as of now). Even if the builder is defined as webpack4 in Storybook, the `vue-loader` plugin will end up using its webpack5 implementation, which will break.

**Comment by ndelangen** [comment]
1 work around would be to provide a resolution in package.json for webpack, I guess.

**Comment by ndelangen** [comment]
The version range of storybook allows for both:
https://github.com/storybookjs/storybook/blob/de741e3e6b8de8bcd4a8d5db37b5ee4c1d805a4e/app/vue3/package.json#L67

The issue is that the package manager doesn't seem to install the same version as the user specified? Instead opting to install a newer version because it's technically allowed by storybook.

We could change it to a peerDependency, but does that change anything? NPM installs peerDependencies by default, and yarn with pnp enabled will start complaining if the user doesn't have a direct dependency on webpack at all.

It feels like that will not solve the issue at all, and potentially make it worse?

**Comment by uoc1691** [comment]
Having this issue when upgrading from 6.4 to 6.5.


<img width="172" alt="image" src="https://user-images.githubusercontent.com/1751412/184795220-461da4e5-74f9-42e0-9d6f-3eed30a47d18.png">

<img width="390" alt="image" src="https://user-images.githubusercontent.com/1751412/184795461-a35b6aa3-307d-46ea-bec9-b145d4e52877.png">


<img width="808" alt="image" src="https://user-images.githubusercontent.com/1751412/184795182-09a85640-76b9-407e-b1aa-2f050c027e12.png">

**Comment by uoc1691** [comment]
### Solution worked for me

**_Backgroud_**: Project is upgraded to use **Webpack 5**. No need for Webpack 4.

If you see the error, it's referring to builder-webpack4. 
![image](https://user-images.githubusercontent.com/1751412/184796784-e1f23b7e-4397-4285-b9f9-a165e587cce7.png)

Fix:
Install **@storybook/manager-webpack5** and **@storybook/builder-webpack5** as dev dependencies.
Modify main.js and specify webpack5 as the builder.

<img width="105" alt="image" src="https://user-images.githubusercontent.com/1751412/184797001-a8d674d2-38bf-4692-b31c-cb9526659121.png">

**Comment by symmetriq** [comment]
I tried all of the above suggestions, and am still seeing the same error when I try to start Storybook.

**Comment by symmetriq** [comment]
Thanks @uoc1691 — I've got Storybook 6.5.12 working with Vue 3 now.

**Comment by bodograumann** [comment]
We have been successfully using storybook 7.0 for some time now, so I am going to close this.

Note to future self: If weird things happen try `rm node_modules package-lock.json -r`, though I hope with the new bundling strategy in storybook this will be necessary far less often.
