### ISSUE TITLE
@storybook/builder-webpack5@6.5.0 breaks the babelModeV7 option

### ISSUE THREAD

**Issue by mmis1000** [storybookjs/storybook#18263]
**Describe the bug**

When in condition above, compilation failed with

```
ERR! TypeError: Cannot read property 'push' of undefined
ERR!     at Object.babel (/<project>/node_modules/@storybook/builder-webpack5/dist/cjs/presets/preview-preset.js:37:18)
```

**To Reproduce**

Enable both webpack5 builder and babelModeV7 in 6.5.0

**System**

```
Environment Info:

  System:
    OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (8) x64 AMD Ryzen 9 5950X 16-Core Processor
  Binaries:
    Node: 14.15.0 - ~/.nvm/versions/node/v14.15.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.15.0/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.0/bin/npm
  Browsers:
    Chrome: 92.0.4515.131
    Firefox: 90.0.2
  npmPackages:
    @storybook/addon-actions: ^6.5.0 => 6.5.0 
    @storybook/addon-essentials: ^6.5.0 => 6.5.0 
    @storybook/addon-links: ^6.5.0 => 6.5.0 
    @storybook/builder-webpack5: ^6.5.0 => 6.5.0 
    @storybook/manager-webpack5: ^6.5.0 => 6.5.0 
    @storybook/vue3: ^6.5.0 => 6.5.0 
```

**Additional context**

https://github.com/storybookjs/storybook/commit/79e5f5a198fae811f9cd4d54f878cab308177d74

This line of code is added in `@storybook/builder-webpack5@6.5.0`

**Comment by mandarini** [comment]
Getting a different error, on Nx workspaces with React apps, still webpack5 related. Posted a comment [here](https://github.com/storybookjs/storybook/issues/18260#issuecomment-1131598115).

**Comment by Tim-arts** [comment]
Have the same issue so far

**Comment by shilman** [comment]
Ouch! Sorry gang, should have a fix in the next day or so.

**Comment by ntucker** [comment]
Is https://github.com/storybookjs/storybook/issues/18279 related to this? I don't have either of those options enabled; but I use custom webpack config so I assume that is equivalent to babelv7 mode?

**Comment by shilman** [comment]
Gadzooks!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.4 containing PR #18284 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```
