### ISSUE TITLE
Fix x-default-browser vulnerability changing it to default-browser package

### ISSUE THREAD

**Issue by rivajunior** [storybookjs/storybook#18287]
`x-default-browser` is active maintained. The last update was 4 to 5 years ago. And it depends on an outdated `default-browser-id` version which brings a `trim-newlines`  version with a high severity vulnerability through its `meow` dependency.

I suggest to use [default-browser](https://github.com/sindresorhus/default-browser)

I am willing to send a Pull request

**Comment by bodograumann** [comment]
Fixed in v7.0.0-alpha.9 and later with https://github.com/storybookjs/storybook/pull/18277
