### ISSUE TITLE
Story book 6.5.3 and CRA 5 caused problem

### ISSUE THREAD

**Issue by CreativeSight** [storybookjs/storybook#18283]
**Describe the bug**
After npx sb init and detect Create React App 5 story book make some mess in packages an downgrade @storybook/preset-create-react-app into v3 like below:

"@storybook/builder-webpack4": "^6.5.3",
 "@storybook/builder-webpack5": "^6.5.3",
 "@storybook/manager-webpack4": "^6.5.3",
 "@storybook/manager-webpack5": "^6.5.3",
 "@storybook/node-logger": "^6.5.3",
 "@storybook/preset-create-react-app": "^3.2.0",

**To Reproduce**
Run npx sb init in the project with CRA 5 

**System**
  System:
    OS: macOS 12.3.1
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 16.15.0 - /usr/local/bin/node
    npm: 8.5.5 - /usr/local/bin/npm
  Browsers:
    Chrome: 101.0.4951.64
    Firefox: 100.0.1
    Safari: 15.4

**Additional context**
Clean up manually packages and udpate manually @storybook/preset-create-react-app into v4.1.0 solved problem

**Comment by yannbf** [comment]
Hey @CreativeSight thanks for opening this issue. Did your project not have any Storybook prior to running `npx sb init`? I am not able to reproduce the issue unfortunately.

A fresh CRA5 project, when running `npx sb init`, will install the correct dependencies:

```ts
"@storybook/preset-create-react-app": "^4.1.0",
"@storybook/react": "^6.5.3",
```

**Comment by CreativeSight** [comment]
Hey @yannbf seems problem comes from Adobe SPA repo when one of the dependency is Webpack4 but CRA is 5, so should I close this issue?

**Comment by yannbf** [comment]
@CreativeSight thanks for the info. I tried to reproduce the issue once again with Webpack4 and CRA5 and still I couldn't reproduce it. Do you have maybe some more info, or can you create a reproduction repro to help fix this issue? Thanks!

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
