### ISSUE TITLE
Why does Project type checked from node module file?

### ISSUE THREAD

**Issue by PeterJSung** [storybookjs/storybook#18295]
It seems like storybook check `Project type` at installation. When checking `CRA` type, why does storybook check it from the file in the node module?
other type was checked by `dependencies` but, only `ProjectType.REACT_SCRIPTS` was checked by both `dependencies` and `files`. is there any reason??

https://github.com/storybookjs/storybook/blob/efbd2305673960e63ab16a1d4ab0eae2f79a02cc/lib/cli/src/project_types.ts#L178

**Comment by ndelangen** [comment]
According to the code-comment it's to attempt to support cra-wrappers:
https://github.com/storybookjs/storybook/blob/43f93bb8fb8056fbbd46f6d5fd90ca460c5f858a/code/lib/cli/src/project_types.ts#L185-L194
