### ISSUE TITLE
ParseError: Unexpected token in perfectly valid code.

### ISSUE THREAD

**Issue by roobscoob** [storybookjs/storybook#18306]
**Describe the bug**
I'm unable to build my storybook. When attempting to build my only story, the following error is thrown
```
ERROR in ./src/lib/button.svelte
Module build failed (from ./node_modules/svelte-loader/index.js):
Error: ParseError: Unexpected token (7:7)
 5:   import IconExclamation from "./icons/iconExclamation.svelte";
 6:
 7:   type States = "normal" | "loading" | "error";
           ^
 8:
 9:   const dispatch = createEventDispatcher();
    at C:\Users\roobscoob\Documents\cityspan\components\node_modules\svelte-loader\index.js:87:12
```
This is unexpected as the exact same source compiles perfectly fine when using sveltekit's `npm run dev`

**System**
```
Environment Info:

  System:
    OS: Windows 10 10.0.18362
    CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor
  Binaries:
    Node: 18.0.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.2.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 7.17.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 101.0.4951.67
    Edge: Spartan (44.18362.449.0)
  npmPackages:
    @storybook/addon-actions: ^6.5.4 => 6.5.4
    @storybook/addon-docs: ^6.5.4 => 6.5.4
    @storybook/addon-essentials: ^6.5.4 => 6.5.4
    @storybook/addon-interactions: ^6.5.4 => 6.5.4
    @storybook/addon-links: ^6.5.4 => 6.5.4
    @storybook/addon-svelte-csf: ^2.0.4 => 2.0.4
    @storybook/builder-webpack4: ^6.5.4 => 6.5.4
    @storybook/manager-webpack4: ^6.5.4 => 6.5.4
    @storybook/svelte: ^6.5.4 => 6.5.4
    @storybook/testing-library: ^0.0.11 => 0.0.11
```

**Comment by roobscoob** [comment]
Further, when removing the `type` declaration, the issue is just bumped to the next typescript-specific syntax. Could this be an issue of Storybook not compiling through typescript before being parsed? There is a `lang="ts"` property on the `script` element

```
ERROR in ./src/lib/button.svelte
Module build failed (from ./node_modules/svelte-loader/index.js):
Error: ParseError: Unexpected token (12:16)
10:
11:   let state = "normal";
12:   let stateIndex: number | undefined = undefined;
                    ^
13:   let isHover: number | undefined = undefined;
14:   let isFocus: number | undefined = undefined;
    at C:\Users\roobscoob\Documents\cityspan\components\node_modules\svelte-loader\index.js:86:12
```

**Comment by shilman** [comment]
@roobscoob Yes I believe that `@storybook/svelte` does not come with Typescript support out of the box. @j3rem1e do you know the current status of that?

**Comment by j3rem1e** [comment]
Svelte supports typescript with the help of preprocessors.

`npm storybook init` auto configure preprocessors if possible, but you can configure it by hand with the `svelteOptions` in `.storybook/main.js`. 

see https://github.com/storybookjs/storybook/blob/next/examples/svelte-kitchen-sink/.storybook/main.js#L8

**Comment by bmitchinson** [comment]
> Svelte supports typescript with the help of preprocessors.
> 
> `npm storybook init` auto configure preprocessors if possible, but you can configure it by hand with the `svelteOptions` in `.storybook/main.js`.
> 
> see https://github.com/storybookjs/storybook/blob/next/examples/svelte-kitchen-sink/.storybook/main.js#L8

Any idea where this link was moved to?

**Comment by benmccann** [comment]
`svelteOptions` has been removed in favor of `svelte.config.js`. When you setup a new SvelteKit project it will ask you if you want to use TypeScript and if you setup a new plain Svelte Vite project I believe support will be included automatically.
