### ISSUE TITLE
Running clean repository command trashes .idea

### ISSUE THREAD

**Issue by okonet** [storybookjs/storybook#18308]
**Describe the bug**

When running "Clean repository" task via `yarn bootstrap`, it says that `.idea` will be preserved along with `.vscode` but in reality is removes `.idea` as well.

**To Reproduce**

1. Run `yarn bootstrap` command
2. Choose `Clean repository` in the list of tasks
3. Press `y` when asked

The log will contain the following

```
trashed .yarn/install-state.gz
trashed examples/react-ts-webpack4/
trashed reset.log
trashed .idea/
```

**Comment by shilman** [comment]
@okonet `--reset` deletes any files that git doesn't know about, so the fix is probably just to update the docs

**Comment by okonet** [comment]
I think that the intent is correct since it makes WebStorm users suffer for now specific reason. I already have a fix in place so I'll PR soon.
