### ISSUE TITLE
Open in browser doesn't work in WSL when some system dependencies aren't installed

### ISSUE THREAD

**Issue by lesha1201** [storybookjs/storybook#18304]
**Describe the bug**

Storybook uses `x-default-browser` for determing a default browser. On Linux, `x-default-browser` requires `xdg-utils`  to be installed to determine it. It determines by running a command `xdg-mime query default x-scheme-handler/http`.

![image](https://user-images.githubusercontent.com/10157660/169856798-d90cbee9-7589-4554-b361-74fa09e38d32.png)

In case of WSL, we doesn't need to have `xdg-utils` to be installed to open in a browser. We still can open it in a browser without it.

However, we doesn't fallback when `x-default-browser` fails. I think we should fallback to `open` in this case.

![image](https://user-images.githubusercontent.com/10157660/169857336-46224167-5fde-4b15-886d-3e8fb86f6a47.png)

**Comment by shilman** [comment]
ZOMG!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.5-alpha.3 containing PR #18305 that references this issue. Upgrade today to the `@prerelease` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
