### ISSUE TITLE
Angular: not possible to add storybook to an Angular project created with @angular/cli > 14.0.0-next.7

### ISSUE THREAD

**Issue by stefanoslig** [storybookjs/storybook#18316]
**Describe the bug**
As you can see in the [CHANGELOG](https://github.com/angular/angular-cli/blob/main/CHANGELOG.md#angularcli-11) of the angular-cli project, after version 14.0.0-next.7, the `defaultProject` property has been deprecated. That means that when we create a new project and try to run `npx sb init` , we will get the following error because this property is not in the `angular.json` file:

![image](https://user-images.githubusercontent.com/6942946/170126221-82910f1a-6b4e-4fb7-9e30-846f9b86f3f4.png)

To solve this, we need to change the Angular generators(`angular-helpers.ts`, `index.ts`) and instead of using the `defaultProject` property, we should try to retrieve this value form the first key of the `project` object. 

**To Reproduce**
1. Install the latest version of the angular-cli in your machine
2. run `ng new my-angular-project`
3. run `npx sb init`

**System**
```
  System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 16.10.0 - ~/.nvm/versions/node/v16.10.0/bin/node
    Yarn: 3.2.1 - ~/.nvm/versions/node/v16.10.0/bin/yarn
    npm: 7.24.0 - ~/.nvm/versions/node/v16.10.0/bin/npm
  Browsers:
    Chrome: 101.0.4951.64
    Firefox: 99.0.1
    Safari: 15.4
```

**Additional context**
I will open a PR soon for this.

**Comment by shilman** [comment]
Fixed in https://github.com/storybookjs/storybook/releases/tag/v6.5.7
