### ISSUE TITLE
Storybook 6.5 gives an error when using an element with class attribute instead of className into Canvas tag. 

### ISSUE THREAD

**Issue by Dachak** [storybookjs/storybook#18328]
**Describe the bug**
Since we updated storybook from 6.3. to 6.5,  we have an error during runtime in the chrome console when we use a class on an element attribute into Canvas tag. 

For example the span:
`<Canvas>
  <dsd-input type="text" name="input">
    <span slot="label">Lorem ipsum <span class="dsd-sr-only">: lorem ipsum</span></span>    
  </dsd-input>
</Canvas>`

this will return this error :
![image](https://user-images.githubusercontent.com/48768839/170339050-a6b96f04-f778-4432-b603-0baa4cf4edad.png)

We know that jsx wants className, but If we modify class by className we do not have an error but the code snippet wont be the good one to show in our documentation :

expected 
![image](https://user-images.githubusercontent.com/48768839/170339364-d5b8e5f9-8c73-45e1-992b-9a02e4f16a9d.png)

result if we modify for className
![image](https://user-images.githubusercontent.com/48768839/170339477-c0f84d17-3edf-460f-9e7e-b0347e52bf50.png)

Is there a way to ignore the error in the console ? Or is there something we can do so the class is accepted in Canvas for our code snippet?

**To Reproduce**
insert an element with class attribute into a canvas tag in a mdx file. Then run storybook

**System**
Environment Info:

  System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
  Binaries:
    Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (101.0.1210.53)

**Additional context**
Our web-components are created with stencil js & typescript.

**Comment by zhyd1997** [comment]
the same to React Hooks & TypeScript.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
