### ISSUE TITLE
Incorrect processing of `PropTypes.oneOfType` in stories

### ISSUE THREAD

**Issue by aaavakian** [storybookjs/storybook#18321]
**Describe the bug**

Using `PropTypes.oneOfType` displays everything correctly, but if I update the field and then reload the page, value is not being saved. It's being reset to a default value.

**To Reproduce**

Link to the reproduction repo: https://github.com/aaavakian/storybook-reproduction

- Visit a story for a component that has `PropTypes.oneOfType` prop;
- Update a prop;
- Refresh the page and see that changes are not saved.

Loom: https://www.loom.com/share/4adc995b17d4476d8579e990e8218a5d

**System**

```
Environment Info:

  System:
    OS: macOS 12.2.1
    CPU: (8) arm64 Apple M1 Pro
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 3.2.1 - ~/.nvm/versions/node/v16.15.0/bin/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
  Browsers:
    Chrome: 101.0.4951.64
    Safari: 15.3
  npmPackages:
    @storybook/addon-actions: ^6.5.5 => 6.5.5 
    @storybook/addon-docs: ^6.5.5 => 6.5.5 
    @storybook/addon-essentials: ^6.5.5 => 6.5.5 
    @storybook/addon-interactions: ^6.5.5 => 6.5.5 
    @storybook/addon-links: ^6.5.5 => 6.5.5 
    @storybook/builder-webpack4: ^6.5.5 => 6.5.5 
    @storybook/manager-webpack4: ^6.5.5 => 6.5.5 
    @storybook/react: ^6.5.5 => 6.5.5 
    @storybook/testing-library: ^0.0.11 => 0.0.11 
```

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
