### ISSUE TITLE
Support React 18

### ISSUE THREAD

**Issue by tmthan** [storybookjs/storybook#18331]
When I use storybook with react 18. I recived a warning from React: " ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17."
React 18 use createRoot instead ReactDOM.render.
please upgrade to use createRoot when user use react 18.
Thanks

**Comment by ofirrifo** [comment]
I have the same issue

**Comment by DavidSchillinger** [comment]
This means we can't use Storybook to test that components work correctly on React 18. I'm unsure if Storybook is intended for this but testing component stories was going to be part of the React 18 upgrade process for a component library that I work on.

So I think a way to switch rendering to React 18 would be great :smile:

**Comment by dan-mba** [comment]
@DavidSchillinger From what I can tell, the Storybook UI (which is React based) is being rendered using the old API, but the iframe that renders a component is using the new API.

**Comment by shilman** [comment]
@dan-mba that's correct. we're planning to move the storybook UI to react18 in 7.0, but in the meantime you should be able to render & test your components in react18 starting in 6.5.

**Comment by shilman** [comment]
closing this as dupe to
