### ISSUE TITLE
:first-child in server-side rendering

### ISSUE THREAD

**Issue by tmthan** [storybookjs/storybook#18332]
When I use server-side rendering with NextJS. I recived a alert: "The pseudo class ":first-child" is potentially unsafe when doing server-side rendering. Try changing it to ":first-of-type""
I changed all of my css from ":first-child to ":first-of-type and I still recive that alert. I think the css of storybook still use :first-child. I hope you change from first-child to ":first-of-type" in storybook.
Thanks

**Comment by jserra91** [comment]
I have the same problem with Angular (v13).

**Comment by shilman** [comment]
closing as dupe to #18103
