### ISSUE TITLE
Dynamic import in @storybook/csf-tools breaking jest tests in ^6.5

### ISSUE THREAD

**Issue by panbenson** [storybookjs/storybook#18341]
**Describe the bug**
Dynamic import in `readCsfOrMdx` is breaking jest tests. 

**To Reproduce**
Import and run any function that uses `readCsfOrMdx` from `@storybook/csf-tools`. Running the test produces the following traceback:
```
    TypeError: _vm(...).SyntheticModule is not a constructor

      3 |
      4 | const parseMdxFile = async (mdxFilePath) => {
    > 5 |     return await readCsfOrMdx(mdxFilePath)
        |            ^
      6 | }
      7 |
      8 | module.exports = {

      at Runtime.loadCjsAsEsm (node_modules/jest-runtime/build/index.js:657:20)
      at readCsfOrMdx (node_modules/@storybook/csf-tools/index.cjs:12:11)
      at parseMdxFile (parseMdxFile.js:5:12)
      at Object.<anonymous> (parseMdxFile.test.js:5:24)
```
I've created a minimum repro here: https://github.com/panbenson/readcsformdx-issue-repro/tree/master

**System**
Environment Info:

  System:
    OS: macOS 12.2.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 16.3.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.15.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 102.0.5005.61
    Edge: 101.0.1210.53
    Firefox: 99.0.1
    Safari: 15.3
  npmPackages:
    @storybook/csf-tools: ^6.5.5 => 6.5.5 
    @storybook/mdx2-csf: ^0.0.3 => 0.0.3 

**Additional context**
N/A

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
