### ISSUE TITLE
Args docs for vue are wrong

### ISSUE THREAD

**Issue by SassNinja** [storybookjs/storybook#18358]
**Describe the bug**
The last section of the args docs for yue are incorrect because the shown code doesn't work for vue as `useArgs`is a react specific hook: https://storybook.js.org/docs/vue/writing-stories/args#mapping-to-complex-arg-values

**To Reproduce**
Simply try to use the hook in a vue story to update the args on click.

```javascript
export const Broken = (args) => ({
  setup() {
    const [_, updateArgs] = useArgs();
    const handleClick = () => {
      updateArgs({ foo: 789 })
    };
    return { args, handleClick };
  },
  template: `
    <div>
      <p>foo: {{ args.foo }}</p>
      <button @click="handleClick">update</button>
    </div>
  `,
});
Broken.args = {
  foo: 123
}
```

**System**

System:
    OS: macOS 12.1
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 16.14.1 - ~/.nvm/versions/node/v16.14.1/bin/node
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.1/bin/npm
  Browsers:
    Chrome: 102.0.5005.61
    Firefox: 98.0.2
    Safari: 15.2
  npmPackages:
    @storybook/addon-actions: ^6.4.19 => 6.4.19
    @storybook/addon-essentials: ^6.4.19 => 6.4.19
    @storybook/addon-links: ^6.4.19 => 6.4.19
    @storybook/vue3: ^6.4.19 => 6.4.19

**Additional context**
There's another issue which mentions this problem: https://github.com/storybookjs/storybook/issues/12006#issuecomment-1099664571
So the vue docs should either remove this react specific code or should describe the vue solution (if there is one)

**Comment by prashantpalikhe** [comment]
@SassNinja The `useArgs` hook should work within the context of a story function. In your code example, you are using it in the context of a Vue component. Could you try a snippet like this e.g.?

```JS
export const Broken = (args) => {
  const [_, updateArgs] = useArgs();

  return {
    setup() {
      const handleClick = () => {
        updateArgs({ foo: 789 });
      };

      return { args, handleClick };
    },
    template: `
      <div>
        <p>foo: {{ args.foo }}</p>
        <button @click="handleClick">update</button>
      </div>
    `,
  };
};
Broken.args = {
  foo: 123,
};
```

**Comment by fgordillo** [comment]
I tried something similar to what @prashantpalikhe describes and I still get the same error:
```
Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:

1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
```
That hook should be React-only.

**Comment by shilman** [comment]
The issue is that there are two `useArgs` hooks.

The referenced docs are about extending addons, which are written in React and run in Storybook's "manager" UI. The import is:

```js
import { useArgs } from '@storybook/api':
```

The hooks that run inside your story functions are framework agnostic:

```js
import { useArgs } from '@storybook/client-api';
```

I believe we've discussed renaming these packages in 7.0 as part of our cleanup. @tmeasday @ndelangen do you remember where we landed on this?

More info: https://github.com/storybookjs/storybook/blob/main/lib/store/README.md#using-args-in-an-addon

**Comment by tmeasday** [comment]
@shilman yes! I think (ideally) in 7.0 it'll be:

```ts
import { useArgs } from '@storybook/manager':
```

and

```js
import { useArgs } from '@storybook/preview':
```

Which should it make it a fair bit more obvious which one to use! Also I think we might be able to make it so if you import them in the wrong place it just errors or warns you about it.

**Comment by SassNinja** [comment]
Thanks a lot @prashantpalikhe and @shilman – this solved my problem!
I'm able to update my args now as intended :-)

I think adjusting the vue docs would help a lot because the two requirements are definitely not obvious
- use the hook from `@storybook/client-api`
- call `useArgs` outside of vue's setup function
