### ISSUE TITLE
Issue while building storybook

### ISSUE THREAD

**Issue by ankita219819** [storybookjs/storybook#18368]
I get the following issue on building the storybook.
```
node_modules/@storybook/core/node_modules/file-system-cache/lib/common/Util.js:23
    return input.flat().filter((value) => !libs_1.R.isNil(value));
                 ^

TypeError: input.flat is not a function
    at compact (/home/user/storybook-component/node_modules/@storybook/core/node_modules/file-system-cache/lib/common/Util.js:23:18)
    at /home/user/storybook-component/node_modules/ramda/src/internal/_pipe.js:3:27
    at /home/user/storybook-component/node_modules/ramda/src/internal/_arity.js:11:19
    at Object.hash (/home/user/storybook-component/node_modules/@storybook/core/node_modules/file-system-cache/lib/common/Util.js:46:57)
    at new FileSystemCache (/home/user/storybook-component/node_modules/@storybook/core/node_modules/file-system-cache/lib/FileSystemCache.js:18:33)
    at exports.default (/home/user/storybook-component/node_modules/@storybook/core/node_modules/file-system-cache/lib/index.js:6:32)
    at Object.<anonymous> (/home/user/storybook-component/node_modules/@storybook/core/dist/server/build-dev.js:88:42)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! storybook-component-library@0.0.0 build-storybook: `build-storybook -c .storybook -o storybook-component-storybook`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the storybook-component-library@0.0.0 build-storybook script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Don't know the reason as we didn't make any library change or version change. we have been using this since long but this error occurring since last few days

Version:
npm : 6.13.4
angular: 8
node: v10.19.0
storybook angular: 6.0.12

Can you please provide the solution faster

**Comment by jgreenlee26** [comment]
@ankita219819 
I ran into this same issue using an older version of storybook (5.2.1) and Vue after updating dependencies but was only able to reproduce the issue in a CI/CD environment. The file-system-cache dependency appears to be required by @storybook/core. Pinning the node file-system-cache dependency to 1.0.5 appears to have resolved the issue for me. 

Try adding "file-system-cache": "1.0.5" to your devDependencies, removing the package-lock.json file and reinstalling node_modules.

**Comment by ankita219819** [comment]
> @ankita219819 I ran into this same issue using an older version of storybook (5.2.1) and Vue after updating dependencies but was only able to reproduce the issue in a CI/CD environment. The file-system-cache dependency appears to be required by @storybook/core. Pinning the node file-system-cache dependency to 1.0.5 appears to have resolved the issue for me.
> 
> Try adding "file-system-cache": "1.0.5" to your devDependencies, removing the package-lock.json file and reinstalling node_modules.


Sure I can give this a try

**Comment by ldewald** [comment]
> Same issue here with the same version of Node.js. The problem is that `Array.prototype.flat` only exists in [Node.js v11+](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat#browser_compatibility)


The fix suggested by [jgreenlee26](https://github.com/jgreenlee26) ended up working for me. I added `"file-system-cache": "1.0.5"` to my devDependencies, removed the node modules cache for storybook `rm -rf node_modules/.cache/storybook`, reinstalled modules `npm install`, and then the build started working consistently.

**Comment by ankita219819** [comment]
This is resolved.. `rm -rf` worked 
Thanks @ldewald and @jgreenlee26

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
