### ISSUE TITLE
After upgrading to v6.5.0+ I get process is not defined

### ISSUE THREAD

**Issue by joshwooding** [storybookjs/storybook#18366]
**Describe the bug**

After upgrading to v6.5.0+ I get process is not defined when running tests that import storybook packages.

**To Reproduce**
I don't have a great reproduction but I've seen it in two places with the Vite builder:

https://github.com/jpmorganchase/uitk/runs/6656327980?check_suite_focus=true#step:7:96
https://github.com/storybookjs/builder-vite/runs/6610284218?check_suite_focus=true#step:7:93

**System**
Please paste the results of `npx sb@next info` here.

Environment Info:

  System:
    OS: Windows 10 10.0.19043
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.2.0 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.10.0 - ~\AppData\Roaming\npm\npm.CMD
  Browsers:
    Chrome: 102.0.5005.62
    Edge: Spartan (44.19041.1266.0), Chromium (101.0.1210.53)
  npmPackages:
    @storybook/addon-a11y: 6.5.6 => 6.5.6
    @storybook/addon-actions: 6.5.6 => 6.5.6
    @storybook/addon-docs: 6.5.6 => 6.5.6
    @storybook/addon-essentials: 6.5.6 => 6.5.6
    @storybook/addon-links: 6.5.6 => 6.5.6
    @storybook/builder-vite: ^0.1.35 => 0.1.35
    @storybook/node-logger: 6.5.6 => 6.5.6
    @storybook/react: 6.5.6 => 6.5.6
    @storybook/testing-react: ^1.2.2 => 1.2.3

**Additional context**
I believe this is a similar issue to https://github.com/storybookjs/storybook/pull/18015 but with `@storybook/theming`

**Comment by shilman** [comment]
Yippee!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.9-alpha.1 containing PR #18367 that references this issue. Upgrade today to the `@prerelease` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Gadzooks!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.9 containing PR #18469 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```

**Comment by shilman** [comment]
¡Ay Caramba!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-alpha.2 containing PR #18469 that references this issue. Upgrade today to the `@future` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

**Comment by shilman** [comment]
Boo-yah!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.10-alpha.0 containing PR #18469 that references this issue. Upgrade today to the `@prerelease` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

**Comment by shilman** [comment]
Jeepers creepers!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.10 containing PR #18367 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```
