### ISSUE TITLE
The prebundle script does not work on windows

### ISSUE THREAD

**Issue by joshwooding** [storybookjs/storybook#18364]
**Describe the bug**

When running the prebundle script on Windows it breaks:

![image](https://user-images.githubusercontent.com/12938082/171068834-e9acdebf-4bb3-4fbc-b193-a832f6bf9a4b.png)

**To Reproduce**

Run any prepare script that prebundles on Windows.

**System**

**Environment Info:
    Chrome: 102.0.5005.62
    Edge: Spartan (44.19041.1266.0), Chromium (101.0.1210.53)**

**Additional context**

**Comment by shilman** [comment]
Shiver me timbers!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-alpha.2 containing PR #18365 that references this issue. Upgrade today to the `@future` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
