### ISSUE TITLE
Setting component and subcomponents properties on story parameters no longer supported?

### ISSUE THREAD

**Issue by tevey** [storybookjs/storybook#18362]
Hi,
We are using storybook for web-components version 6.3.7, today we set the component and subcomponent properties on the story parameters like this:
```typescript
/* my-component.stories.ts*/
const component {
    title: `My Component`,
};

export default component;

export const Main = () => html`<p>my demo</p>`;
Main.parameters.component = 'my-component';
Main.parameters.subcomponents = { 'my-component-sub': 'my-component-sub' };
```

And this works fine to get the documentation from the customelements json file displayed correct in the docs page.

But after upgrading to storybook version 6.5.4 this doesn't work anymore, now we only get the correct documentation displayed if we set the component and subcomponent properties on the default export like this:

```typescript
/* my-component.stories.ts*/
const component {
    title: `My Component`,
    component: 'my-component',
    subcomponents: { 'my-component-sub': 'my-component-sub' },
};

export default component;

export const Main = () => html`<p>my demo</p>`;
```
Is this an intentional change or a bug?

**Comment by tevey** [comment]
No one?

**Comment by shilman** [comment]
@tevey Sorry your issue got caught in the shuffle. AFAIK `parameters.components`/`subcomponents` was an implementation detail that happened to work by accident and never a public/documented API. Removing it broke some users that used this approach, but we don't consider it to be a breaking change.

Hope that helps! Closing this for now, but happen to continue the convo as necessary.
