### ISSUE TITLE
`extractArgTypes` doesn't function for `@storybook/html` since v6.5.0

### ISSUE THREAD

**Issue by weaintplastic** [storybookjs/storybook#18376]
**Describe the bug**
Up until v6.4.22 of Storybook, we've been able to enhance the argTypes hooking into the `docs` parameters via `extractArgTypes`. While this hook seems to still work for `@storybook/web-components` for versions `6.5.*` it suddenly stopped calling the function for `@storybook/html` of `6.5.*` versions.

**To Reproduce**
I've created a repository with `README.md` instructions to reproduce the error.
https://github.com/weaintplastic/storybook-html-extractArgTypes

**System**
```
System:
    OS: macOS 12.3.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 3.2.1 - ~/.nvm/versions/node/v16.13.1/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
  Browsers:
    Chrome: 101.0.4951.64
    Edge: 101.0.1210.53
    Firefox: 92.0.1
    Safari: 15.4
  npmPackages:
    @storybook/addon-actions: 6.4.22 => 6.4.22 
    @storybook/addon-docs: 6.4.22 => 6.4.22 
    @storybook/addon-essentials: 6.4.22 => 6.4.22 
    @storybook/addon-interactions: 6.4.22 => 6.4.22 
    @storybook/addon-links: 6.4.22 => 6.4.22 
    @storybook/builder-webpack4: 6.4.22 => 6.4.22 
    @storybook/html: 6.4.22 => 6.4.22 
    @storybook/manager-webpack4: 6.4.22 => 6.4.22 
    @storybook/testing-library: ^0.0.11 => 0.0.11 
```

**Additional context**

We are using `@storybook/html` in combination with `enhanceArgTypes` to render web components with StencilJS in stories and enhance their documentation with custom data.

We know that `@storybook/web-components` does exist and allows extending the documentation with a `custom-elements.json`, though the possibilities of information to add is too limiting for us. Also when using `@storybook/web-components` returning a template string from a Story, it isn't turned into HTML but rendered as a serialized string in stories in the "Docs" tab.

**Comment by weaintplastic** [comment]
I'm happy to jump on fixing this myself if someone could point me in the right direction.

**Comment by weaintplastic** [comment]
Thanks, @shilman for taking care of this.

**Comment by shilman** [comment]
Jeepers creepers!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-alpha.18 containing PR #18831 that references this issue. Upgrade today to the `@future` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Gadzooks!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.10-alpha.1 containing PR #18831 that references this issue. Upgrade today to the `@prerelease` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

**Comment by weaintplastic** [comment]
@shilman I just gave it a try and can confirm that the issue is fixed. Thanks a lot for taking care of this. 🙏

**Comment by shilman** [comment]
Yippee!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.10 containing PR #18831 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```
