### ISSUE TITLE
Your test suite must contain at least one test.

### ISSUE THREAD

**Issue by wegry** [storybookjs/storybook#18387]
**Describe the bug**
Using 

- @storybook/addon-storyshots@6.5.6
- @storybook/react@6.5.6
- jest@27.5.1
- yarn@3.2.1

**To Reproduce**
Please create a reproduction by running `npx sb@next repro` and following the instructions. Read our [documentation](https://storybook.js.org/docs/react/contribute/how-to-reproduce) to learn more about creating reproductions.
Paste your repository and deployed reproduction here. We prioritize issues with reproductions over those without.

1. clone https://github.com/wegry/react-component-library-template2. 
2. run `yarn`
3. run `yarn test`
4. Note 
```
 FAIL  src/stories.spec.tsx
  ● Test suite failed to run

    Your test suite must contain at least one test.

      at onResult (node_modules/@jest/core/build/TestScheduler.js:175:18)
      at node_modules/@jest/core/build/TestScheduler.js:316:17
      at node_modules/emittery/index.js:260:13
          at Array.map (<anonymous>)
      at Emittery.emit (node_modules/emittery/index.js:258:23)
```
      
 **System**
Please paste the results of `npx sb@next info` here.

```
Environment Info:

  System:
    OS: macOS 12.4
    CPU: (4) x64 Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 3.2.1 - ~/.yarn/bin/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
  Browsers:
    Chrome: 102.0.5005.61
    Safari: 15.5
  npmPackages:
    @storybook/addon-actions: 6.5.6 => 6.5.6
    @storybook/addon-essentials: 6.5.6 => 6.5.6
    @storybook/addon-links: 6.5.6 => 6.5.6
    @storybook/addon-storyshots: ^6.5.6 => 6.5.6
    @storybook/react: 6.5.6 => 6.5.6
```

**Additional context**

I did have the test suite correctly generate a snapshot once, and then never succeed again, even after removing the generated snapshots folder. I wonder if there's some sort of caching involved?

**Comment by wegry** [comment]
Switching from `.storiesOf` to CSF seemed to fix this, bizarrely.

**Comment by YoanDo** [comment]
Hi @wegry! 
I have the same issue. I'm using CSF [play function](https://storybook.js.org/docs/react/api/csf#play-function).
Could you give me more details about how you resolved it ?

**Comment by wegry** [comment]
@YoanDo `Your test suite must contain at least one test.` seems to have a number causes. If you're already using CSF, your issue is likely something different.

**Comment by kerosan** [comment]
![image](https://user-images.githubusercontent.com/10149363/217649406-8c9f6455-ea64-4f80-b9d6-eeb0ba0ec879.png)
commenting this lines helped me
