### ISSUE TITLE
Addons tab still shows in mobile viewports even when `showPanel:false` is set

### ISSUE THREAD

**Issue by TristanWatanabe** [storybookjs/storybook#18386]
## Describe the bug

When setting `showPanel: false` in the manager.js file, the add-ons panel is hidden on desktop viewports but is still present in mobile viewports. My expectation here would be that when `showPanel: false` is set, the addons tab is completely inaccessible whether it be on desktop or mobile.

## To Reproduce
Repro Repo: https://github.com/TristanWatanabe/storybook-issue-repro
Published Chromatic Link: https://62979a5749b36f003aba9679-uzhortlcyh.chromatic.com/?path=/story/example-button--primary

Steps to Repro:
1) Open chromatic [link ](https://62979a5749b36f003aba9679-uzhortlcyh.chromatic.com/?path=/story/example-button--primary).
2) Open chrome console.
3) Click on "Toggle Device Emulation" and observe issue.
	- ![image](https://user-images.githubusercontent.com/8649804/171462131-8ece890e-9f03-465c-aa80-f35fc434fae4.png)

## System
  System:
    OS: Linux 5.10 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 3.2.1 - /usr/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Chrome: 93.0.4577.63
  npmPackages:
    @storybook/addon-a11y: ^6.5.6 => 6.5.6 
    @storybook/addon-actions: ^6.5.6 => 6.5.6 
    @storybook/addon-docs: ^6.5.6 => 6.5.6 
    @storybook/addon-essentials: ^6.5.6 => 6.5.6 
    @storybook/addon-interactions: ^6.5.6 => 6.5.6 
    @storybook/addon-knobs: ^6.4.0 => 6.4.0 
    @storybook/addon-links: ^6.5.6 => 6.5.6 
    @storybook/addons: ^6.5.6 => 6.5.6 
    @storybook/builder-webpack5: ^6.5.6 => 6.5.6 
    @storybook/manager-webpack5: ^6.5.6 => 6.5.6 
    @storybook/node-logger: ^6.5.6 => 6.5.6 
    @storybook/preset-create-react-app: ^4.1.2 => 4.1.2 
    @storybook/react: ^6.5.6 => 6.5.6 
    @storybook/testing-library: ^0.0.11 => 0.0.11

**Comment by BikashSah999** [comment]
Hi @shilman @ndelangen @tmeasday  , Can I work on this issue ?

**Comment by shilman** [comment]
@BikashSah999 That would be awesome!!! 🙏

**Comment by BikashSah999** [comment]
Hi @shilman  @ndelangen  @tmeasday , the PR for this issue is up for review. Could you please review it?

**Comment by shilman** [comment]
Yo-ho-ho!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-alpha.51 containing PR #19807 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
