### ISSUE TITLE
Storybook Background addon not working with 6.5

### ISSUE THREAD

**Issue by TomDo1234** [storybookjs/storybook#18385]
**Describe the bug**
Change background option and background parameters for preview.js no longer appear/work.

**To Reproduce**
Simply install storybook 6.5 on a Vue3 project , then open a storybook dev server

You will see there isn't a change background button on top anymore

package.json

> "devDependencies": {
>     "@babel/core": "^7.18.2",
>     "@storybook/addon-actions": "^6.5.6",
>     "@storybook/addon-essentials": "^6.5.6",
>     "@storybook/addon-interactions": "^6.5.6",
>     "@storybook/addon-links": "^6.5.6",
>     "@storybook/builder-vite": "^0.1.35",
>     "@storybook/testing-library": "^0.0.11",
>     "@storybook/vue3": "^6.5.6",
>     "@vitejs/plugin-vue": "^2.3.3",
>     "babel-loader": "^8.2.5",
>     "vite": "^2.9.9",
>     "vue-loader": "^16.8.3"
>   }

**Comment by IanVS** [comment]
This is a vite builder issue, thanks for reporting, @TomDo1234, and for opening https://github.com/storybookjs/builder-vite/issues/401.
