### ISSUE TITLE
Storybook 6.5.6 - Vue - ArgsTable not working with MDX

### ISSUE THREAD

**Issue by mvitz** [storybookjs/storybook#18397]
We are using Vue 2 with vue-cli and Storybook 6.4.22 with Webpack 5, addon-docs and MDX.

For an example story like

```
import { Meta, ArgsTable, Story, Canvas } from "@storybook/addon-docs";
import Greeting from "./Greeting.vue";

<Meta
  title="Greeting"
  component={Greeting}
  argTypes={{
    color: {
      control: {
        type: "select",
        options: ["red", "blue", "black"],
      },
    },
  }}
/>

# Greeting

Renders a greeting.

export const Template = (args, { argTypes }) => ({
  props: Object.keys(argTypes),
  components: { Greeting },
  template: `<Greeting v-bind="$props"></Greeting>`,
});

<Canvas>
  <Story name="Default">{Template.bind({})}</Story>
</Canvas>

<ArgsTable story="Default" />
```

with the Component written as

```
<script>
export default {
  props: {
    /**
     * Greeting.
     */
    greeting: {
      type: String
    },
    /**
     * Color of the text.
     */
    color: {
      type: String,
      default: 'red'
    },
  }
}
</script>

<template>
  <p class="greeting" :style="'color: ' + color + ';'">{{ greeting }}</p>
</template>

<style>
.greeting {
  font-weight: bold;
}
</style>
```

the ArgsTable is working. It shows both properties and I can change the values and see the effects.

After updating to Storybook 6.5.6 the ArgsTable only renders the color prop (which is overwritten by the argTypes of Meta) but the greeting prop is missing. If the argTypes of Meta is removed the ArgsTable shows

> Args unsupported. See Args documentation for your framework. 

**To Reproduce**

To reproduce this issue you can use the code from https://github.com/mvitz/vue-sb-bug and run `npm i && npm start` afterwards the storybook is served at http://localhost:6006

**System**

```
Environment Info:

  System:
    OS: macOS 11.6.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 12.20.1 - ~/.nvm/versions/node/v12.20.1/bin/node
    npm: 6.14.10 - ~/.nvm/versions/node/v12.20.1/bin/npm
  Browsers:
    Chrome: 102.0.5005.61
    Safari: 15.5
  npmPackages:
    @storybook/addon-docs: ~6.5.6 => 6.5.6
    @storybook/builder-webpack5: ~6.5.6 => 6.5.6
    @storybook/manager-webpack5: ~6.5.6 => 6.5.6
    @storybook/vue: ~6.5.6 => 6.5.6
```

**Comment by atrunelle** [comment]
I was just about to raise an issue for this and found this one. We have the exact same problem.
I managed to narrow it down to using `vue-cli-storybook` plugin.

I tried to set up Storybook on a brand new Vue 2 project with the Vue CLI. Controls and ArgTable were working. But if I use `vue-cli-storybook`, it breaks and I see `Args unsupported. See Args documentation for your framework.`.

The other issue is the stories height is all messed up when viewed in the Doc tab. It doesn't take the size of the story and requires to set a height on the story.

![Screenshot 2022-10-14 at 16 00 22](https://user-images.githubusercontent.com/17130395/196977788-5b267e76-3b9f-46ec-87a4-f560e0584296.png)

I had to downgrade Storybook back to 6.4.22 to fix the issue.

**Comment by vanessayuenn** [comment]
In attempt to clean up old issue, I will be closing this one. We've made lots of improvements in Storybook since 7.0 so it's quite likely that this issue has been resolved already. If this is still a problem, please open a new issue with reproduction steps for 7.x version. Thank you!
