### ISSUE TITLE
Documentation of precautions when using Vite

### ISSUE THREAD

**Issue by yogarasu** [storybookjs/storybook#18399]
I'm new to Storybook, but when using it with Vite, I had the following two problems, and I wasted a day with the latter problem.  

- To run Storybook, need to install the `@mdx-js/xxxxx` package.
- global is not defined error

The global is not defined error can can be avoided by adding the preview-head.html file and adding the following code.  
Seems to be due to the jest-mock package used inside the `@storybook/addon-interactions` add-on.  

https://github.com/storybookjs/storybook/issues/17516
```html
<script>
  window.global = window;
</script>
```

I couldn't find a description of these issues in the official documentation, but I can't use the Storybook without addressing these issues.  
I was confused because `@storybook/addon-interactions` was omitted without explanation in the Vite section of the official docs, even though it was the default add-on.  

https://storybook.js.org/docs/react/builders/vite

I will pull request if I have time, but please let me know if my understanding is wrong.

**Comment by IanVS** [comment]
Thanks for bringing this up, @yogarasu.  I'm writing up a `converting to vite builder` section for the readme right now, and will include the mdx issue in the `known issues` section as well, until we can get that straightened out.

**Comment by yogarasu** [comment]
@IanVS 
Thank you very much!!!
People like me want to use Vite in terms of performance, so I want to lower the barrier as much as possible.

I don't think there is any particular reason to install the packages individually, so in the future it would be nice if the mdx package that suits your environment is automatically installed.

I will check the review.

**Comment by IanVS** [comment]
For sure, it's definitely a bug (https://github.com/storybookjs/builder-vite/issues/391).  It's due to react 18 and mdx2 and the mdx plugin we're using, etc. We're working on it in https://github.com/storybookjs/builder-vite/pull/377, which I hope will solve that issue.

**Comment by yogarasu** [comment]
@IanVS 
I confirmed, I think there is no problem.
I was impressed by the prompt response, thank you !!!

**Comment by yogarasu** [comment]
@IanVS 
It's just a feeling, but I'll leave the money for the coffee through the github sponsor, thank you.
