### ISSUE TITLE
 Cannot find module error, for all of my stories after upgrading to storybook version 6.5.6 

### ISSUE THREAD

**Issue by talwaserman** [storybookjs/storybook#18416]
**Describe the bug**
i upgraded storybook from  storybook/react@6.3.12  to @storybook/react@6.5.6

also upgraded webpack to 
"webpack": "^5.72.1",
"webpack-cli": "^4.9.2",
    
and upgraded all addons

in the main.hs file, when i turn  **storyStoreV7: true**  i get an error that all of my stories are not found
`Error: Cannot find module './src/workspace/Gizmo/templates/Welcome/index.story.js'`

i didn't change the path of the stories before the upgrade.

my main.js file:
`module.exports = {
  stories: [
    '../src/workspace/Gizmo/templates/Welcome/index.story.js', // set this story as default
    '../src/workspace/**/**/*.story.js'
  ],
  addons: [
    '@storybook/addon-controls',
    '@storybook/addon-knobs',
    '@storybook/addon-links',
    '@storybook/addon-notes/register',
    '@storybook/addon-notes/register-panel',
    '@storybook/addon-viewport',
    '@storybook/addon-storysource',
    '@storybook/addon-queryparams',
    '@storybook/addon-measure'
  ],
  features: {
    storyStoreV7: true
  },
  core: {
    builder: {
      name: 'webpack5',
      options: {
        lazyCompilation: true,
        fsCache: true
      }
    }
  },
  framework: '@storybook/react'
};
`

packadge.json:

`
{
  "name": "...",
  "version": "...",
  "author": "...",
  "description": "...",
  "module": "...",
  "repository": {
...
  },
  "publishConfig": {
   ...
  },
  "dependencies": {
    "@babel/runtime": "^7.16.0",
    "@storybook/react": "^6.5.6",
    "antd": "^4.17.1",
    "axios": "^0.19.0",
    "babel-eslint": "^10.0.3",
    "babel-preset-jest": "^26.6.2",
    "copyfiles": "^2.3.0",
    "cross-env": "^6.0.3",
    "jest": "^26.1.0",
    "less": "^3.10.3",
    "lodash": "^4.17.15",
    "moment": "^2.24.0",
    "moment-timezone": "^0.5.31",
    "prop-types": "^15.7.2",
    "rc-util": "5.8.0",
    "react": "^17.0.2",
    "react-app-rewired": "^2.1.3",
    "react-dom": "^17.0.2",
    "react-helmet": "^6.1.0",
    "react-scripts": "3.1.2",
    "react-tracked": "^1.7.2",
    "recharts": "2.0.0-beta.6",
    "rsync": "^0.6.1",
    "socket.io-client": "^2.3.0",
    "virtualizedtableforantd4": "^1.1.4",
    "webpack": "^5.72.1",
    "webpack-cli": "^4.9.2",
    "yargs-parser": "^20.2.0"
  },
  "scripts": {
    ....
  },
  "pre-commit": [
    "lint",
    "test:all"
  ],
  "eslintConfig": {
    "extends": "react-app"
  },
  "resolutions": {
    "webpack": "^5"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "@babel/cli": "^7.12.10",
    "@babel/core": "^7.12.10",
    "@babel/plugin-proposal-class-properties": "^7.12.1",
    "@babel/plugin-transform-async-to-generator": "^7.12.1",
    "@babel/plugin-transform-modules-commonjs": "^7.12.1",
    "@babel/plugin-transform-runtime": "^7.16.0",
    "@babel/plugin-transform-strict-mode": "^7.12.1",
    "@babel/preset-env": "^7.12.11",
    "@babel/preset-react": "^7.12.10",
    "@storybook/addon-actions": "6.5.6",
    "@storybook/addon-console": "^1.2.3",
    "@storybook/addon-controls": "^6.5.6",
    "@storybook/addon-info": "5.3.21",
    "@storybook/addon-knobs": "6.3.1",
    "@storybook/addon-links": "6.5.6",
    "@storybook/addon-measure": "^6.5.6",
    "@storybook/addon-notes": "5.3.21",
    "@storybook/addon-options": "5.3.21",
    "@storybook/addon-queryparams": "^6.2.9",
    "@storybook/addon-storyshots": "^6.5.6",
    "@storybook/addon-storysource": "6.5.6",
    "@storybook/addon-viewport": "6.5.6",
    "@storybook/addons": "6.5.6",
    "@storybook/builder-webpack5": "^6.5.6",
    "@storybook/manager-webpack5": "^6.5.6",
    "@storybook/storybook-deployer": "^2.8.11",
    "auto-changelog": "^1.16.2",
    "axios-mock-adapter": "^1.17.0",
    "babel-loader": "^8.2.2",
    "babel-plugin-import": "^1.13.3",
    "customize-cra": "^0.7.0",
    "eslint": "^6.7.2",
    "eslint-config-prettier": "^4.2.0",
    "eslint-config-react-app": "^3.0.7",
    "eslint-plugin-flowtype": "3.6.1",
    "eslint-plugin-i18n-json": "^2.4.1",
    "eslint-plugin-import": "2.x",
    "eslint-plugin-json": "^1.4.0",
    "eslint-plugin-jsx-a11y": "6.x",
    "eslint-plugin-prettier": "^3.0.1",
    "eslint-plugin-react": "^7.14.2",
    "eslint-plugin-react-hooks": "^1.6.0",
    "jest-localstorage-mock": "^2.4.2",
    "less-loader": "^5.0.0",
    "less-watch-compiler": "^1.14.1",
    "lint-staged": "^9.3.0",
    "pre-commit": "^1.2.2",
    "prettier": "^1.18.2",
    "pretty-quick": "^1.11.1",
    "react-app-rewire-less": "^2.1.3",
    "react-test-renderer": "^17.0.2",
    "release-it": "^13.5.1"
  }
}

`

i'm working on a mac.

**Comment by kekcuuuk** [comment]
have same issue

**Comment by rtturner** [comment]
Also running into this - coming from v6.4.19 to 6.5.x

I've found removing `@babel/plugin-transform-modules-commonjs` allows my stories to load but I'm not able to remove this  as a permanent solution. Also on babel 7 and webpack 5

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
