### ISSUE TITLE
Angular source files are containing processed information

### ISSUE THREAD

**Issue by Tallyb** [storybookjs/storybook#18439]
**Describe the bug**
When building storybook angular, source maps are not really sources. 

**To Reproduce**
Clone repo https://github.com/Tallyb/taskbox-angular-storybook-demo and run npm install. 
Run `npm run start`, open source file (in devtools): `button.component.ts`

Run `npm run storybook`. Open the same file. 

In the first case the code looks exactly like the original file. 
Inside storybook the code looks different: 

```
import { __decorate } from "tslib";
import __NG_CLI_RESOURCE__0 from "./button.css?ngResource";
import { Component, Input, Output, EventEmitter } from '@angular/core';
let ButtonComponent = class ButtonComponent {
    constructor() {
        /**
         * Is this the principal call to action on the page?
         */
        this.primary = false;
```

While it does not seem that crucial, in our larger code base there were additional changes, like variables defined as
var _a, _b etc. 

Is there a way to get the original code in the source maps? 

**System**
  System:
    OS: macOS 12.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 18.2.0 - ~/.nvm/versions/node/v18.2.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v18.2.0/bin/npm
  Browsers:
    Chrome: 102.0.5005.61
    Firefox: 97.0
    Safari: 15.5
  npmPackages:
    @storybook/addon-actions: ^6.5.0 => 6.5.7
    @storybook/addon-essentials: ^6.5.0 => 6.5.7
    @storybook/addon-interactions: ^6.5.0 => 6.5.7
    @storybook/addon-links: ^6.5.0 => 6.5.7
    @storybook/angular: ^6.5.0 => 6.5.7
    @storybook/builder-webpack5: ^6.5.7 => 6.5.7
    @storybook/manager-webpack5: ^6.5.7 => 6.5.7
    @storybook/testing-library: 0.0.11 => 0.0.11

Angular 14, but same was happening in angular 13. 

**Additional context**
It is using the angular storybook builder.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
