### ISSUE TITLE
[@storybook/addon-storyshots] Please upgrade the `react-test-renderer` version to v18.1.0 in`addon-storyshots`

### ISSUE THREAD

**Issue by NeoLSN** [storybookjs/storybook#18431]
**Describe the bug**

 TypeError: Cannot read properties of undefined (reading 'current')

      at warnIfNotScopedWithMatchingAct (node_modules/@storybook/addon-storyshots/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14999:31)
      at updateContainer (node_modules/@storybook/addon-storyshots/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:16413:7)
      at create (node_modules/@storybook/addon-storyshots/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:17149:3)
      at getRenderedTree (node_modules/@storybook/addon-storyshots/dist/ts3.9/frameworks/react/renderTree.js:24:18)
      at node_modules/@storybook/addon-storyshots/dist/ts3.9/test-bodies.js:9:24
      at Object.<anonymous> (node_modules/@storybook/addon-storyshots/dist/ts3.9/api/snapshotsTestsTemplate.js:29:24)

**To Reproduce**

1. Using react-v18 and following instructions of the document on [@storybook/addon-storyshots](https://www.npmjs.com/package/@storybook/addon-storyshots).
2. run `npm test`.

**System**
  System:
    OS: macOS 12.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 1.22.18 - ~/.nvm/versions/node/v16.13.2/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
  Browsers:
    Chrome: 102.0.5005.61
    Safari: 15.5
  npmPackages:
    @storybook/addon-essentials: 6.5.7 => 6.5.7 
    @storybook/addon-postcss: 2.0.0 => 2.0.0 
    @storybook/addon-storyshots: 6.5.7 => 6.5.7 
    @storybook/addon-storysource: 6.5.7 => 6.5.7 
    @storybook/builder-webpack5: 6.5.7 => 6.5.7 
    @storybook/manager-webpack5: 6.5.7 => 6.5.7 
    @storybook/react: 6.5.7 => 6.5.7 
    @storybook/testing-react: 1.3.0 => 1.3.0 

**Additional context**
N/A

**Comment by vojkog** [comment]
It seems that [EugeneDraitsev](https://github.com/EugeneDraitsev) also reported this in #17985.

**Comment by NeoLSN** [comment]
OK. But still suggest to support `"react-test-renderer": "18.1.0"` in the plugin.

**Comment by NeoLSN** [comment]
Re-open this issue until the bug has been fixed.

**Comment by arthurzakharov** [comment]
With new `6.5.9` error is still there

**Comment by geisterfurz007** [comment]
A related PR has been merged a couple hours ago: https://github.com/storybookjs/storybook/pull/18296; as of now, there hasn't been a new release though

**Comment by geisterfurz007** [comment]
The mentioned change has been released in https://github.com/storybookjs/storybook/releases/tag/v7.0.0-alpha.16, so I guess this could be closed?

**Comment by NeoLSN** [comment]
> The mentioned change has been released in https://github.com/storybookjs/storybook/releases/tag/v7.0.0-alpha.16, so I guess this could be closed?

I'll close it after stable version released.

**Comment by aliceathens** [comment]
I have upgraded to `"@storybook/react": "^7.0.0-alpha.16",` but it still doesn’t work for me.

**Comment by trizerr** [comment]
I patched @storybook/addon-storyshots to have 
`"react-test-renderer": "18.1.0"`
But for some reason, it was still looking for an older version of the renderer, which was installed under @storybook/addon-storyshots/node_modules.

So I've created bash file postinstall.sh, and added the following line to remove react-test-renderer from addon-storyshots/node_modules
`rm -rf node_modules/@storybook/addon-storyshots/node_modules/react-test-renderer`

and then just call this file in package.json postinstall
` "postinstall": "patch-package && bash ./postinstall.sh",`

this solved the issue for me

**Comment by NuiceT** [comment]
Same issue for me...

**Comment by shilman** [comment]
Can anybody confirm if the problem is still present in the latest prerelease?

Migration guide: https://storybook.js.org/migration-guides/7.0

**Comment by NeoLSN** [comment]
This issue has been solved in v7.
