### ISSUE TITLE
The error message for a missing addon that tries to load is very unclear

### ISSUE THREAD

**Issue by RHeynsZa** [storybookjs/storybook#18448]
**Is your feature request related to a problem? Please describe**
The error message when trying to load a non installed addon is really really undescriptive, and very confusing when trying to debug
```
WARN   Failed to load preset: {"type":"presets"} on level 1
ERR! TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received an instance of Object
```

**Describe the solution you'd like**
Maybe something like `Trying to import missing package, please check addons`

**Describe alternatives you've considered**
Not being stupid, and actually checking my addons. Yes ive tried, but this something I struggle with in general

**Are you able to assist to bring the feature to reality?**
Yeah i can PR this, if it seems like a good idea

**Comment by milesj** [comment]
I see this error when enabling the `@storybook/addon-a11y` addon.

**Comment by prewk** [comment]
Definitely would've saved me an hour's work today

**Comment by chriskuech** [comment]
I keep adding storybook new to a project but after some `npm install`s this error occurs. It is pretty impossible to debug and I think my experience proves that this issue (at least sometimes) is unrelated to missing add-ons.

**Comment by lobaak** [comment]
We're also experiencing this. Is there a fix?

**Comment by razzeee** [comment]
I'm also seeing this whenever I enable `@storybook/addon-a11y`

**Comment by shilman** [comment]
Ta-da!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.26 containing PR #20455 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by maciej-gurban** [comment]
Can we get this fixed on 6.x as well? 7.x doesn't seem to play well with yarn pnp just yet
