### ISSUE TITLE
ModuleNotFoundError: Module not found: Error: Package path ./lib/utils is not exported from package /XXX/node_modules/cheerio (see exports field in /XXX/node_modules/cheerio/package.json)

### ISSUE THREAD

**Issue by shamaz332** [storybookjs/storybook#18450]
I'm facing this issue while running yarn storybook
![Screenshot from 2022-06-10 00-30-24](https://user-images.githubusercontent.com/40767080/172929578-e1f8f705-3806-42f5-b3df-e6118f87255f.png)

**Comment by shamaz332** [comment]
@shilman @ndelangen @paulrosania @Peeja @theshortcut @theinterned

**Comment by shilman** [comment]
Do you a have a reproduction repo you can share? If not, can you create one? See [how to create a repro](https://storybook.js.org/docs/react/contribute/how-to-reproduce). We prioritize issues with reproductions over those without. Thank you! 🙏

**Comment by lenichols** [comment]
think im running into the same issue trying to use storybook with a nextjs app.

<img width="876" alt="Screen Shot 2022-06-12 at 9 26 13 PM" src="https://user-images.githubusercontent.com/5247113/173279673-e341dfdf-fc9a-4a39-a1f0-a16b7ea5ac3c.png">

**Comment by sgerrand** [comment]
You'll need to resolve the version of `cheerio` to 1.0.0-rc8 or lower as `util.js` was removed after then.

**Comment by ndelangen** [comment]
1.0.0-rc8 or LOWER?

Don;t you mean higher?

**Comment by sgerrand** [comment]
No, I don't. As I said previously:

> `util.js` was removed after then.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).

**Comment by mahirahman** [comment]
I was able to resolve this by using `"cheerio": "1.0.0-rc.6"`.
`"cheerio": "1.0.0-rc.8"` did not work.
