### ISSUE TITLE
Cannot read properties of undefined (reading 'compilation')

### ISSUE THREAD

**Issue by Marwan-AE** [storybookjs/storybook#18473]
Updated storybook and using webpack 5 but still getting the error 

Cannot read properties of undefined (reading 'compilation')

**Comment by lizschwab** [comment]
I had this same issue and was able to resolve it by adding in a missing `styled-jsx` dev dependency package. Hope this helps!

**Comment by MarwanEsm** [comment]
> I had this same issue and was able to resolve it by adding in a missing `styled-jsx` dev dependency package. Hope this helps!

Thanks, still trying :)

**Comment by victorhenriq3** [comment]
Do you have the repository of this code? This problem already happened to me and I solved it just by deleting the **.cache** folder in `node_modules/.cache`

**Comment by huyhoang160593** [comment]
None of the suggest ways here is working :(. Pls helppp

**Comment by ndelangen** [comment]
Without a reproduction or further information there's nothing we can do to help here.

I'd be happy to reopen and investigate when a reproduction is added.
