### ISSUE TITLE
Azure devops npm ci error

### ISSUE THREAD

**Issue by rexkenley** [storybookjs/storybook#18492]
**Describe the bug**
npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
npm ERR! 
npm ERR! Invalid: lock file's @storybook/expect@27.4.2 does not satisfy @storybook/expect@27.5.2-0
npm ERR! Missing: require-from-string@2.0.2 from lock file
npm ERR! Missing: acorn@8.7.1 from lock file

**To Reproduce**
This can only be reproduced in Azure devOps cloud. I don't get this error when running from my laptop. 

**System**
*Note this was ran on my laptop.

System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (102.0.1245.41)
  npmPackages:
    @storybook/addon-actions: ^6.5.9 => 6.5.9
    @storybook/addon-essentials: ^6.5.9 => 6.5.9
    @storybook/addon-interactions: ^6.5.9 => 6.5.9
    @storybook/addon-jest: ^6.5.9 => 6.5.9
    @storybook/addon-links: ^6.5.9 => 6.5.9
    @storybook/jest: ^0.0.10 => 0.0.10
    @storybook/react: ^6.5.9 => 6.5.9
    @storybook/testing-library: ^0.0.13 => 0.0.13
    @storybook/testing-react: ^1.3.0 => 1.3.0

**Comment by Tovli** [comment]
I'm having the same issue :(
Tried deleting packages-lock.json but no change
