### ISSUE TITLE
Storybook glob pattern ignored, all files are included

### ISSUE THREAD

**Issue by eranimo** [storybookjs/storybook#18496]
**Describe the bug**
Storybook is including all files, breaking on Jest test files and causing errors like:

```
Cannot find name 'it'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha`.
```

All files in the app are being loaded by Storybook, which causes runtime errors when loading stories because these files were not intended to be ran in storybook.

**To Reproduce**
Seems to start happening in v6.3, after I switched from webpack 4 to webpack 5.

**System**
```
  System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 14.19.1 - ~/.nvm/versions/node/v14.19.1/bin/node
    npm: 6.14.16 - ~/.nvm/versions/node/v14.19.1/bin/npm
  Browsers:
    Chrome: 102.0.5005.115
    Firefox: 101.0.1
    Safari: 13.1.3
  npmPackages:
    @storybook/addon-essentials: 6.3.12 => 6.3.12
    @storybook/addon-knobs: ^6.4.0 => 6.4.0
    @storybook/addons: 6.3.12 => 6.3.12
    @storybook/builder-webpack5: 6.3.12 => 6.3.12
    @storybook/manager-webpack5: 6.3.12 => 6.3.12
    @storybook/react: 6.3.12 => 6.3.12
    @storybook/theming: 6.3.12 => 6.3.12
```

This also happens in v6.5.

I'm also not using glob patterns in the stories option at all. I am manually including each storybook story file, which didn't solve the issue.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
