### ISSUE TITLE
Getting isPlainObject.isPlainObject is not a function when using boolean props in ComponentStory Template.  

### ISSUE THREAD

**Issue by jberrydev** [storybookjs/storybook#18495]
**Describe the bug**
Getting isPlainObject.isPlainObject is not a function when using boolean props in ComponentStory Template.  
```
export default {
  component: SkuTextField,
  title: 'Components/TextField',
} as ComponentMeta<typeof SkuTextField>;

const SkuTextFieldTemplate: ComponentStory<typeof SkuTextField> = (props) => {
  return (
      <SkuTextField
        label="With helper text"
        placeholder="Text Input"
        helperText="Helper text"
        disabled
        {...props}
      />
  );
};

export const TextField = SkuTextFieldTemplate.bind({});
TextField.args = {};
```
When adding the `disabled` boolean prop storybook throws the above error

Versions
```
    "react": "^18.1.0",
    "@storybook/addon-essentials": "^6.5.9",
    "@storybook/builder-webpack5": "^6.5.9",
    "@storybook/core-server": "^6.5.9",
    "@storybook/manager-webpack5": "^6.5.9",
    "@storybook/react": "^6.5.9",
```

**Additional context**
I am using nx for monorepo, but from what I can tell after upgrading storybook I am getting the following.  I can purely add `disabled='disabled'` as a string to fix, but this should truly be a boolean.  I made sure my types were all good, but can't figure out why this can't be done.

**Comment by jawakardurai** [comment]
This happens for my component too, structure is provided below and I don't have any boolean props.

```jsx
import { PressRelease } from "components/Design/Card/PressRelease";
import { Container } from "components/Design/Grid/Grid";
import { Listing } from "components/Listing";
import React from "react";
import { constructArtDirectedImage } from "utils/constructMockImage";

export default {
  title: "component/PressRelease",
};

const PressReleaseTemplate = (props) => (
  <Container>
    <Listing>
      <PressRelease {...props} />
      <PressRelease {...props} />
    </Listing>
  </Container>
);

export const DefaultPressReleaseListing = PressReleaseTemplate.bind({});
DefaultPressReleaseListing.args = {
  release: {
    title: "Press release 2020 October",
    hotels: [
      {
        name: "RIMBA Jimbaran BALI",
      },
      {
        name: "AYANA Resort and Spa, BALI",
      },
      {
        name: "AYANA Resort and Spa, BALI",
      },
      {
        name: "Ayana Jakarta",
      },
    ],
    summary:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc lobortis purus non rutrum facilisis. Nam maximus condimentum lorem non sodales. Sed eget felis ante. Ut non posuere ex. Cras viverra nisl sit amet augue vehicula, id dictum est consequat. Praesent nunc dui, dignissim a orci sit amet, hendrerit venenatis massa. Vivamus mi magna, ornare at egestas elementum, dapibus non urna. Praesent a metus ut libero ultrices sodales. Etiam sed efficitur mi. Sed rhoncus id turpis et luctus. Vivamus ultrices sem in ex pellentesque, vel vulputate elit luctus. ",
    slug: "/bai/press/1",
    date: "2022-10-29",
    ...constructArtDirectedImage({
      mobile: [300, 200],
      desktop: [300, 200],
    }),
  },
};

```

**Comment by basharov** [comment]
I face the same issue and I see that it happens when I use objects more complex than strings/numbers/booleans, e.g. objects, arrays, like this:

```
  paymentMethods: [
    { id: 1, label: 'Cash' },
    { id: 2, label: 'Wire' },
    { id: 3, label: 'BTC' },
    { id: 4, label: 'PayPal' },
  ]
```

**Comment by basharov** [comment]
I had a look at `is-plain-object` dependency in my project and it was something like `2.0.1`. Probably it was a dependency for some other library I have. 

I noticed that the `isPlainObject` function was a default export. However, the latest version `5.0.0` has a named export. 

I added `"is-plain-object": "5.0.0"` to plackage.json to replace the old one and now it works.

**Comment by jtrivette** [comment]
> I had a look at `is-plain-object` dependency in my project and it was something like `2.0.1`. Probably it was a dependency for some other library I have.
> 
> I noticed that the `isPlainObject` function was a default export. However, the latest version `5.0.0` has a named export.
> 
> I added `"is-plain-object": "5.0.0"` to package.json to replace the old one and now it works.

This worked for me too.  I was on 2.0.3.  Thanks!

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
