### ISSUE TITLE
Websockets connection fails in GitHub Codespace

### ISSUE THREAD

**Issue by kaelig** [storybookjs/storybook#18512]
**Describe the bug**

Websockets connection fails when developing in GitHub Codespaces, which seems to trigger an iframe refresh every few seconds.
<img width="988" alt="Screen Shot 2022-06-19 at 8 05 39 PM" src="https://user-images.githubusercontent.com/85783/174518132-a35b005b-6e49-489c-aea5-86712fe6f701.png">

**To Reproduce**

Here's a repository with the appropriate dev container settings: https://github.com/kaelig/vite-storybook-repro-ws-bug

**:warning: Pre-requisite:** You'll need to have access to the GitHub Codespaces Beta to create a new CodeSpace. Sign up here: https://github.com/features/codespaces/signup

1. Open a CodeSpace for https://github.com/kaelig/vite-storybook-repro-ws-bug <img width="937" alt="Screen Shot 2022-06-19 at 8 01 32 PM" src="https://user-images.githubusercontent.com/85783/174517914-cc5a9b24-5e18-4788-8af8-3d5687e6603d.png">

2. In the CodeSpace VS Code terminal, run `npm run storybook`
3. Look for console errors in dev tools

**System**

```
Environment Info:

  System:
    OS: Linux 5.4 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (4) x64 Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/bin/yarn
    npm: 8.5.0 - /usr/local/bin/npm
  npmPackages:
    @storybook/addon-actions: ^6.5.9 => 6.5.9 
    @storybook/addon-essentials: ^6.5.9 => 6.5.9 
    @storybook/addon-interactions: ^6.5.9 => 6.5.9 
    @storybook/addon-links: ^6.5.9 => 6.5.9 
    @storybook/builder-vite: ^0.1.36 => 0.1.36 
    @storybook/react: ^6.5.9 => 6.5.9 
    @storybook/testing-library: ^0.0.13 => 0.0.13 
```

**Additional context**

I only tested with the Vite builder, but I assume this probably applies to other builders too.

**Comment by LeoDog896** [comment]
This seems to be a [bug with codespaces](https://github.com/community/community/discussions/3908).

**Comment by medihack** [comment]
Same with Gitpod (and I guess any Cloud IDE). The problem is that the Websocket server address is not configurable (see #20068). On the other side, Next.js has no problem with its HMR and Websocket when using Gitpod or GitHub Codespaces.

**Comment by kaelig** [comment]
This bug is related to https://github.com/storybookjs/storybook/issues/20068

**Comment by kaelig** [comment]
Closing as duplicate of https://github.com/storybookjs/storybook/issues/20068
