### ISSUE TITLE
storybook doesnt want to build with react-leaflet maps component

### ISSUE THREAD

**Issue by milena-valkova** [storybookjs/storybook#18538]
**Describe the bug**
I created an ordinary component which loads the react-leaflet map, but when I try to view it in storybook, I can't because the build brokes and storybook doesn't want to start at all.

**To Reproduce**
https://github.com/milena-valkova/react-leaflet-storybook-repro

**System**
Environment Info:
  System:
    OS: macOS 12.2.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.18 - ~/.yarn/bin/yarn
    npm: 8.6.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 102.0.5005.115
    Safari: 15.3

**Comment by ferdicus** [comment]
Hi there 👋🏿 

I was running into something as well when trying to use react-leaflet with storybook. 

Problem also being, that storybooks pipeline is different than the one I use under production. 

I was getting 

```
ERROR in ./node_modules/@react-leaflet/core/lib/path.js 10:47
Module parse failed: Unexpected token (10:47)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     useEffect(function updatePathOptions() {
|         if (props.pathOptions !== optionsRef.current) {
>             const options = props.pathOptions ?? {};
```

There are actually quite some issues open within the react-leaflet repo concerning this issue specifically. 


Problem being the highlighted token `??` in the error message above and no loader... well like the error message said. 

I've solved this via adding an additional rule within storybooks `main.js` file in `/.storybook`

Under your `module.exports` section add this:
```js
module.exports = {
  webpackFinal: (config) => {
    const leafletRule = {
      test: /\.js$/,
      // is you're smarter than me, you could also do it via MatchPattern 🤷‍♀️
      include: [ /node_modules\/@react-leaflet/, /node_modules\/react-leaflet/],
      use: [
        {
          loader: 'babel-loader',
          options:{"presets":[["@babel/preset-env",{"modules":"commonjs"}]]}
        }
      ]
    }

    config.module.rules.push(leafletRule);

    return config;
  },
  stories: [
    // ... where to look for stories
  ],
  addons: [
    // ... your addons here 
  ],
  framework: "@storybook/react",
  core: {
    disableTelemetry: true,
    enableCrashReports: false,
  },
};
```


Now, something like this
```js
const options = props.pathOptions ?? {};
```

will => babel-loaded => become this

```js
"use strict";

var _props$pathOptions;

const options = (_props$pathOptions = props.pathOptions) !== null && _props$pathOptions !== void 0 ? _props$pathOptions : {};
```

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
