### ISSUE TITLE
Stories are not sorted by their export when in custom filename format

### ISSUE THREAD

**Issue by siminino** [storybookjs/storybook#18535]
**Describe the bug**
The issue where stories are not sorted by their export order persist if you use a different filename format for stories file.
I work in a project that uses the format `*.example.js` for every component stories, as on the "To Reproduce" steps below.

**To Reproduce**
- npx create-react-app storybook-play
- cd storybook-play; npm install
- npx sb init --builder webpack5
- change .storybook/main.js to:
```javascript
module.exports = {
  "stories": [
  "stories": [
    "../src/**/*.stories.mdx",
    "../src/**/*.stories.@(js|jsx|ts|tsx)",
    "../src/**/*.example.@(js|jsx|ts|tsx)"      // <--- ADD THIS LINE
  ],
  "addons": [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/addon-interactions",
  ],
  "framework": "@storybook/react",
  "core": {
    "builder": "@storybook/builder-webpack5"
  }
}
```
- rename button stories file to example:
```mv src/stories/Button.stories.jsx src/stories/Button.example.jsx```
- start-storybook

**System**
Environment Info:
  System:
    OS: macOS 12.3.1
    CPU: (8) arm64 Apple M1 Pro
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.18 - ~/.nvm/versions/node/v16.13.1/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
  Browsers:
    Chrome: 102.0.5005.115
    Safari: 15.4
  npmPackages:
    @storybook/addon-actions: ^6.5.9 => 6.5.9
    @storybook/addon-essentials: ^6.5.9 => 6.5.9
    @storybook/addon-interactions: ^6.5.9 => 6.5.9
    @storybook/addon-links: ^6.5.9 => 6.5.9
    @storybook/builder-webpack5: ^6.5.9 => 6.5.9
    @storybook/manager-webpack5: ^6.5.9 => 6.5.9
    @storybook/node-logger: ^6.5.9 => 6.5.9
    @storybook/preset-create-react-app: ^4.1.2 => 4.1.2
    @storybook/react: ^6.5.9 => 6.5.9
    @storybook/testing-library: ^0.0.13 => 0.0.13

**Additional context**
<img width="229" alt="Screenshot 2022-06-22 at 13 16 05" src="https://user-images.githubusercontent.com/632044/175016097-9503ae8e-5efb-46d6-81d7-defe03573d5e.png">

**Comment by shilman** [comment]
We don't support `.example.js` out of the box in Storybook. However, you can configure it yourself by adding this babel plugin to a custom webpack or babel config: https://github.com/storybookjs/babel-plugin-named-exports-order

Closing this for now!

**Comment by siminino** [comment]
@shilman 
Doesn't make sense allowing different filename formats in storybook by `stories` settings (in main.js) and not supporting it. I would recommend removing it from the docs.
Obs: this information you gave is not even mentioned on the docs.
https://storybook.js.org/docs/react/configure/overview#configure-your-storybook-project
https://storybook.js.org/docs/react/configure/overview#configure-story-loading

**Comment by siminino** [comment]
For those into the same issue, this is the `main.js` after applying the workaround:
```javascript
module.exports = {
  stories: ['../src/components/**/*.example.js'],
  framework: '@storybook/react',
  addons: [
    '@storybook/addon-actions',
    '@storybook/addon-viewport',
    '@storybook/addon-docs',
    '@storybook/addon-controls',
  ],
  core: {
    builder: 'webpack5',
  },
  babel: async options => ({
    ...options,
    plugins: [
      ...options.plugins,
      ['babel-plugin-named-exports-order'],
    ]
  }),
}
```
