### ISSUE TITLE
MDX2: Table incorrectly rendering

### ISSUE THREAD

**Issue by stramel** [storybookjs/storybook#18556]
**Describe the bug**
When inserting a markdown table into a `.mdx` story with the `previewMdx2: true` set. It causes the table to render as text instead of as a table. Disabling the `previewMdx2` setting, and restarting renders the table correctly.

**To Reproduce**
Insert this into a `.mdx` story

```md
| Name                                                 | Value                     | Reference                  | Type      |
| ---------------------------------------------------- | ------------------------- | -------------------------- | --------- |
| button-background-color-icon-dark-backdrop-default   | rgba(0, 0, 0, 0)          | transparent                | Color     |
```

in your `main.js` set the following flag

```diff
features: {
+  previewMdx2: true
}
```

run `npm run start-storybook`

**System**
```txt
System:
    OS: macOS 12.3.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 16.14.2 - /private/var/folders/hs/d7smfnbx6dlf7m99x1f7cn640000gs/T/xfs-2c8ef741/node
    Yarn: 3.2.1 - /private/var/folders/hs/d7smfnbx6dlf7m99x1f7cn640000gs/T/xfs-2c8ef741/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Chrome: 103.0.5060.53
    Edge: 102.0.1245.41
    Firefox: 91.10.0
    Safari: 15.4
```

**Comment by maicol07** [comment]
In the meantime, I've found a workaround:

Paste your markdown tables in this website to convert them to HTML tables: [https://tableconvert.com/markdown-to-html](https://tableconvert.com/markdown-to-html)

After pasting the HTML table back to MDX replace the `<table>` element with Storybook `<Table` element

**Comment by ndelangen** [comment]
@shilman I ran into this as well here: https://github.com/storybookjs/storybook/pull/18735

**Comment by ndelangen** [comment]
It looks looks it's just not supported in mdx2:
https://mdxjs.com/table-of-components/

**Comment by ndelangen** [comment]
Looks like we need to apply some options / setting:

![Screen Shot 2022-07-19 at 16 38 27](https://user-images.githubusercontent.com/3070389/179777671-249e0d7d-f40e-42c4-8fc4-e7848320d3e1.png)

https://mdxjs.com/playground/

**Comment by ivlev-ye** [comment]
This change should fix this https://github.com/storybookjs/mdx2-csf/pull/12

**Comment by shilman** [comment]
We can add an automigration that tells them:

"If you use table / x / y / z and want GFM support in MDX2, we can add it for you [y/N]"

More info: https://mdxjs.com/migrating/v2/#gfm

**Comment by fcisio** [comment]
Very much looking forward to this!
My usage of SWC breaks my MDX (01) at the moment and MDX2 seems to be way more stable in my environment.

But my tables & checkboxes can't currently be transformed.

**Comment by shilman** [comment]
Closing as duplicate to #20091
