### ISSUE TITLE
Storybook 6.5.9 not working with React 18.

### ISSUE THREAD

**Issue by Vinayaksma** [storybookjs/storybook#18559]
**Describe the bug**
In my project with React 18, the version of Storybook and its add-ons with version 6.5.9 are not compatible with react version 18. 
Getting failed while installing package.

Conflicting peer dependency: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@"^16.13.1 || ^17.0.0" from @mdx-js/react@1.6.22
npm WARN   node_modules/@storybook/addon-docs/node_modules/@mdx-js/react
npm WARN     @mdx-js/react@"^1.6.22" from @storybook/addon-docs@6.5.9
npm WARN     node_modules/@storybook/addon-docs

**Comment by nonameolsson** [comment]
I have the same problem :(

**Comment by konhi** [comment]
@nonameolsson it might be fixed in v7.0 - which is currently in alpha ✨

https://twitter.com/storybookjs/status/1550126340648476672
![image](https://user-images.githubusercontent.com/61631665/180418160-a3e2ddbe-14d3-405e-8fe5-122c67556635.png)

**Comment by ColmBhandal** [comment]
Similar issue for me in `6.5.10`:

```
npm WARN While resolving: react-element-to-jsx-string@14.3.4
npm WARN Found: react@18.2.0
npm WARN node_modules/react
npm WARN   peer react@"^16.8.4 || ^17.0.0" from react-inspector@5.1.1
npm WARN   node_modules/@storybook/addon-actions/node_modules/react-inspector
npm WARN     react-inspector@"^5.1.0" from @storybook/addon-actions@6.5.10
npm WARN     node_modules/@storybook/addon-actions
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^0.14.8 || ^15.0.1 || ^16.0.0 || ^17.0.1" from react-element-to-jsx-string@14.3.4
npm WARN node_modules/@storybook/react/node_modules/react-element-to-jsx-string
npm WARN   react-element-to-jsx-string@"^14.3.4" from @storybook/react@6.5.10
npm WARN   node_modules/@storybook/react
npm WARN 
npm WARN Conflicting peer dependency: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@"^0.14.8 || ^15.0.1 || ^16.0.0 || ^17.0.1" from react-element-to-jsx-string@14.3.4
npm WARN   node_modules/@storybook/react/node_modules/react-element-to-jsx-string
npm WARN     react-element-to-jsx-string@"^14.3.4" from @storybook/react@6.5.10
npm WARN     node_modules/@storybook/react
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-element-to-jsx-string@14.3.4
npm WARN Found: react-dom@18.2.0
npm WARN node_modules/react-dom
npm WARN   react-dom@"^18.2.0" from the root project
npm WARN   40 more (@chakra-ui/modal, @chakra-ui/portal, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react-dom@"^0.14.8 || ^15.0.1 || ^16.0.0 || ^17.0.1" from react-element-to-jsx-string@14.3.4
npm WARN node_modules/@storybook/react/node_modules/react-element-to-jsx-string
npm WARN   react-element-to-jsx-string@"^14.3.4" from @storybook/react@6.5.10
npm WARN   node_modules/@storybook/react
npm WARN 
npm WARN Conflicting peer dependency: react-dom@17.0.2
npm WARN node_modules/react-dom
npm WARN   peer react-dom@"^0.14.8 || ^15.0.1 || ^16.0.0 || ^17.0.1" from react-element-to-jsx-string@14.3.4
npm WARN   node_modules/@storybook/react/node_modules/react-element-to-jsx-string
npm WARN     react-element-to-jsx-string@"^14.3.4" from @storybook/react@6.5.10
npm WARN     node_modules/@storybook/react
```

**Comment by der-daniel** [comment]
See https://github.com/algolia/react-element-to-jsx-string/issues/728

This is already fixed by `react-element-to-jsx-string`

**Comment by morganney** [comment]
> See [algolia/react-element-to-jsx-string#728](https://github.com/algolia/react-element-to-jsx-string/issues/728)
> 
> This is already fixed by `react-element-to-jsx-string`
> 
> Maybe just bumping the dep would fix it.

```json
  "overrides": {
    "@storybook/react": {
      "react-element-to-jsx-string": "15.0.0"
    }
  }
```

**Comment by shilman** [comment]
Olé!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-alpha.30 containing PR #19104 that references this issue. Upgrade today to the `@future` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by cameron-martin** [comment]
`@mdx-js/mdx`, `@mdx-js/react` and `@mdx-js/loader` v1 is still used by the docs addon, which only support React 18. I did try upgrading these to v2, but hit a lot of issues with those packages and a lot of their dependencies being esmodule-only.

These are mentioned in the original post. Can this be re-opened?

**Comment by daphnesmit** [comment]
N Could not resolve dependency:
npm WARN peer react@"^16.8.4 || ^17.0.0" from react-inspector@5.1.1
npm WARN node_modules/@storybook/addon-actions/node_modules/react-inspector
npm WARN   react-inspector@"^5.1.0" from @storybook/addon-actions@6.5.13

**Comment by shilman** [comment]
@ismay mdx has been upgraded in v7 `npx sb@next upgrade --prerelease`

@daphnesmit npm audit warnings are fixed in v7. can't be fixed in v6 due to semver/breaking changes in dependent packages.
