### ISSUE TITLE
MDX2: Custom components getting ignored

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#18553]
_Originally posted by @shilman in https://github.com/storybookjs/storybook/issues/18383#issuecomment-1164673384_

@sgrobert @dgonzalezr MDX2 support is experimental and we're still working out the kinks. Thanks for your patience!

I think what's going on there is that MDX1 allows you to pass in a mapping of elements to the corresponding components, such as:

```
{
   h1: MyH1Component,
   h2: MyH2Component,
   ...
}
```

We use this to define the components to render the docs in MDX1. However, it is ignored in MDX2, either by the underlying MDX2 library or by Storybook's usage of it. I'll follow up in a separate issue.

**Comment by wooorm** [comment]
This should be fine. Though, if you are using component passing through a provider (such as `@mdx-js/react`), you need to configure `@mdx-js/mdx` to compile for that providers: https://mdxjs.com/packages/mdx/#optionsproviderimportsource

**Comment by sgrobert** [comment]
Hi @wooorm / @shilman ,

Pardon me for getting back on this late. 

Just wondering how I may help to implement this into StorybookJS? Currently on `StorybookJS v6.5.9`. Hope to help resolve the issue where the default StorybookJS styled-components will look the way they should, currently when on `MDX2`, anything that is on Markdown doesn't work at all. 

The only good thing is the StorybookJS currently works. 

Thank you!

**Comment by shilman** [comment]
Closing as dupe to [#19532](https://github.com/storybookjs/storybook/issues/19532)
