### ISSUE TITLE
MDX2: HTML comments break transcluded Markdown

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#18554]
_Originally posted by @pixelass in https://github.com/storybookjs/storybook/issues/18383#issuecomment-1160767410_

Looks like I found the issue while trying to build the repro.

It is an HTML comment within the markdown

`README.md`  
```md
# This file will not work

<!-- Because of this comment -->
```
`Test.stories.mdx`  
```mdx
import { Meta } from "@storybook/addon-docs";
import Readme from "../README.md";

<Meta title="Just / A /Test" />

<Readme />

```

which is then reactified via:

`.stroybook/main.js` (partial)   
```js

    {
      name: "@storybook/addon-docs",
      options: {
        configureJSX: true,
        sourceLoaderOptions: null,
        transcludeMarkdown: true,
      },
    },

```

Here's the very minimal repro: https://github.com/pixelass/sb-repro-mdx

There is only one story and a readme.md that should be rendered.

We used npm since this is how our project is set up but I expect the same issue to occur with yarn.

---

EDIT: I want to mention that removing the comments from all markdown files is not an option (it is also valid md and therefore should not cause issues)

**Comment by zhyd1997** [comment]
it's [mdx](https://mdxjs.com/playground/) issue:

<img width="2012" alt="Screen Shot 2022-07-13 at 18 14 46" src="https://user-images.githubusercontent.com/31362988/178710385-716467f0-0c89-4a35-9381-e8240b9439be.png">

**Comment by shilman** [comment]
Closing as dupe to [#20200](https://github.com/storybookjs/storybook/issues/20200)
