### ISSUE TITLE
[SOLVED] svgr config for typescript + storybook + next.js + webpack 5

### ISSUE THREAD

**Issue by lynndylanhurley** [storybookjs/storybook#18557]
This was very painful to figure out. I'm hoping it helps anyone that runs into the same issue.

## Goal

To use the [svgr](https://react-svgr.com/) plugin in the following way:

```tsx
import React from 'react';

// default export should return the URL to the asset
import svgUrl from './img/test.svg';

// named export should return a react component
import { ReactComponent as Svg } from './img/test.svg';

const Test: React.FC = () => (
  <>
    {/* use default import as URL */}
    <img src={svgUrl} />

    {/* use named import as react componenthttps://react-svgr.com/ */
    <Svg />
  </>
);
```

### Typescript

Create a file called `globals.d.ts` at the root of your next.js project and add the following:

```ts
declare module '*.svg' {
  const ReactComponent: React.FC<React.SVGProps<SVGSVGElement>>;
  const content: string;

  export { ReactComponent };
  export default content;
}
```

### Next.js

Assuming you've installed the `svgr` plugin, add this to your `.next.config.js` file:

```js
/** @type {import('next').NextConfig} */
const nextConfig = {
  // ... other next config items

  webpack: config => {
    // ... other rules

    config.module.rules.push({
      test: /\.svg$/,
      use: [
        {
          loader: '@svgr/webpack'
        },
        {
          loader: 'file-loader',
          options: {
            name: 'static/[path][name].[ext]'
          }
        }
      ],
      type: 'javascript/auto',
      issuer: {
        and: [/\.(ts|tsx|js|jsx|md|mdx)$/]
      }
    });

    return config;
  }
};

module.exports = nextConfig;

```

### Storybook

My entire `.storybook/main.js` file:

```js
const path = require('path');
const TsconfigPathsPlugin = require('tsconfig-paths-webpack-plugin');

module.exports = {
  staticDirs: [
    '../public',
  ],
  stories: [
    '../stories/**/*.stories.mdx',
    '../(blocks|components)/**/*.stories.@(js|jsx|ts|tsx)'
  ],
  addons: [
    'storybook-addon-next',
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    '@storybook/addon-interactions'
  ],
  framework: '@storybook/react',
  core: {
    builder: '@storybook/builder-webpack5'
  },
  webpackFinal: async (config) => {
    // configure for absolute imports
    config.resolve.plugins = [
      ...(config.resolve.plugins || []),
      new TsconfigPathsPlugin({
        extensions: config.resolve.extensions,
      }),
    ];

    // disable whatever is already set to load SVGs
    config.module.rules
      .filter(rule => rule.test.test('.svg'))
      .forEach(rule => rule.exclude = /\.svg$/i);

    // add SVGR instead
    config.module.rules.push({
      test: /\.svg$/,
      use: [
        {
          loader: '@svgr/webpack'
        },
        {
          loader: 'file-loader',
          options: {
            name: 'static/media/[path][name].[ext]'
          }
        }
      ],
      type: 'javascript/auto',
      issuer: {
        and: [/\.(ts|tsx|js|jsx|md|mdx)$/]
      }
    });

    return config;
  }
}
```

**Comment by tomschall** [comment]
Thanks man, you helped me a lot. <3

**Comment by husnainali92** [comment]
I'm getting this error. I'm using react + typescript + storybook
TypeError: Cannot read property 'test' of undefined
![image](https://user-images.githubusercontent.com/101558118/207423106-c27b91d2-03d3-415a-9a0e-1baa82ae6c16.png)

**Comment by iKBAHT** [comment]
@husnainali92 
fix this code
```
config.module.rules
      .filter(rule => rule && rule.test.test('.svg'))
      .forEach(rule => rule.exclude = /\.svg$/i);
```

**Comment by IhToN** [comment]
Thanks to this my Storybook installation is not crashing anymore but I'm getting the next error when trying to load a SVG :/

`Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" viewBox="0 0 32 32"`

**Comment by eli-front** [comment]
this worked for me
```
import type { StorybookConfig } from '@storybook/nextjs';


const config: StorybookConfig = {
  stories: [
    '../components/**/*.stories.@(js|jsx|ts|tsx)',
    '../components/**/*.stories.mdx',
  ],
  addons: [
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    '@storybook/addon-interactions',
  ],
  framework: {
    name: '@storybook/nextjs',
    options: {},
  },
  docs: {
    autodocs: 'tag',
  },
  staticDirs: [{ from: '../public', to: '/public' }],
  core: {
    builder: '@storybook/builder-webpack5',
  },
  webpackFinal: async config => {
    const imageRule = config.module?.rules?.find(rule => {
      const test = (rule as { test: RegExp }).test

      if (!test) {
        return false
      }

      return test.test('.svg')
    }) as { exclude: RegExp }

    imageRule.exclude = /\.svg$/

    config.module?.rules?.push({
      test: /\.svg$/,
      use: ['@svgr/webpack']
    })

    return config
  }

};
export default config;

```

**Comment by con-dog** [comment]
Any solutions for vite.config.js??????? Still not working for me:

```
const { mergeConfig } = require('vite')

module.exports = {
  stories: ['../src/**/*.stories.mdx', '../src/**/*.stories.@(js|jsx|ts|tsx)'],
  addons: [
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    '@storybook/addon-interactions'
  ],
  framework: '@storybook/react',
  core: {
    builder: '@storybook/builder-vite'
  },
  features: {
    storyStoreV7: true
  },
  async viteFinal(config) {
    // Merge custom configuration into the default config
    return mergeConfig(config, {
      // Use the same "resolve" configuration as your app
      resolve: (await import('../vite.config.js')).default.resolve,
      // Add dependencies to pre-optimization
      optimizeDeps: {
        include: ['storybook-dark-mode']
      }
    })
  }
}

```

**Comment by tomschall** [comment]
> Any solutions for vite.config.js??????? Still not working for me:
> 
> 
> 
> ```
> 
> const { mergeConfig } = require('vite')
> 
> 
> 
> module.exports = {
> 
>   stories: ['../src/**/*.stories.mdx', '../src/**/*.stories.@(js|jsx|ts|tsx)'],
> 
>   addons: [
> 
>     '@storybook/addon-links',
> 
>     '@storybook/addon-essentials',
> 
>     '@storybook/addon-interactions'
> 
>   ],
> 
>   framework: '@storybook/react',
> 
>   core: {
> 
>     builder: '@storybook/builder-vite'
> 
>   },
> 
>   features: {
> 
>     storyStoreV7: true
> 
>   },
> 
>   async viteFinal(config) {
> 
>     // Merge custom configuration into the default config
> 
>     return mergeConfig(config, {
> 
>       // Use the same "resolve" configuration as your app
> 
>       resolve: (await import('../vite.config.js')).default.resolve,
> 
>       // Add dependencies to pre-optimization
> 
>       optimizeDeps: {
> 
>         include: ['storybook-dark-mode']
> 
>       }
> 
>     })
> 
>   }
> 
> }
> 
> 
> 
> ```
> 
> 

You could use svgr to generate typecript svg components, this will render you one svg component per svg. We use it in our project and you can take a look at how we do it here (build-icons):

https://github.com/smartive-education/design-system-component-library-yeahyeahyeah/blob/master/package.json

**Comment by MarkLyck** [comment]
> I was able to make it work with:
> 
> * `"storybook": "^7.0.0-beta.54"`
> * `"@svgr/webpack": "^6.5.1"`
> 
> following the `storybook-addon-next`’s [Custom Webpack Config](https://github.com/RyanClementsHax/storybook-addon-next/blob/06480c7de9424296b8ffdfa5df5ecf54f378213a/README.md#custom-webpack-config) section. I’ve just added some checks so the TS is happy:
> 
> ```tsx
> webpackFinal: (webpackConfig) => {
>   // This modifies the existing image rule to exclude `.svg` files
>   // since we handle those with `@svgr/webpack`.
>   const imageRule = webpackConfig.module.rules.find((rule) => {
>     if (typeof rule !== 'string' && rule.test instanceof RegExp) {
>       return rule.test.test('.svg')
>     }
>   })
>   if (typeof imageRule !== 'string') {
>     imageRule.exclude = /\.svg$/
>   }
> 
>   webpackConfig.module.rules.push({
>     test: /\.svg$/,
>     use: ['@svgr/webpack'],
>   })
> 
>   return webpackConfig
> },
> ```

Can you elaborate on your solution?

I'm trying the same with Nextjs 13 and storybook@7.0.0-rc.3

but neither your solution or the one in the `@storybook/nextjs` works for me.

if I attempt to import an SVG as a ReactComponent it is `undefined` and storybook throws an error.

**Comment by renanvalentin** [comment]
This did the trick for me:

```
    const fileLoaderRule = config.module.rules.find(rule =>
      rule.test?.test('.svg'),
    );
    fileLoaderRule.exclude = /\.svg$/;
```

Thanks a lot @lynndylanhurley

**Comment by xdata-denis** [comment]
In nx.dev monorepo for NextJS app fix was adding `"url-loader"`:
```
const imageRule = config.module.rules.find((rule) =>
      rule.test?.test(".svg")
);
imageRule.exclude = /\.svg$/;
config.module.rules.push({
      test: /\.svg$/,
      use: ["@svgr/webpack", "url-loader"],
});
```

**Comment by denissamoilov** [comment]
In nx.dev monorepo for NextJS app fix was adding `"url-loader"`:
```
const imageRule = config.module.rules.find((rule) =>
      rule.test?.test(".svg")
);
imageRule.exclude = /\.svg$/;
config.module.rules.push({
      test: /\.svg$/,
      use: ["@svgr/webpack", "url-loader"],
});
```

**Comment by diegorochawebdg** [comment]
> In nx.dev monorepo for NextJS app fix was adding `"url-loader"`:
> 
> ```
> webpackFinal: async (config) => {
>   const imageRule = config.module.rules.find((rule) =>
>       rule.test?.test(".svg")
>   );
>   imageRule.exclude = /\.svg$/;
>   config.module.rules.push({
>       test: /\.svg$/,
>       use: ["@svgr/webpack", "url-loader"],
>   });
> }
> ```

It worked! 
Thank you so much!

**Comment by Sebash93** [comment]
I had to do some workarounds for Typescript to stop complaining.

Here is how i was able to make it just in case its useful for anyone.

First i had to import RuleSetRule to cast the rules variable:

`import { RuleSetRule } from 'webpack';`

And here is the webpackFinal:
 ```
webpackFinal: async (config) => {
      const rules = config?.module?.rules as RuleSetRule[];
      const imageRule = rules.find(
        (rule) => rule?.test instanceof RegExp && rule.test.test('.svg'),
      );
      if (imageRule) {
        imageRule.exclude = /\.svg$/;
      }
      rules.push({
        test: /\.svg$/,
        use: ['@svgr/webpack'],
      });
      return config;
    },
```

**Comment by Mrowa96** [comment]
Hmm, for me examples above didn't work because next's config for storybook has two rules for `.svg` files. One for styles issuer and other for any other issuer.

Here is how my storybook web pack config looked by default:
<img width="916" alt="Screenshot 2023-09-01 at 11 21 34" src="https://github.com/storybookjs/storybook/assets/13927412/ca940683-7b32-479b-8cbf-60a28a918026">

And my code which fixed it. it supports Typescript.
```ts
function setupSVGR(config: Configuration) {
  // https://github.com/storybookjs/storybook/issues/18557
  const rules = config?.module?.rules;

  if (!Array.isArray(rules)) {
    return config;
  }

  let fileLoaderRule = rules.find(rule => {
    if (rule && typeof rule === 'object' && 'test' in rule && rule?.test instanceof RegExp && rule.test.test('.svg')) {
      return true;
    }

    return false;
  });

  if (Array.isArray(fileLoaderRule) && fileLoaderRule.length > 1) {
    fileLoaderRule = fileLoaderRule.at(0);
  }

  if (!fileLoaderRule || typeof fileLoaderRule !== 'object') {
    return config;
  }

  rules.push({
    test: /\.svg$/i,
    issuer: fileLoaderRule.issuer,
    use: ['@svgr/webpack'],
  });

  if (fileLoaderRule) {
    fileLoaderRule.exclude = /\.svg$/;
  }

  return config;
}
```

**Comment by nascjoao** [comment]
> I had to do some workarounds for Typescript to stop complaining.
> 
> Here is how i was able to make it just in case its useful for anyone.
> 
> First i had to import RuleSetRule to cast the rules variable:
> 
> `import { RuleSetRule } from 'webpack';`
> 
> And here is the webpackFinal:
> 
> ```
> webpackFinal: async (config) => {
>      const rules = config?.module?.rules as RuleSetRule[];
>      const imageRule = rules.find(
>        (rule) => rule?.test instanceof RegExp && rule.test.test('.svg'),
>      );
>      if (imageRule) {
>        imageRule.exclude = /\.svg$/;
>      }
>      rules.push({
>        test: /\.svg$/,
>        use: ['@svgr/webpack'],
>      });
>      return config;
>    },
> ```

Saved me! Thanks!

**Comment by andpigge** [comment]
> I was able to make it work with:
> 
> * `"storybook": "^7.0.0-beta.54"`
> * `"@svgr/webpack": "^6.5.1"`
> 
> following the `storybook-addon-next`’s [Custom Webpack Config](https://github.com/RyanClementsHax/storybook-addon-next/blob/06480c7de9424296b8ffdfa5df5ecf54f378213a/README.md#custom-webpack-config) section. I’ve just added some checks so the TS is happy:
> 
> ```tsx
> webpackFinal: (webpackConfig) => {
>   // This modifies the existing image rule to exclude `.svg` files
>   // since we handle those with `@svgr/webpack`.
>   const imageRule = webpackConfig.module.rules.find((rule) => {
>     if (typeof rule !== 'string' && rule.test instanceof RegExp) {
>       return rule.test.test('.svg')
>     }
>   })
>   if (typeof imageRule !== 'string') {
>     imageRule.exclude = /\.svg$/
>   }
> 
>   webpackConfig.module.rules.push({
>     test: /\.svg$/,
>     use: ['@svgr/webpack'],
>   })
> 
>   return webpackConfig
> },
> ```

Спасибо. Единственный код который у меня работал с новой версией storybook.

**Comment by ChellappanRajan** [comment]
I'm migrating from Storybook 6 to Storybook 7 and encountering an "additional loader needed" error. This configuration worked fine in Storybook 6. Has anyone else faced this issue?

**Comment by destinyamba625** [comment]
> I was able to make it work with:
> 
> * `"storybook": "^7.0.0-beta.54"`
> * `"@svgr/webpack": "^6.5.1"`
> 
> following the `storybook-addon-next`’s [Custom Webpack Config](https://github.com/RyanClementsHax/storybook-addon-next/blob/06480c7de9424296b8ffdfa5df5ecf54f378213a/README.md#custom-webpack-config) section. I’ve just added some checks so the TS is happy:
> 
> ```tsx
> webpackFinal: (webpackConfig) => {
>   // This modifies the existing image rule to exclude `.svg` files
>   // since we handle those with `@svgr/webpack`.
>   const imageRule = webpackConfig.module.rules.find((rule) => {
>     if (typeof rule !== 'string' && rule.test instanceof RegExp) {
>       return rule.test.test('.svg')
>     }
>   })
>   if (typeof imageRule !== 'string') {
>     imageRule.exclude = /\.svg$/
>   }
> 
>   webpackConfig.module.rules.push({
>     test: /\.svg$/,
>     use: ['@svgr/webpack'],
>   })
> 
>   return webpackConfig
> },
> ```

You are a super star

**Comment by destinyamba625** [comment]
> this worked for my `main.ts`
> 
> ```
> import type { StorybookConfig } from '@storybook/nextjs';
> 
> 
> const config: StorybookConfig = {
>   stories: [
>     '../components/**/*.stories.@(js|jsx|ts|tsx)',
>     '../components/**/*.stories.mdx',
>   ],
>   addons: [
>     '@storybook/addon-links',
>     '@storybook/addon-essentials',
>     '@storybook/addon-interactions',
>   ],
>   framework: {
>     name: '@storybook/nextjs',
>     options: {},
>   },
>   docs: {
>     autodocs: 'tag',
>   },
>   staticDirs: [{ from: '../public', to: '/public' }],
>   core: {
>     builder: '@storybook/builder-webpack5',
>   },
>   webpackFinal: async config => {
>     const imageRule = config.module?.rules?.find(rule => {
>       const test = (rule as { test: RegExp }).test
> 
>       if (!test) {
>         return false
>       }
> 
>       return test.test('.svg')
>     }) as { [key: string]: any }
> 
>     imageRule.exclude = /\.svg$/
> 
>     config.module?.rules?.push({
>       test: /\.svg$/,
>       use: ['@svgr/webpack']
>     })
> 
>     return config
>   }
> 
> };
> export default config;
> ```

You are a super star for this. It works for me

**Comment by artemis-prime** [comment]
@ChellappanRajan : I would suggest filing a separate issue, since it's a different version, it may well be unrelated rather that a regression.  My 2c

**Comment by adityaa72** [comment]
None of the above solutions will work after migrating to storybook@8.1.1

this worked for me
``` ts
 webpackFinal: async (config) => {
    config.module?.rules?.forEach((rule) => {
      if (
        rule &&
        typeof rule === "object" &&
        rule.test instanceof RegExp &&
        rule.test.test(".svg")
      ) {
        rule.exclude = /\.svg$/;
      }
    });
    config.module?.rules?.push({
      test: /\.svg$/,
      use: ["@svgr/webpack"],
    });
    return config;
  }
```

**Comment by sagarscript** [comment]
### Scenario
I'm using `NextJS 14.2.4` + `React 18.3.1` `@svgr/webpack 8.1.0`, and had the same problem described and the solution(s) proposed in this thread only helped with a part of my issue.

### Current Solution Proposed
The solutions proposed only supports the import of the svg as a react component i.e:
```
import Icon from "./assets/some-icon.svg"

const Component = () => {
  return (<Icon />)
}
```
### Issue
but not the svg as a url with the `?url` suffix i.e:
```
import iconUrl from "./assets/some-icon.svg?url"

const Component = () => {
  return (<img src{iconUrl} />)
}
```

### Investigation
Looking at the [SVGR docs](https://react-svgr.com/docs/next/#usage) - your `next.config.js` should look something like this:
```
module.exports = {
  webpack(config) {
    // Grab the existing rule that handles SVG imports
    const fileLoaderRule = config.module.rules.find((rule) =>
      rule.test?.test?.('.svg'),
    )

    config.module.rules.push(
      // Reapply the existing rule, but only for svg imports ending in ?url
      {
        ...fileLoaderRule,
        test: /\.svg$/i,
        resourceQuery: /url/, // *.svg?url
      },
      // Convert all other *.svg imports to React components
      {
        test: /\.svg$/i,
        issuer: fileLoaderRule.issuer,
        resourceQuery: { not: [...fileLoaderRule.resourceQuery.not, /url/] }, // exclude if *.svg?url
        use: ['@svgr/webpack'],
      },
    )

    // Modify the file loader rule to ignore *.svg, since we have it handled now.
    fileLoaderRule.exclude = /\.svg$/i

    return config
  },

  // ...other config
}
```

### Solution
With that in mind I modified the suggestions with the additional consideration for the url `?url` - my storybook `main.ts` now looks like this and it works a treat!
```
import type { StorybookConfig } from "@storybook/nextjs"

const config: StorybookConfig = {
  ...
  webpackFinal: async (config) => {
    // Grab the existing rule that handles SVG imports
    const fileLoaderRule = config.module?.rules?.find((rule) =>
      (rule as { test?: RegExp })?.test?.test(".svg")
    ) as { [key: string]: any }

    config.module?.rules?.push(
      // Reapply the existing rule, but only for svg imports ending in ?url
      {
        ...fileLoaderRule,
        test: /\.svg$/i,
        resourceQuery: /url/ // *.svg?url
      },
      // Convert all other *.svg imports to React components
      {
        test: /\.svg$/i,
        issuer: fileLoaderRule.issuer,
        resourceQuery: {
          not: [...(fileLoaderRule?.resourceQuery?.not || []), /url/]
        }, // exclude if *.svg?url
        use: ["@svgr/webpack"]
      }
    )
    // Modify the file loader rule to ignore *.svg, since we have it handled now.
    fileLoaderRule.exclude = /\.svg$/i

    return config
  }
}
export default config

```

**Comment by arudenkoofficial** [comment]
> In nx.dev monorepo for NextJS app fix was adding `"url-loader"`:
> 
> ```
> webpackFinal: async (config) => {
>   const imageRule = config.module.rules.find((rule) =>
>       rule.test?.test(".svg")
>   );
>   imageRule.exclude = /\.svg$/;
>   config.module.rules.push({
>       test: /\.svg$/,
>       use: ["@svgr/webpack", "url-loader"],
>   });
> }
> ```

Worked for me perfectly!

**Comment by allicanseenow** [comment]
Wonder if there is a similar solution for next-images?

**Comment by ahmedhrayyan** [comment]
Any case anyone looking for how to use some SVG as an asset (url) and other SVG as a React component like explained [here](https://react-svgr.com/docs/webpack/#use-svgr-and-asset-svg-in-the-same-project). Here what is made the trick for me
    import type { StorybookConfig } from "@storybook/nextjs"
    
    const config: StorybookConfig = {
      
      // ...other config
    
    
      webpackFinal: async (config) => {
          const fileLoaderRule = config.module?.rules?.find((rule) => {
          if (rule instanceof Object && "test" in rule) {
            return rule.test?.toString().includes("svg");
          }
        }) as Record<string, any>;
    
        config.module?.rules?.push(
          // Reapply the existing rule, but only for svg imports ending in ?url
          {
            ...fileLoaderRule,
            test: /\.svg$/i,
            resourceQuery: /url/, // *.svg?url
          },
          // Convert all other *.svg imports to React components
          {
            test: /\.svg$/i,
            issuer: fileLoaderRule.issuer,
            resourceQuery: { not: [/url/] }, // exclude if *.svg?url
            use: ["@svgr/webpack"],
          },
        );
    
        // Modify the file loader rule to ignore *.svg, since we have it handled now.
        fileLoaderRule.exclude = /\.svg$/i;
    
        return config;
      }
    }

**Comment by f0rmat1k** [comment]
I've made another one (storybook 9 + svgr) https://gist.github.com/f0rmat1k/dc24e7a4d76743bd58146a2175b30835
