### ISSUE TITLE
Composition: How to avoid error/deprecation messages?

### ISSUE THREAD

**Issue by prewk** [storybookjs/storybook#18581]
I build 19 storybooks in my Angular project (I'm using `nx`), then I have a special `.storybook/` for building a composition of those storybooks. I deploy everything to a static s3 bucket with a git-sha in the url. So far so good.

When I perform the build, however, I get this warning:

```
WARN Your Storybook startup uses a solution that will not be supported in version 7.0.
WARN You must use angular builder to have an explicit configuration on the project used in angular.json
```

It's a bit unclear to me how to involve angular at all for the composition build? It's just a simple composition that points out absolute urls via `refs`?

Also:

```
ERR! => Could not find angular workspace config (angular.json) on this path "/omitted/path/to/project"
info => Fail to load angular-cli config. Using base config
```

I guess it might be confused by the `nx`ed angular.json (The file is there, but every project is monorepoed so it references other project.json files in subdirs instead of keeping all the configuration there). But again, can I make it ignore Angular, it's not really relevant to the composition build?

It builds successfully.

**My composiiton main.js**

`STORYBOOK_PROJECTS` will be `"foo bar baz"` with built storybook directories. `CI_COMMIT_SHA` is the git commit sha.

```
const _ = require('lodash');

module.exports = {
  stories: ['./docs/*.stories.ts'],
  core: {
    builder: 'webpack5',
  },
  refs: (process.env.STORYBOOK_PROJECTS || '').split(' ').reduce(
    (acc, name) => ({
      ...acc,
      [name]: {
        title: _.startCase(name),
        url: `/${process.env.CI_COMMIT_SHA || ''}/${name}`,
      },
    }),
    {}
  ),
};
```

**System**

```
  System:
    OS: macOS 12.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 16.15.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.11.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 102.0.5005.115
    Safari: 15.5
  npmPackages:
    @storybook/addon-essentials: ~6.5.9 => 6.5.9
    @storybook/addon-interactions: ^6.5.9 => 6.5.9
    @storybook/angular: ~6.5.9 => 6.5.9
    @storybook/builder-webpack5: ~6.5.9 => 6.5.9
    @storybook/core-server: ~6.5.9 => 6.5.9
    @storybook/jest: ^0.0.10 => 0.0.10
    @storybook/manager-webpack5: ~6.5.9 => 6.5.9
    @storybook/test-runner: ^0.2.0 => 0.2.0
    @storybook/testing-library: ^0.0.13 => 0.0.13
```

**Comment by mandarini** [comment]
I saw [the same warning](https://app.warp.dev/block/QEkHpHc7jHw4wTiUWsUryA)
```
WARN Your Storybook startup uses a solution that will not be supported in version 7.0.
WARN You must use angular builder to have an explicit configuration on the project used in angular.json
```

when running Storybook with `yarn storybook` in an Angular app (just Angular, no Nx). Here's [the repro repo](https://github.com/mandarini/pure-angular-storybook). Clone, `yarn` to install, and then `yarn storybook` to start Storybook.

To reproduce from scratch:
1. `ng new my-app`
2. `cd my-app`
3. `npx sb init`
4. Here you will get a warning that `ajv-formats` so install `ajv-formats`
5. `yarn storybook`

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
