### ISSUE TITLE
Alignment of text and icon on sidebar is changed when font of storybook is changed 

### ISSUE THREAD

**Issue by saravanamani1999** [storybookjs/storybook#18607]
Have changed the font to open sans in `theme.js` and when doing so, the alignment of the text to the icons on the sidebar gets affected as shown in the image

<img width="101" alt="alignment_off_center" src="https://user-images.githubusercontent.com/66838856/176655360-5bd5d86c-fc60-4d56-85cf-ebf38838981f.png">

**Comment by ndelangen** [comment]
@saravanamani1999 is this still an issue in 7.0 beta?

If you would you be interested in opening a PR to address this?

**Comment by iamkelv** [comment]
@ndelangen is the issue still open? I will like to work on it

**Comment by ndelangen** [comment]
It might be @iamkelv ! I'm not sure.

If you'd do an investigation, create a reproduction? 🙏

**Comment by himanshu1221** [comment]
Can I work on this issue?

**Comment by ndelangen** [comment]
@himanshu1221 yea please! That would be very welcome indeed!

**Comment by ParbhatKataria1** [comment]
Is this issue resolved? If not, I would love to fix it.

**Comment by ndelangen** [comment]
@ParbhatKataria1 I'm not sure, I just updated this PR: https://github.com/storybookjs/storybook/pull/22221

Would you be interested in reviewing it and testing it for yourself?
