### ISSUE TITLE
Storybook v7 - Error: Sorry, for now, you can not do this, please use a framework such as @storybook/react-webpack5

### ISSUE THREAD

**Issue by humarkx** [storybookjs/storybook#18601]
When running `npx storybook@7.0.0-alpha.7 init`
Or any other 7 alpha release I get the following error:
`Error: Sorry, for now, you can not do this, please use a framework such as @storybook/react-webpack5`

A brand new project Vite with react ts template

![image](https://user-images.githubusercontent.com/13049940/176437392-65780be9-97bd-4c08-b8a6-3989efe45e41.png)

**Comment by unicornware** [comment]
i don't think vite is supported just yet - it doesn't have a [framework][1]. storybook 7 also includes several breaking changes that are not supported by `@storybook/builder-vite` (as of `v0.2.0-beta.2`). 

esm support received some major updates, so i was hoping to use `patch-package` to workaround some of the kinks, but after hitting a wall and checking out the wip on the [`framework-vite`][2] branch, i'm thinking we have to submit some PRs haha, or wait for a release.

@shilman or @IanVS  can you confirm?

[1]: https://github.com/storybookjs/storybook/blob/v7.0.0-alpha.12/MIGRATION.md#framework-field-mandatory
[2]: https://github.com/storybookjs/storybook/tree/future/framework-vite

**Comment by IanVS** [comment]
That's right, although I hear it's coming very soon!

**Comment by joshwooding** [comment]
@humarkx Do you still encounter this? Storybook 7 now has vite support.

**Comment by himyjan** [comment]
yes
<img width="674" alt="image" src="https://user-images.githubusercontent.com/51815522/194467259-1e8497ad-a5e7-4fcd-a7ce-db1cbd232dfe.png">

**Comment by himyjan** [comment]
works now
`npm create vite@latest`
typescript
react

`npx sb@7.0.0-alpha.35 init` work

`npx sb@7.0.0-alpha.35 init --builder @storybook/builder-vite` not work

<img width="674" alt="image" src="https://user-images.githubusercontent.com/51815522/194467411-eda03caf-9d79-4b42-a71c-9b416e1525bd.png">

**Comment by IanVS** [comment]
The flag is `--builder=vite`, which should work hopefully.

**Comment by eliabyteixeira** [comment]
with the --builder=vite flag it worked for me! Thanks!

**Comment by eliabyteixeira** [comment]
> The flag is `--builder=vite`, which should work hopefully. We should throw an error on bad values...

with the --builder=vite flag it worked for me! Thanks!
