### ISSUE TITLE
addon-storysource copy line numbers in chrome

### ISSUE THREAD

**Issue by iriswang233** [storybookjs/storybook#18629]
**Describe the bug**
When copying code from story tab in chrome and paste it in vs code, line numbers will be pasted too. This is not user friendly. However, when copying code from story tab in firefox and paste it in vs code, line numbers are not there. This should be the correct behaviour.
**To Reproduce**
1. open https://backstage.io/storybook/?path=/story/layout-item-cards--styling in chrome
2. open story tab
3. copy several lines code
4. paste in vs code file => **Line numbers are pasted**
<img width="859" alt="image" src="https://user-images.githubusercontent.com/49713904/177242302-ffb0a47c-784a-494e-88ec-dc724b6fee0a.png">

**System**
chrome
**Additional context**
no

**Comment by shilman** [comment]
ZOMG!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-alpha.24 containing PR #18725 that references this issue. Upgrade today to the `@future` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
