### ISSUE TITLE
Yarn PnP -  yarn storybook says : error: unknown option '-p' / Invalid command: dev. 

### ISSUE THREAD

**Issue by fivaz** [storybookjs/storybook#18625]
**Describe the bug**

When running "yarn storybook" with 7.0.0-alpha.10 in Yarn PnP mode it says:
`
error: unknown option '-p'
` 
if I remove all the flags of 
`npx storybook dev -p 6006 -s public`
it says:
`
 Invalid command: dev. 
 `

**To Reproduce**
Please create a reproduction by running `npx sb@next repro` and following the instructions. Read our [documentation](https://storybook.js.org/docs/react/contribute/how-to-reproduce) to learn more about creating reproductions.
Paste your repository and deployed reproduction here. We prioritize issues with reproductions over those without.

https://github.com/fivaz/react-storybook-wepback

**System**
Please paste the results of `npx sb@next info` here.

System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i5-12600K
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.2.1 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.12.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.160.0), Chromium (103.0.1264.37)

**Additional context**

**Comment by ld210** [comment]
I have a similar error, with @storybook/angular, using Yarn 3.2.1 in PnP mode.
The command `compodoc -p .storybook/tsconfig.json -d /Documents/myApp -e json` throws this error :  `error: unknown option '-e'`

**Comment by ld210** [comment]
Ok, so, for me Compodoc is indeed the culprit.
I replaced the script `"docs:json": "yarn dlx compodoc -p ./tsconfig.json -e json -d . --disableRoutesGraph"` in package.json by
`"docs:json": "yarn dlx @compodoc/compodoc -p ./tsconfig.doc.json -e json -d . --disableRoutesGraph"
And it works like it should. However, using the angular builder still runs the outdated command.

**Comment by ld210** [comment]
@fivaz You rollbacked to a previous version ? If so, wich version did you rollbacked to ? 6.5.9 is the current one

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
