### ISSUE TITLE
lib/core-common and lib/core-server both rely on webpack 4

### ISSUE THREAD

**Issue by jordanmbell** [storybookjs/storybook#18643]
**Describe the bug**
The `@storybook/core-common` and `@storybook/core-server` packages both have a dependency: `"webpack": "4"`. This worked with webpack 4 everywhere, but now that storybook supports webpack 5 this dependency should probably be changed to `"*"`.

**Comment by jordanmbell** [comment]
Additionally `@storybook/core-server` should probably be changed to depend on `@storybook/builder-webpack5` and `@storybook/manager-webpack5` rather than the version 4s

**Comment by JordanAtBridgit** [comment]
Apparently, this would be a breaking change and is slated to be done in [version 7](https://github.com/storybookjs/storybook/issues/17436#issuecomment-1032182293)

**Comment by jordanmbell** [comment]
Somehow missed this issue while searching, I'll close as duplicate
