### ISSUE TITLE
CI pipeline passes even with fatal build-storybook error

### ISSUE THREAD

**Issue by Ray2126** [storybookjs/storybook#18652]
**Describe the bug**
Github workflow passes even though the project is missing Storybook configuration files.

Note the lines:
```
ERR!  Error: No configuration files have been found in your configDir (/home/runner/work/storybook-ci-build-failure-test/storybook-ci-build-failure-test/.storybook).
ERR! Storybook needs either a "main" or "config" file.
```

<img width="1650" alt="image" src="https://user-images.githubusercontent.com/50732795/177704491-e4759f38-554b-431c-ab44-ab6a64e8f67c.png">

**To Reproduce**
Reproduction repo: https://github.com/Ray2126/storybook-ci-build-failure-test
Link to the pipeline: https://github.com/Ray2126/storybook-ci-build-failure-test/runs/7227895689?check_suite_focus=true

**System**
```
System:
    OS: macOS 12.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 14.19.0 - ~/.nvm/versions/node/v14.19.0/bin/node
    Yarn: 3.2.1 - /usr/local/bin/yarn
    npm: 6.14.16 - ~/.nvm/versions/node/v14.19.0/bin/npm
  Browsers:
    Chrome: 103.0.5060.114
    Firefox: 101.0
    Safari: 15.5
  npmPackages:
    @storybook/addon-actions: ^6.5.9 => 6.5.9 
    @storybook/addon-docs: ^6.5.9 => 6.5.9 
    @storybook/addon-essentials: ^6.5.9 => 6.5.9 
    @storybook/addon-interactions: ^6.5.9 => 6.5.9 
    @storybook/addon-links: ^6.5.9 => 6.5.9 
    @storybook/builder-webpack4: ^6.5.9 => 6.5.9 
    @storybook/manager-webpack4: ^6.5.9 => 6.5.9 
    @storybook/testing-library: ^0.0.13 => 0.0.13 
    @storybook/vue: ^6.5.9 => 6.5.9
```

**Additional context**
The issue is not isolated for Github Workflows. Our team is seeing the same behaviour in Bitbucket pipelines.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
