### ISSUE TITLE
Inertia Links not rendering

### ISSUE THREAD

**Issue by EBAdev** [storybookjs/storybook#18661]
**Describe the bug**
Hi im trying out storybook, loving it so far!

My issue is that im implementing it in my Laravel app, with inertia. Im trying to render a navigation link component, which uses the inertia links wrapper: https://inertiajs.com/links 

The component is registered in storybook, but does not render, because the of the inertia-link replacing the html in the code. Is there a way to import the inertia link in storybook, making rendering possible?

If I manually change the tag in the html via inspection to an anchor tag (<a>), the component renders. Which tells me that it is, indeed the inertia-link, giving me a headache.

I have tried for some time now, I also tried searching for som time, but I simply can't find an answer :( 

Will keep you updated if I make new discoveries. 

**The code of the vue component:**

```<template>
  <Link
    class="font-medium uppercase hover:text-blue-600 dark:hover:text-blue-400"
    :class="{
      ' text-blue-500 hover:text-blue-500 dark:hover:text-blue-500': active,
    }"
  >
    <slot />
  </Link>
</template>

<script>
export default {
  props: {
    active: Boolean,
  },
}
</script>
```
**The story:** 
```
import NavLink from '../resources/js/components/ui/AppNavLink.vue'
import { Link } from '@inertiajs/inertia-vue3'

//👇 This default export determines where your story goes in the story list
export default {
  /* 👇 The title prop is optional.
   * See https://storybook.js.org/docs/vue/configure/overview#configure-story-loading
   * to learn how to generate automatic titles
   */
  title: 'Design System/Navbar link',
  component: NavLink,
  subcomponents: { Link },
}

//👇 We create a “template” of how args map to rendering
const Template = (args) => ({
  components: { NavLink, Link },
  setup() {
    //👇 The args will now be passed down to the template
    return { args }
  },
  template: ' <NavLink href=args.href > Posts </NavLink>',
})

export const Default = Template.bind({})

Default.args = {
  /* 👇 The args you need here will depend on your component */
  href: '/',
}
```
**main.js:** 
```
const path = require('path')
const tailwindcss = require('../tailwind.config')
module.exports = {
  stories: [
    '../stories/**/*.stories.mdx',
    '../stories/**/*.stories.@(js|jsx|ts|tsx)',
  ],
  addons: [
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    '@storybook/addon-interactions',
  ],
  staticDirs: ['../public', '../node_modules'],
  framework: '@storybook/vue3',
  core: {
    builder: '@storybook/builder-webpack5',
  },
  webpackFinal: (config) => {
    config.module.rules.push({
      test: /\.css$/,
      use: [
        {
          loader: 'postcss-loader',
          options: {
            postcssOptions: {
              implementation: 'postcss',
              plugins: {
                tailwindcss,
              },
            },
          },
        },
      ],
      include: path.resolve(__dirname, '../'),
    })
    config.resolve = {
      ...config.resolve,
      alias: {
        ...config.resolve?.alias,
        '@': '../resources/js',
      },
    }
    return config
  },
}

```

**preview.js:** 
```
import '../resources/css/app.css'

export const parameters = {
  actions: { argTypesRegex: '^on[A-Z].*' },
  controls: {
    matchers: {
      color: /(background|color)$/i,
      date: /Date$/,
    },
  },
}

```

**To Reproduce**
Add vue composent with and inertia.js link to storybook

**System**
Environment Info:

  System:
    OS: macOS 12.4
    CPU: (8) x64 Apple M1
  Binaries:
    Node: 16.16.0 - /usr/local/bin/node
    Yarn: 3.2.1 - /opt/homebrew/bin/yarn
    npm: 8.11.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 91.0.4472.77
    Safari: 15.5
  npmPackages:
    @storybook/addon-actions: ^6.5.9 => 6.5.9 
    @storybook/addon-essentials: ^6.5.9 => 6.5.9 
    @storybook/addon-interactions: ^6.5.9 => 6.5.9 
    @storybook/addon-links: ^6.5.9 => 6.5.9 
    @storybook/builder-webpack5: ^6.5.9 => 6.5.9 
    @storybook/manager-webpack5: ^6.5.9 => 6.5.9 
    @storybook/testing-library: ^0.0.13 => 0.0.13 
    @storybook/vue3: ^6.5.9 => 6.5.9 

**Additional context**
The tech stack for the whole SPA is:
Vue 3
TailwindCSS
Inertia.js
Laravel
Storybook
Webpack

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
