### ISSUE TITLE
Binding a keyboard shortcut for Remount component button in toolbar

### ISSUE THREAD

**Issue by akilansengottaiyan** [storybookjs/storybook#18669]
**Is your feature request related to a problem? Please describe**
Having a button for Remounting a component is super useful. But for such a super useful feature, having no keyboard shortcut bound to it makes the developer life difficult.

**Describe the solution you'd like**
As we have shortcuts for different actions in toolbar, we could also assign a shortcut to it possibly (alt + R)

**Describe alternatives you've considered**
None.

**Are you able to assist to bring the feature to reality?**
yes, I can.

**Additional context**
Button in the toolbar titled **_Remount component_**
Attaching a screenshot for more clarity.
<img width="738" alt="Screenshot 2022-07-09 at 3 26 15 PM" src="https://user-images.githubusercontent.com/61273298/178100935-141bd1eb-c5c1-428d-b84f-b9d81902e46f.png">
I am talking about the button highlighted in the screenshot

**Comment by akilansengottaiyan** [comment]
@ndelangen @shilman Kindly take a look and let me know if I could proceed to raise a PR.

**Comment by akilansengottaiyan** [comment]
@ndelangen @shilman In case if you missed it.

**Comment by MichaelAllenWarner** [comment]
Yes, a keyboard shortcut for remount would be great!

**Comment by ndelangen** [comment]
I marked this as "good first issue". If someone would like to work on this, I'd be happy to help get them started!

**Comment by Roel-t** [comment]
I would like to give it a shot! Looked over through a bit at how other shortcuts are done, but if I get block or need your help I will reach out to you through discord.

**Comment by ndelangen** [comment]
Awesome! thanks!

**Comment by shilman** [comment]
Yee-haw!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.1.0-alpha.2 containing PR #21401 that references this issue. Upgrade today to the `@future` NPM tag to try it out!

```
npx sb@next upgrade --tag future
```

**Comment by shilman** [comment]
Ooh-la-la!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.7 containing PR #21401 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb@latest upgrade
```
