### ISSUE TITLE
Global SCSS Variables are not found using Vite and generate build error

### ISSUE THREAD

**Issue by hexagon06** [storybookjs/storybook#18670]
**Describe the bug**
Storybook does not load the scss variables using when using Vite. 
The Vue3 project requires the variables to be loaded throught the ` css.preprocessorOptions.scss.aditionalData` in the ` vite.config.ts`. This works fine when running the project (yarn dev), but Storybook (yarn storybook) seems to ignore that configuration as I get the same error when running the project without that configuration option. 
![image](https://user-images.githubusercontent.com/9200092/178100024-128ab89c-a4b9-40d7-ad45-5f5609bd0ce4.png)

**To Reproduce**
All is wrapped up in [this ](https://github.com/hexagon06/vue3-boilerplate-library/tree/storybook-scss) branch:
I tried publishing to Chromatic, but since this generates a build error it is impossible to create an artifact to publish.

Note: this has not been done with the `npx sb@next` command, but it is the minimal required effort to reproduce. I am making a boilerplate library after all. Running the sb@next command I saw that it was using the vue cli, which is using webpack configuration, which is a different situation than the bug anyways. This is a boilerplate/template project, so next to some configuration there is next to no content included.

I did try to reproduce using the command, and that attempt can be found [here](https://github.com/hexagon06/vue3-boilerplate-library/tree/storybook-scss-repro) (chose Vue3 as framework with vue3 as template and directory vue3). Is it just me, or does that not add storybook anywhere, just vue3 created with vue-cli?

- It is a vue 3 library project
- Created with Vite
- using typescript
- added storybook
- added (dart) sass
- added some css and scss files
- tried to use a variable from a global scss in a vue component
- starting storybook using `yarn storybook` shows the page, but with the error shown in the image above on every page/story.

**If it is still usefull to do the `sb@next repro` command in a different way, please let me know, but it seems redundant with this configuration and previous results.** 

**System**
**Environment Info:**

  System:
    OS: Windows 10 10.0.19043
    CPU: (4) x64 Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
  Binaries:
    Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.2.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.3.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (103.0.1264.49)

note that I am using nvm for node management

**Additional context**
I eventually I intend to make this a library project, inlcuding rollup publications, testing etc.

**Comment by tarsusi** [comment]
Hello @hexagon06,

I had the same issue yesterday and after searching any solution I came up with this solution. You can override or extend configurations on your `.storybook/main.js` like this:

```javascript
const path = require('path');
const {mergeConfig} = require('vite');

module.exports = {
  "stories": [
      "../src/**/*.stories.mdx",
      "../src/**/*.stories.@(js|jsx|ts|tsx)"
  ],
  "addons": [
      "@storybook/addon-links",
      "@storybook/addon-essentials",
      "@storybook/addon-interactions"
  ],
  "framework": "@storybook/vue3",
  "core": {
      "builder": "@storybook/builder-vite"
  },
  "features": {
      "storyStoreV7": true
  },
  async viteFinal(config) {
        return mergeConfig(config, {
            css: {
                postcss: null,
                preprocessorOptions: {
                    scss: {
                        additionalData: `
                            @import "${path.resolve(__dirname, '../src/styles/variables')}";
                        `,
                    },
                },
            },
        });
    },
}
```

I hope this can solve your problem.

**Comment by MatheusNascimentoti99** [comment]
Same problem here.

**Comment by hexagon06** [comment]
@tarsusi Thank you for taking the effort to reply. I tried your `viteFinal` override in the same way, and with the added file extension. Sadly I get the following error in both cases. The error seems to originate from `sass.dart.js`. The file path is correct and can be opened. Did you encounter this error and solve it perchance? (or have a clue as to how to resolve it)

![image](https://user-images.githubusercontent.com/9200092/180503544-c2621ce5-c664-49bc-a012-8dfb578a189d.png)

**Comment by MatheusNascimentoti99** [comment]
> Same problem here.

My problem was the wrong path for my variables.
Try something like this:
`css: {
        preprocessorOptions: {
          scss: { additionalData: `@import "../src/css/variables.scss";` },
        },
      },
`

**Comment by fabsval** [comment]
Some problem here... but the fix you mentionned partially resolved that issue, because now additionalData files are called on every components and not globally...

**Comment by IanVS** [comment]
In 7.0, Storybook uses your project's vite config automatically.  Can anyone confirm whether they are still having this problem with the latest 7.0 betas?

**Comment by shilman** [comment]
Closing this as fixed in 7.0 Please let me know if there's more to be done here!

**Comment by facundomdelp** [comment]
Hello. I'm configuring latest Storybook and I'm having issues for importing the scss variables directly to my **tsx components**.
I an older version of my Storybook configured with webpack, I used to have an `:export`, and after that I was able to import my object of colors this way (example): `style= {{ backgroundColor: Colors[main] }}`

Thanks!

**Comment by Walnussbaer** [comment]
> Thank you @tarsusi and @MatheusNascimentoti99. Both of your code combined resolved this issue for me. The way using the `path` library did not work for me and generated the error above. Using the vite configuration in the `vite.config.ts` only did not do the trick either.
> 
> So this is the final working code in `main.js`
> 
> ```js
> async viteFinal(config) {
>         return mergeConfig(config, {
>             css: {
>                 postcss: null,
>                 preprocessorOptions: {
>                     scss: {
>                       additionalData: `
>                         @import '../src/styles/variables.scss';
>                         @import '../src/styles/classes.scss';
>                       `
>                     },
>                 },
>             },
>         });
>     },
> ```
> 
> still requiring the configuration in the `vite.config.ts` too, to be able to build the code for library publish purposes:
> 
> ```ts
> css: {
>     preprocessorOptions: {
>       scss: {
>         additionalData: `
>           @import "./src/styles/variables.scss";
>           @import "./src/styles/classes.scss";
>         `,
>       },
>     },
>   },
> ```
> 
> I will keep this issue open for triage since I think there should be documentation for this kind of information.

Is it still necessary to do these imports when using scss? I am using Storybook 7.5.3 with Vite in a Vue 3.x project
