### ISSUE TITLE
Actions don't work with vue events

### ISSUE THREAD

**Issue by jojomatik** [storybookjs/storybook#18688]
**Describe the bug**
I'm not able to get a log output in the actions tab clicking my custom `RestartButtonComponent` which throws the `@restart` event. Doesn't seem to work with the default vuetify button as well.

**To Reproduce**

Link to repository. https://github.com/jojomatik/blockcluster/commit/e8f163bf96205dc9feb5d6ebdd2198b4092270ff

Link to storybook (`RestartButtonComponent`): https://62cab50a2ca3572c9947bcb6-xqadvzcelc.chromatic.com/?path=/story/components-restartbuttoncomponent--default 

**System**
Github Actions: [`ubuntu-latest`](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md)

**Additional context**
RestartButtonComponent.stories.ts
```RestartButtonComponent.stories.ts
import RestartButtonComponent from "@/components/buttons/RestartButtonComponent.vue";
import { ServerStatus } from "../../../common/components/server";
import prepareEnum from "../../../.storybook/enumPrepare";

export default {
  component: RestartButtonComponent,
  argTypes: {
    status: {
      control: "select",
      options: prepareEnum(ServerStatus),
    },
    restart: { action: "clicked" },
  },
};

export const Default = {
  args: {
    disabled: false,
    status: ServerStatus.Started,
  },
};

```

I thought that `restart: { action: "clicked" },` should already do the trick, but it doesn't? See also https://storybook.js.org/docs/vue/essentials/actions

I've also tried the solution from this issue but with no success https://github.com/storybookjs/storybook/discussions/11372

**Comment by jojomatik** [comment]
> Maybe something with my installation is just seriously wrong?

I've also noticed that the docs page has stopped working somewhere along my line of development, which would make this more likely. I'd like to recreate `package-lock.json` completely, but I even have trouble doing that as storybook doesn't work at all afterwards.

**Comment by jojomatik** [comment]
> > Maybe something with my installation is just seriously wrong?
> 
> I've also noticed that the docs page has stopped working somewhere along my line of development, which would make this more likely. I'd like to recreate `package-lock.json` completely, but I even have trouble doing that as storybook doesn't work at all afterwards.
> 
> I don't know why it is doing that but I've also noticed that `npm` install some dependencies of storybook not directly in `node_modules` but rather inside another dependency. I've completely recreated the lockfile and I still have multiple instances of `@storybook/api` for some reason. Maybe this is related?

Well, these problems have been fixed in https://github.com/jojomatik/blockcluster/pull/484, but the actions still don't work.

**Comment by moebiusmania** [comment]
@jojomatik just for double check, did you also added `'@storybook/addon-actions'` in the `addons` array in `.storybook/main.js` ?

**Comment by jojomatik** [comment]
Currently not explicitly, but I believe that `"@storybook/addon-essentials"` includes it? At least the action tab shows up.

Adding it does not seem to change anything either.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
