### ISSUE TITLE
Play function can run before global decorators have been fully executed

### ISSUE THREAD

**Issue by sballesteros** [storybookjs/storybook#18697]
**Describe the bug**

The [play function](https://storybook.js.org/docs/react/writing-stories/play-function) can run _before_ global decorators have been fully executed.
If a global decorator relies on an API forcing re-rendering (e.g.,`useAddonState`) this can result in the storybook canvas reflecting the _initial_ state of the story as opposed to the one obtained as a result of the `play` function.

**To Reproduce**

👉 See https://github.com/sballesteros/storybook-play-function-reproduction
Look at the `PlayFunctionBug` stories. Those stories use a simple counter as an example. The counter starts at 0 and clicking on the "increment" button increments the value.

- The `Step With Bug` story shows an example with the bug. Here the storybook canvas shows the initial story state ("step: 0") instead of the state resulting from having run the `play` function (the play function emulates a user click on the increment button so the storybook canvas should be "step: 1" and not "step: 0"). The bug is due to the fact that we added a global decorator relying on the `useAddonState` API in `preview.js`. So:
    - The `play` function work as expected
    - But at the end, the story re-renders (without re-running the play function) and so the Storybook canvas reflects the story's initial state
- The `Step With Workaround` story shows a workaround preventing the bug (delaying the play function execution until all the effects of the global decorator have been executed).

**System**
Please paste the results of `npx sb@next info` here.

```
  System:
    OS: macOS 11.6.7
    CPU: (8) x64 Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 3.2.1 - ~/.nvm/versions/node/v16.14.0/bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
  Browsers:
    Chrome: 103.0.5060.114
    Firefox: 101.0.1
    Safari: 15.5
  npmPackages:
    @storybook/addon-actions: ^6.5.9 => 6.5.9 
    @storybook/addon-docs: ^6.5.9 => 6.5.9 
    @storybook/addon-essentials: ^6.5.9 => 6.5.9 
    @storybook/addon-interactions: ^6.5.9 => 6.5.9 
    @storybook/addon-links: ^6.5.9 => 6.5.9 
    @storybook/builder-webpack4: ^6.5.9 => 6.5.9 
    @storybook/jest: ^0.0.10 => 0.0.10 
    @storybook/manager-webpack4: ^6.5.9 => 6.5.9 
    @storybook/preact: ^6.5.9 => 6.5.9 
    @storybook/testing-library: ^0.0.13 => 0.0.13 
```

**Additional context**

**Comment by sballesteros** [comment]
Thinking more I don't think that this is a bug per se and more smtg to be aware of.

**Comment by lworkman** [comment]
I don't know if this lines up with your issue @sballesteros, but I'm having an issue where a global decorator delays render until a `useEffect` hook is run, which causes the `play` function to look for elements that don't exist yet.

Is there a globally defined `play` function I can define which lets me add a delay to every story?

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
