### ISSUE TITLE
Module not found: Can't resolve '@storybook/addon-ondevice-actions/manager' in React Native 

### ISSUE THREAD

**Issue by jsflor** [storybookjs/storybook#18692]
**Describe the bug**
Getting module not found error when trying to run storybook in react native

```
./storybook/rn-addons.js:1
Module not found: Can't resolve '@storybook/addon-ondevice-actions/manager'
> 1 | import '@storybook/addon-ondevice-actions/manager';
  2 | import '@storybook/addon-ondevice-knobs/manager';
  3 |
./storybook/rn-addons.js:2
Module not found: Can't resolve '@storybook/addon-ondevice-knobs/manager'
  1 | import '@storybook/addon-ondevice-actions/manager';
> 2 | import '@storybook/addon-ondevice-knobs/manager';
  3 |
```

**To Reproduce**
Can't use repro command properly since there is no support of react native yet.
Follow the steps depicted in [Storybook get started](https://storybook.js.org/tutorials/intro-to-storybook/react-native/en/get-started/):

1. `expo init --template tabs@sdk-36 taskbox` (Create new empty expo project)

2. `cd taskbox`

3. `npx -p @storybook/cli sb init --type react_native` (Add storybook support)

4. `export {default} from './storybook';` (Export default from entrypoint of your app)

After setting up the project if you try to run storybook it will crash and you got the error depicted

**System**

System:
    OS: macOS 11.6.1
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
  Binaries:
    Node: 14.17.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 7.16.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 103.0.5060.114
    Firefox: 100.0
    Safari: 15.2
  npmPackages:
    @storybook/addon-actions: ^5.3 => 5.3.21 
    @storybook/addon-knobs: ^5.3 => 5.3.21 
    @storybook/addon-links: ^5.3 => 5.3.21 
    @storybook/addon-ondevice-actions: ^5.3.23 => 5.3.23 
    @storybook/addon-ondevice-knobs: ^5.3.25 => 5.3.25 
    @storybook/react-native: ^5.3.25 => 5.3.25 

**Additional context**
<img width="596" alt="Screenshot 2022-07-12 at 13 54 50" src="https://user-images.githubusercontent.com/50371169/178487111-6cf6eab3-fdd3-4edb-b4a7-5c1288f88e76.png">

**Comment by retyui** [comment]
Fix:

```diff
-import '@storybook/addon-ondevice-actions/manager';
-import '@storybook/addon-ondevice-knobs/manager';
+import '@storybook/addon-ondevice-actions/register';
+import '@storybook/addon-ondevice-knobs/register';
```

**Comment by jsflor** [comment]
@designorant I got it changing only the `./storybook/rn-addons.js` imports but checked the sources of `./storybook/addons.js` imports and they also should be updated:

```
import '@storybook/addon-actions/register';
import '@storybook/addon-links/register';
import '@storybook/addon-knobs/register';
```

Did you export StorybookUIRoot from the entry point of you app?

**Comment by designorant** [comment]
@jsflor Yes, thanks, I did. I see Storybook in iOS Simulator just fine, but the web version via `yarn storybook` doesn't pick up the stories at all. Apparently [this is a known issue](https://github.com/storybookjs/react-native/issues/55) but issues like this one makes me wonder whether Storybook in RN is a niche. Clearly there's quite a few things that just don't work.

Interestingly, when following [the tutorial](https://storybook.js.org/tutorials/intro-to-storybook/react-native/en/get-started/) via Expo, `yarn storybook` still doesn't load stories, the Expo Web View works fine, but the Expo iOS Sim doesn't. Bit of a mix and match experience!

**Comment by shilman** [comment]
Ermahgerd!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-alpha.16 containing PR #18693 that references this issue. Upgrade today to the `@future` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Zoinks!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.10-alpha.0 containing PR #18693 that references this issue. Upgrade today to the `@prerelease` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

**Comment by shilman** [comment]
Yippee!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.10 containing PR #18693 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```
