### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'collections') on fresh Storybook install

### ISSUE THREAD

**Issue by dcastil** [storybookjs/storybook#18694]
**Describe the bug**

I installed Storybook in a fresh Vite project and Storybook seems to work in development mode but the endpoint `/runtime-error` is called every second which then returns a 404, cluttering browser devtools.

**To Reproduce**

```sh
# Create empty ts-react project `my-app`
yarn create vite
# Navigate to project directory
cd my-app
# Initialize Storybook
npx storybook init
# Run Storybook dev server
yarn storybook
```

The result (I ran on port 6012 instead of 6006 to not pollute scope of my actual dev server):

![Screenshot 2022-07-12 at 16 20 32](https://user-images.githubusercontent.com/31006608/178512791-688e34c0-650b-46ee-a217-c9a2c6e75b90.png)

![Screenshot 2022-07-12 at 16 20 42](https://user-images.githubusercontent.com/31006608/178512808-b10ba807-309f-4b47-acfd-9a93eeb02a5a.png)

When I outcomment the Vite-specific part of the Storybook config, the issue still persists.

```diff
 module.exports = {
     stories: [
         '../src/**/*.stories.mdx',
         '../src/**/*.stories.@(js|jsx|ts|tsx)',
     ],
     addons: [
         '@storybook/addon-links',
         '@storybook/addon-essentials',
         '@storybook/addon-interactions',
     ],
     framework: '@storybook/react',
-    "core": {
-      "builder": "@storybook/builder-vite"
-    },
     "features": {
       "storyStoreV7": true
     }
}

```

**System**

```
Environment Info:

  System:
    OS: macOS 12.4
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 16.14.0 - /usr/local/bin/node
    Yarn: 1.22.17 - ~/.npm-global/bin/yarn
    npm: 8.5.5 - ~/.npm-global/bin/npm
  Browsers:
    Chrome: 103.0.5060.114
    Firefox: 97.0.1
    Safari: 15.5
  npmPackages:
    @storybook/addon-actions: ^6.5.9 => 6.5.9 
    @storybook/addon-essentials: ^6.5.9 => 6.5.9 
    @storybook/addon-interactions: ^6.5.9 => 6.5.9 
    @storybook/addon-links: ^6.5.9 => 6.5.9 
    @storybook/builder-vite: ^0.1.39 => 0.1.39 
    @storybook/react: ^6.5.9 => 6.5.9 
    @storybook/testing-library: ^0.0.13 => 0.0.13
```

**Additional context**

None

**Comment by dcastil** [comment]
Related: https://github.com/storybookjs/storybook/issues/18716

**Comment by IanVS** [comment]
Could you try upgrading to 7.0 to see if it still occurs there?  `npx sb@next upgrade --prerelease` will get you there.

**Comment by dcastil** [comment]
@IanVS I realized that this error was caused by the [MobX devtools extension](https://chrome.google.com/webstore/detail/mobx-developer-tools/pfgnfdagidkfgccljigdamigbcnndkod). Disabling the extension resolved the issue for me.

Forgot to update this issue, sorry for that!
