### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'createSnapshot') with Vite+React+Typescript

### ISSUE THREAD

**Issue by ArondeParon** [storybookjs/storybook#18696]
**Describe the bug**
When changing the builder to `vite`, on my React/Typescript project, I get the following error:

```
> storybook
> start-storybook -p 6006

info @storybook/react v6.5.9
info 
info => Loading presets
ℹ ｢wdm｣: wait until bundle finished: 
/[redacted]/node_modules/html-webpack-plugin/lib/webpack5/file-watcher-api.js:13
    mainCompilation.fileSystemInfo.createSnapshot(
                                   ^

TypeError: Cannot read properties of undefined (reading 'createSnapshot')
    at /[redacted]/node_modules/html-webpack-plugin/lib/webpack5/file-watcher-api.js:13:36
    at new Promise (<anonymous>)
    at Object.createSnapshot (/[redacted]/node_modules/html-webpack-plugin/lib/webpack5/file-watcher-api.js:12:10)
    at /[redacted]/node_modules/html-webpack-plugin/lib/cached-child-compiler.js:219:35

```

**To Reproduce**
I have not been able to successfully run `nix sb@next repro` because it fails with errors.

**System**
```
Environment Info:

  System:
    OS: macOS 12.4
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 3.2.1 - /opt/homebrew/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
  Browsers:
    Chrome: 103.0.5060.114
    Safari: 15.5
  npmPackages:
    @storybook/addon-actions: ^6.5.9 => 6.5.9 
    @storybook/addon-essentials: ^6.5.9 => 6.5.9 
    @storybook/addon-interactions: ^6.5.9 => 6.5.9 
    @storybook/addon-links: ^6.5.9 => 6.5.9 
    @storybook/addon-postcss: ^2.0.0 => 2.0.0 
    @storybook/builder-vite: ^0.1.39 => 0.1.39 
    @storybook/react: ^6.5.9 => 6.5.9 
    @storybook/testing-library: ^0.0.11 => 0.0.11 
```

**Additional context**

.babelrc
```
{
  "presets": [
    "@babel/preset-react",
    "@babel/preset-env",
    "@babel/preset-typescript"
  ]
}
```

tsconfig.json
```
{
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "moduleResolution": "node",
    "jsx": "react",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "paths": {
      "@/*": ["./resources/js/*"]
    },
    "types": [
      "vite/client",
    ],
    "downlevelIteration": true,
    "lib": [
      "dom",
      "es5",
      "scripthost",
      "es2015.collection"
    ]
  }
}
```

vite.config.js
```
import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';
import react from '@vitejs/plugin-react';

export default defineConfig({
    plugins: [
        laravel([
            'resources/js/app.tsx',
        ]),
        react(),
    ],
    resolve: {
        alias: {
            '@': '/resources/js',
            '~': '/resources',
        },
    },
});
```

postcss.config.js
```
module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
```

**Comment by jdatpdm** [comment]
I am also hitting this same error. 

Did you find a solution?

**Comment by angelocordon** [comment]
Unsure if this is applicable to a general setup, but for my current component library project (brand new), this started failing for us when we implemented Jest the more mainstream way - I had a hunch that babel was messing with compilation, so I reconfigured Jest to use ts-jest instead. 

So far, its looking promising.

**Comment by goddancer** [comment]
i changed the builder option in the .storybook/main.js file from '@storybook/builder-vite' to 'webpack5', and refer this link [cra5-upgrade](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#cra5-upgrade) to force Storybook to use webpack 5 for building.
now it works fine

**Comment by robotkutya** [comment]
@goddancer that kind of defeats the purpose though, no?

Does anyone have a solution for this using the vite builder?

**Comment by Emil-Ekman** [comment]
Deleting node_modules & package-lock.json then running npm i resolved it for me.
using "@storybook/builder-vite": "^0.2.5",

**Comment by kyh** [comment]
Any updates here?

**Comment by IanVS** [comment]
Can someone who is experiencing this provide a reproduction example that we can look into?  You can also try upgrading to Storybook 7.0 (`npx sb@next upgrade --prerelease`).

**Comment by rodoabad** [comment]
Anyone got any solution other than updating to a prerelease?

**Comment by IanVS** [comment]
@rodoabad 7.0 is now in release candidate phase, and will hopefully be released as stable soon.

We're not able to look into the issue further without a reproduction.

**Comment by lobaak** [comment]
Also seeing the same error

**Comment by IanVS** [comment]
@lobaak do you have a reproduction that you can share, specifically one using Storybook 7?

**Comment by katelynlensch** [comment]
@rodoabad did you find a solution to issue or did you upgrade?
