### ISSUE TITLE
Props tables generation from PropTypes doesn't work with preact

### ISSUE THREAD

**Issue by sballesteros** [storybookjs/storybook#18698]
**Describe the bug**

[Props tables](https://github.com/storybookjs/storybook/tree/next/addons/docs/react#props-tables) generation from PropTypes doesn't work with preact.

**To Reproduce**

👉  See https://github.com/sballesteros/storybook-reproduction-proptypes-preact

- Visit the docpage for the Primary Button story (the underlying component contains PropTypes with JSDocs comment):
    ```js
    Button.propTypes = {
      /**
       * Is this the principal call to action on the page?
       */
      primary: PropTypes.bool,
      //...
    }
    ```
- Notice the lack of description in the props table.

<img width="1051" alt="Screen Shot 2022-07-12 at 2 48 13 PM" src="https://user-images.githubusercontent.com/1141327/178602214-54c270a1-f63d-4b52-a074-2922df4ac7f7.png">

**System**
Please paste the results of `npx sb@next info` here.

```
  System:
    OS: macOS 11.6.7
    CPU: (8) x64 Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 3.2.1 - ~/.nvm/versions/node/v16.14.0/bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
  Browsers:
    Chrome: 103.0.5060.114
    Firefox: 101.0.1
    Safari: 15.5
  npmPackages:
    @storybook/addon-actions: ^6.5.9 => 6.5.9 
    @storybook/addon-docs: ^6.5.9 => 6.5.9 
    @storybook/addon-essentials: ^6.5.9 => 6.5.9 
    @storybook/addon-interactions: ^6.5.9 => 6.5.9 
    @storybook/addon-links: ^6.5.9 => 6.5.9 
    @storybook/builder-webpack4: ^6.5.9 => 6.5.9 
    @storybook/manager-webpack4: ^6.5.9 => 6.5.9 
    @storybook/preact: ^6.5.9 => 6.5.9 
    @storybook/testing-library: ^0.0.13 => 0.0.13 
```

**Additional context**

**Workaround**

Manually specify data with ArgTypes.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
