### ISSUE TITLE
Runtime Error Endpoint is a 404

### ISSUE THREAD

**Issue by exoRift** [storybookjs/storybook#18716]
**Describe the bug**
Whenever my React module has an error, rather than Storybook displaying the error, the endpoint to which the error should be posted (`/runtime-error`) returns a 404. It used to work, but I'm not sure what I changed that caused it to stop working.

**To Reproduce**
https://github.com/exoRift/fluentctx/tree/dev

**System**
```
Environment Info:

  System:
    OS: Linux 4.4 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (8) x64 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
  npmPackages:
    @storybook/addon-actions: ^6.5.9 => 6.5.9 
    @storybook/addon-essentials: ^6.5.9 => 6.5.9 
    @storybook/addon-interactions: ^6.5.9 => 6.5.9 
    @storybook/addon-links: ^6.5.9 => 6.5.9 
    @storybook/builder-webpack4: ^6.5.9 => 6.5.9 
    @storybook/manager-webpack4: ^6.5.9 => 6.5.9 
    @storybook/react: ^6.5.9 => 6.5.9 
    @storybook/testing-library: ^0.0.13 => 0.0.1
```

**Additional context**
![image](https://user-images.githubusercontent.com/20345400/179044434-7c47a236-a49e-4ce8-a293-f97babbda872.png)
![image](https://user-images.githubusercontent.com/20345400/179044460-e5fdec26-5cf0-476f-93ff-c1d62432da38.png)
![image](https://user-images.githubusercontent.com/20345400/179044481-65ba91f1-ddec-464e-9ad2-c94b2c46cc1b.png)

**Comment by ericclemmons** [comment]
I have the same issue - everything "works", but any uncaught error on the page gets sent here.

For example:

```js
{"message":"ResizeObserver loop limit exceeded","source":"http://localhost:6006/iframe.html?viewMode=story&id=payments-experience--live","line":0,"column":0,"error":null,"origin":"preview"}
```

**Comment by nategarrow** [comment]
Not sure if you have figured this out yet or not, but I had the same issue and it came down to a conflict I had with a browser extension ('Change Timezone for Google Chrome™' in my case).

In addition to the `/runtime-error 404` error, I had another error that had a few variable and function names that led me to the culprit extension. If you haven't already, start there. Hope you can figure it out!

**Comment by luin** [comment]
I think the 404 error has been fixed in https://github.com/storybooks/storybook/pull/20462?

**Comment by exoRift** [comment]
Could somebody test this before I close the issue?

**Comment by shilman** [comment]
Closing this for now. Please let me know if there's more to be done here!

**Comment by kiran-chikkala** [comment]
SyntaxError: Unexpected token '<'
