### ISSUE TITLE
@storybook/node-logger Cannot use import statement outside a module

### ISSUE THREAD

**Issue by Nieloss** [storybookjs/storybook#18727]
**Describe the bug**
`SyntaxError: Cannot use import statement outside a module` error when trying to add the `@storybook/addon-postcss` addon for using TailwindCSS in Storybook

**To Reproduce**
https://storybook.js.org/addons/@storybook/addon-postcss

**System**
```
  System:
    OS: macOS 12.4
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 16.16.0 - /opt/homebrew/opt/node@16/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.11.0 - /opt/homebrew/opt/node@16/bin/npm
  Browsers:
    Chrome: 103.0.5060.114
    Safari: 15.5
  npmPackages:
    @storybook/addon-actions: ^6.5.9 => 6.5.9
    @storybook/addon-essentials: ^6.5.9 => 6.5.9
    @storybook/addon-interactions: ^6.5.9 => 6.5.9
    @storybook/addon-links: ^6.5.9 => 6.5.9
    @storybook/addon-postcss: ^3.0.0-alpha.1 => 3.0.0-alpha.1
    @storybook/builder-webpack5: ^6.5.9 => 6.5.9
    @storybook/manager-webpack5: ^6.5.9 => 6.5.9
    @storybook/react: ^6.5.9 => 6.5.9
    @storybook/testing-library: ^0.0.13 => 0.0.13
```

**Additional context**
Using TypeScript and Next.JS

**Comment by Nieloss** [comment]
```
ERR! PATH_TO_PROJECT/node_modules/@storybook/addon-postcss/dist/index.js:1
ERR! import { logger } from '@storybook/node-logger';
ERR! ^^^^^^
ERR!
ERR! SyntaxError: Cannot use import statement outside a module
```

**Comment by Piderman** [comment]
Same here, running into issues with Tailwind 3, `storybook-addon-next` and the suggested solution from storybook docs specifically for post-css  : https://storybook.js.org/addons/@storybook/addon-postcss.

All was working well this morning until I tried adding a CSS module to a component rather than a page and storybook just started failing.

This is for a new project too so not expecting a fresh install of the packages to throw such an error.

**Comment by Nieloss** [comment]
Hey guys,

The problem occurs in the new `3.0.0-alpha.1` version, which was released 3 days ago.

Try installing version `2.0.0 `using `yarn add -D @storybook/addon-postcss@2.0.0` or `npm install @storybook/addon-postcss@2.0.0`.

Downgrading to version `2.0.0` fixed this issue for me.
```yarn
yarn run v1.22.19
$ start-storybook -p 6006
info @storybook/react v6.5.9
info
info => Loading presets
info => Serving static files from ././public at /
info Addon-docs: using MDX1
info => Using PostCSS preset with postcss@8.4.14
```

Let me know if this fixes your issues aswell!

**Comment by brianbancroft** [comment]
This solution also works for me, but I ran into an error and figured it out. Sharing in the hopes that it helps someone out:

```
Error: Cannot find module 'webpack/lib/util/makeSerializable.js'
```

Installing webpack@5 as a dev dependency was all I had to do in order to make Neils' solution work.
