### ISSUE TITLE
Call for help: Migrating to modern build tool : TSUP

### ISSUE THREAD

**Issue by ndelangen** [storybookjs/storybook#18732]
Hey friends!

If you're looking for a way to contribute to storybook's codebase, i might have a few small-ish tasks most people should be able to pick up!

We're in the process of migrating away from having custom scripts to prepare out packages for publishing to npm.
We've used `babel` and `tsc` to generate a `modern`, `esm`, and `cjs` output (in different directories.

We've picked a new tool that's better because:
- it bundles: meaning storybook can become less dependent on npm modules, de-duplicating etc.
- it's fast, faster then running babel multiple times, and running tsc
- it can generate typescript definition files that are also bundled

I've developed a wrapper around this tool called `ts-up` https://tsup.egoist.sh/#code-splitting

<details>
<summary>How does this script work?</summary>
here:
https://github.com/storybookjs/storybook/blob/19d75f066385e5afe01edbc78c6beabf938e90fe/scripts/prepare/bundle.ts

And the way we use it in our packages:
https://github.com/storybookjs/storybook/blob/19d75f066385e5afe01edbc78c6beabf938e90fe/code/lib/ui/package.json#L52

The script generates files in a different place (it does not generate into sub-directories):
- `entrypoint.js` (`cjs`)
- `entrypoint.mjs` (`esm`)
- `entrypoint.d.ts` (`definitions`)

So the references in `package.json` need to be updated:
https://github.com/storybookjs/storybook/blob/19d75f066385e5afe01edbc78c6beabf938e90fe/code/lib/ui/package.json#L41-L43

In addition to the above, we should also add a `exports` field in `package.json`, we need to add 1 for each entrypoint of the package, and also add a field for `package.json` file:
https://github.com/storybookjs/storybook/blob/19d75f066385e5afe01edbc78c6beabf938e90fe/code/lib/ui/package.json#L22-L40

Then of-course we need to define what the valid entrypoints are of the package, that the script should bundle:
https://github.com/storybookjs/storybook/blob/19d75f066385e5afe01edbc78c6beabf938e90fe/code/lib/ui/package.json#L96-L99
For most packages, this will likely just be 1 file.

If there's some code that needs to run before the bundling process, like generating a file:
https://github.com/storybookjs/storybook/blob/19d75f066385e5afe01edbc78c6beabf938e90fe/code/lib/ui/package.json#L95
Though this is not super common.

And if the package only runs in node or the browser, and you're getting errors about missing globals, you might need to specify the `"platform"` ("browser" or "node"): https://github.com/storybookjs/storybook/blob/19d75f066385e5afe01edbc78c6beabf938e90fe/code/addons/controls/package.json#L93

After applying the changes, run `yarn install` in the root of the project,

Then run `yarn build <name of package>` to see if the bundling works.
If it does, then we still need to check if it actually works.
That we can do by running the CI. If we wanted to test locally, run 1 of the examples, using the package.

Then run `yarn check <name of package>` to see if the bundling caused any TypeScript issues.
</details>

So we could use your help migrating all of out packages to use this new script!

Here's a list of packages we could use your help with:

| package name                                                                   | assign to        | completed | PR |
|--------------------------------------------------------------------------------|------------------|-----------|----|
| [`addons/a11y`](../blob/next/code/addons/a11y/package.json)                    | @Saunved         | ☒         |  https://github.com/storybookjs/storybook/pull/18772  |
| [`addons/actions`](../blob/next/addons/actions/package.json)                   |   @Saunved      | ☒         |   https://github.com/storybookjs/storybook/pull/18775 |
| [`addons/backgrounds`](../blob/next/addons/backgrounds/package.json)           | @Saunved         | ☒        |  https://github.com/storybookjs/storybook/pull/18784  |
| [`addons/controls`](../blob/next/addons/controls/package.json)                 | @Saunved         | ☒         |  https://github.com/storybookjs/storybook/pull/18786  |
| [`addons/docs`](../blob/next/addons/docs/package.json)                         | @ndelangen          | ☒         |  https://github.com/storybookjs/storybook/pull/19790  |
| [`addons/essentials`](../blob/next/addons/essentials/package.json)             |   @jeangregorfonrose      | ☒         | https://github.com/storybookjs/storybook/pull/19322   |
| [`addons/highlight`](../blob/next/addons/highlight/package.json)               |   @bryanjtc      | ☒         | https://github.com/storybookjs/storybook/pull/19483   |
| [`addons/interactions`](../blob/next/addons/interactions/package.json)         | @Ianvs         | ☒         |  https://github.com/storybookjs/storybook/pull/19139  |
| [`addons/jest`](../blob/next/addons/jest/package.json)                         | @luciana-mendonca                | ☒         |  https://github.com/storybookjs/storybook/pull/18836  |
| [`addons/links`](../blob/next/addons/links/package.json)                       | @luciana-mendonca                | ☒         |  https://github.com/storybookjs/storybook/pull/18908  |
| [`addons/measure`](../blob/next/addons/measure/package.json)                   | @luciana-mendonca                | ☒         |  https://github.com/storybookjs/storybook/pull/18837  |
| [`addons/outline`](../blob/next/addons/outline/package.json)                   | @luciana-mendonca                | ☒         |  https://github.com/storybookjs/storybook/pull/18842  |
| [`addons/storysource`](../blob/next/addons/storysource/package.json)           |   @bryanjtc           | ☒         |  https://github.com/storybookjs/storybook/pull/19482  |
| [`addons/toolbars`](../blob/next/addons/toolbars/package.json)                 | @luciana-mendonca                | ☒         |  https://github.com/storybookjs/storybook/pull/18847  |
| [`addons/viewport`](../blob/next/addons/viewport/package.json)                 | @luciana-mendonca                | ☒         |  https://github.com/storybookjs/storybook/pull/18943  |
| [`frameworks/angular`](../blob/next/frameworks/angular/package.json)           | LOOKING FOR ANGULAR EXPERT                | ☐         |  https://github.com/storybookjs/storybook/pull/19036  |
| [`frameworks/ember`](../blob/next/frameworks/ember/package.json)               | LOOKING FOR EMBER EXPERT  | ☐         |    |
| [`lib/addons`](../blob/next/code/lib/addons/package.json)                           |    @abdlqader         | ☒         |  https://github.com/storybookjs/storybook/pull/18805  |  
| [`lib/api`](../blob/next/code/lib/api/package.json)                                 | @ndelangen                | ☒         |  https://github.com/storybookjs/storybook/pull/19269  |
| [`lib/builder-webpack5`](../blob/next/code/lib/builder-webpack5/package.json)       |    @ndelangen           | ☒         |    |
| [`lib/channel-postmessage`](../blob/next/code/lib/channel-postmessage/package.json) |    @javier-arango           | ☒        |  https://github.com/storybookjs/storybook/pull/19388  |
| [`lib/channel-websocket`](../blob/next/code/lib/channel-websocket/package.json)     |   @bryanjtc   | ☒         | https://github.com/storybookjs/storybook/pull/19694   |
| [`lib/channels`](../blob/next/code/lib/channels/package.json)                       |   @B2Y4N        | ☒         |  https://github.com/storybookjs/storybook/pull/18882  |
| [`lib/cli`](../blob/next/code/lib/cli/package.json)                                 | @ianvs                | ☒         |  https://github.com/storybookjs/storybook/pull/19138  |
| [`lib/client-api`](../blob/next/code/lib/client-api/package.json)                   | @ndelangen                 | ☒        |  https://github.com/storybookjs/storybook/pull/19271  |
| [`lib/client-logger`](../blob/next/code/lib/client-logger/package.json)             | @ezmnysniper7                | ☒         |  https://github.com/storybookjs/storybook/pull/18893  |
| [`lib/codemod`](../blob/next/code/lib/codemod/package.json)                         |   @Platiplus          | ☒         |  https://github.com/storybookjs/storybook/pull/19398  |
| [`lib/core-client`](../blob/next/code/lib/core-client/package.json)                 | @ndelangen                 | ☒         | https://github.com/storybookjs/storybook/pull/19276   |
| [`lib/core-events`](../blob/next/code/lib/core-events/package.json)                 | @abdlqader       | ☒         |  https://github.com/storybookjs/storybook/pull/18798  |
| [`lib/core-server`](../blob/next/code/lib/core-server/package.json)                 | @ndelangen                | ☒         | https://github.com/storybookjs/storybook/pull/19278   |
| [`lib/core-webpack`](../blob/next/code/lib/core-webpack/package.json)               | @GanHingLong0423   | ☒         |  https://github.com/storybookjs/storybook/pull/18912  |
| [`lib/csf-tools`](../blob/next/code/lib/csf-tools/package.json)                     | @ianvs                | ☒         |  https://github.com/storybookjs/storybook/pull/19141  |
| [`lib/docs-tools`](../blob/next/code/lib/docs-tools/package.json)                   |   @darenbt    | ☒         | https://github.com/storybookjs/storybook/pull/19206   |
| [`lib/instrumenter`](../blob/next/code/lib/instrumenter/package.json)               |   @darenbt      | ☒         | https://github.com/storybookjs/storybook/pull/19206   |
| [`lib/node-logger`](../blob/next/code/lib/node-logger/package.json)                 |   @hayawata3626     | ☒        |  https://github.com/storybookjs/storybook/pull/19173  |
| [`lib/postinstall`](../blob/next/code/lib/postinstall/package.json)                 |   @tolkadot      | ☒         |  https://github.com/storybookjs/storybook/pull/19327  |
| [`lib/preview-web`](../blob/next/code/lib/preview-web/package.json)                 |   @javier-arango and @ndelangen      | ☒         |   https://github.com/storybookjs/storybook/pull/19319 - https://github.com/storybookjs/storybook/pull/19655 |
| [`lib/router`](../blob/next/code/lib/preview-web/package.json)                 | @hayawata3626       | ☒         |  https://github.com/storybookjs/storybook/pull/19140  |
| [`lib/source-loader`](../blob/next/code/lib/source-loader/package.json)             |  @shariqx5      | ☒         |  https://github.com/storybookjs/storybook/pull/19313  |
| [`lib/store`](../blob/next/code/lib/store/package.json)                             |  @javier-arango      | ☒         | https://github.com/storybookjs/storybook/pull/19308   |
| [`lib/telemetry`](../blob/next/code/lib/telemetry/package.json)                     |   @tolkadot      | ☒         |  https://github.com/storybookjs/storybook/pull/19317   |

So if you'd like to help converting any of these ♥️ ! Please mention here, which ones, you can take on, and open a PR converting a package.

There are details on how to do it, in the "How does this script work" `<details/>` in this issue.
If you need any help, please reach out to storybook maintainers on the [contributing channel](https://discord.gg/5pVUdF8gjj) on the Storybook discord.

**Comment by Saunved** [comment]
@ndelangen  Hi, I would like to pick up the first 8 packages from this list, viz. from `addons/a11y` to `addons/interactions`. 
If time permits, and if there aren't other takers, I could pick up a few more. Thanks!

**Comment by italoteix** [comment]
Since @Saunved is doing top -> bottom, I would like to also pick some and I'll do it bottom -> top and at least do 8 packages.

**Comment by shilman** [comment]
Son of a gun!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-alpha.16 containing PR #18772 that references this issue. Upgrade today to the `@future` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Gadzooks!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-alpha.17 containing PR #18786 that references this issue. Upgrade today to the `@future` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by abdlqader** [comment]
I would like to take the first 5 in lib directory.

**Comment by luciana-mendonca** [comment]
Hi @ndelangen  👋🏻  

I would like to contribute! 
Is it possible to take the rest of the `addons/*` packages? 

```
addons/jest 
addons/links  
addons/measure  
addons/outline  
addons/storysource  
addons/toolbars  
addons/viewport
```

**Comment by shilman** [comment]
w00t!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-alpha.18 containing PR #18836 that references this issue. Upgrade today to the `@future` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by B2Y4N** [comment]
Hi @ndelangen

This is my first time and I would like to contribute!
Can I take the lib/channels package?

**Comment by josh-the-dev** [comment]
Will take a look at lib/client-api. Love the idea by the way of collaboratively doing this!

**Comment by josh-the-dev** [comment]
Can help out with [lib/csf-tools](https://github.com/storybookjs/storybook/blob/next/lib/csf-tools/package.json) ! Love the idea 👍 !

**Comment by maytheu** [comment]
Hi @ndelangen 

I would love to pick the lib/core-client and lib/codemod

**Comment by shilman** [comment]
Jeepers creepers!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-alpha.19 containing PR #18847 that references this issue. Upgrade today to the `@future` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by ayush9398** [comment]
@shilman Are the packages mentioned without assignees available? If so, can I take them up?

**Comment by shilman** [comment]
@B2Y4N @josh-the-dev @maytheu thanks! i've updated the issue description. looking forward to your PRs!

@ayush9398 yes, which ones would you like to take?

**Comment by IanVS** [comment]
FWIW, it looks like the `esrun` part is no longer required.

**Comment by ayush9398** [comment]
The changes are similar, I think I can take all the remaining ones, but for starters can work on both framework packages first.

**Comment by shilman** [comment]
Jeepers creepers!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-alpha.24 containing PR #18912 that references this issue. Upgrade today to the `@future` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by ayush9398** [comment]
@shilman I have opened a [PR](https://github.com/storybookjs/storybook/pull/19036) but my tests are failing, can you please review it?

**Comment by IanVS** [comment]
I see that `@storybook/router` isn't in the list.  Should it be, or is there a reason not to convert it?

**Comment by hayawata3626** [comment]
Hi @ndelangen

I would like to contribute!
Is it possible to take the rest of the addons/* packages?

**Comment by ndelangen** [comment]
@hayawata3626 yeah awesome! thanks!, I would suggest you start with `lib/client-logger`.

**Comment by ndelangen** [comment]
@IanVS ow, yes! `lib/router` can be converted as well!

**Comment by hayawata3626** [comment]
@ndelangen 
Thanks for the reply!
I checked, and it looks like it's already handled.
https://github.com/storybookjs/storybook/blob/next/code/lib/client-logger/package.json#L42

I would like try the others if possible.

**Comment by IanVS** [comment]
Should `@storybook/cli-storybook` and `@storybook/cli-sb` even _have_ a `prep` script?  They don't seem to have been generating any `dist` folders previously, and I can't think what the `entries` would be.

**Comment by ndelangen** [comment]
> Should @storybook/cli-storybook and @storybook/cli-sb even have a prep script? They don't seem to have been generating any dist folders previously, and I can't think what the entries would be.

No they probably do not need a prep script at all!

**Comment by darenbt** [comment]
Hi @ndelangen,
I'm hoping to contribute to your codebase by converting these json packages:
```
lib/docs-tools
lib/instrumenter
```
I'll be submitting a PR in the near future.

**Comment by hayawata3626** [comment]
Hi @ndelangen!

I would like to contribute again.
Is it possible below?
```
node-logger
```

**Comment by Saunved** [comment]
I've been on vacation the last month! I'll pick up the pending packages in the next day or so 🤞

**Comment by javier-arango** [comment]
Hi @ndelangen

I would love to help you guys with this. Is it possible I can help converting these packages:

```
addons/actions
addons/storysource
```

**Comment by IanVS** [comment]
I think it's not necessary to ask for permission.  I suggest claiming them when you start working on them, just so others can know that they shouldn't start working on the same ones.

**Comment by shilman** [comment]
ZOMG!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-alpha.33 containing PR #19140 that references this issue. Upgrade today to the `@future` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by jeangregorfonrose** [comment]
Hi, @ndelangen,
I want to contribute to the codebase by converting these packages
`addons/essentials` `lib/addons`

**Comment by ndelangen** [comment]
@jeangregorfonrose `addons/essentials` should be very straight-forward!

I think `lib/addons` has been attempted before and was running into issues. #18805

**Comment by LuisChiej** [comment]
@ndelangen, I could pick up `lib/channels` and [lib/channel-websocket](https://github.com/storybookjs/storybook/blob/next/lib/channel-websocket/package.json)

**Comment by LuisChiej** [comment]
@IanVS, I'm new to the repo though, could I get a guide?

**Comment by IanVS** [comment]
Sure thing, you can checkout https://github.com/storybookjs/storybook/blob/next/CONTRIBUTING.md for overall repo setup, and there are some instructions in the original post above if you spin down the `How does this script work?` summary.  If you have other questions, feel free to ask here, or in the storybook discord: discord.gg/storybook.

**Comment by shariqx5** [comment]
Hey @ndelangen, I'd like to pick `lib/source-loader.`

**Comment by shariqx5** [comment]
Hey @ndelangen, I'd like to pick `lib/source-loader.`

**Comment by shilman** [comment]
Ooh-la-la!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-alpha.34 containing PR #19173 that references this issue. Upgrade today to the `@future` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by IanVS** [comment]
19/41 complete, almost half-way!

**Comment by tolkadot** [comment]
Hey @ndelangen, I can pick up  lib/telemetry.

**Comment by anubhavadarsh** [comment]
Hello @ndelangen , I can take up [`lib/store`](https://github.com/storybookjs/storybook/blob/next/code/lib/store/package.json)

**Comment by javier-arango** [comment]
@ndelangen I open a PR for `lib/store` and I am working on `lib/telemetry` right now. I was working on `addons/storysource`, but I was getting errors and I was not able to fix it.

**Comment by tolkadot** [comment]
I can pick up [lib/postinstall](https://github.com/storybookjs/storybook/blob/next/code/lib/postinstall/package.json)

**Comment by shilman** [comment]
Egads!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-alpha.35 containing PR #18805 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by Platiplus** [comment]
@ndelangen can I work on [lib/codemod](https://github.com/storybookjs/storybook/blob/next/code/lib/codemod/package.json) ?

**Comment by IanVS** [comment]
@Platiplus I've added you to the list, go for it!

**Comment by tolkadot** [comment]
I can take a look at [lib/builder-webpack5](https://github.com/storybookjs/storybook/blob/next/code/lib/builder-webpack5/package.json)

**Comment by SeepG** [comment]
I can pick this [lib/channel-postmessage](https://github.com/storybookjs/storybook/blob/next/code/lib/channel-postmessage/package.json)

**Comment by IanVS** [comment]
@SeepG it looks like there's already a PR for channel-postmessage.  https://github.com/storybookjs/storybook/pull/19388

I'll update the table, would you like to work on a different package?

**Comment by SeepG** [comment]
Sure @IanVS, the table is updated now. I see [lib/channel-websocket](https://github.com/storybookjs/storybook/blob/next/code/lib/channel-websocket/package.json) can I do that ?

**Comment by bryanjtc** [comment]
I can do `lib/channels`

**Comment by IanVS** [comment]
@SeepG @bryanjtc thanks, go for it!

**Comment by bryanjtc** [comment]
It seems someone already did lib/channels and it was merged. I will do `addons/storysource` and `addons/highlight`

**Comment by bryanjtc** [comment]
Someone named Jean already did addons/essentials and it was merged. It should be on the table.

**Comment by IanVS** [comment]
Thanks, I've updated the table.  We're getting close!

**Comment by shilman** [comment]
Son of a gun!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-alpha.38 containing PR #19388 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Egads!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-alpha.39 containing PR #19482 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by bryanjtc** [comment]
I can try to do [addons/docs](https://github.com/storybookjs/storybook/blob/next/addons/docs/package.json)
I know there is already a pr, but it seems it had a few problems.

**Comment by shilman** [comment]
Ermahgerd!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-alpha.46 containing PR #19655 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by SeepG** [comment]
Haven't been able to look at 😞 [lib/channel-websocket](https://github.com/storybookjs/storybook/blob/next/code/lib/channel-websocket/package.json), if anyone is interested please feel free to pick it up.

**Comment by bryanjtc** [comment]
@SeepG I can

**Comment by shilman** [comment]
Boo-yah!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-alpha.49 containing PR #19790 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Yo-ho-ho!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-alpha.51 containing PR #19694 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Ermahgerd!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-alpha.53 containing PR #19895 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Great Caesar's ghost!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.15 containing PR #20134 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

**Comment by shilman** [comment]
w00t!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.20 containing PR #20150 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Ermahgerd!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.21 containing PR #20156 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
@ndelangen Is this done? I recall that you had a fix for `builder-webpack5` somewhere?
