### ISSUE TITLE
Storybook theming package conflicts with `@emotion/react`

### ISSUE THREAD

**Issue by e-cooper** [storybookjs/storybook#18742]
**Describe the bug**

The published `@storybook/theming` (v6.5.9) package includes code from the `@emotion/react` package which causes a console warning to appear. **This was not the case pre-6.5.** It states `You are loading @emotion/react when it is already loaded. Running multiple instances may cause problems. This can happen if multiple versions are used, or if multiple builds of the same version are used.` This is because the code to check whether Emotion 11 is included is run twice. Once from each package that includes it.

**To Reproduce**

[Here's a Codesandbox with both libs pulled in.](https://codesandbox.io/s/mystifying-montalcini-vh5y3k?file=/src/App.js)

**System**

n/a

**Additional context**

This may cause more issues than just a console warning, but this has been the only issue I've noticed so far.

**Comment by e-cooper** [comment]
Should `@emotion/react` be a peer dependency?

**Comment by TomFreudenberg** [comment]
Would be great to get an information about any progress on this task.

**Comment by mwood23** [comment]
This is breaking MDX styling for me in a monorepo that also uses Chakra UI. Running `npm dedupe` fixes the issue but I'm not sure the other issues that introduces.

**Comment by ndelangen** [comment]
This is fixed in storybook 7.0 beta

**Comment by mcqj** [comment]
Seeing the error with Storybook 7.0.22.
Apart from upgrading to 7, is there something that needs to be changed in Storybook config?

**Comment by ndelangen** [comment]
please provide a repro, It's likely there's something odd happening with multiple (including old) versions getting installed.
