### ISSUE TITLE
Public members of a component are converted to strings

### ISSUE THREAD

**Issue by gitout0fhere** [storybookjs/storybook#18748]
**Description**
When implementing a component and adding public members to the component, for example an object, the public member is of the type I gave it when running the application. When running Storybook however, the public members are converted to strings.

```
  public thisIsATest = "1234567890";
  public thisIsATestObject = { name: "Hola Mundo" };

  public test(): string {
    return typeof this.thisIsATestObject;
  }
```

**How to reproduce**
* Clone the repository https://github.com/gitout0fhere/storybook-bug-public-members-are-strings
* Check out the modifications I made in the last commit
* `npm i`
* `ng serve`
* Navigate to `localhost:4200`
* Check the result of the variable checks I made: 1234567890 object ![image](https://user-images.githubusercontent.com/75678224/179925209-1d4c0f34-3425-446f-99e0-2d22ff121460.png)
* `ng run taskbox:storybook`
* Navigate to `localhost:6007`
* Open the Header story
* Check the result of the variable checks I made: "1234567890" string (also note the quotation marks around 1234567890) ![image](https://user-images.githubusercontent.com/75678224/179925751-5ec2b12e-41e9-4904-b49f-4d281ff460bc.png)

**System**
Environment Info:

  System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  Binaries:
    Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.18 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.12.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (103.0.1264.62)
  npmPackages:
    @storybook/addon-actions: ^6.5.6 => 6.5.7
    @storybook/addon-essentials: ^6.5.6 => 6.5.7
    @storybook/addon-interactions: ^6.5.6 => 6.5.7
    @storybook/addon-links: ^6.5.6 => 6.5.7
    @storybook/angular: ^6.5.6 => 6.5.7
    @storybook/builder-webpack5: ^6.5.6 => 6.5.7
    @storybook/jest: ^0.0.10 => 0.0.10
    @storybook/manager-webpack5: ^6.5.6 => 6.5.7
    @storybook/testing-library: ^0.0.11 => 0.0.11

**Comment by gitout0fhere** [comment]
Private members work like it should.

**Comment by impurity-dev** [comment]
This seems related to #16838

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
