### ISSUE TITLE
Cannot copy files into NextJS public folder during build (Cannot copy 'public' to a subdirectory of itself)

### ISSUE THREAD

**Issue by mikeebee** [storybookjs/storybook#18753]
I am using NextJS, I need Storybook to be accessed via the same project URL (http://webaddress.com/storybook) as such as part of my build step I use `/public` as the output directory.

`build-storybook -o ./public/storybook`

As part of the standard NextJS setup, my assets are also in this directory `/public/assets` and I serve them to Storybook using the `staticDirs` property in `main.js`.

`staticDirs: ['../public'],`

This has worked fine until today when I needed to upgrade Node from 14x (`14.15.1`) to 16x (`16.13.2`) as part of a dependency requirement for [Next Auth](https://next-auth.js.org/).

Now, when I try to build I get this error...

```
/project-dir/node_modules/@storybook/core-server/node_modules/fs-extra/lib/util/stat.js:42
      return cb(new Error(errMsg(src, dest, funcName)))
                ^

Error: Cannot copy '/project-dir/public' to a subdirectory of itself, '/project-dir/public/storybook/'.
    at /project-dir/node_modules/@storybook/core-server/node_modules/fs-extra/lib/util/stat.js:42:17
```

As far as I know, this is the standard approach, so I'm unsure how best to proceed. Any direction (or alternatives) will be much appreciated 😊

**System**

```
Environment Info:

  System:
    OS: macOS 11.6
    CPU: (12) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
  Browsers:
    Chrome: 103.0.5060.134
    Safari: 15.4
  npmPackages:
    @storybook/addon-actions: ^6.5.9 => 6.5.9
    @storybook/addon-essentials: ^6.5.9 => 6.5.9
    @storybook/addon-links: ^6.5.9 => 6.5.9
    @storybook/builder-webpack5: ^6.5.9 => 6.5.9
    @storybook/client-api: ^6.5.9 => 6.5.9
    @storybook/manager-webpack5: ^6.5.9 => 6.5.9
    @storybook/react: ^6.5.9 => 6.5.9
```

**Additional info**

I see that [at the bottom of the CLI docs](https://storybook.js.org/docs/react/api/cli-options), it says this...

![oh do one](https://user-images.githubusercontent.com/1635958/180322870-d601e9f8-f24e-4805-8f3a-2f3ac87be1c4.png)

I tried adding the `--` flag but it just build into the default `storybook-static` directory outside of public.

**Comment by DzmVasileusky** [comment]
same here, that was working before and have stopped to work after I've change the static assets directory

**Comment by jxnx888** [comment]
> 

Where to put this configuration?

**Comment by DzmVasileusky** [comment]
@jxnx888 that's `./storybook/main.js`

**Comment by mikeebee** [comment]
@DzmVasileusky thanks for the suggestion but this didn't work for me but I'm unsure of the purpose of `const rootMain = require('../../../.storybook/main');` or how to use it in the file so may be missing a step.

My current workaround (Which I. will replace if I can fix it properly) was to manually move the folder after Storybook has been built.

In `package.json` (Other scripts removed for brevity)

```
 "scripts": {
    "build": "npm run build:storybook && npm run move-storybook && npm run build:next",
    "build:next": "next build",
    "build:storybook": "rm -rf ./public/storybook && build-storybook",
    "move-storybook": "mv ./storybook-static ./public/storybook"
  },
```

**Comment by jeremyfrank** [comment]
I also encountered this issue, and @DzmVasileusky's `staticDirs` fix worked for me. I just had to adjust the `from` path a little. /cc @mikeebee

```js
module.exports = {
    ...
    staticDirs: [{ from: '../public/assets', to: '/assets' }],
};
```

**Comment by mikeebee** [comment]
@jeremyfrank thanks for the clarification, I didn't fully understand correctly how to use @DzmVasileusky's solution. This works perfectly!

Thanks so much to you both 🙌
