### ISSUE TITLE
After switching component/story old style stays on a new story 

### ISSUE THREAD

**Issue by TodBob** [storybookjs/storybook#18756]
**Describe the bug**
When I switch to a new story, that old style always stays on a new story.
So for example, I have Avatar and Button components. I start on the avatar and switch to the button, but the avatar leaves some width style and border radius on the button. I have to refresh storybook to correctly render components.

I'm using React and BaseWeb from uber.

Any idea how to force the storybook first to clear the old style and after that render new styles? BaseWeb applies classNames on components.

**To Reproduce**
My project:
https://github.com/TodBob/storybook

**Comment by Maxi937** [comment]
Same issue - fix was to manually track the styles for each story and append/remove them when the story id was changed
