### ISSUE TITLE
How to access custom helper/util/hook function on storybook ?

### ISSUE THREAD

**Issue by YosaRama** [storybookjs/storybook#18766]
### Discussed in https://github.com/storybookjs/storybook/discussions/18724

<div type='discussions-op-text'>

<sup>Originally posted by **YosaRama** July 16, 2022</sup>
Hi I'm New at Storybook.js,

I want to ask how to access some custom function that I use on my components ?

Here my component Code :
<img width="569" alt="Screen Shot 2022-07-16 at 08 30 20" src="https://user-images.githubusercontent.com/67961793/179327095-699c007d-d490-4a25-a822-a43f1644ca99.png">

Currently my component have 2 helper, and load from "../app/helpers"

Here my storiesbook for that component : 
<img width="582" alt="Screen Shot 2022-07-16 at 08 32 13" src="https://user-images.githubusercontent.com/67961793/179327139-e4e49a23-3e4f-453a-be49-ccd97f6d36c9.png">

And I got this error when running `yarn storybook`
<img width="507" alt="Screen Shot 2022-07-16 at 08 33 19" src="https://user-images.githubusercontent.com/67961793/179327171-47052ef7-6a7b-43d3-9b5f-bee3fbd8dc60.png">

Please anyone can give me some advice for this problem ?

Thanks

</div>

**Comment by ndelangen** [comment]
The path to your module is not a relative path. The builder can't find it.
