### ISSUE TITLE
eslint-plugin-storybook can't be listed as optionalDependencies 

### ISSUE THREAD

**Issue by eric-burel** [storybookjs/storybook#18760]
**Describe the bug**
When eslint-plugin-storybook is listed as an optional dependencies in the package.json, `npx sb upgrade` will fail with `Usage Error: Package "eslint-plugin-storybook" is already listed as a regular dependency - remove the -D,-P flags or remove it from your dependencies first`.

**To Reproduce**
(this is really a minor bug so not sure about a repro: install esling-plugin-storybook using -O and try to update SB with the CLI)

**System**
Please paste the results of `npx sb@next info` here.
```
Environment Info:

  System:
    OS: Linux 5.15 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (6) x64 Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 3.2.1 - /usr/bin/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
  Browsers:
    Chrome: 90.0.4430.93
    Firefox: 102.0
  npmPackages:
    @storybook/builder-webpack5: next => 6.5.0-beta.2 
    @storybook/manager-webpack5: next => 6.5.0-beta.2 
    @storybook/testing-react: ^1.3.0 => 1.3.0 


```
**Additional info**

The npm package.json structure is a legacy that do not correctly represent today's use case.
- dependencies: should be kept for runtime dependencies
- devDependencies: should be kept for build time dependencies => when Node was created there was no such thing as a build system! so nothing was planned for build deps. devDependencies happens to be the best place for those deps.
- optionalDependencies: should be kept for local dev dependencies => this will make deployment way faster, because those deps are not needed for deployment (only for local testing and CI)

That's why I care that much about having `eslint-plugin-storybook` as an optional dependency.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
