### ISSUE TITLE
Vue 2 class components using vue-property-decorator and typescript do not render initially and generate mutating prop warnings

### ISSUE THREAD

**Issue by kaethr01** [storybookjs/storybook#18770]
**Describe the bug**
Using vue-property-decorators, Vue 2, and typescript in a Vue CLI generated project when the page renders on mount of the component a console error is generated for every prop stating not to modify props and the component does not render until a prop is modified in the Controls section of Storybook UI.  I do not notice this behavior when not using vue-property-decorators and the class component syntax.

**To Reproduce**
1. Create a new project using the Vue CLI UI selecting Vue 2, Typescript, and Class Component Syntax
2. Install storybook using `npx sb init --type vue`
3. Add the `@storybook/preset-typescript` package 
4. Add `@storybook/preset-typescript` to the addons section of `.storybook/main.js`
5. Create a component using vue-property-decorators and a couple props using `@Prop`
6. Create a basic story for the component
7. Launch storybook using `npm run storybook`
8. Click the component story in the left navigation
9. Observe the component is not rendered initially and there is a Vue warning about modifying props for each prop
10. Updating a prop in the storybook Controls UI will render the component.  Navigating to a different story and back to this story produces the same behavior each same.  So does hitting the remount component button in the UI.

Here is a reproduction repo: https://github.com/kaethr01/vue-ts-storybook-property-decorator
The component example is `src/components/TestButton.vue`
The story example is `src/stories/TestButton.stories.js`

**System**
  System:
    OS: Windows 10 10.0.18363
    CPU: (12) x64 Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz
  Binaries:
    Node: 16.14.0 - ~\AppData\Local\REDACTED\tools\node\16.14.0\node.EXE
    npm: 8.3.1 - ~\AppData\Local\REDACTED\tools\node\16.14.0\npm.CMD
  Browsers:
    Edge: Spartan (44.18362.1593.0)
  npmPackages:
    @storybook/addon-actions: ^6.5.9 => 6.5.9
    @storybook/addon-essentials: ^6.5.9 => 6.5.9
    @storybook/addon-interactions: ^6.5.9 => 6.5.9
    @storybook/addon-links: ^6.5.9 => 6.5.9
    @storybook/builder-webpack5: ^6.5.9 => 6.5.9
    @storybook/manager-webpack5: ^6.5.9 => 6.5.9
    @storybook/testing-library: ^0.0.13 => 0.0.13
    @storybook/vue: ^6.5.9 => 6.5.9

**Additional context**

Pictures of the console errors- these are the errors produced by Vue itself.  The component renders the button but does not put the props on it correctly.
![image](https://user-images.githubusercontent.com/48555653/180447114-28ae87f3-e613-43bd-8f77-c57b67c6d343.png)

After changing something in the Controls section, it all renders properly
![image](https://user-images.githubusercontent.com/48555653/180447595-0ea9507b-d8ab-4918-98dc-3c0b81186cd1.png)

These issues were observed in both Chrome and Edge.

**Comment by MJB52** [comment]
+1 same issue

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).

**Comment by supuwoerc** [comment]
+1
