### ISSUE TITLE
Controls tab count should exclude hidden controls

### ISSUE THREAD

**Issue by josephmarkus** [storybookjs/storybook#18780]
**Describe the bug**
Consider `MyComponent` that has `label` prop, as well as other 4 props. In total, that's 5 props, 1 of which is hidden like so:

```
<Meta
  title="Components/MyComponent"
  component={MyComponent}
  argTypes={{
    label: {
      table: {
        disable: true,
      },
    },
  }}
/>
```

When toggling into **Controls** tab in Storybook, in parentheses it shows the number of available controls.

The number shows as 5, when it should show 4, because 1 is hidden.

**To Reproduce**
Check reproduction repo - https://github.com/josephmarkus/storybook-control-count-bug/blob/master/src/stories/Button.stories.jsx#L6-L32

## Observe `Controls (4)` below when it should read `Controls (1)`
![Screenshot 2022-07-25 at 12 03 41](https://user-images.githubusercontent.com/9258365/180763277-eba9dcb3-3395-4ed9-9523-5aea7e736fec.png)

**System**
```
Environment Info:

  System:
    OS: macOS 12.4
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 3.2.2 - ~/.nvm/versions/node/v16.16.0/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
  Browsers:
    Chrome: 103.0.5060.134
    Safari: 15.5
  npmPackages:
    @storybook/addon-actions: ^6.5.9 => 6.5.9 
    @storybook/addon-docs: ^6.5.9 => 6.5.9 
    @storybook/addon-essentials: ^6.5.9 => 6.5.9 
    @storybook/addon-interactions: ^6.5.9 => 6.5.9 
    @storybook/addon-links: ^6.5.9 => 6.5.9 
    @storybook/builder-webpack5: ^6.5.9 => 6.5.9 
    @storybook/manager-webpack5: ^6.5.9 => 6.5.9 
    @storybook/node-logger: ^6.5.9 => 6.5.9 
    @storybook/preset-create-react-app: ^4.1.2 => 4.1.2 
    @storybook/react: ^6.5.9 => 6.5.9 
    @storybook/testing-library: ^0.0.13 => 0.0.13 
```

**Additional context**

**Comment by BikashSah999** [comment]
Hi @shilman @ndelangen , Can I work on this issue ?

**Comment by BikashSah999** [comment]
Hi @shilman  @ndelangen , the PR for this issue is ready for review. Could you please review it?

**Comment by valentinpalkovic** [comment]
Hi @BikashSah999, the PR has been merged!

**Comment by jonniebigodes** [comment]
@BikashSah999 wanted to follow up with you on a tiny item related to this issue and the pull request you've made addressing it. If you're ok with it, can you message me on our [Discord server](https://discord.gg/storybook) (same username), and we'll take it from there. Sounds good?

Hope you have a great week.

Stay safe

**Comment by shilman** [comment]
Jiminy cricket!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-alpha.53 containing PR #19877 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
