### ISSUE TITLE
Generated stories.json not respecting dynamic includeStories/excludeStories config

### ISSUE THREAD

**Issue by malouro** [storybookjs/storybook#18792]
**Describe the bug**

We have a setup where we use `includeStories` and `excludeStories` parameters to hide certain stories in certain environments and builds of our Storybook. (for example, different stories for testing specifically vs. what we publish) 

Given the following setup in an example `Button.stories.jsx`:

```js
import getStoriesToInclude from './getStoriesToInclude';

export default {
  title: 'Example/Button',
  component: Button,
  ...getStoriesToInclude()
};

export const Primary = () => { /* component code */ }
export const Secondary = () => { /* component code */ }
// etc.
```

and an example `getStoriesToInclude.js`:

```js
// ./getStoriesToInclude.js
export default function() {
  if (process.env.NODE_ENV === 'test') {
    return {
      excludeStories: ['Secondary']
    };
  }
  return {};
}
```

When we extract a `stories.json` with `NODE_ENV=test` however, it still includes the "Secondary" Button story.

**To Reproduce**

1. Check out & clone https://github.com/malouro/storybook-exclude-stories-repro
2. Install dependencies and run `NODE_ENV=test yarn build-storybook`
3. View contents of `storybook-static/stories.json` and see it includes the "Secondary" Button story.

**System**

```
Environment Info:

  System:
    OS: macOS 12.3.1
    CPU: (10) x64 Apple M1 Pro
  Binaries:
    Node: 14.19.3 - ~/.nvm/versions/node/v14.19.3/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 6.14.17 - ~/.nvm/versions/node/v14.19.3/bin/npm
  Browsers:
    Chrome: 103.0.5060.134
    Firefox: 102.0.1
    Safari: 15.4
  npmPackages:
    @storybook/addon-actions: ^6.5.9 => 6.5.9 
    @storybook/addon-essentials: ^6.5.9 => 6.5.9 
    @storybook/addon-interactions: ^6.5.9 => 6.5.9 
    @storybook/addon-links: ^6.5.9 => 6.5.9 
    @storybook/builder-webpack4: ^6.5.9 => 6.5.9 
    @storybook/manager-webpack4: ^6.5.9 => 6.5.9 
    @storybook/react: ^6.5.9 => 6.5.9 
    @storybook/testing-library: ^0.0.13 => 0.0.13
```

**Additional context**

As mentioned before, the configuration described here is how we've built our Storybook for different environments (different stories for testing vs. publication)

We might be utilizing the `includeStories`/`excludeStories` configurations in a non-supported or unexpected way with this setup, but figured making a report could help narrow down how this should be handled.

Also, the `stories.json` *will* build correctly if the `excludeStories` is explicitly listed as a static config like:

```js
export default {
  title: 'Example/Button',
  component: Button,
  excludeStories: ['Secondary']
};
```

moreover, this config breaks the build:

```js
export default {
  title: 'Example/Button',
  component: Button,
  excludeStories: [].concat(process.env.NODE_ENV === 'test' ? ['Secondary'] : [])
};
```

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).

**Comment by apetta** [comment]
This is still a problem, and very difficult to work around. Alternatively, a global excludeStories would do the trick - at least in my case.

**Comment by apetta** [comment]
For anyone else dealing with this, a workaround is to make `includeStories` or `excludeStories` itself conditional.

In other words, something like this:

```
const excludeStory = isNative ? { excludeStories: ["Tests"] } : {};

const Metadata: Meta<InputProps> = {
  ...excludeStory,
```
