### ISSUE TITLE
none of the links work on the readme

### ISSUE THREAD

**Issue by ethanneff** [storybookjs/storybook#18807]
Sub Projects
[CLI](https://github.com/storybookjs/storybook/blob/next/lib/cli) - Streamlined installation for a variety of app types
[examples](https://github.com/storybookjs/storybook/blob/next/examples) - Code examples to illustrate different Storybook use cases

**Comment by jonniebigodes** [comment]
@ethanneff, thanks for taking the time to open up this issue and letting us know. To give you a bit more context, we're aware of this, and a pull request fixing the links will be up soon.

Hope you have a great day!

Stay safe
