### ISSUE TITLE
Components with vue functional keyword does not render on storybook

### ISSUE THREAD

**Issue by avinean** [storybookjs/storybook#18811]
**Describe the bug**
Vue component with `functional: true` doesn't render in storybook

**To Reproduce**
How component looks like
`import { defineComponent, PropType } from 'vue'
  const sizes = { xs: 12, sm: 14, md: 16, lg: 24, xl: 28 }
  const dirs = { down: 90, up: -90, left: -180 }

  export default defineComponent({
    functional: true,
    props: {
      name: {
        type: String,
        required: true
      },
      size: String as PropType<'xs' | 'sm' | 'md' | 'lg' | 'xl'>,
      dir: String as PropType<'down' | 'up' | 'left'>
    },
    render(h, { props, data, listeners }) {
      return h('svg-icon', {
        props: {
          name: props.name
        },
        class: [...(data.staticClass || data.class ? [data.staticClass, data.class] : [])],
        attrs: {
          ...data.attrs,
          ...(props.size && {
            width: sizes[props.size],
            height: sizes[props.size]
          })
        },
        on: listeners,
        style: {
          'flex-shrink': 0,
          'fill': 'currentColor',
          ...(props.dir && { transform: `rotate(${dirs[props.dir]}deg)` })
        }
      })
    }
  })`

How story looks like 
`
export const test = (_, { argTypes }) => ({
  props: Object.keys(argTypes),
  template: `<base-icon name="search" size="lg" />`
})
`

I expect to see the same code in docs.
But here is what I see
<img width="1116" alt="image" src="https://user-images.githubusercontent.com/22274408/181729694-e528927f-d8fd-4180-ac10-59132c3ba3ec.png">

**Comment by avinean** [comment]
While I was waiting for the answer I found a solution.
The main idea is to create one more component with proper name that renders necessary component and register it in particular story

`
import Icon from '@/components/base/Icon.vue'
const BaseIcon = {
  name: 'BaseIcon',
  components: { Icon },
  template: '<icon v-bind="$attrs" />'
}

export const test = (_, { argTypes }) => ({
  props: Object.keys(argTypes),
  components: { BaseIcon },
  template: `<base-icon name="search" size="lg" />`
})
`

<img width="1124" alt="image" src="https://user-images.githubusercontent.com/22274408/181732309-31b6a651-c7d9-42b3-a6da-7aaac8721cd8.png">

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
