### ISSUE TITLE
"Failed to load source map" warnings in local dev

### ISSUE THREAD

**Issue by TrevorBurnham** [storybookjs/storybook#18815]
**Describe the bug**
When running Storybook locally, Chrome's dev tools emits the warning

> DevTools failed to load source map: Could not load content for http://localhost:6006/index.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

because multiple bundles emitted by Storybook include the source map reference

```js
//# sourceMappingURL=index.js.map
```

These source map references come from upstream packages. Normally the solution would be to use [source-map-loader](https://github.com/webpack-contrib/source-map-loader/) to resolve `sourceMappingURL` comments in imported code, but adding `source-map-loader` to Storybook's `webpackFinal` configuration does not eliminate all `sourceMappingURL` comments. Specifically, it `sourceMappingURL` comments in `vendors~main.iframe.bundle.js` but not in `vendors~main.manager.bundle.js`.

**To Reproduce**
This one is reproducible out of the box by running `npx sb@next repro` and selecting the options `react`, then `react-typescript`.

I created a repro that takes the additional step of adding `source-map-loader` to Storybook's Webpack config: https://github.com/TrevorBurnham/sb-sourcemap-bug I've tried using Webpack 5 + the latest `source-map-loader` version, with the same results.

**System**
```
Environment Info:

  System:
    OS: macOS 12.5
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 16.13.0 - ~/.volta/tools/image/node/16.13.0/bin/node
    Yarn: 3.2.2 - ~/.volta/tools/image/yarn/1.22.17/bin/yarn
    npm: 8.1.3 - ~/.volta/tools/image/npm/8.1.3/bin/npm
  Browsers:
    Chrome: 103.0.5060.134
    Firefox: 102.0.1
    Safari: 15.6
  npmPackages:
    @storybook/addon-actions: ^6.5.9 => 6.5.9 
    @storybook/addon-docs: ^6.5.9 => 6.5.9 
    @storybook/addon-essentials: ^6.5.9 => 6.5.9 
    @storybook/addon-interactions: ^6.5.9 => 6.5.9 
    @storybook/addon-links: ^6.5.9 => 6.5.9 
    @storybook/builder-webpack4: ^6.5.9 => 6.5.9 
    @storybook/manager-webpack4: ^6.5.9 => 6.5.9 
    @storybook/react: ^6.5.9 => 6.5.9 
    @storybook/testing-library: ^0.0.13 => 0.0.13 
```

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
