### ISSUE TITLE
Fontawesome icons cannot be displayed

### ISSUE THREAD

**Issue by michalgrzegorczyk-dev** [storybookjs/storybook#18822]
**Describe the bug**
Unable to display fontawesome icons.

**To Reproduce**
Put font awesome icon into the code. It's visible in application but not visible in storybook.

**Comment by rwagatenga** [comment]
Hi @michalgrzegorczyk-dev
can you please clarify how to reproduce an error? better any image or loom video could help.

**Comment by sourcec0de** [comment]
@michalgrzegorczyk-dev 
Add this to `preview.ts`
```ts
import '@fortawesome/fontawesome-svg-core/styles.css'
```

**Comment by shilman** [comment]
#### Bug Fixes

-   Server: Fix .stories.yml support [#22906](https://github.com/storybooks/storybook/pull/22906)
-   Docs: Fix Source block snippet updates [#22835](https://github.com/storybooks/storybook/pull/22835)
-   Core: Fix indexing errors by excluding node_modules stories [#22873](https://github.com/storybooks/storybook/pull/22873)
-   CLI: Fix upgrade notification message [#22933](https://github.com/storybooks/storybook/pull/22933)
-   Angular: Add --open/--no-open flag to dev command [#22964](https://github.com/storybooks/storybook/pull/22964)
-   Angular: Silence compodoc when running storybook with --quiet [#22957](https://github.com/storybooks/storybook/pull/22957)

#### Maintenance

-   Core: Improve MDX of error in story index [#22782](https://github.com/storybooks/storybook/pull/22782)

#### Build

-   Build: Fix the theme output during development [#22841](https://github.com/storybooks/storybook/pull/22841)
-   Revert "Docs: E2E tests for Source block update fix" [#22934](https://github.com/storybookjs/storybook/pull/22934)
