### ISSUE TITLE
Scss file doesn't work in react storybook

### ISSUE THREAD

**Issue by raguct25** [storybookjs/storybook#18841]
**Describe the bug**
   I have created react storybook and create separate folder for storybook.
   In storybook directory, installed storybook used command is **npx storybook init** and  I have selected **react** type. 
   It has working fine for **CSS** files. When I use **SCSS** file I got this error.

   `ERROR in ./stories/ButtonComponent/button.scss 1:0 Module parse failed: Unexpected token (1:0) You may need an appropriate 
    loader to handle this file type, currently no loaders are configured to process this file.`

**Folder structure**

![image](https://user-images.githubusercontent.com/35067734/182316790-9172994a-04e9-43ef-990d-4130c3ded344.png)

**Used packages**

> "devDependencies": {
"@babel/core": "^7.18.9",
"@storybook/addon-actions": "^6.5.9",
"@storybook/addon-essentials": "^6.5.9",
"@storybook/addon-interactions": "^6.5.9",
"@storybook/addon-links": "^6.5.9",
"@storybook/builder-webpack4": "^6.5.9",
"@storybook/manager-webpack4": "^6.5.9",
"@storybook/react": "^6.5.9",
"@storybook/testing-library": "0.0.13",
"babel-loader": "^8.2.5"
},

**main.js file**

> module.exports = {
stories: [
'../stories/**/*.stories.mdx',
'../stories/**/*.stories.@(js|jsx|ts|tsx)',
],
addons: [
'@storybook/addon-links',
'@storybook/addon-essentials',
'@storybook/addon-interactions',
],
framework: '@storybook/react',
};

**preview.js file**

> export const parameters = {
actions: { argTypesRegex: "^on[A-Z].*" },
controls: {
matchers: {
  color: /(background|color)$/i,
  date: /Date$/,
   },
 },
}

**package.json**

> "scripts": {
    "storybook": "start-storybook -p 6006",
    "build-storybook": "build-storybook"
  },

Anyone tell me, Is need any **packages** and any **configurations** in **main.js** file ?

**Comment by pocka** [comment]
Yes, you need to install the [SCSS preset](https://github.com/storybookjs/presets/tree/master/packages/preset-scss) or configure Storybook's webpack configuration. See [Importing CSS files (official docs)](https://storybook.js.org/docs/react/configure/styling-and-css#importing-css-files).
