### ISSUE TITLE
Storybook for Angular generates errors when component uses FontAwesome icons

### ISSUE THREAD

**Issue by chrisraiskin** [storybookjs/storybook#18861]
Describe the bug
When creating a story for an Angular component using FontAwesome icons, the story renders the component, but  the console displays errors. It's worth mentioning that the story template does not reference FontAwesome icons directly, but the component template does.  The browser console shows 

```
ERROR Error: Could not find icon with iconName=fasMapMarkerAlt and prefix=fas in the icon library.
```

To Reproduce
Create a story for a component using FontAwesome icons

System

    "@angular/core": "~13.1.0",
    "@fortawesome/angular-fontawesome": "^0.10.1",

    "@storybook/angular": "^6.5.9",
    "@storybook/builder-webpack5": "^6.5.9",
    "@storybook/manager-webpack5": "^6.5.9",
    
Chrome Version 103.0.5060.114 (Official Build) (x86_64)

What I have tried 

I have found this guide on how to use FontAwesome within Storybook
https://github.com/FortAwesome/angular-fontawesome/blob/master/docs/guide/storybook.md
and added the following `APP_INITIALIZER` to  the story setup:

```ts
export default {
  title: 'Prism/Cards/Office',
  component: PrismCardOfficeComponent,
  argTypes: {},
  decorators: [
    moduleMetadata({
      declarations: [PrismCardOfficeComponent],
      imports: [FontAwesomeModule],
      providers: [
        {
          provide: APP_INITIALIZER,
          useFactory: (iconLibrary: FaIconLibrary) => async () => {
            // add any icons needed here:
            iconLibrary.addIconPacks(fas);
            iconLibrary.addIcons(fasMapMarkerAlt);
            iconLibrary.addIcons(fasPhone);
            iconLibrary.addIcons(fasFax);
            iconLibrary.addIcons(fasEnvelope);
          },
          // when using a factory provider you need to explicitly specify its dependencies
          deps: [FaIconLibrary],
          multi: true
        }
      ]
    })
  ]
} as Meta;

// Template of how args map to a story
const Template: Story<PrismCardOfficeComponent> = (args: PrismCardOfficeComponent) => ({
  component: PrismCardOfficeComponent,
  props: args,
  template: `
                <prism-card-office
                  [officeName]="officeName"
                  [address]="address"
                  [phone]="phone"
                  [fax]="fax"
              ></prism-card-office>
  `
});
```

however, that did not stop the errors from showing in the console for each FA icon referenced.
But even if the above did work, I would certainly hope that the story does not need to know this much about the component it's rendering.

**Comment by ndelangen** [comment]
This isn't something we can really support here.
I hope you've found a solution in the mean time. If not perhaps you could try posting on StackOverflow.
Good luck 🙏
