### ISSUE TITLE
"@mdx-js/mdx" should be updated to "^2.0.0" for avoiding ReDoS

### ISSUE THREAD

**Issue by GuillaumeCisco** [storybookjs/storybook#18860]
https://github.com/storybookjs/storybook/blob/85db984dab6b8d132c612ab6ba51bb636711ef93/code/lib/codemod/package.json#L46

In `storybook/codemod` package.json,
`@mdx-js/mdx` should be updated to `^2.0.0` for avoiding `remark-mdx` to be on `1.6.22` implying `remark-parse` to be on `8.0.3` implying trim to be on `0.0.1` which is vulnerable to Regular Expression Denial of Service (ReDoS)

`trim` should be on `0.0.3` thanks to `remark-parse` to be on `^10.0.0` thanks to `remark-mdx` to be on `^2.0.0` thanks to `@mdx-js/mdx` to be on `^2.0.0`

**Comment by shilman** [comment]
closing as dupe to #14603
