### ISSUE TITLE
Toolbar - Hide only background button but keep grid button

### ISSUE THREAD

**Issue by iKrishnaSahu** [storybookjs/storybook#18870]
**Describe the bug**
Is there any way to hide background button without hiding grid button?
Currently snippet provided in reproduction section is hiding both background as well as grid button.
My requirement is to hide only background button.

**To Reproduce**

Use below code in preview.js file

```ts
export const parameters = {
  ...
  toolbar: {
    'storybook/background': { hidden: true }
  }
}
```

Before
<img width="441" alt="image" src="https://user-images.githubusercontent.com/34937515/182860146-8f18b7a6-1dad-4055-b9cf-511ecf181a8c.png">

After

<img width="395" alt="image" src="https://user-images.githubusercontent.com/34937515/182855468-eb81ec7f-c80a-42ab-bbbc-0091e934d0e0.png">

**System**
Environment Info:

  System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.15.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (103.0.1264.77)
  npmPackages:
    @storybook/addon-essentials: ~6.5.4 => 6.5.9
    @storybook/angular: ~6.5.4 => 6.5.9
    @storybook/builder-webpack5: ~6.5.4 => 6.5.9
    @storybook/core-server: ~6.5.4 => 6.5.9
    @storybook/html: ^6.5.8 => 6.5.9
    @storybook/manager-webpack5: ~6.5.4 => 6.5.9
    @storybook/preset-scss: ^1.0.3 => 1.0.3

**Additional context**

**Comment by BikashSah999** [comment]
Hi @shilman @ndelangen , Can I work on this issue and what would be the desired behavior?

**Comment by BikashSah999** [comment]
@iKrishnaSahu  We can use this config to resolve this issue
```
Primary.parameters = {
  backgrounds: {
    grid: { disable: false },
    disable: true
  }
}
```

**Comment by BikashSah999** [comment]
@CHE1RON  you can check about `disabling/enabling` background and grid [here in the docs](https://storybook.js.org/docs/react/essentials/backgrounds)
