### ISSUE TITLE
Source Doc Block should be visible when Canvas Doc Block contains only HTML and has withSource="open" attribute

### ISSUE THREAD

**Issue by 7studio** [storybookjs/storybook#18871]
**Describe the bug**
Source Doc Block is not visible by default when Canvas Doc Block has `withSource="open"` attribute and contains only HTML.

**To Reproduce**
1. Create a MDX stories file
2. Set Canvas Doc Block with some HTML
3. Add `withSource="open"` to the Canvas Doc Block
4. Open "Docs" panel

**Expected behavior**
"Hide code" mention should be present and Source Doc Block should be displayed by default.

**Reproduction**
GitHub repository: https://github.com/7studio/sb-repo-html-canvas-source
Chromatic project: https://62eb96363d58eea5f465900f-omtihjeekw.chromatic.com/?path=/docs/dynamic-source--dynamic-source

**System**
```
  System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
  Binaries:
    Node: 14.17.0 - C:\nodejs\node.EXE
    npm: 6.14.13 - C:\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (103.0.1264.77)
  npmPackages:
    @storybook/addon-actions: 6.4.19 => 6.4.19
    @storybook/addon-essentials: 6.4.19 => 6.4.19
    @storybook/addon-links: 6.4.19 => 6.4.19
    @storybook/addons: 6.4.19 => 6.4.19
    @storybook/builder-webpack5: 6.4.19 => 6.4.19
    @storybook/html: 6.4.19 => 6.4.19
    @storybook/manager-webpack5: 6.4.19 => 6.4.19
    @storybook/preset-scss: 1.0.3 => 1.0.3
    @storybook/theming: 6.4.19 => 6.4.19
```

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
