### ISSUE TITLE
tsconfig absolute paths not working in a react+ts+vite+storybook project #65

### ISSUE THREAD

**Issue by alirezaaminii** [storybookjs/storybook#18891]
**Bug**
I can't use absolute paths importing in a react+ts+vite+storybook project.
I tried to solve the bug with [vite-tsconfig-paths](https://github.com/aleclarson/vite-tsconfig-paths) plugin that vite community published but it still is not working.

**tsconfig.json:**

```
{
  "include": ["src", "vite.config.ts"],
  "compilerOptions": {
    ...
    "baseUrl": "./src",
    "paths": {
      "~/*": ["./*"]
    }
  },
}
```

**vite.config.ts:**
`plugins: [react(), tsconfigPaths()],`

**code:**
`> src/components/button/index.stoties.tsx`
`import {icon} from '~/components/icons/icon';`

**Error:**
`TypeError: Failed to fetch dynamically imported module: http://localhost:6006/src/components/button/index.stories.tsx`

**Comment by spicattutti** [comment]
See https://github.com/storybookjs/storybook/issues/3291#issuecomment-1012911640, worked for me.

**Comment by alirezaaminii** [comment]
> See [#3291 (comment)](https://github.com/storybookjs/storybook/issues/3291#issuecomment-1012911640), worked for me.

As I said I'm using vite instead of webpack for building my library,  what should I write instead of `webpackFinal` in storybook configs?

**Comment by akinorimizushima** [comment]
You can use `viteFinal`. In my case, I wrote some code to resolve paths.

```typescript
async viteFinal(config) {
  const sourceRoot = resolve(__dirname, "../src");
  const dirs = (
    await readdir(resolve(sourceRoot), {
      withFileTypes: true,
    })
  ).filter((dirent) => dirent.isDirectory());
  const sourceRootAliases = dirs.reduce((acc, dir) => {
    const dirPath = resolve(sourceRoot, dir.name);
    return { ...acc, [dir.name]: dirPath };
  }, {});

  return mergeConfig(config, {
    resolve: { alias: { ...config.resolve.alias, ...sourceRootAliases } },
  });
},
```

**Comment by JakubPradeniak** [comment]
@alirezaaminii hi! I have found simple solution to this problem -> according to https://github.com/storybookjs/builder-vite the Storybook will **not** load your `vite.config.ts`, thus it will not load anything you have specified in your cofig files.

As @akinorimizushima wrote the solution is to use viteFinal, but basicaly you only have to add your `vite.config.ts` contents.

To add path resolutions from my `tsconfig.json` I'm using https://github.com/aleclarson/vite-tsconfig-paths (same as your conf), to use it in Storybook I've edited `.storybook/main.cjs` as follows:

```javascript
const viteTsconfig = require('vite-tsconfig-paths');
const tsconfigPaths = viteTsconfig.default;

const { mergeConfig } = require('vite');

module.exports = {
  stories: ['../src/**/*.stories.mdx', '../src/**/*.stories.@(js|jsx|ts|tsx)'],
  addons: [
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    '@storybook/addon-interactions',
  ],
  framework: '@storybook/react',
  core: {
    builder: '@storybook/builder-vite',
  },
  features: {
    storyStoreV7: true,
  },
  async viteFinal(config) {
    return mergeConfig(config, {
      plugins: [tsconfigPaths()],
    });
  },
};
```

**NOTE:** do **not** include `react()` to config in `.storybook/main.cjs`, because doing so will include it second time and thus create "already defined" conflicts.

**Comment by IanVS** [comment]
You're right, @JakubPradeniak, thanks for explaining.  We found this behavior to be confusing, and in 7.0, we _will_ read and use your `vite.config.js` automatically, which should hopefully make things easier.

**Comment by Guilherme-Jesus** [comment]
@JakubPradeniak 
Thank you, the solution presented, solved an error that I was trying to solve for 3 days.

**Comment by nelsieborja** [comment]
> #3291 (comment)

Works for tsx but not for mdx files:
Storybook v7
tsconfig.json
```
{
  ...
  "baseUrl": "./src",
  "paths": {
    "~/*": ["./*"]
  },
  ...
}
```
vite.config.ts
```
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import tsconfigPaths from "vite-tsconfig-paths";
export default defineConfig({
  plugins: [react(), tsconfigPaths()],
});

```

**Comment by carlflor** [comment]
Both of these approaches don't work when importing something in `.storybook/preview.ts`

just by using vite.config.ts
```
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import tsconfigPaths from "vite-tsconfig-paths";
export default defineConfig({
  plugins: [react(), tsconfigPaths()],
});
```
nor

using viteFinal
```
  async viteFinal(config) {
    return mergeConfig(config, {
      plugins: [tsconfigPaths()],
    });
  },
```

**Comment by JakubPradeniak** [comment]
@nelsieborja , @carlflor hi guys, this solution was designed fot SB v6. This shouldn't be neccessary in SB v7 (see IanVS comment above).
If you have this problems, maybe consiged creating new issue for SB v7.

**Comment by bildungsroman** [comment]
I'm having issues with this as well, and a google search landed me here. I'm on SB8 and using @storybook/react-vite and getting the "Failed to fetch dynamically imported module" error when running SB.

**Comment by kerryj89** [comment]
Using `Storybook 8.5.3` and `storybook/experimental-nextjs-vite`

Importing files seems to work partially - as in, if I misspell the file filename it throws an error as expected, so it sees the file I am trying to import in.

The act of importing in members of the file with the alias seems to fail in .storybook and mdx files:
- src/components/**/*.mdx
- .storybook/ (config files)

Changing the import from

```jsx
import * as BoxStories from '@/components/Box/stories/Box.stories.tsx';
```

to

```jsx
import * as BoxStories from '../../Box/stories/Box.stories';
```

fixes the errors.

From what I can see, custom aliases are not fully resolved in .storybook/ config files and MDX files sadly.

**Comment by NishargShah** [comment]
Any example for ESM? its breaking in `node 22`?

```
viteFinal: async (config) => {
  config.resolve = {
    ...config.resolve,
    alias: {
      ...(config.resolve?.alias || {}),
      '@': path.resolve(__dirname, '../src'),
    },
  };
  return config;
},
```
