### ISSUE TITLE
After storybook init, it cannot load any of the generated .tsx examples: ReferenceError: $RefreshReg$ is not defined

### ISSUE THREAD

**Issue by jeremytowne** [storybookjs/storybook#18913]
They all fail to load with this error:
```
Unexpected error while loading ./stories/Button.stories.tsx: $RefreshReg$ is not defined
 ReferenceError: $RefreshReg$ is not defined
    at ./src/stories/Button.tsx (http://localhost:6006/main.iframe.bundle.js:703:1)
    at __webpack_require__ (http://localhost:6006/runtime~main.iframe.bundle.js:28:33)
    at fn (http://localhost:6006/runtime~main.iframe.bundle.js:339:21)
    at ./src/stories/Button.stories.tsx (http://localhost:6006/main.iframe.bundle.js:212:65)
    at __webpack_require__ (http://localhost:6006/runtime~main.iframe.bundle.js:28:33)
    at fn (http://localhost:6006/runtime~main.iframe.bundle.js:339:21)
    at webpackContext (http://localhost:6006/main.iframe.bundle.js:1390:9)
    at http://localhost:6006/vendors-node_modules_storybook_addon-actions_preview_js-generated-config-entry_js-node_module-2d1eff.iframe.bundle.js:28754:29
    at Array.forEach (<anonymous>)
    at http://localhost:6006/vendors-node_modules_storybook_addon-actions_preview_js-generated-config-entry_js-node_module-2d1eff.iframe.bundle.js:28752:18
```

This is using the default out of the box config generated by `npx storybook init`, so my `main.js` is still using webpack5
```
module.exports = {
  "stories": [
    "../src/**/*.stories.mdx",
    "../src/**/*.stories.@(js|jsx|ts|tsx)"
  ],
  "addons": [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/addon-interactions"
  ],
  "framework": "@storybook/react",
  "core": {
    "builder": "@storybook/builder-webpack5"
  }
}
```

**Comment by ndelangen** [comment]
This seems like some bad config/setup to me. Can you supply a reproduction?

Does this issue still exist? Can you try the latest 7.0 beta?

**Comment by mgenov** [comment]
Getting the same error with 7.1.0

<img width="456" alt="image" src="https://github.com/storybookjs/storybook/assets/209223/8f88e38f-7966-4fc6-953a-d04510a39af7">

<img width="1071" alt="image" src="https://github.com/storybookjs/storybook/assets/209223/fd2b0085-0b6b-42dd-9418-6c0a3dede91e">

**Comment by ndelangen** [comment]
Can you supply a reproduction?

**Comment by mgenov** [comment]
Yes, I found the solution in the second link. 

Setting explicit fastRefresh: true worker for me. 

```jsx
reactOptions: {
    fastRefresh: true,
},
```

Thanks for your feedback.

**Comment by ereminnf** [comment]
The solution with reactOptions from [mgenov](https://github.com/mgenov) above didn't work for me.
I adjusted the babel config specifically for the storybook, removed the 'react-refresh/babel' plugin and now everything is working.

p.s. I use babel config via [babel](https://storybook.js.org/docs/react/api/main-config-babel#babelconfig) parameter in .storybook/main.js

**Comment by valentinpalkovic** [comment]
@doctap Can you provide a reproduction? The error shouldn't occur. Of course fast-refresh option might fix it but I am curious what's causing the error.
