### ISSUE TITLE
[@storybook/builder-vite] `process is not defined` error in production bundle.

### ISSUE THREAD

**Issue by AkimaLunar** [storybookjs/storybook#18920]
**Describe the bug**
I am using `@storybook/builder-vite` and started getting `process is not defined` _only_ in the production build. The preview still runs ok. When I remove `builder: '@storybook/builder-vite',` the build gets fixed.

![image](https://user-images.githubusercontent.com/5331992/184236252-37e283e7-4229-4b66-ae4f-027e740a72f2.png)

**To Reproduce**
- Check out [repro-repo](https://storybook.js.org/docs/react/contribute/how-to-reproduce).
- `cd docs`
- `python3 -m http.server 8000`

**System**
  System:
    OS: Linux 5.15 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    npm: 8.13.2 - ~/.nvm/versions/node/v16.15.1/bin/npm

**Additional context**

```json
  "devDependencies": {
    "@fluentui/react-theme": "^9.0.0",
    "@griffel/react": "^1.3.0",
    "@storybook/addon-actions": "^6.5.10",
    "@storybook/addon-essentials": "^6.5.10",
    "@storybook/addon-interactions": "^6.5.10",
    "@storybook/addon-links": "^6.5.10",
    "@storybook/builder-vite": "^0.2.2",
    "@storybook/jest": "^0.0.10",
    "@storybook/react": "^6.5.10",
    "@storybook/testing-library": "^0.0.13",
    "assert": "^2.0.0",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "typescript": "^4.7.4",
    "vite": "^3.0.5"
  }
```

**Comment by phenrique7** [comment]
There's a thread in https://github.com/browserify/node-util/issues/43 that discusses solutions to this problem in more detail. I was able to find a more general solution in another thread, in this [comment](https://github.com/evanw/esbuild/issues/1626#issuecomment-970629402).

**Comment by iamcsharper** [comment]
> 

Hi! Could you please provide an example? Can't see how a plugin for esbuild can be applied to storybook's vite pipeline

**Comment by IanVS** [comment]
Vite does not polyfill `process` for the browser like webpack does.  You'll want to use `import.meta.env` instead, for code that runs in the browser.  See https://vitejs.dev/guide/env-and-mode.html#env-variables.

If you want to add esbuild plugins, I believe you can use the `esbuild` option (https://vitejs.dev/config/shared-options.html#esbuild), though I haven't done that before myself.  You can set this in `viteFinal` in your `.storybook/main.js` as seen here: https://github.com/storybookjs/builder-vite#customize-vite-config

**Comment by kharann** [comment]
Anyone has some guidance on how to solve this?

**Comment by IanVS** [comment]
@kharann what have you tried?  I've given some guidance above.  You should be using `import.meta.env` and not `process.env`, and you may need to find packages that are designed to run in the browser instead of ones using node.js APIs, if this is coming from a dependency.

**Comment by JaapWeijland** [comment]
I did this and it worked - for now. What seems to be causing the error is the fact the we are using webpack 5 under the hood (?), and webpack 5 doesnt provide polyfills by default anymore. Since `process` doesn't exist in the browser, it needs to be polyfilled.

This is a very dirty workaround (`.storybook/main.js`):

```
module.exports = {
    async viteFinal(config, { configType }) {
        return mergeConfig(config, {
            define: {
                ...
                'process.env.NODE_DEBUG': false,
            },
            ...
        });
    },
    ...
};

```

**Comment by IanVS** [comment]
Personally I would recommend against mixing @storybook/builder-vite with an app that is using webpack.  I think it's better to have consistency between the way your app and storybook are being bundled.  But I understand that some prefer to have the speed of vite in storybook even if they aren't using it for their app (e.g. they're using next.js and can't switch).  Just be aware that it's not really an "official" configuration and you might hit snags like above.

I'll close out this issue since it's not a problem in the vite builder, but thanks everyone for sharing your solutions, and hopefully they'll help others who might hit this challenge.

**Comment by JaapWeijland** [comment]
I actually don't mix webpack with vite intentionally; I am using Hydrogen which is using vite. I think it's one of the addons that is using webpack instead of vite, and not my project per se. Since @storybook/vite-builder is supposed to work in tandem with addons like `@storybook/addon-essentials`, I do think its an issue with the storybook ecosystem, of which @storybook/builder-vite is part.

**Comment by JaapWeijland** [comment]
Btw, during debugging, commenting out `@storybook/addon-essentials` did remove the error. So it has something to do with the interplay between this addon and `@storybook/builder-vite`.

**Comment by IanVS** [comment]
@JaapWeijland what version of storybook are you using?  6.x uses webpack 4 for building the "manager" part of the UI (sidebar, addons panel, etc), but 7.0 does not.  You could try running `npm why webpack` to see why webpack might be getting included in your project.   But, I don't see `NODE_DEBUG` anywhere in the storybook source, so I'm not sure where that could have been coming from.

**Comment by kharann** [comment]
I kinda fixed it with:
```
      define: {
        "process.env": {},
      },
```

in my viteFinal config. I'm mixing Vite due to my design-system is being built with esbuild. Therefore I used vite to display the stories from the design system. However, I also have some specific storybook components in the Nextjs application that didn't work.

**Comment by erkinun** [comment]
hey @IanVS I created a fresh Vite project and added Storybook to it and getting the same exact problem. 
```
   mkdir storybook-test
   cd storybook-test
   yarn create vite
   cd storybook-test
   yarn
   npx storybook init
   yarn run build-storybook
   npx http-server ./storybook-static
```

And these are my dev dependency versions: 
```
"devDependencies": {
    "@babel/core": "^7.20.2",
    "@storybook/addon-actions": "^6.5.13",
    "@storybook/addon-essentials": "^6.5.13",
    "@storybook/addon-interactions": "^6.5.13",
    "@storybook/addon-links": "^6.5.13",
    "@storybook/builder-vite": "^0.2.5",
    "@storybook/react": "^6.5.13",
    "@storybook/testing-library": "^0.0.13",
    "@types/react": "^18.0.24",
    "@types/react-dom": "^18.0.8",
    "@vitejs/plugin-react": "^2.2.0",
    "babel-loader": "^8.3.0",
    "typescript": "^4.6.4",
    "vite": "^3.2.3"
  }
```
Shall I create another issue?

**Comment by jaredh159** [comment]
had the same issue with storybook + `next/link`, fix was:

```js
// .storybook/main.js
module.exports {
  async viteFinal(config, { configType }) {
    return mergeConfig(config, {
      define: { 'process.env': {} },
    });
  },
  // ...rest of config
}
```

**Comment by IanVS** [comment]
@jaredh159 that will probably work, but keep in mind that Next.js is built on top of Webpack, so we don't recommend using the Vite builder for your Storybook, since you can run into inconsistencies like this.

**Comment by tobiasdiez** [comment]
I also encountered this error. For me, it was caused by
https://github.com/browserify/node-util/blob/ef984721db7150f651800e051de4314c9517d42c/util.js#L109-L116
with util being pulled-in by 
```
@storybook/builder-manager@npm:7.0.0-beta.31
│  └─ util@npm:0.12.5 (via npm:^0.12.4)
│
├─ @storybook/codemod@npm:7.0.0-beta.31
│  └─ util@npm:0.12.5 (via npm:^0.12.4)
```
There is already an upstream PR fixing this, https://github.com/browserify/node-util/pull/62, but it seemed stalled.

**Comment by arinthros** [comment]
For folks using Yarn, you can use yarn's built in patch functionality to patch the `util` package to resolve this error. Here's a gist to patch the package if you want to avoid faking process.env in the bundler configs.

https://gist.github.com/arinthros/68e1b622b27b98f3a6a45585dc751b82

**Comment by kellyrmilligan** [comment]
why is this issue even closed?  if you check out a fresh version of storybook with vite, this still exists.

**Comment by IanVS** [comment]
@kellyrmilligan could you provide a reproduction or steps to reproduce?  We have CI that runs on every PR that creates new Vite projects, so we know this is not broken globally in all cases.

**Comment by kellyrmilligan** [comment]
I guess i'm going off of the post above that has the steps to repro?

I did track down my version of the issue, and I seem to be not able to even provide a variable in define for production mode. 

```ts
 define: {
        "process.env.NODE_ENV": JSON.stringify(
          configType === "DEVELOPMENT" ? "development" : "production"
        ),
        "process.env.REACT_APP_ENV": JSON.stringify(
          configType === "DEVELOPMENT" ? "development" : "production"
        ),
      },
```

and the code that breaks it is in a file that is imported in my `preview.tsx` file.

**Comment by kellyrmilligan** [comment]
ok, I just noticed that the code that was causing the issue was using optional chaining on the process.env variable, so it was not picking it up. 😭

**Comment by IanVS** [comment]
Ah yeah, sneaky.  It's a straight-up string replacement, so that would do it.  Glad you got it figured out.

**Comment by bronz3beard** [comment]
I was importing next/image by error (honestly I forgot it was there 😅) and it uses `process.env.__NEXT_IMAGE_OPTS` I remove `<Image ... />` and everything is happy now 🎉
