### ISSUE TITLE
MDX2: newline character is added visually, and extra `<p>` tag is getting inserted in the DOM

### ISSUE THREAD

**Issue by melanieseltzer** [storybookjs/storybook#18921]
**Describe the bug**

I've come across two rendering issues working with MDX 2 / `previewMdx2: true` is set.

- When there's no newline between jsx in the story source code, `"\n"` gets inserted visually in the UI.

- When the jsx is multi-line in the source code, then the content gets wrapped in a `<p>` tag in the DOM. ONLY occurs if the source code itself (the jsx) is multi-line, not if the content itself is rendered on multiple lines and wraps in the UI.

I can't seem to upload any screenshots along with this issue report to help visually show this (GitHub says `"something went wrong and we can't process that file"` 😕), so please check out my link below to reproduce this.

**To Reproduce**
https://github.com/melanieseltzer/mdx2-rendering-bugs-reproduction

**System**
```
  System:
    OS: macOS 11.2.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
  Browsers:
    Chrome: 104.0.5112.79
    Firefox: 102.0.1
    Safari: 14.0.3
  npmPackages:
    @storybook/addon-docs: ^6.5.10 => 6.5.10 
    @storybook/addon-essentials: ^6.5.10 => 6.5.10 
    @storybook/builder-webpack5: ^6.5.10 => 6.5.10 
    @storybook/manager-webpack5: ^6.5.10 => 6.5.10 
    @storybook/mdx2-csf: ^0.0.3 => 0.0.3 
    @storybook/react: ^6.5.10 => 6.5.10
```

**Additional context**

**Comment by zhyd1997** [comment]
This is [mdx](https://github.com/mdx-js/mdx/tree/main/packages/mdx) library issue.

### SHORT ANSWER

The bug occurred at [fromMarkdown](https://github.com/syntax-tree/mdast-util-from-markdown/blob/77208c8d1bfaf33f4024ce0b90e640178322e7d1/dev/lib/index.js#L105) fn.

### LONG EXPLANATION

For `mdx` example from repro repo: 
https://github.com/melanieseltzer/mdx2-rendering-bugs-reproduction/blob/47f402b136f7603016cb7e186086cd25515b2fba/stories/Heading.stories.mdx

to demonstrate the explanation, I set up a new repo: [debug-mdx](https://github.com/zhyd1997/debug-mdx)

the call stack is:

[compile(file, options?)](https://github.com/mdx-js/mdx/blob/main/packages/mdx/readme.md#compilefile-options) <- [process(file)](https://github.com/unifiedjs/unified/blob/b9358691047ad72e6390dfc3c3eedc15509e01fa/lib/index.js#L374) <- [parse(doc)](https://github.com/unifiedjs/unified/blob/b9358691047ad72e6390dfc3c3eedc15509e01fa/lib/index.js#L261)

for [line 263](https://github.com/unifiedjs/unified/blob/b9358691047ad72e6390dfc3c3eedc15509e01fa/lib/index.js#L263), the `file` result a normal [VFile](https://github.com/vfile/vfile) object:

```js
VFile {
  data: {},
  messages: [],
  history: [],
  cwd: '/Users/zhyd1997/workspace/mdx',
  value: "import { Canvas, Meta, Story, ArgsTable } from '@storybook/addon-docs';\n" +
    "import { Heading } from './Heading';\n" +
    '\n' +
    '<Meta title="Components/Heading" component={Heading} />\n' +
    '\n' +
    '# MDX 2 Rendering Bugs\n' +
    '\n' +
    `When there's no linebreak between jsx in the story source code, "\n` +
    '" gets inserted visually in the UI.\n' +
    '\n' +
    '<Canvas>\n' +
    '  <Story name="one">\n' +
    '    <Heading>Lorem ipsum dolor sit amet</Heading>\n' +
    '    <Heading>Lorem ipsum dolor sit amet</Heading>\n' +
    '  </Story>\n' +
    '</Canvas>\n' +
    '\n' +
    `When there is a linebreak between jsx in the story source code, then there's no "\n` +
    '" in the UI, and things look normal.\n' +
    '\n' +
    '<Canvas>\n' +
    '  <Story name="two">\n' +
    '    <Heading>Lorem ipsum dolor sit amet</Heading>\n' +
    '\n' +
    '    <Heading>Lorem ipsum dolor sit amet</Heading>\n' +
    '\n' +
    '  </Story>\n' +
    '</Canvas>\n' +
    '\n' +
    'When the jsx is multi-line in the source code, then the content gets wrapped in a \\<p\\> tag when rendered.\n' +
    '\n' +
    'ONLY occurs if the source code itself (the jsx) is multi-line, not if the content itself is rendered on multiple lines and wraps in the UI.\n' +
    '\n' +
    '<Canvas>\n' +
    '  <Story name="three">\n' +
    '    <Heading>I am very long, but am kept on one line in the source code, so there is no wrapper paragraph tag inserted around me. I am very long, but am kept on one line in the source code, so there is no wrapper paragraph tag inserted around me.</Heading>\n' +
    '\n' +
    '    <Heading>\n' +
    '      Multi-line in the source code, wrapped in p tag.\n' +
    '    </Heading>\n' +
    '\n' +
    '  </Story>\n' +
    '</Canvas>\n' +
    '\n' +
    '## Props\n' +
    '\n' +
    '<ArgsTable of={Heading} />'
}
```

but when running the [return](https://github.com/unifiedjs/unified/blob/b9358691047ad72e6390dfc3c3eedc15509e01fa/lib/index.js#L273) statement, the result is strange (you can try to run `console.log(JSON.stringify(Parser(String(file), file)))`, and format it on a online JSON viewer.):
1. `\n` issue:

<img width="1022" alt="Screen Shot 2022-08-16 at 16 47 13" src="https://user-images.githubusercontent.com/31362988/184838889-5570a7cd-5228-441d-af8f-e935f2c8e1d2.png">
<img width="1022" alt="Screen Shot 2022-08-16 at 16 51 54" src="https://user-images.githubusercontent.com/31362988/184838896-0170cfaa-12ae-4613-8e08-c0830acb0d82.png">


2. `<p>` issue:
<img width="892" alt="Screen Shot 2022-08-16 at 16 36 48" src="https://user-images.githubusercontent.com/31362988/184835805-5cdc5c05-5827-4fd0-893f-e1c78155befe.png">

<img width="654" alt="Screen Shot 2022-08-16 at 16 34 02" src="https://user-images.githubusercontent.com/31362988/184835360-86baadce-671a-41f4-ba5f-5fc9c1f82962.png">

After logging the [Parser](https://github.com/unifiedjs/unified/blob/b9358691047ad72e6390dfc3c3eedc15509e01fa/lib/index.js#L264):

```js
console.log(Parser.toString())
```

I found it uses `remark-parse` [parser](https://github.com/remarkjs/remark/blob/99179c6745a2173d07d5c3b46bad7df767e1989d/packages/remark-parse/lib/index.js#L11-L25).


so continuing the call stack:

`remarkParse(options)` <- [fromMarkdown](https://github.com/remarkjs/remark/blob/99179c6745a2173d07d5c3b46bad7df767e1989d/packages/remark-parse/lib/index.js#L15)

the definition of `fromMarkdown` is from [mdast-util-from-markdown](https://github.com/syntax-tree/mdast-util-from-markdown/):

https://github.com/syntax-tree/mdast-util-from-markdown/blob/77208c8d1bfaf33f4024ce0b90e640178322e7d1/dev/lib/index.js#L105

That's all I found **until now**.

**Comment by zhyd1997** [comment]
**Update**: `fromMarkdown` relies on [parse](https://github.com/syntax-tree/mdast-util-from-markdown/blob/05875cde264253f0d6a725791f10f55eb8d8c267/dev/lib/index.js#L87), maybe the deeper cause is related to this issue from [micromark](https://github.com/micromark/micromark/issues/114).

**Comment by wooorm** [comment]
I don’t know enough about everything here, but the main thing on the `<p>` being there sounds like the rule of interleaving is not respected: https://mdxjs.com/docs/what-is-mdx/#interleaving. Follow that rule, and it is good.

**Comment by melanieseltzer** [comment]
Thanks @wooorm, make sense 👍  

In my case, it was because I have my IDE set to run Prettier on save, and text was getting forced onto a new line due to props bloating the line length. 

Getting around it in my stories with curly braces:

```js
<Heading prop="asdf" anotherProp="asdf">
  {"Some text"}
</Heading>
```

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
