### ISSUE TITLE
Type of BaseAnnotations<TFramework, TArgs> seems broken in 6.5.*

### ISSUE THREAD

**Issue by mathias-falkenberg** [storybookjs/storybook#18941]
**Description of the bug**
After trying to upgrade from version 6.4.22 to the latest (currently 6.5.10) my stories no longer compile due to a change in the signature of the BaseAnnotations type. Specifically, I have a decorator like this:

```
MyStory.decorators = [
   (story: Story<MyProps>, context: StoryContext<ReactFramework, MyProps>) => { 
      ...
   }
];
```
This compiles and runs correctly in previous versions, but now causes a compilation error since the signature of `decorators` has changed from `decorators?: DecoratorFunction<TFramework, TArgs>[];` to `decorators?: DecoratorFunction<TFramework, Args>`

> error TS2322: Type '(story: Story<MyProps>, context: StoryContext<ReactFramework, MyProps>) => JSX.Element' is not assignable to type 'DecoratorFunction<ReactFramework, Args>'.
>   Types of parameters 'context' and 'c' are incompatible.
>     Type 'StoryContext<ReactFramework, Args>' is not assignable to type 'StoryContext<ReactFramework, MyProps>'.
>       Type 'StoryContext<ReactFramework, Args>' is not assignable to type '{ component?: ComponentType<any> | undefined; subcomponents?: Record<string, ComponentType<any>> | undefined; parameters: Parameters; initialArgs: MyProps; argTypes: StrictArgTypes<...>; }'.
>         Types of property 'initialArgs' are incompatible.
>           Type 'Args' is missing the following properties from type 'MyProps': propA, propB

**System**
OS: Windows 10 10.0.18363
CPU: (12) x64 Intel(R) Xeon(R) W-10855M CPU @ 2.80GHz
**Binaries**
Node: 16.13.2 - C:\nvm\nodejs\node.EXE
npm: 8.1.2 - C:\nvm\nodejs\npm.CMD
**Browsers**
Edge: Spartan (44.18362.1593.0)
**npmPackages**
@storybook/addon-a11y: 6.4.22 => 6.4.22
@storybook/addon-docs: 6.4.22 => 6.4.22
@storybook/addon-essentials: 6.4.22 => 6.4.22
@storybook/addon-links: 6.4.22 => 6.4.22
@storybook/addons: 6.4.22 => 6.4.22
@storybook/react: 6.4.22 => 6.4.22

**Comment by vanessayuenn** [comment]
In attempt to clean up old issue, I will be closing this one. We've made lots of improvements in Storybook since 7.0 so it's quite likely that this issue has been resolved already. If this is still a problem, please open a new issue with reproduction steps for 7.x version. Thank you!
