### ISSUE TITLE
Addon Docs ArgsTable assigns an object control to Vue events 

### ISSUE THREAD

**Issue by dwightjack** [storybookjs/storybook#18953]
**Describe the bug**

In a Vue2 project, if a component has an event emitter, that even shows on the ArgsTable with an object control. My understanding is that it shouldn't show any control.

Screenshot:

<img width="636" alt="image" src="https://user-images.githubusercontent.com/104721/185305853-c9f62aa5-af40-468b-b213-4957e056350f.png">

**To Reproduce**

See this demo repository (default installation of storybook in a Vue2 project generated with vue-cli) and navigate to the button story: https://github.com/dwightjack/demo-vue2-storybook

**System**

Environment Info:

  System:
    OS: macOS 12.5
    CPU: (4) x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
  Binaries:
    Node: 16.13.1 - ~/Library/Caches/fnm_multishells/38998_1660802321945/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 8.1.2 - ~/Library/Caches/fnm_multishells/38998_1660802321945/bin/npm
  Browsers:
    Chrome: 104.0.5112.79
    Firefox: 103.0.2
    Safari: 15.6
  npmPackages:
    @storybook/addon-actions: ^6.5.10 => 6.5.10
    @storybook/addon-essentials: ^6.5.10 => 6.5.10
    @storybook/addon-interactions: ^6.5.10 => 6.5.10
    @storybook/addon-links: ^6.5.10 => 6.5.10
    @storybook/builder-webpack5: ^6.5.10 => 6.5.10
    @storybook/manager-webpack5: ^6.5.10 => 6.5.10
    @storybook/testing-library: ^0.0.13 => 0.0.13
    @storybook/vue: ^6.5.10 => 6.5.10

**Additional context**

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).

**Comment by FlorianManeyrol** [comment]
It also appears on storybook 7.5 (with vue3).
If you remove "on" the control is a button with "set object".
"click" => button with "set object"
"onClick" => mock object
