### ISSUE TITLE
Warning when using angular 14 with sb 6.5.10, public-api.ts is part of the TypeScript compilation but it's unused. WARN Add only entry points to the 'files' or 'include' properties in your tsconfig.

### ISSUE THREAD

**Issue by mukundkatpatal** [storybookjs/storybook#18954]
**Describe the bug**
After upgrading the existing repo from 13 to 14, started getting this warning for almost every ts file. The storybook is building, but cant figure out what I am doing wrong in the tsconfig file.

**To Reproduce**
after npm install, please fire below in the repo [here](https://github.com/mukundkatpatal/ng14-with-sb)
`ng run my-ng-app:build-storybook`

and then I get the warnings like 
my-ng-app/projects/ng-loader/src/lib/public-api.ts is part of the TypeScript compilation but it's unused.
WARN Add only entry points to the 'files' or 'include' properties in your tsconfig.

**System**
Please paste the results of `npx sb@next info` here.
Need to install the following packages:
  sb@6.5.0-rc.1
Need to install the following packages:
  sb@6.5.0-rc.1
Ok to proceed? (y) y
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.

Environment Info:

  System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.13.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (102.0.1245.33)
  npmPackages:
    @storybook/addon-actions: ^6.5.10 => 6.5.10
    @storybook/addon-essentials: ^6.5.10 => 6.5.10
    @storybook/addon-interactions: ^6.5.10 => 6.5.10
    @storybook/addon-links: ^6.5.10 => 6.5.10
    @storybook/angular: ^6.5.10 => 6.5.10
    @storybook/builder-webpack5: ^6.5.10 => 6.5.10
    @storybook/manager-webpack5: ^6.5.10 => 6.5.10
    @storybook/testing-library: ^0.0.13 => 0.0.13

**Additional context**
I have a library project projects\ng-loader and most of the stories are there.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
