### ISSUE TITLE
Online Documentation not working

### ISSUE THREAD

**Issue by stevenbriscoeca** [storybookjs/storybook#18967]
**Describe the bug**
I cannot access sections of the doc : 
![storybook-doc](https://user-images.githubusercontent.com/3018441/185655831-1b6eafa8-18a2-43dc-859e-881419e4af70.gif)

**To Reproduce**
Go on website, click links.

**Additional context**
This is what I see in the console. I am in a bank corporation setting so maybe my chrome has heavier security policies. On my phone it works
![image](https://user-images.githubusercontent.com/3018441/185654985-1a4bd559-a254-4204-95ca-07669a17e416.png)

**Comment by zhyd1997** [comment]
It works for me, both PC and phone.

Try to refresh the page.

**Comment by stevenbriscoeca** [comment]
> It works for me, both PC and phone.
> 
> Try to refresh the page.

I hard refreshed, it still doesn't work
![image](https://user-images.githubusercontent.com/3018441/185656732-07fa4b68-a03d-4e4a-9884-7b7c02d61221.png)

**Comment by zhyd1997** [comment]
How about the 3rd refresh option 👀

**Comment by stevenbriscoeca** [comment]
Yep, that's what I did. It works on my phone so much hunch is that it's a problem that my chrome as additional security checks when looking at webpages. And there seems to be an security issue with CORS. so probably it doesn't pass that check or something.

**Comment by zhyd1997** [comment]
So it's possible to try open the website in incognito mode?

**Comment by stevenbriscoeca** [comment]
yes and it still doesn't work in incognito

**Comment by zhyd1997** [comment]
What's your Chrome version?

**Comment by stevenbriscoeca** [comment]
Version 104.0.5112.102

**Comment by zhyd1997** [comment]
Interesting CORS issue.

**Comment by stevenbriscoeca** [comment]
I installed firefox just now and its working there, so prob a additional security setting added onto chrome from my organisation I'm guessing here

**Comment by stevenbriscoeca** [comment]
now all of a sudden I get the same error in firefox

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
