### ISSUE TITLE
@storybook/addon-storyshots is incompatible with storyStoreV7 option

### ISSUE THREAD

**Issue by matthew-dean** [storybookjs/storybook#18994]
I just wanted to document this in case someone else comes across this.

I updated a number of things in my Storybook setup, and the Storyshots addon kept producing this error:
```
Your test suite must contain at least one test.
```
My number of tests hadn't changed, and no Storyshots settings had changed. I _finally_ tracked this down to the `storyStoreV7: true` change I had made. Once I commented it out, then Storyshots worked again immediately.

**Comment by itsPrajapat** [comment]
I want to work on this but How to install node modules folder as package.json file is not there in the project. Please help me

**Comment by shilman** [comment]
This is a known limitation and has been documented here:

https://github.com/storybookjs/storybook/blob/2d5e11aae090df3541aa65231ed87da21f9abc34/MIGRATION.md#L2252-L2268
