### ISSUE TITLE
Support for Vue 2.7

### ISSUE THREAD

**Issue by vate** [storybookjs/storybook#19014]
**Is your feature request related to a problem? Please describe**
While upgrading my project from Vue 2.6 to the recent vue 2.7 I found that the component compilation is not done correctly in storybook because the supported version is Vue 2.6.12

https://github.com/storybookjs/storybook/blob/3b441bf002b8c8e427310a55e66fbaa3beeee557/code/renderers/vue/package.json#L67

Vue 2.7 introduces some important changes, for example the ability to import composition API methods without the need of the `@vue/composition-api` plugin. The result now with storybook is that in components that use the new vue 2.7 features cannot work with vue 2.6

**Describe the solution you'd like**
Be able to create a storybook with components based on vue 2.7

**Describe alternatives you've considered**
Probably a switch in the configuration to be able to use the 2.7 version. I don't think using the storybook/vue3 version will help in this case

**Are you able to assist to bring the feature to reality?**
No, unfortunately my knowledge of the core code of storybook is very limited

**Additional context**
For example, before, in vue 2.6 I imported  `computed` for composition API use this way: 

```js
import { computed, defineComponent } from "@vue/composition-api";
```

But in vue 2.7 you can do it directly from vue

```js
import { computed, defineComponent } from "vue";
```

In the current setup this causes the vue renderer in storybook to yoels errors of this type: `export 'computed' was not found in 'vue'`

**Comment by shilman** [comment]
Hi @vate! `^2.6.12` is a range specifier and `2.7.x` matches that range specifier, so I added Storybook to a 2.7.10 project and it appears to work fine. If you run into specific issues getting SB to work with 2.7, please file bugs here. Closing this for now, but please let me know if I missed something.
