### ISSUE TITLE
Fails to use Storybook 7 on Windows

### ISSUE THREAD

**Issue by Delagen** [storybookjs/storybook#19020]
**Describe the bug**

**To Reproduce**
Create project using latest version of Storybook 7 on Windows
Start building (I tried via Angular-Cli and received ENOENT error when spawning CompoDoc via npx

Described in !19019

**Comment by shilman** [comment]
Egads!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-alpha.33 containing PR #19019 that references this issue. Upgrade today to the `@future` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
