### ISSUE TITLE
--no-version-updates CI flag bust manager webpack5 cache

### ISSUE THREAD

**Issue by davincho** [storybookjs/storybook#19027]
**Describe the bug**

The CLI option`--no-version-updates` defined in https://github.com/storybookjs/storybook/blob/v6.5.10/lib/core-common/src/types.ts#L205 makes [this line](https://github.com/storybookjs/storybook/blob/v6.5.10/lib/core-server/src/build-dev.ts#L37-L38) to resolve with `{ success: false, data: {}, time: Date.now() }` which causes the cache config comparison in https://github.com/storybookjs/storybook/blob/v6.5.10/lib/manager-webpack5/src/utils/manager-cache.ts#L26 to fail all the time - `Date.now()` is not idempotent obviously.
This means that one will get consistently "Ignoring cached manager due to change in manager config" when running `start-storybook --no-version-updates`

**To Reproduce**

Minimal reproduction: https://github.com/davincho/storybook-manager-cache-bug-repro
Codesandbox Project: https://codesandbox.io/p/github/davincho/storybook-manager-cache-bug-repro/main 

Every consecutive run of our storybook will behave the following way

| yarn storybook:good | yarn storybook:wrong |
|-------------------------|----------------------------|
| <img width="479" alt="image" src="https://user-images.githubusercontent.com/2635143/186856983-6ec50888-8ecb-4882-87dc-80065ebb9477.png"> | <img width="568" alt="image" src="https://user-images.githubusercontent.com/2635143/186857853-701235d2-f963-40d0-b0b7-638bf769d9d1.png"> |

**System**
Please paste the results of `npx sb@next info` here.

```
Environment Info:

  System:
    OS: Linux 5.4 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (4) x64 AMD EPYC
  Binaries:
    Node: 16.16.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /opt/pitcher/bin/yarn
    npm: 8.11.0 - /opt/pitcher/bin/npm
  npmPackages:
    @storybook/addon-actions: ^6.5.10 => 6.5.10 
    @storybook/addon-essentials: ^6.5.10 => 6.5.10 
    @storybook/addon-interactions: ^6.5.10 => 6.5.10 
    @storybook/addon-links: ^6.5.10 => 6.5.10 
    @storybook/builder-webpack5: ^6.5.10 => 6.5.10 
    @storybook/manager-webpack5: ^6.5.10 => 6.5.10 
    @storybook/react: ^6.5.10 => 6.5.10 
    @storybook/testing-library: 0.0.13 => 0.0.13 
```

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).

We're no longer caching the manager in v7 so I don't think this applies anymore.
