### ISSUE TITLE
6.x.x: Add TS 4.8 support

### ISSUE THREAD

**Issue by jlowcs** [storybookjs/storybook#19050]
**Is your feature request related to a problem? Please describe**
Type checking currently fails with Typescript [4.8.2](https://devblogs.microsoft.com/typescript/announcing-typescript-4-8/)

**Describe the solution you'd like**
Update the types so that the library can be used with Typescript 4.8.2

**Are you able to assist to bring the feature to reality?**
I'm missing some context as to where those types should be updated.

**Additional context**

Error:
```
node_modules/@storybook/components/dist/ts3.9/_modules/@popperjs-core-lib-types.d.ts:123:34 - error TS2344: Type 'Options' does not satisfy the constraint 'Obj'.

123     fn: (arg0: ModifierArguments<Options>) => State | void;
                                     ~~~~~~~

  node_modules/@storybook/components/dist/ts3.9/_modules/@popperjs-core-lib-types.d.ts:117:36
    117 export declare type Modifier<Name, Options> = {
                                           ~~~~~~~
    This type parameter might need an `extends Obj` constraint.

node_modules/@storybook/components/dist/ts3.9/_modules/@popperjs-core-lib-types.d.ts:124:39 - error TS2344: Type 'Options' does not satisfy the constraint 'Obj'.

124     effect?: (arg0: ModifierArguments<Options>) => (() => void) | void;
                                          ~~~~~~~

  node_modules/@storybook/components/dist/ts3.9/_modules/@popperjs-core-lib-types.d.ts:117:36
    117 export declare type Modifier<Name, Options> = {
                                           ~~~~~~~
    This type parameter might need an `extends Obj` constraint.
```

The typing issues are fixed by adding an `extends Obj` in the `@popperjs-core-lib-types.d.ts` file
```ts
export declare type Modifier<Name, Options extends Obj> = {
// ...
```

**Comment by jlowcs** [comment]
Looks like those types are coming from [here](https://github.com/floating-ui/floating-ui/blob/v2.x/src/types.js#L135), which might be tricky to update.

**Comment by jlowcs** [comment]
So maybe updating `@popperjs/core` would do the trick?

**Comment by drewbrend** [comment]
Yes, I think upgrading would do the trick.  I just ran into this as well and came to log this exact same bug.  Thanks!

**Comment by davidmh** [comment]
In case anyone else is being blocked by this issue, I solved it by patching the package post-install with [patch-package([https://www.npmjs.com/package/patch-package):

`patches/@storybook+components+6.5.12.patch`

```patch
diff --git a/node_modules/@storybook/components/dist/ts3.9/_modules/@popperjs-core-lib-types.d.ts b/node_modules/@storybook/components/dist/ts3.9/_modules/@popperjs-core-lib-types.d.ts
index 3a67cf6..2616382 100644
--- a/node_modules/@storybook/components/dist/ts3.9/_modules/@popperjs-core-lib-types.d.ts
+++ b/node_modules/@storybook/components/dist/ts3.9/_modules/@popperjs-core-lib-types.d.ts
@@ -114,7 +114,7 @@ export declare type ModifierArguments<Options extends Obj> = {
     options: Partial<Options>;
     name: string;
 };
-export declare type Modifier<Name, Options> = {
+export declare type Modifier<Name, Options extends Obj> = {
     name: Name;
     enabled: boolean;
     phase: ModifierPhases;
```

**Comment by AndrewLeedham** [comment]
> So maybe updating @popperjs/core to the latest v2 minor would do the trick?

Had a little look at this, and it seems `@storybook/components` depends on `react-popper-tooltip`, which depends on `@popperjs/core`. `react-popper-tooltip` is now on 4.x, and `@storybook/components` is using 3.x, meaning the implementation would need to be refactored to use the new hook model, as well as the minor being bumped over there.

I am using the patch for now, thanks @davidmh. Just thought I'd share my findings.

**Comment by vanessayuenn** [comment]
This has been covered by the 7.x releases!
