### ISSUE TITLE
Components are not being rendered (vite + vue3 + tsx)

### ISSUE THREAD

**Issue by chelentos** [storybookjs/storybook#19056]
**Describe the bug**
Trying to get things work with Vite + Vue 3 + components in tsx, but components are not being rendered. Though setup function of component runs.
![image](https://user-images.githubusercontent.com/21958075/187403924-213698c5-f78e-42cb-81c3-1c0bb9482d80.png)

**To Reproduce**
You can clone or watch my repo(couldn't make a repro with sb@next repro) - https://github.com/chelentos/pet-1/blob/master/src/components/button/button.stories.tsx.

**System**
  System:
    OS: Windows 10 10.0.19043
    CPU: (6) x64 Intel(R) Core(TM) i5-9600KF CPU @ 3.70GHz
  Binaries:
    Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 104.0.5112.102
    Edge: Spartan (44.19041.1266.0), Chromium (104.0.1293.70)
  npmPackages:
    @storybook/addon-actions: ^6.5.10 => 6.5.10
    @storybook/addon-essentials: ^6.5.10 => 6.5.10
    @storybook/addon-interactions: ^6.5.10 => 6.5.10
    @storybook/addon-links: ^6.5.10 => 6.5.10
    @storybook/builder-vite: ^0.2.2 => 0.2.2
    @storybook/testing-library: ^0.0.13 => 0.0.13
    @storybook/vue3: ^6.5.10 => 6.5.10

**Additional context**
Code of the component:
```js
import { defineComponent, PropType, VNodeChild } from 'vue'

import styles from './button.module.css'

export enum ButtonVariant {
    primary = 'primary',
    secondary = 'secondary',
    ghost = 'ghost',
}

export interface ButtonProps {
    label?: string
    variant: ButtonVariant
}

const Button = defineComponent({
    name: 'Button',
    props: {
        label: {
            type: String as PropType<ButtonProps['label']>,
            required: false,
            default: '',
            readonly: true,
        },
        variant: {
            type: String as PropType<ButtonProps['variant']>,
            required: true,
            default: ButtonVariant.primary,
            readonly: true,
        },
    },
    setup(props, { slots }) {
        console.log({ props })

        const renderSlot: (slots: any) => VNodeChild = (slots) => {
            if (typeof slots.default === 'function') {
                return slots.default()
            }
    
            return slots.default
        }


        return () => (
            <button class={styles.button}>
                <span class={styles.buttonText}>{renderSlot(slots)}</span>
            </button>
        )
    }
})

export { Button }
```

Code of the story:
```js
import { Button, ButtonProps, ButtonVariant } from "./button"
import { Meta, Story } from "@storybook/vue3"

export default {
    title: 'Button',
    component: Button,
} as Meta<typeof Button>

export const Primary: Story<ButtonProps> = (args) => ({
    components: { Button },
    setup() {
        return { args };
      },
    template: '<Button v-bind="args">{{args.label}}</Button>'
})

const primaryProps: ButtonProps = {
    variant: ButtonVariant.primary,
    label: 'Button',
}

Primary.args = primaryProps
```

Also when clicking remount, i'm getting this:
![image](https://user-images.githubusercontent.com/21958075/187406984-fb839399-8acf-495c-8c94-165976c5434a.png)

**Comment by mockingjet** [comment]
any workarounds on this? This is a serious bug. 😢

**Comment by mockingjet** [comment]
I found that with `@storybook/builder-vite`, the default vite config has some react plugins

![image](https://user-images.githubusercontent.com/32839503/190959680-04c62c18-b348-4a07-8cf9-0676ddd0876d.png)

So I removed these plugin and restarted, the canvas page work.

```ts
	async viteFinal(config) {
		const idx = config.plugins.findIndex(
			(p) => Array.isArray(p) && p.some((nested) => nested.name.includes('react')),
		);
		config.plugins.splice(idx, 1);
		config.plugins.push(vueJsx());
		return config;
	}
```

However, the docs page fails: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'isBatchingLegacy')

**Comment by IanVS** [comment]
We no longer inject react plugins into other frameworks.  If you're still having this problem in the latest beta versions of 7.0, please let me know and we can re-open.
