### ISSUE TITLE
eslint migration causes unnecesary edits in `.eslintrc`

### ISSUE THREAD

**Issue by thany** [storybookjs/storybook#19076]
**Describe the bug**
After having done the eslint migration step in a clean install in an existing project, it does a lot of neccesary edits in the `.eslintrc` file. Not only that, but these edits introduce linting errors themselves.
![image](https://user-images.githubusercontent.com/152227/187880904-cd1bf210-7b2b-4199-8bc1-777fe149da6d.png)

Please only make the edits you need to do, and leave the rest of the file as-is.

**To Reproduce**
Perform the `npx storybook init` script in an existing project with eslint, with an `.eslintrc` file populated, and say yes to the eslint migration question during install.

**System**
Please paste the results of `npx sb@next info` here.
```
Need to install the following packages:
  sb@6.5.0-rc.1
Ok to proceed? (y) n
npm ERR! canceled

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\<snip>\2022-09-01T09_23_43_652Z-debug-0.log
```

**Comment by vanessayuenn** [comment]
In attempt to clean up old issue, I will be closing this one. We've made lots of improvements in Storybook since 7.0 so it's quite likely that this issue has been resolved already. If this is still a problem, please open a new issue with reproduction steps for 7.x version. Thank you!
