### ISSUE TITLE
Make it possible to save snapshots next to each story

### ISSUE THREAD

**Issue by Robin-Hoodie** [storybookjs/storybook#19128]
**Is your feature request related to a problem? Please describe**

Currently, the setup instructions read as follows:
> Create a new test file with the name Storyshots.test.js. (Or whatever the name you prefer, as long as it matches Jest's config [testMatch](http://facebook.github.io/jest/docs/en/configuration.html#testmatch-array-string)). Then add following content to it:
> ```
> import initStoryshots from '@storybook/addon-storyshots';
> 
> initStoryshots();
> ```
> That's all.
> Now run your Jest test command. (Usually, npm test.) Then you can see all of your stories are converted as Jest snapshot tests.

There are 2 problems I've noticed with this:

1. All snapshots are written to a `__snapshots__/Storyshots.test.js.snap` file. This can become a nightmare to review pretty quickly
2. As the `Storyshots.test.js` file is an arbitrary test file, it's not picked up by Jest if running a specific (set of) test file(s). E.g. running `jest foo.test.js` will not check any snapshots for `foo.stories.js`

I know this has been brought up in https://github.com/storybookjs/storybook/issues/3917 & https://github.com/storybookjs/storybook/issues/887 which both seem to be about solving problem#1 but neither of these solve problem#2 

**Describe the solution you'd like**

I assume it's possible to spend a few hours/days to configure your way around this, but to me this seems like it should be a logical default. The current default setup requires quite some googling & manual configuration to solve problem#1 & does not solve problem#2

**Comment by jonniebigodes** [comment]
The Storyshots addon is officially deprecated and will be removed in a future release of Storybook. To help with the transition process, we've created a [migration guide](https://storybook.js.org/docs/writing-tests/storyshots-migration-guide) for the available options and common use cases.
