### ISSUE TITLE
Allow using describe or test function in play function 

### ISSUE THREAD

**Issue by anhdd-kuro** [storybookjs/storybook#19148]
**Is your feature request related to a problem?

I'm writing interaction test in storybook
The problem is I want to use jest's describe or test function to separate and know what I'm testing inside play function
But for now both @storybook/jest and @storybook/testing-library don't have those functions
My interaction test file become long and hard to maintain and have to use comment to know what I'm testing

**Describe the solution you'd like**

Allow using describe in play function and some how make it easier to see it in Interactions tab instead of just showing expected 
Interactions tab may look like

```
Open modal
  user.click()
  expected(...).toBeInTheDocument()
Close modal
  user.click()
  expected(...).toBeInTheDocument()
```

instead of 

```
user.click()
expected(...).toBeInTheDocument()
expected(...).toBeInTheDocument()
user.click()
expected(...).toBeInTheDocument()
expected(...).toBeInTheDocument()
```

**Comment by DonnyVerduijn** [comment]
The real question that undoubtedly comes up, is if we should envision the concept of a story as a single test or be unopinionated about it and let users decide for themselves.
