### ISSUE TITLE
Storybook alpha 31 fails with Next.js and Typescript

### ISSUE THREAD

**Issue by DannyJoris** [storybookjs/storybook#19157]
**Describe the bug**

Storybook alpha 31 fails with Next.js and Typescript. It looks like when Storybook builds it does not recognize any TypeScript syntax. It throws errors when it encounters TypeScript syntax in Stories and React files.

This happens in our existing codebase when trying to upgrade from Storybook 6.5 to 7-alpha.31, but also when creating a Storybook + Next.js TypeScript project from scratch.

![Screen Shot 2022-09-09 at 10 38 51 AM](https://user-images.githubusercontent.com/110365/189363646-91aca112-ac7c-470d-940e-6c324f25c49e.png)

**To Reproduce**
Please create a reproduction by running `npx sb@next repro` and following the instructions. Read our [documentation](https://storybook.js.org/docs/react/contribute/how-to-reproduce) to learn more about creating reproductions.
Paste your repository and deployed reproduction here. We prioritize issues with reproductions over those without.

I created the app the following way:
- Created a Next.js app with TypeScript: `npx create-next-app@latest --ts`
- Inside the app folder I ran `npx storybook@future init`
- Ran `npm run storybook`
https://github.com/DannyJoris/storybook-alpha-nextjs-typescript

**System**
Please paste the results of `npx sb@next info` here.

```
Environment Info:

  System:
    OS: macOS 12.3.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
  Browsers:
    Chrome: 105.0.5195.102
    Firefox: 104.0.1
    Safari: 15.4
  npmPackages:
    @storybook/addon-essentials: ^7.0.0-alpha.31 => 7.0.0-alpha.31
    @storybook/addon-interactions: ^7.0.0-alpha.31 => 7.0.0-alpha.31
    @storybook/addon-links: ^7.0.0-alpha.31 => 7.0.0-alpha.31
    @storybook/react: ^7.0.0-alpha.31 => 7.0.0-alpha.31
    @storybook/react-webpack5: ^7.0.0-alpha.31 => 7.0.0-alpha.31
    @storybook/testing-library: ^0.0.13 => 0.0.13
```

**Additional context**

**Comment by valentinpalkovic** [comment]
Please reopen if the issue is not resolved.

**Comment by DannyJoris** [comment]
@valentinpalkovic Sorry for the late reply, but yes, that works. Thank you!
