### ISSUE TITLE
Addon-docs: DocsPage story sorting broken in V7

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#19163]
Stories are sorted alphabetically on DocsPage, even when they are sorted correctly in the sidebar.

See reproduction in the addon-docs generic stories in which `Another` is sorted before `Basic`:

https://github.com/storybookjs/storybook/pull/19162/files#diff-c30e0cfbc01713e2dac4527bedfef88930352aa03330dd0771139689f2c1010b

**Comment by mogamogua** [comment]
I wonder if this fix has been release through regular version.
I'm using storybook 7.3.1, but storybook sidebar's category, group's ordering is not sorted by the `sortStory.order` :/
