### ISSUE TITLE
Wrong links to Interractions documentation

### ISSUE THREAD

**Issue by vitalii-bulyzhyn** [storybookjs/storybook#19171]
**Describe the bug**
Link on the app send us to [here](https://github.com/storybookjs/storybook/blob/next/addons/interactions/README.md), but the right path is [this one](https://github.com/storybookjs/storybook/blob/next/code/addons/interactions/README.md)

**Comment by jonniebigodes** [comment]
@vitalii-bulyzhyn, thanks for taking the time to open up the issue. We're aware of the fact that the addon is pointing to the wrong place in the documentation. Hope you don't mind, but I'm closing this issue as it's already being tracked in #18957.

Hopefully, a patch will be up soon addressing both issues.


Hope you have a great week.

Stay safe
