### ISSUE TITLE
Presets: Support recursive addon imports

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#19176]
Currently, addons can reference other addons by name. For example, `addon-essentials` has the following structure:

```
export const addons = async (existing) => ([...existing, '@storybook/addon-actions', ...]);
```

This matches how users configure addons in their `.storybook/main.js` file. However, it presents problems when it comes to package management / module resolution / hoisting, since the dependencies are implicit. If instead we supported the ability to reference other addons directly, this would mean that an addon's dependencies are explicit and we wouldn't have to play any games with module resolution.

We should update Storybook's preset mechanism and port existing addons to this structure:

```
export const addons = async (existing) => ([...existing, await import('@storybook/addon-actions'), ...]);
```

We wouldn't need to force users to adopt this in `main.js`, but it would be useful for addons that make use of other addons (e.g. `addon-essentials`).

**Comment by IanVS** [comment]
👍  This will help us to improve support for package managers that don't hoist, like pnpm and yarn pnp without some of the games we currently play like using `require.resolve()` to get an absolute path (which also always resolves to the cjs version, even if esm could be used).

**Comment by IanVS** [comment]
Is this something that I could start working on, or do you envision it being something with sharp edges, @shilman @ndelangen?

**Comment by IanVS** [comment]
OK, I've gotten further.  I can now require the sub-addons just fine, but I think there's a fatal flaw here. I now have an array of `previewAnnotations` that is something like this:

```
{
  previewAnnotations: [
    '@storybook/react/preview',
    '@storybook/addon-links/preview',
    { parameters: [Getter] },
    { argsEnhancers: [Getter], decorators: [Getter] },
    { decorators: [Getter], parameters: [Getter] },
    { decorators: [Getter], globals: [Getter] },
    { decorators: [Getter], globals: [Getter] },
    { highlightObject: [Getter], highlightStyle: [Getter] },
    '@storybook/addon-interactions/preview',
    './src/stories/components',
    './template-stories/lib/store/preview.ts',
    './template-stories/addons/toolbars/preview.ts'
  ]
}
```

Now, I need to get that into the preview.  But since there are objects with functions, I guess I can't just serialize it straight into the virtual module in the preview builder.  The strings can be `import`ed as before, but what can I do with the sub-addons after I've imported them?  😕

**Comment by shilman** [comment]
Hurrah!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-alpha.49 containing PR #19689 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
@IanVS @tmeasday is it correct that we won't pursue this issue now that @IanVS 's PR has been merged/released, and if we do enhance it, it will be a different approach with an `addons` field in `preview.js`? In other words, should I leave this closed?

**Comment by tmeasday** [comment]
That sounds right to me @shilman
