### ISSUE TITLE
Vue3+Typescript Controls Not Generating from Types

### ISSUE THREAD

**Issue by jnarowski** [storybookjs/storybook#19233]
**Describe the bug**
The controls are not populating with the info from our types. We do not want to define all of our controls twice (once in Types and once in Storybook). The only way we can justify storybook for Vue3/Typescript is if it automatically infers the controls and control options from the Types in the component. 

https://jmp.sh/7Wp13yz

**To Reproduce**
[Here is the code sandbox link to reproduce
](https://codesandbox.io/p/github/jnarowski/vue3-vite-typescript-storybook/csb-to6qbp/draft/keen-tdd?file=%2FREADME.md&workspace=%257B%2522activeFileId%2522%253A%2522cl7qc3xho0000lphy2fjq69u9%2522%252C%2522openFiles%2522%253A%255B%2522%252FREADME.md%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522sidekickItems%2522%253A%255B%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522key%2522%253A%2522cl7qc4hin00a83b6k78c9wkik%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522key%2522%253A%2522cl7qc4gqc005i3b6khu6ppvj1%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D)

**System**
  System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 18.7.0 - /opt/homebrew/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.15.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 105.0.5195.125
    Firefox: 101.0.1
    Safari: 16.0
  npmPackages:
    @storybook/addon-actions: ^6.5.9 => 6.5.9
    @storybook/addon-essentials: ^6.5.9 => 6.5.9
    @storybook/addon-interactions: ^6.5.9 => 6.5.9
    @storybook/addon-links: ^6.5.9 => 6.5.9
    @storybook/builder-vite: ^0.2.2 => 0.2.2
    @storybook/testing-library: ^0.0.13 => 0.0.13
    @storybook/vue3: ^6.5.9 => 6.5.9

**Additional context**

**Comment by tdekoning** [comment]
Can second this, Storybook doesn't auto-generate controls for vue3 components. It only honors the explicitly supplied arguments.

**Comment by kasperpeulen** [comment]
This is fixed right @chakAs3 ?

**Comment by larsrickert** [comment]
Hey, this will be fixed with #22285

**Comment by larsrickert** [comment]
Fixed with #22285 in version 8
