### ISSUE TITLE
new version opens browser despite "BROWSER=none"

### ISSUE THREAD

**Issue by bebbi** [storybookjs/storybook#19262]
**Describe the bug**

Running this package.json line:
```
"storybook": "BROWSER=none start-storybook -p 6006 -c .storybook",
```

always avoided opening a default browser window/tab up to `^6.3.8`, but after upgrading to `^6.5.12`, storybook consistently opens a new default browser tab again everytime it's run.

**To Reproduce**
> Please create a reproduction by running `npx sb@next repro` and following the instructions.

I've issued that command & read the docs

> If everything worked as it should, you should have a fully functional Storybook set up in your local environment.

but ended up with a package.json missing storybook, so skipping this step.

```
  "dependencies": {
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-scripts": "5.0.1",
    "web-vitals": "^2.1.4"
  },
```

**System**
Please paste the results of `npx sb@next info` here.

  System:
    OS: macOS 12.6
    CPU: ...
  Binaries:
    Node: 16.17.0 - ~/.volta/tools/image/node/16.17.0/bin/node
    Yarn: 3.2.3 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
    npm: 8.15.0 - ~/.volta/tools/image/node/16.17.0/bin/npm
  Browsers:
    Chrome: 105.0.5195.125
    Firefox: 104.0.2
    Safari: 16.0

**Additional context**

**Comment by Tim-arts** [comment]
https://github.com/storybookjs/storybook/discussions/12186

**Comment by IanVS** [comment]
That's right, you can pass `--no-open` to keep the browser from opening.
