### ISSUE TITLE
vulnerability in got 9.6.0 package used by storybook cli

### ISSUE THREAD

**Issue by brodarte-gfm** [storybookjs/storybook#19274]
**Describe the bug**
Not exactly a bug, but there's an Open Redirect vulnerability in the version of the got package (9.6.0) used by storybook cli. Details here: https://security.snyk.io/vuln/SNYK-JS-GOT-2932019

**To Reproduce**
running npm ls got or yarn why got shows the origin of the dependency as sb / storybook cli
<img width="333" alt="Screen Shot 2022-09-27 at 3 35 01 PM" src="https://user-images.githubusercontent.com/105670039/192650578-f6078185-06dd-4399-94f9-a19d04729e19.png">

**Comment by dr-bizz** [comment]
Any update on when this will be updated?

**Comment by shilman** [comment]
This is fixed in 7.0. Migration guide: https://storybook.js.org/migration-guides/7.0
