### ISSUE TITLE
Fix your examples

### ISSUE THREAD

**Issue by tomeof** [storybookjs/storybook#19285]
All i wanted was to run locally your ts-react example. I sampled some of your countless braches and i got back a bouquet of errors. At some point i got an error python2 was not found in PATH. WHY ON EARTH python is needed for a frontend storybook react example??? Are your examples working? Do you even check if they are working? If your examples are not working then why you publish them?

**Comment by valentinpalkovic** [comment]
@tomeof Thank you for opening up this issue. Could you provide a reproduction repository or tell us which commands you have executed?

**Comment by ndelangen** [comment]
We ended up removing the examples, and replace them with sandboxes that are generated as they are needed.

I guess deleting stuff is 1 way of fixing them?

Thanks for reporting, have an awesome day!
