### ISSUE TITLE
Wrong tab selected by default 

### ISSUE THREAD

**Issue by David-Trejo** [storybookjs/storybook#19282]
**Describe the bug**
My intention of my code modifications were to rearrange the order of the Tabs in Storybook. I want the Docs' tab to be the first item and be the selected item upon loading the page follow by the Canvas' tab as the second item. 

Upon loading the storybook page, the Accordions story is chosen by default. However, the Canvas tab is selected rather than the Docs tab. The bug only seems to be occurring to the first story. If I select other stories listed in the file tree, they all default to the Docs tab. In addition, if were to click back on the first story it will default to Docs tab. 

[![Image from Gyazo](https://i.gyazo.com/e8a40d22a1f9d7f74d4aa4ed14351086.gif)](https://gyazo.com/e8a40d22a1f9d7f74d4aa4ed14351086)

**To Reproduce**
In my `preview.js`, I have the following code.

```javascript
import React from "react";
import { ThemeProvider, theme } from "../src";
import { addParameters } from '@storybook/react';

addParameters({
  viewMode: "docs",
  previewTabs: {
    canvas: {
      index: 999
    }
  }
});

export const decorators = [
  Story => {
    return (
      <ThemeProvider theme={theme}>
        <Story />
      </ThemeProvider>
    );
  },
];
```

**System**
```
Environment Info:
  System:
    OS: macOS 12.6
    CPU: (10) x64 Apple M1 Pro
  Binaries:
    Node: 12.22.7 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 6.14.15 - /usr/local/bin/npm
  Browsers:
    Chrome: 106.0.5249.61
    Firefox: 105.0.1
    Safari: 15.6.1
```
**Additional context**

**Comment by sysa20** [comment]
I can do that if you assign me that

**Comment by shilman** [comment]
The Docs/Canvas tabs are going away in 7.0 which is slated for release this week or next. Closing this!

- More info: https://storybook.js.org/blog/storybook-7-docs/
- Migration info: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#70-docs-changes
