### ISSUE TITLE
Stories are not loading after upgrade from 6.4 to 6.5

### ISSUE THREAD

**Issue by roofs-runner** [storybookjs/storybook#19335]
**Describe the bug**
After upgrading Storybook, my monorepo stories are not loading.
The Storybook starts fine but in browser console, I've got an error:

```
Unable to load story '*':
Error: Couldn't find any stories in your Storybook.
```

**To Reproduce**
Here is my `main.js`

```
module.exports = {
  core: {
    builder: 'webpack5',
  },
  stories: ["../../../**/*.(story|stories).@(tsx|mdx|js)"],
  addons: [
    "@storybook/addon-essentials"
  ],
  staticDirs: ['../fonts/'],
  ...
};
```

And here is my file structure 
<img width="285" alt="Screen Shot 2022-10-03 at 20 10 04" src="https://user-images.githubusercontent.com/7910948/193637872-919faa37-16b4-4369-81ef-33c1227f79c9.png">

There are no other errors or messages.
This path is validated by picomatch. Plus, it worked in the previous version 6.4.x

**Comment by ArmanNisch** [comment]
I have a similar issue when attempting to upgrade from storybook v6.4.22 to any version of storybook 5.x (I have tested several versions). I always get the following error: 

```
99% done plugins webpack-hot-middlewarewebpack built preview baa3538ce020023add69 in 16047ms
WARN Force closed manager build
ModuleParseError: Module parse failed: Unexpected token (113:8)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|         // Note: In dev, we call onHeadRendered twice( in FireCallbackInEffect and after mutualution observer dectects initail render into hiddenRoot) this is for hot reloading
|         // In Prod we only call onHeadRendered in FireCallbackInEffect to render to head
>         <FireCallbackInEffect callback={onHeadRendered}>
|           <StaticQueryContext.Provider value={staticQueryResults}>
|             <LocationProvider>

```

**Comment by samkahchiin** [comment]
@roofs-runner  Can you share how do you solve this
