### ISSUE TITLE
ColorPalette type fails to accept children. Type '{ children: Element; }' has no properties in common with type 'IntrinsicAttributes'.

### ISSUE THREAD

**Issue by mlp73** [storybookjs/storybook#19359]
**Describe the bug**
On react 18, when using <ColorPalette></ColorPalette> from '@storybook/addon-docs'
as described in this example: https://storybook.js.org/docs/react/writing-docs/doc-block-colorpalette

Typecheck with fail because of providing children to ColorPalette:
Type '{ children: Element; }' has no properties in common with type 'IntrinsicAttributes'.

**To Reproduce**
Running the provided example on react 18.

**Additional context**
As described in the breaking change section, 1) removal of implicit children:
https://blog.logrocket.com/upgrading-react-18-typescript/
ColorPalette is typed as FunctionalComponent and thereby does not accept children.

Details about the merged pull request in react types:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/59751

**Comment by ptim** [comment]
Maybe related (though not to ColorPalette)

I get the same error on `Unstyled`:

```tsx
import { Unstyled } from '@storybook/addon-docs';

type WithThemeProps = {
  children?: React.ReactNode;
};
export const Themed = ({ children }: WithThemeProps) => (
  // @ts-expect-error Type '{ children: Element; }' has no properties in common with type 'IntrinsicAttributes'.
  <Unstyled>
    <ChakraProvider theme={theme}>{children}</ChakraProvider>
  </Unstyled>
);
```

```
Environment Info:

  System:
    OS: macOS 13.0.1
    CPU: (10) x64 Apple M1 Pro
  Binaries:
    Node: 18.12.1 - ~/Library/Caches/fnm_multishells/99647_1677464869503/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.4.0 - /opt/homebrew/bin/npm
  Browsers:
    Firefox: 110.0
    Safari: 16.1
  npmPackages:
    @storybook/addon-essentials: ^7.0.0-beta.43 => 7.0.0-beta.43
    @storybook/addon-interactions: ^7.0.0-beta.43 => 7.0.0-beta.43
    @storybook/addon-links: ^7.0.0-beta.43 => 7.0.0-beta.43
    @storybook/blocks: ^7.0.0-beta.43 => 7.0.0-beta.43
    @storybook/react: ^7.0.0-beta.43 => 7.0.0-beta.43
    @storybook/react-vite: ^7.0.0-beta.43 => 7.0.0-beta.43
    @storybook/testing-library: ^0.0.14-next.1 => 0.0.14-next.1

...

  "dependencies": {
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    ...
  },
```

**Comment by shilman** [comment]
Yowza!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-rc.10 containing PR #21803 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```
