### ISSUE TITLE
Using Webpack aliasing to mock an imported module breaks other imports

### ISSUE THREAD

**Issue by arimendelow** [storybookjs/storybook#19395]
Hi! I'm working on a project that requires mocking imports, and attempted to do so following [the docs](https://storybook.js.org/docs/react/writing-stories/build-pages-with-storybook#mocking-imports).

However, when I do this, it breaks other imports - they simply show up as `undefined`, even if they're totally unrelated.

This is very odd behavior, is there a suggested way for me to debug this?

Thanks!

**Comment by ndelangen** [comment]
MWS can only mock request, not mock modules/imports.

But you could research using webpack's alias feature?

Or investigate doing dependency injection instead, and providing the mocked module via props.
