### ISSUE TITLE
Svelte Example Components injecting global CSS

### ISSUE THREAD

**Issue by Amerlander** [storybookjs/storybook#19409]
**Describe the bug**
The example components (Button, Header, Page) are adding the CSS files trough `import './header.css';`.
The CSS is then Globally available and not scoped to the Component.

https://github.com/storybookjs/storybook/blob/c745ff687e0dd445e0b9b4b908c1dfe75b3bfa3a/code/lib/cli/rendererAssets/svelte/Header.svelte#L3

The Behavior of adding CSS through an Import is resulting in global CSS is not the Bug. Usual, most Svelte Components would not import CSS like that, and therefore I think having a Component as a sample which introduces a bad pattern and leads to side effects should be avoided.

**To Reproduce**
Every new installation of Storybook ads this behavior.

**Additional context**
There are two ways so solve that (https://github.com/sveltejs/svelte/issues/7125):
- Create a container element, add css to that and import the external css file through a precompiler like scss
- Do not import the css file, but write the CSS directly inside the component.

I think adding css into the components will be cleaner, but it will also mean duplicating the css code for svelte.

**Comment by Amerlander** [comment]
Example: Here is an Icon component, that has an unstyled SVG. But there is still some css applied, which comes from the header-css:
![image](https://user-images.githubusercontent.com/3764089/194764044-539a67a1-a89f-4e57-b41e-842492cfbc3d.png)


Also, I have a Button component, which has an Icon.
This is how it should look like and how it looks on my actual site:
![image](https://user-images.githubusercontent.com/3764089/194764485-9808bc2c-c541-4746-8f37-e5af1b8997d8.png)

And this is how the component looks like in storybook after a fresh installation of storybook:
![image](https://user-images.githubusercontent.com/3764089/194764537-ecd02842-5b6f-4f20-bbfd-f055014f027e.png)

I think storybook should not come with that behavior by default. So a novice User should not have to remove three components after installation to avoid css issues.

**Comment by shilman** [comment]
ZOMG!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.1.0-alpha.14 containing PR #22162 that references this issue. Upgrade today to the `@future` NPM tag to try it out!

```
npx sb@next upgrade --tag future
```

**Comment by shilman** [comment]
Jiminy cricket!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.10 containing PR #22162 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb@latest upgrade
```

**Comment by yannbf** [comment]
Thank you so much @Amerlander !!
