### ISSUE TITLE
Snapshot testing broken with static builds in v7

### ISSUE THREAD

**Issue by KorySchneider** [storybookjs/storybook#19423]
**Describe the bug**
Snapshot testing with `@storybook/addon-storyshots-puppeteer`, using a static storybook build and dockerized headless chrome worked with Storybook 6, breaks in Storybook 7. Resulting image diffs look like this:
![button-primary-1-diff](https://user-images.githubusercontent.com/5200816/195152571-112cb6f9-421a-4498-943d-6607fa3cff3a.png)

**To Reproduce**
The `npx sb@next repro` command kept failing to install properly, so here are the repro steps:

- Copy `storyshots.test.js` (below)
- Run docker command (below) to spin up headless chrome instance
- Build storybook, output to `storybook-static/`
- Run jest, which will pick up `storyshots.test.js`
- See that all image snapshots are of stacktrace (example above)

<details>
  <summary>Test file: storyshots.test.js</summary>

  ```
  import initStoryshots from '@storybook/addon-storyshots'; // version 7.0.0-alpha.35
  import { imageSnapshot } from '@storybook/addon-storyshots-puppeteer'; // version 7.0.0-alpha.35
  import puppeteer from 'puppeteer'; // version 3.3.0
  
  const HOST_IP = process.env.HOST_IP;
  let browser;
  
  const imageTestFn = imageSnapshot({
    storybookUrl: 'file:///opt/storybook-static',
    getCustomBrowser: async () => {
      browser = await puppeteer.connect({
        browserURL: (() => {
          // For CI env's: If running in docker inside docker, you'll need the IP address of the host
          if (HOST_IP) {
            return `http://${HOST_IP}:9222`;
          }
          return 'http://localhost:9222';
        })(),
      });
      return browser;
    },
    getScreenshotOptions: ({ context, url }) => ({
      encoding: 'base64',
      fullScreen: false,
    }),
    beforeScreenshot: async (
      page,
      { context: { kind, story, parameters }, url }
    ) => {
      await page.evaluateHandle('document.fonts.ready');
      await page.setViewport({
        deviceScaleFactor: parameters?.imageSnapshot?.deviceScaleFactor ?? 2,
        width: parameters?.imageSnapshot?.width ?? 800,
        height: parameters?.imageSnapshot?.height ?? 600,
      });
    },
  });
  
  imageTestFn.afterAll = () => {
    if (browser) browser.close();
  };
  
  initStoryshots({
    suite: 'Image Snapshots',
    test: imageTestFn,
  });
  ```
</details>

<details>
  <summary>Docker command to spin up headless chrome instance</summary>

  ```
  docker run -d --rm \
    -p 9222:3000 \
    -e "CONNECTION_TIMEOUT=600000" \
    -e "ALLOW_FILE_PROTOCOL=true" \
    -e "DEFAULT_LAUNCH_ARGS=[\"--allow-file-access-from-files\", \"--disable-web-security\"]" \
    --name chrome \
    -v "$PWD/storybook-static/:/opt/storybook-static" \
    browserless/chrome
  ```
</details>

**System**

<details>
  <summary>`npx sb@next info` output</summary>

  ```
  Environment Info:
  
    System:
      OS: macOS 12.6
      CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Binaries:
      Node: 17.7.1 - ~/.nvm/versions/node/v17.7.1/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 8.5.2 - ~/.nvm/versions/node/v17.7.1/bin/npm
    Browsers:
      Chrome: 105.0.5195.125
      Firefox: 105.0.1
      Safari: 15.6.1
    npmPackages:
      @storybook/addon-a11y: ^7.0.0-alpha.35 => 7.0.0-alpha.35
      @storybook/addon-actions: ^7.0.0-alpha.35 => 7.0.0-alpha.35
      @storybook/addon-essentials: ^7.0.0-alpha.35 => 7.0.0-alpha.35
      @storybook/addon-interactions: ^7.0.0-alpha.35 => 7.0.0-alpha.35
      @storybook/addon-links: ^7.0.0-alpha.35 => 7.0.0-alpha.35
      @storybook/addon-storyshots: ^7.0.0-alpha.35 => 7.0.0-alpha.35
      @storybook/addon-storyshots-puppeteer: ^7.0.0-alpha.35 => 7.0.0-alpha.35
      @storybook/addons: ^7.0.0-alpha.35 => 7.0.0-alpha.35
      @storybook/api: ^7.0.0-alpha.35 => 7.0.0-alpha.35
      @storybook/builder-webpack5: ^7.0.0-alpha.35 => 7.0.0-alpha.35
      @storybook/cli: 7.0.0-alpha.35 => 7.0.0-alpha.35
      @storybook/components: ^7.0.0-alpha.35 => 7.0.0-alpha.35
      @storybook/core-events: ^7.0.0-alpha.35 => 7.0.0-alpha.35
      @storybook/jest: ^0.0.10 => 0.0.10
      @storybook/manager-webpack5: ^7.0.0-alpha.10 => 7.0.0-alpha.10
      @storybook/react: ^7.0.0-alpha.35 => 7.0.0-alpha.35
      @storybook/react-webpack5: 7.0.0-alpha.35 => 7.0.0-alpha.35
      @storybook/testing-library: ^0.0.14-next.0 => 0.0.14-next.0
      @storybook/theming: ^7.0.0-alpha.35 => 7.0.0-alpha.35
  ```
</details>

**Additional context**
- Tested with `7.0.0-alpha.34` and `.35`
- Adding `return { ...indexJsonContents }` before the fetch circumvents the issue. This is how I isolated the problem.

**Comment by KorySchneider** [comment]
Update: I was adding the chrome launch flags in the wrong place -- I have updated the docker command in the original post to include these flags. Unfortunately, after adding the flags to get past the CORS issue I ran into another problem:

<img width="1680" alt="Screen Shot 2022-10-11 at 9 27 42 AM" src="https://user-images.githubusercontent.com/5200816/195147839-152d49ab-65c5-4ad9-a340-f54ef34dee66.png">

<img width="1108" alt="Screen Shot 2022-10-11 at 9 41 04 AM" src="https://user-images.githubusercontent.com/5200816/195150574-2c2250f9-4790-46e3-a3c8-9bb7cf5dd923.png">

**Comment by valentinpalkovic** [comment]
@KorySchneider Why was `npx sb@next repro`? With which framework was it failing? Can you try it once again and try to create a reproduction repository?

**Comment by ndelangen** [comment]
The future of storyshots is the test-runner:
https://storybook.js.org/docs/react/writing-tests/test-runner#page-top

And use the play function for expectations:
https://storybook.js.org/docs/react/writing-stories/play-function#page-top

We will not be making any improvement / changes to storyshots.
