### ISSUE TITLE
Docs: Add next and previous buttons to navigate documentation

### ISSUE THREAD

**Issue by asheerrizvi** [storybookjs/storybook#19474]
**Is your feature request related to a problem? Please describe**
The guides section should have buttons to navigate from the current page to the next or the previous page.

**Describe the solution you'd like**
Something like the following screenshot (from react-testing-library):

<img width="1058" alt="image" src="https://user-images.githubusercontent.com/17976252/195588700-eb6b7c8a-f514-4c65-8b47-233a2a16f6aa.png">

**Describe alternatives you've considered**
Not considered any alternatives.

**Are you able to assist to bring the feature to reality?**
Yes, if given enough context. I am new to the project so will take some time getting familiar with the code.

**Additional context**
Not required.

**Comment by saiteja2108** [comment]
hello , can you please assigned this to me .I will add this features to your code in html and for your reference see the below code . let me know about the changes to the code I have to do

<!DOCTYPE html>
<html>
<head>
<style>

a {
    text-decoration: none;
    display: inline-block;
    padding: 8px 16px;
}
a:hover {
    background-color: white;
    color: black;
}

.previous {
    background-color: black;
    color: white;
}

.next {
    background-color: black;
    color: white;
}

.round {
    border-radius: 50%;
}
</style>
</head>
<body>

<h2>Next and Previous buttons</h2>

<a href="#" class="previous round"><</a>
<a href="#" class="next round">></a>
  
</body>
</html>

**Comment by kylegach** [comment]
Hi @saiteja2108,

They meant that the website's code is not in this repository, it's in https://github.com/storybookjs/frontpage. So any issues or PRs related to the site belong there.

However, the docs pages already have a "what's next" link, _when there is a clear next step_:

![Screenshot of the "next" link on a docs page](https://user-images.githubusercontent.com/486540/195616833-8c537b53-b4af-4739-aa5c-eec8d2d6e119.png)
[Source](https://storybook.js.org/docs/react/get-started/introduction)

So it's not likely your PR would be accepted.

**Comment by saiteja2108** [comment]
Thank you for the clarification.
