### ISSUE TITLE
builder vite is webpack builder and vite export ?

### ISSUE THREAD

**Issue by Minitiai** [storybookjs/storybook#19485]
"core": {
    "builder": "@storybook/builder-vite"
  }

when i use vite and npm run storybook, The log output is as follows, actually vite import, is this reasonable ?

Version: webpack 4.46.0
Time: 6421ms
Built at: 2022/10/14 15:55:01 utc +08:00

**Comment by joshwooding** [comment]
The manager is built with webpack but the preview is built with vite. So this is normal in v6, in v7 the manager will be prebundled so only vite will be used when using the vite builder.

There's more explanation on preview vs manager here: https://storybook.js.org/docs/react/builders/overview
