### ISSUE TITLE
No documentation or way users can tell what possible values of `type` to use for controls / ArgTypes

### ISSUE THREAD

**Issue by brennancheung** [storybookjs/storybook#19517]
**Describe the bug**
There is no mention or documentation on what the possible `type` values are to expose controls for `ArgTypes`.  The documentation only shows the `radio` type.

Ex:
```javascript
{
  argTypes: {
    foo: {
      control: { type: 'WHAT_CAN_GO_HERE???' }
    }
  }
}
```

**To Reproduce**
1. Read the documentation for controls located at https://storybook.js.org/docs/react/essentials/controls.
2. Ask yourself the question, what are the other types of controls I can use?
3. Confusion

**Desired Outcome**
The documentation should either show, or link to something that enumerates the different possible values of `type` with any corresponding parameters that can be used for that variant of `type`.

**Comment by brennancheung** [comment]
After digging through the source code I think I found the answer here:

https://github.com/storybookjs/storybook/blob/next/code/lib/blocks/src/controls/types.ts#L68

This really needs to be documented though.

**Comment by jonniebigodes** [comment]
@brennancheung, thanks for reaching out to us with your question. We appreciate it. One quick question for you. Did you, by any chance, check this part of the [documentation](https://storybook.js.org/docs/react/essentials/controls#annotation)? I know there's room for improvement, and we're addressing it in the near future in terms of better example usage. But for now, at least should give you some context on how to use/customize and which options are available.

Looking forward to hearing from you.

Hope you have a great day.

Stay safe

**Comment by brennancheung** [comment]
Thank you, that solves my issue.  I must admit I missed that part.  I was scrolling through the documentation and skimmed over it because it was so far away from https://storybook.js.org/docs/react/essentials/controls#choosing-the-control-type and looked like it belonged to another section.

You have to scroll through `Custom Control Type Matchers`, `Fully Custom Args` , `Dealing with complex values` before you get to it so in my mind I mistakenly associated it to having something to do with those and filtered it out as I was skimming.

A link to that table of types in the `Choosing the Control Type` section, or even just moving the table there would add more clarity I think.

**Comment by jonniebigodes** [comment]
I get it. It's a lot to take in, I can make a pull request throughout those docs to point out to the table and add some clarification.
