### ISSUE TITLE
[Bug]: "Learn how to add interactions to your story" link is broken.

### ISSUE THREAD

**Issue by agiron123** [storybookjs/storybook#19527]
### Describe the bug

After running a fresh install, I noticed that the link to the documentation on how to add interactions to your story is broken.

The link goes here, which appears to not exist:
https://github.com/storybookjs/storybook/blob/next/addons/interactions/README.md

### To Reproduce

Run a fresh install of storybook.

In my case:

```shell
npx storybook init --use-npm
npm run storybook
```

Now choose a component like the Button component and navigate to the interactions tab on the bottom. You should be able to click the link "Learn how to add interactions to your story" from there.

### System

```shell
Environment Info:

  System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1 Pro
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
  Browsers:
    Chrome: 106.0.5249.119
    Firefox: 105.0.1
    Safari: 16.0
  npmPackages:
    @storybook/addon-actions: ^6.5.12 => 6.5.12 
    @storybook/addon-essentials: ^6.5.12 => 6.5.12 
    @storybook/addon-interactions: ^6.5.12 => 6.5.12 
    @storybook/addon-links: ^6.5.12 => 6.5.12 
    @storybook/builder-webpack4: ^6.5.12 => 6.5.12 
    @storybook/manager-webpack4: ^6.5.12 => 6.5.12 
    @storybook/react: ^6.5.12 => 6.5.12 
    @storybook/testing-library: ^0.0.13 => 0.0.13
```

**Comment by jonniebigodes** [comment]
@agiron123, thanks for taking the time to open up the issue. We're aware of the fact that the addon is pointing to the wrong place in the documentation. Hope you don't mind, but I'm closing this issue as it's already being tracked in #18957.

Hopefully, a patch will be up soon addressing both issues.

Hope you have a great week.

Stay safe

**Comment by agiron123** [comment]
Thanks @jonniebigodes, glad that this is being tracked. Have a great one!
