### ISSUE TITLE
MDX2 migration path for docs components

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#19532]
In MDX1, Storybook created a bunch of themed components for HTML elements `h1`, `h2`, ..., `p`, `div`, etc.

https://github.com/storybookjs/storybook/blob/next/code/addons/docs/src/DocsRenderer.tsx#L10-L15

We used this convoluted approach to try to avoid CSS bleed between our documentation components and user components which can be rendered inline from their stories.

| MDX source | MDX1 | MDX2 |
|-------------|-------|-------|
| `# hello`     |  `<DocsH1>hello</DocsH1>` | `<DocsH1>hello</DocsH1>` |
| `<h1>hello</h1>` | `<DocsH1>hello</DocsH1>` | `<h1>hello</h1>` |

This is a breaking change that will affect most Docs users. We need to:

- [ ] Create a migration strategy for existing users
- [ ] Possibly rethink our styling approach for MDX

**Comment by konsalex** [comment]
Redirected from: https://discord.com/channels/486522875931656193/1037707463811674203

The difference we have with Storybook v7 can be seen below:
![image](https://user-images.githubusercontent.com/12672541/199967403-4b37a680-a342-4c56-be0f-0f2443205c4d.png)

The original code was:
```tsx
<Alert icon type="warning" title="Styles breaking?">

  Common issues is when the styles are breaking in your project. Be sure to have
  the{' '}
  <a href="https://tailwindcss.com/docs/preflight" target="_blank">
    preflight off
  </a>
  , as we provide our own CSS Reset, based on the one from Tailwind.

</Alert>
```

If the children are in one line it fixes the weird new line rendering:

```tsx
<Alert icon type="warning" title="Styles breaking?">
    Common issues is when the styles are breaking in your project. Be sure to have the <a href="https://tailwindcss.com/docs/preflight" target="_blank"> preflight off </a> , as we provide our own CSS Reset, based on the one from Tailwind.
</Alert>
```

but still the children is wrapped in a Storybook `p` component.

Currently the only way to make this work is by wrapping the children to a span element like:

```tsx
<Alert icon type="warning" title="Styles breaking?">
    <span>Common issues is when the styles are breaking in your project. Be sure to have the <a href="https://tailwindcss.com/docs/preflight" target="_blank"> preflight off </a> , as we provide our own CSS Reset, based on the one from Tailwind.</span>
</Alert>
```

**Comment by shilman** [comment]
Closing as solved by our new styling structure thanks to @JReinhold
