### ISSUE TITLE
[Bug]: .mjs modules are bundled without esModuleInterop

### ISSUE THREAD

**Issue by edoardocavazza** [storybookjs/storybook#19533]
### Describe the bug

Some bundled modules that are meant to work in node environment, does not work when using ESM imports and `"type": "module"`. It happens because the module tries to import cjs dependencies without the `esModuleInterop` option.

For example, you cannot use `@storybook/csf-tools` because it imports `traverse` from `@babel/traverse` as default import.  Since `@babel/traverse` is a cjs dependency, the actual `traverse` method is only accessible at `traverse.default` in node.

### To Reproduce

* create a blank node project with `"type": "module"`
* install `@storybook/csf-tools@alpha`
* try to run the following code

```js
import { loadCsf } from '@storybook/csf-tools';

const csfFile = loadCsf('', {});
csfFile.parse();
```

### System

```shell
Node: v17.9.1
```

**Comment by IanVS** [comment]
@ndelangen I've noticed this as well.  Is this something we can fix by adjusting the way ts-up is bundling the files?

**Comment by shilman** [comment]
Shiver me timbers!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-alpha.46 containing PR #19661 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
