### ISSUE TITLE
[Bug]: Issue loading stories.json when using webpack publicPath

### ISSUE THREAD

**Issue by AckermannJan** [storybookjs/storybook#19546]
### Describe the bug

The goal is to deploy storybook feature branches via a Gitlab CI/CD.

We deploy our static files to static.cdn.domain-staging. So URLs for the bundled js files will look like this:
`https://static.cdn.domain-staging.de/shared-components/feature/storybook-ssc-461-update-node-and-package-lock/dist/551.9c307ca83b3e46cacb04.manager.bundle.js`
Reaching the index.html is done via a link like this:
`https://www.domain-staging.de/shared-components/feature/storybook-ssc-461-update-node-and-package-lock/`

We are accomplishing this using the webpack config using the publicPath for the webpackFinal and webpackManager configs. This looks like this:

```
module.exports = {
    ...
    webpackFinal: async (config) => {
        if (process.env.STORYBOOK_SSC_PUBLIC_PATH) {
            config.output.publicPath = process.env.STORYBOOK_SSC_PUBLIC_PATH
        }

        return config;
    },
    managerWebpack: async (config) => {
        if (process.env.STORYBOOK_SSC_PUBLIC_PATH) {
            config.output.publicPath = process.env.STORYBOOK_SSC_PUBLIC_PATH
        }
        return config;
    }
}
```

This worked perfectly fine before switching to `storyStoreV7` here it now tries to load the `stories.json` which did not work for the manager and the preview. After some trying I got it working for the preview using `--preview-url $STORYBOOK_SSC_PREVIEW_URL --force-build-preview` with that it will load the `stories.json` from our `static.cdn.domain-staging.de` but I have not option to do the same for the manager that is why it is loading the file from the URL where our index is hosted.

Fetch preview stories.json: (Right)
`https://static.cdn.domain-staging.de/shared-components/feature/storybook-ssc-461-update-node-and-package-lock/dist/stories.json`
Fetch manager stories.json: (Wrong)
`https://www.domain-staging.de/shared-components/feature/storybook-ssc-461-update-node-and-package-lock/stories.json`

So my current state is. Its loading the story on the first page visit, but the sidebar where all stories should be listed its just loading forever 

### To Reproduce

```shell
Sadly i can not provide this yet since it needs deployments and since our company libs are private I can not share them.
```

### System

```shell
Environment Info:

  System:
    OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
  Binaries:
    Node: 18.10.0 - /usr/local/bin/node
    Yarn: 1.22.17 - ~/.npm-global/bin/yarn
    npm: 8.19.2 - ~/.npm-global/bin/npm
  Browsers:
    Chrome: 106.0.5249.119
    Firefox: 105.0
  npmPackages:
    @storybook/addon-actions: ^6.5.12 => 6.5.12 
    @storybook/addon-essentials: ^6.5.12 => 6.5.12 
    @storybook/addon-interactions: ^6.5.12 => 6.5.12 
    @storybook/addon-links: ^6.5.12 => 6.5.12 
    @storybook/builder-webpack5: ^6.5.12 => 6.5.12 
    @storybook/manager-webpack5: ^6.5.12 => 6.5.12 
    @storybook/testing-library: ^0.0.13 => 0.0.13 
    @storybook/vue: ^6.5.12 => 6.5.12
```

**Comment by deepak-kumar-subramani** [comment]
I am also facing the same issue 
is there any workaround for this in v7 @AckermannJan

**Comment by vanessayuenn** [comment]
Is this still an issue with 8.x? If so, can you open a new issue with a repro using https://storybook.new please? Thanks!
