### ISSUE TITLE
[Bug]: @storybook/addon-storyshots is not compatible with react 18

### ISSUE THREAD

**Issue by barroudjo** [storybookjs/storybook#19541]
### Describe the bug

storyshots with react v18 throws `react-test-renderer TypeError: Cannot read properties of undefined`

This is due to @storybook/addon-storyshots@6.5.12 having the following dependency for react-test-renderer: `^16.8.0 || ^17.0.0` which is incompatible with react v18.

Using resolutions in package.json solves the problem, but it should really be solved in @storybook/addon-storyshots dependencies by allowing react-test-renderer@18.
``
"resolutions": {
    "react-test-renderer": "18.2.0"
  }
``

### To Reproduce

```shell
@storybook/addon-storyshots@6.5.12 and react@18.2.0
```

**Comment by KorySchneider** [comment]
Same issue here, even when I have `react-test-renderer` 18.x installed, the storyshots addon uses version 17.

```
$ pnpm why react-test-renderer

devDependencies:
@storybook/addon-storyshots 6.5.12
└── react-test-renderer 17.0.2
@storybook/addon-storyshots-puppeteer 6.5.12
└─┬ @storybook/addon-storyshots 6.5.12 peer
  └── react-test-renderer 17.0.2
react-test-renderer 18.2.0
```

**Comment by KorySchneider** [comment]
The `resolutions` workaround did not work for me, but updating `@storybook/addon-storyshots` and `@storybook/addon-storyshots-puppeteer` to `@future` (currently `7.0.0-alpha.40`) seems to have fixed it.

@shilman It would be great to get [this change](https://github.com/storybookjs/storybook/pull/18296) released on 6.x

**Comment by shilman** [comment]
@KorySchneider pretty sure that would be a breaking change. Can you use 6.x and force it with yarn resolutions (or whatever the npm equivalent is)?

**Comment by shilman** [comment]
@KorySchneider pretty sure that would be a breaking change. any idea why the resolutions workaround didn't work?

**Comment by KorySchneider** [comment]
@shilman Ah I see. Not sure why the resolutions didn't work...I'm using pnpm so potentially a bug with that?

**Comment by KorySchneider** [comment]
@shilman Yep that's what I used. `resolutions` is just an alias for `overrides`. I tried it two ways:

```
"overrides": {
  "react-test-renderer": "18.2.0"
}
```
and
```
"overrides": {
  "@storybook/addon-storyshots>react-test-renderer": "18.2.0"
}
```

**Comment by barroudjo** [comment]
Have you checked in your node_modules the package version of
react-test-renderer to see if the overrides/resolutions were respected ?

Le lun. 24 oct. 2022, 16:08, Kory Schneider ***@***.***> a
écrit :

**Comment by KorySchneider** [comment]
@barroudjo I believe I did but I'll try it again soon and see what I see. What I do remember is that in the logs, the TypeError was coming from `react-test-renderer@17.x.x` (with the overrides set in package.json)

**Comment by coolboy0961** [comment]
This solution fix my problem.

"overrides": {
  "react-test-renderer": "18.2.0"
}

steps
1. add overrides setting in package.json
2. delete node_modules and package-lock.json
3. npm install
4. execute `npx jest --clearCache`
5. npm run test

**Comment by barroudjo** [comment]
> This solution fixed my problem.
> 
> "overrides": { "react-test-renderer": "18.2.0" }
> 
> steps
> 
> 1. add overrides setting in package.json
> 2. delete node_modules and package-lock.json
> 3. npm install
> 4. execute `npx jest --clearCache`
> 5. npm run test

Yeah my bad, my solution with `"resolutions": { "react-test-renderer": "18.2.0" }` was for yarn, the solution if you use npm is `"overrides": { "react-test-renderer": "18.2.0" }`

**Comment by jonniebigodes** [comment]
The Storyshots addon is officially deprecated and will be removed in a future release of Storybook. To help with the transition process, we've created a [migration guide](https://storybook.js.org/docs/writing-tests/storyshots-migration-guide) for the available options and common use cases.
