### ISSUE TITLE
[Bug]: story source code not avaliable with vite builder

### ISSUE THREAD

**Issue by HongSiyuan** [storybookjs/storybook#19554]
### Describe the bug

docs page dose not show story source code with vite builder. It shows "No code avaliable".
**Storybook version: 7.0.0-alpha.40**

<img width="1363" alt="image" src="https://user-images.githubusercontent.com/38722610/196901625-4cdd0bc6-49af-4bf6-afc4-3178ca0e53d1.png">

### Reproduce
```
npm init vue@latest
cd <your-project-name>
npm install
npx storybook init@next
```

### System

```shell
Environment Info:

  System:
    OS: macOS 12.5.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 14.20.1 - ~/.nvm/versions/node/v14.20.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v14.20.1/bin/yarn
    npm: 6.14.17 - ~/.nvm/versions/node/v14.20.1/bin/npm
  Browsers:
    Chrome: 106.0.5249.119
    Firefox: 105.0
    Safari: 15.6.1
  npmPackages:
    @storybook/addon-essentials: ^7.0.0-alpha.40 => 7.0.0-alpha.40 
    @storybook/addon-interactions: ^7.0.0-alpha.40 => 7.0.0-alpha.40 
    @storybook/addon-links: ^7.0.0-alpha.40 => 7.0.0-alpha.40 
    @storybook/testing-library: ^0.0.13 => 0.0.13 
    @storybook/vue3: ^7.0.0-alpha.40 => 7.0.0-alpha.40 
    @storybook/vue3-vite: ^7.0.0-alpha.40 => 7.0.0-alpha.40
```

**Comment by shilman** [comment]
Jiminy cricket!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.0 containing PR #20147 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
