### ISSUE TITLE
[Bug]: DocsPage does not respect story sort

### ISSUE THREAD

**Issue by iansan5653** [storybookjs/storybook#19605]
### Describe the bug

The DocsPage feature seems to be ignoring the sort order of my stories. For example, I have this `Avatar` component which exports five stories:

```tsx
const metadata: Meta = {
  component: Avatar
}

export default metadata

export function Default() { /*...*/ }

export function Square() { /*...*/ }

export function CustomSize() { /*...*/ }

export function CustomAltText() { /*...*/ }

export function CustomStyling() { /*...*/ }
```

This looks correct in the story navigation sidebar:

<img width="212" alt="The sidebar section for 'Avatar'. Under the component name is (in order): Docs, Default, Square, Custom Size, Custom Alt Text, and Custom Styling." src="https://user-images.githubusercontent.com/2294248/197555292-74f742ca-bf2a-4be8-b45f-9fa369342856.png">

However, on the automatically generated Docs page, the stories seem to be rendered in random order:

<img width="1025" alt="The docs page for 'Avatar'. The default story is 'Custom Alt Text', followed by (in order): Custom Size, Custom Styling, Default, and Square." src="https://user-images.githubusercontent.com/2294248/197555662-4a037ec4-c116-4e8a-b5a8-13ab2b6db4a6.png">

As you can see from the screenshot, the default (top) story is not "Default" as I would expect. Instead it's "Custom Alt Text" and the rest of the stories follow in apparently random order.

### To Reproduce

This [repository](https://github.com/iansan5653/storybook-docs-order-repro/tree/main) has no changes at all from the `npx sb@next repro` output but it does still reproduce the problem. For example, see the `Button` stories - the first story should be `Primary` but instead it's `Large`.

### System

```shell
System:
    OS: Linux 5.4 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz
  Binaries:
    Node: 16.18.0 - ~/.nodejs/current/bin/node
    Yarn: 3.2.4 - /usr/bin/yarn
    npm: 8.19.2 - ~/.nodejs/current/bin/npm
  npmPackages:
    @storybook/addon-docs: ^7.0.0-alpha.42 => 7.0.0-alpha.42 
    @storybook/addon-essentials: ^7.0.0-alpha.42 => 7.0.0-alpha.42 
    @storybook/addon-interactions: ^7.0.0-alpha.42 => 7.0.0-alpha.42 
    @storybook/addon-links: ^7.0.0-alpha.42 => 7.0.0-alpha.42 
    @storybook/react: ^7.0.0-alpha.42 => 7.0.0-alpha.42 
    @storybook/react-webpack5: ^7.0.0-alpha.42 => 7.0.0-alpha.42 
    @storybook/testing-library: ^0.0.13 => 0.0.13
```

### Additional context

There is no `storySort` configured - I am using the default sort order. But the issue still happens even with a custom sort order.

**Comment by richard-jfc** [comment]
It seems that the stories returned by https://github.com/storybookjs/storybook/blob/65957e6789bc57d506ca63e6f3be3927f110565e/code/lib/preview-web/src/render/TemplateDocsRender.ts#L67 are returned in alphabetical order.

I patched around it by changing https://github.com/storybookjs/storybook/blob/65957e6789bc57d506ca63e6f3be3927f110565e/code/lib/store/src/csf/processCSFFile.ts#L56 to 
```
  __namedExportsOrder.forEach((key) => { 
```

Unfortunately I don't know the codebase well enough to understand whether `processCSFFileWithCache` should already be returning sorted exports.

**Comment by zigang93** [comment]
I had same problem.. well it is not random.. actually is sort by alphabetical

**Comment by iansan5653** [comment]
Just sharing my workaround. This is pretty hacky and relies on Storybook internals which may break, but it allows me to customize which story becomes the primary one. I do this by defining a custom docs page component:

```jsx
import React, {useContext} from 'react'

import {Title, Subtitle, Description, Primary, ArgsTable, Stories, DocsContext, Heading} from '@storybook/addon-docs'

/** For each component, we'll extract the story with this name and use it as the primary. */
const PRIMARY_STORY_NAME = "Default"

export const DocsPage = () => {
  const context = useContext(DocsContext)

  // The 'primary' story is rendered at the top of the page. The default implementation picks
  // the first story in the alphabet; we look for one with a standard name instead and then
  // override the private field on the context object to update it.
  // This will probably break with updates to Storybook, but ideally Storybook will simultaneously
  // add configuration for the primary story so we can just set this properly.
  let primaryStoryId
  try {
    primaryStoryId = context.storyIdByName(PRIMARY_STORY_NAME) // Throws if missing

    // Even though we pass the primary story name to the ArgsTable, it still gets confused
    // and renders the wrong controls unlesss we also set the primaryStory private value
    context.primaryStory = context.storyById(primaryStoryId)
    // The Stories block is wierdly doesn't read primary story from any field or props,
    // instead just assuming the first story is primary. So even though we set that field
    // we still have to sort the stories to put the primary one first
    // see: https://github.com/storybookjs/storybook/blob/65957e6789bc57d506ca63e6f3be3927f110565e/code/ui/blocks/src/blocks/Stories.tsx
    context.componentStoriesValue = context
      .componentStories()
      // This leaves the rest of the stories in alpha order. We could instead define a custom sort here
      .sort((a, b) => (a.name === PRIMARY_STORY_NAME ? -1 : b.name === PRIMARY_STORY_NAME ? 1 : 0))
  } catch {}

  const primaryStoryFound = primaryStoryId !== undefined
  return (
    <>
      <Title />
      <Subtitle />
      <Description />

      {primaryStoryFound && <Primary name={PRIMARY_STORY_NAME} />}

      <Heading>Props</Heading>
      <ArgsTable story={primaryStoryFound && PRIMARY_STORY_NAME} />

      <Stories includePrimary={primaryStoryFound} />
    </>
  )
}
```

Which I then set in my `preview.js`:

```js
export const parameters = {
  docs: {
    page: DocsPage
  }
}
```

**Comment by shilman** [comment]
closing as dupe to #19605
