### ISSUE TITLE
[Bug]: react-docgen-typescript-plugin: Deprecation warnings after updating to TypeScript 4.8

### ISSUE THREAD

**Issue by daniel-ac-martin** [storybookjs/storybook#19618]
### Describe the bug

See: https://github.com/hipstersmoothie/react-docgen-typescript-plugin/issues/69

### To Reproduce

```shell
See: https://github.com/hipstersmoothie/react-docgen-typescript-plugin/issues/69
```

### System

```shell
N/A
```

### Additional context

Is there any chance that the [Storybook fork of react-docgen-typescript-plugin](https://github.com/storybookjs/react-docgen-typescript-plugin) could be updated to [v1.0.2](https://github.com/hipstersmoothie/react-docgen-typescript-plugin/releases/tag/v1.0.2) which has a fix for this bug?

**Comment by daniel-ac-martin** [comment]
@shilman: Any thoughts on this?

**Comment by taraskhvyl** [comment]
also actual for us

**Comment by IntusFacultas** [comment]
+1, affecting us as well

**Comment by tabuckner** [comment]
I would also love to know if this is possible.

**Comment by Naes0** [comment]
Also affecting us

**Comment by shilman** [comment]
closing this as duplicate to #19055, which is in progress for 7.0
