### ISSUE TITLE
[Bug]: all svelte stories fail `does not provide an export named 'combineParameters'``

### ISSUE THREAD

**Issue by gbkwiatt** [storybookjs/storybook#19663]
### Describe the bug

on latest alpha.45 after fixing one regression, another happens, and all stories don't work at all

`The requested module '/node_modules/.cache/.vite-storybook/deps/@storybook_client-api.js?v=d02afa6c' does not provide an export named 'combineParameters'`

**Comment by JReinhold** [comment]
I'm not able to reproduce this, tried with the `svelte-vite/default-js` sandbox.

Can you provide a minimal reproduction?

Have you tried deleting the `node_modules/.cache` folder after upgrading?

**Comment by gbkwiatt** [comment]
ok so I figured that it happens with latest `@storybook/addon-svelte-csf` 3.0.0.next but not with `2.0.9`

**Comment by gbkwiatt** [comment]
Here it is, minimal reproduction - basically any svelte component
https://github.com/gbkwiatt/generic-sveltekit-storybook

**Comment by IanVS** [comment]
Thanks for the reproduction.  I upgraded storybook and sveltekit in your repro, and it works correctly now.  Let us know if you're still having trouble.
