### ISSUE TITLE
[Bug]: Reference to @storybook/mdx1-csf still exists in 7.0

### ISSUE THREAD

**Issue by IanVS** [storybookjs/storybook#19677]
### Describe the bug

A user was having a problem in Discord, getting this warning:

![image](https://user-images.githubusercontent.com/4616705/198675435-5443b05f-e6cd-4bf6-860e-a82550c6f408.png)

The only place I can still see `@storybook/mdx1-csf` still being referenced is in https://github.com/storybookjs/storybook/blob/4368b1569df0f2b296189ad5f3f8add9522d4ddd/code/addons/docs/mdx-compiler-plugin.js#L1, but that file itself doesn't seem to be used anywhere.  So I'm not certain what's going on.  But it seems like this reference should be removed or updated, maybe?

### Additional context

The thread in discord: https://discord.com/channels/486522875931656193/1035550969632661555

**Comment by emojivibe** [comment]
can i do this?

**Comment by IanVS** [comment]
Sorry, it's already done in https://github.com/storybookjs/storybook/pull/19681

**Comment by shilman** [comment]
Egads!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-alpha.47 containing PR #19681 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
