### ISSUE TITLE
[Bug]: Storybook build and dev server not working after updating to Node.js 18

### ISSUE THREAD

**Issue by dcastil** [storybookjs/storybook#19692]
### Describe the bug

After I updated from Node.js 16 to 18, the `storybook-build` command fails with following error message:

```
transforming (40) node_modules/@storybook/addon-interactions/dist/esm/preset/preview.jsnode:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/Users/dany/code/tests/storybook-test/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/dany/code/tests/storybook-test/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/dany/code/tests/storybook-test/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/dany/code/tests/storybook-test/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/dany/code/tests/storybook-test/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/dany/code/tests/storybook-test/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/dany/code/tests/storybook-test/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/Users/dany/code/tests/storybook-test/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Users/dany/code/tests/storybook-test/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /Users/dany/code/tests/storybook-test/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /Users/dany/code/tests/storybook-test/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

### To Reproduce

Run this in the CLI:

```shell
yarn create vite storybook-test --template react-ts
cd storybook-test
# Remove `type: module` from package.json
npx storybook init
yarn build-storybook
# Last command should fail with error message from above
```

### System

```shell
Environment Info:

  System:
    OS: macOS 13.0
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 18.12.0 - /usr/local/bin/node
    Yarn: 1.22.17 - ~/.npm-global/bin/yarn
    npm: 8.19.2 - ~/.npm-global/bin/npm
  Browsers:
    Chrome: 107.0.5304.62
    Firefox: 106.0.2
    Safari: 16.1
  npmPackages:
    @storybook/addon-actions: ^6.5.13 => 6.5.13 
    @storybook/addon-essentials: ^6.5.13 => 6.5.13 
    @storybook/addon-interactions: ^6.5.13 => 6.5.13 
    @storybook/addon-links: ^6.5.13 => 6.5.13 
    @storybook/builder-vite: ^0.2.5 => 0.2.5 
    @storybook/react: ^6.5.13 => 6.5.13 
    @storybook/testing-library: ^0.0.13 => 0.0.13
```

### Additional context

The problem seems to be [due to a change in the OpenSSL API in Node 17](https://stackoverflow.com/questions/70582072/npm-run-fails-with-err-ossl-evp-unsupported). There is a workaround for this: Run Node.js with the option `--openssl-legacy-provider`, e.g. by adding the environment variable `NODE_OPTIONS=--openssl-legacy-provider`.

Possibly related:
- https://github.com/storybookjs/storybook/issues/18733
- https://github.com/chromaui/chromatic-cli/issues/628

**Comment by CraigWatt** [comment]
downgrading node to v16.13.0 avoids the error for me.  Not really a valid solution though...

**Comment by dcastil** [comment]
I also just noticed that the Storybook dev server also doesn't work anymore in Node.js 18. I updated the issue description to include that.

**Comment by CraigWatt** [comment]
Looking around this does seem to be a node specific issue...

I guess I would want to ask anyone using storybook, are they able to run / build storybook using node 17 or 18 at all?

Does everyone just use Node 16?

**Comment by CraigWatt** [comment]
I'm currently checking the following in storybook docs... https://storybook.js.org/docs/react/builders/webpack

**Comment by CraigWatt** [comment]
Bingo!  i think this solves it.  by default storybook uses Webpack 4.  if you set storybook to use Webpack 5, i am able to run yarn storybook on node v18.2.0

https://storybook.js.org/docs/react/builders/webpack

@dcastil can you let me know if this solves the issue for you too?

**Comment by dcastil** [comment]
Hey @CraigWatt! Ah nice that it works with webpack5. Unfortunately I can't switch to it in my app because we're using the Vite builder which forces us to use `@storybook/builder-vite` for Storybook. But I guess that makes this a problem in the Vite builder rather than Storybook itself.

After some searching I also came along a definitive answer to the problem in https://github.com/storybookjs/builder-vite/issues/414#issuecomment-1210668981:

> Unfortunately webpack 4 will not be updated to support node 17: https://github.com/webpack/webpack/issues/14532#issuecomment-947513562. And the storybook manager is currently always built with webpack 4. This will change in Storybook 7, which will use webpack 5 and no longer support webpack 4. So my recommendation for now is to use node 16 or the `--openssl-legacy-provider` flag, until Storybook v7 is released.

This means we need to wait for Storybook v7 for this to get resolved and use the workarounds in the meantime.

**Comment by oseisaac** [comment]
This was the solution for me 

`NODE_OPTIONS=--openssl-legacy-provider `

`"start": "NODE_OPTIONS=--openssl-legacy-provider  npm run storybook",`
