### ISSUE TITLE
[Bug]: Docs: Update link to Testing Library user-events page

### ISSUE THREAD

**Issue by domyen** [storybookjs/storybook#19703]
### Describe the bug

Update link for "official user-event docs" in the Interaction Testing docs [here](https://storybook.js.org/docs/react/writing-tests/interaction-testing#api-for-user-events) to point to the latest user-event docs (instead of the recently deprecated 13.5 docs).

<img width="863" alt="image" src="https://user-images.githubusercontent.com/263385/199329705-8be548a8-707b-4221-8a90-4d7403d16b96.png">

**Comment by jonniebigodes** [comment]
Closing this as the documentation is now updated to reflect. Changes are already featured in a local 7.0 branch. They will be pushed in the upcoming weeks
