### ISSUE TITLE
[Bug]: Yarn pnp support broken on 7.0.0-alpha.47

### ISSUE THREAD

**Issue by bryanjtc** [storybookjs/storybook#19707]
### Describe the bug

After installing storybook 7.0 on a react-vite project with yarn v3 pnp, the following error shows up on mdx files:
`Uncaught TypeError: Cannot read properties of undefined (reading 'fonts')`
![image](https://user-images.githubusercontent.com/49354825/199386643-a1f813e4-47e5-4135-97f5-2a99155db0c1.png)

### To Reproduce

```shell
https://github.com/bryanjtc/storybook-7-vite-test
```

### System

```shell
System:
    OS: Linux 5.10 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
Binaries:
    Node: 18.12.0 - ~/.nvm/versions/node/v18.12.0/bin/node
    Yarn: 3.2.4 - /mnt/c/Program Files/nodejs/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.0/bin/npm
```

**Comment by IanVS** [comment]
@bryanjtc did you find out what was causing this?  I'm running into it with someone else's repo, and trying to figure out what's going on.

**Comment by bryanjtc** [comment]
No, but when I upgraded to alpha 49 it was fixed.
