### ISSUE TITLE
[Bug]: Dead links in docs (everywhere)

### ISSUE THREAD

**Issue by coler-j** [storybookjs/storybook#19719]
### Describe the bug

Many of your website docs have links that are dead.

For example: https://storybook.js.org/docs/react/configure/babel

![image](https://user-images.githubusercontent.com/7839615/199501323-96b81d8a-9258-4ec2-acc6-9bd23f8cadb7.png)

The "source" link goes to "https://github.com/storybookjs/storybook/blob/next/lib/core-common/src/utils/babel.ts"

Which does not exist. 

I think it should be something other than "next" in the URL.

**Comment by maxmorozoff** [comment]
Another broken link found here: [](https://github.com/storybookjs/storybook/blob/d2d6f9d0eddef2176da5815296be0eabe5622434/docs/addons/writing-presets.md?plain=1#LL210C253-L210C348)

[](https://storybook.js.org/docs/react/addons/writing-presets#previewmanager-templates)

**Comment by jonniebigodes** [comment]
Closing this as the documentation was vetted per the Storybook 7 release and most of the links mentioned here are already fixed.

**Comment by maxmorozoff** [comment]
> Another broken link found here: https://github.com/storybookjs/storybook/blob/d2d6f9d0eddef2176da5815296be0eabe5622434/docs/addons/writing-presets.md?plain=1#LL210C253-L210C348
> 
> https://storybook.js.org/docs/react/addons/writing-presets#previewmanager-templates

Is still broken.
