### ISSUE TITLE
sb-scripts automigration unable to migrate script

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#19728]
```
"build:storybook": "build-storybook -c .storybook -o dist-storybook",
"storybook": "start-storybook -p 9001 -c .storybook"
```

**Comment by yannbf** [comment]
The automigration looks for official scripts added by Storybook: `storybook` and `build-storybook`. If a user decides to change them, the automigration stays on the safe side and does not change them (but does detect them if they contain storybook in the name), the command is quite explicit showing that and asking users to change them manually:

![Image](https://user-images.githubusercontent.com/1671563/204877516-ce195474-064d-4806-9c05-a7382ba3c677.png)

Is this behavior something you'd like to see changed @shilman ? As in, no distinction between custom scripts and therefore changing all of them, even though that could break?

**Comment by yannbf** [comment]
I improved the logic at #20035 which should detect that particular use case

**Comment by shilman** [comment]
w00t!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-alpha.59 containing PR #20035 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
