### ISSUE TITLE
typescript.checkOptions has been removed

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#19731]
See https://gist.github.com/mihkeleidast/af2e01ee4672804ed79d903a1093a7ab

**Comment by ndelangen** [comment]
I checked this, and it's NOT been removed for webpack. but it is not used by vite as far as I can see.

**Comment by ndelangen** [comment]
I found that the exact interface is missing though, so maybe that's what this issue is about? Even though the link above mentions vite.

I found a solution for that. Opening PR now.

**Comment by shilman** [comment]
Yippee!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.2 containing PR #20166 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
