### ISSUE TITLE
[Feature Request]: Enable Scorecard Github Action and Badge

### ISSUE THREAD

**Issue by joycebrum** [storybookjs/storybook#19743]
### Is your feature request related to a problem? Please describe

Hi I am Joyce from Google and I'm working on behalf of the [Open Source Security Foundation][ossf] (OpenSSF) to help open source projects to improve their supply-chain security, since open source supply-chain attacks are [increasing every year][sonatype].

Besides, many maintainers, due to lack of time, are not able to be always up to date to the best security posture and best practices to follow to mitigate security vulnerabilities in the project.

[ossf]: https://openssf.org/
[sonatype]: https://www.sonatype.com/resources/state-of-the-software-supply-chain-2021

### Describe the solution you'd like

The [Scorecard Github Action][sc-gha] (developed by the OpenSSF, [in partnership with GitHub][sc-blog]) is an easy and fast way to run the [Scorecard][sc] frequently in the project to check the project's security posture and identify which changes would be interesting to be adopted in order to improve its supply-chain security. 

The Scorecard Github Action runs all the Scorecard [checks][checks] and uploads the result in the project's [security dashboard](https://github.com/storybookjs/storybook/security), with suggestion on how to solve any issue (see examples on the Addional Context). It also allows a [badge][badge] to be added to the README file with the project's score.

This Action has been adopted by 1800+ projects already, having some prominent users like [Tensorflow][tensorflow], [Angular][angular], [Flutter][flutter], [sos.dev][sos-dev] and [deps.dev][deps-dev].

For common question, you can try checking [Scorecard FAQ][faq], anyway feel free to reach me out.

Would a PR with this changes be welcome? I can open it if you are ok with it.

[badge]: https://openssf.org/blog/2022/09/08/show-off-your-security-score-announcing-scorecards-badges/
[checks]: https://github.com/ossf/scorecard#scorecard-checks
[sc]: https://github.com/ossf/scorecard
[sc-blog]: https://github.blog/2022-01-19-reducing-security-risk-oss-actions-opensff-scorecards-v4/
[sc-gha]: https://github.com/ossf/scorecard-action
[faq]: https://github.com/ossf/scorecard/blob/main/docs/faq.md#frequently-asked-questions 

[tensorflow]: https://github.com/tensorflow/tensorflow
[angular]: https://github.com/angular/angular  
[flutter]: https://github.com/flutter/flutter 
[sos-dev]: https://sos.dev/ 
[deps-dev]: https://deps.dev/ 

### Are you able to assist to bring the feature to reality?

yes, I can

### Additional context

![Code scanning dashboard with multiple alerts, including Code-Review and Token-Permissions][img-security]

![Detail of a Token-Permissions alert, indicating the specific file and remediation steps][img-detail]

[img-security]: https://user-images.githubusercontent.com/15221358/190184391-84ca1844-259a-4b3b-9c86-74adadbea7f1.png
[img-detail]: https://user-images.githubusercontent.com/15221358/190184600-ee8d3b39-077e-416a-8711-1b5fb01cf0b3.png

**Comment by shilman** [comment]
Thanks so much for this @joycebrum ! We'd be happy to accept a PR adding this to our repo 🙏

**Comment by shilman** [comment]
¡Ay Caramba!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.27 containing PR #19755 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```
