### ISSUE TITLE
26 high vulnerabilities with latest react and storybook setup

### ISSUE THREAD

**Issue by JoBurg007** [storybookjs/storybook#19751]
### Describe the bug

Hello,
I have just installed a react 18.2 and storybook app and receive some dozens of warning like "Could not resolve dependency:" and a warning of "26 high severity vulnerabilities". The following screenshot is only showing a fraction:
https://ibb.co/R0VKtvp

Before installing storybook I did not have any warnings or vulnerabilities like this.

What is wrong? How to solve this in a solid way? I don't wont to ignore it and simply carry on. It is not the first time I am experiencing this with storybook.

I hope somebody can help me.
Thanks

### To Reproduce

```shell
Was not possible:

Starting for react_typescript latest

🏗 Bootstrapping react_typescript project (this might take a few minutes)
mkdir react_typescript2 && cd react_typescript2 && touch yarn.lock && yarn init --yes && yarn add react react-dom

An error occurred while executing: `mkdir react_typescript2 && cd react_typescript2 && touch yarn.lock && yarn init --yes && yarn add react react-dom`
🚨 Bootstrapping react_typescript failed
🚨 Failed to create repro
ERR! Error: command exited with code: 1:
```

### System

```shell
Environment Info:

  System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.19.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 107.0.5304.88
    Edge: Spartan (44.22000.120.0), Chromium (107.0.1418.26)
  npmPackages:
    @storybook/addon-essentials: ~6.5.9 => 6.5.13
    @storybook/builder-webpack5: ~6.5.9 => 6.5.13
    @storybook/core-server: ~6.5.9 => 6.5.13
    @storybook/manager-webpack5: ~6.5.9 => 6.5.13
    @storybook/react: ~6.5.9 => 6.5.13
```

**Comment by shilman** [comment]
Please try upgrading to the latest prerelease:

```
npx storybook@next upgrade --prerelease
```

We've fixed all of the known vulnerabilities in 7.0. Unfortunately many of them involve breaking changes that can't be ported back to 6.5.

**Comment by JoBurg007** [comment]
Thank you very much! This reduced the "26 high severity vulnerabilities" down to "5 high severity vulnerabilities". Looks good. A further "npm audit fix --force" solved it down to 0.
You saved my weekend.

I guess your hint is valuable for many users!

Thank you!

**Comment by shilman** [comment]
Thanks @JoBurg007 !! We'll be doing major version updates more frequently in the future to avoid getting into this situation again
