### ISSUE TITLE
[Bug]: Next.js / Typescript Interaction with Storybook

### ISSUE THREAD

**Issue by maaxayotte** [storybookjs/storybook#19782]
### Describe the bug

When utilizing storybook with next.js and Typescript there is an error with storybook displaying the next Image tag when the src link is a gif.

`{loading ? <Image src="/gifs/spinner.gif" alt="A loading gif" width={26} height={26} quality={100} /> : children}`

In this code snip the loaded image is a gif called "spinner.gif"

The component loaded in storybook loads with the alt text as would happen when the gif wont load.
![Screen Shot 2022-11-08 at 3 25 47 PM](https://user-images.githubusercontent.com/71656500/200668105-1901cc2d-e378-4df7-9274-650eb1857b1b.png)

However when launching my Next server into a localhost environment the component functions fine and the gif loads
![Screen Shot 2022-11-08 at 3 27 05 PM](https://user-images.githubusercontent.com/71656500/200668354-b2421cd6-786a-4149-a862-c0899c668ed3.png)

My guess is that because Next only recently added GIF support to the next/Image tag, storybook hasn't been properly updated to reflect this change and load those image types.

Hope this helps, let me know if more info is needed! :)

### System

```shell
System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1 Pro
  Binaries:
    Node: 16.15.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.11.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 107.0.5304.87
    Safari: 15.6.1
  npmPackages:
    @storybook/addon-actions: ^6.5.13 => 6.5.13 
    @storybook/addon-essentials: ^6.5.13 => 6.5.13 
    @storybook/addon-interactions: ^6.5.13 => 6.5.13 
    @storybook/addon-links: ^6.5.13 => 6.5.13 
    @storybook/builder-webpack5: ^6.5.13 => 6.5.13 
    @storybook/manager-webpack5: ^6.5.13 => 6.5.13 
    @storybook/react: ^6.5.13 => 6.5.13 
    @storybook/testing-library: ^0.0.13 => 0.0.13
```

**Comment by yannbf** [comment]
Hey @maaxayotte thanks for opening an issue here! So `@storybook/react` does not contain the necessary setup for the Next Image component. You have two options here:
1. Use [storybook-addon-next](https://github.com/RyanClementsHax/storybook-addon-next) in your project, with Storybook 6.
2. Try our new `@storybook/nextjs` package, which only works with Storybook 7 (currently in alpha). If you do, you can use [this project](https://github.com/storybookjs/repro-templates-temp/tree/next/nextjs/default-ts/after-storybook) as a reference (.storybook/main.js and package.json) to set the necessary bits up.

**Comment by valentinpalkovic** [comment]
Hi @maaxayotte!

Hopefully, the solutions mentioned above helped. Please let me know if your problem still exists. Then I will reopen this issue.
