### ISSUE TITLE
Extending syntax highlighter languages broken in v7

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#19794]
_Originally posted by @i-am-the-slime in https://github.com/storybookjs/storybook/issues/7847#issuecomment-1304800591_

**Comment by j3rem1e** [comment]
Is there a workaround for this issue ?

I used to add highlighting for java and Svelte in sb V6 but it doesn't work in v7

**Comment by JReinhold** [comment]
@ndelangen wasn't this fixed in https://github.com/storybookjs/storybook/pull/23166?

**Comment by ndelangen** [comment]
AFAIK this was indeed fixed by the above mentioned PR.
