### ISSUE TITLE
[Bug]: @mdx-js/react is not used in a pnpm-safe way

### ISSUE THREAD

**Issue by IanVS** [storybookjs/storybook#19821]
### Describe the bug

When creating a new project with pnpm and storybook, an error occurs in the introduction mdx.  

```
[vite] Internal server error: Failed to resolve import "@mdx-js/react" from "src/stories/Introduction.stories.mdx". Does the file exist?
  Plugin: vite:import-analysis
  File: /Users/ianvs/code/experiments/pnpm-final/src/stories/Introduction.stories.mdx:5:53
  2  |  /*@jsxRuntime automatic @jsxImportSource react*/
  3  |  import { Fragment as _Fragment, jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
  4  |  import { useMDXComponents as _provideComponents } from "@mdx-js/react";
     |                                                          ^
  5  |  import { Meta } from '@storybook/addon-docs';
  6  |  import Code from './assets/code-brackets.svg';
```

I guess this is because of the way that `@mdx-js/react` is included as a sub-dependency of a storybook package, but is being injected directly into the code that is run in the browser, which fails due to the way pnpm does not hoist dependencies.

### To Reproduce

```shell
pnpm create vite@latest
pnpx sb@next init --builder=vite
pnpm run storybook
```

**Comment by shilman** [comment]
I believe this is the off the shelf MDX behavior @IanVS. We might be able to do the re-export trick for addon-docs and tweak the compiler to import from addon-docs. However this is ugly because we'd need to figure out whether to reference addon-docs or addon-essentials.

Any ideas?

**Comment by dvins** [comment]
@IanVS Seeing this error too -- assuming the shim is in v7.0.0-beta.1 it unfortunately did not solve the issue for us. We're using PNPM 7.16.1

**Comment by shilman** [comment]
@dvins do you have a reproduction you can share? i'm not seeing the problem in @IanVS 's original repro.

I'm seeing the following issue in a JS project @ndelangen 

```
 WARN  Issues with peer dependencies found
.
├─┬ @storybook/addon-essentials 7.0.0-beta.2
│ └─┬ @storybook/addon-controls 7.0.0-beta.2
│   └─┬ @storybook/blocks 7.0.0-beta.2
│     └─┬ @storybook/docs-tools 7.0.0-beta.2
│       └─┬ @storybook/core-common 7.0.0-beta.2
│         └── ✕ missing peer typescript@"*"
└─┬ @storybook/vue3-vite 7.0.0-beta.2
  ├─┬ @storybook/builder-vite 7.0.0-beta.2
  │ └─┬ @joshwooding/vite-plugin-react-docgen-typescript 0.0.5
  │   ├── ✕ missing peer typescript@">= 4.3.x"
  │   └─┬ react-docgen-typescript 2.2.2
  │     └── ✕ missing peer typescript@">= 4.3.x"
  └─┬ @storybook/core-server 7.0.0-beta.2
    └── ✕ missing peer typescript@"*"
Peer dependencies that should be installed:
  typescript@>=4.3.0
```

**Comment by shilman** [comment]
I believe this is done. The TS issue is open in #20179
