### ISSUE TITLE
[Feature Request]:  add i18n to sb7 vue 3 vite

### ISSUE THREAD

**Issue by Shinokami** [storybookjs/storybook#19855]
### Is your feature request related to a problem? Please describe

stack: vue 3, vite. 
I'm trying to run storybook 7 alpha but can't add the `i18n` package. 
it used to be like this in `preview.js`, but now it can't work. unable to import `app`
```
import { app } from '@storybook/vue3';
import { i18n } from 'i18n';
app.use(i18n)
```
<img width="754" alt="image" src="https://user-images.githubusercontent.com/38629018/202206602-9a3bc832-c4f0-47d2-a7c0-ec95f06e24bd.png">

### Describe the solution you'd like

ability to add packages to vue app

### Describe alternatives you've considered

i tried the following code in `preview.js` but it didn't solve the problem
```
import { setup } from '@storybook/vue3';
import { i18n } from 'i18n';
setup((app) => {
   app.use(i18n)
});
```

### Additional context

maybe need to be added to the `app` export in `@storybook/vue3`

**Comment by eikooc** [comment]
I've also made a smaller reproduction. It looks like no Vue plugins can be used:
```js
app.use({
    install(app, options) {
      app.config.globalProperties.$t = () => "Hello"
    },
  })
```

**Comment by Hanawa02** [comment]
@Shinokami in my case the setup function worked. But I don't use the i18n package directly, I believe you need to use the instance you create with your config.

![image](https://user-images.githubusercontent.com/11237366/221243205-b3a6555a-1abb-44ed-94f8-d0fd9ad08ca7.png)

**Comment by Shinokami** [comment]
@Hanawa02 , @eikooc thank you very much for your solutions. There is some truth in what @eikooc says, `app` is no longer exported and has been removed, we can use the `setup`, but if you call the `setup` at the story level, then the global setting from the preview does not work anymore and we need to reconnect everything. I think the topic can be closed, but I think the connection of libraries to the vue application still needs to be improved
