### ISSUE TITLE
[Bug]: Add viteFinal to StorybookConfiguration 

### ISSUE THREAD

**Issue by yarinsa** [storybookjs/storybook#19867]
### Describe the bug

The current 
`import type { StorybookConfig } from '@storybook/react/types';`

Includes "webpackFinal" in it's types but I am using viteBuilder and got viteFinal. 

### To Reproduce

```shell
import { mergeConfig, UserConfig } from 'vite';
import { config as viteConfig } from './vite.config';
import { viteFinalFactory } from 'storybook-design-token/dist/preset';
import type { StorybookConfig } from '@storybook/react/types';

const config: StorybookConfig = {
  framework: '@storybook/react',
  stories: ['../stories/**/*.stories.mdx', '../src/**/*.stories.@(js|jsx|ts|tsx|mdx)'],
  addons: [
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    'storybook-addon-designs/preset',
    '@storybook/addon-docs',
    'storybook-design-token',
  ],
  core: {
    builder: '@storybook/builder-vite',
    disableTelemetry: true,
  },
  features: {
    storyStoreV7: true,
  },
  typescript: {
    reactDocgen: 'react-docgen-typescript',
    reactDocgenTypescriptOptions: {
      // By default react-doc-gen-typescript filters node_modules type, this includes antd types
      tsconfigPath: '../tsconfig.json',
      propFilter: (prop: any) => {
        const res = /antd/.test(prop.parent?.fileName) || !/node_modules/.test(prop.parent?.fileName);
        return prop.parent ? res : true;
      },
      // The following 2 options turns string types into string literals and allows
      shouldExtractLiteralValuesFromEnum: true,
      savePropValueAsString: true,
      shouldRemoveUndefinedFromOptional: true,
    },
  },
  viteFinal: async (config: UserConfig, { configType }: { configType: string }) => mergeConfig(config, viteConfig({ command: 'serve', mode: configType.toLowerCase() })),

  // },
};
export default config;

```

### System

```shell
sb@next info
Need to install the following packages:
  sb@7.0.0-alpha.50
Ok to proceed? (y)
```

**Comment by kasperpeulen** [comment]
@yarinsa You should import this type from the framework:

```ts
import type { StorybookConfig } from "@storybook/react-vite";
```

However, I get some issues when I try to do this:

```ts
TS2321: Excessive stack depth comparing types '{ framework: string; stories: string[]; addons: string[]; core: { builder: string; disableTelemetry: true; }; features: { storyStoreV7: true; }; typescript: { reactDocgen: string; reactDocgenTypescriptOptions: { ...; }; }; viteFinal: (config: UserConfig, { configType }: { ...; }) => Promise...>; }' and 'StorybookConfig'.
```

You can get rid of those by not explicitly typing the `viteFinal` parameters. 

```ts
 viteFinal: async (config, { configType }) => mergeConfig(config, viteConfig),
```

As they are contextually typed now. 

Seems because of the type definitions of vite 3.2 and 3.1 conflict. Shall we upgrade to vite 3.2 in the monorepo @IanVS @ndelangen?

**Comment by IanVS** [comment]
@kasperpeulen Vite 4 will be released soon.  I think we need to find a way to be more flexible with the vite dependency and types, and use whatever the user already has installed.

**Comment by dev-nicolaos** [comment]
> @yarinsa You should import this type from the framework:
> 
> ```ts
> import type { StorybookConfig } from "@storybook/react-vite";
> ```

Just a heads up, it looks like [the example in the docs](https://storybook.js.org/docs/7.0/react/builders/vite#typescript) needs to be updated for this.

**Comment by IanVS** [comment]
@dev-nicolaos you're right.  Would you be willing to submit a PR to update it?

**Comment by jonniebigodes** [comment]
@dev-nicolaos, you're right about it. This is part of the body of work still undergoing for 7.0, but if you're interested in contributing and fixing that example, I'd be more than glad to follow up with you on it. 

Looking forward to seeing the pull request up.

Have a great day.

Stay safe
