### ISSUE TITLE
[Bug]: Buffer is not defined when using Next.js 13 & async components

### ISSUE THREAD

**Issue by bmarshall511** [storybookjs/storybook#19872]
### Describe the bug

Here's the component in question: https://github.com/Entermedia-LLC/nextjs-components/tree/671e9ca8da781a2a1a16c4bc84b1a127d413b3c1/templates/Page

When running storybook on Next.js 13 looking at a component in the `app` directory, getting:

```
Unexpected error while loading ./app/components/templates/Page/Page.stories.tsx: Buffer is not defined
 ReferenceError: Buffer is not defined
```

Only happens when running storybook.

Found this https://github.com/storybookjs/storybook/issues/17344 and mentioned something about webpack, but if I remember right, Next.js no longer used webpack, instead their own system called Turbopack: https://nextjs.org/blog/next-13#introducing-turbopack-alpha

### To Reproduce

```shell
1. Clone https://github.com/Highfivery/nextjs-starter
2. `npm install`
3. `npm run storybook`
```

### System

```shell
Need to install the following packages:
  sb@7.0.0-alpha.50

Do I need to do that?
```

**Comment by borispoehland** [comment]
Any progress on this?

**Comment by shilman** [comment]
closing as duplicate to #21540
