### ISSUE TITLE
[Feature Request]: Add sun and moon icons to be used in theme switcher toolbars

### ISSUE THREAD

**Issue by JReinhold** [storybookjs/storybook#19884]
### Is your feature request related to a problem? Please describe

Adding a theme switcher to Storybooks is a pretty common scenario, and it's fairly easy to do as shown in this recent video:

https://youtu.be/FVg9eWQsUbU

The only thing missing is really good icons to be used in the toolbar options.

### Describe the solution you'd like

It seems like the industry has settled for the sun/moon analogy for a theme switcher, so I suggest we make three icons to support that:

1. Sun
2. Moon
3. Both, split in half

See prior art at Iconify:
["Theme" search](https://icon-sets.iconify.design/?query=theme
)
["Light" search](https://icon-sets.iconify.design/?query=light
)
["Dark" search](https://icon-sets.iconify.design/?query=dark
)

### Describe alternatives you've considered

The Iconify searches above also shows icons using lamps and lightbulbs which might also be an option.

### Are you able to assist to bring the feature to reality?

no

### Additional context

The best solution I've found with the current set of icons is using filled/stroked circles - which is also what we do for our UI Storybook. I think it's a bit too vague, and it has the downside that if the browser is in dark theme it will actually have the reverse meaning, as shown here:

![screenshot of a theme picker in dark mode](https://user-images.githubusercontent.com/5678122/202679010-ef38077a-288d-4def-a9ba-3dad6b7e8660.png)

**Comment by shilman** [comment]
Yee-haw!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.30 containing PR #20621 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
