### ISSUE TITLE
[Bug]: Storysource not working for v7

### ISSUE THREAD

**Issue by TomDoFuture** [storybookjs/storybook#19882]
### Describe the bug

Hangs on loading source...

### To Reproduce

Create Project with Svelte
Add SB to it @next so alpha.50
Add the storysource plugin then create a component and a story for it
Hangs on Loading source...

### System

```shell
System:
    OS: macOS 12.3.1
    CPU: (4) x64 Intel(R) Core(TM) i3-8100B CPU @ 3.60GHz
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.15.1/bin/yarn
    npm: 8.12.2 - ~/.nvm/versions/node/v16.15.1/bin/npm
  Browsers:
    Chrome: 107.0.5304.110
    Safari: 15.4
  npmPackages:
    @storybook/addon-essentials: ^7.0.0-alpha.50 => 7.0.0-alpha.50 
    @storybook/addon-interactions: ^7.0.0-alpha.50 => 7.0.0-alpha.50 
    @storybook/addon-links: ^7.0.0-alpha.50 => 7.0.0-alpha.50 
    @storybook/addon-postcss: ^2.0.0 => 2.0.0 
    @storybook/addon-storysource: ^7.0.0-alpha.50 => 7.0.0-alpha.50 
    @storybook/svelte: ^7.0.0-alpha.50 => 7.0.0-alpha.50 
    @storybook/svelte-vite: ^7.0.0-alpha.50 => 7.0.0-alpha.50 
    @storybook/testing-library: ^0.0.13 => 0.0.13
```

### Additional context

I tested this on Sveltekit , but there is no reason why it would just break on Svelte

**Comment by TomDoFuture** [comment]
@IanVS

**Comment by shilman** [comment]
Egads!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.0 containing PR #20147 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
