### ISSUE TITLE
Backport #19623 (overriding `WebView`/`UrlStore`) to 6.5

### ISSUE THREAD

**Issue by tmeasday** [storybookjs/storybook#19904]
### Is your feature request related to a problem? Please describe

React Native wants to be able to define a non-web version of the view+store without needing to monkey patch and polyfill.

We have a solution in https://github.com/storybookjs/storybook/pull/19623 but we need to backport it to 6.5 

### Describe the solution you'd like

As https://github.com/storybookjs/storybook/pull/19623 but leaving out the complex typing changes.

**Comment by yannbf** [comment]
Quick reminder to also change code in the instrumenter if you're backporting this to 6.5, else addon-interactions will break as it refers to `urlStore` to get the story ids.

**Comment by tmeasday** [comment]
This got sorted out in https://github.com/storybookjs/storybook/pull/19975 -- the change was really simple in 6.x so the above won't be an issue. Thanks for highlighting @yannbf
