### ISSUE TITLE
[Bug]: next/link className props is not available in storybook

### ISSUE THREAD

**Issue by yagiz-noonlight** [storybookjs/storybook#19918]
### Describe the bug

Using next/link component with className results in empty className in storybook, but works correctly in Next.js 13

### To Reproduce

```shell
- Create a next.js project with storybook.
- Add a component that uses next/link
- Add className property to next/link component.
- Visit storybook (the component does not have any class)
```

### System

```shell
Environment Info:

  System:
    OS: macOS 12.6.1
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 19.0.1 - /opt/homebrew/bin/node
    npm: 8.19.2 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 107.0.5304.110
    Safari: 16.1
  npmPackages:
    @storybook/addon-actions: ^6.5.13 => 6.5.13
    @storybook/addon-essentials: ^6.5.13 => 6.5.13
    @storybook/addon-interactions: ^6.5.13 => 6.5.13
    @storybook/addon-links: ^6.5.13 => 6.5.13
    @storybook/addon-postcss: ^2.0.0 => 2.0.0
    @storybook/builder-webpack5: ^6.5.13 => 6.5.13
    @storybook/manager-webpack5: ^6.5.13 => 6.5.13
    @storybook/react: ^6.5.13 => 6.5.13
    @storybook/testing-library: ^0.0.13 => 0.0.13
```

**Comment by doougui** [comment]
The same thing happened to me. Even inline styles are not being applied for some reason.

![image](https://user-images.githubusercontent.com/44846329/203436493-9818a189-aa83-4320-acc2-57c670a18e78.png)
![image](https://user-images.githubusercontent.com/44846329/203436504-dd77e104-9555-4285-8a52-6cc87837882d.png)

**Comment by doougui** [comment]
Seems like this is related to this issue: https://github.com/storybookjs/storybook/issues/19813.

**Comment by valentinpalkovic** [comment]
https://github.com/storybookjs/storybook/releases/tag/v7.0.0-alpha.52 was released, which contains the PR https://github.com/storybookjs/storybook/pull/19834 that fixes this issue. Upgrade today to the @next NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
