### ISSUE TITLE
[Bug]: File controls are not resetting in storybook

### ISSUE THREAD

**Issue by abhijeet-shelhalkar** [storybookjs/storybook#19921]
### Describe the bug

File controls (name of previous selected file) not resetting.

1. before reset button clicked.
![before-reset](https://user-images.githubusercontent.com/32697900/203303874-d2aa28bc-12fe-46fe-8a67-5ee6ef07b329.png)
2. after reset button clicked.
![after-reset](https://user-images.githubusercontent.com/32697900/203303873-ebb07700-17f4-434a-82d8-0a5ede7ae506.png)

**Note:** I am using mdx for story writing. and using "@storybook/web-components": "^6.5.8"

### System

```shell
Environment Info:

  System:
    OS: Windows 11
  Binaries:
    Node: v16.15.0
    npm: .5.5
  Browsers:
    Chrome: 107.0.5304.63
    Safari: 16.1
  npmPackages:
    "@storybook/addon-a11y": "^6.5.8",
    "@storybook/addon-actions": "^6.5.8",
    "@storybook/addon-controls": "^6.5.8",
    "@storybook/addon-docs": "^6.5.8",
    "@storybook/addon-essentials": "^6.5.8",
    "@storybook/addon-knobs": "^6.4.0",
    "@storybook/addon-links": "^6.5.8",
    "@storybook/addon-storysource": "^6.5.8",
    "@storybook/addon-viewport": "^6.5.8",
    "@storybook/web-components": "^6.5.8",
```

**Comment by BikashSah999** [comment]
@shilman @ndelangen  I can reproduce this issue so can I work on this issue?

**Comment by BikashSah999** [comment]
Hi @shilman  @ndelangen  the PR for this issue is ready for review. Could you please review it?

**Comment by shilman** [comment]
Ermahgerd!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.1 containing PR #19998 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
