### ISSUE TITLE
[Bug]: I have a error compiling Storybook with ifram

### ISSUE THREAD

**Issue by JuanjoOrt** [storybookjs/storybook#19947]
### Describe the bug

Hello,

When I compile my storybook to static versión, everythings works. But when I open it, have this issue:

`iframe.html:373          GET http://localhost:63342/assets/iframe.38d22227.js net::ERR_ABORTED 404 (Not Found)`

**Comment by catnuko** [comment]
same issue

**Comment by Semigradsky** [comment]
@JuanjoOrt @catnuko You fixed it? I have the same
