### ISSUE TITLE
[Bug]: Cannot GET / when starting Storybook

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#19968]
### Describe the bug

In Storybook 7.0.0-alpha.54, once running Storybook, the browser is instantly opened with an error:`Cannot GET /`

![image](https://user-images.githubusercontent.com/1671563/204021955-f8ea05e7-3ca4-4930-9515-cbaf62a3d0b2.png)

Doing a refresh fixes the issue.

### To Reproduce

```shell
Create a repro with Storybook 7.0.0-alpha.54 and run `yarn storybook`
```

**Comment by shilman** [comment]
Jeepers creepers!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-alpha.55 containing PR #20005 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```
