### ISSUE TITLE
[Bug]: Wrong link in storybook page

### ISSUE THREAD

**Issue by OlegStrokan** [storybookjs/storybook#19961]
### Describe the bug

![IMAGE 2022-11-25 08:23:20](https://user-images.githubusercontent.com/31828361/203924048-5bb7ed15-4058-40ff-a81b-a0e4683f0da9.jpg)
I find incorrect link in control panel in storybook page.
This link looks like - https://github.com/storybookjs/storybook/blob/next/addons/controls/README.md#writing-stories
But I received error:
![IMAGE 2022-11-25 08:27:00](https://user-images.githubusercontent.com/31828361/203924711-43429015-fd0b-4c23-b1c8-f1cac7ca3aa1.jpg)
Then i try to find correct link in your github and i think this link - https://github.com/storybookjs/storybook/blob/next/docs/writing-stories/introduction.md
will be correct
Please fix this issue

**Comment by jonniebigodes** [comment]
@OlegStrokan, thanks for reaching out to us with your issue. We appreciate it. Hope you don't mind, but I'm closing this as it's already being addressed in #19803. If you check the pull request description, you'll also see that some other Storybook users have already reported it and we're on top of it.

Hope you have a great weekend.

Stay safe
