### ISSUE TITLE
[Bug]: Interactions panel duplicating entries in Storybook 7.0.0-alpha.48

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#19969]
### Describe the bug

When remounting the component (or clicking on interactions debugger for anything, either step back or forward), the panel is not behaving correctly.

**Alpha 47:**
![2022-11-25 17 53 04](https://user-images.githubusercontent.com/1671563/204029346-fff0a98e-ad4c-4669-bd01-244c0ea1c801.gif)

**Alpha 48:**
![2022-11-25 17 56 10](https://user-images.githubusercontent.com/1671563/204029338-d1fd2a0b-b528-446a-8edb-4247a1c58bd6.gif)

The bug was introduced in https://github.com/storybookjs/storybook/releases/tag/v7.0.0-alpha.48

### To Reproduce

**Alpha 47:**
https://634ff0d0ec053b270775979d-nkvqkczlop.chromatic.com/?path=/story/addons-interactions-basics--async-wait-for

**Alpha 48:**
https://634ff0d0ec053b270775979d-nclepguyht.chromatic.com/?path=/story/addons-interactions-basics--async-wait-for

**Comment by yannbf** [comment]
Also for some reason the spies changed.

**Alpha 47:**
<img width="409" alt="image" src="https://user-images.githubusercontent.com/1671563/204043014-f56a6f4f-563f-4a03-83f1-a7be9e2040bc.png">

**Alpha 48:**
<img width="379" alt="image" src="https://user-images.githubusercontent.com/1671563/204043026-d90a0b55-4057-4090-bf98-64c283b5854a.png">

**Comment by tmeasday** [comment]
Hmm, I can't see anything in the diff between those two versions that could be relevant @yannbf. What are the versions of the interactions addon / testing-library dependencies in your repros there?

**Comment by yannbf** [comment]
> Hmm, I can't see anything in the diff between those two versions that could be relevant @yannbf. What are the versions of the interactions addon / testing-library dependencies in your repros there?

interactions: equivalent alphas
testing-library: 0.0.14-next

**Comment by shilman** [comment]
w00t!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-alpha.56 containing PR #20004 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
