### ISSUE TITLE
Extra sidebar entries in docs-only MDX with local variables

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#19965]
### Describe the bug

Originally reported at https://discord.com/channels/486522875931656193/1045086330268422254/1045086330268422254

A `.stories.mdx` file with a local variable will cause the following extra sidebar entries:

![](https://cdn.discordapp.com/attachments/1045086330268422254/1045086330696249446/image.png)

### To Reproduce

```md
// src/Introduction.stories.mdx
import { Meta } from '@storybook/addon-docs';

<Meta title="Parent/Child" />

# Hello world

export const TestControl = () => (<p>Hello</p>);

<TestControl />
<TestControl />
```

### Workarounds
- If you rename the file to `Introduction.mdx` it solves the problem
- If you delete the `export const TestControl = () => (<p>Hello</p>);` local variable declaration it also solves the problem

**Comment by cmcnicholas** [comment]
I have also a third workaround, put the export in an additional file e.g. `TestControl.tsx` and then reference that in your MDX file with an `import`

**Comment by tmeasday** [comment]
@shilman this looks like a bug in `csf-tools`. The issue is in the story indexer the `__page` story does not have the `docsOnly` parameter:

(if I add `console.log(absolutePath, csf.stories)` to `StoryIndexGenerator:230`), I see:

```
/Users/tom/GitHub/storybookjs/storybook/sandbox/react-vite-default-ts/src/stories/Introduction.stories.mdx [
  {
    id: 'parent-child--page',
    name: 'Page',
    parameters: { __isArgsStory: false, __id: 'parent-child--page' }
  }
]
```

However, in the browser I see:

<img width="457" alt="image" src="https://user-images.githubusercontent.com/132554/205432915-4839f07f-a93b-4204-b5fa-001e877b806c.png">

**Comment by shilman** [comment]
Huzzah!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.7 containing PR #20255 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
