### ISSUE TITLE
[Bug]: Styling and CSS (Uncaught TypeError: __webpack_require__.n is not a function)

### ISSUE THREAD

**Issue by LukasMachetanz** [storybookjs/storybook#19981]
### Describe the bug

Having a storybook-configuration with custom [styles](https://storybook.js.org/docs/angular/configure/styling-and-css#nx-with-angular-13) within an [nx](https://nx.dev/)-workspace throws an unexpected error within the browser console - see screenshot.

<img width="1054" alt="Screenshot 2022-11-28 at 10 56 46" src="https://user-images.githubusercontent.com/44839051/204248611-aee69400-4103-44a0-b5a7-4879fffc1af6.png">

Using [Cypress](https://www.cypress.io/) together with storybook results in failing test suite of the e2e specs as an uncaught exception is thrown due to this bug.

### To Reproduce

- Create a **nx-workspace** like `npx create-nx-workspace my-workspace`
   - _Choose your style:_ integrated
   - _What to create in the new workspace:_ angular
   - _Application name:_ web-app
   - _Default stylesheet format:_ SCSS
   - _Enable distributed caching to make your CI faster:_ No
- Create a **library** like `nx g @nrwl/angular:lib my-lib`
- Create a **component** within the library like `cd libs/my-lib/src/lib` and `nx g @nrwl/angular:c my-comp`
- Create a **storybook-configuration** for the generated library like `nx g @nrwl/angular:storybook-configuration my-lib` (all questions can be answered with yes)
- Create a **stylesheet** `styles.scss` and include it within the section `build:storybook` of `project.json` as explained in [Styling and CSS](https://storybook.js.org/docs/angular/configure/styling-and-css#nx-with-angular-13) - `"styles": ["libs/my-lib/src/styles.scss"]`
- Start storybook with `nx run my-lib:storybook`
- Have a look at the console in the browser

**Comment by samvloeberghs** [comment]
Seems to be fixed with last version of nx and storybook libraries.
Can you try upgrading? @LukasMachetanz

**Comment by LukasMachetanz** [comment]
I run `nx migrate latest` which installs version `15.2.4` of `@nrwl/storybook`, but the problem still exists. Which version do you use @samvloeberghs?

**Comment by samvloeberghs** [comment]
Same here; 15.2.4 fixed it.
Also check your storybook dependencies to be latest @LukasMachetanz

**Comment by LukasMachetanz** [comment]
I can confirm that the described issue is resolved using the latest versions.

**Comment by samvloeberghs** [comment]
The bug reappeared when I migrated to latest nx:
v15.2.4 to v15.3.3.
Storybook dependencies remained the same.

**Comment by jogelin** [comment]
Same here, doing the migration to latest Nx 15.3.3 and storybook 6.5.14 and I have:
![image](https://user-images.githubusercontent.com/954509/208116533-9e7744e7-0a63-46b7-b3a3-aa63cd3c95a6.png)

I found related PR here:
- https://github.com/storybookjs/storybook/pull/19937
- https://github.com/storybookjs/storybook/pull/19875

**Comment by shilman** [comment]
We probably need to patch this back to 6.5 also @valentinpalkovic  WDYT?

https://github.com/storybookjs/storybook/pull/20287

**Comment by samvloeberghs** [comment]
@shilman @valentinpalkovic can you please re-open the bug to be sure we track this?
Thanks a lot for investigating this!

**Comment by shilman** [comment]
@samvloeberghs it's patched back here. can you please test? https://github.com/storybookjs/storybook/releases/tag/v6.5.15-alpha.1

**Comment by jogelin** [comment]
@shilman @samvloeberghs for me it works!

Let's migrate all Angular Material Components from legacy to v15 now :D

**Comment by shilman** [comment]
Nice!! I'll do a full release now

**Comment by samvloeberghs** [comment]
@shilman
Can also confirm it works, thanks, you guys rock!

**Comment by LukasMachetanz** [comment]
@samvloeberghs, sorry for reopening the issue so late. 

It seems that the problem is resolved again and that the issue can be closed, right?
