### ISSUE TITLE
Unexpected reserved word 'interface'

### ISSUE THREAD

**Issue by soeasyjx** [storybookjs/storybook#19995]
### Describe the bug

1. Initialize the project using `npx storybook@next init --type react`

2. Write components in typescript, define interfaces，An error occurred starting the project

3. Run a command `npm run storybook`

Directory structure：
```tree
    storybook-react-doc-v7.0
├── package-lock.json
├── package.json
├── src
│   └── Button.tsx
└── stories
    ├── Button.jsx
    ├── Button.stories.tsx
    ├── Header.jsx
    ├── Header.stories.js
    ├── Introduction.stories.mdx
    ├── Page.jsx
    ├── Page.stories.js
    ├── assets
    │   ├── code-brackets.svg
    │   ├── colors.svg
    │   ├── comments.svg
    │   ├── direction.svg
    │   ├── flow.svg
    │   ├── plugin.svg
    │   ├── repo.svg
    │   └── stackalt.svg
    ├── button.css
    ├── header.css
    ├── myIframe.stories.mdx
    └── page.css
```

### src/Button.tsx

Component Development Directory：

```tsx
import React from "react";

interface IButtonProps {
  /**
   * 文字
   */
  text: string;
}

export const Button = (props:IButtonProps) => {
  return <div>{props.text}</div>;
};
```

### stories/Button.stories.tsx

**Reference components to write stories**

```tsx
import React from 'react';
import { Button } from '../src/Button';

export default {
  /* 👇 The title prop is optional.
   * See https://storybook.js.org/docs/7.0/react/configure/overview#configure-story-loading
   * to learn how to generate automatic titles
   */
  tags: ['docsPage'],
  title: 'Button',
  component: Button,
};

/*
 *👇 Render functions are a framework specific feature to allow you control on how the component renders.
 * See https://storybook.js.org/docs/7.0/react/api/csf
 * to learn how to use render functions.
 */
export const Text = {
    args:{
        text:"xxxxx"
    },
  render: (props) => <Button text={props.text} ></Button>,
};
```

### package.json
```json
{
  "name": "storybook-react-doc-v7.0",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "storybook": "storybook dev -p 6006",
    "build-storybook": "storybook build"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@storybook/addon-essentials": "^7.0.0-alpha.54",
    "@storybook/addon-interactions": "^7.0.0-alpha.54",
    "@storybook/addon-links": "^7.0.0-alpha.54",
    "@storybook/addons": "^6.5.13",
    "@storybook/react": "^7.0.0-alpha.54",
    "@storybook/react-webpack5": "^7.0.0-alpha.54",
    "@storybook/testing-library": "^0.0.14-next.0",
    "@storybook/theming": "^6.5.13",
    "storybook": "^7.0.0-alpha.54"
  },
  "dependencies": {
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  }
}
```

Results of operation：
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/17918538/204420033-d43b5d34-cde1-4c3e-a875-f743834d2436.png">

### System

```shell
Environment Info:

  System:
    OS: macOS 12.5.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 3.2.0 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Chrome: 107.0.5304.110
    Safari: 15.6.1
  npmPackages:
    @storybook/addon-essentials: ^7.0.0-alpha.54 => 7.0.0-alpha.54 
    @storybook/addon-interactions: ^7.0.0-alpha.54 => 7.0.0-alpha.54 
    @storybook/addon-links: ^7.0.0-alpha.54 => 7.0.0-alpha.54 
    @storybook/addons: ^6.5.13 => 6.5.13 
    @storybook/react: ^7.0.0-alpha.54 => 7.0.0-alpha.54 
    @storybook/react-webpack5: ^7.0.0-alpha.54 => 7.0.0-alpha.54 
    @storybook/testing-library: ^0.0.14-next.0 => 0.0.14-next.0 
    @storybook/theming: ^6.5.13 => 6.5.13
```

**Comment by ntvangoor** [comment]
I also had this issue when declaring types for parameters
It seems that tsx is interpreted as jsx

**Comment by shilman** [comment]
Do you a have a reproduction repo you can share? If not, can you create one? See [how to create a repro](https://storybook.js.org/docs/react/contribute/how-to-reproduce). We prioritize issues with reproductions over those without. Thank you! 🙏

**Comment by jonesmac** [comment]
Same issue for me.  Here's the repo with the error - https://github.com/jonesmac/sb-v7-typescript

Try to start it with `yarn storybook dev` and you will see the error in the screenshot of the OP.

Interestingly, if you try to add the babelrc config via `yarn storybook babelrc` it does add the config and packages to the package.json file.  However, those new presets DO NOT seem to show up in the actual webpack config.

If you run `yarn storybook dev --debug-webpack`, you can see the module rules show babel should be used for .tsx files, however none of the new presets are present in the config:

``` javascript
module: {
    rules: [
      { test: /\.m?js$/, type: 'javascript/auto' },
      { test: /\.m?js$/, resolve: { fullySpecified: false } },
      {
        test: /\.(mjs|tsx?|jsx?)$/,
        use: [
          {
            loader: '/Users/mattjones/XYLabs/repos/sb-v7-test/node_modules/babel-loader/lib/index.js',
            options: {
              cacheDirectory: '/Users/mattjones/XYLabs/repos/sb-v7-test/node_modules/.cache/storybook/babel',
              // Below should include @babel/preset-react and @babel/preset-typescript
              presets: [
                [
                  '/Users/mattjones/XYLabs/repos/sb-v7-test/node_modules/@babel/preset-react/lib/index.js',
                  { runtime: 'automatic' }
                ]
              ],
              plugins: [
                '/Users/mattjones/XYLabs/repos/sb-v7-test/node_modules/babel-plugin-add-react-displayname/index.js'
              ],
              overrides: [
                {
                  test: /\.(story|stories).*$/,
                  plugins: [
                    '/Users/mattjones/XYLabs/repos/sb-v7-test/node_modules/babel-plugin-named-exports-order/index.js'
                  ]
                },
                {
                  test: /\.(cjs|mjs|jsx?)$/,
                  plugins: [
                    [
                      '/Users/mattjones/XYLabs/repos/sb-v7-test/node_modules/babel-plugin-react-docgen/lib/index.js'
                    ]
                  ]
                }
              ]
            }
          }
        ],
        include: [ '/Users/mattjones/XYLabs/repos/sb-v7-test' ],
        exclude: /node_modules/
      },
      { test: /\.md$/, type: 'asset/source' },
      {
        test: /(stories|story)\.mdx$/,
        use: [
          {
            loader: '/Users/mattjones/XYLabs/repos/sb-v7-test/node_modules/@storybook/mdx2-csf/loader.js',
            options: {
              skipCsf: false,
              mdxCompileOptions: {
                providerImportSource: '@storybook/addon-essentials/docs/mdx-react-shim',
                remarkPlugins: [ [Function: slug], [Function: externalLinks] ]
              },
              jsxOptions: {}
            }
          }
        ]
      },
      {
        test: /\.mdx$/,
        exclude: /(stories|story)\.mdx$/,
        use: [
          {
            loader: '/Users/mattjones/XYLabs/repos/sb-v7-test/node_modules/@storybook/mdx2-csf/loader.js',
            options: {
              skipCsf: true,
              mdxCompileOptions: {
                providerImportSource: '@storybook/addon-essentials/docs/mdx-react-shim',
                remarkPlugins: [ [Function: slug], [Function: externalLinks] ]
              },
              jsxOptions: {}
            }
          }
        ]
      },
      {
        test: /\.css$/,
        sideEffects: true,
        use: [
          '/Users/mattjones/XYLabs/repos/sb-v7-test/node_modules/style-loader/dist/cjs.js',
          {
            loader: '/Users/mattjones/XYLabs/repos/sb-v7-test/node_modules/css-loader/dist/cjs.js',
            options: { importLoaders: 1 }
          }
        ]
      },
      {
        test: /\.(svg|ico|jpg|jpeg|png|apng|gif|eot|otf|webp|ttf|woff|woff2|cur|ani|pdf)(\?.*)?$/,
        type: 'asset/resource',
        generator: { filename: 'static/media/[path][name][ext]' }
      },
      {
        test: /\.(mp4|webm|wav|mp3|m4a|aac|oga)(\?.*)?$/,
        type: 'asset',
        parser: { dataUrlCondition: { maxSize: 10000 } },
        generator: { filename: 'static/media/[path][name][ext]' }
      },
      { test: /\.m?js$/, type: 'javascript/auto' },
      { test: /\.m?js$/, resolve: { fullySpecified: false } }
    ]
  },
```

**Comment by jonesmac** [comment]
Actually, I think I got it to work.  After you run `yarn storybook babelrc` it looks like you need to actually install the packages 😞 .  Once I did that, I was able to get the demo repo to work.  I also added type checking so @shilman maybe this will help you with your setup.

**Comment by shilman** [comment]
@ndelangen we should make `sb babelrc` install the packages if it doesn't already

**Comment by jonesmac** [comment]
@shilman First, I tried to manually add the new presets to the webpack config via the webpackFinal callback.  When I went to look for the paths where I expected them, they weren't there which led me to believe they weren't installed automatically.  Is the expectation that --debug-webpack output would show the additional presets added in the .babelrc.json file?

**Comment by shilman** [comment]
@jonesmac No unfortunately I don't think that it will show there. That only shows how we configure webpack, but I believe the Babel config loading happens "magically" by Babel. There are ways to debug this and I believe we've added them to the docs. However I'll update the migration guide to be more explicit about all this. Thanks for debugging and helping make the upgrade smoother!

**Comment by ndelangen** [comment]
It does install the packages, if it can. @shilman

**Comment by aserputov** [comment]
@ndelangen  any news how to solve the issue?

**Comment by ndelangen** [comment]
@aserputov ensuring there's a babel config that handles typescript should make things work.

the command: `sb babelrc` should help with this.

Internally we've had a discussion to perhaps detect usage of typescript and add that to the default babel config. But in 7.0 we try to stay away from shipping with too much default config.

- detecting typescript usage might not be simple (which filename, which directory? from where? throw monorepo setups, symlinks, versions, different package managers into the mix, and things become complex fast.
- adding a babel preset by default sounds harmless, but in order to do so, we have to depend on it. This adds the possibility of duplicate versions installed by the package manager, which if that happens could lead to the preset being added twice, causing all sorts of issues including possible performance degradation.

You ask me "how to solve", my questions to you is: "how did this occur"?
How is your codebase using typescript without having a babel config that includes typescript?
If it doesn't have a babel config at all, what is doing the transpilation?

**Comment by aserputov** [comment]
Thanks Norbert, I will try that!

**Comment by BirmiiiYO** [comment]
Hi, install @babel/preset-typescript if ypu dont have and chagne .babelrc w this one

**Comment by shilman** [comment]
@yannbf can you please give this issue a quick look and see if we need to do more work on `sb babelrc`?

**Comment by shilman** [comment]
Solved by @yannbf 's automigration that prompts for babelrc
