### ISSUE TITLE
[Bug]: Web component installation snippet missing

### ISSUE THREAD

**Issue by geromegrignon** [storybookjs/storybook#20008]
### Describe the bug

On the [Installation page](https://storybook.js.org/docs/web-components/get-started/install) of the Web Component documentation, the following snippet is missing:

![image](https://user-images.githubusercontent.com/32737308/204545064-ea0a6c1e-7398-4a2d-b536-dc0981d7a99c.png)

But as it's clearly defined in the md snippet without any typo:

```
<FeatureSnippets paths={[ 'get-started/installation-command-section/angular.mdx', 'get-started/installation-command-section/ember.mdx', 'get-started/installation-command-section/html.mdx', 'get-started/installation-command-section/preact.mdx', 'get-started/installation-command-section/react.mdx', 'get-started/installation-command-section/svelte.mdx', 'get-started/installation-command-section/vue.mdx', 'get-started/installation-command-section/web-components.mdx', ]} />
```

### To Reproduce

```shell
- visit the vue installation: https://storybook.js.org/docs/vue/get-started/install
- the snippet is present

- visit the web components snippet: https://storybook.js.org/docs/web-components/get-started/install
- the snippet is missing
```

### Additional context

Feel free to make me contribute to the resolution of this bug if you find out the reason, saving you some time :)

**Comment by jonniebigodes** [comment]
@geromegrignon, once again thanks for taking the time to reach out to us. We're aware of the fact and it's actually being tracked [here](https://github.com/storybookjs/frontpage/issues/228) if you're interested in helping us out let's continue the conversation in the issue I've linked and close this one out. Sounds good to you?

**Comment by geromegrignon** [comment]
@jonniebigodes sounds good indeed.
I close this one and will investigate based on the existing info.
