### ISSUE TITLE
Make index failures result in build failures

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#20044]
### Describe the bug

Storybook generates a "story index" on startup which generates the sidebar.

Currently, when a story fails to parse, it will be skipped. This is "unsafe" in that it can hide problems in your storybook. Instead, the story index should fail to generate and your Storybook should break.

**Comment by ndelangen** [comment]
@yannbf I believe you ran into some situation where this kept happening to you, do you remember? Could you assist by describing that situation in which it happened?

**Comment by tmeasday** [comment]
Closing this in favour of https://github.com/storybookjs/storybook/issues/20663
