### ISSUE TITLE
[Feature Request]: Add `preact-vite` framework to v7

### ISSUE THREAD

**Issue by estherkim** [storybookjs/storybook#20052]
### Describe the solution you'd like

I have a project using vite and preact, and would like to install storybook v7. Having the framework `preact-vite` for v7 would be great!

### Are you able to assist to bring the feature to reality?

yes, I can

**Comment by shilman** [comment]
Thanks for volunteering to help @estherkim. If you're willing to work on this, we'd love to collaborate in the `#contributing` of [the Storybook Discord](https://discord.gg/storybook).

**Comment by KrofDrakula** [comment]
@estherkim An implementation is being worked on in #20390. There are no NPM packages published for `preact-vite` until we get it tested, verified & shipped first.

**Comment by shilman** [comment]
Yowza!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.16 containing PR #20390 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
