### ISSUE TITLE
[Bug]: remove @storybook/*-webpack4 from @storybook/core-server

### ISSUE THREAD

**Issue by LucaVazz** [storybookjs/storybook#20062]
### Describe the bug

As far as I understand the concept of @storybook/core-server, it is supposed to be independent of the builder.

However, currently in its package.json, there is a reference to @storybook/builder-webpack4 and @storybook/manager-webpack4:  
https://github.com/storybookjs/storybook/blob/v6.5.14/lib/core-server/package.json#L43  
https://github.com/storybookjs/storybook/blob/v6.5.14/lib/core-server/package.json#L49

Instead, I'd suggest its package.json to be structured as the one of @storybook/core, specifiying the webpack packages as optional peer depenedencies:  
https://github.com/storybookjs/storybook/blob/v6.5.14/lib/core/package.json#L52

This would be primarily to reduce installation size (i.e. our project does not need webpack4 dependencies as we've switched to webpack5 overall, including storybook).  
Furthermore, in our project #14294 still appears during npm install, even though #13990 is merged into webpack5 packages.

### To Reproduce

- Only place @storybook/builder-webpack5 and @storybook/manager-webpack5 in your project's package.json
- Run npm i
- Run npm ls @storybook/builder-webpack4

Current output:
```
[redacted project info]
└─┬ @storybook/core-server@6.5.13
  └── @storybook/builder-webpack4@6.5.13
```

Expected output:
```
[redacted project info]
└── (empty)
```

### System

```shell
Environment Info:

  System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz
  Binaries:
    Node: 16.18.1 - ~\AppData\Local\nvs\node\16.18.1\x64\node.EXE
    npm: 8.19.2 - ~\AppData\Local\nvs\node\16.18.1\x64\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (107.0.1418.56)
  npmPackages:
    @storybook/addon-a11y: 6.5.13 => 6.5.13
    @storybook/addon-essentials: 6.5.13 => 6.5.13
    @storybook/addon-interactions: 6.5.13 => 6.5.13
    @storybook/addon-storysource: 6.5.13 => 6.5.13
    @storybook/angular: 6.5.13 => 6.5.13
    @storybook/builder-webpack5: 6.5.13 => 6.5.13
    @storybook/core-server: 6.5.13 => 6.5.13
    @storybook/jest: 0.0.10 => 0.0.10
    @storybook/manager-webpack5: 6.5.13 => 6.5.13
    @storybook/mdx2-csf: 0.0.3 => 0.0.3
    @storybook/testing-library: 0.0.13 => 0.0.13
```

**Comment by JasonKleban** [comment]
And closely related:`"@types/webpack": ^4.41.26` I think should be removed because webpack 5 ships with its own type definitions which conflict with `@types/webpack` in some circumstances.

**Comment by jagomf** [comment]
Same issue here.
Just migrated to Angular 14, which requires webpack 5, and found out that enabling usage of webpack 5 in Storybook is rather useless because there are inner dependencies forcing usage of webpack 4:

This is what `npm ls webpack` shows:
```
[project info]
├─┬ @angular-devkit/build-angular@14.2.10
│ └── webpack@5.74.0 
├─┬ @storybook/angular@6.5.14
│ ├─┬ @storybook/core@6.5.14
│ │ └─┬ @storybook/core-server@6.5.14
│ │   ├─┬ @storybook/builder-webpack4@6.5.14
│ │   │ └── UNMET PEER DEPENDENCY webpack@4.46.0 
│ │   ├─┬ @storybook/manager-webpack4@6.5.14
│ │   │ └── webpack@4.46.0 
│ │   └── webpack@4.46.0 
│ ├─┬ @storybook/core-common@6.5.14
│ │ └── webpack@4.46.0 
│ └── webpack@5.75.0  deduped
├─┬ @storybook/builder-webpack5@6.5.14
│ └── webpack@5.75.0  deduped
├─┬ @storybook/manager-webpack5@6.5.14
│ └── webpack@5.75.0  deduped
```
And this is causing the #17014 error as a consequence: compilation fails because there are webpack 4 internals being used instead of webpack 5 ones.

I would say this is rather urgent because currently Storybook cannot be used in Angular 14 otherwise.

**Comment by shilman** [comment]
This is fixed in Storybook 7. Please try upgrading to the latest prerelease.

Migration guide: https://storybook.js.org/migration-guides/7.0

**Comment by Pazns** [comment]
@shilman :
I'm a bit disappointed, to be honest.
This is adding update pressure on a lot of third-parties for something that is definitely a bug.

_However_, I imagine that a backport in 6.5.x would be very impractical.

When is 7.x roughly expected for stable release ?
