### ISSUE TITLE
[Bug]: stuck at 99% done plugins webpack-hot-middleware webpack

### ISSUE THREAD

**Issue by CharowDEV** [storybookjs/storybook#20073]
### Describe the bug

Storybook runs great and successfully. All components are loaded as expected, but it keeps saying: 

```
99% done plugins webpack-hot-middlewarewebpack built preview 7af76c0f632076b531db in 1041ms
webpack building...
99% done plugins webpack-hot-middlewarewebpack built preview 7af76c0f632076b531db in 1055ms
```

NextJS 13.0.6
 "typescript": "4.8.4"
  "tailwindcss": "^3.2.1",
 "@storybook/react": "^6.5.13",

### To Reproduce

```shell
Repo: https://github.com/CharowDEV/charow.dev
```

### System

```shell
Environment Info:

  System:
    OS: macOS 12.5
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 19.1.0 - ~/.nvm/versions/node/v19.1.0/bin/node
    npm: 9.1.2 - ~/.nvm/versions/node/v19.1.0/bin/npm
  Browsers:
    Chrome: 107.0.5304.121
    Firefox: 106.0.5
    Safari: 15.6
  npmPackages:
    @storybook/addon-actions: ^6.5.13 => 6.5.13 
    @storybook/addon-essentials: ^6.5.13 => 6.5.13 
    @storybook/addon-interactions: ^6.5.13 => 6.5.13 
    @storybook/addon-links: ^6.5.13 => 6.5.13 
    @storybook/addon-postcss: ^2.0.0 => 2.0.0 
    @storybook/builder-webpack5: ^6.5.13 => 6.5.13 
    @storybook/manager-webpack5: ^6.5.13 => 6.5.13 
    @storybook/react: ^6.5.13 => 6.5.13 
    @storybook/testing-library: ^0.0.13 => 0.0.13
```

**Comment by RobAndrsn** [comment]
upgraded from 6.3.6 -> 6.5.14 also seeing this issue

**Comment by ManuC84** [comment]
I've got this issue now but just in one feature branch, it's working fine on main. Trying to find what's the cause.

**Comment by F3MDEV** [comment]
Is any solution for this?

**Comment by Syedateeq160** [comment]
Just run npm i

**Comment by Maybach91** [comment]
Is there any plan to fix this?

/cc @valentinpalkovic

**Comment by ndelangen** [comment]
Your repro repo gives me a 404 @CharowDEV

**Comment by CharowDEV** [comment]
> Your repro repo gives me a 404 @CharowDEV

Ah I referred to a specific branch that no longer exists, my fault! Updated the link

**Comment by gigamesh** [comment]
Still happening on 6.5.16 😞

**Comment by shilman** [comment]
Does upgrading to the latest 7.0 prerelease fix the problem?

Migration guide: https://storybook.js.org/migration-guides/7.0

**Comment by border-none** [comment]
Same problem :c

**Comment by border-none** [comment]
upgrading to the latest 7.0 prerelease helped. thanks. i hate storybook theres so much problems i had to fix just to get it running. oh my god

**Comment by shilman** [comment]
Closing this as fixed in 7.0

**Comment by Lighttree** [comment]
Maybe this help someone: https://github.com/storybookjs/storybook/issues/14405#issuecomment-1468734210

**Comment by lentilz** [comment]
Ive started to see this when trying to update from sb@6.5.16 to 7.0.7
