### ISSUE TITLE
[Bug]: @7.0.0-alpha.57 using Vite, Cannot GET /iframe.html

### ISSUE THREAD

**Issue by AlexisDoroszkiewicz** [storybookjs/storybook#20079]
### Describe the bug

Using the latest prerelease version and Vite, the first render return the following error: Cannot GET /iframe.html

the curl request is as follows and returns 404 Cannot GET /iframe.html:

curl 'http://localhost:6006/iframe.html?viewMode=docs&id=iconography--docs' \
  -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9' \
  -H 'Accept-Language: en-GB,en-US;q=0.9,en;q=0.8,fr;q=0.7' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Cookie: intercom-id-glsleifc=20253d43-5629-4f54-be19-e57beddc475e' \
  -H 'Pragma: no-cache' \
  -H 'Referer: http://localhost:6006/?path=/docs/iconography--docs' \
  -H 'Sec-Fetch-Dest: iframe' \
  -H 'Sec-Fetch-Mode: navigate' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'Upgrade-Insecure-Requests: 1' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua: "Google Chrome";v="107", "Chromium";v="107", "Not=A?Brand";v="24"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  --compressed
  
  I feel like I did nothing special, my project is almost empty
  A simple page reload solves the issue, but ideally page would load properly on first try

**Comment by ndelangen** [comment]
That's strange, because we have this code here already:
https://github.com/storybookjs/storybook/blob/8e4e29c17a299af4ebb939e4efcb0696c23ae648/code/lib/builder-vite/src/vite-config.ts#L54

**Comment by ndelangen** [comment]
I'll be fixing this today

**Comment by shilman** [comment]
Ta-da!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-alpha.62 containing PR #20123 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

**Comment by ChrisJamesC** [comment]
That's awesome. Thanks!
