### ISSUE TITLE
MDX does not display the source snippet when using render

### ISSUE THREAD

**Issue by soeasyjx** [storybookjs/storybook#20082]
### Describe the bug

1. When writing a document using the.mdx type and adding a story to it, clicking the show code button in Docs does not require the source code

2. With the `ArgsTable` component, the control column is not shown in Docs

**I don't think I have a problem with it**

## component source
Component Name: Alert
### source
```tsx
import React from "react";

interface IAlertProps {
  /**
   * 显示文案
   * @default 1112233
   * @type string
   */
  text: string;
}

export const Alert = (props: IAlertProps) => {
  const { text } = props;
  return <div>{text}</div>;
};
```

### stories

alert.stories.mdx
```
import { Canvas, Meta, Story,ArgsTable } from "@storybook/addon-docs";
import { Alert } from "./index";

<Meta title="基础组件/Alert" component={Alert} />


<Canvas withSource="open" withToolbar>
  <Story
    name="Text"
    args={{
      text: "1111"
    }}
    render={(args) => <Alert {...args} />}
  />
</Canvas>

## API
<ArgsTable of={Alert} />
```

### results
<img width="1429" alt="image" src="https://user-images.githubusercontent.com/17918538/205485648-05577956-39e5-4c7e-aba5-b2ef4d0360dd.png">

### expect

Can correctly display source code and control

### System

```shell
Environment Info:

  System:
    OS: macOS 12.5.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 3.3.0 - ~/.nvm/versions/node/v16.17.0/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
  Browsers:
    Chrome: 108.0.5359.94
    Safari: 15.6.1
  npmPackages:
    @storybook/addon-essentials: ^7.0.0-alpha.56 => 7.0.0-alpha.56 
    @storybook/addon-interactions: ^7.0.0-alpha.56 => 7.0.0-alpha.56 
    @storybook/addon-links: ^7.0.0-alpha.56 => 7.0.0-alpha.56 
    @storybook/node-logger: ^7.0.0-alpha.56 => 7.0.0-alpha.56 
    @storybook/preset-create-react-app: ^4.1.2 => 4.1.2 
    @storybook/react: ^7.0.0-alpha.56 => 7.0.0-alpha.56 
    @storybook/react-webpack5: ^7.0.0-alpha.56 => 7.0.0-alpha.56 
    @storybook/testing-library: ^0.0.13 => 0.0.13
```

**Comment by shilman** [comment]
For the controls column try:

```
<ArgsTable story="Text" />
```

When `ArgsTable` is applied to a component it hides the controls column because it doesn't have a story to control.

The source snippet might be a bug -- I need to investigate.

**Comment by shilman** [comment]
Do you a have a reproduction repo you can share? If not, can you create one? See [how to create a repro](https://storybook.js.org/docs/react/contribute/how-to-reproduce). We prioritize issues with reproductions over those without. Thank you! 🙏

**Comment by soeasyjx** [comment]
> Do you a have a reproduction repo you can share? If not, can you create one? See [how to create a repro](https://storybook.js.org/docs/react/contribute/how-to-reproduce). We prioritize issues with reproductions over those without. Thank you! 🙏

https://github.com/soeasyjx/storybook7-test.git

**Comment by soeasyjx** [comment]
> > Do you a have a reproduction repo you can share? If not, can you create one? See [how to create a repro](https://storybook.js.org/docs/react/contribute/how-to-reproduce). We prioritize issues with reproductions over those without. Thank you! 🙏
> 
> https://github.com/soeasyjx/storybook7-test.git

I created the project using the `npx create-react-app name-template typescript` directive and then `npx storybook@next init`
