### ISSUE TITLE
[Bug]: Inconsistent propTypes handling between dev + build modes in NextJs

### ISSUE THREAD

**Issue by tmeasday** [storybookjs/storybook#20087]
### Describe the bug

[JS arg types tests](https://www.chromatic.com/build?appId=634ff0454a50407deedde524&number=205) have changed the last 15 days on the `nextjs/default-js` sandbox, likely due to this PR: https://github.com/storybookjs/storybook/pull/19842

### To Reproduce

```shell
1. Checkout `next`
2. Run `yarn task --task dev --template nextjs/default-js`
3. Notice the story (http://localhost:6006/iframe.html?args=&id=renderers-react-js-argtypes--js-class-component) appears like the LHS of the Chromatic changes: https://www.chromatic.com/test?appId=634ff0454a50407deedde524&id=638be2c76de7967b8d2a22e6

4. Run `yarn task --task serve --template nextjs/default-js`
6. Notice the story (http://localhost:8001/iframe.html?args=&id=renderers-react-js-argtypes--js-class-component) appears like the RHS of the Chromatic changes: https://www.chromatic.com/test?appId=634ff0454a50407deedde524&id=638be2c76de7967b8d2a22e6
```

### Additional context

Debugging into the [`getPropDefs` function](https://github.com/storybookjs/storybook/blob/ee32804f5b69cc7a4f749c20a9403ee7f24aaf52/code/renderers/react/src/docs/extractProps.ts#L24) I'm pretty sure the difference is that the `component.propTypes` are stripped in build mode.

You can see this with (in the iframe console):

```js
c = __STORYBOOK_PREVIEW__.currentRender.storyContext()
c.parameters.component // <- no prop types in the build
```

It's clear they aren't there in the source code.

**dev**

<img width="440" alt="image" src="https://user-images.githubusercontent.com/132554/205524554-caf91b37-c90d-4596-a666-8e2faf131736.png">

**build**

<img width="442" alt="image" src="https://user-images.githubusercontent.com/132554/205524568-787786f7-e291-46fd-81bc-17bbce6b5852.png">

**Comment by valentinpalkovic** [comment]
Opened a ticket: https://github.com/vercel/next.js/issues/43725

After the feature request is accepted, I will open a PR to introduce the necessary change.

**Comment by shilman** [comment]
Zoinks!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.55 containing PR #21104 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```
