### ISSUE TITLE
[Bug]: Automigrations for Svelte-Vite projects from 6.5 to 7.0 breaks

### ISSUE THREAD

**Issue by JReinhold** [storybookjs/storybook#20080]
### Describe the bug

When running `sb@next upgrade --prerelease` in a Svelte-Vite project the `newFramework` fix will fail, which is a pretty crucial fix to apply, as other fixes depends on it.

This is what a default Svelte-Vite Storybook 6.5 `main.cjs` config looks like:

```js
module.exports = {
  "stories": [
    "../src/**/*.stories.mdx",
    "../src/**/*.stories.@(js|jsx|ts|tsx|svelte)"
  ],
  "addons": [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/addon-interactions"
  ],
  "framework": "@storybook/svelte",
  "core": {z
    "builder": "@storybook/builder-vite"
  },
  "svelteOptions": {
    "preprocess": require("../svelte.config.js").preprocess
  },
  "features": {
    "storyStoreV7": true
  }
}
```

The issue is with the `require` call under `svelteOptions`. Adding some logging to the `newFramework` fix shows this trace of events:

```
LOG "code" AT csf-tools:getFieldValue: 
{
  "preprocess": require("../svelte.config.js").preprocess
}

ReferenceError: require is not defined
    at eval (eval at getFieldValue (/Users/jeppe/dev/chromatic/storybook/code/lib/csf-tools/dist/index.js:31929:30), <anonymous>:2:47)
    at eval (eval at getFieldValue (/Users/jeppe/dev/chromatic/storybook/code/lib/csf-tools/dist/index.js:31929:30), <anonymous>:3:4)
    at eval (<anonymous>)
    at ConfigFile.getFieldValue (/Users/jeppe/dev/chromatic/storybook/code/lib/csf-tools/dist/index.js:31929:30)
    at getFrameworkOptions (/Users/jeppe/dev/chromatic/storybook/code/lib/cli/dist/generate.js:2521:33)
    at Object.check (/Users/jeppe/dev/chromatic/storybook/code/lib/cli/dist/generate.js:2573:30)
    at async automigrate (/Users/jeppe/dev/chromatic/storybook/code/lib/cli/dist/generate.js:2947:16)
    at async doUpgrade (/Users/jeppe/dev/chromatic/storybook/code/lib/cli/dist/generate.js:3548:28)
    at async withTelemetry (/Users/jeppe/dev/chromatic/storybook/code/lib/core-server/dist/cjs/withTelemetry.js:63:5)
    at async upgrade (/Users/jeppe/dev/chromatic/storybook/code/lib/cli/dist/generate.js:3556:3)
failed to check fix: newFrameworks
```

Basically when we do [`getFieldValue` on the main config, we eval it](https://github.com/storybookjs/storybook/blob/next/code/lib/csf-tools/src/ConfigFile.ts#L204), but `require` is not defined, so the eval breaks and the whole fix breaks.

This `svelteOptions` field is not supported nor required in SB 7.0, as the new Vite builder will automatically get the project's root `vite.config.js` which contains the Svelte options (correct me if I'm wrong here @IanVS).

So my suggestion to this would be to write an automigration that removes `svelteOptions` for any valid projects, and apply that migration **before** the `newFramework` migration.
A valid project would be one that has `@storybook/builder-vite` and `@storybook/svelte`.

This doesn't fix the underlying problem, but it fixes this specific use case and we need this automigration anyway since SB 7 breaks if you don't remove that `require` call.

### To Reproduce

```shell
1. `npm create svelte@latest sveltekit-storybook65` to create a fresh SvelteKit project
2. `npx sb init` to initialize Storybook `v6.5`
3. `npx sb upgrade --prerelease` to upgrade to `v7.0-alpha` and run automigrations

See the text `failed to check fix: newFrameworks` and that the frameworks will not have migrated.
```

**Comment by shilman** [comment]
Could we just wrap this in a `try/catch` and warn the user somehow?

https://github.com/storybookjs/storybook/blob/next/code/lib/cli/src/automigrate/fixes/new-frameworks.ts#L71-L74

**Comment by shilman** [comment]
We could also replace `get/setFieldValue` with `get/setFieldNode`. The `Node` versions operate on the unevaluated AST, so they shouldn't have this problem.

**Comment by shilman** [comment]
Egads!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-alpha.62 containing PR #20128 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by JReinhold** [comment]
> , but we also use `loadSvelteConfig` from `@sveltejs/vite-plugin-svelte` to read the `svelte.config.js` file. Svelte config is not normally placed into `vite.config.js`, as far as I can tell.
> So, the gist of what you're saying is true. Unless we think that folks need special support for a different svelte config in storybook than they use in their app, we could remove the option and simplify a few things.

Yeah you're right. A quick search on public GH repos with Svelte+Storybook indicates that there are use cases for having different Svelte options, eg. for loading CSS differently, so let's keep it there.
