### ISSUE TITLE
[Bug]: Support for zone.js 0.12.0 for Angular 15

### ISSUE THREAD

**Issue by nzacca** [storybookjs/storybook#20093]
### Describe the bug

When installing storybook with Angular 15 and Zone.js 0.12.0, we're receiving an npm dependency conflict for zone.js.

### Additional context

Problem is `package.json` in the `angular` package is locked down to specific versions of zone.js:

https://github.com/storybookjs/storybook/blob/v7.0.0-alpha.58/code/frameworks/angular/package.json#L108

https://github.com/storybookjs/storybook/blob/v6.5.14/app/angular/package.json#L123

Workaround: use `force` flag with `npm i`.

**Comment by shilman** [comment]
Shiver me timbers!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.0 containing PR #20107 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
