### ISSUE TITLE
[Bug]: --coverage fails the test

### ISSUE THREAD

**Issue by HJZzzzz** [storybookjs/storybook#20119]
### Describe the bug

Describe the bug
Tests are passed by default, but after runing the --coverage command, it throw error:

![image](https://user-images.githubusercontent.com/44113416/206104171-cc4aa22c-ae4f-456e-8e6d-d873eefe0e77.png)

Steps to reproduce the behavior
run yarn test-storybook --coverage

Screenshots and/or logs
Here are the settings in main.js
![image](https://user-images.githubusercontent.com/44113416/206104209-4b2684ca-513e-45ca-97f5-a130fbc8f651.png)

Im using React 17

**Comment by shilman** [comment]
Can you please share more information about your setup?

```
npx sb info
```

**Comment by HJZzzzz** [comment]
it worked for no reason after i  run  yarn again.
so i close this issue
