### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by mnrendra** [storybookjs/storybook#20137]
### Describe the bug

Error when running `npm run storybook` or `yarn storybook`  
where the script in `package.json` is like this:  
```
{
  "scripts": {
    "storybook": "start-storybook -p 6006",
  }
}
```

<img width="1080" alt="Screenshot 2022-12-07 at 11 04 10 PM" src="https://user-images.githubusercontent.com/7542440/206230125-26aca1c0-4213-4762-8f7f-79901f883bcd.png">

It solved by adding `export SET NODE_OPTIONS=--openssl-legacy-provider` in the script:  
```
{
  "scripts": {
    "storybook": "export SET NODE_OPTIONS=--openssl-legacy-provider && start-storybook -p 6006",
  }
}
```  
But doesn't work when running on [Chromatic Github Action](https://storybook.js.org/docs/react/sharing/publish-storybook#setup-ci-to-publish-automatically).  

<img width="1038" alt="Screenshot 2022-12-07 at 11 19 59 PM" src="https://user-images.githubusercontent.com/7542440/206233510-1cd1060f-8a72-4f34-a1a9-4fa8fb6faf35.png">

Note:
- Node version: v18.12.1  
- dependecies version:  
```
{
  "dependencies": {
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@babel/core": "^7.20.5",
    "@storybook/addon-actions": "^6.5.14",
    "@storybook/addon-essentials": "^6.5.14",
    "@storybook/addon-interactions": "^6.5.14",
    "@storybook/addon-links": "^6.5.14",
    "@storybook/builder-vite": "^0.2.5",
    "@storybook/react": "^6.5.14",
    "@storybook/testing-library": "^0.0.13",
    "@types/react": "^18.0.24",
    "@types/react-dom": "^18.0.8",
    "@vitejs/plugin-react": "^2.2.0",
    "autoprefixer": "^10.4.13",
    "babel-loader": "^8.3.0",
    "chromatic": "^6.11.4",
    "eslint": "^8.29.0",
    "eslint-plugin-storybook": "^0.6.8",
    "postcss": "^8.4.19",
    "tailwindcss": "^3.2.4",
    "typescript": "^4.6.4",
    "vite": "^3.2.3"
  }
}
```

### To Reproduce

```shell
repository: https://github.com/mnrendra/particleui
deployed reproduction: https://github.com/mnrendra/particleui/actions/runs/3640086691/jobs/6144298287
```

### System

```shell
Environment Info:

  System:
    OS: macOS 13.0.1
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 3.2.4 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Chrome: 108.0.5359.94
    Safari: 16.1
  npmPackages:
    @storybook/addon-actions: ^6.5.14 => 6.5.14 
    @storybook/addon-essentials: ^6.5.14 => 6.5.14 
    @storybook/addon-interactions: ^6.5.14 => 6.5.14 
    @storybook/addon-links: ^6.5.14 => 6.5.14 
    @storybook/builder-vite: ^0.2.5 => 0.2.5 
    @storybook/react: ^6.5.14 => 6.5.14 
    @storybook/testing-library: ^0.0.13 => 0.0.13
```

**Comment by IanVS** [comment]
Node 18 is not supported with @storybook 6.5 when using builder-vite.  If you'd like to run with node 18 and the vite builder, I suggest upgrading to storybook 7.  You can use `npx sb@next upgrade --prerelease`, and check out https://github.com/storybookjs/storybook/blob/next/MIGRATION.md for the details on what has changed.
