### ISSUE TITLE
[Bug]: When having 2 different component with same name, the inputs are generated from the wrong component

### ISSUE THREAD

**Issue by ronysason** [storybookjs/storybook#20132]
### Describe the bug

I use Storybook for Angular version: 6.5.14
I have 2 different components under 2 different Modules, that share the same component name.
Even though I use inside the "stories" file a specific component (and import them from a different path), the view of the stories is ok, but the inputs that are displayed are the same for both (of the last component that is loading).

### To Reproduce

```shell
1. Create 2 component with the same name under different modules
2. Add different Inputs for each of the component
3. Create 2 different "stories.ts" file for each of them
4. Run storybook and see that both stories contain the same inputs (of the last loaded component)
```

### System

```shell
Environment Info:

  System:
    OS: macOS 12.6.1
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 14.21.1 - ~/.nvm/versions/node/v14.21.1/bin/node
    npm: 6.14.17 - ~/.nvm/versions/node/v14.21.1/bin/npm
  Browsers:
    Chrome: 108.0.5359.94
    Safari: 15.6.1
  npmPackages:
    @storybook/addon-a11y: ^6.5.14 => 6.5.14 
    @storybook/addon-actions: ^6.5.14 => 6.5.14 
    @storybook/addon-docs: ^6.5.14 => 6.5.14 
    @storybook/addon-essentials: ^6.5.14 => 6.5.14 
    @storybook/addon-interactions: ^6.5.14 => 6.5.14 
    @storybook/addon-links: ^6.5.14 => 6.5.14 
    @storybook/angular: ^6.5.14 => 6.5.14 
    @storybook/builder-webpack5: ^6.5.14 => 6.5.14 
    @storybook/manager-webpack5: ^6.5.14 => 6.5.14 
    @storybook/theming: ^6.5.14 => 6.5.14
```

**Comment by IanVS** [comment]
Are you specifying the `component` in the default export of the stories?  Can you share what one of your stories looks like?

**Comment by rolandarau** [comment]
we are also experiencing the same issue. `@storybook/angular` version `7.6.1`. In our library, two components from different subpaths exist with the same class name and selector. Story is as simple as this:

`import { Meta, StoryObj } from '@storybook/angular';
import { DvButtonParams } from './button';
import { DvButtonComponent } from './button.component';
const meta: Meta<DvButtonComponent> = {
  title: 'Legacy/Shared/Button',
  component: DvButtonComponent,
  tags: ['autodocs'],
};

export default meta;
type Story = StoryObj<DvButtonComponent>;

const defaultProps: DvButtonParams = {
  text: 'Button',
  color: 'primary',
  type: 'raised',
};

export const Default: Story = {
  args: {
    ...defaultProps,
  },
};
`
The other component has another is separated with another path in the title's nested structure.

**Comment by vanessayuenn** [comment]
@ronysason @rolandarau do you have a reproduction repo you can share? If not, can you please create one via [storybook.new](https://new-storybook.netlify.app/)? We prioritize bug reports that have reproduction. Thank you! 🙏

**Comment by Nityel** [comment]
[Here](https://stackblitz.com/edit/github-hwx8sn?file=src%2Fstories%2Fcurrent%2Ftest%2Ftest.component.html) is a reproduction that reproduces the issue, though the setup to export the components to a library has not been done.
