### ISSUE TITLE
Frameworks automigration didn't run for vue3/vite project

### ISSUE THREAD

**Issue by tmeasday** [storybookjs/storybook#20148]
I ran `npx storybook@next upgrade --tag next` on https://github.com/inkline/inkline and it ran successfully, running a bunch of migrations.

However `yarn storybook` then failed with:

```
ERR! Error: Invalid value of @storybook/vue3 in the 'framework' field of Storybook config.
```

Due to `main.js` remaining:

```js
  framework: '@storybook/vue3',
  core: {
    builder: '@storybook/builder-vite'
  },
```

**Comment by yannbf** [comment]
Hey @tmeasday I tried this in the project and the automigration is correct. You probably missed the error that the vite version is not compatible.

in #20222 I'm adding a summary which should make this pretty clear, this is what will look like in that project:


![Image](https://user-images.githubusercontent.com/1671563/207673763-494424dc-a8a6-4f7f-ab6a-cc67b129f0b4.png)



And after Vite is upgraded, when running automigrate as indicated in the message:

![Image](https://user-images.githubusercontent.com/1671563/207673793-f744068d-c4b4-48de-9fe6-cd6a58f989cc.png)

If you don't mind, I'll close this issue, but feel free to reopen it if you disagree!

**Comment by tmeasday** [comment]
Great job @yannbf
