### ISSUE TITLE
[Bug]: NextJS 13 'next/head` component not working

### ISSUE THREAD

**Issue by pm0u** [storybookjs/storybook#20189]
### Describe the bug

When using the NextJS 13 (13.0.6) Head component in storybook, it seems nothing happens.

### To Reproduce

```shell
https://github.com/pm0u/storybook-next-head

View the tester component, default story
```

### System

```shell
Environment Info:

  System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Chrome: 108.0.5359.98
    Firefox: 105.0.3
    Safari: 16.1
  npmPackages:
    @storybook/addon-actions: ^6.5.14 => 6.5.14 
    @storybook/addon-essentials: ^6.5.14 => 6.5.14 
    @storybook/addon-interactions: ^6.5.14 => 6.5.14 
    @storybook/addon-links: ^6.5.14 => 6.5.14 
    @storybook/builder-webpack5: ^6.5.14 => 6.5.14 
    @storybook/manager-webpack5: ^6.5.14 => 6.5.14 
    @storybook/react: ^6.5.14 => 6.5.14 
    @storybook/testing-library: ^0.0.13 => 0.0.13
```

### Additional context

As a possible workaround, I tried just using this in preview:

```
import * as Head from 'next/head'

Object.defineProperty(Head, 'default', {
  configurable: true,
  value: ({ children }) => <>{children}</>
})
```

Which just sticks whatever goes into head into the page, which works OK for things like link or script as they are valid outside of the `<head>` element. For things that must be in the head (like `meta` tags) I don't think this will work.

**Comment by shilman** [comment]
Please try upgrading to the latest prerelease and use the `@storybook/nextjs` framework. Full instructions here: 
https://storybook.js.org/blog/integrate-nextjs-and-storybook-automatically/

Does that fix it?

**Comment by pm0u** [comment]
@shilman I just updated that example repo following the steps here: https://github.com/storybookjs/storybook/tree/next/code/frameworks/nextjs#automatic-migration

I just ran the auto migration. I confirmed that the nextjs framework is in the main.js config, but I'm not sure if there's more that needs to be verified. I am getting some console errors when storybook runs.

The updates are on the branch `storybook-next` https://github.com/pm0u/storybook-next-head/tree/storybook-next

I am still not seeing any network request and a querySelector for the ID of the element comes back null

**Comment by valentinpalkovic** [comment]
Hi @pm0u,

I am pretty sure that `next/head` is not supported yet. I will take care of adding support in the following weeks. Due to the holiday season, fully-fledged support might be available at the end of the year or in the first weeks of next year. I will let you know as soon as next/head is supported.

**Comment by pm0u** [comment]
@valentinpalkovic totally understand. Thanks for looking into it! It would be great to have just for reviewing/qa purposes on things like third party scripts and preloaded images.

**Comment by shilman** [comment]
Egads!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.19 containing PR #20436 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
