### ISSUE TITLE
[Bug]: vite4 support - missing dependency upgrade

### ISSUE THREAD

**Issue by marcoreni** [storybookjs/storybook#20190]
### Describe the bug

[Vite 4 is out](https://vitejs.dev/blog/announcing-vite4.html), and 7.0.0-beta2 supports it, but there seems to be a little dependency leftover:

```
 WARN  Issues with peer dependencies found
.
└─┬ @storybook/react-vite 7.0.0-beta.2
  ├─┬ @storybook/builder-vite 7.0.0-beta.2
  │ └─┬ @vitejs/plugin-react 2.2.0
  │   └── ✕ unmet peer vite@^3.0.0: found 4.0.0 in @storybook/builder-vite
  └─┬ @vitejs/plugin-react 2.2.0
    └── ✕ unmet peer vite@^3.0.0: found 4.0.0 in @storybook/react-vite
```

In fact, vitejs/plugin-react should be updated to [3.0.0](https://github.com/vitejs/vite-plugin-react/blob/plugin-react@3.0.0/packages/plugin-react/CHANGELOG.md#300-2022-12-09)

**Comment by IanVS** [comment]
Ah, yes I forgot we include that as a fallback. Until we can get a fix out, you can use overrides or resolutions in your package.json to force the correct version to be used, but we'll get this updated quickly, thanks.

**Comment by shilman** [comment]
Ta-da!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.5 containing PR #20199 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by IanVS** [comment]
The referenced PR only updated ESBuild.  We're handling vite elsewhere.

**Comment by iva2k** [comment]
For a workaround add:

```json
// package.json
{
  ...
  "overrides": {
    "@vitejs/plugin-react": "^3.0.0"
  }
}
```

Works with `npm` and `pnpm`.

**Comment by IanVS** [comment]
@iva2k are you still having problems with the latest beta versions?  It shouldn't require an override.

**Comment by iva2k** [comment]
@IanVS - it was not straightforward to sort it out. After I updated my package.json, I still had the error, and override was fixing it.
After removing pnpm-lock.yaml and node_modules and reinstalling `pnpm i` I finally got rid of the problem.
