### ISSUE TITLE
Encountered two children with the same key, `13-14` ComponentStory

### ISSUE THREAD

**Issue by sandeep-exe** [storybookjs/storybook#20195]
### Describe the bug

I have a simple button component 
![image](https://user-images.githubusercontent.com/81352206/206920413-67f041c8-d895-4358-882a-ef98a7b9835f.png)
as you can see that for some reason line 14 is repeated 4 times (the number of times I've called bind({}) method on template)
So this cause following warning
![image](https://user-images.githubusercontent.com/81352206/206920489-b3213827-05fe-4aea-a212-c3f528a5aa37.png)
Do how can can I fix it? or are there any workarounds?
```
"@storybook/addon-a11y": "^6.5.9",
    "@storybook/addon-actions": "^6.3.7",
    "@storybook/addon-docs": "^6.5.0-rc.1",
    "@storybook/addon-essentials": "^6.3.7",
    "@storybook/addon-links": "^6.3.7",
    "@storybook/addon-storysource": "^6.5.9",
    "@storybook/addons": "^6.3.7",
    "@storybook/react": "^6.3.7",
    "@storybook/testing-react": "^1.2.4",
    "@storybook/theming": "^6.3.7",
    "storybook-addon-jarle-monaco": "^0.4.1",
```

**Comment by eBitzu** [comment]
hi @sandeep-exe can you create a sandbox for this use-case? I'll have a look after
