### ISSUE TITLE
[Bug]: `enableShortcuts: false` doesn't work with beta.3

### ISSUE THREAD

**Issue by jpzwarte** [storybookjs/storybook#20202]
### Describe the bug

`manager.js`:
```js
import { addons } from '@storybook/manager-api';

 addons.setConfig({
   enableShortcuts: false
 });
```

If you then start storybook, shortcuts are still enabled.

### To Reproduce

```shell
https://kind-plant-088739303-111.westeurope.1.azurestaticapps.net/?path=/story/editor_editor--api
```

**Comment by shilman** [comment]
w00t!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.9 containing PR #20264 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
