### ISSUE TITLE
Runtime check for react/react-dom peer dependencies & clear error message

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#20203]
I talked to @jpzwarte and he does not have react/react-dom installed in his project.

I think this is going to be confusing to many people.  We may want to consider adding a runtime check to confirm that react + react-dom are installed, and explain to the user why they are needed, and how they can remove docs if they do not want that feature.

_Originally posted by @IanVS in https://github.com/storybookjs/storybook/issues/20160#issuecomment-1342744883_

**Comment by ndelangen** [comment]
@valentinpalkovic Looks like this got also assigned to you?

Your PR: https://github.com/storybookjs/storybook/pull/20206 seems to fix this?

**Comment by valentinpalkovic** [comment]
@ndelangen Exactly. The PR should fix this issue.

**Comment by shilman** [comment]
Yippee!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.5 containing PR #20206 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
