### ISSUE TITLE
Add automigration MDX1 HTML comments to MDX2 JSX comments

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#20200]
See #18554

**Comment by ndelangen** [comment]
@shilman replacing HTML-comment with JS comments in all MDX files, should do the trick right?

We likely will have to do this with a RegExp, considering the MDX compiler actually is not able to parse the file..

**Comment by shilman** [comment]
Yup!!

**Comment by slorber** [comment]
Docusaurus maintainer 👋  also trying to upgrade to MDX 2 https://github.com/facebook/docusaurus/pull/8288

Worth taking into consideration that comments might be nested inside HTML code blocks 🤪 

````md

<!-- md comment -->

```html
<div>
  <!-- HTML comment (do not transform) -->
</div>
```

````

**Comment by ndelangen** [comment]
<img src="https://media3.giphy.com/media/Ofo2Z3DnjvAHa4WJOf/giphy.gif"/>

**Comment by shilman** [comment]
Crikey!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.26 containing PR #20349 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
