### ISSUE TITLE
[Bug]: Support for nrwl/workspace 15.3+ for Angular 15

### ISSUE THREAD

**Issue by nzacca** [storybookjs/storybook#20213]
### Describe the bug

When installing Storybook within an Nx 15+ workspace, we receive a peer dependency conflict for the `@nrwl/workspace` package which requires v14.6.1:

https://github.com/storybookjs/storybook/blob/v7.0.0-beta.3/code/frameworks/angular/package.json#L103

### Additional context

Note, here is where the `@nrwl/workspace` package is referenced within Storybook:

https://github.com/storybookjs/storybook/blob/fd2ce3f18f26372cc082bfded019921d793e282a/code/frameworks/angular/src/server/angular-read-workspace.ts#L23

https://github.com/storybookjs/storybook/blob/fd2ce3f18f26372cc082bfded019921d793e282a/code/frameworks/angular/src/server/angular-read-workspace.ts#L25

Also note that `readNxJson` on line 23 is not exported from `@nrwl/workspace` so this line will always throw. It is found within `@nrwl/devkit`:

https://github.com/nrwl/nx/blob/15.3.3/packages/devkit/index.ts#L63

**Comment by shilman** [comment]
Ta-da!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.30 containing PR #20559 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
