### ISSUE TITLE
[Bug]: CSF-2-3 automigration scripts ignores Typescript types

### ISSUE THREAD

**Issue by valentinpalkovic** [storybookjs/storybook#20219]
### Describe the bug

The csf-2-3 automigration script does not transform `StoryFn` types to `StoryObj`.

Requirements:

1. `StoryFn` type assignments should be replaced by `StoryObj`.
2. The import has to be adjusted to import `StoryFn` instead of `StoryObj`

### To Reproduce

1. Create a Story, which imports `StoryFn` from "@storybook/<framework>" and use it for a Story.

```ts
export const Default: StoryFn = () => {...}
```

2. Run the auto migration script

```shell
npx sb@next migrate csf-2-to-3 --glob="**/*.stories.ts" 
```

3. The `StoryFn` type is not transformed to `StoryObj`

**Comment by valentinpalkovic** [comment]
👆 fyi: @kasperpeulen

**Comment by kasperpeulen** [comment]
Strange, I have used this script to transform all the CLI templates from CSF2 to CSF3 🤔

**Comment by kasperpeulen** [comment]
Also tagging mr. @shilman

**Comment by kasperpeulen** [comment]
@valentinpalkovic I have the same issue. Not sure if this is a regression then.

**Comment by shilman** [comment]
Great Caesar's ghost!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.29 containing PR #20273 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
