### ISSUE TITLE
[Feature Request]: Make search box more accessible

### ISSUE THREAD

**Issue by adamsamec** [storybookjs/storybook#20224]
### Is your feature request related to a problem? Please describe

Would it be possible to replace the storybook's search button directly with the search edit field? This has accessibility implications becaus screen reader users are used to look for an input field type of element when they look for the search box on page. Screen readers have the functionality which allows their users to quickly navigate by a certain element type, thus users navigate by edit fields to find the search field.
 But in storybook this is not possible because the edit field appears only after activating the serch button.

### Describe the solution you'd like

A search edit field placed directly on the page, replacing the search button.

### Are you able to assist to bring the feature to reality?

no

**Comment by valentinpalkovic** [comment]
@MichaelArestad, @domyen Any thoughts about this?

**Comment by domyen** [comment]
Hasn't come up before. I think we already match the web standard of having an `input` with attr `type="search"`?

**Comment by valentinpalkovic** [comment]
> A search edit field placed directly on the page, replacing the search button.

To which search button are you referring? Are you talking about the storybook website? Or are you talking about the Storybook Manager, like this one https://pigment.customink.com/. My guess is, that you are talking about the Storybook website, which has indeed a button in place which opens a search in a modal. The Storybook Manager though doesn't have a kind of search button.

**Comment by winkerVSbecks** [comment]
Ah okay, sorry for the confusion. That is in fact part of the Storybook app itself. So your original issue was correct. I'll reply there with a comment.

**Comment by adamsamec** [comment]
The issue appears also in the not modified version of Storybook. The problem is in the editable combobox search field  implementation. There is a div element wrapping the input element, the div element should not have the role="combobox" attribute and other aria attributes. Instead, these attributes should be placed directly on the input element. If you want a working example, please check this [ Combobox With List Autocomplete Example](https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-autocomplete-list/) from W3C.
