### ISSUE TITLE
[Bug]: ERR_MODULE_NOT_FOUND cannot find lodash/isPlainObject in 7.0.0-beta.4

### ISSUE THREAD

**Issue by AndrewLeedham** [storybookjs/storybook#20225]
### Describe the bug

When using the MJS bundles in the Storybook `7.0.0-beta.4`, I get the following error:
```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '<redacted>/node_modules/lodash/isPlainObject' imported from <redacted>/node_modules/@storybook/preview-api/dist/chunk-QMJ3NG6X.mjs
```

I have tried with `pnpm`, `npm` and `yarn` and they all have the same issue. I believe this is because `lodash` does not provide an exports field and therefore would need to be referenced with `lodash/isPlainObject.js` (note the addition of `.js`) to work with ESM.

The dist file in question is here: https://unpkg.com/browse/@storybook/preview-api@7.0.0-beta.4/dist/chunk-QMJ3NG6X.mjs you can see it erroneously imports `lodash/isPlainObject`.

### To Reproduce

This is quite simple to test, you just need a repo with `Storybook@7.0.0-beta.4` and a single `mjs` file like so:

```javascript
import { storiesOf } from "@storybook/server";

storiesOf();
```

### System

```shell
Environment Info:

  System:
    OS: macOS 12.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 16.18.0 - ~/.nvm/versions/node/v16.18.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.0/bin/npm
  npmPackages:
    @storybook/addon-actions: 7.0.0-beta.4 => 7.0.0-beta.4 
    @storybook/addon-essentials: 7.0.0-beta.4 => 7.0.0-beta.4 
    @storybook/addon-interactions: 7.0.0-beta.4 => 7.0.0-beta.4 
    @storybook/addon-links: 7.0.0-beta.4 => 7.0.0-beta.4 
    @storybook/builder-vite: 7.0.0-beta.4 => 7.0.0-beta.4 
    @storybook/server: 7.0.0-beta.4 => 7.0.0-beta.4 
    @storybook/testing-library: 0.0.13 => 0.0.13
```

**Comment by menasheh** [comment]
running into this same issue

**Comment by shilman** [comment]
Shiver me timbers!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.19 containing PR #20443 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by menasheh** [comment]
confirmed works
