### ISSUE TITLE
[Bug]: sb babelrc produces empty config

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#20220]
### Describe the bug

Users of SB6 migrating to SB7 who don't have a babelrc should be able to run:

```
npx sb babelrc
```

This should create a `.babelrc.json` that provides a legacy v6 babel configuration. Instead it prodcues:

```json
{
  "sourceType": "unambiguous",
  "presets": [],
  "plugins": []
}
```

**Comment by ndelangen** [comment]
Code is generated here:

https://github.com/storybookjs/storybook/blob/5a557d37ce573e15290cd7ed43ba434e3b42e6b5/code/lib/cli/src/babel-config.ts#L13-L21

**Comment by ndelangen** [comment]
I can't generate it with comments because of the `.json` extension. And even if that could support comments, I'd need to switch to some other form of code-generation; because `JSON.stringify` can't do it.

**Comment by shilman** [comment]
Yo-ho-ho!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.9 containing PR #20234 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
