### ISSUE TITLE
[Bug]: Not able to overwrite default argTypes options (seems to just merge them)

### ISSUE THREAD

**Issue by basickarl** [storybookjs/storybook#20245]
### Describe the bug

I have the current code:
```
export default {
  title: 'UIComponents/Alert',
  component: Alert,
  subcomponents: {
    AlertAction,
  },
  parameters: {
    controls: {
      sort: 'alpha',
      expanded: true,
    },
  },
  argTypes: {
    test: {
      control: {
        type: 'select',
        options: {
          derp: 'derp', // <- this does not disappear when I try and overwrite the options further down in the code
        },
      },
    },
  },
};

// ...more code

export const DefaultAlert: Story<AlertProps> = Template.bind({});
DefaultAlert.argTypes = {
  test: {  // Here I am attempting to overwrite the entire object property 
    control: {
      type: 'select',
      options: {
        hiya: 'hiya', // <- here I am trying to get rid of the default "derp" and just have the "hiya" option
      },
    },
  },
};
```

So from the comment in the code from above, the `hiya` seems to just be added onto the option and does not replace it. If I wanted to add it I would done a simple spread of the default object property onto here.

This is the result:
<img width="291" alt="image" src="https://user-images.githubusercontent.com/10507098/207489617-76f48f75-5ebc-4226-8ec4-891fa2cb47c9.png">

I am expecting only `hiya` in that list.

I can't read anywhere in the documentation how to do this?

```
    "@storybook/addon-a11y": "^6.4.19",
    "@storybook/addon-actions": "^6.3.12",
    "@storybook/addon-essentials": "^6.3.12",
    "@storybook/addon-links": "^6.3.12",
    "@storybook/addon-storysource": "^6.4.19",
    "@storybook/react": "6.4.20",
```

### To Reproduce

```shell
.
```

### System

```shell
Environment Info:

  System:
    OS: macOS 12.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Binaries:
    Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.18.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
```

### Additional context

.

**Comment by shilman** [comment]
If you update to 6.5 and use the options array documented here you can override at the story level.

https://storybook.js.org/docs/react/essentials/controls#choosing-the-control-type

In general SB args/argTypes/parameters have deep-merge semantics for objects and replacement semantics for arrays

To upgrade:
```
npx sb upgrade
```

And check the migration notes at https://github.com/storybookjs/storybook/blob/next/MIGRATION.md
