### ISSUE TITLE
Update default `main.js:stories` to match `.mdx`

### ISSUE THREAD

**Issue by tmeasday** [storybookjs/storybook#20249]
If a user has:

```js
  stories: ['../src/**/*.stories.mdx', '../src/**/*.stories.@(js|jsx|ts|tsx)'],
```

(or equivalent), *and* they no longer have any `.stories.mdx` files (due to other migrations), update it to

```js
  stories: ['../src/**/*.mdx', '../src/**/*.stories.@(js|jsx|ts|tsx)'],
```

If they do have stories that still match, print a helpful message that tells them what other migrations / documentation is available to help migrate them.

We may want to consider matching both as a fallback, in order to help with https://github.com/storybookjs/storybook/issues/20733

Note that in https://github.com/storybookjs/storybook/pull/19795 we changed the default glob if you supply a directory name to match both.

**Comment by shilman** [comment]
I think we should let users do this by hand or make it part of their "Docs2" migration process (whether manual or semi-automated)

**Comment by tmeasday** [comment]
Ok will leave this ticket in "required for RC" for now.

**Comment by JReinhold** [comment]
Detecting and changing `'../src/**/*.stories.mdx'` is pretty doable, but there are more advanced globs that would match `*.stories.mdx` which I think are non-trivial to migrate. Like `['../src/**/*.stories.@(js|jsx|ts|tsx|mdx)']` could be converted to `['../src/**/*.mdx', '../src/**/*.stories.@(js|jsx|ts|tsx)']`, but the detecting and change would even be different depending on where in the list the `mdx` appears (start, middle or end).

Would be be okay with only supporting the simple case, or do we want to attempt to support more advanced globs?

**Comment by tmeasday** [comment]
I think at the least we should support the globs *we* wrote to `main.js` ourselves in earlier versions.

**Comment by JReinhold** [comment]
Notes to self about historical globs:

Current globs: https://github.com/storybookjs/storybook/blob/next/code/lib/cli/src/generators/configure.ts#L42
```
[`${prefix}/**/*.mdx\`, \`${prefix}/**/*.stories.@(${extensions.join('|')})`]
```
---
https://github.com/storybookjs/storybook/blame/59ac6d804bd800538c2c633b2c69b57bf4baa5c4/code/lib/cli/src/generators/configure.ts#LL31C7-L31C7
```
    stories: [`${prefix}/**/*.stories.mdx`, `${prefix}/**/*.stories.@(${extensions.join('|')})`],
```

https://github.com/storybookjs/storybook/blame/8ab8425ec556f7350bcc211154ed26efd62a7508/lib/cli/src/generators/configure.ts#L7-L10
```
  const config = {
    stories: [!hasSrc && '../stories/**/*.stories.*', hasSrc && '../src/**/*.stories.*'].filter(
      Boolean
    ),
```

This last one is from June 2020 and I'm struggling to trace it further back than that. I think that's fine.

**Comment by JReinhold** [comment]
> ... _and_ they no longer have any `.stories.mdx` files (due to other migrations), update it to
> 
> ```js
>   stories: ['../src/**/*.mdx', '../src/**/*.stories.@(js|jsx|ts|tsx)'],
> ```

@tmeasday I don't think what you're specifying here makes sense. Changing the glob from `*.stories.mdx` to `*.mdx` would still match any `*.stories.mdx` files, so I think it's safe to run this migration even if they still have `.stories.mdx` files. This migration would only cause it to match _more_ files, it wouldn't exclude any.

**Comment by tmeasday** [comment]
Oh, right 🤦 

So does that mean this task is pretty simple then @JReinhold?

**Comment by shilman** [comment]
Shiver me timbers!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.47 containing PR #21035 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```
