### ISSUE TITLE
Doc Blocks need to be "unstyled"

### ISSUE THREAD

**Issue by tmeasday** [storybookjs/storybook#20251]
Default MDX styles leak through to doc blocks components.

![Image](https://user-images.githubusercontent.com/132554/207504055-7a5ccee6-0bd2-4518-ae2b-c718a0caa5b2.png)

Also the `Unstyled` component isn't exported (I was going to check to see if it fixed the problem).

**Comment by robin-thomas** [comment]
@tmeasday I have the same issue with my storybook, and I checked with the `Unstyled` component from `7.0.0-beta.25`. Didn't fix this issue.

@JReinhold Any update on this?

**Comment by JReinhold** [comment]
@robin-thomas can you explain what you tried with `Unstyled`, and what didn't work? Did anything in the migration notes help? https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#default-docs-styles-will-leak-into-non-story-user-components

**Comment by robin-thomas** [comment]
@JReinhold My issue was with the argsTable on the docs page, as the styles were leaking to it (just like mentioned in this issue description).

I can see you have already made a PR that should fix the issue. Thanks!

**Comment by shilman** [comment]
Ta-da!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.33 containing PR #20757 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```
