### ISSUE TITLE
"unexpected storiesOf call" logged in v6 mode

### ISSUE THREAD

**Issue by tmeasday** [storybookjs/storybook#20254]
Due to the `csf-plugin`

**Comment by shilman** [comment]
Great Caesar's ghost!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.7 containing PR #20256 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
