### ISSUE TITLE
`Uncaught Error: Accessing non-existent serverChannel` in v6 mode

### ISSUE THREAD

**Issue by tmeasday** [storybookjs/storybook#20252]
Seems to come from this line: https://github.com/storybookjs/storybook/blob/120aa234138aabf7ccc6db8ebebb9e4a546274b6/code/ui/manager/src/components/preview/preview.tsx#L74

When `storyStoreV7: false`. See this repo: https://github.com/tmeasday/inkline/tree/ssv6

**Comment by tmeasday** [comment]
It also logs:

```
CSF: unexpected storiesOf call (line 11, col 0)

More info: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#story-store-v7
```

In the terminal, so it could have something to do with that.

**Comment by tmeasday** [comment]
@shilman asked to keep issues open until they've been released in a beta, as usual, so I undid my closing :)

**Comment by shilman** [comment]
Yippee!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.7 containing PR #20253 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
