### ISSUE TITLE
Vite does not show a spinner while loading first story

### ISSUE THREAD

**Issue by tmeasday** [storybookjs/storybook#20250]

**Comment by tmeasday** [comment]
So the issue appears to be that it takes a long time to fetch the project annotations, for whatever reason. We should probably just set the view to `showPreparingStory` before the annotations have even loaded? -- the problem here is that we don't know if the first entry is a story or a doc until we load the index, which happens *after* the annotations.

Perhaps we should reverse that and load the index first?


![Image](https://user-images.githubusercontent.com/132554/207580950-f74a3ef3-dd8f-4442-b106-906a0dfdf5a5.png)

**Comment by tmeasday** [comment]
- Load index in parallel to preview.js
- Show the preview compiling bar while waiting on index.

**Comment by shilman** [comment]
Boo-yah!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.30 containing PR #20425 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
