### ISSUE TITLE
[Bug]: mdx-js/react version in the latest @6.5.14 is old

### ISSUE THREAD

**Issue by t29gupta** [storybookjs/storybook#20260]
### Describe the bug

Current version of @storybook/addon-docs@6.5.14 is using "@mdx-js/react@1.6.22"; which has a peer dependancy on React 17 max. This is preventing the library to be used in React 18 project.
@mdx-js/react already has a later version supporting react 18. Please upgrade the library in the package.

<img width="461" alt="Screenshot 2022-12-14 at 12 28 50" src="https://user-images.githubusercontent.com/10693435/207583926-f02cda25-e6ce-4e9e-a72e-2af815c7f2e7.png">

### To Reproduce

```shell
Installing addon-docs in React-18 project. Getting dependancy error.
```

**Comment by shilman** [comment]
This is fixed in the latest prerelease & we can't apply the fix back to 6.5 due to semver. Please try upgrading:

```
npx storybook@next upgrade --prerelease
```

Preliminary 7.0 migration guide here https://www.notion.so/chromatic-ui/Storybook-7-migration-guide-dbf41fa347304eb2a5e9c69b34503937
