### ISSUE TITLE
[Feature Request]: Change sidebar icon when canvas hidden

### ISSUE THREAD

**Issue by loic-enedis** [storybookjs/storybook#20274]
### Is your feature request related to a problem? Please describe

I want my documentation only stories to have the document icon in the sidebar when I create a story without canvas : 

```
myStory.parameters = {
  previewTabs: {
    canvas: {
      hidden: true,
    },
  },
  viewMode: 'docs',
};
```

### Describe the solution you'd like

When the canvas tab is disabled, the icon should change

### Describe alternatives you've considered

Using css to hide the story icon and show the document one. 

### Are you able to assist to bring the feature to reality?

no

**Comment by shilman** [comment]
there is no tab structure in 7.0, so i'm not sure whether this feature request makes sense for the future of SB

**Comment by loic-enedis** [comment]
In fact, I did not look for the 7.0 preview. Your project is great, you are great, thanks

**Comment by shilman** [comment]
@loic-enedis thanks so much. we're doing our best to try to make storybook better with each release!
