### ISSUE TITLE
If a user has a broken addon (with a manager entry), it breaks subsequent imports from the manager builder

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#20285]
One broken import impacts the others:

![Image](https://user-images.githubusercontent.com/1671563/207835617-6b164bee-244d-4847-bb7e-f9d80d39ad38.png)

**Comment by shilman** [comment]
Hurrah!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.9 containing PR #20286 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
