### ISSUE TITLE
[Bug]: Show Code in Sample Components is not showing the component code (7.0.0-beta13 nextjs)

### ISSUE THREAD

**Issue by tylerexpa** [storybookjs/storybook#20356]
### Describe the bug

This bug is for 7.0.0-beta13 with nextjs and was confirmed by shilman (see below).

1. Run npx storybook@next init into a nextjs (13) project.  
2. Start the dev server with npm run storybook
3. Navigate to sample component docs
4. All of the "show code" views in the sample components don't seem to be showing the component code.  I did a bunch of searching but can't find anyone else that has run into this.   Every sample component (EG: the default Button) shows the attached code when you click on "Show code".

<img width="234" alt="Screenshot 2022-12-20 at 3 07 16 PM" src="https://user-images.githubusercontent.com/98788395/208790316-6d9557b5-1bd2-4604-a30d-09e70772671b.png">

Feedback from shilman
Ok i'm able to reproduce the issue. Can you please file a github issue about this?  Looks like a bug in @storybook/nextjs

I think there are a couple problems:
1. it doesn't show the component name
2. it doesn't show the props passed to the component
5. the PageRouterProvider is getting automatically injected by the nextjs frameowork, but i believe shouldn't show up in the source snippet because it's an implementation detail

### To Reproduce

```shell
This command seems to be hanging for me but the bug is reproducible by installing the latest storybook@next beta and initiating a new instance in a nextjs 13 project (confirmed by other parties including shilman)
```

### System

```shell
System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 18.10.0 - /opt/homebrew/bin/node
    npm: 8.19.2 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Safari: 16.2
```

**Comment by madelahsan** [comment]
Still facing the same issue in beta43.

**Comment by valentinpalkovic** [comment]
Hey @madelahsan,

Fyi: I aim to work on this issue in the next couple of weeks.

**Comment by tmeasday** [comment]
@valentinpalkovic can you revert 29cf97e85d2e0f5acc083ad78d10827b6ad614ce as part of this PR? I had to disable a test that inspects the snippet in NextJs.

**Comment by valentinpalkovic** [comment]
@tmeasday I don't have to anymore. It seems already been reverted.

**Comment by tmeasday** [comment]
@valentinpalkovic I guess that PR hasn't been merged yet https://github.com/storybookjs/storybook/pull/20915 -- had some last minute issues that we are waiting on @shilman for.

Let's just try and coordinate to get the test re-enabled when both your and my PRs are merged :)

**Comment by elliotgonzalez-lk** [comment]
Just reporting in, as I'm seeing something slightly different.  Started a fresh NextJs app, ran `npx sb@next init` and after launching `yarn storybook`, the "show code" section is giving me: 

 `<HeadManagerProvider>
  <No Display Name />
</HeadManagerProvider>`

Running Storybook 7.0.0-beta.47 for nextjs v13.1.6

**Comment by shilman** [comment]
Boo-yah!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.48 containing PR #21029 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```

**Comment by madelahsan** [comment]
> Boo-yah!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.48 containing PR #21029 that references this issue. Upgrade today to the `@next` NPM tag to try it out!
> 
> ```
> npx sb@next upgrade --prerelease
> ```

just updated to beta-48. It's fixed now thank you guys.
