### ISSUE TITLE
[Bug]: @joshwooding/vite-plugin-react-docgen-typescript 404 Not Found

### ISSUE THREAD

**Issue by furkanalptokac** [storybookjs/storybook#20381]
### Describe the bug

I can't install latest version of @storybook/react-vite. Error:

An unexpected error occurred: "https://ournexusrepository/repository/npm-group/@joshwooding/vite-plugin-react-docgen-typescript/-/vite-plugin-react-docgen-typescript-0.0.0-20221218231544.tgz: Request failed \"404 Not Found\"".

I checked the @storybook/react-vite package.json history and @ndelangen changed this package's version in this commit 37fd1f0ec56b642094f1884ddbb3d2db6c8ee4c4 but latest commit b909242c8b5122d8406c919ce9bdc0d99aeefe43 package's version upgraded 0.2.1. In that case, there should be no problem here.

Note: It occurs from @storybook/react-vite@7.0.0-beta.13

**Comment by ndelangen** [comment]
Hello @furkanalptokac that's odd, because that package/version should still be on pnm..

Can you upgrade to the latest beta? it upgrades that packages..

**Comment by furkanalptokac** [comment]
Hello @ndelangen . I'm already trying with `yarn add -D @storybook/react-vite@next` and `yarn info @storybook/react-vite@next` gives me `
'dist-tags': {
    next: '7.0.0-beta.13',
    future: '7.0.0-alpha.34',
    latest: '7.0.0-alpha.25'
  },
`
react-vite is already on 7.0.0-beta.13 version on Storybook repo, interesting.

**Comment by furkanalptokac** [comment]
And also I'm trying to get package on a new empty project to be sure. @ndelangen

**Comment by ndelangen** [comment]
@furkanalptokac Can you add a resolution to have it take the latest version of `@joshwooding/vite-plugin-react-docgen-typescript`, Does that work for you?

**Comment by furkanalptokac** [comment]
Fixed with @storybook/react-vite@7.0.0-beta.15
