### ISSUE TITLE
[Bug]: ./storybook-config-entry.js undefined

### ISSUE THREAD

**Issue by m4r-k0v** [storybookjs/storybook#20391]
### Describe the bug

After upgrading from 6.x.x -> 7.0.0-beta.13

I am facing following issue:
```
ModuleBuildError: Module build failed (from ./node_modules/babel-loader/lib/index.js):
BrowserslistError: [BABEL] /Users/mk/Projects/storybook/storybook-config-entry.js: Unknown browser query `default`. Maybe you are using old Browserslist or made typo in query. (While processing: "/Users/mk/Projects/storybook/node_modules/@babel/preset-env/lib/index.js")
```

`main.js Configuration`
`const path = require('path');
const TsconfigPathsPlugin = require('tsconfig-paths-webpack-plugin');
module.exports = {
  framework: {
    name: '@storybook/react-webpack5',
    options: {}
  },
  stories: ['../src/**/*.stories.mdx', '../src/**/*.stories.@(js|jsx|ts|tsx)'],
  addons: ['@storybook/addon-links', '@storybook/addon-essentials'],
  webpackFinal: async config => {
    config.resolve.plugins = [new TsconfigPathsPlugin()];
    config.module.rules.push({
      test: /\,css&/,
      use: [{
        loader: 'postcss-loader',
        options: {
          ident: 'postcss',
          plugins: [require('tailwindcss'), require('autoprefixer')]
        }
      }],
      include: path.resolve(__dirname, '../')
    });
    return config;
  },
  docs: {
    docsPage: 'automatic'
  }
};`

We are using rollup to build components

### System

```shell
System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1 Pro
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Safari: 16.0
  npmPackages:
    @storybook/addon-actions: ^7.0.0-beta.13 => 7.0.0-beta.13 
    @storybook/addon-docs: ^7.0.0-beta.13 => 7.0.0-beta.13 
    @storybook/addon-essentials: ^7.0.0-beta.13 => 7.0.0-beta.13 
    @storybook/addon-links: ^7.0.0-beta.13 => 7.0.0-beta.13 
    @storybook/addons: ^7.0.0-beta.13 => 7.0.0-beta.13 
    @storybook/react: ^7.0.0-beta.13 => 7.0.0-beta.13 
    @storybook/react-webpack5: ^7.0.0-beta.13 => 7.0.0-beta.13 
    @storybook/theming: ^7.0.0-beta.13 => 7.0.0-beta.13
```

**Comment by Mahmoudqandil** [comment]
M.Q

**Comment by shilman** [comment]
Do you a have a reproduction repo you can share? If not, can you create one? See [how to create a repro](https://storybook.js.org/docs/react/contribute/how-to-reproduce). Thank you! 🙏
