### ISSUE TITLE
[Bug]: Babel peer dependency issue with @storybook/codemod in v7 beta 14 and yarn pnp

### ISSUE THREAD

**Issue by bryanjtc** [storybookjs/storybook#20398]
### Describe the bug

The following warning shows up when running yarn install on a project with storybook v7 on beta 14
![image](https://user-images.githubusercontent.com/49354825/209351112-8b36b94a-e237-4b24-a90e-336cdbe93244.png)

### To Reproduce

```shell
https://github.com/bryanjtc/storybook-7-vite-test
```

### System

```shell
Environment Info:

  System:
    OS: Windows 10 10.0.22000
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.2.4 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (108.0.1462.54)
```

**Comment by shilman** [comment]
Ermahgerd!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.15 containing PR #20399 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```
