### ISSUE TITLE
[Bug]: SvelteKit "Cannot find module '[...].svelte' or its corresponding type declarations." when importing `*.svelte` into `*.stories.ts`

### ISSUE THREAD

**Issue by FelixTJDietrich** [storybookjs/storybook#20394]
### Describe the bug

After a clean setup of a SvelteKit app and initialising Storybook 7, I have problems importing `*.svelte` component types into my `*.stories.ts`: `Cannot find module './Button.svelte' or its corresponding type declarations.ts(2307)`
<img width="701" alt="image" src="https://user-images.githubusercontent.com/5898705/209341609-a0fc9be5-a84d-4637-8d5d-d584e6b44941.png">

There are no issues with rendering the components with the Storybook app. I have been trying to find a solution for this for the past days but can't resolve it.

### To Reproduce
`npx sb@next repro` did not work for me but here are my steps to reproduce:
```shell
npm create svelte@latest my-app
> Skeleton project
> Yes, using TypeScript syntax
> No
> No
> No
> No
cd my-app
npx storybook@next init
```

### System

```shell
Environment Info:

  System:
    OS: macOS 13.0.1
    CPU: (8) arm64 Apple M1 Pro
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.15.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 107.0.5304.110
    Safari: 16.1
  npmPackages:
    @storybook/addon-essentials: ^7.0.0-beta.14 => 7.0.0-beta.14 
    @storybook/addon-interactions: ^7.0.0-beta.14 => 7.0.0-beta.14 
    @storybook/addon-links: ^7.0.0-beta.14 => 7.0.0-beta.14 
    @storybook/blocks: ^7.0.0-beta.14 => 7.0.0-beta.14 
    @storybook/svelte: ^7.0.0-beta.14 => 7.0.0-beta.14 
    @storybook/sveltekit: ^7.0.0-beta.14 => 7.0.0-beta.14 
    @storybook/testing-library: ^0.0.13 => 0.0.13
```

### Additional context

I'm using VSCode with the `Svelte for VS Code` extension.

**Comment by shilman** [comment]
@kasperpeulen @JReinhold  any suggestions here?

**Comment by JReinhold** [comment]
I wonder if this is at all related to https://github.com/sveltejs/language-tools/issues/1556 .

I'll investigate this more when I get the time, just leaving this as a mental note.

**Comment by nazrullayevkamoliddin** [comment]
What happened next? How did you fix this error? I made the same mistake!

**Comment by JReinhold** [comment]
I think I dropped this @nazrullayevkamoliddin - can you provide a reproduction @nazrullayevkamoliddin or @FelixTJDietrich? I'm having trouble reproducing this on my machine.
