### ISSUE TITLE
[Bug]: Command 'start-storybook' stop working after upgrade to 7.0.0-beta.14

### ISSUE THREAD

**Issue by reidark** [storybookjs/storybook#20400]
### Describe the bug

After upgrading to 7.0.0-beta.14 with the `npx sb upgrade --prerelease` ([#20093](https://github.com/storybookjs/storybook/issues/20093#issuecomment-1342240091)), the command 'start-storybook' doesn't work anymore.

I have upgraded to this version because the incompatibility of the range of Zone.js and Angular.

Error message:
![image](https://user-images.githubusercontent.com/3278567/209408973-286b83c8-577f-4153-81aa-04c9c355da9d.png)

_Translation:_ 'start-storybook' is not recognized as a internal or external command.

### System

```shell
Environment Info:

  System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.19.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 108.0.5359.125
    Edge: Spartan (44.19041.1266.0), Chromium (108.0.1462.54)
  npmPackages:
    @storybook/addon-actions: ^7.0.0-beta.14 => 7.0.0-beta.14
    @storybook/addon-essentials: ^7.0.0-beta.14 => 7.0.0-beta.14
    @storybook/addon-interactions: ^7.0.0-beta.14 => 7.0.0-beta.14
    @storybook/addon-links: ^7.0.0-beta.14 => 7.0.0-beta.14
    @storybook/angular: ^7.0.0-beta.14 => 7.0.0-beta.14
    @storybook/builder-webpack5: ^7.0.0-beta.14 => 7.0.0-beta.14
    @storybook/manager-webpack5: ^7.0.0-alpha.10 => 7.0.0-alpha.10
    @storybook/testing-library: ^0.0.14-next.1 => 0.0.14-next.1
```

**Comment by joshwooding** [comment]
Hi, start-storybook was removed in 7. You can read the migration docs here: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#start-storybook--build-storybook-binaries-removed
