### ISSUE TITLE
[Bug]: [v7] storybook crashes with ERR_UNSUPPORTED_ESM_URL_SCHEME with vite builder and yarn pnp on windows

### ISSUE THREAD

**Issue by blikblum** [storybookjs/storybook#20404]
### Describe the bug

In a clean install of storybook in a project configured to use yarn v3 / pnp, running the script "storybook" on windows leads to the following error:

```
ERR! Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'd:'
ERR!     at __node_internal_captureLargerStackTrace (node:internal/errors:478:5)
ERR!     at new NodeError (node:internal/errors:387:5)
ERR!     at throwIfUnsupportedURLScheme (node:internal/modules/esm/resolve:1017:11)
ERR!     at defaultResolve (node:internal/modules/esm/resolve:1097:3)
ERR!     at nextResolve (node:internal/modules/esm/loader:163:28)
ERR!     at resolve$1 (file:///D:/repositories/storybook-yarn/.pnp.loader.mjs:1966:14)
ERR!     at nextResolve (node:internal/modules/esm/loader:163:28)
ERR!     at ESMLoader.resolve (node:internal/modules/esm/loader:837:30)
ERR!     at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
ERR!     at ESMLoader.import (node:internal/modules/esm/loader:521:22)
ERR!     at importModuleDynamically (node:internal/modules/cjs/loader:1094:29)
ERR!     at importModuleDynamicallyWrapper (node:internal/vm/module:438:21)
ERR!     at importModuleDynamically (node:vm:389:46)
ERR!     at importModuleDynamicallyCallback (node:internal/process/esm_loader:35:14)
ERR!     at getPreviewBuilder (D:\repositories\storybook-yarn\.yarn\cache\@storybook-core-server-npm-7.0.0-beta.15-b304f2875e-321ca5d8ec.zip\node_modules\@storybook\core-server\dist\index.js:10:1913)
ERR!     at buildDevStandalone (D:\repositories\storybook-yarn\.yarn\cache\@storybook-core-server-npm-7.0.0-beta.15-b304f2875e-321ca5d8ec.zip\node_modules\@storybook\core-server\dist\index.js:33:2139)
ERR!     at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Basically the error is because is missing file:/// prefix in module specifier

### To Reproduce

```shell
I created a repository with a newly configured yarn pnp and clean install of storybook:

https://github.com/blikblum/yarn-storybook

Steps:

    yarn set version stable
    yarn init
    yarn add --dev vite
    npx sb@next init --builder=vite
      Choose web-components type
    yarn add --dev @storybook/builder-vite (is not added automatically)
    yarn storybook
```

### System

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.3.1 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.10.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (108.0.1462.46)

vite: ^4.0.3
storybook: 7.0.0-beta.15
```

### Additional context

I tried also with yarn canary (v4) without success

**Comment by geisterfurz007** [comment]
This doesn't appear to be limited to pnp; I am facing the same thing with `nodeLinker: node-modules` in a monorepo Yarn 3 project.

**Comment by blikblum** [comment]
Some more info that may help:
 - it crashes regardless of being a package of type module or commonjs
 - seems a problem of dynamic import most likely from https://github.com/storybookjs/storybook/blob/d491ad3a97382f09bb0ffc5f61ea1df3e0ad1db5/code/lib/core-server/src/utils/get-builders.ts#L20 
 - seems a candidate to fix https://github.com/storybookjs/storybook/pull/20408/files#diff-fed81323d1084bcbecbbf0016c47ae40af46b4d9abc041fa8a9f0fcae32ff896R21

**Comment by ArianHamdi** [comment]
The same applies to NextJS apps:
node.js : v16.19.0
nextjs : v13.1.1
storybook : v7.0.0-beta.16
OS : Windows 11 Pro 64-bit  (10.0, Build 22621)

Pnpm and npm are also not working.

**Comment by shilman** [comment]
Ooh-la-la!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.17 containing PR #20430 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by blikblum** [comment]
Thanks. I confirm is working now with storybook 7 beta 17 and yarn stable (v3)

As a side note, a different error occurs when running with yarn v4 (release candidate).

I filled a [bug report](https://github.com/yarnpkg/berry/issues/5164) at yarn but was marked as [wont fix](https://github.com/yarnpkg/berry/issues/5164#issuecomment-1367995356)

For the time being, i will stick with yarn v3.

**Comment by shilman** [comment]
cc @valentinpalkovic

**Comment by ndelangen** [comment]
@valentinpalkovic did this PR: https://github.com/storybookjs/storybook/pull/20430 fix the issue? Can this be closed?

**Comment by blikblum** [comment]
This bug is fixed on my side and for me it can be closed.

Still not working with yarn pnp but due to a different bug: https://github.com/storybookjs/storybook/issues/24635

**Comment by valentinpalkovic** [comment]
Closing. Let me know, if some of you still encounter the issue! Thanks.

**Comment by Dmytro-Shulha** [comment]
It seems like I've stumbled upon this exact issue recently when tried to imlpement Storybook custom indexer using this example:
https://github.com/Sidnioulz/storybook-sidebar-urls

On stackblitz it runs smoothly, but when I cloned that repo to my Windows 10 machine and started storybook using Git bash terminal - got ERR_UNSUPPORTED_ESM_URL_SCHEME

![Image](https://github.com/user-attachments/assets/b73996ae-42c8-4e40-baf9-0d4b9ab49c26)

**Comment by Sidnioulz** [comment]
🤷 I don't use Yarn, can't help you with that one unfortunately.

**Comment by Dmytro-Shulha** [comment]
> 🤷 I don't use Yarn, can't help you with that one unfortunately.

On the main page of `storybook-sidebar-url` repository it is recommended to use yarn:
![Image](https://github.com/user-attachments/assets/5805b38c-f648-4518-bd46-69fd6963ac0c)

Got same error with pnpm:
```bash
rm -rf node_modules
npx pnpm install
npx pnpm storybook
```

![Image](https://github.com/user-attachments/assets/0c0fd440-4472-427c-9226-46459f9ea772)

Also got dependency issues with `npm install`:

![Image](https://github.com/user-attachments/assets/994dcba3-8cb5-4092-8589-0857328e0f03)


Can you please suggest a package manager you use for that project @Sidnioulz ?

**Comment by Sidnioulz** [comment]
`storybook-sidebar-url` is a showcase repo, I do not maintain it or provide support for it due to time limitations. I also generally speaking do not support non-POSIX operating systems.

There's a hint here with `c:` in the error message that this could be a Windows compatibility issue. See https://github.com/storybookjs/storybook/pull/20430/files#diff-fed81323d1084bcbecbbf0016c47ae40af46b4d9abc041fa8a9f0fcae32ff896R21 for an example fix in this here issue. You could do the same to replace the failing relative import, or you could use WSL to have a better-behaving development environment.

**Comment by Dmytro-Shulha** [comment]
Been able to workaround it by adding `file://` at
```js
const fileData = await import(`file://${fileName}`);
```

![Image](https://github.com/user-attachments/assets/5b9e3244-127f-4bba-9c1d-02530ac6de0f)

![Image](https://github.com/user-attachments/assets/34fe4bb6-b2ad-4ef1-a7cc-7e7cf6c3c7c5)

**Comment by Sidnioulz** [comment]
Thanks for sharing the outcome!
