### ISSUE TITLE
[Bug]: addon-storyshots does not work if Jest v.29^ is installed in same repo

### ISSUE THREAD

**Issue by mhdSid** [storybookjs/storybook#20414]
### Describe the bug

Currently, "addon-storyshots" uses Jest v.26^ dependencies in order to execute the tests and generate snapshots.
In our projects, we have recently migrated to use Node 18 along with Jest v.^29.

The bug is a result of clash of versioning between the repo's Jest v.^29 vs "addon-storyshots"  Jest v.26

`Error: Cannot set properties of undefined (setting 'STORYBOOK_REACT_CLASSES')`

### To Reproduce

```shell
- Install Jest v.^29 in project and run unit tests with this version installed.
- Install "addon-storyshots" with latest version of storybook deps.
- Run unit tests
- Run Storybook tests
- Both tests fail
```

### System

```shell
MacOs BigSur
Node18.12.0
Yarn 3
```

**Comment by jonniebigodes** [comment]
The Storyshots addon is officially deprecated and will be removed in a future release of Storybook. To help with the transition process, we've created a [migration guide](https://storybook.js.org/docs/writing-tests/storyshots-migration-guide) for the available options and common use cases.
