### ISSUE TITLE
[Bug]: [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'e:'    

### ISSUE THREAD

**Issue by AhammadAliPK** [storybookjs/storybook#20415]
### Describe the bug

getting this error when adding storybook into next js 13, working well for for other person and he is using pnpm, 

to reproduce, run below commands, 

`npx sb init --builder webpack5  `
`npm run storybook`

im getting below error 
`Err! Error [err_unsupported_esm_url_scheme]: only urls with a scheme in: file, data are supported by the default esm loader. On windows, absolute paths must be valid file: // urls. Received protocol 'e: ' err! At __node_internal_capturelargerstacktrace (node: internal/errors:478:5) err! At new nodeerror (node: internal/errors:387:5) err! At throwifunsupportedurlscheme (node: internal/modules/esm/resolve:1017:11) err! At defaultresolve (node: internal/modules/esm/resolve:1097:3) err! At nextresolve (node: internal/modules/esm/loader:163:28) err! At esmloader. Resolve (node: internal/modules/esm/loader:841:30) err! At esmloader. Getmodulejob (node: internal/modules/esm/loader:424:18) err! At esmloader. Import (node: internal/modules/esm/loader:525:22) err! At importmoduledynamically (node: internal/modules/cjs/loader:1104:29) err! At importmoduledynamicallywrapper (node: internal/vm/module:438:21) err! At importmoduledynamically (node: vm:389:46) err! At importmoduledynamicallycallback (node: internal/process/esm_loader:35:14) err! At getpreviewbuilder (e: \freelance works\gamepay\gamepay-web\node_modules\@storybook\core-server\dist\index. Js:10:1913) err! At builddevstandalone (e: \freelance works\gamepay\gamepay-web\node_modules\@storybook\core-server\dist\index. Js:33:2139) err! At async withtelemetry (e: \freelance works\gamepay\gamepay-web\node_modules\@storybook\core-server\dist\index. Js:33:5533) err! At async dev (e: \freelance works\gamepay\gamepay-web\node_modules\@storybook\cli\dist\generate. Js:441:440) err! Error [err_unsupported_esm_url_scheme]: only urls with a scheme in: file, data are supported by the default esm loader. On windows, absolute paths must be valid file: // urls. Received protocol 'e: ' err! At __node_internal_capturelargerstacktrace (node: internal/errors:478:5) err! At new nodeerror (node: internal/errors:387:5) err! At throwifunsupportedurlscheme (node: internal/modules/esm/resolve:1017:11) err! At defaultresolve (node: internal/modules/esm/resolve:1097:3) err! At nextresolve (node: internal/modules/esm/loader:163:28) err! At esmloader. Resolve (node: internal/modules/esm/loader:841:30) err! At esmloader. Getmodulejob (node: internal/modules/esm/loader:424:18) err! At esmloader. Import (node: internal/modules/esm/loader:525:22) err! At importmoduledynamically (node: internal/modules/cjs/loader:1104:29) err! At importmoduledynamicallywrapper (node: internal/vm/module:438:21) err! At importmoduledynamically (node: vm:389:46) err! At importmoduledynamicallycallback (node: internal/process/esm_loader:35:14) err! At getpreviewbuilder (e: \freelance works\gamepay\gamepay-web\node_modules\@storybook\core-server\dist\index. Js:10:1913) err! At builddevstandalone (e: \freelance works\gamepay\gamepay-web\node_modules\@storybook\core-server\dist\index. Js:33:2139) err! At async withtelemetry (e: \freelance works\gamepay\gamepay-web\node_modules\@storybook\core-server\dist\index. Js:33:5533) err! At async dev (e: \freelance works\gamepay\gamepay-web\node_modules\@storybook\cli\dist\generate. Js:441:440) { err! Code: 'err_unsupported_esm_url_scheme' err! } warn broken build, fix the error above. Warn you may need to refresh the browser.`

**Comment by shilman** [comment]
closing as dupe to #20404
