### ISSUE TITLE
[Bug]: [v7.0.0-beta.16] Broken production build when `manager.js` added

### ISSUE THREAD

**Issue by fmal** [storybookjs/storybook#20427]
### Describe the bug

I've successfully setup latest beta in my project which uses Yarn in PnP Mode, everything is working great in development, but i've run into interesting quirk with generated production build being broken. 

Storybook is installed in a `storybook` workspace within a monorepo, i've put together a minimal reproduction at https://github.com/fmal/storybook-yarn-monorepo.

As long as i don't introduce `manager.js`,  production build generates correct artifacts.
Below is an excerpt from `storybook/dist/index.html`. `sb-addons` imports paths are pointing to folder structure that actually exists inside the generated `dist` directory. When i serve the generated assets or upload to Chromatic (https://63ac6ba300bd3c91074bc891-ryhbvuoglg.chromatic.com/?path=/docs/example-introduction--docs), Storybook is working fine. 

```html
    <script type="module">
      import './sb-manager/runtime.mjs';

      
      import './sb-addons/%40storybook-addon-links-virtual-960f351619/0/cache/%40storybook-addon-links-npm-7.0.0-beta.16-1b3d95b06a-7919f55a78.zip/node_modules/%40storybook/addon-links/dist/manager-bundle.mjs';
      
      import './sb-addons/%40storybook-addon-essentials-virtual-56aaa8e568/0/cache/%40storybook-addon-essentials-npm-7.0.0-beta.16-b9b8c5e1e3-f20a06ca2f.zip/node_modules/%40storybook/addon-essentials/dist/controls/manager-bundle.mjs';
           
      // more imports
    </script>   
```

When I create `manager.js` in `storybook/.storybook/manager.js` (even an empty file!) and run the build again (either `yarn run build` inside workspace or `yarn run build-storybook` in repo root), the generated production build becomes broken. Specifically the paths in `dist/index.html` are now pointing to structure that doesn't exist in generated `dist` directory:

```html
    <script type="module">
      import './sb-manager/runtime.mjs';

      
      import './sb-addons/.yarn/__virtual__/%40storybook-addon-links-virtual-960f351619/0/cache/%40storybook-addon-links-npm-7.0.0-beta.16-1b3d95b06a-7919f55a78.zip/node_modules/%40storybook/addon-links/dist/manager-bundle.mjs';
      
      import './sb-addons/.yarn/__virtual__/%40storybook-addon-essentials-virtual-56aaa8e568/0/cache/%40storybook-addon-essentials-npm-7.0.0-beta.16-b9b8c5e1e3-f20a06ca2f.zip/node_modules/%40storybook/addon-essentials/dist/controls/manager-bundle.mjs';
   
       // more imports 
    </script>    
```

<img width="1643" alt="Screenshot 2022-12-28 at 20 29 39" src="https://user-images.githubusercontent.com/927591/209862968-45264950-8303-45b8-9357-106802d9bcf5.png">

Delete the `manager.js` rerun the build and generated build is correct again...

Seems like this is related to how package paths are resolved with Yarn PnP (cc @merceyz), but why they resolve different depending on the presence of `manager.js` is beyond me.

@shilman this is the only thing stopping me from being able to successfully use the pre-release, 
so i would highly appreciate looking into this 😃 

### To Reproduce

```shell
https://github.com/fmal/storybook-yarn-monorepo
```

### System

```shell
Environment Info:

  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz
  Binaries:
    Node: 16.17.0 - /private/var/folders/p8/xrx0cff927l3pllrjxkqmgb40000gp/T/xfs-35728a57/node
    Yarn: 3.3.1 - /private/var/folders/p8/xrx0cff927l3pllrjxkqmgb40000gp/T/xfs-35728a57/yarn
    npm: 8.15.0 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 107.0.1
    Safari: 14.1.2
```

**Comment by IanVS** [comment]
cc: @ndelangen.

**Comment by Psvensso** [comment]
Same behavior with Pnpm workspace repo and beta 19.
 
 ```
 "@storybook/manager-api": "^7.0.0-beta.19",
 "@storybook/addon-docs": "^7.0.0-beta.19",
 "@storybook/addon-essentials": "^7.0.0-beta.19",
 "@storybook/addon-storysource": "^7.0.0-beta.19",
 "@storybook/react": "^7.0.0-beta.19",
 "@storybook/react-vite": "^7.0.0-beta.19",
 ```

**Comment by ndelangen** [comment]
I'll take a look at the reproduction next week

**Comment by ndelangen** [comment]
Might be somehow related to https://github.com/storybookjs/storybook/issues/20418
...and thus: https://github.com/storybookjs/storybook/pull/20331

**Comment by ndelangen** [comment]
I think what might be happening is that when esbuild is considering all the entrypoint, it find the common path between all the entries.

When there is no manager.js file, the common path will be somewhere deep in node_modules.
When manager.js **IS** present.. this changes things. resulting in the path being far longer.

**Comment by fmal** [comment]
@ndelangen yeah definitely presence of `manager.js` is somehow affecting the resolution of addon bundles, seems like with `manager.js` the bundles are looked up according to `packageLocation` field of virtual entries in `.pnp.cjs` file.
<img width="1176" alt="Screenshot 2023-01-08 at 20 53 24" src="https://user-images.githubusercontent.com/927591/211216073-a022e4bd-db61-415f-b1e1-f2bfc6ea44fe.png">

But these locations are not available in the output folder of production build of course.

Would highly appreciate looking into this as this is a showstopper for me to deploy the production build of storybook v7. Hope there is an easy way to fix this.

**Comment by shilman** [comment]
Boo-yah!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.23 containing PR #20550 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
