### ISSUE TITLE
[Bug]: Can't build storybook 6.5.x with Bazel due to @storybook/metadata failing to find package.json

### ISSUE THREAD

**Issue by maciek-codes** [storybookjs/storybook#20429]
### Describe the bug

I am working in a monorepo that uses Bazel and I tried upgrading from 6.4.x to 6.5.x.

Bazel uses different working directory to run `nodejs_binary` target to execute `storybook build`. It fails to build, because `@storybook/metadata` relies on the assumption that the `package.json` file will be in the same working directory as the current process' working directory (it uses `readPkgUp(process.cwd())`).

I am using SB version 6.5.15.

I tried adding `--disable-telemetry` to the build command line, as well as `main.js`.

Error:
```bash
TypeError: Cannot read property 'packageJson' of undefined
    at _callee2$ (/tmpdir/{pid}/execroot/__main__/node_modules/@storybook/telemetry/dist/cjs/storybook-metadata.js:327:15)
    at tryCatch (/tmpdir/{pid}/execroot/__main__/node_modules/regenerator-runtime/runtime.js:63:40)
    [...]
    at /tmpdir/{pid}/execroot/__main__/node_modules/@storybook/telemetry/dist/cjs/storybook-metadata.js:70:97
    at getStorybookMetadata (/tmpdir/{pid}/execroot/__main__/node_modules/@storybook/telemetry/dist/cjs/storybook-metadata.js:351:18)
```

Due to the nature of Bazel, it's tricky to change the command working directory - at least without breaking other things.
It'd be great if:
- storybook would skip reading `package.json` if directory was disabled
- or if it tried to find `package.json` in the directory of my choice
- tried to traverse the `config_dir` also 

### System

```shell
6.5.15
```

**Comment by vanessayuenn** [comment]
Could you please upgrade to the latest Storybook@7.x version and see if this issue persists? We've made lots of improvements in Storybook since 7.0 so it's quite likely that this issue has been resolved already. If this is still a problem, please update this issue with reproduction steps for 7.x version. Thank you!
