### ISSUE TITLE
[Bug]: Storysource add-on *depends* on Docs add-on to work

### ISSUE THREAD

**Issue by jpzwarte** [storybookjs/storybook#20421]
### Describe the bug

The Docs add-on uses the `csf-plugin` module to convert the source of a story to a `storysource: { source: '...' }` parameter. 

If you happen to not have the Docs add-on loaded then:
- You *do not* get a message that you should have loaded it for the storysource add-on to work
- You only see "Loading sources..." in the Story panel of the Storysource add-on

Easy to reproduce with 7.0.0-beta.15 by disabling or not loading `@storybook/addon-docs`:

```js
    {
      name: '@storybook/addon-essentials',
      options: {
        docs: false
      }
    },
    '@storybook/addon-storysource'
```

**Comment by shilman** [comment]
Olé!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.31 containing PR #20688 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
This is still an issue with the Vite builder. Will work on this as followup

**Comment by jpzwarte** [comment]
@shilman I can confirm that storysource works fine now when `docs: false` with `@storybook/web-components-webpack5`. Thanks!

**Comment by shilman** [comment]
Olé!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.48 containing PR #21096 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```

**Comment by shilman** [comment]
Jiminy cricket!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.51 containing PR #21159 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```
