### ISSUE TITLE
[Bug]: Broken link formatting in CLI options documentation

### ISSUE THREAD

**Issue by thibaudcolas** [storybookjs/storybook#20445]
### Describe the bug

On the [CLI Options](https://storybook.js.org/docs/react/api/cli-options) page ([cli-options.md](https://github.com/storybookjs/storybook/blob/next/docs/api/cli-options.md)), the first aside’s text shows the Markdown source as-is:

```markdown
[…]
Participation is optional, and you may [opt-out](../configure/telemetry.md#how-to-opt-out) if you'd not like to share any information.
```

### To Reproduce

Go to <https://storybook.js.org/docs/react/api/cli-options>.

### Additional context

This is puzzling because there doesn’t seem to be anything wrong with that specific link’s formatting, the target is correct, and there is a similar "Markdown link in an aside" further down the page that works fine.

**Comment by jonniebigodes** [comment]
@thibaudcolas, thanks for taking the time to reach out to us and letting us know. I've checked, and it seems that it's only affecting the current version of the documentation (i.e., for version 6.5), which is on the `main` branch and not the `next` branch (i.e., documentation for the current version 7.0 beta). I'll push a pull request on Monday morning addressing this.

Hope you have a fantastic day.

Stay safe

**Comment by jonniebigodes** [comment]
Closing this as the pull request was merged just moments ago.
