### ISSUE TITLE
[Bug]: Storybook v7 dependencies are not found with pnpm workspace without hoist

### ISSUE THREAD

**Issue by MPeloquin** [storybookjs/storybook#20454]
### Describe the bug

With storybook v7, if I have a pnpm workspace with a `.npmrc` file with the [option](https://pnpm.io/npmrc#hoist)

```yaml
hoist=false
```

Then storybook fails with the following error: `Starting in 7.0, react and react-dom are now required peer dependencies of Storybook.`

If I add the following options in my `.npmrc` file, re run `pnpm install`, then storybook works: 

```yaml
hoist-pattern[]=*react*
hoist-pattern[]=*storybook*
```

There's probably an issue with the peer dependencies declaration of storybook.

### To Reproduce

Clone the following repo: https://github.com/MPeloquin/StorybookPnpmWorkspaceIssue
Run the following commands:

```shell
pnpm install
cd apps/vite-project
pnpm storybook
```

Notice react error, even though react is declared in dependecies of my vite-project.

### System

```shell
System:
    OS: macOS 12.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 16.18.0 - ~/.nvm/versions/node/v16.18.0/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.0/bin/npm
  npmPackages:
    @storybook/addon-essentials: ^7.0.0-beta.15 => 7.0.0-beta.15 
    @storybook/addon-interactions: ^7.0.0-beta.15 => 7.0.0-beta.15 
    @storybook/addon-links: ^7.0.0-beta.15 => 7.0.0-beta.15 
    @storybook/blocks: ^7.0.0-beta.15 => 7.0.0-beta.15 
    @storybook/react: ^7.0.0-beta.15 => 7.0.0-beta.15 
    @storybook/react-vite: ^7.0.0-beta.15 => 7.0.0-beta.15 
    @storybook/testing-library: ^0.0.13 => 0.0.13
```

**Comment by IanVS** [comment]
React and React-dom are indeed peer dependencies of Storybook.  You should add them to your package.json's `devDependencies`.  See https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#react-peer-dependencies-required for details.  There is also an automigration that is run when installing or upgrading storybook that adds react and react-dom automatically.

**Comment by IanVS** [comment]
Sorry, I just saw your note about having react and react-dom installed in your project.  I'll take a look at this.

**Comment by shilman** [comment]
Huzzah!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.19 containing PR #20459 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by IanVS** [comment]
@ndelangen maybe we can move `ensure-react-peer-deps` somewhere else?  Maybe as a runtime check in addon-docs?  (I think that's why we require react, after all, right?  The MDX support and storybook blocks?)

**Comment by ndelangen** [comment]
@IanVS See my comment in the existing PR: https://github.com/storybookjs/storybook/pull/20538#pullrequestreview-1241110663
