### ISSUE TITLE
[Bug]: Storyshots with Vite has the following error: Your test suite must contain at least one test.

### ISSUE THREAD

**Issue by Lory1990** [storybookjs/storybook#20452]
### Describe the bug

When I hit `yarn test` appears the following message

```
$ jest
 FAIL  src/storyshots.test.ts
  ● Test suite failed to run

    Your test suite must contain at least one test.

      at onResult (node_modules/@jest/core/build/TestScheduler.js:133:18)
      at node_modules/@jest/core/build/TestScheduler.js:254:19
      at node_modules/emittery/index.js:363:13
          at Array.map (<anonymous>)
      at Emittery.emit (node_modules/emittery/index.js:361:23)
```

### To Reproduce

* Clone this repo https://github.com/Lory1990/storyshots-vite-test
* `yarn install`
* `yarn test`

### System

```shell
Environment Info:

  System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 18.12.1 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Safari: 16.2
  npmPackages:
    @storybook/addon-actions: ^6.5.15 => 6.5.15 
    @storybook/addon-essentials: ^6.5.15 => 6.5.15 
    @storybook/addon-interactions: ^6.5.15 => 6.5.15 
    @storybook/addon-links: ^6.5.15 => 6.5.15 
    @storybook/addon-storyshots: ^6.5.15 => 6.5.15 
    @storybook/builder-vite: ^0.2.6 => 0.2.6 
    @storybook/react: ^6.5.15 => 6.5.15 
    @storybook/testing-library: ^0.0.13 => 0.0.13
```

**Comment by IanVS** [comment]
I'm not super familiar with storyshots, but it's not very well maintained so there could well be issues in using it together with Vite.  Have you looked into using the storybook test runner for visual regression testing instead?  https://github.com/storybookjs/test-runner#image-snapshot-recipe

**Comment by Lory1990** [comment]
Hi @IanVS i have seen that it works with your recepie, great!

This is a good workroud but storyshots remains broken

**Comment by William0155** [comment]
> ### Describe the bug
> When I hit `yarn test` appears the following message
> 
> ```
> $ jest
>  FAIL  src/storyshots.test.ts
>   ● Test suite failed to run
> 
>     Your test suite must contain at least one test.
> 
>       at onResult (node_modules/@jest/core/build/TestScheduler.js:133:18)
>       at node_modules/@jest/core/build/TestScheduler.js:254:19
>       at node_modules/emittery/index.js:363:13
>           at Array.map (<anonymous>)
>       at Emittery.emit (node_modules/emittery/index.js:361:23)
> ```
> 
> ### To Reproduce
> * Clone this repo https://github.com/Lory1990/storyshots-vite-test
> * `yarn install`
> * `yarn test`
> 
> ### System
> ```shell
> Environment Info:
> 
>   System:
>     OS: macOS 13.1
>     CPU: (8) arm64 Apple M1
>   Binaries:
>     Node: 18.12.1 - /usr/local/bin/node
>     Yarn: 1.22.19 - ~/.yarn/bin/yarn
>     npm: 8.19.2 - /usr/local/bin/npm
>   Browsers:
>     Chrome: 108.0.5359.124
>     Safari: 16.2
>   npmPackages:
>     @storybook/addon-actions: ^6.5.15 => 6.5.15 
>     @storybook/addon-essentials: ^6.5.15 => 6.5.15 
>     @storybook/addon-interactions: ^6.5.15 => 6.5.15 
>     @storybook/addon-links: ^6.5.15 => 6.5.15 
>     @storybook/addon-storyshots: ^6.5.15 => 6.5.15 
>     @storybook/builder-vite: ^0.2.6 => 0.2.6 
>     @storybook/react: ^6.5.15 => 6.5.15 
>     @storybook/testing-library: ^0.0.13 => 0.0.13
> ```
> 
> ### Additional context
> _No response_

I meet same problem.

**Comment by ndelangen** [comment]
The future of storyshots is the test-runner:
https://storybook.js.org/docs/react/writing-tests/test-runner#page-top

And use the play function for expectations:
https://storybook.js.org/docs/react/writing-stories/play-function#page-top

We will not be making any improvement / changes to storyshots.
