### ISSUE TITLE
[Bug]: pnpm is not used reliably

### ISSUE THREAD

**Issue by IanVS** [storybookjs/storybook#20463]
### Describe the bug

@rohanrajpal reported issues with yarn being preferred over pnpm in https://github.com/storybookjs/storybook/issues/15675#issuecomment-1368172238.  I'm creating this ticket to troubleshoot and discuss improvements.

### To Reproduce

It's a little unclear, but I suspect this occurs when a `yarn.lock` file is found somewhere in the file system in an ancestor directory.  If so, we will prefer yarn, even if a pnpm lock file is closer to the project.

**Comment by IanVS** [comment]
@rohanrajpal, I'm pretty sure you must have a `yarn.lock` file somewhere on your system between your pnpm workspace project and the root.  Most likely in your home directory.

This is not an uncommon scenario (usually it's unintentional, though), so I've opened a PR which will adjust the logic used by the Storybook CLI to prefer the _closest_ lockfile instead of looking for one kind, then another.

**Comment by rohanrajpal** [comment]
> @rohanrajpal, I'm pretty sure you must have a `yarn.lock` file somewhere on your system between your pnpm workspace project and the root. Most likely in your home directory.
> 
> This is not an uncommon scenario (usually it's unintentional, though), so I've opened a PR which will adjust the logic used by the Storybook CLI to prefer the _closest_ lockfile instead of looking for one kind, then another.

You were right! There was a `yarn.lock` file in my home directory for no reason at all 🤦

Btw curious to know as to why does the program search starting from the home directory to the current directory instead of the other way around? I guess that would fix this issue?

**Comment by IanVS** [comment]
You can take a look at the PR I linked to see what was happening. We looked for both yarn and pnpm, but then check if we found a yarn file first, then check the pnpm.  The PR I posted looks upwards from the cwd to find the closest lockfile instead.

**Comment by shilman** [comment]
Whoopee!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.19 containing PR #20464 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by rohanrajpal** [comment]
> Whoopee!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.19 containing PR #20464 that references this issue. Upgrade today to the `@next` NPM tag to try it out!
> 
> ```
> npx sb upgrade --prerelease
> ```
> 
> Closing this issue. Please re-open if you think there's still more to do.

This works, thanks!
