### ISSUE TITLE
[Bug]: [7.0.0-beta.17]: Storybook doesn't display SVG icons

### ISSUE THREAD

**Issue by michu2k** [storybookjs/storybook#20465]
### Describe the bug

In the latest version of the Storybook (7.0.0-beta.17) SVG icons in the Introduction.mdx don't display correctly.

Here's a screenshot of what it looks like: 
![image](https://user-images.githubusercontent.com/22056149/210166997-a79707b2-a3b9-4f64-a46d-3c6668927852.png)

### To Reproduce

```shell
Run the following commands:

npx create-next-app@latest
npx sb@next init
npm run storybook
```

### System

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
  Binaries:
    Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (108.0.1462.54)
  npmPackages:
    @storybook/addon-essentials: ^7.0.0-beta.17 => 7.0.0-beta.17
    @storybook/addon-interactions: ^7.0.0-beta.17 => 7.0.0-beta.17
    @storybook/addon-links: ^7.0.0-beta.17 => 7.0.0-beta.17
    @storybook/blocks: ^7.0.0-beta.17 => 7.0.0-beta.17
    @storybook/nextjs: ^7.0.0-beta.17 => 7.0.0-beta.17
    @storybook/react: ^7.0.0-beta.17 => 7.0.0-beta.17
    @storybook/testing-library: ^0.0.14-next.1 => 0.0.14-next.1
```

**Comment by shilman** [comment]
@valentinpalkovic assuming this is either a windows issue or a nextjs issue (or both) -- either way, ball's in your court! 😂

**Comment by bartlangelaan** [comment]
I also experienced this issue. At first I thought that the Storybook beta was broken, but it is actually a simpler issue - the NextJS framework changes all image imports.

Normally, if you would do this:
```
import image from './image.svg';
console.log(image);
```
You would get a string, which is the location where the svg is hosted. However, if you use the NextJS framework plugin from Storybook, the same code would give a different output. It would output an object with a `src` property inside.

This means that the default Storybook examples break, because `<img src="[object Object]" />` will be rendered.

While this is not a bug in Storybook, or a bug in the NextJS plugin, it _does_ give a bad first impression of Storybook. The recommended way of starting a NextJS+Storybook project shows broken images by default. Maybe the NextJS plugin should replace the demo content with content that is compatible with the plugin, to not scare off users that are trying Storybook out for the first time.

**Comment by michu2k** [comment]
It seems to me there is a problem with Storybook's webpack config. After updating the storybook webpack config with the example from the docs [(Storybook for Next.js)](https://github.com/storybookjs/storybook/tree/next/code/frameworks/nextjs#custom-webpack-config) and simply replacing `@svgr/webpack` with `url-loader` it looks like the SVG icons are rendered correctly.

**Comment by valentinpalkovic** [comment]
@bartlangelaan You‘re right. We want to mimic Next.js behaviour in Storybook by not giving back the resource path from an image directly, but to return an object, which can be passed directly to Next.js Image component. The documentation and the example stories have to be adjusted! I will find some time next week to update the examples! 

Thank you so much for your investigations!

**Comment by valentinpalkovic** [comment]
Issue is fixed since [v7.0.0-beta.29](https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.29)

**Comment by shilman** [comment]
Yee-haw!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.44 containing PR #20798 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```

**Comment by carlosrsabreu** [comment]
For those who are struggling with `.svg` images using the nrwl/nx monorepo, try this:

````javascript
webpackFinal: (config) => {
    // this modifies the existing image rule to exclude .svg files
    // since we want to handle those files with @svgr/webpack
    const svgRules = config.module.rules.filter((rule) =>
      rule.test.test('.svg'),
    );

    svgRules.forEach((rule) => {
      rule.exclude = /\.svg$/;
    });

    // configure .svg files to be loaded with @svgr/webpack
    config.module.rules.push({
      test: /\.svg$/,
      use: ['@svgr/webpack'],
    });

    return config;
}
````

Read more [here](https://github.com/RyanClementsHax/storybook-addon-next/issues/100).

**Comment by Karibash** [comment]
When using Next.js, using forEach instead of find works fine.
I think the [documentation](https://github.com/storybookjs/storybook/tree/next/code/frameworks/nextjs#custom-webpack-config) needs to be corrected.
```ts
config?.module?.rules?.forEach(rule => {
  if (!rule || typeof rule !== 'object') return;
  if (rule.test instanceof RegExp && rule.test.test('.svg')) {
    rule.exclude = /\.svg$/;
  }
});
```

**Comment by mariovde-IIO** [comment]
@Karibash  or @carlosrsabreu  where would this code be added?
could you post the new file please?

thanks!

**Comment by carlosrsabreu** [comment]
> @Karibash or @carlosrsabreu where would this code be added? could you post the new file please?
> 
> thanks!

In `.storybook/main.js` file:

```
module.exports = {
  // All configs you have set for storybook
  webpackFinal: async (config) => {
    // code goes here
  }
}
```

**Comment by mariovdeEINR** [comment]
yes, that worked! Thanks a bunch!
