### ISSUE TITLE
[Bug]: Stories Unable to compile with module type

### ISSUE THREAD

**Issue by Dhananjay-JSR** [storybookjs/storybook#20484]
### Describe the bug

when the type is defined as a module instead of commonjs in package JSON stories fail to compile showing unable to find loader error

### Additional context

![image](https://user-images.githubusercontent.com/47073516/210377202-00f93da9-c5e5-4ad7-a93f-289da42b7b96.png)

**Comment by shilman** [comment]
Can you please share more information about your setup, e.g. `npx sb info`?

**Comment by ndelangen** [comment]
The problem isn't the module type.. the problem in this example is JSX, in `.cjs` file.

The error stack trace clearly points at the `<` character which isn's valid JS.

This problem might go away in 7.0 beta, give it a try?
