### ISSUE TITLE
[Bug]: Impossible to start storybook (opensslErrorStack)

### ISSUE THREAD

**Issue by achammah** [storybookjs/storybook#20482]
### Describe the bug

New to storybook, tried installing storybook on my react/typescript project using tsdx

> Ran tsdx in one terminal : No issue
> opened a new terminal in the same folder -> run yarn storybook  (as in README.md)

got this error

```
yarn run v1.22.19
$ start-storybook -p 6006
info @storybook/react v6.5.15
info
info => Loading presets
info Addon-docs: using MDX1
info => Using implicit CSS loaders
info => Using prebuilt manager
(node:3171) DeprecationWarning: Default PostCSS plugins are deprecated. When switching to '@storybook/addon-postcss',       
you will need to add your own plugins, such as 'postcss-flexbugs-fixes' and 'autoprefixer'.

See https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-default-postcss-plugins for details.
(Use `node --trace-deprecation ...` to show where the warning was created)
info => Using default Webpack4 setup
Starting type checking service...
10% building 1/7 modules 6 active ...enerated-config-entry.jsnode:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported  
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:140:10)
    at module.exports (/mnt/c/<folder>/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/mnt/c/<folder>/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/mnt/c/<folder>/node_modules/webpack/lib/NormalModule.js:471:10)
    at /mnt/c/<folder>/node_modules/webpack/lib/NormalModule.js:503:5
    at /mnt/c/<folder>/node_modules/webpack/lib/NormalModule.js:358:12
    at /mnt/c/<folder>/node_modules/loader-runner/lib/LoaderRunner.js:373:3       
    at iterateNormalLoaders (/mnt/c/<folder>/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at /mnt/c/<folder>/node_modules/loader-runner/lib/LoaderRunner.js:205:4 {     
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v19.3.0
error Command failed with exit code 1.
```
I have absolutely no idea why this occur and how I might solve it

### To Reproduce

```shell
> npx tsdx create storybooklibrary
> template react-with-storybook
in one terminal
> cd storybooklibrary
> npm start
open other terminal
> cd storybooklibrary
> npm run storybook
```

**Comment by shilman** [comment]
what version of node are you using?

**Comment by achammah** [comment]
19.3 - do you think this might be the source of the problem ?

**Comment by shilman** [comment]
definitely. what's the output of `npx sb info`?

**Comment by darkSalvation** [comment]
Hi, we are running into the same issue with node LTS version: 

System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz
  Binaries:
    Node: 19.1.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.2.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.3 - C:\VisualStudio\xxx\node_modules\.bin\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (108.0.1462.54)
  npmPackages:
    @storybook/addon-a11y: ^6.5.13 => 6.5.14
    @storybook/addon-actions: ^6.5.13 => 6.5.14
    @storybook/addon-essentials: ^6.5.13 => 6.5.14
    @storybook/addon-events: ^6.2.9 => 6.2.9
    @storybook/addon-interactions: ^6.5.13 => 6.5.14
    @storybook/addon-links: ^6.5.13 => 6.5.14
    @storybook/addon-outline: ^6.5.13 => 6.5.14
    @storybook/addon-viewport: ^6.5.13 => 6.5.14
    @storybook/builder-vite: ^0.2.5 => 0.2.5
    @storybook/builder-webpack5: ^6.5.13 => 6.5.14
    @storybook/node-logger: ^6.5.13 => 6.5.14
    @storybook/preset-typescript: ^3.0.0 => 3.0.0
    @storybook/store: ^6.5.13 => 6.5.14
    @storybook/test-runner: ^0.9.0 => 0.9.1
    @storybook/testing-library: ^0.0.13 => 0.0.13
    @storybook/theming: ^6.5.13 => 6.5.14
    @storybook/vue3: ^6.5.13 => 6.5.14

**Comment by pastelite** [comment]
i found a temporary solution: add --openssl-legacy-provider to node option. I using windows and changing the "storybook" script in package.json to `SET NODE_OPTIONS=--openssl-legacy-provider && start-storybook -p 6006` solved the problem. iirc you can just remove the `SET` and it will works for mac and linux (`NODE_OPTIONS=--openssl-legacy-provider && start-storybook -p 6006`)

**Comment by Vassi** [comment]
I have this same error, unfortunately the workaround doesn't do anything for me. I'm using nothing the storybook init didn't give me.

`> NODE_OPTIONS=--openssl-legacy-provider && start-storybook -p 6006

info @storybook/react v6.5.15
info 
info => Loading presets
ℹ ｢wdm｣: wait until bundle finished: 
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/vassi/source/data-trails/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/vassi/source/data-trails/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/vassi/source/data-trails/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/vassi/source/data-trails/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/vassi/source/data-trails/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/vassi/source/data-trails/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/vassi/source/data-trails/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/home/vassi/source/data-trails/node_modules/loader-runner/lib/LoaderRunner.js:205:4) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'`

Environment Info:

  System:
    OS: Linux 4.19 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
  Binaries:
    Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
    npm: 8.19.3 - ~/.nvm/versions/node/v18.13.0/bin/npm
  npmPackages:
    @storybook/addon-actions: ^6.5.15 => 6.5.15 
    @storybook/addon-essentials: ^6.5.15 => 6.5.15 
    @storybook/addon-interactions: ^6.5.15 => 6.5.15 
    @storybook/addon-links: ^6.5.15 => 6.5.15 
    @storybook/builder-vite: ^0.2.6 => 0.2.6 
    @storybook/react: ^6.5.15 => 6.5.15 
    @storybook/testing-library: ^0.0.13 => 0.0.13

**Comment by aminya** [comment]
Use `cross-env` to apply the workaround for any operating system.

```json
  "scripts": {
    "storybook": "cross-env NODE_OPTIONS=--openssl-legacy-provider start-storybook -p 6006",
    "build-storybook": "cross-env NODE_OPTIONS=--openssl-legacy-provider build-storybook"
  }
```

```shell
npm i --save-dev cross-env
```

**Comment by Soviut** [comment]
If you're running nvm you can downgrade node to 16.

**Comment by thatsbrandon** [comment]
I'm running into this issue as well & none of the above has worked for me, currently tried `"dev": "cross-env NODE_OPTIONS=--openssl-legacy-provider start-storybook -p 6006"` & am getting the following error bellow

```console
$ cross-env NODE_OPTIONS=--openssl-legacy-provider start-storybook -p 6006
/usr/bin/node: --openssl-legacy-provider is not allowed in NODE_OPTIONS
```

Any ideas on how to get around this? Using `Yarn` if this helps

**Comment by shilman** [comment]
Please try upgrading to the 7.0 prerelease. Migration guide: https://storybook.js.org/migration-guides/7.0

**Comment by thatsbrandon** [comment]
@shilman Will try this when I get home, not sure which version I installed

**Comment by thatsbrandon** [comment]
Running into `ERR_OSSL_EVP_UNSUPPORTED` while using `"@storybook/html": "6.5.16",`
When switched to version 7 I get this following error
```console
yarn run v1.22.19
$ start-storybook -p 6006
info @storybook/react v6.5.13
info 
info => Loading presets
ℹ ｢wdm｣: wait until bundle finished: 
node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/home/node001/workspaces/mesh/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/node001/workspaces/mesh/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/node001/workspaces/mesh/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/node001/workspaces/mesh/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/node001/workspaces/mesh/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/node001/workspaces/mesh/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/node001/workspaces/mesh/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/home/node001/workspaces/mesh/node_modules/loader-runner/lib/LoaderRunner.js:205:4) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
error Command failed with exit code 1.
```
I have no clue why it's mow saying `@storybook/react v6.5.13` once I moved to version 7 of storybook

**Comment by ndelangen** [comment]
@thatsbrandon that would suggest to upgrade to storybook 7 is not complete or you're invoking storybook with an old bin?

**Comment by kyleatcolenso** [comment]
> Please try upgrading to the 7.0 prerelease. Migration guide: https://storybook.js.org/migration-guides/7.0

This works flawlessly. Thanks

**Comment by IgorSrdocRadical** [comment]
just downgrade node to 16.16.0:

1.nvm- v
2.nvm install 16.16.0
3.nvm use 16.16.0
4.export NODE_OPTIONS=--openssl-legacy-provider
5.npm run storybook

you'll be fine :)

**Comment by gianlucadibella** [comment]
> i found a temporary solution: add --openssl-legacy-provider to node option. I using windows and changing the "storybook" script in package.json to `SET NODE_OPTIONS=--openssl-legacy-provider && start-storybook -p 6006` solved the problem. iirc you can just remove the `SET` and it will works for mac and linux (`NODE_OPTIONS=--openssl-legacy-provider && start-storybook -p 6006`)

This one worked for me
