### ISSUE TITLE
[Feature Request]: Accept --configFolderPath option in automigrators & migrators

### ISSUE THREAD

**Issue by mandarini** [storybookjs/storybook#20508]
### Is your feature request related to a problem? Please describe

We want to be able to call the automigrators from Nx. In Nx, there are multiple `.storybook` directories, and multiple `.storybook/main|preview.js` files.

From within a Nx generator, we want to recursively call the automigrators (eg. `npx sb automigrate mainjsFramework`) and also pass a flag to tell Storybook which directory to look into, so for example:

```
npx sb automigrate --fixId mainjsFramework -c apps/my-app/.storybook
```

That would enable us to call the automigrators from Nx, or allow anyone to call the automigrators for a Nx workspace.

### Describe the solution you'd like

The functions that are listed [here](https://github.com/storybookjs/storybook/blob/next/code/lib/cli/src/automigrate/fixes/index.ts) to accept an option for `configFolderPath` (or anything similarly named, to allow Nx to pass the directory).

Similarly, if there's a migrator that looks for any other Storybook-related files (eg. stories transformation) to accept a relevant `glob` or something (like `sb migrate csf-2-to-3` which accepts `--glob`).

### Are you able to assist to bring the feature to reality?

yes, I can

**Comment by shilman** [comment]
Olé!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.51 containing PR #20647 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```
