### ISSUE TITLE
[Feature Request]: Return `port` information from `buildDevStandalone`

### ISSUE THREAD

**Issue by mandarini** [storybookjs/storybook#20509]
### Is your feature request related to a problem? Please describe

I need to be able to dynamically read the port, so that I can pass it to cypress, when running e2e tests in parallel. We need this specifically for Nx, but I think it could apply to other people's use cases as well.

### Describe the solution you'd like

[Here](https://github.com/storybookjs/storybook/blob/3ff30b6fac4ca4aa7e4c2e410ba46980fa1644d6/code/lib/core-server/src/build-dev.ts#L176) return `return { port }`

And for Angular:

[Here](https://github.com/storybookjs/storybook/blob/3ff30b6fac4ca4aa7e4c2e410ba46980fa1644d6/code/frameworks/angular/src/builders/start-storybook/index.ts#L110) return:
```
return { success: true, info: { port } };
```

### Are you able to assist to bring the feature to reality?

yes, I can

**Comment by mandarini** [comment]
We already discussed this with @valentinpalkovic, I am just creating this feature request for visibility!

**Comment by mandarini** [comment]
Will help with: https://github.com/nrwl/nx/issues/3953

**Comment by shilman** [comment]
¡Ay Caramba!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.26 containing PR #20575 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```
