### ISSUE TITLE
[Bug]: Investigate code getting pre-bundled multiple times

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#20514]
### Describe the bug

Inside the new `preview-api` package things appear to be included too many times. For example:

```
shilman@MBP14 lit-vite-default-js % grep getSelectionSpecifierFromPath node_modules/@storybook/preview-api/dist/*
node_modules/@storybook/preview-api/dist/chunk-S6GMWV4D.mjs:var getSelectionSpecifierFromPath = () => {
node_modules/@storybook/preview-api/dist/chunk-S6GMWV4D.mjs:    this.selectionSpecifier = getSelectionSpecifierFromPath();
node_modules/@storybook/preview-api/dist/core-client.js:var getSelectionSpecifierFromPath = () => {
node_modules/@storybook/preview-api/dist/core-client.js:    this.selectionSpecifier = getSelectionSpecifierFromPath();
node_modules/@storybook/preview-api/dist/index.js:var getSelectionSpecifierFromPath = () => {
node_modules/@storybook/preview-api/dist/index.js:    this.selectionSpecifier = getSelectionSpecifierFromPath();
node_modules/@storybook/preview-api/dist/preview-web.js:var getSelectionSpecifierFromPath = () => {
node_modules/@storybook/preview-api/dist/preview-web.js:    this.selectionSpecifier = getSelectionSpecifierFromPath();
```

Note that this is also bundled in the `preview` package as well, further contributing to the install size.

This may contribute to a ballooning install size in our benchmarks:

<img width="869" alt="image" src="https://user-images.githubusercontent.com/488689/210921260-0c9f235d-8f4a-4b2f-9402-d48fa33e2442.png">

**Comment by ndelangen** [comment]
These are all the commonJS files, which do indeed not tree-shake, and for backwards compatibility have all the old code still present/bundled.

What are we measuring here?

**Comment by ndelangen** [comment]
I can't say with full confidence, but I think these commonjs files would only ever be used by storyshots, I think.

**Comment by ndelangen** [comment]
I verified that the MJS files are in the prebundle.

**Comment by ndelangen** [comment]
I have noticed that the deprecation warnings for the removed packages don't actually make it into the ESM dist (they do appear in the CJS dist)

**Comment by ndelangen** [comment]
I verified, that in the webpack-builder the externalisation of the packages we want work correctly, and they are all ESM.

**Comment by ndelangen** [comment]
I found that vite-builder was using :
```
import externalGlobals from 'rollup-plugin-external-globals';
```
But this resulted in the code existing multiple times.
Switching to 
```
import { viteExternalsPlugin } from 'vite-plugin-externals';
```
made it work!

**Comment by ndelangen** [comment]
will open a PR.

**Comment by shilman** [comment]
w00t!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.26 containing PR #20594 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
