### ISSUE TITLE
[Bug]: [7.0.0-beta.20]: Vite is converting arrow function into `function ro()` on a production build

### ISSUE THREAD

**Issue by JUNNNI** [storybookjs/storybook#20522]
### Describe the bug

When creating a new Storybook build that is using Vite, components preview codes are converted into something wrong.

For example, arrow functions are converted into `function ro()` rather than `() =>`

![image](https://user-images.githubusercontent.com/8655890/211036943-d310f5d9-dd84-452a-9acb-be61d6c801c7.png)

### To Reproduce

1) Use these two files in order to create a new component and a story.
2) On two separate windows, start Storybook in development and generate a build.
3) Compare the two versions like in the image above. Arrow function defined for the `onClick` prop has been converted to `function ro()`

```tsx
// ExampleButton.tsx

type ButtonProps = {
    primary?: boolean;
    backgroundColor?: string;
    size?: 'small' | 'medium' | 'large';
    label: string;
    onClick?: () => void;
};

export const ExampleButton = ({ primary = false, size = 'medium', backgroundColor, label }: ButtonProps) => {
    const mode = primary ? 'storybook-button--primary' : 'storybook-button--secondary';

    return (
        <button
            type="button"
            className={['storybook-button', `storybook-button--${size}`, mode].join(' ')}
            style={{ backgroundColor }}
        >
            {label}
        </button>
    );
};
```

```tsx
// ExampleButton.stories.tsx

import type { Meta, StoryObj } from '@storybook/react';
import { ExampleButton } from './ExampleButton';

const meta: Meta<typeof ExampleButton> = {
    title: 'Example/Stories Button - Example',
    component: ExampleButton,
    tags: ['autodocs'],
};

export default meta;
type Story = StoryObj<typeof ExampleButton>;

export const Primary: Story = {
    args: {
        primary: true,
        label: 'Button',
    },
};
```

### System

```shell
MacOS Monterey 12.5.1
pnpm version 7.17.1
Storybook v7.0.0-beta.20
```

### Additional context

I know that Vite is using [esbuild](https://esbuild.github.io/) in development and [rollupjs](https://rollupjs.org/guide/en/) in development. Looks like rollup issue, would that be a configuration option available to fix that issue?

**Comment by wederchr** [comment]
Any updates on this? This is still an issue with 7.0.0-rc.5

**Comment by shilman** [comment]
Closing as duplicate to #21747 

Please lmk if you think this is not the case!
