### ISSUE TITLE
[Bug]: Missing react peer dependency on storybook v7 package

### ISSUE THREAD

**Issue by bryanjtc** [storybookjs/storybook#20537]
### Describe the bug

The following change: https://github.com/storybookjs/storybook/pull/20459, introduced the warnings below. `storybook` package depends on `@storybook/cli`

![image](https://user-images.githubusercontent.com/49354825/211233542-e100e991-c79a-4e07-8261-f13adcf48005.png)
![image](https://user-images.githubusercontent.com/49354825/211233545-6640bf8d-bfaf-4058-9edd-72d241fe9079.png)
![image](https://user-images.githubusercontent.com/49354825/211233552-aa6dfbc3-d82e-409d-95bc-1709fe55962b.png)

### To Reproduce

```shell
https://github.com/bryanjtc/storybook-7-vite-test
Run yarn install
```

### System

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
  Binaries:
    Node: 16.17.0 - /tmp/xfs-e389171e/node
    Yarn: 3.2.4 - /tmp/xfs-e389171e/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
```

**Comment by polRk** [comment]
It's stupid to require react when I use vue...
