### ISSUE TITLE
[Bug]: Storybook automigration fails to install dependencies in pnpm workspace

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#20556]
### Describe the bug

When running `pnpx storybook@next upgrade --prerelease` in a pnpm workspace project, the migrations fail when trying to install dependencies:

``` 
🔎 found a 'eslintPlugin' migration:
╭ Automigration detected ──────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                                      │
│   We've detected you are not using our eslint-plugin.                                                                                │
│                                                                                                                                      │
│   In order to have the best experience with Storybook and follow best practices, we advise you to install eslint-plugin-storybook.   │
│                                                                                                                                      │
│   More info: https://github.com/storybookjs/eslint-plugin-storybook#readme                                                           │
│                                                                                                                                      │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
✔ Do you want to run the 'eslintPlugin' migration on your project? … yes
✅ Adding dependencies: eslint-plugin-storybook
 ERR_PNPM_ADDING_TO_ROOT  Running this command will add the dependency to the workspace root, which might not be what you want - if you really meant it, make it explicit by running this command again with the -w flag (or --workspace-root). If you don't want to see this warning anymore, you may set the ignore-workspace-root-check setting to true.

 ERROR  Command failed with exit code 1: /Users/Library/pnpm/store/v3/tmp/dlx-5676/node_modules/.bin/storybook upgrade --prerelease
```

Storybook should either detect that this is a workspace and install the dependencies with the `--workspace-root` flag, or it should prompt me to install the dependency manually

**Comment by JReinhold** [comment]
My interpretation is that the issue is a bit different here. The issue is unrelated to pnpm, but rather about running the CLI from the workspace root or not.

Some projects will run `pnpx storybook@next upgrade --prerelease` in the subpackage that contains Storybook, this should work fine. Other projects will run it in the workspace root, which will cause the error above. We should handle the case of the workspace root, either by detecting it upfront or reacting to the error and re-running the command with the correct flag.

I expect this is an issue for pnpm, yarn and npm.

**Comment by ndelangen** [comment]
for pnpm here's the heuristic:
> if there's a pnpm-workspace.yaml in the CWD, then call pnpm install with the extra -w flag

Author of pnpm confirmed this should work.

**Comment by ndelangen** [comment]
for npm (TIL npm has workspaces support), the above approach for yarn, will likjely also work:

> if in the CWD/package.json there's a workspaces field, call yarn install with an extra flag -W

based on docs here: https://docs.npmjs.com/cli/v9/using-npm/workspaces?v=true

**Comment by ndelangen** [comment]
I'll implement the above heuristics in a PR, and ask @JReinhold for a review.

**Comment by shilman** [comment]
ZOMG!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.59 containing PR #21331 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```
