### ISSUE TITLE
[SB-1175] Migration: Main.js/Preview default exports

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#20554]
### Is your feature request related to a problem? Please describe

We are moving to default exports for main.js and preview.js configuration. This is friendlier for TypeScript.

Before:

```
module.exports = { stories: [...] }
//OR
export const stories = [...]
```

After:

```
export default {
  stories: [...]
}

const config = {
  addons: ['docs']
} satisfies Config;

const preview = {
  
} satisfies Preview;

export default preview;
```

### Describe the solution you'd like

Default exports are already supported in SB7, but now we need to get users upgraded:

* [ ] Add deprecation warnings for any other format
* [ ] Provide an automigration that upgrades users to default exports
  * [ ] JS users
  * [ ] TS users

### Describe alternatives you've considered

*No response*

### Are you able to assist to bring the feature to reality?

no

### Additional context

*No response*

<sub>From [SyncLinear.com](https://synclinear.com) | [SB-1175](https://linear.app/chromaui/issue/SB-1175/migration-mainjspreview-default-exports)</sub>

**Comment by yannbf** [comment]
@shilman are we expecting users to use `as` or `satisfies` in `export default`? I believe the type-safest solution would be:

```ts
const config: StorybookConfig = {
  stories: [...]
}

export default config
``` 

Also, is this for preview.js as well? I don't believe we have a type for that

**Comment by shilman** [comment]
I think what you wrote is correct. For `preview.js`, it's up for discussion. I think @kasperpeulen wanted it but maybe we can split this into two tickets & do the other one once he gets back

**Comment by yannbf** [comment]
That sounds much better. We need a proper typing system that will also address addons, parameters, globalTypes, etc

**Comment by IanVS** [comment]
Have you considered using a helper like vite's `defineConfig`?  https://vitejs.dev/config/#config-intellisense?

**Comment by shilman** [comment]
ZOMG!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.38 containing PR #20797 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
