### ISSUE TITLE
[Bug]: 7.0.0-beta.24:  addon-links TypeScript issues

### ISSUE THREAD

**Issue by DannyJoris** [storybookjs/storybook#20580]
### Describe the bug

Using Storybook addon-links v7.0.0-beta.24, I'm encountering 2 issues:

1) `LinkTo` shows the following type error: `JSX element type 'LinkTo' does not have any construct or call signatures.`

![Screenshot 2023-01-11 at 11 00 48 AM](https://user-images.githubusercontent.com/110365/211839942-46c6b79d-edb2-420f-b048-eee29f34447e.png)

2) `linkTo()` gives the following error in Storybook:
```
(0 , _storybook_addon_links_react__WEBPACK_IMPORTED_MODULE_2__.linkTo) is not a function
```
![Screenshot 2023-01-11 at 11 01 16 AM](https://user-images.githubusercontent.com/110365/211839993-95e4e199-9d41-4f17-ae48-076eb6f3c256.png)

### To Reproduce

I created the app the following way:

- Created a Next.js app with TypeScript: `npx create-next-app@latest --ts`
- Inside the app folder I ran `npx storybook@future init`
- Configured `main.js` to use `nextjs` as framework:
```
export default {
 ...
  "framework": {
    "name": "@storybook/nextjs",
    "options": {}
  }
}
```
- Ran `npx sb@next upgrade --prerelease`
- Ran csf 2 to 3 conversion: `npx sb@next migrate csf-2-to-3 --glob="**/*.stories.tsx"`
- Created a [LinkToExample.stories.tsx](https://github.com/DannyJoris/storybook-nextjs-linkto/blob/main/stories/LinkToExample.stories.tsx) story with a `LinkTo` and `linkTo()` example.
- Ran `npm run storybook`
- See: https://github.com/DannyJoris/storybook-nextjs-linkto

### System

```shell

Environment Info:

  System:
    OS: macOS 13.0.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 108.0.1
    Safari: 16.1
  npmPackages:
    @storybook/addon-essentials: ^7.0.0-beta.24 => 7.0.0-beta.24
    @storybook/addon-interactions: ^7.0.0-beta.24 => 7.0.0-beta.24
    @storybook/addon-links: ^7.0.0-beta.24 => 7.0.0-beta.24
    @storybook/nextjs: ^7.0.0-beta.24 => 7.0.0-beta.24
    @storybook/react: ^7.0.0-beta.24 => 7.0.0-beta.24
    @storybook/react-webpack5: ^7.0.0-beta.24 => 7.0.0-beta.24
    @storybook/testing-library: ^0.0.14-next.1 => 0.0.14-next.1
```

**Comment by shilman** [comment]
Olé!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.32 containing PR #20671 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```
