### ISSUE TITLE
[Bug]: Order of stories inconsistent in built Storybooks

### ISSUE THREAD

**Issue by tmeasday** [storybookjs/storybook#20626]
### Describe the bug

The order that components are listed in the sidebar differs in our sandboxes across builds. Here are the [last](https://634ff0d0ec053b270775979d-qlxfvabepu.chromatic.com/?path=/docs/example-introduction--docs) [3](https://634ff0d0ec053b270775979d-huvbyeunio.chromatic.com/?path=/docs/example-introduction--docs) [builds](https://634ff0d0ec053b270775979d-tgidebabez.chromatic.com/?path=/docs/example-introduction--docs) on next:

![image](https://user-images.githubusercontent.com/132554/212576451-1b03c1f2-ae7d-440a-b6f5-978f969172ee.png)
![image](https://user-images.githubusercontent.com/132554/212576681-77ac5ce8-4f0f-4c72-bb1d-be3938ceecd1.png)
![image](https://user-images.githubusercontent.com/132554/212576470-c37195a4-c7fd-45a5-848b-b22402bde8c3.png)

The issue comes from the `index.json` (note line numbers):
![image](https://user-images.githubusercontent.com/132554/212576567-6d6d174b-6136-4a3b-979d-6f5f09ffead6.png)
![image](https://user-images.githubusercontent.com/132554/212576573-72e51b8e-af62-4021-9422-8472384d4458.png)

### To Reproduce

```shell
Check different commits and build the storybook. I'm guessing you could probably just build a the same commit several times to see it.
```

**Comment by tmeasday** [comment]
Ok, I logged the order in the build step on CI and it is inconsistent:
 - 1. [build:](https://app.circleci.com/pipelines/github/storybookjs/storybook/39043/workflows/55d9eb7c-e015-4568-9b4e-099f24cc8495/jobs/472721) 106
 - 2. [build](https://app.circleci.com/pipelines/github/storybookjs/storybook/39043/workflows/9e385bd6-3c03-4e54-b3ab-080875aa69b8/jobs/472753): 189
 - 3. [build](https://app.circleci.com/pipelines/github/storybookjs/storybook/39043/workflows/89bd6e1a-2ee4-434d-8923-dfdf35826d3a/jobs/472746): 145
 - 4. [build](https://app.circleci.com/pipelines/github/storybookjs/storybook/39043/workflows/aa0638c6-3891-4588-b5f4-e3843398e34a/jobs/472754): 188

I was not able to reproduce this behaviour locally.

**Comment by shilman** [comment]
Ta-da!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.33 containing PR #20705 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```
