### ISSUE TITLE
[Bug]: [7.0.0-beta.27] Incorrect version of testing-library pkg

### ISSUE THREAD

**Issue by michu2k** [storybookjs/storybook#20623]
### Describe the bug

After installing the storybook, the version of `@storybook/testing-library` that appears in package.json is `0.0.13`, so when you open the "Page" component, which has interaction tests, the error below appears: 

![image](https://user-images.githubusercontent.com/22056149/212469621-c9d609c6-75e5-4f8f-b599-d81e3537fb28.png)

The correct version should be `0.0.14-next.1`, as this version added support for storybook 7. https://github.com/storybookjs/testing-library/releases/tag/v0.0.14-next.1

### To Reproduce

```shell
Run the following commands:

npx create-next-app@latest
npx sb@next init
npm run storybook

Open "Page" component
```

### System

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
  Binaries:
    Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (108.0.1462.76)
  npmPackages:
    @storybook/addon-essentials: ^7.0.0-beta.27 => 7.0.0-beta.27
    @storybook/addon-interactions: ^7.0.0-beta.27 => 7.0.0-beta.27
    @storybook/addon-links: ^7.0.0-beta.27 => 7.0.0-beta.27
    @storybook/blocks: ^7.0.0-beta.27 => 7.0.0-beta.27
    @storybook/nextjs: ^7.0.0-beta.27 => 7.0.0-beta.27
    @storybook/react: ^7.0.0-beta.27 => 7.0.0-beta.27
    @storybook/testing-library: ^0.0.13 => 0.0.13
```

**Comment by vanessayuenn** [comment]
@yannbf has this been fixed already?

**Comment by yannbf** [comment]
Hey @michu2k thanks a lot for reporting this. 
This got fixed as part of the release which just happened https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.38

Please upgrade and let us know if you face any other issues!
