### ISSUE TITLE
[Bug]: Storyshot fails with `TypeError: Cannot read properties of undefined (reading 'readdirSync')`

### ISSUE THREAD

**Issue by SimenB** [storybookjs/storybook#20624]
### Describe the bug

See https://www.runpkg.com/?@storybook/addon-storyshots@7.0.0-beta.28/dist/frameworks/frameworkLoader.js#4 and https://www.runpkg.com/?@storybook/addon-storyshots@7.0.0-beta.28/dist/frameworks/frameworkLoader.js#9. `fs` is plain `require`d, but then tried to access via `.default` without the interop code. Something in the transpilation is off.

### To Reproduce

```shell
See above
```

### System

```shell
System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 16.19.0 - /private/var/folders/v4/wwfy9s191x577dcxnlkx5vsc0000gn/T/xfs-93f4dd4c/node
    Yarn: 3.3.1 - /private/var/folders/v4/wwfy9s191x577dcxnlkx5vsc0000gn/T/xfs-93f4dd4c/yarn
    npm: 9.2.0 - ~/.nvm/versions/node/v16.19.0/bin/npm
  Browsers:
    Chrome: 109.0.5414.87
    Firefox: 108.0.1
    Safari: 16.2
```

**Comment by valentinpalkovic** [comment]
@ndelangen This Has something to do with how the `prepare/tsc.ts` script works, I think we have to add `esModuleInterop: true` to the `createProgram` options. Then the error is gone.

I have exactly the same issue.

**Comment by shilman** [comment]
Yowza!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.29 containing PR #20630 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
