### ISSUE TITLE
[Bug]: storybook 7 beta .28 with Vite - MDX stories not containing a Story are not diplayed

### ISSUE THREAD

**Issue by alexis-dorosz** [storybookjs/storybook#20645]
### Describe the bug

Using Vite, for MDX stories which do not explicitly use the Story block, the following error occurs :

`Uncaught (in promise) Error: Unexpected missing story *--page from referenced CSF file.`

This is a problem for welcome pages, guidelines documentations or if using only the ColorPalette or Typeset blocks

### To Reproduce

```shell
This can be reproduced easily by creating a mdx story without using the Story block.

You can also reproduce it by creating a fresh create-vite project, use storybook init and upgrade to beta to get the default storybook welcome mdx storie and see that it is not displayed
```

### System

```shell
System:
    OS: macOS 13.0
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Chrome: 109.0.5414.87
    Firefox: 108.0.2
    Safari: 16.1
  npmPackages:
    @storybook/addon-essentials: ^7.0.0-beta.26 => 7.0.0-beta.26 
    @storybook/addon-interactions: ^7.0.0-beta.26 => 7.0.0-beta.26 
    @storybook/addon-links: ^7.0.0-beta.26 => 7.0.0-beta.26 
    @storybook/react: ^7.0.0-beta.26 => 7.0.0-beta.26 
    @storybook/react-vite: ^7.0.0-beta.26 => 7.0.0-beta.26 
    @storybook/testing-library: ^0.0.14-next.1 => 0.0.14-next.1 
    @storybook/theming: ^7.0.0-beta.26 => 7.0.0-beta.26
```

### Additional context

System was captured as I rolled back to beta.26 but the problem still occurs there, I noticed the issue when I was using .28 so this bug is still present

**Comment by StuDownie** [comment]
Ran into this issue as well. Renaming files from `About.stories.mdx` -> `About.mdx` for simple docs pages. 

Additionally, importing stories and adding `of={MyStories}`  to the Meta tag as explained here might help:

https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#standalone-docs-files
