### ISSUE TITLE
 [Feature Request]: Rationalize index generation errors

### ISSUE THREAD

**Issue by tmeasday** [storybookjs/storybook#20663]
### Scenarios

There are various times you could run into indexing problems:

- When starting dev mode
- When HMR-ing in dev mode
- When building
- When smoke testing dev mode.

In all cases, there are several distinct types of errors:

- Syntax errors
- Invalid CSF errors (e.g. no default export)
- Duplicate errors (same story twice).

### Desired Behaviour

1. All errors should lead to the same behaviour
2. All errors should be collected into a useful message (if there are >1 files/stories with problems)
3. In dev mode (startup and HMR) it should:
    1. Log to the console
    2. Cause the `/index.json` route to `5xx` and serve a useful error
    3. Cause the preview to redbox that error
    4. Cause the sidebar to show an error UI
    5. Resolve itself automatically (no user input) when the file is fixed and saved.
4. In build mode (building and smoke testing) it should error and stop the build process, and print all the errors to the console.

https://github.com/storybookjs/storybook/issues/20663#tasklist-block-007b2015-3f5c-4bd3-88ea-4e4da773e37f

**Comment by shilman** [comment]
Ooh-la-la!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.52 containing PR #21112 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```
