### ISSUE TITLE
[Feature Request]: Change name on panel for Storysource

### ISSUE THREAD

**Issue by derekreilly1990** [storybookjs/storybook#20672]
### Is your feature request related to a problem? Please describe

We are using the Storysource addon to display examples of our component variations, But we feel that the title on the panel "Story" doesnt describe its Content.

### Describe the solution you'd like

 it would be nice to override the panel name if this is possible, or at least give it a reasonably descriptive name "Source" or "Code" for example

### Are you able to assist to bring the feature to reality?

yes, I can

**Comment by shilman** [comment]
I'm fine with updating the string in the addon. Adding another configuration option is probably overkill. Mind opening a PR for this to start the discussion? Many thanks! 🙏 

Please check out [how to contribute](https://storybook.js.org/docs/react/contribute/how-to-contribute) in our docs and feel free to ask questions in `#contributing` in [our Discord](https://discord.gg/storybook).

**Comment by derekreilly1990** [comment]
Yes i can work on a PR

**Comment by mayank99** [comment]
in the meantime, i've been using this code in `manager.js`:
```js
import { addons } from '@storybook/addons';

setTimeout(() => {
  const storySourceId = 'storybook/source-loader/panel';
  const storyTab = addons.getElements('panel')?.[storySourceId];
  if (storyTab) {
    storyTab.title = 'Code';
  }
});
```

**Comment by shilman** [comment]
Ta-da!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.50 containing PR #21132 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```
