### ISSUE TITLE
[Bug]: sb7+vite env variables not working inside addons

### ISSUE THREAD

**Issue by Luk-z** [storybookjs/storybook#20675]
### Describe the bug

Environment variables are not available inside addon.

This is a repo to reproduce the error: node16 + sb7 + vite + npm
https://github.com/Luk-z/vite_ts_sb7_npm

This is a repo where the env variables works inside addons: node14 + sb6 + vite + npm
https://github.com/Luk-z/vite_ts_sb6_npm

To write the simple addon i followed https://storybook.js.org/docs/react/addons/writing-addons.

I'm expecting env variables are available inside an addon.

### To Reproduce

```shell
https://github.com/Luk-z/vite_ts_sb7_npm
```

### System

```shell
$ npx sb@next info

Environment Info:

  System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 106.0.1
    Safari: 16.0
  npmPackages:
    @storybook/addon-essentials: ^7.0.0-beta.30 => 7.0.0-beta.30 
    @storybook/addon-interactions: ^7.0.0-beta.30 => 7.0.0-beta.30 
    @storybook/addon-links: ^7.0.0-beta.30 => 7.0.0-beta.30 
    @storybook/blocks: ^7.0.0-beta.30 => 7.0.0-beta.30 
    @storybook/react: ^7.0.0-beta.30 => 7.0.0-beta.30 
    @storybook/react-vite: ^7.0.0-beta.30 => 7.0.0-beta.30 
    @storybook/testing-library: ^0.0.13 => 0.0.13
```

**Comment by IanVS** [comment]
Where are you setting the `STORYBOOK_TEST` env var?

**Comment by Luk-z** [comment]
`.env` file https://github.com/Luk-z/vite_ts_sb7_npm/blob/main/.env

**Comment by IanVS** [comment]
I think this isn't related to Vite, since it's an addon and being rendered in the manager.  @ndelangen is this maybe a consequence of changing the manager over from Webpack to esbuild?  I see that `process.env` is an empty object even when prepending to the storybook command (`STORYBOOK_TEST=abcd storybook dev -p 6006`), so it doesn't seem related to loading the `.env` file.

**Comment by ndelangen** [comment]
Right.. so the builder-manager needs to be modified to setup injecting environment variables into addons-bundles.

Likely to be implemented here:
https://github.com/storybookjs/storybook/blob/e7c74620ff73afa7a25d54dd1def535f8b50bf2d/code/lib/builder-manager/src/index.ts#L77-L83

**Comment by IanVS** [comment]
Not released yet

**Comment by ndelangen** [comment]
@IanVS @vanessayuenn @shilman we're using the auto close feature nowadays, correct?

**Comment by shilman** [comment]
Yes. @IanVS We're experimenting with using GH's PR-issue linkage feature so that our workflow is more standard

**Comment by shilman** [comment]
Crikey!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.39 containing PR #20834 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```

**Comment by Luk-z** [comment]
It works, thx!
