### ISSUE TITLE
[Bug]: Decorators in Svelte causes dispatched events to not be logged in Actions

### ISSUE THREAD

**Issue by JReinhold** [storybookjs/storybook#20690]
### Describe the bug

Usually, any globally dispatched events in a Svelte component automatically gets inferred and attached to actions.

This works fine for basic components, but as soon as a decorator is decorating a story, it stops attaching any events to actions. Even when manually specifying the argType it still doesn't get logged in the actions panel.

### To Reproduce

```shell
The default stories from a fresh Svelte project works fine.

Adding a decorator breaks it:


export const Secondary = {
  args: {
    label: 'Button',
  },
  argTypes: {
    // onClick: { action: 'clicked' }, // manually doing it should also work in theory
  },
  decorators: [() => BorderDecoratorRed ]
};
```

### Additional context

This is likely a regression introduced in https://github.com/storybookjs/storybook/pull/19987

**Comment by Anthony-Jhoiro** [comment]
This is really a pain. Has anyone found a workaround for this issue?

**Comment by heneke** [comment]
@Anthony-Jhoiro 

No, it's a bug introduced in 5b2b0b4. EventListeners are only attached when svelteVersion is < 5 here: https://github.com/storybookjs/storybook/blob/next/code/renderers/svelte/src/components/SlotDecorator.svelte#L13

svelteVersion is undefined in https://github.com/storybookjs/storybook/blob/next/code/renderers/svelte/src/decorators.ts#L62, so no events are forwarded when using decorators.

**Comment by JReinhold** [comment]
@heneke are you sure about that? This issue predates that commit by a year.

**Comment by heneke** [comment]
@JReinhold I lost track of the open tabs with issues when answering.

But: Decorators do not work with storybook-svelte 8.1.6 because of the commit mentioned and the missing version in the snippet posted by @Anthony-Jhoiro.

**Comment by JReinhold** [comment]
@Anthony-Jhoiro, @heneke, PR https://github.com/storybookjs/storybook/pull/28247 is an attempt at fixing this issue. It would be great if you could try out the PR's canary release and see if it fixes it for you, and/or causes other related problems. See the bottom of the PR description for how to (temporarily) "upgrade" your project to that specific canary version.

**Comment by heneke** [comment]
@JReinhold I confirm that my decorators work again with the canary release. There seem to be no other issues. I cannot say anything regarding docs (not used in my project)
