### ISSUE TITLE
[Bug]: => Failed to build the preview ERR! main.e403f26d.iframe.bundle.js from Terser plugin ERR! Unexpected token: punc 

### ISSUE THREAD

**Issue by IbanezDenis28** [storybookjs/storybook#20716]
### Describe the bug

I had angular 13, but after updating to 14, I try to build the storybook and I get this error:

![image](https://user-images.githubusercontent.com/109361616/213788297-a1441b84-add4-45c2-b52c-6d227eda1cf5.png)

[Bug]: => Failed to build the preview ERR! main.e403f26d.iframe.bundle.js from Terser plugin ERR! Unexpected token: punc 

npm run storybook works fine, but build not.

### To Reproduce

```shell
const path = require('path');

module.exports = {
  "stories": [
    "../stories/**/*.stories.mdx",
    "../stories/**/*.stories.@(js|jsx|ts|tsx)",
    // added the below
    '../projects/**/*.stories.mdx',
    '../projects/**/*.stories.@(js|jsx|ts|tsx)',
  ],
  "addons": [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/addon-interactions",
    "storybook-addon-angular-router",
    "@storybook/preset-scss",
  ],
  "framework": "@storybook/angular",
  "core": {
    "builder": "@storybook/builder-webpack5"
  },
  "angularOptions": {
    "enableIvy": false,
  },
}


"@storybook/addons": "^6.5.9",
    "@storybook/preset-scss": "^1.0.3",
"storybook-addon-angular-router": "^1.5.0",
    "@storybook/theming": "^6.5.9",
    "@compodoc/compodoc": "^1.1.19",
    "@storybook/addon-actions": "^6.5.9",
    "@storybook/addon-essentials": "^6.5.9",
    "@storybook/addon-interactions": "^6.5.9",
    "@storybook/addon-links": "^6.5.9",
    "@storybook/angular": "^6.5.9",
    "@storybook/builder-webpack5": "^6.5.9",
    "@storybook/manager-webpack5": "^6.5.9",
    "@storybook/testing-library": "0.0.13",
```

### System

```shell
windows 11
```

**Comment by shilman** [comment]
Please try upgrading to the latest prerelease. Does that fix it?

Migration guide: https://storybook.js.org/migration-guides/7.0

**Comment by user-srzs** [comment]
I had the same problem. How did you solve it

**Comment by melloware** [comment]
+1

**Comment by vipulrawat** [comment]
I am currently disabling the terser plugin as a workaround. This seems like a bug on storybook's webpack config.

**Comment by melloware** [comment]
Can you post how you are disabling it?

**Comment by vipulrawat** [comment]
You can use the `webpackFinal`  in the config to set `config.optimization.minimize = false`. It should look something like this:

```js
webpackFinal: async (config)  => {
  config.optimization.minimize = false
  return config
}
```

**Comment by melloware** [comment]
Works like a charm.  You rock!

**Comment by jaspk06** [comment]
try updating your version of webpack. I was on storybook 7.1.1 with webpack 5.70.0 and was having this error. Updating to the latest 5.88.2 fixed it

**Comment by melloware** [comment]
@jaspk06 fixed my issue you totally rule!

**Comment by klaygomes** [comment]
Same issue here. If someone is planning to investigate the problem, I think this dump can help:

https://gist.github.com/klaygomes/3cd87d87f1c313a6da48922ea3c618d4

**Comment by klaygomes** [comment]
The bug persists. I'm still having to use `config.optimization.minimize = false` as a fix.
