### ISSUE TITLE
Remove warnings generated by deprecated `state` fields

### ISSUE THREAD

**Issue by tmeasday** [storybookjs/storybook#20728]
### Describe the bug

```
state.storiesHash is deprecated, please use state.index
state.storiesConfigured is deprecated, please use state.previewInitialized
state.storiesFailed is deprecated, please use state.indexError
```

Warnings are created on [this line](https://github.com/storybookjs/storybook/blob/e0228420db831fddb42d1eb6cd157db62fe0d3c1/code/lib/manager-api/src/index.tsx#L210) when we compose the `stories` module's state into the total state.

**Comment by shilman** [comment]
Great Caesar's ghost!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.61 containing PR #21367 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```
