### ISSUE TITLE
Remove React 18 warning in docs

### ISSUE THREAD

**Issue by tmeasday** [storybookjs/storybook#20729]
### Describe the bug

The following warning is created by [rendering in the React 17 style](https://github.com/storybookjs/storybook/blob/e0228420db831fddb42d1eb6cd157db62fe0d3c1/code/addons/docs/src/DocsRenderer.tsx#L34-L40) when the project has React 18:

```
Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot
```

**Comment by tmeasday** [comment]
- Create a package `@storybook/react-dom-shim` with two entry points
  - the first one uses `react-dom@17`'s code path
  - the second uses `react-dom@18`'s.
- In `@storybook/react` and `@storybook/addon-docs` depend on the above, import the former and use in the place of `react-dom`.
- Additionally, add an alias in both packages (or perhaps a preset dependency on the shim package which adds an alias), which does something along the lines of:

```js
import { readJSON } from 'fs-extra';

export const webpackFinal: StorybookConfig['webpackFinal'] = async (config) => {
  const reactDomPkg = await readJSON(require.resolve('react-dom/package.json'));
  const isReact18 = reactDomPkg?.version?.startsWith('18') || reactDomPkg?.version?.startsWith('0.0.0');

  if (!isReact18) return config;

  return {
    ...config,
    resolve: {
       ...config.resolve,
       alias: {
         '@storybook/react-dom-shim': '@storybook/react-dom-shim/react-18'
       }
    }
  };
};
```

And similar for Vite.

**Comment by shilman** [comment]
Zoinks!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.54 containing PR #21197 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```
