### ISSUE TITLE
[Bug]: Error installing storybook in monorepo

### ISSUE THREAD

**Issue by osvaldokalvaitir** [storybookjs/storybook#20726]
### Describe the bug

Error installing storybook in monorepo

Node - v18.13.0

NPM - 9.3.1

When running the command:

`npx storybook init`

or

`npx storybook init --builder @storybook/builder-vite --type react --use-npm`

this error occurs:

![errro](https://user-images.githubusercontent.com/40433049/213933580-82585a99-4438-46d2-87f1-3424f1650a21.png)

**Comment by cngJo** [comment]
Same issues with node `v19.3.0`. I tried to install storybook with vuejs 3 in a separate repository to import components from different other packages in the same workspace.

Tested with the latest storybook 6.5 as well as 7.0.0-beta.31.

**Comment by osvaldokalvaitir** [comment]
I was able to perform the process on Node v16.15.0

**Comment by cngJo** [comment]
What have you done to get this working?

I have the following NPM workspace setup for my monorepo:
```
. 
./assets/apps/mc-storybook
./asstes/apps/mc-web
./assets/packages/component-library
./assets/packages/other-lib
```

where both `assets/packages/*` and `assets/apps/*` are defined as workspaces:
```json
"workspaces": [
  "assets/packages/*",
  "assets/apps/*"
]
```

I've then create a new vuejs3 app in the `./assets/apps/storybook` directory and ran `npx storybook init --builder @storybook/builder-vite --type vue3 --use-npm` which crashed with the error you originally posted.

Looking at the debug logs, this seems to be related to storybook calling the [`command:config`](https://docs.npmjs.com/cli/v9/commands/npm-config) command which is not supported by workspace:

Quote form the docs:
> Note: This command is unaware of workspaces.


Are you doing sth. different than what I've described?

---
<details>
    <summary>Complete npm log file (with a censored path)</summary>
<pre>
0 verbose cli /usr/local/Cellar/node/19.3.0/bin/node /usr/local/bin/npm
1 info using npm@9.3.1
2 info using node@v19.3.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 1ms
9 info found workspace root at /Users/johannes/Programming/organisation/SaaS/project/project
10 timing config:load:file:/Users/johannes/Programming/organisation/SaaS/project/project/.npmrc Completed in 0ms
11 timing config:load:project Completed in 10ms
12 timing config:load:file:/Users/johannes/.npmrc Completed in 1ms
13 timing config:load:user Completed in 1ms
14 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
15 timing config:load:global Completed in 0ms
16 timing config:load:setEnvs Completed in 1ms
17 timing config:load Completed in 18ms
18 timing npm:load:configload Completed in 18ms
19 timing npm:load:mkdirpcache Completed in 0ms
20 timing npm:load:mkdirplogs Completed in 0ms
21 verbose title npm config get legacy-peer-deps
22 verbose argv "config" "get" "legacy-peer-deps" "--location" "project"
23 timing npm:load:setTitle Completed in 2ms
24 timing config:load:flatten Completed in 2ms
25 timing npm:load:display Completed in 4ms
26 verbose logfile logs-max:10 dir:/Users/johannes/.npm/_logs/2023-01-23T19_51_39_486Z-
27 verbose logfile /Users/johannes/.npm/_logs/2023-01-23T19_51_39_486Z-debug-0.log
28 timing npm:load:logFile Completed in 13ms
29 timing npm:load:timers Completed in 0ms
30 timing npm:load:configScope Completed in 0ms
31 timing npm:load Completed in 38ms
32 timing command:config Completed in 2ms
33 verbose stack Error: This command does not support workspaces.
33 verbose stack     at Config.cmdExec (/usr/local/lib/node_modules/npm/lib/base-command.js:123:29)
33 verbose stack     at Npm.exec (/usr/local/lib/node_modules/npm/lib/npm.js:154:20)
33 verbose stack     at async module.exports (/usr/local/lib/node_modules/npm/lib/cli.js:134:5)
34 verbose cwd /Users/johannes/Programming/organisation/SaaS/project/project/assets/apps/mc-storybook
35 verbose Darwin 22.2.0
36 verbose node v19.3.0
37 verbose npm  v9.3.1
38 error code ENOWORKSPACES
39 error This command does not support workspaces.
40 verbose exit 1
41 timing npm Completed in 50ms
42 verbose code 1
43 error A complete log of this run can be found in:
43 error     /Users/johannes/.npm/_logs/2023-01-23T19_51_39_486Z-debug-0.log
</pre>
</details>

**Comment by osvaldokalvaitir** [comment]
> What have you done to get this working?
> 
> I have the following NPM workspace setup for my monorepo:
> 
> ```
> . 
> ./assets/apps/mc-storybook
> ./asstes/apps/mc-web
> ./assets/packages/component-library
> ./assets/packages/other-lib
> ```
> 
> where both `assets/packages/*` and `assets/apps/*` are defined as workspaces:
> 
> ```json
> "workspaces": [
>   "assets/packages/*",
>   "assets/apps/*"
> ]
> ```
> 
> I've then create a new vuejs3 app in the `./assets/apps/storybook` directory and ran `npx storybook init --builder @storybook/builder-vite --type vue3 --use-npm` which crashed with the error you originally posted.
> 
> Looking at the debug logs, this seems to be related to storybook calling the [`command:config`](https://docs.npmjs.com/cli/v9/commands/npm-config) command which is not supported by workspace:
> 
> Quote form the docs:
> 
> > Note: This command is unaware of workspaces.
> 
> Are you doing sth. different than what I've described?
> 
> Complete npm log file (with a censored path)

I only changed the version of Node.js

My package.json:

```
{
  "private": true,
  "workspaces": [
    "packages/*"
  ]
}
```

**Comment by motograter** [comment]
I can normal install this lib, always when i want use sb i must fixed 10 errors

wtf?

same error.... 
i think is npm version

**Comment by danleyden** [comment]
Hit this issue also with Node v19.6.0

It worked correctly after downgrading to Node v16.19.0

**Comment by sgpicone** [comment]
Also hit this issue, with Node v19.6.0, 19.5.0, 18.14.0

Downgrading to Node v16.19.0 resolved the problem but is definitely not ideal

**Comment by clearly-outsane** [comment]
```Error: npm ERR! code ENOWORKSPACES
npm ERR! This command does not support workspaces.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Local\npm-cache\_logs\2023-02-24T14_41_14_696Z-debug-0.log```

Same. With npm v18

**Comment by AFusco** [comment]
getting the same error, following the turborepo guide at https://turbo.build/repo/docs/handbook/tools/storybook

**Comment by idoialongan** [comment]
`An error occurred while installing dependencies.
npm ERR! code ENOWORKSPACES
npm ERR! This command does not support workspaces.`

Same error with Node v18.14.2 and npm 9.6.0

**Comment by joepetrillo** [comment]
I am getting the same error while using turborepo with npm and nextjs.

node 18.15.0
npm 9.6.1
turborepo 1.8.3
nextjs 13.2.4

**Comment by RodrigoNovais** [comment]
Having the same issue
I see it was tagged with "has workaround", I hope the workaround is not "use a no longer manteined version of node" cause I don't see any

**Comment by dolgachio** [comment]
I also faced this issue with Turborepo and React. So, it remains. 
I want to contribute to fixing it if contributors think it makes sense. 

```
node v18.19.0
npm v10.2.3
turbo v1.11.3
```

**Comment by aewshyae** [comment]
FYI same error in nextjs. 
https://github.com/vercel/next.js/issues/47121#issuecomment-1499044345

I hope it may help

**Comment by valentinpalkovic** [comment]
Can someone provide a minimal reproduction? https://storybook.new

**Comment by dolgachio** [comment]
@valentinpalkovic thank you for your response, so to reproduce it, do you need some examples on StackBlitz or some similar platform?

**Comment by valentinpalkovic** [comment]
You can also just provide a GitHub Repo with the minimal reproduction.

**Comment by osvaldokalvaitir** [comment]
not yet resolved

**Comment by valentinpalkovic** [comment]
Reproduction:

1. git clone https://github.com/kinetics-dev/kinetics.git
2. cd ./packages/kinetics-core
3. npx storybook@latest init

Error message:

```
Error: Command failed with exit code 1: npm config get registry
npm error code ENOWORKSPACES
npm error This command does not support workspaces.

npm error A complete log of this run can be found in: /-/.npm/_logs/2024-07-15T12_18_11_132Z-debug-0.log
    at makeError (/-/.npm/_npx/842836d16bfc19ab/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/-/.npm/_npx/842836d16bfc19ab/node_modules/execa/index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Yarn2Proxy.executeCommand (/-/.npm/_npx/842836d16bfc19ab/node_modules/@storybook/core-common/dist/index.js:1667:11)
    at async Yarn2Proxy.getRegistryURL (/-/.npm/_npx/842836d16bfc19ab/node_modules/@storybook/core-common/dist/index.js:1376:7)
    at async resolveUsingBranchInstall (/-/.npm/_npx/842836d16bfc19ab/node_modules/@storybook/cli/dist/generate.js:2066:17)
    at async getRendererDir (/-/.npm/_npx/842836d16bfc19ab/node_modules/@storybook/cli/dist/generate.js:2094:12)
    at async templatePath (/-/.npm/_npx/842836d16bfc19ab/node_modules/@storybook/cli/dist/generate.js:2185:21)
    at async copyTemplateFiles (/-/.npm/_npx/842836d16bfc19ab/node_modules/@storybook/cli/dist/generate.js:2228:40)
    at async baseGenerator (/-/.npm/_npx/842836d16bfc19ab/node_modules/@storybook/cli/dist/generate.js:2995:5)
    at installStorybook (/-/.npm/_npx/842836d16bfc19ab/node_modules/@storybook/cli/dist/generate.js:3856:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async installStorybook (/-/.npm/_npx/842836d16bfc19ab/node_modules/@storybook/cli/dist/generate.js:3849:14)
    at async doInitiate (/-/.npm/_npx/842836d16bfc19ab/node_modules/@storybook/cli/dist/generate.js:3993:23)
    at async withTelemetry (/-/.npm/_npx/842836d16bfc19ab/node_modules/@storybook/core-server/dist/index.js:40:3599)
    at async initiate (/-/.npm/_npx/842836d16bfc19ab/node_modules/@storybook/cli/dist/generate.js:4078:24)
```

**Comment by valentinpalkovic** [comment]
Removing the `has workaround` label since it isn't an option nowadays anymore to downgrade to Node.js 16
