### ISSUE TITLE
[Bug]: storybook init with web-component Type 'null' is not assignable to type 'string'

### ISSUE THREAD

**Issue by ta1m1kam** [storybookjs/storybook#20720]
### Describe the bug

I get typescript type errors in web-components projects like using lit.
In tsconfig.json, strict mode is true.
This is because the backgroundColor in the Button template in web-components does not allow the default argument null.

### To Reproduce

- Run `npx storybook init` in web-components project.
- Capture
<img width="458" alt="スクリーンショット 2023-01-22 1 45 54" src="https://user-images.githubusercontent.com/25325947/213877493-fa53489e-3f72-4b23-9771-941a78df9d23.png">

### System

```shell
❯ npx sb@next info

Environment Info:

  System:
    OS: macOS 12.5.1
    CPU: (8) arm64 Apple M1 Pro
  Binaries:
    Node: 18.10.0 - ~/.nvm/versions/node/v18.10.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.10.0/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.10.0/bin/npm
  Browsers:
    Chrome: 109.0.5414.87
    Firefox: 105.0.3
    Safari: 15.6.1
  npmPackages:
    @storybook/addon-actions: ^6.5.15 => 6.5.15 
    @storybook/addon-essentials: ^6.5.15 => 6.5.15 
    @storybook/addon-links: ^6.5.15 => 6.5.15 
    @storybook/builder-webpack5: ^6.5.15 => 6.5.15 
    @storybook/manager-webpack5: ^6.5.15 => 6.5.15 
    @storybook/web-components: ^6.5.15 => 6.5.15
```
```

**Comment by shilman** [comment]
Does it work if you upgrade to the latest prerelease?

Migration guide: https://storybook.js.org/migration-guides/7.0

**Comment by ta1m1kam** [comment]
This is an type error about webcomponent cli template, I think it doesn't affect upgrade.

**Comment by shilman** [comment]
Crikey!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.34 containing PR #20722 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
