### ISSUE TITLE
Migration to rename `.stories.mdx` files to `.mdx`

### ISSUE THREAD

**Issue by tmeasday** [storybookjs/storybook#20733]
An (opt-in) migration to rename `.stories.mdx` files to `.mdx` files *if* we think they will work as "MDX" docs files.

1. Check the file doesn't do anything that requires `.stories.mdx` (basically doesn't declare any stories via `<Story name={} />` or `<Story story={} />`.

2. If not, rename from `.stories.mdx` to `.mdx`.

We should probably check if the stories glob matches `.mdx`, and bail out if it does not (we already adjusted the default glob to match them: https://github.com/storybookjs/storybook/pull/19795)

**Comment by JReinhold** [comment]
Related to https://github.com/storybookjs/storybook/issues/19497, that handles the opposite case where there _are_ story declarations.

**Comment by kasperpeulen** [comment]
I think I fix this in this PR:
https://github.com/storybookjs/storybook/pull/21073

I think it will handle both cases.

**Comment by shilman** [comment]
Whoopee!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.53 containing PR #21073 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
