### ISSUE TITLE
Remove emotion `first-child` warnings in docs

### ISSUE THREAD

**Issue by tmeasday** [storybookjs/storybook#20730]
### Describe the bug

```
The pseudo class ":first-child" is potentially unsafe when doing server-side rendering. Try changing it to ":first-of-type".
```

**Comment by ndelangen** [comment]
I believe this has been fixed..?

**Comment by tmeasday** [comment]
I don't think so @ndelangen:

<img width="481" alt="image" src="https://user-images.githubusercontent.com/132554/217126743-0016983e-74f6-4dec-aa43-fafbbbbab3eb.png">

From https://635781f3500dd2c49e189caf-eldrpdmwma.chromatic.com/?path=/docs/storybook-blocks-examples-button--docs (latest build on `next`).

**Comment by tmeasday** [comment]
@ndelangen so what I think has happened here:

1. Originally there was [an issue](https://github.com/storybookjs/storybook/issues/18103) (in the manager) where our prior use of a special code comment to disable the warning wasn't working.
2. [The workaround for that](https://github.com/storybookjs/storybook/pull/18361) was to use a special emotion cache that just didn't send the warning, and removed the need for the special code comments, so we removed them.
3. Then later, [in one PR](https://github.com/storybookjs/storybook/pull/18657), @Andarist did the same process as 2. for docs. However, he didn't merge it, as in the meantime:
4. He fixed the root problem in Emotion, and made a [PR to update the version](https://github.com/storybookjs/storybook/pull/18992), and suggested reverting step 2.
5. However, that did't get merged because [Emotion got updated separately](https://github.com/storybookjs/storybook/pull/19029).

OK, phew! But in all that, we never reverted step 2. And we never either added the cache or added the code comments to docs.

So I believe the right steps forward here are:
1. Revert step 2 (PR #18361)
2. Add special code comments (`ignoreSsrWarning`) to whichever docs components are triggering the warnings.

**Comment by Andarist** [comment]
Both the "what happened" and "what can be done" look OK to me. Let me know if I can assist you anyhow - if the problem won't go away I'm happy to take another look at this.

**Comment by tmeasday** [comment]
Thanks @Andarist - I'm hoping this should pretty mechanical now I know what's going on! :)

**Comment by shilman** [comment]
Whoopee!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.1.0-alpha.0 containing PR #21213 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```
