### ISSUE TITLE
Remove React warning when unmounting a docs page

### ISSUE THREAD

**Issue by tmeasday** [storybookjs/storybook#20731]
### Describe the bug

```
Warning: Attempted to synchronously unmount a root while React was already rendering. React cannot finish unmounting the root until the current render has completed, which may lead to a race condition.
```

**Comment by aryatalathi** [comment]
Can I work on this issue? Waiting for a reply. Thank you.

**Comment by ndelangen** [comment]
@aryatalathi yes please, that'd be great!

I can assist, if needed.

**Comment by tmeasday** [comment]
Reading [this issue](https://github.com/facebook/react/issues/25675):

> In short: Triggers a warning if you unmount a root in a ref callback. Also getting the warning of the state update is caused by a non-discrete event.

> So seems intended that you use setTimeout instead? Though it is confusing to me that ref callbacks are considered "during rendering".

I think this the line where we do that:

https://github.com/storybookjs/storybook/blob/bbc8f9b293bacae4d823fded3268c00635d3b6a8/code/ui/blocks/src/components/Story.tsx#L50

So maybe we should just wrap it in a `setTimeout(...,0)`? I tried that and the warning went away.

If that's the right approach, then I would want to be sure that we don't accidentally break the teardown/cleanup mechanism, which was added in: https://github.com/storybookjs/storybook/pull/18457

**Comment by tmeasday** [comment]
@aryatalathi - I ended up doing this: https://github.com/storybookjs/storybook/pull/21214

**Comment by shilman** [comment]
Hurrah!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.58 containing PR #21214 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```
