### ISSUE TITLE
[Bug]: Image src broken with `[object Object]` from mdx files when using Next.js + Storybook

### ISSUE THREAD

**Issue by rkrishnasanka** [storybookjs/storybook#20756]
### Describe the bug

The intro page images are broken when I set up Storybook on Tailwind + Next.js + Typescript application.

I've also tried using the 7.0 beta, which remains broken. Here's the [Github](https://github.com/rkrishnasanka/nextjs-template) (it's just the template). The instructions on how to setup the app are given here (https://github.com/rkrishnasanka/nextjs-template#temaplate-setup-instructions)

Here's an image showing how its broken with the dev tools open on the side:
<img width="1409" alt="Screen Shot 2023-01-23 at 4 54 12 PM" src="https://user-images.githubusercontent.com/855696/214159457-c019055b-2d95-40f7-a786-ac8adb8b6a91.png">

### To Reproduce

Here are all the detailed steps to setup the template (also found [here](https://github.com/rkrishnasanka/nextjs-template#temaplate-setup-instructions):
```shell



npx create-next-app@latest --typescript --eslint react-experiment
cd react-experiment
npm install -D tailwindcss postcss autoprefixer
npx tailwindcss init -p


Update `tailwind.config.js` to include the following:

```js
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
​
    // Or if using `src` directory:
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
``` 

Update `src/app/globals.css` to include the following:

```css
@tailwind base;
@tailwind components;
@tailwind utilities;
```

Setup Index 

```tsx
export default function Home() {
  return (
    <h1 className="text-3xl font-bold underline">
      Hello world!
    </h1>
  )
}
```

It'll look weird, if the default css is still there

```bash
npx sb init --builder webpack5
npm install --save-dev storybook-addon-next

```

update `.storybook/main.js` to include the following:
```
module.exports = {
  "stories": [
    "../src/**/*.stories.mdx",
    "../src/**/*.stories.@(js|jsx|ts|tsx)"
  ],
  "addons": [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/addon-interactions",
    "storybook-addon-next"
  ],
  "framework": "@storybook/react",
  "core": {
    "builder": "@storybook/builder-webpack5"
  }
}
```
### Environment Info:
```


  System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (4) x64 DO-Premium-Intel
  Binaries:
    Node: 18.12.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
  npmPackages:
    @storybook/addon-actions: ^7.0.0-beta.31 => 7.0.0-beta.31 
    @storybook/addon-essentials: ^7.0.0-beta.31 => 7.0.0-beta.31 
    @storybook/addon-interactions: ^7.0.0-beta.31 => 7.0.0-beta.31 
    @storybook/addon-links: ^7.0.0-beta.31 => 7.0.0-beta.31 
    @storybook/nextjs: ^7.0.0-alpha.41 => 7.0.0-beta.31 
    @storybook/react: ^7.0.0-beta.31 => 7.0.0-beta.31 
    @storybook/testing-library: ^0.0.14-next.1 => 0.0.14-next.1
```

**Comment by valentinpalkovic** [comment]
Hey @rkrishnasanka,

If you want to use `storybook-addon-next`, you should consider to open a Github Issue here: https://github.com/RyanClementsHax/storybook-addon-next

But you could also just use the [Next.Js Storybook framework](https://storybook.js.org/blog/integrate-nextjs-and-storybook-automatically/) instead.

1. Remove `storybook-addon-next` from your package.json and `main.js` addons section.
2. Change the `framework` field in main.js to `@storybook/nextjs` and remove the `core` option.

Then you should be good to go. If you need some additional information about Next.js and Storybook, please take a look at https://github.com/storybookjs/storybook/tree/next/code/frameworks/nextjs

**Comment by rkrishnasanka** [comment]
So should I be using sb 6 or 7 ? When I use this plugin ? I'll do a fresh rewrite to test this out.

**Comment by valentinpalkovic** [comment]
I am unsure about the `storybook-addon-next` plugin, but you can use the native Next.js support starting from SB 7.0.0-beta.29

**Comment by valentinpalkovic** [comment]
And you still have issues?

**Comment by rkrishnasanka** [comment]
@valentinpalkovic Yup, the intro page images are still broken with this. I'm gonna ask on discord to see if people can replicate my steps and see if it's still broken. But it seems like the image src, when defined in `mdx` is still broken. However, I'm unsure whether the `.mdx` file here is mdx 1 or mdx 2. I'm gonna check with a simple image element in a couple of hours and let you know. Its the `Introduction.stories.mdx` file that was generated by default that is not rendering at the moment. 

I'll keep you posted.

**Comment by rkrishnasanka** [comment]
@valentinpalkovic okay then, I created a small test component with an image in it, and it seems like the issue is with direct imports for image tags. I could resolve this by using the `next/image`.

I think the issue will be that as soon as we set next.js as the framework, all the `<img>` tags will break on next.js and hence the introduction mdx also failed because its probably compiled it to `<img>` tags. 

So this is now a `mdx` compilation issue when `nextjs` is set as the framework.

I'm new to next.js, so I may be doing something wrong about image tags. But storybook will need to consider how it runs the `mdx` compilation if the frameworks is set to `nextjs` thanks a lot for the help!  Based on your feedback I'll update the issue.

**Comment by rkrishnasanka** [comment]
@valentinpalkovic it looks like this is an mdx rendering issue for nextjs when used with storybook. Storybook should automatically use `next/Image` tags rather than `<img>` tags when using with nextjs. It seems like its a problem in general.

Let me know if I can keep this here/submit a bug fix/etc.

**Comment by valentinpalkovic** [comment]
The `Introduction.stories.mdx` example for Next.js projects was generated wrongly and is fixed in https://github.com/storybookjs/storybook/pull/20798. This fix should be released soon-ish :)

**Comment by shilman** [comment]
Closing this as fixed in https://github.com/storybookjs/storybook/pull/20798

Please feel free to reopen if the issue remains
