### ISSUE TITLE
[Bug]: Custom events in vue2 are erroring

### ISSUE THREAD

**Issue by fazulk** [storybookjs/storybook#20753]
### Describe the bug

This issue #19318 was solved last week  and fixed event handlers that are already camelCased. eg: `onInput`, `onChange`, `thisHappend`.  

This doesn't account for custom events in vue2 such as `something-happend`, `logged-in`, etc.  The recommended casing for custom events in vue 2 are `kebab-case`.  Vue3 doesn't care if its kebab or camel.

which results in this error if we use a token like 'in':  using `@logged-in`
![image](https://user-images.githubusercontent.com/21964900/214143629-64fe1e57-74d1-4139-8754-be8d09edc775.png)

or this if we don't use a familiar token: using `@something-happend`
![image](https://user-images.githubusercontent.com/21964900/214144224-eb694def-ad7a-4374-9351-5ba3d1d529d0.png)

When you use the Render function this error doesn't come up. 

The solution to this is to camelCase the event names when binding them back to the component. 

### To Reproduce

```shell
load vue2/vite sandbox. 
add `this.$emit('also-clicked')` to line 51 of Button.vue
remove the render function, line 8-12 from Button.stories.js
Add arg types `alsoClicked: { action: 'clicked' }` to argTypes
Console will error
```

### System

```shell
System:
    OS: macOS 13.0.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.17.0/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
  Browsers:
    Chrome: 109.0.5414.87
    Firefox: 70.0
    Safari: 16.1
  npmPackages:
    @storybook/addon-essentials: ^7.0.0-beta.31 => 7.0.0-beta.31
    @storybook/addon-interactions: ^7.0.0-beta.31 => 7.0.0-beta.31
    @storybook/addon-links: ^7.0.0-beta.31 => 7.0.0-beta.31
    @storybook/blocks: ^7.0.0-beta.31 => 7.0.0-beta.31
    @storybook/testing-library: ^0.0.13 => 0.0.13
    @storybook/vue: ^7.0.0-beta.31 => 7.0.0-beta.31
    @storybook/vue-vite: ^7.0.0-beta.31 => 7.0.0-beta.31
```

**Comment by shilman** [comment]
Son of a gun!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.51 containing PR #20754 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
