### ISSUE TITLE
[Feature Request]: Support latest `zone.js` version in Storybook 6

### ISSUE THREAD

**Issue by kfrancois** [storybookjs/storybook#20758]
### Is your feature request related to a problem? Please describe

Hi!

`zone.js@0.12.0` got released a few months back and is a valid peerDependency of Angular: https://github.com/angular/angular/blob/main/packages/core/package.json#L20

Storybook 7 changes this peerDependency to `"~0.11.4 || ~0.12.0"` but is not out yet.

This results in npm being unable to resolve dependencies when on `@storybook/angular@6.5.15`.

It would be great if this could still be included in a minor/patch version, rather than tying this in to the Storybook 7 release.

### Describe the solution you'd like

From the `v6.5.15`-tag, we simply need to update [this line](https://github.com/storybookjs/storybook/blob/v6.5.15/app/angular/package.json#L123) to include `zone.js@0.12.0`. I propose changing this line to the value it has on the [current main-branch](https://github.com/angular/angular/blob/main/packages/core/package.json#L20) for greater compatibility when eventually upgrading to Storybook 7.

### Are you able to assist to bring the feature to reality?

yes, I can

**Comment by valentinpalkovic** [comment]
Hey @kfrancois,

AFAIK zone.js@0.12.0 is only a valid peerDependency of Angular >= 15. Angular 14 still relies on `~0.11.4`, and I think Storybook 6 does not Support Angular 15. If it does, I will backport the dependency version for 6.5. Please let me know what you think.

**Comment by kfrancois** [comment]
Hi @valentinpalkovic!

Sorry for losing track of this - I can confirm Storybook 6.5 works on Angular 15 (more specifically, `15.1.3` which is `latest`).

While Angular 15 might never be officially supported on Storybook 6.5, it would be nice to use the latest version without conflicting peerDependencies given that Storybook 7 is not released yet.

I'd understand the decision not to update peerDependencies though, thank you either way for checking out the issue!

**Comment by tomnar** [comment]
@kfrancois I ran into the same problem.
I don't know if I am stating the obvious, but I fixed it by overriting the version manually.
I have added the following to the package.json for now:
```
  "overrides": {
    "@storybook/angular": {
      "zone.js": "~0.12.0"
    }
  }
```
Obviously not ideal, but I have not experienced any problems (yet)

**Comment by valentinpalkovic** [comment]
@kfrancois 

We are excited to announce the recent release of Storybook 7, which brings a wealth of new features, enhancements, and bug fixes. In light of this development, our team has decided to concentrate our efforts on supporting and refining Storybook 7. Consequently, we will no longer be implementing new features or fixing bugs for Storybook 6.5.x.

We apologize if this causes any inconvenience and encourage you to consider upgrading to Storybook 7 to take advantage of the latest improvements and updates. Our documentation offers a detailed guide to help you navigate the upgrade process with ease.

As a result of this shift in focus, we will be closing relevant issues pertaining to Storybook 6.5.x on our GitHub repository. We welcome you to submit new issues related to Storybook 7, as your input is crucial for our ongoing efforts to provide the best possible experience for our users.

Thank you for your understanding, and we can't wait to see the incredible projects you will develop with Storybook 7!

**Comment by kfrancois** [comment]
Hi @valentinpalkovic 

Thanks for your response. We're happily upgrading Storybook 7 in the meantime, and for anyone who hasn't upgraded they can use the workaround @tomnar mentioned 😄 🚀
