### ISSUE TITLE
[Bug]: crash reports are not sent with MDX2 errors

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#20760]
### Describe the bug

I was trying to understand how an MDX2 error could not send crash reports, and turns out, in my experiment, the reports are never sent because (I guess) the process ends before that happens.

### To Reproduce

1. Create a basic sandbox:
`yarn start`

2. Add an MDX2 error somewhere in Intro stories:
```
<a>
  problems
</a>.
```

3. Run storybook with `STORYBOOK_TELEMETRY_DEBUG=1`

### Additional context

About the error:
    The code starts here in [withTelemetry](https://github.com/storybookjs/storybook/blob/next/code/lib/core-server/src/withTelemetry.ts#L70)
    It then executes [storybookDevServer](https://github.com/storybookjs/storybook/blob/next/code/lib/core-server/src/build-dev.ts#L128)
    And fails in [managerBuilder.start](https://github.com/storybookjs/storybook/blob/next/code/lib/core-server/src/dev-server.ts#L75)
    :point_right:  If you threw an error right before that last line I linked, the error is sent.

**Comment by shilman** [comment]
Egads!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.41 containing PR #20906 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```
