### ISSUE TITLE
[Bug]: Dependabot Alerts on transitive dependencies in several addons

### ISSUE THREAD

**Issue by spiess-demos** [storybookjs/storybook#20779]
### Describe the bug

There are security issues reported by GitHub [Dependabot alerts](https://github.com/demos-europe/demosplan-ui/security/dependabot) for several Storybook modules in **v6.5.15**, that can not be updated to a non-vulnerable version.

**Prototype Pollution in JSON5 via Parse Method** https://github.com/advisories/GHSA-9c47-m6qq-7p4h

- @storybook/addon-docs@6.5.15 requires json5@^1.0.1 via a transitive dependency on loader-utils@1.4.2
- @storybook/addon-essentials@6.5.15 requires json5@^1.0.1 via a transitive dependency on loader-utils@1.4.2
- @storybook/builder-webpack5@6.5.15 requires json5@^1.0.1 via a transitive dependency on loader-utils@1.4.2
- @storybook/manager-webpack5@6.5.15 requires json5@^1.0.1 via a transitive dependency on loader-utils@1.4.2
- @storybook/vue@6.5.15 requires json5@^1.0.1 via a transitive dependency on loader-utils@1.4.2
- The latest possible version that can be installed is 1.0.2
- The earliest fixed version is 2.2.2

**Uncontrolled Resource Consumption in trim-newlines** https://github.com/advisories/GHSA-7p7h-4mm5-852v

- Hoisted from "@storybook#vue#@storybook#core#@storybook#core-server#x-default-browser#default-browser-id#meow#trim-newlines"
- The latest possible version of trim-newlines that can be installed is 1.0.0.
- The earliest fixed version is 3.0.1.

**glob-parent before 5.1.2 vulnerable to Regular Expression Denial of Service in enclosure regex** https://github.com/advisories/GHSA-ww39-953v-wcq6

- @storybook/vue@6.5.15 requires glob-parent@^3.1.0 via a transitive dependency on fast-glob@2.2.7
- The latest possible version that can be installed is 3.1.0 
- The earliest fixed version is 5.1.2

While i'm aware on this [issue and comments from maintainers](https://github.com/storybookjs/storybook/issues/18713), are there fixes planned for Storybook 6?

**Comment by FlorianMH** [comment]
Hi, I also noticed

 **trim lower than 0.0.3 are vulnerable to Regular Expression Denial of Service (ReDoS) via trim().**
 trim is a dependence of remark-parse, and remark-parse@8.0.3 is required by :

-  @storybook/addon-docs
-  @storybook/csf-tools
-  @storybook/mdx1-csf

**Comment by shilman** [comment]
Please try upgrading to the latest 7.0 prerelease. These should all be fixed there. We can't backport the fixes to 6.5 because they are breaking changes.

Migration guide: https://storybook.js.org/migration-guides/7.0

**Comment by spiess-demos** [comment]
@shilman thanks for the clarification!
