### ISSUE TITLE
[Feature Request]: Subcomponents support

### ISSUE THREAD

**Issue by konsalex** [storybookjs/storybook#20782]
### Is your feature request related to a problem? Please describe

Currently the roadmap involves dropping support for `subcomponents`, which is already done in the latest beta if i'm not mistaken, because it was a half-baked feature, but unfortunately there is no real alternative in place.

It's a frequent architecture to have subcomponents in elements like Navigations for example, that need to share the same context.

For example in our case we used this feature in many cases to document sub-components that can be used only in a specific context:
![image](https://user-images.githubusercontent.com/12672541/214562993-9bf106ca-6a98-4fdf-a905-c2f6c9a96a4d.png)

![CleanShot 2023-01-25 at 13 26 54](https://user-images.githubusercontent.com/12672541/214563160-7a3237e8-c891-4378-9a18-32be85751c54.png)

### Describe the solution you'd like

Keep the `subcomponents` functionality, or make a convenient alternative.

As proposed from @JReinhold in the discord forum, grouping in `ArgsTable` could be used: https://storybook.js.org/docs/react/writing-docs/doc-block-argstable#grouping

which have the following pros and cons:

| Pros                           | Cons                                                                                                                              |
|--------------------------------|-----------------------------------------------------------------------------------------------------------------------------------|
|  Can control the subcomponents | Really hard to set this up, as the controls need explicit definition, while the `subcomponents` feature was implicitly inferring the props |
|                                | Less cluttered screen                                                                                                             |

### Describe alternatives you've considered

Keep the subcomponents until there is a valuable alternative, and maybe to avoid confusion, flag the subcomponent tabs, so users can understand that those tabs are not interactive rather than demonstrating the props the components can use.

### Are you able to assist to bring the feature to reality?

no

**Comment by keisha-rw** [comment]
Our team would also appreciate this feature!

**Comment by wilkinsjade** [comment]
@JReinhold How long will the workaround to keep the existing 6.5 behavior be available? Are there plans to eventually deprecate the ArgsTable block

**Comment by JReinhold** [comment]
@wilkinsjade the `ArgsTable` block is already deprecated. For now, the plan is to keep it around until we have an alternative ready.

**Comment by Flcwl** [comment]
Nice! but have a little bit bug...

**Comment by Flcwl** [comment]
I also want to have `autodocs` support for Utils or React Hooks functions demos. because of I often write Utils and React Hooks In Storybook and not only for React components.

**Comment by alasdair009** [comment]
We found this feature particularly useful for our composite structure. I understand why you removed it but I feel this feature does add a lot of value for onboarding our team.

**Comment by anambl** [comment]
I'm not sure I see the problem with "the subcomponents API is that it is documentation-only". Many projects use Storybook for documentation and don't necessarily need the controls.
We have a lot of components which are exporting inner components that don't make sense on their own (e.g. an accordion and accordion item) so it makes sense to have them within one table.

Happy to hear that it's not going away until there's an alternative, as for us this feature is very useful!

**Comment by oncet** [comment]
Also looking for a way to add documentation for compund components using dot notation.

How can I use the `ArgsTable` workaroud with the `*.stories.tsx` file?

Tried something like this but it doesn't work:

```
const meta: Meta<typeof MyComponent> = {
  component: MyComponent,
  subcomponents: {
    PopperContent: MyComponent.MySubComponent,
  },
  tags: ['autodocs'],
};
```

**Comment by nobleach** [comment]
I have the same question as @oncet. "Use the `ArgsTable`" is a bit hand-wavy as I'm having trouble finding any docs explaining _how_ this can be used with subcomponents.

**Comment by JReinhold** [comment]
Time flies and we haven't been able to carve out a new API that would holistically solve the issues that we want, and we don't expect to be able to in the near future.

Therefore we've decided to _undeprecate_ the `subcomponents` API in Storybook 8.0, bringing back the feature as it was, as a permanent solution. I'm very sorry for any confusion and added work this has caused you all. We were surprised by how many users that used and liked this feature.

This means that we'll:

- [ ] Port over subcomponents support to the `ArgTypes` and `Controls` doc blocks so you don't have to implement your own workarounds
- [ ] Remove the `ArgsTable` doc block completely, as this was the last blocker to remove it
- [ ] Remove any deprecation warnings about `subcomponents`
- [ ] Document `subcomponents` properly again
