### ISSUE TITLE
[Bug]: `<Source code="xyz" />` fails in unattached docs.

### ISSUE THREAD

**Issue by tmeasday** [storybookjs/storybook#20780]
### Describe the bug

See https://github.com/storybookjs/storybook/issues/19964#issuecomment-1403397991

**Comment by shilman** [comment]
Son of a gun!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.36 containing PR #20807 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```
