### ISSUE TITLE
[Bug]: `reactDocgen` types missing from `@storybook/react-vite`

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#20789]
### Describe the bug

`@storybook/react-webpack5` has types for `typescript.reactDocgen` as can be seen [here](https://github.com/storybookjs/storybook/blob/next/code/presets/react-webpack/src/types.ts#L23). Similar types (though options should probably come from `@joshwooding/vite-plugin-react-docgen-typescript` and not `@storybook/react-docgen-typescript-plugin`) should be provided for vite as well.

### To Reproduce

This fails:

```js
import { StorybookConfig } from '@storybook/react-vite'

const config: StorybookConfig = {
  typescript: {
    reactDocgen: 'none',
  },
}

export default config;
```

**Comment by shilman** [comment]
Zoinks!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.62 containing PR #21338 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```
