### ISSUE TITLE
[Bug]: Next13 aliased imports of @next/font/google fonts break the storybook

### ISSUE THREAD

**Issue by andreymaslovru** [storybookjs/storybook#20824]
### Describe the bug

When using Next13 Google fonts ('@next/font/google'), the storybook breaks. I can't use the font not in styled-components, not in the global materialUI theme. In the first case, I see an error: "Couldn't find story matching 'ui-atoms-texts-actions-textactionmiddle--common'", and in the second, an endless loader on the storybook. 

### To Reproduce

```shell
//styles.ts
import { Roboto_Flex as fontRobotoFlex } from '@next/font/google'

const robotoFlex = fontRobotoFlex({
  subsets: ['cyrillic', 'cyrillic-ext', 'latin', 'latin-ext'],
  weight: ['400', '500', '600', '700']
})

export const useStyles = makeStyles({
  text: { ...robotoFlex.style }
})

//BaseText.tsx
const BaseText = () => {
  const styles = useStyles()

  return (
    <div styles={styles.text}>{text}</div
  )
}

//BaseText.stories.tsx
export default {
  title: 'UI/Atoms/Texts',
  component: BaseText
} as ComponentMeta<typeof BaseText>

const Template: ComponentStory<typeof BaseText> = (args) => (
  <BaseText {...args} />
)

export const Common = Template.bind({})

Common.args = {
  children: 'Base text'
}


OR USING FONTS WITH MUI: 
const robotoFlex = fontRobotoFlex({
  subsets: ['cyrillic', 'cyrillic-ext', 'latin', 'latin-ext'],
  weight: ['400', '500', '600', '700']
})

//theme.ts
const theme = createTheme({
  typography: {
    ...robotoFlex.style
  }
})
```

### System

```shell
System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 16.15.1 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/node_modules/.bin/yarn
    npm: 8.11.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 109.0.5414.119
    Firefox: 109.0
    Safari: 15.5
  npmPackages:
    @storybook/addon-actions: 6.5.13 => 6.5.13 
    @storybook/addon-essentials: 6.5.13 => 6.5.13 
    @storybook/addon-interactions: 6.5.13 => 6.5.13 
    @storybook/addon-links: 6.5.13 => 6.5.13 
    @storybook/builder-webpack5: 6.5.13 => 6.5.13 
    @storybook/manager-webpack5: 6.5.13 => 6.5.13 
    @storybook/react: 6.5.13 => 6.5.13 
    @storybook/testing-library: 0.0.13 => 0.0.13
```

### Additional context

Please note that the problem is not with local fonts - '@next/fonts/local', but with '@next/fonts/google'
How can I properly use this with a storybook? Components that are used in the storybook refer to global materialUI styles, but not working without MUI

depends: {
  "next": "13.0.7",
  "storybook": "^7.0.0-beta.36"
}

**Comment by yannbf** [comment]
Hey @andreymaslovru thanks for reporting this issue! Could you please setup a reproduction so we can better assist you?

```
npx storybook@next repro nextjs/default-ts --output next-repro
```

**Comment by andreymaslovru** [comment]
@yannbf Hey, please clone or fork this: https://github.com/andreymaslovru/storybookWithNext13Issue
In this repository you can find two branches: master and feature/issue-1
**In the first one**, I reproduced the error with the Google font in component TestFont (more details: stories/TestFont.tsx)
**In the second branch**, you can see the commit, it is related to the materialUI. There I prepared CustomButtonMUI.tsx component in the following path: stories/CustomButtonMUI

Below is a screen that the font is connected (u can run 'yarn dev' and check this), but Storybook not changed fonts
<img width="552" alt="Screenshot 2023-01-30 at 15 33 24" src="https://user-images.githubusercontent.com/74611548/215426040-9c9369e0-21da-44b5-ac5e-97dc8d731ee0.png">

<img width="612" alt="Screenshot 2023-01-30 at 15 36 04" src="https://user-images.githubusercontent.com/74611548/215426588-79a93e44-eea8-4538-87f6-19277b42d8b8.png">

<img width="1215" alt="Screenshot 2023-01-30 at 15 36 25" src="https://user-images.githubusercontent.com/74611548/215426667-0cca8972-9786-4ab1-991e-c88fc7893fe5.png">

I hope this helps to understand what I'm doing wrong or what's the problem

**Comment by andreymaslovru** [comment]
I used the command above, and everything works fine, but I found what was the reason for the breakdown... 

be careful when calling a function 
import {Roboto_Flex as fontRobotoFlex} from '@next/font/google' NOT WORKING!

call directly -> import {Roboto_Flex} from '@next/font/google' 

I close this issue, @yannbf thank you!

**Comment by yannbf** [comment]
Thanks for reporting further @andreymaslovru! I think that is a limitation and we should probably work on fixing that.

@valentinpalkovic this might be related to the logic in here, given that the AST structure might be slightly different with aliased imports? https://github.com/storybookjs/storybook/blob/next/code/frameworks/nextjs/src/font/babel/helpers.ts#L284

**Comment by valentinpalkovic** [comment]
@yannbf i am not sure, whether aliased imports of Google Fonts is even working in Next.js. Can you give us a feedback @andreymaslovru, whether the alias import works in Next.js directly?

**Comment by andreymaslovru** [comment]
@valentinpalkovic  Hey google fonts work next13 when calling alias so you can check it out i created a new commit and attach screenshots below 
<img width="436" alt="Screenshot 2023-01-31 at 12 36 57" src="https://user-images.githubusercontent.com/74611548/215674392-20c6408c-6cf4-45b6-997a-ef468c0527e7.png">

<img width="741" alt="Screenshot 2023-01-31 at 12 37 24" src="https://user-images.githubusercontent.com/74611548/215674456-82f111e5-3cfb-4e7e-bc23-6518c6ee2700.png">

<img width="1440" alt="Screenshot 2023-01-31 at 12 37 58" src="https://user-images.githubusercontent.com/74611548/215674541-5e5c0d7f-eef7-403d-8f15-a7bad9660577.png">

as you can see, the font works, but the storybook doesn't start
you can try change this import `import { Source_Code_Pro as sourceCodeProFunc } from '@next/font/google'` to `import { Source_Code_Pro } from '@next/font/google'` and work it


<img width="787" alt="Screenshot 2023-01-31 at 12 40 13" src="https://user-images.githubusercontent.com/74611548/215674879-3d7acb06-37a1-4432-9c86-cc2c7d43a42d.png">

**Comment by andreymaslovru** [comment]
It would be logical if next13 would not launch the font, but it does (

**Comment by valentinpalkovic** [comment]
Closing. Fixed by https://github.com/storybookjs/storybook/pull/24406
