### ISSUE TITLE
Add the Nunito Sans typeface to Storybook

### ISSUE THREAD

**Issue by vanessayuenn** [storybookjs/storybook#20828]
Storybook was designed to use Nunito Sans. It was never added even if it was listed in the font stack. We will add the Storybook typeface to Storybook.

**Comment by shilman** [comment]
¡Ay Caramba!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.41 containing PR #20846 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```
