### ISSUE TITLE
[Bug]: SB7-beta.36 - Angular: No provider for XXX

### ISSUE THREAD

**Issue by alexciesielski** [storybookjs/storybook#20821]
### Describe the bug

I just upgraded from **alpha**.33 (which worked alright with Angular v14) to beta.36 (because I upgraded Angular to v15) and now I'm getting a lot of `No provider for XXX` errors.

E.g. the `No provider for HttpClient` error does not even go away if I import the `HttpClientModule` explicitly in a given story, which seems to indicate that something is broken about `moduleMetadata` decorator (I could be wrong though).

I also tried reverting to beta.34 and beta.33 to no avail.

BUT, **after having reverted to beta.27 the problem disappeared** and my stories work, so at least I can continue with merging the Angular 15 update branch 🎉  

seems like something along the way broke global Angular providers?

### To Reproduce

```shell
Sorry, private repository
```

### System

Posting the info output of the version that I reverted to from latest, where my stories work

```
Environment Info:

  System:
    OS: macOS 13.0.1
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.13.2/bin/yarn
    npm: 8.16.0 - ~/.nvm/versions/node/v16.13.2/bin/npm
  Browsers:
    Chrome: 109.0.5414.119
    Safari: 16.1
  npmPackages:
    @storybook/addon-essentials: 7.0.0-beta.27 => 7.0.0-beta.27
    @storybook/addon-interactions: 7.0.0-beta.27 => 7.0.0-beta.27
    @storybook/angular: 7.0.0-beta.27 => 7.0.0-beta.27
    @storybook/builder-webpack5: 7.0.0-beta.27 => 7.0.0-beta.27
    @storybook/core-server: 7.0.0-beta.27 => 7.0.0-beta.27
    @storybook/eslint-config-storybook: ~3.1.2 => 3.1.2
    @storybook/jest: ~0.0.11-next.0 => 0.0.11-next.0
    @storybook/manager-webpack5: ~7.0.0-alpha.10 => 7.0.0-alpha.10
    @storybook/mdx2-csf: ~1.0.0-next.5 => 1.0.0-next.5
    @storybook/preset-scss: ~1.0.3 => 1.0.3
    @storybook/testing-library: ~0.0.14-next.1 => 0.0.14-next.1
    @storybook/theming: 7.0.0-beta.27 => 7.0.0-beta.27
```

**Comment by yannbf** [comment]
Hey @alexciesielski thanks for reporting this issue! Would you mind trying other versions, e.g. beta 28, 29, 30, 31, 31 and 32?  Especially beta 29 and 30. You could do it in a bisect fashion to not have to test all of them necessarily. That would be really helpful! Also, are you using standalone components?

**Comment by alexciesielski** [comment]
Yes I did, beta.27 works :) 

No, we are not using standalone components yet.

**Comment by Tallyb** [comment]
We experience similar, and I think it is introduced in beta 30. https://github.com/storybookjs/storybook/pull/20559
Specifically, it is not clear how to configure a storybook, that does not have a real project (i.e. it is a library). What is the suggested builder? We used ng-packagr, but it seems to be wrong.

**Comment by valentinpalkovic** [comment]
Could you provide a minimal reproduction example? I tried to import e.g.`HttpClientModule`, and it was successfully registered. Like so:

```ts
export const WithHttp: StoryFn = () => ({
  template: `<app-root></app-root>`,
  moduleMetadata: {
    imports: [
      HttpClientModule
    ],
    declarations: [
      AppComponent
    ],
  },
});
```

**Comment by sheriffMoose** [comment]
@alexciesielski can you try upgrading to [v7.0.0-beta.41](https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.41) and see if it is fixed?

**Comment by freddycoder** [comment]
I have the same issue in my project, it works great with version ```beta.27``` but I have an error with ```beta.44```

This repository can be used to reproduce the bug. The master branch uses version ```beta.27``` and the branch storybookBetaLatest uses version ```beta.44```

https://github.com/freddycoder/ErabliereApi/
https://github.com/freddycoder/ErabliereApi/tree/storybookBetaLatest

Everything needed to reproduce the bug is in the ```ErabliereIU``` folder. Every story is located in the stories folder. ```ErabiereIU/src/stories```

```
cd ErabliereIU
npm install
npm run storybook
```

storybook beta.44
![image](https://user-images.githubusercontent.com/28284200/217633950-7b7a54f5-8be2-4750-8b91-2b5f96a468a4.png)

storybook beta.27
![image](https://user-images.githubusercontent.com/28284200/217635061-9cba2219-3c31-4481-93d6-259708cf2e36.png)

**Comment by valentinpalkovic** [comment]
@sheriffMoose Finally we have a reproduction example. Thanks @freddycoder for providing it. It is much appreciated!

**Comment by sheriffMoose** [comment]
@freddycoder thanks a lot, I will look into it shortly @valentinpalkovic

**Comment by shilman** [comment]
Yo-ho-ho!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.46 containing PR #21028 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```

**Comment by freddycoder** [comment]
It looks like the HttpClient issue is fixed, but I got the error with another module:

![image](https://user-images.githubusercontent.com/28284200/218161109-d1e5d296-edda-4adc-ba4b-03b84a6f860b.png)

**Comment by marhel** [comment]
We have the same issue with injecting an service array into another service, where one module has a providers configuration that sets multi: true, in order to provide an array of all such services given the injection token. We get no provider for this injection token.

Attempts to override providers config by providing or overriding anything via the providers array in the stories moduleMetadata has been unsuccessful.

**Comment by valentinpalkovic** [comment]
@freddycoder, @Tallyb, @marhel: we are aware of this issue and we are working on a more generic fix to correctly inject all services and providers, which are marked with `providedIn: 'root‘`. Then these kind of issues shouldn't occur anymore. @sheriffMoose does some final investigations before providing a final fix. Thank you for your patience! 🙏

**Comment by nicolae536** [comment]
@valentinpalkovic did you manage to release a fix for this ? I'm running into this issue 🤔 I could try to create a fake root module for now

**Comment by alexciesielski** [comment]
it works for me in `7.0.0-rc.8` but seems to have broken again in some later version

**Comment by valentinpalkovic** [comment]
@nicolae536, @alexciesielski Have you tried following the migration guide?: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#angular-application-providers-and-modulewithproviders

**Comment by nicolae536** [comment]
@valentinpalkovic I can confirm that worked for me thanks
