### ISSUE TITLE
Tabs UX

### ISSUE THREAD

**Issue by vanessayuenn** [storybookjs/storybook#20829]
How many times have you had to scroll sideways on a toolbar to get to an addon tab? Was it obvious that you could scroll sideways?

On narrow screens, the Addons tab bar overflows horizontally. There is not an indicator there is more content out of sight. It is also tough ergonomically to scroll horizontally because that behavior requires finer motor functions to swipe in a constrained space.

Implement a new overflow pattern that condenses down to a single tab.

![image](https://user-images.githubusercontent.com/6842965/215456214-bf0ca192-ec58-4bbc-a03d-8d1128a901a8.png)

**Comment by shilman** [comment]
¡Ay Caramba!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.42 containing PR #20783 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```
