### ISSUE TITLE
[Bug]: Preview breaks in MDX when Story block `of` property is undefined

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#20841]
### Describe the bug

It's quite common to mistype when authoring stories in MDX if you don't have intellisense.

Here's an example when you have everything correct in your MDX. It renders everything fine:
![image](https://user-images.githubusercontent.com/1671563/215593566-09dc6b0a-bf27-4bd7-8e43-295fc5bff251.png)

However as soon as you introduce a single issue with the `of` property, pointing to undefined:

```jsx
<Story of={ButtonStories.Secondayr} /> <-- should have been Secondary, so it ends up undefined
```

The entire preview breaks.
![image](https://user-images.githubusercontent.com/1671563/215593658-8f565d94-6c7d-4543-b969-7f7b59e3ac41.png)

Would it be possible to have an error boundary in it so that only that “404” element stops working? Like how it works with that “broken image icon” which is shown when you have a wrong URL in an <img src> tag?

### To Reproduce

```shell
This should do it:


<Story of={undefined} /> 
```
```


### System

_No response_

### Additional context

_No response_

**Comment by dev-phantom** [comment]
would love to fix this

**Comment by JReinhold** [comment]
@dev-phantom feel free to work on it if you want!

**Comment by yannbf** [comment]
@tmeasday I think this is now good after your changes, right?

**Comment by tmeasday** [comment]
@yannbf which changes are you referring to? If you mean the indexing errors, I'm not 100% sure. I *think* it checks the of is a stories file, so it'll error. We should test it out.

**Comment by tmeasday** [comment]
OK, yes it says this:

<img width="830" alt="image" src="https://user-images.githubusercontent.com/132554/222571870-6fc7eef9-fcb2-4ea7-8299-79a59035e48b.png">

I'm not sure the error is 100% perfect. I'll submit a PR to improve it.

**Comment by tmeasday** [comment]
Ok I improved that error: https://github.com/storybookjs/storybook/pull/21365, but actually this issue is about doing incorrect `of={}` in the story block, which still has the behaviour reported on this issue. @yannbf what changes did you think might have fixed that?

**Comment by tmeasday** [comment]
I reckon the issue here is just more we don't show the error when an MDX errors for whatever reason. For instance if you forget to import the `Story` block, you have a similar white screen.

**Comment by shilman** [comment]
Ermahgerd!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.61 containing PR #21365 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```
