### ISSUE TITLE
Fix Doc Block docs, bugs and migration notes

### ISSUE THREAD

**Issue by vanessayuenn** [storybookjs/storybook#20850]
# Migration notes

- [x] Check deprecation warnings in blocks, and ensure they link to the correct notes
- [x] Check migration notes cover everything

# Docs
Bring docs up to date with final implementation

- [x] Write docs for `Markdown`
- [x] Update docs on `sourceState` in Canvas
- [x] Document `Description` in autodocs page

# Bugs

- [x] Try to remove reset styles from `DocsContainer`
- [x] Old SourceState enum in Canvas block might be broken
- [x] `docs.canvas.withToolbar` doesn't have an effect in autodocs

https://github.com/storybookjs/storybook/pull/20803

**Comment by shilman** [comment]
Yee-haw!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.40 containing PR #20803 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```
