### ISSUE TITLE
Addon Essentials (Outline): Use the new Framework API

### ISSUE THREAD

**Issue by jonniebigodes** [storybookjs/storybook#20862]
Opening this issue so we can address the upcoming changes on how addons are built/updated for the upcoming 7.0 release. If anyone is interested in making the changes required and continuing to support and maintain the addon, let us know so that we're aware and help/guide the community moving forward. To help with this process, we've built an abridged guide [here](https://chromatic-ui.notion.site/Addon-migration-for-Storybook-7-002f2f627c1d470298ca94894ab8a040), and should any questions or issues, please reach out to us in the prerelease channel in our [Discord Server](https://discord.gg/storybook).

**Comment by winkerVSbecks** [comment]
Yea, I don't get it. `@storybook/addon-outline` is already upgraded and `storybook-addon-outline` is deprecated

**Comment by winkerVSbecks** [comment]
deprecated on npm too https://www.npmjs.com/package/storybook-addon-outline
