### ISSUE TITLE
Fix install size benchmark

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#20875]
Install size benchmarks currently report the entire size of `node_modules` including both SB packages and the "app's" packages, resulting in large install sizes that are incorrect.

Based on the way we do our benchmarks (using sandbox repro templates) it's hard to get the before & after sizes. Even if we could get them, there's a lot of variability based on the project you're installing into. E.g. if CRA upgraded some of its dependencies, it could change the numbers a lot even though SB didn't change.

To address these issues we should benchmark install size against an EMPTY project:

```
yarn init -y
npx sb@next init -t react
du -s .
```

This will change the numbers again & won't necessarily reflective of an actual user experience (e.g. if the user already has react installed, then SB won't install it again). But it's simple & consistent & a good baseline moving forward.

**Comment by IanVS** [comment]
>E.g. if CRA upgraded some of its dependencies, it could change the numbers a lot even though SB didn't change.

Only if it added or removed dependencies that are deduplicated with storybook, right?  I think it's still the most accurate to real-user experience to take the before-and-after size of node_modules when installing into a sandbox.

**Comment by vanessayuenn** [comment]
@shilman is this issue still relevant?

**Comment by shilman** [comment]
Nope, fixed when we updated the benchmarks earlier this year. Closing!
