### ISSUE TITLE
[Bug]: Zoom in Safari is not working as expected

### ISSUE THREAD

**Issue by Spielboerg** [storybookjs/storybook#20888]
### Describe the bug

The CSS `zoom` is not working correctly in Safari if rem values are used. See a minimal reproduction here:
https://codepen.io/spielboerg/pen/GRBPRRE

Here is the comparison between Safari & Google Chrome:
<img width="500" alt="Safari Bug" src="https://user-images.githubusercontent.com/7893762/216300215-002af39c-11db-45b5-b7a5-ea1a42bcdb5d.png">

I have already filed a bug report with Apple about this. Until this bug is fixed, it might be better if the zoom was done with `transform: scale()` like for Firefox.

### To Reproduce

1. Open the official Storybook: https://storybookjs.netlify.app/official-storybook/?path=/story/addons-actions--arg-types-example
2. Change the padding of the button in the devTools to `1rem`
3. Increase the zoom in Storybook via <img width="80" alt="SCR-20230202-g58" src="https://user-images.githubusercontent.com/7893762/216302153-bb41fac2-d3a0-44ec-a987-2a5be860c89f.png"> (not the native browser zoom via CMD/Ctrl + +/-)
4. See that the button is not scaled properly (top: normal zoom, bottom: zoomed in):
    <img width="354" alt="Storybook" src="https://user-images.githubusercontent.com/7893762/216302962-e2861729-db3d-4cb3-a375-aa63aadbc542.png">

### System

```shell
Environment Info:

  System:
    OS: macOS 13.2
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.18.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 109.0.5414.119
    Firefox: 109.0
    Safari: 16.3
  npmPackages:
    @storybook/addon-docs: ^6.5.10 => 6.5.16 
    @storybook/addon-essentials: ^6.5.16 => 6.5.16 
    @storybook/addon-links: ^6.5.16 => 6.5.16 
    @storybook/addons: ^6.5.10 => 6.5.16 
    @storybook/builder-webpack5: ^6.5.16 => 6.5.16 
    @storybook/manager-webpack5: ^6.5.16 => 6.5.16 
    @storybook/preset-create-react-app: ^4.1.2 => 4.1.2 
    @storybook/react: ^6.5.16 => 6.5.16 
    @storybook/testing-library: ^0.0.13 => 0.0.13 
    @storybook/theming: ^6.5.10 => 6.5.16
```

**Comment by ndelangen** [comment]
I've labelled this as a good first contribution, because it's a pretty contained feature.
I can support whoever wants to work on this. Please reach out via discord: https://discord.gg/storybook

**Comment by blacktoast** [comment]
Hello, Do you mind if I try to fix it? As It is my first time on this project, could you recommend any particular document or codes to focus on?
I also entered a discord

**Comment by Spielboerg** [comment]
@blacktoast Maybe in the next 2 weeks I will have time to try it as well, but please go ahead. So far I have found these two related files:

https://github.com/storybookjs/storybook/blob/78c303282d870a29eac6a8bdd2f82a8d4d764c24/code/ui/components/src/Zoom/browserSupportsCssZoom.ts#L1-L10

https://github.com/storybookjs/storybook/blob/78c303282d870a29eac6a8bdd2f82a8d4d764c24/code/ui/components/src/Zoom/ZoomIFrame.tsx#L37-L55

I'm not sure how to change the test in `browserSupportsCssZoom()` without adding an exception for Safari, since the existing test is pretty straight forward. But maybe you or @ndelangen have an idea how to solve this problem.

**Comment by blacktoast** [comment]
I don't have any ideas either, other than adding an exception for Safari in `browserSupportsCssZoom()`.

**Comment by ndelangen** [comment]
@blacktoast that sounds like a good solution to me! I'd welcome a PR making that change!

Please ping me, if you open a PR, I'll take a look ❤️

**Comment by shilman** [comment]
¡Ay Caramba!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.50 containing PR #21069 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```
