### ISSUE TITLE
[Bug]: Unable to find versions of @storybook/react using yarn

### ISSUE THREAD

**Issue by dev-phantom** [storybookjs/storybook#20882]
### Whenever I try to run npx sb init in a project it fails with Unable to find versions of <dependency> using yarn error message.

`$ npx sb init

 sb init - the simplest way to add a Storybook to your project. 

 • Detecting project type. ✓
 • Adding Storybook support to your "Create React App" based project
   Unable to find versions of @storybook/react using npm

     Unable to find versions of @storybook/addon-links using npm

     Unable to find versions of @storybook/addon-essentials using npm

     Unable to find versions of @storybook/addon-actions using npm

     Unable to find versions of @storybook/addon-interactions using npm

     Unable to find versions of @storybook/testing-library using npm

`

**Comment by shilman** [comment]
Do you a have a reproduction repo you can share?

**Comment by dev-phantom** [comment]
https://github.com/dev-phantom/bastion-health

**Comment by ndelangen** [comment]
There must be something odd about your connection or npm settings.. I was able to init storybook on your repro.

**Comment by dev-phantom** [comment]
> There must be something odd about your connection or npm settings.. I was able to init storybook on your repro.

Please how did you fix this?

**Comment by ndelangen** [comment]
@dev-phantom there's no method by which I can assist I'm afraid, Your repo "just worked" for me. There must be something going on on your machine, which I can't assist with.

**Comment by abhay-rana** [comment]
hi, I am also getting this problem while installation of the storybook.
so the problem with my file, the file name is .npmrc 
this helps me in not installation of the library using the npm 
check also that there is some file in your folder that is causing hindrance.

**Comment by Chr15t0pher** [comment]
@dev-phantom hi, i have met the same problem, but i solved it by updating my Node.js to latest version, hope this helps.
`nvm install 18.14.2` then `nvm alias default 18.14.2`.
