### ISSUE TITLE
[Bug]: Storybook 7 beta 40 crashes if preview storySort is a reference to an array

### ISSUE THREAD

**Issue by kroeder** [storybookjs/storybook#20883]
### Describe the bug

In your preview.ts / js, if you previously sort stories like this 

```typescript
const myOrder = ['Foo', 'Bar'];
export const parameters = {
    options: {
        storySort: {
            method: 'alphabetical',
            order: myOrder,
            locales: 'en-US',
        }
    }
};
```

Storybook crashes with a runtime error 

```
info => Using angular project with "tsConfig:.storybook/tsconfig.json"
ERR! Error: Unknown node type [object Object]
ERR!     at parseValue (/Users/kroeder/dev/Work/cloud-ui/node_modules/@storybook/csf-tools/dist/index.js:74:11123)
ERR!     at /Users/kroeder/dev/Work/cloud-ui/node_modules/@storybook/csf-tools/dist/index.js:74:11047
ERR!     at Array.reduce (<anonymous>)
ERR!     at parseValue (/Users/kroeder/dev/Work/cloud-ui/node_modules/@storybook/csf-tools/dist/index.js:74:10989)
ERR!     at getStorySortParameter (/Users/kroeder/dev/Work/cloud-ui/node_modules/@storybook/csf-tools/dist/index.js:96:130)
ERR!     at StoryIndexGenerator.getStorySortParameter (/Users/kroeder/dev/Work/cloud-ui/node_modules/@storybook/core-server/dist/index.js:10:17587)
ERR!     at async StoryIndexGenerator.sortStories (/Users/kroeder/dev/Work/cloud-ui/node_modules/@storybook/core-server/dist/index.js:10:15509)
ERR!     at async StoryIndexGenerator.getIndex (/Users/kroeder/dev/Work/cloud-ui/node_modules/@storybook/core-server/dist/index.js:10:15846)
ERR!     at async extractStoriesJson (/Users/kroeder/dev/Work/cloud-ui/node_modules/@storybook/core-server/dist/index.js:10:4396)
ERR!     at async Promise.all (index 4)
ERR!  Error: Unknown node type [object Object]
ERR!     at parseValue (/Users/kroeder/dev/Work/cloud-ui/node_modules/@storybook/csf-tools/dist/index.js:74:11123)
ERR!     at /Users/kroeder/dev/Work/cloud-ui/node_modules/@storybook/csf-tools/dist/index.js:74:11047
ERR!     at Array.reduce (<anonymous>)
ERR!     at parseValue (/Users/kroeder/dev/Work/cloud-ui/node_modules/@storybook/csf-tools/dist/index.js:74:10989)
ERR!     at getStorySortParameter (/Users/kroeder/dev/Work/cloud-ui/node_modules/@storybook/csf-tools/dist/index.js:96:130)
ERR!     at StoryIndexGenerator.getStorySortParameter (/Users/kroeder/dev/Work/cloud-ui/node_modules/@storybook/core-server/dist/index.js:10:17587)
ERR!     at async StoryIndexGenerator.sortStories (/Users/kroeder/dev/Work/cloud-ui/node_modules/@storybook/core-server/dist/index.js:10:15509)
ERR!     at async StoryIndexGenerator.getIndex (/Users/kroeder/dev/Work/cloud-ui/node_modules/@storybook/core-server/dist/index.js:10:15846)
ERR!     at async extractStoriesJson (/Users/kroeder/dev/Work/cloud-ui/node_modules/@storybook/core-server/dist/index.js:10:4396)
ERR!     at async Promise.all (index 4)
 >  NX   Broken build, fix the error above.
   You may need to refresh the browser.
```

### Workaround

Use an inline-array instead.

```typescript
export const parameters = {
    options: {
        storySort: {
            method: 'alphabetical',
            order: ['Foo', 'Bar'],
            locales: 'en-US',
        }
    }
};
```

### System

```shell
System:
    OS: macOS 13.0.1
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
  Browsers:
    Chrome: 109.0.5414.119
    Safari: 16.1
  npmPackages:
    @storybook/addon-a11y: ^7.0.0-beta.40 => 7.0.0-beta.40 
    @storybook/addon-essentials: ^7.0.0-beta.40 => 7.0.0-beta.40 
    @storybook/addon-interactions: ^7.0.0-beta.40 => 7.0.0-beta.40 
    @storybook/addons: ^7.0.0-beta.40 => 7.0.0-beta.40 
    @storybook/angular: ^7.0.0-beta.40 => 7.0.0-beta.40 
    @storybook/jest: 0.0.11-next.0 => 0.0.11-next.0 
    @storybook/testing-library: 0.0.14-next.1 => 0.0.14-next.1 
    @storybook/theming: ^7.0.0-beta.40 => 7.0.0-beta.40
```

**Comment by zhyd1997** [comment]
Yes, the source code is here: https://github.com/storybookjs/storybook/blob/6fbc1d318435630d207ea145d51dd5a27a5dc5c3/code/lib/csf-tools/src/getStorySortParameter.ts#L44

**Comment by shilman** [comment]
@kroeder the code linked to by @zhyd1997 explains the problem with your configuration. I'm wondering why the error in your bug report doesn't show that error.

@yannbf can we add this to the SB eslint rules?

**Comment by kroeder** [comment]
It does

ERR! at async extractStoriesJson

Second last error message.
The error itself makes sense as well

@ndelangen and @valentinpalkovic found out, that the implementation of storySort does not cover references to an array and only a direct array assignment which I would consider a bug that is solvable (you removed the bug label)

I can live with the workaround, though :)

**Comment by zhyd1997** [comment]
@shilman 

it's because `t.isIdentifier(storySort) === true`, so it returned `unsupported` finally:
https://github.com/storybookjs/storybook/blob/6fbc1d318435630d207ea145d51dd5a27a5dc5c3/code/lib/csf-tools/src/getStorySortParameter.ts#L99-L123

**Comment by shilman** [comment]
@kroeder I don't see the string "Parameter 'options.storySort' should be defined inline" in your report.

Regarding whether this is a bug, it's the intended behavior. We've defined the limitations of the code and give an error explaining what to do to fix it.

Yes we could chase down the variable reference but where do you stop? What if it's a reference to a variable that references a variable? What if it's a variable that references an import from another file?

**Comment by zhyd1997** [comment]
**Expected**: returned `unsupported` as above comment shows.
**Actually**: returned `parseValue` early

https://github.com/storybookjs/storybook/blob/6fbc1d318435630d207ea145d51dd5a27a5dc5c3/code/lib/csf-tools/src/getStorySortParameter.ts#L39

<img width="831" alt="Screenshot 2023-02-04 at 16 41 41" src="https://user-images.githubusercontent.com/31362988/216757893-004e3596-549e-4cb7-a782-a619c37a6858.png">

**Comment by zhyd1997** [comment]
I checked again and found that:

`getStorySortParameter` allow 1 parameter that called `previewCode`, which is whole source code in `preview.js` file.

And they are same in both enviroments below, but

`t.isIdentifier(storySort)` on Node enviroment (`getStorySortParameter` in unit test) -- development enviroment
`t.isObjectExpression(storySort)` on Browser enviroment -- production usage by every storybook users.

**Comment by zhyd1997** [comment]
```js
// preview.js
const myOrder = ['Foo', 'Bar'];
export const parameters = {
    options: {
        storySort: {
            method: 'alphabetical',
            order: myOrder,
            locales: 'en-US',
        }
    }
};
```

`t.isObjectExpression(storySort)` but  `t.isIdentifier(p.value)`:

<img width="487" alt="Screenshot 2023-02-04 at 17 53 43" src="https://user-images.githubusercontent.com/31362988/216760781-ad5059c6-0121-42cf-97b3-3a24aedcfd5a.png">


which is not handled by `parseValue` fn.

https://github.com/storybookjs/storybook/blob/6fbc1d318435630d207ea145d51dd5a27a5dc5c3/code/lib/csf-tools/src/getStorySortParameter.ts#L27-L34

that's why throws the error unknown node type:

https://github.com/storybookjs/storybook/blob/6fbc1d318435630d207ea145d51dd5a27a5dc5c3/code/lib/csf-tools/src/getStorySortParameter.ts#L39

This change would be better:

> change `${expr}` to `${expr.type}`.

<img width="966" alt="Screenshot 2023-02-04 at 17 50 27" src="https://user-images.githubusercontent.com/31362988/216760678-3be0b3a5-f803-41ca-850e-0e9efdaddb5d.png">

**Comment by shilman** [comment]
Great Caesar's ghost!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.44 containing PR #20930 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```
