### ISSUE TITLE
Menu design update

### ISSUE THREAD

**Issue by valentinpalkovic** [storybookjs/storybook#20897]
We looked at the variety of menus we use across Storybook and refined the menu system. This update aligns the styling for all menus and provides a fixed set of menu layouts:

1. Icons are always on the left
    1. If there is one icon in a menu item, every other menu item will have an indent to match the space of the icon as seen in the Storybook menu.
2. If there are no icons, the item label is not indented.
3. There is a node on the right of each menu item that can be populated with keyboard shortcuts, illustrations, etc.
4. Active items (denoted with a checkmark) will be both bold and blue.
5. There will be an optional `description` text node that will be below the item label.
6. Keyboard shortcuts will list all commands in one container.
7. The decorative menu tooltip arrows are no longer shown.

![image](https://user-images.githubusercontent.com/5889929/216345740-849eb523-64c4-43d4-abae-0e98206cd157.png)

**Comment by shilman** [comment]
ZOMG!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.45 containing PR #20898 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```
