### ISSUE TITLE
[Feature Request]: hide entire toolbar with parameter

### ISSUE THREAD

**Issue by adamfratino** [storybookjs/storybook#20907]
### Is your feature request related to a problem? Please describe

I can't seem to find an option to hide the toolbar per story (or globally), similar to using `T` to toggle visibility.

### Describe the solution you'd like

```
const paramters = {
  toolbar: { disable: true },
}
```

### Describe alternatives you've considered

Trying to hide things individually to slim down on the toolbar (see: #14617)

### Are you able to assist to bring the feature to reality?

yes, I can

### Additional context

Theoretically I could help on making this a reality, but I'm not currently familiar enough with how storybook is organized to dive in right away (would need some guidance on where to get started).

**Comment by shilman** [comment]
Did you try this?

```js
// .storybook/manager.js
import { addons } from '@storybook/addons';

addons.setConfig({
  showToolbar: false,
});
```

**Comment by adamfratino** [comment]
> Did you try this?
> 
> ```js
> // .storybook/manager.js
> import { addons } from '@storybook/addons';
> 
> addons.setConfig({
>   showToolbar: false,
> });
> ```

Doesn't seem to work for me. I'm on `6.5.15` if that helps.

**Comment by adamfratino** [comment]
That worked! Thanks so much.

Marking as completed, but out of curiosity is it possible to control this option per story?
