### ISSUE TITLE
[Bug]: $props object values are undefined in Storybook 7 with vue3 and vuetify 3

### ISSUE THREAD

**Issue by wheelebin** [storybookjs/storybook#20903]
### Describe the bug

I'm using the CSF2 way of setting up stories in my project and I'm no longer able to pass values from the stories args to my components since the values in the $props object are undefined.
 
I can't find any information about this not being backwards compatible so I'm assuming that this is a bug.

### To Reproduce

```shell
https://github.com/wheelebin/sb7-vue3-vuetify
```

### System

```shell
Environment Info:

  System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Xeon(R) W-1250 CPU @ 3.30GHz
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (109.0.1518.61)      
  npmPackages:
    @storybook/addon-essentials: ^7.0.0-beta.38 => 7.0.0-beta.38   
    @storybook/addon-interactions: ^7.0.0-beta.38 => 7.0.0-beta.38 
    @storybook/addon-links: ^7.0.0-beta.38 => 7.0.0-beta.38        
    @storybook/blocks: ^7.0.0-beta.38 => 7.0.0-beta.38 
    @storybook/testing-library: ^0.0.14-next.1 => 0.0.14-next.1    
    @storybook/vue3: ^7.0.0-beta.38 => 7.0.0-beta.38 
    @storybook/vue3-vite: ^7.0.0-beta.38 => 7.0.0-beta.38
```

**Comment by shilman** [comment]
@chakAs3 is this related to your recent work on vue3?

**Comment by shilman** [comment]
Great Caesar's ghost!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.47 containing PR #20995 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```
