### ISSUE TITLE
[Feature Request]: Components that require "provider" like "support for { Link } from 'react-router-dom'" 

### ISSUE THREAD

**Issue by mineclover** [storybookjs/storybook#20916]
### Is your feature request related to a problem? Please describe

It seems to be caused by the absence of a component acting as a router root in the upper component of the storybook.

Can't we create a provider that fakes the role of RouterRoot and doesn't do anything?

![image](https://user-images.githubusercontent.com/61359316/216530121-56b7cc85-e7a0-4268-9fd8-4de2bee7e264.png)

Just clear `<Link~` from context and it works

### Describe the solution you'd like

Provision of a provider of existing frameworks that do not work for storybooks, but allow you to avoid errors.

### Are you able to assist to bring the feature to reality?

no

### Additional context

```
import React, { useRef } from 'react';
import Lottie from 'lottie-react';
import styles from './NotFound.module.scss';
import notFound from './lottie/404.json';
import arrow from './lottie/arrow.json';
import { Link } from 'react-router-dom';

type Props = {};

const NotFound = (props: Props) => {
  return (
    <article className={styles.notFound}>
      <div className={styles.lottie}>
        <Lottie animationData={notFound} loop={true}></Lottie>
      </div>
      <div className={styles.textBox}>
        <p className={styles.text}>
        NotFound
          <br />
          NotFound
        </p>
      </div>
      <Link to="/">
        <Lottie animationData={arrow} loop></Lottie>
      </Link>
    </article>
  );
};

export default NotFound;
```

**Comment by shilman** [comment]
Have you tried this addon? https://storybook.js.org/addons/storybook-addon-react-router-v6

**Comment by mineclover** [comment]
> 이 애드온을 사용해 보셨습니까? https://storybook.js.org/addons/storybook-addon-react-router-v6

Thank you so much for Storybook!
