### ISSUE TITLE
[Bug]: Stories lose documentation depending on React component exports

### ISSUE THREAD

**Issue by alexgleason** [storybookjs/storybook#20914]
### Describe the bug

Depending on how `Button.tsx` is exported, documentation might not show in Storybook.

| Good :heavy_check_mark: | Bad :x: |
|---------|-------|
|![Screenshot from 2023-02-02 22-28-23](https://user-images.githubusercontent.com/3639540/216513767-d6f26317-61ff-4768-bc04-d8581001fcd6.png)|![Screenshot from 2023-02-02 22-39-14](https://user-images.githubusercontent.com/3639540/216513869-0355c2d7-e34d-409d-ae9a-7923c2629bf4.png)|

### To Reproduce

`Button.tsx`  **GOOD**:

```tsx
const Button: React.FC = () => // ...

export {
  Button as default,
  Button,
};
```

`Button.tsx`  **BAD**:

```tsx
const Button: React.FC = () => // ...

export default Button;
```

`Button.stories.tsx`  has:

```tsx
import Button from './button';

export default {
  component: Button,
  // ...
}
```

### System

```shell
System:
    OS: Linux 6.0 Pop!_OS 22.04 LTS
    CPU: (16) x64 AMD Ryzen 7 PRO 5850U with Radeon Graphics
  Binaries:
    Node: 18.13.0 - ~/.asdf/installs/nodejs/18.13.0/bin/node
    Yarn: 1.22.19 - ~/.asdf/installs/nodejs/18.13.0/.npm/bin/yarn
    npm: 8.19.3 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Firefox: 109.0
  npmPackages:
    @storybook/addon-actions: ^6.5.16 => 6.5.16 
    @storybook/addon-essentials: ^6.5.16 => 6.5.16 
    @storybook/addon-interactions: ^6.5.16 => 6.5.16 
    @storybook/addon-links: ^6.5.16 => 6.5.16 
    @storybook/addon-postcss: ^2.0.0 => 2.0.0 
    @storybook/builder-webpack5: ^6.5.16 => 6.5.16 
    @storybook/manager-webpack5: ^6.5.16 => 6.5.16 
    @storybook/react: ^6.5.16 => 6.5.16 
    @storybook/testing-library: ^0.0.13 => 0.0.13
```

### Additional context

I read through [How to write stories](https://storybook.js.org/docs/react/writing-stories/introduction) and it didn't answer my question.

**Comment by shilman** [comment]
Is this still a problem in 7.0? Migration guide: https://storybook.js.org/migration-guides/7.0

**Comment by alexgleason** [comment]
@shilman I upgraded to 7.0 beta, and it still does not work properly unless the component has a named export. `export default` results in this:

![image](https://user-images.githubusercontent.com/3639540/217603527-7a67ad28-9e7a-4a54-b810-34d0b3f10b73.png)
