### ISSUE TITLE
[Bug]:  sandboxes are broken dependency conflict. ( beta.41 )

### ISSUE THREAD

**Issue by chakAs3** [storybookjs/storybook#20926]
### Describe the bug

last update beta.41. breaks the sandboxes ,  react-vite, vue3-vite at least 
dependency conflict. for "glob"

### To Reproduce

```shell
just clean yarn, and run yarn start or yarn task to create a sandbox
```

**Comment by shilman** [comment]
Huzzah!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.42 containing PR #20927 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```
