### ISSUE TITLE
path.replaceAll is not a function

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#20948]
Have had multiple reports of `path2.replaceAll is not a function`

This appears to be an issue for users with Node < 16. Since we don't support older node versions, we should either:
- [ ] Convert this to `replace` which is back compatible
- [x] OR Detect node version early and exit with a clearer error message & instructions

**Comment by shilman** [comment]
Great Caesar's ghost!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.44 containing PR #20964 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```

**Comment by giorgosera** [comment]
I have the same issue with the latest version (7.0.5). I ran all migrations.

**Comment by shilman** [comment]
@giorgosera What version of node?

**Comment by giorgosera** [comment]
I tried with both`v16.20.0` and  `v18.15.0`. The error appears in both.

**Comment by ndelangen** [comment]
We have stopped supporting node 14, the minimum version of node storybook supports now is 16
