### ISSUE TITLE
[Bug]: Error after changing builder option from webpack5 to webpack4 

### ISSUE THREAD

**Issue by umarnazarov** [storybookjs/storybook#20949]
### Describe the bug

Currently I have a project with weback4 already setup and wanted to use Storybook. Turns out it uses webpack 5 out of the box so I desided to use webpack 4. From that point storybook throwing errors:
![image](https://user-images.githubusercontent.com/83394723/216897697-e3b8983a-ce84-45bf-954e-b82dc445a0da.png)
![image](https://user-images.githubusercontent.com/83394723/216898076-319fde72-9c59-4c5e-b2d1-bbd711140115.png)

### To Reproduce

```shell
npx storybook init --type angular


npm run storybook
```

### System

```shell
Windows 11
```

**Comment by ndelangen** [comment]
You will likely need to add a few resolution/overrides in your package.json to ensure everything will use webpack4.
Seems you now have a mix, and that's bad.

I strongly suggest to upgrade to webpack5 though. In Storybook 7.0 beta we no longer support webpack4 at all.

SB 6.5 won't see fixes for stuff like this, with SB7.0 being close to RC.
