### ISSUE TITLE
[Doc]:  README.md badge twitter error

### ISSUE THREAD

**Issue by Caixetadev** [storybookjs/storybook#20976]
### Describe the bug

the twitter badge is in error

### To Reproduce

```shell
Go to the README(https://github.com/storybookjs/storybook/blob/next/README.md) file and see that the Twitter badge is missing the picture, just with the alt "Official Twitter Handle".
```

### Additional context

In the README:

![errorbadge](https://user-images.githubusercontent.com/87894998/217154956-31be7d5c-bb8c-4af3-828d-7f8efc3041e8.png)

when you try to open the badge on the web:

link: https://badgen.net/twitter/follow/storybookjs?icon=twitter&label=%40storybookjs

![error](https://user-images.githubusercontent.com/87894998/217154992-c7efca5f-7118-48b7-aed6-e882f6371bd1.png)

**Comment by bangank36** [comment]
The issue comes from badgen.net, there is opening issue [like this](https://github.com/badgen/badgen.net/issues/585), and some of the badges are missing on their website too
https://badgen.net/: [Twitter](https://badgen.net/#twitter), [PeerTube](https://badgen.net/#peertube)

**Comment by Faizan711** [comment]
Is this issue still open, if so i would like to be assigned to work on it.
