### ISSUE TITLE
[Bug]: addons/storyshots-core - documentation outdated

### ISSUE THREAD

**Issue by patrickuhlmann** [storybookjs/storybook#21009]
### Describe the bug

In the documenation: https://github.com/storybookjs/storybook/tree/next/code/addons/storyshots-core

In the section ```Configure Jest for Angular```

The following configuration is listed:
```
  transform: {
    '^.+\\.jsx?$': 'babel-jest',
    '^.+\\.(ts|html)$': '<rootDir>/node_modules/jest-preset-angular/preprocessor.js',
  },
```

I am trying to setup that addon with angular currently and using these lines results in the following error:
```
  Module ../<rootDir>/node_modules/jest-preset-angular/preprocessor.js in the transform option was not found.
         <rootDir> is: C:\Users\...
```

Upon checking the location I can confirm that the file preprocessor.js is not present. I am using Angular 15.0.4 with jest-preset-angular 12.2.6 and jest 29.4.2. 

I guess it needs to be configured differently?

**Comment by patrickuhlmann** [comment]
The best example I found was here: 
https://stackoverflow.com/questions/69657102/storybook-addon-storyshots-for-angular-12/69741350#69741350
also I found this bug https://github.com/storybookjs/storybook/issues/12392.

Please be serious. 

If you don't update the storyshots addon and it doesn't work properly since Version 9 without Module Overrides just because the imports are not adjusted and there are no examples anywhere in the documentation stating anything about it

-> delete the addon and announce that it has been abandonned since two years.

**Comment by jonniebigodes** [comment]
The Storyshots addon is officially deprecated and will be removed in a future release of Storybook. To help with the transition process, we've created a [migration guide](https://storybook.js.org/docs/writing-tests/storyshots-migration-guide) for the available options and common use cases.
