### ISSUE TITLE
[Bug]: [7.0.0 beta] `autodocs` does not generate description for components imported from local workspace package

### ISSUE THREAD

**Issue by kvnxiao** [storybookjs/storybook#21007]
### Describe the bug

Using:
- `storybook@7.0.0-beta.44`
- `typescript@4.9.5`

When `autodocs` is enabled, the documentation for prop descriptions is not automatically generated if the component is imported from a different package, e.g. a local workspace package from a multi-package workspace setup (I'm using `pnpm`)

![image](https://user-images.githubusercontent.com/14130413/217439560-f7ded1ab-1fd7-4fa5-b421-43124429d9c1.png)

However, if I try putting the custom component directly in the storybook `apps/docs` workspace package, e.g.:
- `apps/docs/stories/Button.tsx` (copying the custom component src code over)
- `apps/docs/stories/Button.stories.ts` (using `import { Button } from "./Button"`)
the autodocs does indeed generate the `Description` using the JSDoc comments from the component's source code.

![image](https://user-images.githubusercontent.com/14130413/217439373-5d0d62e4-7e88-48f7-b3a5-7c5112f56101.png)

I suspect that it has to do with how the component is bundled into a `./dist` folder in the local multi-package workspace?

### To Reproduce

Example `Button.tsx` component:

```typescript
import { clsx } from "clsx"

export interface ButtonProps {
  /**
   * Text label for the button
   */
  label: string
  /**
   * Boolean toggle for dark mode / light mode button appearance
   */
  dark?: boolean
}

export const Button: React.FC<ButtonProps> = ({
  label,
  className,
  dark,
}: ButtonProps) => {
  return (
    <button
      className={clsx("some-class-name", dark ? "some-dark" : "some-light")}
    >
      {label}
    </button>
  )
}
```

Example `Button.stories.ts`:
```typescript
import { Button } from "@local-workspace-component-package"
// vs. the below local file import, with the button component copied over to a "./Button.tsx"
// import { Button } from "./Button"
import type { Meta, StoryObj } from "@storybook/react"

const meta = {
  component: Button,
  tags: ["autodocs"],
} satisfies Meta<typeof Button>

export default meta
type Story = StoryObj<typeof meta>

export const DarkButton: Story = {
  args: {
    label: "Dark Button",
    dark: true,
  },
}

export const LightButton: Story = {
  args: {
    label: "Light Button",
    dark: false,
  },
}
```

1. Try using above component in a separate workspace package, and use a bundler to bundle the `.tsx` file into separate `.d.ts` and `.js` files in a `./dist` folder
2. Observe creating a `Button.stories.ts` file using the above example content
3. Compare storybook autodocs output of importing the `Button` component from the local workspace package, versus copying the component over into a local `./Button.tsx` file and importing that instead. See screenshots for difference

### System

```shell
❯ pnpm dlx sb@next info                                                                                              
.../Local/pnpm/store/v3/tmp/dlx-40348    | +577 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
.../Local/pnpm/store/v3/tmp/dlx-40348    | Progress: resolved 598, reused 561, downloaded 16, added 577, done
../../AppData/Local/pnpm/store/v3/tmp/dlx-40348/node_modules/.pnpm/esbuild@0.16.17/node_modules/esbuild: Running post../../AppData/Local/pnpm/store/v3/tmp/dlx-40348/node_modules/.pnpm/esbuild@0.16.17/node_modules/esbuild: Running postinstall script, done in 385ms

Environment Info:

  System:
    OS: Windows 10 10.0.22621
    CPU: (32) x64 AMD Ryzen 9 5950X 16-Core Processor
  Binaries:
    Node: 19.2.0 - ~\AppData\Local\fnm_multishells\35420_1675823705107\node.EXE
    npm: 9.2.0 - ~\AppData\Local\fnm_multishells\35420_1675823705107\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1105.0), Chromium (109.0.1518.70)
```
```


### Additional context

_No response_

**Comment by shilman** [comment]
This is a known issue. All of our examples suggest that you should reference your components locally.

@jonniebigodes do you know of a good place to add this to the documentation. Maybe the FAQ?

**Comment by kvnxiao** [comment]
@shilman 
I was able to work around this issue by using a direct import rather than importing the re-exported file from the component package's root index.ts, and using `react-docgen` instead of the default typescript react docgen.

e.g.
`import { Button } from "@component-package/src/Button"` rather than `import { Button } from "@component-package"` where a root `index.ts` file exists that re-exports all workspace components

![image](https://user-images.githubusercontent.com/14130413/218838730-ca651bc0-dac8-4946-b90b-0f76de0b7801.png)

**Comment by jonniebigodes** [comment]
@shilman, the autodocs page has room for a Troubleshooting section. I'm working on some updates for it. I'll add it there based on this issue and provide a bit of context on this. WDYT?

**Comment by jonniebigodes** [comment]
Closing this issue as the documentation was already updated to address this. Should it require additional changes, I'll gladly re-open it and make the required changes.

Thanks for taking the time to open this issue and letting us know @kvnxiao. We appreciate it.

Have a great day.

Stay safe
