### ISSUE TITLE
[Bug]: `defaultValue` not working in Storybook 7

### ISSUE THREAD

**Issue by alexgleason** [storybookjs/storybook#21016]
### Describe the bug

|Storybook 6|Storybook 7|
|---|---|
|![image](https://user-images.githubusercontent.com/3639540/217611128-da01b4cb-f864-4414-a115-a5d27befe4eb.png)|![image](https://user-images.githubusercontent.com/3639540/217611101-53c271c6-911c-42f2-a273-d5127ebd4453.png)|

### To Reproduce

Storybook 6 code:

```tsx
export default {
  title: 'UI/Button',
  component: Button,
  argTypes: {
    text: { type: 'string', defaultValue: 'Button' }, // Note the defaultValue!
    // ...
} as ComponentMeta<typeof Button>;

const Template: ComponentStory<typeof Button> = (args) => <Button {...args} />;

// This would result in a button that says "Button"
export const Primary = Template.bind({});
Primary.args = {
  theme: 'primary',
};
```

Storybook 7 code (`defaultValue` doesn't work):

```tsx
export default {
  title: 'UI/Button',
  component: Button,
  argTypes: {
    text: { type: 'string', defaultValue: 'Button' },
    // ...
} as Meta<typeof Button>;

// Button does not have text!
export const Primary = {
  args:  {
    theme: 'primary',
  },
};
```

### System

```
System:
    OS: Linux 6.0 Pop!_OS 22.04 LTS
    CPU: (16) x64 AMD Ryzen 7 PRO 5850U with Radeon Graphics
  Binaries:
    Node: 18.14.0 - ~/.asdf/installs/nodejs/18.14.0/bin/node
    Yarn: 1.22.19 - ~/.asdf/installs/nodejs/18.14.0/.npm/bin/yarn
    npm: 9.3.1 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Firefox: 109.0
  npmPackages:
    @storybook/addon-actions: ^7.0.0-beta.44 => 7.0.0-beta.44 
    @storybook/addon-essentials: ^7.0.0-beta.44 => 7.0.0-beta.44 
    @storybook/addon-interactions: ^7.0.0-beta.44 => 7.0.0-beta.44 
    @storybook/addon-links: ^7.0.0-beta.44 => 7.0.0-beta.44 
    @storybook/addon-postcss: ^2.0.0 => 2.0.0 
    @storybook/react: ^7.0.0-beta.44 => 7.0.0-beta.44 
    @storybook/react-webpack5: ^7.0.0-beta.44 => 7.0.0-beta.44 
    @storybook/testing-library: ^0.0.14-next.1 => 0.0.14-next.1
```

**Comment by shilman** [comment]
Please see the MIGATION note here: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#no-longer-inferring-default-values-of-args

Closing this for now. If this does not solve your problem, please feel free to reopen.

**Comment by xander-marjoram** [comment]
I'm still seeing an issue using the following `devDependencies` with Storybook running within our turborepo monorepo.
```json
"@storybook/addon-essentials": "7.0.0-beta.47",
"@storybook/addon-links": "7.0.0-beta.47",
"@storybook/blocks": "7.0.0-beta.47",
"@storybook/web-components": "7.0.0-beta.47",
"@storybook/web-components-vite": "7.0.0-beta.47",
```

`argTypes` are defined as follows:
```javascript
argTypes: {
    size: {
        control: 'radio',
        options: ['xsmall', 'small', 'medium', 'large'],
        table: {
            defaultValue: { summary: 'medium' }
        }
    }
}
```

But the default value is still not being applied. Same behaviour for `control: 'select'` too.

![2023-02-14 15_29_43](https://user-images.githubusercontent.com/26894168/218783073-49cc8c3c-5eb6-4d70-8630-3b40a4982fec.png)

**Comment by alexgleason** [comment]
My understanding of the above is that this is an intentional change.

I don't really understand it, though. My `<Button>` component doesn't have text by default. What I want is to render my Button 10 times in Storybook, and have them all say "Button" as the text without having to specify it every time.

I don't see a way to do that in the Storybook 7 beta. You simply have to specify the text every time, and that is intentional(?). Then I don't see the point of having a defaultValue option at all.

**Comment by xander-marjoram** [comment]
Sorry to further hijack your issue, Alex, but I think I managed to get around one of my issues by specifying args and argTypes and thought I'd post the solution in case anyone else was having this same problem.

```javascript
import type { Meta, StoryObj } from '@storybook/web-components';

export default {
    argTypes: {
        size: {
            control: 'radio',
            options: ['xsmall', 'small', 'medium', 'large']
        }
    },
    args: {
        size: 'medium'
    }
} as Meta;

export const MediumButton : StoryObj = {
    args: {
        size: 'medium'
    }
};

export const LargeButton : StoryObj = {
    args: {
        size: 'large'
    }
};
```

I did however have to disable the docs page in the end because although the default values for the controls were now working, the component previews weren't updating or showing the correct properties. The stories themselves work just fine though.

**Comment by JosepSalvat** [comment]
Well, I've the same issue in storybookv7



`
export default {
  title: 'Button',
  component: Button,
  args: {
    text: 'Click Me',
  },
  argTypes: {
    text: {
      control: 'text',
    },
    disabled: {
      control: { type: 'boolean' },
      defaultValue: false,
    },
  },
} as Meta
`
![image](https://user-images.githubusercontent.com/88655444/233349072-d8b228b4-a9f0-4983-a6d6-cd94115b8b25.png)


I've tried everything, but it seems that defaultProps are only working with the select, not with anything else.

`const Template: StoryFn<ButtonProps> = (args) => <Button {...args} />

export const Primary = Template.bind({})
Primary.args = {
  type: 'primary',
  text: 'Primary Button',
}`

hummm I did a test, it seems that autoGenerated docs is taking the first Primary as a default for Docs? so we need to put the defaultvalues that we want to show as a Primary in this case, button?

**Comment by ackvf** [comment]
Do I understand correctly that this is the breaking change?

before
```
export default {
  title: 'Atoms/Link',
  component: Link,
  argTypes: {
    href: {
      control: 'text',
      defaultValue: 'https://app.holograph.xyz',
    },
  },
} as ComponentMeta<typeof Link>
```

after
```
export default {
  title: 'Atoms/Link',
  component: Link,
  argTypes: {
    href: {
      control: 'text',
    },
  },
  args: {
    href: 'https://app.holograph.xyz',
  },
} satisfies Meta<typeof Link>
```

**Comment by ackvf** [comment]
Damn, just a month later and I am googling this thing again. 🤦‍♂️
Thanks past me though 👋

**Comment by mattdell** [comment]
It's frustrating there isn't a codemod to migrate this. I've got to update 200 stories now by hand...
