### ISSUE TITLE
[Bug]: setLocalSaveKeyWord is not a function

### ISSUE THREAD

**Issue by uuuuooi** [storybookjs/storybook#21011]
### Describe the bug

![스크린샷 2023-02-08 오후 6 50 35](https://user-images.githubusercontent.com/117132422/217496557-5b34e4d5-08b7-41b2-9fe6-658d226e713b.png)
```javascript
  useEffect(() => {
    if (typeof window !== "undefined") {
      const result = JSON.parse(localStorage.getItem("keyWord") || "[]");
      setLocalSaveKeyWord(result);
    }
  }, [setLocalSaveKeyWord]);
```
I don't know what caused this error.
This is the code where the error occurred.

**Comment by valentinpalkovic** [comment]
Can you show the implementation of the `setLocalSaveKeyWord` function?

**Comment by uuuuooi** [comment]
![스크린샷 2023-02-09 오전 10 09 39](https://user-images.githubusercontent.com/117132422/217688944-bcc086d1-4747-4a0a-b701-dd61987cb428.png)
![스크린샷 2023-02-09 오전 10 09 43](https://user-images.githubusercontent.com/117132422/217688953-0fe14d66-7060-4141-a902-41e664a0d746.png)

**Comment by uuuuooi** [comment]
I am using the recoil selector as an argument.

**Comment by shilman** [comment]
Do you a have a reproduction repo you can share? If not, can you create one? See [how to create a repro](https://storybook.js.org/docs/react/contribute/how-to-reproduce). Thank you! 🙏
