### ISSUE TITLE
[Bug]: nunito fonts are not loaded, 404

### ISSUE THREAD

**Issue by szykov** [storybookjs/storybook#21017]
### Describe the bug

Throws errors in the browser:
sb-common-assets/nunito-sans-regular.woff2 net::ERR_ABORTED 404 (Not Found)
sb-common-assets/nunito-sans-bold.woff2 net::ERR_ABORTED 404 (Not Found)
sb-common-assets/nunito-sans-italic.woff2 net::ERR_ABORTED 404 (Not Found)
sb-common-assets/nunito-sans-bold-italic.woff2 net::ERR_ABORTED 404 (Not Found)

### To Reproduce
Generate an empty angular project and then init storybook. In my case, it is the library.

### System
sb@7.0.0-beta.43

**Comment by valentinpalkovic** [comment]
Fixed by https://github.com/storybookjs/storybook/issues/21017
