### ISSUE TITLE
[Bug]: Compodoc Fails To Start When Using PNPM (7.0.0-beta.44)

### ISSUE THREAD

**Issue by ak99372** [storybookjs/storybook#21020]
### Describe the bug

Related to Angular setup with compodoc when using pnpm package manager. The storybook will fail to start (no errors)

Debug logs show error:
> ERR_PNPM_NO_SCRIPT  Missing script: compodoc

The installer should either add this to package.json or allow for documentation to be imported in the code (manually).

### To Reproduce

```shell
*angular v.14
1. ng new angular-book
2. pnpx storybook@7.0.0-beta.44 init
3. Do you want to use Compodoc for documentation? Yes
4. pnpx run storybook
```

### System

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 AMD Ryzen 7 5800X 8-Core Processor
  Binaries:
    Node: 16.18.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (96.0.1054.62)
  npmPackages:
    @storybook/addon-essentials: ^7.0.0-beta.44 => 7.0.0-beta.44
    @storybook/addon-interactions: ^7.0.0-beta.44 => 7.0.0-beta.44
    @storybook/addon-links: ^7.0.0-beta.44 => 7.0.0-beta.44
    @storybook/angular: ^7.0.0-beta.44 => 7.0.0-beta.44
    @storybook/blocks: ^7.0.0-beta.44 => 7.0.0-beta.44
    @storybook/testing-library: ^0.0.14-next.1 => 0.0.14-next.1
```

### Additional context

works ok with npm

**Comment by shilman** [comment]
Jeepers creepers!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.54 containing PR #21165 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```
