### ISSUE TITLE
[Bug]: Shows an empty args table, no preview, and the story still renders

### ISSUE THREAD

**Issue by sscaff1** [storybookjs/storybook#21030]
### Describe the bug

I'm getting some weird behavior the story is rendering, but it also rendering an empty args table and a no preview notification. See below:

![localhost_6006__path=_story_buttons--basic-usage](https://user-images.githubusercontent.com/1554424/217816777-8951e160-3098-4472-9c62-1087e464a6f7.png)

My story is on the bottom. The story itself is rendering fine and all of the addons work. I'm not sure how to get of the above two sections though. 

I've never run into this before. I have a monorepo setup where each individual package has its own storybook. I'm getting no errors in the console or the terminal. I'm really at a loss for how to fix this issue.

**Comment by shilman** [comment]
Do you a have a reproduction repo you can share? If not, can you create one? See [how to create a repro](https://storybook.js.org/docs/react/contribute/how-to-reproduce). Thank you! 🙏
