### ISSUE TITLE
[Bug]: Getting error  Identifier '__filename' has already been declared while running `storybook dev`

### ISSUE THREAD

**Issue by Garine519** [storybookjs/storybook#21038]
### Getting error  Identifier '__filename' has already been declared while running `storybook dev`

`"vue": "^2.7.14"`
`"vite": "^4.1.1"`

<img width="1138" alt="Screen Shot 2023-02-09 at 3 14 18 PM" src="https://user-images.githubusercontent.com/37899422/217927054-a6b0f2b0-c6aa-4843-a61e-d76bdf0999d2.png">

my main.js file.
```
const { mergeConfig } = require('vite');
module.exports = {
  core: {
    builder: '@storybook/builder-vite',
    disableTelemetry: true,
    previewCsfV3: false
  },
  framework: '@storybook/vue-vite',
  docs: {
    autodocs: true
  },
  stories: ['../src/**/*.stories.mdx', '../src/**/*.stories.@(js|jsx|ts|tsx)'],
  staticDirs: ['../public', '../src/assets'],
  addons: ['@storybook/addon-links', '@storybook/addon-essentials', '@storybook/addon-interactions'],
  features: {
    interactionsDebugger: true, // 👈 Enable playback controls
    previewCsfV3: false
  },
  async viteFinal(config, { configType }) {
    if (configType === 'PRODUCTION') {
    return mergeConfig(config, {
        build: {
          sourcemap: false,
          commonjsOptions: { requireReturnsDefault: false },
        }
      });
    }
    return config;
  }
};
```

### To Reproduce

```shell
https://github.com/Garine519/2.7-js/blob/main/README.md
```

### System

```shell
Environment Info:

  System:
    OS: macOS 12.5
    CPU: (10) x64 Apple M1 Pro
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
  Browsers:
    Chrome: 110.0.5481.77
    Firefox: 109.0.1
    Safari: 15.6
  npmPackages:
    @storybook/addon-actions: ^7.0.0-beta.45 => 7.0.0-beta.45 
    @storybook/addon-backgrounds: ^7.0.0-beta.45 => 7.0.0-beta.45 
    @storybook/addon-docs: ^7.0.0-beta.45 => 7.0.0-beta.45 
    @storybook/addon-essentials: ^7.0.0-beta.45 => 7.0.0-beta.45 
    @storybook/addon-interactions: ^7.0.0-beta.45 => 7.0.0-beta.45 
    @storybook/addon-links: ^7.0.0-beta.45 => 7.0.0-beta.45 
    @storybook/addon-measure: ^7.0.0-beta.45 => 7.0.0-beta.45 
    @storybook/addon-outline: ^7.0.0-beta.45 => 7.0.0-beta.45 
    @storybook/addon-postcss: ^2.0.0 => 2.0.0 
    @storybook/addons: ^7.0.0-beta.45 => 7.0.0-beta.45 
    @storybook/builder-vite: ^7.0.0-beta.45 => 7.0.0-beta.45 
    @storybook/channel-postmessage: ^7.0.0-beta.45 => 7.0.0-beta.45 
    @storybook/channel-websocket: ^7.0.0-beta.45 => 7.0.0-beta.45 
    @storybook/client-api: 7.0.0-beta.45 => 7.0.0-beta.45 
    @storybook/jest: 0.0.11-next.0 => 0.0.11-next.0 
    @storybook/preview-web: 7.0.0-beta.45 => 7.0.0-beta.45 
    @storybook/test-runner: ^0.10.0-next.8 => 0.10.0-next.8 
    @storybook/testing-library: 0.0.14-next.1 => 0.0.14-next.1 
    @storybook/vue: ^7.0.0-beta.45 => 7.0.0-beta.45 
    @storybook/vue-vite: 7.0.0-beta.45 => 7.0.0-beta.45
```

**Comment by shilman** [comment]
@Integrayshaun I think you mentioned that stuff like this can happen when postcss is applied twice. does that make sense given this error and that they are using the `postcss` preset?

**Comment by Integrayshaun** [comment]
@shilman this doesn't look like the same error. While the postcss addon is in their dep list, it's not being registered in addons. Although it should be deleted in case it's causing dependency clashes

**Comment by Garine519** [comment]
found the problem. 
my `tsconfig.json` was causing that weird error.
```
{
    "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"],
      "*": ["node_modules/*"] <--------------------------- 
    },
    "lib": ["esnext", "dom", "dom.iterable", "scripthost"]
  },
}

```

**Comment by Barlow1** [comment]
> found the problem. my `tsconfig.json` was causing that weird error.
> 
> ```
> {
>     "compilerOptions": {
>     "baseUrl": ".",
>     "paths": {
>       "@/*": ["./src/*"],
>       "*": ["node_modules/*"] <--------------------------- 
>     },
>     "lib": ["esnext", "dom", "dom.iterable", "scripthost"]
>   },
> }
> ```

Life saver! Worked for me immediately after hours of trying to uninstall other packages.

**Comment by Juice10** [comment]
For everyone that check their `tsconfig.json` and thinks, 'but I have this, why am I still having the issue', you have to remove `"*": ["node_modules/*"]` to make it work 🤦

> found the problem. my `tsconfig.json` was causing that weird error.
> 
> ```
> {
>     "compilerOptions": {
>     "baseUrl": ".",
>     "paths": {
>       "@/*": ["./src/*"],
>       "*": ["node_modules/*"] <--------------------------- 
>     },
>     "lib": ["esnext", "dom", "dom.iterable", "scripthost"]
>   },
> }
> ```

**Comment by cryp2knight** [comment]
> found the problem. my `tsconfig.json` was causing that weird error.
> 
> ```
> {
>     "compilerOptions": {
>     "baseUrl": ".",
>     "paths": {
>       "@/*": ["./src/*"],
>       "*": ["node_modules/*"] <--------------------------- 
>     },
>     "lib": ["esnext", "dom", "dom.iterable", "scripthost"]
>   },
> }
> ```

omg i was stuck on this issue for a week now. thanks so much!!!

**Comment by sonikasharma1403** [comment]
Facing the same issue.. even tho' i dont have something like that in my tsconfig.json

**Comment by ShunyaWatanabe** [comment]
Facing the same error.
I have this as my tsconfig.json

I don't have `"*": ["node_modules/*"]` in it

```
{
	"compilerOptions": {
		"lib": ["dom", "dom.iterable", "esnext"],
		"allowJs": true,
		"target": "ES6",
		"skipLibCheck": true,
		"strict": true,
		"noEmit": true,
		"esModuleInterop": true,
		"module": "esnext",
		"moduleResolution": "bundler",
		"resolveJsonModule": true,
		"isolatedModules": true,
		"jsx": "preserve",
		"incremental": true,
		"plugins": [
			{
				"name": "next"
			}
		],
		"paths": {
			"@/*": ["./*"]
		}
	},
	"include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
	"exclude": ["node_modules"]
}

```

**Comment by lukebrandonfarrell** [comment]
Downgrade your Vite from 7.x to 5.x and it will fix it:

```json
// package.json

  "overrides": {
    "react": "19.1.0",
    "react-dom": "19.1.0",
    "react-native-web": "^0.21.0",
    "vite": "^5.4.11" <---
  }
```
