### ISSUE TITLE
[Bug]: `sb dev` no longer honors environment variables like `CI` and `SBCONFIG_CONFIG_DIR`

### ISSUE THREAD

**Issue by joshbolduc** [storybookjs/storybook#21055]
### Describe the bug

In Storybook 6.x, `start-storybook` supported environment variables like `CI` and `SBCONFIG_CONFIG_DIR`, which behaved like their equivalent CLI flags. When using `sb dev` with Storybook 7.0 alpha, setting these vars doesn't seem to have any effect.

### To Reproduce

I didn't create a reproduction repo for this issue since it can be reproduced with the unmodified sandbox templates. I tested with the CRA/JS templates, but I assume it applies to all of them.

- Run the command `CI=true yarn storybook`
- With 6.5.16:
  - If port 6006 is taken, a new port is selected without prompting
  - A browser isn't launched
- With 7.0.0-beta.45:
  - If port 6006 is taken, an interactive prompt asks whether to use a different port
  - A browser is launched

Similarly `SBCONFIG_CONFIG_DIR` doesn't seem to be honored with v7, but it is with v6.

### System

```shell
Environment Info:

  System:
    OS: macOS 13.2
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 16.13.1 - ~/.asdf/installs/nodejs/16.13.1/bin/node
    Yarn: 1.22.19 - ~/.asdf/shims/yarn
    npm: 8.1.2 - ~/.asdf/installs/nodejs/16.13.1/bin/npm
  Browsers:
    Firefox: 109.0
    Safari: 16.3
  npmPackages:
    @storybook/addon-essentials: ^7.0.0-beta.45 => 7.0.0-beta.45 
    @storybook/addon-interactions: ^7.0.0-beta.45 => 7.0.0-beta.45 
    @storybook/addon-links: ^7.0.0-beta.45 => 7.0.0-beta.45 
    @storybook/blocks: ^7.0.0-beta.45 => 7.0.0-beta.45 
    @storybook/node-logger: ^7.0.0-beta.45 => 7.0.0-beta.45 
    @storybook/preset-create-react-app: ^4.1.2 => 4.1.2 
    @storybook/react: ^7.0.0-beta.45 => 7.0.0-beta.45 
    @storybook/react-webpack5: ^7.0.0-beta.45 => 7.0.0-beta.45 
    @storybook/testing-library: ^0.0.14-next.1 => 0.0.14-next.1 
```

### Additional context

I didn't see anything in MIGRATION.md about this, so not sure if it's an oversight or if these vars are deprecated with the move from `start-storybook` to `sb`. The normal CLI flags (e.g., `--ci`) seem to work as expected.

I've been using `CI` and `SBCONFIG_CONFIG_DIR` in my VS Code extension when launching the Storybook dev server, since they work well even if users use a custom script to launch Storybook that may or may not pass through CLI args.

**Comment by shilman** [comment]
Good golly!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-rc.7 containing PR #21152 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```
