### ISSUE TITLE
[Bug]: Angular: ControlValueAccessor is always set to null

### ISSUE THREAD

**Issue by jadeen** [storybookjs/storybook#21051]
### Describe the bug

When we create an angular component with ControlValueAccessor, we can't change the value of the control. He always seems to be reset to null. 

The behavior don't appear with the alpha version of storybook 7. 

### To Reproduce

```shell
https://github.com/jadeen/storybook-ngcontrol

there is a test component and the story can be found inside the file button.stories.ts
```

### System

```shell
Environment Info:

  System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  Binaries:
    Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
  Browsers:
    Chrome: 110.0.5481.77
    Firefox: 109.0.1
  npmPackages:
    @storybook/addon-essentials: ^7.0.0-beta.46 => 7.0.0-beta.46 
    @storybook/addon-interactions: ^7.0.0-beta.46 => 7.0.0-beta.46 
    @storybook/addon-links: ^7.0.0-beta.46 => 7.0.0-beta.46 
    @storybook/angular: ^7.0.0-beta.46 => 7.0.0-beta.46 
    @storybook/blocks: ^7.0.0-beta.46 => 7.0.0-beta.46 
    @storybook/testing-library: ^0.0.14-next.1 => 0.0.14-next.1 
```

**Comment by valentinpalkovic** [comment]
@jadeen Could you create a gif/video or explain it a bit more detail in the "How to reproduce" section what you mean? I am not able to follow you and understand the issue.

**Comment by shilman** [comment]
Whoopee!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.52 containing PR #21059 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```

**Comment by jadeen** [comment]
> @jadeen Could you create a gif/video or explain it a bit more detail in the "How to reproduce" section what you mean? I am not able to follow you and understand the issue.

Sorry, I didn't see your message. I have created a component `test` in my library and I use it inside the story `button.stories.ts`
