### ISSUE TITLE
[Bug]: @storybook/addons-storyshots doesn't work with storybook 7.

### ISSUE THREAD

**Issue by jdelStrother** [storybookjs/storybook#21050]
### Describe the bug

I'm trying out v7 beta 45, but can't seem to get snapshots working under jest. I've set `storyStoreV7:false`, but still get this error:

```
 FAIL  webpack/assets/javascripts/components/stories/storybook.test.tsx
  ● Test suite failed to run

    Your test suite must contain at least one test.

      at onResult (node_modules/@jest/core/build/TestScheduler.js:133:18)
      at node_modules/@jest/core/build/TestScheduler.js:254:19
      at node_modules/emittery/index.js:363:13
          at Array.map (<anonymous>)
      at Emittery.emit (node_modules/emittery/index.js:361:23)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        300.813 s
```

Stepping through with the debugger, it looks like `globalWindow.__STORYBOOK_STORY_STORE__.initializationPromise` never gets resolved here - https://github.com/storybookjs/storybook/blob/8c6592ff9da39a9781b62a029884ca831851be6b/code/addons/storyshots-core/src/api/index.ts#L56

I'm aware that snapshots is somewhat deprecated, but given there's a package for @storybook/addon-storyshots@7.0.0-beta45 it seems like it ought to work..?

### To Reproduce

```shell
Checkout https://github.com/jdelStrother/storybook-snapshots
Run `yarn`
Run `yarn jest`
```

### System

```shell
Environment Info:

  System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1 Pro
  Binaries:
    Node: 16.18.1 - /etc/profiles/per-user/jon/bin/node
    Yarn: 1.22.19 - /nix/store/imzxd8mj6airij3v9xh8yddvhzbvvv9n-yarn-1.22.19/bin/yarn
    npm: 8.19.2 - /etc/profiles/per-user/jon/bin/npm
  Browsers:
    Chrome: 109.0.5414.119
    Safari: 16.2
  npmPackages:
    @storybook/addon-essentials: ^6.0 => 6.5.16
    @storybook/addon-interactions: ^6.0 => 6.5.16
    @storybook/addon-links: ^6.0 => 6.5.16
    @storybook/addon-storyshots: ^6.0 => 6.5.16
    @storybook/builder-webpack5: ^6.5.16 => 6.5.16
    @storybook/react: ^6.5.16 => 6.5.16
```
```


### Additional context

_No response_

**Comment by tmeasday** [comment]
Ok, the problem is this line:

https://github.com/storybookjs/storybook/blob/f5d598916ce74b5b0b91456a3e1ad309343d0cdb/code/addons/storyshots-core/src/frameworks/configure.ts#L63

In our latest template (and this example), we export these fields (`stories`, `features`) on the default export. I guess we need to update our test cases to reflect this.

**Comment by shilman** [comment]
Yippee!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.49 containing PR #21097 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```

**Comment by jdelStrother** [comment]
Thanks! Confirming this worked
