### ISSUE TITLE
[Bug]: 'env: node\r: No such file or directory'

### ISSUE THREAD

**Issue by CHE1RON** [storybookjs/storybook#21061]
### Describe the bug

When migrating CSF 2-3 via `npx` script, I get this error (which is most commonly related to Windows line endings):

```
$ npx storybook@next migrate csf-2-to-3 --glob="**/*.stories.tsx"
=> Applying csf-2-to-3: 15 files
env: node\r: No such file or directory
```

### To Reproduce

```shell
Run `$ npx storybook@next migrate csf-2-to-3 --glob="**/*.stories.tsx"`
```

### System

```shell
Ubuntu 22.04, Node v16 & v18
```

**Comment by OlaoluwaM** [comment]
Same here! I'm on MacOS 13.1, Node v16

**Comment by OlaoluwaM** [comment]
So I think I found a solution for this. The issue as @CHE1RON pointed out is the discrepancy between line breaks on Windows and on UNIX, so to solve this, we'll need to find the file that is being executed via `npx` and convert its line breaks from CRLF (Windows) to LF (*NIX). However, this doesn't really work as expected since the actual file being executed is parsed with `jscodeshift`

**Comment by OlaoluwaM** [comment]
Once you have spotted the line that says `npm exec jscodeshift --no-babel -t /Volumes/Sources/bondlink/node_modules/@storybook/codemod/dist/transforms/storiesof-to-csf.js --parser tsx ...` (where '...' refers to all your `.stories` files from the glob you provided) you will need to copy that entire line, replacing `npm exec jscodeshift` with `node node_modules/.bin/jscodeshift`

**Comment by CHE1RON** [comment]
Sounds gread, I'll try it out and let you know!

**Comment by mandarini** [comment]
I am running into the same issue myself!

**Comment by mandarini** [comment]
@OlaoluwaM using `node node_modules/.bin/jscodeshift --no-babel -t ...` makes it work, indeed, for what it's worth! 😅

**Comment by shilman** [comment]
Gadzooks!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.53 containing PR #21180 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```
