### ISSUE TITLE
[Bug]: npm7 migration dumps environmental secrets into migration file

### ISSUE THREAD

**Issue by csidell-guilded** [storybookjs/storybook#21065]
### Describe the bug

When running the npm7 migration for npm v8 the process takes all existing secrets with environment variables and places them in plaintext in .npmrc.

I'm not sure why storybook is trying to interpret the .npmrc file, but it definitely shouldn't be modifying environment variables to be their plaintext variant.

### To Reproduce

```shell
Run the npm7 migration with environment variable references in your .npmrc `${SOME_ENV_VAR}`
```

### System

```shell
Irrelevant, but osx.
```

**Comment by shilman** [comment]
@csidell-guilded can you please clarify the reproduction? do you have a repo we can look at, or a more clear set of steps to follow? thanks! 🙏

**Comment by csidell-guilded** [comment]
@shilman 

Sorry this got lost in my notifications. The repro is just installing storybook with a .npmrc file in the directory with environment variables.

For example if you use fontawesome you'd put this in your .npmrc so that it gets picked up in your local environment (local dev, docker, etc)

    @fortawesome:registry=https://npm.fontawesome.com/
    //npm.fontawesome.com/:_authToken=${FONTAWESOME_TOKEN}

When you get to the step about running the above migration it will attempt to add `legacy-peer-deps=true` to the .npmrc file. In doing so it saves the file with the environment variables dumped in the file instead of leaving those lines untouched. So instead of `${FONTAWESOME_TOKEN}` you'd get `production-fontawesome-token10293`

There really isn't much else in terms of a repro. If you want to know the full flow for the install it's the following

<img width="563" alt="image" src="https://user-images.githubusercontent.com/94870579/221396361-f67bc82e-2b81-4f88-8065-a6fc877a7e2e.png">
