### ISSUE TITLE
[Bug]: Angular Source Snippets render string args incorrectly

### ISSUE THREAD

**Issue by tmeasday** [storybookjs/storybook#21066]
### Describe the bug

[On the latest Angular build on `next`](https://6322ce6af69825592bbb28fc-bodkdxwbnb.chromatic.com/?path=/docs/example-button--docs), open the source snippet:

<img width="355" alt="image" src="https://user-images.githubusercontent.com/132554/218369295-75faecd8-1f1a-48b1-a21e-7c1949ee41e7.png">

Note it should say `label="Primary"`

**Comment by shilman** [comment]
Boo-yah!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-rc.5 containing PR #21609 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```
