### ISSUE TITLE
[Bug]: preview-level parameters not merge with story-level

### ISSUE THREAD

**Issue by unional** [storybookjs/storybook#21092]
### Describe the bug

e.g. in `preview.tsx`:

```ts
export const parameters = {
  darkMode: {
    darkClass: 'my-dark'
  }
}
```

in `MyComp.stories.tsx`:

```ts
export const Playground = {
  parameters: {
    a: 1
  }
}
```

The story-level parameters override the preview-level one.

### To Reproduce

```shell
Please see above for now
```

### System

```shell
Environment Info:

  System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
  Browsers:
    Chrome: 109.0.5414.119
    Firefox: 109.0
    Safari: 16.3
```

### Additional context

Using: Storybook 7.0.0-beta.15 for react-vite

**Comment by shilman** [comment]
Do you a have a reproduction repo you can share? If not, can you create one? See [how to create a repro](https://storybook.js.org/docs/react/contribute/how-to-reproduce). We test parameter merging in various ways in our CI so it would be really surprising to me if this broke. However, if you have a reproduction we'd definitely take a look. Thank you! 🙏

**Comment by unional** [comment]
Should not be too hard to repro. Working on something atm. Will try to create a repro in a few days.
