### ISSUE TITLE
[Bug]:  Could not load stories from Storybook v7.0.0-beta.47 with vue3 + vite in Windows

### ISSUE THREAD

**Issue by sfe-efficy** [storybookjs/storybook#21101]
### Describe the bug

Using Vue3 + Vite for storybook v7.0.0-beta.47 report and error trying to import each story in Windows:

[unplugin-csf] Could not load /src/stories/Button.stories.ts (imported by ../../../../../../../../virtual:/@storybook/builder-vite/storybook-stories.js): ENOENT: no such file or directory, open 'C:\src\stories\Button.stories.ts'

It's ignoring the working directoy, and tries to load the content from C:\ root folder.

### To Reproduce

```shell
https://github.com/storybookjs/sandboxes/tree/next/vue3-vite/default-ts/after-storybook

Using the sandbox configuration as it.
```

### System

```shell
Environment Info:

  System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (110.0.1587.41)
  npmPackages:
    @storybook/addon-essentials: ^7.0.0-beta.47 => 7.0.0-beta.47
    @storybook/addon-interactions: ^7.0.0-beta.47 => 7.0.0-beta.47
    @storybook/addon-links: ^7.0.0-beta.47 => 7.0.0-beta.47
    @storybook/blocks: ^7.0.0-beta.47 => 7.0.0-beta.47
    @storybook/testing-library: ^0.0.14-next.1 => 0.0.14-next.1
    @storybook/vue3: ^7.0.0-beta.47 => 7.0.0-beta.47
    @storybook/vue3-vite: ^7.0.0-beta.47 => 7.0.0-beta.47
```

### Additional context

I'm having the same problem in my project, so I was looking for a sandbox configuration for vue3 +vite for Storybook v7.
I simplily run:
- npm install
- npm build-storybook

**Comment by xander-marjoram** [comment]
I'm getting the same error and managed to pinpoint it down to `7.0.0-beta.45`, 44 works for me.

**Comment by sfe-efficy** [comment]
It's true. The error was introduced here:
https://github.com/storybookjs/storybook/pull/21013

**Comment by sfe-efficy** [comment]
Ok, the problem is related of using posix with a config directory in Win32 format:

At line 17
https://github.com/storybookjs/storybook/pull/21013/files#diff-2863b3fa2d25f11b17809621643879a0efe0d28b9512def8fd6708b6a5eb3875R17

It's using a mix of slashes, options.configDir has a windows format, but pattern is with posix format, so the final result is like:

`src/**/*.mdx`

when it was waiting for something like 

/Users/user.dot.name/folder/storybook-sandboxes/vue3-vite/default-ts/after-storybook/src/**/*.mdx

That's because the options.configDir is `C:\Users\user.dot.name\folder\storybook-sandboxes\vue3-vite\default-ts\after-storybook\.storybook`

**Comment by shilman** [comment]
Instead of using posixPath we should just use `slash` to normalize the paths for our glob processor (I think)

**Comment by xenoxsis** [comment]
It's still a problem in `7.0.0-beta.53`, is it being worked on?

**Comment by sfe-efficy** [comment]
The error still happening:

```
./sb-common-assets/fonts.css doesn't exist at build time, it will remain unchanged to be resolved at runtime
✓ 15 modules transformed.
[unplugin-csf] Could not load /src/stories/Button.stories.ts (imported by ../../../../../../../../virtual:/@storybook/builder-vite/storybook-stories.js): ENOENT: no such file or directory, open 'C:\src\stories\Button.stories.ts'
transforming (320) node_modules\lodash\_baseFindIndex.jsERR! Error: Could not load /src/stories/Button.stories.ts (imported by ../../../../../../../../virtual:/@storybook/builder-vite/storybook-stories.js): ENOENT: no such file 
or directory, open 'C:\src\stories\Button.stories.ts'
```

```

Environment Info:

  System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (110.0.1587.50)
  npmPackages:
    @storybook/addon-essentials: ^7.0.0-beta.47 => 7.0.0-beta.53
    @storybook/addon-interactions: ^7.0.0-beta.47 => 7.0.0-beta.53
    @storybook/addon-links: ^7.0.0-beta.47 => 7.0.0-beta.53
    @storybook/blocks: ^7.0.0-beta.47 => 7.0.0-beta.53
    @storybook/testing-library: ^0.0.14-next.1 => 0.0.14-next.1
    @storybook/vue3: ^7.0.0-beta.47 => 7.0.0-beta.53
    @storybook/vue3-vite: ^7.0.0-beta.47 => 7.0.0-beta.53
```

**Comment by MJB52** [comment]
Also still seeing this issue in 7.0.0-beta.53

**Comment by shilman** [comment]
cc @IanVS

**Comment by gipoezcan** [comment]
@IanVS the bug is already found AFAICT:

@sfe-efficy wrote:

> Ok, the problem is related of using posix with a config directory in Win32 format:
> 
> At line 17 https://github.com/storybookjs/storybook/pull/21013/files#diff-2863b3fa2d25f11b17809621643879a0efe0d28b9512def8fd6708b6a5eb3875R17
> 
> It's using a mix of slashes, options.configDir has a windows format, but pattern is with posix format, so the final result is like:
> 
> `src/**/*.mdx`
> 
> when it was waiting for something like
> 
> /Users/user.dot.name/folder/storybook-sandboxes/vue3-vite/default-ts/after-storybook/src/**/*.mdx
> 
> That's because the options.configDir is `C:\Users\user.dot.name\folder\storybook-sandboxes\vue3-vite\default-ts\after-storybook\.storybook`
> 
> And also, glob still retuning absolute paths from each file in windows format, but the code is waiting a posix format.

It's exactly this change which broke it. I did test reverting that manually simply by changing the installed lib: It does work.

**Comment by IanVS** [comment]
@gipoezcan, it's been suggested to use `slash` more thoroughly when building these URLs.  Would you be interested in trying it out and pushing up a PR?  You can read https://github.com/storybookjs/storybook/blob/next/CONTRIBUTING.md for some tips to get started if you haven't worked in the Storybook repo before, but it is pretty straightforward.  I'm happy to also provide support either here or on discord.gg/storybook.  (I'm `@IanVS` there as well).

**Comment by gipoezcan** [comment]
@IanVS sure of course, thanks for the offer, let me try

**Comment by gipoezcan** [comment]
@IanVS I opened a PR, tests seem to pass. With that change they pass on Windows as well :) This is the first time I've ever touched yarn so took a bit setting up then a long time to realize the lint check failed. Well, all is fixed now, at least AFAICT

**Comment by shilman** [comment]
Jiminy cricket!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.59 containing PR #21305 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```

**Comment by gipoezcan** [comment]
I upgraded to the beta.59 and both the dev and the build commands worked without errors. Thanks for the fast merge!
