### ISSUE TITLE
[Bug]: Docs styles missing after update to Storybook 6.5.16

### ISSUE THREAD

**Issue by luis-pato** [storybookjs/storybook#21118]
### Describe the bug

After updating from Storybook 6.5.15 to Storybook 6.5.16 (for Web-Components) the `sbdocs...` classes are missing from all docs pages (all written in mdx).

Before the update a `# some text` headline would be:
```html
<h1 class="sbdocs sbdocs-h1 css-1wtt4d1">some text</h1>
```

After the update
```html
<h1>some text</h1>
```

I still see some `sbdocs` classes, namely:
```html
<div class="sbdocs sbdocs-wrapper css-o0g98q">
    <div class="sbdocs sbdocs-content css-1gh4yjl">
        <!-- every element inside the sbdocs-content has no sbdocs classes at all -->
    </div>
</div>
```

### System

```shell
Environment Info:

  System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 19.4.0 - ~/.nvm/versions/node/v19.4.0/bin/node
    npm: 9.4.0 - ~/Sites/toujou-2-storybook/node_modules/.bin/npm
  Browsers:
    Chrome: 109.0.5414.119
    Firefox: 110.0
    Safari: 16.2
  npmPackages:
    @storybook/addon-a11y: ^6.5.16 => 6.5.16 
    @storybook/addon-actions: ^6.5.16 => 6.5.16 
    @storybook/addon-controls: ^6.5.16 => 6.5.16 
    @storybook/addon-docs: ^6.5.16 => 6.5.16 
    @storybook/addon-essentials: ^6.5.16 => 6.5.16 
    @storybook/addon-links: ^6.5.16 => 6.5.16 
    @storybook/addons: ^6.5.16 => 6.5.16 
    @storybook/builder-vite: ^0.4.2 => 0.4.2 
    @storybook/theming: ^6.5.16 => 6.5.16 
    @storybook/web-components: ^6.5.16 => 6.5.16
```

### Additional context

I have tried deleting the node_modules folder, clearing npm cache and then installing everything again. No change

**Comment by luis-pato** [comment]
I still haven't found a solution for this problem. Maybe someone has an idea...

**Comment by william-p** [comment]
Same issue here, i found a workaround with downgrade `@storybook/builder-vite` to `0.3` branch:

    "@storybook/builder-vite": "^0.3.0"

**Comment by luis-pato** [comment]
> Same issue here, i found a workaround with downgrade `@storybook/builder-vite` to `0.3` branch:

Thank you. That did solve the problem!

**Comment by jimmynotjim** [comment]
Downgrading isn't a long term solution. Anyone know if this is being tracked elsewhere? Otherwise can it be reopened?
