### ISSUE TITLE
[Bug]: The `Primary` doc block in an attached MDX file shows invalid code preview

### ISSUE THREAD

**Issue by elisehein** [storybookjs/storybook#21125]
### Describe the bug

I'm seeing invalid code previews when using the `Primary` doc block and clicking "Show code":

```jsx
import {
  Meta,
  Primary,
} from "@storybook/blocks";

import * as ButtonStories from "./Button.stories.js";

<Meta of={ButtonStories} />

<Primary />
```

<img width="381" alt="CleanShot 2023-02-16 at 15 52 42@2x" src="https://user-images.githubusercontent.com/604621/219383321-b6e02346-db19-4605-82d3-20df19bf0b0f.png">

When relying on autodocs, the docs page generated for each component shows the correct JSX in the code preview. But when I add an MDX file and attach that file to a component using the `Meta` block, none of the code previews work (the example above is for the `Primary` block, but I'm also seeing the same error on the `Canvas` block when using `<Canvas of={ButtonStories.Primary} />`).

### To Reproduce

See reproduction repo: https://github.com/elisehein/storybook7-primary-block-code-preview

See README for steps to reproduce, or have a look at the problematic file https://github.com/elisehein/storybook7-primary-block-code-preview/blob/main/src/stories/Button.mdx?plain=1

The repro was created using `npx sb@next init`

### System

```shell
Environment Info:

  System:
    OS: macOS 12.6.3
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 16.17.1 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.15.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 110.0.5481.96
    Firefox: 109.0.1
    Safari: 15.6.1
  npmPackages:
    @storybook/addon-essentials: ^7.0.0-beta.47 => 7.0.0-beta.47
    @storybook/addon-interactions: ^7.0.0-beta.47 => 7.0.0-beta.47
    @storybook/addon-links: ^7.0.0-beta.47 => 7.0.0-beta.47
    @storybook/blocks: ^7.0.0-beta.47 => 7.0.0-beta.47
    @storybook/react: ^7.0.0-beta.47 => 7.0.0-beta.47
    @storybook/react-webpack5: ^7.0.0-beta.47 => 7.0.0-beta.47
    @storybook/testing-library: ^0.0.14-next.1 => 0.0.14-next.1
```

### Additional context

In my own codebase I was able to fix one particular instance of this by replacing `const Default = {}; export { Default as ComponentName }` in my stories file with `export const Default = {}`. (See [Discord](https://discord.com/channels/486522875931656193/1075399365004361798/1075399365004361798)) I wasn't able to reproduce this here.

**Comment by tmeasday** [comment]
@ndelangen I think this is a bundling issue. I see two copies of the blocks package in the webpack build, in files:
 - `vendors-node_modules_mdx-js_react_lib_index_js-node_modules_storybook_blocks_dist_index_mjs.iframe.…`
 - `vendors-node_modules_storybook_addon-essentials_dist_actions_preview_js-node_modules_storyboo-cd2af…`

I think the second file is accessed when you import `@storybook/blocks` from an MDX file. I think this means there are two `SourceContainer`s, which means the `Source` block gets the wrong one (and thus it is empty).

**Comment by ndelangen** [comment]
@elisehein I think you likely haven't pushed all files to the remote.
Your repro won't start for me.

```
(main) % npm install                                                                                                                                                                                                                 ~/Projects/GItHub/repros/storybook7-primary-block-code-preview

added 1037 packages, and audited 1038 packages in 37s

176 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
(main)⚡ % npm run storybook                                                                                                                                                                                                         ~/Projects/GItHub/repros/storybook7-primary-block-code-preview

> test-storybook-init@1.0.0 storybook
> storybook dev -p 6006

@storybook/cli v7.0.0-beta.47

Error: No configuration files have been found in your configDir (/Users/me/Projects/GitHub/repros/storybook7-primary-block-code-preview/.storybook).
Storybook needs "main.js" file, please add it.
    at validateConfigurationFiles (/Users/me/Projects/GitHub/repros/storybook7-primary-block-code-preview/node_modules/@storybook/core-common/dist/index.js:9:30)
(main)⚡ [1] %                                                                                                                                                                                                                       ~/Projects/GItHub/repros/storybook7-primary-block-code-preview
```

There is no `.storybook` dir..

**Comment by elisehein** [comment]
@ndelangen apologies, should be fixed now.

**Comment by ndelangen** [comment]
this is strange: `vendors-node_modules_mdx-js_react_lib_index_js-node_modules_storybook_blocks_dist_index_mjs.iframe.…
`

because `@mdx-js/react` doesn't have a dependency on `@storybook/block`..

I was also able to reproduce this ensuring there's only 1 version of the package installed.

**Comment by ndelangen** [comment]
I found the bug!
Will open a PR soon 🎉

**Comment by shilman** [comment]
Ooh-la-la!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.53 containing PR #21161 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```

**Comment by elisehein** [comment]
Confirming that this is fixed in 7.0.0-rc3 when I upgrade in the reproduction repo. Unfortunately this hasn't fixed the issue for me in my actual codebase, and I'm unable to figure out what is causing it 🤔

**Comment by tmeasday** [comment]
@elisehein, hmm, that's frustrating! Maybe can you see if the same root issue is going on in your repo? If you open Dev tools and search for `SourceContainer`, do you get more than one file?

<img width="894" alt="image" src="https://user-images.githubusercontent.com/132554/225098401-2deaf9f9-4283-4684-b2ae-0fe3868620f0.png">

**Comment by elisehein** [comment]
@tmeasday Thanks for the tip, this is what my search results show:

<img width="1578" alt="CleanShot 2023-03-15 at 09 14 07@2x" src="https://user-images.githubusercontent.com/604621/225235968-92abb76f-e339-403e-b662-631e0a90b009.png">

It's all index.mjs from @storybook/blocks like yours but I don't know why I get that three times 🤔 

This is after purging node_modules, yarn.lock, and a fresh install, the version is definitely rc3.

**Comment by tmeasday** [comment]
Ok, looks like it likely is the same proximate issue @elisehein. Can you run `yarn why` (or look in `node_modules`) and see if `@storybook/blocks` is installed more than once? It looks like each of those (3!) entries is an `.mjs` file, so if I am reading it correctly it isn't the same problem as the one we had fixed in https://github.com/storybookjs/storybook/pull/21161, even if the symptom was the same.

**Comment by elisehein** [comment]
@tmeasday Here's the output from `yarn why`

```
yarn why v1.22.19
[1/4] 🤔  Why do we have the module "@storybook/blocks"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "@storybook/blocks@7.0.0-rc.3"
info Has been hoisted to "@storybook/blocks"
info Reasons this module exists
   - Specified in "devDependencies"
   - Hoisted from "@storybook#addon-essentials#@storybook#addon-controls#@storybook#blocks"
   - Hoisted from "@storybook#addon-essentials#@storybook#addon-docs#@storybook#blocks"
info Disk size without dependencies: "976KB"
info Disk size with unique dependencies: "28.01MB"
info Disk size with transitive dependencies: "79.8MB"
info Number of shared dependencies: 143
✨  Done in 0.58s.
```

**Comment by tmeasday** [comment]
Hmm, I'm puzzled by that bundling then. Do you have a custom `webpackFinal` in `main.js`?

@ndelangen do you have any ideas here? TLDR: @elisehein has only a single copy of `@storybook/blocks` but it seems to be in 3 seperate webpack chunks.

**Comment by elisehein** [comment]
@tmeasday I do in fact have a custom `webpackFinal`, apologies, I should have included that straight away:

```js
  webpackFinal: async (config, { configType }) => {
    config.stats = "none";

    // Needed to build Iconoir
    // See https://github.com/storybookjs/storybook/issues/16690#issuecomment-971579785
    config.module.rules.push({
      test: /\.mjs$/,
      include: /node_modules/,
      type: "javascript/auto",
    });

    return config;
  },
```

But removing it does not fix the code preview issue still :( And removing it doesn't change the output of `yarn why`.

To clarify, code previews are working in auto-generated docs pages, it's only when I have a custom .mdx file and use `Primary` or `Canvas` that they break. The `Primary` block just shows a copy of the story in CSF3 format:

<img width="303" alt="CleanShot 2023-03-17 at 10 29 08@2x" src="https://user-images.githubusercontent.com/604621/225852806-368deb39-867a-40ea-9e8b-10e7cc5b6cfe.png">

Trying out rc4 just now I also noticed that code previews also break on auto-generated docs pages where they were working fine on beta47. I get the dreaded `<No Display Name />`.

<img width="245" alt="CleanShot 2023-03-17 at 10 33 30@2x" src="https://user-images.githubusercontent.com/604621/225854094-be6b9538-6b08-4708-963b-d07236dbabb4.png">

**Comment by tmeasday** [comment]
> @tmeasday I do in fact have a custom webpackFinal, apologies, I should have included that straight away:

No worries, I don't think it's the problem here.

> BUT trying out rc4 just now I'm seeing that code previews also break on auto-generated docs pages where they were working fine on beta47. I get the dreaded <No Display Name />, so this is a regression for me.

The `<No Display Name />` issue is something else: https://github.com/storybookjs/storybook/issues/21649, I don't think it's related to the problem you are seeing with "raw" snippets here. We'll sort it out soon but I imagine the other problem will recur.

I'm hoping @ndelangen might have some ideas as to why `@storybook/blocks` get rendered more than once.

**Comment by ndelangen** [comment]
@elisehein is this repro repo up to date with those changes?
[elisehein/storybook7-primary-block-code-preview](https://github.com/elisehein/storybook7-primary-block-code-preview)

I can investigate why you seem to be getting the find the same code 3 times.

**Comment by elisehein** [comment]
@ndelangen unfortunately not, as upgrading to rc3 fixes it in the repro. I haven't been able to reproduce the issue in isolation, I'm seeing it on my own codebase with both beta47 and rc3 (and 4).

**Comment by ndelangen** [comment]
@elisehein and you're sure that in that situation it's only installed once?

Might there be anything going on with symlinks or anything like that?
Can you find out what file-paths the multiple instances are from?
