### ISSUE TITLE
[Bug]: Custom toolbar annotation switches between 2 states indefinitely

### ISSUE THREAD

**Issue by RunDevelopment** [storybookjs/storybook#21131]
### Describe the bug

I followed [the guide here](https://storybook.js.org/docs/7.0/react/essentials/toolbars-and-globals#global-types-and-the-toolbar-annotation) and added the following to my `preview.ts`:

```ts
export const globalTypes = {
  theme: {
    name: 'Theme',
    description: 'Global theme for components',
    defaultValue: 'light',
    toolbar: {
      icon: 'circlehollow',
      // Array of plain string values or MenuItem shape (see below)
      items: ['light', 'dark'],
      // Property that specifies if the name of the item will be displayed
      showName: true,
      // Change title based on selected value
      dynamicTitle: true,
    },
  },
};
```

This is intended to be a simple why to switch between light mode and dark mode to test how components look. 

![image](https://user-images.githubusercontent.com/20878432/219436513-cb7078bb-46ba-4d95-9620-a9f8a1fffc35.png)

This does work as intended most of the time, but it sometimes get stuck when changing the value. It will constantly reload the page, which seems to reset the global to its previous state only for it to be changed again. This makes the site unusable and requires a full reload to fix.

Note that I do not currently do anything with the global. There are no decorators or anything that reads any globals or context, so I can exclude any of my stories to be the source of the bug.

### To Reproduce

https://github.com/OpenModelDB/open-model-database

Not a special reproduction repo, but the repo where the bug occurrs. It's a fresh installation of SB following the NextJS installation path.

### System

```shell
Environment Info:

  System:
    OS: Windows 10 10.0.19045
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz    
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.1.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 110.0.5481.97
    Edge: Spartan (44.19041.1266.0), Chromium (109.0.1518.78)
  npmPackages:
    @storybook/addon-essentials: ^7.0.0-beta.49 => 7.0.0-beta.49
    @storybook/addon-interactions: ^7.0.0-beta.49 => 7.0.0-beta.49
    @storybook/addon-links: ^7.0.0-beta.49 => 7.0.0-beta.49
    @storybook/blocks: ^7.0.0-beta.49 => 7.0.0-beta.49
    @storybook/nextjs: ^7.0.0-beta.49 => 7.0.0-beta.49
    @storybook/react: ^7.0.0-beta.49 => 7.0.0-beta.49
    @storybook/testing-library: ^0.0.14-next.1 => 0.0.14-next.1
```

**Comment by tannera** [comment]
Getting the same error here, makes the docs page in SB7 currently unusable with any custom controls.

**Comment by tmeasday** [comment]
@RunDevelopment is there a particular browser you see the behaviour in? 

What I am seeing here (in Chrome) is when you change theme it sometimes reloads the whole iframe, (although it doesn't always, and it doesn't get "stuck" as you describe). Doesn't seem ideal in any case.

> Note that I do not currently do anything with the global. There are no decorators or anything that reads any globals or context, so I can exclude any of my stories to be the source of the bug.

Hmm, this is not quite true, you do this:

https://github.com/OpenModelDB/open-model-database/blob/545c4ba9773ce2f3b2c3cdea03b42810ac5ef656/.storybook/preview.ts#L37

When I comment that out, or put it in a `setTimeout(..., 0)` the problem goes away. It's a bit odd. Can you tell me any thing else about what that `dataset` is used for?

**Comment by RunDevelopment** [comment]
Huh, I can't reproduce it anymore. Well, that's good, I guess?

> Hmm, this is not quite true, you do this:

True, but at the time, the decorator didn't matter. The bug occurred even with the decorator removed. I simply got a little lazy with the reproduction repo. Sorry for the confusion.

> Can you tell me any thing else about what that `dataset` is used for?

We do theming (well, dark mode vs light mode) using a `data-theme` attribute on `<body>`. `dataset` is just used a convenient way to set this attribute.

**Comment by tmeasday** [comment]
So setting `dataset` doesn't trigger any code to run? And there's no code in the component or another decorator that reads that theme and (somehow) reloads the page because of it?

Are you seeing the behaviour I saw where the iframe reloads (you can notice a bunch of requests including `iframe.html`) when you switch theme? I definitely saw a difference where that wouldn't happen if the decorator was disabled.

**Comment by RunDevelopment** [comment]
> So setting `dataset` doesn't trigger any code to run?

No, `data-theme` is only read by our CSS styles.

> Are you seeing the behaviour I saw where the iframe reloads (you can notice a bunch of requests including `iframe.html`) when you switch theme?

Yes, I see that too, but it's also happening when I removed the decorator.

For reference: When I test out different configuration (e.g. with or without decorator), I always manually restart storybook. So no configs should carry over.
