### ISSUE TITLE
[Bug]: Warning: Attempted to synchronously unmount a root while React was already rendering

### ISSUE THREAD

**Issue by Guilherme-Jesus** [storybookjs/storybook#21136]
### Describe the bug

When switching between items, Storybook displays an error message that says "Warning: Attempted to synchronously unmount a root while React was already rendering. React cannot finish unmounting the root until the current render is complete, which may lead to a race condition." This message indicates that there is a problem in the code that is trying to unmount a component while React is still rendering another component, which could lead to a run condition and cause issues.

To fix this issue, we suggest checking the code of the component causing the error and making sure there are no attempts to unmount a component while React is rendering another component. One possible solution is to use useEffect with an empty dependency to ensure that the code is executed only after rendering is complete. Another option is to move the disassembly code to another location in the component's lifecycle.

This issue can affect the usability of the Storybook and therefore it is important to fix it as soon as possible. Any help resolving this issue will be greatly appreciated. In Storybook version 7.0.0-beta.49

### To Reproduce

private repository

### System

```shell
chunk-6ZDUWZXD.js?v=48af8df4:521 Warning: Attempted to synchronously unmount a root while React was already rendering. React cannot finish unmounting the root until the current render has completed, which may lead to a race condition.
```

**Comment by shilman** [comment]
closing as dupe to #20731
