### ISSUE TITLE
[Feature Request]: storybook-build watch mode 

### ISSUE THREAD

**Issue by abdo99989** [storybookjs/storybook#21130]
### Is your feature request related to a problem? Please describe

In some scenarios we need to serve the static build of story in our custom server in watch mode 

It's an easy feature to add, can you implement it? 

Thanks!  

### Describe the solution you'd like

the command will look like this 
```
storybook-build --watch
```

or 

```
storybook-build -w
```

### Are you able to assist to bring the feature to reality?

no

**Comment by abdo99989** [comment]
If there's a workaround it will be much appreciated

**Comment by shilman** [comment]
closing as dupe to #15946 please upvote
