### ISSUE TITLE
[Bug]: @types/storybook__react outdated

### ISSUE THREAD

**Issue by y-a-v-a** [storybookjs/storybook#21133]
### Describe the bug

I am trying to create a very shallow Docker image for my NextJS app.
When building NextJS, it does type checking.
It fails on my `*.stories.tsx` files because `@storybook/react` is a devDependency.
I only need types for type checks, I don't want `@storybook/react` in my Docker image. Too many dependencies.
`@types/storybook__react` is 3 years old and says I don't need it. But I don't want `@storybook/react`.
How can I fix this?
Maybe best approach is, as NextJS suggests, to separate stories like in https://github.com/vercel/next.js/tree/canary/examples/with-storybook ?
Cheers Vincent

### System

```shell
Macbook pro
nodejs 18
```

**Comment by shilman** [comment]
Storybook ships its own types and won't be updating definitely typed.

**Comment by y-a-v-a** [comment]
Oh bummer. Can I extract its types into my project so my `yarn install` will only install the types?
I guess not - so I will remove all my `*.stores.tsx` files into its own subtree outside of my components library - as NextJS also does in their Storybook example - in order to mitigate type checking errors during next's build time, as I want my Docker image as shallow as possible.
