### ISSUE TITLE
[Bug]: hot reload not working on create-react-app or create-next-app

### ISSUE THREAD

**Issue by mehm8128** [storybookjs/storybook#21151]
### Describe the bug

When I make my react or next.js project by using `create-react-app` or `create-next-app`, hot reload doesn't work, but I observed that on the react project using vite, it works well.

### To Reproduce

1. `npx sb@next sandbox`(choose `Create React App (Typescript)` and `Next.js (TypeScript)`)
1. move directory
1. `yarn`
1. `yarn storybook`
1. make a change on button component or other components
1. changed component doesn't update its appearance automatically
1. when I reload the page, component updates its appearance

### System

create-react-app
```shell
Environment Info:

  System:
    OS: Linux 5.4 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
  Binaries:
    Node: 16.14.2 - ~/.nodenv/versions/16.14.2/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.5.0 - ~/.nodenv/versions/16.14.2/bin/npm
  npmPackages:
    @storybook/addon-essentials: ^7.0.0-beta.47 => 7.0.0-beta.50
    @storybook/addon-interactions: ^7.0.0-beta.47 => 7.0.0-beta.50
    @storybook/addon-links: ^7.0.0-beta.47 => 7.0.0-beta.50
    @storybook/blocks: ^7.0.0-beta.47 => 7.0.0-beta.50
    @storybook/node-logger: ^7.0.0-beta.47 => 7.0.0-beta.50
    @storybook/preset-create-react-app: ^4.1.2 => 4.1.2
    @storybook/react: ^7.0.0-beta.47 => 7.0.0-beta.50
    @storybook/react-webpack5: ^7.0.0-beta.47 => 7.0.0-beta.50
    @storybook/testing-library: ^0.0.14-next.1 => 0.0.14-next.1
```

next.js
```shell
Environment Info:

  System:
    OS: Linux 5.4 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
  Binaries:
    Node: 16.14.2 - ~/.nodenv/versions/16.14.2/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.5.0 - ~/.nodenv/versions/16.14.2/bin/npm
  npmPackages:
    @storybook/addon-essentials: ^7.0.0-beta.47 => 7.0.0-beta.50
    @storybook/addon-interactions: ^7.0.0-beta.47 => 7.0.0-beta.50
    @storybook/addon-links: ^7.0.0-beta.47 => 7.0.0-beta.50
    @storybook/blocks: ^7.0.0-beta.47 => 7.0.0-beta.50
    @storybook/nextjs: ^7.0.0-beta.47 => 7.0.0-beta.50
    @storybook/react: ^7.0.0-beta.47 => 7.0.0-beta.50
    @storybook/testing-library: ^0.0.14-next.1 => 0.0.14-next.1
```

**Comment by shilman** [comment]
Hi @mehm8128 I just tried this and couldn't repro on my machine. Do you have a repro repo you can share?

**Comment by mehm8128** [comment]
Sorry, this issue could be my environment's problem.
I'll investigate by myself.
But [this repository(this branch)](https://github.com/mehm8128/mehm8128-study-client/tree/feat/add-stories) is example for this issue.

**Comment by mehm8128** [comment]
Sorry, it has been fixed automatically, and it could be my PC's problem.
I'll close this issue.

**Comment by Loic57** [comment]
Same issue here --> https://github.com/storybookjs/storybook/issues/22124
