### ISSUE TITLE
[Bug]: Unable to debug source-mapped Angular source code in browser

### ISSUE THREAD

**Issue by ghost** [storybookjs/storybook#21171]
### Describe the bug

We have a NX monorepo where we have an Angular library along with a Storybook that we use to develop and demo it.

Everything is working as expected except that our library code does not seem to be source-mapped correctly when using the browser tools to debug a story. This means when we go to debug an issue we see a transpiled version of our component code.

Here a screenshot of the source we see in dev tools for an Angular library component:

<img width="644" alt="Screen Shot 2023-02-20 at 1 50 17 PM" src="https://user-images.githubusercontent.com/69214148/220196620-92082c8e-ab40-49b4-a1da-dec6ca2ce82a.png">

This is a transpiled version of our code - while more helpful than nothing, this feels like a symptom of something wrong.

When I do the same thing with a NX monorepo with a react library (using WebPack) I do see the original TSX code:

<img width="498" alt="Screen Shot 2023-02-20 at 1 59 52 PM" src="https://user-images.githubusercontent.com/69214148/220197732-19e96ee0-e113-49cf-9142-7d4df5428888.png">

### To Reproduce

This repository contains a default a library and storybook integration via NX. I don't think there is anything NX specific about the problem but was the easiest way for me to bootstrap an example.

https://github.com/ta-reesemclean/storybook-angular-debugger

Download the repo and the run the instructions given in the readme.

### System

```shell
Environment Info:

  System:
    OS: macOS 12.5
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 16.18.0 - ~/.nvm/versions/node/v16.18.0/bin/node
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.0/bin/npm
  Browsers:
    Chrome: 110.0.5481.100
    Firefox: 109.0
    Safari: 15.6
  npmPackages:
    @storybook/addon-essentials: ^6.5.15 => 6.5.16 
    @storybook/angular: ^6.5.15 => 6.5.16 
    @storybook/builder-webpack5: ^6.5.15 => 6.5.16 
    @storybook/core-server: ^6.5.15 => 6.5.16 
    @storybook/manager-webpack5: ^6.5.15 => 6.5.16 
    @storybook/source-loader: ^6.5.16 => 6.5.16
```

### Additional context

Willing to contribute but would need an idea of where we would need to start to look to address.

(Adding for more context of why this is an issue for us. Beyond dev tools, this has become an issue as we have tried to add code coverage of our e2e tests through Playwright. We get code coverage results for the transpiled code instead of the original source - I believe if we solve the issue above we will be able to make more progress on this.)

**Comment by shilman** [comment]
Have you tried upgrading to 7.0 to see if the problem is solved there? We're pretty far along and will be going to RC soon

Migration guide: https://storybook.js.org/migration-guides/7.0

**Comment by ta-reesemclean** [comment]
After updating to 7.0.0-beta.52 we are seeing the exact same behavior so does not look like the problem is solved there.

**Comment by ta-reesemclean** [comment]
Here is a branch with the upgrade to 7.0: https://github.com/ta-reesemclean/storybook-angular-debugger/tree/storybook_7

## Environment Info:

  System:
    OS: macOS 12.5
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
    npm: 8.19.3 - ~/.nvm/versions/node/v18.13.0/bin/npm
  Browsers:
    Chrome: 110.0.5481.100
    Firefox: 109.0.1
    Safari: 15.6
  npmPackages:
    @storybook/addon-essentials: ^7.0.0-beta.53 => 7.0.0-beta.53 
    @storybook/angular: ^7.0.0-beta.53 => 7.0.0-beta.53 
    @storybook/core-server: ^7.0.0-beta.53 => 7.0.0-beta.53 
    @storybook/source-loader: ^7.0.0-beta.53 => 7.0.0-beta.53

**Comment by valentinpalkovic** [comment]
@ndelangen any clue what’s going on here? Are even source maps (inline or external) generated per default?

**Comment by ta-reesemclean** [comment]
> @ndelangen any clue what’s going on here? Are even source maps (inline or external) generated per default?

For what its worth - in the Angular project tsconfig.json, setting either inline and non-inline source maps does not change the outcome here.

**Comment by ndelangen** [comment]
I think this might be the setting you're looking for:
https://github.com/storybookjs/storybook/blob/84f5f3b6108cf2c5e000e2bd3248aaba38c90e05/code/lib/builder-webpack5/src/preview/iframe-webpack.config.ts#L207

**Comment by ta-reesemclean** [comment]
Initial findings when playing around with that (though please verify that how I tested actually did anything) - I did not see a difference in changing this to different dev tool values...

The way I tested was to just modify `node_modules/@storybook/builder-webpack5/dist/presets/preview-preset.js` and `node_modules/@storybook/builder-webpack5/dist/presets/preview-preset.mjs` and changing the value directly and then rebuilding.

Because in a React project I can see source-mapped tsx files, I would have expected the problem to in an Angular specific part of the codebase.
