### ISSUE TITLE
[Bug]: HTML and Lit CLI templates for Typescript generate Javascript stories instead

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#21179]
### Describe the bug

I detected a [regression](https://github.com/storybookjs/sandboxes/commit/0cd7939bddd9eb3993d27c1592b65c0fd4d40560) in the sandbox repository:
![image](https://user-images.githubusercontent.com/1671563/220305596-5c3d21e8-85ef-457d-b730-5e112170bf93.png)

Here are the templates which should contain ts stories:
[HTML-ts](https://github.com/storybookjs/sandboxes/tree/next/html-vite/default-ts/after-storybook/src/stories)
[Lit-ts](https://github.com/storybookjs/sandboxes/tree/next/lit-vite/default-ts/after-storybook/src/stories)

**Comment by shilman** [comment]
Yowza!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-rc.6 containing PR #21647 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```
