### ISSUE TITLE
[Bug]: Angular lifecycle hook ngOnDestroy not invoked when switching between stories in Storybook 7

### ISSUE THREAD

**Issue by unitario** [storybookjs/storybook#21198]
### Describe the bug

When going from one story (containing a single component) to another I expect that both `ngOnInit` and `ngOnDestroy` are invoked every time I enter and leave the story, or that `ngOnInit` is invoked the first time you enter the story and then never again.

Currently `ngOnInit` is invoked every time I enter a story but not `ngOnDestroy`, this is a problem in Angular since it is common to create RxJS subscriptions on component initialization and then unsubscribe from these when the component is destroyed. Since `ngOnDestroy` is not invoked that leads to multiple subscriptions being created but destroyed causing memory leakage and performance problems.

This video illustrates the problem:

https://user-images.githubusercontent.com/9481000/220566502-ec1b7bde-19cf-4eff-8115-97affa9d911f.mov

### To Reproduce

https://github.com/unitario/storybook-not-destroyed

### System

```shell
Environment Info:

  System:
    OS: macOS 13.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
  Binaries:
    Node: 16.14.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.12.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 110.0.5481.100
    Safari: 16.2
  npmPackages:
    @storybook/addon-essentials: ^7.0.0-beta.47 => 7.0.0-beta.53 
    @storybook/addon-interactions: ^7.0.0-beta.47 => 7.0.0-beta.53 
    @storybook/addon-links: ^7.0.0-beta.47 => 7.0.0-beta.53 
    @storybook/angular: ^7.0.0-beta.47 => 7.0.0-beta.53 
    @storybook/blocks: ^7.0.0-beta.47 => 7.0.0-beta.53 
    @storybook/testing-library: ^0.0.14-next.1 => 0.0.14-next.1
```

### Additional context

src/app/app.component.ts

```typescript
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-root',
  template: "{{ type }}",
  styles: []
})
export class AppComponent {
  @Input() type: string = "";
  ngOnInit() {
    console.log("ngOnInit")
  }
  ngOnDestroy() {
    console.log("ngOnDestroy")
  }
}
```
src/app/app.stories.ts

```typescript
import type { Meta, StoryObj } from '@storybook/angular';
import { AppComponent } from './app.component';

const meta: Meta<AppComponent> = {
  title: 'AppComponent',
  component: AppComponent,
  tags: ['autodocs'],
};

export default meta;
type Story = StoryObj<AppComponent>;

export const Primary: Story = {
  args: {
    type: "Primary",
  },
};

export const Secondary: Story = {
  args: {
    type: "Secondary",
  },
};
```

**Comment by shilman** [comment]
Huzzah!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.54 containing PR #21219 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```
