### ISSUE TITLE
[Bug]: Automigrating SvelteKit projects fail because of wrong package name

### ISSUE THREAD

**Issue by JReinhold** [storybookjs/storybook#21209]
### Describe the bug

Recent changes to the `newFrameworks` automigration introduced in https://github.com/storybookjs/storybook/pull/20647 causes the automigrating SvelteKit projects to fail. (They will first fail because of #21208, but after fixing that manually, they will fail with this issue).

The automigration mixes up `@storybook/sveltekit` with `@storybook/svelte-kit` most places, causing it to try to install the non-existing `@storybook/svelte-kit` package.

- [ ] Change `@storybook/svelte-kit` to `@storybook/sveltekit` everywhere
- [ ] Change "Svelte kit" to SvelteKit" everywhere

**Comment by shilman** [comment]
Gadzooks!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.54 containing PR #21210 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```
