### ISSUE TITLE
[Bug]: exprect()ToBeInTheDocument throws a TypeScript error as if it didn't exist in @storybook/jest

### ISSUE THREAD

**Issue by santiagopuentep** [storybookjs/storybook#21211]
### Describe the bug

The function works but TypeScript doesn't find the types for jest-dom functions in the `@storybook/jest package`.

### To Reproduce

To reproduce, install the `@storybook/jest` package, import expect and try to call `expect(someElement).toBeInTheDocument()`. TypeScript says `toBeInTheDocument` doesn't exist, but it does (the code works).

### System

```shell
The command doesn't work because I'm using node 14.
```

**Comment by shilman** [comment]
closing as duplicate to https://github.com/storybookjs/jest/issues/21
