### ISSUE TITLE
[Bug]: Angular missing environment providers on module import in 7.0.0-beta.52

### ISSUE THREAD

**Issue by AE1NS** [storybookjs/storybook#21218]
### Describe the bug

Example (global decorator in preview.ts):
```
import { Decorator, moduleMetadata } from '@storybook/angular';
import { APP_INITIALIZER } from '@angular/core';
import { TranslateModule, TranslateService } from '@ngx-translate/core';

export const decorators: Decorator[] = [
    moduleMetadata({
        imports: [TranslateModule.forRoot()],
        providers: [
            {
                provide: APP_INITIALIZER,
                useFactory: (translateService: TranslateService) => () => {
                    console.log(translateService.instant('TEST'));
                },
                deps: [TranslateService],
                multi: true,
            },
        ],
    }),
];
```

`NullInjectorError: No provider for TranslateService!`

**Comment by valentinpalkovic** [comment]
@sheriffMoose Would you like to take a look?

**Comment by sheriffMoose** [comment]
@valentinpalkovic I just verified, the error doesn't show on the sandbox under beta.53.
@AE1NS can you please provide a reproduction repo?

**Comment by AE1NS** [comment]
Working in 7.0.0-beta.53. Thanks!

**Comment by 87Dev** [comment]
@AE1NS can you confirm is working on 7.0.2???
preview.ts
`export const decorators: Decorator[] = [
    moduleMetadata({
        providers: [
            {
                provide: APP_INITIALIZER,
                useFactory: (translateService: BvfIconService) => () => {
                    console.log(Object.values(ICONS));
                    translateService.registerIcons(Object.values(ICONS));
                },
                multi: true,
                deps: [BvfIconService],
            },
        ],
    }),
];`

Not working in my case

**Comment by ilFortu** [comment]
I have the same issue on v7.0.2

**Comment by valentinpalkovic** [comment]
@87Dev, @ilFortu please follow the migration guide: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#angular-application-providers-and-modulewithproviders

**Comment by 87Dev** [comment]
> @87Dev, @ilFortu please follow the migration guide: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#angular-application-providers-and-modulewithproviders

Thanks, I couldn't find that part of the documentation.
It has worked perfectly.


Greetings

**Comment by ilFortu** [comment]
> @87Dev, @ilFortu please follow the migration guide: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#angular-application-providers-and-modulewithproviders

Thanks for the tip, like that it's working now!!
