### ISSUE TITLE
[Bug]: Vue CLI sandbox templates broken

### ISSUE THREAD

**Issue by tmeasday** [storybookjs/storybook#21236]
### Describe the bug

The `vue-cli` sandbox generation was generating empty folders due to some complexities of yarn setup.

I believe I fixed the problem in 70a9e93229. 

A larger issue is **we shouldn't continue with the sandbox if `sb init` fails (which it did in this case)** -- otherwise we write a broken sandbox to the sandboxes repo and break all PRs!!

We should revert https://github.com/storybookjs/storybook/commit/696986708558ae16651d6cdd3539d65dcab750f9 once we have working templates again.

**Comment by tmeasday** [comment]
I currently can't regenerate proper templates with my fix due to a different issue with nextjs generation failing.

**Comment by shilman** [comment]
@tmeasday we can close this right?
