### ISSUE TITLE
[Bug]: FavIcon doesn't load on localhost with Vite builder

### ISSUE THREAD

**Issue by renato-bohler** [storybookjs/storybook#21245]
### Describe the bug

The favicon is not loading on localhost when Vite builder is being used.

### To Reproduce

Create a React project using Vite and TypeScript, and then initialize and start Storybook (next) on it:

```bash
npm create vite@latest
# Project name: vite-project
# Framework: React
# Variant: TypeScript

cd vite-project
yarn
npx sb@next init --builder=vite # this installed 7.0.0-beta.54 for me
yarn storybook
```

This is what I get:
![1](https://user-images.githubusercontent.com/25781956/221183212-f882b1a3-e498-452e-bd9c-c57c0738dd76.png)

Notice the lack of a favicon on the tab. Inspecting the page, I found that it was trying to use `./favicon.svg`, but `http://localhost:6006/favicon.svg` does not find anything:

![image](https://user-images.githubusercontent.com/25781956/221183720-3a327731-0cae-4732-bd1d-6d8ca2715318.png)

![image](https://user-images.githubusercontent.com/25781956/221183793-1d5910b6-1344-4396-9384-d9d4332a95b3.png)

After building, it works:

```bash
yarn build-storybook
npx http-server ./storybook-static
```

![2](https://user-images.githubusercontent.com/25781956/221184030-2be50f38-4575-4277-8430-19f3b7b270ee.png)

### System

```
Environment Info:

  System:
    OS: Linux 5.19 Ubuntu 22.10 22.10 (Kinetic Kudu)
    CPU: (32) x64 13th Gen Intel(R) Core(TM) i9-13900K
  Binaries:
    Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.18.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
  Browsers:
    Chrome: 110.0.5481.177
    Firefox: 110.0
  npmPackages:
    @storybook/addon-essentials: 7.0.0-beta.54 => 7.0.0-beta.54 
    @storybook/addon-interactions: 7.0.0-beta.54 => 7.0.0-beta.54 
    @storybook/addon-links: 7.0.0-beta.54 => 7.0.0-beta.54 
    @storybook/blocks: ^7.0.0-alpha.8 => 7.0.0-alpha.8 
    @storybook/react: 7.0.0-beta.54 => 7.0.0-beta.54 
    @storybook/react-vite: 7.0.0-beta.54 => 7.0.0-beta.54 
    @storybook/testing-library: ^0.0.14-next.1 => 0.0.14-next.1 
```

### Additional context

This was probably introduced by https://github.com/storybookjs/storybook/pull/20130. This PR was released on `7.0.0-alpha.62`, and if I downgrade to `7.0.0-alpha.61`, the favicon seems to show up just fine:

```bash
yarn add -DE storybook@7.0.0-alpha.61 @storybook/react@7.0.0-alpha.61 @storybook/react-vite@7.0.0-alpha.61 @storybook/addon-essentials@7.0.0-alpha.61 @storybook/addon-interactions@7.0.0-alpha.61 @storybook/addon-links@7.0.0-alpha.61
yarn storybook
```

![3](https://user-images.githubusercontent.com/25781956/221184427-8b2be31b-d701-486a-9e1c-efcf67fe75a4.png)

https://github.com/storybookjs/storybook/pull/20612 might also be related.

**Comment by JorisAerts** [comment]
I can confirm this. I'm using @storybook/vue3-vite and I also don't have a favicon. (on 7.0.0-rc9)

There is a favicon declared in the header:
```html
<link rel="icon" type="image/svg+xml" href="./favicon.svg">
```
But when navigating to it, you get a 404.

There is a **favicon.ico** though, but it seems nothing but a 328 bytes blank square.

**Comment by ghengeveld** [comment]
Can confirm, still present on 7.5.0-alpha.1.

**Comment by rossanag** [comment]
@JorisAerts I don't know if it has to do with the fact, hat some browsers don't display the icon (Chrome, Safari), if they are local.
Just for the purpose of testing I copy my icon into another folder under  the```src``` folder, and then the icon displays correctly.
(I changed ```<link rel="icon" type="image/svg+xml" href="src/assets/vite.svg" />```    )

**Comment by designcouch** [comment]
Having a similar issue, and I believe it's because when you build for production, Vite hashes all static files to bust the cache and be sure that users get any updates.

Most internal views/components are updated on build to reflect this change - but anything in index.html that is "hard coded" does not get this update. So the actual filename for your favicon is being hashed on build.

**Comment by ndelangen** [comment]
@IanVS Does that make sense to you? What would be an appropriate fix/solution?

**Comment by IanVS** [comment]
I do not see this behavior.  The favicon is working fine in both my app, as well as in a new Storybook.  Does someone have a reproduction for us to look at?

**Comment by biswarupz** [comment]
in the index file I added     <link rel="icon" type="image/png" href="/public/favicon.ico" />
but still the favicon is not showing up. any idea to fix it ?

**Comment by ritute** [comment]
I ran into this as well in a different app, and it appears that on localhost the favicon only appears if I prepend the path with public: `/public/favicon.ico`.

**Comment by ndelangen** [comment]
@ritute I thought I had fixed this, Can you supply a repro with the failure that caused you to add that work-around?

**Comment by ritute** [comment]
> @ritute I thought I had fixed this, Can you supply a repro with the failure that caused you to add that work-around?

It's in a different project, not storybook, but just wanted to share what I had to do in my Vite project to fix this similar issue in case somebody here runs into it or comes across this from google searches for it.

**Comment by dantaylor** [comment]
I just moved the favicon from /public/favicon.ico to /public/images/favicon.ico and updated the index file like so: 
<link rel="icon" type="image/x-icon" href="images/favicon.ico" />
and it worked in both locahost and build.
