### ISSUE TITLE
[Bug]: Rendering MDX breaks when requirejs is imported via CDN within preview-head.html

### ISSUE THREAD

**Issue by herrKlein** [storybookjs/storybook#21250]
### Describe the bug

when adding a script tag with requirejs to the ```preview-head.html``` MDX rendering breaks. 

```html
<script
  src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js"
  integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg=="
  crossorigin="anonymous"
  referrerpolicy="no-referrer"
></script>
```

I reported this because it took me a long time to figure out whats wrong with MDX rendering, first thought it had something to do with the 7.0.0-beta.54 version. It was me after all.

<img width="862" alt="Screenshot 2023-02-24 at 18 19 34" src="https://user-images.githubusercontent.com/6085660/221245423-c3259f94-e1c5-43c9-acc1-4bc37eb96b5c.png">

### To Reproduce

7.0.0-beta.54

### System

```shell
Environment Info:
  System:
    OS: macOS 12.6.1
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.18 - ~/.yarn/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Chrome: 110.0.5481.177
    Firefox: 110.0
    Safari: 16.1
```

### Additional context

This is happening in an NX webcomponents repository with the latest Storybook 7.0.0-beta.54. Its not an urgent issue, but a weird issue. Don't know what the policy is and the urgency of importing requirejs. I thought ```requirejs``` should just be available within the iframes sandbox and not break Storybook related libraries.

**Comment by herrKlein** [comment]
This is still an issue, and I kinda expect Storybook not breaking when putting requirejs in the Iframe. Does anyone know of a workaround, or should i file with the overlays scrollbar component?

**Comment by gk1041** [comment]
@herrKlein did you ever find a solution? I'm having same issue

**Comment by herrKlein** [comment]
> @herrKlein did you ever find a solution? I'm having same issue

Sadly not, tried everything, hacking requirejs to use another name, using a closure around requirejs.. trying to use https://www.npmjs.com/package/requirees .. which should be an es loader for requirejs I think..

Maybe we should report the error in the thirdparty library here: https://kingsora.github.io/OverlayScrollbars/ which is where storybook says the problem lies.

**Comment by herrKlein** [comment]
Looks like this is no issue anymore
