### ISSUE TITLE
[Bug]: Types for `subcomponents` in `Meta` are broken (React)

### ISSUE THREAD

**Issue by josh-degraw** [storybookjs/storybook#21253]
### Describe the bug

![image](https://user-images.githubusercontent.com/18509575/221292086-6116ea4c-f94a-4a7d-b5c5-5c4381e8f1d5.png)
![image](https://user-images.githubusercontent.com/18509575/221298743-b37e9b9a-c3e9-41ae-84ab-ec51f8b0cc69.png)

From what I can tell, the problem seems to stem from the definition of `component` in `ReactRenderer`, where it's resolving to `ComponentType<unknown>` instead of `ComponentType<{}>`, which better matches React's defaults.

Adding `T: {}` to `ReactRenderer` in the type definition file in my node_modules seems to fix it for me, but I don't know enough about the ecosystem to know if there's a better fix than that or if doing so would break anything else.

### To Reproduce

https://github.com/josh-degraw/stjorybook-repro

### System

```shell
Environment Info:

  System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Binaries:
    Node: 18.12.1 - ~\AppData\Local\fnm_multishells\81532_1677274577441\node.EXE
    Yarn: 3.3.1 - ~\AppData\Local\fnm_multishells\81532_1677274577441\yarn.CMD
    npm: 8.19.2 - ~\AppData\Local\fnm_multishells\81532_1677274577441\npm.CMD
  Browsers:
    Chrome: 110.0.5481.105
    Edge: Spartan (44.19041.1266.0), Chromium (110.0.1587.50)
  npmPackages:
    @storybook/addon-docs: ^7.0.0-beta.53 => 7.0.0-beta.54
    @storybook/addon-essentials: ^7.0.0-beta.53 => 7.0.0-beta.54
    @storybook/addons: ^7.0.0-beta.53 => 7.0.0-beta.54
    @storybook/react: ^7.0.0-beta.53 => 7.0.0-beta.54
    @storybook/react-webpack5: ^7.0.0-beta.53 => 7.0.0-beta.54
```

**Comment by josh-degraw** [comment]
Looks like it also causes issues with `@storybook/testing-react`:
![image](https://user-images.githubusercontent.com/18509575/221301734-c143194c-967a-477f-a9fc-59c84ce859f2.png)

**Comment by JReinhold** [comment]
`subcomponents` is deprecated in 7.0. The API is very limiting and hard to improve on. It is somewhat of a half-baked feature, that we want to rethink and do better.

Subcomponents has been removed from the default DocsPage in 7.0, but since it's still available in the now deprecated `<ArgsTable />` doc block, they can be re-added by defining your own DocsPage globally.

We don't have a clear path forward from this yet, we want to collect feedback from the community about what they want from their subcomponent documentation and how they want to use it, both for docs and for development.

It's unfortunate that the types are broken for the feature here, as it's not yet completely removed.

**Comment by keisha-rw** [comment]
@JReinhold - Is there any chance this could be added back into Storybook until there is a good solution (non-deprecated) for those currently using subcomponents? We have a design system built from web components and this is a major shift for us.  Subcomponents was a great way to say, "this component is not meant to be used on its own."  We're looking to shift to Storybook 7 now and this limitation is really disappointing.

**Comment by ervinpiol** [comment]
Is there any update on this  subcomponents?

**Comment by JReinhold** [comment]
As mentioned in the canonical issue, this has been added back in Storybook 8.0

https://github.com/storybookjs/storybook/issues/20782#issuecomment-1892178858

If there are still issues with the types, feel free to open a new issue (or PR) with a minimal reproduction.

**Comment by endreujhelyi** [comment]
This is still an issue in Storybook 8.1.10. Please see https://github.com/storybookjs/storybook/issues/27535
