### ISSUE TITLE
[Bug]: Boilerplate stories for new solid have broken links in the source

### ISSUE THREAD

**Issue by jonyo** [storybookjs/storybook#21251]
### Describe the bug

Using the command to initialize it:

```bash
pnpx storybook@next init --type solid -p tsx -b vite
```

It generates `src/stories/` that contain comments like this:

> // More on how to position stories at: https://storybook.js.org/docs/7.0/solid/configure/story-layout

All of the links in the comments go to 404 pages.

Full list of broken links scattered through the generated files:

- // More on how to position stories at: https://storybook.js.org/docs/7.0/solid/configure/story-layout
- // More on interaction testing: https://storybook.js.org/docs/7.0/solid/writing-tests/interaction-testing
- // This component will have an automatically generated Autodocs entry: https://storybook.js.org/docs/7.0/solid/writing-docs/docs-page
- // More on how to set up stories at: https://storybook.js.org/docs/7.0/solid/writing-stories/introduction
- // More on writing stories with args: https://storybook.js.org/docs/7.0/solid/writing-stories/args

It seems the `solid` part of the URL is the issue. If you change to something like `html` it resolves, though obviously not specific to solid.

### To Reproduce

Start with a starter solid app.

Then initialize :

```bash
pnpx storybook@next init --type solid -p tsx -b vite
```

NOTE: maybe this is another bug, but just using `--type solid` without the other options did not work, it failed. Maybe that is another issue.  But the above did work.

Go through the prompts, saying "yes" to install various options.

Now open up the different `src/stories/` files, they will have broken links.

### System

```shell
Environment Info:

  System:
    OS: macOS 13.2.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Chrome: 110.0.5481.177
    Safari: 16.3
  npmPackages:
    @storybook/addon-essentials: ^7.0.0-beta.54 => 7.0.0-beta.54 
    @storybook/addon-interactions: ^7.0.0-beta.54 => 7.0.0-beta.54 
    @storybook/addon-links: ^7.0.0-beta.54 => 7.0.0-beta.54 
    @storybook/addon-mdx-gfm: ^7.0.0-beta.54 => 7.0.0-beta.54 
    @storybook/blocks: 7.0.0-beta.54 => 7.0.0-beta.54 
    @storybook/html: ^7.0.0-beta.54 => 7.0.0-beta.54 
    @storybook/html-vite: 7.0.0-beta.54 => 7.0.0-beta.54 
    @storybook/testing-library: ^0.0.14-next.1 => 0.0.14-next.1
```

### Additional context

I would not be surprised if this was already on someone's radar since solid support was just added.  I just wanted to make sure it didn't get overlooked if that was not the case. 😄

**Comment by jonniebigodes** [comment]
@jonyo, thanks for reaching out to us with your issue. We appreciate it. To give you some context, indeed, the Solid framework is being actively developed same as with the documentation. The reason you're getting a 404 for the links is that we decided to hold off on merging the documentation pull request l(i.e., #21207) until 7.0 is out and also allow the contributor to spin up a sandbox to help with vetting and improving the examples and documentation, as mentioned in said pull request. If you're ok with it and want to give us a hand, check out the pull request and join our Discord server [https://discord.gg/storybook) and follow up with the contributor and me in the #wg-solid channel so we can get it out as soon as possible and help you and other SolidJS users. Sounds good to you?


Looking forward to hearing from you.

Hope you have a great day.

Stay safe

**Comment by jonniebigodes** [comment]
@jonyo just wanted to let you that the mentioned pull request is merged, and the documentation is now updated to feature the SolidJS snippets. Closing this for now.

Feel free to reach out to us if you run into any issues, and we'll be more than glad to follow up with you on them. 

Hope you have a fantastic day.

Stay safe
