### ISSUE TITLE
[Bug]: Getting an error when try to add storybook with CRA

### ISSUE THREAD

**Issue by zakariamagdyz** [storybookjs/storybook#21260]
### Describe the bug

`99% done plugins webpack-hot-middlewarewebpack built preview 397a36fc31538f2891fc in 16726ms
WARN Force closed manager build
ModuleParseError: Module parse failed: 'import' and 'export' may appear only with 'sourceType: module' (3:0)
File was processed with these loaders:
 * ./node_modules/@storybook/preset-create-react-app/node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js
You may need an additional loader to handle the result of these loaders.
| __webpack_require__.$Refresh$.runtime = require('/mnt/ssd/Projects/Work/hollydesk-v2/node_modules/react-refresh/runtime.js');
| 
> export const parameters = {
|   actions: { argTypesRegex: "^on[A-Z].*" },
|   controls: {
    at handleParseError (/mnt/ssd/Projects/Work/hollydesk-v2/node_modules/webpack/lib/NormalModule.js:976:19)
    at /mnt/ssd/Projects/Work/hollydesk-v2/node_modules/webpack/lib/NormalModule.js:1095:5
    at processResult (/mnt/ssd/Projects/Work/hollydesk-v2/node_modules/webpack/lib/NormalModule.js:800:11)
    at /mnt/ssd/Projects/Work/hollydesk-v2/node_modules/webpack/lib/NormalModule.js:860:5
    at /mnt/ssd/Projects/Work/hollydesk-v2/node_modules/loader-runner/lib/LoaderRunner.js:407:3
    at iterateNormalLoaders (/mnt/ssd/Projects/Work/hollydesk-v2/node_modules/loader-runner/lib/LoaderRunner.js:233:10)
    at iterateNormalLoaders (/mnt/ssd/Projects/Work/hollydesk-v2/node_modules/loader-runner/lib/LoaderRunner.js:240:10)
    at /mnt/ssd/Projects/Work/hollydesk-v2/node_modules/loader-runner/lib/LoaderRunner.js:255:3
    at context.callback (/mnt/ssd/Projects/Work/hollydesk-v2/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at /mnt/ssd/Projects/Work/hollydesk-v2/node_modules/@storybook/preset-create-react-app/node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js:94:7
ModuleNotFoundError: Module not found: Error: Can't resolve '/mnt/ssd/Projects/Work/hollydesk-v2/node_modules/@storybook/client-api' in '/mnt/ssd/Projects/Work/hollydesk-v2/.storybook'
Did you mean 'index.js'?
BREAKING CHANGE: The request '/mnt/ssd/Projects/Work/hollydesk-v2/node_modules/@storybook/client-api' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
    at /mnt/ssd/Projects/Work/hollydesk-v2/node_modules/webpack/lib/Compilation.js:2016:28
    at /mnt/ssd/Projects/Work/hollydesk-v2/node_modules/webpack/lib/NormalModuleFactory.js:798:13
    at eval (eval at create (/mnt/ssd/Projects/Work/hollydesk-v2/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /mnt/ssd/Projects/Work/hollydesk-v2/node_modules/webpack/lib/NormalModuleFactory.js:270:22
    at eval (eval at create (/mnt/ssd/Projects/Work/hollydesk-v2/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)`

### System

```shell
os : linux(pop-os)
```

**Comment by shilman** [comment]
Do you a have a reproduction repo you can share? If not, can you create one? See [how to create a repro](https://storybook.js.org/docs/react/contribute/how-to-reproduce). 🙏

If not, can you provide repro steps? Which version of CRA? Which versions of Storybook packages?
