### ISSUE TITLE
[Bug]: npx storybook@next upgrade --prerelease does not upgrade @storybook/addon-coverage

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#21288]
### Describe the bug

Pretty much all storybook packages but `@storybook/addon-coverage` are updated correctly.

### To Reproduce

- Have a project with `"@storybook/addon-coverage":  "0.0.2"`
- Run `npx storybook@next upgrade --prerelease`
- Expect the package to be picked up and upgraded to `0.0.8`

**Comment by shilman** [comment]
closing as duplicate to #21287
