### ISSUE TITLE
Automigrations: GFM fails with complex addon object

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#21286]
### Describe the bug

The GFM automigration fails on a `main.js` that contains a complex `addons` config, such as the following:

```js
const postcssConfig = require('../postcss.config');

module.exports = {
    addons: [
        {
            name: '@storybook/addon-postcss',
            options: {
                postcssLoaderOptions: {
                    ...postcssConfig,
                    implementation: require('postcss')
                }
            }
        },
```

It tries to parse the `addons` field into an array, append an addon string to the array, and then set it again in the `ConfigFile` object.

- [ ] it should not parse `addons` and should append the string to the addons array in the AST to work around this issue.
- [ ] if the automigration fails anyway, it should produce a better error message stating the failure and the manual workaround

### To Reproduce

https://github.com/inkline/inkline/blob/85c694daebf4eb18462988876d89ab95e4a0ab78/.storybook/main.js#L10-L18

**Comment by tmeasday** [comment]
I'll also note it claimed to work: 

![Image](https://user-images.githubusercontent.com/132554/222044240-4bfe0171-2843-4076-96de-621151baa5ed.png)

**Comment by shilman** [comment]
Shiver me timbers!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-rc.6 containing PR #21731 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```
