### ISSUE TITLE
[Bug]: 7.0.0-beta.55, TS, Vite Svelte, @storybook/theming - "TypeError: theme.typography is undefined"

### ISSUE THREAD

**Issue by doolijb** [storybookjs/storybook#21285]
### Describe the bug

I believe this is a general need to upgrade the lib, but I did not see any related tickets after a few search queries.

On `npm run storybook`, the application starts. Custom [themes](https://storybook.js.org/docs/7.0/svelte/configure/theming) (copy and paste) do not display. The demo documentation page attempts to load with the below error:

```js
// Web Console
TypeError: theme.typography is undefined
```

Stressor:
Fixes made for Vite/Svelte were never backported, so V6.5 is untenable.

### To Reproduce

```sh
npm create vite@latest . -- --template svelte-ts
npx sb@next init

# Validate SB runs
npm run storybook

# Install theming
npm i --dev @storybook/addons @storybook/theming
```

Next, follow the documentation for `.storybook/manage.js` and run again.

### Steps to remove:
```
npm remove @storybook/theming
rm ./package-lock.json
rm -rf ./node_modules
npm I
```

### System

```shell
System:
    OS: Linux 5.15 Zorin OS 16.2
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i7-1260P
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    npm: 8.19.2 - ~/.nvm/versions/node/v16.17.0/bin/npm
  Browsers:
    Chrome: 110.0.5481.177
    Firefox: 110.0
  npmPackages:
    @storybook/addon-essentials: ^7.0.0-beta.55 => 7.0.0-beta.55 
    @storybook/addon-interactions: ^7.0.0-beta.55 => 7.0.0-beta.55 
    @storybook/addon-links: ^7.0.0-beta.55 => 7.0.0-beta.55 
    @storybook/addons: ^6.5.16 => 6.5.16 
    @storybook/blocks: ^7.0.0-alpha.8 => 7.0.0-beta.55 
    @storybook/svelte: ^7.0.0-beta.55 => 7.0.0-beta.55 
    @storybook/svelte-vite: ^7.0.0-beta.55 => 7.0.0-beta.55 
    @storybook/testing-library: ^0.0.14-next.1 => 0.0.14-next.1
```

**Comment by shilman** [comment]
Please try upgrading to the latest prerelease. This might have been fixed in a more recent version. AFAIK there are no outstanding theming issues in SB7.

Migration guide: https://storybook.js.org/migration-guides/7.0

If you're still having problems, please open with a linked reproduction and we'd be happy to take a look. Thanks!
