### ISSUE TITLE
[Bug]: Test runner does not run if main storybook config file is a Typescript file in NextJs

### ISSUE THREAD

**Issue by elliotgonzalez123** [storybookjs/storybook#21298]
### Describe the bug

In NextJs, after installing and setting up the storybook test runner, running `npm run test-storybook` throws the following error in the console...

`/Users/{{user}}/Desktop/my-app/.storybook/main.ts: Unexpected token, expected "from"`

If you change the `main.ts` file to `main.js`, remove the type imports and use `module.exports` syntax, the test runner runs without a problem.

I've also solved this by adding in a custom `.babelrc` file in my NextJs project, however this is not ideal as it overrides the new NextJs swc compiler which is necessary for many of NextJs's newest features.

For context, here is a previous issue for a non NextJs project: https://github.com/storybookjs/storybook/issues/17589

### To Reproduce

A stackblitz repro can be found here:  https://stackblitz.com/edit/github-uriqhe?file=package.json

1. Setup a fresh NextJs typescript project
2. Add storybook
3. Use the typescript example in the docs to setup the config file
4. Add test runner
5. Run `npm run test-storybook`

### System

```shell
Environment Info:
  System:
    OS: macOS 12.5.1
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 18.8.0 - /opt/homebrew/bin/node
    npm: 9.5.1 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 110.0.5481.177
    Firefox: 105.0.3
    Safari: 15.6.1
  npmPackages:
    @storybook/addon-coverage: ^0.0.8 => 0.0.8 
    @storybook/addon-essentials: ^7.0.0-beta.55 => 7.0.0-beta.55 
    @storybook/addon-interactions: ^7.0.0-beta.55 => 7.0.0-beta.55 
    @storybook/addon-links: ^7.0.0-beta.55 => 7.0.0-beta.55 
    @storybook/blocks: ^7.0.0-alpha.8 => 7.0.0-beta.55 
    @storybook/nextjs: ^7.0.0-beta.55 => 7.0.0-beta.55 
    @storybook/react: ^7.0.0-beta.55 => 7.0.0-beta.55 
    @storybook/test-runner: ^0.9.4 => 0.9.4 
    @storybook/testing-library: ^0.0.14-next.1 => 0.0.14-next.1
```

**Comment by domyen** [comment]
@yannbf @valentinpalkovic Seems like there's a bug when the test runner is combined with next framework

**Comment by shilman** [comment]
@elliotgonzalez123 Have you tried upgrading to the `next` release of the test runner?

**Comment by shilman** [comment]
closing as dupe to https://github.com/storybookjs/test-runner/issues/270
