### ISSUE TITLE
[Bug]: Nunito-sans-italic preloaded using link preload but not used within a few seconds from the window's load event

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#21315]
### Describe the bug

After migrating and building Storybook, then serving it via npx http-server

there are browser warnings regarding the fonts that Storybook provides:

> The resource http://127.0.0.1:8080/sb-common-assets/nunito-sans-italic.woff2 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate as value and it is preloaded intentionally.
:8080/iframe.html?viewMode=docs&id=components-errorblock--docs:1 The resource http://127.0.0.1:8080/sb-common-assets/nunito-sans-bold-italic.woff2 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate as value and it is preloaded intentionally.
:8080/?path=/docs/components-errorblock--docs:1 The resource http://127.0.0.1:8080/sb-preview/runtime.mjs was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate as value and it is preloaded intentionally.

### To Reproduce

https://github.com/yannbf/mealdrop

**Comment by tmeasday** [comment]
Perhaps we should be using `prefetch` instead?

**Comment by shilman** [comment]
If this isn't an easy fix, let's discuss before putting much time into it.

**Comment by shilman** [comment]
Yowza!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-rc.4 containing PR #21599 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```
