### ISSUE TITLE
[Bug]: Wrong description for toggle outline in shortcuts page

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#21321]
### Describe the bug

Reported by @RhysSullivan (Thank you!!)

In the “Keyboard Shortcuts” section, there is an entry for Toggle Measure [O] however O is the keybind for toggle outline. Further down the page there is another entry for Toggle Measure [M] which is the correct one.

![image](https://user-images.githubusercontent.com/1671563/222108229-7ca44367-409e-4361-9c5a-69b48af03e74.png)

They should be `Toggle Outline [O]` and `Toggle Measure [M]` respectively

### To Reproduce

Select the "Keyboard shortcuts" option in the gear icon on top left in Storybook.
<img width="242" alt="image" src="https://user-images.githubusercontent.com/1671563/222108777-ff9710bd-7575-4426-b67d-359c535ff04e.png">

**Comment by shilman** [comment]
Yo-ho-ho!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-rc.3 containing PR #21515 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```
