### ISSUE TITLE
[Bug]: An additional outline border is displayed in docs mode

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#21328]
### Describe the bug

Reported by @kbrandwijk (Thank you!)

When seeing a story in canvas, the Outline addon functionality is correct:
![image](https://user-images.githubusercontent.com/1671563/222114996-6b089ccb-8969-48c1-a516-2ebfb197056d.png)

But when seeing in a docs entry, it outlines more elements that it should not, such as the "show code" button and the story wrapper:
![image](https://user-images.githubusercontent.com/1671563/222115352-4f6c50ad-cb2a-4a21-886d-bd600ae30504.png)

The addon should only highlight the child elements of the story wrapper (e.g. `<div id="story--components-category--default--primary-inner" data-name="Default">`) in docs mode.

### To Reproduce

- Run Storybook 7 with addon-essentials
- Open a story in docs mode
- Enable outline (press O on keyboard)

**Comment by Ocoldwell** [comment]
I'd like to work on this if it's available.

**Comment by shilman** [comment]
Yowza!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.1.0-alpha.15 containing PR #21773 that references this issue. Upgrade today to the `@future` NPM tag to try it out!

```
npx sb@next upgrade --tag future
```

**Comment by shilman** [comment]
Great Caesar's ghost!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.11 containing PR #21773 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb@latest upgrade
```
