### ISSUE TITLE
[Bug]: Searchbar does not reflect custom shortcut if set

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#21325]
### Describe the bug

Reported by @kbrandwijk (Thank you!)

If you override the ‘focus search’ shortcut, then the search field keeps showing the (now non-working) ‘/’ shortcut.

![image](https://user-images.githubusercontent.com/1671563/222112567-15d2d684-87ed-46b3-9eab-698896a05a47.png)

### To Reproduce

- Run Storybook 7
- Go to settings page http://localhost:6006/?path=/settings/shortcuts
- Override search command

**Comment by kabhamo** [comment]
@yannbf , @shilman,
Hi I hope you are doing well.
I am trying to fix the bug, but I need to console.log and debug some values.
I was trying to use the inspect=>console or source, but it dose not work.
Any suggestions, please?

**Comment by nv1327** [comment]
@yannbf I would like to contribute to an open source project for a university class. Would you mind if I took up this issue?

**Comment by yannbf** [comment]
Hey everyone so sorry for the late reply, but it seems like this issue is already being handled in a PR. Thank you so much for your interest <3

**Comment by shilman** [comment]
Son of a gun!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.11 containing PR #21619 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb@latest upgrade
```
