### ISSUE TITLE
[Bug]: Measure tool stays active when switching to Docs, causing it to measure the Docs page.

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#21327]
### Describe the bug

Reported by @kbrandwijk (Thank you!)

The measure tool stays active when switching to Docs, causing it to measure the Docs page.

![image](https://user-images.githubusercontent.com/1671563/222113801-62b2b476-04ab-4b99-bf35-1aa41ccc6861.png)

⚠️ Additionally, the Measure addon functionality, even though there is no button to enable it in docs mode, can be enabled via keyboard shortcuts. When it's enabled, it can't be disabled via keyboard shortcuts anymore.

### To Reproduce

- Run Storybook 7 with addon-essentials
- Open a story, toggle measure on (press M or the addon icon)
- Switch to docs

**Comment by Dev79844** [comment]
Hey
I would like to work on this issue. Can you assign it to me?

**Comment by shilman** [comment]
Good golly!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.1.0-alpha.15 containing PR #21602 that references this issue. Upgrade today to the `@future` NPM tag to try it out!

```
npx sb@next upgrade --tag future
```

**Comment by shilman** [comment]
Great Caesar's ghost!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.11 containing PR #21602 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb@latest upgrade
```
