### ISSUE TITLE
[Bug]: Storybook v7 (Beta 54) does not respect parameters.options.storySort

### ISSUE THREAD

**Issue by RobinBertilsson** [storybookjs/storybook#21322]
### Describe the bug

According to the [documentation](https://storybook.js.org/docs/7.0/react/writing-stories/naming-components-and-hierarchy#sorting-stories), you should be able to sort your stories by defining the storySort object (or method), but neither works in the latest beta version of Storybook v7.

I'm using `@storybook/react` (with TypeScript).

### To Reproduce

1. Clone https://github.com/RobinBertilsson/storybook-v7-sort-order-issue
2. Run `npm install`.
3. Run `npm run storybook`.
4. The expected order, according to `storySort.order` would be `Button, Introduction, Header, Page`, but it's not.

### System

```shell
Environment Info:

  System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1 Pro
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Chrome: 110.0.5481.177
    Firefox: 110.0
    Safari: 16.3
```

**Comment by tmeasday** [comment]
@shilman this is due to the change to the default export.

**Comment by shilman** [comment]
Jeepers creepers!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.60 containing PR #21353 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```

**Comment by RobinBertilsson** [comment]
Lovely @shilman, thanks for the quick help! ❤️
