### ISSUE TITLE
storybook for svelte

### ISSUE THREAD

**Issue by edbek** [storybookjs/storybook#21320]
### Describe the bug

Tell me someone, I'm new and I can not install storybook for my svelte project in any way.
Is there any working guide to install storybook for svelte ? 
Everything I read on the site storybook - it does not work!

**Comment by valentinpalkovic** [comment]
Hey @edbek,

If you want to use SvelteKit with Storybook, please follow the following documentation: https://github.com/storybookjs/storybook/blob/next/code/frameworks/sveltekit/README.md

If you want to play around with some of our svelte sandboxes, please check them out:

Run `npx storybook@next repro` to create a working sandbox for `Svelte Vite (JS/TS)` and for `Svelte Kit(JS/TS). Then you are able to compare your options with the sandbox ones to figure out, why Storybook is not working for you.

If you have general questions, ask for support in our dedicated `svelte` channel on [Discord](https://discord.com/channels/486522875931656193/495147526278610945).

**Comment by edbek** [comment]
Thanks for the advice!
Yes, it works.
