### ISSUE TITLE
[Bug]: Addon docs README is not up to date with Storybook 7

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#21329]
### Describe the bug

When looking at the ["How to document components" page](https://storybook.js.org/docs/7.0/react/writing-docs/introduction), there is a link to the README:
![image](https://user-images.githubusercontent.com/1671563/222119983-b47f5300-d8b8-4e2f-9218-fb1a6a89e853.png)

And the README contains instructions for Storybook 5.3-6.0 style addon docs:
https://github.com/storybookjs/storybook/blob/next/code/addons/docs/README.md

**Comment by jonniebigodes** [comment]
@yannbf I'm aware of this, and this and the other monorepo Readme's will be updated after 7.0 as part of this [issue](https://github.com/storybookjs/storybook/issues/20732).

**Comment by tmeasday** [comment]
Should we close this ticket as a dupe? And add the other to the board?

**Comment by shilman** [comment]
Closing as dupe to #20732
