### ISSUE TITLE
[Bug]: Keyboard navigation doesn’t scroll search results

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#21323]
### Describe the bug

Reported by @kbrandwijk (thank you!)

Keyboard navigation doesn’t scroll search results. If I use arrow up/arrow down in the ‘normal’ sidebar, it scrolls my sidebar so the active item stays into view. In the search results this doesn’t happen, and arrow down goes out of view at the bottom of the list, which is an a11y concern.

### To Reproduce

![2023-03-01 11 14 56](https://user-images.githubusercontent.com/1671563/222110662-7fb2c76b-2156-408f-9596-bdbb45eb253f.gif)

**Comment by shilman** [comment]
Zoinks!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-rc.9 containing PR #21692 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
