### ISSUE TITLE
[Bug]: SB v7.0.0-beta.45 story parameters not passed to addons on doc pages

### ISSUE THREAD

**Issue by wilkinsjade** [storybookjs/storybook#21337]
### Describe the bug

Hi! I'm currently using Storybook v7.0.0-beta.45 with React 17.0.2. I am working on creating a custom addon that adds an additional tab to the docs page. I am noticing that parameters set in the stories meta are not being passed to the docs page but the parameters are passed to the story page.

Custom Tab addon source code
![customAddOnCode](https://user-images.githubusercontent.com/126698952/222201323-3d6ef8db-91dd-43e6-9284-baf430ab0212.png)

Parameters being set in the story (In the component meta a data property is set and the canvas tab is set to be hidden)
![storymeta](https://user-images.githubusercontent.com/126698952/222201847-7bc6281a-9645-4b41-bffa-0e313de93d95.png)

Parameters succesfuly passed (the parameters are passed successfully canvas tab is hidden and the parameter is passed to the addon)
![additonalscreenshot](https://user-images.githubusercontent.com/126698952/222203957-cbd74a0d-fa96-4468-b7c6-95479e4ccd92.png)
ssed to the story page

Parameters not passed to the docs page (parameters are not passed, the canvas tab is still visible and the data parameter is not passed to the addon)
![DocsTabNoParamTab](https://user-images.githubusercontent.com/126698952/222202443-4c2a046c-f996-4787-967f-9f7cd1b1fe1b.png)

**Comment by JReinhold** [comment]
@tmeasday @shilman have you thought about this use case, addons that adds tabs to docs entries?

1. Which parameters would we surface to the addon? I can sort of see we could re-use `PreparedMeta` for attached docs, and project annotations for unattached docs?
2. Looks like a bug to me that when an addon tab is added, a docs entry has a "Canvas" tab. I'm not sure from the screenshot if the "Documentation" tab is the actual docs page, or another addon that OP has installed.

For now it feels like custom addon tabs are not supported for docs entries.

**Comment by wilkinsjade** [comment]
@JReinhold The Documentation tab is another custom addon tab

**Comment by tmeasday** [comment]
> Which parameters would we surface to the addon? I can sort of see we could re-use PreparedMeta for attached docs, and project annotations for unattached docs?

I think that'd make sense. We don't currently have the concept of project or component-level parameters in the manager side (or really in the store at all as you've seen). We might want to reconsider this in the future?

> For now it feels like custom addon tabs are not supported for docs entries.

Should we (for now at least) hide the custom tabs when you visit a docs entry? (Obviously not helping you @wilkinsjade but maybe a little less "broken"?)

**Comment by JReinhold** [comment]
> Should we (for now at least) hide the custom tabs when you visit a docs entry? (Obviously not helping you @wilkinsjade but maybe a little less "broken"?)

Agreed, the tabs in docs is currently not able to handle this, so let's hide it until we've added proper support for this.

**Comment by tmeasday** [comment]
@wilkinsjade can you let us know the addons you are using there that add tabs for a simple reproduction?

**Comment by wilkinsjade** [comment]
@tmeasday Hey the two tabs usage and documentation are simple addons I created by following this doc https://storybook.js.org/docs/react/addons/addon-types

**Comment by wilkinsjade** [comment]
@tmeasday @JReinhold Any updates on this ticket? My team is in the process of planning out our storybook documentation and we want to close the loop on if it will be possible to have custom tabs on the docs' pages. Thanks!

**Comment by JReinhold** [comment]
@wilkinsjade you shouldn't expect custom tabs to work in Docs entries. Either we'll hide them completely before 7.0 stable release, or we will fix other things instead (PR welcome though!).

We might revisit this in a later release, but we can't promise anything about that right now.

**Comment by wilkinsjade** [comment]
@JReinhold Thanks! We will plan accordingly

**Comment by robin-ambachtsheer** [comment]
This issue is not just about tabs right? I've noticed the parameters are also not being passed for toolbar actions. (For example the backgrounds addon lets you disable the grid button trough the global parameters but it's not being honored for the attached docs). In my use case I want to show a status badge for the component in the toolbar which works fine for stories, but again the attached docs where it's most useful is not picking up the parameter. I might be able to create a reproduction if needed, though it's easy to spot with the standard backgrounds addon.

**Comment by tmeasday** [comment]
@robin-ambachtsheer yes this is a known regression, you can read a discussion on this PR: https://github.com/storybookjs/storybook/pull/19959
