### ISSUE TITLE
[Bug]: Storybook does not respect BROWSER env var if default browser is not chromium based.

### ISSUE THREAD

**Issue by thtliife** [storybookjs/storybook#21343]
### Describe the bug

When using the environment variable BROWSER to configure the browser that storybook opens in, storybook will not respect this configuration if the users default browser is not set to a browser which the `@aw-web-design/x-default-browser` package does not resolve to either `chrome`, `chromium` or `com.brave.browser`.

#### Set the system default browser to something not based on chromium

eg: `safari`

#### Clone the reproduction repo

```bash
mkdir repo-test
cd repo-test
git clone https://github.com/thtliife/storybook-specify-browser-repro
```

#### Install dependencies

```bash
yarn
```

#### Run storybook with the BROWSER environment variable set to something other than the default system browser:

```bash
BROWSER=firefox yarn storybook
```

or create a .env file in the root of the project with the following contents:

```bash
BROWSER=firefox
```

then run storybook
```bash
yarn storybook
```

### System

```shell
Environment Info:

  System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 16.13.0 - ~/.tools/n/bin/node
    Yarn: 1.22.19 - ~/.tools/n/bin/yarn
    npm: 8.1.0 - ~/.tools/n/bin/npm
  Browsers:
    Chrome: 110.0.5481.177
    Firefox: 110.0.1
    Safari: 16.2
```

### Additional context

The problem is caused by the `open-in-browser` utility not passing args to `open` when the default browser is not chromium.

If the default browser is a chromium browser, `better-opn` is used which does its own evaluation of environment variables, allowing the BROWSER variable to be evaluated.

**Comment by thtliife** [comment]
A force push from the pull bot removed my changes in the pr #21344 
It ended up with no changed files.
Should I create another pr for this?

**Comment by tmeasday** [comment]
I guess so-- something odd is happening here !

**Comment by thtliife** [comment]
hahaha
no problems

**Comment by thtliife** [comment]
there we go, fingers crossed this one merges ok 😉

**Comment by shilman** [comment]
Egads!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.1.0-alpha.21 containing PR #21473 that references this issue. Upgrade today to the `@future` NPM tag to try it out!

```
npx sb@next upgrade --tag future
```
