### ISSUE TITLE
[Bug]: ReferenceError: module is not defined

### ISSUE THREAD

**Issue by erwan-joly** [storybookjs/storybook#21340]
### Describe the bug

Not sure why since I upgraded from 7.0.0-beta.52 to 7.0.0-beta.53-57 I am getting this error on stories.

ReferenceError: module is not defined
    at ./node_modules/@storybook/addon-links/dist/chunk-HG45ZTEM.mjs (http://localhost:6006/vendors-node_modules_storybook_react_preview_js-node_modules_storybook-addon-apollo-client_di-ff1302.iframe.bundle.js:77130:27)
    at __webpack_require__ (http://localhost:6006/runtime~main.iframe.bundle.js:28:33)
    at fn (http://localhost:6006/runtime~main.iframe.bundle.js:323:25)
    at ./node_modules/@storybook/addon-links/dist/preview.mjs (http://localhost:6006/vendors-node_modules_storybook_react_preview_js-node_modules_storybook-addon-apollo-client_di-ff1302.iframe.bundle.js:77188:77)
    at __webpack_require__ (http://localhost:6006/runtime~main.iframe.bundle.js:28:33)
    at fn (http://localhost:6006/runtime~main.iframe.bundle.js:323:25)
    at Object.getProjectAnnotations [as nextFn] (http://localhost:6006/main.iframe.bundle.js:118:582)
    at http://localhost:6006/sb-preview/runtime.mjs:4:78491
    at Array.forEach (<anonymous>)
    at SynchronousPromise4._runResolutions (http://localhost:6006/sb-preview/runtime.mjs:4:78432)

**Comment by valentinpalkovic** [comment]
Please delete your yarn.lock/package-lock file, delete your node_modules and reinstall all dependencies. Does the error still occur?

**Comment by erwan-joly** [comment]
yes it does still occur

**Comment by shilman** [comment]
@tmeasday @ndelangen probable dupe to the one you were looking at for BBC

**Comment by codejunkienick** [comment]
Happened to me as well when I've upgraded from beta.28 to beta.60

**Comment by erwan-joly** [comment]
I do have webpackFinal
‘’’
const custom = require('../webpack.server.config.js');
module.exports = {
    stories: [
        "../src/**/*.mdx",
        "../src/**/*.stories.@(js|jsx|ts|tsx)"
    ],
    addons: [
        "@storybook/addon-links",
        "@storybook/addon-essentials",
        "@storybook/addon-interactions",
        "storybook-addon-apollo-client",
        "storybook-addon-react-router-v6"
    ],
    framework: {
        "name": "@storybook/react-webpack5",
        "options": {}
    },
    staticDirs: ['../public'],
    webpackFinal: async (config) => {
        return { ...config, module: { ...config.module, rules: custom.module.rules } };
    },
    docs: {
        "docsPage": true
    }
}
‘’’

**Comment by ndelangen** [comment]
@erwan-joly 

```
        return { ...config, module: { ...config.module, rules: custom.module.rules } };
```

...that throws away all of storybook's loaders!

**Comment by erwan-joly** [comment]
removing that line seems to solve the issue. Not sure why it was working before tho

**Comment by tmeasday** [comment]
Hmm @ndelangen it seems at the very least we have a documentation issue, possibly a larger migration problem--any thoughts on why that would have worked in 6.5 but not now?

**Comment by erwan-joly** [comment]
It was working in 7.0.0-beta.52

**Comment by ndelangen** [comment]
@erwan-joly when you upgraded from 7.0.0-beta.52 to the newer beta, did anything else change with it?

I'll open a PR with the documentation fix.

**Comment by erwan-joly** [comment]
Nope that’s the only change reverting to 52 solve the issue. Note: i updated all the packages from storybook to the same version but I believe that’s the normal thing to do anyway

**Comment by tmeasday** [comment]
@erwan-joly can you try adding this line to your `rules` section:

https://github.com/storybookjs/storybook/blob/b125f358cfe900d0250bf92efe47f5e5d9a83742/code/lib/builder-webpack5/src/preview/iframe-webpack.config.ts#L281-L284

**Comment by shilman** [comment]
Jeepers creepers!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.62 containing PR #21421 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```

**Comment by ekeijl** [comment]
Hi, I'm encountering a similar bug in a different environment.

The issue is that global variable `module` is undefined [here](https://github.com/storybookjs/storybook/blob/7e838f7dd3f465751c5393435a70a7ebcf07997e/code/renderers/react/src/index.ts#L11).

I'm trying to write a Cypress test that mounts Storybook stories using `@storybook/react composeStories` (previously `@storybook/testing-react`).

```js
// storybook.cy.js
import { mount } from 'cypress/react';
import { composeStories, setProjectAnnotations } from '@storybook/react';

before(() => {
	setProjectAnnotations(globalStorybookConfig);
});

describe('Storybook tests', () => {
	// Find all stories in src
	const resolve = require.context('../src/', true, /\.\/.*\.stories.jsx$/);

	// Resolve the module and wrap in cypress alias
	resolve.keys().forEach((path) => {
		const module = resolve(path);
		// composeStories() creates a React <Story /> component for every export that can be rendered
		const stories = composeStories(module);
                describe(`Stories for ${path}`, () => {
			Object.entries(stories).forEach((composed) => {
				const [StoryName, Story] = composed;
				it(`should render ${StoryName}`, () => {
					mount(<Story />);
				});
			});
		});
	});
});
```

Cypress uses its own Webpack configuration, so I think hot reloading is completely irrelevant in this scenario.
Should a similar fix be applied here?

Using Storybook v7.0.3 and Cypress v12.5.1.

I have a workaround, by defining module in the Cypress webpack config:

```
new DefinePlugin({
	module: {},
}),
```
