### ISSUE TITLE
[Bug]: Can't add new languages to syntax highlighter

### ISSUE THREAD

**Issue by jnschrag** [storybookjs/storybook#21341]
### Describe the bug

The syntax highlighting for additional languages at a project-level for use in `.mdx` files doesn't work after following the instructions from the [6.5 docs](https://storybook.js.org/docs/react/writing-docs/mdx#syntax-highlighting). For example, adding highlighting for `scss` and `svelte` does not work in this [`.mdx` file](https://github.com/jnschrag/storybook-syntax-highlighting/blob/main/src/lib/Introduction.mdx?plain=1). 

### To Reproduce

Test repo: https://github.com/jnschrag/storybook-syntax-highlighting

Includes importing of `scss` highlighting from `react-syntax-highlighter` and a custom highlighter for `.svelte` files.

### System

```shell
Environment Info:

  System:
    OS: macOS 11.7.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 16.15.1 - ~/.n/bin/node
    npm: 8.11.0 - ~/.n/bin/npm
  Browsers:
    Chrome: 110.0.5481.177
    Firefox: 110.0.1
    Safari: 16.3.1
  npmPackages:
    @storybook/addon-actions: ^7.0.0-beta.59 => 7.0.0-beta.59 
    @storybook/addon-essentials: ^7.0.0-beta.59 => 7.0.0-beta.59 
    @storybook/addon-interactions: ^7.0.0-beta.59 => 7.0.0-beta.59 
    @storybook/addon-links: ^7.0.0-beta.59 => 7.0.0-beta.59 
    @storybook/addon-mdx-gfm: ^7.0.0-beta.59 => 7.0.0-beta.59 
    @storybook/addon-svelte-csf: ^3.0.0-next.3 => 3.0.0-next.3 
    @storybook/svelte: ^7.0.0-beta.59 => 7.0.0-beta.59 
    @storybook/sveltekit: ^7.0.0-beta.59 => 7.0.0-beta.59 
    @storybook/testing-library: ^0.0.14-next.1 => 0.0.14-next.1
```

### Additional context

@JReinhold looked at this with me on [Discord](https://discord.com/channels/486522875931656193/1080530799780179988) and thinks it might be a regression.

**Comment by JReinhold** [comment]
@ndelangen without investigating this, I think this happens because we're prebundling [`react-syntax-highlighter`_ in `@storybook/components`](https://github.com/storybookjs/storybook/blob/next/code/ui/components/package.json#L70), and so when the user imports it and registers languages in `preview.js`, they are actually importing another instance of the package, causing the registrering to not have any effect.

Does that sound plausible to you?

**Comment by ndelangen** [comment]
Yes, that makes sense.

**Comment by marcosmko** [comment]
Seems like this stopped working on version `6.5.10`.
The previous version (`6.5.9`) works.

**Comment by timbomckay** [comment]
I'm a little confused on this. I see this was recently added as "nice to have" for v7 but it's also mentioned in the FAQs (https://storybook.js.org/docs/7.0/vue/faq#why-arent-my-code-blocks-highlighted-with-storybook-mdx). I spent a couple of hours trying to figure this out with v7-rc5 to no avail.

Is it working and I'm just having an issue on my end? Is this a known issue for the Vue instance but works for React? Or is it something still in the works and the documentation needs to be removed or updated?

**Comment by hobbes7878** [comment]
Hi there. Saw this issue moving off core team. It's the last unfortunate hurdle that's keeping my team from upgrading, so I'd like to help if I can.

Before we crash the gates with PRs, though, I wonder if maintainers have opinions on their preferred solve. 

To keep `react-syntax-highlighter` pre-bundled, I _think_ I only see two options:
1. Be more liberal in [what languages get registered by default](https://github.com/storybookjs/storybook/blob/68e264171bc0719bda283cf339af78f6b6f16b06/code/ui/components/src/syntaxhighlighter/syntaxhighlighter.tsx#L36-L46). I can make a case at least for the core and community frameworks as advertised, e.g., Vue and Svelte. That doesn't solve various flavours of, for example, SCSS, though.
2. Drill some user config down through props to [SyntaxHighlighter](https://github.com/storybookjs/storybook/blob/68e264171bc0719bda283cf339af78f6b6f16b06/code/ui/components/src/syntaxhighlighter/syntaxhighlighter.tsx#L192). That's a big props chain, though, from what I can tell before we have access to any user-defined config, unless there's a shortcut I'm missing.

Anyway, grateful for any nominal direction and happy to put the time in to get this out of the way of more folks who want to jump to v7. Thanks.
