### ISSUE TITLE
[Bug]: Docs: `typeof` only needed for React and Svelte

### ISSUE THREAD

**Issue by IanVS** [storybookjs/storybook#21360]
### Describe the bug

In the docs, the CSF3 examples all use `typeof MyComponent`, but that is only needed for some frameworks, and not all.  If you use it for Lit, Angular, Vue, etc, you'll hit errors.  See referenced discord conversation below.

### Additional context

https://discord.com/channels/486522875931656193/1079734821812703232/1080041263316869220

**Comment by kasperpeulen** [comment]
@jonniebigodes I'm sorry, it is actually Lit, Angular and Svelte that don't need it, because they are class based.

Vue, React do need the `typeof` before the component, and html will need it as well once we at typesafety there as well
