### ISSUE TITLE
[Bug]: ArgsTable does not work unattached

### ISSUE THREAD

**Issue by tmeasday** [storybookjs/storybook#21366]
### Describe the bug

If you use:

```mdx
<ArgsTable of="example-button--primary" />
```

You get:

```
Uncaught (in promise) Error: No primary story defined for docs entry. Did you forget to use `<Meta>`
```

### To Reproduce

Add 

```md
<ArgsTable of="example-button--primary" />
```

to `Introduction.mdx` in a sandbox.

**Comment by tmeasday** [comment]
@shilman AFAICT that API is not allowed, `of` is supposed to be either `&` or a component? -- code on `main`: 

https://github.com/storybookjs/storybook/blob/f77cdd1c2fe07636dcc8a19380aa1d946b4c5cea/code/ui/blocks/src/blocks/ArgsTable.tsx#L33

**Comment by shilman** [comment]
@tmeasday You transcribed the issue wrong. In AstroDS the code is:

```
<ArgsTable of="rux-button-group" />
```

And `rux-button-group` is a Component in the web-components renderer.

**Comment by shilman** [comment]
Yay!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.62 containing PR #21371 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```
