### ISSUE TITLE
[Bug]: Error accessing to storybook doc pages 

### ISSUE THREAD

**Issue by alvaroperezmeza** [storybookjs/storybook#21364]
### Describe the bug

Right now the only way of accessing specific documentation pages of our storybook project is by going to the root page and using the navigation bar. If we copy the URL of any page and try to access it directly, we get a 404, e.g: https://xxxxxxx/?path=/story/react-developers-intro--page

![Screenshot 2023-03-02 at 17 57 54](https://user-images.githubusercontent.com/100375503/222582590-608086e5-e77d-4bc6-92a7-77fd56e79b5a.png)
![Screenshot 2023-03-02 at 18 00 08](https://user-images.githubusercontent.com/100375503/222582624-2adadc23-78e7-42ea-a175-e9a60647b47f.png)
 Currently, we are using these storybook dependencies
`"devDependencies": {
    "@storybook/addon-actions": "^6.5.16",
    "@storybook/addon-essentials": "^6.5.16",
    "@storybook/addon-interactions": "^6.5.16",
    "@storybook/addon-links": "^6.5.16",
    "@storybook/builder-webpack5": "^6.5.16",
    "@storybook/manager-webpack5": "^6.5.16",
    "@storybook/node-logger": "^6.5.16",
    "@storybook/preset-create-react-app": "^4.1.2",
    "@storybook/testing-library": "^0.0.13",
    "babel-plugin-named-exports-order": "^0.0.2",
    "eslint": "^8.21.0",
    "eslint-config-airbnb-typescript-prettier": "^5.0.0",
    "eslint-plugin-storybook": "^0.6.11",
    "prettier": "^2.7.1",
    "prop-types": "^15.8.1",
    "typescript": "^4.7.4",
    "webpack": "^5.73.0"
  }`
`"dependencies": {
    "@loadable/component": "^5.15.2",
    "@storybook/addon-docs": "^6.5.16",
    "@storybook/api": "^6.5.16",
    "@storybook/react": "^6.5.16",
    "@storybook/theming": "^6.5.16",
    "@testing-library/jest-dom": "^5.16.4",
    "@testing-library/react": "^13.3.0",
    "@testing-library/user-event": "^13.5.0",
    "@types/jest": "^27.5.2",
    "@types/loadable__component": "^5.13.4",
    "@types/node": "^16.11.41",
    "@types/react": "^18.0.14",
    "@types/react-dom": "^18.0.5",
    "clsx": "^1.2.1",
    "highcharts": "^10.2.0",
    "highcharts-react-official": "^3.1.0",
    "react": "^18.2.0",
    "react-aria": "^3.19.0",
    "react-dom": "^18.2.0",
    "react-scripts": "5.0.1",
    "sass": "^1.53.0",
    "storybook-addon-designs": "^6.3.1",
    "storybook-addon-state": "^1.0.3",
    "web-vitals": "^2.1.4"
  },`

and we are running storybook with this command `start-storybook -p xxxx public`

What could be the issue? Thanks for your attention

**Comment by shilman** [comment]
Do you a have a reproduction repo you can share? If not, can you create one? See [how to create a repro](https://storybook.js.org/docs/react/contribute/how-to-reproduce). Thank you! 🙏

**Comment by alvaroperezmeza** [comment]
> Do you a have a reproduction repo you can share? If not, can you create one? See [how to create a repro](https://storybook.js.org/docs/react/contribute/how-to-reproduce). Thank you! 🙏

The thing is that when you run the project locally, it works fine, the problem is when the project is in the production server, so is there something that we should config, enable or disable to avoid this happening? do you have error reports similar to this one?
