### ISSUE TITLE
[Bug]: Syntax Highlight does not work in vite and vue3 when writing MDX

### ISSUE THREAD

**Issue by wre232114** [storybookjs/storybook#21374]
### Describe the bug

The project is a full new project initialized by "npx storybook init", and then I add the following code:

<img width="480" alt="image" src="https://user-images.githubusercontent.com/8372439/222698197-a052b80d-34ae-4848-939f-0360459258b1.png">

But Syntax hightlight does not work. The docs says it should be work out of box.
<img width="567" alt="image" src="https://user-images.githubusercontent.com/8372439/222698683-1a76a371-99c5-48ce-98d8-8bb8f44a6473.png">

**Comment by shilman** [comment]
@wre232114 do you have a reproduction you can share? I tried the example above and it's working fine for me.
