### ISSUE TITLE
[Bug]: Docs: Rendering story breaks when browsing away

### ISSUE THREAD

**Issue by riovir** [storybookjs/storybook#21381]
### Describe the bug

Since the v[7.0.0.beta-58](https://github.com/storybookjs/storybook/pull/21214) added a [setTimeout(() => cleanup(), 0)](https://github.com/storybookjs/storybook/blob/ebb8cf2a5021f375d5ceb92fcd42e0418fb770d8/code/ui/blocks/src/components/Story.tsx#L63) to the Vue stories shown in the docs are broken when navigating to another docs page. There's a quick blinking effect that can be barely seen:
- the story renders
- then disappears

My suspicion is that the cleanup's delay causes the new story to be wiped away.

### To Reproduce

Take a basic Vue 3 Storybook (Vite, Webpack doesn't matter), and add two components with docs. Upon navigating from one docs page to the other, the Docs page base story example blinks out of existence.

### Additional context

This issue is related to https://github.com/storybookjs/storybook/issues/20731
Undoing the setTimeout (essentially backing the previous PR out) fixes this particular issue.

**Comment by tmeasday** [comment]
I think this was fixed by https://github.com/storybookjs/storybook/pull/21476 -- @riovir have you tried v7.0.0-beta.63 or later?

**Comment by riovir** [comment]
Jest, the latest Release Candidate (RC.8) fixed this issue. I consider it closed on my part.
