### ISSUE TITLE
[Bug]: MIME Type Error When Deploying Storybook with Vue3 and Vite

### ISSUE THREAD

**Issue by nebojsa91markovic** [storybookjs/storybook#21388]
### Describe the bug

I migrated our project to Vue 3 Vite and Storybook v7.0.0-beta.60, and I am trying to publish static storybook web from inside of `./dist ` folder built using `vite build`.
When I try to access my storybook page as e.g. `http://mywebsite.com/storybook` I get this error in console:
`Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.`

Previously, before migrating I was able to do the same using Vue 2 + babel + Storybook 6.4.0

### To Reproduce

I run script `npm run build` - script looks like this:
`"build": "npm run build-web && npm run build-storybook",
"build-web": "vite build",
"build-storybook": "build:storybook --output-dir ./dist/storybook",`

From inside of main.ts from .storybook, my config file contains this portion:
`  "framework": {
    "name": "@storybook/vue3-vite",
    "options": {}
  },
  "core": {
    "builder": "@storybook/builder-vite",
  },`
  

### System

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE    
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD       
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (110.0.1587.57)
  npmPackages:
    @storybook/addon-essentials: ^7.0.0-beta.60 => 7.0.0-beta.60
    @storybook/addon-interactions: ^7.0.0-beta.60 => 7.0.0-beta.60
    @storybook/addon-links: ^7.0.0-beta.60 => 7.0.0-beta.60
    @storybook/addon-mdx-gfm: ^7.0.0-beta.60 => 7.0.0-beta.60
    @storybook/blocks: ^7.0.0-beta.60 => 7.0.0-beta.60
    @storybook/builder-vite: ^7.0.0-beta.60 => 7.0.0-beta.60
    @storybook/testing-library: ^0.0.14-next.1 => 0.0.14-next.1
    @storybook/vue3: ^7.0.0-beta.60 => 7.0.0-beta.60
    @storybook/vue3-vite: ^7.0.0-beta.60 => 7.0.0-beta.60
```

**Comment by nebojsa91markovic** [comment]
OK, I found a solution that helped me, I will leave a comment here cause someone can benefit from it in the future.

I am still not sure what caused this problem, so I will not close this issue yet. My assumption is that this has something to do with how viteFinal resolves extensions in _main.ts_ file.

The problem occurred when storybook tried to access some `mjs` files, that were stored into _/dist/storybook/sb-manager_ subfolder of storybook.

My solution was to add this into my _Web.config_ file

``` <system.webServer>
    <staticContent>
      <remove fileExtension=".mjs" /> 
      <mimeMap fileExtension=".mjs" mimeType="text/javascript" />
    </staticContent>
  </system.webServer> ```
```````

More about why I needed to first remove and than add fileExtension you can read in the answer Eric Barr provided:
https://stackoverflow.com/a/24725233/21340957
It is connected due that IIS 8+ is duplicating mimeType.

**Comment by IanVS** [comment]
@nebojsa91markovic how are you opening the built files?  You mention IIS.  Does storybook load correctly if you use something like `npx http-server ./dist/storybook`?  It might be an issue in IIS itself, perhaps it doesn't support ES modules correctly?

**Comment by nebojsa91markovic** [comment]
> @nebojsa91markovic how are you opening the built files? You mention IIS. Does storybook load correctly if you use something like `npx http-server ./dist/storybook`? It might be an issue in IIS itself, perhaps it doesn't support ES modules correctly?

Yes, storybook can run locally, so it is connected to do with IIS definitely. But I would not say it's only because of the IIS, because the same IIS version used to work, as I mention above with Vue2 + babel + Storybook 6.4.
So I still think the problem is with _builder-vite_ cause once I _mimeMap_ _.mjs_ file extensions it works.

@shilman I written an article that might provide more info about this issue that I had and how I workaround it. If I can help somehow please don't hesitate to ask.

**Comment by IanVS** [comment]
One change between 6.4 and 7.0 is the inclusion of `<script type="module">`, which we didn't have before.  I don't think this is a bug in storybook though, since it's working fine in other web servers.

**Comment by nebojsa91markovic** [comment]
When I tried to deploy this to Chromatic, everything is working correctly.
So, it might only be a problem with this approach _build vue => build storybook inside of /dist_ and when trying to access _http://mywebpage.com/storybook_ it gets confused somehow when trying to map _.mjs_ files
 
So probably it is only connected to _IIS8^_  but I would not exclude completely _builder_vite_ Do you know if can confirm this somehow?

**Comment by soullivaneuh** [comment]
It looks like an http server configuration issue, please see https://github.com/storybookjs/storybook/issues/20157#issuecomment-1500456820.

**Comment by siggerzz** [comment]
We're also seeing this issue when trying to deploy to AWS Amplify. We're in touch with AWS and they're looking into this, just in case anyone else is using the same deployment mechanism!

**Comment by spencercampbell42** [comment]
> We're also seeing this issue when trying to deploy to AWS Amplify. We're in touch with AWS and they're looking into this, just in case anyone else is using the same deployment mechanism!

Did you ever find a solution to this issue with Amplify?
