### ISSUE TITLE
[Bug]: Broken React 18 peer dependency when installing `sb@next` having old(?) `@storybook/blocks 7.0.0-alpha.8` with outdated @mdx-js/react version

### ISSUE THREAD

**Issue by D1no** [storybookjs/storybook#21396]
### Describe the bug

Just installed the latest storybook 7 version in our `pnpm` monorepo, where react 18.2 is global and got the following. Not sure why `@mdx-js/react` is at version `1.6.22` in SB <-> while the latest [release of mdx](https://github.com/mdx-js/mdx/releases) is `2.3.0` at time of writing (?)

```cpp
 ERR_PNPM_PEER_DEP_ISSUES  Unmet peer dependencies

_tooling/storybook
└─┬ @storybook/blocks 7.0.0-alpha.8
  └─┬ @mdx-js/react 1.6.22
    └── ✕ unmet peer react@"^16.13.1 || ^17.0.0": found 18.2.0
```

### To Reproduce

_Using `pnpm@7.28.0` (latest stable) though this dependency problem is package manager unrelated._

#### Strict Peer Dependencies

Create `.npmrc` file with 
```ini
strict-peer-dependencies = true
```

#### Add React 18 to empty project
```shell
pnpm install react
```

#### Init Storybook
```shell
pnpx storybook@next init --builder vite
```

# Result during install
```cpp
_tooling/storybook
└─┬ @storybook/blocks 7.0.0-alpha.8
  └─┬ @mdx-js/react 1.6.22
    └── ✕ unmet peer react@"^16.13.1 || ^17.0.0": found 18.2.0

hint: If you don't want pnpm to fail on peer dependency issues,
add "strict-peer-dependencies=false" to an .npmrc file at the root of your project.
```

### System

```shell
Environment Info:

  System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 18.14.1 - ~/.nvs/default/bin/node
    npm: 9.3.1 - ~/.nvs/default/bin/npm
  Browsers:
    Chrome: 110.0.5481.177
    Firefox: 97.0.1
    Safari: 16.3
  npmPackages:
    @storybook/addon-essentials: ^7.0.0-beta.61 => 7.0.0-beta.61 
    @storybook/addon-interactions: ^7.0.0-beta.61 => 7.0.0-beta.61 
    @storybook/addon-links: ^7.0.0-beta.61 => 7.0.0-beta.61 
    @storybook/blocks: ^7.0.0-alpha.8 => 7.0.0-alpha.8 
    @storybook/react: ^7.0.0-beta.61 => 7.0.0-beta.61 
    @storybook/react-vite: ^7.0.0-beta.61 => 7.0.0-beta.61 
    @storybook/testing-library: ^0.0.14-next.1 => 0.0.14-next.1
```

### Additional context

In https://github.com/storybookjs/storybook/issues/20260 and https://github.com/storybookjs/storybook/issues/14119 it was said that mdx was updated in december (?)

**Comment by D1no** [comment]
Here in git on the _next_ branch, `@storybook/blocks` is at version `7.0.0-beta.60`. No idea why a fresh SB install today uses version `7.0.0-alpha.8`. Maybe a project publishing issue? 🤷🏻‍♂️🤷🏻‍♂️

https://github.com/storybookjs/storybook/blob/3ea1a30e4d0dae1ab57aabd284690dd7dccd5fda/code/ui/blocks/package.json#L2-L3

**Comment by D1no** [comment]
Also after installing storybook, depreciated warning for `stable@0.1.8`:

```ccp
_tooling/storybook                       |  WARN  deprecated stable@0.1.8
```

**Comment by ndelangen** [comment]
I suspect it might be a lockfile issue @D1no, try regenerating it?

**Comment by D1no** [comment]
No, it's a fresh install. Also shows up in the (unrelated) storybook reproduction - 

https://github.com/D1no/reproduction-storybook-symlinks-pnpm/commit/92eee472e3e41bca1bbc691d39cb25e043e12f1b

**Comment by D1no** [comment]
Closing this, as with `storybook@7.0.0-beta.62` seems to correctly reference `@storybook/blocks@7.0.0-beta.62` and no longer throws the reported warning! 👏

See
https://github.com/D1no/reproduction-storybook-symlinks-pnpm/commit/5f71f59a5f758b2f4ea17c3add7f6168a31e1d0b
