### ISSUE TITLE
[Bug]: CSF 3.0 objects cannot be spread

### ISSUE THREAD

**Issue by CHE1RON** [storybookjs/storybook#21397]
### Describe the bug

The v7 [docs describe](https://storybook.js.org/blog/component-story-format-3-0/#spreadable-story-objects) CSF 3.0 story objects as being spreadable. I cannot reproduce this behaviour in at least one case:

### To Reproduce

```tsx
// Button.stories.tsx

import { Meta } from '@storybook/react';

import Button from '.';

export const Default = {
  args: {
    disableRipple: true,
    label: 'Default button',
  } as Meta<typeof Button>,
};

export const Outlined = {
  ...Default,
  args: {
    label: 'Outlined button',
    variant: 'outlined',
  } as Meta<typeof Button>,
};
```

However, the `Outlined` button story comes with `disableRipple: false` instead of `true` which means the `Default` story object was not spread correctly.

**Note:**
My `Button` component extends the Material UI v5 one, so `import Button from '.'` is interchangeable with `import { Button } from '@mui/material'`

### System

```shell
System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M2
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    Yarn: 1.22.19 - ~/code/client/node_modules/.bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
  Browsers:
    Chrome: 110.0.5481.177
    Firefox: 110.0
    Safari: 16.3
  npmPackages:
    @storybook/addon-a11y: ^7.0.0-beta.61 => 7.0.0-beta.61
    @storybook/addon-actions: ^7.0.0-beta.61 => 7.0.0-beta.61
    @storybook/addon-essentials: ^7.0.0-beta.61 => 7.0.0-beta.61
    @storybook/addon-interactions: ^7.0.0-beta.61 => 7.0.0-beta.61
    @storybook/addon-links: ^7.0.0-beta.61 => 7.0.0-beta.61
    @storybook/node-logger: ^7.0.0-beta.61 => 7.0.0-beta.61
    @storybook/preset-create-react-app: ^7.0.0-beta.61 => 7.0.0-beta.61
    @storybook/react: ^7.0.0-beta.61 => 7.0.0-beta.61
    @storybook/react-vite: ^7.0.0-beta.61 => 7.0.0-beta.61
    @storybook/test-runner: ^0.10.0-next.8 => 0.10.0-next.8
    @storybook/testing-library: ^0.0.14-next.1 => 0.0.14-next.1
```

**Comment by shilman** [comment]
CSF3's spread semantics are identical to JS, so in your example to "inherit" the args from the `Default` story in `Outlined`, you would do:

```ts
export const Default = {
  args: {
    disableRipple: true,
    label: 'Default button',
  }
};

export const Outlined = {
  ...Default,
  args: {
    ...Default.args,
    label: 'Outlined button',
    variant: 'outlined',
  }
};
```

There is also another mechanism for sharing data, which is that data cascades from the Meta export into stories. So if you set the args in the Meta, you do NOT have to spread:

```ts
export default {
  args: {
    disableRipple: true
  }
};

export const Default = {
  args: {
    label: 'Default button',
  }
};

export const Outlined = {
  ...Default,
  args: {
    label: 'Outlined button',
    variant: 'outlined',
  }
};
```

Hope that helps...

**Comment by CHE1RON** [comment]
Hey there @shilman, your first approach was what I used in the meantime as workaround, but it's way more elegant to "just spread once" 😅

I will go with the second approach, many thanks! I guess there's no need for "one spread serves all", so I'm closing this issue? ❓
