### ISSUE TITLE
[Bug]: Storybook init installs @storybook/blocks@7.0.0-alpha.8 instead of beta

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#21410]
### Describe the bug

<img width="642" alt="image" src="https://user-images.githubusercontent.com/1671563/223056595-453e55d2-253f-4166-8241-61a165485903.png">

### To Reproduce

`pnpx storybook@next init` in a project, check the diff!

**Comment by shilman** [comment]
Great Caesar's ghost!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.62 containing PR #21418 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```
