### ISSUE TITLE
[Bug]: Styles in storybook breaking when using media query in scss modules

### ISSUE THREAD

**Issue by PixeledCode** [storybookjs/storybook#21425]
### Describe the bug

I have tested this with regular media queries and using sass mixins. In both cases, most styles after the media query are not applied to the component. To apply them, I must go to the styling file `component.modules.scss` and save it again which will then apply all the styles. But, if I go back to the storybook file and save it there, the styles are removed again.

The issue is only in the storybook and not in the Nextjs app that is part of the monorepo.

### To Reproduce

Here is the repo: https://github.com/CivicDataLab/opub-mono
`yarn && yarn dev` in root should start the server for both nextjs and storybook

Here is the deployed version on chromatic: https://main--64004009fa0a900a3197549c.chromatic.com/?path=/docs/components-checkboxwithmedia--docs

I have added a component called `CheckboxWithMedia` that has a single media query in its stylesheet which breaks all the styles that comes after it. `Checkbox` has all media queries commented out, so it's working fine

### System

```shell
System:
    OS: macOS 13.2.1
    CPU: (8) x64 Apple M1
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
  Browsers:
    Chrome: 110.0.5481.177
    Firefox: 110.0.1
    Safari: 16.3
  npmPackages:
    @storybook/theming: ^7.0.0-beta.47 => 7.0.0-beta.60
```

### Additional context

I am using version 7.0.0-beta.47 with Vite 4.1.4

**Comment by yannbf** [comment]
Hey @PixeledCode thanks for reporting this issue! I believe this might be coming from https://github.com/chromaui/storybook-addon-pseudo-states actually.

They have an open issue that seems similar to yours: https://github.com/chromaui/storybook-addon-pseudo-states/issues/57

Could you move the discussion there, if it is indeed the same issue?

**Comment by PixeledCode** [comment]
> Hey @PixeledCode thanks for reporting this issue! I believe this might be coming from https://github.com/chromaui/storybook-addon-pseudo-states actually.
> 
> They have an open issue that seems similar to yours: [chromaui/storybook-addon-pseudo-states#57](https://github.com/chromaui/storybook-addon-pseudo-states/issues/57)
> 
> Could you move the discussion there, if it is indeed the same issue?

Ohh, thank you for figuring it out! I'm gonna close this issue and keep a lookout for that one.
