### ISSUE TITLE
[Bug]: Changes to `preview.js` required a manual browser reload to get effect

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#21426]
### Describe the bug

Reported by @tmeasday 

Changing `preview.js` triggered HMR but required a reload. If a project has `preview-head.html` and changes are made in that file, HMR behaves correctly.

### To Reproduce

The reporter used this repo: https://github.com/inkline/inkline

1. Run a Storybook 7 project
2. Make changes to preview.js, e.g.:
```js
// ./preview.js
alert('Hello')
```

The alert should be shown as soon as you save, but it only gives effect once you manually reload the browser page.

**Comment by tmeasday** [comment]
@IanVS this is a vite issues. It seems like in 6.5 when there was a change in `preview.js`, the whole app reloaded. Now it doesn't, which could be better, but it doesn't quite work. What I am seeing:

1. There is a mismatch between the filepath in the event and the file in the `import.meta.hot.accept` block:

**The event:**
![image](https://user-images.githubusercontent.com/132554/223599472-7449da3c-fbe0-4a3f-8681-9e53883b046b.png): 

**The code:**
![image](https://user-images.githubusercontent.com/132554/223599568-80973b3d-6222-4bc2-bdbd-cf11e965e265.png)
![image](https://user-images.githubusercontent.com/132554/223599601-51390ec1-48c0-48c6-8729-6066d417564b.png)

2. When I manually change [the source](https://github.com/storybookjs/storybook/blob/0c7d7cc7772f9e7387a19c4ea42de3370bcb60c2/code/lib/builder-vite/src/codegen-modern-iframe-script.ts#L39) to match them up (not use absolute paths in the `.hot.accept), I see a second issue, which is that the `newConfigEntries` has many `null` items inside. This is actually expected given the [Vite HMR API](https://vitejs.dev/guide/api-hmr.html#hot-accept-deps-cb). I guess this code path has never actually run in Vite.

We probably need to figure out how to handle this (should we re-import all the other annotations, like [the original `getProjectAnnotations`](https://github.com/storybookjs/storybook/blob/0c7d7cc7772f9e7387a19c4ea42de3370bcb60c2/code/lib/builder-vite/src/codegen-modern-iframe-script.ts#L61-L63)?)

**Comment by shilman** [comment]
Yowza!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.64 containing PR #21485 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```
