### ISSUE TITLE
[Bug]: Vite import map is not updated properly for new MDX file

### ISSUE THREAD

**Issue by tmeasday** [storybookjs/storybook#21439]
### Describe the bug

When you create a new `.mdx` file, if you visit it you get an error:

```
importers[path] is not a function
TypeError: importers[path] is not a function
    at importFn (http://localhost:6006/virtual:/@storybook/builder-vite/storybook-stories.js?t=1678161006498:77:31)
    at StoryStore.loadEntry (http://localhost:6006/sb-preview/runtime.mjs:40:10704)
    at async MdxDocsRender.prepare (http://localhost:6006/sb-preview/runtime.mjs:74:6697)
    at async PreviewWeb.renderSelection (http://localhost:6006/sb-preview/runtime.mjs:83:3120)
```

Note the same does not happen for `.stories.*` (including `.stories.mdx`) files.

### To Reproduce

1. Run a vite sandbox (`yarn start`)
2. Load in browser
3. Add a new `.mdx` file (empty or with content is fine)
4. Visit the new entry in the sidebar.
5. Try reloading browser (doesn't help)
6. Make any change to the file (no change)
7. Now reload the browser again (fixes it).

![image](https://user-images.githubusercontent.com/132554/223316337-a0648fc8-228c-4b84-b774-960af8319a08.png)

![image](https://user-images.githubusercontent.com/132554/223316409-85d30ad7-6eca-4bc4-9043-3064ad822ae7.png)

**Comment by tmeasday** [comment]
@IanVS I'm not sure how this works for `.stories.*` files. Somehow the `storybook-stories.js` virtual module is regenerated when a new file is added that matches the glob, can you tell me about where that code is?

When a new `.mdx` file is added, that *doesn't* happen, which means the index gets updated, but the `importFn` does not, leading to the observed behaviour.

**Comment by tmeasday** [comment]
Oh is it this line: 

https://github.com/storybookjs/storybook/blob/0c7d7cc7772f9e7387a19c4ea42de3370bcb60c2/code/lib/builder-vite/src/plugins/code-generator-plugin.ts#L47

Should we drop the `\.(story|stories)` match in front of the `.mdx` part there?

**Comment by IanVS** [comment]
@tmeasday good catch, yes.  Now that stories can be in mdx files that do not include `.stories`, there may actually be a few places we need to update for vite, that I didn't think of previously.  Another is here:

https://github.com/storybookjs/storybook/blob/20156b94044dd648866a177327fa4fb09a650dee/code/lib/builder-vite/src/plugins/mdx-plugin.ts#L5

Though I'm not positive whether it needs to change or not based on how it's being used.

Does the "export order" matter for these new mdx files?  

https://github.com/storybookjs/storybook/blob/20156b94044dd648866a177327fa4fb09a650dee/code/lib/builder-vite/src/plugins/inject-export-order-plugin.ts#L5

**Comment by shilman** [comment]
Yo-ho-ho!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.64 containing PR #21490 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```
