### ISSUE TITLE
[Bug]:  "ExperimentalWarning: The Fetch API is an experimental feature" shown during storybook commands in node v18

### ISSUE THREAD

**Issue by kasperpeulen** [storybookjs/storybook#21432]
### Describe the bug

We use `isomorphic-unfetch` that will use the actual fetch implementation in node 18.
However, this will cause warnings:

![image](https://user-images.githubusercontent.com/1035299/223175308-babb7104-10b5-45c0-be50-7d520c168771.png)

We should probably move to node-fetch, or conditionally use isomorphic-unfetch only when the environment is node 19, where the fetch impl. is stable.

### To Reproduce

Start storybook v7 in node 18.

**Comment by tmeasday** [comment]
@kasperpeulen I wasn't able to reproduce this in a sandbox:

<img width="969" alt="image" src="https://user-images.githubusercontent.com/132554/223933208-e38e828d-2167-4a26-95a8-d47590b7c7db.png">

Am I missing something? What node version did you use exactly?

**Comment by kasperpeulen** [comment]
@tmeasday This only happens in node 18 and (when telemetry enabled I guess). 

<img width="1029" alt="image" src="https://user-images.githubusercontent.com/1035299/223960909-9706a0f8-8230-4258-bc57-27f7b2775c2a.png">

**Comment by kasperpeulen** [comment]
Also happens for me in a sandbox when using node 18:

<img width="995" alt="image" src="https://user-images.githubusercontent.com/1035299/223975607-0ee80b06-8008-4f8c-ab43-a7d4b160b80f.png">

**Comment by tmeasday** [comment]
@kasperpeulen i was running node 18 (see screenshot) and telemetry was definitely enabled. 

Which version of node 18 did you have exactly?

**Comment by tmeasday** [comment]
Oh, 18.12 I see. I'll try that version

**Comment by kasperpeulen** [comment]
I can confirm that I don't see this message in next when using node 18.

**Comment by shilman** [comment]
Crikey!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-rc.0 containing PR #21497 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```

**Comment by tmeasday** [comment]
OK, I see this warning (on older versions) in node 18.12 but not 18.15. I think we should revert, we shouldn't risk making late changes to telemetry for specific minor node versions.

**Comment by tmeasday** [comment]
https://github.com/storybookjs/storybook/pull/21526
