### ISSUE TITLE
[Bug]: Typeset block from @storybook/blocks doesn't account for dark mode in docs view

### ISSUE THREAD

**Issue by valentinpalkovic** [storybookjs/storybook#21430]
### Describe the bug

Reported by @yannbf 

The [Typeset block](https://storybook.js.org/docs/7.0/react/api/doc-block-typeset) in `@storybook/blocks` doesn't account for dark mode in docs view:

![image](https://user-images.githubusercontent.com/5889929/223163312-73bd5ab4-964c-47bb-99a1-f0636621697d.png)

### To Reproduce

The reporter used this repo: https://github.com/yannbf/mealdrop

1. Create a sandbox
2. Create a Typography.mdx like described [here](https://storybook.js.org/docs/7.0/react/api/doc-block-typeset)
3. Switch to dark mode. The font color is still black.

**Comment by shilman** [comment]
Closing as dupe to  #21080
