### ISSUE TITLE
[Bug]: Manager.js caching prevents changes in theming

### ISSUE THREAD

**Issue by valentinpalkovic** [storybookjs/storybook#21443]
### Describe the bug

Reported by @yannbf 

Changing themes is slightly frustrating, as the manager.js file is cached by the browser, e.g. http://localhost:6006/sb-addons/storybook-11/manager-bundle.mjs

And as a result, if you change your theme to something else (e.g. from light to dark mode), it seems like Storybook didn't do anything. Busting the cache in the browser does the job, but it doesn't feel great. In this gif, you can see that I can refresh many times and Storybook still uses the previous theme. After hard refreshing, it works.

![image](https://user-images.githubusercontent.com/5889929/223363269-96aa5de9-5835-4d2a-a017-930e1af01493.png)

### To Reproduce

- Create a sandbox
- Startup the sandbox
- Change the theme in `manager.js`
- Go back to the browser. Theme only updates after a hard refresh

**Comment by shilman** [comment]
w00t!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-rc.4 containing PR #21574 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```
