### ISSUE TITLE
[Bug]: `<Story of={obj.undefined} />` renders the primary story

### ISSUE THREAD

**Issue by tmeasday** [storybookjs/storybook#21441]
### Describe the bug

If you pass the wrong key into `<Story of />` the behaviour is equivalent to `<Story />` which is confusing

### To Reproduce

```
import { Meta, Story  } from '@storybook/blocks';
import * as ButtonStories from './Button.stories';

<Meta of={ButtonStories} />
<Story of={ButtonStories.Primar} />

<Story />
```

### Additional context

We can check for `'of' in props` to distinguish the two.

**Comment by shilman** [comment]
ZOMG!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.64 containing PR #21452 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```
