### ISSUE TITLE
[Bug]: unexpected 'parameters'. Parameters 'options.storySort' should be defined inline e.g. ...

### ISSUE THREAD

**Issue by developenguin** [storybookjs/storybook#21455]
### Describe the bug

Since updating from V7 beta 57 to beta 62 I've run into this issue where no stories will load and throw the error 'options.storySort should be defined inline e.g. ...). Couldn't find any indications in the release notes as to what could cause this.

I've tried
- Defining the option in the parameters in preview.tsx
- Removing the parameters object altogether

### To Reproduce

https://github.com/developenguin/storybook-storysort-bug

To reproduce:
run `yarn install`
run `yarn storybook`
Observe that an error is shown

### System

```shell
Environment Info:

  System:
    OS: Linux 5.19 Linux Mint 21.1 (Vera)
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
  Binaries:
    Node: 18.12.1 - ~/n/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.19.2 - ~/n/bin/npm
  Browsers:
    Firefox: 111.0b6
  npmPackages:
    @storybook/addon-actions: ^7.0.0-beta.62 => 7.0.0-beta.62 
    @storybook/addon-essentials: ^7.0.0-beta.62 => 7.0.0-beta.62 
    @storybook/addon-links: ^7.0.0-beta.62 => 7.0.0-beta.62 
    @storybook/mdx2-csf: ^1.0.0-next.5 => 1.0.0-next.5 
    @storybook/nextjs: ^7.0.0-beta.62 => 7.0.0-beta.62 
    @storybook/react: ^7.0.0-beta.62 => 7.0.0-beta.62
```

**Comment by shilman** [comment]
Thanks for the reproduction! This is indeed a bug, and an annoying one -- will fix today.

**Comment by shilman** [comment]
Gadzooks!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.63 containing PR #21481 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```
