### ISSUE TITLE
[Bug]: Story in Docs is not rendered after upgrading to v7.0.0-beta.58

### ISSUE THREAD

**Issue by ozguruysal** [storybookjs/storybook#21467]
### Describe the bug

After upgrading to v7.0.0-beta.58 and onwards, stories when "Docs" is selected in sidebar intermittently fails to render. It's just empty with no errors in console.

Clicking one of the other stories then going back to "Docs" renders it fine.

https://user-images.githubusercontent.com/53624/223563806-b19f7cfc-ef99-4b16-b2ee-30f5ee4bb534.mov

### System

```shell
Environment Info:

  System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 16.18.0 - ~/.nvm/versions/node/v16.18.0/bin/node
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.0/bin/npm
  Browsers:
    Chrome: 110.0.5481.177
    Safari: 16.3
  npmPackages:
    @storybook/addon-a11y: 7.0.0-beta.58 => 7.0.0-beta.58 
    @storybook/addon-essentials: 7.0.0-beta.58 => 7.0.0-beta.58 
    @storybook/addon-interactions: 7.0.0-beta.58 => 7.0.0-beta.58 
    @storybook/addon-links: 7.0.0-beta.58 => 7.0.0-beta.58 
    @storybook/addons: 7.0.0-beta.58 => 7.0.0-beta.58 
    @storybook/blocks: 7.0.0-beta.58 => 7.0.0-beta.58 
    @storybook/manager-api: 7.0.0-beta.58 => 7.0.0-beta.58 
    @storybook/react: 7.0.0-beta.58 => 7.0.0-beta.58 
    @storybook/react-vite: 7.0.0-beta.58 => 7.0.0-beta.58 
    @storybook/testing-library: 0.0.14-next.1 => 0.0.14-next.1 
    @storybook/theming: 7.0.0-beta.58 => 7.0.0-beta.58
```

**Comment by shilman** [comment]
Do you a have a reproduction repo you can share? If not, can you create one? See [how to create a repro](https://storybook.js.org/docs/react/contribute/how-to-reproduce). Thank you! 🙏

**Comment by ozguruysal** [comment]
I updated to v7.0.0-rc.1 today and I don't see the issue anymore. It must have been fixed somewhere. Thank you 👍 , and closing this.
