### ISSUE TITLE
[Bug]: Fail rather than warn if you name an attached docs entry the same as a story

### ISSUE THREAD

**Issue by tmeasday** [storybookjs/storybook#21478]
### Describe the bug

There are various ways you can name an attached docs entry the same name as a story `MyStory`:

- Call the file `MyStory.mdx`
- Use `<Meta of={...} name="MyStory" />`
- Set the `docs.defaultName` option to `"MyStory"`.

Currently we warn about this. We should just error, the warning is easily lost and leads to weird ordering and no docs entry.

```
> WARN 🚨 You have a story for Example/Button with the same name as your component docs page (Secondary), so the docs page is being dropped. Use <Meta of={} name="Other Name"> to distinguish them.
```

### To Reproduce

1. Create a file `Secondary.mdx` with:
```mdx
import { Meta } from '@storybook/blocks';
import * as ButtonStories from './Button.stories';

<Meta of={ButtonStories} />
```

**Comment by tmeasday** [comment]
@shilman do you think we should also fail (instead of warn) if you have two MDX files with the same name?

**Comment by shilman** [comment]
@tmeasday Yes that sounds like a fail to me!
