### ISSUE TITLE
[Bug]: storyIndex V2 is not supported in composition

### ISSUE THREAD

**Issue by ndelangen** [storybookjs/storybook#21479]
### Describe the bug

When composing a storybook that has a v2 storyIndex JSON file, the resulting sidebar doesn't have the correct structure.

![Image](https://user-images.githubusercontent.com/3070389/222403156-37ecc040-cbcc-4c20-97b4-88ac1694da20.png)

**Comment by shilman** [comment]
Whoopee!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.64 containing PR #21354 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```
