### ISSUE TITLE
[Bug]: Svelte stories that use a decorator show `<SlotDecorator>` as source

### ISSUE THREAD

**Issue by tmeasday** [storybookjs/storybook#21477]
### Describe the bug

The Svelte snippet generator fails if you use a decorator.

![image](https://user-images.githubusercontent.com/5678122/223712810-992481f3-12d8-4a60-b858-9f4a58fc4477.png)

### To Reproduce

1. Start a Svelte sandbox.
2. Add a decorator

```js
// .storybook/preview.js
import SomeDecorator from './SomeDecorator.svelte';

/** @type { import('@storybook/svelte').Preview } */
const preview = {
  parameters: {
    backgrounds: {
      default: 'light',
    },
    actions: { argTypesRegex: '^on[A-Z].*' },
    controls: {
      matchers: {
        color: /(background|color)$/i,
        date: /Date$/,
      },
    },
  },
  decorators: [() => SomeDecorator]
};

export default preview;

```

```svelte
// .storybook/SomeDecorator.svelte
<div>
	decorated
	<slot/>
</div>
```

3. Open an autodoc and click "Show code"
4. See that the component name is always "SlotDecorator", which is incorrect.

### Additional context

`SlotDecorator` is an internal component used in the Svelte renderer.

**Comment by hugohaggmark** [comment]
Hi there, any updates or plan on fixing this issue?

**Comment by hugohaggmark** [comment]
Hi @tmeasday, can I help out fixing this issue? If so can you point me in the right direction, I haven't contributed to Storybook (yet). Thank you 🙏

**Comment by tmeasday** [comment]
@hugohaggmark sorry about the lack of response! I asked @JReinhold for his opinion and accidentally nerd sniped him into fixing it 😆 not my intention!

**Comment by hugohaggmark** [comment]
Great news @tmeasday and @JReinhold 🙌 , thank you!
