### ISSUE TITLE
[Bug]: Composition - switching stories within a composed storybook shows spinners and reloads

### ISSUE THREAD

**Issue by ndelangen** [storybookjs/storybook#21499]
### Describe the bug

Issue extracted from: https://github.com/storybookjs/storybook/issues/21352

@yannbf reported some of these in QA as well.

When visiting composed stories, the preview completely reloads after a second. 
This is composing the SB Design system.

![2023-03-07 18 30 44](https://user-images.githubusercontent.com/3070389/223967068-6f533043-5c13-4452-bf20-6af681a1bd32.gif)

Here's another example showing the difference between a composed storybook and the uncomposed:

![2023-03-07 18 36 09](https://user-images.githubusercontent.com/3070389/223968311-09414c63-9a22-4bf4-a224-7416d8a70419.gif)

---

Changing controls to a composed Storybook seems to reload the entire preview.

### To Reproduce

- Add a ref to the `code/ui/.storybook/main.ts` file.
  ```js
  refs: {
    'design-system': {
      title: 'Design System',
      url: 'https://master--5ccbc373887ca40020446347.chromatic.com/',
    },
  },
  ```
- start the storybook
- switch stories

**Comment by tmeasday** [comment]
Note that this also occurs in 6.5 -- this has been an issue for some time; it happens due to changing the `src` attribute on the ref's `iframe`, IIUC. In fact I am struggling to pin down exactly when it first occurred; it may have been an issue from the start with composition!

I would love to fix it but not sure about the riskiness of changing it at this stage @ndelangen @shilman.

**Comment by ndelangen** [comment]
@tmeasday WDYT about:
```
  return (
    <Fragment>
      <Global styles={styles} />
      <Consumer filter={whenSidebarIsVisible}>
        {({ isFullscreen, showNav, selectedStoryId }) => {
          if (!isFullscreen && !!showNav && selectedStoryId) {
            return (
              <SkipToSidebarLink secondary isLink tabIndex={0} href={`#${selectedStoryId}`}>
                Skip to sidebar
              </SkipToSidebarLink>
            );
          }
          return null;
        }}
      </Consumer>
      {Object.entries(frames).map(([id, src]) => {
        const [key] = refs[id] ? refs[id].url.split('?') : [id];
        return (
          <Fragment key={id}>
            <IFrame
              active={id === active}
              key={key}
              id={id}
              title={id}
              src={src}
              allowFullScreen
              scale={scale}
            />
          </Fragment>
        );
      })}
    </Fragment>
  );
```

Where we ensure the frame isn't recreated every time?

**Comment by ndelangen** [comment]
Hmmm testing the above and it still refreshes

**Comment by ndelangen** [comment]
OK, found a fix, I'll submit a PR.

**Comment by shilman** [comment]
Yo-ho-ho!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-rc.8 containing PR #21713 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```
