### ISSUE TITLE
[Bug]: Composition - blank page when path/storyId contains underscore

### ISSUE THREAD

**Issue by ndelangen** [storybookjs/storybook#21504]
### Describe the bug

Reported by @yannbf during QA:

When trying to access a path to a composed story that does not exist (happened to me many times while disabling a composition and rerunning Storybook, which reloaded the page which had a story being visited), the entire Storybook crashes into a white screen.

The browser error logs: 
```
Uncaught TypeError: Cannot read properties of undefined (reading 'index') at Object.resolveStory
```

I figured out that this can be easily reproduced in any Storybook with the following URL param: /?path=/story/foo_bar
Example: https://mealdrop.vercel.app/storybook/?path=/story/foo_bar

I guess this is related to an internal logic that checks if the story id contains an underscore, and then assumes it's a composed story. 
Seems like the error handling is completely borked, which leads us to a white page.

### To Reproduce

- visit https://mealdrop.vercel.app/storybook/?path=/story/foo_bar

**Comment by shilman** [comment]
w00t!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-rc.4 containing PR #21598 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```
