### ISSUE TITLE
[Bug]: Composition - version switcher doesn't close, no visual feedback

### ISSUE THREAD

**Issue by ndelangen** [storybookjs/storybook#21505]
Related: https://github.com/storybookjs/storybook/issues/21534
Related: https://github.com/storybookjs/storybook/issues/5593

### Describe the bug

The version picker works, but is slow. it does not give feedback, it doesn't close

![](https://user-images.githubusercontent.com/3070389/222403936-96528760-00d6-4f07-84ef-7ec5346d824b.png)

### To Reproduce

- Add the design system as a ref to `code/ui/.storybook/main.ts`
- Switch to a different version using the dropdown

**Comment by ndelangen** [comment]
@valentinpalkovic do you think your PR https://github.com/storybookjs/storybook/pull/21589 will fix this issue as well?

**Comment by valentinpalkovic** [comment]
My PR just fixes an issue of not closing the tooltip, if the user clicks into the iframe area

**Comment by shilman** [comment]
Jiminy cricket!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-rc.6 containing PR #21621 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```
