### ISSUE TITLE
[Bug]: Composition - hovering over sidebar items from ref cause error in console

### ISSUE THREAD

**Issue by ndelangen** [storybookjs/storybook#21516]
### Describe the bug

reported by @shilman and @tmeasday and @yannbf during QA:

When hovering over any entry from the composed Storybook, the browser throws an error: Uncaught (in promise) TypeError: ids.map is not a function. Probably related to the prefetching logic in the sidebar

<img width="615" alt="Untitled-01" src="https://user-images.githubusercontent.com/3070389/224041806-b2db9ea6-2d94-40c5-bd98-304378042a64.png">

This is likely some bug in the preloading mechanism, perhaps we should just turn that off for composed storybooks?

**Comment by kabhamo** [comment]
@ndelangen ,
What did you mean by "When hovering over any entry from the composed Storybook"
I am trying to reproduce the bug

**Comment by kabhamo** [comment]
@ndelangen, thank you, it is related to storybookjs/design-system repo.
I will start checking the issue on my local machine.
I will let u know if there is any progress.

**Comment by kabhamo** [comment]
@ndelangen, @yannbf,
I run it and there are no errors at all.
I check it on 
localhost: http://localhost:6006/?path=/story/intro--page
and on 
production: https://master--5ccbc373887ca40020446347.chromatic.com/?path=/story/intro--page
Make sure to check the issue again :)

**Comment by ndelangen** [comment]
@vanessayuenn I think this is fixed by another PR, I'll close it.
