### ISSUE TITLE
[Bug]: Docs: Writing an Addon docs are outdated

### ISSUE THREAD

**Issue by IanVS** [storybookjs/storybook#21514]
### Describe the bug

I was looking at the 7.0 docs for writing addons, and noticed that they're a bit out of date.  For instance,

https://storybook.js.org/docs/7.0/react/addons/writing-presets#webpack mentions that a webpack 4 config object should be used, but in 7.0, it's webpack 5 only.  It also mentions "As of Storybook 6.3, Storybook can run with either webpack4 or webpack5 builder."

And if it's mentioning webpack options, it would be good to mention `viteFinal` as well.

There may be other changes needed as well.

**Comment by jonniebigodes** [comment]
Addressed with #23246 . Closing
