### ISSUE TITLE
[Bug]: The requested module '/@fs/.../node_modules/lodash/<anyFunction>.js' does not provide an export named 'default'

### ISSUE THREAD

**Issue by thtliife** [storybookjs/storybook#21527]
### Describe the bug

`SyntaxError: The requested module '/@fs/Users/vito/repos/personal/demo-storybook/node_modules/lodash/mapValues.js?v=fae03021' does not provide an export named 'default'`

This issue occurs in storybook `7.0.0-rc.0`

### To Reproduce

Clone the `next` branch from storybookjs/storybook and run `yarn start`

Observe results
![sb error](https://user-images.githubusercontent.com/9210782/224207651-2a928a7f-23d6-4449-8355-e2bbf8324210.png)

### System

```shell
Environment Info:

  System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 19.7.0 - ~/.tools/n/bin/node
    Yarn: 3.4.1 - ~/.tools/n/bin/yarn
    npm: 9.5.0 - ~/.tools/n/bin/npm
  Browsers:
    Chrome: 111.0.5563.64
    Firefox: 110.0.1
    Safari: 16.2
```

**Comment by thtliife** [comment]
This issue can be worked around via the use of the vite configs `optimizeDeps` option.
eg:

```typescript
export const viteFinal = async (config: InlineConfig) =>
  mergeConfig(config, {
    optimizeDeps: {
      include: [
        'lodash/camelCase.js',
        'lodash/cloneDeep.js',
        'lodash/countBy.js',
        'lodash/debounce.js',
        'lodash/isEqual.js',
        'lodash/isFunction.js',
        'lodash/isPlainObject.js',
        'lodash/isString.js',
        'lodash/kebabCase.js',
        'lodash/mapKeys.js',
        'lodash/mapValues.js',
        'lodash/merge.js',
        'lodash/mergeWith.js',
        'lodash/pick.js',
        'lodash/pickBy.js',
        'lodash/startCase.js',
        'lodash/throttle.js',
        'lodash/uniq.js',
        'lodash/upperFirst.js'
      ]
    }
  });
```

**Comment by shilman** [comment]
This looks like a problem with node 19. We should fix before GA

**Comment by D1no** [comment]
@shilman No it's a regression from `beta-63` to `rc.0` on node 18 LTS

https://github.com/storybookjs/storybook/issues/21523#issuecomment-1463112834

**Comment by shilman** [comment]
Good catch. Will try to get this fixed today!

**Comment by shilman** [comment]
Shiver me timbers!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-rc.1 containing PR #21532 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```
