### ISSUE TITLE
[Bug]: Doctrine does not provide an export named 'default' in v7.0.0-rc.0

### ISSUE THREAD

**Issue by bryanjtc** [storybookjs/storybook#21523]
### Describe the bug

The requested module '/.yarn/cache/doctrine-npm-3.0.0-c6f1615f04-fd7673ca77.zip/node_modules/doctrine/lib/doctrine.js?v=4047beba' does not provide an export named 'default'

### To Reproduce

Run yarn storybook
https://github.com/bryanjtc/storybook-7-vite-test

### System

```shell
Environment Info:

  System:
    OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (16) x64 AMD EPYC 7B13
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    Yarn: 3.4.1 - ~/.nvm/versions/node/v16.19.0/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
```

### Additional context

The repo uses yarn pnp.

**Comment by bryanjtc** [comment]
Doctrine is used by @storybook/docs-tools. Here https://github.com/storybookjs/storybook/blob/520d0b21ca73e1f0c81833cf56fe7fdf8e6ccfc5/code/lib/docs-tools/src/argTypes/jsdocParser.ts#L2

**Comment by nickgros** [comment]
I'm seeing the same issue with pnpm + react-vite

**Comment by D1no** [comment]
Same here
![image](https://user-images.githubusercontent.com/2397125/224205218-e705fdae-66d6-4384-8c99-5beb14f6b357.png)

Resulted after running
```
cd tools && pnpx storybook@next upgrade --prerelease --skip-check
```
to upgrade from `^7.0.0-beta.63  →  ^7.0.0-rc.0`

In my stroybook-pnpm reproduction repo
https://github.com/D1no/reproduction-storybook-symlinks-pnpm

**Comment by sawden** [comment]
I have the same issue with vite and pnpm.

**Comment by thtliife** [comment]
see if adding doctrine to optimizeDeps.include array in your viteFinal config in main.js/main.ts helps? (example in #21527)

**Comment by shilman** [comment]
(Assuming the workaround from #21527 works, have not tested)

**Comment by D1no** [comment]
Can be closed @shilman. Regression disappeared with `7.0.0-rc.1` ✅

**Comment by shilman** [comment]
Yowza!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-rc.4 containing PR #21535 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```
