### ISSUE TITLE
[Bug]: controls are not generated from arrow function types since 61 beta

### ISSUE THREAD

**Issue by dartess** [storybookjs/storybook#21530]
### Describe the bug

For component like 
```
function Market(props: Props) {
  return null;
}
```
Everything is fine:
<img width="280" alt="image" src="https://user-images.githubusercontent.com/15047511/224241942-606ae5f1-2b43-4d87-a3ad-e2054b0ba6c9.png">

For component like:
```
const Market = (props: Props) => {
  return null;
};
```
I got empty table:

<img width="476" alt="image" src="https://user-images.githubusercontent.com/15047511/224242033-7c4ccd6a-1144-4417-8499-93e07a293a08.png">

I can assume that this is related to this PR: https://github.com/storybookjs/storybook/pull/21380

Also relevant for rc.0

### To Reproduce

https://github.com/dartess/storybook-arrow-fn-bug

### System

```shell
Environment Info:

  System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 18.12.0 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 111.0.5563.64
    Firefox: 109.0.1
    Safari: 16.3
  npmPackages:
    @storybook/addon-actions: ^7.0.0-rc.0 => 7.0.0-rc.0 
    @storybook/addon-docs: ^7.0.0-rc.0 => 7.0.0-rc.0 
    @storybook/addon-essentials: ^7.0.0-rc.0 => 7.0.0-rc.0 
    @storybook/addon-links: ^7.0.0-rc.0 => 7.0.0-rc.0 
    @storybook/react: ^7.0.0-rc.0 => 7.0.0-rc.0 
    @storybook/react-webpack5: ^7.0.0-rc.0 => 7.0.0-rc.0
```

**Comment by shilman** [comment]
Jeepers creepers!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-rc.6 containing PR #21693 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```

**Comment by dartess** [comment]
Open new issue https://github.com/storybookjs/storybook/issues/21939
