### ISSUE TITLE
[Bug]: Development build failed

### ISSUE THREAD

**Issue by leidto** [storybookjs/storybook#21533]
### Describe the bug

I'm getting the following error after command `storybook dev -p 6006`

[storybook] info => Starting manager..
[storybook] X [ERROR] No matching export in "global-externals:@storybook/components" for import "ErrorFormatter"
[storybook]
[storybook]     node_modules/@storybook/blocks/dist/index.mjs:1:11369:
[storybook]       1 │ ...port{Loader,getStoryHref,ErrorFormatter}from"@storybook/componen...
[storybook]         ╵                             ~~~~~~~~~~~~~~
[storybook]
[storybook] info Found existing addon "@storybook/addon-actions", skipping.

### To Reproduce

storybook dev -p 6006

**Comment by kabhamo** [comment]
@leidto, 
what is the node version you work with.?

**Comment by kabhamo** [comment]
@leidto, change it to 16.3.0 and try again after .

**Comment by snettah** [comment]
For me I've keeping node 18 but I've updated all the packages `npx storybook@next upgrade --prerelease`

**Comment by shilman** [comment]
Does anybody a have a reproduction repo you can share? If not, can you create one? See [how to create a repro](https://storybook.js.org/docs/react/contribute/how-to-reproduce). Thank you! 🙏

**Comment by moti-maestro** [comment]
> For me I've keeping node 18 but I've updated all the packages `npx storybook@next upgrade --prerelease`

Thanks!
Worked for me with node v19 after installing `7.0.0-rc.1` packages instead of `7.0.0-beta.62` (or 54/55)

**Comment by StijnLammens** [comment]
I'm having this issue with 7.0.0-rc.3 and node: v16.19.1
