### ISSUE TITLE
[Feature Request]: Close dropdown when clicking/focusing outside

### ISSUE THREAD

**Issue by ghidersamihaela** [storybookjs/storybook#21534]
### Is your feature request related to a problem? Please describe

The dropdown remains open when clicking outside. Only clicking again on its corresponding button will close it. 
<img width="551" alt="Screenshot 2023-03-10 at 13 30 48" src="https://user-images.githubusercontent.com/31012181/224305893-0036e7fb-3167-4e23-a019-a546cdaba414.png">

### Describe the solution you'd like

More user-friendly should be for the dropdown to close when the focus is lost and we move/click on a different area in the preview.

### Are you able to assist to bring the feature to reality?

yes, I can

**Comment by shilman** [comment]
@ghidersamihaela any chance you can submit a PR to fix it? That would be much appreciated!!!

**Comment by Saransh27** [comment]
Hi @shilman @ghidersamihaela I was searching for a good first issue. this feature request is something I can also pick if you allow me😃.

**Comment by valentinpalkovic** [comment]
@MichaelArestad fyi

**Comment by ghidersamihaela** [comment]
> Hi @shilman @ghidersamihaela I was searching for a good first issue. this feature request is something I can also pick if you allow me😃.

Sure @Saransh27, please do.

**Comment by Saransh27** [comment]
Thank you @ghidersamihaela 
Hi @MichaelArestad,
I hope you also agree with this feature request. from a user perspective, it is kind a annoying that the dropdown is not getting closed on clicking outside.

**Comment by MichaelArestad** [comment]
@valentinpalkovic Can you fix this before 7.0 goes out? It feels like a regression when using toolbar menus.

**Comment by valentinpalkovic** [comment]
@ghidersamihaela I cannot reproduce it in SB v7.0.0-rc.3. Is this a bug in 6.5?

**Comment by valentinpalkovic** [comment]
It seems that the root cause is this bug https://github.com/storybookjs/storybook/issues/5593

**Comment by shilman** [comment]
Gadzooks!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-rc.4 containing PR #21589 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```
