### ISSUE TITLE
MDX codemod should always update imports even when no stories are extracted

### ISSUE THREAD

**Issue by kasperpeulen** [storybookjs/storybook#21542]
At this moment the '@storybook/addon-docs' import is only updated to `@storybook/blocks` when the mdx file contains stories to extract. 

We should update the codemod so that the imports are always updated.

**Comment by shilman** [comment]
Yowza!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-rc.2 containing PR #21549 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```
