### ISSUE TITLE
Update stories glob in mdx codemod and not in mdx automigration

### ISSUE THREAD

**Issue by kasperpeulen** [storybookjs/storybook#21543]
We now update the stories glob in an automigration, but only rename the stories as part of a codemod.

We should change the automigration to only point the user to the codemod, but not do anything.

The codemod should be changed to update the stories glob.

**Comment by shilman** [comment]
Son of a gun!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-rc.11 containing PR #21809 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```
