### ISSUE TITLE
[Bug]: Vite resolve aliases stop working when using `@storybook/addon-essentials`

### ISSUE THREAD

**Issue by jthrilly** [storybookjs/storybook#21547]
### Describe the bug

When I enable `@storybook/addon-essentials` any stories that import components using a vite resolve alias (i.e `@/components/Button`) stop working, and the startup log lists messages such as:

```
The following dependencies are imported but could not be resolved:

  @/components/ (imported by /Users/joshua/Projects/fresco/packages/ui/src/components/Toast/ToastManager.stories.jsx)
  @/components/BackgroundBlobs (imported by /Users/joshua/Projects/fresco/packages/ui/src/components/BackgroundBlobs.stories.jsx)
  @/components/ProgressBar (imported by /Users/joshua/Projects/fresco/packages/ui/src/components/ProgressBar.stories.jsx)

Are they installed?
```

Running with `pnpm` inside a turbo monorepo.

### To Reproduce

Use `@storybook/addon-essentials` with storybook rc.1.

### System

```shell
Environment Info:

  System:
    OS: macOS 13.2.1
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
  Binaries:
    Node: 18.12.0 - ~/.nvm/versions/node/v18.12.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.0/bin/npm
  Browsers:
    Chrome: 110.0.5481.177
    Firefox: 110.0.1
    Safari: 16.3
```

**Comment by jthrilly** [comment]
Just to add that this is still an issue in `7.0.0-rc-2`.

**Comment by shilman** [comment]
@jthrilly do you happen to have a reproduction you can share? if not, can you make one at https://storybook.new ?

**Comment by IanVS** [comment]
@jthrilly how are you defining your aliases?  Is it possible that you're hitting this problem?  https://github.com/storybookjs/storybook/pull/21480#issuecomment-1466354772

**Comment by jthrilly** [comment]
I'll work on a reproduction for you. 

> @jthrilly how are you defining your aliases? Is it possible that you're hitting this problem? #21480

I saw this issue, and did wonder if that could be the cause. I didn't find any vite documentation for defining aliases as anything other than an array, so I put it to one side. I will look more closely and see if this is the root cause.

**Comment by jthrilly** [comment]
I can confirm that this seems to be a dupe of #21480

Alias config works when specified as an object:

```
  resolve: {
    alias: {
      '@': path.resolve(path.dirname(fileURLToPath(import.meta.url)), 'src'),
    },
  },
```

**Comment by shilman** [comment]
Whoopee!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-rc.4 containing PR #21480 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```
