### ISSUE TITLE
[Bug]: Your application tried to access @storybook/builder-vite, but it isn't declared in your dependencies v7.0.0-beta.59

### ISSUE THREAD

**Issue by bryanjtc** [storybookjs/storybook#21548]
### Describe the bug

After running the new frameworks migration in my project, it removed @storybook/builder-vite package, but it's needed by core-server.
![image](https://user-images.githubusercontent.com/49354825/224359729-1b7775b5-eac9-4241-bd36-a2f96e656cdf.png)

### To Reproduce

https://github.com/bryanjtc/storybook-7-vite-test/commit/e9fead04c4ec9bd7cc358a5b63a17210df6230bf

### System

```shell
Environment Info:

  System:
    OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (16) x64 AMD EPYC 7B13
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    Yarn: 3.4.1 - ~/.nvm/versions/node/v16.19.0/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
```

### Additional context

Fixed with https://github.com/storybookjs/storybook/pull/21486
Reverted fix with https://github.com/storybookjs/storybook/pull/21532
Can be fixed with #21535
Discord discussion: https://discord.com/channels/486522875931656193/1081643102349049937

**Comment by shilman** [comment]
¡Ay Caramba!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-rc.4 containing PR #21535 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
