### ISSUE TITLE
[Bug]: `@storybook/nextjs` is incompatible with Google fonts in Next.js 13.2.4

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#21552]
### Describe the bug

Next.js made a release today which made [big refactoring changes to the next/font structure](https://github.com/vercel/next.js/commit/533748d3834cfaf6f7807d6e5f0bf96d99c247c1) and that affected how `@storybook/nextjs` works internally, as it uses an internal path from next/font to access its utilities, which, in newer versions, does not exist anymore.

[This is the line of code](https://github.com/storybookjs/storybook/blob/next/code/frameworks/nextjs/src/font/webpack/loader/utils/google-font-utils.ts#L47) in Storybook that breaks, as the path is now different.

The regression was caught in CI [here](https://app.circleci.com/pipelines/github/storybookjs/storybook/44042/workflows/08e19a7a-fb6a-4d52-a0ac-6032b0b64e6d/jobs/497300/parallel-runs/12).

### Additional context

@hanneslund do you think there's a better way to collaborate and provide good support for next/font, with a solution that's not so brittle like it currently is? We currently had to make changes to support both `@next/font` and `next/font`, and we'll have to add another code path to support Next 13.2.4, plus additional ones if there are more internal changes in the future.

It would be incredible if we could collaborate and get into a more stable state, to better support Next.js users! ❤️

**Comment by shilman** [comment]
Yo-ho-ho!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-rc.2 containing PR #21560 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```
