### ISSUE TITLE
[Feature Request]: First-class support for Rspack

### ISSUE THREAD

**Issue by kaelig** [storybookjs/storybook#21561]
### Is your feature request related to a problem? Please describe

In various codebases I've worked on, Storybook + Webpack (even with ESBuild) has a slow start and more importantly, slow refresh times. I've tried to migrate to the Vite builder but ran into issues because our setup is heavily tied to several Webpack constructs.

### Describe the solution you'd like

Rspack just came out (https://www.rspack.dev/), and it offers a great migration path for Webpack-powered codebases so they can improve local start and reload speed, as well as build speed.

I'd love to see first-class support for Rspack in Storybook!

(I heard there already are discussions happening between the Storybook team and the Rspack team – I'm opening this issue hoping to bring visibility)

### Are you able to assist to bring the feature to reality?

no

**Comment by shilman** [comment]
We're investigating with the Rspack team what it would take to create a `builder-rspack` for Storybook. Fingers crossed! 🤞

**Comment by shilman** [comment]
For anybody who's interested, there's an experimental builder documented here https://www.rspack.dev/guide/migrate-storybook.html

**Comment by probablyup** [comment]
Thanks @shilman, also worth adding a note to that guide that storyStore v6 is not supported for this

**Comment by valentinpalkovic** [comment]
Here we go: https://github.com/rspack-contrib/storybook-rsbuild

**Comment by fi3ework** [comment]
[storybook-rsbuild](https://github.com/rspack-contrib/storybook-rsbuild) is still in early stage. Give it a try and feel free to feed back if you need any help or encounter any issue. 🤗

**Comment by matheusmichels** [comment]
@fi3ework does `storybook-rsbuild` have support for `--webpack-stats-json`?
I currently use Webpack in my Storybook setup, and was wondering if I can run `storybook build --webpack-stats-json` with RSBuild and have the same stats file output.

**Comment by Narretz** [comment]
It would still be cool to have **rspack** framwork / builder support for storybook, because rsbuild is a whole build tool. For example, if you're replacing webpack with rspack in your app, you don't need the whole rsbuild. But storybook with rspack needs the whole [storybook-rsbuild](https://github.com/rspack-contrib/storybook-rsbuild) which means extra dependencies you don't need and duplicated configuration.

**Comment by Niels-NTG** [comment]
Rspack, a variant of Rsbuild that's a drop-in replacement for Webpack ("drop-in replacement" with some caveats, but it's quite easy migrate to it from Webpack), still isn't properly supported by [storybook-rsbuild](https://github.com/rspack-contrib/storybook-rsbuild). Some of the current issues are outlined in [this issue](https://github.com/rspack-contrib/storybook-rsbuild/issues/92). I haven't heard of any progress regarding this issue. Maybe someone from the Storybook team could be of some assistance?

Lacking support for Storybook is the one thing holding us back from migrating from Webpack to Rspack right now.
