### ISSUE TITLE
[Bug]: jest-dom types do not exist in storybook/jest even though its included

### ISSUE THREAD

**Issue by lifeiscontent** [storybookjs/storybook#21581]
### Describe the bug

The types for jest-dom are not included in storybook/jest even though the matchers are indeed included.

### To Reproduce

```tsx
import { expect } from '@storybook/jest';
...
  await expect(
    screen.getByRole('button', { name: /Close Dialog/i })
    // @ts-expect-error toHaveFocus comes from @testing-library/jest-dom but storybook doesn't include the types currently.
  ).toHaveFocus();
```

**Comment by yannbf** [comment]
Hey there! There isn't much we can do for now, this issue is related to specific setups in package managers. I added a detailed explanation about that here: https://github.com/storybookjs/jest#typescript-does-not-recognize-expecttobeinthedocument

**Comment by Nateowami** [comment]
@yannbf I'm using npm and seeing this build error.

- The types are being hoisted as expected, evidenced by `ls node_modules/@types/testing-library__jest-dom`.
- Directly installing `@types/testing-library__jest-dom@5.14.5` does not solve the problem.
- The marchers actually exist at runtime; `(expect(element) as any).toBeInTheDocument()` builds and passes.

I assume this has something to do with properly configuring types in `tsconfig.json`, but it's not clear to me which tsconfig is being used, and setting `typeRoots` to `node_modules/@types` in any of the tsconfig files I think it might be using has not resolved the issue.

**Comment by jbowtie** [comment]
For Storybook 7.0, I was able to fix this in my project with the following steps:

1. Create `.storybook/jest-setup.ts` with the the content `import '@testing-library/jest-dom'`
2. In `.storybook/tsconfig.json` add `./jest-setup.ts` to the `include` array.

After that it worked as expected.

**Comment by Nateowami** [comment]
@jbowtie Thank you. I can confirm this is working for Storybook 6.5.16 as well.

**Comment by yannbf** [comment]
Thanks everyone! I'd recommend anyone else having issues like this to read the following link for directions:
https://github.com/storybookjs/jest#typescript-does-not-recognize-expecttobeinthedocument

I'll be closing this issue for now!
