### ISSUE TITLE
[Bug]: Unable to use TypeScript 4.9 `satisfies` operator inside vue component

### ISSUE THREAD

**Issue by larsrickert** [storybookjs/storybook#21606]
### Describe the bug

When using the TypeScript `satisfies` operator inside a `.vue` file, you are not able to use storybook because the error shown in the screenshot is shown.

<img width="902" alt="image" src="https://user-images.githubusercontent.com/67898185/225085316-7e96875d-e424-468f-b708-3ce626712901.png">

### To Reproduce

- Repository: https://github.com/larsrickert/storybook-typescript-satisfies
- Stackblitz: https://stackblitz.com/github/larsrickert/storybook-typescript-satisfies?preset=node

### System

```shell
Environment Info:

  System:
    OS: macOS 13.0.1
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.5.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 110.0.5481.177
    Safari: 16.1
  npmPackages:
    @storybook/addon-essentials: ^7.0.0-rc.3 => 7.0.0-rc.3 
    @storybook/addon-interactions: ^7.0.0-rc.3 => 7.0.0-rc.3 
    @storybook/addon-links: ^7.0.0-rc.3 => 7.0.0-rc.3 
    @storybook/blocks: ^7.0.0-rc.3 => 7.0.0-rc.3 
    @storybook/testing-library: ^0.0.14-next.1 => 0.0.14-next.1 
    @storybook/vue3: ^7.0.0-rc.3 => 7.0.0-rc.3 
    @storybook/vue3-vite: ^7.0.0-rc.3 => 7.0.0-rc.3
```

**Comment by shilman** [comment]
We probably need to upgrade `vue-docgen-api` to the latest version

**Comment by kasperpeulen** [comment]
cc @chakAs3

**Comment by chakAs3** [comment]
@kasperpeulen @shilman i'm working on replacing it by vue-component-meta volar

**Comment by chakAs3** [comment]
i have already done it  will push a PR

**Comment by larsrickert** [comment]
Hey, are there any updates on this? :)

**Comment by kasperpeulen** [comment]
cc @chakAs3

**Comment by chakAs3** [comment]
hi @kasperpeulen it will be ready for review today. I'm on it.
