### ISSUE TITLE
[Bug]: vite overwrites generated `index.html`

### ISSUE THREAD

**Issue by LucidityDesign** [storybookjs/storybook#21618]
### Describe the bug

When building storybook@7.0.0-rc.3 via `storybook build` the generated `storybook-static/index.html` will be overwritten if there exists `public/index.html` and the builder is `@storybook/react-vite`

### To Reproduce

- `yarn create react-app my-app --template typescript`
- `cd my-app`
- `yarn add typescript @types/node @types/react @types/react-dom @types/jest`
- `npx storybook@next init`
- Change builder to `vite`: https://storybook.js.org/docs/7.0/react/builders/vite
- `yarn build-storybook`

### System

```shell
Environment Info:

  System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.13.0/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v18.13.0/bin/npm
  Browsers:
    Chrome: 111.0.5563.64
    Firefox: 109.0
    Safari: 16.3
  npmPackages:
    @storybook/addon-essentials: ^7.0.0-rc.3 => 7.0.0-rc.3 
    @storybook/addon-interactions: ^7.0.0-rc.3 => 7.0.0-rc.3 
    @storybook/addon-links: ^7.0.0-rc.3 => 7.0.0-rc.3 
    @storybook/blocks: ^7.0.0-rc.3 => 7.0.0-rc.3 
    @storybook/builder-vite: ^7.0.0-rc.3 => 7.0.0-rc.3 
    @storybook/preset-create-react-app: ^7.0.0-rc.3 => 7.0.0-rc.3 
    @storybook/react: ^7.0.0-rc.3 => 7.0.0-rc.3 
    @storybook/react-vite: ^7.0.0-alpha.25 => 7.0.0-alpha.25 
    @storybook/react-webpack5: ^7.0.0-rc.3 => 7.0.0-rc.3 
    @storybook/testing-library: ^0.0.14-next.1 => 0.0.14-next.1
```

### Additional context

If you open `storybook-static/index.html` while the build process is running, you will see the correct html file briefly before it gets overwritten by `public/index.html`

**Comment by IanVS** [comment]
Yep, you shouldn't have an `index.html` in your public folder.  See https://vitejs.dev/guide/#index-html-and-project-root

**Comment by IanVS** [comment]
Actually, I just ran the reproduction steps, and it built just fine.  The only difference was that I combined two of your steps into `npx storybook@next init --builder=vite`.

**Comment by IanVS** [comment]
I see you still have `@storybook/preset-create-react-app` and `@storybook/react-webpack5`, that could be causing you problems.

**Comment by LucidityDesign** [comment]
Thanks for investigating!
