### ISSUE TITLE
[Bug]: `7.0.0-rc.-3` breaks vite + pnpm support - Error: Cannot find module `@storybook/builder-vite`

### ISSUE THREAD

**Issue by D1no** [storybookjs/storybook#21612]
### Describe the bug

Regression when updating from `7.0.0-rc.1` to `7.0.0-rc.3` leading to

Error: Cannot find module '@storybook/builder-vite'

### To Reproduce

<sub>(I use `pnpm`)</sub>

Clone [Reproduction](https://github.com/D1no/reproduction-storybook-symlinks-pnpm) and Checkout [839aabc](https://github.com/D1no/reproduction-storybook-symlinks-pnpm/commit/839aabc24a56a3124f2d5da8dd1c506644087462)
```bash
git clone git@github.com:D1no/reproduction-storybook-symlinks-pnpm.git && cd reproduction-storybook-symlinks-pnpm && git checkout 839aabc
```

Update Storybook with
```bash
cd tools && pnpx storybook@next upgrade --prerelease --skip-check
```

Result:
```bash
➜  tools git:(master) ✗ pnpm run storybook                                   

> tools@ storybook /Users/worker/development/_REPRODUCTIONS/reproduction-storybook-symlinks-pnpm/tools
> storybook dev -p 6006

@storybook/cli v7.0.0-rc.3

ERR! Error: Cannot find module '@storybook/builder-vite'
ERR! Require stack:
ERR! - /Users/worker/development/_REPRODUCTIONS/reproduction-storybook-symlinks-pnpm/tools/node_modules/.pnpm/@storybook+core-server@7.0.0-rc.3/node_modules/@storybook/core-server/dist/index.js
ERR! - /Users/worker/development/_REPRODUCTIONS/reproduction-storybook-symlinks-pnpm/tools/node_modules/.pnpm/@storybook+cli@7.0.0-rc.3/node_modules/@storybook/cli/dist/generate.js
ERR! - /Users/worker/development/_REPRODUCTIONS/reproduction-storybook-symlinks-pnpm/tools/node_modules/.pnpm/@storybook+cli@7.0.0-rc.3/node_modules/@storybook/cli/bin/index.js
ERR! - /Users/worker/development/_REPRODUCTIONS/reproduction-storybook-symlinks-pnpm/tools/node_modules/.pnpm/storybook@7.0.0-rc.3/node_modules/storybook/index.js
ERR!     at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
ERR!     at Function.resolve (node:internal/modules/cjs/helpers:116:19)
ERR!     at getPreviewBuilder (/Users/worker/development/_REPRODUCTIONS/reproduction-storybook-symlinks-pnpm/tools/node_modules/.pnpm/@storybook+core-server@7.0.0-rc.3/node_modules/@storybook/core-server/dist/index.js:10:1789)
ERR!     at buildDevStandalone (/Users/worker/development/_REPRODUCTIONS/reproduction-storybook-symlinks-pnpm/tools/node_modules/.pnpm/@storybook+core-server@7.0.0-rc.3/node_modules/@storybook/core-server/dist/index.js:40:2022)
ERR!     at async withTelemetry (/Users/worker/development/_REPRODUCTIONS/reproduction-storybook-symlinks-pnpm/tools/node_modules/.pnpm/@storybook+core-server@7.0.0-rc.3/node_modules/@storybook/core-server/dist/index.js:27:3469)
ERR!     at async dev (/Users/worker/development/_REPRODUCTIONS/reproduction-storybook-symlinks-pnpm/tools/node_modules/.pnpm/@storybook+cli@7.0.0-rc.3/node_modules/@storybook/cli/dist/generate.js:446:400)
ERR!     at async Command.<anonymous> (/Users/worker/development/_REPRODUCTIONS/reproduction-storybook-symlinks-pnpm/tools/node_modules/.pnpm/@storybook+cli@7.0.0-rc.3/node_modules/@storybook/cli/dist/generate.js:448:327)
ERR!  Error: Cannot find module '@storybook/builder-vite'
ERR! Require stack:
ERR! - /Users/worker/development/_REPRODUCTIONS/reproduction-storybook-symlinks-pnpm/tools/node_modules/.pnpm/@storybook+core-server@7.0.0-rc.3/node_modules/@storybook/core-server/dist/index.js
ERR! - /Users/worker/development/_REPRODUCTIONS/reproduction-storybook-symlinks-pnpm/tools/node_modules/.pnpm/@storybook+cli@7.0.0-rc.3/node_modules/@storybook/cli/dist/generate.js
ERR! - /Users/worker/development/_REPRODUCTIONS/reproduction-storybook-symlinks-pnpm/tools/node_modules/.pnpm/@storybook+cli@7.0.0-rc.3/node_modules/@storybook/cli/bin/index.js
ERR! - /Users/worker/development/_REPRODUCTIONS/reproduction-storybook-symlinks-pnpm/tools/node_modules/.pnpm/storybook@7.0.0-rc.3/node_modules/storybook/index.js
ERR!     at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
ERR!     at Function.resolve (node:internal/modules/cjs/helpers:116:19)
ERR!     at getPreviewBuilder (/Users/worker/development/_REPRODUCTIONS/reproduction-storybook-symlinks-pnpm/tools/node_modules/.pnpm/@storybook+core-server@7.0.0-rc.3/node_modules/@storybook/core-server/dist/index.js:10:1789)
ERR!     at buildDevStandalone (/Users/worker/development/_REPRODUCTIONS/reproduction-storybook-symlinks-pnpm/tools/node_modules/.pnpm/@storybook+core-server@7.0.0-rc.3/node_modules/@storybook/core-server/dist/index.js:40:2022)
ERR!     at async withTelemetry (/Users/worker/development/_REPRODUCTIONS/reproduction-storybook-symlinks-pnpm/tools/node_modules/.pnpm/@storybook+core-server@7.0.0-rc.3/node_modules/@storybook/core-server/dist/index.js:27:3469)
ERR!     at async dev (/Users/worker/development/_REPRODUCTIONS/reproduction-storybook-symlinks-pnpm/tools/node_modules/.pnpm/@storybook+cli@7.0.0-rc.3/node_modules/@storybook/cli/dist/generate.js:446:400)
ERR!     at async Command.<anonymous> (/Users/worker/development/_REPRODUCTIONS/reproduction-storybook-symlinks-pnpm/tools/node_modules/.pnpm/@storybook+cli@7.0.0-rc.3/node_modules/@storybook/cli/dist/generate.js:448:327) {
ERR!   code: 'MODULE_NOT_FOUND',
ERR!   requireStack: [
ERR!     '/Users/worker/development/_REPRODUCTIONS/reproduction-storybook-symlinks-pnpm/tools/node_modules/.pnpm/@storybook+core-server@7.0.0-rc.3/node_modules/@storybook/core-server/dist/index.js',
ERR!     '/Users/worker/development/_REPRODUCTIONS/reproduction-storybook-symlinks-pnpm/tools/node_modules/.pnpm/@storybook+cli@7.0.0-rc.3/node_modules/@storybook/cli/dist/generate.js',
ERR!     '/Users/worker/development/_REPRODUCTIONS/reproduction-storybook-symlinks-pnpm/tools/node_modules/.pnpm/@storybook+cli@7.0.0-rc.3/node_modules/@storybook/cli/bin/index.js',
ERR!     '/Users/worker/development/_REPRODUCTIONS/reproduction-storybook-symlinks-pnpm/tools/node_modules/.pnpm/storybook@7.0.0-rc.3/node_modules/storybook/index.js'
ERR!   ]
ERR! }

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

✔ Would you like to help improve Storybook by sending anonymous crash reports? … yes
 ELIFECYCLE  Command failed with exit code 1.
```

### System

```shell
Environment Info:

  System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 18.14.1 - ~/.nvs/default/bin/node
    npm: 9.3.1 - ~/.nvs/default/bin/npm
  Browsers:
    Chrome: 111.0.5563.64
    Firefox: 97.0.1
    Safari: 16.3
  npmPackages:
    @storybook/addon-essentials: ^7.0.0-rc.1 => 7.0.0-rc.1 
    @storybook/addon-interactions: ^7.0.0-rc.1 => 7.0.0-rc.1 
    @storybook/addon-links: ^7.0.0-rc.1 => 7.0.0-rc.1 
    @storybook/blocks: ^7.0.0-rc.1 => 7.0.0-rc.1 
    @storybook/react: ^7.0.0-rc.1 => 7.0.0-rc.1 
    @storybook/react-vite: ^7.0.0-rc.1 => 7.0.0-rc.1 
    @storybook/testing-library: ^0.0.14-next.1 => 0.0.14-next.1
```

### Additional context

_Originally posted by @D1no in https://github.com/storybookjs/storybook/issues/21399#issuecomment-1469048323_

**Comment by hyrious** [comment]
I met this issue too yesterday and digged a little. This is because [the `@storybook/core-server` will try to load `@storybook/builder-vite` from the `.storybook` folder](https://github.com/storybookjs/storybook/blob/f47000eecda21e1a7e51b367d7d05adf147a279b/code/lib/core-server/src/utils/get-builders.ts#L14-L17) and [`@storybook/react-vite` put builder-vite in its dependencies](https://github.com/storybookjs/storybook/blob/cf38eaf29cacf324a3190fcaac435ff4759340eb/code/frameworks/react-vite/package.json#L53). As you may know [`pnpm` enforces correct dependency tree](https://www.kochan.io/nodejs/pnpms-strictness-helps-to-avoid-silly-bugs.html), here comes the issue: pnpm made this folder structure:

```
.storybook/
node_modules/
	@storybook/core-server/
	@storybook/react-vite/
		node_modules/
			@storybook/builder-vite/
```

Starting from `.storybook`, it can not <q>see</q> `builder-vite` since it is not a direct dependency of the root folder. Thus `require.resolve('@storybook/builder-vite')` fails here.

One possible solution is react-vite put builder-vite in its peer dependencies, which means the user must install builder-vite as a direct dependency.

- - -

Workarounds:

- You can manully install `@storybook/builder-vite@^7.0.0-rc.3` as your dev dependencies.
- Or, add a [hoist pattern](https://pnpm.io/npmrc#hoist-pattern) like `hoist-pattern[]=*storybook*`.

**Comment by D1no** [comment]
Thanks @hyrious — hopefully that helps the storybook team to fix this regression. Can't tell what PR broke this from rc.1 to rc.3.

**Comment by IanVS** [comment]
I tested storybook in a new pnpm project with the following steps:

- `pnpm -v`-> `7.29.3`
- `pnpm create vite@latest`
- Chose a name, react, typescript
- cd into project, `pnpm install`
- `pnpx sb@next init` -> no warnings
- `pnpm run storybook` -> loads storybook without any issues.

@D1no it looks like when you added `@storybook/builder-vite`, you installed the old version for storybook 6.5.  

I also followed your reproduction steps, and was able to successfully upgrade to rc.3 and start storybook without any issues.  Perhaps you have a problem in your pnpm global cache?  https://github.com/pnpm/pnpm/discussions/4413#discussioncomment-2304751

**Comment by D1no** [comment]
Hey, thanks for the quick reply @IanVS . Mh, I ran clean build 🧐. Was also surprised, that despite lock files and all an old project on `v7.0.0-beta.62` just now suddenly stopped working. If it works now, great — but the reports here kinda point to unversioned dependency shifts you guys should look into.

> I had this issue today as well with rc-1 on Vercel build but not locally. **A bit strange but it was ok yesterday.**
↳ This is kinda evidences the assumption

**Comment by IanVS** [comment]
I don't understand what you mean by non-dertministic.  If you are using lock files, which every major package manager supports, then nothing is non-deterministic.  Maybe pnpm has a bug or something, which is not treating lockfiles correctly?

**Comment by D1no** [comment]
Unlikely that a version 7 package manager, existing for many years, vetted by thousands of engineers has an issue with simple lock files.

Much more likely is that your build chain is pushing changes that aren't versioned or not correctly peer referenced. I don't know your set-up but when people report stuff like this, i.e. "works on my machine but not on vercel" it points to build chain issues and not to the user.

**Comment by IanVS** [comment]
@zkochan have you ever heard of something like this?  A few users here are saying that in the last few days, they got what appears to be changes to dependencies when installing a project with a `pnpm-lock.yaml`.  Do you know of anything that could have caused this?

**Comment by IanVS** [comment]
@ozguruysal it would be good to confirm what version of pnpm is used by vercel, and whether that has maybe changed in the last few days if it's not locked.

**Comment by IanVS** [comment]
Ah that does seem suspiciously similar, thanks @zkochan!

I'm going to close out the issue, because it doesn't seem to be related to storybook, but let me know if anyone finds anything that does seem to point our direction.

**Comment by IanVS** [comment]
> as its not (yet) the case.

Sorry, but what part is not the case?  I was able to add storybook to a pnpm project just this morning without any issues, as I showed above.
