### ISSUE TITLE
[Bug]: react-vite doesn't allow to disable "Fast Refresh"

### ISSUE THREAD

**Issue by oriSomething** [storybookjs/storybook#21631]
### Describe the bug

React Vite ignores `fastRefresh` settings, and doesn't allow to turn it off.

As you can see, not settings of `fastRefresh` is passing, so it's automatically `true` in development (even if I'd like to turn it off):
https://github.com/storybookjs/storybook/blob/next/code/frameworks/react-vite/src/preset.ts#L20

Vite allow to turn it off:
https://github.com/vitejs/vite-plugin-react/blob/main/packages/plugin-react/src/index.ts#L22

### To Reproduce

Create config in `main.js` either with:
- `framework: { … options: { fastRefresh: false } }`
- or `reactOptios: { fastRefresh: false }`

Run Storybook, And inspect change that fast refresh cannot support with:
```js
if (import.meta.hot) {
  import.meta.hot.on("vite:beforeUpdate", (...args) =>
    console.log("%c%s", "font-size: 12px; color: orange;", "vite:beforeUpdate", args),
  );
  import.meta.hot.on("vite:afterUpdate", (...args) =>
    console.log("%c%s", "font-size: 12px; color: orange;", "vite:afterUpdate", args),
  );
  import.meta.hot.on("vite:beforeFullReload", (...args) =>
    console.log("%c%s", "font-size: 12px; color: orange;", "vite:beforeFullReload", args),
  );
  import.meta.hot.on("vite:beforePrune", (...args) =>
    console.log("%c%s", "font-size: 12px; color: orange;", "vite:beforePrune", args),
  );
  import.meta.hot.on("vite:invalidate", (...args) =>
    console.log("%c%s", "font-size: 12px; color: orange;", "vite:invalidate", args),
  );
  import.meta.hot.on("vite:error", (...args) =>
    console.log("%c%s", "font-size: 12px; color: orange;", "vite:error", args),
  );
}
```

### System

```shell
The command has issue with yarn 3, so the installed packages:

    "@storybook/addon-a11y": "^7.0.0-rc.1",
    "@storybook/addon-actions": "^7.0.0-rc.1",
    "@storybook/addon-essentials": "^7.0.0-rc.1",
    "@storybook/addon-links": "^7.0.0-rc.1",
    "@storybook/api": "^7.0.0-rc.1",
    "@storybook/builder-vite": "^7.0.0-rc.1",
    "@storybook/cli": "^7.0.0-rc.1",
    "@storybook/components": "^7.0.0-rc.1",
    "@storybook/core": "^6.5.16",
    "@storybook/react": "^7.0.0-rc.1",
    "@storybook/react-vite": "^7.0.0-rc.1",
    "storybook": "^7.0.0-rc.1",
```
```


### Additional context

_No response_

**Comment by oriSomething** [comment]
I have some issues, because of some of the projects that uses `vite.config.js`, that I needed not to put `react()` over there. I know how to work around. I hope I had more convenient way. But I understand considerations for now adding more code to a project. I'll close the PR I've opened. Thanks 🙏

**Comment by IanVS** [comment]
If you can't change the `vite.config.js` for the main project, you can create a config specifically for storybook, and set the `framework.options.builder.viteConfigPath` option (string path relative to cwd).

Alternatively, you can use a `filter` in your `viteFinal` to remove the `plugin-react` plugins and re-add it with the config you need.
