### ISSUE TITLE
[Bug]: Storybook unable to locate stories when special characters are used in path to working directory in v.7.0.0-rc3.

### ISSUE THREAD

**Issue by unitario** [storybookjs/storybook#21636]
### Describe the bug

If the path to Storybook contains [special characters](https://www.npmjs.com/package/glob) the glob lookup fails with a warning saying that no story could be found using pattern.

The problem is the concatenation of of the `fullGlob` which include the working directory: 

https://github.com/storybookjs/storybook/blob/2d280e66291a6e750e79d8908290a32410c7a106/code/lib/core-server/src/utils/StoryIndexGenerator.ts#L121-L123

That means if there are special characters in that path like parenthesis those will be processed as a glob pattern:

https://github.com/storybookjs/storybook/blob/2d280e66291a6e750e79d8908290a32410c7a106/code/lib/core-server/src/utils/StoryIndexGenerator.ts#L124

Possible solution could be by changing this:

```typescript

  const fullGlob = slash(
    path.join(this.options.workingDir, specifier.directory, specifier.files)
  );
  const files = await glob(fullGlob);
```

To this:

```typescript
  const fullGlob = slash(
    path.join(specifier.directory, specifier.files)
  );
  const files = await glob(fullGlob, { cwd: this.options.workingDir });
```

I have monkey patched it and works fine.

### To Reproduce

Put Storybook in a working directory that contains [special characters](https://www.npmjs.com/package/glob) like `/Users/User/Special (1)/` and serve Storybook.

### System

```shell
Environment Info:

  System:
    OS: macOS 13.2.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
  Binaries:
    Node: 16.14.0 - /usr/local/bin/node
    Yarn: 3.2.2 - /usr/local/bin/yarn
    npm: 8.12.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 111.0.5563.64
    Safari: 16.3
```

**Comment by shilman** [comment]
@unitario thanks for filing & coming up with a potential fix. any chance you can submit a PR? we can give it a thorough test before merging. 🙏

**Comment by unitario** [comment]
@shilman I could but it might take while (one or two weeks due to traveling). I suggest you label this "good first issues" and if no takers then I'll look into it at when available?

**Comment by shilman** [comment]
Ok we'll probably take this one then to get it out as part of 7.0. Thanks for letting me know!

**Comment by caiotracera** [comment]
Hey, @shilman @unitario!
I was wondering if it would be possible for me to work on this issue?

**Comment by shilman** [comment]
@caiotracera that would be wonderful!  🙏  Please check out [how to contribute](https://storybook.js.org/docs/react/contribute/how-to-contribute) in our docs and feel free to ask questions in `#contributing` in [our Discord](https://discord.gg/storybook).

**Comment by jankoritak** [comment]
I can grab this. Feel free to assign me. 😊
