### ISSUE TITLE
[Bug]: Discord channel link not working

### ISSUE THREAD

**Issue by jainavi** [storybookjs/storybook#21655]
### Describe the bug

The link for the discord channel on the GitHub repo and the official website of the Storybook is no longer valid.

Error Screen Shot
![Screenshot 2023-03-03 112759](https://user-images.githubusercontent.com/62948292/225982911-5bf9800d-8740-4b15-b7ac-28f00110f21e.png)

### To Reproduce

Click on any links provided in the GitHub repo or the official website of Storybook.

### System

```shell
Windows 11 Version 22H2 
```

### Additional context
The link works fine on my Linux machine (Ubuntu 22.04.2).

_No response_

**Comment by shilman** [comment]
Unable to reproduce this. Perhaps there is a problem with your account? Please contact Discord. Will reopen if I hear reports from other users.
