### ISSUE TITLE
[Bug]: IconButton should be in active state when corresponding menu is open

### ISSUE THREAD

**Issue by pratikkarad** [storybookjs/storybook#21665]
### Describe the bug

Right now, the button reverts to a resting state when the corresponding menu is open making it hard to distinguish what the menu correlates to.

![image](https://user-images.githubusercontent.com/32093370/226098181-3dacbd91-4454-4c63-b387-0e9cd2893768.png)

### Additional context

Recently, a similar issue #21463 got closed but this one got skipped in that.

**Comment by pratikkarad** [comment]
Let me take this home. Please assign it to me.

**Comment by pratikkarad** [comment]
Hi @shilman, I have already created PR. PTAL, Thanks! 😄

**Comment by shilman** [comment]
Whoopee!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-rc.6 containing PR #21666 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```
