### ISSUE TITLE
[Bug]: Error: No configuration files found with Next.js and Storybook

### ISSUE THREAD

**Issue by heildionis** [storybookjs/storybook#21668]
### Describe the bug

When trying to run Storybook with Next.js, the error message "No configuration files have been found in your configDir (C:\Users\densa\OneDrive\Рабочий стол\Файлы\Programmes\Projects\Web\Typescript\baking-bread\client.storybook)" is displayed and I can't run Storybook. I am using the latest version of both Storybook and Next.js.

I'm installed react, react-dom, next and then installed storybook with command:
npx storybook@next init

![image](https://user-images.githubusercontent.com/105888081/226112560-4a1207ba-9a49-4737-9d82-12a9d9dc9753.png)
![image](https://user-images.githubusercontent.com/105888081/226112587-4b9ddc00-6112-4e83-b1ee-13455a5dc742.png)

### To Reproduce

I tried a reproduction with option nextjs/default-ts  and i still have the same issue

![image](https://user-images.githubusercontent.com/105888081/226112944-5109ea93-7137-421e-9cb2-70719993b5a3.png)
![image](https://user-images.githubusercontent.com/105888081/226112968-cff1b712-cf19-4fc2-9a12-75c2acba31aa.png)

### System

```shell
Environment Info:

  System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 AMD Ryzen 5 5600H with Radeon Graphics
  Binaries:
    Node: 19.7.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (111.0.1661.41)
  npmPackages:
    @storybook/addon-essentials: 7.0.0-rc.4 => 7.0.0-rc.4
    @storybook/addon-interactions: 7.0.0-rc.4 => 7.0.0-rc.4
    @storybook/addon-links: 7.0.0-rc.4 => 7.0.0-rc.4
    @storybook/blocks: 7.0.0-rc.4 => 7.0.0-rc.4
    @storybook/nextjs: 7.0.0-rc.4 => 7.0.0-rc.4
    @storybook/react: 7.0.0-rc.4 => 7.0.0-rc.4
    @storybook/testing-library: 0.0.14-next.1 => 0.0.14-next.1
```

**Comment by shilman** [comment]
Yee-haw!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-rc.9 containing PR #21786 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```
