### ISSUE TITLE
[Bug]: .storybook/* doesn't resolve aliases

### ISSUE THREAD

**Issue by agriffis** [storybookjs/storybook#21669]
### Describe the bug

Importing from an alias doesn't work in files like `.storybook/main.ts` or `.storybook/manager.ts`, for example:

```js
import {blah} from 'utils'
```

where you might have in `vite.config.ts`

```
resolve: {alias: {utils: path.resolve(__dirname, 'src/utils')}}
```

results in

```
info => Starting manager..
✘ [ERROR] Could not resolve "utils"

    .storybook/manager.ts:1:16:
      1 │ import {blah} from 'utils'
        ╵                 ~~~~~~~~~~~~~~~~
```

One of the places this becomes a big problem is local addons which might want to reuse significant code from the application.

### To Reproduce

https://github.com/agriffis/automatic-spoon

```
pnpm storybook
```

This example uses `components/Foo` which is relative to the top-level `src`

It works with pnpm tsc because of baseUrl in tsconfig.json

It works with vite build because of resolve.alias in vite.config.ts

It works with Foo.stories.tsx also because of vite.config.ts

but it doesn't work in storybook manager files because those configurations don't apply, instead we're deep in `serverRequire` and `esbuild-register` with a static raw tsconfig

### System

```shell
System:
    OS: Linux 6.1 Fedora Linux 36 (Server Edition)
    CPU: (12) x64 Intel Core Processor (Skylake, IBRS)
  Binaries:
    Node: 16.18.1 - /usr/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.2.0 - /usr/local/bin/npm
  Browsers:
    Firefox: 2.38
  npmPackages:
    @storybook/addon-essentials: ^7.0.0-rc.4 => 7.0.0-rc.4
    @storybook/addon-interactions: ^7.0.0-rc.4 => 7.0.0-rc.4
    @storybook/addon-links: ^7.0.0-rc.4 => 7.0.0-rc.4
    @storybook/blocks: ^7.0.0-rc.4 => 7.0.0-rc.4
    @storybook/react: ^7.0.0-rc.4 => 7.0.0-rc.4
    @storybook/react-vite: ^7.0.0-rc.4 => 7.0.0-rc.4
    @storybook/testing-library: ^0.0.14-next.1 => 0.0.14-next.1
```

### Additional context

I also reported this at https://discord.com/channels/486522875931656193/1086420804163604500

This used to work on v6 via `managerWebpack`

**Comment by shilman** [comment]
The manager is no longer configurable by design, a breaking change in 7.0: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#no-more-configuration-for-manager

If you can't achieve what you're trying to do without manager configuration, please describe the use case here and we can discuss whether there are workarounds. cc @ndelangen

**Comment by agriffis** [comment]
My application consists of blocks with accompanying configuration dialogs (it's a CMS)

With storybook v6, I reused the configuration dialogs in an addon so I could configure the block under development in a story. That involves some heavy dependency on stuff in my primary `src` dir.

My guess is that the path of least resistance here is to stop using addons, and instead make my stories more powerful to host both the block and the accompanying config dialog.

The other use-case for me has been loading [msw](https://mswjs.io/) with a common set of mocked data between the manager and the preview. I was doing that from `manager.ts` previously. Hmm, now that I think about it, that was only in service of the config dialogs, so I don't need it if I'm going to stop using addons for config.

FWIW I agree with the change you made here. I'm sure it's going to make things easier for your ongoing development and fewer bug reports. I just have to figure out how to adapt. 😄

**Comment by ndelangen** [comment]
@agriffis what you could do is prebuild the addon in some build script separate from storybook.
Then import that prebuilt asset in `manager.ts`.

That's the path I'd recommend taking.

We won't be supporting extending the manager build-system going forwards.
You're not the only one getting hit by this, but it's a choice we had to make in the pursuit of performance, and inter-compatibility with vite/webpack/future builders.

We do ship storybook with a list of premade components you can use with ease inside the manager from `@storybook/components` there might be components in there you could use.
We also accept additions to that package.. it's goal is so creating addons doesn't require a lot of custom UI work; so if there is stuff missing, we're open to feedback/suggestion/contributions.

**Comment by agriffis** [comment]
Thanks @ndelangen. I'll have to take a look at how addons are prebuilt.

This approach does make #21673 more important, though, since my addons depend on React 18 features, especially useId`

**Comment by ndelangen** [comment]
@agriffis agreed, that PR will need to happen. I'm not quite sure exactly when or how. It's going to be post 7.0 that's for sure.

**Comment by agriffis** [comment]
FWIW I'm leaning away from porting my addons forward, instead I'll move them to the preview area with some decorators. _waves hands expressively_

In any case, I'll close this now because it's technically not a bug, although it is a pretty significant breaking change for anybody with local addons on a Storybook 6.x setup. It would be great to eventually see a blog post or straightforward example of prebundling a local addon to help people migrate.
