### ISSUE TITLE
[Feature Request]:

### ISSUE THREAD

**Issue by jeengbe** [storybookjs/storybook#21667]
### Is your feature request related to a problem? Please describe

The following line is not entirely clear:

https://github.com/storybookjs/storybook/blob/fa70b596a2480390a5a4ecad04a146550a46f830/docs/writing-stories/decorators.md?plain=1#L106

Does this mean that the above example is a good way to wrap single stories or not?

### Describe the solution you'd like

Depending on how it's supposed to be used, something like:

```
It is useful to ensure that the story remains a “pure” rendering of the component under test, and any extra HTML or components are used only as decorators. In particular, the [Source](../api/doc-block-source.md) doc block works best when you do this.
```

or 

```
It is useful to ensure that the story remains a “pure” rendering of the component under test, and any extra HTML or components are used only as decorators of the component, not the individual story. In particular, the [Source](../api/doc-block-source.md) doc block works best when you do this.
```

might make it more clear

### Are you able to assist to bring the feature to reality?

yes, I can

**Comment by jonniebigodes** [comment]
@jeengbe thanks for taking the time to open up this issue and provide some clarity on the documentation. I've just pushed a pull request addressing your feedback. So that we're clear, the first option you mentioned seemed the most accurate, and I went with it.

Hope you have a great day.

Stay safe
