### ISSUE TITLE
[Bug]: stories/Button.vue has bad reference to button.css

### ISSUE THREAD

**Issue by nstuyvesant** [storybookjs/storybook#21670]
### Describe the bug

When I run `npx storybook@next init` on a freshly created Vue.js 3 project, Storybook won't start because Button.vue line 6 tries to import `buttons.css`. The correct filename is `button.css`.

### To Reproduce

1. Create a new Vue.js project
2. Run `npx storybook@next init`
3. Run `npm run storybook`

### System

```shell
Environment Info:

  System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 18.15.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.6.1 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 111.0.5563.64
    Firefox: 111.0
    Safari: 16.3
  npmPackages:
    @storybook/addon-essentials: ^7.0.0-rc.4 => 7.0.0-rc.4 
    @storybook/addon-interactions: ^7.0.0-rc.4 => 7.0.0-rc.4 
    @storybook/addon-links: ^7.0.0-rc.4 => 7.0.0-rc.4 
    @storybook/blocks: ^7.0.0-rc.4 => 7.0.0-rc.4 
    @storybook/testing-library: ^0.0.14-next.1 => 0.0.14-next.1 
    @storybook/vue3: ^7.0.0-rc.4 => 7.0.0-rc.4 
    @storybook/vue3-vite: ^7.0.0-rc.4 => 7.0.0-rc.4
```

**Comment by jonniebigodes** [comment]
@nstuyvesant, thanks for taking the time to open up this issue and following up with us, I've checked, and you're right about it. It seems that a small regression was introduced recently that led to that issue which, based on some research is only affecting Vue 3 with TypeScript <4.9. A pull request will be up soon addressing it.


Hope you have a great weekend.

Stay safe

**Comment by jonniebigodes** [comment]
@nstuyvesant a pull request is already up and I'll defer to the rest of the team & maintainers to get this across the finish line and hopefully get it out soon. Once again, appreciate you taking the time to let us know of this small but rather important issue. 🙏
