### ISSUE TITLE
[Bug]: npx storybook@next init in an Angular Component Library project assumes it's an app

### ISSUE THREAD

**Issue by nstuyvesant** [storybookjs/storybook#21672]
### Describe the bug

Ran `npx storybook@next init` on an Angular Component library (freshly created. When I tried to run `npm run storybook`, it failed with this error:
```
Error: error TS5012: Cannot read file '/Users/xyz/dev/angular-lib/projects/charts-angular/tsconfig.app.json': ENOENT: no such file or directory, open '/Users/xyz/dev/angular-lib/projects/charts-angular/tsconfig.app.json'.
```

The problem is that `npx storybook@next init` assumed the TypeScript configuration would be in tsconfig.app.json but for Angular libraries, the file is called tsconfig.lib.json.

Storybook init needs to read the angular.json's projects and look at the projectType field to determine if it's an app or a library.

It's easy to fix by adding to storybook and build-storybook in the angular.json...
```
            "tsConfig": "projects/charts-angular/tsconfig.lib.json",
```

As a side note, Angular sets up workspaces (like a monorepo) for libraries as a default. The first library you create is in a subdirectory called projects. It would be nice to have the option to have Storybook created as a project. The use-case would be to have one Storybook for several libraries. It's just a matter of detecting projects and asking the user `Install Storybook into an Angular project or create as its own project?` then adjusting the paths. Curious whether it would detect more than one project in an Angular workspace (did not try it).

### To Reproduce

1. Install @angular/cli globally `npm install -g @angular/cli`
2. Type `ng new angular-lib --no-create-application`
3. Type `cd angular-lib`
4. Type `npm install`
5. Type `ng generate library my-lib`
6. Type `npx storybook@next init`
7. Type `npm run storybook`

### System

```shell
Environment Info:

  System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 18.15.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.6.2 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 111.0.5563.64
    Firefox: 111.0
    Safari: 16.3
  npmPackages:
    @storybook/addon-essentials: ^7.0.0-rc.4 => 7.0.0-rc.4 
    @storybook/addon-interactions: ^7.0.0-rc.4 => 7.0.0-rc.4 
    @storybook/addon-links: ^7.0.0-rc.4 => 7.0.0-rc.4 
    @storybook/angular: ^7.0.0-rc.4 => 7.0.0-rc.4 
    @storybook/blocks: ^7.0.0-rc.4 => 7.0.0-rc.4 
    @storybook/testing-library: ^0.0.14-next.1 => 0.0.14-next.1
```

**Comment by nstuyvesant** [comment]
Also, probably because it didn't see that tsconfig.lib.json initially, the .storybook/ directory was missing from TypeScript compilation...
```
Error: /Users/xyz/dev/angular-lib/projects/charts-angular/.storybook/preview.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
```

**Comment by nstuyvesant** [comment]
And that tsconfig.lib.json was missing "resolveJsonModule": true so it failed.

And Storybook init put the stories in the project's src folder but was looking for them one level up.

These are all easily correctable issues but it took some time to get it running.

**Comment by shilman** [comment]
@valentinpalkovic @sheriffMoose any thoughts here?

**Comment by sheriffMoose** [comment]
@shilman just reproduced, this is happening because we have a single template for angular applications, we need to create another template files for angular libraries as well. should be straight-forward, I will have a PR up shortly.

**Comment by shilman** [comment]
Jiminy cricket!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-rc.5 containing PR #21675 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```
