### ISSUE TITLE
[Documentation]: v7 Spreadable Story Objects should include TypeScript type assertion. 

### ISSUE THREAD

**Issue by dwjohnston** [storybookjs/storybook#21679]
### Describe the bug

In the documentation here: 

https://storybook.js.org/docs/7.0/react/api/csf#:~:text=In%20CSF%203%2C%20we,over%20all%20its%20annotations%3A

The example given is: 

```
// CSF 3
export const PrimaryOnDark = {
  ...Primary,
  parameters: { background: { default: 'dark' } },
};
```

The problem this example as it is, is that it is possible for a developer make a mistake with the values they provide. 

A simple type assertion solves this: 

```
// CSF 3
export const PrimaryOnDark : Story = {
  ...Primary,
  parameters: { background: { default: 'dark' } },
};
```

As an aside, the example given here is inconsistent with the [previous example](https://storybook.js.org/docs/7.0/react/api/csf#:~:text=Here%27s%20the%20CSF%203%20equivalent%3A) we're working with - where it's  dealing with the `args` property. It's unclear to me reading it, what the parameters property is doing, I can look it up, but this bit of documentation is introducing two new concepts. 

### Additional context

It's unclear whether bringing up documentation issues as an issue is on topic or not. When we go to create issue, there is a section for 'documentation' but that just takes you to the documentation, doesn't take you to a place for offering corrections suggestions to the documentation.

**Comment by jonniebigodes** [comment]
@dwjohnston, thank you for reaching out to us with your issue and mentioning that small but rather important misconception in our documentation. We appreciate it. 🙏 . I've checked and should be a small fix I'll push a pull request shortly.
