### ISSUE TITLE
[Bug]: SB7 markdown tables are not rendered

### ISSUE THREAD

**Issue by devgioele** [storybookjs/storybook#21683]
### Describe the bug

In Storybook 6, Markdown tables were rendered correctly. In Storybook 7 I see that Markdown tables are no longer rendered.

![image](https://user-images.githubusercontent.com/63794725/226306586-7666916c-dfce-4c9a-acda-3261f7f56c23.png)

Markdown tables should be rendered in Storybook 7, so I assume this is a bug.

### To Reproduce

Clone [the repro repo](https://github.com/devgioele/sb-issue-md-table) or [see it on StackBlitz](https://stackblitz.com/github/devgioele/sb-issue-md-table?file=stories%2FIntroduction.mdx&preset=node).

### System

```shell
Environment Info:

  System:
    OS: macOS 13.2.1
    CPU: (12) arm64 Apple M2 Pro
  Binaries:
    Node: 16.19.0 - ~/.local/share/.nvm/versions/node/v16.19.0/bin/node
    npm: 8.19.3 - ~/.local/share/.nvm/versions/node/v16.19.0/bin/npm
  Browsers:
    Safari: 16.3
  npmPackages:
    @storybook/addon-essentials: ^7.0.0-rc.4 => 7.0.0-rc.5 
    @storybook/addon-interactions: ^7.0.0-rc.4 => 7.0.0-rc.5 
    @storybook/addon-links: ^7.0.0-rc.4 => 7.0.0-rc.5 
    @storybook/blocks: ^7.0.0-rc.4 => 7.0.0-rc.5 
    @storybook/nextjs: ^7.0.0-rc.4 => 7.0.0-rc.5 
    @storybook/react: ^7.0.0-rc.4 => 7.0.0-rc.5 
    @storybook/testing-library: ^0.0.14-next.1 => 0.0.14-next.1
```

**Comment by shilman** [comment]
MDX2 does not support github-flavored markdown (GFM) out of the box, and starting in v7 neither does Storybook. Please see the docs for how to configure it: https://storybook.js.org/docs/7.0/react/writing-docs/mdx#lack-of-github-flavored-markdown-gfm

**Comment by devgioele** [comment]
Thank you for redirecting me to the solution
