### ISSUE TITLE
[Bug] Composition - during initial load sometimes shows error/empty state instead of loading state

### ISSUE THREAD

**Issue by ndelangen** [storybookjs/storybook#21688]

**Comment by ndelangen** [comment]
![Screenshot 2023-03-20 at 14 31 49](https://user-images.githubusercontent.com/3070389/226355589-51b5df2d-28b1-4f92-8323-f86eb7b89314.png)

**Comment by shilman** [comment]
Yay!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-rc.8 containing PR #21690 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```
