### ISSUE TITLE
[Bug]: storySort not working as a preset add-on in v7

### ISSUE THREAD

**Issue by fnhipster** [storybookjs/storybook#21698]
### Describe the bug

I have a preset addon that, among other things, also sorts stories through multiple projects, but since upgrading to v7, the storySort configuration is no longer picked up. If I copy that over to the project's `.storybook/preset.js`, the sorting works as expected, but it doesn't as part of the add-on.

```js
// addon/index.js

module.exports = {
  managerWebpack: async (config) => {
    return config;
  },

  managerBabel: async (config) => {
    return config;
  },

  webpackFinal: async (config) => {
    return config;
  },

  babel: async (config) => {
   return config;
  },

  previewAnnotations: (entry = []) => {
    return [...entry, path.resolve(__dirname, './preview')];
  },

  managerEntries: (entry = []) => {
    return [...entry, path.resolve(__dirname, './manager')];
  },
};

```

```js
// addon/preset.js
export const parameters = {
  options: {
    method: 'alphabetical',
    storySort: {
      order: ['Base', ['Intro', '*']],
    },
  },
};
```

**Comment by shilman** [comment]
Sorry for the slow reply. This is an expected shortcoming of the V7-style story store. I've updated the documentation here:

https://github.com/storybookjs/storybook/commit/43fc2b1da585911ffc0769bbe1a0a27c1dce52a4

Closing this for now!
