### ISSUE TITLE
[Bug]: Broken rendering of story source (react stories)

### ISSUE THREAD

**Issue by sara0405** [storybookjs/storybook#21709]
### Describe the bug

After upgrading from v7.0.0-beta.53 to **v7.0.0-rc.5** story sources for both stories that use args and function is broken.

Before:

![image004](https://user-images.githubusercontent.com/31178927/226582801-6ec8f8d5-96aa-4743-9b63-51ec44df7041.png)

Now:
![image003](https://user-images.githubusercontent.com/31178927/226582869-126d6a7c-8ddb-459b-abae-b0c6a3d27d4d.png)

### System

```shell
System:
    OS: macOS 12.5.1
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 16.17.1 - /opt/homebrew/opt/node@16/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.15.0 - /opt/homebrew/opt/node@16/bin/npm
 Browsers:
    Chrome: 111.0.5563.64
    Safari: 16.0
```

**Comment by shilman** [comment]
closing as dupe to #21649 , which should have a fix in the next RC. thanks for filing and please reopen if you think this is a separate issue!
