### ISSUE TITLE
[Bug]: Unable to abstract the CSF Default Export with a function

### ISSUE THREAD

**Issue by jimmy-e** [storybookjs/storybook#21703]
### Describe the bug

Hi, I want to abstract the CSF default export object for Storybook, like below:

**metaFunction.js**
```js
export const getMeta = (title, component) => ({
  title: `Example/${title}`,
  component: component,
  tags: ['autodocs'],
  argTypes: {
    backgroundColor: { control: 'color' },
  },
});
```

**Button.stories.js:**
```js
import { Button } from './Button';
import { getMeta } from './metaFunction';

// This works 👇
// const meta = {
//   title: 'Example/Button',
//   component: Button,
//   tags: ['autodocs'],
//   argTypes: {
//     backgroundColor: { control: 'color' },
//   },
// };

// This doesn't 👇
const meta = getMeta('Button', Button);

export default meta;

export const Primary = {
  args: {
    primary: true,
    label: 'Button',
  },
};

export const Secondary = {
  args: {
    label: 'Button',
  },
};

export const Large = {
  args: {
    size: 'large',
    label: 'Button',
  },
};

export const Small = {
  args: {
    size: 'small',
    label: 'Button',
  },
};
```

The problem is that when I use the `getMeta` function, Storybook crashes with the error "CSF: missing default export". It seems like I must declare an object and cannot abstract it at all, or even use a spread object inside the initial meta object.

Is there any way to abstract the CSF default export object with a function?

### To Reproduce

Go to [this repo and the function_debug branch](https://github.com/jimmy-e/storybook-fn-debug/tree/function_debug), run `npm install` and then `npm run storybook`.

### System

```shell
`^7.0.0-rc.5`
```

**Comment by giniedp** [comment]
this holds us back from upgrading to Storybook 7 and CSF 3

**Comment by shilman** [comment]
This is an intentional change. I've updated the code to make the error a little more descriptive: #22190

SB7 statically analyzes the story files for performance reasons and we can't statically analyze functions. You'll need to rewrite your default exports if you've written functions to generate them -- we should have been more explicit about disallowing this kind of code in earlier Storybook versions, but unfortunately that ship has sailed. The performance benefits of the new approach greatly outweigh the costs, so I don't expect this to change in future versions of Storybook.

Closing this for now!

**Comment by giniedp** [comment]
with this feature flag i was able to keep my old abstraction
```
  features: {
    storyStoreV7: false, // 👈 Opt out of on-demand story loading
  },
```
@shilman is that the way to go? Or is it a side effect?
Another way is to export the minimal structure that is needed for the static analyzer and then augment the object with custom code later. But that is ugly and weird.

I understand the performance benefits, but i dislike the idea of being forced to a certain code format. I need to wrap the stories with a custom DSL to reduce some boilerplate code and add typesafety.

**Comment by shilman** [comment]
Whoopee!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.1.0-alpha.8 containing PR #22190 that references this issue. Upgrade today to the `@future` NPM tag to try it out!

```
npx sb@next upgrade --tag future
```

**Comment by shilman** [comment]
Jeepers creepers!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.7 containing PR #22190 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb@latest upgrade
```

**Comment by dmitry-stepanenko** [comment]
Storybook becomes more and more verbose without a need. We have a lot of configurations that we want to abstract, a simple wrapper for the `Meta` could do it. Please bring this functionality back or at least make it optional. For me it's totally fine to sacrifice some of the performance gains in favour of much better DX

**Comment by localusercamp** [comment]
> Storybook becomes more and more verbose without a need.

Absolutely agree, this is just **SO** rediculous...

**Comment by StarDust198** [comment]
Any news on this? Wanted to wrap our stories in a helper too and got same error..

**Comment by StarDust198** [comment]
I've found the solution to make it work:
```
// .storybook/main.js
export default {
  features: {
    storyStoreV7: false,
  }
}
```

**Comment by dmitry-stepanenko** [comment]
> Any news on this? Wanted to wrap our stories in a helper too and got same error..

There's a workaround, that works for now

```typescript
const meta: CosMeta = { 
  title: 'Required Title',
  ...your props
};
cosMeta(meta);
export default meta;

export const Primary = cosStory();
```

Basically we mutate the statically defined `meta` object in. place using `cosMeta` function. All cos-prefixed interfaces and utils from the example are our custom ones.

**Comment by smhutch** [comment]
Tried to upgrade Storybook, and now I need to update 160+ files to remove a carefully crafted abstraction.

@shilman the error message we're showing here still isn't helpful. I _am_ returning an object from the function that I added to add type-safety and other guardrails.

**Comment by frank-topel-dbi** [comment]
@shilman Your performance optimizations **should really be configurable** in this regard. This comes really unexpected and makes it much harder if not impossible to simply automate generation of stories using proper abstractions!

**Comment by DanielAraldi** [comment]
> This is an intentional change. I've updated the code to make the error a little more descriptive: [#22190](https://github.com/storybookjs/storybook/pull/22190)
> 
> SB7 statically analyzes the story files for performance reasons and we can't statically analyze functions. You'll need to rewrite your default exports if you've written functions to generate them -- we should have been more explicit about disallowing this kind of code in earlier Storybook versions, but unfortunately that ship has sailed. The performance benefits of the new approach greatly outweigh the costs, so I don't expect this to change in future versions of Storybook.
> 
> Closing this for now!

Hi @shilman, I'd like to get for you give an update on the [Storybook Test runner](https://storybook.js.org/docs/writing-tests/test-runner). I used and followed this documentation step by step, but **absolutely nothing** worked because this error occurred. Do you have some suggestions?

**Comment by Desteel** [comment]
> with this feature flag i was able to keep my old abstraction
> 
> ```
>   features: {
>     storyStoreV7: false, // 👈 Opt out of on-demand story loading
>   },
> ```
> 
> https://storybook.js.org/docs/angular/configure/overview#on-demand-story-loading
> 
> [@shilman](https://github.com/shilman) is that the way to go? Or is it a side effect? Another way is to export the minimal structure that is needed for the static analyzer and then augment the object with custom code later. But that is ugly and weird.
> 
> I understand the performance benefits, but i dislike the idea of being forced to a certain code format. I need to wrap the stories with a custom DSL to reduce some boilerplate code and add typesafety.

It seems that it is not available in the latest version. Is there any other workaround?

**Comment by alex-page** [comment]
This would be super helpful when splitting stories for public and private storybook deploys. Trying to do something like this to adjust what exported stories are used doesn't feel great with the current limitations:

```ts
export const generateMeta = (meta: Meta) => {
  const { tags } = meta;
  const hasPublicStories = process.env.STORYBOOK_PUBLIC === 'true' && !tags?.includes('unstable');

  meta = {
    ...meta,
    ...(hasPublicStories ? { includeStories: ['All'] } : {}),
  } satisfies Meta;
};
```
