### ISSUE TITLE
[Bug]: build-storybook with @storybook/builder-vite produce invalid assets URLs

### ISSUE THREAD

**Issue by tor-nav** [storybookjs/storybook#21711]
### Describe the bug

I recently started building Storybook using Vite instead of Webpack. But when I try to build static code with @storybook/builder-vite the assets url doesn't seem to be correct. From iframe.html:
```
    <script type="module" crossorigin src="/assets/iframe-2d7f30d5.js"></script>
    <link rel="stylesheet" href="/assets/iframe-10c03eda.css">
```
This will produce the folloving url: https://domain-name/assets/iframe-2d7f30d5.js.
If I add '.' to the url in the script and link tags it will work ('./assets/...')

The static code produced by the webpack builder doesn't have any assets folder. Everything are in the root folder and works as expected.

### System

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700H
  Binaries:
    Node: 18.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.4.1 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.3.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 111.0.5563.65
    Edge: Spartan (44.19041.1266.0), Chromium (111.0.1661.44)
  npmPackages:
    @storybook/addon-essentials: 6.5.16 => 6.5.16
    @storybook/addon-links: 6.5.16 => 6.5.16
    @storybook/addons: 6.5.16 => 6.5.16
    @storybook/builder-vite: 0.4.2 => 0.4.2
    @storybook/builder-webpack5: 6.5.16 => 6.5.16
    @storybook/cli: 6.5.16 => 6.5.16
    @storybook/manager-webpack5: 6.5.16 => 6.5.16
    @storybook/react: 6.5.16 => 6.5.16
    @storybook/storybook-deployer: 2.8.16 => 2.8.16
    @storybook/testing-react: 1.3.0 => 1.3.0
    @storybook/theming: 6.5.16 => 6.5.16
```

**Comment by shilman** [comment]
Please try upgrading to the latest prerelease where I believe this is fixed.

Migration guide: https://storybook.js.org/migration-guides/7.0

I'll see if there's something we can patch back to 6.5 to fix this issue there as well. It's an upstream issue in rollup.

**Comment by tor-nav** [comment]
> Please try upgrading to the latest prerelease where I believe this is fixed.
> 
> Migration guide: https://storybook.js.org/migration-guides/7.0
> 
> I'll see if there's something we can patch back to 6.5 to fix this issue there as well. It's an upstream issue in rollup.

I did in fact try to upgrade to v7.0.0-rc.6. Everything worked locally, but I got this error after deploying to github:

`Failed to fetch dynamically imported module: https://domain/preview-1bb7c46c.js `

The file exists on the server, so it seems odd that it can't be fetched

**Comment by amcdnl** [comment]
I'm getting the same thing when using Vite + React + TS and then deploying to Github Pages. Odd thing is if I copy / paste the url it fails on into the bar it works.

<img width="1378" alt="image" src="https://user-images.githubusercontent.com/227909/229894985-4405ca5e-3694-4826-a827-caed138e30d5.png">

**Comment by ndelangen** [comment]
Thank you for the comment @amcdnl 

I'm going to close this as "not an issue with storybook" but I am open to discussing what we could do on our side to make this work better.

**Comment by j0k3r** [comment]
Otherwise, you need to create a `. nojekyll ` at the root of the directory on the `gh-pages` branch

See https://github.blog/2009-12-29-bypassing-jekyll-on-github-pages/

**Comment by laclys** [comment]
Your comment helped me, thanks for sharing! @j0k3r

**Comment by ZennerBlade** [comment]
Almost same issue here.
I'm using gh-pages but when the run the deploy command, the nojekyll file gets deleted automatically from the gh-pages branch and i get the same error.
Any idea why?
