### ISSUE TITLE
[Bug]: Storybook 7 migration not sucessful in monorepo

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#21710]
### Describe the bug

When migrating a Storybook project included in a monorepo setting, Storybook is broken and can't start.
I have seen this on about four projects, using yarn workspaces and turborepo as well.

The error relates to how Storybook libraries are (wrongly) hoisted. The error message most of the times is related to not finding a framework package:

<img width="708" alt="image" src="https://user-images.githubusercontent.com/1671563/226576714-d257fdbf-062a-4cce-9793-45722881479d.png">

Reason being that `@storybook/core-server` is hoisted at the root level, while `@storybook/web-components` **it not hoisted** and stays at a package level, therefore a call like `require('@storybook/web-components')` coming from core-server, fails and displays that error.

The fix normally is to either:
- nuke lock files (e.g. yarn.lock) and rerun install
- force install e.g. `yarn install --force`
- add `nohoist` for Storybook libraries e.g.
```
"workspaces": {
  "nohoist": [
	  "**/@storybook/**",
      "**/storybook"
    ]
}
```

But neither of the solutions are optimal, as they can affect user's code. The `nohoist` solution only works for package managers that support it, therefore projects that use tools like turborepo can't use such fix.

### To Reproduce

- I'm in the process of getting a repro!

**Comment by TheTedAdams** [comment]
Just adding I have been unable to get 7 to run in a `pnpm` monorepo. I have an `.npmrc` file with `hoist=false` in it. I removed `@storybook/react` from the root package.json so there shouldn't be any hoisting happening. But I still get
```
WARN   Failed to load preset: "@storybook/react-webpack5/preset"
ERR! Error: Cannot find module '@storybook/react-webpack5/preset'
```

I tried swapping react-webpack5 for react-vite and got the exact same error but with `@storybook/react-vite/preset`.

**Comment by nstuyvesant** [comment]
In my case, I am using yarn 3.5.0 workspaces and lerna. I was able to temporarily workaround the issue by adding
```
nmHoistingLimits: workspaces
```
to my monorepo's .yarnrc.yml. I see this only as a temporary solution.

**Comment by sidmclaughlin** [comment]
This also happens in npm workspaces.

I was able to work around this issue by putting the @storybook/* devDependencies in the root package.json.

**Comment by yannbf** [comment]
@nstuyvesant @sidmclaughlin @TheTedAdams thank you so much for reporting this! Is any of your projects open source? I'm having a really hard time trying to create a reproduction and was not able to. If any of you could share a reproduction I'd be forever thankful

**Comment by nstuyvesant** [comment]
Absolutely! It is challenging to build a monorepo from scratch.

Please install yarn@3.5.0 before these steps (and use node 18.15.0)...

```bash
git clone https://github.com/nstuyvesant/carbon-charts.git
cd carbon-charts
git checkout next
git pull
yarn install
yarn build
cd packages/charts-angular
yarn storybook
cd ../charts-react
yarn storybook
# you get the idea
```

You can play with the settings in the top-level .yarnrc.yaml file (`nmHoistingLimits: workspaces`). Try taking that line out then...
```
yarn clean
yarn install
yarn build
```

**Comment by mxp-qk** [comment]
Hi,

I have the same issue `Cannot find module '@storybook/react-vite/preset'` with rc-9 but it is working with rc-3 without modifying anything else

**Comment by nstuyvesant** [comment]
Please check out @JReinhold's last comment on https://github.com/storybookjs/storybook/issues/21788 - it may be related.

**Comment by pmartinsdev** [comment]
Same problem here guys.

I'm using yarn workspaces, and I tried to install into a angular project

![image](https://user-images.githubusercontent.com/55673235/230466091-9ffd2e92-2dde-4309-adb4-a7f429359668.png)

**Comment by ekeijl** [comment]
A temporary workaround for Yarn users is to add an override for the core package in your Yarn config.

In `.yarnrc.yml` add the following section:

```
packageExtensions:

    "@storybook/core-common@*":
        dependencies:
            "@storybook/react-webpack5": "7.0.3"
```

Replace `@storybook/react-webpack5` by the missing module (and use the same version as your other Storybook dependencies)

**Comment by briandipalma** [comment]
Same issue in another pnpm monorepo:

![image](https://user-images.githubusercontent.com/1597820/234243551-edb3982e-7db4-4679-8f6b-93871854b0e4.png)

The fact that it's happening in pnpm, yarn and npm monorepos does make it seem like there is something wrong in how storybook v7 is setup/specifying its dependencies.

**Comment by TheTedAdams** [comment]
All the pnp implementations intend to not allow packages to access any other package that isn't specified as a dep in their package.json as an intentional part of their design...

So the problem would seem to be that while `@storybook/react-webpack5` is a dep in the user's application's package.json, because it is not listed as a dep in `@storybook/core-common` the pnp implementations are not making it available to `require()` (This assumption is supported by @ekeijl 's fix working. Telling yarn that `@storybook/core-common` has the preset as a dep makes it magically available via pnp/symlink).

I think conceptually what would work is if rather than passing `framework: { name: 'astringnameofamodule' }` we had something more along the lines of `framework: require('astringnameofmodule')`

That is to say, `@storybook/react-webpack5` would be available to import in `.storybook/main.js` because it's listed as a dep in the storybook app's package.json, but passing the module name as a string and letting `core-common` do the import is the cause of the issue...

**Comment by yjoer** [comment]
I am using Yarn 3.5.0 with the pnpm linker within a monorepo. It turned out that I have to specify `@babel/core`, `react`, and `react-dom` in addition to `@storybook/react-webpack5` mentioned by @ekeijl (https://github.com/storybookjs/storybook/issues/21710#issuecomment-1504976732) to dismiss all the errors while starting up as well as during the compilation.

```yml
'@storybook/core-common@*':
  dependencies:
    '@babel/core': '*'
    'react': '*'
    'react-dom': '*'
    '@storybook/react-webpack5': '*'
```

**Comment by erickreutz** [comment]
Using `pnpm` in a monorepo I ran into this issue. Tweaking `.npmrc` config was no help. Adding `"@storybook/react-webpack5": "~7.0.6"` as a dev dependency to my root `package.json` fixed the issue. It's not ideal but it works for now.

**Comment by lee-chase** [comment]
I barely made it past the `npx storybook@latest upgrade` which complained it could not find my config. Tried passing `--config-dir` without success.

Tried storybook versions directly and then upgrading files to find complaints about dynamic titles.

Tried running storybook, but that bombs out 
```
command not found: start-storybook
ERROR: "start:storybook" exited with 1.
ERROR: "storybook:start" exited with 1.
```

We have our storybook in a package called `core` for historical reasons and they may return in the future.

https://github.com/carbon-design-system/ibm-products

**Comment by adrianu197** [comment]
I had the same issue(about `Cannot find module '@storybook/react-webpack5/preset'`) and I solved it with:
https://storybook.js.org/docs/react/faq#how-do-i-fix-module-resolution-while-using-pnpm-plug-n-play

![Screenshot 2023-06-21 at 16 53 55](https://github.com/storybookjs/storybook/assets/33718513/6a8697ab-05b8-4ac2-a006-44ebe6c39f9c)

**Comment by asyndesis** [comment]
Thanks, @adrianu197!

We are using `yarn v1` and a `lerna 6.5` monorepo.

My working `.storybook/main.js`:

```js
import path from 'path';
const wrapForPnp = (packageName) =>
  path.dirname(require.resolve(path.join(packageName, 'package.json')));

const config = {
  core: {
    builder: 'webpack5',
  },
  framework: {
    name: wrapForPnp('@storybook/react-webpack5'),
    options: {},
  },
  stories: ['../stories/**/*.stories.@(js|mdx)'],
  addons: [
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    'storybook-dark-mode',
  ],
  docs: {
    autodocs: true,
  },
};

export default config;

```

**Comment by lurdharry** [comment]
@adrianu197  and @asyndesis  solutions worked for me

**Comment by Banyalis** [comment]
Hello!
Same problem.
`Vue2, Storybook 7.6.17`
Error when starting - `Storybook failed to load the following preset: ./node_modules/@storybook/vue-webpack5/preset.`
My config:
```
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const path = require('path');
const getAbsolutePath = (packageName) =>
    path.dirname(require.resolve(path.join(packageName, 'package.json')));

module.exports = {
    stories: ['../src/**/*.mdx', '../src/**/*.stories.@(js|jsx|mjs|ts|tsx)'],
    framework: {
        name: getAbsolutePath('@storybook/vue-webpack5'),
        options: {}
    },
    ...
};

```

**Comment by brianunlam** [comment]
I could solve it change it my main.js storybook file from

```
module.exports = {
  stories: ["../**/*.stories.mdx", "../**/*.stories.@(js|jsx|ts|tsx)"],

  addons: [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/addon-interactions",
    "@storybook/addon-mdx-gfm"
  ],

  framework: {
    name: "@storybook/react-webpack5",
    options: {}
  },

  staticDirs: ["../stories/media", "../stories/stockfish"],

  docs: {
    autodocs: true
  }
};

```

to 


```
const path = require('path');

// Utility function to resolve absolute paths for packages
const getAbsolutePath = (packageName) =>
  path.dirname(require.resolve(path.join(packageName, 'package.json')));

module.exports = {
  stories: ["../**/*.stories.mdx", "../**/*.stories.@(js|jsx|ts|tsx)"],

  addons: [
    getAbsolutePath("@storybook/addon-links"),
    getAbsolutePath("@storybook/addon-essentials"),
    getAbsolutePath("@storybook/addon-interactions"),
    getAbsolutePath("@storybook/addon-mdx-gfm"),
  ],

  framework: {
    name: getAbsolutePath("@storybook/react-webpack5"),
    options: {},
  },

  staticDirs: ["../stories/media", "../stories/stockfish"],

  docs: {
    autodocs: true,
  },
};

```

as it was suggested by @adrianu197 using this link:

https://storybook.js.org/docs/faq#how-do-i-fix-module-resolution-in-special-environments
