### ISSUE TITLE
[Feature Request]: Upgrade glob package to 9.x

### ISSUE THREAD

**Issue by ethriel3695** [storybookjs/storybook#21726]
### Is your feature request related to a problem? Please describe

The `glob` [package](https://github.com/storybookjs/storybook/blob/next/code/package.json#L232) used in Storybook has a new major version.

The new `9.x` version of [this package](https://github.com/isaacs/node-glob/blob/main/changelog.md#90) has significant algorithm and API changes.

### Describe the solution you'd like

Updating to the latest version of the package will result in keeping user projects in line with major version updates and the latest major version of the package has significant performance improvements.

### Describe alternatives you've considered

The alternative to upgrading the package is to continue using the `8.x` version that Storybook currently implements.

### Are you able to assist to bring the feature to reality?

yes, I can

### Additional context

I've talked to the Storybook core maintainers about this and they agree it's a great idea but will require a bit of work to implement so this is definitely something that won't be considered until after the Storybook 7.0 release.

**Comment by znarf** [comment]
Done in https://github.com/storybookjs/storybook/pull/22171
