### ISSUE TITLE
[Feature Request]: Storybook 7: previous browsers support for iframe

### ISSUE THREAD

**Issue by Semigradsky** [storybookjs/storybook#21725]
### Is your feature request related to a problem? Please describe

By https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#modern-browser-support Storybook 7 no longer supported old browsers, but I need to screenshot testing my site in pretty old browsers (Chrome 67, Firefox 69). Currently, I using for this storybook in iframe mode.

I have added `babel.config` and `.browserslistrc` files, it helped with my code. But `sb-preview/runtime.mjs` and other storybook files transpired with a target of chrome >= 100.

### Describe the solution you'd like

Transpile storybook files with a previous target (or https://caniuse.com/es6-module support). Or any other workaround, please

### Are you able to assist to bring the feature to reality?

no

**Comment by shilman** [comment]
AFAIK you'll need to stick with 6.x for this. @ndelangen can you help here?

**Comment by ndelangen** [comment]
@Semigradsky we won't be supporting this use-case, we will target modern browser from now on.
We'll make no gaurentees about our code running in environments `chrome < 100` or `node < 16`.

You could use something like https://www.npmjs.com/package/patch-package and transpile our shipped code, if you so desire/dare.

**Comment by Semigradsky** [comment]
😢
