### ISSUE TITLE
[Bug]: Unable to create separate files for CSF Stories

### ISSUE THREAD

**Issue by jimmy-e** [storybookjs/storybook#21734]
### Describe the bug

My current storybook file looks like the following:

**Button.stories.js:**
```js
import { Button } from './Button';

export default {
  title: 'Example/Button',
  component: Button,
  tags: ['autodocs'],
  argTypes: {
    backgroundColor: { control: 'color' },
  },
};

export const Primary = {
  args: {
    primary: true,
    label: 'Button',
  },
};

export const Secondary = {
  args: {
    label: 'Button',
  },
};

export const Large = {
  args: {
    size: 'large',
    label: 'Button',
  },
};

export const Small = {
  args: {
    size: 'small',
    label: 'Button',
  },
};
```

I want to be able to create a separate file for my stories and then import them into `Button.stories.js`, however, when I try and do so, these stories do not get created. See the below:

**Button.examples.js:**
```js
import { Button } from './Button';

export const Primary = {
  args: {
    primary: true,
    label: 'Button',
  },
};

export const Secondary = {
  args: {
    label: 'Button',
  },
};

export const Large = {
  args: {
    size: 'large',
    label: 'Button',
  },
};

export const Small = {
  args: {
    size: 'small',
    label: 'Button',
  },
};
```

**Button.stories.js:**
```js
import { Button } from './Button';
export * from './Button.examples';

export default {
  title: 'Example/Button',
  component: Button,
  tags: ['autodocs'],
  argTypes: {
    backgroundColor: { control: 'color' },
  },
};
```

### To Reproduce

Go to [this repo / branch](https://github.com/jimmy-e/storybook-fn-debug/tree/how_to_export), run `npm install`, and then `npm run storybook`.

### System

```shell
`^7.0.0-rc.5`
```

**Comment by shilman** [comment]
In Storybook 7 we use a [performance optimization](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#storystorev7-enabled-by-default) that requires that all CSF exports be statically analyzable.

Try updating your `.stories.js` file like so:

```js
export { Primary, Secondary, Large, Small } from './Button.examples';
```

You can also opt out of the new behavior, though I would recommend against it:

```js
// .storybook/main.js
export default {
  features: {
    storyStoreV7: false,
  }
}
```

**Comment by jimmy-e** [comment]
Ok great, that works, thanks!
