### ISSUE TITLE
[Bug]: tsx story's `parameters.docs.source.type = 'code'` shows compiled js code

### ISSUE THREAD

**Issue by zb-sj** [storybookjs/storybook#21747]
### Describe the bug

Doc's source view shows precompiled code while trying to provide sample with TypeScript code.

It also includes unnecessary parts such as `play`, `args` etc.. 
where previously only showed what's in `render` part.

### To Reproduce

[zb-sj/storybook-issue-21747/Issue.stories.tsx](https://github.com/zb-sj/storybook-issue-21747/blob/master/stories/Issue.stories.tsx)

```ts
// Issue.stories.tsx
import type { Meta, StoryObj } from '@storybook/react';
import { within, userEvent } from '@storybook/testing-library';
import { useState } from 'react';

import { Button } from './Button';

const meta: Meta = {
  component: Button,
  tags: ['autodocs'],
  parameters: {
    layout: 'fullscreen',
  },
};

export default meta;

function SampleComponent(args: { foo: string }) {
  const [label, setLabel] = useState('hello');

  return <Button label={label} onClick={() => setLabel(`${args.foo} bar`)} />;
}

type Story = StoryObj<typeof SampleComponent>;

export const CodeIssue: Story = {
  render: SampleComponent,
  args: {
    foo: 'foo',
  },
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement);
    const loginButton = await canvas.getByRole('button', {
      name: /Log in/i,
    });
    await userEvent.click(loginButton);
  },
  parameters: {
    docs: {
      source: {
        type: 'code',
      },
    },
  },
};
```
```js
// code in docs
{
  render: SampleComponent,
  args: {
    foo: 'foo'
  },
  play: function () {
    var _play = _asyncToGenerator( /*#__PURE__*/_regeneratorRuntime.mark(function _callee(_ref) {
      var canvasElement, canvas, loginButton;
      return _regeneratorRuntime.wrap(function _callee$(_context) {
        while (1) switch (_context.prev = _context.next) {
          case 0:
            canvasElement = _ref.canvasElement;
            canvas = within(canvasElement);
            _context.next = 4;
            return canvas.getByRole('button', {
              name: /Log in/i
            });
          case 4:
            loginButton = _context.sent;
            _context.next = 7;
            return userEvent.click(loginButton);
          case 7:
          case "end":
            return _context.stop();
        }
      }, _callee);
    }));
    function play(_x) {
      return _play.apply(this, arguments);
    }
    return play;
  }(),
  parameters: {
    docs: {
      source: {
        type: 'code'
      }
    }
  }
}
```

### System

```shell
Environment Info:

  System:
    OS: macOS 13.2
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 16.19.1 - ~/.nvm/versions/node/v16.19.1/bin/node
    Yarn: 3.4.1 - /usr/local/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.1/bin/npm
  Browsers:
    Chrome: 111.0.5563.64
    Safari: 16.3
```

### Additional context

was first discussed at [discord](https://discord.com/channels/486522875931656193/1088335391867818075)

**Comment by shilman** [comment]
@valentinpalkovic could this be due to the changes in https://github.com/storybookjs/storybook/pull/21629 ?

**Comment by valentinpalkovic** [comment]
@shilman Yes, the bug was caused by https://github.com/storybookjs/storybook/pull/21629. I have to investigate a proper solution.

**Comment by dohomi** [comment]
I experience the same issue. After transition from v6 => v7 all docs with render functions have a unreadable output:
https://tamagui-extras.vercel.app/?path=/docs/ui-forms-button--documentation#sizes

**Comment by mscrivo** [comment]
> I experience the same issue. After transition from v6 => v7 all docs with render functions have not the same output as v6. It seems docs: "code" makes no difference: [tamagui-extras.vercel.app/?path=/docs/ui-forms-button--documentation#sizes](https://tamagui-extras.vercel.app/?path=/docs/ui-forms-button--documentation#sizes)

same exact issue here. Is there a workaround to get show code to work with 7?

**Comment by Azcanba** [comment]
@mscrivo  There is one but only when you are really desperate :)

you can create template literals from your code for example 

const codeSnippet = `<Box> Some text </Box>`

and then you can pass it in the exact story like 
parameters: {
  docs: {
    source: { code: codeSnippet }
  }
}

**Comment by erosenberg** [comment]
This is happening for me as well. I didn't set any parameters manually, but I'm still seeing compiled JS instead of what the source code should look like.

**Comment by valentinpalkovic** [comment]
@ccsenter we are actively working on it (https://github.com/storybookjs/storybook/pull/22048). I hope I am able to merge the PR tomorrow.

**Comment by ccsenter** [comment]
That's great!

**Comment by shilman** [comment]
Yowza!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.1.0-alpha.4 containing PR #22048 that references this issue. Upgrade today to the `@future` NPM tag to try it out!

```
npx sb@next upgrade --tag future
```

**Comment by Flcwl** [comment]
> Yowza!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.1.0-alpha.4 containing PR #22048 that references this issue. Upgrade today to the `@future` NPM tag to try it out!
> 
> ```
> npx sb@next upgrade --tag future
> ```

@shilman  To be latest please~

**Comment by shilman** [comment]
Whoopee!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.5 containing PR #22048 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb@latest upgrade
```

**Comment by bratanon** [comment]
> It also includes unnecessary parts such as `play`, `args` etc..
> where previously only showed what's in `render` part.

This is still an issue for me. 

```
Environment Info:

  System:
    OS: Linux 5.19 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700K
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
  Browsers:
    Chrome: 112.0.5615.121
    Firefox: 112.0.1
  npmPackages:
    @storybook/addon-actions: ^7.0.7 => 7.0.7 
    @storybook/addon-essentials: ^7.0.7 => 7.0.7 
    @storybook/addon-interactions: ^7.0.7 => 7.0.7 
    @storybook/addon-links: ^7.0.7 => 7.0.7 
    @storybook/addon-mdx-gfm: ^7.0.7 => 7.0.7 
    @storybook/addon-postcss: ^2.0.0 => 2.0.0 
    @storybook/addons: ^7.0.7 => 7.0.7 
    @storybook/react: ^7.0.7 => 7.0.7 
    @storybook/react-webpack5: ^7.0.7 => 7.0.7 
    @storybook/testing-library: ^0.1.0 => 0.1.0 
    @storybook/theming: ^7.0.7 => 7.0.7 
```

**Comment by valentinpalkovic** [comment]
The fix only aimed to not show compiled code anymore. I am not sure, whether we only want to display code from the `render` part. @JReinhold, @tmeasday might have further insights

**Comment by tmeasday** [comment]
It seems like maybe a reasonable thing to do, let's open a feature request for it?

**Comment by JReinhold** [comment]
@tmeasday considering this was the behavior in 6.5 I would consider this a regression and not a feature request. I've filed a separate bug for it at #22281
