### ISSUE TITLE
[Bug]: Have no possibility to open the addons (controls)

### ISSUE THREAD

**Issue by ArtemFedorchuk** [storybookjs/storybook#21765]
### Describe the bug

From time to time I get an issue with the opening controls in my stories.
Sometimes I have the possibility to open it and then after some time the button (on the top right corner) which open the addons disappears, and when I press the `A` button it appears and after clicking this button it disappears again without opening the addons. 

I didn't change any environments or settings or something like this in the Storybook but from time to time I catch this bug.
I've tried to restart the Storybook but it hasn't helped me and I've just had to play with my stories from the `Docs`.

**main.js file**
<img width="683" alt="Screenshot 2023-03-24 at 12 33 24" src="https://user-images.githubusercontent.com/43110065/227498337-8ca7f21c-e34b-47ef-8b06-14a847754b2b.png">

**package.json**
<img width="449" alt="Screenshot 2023-03-24 at 12 21 07" src="https://user-images.githubusercontent.com/43110065/227495803-f457c94b-6b4d-442d-92a7-3d690977b660.png">

### System

```shell
System:
    OS: macOS 13.1
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.17 - ~/.yarn/bin/yarn
    npm: 8.5.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 111.0.5563.110
    Firefox: 107.0.1
    Safari: 16.2
```

**Comment by shilman** [comment]
closing as dupe to #14916
