### ISSUE TITLE
[Bug]: Failed to resolve module in static storybook build

### ISSUE THREAD

**Issue by brettsaunders21** [storybookjs/storybook#21771]
### Describe the bug

1. In a Vite (using Vue 2.7) project I setup Storybook using `npx sb@next init` 
2. Ran yarn build-storybook
3. Copied the storybook-static to an empty GitHub repository and renamed folder docs
4. Setup github pages to point to that branch and docs folder

When I visit the github pages link storybooks loads but I see the following error `Failed to resolve module specifier "vue/dist/vue.esm.js". Relative references must start with either "/", "./", or "../".`

![image](https://user-images.githubusercontent.com/32368716/227577744-b32619c1-f3c0-416d-902f-2b60afa8c7bd.png)

### To Reproduce

Repo: https://github.com/brettsaunders21/storybook-issue-21771
https://brettsaunders21.github.io/storybook-issue-21771/

Steps
1.  Run reproducer command and select Vue 2.7 
2. Run yarn in repo
3. Run yarn build-storybook
4. Copy contents of static-storybook to new branch gp-pages with no other contents in
5. Go to Gihtub repo settings, pages
6. Select deploy from branch, gp-pages and /root and save
7. Open deploy and see dynamic import error 
![image](https://user-images.githubusercontent.com/32368716/229245893-96e07aea-5d92-446d-81cf-d848b4de6a9c.png)

**Comment by shilman** [comment]
Do you a have a reproduction repo you can share? If not, can you create one? See [how to create a repro](https://storybook.js.org/docs/react/contribute/how-to-reproduce). Thank you! 🙏

**Comment by brettsaunders21** [comment]
> Do you a have a reproduction repo you can share? If not, can you create one? See [how to create a repro](https://storybook.js.org/docs/react/contribute/how-to-reproduce). Thank you! 🙏

Updated to include reproducer

**Comment by nhabre13** [comment]
I would like to add to this issue. I am using storybook v7 and when I try to load a static version of my storybook I get the same error mentioned above

**Comment by brettsaunders21** [comment]
@shilman Any update on this? It seems like there is no way to host a site when using Vue2.7 and Vite?

Dev mode is the only way to get storybook running but can't really use that to host it.

**Comment by ndelangen** [comment]
For reference:
https://stackoverflow.com/questions/40104627/ignore-a-path-on-a-github-pages-site
https://github.com/mpetrovich/stylemark/issues/65

This seems to be a solution:
https://github.com/mpetrovich/stylemark/issues/65#issuecomment-492130126
