### ISSUE TITLE
[Bug]: server config in vite.config.ts is overwritten by builder-vite/src/vite-server.ts

### ISSUE THREAD

**Issue by andreev-artem** [storybookjs/storybook#21772]
### Describe the bug

https://github.com/storybookjs/storybook/blob/a0d5ecf8ec0d02c9ac4e38720107ecc9ec0689f6/code/lib/builder-vite/src/vite-server.ts#L13-L28

If `commonConfig` contains `server` config option it will be overwritten. Eg: `fs.allow` will not work.

Workaround: setup `fs.allow` in `main.cjs` using following code:
```javascript
    async viteFinal(config) {
        return mergeConfig(config, {
            server: {
                fs: {
                    allow: ['.', '../some/your/path/'],
                },
            },
        });
    },
```

### System

```shell
Environment Info:

  System:
    OS: Windows 10 10.0.19045
    CPU: (4) x64 Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz
  Binaries:
    Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 111.0.5563.111
    Edge: Spartan (44.19041.1266.0), Chromium (111.0.1661.51)
  npmPackages:
    @storybook/addon-actions: ^7.0.0-rc.5 => 7.0.0-rc.5
    @storybook/addon-essentials: ^7.0.0-rc.5 => 7.0.0-rc.5
    @storybook/addon-interactions: ^7.0.0-rc.5 => 7.0.0-rc.5
    @storybook/addon-links: ^7.0.0-rc.5 => 7.0.0-rc.5
    @storybook/addon-mdx-gfm: ^7.0.0-rc.5 => 7.0.0-rc.5
    @storybook/react: ^7.0.0-rc.5 => 7.0.0-rc.5
    @storybook/react-vite: ^7.0.0-rc.5 => 7.0.0-rc.5
    @storybook/testing-library: ^0.0.14-next.1 => 0.0.14-next.1
```

**Comment by shilman** [comment]
@IanVS is it an intentional design choice to override the server properties completely?

**Comment by IanVS** [comment]
Yes, it is intentional.  In general, Storybook will not function correctly with user-specified server config, so we don't try to automatically merge it.  The workaround specified here, using `viteFinal` is the correct approach that I would recommend, and is the kind of reason we have such an escape-hatch.

**Comment by IanVS** [comment]
That said, we could try to merge `server.fs.allow`, as a special case...

**Comment by ndelangen** [comment]
Based on the comments above, I've changed this to a feature-request.

**Comment by ndelangen** [comment]
@IanVS I think we should not make an exception here, and just let the user configure this using `main.ts` and `viteFinal`.

I'll close this, let me know if you disagree?

**Comment by fvsch** [comment]
> If we hear from users being confused by it

Definitely was confused by this. Went on a hours-long detour trying to configure stuff on the Vite config file that get overriden by StoryBook.

I think the docs at https://storybook.js.org/docs/react/builders/vite#configuration could be clarified:

- The docs language suggests that StoryBook does some deep or clever merging, not a shallow merge where the entire `config.server` gets replaced by StoryBook's config.
- Maybe add the `config.server.fs.allow` use case to the “Troubleshooting” section?

Language I understood as suggesting my config would be “merged with” StoryBook's config, not overwritten:

> Storybook's Vite builder includes a set of configuration defaults for the supported frameworks, which are merged alongside your existing configuration file.

> For an optimal experience when using the Vite builder, we recommend applying any configuration directly inside Vite's configuration file.

> When Storybook loads, it automatically merges the configuration into its own.

**Comment by fvsch** [comment]
Related issue: https://github.com/storybookjs/storybook/issues/19873
