### ISSUE TITLE
[Bug]: 7.0.0-rc.8 @storybook/react-vite - Memory utilization for storybook build for react 18

### ISSUE THREAD

**Issue by nstuyvesant** [storybookjs/storybook#21781]
### Describe the bug

Can you please check the memory utilization to do a storybook build using @storybook/react-vite? For my monorepo, I am building storybooks for Angular, HTML, React, Svelte and Vue3.

The React storybook was failing to deploy to Netlify due to:
11:35:30 AM: FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory

The others deployed fine. I had to change the build from lerna to yarn directly and cut out one of the vite plugins using viteFinal.

All the storybooks for my monorepo are virtually identical as are the packages they are based on. There seems to be something different about @storybook/react-vite that causes the memory utilization to be higher than builds for Angular, Svelte, HTML and Vue3.

### To Reproduce

```
git clone https://github.com/nstuyvesant/carbon-charts.git
git checkout next
git pull
cd carbon-charts
yarn install
cd packages/charts-react
yarn build
```

### System

```shell
Environment Info:

  System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 18.15.0 - /opt/homebrew/bin/node
    Yarn: 3.5.0 - /opt/homebrew/bin/yarn
    npm: 9.6.2 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 111.0.5563.110
    Firefox: 111.0
    Safari: 16.3
  npmPackages:
    @storybook/addon-essentials: ^7.0.0-0 => 7.0.0-rc.8 
    @storybook/addon-interactions: ^7.0.0-0 => 7.0.0-rc.8 
    @storybook/addon-links: ^7.0.0-0 => 7.0.0-rc.8 
    @storybook/blocks: ^7.0.0-0 => 7.0.0-rc.8 
    @storybook/manager-api: ^7.0.0-0 => 7.0.0-rc.8 
    @storybook/react: ^7.0.0-0 => 7.0.0-rc.8 
    @storybook/react-vite: ^7.0.0-0 => 7.0.0-rc.8 
    @storybook/testing-library: ^0.0.14-next.1 => 0.0.14-next.1 
    @storybook/theming: ^7.0.0-0 => 7.0.0-rc.8
```

**Comment by ndelangen** [comment]
> and cut out one of the vite plugins using viteFinal.

Which one?
What did you change?
This change does not show up in your repro:
https://github.com/nstuyvesant/carbon-charts/blob/next/packages/charts-react/.storybook/main.ts

**Comment by nstuyvesant** [comment]
Sorry about that... spinning a lot of plates to get the 2.0 release done. I undid that and focused on making sure storybook build had enough memory...

In this repo's current state, I changed the `build:demo` script in packages/charts-react/package.json to add `NODE_OPTIONS=--max_old_space_size=9126` at the beginning of the line to keep the deploys from the failing.

**Comment by nstuyvesant** [comment]
What's odd is that I never had memory issues with the storybook build for HTML, Angular, Svelte, or Vue.

**Comment by ndelangen** [comment]
@nstuyvesant I see.. I'm not sure there's anything I can do here at this point.

This memory problem could be in so many layers, and it likely only is a problem when some of those layers overlap in the exact wrong way.
This is near impossible for me to start to debug.
