### ISSUE TITLE
[Bug]: Storybook 7 - controls missing when navigating from controls: disabled story

### ISSUE THREAD

**Issue by thomassimko** [storybookjs/storybook#21805]
### Describe the bug

When navigating from a story with controls: disabled to a story that has controls, the controls tab does not reappear.  If the user does a hard refresh of the page, the controls reappear.  This has been tested using CSF3 on Storybook 7.

```
export const Primary: Story = {
  args: {
    primary: true,
    label: 'Button',
  },
};

export const Secondary: Story = {
  args: {
    label: 'Button',
  },
  parameters: {
    controls: {
      disable: true,
    },
  },
};
```
Navigating from Primary to Secondary hides the controls (this is expected).
Navigating from Secondary to Primary does not re-show the controls panel (bug).

https://user-images.githubusercontent.com/11153023/228364808-c8a3fe5e-822a-4996-9b4c-703d28b9fe74.mov

### To Reproduce

Repo: https://github.com/thomassimko/storybook-control-reproduction
Chromatic: https://642351abc3a0198a09dec78d-yvodapsyev.chromatic.com/?path=/story/example-button--primary

### System

```shell
Environment Info:

  System:
    OS: macOS 13.2.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 16.16.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.11.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 111.0.5563.110
    Edge: 111.0.1661.54
    Firefox: 99.0.1
    Safari: 16.3
  npmPackages:
    @storybook/addon-essentials: ^7.0.0-rc.8 => 7.0.0-rc.8 
    @storybook/addon-interactions: ^7.0.0-rc.8 => 7.0.0-rc.8 
    @storybook/addon-links: ^7.0.0-rc.8 => 7.0.0-rc.8 
    @storybook/blocks: ^7.0.0-rc.8 => 7.0.0-rc.8 
    @storybook/react: ^7.0.0-rc.8 => 7.0.0-rc.8 
    @storybook/react-webpack5: ^7.0.0-rc.8 => 7.0.0-rc.8 
    @storybook/testing-library: ^0.0.14-next.1 => 0.0.14-next.1
```

**Comment by shilman** [comment]
Great Caesar's ghost!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.1.0-alpha.9 containing PR #21967 that references this issue. Upgrade today to the `@future` NPM tag to try it out!

```
npx sb@next upgrade --tag future
```

**Comment by shilman** [comment]
Son of a gun!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.8 containing PR #21967 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb@latest upgrade
```
