### ISSUE TITLE
[Bug]: Critical dependency: require function is used in a way in which dependencies cannot be statically extracted.

### ISSUE THREAD

**Issue by mhlozek** [storybookjs/storybook#21822]
### Describe the bug

I updated to latest Storybook 7-rc10 and get the same (or similar error as in #21316

![image](https://user-images.githubusercontent.com/2743172/228661907-727b94f6-73b1-4215-8470-37308958e3da.png)

I have tried to delete node modules and lock file and reinstall but withou success - error still persist.
Is this problem in my config or in Storybook itself?

### System

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
  Binaries:
    Node: 18.12.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1413.0), Chromium (111.0.1661.54)
  npmPackages:
    @storybook/addon-essentials: ^7.0.0-rc.10 => 7.0.0-rc.10
    @storybook/addon-links: ^7.0.0-rc.10 => 7.0.0-rc.10
    @storybook/blocks: ^7.0.0-rc.10 => 7.0.0-rc.10
    @storybook/html: ^7.0.0-rc.10 => 7.0.0-rc.10
    @storybook/html-webpack5: ^7.0.0-rc.10 => 7.0.0-rc.10
```

**Comment by shilman** [comment]
It looks like that issue was closed as fixed, but needs to be re-opened. Closing this as duplicate and re-opening that one to preserve the context. Thank you for getting this back on our radar!
