### ISSUE TITLE
[Bug]: ArgsTable "deprecated" jsdoc handling leading to unstyled description

### ISSUE THREAD

**Issue by probablyup** [storybookjs/storybook#21843]
### Describe the bug

For a story with a component that has a prop interface like this:

```ts
/**
 * @deprecated use `actions`
 *
 * Called when the user selects the special action dropdown item.
 *
 * Used in conjunction with `actionIcon` and `actionLabel` to
 * add a special option to the end of the dropdown outside the
 * main list.
 *
 * It is meant to be used in situations like adding
 * a new option to the data store that backs the option list.
 */
action?: () => void;
```

Renders like this:
<img width="1096" alt="Screenshot 2023-03-30 at 3 48 07 PM" src="https://user-images.githubusercontent.com/570070/228948153-134a5561-2002-4765-8cbc-1ff1a90746d5.png">

The `@deprecated` part forces the ArgsTable representation into a different rendering mode that doesn't run the description block through the typical mechanism that gives nicer styling.

Here's what it looks like if I remove `@deprecated`:
<img width="1107" alt="Screenshot 2023-03-30 at 3 49 43 PM" src="https://user-images.githubusercontent.com/570070/228948465-53094425-8fc6-4508-be66-560102be7a5b.png">

If it's possible to use the pretty path more often, that would be appreciated

### System

```shell
storybook v7 rc10
```

**Comment by JReinhold** [comment]
Thanks for the report, but this is actually an issue with how the tags in JSDocs are ordered.
The description always have to come before any tags like `@deprecated`, `@param`, etc.

Here's how it looks in Storybook if you move `@deprecated` down below the description:

![image](https://user-images.githubusercontent.com/5678122/229070330-b76b8343-7506-41e2-8596-3197a906de05.png)

While there's infamously no spec for JSDoc, I've confirmed this to be the case with the CLI from the "official" JSDoc site https://jsdoc.app/.

Here's a few examples that shows this behavior with the `jsdoc` cli. They'll show that the description will always be "swallowed" by the tag directly above it.

# 1. Description at the top (desired output)

```js
/**
 *
 * Called when the user selects the special action dropdown item.
 *
 * Used in conjunction with `actionIcon` and `actionLabel` to
 * add a special option to the end of the dropdown outside the
 * main list.
 *
 * It is meant to be used in situations like adding
 * a new option to the data store that backs the option list.
 * 
 * @deprecated use `actions`
 * @param {string} aParam - This is just a paramter
 */
```

![image](https://user-images.githubusercontent.com/5678122/229068919-4c45db7d-deee-442e-9d90-34751a59ec2f.png)


# 2. `@deprecated` before description

```js
/**
 * @deprecated use `actions`
 *
 * Called when the user selects the special action dropdown item.
 *
 * Used in conjunction with `actionIcon` and `actionLabel` to
 * add a special option to the end of the dropdown outside the
 * main list.
 *
 * It is meant to be used in situations like adding
 * a new option to the data store that backs the option list.
 *
 * @param {string} aParam - This is just a paramter
 */
```

![image](https://user-images.githubusercontent.com/5678122/229068798-978202e2-410b-45c7-8e7b-57c9f4ac2090.png)

# 3. `@param` before description

```js
/**
 * @param {string} aParam - This is just a paramter
 *
 * Called when the user selects the special action dropdown item.
 *
 * Used in conjunction with `actionIcon` and `actionLabel` to
 * add a special option to the end of the dropdown outside the
 * main list.
 *
 * It is meant to be used in situations like adding
 * a new option to the data store that backs the option list.
 *
 * @deprecated use `actions`
 */
```

![image](https://user-images.githubusercontent.com/5678122/229069131-7ed1af85-9e50-4b5b-93e7-caa2151e8de7.png)

# 4. Both tags before description, `@param` last

```js
/**
 * @deprecated use `actions`
 * @param {string} aParam - This is just a paramter
 *
 * Called when the user selects the special action dropdown item.
 *
 * Used in conjunction with `actionIcon` and `actionLabel` to
 * add a special option to the end of the dropdown outside the
 * main list.
 *
 * It is meant to be used in situations like adding
 * a new option to the data store that backs the option list.
 *
 */
```

![image](https://user-images.githubusercontent.com/5678122/229069337-dfcd666d-f7ed-44db-93c8-cb420b1b8dee.png)

# 5. Both tags before description, `@description` last

```js
/**
 * @param {string} aParam - This is just a paramter
 * @deprecated use `actions`
 *
 * Called when the user selects the special action dropdown item.
 *
 * Used in conjunction with `actionIcon` and `actionLabel` to
 * add a special option to the end of the dropdown outside the
 * main list.
 *
 * It is meant to be used in situations like adding
 * a new option to the data store that backs the option list.
 *
 */
```

![image](https://user-images.githubusercontent.com/5678122/229069442-3e071d32-7032-4ee6-9553-0f09e5835225.png)

**Comment by probablyup** [comment]
Interesting. Thanks for the tip, I did try rearranging the tag at one point and it didn’t update for me for some reason, but that could be a caching issue

**Comment by JReinhold** [comment]
Yeah unfortunately HMR doesn't support comments at the moment, so you might even need to restart the Storybook server to see the changes.
