### ISSUE TITLE
[Bug]: parameters.controls.sort no longer is working

### ISSUE THREAD

**Issue by probablyup** [storybookjs/storybook#21864]
### Describe the bug

I have a storybook with `argTypes` and `parameters` named exports in `preview.ts`:

```tsx
export const argTypes = {
  disableAnimation: {
    control: 'boolean',
    defaultValue: false,
    description:
      'Disables animation for all components in the story for testing purposes.',
  },
};

export const parameters = {
  controls: {
    sort: 'alpha',
  },
}
```

As of v7 (final, upgraded off RC) the alpha sort is no longer working:

<img width="1128" alt="Screenshot 2023-03-31 at 1 20 53 PM" src="https://user-images.githubusercontent.com/570070/229187759-d997a59a-ad31-4b78-a758-118623636fd7.png">

**Comment by probablyup** [comment]
This ended up being that the `Controls` component from `@storybook/blocks` doesn't inherit the global setting from `preview.ts`.

**Comment by IndProgo** [comment]
Try setting sort also in docs parameters
For some reason, parameters.controls (works in canvas/story page) and parameters.docs.controls (works in Docs page) have separate sort.  Other options, like, include or exclude works for both, when set only on parameters.controls
```js
export const parameters = {
  controls: {
    sort: 'alpha',
  },
  docs: {
    controls: {
      sort: 'alpha'
    }
  }
}
```
