### ISSUE TITLE
[Bug]: Security vulnerabilities in a few dependencies.

### ISSUE THREAD

**Issue by adityapant1286** [storybookjs/storybook#21867]
### Describe the bug

I am using Storybook version `6.5.16`. Git dependabot flagging _High_ alrets to some of the dependencies in Storybook. Can you please advise on the resolution?

I have executed `yarn audit` and attached the report in Json format (zip file).

![image](https://user-images.githubusercontent.com/13958935/229266415-bccbfe45-ac19-4642-b325-14644ffce6cf.png)

[audit.zip](https://github.com/storybookjs/storybook/files/11128477/audit.zip)

### To Reproduce

- Create a new or build a project with Storybook version `6.5.16`
- Execute `yarn audit`

**Comment by shilman** [comment]
Please try upgrading to 7.0, which fixes all outstanding security notifications.

Migration guide: https://storybook.js.org/migration-guides/7.0
