### ISSUE TITLE
[Documentation]: Typo in automigration link

### ISSUE THREAD

**Issue by EdricChan03** [storybookjs/storybook#21874]
### Describe the problem

There's an extra `#` symbol in one of the automigration links for Storybook v6 -> v7, which causes the referenced link to be broken:

https://github.com/storybookjs/storybook/blob/510f71e6e619c3a9e1adbda516ebb558785fc491/code/lib/cli/src/automigrate/fixes/new-frameworks.ts#L427

Suggested fix:

```diff
-https://github.com/storybookjs/storybook/blob/next/MIGRATION.md##new-framework-api
+https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#new-framework-api
```

### Additional context

This was encountered in the midst of updating an existing Storybook v6.5 project to v7 using the `pnpx storybook@next upgrade --prerelease` command

**Comment by jonniebigodes** [comment]
@EdricChan03, thanks for taking the time and effort into this opening up this issue and letting us know of that small but rather important issue in our CLI. I've just pushed a small pull request addressing it, and it should be merged shortly.

Hope you have a great day.

Stay safe

**Comment by shilman** [comment]
Gadzooks!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.1 containing PR #21875 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```
