### ISSUE TITLE
[Bug]: SB7 Angular for a component throws: Type XComponent is part of the declarations of 2 modules

### ISSUE THREAD

**Issue by rezoled** [storybookjs/storybook#21873]
### Describe the bug

When creating a simple story with the new recommended annotation for Angular (described here: https://github.com/storybookjs/storybook/blob/v7.0.0-rc.11/MIGRATION.md#angular-application-providers-and-modulewithproviders), angular throws the following error:
```
Type AvatarComponent is part of the declarations of 2 modules: AvatarModule and StorybookComponentModule! Please consider moving AvatarComponent to a higher module that imports AvatarModule and StorybookComponentModule. You can also create a new NgModule that exports and includes AvatarComponent then import that NgModule in AvatarModule and StorybookComponentModule.
```

### To Reproduce

Story:
```
export default {
	component: AvatarComponent,
	decorators: [
		applicationConfig({
			providers: [importProvidersFrom(AvatarModule)],
		}),
	],
} as Meta;
```

Module:
```
import { NgModule } from '@angular/core';
import { AvatarComponent } from './avatar.component';

@NgModule({
	declarations: [AvatarComponent],
	exports: [AvatarComponent],
})
export class AvatarModule {}
```

**Comment by rezoled** [comment]
@valentinpalkovic Opened a new issue as requested

**Comment by valentinpalkovic** [comment]
Can you provide a minimal reproduction?

**Comment by rezoled** [comment]
Here it is in my private account: https://github.com/roypeled/sb7-bug

**Comment by franknwankwo** [comment]
just installed Storybook 7 and I'm having the same issue.

**Comment by valentinpalkovic** [comment]
Hey @rezoled,

Thank you for the reproduction. I think your usecase does not make much sense, because there are no providers, which can be extracted from `AvatarModule`, therefore importing it in combination with `importProvidersFrom` helper function does not make much sense. Can you give me a more realistic example?

**Comment by valentinpalkovic** [comment]
@DanK1368 Can you describe your exact use case? Maybe you can share your stories file and the component and module you try to set up for the story.

**Comment by valentinpalkovic** [comment]
@franknwankwo Can you share the contents of StorybookTranslateModule and could you also share your whole Story content?

**Comment by rezoled** [comment]
> Hey @rezoled,
> 
> Thank you for the reproduction. I think your usecase does not make much sense, because there are no providers, which can be extracted from `AvatarModule`, therefore importing it in combination with `importProvidersFrom` helper function does not make much sense. Can you give me a more realistic example?

I  wanted to create the simplest use case, would adding providers solve the problem? This error still happens which much more complicated modules.

**Comment by valentinpalkovic** [comment]
@rezoled If `AvatarModule` is not a pure service that contains providers, but actually deals as a packager to package all necessary components/directives into a single unit and your angular component depends on it, it would be still necessary to add it to the `imports` section of `moduleMetadata`. The `importProvidersFrom` helper function only extracts providers and does not register components/pipes/directives.

**Comment by rezoled** [comment]
Ahhh I see.
Your suggestion works, it makes sense.

Maybe add in the documentation a specific page the explains what applicationConfig does and its usage with root modules (such as router and animation)?
