### ISSUE TITLE
[Bug]: vue-router on build-storybook has a runtime error

### ISSUE THREAD

**Issue by trajano** [storybookjs/storybook#21880]
### Describe the bug

Only on the build-storybook version, but not on the normal storybook.

I get the following error 
> can't access lexical declaration 're' before initialization

I presume it's using the production version of the vue-router as it is minified

### System

```shell
fails with 

  stdout: '',
  stderr: "'wmic' is not recognized as an internal or external command,\r\n" +
    'operable program or batch file.\r\n',
  failed: true,
  signal: null,
  cmd: 'wmic os get Caption',
  timedOut: false
```
```


### Additional context

_No response_

**Comment by shilman** [comment]
Do you a have a reproduction repo you can share? If not, can you create one? See [how to create a repro](https://storybook.js.org/docs/react/contribute/how-to-reproduce). Thank you! 🙏
