### ISSUE TITLE
[Bug]: The docs page does not update correctly when changing controls

### ISSUE THREAD

**Issue by techmind-git** [storybookjs/storybook#21894]
### Describe the bug

The (auto)docs-page is not updating when changing the value of a prop (like toggle false/true state for a component). The main component on docs-page will update, but in the stories overview part all components disappear. On the individual story-pages the components work fine.

### To Reproduce

I was able to reproduce on someone else's storybook: https://geromegrignon.github.io/angular-material-storybook/?path=/docs/usecases-progress-indicators--docs Components disappear when for example changing the color property from primary to accent.
It was confirmed to be reproducable on discord (see "Additional context")

### System

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700H
  Binaries:
    Node: 18.13.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.4.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1413.0), Chromium (111.0.1661.62)
  npmPackages:
    @storybook/addon-essentials: ^7.0.2 => 7.0.2 
    @storybook/addon-interactions: ^7.0.2 => 7.0.2 
    @storybook/addon-links: ^7.0.2 => 7.0.2 
    @storybook/angular: ^7.0.2 => 7.0.2 
    @storybook/blocks: ^7.0.2 => 7.0.2 
    @storybook/testing-library: ^0.1.0 => 0.1.0
```

### Additional context

It was confirmed on discord to be a bug: https://discord.com/channels/486522875931656193/490770949910691862/1086798445563629720 but I haven't been able to get an update and don't know if there is already an issue submitted. I could only check that it was not solved in the latest release

**Comment by shilman** [comment]
Huzzah!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.1.0-alpha.0 containing PR #21944 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```

**Comment by shilman** [comment]
Huzzah!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.3 containing PR #21944 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```
