### ISSUE TITLE
[Bug]: Documentation is not generated when using `React.FC` in TypeScript

### ISSUE THREAD

**Issue by kyletsang** [storybookjs/storybook#21898]
### Describe the bug

When using `React.FC` to specify the component type, the documentation will not be generated.

Here is minimal repro of a component:
```
export interface AppProps {
  /**
   * A string paramter.
   */
  param1: string

  /**
   * A number parameter.
   */
  param2: number
}

/**
 * This is a component.
 */
const App: React.FC<AppProps> = ({ param1, param2 }) => {
  return (
    <div>
      <div>Param 1: {param1}</div>
      <div>Param 2: {param2}</div>
    </div>
  )
}

export default App
```

If I use the above snippet and substitute the declaration using the following, it works properly
```
const App = ({ param1, param2 }: AppProps) => {
```

This used to work in the earlier betas (Beta 33 I think?), but stopped working at some point after that.  When I get a chance, I'll try to find the earliest version in which this started occurring.

### To Reproduce

https://github.com/kyletsang/storybook-ts-docs-repro

### System

```shell
Environment Info:

  System:
    OS: macOS 13.2.1
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 8.19.4
  Browsers:
    Chrome: 111.0.5563.146
    Edge: 111.0.1661.62
    Firefox: 109.0.1
    Safari: 16.3
```

**Comment by nuxcodes** [comment]
#21801

**Comment by nuxcodes** [comment]
Similar to #21801. `React.forwardRef` also breaks ArgTypes type inference.

The type inference works once I remove `React.FC`, and the control becomes radio buttons for union types. But if I use `cva`, the control remains text controls for union types.

<img width="846" alt="image" src="https://user-images.githubusercontent.com/44252050/229693694-4a5c7b8b-31e0-4a7a-8d95-78bc2af56c74.png">

**Comment by kasperpeulen** [comment]
Somehow using a named export fixes this issue.
Even though that the component is still imported as a default export...
cc @shilman 

<img width="590" alt="image" src="https://user-images.githubusercontent.com/1035299/231090313-b544ecb9-c94f-4369-8e08-293fe534aeb2.png">

**Comment by shilman** [comment]
Jeepers creepers!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.1.0-alpha.1 containing PR #22024 that references this issue. Upgrade today to the `@future` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```
