### ISSUE TITLE
[Bug]: 7.0.0-rc.9 Decorators are broken in custom render components

### ISSUE THREAD

**Issue by IanVS** [storybookjs/storybook#21900]
### Describe the bug

I started to get an error indicating that my react-router decorator was no longer working when I upgraded from rc.5 to 7.0.2.  I narrowed it down to starting in rc.9, and have reproduced the issue in a stackblitz, linked below.  It seems like decorators are no longer used in some situations, depending on whether arguments are provided to a custom render function.

### To Reproduce

https://stackblitz.com/edit/github-ytdmum?file=src%2Fstories%2FPage.stories.tsx&preset=node

### System

```shell
System:
    OS: macOS 13.2.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 18.12.1 - ~/Library/Caches/fnm_multishells/20832_1680559884027/bin/node
    Yarn: 1.22.19 - ~/Library/Caches/fnm_multishells/20832_1680559884027/bin/yarn
    npm: 9.6.3 - ~/Library/Caches/fnm_multishells/20832_1680559884027/bin/npm
  Browsers:
    Firefox: 111.0.1
    Safari: 16.3
  npmPackages:
    @storybook/addon-a11y: 7.0.0-rc.9 => 7.0.0-rc.9
    @storybook/addon-actions: 7.0.0-rc.9 => 7.0.0-rc.9
    @storybook/addon-docs: 7.0.0-rc.9 => 7.0.0-rc.9
    @storybook/addon-essentials: 7.0.0-rc.9 => 7.0.0-rc.9
    @storybook/addon-interactions: 7.0.0-rc.9 => 7.0.0-rc.9
    @storybook/addon-links: 7.0.0-rc.9 => 7.0.0-rc.9
    @storybook/addon-mdx-gfm: ^7.0.0-rc.9 => 7.0.2
    @storybook/addons: 7.0.0-rc.9 => 7.0.0-rc.9
    @storybook/expect: ^27.5.2-0 => 27.5.2-0
    @storybook/jest: 0.0.11-next.0 => 0.0.11-next.0
    @storybook/react: 7.0.0-rc.9 => 7.0.0-rc.9
    @storybook/react-vite: 7.0.0-rc.9 => 7.0.0-rc.9
    @storybook/test-runner: 0.10.0 => 0.10.0
    @storybook/testing-library: 0.0.14-next.1 => 0.0.14-next.1
    @storybook/testing-react: 2.0.0-next.0 => 2.0.0-next.0
```

**Comment by shilman** [comment]
This was an intentional breaking change: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#parametersdocssourceexcludedecorators-defaults-to-true

Can you try setting `docs.source.excludeDecorators` to `false` globally in `.storybook/preview.js` or for the stores that are breaking?

**Comment by IanVS** [comment]
@shilman you're right, if I change that parameter it starts to work again.  I've updated my reproduction to show it both ways.

**Comment by shilman** [comment]
Yee-haw!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.1.0-alpha.0 containing PR #21902 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```

**Comment by StraightOuttaCrompton** [comment]
Seems to be related to the MR. The `parameters.docs.source.excludeDecorators defaults to true` link in https://github.com/storybookjs/storybook/blob/next/MIGRATION.md is dead.

**Comment by shilman** [comment]
Good catch @IanVS -- fixed

**Comment by shilman** [comment]
Son of a gun!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.3 containing PR #21902 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```
