### ISSUE TITLE
[CI]: Failures in scheduled GitHub workflows don't notify anyone

### ISSUE THREAD

**Issue by JReinhold** [storybookjs/storybook#21910]
When the following workflows fail, no one is notified automatically:

- [Markdown Links Check](https://github.com/storybookjs/storybook/blob/next/.github/workflows/cron-weekly.yml)
- [Generate and push sandboxes (main)](https://github.com/storybookjs/storybook/blob/next/.github/workflows/generate-sandboxes-main.yml)
- [Generate and push sandboxes (next)](https://github.com/storybookjs/storybook/blob/next/.github/workflows/generate-sandboxes-next.yml)

This means that failures can go unnoticed. My proposal would be to add a failure case to the workflows that sends a message to the #monitoring channel on Discord.

We could probably create a [composite action](https://docs.github.com/en/actions/creating-actions/creating-a-composite-action) to use everywhere.

**Comment by shilman** [comment]
@ndelangen @yannbf didn't we add failure notifications to the generate & push sandboxes ? If so, can we close this?
