### ISSUE TITLE
[Bug]: Unable to find Storybook story files using specified pattern in a monorepo managed with Turbo and PNPM

### ISSUE THREAD

**Issue by douglaszaltron** [storybookjs/storybook#21924]
### Describe the bug

I am facing an issue where Storybook is unable to locate the story files in my monorepo, which is being managed by Turbo and PNPM. The Storybook is installed in one of the apps within this monorepo. Whenever I run the Storybook, I receive a warning message stating 

> "No story files found for the specified pattern: stories/**/*.stories.@(js|jsx|ts|tsx)." 

### To Reproduce

**Steps Taken:**
I have ensured that the Storybook configuration file has been correctly set up, and the specified pattern for story files matches the actual file path. I have also checked the file permissions for the story files, and they seem to be set up correctly. I have tried to run the Storybook with different patterns for story files, but the issue persists.

**Expected Outcome:**
I expect Storybook to locate and display the story files for the specified pattern successfully.

**Current Outcome:**
Storybook is unable to locate the story files, and I receive a warning message every time I run it.

### System

```shell
Environment Info:

  System:
    OS: Linux 5.14 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
  Browsers:
    Chrome: 110.0.5481.77
```

### Additional context

- Monorepo is managed using Turbo and PNPM.
- Storybook is installed in one of the apps in the monorepo.
- Storybook configuration file is correctly set up.
- File permissions for story files seem to be set up correctly.
- I have tried different patterns for story files, but the issue persists.

![image](https://user-images.githubusercontent.com/4502670/229874228-e4555a68-b356-480d-9d00-77ded0ce97d4.png)
![image](https://user-images.githubusercontent.com/4502670/229874399-3d521b07-150e-41b5-a3bd-84e8dee96b64.png)

**Comment by douglaszaltron** [comment]
But if I open the .stories.tsx file in the editor and save it, the example will be displayed in the interface. 🤔

**Comment by shilman** [comment]
Do you a have a reproduction repo you can share? If not, can you create one? See [how to create a repro](https://storybook.js.org/docs/react/contribute/how-to-reproduce). Thank you! 🙏

**Comment by douglaszaltron** [comment]
@shilman I was able to identify the problem. Actually, it was not a bug with Storybook, but rather an issue with my local directory where the project was stored. I decided to recreate it and it worked properly. Thank you for the prompt response.

**Comment by Risk-taker0501** [comment]
Hi, @douglaszaltron . I met the same issue like you.
Can you explain how to fix them?

**Comment by MehakBaig** [comment]
Hi, I have the same issue! Could we please get some solutions on this ?

**Comment by yrsluv** [comment]
+1

**Comment by alyanoyigor** [comment]
Same error in my monorepo project after upgrading storybook from v5 to v7. Found temp solution `features: { storyStoreV7: false }`

**Comment by stephencroberts** [comment]
This has been a problem for me as well. I started a fresh project with the latest Storybook and had the issue. @alyanoyigor 's fix worked for me!

**Comment by awesome1115** [comment]
I wanna your help.

WARN No story files found for the specified pattern: src\**\*.mdx
WARN No story files found for the specified pattern: src\**\*.stories.@(js|jsx|mjs|ts|tsx)

**Comment by valentinpalkovic** [comment]
Without a reproduction we are not able to help out. We are still waiting for one. Visit https://storybook.new to create one based on some preselected templates.

**Comment by Noldor99** [comment]
@FoXTiSiTY 
> У меня была та же проблема: оказалось, что в родительской папке есть символы ( ), и похоже, что сборка Storybook ей не понравилась.

Your answer turned out to be a solution for me 🙂

**Comment by misiyevich** [comment]
same issue
