### ISSUE TITLE
[Bug]: 7.0.2 - ColorPalette results in Cannot read properties of undefined (reading 'fonts') 

### ISSUE THREAD

**Issue by homerchen19** [storybookjs/storybook#21934]
### Describe the bug

I'm currently using Storybook 7 with Vite, but I'm encountering the following error when I use `ColorPalette`: `Cannot read properties of undefined (reading 'fonts')`. Using `ColorPalette` in `tsx` file was working fine in v6.5, so I wonder is there anything changed I missed.

![Screenshot 2023-04-05 at 11 15 37](https://user-images.githubusercontent.com/12113222/229972420-4ec32e81-7769-4796-b5cf-d37de2f2a9d8.png)

Code snippet
```tsx
import { ColorItem, ColorPalette } from "@storybook/blocks";

const theme = {
  colors: {
    primaryDark: {
      value: "#1C1C1C",
    },
    primaryRegular: {
      value: "#363636",
    },
    primaryLight1: {
      value: "#4D4D4D",
    },
    primaryLight2: {
      value: "#878787",
    },
    primaryLight3: {
      value: "#D1D1D1",
    },
    primaryLight4: {
      value: "#EDEDED",
    },
  },
};

export default {
  title: "Theme",
};

export const Colors = () => {
  return (
    <ColorPalette>
      {Object.entries(theme.colors).map(([key, { value }]) => (
        <ColorItem
          colors={{
            [key]: value,
          }}
          key={key}
          subtitle={`theme.colors.${key}`}
          title={key}
        />
      ))}
    </ColorPalette>
  );
};
```

### To Reproduce

Codesandbox: https://codesandbox.io/p/sandbox/storybook7-vite-4xhjpq

### System

```shell
System:
    OS: Linux 5.15 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (2) x64 AMD EPYC
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.15.0 - /usr/local/bin/npm
  npmPackages:
    @storybook/addon-essentials: 7.0.2 => 7.0.2 
    @storybook/addons: 7.0.2 => 7.0.2 
    @storybook/blocks: 7.0.2 => 7.0.2 
    @storybook/builder-vite: 7.0.2 => 7.0.2 
    @storybook/react: 7.0.2 => 7.0.2 
    @storybook/react-vite: 7.0.2 => 7.0.2 
```

**Comment by shilman** [comment]
Doc blocks are only for use in docs, not for use in stories.

@jonniebigodes @JReinhold i was looking for documentation about this in the official docs, but could not find one. Can  you please add this so we can link to it the next time this comes up? (This is probably the 10th issue I've seen about this).

**Comment by homerchen19** [comment]
Understood! Thanks for the quick reply. It will be very helpful if this can be noted in the document or the migration guide. Thank you!

**Comment by jonniebigodes** [comment]
Sure, I'll take care of it @shilman

**Comment by StraightOuttaCrompton** [comment]
I've hit this same issue whilst migrating the Proton storybook to v7, and like you say it only works in docs and not stories.

However, this has led me to an issue where the decorators used to theme our [color stories](https://design-system.protontech.ch/?path=/docs/core-concepts-colors--base-prominent&globals=theme:Monokai) are no longer applied to the color docs. You can find the decorators we apply [here](https://github.com/ProtonMail/WebClients/blob/main/applications/storybook/.storybook/preview.js#L45).

My question: Is there a way to apply the decorators to docs as well?
