### ISSUE TITLE
[Bug] Storybook doesn't work on windows machines with "storyStoreV7=false"

### ISSUE THREAD

**Issue by sateffen** [storybookjs/storybook#21948]
### What version of `vite` are you using?

4.2.1

### System info and storybook versions

OS: Windows 10
Node: 18.15.0
Yarn: 1.22.19
Vite: 4.2.1
Storybook: 7.0.2

### Describe the Bug

**Description**

Using storybook with vite on windows and setting "storyStoreV7" lets storybook generate an invalid path for vite, leading to this error message:

```
[vite] Internal server error: Failed to resolve import "C:[redacted]vite-react-storybook
eact" from "..\..\..\..\..\..\virtual:\@storybook\builder-vite\vite-app.js". Does the file exist?
  Plugin: vite:import-analysis
  File: /virtual:/@storybook/builder-vite/vite-app.js:3:32
  1  |  // Ensure that the client API is initialized by the framework before any other iframe code
  2  |      // is loaded. That way our client-apis can assume the existence of the API+store
  3  |      import { configure } from 'C:\[redacted]\vite-react-storybook\node_modules\@storybook\react';
     |                                 ^
  4  |
  5  |      const { logger } = __STORYBOOK_MODULE_CLIENT_LOGGER__;
```
(the redacted parts are private paths on my computer).

The basic issue is, that the import path is written using single backslashes, which are only for escaping parts of paths. The path has to either contain double backslashes or normal slashes.

The bug occurs in this line: https://github.com/storybookjs/builder-vite/blob/main/packages/builder-vite/codegen-iframe-script.ts#L23 . A quick test with `.replaceAll('\\', '/')` fixed the issue locally.

**Steps to reproduce**

On a windows system, open a terminal and:

```sh
yarn create vite vite-react-storybook --template react
cd vite-react-storybook
yarn init -y
yarn add -D storybook
npx storybook init
```

Now you can edit the `.storybook/main.js` file and add the following config:

```
  features: {
    storyStoreV7: false,
  },
```

and run `yarn run storybook`.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by elephantcatdog** [comment]
I have this issue also.

**Comment by morcosan** [comment]
I am also waiting for a fix on this issue in order to migrate to Storybook 7 😀

**Comment by ovidiusf** [comment]
any news on this? I have the exact same issue and linux / WSL is not really a choice for us.

**Comment by roshanind** [comment]
I'm also having the same issue. appreciate if some one can respond with a workaround.

**Comment by valentinpalkovic** [comment]
Thank you for reaching out! I wanted to let you know that in Storybook 8.0.0, we are transitioning away from storyStoreV6 as part of our ongoing improvements, which you can read more about in our [migration guide](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#storystorev6-and-storiesof-is-deprecated). We encourage you to switch to storyStoreV7 to take advantage of the latest features and updates. While we understand this change might require some adjustments, please know that this decision is made to enhance the overall experience. As we are now focusing our resources on supporting storyStoreV7, I'll be closing this issue, but we're here to assist if you have any questions or need guidance during your migration process. Thanks for your understanding and support!
