### ISSUE TITLE
[Bug]: Error: Could not find HttpClient provider for use with Angular Material icons.

### ISSUE THREAD

**Issue by Oussamawadih** [storybookjs/storybook#21942]
### Describe the bug

error in storybook 7.0.1 & 7.0.2 : Error: Could not find HttpClient provider for use with Angular Material icons. Please include the HttpClientModule from @angular/common/http in your app imports.

![Capture](https://user-images.githubusercontent.com/24549969/230029716-83c1585e-7cfb-484a-b4b9-2f33cad55461.PNG)

**Comment by shilman** [comment]
Do you a have a reproduction repo you can share? If not, can you create one? See [how to create a repro](https://storybook.js.org/docs/react/contribute/how-to-reproduce). Thank you! 🙏

**Comment by chialinglu21** [comment]
I also face this problem after I migrated to Storybook 7. I created a reproduction repo [here](https://github.com/chialinglu21/iconIssueSample). 

There is an icon story that I try to register an icon-sprite.svg to mat-icon, and I got the error below even I already imported HttpClientModule in meta.
<img width="1330" alt="image" src="https://user-images.githubusercontent.com/24379998/231668635-043f43fa-6fcc-4124-ae10-bddfcd27337a.png">


```typescript
// Icon.stories.ts
const meta: Meta<IconComponent> = {
  title: "Icon Sample",
  component: IconComponent,
  decorators: [
    moduleMetadata({
      imports: [HttpClientModule, IconRegistryModule],
    }),
  ],
};
```


### System Environment
![image](https://user-images.githubusercontent.com/24379998/231667077-093784aa-4943-4e6b-9fa5-d5a5b24ac4e6.png)

**Comment by Ulse81** [comment]
I'm facing the same issue: After migrating to Storybook 7.0.6 the `mat-icons` are missing because `HttpClientModule` couldn't be found.

Dependencies:
- Angular 15.2.7 
- rxjs 7.8.0
- nx 15.9.2
- typescript 4.9.5

**Comment by Ulse81** [comment]
After some time of research, I found a solution for my problem: I added `applicationConfig` to my `preview.js` with following code:
```js
const decorators = [
  ...,
  applicationConfig({
    providers: [importProvidersFrom(HttpClientModule)]
  })
];
const preview = {
  parameters: ...,
  decorators: decorators
};
export default preview;
```
And removed the imports in each story. This was documented here:  
https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#angular-application-providers-and-modulewithproviders

**Comment by valentinpalkovic** [comment]
Indeed, you have to use the applicationConfig decorator to configure application-wide providers.
