### ISSUE TITLE
[Bug]:  Adding a decorator breaks Show Code view

### ISSUE THREAD

**Issue by grish92** [storybookjs/storybook#21964]
### Describe the bug

When adding  decorator withHeadless in the Preview file, the Show Code view in the Docs View is breaking.
Showcode with withHeadless decorator
![Screenshot from 2023-04-06 12-54-52](https://user-images.githubusercontent.com/73484843/230327448-9dfe19a5-0b3d-45ab-b6fe-0c179238ed5c.png)

Showcode without withHeadless decorator
![Screenshot from 2023-04-06 12-58-21](https://user-images.githubusercontent.com/73484843/230328058-2a1e22c7-e447-4a6f-820b-4af95b1cfe0c.png)

### To Reproduce

npm packages:
  "@storybook/addon-docs": "^6.5.16",
    "@storybook/addon-essentials": "6.5.16",
    "@storybook/addon-interactions": "6.5.16",
    "@storybook/addon-links": "6.5.16",
    "@storybook/addon-postcss": "2.0.0",
    "@storybook/builder-webpack5": "6.5.16",
    "@storybook/manager-webpack5": "6.5.16",
    "@storybook/react": "6.5.16",

**Comment by shilman** [comment]
Please try upgrading to 7.0 https://storybook.js.org/migration-guides/7.0 and track #21649 which should be fixed in the next release or so. Closing this for now.
