### ISSUE TITLE
[Bug]: Markdown import of README.md file not working

### ISSUE THREAD

**Issue by Chrisdo82** [storybookjs/storybook#21961]
### Describe the bug

I cannot import the `README.md` into an `mdx` file. However, it works with any other markdown file. Even if I rename the `README.md`, then strangely it works with this one. So the problem seems to be the file name, but it is not an option for me to rename the README. 

Is there another way or am I doing something wrong?

```
import { Meta, Markdown } from "@storybook/blocks"
import ReadMe from "../README.md?raw"

<Meta title="Intro" />

<Markdown>{ReadMe}</Markdown>
```

### System

```shell
System:
    OS: macOS 13.3
    CPU: (8) arm64 Apple M1 Pro
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
  Browsers:
    Chrome: 111.0.5563.146
    Firefox: 111.0.1
    Safari: 16.4
  npmPackages:
    @storybook/addon-a11y: 7.0.2 => 7.0.2 
    @storybook/addon-essentials: 7.0.2 => 7.0.2 
    @storybook/addon-jest: ^7.0.2 => 7.0.2 
    @storybook/addon-links: 7.0.2 => 7.0.2 
    @storybook/addon-mdx-gfm: 7.0.2 => 7.0.2 
    @storybook/addon-storysource: 7.0.2 => 7.0.2 
    @storybook/blocks: 7.0.2 => 7.0.2 
    @storybook/react: 7.0.2 => 7.0.2 
    @storybook/react-vite: 7.0.2 => 7.0.2
```

**Comment by shilman** [comment]
Do you a have a reproduction repo you can share? If not, can you create one? Go to https://storybook.new or see [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce). Thank you! 🙏

**Comment by Chrisdo82** [comment]
Sorry for the late reply. I wasn't able to reproduce it with https://storybook.new/ but I still get this error on my project. Is there anything I can do?

**Comment by JReinhold** [comment]
That's unfortunate. Can you take your original project then, and strip everything out while still maintaining the error? make it as small as possible, and obviously also removing any sensitive/closed source information, and then share it in a repository.

**Comment by JReinhold** [comment]
That is a slightly different issue @maxkarkowski. The syntax for importing plain markdown in docs has changed in v7, due to the differences between MD and MDX2.

This is described in the migration notes here: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#importing-plain-markdown-files-with-transcludemarkdown-has-changed

And in the docs here: https://storybook.js.org/docs/vue/api/doc-block-markdown

So you need to change your MDX to this instead:

```
import { Meta, Markdown } from '@storybook/addon-docs';
import Changelog from './test.md?raw';

<Meta title="Changelog" />

<Markdown>{Changelog}</Markdown>
```

See this fork of your reproduction: https://stackblitz.com/edit/github-fr2xv3-rr5ebg?file=src/stories/Introduction.mdx

**Comment by abudd1094** [comment]
This issue is still present.  I found that when adding directories to the `staticDirs` array within the Storybook `main.js` file, the second a folder with a file called `README.md` is added, the ability to import the `README.md` is broken.

**Comment by JReinhold** [comment]
@abudd1094 please open a new issue with a reproduction repository, for us to be able to look into it.

https://storybook.js.org/docs/contribute/how-to-reproduce
