### ISSUE TITLE
[Bug]: incorrect check for peer dependencies in JsPackageManager.writePackageJson

### ISSUE THREAD

**Issue by geertjansen** [storybookjs/storybook#21982]
### Describe the bug

I think this line is incorrect:
https://github.com/storybookjs/storybook/blob/602854121d0abc095c414f5aaaa07991f0c9d140/code/lib/cli/src/js-package-manager/JsPackageManager.ts#L117

and should be changed like this

```diff
  if (
-   packageJsonToWrite.dependencies &&
+   packageJsonToWrite.peerDependencies &&
    Object.keys(packageJsonToWrite.peerDependencies).length === 0
  ) {
    delete packageJsonToWrite.peerDependencies;
  }
```

**Comment by shilman** [comment]
Thanks @geertjansen ! #22006
