### ISSUE TITLE
[Documentation]: StorybookConfig not exported from @storybook/react

### ISSUE THREAD

**Issue by dtrenz** [storybookjs/storybook#21981]
### Describe the problem

[The migration documentation for ESM in main.js ](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#esm-format-in-mainjs)say that configs can be typed in a `main.ts` file using a `StorybookConfig` type exported from the framework module (e.g. `@storybook/react`).  However, it does not appear that `StorybookConfig` is an exported type from the `@storybook/react` module.

> `Module '"@storybook/react"' has no exported member 'StorybookConfig'`

```ts
// main.ts
import { StorybookConfig } from "@storybook/react";

const config: StorybookConfig = {};

export default config;
```

**Comment by ihmpavel** [comment]
The export is available in `@storybook/react-vite` package instead of `@storybook/react`.

This change has to be made

```diff
- import { StorybookConfig } from "@storybook/react";
+ import { StorybookConfig } from "@storybook/react-vite";
```

**Comment by shilman** [comment]
@ihmpavel is right. This is a documentation bug. it should either be imported from the framework package that you're using (e.g. `@storybook/react-vite`, `@storybook/react-webpack5`, `@storybook/nextjs`, etc.)

**Comment by jonniebigodes** [comment]
Closing this for now, as the documentation features the proper import from the renderer, and upon a search, it seems that the only item was that one. Other similar references no longer exist in the documentation or were transformed into agnostic snippets.


Thanks for bringing this to our attention nonetheless. We appreciate it 🙏 

If you encounter any other places, please feel free to ping me and I'll gladly re-open this and apply the required changes.

Hope you have a great day.

Stay safe

**Comment by machiapply** [comment]
Hi, I just started getting an error on our CI for 
`error The requested module '@storybook/react-native' does not provide an export named 'StorybookConfig'.`

we're using `@storybook/react-native` as framework, so
```
import { StorybookConfig } from "@storybook/react-native";

```
must be correct, right? I see on my local build, it exists for v8.4.3, and CI seems to be installing the same version. I am not sure what could make it error..?

**Comment by phunanon** [comment]
We've had the same issue upgrading Node from 23.4.0 to 23.9.0, using @storybook/react-webpack5@^8.2.9

**Comment by gabrielumatch** [comment]
For me it doesn't work on node version  24 ... but it's working fine on 20

**Comment by cam-shaw** [comment]
> We've had the same issue upgrading Node from 23.4.0 to 23.9.0, using @storybook/react-webpack5@^8.2.9

Legend. I've nailed it down to node 23.6.0 being the start of the problem. 
From my testing - 23.4.0/23.5.0 are fine, 23.6.0/23.7.0/23.11.1 all have the issue.

**Comment by cam-shaw** [comment]
For anyone reading this now - I don't see this issue on node 24.6.0.
