### ISSUE TITLE
[Bug]: pnpm dlx storybook init fails on a new project

### ISSUE THREAD

**Issue by newtriks** [storybookjs/storybook#21980]
### Describe the bug

```
attention => Storybook now collects completely anonymous telemetry regarding usage.
This information is used to shape Storybook's roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://storybook.js.org/telemetry

 ERROR  Command failed with exit code 1: storybook init

pnpm: Command failed with exit code 1: storybook init
    at makeError (/Users/simon.bailey/.cache/node/corepack/pnpm/8.1.1/dist/pnpm.cjs:24235:17)
```

### To Reproduce

`pnpm dlx storybook init`

### System

```shell
Environment Info:

  System:
    OS: macOS 13.2.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.13.2/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v18.13.0/bin/npm
  Browsers:
    Chrome: 111.0.5563.146
    Safari: 16.3
  npmPackages:
    @storybook/addon-essentials: ^7.0.2 => 7.0.2 
    @storybook/addon-interactions: ^7.0.2 => 7.0.2 
    @storybook/addon-links: ^7.0.2 => 7.0.2 
    @storybook/blocks: ^7.0.2 => 7.0.2 
    @storybook/react: ^7.0.2 => 7.0.2 
    @storybook/react-vite: ^7.0.2 => 7.0.2 
    @storybook/testing-library: ^0.0.14-next.2 => 0.0.14-next.2 
```
```


### Additional context

* Also tried `pnpm dlx storybook init -f` - error
* Generates `package-lock.json` as opposed to `pnpm-lock` which I'd expect as this is `pnpm` installation.
* Tries to install a beta version of vite?
WARN  Issues with peer dependencies found
.
└─┬ @storybook/react-vite 7.0.2
  └─┬ @vitejs/plugin-react 3.1.0
    └── ✕ unmet peer vite@^4.1.0-beta.0: found 3.1.0
* If I then try to change it I get:
WARN  Issues with peer dependencies found
.
└─┬ @vitejs/plugin-react 2.0.0
  └── ✕ unmet peer vite@^3.0.0: found 4.1.0-beta.0
```

**Comment by IanVS** [comment]
What version of `vite` and `@vitejs/plugin-react` do you have installed in your project?

**Comment by newtriks** [comment]
`"@vitejs/plugin-react": "^2.0.0"`
`"vite": "^3.1.0"`

```
WARN  Issues with peer dependencies found
.
└─┬ @storybook/react-vite 7.0.2
  └─┬ @vitejs/plugin-react 3.1.0
    └── ✕ unmet peer vite@^4.1.0-beta.0: found 3.1.0
```
If I then try to change it I get:
```
WARN  Issues with peer dependencies found
.
└─┬ @vitejs/plugin-react 2.0.0
  └── ✕ unmet peer vite@^3.0.0: found 4.1.0-beta.0

**Comment by IanVS** [comment]
Storybook installs `@vitejs/plugin-react@^3.0.1` as a backup in case someone does not have a vite config.  However, they released 3.1.0 with a peer-dep on vite of `^4.1.0-beta.0`.  That is where the warning is coming from, since your version of vite is too old to support that one.  

Now that it looks like you've updated vite and the plugin, I would try using `pnpm dlx storybook@latest init`.  If it's anything like npm, using it without a tag can pull in a cached, older version of the storybook cli.

**Comment by newtriks** [comment]
Nope, same issue sadly. Here's a demo repos with the `release` branch being configured to try and run `https://github.com/newtriks/storybook-for-vite/tree/release`.

**Comment by shilman** [comment]
Just to be safe can you try `pnpm dlx storybook@latest init` if you haven't already?

**Comment by IanVS** [comment]
I pulled down your repo, checked out `main`, removed the existing storybook files and `.pnpmfile.cjs` file, and ran `pnpm dlx storybook@latest init` and it worked correctly.  I also upgraded pnpm from 7 to 8, tried again, and it installed fine then too.  

Maybe you have a corrupted local pnpm store?  I've seen that happen before and it can cause problems.

**Comment by newtriks** [comment]
That did it, pnpm seems to be a royal pita in this instance, thanks @IanVS

**Comment by IanVS** [comment]
You could try this: https://github.com/orgs/pnpm/discussions/4413#discussioncomment-2304751

**Comment by newtriks** [comment]
@IanVS on trying to upgrade another project I'm hitting the exact same issue but nothing I tried before is working. I also tried:

* `pnpm store status` 
* `pnpm install --force`
* `pnpm store prune`

Running ` pnpm dlx storybook@latest init`, any other ideas?

**Comment by IanVS** [comment]
You could try this: [github.com/orgs/pnpm/discussions/4413#discussioncomment-2304751](https://github.com/orgs/pnpm/discussions/4413#discussioncomment-2304751)

**Comment by IanVS** [comment]
Going to close since it seems this is an issue with pnpm.  Let me know if you think there's a bug in Storybook.
