### ISSUE TITLE
[Bug]: Composition errors out with CORS error

### ISSUE THREAD

**Issue by jmucsi** [storybookjs/storybook#21995]
### Describe the bug

I am adding a Storybook instance to main.js like so:

const config = {
  refs: {
    'xyz': {
      title: 'xyz Design System',
      url: '//xyz-design-system.xyz.com/',
      expanded: false, // Optional, true by default
    },
  },

### To Reproduce

Start Storybook with `npm run storybook`. Observe CORS error for stories.json in network tab.

<img width="1028" alt="cors error" src="https://user-images.githubusercontent.com/94075049/230657406-22713f0c-5a65-4d42-b603-074c08990c6c.png">

### System

```shell
Environment Info:

  System:
    OS: macOS 12.6.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 16.19.1 - ~/Library/pnpm/node
    npm: 8.19.3 - ~/Library/pnpm/npm
  Browsers:
    Chrome: 112.0.5615.49
    Safari: 16.4
  npmPackages:
    @storybook/addon-a11y: ^7.0.0 => 7.0.2
    @storybook/addon-actions: ^7.0.0 => 7.0.2
    @storybook/addon-essentials: ^7.0.0 => 7.0.2
    @storybook/addon-interactions: ^7.0.0 => 7.0.2
    @storybook/addon-links: ^7.0.0 => 7.0.2
    @storybook/addon-mdx-gfm: ^7.0.0 => 7.0.2
    @storybook/blocks: ^7.0.0 => 7.0.2
    @storybook/mdx1-csf: ^1.0.0 => 1.0.0
    @storybook/testing-library: ^0.0.14-next.2 => 0.0.14-next.2
    @storybook/vue3: ^7.0.0 => 7.0.2
    @storybook/vue3-vite: ^7.0.0 => 7.0.2
```

### Additional context

(anonymous) @ http://localhost:6006/sb-manager/chunk-Q4UME242.mjs:43
checkRef @ http://localhost:6006/sb-manager/chunk-Q4UME242.mjs:43
(anonymous) @ http://localhost:6006/sb-manager/chunk-Q4UME242.mjs:53
init7 @ http://localhost:6006/sb-manager/chunk-Q4UME242.mjs:53
(anonymous) @ http://localhost:6006/sb-manager/chunk-Q4UME242.mjs:53
ManagerProvider @ http://localhost:6006/sb-manager/chunk-Q4UME242.mjs:53
constructClassInstance @ http://localhost:6006/sb-manager/chunk-FGVEHHDQ.mjs:44
updateClassComponent @ http://localhost:6006/sb-manager/chunk-FGVEHHDQ.mjs:69
beginWork @ http://localhost:6006/sb-manager/chunk-FGVEHHDQ.mjs:71
beginWork$1 @ http://localhost:6006/sb-manager/chunk-FGVEHHDQ.mjs:90
performUnitOfWork @ http://localhost:6006/sb-manager/chunk-FGVEHHDQ.mjs:90
workLoopSync @ http://localhost:6006/sb-manager/chunk-FGVEHHDQ.mjs:90
performSyncWorkOnRoot @ http://localhost:6006/sb-manager/chunk-FGVEHHDQ.mjs:90
scheduleUpdateOnFiber @ http://localhost:6006/sb-manager/chunk-FGVEHHDQ.mjs:90
updateContainer @ http://localhost:6006/sb-manager/chunk-FGVEHHDQ.mjs:127
(anonymous) @ http://localhost:6006/sb-manager/chunk-FGVEHHDQ.mjs:127
unbatchedUpdates @ http://localhost:6006/sb-manager/chunk-FGVEHHDQ.mjs:90
legacyRenderSubtreeIntoContainer @ http://localhost:6006/sb-manager/chunk-FGVEHHDQ.mjs:127
render @ http://localhost:6006/sb-manager/chunk-FGVEHHDQ.mjs:127
renderStorybookUI @ http://localhost:6006/sb-manager/chunk-Q4UME242.mjs:406
(anonymous) @ http://localhost:6006/sb-manager/runtime.mjs:1

GET /stories.json HTTP/1.1
Accept: application/json
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9
Connection: keep-alive
Host: xyz-design-system.xyz.com
Origin: http://localhost:6006
Referer: http://localhost:6006/
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36

HTTP/1.1 200 OK
server: istio-envoy
date: Fri, 07 Apr 2023 17:59:51 GMT
content-type: application/json
content-length: 18014
last-modified: Tue, 04 Apr 2023 19:27:07 GMT
etag: "642c7a0b-465e"
accept-ranges: bytes
x-envoy-upstream-service-time: 24

**Comment by shilman** [comment]
When you navigate to `//xyz-design-system.xyz.com/stories.json` manually, does it load properly in the browser? Does it have CORS headers?

**Comment by jmucsi** [comment]
<img width="1668" alt="storiesjson" src="https://user-images.githubusercontent.com/94075049/230940428-4f33098e-3c38-4954-a1f5-c399c8184b87.png">

Yes, the screenshot shows our stories.json on the left side. Is there a particular header that should be in the response such as Vary: Origin?
Thanks.

**Comment by shilman** [comment]
Do you a have a reproduction repo you can share? If not, can you create one? Go to https://storybook.new or see [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce). Thank you! 🙏

**Comment by jmucsi** [comment]
Just create a project on storybook.new and link to it from your local Storybook instance. That's what I did. For example:

refs: {
    'myxyz': {
      title: 'My Design System',
      url: 'https://mkligablbgithub-5mnj--6006--b5037fed.local-credentialless.webcontainer.io',
      expanded: false, // Optional, true by default
    },
  },
