### ISSUE TITLE
Curly brackets instead of square brackets, in array not required input

### ISSUE THREAD

**Issue by jasiukiewicztymon** [storybookjs/storybook#22003]
### Describe the bug

**Curly brackets** instead of **square brackets**, in array not required input are shown in the text input. The problem is shown in the screenshot below:

![image](https://user-images.githubusercontent.com/73474137/230794421-b922ca4e-c5ce-4617-9324-248bd7e5fdaf.png)

### To Reproduce

1. Create a React project (npx create-react-app ...)
2. Add storybook (npx sb init)
3. Add a PropTypes to the component with a value set to array not required

### System

```shell
storybook@7.0.2
```

**Comment by shilman** [comment]
Do you a have a reproduction repo you can share? If not, can you create one? Go to https://storybook.new or see [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce). Thank you! 🙏

**Comment by jasiukiewicztymon** [comment]
---

[Reproduction repo](https://github.com/jasiukiewicztymon/storybook-bug-no22003)

---

I have noticed as well that here the label says to set my starting position as an object:

![image](https://user-images.githubusercontent.com/73474137/230910880-76dd42e4-6ee6-4c79-b38d-84df6f621fb0.png)

But you can see that on the first screen, it shows us that is an array...

**Comment by jasiukiewicztymon** [comment]
> Do you a have a reproduction repo you can share? If not, can you create one? Go to https://storybook.new or see [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce). Thank you! 🙏

Is the comment above ok?
