### ISSUE TITLE
[Bug]: addDecorator got removed from @storybook/react

### ISSUE THREAD

**Issue by furkanalptokac** [storybookjs/storybook#22005]
### Describe the bug

Hi there. I'm migrating storybook v6.4.17 to 7.0.2. We were using `addDecorator` with @storybook/react@6.4.17 and somehow, it got removed from @storybook/react. I checked the changelog and I saw under MIGRATION.md that you dropped support for addDecorators. We need addDecorators, it's really breaking change for us. Could we bring it back with a small patch, maybe?

### System

```shell
Environment Info:

  System:
    OS: Linux 5.15 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
  Binaries:
    Node: 16.19.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.3 - /usr/local/bin/npm
  npmPackages:
    @storybook/addon-essentials: ^7.0.2 => 7.0.2
```

**Comment by shilman** [comment]
@furkanalptokac  addDecorator has been deprecated for over 2y https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-addparameters-and-adddecorator

If you have code that looks like:

```js
addDecorator(someDecoratorFn);
```

Just rewrite it to:

```js
export default {
  decorators: [someDecoratorFn],
};
```

And it will work exactly the same as before.
