### ISSUE TITLE
[Bug]: change in a story requires double save to be hot reloaded

### ISSUE THREAD

**Issue by lukasz-blazewicz-erecruiter** [storybookjs/storybook#22018]
### Describe the bug

Version: 7.0.2 + vite

Setup details: rollup-based react-component library with storybook+vite alongside (within the same project).

As you can see in the following gif, the first hmr update does not bring the changes to the storybook UI - only if the story gets saved for the second time inside VS Code, the changes are reflected on the page. 

![2023-04-11_07h35_17](https://user-images.githubusercontent.com/118973773/231066459-3a32d701-0ea0-47a8-983f-96b2501bafd7.gif)

Any idea what might be the reason or how to track the bug down? Happy to provide any configuration details if needed. 

Thanks a lot.

### System

```shell
System:
    OS: Windows 10 10.0.22621 // (not true, btw, it's win11)
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i7-1270P
  Binaries:
    Node: 19.7.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1413.0), Chromium (112.0.1722.34)
  npmPackages:
    @storybook/addon-essentials: 7.0.2 => 7.0.2
    @storybook/addon-interactions: 7.0.2 => 7.0.2
    @storybook/addon-links: 7.0.2 => 7.0.2
    @storybook/blocks: 7.0.2 => 7.0.2
    @storybook/react: 7.0.2 => 7.0.2
    @storybook/react-vite: 7.0.2 => 7.0.2
    @storybook/testing-library: 0.0.14-next.1 => 0.0.14-next.1
  npmGlobalPackages:
    @storybook/cli: 6.5.16
```

**Comment by shilman** [comment]
Do you a have a reproduction repo you can share? If not, can you create one? Go to https://storybook.new or see [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce). Thank you! 🙏

**Comment by lukasz-blazewicz-erecruiter** [comment]
@shilman 
Sure thing, Michael, thanks.
For the next month I remain OOO (on the trip to SF, by the way 😎) so I won't be able to provide you with the reproduction quickly. However, as soon as I'm back, I will do my best to bring back a repo with a proper repro, so let's keep the issue open, please.

**Comment by lukasz-blazewicz-erecruiter** [comment]
@shilman 
Hey again!
Coming back with the reproduction:
https://github.com/lukasz-blazewicz-erecruiter/storybook-hmr-repro

The repo is a stripped version of our internal component library, so please ignore some pieces of configuration that seem strange at first glance (e. g. in the actual repo we do apply a decorator in preview.tsx 😉). Just tried to keep it as close to the original one as possible, without exposing the in-house stuff.

In the following scenario a dummy button is used to demonstrate how the changes in code are reflected in storybook with an off-by-one delay. Interestingly, the first update attempt is correct, but all the following ones are lagging behind. The autosave feature is deliberately turned off in the editor, to make it clear when the actual save happens - but anyway, with VS Code autosave turned on, it's exactly the same story.

![storybook-hmr-repro](https://github.com/storybookjs/storybook/assets/118973773/a16956e9-5e5a-4ab2-a661-6e738ed6704d)

What's important - double saving does the trick (I forgot to include it in the gif, my bad). If we perform save attempt twice (or, with autosave on, we follow up the automatic save with a manual one) without code changes in between, the storybook displays the correct version of the component.

If any help is needed, just let me know.
Thanks!

**Comment by lukasz-blazewicz-erecruiter** [comment]
Seems the culprit is `@rollup/plugin-typescript`, it has nothing to do with Storybook itself. 
https://github.com/vitejs/vite/issues/12428

Thanks anyway and apologies for the confusion. Closing the issue, then.
