### ISSUE TITLE
[Bug]: Fix @storybook/testing-library types to force async usage

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#22015]
### Describe the bug

Storybook's testing-library wrapper exports synchronous types for various functions that should be awaited in order to make the debugger work. This is currently encoded in eslint rules, but it should be encoded in TS types as well. Otherwise we get misunderstandings like: https://github.com/storybookjs/storybook/pull/21957

@jonniebigodes until we fix the types, we should also add a comment in the CLI template explaining why things must be awaited.

**Comment by ydv-ankit** [comment]
hey, i want to work on this issue

**Comment by shilman** [comment]
thanks @ydv-ankit ! 🙏

**Comment by kasperpeulen** [comment]
Fixed in `@storybook/test`
