### ISSUE TITLE
[Feature Request] Visibility of custom toolbar action

### ISSUE THREAD

**Issue by konsalex** [storybookjs/storybook#22023]
### Is your feature request related to a problem? Please describe

Followed [this guide](https://www.youtube.com/watch?v=DuJ_gmSncLM) to build a custom toolbar item, to enable Dark/Light theme testing.

While it works, the issue is that we may want to use it only for testing in a individual stories, but also to avoid it being displayed in Docs pages. This is the current functionality of the default toolbar items.

![image](https://user-images.githubusercontent.com/12672541/231156205-7e90f933-dc38-4765-a35d-16faebeabaf0.png)

### Describe the solution you'd like

Having more granularity, if we want to display this in Doc pages or not, maybe even on which components to display this (as it might be the case with Design systems that are slowly start supporting dark theme in some components).

### Describe alternatives you've considered

None, maybe there are hacky workarounds with custom scripting to hide this, but the best would be an official support imho

### Are you able to assist to bring the feature to reality?

no

### Additional context

Redirected from Discord: https://discord.com/channels/486522875931656193/1093503083574730752

**Comment by shilman** [comment]
Closing as duplicate to #22081
