### ISSUE TITLE
[Feature Request]: Allow configuration for alias paths in manager builder (esbuild)

### ISSUE THREAD

**Issue by Goncalongt** [storybookjs/storybook#22027]
### Is your feature request related to a problem? Please describe

Whenever I try to import something using a path alias inside manager.ts, I get an error while running/building storybook because it can't resolve that path. However, in the other files (preview.ts, ...) the path alias work fine.

### Describe the solution you'd like

According to what's stated in the following issue #20582, storybook 7 now uses esbuild and not webpack to build the manager, and it's also not configurable, which doesn't allow us to add support for path alias, and instead having to pretranspile our referenced packages. I would love to either have that supported natively, or at least allow us to configure the builder to add support for that.

### Are you able to assist to bring the feature to reality?

no

### Additional context

Here is a shortened version of the code I have on the manager:

```typescript
// .storybook/manager.ts

import { addons } from '@storybook/manager-api';
import { create } from '@storybook/theming';
import { brandTheme } from '@eds/core';

const storybookTheme = create({
	base: 'light',
	colorPrimary: brandTheme.palette.primary.main,
	fontBase: brandTheme.typography.fontFamily,
});

addons.setConfig({
	theme: storybookTheme
});
```

And here's the error I get when running storybook:

```shell
X [ERROR] Could not resolve "@eds/core"                                                          
                                                                                                 
    packages/storybook-host/.storybook/manager.ts:3:27:                                          
      3 │ import { brandTheme } from '@eds/core';                                                
        ╵                            ~~~~~~~~~~~                                                 
                                                                                                 
  You can mark the path "@eds/core" as external to exclude it from the bundle, which will remove 
  this error.     
```

**Comment by ryan-mcginty-alation** [comment]
@Goncalongt is there a workaround for this?
