### ISSUE TITLE
[Bug]: missing stories.iframe.bundle.js

### ISSUE THREAD

**Issue by Shafi-Hassan** [storybookjs/storybook#22031]
### Describe the bug

In the next js app we've created, the storybook is throwing a missing stories.iframe.bundle.js.  We beilve it is because of one of the components that is used in other components throughout the site.  The component uses forwardRef and has a few functions as props.  I think because of this that error is being thrown, also when I disable controls is seems to work but then we have lost control of the storybook .

### System

```shell
Environment Info:

  System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i7-10810U CPU @ 1.10GHz
  Binaries:
    Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.6.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (112.0.1722.39)
  npmPackages:
    @storybook/addon-actions: ^7.0.2 => 7.0.2
    @storybook/addon-backgrounds: ^7.0.2 => 7.0.2
    @storybook/addon-controls: ^7.0.2 => 7.0.2
    @storybook/addon-outline: ^7.0.2 => 7.0.2
    @storybook/addon-toolbars: ^7.0.2 => 7.0.2
    @storybook/addon-viewport: ^7.0.2 => 7.0.2
    @storybook/components: 7.0.2 => 7.0.2
    @storybook/core-events: ^7.0.2 => 7.0.2
    @storybook/manager-api: ^7.0.2 => 7.0.2
    @storybook/nextjs: 7.0.2 => 7.0.2
    @storybook/preview-api: ^7.0.2 => 7.0.2
    @storybook/react: 7.0.2 => 7.0.2
    @storybook/testing-library: ^0.1.0 => 0.1.0
```

**Comment by shilman** [comment]
Do you a have a reproduction repo you can share? If not, can you create one? Go to https://storybook.new or see [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce). Thank you! 🙏

**Comment by georgecartridge** [comment]
In case anyone runs into this again, I had the same issue recently. Storybook would throw an error stating: `missing stories.iframe.bundle.js` for some of my components. 

In my case, the error was occurring when attempting to do a default export before the definition of compound components in React. React didn't have any issues with this pattern, but it seems like Storybook doesn't like it.

My code that was causing the error looked something like this:

```jsx
import { Phrase } from './Phrase';

export default function HelloWorld() {
    return(
        <div>...</div>
    );
}

HelloWorld.Phrase = Phrase;
```

To resolve it, I just moved the default export after the definition of compound components:

```jsx
import { Phrase } from './Phrase';

function HelloWorld() {
    return(
        <div>...</div>
    );
}

HelloWorld.Phrase = Phrase;

export default HelloWorld;
```

**Comment by consdu** [comment]
> In case anyone runs into this again, I had the same issue recently. Storybook would throw an error stating: `missing stories.iframe.bundle.js` for some of my components.
> 
> In my case, the error was occurring when attempting to do a default export before the definition of compound components in React. React didn't have any issues with this pattern, but it seems like Storybook doesn't like it.
> 
> My code that was causing the error looked something like this:
> 
> ```js
> import { Phrase } from './Phrase';
> 
> export default function HelloWorld() {
>     return(
>         <div>...</div>
>     );
> }
> 
> HelloWorld.Phrase = Phrase;
> ```
> 
> To resolve it, I just moved the default export after the definition of compound components:
> 
> ```js
> import { Phrase } from './Phrase';
> 
> function HelloWorld() {
>     return(
>         <div>...</div>
>     );
> }
> 
> HelloWorld.Phrase = Phrase;
> 
> export default HelloWorld;
> ```

This worked for me!
