### ISSUE TITLE
[Bug]: Path alias in manager builder (esbuild) not working/configurable

### ISSUE THREAD

**Issue by Goncalongt** [storybookjs/storybook#22078]
### Describe the bug

Whenever you try to import something using a path alias inside manager.ts, you'll get an error while running/building storybook because it can't resolve that path. However, in the other files (preview.ts, ...) the path alias work fine.

### To Reproduce

https://stackblitz.com/edit/github-fvxqrj?file=.storybook/manager.ts&view=editor

It's slightly different from my code (which I state below), but the essence of the problem is the same. The path alias to "@public" doesn't work, but on preview.ts it does.

### System

```shell
System:
  OS: Windows 10 10.0.17763
  CPU: (12) x64 Intel(R) Xeon(R) E-2246G CPU @ 3.60GHz
Binaries:
  Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
  Yarn: 3.5.0 - C:\Program Files\nodejs\yarn.CMD
  npm: 9.6.4 - C:\Program Files\nodejs\npm.CMD
Browsers:
  Chrome: 111.0.5563.147
npmPackages:
  @storybook/addon-essentials: 7.0.4 => 7.0.4
  @storybook/addon-mdx-gfm: 7.0.4 => 7.0.4
  @storybook/core-common: 7.0.4 => 7.0.4
  @storybook/core-server: 7.0.4 => 7.0.4
  @storybook/react: 7.0.4 => 7.0.4
  @storybook/react-vite: 7.0.4 => 7.0.4
```

### Additional context

According to what's stated in the following issue #20582, storybook 7 now uses esbuild and not webpack to build the manager, and it's also not configurable, which doesn't allow us to add support for path alias, and instead having to pretranspile our referenced packages. I would love to either have that supported natively, or at least allow us to configure the builder to add support for that (configuration file in the .storybook folder, configuration parameter in main.ts, etc).

Here is a shortened version of the code I have on the manager:

```typescript
// .storybook/manager.ts

import { addons } from '@storybook/manager-api';
import { create } from '@storybook/theming';
import { brandTheme } from '@eds/core';

const storybookTheme = create({
	base: 'light',
	colorPrimary: brandTheme.palette.primary.main,
	fontBase: brandTheme.typography.fontFamily,
});

addons.setConfig({
	theme: storybookTheme
});
```

And here's the error I get when running storybook:

```shell
X [ERROR] Could not resolve "@eds/core"                                                          
                                                                                                 
    packages/storybook-host/.storybook/manager.ts:3:27:                                          
      3 │ import { brandTheme } from '@eds/core';                                                
        ╵                            ~~~~~~~~~~~                                                 
                                                                                                 
  You can mark the path "@eds/core" as external to exclude it from the bundle, which will remove 
  this error.     
```

**Comment by ernestostifano** [comment]
Related to this: https://github.com/storybookjs/storybook/discussions/22851

I have the same problem...

**Comment by emlynmac** [comment]
+1, I have the same issue. Blocking updating to v7

**Comment by DavidVollmers** [comment]
Same problem here. Have a NX mono repository where I have multiple storybooks and a common theme package. Can't import it in the `tsconfig` using the path alias...

**Comment by ernestostifano** [comment]
Related to this issue too https://github.com/storybookjs/storybook/issues/22027

**Comment by ernestostifano** [comment]
This issue should be prioritised because with the new behaviour of TypeScript in ESM environments, imports should always have a '.js' extension, independently of the actual extension of the real file.

This makes it impossible to create addons in ESM + TypeScript setups.

So basically, this happens:

```bash
Error: Build failed with 3 errors:
pnp:./.storybook/addons/styling/manager.ts:6:7: ERROR: [plugin: @yarnpkg/esbuild-plugin-pnp] Qualified path resolution failed: we looked for the following paths, but none could be accessed.

Source path: ./src/styling/themes/index.js
Not found: ./src/styling/themes/index.js
Not found: ./src/styling/themes/index.js.tsx
Not found: ./src/styling/themes/index.js.ts
Not found: ./src/styling/themes/index.js.jsx
Not found: ./src/styling/themes/index.js.mjs
Not found: ./src/styling/themes/index.js.cjs
Not found: ./src/styling/themes/index.js.js
Not found: ./src/styling/themes/index.js.css
Not found: ./src/styling/themes/index.js.json
```

**Comment by valentinpalkovic** [comment]
Closing, because [not planned for now](https://github.com/storybookjs/storybook/pull/24765#issuecomment-1810237296)

**Comment by ernestostifano** [comment]
Cross-posting https://github.com/storybookjs/storybook/pull/24765#issuecomment-1817592164 for future reference
