### ISSUE TITLE
[Bug]: On Storybook 7, the code snippet doesn't work if one of the controls is hidden

### ISSUE THREAD

**Issue by macabeus** [storybookjs/storybook#22099]
### Describe the bug

I have a React component whose story has conditional controls, but I noticed that it doesn't outputs correctly the JSX if one of the controls is hidden.

The same code works on Storybook 6.

May be related to #22100

<img width="1060" alt="image" src="https://user-images.githubusercontent.com/9501115/232120159-6aad98a3-614b-4190-b55b-6f09a1731976.png">

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/9501115/232120186-7d89c58e-6bdf-4373-8c25-019bfde4cff5.png">

### To Reproduce

```tsx
import { Meta, StoryObj } from '@storybook/react';
import React from 'react';

const Example = (props) => {
  return <div>Message: {props.hasMessage ? props.message : 'no text'}</div>;
};

type Component = typeof Example;

const meta: Meta<Component> = {
  component: Example,
  argTypes: {
    hasMessage: { type: 'boolean' },
    message: {
      control: 'text',
      if: { arg: 'hasMessage' },
    },
  },
};

export default meta;

export const Default: StoryObj<Component> = {
  args: {
    hasMessage: false,
    message: 'foo',
  },
};
```

### System

```shell
Environment Info:

  System:
    OS: macOS 13.2
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.15.1/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
  Browsers:
    Chrome: 111.0.5563.110
    Firefox: 109.0.1
    Safari: 16.3
  npmPackages:
    @storybook/addon-actions: ^7.0.4 => 7.0.4
    @storybook/addon-docs: ^7.0.4 => 7.0.4
    @storybook/addon-essentials: ^7.0.4 => 7.0.4
    @storybook/addon-links: ^7.0.4 => 7.0.4
    @storybook/addon-mdx-gfm: ^7.0.4 => 7.0.4
    @storybook/node-logger: ^7.0.4 => 7.0.4
    @storybook/react: ^7.0.4 => 7.0.4
    @storybook/react-vite: ^7.0.4 => 7.0.4
```

**Comment by shilman** [comment]
I can reproduce with your example.This is probably the root cause of your other issue #22100.  This is pretty weird--taking a look now!

**Comment by shilman** [comment]
@tmeasday This looks like a bug here:

https://github.com/storybookjs/storybook/blob/e154c170b2a3b5410ca2cf41a5c374a2dae50f83/code/ui/blocks/src/blocks/Source.tsx#L83-L99

Is it possible that this doesn't take conditional controls into account? You can reproduce the problem by copying @macabeus 's example into a sandbox. The JSX is getting rendered successfully, but somehow this function is returning the empty string, which is causing other code to fallback to using the original story source in another part of the code.

**Comment by tmeasday** [comment]
@shilman I'll admit I don't know how the conditional args work -- where in the chain does the `message` arg get stripped off?

**Comment by tmeasday** [comment]
Thanks @winkerVSbecks. Mapping + conditional control filtering happen in the same place so this is indeed the same issue.

**Comment by shilman** [comment]
Great Caesar's ghost!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.1.0-alpha.12 containing PR #22135 that references this issue. Upgrade today to the `@future` NPM tag to try it out!

```
npx sb@next upgrade --tag future
```

**Comment by shilman** [comment]
Jiminy cricket!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.12 containing PR #22135 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb@latest upgrade
```
