### ISSUE TITLE
[Bug]: SB7 Build fail - Webpack failed - Nx, Angular

### ISSUE THREAD

**Issue by Majky1423** [storybookjs/storybook#22105]
### Describe the bug

I am not able to run build-storybook after NX update to 15.8.9 (I was not using SB for a longer time but I think, the last time I built SB, I had Nx ~14.4). I am able to run just storybook ("@storybook/angular:start-storybook") command without any problems. I was definitely able to build SB on v.7 beta (.48) but now I can only run it, not build it. I tried to update SB to the latest version but it did not help. I opened issue on NX GitHub but apparently, they're just calling `@storybook/angular` directly, so I dont know. I tried everything that was suggested on Nx github and without luck. Also tried to make reproduction but without luck. Any hint, what could be wrong, is really appreciated, thanks.

### System

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
  Binaries:
    Node: 16.10.0 - C:\Program Files\nodejs\node.EXE
    npm: 7.24.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (112.0.1722.46)    
  npmPackages:
    @storybook/addon-actions: ^7.0.4 => 7.0.4 
    @storybook/addon-docs: ^7.0.4 => 7.0.4 
    @storybook/addon-essentials: ~7.0.4 => 7.0.4 
    @storybook/addon-mdx-gfm: ^7.0.4 => 7.0.4 
    @storybook/angular: ~7.0.4 => 7.0.4 
    @storybook/blocks: ^7.0.4 => 7.0.4 
    @storybook/client-api: ^7.0.4 => 7.0.4 
    @storybook/core-server: ~7.0.4 => 7.0.4 
    @storybook/manager-api: ^7.0.4 => 7.0.4
    @storybook/theming: ^7.0.4 => 7.0.4
```

### Additional context

Failure log
A lot of: 
ERR! => Failed to build the preview
ERR!8192.a49061ef.iframe.bundle.js from Terser plugin
ERR! __spreadProps is not defined
ERR! ReferenceError: __spreadProps is not defined
ERR!     at buildTerserOptions (eval at transform (\node_modules\terser-webpack-plugin\dist\minify.js:43:3), <anonymous>:71:5)
ERR!     at terserMinify (eval at transform (\node_modules\terser-webpack-plugin\dist\minify.js:43:3), <anonymous>:90:25)
ERR!     at minify (\node_modules\terser-webpack-plugin\dist\minify.js:23:10)
ERR!     at Object.transform (\node_modules\terser-webpack-plugin\dist\minify.js:44:10)
ERR!     at execFunction (\node_modules\jest-worker\build\workers\threadChild.js:148:17)
ERR!     at execHelper (\node_modules\jest-worker\build\workers\threadChild.js:127:5)
ERR!     at execMethod (\node_modules\jest-worker\build\workers\threadChild.js:131:5)
ERR!     at MessagePort.messageListener (\node_modules\jest-worker\build\workers\threadChild.js:49:7)
ERR!     at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:559:20)
ERR!     at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)

And at the end:
ERR!
ERR! Error: => Webpack failed, learn more with --debug-webpack
ERR!     at null.<anonymous> (\node_modules\@storybook\builder-webpack5\dist\index.js:1:7620)
ERR!     at null.<anonymous> (\node_modules\webpack\lib\HookWebpackError.js:68:3)
ERR!     at Hook.eval [as callAsync] (eval at create (\node_modules\tapable\lib\HookCodeFactory.js:25:14), <anonymous>:11:1)
ERR!     at Hook.CALL_ASYNC_DELEGATE (\node_modules\tapable\lib\Hook.js:18:14)
ERR!     at Cache.shutdown (\node_modules\webpack\lib\Cache.js:150:23)
ERR!     at null.<anonymous> (\node_modules\webpack\lib\Compiler.js:1225:15)
ERR!     at Hook.eval [as callAsync] (eval at create (\node_modules\tapable\lib\HookCodeFactory.js:25:14), <anonymous>:15:1)
ERR!     at Hook.CALL_ASYNC_DELEGATE (\node_modules\tapable\lib\Hook.js:18:14)
ERR!     at Compiler.close (\node_modules\webpack\lib\Compiler.js:1218:23)
ERR!     at null.<anonymous> (\node_modules\@storybook\builder-webpack5\dist\index.js:1:7572)
ERR!

**Comment by shilman** [comment]
Do you a have a reproduction repo you can share? If not, can you create one? Go to https://storybook.new or see [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce). Thank you! 🙏

**Comment by Majky1423** [comment]
I tried few times but with any luck ... will try to more copy our project but I can't promise anything :/

**Comment by Majky1423** [comment]
Well, I manage to fix it by deleting both node_modules with package-lock.json and install again. Thanks anyway :)
