### ISSUE TITLE
[Bug]: v4 links are broken

### ISSUE THREAD

**Issue by mahassan** [storybookjs/storybook#22137]
### Describe the bug

While visiting the [page](https://github.com/storybookjs/storybook/tree/next/lib/codemod) while visiting [page](https://github.com/storybookjs/storybook/blob/master/lib/core/docs/storiesOf.md) link

### To Reproduce

visiting [page](https://github.com/storybookjs/storybook/blob/master/lib/core/docs/storiesOf.md) and click on links which are mostly brokem

**Comment by tauseefmohammed2** [comment]
Hi!
I would love to contribute to the repo. I saw that the issue is labelled "first time", which is perfect for me as I am new to this project and eager to get started. Could you please assign this issue to me?
