### ISSUE TITLE
[Bug]: Storybook in v.7 does not render html code in slots

### ISSUE THREAD

**Issue by Juanjo-GEx** [storybookjs/storybook#22139]
### Describe the bug

Storybook only allows you to pass **strings** in the slots. You should be able to pass **templates html** as previously allowed.

### To Reproduce

```
export const Testing: Story = {
  args: {
    default: `<div><span>Example</span></div>`,
  },
};
```

Renders the code as a string instead of html

**Comment by dylanjmcdonald** [comment]
Does your story filename end with `.jsx` or `.tsx`?

**Comment by dylanjmcdonald** [comment]
If you are using React you can either use [dangerouslySetInnerHTML](https://legacy.reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml) or make sure you're using a `.tsx` file extension for your Story file and remove the backtick characters from your HTML string.

**Comment by shilman** [comment]
Do you have a full reproduction you can share? If not, can you create one? Go to https://storybook.new or see [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce). Thank you! 🙏

**Comment by michaelGregoire** [comment]
This is quite a major bug. I sure hope it’s being prioritized.

**Comment by mattjcj** [comment]
Hello, here's a repro: https://stackblitz.com/edit/github-268xge-u7p1nv?file=package.json&preset=node

Can this be reopened ? Thanks

**Comment by ozgur-proreact** [comment]
@shilman this is an important bug that blocks use to use Storybook. I hope it’s being prioritized.
