### ISSUE TITLE
[Bug]: non-inline stories do not receive updates from controls for Docs pages

### ISSUE THREAD

**Issue by probablyup** [storybookjs/storybook#22148]
### Describe the bug

There appears to be a bug where a docs page that contains a non-inline primary story does not receive arg changes from the related `<Controls />` panel.

### To Reproduce

Visit a Docs page for a component and set the story parameters as follows:

```
docs: {
  story: {
    inline: false,
  },
},
```

This triggers the story to load inside an iframe instead of inline. When this config is set, manipulating the controls for the story has no effect.

### Additional context

Does occur in v6 as well when `inlineStories: false`

**Comment by probablyup** [comment]
Hmm I removed my custom DocsPage and it's working... will investigate further.

**Comment by probablyup** [comment]
I'm wondering if it's because the ID for iframe stories has the "iframe--" prefix?

**Comment by shilman** [comment]
closing as dupe to #11908
