### ISSUE TITLE
[Bug]: WARN Broken build, fix ... ModuleDependencyError for storybook-start (6/7)

### ISSUE THREAD

**Issue by georgec-travellocal** [storybookjs/storybook#22159]
### Describe the bug

Here is what the error output looks like:

```
ModuleDependencyError: export 'createChannel' (imported as 'createChannel') was not found in '@storybook/channel-postmessage' (possible exports: KEY, PostmsgTransport, default)

ModuleDependencyError: export 'deprecate' (imported as 'deprecate2') was not found in '@storybook/client-logger' (possible exports: logger, once, pretty)

...

ModuleDependencyError: export 'PLAY_FUNCTION_THREW_EXCEPTION' (imported as 'PLAY_FUNCTION_THREW_EXCEPTION') was not found in '@storybook/core-events'

...

ModuleDependencyError: export 'SET_INDEX' (imported as 'SET_INDEX') was not found in '@storybook/core-events'
```

I don't really know how to reproduce it, I merged a branch where both storybook-start was working on both branches but after merging gave the above error so I can't open storybook to view all the components. In my branch I upgraded from next 12 to 13.

Any idea how to fix the above errors?

Thanks

### System

```shell
Environment Info:

  System:
    OS: Linux 5.10 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i7-1255U
  Binaries:
    Node: 16.14.2 - ~/.nodenv/versions/16.14.2/bin/node
    Yarn: 3.2.4 - ~/.nodenv/versions/16.14.2/bin/yarn
    npm: 8.5.0 - ~/.nodenv/versions/16.14.2/bin/npm
```

### Additional context

I'm running it on Windows Subsystem for Linux (WSL).

**Comment by georgec-travellocal** [comment]
After deleting the project and cloning it again, the issue has gone away.

**Comment by alextreppass** [comment]
Also running into this with storybook libs at `^6.5.13"`.

For me, it's the import of `{ expect } from '@storybook/jest' which breaks it. I am using it as per the storybook interactions docs, and it won't start with that import in place.

**Comment by eadmundo** [comment]
I had this issue, all `@storybook` libs at `6.5.16` (we can't upgrade to 7 yet).

I managed to solve it by pinning:
- `@storybook/testing-library` to `0.0.13`
-  `@storybook/jest` to `0.0.10`
-  `@storybook/test-runner` is at `0.9.2`.

Essentially I think you need all the libraries to be just pre-"Support version 7.0". hope that helps!

**Comment by alextreppass** [comment]
Thanks - tried pinning those versions but no dice w/ storybook libs at 6.5.13. I also tried 6.5.16.

I think I'll have to bite the bullet and upgrade to SB 7
