### ISSUE TITLE
Addon panel does not update after disabling/enabling an addon

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#22158]
1. Open Storybook
2. Add `actions: { disable: true }` and see it update correctly
3. change to `actions: { disable: false }` or remove the line altogether, and see that the panel does not get updated (at the end of the gif I had to refresh the browser):

![2023-03-21 18 04 22](https://user-images.githubusercontent.com/1671563/226687329-39cee732-5dfe-440f-b6df-51a43ca3cbff.gif)

Is this a memo issue?

_Originally posted by @yannbf in https://github.com/storybookjs/storybook/issues/21650#issuecomment-1478281006_

**Comment by shilman** [comment]
Ta-da!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.1.0-alpha.12 containing PR #22258 that references this issue. Upgrade today to the `@future` NPM tag to try it out!

```
npx sb@next upgrade --tag future
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
w00t!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.8 containing PR #22258 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb@latest upgrade
```

**Comment by yannbf** [comment]
Closing as the issue has been fixed!
