### ISSUE TITLE
[Bug]: Storybook action logs eventName:{name: eventName, args: false} for false value works with boolean true value

### ISSUE THREAD

**Issue by tejas-ansys** [storybookjs/storybook#22163]
### Describe the bug

Hello,
I am having button component which is emitting value as a boolean value.
Storybook shows the value in the action tab as eventName say click then
**click:true** if value emitted is true but if we are emitting a value false then it logs click:{name: "clicked", args: false}} which is not correct. I tried this with both angular and react project which is not working.
It should emit **click:false** rather than **click:{name: "clicked", args: false}}.**
![Screenshot 2023-04-19 154308](https://user-images.githubusercontent.com/107472195/233045041-501e93ad-a8d3-4d03-bbb7-b94b2c3979ed.png)

### To Reproduce

```
///component.tsx
import React from 'react';

const Buttons: React.FunctionComponent<any> = (props) => {
  let val = false;
  const onClickHandler = () => {
    val = !val;
    props.onClick(val);
  };

  return (
    <button className="button" onClick={onClickHandler}>Button</button>
  );
};

export default Buttons;


// stories.tsx

import { Meta, Story } from '@storybook/react/types-6-0';
import React from 'react';
import Buttons from '.';

export default {
  title: 'Misc/Action Bar',
  argTypes: { onClick: { action: 'clicked' } },
} as Meta;

const Template: Story<any> = (args) => {
  return <Buttons {...args} />;
};

export const BasicDemo = Template.bind({});

BasicDemo.args = {};
```

**Comment by shilman** [comment]
Do you a have a reproduction repo you can share? If not, can you create one? Go to https://storybook.new or see [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce). Thank you! 🙏

**Comment by tejas-ansys** [comment]
@shilman 
please have a look at this:
https://stackblitz.com/edit/github-xyklgy?file=src%2Fstories%2FButton.tsx,src%2Fstories%2FButton.stories.ts&preset=node

**Comment by chloeaallison** [comment]
@shilman Is there any update on this issue?

**Comment by homj** [comment]
I have the same issue. Emitting `true` is being logged correctly, but false is logged as an object

![Bildschirmfoto 2023-05-05 um 12 13 42](https://user-images.githubusercontent.com/3742395/236431877-12b1df7b-ca1c-48df-b969-1330392bebcc.png)

**Comment by TheCrimsonKing92** [comment]
> @shilman please have a look at this: https://stackblitz.com/edit/github-xyklgy?file=src%2Fstories%2FButton.tsx,src%2Fstories%2FButton.stories.ts&preset=node
> 
> Goto button stories and click on button. Then check actions tab.

@tejas-ansys this crashes for me in Chrome with a sandbox out of memory error, is this something you can resolve?

**Comment by chloeaallison** [comment]
@shilman Is there any update here?

**Comment by QuentinLeCaignec** [comment]
I'm encountering this bug as well, any updates?

**Comment by takumi-ricoh** [comment]
I'm also suffering from the same bug.

**Comment by Fatcat560** [comment]
A colleague and me at work encountered this problem too. After digging around in the source code, we believe this line is the culprit here:

https://github.com/storybookjs/storybook/blob/c8f70900b19131e4e606501ab38594daabd1bd48/code/addons/actions/src/components/ActionLogger/index.tsx#L53

Any value we pass as argument that evaluates falsey would be replaced by the whole data object, which is exactly what is happening here.

Simply replacing the or (||) operator with the nullish coalescing (??) operator should fix the issue. 

If I find the time this weekend I'll try to create a PR for this issue.

**Comment by Fatcat560** [comment]
I had some time today to try this one out. In the test stories included, the old behaviour was easy to replicate by simply randomly flipping a boolean:
![behaviour_prev_bool](https://github.com/storybookjs/storybook/assets/21345415/8cfb4d0e-086d-43c9-b47b-8c53f5e02f4e)

This also happens with a counter once it would reach 0:
![behaviour_prev_num](https://github.com/storybookjs/storybook/assets/21345415/76a2da04-230c-4d4b-acd4-29ee48ce9727)

With the proposed change, the booleans and numbers would get printed as one would expect:
![behaviour_new_bool](https://github.com/storybookjs/storybook/assets/21345415/546768d0-5a30-4da3-969b-ad8122d3c513)
![behaviour_new_num](https://github.com/storybookjs/storybook/assets/21345415/6a9b337d-0f4d-4170-b690-7d624599232e)

@ndelangen @yannbf sorry for the pings but I saw your names as the code owners for the actions addon. Would such a change be welcome?
