### ISSUE TITLE
[Bug]: Vue source code alternates between compiled template and story obj

### ISSUE THREAD

**Issue by drunkenvalley** [storybookjs/storybook#22166]
### Describe the bug

When viewing a Vue component in Storybook the output from any source code gets garbled on a regular basis.

Notably:
1. Before initial render we receive the story obj, not the compiled template
2. After editing any props we receive the story obj again, not the compiled template

#### Expected behavior

![image](https://user-images.githubusercontent.com/1728144/233062481-20b6fd43-267e-4190-b417-89824d29b84b.png)

#### Actual behavior

![image](https://user-images.githubusercontent.com/1728144/233062572-7b8ca648-63d8-4c50-8ce6-3a6c6b192510.png)

### To Reproduce

See reproduction: https://stackblitz.com/github/storybookjs/sandboxes/tree/next/vue2-vite/2.7-js/after-storybook?file=src/stories/Button.stories.js

This is genuinely an unedited reproduction. Simply view the generated Storybook, go to the **Button** component, and click **Show code**. You should see a compiled template like the **Expected Behavior** image. 

However, if you edit the props the code now changes to the **Actual Behavior** image.

You can also see this **Actual Behavior** output by creating an MDX document and importing **Source**, then use it like this, as it appears the initial page load also outputs this incorrect code.

```mdx
<Source of={Component} type="code" />
```

### System

```shell
Environment Info:

  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @storybook/addon-essentials: ^7.1.0-alpha.5 => 7.1.0-alpha.7 
    @storybook/addon-interactions: ^7.1.0-alpha.5 => 7.1.0-alpha.7 
    @storybook/addon-links: ^7.1.0-alpha.5 => 7.1.0-alpha.7 
    @storybook/blocks: ^7.1.0-alpha.5 => 7.1.0-alpha.7 
    @storybook/testing-library: ^0.0.14-next.2 => 0.0.14-next.2 
    @storybook/vue: ^7.1.0-alpha.5 => 7.1.0-alpha.7 
    @storybook/vue-vite: ^7.1.0-alpha.5 => 7.1.0-alpha.7
```

**Comment by shilman** [comment]
closing as probable dupe to #22099
