### ISSUE TITLE
[Bug]: Issues installing sb7 on vue 2 with webpack 4

### ISSUE THREAD

**Issue by yeezussniper** [storybookjs/storybook#22194]
### Describe the bug

```
Error: Compiling RuleSet failed: Unexpected property test in condition (at ruleSet[1].rules[5].resource.test: (resource2) => {
        currentResource = resource2;
        return true;
      })
```

I see this message when I try to run version 7 on vue 2 with webpack 4

My package.json 

```
  "dependencies": {
    "core-js": "^3.8.3",
    "vue": "^2.6.14",
    "vuetify": "^2.6.0"
  },
  "devDependencies": {
    "@storybook/addon-essentials": "^7.0.6",
    "@storybook/addon-interactions": "^7.0.6",
    "@storybook/addon-links": "^7.0.6",
    "@storybook/blocks": "^7.0.6",
    "@storybook/testing-library": "^0.0.14-next.2",
    "@storybook/vue": "^7.0.6",
    "@storybook/vue-webpack5": "^7.0.6",
    "@vue/cli-plugin-babel": "^4.5.13",
    "@vue/cli-plugin-typescript": "^4.5.13",
    "@vue/cli-service": "^4.5.13",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "sass": "^1.32.7",
    "sass-loader": "^10",
    "storybook": "^7.0.6",
    "typescript": "~4.5.5",
    "vue-cli-plugin-vuetify": "~2.5.8",
    "vue-loader": "^15.10.1",
    "vue-template-compiler": "^2.6.14",
    "vuetify": "^2.6.0",
    "vuetify-loader": "^1.7.0"
  },
```

**Comment by shilman** [comment]
@yeezussniper Unfortunately SB7 does not support wepback4 https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#webpack4-support-discontinued

**Comment by yeezussniper** [comment]
@shilman I tried to run the installation via "npx storybook init --type vue" and "npx storybook@6.5 init --type vue", storybook initializes folders and config files, but my project does not see the storybook-build command, what am I doing wrong? 😅

**Comment by viaFarhan** [comment]
@yeezussniper If you are able to update to webpack5 and still need vue 2.7:

* `npx storybook@latest init`
	* `npx --legacy-peer-deps ...` to get it to work for my project because there are old things we are updating later
	* also need to specify webpack5 as builder
		* `--builder webpack5`
		* supposed to be default but ours installed with `vite`!

So at the end of the day what worked for me was:
`npx --legacy-peer-deps storybook@latest init --builder webpack5`

---

I lost a ton of time trying to figure this out when it should be in the docs. And the docs specifically said wp5 was the default, yet it configured it for vite.
