### ISSUE TITLE
[Bug]: Error upgrading -> 7.0. The specifier “@storybook/react/preview” was a bare specifier, but was not remapped to anything

### ISSUE THREAD

**Issue by leeweisberger** [storybookjs/storybook#22204]
### Describe the bug

Full error message:
The specifier “@storybook/react/preview” was a bare specifier, but was not remapped to anything. Relative module specifiers must start with “./”, “../” or “/”.

I am using the storybook vite framework, upgrading from the latest version of storybook 6.x.x using the automigration script.

`storybook dev` works fine - I get this error when running `storybook build` and then viewing the built-directory in my browser using `npx http-server ./storybook-static`.

### System

```shell
Environment Info:

  System:
    OS: Linux 5.17 Pop!_OS 22.04 LTS
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.15.0/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
  Browsers:
    Chrome: 110.0.5481.177
    Firefox: 110.0
```

**Comment by shilman** [comment]
Do you a have a reproduction repo you can share? If not, can you create one? Go to https://storybook.new or see [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce). Thank you! 🙏

**Comment by leeweisberger** [comment]
I figured this out.

I didn't realize storybook pulls from our vite config file.

In our vite config, we were marking dependencies as external because we are shipping a component library. Storybook needed us to include these dependencies in the bundle. This seems to have changed from storybook 6.x with vite.
