### ISSUE TITLE
[Bug]: title not set as informed in documentation

### ISSUE THREAD

**Issue by muratcorlu** [storybookjs/storybook#22211]
### Describe the bug

For setting `<title>` tag of the main html file, [current document](https://storybook.js.org/docs/web-components/sharing/publish-storybook#title) says just adding this to `.storybook/main.js` file will do the trick:

```js
export const title = 'My awesome project';
```

But that doesn't work for me (v7.0.6).

### To Reproduce

https://stackblitz.com/edit/github-jrebwy?file=.storybook%2Fmain.ts

One you run/build storybook, HTML title becomes:

```html
<title>@storybook/cli - Storybook</title>
```

### System

```shell
Environment Info:

  System:
    OS: macOS 13.3
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 16.19.1 - /usr/local/bin/node
    npm: 8.15.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 112.0.5615.49
    Safari: 16.4
  npmPackages:
    @storybook/addon-a11y: 7.0.6 => 7.0.6 
    @storybook/addon-actions: 7.0.6 => 7.0.6 
    @storybook/addon-essentials: 7.0.6 => 7.0.6 
    @storybook/addon-interactions: ^7.0.6 => 7.0.6 
    @storybook/addon-links: 7.0.6 => 7.0.6 
    @storybook/addon-mdx-gfm: ^7.0.6 => 7.0.6 
    @storybook/addon-storysource: 7.0.6 => 7.0.6 
    @storybook/addon-viewport: ^7.0.6 => 7.0.6 
    @storybook/jest: ^0.1.0 => 0.1.0 
    @storybook/testing-library: ^0.1.0 => 0.1.0 
    @storybook/web-components: 7.0.6 => 7.0.6 
    @storybook/web-components-vite: ^7.0.6 => 7.0.6
```

**Comment by shilman** [comment]
This looks like a bug in the documentation @jonniebigodes @ndelangen  -- did we ever support this?

**Comment by ndelangen** [comment]
No that's never worked AFAICS:
![Screenshot 2023-04-25 at 08 31 21](https://user-images.githubusercontent.com/3070389/234192906-df0f7292-7f9c-4063-ba40-80560ca5e3f6.png)

**Comment by muratcorlu** [comment]
That's sad. It was nice to see a simple solution to set the title. Because [we really suffer from that](https://github.com/storybookjs/storybook/issues/866) and even [some popular projects make hacks](https://github.com/microsoft/fluentui/blob/2d93a25e46b76bb473f1deaea3180df5ef3c53ec/apps/public-docsite-v9/.storybook/fix-title.js) to work around it.

**Comment by jonniebigodes** [comment]
@muratcorlu Sorry about this and the confusion around it 🙏 . For the time being, this is going to be removed from the documentation to prevent similar issues as you've experienced, and once we have a good way to address this, it will be properly documented. 

Nonetheless, thank you so much for reaching out to us with your issue and letting us know of this small but rather crucial issue with the documentation.


Hope you have a great day.

Stay safe
