### ISSUE TITLE
[Bug]: Unable to find version 7.0.6 of "@storybook/manager-webpack5" on registry

### ISSUE THREAD

**Issue by giero** [storybookjs/storybook#22225]
### Describe the bug

Hello,

I am trying to install version 7.0.6 of "@storybook/manager-webpack5" via yarn, but it seems that this version is not available in the registry yet. According to https://registry.yarnpkg.com/@storybook%2fmanager-webpack5 latest available version is 7.0.0-alpha.10.

Can you please let me know if there is any issue with publishing this version to the yarnpkg registry or if there is anything else that I can try to install this version via yarn?

Thank you for your time and help.

Best regards,
Giero

**Comment by shilman** [comment]
Manager-webpack5 no longer exists in Storybook 7. If you upgrade your project using `npx storybook@latest upgrade` it should remove that dependency from your project. If not, please remove it by hand.
