### ISSUE TITLE
Vue: After upgrading to V7 controls are not interactable

### ISSUE THREAD

**Issue by gridmaniac** [storybookjs/storybook#22227]
### Describe the bug

After migrated to Storybook V7, now Controls do not trigger Story re-render.
I have simple component

### MyButton.vue
```vue
<script setup lang="ts">
defineProps<{
  counter: number;
}>();
</script>

<template>
  <button>
    {{ counter }}
  </button>
</template>
```

### MyButton.stories.js

```js
import MyButton from "./MyButton.vue";

export default {
  component: MyButton,
};

export const Primary = {
  render: (args) => ({
    components: { MyButton },
    template: '<my-button v-bind="args"/>',
    setup() {
      return {
        args,
      };
    },
  }),
  args: {
    counter: 51,
  },
};
```

Under individual stories Controls it doesn't re-render story after I changed arg value.
![image](https://user-images.githubusercontent.com/25141263/233964567-414400fd-ef7e-474f-ade3-f05526dc7637.png)

But if I switch to Docs, it is re-rendered with new args
![image](https://user-images.githubusercontent.com/25141263/233964850-95219136-3a5e-4ab8-9bdb-85b0341ed1ac.png)

And if I change value again, it doesn't get updated.
It was working with latest v6.

### To Reproduce

1. Make vue script setup component with `vue-demi` + `vue-vite`
2. Cover with SFC story
3. Use `Controls` to play with component - it doesn't work

### System

```shell
Environment Info:

  System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M2
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
  Browsers:
    Chrome: 112.0.5615.137
    Safari: 15.5
  npmPackages:
    @storybook/addon-actions: ^7.0.6 => 7.0.6 
    @storybook/addon-essentials: ^7.0.6 => 7.0.6 
    @storybook/addon-interactions: ^7.0.6 => 7.0.6 
    @storybook/addon-links: ^7.0.6 => 7.0.6 
    @storybook/addon-mdx-gfm: ^7.0.6 => 7.0.6 
    @storybook/testing-library: ^0.1.0 => 0.1.0 
    @storybook/vue: ^7.0.6 => 7.0.6 
    @storybook/vue-vite: ^7.0.6 => 7.0.6
```

**Comment by gridmaniac** [comment]
Can be related: https://github.com/storybookjs/storybook/issues/17605

**Comment by shilman** [comment]
Can you please try upgrading to 7.1 alpha?

```
npx sb@next upgrade --tag future
```

See https://github.com/storybookjs/storybook/pull/21273 https://github.com/storybookjs/storybook/pull/21954

**Comment by gridmaniac** [comment]
@shilman thank you for giving more context, I upgraded to latest `7.1.0-alpha.8` and I think the issue only exists in` vue-vite` not `vue3-vite` as I tested it with clean bran-new vue 3 project with vite and it is working as expected.

As I mentioned I am using `vue-demi` and I am still on `Vue 2.7 Naruto` so I guess for `@storybook/vue-vite` there is still some incompatibility and for now I am downgrading to `6` and either consider migrating to Vue 3 or maybe vue-vite framework will be updated in future

**Comment by kasperpeulen** [comment]
I think we put all our effort on making Vue3 more reactive, but we haven't done really anything on Vue2.
@shilman @vanessayuenn Shall we prio that for 7.1?

**Comment by GrtDev** [comment]
We have had this issue as well in both V6 and V7. Currently we are using `vue-vite` configuration. 
I do seem to have found a workaround for the issue though. For creating stories I have a helper function that among other things registers a reference to the `currentInstance`.  Next time the story function is triggered it will use the instance to update the args and force an update. 

Something along the lines of this:

`let component: ComponentOptions<Vue> | null = null;
let currentInstance: ReturnType<typeof getCurrentInstance> = null;

export const Story: StoryFn = ({ ...args }) => {
    if (component && currentInstance?.proxy) {
        (currentInstance.proxy as any).args = args;
        currentInstance.proxy.$forceUpdate();
        return component;
    }

    component = {
        components: { ... },
        setup(props) {
            currentInstance = getCurrentInstance();

            return { args, props };
        },
        template: '...',
    };

    return component;
};`

Hope this helps someone dealing with the same issue (:

**Comment by mokone91** [comment]
Hi! is its possible to make same using decorator? it will allow to apply this globally

**Comment by PenguinQ** [comment]
This also happened to any `reactive` object in `7.1.0-alpha.29`.

**Not Working**
```
const styleObj = reactive({
  color: props.color,
  backgroundColor: props.backgroundColor,
});

<template>
  <div :style="styleObj" />
</template>
```

**Working**
```
<template>
  <div :style="`color: ${color}; background-color: ${backgroundColor}`" />
</template>
```

**Comment by kasperpeulen** [comment]
@chakAs3 Do you think this would be easy to fix for vue2?

**Comment by kasperpeulen** [comment]
> > @chakAs3 Do you think this would be easy to fix for vue2?
> 
> yes I'm thinking of doing a merge. and have only @storybook/vue , so any version >= 2.7 will work. what do you think @shilman ?

So then we would drop support for Vue <2.7. 
Do you know how many people still use storybook for that version @shilman ?

**Comment by shaniqwa-drm** [comment]
I experience the same issue, using vue3 & @storybook/vue3

**Comment by qnp** [comment]
@mokone91, facing this issue, given the @GrtDev solution, I did not manage to make it a decorator unfortunately because I did not manage to hook in the decorator’s `storyFn` returned object.

Yet, based on that idea, I use a wrapper to author stories (I use the `mounted` lifecycle hook in order to get the current instance):
```ts
import type { StoryFn } from '@storybook/vue';
import type { ComponentOptions } from 'vue';

export function storyWrapper<ArgsT>(storyFn: StoryFn<ArgsT>): StoryFn<ArgsT> {
  type ComponentInstance = Vue & { args: ArgsT };
  let storyComponent: ComponentOptions<Vue> | null = null;
  let currentInstance: ComponentInstance | null = null;

  const wrappedStory: StoryFn<ArgsT> = (storyArgs, storyContext) => {
    if (storyComponent && currentInstance) {
      currentInstance.args = storyArgs;
      currentInstance.$forceUpdate();
      return storyComponent;
    }
    storyComponent = (storyFn(storyArgs, storyContext) ??
      {}) as ComponentOptions<Vue>;
    storyComponent.mounted = function() {
      currentInstance = this as ComponentInstance;
    };
    return storyComponent;
  };
  return wrappedStory;
}
```
which is used very nicely like this:
```ts
const Template = storyWrapper<LogoProps>(args => ({
  components: { Logo },
  setup: () => ({ args }),
  template: '<Logo v-bind="args" />',
}));

export const Light = Template.bind({});
Light.args = {
  variant: 'light'
};

export const Dark = Template.bind({});
Dark.args = {
  variant: 'dark'
};
```

**Comment by qnp** [comment]
@mokone91, facing this issue, given the @GrtDev solution, I did not manage to make it a decorator unfortunately because I did not manage to hook in the decorator’s `storyFn` returned object.

Yet, based on that idea, I use a wrapper to author stories:
```ts
import { getCurrentInstance } from 'vue';

import type { StoryFn } from '@storybook/vue';
import type { ComponentOptions } from 'vue';

export function defineStory<ArgsT>(storyFn: StoryFn<ArgsT>): StoryFn<ArgsT> {
  type ComponentInstance = Vue & { args: ArgsT };
  let storyComponent: ComponentOptions<Vue> | null = null;
  let currentInstance: ComponentInstance | null = null;

  const wrappedStory: StoryFn<ArgsT> = (storyArgs, storyContext) => {
    if (storyComponent && currentInstance) {
      currentInstance.args = storyArgs;
      currentInstance.$forceUpdate();
    }
    storyComponent = (storyFn(storyArgs, storyContext) ??
      {}) as ComponentOptions<Vue>;

    const originalSetup = storyComponent.setup;
    storyComponent.setup = function(setupProps, setupContext) {
      currentInstance = getCurrentInstance()?.proxy as ComponentInstance;
      return originalSetup?.(setupProps, setupContext);
    };

    return storyComponent;
  };

  return wrappedStory;
}

```
which is used very nicely like this:
```ts
const Template = storyWrapper<LogoProps>(args => ({
  components: { Logo },
  setup: () => ({ args }),
  template: '<Logo v-bind="args" />',
}));

export const Light = Template.bind({});
Light.args = {
  variant: 'light'
};

export const Dark = Template.bind({});
Dark.args = {
  variant: 'dark'
};
```

I have to mention @GrtDev, using this wrapper solution was breaking the reactivity in stories themselves (here in the example when switching between "Light" and "Dark" story nothing happened) because the early return 
```
    if (component && currentInstance?.proxy) {
        ...
        return component;
    }
```
was preventing to use properly any newly created instances. So in my implementation I don't have this early return.

**Comment by shaniqwa-drm** [comment]
is there anything new with this issue ? an I suppose to refactor all my stories to use the suggested workarounds?

**Comment by valentinpalkovic** [comment]
As already mentioned, Vue 2 support will be discontinued in Storybook 8, which is scheduled for release in the coming weeks. This decision was made to streamline our development process and focus on supporting the latest technologies. 

### Support for Vue 2 in Storybook 7

To ensure a smooth transition, we will continue to provide security patches and highly upvoted bug fixes for Storybook 7. However, we strongly recommend migrating to Vue 3 or a later version as soon as possible to take advantage of the latest features and improvements.

I am closing this ticket as not planned.

**Comment by shaniqwa-drm** [comment]
@valentinpalkovic this issue happens to me using the latest vue3 & storybook versions. it started after I migrated from storybook 6 to 7, and now in 8, it's sill like this... I have tried double-checking every configuration. should I open a new bug ?

**Comment by valentinpalkovic** [comment]
Hi @shaniqwa-drm 

Yes! Please create a new bug report.

**Comment by shaniqwa-drm** [comment]
opened https://github.com/storybookjs/storybook/issues/26876
