### ISSUE TITLE
[Bug]: TypeError: _addons.default.getChannel is not a function

### ISSUE THREAD

**Issue by yairEO** [storybookjs/storybook#22220]
### Describe the bug

I am trying to upgrade my workplace's Storybook from v6.5 to v7 (took me weeks just to upgrade to v6.5 a year ago).

Using custom [webpack 5 configuration `main.js`](https://github.com/yairEO/sb-6.5-to-7-issue/blob/main/.storybook/main.js)

I am getting this error:

```
TypeError: _addons.default.getChannel is not a function
    at http://localhost:9001/vendors-node_modules_babel_runtime_helpers_esm_asyncToGenerator_js-node_modules_babel_runtime-596a72.iframe.bundle.js:41268:24
    at decorators (http://localhost:9001/main.iframe.bundle.js:321:81)
    at hookified (http://localhost:9001/sb-preview/runtime.mjs:7:17032)
    at http://localhost:9001/sb-preview/runtime.mjs:34:1454
    at http://localhost:9001/sb-preview/runtime.mjs:34:2116
    at http://localhost:9001/sb-preview/runtime.mjs:7:17849
    at unboundStoryFn (http://localhost:9001/sb-preview/runtime.mjs:34:3333)
    at renderWithHooks (http://localhost:9001/vendors-node_modules_babel_runtime_helpers_esm_asyncToGenerator_js-node_modules_babel_runtime-596a72.iframe.bundle.js:31749:157)
    at mountIndeterminateComponent (http://localhost:9001/vendors-node_modules_babel_runtime_helpers_esm_asyncToGenerator_js-node_modules_babel_runtime-596a72.iframe.bundle.js:32088:872)
    at beginWork (http://localhost:9001/vendors-node_modules_babel_runtime_helpers_esm_asyncToGenerator_js-node_modules_babel_runtime-596a72.iframe.bundle.js:32332:93)
```

![image](https://user-images.githubusercontent.com/845031/233858327-199af5d2-ab53-4675-8b82-7c09f462a72c.png)

Only the `@storybook/addon-mdx-gfm` addon is [being used](https://github.com/yairEO/sb-6.5-to-7-issue/blob/main/.storybook/main.js#L7).

I have left only a single story and simplified it. Might be related to issue #20971

### To Reproduce

https://github.com/yairEO/sb-6.5-to-7-issue

### System

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
  Binaries:
    Node: 16.20.0 - ~\AppData\Local\Volta\tools\image\node\16.20.0\node.EXE
    npm: 8.19.4 - ~\AppData\Local\Volta\tools\image\node\16.20.0\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (112.0.1722.58)
  npmPackages:
    @storybook/addon-essentials: 7.0.6 => 7.0.6
    @storybook/addon-knobs: 7.0.0 => 7.0.0
    @storybook/addon-mdx-gfm: 7.0.6 => 7.0.6
    @storybook/addon-storysource: 7.0.6 => 7.0.6
    @storybook/mdx2-csf: 1.0.0 => 1.0.0
    @storybook/react: 7.0.6 => 7.0.6
    @storybook/react-webpack5: 7.0.6 => 7.0.6
    @storybook/source-loader: 7.0.6 => 7.0.6
```

### Additional context

I have simplified the code as much as possible, as this is my workplace's components' repository code and I've only left 1 story and removed unrelated packages (from `package.json`).

**Comment by shilman** [comment]
The addons package [no longer has a default export](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#no-more-default-export-from-storybookaddons). This means one of the addons you're using (possibly some residual install in your node_modules folder?) is outdated.

Please try removing your addons from `.storybook/main.js` and adding them back one by one until you isolate the problem. If the addon needs an update, [please file an issue on the appropriate repo](https://github.com/storybookjs/storybook/issues/20529).

**Comment by yairEO** [comment]
Hello dear hard-working @shilman - I've already did the legwork and learnt this before opening the issue, and also wrote in my post (above) regarding my addons used in `main.js`:

> *Only the @storybook/addon-mdx-gfm addon is [being used](https://github.com/yairEO/sb-6.5-to-7-issue/blob/main/.storybook/main.js?rgh-link-date=2023-04-23T19%3A00%3A48Z#L7).*

I've tried removing also the `addon-mdx-gfm` addon without luck.

**Comment by shilman** [comment]
@yairEO Sorry I missed that! I looked at your repo and it looks like you're still using `storybook-readme` even though it's not listed in your `addons` settings:

https://github.com/yairEO/sb-6.5-to-7-issue/blob/main/.storybook/index.js#L2-L3

I checked the source and it's using the old API:

https://github.com/tuchk4/storybook-readme/blob/master/packages/storybook-readme/src/index.js#L2

**Comment by yairEO** [comment]
I'll be damned Shilman you're the man! (it was actually in `preview.js`).

I feel like an idiot for have wasted your time!
was just so focused on the addons that I completely forgot there can be addons which are not defined as part of `main.js` configuration. 

Hopefully this issue will be a beacon to those with similar problem and your wise counsel will save countless headaches. 

---

The lesson of this ticket: search in your codebase **each and every** Storybook-related node package to eliminate any possible usage of a "bad" package tainting everything.

Thanks again to the super-busy-but-nicest-guy Shilman who dedicates his life to the crusade of Storybook. Here are some flowers for you - 💐💐💐

**Comment by shilman** [comment]
Happens to all of us @yairEO !! Still a long way to go to get Storybook to the point where these things are easier to debug. But we're working on it!
