### ISSUE TITLE
[Bug]: storybook does not open automatically in v7

### ISSUE THREAD

**Issue by probablyup** [storybookjs/storybook#22234]
### Describe the bug

Previously in v6, storybook used to open a browser tab automatically when the build completed. There is still some CLI documentation that implies it's meant to be happening in the v7 docs:

```
--no-open | Do not open Storybook automatically in the browser
```

(from https://storybook.js.org/docs/react/api/cli-options)

But it hasn't opened for me automatically ever since upgrading in any of the betas and the current stable releases of v7.

### System

```shell
System:
    OS: macOS 13.3.1
    CPU: (12) arm64 Apple M2 Pro
  Binaries:
    Node: 16.20.0 - ~/Library/Caches/fnm_multishells/59430_1681325587831/bin/node
    Yarn: 3.5.0 - /opt/homebrew/bin/yarn
    npm: 8.19.4 - ~/Library/Caches/fnm_multishells/59430_1681325587831/bin/npm
  Browsers:
    Chrome: 112.0.5615.137
    Safari: 16.4
```

### Additional context

Nothing has changed about my environment, and I still have an active v6 branch on my current machine that exhibits the expected behavior.

**Comment by shilman** [comment]
Do you have a reproduction? It is opening the browser for me:

```
Environment Info:

  System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    Yarn: 3.5.0 - /usr/local/bin/yarn
    npm: 8.15.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 112.0.5615.137
    Safari: 16.4
```

**Comment by usrrname** [comment]
Usually the -o flag on the cli command induces an opening... is there something else in your setup preventing this?

**Comment by probablyup** [comment]
> Usually the -o flag on the cli command induces an opening... is there something else in your setup preventing this?

Is that new undocumented behavior? See the OP

**Comment by usrrname** [comment]
@probablyup my mistake: I conflated that with another framework; `-o` in SB defines the output dir for the static build. 

That is truly puzzling behaviour! 

My settings:
```
Environment Info:

  System:
    OS: macOS 13.0
    CPU: (8) x64 Apple M2
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
  Browsers:
    Chrome: 112.0.5615.137
    Firefox: 87.0
    Safari: 16.1
 ```
 Been trying out 7.0.6 on `@storybook/html` and react projects... both are opening on build success with `storybook dev -p 3000` or `storybook dev -p 6006`

**Comment by probablyup** [comment]
I don’t usually explicitly pass the port, will see if that affects anything.

**Comment by platzhersh** [comment]
Same issue here, using storybook `7.0.12` on node `18.12.1` on a macbook
