### ISSUE TITLE
[Bug]: `showName` is deprecated as `name` will stop having dual purposes in the future. Please specify a `title` in `globalTypes` instead.

### ISSUE THREAD

**Issue by magnattic** [storybookjs/storybook#22245]
### Describe the bug

I updated to Storybook 7 (v7.0.6) and got the following warning in the console:

> `showName` is deprecated as `name` will stop having dual purposes in the future. Please specify a `title` in `globalTypes` instead.

This is my `globalTypes` config from `preview.tsx`:

```
  globalTypes: {
    theme: {
      name: 'Theme',
      description: 'Global UrbyoTheme',
      defaultValue: UrbyoTheme.Light,
      toolbar: {
        icon: 'mirror',
        items: [UrbyoTheme.Light, UrbyoTheme.Dark],
        dynamicTitle: true,
      },
    },
  },
```

Switching `name` to `title` did not help.

I searched the migration docs but found nothing there, what am I doing wrong?

### System

```shell
Environment Info:

  System:
    OS: Linux 5.15 Ubuntu 22.10 22.10 (Kinetic Kudu)
    CPU: (16) x64 AMD Ryzen 7 PRO 5850U with Radeon Graphics
  Binaries:
    Node: 18.3.0 - ~/.nvm/versions/node/v18.3.0/bin/node
    Yarn: 3.5.0 - ~/.nvm/versions/node/v18.3.0/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v18.3.0/bin/npm
  Browsers:
    Chrome: 106.0.5249.119
```

**Comment by 365kim** [comment]
I'm experiencing the same issue. 🥲

```
    "@storybook/addon-a11y": "7.0.2",
    "@storybook/addon-docs": "7.0.2",
    "@storybook/addon-essentials": "7.0.2",
    "@storybook/addon-links": "7.0.2",
    "@storybook/addon-viewport": "7.0.2",
    "@storybook/blocks": "7.0.2",
    "@storybook/react": "7.0.2",
    "@storybook/react-vite": "7.0.2",
    "@storybook/types": "7.0.2",
```

**Comment by magnattic** [comment]
Good catch, that fixed it.

This should really be mentioned in the docs, the example here doesn't set title either: https://storybook.js.org/docs/react/essentials/toolbars-and-globals#global-types-and-the-toolbar-annotation

**Comment by jonniebigodes** [comment]
@magnattic, thanks for reaching out to us with your issue regarding the documentation and wanted to let you know that a pull request is already up addressing it. Sorry for the confusion here, but will all the changes introduced with Storybook 7.0, this small change must have gotten lost in the mix. Once it's merged, it should be available in the official documentation shortly.

Hope you have a great day.

Stay safe

**Comment by gilbarbara** [comment]
Hey @jonniebigodes 
Since `showName` was removed, how do I hide the name/title?
I've tried to set an empty string to both, but it used the globalTypes object key instead.
