### ISSUE TITLE
[Bug]: Unable to render MDX docs for stories in Storybook/HTML (v7) 

### ISSUE THREAD

**Issue by basher** [storybookjs/storybook#22249]
### Describe the bug

I'm unable to associate MDX files to their related component stories, after migrating from Storybook/HTML V6.5 to V7, using the new MDX2 docs API, as documented in https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#70-docs-changes.

I've created a repro using a fresh install of Storybook/HTML, and trying to add a `Button.mdx` file to the Button story.

I get the following error for the new MDX file, and no docs are shown for button component:

![mdx](https://user-images.githubusercontent.com/452809/234280595-e9355471-7b32-471b-b8a3-684f4b44cd7e.PNG)

If I remove the `<Meta>` tag, I get the same error, with the new MDX docs placed outside the Button folder.
The original auto-generated Button docs are shown again inside the Button folder.

### To Reproduce

https://github.com/basher/storybook7-html-minimal

### System

```shell
Environment Info:

  System:
    OS: Windows 10 10.0.19045
    CPU: (4) x64 Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz   
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE        
    npm: 9.6.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 112.0.5615.138
    Edge: Spartan (44.19041.1266.0), Chromium (112.0.1722.58)
  npmPackages:
    @storybook/addon-a11y: ^7.0.7 => 7.0.7
    @storybook/addon-essentials: ^7.0.7 => 7.0.7
    @storybook/addon-links: ^7.0.7 => 7.0.7
    @storybook/blocks: ^7.0.7 => 7.0.7
    @storybook/html: ^7.0.7 => 7.0.7
    @storybook/html-vite: ^7.0.7 => 7.0.7
```

**Comment by shilman** [comment]
Try changing the story reference to 

```
<Story of={Button.Primary} />
```

**Comment by basher** [comment]
Thanks Michael.
I had already tried that, but I didn't get the code view or story args showing.

What is the correct approach to show both code view and custom markdown docs?

In v6.5 I do the following:
```
<Preview>
    <Story id="components-button--button" />
</Preview>
```

# To summarise the issue in V7

## 1. With `<Meta>`

![MDX with meta](https://user-images.githubusercontent.com/452809/235098412-83b041f1-1f1b-4a13-b77e-64cb2feb00ee.png)

![MDX with meta Storybook](https://user-images.githubusercontent.com/452809/235098437-c8696564-b005-40f7-96eb-5013df6f146d.png)


## 2. Without `<Meta>`

![MDX without meta Storybook](https://user-images.githubusercontent.com/452809/235098488-cd87db0e-273a-471d-991b-8e0d9f854c10.png)

**Comment by usrrname** [comment]
Have you tried using the `Markdown` docs block? https://storybook.js.org/docs/html/api/doc-block-markdown

**Comment by basher** [comment]
Hmmm... I'm confused as to why I would need to use markdown docs block?

I've also looked at https://storybook.js.org/docs/html/api/doc-block-story for a different approach.

I can't get anything to work in V7 which gives me the equivalent docs experience as V6.5.

Here's a working Storybook/HTML V6.5 repo, which I want to upgrade to V7:
https://github.com/basher/Web-UI-Boilerplate

**Comment by basher** [comment]
Tried again today, after bumping to Storybook/HTML V7.2.0.

I now have MDX docs, showing:
- custom markdown
- args table
- controls table

But I still cannot see a "**show code**" button.

## Button.mdx
```
import { Meta, ArgTypes, Controls, Story } from '@storybook/blocks';
import * as Button from './Button.stories';

<Meta of={Button} />

## Story args
<ArgTypes />

## Story controls
<Controls />

## Primary
- Extra Markdown docs...

<Story of={Button.Primary} />

## Secondary
- Extra Markdown docs...

<Story of={Button.Secondary} />
```

## Rendered docs in Storybook
![storybook v7](https://github.com/storybookjs/storybook/assets/452809/a37bf044-5d5a-4549-9cd9-38492d754630)

**Comment by basher** [comment]
@nickpoulos 

Are you using Storybook/HTML?

My minimal repo was updated a few weeks ago... I bumped to latest version of Storybook 7, and I updated my test button story code to use a template literal in the `render()` function.

- The button story renders OK.
- The MDX renders OK, but still does NOT have a "**show code**" button", just like the screenshot in my previous comment.

Story:
https://github.com/basher/storybook7-html-minimal/blob/main/stories/Components/Button.stories.js

MDX:
https://github.com/basher/storybook7-html-minimal/blob/main/stories/Components/Button.mdx

**Comment by basher** [comment]
I have now fixed ALL my MDX issues in my minimal repo. 

The missing bit was the `<Source of={Button.TextButton} />` to render the source HTML code.

Complete fixed MDX file = https://github.com/basher/storybook7-html-minimal/blob/main/stories/Components/Button.mdx

My simple button docs page now correctly shows:
- story args
- story controls
- custom markdown docs
- rendered component
- source HTML code

![sb7](https://github.com/storybookjs/storybook/assets/452809/26e18103-c1d0-4f0c-a0b3-023f87d53bf8)
