### ISSUE TITLE
[Bug]: @storybook/nextjs not loading google fonts with 3 words in name

### ISSUE THREAD

**Issue by msadura** [storybookjs/storybook#22248]
### Describe the bug

Google font is not loaded correctly when it has more than 2 words (parts) in name. Loaded font's `className` and `variable` have space in name and do not work probably because of that.

import font code:
```
import { PT_Sans_Narrow } from 'next/font/google';

export const font = PT_Sans_Narrow({
  subsets: ['latin'],
  variable: '--font-family-sans',
  fallback: ['Georgia', 'ui-serif', 'serif'],
  weight: ['400', '700']
});
```

output:

```
{
    "className": "pt-sans narrow-normal",
    "style": {
        "fontFamily": "PT Sans Narrow",
        "fontStyle": "normal"
    },
    "variable": "__variable_pt-sans narrow-normal"
}
```

Fonts with 1 or 2-part names works, looks like 3rd part gets space instead of `-` in className

### To Reproduce

https://github.com/msadura/sb-google-font-bug-repro/tree/main/nextjs/default-ts

start sotrybook and check console log from `preview.ts` - google font `className` and  `variable` are incorrect.

### System

```shell
System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 18.12.1 - ~/.asdf/installs/nodejs/18.12.1/bin/node
    Yarn: 1.22.19 - ~/node_modules/.bin/yarn
    npm: 8.19.2 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Chrome: 112.0.5615.137
    Firefox: 112.0.1
    Safari: 16.2
  npmPackages:
    @storybook/addon-essentials: ^7.0.6 => 7.0.6 
    @storybook/addon-interactions: ^7.0.6 => 7.0.6 
    @storybook/addon-links: ^7.0.6 => 7.0.6 
    @storybook/blocks: ^7.0.6 => 7.0.6 
    @storybook/nextjs: ^7.0.6 => 7.0.6 
    @storybook/react: ^7.0.6 => 7.0.6 
    @storybook/testing-library: ^0.0.14-next.2 => 0.0.14-next.2 

nextjs version: 13.2, 13.3.1
```

**Comment by u840903** [comment]
Just spent two hours on figuring out why IBM Plex Sans didn't work. 
https://fonts.google.com/specimen/IBM+Plex+Sans

**Comment by shilman** [comment]
Cc @valentinpalkovic

**Comment by ygkn** [comment]
Hi, I have found workarounds and why this issue causes.

### Workaround

Although the className has spaces and doesn't work, the font itself still be loaded. So you can directly refer to the `font-family` in CSS. Here's an example using decorators:

```ts
decorators: [
  (story) => (
    <div className={font.className}>
      <style>{`
        /* for className method */
        ${font.className.split(" ")[0]} {
          font-family: 'PT Sans Narrow';
          font-style: normal;
        }

        /* for variable method */
        html /* and any selectors */ {
          --font-family-sans: ${font.style.fontFamily};
        }
      `}</style>
      {story()}
    </div>
  ),
],
```

### Why

The issue originates from the `getClassName` function in [`get-css-meta.ts`](https://github.com/storybookjs/storybook/blob/next/code/frameworks/nextjs/src/font/webpack/loader/utils/get-css-meta.ts#L40), specifically in the line `const font = fontFamily.replace(' ', '-').toLowerCase();`. The `replace` method only replaces a single space, causing the problem.

### How to fix

To fix the bug, you can replace `replace` with either `replaceAll` (I prefer this) or `replace(/ /g, '-')` to replace all spaces.

Would it be alright if I submit a pull request with the fix?
Thanks you.

**Comment by ygkn** [comment]
I read [Code contributions](https://storybook.js.org/docs/react/contribute/code) document　and open PR #23121.
