### ISSUE TITLE
Storyshots Migration

### ISSUE THREAD

**Issue by kylegach** [storybookjs/storybook#22263]
Related discussion: https://github.com/storybookjs/storybook/discussions/22520#discussioncomment-5875659

With the release of the test runner package, the famous testing package storyshots is now mostly deprecated and will not receive any changes / improvements. 

In our documentation, we're still mentioning how to enable snapshot testing with the said package, and we're at a point where we should start consolidating all the testing patterns around the test runner. For reference, here's the [example](https://github.com/storybookjs/storybook/issues/14525#issuecomment-1386217514) response that the Storybook team sent out while triaging storyshots issues. 

What needs to happen:
- Update the documentation [here](https://storybook.js.org/docs/react/writing-tests/snapshot-testing) to be a migration guide to snapshot testing with the test runner as opposed to a how-to guide for the storyshots package.

**Comment by joriswitteman** [comment]
Will this include a way to replace the different controls settings variations coverage that StoryShots offered?
