### ISSUE TITLE
Content audit for outdated references

### ISSUE THREAD

**Issue by kylegach** [storybookjs/storybook#22275]
Per an internal team conversation, it would be in our best interest to cycle through the content we released for outdated references no longer aligned with Storybook 7 way (e.g., main.js, etc.). 

What needs to happen:
- Cycle through the marketing content available (Storybook blog, Chromatic blog) and verify that the breaking changes related to Storybook are referenced. 

To avoid introducing misconceptions, only content related to Storybook 7.x alpha should be vetted and updated.

**Comment by jonniebigodes** [comment]
Closing this as the final changes will be up shortly.
