### ISSUE TITLE
[Documentation]: API docs for `componentWrapperDecorator` and `moduleMetadata`

### ISSUE THREAD

**Issue by winkerVSbecks** [storybookjs/storybook#22289]
### Describe the problem

To write Angular specific decorators we need to use the `componentWrapperDecorator` and `moduleMetadata` utilities from `@storybook/angular`. However, these utils are not documented which makes it hard to figure out their API. 

For example, [docs/angular/writing-stories/decorators](https://storybook.js.org/docs/angular/writing-stories/decorators#page-top) has several examples but none that show how to access context within a decorator. I had to look at the Angular sandbox to find this example:

```
import type { Preview, StoryContext } from '@storybook/angular';
import { setCompodocJson } from '@storybook/addon-docs/angular';
import { componentWrapperDecorator } from '@storybook/angular';
import docJson from '../documentation.json';
setCompodocJson(docJson);

const preview: Preview = {
  parameters: {
    actions: { argTypesRegex: '^on[A-Z].*' },
    controls: {
      matchers: {
        color: /(background|color)$/i,
        date: /Date$/,
      },
    },
  },
  globalTypes: {
    myvar: {
      name: 'My Var',
      defaultValue: 'a',
      toolbar: {
        icon: 'globe',
        items: ['a', 'b', 'c'],
        showName: true,
        dynamicTitle: true,
      },
    },
  },
  decorators: [
    componentWrapperDecorator(
      (story) => `<div [class]="myTheme">${story}</div>`,
      ({ globals }) => {
        return { myTheme: globals['myvar'] };
      }
    ),
  ],
};

export default preview;
```

### Additional context

TBH the docs for other frameworks also don't show how to access `context` in a decorator: https://storybook.js.org/docs/react/writing-stories/decorators

**Comment by etgeorge** [comment]
I spent all of yesterday trying to figure out how to access context within Angular, thank you for bringing this to light!

**Comment by dmy-leanix** [comment]
Nice! Just was searching for this

**Comment by tomatemeo** [comment]
This is still an issue. This here worked, thanks so much! 👍 
The original documentation for preview / global decorators is still very misleading, implying that `componentWrapperDecorator` takes one function argument that gets passed two parameters, however, this does not work for access to `globalTypes`.
