### ISSUE TITLE
[Bug]: Angular applicationConfig API Cannot read properties of null

### ISSUE THREAD

**Issue by jonniebigodes** [storybookjs/storybook#22283]
### Describe the bug

While applying the required changes for the Angular version of the Intro to Storybook tutorial, we currently maintain [here](https://storybook.js.org/tutorials/intro-to-storybook/angular/en/get-started/), more specifically, the [Screen section](https://storybook.js.org/tutorials/intro-to-storybook/angular/en/screen/), I ran into an issue with the new `applicationConfig` API introduced with Storybook 7.0, it appeared to work up until the point where I navigated from the `Default` to the `Error` story and the following error appears:

![SB-7-0-Error-provider](https://user-images.githubusercontent.com/22988955/234839656-782ee29d-72fb-4eca-ace8-2fcc07008c0c.png)

Refreshing the page seems to resolve it, and the component will render as it should. We'll need to investigate a bit further and see where the actual issue lies and how to solve it to prevent users from having to manually refresh their browsers in order to verify that their components render correctly.

Based on a cursory search around the issue tracker, I was able to verify that a similar issue is already present that we need to account for on top of this issue (i.e., #22185).

### To Reproduce

- Open the Chromatic deployment and select the `Error` story, and the error will present itself.
- Refresh the browser, and the error goes away.

### System

```shell
N/A
```

### Additional context

For context, I've set up a code repository [here](https://github.com/jonniebigodes/testing-intro-storybook-angular-template-sb-7) and a Chromatic deployment [here](https://6442ff86d95353880ab5d3a3-crqafyhqca.chromatic.com/?path=/story/pureinboxscreen--default).

**Comment by valentinpalkovic** [comment]
@jonniebigodes After doing some investigations, I reproduced the bug without Storybook. I will open a PR to fix the issue in ngxs itself.

**Comment by valentinpalkovic** [comment]
Update: Waiting for https://github.com/ngxs/store/pull/2002 being released

**Comment by jonniebigodes** [comment]
Closing as it's already solved with the latest release of the package and verified on the latest changes of the Intro to Storybook. Thanks for taking a look into this @valentinpalkovic. Appreciate it 🙏
