### ISSUE TITLE
[Bug]: upgrading to 7.0.7 breaks app start/compile

### ISSUE THREAD

**Issue by JeffreyStevens** [storybookjs/storybook#22288]
### Describe the bug

Running the `npx storybook@latest upgrade` upgraded to 7.0.7 but `@storybook/addon-actions` causes the following error (reverting just @storybook/addon-actions to 7.0.6 fixes the issue) when attempting to start/compile my app:

![sb-addon](https://user-images.githubusercontent.com/34170674/234879906-63648dde-529e-43b4-91b3-a3775c7dce74.png)

### System

```shell
m087610:sts-react (develop) ✔ npx storybook@latest info

Environment Info:

  System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M1 Pro
  Binaries:
    Node: 20.0.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.6.4 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 112.0.5615.137
    Edge: 112.0.1722.58
    Safari: 16.4
  npmPackages:
    @storybook/addon-a11y: ^7.0.7 => 7.0.7 
    @storybook/addon-actions: 7.0.6 => 7.0.6 
    @storybook/addon-console: ^1.2.3 => 1.2.3 
    @storybook/addon-docs: ^7.0.7 => 7.0.7 
    @storybook/addon-essentials: ^7.0.7 => 7.0.7 
    @storybook/addon-interactions: ^7.0.7 => 7.0.7 
    @storybook/addon-links: ^7.0.7 => 7.0.7 
    @storybook/addon-mdx-gfm: ^7.0.7 => 7.0.7 
    @storybook/addon-viewport: ^7.0.7 => 7.0.7 
    @storybook/addons: ^7.0.7 => 7.0.7 
    @storybook/jest: ^0.1.0 => 0.1.0 
    @storybook/preset-create-react-app: ^7.0.7 => 7.0.7 
    @storybook/react: ^7.0.7 => 7.0.7 
    @storybook/react-webpack5: ^7.0.7 => 7.0.7 
    @storybook/test-runner: ^0.10.0 => 0.10.0 
    @storybook/testing-library: 0.1.0 => 0.1.0 
    @storybook/theming: ^7.0.7 => 7.0.7 
    @storybook/types: ^7.0.7 => 7.0.7
```

**Comment by shilman** [comment]
@JeffreyStevens Do you a have a reproduction repo you can share? If not, can you create one? Go to https://storybook.new or see [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce).

@ndelangen it looks like it's very likely due to this PR https://github.com/storybookjs/storybook/pull/22175

**Comment by shilman** [comment]
¡Ay Caramba!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.1.0-alpha.12 containing PR #22261 that references this issue. Upgrade today to the `@future` NPM tag to try it out!

```
npx sb@next upgrade --tag future
```
