### ISSUE TITLE
[Feature Request]: Exclude story, but still able to use in MDX

### ISSUE THREAD

**Issue by MatthijsBon** [storybookjs/storybook#22302]
### Is your feature request related to a problem? Please describe

I've seen [the option to exclude stories](https://storybook.js.org/docs/react/api/csf#non-story-exports) from being exported. From what I gather, they're not actually omitted from the module exports, but simply not handled as stories (and processed that way). 

I wanted to use this functionality so that I could export "normal" stories to showcase the more complex variants of a component, and exclude the very simples stories that I only want to use in a mdx file, to showcase the button.

Concrete example:
```
// Button.stories.tsx

const meta {
  ...
  excludeStories: /Docs*/,
};

export default meta;

export const ComplexStory = ...;

export const DocsPrimaryButton = {
  args: {
    variant: "primary",
  },
}

```

```
// Button.mdx

import { Meta, Primary, Controls, Title, Description, Story } from '@storybook/blocks';
import * as ButtonStories from './Button.stories';

<Meta of={ButtonStories} />
<Title />
<Description />
<Primary />

## Usage
Buttons allows users to execute a certain action. Buttons can come in different variants, each one indicating a certain intent. The button has no internal state, but it does handle hover behaviour using css.

## Props
<Controls />

## Variants
Variants of the button are mutually exclusive and are used to indicate the intent of the button.

### Primary
The primary button is the default variant of the button. When in doubt, use primary.
<Story of={ButtonStories.DocsPrimary} />
```

This last line is where Storybook fails me, as it's telling me (probably correct):
```
Invalid value passed to the 'of' prop. The value was resolved to a 'component or unknown' type but the only types for this block are: story.
- Did you pass a component to the 'of' prop when the block only supports a story or a meta?
- ... or vice versa?
- Did you pass a story, CSF file or meta to the 'of' prop that is not indexed, ie. is not targeted by the 'stories' globs in the main configuration?
```

I'm not sure what is the cause of this, but I assume the `DocsPrimary` story is not exported as a full story, or not processed as such, which is why the `<Story of={DocsPrimary} />` doesn't work. 

### Describe the solution you'd like

Ideally, the `excludeStories` works more as a `hideStories`, like I described above. These exports will be handled as a story if possible and as a normal export if not (so the Data example in the docs still works as intended).

I have no idea how to implement this. I have little experience with contributing to OpenSource projects. However, I would be able to invest some time if necessary, given some pointers.

### Describe alternatives you've considered

Right now, my workaround is to just export these stories anyway, but it just clutters the Button stories, as I'm now also exporting stories that are very simple.

### Are you able to assist to bring the feature to reality?

yes, I can

### Additional context

These are our relevant dependencies, in case any of them clash or could cause problems:
```
{
    "@storybook/addon-essentials": "^7.0.2",
    "@storybook/addon-interactions": "^7.0.2",
    "@storybook/addon-links": "^7.0.2",
    "@storybook/blocks": "^7.0.2",
    "@storybook/react": "^7.0.2",
    "@storybook/react-vite": "^7.0.2",
    "storybook": "^7.0.2",
    "typescript": "^5.0.3",
    "vite": "^4.2.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "@vitejs/plugin-react": "^3.1.0",
}
```

**Comment by shilman** [comment]
Hi @MatthijsBon! Thanks for filing this. We're aware of the issue and have a solution planned as part of 7.1. In the meantime, we don't have a workaround, unfortunately.

**Comment by lentilz** [comment]
As a potential work around for this, is there a way to support passing args to the `<Story />` block? I'm aware this has been deprecated in 7.0+ per https://storybook.js.org/docs/vue/api/doc-block-story#args-deprecated however it would be great to be able to show variants of a Story in .mdx with the story block without needing to create separate story exports that display in the sidebar.

ie: Opposed to `<Story of={Tags.Green} />` I'd prefer `<Story of={Tags.Primary} args={background: 'green'} />`

In v6.5, it was great to be able to display all variants in a single Canvas block like below, but again, [this has also been deprecated](https://storybook.js.org/docs/vue/api/doc-block-canvas).
```
<Canvas>
    <Story 
        name="Default"
        args={{
            classes: 'button-default',
            text: 'Default'
        }}>
        {Template.bind({})}
    </Story>
    <Story 
        name="Disabled State"
        args={{
            classes: 'button-default',
            text: 'Disabled State',
            disabled: true
        }}>
        {Template.bind({})}
    </Story>
</Canvas>
```

**Comment by duncan-thacker** [comment]
Just to add - our 6.x Storybook instance uses handcrafted MDX docs only and doesn't contain any CSF stories, so the removal of the ability to do inline `<Canvas>` demos means we have 2 choices:

1. Flood our navigation tree with an extra 200+ nodes that are all surplus to requirements, or
2. Write our own `<Canvas>` element that is exactly the same as 6.x, but lacks the ability to show the source.

We'll probably go with option 2 but either is a big downgrade for our users. I find it hard to believe that we're the only "docs-only" Storybook team out there!

**Comment by blabute** [comment]
Hello! Thanks for this awesome package 🎉 

Any word on when this will be addressed? It appears that Storybook 7.1 has been released but we are still running into the same issue.

**Comment by jwilliams-met** [comment]
Bump

**Comment by enableds** [comment]
Bump?

**Comment by shilman** [comment]
FWIW this is mostly possible to roll by hand in the latest stable version of Storybook. I've created a throwaway demo project here to play with some ideas: https://github.com/shilman/storybook-tag-filtering

All feedback welcome!

**Comment by shilman** [comment]
RFC here https://github.com/storybookjs/storybook/discussions/25535
Implemented here https://github.com/storybookjs/storybook/pull/25328

**Comment by designbyadrian** [comment]
@jwilliams-met, @enableds 

Please don't dirty the thread by commenting "bump" or "+1". Use the +1 reaction on the main post instead. That's how maintainers can organise issues by popularity.
