### ISSUE TITLE
storybook init: Issues with PackageManager proxies

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#22343]
Many users are experiencing errors when running `storybook init`, which originate from the following:

- NPMProxy.installDependencies
- NPMProxy.executeCommand
- Yarn1Proxy.installDependencies
- Yarn1Proxy.addDependencies
- Yarn2Proxy.addDependencies
- PNPMProxy.installDependencies

The error message is always empty, which should be improved, but we should also investigate in which scenarios this happens, so we can fix it or provide a suggestion for the user in the error message if the error is legit.

**Comment by shilman** [comment]
Good golly!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.1.0-alpha.14 containing PR #22401 that references this issue. Upgrade today to the `@future` NPM tag to try it out!

```
npx sb@next upgrade --tag future
```

**Comment by shilman** [comment]
Yo-ho-ho!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.10 containing PR #22401 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb@latest upgrade
```

**Comment by shilman** [comment]
Egads!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.1.0-alpha.20 containing PR #22554 that references this issue. Upgrade today to the `@future` NPM tag to try it out!

```
npx sb@next upgrade --tag future
```
