### ISSUE TITLE
storybook init: Detach automigrate from init

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#22346]
Error location: [automigrate](https://github.com/storybookjs/storybook/blob/next/code/lib/cli/src/automigrate/index.ts#L92)

Suggested work:

This is a bug where the `fixes` object from running automigration is not an object. It seems to be related to [these](https://github.com/storybookjs/storybook/blob/next/code/lib/cli/src/automigrate/index.ts#L160) [early](https://github.com/storybookjs/storybook/blob/next/code/lib/cli/src/automigrate/index.ts#L175) [bails](https://github.com/storybookjs/storybook/blob/next/code/lib/cli/src/automigrate/index.ts#L186) when running automigrations that could happen due to the CLI:

- not detecting main.js (user has to run the command again with —config-dir, but it does not make sense when running sb init)
- having errors trying to parse the main.js file (maybe something else failed and there is no main.js)

This happens because we always run automigrate as part of init, and it can cause potential issues for users without necessity for that.

We currently run automigrations as part of init because for select packages, typescript (or some babel features) are not supported out of the box: 

```groovy
@storybook/react-webpack5
@storybook/vue-webpack5
@storybook/vue3-webpack5
@storybook/html-webpack5
@storybook/web-components-webpack5
```

As part of this task, we should detach automigrate from init, and provide a better solution for the projects listed above to work out of the box, such as running the code from `missing-babelrc` automigration as part of the init step, only for that select group of frameworks.

The other reason we run automigrations is to provide users the option to install `eslint-storybook-plugin` automatically, which is really helpful. We should also move this suggestion to the sb init command.

**Comment by shilman** [comment]
Gadzooks!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.12 containing PR #22523 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb@latest upgrade
```
