### ISSUE TITLE
storybook init: Could not find the framework (abc) or renderer (xyz) package

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#22349]
Error location:  [getFrameworkDetails](https://github.com/storybookjs/storybook/blob/next/code/lib/cli/src/generators/baseGenerator.ts#L128).

Suggested work: 

This error seems to be connected to users trying to initialize Storybook with community packages or packages we don't support anymore:

- Could not find the framework (undefined) or renderer (storybook-solidjs) package
- Could not find the framework (@storybook/marionette-webpack5) or renderer (@storybook/marionette)
- Could not find the framework (@storybook/marko-webpack5) or renderer (@storybook/marko) package

We should do one of more of the following options:

- Go through the [baseGenerator](https://github.com/storybookjs/storybook/blob/next/code/lib/cli/src/initiate.ts#L71) file and clean it up by removing unsupported projects e.g. marko, mithrill, riot, aurelia, marionette, and rax.
- Investigate and fix the storybook-solidjs scenario, which seems to happen quite often (probably because a single package is both a framework and a renderer, different than other packages)

**Comment by yannbf** [comment]
These are all authentic errors for the packages I mentioned:

```
Error: Could not find the framework (@storybook/rax-webpack5) or renderer (@storybook/rax) package
Error: Could not find the framework (@storybook/mithril-webpack5) or renderer (@storybook/mithril) package
Error: Could not find the framework (@storybook/marko-webpack5) or renderer (@storybook/marko) package
Error: Could not find the framework (@storybook/riot-webpack5) or renderer (@storybook/riot) package
Error: Could not find the framework (@storybook/aurelia-webpack5) or renderer (@storybook/aurelia) package
Error: Could not find the framework (@storybook/marionette-webpack5) or renderer (@storybook/marionette) package
```

mithrill, riot, aurelia, marionette, and rax were moved to be external community packages, and have since gotten stale/unmaintained (since version 6.2.9).

marko is the only package which actually was worked on but still does not support Storybook 7

**Comment by yannbf** [comment]
We should:
1. Clear the unused packages
2. Either: Add SOLID as Vite by default or try to fix the issue by detecting Vite/Webpack from package.json as a fallback mechanism. If multiple are detected (e.g. monorepo), then prompt the user to select which one they'd like.

**Comment by shilman** [comment]
Jiminy cricket!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.1.0-alpha.17 containing PR #22492 that references this issue. Upgrade today to the `@future` NPM tag to try it out!

```
npx sb@next upgrade --tag future
```

**Comment by shilman** [comment]
Shiver me timbers!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.11 containing PR #22492 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb@latest upgrade
```
