### ISSUE TITLE
storybook init: Couldn't find template dir

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#22348]
Error locations:

- [angular generator](https://github.com/storybookjs/storybook/blob/next/code/lib/cli/src/generators/ANGULAR/index.ts#L83)
- [server generator](https://github.com/storybookjs/storybook/blob/next/code/lib/cli/src/generators/SERVER/index.ts#L13)
- [aurelia generator](https://github.com/storybookjs/storybook/blob/next/code/lib/cli/src/generators/AURELIA/index.ts#L29)

Suggested work:

This seems like a bug that should be investigated and fixed. In the scenario where the issue makes sense, the error message should be improved with a suggestion where the user can act upon.

**Comment by shilman** [comment]
Boo-yah!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.1.0-alpha.14 containing PR #22375 that references this issue. Upgrade today to the `@future` NPM tag to try it out!

```
npx sb@next upgrade --tag future
```

**Comment by shilman** [comment]
Ermahgerd!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.10 containing PR #22375 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb@latest upgrade
```
