### ISSUE TITLE
storybook init: Angular project already installed

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#22342]
Error location: [doInitiate](https://github.com/storybookjs/storybook/blob/next/code/lib/cli/src/initiate.ts#L326)

Suggested work: 

See whether the implementation is correct (given that Angular with its multi-project nature behaves differently than any other Storybook framework). If the implementation is correct, we could change the behavior to provide a prompt in the CLI to the user to continue the installation if they wanted, rather than throwing an error and asking the user to run the command again.

**Comment by shilman** [comment]
Olé!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.1.0-alpha.16 containing PR #22392 that references this issue. Upgrade today to the `@future` NPM tag to try it out!

```
npx sb@next upgrade --tag future
```

**Comment by shilman** [comment]
Great Caesar's ghost!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.11 containing PR #22392 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb@latest upgrade
```
