### ISSUE TITLE
storybook init: No `angular.json` file found

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#22351]
Error location: [angular generator → AngularJSON](https://github.com/storybookjs/storybook/blob/next/code/lib/cli/src/generators/ANGULAR/helpers.ts#L36)

Suggested work:

This is related to projects that try to initialize Storybook but do not have an `angular.json` file *in the current working directory.* We should investigate what exactly is happening, whether this is a correct scenario or if we could improve it. For instance, we could use [find-up](https://www.npmjs.com/package/find-up) to detect the angular.json file rather than `readSync` which only looks for files at the current working directory.

If there is no need to change the behavior because the error is legit, then we should at least improve the error message to provide a link to an FAQ entry (that should be created as part of this task) in the Storybook documentation website.

**Comment by shilman** [comment]
Ooh-la-la!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.1.0-alpha.14 containing PR #22377 that references this issue. Upgrade today to the `@future` NPM tag to try it out!

```
npx sb@next upgrade --tag future
```

**Comment by shilman** [comment]
Ooh-la-la!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.10 containing PR #22377 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb@latest upgrade
```
