### ISSUE TITLE
storybook init: Cannot destructure property 'root' of 'angularJSON.getProjectSettingsByName(...)' as it is undefined

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#22350]
Error location: [angular generator](https://github.com/storybookjs/storybook/blob/next/code/lib/cli/src/generators/ANGULAR/index.ts#L41)

Suggested work:

This is a bug in the way the `angular.json` file is parsed when initializing Storybook. Could be related to different formats present in different angular versions, or really just lack of better error handling. We should investigate it and fix it. Additionally, we should investigate the feedback from [this comment](https://github.com/storybookjs/storybook/issues/16110#issuecomment-1488619526) and take into account when improving the error message (or maybe adding an FAQ entry to the docs website).

**Comment by yannbf** [comment]
Finding as part of this investigation: We should improve the handling here, as it sends `null` errors:
https://github.com/storybookjs/storybook/blob/next/code/lib/cli/src/generators/ANGULAR/index.ts#L34

**Comment by yannbf** [comment]
Finding: it's likely that this line of code receives `undefined` as `this.projects[projectName]` does not exist:
https://github.com/storybookjs/storybook/blob/next/code/lib/cli/src/generators/ANGULAR/index.ts#L41

**Comment by valentinpalkovic** [comment]
@yannbf I think you wanted to take this ticket over. Or was it another which we talked about yesterday?

**Comment by shilman** [comment]
Zoinks!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.13 containing PR #22663 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb@latest upgrade
```

**Comment by shilman** [comment]
Yo-ho-ho!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.1.0-alpha.21 containing PR #22663 that references this issue. Upgrade today to the `@future` NPM tag to try it out!

```
npx sb@next upgrade --tag future
```
