### ISSUE TITLE
[Bug]: Zero-Config TypeScript Not Working After Upgrade from v6 to v7

### ISSUE THREAD

**Issue by NTARelix** [storybookjs/storybook#22357]
### Describe the bug

After following the [migration guide](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#from-version-65x-to-700) from v6 to v7 I get errors seemingly related to TypeScript syntax being unrecognized.

### To Reproduce

1. Clone my demo repo https://github.com/NTARelix/sb7-no-config-ts
2. Setup repo with `nvm i && npm ci`
3. Start Storybook with `npm start`
4. See error in console

### System

```shell
Environment Info:

  System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
  Browsers:
    Chrome: 112.0.5615.137
    Firefox: 112.0.1
    Safari: 16.4
  npmPackages:
    @storybook/addon-essentials: ^7.0.7 => 7.0.7 
    @storybook/react: ^7.0.7 => 7.0.7 
    @storybook/react-webpack5: ^7.0.7 => 7.0.7
```

### Additional context

In Storybook 6 all of this worked, presumably due to the [Zero Config TypeScript support](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#zero-config-typescript). After migrating to v7 the Storybook CLI describes a fatal error about syntax as if it doesn't understand TypeScript. To confirm my suspicion I added a log statement to `.storybook/main.ts` which shows the generated Webpack 5 config, in which there seems to be no mention of TypeScript. I would expect to see `.ts` extension resolution and `babel-loader` or `ts-loader`.

It seems as though "Zero Config TypeScript" is no longer supported, but I can't find anything in the migration docs regarding such a change.

I see a few possible causes/solutions:
1. Zero config TypeScript is supposed to be present, but isn't; feature must be re-added
2. Zero config TypeScript was removed; migration docs must be updated
3. Zero config TypeScript is present, but is not working as intended; bug fix must be released
4. I missed a migration step, resulting in an invalid config for TypeScript support; my config must be updated

In any case, it will be easy enough for me to manipulate the Webpack config using `webpackFinal()` in `.storybook/main.ts` until there's some kind of resolution to this.

**Comment by shilman** [comment]
That's correct. We changed the way Babel is handled. During the 7.0 automigration if you don't have a babelrc, the migration tool can automatically create one for you with Typescript support built in. If you don't choose that option, we don't support TS. 

More info: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#babel-mode-v7-exclusively

**Comment by serpearl** [comment]
Experiencing a similar issue in a React monorepo. I ran `npx storybook@latest babelrc` as suggested in the migration guide and it generated a `.babelrc.json` file with these options:
```json
{
  "sourceType": "unambiguous",
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": {
          "chrome": 100
        }
      }
    ],
    "@babel/preset-typescript",
    "@babel/preset-react"
  ],
  "plugins": []
}
```

Still getting compilation errors when stories contain any TypeScript syntax, e.g.
```
SyntaxError: D:\[...]\Anchor.stories.tsx: Unexpected token, expected "," (50:2)
  48 |     }
  49 |   }
> 50 | } as Meta);
     |   ^

```

**Comment by nataaverin** [comment]
Seems the same issue. Turborepo + Nextjs + Storybook 7.0.8
Getting errors related to Typescript. 

For example:
```
Unexpected token, expected "," (1:22)

> 1 | export { Button, type ButtonProps } from './button/Button';
    |                       ^
  2 |
  ```
  or

```
Support for the experimental syntax 'flow' isn't currently enabled (10:8):

   8 | import styles from './Button.module.css';
   9 |
> 10 | export interface ButtonProps {
     |        ^
  11 |   label: string;
  
  Add @babel/preset-flow (https://github.com/babel/babel/tree/main/packages/babel-preset-flow) to the 'presets' section of your Babel config to enable transformation.
If you want to leave it as-is, add @babel/plugin-syntax-flow (https://github.com/babel/babel/tree/main/packages/babel-plugin-syntax-flow) to the 'plugins' section to enable parsing.
  
  ```
  
  .babelrc.json is already containing preset-typescript:
  ```
{
  "sourceType": "unambiguous",
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": {
          "chrome": 100
        }
      }
    ],
    "@babel/preset-typescript",
    "@babel/preset-react"
  ],
  "plugins": []
}
```

Installation of @babel/preset-flow or @babel/plugin-syntax-flow as suggested doesn't help.

**Comment by serpearl** [comment]
Following up with what I experienced - renaming the `.babelrc.json` file to `babel.config.json` as suggested [here](https://github.com/storybookjs/storybook/issues/20423#issuecomment-1397755115) seemed to help a lot with TypeScript support.
I have since ran into unrelated issues and ended up with a different Storybook config, this time based around Next.js.

**Comment by tomhalley** [comment]
Thanks @serpearl this worked for me too

**Comment by joshuajaco** [comment]
> That's correct. We changed the way Babel is handled. During the 7.0 automigration if you don't have a babelrc, the migration tool can automatically create one for you with Typescript support built in. If you don't choose that option, we don't support TS.
> 
> More info: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#babel-mode-v7-exclusively

Does this mean we now have to maintain a babel config even though we don't use it outside of storybook?
Seeing a babel config in our root folder seems rather strange now.

**Comment by NTARelix** [comment]
@shilman When I created this issue I couldn't get the automigration feature to work (it works now), so I followed the manual migration guide. Looking through the guide I see a reference to "providing your own Babel config", but my project used `tsc` instead of Babel. This explains why this was broken for me. Based on the various comments here I'm confident this isn't a bug and I can continue with Storybook v7 by either migrating to Babel or manipulating the Webpack config with `webpackFinal` to replace `babel-loader` with `ts-loader`.

**Comment by bigbunty** [comment]
> babel-loader

after changing .babelrc.json to babel.config.json getting below errors
<img width="779" alt="Screenshot 2023-06-27 at 5 44 13 PM" src="https://github.com/storybookjs/storybook/assets/108940398/6228ac08-4222-438a-a38a-647f5d6ba2a1">

Checked with Rules of Hooks also, everything is fine.

**Comment by kputnins** [comment]
For anyone stumbling upon this - the override to the storybooks webpack config would be something like this
```ts
const config: StorybookConfig = {
    // ...
    typescript: {
        // Removes babel-loader from webpack config
        skipBabel: true,
    },
    webpackFinal: async (config: Configuration) => {
        // Custom rule for ts files
        const tsRule: RuleSetRule = {
            test: /\.(tsx?|jsx?)$/,
            loader: 'ts-loader',
            options: {
                transpileOnly: true,
            },
        };

        return {
            ...config,
            module: { ...config.module, rules: [...(config.module?.rules || []), tsRule] },
        };
    },
};
```

**Comment by bigbunty** [comment]
After adding 'ts-loader' rule & skipLabel getting below error.

_ModuleParseError: Module parse failed: Unexpected token (1:12)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> import type { Preview } from "@storybook/react";_

<img width="1134" alt="Screenshot 2023-06-30 at 2 10 03 PM" src="https://github.com/storybookjs/storybook/assets/108940398/730da45d-96ca-43e5-abad-d71e5738539d">

**Comment by bigbunty** [comment]
If I am pasting same stories under "stories" folder (got created while storybook 7 installation), stories are working fine. But I need to keep stories under each component folders(Button, Icon, Checkboax, etc.)

**Comment by TSjianjiao** [comment]
> After adding 'ts-loader' rule & skipLabel getting below error.
> 
> _ModuleParseError: Module parse failed: Unexpected token (1:12) You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> 
> > import type { Preview } from "@storybook/react";_
> 
> <img alt="Screenshot 2023-06-30 at 2 10 03 PM" width="1134" src="https://user-images.githubusercontent.com/108940398/250041257-730da45d-96ca-43e5-abad-d71e5738539d.png">

remove this config：
```
    typescript: {
        // Removes babel-loader from webpack config
        skipBabel: true,
    },
```

**Comment by jelling** [comment]
With a h/t to @kputnins, here is a full `.storybook/main.ts` example including `TsConfigPathsPlugin` to load paths from an alias in `tsconfig.json`:

```
import type { StorybookConfig } from "@storybook/react-webpack5";
import { Configuration, RuleSetRule } from "webpack";
import TsconfigPathsPlugin from "tsconfig-paths-webpack-plugin";

const config: StorybookConfig = {
  addons: ["@storybook/preset-create-react-app"],
  framework: "@storybook/react-webpack5",
  stories: ["../src/**/*.mdx", "../src/**/*.stories.@(js|jsx|mjs|ts|tsx)"],
  typescript: {
    // Removes babel-loader from webpack config
    skipBabel: true,
  },
  webpackFinal: async (config: Configuration) => {
    // Custom rule for ts files
    const tsRule: RuleSetRule = {
      test: /\.(tsx?|jsx?)$/,
      loader: "ts-loader",
      options: {
        transpileOnly: true,
      },
    };

    // tsconfig paths
    if (config.resolve) {
      config.resolve.plugins = [
        ...(config.resolve.plugins || []),
        new TsconfigPathsPlugin({
          extensions: config.resolve.extensions,
        }),
      ];
    }

    return {
      ...config,
      module: {
        ...config.module,
        rules: [...(config.module?.rules || []), tsRule],
      },
    };
  },
};

export default config;
```

Fwiw I found this issue after trying to automatically upgrade from SB 6 to 7. In my case, the migration seemed to mostly succeed but it never exited.

**Comment by NealEhardt** [comment]
Thanks @serpearl, this was hugely helpful!

I discovered that Storybook also accepts babel.config.js (not just JSON). That allowed me to document why we have a babel.config at all, since it isn't required by our Parcel build.

```
// This babel config is required for Storybook to parse our stories as TypeScript.
// Read more: https://github.com/storybookjs/storybook/issues/22357

module.exports = {
  sourceType: "unambiguous",
  presets: [
    [
      "@babel/preset-env",
      {
        targets: {
          chrome: 130,
        },
      },
    ],
    "@babel/preset-typescript",
    "@babel/preset-react",
  ],
  plugins: [],
};

```
