### ISSUE TITLE
[Bug]: Absolute path .js imports could not be found

### ISSUE THREAD

**Issue by Be-Like** [storybookjs/storybook#22358]
### Describe the bug

Vue + Vite

When importing a JavaScript file into a Vue file using the absolute path, I am receiving a "... could not be found in ..." error (screenshot below) when I go to build the storybook. 

In my vite.config.js file I have the resolve alias:
```
resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url))
    }
  },
```

![image](https://user-images.githubusercontent.com/36450393/235736219-87ebaa45-3038-4a4a-909d-571b79493130.png)

### System

```shell
Environment Info:

  System:
    OS: Linux 5.15 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (12) x64 AMD Ryzen 9 5900X 12-Core Processor
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
  Browsers:
    Chrome: 94.0.4606.71
  npmPackages:
    @storybook/addon-essentials: ^7.0.7 => 7.0.7
    @storybook/addon-interactions: ^7.0.7 => 7.0.7
    @storybook/addon-links: ^7.0.7 => 7.0.7
    @storybook/blocks: ^7.0.7 => 7.0.7
    @storybook/testing-library: ^0.1.0 => 0.1.0
    @storybook/theming: ^7.0.7 => 7.0.7
    @storybook/vue3: ^7.0.7 => 7.0.7
    @storybook/vue3-vite: ^7.0.7 => 7.0.7
```

**Comment by shilman** [comment]
Do you a have a reproduction repo you can share? If not, can you create one? Go to https://storybook.new or see [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce). Thank you! 🙏
