### ISSUE TITLE
[Bug]: Composition Api not allowed in @storybook/vue3

### ISSUE THREAD

**Issue by jmgayosso** [storybookjs/storybook#22366]
### Describe the bug

When a composable is implemented in a component linked to a story the "Legacy" error appears
![Screenshot 2023-05-02 at 18 25 27](https://user-images.githubusercontent.com/58195358/235812377-8781d788-c763-40a1-9803-a1c6f55997a4.png)

### System

Node js v18, VUE 3
"@storybook/vue3": "^6.5.15",

**Comment by shilman** [comment]
Please try upgrading to the latest release. Does that fix the problem? 7.0 contains a bunch of vue improvements.

Migration guide: https://storybook.js.org/migration-guides/7.0

@chakAs3 do you know anything about this?

**Comment by chakAs3** [comment]
@jmgayosso please upgrade to Storybook 7 so I can help you, I believe the problem is not composability but vite configuration and using aliases
