### ISSUE TITLE
[Bug]: @storybook/mdx2-csf/loader.js Killed

### ISSUE THREAD

**Issue by souhailmerroun** [storybookjs/storybook#22378]
### Describe the bug

0. New Github Codespace
1. npx create-next-app@latest --typescript
2. npx storybook@latest init
3. npm run storybook

```
@souhailmerroun ➜ /workspaces/storybook (main) $ npm run storybook

> my-app@0.1.0 storybook
> storybook dev -p 6006

@storybook/cli v7.0.8

info => Starting manager..
WARN You (or an addon) are using the 'config' preset field. This has been replaced by 'previewAnnotations' and will be removed in 8.0
info Addon-docs: using MDX2
info => Using implicit CSS loaders
info => Using default Webpack5 setup
<i> [webpack-dev-middleware] wait until bundle finished
10% building import loader ./node_modules/@storybook/mdx2-csf/loader.jsKilled
```

### System

```shell
@souhailmerroun ➜ /workspaces/storybook (main) $ npx storybook@latest info

Environment Info:

  System:
    OS: Linux 5.4 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (2) x64 Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz
  Binaries:
    Node: 19.9.0 - ~/nvm/current/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 9.6.3 - ~/nvm/current/bin/npm
  npmPackages:
    @storybook/addon-essentials: ^7.0.8 => 7.0.8 
    @storybook/addon-interactions: ^7.0.8 => 7.0.8 
    @storybook/addon-links: ^7.0.8 => 7.0.8 
    @storybook/blocks: ^7.0.8 => 7.0.8 
    @storybook/nextjs: ^7.0.8 => 7.0.8 
    @storybook/react: ^7.0.8 => 7.0.8 
    @storybook/testing-library: ^0.0.14-next.2 => 0.0.14-next.2
```

**Comment by souhailmerroun** [comment]
I've attempted the same with Vite + React, I get `Killed` as well.

**Comment by shilman** [comment]
Hi @souhailmerroun I followed your instructions and was not able to reproduce locally OR on a github codespace. Can you please try again, and if you are able to reproduce, share the reproduction repo here? Thanks!

**Comment by souhailmerroun** [comment]
Hello, I've recorded a screencast of how the bug happens for me.

https://www.youtube.com/watch?v=_sRwG4yW_x4

You can see 
- I install a fresh next.js app
- I install storybook 
- everything works fine so far
- I delete the stories that comes with installation
- Re run storybook <- (Bug happen)

**Comment by souhailmerroun** [comment]
@shilman were you able to reproduce?

**Comment by souhailmerroun** [comment]
Yes it looks very similar. I suspect it is a memory issue. I'll try on a 4 GB Core Codespace to see If I get the same error.

**Comment by cbou** [comment]
Yes it looks like a memory issue. I had the problem with our docker and after I increased the memory it was fine. Build needs around 2GB and my whole linux had 2GB ^^
