### ISSUE TITLE
[Feature Request]: remove unusual header from Stories DocBlock

### ISSUE THREAD

**Issue by herzaso** [storybookjs/storybook#22380]
### Is your feature request related to a problem? Please describe

Currently, it seems that only Stories DocBlock uses StyledHeading - a header that doesn't look other headers and more importantly, doesn't look like a header in a custom DocBlock (unless this specific code is duplicated).

### Describe the solution you'd like

I suggest to replace this header with the simpler `Heading`

### Are you able to assist to bring the feature to reality?

yes, I can

**Comment by shilman** [comment]
@herzaso This sounds like a bug not a feature. Can you share a screenshot with more information about what's inconsistent with the other headers? Thank you! 🙏

**Comment by herzaso** [comment]
<img width="1115" alt="Screen Shot 2023-05-04 at 14 12 32" src="https://user-images.githubusercontent.com/3350658/236190139-c71f17e3-dc65-4f62-91fa-a16dddb661f4.png">

Notice the `Stories` heading which looks in a different design language than `Primary` and cannot be replicated by users (unless they copy the code from `StyledHeading`.
I think that the design style should be identical to what the users would get from h1, h2, h3, etc.
