### ISSUE TITLE
Snapshot tests for the same repository on Windows and Linux should not fail.

### ISSUE THREAD

**Issue by maximemolines** [storybookjs/storybook#22382]
### Describe the bug

Snapshot tests for the same repository on Windows and Linux should not fail.

Instead when running the tests on different OS the "number" in `id` is different making the tests fail.

`id="mui-20" //exemple created on mac`
`id="mui-224" //exemple created on windows`

### To Reproduce

- Create snapshots in MAC and commit/push.
- Run tets (tests are fine)
- Clone repo with snapshots onWIN.
- Run tests (tests are failing, different number in className)

Versions : 

- `"@storybook/react": "^6.4.19"`
- `"@storybook/addon-storyshots": "^6.4.19"`

### System

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
  Binaries:
    Node: 19.3.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.2.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (112.0.1722.64)
```

### Additional context

It happens with the single snapshot file, className and Ids are generated by material-ui.

Related issue : https://github.com/storybookjs/storybook/issues/3140

**Comment by maximemolines** [comment]
I am using mui, versions : 
`"@mui/icons-material": "5.11.16"
    "@mui/lab": "5.0.0-alpha.82"
    "@mui/material": "5.12.0"
    "@mui/styles": "5.12.0"
    "@mui/system": "5.12.0"`

Commands for running tests : 
`jest // local`
`jest --ci --forceExit`

+ we can try and retry as many times as we want the classNames and Ids will always be good with a unix system et always be wrong with windows system

**Comment by jonniebigodes** [comment]
The Storyshots addon is officially deprecated and will be removed in a future release of Storybook. To help with the transition process, we've created a [migration guide](https://storybook.js.org/docs/writing-tests/storyshots-migration-guide) for the available options and common use cases.
