### ISSUE TITLE
[Bug]: Touch device loses focus or focus doesn't persist

### ISSUE THREAD

**Issue by IHIutch** [storybookjs/storybook#22387]
### Describe the bug

Im not exactly sure what the underlying problem is, but I think its related to losing/not trapping focus when using a touch device. You can also simulate this in desktop Chrome using the device view. 

You can see this happening at this link (Storybook 7.0.8) [https://draft-ui-storybook-auoslh311-ihiutch.vercel.app/?path=/story/menu--default](https://draft-ui-storybook-auoslh311-ihiutch.vercel.app/?path=/story/menu--default). When you press the button, the menu opens but immediately closes. 

This was worse in Storybook 7.0.6 (https://draft-ui-storybook-odx822byw-ihiutch.vercel.app/?path=/story/menu--default), where the menu would appear to "start" open when clicking the button and immediately close again.

https://user-images.githubusercontent.com/20825047/236035006-348837df-61ee-4a62-8d07-f0277628b13b.mp4

### To Reproduce

Try either of the links above. Happens with any of the components that open a "dropdown", eg. Menu, Datepicker, etc, . Seems to not be a problem for the Modal, I'm not sure what the differences are under the hood.

### System

```shell
System:
    OS: macOS 12.6.5
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
  Browsers:
    Chrome: 112.0.5615.137
    Firefox: 112.0.2
    Safari: 16.4.1
  npmPackages:
    @storybook/addon-styling: ^1.0.6 => 1.0.6
```

### Additional context

Underlying components are using `react-aria-components@1.0.0-alpha.3`

**Comment by shilman** [comment]
Do you a have a reproduction repo you can share? If not, can you create one? Go to https://storybook.new or see [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce). Thank you! 🙏

**Comment by IHIutch** [comment]
Ah, yes. Sorry about that https://stackblitz.com/edit/github-ci6nux?file=tsconfig.node.json
