### ISSUE TITLE
[Feature Request]: add cli only for dev and build commands

### ISSUE THREAD

**Issue by TrySound** [storybookjs/storybook#22416]
### Is your feature request related to a problem? Please describe

Storybook 7 cut a lot of packages. Though in v6 dev and build commands were used per framework package and now storybook cli is necessary to start dev or build stories. And cli have a big baggage of dependencies usually used via npx or similar tools. Now storybook cli should be installed along with all "generator" dependencies.

I found both dev and build already implemented separately in core-server package so adding new cli just for this commands will not require many changes.

Here's size comparison of freshly installed storybook with pnpm

```
du -ck node_modules
storybook: 116908
@storybook/core-server 77636
```

Almost 40MB is used for commands devs run rarely and use npx for this.

### Describe the solution you'd like

Some new cli like `@storybook/runner` or something with only `build` and `dev` commands for daily usage.

### Describe alternatives you've considered

Split all generators into separate CLI though this would require another major bump.

### Are you able to assist to bring the feature to reality?

yes, I can

**Comment by TrySound** [comment]
Hi @shilman, do you have any public discussions I could follow? Looks like 7.1 does not include changes you mentioned.

**Comment by JReinhold** [comment]
I'm sorry for dropping the ball here @TrySound. We ended up scoping it out of the 7.1 release, but we still want it to happen at some point.

I've written an RFC for it here, would love your input and involvement. https://github.com/storybookjs/storybook/discussions/23590
