### ISSUE TITLE
[Feature Request]: WTF Happened with the docs tab

### ISSUE THREAD

**Issue by youpage** [storybookjs/storybook#22424]
### Is your feature request related to a problem? Please describe

Your entire solution is a mess and the avalanch of plugins are not helping. Documentation is BS.
I am glad you have autodocs: true/false/tags(whatever the F this is), but not have a `tab` option to put that fking true in a TAB 

### Describe the solution you'd like

Show the docs in a Docs tab, without effort

### Are you able to assist to bring the feature to reality?

no

**Comment by jonniebigodes** [comment]
Closing this as per the rules of the code of conduct stated [here](https://github.com/storybookjs/storybook/blob/next/CODE_OF_CONDUCT.md), this type of language is not allowed here. And to wrap up this conversation, if you check our blog, we have various posts mentioning the Docs rework that was done as part of the Storybook 7.0 release. 

Have a great day. 

Stay safe
Hope you have a great
