### ISSUE TITLE
[Feature Request]: BS global decoration

### ISSUE THREAD

**Issue by youpage** [storybookjs/storybook#22425]
### Is your feature request related to a problem? Please describe

What is the point of having 
const preview: Preview = {
  parameters: {
    decorators: []

then when I set the below
decorators: [
      applicationConfig({
        providers: [importProvidersFrom(BrowserAnimationsModule, CommonModule)],
      }),
    ],

is not applied to every Story

### Describe the solution you'd like

make the above work

### Are you able to assist to bring the feature to reality?

no

### Additional context

I wonder who is managing this project, cause is mess.

**Comment by jonniebigodes** [comment]
Closing this as per the rules of the code of conduct stated [here](https://github.com/storybookjs/storybook/blob/next/CODE_OF_CONDUCT.md), this type of language is not allowed here, as already mentioned in another issue. We're more than welcome to follow up with our users/contributors but don't forget we're humans, and we're building a healthy community where everyone is welcome. Hope you understand.

Have a great day.

Stay safe
