### ISSUE TITLE
[Bug]: Storybook build broken when updating from v7.0.6 to v7.0.9

### ISSUE THREAD

**Issue by dgonzalezr** [storybookjs/storybook#22430]
### Describe the bug

The Storybook build is broken in an Nx monorepo when updating from v7.0.6. I've tested with v7.0.7 and v7.0.8 separately and the build has broken with the same error:

<img width="1300" alt="CleanShot 2023-05-06 at 12 28 12@2x" src="https://user-images.githubusercontent.com/328492/236615913-77c90fb1-e9ee-40a3-ab28-763d4c3bf008.png">

### To Reproduce

You can see the related change on our public repo, here in [this PR](https://github.com/Endava/bee-q/pull/236).
Checkout the repo from this specific branch: https://github.com/Endava/bee-q/tree/chore/%40storybook

```
npm run build
```

the build broke with the following output:

```
>  NX  Storybook builder starting ...
info => Cleaning outputDir: /dist/storybook/bee-q
info => Loading presets
info => Building manager..
✘ [ERROR] No matching export in "global-externals:@storybook/core-events" for import "DOCS_PREPARED"
    node_modules/@storybook/blocks/node_modules/@storybook/preview-api/dist/chunk-34WDGA45.mjs:6:356:
      6 │ ..._CHANGED, STORY_PREPARED, DOCS_PREPARED, STORY_MISSING, STORY_TH...
        ╵                              ~~~~~~~~~~~~~
✘ [ERROR] No matching export in "global-externals:@storybook/core-events" for import "DOCS_PREPARED"
    node_modules/@storybook/docs-tools/node_modules/@storybook/preview-api/dist/chunk-34WDGA45.mjs:6:356:
      6 │ ..._CHANGED, STORY_PREPARED, DOCS_PREPARED, STORY_MISSING, STORY_TH...
        ╵                              ~~~~~~~~~~~~~
 >  NX   Build failed with 2 errors:
   node_modules/@storybook/blocks/node_modules/@storybook/preview-api/dist/chunk-34WDGA45.mjs:6:356: ERROR: No matching export in "global-externals:@storybook/core-events" for import "DOCS_PREPARED"
   node_modules/@storybook/docs-tools/node_modules/@storybook/preview-api/dist/chunk-34WDGA45.mjs:6:356: ERROR: No matching export in "global-externals:@storybook/core-events" for import "DOCS_PREPARED"
   Pass --verbose to see the stacktrace.

 

 >  NX   Running target "bee-q:storybook-build" failed

   Failed tasks:
   
   - bee-q:storybook-build
   
   Hint: run the command with --verbose for more details.

   View structured, searchable error logs at https://cloud.nx.app/runs/HOxaLg9NJW

ERROR: "build:storybook" exited with 1
```

### System

```shell
System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 18.16.0 - ~/.volta/tools/image/node/18.16.0/bin/node
    Yarn: 3.4.1 - ~/.volta/tools/image/yarn/3.4.1/bin/yarn
    npm: 9.5.0 - ~/.volta/tools/image/npm/9.5.0/bin/npm
  Browsers:
    Safari: 16.3
  npmPackages:
    @storybook/addon-a11y: 7.0.6 => 7.0.6 
    @storybook/addon-actions: 7.0.6 => 7.0.6 
    @storybook/addon-docs: 7.0.6 => 7.0.6 
    @storybook/addon-essentials: 7.0.6 => 7.0.6 
    @storybook/addon-links: 7.0.6 => 7.0.6 
    @storybook/mdx2-csf: 1.0.0 => 1.0.0 
    @storybook/web-components: 7.0.6 => 7.0.6 
    @storybook/web-components-webpack5: 7.0.6 => 7.0.6
```
```


### Additional context

_No response_

**Comment by shilman** [comment]
Hi @dgonzalezr! Thanks for reporting. To clarify, the problem DOES NOT exist in `7.0.6` and DOES exist in `7.0.7`/`7.0.8`/`7.09`?

**Comment by shilman** [comment]
@dgonzalezr Can you try clearing your package lock & `node_modules` and reinstalling? The `DOCS_PREPARED` event was introduced in `7.0.7` and this error would occur if an older version of  `@storybook/core-events` was being used. Alternatively you could try `npm ls @storybook/core-events` to see which versions are being used in your project.

**Comment by dgonzalezr** [comment]
> Hi @dgonzalezr! Thanks for reporting. To clarify, the problem DOES NOT exist in `7.0.6` and DOES exist in `7.0.7`/`7.0.8`/`7.09`?

Hi @shilman , yes, the problem DOES NOT exist in `v7.0.6` of storybook. Regarding cleaning the `npm_modules` I did that and it is something failing also on [our CI pipeline](https://app.circleci.com/pipelines/github/Endava/bee-q/370/workflows/673d4845-9fb6-4449-a1e3-22e72bb5e18c/jobs/379).
