### ISSUE TITLE
[Bug]: Storybook errors if compodoc is not selected as the document generator

### ISSUE THREAD

**Issue by fireflysemantics** [storybookjs/storybook#22438]
### Describe the bug

https://stackoverflow.com/questions/76196298/adding-compodoc-to-storybook-after-running-npx-storybooklatest-init

### To Reproduce

Create an Angular project and don't select compodoc ...

**Comment by valentinpalkovic** [comment]
@fireflysemantics This is not reproducible for me in a new Angular project.

**Comment by fireflysemantics** [comment]
OK I'm going to retry creating the project from scratch

```
ng new storybook-workspace --create-application=false && cd storybook-workspace
ng g library lib && ng g application playground --defaults --style=scss --routing 
npx storybook@latest init
```

Select `lib` for the project.

When it asks if `compodoc` should be used for documentation, just leave the default `N`.

Hmmm ... Now it works for me too, so I'm going to close.
