### ISSUE TITLE
[Bug]: cant run storybook if change location with my stories

### ISSUE THREAD

**Issue by serveyk0-work** [storybookjs/storybook#22476]
### Describe the bug

I tried to export my stories to the ysh folder (not src), but I get an annoying error when starting the storybook. 

ModuleParseError: Module parse failed: Unexpected token (3:12)
File was processed with these loaders:
 * ./node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js
 * ./node_modules/unplugin/dist/webpack/loaders/load.js
You may need an additional loader to handle the result of these loaders.
| __webpack_require__.$Refresh$.runtime = require('D:/work/projects/test_storybook/node_modules/react-refresh/runtime.js');

Could you give me some tips on how to fix this? I am attaching the source code. Thank you!

https://github.com/serveyk0-work/test_storybook

![image](https://github.com/storybookjs/storybook/assets/78041681/43b31a62-fae6-4dd8-9e95-cca0d612c349)

**Comment by shilman** [comment]
Storybook for CRA uses CRA's webpack settings which only apply to files underneath the `src` folder. If you'd like to to customize the webpack settings you can add custom rules using the `webpackFinal` method in `.storybook/main.js`: https://storybook.js.org/docs/react/builders/webpack#override-the-default-configuration

**Comment by serveyk0-work** [comment]
> Storybook for CRA uses CRA's webpack settings which only apply to files underneath the `src` folder. If you'd like to to customize the webpack settings you can add custom rules using the `webpackFinal` method in `.storybook/main.js`: https://storybook.js.org/docs/react/builders/webpack#override-the-default-configuration
> 
> Hope that helps!

Hi)
Thanks for the answer)
Can you provide an example of webpackFinal setup, for this example?
Everything I've tried leads to the same error.
Thanks a lot!
