### ISSUE TITLE
[Bug]: 7.0.8+ "Uncaught SyntaxError: Unexpected token 'export'" if "type" is "commonjs" in package.json

### ISSUE THREAD

**Issue by hailwood** [storybookjs/storybook#22511]
### Describe the bug

Build runs fine but on page load we get a white screen with "Uncaught SyntaxError: Unexpected token 'export'" from each of the addons.

Talking with @JReinhold and we think it is likely https://github.com/storybookjs/storybook/pull/22247 that is the culprit.

The error only occurs if the type is explicitly "commonjs".
If it is missing or set to "module" then it does not occur.

### To Reproduce

https://stackblitz.com/edit/github-3zs2je?file=package.json

### System

```shell
Environment Info:

  System:
    OS: Linux 6.2 Ubuntu 23.04 23.04 (Lunar Lobster)
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
  Binaries:
    Node: 19.4.0 - /run/user/1000/fnm_multishells/1690392_1683750957209/bin/node
    npm: 9.3.0 - /run/user/1000/fnm_multishells/1690392_1683750957209/bin/npm
  Browsers:
    Chrome: 113.0.5672.92
    Firefox: 112.0.2
```

### Additional context

[Original Discord thread](https://discord.com/channels/486522875931656193/1103637173820989441/1103637173820989441)

**Comment by DustinJSilk** [comment]
Experiencing this as well, works up until 7.0.7

**Comment by jimmynotjim** [comment]
I just ran into this while migrating from v6 to v7 in my project. I can confirm that changing the type field in package.json from commonjs to module stops the error and storybook is able to load. (though I'm facing other problems I'm hoping are just issues with our existing setup)

(Sorry for the dupe comment SB team, I just realized I left this on the original PR and not this open issue)

**Comment by umer4ik** [comment]
Confirm it in 7.0.20, and changing to `"type": "module"` fixes the issue, but this is not suitable for me, because tests stop working

**Comment by jimmynotjim** [comment]
In case anyone else is tempted by the recent releases, I can confirm this is still an issue in 7.1.1 and 7.2.0-rc.0. I have one project I was able to remove the type but another where it causes other issues so that one is pinned to 7.0.7

**Comment by VelizarDemirev** [comment]
Still not working with version `7.4.1`. Since `commonjs` is the default value for `type` its safe atm to remove it from `package.json`, but its also reasonable to leave it since defaults can change. Would be nice to see a fix here.
