### ISSUE TITLE
[Feature Request]: Do not ignore initStoryshots renderer option when using test option

### ISSUE THREAD

**Issue by minsgiman** [storybookjs/storybook#22526]
### Is your feature request related to a problem? Please describe

If specify the `test` option to `initStoryshots`, it ignores the `renderer` option. 
I would like to use as below because I should set renderer to match `react-test-renderer` and `react` version.
but `renderer` option is ignored in this case

```
import { create } from 'react-test-renderer';

import initStoryshots from '@storybook/addon-storyshots';

initStoryshots({
  configPath: resolve('.storybook'),
  framework: 'react',
  renderer: create,
  test: multiSnapshotWithOptions(),
```

my package.json
```
"react": "^16.10.2",
"react-dom": "^16.10.2",
"react-test-renderer": "^16.10.2",
"@storybook/addon-storyshots": "^7.0.8",
"@storybook/addon-storyshots-puppeteer": "^7.0.8",
"@storybook/addon-viewport": "^7.0.8",
"@storybook/jest": "^0.1.1-next.0",
"@storybook/node-logger": "^7.0.8",
"@storybook/react": "^7.0.8",
"@storybook/react-webpack5": "^7.0.8",
```

seems same request : https://github.com/storybookjs/storybook/issues/3604

### Describe the solution you'd like

when use `test` option to `initStoryshots`, not ignores the `renderer` option. 

### Are you able to assist to bring the feature to reality?

no

**Comment by jonniebigodes** [comment]
The Storyshots addon is officially deprecated and will be removed in a future release of Storybook. To help with the transition process, we've created a [migration guide](https://storybook.js.org/docs/writing-tests/storyshots-migration-guide) for the available options and common use cases.
