### ISSUE TITLE
[Bug]: doesn't exist at build time, it will remain unchanged to be resolved at runtime

### ISSUE THREAD

**Issue by lvchenyang** [storybookjs/storybook#22531]
### Describe the bug

Build output:

```
info => Cleaning outputDir: /build
info => Loading presets
info => Building manager..
info => Manager built (121 ms)
info => Copying static files: /Users/lvchenyang/Projects/cya/mintpie-gravitation/common/temp/node_modules/.pnpm/@storybook+manager@7.0.10/node_modules/@storybook/manager/static at /Users/lvchenyang/Projects/cya/mintpie-gravitation/docs/build/sb-common-assets
vite v4.3.5 building for production...

> ./sb-common-assets/fonts.css doesn't exist at build time, it will remain unchanged to be resolved at runtime

✓ 1501 modules transformed.
build/assets/direction-94a9917f.svg                         1.28 kB │ gzip:   0.71 kB
build/assets/flow-275142c6.svg                              1.39 kB │ gzip:   0.68 kB
build/assets/code-brackets-9ef6443e.svg                     1.46 kB │ gzip:   0.69 kB
build/assets/comments-f15a6837.svg                          1.53 kB │ gzip:   0.70 kB
build/assets/repo-fb4ece47.svg                              1.64 kB │ gzip:   0.83 kB
build/assets/plugin-57148314.svg                            2.17 kB │ gzip:   0.98 kB
build/assets/stackalt-2ad81543.svg                          2.55 kB │ gzip:   1.09 kB
build/assets/colors-ac9401f3.svg                            8.51 kB │ gzip:   3.61 kB
build/iframe.html                                          12.76 kB │ gzip:   3.59 kB
build/assets/AddressEditor.stories-43daeb51.css             0.06 kB │ gzip:   0.08 kB
build/assets/Header-a6911580.css                            0.51 kB │ gzip:   0.31 kB
```

**How to ignore this build error?**

When I run `rush build` in gitlab CI/CD pipeline, this output will cause the pipeline job fail!

<img width="1047" alt="image" src="https://github.com/storybookjs/storybook/assets/5507872/c33be8dc-650d-4d3f-a5be-dcb42be24376">

### System

```shell
Environment Info:

  System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 16.20.0 - ~/.nvm/versions/node/v16.20.0/bin/node
    Yarn: 3.2.0 - ~/.nvm/versions/node/v16.20.0/bin/yarn
    npm: 8.19.4 - ~/.nvm/versions/node/v16.20.0/bin/npm
  Browsers:
    Chrome: 113.0.5672.92
    Safari: 16.4
  npmPackages:
    @storybook/addon-essentials: ^7.0.10 => 7.0.10 
    @storybook/addon-interactions: ^7.0.10 => 7.0.10 
    @storybook/addon-links: ^7.0.10 => 7.0.10 
    @storybook/blocks: ^7.0.10 => 7.0.10 
    @storybook/builder-vite: ^7.0.10 => 7.0.10 
    @storybook/react: ^7.0.10 => 7.0.10 
    @storybook/react-vite: ^7.0.10 => 7.0.10 
    @storybook/testing-library: ^0.1.0 => 0.1.0
```

### Additional context

main.ts

```typescript
import type { StorybookConfig } from "@storybook/react-vite";
import { mergeConfig } from "vite";

const config: StorybookConfig = {
  stories: ["../src/**/*.mdx", "../src/**/*.stories.@(js|jsx|ts|tsx)"],
  addons: [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/addon-interactions",
  ],
  core: {
    builder: "@storybook/builder-vite",
  },
  framework: {
    name: "@storybook/react-vite",
    options: {},
  },
  docs: {
    autodocs: "tag",
  },
  async viteFinal(config) {
    return mergeConfig(config, {
      build: {
        chunkSizeWarningLimit: 4096,
        rollupOptions: {
          onwarn: ({ message }) => {
            if (/Use of eval in/.test(message)) {
              return;
            }
            console.log(message);
          },
        },
      },
    });
  },
};
export default config;
```

**Comment by douglasward** [comment]
I am also getting this error when importing our stylesheet with a relative path in the preview.ts file

**Comment by ericclemmons** [comment]
Also getting this error. The build seems to _work_ though...

**Comment by joseangel-mm** [comment]
I have the same error. It seems the problem is in the iframe.html file (from `builder-vite` package), in that package, there is no assets folder to get the fonts.
<img width="1306" alt="Screenshot 2023-06-28 at 14 00 36" src="https://github.com/storybookjs/storybook/assets/85619872/e9b4c8a0-43f2-4af5-9828-592111273782">

**Comment by alb3rtuk** [comment]
Anybody figured out how to fix this?

**Comment by MJB52** [comment]
This won't help everyone but for anyone using Rush like @lvchenyang - try redeclaring the "build" command in your command-line.json file and add the setting `"allowWarningInSuccessfulBuild": true`. This will keep warnings from failing your CI/CD builds

```json
    {
      //this command is to override the existing build command to allow warnings in the build
      "commandKind": "bulk",
      "name": "build", 
      "summary": "Build",
      "description": "This command will build projects",
      "safeForSimultaneousRushProcesses": false,
      "enableParallelism": true,
      "ignoreDependencyOrder": false,
      "ignoreMissingScript": true,
      "allowWarningsInSuccessfulBuild": true
    },
```

**Comment by lvchenyang** [comment]
> This won't help everyone but for anyone using Rush like @lvchenyang - try redeclaring the "build" command in your command-line.json file and add the setting `"allowWarningInSuccessfulBuild": true`. This will keep warnings from failing your CI/CD builds
> 
> ```json
>     {
>       //this command is to override the existing build command to allow warnings in the build
>       "commandKind": "bulk",
>       "name": "build", 
>       "summary": "Build",
>       "description": "This command will build projects",
>       "safeForSimultaneousRushProcesses": false,
>       "enableParallelism": true,
>       "ignoreDependencyOrder": false,
>       "ignoreMissingScript": true,
>       "allowWarningsInSuccessfulBuild": true
>     },
> ```

Yep！Add `"allowWarningInSuccessfulBuild": true` would pass the CI/CD.

**Comment by 001123** [comment]
Still got this issue, any way to fix it?

**Comment by Sinled** [comment]
Any chances for this to be fixed? or way to silence it without allowing warnings in Rush?

**Comment by hc-12** [comment]
You might also get this issue if you are importing markdown files.

To fix the issue, you need to change the import:

```diff
-import changeLog from './changelog.md`
+import changeLog from './changelog.md?raw`
```

**Comment by h-bessa** [comment]
does anybody know how to fix this problem?

**Comment by h-bessa** [comment]
PS: I've tried to create my lib using rollup bundler and not vite bundler. it seems to work. No warning, no problem.

**Comment by kouts** [comment]
This issue still exists in v8, the only workaround I found is to create an `sb-common-assets/fonts.css` file in the root dir of the project.

**Comment by soullivaneuh** [comment]
The bug occurs also on a fresh new install of storybook:

1. Run `npx storybook@latest init`
2. Select project template `React + Vite (TS)`
3. Once installed, run `npm run build-storybook`

Then you will have the same error on the output.

Here is the env info of the fresh install:

```
Storybook Environment Info:

  System:
    OS: Linux 6.2 Ubuntu 23.04 23.04 (Lunar Lobster)
    CPU: (8) x64 Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm <----- active
    pnpm: 8.14.3 - ~/.local/share/pnpm/pnpm
  Browsers:
    Chrome: 120.0.6099.224
  npmPackages:
    @storybook/addon-essentials: ^8.0.0 => 8.0.0 
    @storybook/addon-interactions: ^8.0.0 => 8.0.0 
    @storybook/addon-links: ^8.0.0 => 8.0.0 
    @storybook/addon-onboarding: ^8.0.0 => 8.0.0 
    @storybook/blocks: ^8.0.0 => 8.0.0 
    @storybook/react: ^8.0.0 => 8.0.0 
    @storybook/react-vite: ^8.0.0 => 8.0.0 
    @storybook/test: ^8.0.0 => 8.0.0 
    eslint-plugin-storybook: ^0.8.0 => 0.8.0 
    storybook: ^8.0.0 => 8.0.0 
```

**Comment by larbimahmoud** [comment]
did any one resolve the error !!

**Comment by dohomi** [comment]
I see this issue on Vite with Storybook v8.0.9 and deploying on Vercel

**Comment by julianCast** [comment]
Also having this issue, details:
```sh
Info => Copying static files: /Users/me/Documents/GitHub/x/frontend/packages/y/node_modules/@storybook/manager/static at /Users/me/Documents/GitHub/x/frontend/packages/y/storybook-static/sb-common-assets

./sb-common-assets/fonts.css doesn't exist at build time, it will remain unchanged to be resolved at runtime
```
Could it be because the structure of the project?
Main package with package.json from where we run storybook build command as :     
 `"build-storybook": "yarn storybook build -c ./src/storybook/.storybook"`

And then our storybook is in `root > src > storybook`
The `storybook-static`folder is created in `root > storybook-static`

Our root package uses gatsby with webpack.

**Comment by soullivaneuh** [comment]
The bug looks to not be present anymore. Tested with Storybook 8.0.10 with the same steps to reproduce as LINK:

```
❯ npm run build   

> storybook-test@0.0.0 build
> vite build

vite v5.2.11 building for production...
✓ 34 modules transformed.
dist/index.html                   0.46 kB │ gzip:  0.30 kB
dist/assets/react-CHdo91hT.svg    4.13 kB │ gzip:  2.14 kB
dist/assets/index-DiwrgTda.css    1.39 kB │ gzip:  0.72 kB
dist/assets/index-DVoHNO1Y.js   143.36 kB │ gzip: 46.06 kB
✓ built in 1.72s
```

This issue may be closed.

**Comment by valentinpalkovic** [comment]
@soullivaneuh You have to run the Storybook build instead of the vite build. The issue still exists. I've just tested it.

**Comment by soullivaneuh** [comment]
@valentinpalkovic Indeed! I stupidily ran `npm run build` cause I use the storybook init command, I was thinking it was for storybook build at this time! Doh! 

Running `npm run build-storybook` makes indeed the error appearing. :upside_down_face: 

Sorry for that.
