### ISSUE TITLE
[Feature Request]: Support nuxt

### ISSUE THREAD

**Issue by crunchwrap89** [storybookjs/storybook#22588]
### Is your feature request related to a problem? Please describe

There is currently no support or specified instructions on how to implement storybook with nuxt 3.

### Describe the solution you'd like

Create a nuxt/storybook module that works with nuxts 3 auto imports.

### Describe alternatives you've considered

Another application called Histoire

### Are you able to assist to bring the feature to reality?

no

**Comment by shilman** [comment]
Have you tried this? https://github.com/hirotaka/storybook-addon-nuxt

**Comment by shilman** [comment]
Closing as dupe to https://github.com/storybookjs/storybook/issues/20312

**Comment by crunchwrap89** [comment]
No but I saw this was released just three days ago, awesome. I will be testing this asap. :) thanks.

**Comment by shilman** [comment]
@crunchwrap89 Awesome, I hope it works well. Please report back!
