### ISSUE TITLE
[Bug]: @whitespace/storybook-addon-html

### ISSUE THREAD

**Issue by volnei** [storybookjs/storybook#22586]
### Describe the bug

```
npm ERR! Could not resolve dependency:
npm ERR! dev @whitespace/storybook-addon-html@"*" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @storybook/addons@6.5.16
npm ERR! node_modules/@storybook/addons
npm ERR!   peer @storybook/addons@"^6.5.8" from @whitespace/storybook-addon-html@5.1.4
```

### To Reproduce

Create a project with latest storybook version and try to install the dependency
```
npm i --save-dev @whitespace/storybook-addon-html
```

**Comment by yannbf** [comment]
Hey @volnei it seems like this issue is on another package, not related to this repo. It seems to be lack of compatibility with storybook 7.

Could you mention your issue at the right place instead?

https://github.com/whitespace-se/storybook-addon-html/issues/96


cc @jonniebigodes
