### ISSUE TITLE
[Bug]: TailwindCSS classes not applied during development

### ISSUE THREAD

**Issue by jansedlon** [storybookjs/storybook#22616]
### Describe the bug

When I create a new story, the classes in the component are not applied in Storybook. To fix it, I have to restart the development server.

### To Reproduce

https://stackblitz.com/edit/github-nnjva4?file=src%2Fstories%2Favatar.stories.tsx,src%2Fstories%2Favatar.tsx&preset=node

## Steps
- Create a new component with classes that are not used (you can inspire with the avatar.tsx component that I made there)
- Make a story for it
- TailwindCSS classes are not applied.

### System

```shell
Environment Info:

  System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 18.14.0 - ~/.nvm/versions/node/v18.14.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.14.0/bin/yarn
    npm: 9.3.1 - ~/.nvm/versions/node/v18.14.0/bin/npm
  Browsers:
    Edge: 113.0.1774.42
    Firefox: 113.0
    Safari: 16.4
  npmPackages:
    @storybook/addon-essentials: ^7.0.12 => 7.0.12 
    @storybook/addon-interactions: ^7.0.12 => 7.0.12 
    @storybook/addon-links: ^7.0.12 => 7.0.12 
    @storybook/addon-styling: ^1.0.8 => 1.0.8 
    @storybook/blocks: ^7.0.12 => 7.0.12 
    @storybook/react: ^7.0.12 => 7.0.12 
    @storybook/react-vite: ^7.0.12 => 7.0.12 
    @storybook/testing-library: ^0.0.14-next.2 => 0.0.14-next.2
```

**Comment by ginabeki** [comment]
Hey @jansedlon can I work on this?

**Comment by jansedlon** [comment]
Hi @ginabeki. Yeah, probably. I'm not in charge of prioritising 😄

**Comment by N-koder** [comment]
I think you should add tsx in tailwind.config.js in content section 
for example : 
```javascript

```  ** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,js,jsx,tsx}"],
  theme: {
    extend: {
      fontFamily : {
        satoshi : ["Satoshi", "sans-serif"],
        inter : ["Inter" , "sans-serif"]
      }
    },
  },
  plugins: [],
}

**Comment by N-koder** [comment]
let me know if it works or not!

**Comment by shilman** [comment]
@Integrayshaun is this something you can lend a hand with?

**Comment by Integrayshaun** [comment]
@shilman in this case, it's a file watching problem, not the styling addon. Tailwind builds the stylesheet based on the classes it sees in the files that match it's `content` pattern.

Creating a new component with new classes means postcss isn't looking at them until a server restart. Maybe this is something that can be tweaked in vite?

**Comment by molul** [comment]
Did this ever get solved? I'm having a similar issue in a project with Vue+Vite+Storybook.

**Comment by Integrayshaun** [comment]
@molul not yet! However, I wonder if our resident vite expert, @IanVS has any ideas?

**Comment by molul** [comment]
If it helps, I was able to solve it following these steps: https://github.com/tailwindlabs/tailwindcss/discussions/12432#discussioncomment-7596975

**Comment by Integrayshaun** [comment]
@jansedlon Hey there 👋 

Is this still a problem for you? I rechecked your repro and wasn't able to reproduce the issue.

**Comment by jansedlon** [comment]
Hey @Integrayshaun 
I'm really sorry but I don't use it anymore 😅 So really can't tell

**Comment by Integrayshaun** [comment]
Hey folks 👋 

I'm going to close this issue for now since it's been inactive. If anyone else still has this problem, please leave a comment with a reproduction of the issue and we can re-open it for discovery.
