### ISSUE TITLE
[Bug]: toolbar theme change doesn't update the query param in the URL which the context.globals.theme is based on

### ISSUE THREAD

**Issue by zeckdude** [storybookjs/storybook#22636]
### Describe the bug

It seems that the `context.global.theme` value that is accessible in the decorator draws directly from a URL query param. When the toolbar selection for the theme is changed, the `context.global.theme` briefly shows with the selected value and then reverts back to nothing, since I assume it tries to draw its value from the URL query param again. It appears that maybe it refreshes the preview window and then tries to grab the value from the URL query param but it's not there.

### To Reproduce

Use the example exactly from https://storybook.js.org/docs/react/essentials/toolbars-and-globals 

`preview.js`
```js
const preview: Preview = {
  globalTypes: {
    theme: {
      description: 'Global theme for components',
      defaultValue: 'light',
      toolbar: {
        title: 'Theme',
        icon: 'circlehollow',
        items: ['light', 'dark'],
        dynamicTitle: true,
      },
    },
  },
}

export default preview
```

In component story
```js
const withColorScheme = (Story2, context) => {
  console.log('context.globals.theme', context.globals.theme)
}

const meta: Meta<typeof Text> = {
  title: 'Headings/Text',
  component: Text,
  tags: ['autodocs'],
  argTypes: {},
  decorators: [withColorScheme],
}
```

There's an error in the console: `manager  received storyRenderPhaseChanged but was unable to determine the source of the event`

### System

```shell
Environment Info:

  System:
    OS: macOS 12.5
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 19.8.1 - ~/.nvm/versions/node/v19.8.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v19.8.1/bin/yarn
    npm: 9.6.5 - ~/.nvm/versions/node/v19.8.1/bin/npm
  Browsers:
    Chrome: 111.0.5563.146
    Firefox: 113.0.1
    Safari: 15.6
  npmPackages:
    @storybook/addon-essentials: ^7.0.12 => 7.0.12
    @storybook/addon-interactions: ^7.0.12 => 7.0.12
    @storybook/addon-links: ^7.0.12 => 7.0.12
    @storybook/addon-styling: ^1.0.0-next.2 => 1.0.0-next.2
    @storybook/blocks: ^7.0.12 => 7.0.12
    @storybook/nextjs: ^7.0.12 => 7.0.12
    @storybook/react: ^7.0.12 => 7.0.12
    @storybook/testing-library: ^0.0.14-next.2 => 0.0.14-next.2
```

**Comment by marcellus-trixus** [comment]
I am seeing the same error but it only appears on `autodocs` pages. On individual story pages the switching works fine even without appending query param to URL.

**Comment by matthprost** [comment]
Hello! I'm having the exact same issue with theme switcher on docs view. It seems like it doesn't work on docs view only, when I go to story view it works just fine.

https://github.com/storybookjs/storybook/assets/15812968/d8b18a85-c3d5-45f5-ac15-73df01a13f48

**Comment by shilman** [comment]
I just tried a fresh Vite / React project that included stories, autodocs, MDX files referencing those stories, etc. In every case the toolbar / URL / `context.global.theme` value updated as expected.

Do you a have a reproduction repo you can share? If not, can you create one? Go to https://storybook.new or see [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce). Thank you! 🙏

**Comment by mimittqq** [comment]
dynamicTitle don't work when add loaders to story. is it expected?

**Comment by binaryfire** [comment]
> Hello! I'm having the exact same issue with theme switcher on docs view. It seems like it doesn't work on docs view only, when I go to story view it works just fine.
> 
>  Screen.Recording.2023-09-12.at.10.42.16.mov

@matthprost Were you able to figure out a workaround? I'm running into this with Storybook 10 and Tanstack Start
