### ISSUE TITLE
[Bug]: Could not resolve "react"

### ISSUE THREAD

**Issue by JoeshuTT** [storybookjs/storybook#22632]
### Describe the bug

```bash
$ npm run storybook

> vue-project@0.0.0 storybook
> storybook dev -p 6006

@storybook/cli v7.0.12

info => Starting manager..
╭────────────────────────────────────────────────────╮
│                                                    │
│   Storybook 7.0.12 for vue3-vite started           │
│   304 ms for manager and 1.99 s for preview        │
│                                                    │
│    Local:            http://localhost:6006/        │
│    On your network:  http://192.168.6.196:6006/    │
│                                                    │
╰────────────────────────────────────────────────────╯
X [ERROR] Could not resolve "react"

    ../node_modules/@emotion/styled/dist/emotion-styled.browser.esm.js:2:7:
      2 │ import 'react';
        ╵        ~~~~~~~

  You can mark the path "react" as external to exclude it from the bundle, which will remove this
  error.
```

### System

```shell
$ npx storybook@latest info

Environment Info:

  System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz
  Binaries:
    Node: 18.16.0 - D:\software\nodejs\node.EXE
    npm: 9.5.1 - D:\software\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (113.0.1774.42)
  npmPackages:
    @storybook/addon-essentials: ^7.0.12 => 7.0.12
    @storybook/addon-interactions: ^7.0.12 => 7.0.12
    @storybook/addon-links: ^7.0.12 => 7.0.12
    @storybook/blocks: ^7.0.12 => 7.0.12
    @storybook/testing-library: ^0.0.14-next.2 => 0.0.14-next.2
    @storybook/vue3: ^7.0.12 => 7.0.12
    @storybook/vue3-vite: ^7.0.12 => 7.0.12
```

### Additional context

1. creat a vue3+vite project
```bash
npm init vue
cd vue-project
```
2.  install Storybook
```bash
npx storybook@latest init
```
3. see error
```
X [ERROR] Could not resolve "react"
```

**Comment by N-koder** [comment]
I can solve this issue! may I?

**Comment by JoeshuTT** [comment]
How to solve it

**Comment by N-koder** [comment]
Instead of importing 'react' use import React from 'react' may this resolve the bug.

**Comment by N-koder** [comment]
if you don't have a webpack.config.js file 

create it in the ./storybook directory

and paste the below code in it.
const path = require('path');

module.exports = {
  resolve: {
    alias: {
      'react': path.resolve(__dirname, '../node_modules/react'),
    },
  },
};
This configuration sets up an alias for 'react' in the webpack configuration so that it can resolve to the correct path. Adjust the path if your node_modules directory is in a different location. because the above error occur in node modules directory.

**Comment by N-koder** [comment]
let me know if all of them do not work for you and make sure to try these solutions one at a time and test Storybook after each attempt.

**Comment by JoeshuTT** [comment]
Thank you for your answer. I need to return to the company to verify this issue, Monday. I will reply to you.

**Comment by N-koder** [comment]
sure I will wait.

**Comment by JoeshuTT** [comment]
It's not resolved.  May be caused by cache dependency. I rebuilt the project. it is run ok.

**Comment by N-koder** [comment]
ok as your wish! If you want help contact me. thank you
