### ISSUE TITLE
[Bug]: the `view source` functionality doesn't re-render when arguments change

### ISSUE THREAD

**Issue by marcomontalbano** [storybookjs/storybook#22645]
### Describe the bug

When working with the `html` template, the `view source` functionality doesn't re-render when arguments change. It will render correctly only the first time, but when you set back the attribute, it doesn't update.

I'm posting a video to show better the issue that as mentioned below is directly reproducible on your official StackBlitz sandbox.

https://github.com/storybookjs/storybook/assets/1681269/4b3248be-b26e-4e35-b6b4-b5925b76f24c

### To Reproduce

I'm able to reproduce this issue on any official `html` and `lit` sandboxes.

From `next` release:
* https://stackblitz.com/github/storybookjs/sandboxes/tree/next/html-webpack/default/after-storybook
* https://stackblitz.com/github/storybookjs/sandboxes/tree/next/html-vite/default-js/after-storybook
* https://stackblitz.com/github/storybookjs/sandboxes/tree/next/html-vite/default-ts/after-storybook
* https://stackblitz.com/github/storybookjs/sandboxes/tree/next/lit-vite/default-ts/after-storybook
* https://stackblitz.com/github/storybookjs/sandboxes/tree/next/lit-vite/default-js/after-storybook

From `main` release:
* https://stackblitz.com/github/storybookjs/sandboxes/tree/main/html-webpack/default/after-storybook
* https://stackblitz.com/github/storybookjs/sandboxes/tree/main/html-vite/default-js/after-storybook
* https://stackblitz.com/github/storybookjs/sandboxes/tree/main/html-vite/default-ts/after-storybook
* https://stackblitz.com/github/storybookjs/sandboxes/tree/main/lit-vite/default-ts/after-storybook
* https://stackblitz.com/github/storybookjs/sandboxes/tree/main/lit-vite/default-js/after-storybook

I'm able to reproduce it locally by running:

```sh
npx sb@next init --type html
npm run storybook 
```

### System

```shell
Environment Info:

  System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 18.15.0 - ~/Library/pnpm/node
    Yarn: 1.22.19 - ~/node_modules/.bin/yarn
    npm: 8.19.2 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 113.0.5672.126
    Firefox: 112.0.2
    Safari: 16.4
  npmPackages:
    @storybook/addon-essentials: ^7.0.12 => 7.0.12 
    @storybook/addon-interactions: ^7.0.12 => 7.0.12 
    @storybook/addon-links: ^7.0.12 => 7.0.12 
    @storybook/blocks: ^7.0.12 => 7.0.12 
    @storybook/html: ^7.0.12 => 7.0.12 
    @storybook/html-webpack5: ^7.0.12 => 7.0.12 
    @storybook/testing-library: ^0.0.14-next.2 => 0.0.14-next.2
```

**Comment by marcomontalbano** [comment]
@chakAs3 you're right! I didn't test them, but checking now I get the same issue with React here:
https://stackblitz.com/github/storybookjs/sandboxes/tree/next/react-webpack/18-ts/after-storybook

It's the first time I open the Storybook's source code, so I can probably go wrong, but I notice that the Source component is rendered as soon as the SourceContext is updated, but here that context will not update when the `newSource` is already present in the state. I hope this can help.

https://github.com/storybookjs/storybook/blob/e8c11645347c01822726c91922692fac0510f8db/code/ui/blocks/src/blocks/SourceContainer.tsx#L73-L86

**Comment by chakAs3** [comment]
hi @marcomontalbano   i have already open a PR fixing this,Indeed that is the bug if the hash(arg) already in the current source the function return. always current, not only if the arg is boolean but also if you go back and forth between 2 states

**Comment by shilman** [comment]
Jiminy cricket!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.1.0-alpha.28 containing PR #22807 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```
