### ISSUE TITLE
[Bug]: Storybook vue2 router undefined

### ISSUE THREAD

**Issue by marcianos** [storybookjs/storybook#22648]
### Describe the bug

I started using storybook in my vue project. At the moment I am still at vue 2.7. I am using completely script setup, composition api and vue Router composable. When I use useRouter() in my component and write a story, every story is broken and storybook says “router is undefined”. But the component works without any errors in normal vue app. Is this a bug or do I need to configure something?

### To Reproduce

Just use vue 2.7 with script setup and inside the component:

`const router = useRouter();`

**Comment by kyumoon** [comment]
+1 vue3.x

**Comment by Walnussbaer** [comment]
Same problem here with vue 3.3.4

**Comment by vanessayuenn** [comment]
Thank you for raising this issue. However, we will be [discontinuing support for vue2](https://github.com/storybookjs/storybook/discussions/24951) starting from the upcoming 8.0 release. @Walnussbaer if this is indeed also an issue with vue3, can you please open a new issue with a reproduction in vue3 (see [how to create a repro](https://storybook.js.org/docs/react/contribute/how-to-reproduce))? We prioritize bug reports that have reproduction. Thank you! 🙏

**Comment by lentilz** [comment]
Have manage the below snippet as a workaround for this issue:
```
webpackFinal: async (config) => {
    ...
    config.resolve = {
	    alias: {
		    'vue-router/composables': require.resolve('path/to/file/mock/vue-router-composables.ts')
	    }
};
```

in the composables file:
```
export const useRoute = () => ({
	path: '',
	hash: '',
	query: {},
	params: {},
	fullPath: '',
	matched: []
});

export const useRouter = () => ({
	resolve() {
		return {
			resolved: {
				path: '/',
				hash: '#',
				matched: [],
				name: '',
				params: {}
			}
		};
	}
});
```
