### ISSUE TITLE
[Bug]: Failed to fetch dynamically imported module: https://vaynevayne.github.io/soul/assets/config-c065c578.js

### ISSUE THREAD

**Issue by vaynevayne** [storybookjs/storybook#22654]
### Describe the bug

https://vaynevayne.github.io/soul/

this is my git repository url :  https://github.com/vaynevayne/soul
I saw through chrome dev that this js file is already on the network, but why is there still this error?

Can you take a look at it? I can't use it at all right now

**Comment by juandanceswild** [comment]
@vaynevayne I see you fixed the error. Can you share what was your solution please?

**Comment by vaynevayne** [comment]
It's been too long, forgotten, and the solution may be to upgrade to the latest version
