### ISSUE TITLE
Unhandled Runtime Error TypeError: Cannot read properties of undefined (reading 'text')

### ISSUE THREAD

**Issue by kamalaryal123** [storybookjs/storybook#22653]
### Describe the bug

![image](https://github.com/storybookjs/storybook/assets/131939809/3deed604-7cc8-4084-9aa6-8528cb471127)

in storybook it is running fine but when i use the components in another application(next js application) it is showing the error 
.i am using emotion/styled  and mui for making storybook components. When using the component without theme in emotion/styled it is working fine but when using with theme is it not working.showing same error for all components

**Comment by N-koder** [comment]
what says your browser's console about this?

**Comment by shilman** [comment]
Do you a have a reproduction repo you can share? If not, can you create one? Go to https://storybook.new or see [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce). Thank you! 🙏

**Comment by N-koder** [comment]
sorry but, I can't understand what you want to tell
