### ISSUE TITLE
[Bug]: @storybook/nextjs incompatible with Next 13.4.3

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#22686]
### Describe the bug

When upgrading Next to 13.4.3 or higher, Storybook breaks with the following error:

```
WARN Force closed preview build
ModuleNotFoundError: Module not found: Error: Can't resolve 'fs' in '/Users/yannbraga/open-source/storybook/sandbox/nextjs-default-js/node_modules/next/dist/compiled/gzip-size'
    at /Users/yannbraga/open-source/storybook/sandbox/nextjs-default-js/node_modules/webpack/lib/Compilation.js:1512:33
    at /Users/yannbraga/open-source/storybook/sandbox/nextjs-default-js/node_modules/webpack/lib/NormalModuleFactory.js:656:18
    at eval (eval at create (/Users/yannbraga/open-source/storybook/sandbox/nextjs-default-js/node_modules/tapable/lib/HookCodeFactory.js:28:14), <anonymous>:10:1)
```

### To Reproduce

Run `yarn storybook` in [this sandbox](https://github.com/storybookjs/sandboxes/tree/next/nextjs/default-js/after-storybook)

**Comment by shilman** [comment]
Ermahgerd!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.1.0-alpha.21 containing PR #22697 that references this issue. Upgrade today to the `@future` NPM tag to try it out!

```
npx sb@next upgrade --tag future
```

**Comment by shilman** [comment]
Ermahgerd!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.15 containing PR #22697 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb@latest upgrade
```
