### ISSUE TITLE
[Bug]: Vue 3.3 imported Props as type

### ISSUE THREAD

**Issue by Blackfaded** [storybookjs/storybook#22681]
### Describe the bug

After upgrading to vue 3.3 and defining props as a type from en external file the story does not compile anymore.

working example: 
```ts
interface Props {
   hello: string;
}

const props = defineProps<Props>();
```

working example: 
```ts
import { SharedProps } from './sharesProps.ts';
interface Props extends SharedProps{}

const props = defineProps<Props>();
```

not working example: 
```ts
import { SharedProps } from './sharesProps.ts';
type Props = SharedProps

const props = defineProps<Props>();
```

The error message is `TypeError: Failed to fetch dynamically imported module: `

### To Reproduce

https://stackblitz.com/edit/github-evs32s?file=src%2Fcomponents%2FHelloWorldFailing.vue

### System

```shell
Environment Info:

  System:
    OS: macOS 12.5.1
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Chrome: 113.0.5672.126
    Safari: 15.6.1
  npmPackages:
    @storybook/addon-actions: 7.1.0-alpha.20 => 7.1.0-alpha.20 
    @storybook/addon-essentials: 7.1.0-alpha.20 => 7.1.0-alpha.20 
    @storybook/addon-links: 7.1.0-alpha.20 => 7.1.0-alpha.20 
    @storybook/vue3: 7.1.0-alpha.20 => 7.1.0-alpha.20 
    @storybook/vue3-vite: 7.1.0-alpha.20 => 7.1.0-alpha.20
```

**Comment by shilman** [comment]
@chakAs3 @kasperpeulen mind taking a look at this one? wouldn't this be a breaking change for all Vue3 users who are not on the latest version?

**Comment by chakAs3** [comment]
@Blackfaded, It is normal now, Just wait for the next stable release or alpha release  it will automatically support 3.3.0
