### ISSUE TITLE
[Bug]: Storybook 7 viewport menu not working

### ISSUE THREAD

**Issue by romi103** [storybookjs/storybook#22718]
### Describe the bug

The viewport button in the top buttons bar does not update the screen size anymore.

- Storybook 7
- Vite 
- TS 
  

### To Reproduce

https://stackblitz.com/github/storybookjs/sandboxes/tree/next/vue3-vite/default-ts/after-storybook?file=README.md&preset=node

**Comment by shilman** [comment]
Son of a gun!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.1.0-alpha.26 containing PR #22829 that references this issue. Upgrade today to the `@future` NPM tag to try it out!

```
npx sb@next upgrade --tag future
```
