### ISSUE TITLE
[Bug]: keyword "private" is not working in the constructor

### ISSUE THREAD

**Issue by Jong1co** [storybookjs/storybook#22752]
### Describe the bug

The following code is not working :

```
// dateFilter.ts

export class DateFilter extends RootDateFilter {
  private root: IDateFilter;

  constructor(private mode: FilterMode, private week: number | null) {.  <<< is not working
    super();
    this.mode = mode;
    this.week = week;
    this.root = createFilter(this.mode, this.week);
  }

```

```
// error message
in ./src/utils/dateFilter/dateFilter.ts 44:22
Module parse failed: The keyword 'private' is reserved (44:22)
File was processed with these loaders:
```

but is working :

```
export class DateFilter extends RootDateFilter {
  private root: IDateFilter;
  private mode: FilterMode;
  private week: number | null;

  constructor(mode: FilterMode, week: number | null) {
    super();
    this.mode = mode;
    this.week = week;
    this.root = createFilter(this.mode, this.week);
  }
```

Why does the second code work and the first code doesn't work? 
I'd appreciate it if you could tell me why..!

**Comment by N-koder** [comment]
Because you pass the private keyword to the constructor in the first code snippet but not in the second that's why the second work and the first throw error!

**Comment by usman-web-dev** [comment]
> Because you pass the private keyword to the constructor in the first code snippet but not in the second that's why the second work and the first throw error!

WTF is that logic?

**Comment by freshollie** [comment]
Why has this only just started happening for me? I've not upgraded storybook as far as I understand?
