### ISSUE TITLE
[Project - Onboarding]: Adjust created dummy files and Storybook configuration

### ISSUE THREAD

**Issue by valentinpalkovic** [storybookjs/storybook#22784]
For the onboarding experience, we have to adjust the created dummy Stories slightly:

- All the button stories must be displayed in the center of the canvas. Add the appropriate layout setting in the meta section of the button Stories.
- Remove `Introduction.mdx` and introduce a new `Configure.mdx` file. @domyen, @cdedreuille What should the content of the `Configure.mdx` file be? Could you provide it in this ticket?

```[tasklist]
### Blockers
- [x] Configure.mdx content provided: https://github.com/storybookjs/addon-onboarding/issues/27
```

**Comment by yannbf** [comment]
@cdedreuille any news on the design for the mdx file?
@valentinpalkovic should the CLI template stories be changed for all projects or just the ones that will have the onboarding?

**Comment by valentinpalkovic** [comment]
> @valentinpalkovic should the CLI template stories be changed for all projects or just the ones that will have the onboarding?

Let's change only the ones, which have the onboarding for now.

**Comment by valentinpalkovic** [comment]
Second one. We will change the code in the onboarding
