### ISSUE TITLE
[Documentation]: Enable Framework-specific documentation

### ISSUE THREAD

**Issue by jonniebigodes** [storybookjs/storybook#22817]
### Describe the problem

Currently, the documentation is showing examples of how to use certain specific framework paradigms, which can cause readers issues as the way it's documented does not apply to their framework (e.g., [React Hooks with Angular](https://storybook.js.org/docs/angular/writing-stories/introduction#working-with-react-hooks)). With this the documentation needs to be updated, or put in place a mechanism that only shows the documentation when the user selects the appropriate framework.

See [related discussion](https://github.com/storybookjs/storybook/discussions/22403#discussioncomment-6011171)

### Additional context

N/A

**Comment by kylegach** [comment]
This was prematurely closed. The capability is now there, but the docs still need updated to use it.
