### ISSUE TITLE
[Bug]: `handlebars` encodes `=` character in patched pnpm dependency, breaks preview annotations in `@storybook/builder-webpack5`

### ISSUE THREAD

**Issue by askoufis** [storybookjs/storybook#22828]
### Describe the bug

PNPM injects a hash containing an `=` to the file path of patched dependencies, this looks something like `_patch_hash=xpvpw3nxoacxewbpf6zgrfgd4u_`. `handlebars` encodes this `=` to `&#x3D;`. AFAIK this is an intentional feature of handlebars.js, you can verify this in [the handlebars playground](https://handlebarsjs.com/playground.html#format=1&currentExample=%7B%22template%22%3A%22%7B%7Bfirstname%7D%7D%20%7B%7Bloud%20lastname%7D%7D%5Cn%22%2C%22partials%22%3A%5B%5D%2C%22input%22%3A%22%7B%5Cn%20%20firstname%3A%20%5C%22foo%3Dbar%5C%22%2C%5Cn%20%20lastname%3A%20%5C%22Katz%5C%22%2C%5Cn%7D%5Cn%22%2C%22output%22%3A%22foo%26%23x3D%3Bbar%20KATZ%5Cn%22%2C%22preparationScript%22%3A%22Handlebars.registerHelper('loud'%2C%20function%20(aString)%20%7B%5Cn%20%20%20%20return%20aString.toUpperCase()%5Cn%7D)%5Cn%22%2C%22handlebarsVersion%22%3A%224.7.7%22%7D) by putting an `=` in the input. This encoded character causes webpack to fail to resolve `previewAnnotations` that are injected via `handlebars`. This becomes an issue if you happen to have `pnpm patch`ed a dependency that contains a preview annotation. 

Relevant code:

https://github.com/storybookjs/storybook/blob/fc3b4b7843b77707e9c8936bf0a7880bf344f1c8/code/builders/builder-webpack5/src/preview/iframe-webpack.config.ts#L133-L144

Maybe you've patched an addon's preview annotation, or in my case we're symlinking the user's `.storybook/preview.js` file to a storybook config folder controlled by our framework (which users install as a dependency in their project). We do this because we have a pretty involved webpack config that we need to inject into storybook's webpack config, so we maintain control over `main.js`, while allowing users to provide their own `preview.js`.

You could argue a few things here:
- PNPM using `=` in paths isn't great (IMO), but I'm sure there's a reason for it
- `handlebars` encoding some characters for you makes it unfit for this specific purpose. You already double escape `\` anyway, so what's one more tweak to the handlebars output.
- We have a niche use case that's not worth supporting. I agree, but I think supporting pnpm patched dependencies is worth it, even though that's also a niche use case. 

### To Reproduce

1. Clone https://github.com/askoufis/storybook-repro
2. `pnpm install`
3. `pnpm run storybook`. Webpack can't resolve the file, storybook crashes.
4. Check out the previous commit (before [patching `@storybook/addon-interactions`](https://github.com/askoufis/storybook-repro/commit/d5a8438caf9057d3ecc7a757f2fad87d64fd416b)): `git checkout 1ac0916b180e505d3c281e8b301027d99a9a30c5`
5. `pnpm install`
6. `pnpm run storybook`. Storybook works fine.

### System

```shell
Environment Info:

  System:
    OS: macOS 13.4
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 18.16.0 - ~/.local/share/.volta/tools/image/node/18.16.0/bin/node
    Yarn: 1.22.19 - ~/.local/share/.volta/tools/image/yarn/1.22.19/bin/yarn
    npm: 9.5.1 - ~/.local/share/.volta/tools/image/node/18.16.0/bin/npm
    pnpm: 8.6.0 - ~/.local/share/.volta/bin/pnpm
  Browsers:
    Chrome: 113.0.5672.126
    Edge: 113.0.1774.57
    Safari: 16.5
  npmPackages:
    @storybook/addon-essentials: ^7.0.18 => 7.0.18
    @storybook/addon-interactions: ^7.0.18 => 7.0.18
    @storybook/addon-links: ^7.0.18 => 7.0.18
    @storybook/blocks: ^7.0.18 => 7.0.18
    @storybook/react: ^7.0.18 => 7.0.18
    @storybook/react-webpack5: ^7.0.18 => 7.0.18
    @storybook/testing-library: ^0.0.14-next.2 => 0.0.14-next.2
```

**Comment by shilman** [comment]
Hi @askoufis this is a pretty specific edge case. Any idea what we could change on the Storybook side to fix it?

**Comment by askoufis** [comment]
> Hi @askoufis this is a pretty specific edge case. Any idea what we could change on the Storybook side to fix it?

You're right, it is quite specific. However, `handlebars` was originally designed for templating HTML, as opposed to JS/TS source code templating, so I think it's worth tweaking how it's used to make it better fit the use case, that is specifically templating file paths.

I think there are a few potential options to fix this:
- Add another `replace` that un-encodes the `=` encoding. This is a bandaid fix that only fixes this specific issue, but does nothing to mitigate future encoding issues should they arise.
- Opt-out of [HTML escaping](https://handlebarsjs.com/guide/#html-escaping) by using triple curly braces in the template. This could be dangerous, but potentially viable if we can validate that the input is not malicious (somehow).
- Register a [custom handlebars helper](https://handlebarsjs.com/guide/#custom-helpers) that conditionally escapes certain character, or at least validates that the input is a file path or something before _not_ escaping it.

Luckily this appears to be the only place where `handlebars` from `@storybook/core-common` is used, so there's not much risk in tweaking it to fit the use case.

**Comment by temm1210** [comment]
How is it going? any update?? facing the same issue

**Comment by r34son** [comment]
Also facing

**Comment by LightScrool** [comment]
Was facing the same issue, fixed it with another patch.

Patch command:
```
pnpm patch @storybook/builder-webpack5@7.5.2
```

In file `dist/presets/preview-preset.js`
Replace this:
```
.replace(/\\/g,"\\\\")
```
With that:
```
.replace(/\\/g,"\\\\").replace("&#x3D;", "=")
```

In file `dist/index.js`
Replace this:
```
;return presets.apply("webpack",{},{...options,babelOptions,typescriptOptions,frameworkOptions})
```
With that:
```
,config = await presets.apply("webpack", {}, {...options, babelOptions, typescriptOptions, frameworkOptions}),obj = config.plugins[0]._staticModules,moduleKey = Object.keys(obj).find(key => key.endsWith('storybook-config-entry.js')),moduleValue = obj[moduleKey],moduleNewValue = moduleValue.replace("&#x3D;", "=");obj[moduleKey] = moduleNewValue;return config
```

**Comment by askoufis** [comment]
After upgrading my reproduction to the latest prelease version (8.4.0-alpha.6 at time of writing) the bug appears to be fixed. I'm guessing https://github.com/storybookjs/storybook/pull/29208 fixed the issue as `handlebars` is no longer used within Storybook.

@shilman Should I close this issue even though the fix hasn't be released in a stable version, or should it be kept open until 8.4.0 is released?

**Comment by shilman** [comment]
Thanks for following up on this @askoufis ! Let's close it as fixed. The fix is available in an alpha today and will be stable in a few weeks.
