### ISSUE TITLE
[Bug]: 7.0.18 Vue typescript regression on slot typing

### ISSUE THREAD

**Issue by Sidnioulz** [storybookjs/storybook#22853]
### Describe the bug

Before 7.0.18, specifically this PR https://github.com/storybookjs/storybook/pull/22814/files, I was able to define properties for slots in my StoryObj `args`:

```ts
export const SimpleSlotTest: StoryObj<typeof meta> = {
  args: {
    label: 'Storybook Day',
    header: () => h('h1', 'Header Text Slot'),
    default: () => 'Default Text Slot',
    footer: h('p', 'Footer VNode Slot'),
  }
}
```

Now, those properties are no longer visible in `args`'s computed type. We get the following TS error:

```
Object literal may only specify known properties, and 'header' does not exist in type 'Partial<{ readonly label?: string | undefined; key?: string | number | symbol | undefined; ref?: VNodeRef | undefined; ref_for?: boolean | undefined; ref_key?: string | undefined;...
```

This happens regardless of whether `defineSlots` is used to type slots on the Vue SFC file.

### To Reproduce

Use https://github.com/chakAs3/vue3-storybook-slots-examples for a MWE. Open `src/stories/ReactiveSlots.stories.ts` and notice args doesn't accept any of the slots keys any more.

### System

```shell
14:11 $ npx storybook@latest info
Need to install the following packages:
  storybook@7.0.18
Ok to proceed? (y) 

Environment Info:

  System:
    OS: Linux 6.2 Arch Linux
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
  Binaries:
    Node: 16.20.0 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.19.2 - /usr/bin/npm
  Browsers:
    Firefox: 111.0.1
  npmPackages:
    @storybook/addon-essentials: ^7.0.18 => 7.0.18 
    @storybook/addon-interactions: ^7.0.18 => 7.0.18 
    @storybook/addon-links: ^7.0.18 => 7.0.18 
    @storybook/blocks: ^7.0.18 => 7.0.18 
    @storybook/testing-library: ^0.0.14-next.2 => 0.0.14-next.2 
    @storybook/vue3: ^7.0.18 => 7.0.18 
    @storybook/vue3-vite: ^7.0.18 => 7.0.18
```

**Comment by kasperpeulen** [comment]
Thanks for the investigation @Sidnioulz! 
Maybe @johnsoncodehk knows what we can do best here?

We test our Vue type definitions with vue-tsc@1.7.8 in the monorepo. 
It just automatically bumped when regenerating the lock file.

**Comment by Sidnioulz** [comment]
The Volar devs confirmed, if I understood what they said properly, that 1.7.8 is indeed pre-prod and not yet intended to be released.

**Comment by kasperpeulen** [comment]
Thanks for confirming @Sidnioulz

Okay, great, so I will just use:
```json
  "dependencies": {
    "@storybook/core-client": "7.1.0-alpha.30",
    "@storybook/docs-tools": "7.1.0-alpha.30",
    "@storybook/global": "^5.0.0",
    "@storybook/preview-api": "7.1.0-alpha.30",
    "@storybook/types": "7.1.0-alpha.30",
    "ts-dedent": "^2.0.0",
    "type-fest": "^3.11.0",
    "vue-component-type-helpers": "latest"
  },
```
Or maybe I really should make it a peer dep right? So that the user can choose themself what version to use?

**Comment by Sidnioulz** [comment]
@kasperpeulen, https://www.npmjs.com/package/vue-component-type-helpers?activeTab=versions shows that `latest` is 1.6.5, whereas `next` is 1.7.11 as of today.

When we had 1.6.5, we had issues. With 1.7.8, it was fine, and we had a report that 1.6.4 worked too from our of our users (which I **did not** verify).

So if you want to set the dependency to a working version, I would say `latest` is not that, since it was the version that caused type issues for us.

**Comment by Sidnioulz** [comment]
In my IDE, I am not sure. I'm not on the official VSCode but a FOSS version that appears to have differently packaged / versioned extensions sometimes. Mine is 0.34.x and likely irrelevant.

I had a colleague with 1.6.5 in their IDE who did experience a TS bug related to the types of parameters for some event listeners defined with `defineEmits`. I had another report the bug I showed above where slots aren't in the arg types.

Locally with vue-tsc, my colleagues found that 1.6.4 works, 1.6.5 doesn't, and 1.7.x work. I will now reopen the MWE above and re-run vue-tsc with all three versions to confirm.
