### ISSUE TITLE
[Project - Onboarding]: Automate call to `storybook dev <url-params>` after `storybook init`

### ISSUE THREAD

**Issue by valentinpalkovic** [storybookjs/storybook#22871]
## Description

The purpose of this task is to automate the execution of the `storybook dev --initial-path /onboarding` command immediately after the storybook init command. Still, this enhancement should only apply to React-based frameworks. This adjustment will reduce the steps required to start a Storybook with custom parameters for React projects, making the development process more efficient.

## Prerequisite

This enhancement is only applicable to frameworks that use React. Other frameworks should not be affected by this change.

## Acceptance Criteria:

- Upon successful execution of storybook init, `storybook dev --initial-path /onboarding` should automatically be called, but only if the initialized project uses a React-based framework.
- The CLI option `--initial-path /onboarding` should be passed as arguments to the storybook dev command.
- In case storybook init fails for any reason, `storybook dev --initial-path /onboarding` should not be called and a meaningful error message should be logged.
- For non-React frameworks, `init` should also run `dev` automatically but without the onboarding flag.
- All existing functionality of storybook init and storybook dev should remain unaffected for React and non-React projects.
- Detection of React-based framework: The solution should accurately determine whether the framework of the initialized project is based on React.

**Comment by vanessayuenn** [comment]
I reckon we should make all successful `init`s automatically run `dev`(without the onboarding) for non-react frameworks as well. @shilman thoughts?

**Comment by shilman** [comment]
@vanessayuenn I agree!

**Comment by vanessayuenn** [comment]
I updated the acceptance criteria for non-react frameworks. Not that it's needed, @yannbf did the work in the [PR](https://github.com/storybookjs/storybook/pull/22928) already. :)

**Comment by shilman** [comment]
Jeepers creepers!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.20 containing PR #22964 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb@latest upgrade
```
