### ISSUE TITLE
[Bug]: @storybook/builder-webpack5 install fails with node 14

### ISSUE THREAD

**Issue by johnhunter** [storybookjs/storybook#22874]
### Describe the bug

We upgraded our Webpack from v4 to latest 5 and our storybook build is failing. Following the migration guide https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#webpack-5 I am unable to run `npx sb automigrate` as we are on node@14 and cannot upgrade yet.

Manually installing `@storybook/builder-webpack5` fails due to node>=16 requirement in `glob-promise`. I have raised an issue with them as I am unsure if this is a hard requirement https://github.com/ahmadnassri/node-glob-promise/issues/205

Is this just the glob-promise issue? or is there a hard requirement in storybook 6 to use node > 14?

Thanks.

### To Reproduce

Run `npm i -D @storybook/builder-webpack5`
Error output
```npm ERR! code ENOTSUP
npm ERR! notsup Unsupported engine for glob-promise@6.0.2: wanted: {"node":">=16"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm ERR! notsup Not compatible with your version of node/npm: glob-promise@6.0.2
npm ERR! notsup Not compatible with your version of node/npm: glob-promise@6.0.2
npm ERR! notsup Required: {"node":">=16"}
npm ERR! notsup Actual:   {"npm":"6.14.18","node":"14.21.3"}
```

### System

```shell
> To run storybook you need to have node 16 or higher

Relevant dependencies are:

- @storybook/react@6.5.16
- node@14.21.3
- webpack@5.84.1
- webpack-cli@5.1.1
```

**Comment by johnhunter** [comment]
Ok, I can workaround the dependency issue by using `engine-strict=false` in my `.npmrc`.

Running `build-storybook` with `core: { builder: 'webpack5' }` in main.js config gives me `Error: You must specify a framework in '.storybook/main.js' config.`.
Adding `framework: '@storybook/react'` makes no difference to the error.

**Comment by johnhunter** [comment]
Further docs in https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#framework-field-mandatory indicate the correct framework value is `'@storybook/react-webpack5'`. This triggers additional errors.

```
info => Loading presets
WARN   Failed to load preset: {"type":"presets"} on level 1
ERR! TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received an instance of Object
```
followed by
```
info => Compiling manager..
info => Compiling preview..
ERR! Error: You must specify a framework in '.storybook/main.js' config.
```

**Comment by vanessayuenn** [comment]
Hi @johnhunter, thank you for raising this. As of v7, Storybook requires node version 16 and above, so I am closing this issue. However, if you can confirm this issue also happens with node 16, please feel free to reopen. Thanks!

**Comment by johnhunter** [comment]
Thanks @vanessayuenn I'm no longer working on the project that had the issue, but it has upgraded to node@16 so someone may be able to verify if the issue is resolved.

cc @adrianbielawski

**Comment by vidal7** [comment]
If you are using Vue, Migration guide says that Node 16 is required but in reality, Node 16.14 is required since package @storybook/vue-webpack5 require Node 16.14 because of lru-cache@8.0.5
