### ISSUE TITLE
[Bug]: Storybook server needs an indexer for `.stories.yml` files

### ISSUE THREAD

**Issue by cosmicdreams** [storybookjs/storybook#22896]
### Describe the bug

Storybook server recently added support for a json indexer.  Storybook server 6.5 also supports a yaml indexer.  I continue to need that Yaml indexer for my integration purposes.  Storybook 7 doesn't have a yaml indexer yet.

### To Reproduce

(on a reponsitory that has .stories.yml files available to be indexed)
```
yarn storybook 
WARN 🚨 Unable to index ./web/core/profiles/demo_umami/themes/umami/components/my-component/my-component.stories.yml:
WARN   Error: No matching story indexer found for /var/www/html/web/core/profiles/demo_umami/themes/umami/components/my-component/my-component.stories.yml

```

**Comment by shilman** [comment]
Thanks for the heads up @cosmicdreams I'll try to fix it now

**Comment by shilman** [comment]
Ermahgerd!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.1.0-alpha.27 containing PR #22906 that references this issue. Upgrade today to the `@future` NPM tag to try it out!

```
npx sb@next upgrade --tag future
```

**Comment by shilman** [comment]
Boo-yah!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.20 containing PR #22906 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb@latest upgrade
```
