### ISSUE TITLE
[Bug]: Stories aren't loading on demand with storyStoreV7

### ISSUE THREAD

**Issue by stevezhu** [storybookjs/storybook#22904]
### Describe the bug

It doesn't seem like stories are loading on demand as stated here: https://storybook.js.org/docs/react/configure/overview#on-demand-story-loading

Correct me if I'm misunderstanding what the `storyStoreV7` option does, but it seems like all the stories are still being loaded regardless of which story is being viewed even when `storyStoreV7` is explicitly set to `true`.

Marked in the image below from the stackblitz reproduction, I only opened the `Button > Primary` story, but `Header.stories.tsx` and `Header.tsx` were still loaded.

Vite:
![image](https://github.com/storybookjs/storybook/assets/4130171/49d5b698-b990-4370-8744-d7ebbfd63ec5)

Webpack 5:
![image](https://github.com/storybookjs/storybook/assets/4130171/3fcfe8f5-b452-49e1-a6fd-088388821f5f)

### To Reproduce

Vite: https://stackblitz.com/edit/github-c8i1hr?file=.storybook%2Fmain.ts
Webpack5: https://stackblitz.com/edit/github-eha1rn?file=.storybook%2Fmain.ts

### System

(From stackblitz)

Vite:
```shell
Environment Info:
  System:
    OS: Linux 5.0 undefined
    CPU: (6) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @storybook/addon-essentials: ^7.1.0-alpha.26 => 7.1.0-alpha.26 
    @storybook/addon-interactions: ^7.1.0-alpha.26 => 7.1.0-alpha.26 
    @storybook/addon-links: ^7.1.0-alpha.26 => 7.1.0-alpha.26 
    @storybook/blocks: ^7.1.0-alpha.26 => 7.1.0-alpha.26 
    @storybook/react: ^7.1.0-alpha.26 => 7.1.0-alpha.26 
    @storybook/react-vite: ^7.1.0-alpha.26 => 7.1.0-alpha.26 
    @storybook/testing-library: ^0.0.14-next.2 => 0.0.14-next.2
```

Webpack5:
```shell
Environment Info:
 
  System:
    OS: Linux 5.0 undefined
    CPU: (6) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @storybook/addon-essentials: ^7.1.0-alpha.26 => 7.1.0-alpha.26 
    @storybook/addon-interactions: ^7.1.0-alpha.26 => 7.1.0-alpha.26 
    @storybook/addon-links: ^7.1.0-alpha.26 => 7.1.0-alpha.26 
    @storybook/blocks: ^7.1.0-alpha.26 => 7.1.0-alpha.26 
    @storybook/react: ^7.1.0-alpha.26 => 7.1.0-alpha.26 
    @storybook/react-webpack5: ^7.1.0-alpha.26 => 7.1.0-alpha.26 
    @storybook/testing-library: ^0.0.14-next.2 => 0.0.14-next.2
```

**Comment by shilman** [comment]
I believe that we prefetch the components before and after the currently-viewed component as an optimization and that's what you're seeing here. @tmeasday @ndelangen can you please confirm?

**Comment by tmeasday** [comment]
I think it's actually just when you mouse over them in the sidebar. When I load the repro in Vite, it doesn't load `Header` or `Page` until I do so.
