### ISSUE TITLE
[Bug]: The Meta docs component has no type for title, though it still works.

### ISSUE THREAD

**Issue by MWhite-22** [storybookjs/storybook#22910]
### Describe the bug

When using the `<Meta />` block from `@storybook/blocks`, there is no title prop available, and TS throws an error. Everything still works in the frontend, just an unhappy TS.

### To Reproduce

No title prop defined: 

<img width="587" alt="image" src="https://github.com/storybookjs/storybook/assets/37516851/f4a6ee1f-7faf-42d9-92da-bdce6e1e84aa">
<img width="1239" alt="image" src="https://github.com/storybookjs/storybook/assets/37516851/b7510963-3392-4610-830d-a7dc5149f83a">

### System

```shell
Environment Info:

  System:
    OS: macOS 13.4
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
  Browsers:
    Chrome: 114.0.5735.90
    Edge: 113.0.1774.57
    Firefox: 113.0.2
    Safari: 16.5
  npmPackages:
    @storybook/addon-a11y: ^7.0.18 => 7.0.18
    @storybook/addon-essentials: ^7.0.18 => 7.0.18
    @storybook/addon-interactions: ^7.0.18 => 7.0.18
    @storybook/blocks: ^7.0.18 => 7.0.18
    @storybook/react: ^7.0.18 => 7.0.18
    @storybook/react-vite: ^7.0.18 => 7.0.18
    @storybook/testing-library: ^0.1.0 => 0.1.0
    @storybook/types: ^7.0.18 => 7.0.18
```

**Comment by laozhu** [comment]
The same issue for me, but I am using @storybok/addon-docs

<img width="841" alt="image" src="https://github.com/storybookjs/storybook/assets/1212457/cf4b023a-edfb-4122-bf39-8f2824bf6ea2">

**Comment by VardaQuraishi** [comment]
Can I work on this issue ?  @shilman @MWhite-22

**Comment by shilman** [comment]
@VardaQuraishi Thank you for helping make Storybook better! 🙏  Please check out [how to contribute](https://storybook.js.org/docs/react/contribute/how-to-contribute) in our docs and feel free to ask questions in `#contributing` in [our Discord](https://discord.gg/storybook).

**Comment by MWhite-22** [comment]
@VardaQuraishi go for it mate! I haven’t started anything yet.

**Comment by aditya1** [comment]
Is this issue already fixed or I can take a stab at it soon?

**Comment by noobcoder6602** [comment]
@shilman @MWhite-22 
i have made a PR, would anyone of you please review it?
