### ISSUE TITLE
[Bug]: Single story hoisting doesn't work in v7

### ISSUE THREAD

**Issue by chimung** [storybookjs/storybook#22931]
### Describe the bug

I updated Button's story to only export one story with the same name to the component name.
I start using Storybook in v7 so idk whether or not it works in v6.
![image](https://github.com/storybookjs/storybook/assets/7089484/51d0032e-220a-4506-9214-9f0d02de4aef)

### To Reproduce

Projects I create in [codesandbox](https://codesandbox.io/p/github/chimung/storybook-v7-playground/bugs/single-story-hoisting?layout=%257B%2522sidebarPanel%2522%253A%2522GIT%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522clijrl1q3000b356kehf54id0%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522clijrl1q3000d356kplb3r7ox%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clijrl1q3000b356kehf54id0%2522%253A%257B%2522id%2522%253A%2522clijrl1q3000b356kehf54id0%2522%252C%2522activeTabId%2522%253A%2522clijrtv3e005p356kgoa6aqhv%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clijrl1q3000a356kd8c7t4i8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fstories%252FButton.stories.js%2522%252C%2522id%2522%253A%2522clijrn1hg00t9356kgomyj3oh%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522id%2522%253A%2522clijrtv3e005p356kgoa6aqhv%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522clijrl1q3000d356kplb3r7ox%2522%253A%257B%2522id%2522%253A%2522clijrl1q3000d356kplb3r7ox%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clijrmeak00i4356klqxcqna1%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clijrmfk3001mg2gbfm4l2dlf%2522%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A6006%252C%2522id%2522%253A%2522clijrmqeo00m0356kgvqd3e50%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%253Fpath%253D%252Fdocs%252Fexample-button--docs%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clijrmqeo00m0356kgvqd3e50%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### System

```shell
System:
    OS: Linux 5.15 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (2) x64 AMD EPYC
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.15.0 - /usr/local/bin/npm
  npmPackages:
    @storybook/addon-essentials: ^7.0.6 => 7.0.6 
    @storybook/addon-interactions: ^7.0.6 => 7.0.6 
    @storybook/addon-links: ^7.0.6 => 7.0.6 
    @storybook/blocks: ^7.0.6 => 7.0.6 
    @storybook/jest: ^0.1.0 => 0.1.0 
    @storybook/react: ^7.0.6 => 7.0.6 
    @storybook/react-vite: ^7.0.6 => 7.0.6 
    @storybook/testing-library: ^0.0.14-next.2 => 0.0.14-next.2
```

**Comment by tmeasday** [comment]
I think you'll need to remove the docs entry to get the single story hoisting. Try removing the `autodocs` tag.

**Comment by chimung** [comment]
> I think you'll need to remove the docs entry to get the single story hoisting. Try removing the `autodocs` tag.

Thanks for your quick response.
You're right. But it seems to use the default template for the story. Could I customize it by MDX ?

![image](https://github.com/storybookjs/storybook/assets/7089484/37deb6f0-0cc4-419b-916f-f51c84a744b0)

**Comment by tmeasday** [comment]
If you wanted just a docs page that rendered the story, you would need to put the story somewhere else. I don't believe we supported single story hoisting in this way in 6.5 though?

We hope to implement filtering of stories via tags in the future which would hit this use case (so you could filter the story rather than "putting it somewhere else").

**Comment by chimung** [comment]
@tmeasday looking forward to the solution via tags
