### ISSUE TITLE
[Bug]: "@storybook/react" is not published.  node/no-unpublished-import

### ISSUE THREAD

**Issue by JSON-FS** [storybookjs/storybook#22932]
### Describe the bug

I ran my linter to attempt to lint the project - this is where i encountered the errors. Note that these components and stories are the default files made by Storybook when I ran `npx storybook@latest init`.
![image](https://github.com/JSON-FS/repro-sb-gts-nopub-issue/assets/107381769/4e3a20c4-c781-4e01-be39-f99fff404e52)

### To Reproduce

Repo with the bug: https://github.com/JSON-FS/repro-sb-gts-nopub-issue

---

In order to reproduce this bug, basically:
1) I Installed the latest version of Next JS using `npx create-next-app@latest`. The screenshot below displays the options I chose
![image](https://github.com/JSON-FS/repro-sb-gts-nopub-issue/assets/107381769/a4ecb7f5-46f6-4e2b-96c0-c309fadba9f4)

2) I Installed [gts](https://github.com/google/gts) using `npm i gts`. This installed a lower version so I had to modify `package.json` to install a newer version `^4.0.1`. I ran `npm i` afterwards.
3) I create and configured `.eslintrc.js` so that it extends `gts`. I deleted the old `.eslintrc.json` to give priority to `.eslintrc.js`
4) I Installed Storybook using `npx storybook@latest init`
5) I ran prettier to format the code base. I made a npm script for this called `format`. So I can just do `npm run format`
6) I ran `npm run lint` to attempt to lint the project - this is where i encountered the errors. Note that these components and stories are the default files made by Storybook when I ran `npx storybook@latest init`.
![image](https://github.com/JSON-FS/repro-sb-gts-nopub-issue/assets/107381769/4e3a20c4-c781-4e01-be39-f99fff404e52)

### System

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 AMD Ryzen 7 4800H with Radeon Graphics
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (114.0.1823.37)
  npmPackages:
    @storybook/addon-essentials: ^7.0.18 => 7.0.18
    @storybook/addon-interactions: ^7.0.18 => 7.0.18
    @storybook/addon-links: ^7.0.18 => 7.0.18
    @storybook/blocks: ^7.0.18 => 7.0.18
    @storybook/nextjs: ^7.0.18 => 7.0.18
    @storybook/react: ^7.0.18 => 7.0.18
    @storybook/testing-library: ^0.0.14-next.2 => 0.0.14-next.2
```

### Additional context

The repo I linked only contains a very basic project that helps in displaying the linting errors. The actual project where I encountered this on is much bigger than this and contains multiple dependencies. Those dependencies are functioning as intended and are passing the linting process. It is only Storybook that fails the check for `node/no-unpublished-import`

**Comment by shilman** [comment]
Looks like you need to either move SB from your `devDependencies` to `dependencies` or fix your linting configuration. More info: https://stackoverflow.com/questions/67551956/node-no-unpublished-import-chai-is-not-published

Closing this because it doesn't appear to be a Storybook issue. Good luck!
