### ISSUE TITLE
[Bug]: No matching version found for @storybook/client-logger@7.0.20

### ISSUE THREAD

**Issue by DusanMilko** [storybookjs/storybook#22971]
### Describe the bug

Getting 
```
No matching version found for @storybook/client-logger@7.0.20
```

**Comment by shilman** [comment]
Sometimes the new packages take time to propagate in the npm registry. As far as I know this is a service issue in the npm registry.

Try waiting a few hours, clearing your npm cache, and re-running. New packages usually propagate within a few minutes, but I've seen it take up to 24h to propagate.

If you're in a rush, manually decrement the version and reinstall.
