### ISSUE TITLE
[Bug]: Build hangs at "Output directory"

### ISSUE THREAD

**Issue by pm0u** [storybookjs/storybook#22985]
### Describe the bug

We have a storybook setup using the NextJS framework and it seems to randomly hang at the step of `info => Output directory: /vercel/path0/apps/joinhandshake-web/storybook-static`

Output from recent build on Vercel: https://gist.github.com/pm0u/7e58e553cf3eee2ea07d9fc086d4a095

At this point it will hang for up to 45mins, which is the maximum build time on Vercel. It does also occasionally happen locally on MacOS. It does not happen every build.

```json

  "dependencies": {
    "@headlessui/react": "^1.7.13",
    "@portabletext/react": "^2.0.0",
    "@sanity/client": "^6.1.1",
    "@sanity/image-url": "^1.0.1",
    "@types/async-retry": "^1.4.5",
    "@types/node": "^18.15",
    "@types/react": "~18.0.28",
    "@types/react-dom": "~18.0.11",
    "async-retry": "^1.3.3",
    "class-variance-authority": "^0.4.0",
    "cross-env": "^7.0.3",
    "interactjs": "^1.10.17",
    "jose": "^4.11.4",
    "lottie-react": "^2.4.0",
    "moment": "^2.29.4",
    "next": "13.3.1",
    "next-plugin-preval": "^1.2.4",
    "next-sanity": "^4.3.2",
    "next-sanity-image": "^6.0.0",
    "pixi.js": "^6.0.4",
    "postcss-media-minmax": "^5.0.0",
    "puppeteer": "^19.7.1",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-gist": "^1.2.4",
    "react-youtube": "^10.1.0",
    "schema-dts": "^1.1.2",
    "sharp": "^0.31.3",
    "typescript": "4.9.3"
  },
  "devDependencies": {
    "@next/bundle-analyzer": "^13.1.2",
    "@storybook/addon-a11y": "^7.0.18",
    "@storybook/addon-actions": "7.0.18",
    "@storybook/addon-essentials": "7.0.18",
    "@storybook/addon-interactions": "7.0.18",
    "@storybook/addon-links": "7.0.18",
    "@storybook/blocks": "7.0.18",
    "@storybook/nextjs": "7.0.18",
    "@storybook/react": "7.0.18",
    "@types/twitter-for-web": "^0.0.2",
    "@typescript-eslint/eslint-plugin": "^5.47.0",
    "autoprefixer": "^10.4.13",
    "eslint": "8.28.0",
    "eslint-config-next": "13.1.2",
    "eslint-config-prettier": "^8.5.0",
    "eslint-config-standard-with-typescript": "^24.0.0",
    "eslint-mdx": "^2.0.5",
    "eslint-plugin-import": "^2.26.0",
    "eslint-plugin-mdx": "^2.0.5",
    "eslint-plugin-n": "^15.6.0",
    "eslint-plugin-promise": "^6.1.1",
    "eslint-plugin-storybook": "^0.6.8",
    "eslint-plugin-tailwindcss": "^3.12.1",
    "file-loader": "^6.2.0",
    "postcss": "^8.4.21",
    "prettier": "^2.8.1",
    "prettier-plugin-tailwindcss": "^0.2.6",
    "sass": "^1.57.1",
    "storybook": "7.0.18",
    "stylelint": "^15.4.0",
    "stylelint-config-prettier": "^9.0.4",
    "stylelint-config-standard": "^32.0.0",
    "stylelint-prettier": "^3.0.0",
    "tailwindcss": "^3.3.2",
    "typescript-plugin-css-modules": "^5"
  }
```

This seems to have started with the upgrade to v7 and has occurred from versions `7.0.4` to `7.0.18`. The first deployment we had this occur on, this is the package.json:

```json
  "dependencies": {
    "@headlessui/react": "^1.7.13",
    "@portabletext/react": "^2.0.0",
    "@sanity/client": "^5.0.0",
    "@sanity/image-url": "^1.0.1",
    "@types/async-retry": "^1.4.5",
    "@types/node": "^18.15",
    "@types/react": "~18.0.28",
    "@types/react-dom": "~18.0.11",
    "async-retry": "^1.3.3",
    "class-variance-authority": "^0.4.0",
    "interactjs": "^1.10.17",
    "jose": "^4.11.4",
    "lottie-react": "^2.4.0",
    "next": "13.3.1",
    "next-plugin-preval": "^1.2.4",
    "next-sanity": "^4.1.5",
    "next-sanity-image": "^6.0.0",
    "pixi.js": "^6.0.4",
    "postcss-media-minmax": "^5.0.0",
    "puppeteer": "^19.7.1",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-youtube": "^10.1.0",
    "schema-dts": "^1.1.2",
    "sharp": "^0.31.3",
    "typescript": "4.9.3"
  },
  "devDependencies": {
    "@next/bundle-analyzer": "^13.1.2",
    "@storybook/addon-a11y": "^7.0.4",
    "@storybook/addon-actions": "^7.0.4",
    "@storybook/addon-essentials": "^7.0.4",
    "@storybook/addon-interactions": "^7.0.4",
    "@storybook/addon-links": "^7.0.4",
    "@storybook/blocks": "^7.0.4",
    "@storybook/nextjs": "^7.0.4",
    "@storybook/react": "^7.0.4",
    "@typescript-eslint/eslint-plugin": "^5.47.0",
    "autoprefixer": "^10.4.13",
    "eslint": "8.28.0",
    "eslint-config-next": "13.1.2",
    "eslint-config-prettier": "^8.5.0",
    "eslint-config-standard-with-typescript": "^24.0.0",
    "eslint-mdx": "^2.0.5",
    "eslint-plugin-import": "^2.26.0",
    "eslint-plugin-mdx": "^2.0.5",
    "eslint-plugin-n": "^15.6.0",
    "eslint-plugin-promise": "^6.1.1",
    "eslint-plugin-storybook": "^0.6.8",
    "eslint-plugin-tailwindcss": "^3.10.1",
    "file-loader": "^6.2.0",
    "jiti": "^1.18.2",
    "postcss": "^8.4.21",
    "prettier": "^2.8.1",
    "prettier-plugin-tailwindcss": "^0.2.6",
    "sass": "^1.57.1",
    "storybook": "^7.0.4",
    "stylelint": "^15.4.0",
    "stylelint-config-prettier": "^9.0.4",
    "stylelint-config-standard": "^32.0.0",
    "stylelint-prettier": "^3.0.0",
    "tailwindcss": "^3.3.1",
    "typescript-plugin-css-modules": "^5"
  }
  ```
  
  The previous commit had the following package.json:
  
  ```json
    "dependencies": {
    "@headlessui/react": "^1.7.13",
    "@portabletext/react": "^2.0.0",
    "@sanity/client": "^5.0.0",
    "@sanity/image-url": "^1.0.1",
    "@types/async-retry": "^1.4.5",
    "@types/node": "^18.15",
    "@types/react": "~18.0.28",
    "@types/react-dom": "~18.0.11",
    "async-retry": "^1.3.3",
    "class-variance-authority": "^0.4.0",
    "eslint-plugin-tailwindcss": "^3.10.1",
    "interactjs": "^1.10.17",
    "jose": "^4.11.4",
    "lottie-react": "^2.4.0",
    "next": "13.3.1",
    "next-plugin-preval": "^1.2.4",
    "next-sanity": "^4.1.5",
    "next-sanity-image": "^6.0.0",
    "pixi.js": "^6.0.4",
    "postcss-media-minmax": "^5.0.0",
    "puppeteer": "^19.7.1",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-youtube": "^10.1.0",
    "schema-dts": "^1.1.2",
    "sharp": "^0.31.3",
    "typescript": "4.9.3"
  },
  "devDependencies": {
    "@next/bundle-analyzer": "^13.1.2",
    "@storybook/addon-a11y": "^7.0.4",
    "@storybook/addon-actions": "^7.0.4",
    "@storybook/addon-essentials": "^7.0.4",
    "@storybook/addon-interactions": "^7.0.4",
    "@storybook/addon-links": "^7.0.4",
    "@storybook/blocks": "^7.0.4",
    "@storybook/nextjs": "^7.0.4",
    "@storybook/react": "^7.0.4",
    "@swc-node/register": "^1.6.3",
    "@swc/core": "^1.3.44",
    "@typescript-eslint/eslint-plugin": "^5.47.0",
    "autoprefixer": "^10.4.13",
    "eslint": "8.28.0",
    "eslint-config-next": "13.1.2",
    "eslint-config-prettier": "^8.5.0",
    "eslint-config-standard-with-typescript": "^24.0.0",
    "eslint-mdx": "^2.0.5",
    "eslint-plugin-import": "^2.26.0",
    "eslint-plugin-mdx": "^2.0.5",
    "eslint-plugin-n": "^15.6.0",
    "eslint-plugin-promise": "^6.1.1",
    "eslint-plugin-storybook": "^0.6.8",
    "file-loader": "^6.2.0",
    "postcss": "^8.4.21",
    "prettier": "^2.8.1",
    "prettier-plugin-tailwindcss": "^0.2.6",
    "sass": "^1.57.1",
    "storybook": "^7.0.4",
    "stylelint": "^15.4.0",
    "stylelint-config-prettier": "^9.0.4",
    "stylelint-config-standard": "^32.0.0",
    "stylelint-prettier": "^3.0.0",
    "tailwindcss": "^3.3.1",
    "typescript-plugin-css-modules": "^5"
  }
  ```
  
  There were 2 changes - adding jiti (which has now been removed in the latest/first package.json, problem persists) and moving `eslint-plugin-tailwindcss` to devDeps - I don't think either of these changes are likely culprits.
  
Other things I've tried:
- removing any stories that had SCSS dependencies, still persisted

### System

```shell
Environment Info:

  System:
    OS: macOS 12.6.5
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.15.0/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
  Browsers:
    Chrome: 114.0.5735.106
    Firefox: 112.0.2
    Safari: 16.5
```

**Comment by pm0u** [comment]
I've also tried running a build with DEBUG=* but there were no obvious errors or useful output at the end of the log.

I've also tried to utilize why is node running, but with this happening so infrequently it is difficult or impossible to have this work.

**Comment by pm0u** [comment]
Similar issues:
https://github.com/storybookjs/storybook/issues/15227
https://github.com/storybookjs/storybook/issues/15294

**Comment by pm0u** [comment]
I've created a debug script that I think we will use for builds going forward to help pinpoint the issue. If we use this on every build hopefully in a few days we can get a useful log

```js
// @ts-check
// @ts-expect-error
const log = require("why-is-node-running")
const { spawn } = require("node:child_process")

/** @type {NodeJS.Timer} */
let interval

// wait 45 seconds, then every few seconds log why node is running
const timeout = setTimeout(() => {
  interval = setInterval(() => {
    console.log(">>>> LOG <<<<<<")
    log()
    console.log(">>>> END LOG <<<<<<")
  }, 3000)
}, 45000)

const storybook = spawn("storybook", ["build"], {
  stdio: "inherit",
})

// When storybook is done building, close up our intervals so the process can end
storybook.on("close", () => {
  clearTimeout(timeout)
  clearInterval(interval)
})
```

**Comment by pm0u** [comment]
Had a deployment fail today and the output of the above script was this:
```


Storybook appears to be stuck, outputting what is running...

11:18:08.529 |  
11:18:08.532 | Debugger listening on ws://127.0.0.1:9229/5d3297c5-2c8a-445c-8239-5a7e944992b8
11:18:08.532 | For help, see: https://nodejs.org/en/docs/inspector
11:18:09.541 |  
11:18:09.542 | Killing storybook process...


```

not what I expected to see, not sure what that means?

**Comment by pm0u** [comment]
I have confirmed on multiple builds that there is nothing output from the why is node running process when this gets stuck:

```
info
 => Output directory: /Users/pmourer/Git/joinhandshake-headless-2.0/apps/joinhandshake-web/storybook-static



Storybook appears to be stuck, sending -SIGUSR1 to PID 82180...


Killing storybook process...


Exiting...
```

This happens for me (both getting stuck and no output from why-is-node-running) locally as well as in CI. It would be great to get some input for how to debug this further from the storybook team.

**Comment by shilman** [comment]
Thanks @pm0u for your detailed report & debugging attempts. I've reached out to our team to see if there are any suggestions for how to better track this down.

I'm guessing this is something specific to your setup and it would be hard to create a standalone reproduction for, but if you're up for trying you can check out https://storybook.new or see [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce). Thank you! 🙏

**Comment by pm0u** [comment]
@shilman totally understand, it'll take a little time for me to create a repro as there is quite a few moving parts in the original project.

In the meantime, after @osovv suggested changing that particular line/file I found it here:

https://github.com/storybookjs/storybook/blob/8b9ffc74d8e3b34a337962e049a85898f1abdcf6/code/lib/core-server/src/build-static.ts#L218-L233

This led me to wonder if the culprit could be some separate thread/task that is spurred by the telemetry reporting (which would lead to now output from the main storybook thread). For now, I have disabled telemetry on our CI builds and this seems to have immediately improved the issue. I had one particular branch where this seemed to hang pretty reliably and it has now proceeded without issue across several builds. I'm going to continue monitoring.

**Comment by osovv** [comment]
@pm0u I originally disabled telemetry and it still hung up
So maybe it has nothing to do with telemetry reporting

**Comment by pm0u** [comment]
@osovv sorry to hear, going to continue to monitor to see if it resolves for us... best of luck in your search.

**Comment by tmeasday** [comment]
@pm0u I assume you are using node>11 so I would suggest that unref-ed thing is a red herring.

Given this isn't widely reported my first thought would be it is something unusual about your storybooks. @osovv are you using NextJS also? Do either of you have custom webpack configs in `main.js`?

**Comment by pm0u** [comment]
@tmeasday here is what my NextJS config looks like:

```js
module.exports = {
  reactStrictMode: true,
  swcMinify: true,
  images: {
    remotePatterns: [
      {
        hostname: "cdn.sanity.io",
        protocol: "https",
        pathname: `images/${process.env.NEXT_PUBLIC_SANITY_PROJECT_ID}/**`,
      },
    ],
    deviceSizes: [640, 750, 828, 1080, 1200, 1600, 1920, 2048, 3840],
  },
  rewrites: async () => {
    return [
      {
        source: "/apple-app-site-association",
        destination: "/apple-app-site-association.json",
      },
    ]
  },
}
```
This is exported and imported to the root `next.config.js`

```js
const nextConfig = require("./configs/next")
const createNextPluginPreval = require("next-plugin-preval/config")
const withNextPluginPreval = createNextPluginPreval()

let withBundleAnalyzer = (/** @type {any} */ args) => args

// test comment

if (process.env.ANALYZE === "true") {
  withBundleAnalyzer = require("@next/bundle-analyzer")({
    enabled: true,
  })
}

module.exports = withNextPluginPreval(withBundleAnalyzer(nextConfig))
```

And storybook config, which does include some env injections that end up in webpack I assume:

```js
const config = {
 stories: [], // omitted for brevity
 addons: [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/addon-interactions",
    "@storybook/addon-a11y",
  ],
  staticDirs: [
    {
      from: "../public",
      to: "public",
    },
    {
      from: "../storybook/static",
      to: "static",
    },
  ],
  framework: {
    name: "@storybook/nextjs",
    options: {},
  },
  core: {},
  webpackFinal: (config) => {
    const rules = config.module?.rules
    if (!rules) {
      throw new Error("No webpack rules found!")
    }

    // Adds next preval compatibility to storybook webpack
    rules.push({
      test: /\.preval\.(t|j)sx?$/,
      loader: require.resolve("next-plugin-preval/loader"),
    })
    return config
  },
  docs: {
    autodocs: "tag",
  },
  env: (config) => ({
    ...config,
    NEXT_PUBLIC_SANITY_PROJECT_ID:
      process.env.NEXT_PUBLIC_SANITY_PROJECT_ID ?? "",
    NEXT_PUBLIC_FACEBOOK_APP_ID: process.env.NEXT_PUBLIC_FACEBOOK_APP_ID ?? "",
    NEXT_PUBLIC_FACEBOOK_CLIENT_TOKEN:
      process.env.NEXT_PUBLIC_FACEBOOK_CLIENT_TOKEN ?? "",
  }),
}
```

I suppose the obvious red flag here is `next-plugin-preval` as this does make an asynchronous request during the webpack build but I don't see any other reported errors there of something similar. I could also try removing the bundle analyzer OR pointing storybook to the Next config that doesn't include those plugins (We would need preval, somehow to fetch "server side" data for the build. I suppose if this was the issue I could come up with a workaround).

**Comment by tmeasday** [comment]
@pm0u is your issue reproducable consistently? Is there some way you could try dropping the `next-plugin-preval` on a branch to see if it fixes it? It would definitely make sense to look at that first, as you say it's sticking out like a sore thumb here :).

IIUC the bundle analyzer isn't being used so I'd say is unlikely to be relevant.

**Comment by pm0u** [comment]
@tmeasday I did have one commit that at one point, inexplicably, seemed to get stuck reliably. I can look into seeing if dropping that works.

I will add, FWIW, the reason that particular branch/commit stopped hanging was because I disabled telemetry... since disabling telemetry we have had over 30+ deploys without issue. In the past this issue would pop up within a few deploys typically. Not saying this is resolved for certain, but there has at least been a change in behavior with telemetry disabled.

I will find some time to look into the preval plugin

**Comment by tmeasday** [comment]
Well I think the telemetry does do some requests in the background so it's believable that it could hold the process up waiting on them I guess. I'm not sure why it happens here and not elsewhere though 🤷

**Comment by tony-scio** [comment]
As one more data point, we were experiencing this hang about 1 in 5 runs on local macbook pro m1s. We had telemetry disabled in main.js. This wasn't enough (per the note in https://storybook.js.org/docs/react/configure/telemetry#how-to-opt-out that there is an event prior to processing main.js). Disabling it on the command line via `--disable-telemetry` appears to have made it rock solid.

**Comment by tmeasday** [comment]
Ok, interesting @tony-scio. We'll investigate. In the meantime, the `--disable-telemetry` flag seems like the workaround here.

**Comment by tmeasday** [comment]
@tony-scio what is this line? 

```
/private/var/tmp/_bazel_tony/7ebbc78ad9e9d4b46d567aa33c850b0b/execroot/com_github_askscio_scio/node_modules/storybook/index.js:4 - setInterval(log, 2000)
```

I don't see any such intervals in the SB codebase. What version are you on?

**Comment by tmeasday** [comment]
@tony-scio I'm not sure I know how to read that trace (are you sure it was the full thing?) but I don't see anything in there that looks like it has anything to do with telemetry. Most of the entries are coming from the builder which is a bit weird if building is done. I'm not sure about the `FSREQCALLBACK`s, there seem a lot of them from a lot of places that should be "finished".

If you disregard them, then what's left is basically just some calls from inside https://www.npmjs.com/package/@ndelangen/get-tarball, which is odd because it certainly isn't used at all (it's only used during `sb init` IIUC). 

You could try commenting out the import of it ([here](https://github.com/storybookjs/storybook/blob/47446f4aa213d8bf65ce5f59223b02c83a4901b0/code/lib/cli/src/dirs.ts#L3) in the source code), and see how that affects things?

**Comment by lawlesscreation** [comment]
To add, we've seen the same issue after updating from SB 6 to 7 using Node 18. Setting `core: { disableTelemetry: true },` in the main.ts file did not work, but running stencil build with the `--disable-telemetry` flag did work. Not really a fix, but a workaround at least. Thanks

**Comment by filipw01** [comment]
in my case it was because I had some stories fully commented out, they were mentioned at the top of the logs, but the process didn't quit it was stuck instead

**Comment by RetroGameDeveloper** [comment]
This happened to me on a brand new NX project with storybook added exactly as the guide instructs, what fixed it for me was running:
```bash
npm install @base2/pretty-print-object --save
```

This was because I was getting the error:
```
WARN Module Warning (from ../../node_modules/source-map-loader/dist/cjs.js):
WARN Failed to parse source map from '/Users/a/Documents/project/node_modules/@base2/pretty-print-object/src/index.ts' file: Error: ENOENT: no such file or directory, open '/Users/a/Documents/project/node_modules/@base2/pretty-print-object/src/index.ts'
```

**Comment by tijhaart** [comment]
What worked for me was exiting the process after a successful webpack build.

In `.storybook/main.ts` I've added webpackFinal to the Storybook config like below:

```ts
webpackFinal: (config) => {
    config.plugins?.push({
      apply: (compiler) => {
        compiler.hooks.done.tap('BuildDonePlugin', () => {
          setTimeout(() => process.exit());
        });
      },
    });

    return config;
  },
```

Update: this should only used when running inside a CI because this will stop the storybook server when running stories locally.

Updated version which works locally and on the CI.

```ts
  webpackFinal: (config) => {
    const { mode } = config;

    if (mode !== 'development') {
      config.plugins?.push({
        apply: (compiler) => {
          compiler.hooks.done.tap('BuildDonePlugin', () => {
            setTimeout(() => process.exit());
          });
        },
      });
    }

    return config;
  },
```
