### ISSUE TITLE
[Feature Request]: Support for React 18 async Server Components

### ISSUE THREAD

**Issue by thetif** [storybookjs/storybook#22988]
### Is your feature request related to a problem? Please describe

I would really love to be able to take advantage of React's new async Server Components and be able to write stories for them, but that doesn't seem possible at the moment.

### Describe the solution you'd like

I would like for Stories to be written for Server Components that are sync.

### Describe alternatives you've considered

I could re-write my components to not be async, not be server components, or not have stories, but it would be great if they could.

### Are you able to assist to bring the feature to reality?

no

### Additional context

I might be able to help bring this feature to reality if someone can point me to where this would need to be implemented.

**Comment by shilman** [comment]
Hey @thetif, thanks for filing. Closing this as a dupe to #21540, please upvote there!
