### ISSUE TITLE
[Bug]: Github Action broken

### ISSUE THREAD

**Issue by nick** [storybookjs/storybook#23037]
### Describe the bug

The `chromaui/action@v1` GitHub action seems to have broken in the last day or so
<img width="797" alt="image" src="https://github.com/storybookjs/storybook/assets/939/3a405396-9a5d-4ba3-8e22-c31880ac694c">

**Comment by filipw01** [comment]
Duplicate of https://github.com/chromaui/chromatic-cli/issues/762
