### ISSUE TITLE
[Feature Request]: Allow ESM .mjs files for CSF stories

### ISSUE THREAD

**Issue by idesigncode** [storybookjs/storybook#23078]
### Is your feature request related to a problem? Please describe

Can't use ESM `.stories.mjs` files for CSF stories without additional configuration.

### Describe the solution you'd like

The default test for the `csfIndexer` should also include the `.mjs` file type, for example:  
```js
/(stories|story)\.m?[tj]sx?$/,
```

### Describe alternatives you've considered

My current workaround is to manually extend the test for the `csfIndexer`:

```js
// .storybook/main.mjs

export default {
  // ...
  storyIndexers: (indexers) => {
    return indexers.map((indexer) => {
      if (`${indexer.test}`.includes(`[tj]sx?$`)) {
        return {
          ...indexer,
          test: /(stories|story)\.m?[tj]sx?$/,
        };
      }
      return indexer;
    });
  };
```

This works fine but it feels like unnecessary config that may eventually break.

### Are you able to assist to bring the feature to reality?

yes, I can

### Additional context

I am currently only working with CSF stories so I am unsure if there are other configurations that may also need to be considered for non-CSF stories.

**Comment by shilman** [comment]
@idesigncode Want to open a PR for that? Sounds like a slam dunk!

**Comment by idesigncode** [comment]
@shilman will do!
