### ISSUE TITLE
[Feature Request]: Add ability to disable dev starting info

### ISSUE THREAD

**Issue by syabro** [storybookjs/storybook#23127]
### Is your feature request related to a problem? Please describe

Every time I run `dev` command I see
```
╭────────────────────────────────────────────────────╮
│                                                    │
│   Storybook 7.0.22 for react-vite started          │
│   155 ms for manager and 2.37 s for preview        │
│                                                    │
│    Local:            http://localhost:6006/        │
│    On your network:  http://192.168.0.124:6006/    │
│                                                    │
╰────────────────────────────────────────────────────╯
```

But I want my log blank - I want to see only errors there. 

### Describe the solution you'd like

`--quiet` or something like should disable

### Are you able to assist to bring the feature to reality?

yes, I can

**Comment by shilman** [comment]
that sounds very reasonable! any chance you can put together a PR to improve `--quiet` per your request?

**Comment by syabro** [comment]
@shilman will try
