### ISSUE TITLE
[Bug]: ReferenceError: Can't find variable `__STORYBOOK_MODULE_CHANNELS__`

### ISSUE THREAD

**Issue by JesusTheHun** [storybookjs/storybook#23136]
### Describe the bug

I've got this error when I start storybook :

> [Debug] [vite] connecting... (client, line 206)
[Error] ReferenceError: Can't find variable: __STORYBOOK_MODULE_CHANNELS__
[Debug] [vite] connected. (client, line 286)

The error is located at `Module Code (setup-addons.js:1)`

### System

```shell
Environment Info:

  System:
    OS: macOS 13.4
    CPU: (12) arm64 Apple M2 Max
  Binaries:
    Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
    Yarn: 3.1.1 - ~/.nvm/versions/node/v18.13.0/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v18.13.0/bin/npm
  Browsers:
    Chrome: 114.0.5735.133
    Firefox: 109.0
    Safari: 16.5
  npmPackages:
    @storybook/addon-essentials: 7.1.0-alpha.36 => 7.1.0-alpha.36 
    @storybook/addon-interactions: 7.1.0-alpha.36 => 7.1.0-alpha.36 
    @storybook/addon-links: 7.1.0-alpha.36 => 7.1.0-alpha.36 
    @storybook/blocks: 7.1.0-alpha.36 => 7.1.0-alpha.36 
    @storybook/channels: 7.1.0-alpha.36 => 7.1.0-alpha.36 
    @storybook/react: 7.1.0-alpha.36 => 7.1.0-alpha.36 
    @storybook/react-vite: 7.1.0-alpha.36 => 7.1.0-alpha.36 
    @storybook/testing-library: 0.2.0-next.0 => 0.2.0-next.0
```

### Additional context

I upgraded from 6.5.x, nothing special to mention during the migration.
I tried version `7.0.20`, `7.0.22` and `7.1.0-alpha.36`. All have the issue.

Probably unrelated, but I also notice that just after starting storybook, the server logs `.env.test changed, restarting server...`, while the file has not changed at all.

**Comment by JesusTheHun** [comment]
```html
<!-- .storybook/preview-head.html -->
<script rel="preload" src="/config.js" />
```

```js
// config.js
window.APP_CONFIG = { ... };
```

If I remove the script to import the config, Storybook works.

**Comment by Clarkkkk** [comment]
The problem still exists in `7.6.1`

![image](https://github.com/storybookjs/storybook/assets/66827108/c689952b-61e3-48df-85e4-486773ca7ed9)

**Comment by shilman** [comment]
Did you try removing `node_modules` and/or lockfiles and reinstalling?

**Comment by Clarkkkk** [comment]
I cannot reproduce the issue in another project. And the problem is gone refreshing the page manually for several times. I tried removing the node_modules folder and reinstalling and it didn't help.

**Comment by Clarkkkk** [comment]
I think it has something to do with `qiankun`. I use `vite-plugin-qiankun` in the project. Here is a reproduction: https://stackblitz.com/edit/vitejs-vite-skcmru?file=vite.config.ts

**Comment by Clarkkkk** [comment]
A workaround is to provide a custom vite config file following the [doc](https://storybook.js.org/docs/builders/vite#override-the-default-configuration) and avoid using `vite-plugin-qiankun`.

**Comment by shilman** [comment]
@Clarkkkk From a very brief look at that plugin, it looks like it's doing something funny with the `window` object. So I suspect it's just a corner-case incompatibility that we probably won't fix on the Storybook side. If it comes up in too many places or somebody from the community can provide a reproduction & a clean fix, we'd consider merging it.
