### ISSUE TITLE
d[r] is not a function

### ISSUE THREAD

**Issue by robozb** [storybookjs/storybook#23154]
### Describe the bug

It appears randomly at first load of the page after build

The workaround is to reload the page

![image](https://github.com/storybookjs/storybook/assets/8656998/584e06ec-a187-4343-8027-b1c5d05a1ddf)

### System

```shell
"dependencies": {
    "@babel/runtime": "^7.20.13",
    "@emotion/react": "^11.10.6",
    "@emotion/styled": "^11.10.6",
    "@inovua/reactdatagrid-community": "^5.8.4",
    "@mui/icons-material": "^5.11.11",
    "@mui/material": "^5.11.11",
    "@mui/x-date-pickers": "^6.2.0",
    "@react-keycloak/web": "^3.4.0",
    "axios": "^1.3.4",
    "bootstrap": "^5.2.3",
    "dayjs": "^1.11.7",
    "detect-browser": "^5.3.0",
    "keycloak-js": "^21.0.1",
    "lodash": "^4.17.21",
    "moment": "^2.29.4",
    "nanoid": "^4.0.1",
    "react": "^18.2.0",
    "react-bootstrap": "^2.7.0",
    "react-bootstrap-typeahead": "^6.0.0",
    "react-datepicker": "^4.11.0",
    "react-dom": "^18.2.0",
    "react-pro-sidebar": "^1.0.0",
    "react-router-dom": "^6.8.2",
    "react-select": "^5.7.0",
    "web-vitals": "^2.1.4"
  },
  "devDependencies": {
    "@storybook/addon-essentials": "^7.0.20",
    "@storybook/addon-interactions": "^7.0.20",
    "@storybook/addon-links": "^7.0.20",
    "@storybook/addon-styling": "^1.1.0",
    "@storybook/blocks": "^7.0.20",
    "@storybook/react": "^7.0.20",
    "@storybook/react-vite": "^7.0.20",
    "@storybook/testing-library": "^0.0.14-next.2",
    "@types/react": "^18.0.27",
    "@types/react-dom": "^18.0.10",
    "@vitejs/plugin-react": "^3.1.0",
    "prop-types": "^15.8.1",
    "sass": "^1.58.3",
    "storybook": "^7.0.20",
    "typescript": "^4.9.3",
    "vite": "^4.1.0"
  }
```

**Comment by jackocnr** [comment]
I'm getting very similar: "R[i] is not a function", with the same stack trace as you, just different line/character numbers.

This occurs when I navigate to the root /storybook URL and then it redirects to the first doc in the list. If I navigate to the doc directly, the error does not occur (hence op saying refresh fixes the issue).

Another strange symptom is that although I built storybook in docs mode (with --docs flag), when I navigate to the root /storybook URL (and see the above error), both the docs and the stories show in the sidebar, until, like the op, I refresh, then everything works fine - the docs display properly and the stories do not show in the sidebar anymore.

UPDATE: I've now solved this issue, but I'm not 100% sure what did it. I suspect it was clearing my local storage values in chrome dev tools, tho I did also delete my whole /storybook directory and re-build so it could also have been that.
