### ISSUE TITLE
[Bug]: MSW mock service doesn't work in Vue3 unit testing environment, but it works correctly in the component development environment.

### ISSUE THREAD

**Issue by Cxz-web** [storybookjs/storybook#23168]
### Describe the bug

In component development, I use MSW to intercept Axios requests and return data, which works correctly. However, when running unit tests, I find that Axios cannot be intercepted.. What could be the problem?

**Comment by shilman** [comment]
Can you explain more about your unit tests or provide a reproduction? It's hard to know based on your current description of the problem. Also you might try asking on the addon-msw repo instead.
