### ISSUE TITLE
[Documentation]: Docs for @storybook/addon-storyshots-puppeteer are wrong as of v7

### ISSUE THREAD

**Issue by jaslloyd** [storybookjs/storybook#23213]
### Describe the problem

As of storybook v7 static builds of storybook are no longer supported. See this: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#dropped-support-for-file-urls

aka "So you now need to use a web server as described above."

This specific section is wrong:

```md
When running Puppeteer tests for your stories, you have two options:

...
- Have a static build of the storybook (for instance, using npm run build-storybook)
```

I would open a PR to update the docs myself but i want to start a conversation about how teams are suppose to approach this on CI. 

"Just" starting up a web server in CI is really going to be a no-go for a lot of companies...since their CI doesn't allow them to spin up random containers or servers during CI. This also dramatically increases the complexity of running these checks during a CI build.

**Comment by jonniebigodes** [comment]
The Storyshots addon is officially deprecated and will be removed in a future release of Storybook. To help with the transition process, we've created a [migration guide](https://storybook.js.org/docs/writing-tests/storyshots-migration-guide) for the available options and common use cases.
