### ISSUE TITLE
[Bug]: Compiled CSS is missing vendor prefixes, when Next.js does add them

### ISSUE THREAD

**Issue by sawyerh** [storybookjs/storybook#23234]
### Describe the bug

My project's CSS includes modern CSS syntax, such as the [`mask` property](https://developer.mozilla.org/en-US/docs/Web/CSS/mask#browser_compatibility). This property requires vendor prefixes (e.g. `-webkit-mask`) in order to properly render in Chrome.

When using the `@storybook/nextjs` framework, the CSS `mask` property is not being automatically prefixed in the processed CSS. However, Next.js does this for you, so this means the CSS shown in Storybook is somewhat broken compared to when the page is viewed 

**In Next.js**

![CleanShot 2023-06-27 at 13 40 12@2x](https://github.com/storybookjs/storybook/assets/371943/e91afb23-fcb6-46c8-b181-e6658b55683a)

**In Storybook**

![CleanShot 2023-06-27 at 13 41 27@2x](https://github.com/storybookjs/storybook/assets/371943/709d7b78-3774-46c5-99c4-911da3259497)

### To Reproduce

1. I've created a repo with a minimum reproduction of this issue: https://github.com/sawyerh/storybook-css-prefixing-bug
2. Run the Storybook in Chrome

### System

```shell
Environment Info:

  System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 18.12.1 - ~/.asdf/installs/nodejs/18.12.1/bin/node
    Yarn: 1.22.19 - ~/.asdf/installs/nodejs/18.12.1/bin/yarn
    npm: 8.19.2 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Chrome: 114.0.5735.133
    Safari: 16.5.1
  npmPackages:
    @storybook/nextjs: ^7.0.24 => 7.0.24
    @storybook/react: ^7.0.24 => 7.0.24
```
```


### Additional context

_No response_

**Comment by brandon-lent** [comment]
following

**Comment by sawyerh** [comment]
@sookmax Thanks for the quick response! It looks like adding the `postcss.config.js` does fix this in Storybook. For my project, the presence of `postcss-preset-env` in `package.json` was sufficent, and I didn't have to add `autoprefixer` as a direct dependency.

**Comment by ushakovfserg** [comment]
You need to be careful.
Adding `postcss.config.js` in project root disables default next.js internal postcss config.
According to [docs](https://nextjs.org/docs/pages/building-your-application/configuring/post-css#customizing-plugins) it is better to set the same as internal and modify it.

I created `postcss.config.js` like this
```
const MODERN_BROWSERSLIST_TARGET = require('next/dist/shared/lib/modern-browserslist-target');

/**
 * Default configuration for PostCSS in Next.js.
 * https://nextjs.org/docs/pages/building-your-application/configuring/post-css#customizing-plugins
 *
 * Required for correct CSS in storybook, because @storybook/nextjs doesn't support it.
 */
module.exports = {
  plugins: {
    'postcss-flexbugs-fixes': {},
    'postcss-preset-env': {
      browsers: MODERN_BROWSERSLIST_TARGET,
      autoprefixer: {
        flexbox: 'no-2009',
      },
      stage: 3,
      features: {
        'custom-properties': false,
      },
    },
  },
};
```
