### ISSUE TITLE
[Bug]: Component decorator isn't overriding global decorator

### ISSUE THREAD

**Issue by zeckdude** [storybookjs/storybook#23237]
### Describe the bug

Based on the [documentation on decorators](https://storybook.js.org/docs/react/writing-stories/decorators#decorator-inheritance), I would expect a component decorator to override a global decorator. It could be that I'm misunderstanding the functionality around the decorators and perhaps it is set up to add on to the decorator above it, but for my use case I need the global decorator to not be used for a specific set of stories for a component, so if this is not a bug, can you point me in the right direction?
<img width="880" alt="Screen Shot 2023-06-27 at 2 39 37 PM" src="https://github.com/storybookjs/storybook/assets/947856/936115de-b834-4d7f-96bf-16be9e8cce13">

What I'm seeing is that each decorator is just being nested within each other, but I want it to override it at the closer levels.

This bug seems to be related to: https://github.com/storybookjs/storybook/issues/12670

### To Reproduce

https://stackblitz.com/edit/github-6xn5b1

### System

```shell
Environment Info:

  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 16.20.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
  npmPackages:
    @storybook/addon-essentials: ^7.1.0-alpha.39 => 7.1.0-alpha.40 
    @storybook/addon-interactions: ^7.1.0-alpha.39 => 7.1.0-alpha.40 
    @storybook/addon-links: ^7.1.0-alpha.39 => 7.1.0-alpha.40 
    @storybook/addon-onboarding: ^1.0.3 => 1.0.3 
    @storybook/blocks: ^7.1.0-alpha.39 => 7.1.0-alpha.40 
    @storybook/nextjs: ^7.1.0-alpha.39 => 7.1.0-alpha.40 
    @storybook/react: ^7.1.0-alpha.39 => 7.1.0-alpha.40 
    @storybook/testing-library: ^0.2.0 => 0.2.0
```

### Additional context

**.storybook/preview.js**
```js
/** @type { import('@storybook/react').Preview } */
const preview = {
  decorators: [
    (Story, options) => {
      return (
        <div
          style={{
            padding: '100px',
            backgroundColor: 'red',
          }}
        >
          <Story />
        </div>
      );
    },
  ],
  parameters: {
    actions: { argTypesRegex: '^on[A-Z].*' },
    controls: {
      matchers: {
        color: /(background|color)$/i,
        date: /Date$/,
      },
    },
  },
};

export default preview;

```

**Page.stories.js**
```js
import { within, userEvent } from '@storybook/testing-library';
import { Page } from './Page';

export default {
  title: 'Example/Page',
  component: Page,
  decorators: [
    (Story, options) => {
      return (
        <div
          style={{
            padding: '50px',
            backgroundColor: 'green',
          }}
        >
          <Story />
        </div>
      );
    },
  ],
  parameters: {
    // More on how to position stories at: https://storybook.js.org/docs/react/configure/story-layout
    layout: 'fullscreen',
  },
};

export const LoggedOut = {
  decorators: [
    (Story) => (
      <div
        style={{
          padding: '25px',
          backgroundColor: 'blue',
        }}
      >
        <Story />
      </div>
    ),
  ],
};

// More on interaction testing: https://storybook.js.org/docs/react/writing-tests/interaction-testing
export const LoggedIn = {
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement);
    const loginButton = await canvas.getByRole('button', {
      name: /Log in/i,
    });
    await userEvent.click(loginButton);
  },
};

```

**Comment by sookmax** [comment]
@zeckdude Hey, I looked into what was actually processing the provided decorators, and I'm afraid _overriding_ more general decorators (e.g. ones in `.storybook/preview.tsx`) with more specific ones (e.g. ones in the default export or named exports in your story file) is _not_ possible with the current structure, unfortunately even in V7.

I might be wrong though since my understanding of how `decorators` are exactly processed is very shallow, but here are some relevant sections that I've found in the code base.

**code/lib/preview-api/src/modules/store/csf/prepareStory.ts**
```ts
// Inside `prepareStory` function

...

// It seems the decorators to be processed are just being merged into one array.
const decorators = [
    ...(storyAnnotations?.decorators || []),
    ...(componentAnnotations.decorators || []),
    ...(projectAnnotations.decorators || []),
];

...

const decoratedStoryFn = applyHooks<TRenderer>(applyDecorators)(undecoratedStoryFn, decorators);

...
```

It looks like the above _merged_ decorators are eventually processed here:

**code/lib/preview-api/src/modules/store/decorators.ts**
```ts
// Inside `defaultDecorateStory` function

...

// `decorators` here is passed as an argument (unmodified), and being applied one by one with `Array.reduce()`
const decoratedWithContextStore = decorators.reduce(
    (story, decorator) => decorateStory(story, decorator, bindWithContext),
    storyFn
);

...
```

I hope this helps a little. 

Cheers.

**Comment by chakAs3** [comment]
Hi @zeckdude  you can have conditional decorator on the preview like this: 
https://stackblitz.com/edit/github-6xn5b1-84haom?file=.storybook%2Fpreview.js

**Comment by zeckdude** [comment]
Thanks for your feedback @sookmax and @chakAs3! I actually found that workaround earlier today. It seems a bit of hack to me, but it works for now. If there is no way to add this as a feature in Storybook, then having the decorators override via a flag should be documented.

**Comment by chakAs3** [comment]
> Thanks for your feedback @sookmax and @chakAs3! I actually found that workaround earlier today. It seems a bit of a hack to me, but it works for now. If there is no way to add this as a feature in Storybook, then having the decorators override via a flag should be documented.

that is not a workaround @zeckdude it is how decorators work. in general, they are wrappers around the story,  and rendering a wrapper based on a condition seems natural in all UI renderers.  decorators construct your rendering Tree

**Comment by zeckdude** [comment]
> > Thanks for your feedback @sookmax and @chakAs3! I actually found that workaround earlier today. It seems a bit of a hack to me, but it works for now. If there is no way to add this as a feature in Storybook, then having the decorators override via a flag should be documented.
> 
> 
> 
> that is not a workaround @zeckdude it is how decorators work. in general, they are wrappers around the story,  and rendering a wrapper based on a condition seems natural in all UI renderers.  decorators construct your render-Tree.
> 
> 
> 
> so these wrappers are elements of your render tree, no one can override the other. but you can control how they are rendered using conditions 
> 
> 
> 
> ```js
> 
> <GlobalWrapper1>
> 
>    <GlobalWrapper2>
> 
>      <ComponentWrapper>
> 
>         <StoryWrapper1>
> 
>            <StoryWrapper2>
> 
>                <Story/>
> 
>            </StoryWrapper2>
> 
>         </StoryWrapper1>
> 
>      </ComponentWrapper>
> 
>    </GlobalWrapper2>
> 
> </GlobalWrapper1>
> 
> ```
> 
> so if you see StoryWrapper can't override any other wrapper 
> 
> 
> 
>      
> 
> 

If it's not a workaround, then it should be documented how to do all this. I shouldn't need to Google around in forums on how to affect it.

**Comment by kasir-barati** [comment]
BTW this is not a feasible solution in my case, I am loading fonts like this in my **`preview.tsx`**:

```tsx
decorators: [
  (Story) => (
    <div className={roboto.className}>
      <Story />
    </div>
  ),
],
```

And that `roboto` is your normal way of [loading fonts in a NextJS app](https://nextjs.org/docs/pages/building-your-application/optimizing/fonts#google-fonts). But there are components that have their own fonts:
```tsx
import Typography from '@mui/material/Typography';
import { Leckerli_One } from 'next/font/google';

const leckerliOne = Leckerli_One({
  style: 'normal',
  weight: '400',
  subsets: ['latin'],
});

export function SomeRandomComponent() {
  return (
    <Typography className={leckerliOne.className}>
     Some random component
    </Typography>
  );
}
```

And when you create a storybook for this component you have to use these custom ways of doing things while it works out of box when I run my project with NextJS. But that's not all, we loss our flexibility. This is a component meaning I wanna reuse it in other components and other parts of my app. So in those cases I guess I have even a harder time to get it working.

Find more info here: https://github.com/storybookjs/storybook/discussions/24055#discussioncomment-9274708

**Comment by JSMike** [comment]
FYI, I had a similar issue with overriding the sourceDecorator from @storybook/angular, my workaround was to make a local copy of the framework decorator that I needed to override and to override the framework decorator in my preview.ts

```js
import { myReplacementDecorator } from './local-path-to-file'; 
import { decorators } from '@storybook/angular/dist/client/docs/config';
decorators.splice(0, decorators.length, myReplacementDecorator);
```
