### ISSUE TITLE
[Bug]: React+Vite+TS PnP breaks type in `.storybook/main.ts > config.framework.name`

### ISSUE THREAD

**Issue by sni-J** [storybookjs/storybook#23232]
### Describe the bug

Storybook in yarn berry PnP & Vite (React + TS) creates type error in `.storybook/main.ts`
(and other vite frameworks might have same issue)

Initializing storybook generates following code in `.storybook/main.ts`...
```ts
import type { StorybookConfig } from "@storybook/react-vite";

const config: StorybookConfig = {
  // ...
  framework: {
    name: path.dirname(require.resolve(path.join("@storybook/react-vite", "package.json"))),
    options: {},
  },
  //...
```
... which are generated by ... https://github.com/storybookjs/storybook/blob/243ca403fc22495af179ebc5b135d6398e5c1ff2/code/lib/cli/src/generators/baseGenerator.ts#L365 https://github.com/storybookjs/storybook/blob/243ca403fc22495af179ebc5b135d6398e5c1ff2/code/lib/cli/src/generators/baseGenerator.ts#L223-L229 https://github.com/storybookjs/storybook/blob/243ca403fc22495af179ebc5b135d6398e5c1ff2/code/lib/cli/src/generators/baseGenerator.ts#L105-L120 https://github.com/storybookjs/storybook/blob/243ca403fc22495af179ebc5b135d6398e5c1ff2/code/lib/cli/src/generators/baseGenerator.ts#L102-L103

... and this conflicts with type of `framework.name` in `StorybookConfig`
https://github.com/storybookjs/storybook/blob/243ca403fc22495af179ebc5b135d6398e5c1ff2/code/frameworks/react-vite/src/types.ts#L8

Code above added in #20642, looks like PnP case was not considered.

Originally, type of `framework.name`, which was referring `StorybookConfig` from `@storybook/types`, was string and PR above narrowed it down to each framework's name https://github.com/storybookjs/storybook/blob/4f7342b509d4a396e42afc9a215047bed0a42c7b/code/lib/types/src/modules/core-common.ts#L325-L328 https://github.com/storybookjs/storybook/blob/4f7342b509d4a396e42afc9a215047bed0a42c7b/code/lib/types/src/modules/core-common.ts#L226-L231

AFAIK about typescript, it seems like `type FrameworkName = string` is the only way to solve this issue, but not so sure.
And it might lose advantages from strict typing.
(IMHO I love strict typing but in most case those values are created by generator so it doesn't look like huge advantage though)

Are there any other better solutions?

---
For somebody confronted same issue,
to bypass before this issue resolved, use `@ts-expect-error` like below.
```ts
// @ts-expect-error PnP resolution conflicts string literal type
name: path.dirname(require.resolve(path.join("@storybook/react-vite", "package.json"))),
```

### To Reproduce

1. Yarn berry with `nodeLinker: pnp`
2. `yarn create vite --template react-ts`
3. `yarn dlx storybook@latest init`

### System

--

### Additional context

--

**Comment by shilman** [comment]
@kasperpeulen is there an easy fix for this in TS metaprogramming land?

**Comment by kasperpeulen** [comment]
@shilman Should be doable, I actually thought @valentinpalkovic and @ndelangen already worked on this issue?

**Comment by ndelangen** [comment]
@kasperpeulen I thought you had some TypeScript trick to make something both a `string` but also keep the ts suggestions.

Do we think that's worth doing here? It it helpful?

**Comment by kasperpeulen** [comment]
I think it is helpful: `'literal' | 'other' | (string & {})` does the trick
