### ISSUE TITLE
[Bug]: Storybook 7.1.0 / React-vite - storybooks fail to load (works w/react-webpack5) - throws import error tied to react-dom-shim

### ISSUE THREAD

**Issue by nstuyvesant** [storybookjs/storybook#23245]
### Describe the bug

Started Storybook via `yarn storybook` (`npx storybook dev -p 9006`) for React project using @storybook/react-vite.

Tried opening in Chrome 114. This is what shows...

<img width="1233" alt="image" src="https://github.com/storybookjs/storybook/assets/5770938/8681a491-1e7a-4b9c-b657-45c41d8aacef">

JavaScript console error is "Uncaught SyntaxError: The requested module '/node_modules/react/index.js' does not provide an export named 'default' (at react-18.mjs:1:8)".

This is that line of code in node_modules/@storybook/react-dom-shim/dist/react-18.mjs...
```js
import ReactDOM from "/node_modules/react-dom/client.js";
```

### System

```shell
System:
    OS: macOS 13.4.1
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 18.16.1 - /opt/homebrew/bin/node
    Yarn: 3.5.1 - /opt/homebrew/bin/yarn
    npm: 9.7.2 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 114.0.5735.198
    Safari: 16.5.1
  npmPackages:
    @storybook/addon-essentials: ^7.1.0 => 7.1.0 
    @storybook/addon-interactions: ^7.1.0 => 7.1.0
    @storybook/addon-links: ^7.1.0 => 7.1.0
    @storybook/blocks: ^7.1.0 => 7.1.0
    @storybook/manager-api: ^7.1.0 => 7.1.0
    @storybook/react: ^7.1.0 => 7.1.0
    @storybook/react-vite: ^7.1.0 => 7.1.0
    @storybook/testing-library: ^0.2.0 => 0.2.0 
    @storybook/theming: ^7.1.0 => 7.1.0
```

**Comment by shilman** [comment]
@nstuyvesant which version are you upgrading from? have you tried cleaning node_modules and/or lockfiles? off the top of my head i don't know of anything that would cause this

**Comment by nstuyvesant** [comment]
Thanks for jumping in @shilman. I always do an `rm -rf node_modules/.cache` before running Storybook. This is that package that had issues running @storybook/react-vite so I had switched it to @storybook/react-webpack5. As it had been some time since I last tried it, I switched back to react-vite this morning to try it out but got this error instead of the original error I logged as ticket https://github.com/storybookjs/storybook/issues/22435. As it was different, thought I should report it separately.

Here's the background...
```bash
git clone https://github.com/carbon-design-system/carbon-charts.git
cd carbon-charts
yarn install
yarn build
cd packages/react
# then modify .storybook/main.ts to switch back to react-vite from react-webpack5
# then...
yarn storybook
```

**Comment by nstuyvesant** [comment]
@shilman - I'm not really a react developer but should https://github.com/storybookjs/storybook/blob/next/code/lib/react-dom-shim/src/react-18.tsx#L6C1-L7C1 be
```js
import * as ReactDOM from 'react-dom/client';
```
instead of `import ReactDOM from 'react-dom/client';`?

**Comment by nstuyvesant** [comment]
Here's how to quickly reproduce...
```bash
git clone https://github.com/nstuyvesant/carbon-charts.git
cd carbon-charts
git checkout fix-react-vite
yarn install
yarn build
cd packages/react
yarn storybook
```

**Comment by shilman** [comment]
Do you know if this is a 7.1 bug or if it was also present in 7.0 @nstuyvesant ?

**Comment by nstuyvesant** [comment]
Originally saw it in 7.0.24

**Comment by nstuyvesant** [comment]
But retested today

**Comment by nstuyvesant** [comment]
Wonder if this is related: https://github.com/vitejs/vite/issues/11783

The monorepo uses lerna which has nx as a dependency.

**Comment by unrealsolver** [comment]
I have relatively similar error: `SyntaxError: ambiguous indirect export: ReactComponent`. When trying to `import { ReactComponent as A } from './some.svg'`. Using Nx, vite, @storybook/react-vite. App itself have no issues.

**Comment by nstuyvesant** [comment]
Closing as duplicate of #24903
