### ISSUE TITLE
[Bug]: Storybook CSS being overridden by TailwindCSS

### ISSUE THREAD

**Issue by Evaske** [storybookjs/storybook#23260]
### Describe the bug

Ran through the official docs for using TailwindCSS in Storybook located here: https://storybook.js.org/recipes/tailwindcss

My components render correctly but I have noticed some of the StoryBook CSS seems to break. I guess it is being overridden by the Tailwind CSS?

![Screenshot 2023-06-30 at 10 12 58](https://github.com/storybookjs/storybook/assets/819492/76950e3c-0691-4adc-80ce-a60c8df152f2)

### To Reproduce

NextJS 13 with TailWind and latest Storybook following the official documentation of using Tailwind CSS with Storybook and running the command `node node_modules/@storybook/addon-styling/bin/postinstall.js`

### System

```shell
Environment Info:

  System:
    OS: macOS 13.4
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 16.19.1 - ~/.nvm/versions/node/v16.19.1/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.1/bin/npm
  Browsers:
    Chrome: 114.0.5735.198
    Safari: 16.5
  npmPackages:
    @storybook/addon-essentials: ^7.0.24 => 7.0.24 
    @storybook/addon-interactions: ^7.0.24 => 7.0.24 
    @storybook/addon-links: ^7.0.24 => 7.0.24 
    @storybook/addon-styling: ^1.3.2 => 1.3.2 
    @storybook/blocks: ^7.0.24 => 7.0.24 
    @storybook/nextjs: ^7.0.24 => 7.0.24 
    @storybook/react: ^7.0.24 => 7.0.24 
    @storybook/testing-library: ^0.0.14-next.2 => 0.0.14-next.2 
```
```


### Additional context

_No response_

**Comment by newtriks** [comment]
I'm finding similar behaviour but with a React/Vite project, however, the Storybook CSS is overriding the Tailwind CSS in MDX files :(
