### ISSUE TITLE
Storybook 7.0+ doesn't support react-scripts@<5.0.0.

### ISSUE THREAD

**Issue by chadhiremysub** [storybookjs/storybook#23283]
I am still having issues with this! I have react-scripts version 5.0.1, react version 18.2.0, and node version 16.20.1.

I have react-scripts in my dev-dependencies. Is this an issue?

<img width="1512" alt="image" src="https://github.com/storybookjs/storybook/assets/117949150/850ecc4c-71b6-4c2d-99b9-c100e43db125">

_Originally posted by @chadhiremysub in https://github.com/storybookjs/storybook/issues/22794#issuecomment-1612122203_

**Comment by valentinpalkovic** [comment]
The issue is currently only fixed on the prerelease branch and will be fixed in Storybook in v7.1.0 as soon as it is released. Could you try out the latest prerelease version?:

`npx storybook@next init`

**Comment by chadhiremysub** [comment]
@valentinpalkovic I was able to get the latest pre-release installed and launching correctly. This will get me by. Thanks!
