### ISSUE TITLE
[Documentation]: Update Change Log

### ISSUE THREAD

**Issue by lkarvec** [storybookjs/storybook#23280]
### Describe the problem

Current Change Log is from 7.0.21.  I'm not sure of what the current changes are, or if they would affect my project.

### Additional context

[Link to log](https://github.com/storybookjs/storybook/blob/next/CHANGELOG.md)

**Comment by kylegach** [comment]
Hi, @lkarvec. We were working on new release tooling and apparently broke the changelog generation for a bit in the process.

Thanks for reporting, and it looks like it's already been fixed.
