### ISSUE TITLE
7.1-beta QA Tasks

### ISSUE THREAD

**Issue by vanessayuenn** [storybookjs/storybook#23293]
# Project Leads
Project leads for each feature, please fill out the below task list you would like to get tested. Check off your feature to indicate that the QA steps are ready:
- [x] onboarding @valentinpalkovic 
- [x] styling addon @shilman @Integrayshaun 
- [x] vue3 @kasperpeulen 
- [x] Docs TOC @shilman 
- [x] changelog @kasperpeulen 

# Testers
- [ ] Copy the steps below
- [ ] Paste into a comment in this issue
- [ ] Specify the configurations of the projects you will be testing with. Aim to get good coverage by using a combination that hasn't been tested yet.
- [ ] Check off steps as you go to indicate progress
- [ ] Note down any bugs you encounter

-----
## Main features QA steps

```
### Onboarding
**testing with**: 
  - [ ] 1. Initialize Storybook in a React project
  - [ ] 2. Check whether Storybook automatically starts after init and the onboarding welcome modal gets triggered
  - [ ] 3. Go through the onboarding and make sure each step looks properly and make it until the end (end: click on "Configure your Project" docs).
  - [ ] 4. Optional: Initialize Storybook in a Typescript/Non-Typescript project and check, whether the code examples are correct (they have to be typed in Typescript projects)
  - [ ] 5. Optional: Toggle your OS to dark mode/light mode and go through the onboarding once again. Does everything look properly? You can retrigger it by appending "?path=/onboarding" to the localhost URL.
  - [ ] 6. Optional: Test the initialization and onboarding with different package managers (pnpm, yarn + pnp, npm)

### Styling addon
**testing with**: 
- [ ] 1 Review the documentation at https://storybook.js.org/addons/@storybook/addon-styling
- [ ] 2 Choose a new project without Storybook using one of: Tailwind, Material UI, Styled-components, Emotion. NOTE: auto-configuration below not currently supported in monorepos!
- [ ] 3 Install Storybook 7.1 prerelease using `npx storybook@next init`
- [ ] 4 Install addon styling with `storybook add @storybook/addon-styling`
- [ ] 5 Auto-configure the styling addon using `yarn add-styling-setup` (see https://github.com/storybookjs/addon-styling/blob/main/docs/auto-configuration.md)
- [ ] 6 Verify your project components render correctly with their expected styles


### Changelog
**testing with**: 
- [ ] 1 Initialize Storybook in any kind of project, and make sure to put the feature flag whatsNewNotifications: true in main.ts.
- [ ] 2 When starting storybook for the first time with the onboarding flow, you should not see a notification.
- [ ] 3 When you refresh the page after you have done the onboarding flow, you should see a what's new notification.
- [ ] 4 Dismiss the notification, you should still see a green dot in your settings menu, when clicking on the dot, you should see a highlighted "What's new entry"
- [ ] 5 When clicking on the what's new entry, you should go to the what's new post, and the green dot should disappear.
- [ ] 6 After resetting your node_module cache, you should see the What's new notification again.
- [ ] 7 When you click directly on the notification, to read the post, the notification should disappear, and the green dot as well.

### Docs TOC
**testing with**: 
- [ ] 1 Review the documentation draft https://chromatic-ui.notion.site/TOC-in-addon-docs-9db53c27a91b49aa9262bc8bb961f903?pvs=4
- [ ] 2 Create or reuse a storybook with a mix of autodocs, attached/unattached MDX pages
- [ ] 3 Enable the TOC feature globally by setting the `parameters.docs.toc = {}` in `.storybook/preview.js`
- [ ] 4 Browse the different docs pages in both desktop and mobile (less than 768px) viewports
- [ ] 5 Try out the key parameters on different components and with different content lengths and levels heading nesting (disable, headingSelector, ignoreSelector, title)

```

**Comment by vanessayuenn** [comment]
### Onboarding
**testing with**: npm + react + typescript
  - [ ] 1. Initialize Storybook in a React project
  - [ ] 2. Check whether Storybook automatically starts after init and the onboarding welcome modal gets triggered
  - [ ] 3. Go through the onboarding and make sure each step looks properly and make it until the end (end: click on "Configure your Project" docs).
  - [ ] 4. Optional: Initialize Storybook in a Typescript/Non-Typescript project and check, whether the code examples are correct (they have to be typed in Typescript projects)
  - [ ] 5. Optional: Initialize Storybook in a Next.js project and verify, whether the import statement in the code example imports types from "@storybook/nextjs"
  - [ ] 6. Optional: Toggle your OS to dark mode/light mode and go through the onboarding once again. Does everything look properly? You can retrigger it by appending "?path=/onboarding" to the localhost URL.
  - [ ] 7. Optional: Test the initialization and onboarding with different package managers (pnpm, yarn + pnp, npm)

### Styling addon
**testing with**: 
- [ ] 1 Review the documentation at https://storybook.js.org/addons/@storybook/addon-styling
- [ ] 2 Choose a new project without Storybook using one of: Tailwind, Material UI, Styled-components, Emotion. NOTE: auto-configuration below not currently supported in monorepos!
- [ ] 3 Install Storybook 7.1 prerelease using `npx storybook@next init`
- [ ] 4 Install addon styling with `storybook add @storybook/addon-styling`
- [ ] 5 Auto-configure the styling addon using `yarn add-styling-setup` (see https://github.com/storybookjs/addon-styling/blob/main/docs/auto-configuration.md)
- [ ] 6 Verify your project components render correctly with their expected styles


### Changelog
**testing with**: 
- [ ] 1 Initialize Storybook in any kind of project, and make sure to put the feature flag whatsNewNotifications: true in main.ts.
- [ ] 2 When starting storybook for the first time with the onboarding flow, you should not see a notification.
- [ ] 3 When you refresh the page after you have done the onboarding flow, you should see a what's new notification.
- [ ] 4 Dismiss the notification, you should still see a green dot in your settings menu, when clicking on the dot, you should see a highlighted "What's new entry"
- [ ] 5 When clicking on the what's new entry, you should go to the what's new post, and the green dot should disappear.
- [ ] 6 After resetting your node_module cache, you should see the What's new notification again.
- [ ] 7 When you click directly on the notification, to read the post, the notification should disappear, and the green dot as well.

### TOC addons
**testing with**: 
- [ ] 1 Review the documentation draft https://chromatic-ui.notion.site/TOC-in-addon-docs-9db53c27a91b49aa9262bc8bb961f903?pvs=4
- [ ] 2 Create or reuse a storybook with a mix of autodocs, attached/unattached MDX pages
- [ ] 3 Enable the TOC feature globally by setting the `parameters.docs.toc = {}` in `.storybook/preview.js`
- [ ] 4 Browse the different docs pages in both desktop and mobile (less than 768px) viewports
- [ ] 5 Try out the key parameters on different components and with different content lengths and levels heading nesting (disable, headingSelector, ignoreSelector, title)

**Comment by JReinhold** [comment]
### Onboarding
**testing with**: pnpm + react-vite-ts | yarn + react-vite-js 
  - [ ] 1. Initialize Storybook in a React project
  - [ ] 2. Check whether Storybook automatically starts after init and the onboarding welcome modal gets triggered
  - [ ] 3. Go through the onboarding and make sure each step looks properly and make it until the end (end: click on "Configure your Project" docs).
  - [ ] 4. Optional: Initialize Storybook in a Typescript/Non-Typescript project and check, whether the code examples are correct (they have to be typed in Typescript projects)
  - [ ] 5. Optional: Initialize Storybook in a Next.js project and verify, whether the import statement in the code example imports types from "@storybook/nextjs"
  - [ ] 6. Optional: Toggle your OS to dark mode/light mode and go through the onboarding once again. Does everything look properly? You can retrigger it by appending "?path=/onboarding" to the localhost URL.
  - [ ] 7. Optional: Test the initialization and onboarding with different package managers (pnpm, yarn + pnp, npm)

### Styling addon
**testing with**: pnpm + react-vite-ts + emotion | yarn + react-vite-js + emotion
- [ ] 1 Review the documentation at https://storybook.js.org/addons/@storybook/addon-styling
- [ ] 2 Choose a new project without Storybook using one of: Tailwind, Material UI, Styled-components, Emotion. NOTE: auto-configuration below not currently supported in monorepos!
- [ ] 3 Install Storybook 7.1 prerelease using `npx storybook@next init`
- [ ] 4 Install addon styling with `storybook add @storybook/addon-styling`
- [ ] 5 Auto-configure the styling addon using `yarn add-styling-setup` (see https://github.com/storybookjs/addon-styling/blob/main/docs/auto-configuration.md)
- [ ] 6 Verify your project components render correctly with their expected styles


### Changelog
**testing with**: pnpm + sveltekit | yarn + nextjs
- [ ] 1 Initialize Storybook in any kind of project, and make sure to put the feature flag whatsNewNotifications: true in main.ts.
- [ ] 2 When starting storybook for the first time with the onboarding flow, you should not see a notification.
- [ ] 3 When you refresh the page after you have done the onboarding flow, you should see a what's new notification.
- [ ] 4 Dismiss the notification, you should still see a green dot in your settings menu, when clicking on the dot, you should see a highlighted "What's new entry"
- [ ] 5 When clicking on the what's new entry, you should go to the what's new post, and the green dot should disappear.
- [ ] 6 After resetting your node_module cache, you should see the What's new notification again.
- [ ] 7 When you click directly on the notification, to read the post, the notification should disappear, and the green dot as well.

### TOC addons
**testing with**: pnpm + svelte-vite | yarn + vue3
- [ ] 1 Review the documentation draft https://chromatic-ui.notion.site/TOC-in-addon-docs-9db53c27a91b49aa9262bc8bb961f903?pvs=4
- [ ] 2 Create or reuse a storybook with a mix of autodocs, attached/unattached MDX pages
- [ ] 3 Enable the TOC feature globally by setting the `parameters.docs.toc = {}` in `.storybook/preview.js`
- [ ] 4 Browse the different docs pages in both desktop and mobile (less than 768px) viewports
- [ ] 5 Try out the key parameters on different components and with different content lengths and levels heading nesting (disable, headingSelector, ignoreSelector, title)

**Comment by shilman** [comment]
### Onboarding
**testing with**: yarn + webpack / react17
  - [ ] 1. Initialize Storybook in a React project
  - [ ] 2. Check whether Storybook automatically starts after init and the onboarding welcome modal gets triggered
  - [ ] 3. Go through the onboarding and make sure each step looks properly and make it until the end (end: click on "Configure your Project" docs).
  - [ ] 4. Optional: Initialize Storybook in a Typescript/Non-Typescript project and check, whether the code examples are correct (they have to be typed in Typescript projects)
  - [ ] 5. Optional: Initialize Storybook in a Next.js project and verify, whether the import statement in the code example imports types from "@storybook/nextjs"
  - [ ] 6. Optional: Toggle your OS to dark mode/light mode and go through the onboarding once again. Does everything look properly? You can retrigger it by appending "?path=/onboarding" to the localhost URL.
  - [ ] 7. Optional: Test the initialization and onboarding with different package managers (pnpm, yarn + pnp, npm)

### Styling addon
**testing with**: MUI tbd
- [ ] 1 Review the documentation at https://storybook.js.org/addons/@storybook/addon-styling
- [ ] 2 Choose a new project without Storybook using one of: Tailwind, Material UI, Styled-components, Emotion. NOTE: auto-configuration below not currently supported in monorepos!
- [ ] 3 Install Storybook 7.1 prerelease using `npx storybook@next init`
- [ ] 4 Install addon styling with `storybook add @storybook/addon-styling`
- [ ] 5 Auto-configure the styling addon using `yarn add-styling-setup` (see https://github.com/storybookjs/addon-styling/blob/main/docs/auto-configuration.md)
- [ ] 6 Verify your project components render correctly with their expected styles


### Changelog
**testing with**: yarn + vue3-vite
- [ ] 1 Initialize Storybook in any kind of project, and make sure to put the feature flag whatsNewNotifications: true in main.ts.
- [ ] 2 When starting storybook for the first time with the onboarding flow, you should not see a notification.
- [ ] 3 When you refresh the page after you have done the onboarding flow, you should see a what's new notification.
- [ ] 4 Dismiss the notification, you should still see a green dot in your settings menu, when clicking on the dot, you should see a highlighted "What's new entry"
- [ ] 5 When clicking on the what's new entry, you should go to the what's new post, and the green dot should disappear.
- [ ] 6 After resetting your node_module cache, you should see the What's new notification again.
- [ ] 7 When you click directly on the notification, to read the post, the notification should disappear, and the green dot as well.

### Docs TOC
**testing with**: AstroUX Design System (web-components + webpack)
- [ ] 1 Review the documentation draft https://chromatic-ui.notion.site/TOC-in-addon-docs-9db53c27a91b49aa9262bc8bb961f903?pvs=4
- [ ] 2 Create or reuse a storybook with a mix of autodocs, attached/unattached MDX pages
- [ ] 3 Enable the TOC feature globally by setting the `parameters.docs.toc = {}` in `.storybook/preview.js`
- [ ] 4 Browse the different docs pages in both desktop and mobile (less than 768px) viewports
- [ ] 5 Try out the key parameters on different components and with different content lengths and levels heading nesting (disable, headingSelector, ignoreSelector, title)
