### ISSUE TITLE
[Bug]: Getting Error: Cannot read properties of null (reading 'useRef') after upgrading to Storybook 7

### ISSUE THREAD

**Issue by bigbunty** [storybookjs/storybook#23295]
### Describe the bug
React - 18.2.0
Storybook - ^7.0.23
Typescript - ~5.0.2

I am updating Storybook version 6.5 to version 7 in my project. After following version upgrading steps, getting below error.

<img width="1713" alt="Screenshot 2023-07-04 at 1 29 07 PM" src="https://github.com/storybookjs/storybook/assets/108940398/b18e606b-8402-4486-a0b1-85fa24c2ba38">

### To Reproduce

###-folder/library name hidden for security purpose
**main.ts** 
```
import type { StorybookConfig } from "@storybook/react-webpack5";
const CopyWebpackPlugin = require('copy-webpack-plugin');
const path = require('path');
const GLOBAL_PATTERNS = require("@###/sbcore/config/shared/patterns");
const RULES = require("@###/sbcore/config/shared/rules");
const PATTERNS_CONFIG = [...GLOBAL_PATTERNS.patterns, {
  from: path.resolve(__dirname, '../projects/###/reactmaterial/web.config'),
  to: ''
}, {
  from: path.resolve(__dirname, "./public/assets/images"),
  to: 'assets/images/'
}];

const config: StorybookConfig = {
  stories: [
    // "../stories/**/*.mdx",
    // "../stories/**/*.stories.@(js|jsx|ts|tsx)",
    // "../stories/**/**/*.mdx",
    // "../stories/**/**/*.stories.@(js|jsx|ts|tsx)",
    "../projects/###/reactmaterial/src/lib/**/*.stories.mdx",  
    "../projects/###/reactmaterial/src/lib/**/*.stories.@(js|jsx|ts|tsx)"
  ],
  addons: [
    "@storybook/addon-links",
    "@storybook/addon-docs", //
    "@storybook/preset-scss", //
    "@storybook/addon-essentials",
    "@storybook/addon-interactions",
    "@storybook/addon-a11y"
  ],
  framework: {
    name: "@storybook/react-webpack5",
    options: {},
  },
  staticDirs: ["./public"],

  webpackFinal: async config => {
    if (config.resolve) {
      config.resolve.roots = [path.resolve(__dirname, './public')];
    }
    if (config.plugins) {
      config.plugins.push(new CopyWebpackPlugin({
        patterns: PATTERNS_CONFIG
      }));
    }
    if (config.module && config.module?.rules) {
      config.module.rules.push(RULES.RULES);
      config.module.rules.push({
        test: /\.stories\.[tj]sx?$/,
        include: [path.resolve(__dirname, '../projects/###/reactmaterial/src/lib/**')],
        use: [
          {
            loader: require.resolve('@storybook/source-loader'),
            options: {}
          },
        ],
        enforce: 'pre',
      });
    }

    return config;
  },
  docs: {
    autodocs: "tag",
  },
};
export default config satisfies StorybookConfig;

```

**preview.ts**
```
import type { Preview } from "@storybook/react";
import "./styles.scss";
const preview: Preview = {
  parameters: {
    actions: { argTypesRegex: "^on[A-Z].*" },
    controls: {
      matchers: {
        color: /(background|color)$/i,
        date: /Date$/,
      },
    },
  },
};

export default preview;
```

**babel.config.json**

```
{
  "sourceType": "unambiguous",
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": {
          "chrome": 100
        }
      }
    ],
    "@babel/preset-typescript",
    "@babel/preset-react"
  ],
  "plugins": []
}

```

**tsconfig.json**
```
{
  "compilerOptions": {
    "target": "es2020",
    "jsx": "react",
    "module": "es2020",
    "moduleResolution": "node",
    "outDir": "./dist/",
    "noImplicitAny": true,
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "declaration": true
  },
  "include": [
    "projects/emerald/reactmaterial/src/**/*",
    "typings"
  ],
  "exclude": [
    "node_modules",
    "**/*.spec.ts"
  ],
  "typeRoots": [
    "./typings",
    "./node_modules/@types/"
  ]
}
```

**rollup.config.json**
```
import { babel } from "@rollup/plugin-babel";
import copy from "rollup-plugin-copy";
import external from "rollup-plugin-peer-deps-external";
import resolve from "@rollup/plugin-node-resolve";
import typescript from "@rollup/plugin-typescript";
import { terser } from "rollup-plugin-terser";
import scss from "rollup-plugin-scss";

export default [
  {
    input: "projects/###/reactmaterial/src/index.ts",
    output: [
      {
        file: "dist/###/reactmaterial/index.js",
        format: "cjs",
        exports: "named",
      },
      {
        file: "dist/###/reactmaterial/index.es.js",
        format: "es",
        exports: "named",
      },
    ],
    plugins: [
      copy({
        targets: [
          {
            src: "projects/###/reactmaterial/package.json",
            dest: "dist/###/reactmaterial/",
          },
          {
            src: "projects/###/reactmaterial/web.config",
            dest: "dist/###/reactmaterial/",
          },
        ],
      }),
      babel({
        exclude: "node_modules/**",
        presets: ["@babel/preset-react"],
        babelHelpers: "bundled",
      }),
      scss({
        input: "projects/###/reactmaterial/global.scss",
        output: "dist/###/reactmaterial/lib/global.css",
        failOnError: true,
      }),
      external(),
      resolve(),
      typescript(),
      terser(),
    ],
    external: [
      "classnames",
      "react",
      "react-dom",
      "prop-types",
      "react/jsx-runtime",
    ],
  },
];

```

### System

```shell
Environment Info:

  System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 18.14.0 - /usr/local/bin/node
    npm: 9.3.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 114.0.5735.198
    Safari: 16.3
  npmPackages:
    @storybook/addon-a11y: ^7.0.23 => 7.0.25 
    @storybook/addon-actions: ^7.0.23 => 7.0.25 
    @storybook/addon-docs: ^7.0.23 => 7.0.25 
    @storybook/addon-essentials: ^7.0.23 => 7.0.25 
    @storybook/addon-interactions: ^7.0.23 => 7.0.25 
    @storybook/addon-links: ^7.0.23 => 7.0.25 
    @storybook/addon-mdx-gfm: ^7.0.23 => 7.0.25 
    @storybook/angular: ^7.0.24 => 7.0.25 
    @storybook/blocks: ^7.0.23 => 7.0.25 
    @storybook/node-logger: ^7.0.23 => 7.0.25 
    @storybook/preset-scss: ^1.0.3 => 1.0.3 
    @storybook/react: ^7.0.23 => 7.0.25 
    @storybook/react-webpack5: ^7.0.23 => 7.0.25 
    @storybook/source-loader: ^7.0.24 => 7.0.25 
    @storybook/testing-library: ^0.0.14-next.2 => 0.0.14-next.2
```

### Additional context

1. Also tried with Adding SB7 newly to my project after removing .storybook & sb dependencies, again getting same error.
But storybook loads If I am adding my library components & stories inside "stories" directory which was created while installing SB 7.

2. If I keep .babelrc.json (instead of babel.config.json), getting below error.

<img width="1325" alt="Screenshot 2023-07-04 at 2 03 26 PM" src="https://github.com/storybookjs/storybook/assets/108940398/623708ec-f8a7-4500-b232-ffdc4c017a68">

ModuleBuildError: Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /Users/SKumar51/Documents/Emerald/React-Storybook/emerald.reactmaterial/projects/emerald/reactmaterial/src/lib/Button/Button.stories.tsx: Unexpected token, expected "," (82:2)

  80 |   // }
  81 |   tags: ['autodocs']
> 82 | } satisfies Meta<typeof EmeraldButton>);
     |   ^
  83 | export default meta;
  84 | type Story = StoryObj<typeof meta>;
  85 | export const Default: Story = {
    at instantiate (/Users/SKumar51/Documents/Emerald/React-Storybook/emerald.reactmaterial/node_modules/@babel/parser/lib/index.js:63:32)
    at constructor (/Users/SKumar51/Documents/Emerald/React-Storybook/emerald.reactmaterial/node_modules/@babel/parser/lib/index.js:358:12)

**Comment by kerlos** [comment]
For my case, I'm working on a mono repo, and the component that uses React hooks will throw an error due to the dispatcher being null. After a while, I found during debugging that Storybook bundles all React from the imported project, resulting in multiple copies of React, which causes an invalid hook call.

To fix this for me, I added react to the resolve config in the webpack configuration.
```javascript
async webpackFinal(config) {
    config.resolve.alias = {
      react: path.resolve('node_modules/react')
    }
}
```

**Comment by Jintus** [comment]
> For my case using React, I'm working on a mono repo, and the component that uses React hooks will throw an error due to the dispatcher being null. After a while, I found during debugging that Storybook bundles all React from the imported project, resulting in multiple copies of React, which causes an invalid hook call.
> 
> To fix this for me, I added react to the resolve config in the webpack configuration.
> 
> ```js
> async webpackFinal(config) {
>     config.resolve.alias = {
>       react: path.resolve('node_modules/react')
>     }
> }
> ```

Thank you very much, this solve the problem. I was struggling with this since 1 week

**Comment by Undistraction** [comment]
> For my case using React, I'm working on a mono repo, and the component that uses React hooks will throw an error due to the dispatcher being null. After a while, I found during debugging that Storybook bundles all React from the imported project, resulting in multiple copies of React, which causes an invalid hook call.
> 
> To fix this for me, I added react to the resolve config in the webpack configuration.
> 
> ```js
> async webpackFinal(config) {
>     config.resolve.alias = {
>       react: path.resolve('node_modules/react')
>     }
> }
> ```

This is a solid fix, but it's really not obvious and I imagine a lot of people are going to run into this. Seems like something that should be addressed by Storybook.
