### ISSUE TITLE
[Feature Request]: Support correct `argTypes` type inference for named TypeScript types

### ISSUE THREAD

**Issue by segevfiner** [storybookjs/storybook#23313]
### Is your feature request related to a problem? Please describe

A Vue component defining a prop like this will get it's type correctly inferred by Storybook and will render as a select with the proper types:

```ts
const props = defineProps<{
  /**
   * size of the button
   */
  size?: 'small' | 'medium' | 'large',
}>();
```

A prop defined like this won't get properly inferred and be treated as an object:
```ts
type Sizes = 'small' | 'medium' | 'large';

const props = defineProps<{
  /**
   * size of the button
   */
  size?: Sizes,
}>();
```

Or:

```ts
import type { Sizes } from '../sharedTypes';

const props = defineProps<{
  /**
   * size of the button
   */
  size?: Sizes,
}>();
```

### Describe the solution you'd like

For Storybook to be able to correctly infer types in such cases.

### Describe alternatives you've considered

Manually overriding the inference using `argTypes`. Requires also creating an array with the actual values and TypeScript trickery to turn it back into a type.

### Are you able to assist to bring the feature to reality?

no

**Comment by chakAs3** [comment]
hi @segevfiner, this issue is fixed in this PR #22285,
You will get something like this 
![image](https://github.com/storybookjs/storybook/assets/711292/63e90d35-0da5-41b6-9656-264dcfaf4de0)
