### ISSUE TITLE
[Bug] Storybook breaks with Vite 4.4.0-beta

### ISSUE THREAD

**Issue by Marabyte** [storybookjs/storybook#23322]
### What version of `vite` are you using?

4.4.0-beta.3

### System info and storybook versions

Environment Info:

  **System**:
      OS: macOS 13.4
      CPU: (10) arm64 Apple M1 Pro

  **Binaries**:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm

  **Browsers**:
    Chrome: 114.0.5735.133
    Firefox: 114.0.1
    Safari: 16.5

  **npmPackages**:
    @storybook/addon-a11y: ^7.0.7 => 7.0.7 
    @storybook/addon-actions: ^7.0.7 => 7.0.7 
    @storybook/addon-essentials: ^7.0.7 => 7.0.7 
    @storybook/addon-links: ^7.0.7 => 7.0.7 
    @storybook/manager-api: ^7.0.7 => 7.0.7 
    @storybook/react-vite: ^7.0.7 => 7.0.7 
    @storybook/testing-library: ^0.1.0 => 0.1.0 
    @storybook/theming: ^7.0.7 => 7.0.7

### Describe the Bug

I know Vite 4.4.0 is still in beta, but I wanted to test it out with the LightningCSS minifier.

After bumping Vite to version `4.4.0-beta.2` I get this error when starting Storybook:

```bash
  [vite] Internal server error: Missing "./preview.js" specifier in "@storybook/react" package
  Plugin: vite:import-analysis
  File: /virtual:/@storybook/builder-vite/vite-app.js
```

As far as I understand it, `builder-vite` has a code generator plugin and goes through the dependencies and seem to be failing to find `preview.js` in `@storybook/react` but it is declared here:
 https://github.com/storybookjs/storybook/blob/next/code/renderers/react/package.json#L29

### Link to Minimal Reproducible Example

https://github.com/Marabyte/vite-4.4-bug

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by IanVS** [comment]
Tracking in https://github.com/storybookjs/storybook/issues/23338.
