### ISSUE TITLE
[Bug]: Error: Directory import 'node_modules/rxjs/operators' is not supported resolving ES modules imported from 'node_modules/@angular/core/fesm2015/core.mjs'

### ISSUE THREAD

**Issue by ChazUK** [storybookjs/storybook#23324]
### Describe the bug

I'm not sure why this issue is happening. It's an existing Angular 14 project and I've tried installing Storybook 7 from scratch using `npx storybook@latest init`

My project still builds and runs fine, but when trying to run Storybook i get the following error.

The Storybook site loads as well, I can see all of my stories in the sidebar, but none of the iframe content will load. The only console errors are

```
GET http://localhost:6006/sb-preview/runtime.js net::ERR_ABORTED 404 (Not Found)                 localhost/:130
GET http://localhost:6006/iframe.html?viewMode=story&id=components-alert--info 404 (Not Found)   chunk-PUVLCKJJ.js:9
```

```
ERR! Error: Directory import 'node_modules/rxjs/operators' is not supported resolving ES modules imported from node_modules/@angular/core/fesm2015/core.mjs
ERR! Did you mean to import rxjs/operators/index.js?
ERR!     at __node_internal_captureLargerStackTrace (node:internal/errors:478:5)
ERR!     at new NodeError (node:internal/errors:387:5)
ERR!     at finalizeResolution (node:internal/modules/esm/resolve:326:17)
ERR!     at moduleResolve (node:internal/modules/esm/resolve:907:10)
ERR!     at defaultResolve (node:internal/modules/esm/resolve:1115:11)
ERR!     at nextResolve (node:internal/modules/esm/loader:163:28)
ERR!     at ESMLoader.resolve (node:internal/modules/esm/loader:837:30)
ERR!     at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
ERR!     at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
ERR!     at link (node:internal/modules/esm/module_job:75:36)
```

### System

```shell
Environment Info:

  System:
    OS: macOS 13.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Binaries:
    Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
    Yarn: 1.22.19
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
  Browsers:
    Chrome: 114.0.5735.198
    Edge: 114.0.1823.55
    Safari: 16.5
  npmPackages:
    @storybook/addon-essentials: ^7.0.26 => 7.0.26 
    @storybook/addon-interactions: ^7.0.26 => 7.0.26 
    @storybook/addon-links: ^7.0.26 => 7.0.26 
    @storybook/angular: ^7.0.26 => 7.0.26 
    @storybook/blocks: ^7.0.26 => 7.0.26 
    @storybook/cli: ^7.0.26 => 7.0.26 
    @storybook/testing-library: ^0.2.0 => 0.2.0 
```

### Additional context

```
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 14.2.12
Node: 16.18.1
Package Manager: npm 8.19.2 
OS: darwin x64

Angular: 14.3.0
... compiler, core

Package                             Version
-------------------------------------------------------------
@angular-devkit/architect           0.1402.12
@angular-devkit/build-angular       14.2.12
@angular-devkit/core                14.2.12
@angular-devkit/schematics          14.2.12
@angular/animations                 14.2.12
@angular/cdk                        14.2.7
@angular/cli                        14.2.12
@angular/common                     14.2.12
@angular/compiler-cli               14.2.12
@angular/fire                       7.5.0
@angular/forms                      14.2.12
@angular/language-service           14.2.12
@angular/material                   14.2.7
@angular/material-moment-adapter    14.2.7
@angular/platform-browser           14.2.12
@angular/platform-browser-dynamic   14.2.12
@angular/platform-server            14.2.12
@angular/pwa                        14.2.12
@angular/router                     14.2.12
@angular/service-worker             14.2.12
@schematics/angular                 14.2.12
rxjs                                6.6.7
typescript                          4.9.5
webpack                             5.76.1
```

**Comment by bamma** [comment]
Have the same issue at work. I do have storybook 7, but not the latest. I can update tomorrow at work what version i have of storybook 7 where the issue did not occur. It broke for me when I updated to version 7.0.22 cause 7.0.21 i believe had support for angular 16.1 where they had input transformers which i would like to play around with. But storybook still holds me back.

**Comment by bamma** [comment]
You can locally fix i by going to edit `rxjs/operators` to `rxjs/operators/index.js` in your `@angular/core/fesm*/core.mjs` file, Not a viable solution but it does make it run storybook run locally. I wonder if there has been added a setting storybook or a dependency package that breaks that kind of reference.

**Comment by bamma** [comment]
Found the issue. This is what causes the actual bug https://github.com/storybookjs/storybook/pull/23070/files#diff-81075d0b21994ef5f6341d63534adc00680664371c265d89cd5609726dc8e936 this exact change. How did i test, i just imported like normal and used that to check major version. I did this locally modifying the transpiled javascript. I don't know what that "Fix" was suppose to fix. Just seem like an odd solution to import the core package.

**Comment by ChazUK** [comment]
Not a huge fan of editing the files directly inside node_modules as that only persists across a single developer. I have upgraded rxjs to 7.5.0 which appears to solve the issue, but be warned on bigger projects that's not an easy undertaking.

**Comment by bamma** [comment]
@ChazUK you can also just use version Version 7.0.20 until its getting fixed. That is should be the newest working version. where it does not break.

**Comment by echosunqian** [comment]
I install the latest version, and manually edit the package version numbers to 7.0.11 in package.json(according to the official website of storybook), but the problem still exists
