### ISSUE TITLE
[Bug]: can't mount `useRouter` when executing storyshots

### ISSUE THREAD

**Issue by NeoLSN** [storybookjs/storybook#23329]
### Describe the bug

It won't inject any decorators that framework `@storybook/nextjs` provided when executing the storyshots.

```
 Storyshots › Components/TestUI › Primary

 NextRouter was not mounted. https://nextjs.org/docs/messages/next-router-not-mounted
```

### To Reproduce

`index.tsx`
```js
const TestUI = (): FC => {
  const router = useRouter()
  return <div>{router.path}</div>
}
```
`index.stories.tsx`
```js
import { FC } from 'react'
import { Meta } from '@storybook/react'

import TestUI from '.'

export default {
  title: 'Components/TestUI',
  component: TestUI
} as Meta

export const Primary: FC = () => <TestUI/>
```

then run storyshot test case
```js
import initStoryshots from '@storybook/addon-storyshots'
initStoryshots()
```

### System

```shell
Environment Info:

  System:
    OS: macOS 13.4.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    Yarn: 3.6.0 - ~/.nvm/versions/node/v18.15.0/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
  Browsers:
    Chrome: 114.0.5735.198
    Safari: 16.5.1
  npmPackages:
    @storybook/addon-essentials: 7.0.26 => 7.0.26 
    @storybook/addon-storyshots: 7.0.26 => 7.0.26 
    @storybook/addon-storysource: 7.0.26 => 7.0.26 
    @storybook/addon-styling: 1.3.2 => 1.3.2 
    @storybook/nextjs: 7.0.26 => 7.0.26 
    @storybook/react: 7.0.26 => 7.0.26 
    @storybook/testing-react: 2.0.0 => 2.0.0
```

### Additional context

migrate from v6 to v7

in v6, we use `storybook-addon-next-router` for router decorator in `preview.js`

**Comment by fabian-ahorner** [comment]
I am suprised that @storybook/next is not wrapping the stories with a router provider during tests. That would probably be a better solution but this worked for me in the meantime::
```
const test = snapshotWithOptions();
initStoryshots({
  test: (context) => {
    nextRouter.useRouter = jest.fn();
    nextRouter.useRouter.mockImplementation(() => context.context.parameters.nextjs?.router);
    return test(context);
  },
});
```

**Comment by NeoLSN** [comment]
Thanks for the workaround.
Hope this issue will be fixed ASAP.

**Comment by elussich-globant** [comment]
Hello everyone, I posted this on a different Issue but I believe it could help fixing yours:
https://github.com/storybookjs/storybook/issues/22538#issuecomment-1811152343

Let me know! Cheers.

**Comment by jonniebigodes** [comment]
The Storyshots addon is officially deprecated and will be removed in a future release of Storybook. To help with the transition process, we've created a [migration guide](https://storybook.js.org/docs/writing-tests/storyshots-migration-guide) for the available options and common use cases.
