### ISSUE TITLE
[Bug]: Can't exclude props from controls when using custom render function

### ISSUE THREAD

**Issue by lopis** [storybookjs/storybook#23343]
### Describe the bug

I believe I used to be able to hide all props from the controls panel using the following code:

```js
// Vue story
export const Variants = {
  render: () => ({
    template: '<div>test...</div>',
  }),
  parameters: {
    // Hides all controls
    controls: {
      exclude: /.*/g,
      sort: 'alpha',
      hideNoControlsWarning: true,
    },
  },
}
```

![image](https://github.com/storybookjs/storybook/assets/2715751/67638932-0fa4-458c-adcb-0362efd2def4)

The parameters are working, e.g. `hideNoControlsWarning` hides the warning, and the controls for each prop are hidden, but the props themselves don't disappear. I can see the props for the component, but I don't want them in this particular story.

For stories without a custom render function, the effect of excluding all controls is that it also hides all props.

![image](https://github.com/storybookjs/storybook/assets/2715751/1b8257b7-c7f0-4969-b724-c0992a675d7d)

I don't understand why this behaviour is different, and it seems pretty unexpected to me. Am I missing something, or is this a bug?

### System

```shell
Environment Info:

  System:
    OS: Linux 5.19 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
  Binaries:
    Node: 16.20.0 - ~/.nvm/versions/node/v16.20.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.20.0/bin/yarn
    npm: 8.19.4 - ~/.nvm/versions/node/v16.20.0/bin/npm
  npmPackages:
    @storybook/addon-essentials: ^7.0.10 => 7.0.23 
    @storybook/addon-interactions: ^7.0.10 => 7.0.23 
    @storybook/addon-links: ^7.0.22 => 7.0.23 
    @storybook/blocks: ^7.0.10 => 7.0.23 
    @storybook/manager-api: ^7.0.23 => 7.0.23 
    @storybook/preview-api: ^7.0.23 => 7.0.23 
    @storybook/testing-library: ^0.0.14-next.2 => 0.0.14-next.2 
    @storybook/theming: ^7.0.23 => 7.0.23 
    @storybook/vue: ^7.0.10 => 7.0.23 
    @storybook/vue-webpack5: ^7.0.10 => 7.0.23
```

**Comment by sookmax** [comment]
@lopis Hey I know this is going to sound strange, but could you change your render function from this shape (`() => {}`) to this shape (`(args) => {}`); even if you don't actually use the formal parameters `args`, and see if it works?

You should also check out [my sandbox](https://stackblitz.com/edit/github-dvqx8a?file=src%2Fstories%2FButton.stories.tsx); see `Button.stories.tsx`.

**Comment by lopis** [comment]
I'll try and report back. I understand there are some reflection going on
under the hood, so it's not so weird to me at this point :) thanks!

**Comment by sookmax** [comment]
This issue seems related to https://github.com/storybookjs/storybook/issues/23248#issuecomment-1613404861, and the code below:

### `code/lib/preview-api/src/modules/store/inferControls.ts`
```ts
export const inferControls: ArgTypesEnhancer<Renderer> = (context) => {
  const {
    argTypes,
    // eslint-disable-next-line @typescript-eslint/naming-convention
    parameters: { __isArgsStory, controls: { include = null, exclude = null, matchers = {} } = {} },
  } = context;
  if (!__isArgsStory) return argTypes;  // --> here since if the render function is shaped like `()=>{}` without formal parameters specified (e.g., `(args) => {}`), its `__isArgsStory` will be false.

  const filteredArgTypes = filterArgTypes(argTypes, include, exclude);
  const withControls = mapValues(filteredArgTypes, (argType, name) => {
    return argType?.type && inferControl(argType, name, matchers);
  });

  return combineParameters(withControls, filteredArgTypes);
};
```

**Comment by lopis** [comment]
> but could you change your render function from this shape (() => {}) to this shape ((args) => {});

This worked, thank you so much! I'll close this issue then, since it's the same as https://github.com/storybookjs/storybook/issues/23248

**Comment by jonbri** [comment]
> > but could you change your render function from this shape (() => {}) to this shape ((args) => {});
> 
> This worked, thank you so much! I'll close this issue then, since it's the same as #23248

This workaround works, but shouldn't the underlying issue still be fixed? The presence of the `render` function shouldn't have a bearing on whether controls are hidden/shown via the `parameters` config.

Needing to specify a function parameter which is not used in the function body is not ideal and violates linting rules.
