### ISSUE TITLE
[Bug]: 🐞🐞 MDX Stories not formatting "Show Code" properly

### ISSUE THREAD

**Issue by dbaitech** [storybookjs/storybook#23368]
### Describe the bug

I have written some documentation in Storybook using MDX that contains HTML written inside of the Canvas tag to display certain examples of components. These examples also contain a "Show Code" button. However, when clicked, it displays all the HTML inline rather than indented as it is inside the JSX stories. 

This is what "Show Code" displays:
![image](https://github.com/storybookjs/storybook/assets/75461349/4c13c453-083e-499b-b2dc-5e432f2da96c)

However, this is the indentation I am looking for:
![image](https://github.com/storybookjs/storybook/assets/75461349/5e6079c7-97a0-4677-b5b4-3750df31dd6e)

### To Reproduce

1. Create an "stories.mdx" file
2. Write HTML code inside the Canvas tag
3. View Storybook and click on the "Show Code"

**Comment by shilman** [comment]
`.stories.mdx` is deprecated as of 7.0 so we probably won't be investing more time in improving it.

You can customize the source output using the [`docs.source.transform` parameter](https://storybook.js.org/docs/react/api/doc-block-source#transform) or by providing the [code directly](https://storybook.js.org/docs/react/api/doc-block-source#code).
