### ISSUE TITLE
[Bug]: Storybook 7+  CORS error loading most assets

### ISSUE THREAD

**Issue by jfdesgagne** [storybookjs/storybook#23364]
### Describe the bug

Hi, we have an storybook app that we built using 6.1 that works fine, but on our 7.0.23, when we launch the storybook app locally or on our http hosted server, we get CORS error 307 on many assets, like `sb-manager/runtime.js`, or fonts in the public folder.

Has something changed in between 6.1 and 7+ that could explain this, and is there work around it?

![Screenshot 2023-07-07 at 10 15 03 AM](https://github.com/storybookjs/storybook/assets/5866277/abb9c564-69ea-4198-869c-b085050b38dd)

*It's worth noting that we don't have the issue when we the storybook dev server.*

### System

```shell
Environment Info:

  System:
    OS: macOS 13.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
  Browsers:
    Chrome: 114.0.5735.198
    Safari: 16.5
  npmPackages:
    @storybook/addon-docs: ^7.0.18 => 7.0.23 
    @storybook/addon-essentials: ^7.0.18 => 7.0.23 
    @storybook/addon-interactions: ^7.0.18 => 7.0.23 
    @storybook/addon-jest: ^7.0.18 => 7.0.23 
    @storybook/addon-links: ^7.0.18 => 7.0.23 
    @storybook/addon-react-native-web: ^0.0.20 => 0.0.20 
    @storybook/blocks: ^7.0.18 => 7.0.23 
    @storybook/react: ^7.0.18 => 7.0.23 
    @storybook/react-native: ^6.5.3 => 6.5.3 
    @storybook/react-webpack5: ^7.0.18 => 7.0.23 
    @storybook/testing-library: ^0.0.14-next.2 => 0.0.14-next.2
```

**Comment by sunilsurana** [comment]
Facing same issue. Is this being looked into?

**Comment by lukewhitmore** [comment]
Same issue here.

**Comment by shilman** [comment]
Do you a have a reproduction repo you can share? If not, can you create one? Go to https://storybook.new or see [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce). Thank you! 🙏

**Comment by jfdesgagne** [comment]
Hi! Repro rates for me would be to build the storybook website and open it locally in my chrome browser. It won't let me load any of the scripts that are loaded except for runtime.js
