### ISSUE TITLE
[Bug]: 🔥🐞🔥 Removing args in "Show Code" for stories written using React functional components

### ISSUE THREAD

**Issue by dbaitech** [storybookjs/storybook#23367]
### Describe the bug

I have several stories for components that are written using React functional components since they require React hooks such as useState. When viewing the code in Storybook under the "Show Code" tab, it displays the entire function including the "args" parameter of the function as well as the "{...args}" props passed into the component.

I need args to set up controls for the component. However, because args is just for the Storybook implementation of the component and will not be used by developers in their own projects, I'd would like so that "Show Code" removes them the way that render does in CSF. This way developers that copy the code won't get confused about how they are supposed to use "args" when in fact they do not need it at all.

I still would like for "Show Code" to display the story as a functional component rather than just the pure HTML since the user needs to see what expressions are being used before the return statement (e.g. useState expressions).

For example, the Tabs component below uses useState to create a variable and function to update the active tab:
```
export default {
  title: "Navigation/Tabs",
  component: Tabs,
  autodocs: "auto",
  tags: ["autodocs"],
  argTypes: {
    placement: {
      options: ["left", "top"],
      control: { type: "inline-radio" },
    },
  },
  parameters: {
    docs: {
      source: {
        type: "code",
      },
    },
  },
};

export const BasicUsage = (args) => {
  const [activeId, setActiveId] = useState("2");

  const _onClick = (id) => {
    setActiveId(id);
  };

  return (
    <Tabs activeId={activeId} {...args}>
      <Tab id="1" onClick={_onClick}>
        Tab
      </Tab>
      <Tab id="2" onClick={_onClick}>
        Tab
      </Tab>
      <Tab id="3" onClick={_onClick}>
        Tab
      </Tab>
      <Tab id="4" onClick={_onClick}>
        Tab
      </Tab>
    </Tabs>
  );
};
```
In "Show Code", it displays as:
![image](https://github.com/storybookjs/storybook/assets/75461349/e6afb69f-1881-4d55-ae93-da75e2cee778)

However, I'd like for it to show up without the args parameter and without the {...args} prop like so:
```
() => {
  const [activeId, setActiveId] = useState("2");
  const _onClick = id => {
    setActiveId(id);
  };
  return <Tabs activeId={activeId} >
      <Tab id="1" onClick={_onClick}>
        Tab
      </Tab>
      <Tab id="2" onClick={_onClick}>
        Tab
      </Tab>
      <Tab id="3" onClick={_onClick}>
        Tab
      </Tab>
      <Tab id="4" onClick={_onClick}>
        Tab
      </Tab>
    </Tabs>;
}
```

### To Reproduce

1. Create a story using React functional components
2. Add "args" as a parameter to the functional component
3. Pass {...args} as a prop inside component inside the return expression
4. View the component in Storybook and click "Show Code"

**Comment by shilman** [comment]
You can customize the source output using the [`docs.source.transform` parameter](https://storybook.js.org/docs/react/api/doc-block-source#transform) or by providing the [code directly](https://storybook.js.org/docs/react/api/doc-block-source#code).

We'll be taking another pass at the source block later, but for now that's your best bet to get exactly what you want.

**Comment by dbaitech** [comment]
I'm using the docs.source.transform parameter to transform the code string like this:
![image](https://github.com/storybookjs/storybook/assets/75461349/4b3d6d95-41f1-4622-b6fa-0f65172d9c49)

When I check it using console.log it is giving the exact source code I would like to see:
![image](https://github.com/storybookjs/storybook/assets/75461349/f2a02134-8954-43b4-b93d-f89246203b04)

However, it is not showing up in the "Show Code" area:
![image](https://github.com/storybookjs/storybook/assets/75461349/4a184376-6304-4bf6-b82a-6697ba851eb5)

Is there a way to get the returned code to show in the "Show Code" section?

**Comment by ChenReuven** [comment]
i struggle with the same issue

**Comment by seahindeniz** [comment]
Just started to try out Storybook, and results are the same. Output doesn't look good and not DX friendly. Anyway around this?
![image](https://github.com/storybookjs/storybook/assets/5789670/30120046-7ab3-445d-8e56-f369ec1fa5ff)
