### ISSUE TITLE
Fully custom args example has type error

### ISSUE THREAD

**Issue by kylegach** [storybookjs/storybook#23362]
Related discussions: https://github.com/storybookjs/storybook/discussions/22555#discussioncomment-6307241 & https://github.com/storybookjs/storybook/discussions/22640#discussioncomment-6129051

- https://storybook.js.org/docs/react/essentials/controls#fully-custom-args
- https://storybook.js.org/docs/7.0/react/writing-stories/args

Need to apply typing as described here: https://storybook.js.org/blog/writing-stories-in-typescript/#:~:text=in%20your%20tsconfig.-,Typing%20custom%20args,-Sometimes%20stories%20need

**Comment by Sadaf-A** [comment]
@kylegach Greetings, I would like to work on this issue!

**Comment by kylegach** [comment]
Apologies, @Sadaf-A. I ended up addressing this as part of #23711.
