### ISSUE TITLE
[Bug]:  next/font/google are not loaded from storybook

### ISSUE THREAD

**Issue by SatioO** [storybookjs/storybook#23402]
### Describe the bug

I have set up a new Next.js 13 application and configured Storybook within it. However, the documented components are not loading with the actual fonts used in the application.

![Screenshot 2023-07-11 at 4 40 08 PM](https://github.com/storybookjs/storybook/assets/6435708/89b39ea7-a39d-4c44-8804-4924dd0b4a1a)
![Screenshot 2023-07-11 at 4 40 44 PM](https://github.com/storybookjs/storybook/assets/6435708/b0342571-567b-4e3a-8ea0-d94028401848)

Ideally, it should inherit font applied to body but it's not happening so I tried to mention the font specifically, but it did not work as well

![Screenshot 2023-07-11 at 4 43 27 PM](https://github.com/storybookjs/storybook/assets/6435708/e41e4d79-fc13-4450-9cce-d7384bc001be)

![Screenshot 2023-07-11 at 4 43 08 PM](https://github.com/storybookjs/storybook/assets/6435708/a4629730-8648-44ba-9d98-805677473eb7)

As we can see, Times font is getting applied instead of Roboto

<img width="804" alt="Screenshot 2023-07-11 at 4 44 12 PM" src="https://github.com/storybookjs/storybook/assets/6435708/5714dd04-ec78-45a4-a068-212a60a44fd0">

It is also missing the classname which is usually applied by next/font

<img width="232" alt="Screenshot 2023-07-11 at 4 48 16 PM" src="https://github.com/storybookjs/storybook/assets/6435708/366135f5-99bd-4387-8da5-5661d07958d2">

### System

"next": "13.4.9",
"react": "18.2.0",
"react-dom": "18.2.0",
"@storybook/nextjs": "^7.0.26",
"@storybook/react": "^7.0.26",

**Comment by valentinpalkovic** [comment]
Hi @SatioO,

please provide a reproduction on [Stackblitz](https://new-storybook.netlify.app/) or share a GitHub repo.

**Comment by valentinpalkovic** [comment]
@SatioO I Have checked out your example, and I think there needs to be a better understanding. Storybook doesn't load your `app/layout.tsx` file or know anything about it. You have to tell Storybook about the font, that it should be applied at the top of your components.

You can do the following steps to achieve this:

1. Rename `.storybook/preview.ts` to `.storybook/preview.tsx`
2. Paste the following code into `preview.tsx`:

```tsx
// .storybook/preview.tsx
import type { Preview } from "@storybook/react";
import { Roboto } from "next/font/google";
import React from 'react';

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  variable: "--font-roboto",
  display: "swap",
});

const preview: Preview = {
  parameters: {
    actions: { argTypesRegex: "^on[A-Z].*" },
    controls: {
      matchers: {
        color: /(background|color)$/i,
        date: /Date$/,
      },
    },
  },
  decorators: [
    (Story) => (
      <div className={roboto.className}>
        <Story />
      </div>
    ),
  ],
};

export default preview;
```

The added decorator will be applied to all stories. Please go to https://storybook.js.org/docs/react/writing-stories/decorators/ for more information about decorators.

**Comment by SatioO** [comment]
Thanks @valentinpalkovic :) It worked

**Comment by davidkhierl** [comment]
@SatioO I have question why when using font variable doesn't work

```typescript
// .storybook/preview.tsx
import type { Preview } from "@storybook/react";
import { Roboto } from "next/font/google";
import React from 'react';

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  variable: "--font-roboto",
  display: "swap",
});

const preview: Preview = {
  parameters: {
    actions: { argTypesRegex: "^on[A-Z].*" },
    controls: {
      matchers: {
        color: /(background|color)$/i,
        date: /Date$/,
      },
    },
  },
  decorators: [
    (Story) => (
      <div className={`${roboto.variable}`}>
        <Story />
      </div>
    ),
  ],
};

export default preview;
```

**Comment by AlexandrKolesnikov** [comment]
In cases when we're talking about stories for components like `Drawer`, `Modal`, `Dialog`, etc. which are usually rendered using [React Portal API](https://react.dev/reference/react-dom/createPortal) inside `body`, it makes sense to add needed className to the `body`  since in this way we're not adding any extra wrappers in the DOM and our Portal-rendered to the `body` components are inheriting font from the body. Especially it's helpful with the new Next.JS Font Optimization strategy.

So we can create a globally applied decorator (for all stories), which sets className at the body using `useEffect`.

`
import { useEffect } from "react";
import { type Preview } from "@storybook/react";
import { fontInter } from "@/styles/fonts";
import "@/styles/global.scss";

const preview: Preview = {
  parameters: {
    actions: { argTypesRegex: "^on[A-Z].*" },
    controls: {
      matchers: {
        color: /(background|color)$/i,
        date: /Date$/,
      },
    },
  },
  decorators: [
    (Story) => {
      useEffect(() => {
        document.body.classList.add(fontInter.className);
      }, []);

      return <Story />;
    },
  ],
};

export default preview;
`
