### ISSUE TITLE
The contrast ratio between foreground and background color of “RAW” button 3.6:1 which is less than required ratio 4.5:1.

### ISSUE THREAD

**Issue by msftedad** [storybookjs/storybook#23454]
### Describe the bug

The contrast ratio between foreground and background color of “RAW” button 3.6:1 which is less than the minimum required ratio of 4.5:1.

### To Reproduce

1. Open the URL: (https://vivacommonstorybooktest.blob.core.windows.net/$web/index.html?path=/story/common-navigation--scrolling-panel&globals=backgrounds.grid:!false;backgrounds.value:transparent).
2. Navigate to the app bar present in the left pane using tab key and invoke it using Enter key.
3. Navigate to the "Inline" link and invoke it.
4. Now navigate to “Controls” tab item invoke it 
5. Now run "Color contrast Analyzer" tool and apply color contrast for "Raw" button and observe the issue for Raw button
6. Verify whether the "Raw" button meets the minimum required ratio of 4.5:1 or not.

### System

```shell
OS: Windows 11
OS version: 22H2 (OS Build 22621.1992)
Edge Version: 114.0.1823.79 (Official build) (64-bit)
```

### Additional context

![4 5](https://github.com/storybookjs/storybook/assets/93735775/1404eb0d-fb5c-46d9-8a8e-c1475a2be5ae)

**Comment by HriGrit** [comment]
Hey @msftedad, 
I would like to work on this issue, if still viable please allow me to.
