### ISSUE TITLE
The contrast ratio between foreground and background color of Drop down chevron in “Accessibility pane" is 2.4:1" which is less than required ratio 3:1.

### ISSUE THREAD

**Issue by msftedad** [storybookjs/storybook#23455]
### Describe the bug

The contrast ratio between foreground and background colors of Drop down chevron in “Accessibility pane is 2.4:1" which is less than required ratio 3:1.

### To Reproduce

1. Open the URL: (https://vivacommonstorybooktest.blob.core.windows.net/$web/index.html?path=/story/common-navigation--scrolling-panel&globals=backgrounds.grid:!false;backgrounds.value:transparent).
2. Navigate to the app bar present in the left pane using tab key and invoke it using Enter key.
3. Navigate to the "Default" link and invoke it.
4. Now navigate to “Accessibility” tab item invoke it and navigate to "16 passes" button invoke it and navigate any of the drop down.
5. Now run "Color contrast Analyzer" tool and apply color contrast for Drop down and observe the issue for drop down chevron. 
6. Verify whether the Drop chevron meets the minimum required ratio of 3:1 or not.

### System

```shell
OS: Windows 11
OS version: 22H2 (OS Build 22621.1992)
Edge Version: 114.0.1823.79 (Official build) (64-bit)
```

### Additional context

![contrast ratio 2 4](https://github.com/storybookjs/storybook/assets/93735775/83e0e165-e7ff-453b-a7ce-3b7624a68588)

**Comment by tolkadot** [comment]
I'd be happy to look at this one further.

**Comment by valentinpalkovic** [comment]
cc @cdedreuille, @MichaelArestad

**Comment by cdedreuille** [comment]
Great catch. If you are interested in taking this one @tolkadot that would be awesome. Please let me know if you have any issue here or on Discord.

**Comment by tolkadot** [comment]
PR here:  https://github.com/storybookjs/storybook/pull/24402
