### ISSUE TITLE
[Bug]: Storybook build gets stuck at 10%. It looks like it can't find anything to build

### ISSUE THREAD

**Issue by mjperales** [storybookjs/storybook#23460]
### Describe the bug

After I follow all the steps to upgrade to Storybook 7, my build is stuck after `Using default webpack5 setup`. It seems like it doesn't find any entries. 

Storybook 7 terminal: it won't get pass this at all
<img width="406" alt="Screenshot 2023-07-14 at 10 31 18 AM" src="https://github.com/storybookjs/storybook/assets/5091158/e782446e-8b1b-438e-abf1-ae5f1309ab4f">

Storybook ^6: builds just fine
<img width="489" alt="Screenshot 2023-07-14 at 10 35 30 AM" src="https://github.com/storybookjs/storybook/assets/5091158/5a170b15-77d0-49ce-ada3-1a9bb051207e">

### To Reproduce

I'm not sure how you can reproduce but here is a summary of our setup:
Monorepo with Storybook installed _only_ at the root level. List of add-ons: `@storybook/addon-links, @storybook/addon-essentials, @storybook/addon-interactions`. We do not have an issue with the automatic migration scripts. Things go smoothly until we have to build storybook. 

### System

```shell
Environment Info:

  System:
    OS: macOS 13.4.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
    npm: 9.7.2 - ~/.nvm/versions/node/v18.13.0/bin/npm
  Browsers:
    Chrome: 114.0.5735.198
    Firefox: 115.0.2
    Safari: 16.5.1
  npmPackages:
    @storybook/addon-actions: ^7.0.27 => 7.0.27 
    @storybook/addon-docs: ^7.0.27 => 7.0.27 
    @storybook/addon-essentials: ^7.0.27 => 7.0.27 
    @storybook/addon-interactions: ^7.0.27 => 7.0.27 
    @storybook/addon-links: ^7.0.27 => 7.0.27 
    @storybook/addon-mdx-gfm: ^7.0.27 => 7.0.27 
    @storybook/react: ^7.0.27 => 7.0.27 
    @storybook/react-webpack5: ^7.0.27 => 7.0.27 
    @storybook/testing-library: ^0.2.0 => 0.2.0
```

### Additional context

main.ts
```
const config = {
  stories: ["../ui/**/*.stories.mdx", "../ui/**/*.stories.@(js|jsx|ts|tsx)"],
  addons: [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/addon-interactions",
  ],
  framework: {
    name: "@storybook/react-webpack5",
    options: {},
  },
  docs: {
    autodocs: true,
  },
};
export default config;
```

preview.tsx
```
const FUSION_HP_VIEWPORTS = {
  "4-units": {
    name: "Fusion HP 4 Units",
    styles: {
      width: "232px",
      height: "100%",
    },
  },
  "5-units": {
    name: "Fusion HP 5 Units (Good for Ads)",
    styles: {
      width: "298px",
      height: "100%",
    },
  },
  "6-units": {
    name: "Fusion HP 6 Units",
    styles: {
      width: "364px",
      height: "100%",
    },
  },
  "7-units": {
    name: "Fusion HP 7 Units",
    styles: {
      width: "430px",
      height: "100%",
    },
  },
  "8-units": {
    name: "Fusion HP 8 Units",
    styles: {
      width: "496px",
      height: "100%",
    },
  },
  "9-units": {
    name: "Fusion HP 9 Units",
    styles: {
      width: "562px",
      height: "100%",
    },
  },
  "10-units": {
    name: "Fusion HP 10 Units (Small layout)",
    styles: {
      width: "628px",
      height: "100%",
    },
  },
  "11-units": {
    name: "Fusion HP 11 Units",
    styles: {
      width: "694px",
      height: "100%",
    },
  },
  "12-units": {
    name: "Fusion HP 12 Units (Medium layout)",
    styles: {
      width: "760px",
      height: "100%",
    },
  },
  "13-units": {
    name: "Fusion HP 13 Units",
    styles: {
      width: "826px",
      height: "100%",
    },
  },
  "14-units": {
    name: "Fusion HP 14 Units",
    styles: {
      width: "892px",
      height: "100%",
    },
  },
  "15-units": {
    name: "Fusion HP 15 Units",
    styles: {
      width: "958px",
      height: "100%",
    },
  },
  "16-units": {
    name: "Fusion HP 16 Units (Large layout)",
    styles: {
      width: "1024px",
      height: "100%",
    },
  },
  "17-units": {
    name: "Fusion HP 17 Units",
    styles: {
      width: "1090px",
      height: "100%",
    },
  },
  "18-units": {
    name: "Fusion HP 18 Units",
    styles: {
      width: "1156px",
      height: "100%",
    },
  },
  "19-units": {
    name: "Fusion HP 19 Units",
    styles: {
      width: "1222px",
      height: "100%",
    },
  },
  "20-units": {
    name: "Fusion HP 20 Units (Max layout)",
    styles: {
      width: "1288px",
      height: "100%",
    },
  },
};

const preview = {
  actions: { argTypesRegex: "^on[A-Z].*" },
  backgrounds: {
    default: "story",
    values: [
      {
        name: "story",
        value: theme.colors.gray400,
      },
    ],
  },
  controls: {
    matchers: {
      color: /(background|color)$/i,
      date: /Date$/,
    },
  },
  darkMode: {
    stylePreview: true,
    darkClass: darkTheme.className,
  },
  layout: "fullscreen",
  viewport: {
    viewports: { ...FUSION_HP_VIEWPORTS, ...INITIAL_VIEWPORTS },
  },
};

export default preview;

function GlobalStyles(props) {
  globalStyles();
  return props.children;
}

export const decorators = [
  (renderStory) => <GlobalStyles>{renderStory()}</GlobalStyles>,
];
```

**Comment by andreiwow2** [comment]
I am also having the same issue

**Comment by shilman** [comment]
Do you a have a reproduction repo you can share? If not, can you create one? Go to https://storybook.new or see [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce). Thank you! 🙏

**Comment by andreiwow2** [comment]
@shilman 
Here is a repository with a project that I am trying to set up.

I am trying to set up a package where I could create react components to use later in wordpress editor.

So far is bare bones as I was still trying to bring everything together, I started experiencing issues when I tried adding tailwind.

Later tried adding Vite, and now removed vite and is basically to its previous state.

I removed node_modules and the lock file multiple times, tried on different computers but the issue is still there.

If I run `npm run storybook` it will get stuck at 10%, same as the post author.

Here is the repository: https://github.com/appsforyoou/wordpress-blocks

**Comment by shilman** [comment]
@andreiwow2 I was able to get it unstuck by commenting out these lines. It still doesn't build properly, but it runs to completion:

https://github.com/appsforyoou/wordpress-blocks/blob/main/tsconfig.json#L18-L23

**Comment by andreiwow2** [comment]
> @andreiwow2 I was able to get it unstuck by commenting out these lines. It still doesn't build properly, but it runs to completion:
> 
> https://github.com/appsforyoou/wordpress-blocks/blob/main/tsconfig.json#L18-L23

I will try once I get home as I am on the way right now, will try to get it to build, do you have an explanation why the paths caused that?
