### ISSUE TITLE
[Documentation]: Essential addons - Highlight addon missing page

### ISSUE THREAD

**Issue by lucapollani** [storybookjs/storybook#23487]
### Describe the problem

Hi, 
I was checking the documentation about [Essential addons](https://storybook.js.org/docs/react/essentials/introduction) and encountered a problem with the Highlight addon link which refers to this page: https://storybook.js.org/docs/react/essentials/highlight but it's actually not existing.

**Comment by jonniebigodes** [comment]
@lucapollani, thanks for catching this. We appreciate it 🙏 ! I'm already following up with the team on it, and a pull request will address this depending on how we should proceed.

Hope you have a great day.

Stay safe

**Comment by kylegach** [comment]
This will be closed by #23524

**Comment by jonniebigodes** [comment]
@kylegach not so much, actually the documentation requires a bit of tweaking. The pull request you referenced addresses a small part of it
