### ISSUE TITLE
[Bug]:  the storysource "args=>" appears in the story panel

### ISSUE THREAD

**Issue by mjsorribas** [storybookjs/storybook#23484]
### Describe the bug

Storybook version: 6.5.6
Storysource version: 6.5.16
Error on rendering the component: The "args =>" appears in the story panel
screenshot:

![storybook-bug-on-storysource](https://github.com/storybookjs/storybook/assets/1266065/864b4026-d85c-46a3-bec1-fd0f68e79508)

I think this is not the correct behavior. Exists a way to prevent showing the args with the arrow?

### To Reproduce

Install this versions of storybook and storysource
Storybook version: 6.5.6
Storysource version: 6.5.16
Create a component with args and the story for this one with the args too.
Run the storybook.
Verify if the args with the arrow appear in the story panel with the component code.

### Additional context

storybook main config file:
`
module.exports = {
	stories: ["../src/**/*.stories.(js|mdx)"],
	addons: [
		"@storybook/addon-a11y",
		"@storybook/addon-postcss",
		"@storybook/addon-controls",
		"@storybook/addon-measure",
		"@storybook/addon-backgrounds",
		"@storybook/addon-outline",
		"storybook-dark-mode",
		"storybook-addon-grid",
		{
      name: '@storybook/addon-docs',
      options: {
        sourceLoaderOptions: {
          injectStoryParameters: false,
        },
      },
    },
    {
      name: '@storybook/addon-storysource',
      options: {
        loaderOptions: {
          prettierConfig: { printWidth: 80, singleQuote: false },
        },
      },
    }
	]
};
`

**Comment by valentinpalkovic** [comment]
Is this issue still reproducible in Storybook 7? @mjsorribas Can you provide a reproduction?
