### ISSUE TITLE
[Bug]: Storybook + Yarn PnP Windows drive issue

### ISSUE THREAD

**Issue by rawfg** [storybookjs/storybook#23497]
### Describe the bug

Storybook crashes when the Yarn PnP `cacheFolder`  is located on a different drive than `C`. When running `yarn storybook` the path contains combined `C` and `D` drive (`C:\Users\rawf\projects\storybook-pnp-issues\D:\yarn\@storybook-manager-npm-7.0.26-ce3e1a67d5-4912726b5d.`):
```
ERR! Error: Failed to load static files, no such directory: C:\Users\rawf\projects\storybook-pnp-issues\D:\yarn\@storybook-manager-npm-7.0.26-ce3e1a67d5-4912726b5d.zip\node_modules\@storybook\manager\static
```
 This issue doesn't occur when the `cacheFolder` property points to the `C` drive.

There is a [sample project](https://github.com/rawfg/storybook-pnp-issue) provided.

### System

```shell
Environment Info:

  System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.6.1 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1992.0), Chromium (114.0.1823.82)
```

**Comment by jinder** [comment]
Also seeing this with Yarn 4
