### ISSUE TITLE
[Documentation]: "Stories for multiple components › Using children as an arg" in CSF3 not working as expected

### ISSUE THREAD

**Issue by pierreburel** [storybookjs/storybook#23523]
### Describe the problem

I cannot reproduce the ["Using children as an arg"](https://storybook.js.org/docs/react/writing-stories/stories-for-multiple-components#using-children-as-an-arg) example with both `ListItem` and `List` stories written with CSF3 as it throws `Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.`.

Writing `ListItem` in CSF2 resolve the issue, but maybe the documentation should be clearer?

Here's a repository with a simple example: https://github.com/pierreburel/storybook-7-csf-3-children-arg

May be related to #15954.

### Additional context

TypeScript error:

```
JSX element type 'Checked' does not have any construct or call signatures. ts(2604)
'Checked' cannot be used as a JSX component.
  Its type 'StoryAnnotations<ReactRenderer, ListItemProps>' is not a valid JSX element type. ts(2786)
```

**Comment by pierreburel** [comment]
No problem. Still, maybe the doc should be updated to avoid confusing users, as this feature just doesn't work yet despite being documented since SB7 launch (and #15954 being open for almost 2 years).

**Comment by jonniebigodes** [comment]
Our learning team is aware of it, and we hope to prioritize this and get the documentation when possible. We'll need to sync up and get some help from the other Storybook maintainers to get this properly vetted and updated.
