### ISSUE TITLE
[Bug]: Unexpected code documentation in docs page for CSF3

### ISSUE THREAD

**Issue by donaldpipowitch** [storybookjs/storybook#23526]
### Describe the bug

Let's take this code as an example:

```
export const Example: StoryObj = {
  render: () => <p>Hello!</p>,
  parameters: {
    docs: {
      description: {
        story: `This is an example.`,
      },
    },
  },
};
```

I'd have guessed only `<p>Hello!</p>` shows up in the code preview of this example in the docs page, but it is actually the whole object. The `parameters` for example should only configure the Storybook example, but should not be relevant for the consumer of the documented component.

<img width="449" alt="image" src="https://github.com/storybookjs/storybook/assets/1152805/152bd7c6-8b17-421f-9f8b-30f255dbc9be">

### To Reproduce

https://codesandbox.io/p/sandbox/trusting-morning-vr6qzh?file=%2Fsrc%2Fstories%2FButton.stories.tsx%3A52%2C1

Run the "Run storybook" task in the terminal and navigate to https://vr6qzh-6006.csb.app/?path=/docs/example-button--docs.

### System

Storybook 7.1.0

**Comment by shilman** [comment]
Thanks for raising! This is a documentation issue. I've updated the docs here: https://github.com/storybookjs/storybook/pull/23531/files

This was done for historical reasons. When we introduced `args` in 6.0 it broke the original source model of showing the raw source code and we created dynamic snippet rendering to work around that. However, we didn't render no-arg story functions that way since at that time all existing stories were no-arg and the old model worked and dynamic snippets was an experimental feature. We should probably update `dynamic` to be the default in 8.0....

**Comment by ddiddi** [comment]
Can I take this up as a fix?

**Comment by shilman** [comment]
@ddiddi Thanks for volunteering but I think the documentation is already fixed in my PR above. Changing the code behavior would be a breaking update, so cannot happen until 8.0 if we choose to make the change. So I don't think there's anything more to be done now.

**Comment by donaldpipowitch** [comment]
@shilman, thank you! This works. I believe this issue can be closed then.
<img width="1384" alt="image" src="https://github.com/storybookjs/storybook/assets/1152805/18fca76d-0162-4bda-ace0-1d482f190b93">

(By the way: Tried to this new Codesandbox Cloud Environment for the very first time and it is wonderful for showing Storybook examples/bugs 🤯 Are there official templates as a starter by any chance?)

**Comment by JReinhold** [comment]
> By the way: Tried to this new Codesandbox Cloud Environment for the very first time and it is wonderful for showing Storybook examples/bugs 🤯 Are there official templates as a starter by any chance?

That loads incredibly fast, wow.

We don't have Codesandbox templates, we have these using StackBlitz instead: https://storybook.new

They are all based on sandboxes in the sandboxes repo: https://github.com/storybookjs/sandboxes/tree/main

Use the `after-storybook` directory to get a sandbox with Storybook and the chosen framework. I'm not sure if the repo+directory can be imported to Codesandbox.

**Comment by donaldpipowitch** [comment]
Good hint, thank you!
