### ISSUE TITLE
[Bug]: propFilter on reactDocgenTypescript doesn't seem to properly filter node_modules

### ISSUE THREAD

**Issue by genepaul** [storybookjs/storybook#23543]
### Describe the bug

I am building a component library based on Material UI, so a lot of my props extend Material UI props types. However, I want to *exclude* Material UI from props arg tables to make them cleaner (I plan to link to the relevant MUI documentation to supplement information).

So I added the following to my `main.ts`, as instructed in various locations:

```
typescript: {
    reactDocgen: 'react-docgen-typescript',
    reactDocgenTypescriptOptions: {
      propFilter: (prop) => {
        return prop.parent ? !(/node_modules/.test(prop.parent.fileName)) : true;
      }
    }
  }
```

This properly filters out the base HTMLAttributes that MUI extends from (so under the `@types/react` location), but it does not filter out the MUI props. When console logging in the `propFilter`, it appears that both `parent` and `declarations` are undefined for the MUI props. I'm not knowledgeable enough about the TypeScript compiler to understand what that entails, but it makes it impossible for me to detect where the prop is coming from to decide whether to filter it out.

### To Reproduce

Storybook:

https://64b96fcd5b9a471054b3e296-nwxguudiuq.chromatic.com/?path=/docs/example-button--docs
https://github.com/genepaul/sb-ts-repro

I just updated the example button component's props to extend MUIButtonProps, and the issue became apparent.

### System

```shell
Environment Info:

  System:
    OS: macOS 12.6.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
  Browsers:
    Chrome: 115.0.5790.98
    Edge: 114.0.1823.37
    Safari: 15.6.1
  npmPackages:
    @storybook/addon-essentials: ^7.1.0 => 7.1.0 
    @storybook/addon-interactions: ^7.1.0 => 7.1.0 
    @storybook/addon-links: ^7.1.0 => 7.1.0 
    @storybook/addon-onboarding: ^1.0.7 => 1.0.8 
    @storybook/blocks: ^7.1.0 => 7.1.0 
    @storybook/react: ^7.1.0 => 7.1.0 
    @storybook/react-webpack5: ^7.1.0 => 7.1.0 
    @storybook/testing-library: ^0.2.0 => 0.2.0
```

**Comment by shilman** [comment]
Probable duplicate to https://github.com/storybookjs/storybook/issues/23418

Please lmk if that isn't the case!

**Comment by genepaul** [comment]
@shilman - I don't know how I didn't find that issue when I searched. It seems similar, however, it mentions typescript >= 5.1.3. I'm seeing this on typescript 4.9.5, so I'm not sure. I can add some details to that issue though.

**Comment by shilman** [comment]
Hi @genepaul it's odd that the other user is seeing this only in more recent versions of typescript. If you can comment with a reproduction on the other issue, hopefully we can get to the bottom of it
