### ISSUE TITLE
[Bug]: 7.1 Table of contents is not scrollable

### ISSUE THREAD

**Issue by ajkl2533** [storybookjs/storybook#23542]
### Describe the bug

When TOC became too long that overflows the viewport there is no way how to scroll to the lower items.

https://github.com/storybookjs/storybook/assets/18654425/f5e472b0-af49-4ede-b147-e2f0df347cde

### To Reproduce

1. Enable TOC
2. Open component docs (ideally with many stories)
3. Make the viewport smaller so that TOC overflows 

### System

```shell
Environment Info:

  System:
    OS: macOS 13.4.1
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 3.5.0 - ~/.nvm/versions/node/v16.16.0/bin/yarn
    npm: 8.14.0 - ~/Projects/design-system-v2/node_modules/.bin/npm
  Browsers:
    Chrome: 114.0.5735.198
    Safari: 16.5.1
  npmPackages:
    @storybook/addon-a11y: ^7.1.0 => 7.1.0 
    @storybook/addon-actions: ^7.1.0 => 7.1.0 
    @storybook/addon-designs: ^7.0.1 => 7.0.1 
    @storybook/addon-docs: ^7.1.0 => 7.1.0 
    @storybook/addon-essentials: ^7.1.0 => 7.1.0 
    @storybook/addon-interactions: ^7.1.0 => 7.1.0 
    @storybook/blocks: ^7.1.0 => 7.1.0 
    @storybook/components: ^7.1.0 => 7.1.0 
    @storybook/jest: ^0.1.0 => 0.1.0 
    @storybook/react: ^7.1.0 => 7.1.0 
    @storybook/react-vite: ^7.1.0 => 7.1.0 
    @storybook/test-runner: ^0.11.0 => 0.11.0 
    @storybook/testing-library: ^0.2.0 => 0.2.0
```

**Comment by vanessayuenn** [comment]
@shilman do you have any pointers for @almoghaimo?

**Comment by vineetpradhan-dev** [comment]
Hi @vanessayuenn, I would like to work on this issue

**Comment by vineetpradhan-dev** [comment]
Hi @vanessayuenn, If no one is currently working on this I would like to work on this issue

**Comment by almoghaimo** [comment]
Hi @vineetpradhan-dev I have already started to work on it. 
I managed to reproduce the bug and pop up with a solution. 

Are there any pointers about how to test it?
In addition, I'll add a video on what it looks like, can you tell if the scroll behavior is how it is expected to be?

https://github.com/storybookjs/storybook/assets/18032913/edbbb99f-369a-48aa-891d-a5f6445f1458


@vanessayuenn @shilman
