### ISSUE TITLE
[Bug]: Storybook in Safari not working

### ISSUE THREAD

**Issue by feerglas** [storybookjs/storybook#23564]
### Describe the bug

Hi there.

I did setup a new Storybook project wit `npx storybook@latest init` and did choose the `html/vite` config manually via CLI. Without changing anything inside the project, the browser just shows a blank page and i get the following error in `Safari Version 16.3 (18614.4.6.1.6)`:

`SyntaxError: Unexpected token '{'`

But if i open a story via iframe, for example `http://localhost:6006/iframe.html?id=example-button--primary&viewMode=story` it shows the story properly without any errors.

My Safari is clean, i have no addons installed. Same behaviour in normal and private windows.

### System

```shell
Environment Info:

  System:
    OS: macOS 13.2.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 18.16.1 - ~/.asdf/installs/nodejs/18.16.1/bin/node
    npm: 9.5.1 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Chrome: 110.0.5481.100
    Edge: 111.0.1661.51
    Safari: 16.3
  npmPackages:
    @storybook/addon-essentials: ^7.1.0 => 7.1.0 
    @storybook/addon-interactions: ^7.1.0 => 7.1.0 
    @storybook/addon-links: ^7.1.0 => 7.1.0 
    @storybook/blocks: ^7.1.0 => 7.1.0 
    @storybook/html: ^7.1.0 => 7.1.0 
    @storybook/html-vite: ^7.1.0 => 7.1.0 
    @storybook/testing-library: ^0.2.0 => 0.2.0
```

**Comment by valentinpalkovic** [comment]
Hi @feerglas 

Thank you for bringing up this issue! Unfortunately, I wasn't able to reproduce it. Could you provide a reproduction?

**Comment by xfinx** [comment]
I have exactly the same outcome. On both a fresh install on a fresh Vue install and one just upgraded from Version 7.1.0 to 7.1.1

```
npm init vue@latest
Need to install the following packages:
  create-vue@3.7.2
Ok to proceed? (y) 

Vue.js - The Progressive JavaScript Framework

✔ Project name: … vue-project
✔ Add TypeScript? … No / Yes
✔ Add JSX Support? … No / Yes
✔ Add Vue Router for Single Page Application development? … No / Yes
✔ Add Pinia for state management? … No / Yes
✔ Add Vitest for Unit Testing? … No / Yes
✔ Add an End-to-End Testing Solution? › No
✔ Add ESLint for code quality? … No / Yes
✔ Add Prettier for code formatting? … No / Yes

Scaffolding project in 
```
```
% npx storybook@latest init

 storybook init - the simplest way to add a Storybook to your project. 

 • Detecting project type. ✓
 • Preparing to install dependencies. ✓



up to date, audited 425 packages in 721ms

134 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
. ✓
 • Detected Vite project. Setting builder to Vite. ✓
 • Adding Storybook support to your "Vue 3" app
  ✔ Getting the correct version of 10 packages
✔ We have detected that you're using ESLint. Storybook provides a plugin that gives the best experience with Storybook and helps follow best practices: https://github.com/storybookjs/eslint-plugin-storybook#readme

Would you like to install it? … yes
    Configuring Storybook ESLint plugin at .eslintrc.cjs
  ✔ Installing Storybook dependencies
. ✓
 • Preparing to install dependencies. ✓


up to date, audited 1148 packages in 1s

244 packages are looking for funding
  run `npm fund` for details

2 moderate severity vulnerabilities

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
. ✓

attention => Storybook now collects completely anonymous telemetry regarding usage.
This information is used to shape Storybook's roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://storybook.js.org/telemetry
```

**Comment by floroz** [comment]
We run this across our company and can confirm it's not working on Safari 16.3 but working on Safari 16.5

We are running Storybook v7.1.0

**Comment by vinceumo** [comment]
Same issue on 7.1.1, all good on Chrome and Firefox
(Safari 16.2)

![image](https://github.com/storybookjs/storybook/assets/21067002/7e2582e0-7675-4b69-bb4c-576596860564)

**Comment by yannbf** [comment]
Some more context: after some investigation, I can confirm that this issue got introduced in @storybook/manager version [7.1.0-alpha.40](https://github.com/storybookjs/storybook/releases/tag/v7.1.0-alpha.40) (it works in [7.1.0-alpha.39](https://github.com/storybookjs/storybook/releases/tag/v7.1.0-alpha.39)).

It is related to the static syntax used like so:
![image](https://github.com/storybookjs/storybook/assets/1671563/4f364924-f877-4297-aed7-85fed52b8ed3)

when all the (three) occurrences of `static {}` are removed, it all works again.

**Comment by kasperpeulen** [comment]
I can confirm the issue does not happen in Safari 16.4.

@ndelangen did the browser target change in esbuild on 7.1?

**Comment by cb-deveshpawar** [comment]
Same issue on 7.1.0 with safari , all good on Chrome 
![image](https://github.com/storybookjs/storybook/assets/107927400/5d721022-addf-4100-bea0-693180fc35e8)

**Comment by ndelangen** [comment]
No it's been chrome100 ever since 7.0:
https://github.com/storybookjs/storybook/blob/46e914d41eb2a355e962a3d02508aea7b921217f/scripts/prepare/esm-bundle.ts#L81

**Comment by jphawk** [comment]
The issue is still present, running latest Storybook@7.6.11 and it doesn't work in Safari below 16.5, getting `SyntaxError: Unexpected token '{'`. Is there any plan to fix this?

**Comment by kasperpeulen** [comment]
Hm, that is weird, I'm seeing something different:
<img width="514" alt="image" src="https://github.com/storybookjs/storybook/assets/1035299/8ad06af7-43d8-486c-b04c-11603cb2e766">

Can you show us a stackblitz repro?
