### ISSUE TITLE
[Bug]: Can't install storybook with Angular v16.1.0

### ISSUE THREAD

**Issue by morenoisidro** [storybookjs/storybook#23568]
### Describe the bug

I'm trying to install `storybook@latest` in an Angular v16.1.0 project and installation fails.

I have created single-workspace Angular project (v16.1.0) with Angular CLI. (Check source code [here](https://github.com/morenoisidro/ng-kitsune/tree/b8b3c89b616bb4377cdf3ce110d3ef6f356926d8) ): 

When I run: `npx storybook@latest init`

**Issue:** Builder is not detected and project is recognized as an Nx project, but I'm not using Nx. 

Output:
```
✔ We were not able to detect the right builder for your project. Please select one: › Webpack 5

     Error: We have detected Nx in your project. Please use "nx g @nrwl/storybook:configuration" to add Storybook to your project.

For more information, please see https://nx.dev/packages/storybook
    at runGenerator (/Users/isidro/.npm/_npx/bc7e1e37fcb46ffc/node_modules/@storybook/cli/dist/generate.js:89:5803)
    at installStorybook (/Users/isidro/.npm/_npx/bc7e1e37fcb46ffc/node_modules/@storybook/cli/dist/generate.js:93:795)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async doInitiate (/Users/isidro/.npm/_npx/bc7e1e37fcb46ffc/node_modules/@storybook/cli/dist/generate.js:98:845)
    at async withTelemetry (/Users/isidro/.npm/_npx/bc7e1e37fcb46ffc/node_modules/@storybook/core-server/dist/index.js:113:3659)
    at async initiate (/Users/isidro/.npm/_npx/bc7e1e37fcb46ffc/node_modules/@storybook/cli/dist/generate.js:111:602)
```

Workaround (kind of...): I've tried `npx storybook@7.0.6 init` and everything went fine. But noticed v7.1.0 was installed instead. Weird... - Check resulting changes [here](https://github.com/morenoisidro/ng-kitsune/commit/3ff51b3461d8b4db4343ec78a259fd4f88b46785)

### To Reproduce

1. Checkout https://github.com/morenoisidro/ng-kitsune/tree/v0.1.0
2. Run `npx storybook@latest init`

### System

```shell
Environment Info:

  System:
    OS: macOS 13.4.1
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 18.16.1 - /usr/local/bin/node
    npm: 9.5.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 115.0.5790.102
    Edge: 115.0.1901.183
    Safari: 16.5.2
```

**Comment by valentinpalkovic** [comment]
We will fix this soon-ish. In the meantime, please try to initialize with Storybook 7.0

```
npx storybook@7.0.27 init
```

It will still set up your project with Storybook 7.1 dependencies. Let me know whether this works as a temporary workaround.

**Comment by morenoisidro** [comment]
Thanks @valentinpalkovic ! I noticed you already pushed a fix. Glad it wasn't a false positive. Thanks for your help!
