### ISSUE TITLE
[Bug]: Error: plugin.fn is not a function

### ISSUE THREAD

**Issue by sachinwalunj2008** [storybookjs/storybook#23587]
We have a react component library with React 18. In that, we have used the `@tippyjs/react` package.
I have upgraded the storybook to version 7.0.0.

In those components where we have used this tippy in that component, we are getting the below error. 

This issue only happened for the stage and production versions in the development mode; it's not throwing any errors.

Error: plugin.fn is not a function
  at Array.map (<anonymous>))
  at createTippy (/8499.1eaabdfe.iframe.bundle.js:432:58334))
  at /8499.1eaabdfe.iframe.bundle.js:432:68963
  at Array.reduce (<anonymous>))
  at tippy1 (/8499.1eaabdfe.iframe.bundle.js:432:68908))
  at /8499.1eaabdfe.iframe.bundle.js:432:78255
  at Rj (/8499.1eaabdfe.iframe.bundle.js:452:96314))
  at lk (/8499.1eaabdfe.iframe.bundle.js:452:103507))
  at jk (/8499.1eaabdfe.iframe.bundle.js:452:103352))

To Reproduce the 

please install the `npm i @tippyjs/react` in your project and used the tippyjs component in your story.

**Comment by valentinpalkovic** [comment]
Hi @sachinwalunj2008,

Please fill out the issue template appropriately. The provided information needs to be more helpful. What would you like to achieve? Does the issue happen during storybook init or dev? Please also provide information about your environment and give a reproduction if possible.
