### ISSUE TITLE
[Bug]: `storybook dev` works, `storybook build` fails error `TypeError: Converting circular structure to JSON`

### ISSUE THREAD

**Issue by mkosir** [storybookjs/storybook#23604]
### Describe the bug

Upgrade of Storybook from `v7.0.27` to `v7.1.0` introduced error.

`storybook dev` command still works as expected.

`storybook build` command fail with error:
```sh
> storybook build

@storybook/cli v7.1.1

info => Cleaning outputDir: /storybook-static
info => Loading presets
info => Building manager..
info => Manager built (67 ms)
info => Compiling preview..
info => Copying static files: /Users/markokosir/Desktop/projects/frontend-monorepo-boilerplate/node_modules/@storybook/manager/static at /Users/markokosir/Desktop/projects/frontend-monorepo-boilerplate/apps/boilerplate-app/storybook-static/sb-common-assets
WARN You (or an addon) are using the 'config' preset field. This has been replaced by 'previewAnnotations' and will be removed in 8.0
info Addon-docs: using MDX2
info => Using implicit CSS loaders
Unexpected 'default'. Parameter 'options.storySort' should be defined inline e.g.:

export default {
  parameters: {
    options: {
      storySort: <array | object | function>
    },
  },
};
Unexpected 'default'. Parameter 'options.storySort' should be defined inline e.g.:

export default {
  parameters: {
    options: {
      storySort: <array | object | function>
    },
  },
};
info => Using default Webpack5 setup
10% building 0/1 entries 0/0 dependencies 0/0 modulesERR! TypeError: Converting circular structure to JSON
ERR!     --> starting at object with constructor 'Array'
ERR!     |     index 10 -> object with constructor 'Object'
ERR!     |     property 'loc' -> object with constructor 'SourceLocation'
ERR!     --- property 'tokens' closes the circle
ERR!     at JSON.stringify (<anonymous>)
...
```

### To Reproduce

- clone [frontend-monorepo-boilerplate](https://github.com/mkosir/frontend-monorepo-boilerplate) project
- `npm i`
- navigate to (any) monorepo app `cd apps/boilerplate-app`
- `npm run storybook-build` -> error
- (`npm run storybook` works)

### System

```shell
Environment Info:
  System:
    OS: macOS 13.5
    CPU: (12) arm64 Apple M2 Max
  Binaries:
    Node: 18.17.0 - ~/.nvm/versions/node/v18.17.0/bin/node
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.0/bin/npm
  Browsers:
    Chrome: 114.0.5735.198
    Safari: 16.6
  npmPackages:
    @storybook/addon-essentials: 7.1.1 => 7.1.1 
    @storybook/nextjs: 7.1.1 => 7.1.1 
    @storybook/react: 7.1.1 => 7.1.1
```

### Additional context

If Storybook dependencies in `package.json` are downgraded to `v7.0.27`, build is successful.

**Comment by rolandfung** [comment]
@mkosir Do you have named exports ./storybook/preview.js? I was having the same issue, and removing the export statements made build-storybook work again for me (wasn't an issue since I wasn't importing them anywhere anyway).

**Comment by mkosir** [comment]
@rolandfung thanks for pointing it out, default export does the trick 👍 , but would be still nice to see this one fixed 🤞

**Comment by vicrep** [comment]
For a little additional clarity on @rolandfung 's workaround, since it wasn't immediately clear to me. You need to convert named exports for your preview configuration to a single default export of an object containing said configuration keys.

i.e. to work around, change your `preview.ts/js` from
```ts
export const parameters = []
export const decorators = []
export const loaders = []
```

to this:
```ts
const parameters = []
const decorators = []
const loaders = []

const preview = { parameters, decorators, loaders }
export default preview
```

**Comment by shilman** [comment]
@jake-chapman-mark43 Looks like a regression. We'll try to get a fix out in the next release.

**Comment by rishabhmhjn** [comment]
I had the same issue when I found that I had a type export (example below) in my `$ROOT/.storybook/preview.ts` in the nx repository that caused the issue.

```
// $root/.storybook/preview.ts
export type GlobalTypesContext = {
  parameters: {
    layout?: 'fullscreen';
  };
};
```

Commenting it out fixed the issue for me.

This did work in the previous Storybook versions.
