### ISSUE TITLE
[Bug]: Storybook does not render vue3 components in .mdx files

### ISSUE THREAD

**Issue by Juanjo-GEx** [storybookjs/storybook#23627]
### Describe the bug

When creating an .mdx file with my iconography, storybook does not render my icons that have been defined as components.
I have tried to install the following package: **storybook-addon-vue-md**x but it still does not render the icons

### To Reproduce

This is the structure of one os mi icons:
```
<template>
  <svg
    width="24"
    height="24"
    viewBox="0 0 24 24"
    fill="none"
    xmlns="http://www.w3.org/2000/svg">
    <g clip-path="url(#clip0_2214_21994)">
      <path
        d="M20 6L9 17L4 12"
        stroke="#000"
        stroke-width="1.5"
        stroke-linecap="round"
        stroke-linejoin="round" />
    </g>
    <defs>
      <clipPath id="clip0_2214_21994">
        <rect
          width="24"
          height="24"
          fill="white" />
      </clipPath>
    </defs>
  </svg>
</template>
```

and this is the code of the .mdx file where I want to display my icons:
```
import { Meta, Title, IconGallery, IconItem } from '@storybook/blocks';
import { iconCheck } from '../components/icons';

<Meta title="Iconography" />

# Iconography

<IconGallery>
  <IconItem name="check">
    <icon-check name="check" />
  </IconItem>
</IconGallery>
```

### System

```shell
v.7.0.9.
```

### Additional context

The addon is correctly added in main.ts
Imports are done correctly.
The html displays the <icon-check> selector but does not render the associated component.

**Comment by Juanjo-GEx** [comment]
Updated the storybook version to 7.1.1 the same bug still persists

**Comment by santi755** [comment]
@Juanjo-GEx Did you get it?

**Comment by shilman** [comment]
Please file an issue on the addon repo https://github.com/Sidnioulz/storybook-addon-vue-mdx
