### ISSUE TITLE
[Bug]: React StorybookConfig type definition inconsistent with docs

### ISSUE THREAD

**Issue by TheSonOfThomp** [storybookjs/storybook#23624]
### Describe the bug

Using the custom implementation logic defined on the docs site results in a Typescript error.

```ts
// .storybook/main.ts

// Replace your-framework with the framework you are using (e.g., react-webpack5, vue3-vite)
import type { StorybookConfig } from '@storybook/react-webpack5';

async function findStories() {
  // your custom logic returns a list of files
  return ['/some/stories.tsx']
}

const config: StorybookConfig = {
  framework: '@storybook/react-webpack5',
  stories: async (list: Array<string> ) => [
//  ^  Type '(list: string[]) => Promise<string[]>' is missing the following properties from type 'StoriesEntry[]': pop, push, concat, join, and 28 more.
    ...list,
    ...(await findStories()),
  ],
};

export default config;
```

### To Reproduce

Use the [stories config  "custom implementation" example](https://storybook.js.org/docs/react/api/main-config-stories) with TypeScript

### System

```shell
Environment Info:

  System:
    OS: macOS 13.4.1
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.16.0/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
  Browsers:
    Chrome: 114.0.5735.248
    Safari: 16.5.2
```

**Comment by yannbf** [comment]
Hey @TheSonOfThomp if you tried to use the following code instead it should work:

```ts
import type { StorybookConfig } from '@storybook/react-webpack5';
import type { StoriesEntry } from '@storybook/types'

async function findStories(): Promise<StoriesEntry[]> {
  // your custom logic returns a list of files
  return ['/some/stories.tsx']
}

const config: StorybookConfig = {
  framework: '@storybook/react-webpack5',
  stories: async (list: StoriesEntry[]) => [
    ...list,
    ...(await findStories()),
  ],
}

export default config
```

**Comment by ASafaeirad** [comment]
Hey @yannbf,

The problem has been resolved in the most recent alpha release (version 8-alpha). However, the type definition for version 7.6.6 currently does not accept a function. ([Source code](https://github.com/storybookjs/storybook/blob/aa37ebd7db974ef7ffb16cda40d07e12eff7ffae/code/lib/types/src/modules/core-common.ts#L409C11-L409C11)).

I created a [reproduction](https://stackblitz.com/edit/github-wconag?file=.storybook%2Fmain.ts%3AL10-L10&preset=node) repo. Seems it's not only a type issue, the first argument (list) is `undefined` and throws a runtime error.

**Comment by yannbf** [comment]
I see! @kasperpeulen would you mind chiming in? Thanks!
