### ISSUE TITLE
[Bug]: Problem with args when are true (!true)

### ISSUE THREAD

**Issue by joseangel-mm** [storybookjs/storybook#23623]
### Describe the bug

Hello, 
I am having issues with some args when I set it to true.
For example, the prop `showInitialGuidance` is set to false by default so if in the controls I set to true the next time I reload the storybook page it should be true but in the url I can see `!true` and the result is like it would set to false.
I've tested changing manually the url to set it to true (without !) and it works.

<img width="241" alt="Screenshot 2023-07-26 at 16 43 25" src="https://github.com/storybookjs/storybook/assets/85619872/20afc5ab-ab36-45a7-9684-778d5f692292">

This is how that prop is defined:
![Screenshot 2023-07-26 at 16 49 08](https://github.com/storybookjs/storybook/assets/85619872/1e9402c3-5088-4862-9e80-4110385d4306)

This problem doesn't happen on the 6.5.0 storybook version (the version that I usually used).

### System

```shell
Environment Info:

  System:
    OS: macOS 13.4.1
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
  Browsers:
    Chrome: 114.0.5735.248
    Safari: 16.5.2
  npmPackages:
    @storybook/addon-actions: 7.1.0 => 7.1.0 
    @storybook/addon-essentials: 7.1.0 => 7.1.0 
    @storybook/addon-links: 7.1.0 => 7.1.0 
    @storybook/addon-storysource: 7.1.0 => 7.1.0 
    @storybook/addon-styling: 1.3.1 => 1.3.1 
    @storybook/builder-vite: 7.1.0 => 7.1.0 
    @storybook/preset-scss: 1.0.3 => 1.0.3 
    @storybook/react: 7.1.0 => 7.1.0 
    @storybook/react-vite: 7.1.0 => 7.1.0
```

**Comment by joseangel-mm** [comment]
After researching a bit more, it seems the problem only happens with arguments whose default value is false and we set it to true besides we reload the page.
With the arguments that are true by default and we set to false there is no problem.

**Comment by vanessayuenn** [comment]
Hi, thanks for reporting this. do you have a reproduction repo you can share? If not, can you create one (see [how to create a repro](https://storybook.js.org/docs/react/contribute/how-to-reproduce)). We prioritize bug reports that have reproduction. Thank you! 🙏

**Comment by joseangel-mm** [comment]
Hello @vanessayuenn, thanks for the response.

It is a bit tricky to replicate the error in a repro because our case involves machine states and other staff.

Here you have a video of the problematic argument (`showInitialGuidance`) which is set in the storybook javascript file as usual 

```javascript
export default {
  title: 'Example/Default',
  component: ExampleComponent,
  argTypes: {
    showInitialGuidance: {
      type: 'boolean',
    },
  },
  args: {
    showInitialGuidance: false,
  },
};
``` 
https://github.com/storybookjs/storybook/assets/85619872/414668b6-62db-49af-98e7-f7131d806829

**Comment by joseangel-mm** [comment]
Hi again @vanessayuenn, I created a [repository](https://github.com/joseangel-mm/storybook-bug) to replicate our issue.

In that project, you can see how properties that start as false are changed to true and once the page is reloaded the true value is lost.


https://github.com/storybookjs/storybook/assets/85619872/4aff49ee-1bf5-4784-9871-0024e94ac206

**Comment by liu351** [comment]
I see the same issue on 7.3.1, if I send someone a link where a control should have been true, the url shows  "property:!true " and the control gets wiped after clicking the link. I can update the URL "property:true" and after clicking the link, the boolean control gets set to true and url is now "property:!true"

**Comment by joseangel-mm** [comment]
Is there any news regarding this issue @vanessayuenn?

**Comment by dcherman** [comment]
@vanessayuenn We're running into this same issue, and I can point you at the bit of code that looks problematic:

https://github.com/storybookjs/storybook/blob/9c6469d6ce9896ba12c75fac1fe8ee39b813fd9f/code/lib/preview-api/src/modules/store/args.ts#L22C11-L22C11

At the point that this function is invoked, the value being passed is an actual boolean, not a string, so `arg === 'true'` will always return false.

I'm not familiar enough with Storybook yet to make a minimal fix here, but the safest option that I can see is doing:

`return String(arg) === 'true'`

If we're positive that only booleans are ever going to be received at this point, then we can just `return arg`, however that's what I'm unsure of at the moment.

**Comment by Mokss** [comment]
Hi, we are have same bug

**Comment by iCoderXXI** [comment]
Hi, same problem on v7.4.3. Looks like this is an issue of controls addon. It incorrectly serializes boolean value to `!true` in url params.
