### ISSUE TITLE
[Bug]: The contrast ratio between foreground and background colors of the links under 'getting started' section is 2.92: 1 which is less than required ratio 4.5:1.

### ISSUE THREAD

**Issue by msftedad** [storybookjs/storybook#23643]
### Describe the bug

The contrast ratio between foreground and background colors of the links under 'getting started' section is 2.92: 1 which is less than required ratio 4.5:1.

Severity: 1

### To Reproduce

Repro Steps: 

1. Open URL: “[Overview - Docs ⋅ Storybook (windows.net)](https://vivacommonstorybooktest.blob.core.windows.net/$web/index.html?path=/docs/overview--docs)” and sign in with valid credentials.  
2. In left navigation select in “App header” under components and invoke it.  
3. Now Run the Color Contrast Anayzer tool for the links.
4. Verify whether the ontrast ratio between foreground and background colors of the links under 'getting started' is meeting required ratio 4.5:1 or not.

### System

```shell
Windows: Win11 Enterprise
OS: Version 22H2 (OS Build 22621.1992) 
Edge Version: Version 114.0.1823.51 (Official build) (64-bit) 

URL:URL: Overview - Docs ⋅ Storybook (windows.net)
```

### Additional context

**Expected result:**
Ensure the contrast between foreground and background colors meets WCAG 2 AA contrast ratio thresholds.

**Attachments:**

<img width="548" alt="MicrosoftTeams-image (8)" src="https://github.com/storybookjs/storybook/assets/93735775/09ae8c13-0b82-4ff0-8461-902e7654dfb7">

**Comment by chocoscoding** [comment]
@msftedad i want to work on this

**Comment by chocoscoding** [comment]
ok, thanks

**Comment by cdedreuille** [comment]
Thanks a lot for reaching out. That's a great question and a great problem to solve. We are in the process of improving our UI library to make it easier, more accessible and to respect as much as possible all accessibility rules.

The change you are asking is quite a tricky one as it is asking to change one of our main colour from Storybook theming. Realistically I don't think that's a change we can handle right now as this will touch a lot of components but it is something I would love to change in the near future when we are updating our default theme.

**Comment by chocoscoding** [comment]
@cdedreuille Thanks for answering in such short time during your vacation.
Is there any issue you can recommend me taking on as a good first issue.

Thanks

**Comment by cdedreuille** [comment]
@chocoscoding I would recommend going into the list of "good first issues" to see if there's something you could help with:
https://github.com/storybookjs/storybook/issues?q=is:open+is:issue+label:%22good+first+issue%22
