### ISSUE TITLE
[Bug]: NullInjectorError: No provider for HttpClient

### ISSUE THREAD

**Issue by thirumurugan-sundaram** [storybookjs/storybook#23657]
### Describe the bug

R3InjectorError(Standalone[StorybookWrapperComponent])[MrwConfigService -> MrwConfigService -> HttpClient -> HttpClient]

even when we import HttpClientModule in the storybook components, we are still getting the null injection error.

getting this issue after migrating the storybook from 6.5.0 to 7.2.0 , storybook components without wrapper component are getting this issue, storybook components with wrapper and content component with module are loading properly,

I tried changing 1 storybook component to the wrapper and content components and added module file and imported the HttpClientModule , and now the null injection error is removed, but facing issues with how to implement the storybook content component.

Do we need to change all storybook components to storybookwrapper, storybookcontent and storybookmodule file type structure to avoid this error ? and if yes is there any migration steps that needs to be followed ??

### System

```shell
"@babel/core": "7.22.8",
    "@compodoc/compodoc": "1.1.21",
    "@storybook/addon-actions": "7.1.0",
    "@storybook/addon-controls": "7.1.0",
    "@storybook/addon-essentials": "7.1.0",
    "@storybook/addon-links": "7.1.0",
    "@storybook/addon-mdx-gfm": "^7.1.0",
    "@storybook/addons": "7.1.0",
    "@storybook/angular": "7.1.0",
    "@storybook/theming": "7.1.0",
```

**Comment by valentinpalkovic** [comment]
Hi @thirumurugan-sundaram,

have you followed the migration guide here: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#angular-application-providers-and-modulewithproviders

Also, take a look at the following comment:
https://github.com/storybookjs/storybook/issues/21942#issuecomment-1516177565

**Comment by thirumurugan-sundaram** [comment]
I have tried following the changes mentioned in the document , but yet we are still facing the nullInjectorError.

Looks like we need to do some code structure changes, the storybook component is loading only after we create a module.ts file and wrapper component for the storybook, earlier it was working without them.

If someone had encountered the same issues, please share the steps to be followed in order to convert the storybook components to the latest compatible structure.

**Comment by EliezerB123** [comment]
What version of Angular are you using? HTTPClient no longer needs a provider in Angular 15.

**Comment by thirumurugan-sundaram** [comment]
> What version of Angular are you using? HTTPClient no longer needs a provider in Angular 15.

Im currently using below angular and storybook versions
"@angular/cdk": "16.1.4",
    "@angular/common": "16.1.4",
    "@angular/compiler": "16.1.4",
    "@angular/core": "16.1.4",
"rxjs": "7.8.1",

"@compodoc/compodoc": "1.1.21",
    "@storybook/addon-actions": "7.2.1",
    "@storybook/addon-controls": "7.2.1",
    "@storybook/addon-essentials": "7.2.1",
    "@storybook/addon-links": "7.2.1",
    "@storybook/addon-mdx-gfm": "^7.2.1",
    "@storybook/addons": "7.2.1",
    "@storybook/angular": "7.2.1",
    "@storybook/theming": "7.2.1",

issue existing in both angular 15 and angular 16 versions after upgrading from angular 14

**Comment by odaper** [comment]
Hello
The migration guide is well documented, you need to import the needed providers from the module and declare them in the new configuration function, as follows (written in my component story .mdx): 
```
applicationConfig({
      providers: [
        importProvidersFrom(HttpClientModule),
       // your other global providers
      ],
    }),
```

**Comment by BijilyRajan** [comment]
> Hello The migration guide is well documented, you need to import the needed providers from the module and declare them in the new configuration function, as follows (written in my component story .mdx):
> 
> ```
> applicationConfig({
>       providers: [
>         importProvidersFrom(HttpClientModule),
>        // your other global providers
>       ],
>     }),
> ```
> 
> I hope that will help you.
> 
> Thanks

This really helped, thanks!

**Comment by jabalka** [comment]
> Hello The migration guide is well documented, you need to import the needed providers from the module and declare them in the new configuration function, as follows (written in my component story .mdx):
> 
> ```
> applicationConfig({
>       providers: [
>         importProvidersFrom(HttpClientModule),
>        // your other global providers
>       ],
>     }),
> ```
> 
> I hope that will help you.
> 
> Thanks

LEGEND! 
I just had no time to read all the migration doc...

**Comment by shilo123** [comment]
> באיזו גרסה של Angular אתה משתמש? HTTPClient כבר לא צריך ספק ב-Angular 15.


אז איך לעשות בקשת HTTP

**Comment by himanshu-skrpkvnp** [comment]
Go to your app.config.ts
Inside the providers array add:

provideHttpClient()

**Comment by constantinrazvan** [comment]
> Go to your app.config.ts Inside the providers array add:
> 
> provideHttpClient()

Thank you! Your response helped me!

**Comment by kagboton** [comment]
> port the needed providers from the module and declare them in the new configuration function, as follows (written in my component story .mdx):

Thks. Worked !

**Comment by kagboton** [comment]
> Go to your app.config.ts Inside the providers array add:
> 
> provideHttpClient()

Thks. Worked !

**Comment by AnilNewari** [comment]
> Go to your app.config.ts Inside the providers array add:
> 
> provideHttpClient()

Thanks. It worked for me

**Comment by Abasolsss** [comment]
> Go to your app.config.ts Inside the providers array add:
> 
> provideHttpClient()

It worked for me thank you

**Comment by oocarrazco** [comment]
It works. Thank you!!!
