### ISSUE TITLE
[Bug]: global providers declared in preview.ts doesn't exist in Storyshots with Angular

### ISSUE THREAD

**Issue by Adrii77** [storybookjs/storybook#23651]
### Describe the bug

In `preview.ts`, global providers registered with `applicationConfig` (such as `provideHttpClient()`), seems to not exist in Storyshots.

By example, if a `ButtonComponent` injects `HttpClient` and if you have inside `preview.ts` :

```
const preview: Preview = {
  decorators: [
    applicationConfig({
      providers: [provideHttpClient()],
    }),
  ],
};

export default preview;
```

You'll find this : 

```
● Storyshots › app/button › Base

    NullInjectorError: R3InjectorError(Standalone[StorybookWrapperComponent])[_HttpClient -> _HttpClient -> _HttpClient]:
      NullInjectorError: No provider for _HttpClient!
```

Important note : It works perfectly when running Storybook. It should works with Storyshots too.

### To Reproduce

1. Clone : https://github.com/Adrii77/sb-storyshots-bug
2. Go to the folder
3. use `npm i`
4. Run `npm run storybook:test` (you'll see the error).

### System

```shell
Environment Info:

  System:
    OS: macOS 13.4.1
    CPU: (12) arm64 Apple M2 Pro
  Binaries:
    Node: 16.20.0 - ~/.nvm/versions/node/v16.20.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.20.0/bin/yarn
    npm: 8.19.4 - ~/.nvm/versions/node/v16.20.0/bin/npm
  Browsers:
    Edge: 113.0.1774.57
    Safari: 16.5.2
  npmPackages:
    @storybook/addon-actions: ^7.2.0-rc.0 => 7.2.0-rc.0
    @storybook/addon-essentials: ^7.2.0-rc.0 => 7.2.0-rc.0
    @storybook/addon-links: ^7.2.0-rc.0 => 7.2.0-rc.0
    @storybook/addon-storyshots: ^7.2.0-rc.0 => 7.2.0-rc.0
    @storybook/angular: ^7.2.0-rc.0 => 7.2.0-rc.0
```

**Comment by a-jones-afi** [comment]
I'm getting the same error using the `provideAnimations()` function. Has anyone managed to fix it?

  ```
devDependencies: {
    "@storybook/addon-a11y": "^7.2.1",
    "@storybook/addon-actions": "7.2.0",
    "@storybook/addon-essentials": "7.2.0",
    "@storybook/addon-interactions": "7.2.0",
    "@storybook/addon-links": "7.2.0",
    "@storybook/addon-storyshots": "7.5.2",
    "@storybook/angular": "7.2.0",
    "@storybook/testing-library": "0.2.0",
  }

**Comment by jonniebigodes** [comment]
The Storyshots addon is officially deprecated and will be removed in a future release of Storybook. To help with the transition process, we've created a [migration guide](https://storybook.js.org/docs/writing-tests/storyshots-migration-guide) for the available options and common use cases.
