### ISSUE TITLE
[Bug]: Watchpack "ignored" configuration causes to many watchers in larger projects and blocks startup

### ISSUE THREAD

**Issue by yhaering** [storybookjs/storybook#23696]
### Describe the bug

The current default configuration for [watchpack](https://github.com/webpack/watchpack/tree/main) in the core-server package only excludes root level node_modules folders (see [here](https://github.com/storybookjs/storybook/blob/next/code/lib/core-server/src/utils/watch-story-specifiers.ts#L36)) which will cause way to many watcher instances beeing opend in monorepository structures. As the result of 5k+ watchers beeing opened, either the OS will throw an "Watchpack Error (watcher): Error: EMFILE: too many open files" or will try to close thousands of watchers which takes ages. (10 minutes in my case, known issue in watchpack https://github.com/webpack/watchpack/issues/222) 

### To Reproduce

1. Create a monorepository with node_modules folder in sub directories.
2. Start `storybook dev` with a breakpoint in the `watchEventSource.js` file https://github.com/webpack/watchpack/blob/main/lib/watchEventSource.js#L66

### System

```shell
Environment Info:

  System:
    OS: macOS 13.5
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 18.12.1 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/.npm-global/bin/yarn
    npm: 7.24.2 - ~/Develop/node_modules/.bin/npm
  Browsers:
    Chrome: 114.0.5735.198
    Safari: 16.6
```

### Additional context

I have already tried updating the ignored list to `**/node_modules` which works way better. I would highly recommend making this list configurable to also exclude folders like build output, coverage etc.

**Comment by Squixx** [comment]
I'd  like to add to this, IMO the --ci property should disable watchmode all together
