### ISSUE TITLE
[Bug]: No forwarding of Sass variables to vue sfc compiler

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [storybookjs/storybook#23705]
### Describe the bug

So, I see a problem where you use sass variables inside a vue sfc file and try to mount that into storybook while having the necessary sass files imported in the main.js. Those variables get not handed down before the sass replacement of those variables takes place.
So all occurrences of the initial sass loading get replaced correctly, but the part from inside the vue sfc files do not get the value replacement applied.

**Comment by sschneider-ihre-pvs** [comment]
```
ModuleBuildError: Module build failed (from ../../node_modules/sass-loader/dist/cjs.js):
Undefined variable.
```
```
 root stylesheet
```

**Comment by vanessayuenn** [comment]
Looks like this is getting addressed in https://github.com/storybookjs/addon-styling/issues/79. I'll close this issue for now.
