### ISSUE TITLE
[Bug]: @storybook/components has a semver dependency on @storybook/icons which only supports React>=17

### ISSUE THREAD

**Issue by frode-carlsen** [storybookjs/storybook#23721]
### Describe the bug

@storybook/components 7.2.1 has peerDependencies
```
"peerDependencies": {
    "react": "^16.8.0 || ^17.0.0 || ^18.0.0",
    "react-dom": "^16.8.0 || ^17.0.0 || ^18.0.0"
  },
```
but a dependency on @storybook/icons which requires React >=17
This results in conflicting peer dependencies when used in an app with React 16
Since Storybook 7 should support React 16, presumably the peerDependencies in icons must be releaxed/fixed

### To Reproduce

`npm install` in a project utilising React 16.14

**Comment by vanessayuenn** [comment]
This should be fixed in the latest version. Please try it out! Feel free to reopen this issue if the problem persists. Thanks!
