### ISSUE TITLE
[Bug]: Storybook Official Plugin Breaking Types & Migration info 

### ISSUE THREAD

**Issue by emzoumpo** [storybookjs/storybook#23749]
### Describe the bug

The plugin `@storybook/addon-styling` is not following the rest of Storybook plugins versions (current version is 1.3.5 instead of 7.2.1), causing bogus migration warnings, not pointing to the right `@storybook/types` and causing type conflicts unless its dependencies are explicitly deduplicated.

This plugin is somehow not bumped like all the other ones, making it difficult to migrate to newer versions, since it doesn't follow the same cadence.

<img width="1079" alt="Screenshot 2023-08-08 at 10 18 26" src="https://github.com/storybookjs/storybook/assets/2103443/ed7731c0-2ba2-4c35-88d0-ab14f83dc6d9">

**Comment by vanessayuenn** [comment]
@Integrayshaun wanna take a look at this?

**Comment by Integrayshaun** [comment]
Hey @emzoumpo 👋 

Thank you for bringing this up! I've got a PR to exclude it from the core packages list so you won't get that error anymore

**Comment by emzoumpo** [comment]
Hi @Integrayshaun, this would indeed solve the warning when upgrading Storybook.

However, it will not resolve the issue that the sub-dependency `@storybook/types` will get duplicated, when running the Storybook migration, because the version range of the `@storybook/types` will not include the version already fetched in the lockfile by `@storybook/addon-styling`.

I already had this issue where Typescript would throw errors because there were two different `.d.ts` files from two different `@storybook/types` versions.

This could be avoided if there was the same requirement for `@storybook/types` as for the rest of the core plugins, so that their versions match and are updated at the same time.

**Comment by Integrayshaun** [comment]
Hey @emzoumpo 

While `@storybook/addon-styling` is an offical addon, it is not considered core because it's not in the monorepo. We have other examples like `@storybook/test-runner` are handled the same way.

`@storybook/addon-styling` will accept any minor or patch version of `@storybook/types` as long as it's at least 7.0.12. This is something that you can fix in your lockfile by running `yarn dedupe`. You could also delete and rebuild your lockfile instead.

**Comment by Integrayshaun** [comment]
Fantastic! Have a wonderful week 👋
