### ISSUE TITLE
[Bug]: Nuxt storybook page isn't loading: This site can’t be reached (localhost and 'On your network')

### ISSUE THREAD

**Issue by IlyaKorn** [storybookjs/storybook#23756]
### Describe the bug

Hello!
I have a problem.
I use storybook in Nuxt 2.
Storybook successful running and generate 2 links:
  1) localhost
  2) On your network
  But both links are not working, page is not loading and give error: This site can’t be reached (connection timeout).
  My colleague hasn't got this problem (always we use the second link)

My attempts: 
 1) deleted node_modules and package-lock.json - not working
 2) run without cache (--no-manager-cache) - now working
 3) checked port, port is available.
 I don't know what is the problem, I haven't got this problem in my old computer (Ubuntu)
 When I forked a project on my Macbook - this problem is appeared.
 FYI: we use docker and we have nuxt container, where I run storybook.
 
    "@nuxtjs/storybook": "^4.3.2",
    "@storybook/addon-essentials": "^6.5.9",
    "@storybook/addon-links": "^6.5.9",
    "storybook-addon-designs": "^6.3.1",

### System

```shell
Environment Info:

  System:
    OS: Linux 5.15 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (4) arm64 unknown
  Binaries:
    Node: 16.15.0 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.5.5 - /usr/local/bin/npm
  npmPackages:
    @storybook/addon-essentials: ^6.5.9 => 6.5.9 
    @storybook/addon-links: ^6.5.9 => 6.5.9
```

**Comment by vanessayuenn** [comment]
Are you able to upgrade to the latest version of Storybook? If this issue indeed persists in storybook 7.x, please provide a reproduction so we can look into this properly. Thank you!
