### ISSUE TITLE
[Bug]: Storyshots in html project + issues with STORYBOOK_ENV

### ISSUE THREAD

**Issue by adchsm** [storybookjs/storybook#23752]
### Describe the bug

Referencing: #19175. 

Framework: html-vite
```
// storybook.test.ts
import initStoryshots from '@storybook/addon-storyshots';
initStoryshots();
```
Produces error:
```
Test suite failed to run

    Couldn't find an appropriate framework loader -- do you need to set the `framework` option?

      1 | import initStoryshots from '@storybook/addon-storyshots';
      2 |
    > 3 | initStoryshots();
```
Adding framework:
```
// storybook.test.ts
import initStoryshots from '@storybook/addon-storyshots';
initStoryshots({framework: 'html'});
```
Produces error:
```
Test suite failed to run

    TypeError: Cannot set properties of undefined (setting 'STORYBOOK_ENV')

      1 | import initStoryshots from '@storybook/addon-storyshots';
    > 2 | initStoryshots({ framework: 'html' });
```

**Comment by dbismut** [comment]
I've tried using @swc/jest with vite/vue3, and I got the same error. After console logging where I could, it seems that the error is generated at this line, which makes the error message a bit confusing:

https://github.com/storybookjs/storybook/blob/3a26f151b53a1e95e52b8574906777669b323234/code/addons/storyshots-core/src/frameworks/vue3/loader.ts#L38

Hope this helps.

**Comment by loganzartman** [comment]
For me, this error was resolved by setting `testEnvironment: 'jsdom'` in my jest.config.ts file. I also needed to install the jsdom environment.

The error comes from here: https://github.com/storybookjs/storybook/blob/d0dcf7d9182b5c4378bf5e0e83d8335883d423b9/code/renderers/html/src/globals.ts#L5

which is a good clue: `window` is undefined if you're using, for example, the `node` environment instead.

This is actually [mentioned in the docs](https://storybook.js.org/addons/@storybook/addon-storyshots#:~:text=you%20are%20using-,jsdom,-as%20the%20testEnvironment); it might be useful to include the text of this error there.

**Comment by jonniebigodes** [comment]
The Storyshots addon is officially deprecated and will be removed in a future release of Storybook. To help with the transition process, we've created a [migration guide](https://storybook.js.org/docs/writing-tests/storyshots-migration-guide) for the available options and common use cases.
