### ISSUE TITLE
[Bug]: Addon-docs always show "no code available" if story has no args

### ISSUE THREAD

**Issue by felipevisu** [storybookjs/storybook#23768]
### Describe the bug

When rendering the Story without passing args is not possible to see the code.

```mdx
import { Canvas, Meta, Story } from '@storybook/addon-docs';
import { Button } from './Button';

<Meta title="MDX/Button" component={Button} />

<Canvas>
  <Story name="Default">
    <Button>test</Button>
  </Story>
</Canvas>
```

![Screenshot from 2023-08-09 09-13-55](https://github.com/storybookjs/storybook/assets/9272668/bce4cd07-676d-4015-888e-e3b5221d6088)

But when rendering the story passing args in a arrow function the `Show code` button works normally.

```mdx
import { Canvas, Meta, Story } from '@storybook/addon-docs';
import { Button } from './Button';

<Meta title="MDX/Button" component={Button} />

<Canvas>
  <Story name="Default">
    {({args}) => <Button>teste</Button>}
  </Story>
</Canvas>
```

![Screenshot from 2023-08-09 09-27-53](https://github.com/storybookjs/storybook/assets/9272668/b1f63a3f-0623-4f97-ad6c-7e1da43a832a)

Is there some configuration to always show the button enabled?

### System

```shell
Environment Info:

  System:
    OS: Linux 5.19 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i7-1255U
  Binaries:
    Node: 18.17.0 - ~/.nvm/versions/node/v18.17.0/bin/node
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.0/bin/npm
  Browsers:
    Chrome: 114.0.5735.198
  npmPackages:
    @storybook/addon-essentials: ^7.2.1 => 7.2.1 
    @storybook/addon-interactions: ^7.2.1 => 7.2.1 
    @storybook/addon-links: ^7.2.1 => 7.2.1 
    @storybook/addon-onboarding: ^1.0.8 => 1.0.8 
    @storybook/blocks: ^7.2.1 => 7.2.1 
    @storybook/react: ^7.2.1 => 7.2.1 
    @storybook/react-webpack5: ^7.2.1 => 7.2.1 
    @storybook/testing-library: ^0.2.0 => 0.2.0
```

**Comment by hieucd04** [comment]
This bug can also be reproduced using [CSF](https://storybook.js.org/docs/react/api/csf):

```typescript
// This example code is taken from the "CSF" link above
export const WithProp: Story = {
  render: (_args) => ( // "_args" is not used for anything but if we omit it, we got "no code available" bug
    <MyComponent prop="value" />
  )
};
```

**Comment by shilman** [comment]
I tried reproducing in one of our sandbox projects and could not reproduce.

Does anyone have a reproduction repo they can share? If not, can you create one? Go to https://storybook.new or see [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce). Thank you! 🙏
