### ISSUE TITLE
[Bug]: 'next/link'

### ISSUE THREAD

**Issue by pedrojussi** [storybookjs/storybook#23774]
### Describe the bug

ModuleNotFoundError: Module not found: Error: Can't resolve 'next/link' in ...

error starting storybook.

### System

```shell
storybook@7.2.2
```

**Comment by vanessayuenn** [comment]
Hi, thanks for reporting this. do you have a reproduction repo you can share? If not, can you create one (see [how to create a repro](https://storybook.js.org/docs/react/contribute/how-to-reproduce)). We prioritize bug reports that have reproduction. Thank you! 🙏
