### ISSUE TITLE
[Bug]: Within shadow tree, shortcuts are not appropriately ignored

### ISSUE THREAD

**Issue by stropitek** [storybookjs/storybook#23790]
### Describe the bug

When a shadow dom is rendered within a story, keyboard actions are triggered even while a input, textarea, or contenteditable element is focused.

### To Reproduce

https://stackblitz.com/edit/stackblitz-starters-cxrkde?file=src%2Fstories%2Finput.shadow-dom.stories.tsx

### System

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 16.20.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
  npmPackages:
    @storybook/addon-essentials: ^7.2.2 => 7.2.2 
    @storybook/addon-links: ^7.2.2 => 7.2.2 
    @storybook/blocks: ^7.2.2 => 7.2.2 
    @storybook/react: ^7.2.2 => 7.2.2 
    @storybook/react-vite: ^7.2.2 => 7.2.2 
    @storybook/testing-library: ^0.2.0 => 0.2.0
```

### Additional context

I think the problem can be solved by using [`event.composedPath()`](https://developer.mozilla.org/en-US/docs/Web/API/Event/composedPath) instead of `event.target`.

https://github.com/storybookjs/storybook/blob/354d1baac8c10c9646b6dceff5dd93a52f06ec67/code/lib/preview-api/src/modules/preview-web/PreviewWithSelection.tsx#L47C1-L50

The reproduction shows the problem in an input, but same problem is expected on a textarea or `contenteditable` element.

**Comment by vanessayuenn** [comment]
@stropitek thanks for raising this issue. Would you be interested in contributing a fix, since you seem to have a solution in mind already? 😄

**Comment by vanessayuenn** [comment]
@stropitek thank you for helping out! Be sure to check the [contribution guide](https://storybook.js.org/docs/react/contribute/how-to-contribute) and hop onto the [Storybook Discord](https://discord.gg/storybook) if you need any help getting started. Looking forward to your contribution! ✨
