### ISSUE TITLE
[Bug]: Error: <svg> attribute width: Expected length, "inherit".

### ISSUE THREAD

**Issue by dylannnn** [storybookjs/storybook#23815]
### Describe the bug

Since recent update of the storybook to v7.2.3 from v7.1.x, when there is a Controls tab been attached to a story, there is the error in the console:  `Error: <svg> attribute width: Expected length, "inherit".      chunk-SJD7EFYL.js:2 Error: <svg> attribute width: Expected length, "inherit".`

After the investigation, I have found out that when the first time open this storybook, it show the "Interactive story playground
Controls give you an easy to use interface to test your components. Set your story args and you'll see controls appearing here automatically.", which has introduced few svg image, with width and height as inherit value that cause this issue.

See the screenshot here:
<img width="1115" alt="Screenshot 2023-08-11 at 23 17 57" src="https://github.com/storybookjs/storybook/assets/6026590/1b5b0760-da74-4176-b33d-c72b7d992c28">

Error:
<img width="591" alt="Screenshot 2023-08-11 at 23 46 15" src="https://github.com/storybookjs/storybook/assets/6026590/f1522b62-f549-4e9e-8ef3-c02ddb99ff92">

Clear cookie if needed if you want to check multiple times.

### To Reproduce

https://githubc38259-4aaj--6006--d5d65229.local-credentialless.webcontainer.io/

### System

```shell
Environment Info:

  System:
    OS: macOS 13.4.1
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 18.16.1 - ~/.nvm/versions/node/v18.16.1/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 9.8.1
  Browsers:
    Chrome: 115.0.5790.170
    Safari: 16.5.2
  npmPackages:
    @storybook/addon-a11y: 7.2.3 => 7.2.3 
    @storybook/addon-actions: 7.2.3 => 7.2.3 
    @storybook/addon-docs: 7.2.3 => 7.2.3 
    @storybook/addon-essentials: 7.2.3 => 7.2.3 
    @storybook/addon-interactions: 7.2.3 => 7.2.3 
    @storybook/addon-links: 7.2.3 => 7.2.3 
    @storybook/addon-mdx-gfm: 7.2.3 => 7.2.3 
    @storybook/angular: 7.2.3 => 7.2.3 
    @storybook/cli: ^7.2.3 => 7.2.3 
    @storybook/core-common: 7.2.3 => 7.2.3 
    @storybook/core-server: 7.2.3 => 7.2.3 
    @storybook/test-runner: 0.11.0 => 0.11.0 
    @storybook/theming: 7.2.3 => 7.2.3
```

**Comment by yasuaki640** [comment]
For storybook version 7.3.0-alpha.0, this issue appears to have already been fixed.

<img width="1469" alt="image" src="https://github.com/storybookjs/storybook/assets/42242014/c5f9bb21-18e2-40c0-b495-9c1bbf657404">

![image](https://github.com/storybookjs/storybook/assets/42242014/a1e7df3b-c3ce-4d3e-b94f-d67c97a3f8ab)

**Comment by fabiradi** [comment]
This appears to exist on many SVG components, also `Icon.ChevronRight` (https://github.com/storybookjs/storybook/blob/3dfc4173f50fff57ab5de688884da0c409f72c88/code/ui/components/src/new/Link/Link.tsx#L33C24-L33C41)

This seems to show some more occurences: https://github.com/search?q=repo%3Astorybookjs%2Fstorybook+svg+width+inherit+&type=code
