### ISSUE TITLE
[Bug]: TypeError: Invalid version. Must be a string. Got type "undefined".

### ISSUE THREAD

**Issue by GuYun-D** [storybookjs/storybook#23823]
### Describe the bug

When I initialize storybook in a React project，it always tells me that obtaining the version number is undefined

### System

```shell
Environment Info:

  System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
  Binaries:
    Node: 16.18.0 - D:\software\nvm\node.EXE
    Yarn: 1.22.19 - D:\software\nvm\yarn.CMD
    npm: 8.19.2 - D:\software\nvm\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (115.0.1901.203)
```

### Additional context

{
  "name": "demo",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@fortawesome/fontawesome-svg-core": "^6.4.2",
    "@fortawesome/free-solid-svg-icons": "^6.4.2",
    "@fortawesome/react-fontawesome": "^0.2.0",
    "@testing-library/jest-dom": "^5.17.0",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "@types/jest": "^27.5.2",
    "@types/node": "^16.18.40",
    "@types/react": "^18.2.20",
    "@types/react-dom": "^18.2.7",
    "@types/react-transition-group": "^4.4.6",
    "classnames": "^2.3.2",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-scripts": "5.0.1",
    "react-transition-group": "^4.4.5",
    "typescript": "^4.9.5",
    "web-vitals": "^2.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "@babel/preset-typescript": "^7.22.5",
    "sass": "^1.65.1"
  }
}

**Comment by vanessayuenn** [comment]
Hi, thanks for reporting this. do you have a reproduction repo you can share? If not, can you create one (see [how to create a repro](https://storybook.js.org/docs/react/contribute/how-to-reproduce)). We prioritize bug reports that have reproduction. Thank you! 🙏

**Comment by leon846666** [comment]
I met the same problem , my project was init by create-react-app template typescript. 

    "typescript": "^4.9.5",
    "@storybook/react": "^7.3.0",

**Comment by leon846666** [comment]
solved the issue by downgrading to 7.1.0

**Comment by yannbf** [comment]
Hey @leon846666 @GuYun-D I'd really love to see how to reproduce this issue, please share more info if you can.
@GuYun-D I tried your exact package.json and storybook init ran successfully :/

**Comment by Absleepy** [comment]
Try restarting your mongo compass. And reconnect. It will fix the error.
