### ISSUE TITLE
[Bug]: Angular Source Maps Are Not True Source Maps - Throws Off Coverage Reports

### ISSUE THREAD

**Issue by tommyc38** [storybookjs/storybook#23832]
### Describe the bug

I am essentially getting compiled sources for source maps and when I instrument my code it throws thing off because the line numbers are off.  I need true source maps so instrumentation works properly.

### To Reproduce

If the repro provided in #21171 is too old I am happy to provide a repro with the latest versions of storybook, angular, etc.

### Additional context

[This bug](https://github.com/storybookjs/storybook/issues/21171) was previously closed because it is stale so I am reopening it here.

**Comment by tommyc38** [comment]
I found a workaround but I am not sure where the override options are getting set at (e.g. AngularWebpackPlugin has an plugin option, `compilerOptions`, that override tsconfig.json file configurations and something is setting `sourceMap = false` in there).  

```
//libs/mylib/.storybook/main.js
...
webpackFinal: async (config, { configType }) => {
    if (rootMain.webpackFinal) {
      config = await rootMain.webpackFinal(config, { configType });
    }

    // add your own webpack tweaks if needed
    if (configType !== 'PRODUCTION') {
      config.devtool = 'eval-cheap-module-source-map';
      config.plugins = config.plugins.map(plugin => {
        if(plugin.constructor.name === 'AngularWebpackPlugin'){
          plugin.pluginOptions.compilerOptions.sourceMap = true
        }
        return plugin
      })
      return merge(config, {
        module: {
          rules: [
            {
              test: /\.(js|ts)$/,
              loader: 'coverage-istanbul-loader',
              options: { esModules: true, produceSourceMap: true },
              enforce: 'post',
              include: require('path').join(__dirname, '../..'),
              exclude: [
                /\.(e2e|spec|stories|config|setup)\.ts$/,
                /node_modules/,
                /.storybook/,
                /(ngfactory|ngstyle)\.js/,
              ],
            },
          ],
        },
      });
    }
    return config;
  }
```

**Comment by tommyc38** [comment]
Looks like it's getting set [here](https://github.com/angular/angular-cli/blob/c3c4853d4d908025e2f9f0d32419f11459021bff/packages/angular_devkit/build_angular/src/tools/webpack/plugins/typescript.ts#L22C45-L22C45) with the ivyPlugin.  I opened an issue in the angular-cli repo to see if this is a bug or perhaps storybook needs to tweak their angular webpack presets to make it easier to get true coverage. I will close this issue once I get more feedback from the angular team and it turns out storybook needs to make an adjustment.  Hopefully this helps.

**Comment by manuelwaltschek** [comment]
Sorry if this is a dumb question. I'm an amateur when it comes to bundlers / webpack etc.
I stumbled across this issue because I'm trying to debug my angular components with storybook and cannot set the breakpoints in vs code and the source in the browser seems compiled. I think this is related to your issue, isn't it?

**Comment by tommyc38** [comment]
@manuelwaltschek yes, that will jackup your breakpoints.  Look at the webpackFinal function in my storybook config above.  Make sure you add `config.devtool = 'eval-cheap-module-source-map';` (see more options [here](https://webpack.js.org/configuration/devtool/)) and that your tsconfig also has `sourceMap: true`.  It's likely one of the plugins has sourceMap set to false.  Console.log the webpack config and see if you can find a plugin that is explicitly setting sourceMap to false.  Moreover, if you are using typescript then focus on plugins related to that.  Hope this helps.

**Comment by tommyc38** [comment]
I heard back from the angular team in [this issue](https://github.com/angular/angular-cli/issues/25691).  Could you please expose a sourceMap configuration in the storybook executors so we don't have to manually update the webpack config ourselves OR look at the source map settings in the supplied tsconfig and pass that off to the angular builder?  Let me know if you want me to close this and open a feature request, thanks.

**Comment by manuelwaltschek** [comment]
@tommyc38 sadly it doesn't help.
Neither setting 'eval-cheap-module-source-map' nor 'source-map' in the webpackFinal in main.ts
I have different tsconfigs inherited and setting sourceMap to true in all of them does not make a difference.

**Comment by tommyc38** [comment]
@manuelwaltschek You need to set the `AngularWebpackPlugin` source map options to `true`.  See my webpack config above.  Once you do that, along with the other setting, you shouldn't see any compiled code in your source map configs.

**Comment by manuelwaltschek** [comment]
The problem is that I can't do that as I get the following compiler error:
`Property 'pluginOptions' does not exist on type '((this: Compiler, compiler: Compiler) => void)`
on 
` plugin.pluginOptions.compilerOptions.sourceMap = true;`
