### ISSUE TITLE
[Documentation]: Storybook docs v7.2 is lost

### ISSUE THREAD

**Issue by denisbalyko** [storybookjs/storybook#23858]
### Describe the problem

Now, if you want to find `storybook`, your found version 7.2:
https://www.google.com/search?q=viewport+custom+storybook

Or if you want to change to 7.2 from https://storybook.js.org/docs/7.0/react/get-started/why-storybook

I think it's better to keep old links than to lead to 404

Please, roll out version 7.2, it will cause less inconvenience :)

**Comment by jonniebigodes** [comment]
@denisbalyko, thanks for reaching out to us. We're aware of this, and the documentation should be published shortly if already isn't. During the process, we've uncovered yet another unrelated issue, and we're already working on fixing it.

Hope you don't take it the wrong way, but I'm closing this for now. Feel free to follow up with me with any additional feedback, and I'll be more than glad to re-open it.

Hope you have a great day.

Stay safe
