### ISSUE TITLE
[Bug]: Storybook 7: excludeStories entry in docs MDX file throws error

### ISSUE THREAD

**Issue by josephmarkus** [storybookjs/storybook#23861]
### Describe the bug

I have a `<Button>` component for which I have created `Button.stories.ts`.

An entry inside `Button.stories.ts` is called `BrokenStory`.

I don't want this story to appear in the sidebar, so I add it to `Button.stories.ts` default export containing configuration - `excludeStories: ["BrokenStory"],`.

However, I want this example to surface on `<Canvas>` in my docs file as `<Canvas of={ButtonStories.BrokenStory} />`, however I get an error:

```
Invalid value passed to the 'of' prop. The value was resolved to a 'component or unknown' type but the only types for this block are: story.
```

Previously, I would use `<Canvas>` like so:

```
<Canvas>
  ... my code example here...
</Canvas>
```

But since Storybook 7 I need to reference `<Canvas of={ButtonStories.BrokenStory} />`

Moving `BrokenStory` into `Button.stories.ts` means it automatically renders in the sidebar, which is undesirable

### To Reproduce

https://stackblitz.com/edit/github-oxjaxt?file=stories%2FButton.stories.ts,stories%2FButton.mdx

Differences from autogenerated defaults:

New file: Button.mdx
Modifications: Button.stories.ts has `excludeStories` in `meta` and `tags: ['autodocs']` commented out

### Additional context

The workaround I found that works is to render `BrokenStory` like so in MDX:

`<ButtonStories.BrokenStory />`

and not as

`<Canvas of={ButtonStories.BrokenStory} />`

this way autodocs still generate entry for `BrokenStory`, but it can be excluded in `Button.stories.ts` via `excludeStories: ["BrokenStory"]`. This way it doesn't break. The downside is that the component doesn't render on a `<Canvas>`

**Comment by shilman** [comment]
@josephmarkus the function of `excludeStories` is to not treat certain named exports as stories at all, not to remove them from the sidebar, hence the behavior you're seeing. We'll be adding a feature to allow you to filter stories from the sidebar, so I've added this issue to that project. In the meantime, you'll need that story in your sidebar if you want to use it in docs.

**Comment by josephmarkus** [comment]
Thanks for getting back to me @shilman. Perhaps the intention of the feature could be clarified in documentation. Before migrating to v7 I had docs containing example use cases to make it easier for someone to copy/paste a code snippet. This was alongside code examples which were included in the sidebar.

Example sidebar:

1. `<Button>`
1.1 primary
1.2  secondary

And the docs would have examples on how to style `<Button>` with CSS modules or CSS-in-JS. This use case necessitated exclusion of the latter stories after migrating to v7, which would pick up on all named exports.

**Comment by shilman** [comment]
Yeah, we really need to add the filtering feature. Hopefully in q4!

**Comment by vanessayuenn** [comment]
Tags has been shipped in v8! You can now use it to hide stories from the sidebar:
```js
export const HiddenStory: Story = {
  // 👇 This story will not appear in Storybook's sidebar
  tags: ['!dev'],
  ...,
};
```
See more ways to use tags in our [docs](https://storybook.js.org/docs/writing-stories/tags).
