### ISSUE TITLE
[Bug]: tailwindcss dosen't work on storybook

### ISSUE THREAD

**Issue by MarinosTBH** [storybookjs/storybook#23890]
### Describe the bug
the problem is acron and acron-jsx not found

Nextjs tailwindcss and storybook.
Using storybook dosen't apply the css used in my nextjs components 
So i tried to use documentation for handling tailwindcss in storybook but didn't work.

**Comment by MarinosTBH** [comment]
So i did :
npm i -D @storybook/addon-styling
npm i acorn acorn-jsx
import the global.css file of your tailwind config in .storybook/preview.js => import "../assets/styles/globals.css"
Restart storybook
and it worked

**Comment by valentinpalkovic** [comment]
Hey @Integrayshaun,

Is it necessary to install `acorn` and `acorn-jsx` manually?

**Comment by Integrayshaun** [comment]
@MarinosTBH 

The NextJS framework for storybook should already configure PostCSS in webpack for you which means `@storybook/addon-styling` should not be used. Plus, it's now deprecated.

If you remove it from your config and dependencies, including acorn and acorn-jsx, your Storybook should work as expected.

@valentinpalkovic I've never come across this before... I just it's a sub-dep of recast?

**Comment by MarinosTBH** [comment]
True nextjs did it itself, it now works

**Comment by Integrayshaun** [comment]
Right on! I'm glad you were able to get it running.

**Comment by r34son** [comment]
Found workaround (in .storybook/main.ts)

```js
webpackFinal: async (config) => {
    if (config.module) {
      config.module.rules = config.module.rules?.map((rule) => {
        if (
          rule &&
          typeof rule !== 'string' &&
          rule.test instanceof RegExp &&
          rule.test.test('test.css')
        ) {
          return { ...rule, sideEffects: true };
        }
        return rule;
      });
    }
    return config;
  },
```

The issue was that webpack was threeshaking css import. Setting `sideEffects: true` solves issue.

**Comment by r34son** [comment]
Or even simpler. If you have `"sideEffects": false` in your `package.json` - just change it to `"sideEffects": ["*.css"]`.
