### ISSUE TITLE
[Bug]: Warning: Unknown: `key` is not a prop

### ISSUE THREAD

**Issue by n19htz** [storybookjs/storybook#23903]
### Describe the bug

Error happens on the tab of "Tests" added by @storybook/addon-jest

<img width="912" alt="Screenshot 2023-08-21 at 13 40 01" src="https://github.com/storybookjs/storybook/assets/39006390/bfce090d-3760-4842-b4da-be684ad821f2">

https://github.com/storybookjs/storybook/assets/39006390/6e93b930-199b-4e78-b0f6-277ad59b5d03

Related: https://github.com/storybookjs/storybook/issues/23782

### To Reproduce

1. Create a new Storybook project
2. Install and setup @storybook/addon-jest 
3. Create story with tests following @storybook/addon-jest readme
4. Run storybook and click on tab "Tests "

### System

```shell
Environment Info:

  System:
    OS: macOS 13.5.1
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 20.5.1 - ~/Library/Caches/fnm_multishells/32486_1692610196765/bin/node
    npm: 9.8.0 - ~/Library/Caches/fnm_multishells/32486_1692610196765/bin/npm
  Browsers:
    Chrome: 115.0.5790.170
    Safari: 16.6
  npmPackages:
    @storybook/addon-backgrounds: 7.3.2 => 7.3.2 
    @storybook/addon-controls: 7.3.2 => 7.3.2 
    @storybook/addon-jest: 7.3.2 => 7.3.2 
    @storybook/addon-toolbars: 7.3.2 => 7.3.2 
    @storybook/addon-viewport: 7.3.2 => 7.3.2 
    @storybook/angular: 7.3.2 => 7.3.2 
    @storybook/core-common: 7.3.2 => 7.3.2 
    @storybook/core-server: 7.3.2 => 7.3.2 
    @storybook/jest: 0.2.1 => 0.2.1 
    @storybook/test-runner: 0.13.0 => 0.13.0 
    @storybook/testing-library: 0.2.0 => 0.2.0
```

**Comment by Romainpetit** [comment]
Related: https://github.com/storybookjs/storybook/issues/23782

Replacing `storybook-addon-designs` for `@storybook/addon-designs` solved the issue for me.

**Comment by n19htz** [comment]
> Related: #23782
> 
> Replacing `storybook-addon-designs` for `@storybook/addon-designs` solved the issue for me.

In my case it has nothing to do with "addon-designs", since I don't use it

**Comment by Hamza-Rafique** [comment]
facing the same warnings.

**Comment by ndelangen** [comment]
That should have been fixed in this PR:
https://github.com/storybookjs/addon-designs/pull/207

https://github.com/storybookjs/addon-designs
