### ISSUE TITLE
[Bug]: screen-reader-addon is not displaying on migrating from Storybook 6.3.2 to 7.3.2

### ISSUE THREAD

**Issue by umangJain22** [storybookjs/storybook#23927]
### Describe the bug

I am currently on Storybook version 6.3.2.
I am getting Controls and Actions in my docs section,
![image](https://github.com/storybookjs/storybook/assets/46552435/eb8ae6c6-a823-4c51-b18a-578dd631ee9f)

I am upgrading my storybook to version 7.3.2, it's not showing the Screen-reader anymore.
It's throwing the below console error:
![image](https://github.com/storybookjs/storybook/assets/46552435/34d43a3c-c5d5-42f5-b941-0f0434c57a3c)

I am using version 1.8.6 for addon-screen-reader

**Comment by umangJain22** [comment]
There is also an issue raised in the addon repository already:https://github.com/vlaraort/addon-screen-reader/issues/29

**Comment by vanessayuenn** [comment]
Hi @umangJain22 thanks for raising this. Unfortunately this is an issue with an external addon not being compatible with Storybook 7.0+. I will be closing this issue here for now, and hopefully the addon author will soon make the necessary upgrade to be compatible with 7.0+.
