### ISSUE TITLE
[Bug]: Angular Decorator standalone

### ISSUE THREAD

**Issue by walkadaw** [storybookjs/storybook#23937]
### Describe the bug

```
export default {
  title: 'Components/Tooltip',
  component: KTooltipDirective, // standalone directive
}
```
`
Error: Unexpected "KTooltipDirective" found in the "declarations" array of the "StorybookComponentModule" NgModule, "KTooltipDirective" is marked as standalone and can't be declared in any NgModule - did you intend to import it instead (by adding it to the "imports" array)?
`

https://github.com/storybookjs/storybook/blob/9bdffe1d6555efcd33bc6633d417d55cd4002e63/code/frameworks/angular/src/client/angular-beta/utils/PropertyExtractor.ts#L168-L180

it looks like we should allow standalone directive
```
const isStandalone = (isComponent || isDirective) && decorators.some((d) => d.standalone);
```
---------

it is work but I lose all control information
```
export default {
  title: 'Components/Tooltip',
  decorators: [
    moduleMetadata({
      imports: [KTooltipDirective],
    }),
  ],
  ```
--------

The main problem is that we want to receive data for controls from directives, but if we do not specify them in the component, then we do not receive them.

### To Reproduce

https://stackblitz.com/edit/github-mz24pf?file=src%2Fstories%2Fissue.stories.ts,package.json&preset=node

### System

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (4) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.19.3 - C:\git\jb-design-system\node_modules\.bin\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.2134.0), Chromium (116.0.1938.54)
  npmPackages:
    @storybook/addon-actions: ^7.3.2 => 7.3.2
    @storybook/addon-essentials: ^7.3.2 => 7.3.2
    @storybook/addon-interactions: ^7.3.2 => 7.3.2
    @storybook/addon-links: ^7.3.2 => 7.3.2
    @storybook/addon-mdx-gfm: ^7.3.2 => 7.3.2
    @storybook/angular: ^7.3.2 => 7.3.2
    @storybook/testing-library: ^0.2.0 => 0.2.0
    @storybook/theming: ^7.3.2 => 7.3.2
```

**Comment by osnoser1** [comment]
I have the same problem

**Comment by osnoser1** [comment]
I sent a PR with the suggested changes by @walkadaw
