### ISSUE TITLE
[Bug]: TypeScript Monorepo Load Chunk failed missing file but it exists

### ISSUE THREAD

**Issue by smol-honk** [storybookjs/storybook#23933]
### Describe the bug

I have a monorepo with NextJS as consuming apps and a regular ui package library that uses storybook. 

I am able to run storybook on v7.3.2 with react v17 and react-webpack5. The reason I didn't go with NextJS (@storybook/nextjs) is because we don't actually run next in the component library package, and I don't want to have it depend on next if we don't use it. Instead I'm using react-webpack5 to build it.

A good majority of the stories are built correctly, but I get this error:
```
Loading chunk src_AlertModal_AlertModal_tsx failed.  (missing: http://localhost:6006/src_AlertModal_AlertModal_tsx.iframe.bundle.js)
```

The file structure I have is:
```
AlertModal/
        |--- AlertModal.tsx
        |--- AlertModal.stories.tsx
        |--- index.ts
```

The weird thing is that it's not all stories, only some that have that Loading chunk failed.

And when I go to that url `(missing: http://localhost:6006/src_AlertModal_AlertModal_tsx.iframe.bundle.js)` it exists? 

I'm thinking it's something with the naming convention of webpack optimization but my debugging fails after that.

### To Reproduce

Not sure how to reproduce without creating a huge monorepo. 

### System

```shell
Environment Info:

  System:
    OS: macOS 13.4.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    Yarn: 3.6.2 - ~/.nvm/versions/node/v16.19.0/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
  Browsers:
    Chrome: 116.0.5845.96
    Safari: 16.5.2
```

### Additional context

I'm using yarn workspaces and yarn v3.6.2. No lerna or nx. Also using stitches as my styling library.

**Comment by smol-honk** [comment]
Interesting note:
Found that if we export from a barrel file like so:
```
export {default} from './AlertModal'l
```

it'll cause the chunk error. But if we do a named export it works

**Comment by endreujhelyi** [comment]
I have the same issue, but it seems unrelated to how we export the components.

**Comment by kyle-kettler** [comment]
Running into the same issue. It was working fine when I first made the component and story, but then the error started without me making any changes to the file.

**Comment by aestradaes** [comment]
I ran into this problem as well. The problem seemed to be that the default export function was named `Default`. The file was also named `Default.tsx`. After I changed the function and file to something else I no longer got the error. 

@smol-honk 
> Interesting note: Found that if we export from a barrel file like so:
> 
> ```
> export {default} from './AlertModal';
> ```
> 
> it'll cause the chunk error. But if we do a named export it works

So it seems it has to do with the naming of our functions. Hope this helps someone.

**Comment by binaryartifex** [comment]
this issue is driving me insane. I have a forwardRef component, implemented the EXACT SAME WAY as every other component - everything else works fine. for some reason manually setting the displayName on the component works. just that one. no others. go figure. For context im also within a monorepo (NX)

```typescript
import { forwardRef } from "react";
import { useId } from "react-aria";
import { Switch as AriaSwitch } from "react-aria-components";
import { FieldDescription } from "../shared";
import { switchStyles } from "./switch.styles";
import type { SwitchProps } from "./switch.types";

export const Switch = forwardRef<HTMLLabelElement, SwitchProps>(function Switch(
  { children, description, ...props },
  ref,
) {
  const descriptionId = useId();
  const styles = switchStyles();

  return (
    <div>
      <AriaSwitch
        {...props}
        aria-describedby={description ? descriptionId : undefined}
        className={styles.base()}
        ref={ref}
      >
        <div className={styles.track()}>
          <div className={styles.thumb()} />
        </div>
        <span className={styles.label()}>{children}</span>
      </AriaSwitch>
      {description && (
        <FieldDescription disableSlots id={descriptionId}>
          {description}
        </FieldDescription>
      )}
    </div>
  );
});

Switch.displayName = "Switch"; // wont work without this

export default Switch;
```

i tracked the specific error to the following output. the line `switch.displayName = "switch";`  (the lowercase one in the second tryCatch) outputs an error which reads `Uncaught SyntaxError: Unexpected token '.'`

```bash
try {
    // @ts-ignore
    Switch.displayName = "Switch";
    // @ts-ignore
    Switch.__docgenInfo = { "description": "", "displayName": "Switch", "props": { "children": { "defaultValue": null, "description": "Rendered contents of the component.", "name": "children", "required": true, "type": { "name": "ReactNode" } }, "description": { "defaultValue": { value: "undefined" }, "description": "Brief supporting description of the field.", "name": "description", "required": false, "type": { "name": "string" } } } };
    // @ts-ignore
    if (typeof STORYBOOK_REACT_CLASSES !== "undefined")
        // @ts-ignore
        STORYBOOK_REACT_CLASSES["libs/web/common/ui-primitives/src/lib/components/inputs/switch/switch.tsx#Switch"] = { docgenInfo: Switch.__docgenInfo, name: "Switch", path: "libs/web/common/ui-primitives/src/lib/components/inputs/switch/switch.tsx#Switch" };
}
catch (__react_docgen_typescript_loader_error) { }
try {
    // @ts-ignore
    switch.displayName = "switch";
    // @ts-ignore
    switch.__docgenInfo = { "description": "", "displayName": "switch", "props": { "children": { "defaultValue": null, "description": "Rendered contents of the component.", "name": "children", "required": true, "type": { "name": "ReactNode" } }, "description": { "defaultValue": { value: "undefined" }, "description": "Brief supporting description of the field.", "name": "description", "required": false, "type": { "name": "string" } } } };
    // @ts-ignore
    if (typeof STORYBOOK_REACT_CLASSES !== "undefined")
        // @ts-ignore
        STORYBOOK_REACT_CLASSES["libs/web/common/ui-primitives/src/lib/components/inputs/switch/switch.tsx#switch"] = { docgenInfo: switch.__docgenInfo, name: "switch", path: "libs/web/common/ui-primitives/src/lib/components/inputs/switch/switch.tsx#switch" };
}
catch (__react_docgen_typescript_loader_error) { }
```
