### ISSUE TITLE
[Bug]: @storybook/nextjs: Module not found. Error: Can't resolve '@storybook/components/experimental'

### ISSUE THREAD

**Issue by melrose13-69** [storybookjs/storybook#23949]
### Describe the bug

After adding @storybook/nextjs framework

.storybook/main.ts

`import { StorybookConfig } from '@storybook/nextjs'`
`import { resolve } from 'node:path'`

`const config: StorybookConfig = {`
`    stories: [`
`        '../src/components/**/**/*.stories.@(ts|tsx)',`
`        '../src/components/**/**/*.mdx',`
`        '../src/modules/**/**/*.stories.@(ts|tsx)',`
`        '../src/modules/**/**/*.mdx'`
`    ],`
`    addons: [`
`        '@storybook/addon-essentials',`
`        '@storybook/addon-styling',`
`        '@storybook/addon-docs'`
`    ],`
`    framework: {`
`        name: '@storybook/nextjs',`
`        options: {`
`            nextConfigPath: resolve(__dirname, '../../next.config.js')`
`        }`
`    }`
`}`
`export default config`

 ERROR in ./node_modules/@storybook/blocks/dist/index.mjs 7:0-64
   Module not found: Error: Can't resolve '@storybook/components/experimental' in '/Users/poltoratchi/work/hdsk/helpdesk_project/frontend/node_modules/@storybook/blocks/dist'
   resolve '@storybook/components/experimental' in '/Users/poltoratchi/work/hdsk/helpdesk_project/frontend/node_modules/@storybook/blocks/dist'
     Parsed request is a module
     using description file: /Users/poltoratchi/work/hdsk/helpdesk_project/frontend/node_modules/@storybook/blocks/package.json (relative path: ./dist)
       aliased with mapping '@storybook/components': '/Users/poltoratchi/work/hdsk/helpdesk_project/frontend/node_modules/@storybook/builder-webpack5/node_modules/@storybook/components' to '/Users/poltoratchi/work/hdsk/helpdesk_project/frontend/node_modules/@storybook/builder-webpack5/node_modules/@storybook/components/experimental'
         using description file: /Users/poltoratchi/work/hdsk/helpdesk_project/frontend/node_modules/@storybook/blocks/package.json (relative path: ./dist)
           Field 'browser' doesn't contain a valid alias configuration
           root path /Users/poltoratchi/work/hdsk/helpdesk_project/frontend
             using description file: /Users/poltoratchi/work/hdsk/helpdesk_project/frontend/package.json (relative path: ./Users/poltoratchi/work/hdsk/helpdesk_project/frontend/node_modules/@storybook/builder-webpack5/node_modules/@storybook/components/experimental)
               no extension
                 Field 'browser' doesn't contain a valid alias configuration
                 /Users/poltoratchi/work/hdsk/helpdesk_project/frontend/Users/poltoratchi/work/hdsk/helpdesk_project/frontend/node_modules/@storybook/builder-webpack5/node_modules/@storybook/components/experimental doesn't exist
               .mjs
                 Field 'browser' doesn't contain a valid alias configuration
                 /Users/poltoratchi/work/hdsk/helpdesk_project/frontend/Users/poltoratchi/work/hdsk/helpdesk_project/frontend/node_modules/@storybook/builder-webpack5/node_modules/@storybook/components/experimental.mjs doesn't exist
               .js
                 Field 'browser' doesn't contain a valid alias configuration
                 /Users/poltoratchi/work/hdsk/helpdesk_project/frontend/Users/poltoratchi/work/hdsk/helpdesk_project/frontend/node_modules/@storybook/builder-webpack5/node_modules/@storybook/components/experimental.js doesn't exist
               .jsx
                 Field 'browser' doesn't contain a valid alias configuration
                 /Users/poltoratchi/work/hdsk/helpdesk_project/frontend/Users/poltoratchi/work/hdsk/helpdesk_project/frontend/node_modules/@storybook/builder-webpack5/node_modules/@storybook/components/experimental.jsx doesn't exist
               .ts
                 Field 'browser' doesn't contain a valid alias configuration
                 /Users/poltoratchi/work/hdsk/helpdesk_project/frontend/Users/poltoratchi/work/hdsk/helpdesk_project/frontend/node_modules/@storybook/builder-webpack5/node_modules/@storybook/components/experimental.ts doesn't exist
               .tsx
                 Field 'browser' doesn't contain a valid alias configuration
                 /Users/poltoratchi/work/hdsk/helpdesk_project/frontend/Users/poltoratchi/work/hdsk/helpdesk_project/frontend/node_modules/@storybook/builder-webpack5/node_modules/@storybook/components/experimental.tsx doesn't exist
               .json
                 Field 'browser' doesn't contain a valid alias configuration
                 /Users/poltoratchi/work/hdsk/helpdesk_project/frontend/Users/poltoratchi/work/hdsk/helpdesk_project/frontend/node_modules/@storybook/builder-webpack5/node_modules/@storybook/components/experimental.json doesn't exist
               .cjs
                 Field 'browser' doesn't contain a valid alias configuration
                 /Users/poltoratchi/work/hdsk/helpdesk_project/frontend/Users/poltoratchi/work/hdsk/helpdesk_project/frontend/node_modules/@storybook/builder-webpack5/node_modules/@storybook/components/experimental.cjs doesn't exist
               as directory
                 /Users/poltoratchi/work/hdsk/helpdesk_project/frontend/Users/poltoratchi/work/hdsk/helpdesk_project/frontend/node_modules/@storybook/builder-webpack5/node_modules/@storybook/components/experimental doesn't exist
           using description file: /Users/poltoratchi/work/hdsk/helpdesk_project/frontend/node_modules/@storybook/builder-webpack5/node_modules/@storybook/components/package.json (relative path: ./experimental)
             no extension
               Field 'browser' doesn't contain a valid alias configuration
               /Users/poltoratchi/work/hdsk/helpdesk_project/frontend/node_modules/@storybook/builder-webpack5/node_modules/@storybook/components/experimental doesn't exist
             .mjs
               Field 'browser' doesn't contain a valid alias configuration
               /Users/poltoratchi/work/hdsk/helpdesk_project/frontend/node_modules/@storybook/builder-webpack5/node_modules/@storybook/components/experimental.mjs doesn't exist
             .js
               Field 'browser' doesn't contain a valid alias configuration
               /Users/poltoratchi/work/hdsk/helpdesk_project/frontend/node_modules/@storybook/builder-webpack5/node_modules/@storybook/components/experimental.js doesn't exist
             .jsx
               Field 'browser' doesn't contain a valid alias configuration
               /Users/poltoratchi/work/hdsk/helpdesk_project/frontend/node_modules/@storybook/builder-webpack5/node_modules/@storybook/components/experimental.jsx doesn't exist
             .ts
               Field 'browser' doesn't contain a valid alias configuration
               /Users/poltoratchi/work/hdsk/helpdesk_project/frontend/node_modules/@storybook/builder-webpack5/node_modules/@storybook/components/experimental.ts doesn't exist
             .tsx
               Field 'browser' doesn't contain a valid alias configuration
               /Users/poltoratchi/work/hdsk/helpdesk_project/frontend/node_modules/@storybook/builder-webpack5/node_modules/@storybook/components/experimental.tsx doesn't exist
             .json
               Field 'browser' doesn't contain a valid alias configuration
               /Users/poltoratchi/work/hdsk/helpdesk_project/frontend/node_modules/@storybook/builder-webpack5/node_modules/@storybook/components/experimental.json doesn't exist
             .cjs
               Field 'browser' doesn't contain a valid alias configuration
               /Users/poltoratchi/work/hdsk/helpdesk_project/frontend/node_modules/@storybook/builder-webpack5/node_modules/@storybook/components/experimental.cjs doesn't exist
             as directory
               /Users/poltoratchi/work/hdsk/helpdesk_project/frontend/node_modules/@storybook/builder-webpack5/node_modules/@storybook/components/experimental doesn't exist
    @ ./node_modules/@storybook/addon-docs/dist/chunk-S4VUQJ4A.mjs 3:0-81 5:28-43 5:46-55 5:59-69 5:542-546
    @ ./node_modules/@storybook/addon-docs/dist/DocsRenderer-3PUGWF3O.mjs 1:0-71 1:0-71 1:0-71
    @ ./node_modules/@storybook/addon-docs/dist/preview.mjs 1:65-102
    @ ./storybook-config-entry.js 10:1176-1293 36:2-39:4 36:1325-39:3

   preview (webpack 5.88.2) compiled with 1 error in 6770 ms

### To Reproduce

After run storybook dev server, server down with error

### System

node - v18.16.1
npm - 9.5.1
storybook -  ^7.0.23
@storybook/nextjs - ^7.0.23
nextjs - ^13.4.8

**Comment by ahernd2** [comment]
Seeing the same issue. Any fix?

**Comment by vanessayuenn** [comment]
@melrose13-69 @ahernd2 this should have been fixed in the latest release. Can you please try and report back? Thank you!

**Comment by vanessayuenn** [comment]
Amazing! Thanks for verifying.

**Comment by melrose13-69** [comment]
> 

Fixed, up all @storybook packages to latest versions
