### ISSUE TITLE
Storybook 7 compiles twice on launch (not sure if bug)

### ISSUE THREAD

**Issue by mlshohet** [storybookjs/storybook#23957]
### Describe the bug

When running in dev mode, Storybook builds twice on the very first build, otherwise behaves as expected.

Storybook is fired up programmatically using the build script from core, not the terminal.

This behavior seems to come from Webpack's watch mode. When watchOptions are turned off (with "ignore: *") this doesn't happen. Of course any further changes to the source code does not trigger any updates.

I checked if any actual files were being changed on the very first compilation by logging Webpack's compilation.modifiedFiles object in a watchRun hook. No files are changed.

Further investigation of Webpack's stats show that the HMR was indeed being triggered right after the very first build and some more assets were being emitted. You can see this in the screenshot:

<img width="1194" alt="Screenshot 2023-08-25 at 4 52 51 PM" src="https://github.com/storybookjs/storybook/assets/67978846/53172d5a-7ffd-4c2e-acc1-be2dfbe24771">

Stack:
Mac OS Ventura 13
Node 18.15.0
Storybook 7
VS Code

storybook/main.ts :
```
import type { StorybookConfig } from '@storybook/react-webpack5';

const config: StorybookConfig = {
	stories: [`${process.env.STORYBOOK_PATH}/**/*.stories.@(js|jsx|ts|tsx)`],
	addons: [
		'@storybook/addon-links',
		'@storybook/addon-essentials',
		'@storybook/addon-onboarding',
		'@storybook/addon-interactions',
	],
	framework: {
		name: '@storybook/react-webpack5',
		options: {},
	},
	docs: {
		autodocs: 'tag',
	},
	webpackFinal: async (config) => {
		config.module.rules.push(
			{
				test: /\.scss$/,
				use: ['style-loader', 'css-loader', 'sass-loader'],
				exclude: /node_modules/,
			},
			{
				test: /\.tsx?$/,
				use: 'ts-loader',
				exclude: /node_modules/,
			}
		);

		return config;
	},
};

export default config;
```

Another idea was that ts-loader was somehow triggering a rebuild with a type check. I passed transpileOnly option to this loader and it still rebuilt.

Very sorry, but no repro repo at this time.

It's kind of annoying, but no way a deal breaker. Love Storybook! Thanks for any help.

**Comment by nickbullock** [comment]
The same for me, angular16 + storybook7
