### ISSUE TITLE
Vite build issue

### ISSUE THREAD

**Issue by devbinyameen** [storybookjs/storybook#23962]
### Describe the bug

Vite is throwing error while building build using npm run generate and also while running locally using npm run dev

I am getting following error.

`Nuxt Build Error: The requested module 'vite' does not provide an export named 'isCSSRequest'`

### To Reproduce

Nuxt Build Error: The requested module 'vite' does not provide an export named 'isCSSRequest'

![image](https://github.com/storybookjs/storybook/assets/113900881/e8ec8994-b226-4327-9396-54c32845b454)

**Comment by vanessayuenn** [comment]
Hi, thanks for reporting this. do you have a reproduction repo you can share? If not, can you create one (see [how to create a repro](https://storybook.js.org/docs/react/contribute/how-to-reproduce)). We prioritize bug reports that have reproduction. Thank you! 🙏

**Comment by simonepozzobon-ciclope** [comment]
I have same issue.
I ran a clean install of vue project using:
- `yarn create vite vue --template vue`
- `npx storybook@latest init --builder @storybook/builder-vite`

and got
``` 
import { isCSSRequest, normalizePath as normalizePath$1, transformWithEsbuild, formatPostcssSourceMap, createFilter } from 'vite';
         ^^^^^^^^^^^^
SyntaxError: The requested module 'vite' does not provide an export named 'isCSSRequest'
