### ISSUE TITLE
[Bug]: Error: Unable to resolve module @storybook/core-events/preview-errors

### ISSUE THREAD

**Issue by Mazztwo** [storybookjs/storybook#23993]
### Describe the bug

Getting this error when trying to run storybook:

Error: Unable to resolve module @storybook/core-events/preview-errors

@storybook/core-events/preview-errors could not be found within the project or in these directories:
  node_modules/@storybook/preview-api/node_modules
  node_modules
  ../node_modules
  4 | Previous: ${hook.deps}

This was not happening a few days ago.

### To Reproduce

        "@storybook/addon-actions": "^7.4.0",
        "@storybook/addon-knobs": "^7.0.2",
        "@storybook/addon-links": "^7.4.0",
        "@storybook/addon-ondevice-actions": "^6.5.6",
        "@storybook/addon-ondevice-knobs": "^6.5.6",
        "@storybook/addons": "^7.4.0",
        "@storybook/api": "^7.4.0",
        "@storybook/core-events": "^7.4.0",
        "@storybook/preview-api": "^7.4.0",
        "@storybook/react-native": "^6.5.6",
        "react": "18.2.0",
        "react-native": "0.72.4",

**Comment by softwarespot** [comment]
I too am getting this issue. So has it been fixed?
