### ISSUE TITLE
[Bug]: No matching export in "global-externals:@storybook/channels" for import "createBrowserChannel"

### ISSUE THREAD

**Issue by dep** [storybookjs/storybook#23992]
### Describe the bug

I'm making the following dependency updates

```
-    "@storybook/addon-actions": "7.0.24",
+    "@storybook/addon-actions": "7.3.2",
-    "@storybook/addon-controls": "7.0.24",
+    "@storybook/addon-controls": "7.3.2",
-    "@storybook/addons": "7.0.24",
+    "@storybook/addons": "7.4.0",
-    "@storybook/theming": "7.0.24",
+    "@storybook/theming": "7.4.0",
```

and getting a failure on the `build-storybook` command:

```
Error: R] No matching export in "global-externals:@storybook/channels" for import "createBrowserChannel"
    ../../../../node_modules/@storybook/preview-api/dist/chunk-KAFJUYUA.mjs:5:9:
      5 │ import { createBrowserChannel } from '@storybook/channels';
        ╵          ~~~~~~~~~~~~~~~~~~~~
ERR! Error: Build failed with 1 error:
ERR! ../../../../node_modules/@storybook/preview-api/dist/chunk-KAFJUYUA.mjs:5:9: ERROR: No matching export in "global-externals:@storybook/channels" for import "createBrowserChannel"
```

Thanks for any help!

**Comment by spiess-demos** [comment]
Same error here after updating from `7.0.27`. Relevant devDependencies:

```
    "@storybook/addon-actions": "7.4.0",
    "@storybook/addon-docs": "7.4.0",
    "@storybook/addon-essentials": "7.4.0",
    "@storybook/addon-links": "7.4.0",
    "@storybook/addon-mdx-gfm": "7.4.0",
    "@storybook/addon-styling-webpack": "^0.0.2",
    "@storybook/vue": "7.4.0",
    "@storybook/vue-webpack5": "7.4.0",
```

**Comment by dbsmck** [comment]
Same for me:
```
    "@nx/storybook": "16.5.5",
    "@storybook/addon-essentials": "7.0.25",
    "@storybook/addon-interactions": "^7.0.25",
    "@storybook/addon-links": "^7.0.25",
    "@storybook/core-common": "^7.0.25",
    "@storybook/core-server": "7.0.25",
    "@storybook/preset-create-react-app": "^7.0.25",
    "@storybook/react-vite": "7.0.25",
```

**Comment by lovin123** [comment]
Facing same issue. Relevant devDependencies
"@storybook/addon-actions": "^7.0.27",
    "@storybook/addon-docs": "^7.0.27",
    "@storybook/addon-essentials": "^7.0.27",
    "@storybook/addon-interactions": "^7.0.27",
    "@storybook/addon-links": "^7.0.27",
    "@storybook/addon-mdx-gfm": "^7.0.27",
    "@storybook/addon-measure": "^7.0.27",
    "@storybook/addon-storysource": "^7.0.27",
    "@storybook/blocks": "7.0.27",
    "@storybook/cli": "^7.0.27",
    "@storybook/nextjs": "7.0.27",
    "@storybook/react": "^7.0.27",
    "@storybook/testing-library": "^0.2.0",

**Comment by dbsmck** [comment]
Upgrading everything to `7.4.0` fixed it for me

**Comment by ahmad-demos** [comment]
> Upgrading everything to `7.4.0` fixed it for me

it's working! Thnaks!

in `package.json`:
`"storybook": "7.4.0"`
then yarn install
then yarn storybook

**Comment by dep** [comment]
I have the same issue after upgrading to `7.4.0`

```
"@storybook/addon-actions": "7.4.0",
"@storybook/addon-controls": "7.4.0",
"@storybook/addon-docs": "7.4.0",
"@storybook/addon-knobs": "7.0.2",
"@storybook/addon-links": "7.4.0",
"@storybook/addons": "7.4.0",
"@storybook/channels": "7.4.0",
"@storybook/preset-scss": "1.0.3",
"@storybook/react": "7.4.0",
"@storybook/react-webpack5": "7.4.0",
"@storybook/theming": "7.4.0",
```

**Comment by spiess-demos** [comment]
@dep did you also update the `"storybook"` devDependency to the same version?

**Comment by yannbf** [comment]
Hey everyone! thanks for opening this issue. Can you provide a reproduction repo? I'd really like to get to the bottom of this issue and fix it.

Can you also check whether `npx storybook@latest automigrate` mentions any warnings like so in your project?

<img width="644" alt="image" src="https://github.com/storybookjs/storybook/assets/1671563/a4d2a802-f285-473d-9d0a-b295a2c6cdcd">

**Comment by amiramix** [comment]
> Hey everyone! thanks for opening this issue. Can you provide a reproduction repo? I'd really like to get to the bottom of this issue and fix it.
> 
> Can you also check whether `npx storybook@latest automigrate` mentions any warnings like so in your project?
> 
> <img alt="image" width="644" src="https://user-images.githubusercontent.com/1671563/266035930-a4d2a802-f285-473d-9d0a-b295a2c6cdcd.png">

In our case for some reason we had this dependency in the project:
"storybook": "future"

It was pulling @storybook/cli 7.1.0-alpha.29 instead of 7.4.6, like the rest of the project. This caused the 7.1.0-alpha.29 to be used to compile storybooks generated using the newer versions. And as a result we got this error:

```
@storybook/cli v7.1.0-alpha.29

info => Cleaning outputDir: /build
info => Loading presets
info => Building manager..
✘ [ERROR] No matching export in "global-externals:@storybook/channels" for import "createBrowserChannel"

    ../../node_modules/@storybook/preview-api/dist/chunk-KAFJUYUA.mjs:5:9:
      5 │ import { createBrowserChannel } from '@storybook/channels';
        ╵          ~~~~~~~~~~~~~~~~~~~~

```

All it took was to remove "storybook" dependency. I guess, like noted in other comments, the issue is caused by either compiling or recompiling storybook using incompatible versions.

**Comment by ivangabriele** [comment]
Hi ^^. Here is a reproduction PR: https://github.com/MTES-MCT/monitor-ui/pull/891.

Reproducable both via `yarn build:storybook` ([Github Action Run](https://github.com/MTES-MCT/monitor-ui/actions/runs/6879790947/job/18712521601?pr=891)) and Chromatic using `chromaui/action@v1` ([Github Actions Run](https://github.com/MTES-MCT/monitor-ui/actions/runs/6879791568/job/18712523373?pr=891)).
