### ISSUE TITLE
[Bug]: Control for ReactNode is rendered as an object

### ISSUE THREAD

**Issue by herzaso** [storybookjs/storybook#24005]
### Describe the bug

In a react component, I have a placeholder prop with type ReactNode.
In the Controls table, I see it as an object instead of a string or something that makes sense

<img width="1131" alt="Screenshot 2023-08-30 at 11 15 35" src="https://github.com/storybookjs/storybook/assets/3350658/94ba4207-3ea7-4fa9-8b02-423acc9e9ded">

In a different component, I also have ReactNode in a different prop and it shows as a string.

## EDIT:
In the base story for the component that doesn't work well, I actually set the placeholder (in args) as a JSX.
I noticed that if I remove that or set that prop as a string, then the control is shown well (as a string)

### System

```shell
Environment Info:

  System:
    OS: macOS 13.5.1
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 16.19.0 - /private/var/folders/gt/j1n_69cd58q4_8r6n5hpbpjr0000gq/T/xfs-8615acf5/node
    Yarn: 3.3.1 - /private/var/folders/gt/j1n_69cd58q4_8r6n5hpbpjr0000gq/T/xfs-8615acf5/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
  Browsers:
    Chrome: 116.0.5845.140
    Safari: 16.6
  npmPackages:
    @storybook/addon-a11y: 7.4.0 => 7.4.0
    @storybook/addon-essentials: 7.4.0 => 7.4.0
    @storybook/addon-interactions: 7.4.0 => 7.4.0
    @storybook/addon-links: 7.4.0 => 7.4.0
    @storybook/addons: 7.4.0 => 7.4.0
    @storybook/blocks: 7.4.0 => 7.4.0
    @storybook/react: 7.4.0 => 7.4.0
    @storybook/react-vite: 7.4.0 => 7.4.0
    @storybook/testing-library: 0.2.0 => 0.2.0
    @storybook/theming: 7.4.0 => 7.4.0
```

### Additional context

I just upgraded to 7.4.0 from 7.1.0 where the problem also occurred

**Comment by n3ssi3** [comment]
We are using `Storybook 8.0.10` and it also breaks 
![Screenshot 2024-05-08 at 14 02 21](https://github.com/storybookjs/storybook/assets/694883/370f82b7-db1b-473d-b325-e6ba5ea005f3)
![Screenshot 2024-05-08 at 14 02 58](https://github.com/storybookjs/storybook/assets/694883/8d0f9147-e74a-46a6-b195-ef70b6b015bd)

**Comment by shilman** [comment]
closing as dupe to #11428
