### ISSUE TITLE
[Bug]: Regression - @storybook/react-webpack5 v7.4 crashes without @storybook/manager-api

### ISSUE THREAD

**Issue by mkosir** [storybookjs/storybook#24004]
### Describe the bug

It looks like we have a regression in v7.4.0. [Previously fixed bug](https://github.com/storybookjs/storybook/issues/23876).

**Comment by yannbf** [comment]
Hey @mkosir could you please provide a reproduction? The former reproduction that was shared with us, works perfectly fine with 7.4.0. Thanks!

**Comment by mkosir** [comment]
Thanks, reinstalling node_modules and removing lock file did the trick! Sorry for the noise.
