### ISSUE TITLE
[Bug]: Update vue-docgen-api to latest version to support for external types in defineProps and defineEmits

### ISSUE THREAD

**Issue by rmerk** [storybookjs/storybook#24017]
### Describe the bug

Currently, if you import your props types from an external source and they have JSDoc comments it won't pick it up. I would imagine that this also causes issues for Autodocs as well when inferring types, as I had to manually adjust all the ArgTypes for it to show correctly. 

The changes were merged to their latest release as part of this PR which is in version `4.74.0`. The current `vue3/vite`  for storybook is on `4.40.0`. https://github.com/storybookjs/storybook/blob/next/code/frameworks/vue3-vite/package.json

PR from `vue-docgen-api` to support imported types.
https://github.com/vue-styleguidist/vue-styleguidist/pull/1586

![image](https://github.com/storybookjs/storybook/assets/4576425/6567d840-1ceb-4dbf-b0ea-d39a6d01909f)

![image](https://github.com/storybookjs/storybook/assets/4576425/e7f96ef2-a5db-42d3-b232-5982521af7cb)

### To Reproduce

```
import type MBtnProps from './m-btn.types'
import { computed } from 'vue'
import './m-btn.css'


const props = withDefaults(defineProps<MBtnProps>(), {
    ariaLabel: undefined,
    buttonSize: 'lg',
    buttonStyle: 'primary',
    buttonType: 'button',
    disabled: false,
    iconLeading: undefined,
    iconTrailing: undefined,
    label: 'Button',
    loading: false,
    square: false,
    tabIndex: undefined,
})
```

**Results In**
![image](https://github.com/storybookjs/storybook/assets/4576425/c5551f0d-dfaf-423e-b7cf-1a7b0372616e)

### System

```bash
Environment Info:

  System:
    OS: macOS 13.5
    CPU: (12) arm64 Apple M2 Pro
  Binaries:
    Node: 18.17.0 - ~/.nvm/versions/node/v18.17.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.17.0/bin/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.0/bin/npm
  Browsers:
    Chrome: 116.0.5845.110
    Safari: 16.6
  npmPackages:
    @storybook/addon-docs: ^7.4.0 => 7.4.0
    @storybook/addon-essentials: ^7.4.0 => 7.4.0
    @storybook/addon-interactions: ^7.4.0 => 7.4.0
    @storybook/addon-links: ^7.4.0 => 7.4.0
    @storybook/blocks: ^7.4.0 => 7.4.0
    @storybook/testing-library: ^0.2.0 => 0.2.0
    @storybook/vue3: ^7.4.0 => 7.4.0
    @storybook/vue3-vite: ^7.4.0 => 7.4.0
```

**Comment by tfoxy** [comment]
Hi @rmerk ! I have Storybook installed in my project and it's using `4.74.0`. In the `package.json` that you are referring it's set to `^4.40.0`, which will automatically download the latest version of v4. Can you check which version is installed in your project `package-lock.json`? Mine has the following:

```json
    "node_modules/vue-docgen-api": {
      "version": "4.74.0",
      "resolved": "https://registry.npmjs.org/vue-docgen-api/-/vue-docgen-api-4.74.0.tgz",
      "integrity": "sha512-NNYYt0cZzr1E5MeJX1sQEYlZ3QN2QIiZaxuBgqpnidICcLgtGxFtU9PDpsWKMNKIUgH++lWnNW+R1r7vP/WAAQ==",
```
