### ISSUE TITLE
[Bug]: Values are incorrectly passed through the url in a new window

### ISSUE THREAD

**Issue by inspector-code** [storybookjs/storybook#24039]
### Describe the bug

If you change the primary argument from false to true, it will still be false. For example:

http://localhost:6007/iframe.html?args=primary:!false&id=example-button--primary&viewMode=story - will be false
http://localhost:6007/iframe.html?args=primary:!true&id=example-button--primary&viewMode=story - will be false too

**Comment by sonallux** [comment]
I experience the same issue. When I open the iframe using the "Open canvas in new tab" button, I am also getting an URL where boolean values are prefix with `!`. But when I manually remove the `!` in the URL then boolean parameters are respected and everything works as expected.

**Comment by vanessayuenn** [comment]
I think this is a dupe of #25035
