### ISSUE TITLE
[Bug]: Error: [🍍]: "getActivePinia()" was called but there was no active Pinia.

### ISSUE THREAD

**Issue by methodev** [storybookjs/storybook#24080]
### Describe the bug

Given that I have setup Pinia in **preview.js** as follows:
```
import { setup } from '@storybook/vue3';
import { createPinia } from 'pinia';

const pinia = createPinia();

// Setup the Vue app
setup((app) => {
  console.log('register pinia');
  app.use(pinia);
});
```

When I go to a story of a component that is using a Pinia store I keep getting this error that there is no active Pinia in my app instance.

### System

```bash
Environment Info:

  System:
    OS: macOS 13.5.1
    CPU: (12) x64 Apple M2 Pro
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
  Browsers:
    Chrome: 116.0.5845.140
    Edge: 114.0.1823.67
    Safari: 16.6
  npmPackages:
    @storybook/addon-console: ^2.0.0 => 2.0.0 
    @storybook/addon-essentials: ^7.4.0 => 7.4.0 
    @storybook/blocks: ^7.4.0 => 7.4.0 
    @storybook/testing-library: ^0.2.1-next.0 => 0.2.1-next.0 
    @storybook/theming: ^7.4.0 => 7.4.0 
    @storybook/vue3: ^7.4.0 => 7.4.0 
    @storybook/vue3-webpack5: ^7.4.0 => 7.4.0
```

### Additional context

I do it exactly as described in the page [Integrate Pinia with Storybook](https://storybook.js.org/recipes/pinia).

**Comment by shilman** [comment]
@Integrayshaun is this something you can help with?

**Comment by methodev** [comment]
> Hey @methodev 👋
> 
> That's odd! Do you have a small repro that I can dig into?

Hey @Integrayshaun,

[https://github.com/methodev/storybook-with-pinia-test](https://github.com/methodev/storybook-with-pinia-test)

Here's a repo I just created with a very basic configuration. There are just few things that are set to be exactly as in a project I'm working on. For instance, the location of the storybook dir is changed. Take a look at the only Button component, and let me know what do you get, please.

I reproduce the problem in this setup.

![image](https://github.com/storybookjs/storybook/assets/5436678/72092c85-2155-4a4a-bfbf-77c04c259b7c)

**Comment by Integrayshaun** [comment]
Hey @methodev Thank you for putting this together for us :)

I've given it a look and i'm not sure why this breaks.

Perhaps @chakAs3 has an idea?

**Comment by methodev** [comment]
@Integrayshaun, @chakAs3, @doutatsu

I found out what was the problem.

There is a `.babelrc` file in the Storybook directory with the following content:

```
{
  "presets": [["@babel/env", { "modules": "commonjs" }]]
}
```

It all started working after removing the `{ "modules": "commonjs" }`.

**Comment by Integrayshaun** [comment]
Oh jeeze! that's a good catch, @methodev! I'll make sure to keep an eye out for that in the future

**Comment by doutatsu** [comment]
@methodev I don't have nothing like that, so must be something else 😫

**Comment by Integrayshaun** [comment]
@doutatsu Can you share a reproduction so that we can dig in a little deeper?

I'll be away for the next few weeks but perhaps @kasperpeulen or @chakAs3 can help you out.

**Comment by chakAs3** [comment]
hi @doutatsu  just do this 
```
// Setup the Vue app
setup((app) => {
  console.log('register pinia');
 const pinia = createPinia();
  app.use(pinia);
});
```

**Comment by doutatsu** [comment]
@chakAs3 I use Vite, not webpack. Pinia works just fine in my application and is working with Storybook 6. Upgrading to 7 specifically what breaks it. Here is my `preview.js`, adjusted to work with 7

```js
import { setup } from '@storybook/vue3';
import { createHead } from '@unhead/vue';
import { createPinia } from 'pinia';
import VueScreen from 'vue-screen';
import VueTippy from 'vue-tippy';
import VueScrollTo from 'vue-scrollto';
import vClickOutside from 'v-click-outside';
import Vue3TouchEvents from 'vue3-touch-events';
import VueMyToasts from 'vue-my-toasts';
import { createVfm } from 'vue-final-modal';
import VWave from 'v-wave';

import '@/stylesheets/global.scss';
import '@/stylesheets/transitions.scss';
import 'vue-final-modal/style.css';

const pinia = createPinia();
const head = createHead();
const vfm = createVfm();

import router from '@/router/index';

import BaseNotification from '@/components/base_components/BaseNotification.vue';

// Plugins
import HeroIcons from '@/plugins/heroicons';
import globalComponents from '@/plugins/globalComponents';
import darkTheme from '@/plugins/darkTheme';
import { i18n } from '@/plugins/i18n';

setup((app) => {
  app.directive('clickOutside', vClickOutside);

  app.use(pinia);
  app.use(HeroIcons);
  app.use(globalComponents);
  app.use(darkTheme);
  app.use(i18n);
  app.use(head);
  app.use(vfm);
  app.use(VueScrollTo);
  app.use(VueScreen);
  app.use(VWave);
  app.use(Vue3TouchEvents, { disableClick: true, touchHoldTolerance: 300, });
  app.use(VueMyToasts, {
    component: BaseNotification,
    options: {
      position: 'top-right',
    },
  });
  app.use(VueTippy, {
    defaultProps: {
      animation: 'shift-away',
      theme: 'light',
      arrow: false,
      touch: false,
    },
  });

  // Setup router with toasts
  const routerInstance = router(app.config.globalProperties.$toasts);

  app.use(routerInstance);
});


export const decorators = [(story, { parameters }) => {
    const theme = parameters.theme || 'light';
    const themeToAdd = theme === 'light' ? 'light' : 'dark';
    const themeToRemove = theme === 'light' ? 'dark' : 'light';
    const htmlElement = document.querySelector('html');

    htmlElement.classList.add(themeToAdd);
    htmlElement.classList.remove(themeToRemove);

    return story();
}]

export const parameters = {
  layout: 'fullscreen',
  actions: { argTypesRegex: "^on[A-Z].*" },
  chromatic: {
    pauseAnimationAtEnd: true,
    viewports: [375, 1280],
  },
  controls: {
    matchers: {
      color: /(background|color)$/i,
      date: /Date$/,
    },
  },
}

```

**Comment by chakAs3** [comment]
@doutatsu are you using Nuxt ?

**Comment by doutatsu** [comment]
Nope, just regular Vue 3 app

**Comment by chakAs3** [comment]
@doutatsu  but this project is using webpack bundler https://github.com/methodev/storybook-with-pinia-test

**Comment by doutatsu** [comment]
I've created issue for my case over here - https://github.com/storybookjs/storybook/issues/24347

**Comment by Integrayshaun** [comment]
Closing this issue in favour of #24347

**Comment by spiroskarathanassis** [comment]
Same error happened on Nuxt 3
