### ISSUE TITLE
[Bug]: Code block does not work properly with some property names of Vue components

### ISSUE THREAD

**Issue by aosmakserato** [storybookjs/storybook#24119]
### Describe the bug

Suppose we have a Vue component with two props - `ribbonTitle` and `iconClass`. Here is what the code block on the docs page will show:
![Screen Shot 2023-09-11 at 2 41 32 PM](https://github.com/storybookjs/storybook/assets/74880519/3b773645-4801-4285-966b-0d2f938e8dc5)
However, if we rename those to `someTitle` and `someClass` accordingly, it will start working as expected.
![Screen Shot 2023-09-11 at 2 45 55 PM](https://github.com/storybookjs/storybook/assets/74880519/85ffa0bf-93c2-4df2-8c38-e2ca0cd273b4)
Alternatively, you can add a renderer to fix the problem, but it is rather a hotfix, not a proper one.
```
...
  render: (args: any) => ({
    components: { Ribbon },
    setup() {
      return { args };
    },
    template: '<Ribbon v-bind="args" />',
  }),
...
``` 

### To Reproduce

It is quite easy to reproduce. You need a Vue-3 Vite (ts)-based project. Then create a simple Vue component.
```
<template>
  <div class="ribbon">
    <i v-if="iconClass" :class="iconClass" />
    {{ ribbonTitle }}
  </div>
</template>

<script setup lang="ts">
interface Props {
  ribbonTitle?: string
  iconClass?: string
}
const props = withDefaults(defineProps<Props>(), {
  ribbonTitle: 'default',
  iconClass: '',
})
</script>
<style>
.ribbon {
  background-color: #888888;
  display: inline-block;
  padding: 0 100px;
  color: #ffffff;
}
</style>

```
Then, a stories file.
```
import type { Meta, StoryObj } from '@storybook/vue3';
import Ribbon from './Ribbon.vue'

const meta = {
  title: 'Example/Ribbon',
  component: Ribbon,
  tags: ['autodocs'],
} satisfies Meta<typeof Ribbon>;

export default meta;

type Story = StoryObj<typeof Ribbon>;

export const Standard: Story = {
  args: {
    ribbonTitle: 'test',
    iconClass: 'far fa-info-circle'
  }
};

```
Done!

Let me know if you believe creating a reproduction is required here.  

### System

```bash
System:
    OS: macOS 12.3.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 18.17.0 - ~/.nvm/versions/node/v18.17.0/bin/node
    npm: 9.8.1 - ~/.nvm/versions/node/v18.17.0/bin/npm
  Browsers:
    Chrome: 116.0.5845.179
    Safari: 15.4
  npmPackages:
    @storybook/addon-actions: ^7.4.0 => 7.4.0 
    @storybook/addon-essentials: ^7.4.0 => 7.4.0 
    @storybook/addon-interactions: ^7.4.0 => 7.4.0 
    @storybook/addon-links: ^7.4.0 => 7.4.0 
    @storybook/testing-library: ^0.2.0 => 0.2.0 
    @storybook/vue3: ^7.4.0 => 7.4.0 
    @storybook/vue3-vite: ^7.4.0 => 7.4.0 
```

It can also be reproduced in 7.1 and 7.5-alpha.
```


### Additional context

_No response_

**Comment by KevinCarnaille2** [comment]
Yep actually I've posted the same issue 4 months ago 
https://github.com/storybookjs/storybook/issues/23224#issuecomment-1755669313

icon seems to be a key name here. Haven't found any workaround so far

**Comment by vanessayuenn** [comment]
closing this as dupe to https://github.com/storybookjs/storybook/issues/23224
