### ISSUE TITLE
[Bug]: DocsPage remounts components multiple times when globals changes

### ISSUE THREAD

**Issue by gilbarbara** [storybookjs/storybook#24118]
### Describe the bug

Changing the toolbar options on the docs page remounts the components multiple times.

### To Reproduce

https://stackblitz.com/edit/github-4pmoyn

### System

```bash
Environment Info:

  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 16.20.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
  npmPackages:
    @storybook/addon-essentials: ^7.5.0-alpha.1 => 7.5.0-alpha.1 
    @storybook/addon-interactions: ^7.5.0-alpha.1 => 7.5.0-alpha.1 
    @storybook/addon-links: ^7.5.0-alpha.1 => 7.5.0-alpha.1 
    @storybook/addon-onboarding: ^1.0.8 => 1.0.8 
    @storybook/blocks: ^7.5.0-alpha.1 => 7.5.0-alpha.1 
    @storybook/react: ^7.5.0-alpha.1 => 7.5.0-alpha.1 
    @storybook/react-vite: ^7.5.0-alpha.1 => 7.5.0-alpha.1 
    @storybook/testing-library: ^0.2.0 => 0.2.0
```

### Additional context

Open the sandbox, select the Button docs, open the console in the developer tools, and change any of the toolbar options.

**Comment by vanessayuenn** [comment]
hi @gilbarbara, I don't quite understand the repro step - what did you mean by "open the console in the developer tools, and change any of the toolbar options"?

**Comment by gilbarbara** [comment]
I posted the information requested 3 weeks ago...

**Comment by vanessayuenn** [comment]
@gilbarbara sorry for the noise, and thanks for the additional information. The behaviour you described seems correct and the `useEffect` hook as written would run on every render. Can you elaborate on what your expectations are?

**Comment by gilbarbara** [comment]
Hey @vanessayuenn 

For me, the problem is that it keeps remounting the components instead of just re-rendering, which triggers expensive actions in some cases, making the update super slow.
So, I expect that the updates in the `globals` do not re-mount everything.

**Comment by vanessayuenn** [comment]
The repro you provided uses the `useEffect` hook in a way that gets run on every re-render, not on mount ([docs](https://react.dev/reference/react/useEffect#examples-dependencies)). So unless I'm missing something, nothing there indicates the components get re-mounted on each change.

**Comment by gilbarbara** [comment]
Oh, sorry! I forgot to add the empty dependencies array.
I've updated the sandbox and it still shows the same behavior.

**Comment by vanessayuenn** [comment]
I checked out the updated sandbox and cannot see the same behaviour anymore. `mount` gets printed once only

**Comment by gilbarbara** [comment]
Ok, that's the expected behavior, then.
