### ISSUE TITLE
[Bug]: Doesn't `        // Match any prop that ends with "date" or "Date".`

### ISSUE THREAD

**Issue by manavm1990** [storybookjs/storybook#24120]
### Describe the bug

In `preview.ts`, you have: `date: /Date$/,`. 🙅🏾‍♀️ It's missing an `i` at the end. so it's only getting `Date`, and not `date`. 

Just replace the code [here](https://github.com/storybookjs/storybook/blob/ea5688992b812188abafef83fe8aadf94e568b25/code/lib/cli/src/generators/configure.ts#L155) with: `/Date$/i`. That is all. ✔️

**Comment by vanessayuenn** [comment]
@manavm1990 thanks for opening this and digging into the source already. Since you already did the investigation, would you also like to open a PR with a fix? We'd really appreciate that!

**Comment by arup1221** [comment]
@manavm1990 have you completed this and made PR?

**Comment by manavm1990** [comment]
Sorry. I have not. I m on vacation until Monday. Feel free to do it, or else I will check it then @arup1221

**Comment by manavm1990** [comment]
Yes. Please!

**Comment by vanessayuenn** [comment]
closed via #24195. Thanks @arup1221!
