### ISSUE TITLE
[Bug]: Documentation are not generated for a Svelte component when using vite and Typescript

### ISSUE THREAD

**Issue by j3rem1e** [storybookjs/storybook#24137]
### Describe the bug

When using the builder `@storybook/svelte-vite` or `@storybook/sveltekit`, the documentation for a component written in Typescript are not generated.

Vite uses esbuild, and esbuild remove comments and jsdoc when transpiling typescript. However, jsdoc is used to extract the documentation.

It works when using `sveltePreprocess()` instead of `vitePreprocess()`.

### To Reproduce

It's visible on the sandbox `svelte-vite/default-ts` and `sveltekit/default-ts`. The `Button` component doesn't have documentation.

**Comment by JReinhold** [comment]
Closed by #24906
