### ISSUE TITLE
[Bug]: there is no way to hide the "whats new" block

### ISSUE THREAD

**Issue by Crone1331** [storybookjs/storybook#24183]
### Describe the bug

I couldn't find the option to hide the "what's new" block
![IMG_20230914_221006](https://github.com/storybookjs/storybook/assets/43894206/6f46ef9d-21bd-4811-b60c-b3a0bf0f3c7e)

### To Reproduce
https://codesandbox.io/p/sandbox/dreamy-brattain-qkkmjm?file=/.storybook/main.ts:11,40

### System

```bash
storybook 7.4.0
```

**Comment by vanessayuenn** [comment]
There is [an option to disable the notification](https://storybook.js.org/docs/react/api/main-config-core#disablewhatsnewnotifications) but not to hide the menu, which is what I understood that you want, right? Could you elaborate on this request, please?

**Comment by Crone1331** [comment]
Yes, I would like to hide the item and menu too.
although, as far as I understand, this item is only displayed during DEV?
