### ISSUE TITLE
[Bug]: localhost Storybook composition CORS errors

### ISSUE THREAD

**Issue by South-Paw** [storybookjs/storybook#24207]
### Describe the bug

I was testing with 3 Storybook (2 for packages and 1 root one that composed them with docs).

The root storybook (port: 6006) which is only mdx docs, references the other 2 storybooks (ports 6007 and 6008)

I can open storybook 2 and 3 independently, but opening the root storybook it can't compose the other two into it and has the following error in Chrome:

```Access to fetch at 'http://localhost:6007/stories.json' from origin 'http://localhost:6006' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'.```

Don't see CORS errors in Firefox, but they other 2 storybooks wouldn't compose.

![image](https://github.com/storybookjs/storybook/assets/2154764/f5c8c526-2cf1-49c5-bc12-d67b148d2643)

### To Reproduce

Hopefully this repo will suffice: https://github.com/South-Paw/storybook-localhost-composition-reproduction

Just start both Storybooks in different terminals. `one` composes `two` into it.

### System

```bash
Environment Info:

  System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 AMD Ryzen 5 3600X 6-Core Processor
  Binaries:
    Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 116.0.5845.188
    Edge: Spartan (44.19041.1266.0), Chromium (117.0.2045.31)
```

**Comment by South-Paw** [comment]
Looks like if they're started in a different order, the result is different.

If you start storybook one then storybook two, you'll get a CORS error

If you start storybook two then storybook one, they'll compose as expected

🤔

**Comment by shilman** [comment]
closing this as duplicate to https://github.com/storybookjs/storybook/issues/18405
