### ISSUE TITLE
[Bug]: typescript dependencies mean that "npx storybook@latest init" fails

### ISSUE THREAD

**Issue by blomm** [storybookjs/storybook#24218]
### Describe the bug

I've got a Create React App (React version 18.2) and I just cannot get storybook to install.
Looks like storybook insists on typescript ^3.2.1 || ^4?
Does that mean storybook doesn't work with Typescript 5?
(trying to --force doesn't work either)

npm ERR! Could not resolve dependency:
npm ERR! peerOptional typescript@"^3.2.1 || ^4" from react-scripts@5.0.1
npm ERR! node_modules/react-scripts
npm ERR!   react-scripts@"5.0.1" from the root project

**Comment by shilman** [comment]
Based on your description it seems like this is an issue with CRA / `react-scripts`, not with Storybook. People are using Storybook with TS5. Closing this, but happy to re-open if I got this wrong.
