### ISSUE TITLE
[Bug]: Horizontal scroll bar in Canvas hidden by styling

### ISSUE THREAD

**Issue by dexster** [storybookjs/storybook#24226]
### Describe the bug

When using Canvas it will hide most of the horizontal scroll bar for cases where horizontal scrolling is required 

With Show Code
![withshow](https://github.com/storybookjs/storybook/assets/6392334/07960fdc-7687-4a5e-ac50-78760bbe9449)

Hiding Code
![show-hidden](https://github.com/storybookjs/storybook/assets/6392334/4361d99d-7d08-4990-bc61-0a0f8d2669ec)

Removing the margin property fixes the issue
![fix](https://github.com/storybookjs/storybook/assets/6392334/0a31d903-9cdc-4206-8048-85339cd16e17)

### System

```bash
System:
    OS: macOS 13.5.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
  Browsers:
    Edge: 117.0.2045.31
    Safari: 16.6
  npmPackages:
    @storybook/addon-essentials: ^7.4.2 => 7.4.2 
    @storybook/addon-interactions: ^7.4.2 => 7.4.2 
    @storybook/angular: ^7.4.2 => 7.4.2 
    @storybook/core-server: ^7.4.2 => 7.4.2 
    @storybook/jest: ~0.1.0 => 0.1.0 
    @storybook/test-runner: ^0.13.0 => 0.13.0 
    @storybook/testing-library: ~0.2.0 => 0.2.0
```

**Comment by Funkycodes** [comment]
Seems like a negative margin

**Comment by aacode7** [comment]
Hi.I'm Asif and I'm new to open source contribution.I wanna contribute to this issue.Please assign me.

**Comment by Svvmy** [comment]
Hello, I would like to contribute to this issue. How is the contribution for the project going?

**Comment by abhisheksharma010** [comment]
Can this assign to me i want to work on this

**Comment by abhisheksharma010** [comment]
Hey there! 👋

I'm new to open source and super excited to dive in! I'd love to work on this. Can I be assigned to this issue? 🚀

**Comment by supriya-2108** [comment]
Hello team please assign this issue to me
