### ISSUE TITLE
[Bug]: UseMemo console error when disabling actions or controls

### ISSUE THREAD

**Issue by jiacoucci-extron** [storybookjs/storybook#24265]
### Describe the bug

When disabling controls or actions in stories Meta data parameters like `parameters: { actions: {disable: true}}` the console in the browser throws a useMemo error like the screen shot below.
![image](https://github.com/storybookjs/storybook/assets/108286406/927ce5a6-df44-4289-8a0c-bd4c3104a8e1)

This rather annoying since v6.5 of storybook allowed controls to be disabled without any issues. Controls and actions should be allowed to be disabled with out any console errors. This does not seem to break the story as far as i can tell but the only solution ive seen to have no error currently is to just allow controls and actions to be active but empty.

### To Reproduce

code change on line: 16 in Page.stories.ts
https://stackblitz.com/edit/github-vrpkro?file=src%2Fstories%2FPage.stories.ts

1. Load the project.
2. Navigate to the page example
3. open the console
4. the error will be show.

You can navigate to different examples to see no error is shown for examples without controls/actions disabled and then navigate back to see that error.

### System

```bash
Local project: 7.4.3
StackBlitz: 7.5.0-alpha
chrome: Version 116.0.5845.187
```

**Comment by rahimny** [comment]
Looks related to https://github.com/storybookjs/storybook/issues/24539

**Comment by yannbf** [comment]
Hey everyone! This issue has been fixed in Storybook 8. We just released a beta, please consider upgrading your project and using it. Feedback is appreciated 🙏

```
npx storybook@next upgrade
```
