### ISSUE TITLE
[Bug]: Storybook + Tailwind does not load tailwind plugins

### ISSUE THREAD

**Issue by rory-orennia** [storybookjs/storybook#24279]
### Describe the bug

If you use any tailwind plugins, they are not rendered in Storybook.  I've test in both Svelte and Vite+React with the same results.  I originally thought this was an issue with Skeleton (https://www.skeleton.dev/) and raised an issue with them (https://github.com/skeletonlabs/skeleton/issues/2063).  After digging a bunch more I discovered that even the built in tailwind plugins don't work (typography, forms, etc.).  Then I thought maybe it's an issue with the Svelte implementation and whipped up a Vite + React repository to test.  That also didn't work so it would seem that all plugins aren't being loaded by the Storybook tailwind support.

Here's a picture of the component in Storybook vs in `pnpm dev`.  the `prose` class doesn't work (typography plugin) and neither does any of the skeleton classes which come from their own plugin.  But base tailwind is working (bg-green-500)
![image](https://github.com/storybookjs/storybook/assets/93952948/2e315ad5-698d-4359-9feb-13d2d64b6f48)
![image](https://github.com/storybookjs/storybook/assets/93952948/a7d03faf-7de2-46cb-bfab-d0b4e61dfc8e)

### To Reproduce

Svelte: https://github.com/rory-orennia/skeleton-v2-storybook
React: if you want a react one I can push the quick repo I made

### System

```bash
Environment Info:

  System:
    OS: macOS 13.5.2
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 20.5.0 - ~/.nvm/versions/node/v20.5.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 9.8.0 - ~/.nvm/versions/node/v20.5.0/bin/npm
  Browsers:
    Chrome: 116.0.5845.187
    Edge: 117.0.2045.31
    Safari: 16.6
  npmPackages:
    @storybook/addon-essentials: ^7.4.3 => 7.4.3
    @storybook/addon-interactions: ^7.4.3 => 7.4.3
    @storybook/addon-links: ^7.4.3 => 7.4.3
    @storybook/addon-svelte-csf: ^4.0.8 => 4.0.8
    @storybook/addon-themes: ^7.4.3 => 7.4.3
    @storybook/blocks: ^7.4.3 => 7.4.3
    @storybook/svelte: ^7.4.3 => 7.4.3
    @storybook/sveltekit: ^7.4.3 => 7.4.3
    @storybook/testing-library: ^0.2.1 => 0.2.1
```

**Comment by bhvngt** [comment]
I faced similar issue and have landed up here. It will be great if this is fixed.

**Comment by vanessayuenn** [comment]
@Integrayshaun any insights into what's going on here? 👀

**Comment by Integrayshaun** [comment]
Hey @rory-orennia Sorry for the late reply 🙏 

I just took a quick peek at your example and found the issue. The tailwind plugins are working as expected. However, you need to add the `data-theme="wintry"` attribute to the body in the Storybook iframe where your stories are rendered.

The easiest way to achieve this is through [previewBody](https://storybook.js.org/docs/react/api/main-config-preview-body#page-top)

**Comment by Integrayshaun** [comment]
@bhvngt Are you also working with Skeleton? if the above solution doesn't work for you, please give me a reproduction of your issue to work through

**Comment by rory-orennia** [comment]
I added a `.storybook/preview-body.html` with the following code:
```html
<body data-theme="wintry"></body>
```
and now Skeleton works, but the typography plugin still doesn't work
![image](https://github.com/storybookjs/storybook/assets/93952948/594489f0-dcf6-4cb8-9c5c-a70bdffdf683)

**Comment by Integrayshaun** [comment]
@rory-orennia are you sure? I inspected the text and the prose class was being applied the whole color palette. Perhaps it just doesn't seem like the right grey on the white background?

<img width="785" alt="image" src="https://github.com/storybookjs/storybook/assets/18172605/7828e25d-1938-4825-97c6-a182619a8e30">

**Comment by rory-orennia** [comment]
hmm you're right.. Sorry about that.  If I make the background black then it becomes apparent that it's working.  Thanks for your help!  I'll update the skeleton ticket I created to let people know how to get it working in storybook if they stumble upon the same issue.

Feel free to close this unless @bhvngt is still having issues

**Comment by bhvngt** [comment]
After trying [previewBody](https://storybook.js.org/docs/react/api/main-config-preview-body#page-top) its working fine for me. I missed trying this option out. 

I am good with closing this issue. Thanks @rory-orennia @Integrayshaun for all your help and follow up

**Comment by Integrayshaun** [comment]
It's all good @rory-orennia 😁 it's so subtle I had to check to be sure.

@bhvngt I'm glad to hear that this worked out for you as well.

I hope that you both have a wonderful week

**Comment by lorddesert** [comment]
> I added a `.storybook/preview-body.html` with the following code:
> 
> <body data-theme="wintry"></body>
> 
> and now Skeleton works, but the typography plugin still doesn't work ![image](https://github.com/storybookjs/storybook/assets/93952948/594489f0-dcf6-4cb8-9c5c-a70bdffdf683)

Solved the problem. Thanks <3
