### ISSUE TITLE
[Documentation]: Add documentation for vite config location

### ISSUE THREAD

**Issue by michaelw85** [storybookjs/storybook#24306]
### Describe the problem

I'm new to storybook and started a vue3-vite setup.
My existing project contains a `vite.config.ts` and in my case breaks the default HMR functionality of storybook.
To prevent this config from being used I added the following config to my main.ts

```
    framework: {
        name: '@storybook/vue3-vite',
        options: {
            builder: {
                viteConfigPath: '.storybook/vite.config.ts',
            },
        },
    },
```

basic vite config for .storybook directory
```
import vue from '@vitejs/plugin-vue';

const config = {
    plugins: [vue()],
};

export default config;
```

It would be great if this option would be documented and this scenario could be added as a remark in case of issues.

### Additional context

https://github.com/storybookjs/storybook/pull/20681

**Comment by jonniebigodes** [comment]
@michaelw85, thanks for reaching out to us with your issue. We appreciate it 🙏 ! Hope you don't mind, but I'm closing this issue as there's already a similar one that factors in the same body of work required (i.e., #23218).


Hope you have a fantastic week.

Stay safe
