### ISSUE TITLE
[Bug]: Navigation not working on mobile devices.

### ISSUE THREAD

**Issue by pegondo** [storybookjs/storybook#24327]
### Describe the bug

The navigation is not working when using the Storybook version 7.4.5 on a mobile device.

When accessing a Storybook on a mobile device, you get this scenario:
1. Tap on the `Sidebar` tab.
2. Choose a different story.
3. The story is correctly displayed on the right side of the screen.
4. Tap on the `Canvas` tab.
5. The story displayed is the initial one instead of the one selected in step 3.

Here is a video showing the bug scenario:
[example.webm](https://github.com/storybookjs/storybook/assets/90756043/f129f870-8743-440d-8cbb-97d73d239e36)

### To Reproduce

https://stackblitz.com/github/storybookjs/sandboxes/tree/next/react-vite/default-js/after-storybook?file=README.md&preset=node

### System

```bash
Environment Info:

  System:
    OS: Linux 5.19 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.13.1/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
  Browsers:
    Chrome: 114.0.5735.198
```

### Additional context

The most recent version where this bug does not happen is version 7.1.1.
Sometimes, you have to navigate to a different page that is not the landing one to reproduce the error.

**Comment by marcomontalbano** [comment]
I have the same issue described by @pegondo and I also wanna add that using `docsMode: true` the canvas is always blank.

https://github.com/storybookjs/storybook/assets/1681269/5e2d8fbd-b9eb-45a7-9c72-adb4338a1253

### To Reproduce

https://stackblitz.com/edit/github-czjhh4?file=.storybook%2Fmain.js

```diff
// .storybook/main.js

-  docs: {
-    autodocs: 'tag',
-  },
+  docs: {
+    autodocs: true,
+    docsMode: true,
+  },
```

**Comment by marcomontalbano** [comment]
This issue can be linked to #23723.

**Comment by pegondo** [comment]
Yes, it is related to https://github.com/storybookjs/storybook/issues/23723
