### ISSUE TITLE
[Bug]: Big documentation with code blocks are super slow to load since v7

### ISSUE THREAD

**Issue by thibaudsowa** [storybookjs/storybook#24332]
### Describe the bug

Hi

In our project we have un big markdown file to explain migration, version by version for our UI lib.

On storybook v6 the file was displayed instantaneously. Since the migration to v7 it is supeeer slow, the browser is literally freezing.
I noticed that was linked to the usage of code blocks.

Thanks!
Thibaud.

### To Reproduce

https://stackblitz.com/edit/github-d2hqwk-thmbbz?file=src%2FBigDocPage.mdx

### System

```bash
Environment Info:

  System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
  Binaries:
    Node: 16.15.1 - C:\opt\nodejs\node.EXE
    npm: 8.11.0 - C:\opt\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.2134.0), Chromium (117.0.2045.43)
  npmPackages:
    @storybook/addon-actions: ^7.4.5 => 7.4.5
    @storybook/addon-docs: ^7.4.5 => 7.4.5
    @storybook/addon-essentials: ^7.4.5 => 7.4.5
    @storybook/addon-interactions: ^7.4.5 => 7.4.5
    @storybook/addon-links: ^7.4.5 => 7.4.5
    @storybook/angular: ^7.4.5 => 7.4.5
    @storybook/builder-webpack5: ^7.4.5 => 7.4.5
    @storybook/manager-webpack5: ^6.5.16 => 6.5.16
    @storybook/testing-library: ^0.2.1 => 0.2.1
```

**Comment by razlifshitz** [comment]
Any updates? 🙏  we're having this issue as well.

**Comment by shilman** [comment]
For those of you experiencing this issue: how slow is it? And can you do a little profiling in the browser to see where the time is going? The Stackblitz repro above loads instantly on my machine

**Comment by thibaudsowa** [comment]
This is very strange... When I created the Stackblitz in September, I needed to be careful to do not add to much lines in the "big doc" page because my browser freezed to much. Now in the same example, there is no performance use...

@shilman How slow? Slow enough to crash the browser tab.

**Comment by korgon** [comment]
I've recently begun moving from Storybook 6 -> 7, and have the same issue in converting our documentation to utilizing our existing markdown files.

I don't encounter the issue when using the stackblitz provided by **thibaudsowa** - but locally I do have issues. Specifically, I have noticed that it is the code blocks with syntax callouts that cause the issue for me. The code block syntax type doesn't seem to matter, nor do the contents (so long as they have contents). Perhaps my issue is different, but slightly related.

Ex:
```
```html
```

```
```js
```

```
```sh
```

**Comment by SimonKunz** [comment]
We also have trouble with this. I'll append a trace from chrome developer tools. The problem seems to be somewhere here:
[Trace-20240118T154656.json](https://github.com/storybookjs/storybook/files/13978059/Trace-20240118T154656.json)

![image](https://github.com/storybookjs/storybook/assets/10567462/43a65705-c991-4f16-bf33-66807b71efdc)
