### ISSUE TITLE
[Bug]:component is not responsive in doc

### ISSUE THREAD

**Issue by Sudeepa1949** [storybookjs/storybook#24341]
### Describe the bug

I have one chart component, in doc when I try to change chart component properties , its not responsing. in canvas also propereties are  responding . this problem is coming after upgrading from 6.5.13 to  v7.4.5. here is my code in simple way.

`import { html } from "lit";
import { Story, Meta, Canvas, ArgsTable } from "@storybook/blocks";
import "./chart";
import donutOptions from "./charts/donut/sample-config.ts";

<Meta
    title="Components/Chart"
    component="ex-chart"
    parameters={
      {
        layout: "centered",
        status: {
          type: ["stable"],
        },
      }
    }
    argTypes= {{
      width: {
        name: "Width",
        control: {
          type: "number",
        },
      },
    }}
/>

export const DonutTemplate = (args) => {
   const donutChart = {
    ...donutOptions,
    width: args.width,
  };
  return html`
    <ex-chart .options="${donutChart}" ></ex-chart>
  `
};

<Canvas id="Donut">
    <Story name="Donut" 
        parameters={{docs: {
          source: {
              code: `const config = ${JSON.stringify(donutOptions, null, 4)}`,
              language: "javascript",
              dark: true,
          },
        }}}
        args = {{
          width : donutOptions.width,
        }}
        >
      {DonutTemplate.bind({})}
    </Story>
</Canvas>`

**Comment by Sudeepa1949** [comment]
please suggest me, if I miss anything here

**Comment by kmalap05** [comment]
I can resolve this issue, please assign it to me with Hacktoberfest 2023 tag.

**Comment by Sudeepa1949** [comment]
what is the problem here
#Hacktoberfest

**Comment by Sudeepa1949** [comment]
any updates on this, how can I resolve this,  Na is this valid bug? @kmalap05 @valentinpalkovic

**Comment by Sudeepa1949** [comment]
please give some update on this

**Comment by vanessayuenn** [comment]
Hi, thanks for reporting this. do you have a reproduction repo you can share? If not, can you create one (see [how to create a repro](https://storybook.js.org/docs/react/contribute/how-to-reproduce)). We prioritize bug reports that have reproduction. Thank you! 🙏
