### ISSUE TITLE
[Bug]: Error when switching themes (addon-themes)

### ISSUE THREAD

**Issue by cristian-atehortua** [storybookjs/storybook#24351]
### Describe the bug

When using `withThemeByClassName` from `@storybook/addon-themes` and trying to switch from the default theme to another it gets a message on the console: "Attempted to set a global (theme) that is not defined in initial globals or globalTypes".

```typescript
import type { StorybookConfig } from '@storybook/react-webpack5';

import { getAbsolutePath } from './utils';

const config: StorybookConfig = {
  stories: ['../packages/**/src/**/*.stories.{js,jsx,ts,tsx}'],,
  addons: [
    getAbsolutePath('@storybook/addon-links'),
    getAbsolutePath('@storybook/addon-essentials'),
    getAbsolutePath('@storybook/preset-create-react-app'),
    getAbsolutePath('@storybook/addon-interactions'),
    getAbsolutePath('@storybook/addon-knobs'),
    getAbsolutePath('@storybook/addon-themes'),
  ],
  framework: {
    name: getAbsolutePath('@storybook/react-webpack5'),
    options: {},
  },
  docs: {
    autodocs: true,
  },
};
export default config;
```

```typescript
// preview.ts
import type { Preview } from "@storybook/react";
import { withThemeByClassName } from "@storybook/addon-themes";

import './themes.scss';

const preview: Preview = {
  parameters: {
    actions: { argTypesRegex: "^on[A-Z].*" },
    backgrounds: {
      default: 'dark',
    },
    controls: {
      matchers: {
        color: /(background|color)$/i,
        date: /Date$/,
      },
    },
  },
  decorators: [
    withThemeByClassName({
      themes: {
        Light: 'light',
        Dark: 'dark'
      },
      defaultTheme: 'Light',
    }),
  ],
};

export default preview;
```

When clicking in the theme selector and clicking on "Dark theme" to switch themes, the theme is not changed and the mentioned message appears in the console.

### System

```bash
Environment Info:

  System:
    OS: macOS 13.5.2
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 16.20.2 - ~/.nvm/versions/node/v16.20.2/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.20.2/bin/yarn
    npm: 8.19.4 - ~/.nvm/versions/node/v16.20.2/bin/npm
  Browsers:
    Safari: 17.0
  npmPackages:
    @storybook/addon-essentials: ^7.4.5 => 7.4.5 
    @storybook/addon-interactions: ^7.4.5 => 7.4.5 
    @storybook/addon-knobs: ^7.0.2 => 7.0.2 
    @storybook/addon-links: ^7.4.5 => 7.4.5 
    @storybook/addon-themes: ^7.4.5 => 7.4.5 
    @storybook/blocks: ^7.4.5 => 7.4.5 
    @storybook/preset-create-react-app: ^7.4.5 => 7.4.5 
    @storybook/react: ^7.4.5 => 7.4.5 
    @storybook/react-webpack5: ^7.4.5 => 7.4.5 
    @storybook/testing-library: ^0.2.1 => 0.2.2
```

**Comment by tjwiebell** [comment]
I was able to solve this by adding this block to my `preview.ts`. Hopefully a simple patch, will look into contributor requirements and try to find the root cause this weekend.

```ts
const preview: Preview = {
  globalTypes: {
    theme: { type: 'string' },
  },
  ... your config
```

**Comment by vanessayuenn** [comment]
@tjwiebell thanks for the workaround, and looking forward to the patch! Be sure to check the [contribution guide](https://storybook.js.org/docs/react/contribute/how-to-contribute) and hop onto the [Storybook Discord](https://discord.gg/storybook) if you need any help getting started. 

cc @Integrayshaun as maintainer of the addon

**Comment by Integrayshaun** [comment]
@cristian-atehortua @tjwiebell how odd! The global is declared in the [`preview.tsx` file](https://github.com/storybookjs/storybook/blob/next/code/addons/themes/src/preview.tsx).

Are you both using 7.4.5?

**Comment by cristian-atehortua** [comment]
Hi @Integrayshaun, yes. I'm using 7.4.5

**Comment by Integrayshaun** [comment]
@cristian-atehortua @tjwiebell 

Can one of you give me a reproduction of this issue? I wasn't able to replicate it in a 7.4.5 sandbox

**Comment by tjwiebell** [comment]
> @cristian-atehortua @tjwiebell
> 
> Can one of you give me a reproduction of this issue? I wasn't able to replicate it in a 7.4.5 sandbox

Confirming I'm also on 7.4.5. Only commonality I see is we're both using monorepo setups, but I'll work on a repro in StackBlitz.

**Comment by tjwiebell** [comment]
Reproduction instance can be found here; logs the warning message in the console when trying to switch themes.

https://stackblitz.com/edit/github-weunpu?file=packages%2Fstorybook%2F.storybook%2Fpreview.ts

**Comment by JReinhold** [comment]
Thanks for the reproduction @tjwiebell. I was able to fix the issue (both in StackBlitz and locally by removing the usage of `getAbsolutePath` in `main.ts` and simply use the plain package name as a reference instead: https://stackblitz.com/edit/github-weunpu-7zgvzs?file=packages%2Fstorybook%2F.storybook%2Fmain.ts

I'm not sure why this fixes it (I would think both methods should work) and I'm not sure why `getAbsolutePath` was needed in the first place, but I assume there's a nuance that I'm missing.

**Comment by cristian-atehortua** [comment]
According to the comment added to this function when Storybook is initialized: 

```js
/**
 * This function is used to resolve the absolute path of a package.
 * It is needed in projects that use Yarn PnP or are set up within a monorepo.
 */
```

According to that, there are cases in which these function calls can not be removed. So removing them it's a workaround, too. We still need to find and solve the root cause.

**Comment by cristian-atehortua** [comment]
Great @JReinhold. Thanks!

**Comment by Kakadus** [comment]
This error is resurfacing when using CSF Next. Adding 
```
  globalTypes: {
    theme: { type: 'string' },
  },
```
to `preview.ts` works around the issue, but removing `getAbsolutePath` did not work for me.
