### ISSUE TITLE
[Bug]: node_modules is 660mb bigger due to @swc and @esbuild packages

### ISSUE THREAD

**Issue by bbellmyers** [storybookjs/storybook#24375]
### Describe the bug

Just upgraded to latest Storybook and now my node_modules is huge, primarily due to the new @swc and @esbuild packages.  This is breaking my CI system due to the huge build images required.  What can be done to trim this back?

### To Reproduce

install Storybook.  Note node_modules size.

node_modules % du -sk * | sort -rnk1
404140  `@swc`
202700  `@esbuild`
54668   `@storybook`

### System

```bash
Environment Info:

  System:
    OS: macOS 13.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
  Browsers:
    Edge: 117.0.2045.47
    Safari: 16.6
  npmPackages:
    @storybook/addon-a11y: 7.2.2 => 7.2.2 
    @storybook/addon-essentials: 7.2.2 => 7.2.2 
    @storybook/addon-interactions: 7.2.2 => 7.2.2 
    @storybook/addon-links: 7.2.2 => 7.2.2 
    @storybook/addon-styling: 1.3.5 => 1.3.5 
    @storybook/blocks: 7.2.2 => 7.2.2 
    @storybook/react: 7.2.2 => 7.2.2 
    @storybook/react-webpack5: 7.2.2 => 7.2.2 
    @storybook/testing-library: 0.0.14-next.2 => 0.0.14-next.2
```

**Comment by valentinpalkovic** [comment]
Hi @bbellmyers,

Thank you for the bug report!

I tried to verify the numbers on a React 18 (Webpack) project, and here are my stats (in kilobytes):

73668   @storybook
34620   @swc
14908   @babel
9296    @esbuild

Could you provide a reproduction or tell me which renderer and builder you are using? I will try to figure out, whether I can reproduce your numbers.

**Comment by o-alexandrov** [comment]
That's an issue in Yarn v1 [described here](https://github.com/evanw/esbuild/issues/2949#issuecomment-1444455690)

**Comment by valentinpalkovic** [comment]
In that case, we cannot do much but advise people to upgrade to yarn 2/3. I am closing this issue. @bbellmyers Let me know if the problem occurs with other package managers except of yarn 1.

**Comment by bbellmyers** [comment]
I am using npm

**Comment by o-alexandrov** [comment]
@bbellmyers platform-specific packages that are not for your operating system [are ignored](https://github.com/npm/cli/issues/4828) in your specified `npm 8` version.
You might want to try to attempt reproduce the issue with an [example project that was mentioned in a prior comment](https://github.com/storybookjs/storybook/tree/next/code/frameworks/react-webpack5).
- once it confirms you have no issue, then you should look at your `package-lock.json` files for the duplicate libraries
