### ISSUE TITLE
If the height is set on preview, and the height of the window is smaller, you don't see the mobile navigation

### ISSUE THREAD

**Issue by cdedreuille** [storybookjs/storybook#24424]
https://github.com/storybookjs/storybook/assets/1540635/a9fb9d7d-be95-4668-83a9-24febcfc6e8c

**Comment by abhisheksharma010** [comment]
Hey there! 👋

I'm new to open source and super excited to dive in! I'd love to work on this. Can I be assigned to this issue? 🚀

**Comment by cdedreuille** [comment]
Hi @abhisheksharma010. Thanks a lot for wanting to contribute to Storybook. Generally speaking, a good way to get started would be to pick an issue to solve from the list of "good first issues": https://github.com/storybookjs/storybook/issues?q=is:open+is:issue+label:%22good+first+issue%22
