### ISSUE TITLE
[Bug]: Cannot add script tag to end of previewBody

### ISSUE THREAD

**Issue by tjheffner** [storybookjs/storybook#24429]
### Describe the bug

I have an external script that I need to load after the component story has rendered. I have attempted to use `preview-body.html` as well as the config option, but neither seem to load the script tag in the correct place.

Is there a proper way to add a script tag to the bottom of the existing preview body? Or to run an arbitrary script after a story has loaded?

### To Reproduce

  ```
// main.ts
import type { StorybookConfig } from "@storybook/nextjs";

const config: StorybookConfig = {
    ...
    previewBody: (body) => `
      ${body}
      <script src="/generated/static-pages.entry.js"></script>
    `,
  }
  
export default config
  ```
  
  This renders it above the main `#storybook-root` div, instead of down below with the other two script tags coming from storybook proper.
![Screenshot 2023-10-10 at 5 50 46 PM](https://github.com/storybookjs/storybook/assets/11279744/3f09269e-a550-456d-9664-75f4f50d89b6)

### Additional context

I would expect it to render after all body content.

**Comment by shilman** [comment]
What does the script do? Is it possible to run it after the page has rendered using [DOMContentLoaded event](https://developer.mozilla.org/en-US/docs/Web/API/Document/DOMContentLoaded_event)? There's also the `play` function if that helps https://storybook.js.org/docs/react/writing-stories/play-function

**Comment by tjheffner** [comment]
The script is a third-party script that registers some react widgets & web components & initializes them on existing DOM elements. I have tried to use `DOMContentLoaded` as seen in comments in this older issue: https://github.com/storybookjs/storybook/issues/6113#issuecomment-1183339597 , but it doesn't quite work with the script I have to use.

It also seems a little excessive to need to do all of that, for what, in my mind, should be a fairly straightforward ask (add a script tag to the end of the body tag (or at least after the `#storybook-root` div)

Unfortunately, the `play` function doesn't work for me here either.

**Comment by tjheffner** [comment]
I worked around this by creating the script tag manually in a useEffect in one of my providers.

```ts
// webComponentProvider.tsx
import { useEffect, useState } from 'react'
import { defineCustomElements } from 'internal-package-providing-web-components'

const WebComponentProvider = ({ children }) => {
  const [loaded, setLoaded] = useState(false)
  useEffect(() => {
    defineCustomElements()

    // load script that registers additional web-component assets
    const scriptTag = document.createElement('script')
    scriptTag.src = '/generated/static-pages.entry.js'
    scriptTag.addEventListener('load', () => setLoaded(true))
    document.body.appendChild(scriptTag)
  }, [])

  return <>{children}</>
}

export default WebComponentProvider
```

```ts
// preview.tsx
const preview: Preview = {
  decorators: [
    (Story) => <WebComponentProvider>{Story()}</WebComponentProvider>,
  ],
 ...
}

export default preview
```

**Comment by hbendev** [comment]
No, please reopen this issue. This, and the workaroud mentioned in https://github.com/storybookjs/storybook/issues/6113#issuecomment-1183339597 is _really_ not developer friendly. I'm sure there are more use cases other than @tjheffner's, and it's just a matter of time until others face it.

Can you explain why a third option along `previewHead` and `previewBody` that targets the end of the embedded body tag is not a good idea? I think adding this would cause less issues reported in the future, when teams migrate between versions too.

**Comment by Lefthandmedia** [comment]
Same problem here. we need to run a lightbox initscript after our **webcomponents** load. 
would like to be able to have an event  'StorybookpageLoaded' to add in the preview-head.html
So no react here.
tnx 
RDG

**Comment by James-Wilkinson-git** [comment]
Also have this issue we need an easy way to inject a script per story that doesnt rerender twice

**Comment by ChalzZy** [comment]
This is still an issue as of 2024 Nov. Can this be reopened?

**Comment by ChalzZy** [comment]
Found a workaround, especially for those who don't use React. Not ideal, but it looks like this isn't getting fixed any time soon.

Here's an example using Slick Slider.  If you add an additional `<div id="storybook-root">...</div>` element to the DOM, then storybook will render your component in the first available `storybook-root` id. 

Do note that means you'll have two elements with the id of "storybook-root" on your page. But the second element will be invisible. 

The reason why I've added a `setTimeout` on my jQuery is because jQuery's `.ready` method incorrectly thinks the document is loaded, when it hasn't. This is a known issue here: 
https://github.com/storybookjs/storybook/discussions/16710

```js
  previewBody: (body) => `
    <div id="storybook-root">${body}</div>

    <script type="text/javascript" src="//code.jquery.com/jquery-1.11.0.min.js"></script>
    <script type="text/javascript" src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
    <script type="text/javascript" src="slick.min.js"></script>

    <script type="text/javascript">
      $(document).ready(function() {
        setTimeout(function() {
        $(".your-slider-class").each(function() {
          console.log($(this))
          $(this).slick({
            dots: true,
            infinite: true,
            speed: 500,
            slidesToShow: 1,
            slidesToScroll: 1,
          });
        });
        }, 1000);
      });
    </script>
  `,
```
