### ISSUE TITLE
[Bug]: a11y addon: accessibility tab not showing

### ISSUE THREAD

**Issue by Hidduh** [storybookjs/storybook#24436]
### Describe the bug

Hi! I am currently running @storybook/angular version 6.5.9 with the a11y addon. I am running two 'instances' of storybook in the same project: one for HTML-components and the other one which uses Angular. I have installed the a11y addon in both 'instances' and the accessibility tab only appears to be showing in one of the two , I simply can not get the tab showing on the Angular one even though I am using the same dependencies.
 
The versions I'm using are as follows:
@storybook/addon-a11y: 6.5.1
@storybook/addon-actions: 6.5.9
@storybook/addon-docs: 6.5.9
@storybook/angular: 6.5.9
@storybook/builder-webpackj5: 6.5.16
@storybook/manager-webpack5: 6.5.16
 
peerDependencies:
@angular/common: 13.3.10
@angular/core: 13.3.10
 
Thanks!

### To Reproduce

There's no real way to reproduce this; I simply followed the 'getting started' guide as listed [here](https://storybook.js.org/addons/@storybook/addon-a11y).

### System

```bash
System:                                                    
    OS: Windows 10 10.0.19045                                
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz   
  Binaries:                                                  
    Node: 16.20.1 - C:\tools\nodejs\node.EXE                 
    npm: 8.19.4 - C:\tools\nodejs\npm.CMD                    
  Browsers:                                                  
    Chrome: master_preferences                               
    Edge: Spartan (44.19041.1266.0), Chromium (117.0.2045.60)
  npmPackages:                                               
    @storybook/addons: ^6.5.16 => 6.5.16                     
    @storybook/angular: ^6.5.9 => 6.5.16                     
    @storybook/builder-webpack5: ^6.5.16 => 6.5.16
    @storybook/manager-webpack5: ^6.5.16 => 6.5.16
```

**Comment by vanessayuenn** [comment]
Could you please upgrade to the latest Storybook@7.x version and see if this issue persists? We've made lots of improvements in Storybook since 7.0 so it's quite likely that this issue has been resolved already. If this is still a problem, please update this issue with reproduction steps for 7.x version. Thank you!

**Comment by Hidduh** [comment]
> Could you please upgrade to the latest [Storybook@7.x](mailto:Storybook@7.x) version and see if this issue persists? We've made lots of improvements in Storybook since 7.0 so it's quite likely that this issue has been resolved already. If this is still a problem, please update this issue with reproduction steps for 7.x version. Thank you!

We'll be looking into this and i'll get back to you if this issue still persists with version 7. Thanks!
