### ISSUE TITLE
[Bug]: docMode Canvas button not working

### ISSUE THREAD

**Issue by calidan-x** [storybookjs/storybook#24431]
### Describe the bug

when click on mobile view, path back to '/'
<img width="332" alt="111" src="https://github.com/storybookjs/storybook/assets/57343735/5ae4a388-1b86-4983-a04a-192720696891">

**Comment by shilman** [comment]
Can you elaborate on the problem? What version of Storybook? What are the exact steps to reproduce? I don't understand the issue as it's currently filed. Thank you!

**Comment by sipkoepp** [comment]
We're facing the same problem using version 7.5.1. On mobile its impossivle to navigate between pages/components.

**Comment by fredvisser** [comment]
We're seeing the [same thing](https://github.com/ni/nimble/issues/1639) with 7.5.2 - https://nimble.ni.dev/storybook

![](https://user-images.githubusercontent.com/1588923/279721209-946ddd62-a245-4f75-92e0-be91164ba531.gif)

Can't select a story in the sidebar and switch back to see the story, it always goes back to the anchor story.

**Comment by fredvisser** [comment]
Please reopen - the issue has sufficient information to reproduce - thanks!
