### ISSUE TITLE
[Bug]: updating from 7.0.17 to  causes Vercel builds to break

### ISSUE THREAD

**Issue by peter-bilt** [storybookjs/storybook#24441]
### Describe the bug

Upgrading storybook versions breaks my projects build in Vercel. 

here is the error: 

Error: ENOSPC: no space left on device, write
--
22:12:50.604 | Error: ENOSPC: no space left on device, write
22:12:50.770 | SyntaxError: /vercel/output/builds.json: Unexpected end of JSON input
22:12:50.770 | at JSON.parse (<anonymous>)
22:12:50.770 | at T2t (/var/task/sandbox.js:98:491)
22:12:50.770 | at async Cs (/var/task/sandbox.js:239:1383)
22:12:50.770 | at async Object.gEe (/var/task/sandbox.js:239:8583)
22:12:50.770 | at async TCe (/var/task/sandbox.js:245:4681)
22:12:50.770 | at async zBt (/var/task/sandbox.js:261:1990)
22:12:50.771 | at async GBt (/var/task/sandbox.js:261:1791)

package json before updgrading versions: 

    "storybook": "7.0.17",
 "@storybook/addon-essentials": "7.0.17",
    "@storybook/addon-interactions": "7.0.17",
    "@storybook/addon-links": "7.0.17",
    "@storybook/addon-styling": "1.0.8",
    "@storybook/blocks": "7.0.17",
    "@storybook/react": "7.0.17",
    "@storybook/react-webpack5": "7.0.17",
    "@storybook/testing-library": "0.1.0",

package json after upgrading versions:

    "storybook": "7.4.6",
    "@storybook/addon-essentials": "7.4.6",
    "@storybook/addon-interactions": "7.4.6",
    "@storybook/addon-links": "7.4.6",
    "@storybook/addon-styling": "1.3.7",
    "@storybook/blocks": "7.4.6",
    "@storybook/react": "7.4.6",
    "@storybook/react-webpack5": "7.4.6",
    "@storybook/testing-library": "0.2.2",

**Comment by vanessayuenn** [comment]
Hi, from the error trace you provided, it looks like your build was cancelled because it hit the disk space limit. You may be able to find resources from [Vercel's docs](https://vercel.com/docs/deployments/troubleshoot-a-build#build-container-resources). Since this is unrelated to Storybook, I will be closing this issue.
