### ISSUE TITLE
[Bug]: Storybook 7 is not adding Named Import styles from Gatsby 5 components that use CSS Modules

### ISSUE THREAD

**Issue by brootle** [storybookjs/storybook#24449]
### Describe the bug

I have a project using Gatsby 5. And followed Gatsby docs here https://www.gatsbyjs.com/docs/how-to/testing/visual-testing-with-storybook/ to install Storybook 7 by running `npx sb init --builder webpack5` which is supposed to add everything I need, right?

But when my component is rendered by Storybook, there are no styles added, no errors anywhere. Styles in my Gatsby 5 components are imported like this `import { style1, style2 } from "./MyComponent.module.css"`

I only get warnings in browser console like this 

```
[HMR] bundle 'preview' has 2 warnings
./src/components/MyComponent.js 28:15-24
export 'style1' (imported as 'style1') was not found in './MyComponent.module.css' (possible exports: default)
./src/components/MyComponent.js 30:17-23
export 'style2 ' (imported as 'style2 ') was not found in './MyComponent.module.css' (possible exports: default)
```

I was trying to find some example repository where Gatsby 5 is used with Storybook 7 to use it as example, but it looks like it doesn't exist in Gatsby examples on GitHub.

### To Reproduce

Install Gatsby 5, add some component with named import styles using css modules, add Storybook 7 following Gatsby 5 docs here https://www.gatsbyjs.com/docs/how-to/testing/visual-testing-with-storybook/ and run Storybook.

### System

```bash
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.1.0 - ~\Desktop\getsby5\node_modules\.bin\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1992.0), Chromium (117.0.2045.47)
  npmPackages:
    @storybook/addon-essentials: ^7.4.6 => 7.4.6
    @storybook/addon-interactions: ^7.4.6 => 7.4.6
    @storybook/addon-links: ^7.4.6 => 7.4.6
    @storybook/addon-onboarding: ^1.0.8 => 1.0.8
    @storybook/addon-styling: ^1.3.7 => 1.3.7
    @storybook/blocks: ^7.4.6 => 7.4.6
    @storybook/react: ^7.4.6 => 7.4.6
    @storybook/react-webpack5: ^7.4.6 => 7.4.6
    @storybook/testing-library: ^0.2.2 => 0.2.2
```

### Additional context

PS As a walk around, I made some styles loader helper function that uses different ways of importing styles based on env variable, so component is rendered as it should when run by Storybook, but this would require a lot of work updating every component in my project. For sure there must be a way to get named styles work in Storybook 7 environment by some settings in `main.js` and `preview.js`

Here is default main.js

```
/** @type { import('@storybook/react-webpack5').StorybookConfig } */
const config = {
  stories: ["../src/**/*.mdx", "../src/**/*.stories.@(js|jsx|mjs|ts|tsx)"],
  addons: [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/addon-onboarding",
    "@storybook/addon-interactions",
  ],
  framework: {
    name: "@storybook/react-webpack5",
    options: {},
  },
  docs: {
    autodocs: "tag",
  },
};
export default config;
```

and preview.js

```
/** @type { import('@storybook/react').Preview } */
const preview = {
  parameters: {
    actions: { argTypesRegex: "^on[A-Z].*" },
    controls: {
      matchers: {
        color: /(background|color)$/i,
        date: /Date$/,
      },
    },
  },
};

export default preview;
```

**Comment by Integrayshaun** [comment]
Hi @brootle 👋 

named exports for css module files needs to be configured in the `css-loader` of your webpack. This can be done with [`@storybook/addon-styling-webpack`](https://storybook.js.org/addons/@storybook/addon-styling-webpack).

By running `npx storybook add @storybook/addon-styling-webpack`, it will kick off a configuration script where you can ask to configure your project for css-modules. From there, set the `namedExport` option to `true` as per the [`css-loader` documentation](@storybook/addon-styling-webpack).

**Comment by brootle** [comment]
@Integrayshaun thanks a lot! it worked like a charm! I have been fighting with main.js config like for 2 days 😎 and I was checking  this page https://storybook.js.org/docs/react/configure/styling-and-css but didn't figure it out anyway, maybe you can update that part of docs with your solution.

**Comment by Integrayshaun** [comment]
@brootle, that's a wonderful idea! I've been trying to think of a structure for more advanced webpack config section to the styling docs. I'll create an issue specifically for that and tag you on it.
