### ISSUE TITLE
[Bug]: storybook update toast can't be closed by the X button if the X button is on top of the border between the panes 

### ISSUE THREAD

**Issue by herzaso** [storybookjs/storybook#24476]
### Describe the bug

The storybook update toast can't be closed by the X button if the X button is on top of the border between the panes - in this situation, the cursor turns to `col-resize` and clicking doesn't do anything

<img width="346" alt="Screenshot 2023-10-15 at 9 17 32" src="https://github.com/storybookjs/storybook/assets/3350658/e7f7da06-f0e7-4560-a325-b3bf0777b7cd">

### System

```bash
Environment Info:

  System:
    OS: macOS 13.6
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 16.19.0 - /private/var/folders/gt/j1n_69cd58q4_8r6n5hpbpjr0000gq/T/xfs-b5c9992f/node
    Yarn: 3.3.1 - /private/var/folders/gt/j1n_69cd58q4_8r6n5hpbpjr0000gq/T/xfs-b5c9992f/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
  Browsers:
    Chrome: 118.0.5993.70
    Safari: 17.0
  npmPackages:
    @storybook/addon-a11y: 7.4.5 => 7.4.5
    @storybook/addon-essentials: 7.4.5 => 7.4.5
    @storybook/addon-interactions: 7.4.5 => 7.4.5
    @storybook/addon-links: 7.4.5 => 7.4.5
    @storybook/addons: 7.4.5 => 7.4.5
    @storybook/blocks: 7.4.5 => 7.4.5
    @storybook/react: 7.4.5 => 7.4.5
    @storybook/react-vite: 7.4.5 => 7.4.5
    @storybook/testing-library: 0.2.1 => 0.2.1
    @storybook/theming: 7.4.5 => 7.4.5
```

**Comment by supriya-2108** [comment]
Hello, I can resolve this issue please assign this bug resolution to me.

**Comment by lalitkumawat1m** [comment]
Hello Team I want to work on this issue please assign to me

**Comment by supriya-2108** [comment]
Hello team please assign this issue to me

**Comment by vanessayuenn** [comment]
@tanmaysinghx @lalitkumawat1m @herzaso please feel free to open a PR that fixes this issue. thanks!

**Comment by aditya028** [comment]
can you add response to reproduce the issue
