### ISSUE TITLE
[Bug]: "Setup controls >" URL cannot be disabled

### ISSUE THREAD

**Issue by hieucd04** [storybookjs/storybook#24475]
### Describe the bug

I followed this guide: https://storybook.js.org/docs/react/essentials/controls#disable-controls-for-specific-properties
... where I explicitly set `control: false` as mentioned there and it works. However, when I hover my mouse over the disabled control a `Setup controls >` URL is displayed.

Currently, at Storybook `7.4.6`, there are no way to disable that behavior (... or my Googling skill isn't good enough?).
That URL appears in production build of Storybook as well (`sb build -o out-dir`) which is pointless from my perspective. How come our clients, who know nothing about coding and only care about the beauty of React components, need to view that URL?

![link](https://github.com/storybookjs/storybook/assets/89077642/3bf704d6-c759-4e0a-ab86-79d17d491e1a)

**Comment by valentinpalkovic** [comment]
@cdedreuille Can you take a look? It seems that "Setup controls" doesn't respect, whether a control field is disabled or not.

**Comment by peschee** [comment]
Using 

```
control: { type: {} }
```

removes the link.

```
control: {
  disable: true,
}
```

does not

**Comment by cdedreuille** [comment]
I confirm that the disable property was not added to the "setup control" link when we added this feature. I'll take this one on to make sure it does.

**Comment by cdedreuille** [comment]
We just talked about this with @kasperpeulen and he is taking over this task.
