### ISSUE TITLE
[Bug]: Compodoc default value for string and number types 

### ISSUE THREAD

**Issue by MurhafSousli** [storybookjs/storybook#24478]
### Describe the bug

I have an angular library, my components inputs has a default value which is set using a global service predefined values.

This is how the generated docs look like:

- The input with string type shows like `this._gallery.config.propName`.
- The input with number type shows `NaN` in the default column.
- The input with boolean type always shows `false` even when the default value is evaluated to true.

![image](https://github.com/storybookjs/storybook/assets/8130692/369eb7fb-5049-4786-a0ec-19c47bfe8395)

I looked at the generated `documentation.json` by compodoc, 

In some places
```
"jsdoctags": [
   // ....
    {
        "name": "behavior",
        "type": "ScrollBehavior",
        "deprecated": false,
        "deprecationMessage": "",
        "defaultValue": "this._config.value.scrollBehavior",
        "tagName": {
            "text": "param"
        }
    }
]
```
in other places
```
  {
      "required": false,
      "name": "slidingDuration",
      "defaultValue": "this._gallery.config.slidingDuration",
      "deprecated": false,
      "deprecationMessage": "",
      "line": 74,
      "type": "number",
      "decorators": []
  },
```

I know this is probably compodoc issue, but I am wondering if you guys have a experienced this or have a workaround?

### To Reproduce

```ts
@Component({
  selector: 'my-cmp',
  template: `<div></div>`
  standalone: true
})
export class GalleryComponent {

  @Input({ transform: numberAttribute }) slidingDuration: number = this._globalService.config.slidingDuration;

  @Input() scrollBehavior: ScrollBehavior = this._globalService.config.scrollBehavior;

  constructor(private _globalService: GlobalService) {
  }
}
```
```ts
@Injectable({
  providedIn: 'root'
})
export class GlobalService {

  /** Global config */
  config: GalleryConfig = {
      slidingDuration: 400,
      scrollBehavior: 'smooth'
  };
  
}
```

### System

```bash
I was unable to execute the command because it asked me to install 7.4.6 and I am using 7.5.0-alpha.5
```

**Comment by valentinpalkovic** [comment]
Compodoc doesn't evaluate any code but just parses it and analyzes the AST representation of it. Storybook is in the same position. I think the only solution is to manually define the default value via argTypes: https://storybook.js.org/docs/angular/api/arg-types

**Comment by MurhafSousli** [comment]
Sounds good, thanks!
