### ISSUE TITLE
[Bug]: Next.js fonts don't apply on docs pages

### ISSUE THREAD

**Issue by Dremora** [storybookjs/storybook#24485]
### Describe the bug

When using a font from `next/font/google`, relevant class names are not applied on docs pages.

### To Reproduce

I've tried creating a reproduction repo using storybook.new, but it's currently broken (swc can't be installed on Stackblitz). I'll try again once it's resolved.

To reproduce, create a Next.js application with one font, and a docs page. The docs page won't have any relevant styles applied, regardless of whether a font was loaded via a CSS variable.

### System

```bash
Environment Info:

  System:
    OS: macOS 13.5.2
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 18.16.0 - ~/.asdf/installs/nodejs/18.16.0/bin/node
    Yarn: 1.22.19 - ~/.asdf/shims/yarn
    npm: 9.5.1 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Chrome: 117.0.5938.149
    Safari: 16.6
  npmPackages:
    @storybook/addon-essentials: 7.4.5 => 7.4.5 
    @storybook/addon-interactions: ^7.4.5 => 7.4.5 
    @storybook/addon-storysource: 7.4.5 => 7.4.5 
    @storybook/addons: 7.4.5 => 7.4.5 
    @storybook/blocks: ^7.4.5 => 7.4.5 
    @storybook/builder-webpack5: 7.4.5 => 7.4.5 
    @storybook/cli: 7.4.5 => 7.4.5 
    @storybook/core-server: 7.4.5 => 7.4.5 
    @storybook/jest: ^0.1.0 => 0.1.0 
    @storybook/nextjs: ^7.4.5 => 7.4.5 
    @storybook/react: 7.4.5 => 7.4.5 
    @storybook/testing-library: ^0.2.1 => 0.2.1 
    @storybook/theming: ^7.4.5 => 7.4.5 
    @storybook/types: ^7.4.5 => 7.4.5 
```
```


### Additional context

_No response_

**Comment by valentinpalkovic** [comment]
Hi @Dremora 

Thank you for reporting this!

Can you share a reproduction link to a repo? It is hard to figure out the issue without a concrete example.

**Comment by akshayw1** [comment]
Can I work on this please assign

**Comment by Dremora** [comment]
Same as #24484 - Storybook only loads fonts but doesn't apply any class names. It can't do this since it doesn't know how exactly fonts are going to be used.
