### ISSUE TITLE
[Bug]: Storybook 7.5.0 is not supporting a next.js 11.1.4 version

### ISSUE THREAD

**Issue by VidyaGouda17** [storybookjs/storybook#24503]
### Describe the bug

next.js : 11.1.4
storybook: ^7.5.0 
Getting an error => 
Failed to build the preview
Error: Cannot find module 'next/dist/shared/lib/app-router-context'
Require stack:
- .\node_modules\@storybook\nextjs\dist\preset.js
- .\node_modules\@storybook\nextjs\preset.js
- .\node_modules\@storybook\core-common\dist\index.js
- .\node_modules\@storybook\telemetry\dist\index.js
- .\node_modules\@storybook\cli\dist\generate.js
- .\node_modules\@storybook\cli\bin\index.js
- .\node_modules\storybook\index.js

**Comment by valentinpalkovic** [comment]
Hi @VidyaGouda17 

The @storybook/next 7.x framework does not support Next.js < 12 officially(https://github.com/storybookjs/storybook/blob/next/code/frameworks/nextjs/README.md#getting-started see requirements). Therefore we are not maintaining Next.js 11 anymore. Please try to upgrade to Next.js 12 or above.
