### ISSUE TITLE
[Bug]: Start Storybook get stuck when using a node_module from workspace as workspace:*

### ISSUE THREAD

**Issue by Lakshya-Poddar** [storybookjs/storybook#24517]
### Describe the bug

Starting Storybook with a versioned package runs totally fine but with the same package as workspace:* gets stuck at 42%. On checking network tab it shows iframe.html's status code as pending. 

<img width="456" alt="Screenshot 2023-10-19 at 5 16 26 PM" src="https://github.com/storybookjs/storybook/assets/43548762/73c38df3-f311-420e-884e-b7ab6acffde0"> 

### System

```bash
Environment Info:

  System:
    OS: macOS 14.0
    CPU: (8) arm64 Apple M2
  Binaries:
    Node: 18.4.0 - ~/.nvm/versions/node/v18.4.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.4.0/bin/yarn
    npm: 8.12.1 - ~/.nvm/versions/node/v18.4.0/bin/npm
  Browsers:
    Chrome: 118.0.5993.88
    Safari: 17.0
  npmPackages:
    @storybook/addon-a11y: 7.0.22 => 7.0.22 
    @storybook/addon-essentials: 7.0.18 => 7.0.18 
    @storybook/addon-interactions: 7.0.18 => 7.0.18 
    @storybook/addon-links: 7.0.18 => 7.0.18 
    @storybook/blocks: 7.0.18 => 7.0.18 
    @storybook/jest: 0.0.10 => 0.0.10 
    @storybook/react: 7.0.18 => 7.0.18 
    @storybook/test-runner: 0.9.4 => 0.9.4 
    @storybook/testing-library: 0.0.14-next.2 => 0.0.14-next.2
```

**Comment by vanessayuenn** [comment]
Hi, thanks for reporting this. do you have a reproduction repo you can share? If not, can you create one (see [how to create a repro](https://storybook.js.org/docs/react/contribute/how-to-reproduce)). We prioritize bug reports that have reproduction. Thank you! 🙏
