### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by DilipGtcsys** [storybookjs/storybook#24515]
### Describe the bug

Module build failed (from ./node_modules/ts-loader/index.js):

**Comment by valentinpalkovic** [comment]
Unfortunately, this issue is not helpful. Please provide some context as required via issue template and provide a reproduction if possible.

**Comment by vanessayuenn** [comment]
Closing this issue since it lacks information to be actionable. Please feel free to open a new issue with relevant information, thank you.
