### ISSUE TITLE
[Bug]: Disabling addons with `paramKey` doesn't work

### ISSUE THREAD

**Issue by Jeff-DS** [storybookjs/storybook#24539]
### Describe the bug

Disabling an addon panel with its `paramKey` doesn't work. The addon panel should be disabled when  `{ [PARAM_KEY]: { disable: true }` is set in `parameters` at the story, component, or global level (where the value of `PARAM_KEY` is provided as `paramKey` when registering the addon panel).

### To Reproduce

These steps will reproduce the bug for the component level. To reproduce at the story or global level, make the change described in step 3 in the `parameters` object for an individual story or in `.storybook/preview.ts`.

1. Set up [`addon-kit`](https://github.com/storybookjs/addon-kit/): follow the instructions under "Getting Started" and then run `npx storybook@latest upgrade` to upgrade the Storybook version.
2. In `manager.ts`, import `PARAM_KEY` from `constants` and add `paramKey: PARAM_KEY,` to the object passed to the `addons.add` call used to register the panel.
3. In `Buttons.stories.ts`, import `PARAM_KEY`, comment out the `myAddonParameter` key-value pair in `meta.parameters`, and add `[PARAM_KEY]: { disable: true },`.
4. Start the demo with `yarn start`.
5. In the browser, go to the story `Button` > `Primary`.
6. The "My addon" tab still appears in the addons panel.
7. Multiple instances of the following warning appear in the console when navigating to a story for which the addon should be disabled: `Warning: The final argument passed to useMemo changed size between renders. The order and size of this array must remain constant.` The warning shows an array of addon names where `"storybook/my-addon/panel"` appears more than once and is added/removed between renders.

### System

```bash
Storybook Environment Info:

  System:
    OS: macOS 12.6.8
    CPU: (4) x64 Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.18.2/bin/yarn <----- active
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm
  Browsers:
    Chrome: 115.0.5790.170
    Safari: 16.6
  npmPackages:
    @storybook/addon-essentials: ^7.5.1 => 7.5.1 
    @storybook/addon-interactions: ^7.5.1 => 7.5.1 
    @storybook/addon-links: ^7.5.1 => 7.5.1 
    @storybook/react: ^7.5.1 => 7.5.1 
    @storybook/react-vite: ^7.5.1 => 7.5.1 
    @storybook/testing-library: ^0.2.2 => 0.2.2 
    storybook: ^7.5.1 => 7.5.1
```

### Expected behavior

When an addon panel's `paramKey` is used to disable the addon in the story, component or storybook parameters, the tab for the addon panel should not appear (following normal parameter cascading rules). No warning should appear in the console.

Documentation: https://storybook.js.org/docs/react/addons/addon-knowledge-base#disable-the-addon-panel

As far as I can tell, the documentation doesn't explicitly state that this functionality is intended to be available on the component, story, and global level, but it's implied by the way parameter cascading works, and confirmed by this comment: https://github.com/storybookjs/storybook/issues/16822#issuecomment-1008530176

> You can disable addon-a11y for a story, component, or globally, by setting this parameter
> 
> ``` a11y: { disable: true }```
> 
> More info on parameters https://storybook.js.org/docs/react/writing-stories/parameters

### Environment

 - OS: macOS Monterey 12.6.8
 - Node.js version: v18.18.2
 - NPM version: 9.8.1
 - Yarn version: 1.22.19
 - Browser: Chrome
 - Device: MacBook Pro

**Comment by rahimny** [comment]
Also experiencing this issue to on storybook v7.5.1

**Comment by yannbf** [comment]
Hey everyone! This issue has been fixed in Storybook 8. Here's the example from addon-kit using Storybook 8, with the parameter working and no errors in console:
![2024-02-01 11 01 11](https://github.com/storybookjs/storybook/assets/1671563/15f24c07-fb0e-41fc-9c26-fdecde3572a2)

We just released a beta, please consider upgrading your project and using it. Feedback is appreciated 🙏

```
npx storybook@next upgrade
```
