### ISSUE TITLE
Investigate upgrading monorepo to Yarn 4

### ISSUE THREAD

**Issue by vanessayuenn** [storybookjs/storybook#24552]
```[tasklist]
### Tasks
- [ ] Does yarn pnp still work? We are using @yarnpkg/fslib to support pnp
```

## Pnp Support

As of https://github.com/yarnpkg/berry/blob/master/CHANGELOG.md#api-changes, there are changes regarding the pnp API. In the past, we already tried out the release candidate v4.x of @yarnpkg/libzip, which dropped Node v.16 support. This was the reason to roll back to v3. We should verify whether [our implementation](https://github.com/storybookjs/storybook/blob/next/code/lib/cli/src/js-package-manager/Yarn2Proxy.ts#L130) of pnp support still works with yarn v4.

**Comment by JReinhold** [comment]
I've tested mealdrop with Yarn PnP both in v3 and v4, and they seem to behave identical, with the same errors.

Both cases errors with package dependencies missing so I had to manually add them and then it "worked".

So this is still not perfect but it seems like nothing has changed between v3 and v4.

- Migrating Yarn v3 to PnP: https://github.com/JReinhold/mealdrop/commit/66280e7731a147819327e9ba2a9711577b0d5df7
- Migrating Yarn v4 to PnP: https://github.com/JReinhold/mealdrop/commit/3933178cbdb7be363da056d908f8eb9345d9db21
