### ISSUE TITLE
[Documentation]: Suggestion: `storybook-addon-themes` for Storybook 7

### ISSUE THREAD

**Issue by palamarchukser** [storybookjs/storybook#24562]
### Describe the problem

after migration from 7.0.26 to 7.5.1 getting next errors:
```
export 'codeCommon' (imported as 'codeCommon') was not found in '@storybook/components'
export 'IconButtonSkeleton' (imported as 'IconButtonSkeleton') was not found in '@storybook/components'
export 'ErrorFormatter' (imported as 'ErrorFormatter') was not found in '@storybook/components'
...
```
<img width="976" alt="image" src="https://github.com/storybookjs/storybook/assets/10272176/d4eda990-ef28-44ac-95a9-27405ae97433">

As it turned out, the problem was related to `"storybook-addon-themes": "^6.1.0"`

The problem has already been solved, so I’m just wondering if there is a description somewhere in the docs for migrating to Storybook 7 in cases where this module is used?
if not, pehaps it might be useful to add it to automigration or at least to the docs

**Comment by lalitkumawat1m** [comment]
Hello Team I want to work on this issue please assign to me

**Comment by yannbf** [comment]
cc @Integrayshaun

**Comment by Integrayshaun** [comment]
Hey @palamarchukser,

`storybook-addon-themes` is a community addon so we have no control over getting it updated to Storybook 7. There is an [open issue](https://github.com/tonai/storybook-addon-themes/issues/79) on the repo however the maintainer said that can't upgrade it right now. 

However, we recently released a theme switcher addon of our own that you could use instead called [`@storybook/addon-themes`](https://storybook.js.org/addons/@storybook/addon-themes/)
