### ISSUE TITLE
[Bug]: angular new-storybook.netlify.app is broken

### ISSUE THREAD

**Issue by AngularIsAwfull** [storybookjs/storybook#24567]
### Describe the bug

I can't open new angular storybook issue because [storybook.new](https://storybook.new/) is broken. 
<img width="2560" alt="screenshot24-10-2023" src="https://github.com/storybookjs/storybook/assets/144009554/7d951186-5cbb-44b2-a555-78c3e434018a">

### To Reproduce

(https://stackblitz.com/github/storybookjs/sandboxes/tree/next/angular-cli/default-ts/after-storybook?file=README.md&preset=node)

### System

```bash
Storybook Environment Info:

  System:
    OS: Linux 5.0 undefined
    CPU: (6) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm <----- active
    pnpm: 8.9.2 - /usr/local/bin/pnpm
```

**Comment by valentinpalkovic** [comment]
[This seems to be an issue](https://github.com/swc-project/swc/pull/8112#issuecomment-1764805924) of `@swc` not providing a package for `@swc/wasm` for newer versions than 1.3.92

**Comment by kdy1** [comment]
Hmm seems like a bug of publish script I use

**Comment by kdy1** [comment]
https://github.com/swc-project/swc/actions/runs/6626186653 will fix it

**Comment by valentinpalkovic** [comment]
The issue is resolved! Thanks @kdy1, for the fast fix and reply.
