### ISSUE TITLE
[Bug]: Local npm packages don`t work

### ISSUE THREAD

**Issue by vaseklllM** [storybookjs/storybook#24579]
### Describe the bug

If I use useState in @components/section-row I get an error.
I get this error only if I use storybook.

<img width="628" alt="Знімок екрана 2023-10-25 о 4 52 08 пп" src="https://github.com/storybookjs/storybook/assets/40796564/00adbbfc-e66e-4d35-bbc0-2eb5438e4713">

<img width="649" alt="Знімок екрана 2023-10-25 о 4 57 08 пп" src="https://github.com/storybookjs/storybook/assets/40796564/c9047ae5-480f-4a27-8c47-fd28b7c94edf">

**Comment by shilman** [comment]
Do you a have a reproduction repo you can share? If not, can you create one? Go to https://storybook.new or see [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce). Thank you! 🙏
