### ISSUE TITLE
[Bug]: Support for Nextjs 14 is required

### ISSUE THREAD

**Issue by dincerpece** [storybookjs/storybook#24589]
### Describe the bug

Next JS 14 was introduced today and I upgraded the version to 14, but I think nextJS14 is not supported as per the requirements. When is it updated?

![Screenshot_5](https://github.com/storybookjs/storybook/assets/57527680/2848fb23-331a-4c8a-9d94-1acc774511df)

**Comment by TheMikeyRoss** [comment]
@valentinpalkovic Welcome back king. Could we accelerate this 👆

**Comment by TheMikeyRoss** [comment]
Thanks @valentinpalkovic  @nikospapcom ♥
