### ISSUE TITLE
[Bug]:  Why `couldn't fulfill desired order of chunk group(s)`?

### ISSUE THREAD

**Issue by world-visitors** [storybookjs/storybook#24594]
### Describe the bug

WARN    - while fulfilling desired order of chunk group(s) stories-Avatars-Avatar-stories, stories-Avatars-Avatar-stories-tsx
WARN  * css ./node_modules/react-scripts/node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[3].oneOf[8].use[1]!./node_modules/react-scripts/node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[3].oneOf[8].use[2]!./node_modules/resolve-url-loader/index.js??ruleSet[1].rules[3].oneOf[8].use[3]!./node_modules/react-scripts/node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[3].oneOf[8].use[4]!./src/Components/Contacts/ContactsDropdown/style.module.scss
WARN    - couldn't fulfill desired order of chunk group(s) stories-Contacts-ContactsDialog-stories, stories-Contacts-ContactsDialog-stories-tsx

So, what should I do to solve this problem?

**Comment by vanessayuenn** [comment]
Hi, thanks for reporting this. do you have a reproduction repo you can share? If not, can you create one (see [how to create a repro](https://storybook.js.org/docs/react/contribute/how-to-reproduce)). We prioritize bug reports that have reproduction. Thank you! 🙏

**Comment by daviddelusenet** [comment]
@world-visitors did you ever manage to fix this? Running into a similar issue in a monorepo where I try to load stories from multiple workspaces into one Storybook configuration
