### ISSUE TITLE
[Bug]: Webpack fails to compile with `Module parse failed: Unexpected token (3:1051)`

### ISSUE THREAD

**Issue by JReinhold** [storybookjs/storybook#24591]
**UPDATE**: We are waiting for an upstream fix at https://github.com/acornjs/acorn/issues/1253. In the meantime, the temporary workaround for this is to pin `acorn` in your `package.json`.

### Workaround

Use npm overrides/yarn resolutions to pin `acorn` to `8.10.0` (in `package.json`):

**npm:**
```json
  "overrides": {
    "acorn": "8.10.0"
  }
```

**yarn:**
```json
  "resolutions": {
     "acorn": "8.10.0"
   }
```

---

### Describe the bug

Within the past few hours seemingly all - upgraded - Webpack-based projects are failing with this error:

```
You may need an additional loader to handle the result of these loaders.
|             alias: "important",
|             inside: {
>               punctuation: /==+$|--+$/
|             }
|           }, {
```

```
File was processed with these loaders:
 * ./node_modules/@angular-devkit/build-angular/src/tools/babel/webpack-loader.js
You may need an additional loader to handle the result of these loaders.
|           },
|           arrow: {
>             pattern: /=>/,
|             alias: "operator"
|           }
```

Investigation suggest this is due to the release of `acorn@8.11.0` which happened [a few hours ago](https://www.npmjs.com/package/acorn?activeTab=versions): - There is a (non-storybook) reproduction here: https://github.com/acornjs/acorn/issues/1253

Upgrading Storybook or clearing your lock file could cause this.

### To Reproduce

Any Webpack-based sandbox (+Angular and Next.js) can reproduce this problem. Also clearing the lock file of an existing project (causing transitive dependencies to upgrade) will reproduce this. I've been able to reproduce this in a Storybook 7.1.1 project by just upgrading Webpack from `5.88.2` to `5.89.0`, not upgrading any of the Storybook dependencies.

### Additional context

This CI run shows the error: https://app.circleci.com/pipelines/github/storybookjs/storybook/62040/workflows/714253a5-5f50-4ab3-a47c-439ec9ae04c6/jobs/589782

**Comment by JReinhold** [comment]
This is an older create-react-app project running Storybook `7.1.1` and Webpack `5.88.2`: 

https://github.com/JReinhold/storybook-24591

- The `main` branch works fine, no dependencies have been upgraded yet: https://github.com/JReinhold/storybook-24591/tree/main
- The `upgrade-webpack` branch only upgrades Webpack from `5.88.2` to `5.89.0`, and that alone causes the failure: https://github.com/JReinhold/storybook-24591/tree/upgrade-webpack
- The `pin-acorn` branch pins `acorn` to `8.10.0`, which makes the issue go away: https://github.com/JReinhold/storybook-24591/tree/pin-acorn

**Comment by valentinpalkovic** [comment]
Linking the issue at acorn's issue tracker for reference: https://github.com/acornjs/acorn/issues/1253

**Comment by tmeasday** [comment]
This is an issue with `acorn@8.11.x`. For now pinning `acorn@8.10.x` is probably the best workaround.

**Comment by valentinpalkovic** [comment]
Issue is resolved: https://github.com/acornjs/acorn/issues/1253#issuecomment-1782480979

Please upgrade acorn from `8.11.x` to `8.11.2`.
