### ISSUE TITLE
[Bug]: iframe.html incorrect embedding ejs

### ISSUE THREAD

**Issue by CyberDoge** [storybookjs/storybook#24608]
### Describe the bug

file `.storybook/main.ts`
```
import type {StorybookConfig} from '@storybook/react-webpack5';
import paths from '../config/paths';

const config: StorybookConfig = {
  stories: ['../src/**/*.mdx', '../src/**/*.stories.@(js|jsx|mjs|ts|tsx)'],
  addons: ['@storybook/addon-links', '@storybook/addon-essentials', '@storybook/addon-onboarding', '@storybook/addon-interactions',],
  framework: {
    name: '@storybook/react-webpack5', options: {},
  },
  webpackFinal: (config) => {
    config.resolve?.modules?.push(paths.appSrc);
    return {
      ...config, module: {
        ...config.module, rules: [{
          exclude: [/^$/, /\.(js|mjs|jsx|ts|tsx)$/, /\.html$/, /\.json$/], type: 'asset/resource',
        }, ...config.module?.rules ?? []]
      },
    };
  },
  docs: {
    autodocs: 'tag',
  },
};
export default config;

```
Generates iframe.html with such content

<img width="360" alt="screen capture 2023-10-30 в 10 13 44" src="https://github.com/storybookjs/storybook/assets/36932153/c56e9415-7f3e-464a-ab2d-8443cce09dfd">

### System

```bash
dependencies:
    "@babel/core": "^7.16.0",
    "@babel/preset-env": "^7.23.2",
    "@babel/preset-react": "^7.22.15",
    "@babel/preset-typescript": "^7.23.2",
    "@pmmmwh/react-refresh-webpack-plugin": "^0.5.3",
    "@storybook/addon-actions": "^7.5.1",
    "@storybook/addon-essentials": "^7.5.1",
    "@storybook/addon-interactions": "^7.5.1",
    "@storybook/addon-links": "^7.5.1",
    "@storybook/addon-onboarding": "^1.0.8",
    "@storybook/blocks": "^7.5.1",
    "@storybook/builder-webpack5": "^7.5.1",
    "@storybook/manager-webpack5": "^6.5.16",
    "@storybook/react": "^7.5.1",
    "@storybook/react-webpack5": "^7.5.1",
    "@storybook/testing-library": "^0.2.2",
    "storybook": "^7.5.1",
    "webpack": "^5.88.2"
```

**Comment by vanessayuenn** [comment]
Hi, thanks for reporting this. do you have a reproduction repo you can share? If not, can you create one (see [how to create a repro](https://storybook.js.org/docs/react/contribute/how-to-reproduce)). We prioritize bug reports that have reproduction. Thank you! 🙏

**Comment by vathsav** [comment]
@CyberDoge, it looks like you've ejected CRA with Webpack 5 and tried to configure Storybook with the custom webpack config. I'd run into the same issue.

With full control, according to the [docs](https://storybook.js.org/docs/builders/webpack#working-with-webpack-plugins), you should do the following:

> Additionally, when working with Webpack loaders that don't explicitly include specific file extensions (i.e., via the test property), you should exclude the .ejs file extension for that loader.

Search for `type: 'asset/resource'` in `webpack.config.js` and update its `exclude` rule to this:

```
exclude: [
  /^$/,
  /\.(js|mjs|jsx|ts|tsx)$/,
  /\.html$/,
  /\.json$/,
  /\.(ejs|md|mdx|cjs)$/  // <-- .ejs was missing here
],
```

If you run into further issues, you can compare your pre-ejected webpack config against your ejected webpack config using the [`--debug-webpack`](https://storybook.js.org/docs/builders/webpack#debug-webpack-configuration) flag to look for anything sus.
