### ISSUE TITLE
[Bug]: Sidebar content is hidden if the content is too big horizontally

### ISSUE THREAD

**Issue by cdedreuille** [storybookjs/storybook#24626]
### Describe the bug

In Storybook 8.0, the sidebar content is cropped and not horizontally accessible if the content of the sidebar is too big. As you can see in the picture, the search bar is cropped and you can't even access the settings anymore.

![CleanShot 2023-10-31 at 09 10 10@2x](https://github.com/storybookjs/storybook/assets/1540635/15a97d12-0471-428a-9db8-90ef7208876c)

### To Reproduce

1. Set your branch to be on `release-8-0`
2. Go to http://localhost:6006/?path=/story/blocks-blocks-canvas--parameter-story
3. You should now see the sidebar cropped on the left when the content is too small

**Comment by JReinhold** [comment]
This happens in extreme egde cases where the story names/titles contain really long words that the browser don't want to break on. In this example it's `parameters.docs.canvas.additionalActions` being considered a single non-breakable word.

Other stories with long titles/names but consisting of many breakable words seems to work fine, such as this one: https://release-8-0--635781f3500dd2c49e189caf.chromatic.com/?path=/story/manager-notifications-notificationitem--accessibility-gold-icon-long-head-line-no-sub-headline

We could add `word-break: break-word` to the sidebar entries, which will make it behave like this:

https://github.com/storybookjs/storybook/assets/5678122/8cdfba29-fb2b-4bd0-a2aa-83eef7a80b9f

**Comment by valentinpalkovic** [comment]
Fixed by https://github.com/storybookjs/storybook/pull/24707
