### ISSUE TITLE
[Bug]: Getting "Ad Removed" error on iframe on storybook

### ISSUE THREAD

**Issue by ShastrakarAkshay** [storybookjs/storybook#24631]
### Describe the bug

Hello,

When we loads storybook app first time, i get "Ad removed" error on iframe.
When i search for this error on internet, it is telling that page uses too many resources thats why it is blocking iframe and chrome is considering it is ad.

Is there any way to reduce page reload or size of the bundles. 
Can we minify js files?

Please provide solution on this?

**Comment by vanessayuenn** [comment]
Hi, thanks for reporting this. do you have a reproduction repo you can share? If not, can you create one (see [how to create a repro](https://storybook.js.org/docs/react/contribute/how-to-reproduce)). We prioritize bug reports that have reproduction. Thank you! 🙏
