### ISSUE TITLE
[Bug]: Storybook 7 Code block performance 

### ISSUE THREAD

**Issue by victor-move** [storybookjs/storybook#24643]
### Describe the bug

During the upgrade to Storybook 7,  our team has noticed a massive performance degradation on loading doc pages. The worst offender went from `3.8s` to `30+s` TTI. After investigating, I found that pages with 15+ code blocks tend to hang, regardless of how many stories or other elements are included. Running an isolated test with just code blocks, every additional block adds additional loading time.

### To Reproduce

This can be easily replicated using either the Storybook Code block or the markdown code blocks. Create a doc page using 40 code blocks and observe the increased loading time.  This occurs regardless of if you have a language specified for highlighting in markdown (i.e: \`\`\`jsx and \`\`\` perform the same).

### System

```bash
Environment Info:

  System:
    OS: macOS 11.7.10
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Binaries:
    Node: 16.11.1 - /usr/local/bin/node
    Yarn: 3.2.2 - /usr/local/bin/yarn
    npm: 8.0.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 118.0.5993.117
    Edge: 118.0.2088.76
    Safari: 16.6.1
  npmPackages:
    @storybook/addon-a11y: ^7.4.5 => 7.4.5
    @storybook/addon-console: ^2.0.0 => 2.0.0
    @storybook/addon-essentials: ^7.4.5 => 7.4.5
    @storybook/addon-mdx-gfm: ^7.4.5 => 7.4.5
    @storybook/addon-storysource: ^7.4.5 => 7.4.5
    @storybook/react: ^7.4.5 => 7.4.5
    @storybook/react-webpack5: ^7.4.5 => 7.4.5
```

### Additional context

n/a

**Comment by valentinpalkovic** [comment]
cc @ndelangen, @kasperpeulen might be pretty relevant for your current work regarding performance analysis

**Comment by kasperpeulen** [comment]
Hmm @shilman @JReinhold might also be related to the syntax highlighter?

**Comment by victor-move** [comment]
> Hmm @shilman @JReinhold might also be related to the syntax highlighter?

One thing I didn't note in the initial report that I should have- it takes the same exact time to load regardless of if you have a language specified for highlighting in markdown (i.e: ```jsx and ``` perform the same).

**Comment by shilman** [comment]
Do you a have a reproduction repo you can share? If not, can you create one? Go to https://storybook.new or see [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce). Thank you! 🙏

**Comment by victor-move** [comment]
Follow up on this, it seems like upgrading from `7.4.6` to `7.5.3` resolved this issue in our project. Though at the same time, the reproduction repo created in `7.4.6` did not seem to have this issue. So I'm guessing it was an esoteric combination of things on our side that caused this. 

In any case this isn't an issue anymore so I'll close!
