### ISSUE TITLE
[Bug]: `brandImage` resizes itself in wrong circumstances

### ISSUE THREAD

**Issue by emlai** [storybookjs/storybook#24702]
### Describe the bug

1. The `brandImage` logo changes size based on which sidebar item is selected:

https://github.com/storybookjs/storybook/assets/7543552/bbd38745-1ed7-4a4d-8ccd-67956ce67712

2. The logo becomes larger than intended when resizing the sidebar (looks especially bad when the logo becomes gigantic this way).

https://github.com/storybookjs/storybook/assets/7543552/625eb925-9b2d-4b28-8742-f3bf838d3c5c

 I think the logo should stay the original intended size at all times.

### To Reproduce

The sidebar has to resized to its minimum width for 1 to reproduce.

### System

```bash
System:
    OS: macOS 13.5
    CPU: (12) arm64 Apple M2 Pro
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.8.1 - /opt/homebrew/bin/node
    npm: 10.1.0 - /opt/homebrew/bin/npm
    pnpm: 8.6.8 - /opt/homebrew/bin/pnpm <----- active
  Browsers:
    Chrome: 118.0.5993.117
    Safari: 16.6
```

**Comment by black-arm** [comment]
Can I Have this issue?
