### ISSUE TITLE
[Bug]: Package target not found

### ISSUE THREAD

**Issue by Henry-Chung1119** [storybookjs/storybook#24715]
### Describe the bug

Running 'npx storybook@latest init' in react environment but having the following error:

npm ERR! code ETARGET
npm ERR! notarget No matching version found for @storybook/instrumenter@7.5.2.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

also checked 'npm view @storybook/instrumenter versions' and found out there is no version 7.5.2 in the list
but it shows that version 7.5.2 has been published a few days ago 
[https://www.npmjs.com/package/@storybook/instrumenter?activeTab=readme](https://www.npmjs.com/package/@storybook/instrumenter?activeTab=readme)

not sure why...

my npm version is 10.2.1

**Comment by shilman** [comment]
Closing this as an npm issue
