### ISSUE TITLE
[Bug]: Multi-line codeblocks not working in MDX files

### ISSUE THREAD

**Issue by IPWright83** [storybookjs/storybook#24729]
### Describe the bug

Using multi-line code blocks within an MDX file (by way of 3 back ticks) does not format correctly as code. So the following:

```
This is some
code
```

Would not look correct. This is in an existing repository with Storybook that has been upgraded. If I downgrade to Storybook 7.2.0 then everything works as expected. The output looks as follows

**7.4.0 -> 7.5.2**
![image](https://github.com/storybookjs/storybook/assets/1374775/303e4718-10d0-4c1a-9fef-51e917a67c92)

**7.2.0 (and below)**
![image](https://github.com/storybookjs/storybook/assets/1374775/ac425abe-9923-42ff-b200-40ccfad209a6)

### To Reproduce

I have been unable to create a small standalone example despite several attempts. This seems to be work fine in a brand new project with Storybook. If I copy over all the configuration from `main.ts` and match the same dependencies however it still appears broken in my project.

Therefore the easiest reproduction at the moment is:
```
git clone https://github.com/IPWright83/chart-io
git checkout upgrade-storybook
```

Manually update the `/packages/react/package.json` Storybook which can be done using a find and replace on `"7.2.0"` to `"7.5.2"`.

```
pnpm install
pnpm storybook
```

Then open `http://localhost:6006/?path=/docs/getting-started--docs` in a browser. You will see the incorrectly rendered code block.

### System

```bash
Storybook Environment Info:

  System:
    OS: Linux 6.2 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (12) x64 AMD Ryzen 5 3600X 6-Core Processor
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.2.0 - ~/.nvm/versions/node/v20.2.0/bin/node
    Yarn: 1.22.11 - /usr/bin/yarn
    npm: 9.6.6 - ~/.nvm/versions/node/v20.2.0/bin/npm
    pnpm: 8.10.2 - ~/.local/share/pnpm/pnpm <----- active
  Browsers:
    Chrome: 119.0.6045.105
  npmPackages:
    chromatic: ^6.17.0 => 6.24.1 
```
```


### Additional context

This problem was introduced between versions `7.2.0` and `7.4.0` (unfortunately `7.3.0` doesn't load for me so I can't test).

**Comment by BrotaOne** [comment]
I also have the problem, run the following command to reproduce

1. using vite to initialize a react project
2. initialize storybook by execute `pnpm dlx storybook@latest init`
3. add a file named 'Button.mdx' in stories


import {Meta} from '@storybook/blocks';

<Meta title="Button" />

```
console.log(123);
```

**Comment by pedaars** [comment]
@BrotaOne Can you try 
```js
console.log(123;
```

**Comment by IPWright83** [comment]
I've tried add `jsx` after the backticks @pedaars and that didn't help me

**Comment by pedaars** [comment]
hmm thats strange so i have this in my mdx file 

![Screenshot 2023-11-09 at 20 53 02](https://github.com/storybookjs/storybook/assets/11647950/96942dd8-535b-45e3-8159-c584451cf645)

which outputs this in storybook

![Screenshot 2023-11-09 at 20 52 55](https://github.com/storybookjs/storybook/assets/11647950/accb7201-431b-4870-8ee4-4eb4c4cb3bba)

**Comment by BrotaOne** [comment]
> thats strange so i have this in my mdx file

it doesn't work for me

<img width="535" alt="image" src="https://github.com/storybookjs/storybook/assets/30154715/02ed41a4-05b4-4b8c-b093-b556b72c4651">

<img width="405" alt="image" src="https://github.com/storybookjs/storybook/assets/30154715/4d4d6d31-9f11-4107-894c-546de79b1398">

**Comment by floroz** [comment]
Confirming this bug when upgrading from `7.2.0` to `7.5.3`.

**7.2.0**

![Screenshot 2023-11-28 at 12 23 35](https://github.com/storybookjs/storybook/assets/45793869/91de252a-5961-46d4-ae59-acd34d743812)


**7.5.3**

![Screenshot 2023-11-28 at 12 23 43](https://github.com/storybookjs/storybook/assets/45793869/6e2662c6-7902-420f-b3ec-61eaf082dd44)

**Comment by shilman** [comment]
I have not been able to reproduce based on any of the comments above. Does anybody have a minimal reproduction repo you can share? If not, can you create one? Go to https://storybook.new or see [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce). Thank you! 🙏

**Comment by IPWright83** [comment]
@shilman I've been unable to reproduce in a small standalone project, but this affects my upgraded project (reproduction included in the original issue - if that doesn't work let me know). I don't understand what the differences are between my project and a small attempt at reproducing unfortunately.

As @floroz mentioned, it seems to only affect development mode.

**Comment by shilman** [comment]
@IPWright83 Can you check your repro steps again? I don't remember what error I ran into but in believe the branch you mention no longer exists. Happy to give it another try--seems to be affecting various projects and would be good to get to the bottom of it

**Comment by floroz** [comment]
@shilman I can confirm the same issue as @IPWright83 .

I tried to put together a repro but could not reproduce it. However, on my project (large-sized Vue component library) the issue persists.

I am going to share the settings from my project in the hope it can help with the debugging:

- Storybook v7.5.3
- main.ts file below

```ts
import type { StorybookConfig } from "@storybook/vue3-vite";
import { mergeConfig } from "vite";
const config: StorybookConfig = {
  stories: [
    "../src/**/*.mdx",
    "../docs/**/*.mdx",
    "../src/**/*.stories.@(js|jsx|ts|tsx)",
  ],
  addons: [
    "@storybook/addon-a11y",
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/addon-interactions",
    "@storybook/addon-mdx-gfm",
    "@etchteam/storybook-addon-status",
  ],
  core: {
    disableTelemetry: true,
  },
  framework: {
    name: "@storybook/vue3-vite",
    options: {},
  },
  docs: {
    autodocs: "tag",
  },
  staticDirs: ["./assets"],
  typescript: {
    check: false,
  },
  async viteFinal(viteConfig) {
    return mergeConfig(viteConfig, {
      define: {
        "process.env": {},
      },
    });
  },
};
export default config;
```

**Comment by IPWright83** [comment]
Sorry @shilman - not sure how I managed to remove the branch. I've added a new branch with a reproduction here https://github.com/IPWright83/chart-io/tree/upgrade-storybook

**Comment by viliusmileris** [comment]
I had "@mdx-js/react" in my devDependencies, and it turned out to be causing issues with rendering tables in MDX. The issue was resolved by removing "@mdx-js/react".

**Comment by IPWright83** [comment]
Can this be re-opened? A reproduction was provided....
