### ISSUE TITLE
[Bug]: migrate csf-2-to-3 badly wraps `Story` components.

### ISSUE THREAD

**Issue by mctrafik** [storybookjs/storybook#24736]
### Describe the bug

Tried running `npx sb@next migrate csf-2-to-3` today. 

It did things like:
![Screenshot 2023-11-06 at 11 19 23 AM](https://github.com/storybookjs/storybook/assets/1694347/1c7a2911-c6a8-4c64-af19-6b377e0b4b6c)
which creates a function that isn't recognized as a react component.

See:
![Screenshot 2023-11-06 at 11 19 43 AM](https://github.com/storybookjs/storybook/assets/1694347/2f9904b2-0bb4-4c34-b2d4-a49a24f9a793)

**Comment by shilman** [comment]
closing as dupe to https://github.com/storybookjs/storybook/issues/21115
