### ISSUE TITLE
[Bug]: Storybook broken on Nuxt 3 w/ vite

### ISSUE THREAD

**Issue by bmulholland** [storybookjs/storybook#24746]
### Describe the bug

On Nuxt 3 (for me, any version of Nuxt 3 and Storybook), the stories all crash with obscure errors. Root cause looks like the code is getting double-compiled by Vite. Daniel has dug in and diagnosed the issue to code in this repo. Full description linked here:

https://github.com/nuxt-modules/storybook/issues/428#issuecomment-1794448129

### To Reproduce

Use Nuxt 3 (any version with yarn, perhaps only <3.7 on other package managers? Hard to tell). 

Here's one repro (open the Test component -- needs to be something rendered by Nuxt):
https://stackblitz.com/edit/nuxt-starter-qm9s4q?file=components%2FTest.vue,stories%2FTest.stories.ts

**Comment by vanessayuenn** [comment]
Looks like this has been [resolved](https://github.com/nuxt-modules/storybook/issues/428#issuecomment-1822576533) already? In any case, I am closing this in favour of keeping the discussion in one place. Please let me know if I am mistaken, though.
