### ISSUE TITLE
[Bug]: Storybook bundle not deterministic 

### ISSUE THREAD

**Issue by henkerik** [storybookjs/storybook#24747]
### Describe the bug

The storybook bundle is not build deterministically from the source files. The order the stories in the bundle is determined by the `listStories` function: 

https://github.com/storybookjs/storybook/blob/191934373c65de71ce07b1639cf8df79e0e85cf5/code/builders/builder-vite/src/list-stories.ts#L8

This function uses a `glob`, but the order of the results from a glob are given in no arbitrary order. This results in a Storybook bundle in which the list of story imports may differ from one build to the next. 

This breaks artifact based build systems like Bazel or Buck2 because they assume every build action is deterministic. 
  
<img width="1666" alt="Screenshot 2023-10-29 at 18 42 26" src="https://github.com/storybookjs/storybook/assets/267402/b19b5346-e6ad-45c9-af76-2c6d14607880">

**Fix**

This bug in Storybook was easily patched by sorting the list of stories at the end of line: https://github.com/storybookjs/storybook/blob/191934373c65de71ce07b1639cf8df79e0e85cf5/code/builders/builder-vite/src/list-stories.ts#L28

The sort order doesn't matter, as long as it is consistent from one build to the next.

### To Reproduce

Take a large Storybook and build it multiple times from sources. The resulting bundle does not always have the same file hash.

**Comment by valentinpalkovic** [comment]
Hi @henkerik,

Thanks for reporting this! These findings are very interesting. Do you mind opening a PR with a fix? Do you know, whether this bug also applies to the webpack5 builder?

**Comment by henkerik** [comment]
Hey @valentinpalkovic ,

Sure, this is how we fixed (*) this bug: 

https://github.com/storybookjs/storybook/pull/24833

(*) were are currently running Storybook with a patch (https://pnpm.io/cli/patch)

**Comment by henkerik** [comment]
FYI, I don't see any usage of `glob` in the webpack5 builder, so I don't think this specific bug is present in the webpack5 builder.

**Comment by valentinpalkovic** [comment]
Great! Thanks for checking the Webpack5 builder!
