### ISSUE TITLE
[Bug]: Stories docblock duplicating stories on custom .MDX files 

### ISSUE THREAD

**Issue by xsu1010** [storybookjs/storybook#24751]
### Describe the bug

On a Storybook + Lit Web Components + Vite environment, when writing a custom .mdx file, the `<Stories/>` docblock duplicates the stories whenever a global option is ticked (e.g. background, grid, outline).

This happens when using custom MDX docs. When using autodocs, the stories are not duplicated, however, we have some components where we'd like to have more control over the docs, so using autodocs does not work for us.

### To Reproduce

[Here's a repo that can help replicate the issue.](https://github.com/xsu1010/storybook-lit-vite-docs-duplicating)

I also hosted it on Chromatic, [which you can check here.](https://654a6016d95b5229bf2bdeb1-daarfnmlph.chromatic.com/)

## Prerequisites:

- [pnpm](https://pnpm.io/) 

## Steps to reproduce:

1. Clone this repo:

```bash
git clone https://github.com/xsu1010/storybook-lit-vite-docs-duplicating.git
```

2. Install dependencies:

```bash
cd storybook-lit-vite-docs-duplicating && pnpm install
```

3. Run Storybook:

```bash
pnpm storybook
```

4. On the sidebar, you'll find a category named **Docs**. Click on any of the docs inside it and toggle through the global options on top (background, grid, outline).
   1. The Auto MDX doc will work just fine when toggling the global options.
   2. The Custom MDX docs will duplicate the stories when toggling the global options.

### System

```bash
Storybook Environment Info:

  System:
    OS: macOS 14.1
    CPU: (8) arm64 Apple M1 Pro
    Shell: 0.81.0 - /opt/homebrew/bin/nu
  Binaries:
    Node: 18.17.1 - ~/homebrew/bin/node
    Yarn: 1.22.19 - ~/homebrew/bin/yarn
    npm: 9.6.7 - ~/homebrew/bin/npm
    pnpm: 8.6.12 - ~/homebrew/bin/pnpm <----- active
  Browsers:
    Chrome: 119.0.6045.105
    Safari: 17.1
  npmPackages:
    @storybook/addon-essentials: ^7.5.3 => 7.5.3 
    @storybook/addon-links: ^7.5.3 => 7.5.3 
    @storybook/blocks: ^7.5.3 => 7.5.3 
    @storybook/web-components: ^7.5.3 => 7.5.3 
    @storybook/web-components-vite: ^7.5.3 => 7.5.3 
    chromatic: ^7.6.0 => 7.6.0 
    storybook: ^7.5.3 => 7.5.3
```

## Notes:
- This issue also happens with a static build (`pnpm build-storybook`).
- On any of the docs in the Docs category, I noticed that, when toggling through the global options, the page sort of refreshes fully,
sometimes throwing me to the top of the page.
  - However, this does not happen with the example docs (left them there for comparison). I'm not sure if this is related to the issue.

**Comment by JReinhold** [comment]
This is unrelated to Web components, it also happens in a React+vite sandbox: https://next--630511d655df72125520f051.chromatic.com/?path=/docs/addons-docs-docs2-button--metaof&globals=backgrounds.grid:!true
