### ISSUE TITLE
[Documentation]: msw-storybook-addon cannot work with msw 2.0

### ISSUE THREAD

**Issue by TTtuntuntutu** [storybookjs/storybook#24821]
### Describe the problem

I was referring to [mocking-api-services](https://storybook.js.org/docs/react/writing-stories/build-pages-with-storybook#mocking-api-services)  to introduce `msw` and `msw-storybook-addon`. After `yarn add --dev msw msw-storybook-addon`, The version of `msw-storybook-addon` is 1.10.0, and the version of `msw` is 2.0.5.

After running `initialize();` imported from `msw-storybook-addon`, it reports an error `Cannot read properties of undefined (reading 'apply')`.

This is because in `msw` 2.0, function `setupWorker` needs to be imported from the `"msw/browser"` path. While in the function `initialize` in msw-storybook-addon, `setupWorker` is imported from the `"msw"` path. 

So `msw-storybook-addon` can work with `msw` 1.x, but cannot work with `msw` 2.0.

**Comment by yannbf** [comment]
Hey there @TTtuntuntutu, thanks for opening this issue, but the msw addon is maintained in a separate repository. Please refer to this issue regarding MSW 2.0 support, which is possible via a prerelease version: https://github.com/mswjs/msw-storybook-addon/issues/121
