### ISSUE TITLE
[Bug]: Angular - Assets are not Available

### ISSUE THREAD

**Issue by elepner** [storybookjs/storybook#24840]
### Describe the bug

Assets defined in ``angular.json`` are not recognized in Storybook v7. It used to work in v6.

### To Reproduce

I have created a default starter project. https://github.com/elepner/storybook-angular-assets-bug

If you run ``ng serve`` and navigate to http://localhost:4200/assets/test.txt you'll get the content of the file. However, it does not work (404 error) in storybook ``npm run storybook`` and go to http://localhost:6006/assets/test.txt

### System

```bash
Storybook Environment Info:

  System:
    OS: Windows 11 10.0.22621
    CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
  Binaries:
    Node: 18.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD <----- active
  Browsers:
    Edge: Chromium (119.0.2151.58)
  npmPackages:
    @storybook/addon-essentials: ^7.5.2 => 7.5.2
    @storybook/addon-interactions: ^7.5.2 => 7.5.2
    @storybook/addon-links: ^7.5.2 => 7.5.2
    @storybook/angular: ^7.5.2 => 7.5.2
    @storybook/blocks: ^7.5.2 => 7.5.2
    @storybook/jest: ^0.2.3 => 0.2.3
    @storybook/testing-library: ^0.2.2 => 0.2.2
    msw-storybook-addon: ^1.10.0 => 1.10.0
    storybook: ^7.5.2 => 7.5.2
```

**Comment by Marklb** [comment]
The Storybook builder does not inherit `assets` or `styles`, so they need to be defined in the options.
```json
...,
"storybook": {
  "builder": "@storybook/angular:start-storybook",
  "options": {
    "configDir": ".storybook",
    "browserTarget": "taskbox:build",
    "compodoc": true,
    "compodocArgs": ["-e", "json", "-d", "."],
    "port": 6006,
    "assets": ["src/favicon.ico", "src/assets"],
    "styles": ["src/styles.css"]
  }
},
...,
```

**Comment by elepner** [comment]
Thanks, it that worked. This step was not needed in v6. Perhaps, [this](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#70-framework-specific-changes) or [that](https://github.com/storybookjs/storybook/blob/next/code/frameworks/angular/README.md#how-do-i-migrate-to-an-angular-storybook-builder) migration doc can be updated to reflect this change.
