### ISSUE TITLE
[Bug]: When I use <Story id="foo"> my component doesn't render

### ISSUE THREAD

**Issue by dep** [storybookjs/storybook#24860]
### Describe the bug

```
<Canvas>
  <Story id="Basic"><Accordions /></Story>
</Canvas>
```

Shows the following:

![image](https://github.com/storybookjs/storybook/assets/55112925/9222222e-b1eb-4b83-9d3c-d1306518149f)

Whereas

```
<Canvas>
  <Story name="Basic"><Accordions /></Story>
</Canvas>
```

Renders the component:

![image](https://github.com/storybookjs/storybook/assets/55112925/0eae4daa-0d85-412a-a1b3-4dfefd9a51bc)

I like being able to use `id` to hide unnecessary sidebar items

### To Reproduce

Use

```
<Canvas>
  <Story id="Basic"><Accordions /></Story>
</Canvas>
```

instead of

```
<Canvas>
  <Story name="Basic"><Accordions /></Story>
</Canvas>
```

### System

```bash
Storybook 7.5.2
```

**Comment by vanessayuenn** [comment]
Tags has been shipped in v8! You can now use it to hide stories from the sidebar:
```js
export const HiddenStory: Story = {
  // 👇 This story will not appear in Storybook's sidebar
  tags: ['!dev'],
  ...,
};
```
See more ways to use tags in our [docs](https://storybook.js.org/docs/writing-stories/tags).
