### ISSUE TITLE
[Bug]: Instantiating a component with `new` is no longer valid in Svelte 5.

### ISSUE THREAD

**Issue by allozaur** [storybookjs/storybook#24886]
### Describe the bug

Just created an empty SvelteKit Library project with Beta version of Svelte 5 enabled and installed Storybook.

This is what i get when viewing demo component stories:

<img width="883" alt="Zrzut ekranu 2023-11-17 o 11 48 09" src="https://github.com/storybookjs/storybook/assets/37627284/857a43a9-da69-48af-9337-a99fb20f1a22">

### To Reproduce

```
pnpm create svelte
```

Choose Svelte 5 beta.

```
pnpm dlx storybook@latest init
```

### Additional context

I managed to find that this particular code causes the error:

https://github.com/storybookjs/storybook/blob/main/code/renderers/svelte/src/render.ts#L69

According to [docs](https://svelte-5-preview.vercel.app/docs/breaking-changes#components-are-no-longer-classes), this:

```js
let createdComponent = new PreviewRender({ target: canvasElement, props: { storyFn, storyContext, name, kind, showError } });
```

should be changed to this:

```js
import { mount } from 'svelte';

function renderToCanvas({ storyFn, kind, name, showMain, showError, storyContext, forceRemount }, canvasElement) {

  // Rest of the code

  let createdComponent = mount(PreviewRender, { target: canvasElement, props: { storyFn, storyContext, name, kind, showError } });

  // Rest of the code
}

```

**Comment by JReinhold** [comment]
@benmccann is there a recommended approach to migrating this while still being compatible with Svelte 4?

I'd expect as soon as we try to do `import { mount } from 'svelte'` or `import { createClass } from 'svelte/legacy';` it will fail for all Svelte 4 users, unless you're planning on backporting `svelte/legacy` to Svelte 4?

I think we can make this work by doing version detection via `svelte/package.json`, but maybe you had a cleaner idea.

**Comment by allozaur** [comment]
@JReinhold it seems that i have some early-working code for the Storybook Svelte 5 renderer.

Just tested the `svelte-kit/skeleton-js` sandbox and it worked just fine locally for me :)

Tomorrow i will try to test Svelte 5 code to see how stories look.
