### ISSUE TITLE
[Bug]: Navigation Issue in Storybook 7.5.2 on Mobile Devices

### ISSUE THREAD

**Issue by Rezident081** [storybookjs/storybook#24884]
### Describe the bug

After updating to Storybook version 7.5.2, we are experiencing a navigation issue on mobile devices. The issue involves incorrect redirection when using addons in the menu.

Steps to Reproduce:

- Open Storybook on your mobile device.
- Navigate to a component to any component other than the first one, in our case it is "Button component" (the second component in the our list).
- Try to use any function in the addon menu for this component.

Expected Behavior:
When using addons, the current component should remain active.

Actual Behavior:
When using addons, there is an automatic redirect to the first component in the list.

Screenshots:
1) Selected button - 
![image](https://github.com/storybookjs/storybook/assets/15907642/a1fa47ed-f87a-4e3e-bea7-5bc1735bb936)

2) Click to Canvas button -
![image](https://github.com/storybookjs/storybook/assets/15907642/40aba8fc-5093-48fd-a2ed-589ec17ab395)

3) I redirected to Accordion component -
![image](https://github.com/storybookjs/storybook/assets/15907642/23cc230a-9a09-4614-b731-be690e2346bc)

### To Reproduce

Steps to Reproduce:

- Open Storybook on your mobile device.
- Navigate to a component to any component other than the first one, in our case it is "Button component" (the second component in the our list).
- Try to use any function in the addon menu for this component.

**Comment by MichaelAllenWarner** [comment]
I'm seeing this behavior also, on viewport-widths below 600px. Version 7.5.1 here.

When I've got the Sidebar tab open, I can navigate to another story, but when I switch to the Canvas tab I'm "redirected" back to the story that was selected originally.

**Comment by MichaelAllenWarner** [comment]
Same issue as #24603, I'd imagine.

**Comment by valentinpalkovic** [comment]
cc @cdedreuille

**Comment by shilman** [comment]
Please try upgrading to the latest prerelease:

```
npx storybook@next upgrade --prerelease
```

Does that fix it? We've overhauled and greatly improved the mobile UI in 8.0

**Comment by cdedreuille** [comment]
Yes I can confirm that this should be solved in Storybook 8.x
