### ISSUE TITLE
[Bug]: unable to install @storybook/manager-webpack5@^7.5.3    not visible in npm version registry

### ISSUE THREAD

**Issue by igorlino** [storybookjs/storybook#24905]
### Describe the bug

If the package.json contains the latest version, _npm install_ will fail always

Unable to install the latest 7.5.3 version as shown in the [github release page](https://github.com/storybookjs/storybook/releases/tag/v7.5.3)

The registry shows an older version:
[https://www.npmjs.com/package/@storybook/manager-webpack5](npm registry)

The command also does not show any 7.5.x version:
 npm show @storybook/manager-webpack5 versions

### To Reproduce

Create a new empty project using: 
`npm init`
you may use any option from that.

Afterwards use:
`npm -D i @storybook/manager-webpack5@7.5.3`

Result:
```
PS C:\projects\tst\test> npm -D i @storybook/manager-webpack5@7.5.3
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @storybook/manager-webpack5@7.5.3.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

**Comment by valentinpalkovic** [comment]
In Storybook 7 the new [framework API](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#new-framework-api) was introduced. The `@storybook/manager-webpack5` does not exist anymore. Please take a look at the [migration guide](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md) to upgrade from Storybook 6 to Storybook 7.
