### ISSUE TITLE
[Documentation]: More clarity on what including compodoc does?

### ISSUE THREAD

**Issue by fireflysemantics** [storybookjs/storybook#24944]
### Describe the problem

The CLI asks us if we want to use Compodoc.  More documentation on what this does would be great.

https://stackoverflow.com/questions/77519750/using-compodoc-for-storybook-documentation

### Additional context

https://stackoverflow.com/questions/77519750/using-compodoc-for-storybook-documentation

**Comment by Ahmed-0102** [comment]
After researching a bit on internet I have found this conclusion
When you're setting up an Angular project with Storybook, the option to use Compodoc for documentation refers to integrating Compodoc into your Angular project separately from Storybook. This means you can generate and view documentation for your Angular application components using Compodoc, regardless of whether you are using Storybook.

Compodoc is not an alternate way of displaying documentation within Storybook. It is a separate documentation tool for Angular projects. If you choose to use Compodoc in your Angular project, it will generate documentation for your entire Angular application, not just the Storybook stories. The decision to use Compodoc or not depends on your documentation needs for the overall Angular application, whereas Storybook is specifically focused on component development and testing.

Hope it helps.

**Comment by SulthanNK** [comment]
Hi @shilman  👋, Is anyone working on this issue? If not, I'll gothrough and start working on it

**Comment by shilman** [comment]
@SulthanNK  thanks so much for volunteering. Please coordinate with @jonniebigodes on the docs. And note that the answer above is incorrect--Storybook uses the JSON output of compodoc to automatically generate controls.

**Comment by SulthanNK** [comment]
Hi @jonniebigodes , Can you guide me to work on this? and @shilman Is there any other way to contact him?

**Comment by valentinpalkovic** [comment]
We have added a `Compodoc` section in the [docs](https://storybook.js.org/docs/get-started/angular#setup-compodoc), and we have adjusted the CLI to elaborate on what Compodoc exactly does in combination with Storybook.
