### ISSUE TITLE
[Bug]: Docs don't pull component props automatically

### ISSUE THREAD

**Issue by moisespio** [storybookjs/storybook#24943]
### Describe the bug

Stories don't pull the TypeScript prop types automatically in a monorepo project. React docgen does not do the trick either. The expected result is to see the "description" column filled with the propTypes, but it's empty instead. Also, if you don't specify the args/argTypes, the "control" column always treats the prop as an object instead of pulling the type from the component.

[Here's a live example](https://turborepo-examples-designsystem-docs.vercel.sh/?path=/docs/button--docs) (screenshot below)

![image](https://github.com/storybookjs/storybook/assets/2017696/caa2b060-6b1d-4ce3-ba71-04b95c7afece)

### To Reproduce

[Demo link](https://turborepo-examples-designsystem-docs.vercel.sh/?path=/docs/button--docs)
[Repo](https://github.com/vercel/turbo/tree/main/examples/design-system)

### System

```bash
Storybook Environment Info:

  System:
    OS: macOS 13.5
    CPU: (8) arm64 Apple M1 Pro
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.2 - /usr/local/bin/node
    npm: 9.9.0 - ~/Sandbox/node_modules/.bin/npm <----- active
  Browsers:
    Chrome: 119.0.6045.159
    Safari: 16.6
  npmPackages:
    @storybook/addon-a11y: ^7.5.1 => 7.5.1
    @storybook/addon-actions: ^7.5.1 => 7.5.1
    @storybook/addon-controls: ^7.5.1 => 7.5.1
    @storybook/addon-essentials: ^7.5.1 => 7.5.1
    @storybook/addon-interactions: ^7.5.1 => 7.5.1
    @storybook/addon-links: ^7.5.1 => 7.5.1
    @storybook/addon-mdx-gfm: ^7.5.1 => 7.5.1
    @storybook/addon-measure: ^7.5.1 => 7.5.1
    @storybook/addon-outline: ^7.5.1 => 7.5.1
    @storybook/addon-toolbars: ^7.5.1 => 7.5.1
    @storybook/addon-viewport: ^7.5.1 => 7.5.1
    @storybook/blocks: ^7.5.1 => 7.5.1
    @storybook/manager-api: ^7.5.1 => 7.5.1
    @storybook/react: ^7.5.1 => 7.5.1
    @storybook/react-vite: ^7.5.1 => 7.5.1
    storybook: ^7.5.1 => 7.5.1
```

**Comment by GuyGooL5** [comment]
The same thing happened to me, my best guess is that it has something to do with SWC, because I started a new project with Vite 5.x under react-typescript-swc configuration, and got npm conflicts with storybook's peer dependencies.

**Comment by GuyGooL5** [comment]
The same thing happened to me, my best guess is that it has something to do with SWC, because I started a new project with Vite 5.x under react-typescript-swc configuration, and got npm conflicts with storybook's peer dependencies.

**Comment by vanessayuenn** [comment]
@moisespio @GuyGooL5 curious if y'all have tried the [troubleshooting](https://storybook.js.org/docs/writing-docs/autodocs#the-auto-generated-documentation-is-not-showing-up-in-a-monorepo-setup) for monorepo from the docs?

**Comment by fredrik-j-lindberg** [comment]
Experiencing the same thing, also using vite but v4.4.3. Storybook v7.5.0

Monorepo troubleshooting did not appear to do anything

**Comment by moisespio** [comment]
OK, I was finally able to get this thing to work. Thanks @vanessayuenn, the [troubleshooting](https://storybook.js.org/docs/writing-docs/autodocs#the-auto-generated-documentation-is-not-showing-up-in-a-monorepo-setup) definitely guided me to the right direction.

Here's what I did:

#### 1. Updated the imports to import the components directly instead of importing them from the bundle

```jsx
// 👎 Bad
import { Button } from 'ui';

// 👍 Good
import { Button } from 'ui/src/components/Button';
```

#### 2. Installed the `react-docgen` npm package
This step is missing from the documentation, but you need to go into your storybook root folder and run `npm install react-docgen`.

#### 3. Updated Storybook config (.storybook/main.ts) [as per documentation](https://storybook.js.org/docs/writing-docs/autodocs#the-auto-generated-documentation-is-not-showing-up-in-a-monorepo-setup)
```jsx
typescript: {
  reactDocgen: 'react-docgen',
  skipBabel: true,
  check: false,
}
```

#### 4. Restart your dev server and voilà!

**Comment by fredrik-j-lindberg** [comment]
No luck here, even with the dependency installed 😞

**Comment by jbrunner92** [comment]
> OK, I was finally able to get this thing to work. Thanks @vanessayuenn, the [troubleshooting](https://storybook.js.org/docs/writing-docs/autodocs#the-auto-generated-documentation-is-not-showing-up-in-a-monorepo-setup) definitely guided me to the right direction.
> 
> Here's what I did:
> 
> #### 1. Updated the imports to import the components directly instead of importing them from the bundle
> ```js
> // 👎 Bad
> import { Button } from 'ui';
> 
> // 👍 Good
> import { Button } from 'ui/src/components/Button';
> ```
> 
> #### 2. Installed the `react-docgen` npm package
> This step is missing from the documentation, but you need to go into your storybook root folder and run `npm install react-docgen`.
> 
> #### 3. Updated Storybook config (.storybook/main.ts) [as per documentation](https://storybook.js.org/docs/writing-docs/autodocs#the-auto-generated-documentation-is-not-showing-up-in-a-monorepo-setup)
> ```js
> typescript: {
>   reactDocgen: 'react-docgen',
>   skipBabel: true,
>   check: false,
> }
> ```
> 
> #### 4. Restart your dev server and voilà!

What does your full `viteFinal` look like in `main.ts`?

**Comment by jbrunner92** [comment]
> > OK, I was finally able to get this thing to work. Thanks @vanessayuenn, the [troubleshooting](https://storybook.js.org/docs/writing-docs/autodocs#the-auto-generated-documentation-is-not-showing-up-in-a-monorepo-setup) definitely guided me to the right direction.
> > Here's what I did:
> > #### 1. Updated the imports to import the components directly instead of importing them from the bundle
> > ```js
> > // 👎 Bad
> > import { Button } from 'ui';
> > 
> > // 👍 Good
> > import { Button } from 'ui/src/components/Button';
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > #### 2. Installed the `react-docgen` npm package
> > This step is missing from the documentation, but you need to go into your storybook root folder and run `npm install react-docgen`.
> > #### 3. Updated Storybook config (.storybook/main.ts) [as per documentation](https://storybook.js.org/docs/writing-docs/autodocs#the-auto-generated-documentation-is-not-showing-up-in-a-monorepo-setup)
> > ```js
> > typescript: {
> >   reactDocgen: 'react-docgen',
> >   skipBabel: true,
> >   check: false,
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > #### 4. Restart your dev server and voilà!
> 
> For some reason this still doesn't pick up Mui props if you try using mui components. If you replace `packages/ui/src/button.tsx` with the following, the explicity defined interface props show, but not the MuiButtonProps:
> 
> ```js
> import { type ButtonProps as MuiButtonProps } from '@mui/material/Button';
> import  MuiButton from '@mui/material/Button';
> import React from 'react';
> 
> export interface ButtonProps extends MuiButtonProps {
>   label: string;
>   foo: 'foo' | 'bar';
> }
> 
> export function Button({label, ...props}: ButtonProps) {
>   return <MuiButton {...props}>{label}</MuiButton>
> }
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/10749662/303461389-eb729111-2215-40f8-805e-1c7e8fd719a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0MjE4ODcsIm5iZiI6MTcwNzQyMTU4NywicGF0aCI6Ii8xMDc0OTY2Mi8zMDM0NjEzODktZWI3MjkxMTEtMjIxNS00MGY4LTgwNWUtMWM3ZThmZDcxOWE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA4VDE5NDYyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxYTIwNDc5NTMzMThhOGY0YjFlN2M2YjE3MjIzYmE1MjU1YWMwYTUxZDg0ZjcyZTAyNTZjMTFkNTc1MmM2MGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9GnjcmywJi8Q1LdQPqElV-W5Cprcc21vDr2MHwmUtz8)
> 
> This solution also does not work if you use `React.FunctionComponent` like so:
> 
> ```js
> import { type ButtonProps as MuiButtonProps } from '@mui/material/Button';
> import  MuiButton from '@mui/material/Button';
> import type { FunctionComponent } from 'react';
> import React from 'react';
> 
> export interface ButtonProps extends MuiButtonProps {
>   label: string;
>   foo: 'foo' | 'bar';
> }
> 
> const Button: FunctionComponent<ButtonProps> = ({label, ...props}) => {
>   return <MuiButton {...props}>{label}</MuiButton>
> };
> 
> export { Button }
> ```

ah, Figured it out. If you instead change the `typescript` prop to the following, it works. [https://storybook.js.org/recipes/@mui/material#@mui/material](See mui storybook docs here)
```js
typescript: {
    // reactDocgen: 'react-docgen',
    reactDocgen: 'react-docgen-typescript',
    reactDocgenTypescriptOptions: {
      // Speeds up Storybook build time
      compilerOptions: {
        allowSyntheticDefaultImports: false,
        esModuleInterop: false,
      },
      // Makes union prop types like variant and size appear as select controls
      shouldExtractLiteralValuesFromEnum: true,
      // Makes string and boolean types that can be undefined appear as inputs and switches
      shouldRemoveUndefinedFromOptional: true,
      // Filter out third-party props from node_modules except @mui packages
      propFilter: (prop) =>
        prop.parent ? !/node_modules\/(?!@mui)/.test(prop.parent.fileName) : true,
    },
  },
```

**Comment by AnweshGangula** [comment]
I'm facing this issue again with Storybook 9 and typescript. I was able to get the controls to work for the source component props. But I can't get the docs to auto generate controls for props of the imported library (react-aria) in my case

I'm using a monorepo based on the [following repo](https://github.com/XOP/design-system-starter). The repo is working as expected in Storybook 8, but when I upgrade it to version 9, I get this issue.

Refernce Storybook of version 8: https://ds-starter-storybook.vercel.app/?path=/docs/form-button--overview

```typescript
  typescript: {
    check: false,
    reactDocgen: 'react-docgen',
    // reactDocgen: 'react-docgen-typescript',
    // this is required for correct argTypes processing
    reactDocgenTypescriptOptions: {
      // Speeds up Storybook build time
      compilerOptions: {
        allowSyntheticDefaultImports: false,
        esModuleInterop: false,
      },
      include: docgenPaths,
      shouldExtractValuesFromUnion: true,
      shouldExtractLiteralValuesFromEnum: true,
      shouldRemoveUndefinedFromOptional: true,
      propFilter: (prop) => {
        if (prop.parent) {
          return (
            // when NOT using pnpm or/and react-aria make sure to adjust the regEx
            !/node_modules\/.pnpm\/(?!react-aria)/.test(prop.parent.fileName) &&
            !excludedProps.includes(prop.name) // excludedProps = ['style', 'slot']
          );
        }

        return false;
      },
    },
  },
``` 

<img width="1577" height="1209" alt="React Aria Storybook autodocs screenshot" src="https://github.com/user-attachments/assets/8d3266c4-da5b-44f0-84ca-9b57d00c0ef3" />


Expected Documentation:
https://ds-starter-storybook.vercel.app/?path=/docs/form-button--overview


<img width="1620" height="1296" alt="React Aria expected documentation" src="https://github.com/user-attachments/assets/51a448ff-e647-4f77-812b-bea94f21e3a0" />
