### ISSUE TITLE
[Bug]: Install error on cb.apply storybook@latest

### ISSUE THREAD

**Issue by kahlan88** [storybookjs/storybook#25019]
### Describe the bug

I have a similar problem as https://github.com/storybookjs/storybook/issues/15269. Not resolved by following https://stackoverflow.com/questions/63429304/npm-err-cb-apply-is-not-a-function (I only have npx and rimraf as my global npm packages and deleted npm cache. No luck.
I still get:

```
npm ERR! cb.apply is not a function
Install for [ 'storybook@latest' ] failed with code 1
```

Our project is mostly cshtml etc with some `preact` elements. We used to use `storybook\html` but upgrading would be very time-consuming as we'd like to move to either `preact` or `web components`. 

I just uninstalled all `storybook` packages and ran `npm cache clean --force` as well as deleted `npm` cache manually and checked my global node-modules (but only have `npx` and `rimraf` in there so I didn't delete them).

Are there any manual instructions to install storybook or what can I try to fix?

We're on `gulp` v4 and storybook/html v6 worked just fine.

**Comment by valentinpalkovic** [comment]
Hi @kahlan88,
Can you provide a [reproduction](https://storybook.js.org/docs/7.5/contribute/how-to-reproduce)?

**Comment by kahlan88** [comment]
Just solved the issue by updating our client to node v16 and reinstalling everything.
