### ISSUE TITLE
[Bug]: `@storybook/addon-viewport@7.6.0` is broken

### ISSUE THREAD

**Issue by jpzwarte** [storybookjs/storybook#25036]
### Describe the bug

I think `@storybook/addon-viewport` version `7.6.0` is broken: it references `import { L } from './main-c55d8855.js';` in `index.d.ts` which doesn't exist:

![CleanShot 2023-11-29 at 14 21 20@2x](https://github.com/storybookjs/storybook/assets/3968/3bc0da66-7443-4974-9186-59ebb3b52645)
![CleanShot 2023-11-29 at 14 21 25@2x](https://github.com/storybookjs/storybook/assets/3968/1803cc17-c32a-47e3-bfaa-4d4517b3f0f9)

### To Reproduce

-

### System

```bash
-
```

### Additional context

-

**Comment by jpzwarte** [comment]
Weird, it is there in the published version: https://www.npmjs.com/package/@storybook/addon-viewport?activeTab=code

**Comment by jlowcs** [comment]
Same issue in @storybook/addon-viewport@7.6.1

**Comment by JReinhold** [comment]
This is reproducible when compiling in `--no-link` mode on the `main` branch.

**Comment by ndelangen** [comment]
@JReinhold some difference in how the output is generated between `main` and `next`?
I ran it on `next` and wasn't able to reproduce.

**Comment by kasperpeulen** [comment]
https://github.com/storybookjs/storybook/pull/25107
