### ISSUE TITLE
[Bug]: Docs page doesn't load more than four story iframes (inline: false)

### ISSUE THREAD

**Issue by davidlyonsbp** [storybookjs/storybook#25046]
### Describe the bug

I need to render some stories on docs pages in an iframe so their internal window width is correct for media queries.
But MDX and autodocs pages won't load more than four iframe stories (inline: false)
Currently on Storybook 7.6.1, with @storybook/react-webpack5 as the framework in the main.ts config

### To Reproduce

footers.stories.tsx
```jsx
export default {
  title: 'Footers/Examples',
  parameters: {
    layout: 'fullscreen',
    docs: {
      story: {
        inline: false, // render stories in an iframe
        height: 300,
      },
    },
  },
};

export const Story1 = () => <div>Footer 1</div>;
export const Story2 = () => <div>Footer 2</div>;
export const Story3 = () => <div>Footer 3</div>;
export const Story4 = () => <div>Footer 4</div>;
export const Story5 = () => <div>Footer 5</div>;

```

footers.mdx (or an auto docs page)
```mdx
import { Canvas, Meta } from '@storybook/blocks';
import * as FooterStories from './footers.stories.tsx';

<Meta title="Footers/Overview" />

<Canvas of={FooterStories.Story1} />
<Canvas of={FooterStories.Story2} />
<Canvas of={FooterStories.Story3} />
<Canvas of={FooterStories.Story4} />
{/* iframes after the 4th won't render */}
<Canvas of={FooterStories.Story5} />
```

### System
macOS 14
Chrome 119

_No response_

**Comment by Tap-Kim** [comment]
@davidlyonsbp 

Hello! First of all, I was interested in the bug report, so I commented.
However, the MDX document said that more than 5 components could not be rendered based on the actual 7.6.0 version, and it was confirmed that it was working properly.
I think I can help if you can give me a clear code of situations where the bug can occur!

The captured image below is the result of a direct test.
<img width="843" alt="스크린샷 2023-12-02 오후 7 38 19" src="https://github.com/storybookjs/storybook/assets/93532696/cf213dbf-149a-4b38-bf0a-fb0e9916f613">

**Comment by davidlyonsbp** [comment]
@Tap-Kim Which framework did you test with?
It seems like this is an issue with `framework: { name: '@storybook/react-webpack5' }` in my main.ts config.
```
npx create-react-app my-app
cd my-app
npx storybook@latest init
```
@Marklb The iframe is there, but the contents of the iframe doesn't load, it shows either a loading spinner or nothing within the iframe.

---

I tried out a new Storybook with Vite / framework.name `@storybook/react-vite`, and it appears all of the iframes will load if I scroll down slowly to load one iframe at a time:
```
npm create vite@latest
cd vite-project
npx storybook@latest init
```
But if I scroll down quickly and it tries to load several iframes at once, I get this error within some of the iframes:

<img width="1085" alt="Screenshot 2023-12-04 at 3 08 19 PM" src="https://github.com/storybookjs/storybook/assets/66848742/3217eabb-c052-4546-9111-b129eb1d6c6c">

And a lot of these errors in the console:
`Failed to load resource: net::ERR_INSUFFICIENT_RESOURCES`

**Comment by Tap-Kim** [comment]
That version is in use. What version of @davidlyonsbp  is in use exactly?

Maybe it's a problem with ifframe information. 

Can I check it with the code sandbox being tested?

```package.json
"devDependencies": {
    "@storybook/addon-essentials": "^7.6.3",
    "@storybook/addon-interactions": "^7.6.3",
    "@storybook/addon-links": "^7.6.3",
    "@storybook/addon-onboarding": "^1.0.9",
    "@storybook/blocks": "^7.6.3",
    "@storybook/react": "^7.6.3",
    "@storybook/react-vite": "^7.6.3",
    "@storybook/test": "^7.6.3",
    "@types/react": "^18.2.37",
    "@types/react-dom": "^18.2.15",
    "@typescript-eslint/eslint-plugin": "^6.10.0",
    "@typescript-eslint/parser": "^6.10.0",
    "@vitejs/plugin-react": "^4.2.0",
    "eslint": "^8.53.0",
    "eslint-plugin-react-hooks": "^4.6.0",
    "eslint-plugin-react-refresh": "^0.4.4",
    "eslint-plugin-storybook": "^0.6.15",
    "storybook": "^7.6.3",
    "typescript": "^5.2.2",
    "vite": "^5.0.0"
  }
```

**Comment by shilman** [comment]
I believe this is a resource issue. Each iframe consumes memory and loads its own resources. In earlier versions of Storybook this error was common, but after we introduced the [on-demand architecture](https://storybook.js.org/blog/storybook-on-demand-architecture/) I believe the problem has largely gone away. I benchmarked as we were releasing that feature and was able to load nearly 50 iframes without issue.

It's possible that things regressed, or more likely it is an issue with your Storybook. Do you a have a reproduction repo you can share? If not, can you create one? Go to https://storybook.new or see [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce). Thank you! 🙏
