### ISSUE TITLE
[Bug]: Side tree view css os not loading

### ISSUE THREAD

**Issue by Sudeepa1949** [storybookjs/storybook#25056]
### Describe the bug

Storybook side tree view css is not taking for the first time and after refresh those css will get applying
this problem is coming after upgrading from 6.5.13 to v7.4.5.
<img width="373" alt="image" src="https://github.com/storybookjs/storybook/assets/114284914/0f42b974-c8f2-46ca-99a9-30d9616557dd">

### System

```bash
mac 14, safari, chrome
```

**Comment by Sudeepa1949** [comment]
need update on this ASAP

**Comment by shilman** [comment]
Do you a have a reproduction repo you can share? If not, can you create one? Go to https://storybook.new or see [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce). Thank you! 🙏
