### ISSUE TITLE
[Bug]: Vue 3 testing module resolution failing

### ISSUE THREAD

**Issue by Xenossolitarius** [storybookjs/storybook#25080]
### Describe the bug

Breaking change with @storybook/testing-vue3 with the introduction of alpha release

Seems this https://github.com/storybookjs/storybook/commit/da42b5dce7fcea10c667e531ed4d6bd9c4e04654 was the change which caused this

@valentinpalkovic not sure how to fix this, or why it's not working in my use case.

[[private]] replaced private directory structure

│2 FAIL  src/snapshot.test.ts [ src/snapshot.test.ts ]
│3⎯⎯⎯⎯⎯⎯ Failed Suites 1 ⎯⎯⎯⎯⎯⎯⎯
│  RUN  v0.34.6 [[Private]]ting-vue3@1.0.0_@storybook+client-logger@7.6.3_@storybook+preview-api@7.6.3_@st_orecefcvaxra6t3dgrpg6f4tde/node_modules/@storybook/testing-vue3/dist/testing-vue3.cjs.development.js:7:33
│  ❯ src/snapshot.test.ts  (0 test)
│ ⎯⎯⎯⎯⎯⎯ Failed Suites 1 ⎯⎯⎯⎯⎯⎯⎯
│  FAIL  src/snapshot.test.ts [ src/snapshot.test.ts ]
│ Error: Package subpath './preview' is not defined by "exports" in [[private]] node_modules/.pnpm/@storybook+testing-vue3@1.0.0_@storybook+client-logger@7.6.3_@storybook+preview-api@7.6.3_@st_orecefcvaxra6t3dgrpg6f4tde/node_modules/@storybook/vue3/package.json
│  ❯ Object.<anonymous> ../../node_modules/.pnpm/@storybook+testing-vue3@1.0.0_@storybook+client-logger@7.6.3_@storybook+preview-api@7.6.3_@st_orecefcvaxra6t3dgrpg6f4tde/node_modules/@storybook/testing-vue3/dist/testing-vue3.cjs.development.js:7:33

### System

```bash
torybook Environment Info:

  System:
    OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700H
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
    pnpm: 8.11.0 - ~/.local/share/pnpm/pnpm <----- active
  npmPackages:
    @storybook/addon-essentials: ^7.6.3 => 7.6.3 
    @storybook/addon-interactions: ^7.6.3 => 7.6.3 
    @storybook/addon-links: ^7.6.3 => 7.6.3 
    @storybook/addon-mdx-gfm: ^7.6.3 => 7.6.3 
    @storybook/addon-themes: ^7.6.3 => 7.6.3 
    @storybook/blocks: ^7.6.3 => 7.6.3 
    @storybook/testing-library: ^0.2.2 => 0.2.2 
    @storybook/testing-vue3: 1.0.0 => 1.0.0 
    @storybook/vue3: ^7.6.3 => 7.6.3 
    @storybook/vue3-vite: ^7.6.3 => 7.6.3 
    storybook: ^7.6.3 => 7.6.3
```

**Comment by shilman** [comment]
closing as duplicate to https://github.com/storybookjs/testing-vue3/issues/14
