### ISSUE TITLE
[Bug]: Unable to use css in turborepo nextjs application

### ISSUE THREAD

**Issue by nikhilsnayak** [storybookjs/storybook#25097]
### Describe the bug

ERROR in ./src/app/stories/page.css (../../node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[8].use[1]!../../node_modules/postcss-loader/dist/cjs.js!./src/app/stories/page.css) 
Module build failed (from ../../node_modules/postcss-loader/dist/cjs.js):
TypeError: Cannot read properties of undefined (reading '.cjs')
    at loadConfig (C:\Users\nikhils\Desktop\codecraft-internal-apps\node_modules\postcss-loader\dist\utils.js:79:44)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.loader (C:\Users\nikhils\Desktop\codecraft-internal-apps\node_modules\postcss-loader\dist\index.js:45:22)
 @ ./src/app/stories/page.css 8:6-193 22:17-24 26:7-21 52:25-39 53:36-47 53:50-64 57:6-67:7 58:54-65 58:68-82 64:42-53 64:56-70 66:21-28 77:0-163 77:0-163 78:22-29 78:33-47 78:50-64 55:4-68:5
 @ ./src/app/stories/Page.tsx 7:0-20
 @ ./src/app/stories/Page.stories.ts 8:0-30 11:13-17
 @ ./src/ lazy ^\.\/.*$ include: (?:[\\/]src(?:[\\/](?%21\.)(?:(?:(?%21(?:^%7C[\\/])\.).)*?)[\\/]%7C[\\/]%7C$)(?%21\.)(?=.)[^\\/]*?\.stories\.(js%7Cjsx%7Cmjs%7Cts%7Ctsx))$ chunkName: [request] namespace object ./app/stories/Page.stories.ts ./app/stories/Page.stories
 @ ./storybook-stories.js 23:11-27:5
 @ ./storybook-config-entry.js 6:0-50 25:21-29 28:2-31:4 28:58-31:3 30:31-39

### System

```bash
Storybook Environment Info:

  System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.11.0 - ~\AppData\Local\pnpm\pnpm.CMD <----- active
  Browsers:
    Edge: Chromium (119.0.2151.93)
  npmPackages:
    @storybook/addon-essentials: 7.6.3 => 7.6.3
    @storybook/addon-interactions: 7.6.3 => 7.6.3
    @storybook/addon-links: 7.6.3 => 7.6.3
    @storybook/addon-onboarding: 1.0.9 => 1.0.9
    @storybook/blocks: 7.6.3 => 7.6.3
    @storybook/nextjs: 7.6.3 => 7.6.3
    @storybook/react: 7.6.3 => 7.6.3
    @storybook/test: 7.6.3 => 7.6.3
    eslint-plugin-storybook: 0.6.15 => 0.6.15
    storybook: 7.6.3 => 7.6.3
```

**Comment by shilman** [comment]
Do you a have a reproduction repo you can share? If not, can you create one? Go to https://storybook.new or see [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce). Thank you! 🙏
