### ISSUE TITLE
Support Vite 5

### ISSUE THREAD

**Issue by valentinpalkovic** [storybookjs/storybook#25127]
We want to add proper Vite 5 Support in Storybook 8.0.0. The problem is not about Vite 5, but maintaining and supporting multiple versions of Vite since we rely on Vite-plugins, which just support a particular version of Vite. Peer dependency issues are an issue that we have to overcome. One approach might be to make Vite not zero-configurable, but plugins have to be installed by the user to match the users Vite version. The following tasklist mentions the PRs, which are pending

```[tasklist]
- [x] Drop Vite < 4 support
- [ ] https://github.com/storybookjs/storybook/issues/25210
- [x] Update documentation
```

## Related PRs

```[tasklist]
- [ ] https://github.com/storybookjs/storybook/pull/25005
- [ ] https://github.com/storybookjs/storybook/pull/24953
- [ ] https://github.com/storybookjs/storybook/pull/24901
```

## Relevant issues

- https://github.com/storybookjs/storybook/issues/25125#issuecomment-1841761489
- https://github.com/storybookjs/storybook/issues/24918

**Comment by shilman** [comment]
@kasperpeulen I added #24918 to the list above
