### ISSUE TITLE
[Documentation]: Document how to configure SWC

### ISSUE THREAD

**Issue by yringler** [storybookjs/storybook#25121]
### Describe the problem

The [compiler docs ](https://storybook.js.org/docs/configure/compilers#swc)explain how to opt-in to SWC, but do not discuss how to configure.

Configuration is required to enable decorators, which is required to use lit.

I [created a minimal reproduction rep](https://github.com/yringler/swc-decorator-repro) with 3 branches

master - SWC, doesn't build
try-addon - uses the [swc-addon](https://storybook.js.org/addons/storybook-addon-swc), which has excellent documentation
fix-nativeswc-via-config - uses a custom webpackFInal to find and modify the swc option

My fix for native SWC is quite hacky and obtuse. If there is a preferred way, can it be documented? Not included in the repro, but tried elsewhere, is using .swcrc, which was also not recognized.

It would be a small PR to add swcOptions to the builder options, and use that in [createSWCLoader](https://github.com/storybookjs/storybook/blob/3bcca2d4765c1f6b8aaf87ce70916d51cac743c1/code/builders/builder-webpack5/src/preview/loaders.ts#L28)

https://github.com/storybookjs/storybook/blob/3bcca2d4765c1f6b8aaf87ce70916d51cac743c1/code/builders/builder-webpack5/src/preview/loaders.ts#L28

Or, to have the loader check for .swcrc

**Comment by valentinpalkovic** [comment]
Hi @yringler 
The docs for configuring swc are a bit hidden: https://storybook.js.org/docs/api/main-config-swc 

@jonniebigodes Maybe it makes sense to cross-reference this page on the general [compiler page](https://storybook.js.org/docs/configure/compilers#swc)

I hope this helps!
