### ISSUE TITLE
[Bug]: props containing 'on' are improperly rendered in "Show code"

### ISSUE THREAD

**Issue by ChristopheFuzier** [storybookjs/storybook#25143]
### Describe the bug

In the "Show code" section, any prop containing "on" is rendered as a callback. The test should be whether the name starts with "on" rather than whether it contains "on".

### To Reproduce

https://stackblitz.com/edit/github-j6h4hd?file=src%2Fstories%2FButton.vue,src%2Fstories%2FButton.stories.js&preset=node

- Go to Button / Docs in the storybook
- Click "Show code"
- Edit the "icon" prop

-> The generated prop in "Show code" is `icon="()=>({})"` whatever the value you set.

### System

```bash
System:
    OS: Linux 6.2 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn <----- active
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
  Browsers:
    Chrome: 119.0.6045.199
  npmPackages:
    @storybook/addon-essentials: ^7.6.3 => 7.6.3 
    @storybook/addon-interactions: ^7.6.3 => 7.6.3 
    @storybook/addon-links: ^7.6.3 => 7.6.3 
    @storybook/blocks: ^7.6.3 => 7.6.3 
    @storybook/test: ^7.6.3 => 7.6.3 
    @storybook/vue3: ^7.6.3 => 7.6.3 
    @storybook/vue3-vite: ^7.6.3 => 7.6.3 
    storybook: ^7.6.3 => 7.6.3
```

**Comment by Tap-Kim** [comment]
May I handle this issue? please assign to me~ I'll create PR soon!👀
