### ISSUE TITLE
[Bug]: Typescript docstrings formatted like a JSX component get inserted into DOM as elements

### ISSUE THREAD

**Issue by psychedelicious** [storybookjs/storybook#25165]
### Describe the bug

When I put a string formatted like a JSX component into a component's props' type's docstring, the autogenerated docs insert it into the DOM as an element. It gets inserted into the argstable.

Example type w/ docstring:
```ts
interface HeaderProps {
  /**
   * <ThisIsNotAComponent />
   */
  user?: User;
  onLogin: () => void;
  onLogout: () => void;
  onCreateAccount: () => void;
}
```

Error in console:
```ts
Warning: <ThisIsNotAComponent /> is using incorrect casing. Use PascalCase for React components, or lowercase for HTML elements.
    at ThisIsNotAComponent
    ...
```

In the DOM, we see the element:
![image](https://github.com/storybookjs/storybook/assets/4822129/c599632b-f744-4330-ab4f-20f0f70bd54b)

### To Reproduce

https://stackblitz.com/edit/github-za49nr?file=src%2Fstories%2FHeader.tsx

- Note the docstring in the interface `HeaderProps`
- Open the autogenerated docs page for `Header`
- Note the error in the JS console
- Note the presence of the element in the HTML for the argstable

### System

```bash
Storybook Environment Info:

  System:
    OS: Linux 6.2 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (20) x64 13th Gen Intel(R) Core(TM) i5-13600K
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 20.10.0 - /usr/bin/node
    Yarn: 1.22.19 - ~/Documents/Code/InvokeAI/invokeai/frontend/web/node_modules/.bin/yarn
    npm: 10.2.3 - /usr/bin/npm
    pnpm: 8.11.0 - ~/.node/bin/pnpm <----- active
  Browsers:
    Chrome: 117.0.5938.149
  npmPackages:
    @storybook/addon-essentials: ^7.6.4 => 7.6.4 
    @storybook/addon-interactions: ^7.6.4 => 7.6.4 
    @storybook/addon-links: ^7.6.4 => 7.6.4 
    @storybook/blocks: ^7.6.4 => 7.6.4 
    @storybook/manager-api: ^7.6.4 => 7.6.4 
    @storybook/react: ^7.6.4 => 7.6.4 
    @storybook/react-vite: ^7.6.4 => 7.6.4 
    @storybook/test: ^7.6.4 => 7.6.4 
    @storybook/theming: ^7.6.4 => 7.6.4 
    eslint-plugin-storybook: ^0.6.15 => 0.6.15 
    storybook: ^7.6.4 => 7.6.4
```

### Additional context

The stackblitz repro appears to be using a prerelease build of storybook 8. The issue is present on both my local install of `@latest` and on the stackblitz.

**Comment by psychedelicious** [comment]
Looks like you can do all sorts of nonsense with this.

Arbitrary-ish HTML:
![image](https://github.com/storybookjs/storybook/assets/4822129/db4ed9ae-c2b3-42d2-8eaf-50d9a739e50d)

Block interaction in the iframe:
![image](https://github.com/storybookjs/storybook/assets/4822129/3ba110a7-baf7-418a-95e3-5dface7cf71b)

The simple javascript I tried doesn't work - I added `onclick="(()=>{alert("oh hi")})()"` to the HTML and it got stripped out, leaving behind only the `div`.

I haven't tested this, but I suspect a dependency with types utilized by the storybook'd components could do some naughty things.

**Comment by shilman** [comment]
The `Description` block interprets the JSDoc comment as Markdown, which can include HTML.

To escape the elements, enclose them in backticks like this `\`<ThisIsNotAComponent />\``.

If you want to override the default descriptions, you can also use parameters. For more information, see the docs here: https://storybook.js.org/docs/api/doc-block-description
