### ISSUE TITLE
Remove @storybook/addon-storyshots

### ISSUE THREAD

**Issue by valentinpalkovic** [storybookjs/storybook#25185]
```[tasklist]
### Tasks
- [x] Remove StoryShots (https://github.com/storybookjs/storybook/pull/24438)
- [ ] https://github.com/storybookjs/storybook/issues/25326
```

**Comment by illume** [comment]
Hello. Is there a discussion somewhere why support for storyshots is being removed?

**Comment by valentinpalkovic** [comment]
The rationale behind this decision can be read here: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#storyshots-has-been-removed

**Comment by illume** [comment]
Thanks @valentinpalkovic 

I also found this link, https://storybook.js.org/docs/writing-tests/storyshots-migration-guide
Maybe that link would also be a good thing to add to this MIGRATION.md file?

**Comment by yannbf** [comment]
Thanks for the remark @illume! It's been done. :D
