### ISSUE TITLE
[Bug]: Cannot read properties of undefined (reading 'content') error in docs of storybook

### ISSUE THREAD

**Issue by i-suman** [storybookjs/storybook#25187]
### Describe the bug

All the Docs sections of storybooks is throwing either `Cannot read properties of undefined (reading 'content')` or `Cannot read properties of undefined (reading 'font')`

Earlier it was working fine, but just after below mentioned commits, the storybook docs started to break -

- [chore(deps-dev): bump @storybook/addon-interactions from 7.6.3 to 7.6.4](https://github.com/nearform/quantum/commit/261ac6925d9b51c266cba29c91f576b2e568df45)
- [chore(deps-dev): bump storybook from 7.6.3 to 7.6.4](https://github.com/nearform/quantum/commit/9eaff43dcb380590012494e346005f3b04c91180)
- [chore(deps-dev): bump @storybook/addon-essentials from 7.6.3 to 7.6.4](https://github.com/nearform/quantum/commit/001e3e2ea7fccb08fa5966add90a8d3a095a16cd)
- [chore(deps-dev): bump typescript from 5.3.2 to 5.3.3](https://github.com/nearform/quantum/commit/5041c669d9a1e8ab3e140ce18d20a6ce66d035e5)
- [chore(deps-dev): bump @babel/preset-env from 7.23.5 to 7.23.6](https://github.com/nearform/quantum/commit/179add41a13294f6bb8c3e81125501c73d44f74e)
- [chore(deps-dev): bump @storybook/react-vite from 7.6.3 to 7.6.4](https://github.com/nearform/quantum/commit/904742c794d060da4379af2cd9d99266e6bccb77)
- [chore(deps-dev): bump @storybook/addon-onboarding from 1.0.9 to 1.0.10](https://github.com/nearform/quantum/commit/f39043ce1b09bf81b54b7d7875532aabaa0d4cdb)
- [chore(deps-dev): bump prettier from 3.1.0 to 3.1.1](https://github.com/nearform/quantum/commit/921b37dd72313538ac7ab5e5b8a2319938ba00ea)
- [chore(deps-dev): bump @storybook/addon-links from 7.6.3 to 7.6.4](https://github.com/nearform/quantum/commit/7a613291b3bfae63d40ccad5600bbbc704e60999)

Screen shot of the error attached
<img width="1507" alt="Screenshot 2023-12-12 at 3 31 36 PM" src="https://github.com/storybookjs/storybook/assets/151526190/41a3ef51-e2f9-4827-9609-7adf12c18275">

### To Reproduce

Reproduction issue can be found here -
https://nearform.github.io/quantum/?path=/docs/components-buttongroup--docs

Reproduction repo is mentioned below -
https://github.com/nearform/quantum

To reproduce the issue locally -

- Pull the code down
- npm i
- npm run storybook
- navigate to http://localhost:6006

### System

```bash
System:
    OS: macOS 14.1.2
    CPU: (11) arm64 Apple M3 Pro
    Shell: 3.2.57 - /bin/sh
  Binaries:
    Node: 20.10.0 - /usr/local/bin/node
    npm: 10.2.3 - /usr/local/bin/npm <----- active
  Browsers:
    Chrome: 120.0.6099.71
    Safari: 17.1.2
  npmPackages:
    @storybook/addon-essentials: ^7.5.3 => 7.6.4 
    @storybook/addon-interactions: ^7.5.3 => 7.6.4 
    @storybook/addon-links: ^7.5.2 => 7.6.4 
    @storybook/addon-onboarding: ^1.0.8 => 1.0.10 
    @storybook/blocks: ^7.5.2 => 7.6.4 
    @storybook/react: ^7.5.2 => 7.6.4 
    @storybook/react-vite: ^7.5.2 => 7.6.4 
    @storybook/testing-library: ^0.2.2 => 0.2.2 
    eslint-plugin-storybook: ^0.6.15 => 0.6.15 
    storybook: ^7.5.2 => 7.6.4 
    storybook-dark-mode: ^3.0.1 => 3.0.3
```

**Comment by shilman** [comment]
It's working fine for me when I run your repro steps. I assume you figured it out? Closing for now but lmk if you're still having problems.
