### ISSUE TITLE
[Bug]: Dev build breaks upon error or renaming file

### ISSUE THREAD

**Issue by paddotk** [storybookjs/storybook#25195]
### Describe the bug

Whenever I rename a file or do something in the code that causes an error, this nearly always breaks the application. The only way to get it to work again is to stop running Storybook, remove all the caches, and run again. Sometimes this means a simple debugging attempt can take half an hour because every time it has to build again, it takes several minutes just to load.

### System

```bash
System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Xeon(R) Platinum 8168 CPU @ 2.70GHz
  Binaries:
    Node: 16.10.0 - C:\Program Files\nodejs\node.EXE
    npm: 7.24.0 - C:\Program Files\nodejs\npm.CMD <----- active
  Browsers:
    Chrome: 66.0.3359.139
    Edge: Spartan (44.19041.3570.0), Chromium (117.0.2045.60)
  npmPackages:
    @storybook/addon-docs: ^7.5.2 => 7.5.2
    @storybook/addon-essentials: ^7.5.2 => 7.5.2
    @storybook/addon-interactions: ^7.5.2 => 7.5.2
    @storybook/addon-links: ^7.5.2 => 7.5.2
    @storybook/addon-styling-webpack: ^0.0.5 => 0.0.5
    @storybook/angular: ^7.5.2 => 7.5.2
    @storybook/blocks: ^7.5.2 => 7.5.2
    @storybook/testing-library: ^0.2.2 => 0.2.2
    storybook: ^7.5.2 => 7.5.2
```

**Comment by paddotk** [comment]
An example of the error I see (in the console):
```
runtime.js:4  Error: Unable to index ./src/stories/layout/Overview.stories.ts:
  Error: Could not parse import/exports with acorn: SyntaxError: Unexpected token
```
When it breaks, the base layout of Storybook displays but nothing in the sidebar or content area.

**Comment by shilman** [comment]
Do you a have a reproduction repo you can share? If not, can you create one? Go to https://storybook.new or see [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce). Thank you! 🙏
