### ISSUE TITLE
[Documentation]: Rollup Not Supported

### ISSUE THREAD

**Issue by ztroop** [storybookjs/storybook#25206]
### Describe the problem

I believe the documentation suggests that it should be able to use `rollup`, but it clearly does not during the installation process. I understand that `Vite` uses `Rollup` behind the scenes... Would someone mind clarifying?

```sh
➜ npx storybook@latest init

Run `npm audit` for details.
. ✓
✖
We were not able to detect the right builder for your project. Please select one: › Vite, Webpack
```

I think there's a disconnect between the documentation and what the CLI installer is presenting.

**Comment by shilman** [comment]
Vite uses rollup for production builds, and its own esbuild-based dev server. If your app is based on Rollup, Storybook's Vite builder is probably the closest approximation that's supported. Hope that helps!
