### ISSUE TITLE
[Bug]: Can not scroll down the detail page

### ISSUE THREAD

**Issue by iabu94** [storybookjs/storybook#25200]
### Describe the bug

![image](https://github.com/storybookjs/storybook/assets/27818818/24d49dd9-391f-4e88-aa92-fc5072bf7389)
As the image shows there are more contents on the detail page. But I cannot scroll down to see them. And there are not even a scroll bar to scroll as well. I need to zoom out a lot to see all the contents

### To Reproduce

Just install the angular storybook and use

**Comment by shilman** [comment]
Do you a have a reproduction repo you can share? If not, can you create one? Go to https://storybook.new or see [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce). Thank you! 🙏
