### ISSUE TITLE
[Bug]: Disabling storyStoreV7 causes the browser to not being opened on storybook dev command

### ISSUE THREAD

**Issue by MaceM8** [storybookjs/storybook#25213]
### Describe the bug

By running storybook dev command, a new browser window should be opened. This does not work when using feature `storyStoreV7: false`.

Please fix this minor issue, so browser opening behavior si consistent and is not dependent on configuration of feature.

### To Reproduce

- Install clean project and init Storybook
- Open main.ts
- Add config `features: {
        storyStoreV7: false
    },` to `main.ts` file
- Run `yarn storybook dev -p 6006` command

Storybook starts, but browser is not opened. 

### System

```bash
Storybook Environment Info:

  System:
    OS: macOS 14.1.1
    CPU: (12) arm64 Apple M2 Max
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.2 - /opt/homebrew/opt/nvm/versions/node/v18.18.2/bin/node
    Yarn: 1.22.19 - /opt/homebrew/opt/nvm/versions/node/v18.18.2/bin/yarn <----- active
    npm: 9.8.1 - /opt/homebrew/opt/nvm/versions/node/v18.18.2/bin/npm
    pnpm: 8.10.2 - /opt/homebrew/opt/nvm/versions/node/v18.18.2/bin/pnpm
  Browsers:
    Edge: 120.0.2210.61
    Safari: 17.1
  npmPackages:
    @storybook/addon-essentials: ^7.6.4 => 7.6.4 
    @storybook/addon-interactions: ^7.6.4 => 7.6.4 
    @storybook/addon-links: ^7.6.4 => 7.6.4 
    @storybook/addon-onboarding: ^1.0.10 => 1.0.10 
    @storybook/blocks: ^7.6.4 => 7.6.4 
    @storybook/react: ^7.6.4 => 7.6.4 
    @storybook/react-vite: ^7.6.4 => 7.6.4 
    @storybook/test: ^7.6.4 => 7.6.4 
    eslint-plugin-storybook: ^0.6.15 => 0.6.15 
    storybook: ^7.6.4 => 7.6.4
```

**Comment by valentinpalkovic** [comment]
Thank you for reaching out! 

I wanted to let you know that in Storybook 8.0.0, we are transitioning away from storyStoreV6 as part of our ongoing improvements, which you can read more about in our [migration guide](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#storystorev6-and-storiesof-is-deprecated). 

We encourage you to switch to storyStoreV7 to take advantage of the latest features and updates. While we understand this change might require some adjustments, please know that this decision is made to enhance the overall experience. 

As we are now focusing our resources on supporting storyStoreV7, I'll be closing this issue, but we're here to assist if you have any questions or need guidance during your migration process. 

Thanks for your understanding and support!
