### ISSUE TITLE
[Bug]: sb migrate with flags doesn't process files

### ISSUE THREAD

**Issue by valentinpalkovic** [storybookjs/storybook#25226]
### Describe the bug

Running

```
npx storybook@latest migrate csf-2-to-3 --glob="**/*.stories.tsx" --parser=tsx
```

doesn't process any files. The output is the following:

```
=> Applying csf-2-to-3: 33 files
No files selected, nothing to do. 
All done. 
Results: 
0 errors
0 unmodified
0 skipped
0 ok
```

### To Reproduce

1. Checkout https://github.com/washingtonpost/wpds-ui-kit/tree/v2
2. Run the automigration: `npx storybook@latest migrate csf-2-to-3 --glob="**/*.stories.tsx" --parser=tsx`

**Comment by valentinpalkovic** [comment]
cc @vanessayuenn. We should fix this automigration for 8.0.

**Comment by vladsovetov** [comment]
Probably too obvious, but just in case somebody is blocked by this then you can run not the latest, but e.g. v7
```
npx storybook@7.0.0 migrate csf-2-to-3 --glob="**/*.stories.tsx" --parser=tsx
```

in my case I used pnpm and successfully ran this command
```
pnpm dlx storybook@7.0.0 migrate csf-2-to-3 --glob="src/**/*.stories.tsx"
```

**Comment by RamonGebben** [comment]
> Probably too obvious, but just in case somebody is blocked by this then you can run not the latest, but e.g. v7
> 
> ```
> npx storybook@7.0.0 migrate csf-2-to-3 --glob="**/*.stories.tsx" --parser=tsx
> ```
> 
> in my case I used pnpm and successfully ran this command
> 
> ```
> pnpm dlx storybook@7.0.0 migrate csf-2-to-3 --glob="src/**/*.stories.tsx"
> ```

This worked for me. Sadly it only picked up `41` of the `504` files found.

**Comment by turboteddy** [comment]
The workaround didn't work for me. 
```
=> Applying csf-2-to-3: <xx> files
No files selected, nothing to do. 
All done. 
```

**Comment by LouisCullen** [comment]
Using storybook@7.5.3 works for me but later doesn't

**Comment by yannbf** [comment]
Just found out which release caused this issue, to hopefully assist in fixing it:
https://github.com/storybookjs/storybook/releases/tag/v7.6.0-alpha.7

For anyone trying the command, you can use:
```
npx storybook@7.5.3 migrate csf-2-to-3 --glob="**/*.stories.tsx" --parser=tsx
```

or
```
npx storybook@7.6.0-alpha.6 migrate csf-2-to-3 --glob="**/*.stories.tsx" --parser=tsx
```
