### ISSUE TITLE
[Bug]: TestRunner snapshots failing when running on build result (MUI / Emotion).

### ISSUE THREAD

**Issue by luciob** [storybookjs/storybook#25246]
### Describe the bug

When running the test-runner suite against my non-deployed storybook (following this [example](https://storybook.js.org/docs/writing-tests/test-runner#run-against-non-deployed-storybooks) on GH Actions) the test fails due to mismatch in generated classnames. Snapshots are generated while developing (against a Storybook dev instance), so the generated code is different, however I've tried doing the eject of test-runner and using `@emotion/jest` serializer as described [here](https://emotion.sh/docs/testing) but that didn't solve the issue.

<img width="622" alt="Screenshot 2023-12-15 at 17 58 59" src="https://github.com/storybookjs/storybook/assets/61870694/b8cbeb76-130b-4013-b7c3-8de8367e9f23">

### To Reproduce

To reproduce:
1- Clone the [repo](https://github.com/melfore/mosaic/tree/297-tests-migrate-from-enzyme-to-testing-library)
2- Run `npm run build:storybook`
3- Run `npx http-server docs/latest --port 6006 --silent` to serve the result of step 2
4- Open a new shell and run `npm test` with all files option

### System

```bash
System:
    OS: macOS 14.1.1
    CPU: (8) arm64 Apple M1 Pro
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
    npm: 10.2.2 - ~/Works/melfore/libraries/mosaic/node_modules/.bin/npm <----- active
  Browsers:
    Chrome: 120.0.6099.109
    Safari: 17.1
  npmPackages:
    @storybook/addon-actions: ^7.5.2 => 7.5.2 
    @storybook/addon-coverage: ^0.0.9 => 0.0.9 
    @storybook/addon-essentials: ^7.5.2 => 7.5.2 
    @storybook/addon-interactions: ^7.5.2 => 7.5.2 
    @storybook/addon-links: ^7.5.2 => 7.5.2 
    @storybook/jest: ^0.2.3 => 0.2.3 
    @storybook/react: ^7.5.2 => 7.5.2 
    @storybook/react-webpack5: ^7.5.2 => 7.5.2 
    @storybook/test-runner: ^0.13.0 => 0.13.0 
    @storybook/testing-library: ^0.2.2 => 0.2.2 
    eslint-plugin-storybook: ^0.6.15 => 0.6.15 
    storybook: ^7.5.2 => 7.5.2
```

**Comment by yannbf** [comment]
Hey there @luciob in cases like that you will need to write your own snapshot serializer which replaces strings based on a regex: https://storybook.js.org/docs/writing-tests/storyshots-migration-guide#the-format-of-the-snapshot-files-is-different-from-the-ones-generated-by-the-storyshots-addon

something like this, maybe
```js
let text = "css-asd8i213j-MuiButtonIcon";
let pattern = /css-(.*?)-Mui.*/;
let newText = text.replace(pattern, "css-$1");

// becomes css-asd8i213j
```

**Comment by luciob** [comment]
Hi @yannbf thanks for your suggestion!
I followed the steps reported and managed to get it working.

I needed to make a slight change to the suggested serializer method because of some strange classnames and tags being generated by MUI in dev mode that are stripped out when instead it is built in PRD mode.

```
const jestSerializerHtml = require("jest-serializer-html");

const CSS_DYNAMIC_ID = new RegExp("css(-[a-zA-Z0-9]*)*", "g");
const MUI_CLONE_ELEMENT = new RegExp('data-mui-internal-clone-element="true"', "g");

module.exports = {
  serialize(val) {
    const withFixedIds = val
      .replace(CSS_DYNAMIC_ID, "css-mui-classname")
      .replace(MUI_CLONE_ELEMENT, "");
    return jestSerializerHtml.print(withFixedIds);
  },
  test(val) {
    return jestSerializerHtml.test(val);
  },
};
```

**Comment by vanessayuenn** [comment]
Closing this issue; sounds like this is resolved.
