### ISSUE TITLE
[Bug]: Cannot use Canvas for Story objects which have more than one key.

### ISSUE THREAD

**Issue by hashraf38** [storybookjs/storybook#25299]
### Describe the bug

When trying to use the `Canvas` block. I am running into the following issue.

In `Button.stories.ts`:
```
export const Primary: Story = {
  args: {
    primary: true,
    label: 'Button',
  },
};
```

In `Button.mdx`:

`<Canvas of={ButtonStories.Primary}/>`

Works perfectly fine, but when you change the story in `Button.stories.ts` to something like:

```
export const Primary: Story = {
  tags: ['isHidden'],
  args: {
    primary: true,
    label: 'Button',
  },
};
```

or

```
export const Primary: Story = {
  args: {
    primary: true,
    label: 'Button',
  },
  render: (args) => <Button {...args}/>
};
```

The `Canvas` block no longer works. It returns an `unexpected token` error.

### To Reproduce

https://stackblitz.com/edit/github-4dnpbs?file=src%2Fstories%2FButton.stories.ts

A straightforward reproduction - just add another key-value pair to a story object and use the `Canvas` block in the `.mdx` file.

### System

```bash
System:
    OS: Linux 6.2 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (8) x64 Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.20.0 - ~/.nvm/versions/node/v16.20.0/bin/node
    npm: 8.19.4 - ~/.nvm/versions/node/v16.20.0/bin/npm <----- active
  npmPackages:
    @storybook/addon-essentials: ^7.6.6 => 7.6.6 
    @storybook/core-server: ^7.6.6 => 7.6.6 
    @storybook/react-webpack5: ^7.6.6 => 7.6.6 
    @storybook/theming: ^7.6.6 => 7.6.6 
    eslint-plugin-storybook: ^0.6.15 => 0.6.15
```

**Comment by Marklb** [comment]
I checked the reproduction, but I don't see any problem. I tried updating the `Primary` story to both snippets and the second snippet gave me an error, but that error was just because JSX wasn't configured.

Is the error expected to be seen in the reproduction, without making any change?

Where do you see the error? Terminal, devtools, full page, canvas element?

**Comment by hashraf38** [comment]
I get the following full page error in Storybook.
![image](https://github.com/storybookjs/storybook/assets/152533400/a55ebfaa-bee8-455d-91b4-c8092c197418)
