### ISSUE TITLE
[Bug]: TabsState in storybook-component is preventing a tab re-render

### ISSUE THREAD

**Issue by aLosada7** [storybookjs/storybook#25308]
### Describe the bug

The tabs storybook component is preventing tabs from update https://github.com/storybookjs/storybook/blob/next/code/ui/components/src/components/tabs/tabs.stories.tsx

### To Reproduce

Whenever PanelContent re-renders, List is not re-render (component has not optimisation techniques, and I've tried removing TabsState and it works fine)
```import React, { Fragment } from 'react';
import { themes, convert } from '@storybook/theming';
import { TabsState, Placeholder } from '@storybook/components';
import { List } from './List';

export const PanelContent = ({ events, clearData }) => {
  return (
    <TabsState
      initial="events"
      backgroundColor={convert(themes.normal).background.hoverable}
      height="100%"
    >
      <div
        id="overview"
        title="Overview"
        color={convert(themes.normal).color.secondary}
      >
        Some content
      </div>
      <div
        id="events"
        title={`${events.length} Analytics calls`}
        color={convert(themes.normal).color.positive}
      >
        <List items={events} clearData={clearData} />
      </div>
    </TabsState>
  );
};
```

**Comment by shilman** [comment]
Do you a have a reproduction repo you can share? If not, can you create one? Go to https://storybook.new or see [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce). Thank you! 🙏

**Comment by dsebastian** [comment]
@aLosada7 Had the same issue for an internal addon we built. As a workaround I added a `key` prop to it and it seemed to fix the issue.
    <TabsState
      initial={foo}
      key={window.location.href}
    >
