### ISSUE TITLE
[Bug]: Main section disappears when navigating to addon tab

### ISSUE THREAD

**Issue by rbardini** [storybookjs/storybook#25322]
### Describe the bug

While upgrading from Storybook 7.0 to 7.6, I noticed that the main section gets hidden when navigating to an addon tab. ([Playroom](https://github.com/rbardini/storybook-addon-playroom) in this case)

Manually removing the `hidden` attribute from the wrapping `<div>` in browser devtools fixes the issue, i.e. the addon matches the route and renders correctly, but Storybook hides it.

Interestingly, it doesn't seem to affect docs pages. Possibly related to #23292.

### To Reproduce

Open the following deploy preview from https://github.com/rbardini/storybook-addon-playroom/pull/54, navigate to stories and click the _Playroom_ tab:

> https://deploy-preview-54--storybook-addon-playroom.netlify.app/

---

I've also reproduced it in [storybookjs/addon-kit](https://github.com/storybookjs/addon-kit) after bumping Storybook dependencies to their latest versions:

```sh
git clone git@github.com:storybookjs/addon-kit.git && cd addon-kit
npx storybook@latest upgrade
npm start
```

![Demo](https://github.com/storybookjs/storybook/assets/874370/4539d322-4480-4393-b2dd-daa16d2e665e)

### System

```bash
System:
  OS: macOS 14.2.1
  CPU: (10) arm64 Apple M1 Pro
  Shell: 5.9 - /bin/zsh
Binaries:
  Node: 21.5.0 - /opt/homebrew/bin/node
  npm: 10.2.5 - /opt/homebrew/bin/npm <----- active
Browsers:
  Chrome: 120.0.6099.129
  Safari: 17.2.1
npmPackages:
  @storybook/react: ^7.0.0 => 7.6.6 
  @storybook/react-vite: ^7.0.0 => 7.6.6 
  storybook: ^7.0.0 => 7.6.6
```

**Comment by ndelangen** [comment]
Hmm, yeah that looks quite serious, I will have to take a look.
