### ISSUE TITLE
Determine whether to remove deprecated props from the Button component

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#25334]
It's unsure whether these deprecated props should be removed in the `Button` component:
https://github.com/storybookjs/storybook/blob/b30db0ec2769a86857d27384a97d6a2b7205e408/code/ui/components/src/components/Button/Button.tsx#L18

@cdedreuille Please let us know whenever you can 🙏

**Comment by shilman** [comment]
Cc @JReinhold @cdedreuille

**Comment by cdedreuille** [comment]
All deprecated props in Bitcoin and IconButton were made for 8.0. We should remove them in 9.0
