### ISSUE TITLE
Remove deprecated props from Canvas block

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#25339]
It's unclear whether to remove these deprecated properties from the `Canvas` block component in Storybook 8:
https://github.com/storybookjs/storybook/blob/a756d2ab4b9024b6afb46bfb7fdd21b1e832836a/code/ui/blocks/src/blocks/Canvas.tsx#L24

@JReinhold please let us know whenever you can 🙏

**Comment by shilman** [comment]
@JReinhold I think we should have a way to do `docs-only` stories before we remove this. I think I'm pretty close to having something here for 8.0 -- we just need to sit down and agree on some stuff. I can probably code it up in a day once we do. If we can't make that happen for some reason I suggest we punt on this until 9.0.

**Comment by JReinhold** [comment]
@shilman I guess your reason being that the new props only allow for a single story, meaning that users wanting multi-story canvases are left out? Unless we provide a way to write docs-only stories, which would be referencable by the Canvas block as a single story?

I can get behind that.

**Comment by shilman** [comment]
Exactly @JReinhold

**Comment by yannbf** [comment]
I'll leave it up to you @shilman, feel free to close this issue as unplanned if it won't work out!

**Comment by shilman** [comment]
I've implemented an approach to hiding stories from the sidebar https://github.com/storybookjs/storybook/pull/25328, and am confident we can get it into 8.0. Therefore we can move forward with this removal! 🚀
