### ISSUE TITLE
Remove deprecated props from Story block

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#25335]
It's unclear whether to remove these deprecated properties from the `Story` block component in Storybook 8:
https://github.com/storybookjs/storybook/blob/0139b3c248404cd2dfcbc164a9f29e890a47140c/code/ui/blocks/src/blocks/Story.tsx#L33

@JReinhold please let us know whenever you can 🙏

**Comment by JReinhold** [comment]
Yes, remove them.
