### ISSUE TITLE
Remove deprecated props from Description block

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#25338]
It's unclear whether to remove these deprecated properties from the `Description` block component in Storybook 8:
https://github.com/storybookjs/storybook/blob/0139b3c248404cd2dfcbc164a9f29e890a47140c/code/ui/blocks/src/blocks/Description.tsx#L33

@JReinhold please let us know whenever you can 🙏

**Comment by JReinhold** [comment]
🪓
