### ISSUE TITLE
Remove MenuItemIcon component in the Sidebar

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#25333]
Location:
https://github.com/storybookjs/storybook/blob/7a10141273f5b4a31321872d6829a596ee100cb9/code/ui/manager/src/components/sidebar/Menu.tsx#L85

**Comment by yannbf** [comment]
This one is tricky and I need your help @cdedreuille.

the MenuItemIcon is deprecated and it asks users to use `Icons` from `@storybook/components` instead.
However, `Icons` seem to also be deprecated and it asks users to use the `@storybook/icons` package instead.

The other tricky part is that the MenuItemIcon component has a specific order of either using an Icon, an Img or a Placeholder element. What's the correct equivalent for MenuItemIcon then?

**Comment by cdedreuille** [comment]
We should only use icons from @storybook/icons going forward. I need to look more closely to this one to see how to best handle it.

**Comment by cdedreuille** [comment]
I drafted a PR. The component was not used anywhere as I believe we just changed the way we do it and forgot to remove this old component. I removed it and tested it. I could not find any bug but it would be great to have an extra pair of eyes.
