### ISSUE TITLE
Remove deprecated props from Primary block

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#25337]
It's unclear whether to remove these deprecated properties from the `Primary` block component in Storybook 8:
https://github.com/storybookjs/storybook/blob/d3cabc6259d2649a30c58004ae7f01a63a99b2ba/code/ui/blocks/src/blocks/Primary.tsx#L12

@JReinhold please let us know whenever you can 🙏

**Comment by JReinhold** [comment]
Yes, remove them.
