### ISSUE TITLE
Remove StoryIndexer in favor of Indexer

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#25343]
It's unclear whether to remove the deprecated`StoryIndexer` in Storybook 8:
https://github.com/storybookjs/storybook/blob/49ef8fa68f10a45fe26aaa1b73c283d0a558197f/code/lib/types/src/modules/indexer.ts#L84

https://github.com/storybookjs/storybook/blob/3b94da1a9f4e5942dae067f277c2a4672271cf2e/code/lib/types/src/modules/core-common.ts#L524

@shilman please let us know whenever you can, especially if there are extra migration notes needed 🙏

**Comment by shilman** [comment]
Yes `Indexer` only from 8.0 please!
