### ISSUE TITLE
Remove Story types in favor of StoryFn

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#25341]
The following renderers need removal of the `Story` type in favor of the `StoryFn` type:

**Web Components:** https://github.com/storybookjs/storybook/blob/e56998becdb6437ec8aa128653ebfc946c409e44/code/renderers/web-components/src/public-types.ts#L39

**Server:**
https://github.com/storybookjs/storybook/blob/e56998becdb6437ec8aa128653ebfc946c409e44/code/renderers/server/src/public-types.ts#L38

**Preact:**
https://github.com/storybookjs/storybook/blob/e56998becdb6437ec8aa128653ebfc946c409e44/code/renderers/preact/src/public-types.ts#L39

**HTML:**
https://github.com/storybookjs/storybook/blob/e56998becdb6437ec8aa128653ebfc946c409e44/code/renderers/html/src/public-types.ts#L39

**Angular:**
https://github.com/storybookjs/storybook/blob/e56998becdb6437ec8aa128653ebfc946c409e44/code/frameworks/angular/src/client/public-types.ts#L40

**Vue3:**
https://github.com/storybookjs/storybook/blob/1c604e3c176057b091a7d6608ecbc97141106254/code/renderers/vue3/src/public-types.ts#L78

**For React,** there are more utility types which need removal:
```
DecoratorFn -> Decorator
Story -> StoryFn
ComponentStoryFn -> StoryFn
ComponentMeta -> Meta
ComponentStoryObj -> StoryObj
```

Location:
https://github.com/storybookjs/storybook/blob/ef847b9bf1b7ec56cabfed1f431ab0e28dba2f47/code/renderers/react/src/public-types.ts#L126

**Comment by yannbf** [comment]
It's unclear to me whether there is already a codemod for this, or how we expect users to migrate.

cc @kasperpeulen @shilman

**Comment by shilman** [comment]
Looks like there is already a codemod:

https://github.com/storybookjs/storybook/blob/next/code/lib/codemod/src/transforms/upgrade-deprecated-types.ts#L19-L22

**Comment by nkabrown** [comment]
I think the Angular framework was overlooked in PR #25477. It did not remove the `Story` type from `storybook/code/frameworks/angular/src/client/public-types.ts`.

**Comment by shilman** [comment]
Thanks @nkabrown !
