### ISSUE TITLE
Determine whether to remove deprecated methods from core-client start module

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#25365]
It's unclear whether to remove these deprecated properties from the `Story` block component in Storybook 8:

**raw:**
https://github.com/storybookjs/storybook/blob/acdec9c85184fb8fc436b7ea855e519c2cf487c3/code/lib/preview-api/src/modules/core-client/start.ts#L39

**forceReRender:**
https://github.com/storybookjs/storybook/blob/acdec9c85184fb8fc436b7ea855e519c2cf487c3/code/lib/preview-api/src/modules/core-client/start.ts#L49

**configure:**
https://github.com/storybookjs/storybook/blob/acdec9c85184fb8fc436b7ea855e519c2cf487c3/code/lib/preview-api/src/modules/core-client/start.ts#L55

**clientApi:**
https://github.com/storybookjs/storybook/blob/acdec9c85184fb8fc436b7ea855e519c2cf487c3/code/lib/preview-api/src/modules/core-client/start.ts#L60

@ndelangen @shilman  please let us know whenever you can and what can be done migration-wise 🙏

**Comment by shilman** [comment]
I think this will be be removed as part of removing StoryStorev6. Please double check after that PR has been merged.
