### ISSUE TITLE
Remove skipBabel option from core-common

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#25360]
Location:
https://github.com/storybookjs/storybook/blob/3b94da1a9f4e5942dae067f277c2a4672271cf2e/code/lib/types/src/modules/core-common.ts#L256

There are many more places where skipBabel is used which should be worked on.

**Comment by valentinpalkovic** [comment]
Is superseded by https://github.com/storybookjs/storybook/issues/25172
