### ISSUE TITLE
Determine whether to remove subcomponents from meta

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#25363]
It's unclear whether to remove subcomponents from Meta in Storybook 8:
https://github.com/storybookjs/storybook/blob/975ad7604b8236bad273d6498362b50af40975ee/code/lib/types/src/modules/addons.ts#L296

@JReinhold @shilman please let us know whenever you can, and what can be done migration-wise 🙏

**Comment by shilman** [comment]
I think we should keep these & figure out in 9.0. WDYT @JReinhold ?

**Comment by JReinhold** [comment]
We'll keep this around, and maybe even revert the deprecation altogether if time allows it.
