### ISSUE TITLE
Determine whether to remove deprecated hooks from storybook store and addons module

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#25364]
It's unclear whether to remove the deprecated hooks in Storybook 8:

**useSharedState:**
https://github.com/storybookjs/storybook/blob/126ed7f7d8985bd3048476399232aaf18923cf7b/code/lib/preview-api/src/modules/store/hooks.ts#L39

**useAddonState:**
https://github.com/storybookjs/storybook/blob/126ed7f7d8985bd3048476399232aaf18923cf7b/code/lib/preview-api/src/modules/store/hooks.ts#L86

**getAddonState:**
https://github.com/storybookjs/storybook/blob/78bcb62774bb5a6d989a88dd23dfe97355839439/code/lib/manager-api/src/modules/addons.ts#L79

**setAddonState:**
https://github.com/storybookjs/storybook/blob/78bcb62774bb5a6d989a88dd23dfe97355839439/code/lib/manager-api/src/modules/addons.ts#L67

@ndelangen @shilman please let us know whenever you can, and what can be done migration-wise (especially for addon authors) 🙏

**Comment by shilman** [comment]
This is still used in several core addons. We should keep it until we have a plan for how to migrate off. @ndelangen if you already have a plan, happy to discuss here.

**Comment by ndelangen** [comment]
Do not remove yet.
