### ISSUE TITLE
Determine whether to remove deprecated methods from client-api

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#25367]
It's unclear whether to remove these deprecated methods from client-api module in Storybook 8:

raw:
https://github.com/storybookjs/storybook/blob/8d612f3c245ee9fb4810d7ae07636690e2e43c65/code/lib/preview-api/src/modules/client-api/ClientApi.ts#L369

get _storyStore:
https://github.com/storybookjs/storybook/blob/8d612f3c245ee9fb4810d7ae07636690e2e43c65/code/lib/preview-api/src/modules/client-api/ClientApi.ts#L374

@ndelangen @shilman please let us know whenever you can, and what can be done migration-wise 🙏 

This might be related to other deprecations in #25365

**Comment by shilman** [comment]
This should also be removed as part of StoryStoreV6 removal AFAIK
