### ISSUE TITLE
Remove deprecated serverChannel implementations

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#25366]
serverChannel:
https://github.com/storybookjs/storybook/blob/f78038be5b95fa309abd469aaa59f8a94db8ef76/code/lib/preview-api/src/modules/addons/main.ts#L18

setServerChannel:
https://github.com/storybookjs/storybook/blob/f78038be5b95fa309abd469aaa59f8a94db8ef76/code/lib/preview-api/src/modules/addons/main.ts#L63

hasServerChannel:
https://github.com/storybookjs/storybook/blob/f78038be5b95fa309abd469aaa59f8a94db8ef76/code/lib/preview-api/src/modules/addons/main.ts#L53

getServerChannel:
https://github.com/storybookjs/storybook/blob/f78038be5b95fa309abd469aaa59f8a94db8ef76/code/lib/preview-api/src/modules/addons/main.ts#L38

Seems like this change is going to be a little more involved, so here's the PR that introduced it for more context: https://github.com/storybookjs/storybook/pull/22940

**Comment by shilman** [comment]
Cc @ndelangen

**Comment by ndelangen** [comment]
I'm fairly sure, nothing uses these methods anymore, so it's likely fine to remove them?
