### ISSUE TITLE
Remove deprecated properties from api-stories

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#25361]
It's unclear whether to remove these deprecated properties from the `api-stories` module in Storybook 8:
https://github.com/storybookjs/storybook/blob/bf63829a5e374a0b734a50d5e13035676685df78/code/lib/types/src/modules/api-stories.ts#L13

@ndelangen @shilman please let us know whenever you can, and what should be done migration-wise 🙏

**Comment by shilman** [comment]
Yes please remove them. They are superceded by `type: 'root' | 'group' | 'component' | 'docs' | 'story'`

**Comment by yannbf** [comment]
@shilman can you explain what this code becomes?

```ts
useEffect(() => {
    if (api && props.isHighlighted && item.isComponent) { // <-- this becomes `item.type === 'component'` I assume
      api.emit(
        PRELOAD_ENTRIES,
        { ids: [item.isLeaf ? item.id : item.children[0]] }, // what about item.isLeaf?
        { options: { target: item.refId } }
      );
    }
  }, [props.isHighlighted, item]);
```

**Comment by ndelangen** [comment]
isLeaf =  `'docs' | 'story'`, I think.

**Comment by yannbf** [comment]
Reminder to shelve this until the storyStoreV6 work is done.
