### ISSUE TITLE
Remove deprecated `addons` and `mockChannel` from addon api

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#25368]
It's unclear whether to remove these deprecated methods (addons, mockChannel) in Storybook 8:
https://github.com/storybookjs/storybook/blob/62c4b8a28425a33d4b37b7434ee771514b80d24a/code/lib/preview-api/src/index.ts#L32

@ndelangen @shilman  please let us know whenever you can, and what can be done migration-wise 🙏

**Comment by shilman** [comment]
I'll let @ndelangen field this one

**Comment by yannbf** [comment]
> remove!
> 
> Why is it unclear?

Thanks! Anything that doesn't explicitly mention "This will be removed in Storybook 8" is unclear to me. I am going on the safe side so we don't end up having unintended side effects. Some of the issues I opened turned out to be:
- Yes, remove it
- No, it's a Storybook 9.0 removal
- No, let's not remove it yet
- Not sure, we need more info

**Comment by yannbf** [comment]
@ndelangen what are the migration notes for this removal? There are plenty of places which use the `addons` api in the codebase which need to be updated:

https://github.com/search?q=repo%3Astorybookjs%2Fstorybook+%22import+%7B+addons%22&type=code

it's mostly code like this:

```
addons.getChannel()
```

**Comment by valentinpalkovic** [comment]
As discussed with @ndelangen, we keep these exports around for another major version, since they are even used internally a lot, and there seems not to be an easy migration path for them
