### ISSUE TITLE
Remove config preset field in favor of previewAnnotations

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#25374]
Location:
https://github.com/storybookjs/storybook/blob/94f4361eaba818bc01433b47908ad9ae75d90724/code/lib/core-server/src/presets/common-preset.ts#L176

p.s.: this can impact the work of many addon authors and should require a proper follow up

**Comment by shilman** [comment]
This one could break a bunch of addons, since older versions of the addon-kit might have used it? If so, we should feature it i the addons migration guide.
