### ISSUE TITLE
[Bug]: I can't build my Sveltekit storybook: Top-level await is not available in the configured target environment

### ISSUE THREAD

**Issue by alexbjorlig** [storybookjs/storybook#25399]
### Describe the bug

When I try to build my Sveltekit storybook, I get the error: 

```
[vite:esbuild-transpile] Transform failed with 1 error:
assets/index.stories-!~{00F}~.js:12900:26: ERROR: Top-level await is not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari14" + 2 overrides)
```

We are using Svetekit v2.0 (and hence vite v5)

### System

```bash
Storybook Environment Info:

  System:
    OS: macOS 14.2.1
    CPU: (10) arm64 Apple M1 Max
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    npm: 10.0.0 - ~/.nvm/versions/node/v18.17.1/bin/npm <----- active
    pnpm: 8.12.0 - ~/.nvm/versions/node/v18.17.1/bin/pnpm
  Browsers:
    Chrome: 120.0.6099.129
    Safari: 17.2.1
```
```


### Additional context

**package.json**

```
        "@storybook/addon-essentials": "^7.6.6",
        "@storybook/addon-interactions": "^7.6.6",
        "@storybook/addon-links": "^7.6.6",
        "@storybook/addon-storysource": "^7.6.6",
        "@storybook/addon-svelte-csf": "^4.1.0",
        "@storybook/addon-themes": "^7.6.6",
        "@storybook/blocks": "^7.6.6",
        "@storybook/jest": "^0.2.3",
        "@storybook/svelte": "^7.6.6",
        "@storybook/sveltekit": "^7.6.6",
        "@storybook/test": "^7.6.6",
        "@storybook/test-runner": "^0.16.0",
        "@storybook/testing-library": "^0.2.2",
```

**Comment by valentinpalkovic** [comment]
Can you give some context of where you are using top-level await?

**Comment by alexbjorlig** [comment]
Hi, 
I discovered that the `Top-level await`  is from the package `bson` that we use.

But I don't understand the target printed to the console?

We target the following browsers in our `vite.config.js`: `['es2022', 'edge89', 'firefox89', 'chrome89', 'safari15'],`

Where does storybook read the target from, and should it maybe be using the `vite.config` when running with Sveltekit?

**Comment by alexbjorlig** [comment]
Hi @valentinpalkovic  - here are steps to reproduce ([and a repo](https://github.com/21RISK/svelte-story-bson)).

1. Create new sveltekit-app with `npm create svelte@latest`
2. Add Storybook with `npx storybook`
3. Add `import {ObjectId} from 'bson';` and try to build

The build will now fail with:

```
[vite:esbuild-transpile] Transform failed with 1 error:
assets/Button-!~{00m}~.js:90:26: ERROR: Top-level await is not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari14" + 2 overrides)
```

**Comment by JReinhold** [comment]
We don't include the `build` property of a user's Vite config because it has a high risk of colliding with Storybook's build settings - see https://github.com/storybookjs/storybook/pull/19978/commits/0a86cd2f2cc586c0ee02186ebf2ea9c6d71f1452#diff-58844c0c6a00ae8bad85eb2369a25ae5b43f04c8262221bd9187d07159f0f87c

You can instead add the configuration you need like the build target to `viteFinal` in `main.ts`:

```ts

const config = {
    ...
	viteFinal: async (config) => {
		if(!config.build) {
			config.build = {};
		}
		config.build.target = ['es2022', 'edge89', 'firefox89', 'chrome89', 'safari15'];
		return config;
	}
};
export default config;
```

I did this in the repo and it worked.

This sounds like something we want to document though, would you like to open a PR to improve the documentation?

cc @jonniebigodes

**Comment by alexbjorlig** [comment]
@JReinhold  thank you so much, it works!

```
✓ built in 15.33s
info => Preview built (17 s)
info => Output directory: /Users/alexbjorlig/Documents/eddystone/storybook-static
```

✨
