### ISSUE TITLE
Auto migration: Detect .stories.mdx and @storybook/mdx1-csf usage

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#25433]
The work done in #25182 removed support for *.stories.mdx and the CSF in MDX format, which is impactful for a few users:

- *.stories.mdx stories should be migrated to new *.mdx format (there is a codemod already [here](https://storybook.js.org/docs/migration-guide#storiesmdx-to-mdxcsf))
- usage of the legacyMdx1 feature in main.js should be removed
```js
export default {
  features: {
    legacyMdx1: true,
  },
};
```
- @storybook/mdx1-csf should be uninstalled
- jsxOptions (addon option from addon-docs) should be removed (though I'm not sure if there's more to it)
- link https://storybook.js.org/docs/7.6/migration-guide

**Comment by ndelangen** [comment]
@yannbf @valentinpalkovic @shilman any idea on how to actually implement this:

> jsxOptions (addon option from addon-docs) should be removed (though I'm not sure if there's more to it)

**Comment by yannbf** [comment]
@ndelangen I unfortunately do not have a lot of context on usage of the jsxOptions. All I know that it was part of mdx1 and that won't exist anymore because we removed it.
