### ISSUE TITLE
[Bug]: @storybook/jest crashes on expect() after window resizes to/from mobile view

### ISSUE THREAD

**Issue by kartonrad** [storybookjs/storybook#25434]
### Describe the bug

When resizing our window into mobile view, we noticed that our storybook was crashing.

If we reload the window while in mobile size, the mobile view will render correctly. 
however, once we make the window bigger again, the crash happens too.

This only seemed to happen in stories, that had tests, upon hitting an expect() from jest.

The storybook crashes with this error log: (produced by mozilla firefox)
[console-export-2024-1-3_15-19-20.txt](https://github.com/storybookjs/storybook/files/13820021/console-export-2024-1-3_15-19-20.txt)

### To Reproduce

Create a repo with following commands:

```shell
npx create-react-app reproduction
cd reproduction
npx storybook@latest init
npm install @storybook/testing-library @storybook/jest @storybook/addon-interactions --save-dev
# modify code to add test, that executes an: `expect(4).toEqual(4);`
npm run storybook
```

https://github.com/kartonrad/storybook-repro

The important snippet is this code in Button.stories.js:
```js
import { expect } from '@storybook/jest';
import { Button } from './Button';

// ... in the default story
  play: function () {
    expect(4).toEqual(4);
  }
```

Open storybook in the browser, and resize the window below 600px until the siedebar disappears.
Storybook will then crash.

### System

```bash
Storybook Environment Info:
(node:5800) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

  System:
    OS: Windows 10 10.0.19045
    CPU: (24) x64 12th Gen Intel(R) Core(TM) i9-12950HX
  Binaries:
    Node: 21.1.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.6.1 - C:\Program Files\nodejs\yarn.CMD
    npm: 10.2.0 - C:\Program Files\nodejs\npm.CMD <----- active
    pnpm: 8.7.6 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Spartan (44.19041.3636.0), Chromium (120.0.2210.91)
  npmPackages:
    @storybook/addon-essentials: ^7.6.7 => 7.6.7
    @storybook/addon-interactions: ^7.6.7 => 7.6.7
    @storybook/addon-links: ^7.6.7 => 7.6.7
    @storybook/addon-onboarding: ^1.0.10 => 1.0.10
    @storybook/blocks: ^7.6.7 => 7.6.7
    @storybook/jest: ^0.2.3 => 0.2.3
    @storybook/preset-create-react-app: ^7.6.7 => 7.6.7
    @storybook/react: ^7.6.7 => 7.6.7
    @storybook/react-webpack5: ^7.6.7 => 7.6.7
    @storybook/test: ^7.6.7 => 7.6.7
    @storybook/testing-library: ^0.2.2 => 0.2.2
    eslint-plugin-storybook: ^0.6.15 => 0.6.15
    storybook: ^7.6.7 => 7.6.7
```

**Comment by shilman** [comment]
Please try upgrading to the latest prerelease:

```
npx storybook@next upgrade --prerelease
```

In 8.0, we no longer trigger a page refresh when you resize the window. I suspect the underlying bug remains, but at least you shouldn't encounter it under normal usage.

@yannbf @kasperpeulen any idea why this is failing?

**Comment by kartonrad** [comment]
Sure, i think that's reasonable
We were only investigating this because of a possible bug in our own components - if this just bug didn't occour, then noone would fall into that trap.

Given that this crash doesn't really impact our component library, we probably won't be upgrading until we have a stable release.
I will be upgrading the reproduction-repo though, and test it!

**Comment by kartonrad** [comment]
Still, the bug is quite bizzare, since the `expect(4).toEqual(4)`  doesn't even directly depend on the layout - at least not visibly.
however, you are definetly the best person to gauge whether this is concerning or just a rough edge that doesn't effect much else 😌

**Comment by shilman** [comment]
I am a bit concerned--such a weird behavior! Let's see what the experts say @yannbf @kasperpeulen

**Comment by kartonrad** [comment]
This issue doesn't persist in Storybook 8.1.0

**Comment by kartonrad** [comment]
Still, thank you for looking into this and for your work on storybook!
The new Mobile View also looks really great (and doesn't crash) so congrats!
