### ISSUE TITLE
[Bug]: How to use SVG file in Storybook?

### ISSUE THREAD

**Issue by flexcommits** [storybookjs/storybook#25448]
### Describe the bug

I have error like "ERROR in ./src/components/organisms/scheduleReception/search/ReceptionBeforeSearch.tsx 10:0-75
Module not found: Error: Can't resolve 'public/icons/icon_reception_before.svg' in 'D:\Kristoff\synnify-sinka\facility\synnify\src\components\org
anisms\scheduleReception\search'"

**Comment by vanessayuenn** [comment]
Hi, thanks for reporting this. do you have a reproduction repo you can share? If not, can you create one (see [how to create a repro](https://storybook.js.org/docs/react/contribute/how-to-reproduce)). We prioritize bug reports that have reproduction. Thank you! 🙏

**Comment by valentinpalkovic** [comment]
@flexcommits Do you have a space somewhere in your project path? Could you try to remove it and let us know whether it works?
