### ISSUE TITLE
[Bug]:  decodeEntities option is required in browser builds

### ISSUE THREAD

**Issue by p3k** [storybookjs/storybook#25523]
### Describe the bug

While stories render fine, the following error is thrown in the dev console:

```plain
error Error: [@vue/compiler-core] decodeEntities option is required in browser builds.
    at baseParse (compiler-core.esm-bundler.js:2586:1)
    at getComponents (entry-preview-docs.mjs:8:1)
    at getTemplateComponents (entry-preview-docs.mjs:8:1)
    at generateSource (entry-preview-docs.mjs:8:1)
    at immediate (entry-preview-docs.mjs:8:1)
    at callWithErrorHandling (runtime-core.esm-bundler.js:158:1)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:166:1)
    at job (runtime-core.esm-bundler.js:1827:1)
    at doWatch (runtime-core.esm-bundler.js:1858:1)
    at watch (runtime-core.esm-bundler.js:1716:1)#
```

### To Reproduce

not sure I can provide this… :grimacing: 

### System

```bash
Storybook Environment Info:

  System:
    OS: Linux 6.2 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 18.19.0 - /tmp/xfs-38cf59af/node
    Yarn: 4.0.2 - /tmp/xfs-38cf59af/yarn <----- active
    npm: 10.2.3 - /usr/local/bin/npm
  npmPackages:
    @storybook/addon-actions: 7.6.7 => 7.6.7 
    @storybook/addon-essentials: 7.6.7 => 7.6.7 
    @storybook/addon-links: 7.6.7 => 7.6.7 
    @storybook/vue3: 7.6.7 => 7.6.7 
    @storybook/vue3-webpack5: 7.6.7 => 7.6.7 
    eslint-plugin-storybook: 0.6.15 => 0.6.15 
    storybook: 7.6.7 => 7.6.7
```

### Additional context

Might be related to / duplicate of #25496.

Searching for `decodeEntities` in the Storybook documentation yields no results:

![storybook js org_](https://github.com/storybookjs/storybook/assets/16631/d3222b50-e774-49a5-aef8-411c73357d8c)

**Comment by glancel** [comment]
I'm having the same problem after update vue to the latest version, 3.4.

**Comment by chakAs3** [comment]
Please @p3k  if you can't reproduce the bug,  a PR may introduce another bug that you don't see. so please create a reproduction repo, i will help you fix your issue inshallah.

**Comment by susnux** [comment]
That error comes from the Vue sfc-compiler, so something wrong with the vue integration of storybook.

I also get this error, but for me the source code of stories is also broken, so this might be related?

**Comment by Hai-San** [comment]
Same here.

The Source code does not appear here either.

I have the same version in vue2 and it works normally.

**Comment by Michael2109** [comment]
@chakAs3 Do you know which version of Vue `decodeEntities` became required? I'm wondering if a temporary workaround is to downgrade although that could likely lead to other issues.

**Comment by chakAs3** [comment]
decodeEntities only used for DOM compilers that runs in the browser.
 In non-browser builds, this option is ignored.
i think it is not about Vue if the browser requires that it will throw

**Comment by JakeHarder** [comment]
I also see this error. I have a few stories, but I only see this error for a component that uses Vue's Date Picker.
My package.json has:
`"vuejs3-datepicker": "^1.1.2"`
My exact error is:
```
error Error: [@vue/compiler-core] decodeEntities option is required in browser builds.
    at baseParse (compiler-core.esm-bundler.js:2591:13)
    at getComponents (entry-preview-docs.mjs:8:404)
    at getTemplateComponents (entry-preview-docs.mjs:8:264)
    at generateSource (entry-preview-docs.mjs:8:2799)
    at watch.immediate (entry-preview-docs.mjs:8:2608)
    at callWithErrorHandling (runtime-core.esm-bundler.js:193:18)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:201:17)
    at job (runtime-core.esm-bundler.js:1943:9)
    at doWatch (runtime-core.esm-bundler.js:1981:7)
    at watch (runtime-core.esm-bundler.js:1808:10)
```

**Comment by JBustin** [comment]
Hello, a similar issue with Storybook 9
```
    "@storybook/addon-a11y": "9.1.15",
    "@storybook/addon-docs": "9.1.15",
    "@storybook/addon-links": "9.1.15",
    "@storybook/addon-vitest": "9.1.16",
    "@storybook/builder-vite": "9.1.15",
    "@storybook/vue3-vite": "9.1.15",
```

```
[@vue/compiler-core] decodeEntities option is passed but will be ignored in non-browser builds.
```

**Comment by bodograumann** [comment]
I'm seeing this error as well when running tests with addon-vitest under latest storybook 10.0.5. @JBustin 
Is storybook actually using the browser build of the vue-compiler anywhere, @chakAs3  ?

Btw. this is with vue-3.5.24

**Comment by chakAs3** [comment]
Hi @bodograumann can you help with repro repo ? 
Yes, we use the vue-compiler to parse the template string in the CSF story definition so we can dynamically generate the source code snippet displayed in the Docs panel.

**Comment by jannaahs** [comment]
> Yes, we use the vue-compiler to parse the template string in the CSF story definition so we can dynamically generate the source code snippet displayed in the Docs panel.

@chakAs3 I was able to reproduce the issue. Only when a template string is defined the message appears.

Repro repo: https://github.com/jannaahs/reprod-decodeEntities-option

**Comment by messenjer** [comment]
I have the same issue (with vue and addon-vitest). May be we can create a new issue for this ?

**Comment by aethr** [comment]
I'm experiencing this in my project which uses vitest (4.1.10) + storybook for component browser testing. I believe the root cause in my case is: https://github.com/vitest-dev/vitest/issues/11177.
