### ISSUE TITLE
[Bug]: Vue3-vite storybook app.component not working

### ISSUE THREAD

**Issue by RobineSavert** [storybookjs/storybook#25586]
### Describe the bug

In my previous Storybook install (in a Vue3 + Vite project) I had my preview.js file configured like this:

```
import {app} from '@storybook-vue';
import BootstrapIcon from '@dvuckovic/vue3-bootstrap-icons';
app.component('BootstrapIcon', BootstrapIcon);

export const parameters = {
  actions: { argTypesRegex: '^on[A-Z].*' },
  controls: {
    expanded: true,
    hideNoControlsWarning: true,
    matchers: {
      color: /(background|color)$/i,
      date: /Date$/,
    },
  },
};

```

After updating to the lastest version, this breaks and now I can't show my Bootstrap Icons anymore. 
I see that "app" is not an exported function in the new version, but how can I fix this issue?

The error on the frontend:

_The requested module '/node_modules/.cache/sb-vite/deps/@storybook_vue3.js?v=089190db' does not provide an export named 'app'_

Using packages:
    "@storybook/vue3": "^7.6.7",
    "@storybook/vue3-vite": "^7.6.7",
    
    

### To Reproduce

Fresh install of Storybook latest on a Vite-Vue project with packages:

    "vite": "^3.0.9",
    "vue": "^3.2.37",

Install     "@dvuckovic/vue3-bootstrap-icons": "^1.0.6",

And try to install them in the preview.js file

### System

```bash
Storybook Environment Info:

  System:
    OS: Windows 11 10.0.22621
    CPU: (12) x64 Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz
  Binaries:
    Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD <----- active
  Browsers:
    Edge: Chromium (120.0.2210.91)
  npmPackages:
    @storybook/addon-essentials: ^7.6.7 => 7.6.7
    @storybook/addon-interactions: ^7.6.7 => 7.6.7
    @storybook/addon-links: ^7.6.7 => 7.6.7
    @storybook/blocks: ^7.6.7 => 7.6.7
    @storybook/test: ^7.6.7 => 7.6.7
    @storybook/vue3: ^7.6.7 => 7.6.7
    @storybook/vue3-vite: ^7.6.7 => 7.6.7
    storybook: ^7.6.7 => 7.6.7
    storybook-vue: ^3.2.16 => 3.2.16
```

**Comment by shilman** [comment]
I think you're looking for this: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#vue3-replaced-app-export-with-setup

**Comment by RobineSavert** [comment]
Thanks I solved it by importing the BootstrapIcons in each storybook vue file but globally would be better.

**Comment by heyakyra** [comment]
For others getting here via web search, I hit this due to using deprecated `vite-ulpgin-vue2`  and fixed it by upgrading to the official `@vitejs/plugin-vue2` (which only supports vue 2.7x). 

before

```
import { defineConfig } from "vite";

import { createVuePlugin } from "vite-plugin-vue2";

export default defineConfig({
  plugins: [createVuePlugin()],
});
```

after

```
import { defineConfig } from "vite";
import vue from "@vitejs/plugin-vue2";

export default defineConfig({
  plugins: [vue()],
});

```

_P.S. Also, annoyingly, Firefox only gave a `import not found: default` error and only chrome gave a more helpful error similar to the one in the original post here._
