### ISSUE TITLE
[Documentation]: Change "experimentalNextRSC" to "experimentalRSC" in Storybook for React Server Components Blog Article

### ISSUE THREAD

**Issue by davevanhoorn** [storybookjs/storybook#25679]
### Describe the problem

In the `Storybook for React Server Components` found [here]( https://storybook.js.org/blog/storybook-react-server-components/), both `experimentalNextRSC` and `experimentalRSC` are mentioned as configurable features. Shouldn't this only be `experimentalRSC`?

Quoted from the article:

```
Starting in Storybook 8, @storybook/nextjs can wrap your stories in Suspense using the experimentalNextRSC feature flag in .storybook/main.js:

// .storybook/main.js
export default {
  features: {
    experimentalRSC: true,
  }
};
```

The first line says `Using the experimentalNextRSC feature flag`, yet in the code example `experimentalRSC` is used. This is confusing.

In my project (`8.0.0-alpha.12`), only `experimentalRSC` works.

**Comment by shilman** [comment]
@davevanhoorn Thanks for filing this! Indeed, `experimentalRSC` is correct. We updated it in most spots but missed a few. @joevaugh4n when you fix blog post can you please close this issue?

**Comment by joevaugh4n** [comment]
Fixed! Thanks for spotting this, @davevanhoorn!
