### ISSUE TITLE
[Bug]: importing inject from vue

### ISSUE THREAD

**Issue by ananishimoto** [storybookjs/storybook#25671]
### Describe the bug

I'm trying to import `inject` from `vue` but storybook seems to break the as it doesn't recognize it correctly and returns `undefined`. On my application itself, it works fine, and I can log the created emitter.

Where I have the error:
<img width="290" alt="image" src="https://github.com/storybookjs/storybook/assets/8687154/e333e705-7bbe-4284-85f1-d1690ea7cb68">

<img width="444" alt="image" src="https://github.com/storybookjs/storybook/assets/8687154/28b3d5a3-2237-46a1-ae2f-47ab3531bef3">

Storybook error:
`[Vue warn]: injection "emitter" not found.`

If I get ride of the `import { inject } from 'vue'` it works fine, but then I don't have the needed functionality.

These are the version I have for now:

```
"vue": "^3.4.14",
"storybook": "^8.0.0-alpha.11",
"@storybook/addon-designs": "^8.0.0-alpha.11",
"@storybook/addon-essentials": "^8.0.0-alpha.11",
"@storybook/addon-interactions": "^8.0.0-alpha.11",
"@storybook/addon-links": "^8.0.0-alpha.11",
"@storybook/blocks": "^8.0.0-alpha.11",
"@storybook/testing-library": "^0.2.2",
"@storybook/vue3": "^8.0.0-alpha.11",
"@storybook/vue3-vite": "^8.0.0-alpha.11",
```

I tried to find any issues related to that, but couldn't find them! Any help is much appreciated!!

### System

```bash
System:
    OS: macOS 14.2.1
    CPU: (8) x64 Apple M2
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.0 - ~/.volta/tools/image/node/18.18.0/bin/node
    Yarn: 4.0.0-rc.53 - ~/.volta/tools/image/yarn/4.0.0-rc.53/bin/yarn
    npm: 10.2.1 - ~/.volta/tools/image/npm/10.2.1/bin/npm <----- active
  Browsers:
    Chrome: 120.0.6099.234
    Safari: 17.2.1
```

**Comment by extrem7** [comment]
Have you added a decorator with provide function?

**Comment by ananishimoto** [comment]
An update in case someone else is with the same issue: I create mock functions to replace the ones that uses the inject from vue (this indeed seems to be the issue that breaks on storybook). After creating the mock functions, I started to pass it as a prop to all my components, and overwrote the real functionality withing the `args` on my storybook files.

<img width="328" alt="image" src="https://github.com/storybookjs/storybook/assets/8687154/64d4c2a6-4950-4984-b329-29bcdf423b95">
