### ISSUE TITLE
[Bug]: Unclear instructions for migrating manager configuration

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#25718]
### Describe the bug

When creating custom themes or configuring Storybook's UI, in Storybook 7 users would have the dependency `@storybook/addons` and something like this in their manager.js/ts file:

```ts
.storybook/manager.ts
import { addons } from '@storybook/addons'
import { create } from '@storybook/theming/create'

const theme = create({
  base: 'light',
  // ...the properties
})

addons.setConfig({
  theme,
  showPanel: true, // show addons panel by default
  panelPosition: 'right', // position addons panel on the right by default
})
```

In Storybook 7, `@storybook/addons` was split into `@storybook/manager-api` and `@storybook/preview-api` but [the migration notes](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#removed-deprecated-shim-packages) don't really seem clear about what to do in the scenario just described.

When a user upgrades Storybook, they reach the following error:
<img width="550" alt="image" src="https://github.com/storybookjs/storybook/assets/1671563/ed2dcfa1-0315-4b14-bd29-72cbfd630366">

I'd say we should improve the migration notes, but optimally provide an automigration for this.

**Comment by Jkker** [comment]
Bump. As of 8.0.0-alpha.13, the `addPanel` API used in the migration docs is not available in "@storybook/manager-api"

**Comment by vanessayuenn** [comment]
@Jkker can you link where `addons.addPanel()` is used? It has been deprecated since 7.x in favour of `addons.add()` and we should update the docs if it's still there.

**Comment by kylegach** [comment]
Fwiw, `addPanel` does not appear anywhere in the 7.6 or 8.0 docs.

**Comment by kylegach** [comment]
I added a note to `MIGRATION.md` here: https://github.com/storybookjs/storybook/pull/26039
