### ISSUE TITLE
[Bug]: `@storybook/preview@7.6.0` contains breaking change

### ISSUE THREAD

**Issue by thepassle** [storybookjs/storybook#25735]
### Describe the bug

`@storybook/preview@7.5.3` has an export for `globals`:
<img width="854" alt="image" src="https://github.com/storybookjs/storybook/assets/17054057/e626be6d-b108-4c7a-a802-84537965970c">

We import it here: https://github.com/modernweb-dev/web/blob/master/packages/storybook-builder/src/index.ts#L4C1-L5C1

```js
import { globals } from '@storybook/preview/globals';
```

However, in version `7.6.0` it seems that the export has changed to something different, resulting in a breaking change for our storybook builder (`@web/storybook-builder`):

<img width="859" alt="image" src="https://github.com/storybookjs/storybook/assets/17054057/82427b7e-dead-4f8c-8efe-54e782068ce0">

**Comment by JReinhold** [comment]
Sounds about right. AFAIK there was never an intention for other packages than Storybook core packages to use that export, which is why it wasn't considered a breaking change to change it.

I think we can bring back the original `globals` export with little effort in 7.6 though.

**Comment by thepassle** [comment]
I could be wrong, but I think us using this export was one of the things we discussed a while ago with some members of the storybook team, but I forget the details unfortunately. For now it seems like we can just update to the `globalsNameReferenceMap` because those seem to be the same object, but figured I'd report the issue so at least y'all are aware of it. I'll close this issue for now then :) Do be advised that third party Builders may depend on this package however

**Comment by JReinhold** [comment]
> this export was one of the things we discussed a while ago with some members of the storybook team

Could very well be! A lot of nuances and details here and I won't pretend to know everything and every usage.

> Do be advised that third party Builders may depend on this package however

Thanks!
