### ISSUE TITLE
[Bug]: Storybook 8 - source snippets are not highlighted in mdx docs

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#25737]
### Describe the bug

Something happened between alpha versions of Storybook 8 which introduced a bug where the code snippets are rendered as text instead of an element with code highlights and copy button

Storybook 8.0.0-alpha.3
![image](https://github.com/storybookjs/storybook/assets/1671563/dde9b983-52d5-4803-b4b7-943cd720476c)

Storybook 8.0.0-alpha.4 (or higher)
![image](https://github.com/storybookjs/storybook/assets/1671563/c88a63a0-036f-4f24-82cd-f9a81b8f7ebc)

### To Reproduce

Access the following branch and run Storybook:
https://github.com/yannbf/mealdrop/tree/bug/mdx-source-highlight

**Comment by vanessayuenn** [comment]
hrm, cannot repro this in alpha-14. could it be fixed already?

**Comment by JReinhold** [comment]
This happens whenever the installed React version is not v18.2.0
