### ISSUE TITLE
[Bug]: Resizing of Storybook Panel doesn't always apply

### ISSUE THREAD

**Issue by vanessayuenn** [storybookjs/storybook#25759]
### Describe the bug

**Project**: Bitwarden (Angular)
**Version**: 8.0.0-alpha.13
**Bug/feedback**: Resizing of Storybook Panel doesn't always apply
**Tested Browser**: Edge (but also encountered it in Chrome a while ago)

When the panel is resized fast, the changes aren't always applied:

https://github.com/storybookjs/storybook/assets/5889929/73c3edf4-40bd-41a7-abda-887ffbb2c60f

### To Reproduce

1. Go to https://stackblitz.com/edit/github-t8esdj?file=.storybook%2Fmanager.jsx
2. Open the `Primary` Button Story.
3. Try to resize the Storybook Panel fast

**Comment by brielle5810** [comment]
Hi! Could I try and take this on?

**Comment by vanessayuenn** [comment]
@brielle5810 of course! PR is very welcome! If this is your first contribution, be sure to check the [contribution guide](https://storybook.js.org/docs/react/contribute/how-to-contribute) and hop onto the [Storybook Discord](https://discord.gg/storybook) if you need any help getting started. Looking forward to your contribution! ✨

**Comment by hmcostaa** [comment]
Hi @vanessayuenn, can you assign me this one?
