### ISSUE TITLE
[Bug]: Loading @emotion/react more than once

### ISSUE THREAD

**Issue by vanessayuenn** [storybookjs/storybook#25761]
### Describe the bug

**Project:** MealDrop
**Version:** 8.0.0-alpha.4
**Bug/feedback:**

When loading any MDX (docs only or autodocs) in Storybook 8.0.0-alpha-4 or higher, there is a warning in the console mentioning that emotion is loaded multiple times:

```
You are loading @emotion/react when it is already loaded. Running multiple instances may cause problems. This can happen if multiple versions are used, or if multiple builds of the same version are used.
```

Apart from emotion being instantiated by the Manager UI, there are two moments where it gets instantiated in the Preview UI:

Via `@storybook/components`
<img width="512" alt="image" src="https://github.com/storybookjs/storybook/assets/1671563/dba03fde-4baf-4065-8808-aa5e541da954">

Via `@storybook/addon-docs/node_modules/@storybook/components`
<img width="768" alt="image" src="https://github.com/storybookjs/storybook/assets/1671563/ae724b41-3637-4b63-9a9c-1119505acdf4">

### To Reproduce

1. Go to https://github.com/yannbf/mealdrop/tree/bug/multiple-instances-emotion
2. Run Storybook
3. Check the logs

**Comment by JReinhold** [comment]
I have a fix for this, but I think it's highly related to https://github.com/storybookjs/storybook/issues/25737 so I'm trying to fix both.
