### ISSUE TITLE
[Bug]: mobile view should not hint at keyboard shortcut

### ISSUE THREAD

**Issue by vanessayuenn** [storybookjs/storybook#25816]
### Describe the bug

The search bar in mobile view has the keyboard shortcut indicator `⌘ K`:
![Screenshot 2024-01-25 at 14 38 03](https://github.com/storybookjs/storybook/assets/3070389/270731fc-8504-4414-85ae-52314de42e46)

### To Reproduce

1. Open any storybook build
2. Resize to trigger mobile view
3. Open menu from bottom left button

**Comment by KarthiDevelope** [comment]
Still This issue Open , Can i Fix this issue ?

**Comment by vanessayuenn** [comment]
@KarthiDevelope yes! PR welcome!  Be sure to check the [contribution guide](https://storybook.js.org/docs/react/contribute/how-to-contribute) and hop onto the [Storybook Discord](https://discord.gg/storybook) if you need any help getting started. Looking forward to your contribution! ✨

**Comment by tusharwebd** [comment]
Created pull request for issue: https://github.com/storybookjs/storybook/pull/25866. Please review. Thanks!
