### ISSUE TITLE
[Bug]: It's possible to resize the side bar too much

### ISSUE THREAD

**Issue by vanessayuenn** [storybookjs/storybook#25817]
### Describe the bug

**Project**: Chromatic
**Version**: v8.0.0-alpha.14
**Bug/feedback:** 

It's possible to resize the side bar to a point where the gear icon gets cut off

<img width="296" alt="image" src="https://github.com/storybookjs/storybook/assets/6842965/1ce35d85-26c8-40e7-bce3-bfb45be15c84">

Reported in https://github.com/storybookjs/storybook/discussions/25688?sort=new#discussioncomment-8238125

**Comment by cdedreuille** [comment]
This one has been fixed in 8.0 already @vanessayuenn
