### ISSUE TITLE
[Bug]: Number controls do not reset

### ISSUE THREAD

**Issue by vanessayuenn** [storybookjs/storybook#25819]
### Describe the bug

**Project:** MealDrop
**Version:** 8.0.0-alpha.14
**Bug/feedback:**

Number controls do not reset:

<img src="https://github.com/storybookjs/storybook/assets/1671563/924f1fd0-af6e-47bc-ace9-d86301d564c5" width="300"/>

reported here https://github.com/storybookjs/storybook/discussions/25687?sort=new#discussioncomment-8247892

### To Reproduce

1. Go to https://stackblitz.com/edit/github-cde8qu?file=src%2Fstories%2FButton.jsx,src%2Fstories%2FButton.stories.js&preset=node
2. Visit a Button story
3. Define value for the `age` control
4. Reset it
5. Same issue happens in ArgsTable in autodocs

**Comment by chakAs3** [comment]
I remember fixing this in my one of the close no merged PR 
https://github.com/storybookjs/storybook/blob/69c92f8eacca8c0cc89cef24d1ee5c03249ed018/code/ui/blocks/src/controls/Number.tsx

**Comment by ghidersamihaela** [comment]
Hi, I would like to look into this.Thanks.
