### ISSUE TITLE
[Bug]: it should error when there is no main config file

### ISSUE THREAD

**Issue by vanessayuenn** [storybookjs/storybook#25814]
### Describe the bug

**Project**: SvelteUI
**Version**: 8.0.0-alpha.13
**Bug/feedback**:

The upgrade command didn't warn/error about not being able to find the main configuration file. The configuration is in a non-standard directory which the user must define with the `--config-dir` flag, but there was no prompt for this. This caused all automigrations to be skipped.

see https://github.com/storybookjs/storybook/discussions/25692?sort=new#discussioncomment-8220586

**Comment by ndelangen** [comment]
It does actually warn the user, but I chatted with @shilman about this, and we decided to promote it to an error.

Here's what it does today:
![Screenshot 2024-02-16 at 14 36 15](https://github.com/storybookjs/storybook/assets/3070389/d1abd3bb-1b3d-411c-aa09-2490dd66c06a)

I'll fix this inside of https://github.com/storybookjs/storybook/pull/26035
