### ISSUE TITLE
[Bug]: SB's `polished` dependency requires Node >= 20

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#25849]
### Describe the bug

<img width="830" alt="image" src="https://github.com/storybookjs/storybook/assets/488689/eed4ac7c-54a5-4aa0-b237-1ebc96e4101f">

**Comment by pranavks** [comment]
All of a sudden our builds are failing due to this. Unable to bump to node 20 due to other dependencies.

We have temporarily fixed this by overriding this dependency's version in package.json.

**Comment by gcoffey-tgg** [comment]
Breaking change is here > https://github.com/styled-components/polished/pull/643/commits/e05ad0ef7ae4668bb5bd83251dc9defacc6fcd4e

**Comment by samueleiche** [comment]
What's the temporary fix for this - thanks.

**Comment by samueleiche** [comment]
> how to solve this problem T___T...

in package.json you can do 
`
"resolutions": {
	"polished": "4.2.2"
},
`

**Comment by patrykpieniak** [comment]
Check if version locking for the package "polished" will work
This is for NPM
https://stackoverflow.com/questions/15806152/how-do-i-override-nested-npm-dependency-versions

**Comment by valentinpalkovic** [comment]
The problem seems to be resolved: https://github.com/styled-components/polished/issues/644

The 4.3.0v isn't tagged as `latest` anymore and doesn't even seem to be published any more: https://www.npmjs.com/package/polished?activeTab=versions
