### ISSUE TITLE
[Bug]: Upgrade @testing-library/user-event 

### ISSUE THREAD

**Issue by kasperpeulen** [storybookjs/storybook#25853]
### Describe the bug

There are some type and other bugs in @testing-library/user-event version 14.3.0 that we use.

However, the newer versions have (different) bugs, we think they may be easier to reconcile:
https://github.com/testing-library/user-event/issues/1075

**Comment by jaens** [comment]
Predictably, this completely broke form submissions in interactions on Firefox...

**Comment by IanVS** [comment]
The workaround is to use `fireEvent` instead of `userEvent`: https://github.com/testing-library/user-event/issues/1075#issuecomment-1948093169
