### ISSUE TITLE
[Bug]: Click event of an anchor within ul li not triggering the further events

### ISSUE THREAD

**Issue by Prashant-Kan** [storybookjs/storybook#25857]
### Describe the bug

Kindly consider the below HTML structure
```
<div>
<a id="dropDown">Click Here To Open Dropdown</a>
<ul  id="selectoptions">
<li id="opt1">Option 1</li>
<li  id="opt2">Option 2</li>
<li  id="opt3">Option 3</li>
</ul>
</div>
```
When user click on an anchor with id dropDown. it opens the ul li dropdown. 
but then when user click on li button using below code. 

```
cy.get("#dropDown").click().siblings(`ul#selectoptions").within(() => {
            cy.get("opt2").click();
        });
```        
 Click event didn't trigger. Though it closes the dropdown but expected behaviour is to trigger the server call and do the needful. 
     
It works fine in the previous version of cypress till 12.17.0 while in the current version after v13 its not working
     
     
![image](https://github.com/storybookjs/storybook/assets/17109022/92cd4f5e-cc9a-4696-8746-3414d94defb7)

**Comment by vanessayuenn** [comment]
@Prashant-Kan did you mean to open this issue on storybook repo? if so, can you provide more info (e.g. share the output of `npx storybook@latest info`)

**Comment by Prashant-Kan** [comment]
Dont know about storybook.

Can you guide what to do with that.

We need to fix this as early as possible. As our website is used by many live users

**Comment by vanessayuenn** [comment]
@Prashant-Kan I don't see any indication that your project uses [Storybook](storybook.js.org), so I believe you opened this issue in the wrong repo. If this is a [Cypress](https://github.com/cypress-io/cypress) issue, I would recommend reaching out to their maintainers instead. I am closing this issue.
