### ISSUE TITLE
Portable stories - Define and document a pattern for using preview annotations from addons

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#25876]
When using portable stories in different environments (Vitest, Playwright CT, etc), it's normally required to use `setProjectAnnotations` in a "setup test" file, so that the project annotations are applied in portable stories.

```ts
import { setProjectAnnotations } from '@storybook/react'
import * as projectAnnotations from '../.storybook/preview'
import * as addonAnnotations from 'some-other-addon/preview'

setProjectAnnotations([projectAnnotations, addonAnnotations])
```

However the user might not know exactly what to add there, apart from the preview.ts file. That's because there are addons which might export their own preview annotations (such as decorators) which are automatically registered without the user knowing. Those would be needed (in case such decorators are required for rendering) in order to successfully render a portable story.

We should make sure that:
- [addon-kit](https://github.com/storybookjs/addon-kit/) already provides this format (and document this use case for addon-maintainers to understand it)
- our documentation is clear and provides guidance for users to achieve this in their projects

**Comment by yannbf** [comment]
Closing this as the discussion has happened and the idea is to move further with the existing API.

**Comment by JReinhold** [comment]
Does that mean we don't need to do this anyway?

**Comment by yannbf** [comment]
We just take this in consideration when documenting, which is taken care of in #25928
