### ISSUE TITLE
[Bug]: universal_cookie_1.default is not a constructor

### ISSUE THREAD

**Issue by Revanth12-creator** [storybookjs/storybook#25886]
### Describe the bug

Uncaught TypeError while set cookies and get cookies in React application

### Additional context

import Cookies from 'universal-cookie';
let cookies = new Cookies();
 cookies.set('token', data.token);

**Comment by shilman** [comment]
Do you a have a reproduction repo you can share? If not, can you create one? Go to https://storybook.new or see [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce). Thank you! 🙏

**Comment by bnbc** [comment]
Same problem with v7, 6.1.3 is ok !
