### ISSUE TITLE
[Bug]: window.addEventListener is not a function when running 8.0.0 alpha 0 on react native

### ISSUE THREAD

**Issue by dannyhw** [storybookjs/storybook#25890]
### Describe the bug

preview-api has window.addEventListener which crashes react native when rendering a story.

https://github.com/storybookjs/storybook/blob/next/code/lib/preview-api/src/modules/preview-web/render/StoryRender.ts#L233

```
       window.addEventListener('error', onError);
        window.addEventListener('unhandledrejection', onError);
```

### To Reproduce

Run https://github.com/storybookjs/react-native/pull/538 example app

### System

```bash
Storybook Environment Info:

  System:
    OS: macOS 14.2.1
    CPU: (10) arm64 Apple M1 Max
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.9.0 - ~/Library/pnpm/node
    Yarn: 3.6.1 - ~/Library/pnpm/yarn <----- active
    npm: 9.7.2 - ~/Library/pnpm/npm
    pnpm: 8.9.2 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 121.0.6167.139
    Safari: 17.2.1
```

**Comment by dannyhw** [comment]
@kasperpeulen I noticed that you added this in our pr, maybe we could talk about how to make this safe for react native
https://github.com/storybookjs/storybook/commit/7c71684fbb4f5faed3bd47ecd1fba0be095ab405

**Comment by shilman** [comment]
I wonder if we could add a unit test that runs in the node environment that crashes if any of the Preview code accesses `window` or other browser-specific APIs

**Comment by tmeasday** [comment]
Looking at the PR again, I think those event handlers for unhandled exceptions should be added higher in the stack (like `PreviewWeb` probably) and somehow passed to the `StoryRender` when they happen. Probably similarly to this code: https://github.com/storybookjs/storybook/blob/1807f05b65db161f6420b6c952bc006580572032/code/lib/preview-api/src/modules/preview-web/Preview.tsx#L275

**Comment by kasperpeulen** [comment]
```
       window.addEventListener('error', onError);
        window.addEventListener('unhandledrejection', onError);
```

How would we listen to those events in React Native? @dannyhw

**Comment by dannyhw** [comment]
There isn't any global event in react native. You would try catch or use an error boundary maybe. However we don't fully support the play function yet on rn anyway which I think this is related to.

**Comment by kasperpeulen** [comment]
This is actually about events that are not catched in react error boundaries.
Mostly errors that happen in event callbacks.

Couldn't we do the same that you would do in Node in genreral?

```
process.on('uncaughtException', (err) => {
  
});

process.on('unhandledRejection', (reason, promise) => {

});
```

We could also of course just only do this feature in the browser. But I thought it might be nice to make it react native compatible.

**Comment by dannyhw** [comment]
As far as I know its not possible, process is just available as a shim.

**Comment by shilman** [comment]
I believe this has already been fixed so I'm closing this. Please lmk if that's not the case @dannyhw
