### ISSUE TITLE
[Bug]: Storybook v8.0.0-alpha.16 unknown types

### ISSUE THREAD

**Issue by MariaTeo** [storybookjs/storybook#25909]
This is happening in a nextjs14 project with typescript.

this is part of my package.json
```
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint",
    "test": "jest",
    "test:watch": "jest --watchAll",
    "story": "storybook dev -p 6006",
    "build-storybook": "storybook build"
  },
  "dependencies": {
    "next": "14.0.4",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "styled-components": "^6.1.8"
  },
  "devDependencies": {
    "@storybook/addon-essentials": "^8.0.0-alpha.16",
    "@storybook/addon-interactions": "^8.0.0-alpha.16",
    "@storybook/addon-links": "^8.0.0-alpha.16",
    "@storybook/addon-onboarding": "^1.0.10",
    "@storybook/blocks": "^8.0.0-alpha.16",
    "@storybook/nextjs": "^8.0.0-alpha.16",
    "@storybook/react": "^8.0.0-alpha.16",
    "@storybook/test": "^8.0.0-alpha.16",
    "@testing-library/jest-dom": "^6.2.0",
    "@testing-library/react": "^14.1.2",
    "@types/jest": "^29.5.11",
    "@types/node": "^20",
    "@types/react": "^18.2.51",
    "@types/react-dom": "^18",
    "@types/styled-components": "^5.1.34",
    "@typescript-eslint/eslint-plugin": "^6.20.0",
    "@typescript-eslint/parser": "^6.20.0",
    "eslint": "^8.56.0",
    "eslint-config-next": "14.0.4",
    "eslint-config-prettier": "^9.1.0",
    "eslint-plugin-prettier": "^5.1.3",
    "eslint-plugin-storybook": "^0.6.15",
    "jest": "^29.7.0",
    "jest-environment-jsdom": "^29.7.0",
    "prettier": "^3.2.4",
    "storybook": "^8.0.0-alpha.16",
    "ts-jest": "^29.1.2",
    "ts-loader": "^9.5.1",
    "ts-node": "^10.9.2",
    "typescript": "^5.3.3"
```

<img width="588" alt="image" src="https://github.com/storybookjs/storybook/assets/78360817/a9b3ba6e-d3f4-479f-8f9d-071ad8156b7f">

My config seems to be fine. Types of props are not being defined in the storybook docs

**Comment by vanessayuenn** [comment]
@MariaTeo thank you for testing Storybook 8-alpha! I am not able to reproduce your issue in a fresh Next.js project. Could you share a reproduction of your issue with [storybook.new](https://storybook.new)? That will help us significantly in the debugging process. Thank you!

**Comment by MariaTeo** [comment]
hello @vanessayuenn thank you for your response. I have reproduced the issue [here](https://stackblitz.com/edit/github-c8rao1?file=tsconfig.json,.storybook%2Fwepack.config.js,.storybook%2Fmain.ts,src%2Fcomponent%2Ftext%2Ftext.type.ts,src%2Fcomponent%2Ftext%2Ftext.tsx,src%2Fcomponent%2Ftext%2Ftext.style.ts,src%2Fcomponent%2Ftext%2Findex.ts,src%2Fcomponent%2Ftext%2Fstories%2Ftext.stories.tsx,.storybook%2Fpreview.ts&preset=node). Hope that helps

**Comment by HerbCaudill** [comment]
I've put up another example of this behavior [here](https://stackblitz.com/edit/github-kbkwda?file=src%2Fstories%2FButton.tsx).

```ts
// variants.ts
export const variants = {
  sizes: {
    small: 'text-sm',
    medium: 'text-base',
    large: 'text-lg',
  },
};
```


```ts
// Button.tsx
type SizeOptions = keyof typeof variants['sizes'];

interface ButtonProps {
  // ...
  /**
   * How large should the button be?
   */
  size?: SizeOptions;
```

In the description for `size`, it says 

> How large should the button be? `unknown`

![image](https://github.com/storybookjs/storybook/assets/2136620/289b6366-75f8-4038-b8e0-f85b0f59626d)

Storybook 7 handles this correctly: 

> How large should the button be? `small` `medium` `large`

I've experimented and I only get the `unknown` if the type of the prop has to use the bracket syntax (`keyof typeof variants['sizes']`. If I can write `keyof typeof sizes`, then I get `union`.

```ts
const sizes = {
  small: 'text-sm',
  medium: 'text-base',
  large: 'text-lg',
};

export const variants = { sizes };

type SizeOptions = keyof typeof sizes;
``` 

> How large should the button be? `union`

This is also what you get if you put a union type directly in the prop:

```ts
interface ButtonProps {
  //...
  intent?: 'secondary' | 'primary';
}
```
> How large should the button be? `union`

Again, Storybook 7 handles both of these cases correctly, listing the actual options instead of returning `union`.

**Comment by shilman** [comment]
@HerbCaudill I've verified that setting `typescript.reactDocgen` to `react-docgen-typescript` restores the old behavior: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#react-docgen-component-analysis-by-default

**Comment by ndelangen** [comment]
@MariaTeo I think the PR attached closes your issue.
Thank you for supplying the reproduction, it was very useful in reproducing.

Considering you're overriding argTypes manually, you might find that you'll sometimes need to manually specify the `type` property too:
```
...
  argTypes: {
    as: {
      type: 'string',
      description:
        'Represents what kind of header should the text be, by default it is rendered as a paragraph',
      control: 'select',
      options: ['p', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6'],
      defaultValue: 'p',
      property: 'string',
    },
...
```

And you can supply something more complex using `table`:
(This code already works without the patch)

![Screenshot 2024-03-04 at 09 05 30](https://github.com/storybookjs/storybook/assets/3070389/b53eac54-4708-4e75-9ded-7e6c8deaae43)
![Screenshot 2024-03-04 at 09 05 42](https://github.com/storybookjs/storybook/assets/3070389/8f420a3b-980d-4319-bc59-c685e61d3956)
