### ISSUE TITLE
[Bug]: Warning about addons being in the wrong order is confused by getAbsolutePath() added by the codemod during the migration from 7 to 8

### ISSUE THREAD

**Issue by thobas-dnvgl** [storybookjs/storybook#25969]
### Describe the bug

I upgraded our project from the latest version 7.x to 8 beta 1. One of the codemod from the migration tool detected that our project is a monorepo and changed our config file to add a `getAbsolutePath()` function and use it to wrap the list of addons in the config. This is our config after the migration:
```ts
import type { StorybookConfig } from '@storybook/react-vite'
import { resolve } from 'node:path'
import { dirname, join } from 'path'
import { mergeConfig } from 'vite'

const config: StorybookConfig = {
  stories: ['../stories/**/*.mdx', '../stories/**/*.stories.@(ts|tsx)'],
  staticDirs: ['../public'],
  core: {
    disableTelemetry: true,
  },
  addons: [
    getAbsolutePath('@storybook/addon-links'),
    getAbsolutePath('@storybook/addon-essentials'),
    getAbsolutePath('@storybook/addon-interactions'),
    getAbsolutePath('@storybook/addon-a11y'),
  ],
  framework: {
    name: getAbsolutePath('@storybook/react-vite'),
    options: {},
  },
  docs: {
    autodocs: true,
  },
  async viteFinal(config) {
    return mergeConfig(config, {
      resolve: {
        alias: [
          {
            find: 'stories',
            replacement: resolve(__dirname, '../stories'),
          },
        ],
      },
    })
  },
}

export default config

function getAbsolutePath(value: string): any {
  return dirname(require.resolve(join(value, 'package.json')))
}
```

When building Storybook, we now see this warning:
> WARN Expected '@storybook/addon-actions' (or '@storybook/addon-essentials') to be listed before '@storybook/addon-interactions' in main Storybook config.

Except that `@storybook/addon-essentials` **is listed before** `@storybook/addon-interactions`.

### To Reproduce

Use the same config as above with Storybook 8 beta 1.

### System

```bash
Storybook Environment Info:

  System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz
  Binaries:
    Node: 20.8.1 - C:\Program Files\nodejs\node.EXE
    npm: 10.4.0 - C:\Program Files\nodejs\npm.CMD <----- active
  Browsers:
    Chrome: 121.0.6167.160
    Edge: Chromium (121.0.2277.83)
```

**Comment by vanessayuenn** [comment]
@kasperpeulen does the order of addons still matter now that we do explicit actions mocking?

**Comment by kasperpeulen** [comment]
Yeah I think it matters.

**Comment by kasperpeulen** [comment]
I think this might be a windows only issue. I can not reproduce it on Mac. cc @shilman @vanessayuenn 

@valentinpalkovic Maybe we can pair on this one.
