### ISSUE TITLE
[Bug]: SB8 layout issue with sidebar filter count

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#25971]
### Describe the bug

When using the VTA addon and getting changes reported, I noticed that the `.sidebar-bottom-wrapper` element is taking 100% width and the `#changes-found-filter` button inside only takes the width it needs. As a result, the background differs as can be seen at the bottom of this image in the "5 changes" button:

<img src="https://github.com/storybookjs/storybook/assets/1671563/2a6b95b7-2334-404e-b695-599337c7c54c" width="300"/>

It looks a little weird because the button has rounded corners, which touch the vertical limits
<img width="282" alt="image" src="https://github.com/storybookjs/storybook/assets/1671563/09cea1c6-189d-4c11-bd69-55d1590bd3cc">

When the button is not selected, the background is matched correctly:
<img width="298" alt="image" src="https://github.com/storybookjs/storybook/assets/1671563/cd66ba81-b23f-421d-ad1f-bd1ab3b3339a">

I don't know whether the button should have taken the entire width (and be aligned to the left), or this is an intended behavior.

**Comment by syedbarimanjan** [comment]
I would like to work on this @yannbf

**Comment by yannbf** [comment]
Turns out this is a Visual Tests Addon related issue, not Storybook! It's worked on here https://github.com/chromaui/addon-visual-tests/pull/308 so I'll be closing this issue.
