### ISSUE TITLE
[Bug]: Upgrade from Storybook 6 to Storybook 8 fails if storybook or @storybook/cli isn't installed

### ISSUE THREAD

**Issue by valentinpalkovic** [storybookjs/storybook#25975]
### Describe the bug

The `upgrade` command cannot determine the user's Storybook version if `storybook` or `@storybook/cli` aren't listed in the user's package.json. Additionally, the `automigrate` command isn't doing anything in this case because the actual Storybook version cannot be detected.

### To Reproduce

1. Checkout https://github.com/washingtonpost/wpds-ui-kit
2. Run `npx storybook@next upgrade`
3. The `banner` shows previous version `0.0.0`

Alternatively:

1. Checkout https://github.com/washingtonpost/wpds-ui-kit
2. Run `npx storybook@next automigrate`
3. The automigration says it is unable to determine the Storybook version so the automigrations will be skipped.

**Comment by llins-wavefin** [comment]
I'm having this issue when trying to upgrade to storybook v7 too

**Comment by kyle-mcknight** [comment]
Same for me as well going from 6 to 7.
