### ISSUE TITLE
[Bug]:   No matching version found for @storybook/types@7.6.14.

### ISSUE THREAD

**Issue by MaazDev** [storybookjs/storybook#25985]
### Describe the bug

when installing storybook in a new sveltekit project I get the error No matching version found for @storybook/types@7.6.14. I checked storybook types on NPM and indeed the latest verison is 7.6.13.

### To Reproduce

run npx storybook@latest init in a sveltekit project with typescript

**Comment by shilman** [comment]
Sometimes the new packages take time to propagate in the npm registry. As far as I know this is a service issue in the npm registry.

Try waiting a few hours, clearing your npm cache, and re-running. New packages usually propagate within a few minutes, but I've seen it take up to 24h to propagate.

If you're in a rush. Manually decrement the version and reinstall.
