### ISSUE TITLE
[Bug]: SB8 Sidebar scrolls to selected story location when I try to scroll away

### ISSUE THREAD

**Issue by domyen** [storybookjs/storybook#26022]
### Describe the bug

When I try to scroll away, the sidebar automatically scrolls to the selected story.

From @JReinhold:
> I see, this happens in published Storybooks as well, it's also easily triggered by just selecting another addon tab.

![2024-02-12 15 58 12-1](https://github.com/storybookjs/storybook/assets/263385/18ab4379-f719-4609-aa9d-7e7b43327705)

![2024-01-25 15 06 28](https://github.com/storybookjs/storybook/assets/263385/2270910d-17a6-4b5e-b03d-57aef27d85bd)

### To Reproduce

What are the steps for reproducing the issue? 

1. In your local storybook
2. Select a story toward the end of the sidebar list
3. Try to scroll up on the sidebar, then change the addon panel position
4. Watch the sidebar scroll back to position even when the user tries to scroll away

Note: This appears on [published Storybooks](https://6480e1b0042842f149cfd74c-lsmavabuym.chromatic.com/?path=/story/components-snapshotimage--taller-constrained)

**Comment by syedbarimanjan** [comment]
@domyen I would like to solve this.

**Comment by vanessayuenn** [comment]
@syedbarimanjan Thank you for your interest in helping out! Be sure to check the [contribution guide](https://storybook.js.org/docs/react/contribute/how-to-contribute) and hop onto the [Storybook Discord](https://discord.gg/storybook) if you need any help getting started. Looking forward to your PR! ✨
