### ISSUE TITLE
[Bug]:  Unexpected token, expected "," when trying to import .graphql files

### ISSUE THREAD

**Issue by shapeshifta78** [storybookjs/storybook#26028]
### Describe the bug

I am trying to update from ^7.0.12 to ^7.6.14 and started to get `Unexpected token, expected ","` when trying to import .graphql files caused by the babel-parser and could be related to react-docgen.

Besides switching between several vite/rollup graphl-plugins I tried to add `plugins: ['babel-plugin-import-graphql', 'babel-plugin-react-docgen'],`to my babel config. 

The error persists and I am unable to update. Is there anything else I can do to fix it?

### To Reproduce

Import .graphql files in your stories and try to run/build storybook.

### System

```bash
System:
    OS: macOS 13.6.3
    CPU: (10) arm64 Apple M2 Pro
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - /usr/local/bin/node
    Yarn: 1.22.21 - /usr/local/bin/yarn
    npm: 9.5.1 - /usr/local/bin/npm <----- active
  Browsers:
    Chrome: 121.0.6167.160
    Safari: 17.2.1
  npmPackages:
    @storybook/addon-docs: ^7.6.14 => 7.6.15 
    @storybook/addon-essentials: ^7.6.14 => 7.6.15 
    @storybook/addon-links: ^7.6.14 => 7.6.15 
    @storybook/addons: ^7.6.14 => 7.6.15 
    @storybook/builder-vite: ^7.6.15 => 7.6.15 
    @storybook/node-logger: ^7.6.14 => 7.6.15 
    @storybook/react-vite: ^7.6.14 => 7.6.15 
    @storybook/testing-react: ^2.0.1 => 2.0.1 
    @storybook/theming: ^7.6.14 => 7.6.15 
    msw-storybook-addon: ^1.10.0 => 1.10.0 
    storybook: ^7.6.14 => 7.6.15
```

**Comment by vanessayuenn** [comment]
Hi, thanks for reporting this. do you have a reproduction repo you can share? If not, can you please create one via [storybook.new](https://new-storybook.netlify.app/)? We prioritize bug reports that have reproduction. Thank you! 🙏

**Comment by sbeben** [comment]
storybook has by far the most complicated and pain-in-the-ass start up procedure, even with all of their cli stuff and automatic configs
