### ISSUE TITLE
[Bug]: cannot close notification by clicking on `x`

### ISSUE THREAD

**Issue by vanessayuenn** [storybookjs/storybook#26036]
### Describe the bug

Thie report came from QA-ing VTA, but I believe this might be an issue with all notifications.

Project: Fresh, via SB Init
Version: SB ^8.0.0-beta.0, VTA 1.1.0
Bug/feedback: Currently, you cannot close notifications by clicking on the "X" icon.

To Reproduce,
1. Run a build.
2. Click the the Close Icon.

<img width="301" alt="image" src="https://github.com/storybookjs/storybook/assets/68470411/65765e19-f9c9-4a6f-9b89-b7cd8a6155f4">

**Comment by cdedreuille** [comment]
@vanessayuenn I can see you removed me from this issue. What's the status? Is it still happening?

**Comment by vanessayuenn** [comment]
@cdedreuille I believe this is no longer reproducible so I will just close it
