### ISSUE TITLE
Init: Add *storybook.log entry to .gitignore as part of sb init

### ISSUE THREAD

**Issue by valentinpalkovic** [storybookjs/storybook#26095]
`storybook init` doesn't add an entry to `.gitignore`, and files such as:

```
build-storybook.log
automigrate-storybook.log
doctor-storybook.log
```

are versioned by default.

Let's add `*storybook.log` to the user's gitignore during init.

## Requirements

- If a `.gitignore` file can be found:
  - If `.gitignore` doesn’t have the entry `*storybook.log`
    - `add it`
  - Else, do nothing
- Else, do nothing

**Comment by tobiasdiez** [comment]
Would it make sense to also git-ignore the build directory `storybook-static`?

**Comment by aniketicloud** [comment]
> Would it make sense to also git-ignore the build directory `storybook-static`?

I was thinking the same
