### ISSUE TITLE
[Bug]: Storybook 8: Found 'rollup-plugin-turbosnap' which is now included by default in Storybook 8.

### ISSUE THREAD

**Issue by dartess** [storybookjs/storybook#26108]
### Describe the bug

I got 
```
WARN Found 'rollup-plugin-turbosnap' which is now included by default in Storybook 8.
WARN Removing from your plugins list. Ensure you pass `--webpack-stats-json` to generate stats.
WARN 
WARN For more information, see https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#turbosnap-vite-plugin-is-no-longer-needed
```
when I try to build.

But I don't have `rollup-plugin-turbosnap` or `vite-plugin-turbosnap` at all.

Sounds like it is false-positive warning, is it?

### To Reproduce

Repl: https://github.com/dartess/sb8-repl-react-docgen-plugin-bug

run `npm run build`

### Additional context

SB 8.0.0-beta.3

**Comment by tmeasday** [comment]
Thanks for reporting. This was fixed by https://github.com/storybookjs/storybook/pull/26051 which is in `beta.4`, please try upgrading and let us know if not :)
