### ISSUE TITLE
[Bug]: The codemod mdx-to-csf should be an automigration, since Storybook 8 doesn't support stories.mdx files

### ISSUE THREAD

**Issue by valentinpalkovic** [storybookjs/storybook#26131]
In Storybook 8.0, we have removed `.stories.mdx` support. Therefore, the automigration `mdx-to-csf` should be enforced during upgrade.

## Acceptance criteria

- The `mdx-to-csf` codemod should also run as an automigration
- The user should be notified that the codemod isn't perfect, and the user should recheck the story files after the migration.

**Comment by ndelangen** [comment]
Isn't this what the autoblocker is solving already?

**Comment by ndelangen** [comment]
@valentinpalkovic I'm thinking that maybe I can refactor this existing automigration to also do the work of migrating the user's `stories/.mdx` files.
https://github.com/storybookjs/storybook/blob/edb293d8be2e245d7de5260020a5e0bbc40705ab/code/lib/cli/src/automigrate/fixes/bare-mdx-stories-glob.ts#L1-L124

WDYT?
