### ISSUE TITLE
[Bug]: fix `types` usage for addon

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#26185]
### Describe the bug

Currently all our addons using the same pattern:

```ts
import { addons, types, useArgTypes } from '@storybook/manager-api';

addons.register(ADDON_ID, (api) => {
  addons.add(ADDON_ID, {
    title: Title,
    type: types.PANEL,
    // etc.
```

However, `types` is deprecated. We should fix this before the release, either by un-deprecating `types` or by updating our existing addons & the addon-kit to use the proper types. I suspect that this is improperly deprecated.

**Comment by vanessayuenn** [comment]
un-deprecated `types` in #26202
