### ISSUE TITLE
[Bug]: window is not defined when rendering a React component w/ dedicated worker in development w react-vite

### ISSUE THREAD

**Issue by nrakochy** [storybookjs/storybook#26205]
### Describe the bug

Hi there, 

thanks for the great library. Here's a [summary + fix](https://github.com/vitejs/vite-plugin-react/pull/181) for what is happening in the vite plugin, but it looks like the Storybook version [is still on v3](https://github.com/storybookjs/storybook/blob/6b22f0e01cf979aa66ae26ba77dd5edc21a5947f/code/frameworks/react-vite/package.json#L54C1-L54C38).

### To Reproduce

It's a bit complicated to set-up, hopefully it will Just Work™️  with the latest plugin

### System

```bash
System:
    OS: macOS 14.3.1
    CPU: (10) arm64 Apple M1 Pro
    Shell: 5.9 - /bin/zsh
  Binaries:
    npm: 9.8.0 - ~/.nvm/versions/node/v20.5.1/bin/npm <----- active
  Browsers:
    Chrome: 122.0.6261.69
    Safari: 17.3.1
```
```


### Additional context

the plugin injects `window.` checks in fast-refresh which don't exist in a DedicatedWorkerScope.

**Comment by nrakochy** [comment]
Updating the `package-lock.json` to v4 of the vite plugin does indeed prevent the exception which will otherwise `throw`.

**Comment by vanessayuenn** [comment]
@nrakochy I believe this issue shouldn't occur on Storybook 8. Could you try it out and see if that resolved your problem?

**Comment by nrakochy** [comment]
Upgraded to v8, and it seems to be working. I am not sure, though, if this is b/c of monkey-patching the vite plugin locally or if upgrade fixes, but there's at least a path forward if some future traveler runs into it. Thanks for your note.
