### ISSUE TITLE
[Bug]: Imported JSX components in MDX do not work in Beta 5

### ISSUE THREAD

**Issue by T0miii** [storybookjs/storybook#26209]
### Describe the bug

Importing a simple .tsx file crashes the MDX File.

### To Reproduce

MDX
```
import { Meta } from "@storybook/blocks";
import TestBata from "@/stories/TestBata.tsx";

<Meta title="Configure your project" />
<div>Hi</div>
<TestBata></TestBata>
```

TSX
```
import React from 'react';

function Hello() {
    return (
        <div>
            <h1>Hello</h1>
        </div>
    );
}

export default Hello;
```

ERROR:
![image](https://github.com/storybookjs/storybook/assets/10532141/a1470d2e-f086-4963-a298-5d136f883095)

### System

Fresh vue , vite install with storybook 8 beta 5 installed

npm init vue@latest

**Comment by vanessayuenn** [comment]
I am not able to reproduce this on a fresh vue install. Can you please share a repro via [storybook.new](https://new-storybook.netlify.app/)? We prioritize bug reports that have reproduction. Thank you! 🙏

**Comment by T0miii** [comment]
I tried with storybook new also cant reproduce there. Issue can be closed i guess until i find the difference btw local project and the stackblitz. Thank you.
