### ISSUE TITLE
[Bug]: Misleading error message in Interactions addon

### ISSUE THREAD

**Issue by jonniebigodes** [storybookjs/storybook#26240]
### Describe the bug

During some testing with Storybook's beta, specifically with changes introduced to how interaction tests function (e.g., via the `@storybook/test` package and the recent removal of the argTypesRegex pattern in favor of mocked actions with `fn()`), it seems that we're introducing a misleading error message when trying to write a test for a component that includes an action, for instance, the submit button in a form. Here's a recording of the issue:

https://github.com/storybookjs/storybook/assets/22988955/c7f132d1-4729-4921-9e46-956db2058458

Based on the above and putting myself in the mindset of a user familiar with Storybook and how interaction tests work or a brand new user to the ecosystem, they may get confused by the error message as it doesn't provide any information about the actual problem. Additionally, if the user tries to search our documentation for a solution, we won't get any results as it's not documented. If instead the user attempts to search for the error message in [Google](https://www.google.com/search?q=Storybook+Found+1+unhandled+error+while+running+the+play+function.+This+might+cause+false+positive+assertions.+Resolve+unhandled+errors+or+ignore+unhandled+errors+with+setting+thetest.dangerouslyIgnoreUnhandledErrors+parameter+to+true&sca_esv=f5ffd29b8bf133f7&sca_upv=1&ei=h43fZaTLDuSskdUP3puZqAc&udm=&ved=0ahUKEwjkqrOq5s6EAxVkVqQEHd5NBnUQ4dUDCHE&uact=5&oq=Storybook+Found+1+unhandled+error+while+running+the+play+function.+This+might+cause+false+positive+assertions.+Resolve+unhandled+errors+or+ignore+unhandled+errors+with+setting+thetest.dangerouslyIgnoreUnhandledErrors+parameter+to+true&gs_lp=Egxnd3Mtd2l6LXNlcnAi6gFTdG9yeWJvb2sgRm91bmQgMSB1bmhhbmRsZWQgZXJyb3Igd2hpbGUgcnVubmluZyB0aGUgcGxheSBmdW5jdGlvbi4gVGhpcyBtaWdodCBjYXVzZSBmYWxzZSBwb3NpdGl2ZSBhc3NlcnRpb25zLiBSZXNvbHZlIHVuaGFuZGxlZCBlcnJvcnMgb3IgaWdub3JlIHVuaGFuZGxlZCBlcnJvcnMgd2l0aCBzZXR0aW5nIHRoZXRlc3QuZGFuZ2Vyb3VzbHlJZ25vcmVVbmhhbmRsZWRFcnJvcnMgcGFyYW1ldGVyIHRvIHRydWVIAFAAWABwAHgBkAEAmAEAoAEAqgEAuAEDyAEA-AEBmAIAoAIAmAMAkgcA&sclient=gws-wiz-serp) he's directed to either the Storybook GitHub issues or StackOverflow, where the first result is a GitHub issue that is not directly related to the problem at hand and the provided workaround will not work and the other relevant results are StackOverflow questions specific to Vitest which doesn't help the user at all. 

One other point of confusion for users is if they check their component and the Controls addon panel, they will see that the type is accurately inferred, leaving users confused about why the error is being thrown. 

I'm aware that the problem can be easily solved by mocking the action with `fn()` as demonstrated in the video, but the error message is not helpful. It doesn't provide any information about the actual problem or how to solve it.

cc @vanessayuenn @yannbf @kasperpeulen 

### To Reproduce

- Create a project using the framework of choice
- Install Storybook
- Create a simple form component
- Write a simple success interaction test (i.e., success case where the user fills in the username/password and clicks the submit button)

**Comment by shilman** [comment]
I agree this experience is sub-optimal. @kasperpeulen can you clarify whether this is the expected behavior in 8?

**Comment by kasperpeulen** [comment]
@shilman If the users uses `argTypesRegex` it will get a better error message, explaining you why argTypesRegex doesn't work anymore in the play function.

But if you creating a brand new storybook, there is no argTypesRegex, so we won't inject event handlers for you anymore, so basically the exact same error will happen if you would use this component outside of Storybook:
`<LoginForm />` 
without onSubmit handle.

I would kind of say this is only a problem for old users, creating a brand new storybook, but remembered that in SB < 8 we automatically injected event handlers. I don't think that a new user would expect SB to do this.

In some sense, the error is message is clear:
`onSubmit` is not a function

So you forgot to pass along onSubmit. And you can fix it by passing a function to onSubmit in your args.

TBH, I think most users would either have proptypes in place or typescript, which would give a better error message on runtime or in the editor.

**Comment by kasperpeulen** [comment]
I close this, as I don't think we can do anything about this.
