### ISSUE TITLE
[Bug]: Passing props to TextInput causes error

### ISSUE THREAD

**Issue by ShaneKeney** [storybookjs/storybook#26271]
### Describe the bug

Error when spreading props to `TextInput` component from `react-native`.  Removing `{...props}` fixes the issue.  However, it should be possible to spread props into the component such as:

``` 
<TextInput {...props} />
```

for easily creating extensible custom components that still allow all default prop types.

### To Reproduce

https://github.com/ShaneKeney/storybook-repro-1

See `components/TextInput`

May need to add a `.env.local` with `EXPO_PUBLIC_STORYBOOK_ENABLE=true` for injecting environment variable locally when running `yarn storybook`

### System

```bash
Storybook Environment Info:

  System:
    OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (32) x64 13th Gen Intel(R) Core(TM) i9-13900K
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
    Yarn: 1.22.19 - /mnt/c/Users/scken/AppData/Roaming/npm/yarn <----- active
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm
    pnpm: 8.15.1 - ~/.nvm/versions/node/v18.18.2/bin/pnpm
  Browsers:
    Chrome: 120.0.6099.216
  npmPackages:
    @storybook/addon-actions: ^7.6.13 => 7.6.17 
    @storybook/addon-controls: ^7.6.13 => 7.6.17 
    @storybook/addon-essentials: ^7.6.13 => 7.6.17 
    @storybook/addon-links: ^7.6.13 => 7.6.17 
    @storybook/addon-ondevice-actions: ^7.6.15 => 7.6.15 
    @storybook/addon-ondevice-backgrounds: ^7.6.15 => 7.6.15 
    @storybook/addon-ondevice-controls: ^7.6.15 => 7.6.15 
    @storybook/addon-ondevice-notes: ^7.6.15 => 7.6.15 
    @storybook/addon-react-native-web: ^0.0.22 => 0.0.22 
    @storybook/react: ^7.6.13 => 7.6.17 
    @storybook/react-native: ^7.6.15 => 7.6.15 
    @storybook/react-webpack5: ^7.6.13 => 7.6.17 
    storybook: ^7.6.13 => 7.6.17
```

### Additional context

Should be easily reproducible with above.  Adding and removing presents the issue respectively.

**Comment by vanessayuenn** [comment]
cc @shilman @dannyhw

**Comment by dannyhw** [comment]
I already responded to this in the react native issue it doesn't need to be duplicated here

**Comment by dannyhw** [comment]
https://github.com/storybookjs/react-native/issues/560
