### ISSUE TITLE
[Bug]: Restrict usage of node version less 18 in storybook 8

### ISSUE THREAD

**Issue by khats** [storybookjs/storybook#26296]
### Describe the bug

Migration document reference that storybook8 supports node 18 and above:
https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#dropping-support-for-nodejs-16

Code base do check for at least node 16:
https://github.com/storybookjs/storybook/blob/5428db705fbb312bb3712b5d2a4fdc072bb17c14/code/lib/cli/bin/index.js

**Comment by vanessayuenn** [comment]
@khats Good find! Looks like we missed that when we dropped Node 16 support. Any chance you would want to submit a PR fixing that _this week_, given that you already did the investigation? If not, we will still get this fixed before we GA 8.0.

**Comment by khats** [comment]
@vanessayuenn not sure that i will be able do it. I am failed on repo setup, so not rely on me:) Maybe next time, when i will be ready
