### ISSUE TITLE
[Bug]: Storybook failed to load the following preset

### ISSUE THREAD

**Issue by Banyalis** [storybookjs/storybook#26302]
### Describe the bug

Hello!
I'm getting an error after upgrading from version 6 to 7.

I'm using `Vue 2.7.14, Storybook 7.6.17, npm, node 18.15.0`

Error when starting `Storybook failed to load the following preset: ./node_modules/@storybook/vue-webpack5/preset`

.storybook/main.js:
```
const path = require('path');
const getAbsolutePath = (packageName) =>
    path.dirname(require.resolve(path.join(packageName, 'package.json')));

module.exports = {
    stories: ['../src/**/*.mdx', '../src/**/*.stories.@(js|jsx|mjs|ts|tsx)'],
    framework: {
        name: getAbsolutePath('@storybook/vue-webpack5'), // Also used '@storybook/vue-webpack5'
        options: {}
    },
    ...
};
```

storybook dependencies in package.json:
```
"devDependencies": {
    "@storybook/vue": "7.6.17",
    "@storybook/vue-webpack5": "7.6.17",
    "storybook": "7.6.17",
}
```

**Comment by valentinpalkovic** [comment]
Hi @Banyalis 

Do you use a mono-repo, where Storybook is installed in one of the sub lib/apps packages or is your folder structure pretty flat?

**Comment by yamiteru** [comment]
I have the same problem and I use Storybook in a monorepo.
