### ISSUE TITLE
[Bug]: Hide addons button not working

### ISSUE THREAD

**Issue by syedsalehinipg** [storybookjs/storybook#26320]
### Describe the bug

When trying to close the Hide Addons using the close button, the Hide Addons section is not closing, but the toggle button is appearing.

![Recording 2024-03-05 at 11 53 45](https://github.com/storybookjs/storybook/assets/143519265/b74e15c7-de62-4670-bc0f-c4f685574dbf)

**Comment by vanessayuenn** [comment]
Hi, thanks for reporting this. I am not able to reproduce this on a fresh Storybook. Can you please create a repro via [storybook.new](https://new-storybook.netlify.app/)? We prioritize bug reports that have reproduction. Thank you! 🙏
