### ISSUE TITLE
[Bug]: Composition not working in V8

### ISSUE THREAD

**Issue by DotwoodMedia** [storybookjs/storybook#26365]
### Describe the bug

When I run 2 storybooks locally (main on 6006 and composition storybook on 7007) I get this error:
![image](https://github.com/storybookjs/storybook/assets/55753961/5c1c2e08-8559-4fe8-85cf-0e8e98b1a942)

Can this be solved with a setting or is this a bug in storybook itself?

### System

```bash
Storybook Environment Info:

  System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
  Binaries:
    Node: 20.11.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.21 - C:\Program Files\nodejs\yarn.CMD
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD <----- active
    pnpm: 8.15.1 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (122.0.2365.66)
  npmPackages:
    @storybook/addon-essentials: 8.0.0-rc.3 => 8.0.0-rc.3
    @storybook/addon-links: 8.0.0-rc.3 => 8.0.0-rc.3
    @storybook/addon-themes: 8.0.0-rc.3 => 8.0.0-rc.3
    @storybook/blocks: 8.0.0-rc.3 => 8.0.0-rc.3
    @storybook/manager-api: 8.0.0-rc.3 => 8.0.0-rc.3
    @storybook/theming: 8.0.0-rc.3 => 8.0.0-rc.3
    @storybook/vue3: 8.0.0-rc.3 => 8.0.0-rc.3
    @storybook/vue3-vite: 8.0.0-rc.3 => 8.0.0-rc.3
    eslint-plugin-storybook: 0.8.0 => 0.8.0
    storybook: 8.0.0-rc.3 => 8.0.0-rc.3
```

**Comment by valentinpalkovic** [comment]
@ndelangen I guess this isn't related to https://github.com/storybookjs/storybook/issues/26288, is it?

**Comment by shilman** [comment]
@DotwoodMedia was it working as expected in v7? and have both storybooks been upgraded to v8?

**Comment by ndelangen** [comment]
I can take a look if you have a reproduction to share @DotwoodMedia

**Comment by DotwoodMedia** [comment]
The composition works again since 8.0.0-rc.4. Turned out to be the same problem as https://github.com/storybookjs/storybook/issues/26288
