### ISSUE TITLE
[Bug]: V8 Props must be included in the slot

### ISSUE THREAD

**Issue by Mikasa33** [storybookjs/storybook#26383]
### Describe the bug

✅ Documents can be displayed.
```
defineSlots<{
  default: (props: {}) => any
}>()
```
<img width="847" alt="image" src="https://github.com/storybookjs/storybook/assets/29498153/71e4afb7-1042-4107-9d4b-f6709b3613e0">

❌ Document cannot be displayed
```
defineSlots<{
  default: () => any
}>()
```
<img width="841" alt="image" src="https://github.com/storybookjs/storybook/assets/29498153/168d455a-65b2-4102-9fc5-d0ed30022ba5">

### System

```bash
"@storybook/addon-essentials": "^8.0.0-rc.3",
"@storybook/addon-interactions": "^8.0.0-rc.3",
"@storybook/addon-links": "^8.0.0-rc.3",
"@storybook/blocks": "^8.0.0-rc.3",
"@storybook/test": "^8.0.0-rc.3",
"@storybook/vue3": "^8.0.0-rc.3",
"@storybook/vue3-vite": "^8.0.0-rc.3",
"storybook": "^8.0.0-rc.3",
```

**Comment by shilman** [comment]
Can you please try the `vue-component-meta` docgen analysis and see if that fixes it?

```ts
// .storybook/main.js

export default {
  framework: {
    name: "@storybook/vue3-vite",
    options: {
      docgen: "vue-component-meta",
    },
  },
};
```
