### ISSUE TITLE
[Bug]: V8 Props are displayed as exposed in the document

### ISSUE THREAD

**Issue by Mikasa33** [storybookjs/storybook#26396]
### Describe the bug

<img width="319" alt="image" src="https://github.com/storybookjs/storybook/assets/29498153/5c29ba69-d539-473e-8da4-03824958b5e8">
<img width="514" alt="image" src="https://github.com/storybookjs/storybook/assets/29498153/24dc82bc-e7cc-4ce1-9033-a2a110715cd7">
<img width="497" alt="image" src="https://github.com/storybookjs/storybook/assets/29498153/6675d7f9-85a6-49d6-a2f6-b3c756747494">

### To Reproduce

Props are displayed as exposed in the document

### System

```bash
"@storybook/addon-essentials": "^8.0.0-rc.3",
"@storybook/addon-interactions": "^8.0.0-rc.3",
"@storybook/addon-links": "^8.0.0-rc.3",
"@storybook/blocks": "^8.0.0-rc.3",
"@storybook/test": "^8.0.0-rc.3",
"@storybook/vue3": "^8.0.0-rc.3",
"@storybook/vue3-vite": "^8.0.0-rc.3",
```

**Comment by shilman** [comment]
Can you please try the `vue-component-meta` docgen analysis and see if that fixes it?

```ts
// .storybook/main.js

export default {
  framework: {
    name: "@storybook/vue3-vite",
    options: {
      docgen: "vue-component-meta",
    },
  },
};
```

**Comment by tobi-fis** [comment]
@Mikasa33 can you tell me what fixed it for you in the end?

We have the exact same problem at the moment.
Props for callback functions are always listed under "exposed", not "props".

We use the proposed docgen analysis already. Package Versions are `8.4.7`
