### ISSUE TITLE
[Bug]: Storybook 8 notifications uses deprecated icons

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#26436]
### Describe the bug

As can be seen in the image:

![image](https://github.com/storybookjs/storybook/assets/1671563/9fe54bfc-b5cd-4649-9af4-ba6f0988d8b0)

Location: https://github.com/storybookjs/storybook/blob/7a10141273f5b4a31321872d6829a596ee100cb9/code/ui/manager/src/components/notifications/NotificationItem.tsx#L85

**Comment by SalahAdDin** [comment]
I saw and reported this issue in Discord, totally agree with this!
