### ISSUE TITLE
[Bug]: Spacing in interaction panel looks off in brand new SB8 installs

### ISSUE THREAD

**Issue by domyen** [storybookjs/storybook#26447]
### Describe the bug

The top spacing disappeared which means the text is directly touching the nav. 
<img width="624" alt="image" src="https://github.com/storybookjs/storybook/assets/263385/1a6e84a0-c707-45f3-838f-ef892316e7ba">

### To Reproduce

1. `npx storybook@latest init` in an empty project
2. Choose Next as the template
3. Run storybook, go to Button:Primary 
4. Click on the Interactions tab (you might have to open the addon panel)
5. See the spacing issue

### System

```bash
Mac Sonoma 14.2
Chrome
```

**Comment by cdedreuille** [comment]
I saw that as well. I'll fix it in the next couple of days.

**Comment by yannbf** [comment]
Closed by #26481
