### ISSUE TITLE
[Bug]: Can't hide addon panel (empty - "Nothing found")

### ISSUE THREAD

**Issue by mkosir** [storybookjs/storybook#26445]
### Describe the bug

After upgrading to Storybook v8.0 empty bottom panel appears with "Nothing found" text. Not sure how to hide/disable it as it was in v7.x, but tried different configs in `manager.ts` and `preview.tsx` as `showPanel: false`, ` disable: true` etc.

![Screenshot 2024-03-12 at 15 05 25](https://github.com/storybookjs/storybook/assets/3073826/24d6f58b-1b94-4319-aa95-e665ab2b5cdb)

### System

```bash
Storybook Environment Info:

  System:
    OS: macOS 14.4
    CPU: (12) arm64 Apple M2 Max
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
    npm: 10.5.0 - ~/Desktop/projects/react-parallax-tilt/node_modules/.bin/npm <----- active
    pnpm: 8.15.4 - ~/.nvm/versions/node/v20.11.1/bin/pnpm
  Browsers:
    Chrome: 122.0.6261.112
    Safari: 17.4
  npmPackages:
    @storybook/addon-webpack5-compiler-swc: 1.0.2 => 1.0.2 
    @storybook/manager-api: 8.0.0 => 8.0.0 
    @storybook/react: 8.0.0 => 8.0.0 
    @storybook/react-webpack5: 8.0.0 => 8.0.0 
    @storybook/theming: 8.0.0 => 8.0.0 
    eslint-plugin-storybook: 0.8.0 => 0.8.0 
    storybook: 8.0.0 => 8.0.0
```

**Comment by tourshi** [comment]
for anyone that needs to hide the addon panel and wasn't able to with 'showPanel' (seems to be removed as of v8), i managed to hide it by passing `bottomPanelHeight: 0` instead
