### ISSUE TITLE
[Bug]: The attribute of the Vue3 + TSX component is jsx, and the source code display is incorrect.

### ISSUE THREAD

**Issue by a474516631** [storybookjs/storybook#26440]
### Describe the bug

Vue3 + TSX displays props with tsx source code, such as `args: {
    primary: true,
    label: 'Button',
    jsx:()=>{
      return <button>hello</button>
    }
  },` will be displayed `<template> 
  <Button :primary="true" label="Button" jsx="() => { return
  _createVNode("button", null, [_createTextVNode("hello")]); }"/>
</template>`

**Comment by vanessayuenn** [comment]
Hi, can you please elaborate on what you expect to see, and specify what version of Storybook you're using? If you believe this to be a bug, please also share a repro using [storybook.new](https://new-storybook.netlify.app/). We prioritize bug reports that have reproduction. Thank you! 🙏
