### ISSUE TITLE
[Bug]: `@storybook/addon-styling-webpack` is downgraded when upgrading from beta 8 to stable 8 release

### ISSUE THREAD

**Issue by huyenltnguyen** [storybookjs/storybook#26451]
### Describe the bug

I'm currently using Storybook 8.0.0-beta.3. When I tried upgrading to the stable v8 release (using the `npx storybook@latest upgrade` command), I got the following message:

<img width="843" alt="Screenshot 2024-03-12 at 22 18 26" src="https://github.com/storybookjs/storybook/assets/25715018/9df07f5c-4940-4c79-a1e3-3959e5ca094c">

With `@storybook/addon-styling-webpack` being downgraded from 1.0.0 to 0.0.6.

Once the migration was completed, I started Storybook and got the following warning (which was expected):

<img width="843" alt="Screenshot 2024-03-12 at 22 36 41" src="https://github.com/storybookjs/storybook/assets/25715018/bb0b892d-1312-4b2f-9301-66ac41449f93">

---

I was able to start Storybook successfully and things seem to work as expected with `@storybook/addon-styling-webpack` 0.0.6, but I'm wondering if the downgrade is expected.

**Comment by vanessayuenn** [comment]
@JReinhold i think we just need to release a new version of `@storybook/addon-styling-webpack` right?

**Comment by JReinhold** [comment]
@ndelangen decided to not release a new version of `@storybook/addon-styling-webpack` yet, before we have fixed the fundamental issue, as it's a great way to test out the fix in a real scenario.

**Comment by ndelangen** [comment]
Let's release it, my PR is open and tested.

**Comment by ndelangen** [comment]
And merged!
