### ISSUE TITLE
[Bug]: Cannot upgrade to v8 as `Support for Vue 2 has been removed` but not using Vue

### ISSUE THREAD

**Issue by Spence1115** [storybookjs/storybook#26461]
### Describe the bug

I have a project on Webpack and React, but when I try to upgrade to Storybook 8 I get blocked because `Support for Vue 2 has been removed`. However, I'm not using Vue at all, and the only dependencies for `vue` in my yarn.lock file appear to be **because** of storybook.

### System

```bash
Storybook Environment Info:

  System:
    OS: macOS 14.3.1
    CPU: (10) arm64 Apple M1 Pro
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.9.0 - ~/n/bin/node
    Yarn: 4.0.0 - ~/.yarn/bin/yarn <----- active
    npm: 10.1.0 - ~/n/bin/npm
  Browsers:
    Chrome: 122.0.6261.112
    Safari: 17.3.1
  npmPackages:
    @storybook/addon-essentials: ^7.6.6 => 7.6.6 
    @storybook/addon-interactions: ^7.6.6 => 7.6.6 
    @storybook/addon-links: ^7.6.6 => 7.6.6 
    @storybook/addon-onboarding: ^1.0.10 => 1.0.10 
    @storybook/addon-styling-webpack: ^0.0.5 => 0.0.5 
    @storybook/blocks: ^7.6.6 => 7.6.6 
    @storybook/react: ^7.6.6 => 7.6.6 
    @storybook/react-webpack5: ^7.6.6 => 7.6.6 
    @storybook/test: ^7.6.6 => 7.6.6 
    @storybook/test-runner: ^0.17.0 => 0.17.0 
    eslint-plugin-storybook: ^0.6.15 => 0.6.15 
    msw-storybook-addon: ^1.10.0 => 1.10.0 
    storybook: ^7.6.6 => 7.6.6 
    storybook-addon-react-router-v6: ^2.0.10 => 2.0.10 
    storybook-test: ^0.1.8 => 0.1.8 
```
```


### Additional context

_No response_

**Comment by shilman** [comment]
Can you share your project's `package.json` dependencies/devDependencies/peerDependencies?

**Comment by shilman** [comment]
Upon further investigation, can you remove the deprecated `storybook-test` dependency and try again?

https://www.npmjs.com/package/storybook-test?activeTab=dependencies

**Comment by shilman** [comment]
@ndelangen @valentinpalkovic I wonder if the autoblockers should check direct dependencies/devDependencies rather than whether the package is installed at all. WDYT?
