### ISSUE TITLE
[Bug]: Chromatic plugin warns of incorrect `storybookConfigDir` configuration

### ISSUE THREAD

**Issue by szpytfire** [storybookjs/storybook#26511]
### Describe the bug

First & foremost - Storybook 8 & the Chromatic plugin works a charm! :party

However, Chromatic appears to complain about a 'configuration problem':

<img width="516" alt="image" src="https://github.com/storybookjs/storybook/assets/8623098/4ff914ae-668e-4fe6-a51c-ae119d4171cb">

specifically:

<img width="621" alt="image" src="https://github.com/storybookjs/storybook/assets/8623098/ebf3dda6-c0bb-4211-bd52-95df813fd304">

This looks to be a bug, as the suggestion is identical to the string that's currently set.

For reference, my chromatic config file looks as follows:
```
{
  "projectId": "Project:<ID_HERE>",
  "zip": true,
  "storybookBaseDir": "<PATH_HERE>",
  "storybookConfigDir": "src/.storybook"
}

```

**Comment by ghengeveld** [comment]
Pretty sure this was fixed in https://github.com/chromaui/addon-visual-tests/pull/222
Can you verify with v1.2.21 of the addon?

**Comment by szpytfire** [comment]
@ghengeveld - yep, this can now be closed. Thanks 👍
