### ISSUE TITLE
[Bug]: Degraded startup performance with storyStoreV7

### ISSUE THREAD

**Issue by ajkl2533** [storybookjs/storybook#26517]
### Describe the bug

We finally removed all the `storiesOf` syntax to use `storyStoreV7`, but after enabling `storyStoreV7` we noticed a huge startup time increase. We have a big monolithic repository so the performance wasn't that good even before but after enabling `storyStoreV7` the startup time for `preview` went from **1min** to more than **2mins** and for `manager` from **150ms** to **17s**.

We are using `webpack@5` and `babel` for building.

### `storyStoreV7: false`
![Screenshot 2024-03-15 at 13 52 56](https://github.com/storybookjs/storybook/assets/18654425/31e52441-b012-4230-a8a5-c3d3746066bd)

### `storyStoreV7: true`
![Screenshot 2024-03-15 at 13 52 46](https://github.com/storybookjs/storybook/assets/18654425/81120996-824f-40ae-8738-f292f1f829ce)

### Storybook 8
![Screenshot 2024-03-15 at 14 14 03](https://github.com/storybookjs/storybook/assets/18654425/90bbae5d-d358-4dc1-8e9a-80a3c20f141e)

### To Reproduce

Unfortunately, I cannot share the repository. But I tested in one of our public repositories and the degradation is noticeable even though we are using Vite there (140ms -> 1.1s for manager, 5.4s to 8s for UI).

You can use `next-major` branch in https://github.com/securityscorecard/design-system/tree/next-major. And disable `storyStoreV7` in `.storybook/main.ts`.

### System

```bash
Storybook Environment Info:

  System:
    OS: macOS 14.4
    CPU: (10) arm64 Apple M1 Pro
    Shell: 5.9 - /opt/homebrew/bin/zsh
  Binaries:
    Node: 18.19.1 - ~/.nvm/versions/node/v18.19.1/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn <----- active
    npm: 10.2.4 - ~/.nvm/versions/node/v18.19.1/bin/npm
    pnpm: 8.15.1 - ~/.nvm/versions/node/v18.19.1/bin/pnpm
  Browsers:
    Chrome: 122.0.6261.129
    Edge: 122.0.2365.92
    Safari: 17.4
  npmPackages:
    @storybook/addon-actions: ^7.6.10 => 7.6.10 
    @storybook/addon-essentials: ^7.6.10 => 7.6.10 
    @storybook/react: ^7.6.10 => 7.6.10 
    @storybook/react-webpack5: ^7.6.10 => 7.6.10 
    msw-storybook-addon: ^1.10.0 => 1.10.0 
    storybook: ^7.6.10 => 7.6.10
```

### Additional context

I wouldn't mind staying off the storyStoreV7 but we wanted to migrate to v8 and since there is no choice I'm raising this.

**Comment by shilman** [comment]
@ajkl2533 I checked out the `next-major` branch and it is using the Vite builder and building fairly quickly for me even though there are no `storyStoreV7` settings in `main.ts`. Do you still need me to investigate this?

**Comment by ajkl2533** [comment]
@shilman Thank you for looking into it. I agree that in the repository I send it's quick. But as I said it's a small project and it uses Vite and even then the increase there for the manager is almost 800% (140 -> 1100ms) and for UI 150% (5.4s -> 8s).
For the big project that uses Webpack is the increase for manager is also around 11 000% (150ms -> 17s) and 200% (1min -> 2mins). 
So I think it's still valid to investigate more.

**Comment by shilman** [comment]
@ajkl2533 I see. I mis-read your issue description. Checking again now. 👍

**Comment by shilman** [comment]
@ndelangen @vanessayuenn this does look like a possible bug. specifically, the manager builds in 100ms in V6 mode vs 1s in V7 mode. I suspect what's going on is that in V5 mode the manager & preview builds are executed in series, whereas in V7 mode they are executed in parallel. We've seen before that when two builds happen simultaneously it can lead to thrashing and an overall shower experience even though in theory parallel should be faster.

@ajkl2533 Thanks so much for raising this and providing a repro!

**Comment by shilman** [comment]
Possible duplicate to https://github.com/storybookjs/storybook/issues/21333

**Comment by tmeasday** [comment]
@ajkl2533 my suggestion for your webpack repo is to [use `lazyCompilation`.](https://storybook.js.org/blog/storybook-lazy-compilation-for-webpack/) We built that feature for exactly large repos like the one you mention -- unfortunately the tradeoff with webpack is that compilation does that longer when you introduce code splitting (with the benefit that recompilations and page load time being significantly faster).

**Comment by ajkl2533** [comment]
@tmeasday Thank you for the suggestion I didn't know about this. The manager startup time stayed the same but the preview went from 2 minutes down to 25 seconds 🎉

**Comment by ndelangen** [comment]
@shilman In v8 we ditches the parallel execution of both builders, in favor of running the manager first.

https://github.com/storybookjs/storybook/blob/b0736416148b7cc5175204aa12714d5de0880a41/code/lib/core-server/src/dev-server.ts#L87-L93

I'd be interested in investigating why the manager might be taking multiple seconds to build, that does not seem right.

I manually upgraded the repro to SB8 and got this as a result:
![Screenshot 2024-03-20 at 14 38 57](https://github.com/storybookjs/storybook/assets/3070389/98601d1a-1a65-46df-aacb-ff09502dcd84)

@shilman I got most of the storybook to work after the upgrade, except for addon-docs & MDX.

If you're interested, here the PR after the upgrade:
https://github.com/securityscorecard/design-system/pull/936

**Comment by ndelangen** [comment]
I think it's safe to say there's no performance issue in the manager builder in v8 @vanessayuenn

**Comment by shilman** [comment]
@ndelangen are you sure?

> specifically, the manager builds in 100ms in V6 mode vs 1s in V7 mode.

In your screenshot you shared manager is building in 700ms. That's not a lot, but it's still 7x bigger than the 100ms I saw in V6 mode. I don't think it's correct to say that there's no performance issue.

**Comment by vanessayuenn** [comment]
is this still an issue with 8.x? @shilman @ndelangen

**Comment by ndelangen** [comment]
We've removed storyStoreV7 in 8.0, so no.

**Comment by denieler** [comment]
hey folks 👋 I must say we also see some performance issues with v8 vs v7 🤔  They are close, but still v8 objectively slower building manager and preview on a large codebase

**Comment by denieler** [comment]
> [@denieler](https://github.com/denieler) Can you share your project specifics?

@shilman can't share the project, but our monorepo has around 26000 files and when upgraded from v7 to v8 we experience that the build of the storybook started to be slower. We use `@storybook/builder-webpack5` builder. And only introducing `lazyCompilation` option made storybook usable.

**Comment by shilman** [comment]
@denieler The manager build should be fast (sub-second) in both v7 and v8. If it't not, please let me know. Preview build is its own thing and may be different depending on your project. Are you using React + TypeScript? If so, are you using `react-docgen-typescript`? If so, does using other settings dramatically improve perf?

https://storybook.js.org/docs/api/main-config/main-config-typescript

**Comment by ajkl2533** [comment]
Well @shilman that's the thing I was saying when I created this issue (and documented with screenshots). With SB@8 we saw huge performance degradation, it got better over time with newer version, at least for the manager part. When I did the upgrade the manager took more than 15s, now we are using v8.2.2 and manager starts in 400ms, which is good. But the preview part is still around 2 minutes (was 1 minute before) without any changes in our build setup, just because we upgraded to SB@8 and start using storyStoreV7.

I would expect that if we are forced to upgrade to something new (which is fine) the new thing will perform at least same as the previous one and if it doesn't there will be some kind of feedback from your side other than:

> I think it's safe to say there's no performance issue in the manager builder in v8

or

> We've removed storyStoreV7 in 8.0, so no.

Again it's nothing personal agains you guys, you are doing lots of great job and love using Storybook but in this case I kind of feel that you neglect this issue.

**Comment by denieler** [comment]
> [@denieler](https://github.com/denieler) The manager build should be fast (sub-second) in both v7 and v8. If it't not, please let me know. Preview build is its own thing and may be different depending on your project. Are you using React + TypeScript? If so, are you using `react-docgen-typescript`? If so, does using other settings dramatically improve perf?
> 
> https://storybook.js.org/docs/api/main-config/main-config-typescript

Yes, we use TS + React and yes, obviously if we skip typecheck it improves the performance. But we tested side by side with the same configurations v7 and v8 and v8 behaves slower. In addition to that `react-docgen` fails with memory issues not letting us to build the storybook, so we had to stick with `react-docgen-typescript` 🤷‍♂ 

Here I agree with @ajkl2533:

> I would expect that if we are forced to upgrade to something new (which is fine) the new thing will perform at least same as the previous one and if it doesn't there will be some kind of feedback from your side other than:
> > I think it's safe to say there's no performance issue in the manager builder in v8
>
> or
>
> > We've removed storyStoreV7 in 8.0, so no.

We invested quite a lot into upgrading, and now we have a second thought if even we had to do that.

**Comment by shilman** [comment]
> Yes, we use TS + React and yes, obviously if we skip typecheck it improves the performance.

@denieler i'm asking about docgen because i want to understand whether the problem is specifically with the docgen handling, or whether it is a problem with storyStoreV7/webpack. This is a complex system and without a reproduction I can only ask high level questions to try to understand where the time is going.

**Comment by ajkl2533** [comment]
@shilman again it's not against you or Storybook. It was mostly to point out that this issue got closed even though there is still noticeable performance degradation with SSv7.

I tried the suggestion with `lazyCompilation` and `fsCache` but unfortunately that broke integration with our visual testing solution so it's not usable for us unfortunately (I will try to retest that since it's already some time ago). I'm pretty sure that this is somehow related to webpack because I don't have these issues in other repository that use Vite.

To your question, I tried startup times with different `reactDocgen` settings:

`reactDocgen: 'react-docgen-typescript'`
![Image](https://github.com/user-attachments/assets/fceac204-1b8d-4862-9f08-3dbad65277db)

`reactDocgen: 'react-docgen'`
![Image](https://github.com/user-attachments/assets/4c841255-b621-477c-a7b9-082a9c48b3c7)

`reactDocgen: false`
![Image](https://github.com/user-attachments/assets/078f1a4e-faaf-462d-a139-f770f6dfccec)

This is our `typescript` config we use
![Image](https://github.com/user-attachments/assets/42793210-5de0-4237-971e-904d270bf5fc)

**Comment by shilman** [comment]
@ajkl2533 No offense taken. I just want to keep the conversation focused on a solution. I can re-open the issue if you like, but I don't think we're going to revisit a design decision that was made over three years ago. AFAIK the code splitting solution benefits most projects, and it's unfortunate that there are cases where it doesn't. @tmeasday would we consider a builder option to disable code splitting? Or could that be easily configured by the user in `webpackFinal`?

Thanks so much for the docgen perf measurements. It's interesting (and unexpected!) that `react-docgen-typescript` is even faster than `react-docgen` in your project. @tmeasday @valentinpalkovic @ndelangen we really need to do the annotation server at some point!

**Comment by ajkl2533** [comment]
🙏 I accepted the fact that it takes quite some time to start up Storybook, but I usually keep it running and none of my fellow engineers did not complained so far and there is caching solution that can be used. But I can see that it can be an issue not only for us but also for others so I'm trying to push a bit harder.

It would be interesting to find out which part of SSv7 caused the issue but since neither @denieler or I can let you in inside our projects there's not much that can be done right now.

**Comment by shilman** [comment]
@ajkl2533 i think @tmeasday  stated that it's simply the code splitting that slows things down. Vite doesn't do any bundling in dev mode so code splitting is "free." But webpack actually has to do some dependency graph analysis and that takes time on a large codebase. With lazy compilation it still has to do that analysis, but then when it's done it has much less code to actually bundle...

**Comment by tmeasday** [comment]
> @tmeasday would we consider a builder option to disable code splitting? Or could that be easily configured by the user in webpackFinal?

I think at one stage @IanVS and I were talking about an "eager" loading mode for SSv7 (I guess that was in the context of Vite, so not directly relevant but conceptually the same).

@ajkl2533 @denieler are you able to update your project to the latest 8.4 version? I could try making a canary with eager loading enabled (essentially by changing [the generated `importFn`](https://github.com/storybookjs/storybook/blob/487d2cb196b3ac97169579ba23fccec86f30de7a/code/lib/core-webpack/src/to-importFn.ts#L81-L88) to be "dumb" and load everything right away) and we could see what difference it makes?
