### ISSUE TITLE
[Bug]: Nx Project cannot watch and hot reload

### ISSUE THREAD

**Issue by TheDevelolper** [storybookjs/storybook#26540]
### Describe the bug

I'm using Nx with storybook. I see storybook used to support --watch and someone broke it but rather than fixing it was removed 🤷🏽. 

The problem is that now I'm left unsure how to get storybook to hot reload in an Nx project.

### To Reproduce

Create an Nx Project with React and vite
Install the storybook plugin

Try adding --watch flag

### System

```bash
Storybook Environment Info:

  System:
    OS: Linux 5.10 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (16) x64 Intel(R) Core(TM) i9-10980HK CPU @ 2.40GHz
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 20.11.1 - /usr/local/share/nvm/versions/node/v20.11.1/bin/node
    Yarn: 1.22.22 - /usr/bin/yarn <----- active
    npm: 10.2.4 - /usr/local/share/nvm/versions/node/v20.11.1/bin/npm
  npmPackages:
    @storybook/addon-essentials: 7.6.17 => 7.6.17 
    @storybook/addon-interactions: ^7.5.3 => 7.6.17 
    @storybook/core-server: 7.6.17 => 7.6.17 
    @storybook/jest: ^0.2.3 => 0.2.3 
    @storybook/react-vite: 7.6.17 => 7.6.17 
    @storybook/test-runner: ^0.13.0 => 0.13.0 
    @storybook/testing-library: ^0.2.2 => 0.2.2 
    storybook: 7.6.17 => 7.6.17
```

### Additional context

There has to be a workaround for this? It feels like you had something that worked really well... why wouldn't you just fix it?

**Comment by shilman** [comment]
Are you referring to this issue? https://github.com/storybookjs/storybook/issues/15946

Why can't you just run Storybook in `dev` mode?

**Comment by TheDevelolper** [comment]
Hey @shilman, I'm not sure how I'm supposed to do that from within an Nx Monorepo. I couldn't find any documentation on how to do this? 

When you say running it in dev mode do you mean firing up the storybook cli? I did try that but it didn't seem to even build, I think it was looking for the dist directory for the storybook js files. I was probably going about it the wrong way. 

How would you run it in dev mode exactly? Is there a configuration I can put somewhere?

**Comment by shilman** [comment]
@mandarini @valentinpalkovic  is this something you can help with?

**Comment by valentinpalkovic** [comment]
Hi @TheDevelolper 

Unfortunately, I don't understand your issue. On which step do you fail? What are you supposed to do? 

There are a couple of Storybook recipes for NX available: https://nx.dev/recipes/storybook

Can you tell me what you have tried and what exactly isn't working?

**Comment by TheDevelolper** [comment]
Hey,  I'm on mobile atm so message may be a little messy.

 I'm trying to run storybook via Nx.

It works but hot reload isn't working so my workflow is Really slow. I mean unusable. I need to run the whole thing again on each change.

**Comment by TheDevelolper** [comment]
Hey,  I'm on mobile atm so message may be a little messy.

 I'm trying to run storybook via Nx.

It works but hot reload isn't working so my workflow is Really slow. I mean unusable. I need to run the whole thing again on each change. 


It used to work with the --watch flag but this no longer seems to be supported. Not sure how I can get hot reload back.

**Comment by valentinpalkovic** [comment]
Can you provide a minimal reproduction?

**Comment by TheDevelolper** [comment]
> Can you provide a minimal reproduction?

Absolutely, I'll make a repo tomorrow and update this ticket.

**Comment by TheDevelolper** [comment]
Hey @valentinpalkovic, Here's the repo

[https://github.com/TheDevelolper/-storybook-hotload-issue](https://github.com/TheDevelolper/-storybook-hotload-issue)

sorry about the weird - at the start of the name, it was a typo but shouldn't affect anything.

If you open it and run `yarn story book` or `npm run storybook` then storybook will open but if you make a change to the text component in the ui library it won't be hot reloaded.

**Comment by sshmaxime** [comment]
@TheDevelolper I think your problem is coming from the fact that `nx` or `turbo` uses build outputs. `storybook dev` has hot reload but it doesn't actually build the outputs. Therefore you other app doesn't get the feed changes. As I see you are using `vite` the alternative for you is to start in parallel `vite build --watch`. You can use the `concurrently` package to help you with executing both process at the same time.

**Comment by TheDevelolper** [comment]
I was using this from within a dev container, unfortunately docker seems to have given up the ghost, I removed an import from the preview.ts using github codespaces (hopefully it will still build) it just referenced some css. It wasn't needed for this minimal example.

**Comment by TheDevelolper** [comment]
I think the problem stems from the fact that the nx plugin react-vite expects the watch flag to work. You used to be able to pass it but it was removed when it got broken.

**Comment by mandarini** [comment]
I am sorry, I'm travelling this week so it will be a bit hard to debug. I will add it to my priorities for Friday (earliest) or next Tuesday!! Sorry about that!!!

**Comment by TheDevelolper** [comment]
> I am sorry, I'm travelling this week so it will be a bit hard to debug. I will add it to my priorities for Friday (earliest) or next Tuesday!! Sorry about that!!!
> 
> I assigned to myself for the time being, until I investigate more!

No need to apologise, I just appreciate any help you can offer! 🙂

**Comment by TheDevelolper** [comment]
Hey, I took a look at this again today, I set up a new project with Nx and storybook and et voila, it seemed to work right off the bat with hot reloading. No need for the watch flag. 

I'm not sure what the issues are with my other project, it might be due to the project locations maybe? I'll have to investigate but I have something that works which is perfect for now.

**Comment by mandarini** [comment]
Perfect @TheDevelolper ! That's great to hear. If you encounter an issue again just let us know!

**Comment by TheDevelolper** [comment]
@mandarini I managed to reproduce the issue! Okay so this only seems to happen when I run Storybook with Nx inside a Linux dev container! For some reason when running it on the dev container changes aren't detected and updates do not happen. 

My thinking is that it could be one of two things, either there's a port somewhere that's required for the hot reload (possibly via websocket?) to work OR it has something to do with file watchers in the Linux container. 

I'm a little new to this so I'm not sure how I could prove either of these cases.

Do you know if there are any specific ports I need to expose for websockets to work?

I'll do some research into the system watchers thing.

**Comment by TheDevelolper** [comment]
Okay another update, when I make a change outside of the container I see something in my prompt saying "hmr update"... when I run it in the container I don't see it! 

So I think that rules out the socket theory.

Now I'm thinking it's either something to do with the way vite detects changes or system watchers

**Comment by TheDevelolper** [comment]
WOW This was quite the side quest! 

There's a problem with some components that vite uses to monitor file changes.

This gets things working: 

first install: 
``` bash 
$ apt-get -y install inotify-tools
```
If I go to the directory where my component is being edited and I run: 
``` bash 
$ inotifywait -m -e modify "."
```

Now start storybook... it works! 

I tried going to the root dir of the project and running the command with the recursion flag like below but that didn't work: 

``` bash 
$ inotifywait -m -e modify "."
```

More info:
here : https://github.com/vitejs/vite/discussions/14007
which suggests this:  https://github.com/abiosoft/colima/issues/261

**Comment by TheDevelolper** [comment]
I found further information here: 
https://syntackle.com/blog/the-issue-of-watching-file-changes-in-docker/

and I left a comment here: 
https://github.com/microsoft/vscode-remote-release/issues/9282

My suggestion for now is to implement inotifywait  -m -e modify "." as part of a post build script, this will set up all the required system watchers. This really sucks but it seems to be the only viable workaround for now. 

What I can say is that this is NOT a storybook issue, it's not a vite issue, it's a docker volumes issue.

**Comment by TheDevelolper** [comment]
I found a solution to the problem and I've written an article on how to fix it here: 

https://dev.to/simplifycomplexity/solving-hot-reload-issues-in-vs-code-dev-containers-on-windows-with-wsl2-16d5

**Comment by RafaRochaS91** [comment]
Did this ever got brought into the NX issues?
Since this is something that the official nx storybook plugin should tackle.
