### ISSUE TITLE
[Bug]: next/navigation#useParams returns null when using @storybook/nextjs

### ISSUE THREAD

**Issue by samit4me** [storybookjs/storybook#26574]
### Describe the bug

Just tried updating from Storybook v7 to v8 and `useParams` from next, directly or indirectly is returning `null`, but expecting it to return an empty object `{}` if no params are present. In v7 it appeared to returned an object as listed in the [next docs](https://nextjs.org/docs/app/api-reference/functions/use-params#returns).

This seems to be a repeat of this closed bug https://github.com/storybookjs/storybook/issues/22077

### To Reproduce

Created a [small repo](https://github.com/samit4me/next-storybook-useparams) to demo the issue!

- clone repo
- npm install
- npm run storybook
- Navigate to Example > Button > Primary _(you'll see an error - it should log null to the console)_

The issue can be [seen here](https://github.com/samit4me/next-storybook-useparams/blob/main/src/stories/Button.tsx#L38-L39):
```
const params = useParams<{ tag: string}>();
console.log('#### ~ params:', params.tag); // throws error due to params being null, but expecting params to be {}
```

### System

```bash
Storybook Environment Info:

  System:
    OS: macOS 14.4
    CPU: (12) arm64 Apple M3 Pro
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v20.11.1/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm <----- active
    pnpm: 8.15.4 - ~/.nvm/versions/node/v20.11.1/bin/pnpm
  Browsers:
    Chrome: 122.0.6261.129
    Safari: 17.4
  npmPackages:
    @storybook/addon-essentials: ^8.0.2 => 8.0.2 
    @storybook/addon-interactions: ^8.0.2 => 8.0.2 
    @storybook/addon-links: ^8.0.2 => 8.0.2 
    @storybook/addon-onboarding: ^8.0.2 => 8.0.2 
    @storybook/blocks: ^8.0.2 => 8.0.2 
    @storybook/nextjs: ^8.0.2 => 8.0.2 
    @storybook/react: ^8.0.2 => 8.0.2 
    @storybook/test: ^8.0.2 => 8.0.2 
    eslint-plugin-storybook: ^0.8.0 => 0.8.0 
    storybook: ^8.0.2 => 8.0.2
```

**Comment by valentinpalkovic** [comment]
The `next/navigation` package should only be used in the apps directory. There aren't any official documents, that `next/navigation` can be used in the pages directory. 

Your reproduction does not set up the `parameters.nextjs.appDirectory: true`. After setting up the parameter correctly, it works. Please follow the documentation here: 
https://storybook.js.org/docs/get-started/nextjs#nextjs-navigation

**Comment by samit4me** [comment]
Thanks @valentinpalkovic that did work, but looks like we're having the same issue again with Next 14.2.3 and Storybook 8.0.9.

**Comment by valentinpalkovic** [comment]
@samit4me please try to regenerate your npm/yarn/pnpm lock file and try it again. Otherwise, please try to provide a reproduction: http://storybook.new

**Comment by samit4me** [comment]
Thanks @valentinpalkovic, tried do that but still had the same issue unfortunately.
Read the docs again and found a [related section](https://storybook.js.org/docs/get-started/nextjs#useselectedlayoutsegment-useselectedlayoutsegments-and-useparams-hooks) and discovered that adding something like this resolved the issue. Never needed this previously, but that may or may not have been a bug 😅  Cheers for the help 🙌 

```
         nextjs: {
             appDirectory: true,
+            navigation: {
+                segments: [["locale", "en"]],
+            },
         },
```
