### ISSUE TITLE
[Bug]: code blocks not working in mdx

### ISSUE THREAD

**Issue by Hanna922** [storybookjs/storybook#26591]
### Describe the bug

This issue pertains to the non-functioning of code blocks in MDX files.
My project uses vite (v4.4.5), react (v18.2.0), storybook (v7.4.0) and pnpm.
Although I searched for related issues, it seems the exact cause has not been fully identified yet.
Through multiple tests, I've determined that this bug is reproducible in projects that utilize storybook (v7) and pnpm.

The output looks as follows:

**pnpm + 7.4.0**
<img width="910" alt="image" src="https://github.com/storybookjs/storybook/assets/84809236/41a210d1-a262-4f67-8deb-0a04ae67b7fe">

**pnpm + 8.1.0-alpha.3**
<img width="911" alt="image" src="https://github.com/storybookjs/storybook/assets/84809236/3b9e021d-baf1-4ada-826b-3228f96e77ec">

**yarn + 7.4.0**
<img width="1010" alt="image" src="https://github.com/storybookjs/storybook/assets/84809236/60bd4aad-fd6d-43a8-a021-1d954810dadc">

### To Reproduce

https://github.com/Hanna922/storybook-mdx-bug-test

1. npx storybook@next sandbox (React Latest (Vite | TypeScript)
2. remove resolutions in package.json
3. downgrade storybook version (v8 -> v7)
4. pnpm install & pnpm storybook

### System

```bash
Storybook Environment Info:

  System:
    OS: macOS 13.5
    CPU: (8) arm64 Apple M1
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v20.11.1/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm
    pnpm: 8.15.4 - /opt/homebrew/bin/pnpm <----- active
  Browsers:
    Chrome: 122.0.6261.129
    Safari: 16.6
  npmPackages:
    @storybook/addon-essentials: ^7.4.0 => 7.6.17 
    @storybook/addon-interactions: ^7.4.0 => 7.6.17 
    @storybook/addon-links: ^7.4.0 => 7.6.17 
    @storybook/blocks: ^7.4.0 => 7.6.17 
    @storybook/react: ^7.4.0 => 7.6.17 
    @storybook/react-vite: ^7.4.0 => 7.6.17 
    @storybook/test: ^7.4.0 => 7.6.17 
    storybook: ^7.4.0 => 7.6.17
```

### Additional context

I discovered a bug while transitioning my project's package manager from yarn to pnpm. 

### related issues
- https://github.com/storybookjs/storybook/issues/24729
- https://github.com/storybookjs/storybook/issues/24769

**Comment by vanessayuenn** [comment]
Thank you for reporting this @Hanna922! did I interpret correctly that this is _not_ an issue on Storybook 8? We only backport security fixes to previous major versions, so I recommend to continue using Storybook 8 to avoid this bug. Please let me know if this is still a problem on 8, though.
