### ISSUE TITLE
[Bug]: Parameter with function as value is not available in Manager API

### ISSUE THREAD

**Issue by floriangosse** [storybookjs/storybook#26598]
### Describe the bug

When you use a function as the value for parameter config in `preview.js` this function isn't available when you use `useParameter` from the manager API. All the other keys are available.

### To Reproduce

In `preview.js`:

```js
const preview = {
	parameters: {
		myParams: {
			stringKey: 'a string',
			functionKey: () => 'from a function'
		}
	}
};

export default preview;
```

Inside a manager component (addon):

```js
import { useParameter } from '@storybook/manager-api'; 

function MyPanel() {
	const params = useParameter('myParams');

	console.log('stringKey' in params); // => true
	console.log('functionKey' in params); // => false

	// ...
}
```

### System

```bash
System:
	OS: macOS 13.5.1
	CPU: (10) arm64 Apple M1 Max
	Shell: 5.9 - /opt/homebrew/bin/zsh
Binaries:
	Node: 18.19.1 - ~/.nvm/versions/node/v18.19.1/bin/node
	Yarn: 1.22.19 - ~/.nvm/versions/node/v18.19.1/bin/yarn
	npm: 10.2.4 - ~/.nvm/versions/node/v18.19.1/bin/npm <----- active
	pnpm: 7.29.0 - ~/.nvm/versions/node/v18.19.1/bin/pnpm
Browsers:
	Safari: 17.2.1
npmPackages:
	@storybook/components: ^8.0.2 => 8.0.2 
	@storybook/manager-api: ^8.0.2 => 8.0.2 
	@storybook/preview-api: ^8.0.2 => 8.0.2 
	@storybook/react: ^8.0.2 => 8.0.2 
	@storybook/react-vite: ^8.0.2 => 8.0.2 
	@storybook/react-webpack5: ^8.0.2 => 8.0.2 
	@storybook/theming: ^8.0.2 => 8.0.2 
	@storybook/types: ^8.0.2 => 8.0.2 
	storybook: ^8.0.2 => 8.0.2
```

---

2024-04-05: _Updated the example to use the right import - it was just a bug in the example and not in the real code._

**Comment by floriangosse** [comment]
@mnigh, you're right. The example imports the wrong thing. But this is just a bug in my example. In the real code I'm using `useParameter`.

**Comment by floriangosse** [comment]
Thanks for the update. I've worked around the problem – but I might change it back and override the behaviour.

**Comment by lencioni** [comment]
> you can choose to override it with [channelOptions.allowFunction](https://storybook.js.org/docs/api/main-config/main-config-core#channeloptionsallowfunction).

It looks like the `allowFunction` was removed here https://github.com/storybookjs/storybook/pull/30998 as part of the v9 release.
