### ISSUE TITLE
[Documentation]: Missing Vue documentation for Doc Blocks

### ISSUE THREAD

**Issue by Nabil-MEDIOUNI** [storybookjs/storybook#26630]
### Describe the problem

Hi there,

I've noticed that many examples in the Vue documentation are written in React instead of Vue, which can be confusing for users like me who are specifically looking for Vue examples.

I've attached a screenshot for reference. Could someone please guide me on how to render blocks in Vue, as the examples provided are in React?

Thank you for your attention to this matter.

### Additional context

![code](https://github.com/storybookjs/storybook/assets/54674189/3cccb718-2301-42ed-96cb-279fc7a013d5)

**Comment by shilman** [comment]
Storybook Docs is implemented in React, so this is the correct way to use doc blocks in Storybook for any framework including Vue. Please let us how we can better clarify that!

**Comment by Nabil-MEDIOUNI** [comment]
hello @shilman 

Let's consider this simple example:

Code:

<img width="197" alt="image" src="https://github.com/storybookjs/storybook/assets/54674189/3e4069ce-c885-4119-8a73-bd2be248d0e9">

Result:

<img width="960" alt="image" src="https://github.com/storybookjs/storybook/assets/54674189/8910738d-acbc-45a3-ab02-65569e3d0413">


Code:

<img width="168" alt="image" src="https://github.com/storybookjs/storybook/assets/54674189/36086cd6-fc19-4fac-8d3c-a49c0a5bd8b2">

Result:

<img width="960" alt="image" src="https://github.com/storybookjs/storybook/assets/54674189/8eb8b5f9-8d20-4d1e-9519-2bbbc22e9d2c">


Unfortunately, this approach doesn't work because the preview file is not .jsx, and I'm unable to change the file type since I'm using Vue. 

I attempted to import a Vue component and use a similar approach as I do for decorators on **line 43**, but I encountered either an empty docs div or the error shown in the screenshot below:

<img width="703" alt="image" src="https://github.com/storybookjs/storybook/assets/54674189/64f6b231-9866-4eaf-9030-1861d116ddf6">

**Comment by shilman** [comment]
@Nabil-MEDIOUNI Storybook docs are implemented in React, so you need to extend them using React components, even in your Vue projects. If you want to add Vue components you'll need to use https://github.com/devilwjp/veaury or something similar. This is a shortcoming of the current docs implementation.
