### ISSUE TITLE
Automigration for adding VTA on upgrade

### ISSUE THREAD

**Issue by vanessayuenn** [storybookjs/storybook#26665]
When a user upgrades to Storybook 8, an automigration should run to add `addon-visual-tests` for them. 
- It should explain the addon and what they will be opting into (text discussed below)
- It should only run if beforeVersion is `< 8.0.x` where x is the version we release this in

We want to ship this on **Tuesday April 9**.

**Comment by shilman** [comment]
> **Visual Tests addon**
> The Visual Tests addon lets you catch UI bugs faster and more easily than ever before. The addon brings Chromatic, the visual testing cloud service developed by Storybook maintainers, into Storybook for the very first time.
> At the click of a button, you can test all your stories simultaneously, compare each one to previous versions, and pinpoint any visual changes. Then, filter your Storybook sidebar to only see stories containing visual differences and verify those changes one by one.
> Learn more: https://storybook.js.org/blog/visual-tests-addon-beta/
> Would you like us to install Visual Tests addon into your project? [Y]/n

**Comment by shilman** [comment]
@joevaugh4n I like the tone of this better, but it assumes that the reader knows what visual testing is. Can you please add a sentence to clarify? Thanks!
