### ISSUE TITLE
[Bug]: Unable to Use Tailwind CSS classes Available Breakpoints in Storybook Components in a Remix Project

### ISSUE THREAD

**Issue by Pattawine** [storybookjs/storybook#26706]
### Describe the bug

Steps to reproduce the issue
1. Install and Set up a Project Remix V2
2. Install Tailwind CSS in Remix Project 
I experimented with adding the Available breakpoints class, for example "md:hidden ", I found that it worked fine. When running on Remix
I want to install storybook into Remix and Tailwind.css.

***3. After installing Storybook, I encountered an issue can't use the Available breakpoints class, such as "md:hidden". How can I resolve this problem?

```
import { NavLink } from '@remix-run/react'

{/* can't use the Available breakpoints class when install storybook */}
<NavLink to="#" className="md:hidden">Test hidden</NavLink> 
``` 

### To Reproduce

Run Storybook and notice that the  still appears in the Storybook, and the hidden command does not work even when using a desktop screen.

### System

```bash
System:
    OS: macOS 14.3.1
    CPU: (8) arm64 Apple M2
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.1 - /usr/local/bin/node
    npm: 10.2.4 - /usr/local/bin/npm <----- active
  Browsers:
    Chrome: 123.0.6312.87
    Safari: 17.3.1
  npmPackages:
    @storybook/addon-essentials: ^8.0.5 => 8.0.5 
    @storybook/addon-interactions: ^8.0.5 => 8.0.5 
    @storybook/addon-links: ^8.0.5 => 8.0.5 
    @storybook/addon-onboarding: ^8.0.5 => 8.0.5 
    @storybook/addon-styling-webpack: ^1.0.0 => 1.0.0 
    @storybook/blocks: ^8.0.5 => 8.0.5 
    @storybook/react: ^8.0.5 => 8.0.5 
    @storybook/react-vite: ^8.0.5 => 8.0.5 
    @storybook/test: ^8.0.5 => 8.0.5 
    eslint-plugin-storybook: ^0.8.0 => 0.8.0 
    storybook: ^8.0.5 => 8.0.5
```

**Comment by MrDalo** [comment]
I have the same issue with Storybook + React but I can't find solution for that 😥

**Comment by MrDalo** [comment]
> ### Describe the bug
> Steps to reproduce the issue
> 
> 1. Install and Set up a Project Remix V2
> 2. Install Tailwind CSS in Remix Project
>    I experimented with adding the Available breakpoints class, for example "md:hidden ", I found that it worked fine. When running on Remix
>    I want to install storybook into Remix and Tailwind.css.
> 
> ***3. After installing Storybook, I encountered an issue can't use the Available breakpoints class, such as "md:hidden". How can I resolve this problem?
> 
> ```
> import { NavLink } from '@remix-run/react'
> 
> {/* can't use the Available breakpoints class when install storybook */}
> <NavLink to="#" className="md:hidden">Test hidden</NavLink> 
> ```
> 
> ### To Reproduce
> Run Storybook and notice that the still appears in the Storybook, and the hidden command does not work even when using a desktop screen.
> 
> ### System
> ```shell
> System:
>     OS: macOS 14.3.1
>     CPU: (8) arm64 Apple M2
>     Shell: 5.9 - /bin/zsh
>   Binaries:
>     Node: 20.11.1 - /usr/local/bin/node
>     npm: 10.2.4 - /usr/local/bin/npm <----- active
>   Browsers:
>     Chrome: 123.0.6312.87
>     Safari: 17.3.1
>   npmPackages:
>     @storybook/addon-essentials: ^8.0.5 => 8.0.5 
>     @storybook/addon-interactions: ^8.0.5 => 8.0.5 
>     @storybook/addon-links: ^8.0.5 => 8.0.5 
>     @storybook/addon-onboarding: ^8.0.5 => 8.0.5 
>     @storybook/addon-styling-webpack: ^1.0.0 => 1.0.0 
>     @storybook/blocks: ^8.0.5 => 8.0.5 
>     @storybook/react: ^8.0.5 => 8.0.5 
>     @storybook/react-vite: ^8.0.5 => 8.0.5 
>     @storybook/test: ^8.0.5 => 8.0.5 
>     eslint-plugin-storybook: ^0.8.0 => 0.8.0 
>     storybook: ^8.0.5 => 8.0.5
> ```
> 
> ### Additional context
> _No response_

In my case I found the solution. In `tailwind.config.ts` I have wrong scope for the project in the `content` field of the `config` object.
This is my code:
`import type { Config } from 'tailwindcss'

const config = {
  darkMode: ['class'],
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  prefix: '',
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: {
        '2xl': '1400px',
      },
    },
    extend: {
      colors: {
        border: 'rgb(var(--border) / <alpha-value>)',
        input: 'rgb(var(--input) / <alpha-value>)',
        ring: 'rgb(var(--ring) / <alpha-value>)',
        background: 'rgb(var(--background) / <alpha-value>)',
        foreground: 'rgb(var(--foreground) / <alpha-value>)',
        primary: {
          DEFAULT: 'rgb(var(--primary) / <alpha-value>)',
          foreground: 'rgb(var(--primary-foreground) / <alpha-value>)',
        },
        secondary: {
          DEFAULT: 'rgb(var(--secondary) / <alpha-value>)',
          foreground: 'rgb(var(--secondary-foreground) / <alpha-value>)',
        },
        destructive: {
          DEFAULT: 'rgb(var(--destructive) / <alpha-value>)',
          foreground: 'rgb(var(--destructive-foreground) / <alpha-value>)',
        },
        muted: {
          DEFAULT: 'rgb(var(--muted) / <alpha-value>)',
          foreground: 'rgb(var(--muted-foreground) / <alpha-value>)',
        },
        accent: {
          DEFAULT: 'rgb(var(--accent) / <alpha-value>)',
          foreground: 'rgb(var(--accent-foreground) / <alpha-value>)',
        },
        popover: {
          DEFAULT: 'rgb(var(--popover) / <alpha-value>)',
          foreground: 'rgb(var(--popover-foreground) / <alpha-value>)',
        },
        card: {
          DEFAULT: 'rgb(var(--card) / <alpha-value>)',
          foreground: 'rgb(var(--card-foreground) / <alpha-value>)',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
        shimmer: {
          '100%': {
            transform: 'translateX(100%)',
          },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
} satisfies Config

export default config
`

**Comment by Pattawine** [comment]
> I have the same issue with Storybook + React but I can't find solution for that 😥

I encountered an issue when using md:hidden and above screen sizes. When I apply the md:hidden class to hide an element on medium screens and above, the element is hidden as expected. However, other Tailwind CSS classes work fine. Please help me with this issue.

**Comment by Pattawine** [comment]
> > ### Describe the bug
> > Steps to reproduce the issue
> > 
> > 1. Install and Set up a Project Remix V2
> > 2. Install Tailwind CSS in Remix Project
> >    I experimented with adding the Available breakpoints class, for example "md:hidden ", I found that it worked fine. When running on Remix
> >    I want to install storybook into Remix and Tailwind.css.
> > 
> > ***3. After installing Storybook, I encountered an issue can't use the Available breakpoints class, such as "md:hidden". How can I resolve this problem?
> > ```
> > import { NavLink } from '@remix-run/react'
> > 
> > {/* can't use the Available breakpoints class when install storybook */}
> > <NavLink to="#" className="md:hidden">Test hidden</NavLink> 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### To Reproduce
> > Run Storybook and notice that the still appears in the Storybook, and the hidden command does not work even when using a desktop screen.
> > ### System
> > ```shell
> > System:
> >     OS: macOS 14.3.1
> >     CPU: (8) arm64 Apple M2
> >     Shell: 5.9 - /bin/zsh
> >   Binaries:
> >     Node: 20.11.1 - /usr/local/bin/node
> >     npm: 10.2.4 - /usr/local/bin/npm <----- active
> >   Browsers:
> >     Chrome: 123.0.6312.87
> >     Safari: 17.3.1
> >   npmPackages:
> >     @storybook/addon-essentials: ^8.0.5 => 8.0.5 
> >     @storybook/addon-interactions: ^8.0.5 => 8.0.5 
> >     @storybook/addon-links: ^8.0.5 => 8.0.5 
> >     @storybook/addon-onboarding: ^8.0.5 => 8.0.5 
> >     @storybook/addon-styling-webpack: ^1.0.0 => 1.0.0 
> >     @storybook/blocks: ^8.0.5 => 8.0.5 
> >     @storybook/react: ^8.0.5 => 8.0.5 
> >     @storybook/react-vite: ^8.0.5 => 8.0.5 
> >     @storybook/test: ^8.0.5 => 8.0.5 
> >     eslint-plugin-storybook: ^0.8.0 => 0.8.0 
> >     storybook: ^8.0.5 => 8.0.5
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Additional context
> > _No response_
> 
> In my case I found the solution. In `tailwind.config.ts` I have wrong scope for the project in the `content` field of the `config` object. This is my code:
> 
> ```ts
> import type { Config } from 'tailwindcss'
> 
> const config = {
>   darkMode: ['class'],
>   content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
>   prefix: '',
>   theme: {
>     container: {
>       center: true,
>       padding: '2rem',
>       screens: {
>         '2xl': '1400px',
>       },
>     },
>     extend: {
>       colors: {
>         border: 'rgb(var(--border) / <alpha-value>)',
>         input: 'rgb(var(--input) / <alpha-value>)',
>       },
>       borderRadius: {
>         lg: 'var(--radius)',
>         md: 'calc(var(--radius) - 2px)',
>         sm: 'calc(var(--radius) - 4px)',
>       },
>       keyframes: {
>         'accordion-down': {
>           from: { height: '0' },
>           to: { height: 'var(--radix-accordion-content-height)' },
>         },
>         'accordion-up': {
>           from: { height: 'var(--radix-accordion-content-height)' },
>           to: { height: '0' },
>         },
>         shimmer: {
>           '100%': {
>             transform: 'translateX(100%)',
>           },
>         },
>       },
>       animation: {
>         'accordion-down': 'accordion-down 0.2s ease-out',
>         'accordion-up': 'accordion-up 0.2s ease-out',
>       },
>     },
>   },
>   plugins: [require('tailwindcss-animate')],
> } satisfies Config
> 
> export default config
> ```

**Comment by Pattawine** [comment]
> I have the same issue with Storybook + React but I can't find solution for that 😥



> I have the same issue with Storybook + React but I can't find solution for that 😥

Thank you, I found that this issue arises because the tailwind.config.ts features were not described in the content field of the config.

I changed my content to be like this: content: ['./stories/**/*.{js,jsx,ts,tsx}'] and now it works.
