### ISSUE TITLE
[Bug]: Fresh install of 8.0.6 doesn't launch onboarding

### ISSUE THREAD

**Issue by kahlan88** [storybookjs/storybook#26784]
### Describe the bug

I installed a fresh install using the automatic command: `npx storybook@latest init --type=preact` and choosing Vite.

The install proceeds fine and launches Storybook but according to docs, it should launch onboarding. It just launches Storybook but not the onboarding pop up. 

I tried going to `?path=/onboarding` as suggested but it doesn't do anything.

I've not made any changes to the project since install and I still have all the sample stories.

### To Reproduce

Install using `npx storybook@latest init --type=preact` and choose Vite.
Observe the Storybook window that loads.
(No onboarding, it loads `http://localhost:6006/?path=/docs/configure-your-project--docs`)

Go to `?path=/onboarding` i.e. `http://localhost:6006/?path=/onboarding`
(Empty screen with all stories closed but no onboarding)

### System

```bash
Storybook Environment Info:

  System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i7-1265U
  Binaries:
    Node: 20.11.1 - ~\AppData\Roaming\nvm\v20.11.1\node.EXE
    npm: 10.2.4 - ~\AppData\Roaming\nvm\v20.11.1\npm.CMD <----- active
  Browsers:
    Edge: Chromium (123.0.2420.81)
  npmPackages:
    @storybook/addon-essentials: ^8.0.6 => 8.0.6
    @storybook/addon-interactions: ^8.0.6 => 8.0.6
    @storybook/addon-links: ^8.0.6 => 8.0.6
    @storybook/blocks: ^8.0.6 => 8.0.6
    @storybook/preact: ^8.0.6 => 8.0.6
    @storybook/preact-vite: ^8.0.6 => 8.0.6
    @storybook/test: ^8.0.6 => 8.0.6
    storybook: ^8.0.6 => 8.0.6
```
```


### Additional context

_No response_

**Comment by valentinpalkovic** [comment]
The onboarding only works for react projects so far. Since you are initializing it for a preact project, it doesn’t get installed and triggered. @jonniebigodes Can you check, whether we communicate this accordingly?

**Comment by jonniebigodes** [comment]
@valentinpalkovic I've checked, and the documentation is accurate and is only showing up for React as shown below:

https://github.com/storybookjs/storybook/assets/22988955/2660c854-da1c-45ee-9959-da371795b02b

@kahlan88, as the video shows, the Setup Wizard section (i.e., onboarding) will be shown to you when selecting React from the framework selector and not when Preact is selected. Also, by looking at the information you provided in the description, which results from running the Storybook CLI with the `info` flag (i.e., `npx storybook@latest info`), the onboarding addon isn't included. This leads to the behavior you've described when adding the query param to your local Storybook instance. 

Hopefully, we'll get around this and make the onboarding addon available to other frameworks as well, and with that, the documentation will be updated accordingly. Until then, bear with us and be a little patient. The team is working on some other features and improvements to make Storybook even better. Once we have the onboarding experience ready for the different frameworks, we will announce it. Stay tuned!


Hope you have a great day.

Stay safe.
