### ISSUE TITLE
Babel Configuration Not Applied to Storybook Stories[Bug]: 

### ISSUE THREAD

**Issue by krzysztofpniak** [storybookjs/storybook#26798]
### Describe the bug

In the Storybook, it appears that the Babel configuration is not being applied to stories.jsx files. My components compile as expected when I use pipeline operator. Only files with "stories.jsx" suffix produce error. This leads to unexpected behavior and inconsistencies in the rendering of components within Storybook stories. In my case I get 
`SyntaxError: This experimental syntax requires enabling the parser plugin: "pipelineOperator".`
even if I have: `"@babel/plugin-proposal-pipeline-operator"` in my `babel.config.js` file.

### To Reproduce

test.stories.js content:
```
import React from 'react';

const Test = () => {
  'Hello' |> console.log;

  return <div>test</div>;
};

export default {
  title: 'Test',
  component: Test,
};

export const Basic = {};
```

### System

```bash
mac os
```

**Comment by valentinpalkovic** [comment]
Hi @krzysztofpniak 

can you provide the error stacktrace?
