### ISSUE TITLE
[Bug]: Cannot read properties of undefined (reading 'fonts')

### ISSUE THREAD

**Issue by unional** [storybookjs/storybook#26820]
### Describe the bug

When using `Source` component in `@storybook/blocks`.

### To Reproduce

not available yet.

### System

```bash
Storybook Environment Info:

  System:
    OS: macOS 14.4.1
    CPU: (10) arm64 Apple M1 Pro
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
    npm: 10.5.0 - ~/.nvm/versions/node/v20.12.2/bin/npm
    pnpm: 8.13.1 - ~/.nvm/versions/node/v20.12.2/bin/pnpm <----- active
  Browsers:
    Chrome: 123.0.6312.107
    Safari: 17.4.1
  npmPackages:
    @storybook/addon-essentials: ^8.0.8 => 8.0.8 
    @storybook/addon-interactions: ^8.0.8 => 8.0.8 
    @storybook/addon-links: ^8.0.8 => 8.0.8 
    @storybook/addon-storysource: ^8.0.8 => 8.0.8 
    @storybook/blocks: ^8.0.8 => 8.0.8 
    @storybook/manager-api: ^8.0.8 => 8.0.8 
    @storybook/react: ^8.0.8 => 8.0.8 
    @storybook/react-vite: ^8.0.8 => 8.0.8 
    @storybook/test: ^8.0.8 => 8.0.8 
    @storybook/test-runner: ^0.17.0 => 0.17.0 
    @storybook/theming: ^8.0.8 => 8.0.8 
    storybook: ^8.0.8 => 8.0.8 
    storybook-dark-mode: ^4.0.0 => 4.0.1
```

### Additional context

It's the cause by the `typography` is undefined in this line:

`convert({ ...overrideTheme, fontCode: typography.fonts.mono...`

which comes from `let { typography } = useTheme();`

I'm using tailwind, does it needs `ThemeProvider`?

**Comment by valentinpalkovic** [comment]
Hi @unional 

Thank you for reporting the issue!

Can you provide a reproduction? https://storybook.new

**Comment by grubersjoe** [comment]
Here you go: https://stackblitz.com/edit/github-rfhljl?file=src%2Fstories%2FDemo.stories.jsx

I'm facing the same issue.

**Comment by nclskfm** [comment]
We're facing the same issue when using the `Markdown` component to include an md file in our MDX file, e.g.

```mdx
import { Meta, Markdown } from '@storybook/blocks';
import Changelog from '../../../CHANGELOG.md?raw';

<Meta title="Changelog" />

# Changelog

<Markdown>
  {Changelog} 
</Markdown>
```

<details><summary>Error</summary>
<p>

```
Cannot read properties of undefined (reading 'fonts')
TypeError: Cannot read properties of undefined (reading 'fonts')
    at withReset (http://localhost:4400/vendors-node_modules_storybook_blocks_dist_index_mjs.iframe.bundle.js:16557:34)
    at handleInterpolation (http://localhost:4400/vendors-node_modules_storybook_blocks_dist_index_mjs.iframe.bundle.js:21705:22)
    at serializeStyles (http://localhost:4400/vendors-node_modules_storybook_blocks_dist_index_mjs.iframe.bundle.js:21761:77)
```

</p>
</details>

**Comment by audunolsen** [comment]
+1, 

```
"storybook": "8.0.8",
"@storybook/blocks": "8.0.8",
"@storybook/manager-api": "8.0.8",
"@storybook/preview-api": "8.0.8",
"@storybook/react-vite": "8.0.8",
```

**Comment by audunolsen** [comment]
Happens in the stackblitz react/ts/vite template when adding a codeblock inside a markdown component from `@storybook/blocks`

<img width="1327" alt="Screenshot 2024-04-22 at 12 58 40" src="https://github.com/storybookjs/storybook/assets/16224137/52df7a2d-e26b-4544-abb2-79fbda90a763">

**Comment by grubersjoe** [comment]
The reproduction was using the v8.1 alpha (by default). I changed it to use v8.0.x but Stackblitz is unable to save the changes, so it's broken right now, unfortunately. Let's hope Stackblitz will work again soon....

Anyway: this issue is really simple to reproduce. Just render `<Source />` with any content:

```tsx
import { Source } from '@storybook/blocks';

<Source code="broken" />
```

**Comment by levino** [comment]
I can produce quite nicely locally since I cannot use `<Canvas>` in my app. I just thought to highlight this issue to the maintainers so they can remove the "needs repro" tag. I fear as long as this tag is there, this will not be fixed.

**Comment by yoavniran** [comment]
getting the same error when trying to show the package's README.MD as part of the autogen doc.
This used to work prior to upgrading from a 7.x. to 8.1.1

my story file imports the README:

```js
import readme from "./README.md";

```

and (default) exports: 

```js
...
 parameters: {
  docs: {
                description: { component: readme },
            },
   }
...
```

In main.ts, I've tried configuring: 

```ts
addons: [
       "@storybook/addon-links",
        "@storybook/addon-essentials",
        "@storybook/addon-interactions",
        {
            name: "@storybook/addon-docs",
            options: {
                mdxPluginOptions: {
                    mdxCompileOptions: {
                        remarkPlugins: [remarkGfm],
                    },
                },
            }
        },
        "@storybook/addon-webpack5-compiler-babel"
    ],
```

But no luck.

If I simplify my README to just plain text it does work. But any type of "special" element like link, table, code, etc. breaks with the same: `Cannot read properties of undefined (reading 'size')`

**Comment by devilkiller-ag** [comment]
Hi I am creating a Color Pallete for my design System:
```
/* eslint-disable import/no-extraneous-dependencies */
import { ColorItem, ColorPalette } from '@storybook/blocks';
import type { Meta } from '@storybook/react';

const meta: Meta = {
  title: 'Design Tokens/Colors',
  component: ColorPalette
};

export default meta;

export const Colors = () => (
  <>
    <ColorPalette>
      <ColorItem
        title='Primary'
        subtitle='This is the primary color palette across all products.'
        colors={{
          50: '#efe6fd',
          100: '#ceb0fa',
          200: '#b78af7',
          300: '#9654f4',
          400: '#8133f1',
          500: '#6200ee',
          600: '#5900d9',
          700: '#4600a9',
          800: '#360083',
          900: '#290064'
        }}
      />
    </ColorPalette>
  </>
);
```
I don't know why I am getting this error on the storybook page for the color: 
```
 Error: Cannot read properties of undefined (reading 'fonts')
  at handleInterpolation (/vendors-node_modules_pmmmwh_react-refresh-webpack-plugin_client_ReactRefreshEntry_js-node_mod-42ab01.iframe.bundle.js:17016:3193))
  at serializeStyles (/vendors-node_modules_pmmmwh_react-refresh-webpack-plugin_client_ReactRefreshEntry_js-node_mod-42ab01.iframe.bundle.js:17021:1660))
  at /vendors-node_modules_pmmmwh_react-refresh-webpack-plugin_client_ReactRefreshEntry_js-node_mod-42ab01.iframe.bundle.js:17026:1410
  at /vendors-node_modules_pmmmwh_react-refresh-webpack-plugin_client_ReactRefreshEntry_js-node_mod-42ab01.iframe.bundle.js:17021:3015
  at renderWithHooks (/vendors-node_modules_pmmmwh_react-refresh-webpack-plugin_client_ReactRefreshEntry_js-node_mod-42ab01.iframe.bundle.js:63071:18))
  at updateForwardRef (/vendors-node_modules_pmmmwh_react-refresh-webpack-plugin_client_ReactRefreshEntry_js-node_mod-42ab01.iframe.bundle.js:67736:20))
  at beginWork$1 (/vendors-node_modules_pmmmwh_react-refresh-webpack-plugin_client_ReactRefreshEntry_js-node_mod-42ab01.iframe.bundle.js:70495:16))
  at beginWork (/vendors-node_modules_pmmmwh_react-refresh-webpack-plugin_client_ReactRefreshEntry_js-node_mod-42ab01.iframe.bundle.js:78841:14))
  at performUnitOfWork (/vendors-node_modules_pmmmwh_react-refresh-webpack-plugin_client_ReactRefreshEntry_js-node_mod-42ab01.iframe.bundle.js:77687:12))
```
This error seems similar to all the above ones. Additionally here is my .storybook/maint.ts file: 
```
import type { StorybookConfig } from "@storybook/nextjs";

const config: StorybookConfig = {
  stories: [
    "../components/**/*.stories.mdx",
    "../components/**/*.stories.@(js|jsx|mjs|ts|tsx)",
  ],
  addons: [
    "@storybook/addon-onboarding",
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@chromatic-com/storybook",
    "@storybook/addon-interactions",
  ],
  docs: {
    defaultName: 'Documentation',
  },
  framework: {
    name: "@storybook/nextjs",
    options: {},
  },
  staticDirs: ["..\\public"],
};
export default config;
```

Kindly resolve this bug as soon as possible. This is a part of my Google Summer of Code project and I don't want to lack behind my proposed timeline. Thank You. Also let me know if this bug is not what this thread is discussing or you have any possible solution.

**Comment by shilman** [comment]
Doc blocks are not meant to be used in stories. They require a context provider that is only passed on Docs pages and MDX pages.

**Comment by grubersjoe** [comment]
Interesting, thanks for clarifying! That was not obvious to me. In this case I'll just use a 3rd party component to highlight code.

Since several people seem to run into this issue maybe there could be an error message pointing out that the block components are meant to only be used on docs pages.

**Comment by yoavniran** [comment]
> Doc blocks are not meant to be used in stories. They require a context provider that is only passed on Docs pages and MDX pages.

@shilman its unclear who/what you're addressing in your response. There's more than one use case described in posts in this thread.

for my use-case: showing the readme.md alongside the story - should that be possible or not? As mentioned, it seems to work for very simple .MD files but not for anything with non-text elements

**Comment by shilman** [comment]
@yoavniran I was addressing anybody who is trying to use doc blocks in their stories.

For the markdown problem, please open a new issue with a reproduction and I'd be happy to take a look.

**Comment by unional** [comment]
Using `Source` in MDX file is working in 8.1.7 now. thx.

**Comment by dmy-leanix** [comment]
8.1.11 error seems to be returned

**Comment by JoelDSmith** [comment]
Saw this today on 8.3.6 - the workaround over here helped: https://github.com/storybookjs/storybook/issues/29313#issuecomment-2403915357

**Comment by smoglica** [comment]
Another workaround that I found is overriding `code` HTML tag through `<Markdown />` component options

```jsx
import content from './content.mdx?raw';

<Markdown
  options={{
    overrides: {
      code: {
        component: ({ children }) => <code>{children}</code>,
      },
    },
  }}
>
  {content}
</Markdown>
```

**Comment by noahnu** [comment]
Note that this error can happen if you have multiple versions of storybook installed, for example via Yarn PnP virtual dependencies. Deduping those dependencies resolves the issue.

**Comment by toppsdown** [comment]
I'm new to storybook and I'm trying to get dark mode working. It's been a huge PITA to do something that I thought was going to be a 10 min setup. After 2 hours I'm now stuck here. 

Docs don't respect the theme so I'm trying to use the workaround described [here](https://github.com/storybookjs/storybook/discussions/28495#discussioncomment-11184489), but it's causing this fonts error.

**Comment by unional** [comment]
add the theme context provider to the story/decorator

**Comment by toppsdown** [comment]
@unional Finally got it figured, there were two issues:

1. The theme used by the theme provider, and the one used by the DocsContainer are different types. The docs container is supposed to [automatically convert them](https://github.com/storybookjs/storybook/blob/next/code/addons/docs/src/blocks/blocks/DocsContainer.tsx#L59), but for whatever reason it's not working.
2. I was putting the theme provider in the stories/decorators, but it needs to be outside the DocsContainer.


Code:
```ts
docs: {
      //
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      container: (props: any) => {
        const el = document.querySelector("html")
        const theme =
          props?.context.store.userGlobals.globals.theme === "dark"
            ? darkTheme
            : lightTheme
        el!.dataset["theme"] =
          props?.context.store.userGlobals.globals.theme
        const newProps = { ...props, theme }
        return (
          <ThemeProvider theme={convert(theme)}>
            <DocsContainer {...newProps}>{newProps.children}</DocsContainer>
          </ThemeProvider>
        )
      },
    },
```

**Comment by mrginglymus** [comment]
necroposting this one for future travellers - I hit this problem, and whilst I'm struggling to create a minimal repro the problem was that I had two copies of `@storybook/addon-docs/blocks`. I suspect this is because the adding that was overriding `container` was importing from `@storybook/addon-docs/blocks`, but the addon itself was registered with `path.dirname(import.meta.resolve('@storybook/addon-docs/blocks/package.json'))`, which may get vite a bit confused as to what's the same as the other.
