### ISSUE TITLE
[Bug]: `useParams` returns null in NextJS 14.2. Storybook 7 & 8

### ISSUE THREAD

**Issue by RickyRoller** [storybookjs/storybook#26850]
### Describe the bug

When using the `useParams` hook in stories, an error will occur saying that the output of `useParams` is null.
This is happening with version 14.2 of NextJS and is possibly related to this PR which was included in the release https://github.com/vercel/next.js/pull/60708

I've tried in both Storybook 7 and Storybook 8 and the bug is present in both.

### To Reproduce

Here is a repo with an example https://github.com/RickyRoller/next-storybook-useparams
I forked another repo that was used for a similar issue.

### System

```bash
System:
    OS: macOS 14.1.1
    CPU: (10) arm64 Apple M1 Pro
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 10.5.0 - ~/.nvm/versions/node/v20.12.2/bin/npm <----- active
  Browsers:
    Chrome: 123.0.6312.123
    Safari: 17.1
  npmPackages:
    @storybook/addon-essentials: ^8.0.2 => 8.0.2 
    @storybook/addon-interactions: ^8.0.2 => 8.0.2 
    @storybook/addon-links: ^8.0.2 => 8.0.2 
    @storybook/addon-onboarding: ^8.0.2 => 8.0.2 
    @storybook/blocks: ^8.0.2 => 8.0.2 
    @storybook/nextjs: ^8.0.2 => 8.0.2 
    @storybook/react: ^8.0.2 => 8.0.2 
    @storybook/test: ^8.0.2 => 8.0.2 
    eslint-plugin-storybook: ^0.8.0 => 0.8.0 
    storybook: ^8.0.2 => 8.0.2
```

**Comment by yannbf** [comment]
Hey @RickyRoller thank you so much for reporting and your incredible description + repro. I'm on top of it, will get this soon in a patch release!

**Comment by RickyRoller** [comment]
> Hey @RickyRoller thank you so much for reporting and your incredible description + repro. I'm on top of it, will get this soon in a patch release!

Thank you! Much appreciated
