### ISSUE TITLE
[Bug]: Storybook doesn't run with tailwindcss in next.js

### ISSUE THREAD

**Issue by algoORgoal** [storybookjs/storybook#26869]
### Describe the bug

Describe the bug
1. I have a default next.js setup
2. To apply tailwind to Storybook, I followed [the official docs](https://storybook.js.org/recipes/tailwindcss)
3. Tailwindcss has applied to my next.js app when I run `yarn dev` but not to the stories when I run `yarn storybook`.
4. I did some experiments and these results came out:
  - Storybook picks up tailwindcss in these cases.
    1. There is only `postcss.config.js` in the project(root directory)
    2. There are both `postcss.config.mjs` and `postcss.config.js` in the project(root directory)
  
  - Storybook doesn't pick up tailwindcss in this case.
    1. There is only `postcss.config.mjs` in the project

### To Reproduce

You can clone this repo and run yarn storybook

*Make sure to remove `postcss.cofnig.mjs` to see the failure.*

https://github.com/algoORgoal/bug-storybook-tailwindcss

### System

```bash
Storybook Environment Info:

  System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
  Binaries:
    Node: 20.12.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - ~\AppData\Roaming\npm\yarn.CMD <----- active
    npm: 10.5.2 - ~\AppData\Roaming\npm\npm.CMD
  Browsers:
    Chrome: 123.0.6312.123
    Edge: Chromium (123.0.2420.97)      
  npmPackages:
    @storybook/addon-coverage: ^1.0.1 => 1.0.1
    @storybook/addon-essentials: ^8.0.8 => 8.0.8
    @storybook/addon-interactions: ^8.0.8 => 8.0.8
    @storybook/addon-links: ^8.0.8 => 8.0.8
    @storybook/addon-onboarding: ^8.0.8 => 8.0.8
    @storybook/blocks: ^8.0.8 => 8.0.8  
    @storybook/nextjs: ^8.0.8 => 8.0.8  
.17.0
    eslint-plugin-storybook: ^0.8.0 => 0.8.0
    msw-storybook-addon: ^2.0.0-beta.2 => 2.0.0-beta.2
    storybook: ^8.0.8 => 8.0.8
```

### Additional context

"postcss": "8.4.38",
"storybook": "8.0.8",
"tailwindcss": "3.4.1",
"next": "14.2.1",

**Comment by drianoaz** [comment]
I have the same problem. 

A workaround to fix it is change the extensions of files `postcss.config` and `tailwind.config` to `.cjs`. Must be include too a `**/*.cjs` at your `tsconfig.json` as this example.

This is working, but I don't know why.

<img width="385" alt="image" src="https://github.com/storybookjs/storybook/assets/15058771/7deeda86-ad80-46f0-8ac0-939580dbe869">

**Comment by algoORgoal** [comment]
> I have the same problem.
> 
> A workaround to fix it is change the extensions of files `postcss.config` and `tailwind.config` to `.cjs`. Must be include too a `**/*.cjs` at your `tsconfig.json` as this example.
> 
> ~This is working, but I don't know why.~
> 
> <img alt="image" width="385" src="https://private-user-images.githubusercontent.com/15058771/323652333-7deeda86-ad80-46f0-8ac0-939580dbe869.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3MjIwMDQsIm5iZiI6MTcxMzcyMTcwNCwicGF0aCI6Ii8xNTA1ODc3MS8zMjM2NTIzMzMtN2RlZWRhODYtYWQ4MC00NmYwLThhYzAtOTM5NTgwZGJlODY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDE3NDgyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlNDk2MDAyYTFjZTdmMDNiYjM3Y2YzZDg5ZTI0ZmRjY2I5ODhhNzVkMzNmZjU5Nzg2Y2U3NTIyNWI4YmMxODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.k7_ScKLdPKnPaAhHMfYCvvduhuFJmz4xH7dALuJ2rW0">
> ## Why it works?
> Under the hood, `@storybook/nextjs` uses [postcss-loader](https://www.npmjs.com/package/postcss-loader)
> 
> https://github.com/storybookjs/storybook/blob/67a21117d31991758175790f37fc4ea1cc5ea22f/code/frameworks/nextjs/src/css/webpack.ts#L35
> 
> The file `postcss.config.mjs` is not a valid [config file](https://github.com/webpack-contrib/postcss-loader?tab=readme-ov-file#config-files) for this loader
> 
> <img alt="image" width="823" src="https://private-user-images.githubusercontent.com/15058771/323664651-6298423f-cbf0-4002-8aae-dd1237a9a07a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3MjIwMDQsIm5iZiI6MTcxMzcyMTcwNCwicGF0aCI6Ii8xNTA1ODc3MS8zMjM2NjQ2NTEtNjI5ODQyM2YtY2JmMC00MDAyLThhYWUtZGQxMjM3YTlhMDdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDE3NDgyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyOGJmNGRmYzIzZmY2YTY3Yjg4MjdlN2ZiNTIzNTc5ZWRmMTlmMjMxYzQ3N2M1YjNjZTAxZmQzNzdjOTA2ZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UNfWhBsQz9g82bT2yJvI0IQhsQIJBK_6r2qyoaU0lXU">

Wow, thank you so much! I think it would have been better if it was documented somewhere. Maintainers, please let us know if pull requests are welcomed :)

**Comment by travhow99** [comment]
> I have the same problem.
> 
> A workaround to fix it is change the extensions of files `postcss.config` and `tailwind.config` to `.cjs`. Must be include too a `**/*.cjs` at your `tsconfig.json` as this example.
> 
> ~This is working, but I don't know why.~
> 
> <img alt="image" width="385" src="https://private-user-images.githubusercontent.com/15058771/323652333-7deeda86-ad80-46f0-8ac0-939580dbe869.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwNTM0NjUsIm5iZiI6MTcxNDA1MzE2NSwicGF0aCI6Ii8xNTA1ODc3MS8zMjM2NTIzMzMtN2RlZWRhODYtYWQ4MC00NmYwLThhYzAtOTM5NTgwZGJlODY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDEzNTI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1OWI2YWVkY2NkMjZlZDFkODdlOTQzMTMyMThmZDE0MzA3N2ZmNjFkN2E0NjAyMjg0OTkxZDgyMWI0YmE0NDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.G56LF4el-IBAYco7CStOYTcZknPh2kDuENw-_P4fvBw">
> ## Why it works?
> Under the hood, `@storybook/nextjs` uses [postcss-loader](https://www.npmjs.com/package/postcss-loader)
> 
> https://github.com/storybookjs/storybook/blob/67a21117d31991758175790f37fc4ea1cc5ea22f/code/frameworks/nextjs/src/css/webpack.ts#L35
> 
> The file `postcss.config.mjs` is not a valid [config file](https://github.com/webpack-contrib/postcss-loader?tab=readme-ov-file#config-files) for this loader
> 
> <img alt="image" width="823" src="https://private-user-images.githubusercontent.com/15058771/323664651-6298423f-cbf0-4002-8aae-dd1237a9a07a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwNTM0NjUsIm5iZiI6MTcxNDA1MzE2NSwicGF0aCI6Ii8xNTA1ODc3MS8zMjM2NjQ2NTEtNjI5ODQyM2YtY2JmMC00MDAyLThhYWUtZGQxMjM3YTlhMDdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDEzNTI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5YWVkNGFhODU3ZWYyZTQ1ZmMzMDIwYTJiYzU3NGZjODJjMGRkM2RjYjllZGZjYTA2NjNiOTk0MGNkOTljODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bwqTKUOIWbXbqUPcEabakZVHKLMyGZnjqzEjVqnisgg">

Thank you very much for the solution @drianoaz 

Note for others - I only had to change the postcss config to `postcss.config.cjs` to get things working, and was able to leave the tailwind config as `tailwind.config.ts`

**Comment by nady90** [comment]
> Thank you! I just spent several hours trying to get tailwind to work in storybook. This did the trick.
> 
> 1. Rename file to `postcss.config.cjs`
> 2. Change export line at the bottom from `export default config;` to `module.exports = config;`
> 3. Update `tsconfig.json` to include `"**/*.cjs"` in the `include` array.
> 
> I think this framework needs an update ASAP to make this change, as the default install is completely broken without it.
> 
> `@storybook/nextjs 8.0.9. next 14.2.2. tailwindcss 3.4.3. postcss 8.4.38.`

If you are just finding this issue, do just this and it will work. A couple of hours wasted looking around until I found this lol

**Comment by Heet-Bhalodiya** [comment]
Hello everyone,

The above solution is not working for me as I am using nextjs `v14.2.3`.

is there any other solution?? Thanks!

**Comment by Heet-Bhalodiya** [comment]
Thanks @nady90, it's working now.

The issue was that I had `important: '#__next',` in my `tailwind.config.ts` file and that caused the issue.

**Comment by phukon** [comment]
> Thank you! I just spent several hours trying to get tailwind to work in storybook. This did the trick.
> 
> 1. Rename file to `postcss.config.cjs`
> 2. Change export line at the bottom from `export default config;` to `module.exports = config;`
> 3. Update `tsconfig.json` to include `"**/*.cjs"` in the `include` array.
> 
> I think this framework needs an update ASAP to make this change, as the default install is completely broken without it.
> 
> `@storybook/nextjs 8.0.9. next 14.2.2. tailwindcss 3.4.3. postcss 8.4.38.`

thank you so much! I was wondering why it wasn't working for my new nextjs project when the other projects were working fine. so many new storybook peeps are prolly pulling there hair out rn

**Comment by ethanmick** [comment]
As it stands a clean install of Next.js and Storybook results in Tailwind not working in the Storybook. The fix outline in this thread is a good workaround, but please:

1. Update the docs to clearly outline this fix
2. Update Storybook to pickup the default Next.js/Tailwind configuration files.

Thanks!

**Comment by pablohaller** [comment]
I spent the whole day trying different ways to setup storybook in my new NextJS project using Tailwind.

This workaround really made it work:

https://github.com/storybookjs/storybook/issues/26869#issuecomment-2086052901

**Comment by ArthurFakhouri** [comment]
Hey everyone, 

> > Hello everyone,
> > The above solution is not working for me as I am using nextjs `v14.2.3`.
> > is there any other solution?? Thanks!
> 
> In addition to doing the following:
> 
> 1. Rename file to `postcss.config.cjs`
> 2. Change export line at the bottom from `export default config;` to `module.exports = config;`
> 3. Update `tsconfig.json` to include `"**/*.cjs"` in the include array.
> 
> You need to change `preview.js` to import the `globals.css` file (or whatever file has your `tailwindcss` imports:
> 
> `import "../src/app/globals.css";`

This help me too much, but my styles are being override from injected styles by storybook, what can I do?

![image](https://github.com/storybookjs/storybook/assets/71707151/b0d46be3-1dfb-43ae-a59c-67a4775c20c0)

**Comment by valentinpalkovic** [comment]
https://github.com/storybookjs/storybook/pull/26707 should have fixed this issue. Can someone please upgrade to Storybook v8.1 and see if the issue is fixed?

```
npx storybook@latest upgrade
```

**Comment by tom-fletcher** [comment]
@valentinpalkovic I have just updated `storybook` and all the addons to `v8.1.3` and can confirm that for me it is now picking up and using the `postcss.config.js` file (as well as still supporting the older `.cjs` version).  👍
