### ISSUE TITLE
[Bug]: Vite builder: Indirectly exported binding name 'default' cannot be resolved by star export entries.

### ISSUE THREAD

**Issue by henrywoody** [storybookjs/storybook#26889]
### Describe the bug

I've just switched from React with Webpack5 to React with Vite as the builder and have started to encounter this error:

```
Indirectly exported binding name 'default' cannot be resolved by star export entries.
```

It shows in the preview panel of the Storybook app (no errors in the shell console) and the rest of the Storybook app works fine. From what I understand this has something to do with the interaction of CJS and ESM packages, but the error I get does not give me much information to work with. My `package.json` file does specify `"type": "module"`.

Here's the error from the browser console (not very helpful):

```
[Error] SyntaxError: Indirectly exported binding name 'default' cannot be resolved by star export entries.

	error (runtime.js:4:30619)
	renderPreviewEntryError (runtime.js:118:11740)
	renderPreviewEntryError (runtime.js:121:11621)
	(anonymous function) (runtime.js:118:6578)
```

Here is my `.storybook/main.ts` file:

```
export default {
	stories: ["../src/**/*.stories.mdx", "../src/**/*.stories.@(js|jsx|ts|tsx)", "../src/**/stories.@(js|jsx|ts|tsx)"],
	addons: [
		"@storybook/addon-links",
		"@storybook/addon-actions",
		"@storybook/addon-essentials",
		{
			name: "@storybook/addon-docs",
			options: {
				configureJSX: true,
			},
		},
		"@storybook/addon-controls",
	],
	framework: "@storybook/react-vite",
	core: {
		builder: "@storybook/builder-vite",
	},
};
```

and here is my `vite.config.ts` file:

```
import { defineConfig } from "vite";
import tsconfigPaths from "vite-tsconfig-paths";
import react from "@vitejs/plugin-react";

export default defineConfig({
	plugins: [tsconfigPaths(), react()],
});
```

### To Reproduce

I'm having trouble reproducing this outside my repo (which is private and owned by my company). I've created a fresh project and that works fine and I've copied as much of the config from the new project over to my existing repo but still no changes. I've set the stories down to a single story of a component that just renders a `<div>` and still the issue persists.

I can provide more information if needed.

### System

```bash
System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Pro
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.0 - /opt/homebrew/opt/node@20/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 10.2.4 - /opt/homebrew/opt/node@20/bin/npm <----- active
  Browsers:
    Chrome: 123.0.6312.124
    Safari: 16.4
```

**Comment by henrywoody** [comment]
Update: Seems to come from the style imports in my `.storybook/preview.ts` file:

```
import "../src/Styles";

export const parameters = {
	layout: "centered",
};
```

Where `Styles/index.ts` looks like this:

```
export { default as rootStyle } from "./root.css";
export { default as globalStyle } from "./global.css";
export { default as defaultTheme } from "./theme-default.css";
```

But I fixed the issue by updating this file to look like this:

```
export * as rootStyle from "./root.css";
export * as globalStyle from "./global.css";
export * as defaultTheme from "./theme-default.css";
```

using [this StackOverflow question](https://stackoverflow.com/q/68418259/8068625).

**Comment by Thisizzellie** [comment]
this solved it for me 

rm -rf dist node_modules .vite
npm install
npm run build
