### ISSUE TITLE
[Bug]: Error installing 7.6.18

### ISSUE THREAD

**Issue by FlorianBurgevin** [storybookjs/storybook#26926]
### Describe the bug

I'm triying to install storybook and some addons.
But it seems some elements are not published.

npm WARN ERESOLVE overriding peer dependency
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @storybook/docs-tools@7.6.18.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

### To Reproduce

 "@storybook/addon-essentials": "^7.6.18",
    "@storybook/addon-interactions": "^7.6.17",
    "@storybook/addon-links": "^7.6.18",
    "@storybook/blocks": "^7.6.18",
    "@storybook/react-vite": "^7.6.17",
    "storybook": "^7.6.17",

npm i

### System

```bash
none
```

**Comment by kantesilvestrsTWL** [comment]
Having the same issue

```
$ npm install
npm WARN ERESOLVE overriding peer dependency
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @storybook/addon-highlight@7.6.18.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

**Comment by kyselberg** [comment]
having same issue with such packages list
```
"@storybook/addon-essentials": "^7.6.18",
"@storybook/addon-links": "^7.6.18",
"@storybook/addons": "^7.6.18",
"@storybook/react": "^7.6.18",
"@storybook/react-webpack5": "^7.6.17",
"@storybook/theming": "^7.6.18",
```

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @storybook/addon-highlight@7.6.18.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

**Comment by DanielCraig01** [comment]
If you look into versions, you will notice that version 7.6.18 does not exist. Probably they have deleted it by mistake.
Meanwhile, you can use overrides in your package json like this:

  "overrides": {
    "@storybook/csf-plugin": "7.6.17",
    "@storybook/csf-tools": "7.6.17",
    "@storybook/preview-api": "7.6.17",
    "@storybook/react-dom-shim": "7.6.17",
    "@storybook/types": "7.6.17",
    "@storybook/docs-tools": "7.6.17",
    "@storybook/manager-api": "7.6.17"
  }

You're welcome :D

**Comment by kyselberg** [comment]
@FlorianBurgevin  or, following the same @DanielCraig01 's logic you can just remove "^" sign in front of your @storybook/* packages and "lock" 7.6.17 version.
you should up to latest version anyway after they resolve our issues.

**Comment by FlorianBurgevin** [comment]
@kyselberg i tried it yes but that was not working. Only overrides was ok.


Seems to be fixed !
