### ISSUE TITLE
[Bug]: can't pass tags array to CSF default export when is generated from a function (v7 AND v8)

### ISSUE THREAD

**Issue by YossiSaadi** [storybookjs/storybook#26940]
### Describe the bug

Note: I'm using v7 for now, would love to have the possibility to fix it also for v7 please :pray:

If you have a function
```typescript
import { Tag } from '@storybook/types';
export function createMetaSettings(): { tags: Tag[] } {
  return { tags: ['a', 'b'] };
}
```

And you try to use it as:
```typescript
import { createMetaSettings } from './createMetaSettings';

const metaSettings = createMetaSettings();
export default {
  // ...everythingElse,
  tags: metaSettings.tags,
}
```

you always get the error:
> 🚨 Unable to index ./src/stories/MyStory.stories.ts:
WARN   Error: CSF: Expected tags array

When I print the content of `metaSettings.tags` I always see that it is an array.

### To Reproduce

Here's a reproduction through `storybook.new`
Happens both on v7 and v8 of SB.
Check out the `Header.stories.ts` which uses the external function.

https://stackblitz.com/edit/github-cm2fqj?file=src%2Fstories%2FHeader.stories.ts

### System

```bash
Has nothing to do with system, happens on CSB, StackBlitz, and locally.
```

**Comment by YossiSaadi** [comment]
Hey guys, any plan on fixing it?

**Comment by valentinpalkovic** [comment]
Sometimes, settings in `main.ts` aren't evaluated at runtime but rather parsed for performance reasons. This might also be the case here, AFAIK (cc @shilman). This means, that the tags array has to be statically analyzable and you have to "hardcode" it.

**Comment by shilman** [comment]
Correct, this is by design. Apologies for the inconvenience!
