### ISSUE TITLE
Source Maps broken: Could not load content for webpack:

### ISSUE THREAD

**Issue by kasperpeulen** [storybookjs/storybook#26954]
### Discussed in https://github.com/storybookjs/storybook/discussions/26948

<div type='discussions-op-text'>

<sup>Originally posted by **tomitrescak** April 25, 2024</sup>
### Summary

Hello

My sourcemaps are broken with webpack and not loaded in any browser I tried (Chrome, Firefox, Safari).

With chrome I get this error:
`Could not load content for webpack://..` 

With Firefox:
`Error while fetching an original source: unsupported protocol for sourcemap request webpack://`

### Additional information

// main.ts
```ts
import type { StorybookConfig } from "@storybook/nextjs";
import react from "@vitejs/plugin-react-swc";
import tsconfigPaths from "vite-tsconfig-paths";

const config: StorybookConfig & { viteFinal: any } = {
  stories: ["../src/**/*.mdx", "../src/**/*.stories.@(js|jsx|mjs|ts|tsx)"],
  addons: [
    "@storybook/addon-onboarding",
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@chromatic-com/storybook",
    "@storybook/addon-interactions",
  ],
  framework: {
    name: "@storybook/nextjs",
    options: {},
  },
  docs: {
    autodocs: "tag",
  },
  staticDirs: ["../public"],
  features: {
    experimentalRSC: true,
  },
};
export default config;
```

This is preview.ts

```ts
import type { Preview } from "@storybook/react";

import { initialize, mswDecorator } from "msw-storybook-addon";

import "../src/dark.scss";
import "../src/main.scss";
import "../src/utility.css";

const preview: Preview = {
  parameters: {
    nextjs: {
      appDirectory: true,
    },
    controls: {
      matchers: {
        color: /(background|color)$/i,
        date: /Date$/i,
      },
    },
  },
};

initialize();
export const decorators = [mswDecorator];

export default preview;
```

### Create a reproduction

_No response_</div>

**Comment by kasperpeulen** [comment]
cc @valentinpalkovic

**Comment by kasperpeulen** [comment]
cc @shilman and @valentinpalkovic

**Comment by vottens** [comment]
We have the same issue. Impossible to debug when using storybook to TDD.

**Comment by tomitrescak** [comment]
@vottens you can switch temporarily to vite-builder which builds correct maps, but you will lose the Next.js 13 support. Unfortunately, I need Nextjs 13 and am working without source maps. Doable, ..., not pleasant :/

**Comment by willpoorman** [comment]
I just ran into a similar issue in Storybook 7:
```
Could not load content for webpack://<app-path>/ (Fetch through target failed: Unsupported URL scheme; Fallback: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME)
```

I see there was a PR #27171 by @valentinpalkovic that appears to fix it for Storybook 8. Any chance that fix could be back ported to Storybook 7? Currently unable to upgrade to Storybook 8 due to not being able to upgrade to Node 18 yet.
