### ISSUE TITLE
[Bug]: Storybook v8.0.9 fails to load storybook/blocks preset because of tocbot dependency error

### ISSUE THREAD

**Issue by danplubell** [storybookjs/storybook#26952]
### Describe the bug

@storybook/cli v8.0.9

SB_CORE-SERVER_0002 (CriticalPresetLoadError): Storybook failed to load the following preset: ./.storybook/main.ts.

Please check whether your setup is correct, the Storybook dependencies (and their peer dependencies) are installed correctly and there are no package version clashes.

If you believe this is a bug, please open an issue on Github.

SB_CORE-SERVER_0002 (CriticalPresetLoadError): Storybook failed to load the following preset: /Users/myproject/node_modules/.pnpm/@storybook+blocks@8.0.9_@types+react@18.2.45_react-dom@18.2.0_react@18.2.0/node_modules/@storybook/blocks/dist/index.js.

Please check whether your setup is correct, the Storybook dependencies (and their peer dependencies) are installed correctly and there are no package version clashes.

If you believe this is a bug, please open an issue on Github.

/Users/myproject/node_modules/.pnpm/tocbot@4.27.5/node_modules/tocbot/index.js:1
import { destroy, init, refresh } from './src/js/index-esm.js'
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1178:20)
    at Module._compile (node:internal/modules/cjs/loader:1220:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Object.newLoader (/Users/myproject/node_modules/.pnpm/esbuild-register@3.5.0_esbuild@0.20.2/node_modules/esbuild-register/dist/node.js:2262:9)

### To Reproduce

https://stackblitz.com/edit/github-7s5dz5?file=.storybook%2Fmain.ts

### System

```bash
Storybook Environment Info:

  System:
    OS: macOS 14.4.1
    CPU: (12) arm64 Apple M2 Pro
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    Yarn: 1.22.21 - /opt/homebrew/bin/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
    pnpm: 8.15.4 - /opt/homebrew/bin/pnpm <----- active
  Browsers:
    Edge: 124.0.2478.51
    Safari: 17.4.1
  npmPackages:
    @storybook/addon-a11y: 8.0.9 => 8.0.9
    @storybook/addon-actions: 8.0.9 => 8.0.9
    @storybook/addon-essentials: 8.0.9 => 8.0.9
    @storybook/addon-interactions: 8.0.9 => 8.0.9
    @storybook/addon-links: 8.0.9 => 8.0.9
    @storybook/blocks: 8.0.9 => 8.0.9
    @storybook/builder-vite: ^8.0.9 => 8.0.9
    @storybook/components: 8.0.9 => 8.0.9
    @storybook/manager-api: 8.0.9 => 8.0.9
    @storybook/react: 8.0.9 => 8.0.9
    @storybook/react-vite: 8.0.9 => 8.0.9
    @storybook/react-webpack5: 8.0.9 => 8.0.9
    @storybook/test: 8.0.9 => 8.0.9
    @storybook/theming: 8.0.9 => 8.0.9
    @storybook/types: 8.0.9 => 8.0.9
    eslint-plugin-storybook: ^0.8.0 => 0.8.0
    storybook: 8.0.9 => 8.0.9
```

**Comment by mattman240** [comment]
+1 same issue

**Comment by tinykite** [comment]
I saw a different error, but with the same dependency, while creating fresh builds of Svelte and well as Sveltekit (for Svelte 4 and 5). 

Steps to recreate: 
- Install Svelte with `npm create svelte@latest REPO-NAME`
- npm install
- Install and auto-configure Storybook with`npx storybook@latest init`

For Svelte 4, Sveltekit (with Svelte 4) and Sveltekit (with Svelte 5) the installer auto-detected Vite and successfully ran installation script, however failed after attempting to build. This happened again after manually running `npm run storybook`

The exact error:

```
✘ [ERROR] Could not resolve "tocbot"

    node_modules/@storybook/blocks/dist/index.mjs:20:24:
      20 │ ...s tocbot from 'tocbot';
         ╵                  ~~~~~~~~

  The module "./index.mjs" was not
  found on the file system:

    node_modules/tocbot/package.json:10:16:
      10 │ ...import": "./index.mjs",
         ╵             ~~~~~~~~~~~~~

  You can mark the path "tocbot" as
  external to exclude it from the
  bundle, which will remove this
  error and leave the unresolved path
  in the bundle.

Error: Build failed with 1 error:
node_modules/@storybook/blocks/dist/index.mjs:20:24: ERROR: Could not resolve "tocbot"
    at failureErrorWithLog (./node_modules/esbuild/lib/main.js:1651:15)
    at ./node_modules/esbuild/lib/main.js:1059:25
    at runOnEndCallbacks (./node_modules/esbuild/lib/main.js:1486:45)
    at buildResponseToResult (./node_modules/esbuild/lib/main.js:1057:7)
    at ./node_modules/esbuild/lib/main.js:1086:16
    at responseCallbacks.<computed> (./node_modules/esbuild/lib/main.js:704:9)
    at handleIncomingPacket (./node_modules/esbuild/lib/main.js:764:9)
    at Socket.readFromStdout (./node_modules/esbuild/lib/main.js:680:7)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.
```

**Comment by danplubell** [comment]
It looks like the latest version of tocbot resolves the 'cannot import issue' in our case.
