### ISSUE TITLE
[Bug]: Next 14.2.2 [ yarn dlx sb init -> running storybook error ]

### ISSUE THREAD

**Issue by jiwooproity** [storybookjs/storybook#27011]
### Describe the bug

I tried yarn dlx sb init to install storybook on NextJS, but I get an error when running.
---
## Error Message
SB_CORE-SERVER_0002 (CriticalPresetLoadError): Storybook failed to load the following preset: ./.yarn/__virtual__/@storybook-nextjs-virtual-84d4386fdd/5/.yarn/berry/cache/@storybook-nextjs-npm-8.0.9-0f2975ab05-10c0.zip/node_modules/@storybook/nextjs/preset.

Please check whether your setup is correct, the Storybook dependencies (and their peer dependencies) are installed correctly and there are no package version clashes.

If you believe this is a bug, please open an issue on Github.

Error: @storybook/nextjs tried to access webpack (a peer dependency) but it isn't provided by your application; this makes the require call ambiguous and unsound.

Required package: webpack
Required by: @storybook/nextjs@virtual:a66c2dfc1a8e124178cdece2baee0ede0b530dc9fdd194fe72876ef07b201e80d71a23e5cd59e911cafe4b299192da896204bf9e014a8cda7c6d87b55dd7b1c8#npm:8.0.9 (via ./.yarn/__virtual__/@storybook-nextjs-virtual-84d4386fdd/5/.yarn/berry/cache/@storybook-nextjs-npm-8.0.9-0f2975ab05-10c0.zip/node_modules/@storybook/nextjs/dist/)
Ancestor breaking the chain: dejay-home@workspace:.

Require stack:
- ./.yarn/__virtual__/@storybook-nextjs-virtual-84d4386fdd/5/.yarn/berry/cache/@storybook-nextjs-npm-8.0.9-0f2975ab05-10c0.zip/node_modules/@storybook/nextjs/dist/preset.js
- ./.yarn/__virtual__/@storybook-nextjs-virtual-84d4386fdd/5/.yarn/berry/cache/@storybook-nextjs-npm-8.0.9-0f2975ab05-10c0.zip/node_modules/@storybook/nextjs/preset.js
- /Users/jiwoo/.yarn/berry/cache/@storybook-core-common-npm-8.0.9-3b7d4e5821-10c0.zip/node_modules/@storybook/core-common/dist/index.js
- /Users/jiwoo/.yarn/berry/cache/@storybook-telemetry-npm-8.0.9-b3a94385d6-10c0.zip/node_modules/@storybook/telemetry/dist/index.js
- /Users/jiwoo/.yarn/berry/cache/@storybook-cli-npm-8.0.9-aa29c0335c-10c0.zip/node_modules/@storybook/cli/dist/generate.js
- /Users/jiwoo/.yarn/berry/cache/@storybook-cli-npm-8.0.9-aa29c0335c-10c0.zip/node_modules/@storybook/cli/bin/index.js
- /Users/jiwoo/.yarn/berry/cache/storybook-npm-8.0.9-94af20108d-10c0.zip/node_modules/storybook/index.js
    at require$0.Module._resolveFilename (./.pnp.cjs:22521:13)
    at Module._resolveFilename (./.yarn/__virtual__/esbuild-register-virtual-0f58517950/5/.yarn/berry/cache/esbuild-register-npm-3.5.0-d823f64ce0-10c0.zip/node_modules/esbuild-register/dist/node.js:4799:36)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at require$0.Module._load (./.pnp.cjs:22412:31)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:119:18)
    at Object.<anonymous> (./.yarn/__virtual__/@storybook-nextjs-virtual-84d4386fdd/5/.yarn/berry/cache/@storybook-nextjs-npm-8.0.9-0f2975ab05-10c0.zip/node_modules/@storybook/nextjs/dist/preset.js:1:8263)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at require$0.Module._extensions..js (./.pnp.cjs:22564:33)
    at loadPreset (/Users/jiwoo/.yarn/berry/cache/@storybook-core-common-npm-8.0.9-3b7d4e5821-10c0.zip/node_modules/@storybook/core-common/dist/index.js:12:59)

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

### To Reproduce

running : @storybook/cli v8.0.9 start, and i get an error
![스크린샷 2024-05-02 오후 10 30 56](https://github.com/storybookjs/storybook/assets/58384366/18f530a5-f2af-440c-9096-68e41b501e54)

next version : 14.2.2
package manage : yarn berry pnp

Steps:
    1. yarn dlx sb init
    2. installing ....
    3. Running Storybook : @storybook/cli v8.0.9
    4. error ..

### System

```bash
System:
    OS: macOS 14.4.1
    CPU: (8) arm64 Apple M1
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.5.0 - /opt/homebrew/bin/node
    Yarn: 4.1.1 - /opt/homebrew/bin/yarn <----- active
    npm: 10.2.2 - /opt/homebrew/bin/npm
    pnpm: 8.10.2 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 124.0.6367.94
    Safari: 17.4.1
```

**Comment by jiwooproity** [comment]
i tried yarn add --dev webpack and resolved!
i'm sorry to open issue

**Comment by wujibear** [comment]
Please don't be sorry! You helped me fix the same issue!
