### ISSUE TITLE
[Bug]: Empty index.html

### ISSUE THREAD

**Issue by Satsuger** [storybookjs/storybook#27020]
### Describe the bug

When building storybook i have plain index.html with no bundles loaded. 

storybook-static/index.html
`<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="theme-color" content="#000000" />
    <meta
      name="description"
      content="myproject"
    />
    
    
    
    
    <title>myproject</title>
  </head>
  <body>
    <noscript>You need to enable JavaScript to run this app.</noscript>
    <div id="root"></div>
    
  </body>
</html>
`

.storybook/main.ts
`import type { StorybookConfig } from "@storybook/react-vite";
import { mergeConfig } from 'vite';
import tsconfigPaths from 'vite-tsconfig-paths';

const config: StorybookConfig = {
  stories: ["../src/**/*.mdx", "../src/**/*.stories.@(js|jsx|ts|tsx)"],
  addons: [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/addon-onboarding",
    "@storybook/addon-interactions",
  ],
  framework: {
    name: "@storybook/react-vite",
    options: {},
  },
  core: {
    builder: "@storybook/builder-vite",
  },
  docs: {
    autodocs: "tag",
  },
  staticDirs: ["../public"],

  viteFinal: async (viteConfig, { configType }) => {
    return mergeConfig(viteConfig, {
      plugins: [tsconfigPaths()],
    });
  },
};
export default config;
`

### To Reproduce

npm run build-storybook

I have another project with similar setup and i haven't been able to reproduce this error in another project.

### System

```bash
System:
    OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 21.7.3 - ~/.nvm/versions/node/v21.7.3/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v21.7.3/bin/yarn
    npm: 10.5.0 - ~/.nvm/versions/node/v21.7.3/bin/npm <----- active
  npmPackages:
    @storybook/addon-essentials: ^7.4.1 => 7.6.18 
    @storybook/addon-interactions: ^7.4.1 => 7.6.18 
    @storybook/addon-links: ^7.4.1 => 7.6.18 
    @storybook/addon-onboarding: ^1.0.8 => 1.0.11 
    @storybook/blocks: ^7.4.1 => 7.6.18 
    @storybook/builder-vite: ^8.0.9 => 8.0.9 
    @storybook/icons: ^1.2.9 => 1.2.9 
    @storybook/preset-create-react-app: ^7.0.10 => 7.6.18 
    @storybook/react: ^7.4.1 => 7.6.18 
    @storybook/react-vite: ^7.4.1 => 7.6.18 
    @storybook/testing-library: ^0.0.14-next.2 => 0.0.14-next.2 
    storybook: ^7.4.1 => 7.6.18
```

**Comment by shilman** [comment]
Do you a have a reproduction repo you can share? If not, can you create one? Go to https://storybook.new or see [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce). Thank you! 🙏
