### ISSUE TITLE
[Bug]: manager-api / manager.js doesn't work

### ISSUE THREAD

**Issue by Energiz3r** [storybookjs/storybook#27104]
### Describe the bug

manager-api / manager.js doesn't work

Every time storybook is run it defaults to the Addon panel taking up half the page, and the sidebar hidden. I'm trying to fix that.

### To Reproduce

Follow the doco and try to configure anything: https://storybook.js.org/docs/configure/features-and-behavior

### System

```bash
npx storybook@latest info
Need to install the following packages:
  storybook@8.0.10
Ok to proceed? (y) n
```
Yeah so no, 
```
"@storybook/addon-essentials": "^7.5.3",
    "@storybook/addon-interactions": "^7.5.3",
    "@storybook/addon-links": "^7.5.3",
    "@storybook/addon-themes": "^7.5.3",
    "@storybook/blocks": "^7.5.3",
    "@storybook/manager-api": "^8.0.10",
    "@storybook/nextjs": "^7.5.3",
    "@storybook/react": "^7.5.3",
    "@storybook/testing-library": "^0.2.2",
```
```


### Additional context

I also added the manager-api to the plugin list in `./storybook/main.ts` which made no difference. The doco doesn't mention anything about setup or install so it's anyone's guess whether any steps are required.

**Comment by shilman** [comment]
We completely overhauled the way this works in Storybook 8.0. Please try upgrading and let us know if you run into the same problem.

Migration guide: https://storybook.js.org/docs/8.0/migration-guide
