### ISSUE TITLE
[Bug]: Controls is not updating Canvas story if they're in the same mdx.

### ISSUE THREAD

**Issue by jertfelt** [storybookjs/storybook#27205]
### Describe the bug

When I'm using Canvas (with a story) and a control on the same docs file (in this case a mdx-file) the controls changes things, but it isn't shown in the canvas:

<Canvas of={ImportedIconButton} story={{
    inline: false,
  }}
  source={{
    language: 'html',
    format:"dedent",
    type:"dynamic",
    code:""
  }}
  withToolbar={true}
  layout="fullscreen"
  className="custom-class"/>

  <Controls of={ImportedIconButton}/>
  
  

### Reproduction link

https://github.com/jertfelt/storybook-bug/tree/main

### Reproduction steps

When I want to change the different controls, I want the information shown in the docs to be changed. However, the canvas doesn't seem to import it.

### System

```bash
Storybook Environment Info:
(node:27244) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

  System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
  Binaries:
    Node: 21.7.3 - C:\Program Files\nodejs\node.EXE
    npm: 10.5.0 - C:\Program Files\nodejs\npm.CMD <----- active
  Browsers:
    Edge: Chromium (122.0.2365.120)
  npmPackages:
    @storybook/addon-a11y: ^8.1.1 => 8.1.1 
    @storybook/addon-actions: ^8.1.1 => 8.1.1 
    @storybook/addon-essentials: ^8.1.1 => 8.1.1 
    @storybook/addon-interactions: ^8.1.1 => 8.1.1 
    @storybook/addon-links: ^8.1.1 => 8.1.1 
    @storybook/addon-mdx-gfm: ^8.1.1 => 8.1.1 
    @storybook/addon-webpack5-compiler-babel: ^3.0.3 => 3.0.3  
    @storybook/blocks: ^8.1.1 => 8.1.1 
    @storybook/html: ^8.1.1 => 8.1.1 
    @storybook/html-vite: ^8.1.1 => 8.1.1 
    @storybook/manager-api: ^8.1.1 => 8.1.1 
    @storybook/preview-api: ^8.1.1 => 8.1.1 
    @storybook/test: ^8.1.1 => 8.1.1 
    @storybook/theming: ^8.1.1 => 8.1.1 
    storybook: ^8.1.1 => 8.1.1
```

**Comment by shilman** [comment]
This is a known limitation documented here https://storybook.js.org/docs/api/doc-block-story#inline
