### ISSUE TITLE
[Bug]: Excessive React library requirement for angular storybook

### ISSUE THREAD

**Issue by blazkovicz** [storybookjs/storybook#27213]
### Describe the bug

We use storybook 8 with angular 17. As I understood, react libraries are required for storybook auto-documentation, but we do not use it. Storybook builds and shows just fine, but webpack build error arises at the end of build which results in storybook process being unmanageable afterwards (can not be stopped from IDE, only process kill in task manager helps). Debugging webpack configuration gives next errors:

Can't resolve 'react' in 'node_modules\@storybook\icons\dist'
Can't resolve 'react' in 'node_modules\@storybook\manager-api\dist'
Can't resolve 'react' in 'node_modules\@storybook\router\dist'

Is it possible to drop react dependency for these packages?

### Reproduction link

I do not have reproduction link

### System

```bash
System:
    OS: Windows 10 10.0.19045
    CPU: (24) x64 AMD Ryzen 9 5900X 12-Core Processor
  Binaries:
    Node: 20.11.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 4.1.1 - ~\AppData\Roaming\npm\yarn.CMD <----- active
    npm: 9.6.6 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (125.0.2535.51)
  npmPackages:
    @storybook/addon-actions: ^8.0.8 => 8.0.8
    @storybook/addon-controls: ^8.0.8 => 8.0.8
    @storybook/addon-links: ^8.0.8 => 8.0.8
    @storybook/addon-toolbars: ^8.0.8 => 8.0.8
    @storybook/addon-viewport: ^8.0.8 => 8.0.8
    @storybook/addons: ^7.6.17 => 7.6.17
    @storybook/angular: ^8.0.8 => 8.0.8
    eslint-plugin-storybook: ^0.8.0 => 0.8.0
    storybook-addon-mock: ^5.0.0 => 5.0.0
    storybook-dark-mode: ^4.0.1 => 4.0.1
    storybook-preset-inline-svg: ^1.0.1 => 1.0.1
```

**Comment by vanessayuenn** [comment]
You're right that starting from 8.0, there should be no need for a react peer dependency for non-react projects. If your issue only occurs after the upgrade, it's possible that this is a hoisting issue that may be resolved by "nuke & reinstall" all the dependencies. That said, I am afraid we will not be able to prioritize this report without a reproduction. If you are able to create one via [storybook.new](https://new-storybook.netlify.app/), we can look into it. Thank you for your understanding!

**Comment by blazkovicz** [comment]
Regardless reproduction of the problem (it was mentioned as just a case of inconveniency) these common libraries should not use react at all. Setup is: angular project, no autodocs, just component stories, we do not want to keep react dependencies there even as devDependencies.

**Comment by Marklb** [comment]
Are you wanting to drop React as a dependency in your dependencies or are you stating that you don't want it in the Storybook packages dependencies? With a reproduction or error output, it is difficult to determine if you are experiencing a bug that needs to be fixed or something Storybook can work on removing.

Everything Storybook is doing should be isolated away, so you only have to think about your stories, but technically Storybook is a React application that renders stories as isolated mini applications inside a React component.

I may not be understanding the question, but you should not need to specify it as a dependency in your project. I don't think you would be able to avoid it being a dependency in at least some of Storybook's packages, though. The Storybook UI is a React application and story is basically a React component that renders a mini application. In your case, that mini application would be an Angular application. Ideally, Storybook hides the need to think about how it does that, but Storybook is basically just a React application that attempts to render isolated mini applications from any framework.

In an Angular project, Storybook is using Compodoc to collect information for auto-documentation. If you choose to do that then the documentation would be renders with React, but that is only a small part of the UI and React is still being used for the other UI parts.
