### ISSUE TITLE
[Bug]: Cannot add property __docgen, object is not extensible

### ISSUE THREAD

**Issue by Forthtilliath** [storybookjs/storybook#27233]
### Describe the bug

Hello,

Im using storybook with shadcn-svelte. When i installed the component Calendar, the storybook display an error. I created a stackblitz with my code and we can see the error inside ``With Tailwind + CSF``/``Field``.

When i remove the importation of Calendar, the Story works well.

### Reproduction link

https://stackblitz.com/edit/sb-calendar?file=src%2Flib%2Fcomponents%2Ffield%2Ffield.svelte

### System

```bash
Storybook Environment Info:

  System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
  Binaries:
    Node: 20.12.2 - C:\Program Files\nodejs\node.EXE
    npm: 9.7.2 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.1.2 - ~\AppData\Local\pnpm\pnpm.CMD <----- active
  Browsers:
    Edge: Chromium (124.0.2478.51)
  npmPackages:
    @storybook/addon-essentials: ^8.1.2 => 8.1.2
    @storybook/addon-interactions: ^8.1.2 => 8.1.2
    @storybook/addon-links: ^8.1.2 => 8.1.2
    @storybook/addon-svelte-csf: ^4.1.2 => 4.1.3
    @storybook/blocks: ^8.1.2 => 8.1.2
    @storybook/svelte: ^8.1.2 => 8.1.2
    @storybook/sveltekit: ^8.1.2 => 8.1.2
    @storybook/test: ^8.1.2 => 8.1.2
    eslint-plugin-storybook: ^0.8.0 => 0.8.0
    storybook: ^8.1.2 => 8.1.2
```

### Additional context

Storybook page with error : ``With Tailwind + CSF`` / ``Field``
File with calendar import : src\lib\components\field\field.svelte

**Comment by phlrss** [comment]
i'm having the same issue - also with shadcn-svelte in storybook

**Comment by xeho91** [comment]
The reproduction link doesn't show the setup you described, nor show the issue you have.

**Comment by Forthtilliath** [comment]
Hum, it's not what à i posted few days ago. I'll remake it

**Comment by xeho91** [comment]
Inspecting this issue, I firstly suspected `@storybookjs/addon-svelte-csf` code transformation _(commenting out the `export default` or `export { meta }`)_, but it wasn't the root cause for this issue, I've verified it quickly by changing the plugin to remove instead of commenting out. It wasn't the reason.


These is my observations, perhaps could help other maintainers debug quickier to figure out why.

The user is using "compound component", quite common pattern in React AFAIK.

```svelte
<!-- calendar-svelte -->
<script lang="ts">
	import { Calendar as CalendarPrimitive } from "bits-ui";
	import * as Calendar from "./index.js"; // This breaks the Storybook
	import { cn } from "$lib/utils.js";
	// ...
</script>
```

The imported file content is:

```js
// calendar/index.js
import Root from "./calendar.svelte";
import Cell from "./calendar-cell.svelte";
import Day from "./calendar-day.svelte";
import Grid from "./calendar-grid.svelte";
import Header from "./calendar-header.svelte";
import Months from "./calendar-months.svelte";
import GridRow from "./calendar-grid-row.svelte";
import Heading from "./calendar-heading.svelte";
import GridBody from "./calendar-grid-body.svelte";
import GridHead from "./calendar-grid-head.svelte";
import HeadCell from "./calendar-head-cell.svelte";
import NextButton from "./calendar-next-button.svelte";
import PrevButton from "./calendar-prev-button.svelte";

export {
	Day,
	Cell,
	Grid,
	Header,
	Months,
	GridRow,
	Heading,
	GridBody,
	GridHead,
	HeadCell,
	NextButton,
	PrevButton,
	//
	Root as Calendar,
};
```

For some reason which I haven't found yet, this breaks only in Storybook. It works with normal Vite build.

## Current workaround

This is not what the user will want for sure, it will decrease his code readability, but it will work.

```diff
<script lang="ts">
	import { Calendar as CalendarPrimitive } from "bits-ui";
-	import * as Calendar from "./index.js"; // This breaks the Storybook
+	import { Day, Cell, Grid, Header, Months, GridRow, Heading, GridBody, GridHead, HeadCell, NextButton, PrevButton, Calendar } from "./index.js";
	import { cn } from "$lib/utils.js";
	// ...
</script>
```

**Comment by Forthtilliath** [comment]
I tried, and it works. It's not optimal, but at least it works and it's simple to fix. Thanks a lot !
