### ISSUE TITLE
[Bug]: Storybook 8.1 does not display stories from composable (refs) like in previous version

### ISSUE THREAD

**Issue by stefanlivens** [storybookjs/storybook#27352]
### Describe the bug

Setup:
- host/main Storybook 8.x, with refs to
- composed Storybook v7.6.19

With Storybook 8.0.10 as the host, we got an overview of all the stories and their doc file, from the composed Storybook, like in first picture.
<img width="286" alt="Screenshot 2024-05-23 at 17 03 23" src="https://github.com/storybookjs/storybook/assets/296395/57875f09-456e-4188-8a98-38db1542dfc3">

Upon upgrading to Storybook 8.1, this list become a list of only the docs! This is the only change between the 2 pictures.
<img width="282" alt="Screenshot 2024-05-23 at 17 05 07" src="https://github.com/storybookjs/storybook/assets/296395/57fbdc7e-9338-4534-bfc9-2de37c60551b">

I verified stories.json and index.json, these contain the necessary info. For the composed Storybook, the stories have their mdx file linked to them via parameters.docs.page in the stories.js.

### Reproduction link

sorry, all internal

### Reproduction steps

Alas, all internal. 

But going from 8.0.10 to 8.1 displays the erroneous behaviour, going back to 8.0.10 makes it work as before. (Only storybook and @storybook/* dependencies got a version change)

### System

```bash
Storybook Environment Info:

  System:
    OS: macOS 14.5
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.19.0 - /usr/local/bin/node
    npm: 10.2.3 - /usr/local/bin/npm <----- active
  Browsers:
    Safari: 17.5
  npmPackages:
    @storybook/addon-a11y: 8.1.0 => 8.1.0 
    @storybook/addon-designs: ^8.0.2 => 8.0.2 
    @storybook/addon-essentials: 8.1.0 => 8.1.0 
    @storybook/addon-links: 8.1.0 => 8.1.0 
    @storybook/addon-webpack5-compiler-babel: ^3.0.3 => 3.0.3 
    @storybook/web-components-webpack5: 8.1.0 => 8.1.0 
    storybook: 8.1.0 => 8.1.0 

This behaviour is also present when building on azure windows agents
```

**Comment by shilman** [comment]
Hi @stefanlivens That's a pretty bad bug! Taking a closer look now.
