### ISSUE TITLE
[Bug]: Inconsistent Error Handling and Promise Management in Storybook Normalize Angular Entry Plugin

### ISSUE THREAD

**Issue by superhermione** [storybookjs/storybook#27367]
### Describe the bug

The Storybook Normalize Angular Entry Plugin lacks comprehensive error handling and has potential issues in how promises are managed when labeling pull requests. This can lead to unhandled exceptions and system instability in scenarios where network requests fail or the git operations return unexpected results. Furthermore, the constructor of the plugin uses an unused 'options' parameter which could be confusing and misleading for other developers.

### Reproduction link

N/A - The issue relates to code quality and architectural improvements rather than a specific runtime bug

### Reproduction steps

Link: https://github.com/storybookjs/storybook/blob/next/code/frameworks/angular/src/server/plugins/storybook-normalize-angular-entry-plugin.js 
1. Navigate to the Storybook Normalize Angular Entry Plugin codebase.
2. Observe the lack of error handling in asynchronous operations.
3. Trigger operations that lead to errors (e.g., simulate network failures or corrupt git operations).
4. Notice the absence of error recovery, leading to possible system crashes or unhandled promises.

### System

```bash
System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
  Binaries:
    Node: 18.17.1 - C:\Program Files\nodejs\node.EXE
    npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD <----- active
  Browsers:
    Edge: Chromium (123.0.2420.81)
```

**Comment by valentinpalkovic** [comment]
Hi @superhermione 

thank you for reporting the issue!

Would you like to put together a PR with a fix?

**Comment by superhermione** [comment]
> Hi @superhermione
> 
> thank you for reporting the issue!
> 
> Would you like to put together a PR with a fix?

Thank you. I will fix it.
