### ISSUE TITLE
[Bug]: Importing `@storybook/components` into mdx pages results in render failure in Storybook 8

### ISSUE THREAD

**Issue by fmal** [storybookjs/storybook#27371]
### Describe the bug

After upgrade to storybook@8, my mdx documentation pages that imported components from `@storybook/components` stopped rendering due to errors like below:
<img width="561" alt="SCR-20240526-phhm" src="https://github.com/storybookjs/storybook/assets/927591/6b484e13-be15-446f-9840-f960489e4225">

Loading a page that doesn't import anything from `@storybook/components` works fine.

Interesting fact is that these errors are preceded by a warning about multiple instances of `@emotion/react` package.

<img width="1410" alt="SCR-20240526-piad" src="https://github.com/storybookjs/storybook/assets/927591/bc99a92a-becf-4e22-b8c2-b2edeb04ef11">

The repro is setup with latest Yarn (4.2.2) and is a very minimal extract from my production storybook, where this error also happens and prevents me to migrate to version 8. In Storybook 7.6.19 these errors do not occur.

### Reproduction link

https://github.com/fmal/storybook-8-bug-repro

### Reproduction steps

1. Clone the above repo
2. run `yarn install`
3. run `yarn storybook`
4. Open http://localhost:6006/?path=/docs/example-broken-page--docs, the following error will appear:
`Cannot read properties of undefined (reading 'size')`
5. Open http://localhost:6006/?path=/docs/example-introduction--docs, it should display, though multiple instances of `@emotion/react` warning will display in console

### System

```bash
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 20.11.0 - ~/.asdf/installs/nodejs/20.11.0/bin/node
    Yarn: 4.2.2 - ~/.asdf/installs/nodejs/20.11.0/bin/yarn <----- active
    npm: 10.2.4 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Chrome: 125.0.6422.77
    Safari: 15.6.1
```

### Additional context

<img width="1285" alt="SCR-20240526-pfka" src="https://github.com/storybookjs/storybook/assets/927591/eaa641ef-c845-496f-bd6e-6459bff4224c">

**Comment by shilman** [comment]
@storybookjs/core  This looks like some kind of issue with the theme provider. From what I can tell all the package versions are correct, and the Docs page is wrapped in a valid `ThemeProvider`, so I'm really not sure what's going on here. Any ideas?

**Comment by tmeasday** [comment]
This seems to be some kind of webpack/yarn bundle issue @shilman I can see `@storybook/components` in two different chunks, specifically try searching for this `"../.yarn/__virtual__/@storybook-components-virtual-a8967408c7/4/.yarn/berry/cache/@storybook-components-npm-8.1.3-da5969b1b0-10.zip/node_modules/@storybook/components/dist/index.mjs"`, it'll be in both these files:

<img width="711" alt="image" src="https://github.com/storybookjs/storybook/assets/132554/796a7734-2744-4922-9c7d-312a20d15448">

Looking like this in both cases:

<img width="631" alt="image" src="https://github.com/storybookjs/storybook/assets/132554/14b14c38-4226-417f-9cf1-c0169e09a882">

**Comment by ndelangen** [comment]
What's the use case of rendering storybook/components inside stories? This is not it's intended use-case.

For dumentation blocks we have `@storybook/blocks`.

**Comment by fmal** [comment]
@ndelangen not strictly inside stories but for more complex documentation pages, where I oftentimes need to import things like buttons, tabs etc. It makes total sense to me to reuse the UI of Storybook for that purpose and this used to work in storybook@7

**Comment by ndelangen** [comment]
I sympathize that it worked pre 8.0.

However the components defined in `@storybook/components` require a special context present.

But this was not intended to work / officially support.

I would be open to adding some more components for blocks, which would then be officially supported.

**Comment by fmal** [comment]
@ndelangen i tested with the latest release (8.2.8) and the issue is gone, i can successfully import `@storybook/components` into mdx.  Seems like Core Package Consolidation has fixed it. Thanks!
