### ISSUE TITLE
Addon-viewport: Migrate to story globals

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#27524]
### Describe the problem

[Story globals](https://github.com/storybookjs/storybook/discussions/23347#discussioncomment-9575546) simplifies how to configure globals at the story level. We should update the Viewport addon to use the new scheme.

- [ ] Figure out a final API
  - [ ] globals for storing/accessing state
- [ ] Update documentation

#### Before

```js
export const Story = {
  parameters: {
    viewport: {
      defaultViewport: 'phone',
      defaultOrientation: 'landscape',
    },
  },
};
```

#### After (TBD)

```js
export const Story = {
  globals: {
    viewport: 'phone',
    viewportRotated: true,
  },
};
```

### Additional context

We should also try to reconcile Chromatic Modes if we can

**Comment by viters** [comment]
Just wanted to point out that these options are not compatible. `viewport.defaultViewport` was default, `globals.viewport.value` is forced viewport without allowing user to change it.
