### ISSUE TITLE
[Bug]: All `fn()` stubs get logged in the `Actions` panel, not just the component's args

### ISSUE THREAD

**Issue by jalooc** [storybookjs/storybook#27534]
### Describe the bug

Not only the `fn()` arg types are logged in the `Actions` tab, but all the `fn()`s used anywhere.

A sample case I've been tackling with, after upgrading SB to v8, is that I've got quite a lot of stubs defined using `fn()` for mocked api modules in my application (using the `__mock__` folder method with `storybook-addon-manual-mocks`). All their invocations get logged in the `Actions` panel when the component story is invoked, but it does not make sense to have them logged in there - they're neither actions, nor anything relevant to the person using the story. In some cases, when a more complex component, like a page component, makes lots of those mocked api requests, this behaviour renders the `Actions` tab completely unusable, littering it with irrelevant entries.

---

First mention: https://github.com/storybookjs/storybook/pull/24392#discussion_r1625929322

### Reproduction link

https://stackblitz.com/edit/github-xdgoog?file=src%2Fstories%2F__mocks__%2Fapi.ts

### Reproduction steps

1. Go to any `Page` story.
2. See an item logged in the `Actions` tab.
  ![image](https://github.com/storybookjs/storybook/assets/6209244/d759cc07-5639-46f3-91d5-9993461f4dd4)
3. Note that there are no action arguments passed to the story - it's just the `fn()` stub from the `__mocks__` directory being logged.

### System

```bash
Storybook Environment Info:

  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm <----- active
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    @storybook/addon-essentials: ^8.2.0-alpha.5 => 8.2.0-alpha.5 
    @storybook/addon-interactions: ^8.2.0-alpha.5 => 8.2.0-alpha.5 
    @storybook/addon-links: ^8.2.0-alpha.5 => 8.2.0-alpha.5 
    @storybook/addon-onboarding: ^8.2.0-alpha.5 => 8.2.0-alpha.5 
    @storybook/blocks: ^8.2.0-alpha.5 => 8.2.0-alpha.5 
    @storybook/react: ^8.2.0-alpha.5 => 8.2.0-alpha.5 
    @storybook/react-vite: ^8.2.0-alpha.5 => 8.2.0-alpha.5 
    @storybook/test: ^8.2.0-alpha.5 => 8.2.0-alpha.5 
    storybook: ^8.2.0-alpha.5 => 8.2.0-alpha.5 
    storybook-addon-manual-mocks: ^1.0.4 => 1.0.4
```

**Comment by shilman** [comment]
@kasperpeulen is there any way to disable logging of spies if it's not desired?

**Comment by kasperpeulen** [comment]
@jalooc We do want to (allow people to) show spies in the action panel:
https://x.com/KasperPeulen/status/1777934882900963702

We use it extensively in our RSC demo. It show mocks that we automatically set for the nextjs framework (cookies/redirect etc.) And it also shows the spies that are manually attached to the (in memory) database.

https://github.com/storybookjs/storybook-rsc-demo
https://66228a3205a9e64e345243d6-ylfrfcbkzm.chromatic.com/?path=/story/app-note-id-page--logout-should-delete-cookie
<img width="1396" alt="image" src="https://github.com/storybookjs/storybook/assets/1035299/6ddfb543-d388-49fa-965a-c34a4765185e">

But I do agree with you, it very fast become way too noisy. Actually we hardcoded to not show all spies in the action panel that the nextjs framework adds by default:

https://github.com/storybookjs/storybook/blob/174bd22bb8e1a7400a1c97b3d3deaf41d47023d2/code/addons/actions/src/loaders.ts#L20-L43

Which is certainly not ideal, but we didn't have time to make a dedicated action filtering solution yet.

For the short term I propose that **we only log spies if they have a name**.
Let me know if this fixes your concern @jalooc 

You can set a name with `fn().mockName('api.users.create')`. If it has no name, it hardly adds any value, to see it in the action panel.

For a long term solution, I think it would be best to have 2 mock types:

* `query`, this would be for mocking functions that don't mutate, but only query data, typically a GET request
* `action`, this would be for mocking that functions that do mutate (might also get some data), typically a POST/PUT/DELETE request

The API might be: `fn().type('action')` and `fn().type('query')`

We could automatically enhance all event handlers (onClick etc) to be `actions`. And then the action panel might only show `actions` by default, but optionally can show more with some extra UI cc @cdedreuille. Maybe something similar as the chrome console:

![image](https://github.com/storybookjs/storybook/assets/1035299/a7fc2ff0-acff-4b75-9a1b-e23c6492031d)

There still might be cases where you do want to add a name to the spy, and it really is an action, but you still don't want to show it in the action panel by default. For those cases, I think we could have some parameter convention:

```ts
  parameters: {
    actions: {
      filter: {
        'API.getAll': false,
        'next/headers::cookies().get': false,
        `^next/router::useRouter\\(\\)`: true // maybe even regex?
      }
    },
```

Where every addon can disable showing some spies. E.g. this is what the next addon would use. To only show the useful stuff in the action panel.

And then users can:
* renable spies that are hidden by addons
* disable some of their own spies to show in the action panel
* even disable some spies for specific stories with the parameters inheritance

**Comment by shilman** [comment]
@kasperpeulen I like your "no name" solution as a short term fix. Let's do it. For the larger fix, please write a short RFC and let's discuss as a small batch project.

**Comment by kasperpeulen** [comment]
@shilman Made a PR for that #28091

**Comment by jalooc** [comment]
Sorry for the late reply. Answering [that](https://github.com/storybookjs/storybook/issues/27534#issuecomment-2151989086) comment:

Yes, logging spies if they have a name sounds like a reasonable short-term fix.

As for the long-terms solution - not sure about adding the division between _query_ and _action_, cause it kind of enofrces a quite opinionated view on how a dev should treat the actions, whereas I really liked the freedom of the old `actions()` api - it allowed me to log in the `Actions` panel whatever I reckoned made sense for particular story, without limiting myself to the the semantics like _query_ / _action_.

On that note - wouldn't it be possible to bring back that `action()` api? E.g. the `action` function imported from `@storybook/test` could be the simple `fn()` under the hood, just transparently enriched with the code logging it in the `Actions` panel; and the `fn()` itself could be left untouched in order not to leave devs surprised about it additional behaviour. Choosing to use `vitest` as a first-class-citizen was imho a great move, but when a dev learns that parts of the `vitest`'s api are modified (has some side effects) and you can't simply rely on it to work the way you learned it from `vitest` docs, it kind of makes you loose trust in the presumptive behaviour of the api, making the overal experience much less smooth.
