### ISSUE TITLE
Disable loading custom .babelrc

### ISSUE THREAD

**Issue by sergeysova** [storybookjs/storybook#2758]
I use babel@7. But storybook use babel@6.

```
ERROR in ./.storybook/config.js
Module build failed: TypeError: Cannot read property 'loose' of undefined
```

If I rename `.babelrc` all works correctly.

But `babel-loader@8` wants `.babelrc` file when load module through alias and I can't rename config file.

Can I disable loading custom .babelrc?

**Comment by sergeysova** [comment]
If I create `.storybook/.babelrc` with content `{}`, storybook can't parse react.

But I don't want override storybook's config. I want only disable loading config from root.

**Comment by Hypnosphi** [comment]
You may want to replace our instance of `babel-loader` with your own:

```
// .strorybook/webpack.config.js

module.exports = baseConfig => {
  baseConfig.module.rules = [{
    test: /\.js$/,
    exclude: /node_modules/,
    loader: 'babel-loader' // this will use your `babel-loader@8`
  }];
  return baseConfig;
};
```

**Comment by Robula** [comment]
This would be a nice feature. I require a `.babelrc` in the root to configure `babel-jest` in my Lerna monorepo to transpile ESM in node_modules (I'm using TypeScript throughout) and Storybook tries to use this.
```
{
  "env": {
    "test": {
      "plugins": [
        "transform-es2015-modules-commonjs"
      ]
    }
  }
}
```

**Comment by noinkling** [comment]
I also have a .babelrc in the root of my project that's only suitable for backend stuff, it would be nice to have an option to ignore it.

**Comment by noinkling** [comment]
Trying to get started with Storybook in a monorepo and this is an issue for me too. As long as a root .babelrc exists, it seems impossible to use the default included Babel config. There really needs to be an option to choose between default or lookup.

As a bonus, you could then rely on babel-loader's default lookup behaviour (in Babel 6: use the closest config relative to the module) instead of looking only and specifically in the root dir. `package.json` configurations would also work then.

`.storybook/.babelrc` can be retained as an override mechanism.

**Comment by Hypnosphi** [comment]
`@4.0.0-alpha.18` release of Storybook uses Babel 7 by default.

@noinkling #4077 should fix the issue: after releasing it, our default config will be merged with the one from your `babelrc.js`.

I'm also going to add a way to disable loading app's babel config without replicating Storybook default by providing a `.storybook/babel.config.js` file with following content:
```
module.exports = defaultConfig => defaultConfig
```
It will work with Babel 7 only

**Comment by igor-dv** [comment]
@Hypnosphi, can we consider this as done? Overriding babel configuration is already could be achieved with presets (although there is no documentation yet)

**Comment by Hypnosphi** [comment]
Let's close it once we document it

**Comment by StephanBijzitter** [comment]
Any chance the documentation could be added? I'm also running into this and even after reading the merged pull requests for presets I'm not quite sure what I'm expected to do.

**Comment by South-Paw** [comment]
I've added a `.storybook/babel.config.js` file with `module.exports = defaultConfig => defaultConfig;` but this doesn't seem to make a difference? Looks like stoyrbook is still using my projects root `.babelrc` file.

**Comment by Hypnosphi** [comment]
@South-Paw it was only an idea, the corresponding PR wasn't merged

I hope that @igor-dv can tell you how to do it with presets

**Comment by South-Paw** [comment]
I ended up fixing it by creating a separate .babelrc for storybook - seems to have solved it.

Commit: https://github.com/South-Paw/react-vector-maps/commit/ad04a18aba13b80347535ffb2597f6dc2e2d96f6

**Comment by oussamabouchareb** [comment]
for some odd reason using ```"@babel/preset-typescript"``` in my .babelrc made it fail, creating a new .babelrc file in .storybook folder with and putting all of my code from the other .babelrc I had and only removing ```"@babel/preset-typescript"``` fixed it

**Comment by ndelangen** [comment]
I'm planning to fix this one for 6.x:
https://github.com/storybookjs/storybook/issues/14425

But then we'll have to really figure out what we want to do for 7.0
There's a ton of issues relating to babel:
https://github.com/storybookjs/storybook/issues?q=is%3Aissue+is%3Aopen+babel+sort%3Acomments-desc

A lot of them is because in the past (and still to some degree) storybook mixes the babel config for the preview and manager.
I think we could simplify the preview's babel config to essentially no config at all, and have babel figure it out.

@shilman Perhaps we need some "babel config in 7.0" milestone, and discuss options?

**Comment by shilman** [comment]
Yee-haw!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-alpha.33 containing PR #15928 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by florianmartens** [comment]
@shilman for users not familiar with the source code, could you give a little more info about ignoring a root `.babelrc`. What would we need to do to (as the name of the issue) suggests "disable loading custom .babelrc". I was not able to figure this out from the PR alone.

**Comment by shilman** [comment]
@florianmartens did you already read the migration instructions? 

https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#babel-mode-v7

**Comment by TomFreudenberg** [comment]
Hi, I have just overload the loading function from storybook to prevent the default babel configuration from storybook and ignoring any local custom `.babelrc` files.

place this in front of __main.js__

```js
const l = require('@storybook/core-common/dist/cjs/utils/load-custom-babel-config');
// drop current implementation
delete l['loadCustomBabelConfig'];
// set new just return default config
l.loadCustomBabelConfig = async function (configDir, getDefaultConfig) {
  return getDefaultConfig();
};
```

then you can adjust plugins and preset in exports like:

```js
  babel: async (options) => {
    options.presets.push("next/babel");
    options.plugins.push("module/plugin");

    return options;
  },
```
