### ISSUE TITLE
[Bug]: Support bun as a package manager

### ISSUE THREAD

**Issue by valentinpalkovic** [storybookjs/storybook#28164]
### Describe the bug

Storybook supports npm, pnpm and yarn berry as package managers during installation, automigration, upgrade and startup. Adding support for Bun's package manager would be great since it allows a wide range of users to initialize, upgrade and automigrate Storybook in repositories using Bun as the package manager.

```[tasklist]
- [x] Implement a new `BunProxy`. Take a look, how, for example, the PNPMProxy was implemented (https://github.com/storybookjs/storybook/blob/next/code/lib/core-common/src/js-package-manager/PNPMProxy.ts)
- [x] Adjust the JsPackageManagerFactory.getPackageManager to return a new BunProxy (https://github.com/storybookjs/storybook/blob/next/code/lib/core-common/src/js-package-manager/JsPackageManagerFactory.ts#L24)
```

### Acceptance criteria

When Bun is used as a package manager, it should be possible to

- install Storybook
- upgrade Storybook
- run Storybook's automigrations
- run and build Storybook

**Comment by valentinpalkovic** [comment]
Any kind of help would be appreciated and I can give guidance and support if necessary!

**Comment by rhuanbarreto** [comment]
Thanks for pointing out the way! Will have a look at it tonight!

**Comment by lucadibello** [comment]
> Thanks for pointing out the way! Will have a look at it tonight!

If I can help in some way, let me know!

**Comment by rhuanbarreto** [comment]
My first findings:

My fork: https://github.com/storybookjs/storybook/compare/next...rhuanbarreto:storybook:next?expand=1

Bun doesn't support many json outputs for detecting package versions. Need to work more on this.

**Comment by luisalrp** [comment]
I don't now how, because i tried to use storybook myself into a nextjs bun boilerplate, but [midday](https://github.com/midday-ai/midday/tree/main/packages/ui) is staring to use storybook in their turborepo with bun and biome. I hope it helps some kind.

**Comment by RodrigoTomeES** [comment]
I recently have this error but I don't know why because I am using bun with storybook long time ago 😳

**Comment by valentinpalkovic** [comment]
@rhuanbarreto Does it make sense to ignore this limitation for now and just continue on the parts which bun supports? Maybe we can find alternative approaches to read a package version for example.

**Comment by rhuanbarreto** [comment]
@valentinpalkovic I'm trying to follow the interface Storybook gives me in order to do the parsing. For all other package managers, there's a json output where you can parse the values. The supported plain text output rather than the binary format is a yarn v1 plain text that needs it's own parser.

I'm not saying it's not possible. But for working as a package manager, this part of parsing the lockfile is an issue that increases the complexity. Just need effort to make it work.

Once bun itself in the near future will support a more parseable output (hence the linked issue here), I don't think it's worth the effort (for me) to make it work until this change.

**Comment by rhuanbarreto** [comment]
One more thing. Bun still doesn't support many of the commands that the other package managers have in order to peek into the dependency tree. Is this a blocker? No. But increases the level of complexity by some orders of magnitude. I think Bun also need to help introducing more package manager commands into their own software so this can be solved easily.

**Comment by stephenjason89** [comment]
> My first findings:
> 
> My fork: [`next...rhuanbarreto:storybook:next`?expand=1 (compare)](https://github.com/storybookjs/storybook/compare/next...rhuanbarreto:storybook:next?expand=1)
> 
> Bun doesn't support many json outputs for detecting package versions. Need to work more on this.

I think we can use npm info while bun info is not yet implemented. What do you think?

**Comment by stephenjason89** [comment]
> My first findings:
> 
> My fork: [`next...rhuanbarreto:storybook:next`?expand=1 (compare)](https://github.com/storybookjs/storybook/compare/next...rhuanbarreto:storybook:next?expand=1)
> 
> Bun doesn't support many json outputs for detecting package versions. Need to work more on this.

In the meantime, I think we could rely on `npm info` and `npm list` until Bun implements this feature. What are your thoughts?

**Comment by stephenjason89** [comment]
> My first findings:
> 
> My fork: [`next...rhuanbarreto:storybook:next`?expand=1 (compare)](https://github.com/storybookjs/storybook/compare/next...rhuanbarreto:storybook:next?expand=1)
> 
> Bun doesn't support many json outputs for detecting package versions. Need to work more on this.

In the meantime, I think we could rely on `npm info` and `npm list` until Bun implements this feature. What are your thoughts?

**Comment by yymm120** [comment]
I only hope to use storybook under the project managed by the bun. 
Is there any solution to achieve this, even if it's lame. 
Thanks.

**Comment by stephenjason89** [comment]
@valentinpalkovic @rhuanbarreto I went ahead and created a PR that would demonstrate what i meant on the previous comment.

**Comment by mimse** [comment]
I love to be able to use bun with storybook, so if this could be fixed for the next release I would be so grateful :heart:

**Comment by Donal2** [comment]
Hi team, any update on this?

**Comment by nhhockeyplayer** [comment]
angular NX storybook projects are affected as well

is storybook failing or can we ignore this log message

```
nx storybook shared-root-ui-widget             

> nx run shared-root-ui-widget:storybook

Storybook failed to check addon compatibility Error: Unable to find a usable package manager within NPM, PNPM, Yarn and Yarn 2
    at JsPackageManagerFactory.getPackageManager (/Users/meanstack02/meanstacknh/node_modules/@storybook/core/dist/common/index.cjs:143260:11)
    at getIncompatibleStorybookPackages (/Users/meanstack02/meanstacknh/node_modules/@storybook/core/dist/core-server/index.cjs:48358:58)
    at warnOnIncompatibleAddons (/Users/meanstack02/meanstacknh/node_modules/@storybook/core/dist/core-server/index.cjs:48391:17)
    at buildDevStandalone (/Users/meanstack02/meanstacknh/node_modules/@storybook/core/dist/core-server/index.cjs:48465:11)
    at async withTelemetry (/Users/meanstack02/meanstacknh/node_modules/@storybook/core/dist/core-server/index.cjs:47080:12)
info => Starting manager..
info => Starting preview..
info Addon-docs: using MDX3
info => Using implicit CSS loaders
info => Using angular browser target options from "shared-root-ui-widget:build-storybook"
info => Using angular project with "tsConfig:/Users/meanstack02/meanstacknh/libs/shared/root/ui-widget/.storybook/tsconfig.json"
info => Using default Webpack5 setup
<i> [webpack-dev-middleware] wait until bundle finished
WARN /Users/meanstack02/meanstacknh/libs/shared/root/ui-widget/.storybook/main.ts is part of the TypeScript compilation but it's unused.
WARN Add only entry points to the 'files' or 'include' properties in your tsconfig.
WARN DefinePlugin

```

**Comment by nhhockeyplayer** [comment]
WARN Conflicting values for 'process.env.NODE_ENV'

**Comment by IEdiong** [comment]
@valentinpalkovic Is this still open?

**Comment by lritter79** [comment]
Are there currently any plans for Storybook to support Bun?

**Comment by valentinpalkovic** [comment]
[This PR](https://github.com/storybookjs/storybook/pull/29267) actually looks pretty promising.

I have tested:
- `init` in a vue3 project
- `upgrade` from 8.4.0-beta.0 to 0.0.0-pr-29267-sha-1523974d
- `add` command to add @storybook/experimental-addon-test, which also was able to remove @storybook/addon-interactions

Please feel free to test out the canary release: `0.0.0-pr-29267-sha-1523974d`.

I have even tested running Storybook via the bun runtime, and both the `dev` and `build` commands worked successfully in a vue3 example project. 

It is likely that we will introduce bun package manager support and bun runtime support in Storybook 8.5.

Please check out the PR above and try out the canary release. Let us know if things are still buggy.

**Comment by stephenjason89** [comment]
> [This PR](https://github.com/storybookjs/storybook/pull/29267) actually looks pretty promising. It is a community PR which I have continued on and finalized.
> 
> I have tested:
> - `init` in a vue3 project
> - `upgrade` from 8.4.0-beta.0 to 0.0.0-pr-29267-sha-1523974d
> - `add` command to add a Storybook addon
> 
> Please feel free to test out the canary release: `0.0.0-pr-29267-sha-1523974d`.
> 
> I have even tested running Storybook via the bun runtime, and both the `dev` and `build` commands worked successfully in a vue3 example project. 
> 
> It is likely that we will introduce bun package manager support and bun runtime support in Storybook 8.5.
> 
> Please check out the PR above and try out the canary release. Let us know if things are still buggy.

Awesome! I’ll give the canary release a spin with bun on my Nuxt 3 project. Excited for bun support in Storybook 8.5—let’s see if it’s smooth sailing! Thanks for the update! 🚀

**Comment by melMass** [comment]
@valentinpalkovic Awesome!
I'm not sure how to properly test it though?

Using `bun add storybookjs/storybook#pull/29267/head` works fine.

But `bunx storybookjs/storybook#pull/29267/head init` still spits: `error: could not determine executable to run for package`

I honestly dislike init scripts most of the time but I couldn't find any manual instructions on sb's website

**Comment by valentinpalkovic** [comment]
Could you try out `bun add storybook@0.0.0-pr-29267-sha-1523974d`, `bunx storybook@0.0.0-pr-29267-sha-1523974d init` and `bunx storybook/0.0.0-pr-29267-sha-1523974d init --package-manager=bun` instead?

I haven't tried to `init` in an empty directory so far, but only into an existing project.

**Comment by melMass** [comment]
It works thanks! I figured since that my approach was resolving to `@storybook/root` or something like that.
So yes I could properly bootstrap sb on an existing svelte kit project (using svelte 5).
There is one small issue still, it doesn't properly understand [bun's workspace dependency as declared in monorepos](https://bun.sh/docs/install/workspaces) (**TLDR**: they use `workspace:*`):

<img width=480 src="https://github.com/user-attachments/assets/6bca80ef-5384-4996-806d-9eae4a5e5aca"/>

**Comment by valentinpalkovic** [comment]
@melMass The problem is rather that it detects `yarn` as being the package manager, instead of bun. Do you have a bun lock file in the project? If you use `bunx` instead of `npx` or `yarn dlx`, we still try to detect your package manager by searching for lock files. You can enforce a certain package manager by appending `--package-manager=bun` to the init command.

**Comment by melMass** [comment]
Oh yes good catch!
It's because I use bun's [fallback](https://bun.sh/docs/install/lockfile) since their lock file is binary

**Comment by darklight9811** [comment]
@valentinpalkovic tried enforcing with `--package-manager=bun` but still tries to run npm

![Image](https://github.com/user-attachments/assets/494832a8-b38f-45fc-b66d-dbb942205d0a)

**Comment by valentinpalkovic** [comment]
Hi @darklight9811 

A closed issue doesn’t necessarily mean that it is already part of the latest stable release. We close issues automatically as soon as the related PR is merged. You can see [here](https://github.com/storybookjs/storybook/pull/29508) that it is part of the latest pre-release. Therefore, please try to run `npx storybook@ 8.5.0-alpha.2 init` instead.
