### ISSUE TITLE
Controls: Add option to disable "save from controls"

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#28377]
### Discussed in https://github.com/storybookjs/storybook/discussions/27219

<div type='discussions-op-text'>

<sup>Originally posted by **MichaelAllenWarner** May 22, 2024</sup>
### Summary

The new feature for [creating and editing stories from controls](https://storybook.js.org/docs/essentials/controls#creating-and-editing-stories-from-controls) is great, but with my (idiosyncratic) setup it doesn't work, and I'd like to disable it since it just gets in the way. Is there a way to prevent that "You modified this story..." popup from appearing altogether when I use the Controls?

### Create a reproduction

_No response_</div>

**Comment by shilman** [comment]
Proposal:

```js
// .storybook/preview.js
export default {
  parameters: {
    controls: {
      disableSave: true
    }
  }
}
```

**Comment by ghengeveld** [comment]
Alternate proposal:
```js
// .storybook/main.js
const config = {
  addons: [
    {
      name: "@storybook/addon-essentials",
      options: {
        saveFromControls: false
      },
    },
  ],
};
```

**Comment by woutervanvliet** [comment]
Would very much like to see this get implemented

**Comment by cijokb** [comment]
Any update on this ?

**Comment by kartik1112** [comment]
Can I start to work on this ?

**Comment by Tainmat** [comment]
The option called 'disableSaveFromUI'.

```ts
import { Preview } from '@storybook/react'

import { decorators } from './decorators'

const preview: Preview = {
  decorators: decorators,
  parameters: {
    controls: { expanded: true, disableSaveFromUI: true },
    options: {
      storySort: {
        order: [
          'Getting Started',
          ['Introdução', 'Instalação', 'Visão Geral'],
          'Tokens',
          ['Tema', 'Cores'],
          'Tipografia',
          ['Fontes', 'Caption', 'Body', 'Heading']
        ]
      }
    }
  }
}

export default preview
```

**Comment by yairEO** [comment]
@Tainmat - please could you properly format your comment?

**Comment by OsmanYavuzOlgun** [comment]
Can i change the attribute of that button? I have **Buttons do not have an accessible name** a11y issue in that button right now, and i can not control that button.

**Comment by ghengeveld** [comment]
@OsmanYavuzOlgun What button are you referring to exactly? As far as I can tell, all buttons in [that component](https://github.com/storybookjs/storybook/blob/b31600277eac4d3e984b54aa696185f1a1f26821/code/core/src/controls/components/SaveStory.tsx#L154) have either a regular button label or an aria-label attribute.

Update: I dug a little deeper and found that the Close button on the dialog is missing an ARIA label. I'll add that.

**Comment by OsmanYavuzOlgun** [comment]
@ghengeveld  The create new story button (first image) has that a11y issue. You can see the a11y issue in second image, and i can not add aria-label or customize it. 

1)
![Image](https://github.com/user-attachments/assets/e316cdcf-e74d-449a-b5c9-51fe7800d6c4) 

2)
![Image](https://github.com/user-attachments/assets/4fa8964c-5d61-4ceb-bfd7-d5143a63be83)

**Comment by ghengeveld** [comment]
@OsmanYavuzOlgun I'm addressing it [here](https://github.com/storybookjs/storybook/pull/31870).

**Comment by OsmanYavuzOlgun** [comment]
Thank u for that. Have a nice day.
