### ISSUE TITLE
[Bug]: Editing Story: Lost connection to the Storybook server

### ISSUE THREAD

**Issue by ngrippa** [storybookjs/storybook#28381]
### Describe the bug

Whenever I edit a story or create a new one the storybook sever crashes.
This happens on an empty project after running `npx storybook@latest init ` selecting Vue3 + Vite (TS)
This sadly only happens on my machine (Win 11) and I can not reproduce it on Stackblitz.

### Reproduction link

https://stackblitz.com/edit/vitejs-vite-yvbiws?file=package.json

### Reproduction steps

1. Create empty Folder and `cd` into it
2. `npx storybook@latest init`
3. Select Vue3 + Vite (TS)
4. When ready, click on Button->primary
5. Edit the label
6. Save the story
7. The message "Lost connection to the Storybook server" appears
8. The console shows no errors or any other kind of information
9. When reloading the browser the page reloads indefinetly -> The Dev Server has crashed without any output

### System

```bash
Storybook Environment Info:

  System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 13th Gen Intel(R) Core(TM) i7-1365U
  Binaries:
    Node: 20.13.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD <----- active
  Browsers:
    Edge: Chromium (126.0.2592.68)
  npmPackages:
    @storybook/addon-essentials: ^8.1.11 => 8.1.11
    @storybook/addon-interactions: ^8.1.11 => 8.1.11
    @storybook/addon-links: ^8.1.11 => 8.1.11
    @storybook/blocks: ^8.1.11 => 8.1.11
    @storybook/test: ^8.1.11 => 8.1.11
    @storybook/vue3: ^8.1.11 => 8.1.11
    @storybook/vue3-vite: ^8.1.11 => 8.1.11
    storybook: ^8.1.11 => 8.1.11
```

**Comment by vanessayuenn** [comment]
@ngrippa this is fixed by https://github.com/storybookjs/storybook/pull/28485. Please try this on the latest 8.2!

**Comment by ngrippa** [comment]
@vanessayuenn Yes, thanks. The issue is fixed in version `8.2`.

**Comment by luc-marongiu** [comment]
Not fix in 8.3.2. 

I upgrade from 8.0.10 to 8.3.2 and this problem appears.

**Comment by chetan-sonawane** [comment]
I have 8.4.6 still facing same error

**Comment by brupelo** [comment]
I can confirm this crash happens very often on windows with latest ones

```
"@chromatic-com/storybook": "3.2.3",
"@storybook/addon-essentials": "8.4.7",
"@storybook/addon-interactions": "8.4.7",
"@storybook/addon-links": "8.4.7",
"@storybook/manager-api": "8.4.7",
"@storybook/node-logger": "8.4.7",
"@storybook/react": "8.4.7",
"@storybook/react-vite": "8.4.7",
"@storybook/test": "8.4.7",
"@storybook/test-runner": "0.21.0",
"eslint-plugin-storybook": "0.11.1",
"storybook": "8.4.7",
```
