### ISSUE TITLE
CI Flake: BootstrapQueue.test.ts

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#28439]
Code:
https://github.com/storybookjs/storybook/blob/next/code/frameworks/angular/src/client/angular-beta/utils/BootstrapQueue.test.ts

Flake:
https://app.circleci.com/pipelines/github/storybookjs/storybook/79402/workflows/dc88f162-574a-432d-a936-848fb9fe8c07/jobs/676408

**Comment by kasperpeulen** [comment]
Not flaky anymore

**Comment by vanessayuenn** [comment]
Still flakey: https://app.circleci.com/pipelines/github/storybookjs/storybook/82380/workflows/71848b95-5f53-4572-9eec-9764c25595a5/jobs/695419
