### ISSUE TITLE
[Bug]: Conditional babel config such as include and exclude is ignored in @storybook/next

### ISSUE THREAD

**Issue by kasperpeulen** [storybookjs/storybook#28467]
### Describe the bug

If I have a babel config in next that uses conditional config such as `include` or `exclude`, than those lines get always matched to `[root]/__fake__.js`

This is happening in those lines:
https://github.com/storybookjs/storybook/blob/3a1e61cefec8dfd350d42db5598b2d0d9159a878/code/frameworks/nextjs/src/preset.ts#L59-L69

### Reproduction link

https://stackblitz.com/edit/github-iecdof?file=babel.config.js

### Reproduction steps

1. Open the button story.
2. See in the console that async/await is transpiled, even though I override the babel-env to be modern.

### System

```bash
See stackblitz
```

**Comment by chidiebereojingwa** [comment]
Can I work on this?

**Comment by kasperpeulen** [comment]
@chidiebereojingwa Sure!
