### ISSUE TITLE
[Bug]: Type error in @storybook/react 8.2.0

### ISSUE THREAD

**Issue by mrginglymus** [storybookjs/storybook#28500]
### Describe the bug

Distribtued file `@storybook/react/dist/index.d.ts` contains on line 6

```ts
import * as core_dist_types from 'core/dist/types';
```

which cannot be resolved - this is presumably an issue in compilation, but it is causing type errors.

### Reproduction link

https://new-storybook.netlify.app/

### System

```bash
Storybook Environment Info:

  System:
    OS: Windows 10 10.0.19045
    CPU: (24) x64 Intel(R) Core(TM) i9-10920X CPU @ 3.50GHz
  Binaries:
    Node: 20.13.1 - 
    Yarn: 4.3.1 -  <----- active
    npm: 10.5.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (126.0.2592.87)
```

**Comment by valentinpalkovic** [comment]
Thanks for reporting that quickly!

We are looking into it right now :)

**Comment by mrginglymus** [comment]
Amazing thanks for the quick turnaround.
