### ISSUE TITLE
[Bug]: We cannot build storybook 7.6.10 anymore

### ISSUE THREAD

**Issue by DarkDynamite** [storybookjs/storybook#28502]
### Describe the bug

Since one hour our Storybook in version 7.6.10 is not buildable anymore. 

Have you some issues with your dependencies?

Logs:

[2024-07-10T08_57_45_205Z-eresolve-report.txt](https://github.com/user-attachments/files/16158465/2024-07-10T08_57_45_205Z-eresolve-report.txt)
[2024-07-10T08_57_45_205Z-debug-0.log](https://github.com/user-attachments/files/16158472/2024-07-10T08_57_45_205Z-debug-0.log)

### Reproduction link

https://storybook.new

### Reproduction steps

Reproduction with Azure Pipeline:

```
  - script: |
      npm install -g @angular/cli
      npm install
    displayName: "Install NPM dependencies"
```

Reproduction locally:

`npm install`

### System

```bash
ubuntu, mac os
```

**Comment by yannbf** [comment]
Hey @DarkDynamite we just released a new version of Storybook, but that's not the issue. The problem you reported is coming from how the peer dependency range of `storybook-zeplin` addon is set (based on your log file):

```
Could not resolve dependency:
peer storybook@"^8.2.0" from @storybook/components@8.2.0
node_modules/@storybook/components
  peer @storybook/components@">=5.0.0" from storybook-zeplin@2.0.2
  node_modules/storybook-zeplin
    dev storybook-zeplin@"2.0.2" from the root project
```

You probably cleared your lockfile and that caused the issue. To fix it, either install `@storybook/components@^7.6.10` in your project, or add a package resolution to that version.

**Comment by DarkDynamite** [comment]
Thanks for your help.

Adding the following packages to devDependencies did the trick:

```
"@storybook/components": "7.6.10",
"@storybook/theming": "7.6.10",
```
