### ISSUE TITLE
[Bug]: Type inference of args from argTypes is not working

### ISSUE THREAD

**Issue by nklhtv** [storybookjs/storybook#28522]
### Describe the bug

i got a type error in `args`
Type '"https://avatars.githubusercontent.com/u/1"' is not assignable to type '"string"'.ts(2322)
when i use something like:
```
  argTypes: {
    src: {
      control: 'text',
      description: 'URL of the image',
    },
  },
  args: {
    src: 'https://avatars.githubusercontent.com/u/1',
  },
```

### Reproduction link

https://stackblitz.com/edit/github-fxncpc-sqj2tj

### Reproduction steps

1. Go to above link
2. Go to Image.stories.tsx
3. See the type error in `args.src`

### System

```bash
Storybook Environment Info:

  System:
    OS: macOS 14.4.1
    CPU: (10) arm64 Apple M1 Pro
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v20.9.0/bin/yarn
    npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm <----- active
    pnpm: 9.4.0 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 126.0.6478.127
    Safari: 17.4.1
```

### Additional context

Temporarly i use the following workaround:
```
  args: {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    src: "https://avatars.githubusercontent.com/u/1" as any,
  },
```

**Comment by ndelangen** [comment]
I have a solution here:
https://stackblitz.com/edit/github-fxncpc-z6wmbz?file=src%2Fstories%2FImage.stories.tsx

Before:
```tsx
const meta: Meta<{ src: 'string' }> = {
```

After:
```tsx
const meta: Meta<{ src: string }> = {
```
