### ISSUE TITLE
[Bug]: install failed

### ISSUE THREAD

**Issue by Mr-Ao-Dragon** [storybookjs/storybook#28523]
### Describe the bug

plase check Reproduction steps

### Reproduction link

https://asciinema.org/a/GyWvIbZyFBEXrPyVtEAJMdKp7

### Reproduction steps

[![asciicast](https://asciinema.org/a/GyWvIbZyFBEXrPyVtEAJMdKp7.svg)](https://asciinema.org/a/GyWvIbZyFBEXrPyVtEAJMdKp7)

### System

```bash
Storybook Environment Info:

  System:
    OS: Windows 11 10.0.26120
    CPU: (16) x64 AMD Ryzen 7 8845H w/ Radeon 780M Graphics
  Binaries:
    Node: 22.1.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD <----- active
  Browsers:
    Edge: Chromium (127.0.2651.8)
```

**Comment by vanessayuenn** [comment]
hello @Mr-Ao-Dragon thanks for opening the issue. However, we cannot investigate this without a valid reproduction. 
Can you please create one via [storybook.new](https://new-storybook.netlify.app/), or link to a repo where this issue happens? We prioritize bug reports that have reproduction. Thank you! 🙏

**Comment by ndelangen** [comment]
Please try the very latest release: `8.2.1`.
This issue should be resolved on that version.
