### ISSUE TITLE
[Bug]: /virtual:/@storybook/builder-vite/setup-addons.js" points to missing source files

### ISSUE THREAD

**Issue by valentinpalkovic** [storybookjs/storybook#28567]
### Describe the bug

When starting or building Storybook in a Vite project, the following lines are logged to the terminal:

```
Sourcemap for "/virtual:/@storybook/builder-vite/setup-addons.js" points to missing source files
Sourcemap for "/virtual:/@storybook/builder-vite/vite-app.js" points to missing source files
```

In Vite 4 projects, even more files might be affected.

### Reproduction steps

1. Initialize Storybook in a Vite Project
2. Start Storybook

**Comment by kerryj89** [comment]
Upgraded from `8.0.4` to `8.2.4` today and am now running into this issue.

I am guessing this is what's causing my `parameters.docs.source.transform`'s `code` parameter to be undefined and basically error out with the following in any of my component's docs page:

![capture-2024-07-15-xxQUTgge](https://github.com/user-attachments/assets/9f3a6366-a125-41b0-8678-7f8374dfef60)

**Comment by Loic57** [comment]
More or less the same, we did an update form 8.0.8 to 8.2.4 and we have 
```Sourcemap for "/virtual:/@storybook/builder-vite/setup-addons.js" points to missing source files
Sourcemap for "/virtual:/@storybook/builder-vite/vite-app.js" points to missing source files```

Plus, the HMR doesn't work anymore, no error message but any update done in Stencil doesn't refresh the page. We go back to 8.0.8 for now

```    framework: {
        name: getAbsolutePath("@storybook/react-vite")
    },```

**Comment by valentinpalkovic** [comment]
@Loic57 Can you create another GitHub issue related to your HMR issue in Stencil?

**Comment by valentinpalkovic** [comment]
@kerryj89 I don't think your issue is related to the issue of missing source files. Can you please create another GitHub issue?

**Comment by David05500** [comment]
I was facing the same issue today after upgrading to 8.2.4
Sourcemap for "/virtual:/@storybook/builder-vite/setup-addons.js" points to missing source files
Sourcemap for "/virtual:/@storybook/builder-vite/vite-app.js" points to missing source files

So Ive downgraded back to 7.6.20

**Comment by valentinpalkovic** [comment]
@David05500 Except of having a nasty warning in the terminal Storybook should still function. I wouldn’t recommend to downgrade just because of it. You could upgrade to 8.1.11. This version is not containing the issue.

**Comment by phamhongphuc** [comment]
I also got the same error. 

**Reproduction steps:**
- 1. `yarn create vue`
- 2. `yarn dlx storybook init`

**Reproduction repo:**
https://github.com/issue-reproduction/vue-vite-storybook-issue/tree/yarn/nodeLinker-node-modules

```
"vue": "^3.4.31",
"storybook": "^8.2.4",
"vite": "^5.3.4",
"@vitejs/plugin-vue": "^5.0.5"
```

**Full log:**

<details><summary><b><code>yarn storybook dev -p 6006</code></b></summary>
<p>

```log
D:\Code\issue\vue-vite-storybook-issue>yarn storybook dev -p 6006
storybook v8.2.4

info => Starting manager..
info => Starting preview..
╭───────────────────────────────────────────────────╮
│                                                   │
│   Storybook 8.2.4 for vue3-vite started           │
│   411 ms for manager and 672 ms for preview       │
│                                                   │
│    Local:            http://localhost:6006/       │
│    On your network:  http://192.168.1.20:6006/    │
│                                                   │
╰───────────────────────────────────────────────────╯
Sourcemap for "/virtual:/@storybook/builder-vite/setup-addons.js" points to missing source files
Sourcemap for "/virtual:/@storybook/builder-vite/vite-app.js" points to missing source files
```

</p>
</details> 

<details><summary><b><code>yarn storybook build</code></b></summary>
<p>

```log
D:\Code\issue\vue-vite-storybook-issue>yarn storybook build
storybook v8.2.4

info => Cleaning outputDir: storybook-static
info => Loading presets
info => Building manager..
info => Manager built (221 ms)
info => Building preview..
vite v5.3.4 building for production...
node_modules/telejson/dist/index.mjs (1413:15): Use of eval in "node_modules/telejson/dist/index.mjs" is strongly discouraged as it poses security risks and may cause issues with minification.
node_modules/telejson/dist/index.mjs (1416:18): Use of eval in "node_modules/telejson/dist/index.mjs" is strongly discouraged as it poses security risks and may cause issues with minification.
node_modules/@storybook/vue3/dist/entry-preview-docs.mjs (9:1345): Use of eval in "node_modules/@storybook/vue3/dist/entry-preview-docs.mjs" is strongly discouraged as it poses security risks and may cause issues with minification.
✓ 497 modules transformed.
storybook-static/assets/context-C0qIqeS4.png                   6.12 kB
storybook-static/assets/styling-Bk6zjRzU.png                   7.24 kB
storybook-static/iframe.html                                  16.36 kB │ gzip:   4.44 kB
storybook-static/assets/docs---vsFbMi.png                     27.88 kB
storybook-static/assets/share-DGA-UcQf.png                    40.77 kB
storybook-static/assets/accessibility-W_h2acOZ.png            42.34 kB
storybook-static/assets/figma-plugin-CH2hELiO.png             44.25 kB
storybook-static/assets/theming-D6WJLNoW.png                  44.37 kB
storybook-static/assets/testing-cbzR9l9r.png                  49.31 kB
storybook-static/assets/addon-library-BWUCAmyN.png           467.37 kB
storybook-static/assets/Header-BjLH3naM.css                    0.51 kB │ gzip:   0.30 kB
storybook-static/assets/Button-BfyGbg8N.css                    0.52 kB │ gzip:   0.29 kB
storybook-static/assets/Page-B9ntr4df.css                      0.93 kB │ gzip:   0.40 kB
storybook-static/assets/preview-BnWGZYux.js                    0.07 kB │ gzip:   0.08 kB
storybook-static/assets/preview-CIRcjyVj.js                    0.11 kB │ gzip:   0.11 kB
storybook-static/assets/preview-DE7p7AzZ.js                    0.16 kB │ gzip:   0.16 kB
storybook-static/assets/index-BoSSb2R6.js                      0.26 kB │ gzip:   0.18 kB
storybook-static/assets/index-CjvHkRZd.js                      0.39 kB │ gzip:   0.26 kB
storybook-static/assets/preview-BJPLiuSt.js                    0.64 kB │ gzip:   0.45 kB
storybook-static/assets/preview-BpcF_O6y.js                    0.71 kB │ gzip:   0.50 kB
storybook-static/assets/index-DrFu-skq.js                      0.77 kB │ gzip:   0.47 kB
storybook-static/assets/preview-2enRuHIs.js                    0.77 kB │ gzip:   0.50 kB
storybook-static/assets/Header.stories-BGlEp0Gs.js             1.02 kB │ gzip:   0.52 kB
storybook-static/assets/Button.stories-C57JHs79.js             1.56 kB │ gzip:   0.58 kB
storybook-static/assets/Header-DHOsF23d.js                     1.60 kB │ gzip:   0.89 kB
storybook-static/assets/index-Dym7vi56.js                      1.68 kB │ gzip:   0.85 kB
storybook-static/assets/DocsRenderer-PKQXORMH-DOdF88mr.js      1.78 kB │ gzip:   0.88 kB
storybook-static/assets/entry-preview-DM95eRMn.js              2.33 kB │ gzip:   1.25 kB
storybook-static/assets/index-D-8MO0q_.js                      2.58 kB │ gzip:   1.26 kB
storybook-static/assets/preview-9hFJSo5S.js                    3.20 kB │ gzip:   1.38 kB
storybook-static/assets/preview-Ct5NkTJf.js                    3.50 kB │ gzip:   1.69 kB
storybook-static/assets/Page.stories-Dks3FqcD.js               3.54 kB │ gzip:   1.68 kB
storybook-static/assets/iframe-Dly9Xvin.js                     4.54 kB │ gzip:   1.82 kB
storybook-static/assets/preview-DB9FwMii.js                    7.62 kB │ gzip:   1.56 kB
storybook-static/assets/preview-Cdum89jS.js                    8.12 kB │ gzip:   3.10 kB
storybook-static/assets/entry-preview-docs-xQ1Zq6ry.js        14.89 kB │ gzip:   5.81 kB
storybook-static/assets/Configure-CYEWVRpQ.js                 26.65 kB │ gzip:  11.53 kB
storybook-static/assets/Color-KGDBMAHA-NqxdIwus.js            30.80 kB │ gzip:  11.70 kB
storybook-static/assets/index-DZLKizrv.js                     61.57 kB │ gzip:  21.47 kB
storybook-static/assets/index-TAVom-gR.js                     80.58 kB │ gzip:  23.98 kB
storybook-static/assets/vue.esm-bundler-CMiB1aF2.js          156.87 kB │ gzip:  58.77 kB
storybook-static/assets/Button-BQ2yOadR.js                   642.77 kB │ gzip: 148.44 kB
storybook-static/assets/index-C8IehePe.js                  1,023.04 kB │ gzip: 325.85 kB

(!) Some chunks are larger than 500 kB after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/configuration-options/#output-manualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
✓ built in 6.28s
info => Preview built (6.91 s)
info => Output directory: D:\Code\issue\vue-vite-storybook-issue\storybook-static
```

</p>
</details>

**Comment by heyflo** [comment]
> @David05500 Except of having a nasty warning in the terminal Storybook should still function. I wouldn’t recommend to downgrade just because of it. You could upgrade to 8.1.11. This version is not containing the issue.

This is causing some addons to break or not function properly so we have to downgrade in the meantime. Thanks for pointing out a version that doesn't break 👍, I went back to the 8.1.11.

**Comment by psychobolt** [comment]
I have similar issue, but on Yarn 4 PnP and Storybook Vite 8.2.5. Is there a reason why source maps are enabled by default? How can we turn off for performance reasons? Changing the setting in vite configs has no effect.

**Comment by shilman** [comment]
@valentinpalkovic Do you know what's causing this?

**Comment by valentinpalkovic** [comment]
Not yet! I can investigate it next week as part of my empathy week!

**Comment by Labastidaa** [comment]
I encountered the same logs. Meanwhile I guess downgrading is the fix,  handling the storybooks/addons compatibility will be a struggle I guess.

**Comment by jkananen** [comment]
> Except of having a nasty warning in the terminal Storybook should still function.

I don't see any functional issues even though the warning appears in the terminal.

Has anyone encountered any actual failures anywhere?

My deps now:
```
"@storybook/addon-a11y": "^8.2.5",
"@storybook/addon-docs": "^8.2.5",
"@storybook/addon-essentials": "^8.2.5",
"@storybook/addon-interactions": "^8.2.5",
"@storybook/addon-links": "^8.2.5",
"@storybook/react": "^8.2.5",
"@storybook/react-vite": "^8.2.5",
"@storybook/test": "^8.2.5",
"@storybook/test-runner": "^0.19.1",
"storybook": "^8.2.5",
```

**Comment by omer-priel** [comment]
Any update on this?

I use storybook 8.2.7 with a new react (with vite) project and it also appears to me:
```txt
Sourcemap for "/virtual:/@storybook/builder-vite/setup-addons.js" points to missing source files
Sourcemap for "/virtual:/@storybook/builder-vite/vite-app.js" points to missing source files
```

**Comment by 7michele7** [comment]
I'm getting the same errors, with Storybook `8.2.7` (+ vite):

```
Sourcemap for "/virtual:/@storybook/builder-vite/setup-addons.js" points to missing source files
Sourcemap for "/virtual:/@storybook/builder-vite/vite-app.js" points to missing source files

Sourcemap for "project-name/node_modules/.cache/storybook/1c3385a5d25e538d10b518b310c74d3ca2690b6aaffeadccd74da79736171f86/sb-vite/deps/chunk-JT2S5XWW.js" points to missing source files
Sourcemap for "project-name/node_modules/.cache/storybook/1c3385a5d25e538d10b518b310c74d3ca2690b6aaffeadccd74da79736171f86/sb-vite/deps/chunk-G4IBRLZB.js" points to missing source files
Sourcemap for "project-name/node_modules/.cache/storybook/1c3385a5d25e538d10b518b310c74d3ca2690b6aaffeadccd74da79736171f86/sb-vite/deps/chunk-Q3AQ5QX7.js" points to missing source files
Sourcemap for "project-name/node_modules/.cache/storybook/1c3385a5d25e538d10b518b310c74d3ca2690b6aaffeadccd74da79736171f86/sb-vite/deps/chunk-H34TB425.js" points to missing source files
Sourcemap for "project-name/node_modules/.cache/storybook/1c3385a5d25e538d10b518b310c74d3ca2690b6aaffeadccd74da79736171f86/sb-vite/deps/chunk-JO3NLJMA.js" points to missing source files
Sourcemap for "project-name/node_modules/.cache/storybook/1c3385a5d25e538d10b518b310c74d3ca2690b6aaffeadccd74da79736171f86/sb-vite/deps/chunk-IMALHOV3.js" points to missing source files
Sourcemap for "project-name/node_modules/.cache/storybook/1c3385a5d25e538d10b518b310c74d3ca2690b6aaffeadccd74da79736171f86/sb-vite/deps/chunk-G2BJXQAJ.js" points to missing source files
Sourcemap for "project-name/node_modules/.cache/storybook/1c3385a5d25e538d10b518b310c74d3ca2690b6aaffeadccd74da79736171f86/sb-vite/deps/chunk-LPRKOUG3.js" points to missing source files
```

**Comment by sachinlala** [comment]
Same for me, while upgrading to `8.2.7` (react + vite):

<img width="981" alt="image" src="https://github.com/user-attachments/assets/f37d55e3-3d06-4622-bb30-735213e9da45">

Please advise.

**Comment by phamhongphuc** [comment]
> Same for me, while upgrading to `8.2.7` (react + vite):
> 
> <img alt="image" width="981" src="https://private-user-images.githubusercontent.com/20021459/354788600-f37d55e3-3d06-4622-bb30-735213e9da45.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2NTg5NzYsIm5iZiI6MTcyMjY1ODY3NiwicGF0aCI6Ii8yMDAyMTQ1OS8zNTQ3ODg2MDAtZjM3ZDU1ZTMtM2QwNi00NjIyLWJiMzAtNzM1MjEzZTlkYTQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAzVDA0MTc1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkYTM0Y2MyY2NhNDNhMTI0YzRmOTY0Y2RiNTFhYjA0OGExZjJhNGI0NWEyNmQ1NzEwZTU5MzczM2E2NzJjOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TJrhQR2lqyOAyMXNCYgPXJeqYZTqLiIJAwm9NY-YuH8">
> Please advise.

This looks more like a different bug.

**Comment by sachinlala** [comment]
> > Same for me, while upgrading to `8.2.7` (react + vite):
> > <img alt="image" width="981" src="https://private-user-images.githubusercontent.com/20021459/354788600-f37d55e3-3d06-4622-bb30-735213e9da45.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2NTg5NzYsIm5iZiI6MTcyMjY1ODY3NiwicGF0aCI6Ii8yMDAyMTQ1OS8zNTQ3ODg2MDAtZjM3ZDU1ZTMtM2QwNi00NjIyLWJiMzAtNzM1MjEzZTlkYTQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAzVDA0MTc1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkYTM0Y2MyY2NhNDNhMTI0YzRmOTY0Y2RiNTFhYjA0OGExZjJhNGI0NWEyNmQ1NzEwZTU5MzczM2E2NzJjOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TJrhQR2lqyOAyMXNCYgPXJeqYZTqLiIJAwm9NY-YuH8">
> > Please advise.
> 
> This looks more like a different bug.

This is same, hence I reached out - 
> Sourcemap for "/virtual:/@storybook/builder-vite/setup-addons.js" points to missing source files

**Comment by noelparisi** [comment]
I also am experiencing:

```
Sourcemap for "/virtual:/@storybook/builder-vite/setup-addons.js" points to missing source files
Sourcemap for "/virtual:/@storybook/builder-vite/vite-app.js" points to missing source files
```

In addition, HMR is not working.  I am on Vite 5.3.5, storybook 8.2.7 (in react).

**Comment by Walnussbaer** [comment]
I can confirm this bug in a Vue + Vite + Storybook project. I just upgraded to Storybook 8.2.7 from Storybook 7.

**Comment by Walnussbaer** [comment]
Does anyone else here have problem with autodocs not shoing up the table for props, emits and so on?

I'm starting to think that this warning in the console has something to do with autodocs pages bascially being empty. Only the args that I define for a story are shown as well as their controls. But If I don't define any args explicitly, the autodocs page is basically empty and thus uselesse.

**Comment by Walnussbaer** [comment]
> > Does anyone else here have problem with autodocs not shoing up the table for props, emits and so on?
> > I'm starting to think that this warning in the console has something to do with autodocs pages bascially being empty. Only the args that I define for a story are shown as well as their controls. But If I don't define any args explicitly, the autodocs page is basically empty and thus uselesse.
> 
> @Walnussbaer For me, it's not related to this issue.
> 
> Try with the version 8.1 of storybook, if you have also the autodocs problem, looks at the new vue docgen option in >= 8.0 : https://storybook.js.org/docs/get-started/frameworks/vue3-vite?renderer=vue#using-vue-component-meta
> 
> ```diff
>     options: {
> +      docgen: 'vue-component-meta',
>     },
> ```

I downgraded to 8.1.11 but still no meaningful autodocs page (I was already using `vue-component-meta`). I can see the componente but the controls are still missing. I will open my own bug ticket, because I don't want to conquer this one here. Thanks anyway for your suggestion to try 8.1 :)

**Comment by Walnussbaer** [comment]
BTW: I created a sandbox project with the Storybook CLI (`npx storybook@8.2.7 sandbox vue`).

When I start the storybook instance in this new project, even then I get the following errors:

```
Sourcemap for "/virtual:/@storybook/builder-vite/setup-addons.js" points to missing source files
Sourcemap for "/virtual:/@storybook/builder-vite/vite-app.js" points to missing source files
```

**Comment by Bielousov** [comment]
Still an issue, v8.2.9

**Comment by messenjer** [comment]
> I can confirm that issue still persist with storybook v8.2.9 and Vite + react.

Yes, the fix of the issue was reverted, and it's still in progress for the next 8.3 : https://github.com/storybookjs/storybook/pull/28867

**Comment by doppelmutzi** [comment]
I'm experiencing the same issue with Storybook 8.2.9, too.

**Comment by kharrop** [comment]
Tested in 8.3.0-beta.0 and still seeing this issue

**Comment by dzc0d3r** [comment]
+1

**Comment by 7michele7** [comment]
Thanks for sorting this out 🥳
