### ISSUE TITLE
[Bug]: Invariant failed: Expected package.json#version to be defined in the "undefined" package}

### ISSUE THREAD

**Issue by bakervos** [storybookjs/storybook#28606]
### Describe the bug

While upgrading my project from storybook 7 to 8, I noticed that serving does not work any more, with the following error:

```
Error: Invariant failed: Expected package.json#version to be defined in the "undefined" package}
    at invariant (/home/jojoxd/Development/<PROJECT>/node_modules/@storybook/core/dist/core-server/index.cjs:187629:11)
    at buildDevStandalone (/home/jojoxd/Development/<PROJECT>/node_modules/@storybook/core/dist/core-server/index.cjs:189878:3)
    at Object.build (/home/jojoxd/Development/<PROJECT>/node_modules/@storybook/core/dist/core-server/index.cjs:190006:12)
    at runInstance (/home/jojoxd/Development/<PROJECT>/node_modules/@nx/storybook/src/executors/storybook/storybook.impl.js:26:18)
    at storybookExecutor (/home/jojoxd/Development/<PROJECT>/node_modules/@nx/storybook/src/executors/storybook/storybook.impl.js:12:26)
    at storybookExecutor.next (<anonymous>)
    at getLastValueFromAsyncIterableIterator (/home/jojoxd/Development/<PROJECT>/node_modules/nx/src/utils/async-iterator.js:15:34)
    at iteratorToProcessStatusCode (/home/jojoxd/Development/<PROJECT>/node_modules/nx/src/command-line/run/run.js:44:94)
    at /home/jojoxd/Development/<PROJECT>/node_modules/nx/src/command-line/run/run.js:187:16
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

It looks like [this change](https://github.com/storybookjs/storybook/commit/949f87860be55b50c85c7a67bcb1e843bfcbf73e#diff-85422d9e2b6757cd717ca027c56111e08d6f59827e2e1bef460fe27ae5ef4b99L7) was made incorrectly, as the package.json's content should be read, instead of fetching the dirname.

### Reproduction link

https://example.com/there-is-no-reproduction

### System

```bash
Storybook Environment Info:

  System:
    OS: Linux 6.8 Ubuntu 24.04 LTS 24.04 LTS (Noble Numbat)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
    npm: 10.5.0 - ~/.nvm/versions/node/v20.12.2/bin/npm <----- active
  npmPackages:
    @storybook/addon-essentials: 8.2.2 => 8.2.2 
    @storybook/addon-interactions: 8.2.2 => 8.2.2 
    @storybook/core-server: 8.2.2 => 8.2.2 
    @storybook/jest: ^0.2.3 => 0.2.3 
    @storybook/test-runner: ^0.19.1 => 0.19.1 
    @storybook/testing-library: ^0.2.2 => 0.2.2 
    @storybook/vue3-vite: 8.2.2 => 8.2.2
```

### Additional context

This NX Issue is related: https://github.com/nrwl/nx/issues/26914

**Comment by shilman** [comment]
@bakervos Sorry for the hassle! It seems like we've broken the `nx` integration in 8.2. We're meeting with the nx team later this week to get it resolved. In the meantime, if you upgrade to 8.1 I think you should be OK (though nx support for 8.x isn't official yet AFAIK).

**Comment by dgonzalezr** [comment]
> @bakervos Sorry for the hassle! It seems like we've broken the `nx` integration in 8.2. We're meeting with the nx team later this week to get it resolved. In the meantime, if you upgrade to 8.1 I think you should be OK (though nx support for 8.x isn't official yet AFAIK).

@shilman just a note to add, this only happens when serving Storybook (start command), `storybook build` still works as expected without any issue

**Comment by shilman** [comment]
As a workaround, you might also try adding the `storybook` package as a dev dependency in your project.

**Comment by dgonzalezr** [comment]
@shilman I have the `storybook` package as a dev dependency from some time ago.

**Comment by faisal-ethos** [comment]
Is there any workaround. Facing this issue after doing nx migration.

**Comment by marviobezerra** [comment]
+1

**Comment by shubhsk88** [comment]
I am facing this same issue while upgrading my storybook in nx

**Comment by parostatkiem** [comment]
I'm waiting for the solution too 🙏

**Comment by siiron** [comment]
+1 facing the same issue when upgrading Storybook in my NX monorepo.

**Comment by roeb** [comment]
+1 I have the same error. All dependencies of storybook have the same version.

**Comment by abcdmku** [comment]
Hey guys I opened a [PR here](https://github.com/storybookjs/storybook/pull/28752) let me know if this is working on your machine. 

cc: @Coly010

**Comment by ilhamsa1** [comment]
+1 I have same issues  when upgraded  from 7.5.3 to 8.2.7
![image](https://github.com/user-attachments/assets/39979500-4e50-401c-93ce-a5e19ed193b8)
![image](https://github.com/user-attachments/assets/74df0517-6829-4bc6-8788-572dc2507ec3)

**Comment by abcdmku** [comment]
@ilhamsa1 and @christopher-drifte if you want to get storybook running in the meantime try removing the storybook target on your `project.json` files listed on the libraries you are running storybook for:
```json
    "storybook": {
      "executor": "@nx/storybook:storybook",
      "options": {
        "port": 4402,
        "configDir": "libs/component-lib/.storybook"
      },
      "configurations": {
        "ci": {
          "quiet": true
        }
      }
    }
 ```
 
 if your project doesn't already have it defined, go to the `nx.json` file and add storybook as a plugin:
 ```js
 {
  // other config definitions
  "plugins": [ // this might be defined already. if so, just add storybook to the list if its not there.
    {
      "plugin": "@nx/storybook/plugin",
      "options": {
        "serveStorybookTargetName": "storybook", // <-- this is the the command that you are running 
        "buildStorybookTargetName": "build-storybook",
        "testStorybookTargetName": "test-storybook",
        "staticStorybookTargetName": "static-storybook"
      }
    },
    // other plugins
  ]
}

**Comment by Benjythebee** [comment]
Am using Storybook 8.2.7 and am still facing this issue apparently;
