### ISSUE TITLE
Vitest: Create "Component Coverage" per story file

### ISSUE THREAD

**Issue by valentinpalkovic** [storybookjs/storybook#28628]
We need to implement a mechanism in Vitest to generate coverage reports for each story file. This task focuses on collecting coverage data for all affected files when a story file is executed, and outputting the data in a parseable format. This will serve as the foundation for integrating coverage data into the Storybook UI or server at a later stage.

### Configure Vitest for Coverage Reporting:

- Set up Vitest to collect coverage data for story files.
- Ensure that the configuration includes all necessary options for detailed coverage metrics (statements, branches, functions, lines).

### Generate Coverage Reports:

Modify the Vitest configuration to generate coverage reports in a parseable format (e.g., JSON, LCOV).
Ensure the reports include detailed coverage information for all affected files related to the story file being tested.

### (Optional) Save Coverage Data:

Implement a mechanism to save the generated coverage reports in a structured format in a predefined directory.
Ensure the saved data is organized and accessible for later use.

### Documentation:

Document the process and configuration steps required to generate coverage reports with Vitest.
Provide examples of the generated coverage data format for reference.

## Acceptance Criteria:

- Vitest is configured to collect and generate detailed coverage reports for each story file.
- Coverage reports are outputted in a parseable format (e.g., JSON, LCOV) and saved in a predefined directory.
- The process and configuration steps are documented clearly, with examples of the coverage data format.

**Comment by valentinpalkovic** [comment]
Completed. Except of the optional "(Optional) Save Coverage Data" requirement.

**Comment by foxaltus** [comment]
Any docs on this or still too early?

**Comment by valentinpalkovic** [comment]
This was just an experimental spike. We haven't released any coverage addon (yet). We might have plans for the end of year or the beginning of next year, though. 

@shilman Can provide more information about an approx. release date.
