### ISSUE TITLE
[Bug]: Docs page menu item cannot be clicked; the page does not respond.

### ISSUE THREAD

**Issue by phongnguyen-it** [storybookjs/storybook#28640]
### Steps to Reproduce:
1. Navigate to [Storybook Docs - What's a Story](https://storybook.js.org/docs/get-started/whats-a-story).
2. Attempt to click on any menu item in the left sidebar.

### Expected Result:
The page should navigate to the selected section or item within the documentation.

### Actual Result:
The site does not respond to clicks on the menu items in the left sidebar.

### Reproduction link

https://storybook.js.org/docs/get-started/whats-a-story

### Reproduction steps

1. Navigate to [Storybook Docs - What's a Story](https://storybook.js.org/docs/get-started/whats-a-story).
2. Attempt to click on any menu item in the left sidebar.

### System

```bash
System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M1
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
    Yarn: 1.22.22 - /usr/local/bin/yarn
  Browsers:
    Chrome: 126.0.6478.182
    Edge: 126.0.2592.102
    Safari: 17.5
```

**Comment by JohnyTheCarrot** [comment]
Found the root of the problem, will be attempting to fix. Will keep you guys updated.

**Comment by JohnyTheCarrot** [comment]
Fixed with https://github.com/storybookjs/web/pull/208

**Comment by jonniebigodes** [comment]
@phongnguyen-it, thanks for taking the time to reach out to us with your issue and letting us know about it. We appreciate it 🙏 ! We're on it, and a fix has already been merged in. We'll continue monitoring and see if the issue persists. 

@JohnyTheCarrot, we'd like to thank you as well for your contribution and willingness to help us as well 🙇

**Comment by jonniebigodes** [comment]
So that you're aware, the fix is live, and the issue seems to no longer be in effect. I just ran some testing on it and all seems to check out.

I'm going to close this for now, but I'd like to encourage you or anyone else to ping me if you happen to see it surfacing again so that I can reopen the issue and continue to work on it.
