### ISSUE TITLE
[Bug]: Addon build fails due to missing @storybook/manager/globals on 8.2.5

### ISSUE THREAD

**Issue by joris-fonck-loreal** [storybookjs/storybook#28673]
### Describe the bug

Same issue as https://github.com/storybookjs/storybook/issues/28647. The issue seems to be fixed in 8.2.5 by https://github.com/storybookjs/storybook/pull/28650 but it's not.

### Reproduction link

https://stackblitz.com/~/github.com/joris-fonck-loreal/addon-kit

### Reproduction steps

Go to the link above. It should automatically run npm i && npm start. Run build after the install. You should see the error

### System

```bash
Storybook Environment Info:

  System:
    OS: Linux 5.10 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.11.0 - /usr/bin/node
    Yarn: 1.22.19 - /mnt/c/Program Files/nodejs/yarn
    npm: 10.2.4 - /usr/bin/npm
    pnpm: 9.4.0 - /usr/bin/pnpm <----- active
  Browsers:
    Chrome: 120.0.6099.129
  npmPackages:
    @storybook/addon-docs: ^8.2.5 => 8.2.5 
    @storybook/blocks: ^8.2.5 => 8.2.5 
    @storybook/components: ^8.2.5 => 8.2.5 
    @storybook/core-events: ^8.2.5 => 8.2.5 
    @storybook/icons: ^1.2.9 => 1.2.9 
    @storybook/manager: ^8.2.5 => 8.2.5 
    @storybook/manager-api: ^8.2.5 => 8.2.5 
    @storybook/preview: ^8.2.5 => 8.2.5 
    @storybook/preview-api: ^8.2.5 => 8.2.5 
    @storybook/react: ^8.2.5 => 8.2.5 
    @storybook/react-vite: ^8.2.5 => 8.2.5 
    @storybook/types: ^8.2.5 => 8.2.5 
    storybook: ^8.2.5 => 8.2.5
```

**Comment by vanessayuenn** [comment]
@joris-fonck-loreal thanks for reporting this issue but the repro you linked doesn't have the updated dependencies. Does this happen after you have upgraded all the storybook dependencies to 8.2.5?

**Comment by joris-fonck-loreal** [comment]
Sorry for that. Changes were on my local. I updated the repro link
