### ISSUE TITLE
[Bug]: Incorrect null type error for ControlType

### ISSUE THREAD

**Issue by lentilz** [storybookjs/storybook#28677]
### Describe the bug

I just upgraded from v8.1.11 to v8.2.5 and started seeing 

<img width="785" alt="Screenshot 2024-07-22 at 6 05 09 PM" src="https://github.com/user-attachments/assets/e9f3e203-c002-4297-98cb-7144bbe65758">

[control.type](https://storybook.js.org/docs/api/arg-types#controltype) rightly supports `null` but is showing as a type error : 
`Type 'null' is not assignable to type 'ControlType | undefined'.`

### Reproduction link

/

### Reproduction steps

This is in a Vue3 & Typescript 5 project:

1. install sb@8.1.11 and set a control type of one your args to `control: { type: null }`. This should disable any controls for this arg and in place should be a - 
2. In your editor reference the accepted types for control. It should show ControlType | null in the property types node_modules/@storybook/csf/dist/index.d.ts
3. now upgrade to the latest SB@v8.2.5. Re-run storybook. Now `type` has an error and when referencing the types, it now shows `'ControlType | undefined'` as the available types

### System

```bash
System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M1 Pro
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.15.0 - ~/n/bin/node
    npm: 10.7.0 - ~/n/bin/npm <----- active
    pnpm: 8.7.4 - ~/n/bin/pnpm
  Browsers:
    Chrome: 126.0.6478.183
    Safari: 17.5
  npmPackages:
    @storybook/addon-a11y: 8.2.5 => 8.2.5
    @storybook/addon-designs: 8.0.3 => 8.0.3
    @storybook/addon-essentials: 8.2.5 => 8.2.5
    @storybook/addon-interactions: 8.2.5 => 8.2.5
    @storybook/addon-links: 8.2.5 => 8.2.5
    @storybook/addon-webpack5-compiler-swc: 1.0.4 => 1.0.4
    @storybook/blocks: 8.2.5 => 8.2.5
    @storybook/manager-api: 8.2.5 => 8.2.5
    @storybook/test: 8.2.5 => 8.2.5
    @storybook/theming: 8.2.5 => 8.2.5
    @storybook/vue3: 8.2.5 => 8.2.5
    @storybook/vue3-webpack5: 8.2.5 => 8.2.5
    eslint-plugin-storybook: 0.8.0 => 0.8.0
    storybook: 8.2.5 => 8.2.5
```

**Comment by reydelo** [comment]
@lentilz I also ran into this type error. Fixed it with: `control: false`

https://storybook.js.org/docs/api/arg-types#control

**Comment by lentilz** [comment]
Thanks @reydelo I see that now and confirmed false works

**Comment by lentilz** [comment]
Thanks @reydelo I see that now and confirmed false works
