### ISSUE TITLE
[Bug]: PNPM Install returning errors

### ISSUE THREAD

**Issue by madeinjei** [storybookjs/storybook#28696]
### Describe the bug

Whenever I use PNPM to install storybook for nextjs it will install storybook successfully but then return errors when installing whatever packages it needs for the nextjs compatibility

### Reproduction link

NONE

### Reproduction steps

run `pnpm dlx storybook@latest init` in your nextjs project environment

### System

```bash
Storybook Environment Info:

  System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M2 Pro
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.13.1 - /usr/local/bin/node
    pnpm: 9.6.0 - /usr/local/bin/pnpm <----- active
  Browsers:
    Safari: 17.5
  npmPackages:
    @storybook/addon-essentials: ^8.2.5 => 8.2.5 
    @storybook/addon-interactions: ^8.2.5 => 8.2.5 
    @storybook/addon-links: ^8.2.5 => 8.2.5 
    @storybook/addon-onboarding: ^8.2.5 => 8.2.5 
    @storybook/blocks: ^8.2.5 => 8.2.5 
    @storybook/nextjs: ^8.2.5 => 8.2.5 
    @storybook/react: ^8.2.5 => 8.2.5 
    @storybook/test: ^8.2.5 => 8.2.5
```

**Comment by shilman** [comment]
I couldn't reproduce with a fresh next app.

Do you a have a reproduction repo you can share? If not, can you create one? Go to https://storybook.new or see [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce). Thank you! 🙏

**Comment by madeinjei** [comment]
I don't have a repo, but I also tried it on a blank project and I got the same error( and when I say blank I mean I just initialized node and only installed storybook
