### ISSUE TITLE
[Bug]: SB_CORE-SERVER_0002 (CriticalPresetLoadError): Storybook failed to load the following preset: @storybook/react-vite/preset.

### ISSUE THREAD

**Issue by freeshineit** [storybookjs/storybook#28729]
### Describe the bug

> storybook dev -p 6006

storybook v8.2.6

SB_CORE-SERVER_0002 (CriticalPresetLoadError): Storybook failed to load the following preset: @storybook/react-vite/preset.

Please check whether your setup is correct, the Storybook dependencies (and their peer dependencies) are installed correctly and there are no package version clashes.

If you believe this is a bug, please open an issue on Github.

Error: Cannot find module '@storybook/react-vite/preset'
Require stack:
- /Users/qiangshao/shine/github/pnpm-workspace/node_modules/.pnpm/@storybook+core@8.2.6/node_modules/@storybook/core/dist/common/index.cjs
- /Users/qiangshao/shine/github/pnpm-workspace/node_modules/.pnpm/@storybook+core@8.2.6/node_modules/@storybook/core/dist/telemetry/index.cjs
- /Users/qiangshao/shine/github/pnpm-workspace/node_modules/.pnpm/storybook@8.2.6/node_modules/storybook/dist/generate.cjs
- /Users/qiangshao/shine/github/pnpm-workspace/node_modules/.pnpm/storybook@8.2.6/node_modules/storybook/bin/index.cjs
    at Module._resolveFilename (node:internal/modules/cjs/loader:1143:15)
    at Module._resolveFilename (/Users/qiangshao/shine/github/pnpm-workspace/node_modules/.pnpm/esbuild-register@3.6.0_esbuild@0.18.20/node_modules/esbuild-register/dist/node.js:4794:36)
    at Module._load (node:internal/modules/cjs/loader:984:27)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:179:18)
    at interopRequireDefault (/Users/qiangshao/shine/github/pnpm-workspace/node_modules/.pnpm/@storybook+core@8.2.6/node_modules/@storybook/core/dist/common/index.cjs:145609:11)
    at getContent (/Users/qiangshao/shine/github/pnpm-workspace/node_modules/.pnpm/@storybook+core@8.2.6/node_modules/@storybook/core/dist/common/index.cjs:150235:10)
    at loadPreset (/Users/qiangshao/shine/github/pnpm-workspace/node_modules/.pnpm/@storybook+core@8.2.6/node_modules/@storybook/core/dist/common/index.cjs:150241:51)
    at /Users/qiangshao/shine/github/pnpm-workspace/node_modules/.pnpm/@storybook+core@8.2.6/node_modules/@storybook/core/dist/common/index.cjs:150287:24
    at Array.map (<anonymous>)

More info: 

    at loadPreset (/Users/qiangshao/shine/github/pnpm-workspace/node_modules/.pnpm/@storybook+core@8.2.6/node_modules/@storybook/core/dist/common/index.cjs:150276:13)

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

### Reproduction link

nothing

### System

```bash
Storybook Environment Info:

  System:
    OS: macOS 12.7.5
    CPU: (8) x64 Intel(R) 
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 20.12.1 - ~/.nvm/versions/node/v20.12.1/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.5.0 - ~/.nvm/versions/node/v20.12.1/bin/npm
    pnpm: 8.11.0 - /usr/local/bin/pnpm <----- active
  Browsers:
    Chrome: 127.0.6533.73
    Safari: 17.5
  npmPackages:
    @storybook/addon-essentials: ^8.2.6 => 8.2.6 
    @storybook/addon-interactions: ^8.2.6 => 8.2.6 
    @storybook/addon-links: ^8.2.6 => 8.2.6 
    @storybook/addon-onboarding: ^8.2.6 => 8.2.6 
    @storybook/blocks: ^8.2.6 => 8.2.6 
    @storybook/react: ^8.2.6 => 8.2.6 
    @storybook/react-vite: ^8.2.6 => 8.2.6 
    @storybook/test: ^8.2.6 => 8.2.6 
    eslint-plugin-storybook: ^0.8.0 => 0.8.0 
    storybook: ^8.2.6 => 8.2.6
```

**Comment by freeshineit** [comment]
This bug occurs in the pnpm workspace, but it is normal for individual projects

**Comment by freeshineit** [comment]
soryy,  I didn't add it in pnpm workspce, which caused the error

**Comment by kerryj89** [comment]
Same error, but for me it was because my root package.json `nohoist` didn't mask the entire Storybook dependencies, so some were being hoisted up still and Storybook couldn't find it.  Posting this here for anyone that might be running into the same problem.

Root `package.json`:
```json
{
  ...
  "workspaces": {
    ...
    "nohoist": [
      "@storybook",
      "**/@storybook",
      "**/@storybook/**"
    ]
  }
  ...
}
```

**Comment by rchanaud** [comment]
Same error for me

**Node**: 22.14.0
**PNPM**: 10.8.0
**Storybook**: 8.6.3

Default PNPM workspace configuration.

It fails only in my CI using `node:22-alpine`

No error on `node:20-alpine`.

**Comment by rchanaud** [comment]
Nevermind, I just followed this doc and it worked.

[https://storybook.js.org/docs/faq#how-do-i-fix-module-resolution-in-special-environments](https://storybook.js.org/docs/faq#how-do-i-fix-module-resolution-in-special-environments)
