### ISSUE TITLE
[Bug]: @storybook/types issues

### ISSUE THREAD

**Issue by rChaoz** [storybookjs/storybook#28728]
### Describe the bug

At some points between 8.0.10 and 8.2.6, something changed with how types are handled internally. More specifically, I've seen that generally types are now imported from `storybook/internal/types` rather than `@storybook/types` (package which was deprecated). The issue here is that it seems like the package `@storybook/types` is not a dependency of other storybook packages anymore, so it's not installed, making any code that tries to import it fails. Here I'm talking about storybook itself - there's [a few places](https://github.com/search?q=repo%3Astorybookjs%2Fstorybook%20%40storybook%2Ftypes&type=code) in the storybook monorepo that still use `@storybook/types` directly, which now fail, unless `@storybook/types` is manually added as a dependency.

They don't fail as in TypeScript says "package @storybook/types not found", or something, I'm guessing because it doesn't report any errors in `node_modules`. What happens is that any imports made by storybook from `@storybook/types` are skipped without errors. For example, if an interface in storybook extends one imported from `@storybook/types`, the import/extends is simply ignored, practically reducing the type (as if the extends statement is completely removed), and causing errors like `Object literal may only specify known properties, and 'args' does not exist in type 'Partial<StoryProps>'` in the end-user code, which don't make sense.

### Reproduction steps

The issue I encountered is with [addon-svelte-csf](https://github.com/storybookjs/addon-svelte-csf), but it seems like are a couple of places in the storybook monorepo as well that still import `@storybook/types`, as linked above, so I thought it'd be a good idea to open an issue here as well.

See the other issue for a reproduction: https://github.com/storybookjs/addon-svelte-csf/issues/194

**Comment by JReinhold** [comment]
Thank you for the report. Based on the search query you posted, I've narrowed it down to these instances of actual imports from `@storybook/types`: https://github.com/search?q=repo:storybookjs/storybook+@storybook/types+language:TypeScript+NOT+path:/%5Ecode%5C/core%5C/src%5C/preview%5C/globals%5C//+NOT+path:/%5Ecode%5C/core%5C/src%5C/manager%5C/globals%5C//+NOT+path:/%5Ecode%5C/core%5C/src%5C/common%5C//+NOT+path:/%5Ecode%5C/lib%5C/cli%5C/src%5C//+NOT+path:/%5Ecode%5C/addons%5C/actions%5C/src%5C//&type=code
