### ISSUE TITLE
Bug: Investigate global-setup storybook spawn script sometimes not killing Storybook process

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#28890]
Sometimes when running tests in watch mode, Storybook spawns correctly but doesn't get killed correctly. It's difficult to reproduce it but could be related to the internal mechanism of killing the process in the global-setup file not being robust.

File where the logic is placed at:
https://github.com/storybookjs/storybook/blob/next/code/addons/test/src/vitest-plugin/global-setup.ts

How to reproduce:
1. Configure the plugin to use the script:
```ts
  plugins: [
    storybookTest({
      storybookScript: 'yarn storybook --no-open'
    })
  ],
```

2. Run the tests in watch mode
3. Kill the process, check if Storybook is also killed

**Comment by vanessayuenn** [comment]
@yannbf how often is this occurring, based on your experience?
