### ISSUE TITLE
[Bug]: Errors out of the box after 'npx storybook@latest init' in nextjs

### ISSUE THREAD

**Issue by misiyevich** [storybookjs/storybook#28940]
### Describe the bug

In my `"next": "13.0.0"` project i run `npx storybook@latest init`. After initialization, i got opened Storybook tab in browser. But it shows a lot of errors:
`Can't resolve 'next/dist/shared/lib/app-router-context.shared-runtime' in 'C:\Users\misiy\WebstormProjects\freshpet\freshpet\node_modules\@storybook\nextjs\dist'`
`Can't resolve 'next/dist/shared/lib/hooks-client-context.shared-runtime' in 'C:\Users\misiy\WebstormProjects\freshpet\freshpet\node_modules\@storybook\nextjs\dist'`
`Can't resolve 'next/dist/shared/lib/router-context.shared-runtime' in 'C:\Users\misiy\WebstormProjects\freshpet\freshpet\node_modules\@storybook\nextjs\dist'`
`Can't resolve 'next/dist/shared/lib/head-manager-context.shared-runtime' in 'C:\Users\misiy\WebstormProjects\freshpet\freshpet\node_modules\@storybook\nextjs\dist'`
`Can't resolve 'next/dist/client/components/is-next-router-error' in 'C:\Users\misiy\WebstormProjects\freshpet\freshpet\node_modules\@storybook\nextjs\dist'`

After stop script. And run 'npm run storybook" i get another error:
`Error: spawn undefined\System32\WindowsPowerShell\v1.0\powershell ENOENT`

### Reproduction link

http://localhost:6006/?path=/docs/configure-your-project--docs

### Reproduction steps

1.run `npx storybook@latest init`
2.enjoy

### System

```bash
System:
    OS: Windows 10 10.0.19045
    CPU: (4) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
  Binaries:
    Node: 18.12.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD <----- active
  Browsers:
    Chrome: 127.0.6533.120
    Edge: Spartan (44.19041.3636.0), Chromium (127.0.2651.74)
  npmPackages:
    @storybook/addon-actions: ^8.2.9 => 8.2.9
    @storybook/addon-essentials: ^8.2.9 => 8.2.9
    @storybook/addon-interactions: ^8.2.9 => 8.2.9
    @storybook/addon-links: ^8.2.9 => 8.2.9
    @storybook/addon-onboarding: ^8.2.7 => 8.2.9
    @storybook/addon-webpack5-compiler-babel: ^3.0.3 => 3.0.3
    @storybook/blocks: ^8.2.7 => 8.2.9
    @storybook/nextjs: ^8.2.9 => 8.2.9
    @storybook/react: ^8.2.9 => 8.2.9
    @storybook/test: ^8.2.7 => 8.2.9
    storybook: ^8.2.7 => 8.2.9
    storybook-addon-sass-postcss: ^0.3.1 => 0.3.1
```

**Comment by yannbf** [comment]
Hey there @misiyevich thanks for reaching out!
The Storybook nextjs package [needs a minimum version of Next 13.5.0](https://github.com/storybookjs/storybook/blob/4bbfb143c4911eaff21293499ab914c92b0fae44/code/frameworks/nextjs/package.json#L180), your package manager should have complained about the unmet peer dependencies. Hopefully you can upgrade your nextjs project to get the best out of Storybook!
