### ISSUE TITLE
[Bug]: Cannot find module 'storybook/internal/common' error

### ISSUE THREAD

**Issue by moduld** [storybookjs/storybook#29087]
### Describe the bug

Hello.
I use Storybook (@storybook/angular) to preview Angular 18 components. Project settings defined accordingly to official Storybook documentation (https://storybook.js.org/docs/get-started/frameworks/angular).
When I try to execute the ng run storybook:build or ng run storybook:serve command I get next error:
```
An unhandled exception occurred: Cannot find module 'storybook/internal/common'
Require stack:
- C:\Work\web-ui\node_modules\@storybook\angular\dist\builders\build-storybook\index.js
- C:\Work\web-ui\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js
```
How to resolve the problem?

### Reproduction link

https://github.com/storybookjs/storybook/blob/next/code/frameworks/angular/package.json

### Reproduction steps

1. Install storybook to your Angular project accordingly to the official docs https://storybook.js.org/docs/get-started/frameworks/angular
2. Try to execute ng run storybook:serve

### System

```bash
npmPackages:
    @storybook/addon-actions: ^8.2.9 => 8.2.9
    @storybook/addon-console: ^3.0.0 => 3.0.0
    @storybook/addon-controls: ^8.2.9 => 8.2.9
    @storybook/addon-styling: ^1.3.7 => 1.3.7
    @storybook/angular: ^8.2.9 => 8.2.9
```

**Comment by jinbekim** [comment]
I think this issue could help you.

#28591
