### ISSUE TITLE
Add `knip` to identify unused files/exports

### ISSUE THREAD

**Issue by JReinhold** [storybookjs/storybook#29106]
https://knip.dev

**Comment by webpro** [comment]
Via https://discord.com/channels/1227627367204257852/1227627367204257855/1283706041338695682

**Comment by JReinhold** [comment]
See previous attempt, which looked to be closed purely to cleanup stale PRs, so nothing blocking as far as I can see.

https://github.com/storybookjs/storybook/pull/20572
