### ISSUE TITLE
[Bug]: `storybook init --skip-install` still broken

### ISSUE THREAD

**Issue by benmccann** [storybookjs/storybook#29112]
### Describe the bug

`pnpx storybook init --skip-install` generates:
```
  "devDependencies": {
    "@fontsource/fira-mono": "^4.5.10",
    "@neoconfetti/svelte": "^1.0.0",
    "@sveltejs/adapter-auto": "^3.0.0",
    "@sveltejs/kit": "^2.0.0",
    "@sveltejs/vite-plugin-svelte": "^3.0.0",
    "svelte": "^4.2.7",
    "svelte-check": "^3.6.0",
    "typescript": "^5.0.0",
    "vite": "^5.0.3",
    "@storybook/addon-svelte-csf": "^4.1.7",
    "@chromatic-com/storybook": "^1.9.0"
  },
```

`pnpx storybook init` generates:
```
  "devDependencies": {
    "@chromatic-com/storybook": "^1.9.0",
    "@fontsource/fira-mono": "^4.5.10",
    "@neoconfetti/svelte": "^1.0.0",
    "@storybook/addon-essentials": "^8.3.0",
    "@storybook/addon-interactions": "^8.3.0",
    "@storybook/addon-links": "^8.3.0",
    "@storybook/addon-svelte-csf": "^4.1.7",
    "@storybook/blocks": "^8.3.0",
    "@storybook/svelte": "^8.3.0",
    "@storybook/sveltekit": "^8.3.0",
    "@storybook/test": "^8.3.0",
    "@sveltejs/adapter-auto": "^3.0.0",
    "@sveltejs/kit": "^2.0.0",
    "@sveltejs/vite-plugin-svelte": "^3.0.0",
    "storybook": "^8.3.0",
    "svelte": "^4.2.7",
    "svelte-check": "^3.6.0",
    "typescript": "^5.0.0",
    "vite": "^5.0.3"
  },
```

### Reproduction link

see steps below

### Reproduction steps

pnpm create svelte@latest myapp
cd myapp
pnpx storybook init --skip-install

### System

```bash
storybook 8.3.0
```

### Additional context

I think this is at least the third time we've reported this bug. It keeps being fixed in pre-releases and then broken in the final release

The last attempt at fixing this was https://github.com/storybookjs/storybook/pull/28853. I'm not sure how come it didn't stick or the tests didn't catch that it broke again

**Comment by shilman** [comment]
@kasperpeulen @ndelangen @JReinhold @vanessayuenn 

Can we please:
1. Fix this in empathy
2. Make sure that it's well-tested in CI so we don't regress?

**Comment by valentinpalkovic** [comment]
@shilman I can take care of it on Monday since I am taking over empathy from Kasper for a week.

**Comment by benmccann** [comment]
Thank you!! You'll soon be able to setup Storybook in the main Svelte CLI for project creation. This is really helpful for us to be able to enable that
