### ISSUE TITLE
Update test log to handle discrepancy in test results

### ISSUE THREAD

**Issue by ghengeveld** [storybookjs/storybook#29120]
- Detect the fact that one threw an error and the other didn't (play function vs Vitest). 
  - No need to check the actual assertions, only consider the overall result (throwing/erroring or not).
- Show a message in the interactions panel to explain the situation and link to the docs.
- If we have an error message from Vitest, print it.

**Comment by yannbf** [comment]
Closing as it was moved out of scope for the current project.
