### ISSUE TITLE
[Bug]: storybook 8 react native error on regex from jsdoc-type-pratt-parser

### ISSUE THREAD

**Issue by dannyhw** [storybookjs/storybook#29130]
### Describe the bug

jsdoc-type-pratt-parser in getQuoted which uses unicode patterns and "Unicode character class escape" which don't seem to be supported on react native

you can see the code here
`code/node_modules/jsdoc-type-pratt-parser/dist/index.js`

1: `/[$_\p{ID_Start}]|\\u\p{Hex_Digit}{4}|\\u\{0*(?:\p{Hex_Digit}{1,5}|10\p{Hex_Digit}{4})\}/u`

2: `/[$\-\p{ID_Continue}\u200C\u200D]|\\u\p{Hex_Digit}{4}|\\u\{0*(?:\p{Hex_Digit}{1,5}|10\p{Hex_Digit}{4})\}/u`

after being bundled into storybook it looks like

```
    let d = new RegExp("[$_\\p{ID_Start}]|\\\\u\\p{Hex_Digit}{4}|\\\\u\\{0*(?:\\p{Hex_Digit}{1,5}|10\\p{Hex_Digit}{4})\\}", "u"), m = new RegExp(
    "[$\\-\\p{ID_Continue}\\u200C\\u200D]|\\\\u\\p{Hex_Digit}{4}|\\\\u\\{0*(?:\\p{Hex_Digit}{1,5}|10\\p{Hex_Digit}{4})\\}", "u");
```

![image](https://github.com/user-attachments/assets/b129bc05-83cb-4e9b-abde-96681e924b12)

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Regular_expressions/Unicode_character_class_escape

### Reproduction link

https://github.com/storybookjs/react-native/pull/538

### Reproduction steps

1. Open branch `feat/v8`
2. Install (`yarn`)
3. Build (`yarn build`)
4. comment out lines 62-74 in packages/react-native/metro/withStorybook.js
5. `yarn workspace expo-example storybook`

_No response_

### System

```bash
Storybook Environment Info:

  System:
    OS: macOS 15.0
    CPU: (10) arm64 Apple M1 Max
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.13.1 - ~/.local/state/fnm_multishells/12353_1726330415155/bin/node
    Yarn: 4.1.0 - ~/Library/pnpm/yarn <----- active
    npm: 10.5.2 - ~/.local/state/fnm_multishells/12353_1726330415155/bin/npm
  Browsers:
    Chrome: 128.0.6613.138
    Safari: 18.0
```

### Additional context

Hermes's implementation of regex is lacking some of the advanced regex features

**Comment by valentinpalkovic** [comment]
Hi @dannyhw 

Could you please try out 0.0.0-pr-29134-sha-a3d75f58?

**Comment by dannyhw** [comment]
@valentinpalkovic it worked!
