### ISSUE TITLE
[Bug]: npx@latest upgrade crashes, also regression bug

### ISSUE THREAD

**Issue by stevensacks** [storybookjs/storybook#29169]
### Describe the bug

Running `npx sb@latest upgrade` for version 8.3.2 has two issues:

## Regression bug with pinned dependencies
There was a previous fix where if the package.json dependency versions were pinned, the upgrade script would not insert a caret before the version anymore. This issue has returned. A `^` is being injected on pinned dependencies.

## npm error
```
npm error code ERESOLVE
npm error ERESOLVE could not resolve
npm error
npm error While resolving: gaia-template-remix@1.0.0-beta
npm error Found: @storybook/react@8.3.1
npm error node_modules/@storybook/react
npm error   dev @storybook/react@"^8.3.2" from the root project
npm error   @storybook/react@"8.3.1" from @storybook/react-vite@8.3.1
npm error   node_modules/@storybook/react-vite
npm error     dev @storybook/react-vite@"^8.3.2" from the root project
npm error
npm error Could not resolve dependency:
npm error dev @storybook/react@"^8.3.2" from the root project
npm error
npm error Conflicting peer dependency: @storybook/test@8.3.2
npm error node_modules/@storybook/test
npm error   peerOptional @storybook/test@"8.3.2" from @storybook/react@8.3.2
npm error   node_modules/@storybook/react
npm error     dev @storybook/react@"^8.3.2" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
```
The only fix for this is to delete node_modules and package-lock.json and run `npm install`. Then 8.3.2 will install correctly.

### Reproduction link

https://storybook.js.org/

### Reproduction steps

Run `npx sb@latest upgrade` on a project that has 8.3.1.

### System

```bash
Storybook Environment Info:

  System:
    OS: macOS 14.6.1
    CPU: (12) arm64 Apple M2 Pro
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.17.0 - ~/.nvm/versions/node/v20.17.0/bin/node
    npm: 10.8.3 - ~/.nvm/versions/node/v20.17.0/bin/npm <----- active
    pnpm: 8.1.0 - ~/.nvm/versions/node/v20.17.0/bin/pnpm
  Browsers:
    Chrome: 128.0.6613.139
    Safari: 17.6
  npmPackages:
    @storybook/addon-essentials: ^8.3.2 => 8.3.2 
    @storybook/addon-interactions: ^8.3.2 => 8.3.2 
    @storybook/addon-links: ^8.3.2 => 8.3.2 
    @storybook/blocks: ^8.3.2 => 8.3.2 
    @storybook/manager-api: ^8.3.2 => 8.3.2 
    @storybook/preview-api: ^8.3.2 => 8.3.2 
    @storybook/react: ^8.3.2 => 8.3.2 
    @storybook/react-vite: ^8.3.2 => 8.3.2 
    @storybook/test: ^8.3.2 => 8.3.2 
    @storybook/theming: ^8.3.2 => 8.3.2 
    @storybook/types: ^8.3.2 => 8.3.2 
    chromatic: 11.10.2 => 11.10.2 
    eslint-plugin-storybook: 0.8.0 => 0.8.0 
    storybook: ^8.3.2 => 8.3.2 
    storybook-dark-mode: 4.0.2 => 4.0.2 
    storybook-react-i18next: 3.1.7 => 3.1.7
```

**Comment by valentinpalkovic** [comment]
I don't understand how the error message correlates with the issue you described. Can you elaborate?

**Comment by stevensacks** [comment]
When you run `npx sb@latest upgrade` the upgrade fails, and all `npm install` attempts after that fail because the package-lock.json seems to be in a broken state. The only solution is to delete node_modules and package-lock.json and run `npm install`, which at that point works. Storybook 8.3.2 is installed at that point. But, if you don't delete package-lock.json, you will always get that error for any package installation, not just Storybook, until you delete package-lock.json and reinstall from scratch.

**Comment by rakibatomnixima** [comment]
I also faced this when upgrading from 8.3.0 to 8.3.1 and also facing this issue now.

**Comment by JReinhold** [comment]
I can reproduce this. Here are my steps:

1. `npm create vite test-29169 -- --template react-ts`
2. `cd test-29169 `
3. `npm install`
4. add `legacy-peer-deps=true` to `.npmrc` to get around https://github.com/storybookjs/storybook/issues/29212
5. `npx storybook@8.3.1 init`
6. remove `eslint-plugin-storybook` from `package.json` to get around that same issue
7. pin all Storybook dependencies to `8.3.1`
8. Remove `package-lock.json` and `node_modules
9. `npm install` - now the project is in a clean state
10. `npx storybook@latest upgrade`
11. See error as described above

**Comment by JReinhold** [comment]
I've investigated this further, and it's really npm acting very strange with strict peer dependencies.

If you have a fresh project (like described above), with all Storybook dependencies _pinned_ to `8.3.2`, a correct lock-file and `node_modules`. Then you _manually_ change all the Storybook versions in `package.json` to `^8.3.3` and run `npm install`, you'll get the same error as above.

It seems that while trying to install the changed dependencies, npm looks into the `node_modules` and see that what it already have doesn't match. "I already have `@storybook/test@8.3.2` which doesn't match the peer dep requirement of `@storybook/test@8.3.3`", when in fact it should only run that check _after_ it has installed all the updated packages - because then it would match.

If you delete `node_modules` (keep lock-file intact) then it doesn't error. 🙃

I'm not saying this isn't something we should try to fix, just saying that npm is acting strange when upgrading pinned peer deps.

**Comment by dannyhw** [comment]
I was having this problem and the only thing I could do to get past it was override the react version to force a specific version

like

```
 "resolutions": {
    "react": "18.3.1"
  },
```
or
```
  "overrides": {
    "react": "18.3.1"
  },
  ```

**Comment by stevensacks** [comment]
This seems to have something to do with removing the pnpm package.json fix. That’s when it started happening.

**Comment by seb-lean** [comment]
I don't get a message telling me to update to update to the latest version, is that related?
<img width="487" alt="image" src="https://github.com/user-attachments/assets/98532c7f-3dc5-4515-982a-f5a9574b4b0f">

**Comment by stevensacks** [comment]
This is still happening with every version. I'm at 8.4.2 and the only solution is to delete node_modules and package-lock.json and reinstall everything.

**Comment by kasperpeulen** [comment]
@stevensacks Can you give a repro for that.

We tried to fix that with this PR:
https://github.com/storybookjs/storybook/pull/29503

We also patched this PR back to 8.2.10 and 8.3.7.

I still got into this issue with a project that was using addon designs:
https://github.com/storybookjs/addon-designs

I also changed the peer dep constraints there:
https://github.com/storybookjs/addon-designs/releases/tag/v8.0.4

If you can make a repro, maybe there are more externals addons that need to change.

**Comment by stevensacks** [comment]
It's happening in every project that I have. 

Here's my open source Remix template where it's happening: https://github.com/gaia-react/remix

You can run `npx sb@latest upgrade` on it to see the issue.

My projects all have these storybook libraries. Perhaps having one of these in package.json is the cause?
```json
"devDependencies": {
  "@storybook/addon-essentials": "8.4.2",
  "@storybook/addon-interactions": "8.4.2",
  "@storybook/addon-links": "8.4.2",
  "@storybook/blocks": "8.4.2",
  "@storybook/manager-api": "8.4.2",
  "@storybook/preview-api": "8.4.2",
  "@storybook/react": "8.4.2",
  "@storybook/react-vite": "8.4.2",
  "@storybook/test": "8.4.2",
  "@storybook/theming": "8.4.2",
  "@storybook/types": "8.4.2",
  "storybook": "8.4.2",
}
```

**Comment by yannbf** [comment]
Thank you so much @stevensacks for providing a repro. I think I found the issue.

@storybook/react has a peer dependency of @storybook/test, however, @storybook/react-vite, which has a direct dependency of @storybook/react, doesn't have a peer dependency of @storybook/test, thus breaking this chain. I am making some experimentations to see if I can solve this issue!
