### ISSUE TITLE
[Bug]: SIlent failure in react native when using jsx in a file without importing react at the top

### ISSUE THREAD

**Issue by danieloi** [storybookjs/storybook#29205]
### Describe the bug

Newer react versions don't require explicitly importing react at the top of files and many starters follow this new pattrn.

In react native however, you get a blank screen with no error message in the console whatsoever.

### Reproduction link

https://github.com/danieloi/storybook-silent-error-repro/tree/main

### Reproduction steps

Use these components in an expo react native app and notice how you get a blank screen unless you import react at the top of the file

### System

```bash
System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M1 Pro
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.15.1 - ~/.nvm/versions/node/v20.15.1/bin/node
    Yarn: 3.4.1 - ~/.yarn/bin/yarn
    npm: 10.7.0 - ~/.nvm/versions/node/v20.15.1/bin/npm <----- active
  Browsers:
    Chrome: 129.0.6668.60
    Safari: 17.5
```

**Comment by shilman** [comment]
How do I run your reproduction?
