### ISSUE TITLE
[Bug]: Interactions panel is rendering inline HTML in error messages

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#29306]
### Describe the bug

When writing an interaction test and there are errors reported from testing-library, if they relate to an element in the DOM, the element is actually rendered, instead of just showing text:

<img src="https://github.com/user-attachments/assets/de011098-ca3d-4e0a-9d24-d9724f6405a3" width="350px"/>

The regression was introduced here: https://github.com/storybookjs/storybook/pull/29110/files#diff-2771774420a97df6e693cb85b521b53d1fe7c6f7f59a89948bf10cbf6cbd63d4R139

### Reproduction link

-

### Reproduction steps

write an interaction test where an element is not supposed to exist, but it will exist
```ts
render: () => <button />
await expect(canvas.getByRole('button')).not.toBeInTheDocument();
```

### System

-

**Comment by charlotte-whiting** [comment]
Hi @vanessayuenn, I'm new to open source and would like to get started on this. Any tips or things I should follow in order to contribute to this issue? Thanks!
