### ISSUE TITLE
[Bug]: Issue with Storybook and Next.js 12

### ISSUE THREAD

**Issue by ahziani** [storybookjs/storybook#29341]
### Describe the bug

I just installed Storybook for my Next.js project using npx storybook@latest init following the official documentation. However, when I try to run Storybook, I encounter the following error:

`Error: Cannot find module 'next/dist/client/components/navigation'
    at webpackMissingModule 
    at ./node_modules/@storybook/nextjs/dist/export-mocks/navigation/index.mjs 
    at options.factory
    ...`

### System

Storybook Environment Info:

  System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz
  Binaries:
    Node: 20.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - ~\AppData\Roaming\npm\yarn.CMD <----- active
    npm: 10.8.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
  npmPackages:
    @storybook/addon-essentials: 8.3.5 => 8.3.5
    @storybook/addon-interactions: 8.3.5 => 8.3.5
    @storybook/addon-links: 8.3.5 => 8.3.5
    @storybook/addon-onboarding: 8.3.5 => 8.3.5
    @storybook/blocks: 8.3.5 => 8.3.5
    @storybook/nextjs: 8.3.5 => 8.3.5
    @storybook/react: 8.3.5 => 8.3.5
    @storybook/test: 8.3.5 => 8.3.5
    eslint-plugin-storybook: ^0.9.0 => 0.9.0
    storybook: 8.3.5 => 8.3.5

**Comment by Mastercoder424** [comment]
I think I can solve this issue 
-I have to see if there is any problem in version compatibility between Storybook and Next.js
-checking configurations 

Assign me.

**Comment by valentinpalkovic** [comment]
Hi @ahziani,

Next.js 12 is not supported in Storybook 8. Please upgrade Next.js to version 13.5 or newer to use it together with Storybook 8.
