### ISSUE TITLE
[Bug]: [8.4.0-alpha.7] index.html is deleted when storybook is built twice

### ISSUE THREAD

**Issue by IanVS** [storybookjs/storybook#29358]
### Describe the bug

I am testing out the latest 8.4.0 alpha, and found that when there is an existing output folder, if I run `storybook build`, my root `index.html` file is deleted.  

### Reproduction link

https://github.com/IanVS/reproduction-storybook-deletes-index

### Reproduction steps

1. `pnpm install`
2. `pnpm build-storybook` 
3. `git status` should be clean, no changes
4. `pnpm build-storybook` again
5. `git status` shows deleted `index.html` file.

### System

Storybook Environment Info:

  System:
    OS: macOS 15.0
    CPU: (12) arm64 Apple M2 Max
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.15.1 - ~/Library/Caches/fnm_multishells/39880_1728998568139/bin/node
    npm: 10.7.0 - ~/Library/Caches/fnm_multishells/39880_1728998568139/bin/npm <----- active
    pnpm: 9.7.0 - ~/Library/Caches/fnm_multishells/39880_1728998568139/bin/pnpm
  Browsers:
    Edge: 129.0.2792.89
    Safari: 18.0
  npmPackages:
    @storybook/addon-essentials: 8.4.0-alpha.7 => 8.4.0-alpha.7
    @storybook/addon-interactions: 8.4.0-alpha.7 => 8.4.0-alpha.7
    @storybook/addon-onboarding: 8.4.0-alpha.7 => 8.4.0-alpha.7
    @storybook/blocks: 8.4.0-alpha.7 => 8.4.0-alpha.7
    @storybook/react: 8.4.0-alpha.7 => 8.4.0-alpha.7
    @storybook/react-vite: 8.4.0-alpha.7 => 8.4.0-alpha.7
    @storybook/test: 8.4.0-alpha.7 => 8.4.0-alpha.7
    eslint-plugin-storybook: ^0.9.0 => 0.9.0
    storybook: 8.4.0-alpha.7 => 8.4.0-alpha.7

**Comment by IanVS** [comment]
FWIW, It looks like this first started in `8.4.0-alpha.1`

**Comment by JReinhold** [comment]
The most related PR to this regression in 8.4.0-alpha.1 is probably https://github.com/storybookjs/storybook/pull/29126
