### ISSUE TITLE
[Bug]: storybook/@nextjs-experimental-vite ERROR: [plugin: vite:dep-pre-bundle] Failed to resolve entry for package 'fs'

### ISSUE THREAD

**Issue by hsavit1** [storybookjs/storybook#29409]
### Describe the bug

I am trying to update my storybook setup in my next.js project to use the new experimental vite. using version 8.3.6 . I'm getting this error 

    ../../node_modules/next/dist/compiled/gzip-size/index.js:1:2840:
      1 │ ...essFn(o,r):o}return n}},147:e=>{"use strict";e.exports=require("fs")},781:e=>{"use strict";e.exports=require("stream")},796:e=>{"...
        ╵                                                                   ~~~~

10:58:47 AM [vite] error while updating dependencies:
Error: Build failed with 1 error:
../../node_modules/vite/node_modules/esbuild/lib/main.js:1225:21: ERROR: [plugin: vite:dep-pre-bundle] Failed to resolve entry for package "fs". The package may have incorrect main/module/exports specified in its package.json.
    at failureErrorWithLog (/Users/x/code/xx/xxx/xxxx/node_modules/vite/node_modules/esbuild/lib/main.js:1472:15)
    at /Users/x/xx/xxx/xxxx/xxxxx/node_modules/vite/node_modules/esbuild/lib/main.js:945:25
    at /Users/x/xx/xxx/xxxx/xxxxx/node_modules/vite/node_modules/esbuild/lib/main.js:1353:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

### Reproduction link

-

### System

storybook@8.3.6

**Comment by shilman** [comment]
Do you a have a reproduction repo you can share? If not, can you create one? Go to https://storybook.new or see [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce). Thank you! 🙏

**Comment by valentinpalkovic** [comment]
Which version of `next` do you use?

**Comment by hsavit1** [comment]
Im using next 14.2.3 . I just tried again with next 15.0.0 and i got the same error

**Comment by hsavit1** [comment]
Note that this used to work with the webpack builds. it is only failing with vite

**Comment by hsavit1** [comment]
@shilman the storybook.new templates do not have anything with the new next.js experimental vite

**Comment by hsavit1** [comment]
tried again with storybook 8.4.5 and next 15. still the same error
