### ISSUE TITLE
[Documentation]:  svelte csf snippets migth have typo

### ISSUE THREAD

**Issue by domuk-k** [storybookjs/storybook#29415]
### Describe the problem

In the code snippet found in `storybook/docs/_snippets/page-story-slots.md`, there is a `<template let:args> `declaration. If intended as such, it seems that `<Template let:arg>` is more contextually appropriate.

Here is the relevant code snippet:

```html renderer="svelte" language="ts" tabTitle="native-format"
storybook/docs/_snippets/page-story-slots.md

{/* Page.stories.svelte */}

<script>
  import { Meta, Template, Story } from '@storybook/addon-svelte-csf';

  import Page from './Page.svelte';
</script>

<meta title="Page" component="{Page}" /> // not meta => Meta from @storybook/addon-svelte-csf

<template let:args> // not template => Template from @storybook/addon-svelte-csf
  <Page {...args}>
    <footer>{args.footer}</footer>
  </Page>
</template>

<Story name="CustomFooter" args={{ footer: 'Built with Storybook', }} />
```

and same for these snippets i guess

- docs/_snippets/page-story-slots.md
- docs/_snippets/button-story-default.md
- docs/_snippets/list-story-starter.md
- docs/_snippets/button-story-click-handler-simplificated.md
- docs/_snippets/button-story-with-addon-example.md
- docs/_snippets/table-story-fully-customize-controls.md
- docs/_snippets/my-component-with-env-variables.md
- docs/_snippets/button-story-using-args.md
- docs/_snippets/your-component.md
- docs/_snippets/button-story-component-decorator.md
- docs/_snippets/your-component-with-decorator.md
- docs/_snippets/component-story-custom-args-complex.md
- docs/_snippets/button-story-with-args.md

**Comment by jonniebigodes** [comment]
@domuk-k, thanks for taking the time to reach out to us by opening this issue. So that you're aware, the snippets you mentioned are a bit outdated as they referenced a previous version of the Svelte addon and don't reflect the current state of the integration. We're looking into it and hope to update the snippets shortly.

Have a fantastic day.

Stay safe

**Comment by Ankush1oo8** [comment]
can I work On this

**Comment by jonniebigodes** [comment]
@Ankush1oo8, we appreciate your willingness to help out 🙏 ! However, we are working on getting them updated, and a pull request should be up soon. I hope you don't take it the wrong way. 

We'd love your contribution. Feel free to check the [Good first issues](https://github.com/storybookjs/storybook/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) and let us know if you're interested in working on another issue. In the interim, I'll remove the `help wanted` and `good first issue` labels to avoid confusion.

Have a great day.

Stay safe

**Comment by Ankush1oo8** [comment]
Okey

**Comment by jonniebigodes** [comment]
Again, thank you for reporting this and informing us of the issue using Svelte's examples. I've just merged a pull request that will address this issue. I hope you don't mind, but for now, I will close this issue.

Feel free to ping me if you find any issues, and I'll gladly re-open it.

Hope everyone has a great day.

Stay safe

**Comment by Ankush1oo8** [comment]
Okey
