### ISSUE TITLE
[Documentation]: Link to advanced/legacy action usage is broken

### ISSUE THREAD

**Issue by KrofDrakula** [storybookjs/storybook#29496]
### Describe the problem

Page: https://storybook.js.org/docs/essentials/actions#advanced--legacy-usage

The link to the advanced actions readme is broken:

https://storybook.js.org/addons/actions/ADVANCED.md

**Comment by jonniebigodes** [comment]
Thanks for reporting this and letting us know of this issue. We appreciate it 🙏 ! A recent pull request was merged to fix this issue, and hopefully, it will be deployed and the documentation updated.

I hope you don't mind, but I'm going to close this issue for the time being. I'll be more than glad to re-open it if it resurfaces.

Hope you have a fantastic day.

Stay safe
