### ISSUE TITLE
[Bug]: vite builder is incompatible with vite v6

### ISSUE THREAD

**Issue by leiit** [storybookjs/storybook#29565]
### Describe the bug

Attempting to build a storybook using `builder-vite` with latest Vite betas fails. Development environment works as expected.

To reproduce:
1. `pnpm dlx storybook@latest init`
2.  Choose vite+react
3. `pnpm install -D vite@beta`
4. `pnpm build-storybook`

Results in:

```
> storybook build

@storybook/core v8.4.2

info => Cleaning outputDir: storybook-static
info => Loading presets
info => Building manager..
info => Manager built (139 ms)
info => Building preview..
info Using tsconfig paths for react-docgen
vite v6.0.0-beta.6 building for production...
✓ 0 modules transformed.
x Build failed in 24ms
=> Failed to build the preview
[vite:build-html] Could not load ./sb-preview/runtime.js: ENOENT: no such file or directory, open './sb-preview/runtime.js'
file: ./iframe.html
Error: Could not load ./sb-preview/runtime.js: ENOENT: no such file or directory, open './sb-preview/runtime.js'
```

Versions up to `vite@6.0.0-beta.5` worked fine. See their [changelog](https://github.com/vitejs/vite/blob/v6.0.0-beta.9/packages/vite/CHANGELOG.md#600-beta6-2024-10-28) for what changed between betas 5 & 6.

### Reproduction link

https://github.com/leiit/sb-vite6

### Reproduction steps

```
corepack enable
pnpm i
pnpm build-storybook
```

### System

```
Storybook Environment Info:

  System:
    OS: macOS 15.0
    CPU: (10) arm64 Apple M1 Pro
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.11.0 - ~/.asdf/installs/nodejs/22.11.0/bin/node
    npm: 10.9.0 - ~/.asdf/plugins/nodejs/shims/npm
    pnpm: 8.15.8 - ~/.asdf/installs/nodejs/22.11.0/bin/pnpm <----- active
  Browsers:
    Chrome: 130.0.6723.116
    Safari: 18.0
  npmPackages:
    @storybook/addon-essentials: ^8.4.2 => 8.4.2 
    @storybook/addon-interactions: ^8.4.2 => 8.4.2 
    @storybook/addon-onboarding: ^8.4.2 => 8.4.2 
    @storybook/blocks: ^8.4.2 => 8.4.2 
    @storybook/react: ^8.4.2 => 8.4.2 
    @storybook/react-vite: ^8.4.2 => 8.4.2 
    @storybook/test: ^8.4.2 => 8.4.2 
    eslint-plugin-storybook: ^0.11.0 => 0.11.0 
    storybook: ^8.4.2 => 8.4.2 
```

**Comment by yannbf** [comment]
Hey @leiit thank you so much for reporting this issue, investigating which version caused it and providing a repro! This is just perfect to help us get a fix sooner. We've contacted the Vite team and a fix is on the way.

**Comment by yannbf** [comment]
This should be fixed in the upcoming release of Vite https://github.com/vitejs/vite/pull/18618

**Comment by yannbf** [comment]
I'll be closing this issue since it's not related to Storybook per se. The fix PR in Vite has been merged but not yet released, I assume it will happen soon!
