### ISSUE TITLE
[Bug]: Weird coverage report

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#29597]
### Describe the bug

Reproduction:

1. Create empty directory
2. `npx storybook@latest init` => React + vite + TS
3. `npx storybook add @storybook/experimental-addon-test`
4. `npx vitest --coverage`
5. `npx http-server coverage`

Coverage contains weird story paths:

![Image](https://github.com/user-attachments/assets/01addccd-05e4-4538-95a0-bd2ccce519a5)

### Reproduction link

https://github.com/shilman/react-vite-84-coverage-repro

### System

```bash
any
```

**Comment by JReinhold** [comment]
I've confirmed this is fixed by https://github.com/vitest-dev/vitest/pull/6905 in Vitest [v2.2.0-beta.2](https://github.com/vitest-dev/vitest/releases/tag/v2.2.0-beta.2)
