### ISSUE TITLE
[Bug]: Addon test includes stories in coverage reports

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#29613]
### Describe the bug

When running vitest with --coverage using Storybook Test plugin, the reports include story files, which is not expected and affects coverage calculations:

![Image](https://github.com/user-attachments/assets/acbc494b-1226-4cc4-9670-af285962cb4c)

The solution is rather simple but **has to be done in user land**. You can fix it by adding this config to your main vitest (or vite) config:

```ts
// vitest.config.ts
import { defineConfig, coverageConfigDefaults } from 'vitest/config'

export default defineConfig({
  // ... rest of your config
  test: {
    coverage: {
      exclude: [
         ...coverageConfigDefaults.exclude, 
         '**/*.stories.*' // or whatever else the users use, e.g. '**/*.story.*' or '**/stories.*'
       ], 
    }
  }
})
```

This change can't be added in a workspace file because workspaces can't define test.coverage options. Because of that, and the fact that Storybook Test plugin is set up at the workspace level, it makes it impossible for us to set up this configuration automatically as part of the plugin.

Potential solutions for us:
- Document this limitation and explain how to solve it
- When executing the postinstall script of addon test, automatically configure the vite configuration file to include coverage exclude options
- If we don't automatically do it, at least point a link to the docs in the postinstall script

Additionally, we could provide our own export with coverage defaults like so, to make it easier (?) for users:
```ts
// vitest.config.ts
import { defineConfig } from 'vitest/config'
import { coverageConfigDefaults } from '@storybook/experimental-addon-test/config'

export default defineConfig({
  // ... rest of your config
  test: {
    coverage: {
      exclude: [
         ...coverageConfigDefaults.exclude, // should include vitest defaults + Storybook defaults
         // Storybook defaults would be '**/*.stories.*', '**/*.story.*', '**/stories.*', '**/story.*'
       ], 
    }
  }
})
```

**Comment by shilman** [comment]
Duplicate to https://github.com/storybookjs/storybook/issues/29597

**Comment by crebelskydico** [comment]
I encountered the same issue with the `@vitest/coverage-v8` reporter. Switching to the Istanbul provider temporarily solved it for me.

**Comment by shilman** [comment]
@vanessayuenn @JReinhold This should work otherwise the coverage feature is broken out of the box. Bumped this up in priority.

**Comment by psychobolt** [comment]
I was a bit lost on why my coverage settings weren't applied. Did a bit digging and found out `coverage` is only applied for root configs and not workspace level. The added https://storybook.js.org/docs/writing-tests/test-coverage#set-up didn't mention about that, only reference is https://vitest.dev/guide/workspace.html . I believe it would be helpful to update the docs, maybe supply an example for workspace setup e.g.

```ts
// /vitest.workspace.ts
import { defineWorkspace } from 'vitest/config';

export default defineWorkspace([
  'vitest.config.ts', // <-- coverage settings are only applicable here
  'some-other-workspace/vitest.config.ts'
]);
```
