### ISSUE TITLE
[Bug]: Showing/hiding the context menu can cause the whole sidebar to reflow

### ISSUE THREAD

**Issue by JReinhold** [storybookjs/storybook#29651]
https://github.com/user-attachments/assets/d4e13ec4-905f-4d73-93ac-92178e87ef23

Discussed internally at https://chromaticqa.slack.com/archives/C07AXQABXDZ/p1731662493946129

The solution we settled on: Have the button absolute positioned so that it doesn’t reflow layout when visible. This may partially overlap the text:

<img width="268" alt="Image" src="https://github.com/user-attachments/assets/4f7bf76c-4b01-4d06-816e-c41ed2645b75" />

**Comment by INDHU1402** [comment]
Hello @JReinhold 
I came across this issue and would like to work on resolving it. Could you please assign it to me ?

**Comment by JReinhold** [comment]
No assignment necessary, yes u can just open a PR when you're ready
