### ISSUE TITLE
Gracefully handle coverage dependencies on `@vitest/coverage-v8`/`@vitest/coverage-istanbul`

### ISSUE THREAD

**Issue by JReinhold** [storybookjs/storybook#29721]
Running and enabling coverage in the testing module requires that a coverage provider package is installed. We want to handle this gracefully in multiple ways. The built-in Vitest coverage packages are `@vitest/coverage-v8` and `@vitest/coverage-istanbul`.

1. During `npx storybook add @storybook/experimental-addon-test`, we should detect if none of the built-in packages are installed, and ask the user if they want to install `@vitest/coverage-v8` (as that is the default) to enable coverage in Storybook.
2. When running SB, we should detect if the coverage provider package isn't installed. If it isn't disable the Coverage checkbox in the UI with a tooltip explaining why it can't be enabled.

The complexity here is that [users can specify `'custom'` coverage providers](https://vitest.dev/guide/coverage.html#custom-coverage-provider), in which case they don't need any of the two built-in packages installed. we need to handle this case in both 1 and 2.

Original discussion: https://chromaticqa.slack.com/archives/C07AXQABXDZ/p1732659153084449

**Comment by ndelangen** [comment]
I'm doing a follow-up PR to improve the message
