### ISSUE TITLE
[Bug]: Sidebar items wrap to the next line when context menu icon is show

### ISSUE THREAD

**Issue by ghengeveld** [storybookjs/storybook#29740]
The problem: 

https://github.com/user-attachments/assets/3688d524-85c3-48fc-a781-509d9be26657

The solution: always reserve space for the icon, even when it's not shown.

![Image](https://github.com/user-attachments/assets/21f0c7d7-e963-4093-973d-b5a29af8f3e9)

**Comment by JReinhold** [comment]
Closing as duplicate of https://github.com/storybookjs/storybook/issues/29651
