### ISSUE TITLE
[Bug]: The content of the testing module is pushed down when tests are run

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#29742]
The content of the testing module gets pushed down if you access a browser that that already had any statuses in the sidebar.

The gif here shows a tab where no state is saved, then it goes to a tab where I had run a single test.

![Image](https://github.com/user-attachments/assets/16f9ae4e-ca70-4d36-bdae-629d2cbc6a28)

**Comment by JReinhold** [comment]
I'm pretty sure this is fixed. If not, feel free to re-open
