### ISSUE TITLE
Testing Module doesn't communicate properly that Vitest is unresponsive/restarting

### ISSUE THREAD

**Issue by JReinhold** [storybookjs/storybook#29784]
Sometimes we're restarting Vitest, which usually takes less than a second, but during that time, triggering a run won' work, it will be ignored. This can eg. happen when you're toggling coverage and immediately trigger a run, it doesn't do anything.

What happens is:

1. changing a config (coverage/a11y) is debounced to 2s. After that you see "Settings saved" with a green border
2. Vitest is restarted, in that time it's unresponsive.

I see two ways to fix this:

1. Disable the run button whenever we know that Vitest is restarting or otherwise unresponsive.
2. Queue requests when Vitest is restarting, triggering them when Vitest is ready. We probably don't want an actual queue system for this, just "trigger the most recent action". Lining up multiple actions could create a confusing situation.

Originally reported on Discord:

![Image](https://github.com/user-attachments/assets/7aece465-1519-49e9-8796-fc470a4a81c1)

**Comment by ghengeveld** [comment]
Seems like we may need a "starting" status. I had that implemented for the "stuck state" issue last week but didn't continue down that road because I found a simpler solution. Maybe we have a new use case for it here?
