### ISSUE TITLE
[Bug]: Test addon init should update framework in Next projects

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#29796]
### Describe the bug

```sh
mkdir nextjs-test
cd nextjs-test
npx storybook@next init
npx storybook add @storybook/experimental-addon-test
```

The installer should prompt me about switching my framework to `@storybook/experimental-nextjs-vite`. Otherwise the CT UI won't show up in the testing module

### Reproduction link

N/A

### System

```bash
any
```

**Comment by ndelangen** [comment]
So:

- modify the `main.ts` config
- install the new framework
- uninstall the old framework
