### ISSUE TITLE
iframe.html is not aligned in webpack.config.js' `publicPath`

### ISSUE THREAD

**Issue by chardskarth** [storybookjs/storybook#3699]
I can confirm, believing to experience [the same issue](#1291)

**"manager.bundle.js" and "preview.bundle.js" is requested relative to my publicPath but not for "iframe.html".**

### Details

I'm trying to host storybook's output on a path (`http://something.com/storybook`) and "iframe.html" is being requested at `http://something.com/` where `/storybook` is my publicPath in my webpack.config.js

### Steps to reproduce

*Build the project and see manager.bundle.js. Search for "iframe.html" and see that publicPath is not included.*

Upon quick investigation, I think [this seems to be the problem](https://github.com/storybooks/storybook/blob/607f81856994ba23711b8a60039ca1e53c0bac87/lib/core/src/client/manager/provider.js#L35). But I wonder If that line can check the webpack's publicPath to append to.

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react 3.4.2

### Affected platforms 

**N/A**

### Screenshots / Screencast / Code Snippets (Optional)

**N/A**

**Comment by danielduan** [comment]
I wonder if simply changing that url to `./iframe.html?...` would fix the problem.

**Comment by igor-dv** [comment]
Is it still a problem after the discussion in #3172

**Comment by ebrentnelson** [comment]
+1 I am using storybook in a bit of a weird way where we upload all files to a CDN and serve from a server that wants to point to CDN for all static files. So we make great use of `publicPath`. However, for `iframe.html` we've had to be a bit creative (essentially create a redirect rule on the server). It would be lovely if we could avoid that.

**Comment by signal-intrusion** [comment]
Can confirm this show-stopping bug.

**Comment by sarahbethfederman** [comment]
This is an issue for us as well. Having to set the --preview-url flag in addition to the publicPath to get the same result was confusing

**Comment by monkeychops** [comment]
> +1 I am using storybook in a bit of a weird way where we upload all files to a CDN and serve from a server that wants to point to CDN for all static files. So we make great use of `publicPath`. However, for `iframe.html` we've had to be a bit creative (essentially create a redirect rule on the server). It would be lovely if we could avoid that.

Also using story book in this way, served from a docker container on a large corporate cluster and built using storybook-build. It needs a custom uri which i set using publicPath but there is no way of changing the iframe path. Please help

**Comment by valentinpalkovic** [comment]
This issue seems to be solved. Please let me know if the issue still pops up. Closing for now.
