### ISSUE TITLE
Add ability to sort roots for stories

### ISSUE THREAD

**Issue by dietergeerts** [storybookjs/storybook#3730]
It would be great if you could sort the roots for story trees. We're trying to create a toolkit with it and have to root sections: 'design-tokens' and 'components' and want to have the design-tokens come before components, but now it's sorted alphabetically because they're loaded by folder structure. There is an option to sort stories by kind, but sorting the roots would be nice to as an extra option.

**Comment by igor-dv** [comment]
You can ensure the order of the stories, by requiring your stories in this specific order:

That how we have a `Welcome` story in the beggining in our examples:
![image](https://user-images.githubusercontent.com/7867954/41422679-19d9291e-7002-11e8-86d2-b1063665ad3c.png)

in config.js:

```js
import { configure } from '@storybook/angular';

function loadStories() {
  // put welcome screen at the top of the list so it's the first one displayed
  require('../src/stories');

  // automatically import all story ts files that end with *.stories.ts
  const req = require.context('../src/stories', true, /\.stories\.ts$/);
  req.keys().forEach(filename => req(filename));
}

configure(loadStories, module);
```

**Comment by dietergeerts** [comment]
Ow, nice, so as the roots are folder based, I can do two require.context, for each folder. Though if we add folders, we need to change that too. I would prefer an option to sort the root, as the option to sort the stories is available.

**Comment by creatyvtype** [comment]
I'd like to resurface this. Sorting the sections should be more configurable than this arbitrary import order.

**Comment by shilman** [comment]
Reopening since there's useful info and closing #6327 as a dupe

Also related: #5827

**Comment by creatyvtype** [comment]
Let's keep this alive.... still want to know how best to sort the stories without hacky solutions.

**Comment by shilman** [comment]
@creatyvtype this was fixed in `5.2.0-alpha.31`:

- Core: Story sorting ([#6472](https://github.com/storybookjs/storybook/pull/6472))

**Comment by jugglingcats** [comment]
Am not sure why this is closed in favour of #6472 as that issue is about sorting within roots not the roots themselves. I can't find a way of sorting the roots apart from the import hack above which, as various people mention, isn't scalable and doesn't work well if you stories are next to your components. Should this issue be re-opened @shilman?

**Comment by shilman** [comment]
Does this work for you? https://github.com/storybookjs/storybook/pull/9188

**Comment by pladaria** [comment]
please, re-open

**Comment by thedamon** [comment]
Outside of waiting for v6.0.. if you can't wait.. a neat trick to sort sections while dynamically loading your stories that works now feels a little less hacky:
in a file that always loads first (`_global.stories.js` or something) you can define each section with an intro story that describes the section.. and then let the rest of the stories load where they will.

Benefit: you get a nice little intro page explaining what each section is for!
Drawback: you have to figure out what to say in an intro page explaining what each section is for!

Example:

```
storiesOf('Atoms|(intro)', module).add(
  'Atoms',
  () => ({
    template: `
    <div class="container">
      <h1>Atoms</h1>
      <p>Atoms are cool, atoms are great, come for the atoms, stay for this highly scintillating sentence</p>
    </div>
    `
  }),
  { storyshots: false }
);
```

**Comment by jkarttunen** [comment]
Stupid problems call for stupid solutions.
I renamed all to folders and prepended them with category number.

1_button 
1_Input
2_grid
2_stack
3_hero
3_section
