### ISSUE TITLE
Can't mock date on stories for Storyshot

### ISSUE THREAD

**Issue by chris-fran** [storybookjs/storybook#3809]
### Bug or support request summary

I am unable to mock the date so that my Storyshots snapshot tests are always fixed to a date.

### Steps to reproduce

I didn't find any info on how could I do this, so instead, I wrapped the `initStoryshot()` call inside describe blocks so that I could set up and tear down.

```
describe('Storybook', () => {
  const todayDate = '2018-06-26T14:46:36.000Z';
  beforeAll(() => mockDate(todayDate));
  afterAll(() => resetDate());

  describe('second level describe block', () => {
    initStoryshots({
      renderer: shallow,
    });
  });
});
```

The date is not being mocked when I call `new Date()` inside my stories. So I guess wrapping it on a describe doesn't work.

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react 3.4.6

**Comment by bonnici** [comment]
I would like to find a solution to this. My use case is a calendar component that is styled differently "today" than it is on other days.

**Comment by igor-dv** [comment]
You can try something like this:

(The example is for the v4)

```js
import initStoryshots, { shallowSnapshot } from '@storybook/addon-storyshots'

shallowSnapshot.beforeAll(() => mockDate(todayDate));
shallowSnapshot.afterAll(() => resetDate());

// you can also add "beforeEach" and "afterEach"

initStoryshots({
  test: shallowSnapshot,
  /* rest of the params you need */
});
```

LMK if it works for you.

**Comment by annewanghy** [comment]
hi , it seems not solved yet, I have the same problem with https://github.com/storybookjs/storybook/issues/3809#issuecomment-428785848, the beforeAll is not a function.

**Comment by Luonstreak** [comment]
this bug is still ongoing, please reopen

**Comment by ssaric** [comment]
Any solution whatsoever? I even tried with `lolex` to init the date before storyshots, but no luck.

**Comment by Vanuan** [comment]
I think the issue here is that story files are loaded before the first `describe`.

Most likely you have `new Date()` in the body of stories.

So move the date creation into the function. If you had this:

```
const updatedAt = new Date();

storiesOf('MyComponent').
add('default', () => {
  <MyComponent updatedAt={updatedAt} />
})
```

change it to this:

```
const updatedAt = () => new Date();

storiesOf('MyComponent').
add('default', () => {
  <MyComponent updatedAt={updatedAt()} />
})
```

**Comment by Vanuan** [comment]
Also, be sure you have the mock before any module is imported. In you jest config:

```
module.exports = {
  setupFilesAfterEnv: ['./jest.setup.js'],
};
```

And mock the date in that `./jest.setup.js` file:

```
  beforeAll(() => {
    MockDate.set(new Date(2019, 5, 24), 0);
  });
```

**Comment by Vanuan** [comment]
So 2 things to remember:
1. Your mock should be installed before `moment` is loaded (which memoizes the reference to the real Date object)
2. No date creation should be executed in the body of your modules. I.e. no `Date` singletons, only factories.
