### ISSUE TITLE
Configurable keyboard shortcuts

### ISSUE THREAD

**Issue by ndelangen** [storybookjs/storybook#3984]
Keyboard shortcuts are hard-coded atm, they are different for MacOS & Windows, and they are not really the absolute most user-friendly.

It's be great if users could decide for themselves which keyboard shortcuts make sense to them.

We should provide a config for keyboard shortcuts and possibly add a way for users to config shortcuts from within the app itself. (sync back to config-file or local override in localStorage).

Happy to assist anyone willing to take this on!

**Comment by Jessica-Koch** [comment]
@ndelangen I would be willing to work on this, I personally had an issue with <kbd>⌘</kbd><kbd>⇧</kbd> <kbd>C</kbd> being taken because I use that specific command for the Chrome inspector.

**Comment by Jessica-Koch** [comment]
@ndelangen, I assume that you want users to have the ability to change the existing shortcuts, but are there any additional ones you had in mind to configure?  Otherwise, I can start working on the customizability of the existing shortcuts

**Comment by ndelangen** [comment]
@Jessica-Koch AWESOME, please checkout my ui-refactor branch
https://github.com/storybooks/storybook/pull/4086

We should develop this feature on top of this branch.

I haven't given how to do this a lot of thought yet, Would you want to schedule a online meeting to discuss perhaps?

**Comment by Jessica-Koch** [comment]
@ndelangen sounds great, I'm also on the storybook slack.  I'm glad you responded because I would love input on how the UI would ideally be implemented, I have some ideas but felt uncomfortable just throwing them together.

**Comment by ndelangen** [comment]
I messaged you on slack!

**Comment by yog3sha** [comment]
Is there any way to configure and change or remove any key from shortcuts of storybook so that developer can use his targeted functionality in his application on specific keys (ex. f for showing an image in view as fullscreen)?

**Comment by jeremyzilar** [comment]
This would be very helpful

**Comment by shilman** [comment]
This feature is finished AFAIK. Closing, please open enhancements to the existing functionality as separate issues.

<img width="666" alt="Example___Introduction_-_Page_⋅_Storybook" src="https://user-images.githubusercontent.com/488689/115484739-df8f6980-a285-11eb-8088-5f916e6426b3.png">
