### ISSUE TITLE
T-shirts for maintainers

### ISSUE THREAD

**Issue by ndelangen** [storybookjs/storybook#4023]
I should use some open-collective money and get some t-shirts made to handover or mail to maintainers!

Please add your size in a comment @storybooks/team, I'll consolidate into this first message. 

| maintainer | size |
|----|---|
| @Hypnosphi  | M    | 
| @tmeasday  | L    | 
| @ndelangen | M    | 
| @nm123github | M    | 
| @danielduan | S    | 
| @alexandrebodin | L |
| @Keraito | L |
| @igor-dv | L |
| @amcdnl | M |
| @thomasbertet | L |
| @wuweiweiwu | L |
| @mshaaban088 | M |
| @dangreenisrael | L |
| @psimyn | M |
| @theinterned | XL |
| @Gongreg | M |
| @rhalff | L |

**Comment by nm123github** [comment]
M

also if possible do send some stickers too :)

**Comment by igor-dv** [comment]
1 - Yey
2 - I have no idea... Is there any size table?

**Comment by dangreenisrael** [comment]
Can other people buy tshirts?

**Comment by danielduan** [comment]
Maybe we can start a TeeSpring or something?

**Comment by Keraito** [comment]
Think L, but definitely seconding @igor-dv and @nm123github.

**Comment by alexandrebodin** [comment]
Let's go for L !

**Comment by amcdnl** [comment]
`@amcdnl - M`

**Comment by igor-dv** [comment]
Ok, if I need to guess, I would choose **L**

**Comment by thomasbertet** [comment]
Not sure to deserve it but if you get enough money I would accept a L ahah :+1:  Thanks anyway! :100:

**Comment by wuweiweiwu** [comment]
L plz <3

**Comment by mshaaban088** [comment]
M if you consider inactive maintainers

**Comment by psimyn** [comment]
M please

**Comment by theinterned** [comment]
I haven’t been an active contributor in a while, but I’m a huge Storybook advocate in real life. 

**XL** please and thank you. 

Also seconds on the sticker request. My laptop has a perfect spot for it.

**Comment by rhalff** [comment]
@storybooks/team I'll go for the leftover **L**

I think @Hypnosphi deserves a jacket btw :1st_place_medal:
