### ISSUE TITLE
storiesOf name the same in two files (for nesting) but HMR causes only the update file to be listed

### ISSUE THREAD

**Issue by CurtisHumphrey** [storybookjs/storybook#4101]
### Bug or support request summary

1. You have two files each with storiesOf("same name") but with different .add( names).  
2. When storybook first loads both .add (both files) appear under the same group name as they should
3. You change one and on the hot module reloading (HMR) only the one that updates is left being displayed.
Expected: I would expect it to not remove other file's stories.

- @storybook/react 3.4.0

**Comment by CurtisHumphrey** [comment]
My guess is the fix will be somewhere in this file: https://github.com/storybooks/storybook/blob/v3.4.10/lib/ui/src/modules/api/actions/api.js

**Comment by bent0b0x** [comment]
I see a similar issue even if there is just one `storiesOf` call. If I have multiple `add`-ed stories, on page reload (via manual reload, live reload, or HMR), the first story is always the one that is rendered even if I had been previously viewing a different story.

```
storiesOf('A', module)
  .add("foo", () => <View id="foo" />)
  .add("bar", () => <View id="bar" />);
```


  ```@storybook/react-native@3.4.10
react-native@0.56.0
```

**Comment by ndelangen** [comment]
Yes, I understand how this happens.. You found an bug @CurtisHumphrey

Since the HMR executes only a single module (the one that change) the other one is lost.

---

Our advice right now would be to never have multiple files inject the same story.

---

Would you want to try to fix the bug together @CurtisHumphrey ?

**Comment by CurtisHumphrey** [comment]
Yes. There could be more than one way to fix this bug.  We could A) try to store what adds have been attached to a given storiesOf label and then with a HMR is called simple merged the news adds with the old ones (although that means add removals wouldn't be caught). Or B) actually, I cannot seem to think of a B that does have more issues.
A would require a change in the storiesOf and .add functions. It would also mean that the label used in .add would have to be unique (that might already be the case).  Thoughts?
