### ISSUE TITLE
Enforce reloading iframe when switching stories

### ISSUE THREAD

**Issue by phaistonian** [storybookjs/storybook#4312]
There are times where it would be handy to have the whole iframe reloaded (hard reload) instead of just the `window.root` being hydrated / re-rendered.

Is there such an option?

Also, while I am here, is there a way to have, say, storiesOf _react_ AND storiesOf _html_ in the same storybook?

Thank you.

**Comment by diagramatics** [comment]
Resurfacing this, I had a case where I need the preview to be hard reloaded for a piece of code in our component that relies on using a variable declared in `window` on instantiation. Thinking of creating an addon that allows you to change the `window` piggybacked variables, but I believe I'll need this exposed in the preview API.

If this is alright I should be able to contribute to this.

**Comment by hipstersmoothie** [comment]
What would an ideal API look like? @diagramatics  @phaistonian

**Comment by phaistonian** [comment]
Perhaps

`.add('story', callback, true)`

or 

`.add(story, callback, { reload: true }`

Or you could have it for all subs like this:

`storiesOf(myStory, module, { reload: true })`

**Comment by diagramatics** [comment]
I don't have an opinion for a reload-on-story-switch, but I expect an API under `preview` will be needed for it?

**Comment by igor-dv** [comment]
```js
storiesOf(myStory, module, { reload: true })
```

this makes more sense to me since we can have an addon that uses this "reload" prop

**Comment by phaistonian** [comment]
@igor-dv or even `storiesOf(myStory, { module, reload: true })`

**Comment by ozzyogkush** [comment]
See #4945 as well

**Comment by chrisdrackett** [comment]
I'm running into this as well around loading external scripts that then stay around between navigation

**Comment by crimx** [comment]
Same here. This also relates to another ancient issue #729 where styles from different stories get piled up. With a clean slate option should be able to address these issues.

**Comment by Zodiase** [comment]
In my case, I'm using `react-helmet` to load certain external scripts. Some of those scripts may be loaders that inject more scripts into `<head>` and these don't seem to get cleaned up after switching stories AND after HMR.

**Comment by mgohin** [comment]
Same case for me, I'd be sad to remove Storybook for this reason :(

**Comment by mgohin** [comment]
For anyone needing a very ugly hack, I did this and it works.
I have one file per global variable, so I use an object to reference every global var and it's script. Adapt this part for your needs.

**./storybook/preview-head.html**

```html
<script>
  window.reloadLib = function () {
    return new Promise(resolve => {

      // not global function or var to avoid overrides
      const loadScript = function (scriptSrc) {
        return new Promise(resolve => {
          // load script
          const script = document.createElement('script');
          script.type = 'text/javascript';
          script.src = scriptSrc;

          if (script.readyState) {  // IE
            script.onreadystatechange = () => {
              if (script.readyState === 'loaded' || script.readyState === 'complete') {
                resolve();
              }
            };
          } else {  // Others
            script.onload = () => {
              resolve();
            };
          }

          document.getElementsByTagName('head')[0].appendChild(script);
        });
      };

      const scripts = {
        myLib: '/base/myLib.js',
        myLib2: '/base/myLibFile.js',
      };

      const promises = [];

      Object.keys(scripts)
        .forEach(key => {
          delete window[key];
          promises.push(loadScript(scripts[key]));
        });

      Promise.all(promises)
        .then(() => resolve());
    });
  };
</script>

````

**./stories/mystory.js**

```javascript
export const myStory= () => {
    // setTimeout to execute inside code after the returned HTML is loaded in DOM
    // I need this, maybe you don't ;)
    setTimeout(() => {
        window.reloadLib().then(() => {
            // all scripts are loaded and ready
        });
    });

    return 'my html';
};
```

**Comment by JKoehler11** [comment]
Anything updates on this? External JavaScript such as [https://van11y.net/accessible-tab-panel/](https://van11y.net/accessible-tab-panel/) will not work properly when moving from story to story or even on the same story in different tabs.

Was going to move my Pattern Library over to Storybook but now I'm thinking I will not be able to without this feature.

**Comment by Kurtmcmurt** [comment]
I know this is a bit of a "golden oldie" but I've been trying to adapt the govuk component library into Vue 3, largely successful but a bit of a pain in the rear. Nevertheless, managed to get all styles and scripts in for the components which is great. BUT... 

I needed the Story to do a hard refresh on load. Whilst this is usually a great thing (for optimisation and such) it isn't when you need to initialise window functions; the window functions remained but the dom needed getting rid of. 

I made a little helper function to help me out a bit. It might help someone so thought I'd share 👍 

```
DIR: middleware/trigger.js
export const checkWindow = () => {
  let counter = 0;
  let classList = document.body.classList

  classList.contains('initAll-called-govuk') && window.location.reload()
  
  if (counter === 20 || classList.contains('initAll-called-govuk')) return;
  
  setTimeout(
    () => {
      counter++
      window.parent.window[0].GOVUKFrontend.initAll()
      classList.add('initAll-called-govuk');
    }, 500
  )
}

```
And then in a MDX file:
```
import { Meta, Story } from '@storybook/addon-docs';

import Accordion from './Accordion.vue';
import { checkWindow } from '../../middleware/trigger'

<Meta 
  title="GovUK/Accordion"
  component={ Accordion }
/>

export const Template = (args) => ({
    components: { Accordion },
    template: '<Accordion />',
    created () {
      checkWindow()
    }
})

# Default

<Story
  name="default"
>
  {Template.bind()}
</Story>
```

It's literally just to get it working with SB. Might not be the cleanest but I if someone can improve on or know of a better way then YAY!!!!

**Comment by cplumley** [comment]
I ran into a similar-ish issue where I needed a function to be called when a new story rendered. I am going to place the solution that I came up with below. This code exists in `preview-body.html`. Essentially, I am adding a listener to the document for node changes and calling the functions below when that happens:
```javascript
const config = { attributes: false, childList: true, subtree: true };

const observer = new MutationObserver(() => {
   // Place your scripts here
});

observer.observe(document.body, config);
```

**Comment by ndelangen** [comment]
If you want to do something (like refreshing the page) in the storybook life-cycle (like when switching stories)..
You can write a decorator, that runs everytime a story renders:
https://storybook.js.org/docs/react/writing-stories/decorators

**Comment by whitecrownclown** [comment]
For anyone looking for a workaround using `decorators`. 

```js
const forceReloadDecorator = (storyFn, context) => {
  if (context.globals.shouldReload) {
    context.globals.shouldReload = false;
    window.location.reload();
  }

  context.globals.shouldReload = true;

  return storyFn();
};
```

**Comment by dos-format-d** [comment]
Hey everyone,

@whitecrownclown ’s workaround worked perfectly for Storybook versions <8. However, after updating to the latest Storybook version, it no longer works because the globals object is no longer persisted across stories.

I’ve already tried adding the following code to the preview object, but ran into an issue:
	•	When defaultValue is set to true, it causes an infinite reload loop.
	•	When defaultValue is set to false, nothing happens.

Here’s the code:
```ts
globalTypes: {
    shouldReload: {
        name: "Should Reload",
        type: "boolean",
        defaultValue: false,
    },
},
```

Does anyone have an idea how to fix this? 😊
