### ISSUE TITLE
Storybook CLI start/build

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#4427]
## Why

Want to make the CLI `sb` the primary point of interaction for users on the command-line and `start/build` are low-hanging fruit. Part of the #1108 epic.

## What 
- [ ] add `sb start` and `sb build` to the CLI
- [ ] update `sb init` to install `@storybook/cli`
- [ ] update `sb init` templates to use `sb start/build` instead of `start/build-storybook` in `package.json` scripts

**Comment by ndelangen** [comment]
AFAIK this is done.
