### ISSUE TITLE
babel-preset-vue missing as peer dependency

### ISSUE THREAD

**Issue by y-nk** [storybookjs/storybook#4505]
#### In a new directory : 

1. basic install : `npm i --save-dev @storybook/vue@rc`

2. peer dependencies from storybook : `npm i --save-dev babel-loader vue-loader vue-template-compiler && npm i --save vue`

3. package related peer dependencies: `npm i --save-dev @babel/core`

4. add run script to package.json : 

```patch
"scripts" {
+  "storybook": "start-storybook -p 9001 -c .storybook"
},
```

5a. minimal `.storybook/config.js` : 

```js
import { configure } from '@storybook/vue';

configure(() => {
  require('../stories')
}, module);
```
5b. minimal entrypoint with demo :

```js
import { storiesOf } from '@storybook/vue';

storiesOf('demo', module)
  .add('...', () => ({
    template: '<span>hello world</span>',
  }));
```

Now it's time to run :

```
> start-storybook -p 9001 -c .storybook

info @storybook/vue v4.0.0-rc.1
info
(node:16619) ExperimentalWarning: The fs.promises API is experimental
info => Loading presets
ERR! Error: Cannot find module 'babel-preset-vue'
```

**To fix it :** add `babel-preset-vue` as peer dependency in `@storybook/vue/package.json`

Meanwhile : `npm i --save-dev babel-preset-vue`

**Comment by igor-dv** [comment]
Thanks. It's duplicate to #4475

**Comment by y-nk** [comment]
@igor-dv installing latest @storybook/vue@5.1.9 this is still a valid bug

**Comment by shilman** [comment]
@y-nk but it's a dupe to #4475 so let's solve it there?
