### ISSUE TITLE
Throw warning if different version of the storybook addon is installed

### ISSUE THREAD

**Issue by adamchenwei** [storybookjs/storybook#4617]
**Is your feature request related to a problem? Please describe.**
It took me few days to realize a import error with jest was a result of inconsistent addon version for storybook! I would have been easily resolved it if it was mentioned in the installation phase, which nothing has been notified.
**Describe the solution you'd like**
I would like either:
A. A warning / error throw when `npm install` or `yarn install` to indicate there are inconsistent storybook addon is installed and may cause error prevent storybook from running correctly with its addons.
B. Same warning as A but warning when `npm run storybook`
**Describe alternatives you've considered**
Not in mind
**Are you able to assist bring the feature to reality?**
yes, I can, but I will need some pointer on entry points!

**Additional context**
NA

**Comment by AlokTakshak** [comment]
@igor-dv  is it still open?

**Comment by adamchenwei** [comment]
is this hard to add?

**Comment by adamchenwei** [comment]
I can see if I can do it, if I can get point to the right file usually this got handled?

**Comment by PrathameshAshra** [comment]
is it still open ?

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. We do some of this kind of warning in 7.0. Pease open a new issue referencing this one if this is still relevant in SB 7.x.
