### ISSUE TITLE
Inspector broken in React Developer Tools

### ISSUE THREAD

**Issue by nickmccurdy** [storybookjs/storybook#4769]
**Describe the bug**
In Storybook 4, React devtools is now properly scoped to the story (rather than Storybook itself). However, the inspect button in devtools does not let you select anything within the story pane. Additionally, the scope is broken when doing a production build with storybook-build.

**To Reproduce**
1. Open Storybook using Storybook React
2. Install and open React devtools
3. Note that story scope is properly displayed
4. Click inspect button, then a component inside the story pane
5. Note that nothing inside the pane can be selected

**Expected behavior**
Inspecting should work just like it does outside an iframe.

**Screenshots**
![image](https://user-images.githubusercontent.com/927220/48319027-785e2d00-e5d6-11e8-8e43-b3519fe285a4.png)

**Code snippets**
https://github.com/MyCryptoHQ/ui

**System:**
 - OS: macOS
 - Device: Macbook Pro 2015
 - Browser: Chrome
 - Framework: React
 - Version: 4.0.0

**Comment by titimoby** [comment]
I have this issue with 4.0.9 also but more, I have it with 3.4.11

**Comment by bkilrain** [comment]
I'm having the same issue - v4.1.4

**Comment by nickmccurdy** [comment]
I'm still having this issue with Storybook 4.1.6

**Comment by wlkrdv** [comment]
A temporary workaround is:

- Install react-devtools as standalone app globally: `npm i -g react-devtools`
- Inject in each iframe the tag  `<script src ="http://localhost:8097"></script>` through `.storybook/preview-head.html`.

Running up: `react-devtools`, it is possible to debug the components without problems.

Checked with react-devtools@3.6.0

**Comment by shilman** [comment]
Is this still an issue in SB5?

**Comment by jasonbarone** [comment]
> Is this still an issue in SB5?

Ya, looks like it. The inspector scopes to the iframe.

**Comment by vdh** [comment]
It's still an issue, stalebot

**Comment by ypresto** [comment]
@wlkrdv 's solution (`npm i -g react-devtools`) is the official of react-devtools.
https://github.com/facebook/react-devtools/issues/76#issuecomment-280073254

Perhaps we can integrate react-devtools directly with `@storybook/react` package.

**Comment by Grsmto** [comment]
I suppose it's not a Storybook issue but it's more related to React Dev Tools but it really makes me wonder if people are actually using Storybook as a development sandbox. I don't really see how you can build React components without being able to use the dev tool.

The workaround doesn't actually work since you can't use the "target" (you have to open the tree manually one element after the other...).

**Comment by shilman** [comment]
@Grsmto I use storybook all day and have never used react dev tools in my life 😉 

What happens when you click the "eject" button in the upper-right hand corner of the SB5 UI to open the iframe in its own window? Does devtools work then?

**Comment by Grsmto** [comment]
Yeah that's actually the right workaround here! Thanks! :)

Haha then you should try it, I can't do without it :p

**Comment by vdh** [comment]
This issue has been a big headache for me when developing in Storybook, since the React Dev Tools' inspector is effectively broken.

There's a very roundabout workaround where I have to target the DOM element via Chrome's inspector, then make sure `$0` targets a relevant element, and _then_ switch back to React Dev Tools, which hopefully jumps to the relevant React component due to the `$0` integration. But it's quite a pain to do it that way.

**Comment by vdh** [comment]
I feel like the only workarounds so far have been variations of "just don't do that", which isn't really a workaround at all.

**Comment by shilman** [comment]
@vdh the definition of a workaround is that the user wants to do something, in this case select something in the story pane, and although there isn't a fix for it (the issue is still open) the user can hit the eject button, which actually provides a better DX. what am i missing here?

**Comment by nickmccurdy** [comment]
As far as I'm aware Storybook is meant to be a development environment, and I expected it to support React devtools as a result. Is there a way this can be fixed? If not I like the idea of embedding React devtools directly, as it does have standalone components.

**Comment by shilman** [comment]
@nickmccurdy i would gratefully accept a PR if you have a fix for this issue!

**Comment by vdh** [comment]
@shilman The problem is that eject button is just a different page. So it doesn't solve the issue of the broken inspector so much as it just reroutes you away from the main Storybook UI completely so that you never use the inspector on it. Hence why it feels like a "just don't do that".

**Comment by darkowic** [comment]
I would like to add also that react dev tool has a great feature `Highlight updates` but it also does not work with storybooks in an iframe.

**Comment by machineghost** [comment]
Please re-open this.  I'm still having the dev tools (Inspect Element specifically) not work in 2020 and to me this seems like a _major_ issue.

Also, it happens with or without the React dev tools installed.
