### ISSUE TITLE
Decorator Children Displayed In Story Source

### ISSUE THREAD

**Issue by Undistraction** [storybookjs/storybook#4801]
**Describe the bug**
If a decorator itself uses child components, those components are displayed in the Story Source. This can be seen in the following example, where the decorator uses a child component to handle the layout. Prop Tables are also displayed for each of these components. There is no way to exclude these components using the `withInfo` addon as they are internal to the Component.

**Screenshots**
![src](https://user-images.githubusercontent.com/161489/48629225-fb093280-e9b0-11e8-8030-1a0edcc58173.jpeg)

**Code snippets**
### Component
ProgressBar.js
```
import styled from 'styled-components'
import React from 'react'
import PropTypes from 'prop-types'
import { height, themeColor } from '../../styles/api/helpers'
import { ratioToPercentage } from '../../helpers/units'

const Layout = styled.div`
  ${height(1)};
  position: relative;
  width: 100%;
  background-color: ${themeColor(`inset`)};
  border-radius: 20px;
`

const Fill = styled.div`
  position: absolute;
  left: 0;
  height: 100%;
  background-color: ${themeColor(`primary`)};
  width: ${p => ratioToPercentage(p.progress)};
  border-radius: 20px;
`

const ProgressBar = ({ progress }) => (
  <Layout>
    <Fill progress={progress} />
  </Layout>
)

ProgressBar.propTypes = {
  progress: PropTypes.number,
}

ProgressBar.defaultProps = {
  progress: 0,
}

export default ProgressBar
```

### Decorator
VerticalLayoutDecorator.js
```
import React from 'react'
import styled from 'styled-components'
import VLayout from '../../components/layouts/VLayout'

const Layout = styled(VLayout).attrs({ spacing: 1 })``

const VerticalLayoutDecorator = storyFn => <Layout>{storyFn()}</Layout>

export default VerticalLayoutDecorator
```

### Story
ProgressBar.story.js
```
import React from 'react'
import { storiesOf } from '@storybook/react'
import VerticalLayoutDecorator from '../../storybook/decorators/VerticalLayoutDecorator'

import ProgressBar from './ProgressBar'

storiesOf(`ProgressBar`, module)
  .addDecorator(VerticalLayoutDecorator)
  .add(`Default`, () => (
    <React.Fragment>
      <ProgressBar progress={0} />
      <ProgressBar progress={0.25} />
      <ProgressBar progress={0.5} />
      <ProgressBar progress={1} />
    </React.Fragment>
  ))
```

### Displayed In Story Source:
```
<VerticalLayoutDecorator__Layout>
  <Unknown>
    <ProgressBar/>
    <ProgressBar progress={0.25} />
    <ProgressBar progress={0.5} />
    <ProgressBar progress={1} />
  </Unknown>
</VerticalLayoutDecorator__Layout>
```

**Expected behavior**
The Story Source Should Display:
```
<ProgressBar/>
<ProgressBar progress={0.25} />
<ProgressBar progress={0.5} />
<ProgressBar progress={1} />
```

**System:**
 - OS: OSX
 - Device: iMac
 - Browser: All
 - Framework: React
 - Addons:
    ```
    "@storybook/addon-a11y": "^4.0.7",
    "@storybook/addon-actions": "^4.0.7",
    "@storybook/addon-backgrounds": "^4.0.7",
    "@storybook/addon-info": "^4.0.7",
    "@storybook/addon-links": "^4.0.7",
    "@storybook/addon-notes": "^4.0.7",
    "@storybook/addon-options": "^4.0.7",
    "@storybook/addon-viewport": "^4.0.7",
    "@storybook/addons": "^4.0.7",
    ````
 - Version:
    ```
    "@storybook/react": "^4.0.7"
    ```

**Additional context**
Possibly related to: https://github.com/storybooks/storybook/issues/4759

**Comment by Glavin001** [comment]
I am also experiencing this problem. Please don't close as inactive 😅!

**Comment by Undistraction** [comment]
Yep. This is definit lyrics still a problem.

**Comment by Glavin001** [comment]
Still a problem, stalebot.

**Comment by Undistraction** [comment]
Still a problem. Please can a maintainer remove the inactive label.

**Comment by BycorSanchez** [comment]
Yep, same here. Global decorators work just fine, story decorators still have this issue.

**Comment by tonai** [comment]
Same problem for me.

I use the decorator for providing data to my component:
* material UI theme
* date provider for material-ui-pickers
* redux store
* ...etc

But it can't be provided with the global `addDecorator` because data might be different between components.
It would be great if this can be fixed with the local `addDecorator`.

I think the info addon is really nice, but not usable in my case :/

**Comment by Glavin001** [comment]
Still an issue.

**Comment by shilman** [comment]
Hmmm @tmeasday I bet this is due to https://github.com/storybooks/storybook/blob/next/MIGRATION.md#individual-story-decorators

**Comment by tmeasday** [comment]
How do you mean @shilman?

I'm confused though -- is this in the info addon? Have you tried the story source addon? I suspect it may work in this case.

**Comment by tonai** [comment]
[at this location](https://github.com/storybooks/storybook/blob/7251eac232a23408308959f857e06dc9be881955/lib/client-api/src/client_api.js#L208), global decorators are merged after local ones.

But to work properly, the info addon must be the first one.  
So by using local decorators it simply fail this rule.

Maybe local decorators must be merged after global ones.  
But I don't know if this change can impact other things...

The thing you can do in your project to get around this issue, is to remove the global `withInfo` decorator you have in your `.storybook/conffig.js` file and add a local `withInfo` decotors in each of your stories:
```js
storiesOf('Component', module)
  .addDecorator(withInfo)
  .addDecorator(story => (<Provider store={store}>{story()}</Provider>))
  .add(...);
```

**Comment by lookapanda** [comment]
@tonai I tried this but now the whole thing is wrapped around this (including the withInfo stuff) rather than just the source from the `.add()` :/

**Comment by tonai** [comment]
Hi @lookapanda ,
I have created a little example repo to show you how I am using it  : https://github.com/tonai/storybook-addon-info-example
If you look at info for the component in the demo it only show the source of the component event if I'm using the react-redux `<Provider>` as decorator.
Also tested with the 4.x version.

**Comment by maeligg** [comment]
Also experiencing this issue. @tonai 's workaround works (thanks !) but is not practical for our use case as we need both a global and a local withInfo decorator.

**Comment by shilman** [comment]
FYI redoing `addon-info` features as part of the Storybook Docs project. 

https://medium.com/storybookjs/storybook-docs-sneak-peak-5be78445094a

I plan to use the analysis from `addon-storysource` to determine the source to show, if possible, and that wouldn't have this problem. Will post here when there's something to try out, and for anybody who's interested there's a channel called `#docs-mode` in the Storybook Discord for project updates: https://discord.gg/UUt2PJb

**Comment by Undistraction** [comment]
@shilman I'll grin from ear-to-ear if you fix this.

**Comment by Undistraction** [comment]
Still an issue stale bot.

**Comment by shilman** [comment]
@Undistraction this is working well in `addon-docs` thanks to the storysource addon

**Comment by Undistraction** [comment]
@shilman great news. I'll try that out later today.

**Comment by westrem** [comment]
Still an issue

**Comment by chris-pearce** [comment]
Still an issue, be great if this could be fixed.

**Comment by stonecrafter** [comment]
Still an issue, please don't close :D

**Comment by jacklimwenjie** [comment]
Bump! Say no to stale bot

**Comment by Undistraction** [comment]
Still a problem stalebot.

**Comment by chris-pearce** [comment]
Still an issue.

**Comment by shilman** [comment]
If you haven't tried it yet, `addon-docs` is currently in beta and is designed to replace `addon-info`: https://docs.google.com/document/d/1un6YX7xDKEKl5-MVb-egnOYN8dynb5Hf7mq0hipk8JE/edit?usp=sharing

**Comment by stonecrafter** [comment]
Still an issue :(

**Comment by Fouaib** [comment]
i still have the same issue :(

**Comment by kelly-tock** [comment]
came across this issue after googling, I as well see the issue.

**Comment by ConneXNL** [comment]
Was this ever fixed?

**Comment by shilman** [comment]
Not that I know of. All dev effort is going into `addon-docs` now, which fixes this issue and many others: https://medium.com/storybookjs/storybook-docspage-e185bc3622bf

**Comment by ConneXNL** [comment]
> Not that I know of. All dev effort is going into `addon-docs` now, which fixes this issue and many others: https://medium.com/storybookjs/storybook-docspage-e185bc3622bf

Thanks! I came acros yesterday. It's indeed superior and it seems like there are just too many edge cases where using the info without being able to specify the component itself is not sufficient.
