### ISSUE TITLE
in mobile version, the bottom bar partially obscures stories list

### ISSUE THREAD

**Issue by adekbadek** [storybookjs/storybook#4896]
**Describe the bug**
In mobile version, the bottom bar partially obscures stories list, making the bottommost in the list unclickable

**To Reproduce**
1. open a long (taller than screen height) stories list in mobile view
2. the bottommost stories are obscured by the bottom UI bar 

**Expected behavior**
the bottom UI bar should not cover stories list

**Screenshots**
https://monosnap.com/file/hv6brrb7CuWRkPObCU7RQ6ZEMY7I2R

**Code snippets**
As a workaround, following code can be added to `manager-head.html`:
```
<style>
  @media (hover: none) {
    div > div > div > ul {
      padding-bottom: 80px !important;
    }
  }
</style>
```

**System:**
 - OS: iOS
 - Device: iPhone 5s
 - Browser: safari
 - Framework: react
 - Version: 4.0.9

**Comment by dandida95** [comment]
can i help out?

**Comment by igor-dv** [comment]
@dandida95, definitely you can!

**Comment by dpsmith3** [comment]
Does this still need work? Can I help?

**Comment by igor-dv** [comment]
This issue is still open, so yeah =)

**Comment by dsuarezlogans** [comment]
Hello! is still open? can I help on this?

**Comment by hannah-saurusrex** [comment]
Hi there, I just submitted a pull request for this fix. Let me know if I need to adjust anything for approval. Thanks!

**Comment by sanchitbansal10** [comment]
I think this issue is fixed. Can be closed
