### ISSUE TITLE
Add ability to include images and other assets in Markdown-based addons

### ISSUE THREAD

**Issue by ozzyogkush** [storybookjs/storybook#4976]
Designers and such may want to include high-res designs or wireframes and other assets directly in the `addon-info` pane (or other Markdown-based addons).

**Describe the solution you'd like**
When I add a MD image tag that points to a local file eg if my MD file is in

`./storybook/stories/component/component-addon-info.md`

```
![Test File](../../assets/images/test-file.png "Testing")
```

Webpack should be able to process that like it does normally imported images.

**Are you able to assist bring the feature to reality?**
maybe

**Comment by Kacppian** [comment]
Is this still open?

**Comment by ozzyogkush** [comment]
I haven't had a chance to try anything. I'm not sure if this is even possible, if it'd require usage of something like .mdx (MD mixed with JSX) to be able to resolve the included assets correctly, etc.

**Comment by shilman** [comment]
@Kacppian @ozzyogkush I'll be picking up work on rich documentation in Storybook as soon as the v5 release is out the door. If you're interested in collaborating please give me a holler on the Storybook discord!

Related: https://github.com/storybooks/storybook/issues/1147

**Comment by ozzyogkush** [comment]
On that note, I created a simple decorator at my work that lets us automatically inject the contents of MD files into a story. Basically if a file with the kebab-cased version of the story name exists in the current story directory, it applies it to the original addon. I implemented it for notes and info addons because our designers might want to put their info in one or the other without having to mess with any story source code. As this is the use case spawning this issue, it could be more robust or even a built-in feature of these 2 addons.

**Comment by shilman** [comment]
@ozzyogkush Cool! Any interest in contributing?

**Comment by Kacppian** [comment]
yup, would love to contribute!

**Comment by codyaverett** [comment]
@ozzyogkush my team has a similar use case.  I'd like to understand your solution more if you don't mind sharing.

TBH i was hoping that the notes plugin worked with images out of box 😅
Our workaround is simply to host images and other assets as static files. https://storybook.js.org/docs/configurations/serving-static-files/

**Comment by ozzyogkush** [comment]
@codyaverett we haven't had a hard requirement for images, I was really just looking ahead to possible future use cases. If you're asking about the decorator I mentioned above, I made general case MD addon extender that generates a new addon based o the original addon you specify and the function for merging the incoming context and story params with the auto-detected MD file's text. Then I created instances that worked with the Notes and Info addons, and register those instead of the original ones.

There are probably better ways to do it that integrate directly with the original addons and can hook into webpack's process though.

**Comment by cgatian** [comment]
I was able to pull this off in the MDX file by first importing the image, and then assigning it to an image tag.

```html
import ImageFile from './image.png';

<img src={ImageFile} />
```

**Comment by eduina** [comment]
Any advancement on this issue?

**Comment by shilman** [comment]
FYI `addon-info` is being superceded by `addon-docs`, which fixes a bunch of bugs and is easier to maintain. It’s reached release candidate (RC) status and will be properly released soon. Please give it a try! https://medium.com/storybookjs/storybook-docspage-e185bc3622bf

@ozzyogkush @MihaChicken @jvmccarthy @david-dogneton @Kacppian @codyaverett @cgatian @eduina

**Comment by ozzyogkush** [comment]
I'm fine w/closing this in lieu of the new docs addon being released soon. We haven't had a chance to even get to this in my project so no loss on my end.

**Comment by mhulse** [comment]
Out of curiosity, what is the answer? The link to the medium article doesn't offer any answers to this specific question.
