### ISSUE TITLE
Slow start React guide doesn't work

### ISSUE THREAD

**Issue by gretzky** [storybookjs/storybook#5051]
**Describe the bug**
I'm building a UI kit with React. My build is just react, babel, and rollup to compile. When adding storybook based on the slow start react guide- webpack doesn't fully compile and I'm left with a `Cannot get /` error on the defined port.

**To Reproduce**
1. Spin up a simple react project with just babel and rollup
2. Follow [this guide](https://storybook.js.org/basics/guide-react/)
3. `yarn run storybook`

Or just run this [demo repo](https://github.com/gretzky/storybook-slow-start-react-bug)

**Expected behavior**
It should bundle the stories and display them in the browser, according to the guide. These are the only steps it provides for adding storybook to an existing react project.

**Code snippets**
[Demo repo](https://github.com/gretzky/storybook-slow-start-react-bug)

**System:**
 - OS: macOS
 - Device:  MacBook Pro 2015
 - Browser: Firefox
 - Framework: React
 - Addons: N/A
 - Version: 4.0.0

**Comment by gretzky** [comment]
Probable duplicate of #5004

**Comment by wooly** [comment]
We are also having this issue.

**Comment by gretzky** [comment]
So what's the update here? Nearly 20 days and no response, and it's affecting more than just me.

**Comment by shilman** [comment]
There's something wrong with your `yarn.lock` file. When I remove it and reinstall, it works fine.

**Comment by gretzky** [comment]
@shilman I've tried multiple fresh installs, fresh directories, same issue.

**Comment by sophister** [comment]
same problem. open `http://localhost:9001/` just show me `Cannot GET /`. And I use the [guide-react](https://storybook.js.org/basics/guide-react/) to slow start. 

`package.json` is:

```json
{
  "name": "storybook-test",
  "version": "1.0.0",
  "description": "test storybook usage",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "storybook": "start-storybook -p 9001 -c .storybook"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@babel/core": "^7.3.3",
    "@storybook/react": "^4.1.12",
    "babel-loader": "^8.0.5"
  },
  "dependencies": {
    "react": "^16.8.2",
    "react-dom": "^16.8.2"
  }
}
```

directories are:

![image](https://user-images.githubusercontent.com/219501/53074016-9d8eff80-3524-11e9-9d01-f0122f20e350.png)

and `.storybook/config.js` is

![image](https://user-images.githubusercontent.com/219501/53074084-d3cc7f00-3524-11e9-92bf-273a2915c06a.png)

browser result:

![image](https://user-images.githubusercontent.com/219501/53074124-ec3c9980-3524-11e9-9193-08d029843a10.png)

**Comment by ndelangen** [comment]
I'll take a look what's going on

**Comment by ajbowler** [comment]
I ran into this issue after upgrading storybook v3 within a monorepo to v4.

There's zero console output in the browser or within stdout to tell me what errors, if any, are occurring, only this cryptic cannot GET/ message on the webpage.

**Comment by ndelangen** [comment]
I guess what we really need is an upgrade command in our CLI @ajbowler

**Comment by MonteKrysto** [comment]
I'm getting the same thing.  Any updates?

**Comment by gretzky** [comment]
Wow, this is a pretty fundamental issue here and nobody answering. This is why I continue to not use Storybook.

**Comment by MilosJo** [comment]
`Import { Link } from 'gatsby';`
breaks my Storybook... 
Tried upgrading `yarn`, removing `node_modules`, `yarn.lock` and `cache`,
now I get `Cannot GET /` error.
Any solutions?

**Comment by shilman** [comment]
@MilosJo did you follow these instructions? https://www.gatsbyjs.org/docs/visual-testing-with-storybook/

**Comment by MilosJo** [comment]
This is my `.storybook.config.js`
```
import { configure } from '@storybook/react';
import { action } from '@storybook/addon-actions';

global.___loader = {
  enqueue: () => {},
  hovering: () => {},
};

global.__PATH_PREFIX__ = '';
window.___navigate = (pathname) => {
  action('NavigateTo:')(pathname);
};

const req = require.context('../src', true, /\.stories\.js$/);

function loadStories() {
  req.keys().forEach(filename => req(filename));
}

configure(loadStories, module);
```
Roughly I would say they look pretty much the same.
Many thanks, @shilman

**Comment by MilosJo** [comment]
@shilman 
I haven't noticed that I need to create `webpack.config.js` file as well.
```
module.exports = (baseConfig, env, defaultConfig) => {
  // Transpile Gatsby module because Gatsby includes un-transpiled ES6 code.
  defaultConfig.module.rules[0].exclude = [/node_modules\/(?!(gatsby)\/)/]

  // use installed babel-loader which is v8.0-beta (which is meant to work with @babel/core@7)
  defaultConfig.module.rules[0].use[0].loader = require.resolve("babel-loader")

  // use @babel/preset-react for JSX and env (instead of staged presets)
  defaultConfig.module.rules[0].use[0].options.presets = [
    require.resolve("@babel/preset-react"),
    require.resolve("@babel/preset-env"),
  ]

  // use @babel/plugin-proposal-class-properties for class arrow functions
  defaultConfig.module.rules[0].use[0].options.plugins = [
    require.resolve("@babel/plugin-proposal-class-properties"),
  ]

  // Prefer Gatsby ES6 entrypoint (module) over commonjs (main) entrypoint
  defaultConfig.resolve.mainFields = ["browser", "module", "main"]

  return defaultConfig
}
``` 
Works now like charm.
Thanks again!

**Comment by shilman** [comment]
@MilosJo I guess you're using Storybook 4.x? Note that the custom webpack config has changed in 5.x if you decide to upgrade: https://github.com/storybooks/storybook/blob/next/MIGRATION.md#webpack-config-simplification

**Comment by MilosJo** [comment]
Hey @shilman 
Yeah, current project is run on Storybook 4.x.
Will migrate it this week to Storybook 5.x.
Thanks for the heads-up.
Much appreciated

**Comment by JimSRush** [comment]
This was breaking for me because my storybook and addon versions were:
 `"@storybook/react": "^4.0.0-alpha.25",` and `" "@storybook/addon-knobs": "^5.0.6",`. Once I dropped the addon version to `^4.0.6` it seemed to work ok.

**Comment by shilman** [comment]
@JimSRush try to use the same version of all `@storybook/*` packages if possible

**Comment by mlachance** [comment]
Just in case someone else stumbles across this in a Google search like I did, I want to repeat the fix that helped me:

## Delete your `package-lock.json` and your `node_modules` directory.

**Comment by daviddelusenet** [comment]
@mlachance why would this solve the problem? I'm now also experiencing this issue but I don't want to delete my `package-lock.json` since this can cause unexpected problems.

**Comment by dustinlacewell** [comment]
Hmm something in my repo changed and I'm now getting this, and have no idea what caused it.

**Comment by mlachance** [comment]
@daviddelusenet my experience is that the checksums in `package-lock.json` sometimes prevent the proper installation of dependencies, and it does not help that updating your Node version may cause breaking changes. 

Your `package-lock.json` should be committed in your Git repository anyways, so rolling back should it not work is still something you can do. And if you are curious, you can also simply check what changed after running `npm install`.

**Comment by sunny-mittal** [comment]
Hopefully posting this doesn't reopen the issue but for yarn users, if you set up storybook with the CLI commands which uses npm by default, you could run into this. The two package managers handle dependencies very differently and it turned out to be my issue. Trashing node_modules and package-lock and reinstalling with yarn fixed it.

**Comment by ctamas** [comment]
It can be caused by using the 
https://storybook.js.org/blog/storybook-6-migration-guide/
`npx sb upgrade`
NPM command to upgrade while otherwise using yarn.
No need to delete package file, just node_modules.

**Comment by ktryndchrs** [comment]
> Just in case someone else stumbles across this in a Google search like I did, I want to repeat the fix that helped me:
> 
> ## Delete your `package-lock.json` and your `node_modules` directory.

And if you ever get this error after, the solution that worked for me was `npm run install --force`

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"17.0.2" from the root project
npm ERR!   peer react@"^16 || ^17 || ^18" from @headlessui/react@1.3.0
npm ERR!   node_modules/@headlessui/react
npm ERR!     @headlessui/react@"1.3.0" from the root project
npm ERR!   58 more (react-dom, @heroicons/react, @storybook/addon-actions, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"15.x || 16.x || 16.4.0-alpha.0911da3" from @reach/router@1.3.4
npm ERR! node_modules/@storybook/api/node_modules/@reach/router
npm ERR!   @reach/router@"^1.3.4" from @storybook/api@6.3.7
npm ERR!   node_modules/@storybook/api
npm ERR!     @storybook/api@"^6.0.0" from storybook-addon-themes@6.1.0
npm ERR!     node_modules/storybook-addon-themes
npm ERR!       dev storybook-addon-themes@"6.1.0" from the root project
npm ERR!     4 more (storybook-tailwind-dark-mode, @storybook/addons, ...)
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/catherine/.npm/eresolve-report.txt for a full report.
```

**Comment by conner-sabin** [comment]
Yeah, I was having this same issue. Deleting the `package-lock.json` and `node_modules` and then running `npm install` worked for me. The storybook guide for migrating to storybook 6 gives the same advice at the bottom: https://storybook.js.org/blog/storybook-6-migration-guide/
![image](https://user-images.githubusercontent.com/84096523/129391948-3aa425ed-98db-46dc-9b60-07900edf3b57.png)

**Comment by Liu-10004** [comment]
To fix this, run start-storybook once with the --no-manager-cache flag, and hopefully Storybook will work correctly for you. You only need to use this flag once; after that, the cache should be in a good state. The docs advise against using this flag all the time for performance reasons.
Reference:https://githubmemory.com/repo/storybookjs/storybook/issues/14672
