### ISSUE TITLE
Error importing local dependency in a monorepo project

### ISSUE THREAD

**Issue by renatho** [storybookjs/storybook#5117]
**Describe the bug**
I have a monorepo project with the following structure:
```
- Project folder
  - .storybook
  - packages
    - package1
      - Package1.jsx
      - package.json
    - package2
      - Package.jsx
      - package.json
    ...
  - stories
  - RootProject.jsx
  - package.json
```
The packages are not transpiled (this is imported directly). It will be transpiled by the root project. And each package has its own dependencies.

In the root project, I have a storybook configured and in the storybook I have components that use other components imported from packages. When this packages import its own dependencies, the bug occurs.

If run the project directly through webpack, it works normally.

**To Reproduce**
1. Clone the repository where I simulated the problem: https://github.com/renatho/monorepo-with-storybook-bug
1. Run `npm install`
2. Run `npm start` and see it working. Output: "Hey! Dep1"
3. Run `npm run storybook` and see the bug with the message `Cannot assign to read only property 'exports' of object '#<Object>'`

**Expected behavior**
Import the component normally, like running with webpack on `npm start`.

**System:**
 - OS: MacOS Mojave
 - Device: Macbook Pro
 - Browser: Any
 - Framework: React
 - Version: 4.1.4

**Additional context**
I believe it is because the way that storybook uses the babel. See: https://babeljs.io/docs/en/config-files#6x-vs-7x-babelrc-loading

**Comment by renatho** [comment]
Using yarn workspaces it is not working too:
https://github.com/yarnpkg/yarn/issues/6859

**Comment by bertho-zero** [comment]
I had the same problem and I added that in my `package.json`:

```js
{
  // ...
  "nohoist": [
    "**/@storybook/**"
  ]
  // ...
}
```

**Comment by renatho** [comment]
Hi @bertho-zero ! Thank you for your help!

I tried this in this branch: https://github.com/renatho/monorepo-with-storybook-bug/tree/yarn-test-storybook-nohoist

But it doesn't work =(
I tried with the nohoist in the package.json root too, but not work too.

Is that like your code that works?

**Comment by bertho-zero** [comment]
Why React is in the package? There must be only one version of React and it should probably be root (and peerDependencies in the packages), this is the case for me.

I did not look at the structure, I do not have any code at the root, everything in packages. Our structures are very different.

I answered too quickly when I saw "monorepo", my problem is not the same at all.

**Comment by renatho** [comment]
@bertho-zero Tt is because the project is migrating from multi-repo to monorepo structure in baby steps. In a second moment, the "root" will become a package too and the common dependencies will be only on root (it is to prevent versioning problems).

But it is not the problem. I tried with 2 packages with same dependency in different versions and the problem ocurrs.

**Comment by nmccready** [comment]
Re-open
