### ISSUE TITLE
using markdown in addon-notes do not work

### ISSUE THREAD

**Issue by littlepoolshark** [storybookjs/storybook#5217]
**Describe the bug**
using markdown in addon-notes do not work

**To Reproduce**

**Expected behavior**
show notes panel in the markdown way

**Screenshots**
![storybook](https://user-images.githubusercontent.com/7507174/51016122-10ae6900-15aa-11e9-9a5f-a8d146ca7518.png)

**Code snippets**
config.js file:
``` javascript
import { configure, addDecorator } from '@storybook/react';
import { configureViewport } from '@storybook/addon-viewport';
import { withOptions } from '@storybook/addon-options';
import { withNotes } from '@storybook/addon-notes';

// automatically import all files ending in *.stories.tsx
const req = require.context('../stories', true, /.stories.(tsx|ts)$/);

function loadStories() {
  req.keys().forEach(req);
}


configureViewport({
  defaultViewport: 'iphone6'
});

// override option defaults:
addDecorator(withOptions({
  name: '',
  // url: 'https://github.com/vanilla-framework/vanilla-framework-react',
  addonPanelInRight: true,
}))
addDecorator(withNotes)

configure(loadStories, module);

```

index.stories.tsx file:
``` javascript
import * as React from 'react';
import { storiesOf } from '@storybook/react';
import { action } from '@storybook/addon-actions';
import { Input } from '../src';



storiesOf('Button', module)
  // .addDecorator(withNotes('1'))
  .add('with text', () => {
    return <Input  />
  },{
    notes:{
      markdown:`
        ###

        1
        ###

        2
      `
    }
  })
  .add('with some emoji',  () => (
    <div onClick={action('button-click')}>click me,please!</div>
  ),{
    notes:'2'
  });


```

**System:**
 - OS: [e.g. iOS, Windows10, MacOS]
 - Device: [e.g. iPhoneX, Macbook Pro 2018]
 - Browser: [e.g. chrome, safari]
 - Framework: [e.g. react, vue, angular]
 - Addons: [if relevant]
 - Version: [e.g. 4.0.0]

**Additional context**

**Comment by doroncy** [comment]
I had same issue, solved it by creating const parameter with the markdown.
```
const note = `
  ## Some markdown  
`;
iconStories.add(
    'Story',
    () => {
      return {
        template: ''",        
      };
    },
    { notes: { markdown: note }  }
  );
```

**Comment by transitorytammy** [comment]
I am having the same issue (kinda).  It seems like it is rendering the markdown but the formatting for the table in my markdown.

preview from my editor:
![screen shot 2019-01-30 at 11 58 31 am](https://user-images.githubusercontent.com/1967604/52009062-d63c3b80-2486-11e9-885f-1584b1004163.png)

what is showing in storybook:
<img width="613" alt="screen shot 2019-01-30 at 11 58 26 am" src="https://user-images.githubusercontent.com/1967604/52009063-d6d4d200-2486-11e9-85fe-005fdc1ac92e.png">

**Comment by littlepoolshark** [comment]
@doroncy yeah,I finally  get around this issue by creating a const parameter with the markdown.

**Comment by viktorsec** [comment]
@transitorytammy I have the same problem as you. We should create a new issue since it's not at all related to @littlepoolshark's.

**Comment by MightyRevenge** [comment]
having the same problem!

**Comment by KiyaDoig** [comment]
+1 I would like to be able to use markdown in-line (without having to import or use const). Thank you.

**Comment by MurrayJack** [comment]
yes please to above ,  its so easy to get wrong and break the markup!
