### ISSUE TITLE
Addon Tutorial doesn't work

### ISSUE THREAD

**Issue by ryanwelcher** [storybookjs/storybook#5240]
**Describe the bug**
When trying to create a custom addon. If I follow the steps on the [website](https://storybook.js.org/addons/writing-addons/), Storybook will compile but not start the server.

**Comment by dancol93** [comment]
Having exactly the same issue, anyone has found a workaround?

**Comment by ryanwelcher** [comment]
@dancol93 I have not, no. To be clear I have tried both the slow and quick start tutorials and then adding the addon tutorial code. 

The only thing I haven't tried is creating the addon as a package and adding it to my package.json as indicated in the[ docs here](https://storybook.js.org/addons/writing-addons/#packaging)

**Comment by ryanwelcher** [comment]
@ndelangen sorry for the direct ping but we're not getting any traction on this. Hoping you can help?

**Comment by shilman** [comment]
Sorry for the slow turnaround on this. We've been heads down getting v5 out and stabilizing it. I know @ndelangen's updating the addons API (e.g. https://github.com/storybooks/storybook/pull/5402) and is focusing on addons, so hopefully this issue will get some love soon.

**Comment by ryanwelcher** [comment]
Thanks, @shilman. I appreciate the response and completely understand the priority is getting v5 out the door.

**Comment by ndelangen** [comment]
I'm on it

**Comment by ndelangen** [comment]
I have progress here:
https://github.com/storybooks/storybook/pull/6759

and here:
https://github.com/chromaui/learnstorybook.com/pull/91
