### ISSUE TITLE
[addon-info] `No propTypes defined!` on prop table in build mode

### ISSUE THREAD

**Issue by feonit** [storybookjs/storybook#5251]
Maybe this refers to this issues:
https://github.com/storybooks/storybook/issues/1141

I will duplicate my last comment here:

PropTypes still not worked for me in build mode. Here my component:

```js
import React from "react";
import "./Background.css";
import PropTypes from "prop-types";

const Background = (props) => {
	const {children} = props;
	return (
		<div className={"Background"}>
			{children}
		</div>
	)
};

Background.displayName = "Background";

Background.propTypes = {
	/** My content */
	children: PropTypes.any.isRequired
};
export default Background;
```

For command `NODE_ENV=production npm run storybook` i have:
![2019-01-15 18 33 02](https://user-images.githubusercontent.com/3956831/51190821-1d0d2b80-18f4-11e9-88cc-19482e3b85b4.png)

And for `npm run storybook`:
![2019-01-15 18 37 47](https://user-images.githubusercontent.com/3956831/51191077-b3415180-18f4-11e9-9908-dc27deca5b5a.png)

Same for the rest of the components too. But when i added:
```js
Background.defaultProps = {
	children: 'my text'
};
```
 the following happens:
![2019-01-15 18 43 25](https://user-images.githubusercontent.com/3956831/51191471-82ade780-18f5-11e9-86e2-6a7032a33ac2.png)

I use:
```
    "@storybook/addon-info": "4.1.2",
    "@storybook/addon-knobs": "4.1.2",
    "@storybook/addon-options": "4.1.2",
    "@storybook/cli": "4.1.2",
    "@storybook/react": "4.1.2",
```
is amazing

Am I doing something wrong?

**Comment by chulanovskyi** [comment]
You know, we are using the Typescript and a plugin [react-docgen-typescript-webpack-plugin](https://github.com/strothj/react-docgen-typescript-loader) to extract the interfaces into `storybook/addon-info`. The result prop table gets really into a mess if we describe `children` prop to be `React.ReactChild`.
 
![component.tsx](https://user-images.githubusercontent.com/13966263/51330346-01cf2700-1a80-11e9-96c0-9989414f70f4.png)

![storybook](https://user-images.githubusercontent.com/13966263/51330512-5b375600-1a80-11e9-90c1-7d08050b38fc.png)

Is it a real bug? Or we're doing it wrong too? :)

**Comment by feonit** [comment]
and now, in version 5 it still not work!

**Comment by nelsieborja** [comment]
Any update on this issue?

**Comment by tuhinadasgupta** [comment]
would really appreciate an update on this issue!

**Comment by feonit** [comment]
continue the discussion

**Comment by shilman** [comment]
FYI, addon-docs is the successor to addon-info and is currently in beta. We'll still take community contributions on addon-info, but most effort will be put into making docs better. To learn more about addon-docs: https://docs.google.com/document/d/1un6YX7xDKEKl5-MVb-egnOYN8dynb5Hf7mq0hipk8JE/edit?usp=sharing

**Comment by shilman** [comment]
FYI `addon-info` is being superceded by `addon-docs`, which fixes a bunch of bugs and is easier to maintain. It’s reached release candidate (RC) status and will be properly released soon. Please give it a try! https://medium.com/storybookjs/storybook-docspage-e185bc3622bf

@feonit @chulanovskyi @carl-berg @GraySmith00 @nelsieborja @roottool @stale @github-actions @ElliottRoche @tuhinadasgupta @matheustrindade

**Comment by Lory1990** [comment]
I have the same issue, do you have any news?

**Comment by nelsieborja** [comment]
> Any update on this issue?

I have switched to `addon-docs` instead and I kind of actually prefer it. In case you're looking for a quick setup of it using TypeScript and CSF, [this](https://github.com/nelsieborja/gorg-ui-v3#%EF%B8%8F-installation) might probably help you.
