### ISSUE TITLE
How to use babel-emotion-plugin with Storybook + Typescript?

### ISSUE THREAD

**Issue by meebix** [storybookjs/storybook#5262]
I am currently using Storybook (v.4.0.12) with TypeScript and have successfully followed the instructions to set up my TypeScript `webpack.config.js`. This works fine.

However, I cannot seem to find _any_ way of successfully adding a babel plugin to the config. My latest attempt is below, which does not work.

```js
module.exports = (baseConfig, env, config) => {
  config.module.rules.push({
    test: /\.(ts|tsx)$/,
    use: [
      {
        loader: require.resolve('awesome-typescript-loader'),
        options: {
          babelOptions: {
            babelrc: false,
            presets: [],
            plugins: ['emotion'],
          },
        },
      },
    ],
  });
  config.resolve.extensions.push('.ts', '.tsx');

  return config;
};
```

If I boot Storybook with this config, I continue to see the message `Component selectors can only be used in conjunction with babel-plugin-emotion.`, which means that the Emotion babel plugin is not being picked up by Storybook.

I am not using CRA, just plain ol' React and Typescript.

Any suggestions?

Thanks.

**Comment by piyush96arora1** [comment]
config.module.rules.push({
    test: /\.(js|jsx)$/,
    exclude:<<nodemodules>>,
    loader: require.resolve("babel-loader")
  });

**Comment by meebix** [comment]
What? Are you suggesting to add rules for TS and JS?

**Comment by piyush96arora1** [comment]
```
  defaultConfig.module.rules.push({
    test: /\.(ts|tsx)$/,
    include: [path.resolve(__dirname, "../src"), path.resolve(__dirname, "../stories")],
    loader: require.resolve("ts-loader")
  });
  
  defaultConfig.module.rules.push({
    test: /\.(js|jsx)$/,
    exclude: /node_modules/,
    loader: require.resolve("babel-loader")
  });
```

**Comment by meebix** [comment]
This does not work either. ^^

**Comment by ximbong91023** [comment]
Any updates on this? I'm getting the same problem and not sure how to solve

**Comment by kennycrosby** [comment]
Also having this problem if anyone has a solution. @meebix ?

**Comment by MarkLyck** [comment]
Having this issue too, can we re-open please?

Did anyone find a solution @meebix?

**Comment by MarkLyck** [comment]
Reposted the question on SO: https://stackoverflow.com/questions/61781954/how-to-use-babel-emotion-plugin-with-storybook-typescript

**Comment by shilman** [comment]
PSA: Upvoting the original issue description is the most effective way to get it solved. Upvoting comments below is also great, but won't help us prioritize the feature/fix

**Comment by Elfo404** [comment]
@MarkLyck  crossposting it here from SO so other people might find it as well.

I don't know if it applies to everyone, but in my case I got it working with storybook 5.3.x by using in `.storybook/main.js` this:

```js
module.exports = {
  stories: ['../packages/**/*.stories.tsx'],
  webpackFinal: async (config) => {
    config.module.rules.push({
      test: /\.(ts|tsx)$/,
      loader: require.resolve('babel-loader'),
      options: {
        plugins: ['emotion'],
        presets: [['react-app', { flow: false, typescript: true }]],
      },
    });
    config.resolve.extensions.push('.ts', '.tsx');
    return config;
  },
};
```

This doesn't use TypeScript tho, so might or might not be relevant in this situation, or might just be used while a solution using TypeScript is found.

Hope it helps.

**Comment by Chanki-Min** [comment]
for fellows with non-cra enviroment + 2023

```
    config.module?.rules?.push({
      test: /\.(ts|tsx)$/,
      loader: require.resolve('babel-loader'),
      options: {
        plugins: ['@emotion'],
        presets: [
          ['@babel/preset-env', { shippedProposals: true, loose: true }],
          ['@babel/preset-typescript', { flow: false, typescript: true }],
        ],
      },
    });
    config.resolve?.extensions?.push('.ts', '.tsx');
```
