### ISSUE TITLE
Make chosen viewport sticky - reverts to default on code reload - painful/frequent

### ISSUE THREAD

**Issue by rosskevin** [storybookjs/storybook#5267]
**Is your feature request related to a problem? Please describe.**
When we develop, we target two primary sizes - `xs` our mobile default, and `md` our secondary.  We have many other viewports configured but these are the two we commonly use to develop and test responsive layouts.  `xs` is easy since it is our default, but `md` is a real pain because every code reload sets the viewport back to `xs` when we are just tweaking for `md`

**Describe the solution you'd like**
Any chosen viewport should be sticky.

**Describe alternatives you've considered**
Since there can only be one default, I've only considered changing our config code constantly to switch from one default to the other. 

**Are you able to assist bring the feature to reality?**
maybe - not very familiar with the controls involved here, but already developed a minimal in-house addon for our forms.  With some pointers I may be able to PR a change.

**Comment by rosskevin** [comment]
@tmeasday definitely doing a full reload - I haven't spent time trying to figure that out but I will.

**Comment by rosskevin** [comment]
I checked, and it appears to me that I'm getting a hot reload, yet the viewport switches.  It appears like a full reload because the viewport switches, but I tested closely and seems hot.

**Comment by rosskevin** [comment]
/unstale forever. It is now my life's mission.

**Comment by shilman** [comment]
Could be related to #6114 ?

**Comment by tmeasday** [comment]
I think it's worth understanding as part of solving #6114 in any case. The HMR part is interesting in this one.

**Comment by rosskevin** [comment]
I wish there was a better solution than a stale bot, but understand it helps overall.

Go away stale bot.

**Comment by shilman** [comment]
@rosskevin If one marks the issue as `in progress` the stale bot goes away. Any interest in picking this issue up?

**Comment by rosskevin** [comment]
I'm sorry @shilman I'm already spread thin across the other open source and private projects I contribute to. I'd like to pick it up but it would be irresponsible of me to indulge.

**Comment by ndelangen** [comment]
This might help with the reloading issue: #6972

**Comment by ndelangen** [comment]
I won't help with the persistence of state though, if there IS a refresh, it will reset the state.

@shilman and I did discuss the idea of persisting the selected tab, but we haven't really chooses how to exactly solve yet.

**Comment by shilman** [comment]
We want to address this in 6.3. If you want to contribute to Storybook, we'll prioritize PR review for any fixes here. And if you'd like any help getting started, please jump into the #support channel on our Discord: https://discord.gg/storybook

**Comment by ndelangen** [comment]
This is fixed!
