### ISSUE TITLE
[Addon Info] - upgrading from 4.0.12 to 4.1.6 missing styling for prop tables

### ISSUE THREAD

**Issue by DavideDaniel** [storybookjs/storybook#5278]
**Describe the bug**
Upgrading to `storybook/addon-info@^4.1.6` from `4.0.12` broke styling for prop tables.

**To Reproduce**
1. View default propTables on a local repo hard pinned to addon-info@4.0.12
2. Upgrade to addon-info@4.1.6 and restart local storybook
3. Compare prop tables

**Expected behavior**
An explanation on how to retain the styles in the docs or reverting the change to allow default styles to return without a major bump.

**Screenshots**
v4.0.12
<img width="1039" alt="screen shot 2019-01-17 at 4 39 37 am" src="https://user-images.githubusercontent.com/8802938/51319923-3658c980-1a13-11e9-964d-c3c7fa1fbf15.png">

v4.1.6
<img width="1039" alt="screen shot 2019-01-17 at 4 41 59 am" src="https://user-images.githubusercontent.com/8802938/51319966-4ec8e400-1a13-11e9-9a28-d63b2fbaa303.png">

**System:**
 - OS:  MacOS
 - Device: Macbook Pro 2017
 - Browser: Chrome
 - Framework: React
 - Addons: addon-info
 - Version: 4.1.6

**Comment by shilman** [comment]
This visual regression was introduced in #5148 as we pulled this out of the Storybook component library for React back-compat. It would be a great first issue for somebody who wants to style this!

**Comment by Kacppian** [comment]
Can I pick this up please?

**Comment by nimaiwalsh** [comment]
Hi @shilman, 

It would definitely be nice to be able to style the propsTable, could this be achieved by adding propsTable to baseInfoStyles object?

Thanks for all of your work.

**Comment by shilman** [comment]
we're replacing addon-info with a much better option that will also be stylable. more updates soon 👀

**Comment by graygilmore** [comment]
@shilman is there a place I can subscribe to to follow along to the updates? Excited for this!

**Comment by shilman** [comment]
@graygilmore https://medium.com/storybookjs/storybook-docs-sneak-peak-5be78445094a is the announcement, and there is ongoing discussion in `#docs-mode` channel on our discord https://discord.gg/UUt2PJb

**Comment by ndelangen** [comment]
Fixed in 5.1
