### ISSUE TITLE
Document `presets.js`

### ISSUE THREAD

**Issue by tmeasday** [storybookjs/storybook#5301]
Previously we were waiting on #4169 but we've decided to officially support `presets.js` and migrate to the new file in a later release.

So all we really need to is document the current state of the world (as of v4 actually)

**Comment by shilman** [comment]
I have the rest of the puzzle thanks to a call with @igor-dv last week. Hope to finish this soooooon....

**Comment by joeycozza** [comment]
I know you are super busy with Storybook-docs, and I don't want to add stress or pressure, but has this been documented/worked on at all?

**Comment by shilman** [comment]
@joeycozza Yeah there's a WIP here https://github.com/storybooks/storybook/pull/5333

Thanks for the nudge, I'll get that back into shape this week.
