### ISSUE TITLE
[Addon: Knobs] Same name different groupId's

### ISSUE THREAD

**Issue by ManAnRuck** [storybookjs/storybook#5391]
**Is your feature request related to a problem? Please describe.**
When I have the same `name` and different `groupId` only one field will shown.
```js
…
label={text('label', 'Title', 'Input')}
…
label={text('label', 'Title', 'Textarea')}
…
```

**Describe the solution you'd like**
Handle in the background the fields in combination with the groupId, so the same "named" fields still shown.

**Describe alternatives you've considered**
Current workaround is naming the fields different like `text`
```js
…
label={text('label(input)', 'Title', 'Input')}
…
label={text('labe(textarea)l', 'Title', 'Textarea')}
…
```

**Are you able to assist bring the feature to reality?**
no

**Additional context**
In the `All` Tab could be a headline to group/divide the different groups.

**Comment by mrmckeb** [comment]
I think this could be fairly easily implemented @ReggaePanda, if you'd like to have a go, I could help you with the process?

**Comment by shilman** [comment]
Is this still the case in v5?

**Comment by Zyzle** [comment]
@shilman It seems to be, I found this issue after coming across the same problem today.

**Comment by maciejmyslinski** [comment]
It's still an issue in v5

**Comment by shilman** [comment]
Good golly!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-alpha.36 containing PR #6793 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
