### ISSUE TITLE
Support for data driven ember components via ember-data and mirage

### ISSUE THREAD

**Issue by techdragon** [storybookjs/storybook#5611]
**Is your feature request related to a problem? Please describe.**
I already have model data factories for populating components with data during testing. So being required to implement another version of this data factory just to get automatic data into my components when rendering them in storybook. Don't make me repeat myself. 

**Describe the solution you'd like**
Support for ember-data + ember-cli-mirage using ember-qunit to so that I can use my mirage model factories as the source of data when writing component stories. Similar to what you see demonstrated in this blog post https://hashrocket.com/blog/posts/test-driving-a-stubbed-api-in-ember-with-ember-cli-mirage#listing-our-cars 

**Describe alternatives you've considered**
The knobs addon, and also manually coding the creation of data objects for components using faker.js, but neither of these is as efficient as just using the model data & associated model data factories that my data driven component was designed to use.

**Are you able to assist bring the feature to reality?**
I've already spent a day trying, however I'm not an expert on react/storybook or the internals of how ember works, so my contribution may be limited :-(  

**Additional context**
My first attempt was just trying to initialize mirage inside a story similar to how the blog post i linked to sets it up inside the component test, didnt work. It just produced a lot of errors about `Module not found: Error: Can't resolve 'fs' in ...` I've also opened an issue on the ember-cli-mirage bug tracker in case the issue is simple to solve inside mirage alone. https://github.com/samselikoff/ember-cli-mirage/issues/1502

**Comment by shilman** [comment]
Cc @gabrielcsapo

**Comment by transitorytammy** [comment]
I really could use this support too for some components I am working on too.

@techdragon, you mentioned that you are currently have "model data factories for populating components with data during testing."  what are you using there?

**Comment by techdragon** [comment]
@transitorytammy I'm using the model factories feature of mirage, https://www.ember-cli-mirage.com/docs/advanced/factories 

How it is all connected is probably better explained by the Mirage Documentation than by any quick summary I could write. But fundamentally it relies on Ember Data and the normal initialisation sequence, which if my assessment in https://github.com/samselikoff/ember-cli-mirage/issues/1502#issuecomment-464634104 is correct, is bypassed by Storybook, which is effectively a blocker for this working with Mirage.
