### ISSUE TITLE
Add colour picker in addon-backgrounds

### ISSUE THREAD

**Issue by leoyli** [storybookjs/storybook#5624]
**Is your feature request related to a problem? Please describe.**
If work in CDD approach, sometimes we may want to quickly change the iframe background colour. It is tedious to add colour definition in to a story just to see the colour each time...

**Describe the solution you'd like**
Add a colour picker or at least a field that accept colour name.

**Describe alternatives you've considered**
N/A

**Are you able to assist bring the feature to reality?**
Add a field to accept colour dynamically, yes; add a colour picker, it requires some changes in the UI side I believe.

**Additional context**
The old predefined colour set is still very useful and we probably don't want to change it; my proposal is just to augment the add-on so it can be more robust.

**Comment by tmeasday** [comment]
Sounds like a good feature idea @leoyli

**Comment by Kacppian** [comment]
Can I work on this?

**Comment by kohakukun** [comment]
Is this issue still up for grabs?

**Comment by shilman** [comment]
@kohakukun AFAIK it is!

**Comment by kohakukun** [comment]
Working on it

**Comment by lucapollani** [comment]
Was this feature eventually developed? I'd like to have it
