### ISSUE TITLE
Update CLI to ship with recommended addons in v5

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#5731]
## Why

v5 ships with a bunch of great addons -- let's remove the friction by making `sb init` ship with sensible defaults.

Yes this is late in the ship cycle, but it's a very low risk feature as it doesn't touch any of the main code.

## What

- [ ] Notes
- [ ] Backgrounds
- [ ] Viewports
- [ ] TBD?

**Comment by Keraito** [comment]
What do have explicitly in mind? That the `SB init` also comes with these addons? Or that there are templates for those?

**Comment by shilman** [comment]
@keraito yeah  we can update the templates in SB init to help get people started with best practices  highlight the new features in SB5

**Comment by shilman** [comment]
Let's add this as part of 5.1?

**Comment by Keraito** [comment]
Sounds good @shilman , is there a (tentative) release date for 5.1?

As a todo list for what we want:
- [ ] Include the above addons together with the templates.
- [ ] Register them in the `addons.js`.
- [ ] Should we also import them into the existing template stories?
- [ ] Do we want (separate) example stories with usages of those addons?

**Comment by shilman** [comment]
@Keraito Yes we should add them to the template config. I think we can just add them in the simplest way possible including `viewport` and `backgrounds` and maybe `a11y`. I'm going to overhaul the way notes/info work soon, and will include updates for Storybook Docs separately.

**Comment by shilman** [comment]
Yee-haw!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-beta.19 containing PR #9019 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Shiver me timbers!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-beta.20 containing PR #9093 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

**Comment by shilman** [comment]
Yay!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-rc.0 containing PR #9184 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.
