### ISSUE TITLE
Babel errors swallowed in v5 UI

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#5822]
**Describe the bug**

When my JSX has a syntax error, v5 does not display the error in the UI. 

For instance in this example repo https://github.com/hipstersmoothie/story-bug there is a bug:

<img width="258" alt="github_desktop" src="https://user-images.githubusercontent.com/488689/53690436-2ae41680-3da5-11e9-9e4b-e7a33d776746.png">

In v4, error displays in the terminal, browser console, AND UI:

<img width="1432" alt="storybook" src="https://user-images.githubusercontent.com/488689/53690464-e442ec00-3da5-11e9-9e9b-78e8a4293538.png">

In v5, error displays only in the terminal and browser console:

<img width="1436" alt="storybook" src="https://user-images.githubusercontent.com/488689/53690447-7c8ca100-3da5-11e9-8fc4-96647976558f.png">

**Comment by thegiantbeast-csm** [comment]
@shilman how does the workaround work?

Because I didn't had any success following the comments on #5818. Thanks!

**Comment by shilman** [comment]
The workaround is to open the dev tools and see the console output there

**Comment by shilman** [comment]
Hurrah!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-alpha.30 containing PR #6972 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
