### ISSUE TITLE
React Native CLI install broken in SB5 (temporarily)

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#5893]
Running the CLI `sb init` in an RN project installs the wrong version of libraries until we release `@storybook/react-native@5.1` which is coming soon.

### What's going on
- CLI is checking for the latest version of dependent libraries on NPM
  - Latest version of `@storybook/react-native` is 4.x
  - Latest version of the rest of `@storybook/*` is 5.0.x
- These versions are incompatible

### Workaround

Use the `next` version of the CLI / React native to get `5.1.0-alpha.x`:
```
npx -p @storybook/cli@next sb init --type react_native
```

Alternatively, hand edit the version numbers of `@storybook/*` in `package.json` after running `sb init` to match the latest `4.1.x` version of `@storybook/react-native`.

We won't be issuing a fix since we can use that time to release `@storybook/react-native@5.1` instead. Will update here as soon as that's live.

**Comment by shilman** [comment]
Awesome gist from @johnwylie70 with the current install process end to end:

https://gist.github.com/johnwylie70/1f019c643641f56b400acc78415d398d

**Comment by shilman** [comment]
ZOMG!! I just released https://github.com/storybooks/storybook/releases/tag/v5.1.0-alpha.12 that addresses this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
We’ve released a brand new `@storybook/react-native` with a bunch of core improvements. It’s available in the latest `5.1-alpha` on `next` and has been verified by several RN users on their existing apps. It should fix a bunch of compatibility issues, especially if you’re using the web server feature. Please give it a try and comment here if it fixes your problem. Migration instructions available here: https://github.com/storybooks/storybook/blob/next/MIGRATION.md#react-native-server

**Comment by idanhaviv** [comment]
@shilman upgrade by changing "@storybook/react-native": "5.1-alpha" in package.json? 
and what is "next"?

**Comment by shilman** [comment]
Next is both a GitHub branch and also an npm tag. We'll be releasing 5.1 in 2wk which will fix this issue

**Comment by shilman** [comment]
Fixed with 5.1 release!
