### ISSUE TITLE
IE11: webpack-hot-middleware's client requires EventSource to work

### ISSUE THREAD

**Issue by ZebraFlesh** [storybookjs/storybook#5897]
**Describe the bug**
IE11 doesn't hot reload as you make changes.

**To Reproduce**
1. Get setup:
```
git clone https://github.com/storybooks/storybook.git
cd storybook
yarn install
yarn bootstrap --core
cd examples/official-storybook
yarn build-now
yarn storybook
```
2. In Chrome and IE11, visit http://localhost:9011/?path=/story/addons-backgrounds--overriden
3. Edit stories/addon-backgrounds.stories.js and change the overridden story from
```
  .add('overriden', () => <BaseButton label="This one should have different backgrounds" />, {
    backgrounds: [
      { name: 'pink', value: 'hotpink' },
      { name: 'blue', value: 'deepskyblue', default: true },
    ],
  })
```
to
```
.add('overriden', () => <BaseButton label="This one should have different backgrounds" />, {
    backgrounds: [
      { name: 'pink', value: 'hotpink', default: true },
      { name: 'blue', value: 'deepskyblue' },
    ],
  })
```
4. In Chrome, the background changs from blue to pink. IE11 fails to update.

**Expected behavior**
IE11 should automatically update via HMR like Chrome does.

**System:**
 - OS: Windows 10
 - Device: Dell Precision laptop
 - Browser: IE11
 - Framework: react
 - Version: 5.0.0

**Additional context**
IE11 developer tools shows the error:
`webpack-hot-middleware's client requires EventSource to work. You should include a polyfill if you want to support this browser: https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events#Tools`

I've tried `yarn add event-source-polyfill` and then `import 'event-source-polyfill';` in config, but the error  persists.

**Comment by ZebraFlesh** [comment]
This isn't an issue with backgrounds addon -- it's just a handy minimal example. Any storybook will fail to update in IE11 due to the missing EventSource polyfill.

**Comment by ZebraFlesh** [comment]
This is still an issue as of 5.0.6

**Comment by shilman** [comment]
@ZebraFlesh can you try adding it to `addons.js`?

**Comment by alex-page** [comment]
@shilman I tried it out in the `addons.js` file, this is not working. For example both of these fail:

Following `event-source-polyfill` documentation:
```
import {NativeEventSource, EventSourcePolyfill} from 'event-source-polyfill';
const EventSource = NativeEventSource || EventSourcePolyfill;
```

Following @ZebraFlesh's above example.
```
import 'event-source-polyfill';
```

**Comment by ndelangen** [comment]
Can you try adding that to `config.js` ?

**Comment by adamdoyle** [comment]
Adding this line to `addons.js` worked for me:
```javascript
import 'eventsource/lib/eventsource-polyfill';
```

I don't know if it matters, but I used the polyfill package mentioned in the [link](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events#Tools) from the webpack HMR error message, instead of the one that @ZebraFlesh used.

*In other words:*  I used [eventsource](https://www.npmjs.com/package/eventsource) (from the mozilla link) instead of [event-source-polyfill](https://www.npmjs.com/package/event-source-polyfill).

**Comment by adamdoyle** [comment]
I spoke too soon.  Now the error is in the console and in the "actions" panel (and HMR still not working), but it's not giving me the original popup error anymore.  (maybe I suppressed it somehow)

**Comment by adamdoyle** [comment]
this seems to work :crossed_fingers:  

in `config.js`:
```javascript
import { NativeEventSource, EventSourcePolyfill } from 'event-source-polyfill';
global.EventSource =  NativeEventSource || EventSourcePolyfill;
```
