### ISSUE TITLE
[5.0.0] addon-info does not render code snippet markdown given on the text parameter

### ISSUE THREAD

**Issue by dharmawankenny** [storybookjs/storybook#5915]
**Describe the bug**
After upgrading to 5.0.0, addon-info does not render any code snippets given via the `text` key on the `info` parameter on the `addParameter()` function. It successfully displays all the given text but fails and does not display the given code under the ~~~ ~~~ notation, i.e:

~~~
\~~~js
  function something(a) {
    return a;
  }
\~~~
~~~

**To Reproduce**
1. Go to any story, put any string with aforementioned ~~~js ~~~ markdown notation
2. View it on the storybook
3. See that the supposed code snippet does not show at all.

**Expected behavior**
The supposed code snippet should show correctly as before

**Screenshots**
<img width="1736" alt="screen shot 2019-03-06 at 16 55 35" src="https://user-images.githubusercontent.com/19358083/53872398-bb825700-4030-11e9-9559-f99e0dcf6e34.png">

**Code snippets**
<img width="1037" alt="screen shot 2019-03-06 at 16 55 24" src="https://user-images.githubusercontent.com/19358083/53872389-b6bda300-4030-11e9-85c9-6f8ec9116355.png">

**System:**
 - OS: MacOS Mojave, also does not work on netlify deployment
 - Device: Macbook Pro 2017
 - Browser: Chrome
 - Framework: React
 - Addons: addon-info
 - Version: 5.0.0

**Additional context**
none

**Comment by whengely** [comment]
I am also experiencing this with the ```js ``` syntax.

**Comment by aaryn101** [comment]
I see this issue when using individual story parameters as well.

**Comment by warkentien2** [comment]
It does, however, interpret HTML. I had to use `<code>`, `&lt;`, `&gt;` to make do.

**Comment by alexandrecanuto** [comment]
This needs to be merged ASAP.

**Comment by jChris85** [comment]
I also would appreciate that fix to be released

**Comment by inside** [comment]
Here are some clues I found:

This [line](https://github.com/storybooks/storybook/blob/8d49b21473a96c79dd80d79de552ddeae3991ac6/addons/info/src/components/markdown/code.js#L6) should maybe changed to:

```
const Code = (props) => {
  const { language, code } = props

  return (
    <SyntaxHighlighter
      bordered
      copyable
      language={language}
    >
      {code}
    </SyntaxHighlighter>
  );
};
```

But then this [line](https://github.com/storybooks/storybook/blob/0f44cafb95cd4c2f73383cd6568d2306ce399445/lib/components/src/syntaxhighlighter/syntaxhighlighter.js#L36) (and other lines will probably too) results in:
```
Cannot read property 'bar' of undefined
```

Which tells me components consuming the theme aren't up to date with the latest themes [found here](https://github.com/storybooks/storybook/tree/master/lib/theming/src/themes).

May anyone pick it up from here?

**Comment by cutterbl** [comment]
Is there any motion on this issue? Still seeing it in 5.0.10 this morning.

**Comment by amanolar94** [comment]
Yes the issue still exists..

**Comment by jaydlawrence** [comment]
For the sake of helping to weight this issue and keep it fresh:
Having the same issue upgrading from storybook 4 to 5.
I even tried the markdown example from the README and it is also not working.
https://github.com/storybooks/storybook/tree/master/addons/info#markdown

**Comment by giovannicanzio** [comment]
Hi all, still no news about this issue? It would be great to have it fixed...

**Comment by Anandnaik** [comment]
Fix this plx!

**Comment by enrique-ramirez** [comment]
This is a rather urgent problem that I feel deserves more attention, so bumping a bit.

**Comment by whengely** [comment]
There is a relatively easy workaround in this linked issue:

https://github.com/storybooks/storybook/pull/6016

**Comment by cutterbl** [comment]
@whengely Just be nice if it supported the syntax laid out in the documentation. The same syntax this addon supported prior.

**Comment by Anandnaik** [comment]
bump

**Comment by shilman** [comment]
Boo-yah!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-alpha.29 containing PR #6016 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@debug` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Boo-yah!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-alpha.29 containing PR #6016 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@debug` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
