### ISSUE TITLE
Knobs text shares the same colour as the sidebar text colour

### ISSUE THREAD

**Issue by markgaze** [storybookjs/storybook#5931]
**Describe the bug**
When theming the site in v5.0.0, the knobs description text shares the same text colour as the sidebar so when attempting to have a dark coloured sidebar with white text but a white value for `appContentBg` the text is impossible to read.

**To Reproduce**
Use the following theme:

```js
import { create } from '@storybook/theming';

export default create({
  // Is this a 'light' or 'dark' theme?
  base: 'light',

  // Color palette
  colorPrimary: '#2e5685', // primary color
  colorSecondary: '#3b78bd', // secondary color

  // UI
  appBg: '#2e5685',
  appContentBg: 'white',
  appBorderColor: 'rgba(0,0,0,.1)',
  appBorderRadius: 0,

  // Fonts
  fontBase: 'Roboto, Arial, sans-serif',
  fontCode: 'Courier, monospace',

  // Text colors
  textColor: '#FFFFFF',
  textInverseColor: '#333333',

  // Toolbar default and active colors
  barTextColor: 'white',
  barSelectedColor: 'white',
  barBg: '#2e5685',

  // Form colors
  inputBg: 'white',
  inputBorder: 'rgba(0,0,0,.1)',
  inputTextColor: '#333333',
  inputBorderRadius: 4,
});
```

Changing between `base` of `light` or `dark` doesn't make any difference either.

**Expected behavior**
I would expect to be able to theme the text of the knobs separately to the rest of the theme. 

**Screenshots**
![image](https://user-images.githubusercontent.com/16718355/53911604-cfd54c80-404e-11e9-8d26-8d302c1d2a74.png)

**Code snippets**
See "To reproduce".

**System:**
 - OS: Ubuntu 16.04
 - Device: Laptop
 - Browser: Chrome
 - Framework: Angular
 - Addons: Knobs
 - Version: 5.0.0

**Additional context**

**Comment by cromnow** [comment]
Same issue with the "Note" addon. 
![Screenshot 2019-03-13 at 16 38 59](https://user-images.githubusercontent.com/2813034/54293251-e714bc80-45af-11e9-9d79-6c53829d2d27.png)

**Comment by Pixelatex** [comment]
Also running into this issue... The theming options are very limited and don't seem to cover everything.

**Comment by domyen** [comment]
The official theming api doesn't cover _every_ possible variation intentionally. Our first priority is to have a tight, maintainable API so we can ship fast and lower the risk area for unintentionally breaking themes in future releases. 

That said, we're working on an [escape hatch PR](https://github.com/storybooks/storybook/pull/6571) that attaches static classnames to DOM elements so that you can override the styling. This should offer the best of both worlds, easy customization for users, and low maintenance for UI maintainers. YMMV 😊

**Comment by ndelangen** [comment]
Would anyone be able to help us fix this one?

**Comment by Pixelatex** [comment]
I was forced to use a gray-ish color in the dark theme to make everything visible... we have to wait until they extend the api for theming.

**Comment by cjcheshire** [comment]
Still seems to be not configurable?

**Comment by michaelrobertson-fico-com** [comment]
We definitely would like to see more granular control over the major elements in the storybook UI. Per the original post we want to make the left nav dark and style independently of knobs.
