### ISSUE TITLE
Static App cannot browse directly to story urls

### ISSUE THREAD

**Issue by FinestV** [storybookjs/storybook#6030]
**Describe the bug**
When Storybook is exported as a static app using build-storybook you can no longer browse directly to stories by their url. Browsing directly works as expected when running the Storybook in dev mode.

**To Reproduce**
1. npm run build-storybook
2. Start a web server in the output directory eg. npx serve .
3. Open the Storybook in a web browser so that the first story opens
4. Duplicate the tab
5. In the new tab the story will not load and instead say "No Preview"

**Expected behavior**
You should be able to browse directly to stories by url without needing to use the left navigation. This also breaks visual diff integrations such as Applitools eyes-storybook.

**Screenshots**
***Browse Story url directly***
![image](https://user-images.githubusercontent.com/13340489/54175570-3c899480-44f0-11e9-99e5-96d89523844d.png)
***Navigate to Story through the left menu***
![image](https://user-images.githubusercontent.com/13340489/54175594-51662800-44f0-11e9-81d0-3836e515a381.png)

**System:**
 - OS: Windows10
 - Device: Macbook Pro 2015
 - Browser: all
 - Framework: React
 - Version: 5.0.1

**Comment by shilman** [comment]
Can't repro this on my local machine. See also official storybook:

https://storybooks-official.netlify.com/?path=/story/basics-brand-storybookicon--default

**Comment by FinestV** [comment]
It seems to be related to the `serve` package so may be out of scope. Using `http-server` does not seem to exhibit the issue. Storybook docs however suggest to use serve https://storybook.js.org/docs/basics/exporting-storybook/ "To test it locally: npx serve ."

I have put a simple repro here https://github.com/FinestV/storybook-browse-repro

**Comment by elnygren** [comment]
@FinestV check your devtools - are you getting 200 OK for everything?

I'm having this same issue in now.sh; GET iframe.html is getting a 301 redirect to /iframe which seems to be the only difference to `npx http-server` on my local machine.
