### ISSUE TITLE
tests are not found

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [storybookjs/storybook#6040]
Just run example storybook project with Angular and story with tests saying "This story has tests configured, but no file was found" no matter what i have tried.

**Comment by ZacKeilholz** [comment]
I experienced an issue like this earlier today. Make sure your test filename matches the param you're passing to jest and then try npm run build and then restart Storybook.  Feel free to post some code as well.

**Comment by minuz** [comment]
Hello all, I just ran into the same issue and I'm unsure what's wrong with this...

I pushed a repo that contains a test project that has this problem. Any help would be appreciated! 

https://github.com/minuz/ng-jest-storybook

**Comment by afebbraro** [comment]
Thanks @ZacKeilholz! That worked for me!
