### ISSUE TITLE
Can't use JSX nor import CSS file in a custom addon

### ISSUE THREAD

**Issue by mr-wildcard** [storybookjs/storybook#6047]
**Describe the bug**
I created a custom addon whose purpose is to print the HTML of the current viewed story. But it seems that I cannot import a CSS file nor use JSX in my addon.
Adding a custom webpack config with `babel-loader`, `style-loader` and `css-loader` doesn't fix this issue.

**To Reproduce**
Bug reproduction : https://github.com/mr-wildcard/storybook-custom-addon-bug-repro
Temporary fix : https://github.com/mr-wildcard/storybook-custom-addon-bug-repro/tree/temporay-fix

**Expected behavior**
Storybook should let me use JSX without any custom webpack config.
I might be wrong, but Storybook should also let me import a CSS file in my addon and process it out of the box.

**Code snippets**
see reproduction repository.

**System:**
 - OS: macOS 10.14.3
 - Device: Macbook Pro
 - Browser: Chrome
 - Framework: react
 - Addons: custom
 - Version: 5.0.1

**Comment by shilman** [comment]
cc @ndelangen

**Comment by tourshi** [comment]
I'm also experiencing this issue, v5.0.5

**Comment by shilman** [comment]
I'm not sure why the defaults are that way and I'll let @ndelangen field that.

As for customization, when you do typical "webpack customization" you're customizing the webpack in the `preview`, which is the area where your stories are rendered. However, addons are running in the `manager` which is the UI that wraps it. And it has its own webpack process and configuration.

For more info on customizing manager webpack, see this issue: https://github.com/storybooks/storybook/issues/4995

**Comment by mr-wildcard** [comment]
Thank you @shilman . You're right, I was aware of the preview/manager distinction but didn't realize they were built using different webpack configurations.

I'll try @ndelangen [solution](https://github.com/storybooks/storybook/issues/4995#issuecomment-447270973) 👍
