### ISSUE TITLE
Async storage warning on React Native 0.59

### ISSUE THREAD

**Issue by shaundon** [storybookjs/storybook#6078]
**Describe the bug**
React Native's async storage has [been deprecated](https://github.com/react-native-community/react-native-releases/blob/master/CHANGELOG.md#deprecated). This means that when using Storybook with RN 0.59, a warning appears (see screenshot).

This is on `@storybook/react-native: 4.1.14`. I'm unsure if 5.x is affected.

**To Reproduce**
1. Be on RN 0.59
2. Use Storybook 4.x
2. See warning

**Expected behavior**
A warning not to appear 🙈 

**Screenshots**
![Simulator Screen Shot - iPhone 8 - 2019-03-13 at 18 05 13](https://user-images.githubusercontent.com/73652/54340597-a3fa2e00-462f-11e9-9ccd-6835266e50c9.png)

**System:**
 - Framework: [React Native]
 - Version: [e.g. 4.1.14]

**Additional context**
I'm going to try and make a PR for this - it should be trivial to fix by moving over to the community-supported version of async storage.

**Comment by shilman** [comment]
@shaundon Great catch. Would be great to get this into the 5.1 release which will re-introduce React Native (we didn't release a 5.0 version due to timing issues).

cc @benoitdion

**Comment by shaundon** [comment]
@shilman no worries - how would you feel about also putting it in a `4.1.x` patch release too? The reason being we're still using Storybook 4.1 and upgrading to 5 is going to be a larger task that we're not in a position to undertake yet, so it'd be good to get this fixed in both versions.

**Comment by shaundon** [comment]
⬆️ There's a PR for it - hopefully I've done everything correctly! Let me know if there's anything I've missed.

**Comment by benoitdion** [comment]
Even though this is a trivial change I'd like to defer this to the 5.x release since this does bring in an additional dependency. `react-native-async-storage`'s peer dependency version of react-native is 57 and storybook's 4.x is 51.

**Comment by shaundon** [comment]
On the `next` branch, the RN version is 52 - so won't the peer dependency concern continue to be an issue in the 5.x release?

**Comment by benoitdion** [comment]
It would be. Added a comment to your PR recommending we bump our peer dependency to 57. 

@shilman storybook 5.x is a good opportunity to bump our react native peer dependency version. Both expo and react-native-web have support for >= 57 so that's pretty safe.

**Comment by benoitdion** [comment]
fixed in storybookjs/storybook#6079. Thanks @shaundon!

**Comment by shilman** [comment]
Huzzah!! I just released https://github.com/storybooks/storybook/releases/tag/v5.1.0-alpha.7 containing PR storybookjs/storybook#6079 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

**Comment by shaundon** [comment]
Amazing, thanks! The repo I work on is still on 4.1.x but I'll have a go with a branch using 5.1.0-alpha soon.

**Comment by yurykorzun** [comment]
The fix was reversed - https://github.com/storybooks/storybook/commit/0d7581ac9281944ddf5090975080b46cb07915d1
It looks like we are stuck with the warning for a while https://github.com/react-native-community/react-native-async-storage/issues/14

**Comment by lucasbento** [comment]
@benoitdion: any plans on reversing the reversed commit (haha) anytime soon? I see that the issue you linked is closed and seems to have been solved.

**Comment by benoitdion** [comment]
Absolutely. I'd love to give this another try. Testing takes a bit of time since we need to validate the entire matrix (expo, ejected, app using AsyncStorage, app using community AsyncStorage)

**Comment by bericp1** [comment]
Hey @benoitdion: any word on if this has made it into any recent alphas? Couldn't find any other issue tracking this and this one is still closed. I can submit a PR to reverse the reversed commit if that's helpful at all.

Normally warnings are manageable but this one covers the entire toolbar at the bottom even when it
s minimized. 😢

**Comment by benoitdion** [comment]
not the answer you're looking for but you could use `YellowBox.ignoreWarnings` for now. 

We could try this again now though, they've made a lot of improvements to the community asyncstorage now it should be ready

**Comment by bericp1** [comment]
Oh nice I didn't know [that RN API](https://facebook.github.io/react-native/docs/debugging#warnings) existed. Obviously not preferable but we can use that for the time being. We use a `react-native-config` variable anyway to control rendering of storybook vs. the app in the entry point so we can do it only for storybook which is acceptable.

Cheers!

**Comment by joan-saum** [comment]
Any news about this issue ? I have @storybook/react-native in 5.1.9 and still got that warning :/

**Comment by barbieri** [comment]
meanwhile to quiet the warning one can use the following fixup:

```js
const ReactNative = require('react-native');
Object.defineProperty(ReactNative, 'AsyncStorage', {
  get(): any {
    return require('@react-native-community/async-storage').default;
  },
});
```

**Comment by techgerm** [comment]
This is still the sole issue that's holding us back from upgrading to React Native ^0.60 now that it has been released.
@benoitdion any plans on trying to merge this again soon?

**Comment by techgerm** [comment]
@shilman Was this labeled as `has workaround` since we can quiet the warning? 

From my understanding, there is no current workaround to actually upgrade to React Native 0.60 without having this issue resolved and that is the bigger problem here than just seeing a warning.

If this issue is only concerned about hiding the warning, should I open a separate issue detailing how this is preventing folks from upgrading to React Native ^0.60?

**Comment by shilman** [comment]
@germanp173 Yeah I was referring to the comment above for how to quiet the warning. Re: the upgrade, any interest in putting together a PR for this? I think that would be the easiest way to help push things forward here.

**Comment by techgerm** [comment]
@shilman roger that ... I'll see if I can put one together this weekend, thanks 👍

**Comment by joan-saum** [comment]
@germanp173 did you work on it by any chance ? :) If yes, could you reference your PR here? I think some people like me are subscribe to this issue

**Comment by Gongreg** [comment]
Hey, Since nobody worked on this I've created a PR for this issue. I am using approach that should support both expo/React Native <=0.59 and React Native >= .60 users. Tell me what you think about it.

**Comment by shilman** [comment]
Olé!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-alpha.39 containing PR storybookjs/storybook#7801 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by code-jenn-or** [comment]
This did seem to resolve, looking forward to next release coming out!

**Comment by jgreen210** [comment]
https://github.com/react-native-community/async-storage/issues/118#issuecomment-500138053
