### ISSUE TITLE
Storybook/Theme logo looks incorrect in IE11

### ISSUE THREAD

**Issue by JamesIves** [storybookjs/storybook#6100]
**Describe the bug**
In Internet Explorer, the theme logo is not being properly containing which is causing a weird display bug.

**To Reproduce**
1. Go to any page with IE11.
2. You'll see the issue right away.
3. Even more present on pages with custom themes.

**Expected behavior**

The logo should look correct.

**Screenshots**
Present on pages with and without custom screens, examples below;

<img width="213" alt="Screen Shot 2019-03-14 at 6 02 17 PM" src="https://user-images.githubusercontent.com/10888441/54394494-6626f500-4683-11e9-8a57-a6b697920738.png">
<img width="262" alt="Screen Shot 2019-03-14 at 6 02 23 PM" src="https://user-images.githubusercontent.com/10888441/54394495-6626f500-4683-11e9-8fe7-af25bce96858.png">

**Code snippets**

Theme config looks like this, it's very basic. Issue is present on pages with and without a custom theme, seems to just be a CSS issue with how the logo is wrapped.

```
import {create} from '@storybook/theming';
import logo from 'logo.png';

// Configures Storybook theme.
// More info: https://storybook.js.org/docs/configurations/theming/
export default create({
  base: 'light',
  brandTitle: 'James Ives',
  brandUrl: 'https://jamesiv.es',
  brandImage: logo,
});

```

**System:**
 - OS: Windows 10
 - Device: Laptop
 - Browser: Internet Explorer 11
 - Framework: React
 - Version: 5

**Comment by jamesg1** [comment]
Looks like this issue is solved now as I tested this on https://storybook-design-system.netlify.com/?path=/docs/design-system-badge--all and the logo appears to be working in IE11.

![Screen Shot 2019-09-23 at 12 20 04 PM](https://user-images.githubusercontent.com/3621147/65398772-84bd3400-ddfc-11e9-97af-685bdbac7dab.png)
