### ISSUE TITLE
@storybook/addon-storyshots: NPM Audit warning - braces >= 2.3.1 

### ISSUE THREAD

**Issue by danielfigueiredo** [storybookjs/storybook#6110]
When running NPM / yarn audit throws Regular Expression Denial of Service.
In yarn this is a bit worse because it fails with process code 1 and thus CI.

The following path of dependencies depicts the root origin of the error:
```
@storybook/addon-storyshots > jest-specific-snapshot >  jest-snapshot > jest-message-util > micromatch > braces
```

Most libraries have gotten rid of this vulnerability from braces.

### Steps to reproduce

Install latest `@storybook/framework` and `@storybook/addon-storyshots` and run NPM audit.
### Affected platforms 

I'm on macOS but I don't see why it would be different in another OS.

![angular_—_screen___Users_daniel_Projects_coast_coast-web-ui_—_-bash_—_272×68](https://user-images.githubusercontent.com/6464911/54439933-28bc7900-4710-11e9-96db-8f4c79859f22.jpg)

**Comment by flexiblefactory** [comment]
Still relevant.

**Comment by devina91** [comment]
I agree, still relevant, I too have this vulnerability. in addition to #6622

**Comment by arturopie** [comment]
This issue is still relevant. I tried to help by fixing it on a PR, but I couldn't setup the project to run all the tests. If you can point me to the right documentation for setting up my environment to work on this project, I can make a PR.

**Comment by shilman** [comment]
@arturopie There's a development guide in `CONTRIBUTING.md`. Did you take a look at that?

https://github.com/storybooks/storybook/blob/next/CONTRIBUTING.md#reproductions

**Comment by arturopie** [comment]
Yes, I did and got 6 failed test and 3 failed snapshots after running the core tests.

**Comment by shilman** [comment]
@arturopie Failed tests in the `next` branch?

**Comment by arturopie** [comment]
Yes

**Comment by agwells** [comment]
Upgrading to `@storybook/addon-storyshots`@`5.1.3` resolved this issue for me.
