### ISSUE TITLE
Allow fetchLatestVersion xhr request to be turned off

### ISSUE THREAD

**Issue by johnhunter** [storybookjs/storybook#6116]
**Is your feature request related to a problem? Please describe.**
Storybook v5 makes an xhr GET request to `https://storybook.js.org/versions.json`. This  contravenes our internal policies and blocked. However, I continue to receive alerts and have been asked to remove it.

**Describe the solution you'd like**
Provide a way to disable the request though config, or as a CLI build parameter. I.e. add an additional condition to https://github.com/storybooks/storybook/blob/6234e7abe9a7f762d4f0c285fe456b59fcb73d6c/lib/ui/src/core/versions.js#L67

**Describe alternatives you've considered**
Options are:
- Downgrade to v4 - which would be a real shame since v5 is soo good.
- Fork and comment out the fetch

**Are you able to assist bring the feature to reality?**
I would love to raise a PR, not sure how soon I can do that.

**Comment by johnhunter** [comment]
Perhaps `checkInterval` could be set in config with some sort of value that indicates never?

https://github.com/storybooks/storybook/blob/master/lib/ui/src/core/versions.js#L7

**Comment by johnhunter** [comment]
Looks like https://github.com/storybooks/storybook/pull/6143 resolves this issue as long as I use the production build.

**Comment by johnhunter** [comment]
hmm... reporting is turned off in production but we still make the request
https://github.com/storybookjs/storybook/blob/e5001cd9277976143c724c4f02043cb01b64a9ba/lib/ui/src/core/versions.js#L81-L88

**Comment by shilman** [comment]
@johnhunter Ouch. I'll look into this!
