### ISSUE TITLE
Storybook won't work with Fela + preact

### ISSUE THREAD

**Issue by matthewharwood** [storybookjs/storybook#6122]
https://stackoverflow.com/questions/55193107/invalid-attempt-to-destructure-non-iterable-instance-when-using-fela-css-in-js-w/55193190?noredirect=1#comment97124570_55193190

Im getting an error when I try to render the preact-fela RendererProvider inside storybook
![Error](https://i.stack.imgur.com/44pv5.png)

I def got it working in a non-storybook scenario shown here:

https://codesandbox.io/s/9oj37oyv3r

**To Reproduce**
- Make an instance of preact-storybook.
- `npm install preact-fela preact-context --save`
- open the `.storybook/config` and add:
```
import { configure, addDecorator } from '@storybook/preact';


const req = require.context('../libs', true, /\.story\.js$/);
import { createRenderer } from "fela";
import { createComponent, FelaComponent, RendererProvider } from "preact-fela";

const renderer = createRenderer();
console.log(RendererProvider);
import { h } from 'preact';

addDecorator(story => (
  <RendererProvider renderer={renderer}>
    {story()}
  </RendererProvider>
));


function loadStories() {
  req.keys().forEach(req);
}

configure(loadStories, module);
```

**Comment by shilman** [comment]
What version of preact?

**Comment by shilman** [comment]
Possibly relevant: https://twitter.com/marvinhagemeist/status/1105346547338878976?s=21

**Comment by matthewharwood** [comment]
@shilman I think it's more about fela than preact.  But I'll try fela, with react storybook tonight.

**Comment by matthewharwood** [comment]
@shilman I'm still blocked by this I and fela thinks it's storybook problem.  Could ya please help https://github.com/rofrischmann/fela/issues/690

**Comment by shilman** [comment]
@matthewharwood Did you get it working with fela+react in Storybook?

**Comment by rofrischmann** [comment]
@shilman @matthewharwood My first thought was: It's either a Preact or Storybook issue as react-fela and preact-fela built on the exact same source and react-fela works perfectly fine with Storybook.

**Comment by shilman** [comment]
@rofrischmann I'm confused why we're having this conversation. 😄 AFAIK there's a known issue with preact & storybook that I linked to above in a twitter convo. But @matthewharwood said he thought it was about Fela. So ... ???

**Comment by rofrischmann** [comment]
Oh sorry, didn‘t see that. So I guess that‘s the issue then? Can‘t see how this issue is Fela related either.

**Comment by matthewharwood** [comment]
@shilman @rofrischmann Sorry for the confusion.  I don't think the issue linked above is the problem: https://twitter.com/marvinhagemeist/status/1105346547338878976?s=21.  Because, Storybook works with preact@next.  The only issue I know of storybook and preact is because preact uses mjs https://github.com/storybooks/storybook/issues/6003.

I did a bit more research and here's what I found:

These combinations work:
preact + fela
preact + storybook
react + fela + storybook

This combination does **not** work:
preact + storybook + fela

 Any ideas what the error I listed above could mean?

**Comment by shilman** [comment]
Thanks for the followup @matthewharwood. I'm on vacation for the next week but I'll take a closer look when I get back if somebody else doesn't get to it first. If you're interested in debugging it yourself, you can run it in dev mode in the repo by adding your code to `examples/preact-kitchen-sink` then:

```
yarn bootstrap --core
cd examples/preact-kitchen-sink
yarn storybook --no-dll
```

If you want to hack on the code, you can run `yarn dev` in another window (CPU intensive on startup). More info in `CONTRIBUTING.md`.

**Comment by matthewharwood** [comment]
@shilman I make the smallest app I could with preact@next, fela, & storybook here:
https://github.com/matthewharwood/testing-storybook-fela

I'm still unable to figure out why it's broken.

I tried the preact-kitchen-sink and I was unable to even get preact working.  Any help would be awesome!
