### ISSUE TITLE
addon-a11y — Not working with config withInfo({ inline: false })

### ISSUE THREAD

**Issue by weeksling** [storybookjs/storybook#6127]
Our team recently discovered that that you can only get accessibility testing working if withInfo has the option { inline: true }

I would like to either:
  - Add a note of this on the readme.md for the plugin, or 
   - Write a fix to make this work with { inline: false }

Adding this so there is a location to add my pull request when it is ready, and to get any correction or feedback in case I am approaching this incorrectly.

### Please specify which version of Storybook and optionally any affected addons that you're running

```
{
    "@storybook/addon-a11y": "^4.1.13",
    "@storybook/react": "^4.1.13",
}
```

**Comment by shilman** [comment]
Upgrade to `5.0.x`/`5.1.x-alpha` if you can. There have been a lot of good a11y improvements recently.

**Comment by shilman** [comment]
Hoping to replace info with Docs which won't have this issue: https://medium.com/storybookjs/storybook-docs-sneak-peak-5be78445094a
