### ISSUE TITLE
Backgrounds addon does not allow scrolling when having many background options

### ISSUE THREAD

**Issue by stmoreau** [storybookjs/storybook#6150]
**Describe the bug**
When using the backgrounds addon and have many different options on the select I am not able to scroll the select element. This is causing an issue because I am not able to select many of the colours that I have used as options.

**To Reproduce**
1. Create a storybook with more options than the the height of the screen can fit
2. Open storybook and see the error. Some of them will be hidden hence not selectable

**Expected behavior**
When having many options in the background addon I expect to be able to select any of them without a problem

**Screenshots**
![image](https://user-images.githubusercontent.com/15115885/54534875-39295980-4985-11e9-8d2a-151f68391638.png)

**System:**
 - OS: [all]
 - Device: [all]
 - Browser: [all]
 - Framework: [stencil, but same error happens with any framework]
 - Addons: [backgrounds]
 - Version: [e.g. 5.0.3]

**Comment by stmoreau** [comment]
This issue has been added to the [v5.1.0 milestone](https://github.com/storybooks/storybook/milestone/13) so hopefully it will get picked up by someone and not get buried forever 😆

**Comment by shilman** [comment]
Is this anything you might be able to work on? TBH there are many higher priority issues in the pipe.

**Comment by stmoreau** [comment]
This could be a quick fix, but not sure I will get the time any time soon to look into it

**Comment by stmoreau** [comment]
Hopefully, this won't get closed 😄

**Comment by stmoreau** [comment]
:)

**Comment by stmoreau** [comment]
I will just comment one last time to remove the inactive label, in case someone wants to work on it then I will give up 😃 

(sorry about that)

**Comment by shilman** [comment]
Ta-da!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-beta.41 containing PR #7865 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
