### ISSUE TITLE
[Addon Action in v5]: Issue when serializing a Vue instance

### ISSUE THREAD

**Issue by miljan-aleksic** [storybookjs/storybook#6153]
**Describe the bug**
The arguments are not longer decycled in v5. The source code in v4 had a whole decycle function taking care of conficting arguments, this and is now gone in v5.

**To Reproduce**
1. Try to log an action with a cycled argument (with circular references).

**Expected behavior**
I would expect this change to have been documented and a workaround provided.

**Additional context**
I tried using some 3rd party decycle but they are not working as expected.

The env is Vue and the arguments passed by are Vue instances, which will trigger
`[Vue warn]: Property or method "toJSON" is not defined on the instance but referenced during render`. 

As per my understanding this means that during the action arguments processing the objects will be stringified and expected to have a toJSON method, which vue doesn't.

I assume in v4 the inbuild decycle util was doing some thorough work.

**Comment by shilman** [comment]
@ndelangen Did de-cycling break in telejson?

**Comment by miljan-aleksic** [comment]
For the reference the errors I am getting are related to a non existing `toJSON` function in my argument objects. Which is actually not about circular references, but in v4 this was working fine.

**Comment by miljan-aleksic** [comment]
I was able to reproduce this on a simpler configuration and so far I can only confirm is happening with the Vue version. Creating a simple story and trying to log the story vue instance would trigger the toJSON error. Ex

```vue
<template>
    <div>
        <button class="btn btn-primary" type="button" @click="trigger()">Action</button>
    </div>
</template>

<script>
import {action} from '@storybook/addon-actions';

export default {
    methods: {
        trigger(event, params) {
            action('test')([this]);
        }
    }
};
</script>
```

**Comment by shilman** [comment]
cc @ndelangen

**Comment by shilman** [comment]
Is this still an issue? cc @ndelangen

**Comment by miljan-aleksic** [comment]
Is there any interest in solving this?

**Comment by shilman** [comment]
@miljan-aleksic Yes do you want to take a crack at it?

**Comment by miljan-aleksic** [comment]
@shilman, our solution was to implement the SB 4.x decycle into SB5, I don't think that would be accepted. As for working on a real solution I would need to speak with the guy who made this change in the first place, or someone who knows the motivations behind.

Anyway, I would start by adding some more tests, this would not happen with them in place.

**Comment by shilman** [comment]
Thanks @miljan-aleksic. Hopefully @ndelangen sees these mentions and can help you get these changes in.

**Comment by ndelangen** [comment]
Sorry for the delay, @miljan-aleksic I'd be available to chat about the needed changes, join me on discord? https://discord.gg/sMFvFsG

**Comment by miljan-aleksic** [comment]
@ndelangen, I did :)

**Comment by ndelangen** [comment]
I'm on it

**Comment by miljan-aleksic** [comment]
After debugging this with @ndelangen it turns out to be a Vuejs specific issue when a Vue instance is attempted to be serialized. The Telejson library will attempt to use `JSON.stringify` on the Vue instance object which will expect the `toJSON` method to exist, as it does not Vue will warn about a undeclared method being referenced during render.

Serializing a Vue instance is not supported and most likely [will never be](https://github.com/vuejs/vue/issues/10102), and as such it must be addressed by Storybook. Fairly enough is quite simple, and even though it looks like a hack is actually the suggested way of extending Vue:

```
Vue.prototype.toJSON = function () {
    return this;
};
```

This issue can be reproduced in the current Storybook Vue kitchen sink example, triggered by specifically [this](https://github.com/storybookjs/storybook/blob/next/examples/vue-kitchen-sink/src/stories/addon-actions.stories.js#L21-L28) lines. I stay available for further help on this matter.
