### ISSUE TITLE
Navigation tree collapse all

### ISSUE THREAD

**Issue by jjspace** [storybookjs/storybook#6157]
**Is your feature request related to a problem? Please describe.**
Our storybook is fairly with the number of stories and categories so when opening multiple categories it quickly grows past the vertical space on our screens

**Describe the solution you'd like**
I would love if there was a button to collapse all categories so I can clean up the navigation and reopen only the categories I'm currently focused on.

**Additional context**
Many code editors have this feature for the file explorer. For example I use it often in our large shared-ui library in VSCode when refocusing onto a different issue

**Comment by chawlaaditya8** [comment]
I would like to work on this one

**Comment by creatyvtype** [comment]
@chawlaaditya8 what's the progress?

**Comment by whitetig3r** [comment]
@creatyvtype I would like to work on this issue. Is this up for grabs?

**Comment by shilman** [comment]
@whitetig3r def up for grabs!

**Comment by whitetig3r** [comment]
> @whitetig3r def up for grabs!

Will submit a PR soon! :)

**Comment by whitetig3r** [comment]
I'm new to working with `Storybook` development. I've been looking through the code and the patterns followed. Given the feature request, I suppose, I should add another menuItem in `nav.js` and `onClick : () => api.collapseTree()` is the required callback that should be created.

It would be super helpful if you could give me a few cues on where and how to implement this `api` callback which results in calling the `updateExpanded()` function `(treeview.js)`: in `api/lib/layout.ts` or somewhere else? @shilman

**Comment by shilman** [comment]
@ndelangen would you mind giving him a pointer?

**Comment by atanasster** [comment]
Hi, have you checked this request and is it a priority?
It looks like a major task and will probably need to refactor the expanded stories state into the global state and have a provider/consumer actions.
Otherwise it might be too much of a hack.
what do think @shilman @ndelangen

**Comment by shilman** [comment]
@atanasster looks like you figured it out! 💪

**Comment by atanasster** [comment]
Sorry, still learning the code :)
