### ISSUE TITLE
visual indication if HMR is rebuilding

### ISSUE THREAD

**Issue by alexan** [storybookjs/storybook#6196]
**Is your feature request related to a problem? Please describe.**
I use storybook for local component development. Sometimes Its hard for me to see if and when the HMR is rebuilding and when it is finished. 

**Describe the solution you'd like**
A loading spinner could be displayed while HMR is running. This could be overlayed or somewhere inserted in the current ui.

**Describe alternatives you've considered**
At the moment I use to have the dev tools open which shows this information in the logs.

**Are you able to assist bring the feature to reality?**
yes, I can...

**Comment by shilman** [comment]
Nice feature--super useful 👍

**Comment by shilman** [comment]
@alexan any interest in picking this up?

**Comment by alexan** [comment]
I fiddled around getting the frontend running during development. I did not finde a reliable setup for getting my react changes in the browser without triggering `createDlls` all the time

**Comment by shilman** [comment]
@alexan You can run storybook with the `--no-dll` flag to disable this optimization. It's what we do in `examples/official-storybook` to develop interactively
