### ISSUE TITLE
storybook deploy logs public on Google

### ISSUE THREAD

**Issue by tiffanytse** [storybookjs/storybook#6200]
**Describe the bug**
Your deploy logs are publicly searchable on Google; not sure if you want this to be the case. 

**To Reproduce**
1. Go to 'https://www.google.com/search?ei=yXOSXJ_ABcSwtgXb56TwDQ&q=gatsby-plugin-emotion+%3E+%40babel%2Fplugin-transform-react-jsx%407.2.0+has+unmet+peer+dependency+%40babel%2Fcore%40%5E7.0.0-0&oq=gatsby-plugin-emotion+%3E+%40babel%2Fplugin-transform-react-jsx%407.2.0+has+unmet+peer+dependency+%40babel%2Fcore%40%5E7.0.0-0&gs_l=psy-ab.3...2773.6104..6403...0.0..0.0.0.......1....1..gws-wiz.WbHio4ig590'

Just thought you should know that this information is public at the moment.
https://app.netlify.com/sites/storybooks/deploys is publicly accessible.

**Comment by wuweiweiwu** [comment]
hi @tiffanytse thanks for letting us know. I believe our secrets are all stored securely
