### ISSUE TITLE
Change name of "Polymer" app/addon.

### ISSUE THREAD

**Issue by gugadev** [storybookjs/storybook#6208]
Looking at the present and future, I think holding the `@storybook/polymer` name is not very accurate anymore. In fact, that package is compatible with any native web components wrapper like lit-element, haunted, and so on (maybe stencil too). 

For that reason I suggest change the name to `@storybook/web-components` or `@storybook/custom-elements`, it's more accurate than actual one. Same for `@storybook/addon-web-components`.

PD: I would help on those ackages 😃

**Comment by ndelangen** [comment]
I think that makes perfect sense TBH, We'd have to change some test names and maybe netlify sites names and such, but that's alls fairly straight forward.

Happy to accept your help offer @owgus!

Are you on out discord already?

**Comment by owgus** [comment]
> I think that makes perfect sense TBH, We'd have to change some test names and maybe netlify sites names and such, but that's alls fairly straight forward.

@ndelangen That's great.

> Are you on our discord already?

Yeah! I just joined (username: osgusdev)!

**Comment by daKmoR** [comment]
So what should be the name?
- `@storybook/web-components` => probably used mostly by web component people
- `@storybook/lit-html` => technically it just uses lit-html to render html with properties
?

**Comment by shilman** [comment]
I vote web-components

**Comment by stuxdev** [comment]
Yeah, is the most accurate name, IMO.

**Comment by ndelangen** [comment]
@gugadev would you open a PR?

**Comment by emilio-martinez** [comment]
I'd like to keep this open. 👋

**Comment by gugadev** [comment]
Keep it open, currently I'm very busy but I'm working on the PR!

**Comment by bashmish** [comment]
> So what should be the name?
> 
> * `@storybook/web-components` => probably used mostly by web component people
> * `@storybook/lit-html` => technically it just uses lit-html to render html with properties
>   ?

`@storybook/lit-html` is a more accurate name for what it does.

**Comment by shilman** [comment]
We have a `@storybook/web-components` now. Is anything further needed here? Should we deprecate this package somehow in 6.0?

**Comment by ndelangen** [comment]
Yeah I think it's better to continue with `web-components` only in the long term.

Do you agree @daKmoR ?

**Comment by daKmoR** [comment]
jup, I agree - only polymer 2 (superseded by polymer 3 & lit-element) applications would still need it - HTML imports are not going to happen and that is the only reason you would stick with `@storybook/polymer`.

**Comment by ndelangen** [comment]
Shall we just not update app/polymer anymore (and therefore remove it from the monorepo in 6.0.0) ?

**Comment by shilman** [comment]
YES PLEASE! 🙏

**Comment by ndelangen** [comment]
consider it done, kinda sorry for @kroeder 's efforts to migrate it to TS

**Comment by shilman** [comment]
it'll go to `storybook-eol` repo?

**Comment by ndelangen** [comment]
I'd have to extract it out, I don't know if I can do that preserving history, and all.

It will take more time. And for what gain exactly?

**Comment by shilman** [comment]
Probably into its own repo with a big fat deprecation warning at the top of the README. We can't just start deleting packages without warning. We need to deprecate the packages and give users time to migrate off. This means that for some amount of time, users need to be able to submit bugfixes or security fixes. I don't care if we have the github history preserved -- if people really want they can check the monorepo.

**Comment by ndelangen** [comment]
https://github.com/storybookjs/polymer

**Comment by shilman** [comment]
Yee-haw!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-alpha.1 containing PR #9596 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
