### ISSUE TITLE
withInfo show functions

### ISSUE THREAD

**Issue by PaulieScanlon** [storybookjs/storybook#6216]
withInfo `source: true` is great but it lacks the ability to show more complex source
Currently when doing something like this 

```
<button onClick={(event) =>  handleClick(event)}>Click Me </button>
```

withInfo source shows

```
<button onClick={onClick}>Click Me </button>
```

ideally it would show the source as it appears in the story source code

```
<button onClick={(event) =>  handleClick(event)}>Click Me </button>
```

I will occasionally use `react-markdown`, create a readme.md file and render that in a story but it would be way better if source showed all the things that make up the source, not just the component definition.

![Screen Shot 2019-03-21 at 12 22 45](https://user-images.githubusercontent.com/1465706/54751862-1b9dff00-4bd4-11e9-94ca-71520a65dc0d.png)

**Comment by shilman** [comment]
Hey, this is a reasonable request and a limitation of the info addon. I'm working on a replacement now that will be cross-view layer and support a bunch of new documentation features, so I'll try to make this request a part of that. No ETA yet but I hope to release the first version in 5.1.

**Comment by PaulieScanlon** [comment]
@shilman that's great to hear man, thanks!!!  i did actually try to clone the Storybook repo and investigate myself but i fear i'm not the man for the job... as you can see i only make buttons :-)

**Comment by PaulieScanlon** [comment]
Hey man! How’s it going? Have you had a chance to investigate this any further? I’d love to see a fix for this... cheers!

**Comment by shilman** [comment]
@PaulieScanlon 

Some progress: https://medium.com/storybookjs/storybook-docs-sneak-peak-5be78445094a
Current release schedule: https://gist.github.com/shilman/1428d44b2b53644e7b952ac441d2e954

We'll get there 😉

**Comment by PaulieScanlon** [comment]
@shilman this is awesome... it’s gonna blow the design team’s mind! I can’t wait for tomorrow! Thanks man... and team!

**Comment by shilman** [comment]
@PaulieScanlon This is working well in docs now:

<img width="1220" alt="Storybook" src="https://user-images.githubusercontent.com/488689/57824755-b549ed00-77ce-11e9-9a5b-a19507dacc77.png">

**Comment by PaulieScanlon** [comment]
@shilman This looks great! what version of Storybook was this released in i'm still on `5.0.6`

**Comment by shilman** [comment]
@PaulieScanlon 5.2.0-alpha.x. https://docs.google.com/document/d/1un6YX7xDKEKl5-MVb-egnOYN8dynb5Hf7mq0hipk8JE/edit?usp=sharing

**Comment by PaulieScanlon** [comment]
@shillman 🤦‍♂️ Of course! Thanks man!
