### ISSUE TITLE
Load Preview Head from Outside configDirPath

### ISSUE THREAD

**Issue by alex-bezek** [storybookjs/storybook#6220]
Internally, we have a re-usable package that maintains a set of storybook config that sets it up with some defaults and configures it to work with our component library. We then configure our projects with a script like `our-package run-storybook` which runs something like

```js
result = spawn.sync(
    'node',
    [resolveBin('start-storybook')]
      .concat(['-c', `${paths.appNodeModules}/our-package/config/storybook`])
      .concat(['-p', '9001']),
    {stdio: 'inherit'},
  );
```

The issue is that I would like to provide a preview-head.html from my consuming project. However, storybook looks for this file within the config directory
https://github.com/storybooks/storybook/blob/4da246bbe9413510b48d1ab8b9faf4fae4656d92/lib/core/src/server/utils/template.js#L16

So I seem to be fighting myself by trying to have the configuration abstracted into a shared package with its own storybook config folder, while also having my project provide a preview-head.html in a different folder.

**Describe the solution you'd like**
For the directory of the preview-head.html to be configurable separate from the main config folder. If this were possible, our re-usable package could take a config of some sort to specify the preview-head.html location and pass it down to the storybook cli.

**Describe alternatives you've considered**
Hacky ways to get my file into my node modules config folder (sym linking, copying during a post install, etc)

**Are you able to assist bring the feature to reality?**
Depends on the complexity of the proposed solution, I'm very new to the storybook code base

Let me know if there is a config or way to do this I'm missing. Thanks!

**Comment by cookch10** [comment]
The ability to have a dynamic preview-head html would be extremely useful.
