### ISSUE TITLE
Update code owners

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#6223]
@Hypnosphi recently [removed himself](https://github.com/storybooks/storybook/pull/6221) from code owners and it occurred to me that this file hasn't been maintained.

I think we should either delete the file or come up with a better policy for this.

Here's a strawman for discussion. Being a code owner:
- comes from contributing consistently to an area
- makes you a go-to person for PRs and questions/support related to an area
- gets you featured on the team page https://storybook.js.org/team/

I've personally managed every incoming issue and PR for the past few weeks as part of the v5 release, and it would help that process immensely. For example:
- If I could tag an area as "a11y" and know that it would get routed to @CodeByAlex, @Armanio, and @jsomsanith who have all been very active here, that would be awesome
- There have been countless times in the past year that somebody has wanted help with `@storybook/vue` (at this point our second-most popular view layer!) and not known who to contact.

**Comment by CodeByAlex** [comment]
@shilman you can tag me for a11y

**Comment by shilman** [comment]
https://help.github.com/en/articles/about-code-owners

Code owners are for subdirectories of the code. They are automatically requested to review pull requests that touch that code. There's no reason we couldn't use the same file to automate other stuff like notifications. Not sure what Github provides natively if anything, but they have a rich API that I've used extensively for automating release-related stuff.

**Comment by CodeByAlex** [comment]
@shilman, I like the sound of that. I am interested in being a code owner of a11y if we split it up that way.

**Comment by jsomsanith** [comment]
Hey @shilman.

It's an honor to be in this list :D , but I have a question about the commitment.
The time I can allocate can be quite low (I just had a 2nd baby :) ). So what do you expect from code owner in practice ?
I mean, is it problematic for code owners to be inactive during unknown period of time ?
- Yes, I will pass because I don't think I'll fit
- No, with pleasure

In either way I'd like to help in questions/reviews when I can.

**Comment by shilman** [comment]
@jsomsanith congratulations!!!! 🎉👶🍾

As for commitment, I think that's really TBD. First of all this is an OSS project so it's completely voluntary and we all understand that people come and go and that's fine. And it's fundamental. Also, this had better be fun.

Given that, there's a whole range of possible commitment ranging from something very strict (which I'm sure WON'T fly) to none at all (which also isn't so useful).

My strawman would be that as a code owner you agree to get notified for issues/PRs/questions relating to the area that you own, are cool with having people `@mention` you in Github/Discord related to that topic, and will make an effort **subject to your availability, which may change a lot due to work/life commitments** to help push that area of the project forward. If it's overwhelming or stops being fun/interesting, step down. And if it becomes reasonable again, step back up again.

**Comment by Armanio** [comment]
Of course, I agree. 🎉
Honestly, its honor for me. I am ready to do my best.

**Comment by backbone87** [comment]
i can offer to be available for reviews/issues/questions regarding `@storybook/vue`

**Comment by jsomsanith** [comment]
@shilman Thank you :)

Your description seems great, and having notification surely will help to contribute more. Let's go for it :D

**Comment by leoyli** [comment]
I'm also interested in helping since we are using SB as part of our developing and automated code reviewing tools.  It is reasonable to put efforts back to the community and get my bug reports fixed quick.  After all, to improve SB is also going to improve my daily workflow, so why not?! I will take some time to see which area or direction I can help.
