### ISSUE TITLE
Action addon causes Maximum Call Stack

### ISSUE THREAD

**Issue by ar7casper** [storybookjs/storybook#6287]
**Describe the bug**
I've built a Button component using `react-pose` library. 
In my story I called `<Button onClick={() => {}}>Text</Button>` and everything worked fine.

When adding the button in a Dialog component, it suddenly started being very laggy on localhost and threw a "Maximum call stack" error with NODE_ENV=production in the build. 

The only difference was that for the Dialog Story, I used `<Button onClick={action('clicked')}>Text</Button>`.

Removing the action solved the problem.

The code for the Button is very basic, -
`
const Button = posed.button({
   pressed: true,
  init: {scale: 1},
  press: {scale: 0.8}
})
`

and for the Dialog as well, -  
```
const Dialog = () => {
  return (
    <div>
      <....>
      <Button .... />
    </div>
  )
}
```

**Comment by shilman** [comment]
What version of Storybook?

**Comment by Armanio** [comment]
It should be fixed in 5.1.0-alpha.15. Check it please.

**Comment by ar7casper** [comment]
@shilman 
Yeah, sorry for not pointing that out, ver 5.0.1 (I can't upgrade for some reason it fails, still trying)
@Armanio 
Thanks, I can take it for a spin soon and let ya know

**Comment by Armanio** [comment]
@ar7casper it's issue actually?
