### ISSUE TITLE
Addon-info doesn't work with Vue jsx components

### ISSUE THREAD

**Issue by maratfakhreev** [storybookjs/storybook#6296]
**Describe the bug**
I've tried to use `addon-info` globally or locally but the error still occurs.

**To Reproduce**
On the screen you can see exact story code. I think additional description isn't necessary.

Storybook version: 5.0.3
Vue version: 2.5.13

Also using the styled components

**Screenshots**
![image](https://user-images.githubusercontent.com/1300497/55012628-c2313800-4ff8-11e9-91e6-763776a7cc34.png)

**Comment by maratfakhreev** [comment]
Sorry, it's not for storybook, it is for specific plugin `addon-info`

**Comment by shilman** [comment]
Addon-info is currently only for react. I'm working on a replacement that will be compatible with all view layers.

**Comment by maratfakhreev** [comment]
@shilman ok, thanks. Will be waiting for it

**Comment by shilman** [comment]
Some progress!

<img width="716" alt="Storybook" src="https://user-images.githubusercontent.com/488689/55663627-48e4e100-5853-11e9-83ce-407affb9ed8d.png">

**Comment by shilman** [comment]
Docs version tracked here https://github.com/storybooks/storybook/issues/6663
