### ISSUE TITLE
HMR clears the component state

### ISSUE THREAD

**Issue by haskelcurry** [storybookjs/storybook#6308]
I use Angular Storybook. When I change something slightly (i.e. the component's SCSS), the input fields of my simple component get cleared, and the whole state is lost.

**To Reproduce**
1.
```
storiesOf('Input', module)
  .add('with text', () => ({
    template: '<input/>'
  }))
```
2. In Storybook app, insert some text in the input field
3. Change something not related to this component
4. The text gets cleared. The `config` is among the [HMR] updates:
```
[HMR]  - ./.storybook/config.js
```

**Expected behavior**
The state of inputs should persist. That's what the HMR for, not just for live  reloading.

**System:**
 - OS: Arch Linux
 - Browser: chrome
 - Framework: angular
 - Version: 5.0.5

**Comment by mtuzinskiy** [comment]
Any thoughts or comments on this?

**Comment by shilman** [comment]
cc @kroeder @CodeByAlex @jonrimmer

**Comment by jonrimmer** [comment]
@mtuzinskiy This may have been fixed by #6094. Can you test using `@storybook/angular` version `5.1.0-alpha.25` and see if it still happens?

**Comment by mtuzinskiy** [comment]
@jonrimmer That would be great! I tried to update the `@storybook/angular` in  basic example to `5.1.0-alpha.25` and got this:  
```
Provider.renderPreview() is not implemented!
```

**Comment by shilman** [comment]
@mtuzinskiy can you try clearing your node_modules and possibly your yarn.lock?

**Comment by mtuzinskiy** [comment]
@shilman Yes that was it. But unfortunately it didn't solve the problem. I created the sample project, which uses `5.1.0-alpha.25`:  
https://github.com/mtuzinskiy/storybook-hmr-temp
To reproduce, please clone it, run `yarn install` and then `yarn storybook`.
It'll render the simplistic Input component.
Enter anything in the input, and then change the `margin:` value in `input.component.scss`. You'll see that the input gets cleared.

**Comment by mtuzinskiy** [comment]
@shilman  Can we please reopen it?..

**Comment by mtuzinskiy** [comment]
Yes it's still a bug

**Comment by ndelangen** [comment]
@jonrimmer could you have a look at this repro?
https://github.com/storybookjs/storybook/issues/6308#issuecomment-482794031

**Comment by danawoodman** [comment]
AFAIK, this seems to still be an issue, at least for me with a React application using the latest packages.

**Comment by deanius** [comment]
Yes, CodeSandbox does this safely, but Storybook doesn't (as of 5.3.9)

**Comment by valentinpalkovic** [comment]
Please reopen and provide a reproduction, if this issue still exists for Storybook 7.
