### ISSUE TITLE
React Native TextInput Autofocus Infinitely opens and closes keyboard

### ISSUE THREAD

**Issue by owinter86** [storybookjs/storybook#6309]
**Describe the bug**
A story with a TextInput that auto focuses will continually open and close the keyboard when selecting the story on the Navigator ui.

**To Reproduce**
Create a story with a TextInput with the prop autoFocus={true}, navigate to story in the React Native ui, see keyboard continually open and close until Preview mode is selected.

**Expected behavior**
Either selecting a story from the navigator should auto navigate to the "Preview" (or have an option to toggle this behaviour) or the keyboard should not force dismiss if appearing when in the navigator view.

**System:**
 - React Native 0.59.2
 - Storybook: 5.1.0-alpha.18

**Comment by AtlasRider** [comment]
Also having this issue

**Comment by Gongreg** [comment]
Hey @owinter86. We could implement your suggestion to add option to allow to automatically focus story to preview. It could be an option inside getStorybookUI.

Fixing the main issue would require more investigation, since we have some logic to properly handle keyboard.

Could you create a PR for that option?

**Comment by owinter86** [comment]
Hey @Gongreg I should have some time end of this week to implement the auto focus option. I will file a PR as soon as I can.

**Comment by owinter86** [comment]
@Gongreg The auto open preview wont fix the issue in the end as it just returns as soon as you go to navigator to change story. So I think we will need to look into the logic around the keyboard.

**Comment by Gongreg** [comment]
https://github.com/storybookjs/storybook/blob/next/app/react-native/src/preview/components/OnDeviceUI/absolute-positioned-keyboard-aware-view.tsx I wish you luck! :D Touching keyboard part is quite scary since we need to be aware about ios android portrait/landscape mode and rotation.
