### ISSUE TITLE
Storyshot should split tests in a way that Jest only tests changed components

### ISSUE THREAD

**Issue by joms** [storybookjs/storybook#6331]
**Is your feature request related to a problem? Please describe.**
When running tests using Storyshots and Jest for React with CRA, it will run all tests for Storyshots even if only a single component changed. This makes the test running take a lot more time than required.

**Describe the solution you'd like**
When running test runner using Storyshots I would want Storyshots to split up the tests as if I've written separate test files. This way Jest will only run tests for changed components in stead of all of them.

**Describe alternatives you've considered**
The only alternative as I see it is to write the tests manually, which takes away the point of Storyshot.

**Are you able to assist bring the feature to reality?**
We could probably assist in the development of this feature

**Comment by danielbartsch** [comment]
`jest`'s `findRelatedTests` option would do this. But it doesn't work for storyshot testing unfortunately :/
