### ISSUE TITLE
Storybook Typescript preset

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#6342]
We're rewriting Storybook in Typescript https://github.com/storybooks/storybook/issues/5030 which means we'll soon have native type support for every SB package. Let's also make it a one-liner to use Typescript with all of our supported view layers:
- [x] Typescript preset with sensible defaults
- [ ] Ensure that it works with every view layer
- [x] Add to CLI `sb init --story-format=csf-ts`
- [x] Auto-infer typescript in `sb init` if `tsconfig.json` exists
- [ ] Add to documentation
- [ ] Babel typescript option

**Comment by shilman** [comment]
Released `@storybook/preset-typescript` and need to update docs.

**Comment by sw-yx** [comment]
hey @shilman! great work! it would be good to clarify if this applies for just components written in tsx or also for stories. 

also outline when transpileManager is useful vs not

**Comment by shilman** [comment]
Or `--language typescript` per #7492

**Comment by shilman** [comment]
Olé!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-alpha.21 containing PR #8451 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by sw-yx** [comment]
happy to close it! congrats on shipping

**Comment by shilman** [comment]
@sw-yx Thanks!!! still lots to do -- gonna make TS 👌 in Storybook! One step closer tho!!

**Comment by shilman** [comment]
We've just released zero-config typescript support in 6.0-beta. Please upgrade and test it!

- [Release 6.0.0-beta.12+](https://github.com/storybookjs/storybook/releases/tag/v6.0.0-beta.12)
- [Migration instructions](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#zero-config-typescript)
- [Updated docs](https://github.com/storybookjs/storybook/blob/next/docs/src/pages/configurations/typescript-config/index.md)

Thanks for your help and support getting this stable for release!

**Comment by shilman** [comment]
Since typescript is being built in, closing this! 🎉

**Comment by sw-yx** [comment]
nice work
