### ISSUE TITLE
[Addon: info - v5.x] No Prop Types table if using React.forwardRef

### ISSUE THREAD

**Issue by liamross** [storybookjs/storybook#6345]
### Describe the bug

In version 5.0.x of the **info** addon, the **Prop Types** section is not appearing if the component is wrapped in `forwardRef`. This is in a **TypeScript** project.

<img width="728" alt="Screen Shot 2019-03-29 at 11 13 02 AM" src="https://user-images.githubusercontent.com/24969218/55253913-d0a76b80-5213-11e9-9a99-040156b46014.png">

> Note: may be related to #5974

### To Reproduce

1. Create any component using `forwardRef` in React.

### Expected behaviour

Should match up with the result of version `4.x` (table is present)

### System

 - OS: MacOS
 - Device: Macbook Pro 2018
 - Browser: all
 - Framework: React
 - Addons: info
 - Version: 5.0.g
- Language: TypeScript

**Comment by liamross** [comment]
Maybe related to #3389 as well? Regression?

**Comment by shilman** [comment]
How did you setup docgen for typescript?

**Comment by liamross** [comment]
<details><summary><code>.storybook/webpack.config.js</code></summary>

```js
const path = require('path');
const TsconfigPathsPlugin = require('tsconfig-paths-webpack-plugin');

module.exports = ({ config: defaultConfig }) => {
  // Extend defaultConfig as you need.

  // Sass loader:
  defaultConfig.module.rules.push({
    test: /\.scss$/,
    loaders: ['style-loader', 'css-loader', 'sass-loader'],
    include: [path.resolve(__dirname, '../src'), path.resolve(__dirname)],
  });
  defaultConfig.resolve.extensions.push('.scss');

  // Typescript loader:
  defaultConfig.module.rules.push({
    test: /\.(ts|tsx)$/,
    use: [
      { loader: require.resolve('ts-loader') },
      { loader: require.resolve('react-docgen-typescript-loader') },
    ],
  });
  defaultConfig.resolve.extensions.push('.ts', '.tsx');

  // Resolve baseUrl:
  if (!defaultConfig.resolve.plugins) defaultConfig.resolve.plugins = [];
  defaultConfig.resolve.plugins.push(
    new TsconfigPathsPlugin({
      configFile: './tsconfig.json',
      baseUrl: 'src',
    }),
  );

  return defaultConfig;
};
```

</details>

<details><summary>Example of component with no Prop Table</summary>

```tsx
import React, { forwardRef } from 'react';

export interface TestButtonProps {
  /**
   * Some input prop.
   * @default: "Default value"
   */
  someProp?: string;
  /**
   * Some onClick handler prop.
   */
  onClick?: () => void;
}

export const TestButton = forwardRef<HTMLButtonElement, TestButtonProps>(
  ({ someProp = 'Default value', onClick }, ref) => {
    return (
      <button onClick={onClick} ref={ref}>{someProp}</button>
    );
  },
);
```

</details>

And then `addDecorator(withInfo);` in `.storybook/config.ts` as the very first `addDecorator`

**Comment by shilman** [comment]
@liamross No, there may have been some regressions in 5.0 but no material changes in `addon-info` specifically AFAIK. We'll be replacing it with a superior alternative very soon, so I'll be looking at this case as I work on that (and will patch `addon-info` if it's easy while I'm at it)

**Comment by shilman** [comment]
Addon-docs is in alpha now and is intended to replace addon-info. Please give it a try and see whether it solves this issue: https://docs.google.com/document/d/1un6YX7xDKEKl5-MVb-egnOYN8dynb5Hf7mq0hipk8JE/edit?usp=sharing

**Comment by liamross** [comment]
It seems to have resolved itself actually!
