### ISSUE TITLE
Remove hoist-non-react-statics as soon as react-redux works without an explicit dependency

### ISSUE THREAD

**Issue by kroeder** [storybookjs/storybook#6349]
I needed to add hoist-non-react-statics in as dependency in `addon-a11y`, (https://github.com/storybooks/storybook/pull/6348#issuecomment-478246983) otherwise the build runs into the following error

`../../node_modules/@types/react-redux/index.d.ts(103,79): error TS2694: Namespace '"/tmp/storybook/node_modules/hoist-non-react-statics/index"' has no exported member 'NonReactStatics'.`

This dependency needs to be removed as soon as `react-redux` works again without explicitly rely on `hoist-non-react-statics`

**Comment by mbpreble** [comment]
This appears fixed by a change to `@types/react-redux`, which added this explicit dependency: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/33690

The 'build' target of `yarn bootstrap` still succeeds with the explicit dependency removed, opened PR #8310 to remove it.

**Comment by shilman** [comment]
Yo-ho-ho!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-alpha.13 containing PR #8310 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
