### ISSUE TITLE
Vue component as a function won't load without registering

### ISSUE THREAD

**Issue by tomdohnal** [storybookjs/storybook#6357]
I tried to setup storybook for Vue according to the docs. 

However, trying to render the component like this :arrow_down: 
```
storiesOf('Button', module)
  .add('with text', () => '<my-button>with text</my-button>')
```
...didn't work out.

I had to manually register like this :arrow_down: 
```
Vue.component('my-button', MyButton)
```

Is this the expected behavior or not? In the docs there is no such a thing as registering the component so it is kind of confusing to me. I'll be happy to update the docs if the problem is not on my side.

**Comment by shilman** [comment]
cc @backbone87

**Comment by backbone87** [comment]
yes this is expected behavior. nothing is done automagically in regards to component registration. so you need to make sure the component is available just like when you do normal components. the `() => string` overload is just a shortcut for `() => ({ template: string })` so this component only knows about globally registered components.

**Comment by tomdohnal** [comment]
Shall I then make a PR to the docs? And include this `Vue.component('my-button', MyButton)` in the example usage?

**Comment by backbone87** [comment]
ofc, go ahead

**Comment by elevatebart** [comment]
Oh I might dig into this. Let me get an env ready.

**Comment by elevatebart** [comment]
Hey @tomdohnal 
Did you know that the function expects to return ...

a Vue template OR a full vue component?

```js
import Button from './Button.vue'

storiesOf('Button', module)
  .add('with text', () => ({
          components: { MyButton: Button},
          template: '<my-button>with text</my-button>'
  })
```

You can then register and test your components locally without having to globally register them.

**Comment by elevatebart** [comment]
Or you can even go wilder and use JSX. Note that the h parameter is important.

```jsx
import Button from './Button.vue'

storiesOf('Button', module)
  .add('with text', () => ({
          render: h => <Button>hello</Button>,
  })
```
