### ISSUE TITLE
Storybook .eslintrc

### ISSUE THREAD

**Issue by flav0061** [storybookjs/storybook#6363]
Hi,
i'm trying to setup a vue storybook with eslint, i believe the problem is related with storybook, because i'm reusing the same components in a different vue project without storybook and i'm getting linter errors in that project as expected. After reading all the documentation i found a possible solution where someone was using `eslint-loader` but i couldn't make it work. Is there someone with the same problem?

I'm trying to implement the `recommended` linter version

```
...
"@storybook/vue": "^5.0.6",
"@vue/cli-plugin-eslint": "^3.5.1",
"babel-eslint": "^10.0.1",
"babel-loader": "^8.0.4",
"eslint": "^5.15.2",
"eslint-plugin-vue": "^5.0.0",
...
```

```
module.exports = {
  root: true,
  env: {
    browser: true,
    node: true

  },
  'extends': [
    'plugin:vue/recommended',
    '@vue/standard'
  ],
  rules: {
    'no-console': 'off',
    'no-debugger': 'off'
  },
  parserOptions: {
    parser: 'babel-eslint'
  }
}
```

Example of linter error: 
**This returns error**
`    isItWorking: Boolean `

**This doesn't**
`    isItWorking: {
      type: Boolean,
      default: false
    }`

**Comment by flav0061** [comment]
Hi,
Any further development on this?
Thanks for the help

**Comment by flav0061** [comment]
Hi,
Any further development on this?
Thanks for the help

**Comment by shilman** [comment]
I recommend using full-control mode:

https://storybook.js.org/docs/configurations/custom-webpack-config/#full-control-mode

Then running storybook with the `--debug-webpack` CLI flag
