### ISSUE TITLE
Improve performance for larger storybooks

### ISSUE THREAD

**Issue by trevordmiller** [storybookjs/storybook#6391]
First off, thanks for such a fantastic tool! Our company loves storybook and uses it in hundreds of projects.

**Is your feature request related to a problem? Please describe.**

Building a storybook with many stories currently leads to webpack performance warnings:

"asset size limit: The following asset(s) exceed the recommended size limit (244 KiB)"

![image](https://user-images.githubusercontent.com/5497885/55432375-f86a3c80-554f-11e9-9e6a-d0a46b2fe3e6.png)

**Describe the solution you'd like**

It would be great if storybook could implement the code splitting recommendations from the webpack team as shown in the error message attached below; under the hood, so all storybook users with default setups could upgrade and benefit from the performance improvements for "free" without extra config.

**Describe alternatives you've considered**

We have considered extending the default webpack config or using "full control" mode, but would prefer not to "eject" from the default storybook setup. We have also considered breaking up our component library but all the components work together well and it doesn't make sense to break them up from a consuming developer experience.

**Are you able to assist bring the feature to reality?**

I love contributing to open source! But probably don't have time for this currently unless someone can provide a simple implementation.

**Additional context**

Using default setup (we are not extending or using "full control" of the default webpack setup) of  `@storybook/react": "^5.0.3"`.

**Comment by trevordmiller** [comment]
Our organization uses storybook for hundreds of projects and we see this performance warning on many of them.

**Comment by trevordmiller** [comment]
@shilman I noticed you removed the inactive label - is this something that the storybook team plans to address? If this is an isolated problem with our organization, I understand and we can close this issue and try to improve things on our end. But it seems to me with how often we are seeing this warning across the many many storybooks we maintain that perhaps it is a problem for many other teams as well? Would it be possible to code split by default or something, per the link in the web pack warning?

**Comment by shilman** [comment]
@trevordmiller I think this is happening for most storybook users. Nobody is working on it right now, but I don't want performance issues to go stale and get swept under the rug so I "reactivated" it. If anybody wants to give it a go, they are welcome to. Hope at some point we can do a perf-oriented release and tackle this and a bunch of other related issues...

**Comment by ndelangen** [comment]
This related to #6806 

With the current `config.js` is real hard to enable code-splitting in an automated fashion.

**Comment by johnhunter** [comment]
We have the same issue for a different reason. Our Storybook is served from AWS lambda. We recently added IE11 support for our components in Storybook and the additional babel transpilation / polyfilling has pushed the vendor~main over the  lambda maximum file size.

**Comment by shilman** [comment]
@johnhunter We'll do a perf sprint at some point soon and hopefully can get the bundle size down. In the meantime ... that sucks! @ndelangen any thoughts on options here?

**Comment by johnhunter** [comment]
Thanks @shilman, we're already appending to the Storybook webpack.config so its pretty straightforward to resolve using [webpack-merge](https://github.com/survivejs/webpack-merge). The relevant parts of our webpack.config.js look like this:
```
const webpack = require('webpack');
const merge = require('webpack-merge');


const maxAssetSize = 1024 * 1024;

module.exports =  async ({ config, mode }) => {
  return merge(config, {
    //...

    optimization: {
      splitChunks: {
        chunks: 'all',
        minSize: 30 * 1024,
        maxSize: maxAssetSize,
      }
    },
    performance: {
      maxAssetSize: maxAssetSize
    }
  });
};
```
This can produce quite a few bundles on larger projects. If the concern is improve build speed there are a few [splitChunk settings](https://webpack.js.org/plugins/split-chunks-plugin/) you can play with.

**Comment by kkomelin** [comment]
For those who's in search of how to adjust Storybook webpack config, see [Custom Webpack Config](https://storybook.js.org/docs/configurations/custom-webpack-config/) section of the Storybook docs.

**Comment by EvanCarroll** [comment]
Why is this closed, I'm still getting this error..

**Comment by shilman** [comment]
@EvanCarroll have you tried `storyStoreV7` in 6.4? https://storybook.js.org/blog/storybook-on-demand-architecture/

**Comment by yl-endress** [comment]
Hey guys,
in 2025 i still run into the same issue. I have a solution for my angular environment, which should also work in other frameworks:
https://stackoverflow.com/a/79688516/15121712
