### ISSUE TITLE
Custom addon not included in bundle after running build-storybook

### ISSUE THREAD

**Issue by Cheebang** [storybookjs/storybook#6413]
### Bug or support request summary

My custom addon is not being included in the JS bundle after running `build-storybook -c .storybook`. No errors are thrown when running build-storybook. However, I am seeing the addon on the page and in the Javascript when I run `start-storybook`.

The result of this is that my custom addon is not displayed in my static storybook build.

### Steps to reproduce

I am using typescript in the project and have a custom webpack config for storybook.
```
module.exports = ({ config }) => {
  config.module.rules.push({
    test: /\.(ts|tsx)$/,
    loader: require.resolve("babel-loader"),
    options: {
      presets: [["react-app", { flow: false, typescript: true }]]
    }
  });
  config.resolve.extensions.push(".ts", ".tsx");
  return config;
};
```

I'm using a babel.config.js and Babel 7

```
module.exports = {
  presets: [
    [
      '@babel/env',
      {
        targets: {
          node: '8.9'
        }
      }
    ],
    '@babel/typescript'
  ]
};

```

My addon.js file is located in the .storybook directory and contains:

```
import '@storybook/addon-knobs/register';
import './json-addon/register';
```
I am able to attach the register.js if required. It is working locally for me if I run `start-storybook`.

This is how I'm registering the addon in register.js
```
addons.register(ADDON_ID, api => {
  const title = "JSON Content";
  const render = ({ active }) => (
    <JsonPanel
      key={1}
      api={api}
      channel={addons.getChannel()}
      active={active}
    />
  );
  addons.add(PANEL_ID, { type: types.PANEL, title, render });
});
```

### Please specify which version of Storybook and optionally any affected addons that you're running

 - "@babel/core": "7.1.2",
 - "@storybook/addon-actions": "^5.0.6",
 - "@storybook/addon-info": "^5.0.6",
 - "@storybook/addon-knobs": "^5.0.6",
 - "@storybook/addon-links": "^5.0.6",
 - "@storybook/addons": "^5.0.6",
 - "@storybook/cli": "^5.0.6",
 - "@storybook/components": "^5.0.6",
 - "@storybook/react": "^5.0.6",
 - "@storybook/theming": "^5.0.6",

### Affected platforms 

Running on macOS Mojave

### Where to start

I followed the docs on these pages for my configuration:
https://storybook.js.org/docs/configurations/typescript-config/
https://storybook.js.org/docs/addons/writing-addons/

### Acceptance criteria

Successful build-storybook run where the JS bundle contains the addon code so it can be deployed as static files

**Comment by shilman** [comment]
You're also using `addon-knobs`. Is that bundling properly?

**Comment by Cheebang** [comment]
Yes knobs is bundling correctly. When I load up the static storybook built with `build-storybook` I see the knobs and they are functioning correctly. However the custom addon is missing. I tried commenting out knobs in the addons.js file and building and then knobs disappeared.
So my theory is that it's using addons.js but maybe silently failing when importing the custom addon's register.js?

**Comment by shilman** [comment]
@Cheebang that's a good theory. I think there have been some issues about webpack errors getting swallowed ... so this could be related to that? Just did a quick search but couldn't find the issue ☹️

**Comment by Cheebang** [comment]
OK I have an update: I removed the import to the custom addon and just pasted the contents of register.js into addons.js and it has appeared in the bundle :)
So it would seem it is the `import './json-addon/register';` that is silently failing

**Comment by shilman** [comment]
@Cheebang Out of curiosity I did static builds with two separate projects that use custom addons and didn't have problems with either. Both were running `next` code (5.1.x) and neither were typescript. FYI.

**Comment by Cheebang** [comment]
Thanks that is good to know. What was the structure of the project? I'm curious to see where the register.js of the custom addon was sitting

**Comment by shilman** [comment]
Register.js was just in my .storybook folder

**Comment by Kadrei** [comment]
Having the same issue with a local plugin in a subfolder of the `.storybook`-folder not showing up when I execute `build-storybook` - `start-storybook` works fine.

**Comment by shilman** [comment]
From one of our discord users:

> I had  the same issue [...] but managed to resolve it. Found out that it as due to webpack treeshaking my code away. I just had to add a sideEffect reference pointing to my custom addon and then it worked.

**Comment by Kadrei** [comment]
I do not like the need for adding a webpack config to storybook just for that but if it solves the problem.

What about adding a glob pattern targeting the `.storybook` folder to the `sideEffect` default webpack config? I am unsure how much else this would affect but might be a possible solution here.

**Comment by StJohn3D** [comment]
This issue is definitely still happening in version 5.2.6.

Storybook React

My addon at
.storybook/addons/register.js is being stripped from the static build.

**Comment by StJohn3D** [comment]
I had `"sideEffects": false` in my package jason because I'm writing a component library.
Changing it to 
```json
"sideEffects": [
    ".storybook/addons/my-addon/register.js"
  ],
```

Fixed the issue

**Comment by maraisr** [comment]
I don't think putting things in this package.json file for consumers to also see is a good idea. Have we solved this?
