### ISSUE TITLE
"StyledComponent" Component - No propTypes defined!

### ISSUE THREAD

**Issue by rwieruch** [storybookjs/storybook#6417]
After upgrading from Storybook 4.x.x to 5.0.6., I am not able anymore to see the assigned propTypes for Styled Components in Storybook anymore.

That's what I see in Storybook:

___

![Screen Shot 2019-04-04 at 11 56 05](https://user-images.githubusercontent.com/2479967/55547048-c7654580-56d0-11e9-9116-a820436a3015.png)

___

That's what I have coded:

```
const TabBar = styled.div`
  display: flex;
  flex-direction: column;
`;

TabBar.displayName = 'TabBar';

TabBar.propTypes = {
  children: PropTypes.arrayOf(
    PropTypes.shape({
      type: PropTypes.oneOf([TabBar.ContentTab]),
    }),
  ).isRequired,
};
```

And I would expect to see the children prop types instead.

Note: It works for other components which haven't defined with styled components though.

**Comment by shilman** [comment]
So this worked as is in 4.x and then just broke in 5.0? Are you using a custom webpack config?

**Comment by rwieruch** [comment]
I checked again and it worked with 4.1.11. @shilman That's my custom webpack config:

```
module.exports = ({ config }) => {
  config.module.rules.push(
    {
      test: /\.(js|jsx)$/,
      exclude: /node_modules/,
      use: ['babel-loader'],
    },
    {
      test: /\.(woff(2)?|ttf|eot)(\?v=\d+\.\d+\.\d+)?$/,
      use: ['file-loader'],
    },
    {
      test: /stories\.(js|jsx)?$/,
      loaders: [require.resolve('@storybook/addon-storysource/loader')],
      enforce: 'pre',
    },
  );

  return config;
};

```

**Comment by shilman** [comment]
Thanks for confirming @rwieruch. I'm working on a replacement for addon-info, and will keep my eyes out for this. I'll also fix it in addon-info assuming that it's an easy fix.

**Comment by rwieruch** [comment]
Perfect! Thank you @shilman 👍

**Comment by liamross** [comment]
@shilman  This may also be related to the bug I logged for the missing prop table in TypeScript: https://github.com/storybooks/storybook/issues/6345

**Comment by oknoorap** [comment]
it's fixed already and published? @shilman

**Comment by shilman** [comment]
@oknoorap Nope, will comment here when it is. If anybody else wants to take a crack at it, they're more than welcome!

**Comment by cyrus-za** [comment]
Please let me know when this gets fixed. Quite annoying to see all these unknown styled components
![image](https://user-images.githubusercontent.com/1845861/59565084-3243dd00-9081-11e9-9308-bd9ef7ef3ee1.png)

Not using a custom webpack. Using CRA with typescript

**Comment by rwieruch** [comment]
Not sure how to keep issues open when the stale bot comes along 😄

**Comment by shilman** [comment]
FYI you might want to check out Storybook Docs which is designed to replace addon-info.

Here's the project description: https://medium.com/storybookjs/storybook-docs-sneak-peak-5be78445094a
And here's the guide to technical preview alpha you can use today: https://docs.google.com/document/d/1un6YX7xDKEKl5-MVb-egnOYN8dynb5Hf7mq0hipk8JE/edit?usp=sharing

**Comment by rwieruch** [comment]
Thanks for sharing! Looks super promising and I will try it this week 👍

**Comment by shilman** [comment]
@rwieruch Great! Github issues welcome + we also have a discussion going in the `#docs-mode` channel in our discord around design feedback & support https://discord.gg/UUt2PJb
