### ISSUE TITLE
Toggle theme

### ISSUE THREAD

**Issue by rezaabedian** [storybookjs/storybook#6418]
**Is your feature request related to a problem? Please describe.**
Our component library inherits it's styling from a class that is applied to the root <html>  tag. 

Example:
```
<html class="dark">
some stories 
</html>
```

And similar for light. 

So I can get so far by including this html in the preview-head.html and then importing in our stylesheet. 

In parallel I have also developed a storybook theme that is defined in config.js that looks like our dark theme. 

But now I need to be able to toggle the Storybook theme, in sync with switching the class name on the html tag in the preview-head.html

**Describe the solution you'd like**

It would be great if there was a storybook level theme toggle, then when toggled would each story know the current theme value. 

**Describe alternatives you've considered**
Thinking of a add-on that shows a UI that when toggled goes and modifies the markup in the preview-head.html

**Are you able to assist bring the feature to reality?**
yes

**Comment by shilman** [comment]
Have you taken a look at this? https://github.com/leoyli/addon-contexts

cc @leoyli

**Comment by leoyli** [comment]
Would like to know more about your framework of use.  I'm currently pushing my addon out of React to Vue. So if you are in other framework, it may not be so useful at the moment.  But I guess we can work together, or at least I can investigate or prioritize something for you. 💪

**Comment by kevinSuttle** [comment]
I was wondering why using `context.theme` wasn't the default in addon-backgrounds...

**Comment by shilman** [comment]
@kevinSuttle That would be a nice feature for `addon-backgrounds` 👍

**Comment by leoyli** [comment]
@kevinSuttle, @shilman: where this `context.theme` came from?! Is the storybook theming or the application theming?!  I think the later is a bit harder for `addon-backgrounds` to get processed automatically...?!  In our use case, we have theming object came from `material-UI` and we just have a simple file to glue the theming definition with `addon-backgrounds` to remain 1 source of the truth. So I don't see there are something to do on `addon-backgrounds` though.

**Comment by rezaabedian** [comment]
@leoyli we are using Angular and React. I'll investigate `addon-contexts` but I'm guessing that because our theme is being driven by a global scss and not state, context or props, the model in `addon-contexts`isn't just going to do it place.

**Comment by leoyli** [comment]
@rezaabedian, Angular is not supported in the addon yet (will do this). But I believe you can still use this addon for React. If you just want to dynamically inject `className`, you can specify like this:

```js
  {
    icon: 'box',
    title: 'CSS Themes',
    components: ['div'],
    params: [
      { name: 'Dark', props: { className: 'dark' } },
      { name: 'Light', props: { className: 'light' } }],
  }
```

Think this addon is just like an agent who knows how to communicate between Storybook manager and your component preview.

**Comment by dallas** [comment]
+1 to being able to toggle between various Storybook themes. Our UI suite has to accommodate light and dark versions of our components and so far I’ve built a Grommet (styled-components) level toggle as a global decorator but it would be splendid if a similar toggle existed on a higher level that switched the entire Storybook UI theme and simply notified my decorator component in some way so that I could load my component library specific theme for the same color space (light or dark).

**Comment by dallas** [comment]
Something that would let me toggle between light and dark like this:

<img width="1920" alt="Screen Shot 2019-04-06 at 21 08 10" src="https://user-images.githubusercontent.com/5059/55678523-30ef7a80-58b0-11e9-913e-a37699c7db2a.png">
<img width="1920" alt="Screen Shot 2019-04-06 at 21 07 38" src="https://user-images.githubusercontent.com/5059/55678525-38168880-58b0-11e9-9ad2-50b53ecfb40a.png">

**Comment by leoyli** [comment]
@dallas, as mentioned in this thread, please take a look on [`addon-contexts`](https://github.com/leoyli/addon-contexts), this allows you to wrap your stories globally or locally with the ability to control the injected component props from storybook toolbar.

**Comment by dallas** [comment]
Hi, @leoyli, thanks for re-sharing that. I’ve taken a look at the `addon-contexts` add-on, and I’ve found it quite useful already for simplifying my theme wrapper & toggling between my own defined “light” and “dark” themes for our UI library (built on Grommet), but I’m afraid I still don’t understand how it can be used to toggle the UI theme of Storybook itself. Could you provide some guidance or an example for this?

**Comment by kevinSuttle** [comment]
That's great @leoyli. Thanks!

**Comment by leoyli** [comment]
@dallas, Oh my bad, it's actually more than just the story preview but the theme of the manager app too...  then `addon-contexts` can not do such thing although may have a workaround on top of it.

In `addon-contexts` v1.1.0, internally, after user change the addon state from toolbar menu, the addon fires an event called `addon-contexts/UPDATE_PREVIEW` with the information about the current user selected contexts. If you wish to use this addon to manage your story contexts while also want the manager app to get reacted, you can subscribe this event and change the app theme accordingly (some overhead on how SB works internally, though).

**Comment by dallas** [comment]
Okay, cool. Thanks for the info, @leoyli!

**Comment by shilman** [comment]
Have you taken a look at this one? https://github.com/hipstersmoothie/storybook-dark-mode

**Comment by dallas** [comment]
That looks like exactly what I want, @shilman! Thank you so much for sharing it!

**Comment by dfagan2** [comment]
> Angular is not supported in the addon yet (will do this)

@leoyli - any rough ETA on Angular support for the `contexts` addon?
