### ISSUE TITLE
Move 'Show Info' button in info addon

### ISSUE THREAD

**Issue by Glazy** [storybookjs/storybook#6420]
**Is your feature request related to a problem? Please describe.**

When using `@storybook/addon-info` the 'Show Info' button at the top right of the component view area overlays the rendered component. This was a problem when we had a full-width component that had an icon on the right hand side that was being covered by the button.

**Describe the solution you'd like**

It would be nice to make use of Storybooks built-in top bar area. Take a look at the screenshot below 👇

<img width="727" alt="Screen Shot 2019-04-04 at 15 31 58" src="https://user-images.githubusercontent.com/8593744/55564091-115d2400-56ef-11e9-8163-879bd6ab655d.png">

**Describe alternatives you've considered**

There could potentially be a way to toggle this 'Show Info' button but I think the solution I've suggested above is the better fix.

**Are you able to assist bring the feature to reality?**

Yes

**Comment by shilman** [comment]
Cool idea! I think this would be a nice improvement for `addon-info` 👍

**Comment by Armanio** [comment]
Hey @Glazy! I like it, it will decide any problem with 'info' toggle.
Are you have progress? I can help you? Let me know.

**Comment by joeycozza** [comment]
I'd also like to throw in the idea of a flag to put addon-info as a Panel on the bottom.

**Comment by techieshark** [comment]
@joeycozza I think I've seen the idea of changing addon-info in related manner mentioned in other issues (assuming I'm understanding the proposals correctly):

https://github.com/storybooks/storybook/issues/1147#issuecomment-475810179
https://github.com/storybooks/storybook/issues/6049#issuecomment-472175592

cc @shilman

**Comment by shilman** [comment]
FYI just wrapping up the technical preview of `addon-docs` which aims to replace `addon-info` and addresses these issues: https://medium.com/storybookjs/storybook-docs-sneak-peak-5be78445094a

**Comment by jamime** [comment]
PR for `addon-docs` https://github.com/storybookjs/storybook/issues/7101

**Comment by shilman** [comment]
@jamime FYI it's been out as 5.2.0-alpha.x for the past month. Guide: https://docs.google.com/document/d/1un6YX7xDKEKl5-MVb-egnOYN8dynb5Hf7mq0hipk8JE/edit?usp=sharing
