### ISSUE TITLE
Is there a way to close storybook and return to the main app

### ISSUE THREAD

**Issue by acollazomayer** [storybookjs/storybook#6426]
I have a button that opens storybook within the app. However I then can not return to the original app. Is there a way I can do this

**Comment by shilman** [comment]
Need more context. Is this for React native?

**Comment by acollazomayer** [comment]
Yes this is for react native @shilman. Thanks for the response. Sorry if I was not more specific

**Comment by shilman** [comment]
@Gongreg @benoitdion what's the best practice on this?

**Comment by benoitdion** [comment]
For the time being, you'll have to manage it within your app and the answer kinda depends on your set up and what navigation stack you use. Usually, you should be able to treat it like any other screen in the app.

With 5.1 we'd like to add support for a storybook switcher that makes it really easy to switch between the app and storybook.

**Comment by acollazomayer** [comment]
@benoitdion Thanks you. Yeah I have a screen but dont see any button that I can trigger a pop, I am using react-native-n avigation

**Comment by Gongreg** [comment]
@benoitdion, @shilman, I don't think we can do anything here. There is too much to assume how storybook is going to be used. Expo, React Native Navigation, other non native navigations, etc.

**Comment by benoitdion** [comment]
I've got some ideas for how to do this we can chat about

**Comment by Gongreg** [comment]
@benoitdion, feel free to DM me on Discord :)
