### ISSUE TITLE
Vue stories don't work with mixins

### ISSUE THREAD

**Issue by Jivanvl** [storybookjs/storybook#6427]
**Describe the bug**

**To Reproduce**
1. Go to http://jivl-mixin-storybook-bug.162.243.131.170.nip.io/?path=/story/charts-stacked-column-chart--with-toolbox
2. Click on `Show Toolbox`
3. See error

**Expected behavior**
`Show Toolbox` should show a toolbox on top of the chart, that property comes from a mixin, it seems to me that the mixin prevents the property from receiving the values correctly, see attached screenshot

**Screenshots**
<img width="1097" alt="Screen Shot 2019-04-04 at 4 04 11 PM" src="https://user-images.githubusercontent.com/1641877/55594299-4e7be300-56fc-11e9-93a5-b3e7cfb500be.png">

**Code snippets**
https://gitlab.com/gitlab-org/gitlab-ui/merge_requests/231

**System:**
 - OS: macOS 
 - Device: Macbook Pro 15 inch 2018
 - Browser: chrome, firefox, safari
 - Framework: vue
 - Addons: storybook/addon-knobs@5.0.3
 - Version: 5.0.3

**Comment by backbone87** [comment]
knobs values must be passed in as prop default values. (this was a change done somewhere in sb 4.x, but not very well documented):
```js
add('My Story', () => ({
  props: {
    showToolbar: { default: boolean('Show Toolbar', false) }
  }
}))
```
