### ISSUE TITLE
Change sidebar icon colors

### ISSUE THREAD

**Issue by MaxMcKinney** [storybookjs/storybook#6436]
Seeing as the icons are SVGs we should have theme access to changing the icon colors. Right now I don't see any way that exposes them for us to modify.

**Comment by mattbeaudry** [comment]
Taking a look at this...

**Comment by mattbeaudry** [comment]
The ability to simply hide the icons in the sidebar would also be good

**Comment by mattbeaudry** [comment]
Gonna try adding 2 new theme variables, `SidebarIconsHide` and `SidebarIconsColor`

**Comment by mattbeaudry** [comment]
noticing that a class was recently added to the sidebar icons... `.sidebar-svg-icon` which could be used to hide or change icon color using CSS in the manager-head.html file. but seems like adding some theme variables might be cleaner

**Comment by mattbeaudry** [comment]
seems like CSS classes were added 6 days ago...
https://github.com/storybooks/storybook/commit/f46a4554e86e92ca388dffbee2f3fe9d9e66f284
so not sure theme variables are needed for my scenario if I can style with CSS.

**Comment by MaxMcKinney** [comment]
@mattbeaudry That seems useful for now, but themeable variables would prevent any issues with a classname changing in the future. Especially because classnames aren't restricted behind any semantic versioning.

**Comment by aaronmw** [comment]
@MaxMcKinney You said this seemed useful for now, but I'm having issues making any use of these selectors... I've got this in my storybook.css file:

`svg.sidebar-svg-icon path {
    fill: #717e90 !important;
}`

But they're still their default teal color... What'd you do differently??
