### ISSUE TITLE
Storybook does not work with Expo

### ISSUE THREAD

**Issue by kristremblay** [storybookjs/storybook#6445]
**Describe the bug**
When trying to install Storybook with the most recent release of Expo, the process fails at `installing dependencies` with the error `No matching version found for @storybook/react-native@^5.0.6`.

**To Reproduce**
1. Create new project with `expo init ProjectName`
2. cd into the directory
3. Run `getstorybook`

**Expected behavior**
Storybook would install properly and I would be a happy boy.

**System:**
 - OS: Windows 10
 - Node Version: 11.4.0
 - NPM Version: 6.4.1
 - Framework: React Native (Expo)

Log dump
```
245 verbose stack @storybook/react-native: No matching version found for @storybook/react-native@^5.0.6
245 verbose stack     at pickManifest (C:\Users\krist\AppData\Roaming\nvm\v11.4.0\node_modules\npm\node_modules\npm-pick-manifest\index.js:65:11)
245 verbose stack     at fetchPackument.then.packument (C:\Users\krist\AppData\Roaming\nvm\v11.4.0\node_modules\npm\node_modules\pacote\lib\fetchers\registry\manifest.js:52:18)
245 verbose stack     at tryCatcher (C:\Users\krist\AppData\Roaming\nvm\v11.4.0\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
245 verbose stack     at Promise._settlePromiseFromHandler (C:\Users\krist\AppData\Roaming\nvm\v11.4.0\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
245 verbose stack     at Promise._settlePromise (C:\Users\krist\AppData\Roaming\nvm\v11.4.0\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
245 verbose stack     at Promise._settlePromise0 (C:\Users\krist\AppData\Roaming\nvm\v11.4.0\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
245 verbose stack     at Promise._settlePromises (C:\Users\krist\AppData\Roaming\nvm\v11.4.0\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
245 verbose stack     at Async._drainQueue (C:\Users\krist\AppData\Roaming\nvm\v11.4.0\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
245 verbose stack     at Async._drainQueues (C:\Users\krist\AppData\Roaming\nvm\v11.4.0\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
245 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\krist\AppData\Roaming\nvm\v11.4.0\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
245 verbose stack     at processImmediate (timers.js:632:19)
```

**Comment by kristremblay** [comment]
Update:

I went through the guide on the site again and the best I am able to do is get storybook running in the browser. However it is not picking up any of the stories.

As for my app, since I replaced the app entry point with `./storybook` it only shows text that says to visit the browser on port 7007 (which, again, shows empty storyboard)

**Comment by kristremblay** [comment]
Ok, so, I haven't tried installing it in an expo init'd project, but using crna I got it to work by doing the following:

1. run `npx -p @storybook/cli@next sb init`
2. Change APP_NAME to whatever the `appKey` is.  *Note* This property is oddly missing from app.json so you need to add it.  The instructions in storybook's index file say that you don't need to change it if you are using expo...this seems to be incorrect.

Now, using npm run storybook does not load stories, but at least it seems to work on my mobile device.

This whole thing is really frustrating.

**Comment by kristremblay** [comment]
![image](https://user-images.githubusercontent.com/7587183/55678944-0f9a8880-58c8-11e9-917a-2df712a6d449.png)

**Comment by shilman** [comment]
First part of this issue is duplicate to https://github.com/storybooks/storybook/issues/5893

Second part may need some investigation cc @benoitdion

**Comment by alechp** [comment]
> NOTE: This doesn't address kristremblay's concern re: latest version interoperability. I'm simply sharing this for others that are stuck and just want storybook to work (without waiting for storybook/expo-cli latest-version interoperability)

**Non-ideal quick fix**: when installing storybook, choose v4.1.18. 
> Got storybook v4.1.18 working with latest version of expo init.

1. $ `expo init projectName`
2. $ `cd projectName`
3. $ `npx -p @storybook/cli sb init`
4. $ `yarn install`
5. $> choose version 4.1.18
6. $ `yarn start`

(Also at some point during the Storybook install you have to choose your output. I selected **REACT_NATIVE**)


---

![Screen Shot 2019-05-03 at 11 29 39 AM](https://user-images.githubusercontent.com/3058939/57157891-c6d6d200-6d96-11e9-900c-366b394d361f.png)

![Screen Shot 2019-05-03 at 11 28 49 AM](https://user-images.githubusercontent.com/3058939/57157892-c6d6d200-6d96-11e9-95e6-c1e4d7265e0c.png)

**Comment by shilman** [comment]
@kristremblay please take a look at the migration instruction for 5.1: https://github.com/storybooks/storybook/blob/next/MIGRATION.md#react-native-server

**Comment by alechp** [comment]
@kristremblay In case you didn't have time to finalize yet, I put together a finished repo as a reference. Great catch on the appKey btw. The "don't need to do this if you're using expo" threw me as well. Glad you caught it. 

[react-native-expo-storybook-v5](https://github.com/servexyz/react-native-expo-storybook-v5)

@shilman I noticed that I was running into compilation issues with `addons`. Ended up just removing it (obviously not ideal, but I assume this is specific to react-native-server ?)

**Comment by shilman** [comment]
Thanks @alechp . What issues were you having? I know there were some addon-related issues in RN 5.1 but I'm not sure if they're documented or tracked, so if you let me know it would help us with the release. Also, are you on the latest alpha? 🙏

**Comment by alechp** [comment]
> Thanks @alechp . What issues were you having? I know there were some addon-related issues in RN 5.1 but I'm not sure if they're documented or tracked, so if you let me know it would help us with the release. Also, are you on the latest alpha? 🙏

I received this compile time error:
```
ERROR in ./storybook/addons.js Module build failed (from ./node_modules/babel-loader/lib/index.js): Error: Plugin/Preset files are not allowed to export objects, only function
```

Here's the package:
https://github.com/servexyz/react-native-expo-storybook-v5/blob/master/package.json

In terms of https://www.npmjs.com/package/@storybook/cli I chose whatever the latest version listed was... I recall it was a `.3`. Looking at the package version releases, I believe it was `5.2.0-alpha.3` 

UPDATE (11:19AM PST): Confirmed that the version I installed from was `5.2.0-alpha.3`:

<img width="946" alt="Screen Shot 2019-05-07 at 11 19 30 AM" src="https://user-images.githubusercontent.com/3058939/57323156-17616e80-70ba-11e9-934f-8b40be9f6306.png">

Notice that you tagged my previous repo comment to the 5.1.0 milestone. Should it be tagged to 5.2.0 instead?

**Comment by alechp** [comment]
@shilman Update: Here's the original error (returns when I add `addons.js` back to `storybook/` directory

<img width="838" alt="Screen Shot 2019-05-07 at 11 11 27 AM" src="https://user-images.githubusercontent.com/3058939/57322736-1bd95780-70b9-11e9-8418-b2d232e6f493.png">

You can recreate this by 
1. cloning the repo I posted earlier ([react-native-expo-storybook-v5](https://github.com/servexyz/react-native-expo-storybook-v5)) 
2. $ `touch storybook/addons.js`
3. copy this to clipboard: 
```
import '@storybook/addon-actions/register';
import '@storybook/addon-knobs/register';
```
4. $ `pbpaste > storybook/addons.js`

**Comment by alechp** [comment]
> @alechp Please use the latest 5.1.0 version. The 5.2.0 version may be messed up -- it's a long story.

When I try to reinitialize with v5.2.0, `start-storybook` isn't found. What am I doing wrong?

Here's a PDF containing screenshots of my step-by-step interaction: https://github.com/servexyz/react-native-expo-storybook-v5/blob/reverting-to-v510a40/docs/Storybook_version_downgrade.pdf

**Comment by alechp** [comment]
@shilman Current error with `v5.1.0-alpha.40`

<img width="1792" alt="Screen Shot 2019-05-08 at 2 32 31 PM" src="https://user-images.githubusercontent.com/3058939/57409838-29b4d880-719e-11e9-96d8-95fd48fd29a1.png">

**Comment by alechp** [comment]
@shilman got alpha 40 running. Current errors being thrown:

<img width="1680" alt="Screen Shot 2019-05-08 at 2 36 39 PM" src="https://user-images.githubusercontent.com/3058939/57410120-d2fbce80-719e-11e9-9c9d-fbda49a2b304.png">

**In Expo**
```
Unable to resolve "emotion-theming" from "node_modules/@storybook/react-native/dist/preview/index.js"
```

**Added context**

- Stories never load in browser
- Bundler never moves past 99%
- I've rmraf'd my node_modules directory a couple times to no avail


UPDATE:
If I add `emotion-theming` as a peer dependency (with yarn), now there's a new missing dependency: 
```
Unable to resolve "@emotion/core" from "node_modules/emotion-theming/dist/emotion-theming.browser.cjs.js"
```

I can keep adding missing modules, but obviously this isn't right.


UPDATE 2:
Got it working. Had issues when adding `emotion-theming` and `@emotion/core` as peer deps. Added them as dev deps and it seems to have resolved whatever linking issues I was running into before. Still not ideal to have to add; might be worth it to upgrade the migration guide to include these steps in the meantime (during the `babel-loader` install step).

<img width="1680" alt="Screen Shot 2019-05-08 at 2 55 48 PM" src="https://user-images.githubusercontent.com/3058939/57411117-7d74f100-71a1-11e9-8c0c-64001b04b160.png">


UPDATE 3:
On the topic of migration guide, you might want to add that the simulator (I'm doing all of my testing on iOS sim, haven't tried Android emu) needs to be running otherwise Storybook stories will not load.

**Comment by alechp** [comment]
@shilman Not sure if this is a bug of alpha40 or supposed to be a feature of Storybook:

Whenever I run `yarn install` it asks me to select the storybook version.

eg. I installed the Storysource addon (https://github.com/storybooks/storybook/tree/master/addons/storysource)

via `yarn add @storybook/addon-storysource --dev`

and was prompted to choose the install version again:

![Screen Shot 2019-05-09 at 11 46 27 AM](https://user-images.githubusercontent.com/3058939/57478676-68a36680-7250-11e9-90c2-ee6198e5d704.png)

It also seems to re-run if I run `yarn install` by itself (ie. even when I'm not adding a storybook-specific dependency). Is there anyway to disable this hook? It seems unnecessarily time consuming

**Comment by shilman** [comment]
@alechp Not sure what's going on there. @benoitdion have you seen this?

**Comment by benoitdion** [comment]
I haven't seen this. What does your `package.json` look like?

**Comment by alechp** [comment]
> I haven't seen this. What does your `package.json` look like?

@benoitdion 
Repo: https://github.com/servexyz/react-native-expo-storybook-v5
Package: https://github.com/servexyz/react-native-expo-storybook-v5/blob/master/package.json

**Comment by alechp** [comment]
@benoitdion @shilman Update: Also getting prompted to select Storybook version on `yarn remove`:

<img width="946" alt="Screen Shot 2019-05-10 at 2 21 48 PM" src="https://user-images.githubusercontent.com/3058939/57557455-11c08e80-732f-11e9-9c06-330c7bbda8d2.png">

**Comment by leesiongchan** [comment]
Consider using expo 33 with `expo start --web`, it works for me.

**Comment by TheWeeezel** [comment]
@alechp 
Using android I can't get any stories to show on the web. My package.json:

`"scripts": {
    "storybook": "start-storybook -p 7007"
  }, 
"dependencies": {
    "@expo/samples": "2.1.1",
    "core-js": "2",
    "expo": "^32.0.0",
    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
    "react-native-elements": "^1.0.0-beta7",
    "react-native-super-grid": "^3.0.3",
    "react-navigation": "3.0.9"
  },

  "devDependencies": {
    "@emotion/core": "^10.0.10",
    "@storybook/addon-actions": "^5.0.11",
    "@storybook/addon-links": "^5.0.11",
    "@storybook/addon-storysource": "^5.0.11",
    "@storybook/addons": "^5.0.11",
    "@storybook/react-native": "^5.0.11",
    "@storybook/react-native-server": "5.1.0-alpha.7",
    "babel-core": "^6.26.3",
    "babel-loader": "^8.0.5",
    "babel-preset-expo": "^5.0.0",
    "babel-runtime": "^6.26.0",
    "emotion-theming": "^10.0.10",
    "jest-expo": "^32.0.0",
    "prop-types": "^15.7.2",
    "react-dom": "16.5.0"
  },`

I used your workaround and got it to work on the android emulator from Android SDK and there the stories are shown but not on Web. I also get into this loop where I need to select the version every time I run yarn. I installed alpha 40. So far the states I have achieved are either infinite loading or no stories on the web.

**Comment by benoitdion** [comment]
@alechp @TheWeeezel did you try syncing all storybook related deps to the same version?

**Comment by TheWeeezel** [comment]
> @alechp @TheWeeezel did you try syncing all storybook related deps to the same version?

Sorry for my late answer. Yes i did. I figured i wait for Expo 33 to release. I tried so many versions but gave up.

**Comment by alechp** [comment]
@TheWeeezel I'm having similar issues

Android emu
<img width="1680" alt="Screen Shot 2019-06-26 at 9 32 43 AM" src="https://user-images.githubusercontent.com/3058939/60198042-8ffcc580-97f5-11e9-8f1e-4a0afdb2485b.png">

iOS sim
<img width="1680" alt="Screen Shot 2019-06-26 at 9 35 48 AM" src="https://user-images.githubusercontent.com/3058939/60198152-d05c4380-97f5-11e9-858b-d725fb275b59.png">

My hunch is that this has to do with the Android emu and not Storybook (or Expo). Admittedly getting this working on Android isn't top priority for me rn. Have you had any luck getting passed this on your end?

**Comment by Gongreg** [comment]
Hey, if android doesn’t work remember to run `adb reverse tcp:7007 tcp:7007` . Does that help @alechp?

@shilman this issue is really big and talking about 10 different issues, most of them are solved. Not sure what is left to fix here.

**Comment by alechp** [comment]
@Gongreg I agree re: issue being too big. More generic support thread than actual issue at this point. Worth closing IMO

**Comment by Gongreg** [comment]
Closing this issue. If you have any issues feel free to open a separate issue!

@alechp if you could notify here does the adb reverse command solve your issue.

**Comment by RobinLebhar** [comment]
Any news about this issue ? With expo 34 and Storybook 5 Story are loading forever on the left panel.

**Comment by gdedieu92** [comment]
in my case the think is that main file is different with expo and story book.

The left loading panel forever is because by default story book loads a part of de index.js in --web but the folders with examples of stories are only --ios and --android. So is tricky but you can make a "switch" and define what loader wants.

Example:

I made a switch navigator in my app. 
`
const switchNavigator = createSwitchNavigator(
    {
        UserLogged: DrawerLogged,
        UserNoLogged: DrawerNavigator,
        AuthLoadingScreen: AuthLoadingScreen,
        StoryBook: StoryBookLoader
    },
    {
        initialRouteName: 'StoryBook',
    }
);`

`import React from 'react';
import StorybookUIRoot from '../../../storybook';


const StoryBookLoader = ({ }) => <StorybookUIRoot />
export default StoryBookLoader;`

So when i want to work with StoryBook, i follow these steps:
expo start <platform>
read qr with my phone or emulator 
change initialRoute of my switch navigator to "StoryBook" 
And that's then all default config and docs in StoryBook docs.

Hope worth for someone :)

**Comment by i-oliva** [comment]
> Any news about this issue ? With expo 34 and Storybook 5 Story are loading forever on the left panel.

Having the same issue!
