### ISSUE TITLE
Using a custom .babelrc in create-react-app

### ISSUE THREAD

**Issue by ryan-ds** [storybookjs/storybook#6479]
**Describe the bug**
I am using `customize-cra` to add a specific babel plugin for development and I have also added a `.babelrc` in the `.storybook` folder which has the following:

```json
{
  "presets": ["react-app"],
  "plugins": ["@babel/plugin-proposal-optional-chaining"]
}
```
The issue is it doesn't read the babel config even though the terminal says:
![image](https://user-images.githubusercontent.com/38418557/55880828-25a59300-5bbf-11e9-8951-76a63864631b.png)

But in the end it shows the following issue:
![image](https://user-images.githubusercontent.com/38418557/55881054-95b41900-5bbf-11e9-9109-7d8f6b77681d.png)

**Expected behavior**
It should run the plugins and presets from the custom .babelrc file

**System:**
 - OS: MacOS
 - Device: Macbook
 - Browser: Chrome
 - Framework: React
 - Version: 
      `@storybook/react`: 5.0.6
      `react-scripts`: 2.1.8

**Comment by acnebs** [comment]
I am having the same issue.

Obviously the `.babelrc` in `.storybook` is completely overriding the CRA config, rather than extending it. Hypothetically, you could use the .babelrc's "extends" property, but I'm not sure where CRA's .babelrc is located (or if it even has one).

**Comment by shilman** [comment]
@mrmckeb I think the CRA babel heuristic is overriding the user's babelrc. Should we merge them instead?

**Comment by mrmckeb** [comment]
@shilman, I think it's not a good idea as then we allow people to potentially build a component that works in Storybook, but doesn't work in their actual application.

Can @ryan-ds and/or @acnebs provide insight into what you're trying to achieve here? What features do you want to use in Storybook that are not in Create React App and why? :)

**Comment by acnebs** [comment]
@mrmckeb I need to add a babel plugin (`babel-plugin-emotion`).

I add it to the CRA babel config using [customize-cra](https://github.com/arackaf/customize-cra/issues). But can't add it to the Storybook config.

**Comment by mrmckeb** [comment]
@acnebs That makes sense... But I should point out that the recommend way would be to use the macro.
https://emotion.sh/docs/babel-macros

If you really want to modify the config and use `customize-cra`, you'll need to modify the Webpack config. If so, let me know and I can give you some more detailed instructions on how to do that - or share your project and I can take a look this weekend :)

**Comment by acnebs** [comment]
@mrmckeb Unfortunately the specific feature I'm using (and one that I don't think I can avoid using) still requires the babel plugin, even with macros support.

So any tips you can provide to customize my webpack config would be very helpful! I really only need to add this one babel plugin at the moment, otherwise the default config works great.

**Comment by mrmckeb** [comment]
@acnebs Not a problem - sorry for the delay, I started a new job last week and am still a little busy.

If you add a custom webpack config, you'll be able to modify the rules in there.

You can see here that we add CRA's config for TypeScript when it's needed, and you could effectively use the same approach.
https://github.com/storybooks/storybook/blob/next/app/react/src/server/cra-config.js#L196

When you find the rule that you need (using search perhaps), you can then add the babel plugin you need into that rule. It won't look so neat, but it will work for you without breaking the CRA behavour we've designed here.

Again, if you can share your project, I'd be happy to create a PR too (this weekend).

I think @shilman is right and we should improve the base behaviour... I'm just not sure what's best. We don't want that Storybook behaves differently than CRA. The CRA team never recommend using tools like `rewired` for the obvious reason that we can't support every configuration, but I'm also very aware that this is necessary at times.

**Comment by acnebs** [comment]
@mrmckeb Thanks for the thorough talk-through, that is now what I've done and it is working well.

There is some potential to have a lib like [customize-cra](https://github.com/arackaf/customize-cra) that would provide a cleaner API than modifying the `config` object directly.

I actually tried to use `customize-cra` for this purpose, as I thought Storybook was using CRA behind the scenes, but for some reason it appears that the `config` object is structured slightly differently than the default CRA config, to the point where `customize-cra` was not able to find the rule it was looking for.

**Comment by auderer** [comment]
@acnebs could you share your solution? I'm trying to get the same thing working on my end with @babel/plugin-proposal-optional-chaining.

**Comment by thejuan** [comment]
Same setup. I'm trying to upgrade to CRA3 and my storybook webpack.config.js that was adding jsx-control-statements is no longer working.

**Comment by acnebs** [comment]
@auderer @thejuan 

Fair warning, my solution is far from elegant, but it works. [Here's a gist.](https://gist.github.com/acnebs/17518ebd55ab7408311833095ce1542b)

**Comment by corydeppen** [comment]
Quick comment to prevent stale bot from closing the issue. Is consideration still being given to baking this into Storybook so workarounds don't have to be used?

**Comment by gastonmorixe** [comment]
Related issue#7340

**Comment by JamesYFC** [comment]
the config posted by @acnebs doesn't seem to work for my ts + CRA + storybook setup. 

I've got `import { css } from '@emotion/core';` in my tsx files, but it still gives me css="[object Object]"

**Comment by acnebs** [comment]
@JamesYFC I'm not using TS so that could be breaking it. All I can say is it works for me and allows me to use `css` from `@emotion/core`.

**Comment by JamesYFC** [comment]
@acnebs yeah my guess is TS.

For me, the macro + manual pragma for the base css stuff worked with emotion + storybook, But trying to use components made with `import styled from '@emotion/styled/macro';` didn't give me the styles from `styled(MyReactComponent)`, though it worked with the basic stuff like `styled('div')`.

**Comment by JamesYFC** [comment]
Nevermind about the styled bit, you just need to ensure you have className in your props for the React component and pass it down where you want into your jsx accordingly.

**Comment by mrmckeb** [comment]
Hi all,

The preset for CRA is designed to work with CRA, which does not support this - and will soon. We're waiting on TS 3.7.

At that stage, this won't be a problem.

In the meantime, we're working on a new preset which will allow you to extend the Babel config in CRA for Storybook.

**Comment by Ambyjkl** [comment]
You can always just edit the webpack config of react-scripts in a `postinstall` hook. Here's a simple hack to add more babel plugins:

First, add a custom script like `"postinstall": "./scripts/babelrc.sh",` under the scripts section of package.json
`scripts/babelrc.sh`:
```
#!/bin/bash

# remove previously added mod
sed -i '/BABELMOD/d' node_modules/react-scripts/config/webpack.config.js
# HACK: guess line number based on indented piece of code
linenum=$(grep -n '                plugins: \[' node_modules/react-scripts/config/webpack.config.js | cut -f1 -d:)
# add in all the plugins you want
sed -i "$((linenum + 1)) i\
require.resolve('react-hot-loader/babel'),\
require.resolve('foo'),\
require.resolve('bar'),\
require.resolve('baz'),\
// BABELMOD" node_modules/react-scripts/config/webpack.config.js
```
You can come up with cleaner code that doesn't have my hack. Now you can simply install these babel plugins right in your project and require.resolve would pick them up.

**Comment by shilman** [comment]
@mrmckeb TS3.7 is out -- any updates on this?

**Comment by mrmckeb** [comment]
Not yet @shilman, I'm checking now to see why the release is still held up.

**Comment by MeisterTea** [comment]
Is the preset available anywhere ? I was looking for it after I saw your post<https://github.com/storybookjs/storybook/issues/7340#issuecomment-560101242>

Can you confirm the CRA preset won't work in its current state ?

**Comment by shilman** [comment]
@MeisterTea https://www.npmjs.com/package/@storybook/preset-create-react-app

**Comment by MeisterTea** [comment]
do you use optional chaining ? did you specify the plugin in craOverrides ? if so, how ?

**Comment by slorber** [comment]
Hi,


If you are using CRA and you need a custom config (like a babel plugin) you can use react-app-rewired with customize-cra.

Here's how you can add the emotion css props plugin to both CRA + Storybook

# Step 1 

Add customize CRA + React-app-rewired

```
yarn add customize-cra react-app-rewired --dev
```

```
  /* ./package.json */

  "scripts": {
-   "start": "react-scripts start",
+   "start": "react-app-rewired start",
-   "build": "react-scripts build",
+   "build": "react-app-rewired build",
-   "test": "react-scripts test --env=jsdom",
+   "test": "react-app-rewired test --env=jsdom",
    "eject": "react-scripts eject"
}
```

# Step 2: customize the CRA config:

```
/* ./config-overrides.js */

const {
  override,
  addBabelPreset
} = require("customize-cra");
const path = require("path");

module.exports = override(
  addBabelPreset("@emotion/babel-preset-css-prop")
);
```


# Step 3: customize the Storybook config:

Note, you can keep using the CRA storybook preset

```
/* ./storybook/webpack.config.js */

module.exports = ({ config }) => {
  return require("../config-overrides")(config);
};
```


This way you don't have to duplicate the config overrides, and can use the same overrides for both CRA and Storybook to keep them in sync.

**Comment by penx** [comment]
> Step 3: customize the Storybook config:

Note that you can also do this in `.storybook/main.js`:


```js
module.exports = {
  webpackFinal: require("../config-overrides"),
};
```
