### ISSUE TITLE
CRA v2.1.8 and @storybook v5.1.0-alpha.24 addon-info not working for Flow types

### ISSUE THREAD

**Issue by sh00ter** [storybookjs/storybook#6491]
**Describe the bug**
Can't get addon-info to work properly with Flow types when using @storybook with CRA.
Using the default Flow Typed Button example from the official examples I am getting this Props Table

<img width="1624" alt="Screenshot 2019-04-11 at 17 24 06" src="https://user-images.githubusercontent.com/306704/55965188-c14a0880-5c7e-11e9-9dca-471d9aaa7a19.png">

Here is the code used for this story:

```javascript
import React from 'react';
import { storiesOf } from '@storybook/react';
import { action } from '@storybook/addon-actions';
import { withInfo } from '@storybook/addon-info';
import FlowTypeButton from './FlowTypeButton';

storiesOf('FlowTypeButton', module)
  .addDecorator(withInfo)
  .add(
    'Comments from Flow declarations',
    () => (
      <FlowTypeButton onClick={action('clicked')} label="Flow Typed Button" />
    ),
    {
      info:
        'Comments above the Flow declarations should be extracted from the React component file itself and rendered in the Info Addon prop table',
    }
  );
```

On the official demo app I can see the actual Flow types being correctly parsed and placed in the Props Table

<img width="1623" alt="Screenshot 2019-04-11 at 17 24 45" src="https://user-images.githubusercontent.com/306704/55965507-65cc4a80-5c7f-11e9-8566-a2bc9e55675c.png">

**To Reproduce**
1. ```npx create react-app my-app```
2. ```cd my-app```
3. ```npx -p @storybook/cli sb init```
4. install ```addon-info``` addon
5. import Flow Typed Button
6. add story as shown above
7. ```npm run storybook```

**Expected behavior**
I would expect to get the Props Table populated with all the prop types and their respective description. See the screenshot above.
Here is the code for the FlowTypeButton.js from the official @storybook repo
```javascript
// @flow
import React from 'react';

/* eslint-disable react/no-unused-prop-types,react/require-default-props */

const Message = {};

type PropsType = {
  /** A multi-type prop to be rendered in the button */
  label: string,
  /** Function to be called when the button is clicked */
  onClick?: Function,
  /** Boolean representing whether the button is disabled */
  disabled?: boolean,
  /** A plain object */
  obj?: Object,
  /** A complex Object with nested types */
  shape: {
    id: number,
    func?: Function,
    arr?: Array<{
      index: number,
    }>,
    shape?: {
      shape?: {
        foo?: string,
      },
    },
  },
  /** An array of numbers */
  arrayOf?: Array<number>,
  /** A custom type */
  msg?: typeof Message,
  /** `oneOf` as Enum */
  enm?: 'News' | 'Photos',
  /** `oneOf` A multi-type prop of string or custom Message */
  union?: string | typeof Message,
};

/** FlowTypeButton component description imported from comments inside the component file */
const FlowTypeButton = ({ label, onClick, disabled }: PropsType) => (
  <button type="button" onClick={onClick} disabled={disabled}>
    {label}
  </button>
);

FlowTypeButton.defaultProps = {
  disabled: false,
  onClick: () => {},
};

export default FlowTypeButton;
```

**System:**
 - OS: MacOS
 - Device: Macbook Pro Retina
 - Browser: chrome
 - Framework: react
 - Addons: addon-info
 - Version: 5.1.0-alpha.24

**Comment by pnarielwala-tc** [comment]
I'm having the same issue with `react@15.6.2` and SB4 (`4.1.18`)

**Comment by Hypnosphi** [comment]
Reproduced in official example: https://next--storybooks-official.netlify.com/?path=/story/addons-info-react-docgen--comments-from-flow-declarations

**Comment by yann-combarnous** [comment]
Same issue with CRA 3.0.1 and Storybook 5.1.0-rc.0..
