### ISSUE TITLE
storybook/html addon not rendering HTML, just string

### ISSUE THREAD

**Issue by LucaMele** [storybookjs/storybook#6495]
**Describe the bug**
While creating an addon in `storybook/html` i cannot render childNodes. In `storybook/react`, as far as i understood the code if you pass a child React Component it will render the React children. In Storybook Html we dont have react and therefore we need to be able to render childrens.

**To Reproduce**
My code:

```
import addons, { types, makeDecorator, AddonStore } from '@storybook/addons';
import { styled, css } from '@storybook/theming';
import React from 'react';

const ADDON_ID = 'markdown';
const ADDON_EVENT = `${ADDON_ID}/event`;
const PANEL_ID = `${ADDON_ID}/panel`;
const DEFAULT_MSG = 'No Markdown Provided';

addons.register(ADDON_ID, (api) => {
  let input = DEFAULT_MSG;

  const render = () => {
    const Wrapper = styled.div('<div></div>');
    return props => Wrapper;
  };
  const title = 'Readme';
  const channel = addons.getChannel();

  channel.on(ADDON_EVENT, ({ id, html }) => {
    const { render: _render } = addons.getElements(types.PANEL)[PANEL_ID];
    input = html;
    _render();
  });

  addons.add(PANEL_ID, {
    type: types.PANEL,
    title,
    render,
  });
});

export const withMarkdown = makeDecorator({
  name: 'withMarkdown',
  parameterName: 'markdown',
  wrapper: (storyFn, context, { options : html, parameters }) => {
    const channel = addons.getChannel();
    const { id } = context;
    channel.emit(ADDON_EVENT, { id, html: html || DEFAULT_MSG });
    return storyFn(context);
  },
});


```

**Expected behavior**
render should accept type HTMLElement

**Comment by LucaMele** [comment]
error message in console:

` Warning: Functions are not valid as a React child. This may happen if you return a Component instead of <Component /> from render. Or maybe you meant to call this function rather than return it.`

**Comment by Hypnosphi** [comment]
Hi @LucaMele can you please also show an example of story? `@storybook/html` definitely accepts `HTMLElement` as a story return value
