### ISSUE TITLE
Using static build inside an iframe causes Storybook update links to either not work or throw CSP error

### ISSUE THREAD

**Issue by mohsinulhaq** [storybookjs/storybook#6519]
**Describe the bug**
`Refused to display 'https://github.com/storybooks/storybook/pull/xxxx' in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'".`
When trying to open changelog PR links.
And no action at all when opening rest of the links.

**To Reproduce**
1. Render storybook static build inside an iframe.
2. Go to updates section.
3. Clicking on links other than changelog PRs don't even work,
4. Trying to open changelog PRs throws:
`Refused to display 'https://github.com/storybooks/storybook/pull/xxxx' in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'".`
5. I tried adding 'target: "_blank"' to these links but only the PR links work fine, rest of links are still non-functional.

**Expected behavior**
All links should open up in a new window.

**Screenshots**
![image](https://user-images.githubusercontent.com/7688231/56113693-3584f480-5f7c-11e9-9015-a60a24a61906.png)

**System:**
 - OS: Windows 10
 - Browser: Chrome
 - Framework: React
 - Version: 5.0.6

**Comment by jsdevel** [comment]
ok, thanks for the update!  if i have time i'll let you know.  we found a workaround by pushing to s3 internally...

**Comment by johnhunter** [comment]
Related issue with CSP 'unsafe-inline'. Raised at https://github.com/storybookjs/telejson/issues/18

**Comment by domoritz** [comment]
@jsdevel Have you had a chance to look into this bug? This still seems to be a problem.

**Comment by jsdevel** [comment]
@domoritz i haven't.

**Comment by johnhunter** [comment]
If I've understood this correctly you are trying to display the github PR page inside an iframe?

The `github.com` Content-Security-Policy forbids putting github in iframes. See the following response header from `https://github.com/storybooks/storybook/pull/xxxx`
```
Content-Security-Policy:
  default-src 'none'
  base-uri 'self'
  block-all-mixed-content
  connect-src 'self' uploads.github.com www.githubstatus.com collector.githubapp.com api.github.com www.google-analytics.com github-cloud.s3.amazonaws.com github-production-repository-file-5c1aeb.s3.amazonaws.com github-production-upload-manifest-file-7fdce7.s3.amazonaws.com github-production-user-asset-6210df.s3.amazonaws.com wss://live.github.com *.actions.githubusercontent.com wss://*.actions.githubusercontent.com
  font-src github.githubassets.com
  form-action 'self' github.com gist.github.com
  frame-ancestors 'none'
  frame-src render.githubusercontent.com
  img-src 'self' data: github.githubassets.com identicons.github.com collector.githubapp.com github-cloud.s3.amazonaws.com *.githubusercontent.com
  manifest-src 'self'
  media-src 'none'
  script-src github.githubassets.com
  style-src 'unsafe-inline' github.githubassets.com
```
I don't think the response CSP header is configurable by repo owners.

**Comment by johnhunter** [comment]
The issue @jsdevel is having looks slightly different as the host is blocking scripts in the iframe. Adding the appropriate [`sandbox` attribute ](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#attr-sandbox)to the iframe might solve it.
