### ISSUE TITLE
knobs addon - use of default value is unintuitive

### ISSUE THREAD

**Issue by egauci** [storybookjs/storybook#6540]
**Is your feature request related to a problem? Please describe.**
I was trying to have the current value of a select knob persist between page loads by using local storage. It didn't work, and I found the reason:

      const existingKnob = knobStore.get(name);
      // We need to return the value set by the knob editor via this.
      // But, if the user changes the code for the defaultValue we should set
      // that value instead.
      if (existingKnob && deepEqual(options.value, existingKnob.defaultValue)) {
        return this.getKnobValue(existingKnob);
      }

**Describe the solution you'd like**
I'd like a way to pre-select an option on initial load of the story, before the user makes a selection. Once the user makes a selection, I'd want that respected and not overridden. (By _user_ I mean the human operating the browser, not the developer who wrote the code. The code I pasted above seems to mean the developer.)

Ideally I would like a way to make the default parameter behave the way I described above, but I understand that would be a breaking change. Maybe a parameter in _addDecorator_ to change the behavior? I use _addDecorator_ in config.js.

**Describe alternatives you've considered**
I wrote a bunch of code to "freeze" the default I pass after a fresh reload, using React local state. It works, but it's not ideal.

**Are you able to assist bring the feature to reality?**
I'm willing to help if I can. I know JavaScript and React well.

**Comment by leoyli** [comment]
Hi, thank you for bringing your idea!

Just want to get clarified,

> between page loads

Does that saying you want the knob persist to the current selection, even when you refresh the page? I can see this being useful in some cases, but not sure if that is realistic (due to the limitation on the local storage and the current implementation, which means we might need a unique identifier on each single knob value...).

**Comment by egauci** [comment]
@leoyli - no sorry if I was not clear. I think adding functionality to have knobs retain value across page loads is probably best left to the developer users.

I just feel that the way the default value parameter works right now is strange. If it changes between renders, it actually overrides the browser user's selection. Here's an example:

A Select has three values. On initial render, the code specifies the first as the default value, and the select knob is rendered correctly that way and returns the correct value.

The browser user changes the value to the second option. This triggers a render which calls the select function with the first value as default. Since this is the same as before, everything works as expected and the select function returns the second value.

Next the user changes the value to the third option. This triggers a render but this time the select function is called with the second option as the default. This is where things go wrong. The knobs code sees that the default parameter has changed and returns it, overriding the browser user.

There must be a reason it was done this way, but it really should not be called "default" then. In my understanding, a default value should be used when no other value is available. Basically the default value should be used only on the initial render, since after that there is always a usable value. The React useState hook does this correctly.

My initial attempt was to bracket calling select with a load then store, something like this:

    const selectOptions = {} // actually set this up, not as an empty object
    const defVal = localStorage.getItem('selectval') || 'option1'
    const newVal = select('label', selectOptions, defVal)
    localStorage.setItem('selectval', newVal)

If things had worked as I expected, this would have made the selected value persist across page loads.

**Comment by leoyli** [comment]
Aha, I see your point here.  If the passed `devVal` changed, then knob treat it as a new one and ignore the user selection.  It's interesting you set the default value dynamically.  I may need to see the source code a bit since I'm wondering its internal logic later...
