### ISSUE TITLE
Unicode escape character displayed in addon-jest

### ISSUE THREAD

**Issue by SamKirkland** [storybookjs/storybook#6542]
**Describe the bug**
@storybook/addon-jest is displaying \u001b unicode character (ESCAPE) in the addon panel on failed tests.
Clearly it wasn't at some point, I couldn't pin down the exact version jest changed this but it is happening on the current version of CRA (jest v3) and jest v4.

Looks like a replace function could be added to Message.tsx to remove all unicode characters before the final outputs.

**To Reproduce**
1. See official storybook demo
2. https://storybooks-official.netlify.com/?path=/story/addons-jest--withtests
4. See escape character (shows as a box)

**Screenshots**
Storybook jest panel view
![image](https://user-images.githubusercontent.com/7682814/56249393-32b7fb80-6071-11e9-97cd-c0cd48b71e90.png)

jest test result file
![image](https://user-images.githubusercontent.com/7682814/56249369-1fa52b80-6071-11e9-9514-bddd9d5ea8ba.png)

**System:**
 - OS: windows10
 - Device: all
 - Browser: all
 - Framework: react
 - Addons: jest
 - Version: v41.1.18

I attempted to make a PR to resolve the issue but couldn't get a successful build even following the contribution and setup steps.

Thanks guys, keep up the great work.

**Comment by SamKirkland** [comment]
I've confirmed it's only an issue on Google Chrome + Windows. [See this blog post for info](https://gschoppe.com/uncategorized/fixing-unicode-support-in-google-chrome/)

I don't like the idea of fixing a browser + OS specific issue but it is 25%+ of the market share and has been around for 6+ years.

Thoughts? I can throw together a PR that removes \u001b.

**Comment by shilman** [comment]
@SamKirkland Sounds good!

**Comment by goranovs** [comment]
This bug still exists and it is a problem in every browser under Windows that's based on Chromium. (Google Chrome, Microsoft Edge &, etc). Working on Windows with WSL (Ubuntu, Debian &, etc) is a very common thing nowadays. Hopefully, this will be resolved soon.

JFYI, Chromium browsers market share is 64%+ https://gs.statcounter.com/browser-market-share 
and Windows OS has 30% https://gs.statcounter.com/os-market-share if we consider desktops only it's above 70% https://gs.statcounter.com/os-market-share/desktop/worldwide
