### ISSUE TITLE
Clicking knobs button doesn't work

### ISSUE THREAD

**Issue by sibbl** [storybookjs/storybook#6546]
I'd like to use a button knob to change a props I pass to the component I want to present.

I followed the sample given here: https://storybooks-official.netlify.com/?path=/story/addons-knobs-withknobs--triggers-actions-via-button

Unfortunately, both the official sample and my local trigger the method I passed.

Your sample is expected to change anything when clicking the "Toggle item list state" button, but the view doesn't change at all. Nothing's rerendered, although I'd expect it to be rerendered with updated props.

Link to sample code of the story which I've also tested locally in different browsers: https://github.com/storybooks/storybook/blob/59e4d06ad24c22825db5c22925873eb40a819793/examples/official-storybook/stories/addon-knobs.stories.js#L291-L308

All other input fields work fine.

**System:**
 - OS: Windows 10 build 18362.53
 - Device: MS Surface Pro (neither clicking the button via mouse, touch or pen does work)
 - Browser: Chrome, Edge, Firefox
 - Framework: React
 - Addons: knobs
 - Version: 5.0.8 (locally) and 5.0.9 (the version your netlify docs use)

**Comment by javve** [comment]
Bumb! The button knob doesn't seem to work?
It don't work in your example and it don't work for me locally. 
```
const handler = () => {
  console.log('hey?')
  return false
}
button(label, handler)
```
