### ISSUE TITLE
Could add a classname to addon-info proptype table

### ISSUE THREAD

**Issue by nianiaJR** [storybookjs/storybook#6547]
**Is your feature request related to a problem? Please describe.**
I need add style to the prop-types table whithout influencing the showing "Table" component by addon-info，I use the less，but it's diffcult to use css selector only selecting the proptypes table element without influencing the <Table> coomponent I display. 

**Describe the solution you'd like**
Adding a className for the proptypes table element is a nice choice

**Describe alternatives you've considered**
providing a api to set the className is also great.

**Are you able to assist bring the feature to reality?**
If needed, yes

**Comment by shilman** [comment]
You can override `options.TableComponent` so you can literally put whatever you want in there?

**Comment by nianiaJR** [comment]
yes，I know that way. But the options.TableComponent seems  to override table render，what I want is just adding a className to make the div wapper or table more semantic.Tanks for your reply~
