### ISSUE TITLE
"No Preview" Shown when switching between components

### ISSUE THREAD

**Issue by bennypowers** [storybookjs/storybook#6555]
**Describe the bug**

**To Reproduce**
1. Install v5.1.0-alpha.29
2. Create multiple stories using '@storybook/polymer'
3. run storybook
4. Load storybook in browser - first shown story is fine
5. Switch to another story in the side bar menu
6. Second story displays, but so does "No Preview" alert.

**Expected behavior**
"No Preview" should only show when there is no preview.

**Screenshots**
![no-preview-out](https://user-images.githubusercontent.com/1466420/56296969-22b71f00-6138-11e9-8cab-489a3c228ca5.gif)

**Code snippets**
If applicable, add code samples to help explain your problem.

**System:**
 - OS: MacOS
 - Device: Macbook Pro 2018
 - Browser: FF, Chrome
 - Framework: Web-components (polymer package)
 - Addons: a11y, actions, backgrounds, console, knobs, links, notes, options, storysource, viewport
 - Version: 5.1.0-alpha.29

**Comment by shilman** [comment]
It's showing "no preview" for me the whole time on your storybook (private link). Hopefully one of our polymer gurus can give a look!

**Comment by bennypowers** [comment]
Confirming this bug still exits with storybook 5.1.0-rc.0

**Comment by ndelangen** [comment]
I'm not able to reproduce the behavior in the polymer-cli example. @bennypowers if I could take a look at the example too, I might be able to help here. 🙇

**Comment by bennypowers** [comment]
@ndelangen Thanks for writing. I sent you a PM on storybook's discord with the link to the (private for now) storybook. Thanks for the interest

**Comment by bennypowers** [comment]
I was unable to reproduce with storybook 5.1.3. Closing for now. If it comes back once I succeed at building newer versions (#7084) I'll reopen

**Comment by ndelangen** [comment]
Thanks for reporting @bennypowers 🙇 

I sure hope the issues stays closed, but obviously happy to assist if it does crop up again.
