### ISSUE TITLE
problem with custom config folder instead of .storybook

### ISSUE THREAD

**Issue by devniel** [storybookjs/storybook#6568]
Hello,

**Describe the bug**
I'm getting an error on remote platforms (on localhost runs without problems)
`(node:901) UnhandledPromiseRejectionWarning: Error: => Create a storybook config file in "config/storybook/config.{ext}".` when using a custom configuration folder an setting it with the `-c` argument.

**To Reproduce**
I'm building my project on a PaaS, where there is necessary to provide a script to build the project, in my case it's like this.

```bash
#!/bin/bash
npm config delete prefix
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
nvm install 8.11.4
npm install yarn -g
yarn install
yarn build
yarn build-storybook
```
My project structure is:
```
config
 storybook
   config.js
   webpack.config.js
package.json
```

I'm using a custom configuration folder, so my `build-storybook` script executes this command:

`build-storybook -c config/storybook -o storybook` (I've also used `./config/storybook`)

But it returns the described error.

The thing is that when using the default `.storybook` on the root folder, and setting the script to `build-storybook -o storybook` it builds without problems. I'm thinking that there is a problem with the resolution of the given custom folder path.

**Expected behavior**
Build storybook without problems.

**Screenshots**
![image](https://user-images.githubusercontent.com/1231888/56441285-31294600-62b2-11e9-9059-391d37838e55.png)

**Comment by shilman** [comment]
What version?

**Comment by devniel** [comment]
Hi, I'm using `@storybook/react": "^5.0.10"`

**Comment by shilman** [comment]
Strange. Our `examples/official-storybook` uses a custom path:

https://github.com/storybooks/storybook/blob/master/examples/official-storybook/package.json#L6

And it works fine:

https://storybooks-official.netlify.com/

Do you have a repro you can share?

**Comment by bife1** [comment]
The same bug, any suggestions?

**Comment by Gilbert-Adu** [comment]
having the same bug. anyone with suggestions as to how to solve this?
