### ISSUE TITLE
Separating components from project

### ISSUE THREAD

**Issue by Troncoso** [storybookjs/storybook#6576]
When I first saw storybook, it looked like it was a way of building a component library separate of an actual project. After looking more into it, all tutorials have you building up your stories in an actual project. So, let's say I have:

- component-lib
- project1
- project2

Both  project1 and project2 use the same component-lib. Should storybook go in the component-lib or in a project? I would think in the component-lib, but I wouldn't want all the storybook dependencies carrying over when I import component-lib into my actual projects.

Am I misunderstanding how to implement storybook? In my mind, it'd be great to have a stand alone component library that, when changes are committed, a CI implementation would run tests and publish the storybook to an internal webspace for designers/developers to user as reference. Developers can then simply import the library from an internal NPM repository.

**Comment by luksm** [comment]
Hi @Troncoso, you can add storybook as a dev dependency on you component library and add a [files](https://docs.npmjs.com/files/package.json#files) key to your package.json in order to export only your final compiled library.

**Comment by TCiobanu** [comment]
Hey @luksm, I have a similar situation to @Troncoso, I have a components directory which is a submodule to a webapp and storybook integrated into the components. Is there any way to separate storybook, i.e. the config files, and all the stories from the components? Your suggestion, correct me if I'm wrong, separates the storybook module from production but not the stories and associated files.

**Comment by luksm** [comment]
Hey @TCiobanu, sorry for the delay. The same thing applies, when you are packaging your submodule you should be able to say what will make the cut. 

Lets say your components is structured like this

```
sub-module-components
└─ .storybook
└─ dist
│   └─ sub-module-components.js
└─ src
│   └─ component
│   │   index.js
│   │   component.story.js
└─ package.json
```

On your package.json you would have

```
{
    ...
    files: [
        'dist',
        'src/**/*(!.story).js',
    ],
    ...
}
```

And when you run `npm pack` or `npm publish` you'll see that only the storybook files are not included in the final package.
