### ISSUE TITLE
Theme is cached between unrelated instances

### ISSUE THREAD

**Issue by ghengeveld** [storybookjs/storybook#6587]
**Describe the bug**
When running multiple Storybook projects, the logo from one project is shown in another. Investigation shows that the logo URL is stored in `@storybook/ui/store` in LocalStorage, which explains why this happens.

**To Reproduce**
1. Setup a Storybook with a custom `brandImage` and run it locally.
2. Setup another Storybook with default config.
3. Kill the first Storybook, run the second on the same port.
4. The custom logo from the first appears on this completely unrelated Storybook.

**Expected behavior**
The second project should show the default Storybook logo.

**System:**
Mac OS, Chrome

**Comment by mickaelzhang** [comment]
I'm having a similar issue where I tested to create and apply a theme to my current project. At the end, I removed it but the change that I made are still there in `dev` mode

**Comment by shilman** [comment]
An ugly workaround... In browser dev console:
```
> localStorage.clear()
```

**Comment by mickaelzhang** [comment]
Oh didn't know that the them was stored in `localStorage`, what's the reason if you don't mind @shilman ?

**Comment by shilman** [comment]
@mickaelzhang I believe that if we didn't cache it, Storybook would show up with the default theme while it loads and then switch to configured theme after a second or two. With caching, it immediately shows the user-configured theme, and then updates after the configuration loads (tho it seems like that part is broken). Maybe @ndelangen can comment more

**Comment by mickaelzhang** [comment]
@shilman Oh right, it make sense !

It might be due to the fact that I'm using the default theme so no update is done after loading the theme from `localStorage` ?

**Comment by shilman** [comment]
That's a good thought @mickaelzhang -- I bet that's it! @ndelangen is that an easy fix?

**Comment by ndelangen** [comment]
@shilman @mickaelzhang If no theme is set at all, then I don't know a good fix really...

Here's a concept though:
If you're using multiple storybooks and they all have their own theme.
Make sure they all have their own port. That way they do not share the localstorage between them.

**Comment by ndelangen** [comment]
This relates to #6806 
If the theme is loaded from the manager itself instead of loaded in the preview, then transmitted to the manager, the delay disappears. This means we don't have to cache the theme in the localstorage anymore to prevent the flash of incorrect theme (FOIT) 😄

**Comment by ndelangen** [comment]
The best way to fix this right now, if to always set a theme, even if using the default one.

**Comment by xBau** [comment]
This issue is still happening to me with Storybook 5.2.5, the brand logo is being cached after removing a custom theme.

**To Reproduce**

1. Add a theme with a custom brandImage
2. The theme is showed properly
3. Remove the custom theme and keep setting by default (no options.theme at all)
4. The theme is removed but you can still see the former theme brandImage
5. localStorage.clear() in dev console solves the issue

**Comment by shilman** [comment]
@ndelangen is working on a solution in 5.3! 🎉

**Comment by webholics** [comment]
This is still happening for me in storybook v5.3.18

**Comment by shilman** [comment]
I believe this is fixed in 6.0

**Comment by jpcmf** [comment]
I'm facing this issue right now on 6.1.3

**Comment by shilman** [comment]
@jpcmf tracked in #13200

**Comment by jpcmf** [comment]
I figured out to fix this removing node_modules/.cache/storybook
I don't know about the `--no-manager-cache` flag, thank you @shilman

**Comment by arsamsarabi** [comment]
On version 6.1.21, faced the same problem and having no luck with the `--no-manager-cache` flag
