### ISSUE TITLE
Knobs numbers return null instead of undefined

### ISSUE THREAD

**Issue by alfnielsen** [storybookjs/storybook#6591]
**Describe the bug**
I know somebody would say that this is not an error,
but knobs 'number' dont work with default parameter values because 
it returns null instead of undefined on empty string.

**To Reproduce**
1. Create a React/Angular component with default value and write a story for it.
2. When you delete all context from the knobs input in storybook the value in the component will be null instead of the default value. 
(And this is because default values only works with undefined and not null)

**Expected behavior**
expect undefined, not null

**Code snippets**
storybook/addons/knobs/src/converters.js
Line 18:
```
  toFloat: value => (value === '' ? null : parseFloat(value)),
```
Should be:
```
  toFloat: value => (value === '' ? undefined : parseFloat(value)),
```

bs and good in general :)

**Comment by shilman** [comment]
I think this is a dupe to https://github.com/storybooks/storybook/issues/4487

Right @Hypnosphi ?

**Comment by Hypnosphi** [comment]
Yep

**Comment by alfnielsen** [comment]
I dont believe it's a duplicate of #4487 but clearly related.

The problem with 'select' knobs require another solution then this does.

The 'number' knobs is because it's has been choosen at some point to return 'null'
in ```storybook/addons/knobs/src/converters.js``` for numbers that a empty string instead of undefined

**Comment by LilyMGoh** [comment]
I'm experiencing the same issue as well.

**Comment by davidhorm** [comment]
This is my workaround that worked for me:

```javascript
export const knobsStory = () => (
  <MyComponent myNum={number('My Number', 0.5) || undefined}
  />
);
```
