### ISSUE TITLE
React Native ondevice theming

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#6605]
RN ondevice UI should be themable to match the users' app

As much as possible, the theming API should mirror what we're doing for the web: https://storybook.js.org/docs/configurations/theming/

**Comment by shilman** [comment]
w00t!! I just released https://github.com/storybooks/storybook/releases/tag/v5.1.0-alpha.39 containing PR #6603 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by lyqht** [comment]
I would like to request on documentation for ondevice theming! 
I have tried adding the addParameters({ config}) method for theming but it does not work. I think this method does not exist for RN storybook yet, can the devs help to clarify this?

**Comment by shilman** [comment]
@lyqht This needs docs, but did you try this example from the code?

```
// const darkTheme = {
//   backgroundColor: 'black',
//   headerTextColor: 'white',
//   labelColor: 'white',
//   borderColor: 'white',
//   previewBorderColor: 'gray',
//   buttonTextColor: 'white',
//   buttonActiveTextColor: 'white',
// };

 // const StorybookUIRoot = getStorybookUI({ theme: darkTheme });
```

**Comment by lyqht** [comment]
hi @shilman, i have tried the above code that you have given and with the following template code on the storybook website, but both still rendered the storybook in default theme:
```
import { create } from '@storybook/theming';

const storybookTheme = create({
	base: 'light',

	colorPrimary: 'hotpink',
	colorSecondary: 'deepskyblue',

	// UI
	appBg: 'white',
	appContentBg: 'silver',
	appBorderColor: 'grey',
	appBorderRadius: 4,

	// Typography
	fontBase: '"Open Sans", sans-serif',
	fontCode: 'monospace',

	// Text colors
	textColor: 'black',
	textInverseColor: 'rgba(255,255,255,0.9)',

	// Toolbar default and active colors
	barTextColor: 'silver',
	barSelectedColor: 'black',
	barBg: 'hotpink',

	// Form colors
	inputBg: 'white',
	inputBorder: 'silver',
	inputTextColor: 'black',
	inputBorderRadius: 4,

	brandTitle: 'MOL Storybook',
	brandUrl: 'https://example.com',
	brandImage: 'https://placehold.it/350x150',
});

export default storybookTheme
```

```
const StorybookUIRoot = getStorybookUI(
	{ port: 7070, host: 'localhost', theme: storybookTheme });
```

Thanks for helping!

**Comment by Gongreg** [comment]
@lyqht could you also write the storybook version you are using?

**Comment by Gongreg** [comment]
@lyqht, I've just tested out @storybook/react-native@5.1.0 and the way @shilman wrote does work. If you use 

```
 const darkTheme = {
   backgroundColor: 'black',
   headerTextColor: 'white',
   labelColor: 'white',
   borderColor: 'white',
   previewBorderColor: 'gray',
   buttonTextColor: 'white',
   buttonActiveTextColor: 'white',
 };
 const StorybookUIRoot = getStorybookUI({ theme: darkTheme });
```

the styles get applied.

**Comment by RitikaGupta8734** [comment]
Hi @Gongreg [this way](https://github.com/storybookjs/storybook/issues/6605#issuecomment-502094019) of writing and adding theme indeed works and thanks a lot for providing it but I want to ask is there some way so that we can choose what theme to select inside react-native storybook app?. So that we can decide from inside the storybook which theme to choose light, dark or custom ... and it gets rendered accordingly. 
Using the above way we are in a way hardcoding it to use a particular theme and when we need to change it later we have do it manually in the code which I don't want.

**Comment by RitikaGupta8734** [comment]
> @lyqht This needs docs, but did you try this example from the code?
> 
> ```
> // const darkTheme = {
> //   backgroundColor: 'black',
> //   headerTextColor: 'white',
> //   labelColor: 'white',
> //   borderColor: 'white',
> //   previewBorderColor: 'gray',
> //   buttonTextColor: 'white',
> //   buttonActiveTextColor: 'white',
> // };
> // const StorybookUIRoot = getStorybookUI({ theme: darkTheme });
> ```

Hi @shilman Thank you for your answers above. But I want to ask where is this code? I want to see what other parameters we can specify besides these 7. Can we specify `logo` also ? which is specified as `brandImage` in the official docs [here](https://storybook.js.org/docs/react/configure/theming)
