### ISSUE TITLE
5.1.0-alpha.34 react-native linkTo navigating but not rendering story

### ISSUE THREAD

**Issue by arjunmehta** [storybookjs/storybook#6614]
**Describe the bug**
When using `linkTo` to navigate to another story, navigation seems to occur and be registered in the navigator, but the component for that story is not rendered.

**To Reproduce**
Install RN storybook example, try adding `linkTo` to button onPress to navigate to sub-stories.

**Expected behavior**
When tapping on a button having passed `linkTo`, it should navigate to that story AND render the component.

**Screenshots**
![2019-04-24 15 19 41](https://user-images.githubusercontent.com/862049/56697838-be024400-66a4-11e9-8afe-6d09a2931559.gif)

**Code snippets**

```jsx
import React from 'react';

import { storiesOf } from '@storybook/react-native';
import { linkTo } from '@storybook/addon-links';

import Button from '../components/Button.component';
import CenterView from '../components/CenterView.component';
import Welcome from '../components/Welcome.component';

storiesOf('Welcome', module)
  .add('to Storybook', () => <Welcome showApp={linkTo('Button')} />);


storiesOf('Button', module)
  .addDecorator(getStory => {
    return (
      <CenterView>{getStory()}</CenterView>
    );
  })
  .add('with primary type', () => {
    return (
      <Button
        label="Testing A"
        onPress={linkTo('Button', 'with secondary type')}
      />
    );
  })
  .add('with secondary type', () => {
    return (
      <Button
        label="Testing B"
        onPress={linkTo('Button', 'with primary type')}
      />
    );
  });
```

**System:**
 - OS: MacOS
 - Device: iPhoneX, simulator
 - Framework: react-native
 - Addons: `addon-links`
 - Version: 5.1.0-alpha.34

**Additional context**
May have changed something from the template, but not sure what could cause this issue.

**Comment by wilau2** [comment]
Experiencing same behavior

**Comment by shilman** [comment]
Is this related to https://github.com/storybooks/storybook/pull/6823 ?

**Comment by wilau2** [comment]
I'm not sure I thought it was strictly related to react-native... 
I will try the #6823 fix in my project later today if I have time :)!

**Comment by Gongreg** [comment]
Hey,
This issue exists because link addon emits SELECT_STORY event, but react native doesn't listen for this event, it listens to SET_CURRENT_STORY event. I assumed that SET_CURRENT_STORY is like an order and after preview handles it it emits SELECT_STORY event.

Do we have a list of events with descriptions when they are used? I know that there is list of events but it doesn't list use cases. @shilman, @ndelangen. Asking since issues like this can be raised in future.

**Comment by shilman** [comment]
@ndelangen can you document this as part of the addons documentation?
