### ISSUE TITLE
custom webpack config through option while use storybook standalone

### ISSUE THREAD

**Issue by EnjoyChan** [storybookjs/storybook#6615]
**Is your feature request related to a problem? Please describe.**
We have many projects in  our team, and we create a tool called a8k to collect common webpack config, the a8k tool run webpack from node, so we want the standalone too,  but we need to pass webpack config by option not by wepack.config.js in .storybook

**Describe the solution you'd like**
add webpack config option for storybook standalone

**Comment by shilman** [comment]
Can you use this as a workaround?

https://storybook.js.org/docs/configurations/custom-webpack-config/#using-your-existing-config

**Comment by EnjoyChan** [comment]
> Can you use this as a workaround?
> 
> https://storybook.js.org/docs/configurations/custom-webpack-config/#using-your-existing-config

I don't think so. Throught that way, I need to pass exiting config in every project, and the exiting config is loacated in our npm pacakage, that means, I need to copy the config in every project. Can you add webpack config option for storybook standalone

**Comment by shilman** [comment]
Crikey!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-alpha.41 containing PR #6886 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
