### ISSUE TITLE
Configure which browser

### ISSUE THREAD

**Issue by gdarai** [storybookjs/storybook#6618]
**Is your feature request related to a problem? Please describe.**
I am using storybook for a chrome-only app, but the storybook opens everytime in firefox. can I change the default somehow?

**Describe the solution you'd like**
A config option or responsiveness to some env variable.

**Comment by blemaire** [comment]
you may have to setup the default browser on your machine (I'm guessing that's not an option hence why you're asking if it can be configured?)

**Comment by ptandler** [comment]
In case someone steps over this issue: It seems that the `BROWSER` environment variable is used, if set, so you can e.g. use `BROWSER=brave-browser pnpm run storybook` to overwrite the default.

See https://github.com/storybookjs/storybook/issues/15316#issuecomment-869079555
