### ISSUE TITLE
UI looking different in storybook than real

### ISSUE THREAD

**Issue by jamkaramol** [storybookjs/storybook#6620]
In storybook 
![image](https://user-images.githubusercontent.com/11329267/56729729-99c16880-6773-11e9-8163-8f993d2519f7.png)

And in the actual browser

![image](https://user-images.githubusercontent.com/11329267/56729781-b362b000-6773-11e9-9561-75b8dfdcd5e8.png)

Is anything i a am missing ?? please help

**Comment by blemaire** [comment]
most likely your font and your css is not loading in your storybook app
