### ISSUE TITLE
addon-info prop type errors on Chrome devtool

### ISSUE THREAD

**Issue by wellyshen** [storybookjs/storybook#6624]
**Describe the bug**
Addon-info throw prop type errors on Chrome devtool

**To Reproduce**
1. Start storybook
2. Open Chrome devtool
3. Prop type errors displayed on Chrome devtool

**Expected behavior**
No prop type errors.

**Screenshots**
<img width="453" alt="螢幕快照 2019-04-25 下午10 15 46" src="https://user-images.githubusercontent.com/21308003/56743101-87aded00-67a8-11e9-91cf-33616d95ba75.png">

**Code snippets**
```js
.add(
    'Some description',
    () => <div>Test</div>,
    {
      info: `
        ## Purposes
        This example is to override styles to make banner items with full-width of conatiner.

        ## Steps
          - Pass "className" props to Banner, like "full-width-banner"
          - Add styles to make item with full width as container

        ~~~scss
          .full-width-banner {
            &.kk-banner {
              .slider-mask {
                padding: 0;
              }

              .banner-item {
                padding: 0;
              }
            }
          }
        ~~~
      `
    }
  )
```

**System:**
 - OS: MacOS
 - Device: Macbook Pro 2016
 - Browser: Chrome
 - Framework: React
 - Addons: Addon-info
 - Version: v5.0.10

**Additional context**
These errors won't show on v4.x

**Comment by shilman** [comment]
Possible dupe to #5915

**Comment by wellyshen** [comment]
This issue has gone. Close it.
