### ISSUE TITLE
Addon-docs: documentation-only support

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#6644]
Docs are currently tied to stories. We need to add the ability to include freeform docs without stories, e.g. for styleguides, setup instructions, etc., and have them linked in Storybook UI.

Easy (but lame 🤷🏻‍♂️) workaround is to add a dummy story to the top of your doc:

```js
<Story name="Status Colors" height="0">{''}</Story>
```

Short-term approach:
- User adds `<Meta title="x/y/z">` to the doc w/ no stories
- MDX compiler inserts a dummy story with `{ docsOnly: true }` parameter
- Storybook UI is updated to hide `docsOnly` stories unless you're in docs mode #6646

Long-term approach:
- Normalize story parameters vs. kind parameters
- Support adding kinds without adding stories

**Comment by B3Kay** [comment]
Is there any progress on this one?
I'm stoked to see more! 🍔

**Comment by shilman** [comment]
@B3Kay nope. you'll need to use the workaround for now!

**Comment by shilman** [comment]
@domyen @tmeasday After some aborted exploration in #7302 here is an updated proposal for how to deal with this in a more regular way.

<img width="805" alt="Storybook" src="https://user-images.githubusercontent.com/488689/60650619-114bfc00-9e77-11e9-9247-aecb12aa3de5.png">

First, a little background:

1. Users can define these lightweight "docs-only" docs, which can be co-mingled at any level in the nav tree.
2. Users can define stories, which can also be co-mingled at any level.
3. Users can define groups, which are shown as components if they contain leaves, or folders if they only contain non-leaves.

There are a few problems that we're trying to solve at once:

1. Right now there is no concept of "docs" in the `story_store`, which is Storybook's underlying data structure. We hang docs off the stories instead, but when the user writes pure MDX with no stories, we need to create a dummy "docs-only" story to compensate.
2. Having these interminglings above cause complicated UI situations. For example:
  a. When you want to collapse all the stories automatically in "docs mode", what do you do when a group contains both leaves and non-leaves?
  b. When the user clicks on the first story in the nav UI and it scrolls to that story, how does the user get to the top of the document when the any story can be the "primary" story?
  c. How do we handle docs-only stories in various cases above?

To address these issues, I propose the following UI changes:

1. For every MDX file we create a new node in the nav with a different icon (like the document icon above). It's a leaf node, like a story, and it's always the first leaf under its component. Clicking on the node takes you to the top of the docs for that file. This applies both to docs-only MDX as well as to MDX with stories to address issue 2b above.
2. For every story defined in an MDX file, clicking on that story scrolls you to that story's position in the file.
3. For every COMPONENT in the UI, clicking on the component automatically navigates to its first story. This is a controversial change, but it addresses the "extra click" issue raised by a lot of users, and which will get worse when we add doc-only stories per above.
4. Optionally, for docs-only stories defined at the root level, we collapse the docs-only leaf node into its corresponding group to address a special case people adding docs to the beginning of their storybook.

**Comment by domyen** [comment]
This looks awesome! Comments inline:


> Clicking on the node takes you to the top of the docs for that file. This applies both to docs-only MDX as well as to MDX with stories to address issue 2b above.

I'm having some trouble following this. I'm thinking something along the lines of, please correct if I have it wrong: 

- Clicking on a docs-only MDX file should take you to those docs. No toolbar.

If you have a component that uses MDX to create stories: 
- Canvas tab active: Clicking on the story should take you to the story.
- Docs tab active: Clicking on the story should scroll you to the story in the docs modality. If you're viewing a different component it should render new docs and scroll you.

> For every COMPONENT in the UI, clicking on the component automatically navigates to its first story. This is a controversial change, but it addresses the "extra click" issue raised by a lot of users, and which will get worse when we add doc-only stories per above.

I used to be against this but now I agree that it's a good change in context of docs. 

> We collapse the docs-only leaf node into its corresponding group to address a special case people adding docs to the beginning of their storybook.

What does this mean? Does this have to do with the "Other" root that components get lumped into when you define a root?

**Comment by domyen** [comment]
@shilman and I discussed this in person. 

Agreed that the only changes needed are:
- Clicking on a docs-only MDX file should take you to those docs. No toolbar.
- "Primary" story takes the top position in the tree view and clicking on it takes you to the top of the page in Docs

**Comment by shilman** [comment]
ZOMG!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-beta.26 containing PR #7716 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Ooh-la-la!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-beta.28 containing PR #7719 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Corner case on load when the docs-only story is the first story:

<img width="1157" alt="Storybook" src="https://user-images.githubusercontent.com/488689/63162127-62ddce00-c054-11e9-886a-d1adc9ad6c11.png">

**Comment by shilman** [comment]
Good golly!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-beta.32 containing PR #7787 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Yee-haw!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-beta.48 containing PR #7921 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.
