### ISSUE TITLE
Cannot find module 'babel-preset-env'

### ISSUE THREAD

**Issue by amazzoccone** [storybookjs/storybook#6656]
**Describe the bug**
After slow guide for HTML, when running `npm run storybook` it throws an error:
```
ERROR in ./.storybook/config.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module 'babel-preset-env'
- Did you mean "@babel/env"?
```
After some research, i fixed with:
`npm install --save @babel/preset-env`
and add a `.babelrc` in storybook config dir with:
```
{
    "presets": [
        "@babel/env"
    ]
}
```
**To Reproduce**
1. Follow slow guide for HTML (installing babel as suggested)
2. Exec `npm run storybook`
3. See error

**Expected behavior**
It should start Storybook successfully using the docs of https://storybook.js.org/docs/guides/guide-html/

**System:**
 - OS: [MacOS]
 - Device: [Macbook Pro 2015]
 - Framework: [html]
 - Version: [5.0.10]

**Comment by Hypnosphi** [comment]
I can't reproduce it on a clean project. 
Can you please create a GitHub repo with minimal reproduction of your issue?

**Comment by amazzoccone** [comment]
Oh :/. Yeah sure. I will try to reproduce it again. Thanks @Hypnosphi !
