### ISSUE TITLE
Addon-docs: DocsPage for Vue

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#6663]
Addon-info replacement for Vue.
- [x] Title
- [x] Info/notes description
- [x] Docgen info
- [x] Source
- [x] Props
- [ ] Events / Slots #8123

**Comment by bodograumann** [comment]
Are props supported for vue, or not?

The above checklist says yes.
This says no: https://github.com/storybookjs/storybook/issues/8013
This could be interpreted either way: https://github.com/storybookjs/storybook/issues/8123
What does “WIP support” mean? https://github.com/storybookjs/storybook/tree/next/addons/docs#framework-support
This suggests addon-docs can replace the info addon: https://github.com/pocka/storybook-addon-vue-info

[Jacob](https://github.com/raihle) told me on discord, that for him it works when he installs `storybook-addon-vue-info`. I tried that but got conflicts with vue-styleguidist `<docs>` blocks.

**Comment by shilman** [comment]
@bodograumann it supports vue props, but not vue events etc. will sort it all out in the coming week.

what does `conflicts with vue-styleguidist <docs> blocks` mean? cc @elevatebart

**Comment by shilman** [comment]
@bodograumann You'll need the loader from addon-vue-info to use the Props feature of Storybook Docs, but you don't need to register the rest of the addon.

**Comment by bodograumann** [comment]
I see. So I guess I need to fix the conflict after all. Do you have any idea, why the `storybook-addon-vue-info/loader` would concern itself with the `<docs>` block anyway, @shilman ?

This is the error, that I get:
```
error  in ./node_modules/my-components/src/layout/FormRow.vue?vue&type=custom&index=0&blockType=docs

Module parse failed: Unexpected character '#' (33:0)
File was processed with these loaders:
 * ./node_modules/storybook-addon-vue-info/loader/index.js
 * ./node_modules/storybook-addon-vue-info/loader/index.js
 * ./node_modules/cache-loader/dist/cjs.js
 * ./node_modules/vue-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|
|
> ### Examples ###
|
| ```vue

 @ ./node_modules/my-components/src/layout/FormRow.vue?vue&type=custom&index=0&blockType=docs 1:0-229 1:245-248 1:250-476 1:250-476
 @ ./node_modules/my-components/src/layout/FormRow.vue
 @ ./node_modules/my-components/src/index.ts
 @ ./node_modules/storybook-addon-vue-info/loader!./node_modules/cache-loader/dist/cjs.js??ref--14-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/ts-loader??ref--14-3!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/App.vue?vue&type=script&lang=ts&
 @ ./src/App.vue?vue&type=script&lang=ts&
 @ ./src/App.vue
 @ ./src/stories/example.stories.js
 @ ./config/storybook/config.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./node_modules/@storybook/addon-docs/dist/frameworks/common/../../../vue/config.js ./config/storybook/config.js
```

Could a problem be indicated by the fact that `./node_modules/storybook-addon-vue-info/loader/index.js` is listed two times?

**Comment by shilman** [comment]
@bodograumann Is that an MDX file that's getting loaded somehow by that loader? It should only apply to `.[tj]sx?` files

Cc @Aaron-Pool

**Comment by Aaron-Pool** [comment]
@Shilman my best guess after perusing things for a few minutes is that the loader for the `<docs>` block in the `vue` SFC is creating some sort of intermediary file (I think that's what it does with style and template blocks under the hood, as well), and that file happens to be matching one of the loaders that were added by the `addon-docs` plugin.

But that could be way off base, just an initial instinct.

**Comment by bodograumann** [comment]
@shilman I’m not sure how close the styleguidist docs format and MDX are, but it is the former. I have created a sample project where I reproduce the issue: https://github.com/bodograumann/vue-storybook-docs-page-test

To narrow it further down, I changed `<docs>` to `<custom>`. The error is still there. So it is not specific to styleguidist.

From this perspective it is a problem in `storybook-addon-vue-info/loader`.

**Comment by shilman** [comment]
@elevatebart mind taking a quick look at the repro? Looks like storybook is having a hard time reading `vue-styleguidist` annotations and I don't know enough about vue to recommend a path forward.

**Comment by elevatebart** [comment]
I can and will do tonite. Which means in 5 hours.

**Comment by elevatebart** [comment]
On a side note, the problem does not seem related to annotations. It looks like reading the docs block is making it hard for the SB loader. Will investigate

**Comment by elevatebart** [comment]
There seem to be a [bug in vue-loader](https://github.com/vuejs/vue-loader/issues/1595)
As a workaround you can add an empty loader to the ressourceQuery=custom rule as explained [here](https://vue-loader.vuejs.org/guide/custom-blocks.html#custom-blocks)

**Comment by bodograumann** [comment]
Thx, the workaround works :-) @elevatebart 
Cf. https://github.com/bodograumann/vue-storybook-docs-page-test/commit/87ce1fe5789e0d96d90a6f700797559789535aba

**Comment by shilman** [comment]
Boo-yah!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-alpha.29 containing PR #8567 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by Znegl** [comment]
Does anyone has a working example with both the title, description, props and events?
I'm only able to get title and subtitle to work.

**Comment by shilman** [comment]
@Znegl are you using 5.3-beta? It's only available there.

here's an example: https://github.com/storybookjs/storybook/tree/next/examples/vue-kitchen-sink

**Comment by Znegl** [comment]
Yup, and i finally found my bug!
I was adding the `component: MyComponent` property to the export of each individual test instead of the default export of my *.stories.js files.
It all works beautiful now 🤩

**Comment by chuckmasucci** [comment]
@Znegl Can you show an example of your story and component that is working? I am in the same predicament where I see the example and code but no props or methods.

**Comment by bodograumann** [comment]
@chuckmasucci, have a look here https://github.com/Aaron-Pool/Vue-Cli-Storybook-Docs. Maybe that helps you. @Aaron-Pool posted this in https://github.com/storybookjs/vue-cli-plugin-storybook/issues/73.

**Comment by Znegl** [comment]
@chuckmasucci Sadly not, since it's a closed source corporate project on a local git server.
Did the links from @bodograumann help you? If not, I might be able to take some time look at it.

**Comment by pksunkara** [comment]
I have released https://github.com/storybookjs/vue-cli-plugin-storybook 1.2.0 which should get DocsPage working for Vue (with and w/o typescript)
