### ISSUE TITLE
Addon-docs: DocsPage for Angular

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#6664]
Addon-info replacement for Angular.
- [x] Title
- [x] Stories
- [x] Info/notes description
- [ ] Docgen info
- [x] Source
- [ ] Props

**Comment by mtuzinskiy** [comment]
@shilman  Any updates on this?  I recall you said that you've managed to make it work,  and that the first version is soon to come... That would be great :pray:

**Comment by shilman** [comment]
@mtuzinskiy check out https://github.com/storybookjs/storybook/pull/7257

**Comment by shilman** [comment]
Hurrah!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-alpha.37 containing PR #7257 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Olé!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-alpha.36 containing PR #8621 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
