### ISSUE TITLE
Can't use brandTitle with brandImage

### ISSUE THREAD

**Issue by Hypnosphi** [storybookjs/storybook#6677]
**Describe the bug**
Using `brandImage` overrides the effect of `brandTitle`

**To Reproduce**
```
addParameters({
  options: {
    theme: create({
      base: 'light',
      brandTitle: 'Title',
      brandImage: image,
    })
  }
});
```
**Expected behavior**
Both image and text are shown

https://jetbrains.github.io/ring-ui/develop-storybook

**Comment by brendonco** [comment]
how did you change the storybook logo?

**Comment by shilman** [comment]
@Hypnosphi This was a design decision. I believe if you override `brandImage` it should fill the whole space. Maybe @domyen or @ndelangen can give the rationale.

**Comment by Hypnosphi** [comment]
> This was a design decision

Can we reconsider it? Of course one can put a text in the SVG, but it complicates things a bit
