### ISSUE TITLE
Silence all the console.log noise

### ISSUE THREAD

**Issue by OwenMelbz** [storybookjs/storybook#6689]
**Is your feature request related to a problem? Please describe.**
Currently there is a massive overload of noise in the console which is very annoying as it's related to storybook and not your application, there is already a `--quite` and `--ci` flag to allow message suppression on the terminal process, however this doesn't follow through to the web ui

![Storybook](https://user-images.githubusercontent.com/1094740/56948433-077ce400-6b28-11e9-939d-468f342ff348.jpg)

**Describe the solution you'd like**
Either hook into the same quiet flag or add a way to silence the output.

**Describe alternatives you've considered**
A whole lot of `console.clears()`

**Are you able to assist bring the feature to reality?**
Potentially...

**Comment by austil** [comment]
Yes please !
This noise is so annoying that I've became a power user of the filter feature in the dev console.

**Comment by ndelangen** [comment]
A general logLevel setting would solve this.

one day monoconfig will fix this

**Comment by jmlivingston** [comment]
For what it's worth, adding `-HMR` was the easiest way for me to the filter these in Chrome.

![image](https://user-images.githubusercontent.com/1093719/58765811-b51a5300-852b-11e9-969f-13e8e1d2798a.png)

**Comment by ndelangen** [comment]
Related: #6825 

also related #6806

**Comment by akoushke** [comment]
for some reasons `loglevel` is an unknown parameter still
![Screen Shot 2019-08-13 at 10 20 20 AM](https://user-images.githubusercontent.com/14226615/62962552-02306600-bdb4-11e9-8812-e8abee858ea6.png)

**Comment by dmaksimovic** [comment]
loglevel apparently serves the purpose of controlling the build output, not console logs printed in real time in the browser.
