### ISSUE TITLE
Storybook stops working on Create-react-app (CRA) after ejecting

### ISSUE THREAD

**Issue by kluplau** [storybookjs/storybook#6690]
**Describe the bug**
Storybook stops working, after ejecting CRA. Gives `Module parse failed: Unexpected token` error.

**To Reproduce**
1. Install CRA `npx create-react-app storybook-typescript-eject --typescript` and `cd storybook-typescript-eject`.
2. Install Storybook `npx -p @storybook/cli sb init`
3. Verity it works `npm run storybook`
4. Eject `npm run eject` press `y` to confirm.
5. Change Storybook config. Replace loadStories with:
```javascript
function loadStories() {
  // automatically import all story js files that end with *.stories.tsx
  const req = require.context("../src", true, /\.stories\.tsx$/);
  req.keys().forEach(filename => req(filename));
}
```
6. Rename story file to `stories/index.stories.tsx`
7. Verify that it doesn't recognize JSX-tag. `npm run storybook`

**Expected behavior**
I expected the same config that worked before ejecting would work after.

**System:**
 - OS: MacOS Mojave and Windows 7
 - Framework: React
 - Version: Latest

**Comment by kluplau** [comment]
I think this can be achieved by updating tsconfig.json to match the one provided [in this other issue comment](https://github.com/storybooks/storybook/issues/4253#issuecomment-426435162).

**Comment by mrmckeb** [comment]
The CRA config doesn't support ejection right now, you'd need to write your own config in that case - as we no longer have a reliable source.

**Comment by mrmckeb** [comment]
Let me know if you need a hand with that, in the meantime I'll close this off as it's expected behaviour.

Also, consider forking `react-scripts` over ejection.

**Comment by Dergash** [comment]
Hello! I've encountered the similiar issue and based on @mrmckeb response about separate configuration drafted a configuration that gave me the same behaviour which I had before ejecting CRA: https://github.com/storybookjs/presets/issues/72#issuecomment-584284246
Hope it'll help someone who is in the same situation
