### ISSUE TITLE
"No panels available" taking space for no reason

### ISSUE THREAD

**Issue by amypellegrini** [storybookjs/storybook#6699]
**Describe the bug**
There is a section below the preview screen intended to have additional panels which at the moment I'm not in the need of using.

This panel cannot be collapsed, it doesn't disappear on its own, and the information "No panels available" is not particularly useful.

This wouldn't be a problem if it panel could be somehow dismissed, but as it is now, it makes it very uncomfortable to work with the console open, as multiple menus end up taking too much space, and this makes difficult to work on use cases involving a large screen.

I've been working out through this by opening the container iframe in a new tab, but this is hacky at best, as it is not the default behavior of the application, nor an available option/feature in the UI.

**To Reproduce**

1. Setup a Storybook with at least one story and no additional panels.
2. Using the same screen, open the dev tools.

**Expected behavior**
If no panels are available to show, the panel shouldn't even appear at all, allowing the use of the extra available screen space.

**Screenshots**

<img width="1279" alt="Screenshot 2019-05-01 at 10 53 11" src="https://user-images.githubusercontent.com/583564/57012665-97419180-6bff-11e9-84bb-d89286b64599.png">

**Code snippets**
If applicable, add code samples to help explain your problem.

**System:**
Agnostic

**Additional context**
I know I'm being picky here, and the rationale behind these decisions is not straight forward, but I wanted to put my grain of sand because I think SB is a great tool, and this could add value to dev experience.

**Comment by amypellegrini** [comment]
Sorry, digging a bit further I found this:

https://github.com/storybooks/storybook/issues/1817#issuecomment-327931977

Which means that there is a setting I can use to hide that, I'll give it a try and in case close this issue.

Thanks!

**Comment by shilman** [comment]
@amypellegrini https://storybook.js.org/docs/configurations/options-parameter/ see `showPanel`

**Comment by amypellegrini** [comment]
Thanks @shilman! Should we close this ticket or are you considering the possibility of having the panel removed by default if there is no content to show, without the need of config?

**Comment by shilman** [comment]
Let's keep the issue open.

I don't want to hide the panel because addons are a powerful part of the Storybook ecosystem and I want them to be discoverable.

I think we could improve the empty panel to the tune of:

```
**No addons found**

[Learn more about addons](...)
[Hide this panel with `showPanel: false` in your Storybook config](...)
```

What do you think?

As an aside, I noticed you're using an old version of Storybook. v5 allows you to hide that panel by clicking on the X which is a small improvement.

**Comment by amypellegrini** [comment]
Seems legit, having a hint there with references to the docs and config should be enough.

We've just updated to latest Storybook today :)

**Comment by shilman** [comment]
> We've just updated to latest Storybook today :)

Hooray! :tada:

Thanks for raising this @amypellegrini, hope we can get to it soon!

**Comment by shilman** [comment]
I believe the panel was removed in 5.2.0 when there are no addons. 😕 

I'd like to add it back per the discussion above, so keeping this issue open for that. 😁

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if this is still relevant in SB 7.x.
