### ISSUE TITLE
Can the H3 tag be removed in the PropTypes section of the add-info addon?

### ISSUE THREAD

**Issue by GavBaros** [storybookjs/storybook#6701]
[
<img width="825" alt="Screen Shot 2019-05-01 at 12 20 47" src="https://user-images.githubusercontent.com/30755017/57015339-4e440a00-6c0c-11e9-886e-99b5d0d62f0f.png">
](url)

The documentation for handling this is quite poor unfortunately, I was wondering if it is possible to change the highlighted text or even delete it?

FYI I am using the `withInfo` method from `@storybook/addon-info`.

My `.addParameters` method within `storiesOf` is: 

```sh
.addParameters({
    info: {
      TableComponent: () => PropTable(propTableData),
    }
  })
```
`PropTable` is just a component and cannot affect the H3 tag in any way (which looks hardcoded).

Thanks.

**Comment by shilman** [comment]
Storybook docs will replace addon-info and will be super configurable (and pretty much better in every way). Check out the announcement https://medium.com/storybookjs/storybook-docs-sneak-peak-5be78445094a and discussion in the #dosc-mode channel on our discord https://discord.gg/UUt2PJb
