### ISSUE TITLE
How to modify index.html

### ISSUE THREAD

**Issue by Peterabsolon** [storybookjs/storybook#6704]
I'm using React Portals to render modals into a node I specified in my index.html, called 'portal-root'.

This of course fails inside Storybook because there is no such element.

I tried to create this element and set its ID in loadStories(), through decorator or inside my modal constructor. None of these methods worked.

How can I achieve this? Thanks!

**Comment by shilman** [comment]
Could you add a decorator to your story and create the id in there instead?
