### ISSUE TITLE
Addon-docs: Vue inline rendering support

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#6706]
Currently Docs for React has an option `inlineStories: true` that causes stories to be rendered inline in MDX rather than in iframes. This has performance and tool compatibility benefits (e.g. vue-devtools https://github.com/storybooks/storybook/issues/1708). As an optimization over the baseline behavior, we should support inline stories for Vue.

Steps to get this working:
1. Modify `inferInlineStories` to return true for `vue`: https://github.com/storybookjs/storybook/blob/next/addons/docs/src/blocks/Story.tsx#L23
2. This will trigger the code to render an `InlineStory`: https://github.com/storybookjs/storybook/blob/7117-undo-source-loader-examples/lib/components/src/blocks/Story.tsx#L35
3. Probably need to add a global decorator such that when `storyFn` is called, it first calls the decorator to render the story inside React using something like `vuera`: https://github.com/akxcv/vuera

To make all of this work properly, you should understand Vue and deeply understand the Vue render function as defined here: https://github.com/storybookjs/storybook/blob/next/app/vue/src/client/preview/render.js#L20

Also note: there's an effort to redefine all of the "framework" support in Storybook as decorator functions, with the first example here: https://github.com/storybookjs/storybook/pull/6826. This approach above might be quite related to that.

**Comment by elevatebart** [comment]
This is exciting !!!

**Comment by shilman** [comment]
Yowza!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-alpha.15 containing PR #7929 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Whoopee!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-alpha.18 containing PR #8403 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

**Comment by shilman** [comment]
Ermahgerd!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-alpha.19 containing PR #8415 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

**Comment by shilman** [comment]
Ooh-la-la!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-alpha.20 containing PR #8419 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.
