### ISSUE TITLE
Copy link to individual story

### ISSUE THREAD

**Issue by amelia-lewis** [storybookjs/storybook#6708]
**Is your feature request related to a problem? Please describe.**
With my current design system docs setup, I regularly find myself needing to copy URLs for individual stories. 

**Describe the solution you'd like**
Really happy the "share" button is there, but it would be great if there was a direct copy URL to clipboard function rather than having to open the link and copy from the address bar.

**Describe alternatives you've considered**
Even just being able to right click like a regular link would help.

**Are you able to assist bring the feature to reality?**
No (sorry!!)

**Additional context**
<img width="124" alt="Screen Shot 2019-05-01 at 4 15 11 PM" src="https://user-images.githubusercontent.com/3347887/57083215-2dd88600-6cc6-11e9-999d-0b97de68e09b.png">

**Comment by shilman** [comment]
Thanks @amelia-lewis ! We'll get on this soon

**Comment by yozaam** [comment]
> Thanks @amelia-lewis ! We'll get on this soon

Hey shilman, is it alright if I work on this?

**Comment by shilman** [comment]
@yozaam that would be great! PRs welcome!

**Comment by shilman** [comment]
Yay!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.1.0-rc.5 containing PR #6719 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

**Comment by amelia-lewis** [comment]
woohoo!! thanks guys!
