### ISSUE TITLE
Knobs with angular component not updating

### ISSUE THREAD

**Issue by blemaire** [storybookjs/storybook#6709]
**Describe the bug**
When using props on a component, the values of the knobs are not available in the component.

**To Reproduce**
See code snippet

**Expected behavior**
I expect the value within the component to be updated when I type in the `text` knob

**Screenshots**

**Code snippets**
```js
import {storiesOf, moduleMetadata} from '@storybook/angular';
import {Component, Input} from '@angular/core';
import {withKnobs, text} from '@storybook/addon-knobs';
import {FormsModule} from '@angular/forms';

@Component({
  selector: 'simple-component',
  template: `
    {{ name || 'default' }}
    <input type="text" [(ngModel)]="name" />
  `,
})
export class SimpleComponent {
  @Input() name: string;
}

storiesOf('component', module)
  .addDecorator(withKnobs)
  .addDecorator(
    moduleMetadata({
      imports: [FormsModule],
      declarations: [SimpleComponent],
    }),
  )
  .add('notWorking', () => ({
    component: SimpleComponent,
    props: {
      name: text('Name', 'outer name'),
    },
  }));
```

**System:**
 - OS: [MacOS]
 - Browser: [chrome]
 - Framework: [angular]
 - Addons: 
@storybook/addon-knobs
@storybook/addon-notes
@storybook/addon-viewport
@storybook/addon-storysource
storybook-addon-designs
 - Version: 
"@storybook/addon-actions": "^5.0.11",
"@storybook/addon-centered": "^5.0.11",
"@storybook/addon-knobs": "^5.0.11",
"@storybook/addon-notes": "^5.0.11",
"@storybook/addon-storysource": "^5.0.11",
"@storybook/addon-viewport": "^5.0.11",
"@storybook/angular": "^5.0.11",
storybook-addon-designs: 5.0.0

Below I expected to see 'Updated' (which is the value typed in the knob)next to the input but it still shows the default value
![image](https://user-images.githubusercontent.com/7140322/57122288-d812e500-6d7c-11e9-8eb8-8a5901eb97a4.png)

**Comment by blemaire** [comment]
Hey, has anybody had a chance to look at this? It's not blocking as we can wrap the component in a template but it's extra effort to duplicate the bindings when they're already there.
Thanks a lot

**Comment by QuantariusRay** [comment]
I'm also seeing this issue...

**Comment by michahell** [comment]
also having this problem

**Comment by Silverium** [comment]
Hi all, 

I've found a workaround. **Use functions!!**
As you may know, React is all about functions and so are knobs, with this approach, you have instant responsiveness:
```js
...
  .add('your story here', () => ({
    template: `
        <your-component-here
                [customHeight]="height()">
        </your-component-here>
    `,
    props: {
      height: () => number('height', 50)
    },
  }));
```

**Comment by allsteps** [comment]
The issue is still there.
