### ISSUE TITLE
Theme isn't applied when publishing statically

### ISSUE THREAD

**Issue by kevinSuttle** [storybookjs/storybook#6713]
**Describe the bug**

**To Reproduce**
1. Apply a custom theme, with a `dark` base
2. Run `build-storybook`
3. Open storybook-static/index.html in the browser
4. See that the theme is not applied

**Expected behavior**
Theme to be maintained

**System:**
 - OS: [e.g. iOS, Windows10, MacOS] MacOS 10.14.4 (18E226)
 - Device: [e.g. iPhoneX, Macbook Pro 2018]  MacBook Pro (15-inch, 2017)
 - Browser: [e.g. chrome, safari] Firefox 67.0b14 (64-bit)
 - Framework: [e.g. react, vue, angular] React v16.8.6
 - Addons: [if relevant]
 - Version: [e.g. 4.0.0] 5.0.9

**Comment by kevinSuttle** [comment]
Server running: 

<img width="400" alt="Image 2019-05-03 at 2 09 30 PM" src="https://user-images.githubusercontent.com/95672/57156899-335ccb80-6dad-11e9-94c4-690337fe4a9d.png">

Static build:
<img width="400" alt="Image 2019-05-03 at 2 09 06 PM" src="https://user-images.githubusercontent.com/95672/57156910-3ce63380-6dad-11e9-9a88-a138c0f0f48a.png">

**Comment by shilman** [comment]
There's some trickiness with how themes are applied in the web UI (cached in localstorage). My guess is that this trickiness broke the static build.

@kevinSuttle what app are those screenshots from?

**Comment by kevinSuttle** [comment]
Firefox. I’ve noticed a _lot_ of sync latency, colors not even being applied, etc. 

I wonder if it has to do with this, which I’m doing:
> When setting a theme, set a full theme object. The theme is replaced not combined.

However, I’ve seen it work. So, this may be on me. :)

**Comment by kevinSuttle** [comment]
I noticed the `` [environment variable](https://storybook.js.org/docs/configurations/env-vars/#build-time-environment-variables) could be used at build time, but alas, the theme still is not applied when statically exporting.

**Comment by shilman** [comment]
@kevinSuttle Is this is still causing you problems?

**Comment by kevinSuttle** [comment]
As of beta 18 (maybe earlier), it is not! Thanks for the reminder!
