### ISSUE TITLE
Error caught when start storybook from angular project without 'architect.build' options

### ISSUE THREAD

**Issue by seokju-na** [storybookjs/storybook#6735]
**Describe the bug**

https://github.com/storybooks/storybook/blob/next/app/angular/src/server/angular-cli_config.js#L53

In above code, storybook always require `architect.build` options. This will work most of angular pojects, but when your making library which build from [ng-packagr](https://github.com/ng-packagr/ng-packagr), these options can be empty.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System:**
 - OS: [e.g. iOS, Windows10, MacOS]
 - Device: [e.g. iPhoneX, Macbook Pro 2018]
 - Browser: [e.g. chrome, safari]
 - Framework: [e.g. react, vue, angular]
 - Addons: [if relevant]
 - Version: [e.g. 4.0.0]

**Additional context**

**Comment by shilman** [comment]
Yee-haw!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-beta.3 containing PR #6737 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.
