### ISSUE TITLE
About page has an invisible div that prevents user interactions

### ISSUE THREAD

**Issue by kaiyoma** [storybookjs/storybook#6741]
**Describe the bug**
The About page has an invisible div that prevents user interactions. You can't scroll or select text.

**To Reproduce**
1. Go to the About page and try scrolling or selecting text.

**Code snippets**
The div with classname `css-sqdry3` seems to be causing the problems. If you delete this element from devtools, the page starts working normally.

**System:**
 - OS: Windows 10
 - Browser: Chrome, Firefox, Edge
 - Version: 5.1.0-alpha.39

**Comment by kaiyoma** [comment]
AFAIK, this is still an issue.

**Comment by kaiyoma** [comment]
This also affects the "Keyboard shortcuts" page. You can't scroll down to see all the entries.

**Comment by kaiyoma** [comment]
Still an issue.

**Comment by lonyele** [comment]
@kaiyoma Hey! I found where the bug is, I will make a PR that fixes this issue very soon(in 1day) Please wait until then

**Comment by shilman** [comment]
Good golly!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-alpha.40 containing PR #7241 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
