### ISSUE TITLE
show real souce code instead of the third party lib HoC wrapper

### ISSUE THREAD

**Issue by nianiaJR** [storybookjs/storybook#6744]
### support request summary
I use a HOC from the third party lib，and the source code always show the HoC wrapper not the real source code. Even when I use the `addDecorator`. I find all existed suggestions in issues are about hoc defined by themselves (such as [issue 938](https://github.com/storybooks/storybook/issues/938l) . How about third party hoc solution?

### Steps to reproduce
my  code:
```js
import { Form } from 'antd' // HOC from third party lib
import { RealComponent } from './RealComponent'; // my own component 
const FormDecorator = storyFn => {
  const Component = Form.create()(storyFn)
  return <Component />
}
storiesof('Test', module)
   .addDecorator(FormDecorator)
   .add('demo', (props) => {
        ......
       <RealComponent config={config}> form={props.form} / >
   })
```
expected source code show:
```js
<RealComponent config={config} form{props.form />
```
but real show:
```js
<Form(WrappedComponent)/>
```

I knew there were many existed issues about the  similar problem, but I can't find solution about this one. Thx.
### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react ^5.0.3
- @storybook/addon-info ^5.0.6

**Comment by shilman** [comment]
Dupe to #4801?

**Comment by nianiaJR** [comment]
> Dupe to #4801?

Maybe, I think they are not the same problem. Actually, I also have an another gloabl decorator which use styled-components like this:
```javascript
addDecorator(withInfo({
  header: false,
  inline: true
}))
const StyledDemo = styled.div`
  background: #fff;
  padding: 30px;
  #story-root {
    text-align: center;
  }
  h3 + table {
    width: 100%;
    th, tr, td {
      padding: 8px;
      border: 1px solid #eee;
      border-collapse: collapse;
    }
  }
`
const ComponentDecorator = storyFn => <StyledDemo>{storyFn()}</StyledDemo>
addDecorator(ComponentDecorator)
```
It's just like the code in [#4801](https://github.com/storybooks/storybook/issues/4801)， but I don't have the problem he met. I have trouble in using the thrid party lib HoC which wrap my real component      
to show the `<Form(WrappedComponent)/>` instead of real component code. Thx.

**Comment by nianiaJR** [comment]
On the other way, can I set the source code or propsTypes mannually?
such as:
```javascript
withInfo({
      sourceCode: "source code show here...",
      propsTable: ....
})
```

**Comment by shilman** [comment]
@nianiaJR Good idea to allow overriding the source code. I'm writing a long-overdue replacement to `addon-info` and will make it easy & "regular" to override all of the information that is shown. Thanks for the inspiration.

**Comment by nianiaJR** [comment]
@shilman so expecting ^-^

**Comment by shilman** [comment]
Here's the sneak peak: https://medium.com/storybookjs/storybook-docs-sneak-peak-5be78445094a

Adding the `addon-info` functionality this week!

**Comment by shilman** [comment]
@nianiaJR this is currently working well in `addon-docs` thanks to the storysource addon

**Comment by nianiaJR** [comment]
@shilman That's so great. Thanks agiain.

**Comment by nianiaJR** [comment]
@shilman l meet a problem, in the [addon-docs](https://www.npmjs.com/package/@storybook/addon-docs) description:
```
// .storybook/presets.js
module.exports = ['@storybook/addon-docs/presets/react'];
```
When I npm installed the `addon-docs`, I can't find the presets directory, it doesn't exist.

**Comment by shilman** [comment]
This is an old README. Use the technical preview guide linked at the top. And the latest README is here https://www.npmjs.com/package/@storybook/addon-docs/v/5.2.0-alpha.12

**Comment by nianiaJR** [comment]
It seems that I can't find

**Comment by nianiaJR** [comment]
as the [doc](https://www.npmjs.com/package/@storybook/addon-docs/v/5.2.0-alpha.12) say: 
```javascript
// config .storybook/preset.js
module.exports = ['@storybook/addon-docs/react/preset'];
```
But I can't find the `react` directory in `@storybook/addon-docs` module too. Do I misunderstand this doc?

**Comment by shilman** [comment]
@nianiaJR Which version of addon-docs is that? Please upgrade to the latest release, alpha.19. This is a "technical preview" release, as explained in bold letters at the top of the Google doc. If you want something stable, please wait for the stable release.

**Comment by nianiaJR** [comment]
@shilman My version is 5.2.0-alpha.0. I get it and thanks for your patience.
