### ISSUE TITLE
maxPropObjectKeys not being applied to objects within an array prop in the Info addon 

### ISSUE THREAD

**Issue by carlrip** [storybookjs/storybook#6754]
If you have a React component prop that is an array of objects, only 3 props within the objects is shown in the JSX preview. Setting `maxPropObjectKeys` doesn’t seem to effect this.

An example story is below:
```
storiesOf("List", module)
  .addDecorator(withInfo)
  .add(
    "demo",
    () => (
      <List
        data={[
          { name: "Fred", surname: "Smith", category: "A", subCategory: "B" }
        ]}
      />
    ),
    {
      info: {
        maxPropObjectKeys: 100
      }
    }
  );
```

This shows a `List` component that has a `data` array prop. The first object in the array has 4 props which is greater than the default `maxPropObjectKeys` setting which seems to be 3.

The `maxPropObjectKeys` setting is set to 100 for this story.

However, the `subCategory` prop doesn't show in the JSX preview:
![image](https://user-images.githubusercontent.com/10935715/57449538-18c69e80-7254-11e9-82c6-b45d861ce610.png)

I would expect the `subCategory` prop show in the JSX because the `maxPropObjectKeys` should be applied to objects within array props

**Comment by shilman** [comment]
@carlrip I think `maxPropObjectKeys` is currently an option for the PropsTable. Applying it to the source display makes sense too. PRs welcome.
