### ISSUE TITLE
"About Your Storybook" version upgrade recommendation is wrong when using `@storybook/react-native-server@5.1.0-beta.0``

### ISSUE THREAD

**Issue by alechp** [storybookjs/storybook#6768]
**Describe the bug**
@storybook/react-native-server v `5.1.0-beta.0` simply doesn't work. Will file a separate issue to address that.

This is a non-breaking bug. Filing because it causes confusion. If nothing else, figure that it'll help save someone else time.

 Storybook recommends that you update your "storybook" version even if you have already done so... What it really means to say is you should update @storybook/react-native-server _and_ @storybook/react-native to `5.1.0-beta.0`.

> Also worth noting that this issue is persistent between @storybook/react-native v `5.1.0-beta.40` and `5.1.0-beta.0`

**To Reproduce**
0. Setup expo/storybook project with the following deps:
<img width="952" alt="Screen Shot 2019-05-12 at 10 52 57 AM" src="https://user-images.githubusercontent.com/3058939/57586034-810bbf00-74a4-11e9-97c2-7aee08000985.png">

1. Go to 'About Your Storybook' and you should see:
<img width="952" alt="Screen Shot 2019-05-12 at 10 54 07 AM" src="https://user-images.githubusercontent.com/3058939/57586039-8a952700-74a4-11e9-9f31-a4038a840f39.png">

**Expected behavior**
Version recommendations for [@storybook/cli](https://www.npmjs.com/package/@storybook/cli) are clearly separated from [@storybook/react-native-server](https://www.npmjs.com/package/@storybook/react-native-server)

You can see that Storybook thinks its version is `5.1.0-alpha.7` and is recommending you to update `@storybook/cli` to `5.1.0-beta.0`. But in reality, `@storybook/cli` already has version `5.1.0-beta.0` installed. `@storybook/react-native-server` on the other hand currently has `5.1.0-alpha.7` installed. 

**Temporary Solution**
Upgrade `@storybook/react-native-server` to version `5.1.0-beta.0`. 

**Ideal Solution**
The `About Your Storybook` page update notice is more clear.

**Comment by shilman** [comment]
Is it still a problem when all your deps are the same version? They should be.

**Comment by alechp** [comment]
@shilman Updated everything to rc.4 and it seems to have resolved the issues I was having before.

Repo as reference:
https://github.com/servexyz/react-native-expo-storybook-v5

**Comment by shilman** [comment]
Thanks for the followup @alechp 👋
