### ISSUE TITLE
`@storybook/react-native-server@5.1.0-beta.0` is broken 

### ISSUE THREAD

**Issue by alechp** [storybookjs/storybook#6769]
**Describe the bug**

1. `@storybook/react-native-server` is broken in `@storybook/react-native-server@5.1.0-beta.0`. You can tell because none of the stories are displaying in the navbar.

2. `About Your Storybook` has a style issue
> this is a small, related, styling bug that was introduced in `@storybook/react-native-server@5.1.0-beta.0` and is loosely related to https://github.com/storybooks/storybook/issues/6768

<img width="952" alt="Screen Shot 2019-05-12 at 11 04 15 AM" src="https://user-images.githubusercontent.com/3058939/57586191-422b3880-74a7-11e9-98b2-51c85e8a30b4.png">

* Storybook still works in `@storybook/react-native@5.1.0-beta.0`. Simulator screenshot:
<img width="545" alt="Screen Shot 2019-05-12 at 11 26 01 AM" src="https://user-images.githubusercontent.com/3058939/57586297-ed88bd00-74a8-11e9-94d0-4170dfb65e0a.png">

**To Reproduce**
1. Update `@storybook/react-native-server` from version `5.1.0-alpha.7` to `5.1.0-beta.0`
2. Re-run your project & open storybook
3. Notice that the stories section is completely blank.

**Expected behavior**
`@storybook/react-native@5.1.0-beta.0` and `@storybook/react-native-server@5.1.0-beta.0` work together

**Screenshots**
* React Native Server version options:
<img width="1792" alt="Screen Shot 2019-05-12 at 11 16 39 AM" src="https://user-images.githubusercontent.com/3058939/57586208-99310d80-74a7-11e9-9e8e-68a2b5d116b9.png">

* Evidence that `@storybook/react-native-server` v `5.1.0-alpha.7` was working:
<img width="952" alt="Screen Shot 2019-05-12 at 10 45 06 AM" src="https://user-images.githubusercontent.com/3058939/57586229-c54c8e80-74a7-11e9-8288-0a495035e2d1.png">

* Usually when stories are "pending" (usually because the Simulator hasn't been opened yet - or it has been and storybook hasn't been refreshed since), then `@storybook/react-native-server` will simply show greyed-out divs as placeholder rows in the stories section, like so:
<img width="1680" alt="Screen Shot 2019-05-12 at 10 50 27 AM" src="https://user-images.githubusercontent.com/3058939/57586241-eca35b80-74a7-11e9-8328-6111bf94b90a.png">

* In the newest version, you can tell there's something different because now "pending" stories are simply non-existent:
<img width="952" alt="Screen Shot 2019-05-12 at 11 04 15 AM" src="https://user-images.githubusercontent.com/3058939/57586353-a3540b80-74a9-11e9-9ebf-9b1632f7ece8.png">

**Quick Fix**
Reverting `@storybook/react-native-server` to `5.1.0-alpha.7`
Since this quick fix exists, might be worth asking: why did I update the version in the first place? That was to address the issue created by the incorrect version recommendation in `About Your Storybook` as documented here: https://github.com/storybooks/storybook/issues/6768

**Ideal Fix**
`@storybook/react-native@5.1.0-beta.0` and `@storybook/react-native-server@5.1.0-beta.0` work together.

**Comment by benoitdion** [comment]
hey @alechp, I'm unable to reproduce this. Do you mind testing again on the latest rc?

**Comment by alechp** [comment]
@benoitdion Updated everything to rc.4 and it seems to have resolved the issues I was having before.

Repo as reference:
https://github.com/servexyz/react-native-expo-storybook-v5
