### ISSUE TITLE
Migrating to v5, addons throw error

### ISSUE THREAD

**Issue by mglavall** [storybookjs/storybook#6786]
### Bug or support request summary
We have migrated from 4.1.11 to 5.0.11, but we are getting the following error.
![image](https://user-images.githubusercontent.com/23035545/57712167-76058a00-7670-11e9-95a9-c63a5bece23e.png)
It seems related to #5645 , but in our case, the addons are up to date. Is there something that we are missing?

### Please specify which version of Storybook and optionally any affected addons that you're running
    "@storybook/addon-actions": "^5.0.11",
    "@storybook/addon-info": "^5.0.11",
    "@storybook/addon-knobs": "^5.0.11",
    "@storybook/addons": "^5.0.11",
    "@storybook/cli": "^5.0.11",
    "@storybook/react": "^5.0.11",
    "@storybook/react-native": "^4.1.18",

**Comment by ndelangen** [comment]
Addon info requires a modern version of react (16.8), updating to the latest react will fix this.

**Comment by mglavall** [comment]
I just updated react and react-dom like you suggested, the error is still there

**Comment by ndelangen** [comment]
@mglavall thanks for reporting back, can you share your project so I can assist?

**Comment by mglavall** [comment]
I'm afraid I can't, it's a private repo. More info about this: removing addon-info from the project doesn't solve the problem, then it logs the same error but with addon-knobs. 

If there is any other thing that I can share to make this easier, please let me know. Maybe the webpack.config?

**Comment by ndelangen** [comment]
@mglavall There isn't much I can do without being able to reproduce the error.

I'm 99% certain it's a react version issue. I assume you've tried to remove any lockfiles & node_modules after upgrading?

If using yarn, try `yarn upgrade-interactive latest`?

But perhaps you could also attempt to upgrade all storybook packages to the `5.1.0-beta.1`?

**Comment by ndelangen** [comment]
We may have fixed the issue there already.

**Comment by mglavall** [comment]
I updated all my storybook packages to `5.1.0-beta.1`, now the build is not finishing because there is an error with the style-loader, something similar to this: https://github.com/webpack-contrib/css-loader/issues/362

I'll try to fix it and find more about this, I'll report back if I come up with a solution.

**Comment by ndelangen** [comment]
start storybook with the `--debug-webpack` flag.

This should output the full webpack output being used. You can inspect that for abnormalities.
