### ISSUE TITLE
The first knobs button with a title that contains brackets does not render.

### ISSUE THREAD

**Issue by jung-han** [storybookjs/storybook#6790]
**Describe the bug**
Hi, I am currently using a storybook using the knobs button in `^5.1.0-alpha.40` version.

I found a bug ...
The first knobs button with a title that contains brackets does not render.
However, if the first button is exposed, it will render normally.

**Expected behavior**
The text must be fully exposed, no matter what text is entered.

**Code snippets**

```js
// not work
button('selection({ start: [1, 2], end: [3, 4] })', () =>
  app.selection({ start: [1, 2], end: [3, 4] })
);

// work
button('test', () => console.log('test'));
button('selection({ start: [1, 2], end: [3, 4] })', () =>
  app.selection({ start: [1, 2], end: [3, 4] })
);
```

**Screenshots**

// first Code snippets code
![image](https://user-images.githubusercontent.com/35371660/57749149-ddc2e000-7717-11e9-9fd1-adaf6b1de3c0.png)

// second Code snippets code
![image](https://user-images.githubusercontent.com/35371660/57749130-c683f280-7717-11e9-8ad5-e312493205de.png)

**System:**
 - OS: OSX
 - Device: macbook pro 2018
 - Browser: chrome
 - Framework: preact
 - Addons: ^5.1.0-alpha.40
 - Version: ^5.1.0-alpha.40

**Additional context**
Thanks!

**Comment by leoyli** [comment]
related #6526.
