### ISSUE TITLE
Knobs panel renders off screen

### ISSUE THREAD

**Issue by leanne2** [storybookjs/storybook#6796]
**Describe the bug**
When using knobs panel the panel visually diappears despite all set up being correct. What is actually happening is then panel is rendering off screen. This can be seen by searching for `react-draggable` css class in the Chrome Dev Tools elements panel. This shows the panel is renderd but is rendered off screen at the top

**To Reproduce**
I am not entirely sure what triggers this, possibly a screen or browser window size change. It happens twice in two days

**Expected behavior**
It should not be possible for the knobs panel or its draggable edge to render off the visible part of the browser window

**Screenshots**
You can see the knobs panel is off screen
<img width="1273" alt="Screenshot 2019-05-16 at 11 16 29" src="https://user-images.githubusercontent.com/39951938/57846425-13c19c00-77cc-11e9-907b-98e1e790e17a.png">

**System:**
 - OS: MacOS
 - Device: Macbook Pro 2016
 - Browser: Chrome
 - Framework: Rect
 - Addons: Knobs
 - Version: 5.0.11;

**Comment by shilman** [comment]
Is it only knobs or is it all addons? Is it a duplicate of this? https://github.com/storybooks/storybook/issues/6343

**Comment by leanne2** [comment]
@shilman I don't use other addons so cannot say if it is only knobs. Also it seemed today to simply hide the panel without out any reszing of the window. The browser window had been idle for a while, i refocusd it, the UI flickered (*maybe* due to a hot reload), then the panel disappears. To get it to re-appear i have to click "Change Addons orientation"

**Comment by shilman** [comment]
@leanne2 try doing `localStorage.clear()` in your browser console and then hard refresh?
