### ISSUE TITLE
Unable to switch theme back to "light" 

### ISSUE THREAD

**Issue by domyen** [storybookjs/storybook#6798]
**Describe the bug**
I'm unable to switch the theme back to "light" after using the dark theme.  The only resolution is the `localstorage.clear()` hack.

**To Reproduce**
1) Clone the [Storybook Design System](https://github.com/storybooks/design-system) project. 
2) Go to SB config.js and `import { themes } from '@storybook/theming';`
2) Set `options: { theme: themes.dark }` to show the dark theme
3) Comment out above and refresh. It shows dark theme (but should go back to light). And when I set it manually to `themes.light` it does not refresh either.

**Expected behavior**
When I do not set a theme it should reset the theme. 

**Screenshots**
[**Here's a 📹video of this behavior.**](https://www.dropbox.com/s/sdna1pu6a40952w/theme-not-updating.mp4?dl=0)

**System:**
 - OS: Mac OS
 - Device: Macbook Pro 2018
 - Browser: Chrome, safari
 - Framework: React
 - Version: 5.2.x

**Comment by Saifadin** [comment]
Happens for me too. The only difference is, that I work on a React based Storybook, that has the dark theme and i also use an HTML based Storybook. When switching between them, only localStorage.clear works and i loose all other customisations i made to my storybook.

**Comment by ndelangen** [comment]
@Saifadin one recommendation I can give right now, is to not have the 2 storybooks share the same port.

I'll implement #6806 (hopefully soon), which will remove the need to cache the theme in localStorage all-together.

**Comment by patrick-radulian** [comment]
Is there any update on this issue? I looked into theming a react storybook and followed the documentation / tutorial, using the dark theme at first.
To explore possibilities I then created a custom theme and then tried to revert that before implementing more serious theme changes - that's when it broke for me as well, keeping parts of the light theme, parts of the dark theme and parts of my placeholder-custom-theme.

**Comment by shilman** [comment]
@patrick-radulian yes there's been an update here.

@ndelangen has updated the recommended theming API here:

https://github.com/storybookjs/storybook/blob/next/docs/src/pages/configurations/theming/index.md#global-theming

I don't know if this will fix the issue directly, or whether it's part of a longer-term breaking change that won't be usable until 6.0. In the meantime, the workaround is to run on different ports. @ndelangen can yo comment?

**Comment by ndelangen** [comment]
I removed the code that persists the theme, because the FOUC should no longer happen.

**Comment by ndelangen** [comment]
@patricklafrance woulds you be able to review/test?

**Comment by patrick-radulian** [comment]
Sorry for the late reply

I've updated to storybook 5.3.0-beta.25 (could not updated to beta.30 because of a problem with peer-dependencies right now, as it seems) but the situation is still the same.
Changing the theme in the options parameter requires **localStorage.clear()** to be recodnized.

The same thing is going on with other options apparently - I've tried playing with the **panelPosition** option, setting it to **right** and back to **bottom** - also this is only updated after clearing the localStorage.

**Comment by shubhamholkar007** [comment]
is there any simple option than creating new simple theme ?

**Comment by shilman** [comment]
This is getting fixed in https://github.com/storybookjs/storybook/pull/9076 which will hopefully be merged/released soon.

**Comment by shilman** [comment]
Yowza!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-alpha.28 containing PR #9076 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
