### ISSUE TITLE
build-storybook blank screen because only one __webpack_require__(x) gives empty object 

### ISSUE THREAD

**Issue by n44ps** [storybookjs/storybook#6799]
**Describe the bug**
When I start Storybook, I get all my previews and everything's fine.
But when I try to build, the only thing I get is a blank page with "No Preview".

I get a `TypeError: Cannot read property 'colors' of undefined` in the console.

I tried to search further why, and played with the bundle from webpack.
I found the culprit which is one `__webpack_require__(2)` that gives an empty object `{}` but can't understand why.

**To Reproduce**
1. `yarn storybook` OK
2. `yarn build-storybook` KO
2. See error KO
4. Cry
5. Check on webpack bundle the output

**Expected behavior**
It should build and display previews, just like the start-storybook.

**Screenshots**

**Code snippets**

```javascript
2: function(module, __webpack_exports__, __webpack_require__) {
      'use strict';
      var theme = __webpack_require__(28); // got full object
      __webpack_require__(4), __webpack_require__(9), __webpack_require__(15);
      __webpack_require__.d(__webpack_exports__, 'c', function() {
        return theme.e;
      }),
        __webpack_require__.d(__webpack_exports__, 'd', function() {
          return theme.f;
        }),
        __webpack_require__.d(__webpack_exports__, 'a', function() {
          return theme.b;
        }),
        __webpack_require__.d(__webpack_exports__, 'b', function() {
          return theme.c;
        });
    },
```

This one is working :

```javascript
4: function(module, __webpack_exports__, __webpack_require__) {
      'use strict';
      var templateObject_1,
        tslib_es6 = __webpack_require__(3),
        react = __webpack_require__(0),
        react_default = __webpack_require__.n(react),
        styled_browser_esm = __webpack_require__(6),
        src_0 = __webpack_require__(2), // got my full object !
```

Here is the code part that is wrong :

```javascript
9: function(module, __webpack_exports__, __webpack_require__) {
      'use strict';
      var tslib_es6 = __webpack_require__(3),
        styled_browser_esm = __webpack_require__(6),
        src = __webpack_require__(2), // {} empty object
```

I export my theme like this : 

```javascript
// @root/index.ts

export {
  theme,
  themeLight,
  anchorStyle,
  breakpointsName as bs,
  GlobalStyles,
} from './theme';

export * from './components';
```

```javascript
// .babelrc
{
  "presets": ["@babel/preset-react", "@babel/preset-env"],
  "plugins": [
    "add-module-exports",
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-proposal-object-rest-spread"
  ]
}
```

```javascript
// webpack.config.js
const path = require('path');
const TsconfigPathsPlugin = require('tsconfig-paths-webpack-plugin');

module.exports = ({ config }) => {
  config.module.rules[0].use[0].loader = require.resolve('babel-loader');

  config.module.rules[0].use[0].options.presets = [
    require.resolve('@babel/preset-react'),
    require.resolve('@babel/preset-env'),
  ];

  config.module.rules[0].use[0].options.plugins = [
    require.resolve('@babel/plugin-proposal-object-rest-spread'),
  ];

  config.module.rules.push({
    test: /\.(ts|tsx)$/,
    use: [
      {
        loader: require.resolve('babel-loader'),
        options: {
          presets: [
            require.resolve('@babel/preset-react'),
            require.resolve('@babel/preset-env'),
          ],
          plugins: [
            require.resolve('@babel/plugin-proposal-object-rest-spread'),
          ],
        },
      },
      {
        loader: 'ts-loader',
        options: {
          transpileOnly: true,
        },
      },
      { loader: 'react-docgen-typescript-loader' },
      {
        loader: require.resolve('@storybook/addon-storysource/loader'),
        options: {
          parser: 'typescript',
        },
      },
    ],
  });
  config.resolve.plugins = [
    new TsconfigPathsPlugin({
      configFile: path.resolve(__dirname, '../tsconfig.json'),
    }),
  ];
  config.resolve.extensions.push('.ts', '.tsx', '.json');
  return config;
};

```

**System:**
 - OS: [MacOS]
 - Device: [Macbook Pro 2017]
 - Browser: [chrome]
 - Framework: [React]
 - Version: [e.g. 5.0.11]

Thank you for your help :)

**Comment by ndelangen** [comment]
@n44ps do you think you could create a reproduction repo for me to check out?

**Comment by n44ps** [comment]
Hey @ndelangen thank you for your help :) 
https://github.com/n44ps/ui-storybook

Just `yarn`
Check it works using `yarn storybook`
Then `yarn build-storybook`  :)

Thanks !

**Comment by ndelangen** [comment]
So I've run:
`yarn storybook --debug-webpack` & `yarn build-storybook --debug-webpack && npx serve ./storybook-static`

First one works fine, second one indeed gives no stories.

The problem is coming from:

```ts
// src/components/layout/Block.tsx
const Block: FC<Props> = styled(Flex)`
  ${height}
  ${space}
  background: ${theme.colors.light};
  box-shadow: ${theme.boxShadow};
  border-radius: 2px;
`;
```

`theme` is en empty object in prod mode.
It should be coming from `import { theme } from '@root';`. I'm not sure why that's be different in production mode.

Here's the webpack config in dev mode:
<details>
Preview webpack config
{ mode: 'development',
  bail: false,
  devtool: '#cheap-module-source-map',
  entry:
   [ '/Users/dev/Projects/GitHub/storybook/repro/ui-storybook/node_modules/@storybook/core/dist/server/common/polyfills.js',
     '/Users/dev/Projects/GitHub/storybook/repro/ui-storybook/node_modules/@storybook/core/dist/server/preview/globals.js',
     '/Users/dev/Projects/GitHub/storybook/repro/ui-storybook/.storybook/config.tsx',
     '/Users/dev/Projects/GitHub/storybook/repro/ui-storybook/node_modules/webpack-hot-middleware/client.js?reload=true' ],
  output:
   { path:
      '/Users/dev/Projects/GitHub/storybook/repro/ui-storybook/node_modules/@storybook/core/dist/public',
     filename: '[name].[hash].bundle.js',
     publicPath: '' },
  plugins:
   [ HtmlWebpackPlugin {
       options:
        { template:
           '/Users/dev/Projects/GitHub/storybook/repro/ui-storybook/node_modules/@storybook/core/dist/server/templates/index.ejs',
          templateContent: false,
          templateParameters: [Function: templateParameters],
          filename: 'iframe.html',
          hash: false,
          inject: false,
          compile: true,
          favicon: false,
          minify: undefined,
          cache: true,
          showErrors: true,
          chunks: 'all',
          excludeChunks: [],
          chunksSortMode: 'none',
          meta: {},
          title: 'Webpack App',
          xhtml: false,
          alwaysWriteToDisk: true },
       childCompilerHash: undefined,
       childCompilationOutputName: undefined,
       assetJson: undefined,
       hash: undefined,
       version: 4 },
     DefinePlugin {
       definitions:
        { 'process.env':
           { NODE_ENV: '"development"', NODE_PATH: '""', PUBLIC_URL: '"."' } } },
     WatchMissingNodeModulesPlugin {
       nodeModulesPath:
        '/Users/dev/Projects/GitHub/storybook/repro/ui-storybook/node_modules' },
     HotModuleReplacementPlugin {
       options: {},
       multiStep: undefined,
       fullBuildTimeout: 200,
       requestTimeout: 10000 },
     CaseSensitivePathsPlugin { options: {}, pathCache: {}, fsOperations: 0, primed: false },
     ProgressPlugin {
       profile: false,
       handler: undefined,
       modulesCount: 500,
       showEntries: false,
       showModules: true,
       showActiveModules: true },
     DefinePlugin { definitions: {} } ],
  module:
   { rules:
      [ { test: /\.(mjs|jsx?)$/,
          use:
           [ { loader:
                '/Users/dev/Projects/GitHub/storybook/repro/ui-storybook/node_modules/babel-loader/lib/index.js',
               options:
                { cacheDirectory:
                   '/Users/dev/Projects/GitHub/storybook/repro/ui-storybook/node_modules/.cache/storybook',
                  presets:
                   [ '/Users/dev/Projects/GitHub/storybook/repro/ui-storybook/node_modules/@babel/preset-react/lib/index.js',
                     '/Users/dev/Projects/GitHub/storybook/repro/ui-storybook/node_modules/@babel/preset-env/lib/index.js' ],
                  plugins:
                   [ '/Users/dev/Projects/GitHub/storybook/repro/ui-storybook/node_modules/@babel/plugin-proposal-object-rest-spread/lib/index.js' ],
                  babelrc: false } } ],
          include:
           [ '/Users/dev/Projects/GitHub/storybook/repro/ui-storybook' ],
          exclude:
           [ '/Users/dev/Projects/GitHub/storybook/repro/ui-storybook/node_modules' ] },
        { test: /\.md$/,
          use:
           [ { loader:
                '/Users/dev/Projects/GitHub/storybook/repro/ui-storybook/node_modules/raw-loader/index.js' } ] },
        { test: /\.css$/,
          use:
           [ '/Users/dev/Projects/GitHub/storybook/repro/ui-storybook/node_modules/style-loader/index.js',
             { loader:
                '/Users/dev/Projects/GitHub/storybook/repro/ui-storybook/node_modules/css-loader/dist/cjs.js',
               options: { importLoaders: 1 } },
             { loader:
                '/Users/dev/Projects/GitHub/storybook/repro/ui-storybook/node_modules/postcss-loader/src/index.js',
               options:
                { ident: 'postcss', postcss: {}, plugins: [Function: plugins] } } ] },
        { test:
           /\.(svg|ico|jpg|jpeg|png|gif|eot|otf|webp|ttf|woff|woff2|cur|ani)(\?.*)?$/,
          loader:
           '/Users/dev/Projects/GitHub/storybook/repro/ui-storybook/node_modules/file-loader/dist/cjs.js',
          query: { name: 'static/media/[name].[hash:8].[ext]' } },
        { test: /\.(mp4|webm|wav|mp3|m4a|aac|oga)(\?.*)?$/,
          loader:
           '/Users/dev/Projects/GitHub/storybook/repro/ui-storybook/node_modules/url-loader/dist/cjs.js',
          query: { limit: 10000, name: 'static/media/[name].[hash:8].[ext]' } },
        { test: /\.(ts|tsx)$/,
          use:
           [ { loader:
                '/Users/dev/Projects/GitHub/storybook/repro/ui-storybook/node_modules/babel-loader/lib/index.js',
               options:
                { presets:
                   [ '/Users/dev/Projects/GitHub/storybook/repro/ui-storybook/node_modules/@babel/preset-react/lib/index.js',
                     '/Users/dev/Projects/GitHub/storybook/repro/ui-storybook/node_modules/@babel/preset-env/lib/index.js' ],
                  plugins:
                   [ '/Users/dev/Projects/GitHub/storybook/repro/ui-storybook/node_modules/@babel/plugin-proposal-object-rest-spread/lib/index.js' ] } },
             { loader: 'ts-loader', options: { transpileOnly: true } },
             { loader: 'react-docgen-typescript-loader' },
             { loader:
                '/Users/dev/Projects/GitHub/storybook/repro/ui-storybook/node_modules/@storybook/addon-storysource/loader.js',
               options: { parser: 'typescript' } } ] } ] },
  resolve:
   { extensions: [ '.mjs', '.js', '.jsx', '.json', '.ts', '.tsx', '.json' ],
     modules: [ 'node_modules' ],
     alias:
      { 'core-js':
         '/Users/dev/Projects/GitHub/storybook/repro/ui-storybook/node_modules/core-js',
        react:
         '/Users/dev/Projects/GitHub/storybook/repro/ui-storybook/node_modules/react',
        'react-dom':
         '/Users/dev/Projects/GitHub/storybook/repro/ui-storybook/node_modules/react-dom' },
     plugins:
      [ TsconfigPathsPlugin {
          source: 'described-resolve',
          target: 'resolve',
          extensions: [ '.ts', '.tsx' ],
          log:
           { log: [Function],
             logInfo: [Function: doNothingLogger],
             logWarning: [Function],
             logError: [Function] },
          baseUrl: './src',
          absoluteBaseUrl:
           '/Users/dev/Projects/GitHub/storybook/repro/ui-storybook/src',
          matchPath: [Function] } ] },
  optimization:
   { splitChunks: { chunks: 'all' },
     runtimeChunk: true,
     minimizer:
      [ TerserPlugin {
          options:
           { test: /\.m?js(\?.*)?$/i,
             chunkFilter: [Function: chunkFilter],
             warningsFilter: [Function: warningsFilter],
             extractComments: false,
             sourceMap: true,
             cache: true,
             cacheKeys: [Function: cacheKeys],
             parallel: true,
             include: undefined,
             exclude: undefined,
             minify: undefined,
             terserOptions:
              { output: { comments: /^\**!|@preserve|@license|@cc_on/i },
                mangle: false,
                keep_fnames: true } } } ] },
  performance: { hints: false } }
</details

Here's the webpack config in prod mode:
<details>
Preview webpack config
{ mode: 'production',
  bail: true,
  devtool: '#cheap-module-source-map',
  entry:
   [ '/Users/dev/Projects/GitHub/storybook/repro/ui-storybook/node_modules/@storybook/core/dist/server/common/polyfills.js',
     '/Users/dev/Projects/GitHub/storybook/repro/ui-storybook/node_modules/@storybook/core/dist/server/preview/globals.js',
     '/Users/dev/Projects/GitHub/storybook/repro/ui-storybook/.storybook/config.tsx' ],
  output:
   { path:
      '/Users/dev/Projects/GitHub/storybook/repro/ui-storybook/storybook-static',
     filename: '[name].[hash].bundle.js',
     publicPath: '' },
  plugins:
   [ HtmlWebpackPlugin {
       options:
        { template:
           '/Users/dev/Projects/GitHub/storybook/repro/ui-storybook/node_modules/@storybook/core/dist/server/templates/index.ejs',
          templateContent: false,
          templateParameters: [Function: templateParameters],
          filename: 'iframe.html',
          hash: false,
          inject: false,
          compile: true,
          favicon: false,
          minify: undefined,
          cache: true,
          showErrors: true,
          chunks: 'all',
          excludeChunks: [],
          chunksSortMode: 'none',
          meta: {},
          title: 'Webpack App',
          xhtml: false,
          alwaysWriteToDisk: true },
       childCompilerHash: undefined,
       childCompilationOutputName: undefined,
       assetJson: undefined,
       hash: undefined,
       version: 4 },
     DefinePlugin {
       definitions:
        { 'process.env':
           { NODE_ENV: '"production"', NODE_PATH: '""', PUBLIC_URL: '"."' } } },
     CaseSensitivePathsPlugin { options: {}, pathCache: {}, fsOperations: 0, primed: false },
     ProgressPlugin {
       profile: false,
       handler: undefined,
       modulesCount: 500,
       showEntries: false,
       showModules: true,
       showActiveModules: true },
     DefinePlugin { definitions: {} } ],
  module:
   { rules:
      [ { test: /\.(mjs|jsx?)$/,
          use:
           [ { loader:
                '/Users/dev/Projects/GitHub/storybook/repro/ui-storybook/node_modules/babel-loader/lib/index.js',
               options:
                { cacheDirectory:
                   '/Users/dev/Projects/GitHub/storybook/repro/ui-storybook/node_modules/.cache/storybook',
                  presets:
                   [ '/Users/dev/Projects/GitHub/storybook/repro/ui-storybook/node_modules/@babel/preset-react/lib/index.js',
                     '/Users/dev/Projects/GitHub/storybook/repro/ui-storybook/node_modules/@babel/preset-env/lib/index.js' ],
                  plugins:
                   [ '/Users/dev/Projects/GitHub/storybook/repro/ui-storybook/node_modules/@babel/plugin-proposal-object-rest-spread/lib/index.js' ],
                  babelrc: false } } ],
          include:
           [ '/Users/dev/Projects/GitHub/storybook/repro/ui-storybook' ],
          exclude:
           [ '/Users/dev/Projects/GitHub/storybook/repro/ui-storybook/node_modules' ] },
        { test: /\.md$/,
          use:
           [ { loader:
                '/Users/dev/Projects/GitHub/storybook/repro/ui-storybook/node_modules/raw-loader/index.js' } ] },
        { test: /\.css$/,
          use:
           [ '/Users/dev/Projects/GitHub/storybook/repro/ui-storybook/node_modules/style-loader/index.js',
             { loader:
                '/Users/dev/Projects/GitHub/storybook/repro/ui-storybook/node_modules/css-loader/dist/cjs.js',
               options: { importLoaders: 1 } },
             { loader:
                '/Users/dev/Projects/GitHub/storybook/repro/ui-storybook/node_modules/postcss-loader/src/index.js',
               options:
                { ident: 'postcss', postcss: {}, plugins: [Function: plugins] } } ] },
        { test:
           /\.(svg|ico|jpg|jpeg|png|gif|eot|otf|webp|ttf|woff|woff2|cur|ani)(\?.*)?$/,
          loader:
           '/Users/dev/Projects/GitHub/storybook/repro/ui-storybook/node_modules/file-loader/dist/cjs.js',
          query: { name: 'static/media/[name].[hash:8].[ext]' } },
        { test: /\.(mp4|webm|wav|mp3|m4a|aac|oga)(\?.*)?$/,
          loader:
           '/Users/dev/Projects/GitHub/storybook/repro/ui-storybook/node_modules/url-loader/dist/cjs.js',
          query: { limit: 10000, name: 'static/media/[name].[hash:8].[ext]' } },
        { test: /\.(ts|tsx)$/,
          use:
           [ { loader:
                '/Users/dev/Projects/GitHub/storybook/repro/ui-storybook/node_modules/babel-loader/lib/index.js',
               options:
                { presets:
                   [ '/Users/dev/Projects/GitHub/storybook/repro/ui-storybook/node_modules/@babel/preset-react/lib/index.js',
                     '/Users/dev/Projects/GitHub/storybook/repro/ui-storybook/node_modules/@babel/preset-env/lib/index.js' ],
                  plugins:
                   [ '/Users/dev/Projects/GitHub/storybook/repro/ui-storybook/node_modules/@babel/plugin-proposal-object-rest-spread/lib/index.js' ] } },
             { loader: 'ts-loader', options: { transpileOnly: true } },
             { loader: 'react-docgen-typescript-loader' },
             { loader:
                '/Users/dev/Projects/GitHub/storybook/repro/ui-storybook/node_modules/@storybook/addon-storysource/loader.js',
               options: { parser: 'typescript' } } ] } ] },
  resolve:
   { extensions: [ '.mjs', '.js', '.jsx', '.json', '.ts', '.tsx', '.json' ],
     modules: [ 'node_modules' ],
     alias:
      { 'core-js':
         '/Users/dev/Projects/GitHub/storybook/repro/ui-storybook/node_modules/core-js',
        react:
         '/Users/dev/Projects/GitHub/storybook/repro/ui-storybook/node_modules/react',
        'react-dom':
         '/Users/dev/Projects/GitHub/storybook/repro/ui-storybook/node_modules/react-dom' },
     plugins:
      [ TsconfigPathsPlugin {
          source: 'described-resolve',
          target: 'resolve',
          extensions: [ '.ts', '.tsx' ],
          log:
           { log: [Function],
             logInfo: [Function: doNothingLogger],
             logWarning: [Function],
             logError: [Function] },
          baseUrl: './src',
          absoluteBaseUrl:
           '/Users/dev/Projects/GitHub/storybook/repro/ui-storybook/src',
          matchPath: [Function] } ] },
  optimization:
   { splitChunks: { chunks: 'all' },
     runtimeChunk: true,
     minimizer:
      [ TerserPlugin {
          options:
           { test: /\.m?js(\?.*)?$/i,
             chunkFilter: [Function: chunkFilter],
             warningsFilter: [Function: warningsFilter],
             extractComments: false,
             sourceMap: true,
             cache: true,
             cacheKeys: [Function: cacheKeys],
             parallel: true,
             include: undefined,
             exclude: undefined,
             minify: undefined,
             terserOptions:
              { output: { comments: /^\**!|@preserve|@license|@cc_on/i },
                mangle: false,
                keep_fnames: true } } } ] },
  performance: { hints: 'warning' } }
</details

**Comment by ndelangen** [comment]
Perhaps you can help me understand how `@root` works, and why it might not work in prod mode?

**Comment by n44ps** [comment]
I only use a tsconfig.json for custom paths.
And I have a custom babelrc for Storybook !

`
tsconfig.json
{
  "extends": "../tsconfig.base.json",
  "include": ["src"],
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "lib": ["dom", "esnext"],
    "declaration": true,
    "sourceMap": true,
    "rootDir": "./",
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "noImplicitThis": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "skipLibCheck": true,
    "moduleResolution": "node",
    "baseUrl": "./src",
    "paths": {
      "@root": ["./"],
      "@atoms": ["./components/atoms"],
      "@animated": ["./components/animated"],
      "@molecules": ["./components/molecules"],
      "@organisms": ["./components/organisms"],
      "@layout": ["./components/layout"]
    },
    "jsx": "react",
    "esModuleInterop": true
  }
}
`

`{
  "presets": ["@babel/preset-react", "@babel/preset-env"],
  "plugins": [
    "add-module-exports",
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-proposal-object-rest-spread"
  ]
}
`

**Comment by n44ps** [comment]
Hey @ndelangen, do you think it is still on my end ? Thanks

**Comment by ndelangen** [comment]
Tok a stab at diffing the 2 configs:
https://www.diffchecker.com/pkKsizom

But nothing really stands out why a module might be missing after a static build.

Have you been able to make any progress on it?

**Comment by TroySchmidt** [comment]
I have seen this in some other places where the new recommendation is only having the baseUrl setting in tsconfig.json.  It used to be to also have that in a .env file and setting NODE_PATH.  If you have both Storybook seems to be fine.  If you delete the .env file then resolve errors start showing up.

**Comment by n44ps** [comment]
Hey ! Sorry for the long time without any response. For now I'm still having the same issue, trying some stuff but still no good results. I'll keep you posted when I find anything :)
