### ISSUE TITLE
Jest Addon Style

### ISSUE THREAD

**Issue by NickSofology** [storybookjs/storybook#6805]
So basically I can't view the percentage value of my tests across the bar in the top of the addon panel for Jest.

Below is how I am enabling these tests to display on my stories.

```
.addParameters({
    readme: {
      content: AccordionIntro,
      sidebar: AccordionReadme,
    },
    jest: ['Accordion-test', 'AccordionItem-test'],
  })
```

I also have this in my config.js file.

```
addDecorator(
  withTests({
    results,
  })
);
```

It's all pretty standard as per instructions.

**Expected behavior**
I expect to be able to view the percentage value in the bar.

**Screenshots**
![Screenshot 2019-05-17 at 09 43 13](https://user-images.githubusercontent.com/46745772/57915239-3fa25780-7888-11e9-8ac1-2d94e51b8b9b.png)

As you can see from the above screenshot there is something there.  I go into dev tools and I can increase the height to see what I need to see, so I know that what I am seeing is clearly not intended.

**System:**
 - OS: OSX 10.14.4
 - Device: iMac
 - Browser: Chrome 73.0.3683.86
 - Framework: React
 - Addons: Jest
 - Version: 5.0.11

**Comment by CodeByAlex** [comment]
@NickSofology I'm on it!

**Comment by shilman** [comment]
Egads!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.1.0-rc.5 containing PR #6847 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
