### ISSUE TITLE
hrefTo throws an error when kind is not supplied

### ISSUE THREAD

**Issue by Hypnosphi** [storybookjs/storybook#6824]
**Describe the bug**
Can't use `hrefTo` without supplying both kind and story

**To Reproduce**
1. Go to https://next--storybooks-official.netlify.com/?path=/story/addons-links-link--first
2. See error in console: `Uncaught (in promise) TypeError: Cannot read property 'toLowerCase' of undefined`
3. Link's href points to root instead of the linked story

Probably broken by https://github.com/storybooks/storybook/commit/a9d356444c75124ee0f1ff6a85a5604ee0b82ff6. Before the change, the missing `kind` and `story` parameters were handled by `api.getUrlState`

**Comment by lonyele** [comment]
@Hypnosphi Hi, I'm just curious. For fixing those errors, passing `kind` to the `<LinkTo>` component worked fine. Is this supposed to work without explicitly passing `kind`?

**Comment by Hypnosphi** [comment]
Yes, in that case it should preserve the current kind. Quite useful for navigating inside a kind
That's how it worked before the changes from https://github.com/storybookjs/storybook/commit/a9d356444c75124ee0f1ff6a85a5604ee0b82ff6

**Comment by skhiter** [comment]
Hi everyone,
I have the same problem as @Hypnosphi, I installed create-react-native-app with storybook (v5.1.9).

DevDependencies:
-"@storybook/addon-actions": "^5.1.9",
-"@storybook/addon-links": "^5.1.9",
-"@storybook/addons": "^5.1.9",
-"@storybook/react-native": "^5.1.9",
-"@storybook/react-native-server": "^5.1.9",

Dependencies:
-"react": "16.8.3",
-"react-native": "0.59.9"

See error in console: Uncaught (in promise) TypeError: Cannot read property 'toLowerCase' of undefined

Would anyone have been able to fix the problem, please?
