### ISSUE TITLE
Why there is a Unknown tag around story source

### ISSUE THREAD

**Issue by SilenceOfNight** [storybookjs/storybook#6833]
**Describe the bug**
There is a Unknow tag around story source

**To Reproduce**

**Expected behavior**
There is not a Unknow tag aroud story source

**Screenshots**
![image](https://user-images.githubusercontent.com/8108915/58022614-67234980-7b40-11e9-9658-fd6f75746e1b.png)

**Code snippets**
```jsx
// .storybook/addons.js
import "storybook-addon-jsx/register";
import "@storybook/addon-knobs/register";

```

```jsx
// .storybook/config.js
import { addDecorator, configure } from "@storybook/react";

import { Fragment } from "react";
import { jsxDecorator } from "storybook-addon-jsx";
import { withInfo } from "@storybook/addon-info";
import { withKnobs } from "@storybook/addon-knobs";

addDecorator(jsxDecorator);
addDecorator(withKnobs);
addDecorator(withInfo({ inline: true, propTablesExclude: [Fragment] }));

function loadStories() {
  require("../stories/index.js");
}

configure(loadStories, module);

```

```jsx
import React, { Fragment } from "react";

import { Button } from "@cp/ec-ui";
import { storiesOf } from "@storybook/react";

// import { boolean, text } from "@storybook/addon-knobs";

storiesOf("Button", module)
  .add("type prop", () => (
    <div>
      <Button type="primary">Primary Button</Button>
      <Button type="danger">Danger Button</Button>
      <Button>Normal Button</Button>
    </div>
  ))
  .add("with emoji", () => (
    <Button>
      <span role="img" aria-label="so cool">
        😀 😎 👍 💯
      </span>
    </Button>
  ));

```

**System:**
 - OS: Windows10
 - Device: PC
 - Browser: chrome, safari
 - Framework: react
 - Addons: storybook-addon-jsx、@storybook/addon-info、@storybook/addon-knobs
 - Version: 5.0.11

**Additional context**

**Comment by dburles** [comment]
It would be good to perhaps just ignore React fragments

![Screen Shot 2019-05-31 at 4 26 04 pm](https://user-images.githubusercontent.com/319567/58698234-4b406300-83de-11e9-9a6e-ae4bc069d979.png)

**Comment by RazvanDH** [comment]
It seems to be an issue with `withInfo` and `jsxDecorator`. I had the same issue and it was fixed when I switched the order of the two (`withInfo` loading first). But that broke `jsxDecorator` - now it shows `<Story><MyComponent /></Story>`.

Would appreciate some help on this.

**Comment by shilman** [comment]
FYI `addon-info` is being superceded by `addon-docs`, which fixes a bunch of bugs and is easier to maintain. It’s reached release candidate (RC) status and will be properly released soon. Please give it a try! https://medium.com/storybookjs/storybook-docspage-e185bc3622bf

@SilenceOfNight @dburles @Kosai106 @malyw @kvhswong @deini @zgreen @github-actions @stale @RazvanDH
