### ISSUE TITLE
Kinds and hierarchies share the same namespace

### ISSUE THREAD

**Issue by Hypnosphi** [storybookjs/storybook#6834]
**Describe the bug**
If kind's name clashes with an existing hierarchy, it's not displayed.

**To Reproduce**
```
storiesOf('Foo', module)
  .add('Default', () => <Button  />);

storiesOf('Foo|Bar', module)
  .add('Default', () => <Button />)
```

**Expected behavior**
Tho kinds, "FOO -> Bar", and "OTHERS -> Foo" are displayed

**Screenshots**
<img width="207" alt="Screen Shot 2019-05-20 at 20 32 12" src="https://user-images.githubusercontent.com/6651625/58043820-84efaf00-7b3e-11e9-9901-a97eb0e20f24.png">

**Comment by vanessayuenn** [comment]
Hi! I am going through and cleaning up old issues in the repo. We just shipped a ton of improvements in Storybook 7.0, and I suspect this bug might be fixed already. Can you please try it out? If this issue persists with the latest version, please open a new bug report with a 7.x reproduction. Thank you so much! 🙏🏼
