### ISSUE TITLE
Adapt to Font Material Icons syntax

### ISSUE THREAD

**Issue by VictorBaron** [storybookjs/storybook#6851]
When trying to render a Material-Ui Icon identified by its Font material identifier, all I get is the identifier as a string

![Storybook](https://user-images.githubusercontent.com/10496372/58114556-43233f00-7bf8-11e9-8038-d403ffa6972d.png)

The code is as following: 

```
import Icon from "@material-ui/core/Icon";

const MyComp = () => (<Icon>add</Icon>)

storiesOf("MyComp", module).add("default", () => <MyComp />);
```

I would expect to see the corresponding Icon.

**Comment by codecatalysts** [comment]
@VictorBaron I was having the same problem and after reading the [docs](https://storybook.js.org/docs/configurations/add-custom-head-tags/) about custom head tags, I was able to get the icons to work.

I crated and added the following to the preview-head.html file in the Storybook config directory.
```html
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
```

**Comment by AnweshGangula** [comment]
> [@VictorBaron](https://github.com/VictorBaron) I was having the same problem and after reading the [docs](https://storybook.js.org/docs/configurations/add-custom-head-tags/) about custom head tags, I was able to get the icons to work.
> 
> I crated and added the following to the preview-head.html file in the Storybook config directory.
> 
> <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

The solution mentioned above doesn't seem to work in mui v-6.4.7
