### ISSUE TITLE
Notes addon should be part of the panel

### ISSUE THREAD

**Issue by moltar** [storybookjs/storybook#6852]
**Describe the bug**

Notes add gets added to the top nav instead of the panel.

The reason I have qualified this as a bug is because [the screenshot](https://github.com/storybooks/storybook/blob/next/addons/notes/docs/demo.png) on the [Notes README](https://github.com/storybooks/storybook/tree/next/addons/notes) file shows that the add on is part of a panel.

**To Reproduce**

1. Using Vue.
2. Register add-on `import '@storybook/addon-notes/register';`
3. Add a `notes` key to story options.
4. Open Storybook.

**Expected behavior**

Notes should be one of the panel tabs.

**Screenshots**

<img width="342" alt="image" src="https://user-images.githubusercontent.com/491247/58117535-cd55ae00-7bcc-11e9-8b6d-0b72b9db3723.png">

**Code snippets**

N/A

**System:**
 - OS: macOs
 - Device: Macbook Pro 2018
 - Browser: chrome
 - Framework: vue
 - Addons: notes
 - Version: 

```
    "@storybook/addon-actions": "5.0.11",
    "@storybook/addon-knobs": "5.0.11",
    "@storybook/addon-notes": "5.0.11",
    "@storybook/vue": "5.0.11",
```

**Additional context**

N/A

**Comment by moltar** [comment]
Just did an experiment. I removed all registrations from `addons` file, except for notes. I thought maybe there is a conflict with some other addons. But nope, still the same issue.

**Comment by Jenn** [comment]
Having the same issue. We use our notes extensively to view while you are viewing the canvas so this is a dealbreaker for us. 
I did see this in my searching for a solution: https://github.com/storybooks/storybook/pull/6091
Also considered switching to using readme
https://github.com/tuchk4/storybook-readme

**Comment by shilman** [comment]
This was updated here: https://github.com/storybooks/storybook/pull/6091

Needs to be tested & documented. Any takers?

**Comment by moltar** [comment]
Great! I can test it on Monday.

**Comment by seminelee** [comment]
from https://www.npmjs.com/package/@storybook/addon-notes
``` js
// register the notes addon as a tab
import '@storybook/addon-notes/register';
// or register the notes addon as a panel. Only one can be used!
import '@storybook/addon-notes/register-panel';
```
