### ISSUE TITLE
Storybook CSS Prop Parsing

### ISSUE THREAD

**Issue by ConnorNumberOne** [storybookjs/storybook#6853]
It looks like my storybook instance is not parsing the styles I have given it from emotion. See screenshot below. Does anyone know how to fix this? 
![Screen Shot 2019-05-21 at 3 32 04 PM](https://user-images.githubusercontent.com/19382245/58125433-8c669500-7bde-11e9-9cf5-0ff34bf7c623.png)

**Comment by hy2k** [comment]
I had a similar issue when I was using emotion with Gatsby. In my case, although I was using gatsby-plugin-emotion to parse styles, I also added `.babelrc` in `.storybook/` directory which is in the project root. Now Storybook is parsing the styles correctly.

**.storybook/.babelrc**:
```json
{
  "presets": ["@emotion/babel-preset-css-prop"]
}
```

I hope this solves your problem.

**Comment by ConnorNumberOne** [comment]
Thanks @hy2k! Unfortunately my company pivoted to docz instead. It met our needs a little more.
