### ISSUE TITLE
Gradients in theme break shortcut menu

### ISSUE THREAD

**Issue by robbertolierook** [storybookjs/storybook#6855]
**Describe the bug**
Whenever one uses a gradient in the theme, the shortcut button will cause the entire app to crash. 
**To Reproduce**
Theme with crash: 
```js
import { create } from '@storybook/theming';

const blue = '#0063ba';
const grey = '#e6e6e6';
const white = '#ffffff';

export default create({
  base: 'light',

  colorPrimary: blue,
  colorSecondary: blue,

  // UI
  appBg: `linear-gradient(to bottom, ${grey}, ${white})`,
  appContentBg: white,
  appBorderColor: blue,
  appBorderRadius: 0,
});
```
---
Theme without crash:
```js
import { create } from '@storybook/theming';

const blue = '#0063ba';
const grey = '#e6e6e6';
const white = '#ffffff';

export default create({
  base: 'light',

  colorPrimary: blue,
  colorSecondary: blue,

  // UI
  appBg: white,
  appContentBg: white,
  appBorderColor: blue,
  appBorderRadius: 0,
});
```
**Expected behavior**
The gradient background works, but I also expect the shortcut menu to open normally.

**Screenshots**
A screenshot would simply be a white page.

**System:**
 - OS: [MacOS]
 - Device: [Macbook Pro 2018]
 - Browser: [chrome]
 - Framework: [react]
 - Version: [5.0.6]

**Additional**
Also discussed here: #6756 
I think a better error is required to prevent confusion with the theme.

**Comment by ndelangen** [comment]
@robbertolierook that sounds like something that might be fairly easy to get started on, would you be able and interested in contributing to storybook?

I can help you get started.

**Comment by robbertolierook** [comment]
Sure, I could take a look.
Any help you could provide to get me started would be appreciated.
