### ISSUE TITLE
Angular Service generated dynamic component

### ISSUE THREAD

**Issue by kwinyyyc** [storybookjs/storybook#6856]
Hi I would like to check if storybook would support dynamic generated component for Angular.

For the use case I am facing is we have components such as a system loader which is generated dynamically by a service.

Thanks.

**Comment by kroeder** [comment]
You can use a wrapper component for your demo instead of directly point your story to your actual dynamic component

Kinda like 
```
add({
  component: MyDemoWrapperComponent,
  moduleMetadata: {
    imports: [MyDynamicComponentModule]
 }
}] 
```

I'm writing this from my phone and I'm not 100 sure if the Syntax is correct. If you need further implementation help, just let me know! :rocket:

**Comment by kwinyyyc** [comment]
Thanks @kroeder 

Not sure if I got you right, I created a wrapper component and it solves my problem. Let me share here what I have and feel free to comment if there could be any improvements.

In my case, I am using a ngx-toastr library (which is where the ToastrModule from) which generates a dynamic toast component.
I wrap it with a wrapper component and what the wrapper component does it basically call the library service which in turns generate a dynamic toast component.

toast.stories.ts
```Angular
stories.addDecorator(
  moduleMetadata({
    declarations: [ToastWrapperComponent, ToastComponent],
    providers: [ToastService],
    entryComponents: [ToastComponent],
    imports: [ToastrModule.forRoot({
      toastComponent: ToastComponent
    })]
  })
).add('Error Toast', () => ({
  component: ToastWrapperComponent,
}));
```

toast-wrapper.component.ts
```Angular
@Component({
  selector: 'toast-wrapper',
  template: ``,
  providers: [ToastService]
})
export class ToastWrapperComponent implements OnInit {
    constructor(private _toastService: ToastService) {}
    ngOnInit(): void {
        this._toastService.error('test');
    }
}
```

**Comment by CappfinitySimon** [comment]
@kwinyyyc I've hit the same problem with ngx-toastr - Did you ever find a solution for this?
