### ISSUE TITLE
"No Preview" message shown together with story content if press "Back" after navigation to default story

### ISSUE THREAD

**Issue by huston007** [storybookjs/storybook#6868]
**Describe the bug**
Storybook doesn't handle "Back" button properly if navigated to default story

**To Reproduce**
1. Go to https://storybooks-html.netlify.com
2. Wait until it is completely loaded, URL becomes https://storybooks-html.netlify.com/?path=/story/welcome--welcome
3. Press browser's "Back" button. https://storybooks-html.netlify.com/?path=/story/* opens
4. See error: story content shown together with "No Preview" message

**Expected behavior**
I think there should be no "https://storybooks-html.netlify.com/?path=/story/*" state in the history (it should be replaced)

**Screenshots**
<img width="1444" alt="Screenshot 2019-05-23 at 12 02 42" src="https://user-images.githubusercontent.com/4318513/58240002-b04ae780-7d52-11e9-87d7-a12d824c52eb.png">

**System:**
 - OS: macOS
 - Device: macbook pro 2018
 - Browser: chrome
 - Framework: I've tried html and react
 - Version: 5.1.0 I believe

**Comment by shilman** [comment]
Good one! 😆
