### ISSUE TITLE
Support multiple markdown files properly

### ISSUE THREAD

**Issue by de-dan** [storybookjs/storybook#6870]
**Describe the bug**
**Storybook/addon-notes**
Currently the storybook/addon-notes expects one markdown file. It would be nice, if you could serve an array of markdown files.
If I simply concatenate two markdown files, the first line of formatted markdown will not get rendered properly.

**To Reproduce**
1. Create markdownFileA.md. Content:
`Text`
2. Create markdownFileB.md, content:
`# headline`
3. Create a story with addon-notes:
```
{
        notes: {markdown: markdownFileA + markdownFileB}
}
```

**Expected behavior**
The contents of both markdown files should be displayed correctly

**Screenshots**
![renderedMarkdown](https://user-images.githubusercontent.com/13744542/58248066-703c3280-7d5b-11e9-8981-1c25adcabca0.png)

**System:**
 - OS: Windows7
 - Browser: Chrome
 - Addons: Notes
 - Version: 5.0.11

**Comment by shilman** [comment]
What if you do:

```
notes: { markdown: `${markdownFileA}\n\n${markdownFileB}` }
```

**Comment by de-dan** [comment]
Thank you! That works. (But it is a workaround in my opinion)

**Comment by luisjmontoro** [comment]
> What if you do:
> 
> ```
> notes: { markdown: `${markdownFileA}\n\n${markdownFileB}` }
> ```

Hi! I've been trying this but I can't make it work...  I'm trying to render two different md files, but I don't see how! 

Thanks and sorry for writing in a closed issue!

**Comment by shilman** [comment]
FYI `addon-notes` is being superceded by `addon-docs`, which fixes some problems with notes and is also more full-featured. It’s reached release candidate (RC) status and will be properly released soon. Please give it a try! medium.com/storybookjs/storybook-docspage-e185bc3622bf

**Comment by luisjmontoro** [comment]
Thanks @shilman! Can't wait to give it a try. I'm waiting for the development team to update Storybook so we can try the new addon. In the meantime, we thought it was a good idea to start migrating the documentation md files that we have currently on Catalog to each individual story on Storybook :) Thank you!!
