### ISSUE TITLE
Background Addon does not seem to trigger AddonsAPI

### ISSUE THREAD

**Issue by khrome83** [storybookjs/storybook#6873]
**Describe the bug**
I can't get the example code for Background addond to trigger any console.log - 

```
addonAPI.getChannel().on('storybook/background/update', (bg) => {
  console.log('Background color', bg.selected);
  console.log('Background name', bg.name);
});
```

**To Reproduce**
1. Setup Background Addon
2. Past Example Code with addonAPI import into `./storybook/config.js`

**Expected behavior**
Should see the example console.log behavior.

**System:**
 - OS: MacOS
 - Device: Macbook Pro 2017
 - Browser: chrome
 - Framework: vue
 - Addons: backgrounds
 - Version: 5.0.11

**Additional context**
*Question* - My goal was to identify when the background swapped, and append a class to the root within the iFrame. Is there a better way to do this? I need to identify when the background theme was changed so the class can mimic changing a top level section to "inverse" or "dark".

Thanks!

**Comment by shilman** [comment]
@khrome83 You can enable verbose logging in chrome dev tools and see every message that gets sent on the channel. Does that help?

**Comment by khrome83** [comment]
@shilman - i abandoned this and took a different approach. I added a decarator that renders multiple instances of the content, each with a different background color, and applying a different parent class, so the content could respond. 

Thank you though.

**Comment by iamgbayer** [comment]
@shilman I'm having this problem to see trigged consoles same with verbose enabled

**Comment by shilman** [comment]
@iamgbayer you don't see any console messages from the channel? or don't see this specific message?
