### ISSUE TITLE
Ability to rename Knobs / Actions Tab-Titles

### ISSUE THREAD

**Issue by psi-4ward** [storybookjs/storybook#6879]
Would be cool to have the ability to use own title for `Knobs` and `Actions` tabs to make it more consistent with other frameworks like Vue: `Props` and `Events`.

If I look at the code it's hopefully not to difficult.

**Comment by Utzel-Butzel** [comment]
Hi, you can rename the Tab title by acessing the addons object in your config.
```
import addons from '@storybook/addons';
addons.elements.panel['MYADDON/panel'].title = 'New title'
```

**Comment by aviraminy** [comment]
> Hi psi-4ward, you can rename the Tab title by acessing the addons object in your config.
> 
> ```js
> import addons from '@storybook/addons';
> 
> addons.elements.panel['storybookjs/knobs/panel'].title = 'Props';
> addons.elements.panel['storybook/actions/panel'].title = 'Event';
> ```

actually this doesn;t work for me at all i havre an empty addons.elements object, it seems to me that the load is delayed and that is why it isn't adding the element yet during the configure.

PS - i am using storybook v5.2.1

**Comment by diamond-darrell** [comment]
> > Hi psi-4ward, you can rename the Tab title by acessing the addons object in your config.
> > ```js
> > import addons from '@storybook/addons';
> > 
> > addons.elements.panel['storybookjs/knobs/panel'].title = 'Props';
> > addons.elements.panel['storybook/actions/panel'].title = 'Event';
> > ```
> 
> actually this doesn't work for me at all i get an empty addons.elements object.
> It seems to me that the addon register is delayed and that is why it isn't adding the element yet during the configure phase.
> 
> PS - i am using storybook v5.2.1

wrapping assignment in `setTimeout` worked out for me

**Comment by mboudrig** [comment]
@diamond-darrell I'm not able to get it working with setTimeout, do you mind sharing how you got this working?

**Comment by mboudrig** [comment]
> > > Hi psi-4ward, you can rename the Tab title by acessing the addons object in your config.
> > > ```js
> > > import addons from '@storybook/addons';
> > > 
> > > addons.elements.panel['storybookjs/knobs/panel'].title = 'Props';
> > > addons.elements.panel['storybook/actions/panel'].title = 'Event';
> > > ```
> > 
> > 
> > actually this doesn't work for me at all i get an empty addons.elements object.
> > It seems to me that the addon register is delayed and that is why it isn't adding the element yet during the configure phase.
> > PS - i am using storybook v5.2.1
> 
> wrapping assignment in `setTimeout` worked out for me

This didn't work for me from the config.js file but did work from the addons.js file

```js
import addons from "@storybook/addons";

setTimeout(function() {
  addons.elements.panel["storybookjs/knobs/panel"].title = "Props";
  addons.elements.panel["storybook/actions/panel"].title = "Events";
  console.log("elements", addons.elements);
}, 0);
```

**Comment by aviraminy** [comment]
This is not such a good workaround and relies on runtime, i wish there was a proper config for this.

**Comment by diamond-darrell** [comment]
> > > > Hi psi-4ward, you can rename the Tab title by acessing the addons object in your config.
> > > > ```js
> > > > import addons from '@storybook/addons';
> > > > 
> > > > addons.elements.panel['storybookjs/knobs/panel'].title = 'Props';
> > > > addons.elements.panel['storybook/actions/panel'].title = 'Event';
> > > > ```
> > > 
> > > 
> > > actually this doesn't work for me at all i get an empty addons.elements object.
> > > It seems to me that the addon register is delayed and that is why it isn't adding the element yet during the configure phase.
> > > PS - i am using storybook v5.2.1
> > 
> > 
> > wrapping assignment in `setTimeout` worked out for me
> 
> This didn't work for me from the config.js file but did work from the addons.js file
> 
> ```js
> import addons from "@storybook/addons";
> 
> setTimeout(function() {
>   addons.elements.panel["storybookjs/knobs/panel"].title = "Props";
>   addons.elements.panel["storybook/actions/panel"].title = "Events";
> }, 0);
> ```

yes, I'm sorry, I should've mentioned it, I did this in the addons.js file as well as you are

**Comment by StanCreuna** [comment]
Is there a way to rename Addons like Controls/Actions in new Storybook?

**Comment by shilman** [comment]
@StanCreuna `.storybook/addons.js` has been renamed to `.storybook/manager.js`. The method above is not "officially supported" but you could give it a try in `manager.js` and I bet it would "just work."

**Comment by curtgrimes** [comment]
In recent versions of Storybook (I am on 6.5 alpha 48 currently) the workaround for changing the addon title changes slightly because the `elements` property is private.

This changes the Storysource addon's title to "Raw Source":

```
// in manager.js
setTimeout(() => {
    const sourceLoaderAddon = addons.getElements(types.PANEL)['storybook/source-loader/panel'];
    if (sourceLoaderAddon) {
        sourceLoaderAddon.title = 'Raw Source';
    }
}, 0);
```

**Comment by levaigabor** [comment]
@curtgrimes I just came across this problem, maybe you are looking for smth like this (from this PR https://github.com/storybookjs/storybook/pull/9095)?

```previewTabs: {
   addon_id: string: {
    title?: string; // new title for the addon tab
    index?: number; // override the place/order of the tabs (by default the change uses the order of the addon_id keys but index can be used to override in the story parameyters
    hidden?: boolean; // wether to hide the addon tab
    disabled?: boolean; // wether to disable the addon tab
  }
}

**Comment by sag1v** [comment]
@levaigabor This doesn't seems to work, the only way that seems to work is the "workaround" suggested above.
(storybook v7)

In my case (trying to hide/remove a tab) i can't even use the suggested workaround, seems like the `hidden` property is ignored.

This is the only (ugly) way i managed to remove/hide a tab:

```js
// .storybook/manager.js

setTimeout(() => {
  // removes the 'Code' tab from the panel
  const {
    ['storybook/source-loader/panel']: sourceTab,
    ...restOfTabs
  } = addons.elements.panel;
  addons.elements.panel = restOfTabs;
}, 0);
```
