### ISSUE TITLE
Storyshot shallow rendering with decorators

### ISSUE THREAD

**Issue by ewolfe** [storybookjs/storybook#6880]
**Describe the bug**
When shallow rendering with decorators the snapshot generated is useless. For example:

```
// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`Storyshots Components|Avatar default 1`] = `
<StoryRouter
  story={[Function]}
/>
`;
```

**To Reproduce**
1. Create a story
1. Configure storyshots to use shallow rendering
1. Configure storyshots to use a decorator, (e.g. https://github.com/gvaldambrini/storybook-router)

**Expected behavior**
The snapshot contains the serialized component being tested.

**Comment by shilman** [comment]
Closing this as a dupe of #7020

**Comment by ewolfe** [comment]
@shilman that ticket is regarding Storybook 5. I'm still on Storybook 3. Would you mind re-opening this?

**Comment by shilman** [comment]
@ewolfe Aha sorry about that. Reopening!
