### ISSUE TITLE
Story groups for angular

### ISSUE THREAD

**Issue by RogierdeRuijter** [storybookjs/storybook#6888]
Hi,

Is there an addon available to create story groups in angular. Similar to https://github.com/jurgob/react-storybook-addon-add-stories-group.

Cheers

**Comment by CodeByAlex** [comment]
@RogierdeRuijter This is a work in progress but might address what you are looking for: https://medium.com/storybookjs/storybook-docs-sneak-peak-5be78445094a

**Comment by shilman** [comment]
FYI SB docs is available in 5.2.0-alpha.x and documented here: https://docs.google.com/document/d/1un6YX7xDKEKl5-MVb-egnOYN8dynb5Hf7mq0hipk8JE/edit?usp=sharing
