### ISSUE TITLE
How to emit typescript on error?

### ISSUE THREAD

**Issue by gocreating** [storybookjs/storybook#6889]
I followed the [official tutorial](https://storybook.js.org/docs/configurations/typescript-config/) to migrate storybook project to typescript code base. However, `start-storybook` will not launch local server if there is any one type error. This is so annoying for a beginner of typescript.

After I hacked to resolve all type errors, storybook did launch successfully. Is there a better configuration to make us migrate more easily?
It seems that setting tsconfig's `compilerOptions.noEmitOnError` to false is not working.

Here are my configs:

``` js
// .storybook/webpack.config.js
module.exports = ({ config }) => {
  config.module.rules.push({
    test: /\.(ts|tsx)$/,
    use: [
      {
        loader: require.resolve('awesome-typescript-loader'),
      },
      // Optional
      {
        loader: require.resolve('react-docgen-typescript-loader'),
      },
    ],
  });
  config.resolve.extensions.push('.ts', '.tsx');
  return config;
};
```

``` json
// tsconfig.json
{
  "compilerOptions": {
    "outDir": "build/lib",
    "module": "commonjs",
    "target": "es5",
    "lib": ["es5", "es6", "es7", "es2017", "dom"],
    "sourceMap": true,
    "allowJs": false,
    "jsx": "react",
    "moduleResolution": "node",
    "rootDirs": ["src", "stories"],
    "baseUrl": "src",
    "forceConsistentCasingInFileNames": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "suppressImplicitAnyIndexErrors": true,
    "noUnusedLocals": true,
    "declaration": true,
    "allowSyntheticDefaultImports": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "esModuleInterop": true,
    "noEmitOnError": false
  },
  "include": ["src/**/*"],
  "exclude": ["node_modules", "build", "scripts"]
}
```

**Comment by emilio-martinez** [comment]
Hey @gocreating 👋I just tried reproducing with a clean CRA + Storybook + adding Storybook typescript config, but I didn't get any errors. Would you mind sharing more detail on the errors you're seeing?

**Comment by TroySchmidt** [comment]
I think maybe the issue is the baseUrl setting.  That isn't standard if doing clean CRA.  CRA now recommends not having a .env file with NODE_PATH set and instead using baseUrl of tsconfig.json when using TypeScript.  But if you don't have the .env file you will get a lot of resolution errors.
