### ISSUE TITLE
Svelte stores not supported

### ISSUE THREAD

**Issue by tarjei** [storybookjs/storybook#6904]
**Describe the bug**
If you define a Svelte component that dependes on a store, you create the component like this:

`new MyComponent({target: "#roor", store: store})`

The problem is that the Svelte component api (v2) also supports passing in a store value that is unsupported by storybook-svelte. 

**To Reproduce**
Se description above.
**Expected behavior**
Storybook should also pass the store key to the component.

**System:**
 - OS: linux
 - Device: desktop

 - Framework: svelte
 - Version: 
    - svelte 2.16.1,
    - @storybook/svelte": "^5.0.11"

**Comment by shilman** [comment]
cc @plumpNation @cam-stitt

**Comment by plumpNation** [comment]
I'm sorry, I don't have time right now to contribute on this. One thing to be aware of is that there is a lot of work happening to update the svelte version to 3 in storybook. Backward compatibility may not be achieved as there are large breaking changes between svelte 2 and 3.

https://github.com/storybookjs/storybook/pull/7023#issuecomment-504782982

**Comment by cam-stitt** [comment]
As @plumpNation said, storybook has moved to support Svelte 3 *only* as of #6698. It was stated in that PR that it was a "breaking change" as it removed the support for Svelte 2 completely.
