### ISSUE TITLE
Storybook 5 not displaying all stories

### ISSUE THREAD

**Issue by haldunanil** [storybookjs/storybook#6908]
**Describe the bug**
I am dynamically loading stories, but only the first 18 seem to get loaded. The rest simply don't show up on the left nav.

**Expected behavior**
All of the identified story files should be loaded into Storybook (indeed, when I do a console.log of `req.keys()`, all of the files I want are listed).

**Screenshots**
<img width="229" alt="Screen Shot 2019-05-29 at 5 09 42 PM" src="https://user-images.githubusercontent.com/9256828/58591627-b9e1bd00-8234-11e9-90af-88d0287f06d1.png">

<img width="1470" alt="Screen Shot 2019-05-29 at 5 10 39 PM" src="https://user-images.githubusercontent.com/9256828/58591630-bbab8080-8234-11e9-91d2-436b5a134af5.png">

**Code snippets**

```javascript
import React from "react";
import { create } from "@storybook/theming";
import { withDocs } from "storybook-readme";
import styled from "styled-components";
import NEFThemeProvider from "../src/components/NEFThemeProvider";

// add theme
addDecorator(s => <NEFThemeProvider>{s()}</NEFThemeProvider>);

// parameters
addParameters({
  options: {
    panelPosition: "right",
    theme: create({
      base: "light",
      brandTitle: "NEF React Components"
    })
  }
});

const PreviewComponent = styled.div`
  margin: 25px 0;
`;

export const withMarkup = withDocs({
  PreviewComponent
});

// dynamically import all stories
const req = require.context("../src/components", true, /\.stories\.tsx$/);

function loadStories() {
  req.keys().forEach(filename => req(filename));
}

configure(loadStories, module);
```

**System:**
 - OS: Mac OS High Sierra
 - Device: Macbook Pro 2018
 - Browser: Chrone
 - Framework: React
 - Addons: 
    - addon-actions
    - addon-knobs
    - addon-viewport
 - Version: 5.0.11

**Additional context**
Using the [storybook-readme](https://github.com/tuchk4/storybook-readme) project to generate my story markdowns.

**Comment by shilman** [comment]
Any other errors on the JS console or command-line? What happens if you disable `storybook-readme`?

**Comment by haldunanil** [comment]
I was actually able to fix this, I will comment back with what I did as soon as I remember.
