### ISSUE TITLE
TypeError: Cannot destructure property `id` of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by iamnewton** [storybookjs/storybook#6909]
**Describe the bug**

```TypeError: Cannot destructure property `id` of 'undefined' or 'null'.```

This is the only error I receive in the console but its preventing me from seeing any storybooks.

**System:**
 - OS: MacOS
 - Device: MacBook Pro 2016
 - Browser: Chrome 74
 - Framework: React
 - Addons: addon-options, addon-knobs, addon-viewport, addon-actions, addon-links, addon-a11y, storybook-addon-jsx
 - Version: 5.0.11

**Additional context**
```
  | error | @ | vendors~main.f17f6bd…d496.bundle.js:8473
-- | -- | -- | --
  | push../node_modules/@storybook/channel-postmessage/dist/index.js.PostmsgTransport.handleEvent | @ | vendors~main.f17f6bd…d496.bundle.js:8282
  | postMessage (async) |   |  
  | push../node_modules/@storybook/channel-postmessage/dist/index.js.PostmsgTransport.send | @ | index.js:46
  | handler | @ | index.js:46
  | push../node_modules/@storybook/channels/dist/index.js.Channel.emit | @ | index.js:55
  | renderMain | @ | start.js:200
  | renderUI | @ | start.js:216
  | emit | @ | index.js:180
  | (anonymous) | @ | story_store.js:245
  | setTimeout (async) |   |  
  | StoryStore._this.setSelection | @ | story_store.js:244
  | (anonymous) | @ | story_store.js:296
  | emit | @ | index.js:180
  | _renderMain | @ | config_api.js:114
  | render | @ | config_api.js:52
  | ConfigApi.configure | @ | config_api.js:89
  | (anonymous) | @ | config.js:24
  | ./.storybook/config.js | @ | config.js:24
  | __webpack_require__ | @ | bootstrap:782
  | fn | @ | bootstrap:150
  | 0 | @ | index.scss?89d8:45
  | __webpack_require__ | @ | bootstrap:782
  | checkDeferredModules | @ | bootstrap:45
  | webpackJsonpCallback | @ | bootstrap:32
  | (anonymous) | @ | main.a175980….bundle.js:1

**Comment by shilman** [comment]
@iamnewton Do you have a repro here? Hard to tell what's going on just from the stack trace. Is this a project that worked before and broke when you updated? If not, I'd suggest removing all addons and trying to isolate the problem that way. Or provide a repro and somebody can take a look. Thanks!

**Comment by iamnewton** [comment]
sorry, its a private repo, so I don't have anyway to share it; i'll remove stuff, and see what happens

**Comment by y-nk** [comment]
@iamnewton if you wish to receive help, please consider duplicate your private repo in a separate folder, delete the `.git` directory, create a new one, strip out all the sensitive files/informations to isolate the problem and upload it on github.

**Comment by ibandim123** [comment]
I have a same problem, who i just fix that! ? " TypeError: Cannot destructure property 'id' of 'usuario' as it is undefined." 

controllers/home.js
`const { RSA_NO_PADDING } = require("constants")


module.exports = (app) => {
    const HomeController = {
        index: function(req, res) {
            res.render('home/index')
        },
        login( req, res ) {
            const { usuario } = req.body
            const { id, nome } = usuario;
            if( id && nome ) {
                usuario.contatos = [];
                req.session.usuario = usuario;
                res.redirect('/contatos');
            } else {
                res.redirect('/')
            }
        },
        logout( req, res) {
            req.session.destroy();
            res.redirect('/')
        }
    };
    return HomeController
}
`
app.js
`const express = require('express');
const path = require('path');
const consign = require('consign')
const bodyParser = require('body-parser')
const cookieParser = require('cookie-parser')
const expressSession = require('express-session');
const app = express();

//Template engine com express: ejs
app.set('views', path.join(__dirname, 'views'))
app.set('view engine', 'ejs')

app.use(cookieParser('ntalk'));
app.use(expressSession());
app.use(bodyParser.json());
app.use(bodyParser.urlencoded());

//Caminho dos arquivos estáticos
app.use(express.static(path.join(__dirname, '..', 'public')))
app.use(bodyParser.urlencoded({extended: true}))
app.use(bodyParser.json())



//mapear diretórios 
consign({cwd:'src'})
.include('models')
.then('controllers')
.then('routes')
.into(app)




app.listen(3000, (req,res) =>{
    console.log('App no ar!')
})`
