### ISSUE TITLE
add-backgrounds doesn't seem to show configured default background

### ISSUE THREAD

**Issue by KadenLNelson** [storybookjs/storybook#6915]
**Describe the bug**
The configured background only seems to 'appear' when I'm resizing the window.

**Expected behavior**
I expect the backgrounds add on to show the background that I've set as default in `config.js`

**Screenshots**
https://gyazo.com/692513518902f8e403036d29b4ee5c28

**Code snippets**
```
addParameters({
  backgrounds: [
    { name: "E3 Darker Orange", value: "#F15C29", default: true}
  ]
})
```

**System:**
 - OS: MacOS
 - Device: macbook pro 2015
 - Browser: chrome
 - Framework: react
 - Addons: addon-backgrounds
```
    "@storybook/addon-actions": "^5.0.11",
    "@storybook/addon-backgrounds": "^5.0.11",
    "@storybook/addon-links": "^5.0.11",
    "@storybook/addons": "^5.0.11",
    "@storybook/react": "^5.0.11",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
```

**Additional context**

**Comment by djgrant** [comment]
I have the same issue setting backgrounds in `.storybook/config.js` in a TypeScript project. However, the background is not showing even when resizing the window. 

It works fine when adding background parameters to individual stories.

**Comment by djgrant** [comment]
I solved this for myself by calling `addParameters` before `configure`.

**Comment by KadenLNelson** [comment]
> I solved this for myself by calling `addParameters` before `configure`.

Will try this later

**Comment by graup** [comment]
Thanks, that works. Should probably be mentioned in the documentation? Currently it just says "You can add the backgrounds to all stories with addParameters in .storybook/config.js".

**Comment by graup** [comment]
If @KadenLNelson could confirm that this solves their issue we can close this.

**Comment by ndelangen** [comment]
This is indicative of a bug:

Global decorators and parameters must currently be set BEFORE the configure call.

**Comment by KadenLNelson** [comment]
> > I solved this for myself by calling `addParameters` before `configure`.
> 
> Will try this later

This did not work

**Comment by shilman** [comment]
Backgrounds has been overhauled in 6.0 and works properly now https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#backgrounds-addon-has-a-new-api
