### ISSUE TITLE
React-Native Storybook v5.1.0rc3 add-on tabs cannot be seen on simulator.

### ISSUE THREAD

**Issue by lyqht** [storybookjs/storybook#6917]
**Describe the bug**
After upgrading storybook-react-native to ver 5.1.3-rc, there is a lack of padding / margin around the app. Now I am not able to click on the add-on notes & knobs tabs. 

**Expected behavior**
I should be able to click on the add-on tabs.

**Screenshots**
on ver 5.1.3-rc
![image](https://user-images.githubusercontent.com/35736525/58678470-71401600-8392-11e9-8ac5-f9e3c00e5896.png)

on ver 4.1.18
![image](https://user-images.githubusercontent.com/35736525/58678877-d8aa9580-8393-11e9-90cf-a6c2239caf4c.png)

**System:**
 - Device: iPhoneX simulator
 - Framework: React-Native
 - Addons: addon-ondevice notes & knobs

**Comment by lyqht** [comment]
tested on `"@storybook/react-native": "^5.1.3"`, same issue

**Comment by goldenlove** [comment]
5.1.9, same issue here~ 😆
a temporary solution: 
use iPhone 8 Plus or other “none notch" device Instead of iPhoneX simulator~ lol

**Comment by Gongreg** [comment]
Hey. It seems that safe area view is missing as a wrapper for storybook. Would someone like to add it?

**Comment by pvinis** [comment]
Was this working on 4? If yes, I could do a bisect, but I don't know how big the changes were from 4 to 5.

**Comment by Gongreg** [comment]
Hey, I don’t think so. We need to addSafeAreaView wrapper. Could you add it?

**Comment by bqrichards** [comment]
I can do this if you haven't started already @pvinis

**Comment by pvinis** [comment]
feel free to take this :)

**Comment by shilman** [comment]
Crikey!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-beta.39 containing PR #7809 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
