### ISSUE TITLE
addon-knobs for React-Native not working

### ISSUE THREAD

**Issue by lyqht** [storybookjs/storybook#6918]
**Describe the bug**
In the index.tsx file, I have tried adding a global decorator for add-on knobs with the code below. (Notes is working, knobs is not.)
```
addDecorator(withNotes)
addDecorator(withKnobs)

configure(() => {
  loadStories()
}, module)

const StorybookUIRoot = getStorybookUI(
  {port: 7070, host: 'localhost'});

AppRegistry.registerComponent(appName, () => StorybookUIRoot);
export default StorybookUIRoot;
```

And in my story file,
```
// ...
import { number } from '@storybook/addon-knobs';

storiesOf('Pill', module)
  .add('Configuring Colors', () => {
    const pill1R = number('R', 255)
    const pill1G = number('G', 118)
    const pill1B = number('B', 0)
    const pill1Color = `rgb(${pill1R}, ${pill1G}, ${pill1B})`

    return (
    <View style={StoryStyle.centerComponent}>
      <View style={StoryStyle.buttonSubsection}>
        <Pill label="Hello" indicatorColor={pill1Color}  />
        <View style={StoryStyle.space} />
        <Text.H5>Indicator Color: {pill1Color}</Text.H5>
      </View>
    </View> )
  }
```
I can see that the const values are parsed correctly in the app, but there is no knobs available.
![image](https://user-images.githubusercontent.com/35736525/58679664-1a890b00-8397-11e9-81fd-03226c168311.png)

**relevant dependencies:**
```
    "@storybook/addon-actions": "^5.0.11",
    "@storybook/addon-info": "^5.0.11",
    "@storybook/addon-knobs": "^5.0.11",
    "@storybook/addon-notes": "^5.0.11",
    "@storybook/addon-ondevice-backgrounds": "^4.1.18",
    "@storybook/addon-ondevice-knobs": "^4.1.18",
    "@storybook/addon-ondevice-notes": "^4.1.18",
    "@storybook/addons": "^5.0.11",
    "@storybook/react-native": "^4.1.18",
```

**Comment by aswin-s** [comment]
Facing the same issue. Tried alpha & next channels as well.

**Comment by shilman** [comment]
@lyqht @aswin-s You should either use `4.1.x` versions across the board or upgrade everything to `5.1.0-rc.x`. Can't guarantee it will fix the problem, but I wouldn't expect the example posted here to work due to version inconsistency (4.0 to 5.0 is a breaking change)

**Comment by Gongreg** [comment]
@ndelangen, did anything change in knobs addon?

**Comment by Gongreg** [comment]
Sorry, accidentally closed it.

**Comment by aswin-s** [comment]
@shilman Yes I did the same. When I was trying out stable build, all storybook dependencies were on 4.1.18. And for 'rc' tag, I used 5.1.0-rc.3 across.

**Comment by shilman** [comment]
@aswin-s Ok, thanks for letting me know. Hopefully we can get a fix out soon.

**Comment by lyqht** [comment]
@shilman , thank you for getting back on this issue!
- Regarding upgrading to `5.1.0-rc.x`, i faced the resolution issue in #6917 and hence decided to keep it in `4.1.18`. 
- While the add-on knobs are able to work on `4.1.x`, i faced the same issue as #6005 , where the debouncing is too fast and editing the knob value results in NaN before I finish typing the input value. 

![image](https://user-images.githubusercontent.com/35736525/58782710-d81f3280-8611-11e9-8173-cf981443749c.png)

**Comment by aswin-s** [comment]
I tried this on a new CRNA app and to my surprise, it's working. I don't know where I messed up last time. Please mark this as a non-issue.

**Comment by Gongreg** [comment]
Hey, is there still an issue here?

**Comment by lyqht** [comment]
@Gongreg Nope, they are working! But theres still the debounce interval problem that i highlighted. But i guess this issue can be closed for its topic :) Thanks for helping out !

**Comment by slorber** [comment]
is there someone having an Expo SDK33 setup that works? I can't find any RN example anymore in the repo and by ondevice knobs don't appear :(

**Comment by Gongreg** [comment]
Hey @slorber, this is the example: https://github.com/storybookjs/storybook/tree/next/examples-native/crna-kitchen-sink . I hope it works, I am not sure, didn't test it.

**Comment by slorber** [comment]
Thanks @Gongreg this probably saved me few hours :)

Just noticed I simply forgot to add "/register" at the end of each import.

Isn't there a way to warn the user if he types the wrong import, like I did?
