### ISSUE TITLE
addon-ondevice-notes does not format markdown correctly

### ISSUE THREAD

**Issue by lyqht** [storybookjs/storybook#6920]
**Describe the bug**
The format of the markdown is rendered incorrectly (the bullets and table in this case).
![image](https://user-images.githubusercontent.com/35736525/58685476-7612c300-83ae-11e9-8d70-9cbf16c3e793.png)

**Code snippets**
```
export const notes: string = `
## More about the Borders

- By default, the bar selectors will have borders on both at the top and the bottom. 
- Hence, when stacking bar selectors together, it is important to input the isFirstElement prop correctly, so that there will not be overlapping of the borders in between the bar selectors. 
- When isFirstElement={false}, it removes the top border of the BarSelector. 
`
```

```
import notes from "./notes"
storiesOf('Bar Selector', module)
  .add("Types of Bar Selectors", () => (
     // story code 
  ), {
    notes: { markdown: notes }
  })
```

**System:**
 - Device: iPhone X Simulator
 - Framework: React-Native
 - Storybook: @storybook/react-native v4.1.18
 - Addons: addon-ondevice-notes v4.1.18 & add-on-notes v5

Also, it will be great if someone can point out to me how to import and render a `notes.md` file directly from the `.story.tsx` file as `notes`, instead of using `notes.tsx`! I have searched online for many ways e.g. using a typings.d.ts to declare `*.md` as module but still it shows the following error.

![image](https://user-images.githubusercontent.com/35736525/58685215-7ced0600-83ad-11e9-81b0-77b7851e7238.png)

Thank you.

**Comment by Nibblesh** [comment]
There is also issues with escaped tables

The markdown that I am using in the table below renders correctly in github as per the preview. but from storybook it looks as per the screenshot

![image](https://user-images.githubusercontent.com/9124852/59476780-a6219200-8e95-11e9-8010-f53f7da5708a.png)


I am using stencil's doc generation tool which outputs the following:


# my-component






## Properties

| Property   | Attribute  | Description                | Type                                                                                  | Default     |
| ---------- | ---------- | -------------------------- | ------------------------------------------------------------------------------------- | ----------- |
| `disabled` | `disabled` | HTML Button disabled state | `boolean`                                                                             | `undefined` |
| `theme`    | `theme`    | Color Theme for button     | `"danger" \| "dark" \| "light" \| "primary" \| "secondary" \| "success" \| "warning"` | `'primary'` |
| `type`     | `type`     | HTML Button type           | `string`                                                                              | `undefined` |


----------------------------------------------

*Built with [StencilJS](https://stenciljs.com/)*

**Comment by Gongreg** [comment]
Hello @lyqht. Seems like the bullets are rendered in middle of the text instead of the top. To render markdown we are using: https://github.com/CharlesMangwa/react-native-simple-markdown .

Regarding loading the md file, you need to have a way to load it in React Native. Maybe you can find something here: https://stackoverflow.com/questions/52571450/react-native-expo-load-markdown-files

**Comment by Gongreg** [comment]
I think the issue should be opened for CharlesMangwa/react-native-simple-markdown @shilman, what do you think?

**Comment by shilman** [comment]
@Gongreg yeah that makes sense
