### ISSUE TITLE
React-storybook fails when use hooks within forwardRef

### ISSUE THREAD

**Issue by Lehakos** [storybookjs/storybook#6925]
**Describe the bug**
If we use hooks within forwardRef component, we receive next error:
> Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons: 1. You might have mismatching versions of React and the renderer (such as React DOM) 2. You might be breaking the Rules of Hooks 3. You might have more than one copy of React in the same app See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.

**To Reproduce**
1. Make component using hooks and forwardRef
2. Create story for this component

**Code snippets**
Story for example:
```javascript
import React, { useRef, forwardRef } from 'react';
import { storiesOf } from '@storybook/react';

const Test = forwardRef((_, ref) => {
  const state = useRef();
  return <div ref={ref}>Hello</div>;
});

const stories = storiesOf('Test', module).add('Default', () => <Test />);
```

**Storybook:**
 - Version: 5.0.11

**Additional context**
If we make wrapper for this component, and than add wrapper to story, error disappears:
```javascript
const Test = forwardRef((_, ref) => {
  const state = useRef();
  return <div ref={ref}>Hello</div>;
});

const Wrapper = () => <Test />;

const stories = storiesOf('Test', module).add('Default', () => <Wrapper />);
```

**Comment by dylanaubrey** [comment]
This is still an issue on v5.1.9. Although the workaround is valid, when you have a library of hundreds of components, it is not ideal. Is this being looked at?

**Comment by shilman** [comment]
@dylanaubrey Not being looked at AFAIK. Want to take a look?

**Comment by shilman** [comment]
Great Caesar's ghost!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-beta.10 containing PR #7571 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
