### ISSUE TITLE
Have a dedicated command to print debugging information about local environment 

### ISSUE THREAD

**Issue by jamesgeorge007** [storybookjs/storybook#6926]
## The idea

Have a dedicated `info` command that prints out debugging information about the local environment which proves to be useful especially while submitting bug reports. 

### Proposed API
`sb info`

```md
Environment Info:

  System:
    OS: Linux 4.18 Ubuntu 18.10 b(Cosmic Cuttlefish)
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
  Binaries:
    Node: 8.11.4 - /usr/bin/node
    Yarn: 1.17.0-0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 74.0.3729.157
    Firefox: 66.0.5
  npmGlobalPackages:
   @storybook/cli: 5.0.11
```

**Comment by jamesgeorge007** [comment]
@shilman Shall I go ahead and propose a PR?

**Comment by shilman** [comment]
@jamesgeorge007 This is a great idea -- would love a PR!

**Comment by jamesgeorge007** [comment]
cc @shilman

**Comment by shilman** [comment]
Great Caesar's ghost!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-alpha.30 containing PR #6937 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.
