### ISSUE TITLE
Keyboard shortcuts are disruptive and interfere with component interactions

### ISSUE THREAD

**Issue by kaiyoma** [storybookjs/storybook#6930]
Keyboard shortcuts are disruptive and interfere with component interactions. There should be a way to disable them. If I try to type into an input, for instance, Storybook intercepts all the keypresses, which is not desirable.

Is there a way to disable keyboard shortcuts and hide them from the sidebar menu?

**Comment by shilman** [comment]
Closing as a dupe to https://github.com/storybookjs/storybook/issues/6569

**Comment by Valdermeyder** [comment]
Do you have any plans to fix the issue for "Keyboard shortcuts are disruptive"? Because they are still disruptive when '@storybook/html' is used, however, everything works fine when '@storybook/react' is used

**Comment by shilman** [comment]
@Valdermeyder fixed in https://github.com/storybookjs/storybook/pull/7990
