### ISSUE TITLE
Incorrect tsconfig `extends` in Angular 8

### ISSUE THREAD

**Issue by Emobe** [storybookjs/storybook#6934]
**Describe the bug**
storybook tsconfig does not point to the correct tsconfig to extend from

**To Reproduce**
1. Create new angular 8 app
2. Initialise storybook inside the app
3. Run storybook

**Expected behavior**
Check if angular version is 8 and point to correct tsconfig file

**Code snippets**
.storybook/tsconfig.json
`"extends": "../src/tsconfig.app.json"`
should be
`"extends": "../tsconfig.app.json"`

**System:**
 - OS: Arch Linux
 - Framework: Angular
 - Version: 5.0.11

**Comment by kroeder** [comment]
Can confirm, they changed the directory of `tsconfig.app.json` and moved it into the root directory
We should add a check for `< 8.0.0 = src/tsconfig.app.json` and `>= 8.0.0 = ./tsconfig.app.json` 

Maybe it should be double checked again if we need a default tsconfig for app/angular at all. I already forgot why I introduced it but back then it solved a couple of issues

**Comment by kroeder** [comment]
# Workaround
Edit `.storybook/tsconfig.json` and update the `extends` path to `../tsconfig.app.json` instead of `../src/tsconfig.app.json`

**Comment by shilman** [comment]
Fixed in https://github.com/storybookjs/storybook/pull/6940

Released in https://github.com/storybookjs/storybook/releases/tag/v5.1.0-rc.4
