### ISSUE TITLE
First gif on README is ugly on retina screen

### ISSUE THREAD

**Issue by nicgirault** [storybookjs/storybook#6947]
![image](https://user-images.githubusercontent.com/551837/58797013-1d863480-85ff-11e9-80de-ac247cfc6d55.png)

**Comment by shilman** [comment]
@domyen Didn't you have some other plans for this at some point?

**Comment by domyen** [comment]
We can't do much about this without media queries. If we made it higher resolution that would increase the size of the gif for everyone (substantially). Tradeoffs 😅

Closing this. Please reopen if folks can recommend a way forward that balances file size, visual acuity, and something that works with GitHub 🙏

**Comment by nicgirault** [comment]
mmm, I would bet you are dropping ~50% of your users. High screen density (retina and other ones) is the standard at least for developers. This screen is your showcase on which developers make their first impression. I think there is no tradeoff here. I would highly suggest that you reconsider your choice.

This being said, it seems that `srcset` image attribute would do the job and is understood by github readme.
