### ISSUE TITLE
Unable to upgrade from Angular 7 -> 8 with the Angular CLI due to zone.js dependency

### ISSUE THREAD

**Issue by brianmcd** [storybookjs/storybook#6951]
**Describe the bug**
Upgrading from Angular 7 to Angular 8 via the CLI won't proceed due to `@storybook/angular`'s zone.js peerDependency.

**To Reproduce**
```
yarn global add @angular/cli@^7 @storybook/cli
ng new ng8-upgrade-sb
cd ng8-upgrade-sb
sb init
ng update @angular/cli @angular/core
```

Output:
```
Package "@storybook/angular" has an incompatible peer dependency to "zone.js" (requires "^0.8.27", would install "0.9.1").
Incompatible peer dependencies found. See above.
```
And the upgrade stops.

I'd imagine that the zone.js `peerDependency` just needs to be bumped: https://github.com/storybookjs/storybook/blob/8fef8f408f52105f4c48a13d61ab2df2e068080e/app/angular/package.json#L54

**Expected behavior**
The upgrade should complete.

**System:**
 - OS: Linux
 - Framework: angular
 - Version: 5.0.11

**Comment by lyczos** [comment]
I have the same problem.

**Comment by kroeder** [comment]
Thanks for reporting! I'm currently working on a fix but it's blocked by another bug that appeared related to core-js in angular 7.

Can you please try `ng update @angular/cli @angular/core --force`?

**Comment by shilman** [comment]
Closing this as a dupe to #6804 which has some discussion about what's going on (thanks @kroeder !)

**Comment by shilman** [comment]
Not a dupe. Reopening. 😭

**Comment by brianmcd** [comment]
@kroeder - Thanks for working on this!  Upgrading with `--force` does get past the error.

**Comment by shilman** [comment]
Ermahgerd!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.1.0-rc.5 containing PR #6957 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
