### ISSUE TITLE
"document components in Markdown" link doesn't work

### ISSUE THREAD

**Issue by kaiyoma** [storybookjs/storybook#6955]
**Describe the bug**
The "document components in Markdown" link doesn't work.

**To Reproduce**
1. Go to the Notes tab.
2. Click on "document components in Markdown".

**Expected behavior**
The link should work.

**System:**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 5.1.0-rc.4

**Comment by shilman** [comment]
Shiver me timbers!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.1.3 containing PR #6970 that references this issue. Upgrade today to try it out!

Closing this issue. Please re-open if you think there's still more to do.
