### ISSUE TITLE
TypeScript migration in @storybook/ui

### ISSUE THREAD

**Issue by leoyli** [storybookjs/storybook#6975]
## Goal

Follow up #5030, I will use this issue to track the progress of the status in `@storybook/ui`.

## Strategy 

After several weeks and days, I finally have deeper understanding on how our UI get implemented. I'm kind of have some idea how it would be look like by the end. But since UI is likely to be adding feature or fixing bugs frequently, it is **impossible** to move everything at once. Based on my previous TS migration experiences at my company, I would take the following principle as kind of guideline or strategy to manage the complicity: 

- Turn off 'noImplicitAny' flag in `@storybook/ui`.
- Apply separation of concerns, regrouping cohesive logics.
- Decouple several monolith function/component into smaller modular functions.
- Leverage type inference as much as possible, reducing unnecessary typing noise.
- Incrementally shipping adoptions, making sure the package is always ready to be used; this means adding typing or refactoring should, _ideally_, do what they imply.
- Turn back on 'noImplicitAny' flag once the package are properly typed.
- I will assume it will take 5-10 PRs to finish the migration.

After the migration get completed, the UI package should be more readable and easier to be maintained, IMHO. 😃

**Comment by shilman** [comment]
Exciting work @leoyli 🚀
