### ISSUE TITLE
addon-viewport: Add option to disable viewport rotation for custom viewports

### ISSUE THREAD

**Issue by saxoncameron** [storybookjs/storybook#6979]
When registering a custom viewport, the schema is like so
```js
{
    name,
    styles: {width, height},
    type,
}
```

It would be great if we could also specify whether we'd like the viewport to be rotatable; like `rotate: false` in this same object. 

My use-case is that I've added our media-query breakpoint sizes, and the height of those viewports are all 100vh since I'm mainly concerned with the width. Having the ability to rotate these viewports in this case doesn't make sense - so it'd be great if we could opt-out of that functionality on a per-viewport basis.

Also - I've not been able to determine the purpose of 'type'? How/where is this option used?

**Comment by luapaaron** [comment]
+1

**Comment by wa4-fearless-otter** [comment]
I still want this

**Comment by shilman** [comment]
@wa4-fearless-otter PRs welcome!
