### ISSUE TITLE
@storybook/core@4.1.18 is throwing an error on runtime

### ISSUE THREAD

**Issue by mykas** [storybookjs/storybook#6982]
Storybook runtime throws error: Uncaught TypeError: Object(...) is not a function

**To Reproduce**

1. Go to https://github.com/wix/wix-style-react
2. Clone the repo.
3. npm install
4. npm start
5. Open localhost:6006
6. See white screen with an error in console
**Screenshots**
![Screenshot 2019-06-05 at 16 47 57](https://user-images.githubusercontent.com/8919190/58961406-b2c92a80-87b1-11e9-9386-0d25663ab86d.png)

**System:**
 - OS: [MacOS]
 - Browser: [chrome]
 - Framework: [react]
 - Version: [4.1.18]

**Additional context**
This started to happen after reinstalling node_modules. It something related with @emotion/provider.

**Comment by shilman** [comment]
This looks like a react version issue. cc @ndelangen here's your repro?

**Comment by mykas** [comment]
Hey, we found out the issue. It seems that we are using two dependencies that are using `@storybook/react` which uses `@emotion/core` libraries. One of them is direct dependency of our repo and another one is nested. The one which has the latest has @emotion/core 10 version and it win over our dependency chain which lead our storybook 4 to fail.

![image](https://user-images.githubusercontent.com/8919190/59034217-38f97580-8873-11e9-90c8-8389b01f0256.png)

**Comment by mykas** [comment]
We have the workaround to freeze the version, but maybe you could add `@emotion/core` as dependency in `@storybook/ui` ? maybe this will prevent the issue from happening?

**Comment by shilman** [comment]
@mykas I'd try upgrading to 5.1.x and see if it's still an issue. We're unlikely to modify 4.1.x unless this is affecting a lot of people.

**Comment by ndelangen** [comment]
@mykas is anything preventing you from migrating to 5.x? I'm pretty sure it would indeed resolve your issue.

**Comment by mykas** [comment]
@shilman I understand. Still struggling with time to upgrade to storybook 5.

@ndelangen couple of upgrade takes went taking too much of our time. Something with our heavily used third party library `react-live` that gets broken on storybook 5. I believe it might just how we use it that it gets broken or maybe the fact that we need to support React 15 too.

**Comment by ndelangen** [comment]
Storybook 5 supports React15!

(addon-info no longer does)

**Comment by ndelangen** [comment]
Is this still an issue? Have you been able to upgrade to Storybook 5?

**Comment by mykas** [comment]
Hi! We decided to stay for some time on storybook 4 until we will have time to fix the issues for storybook 5. I am closing this issue as we have a workaround for now.
