### ISSUE TITLE
5.1.1 broken decorators?

### ISSUE THREAD

**Issue by leepowellcouk** [storybookjs/storybook#6983]
Just upgraded to 5.1.0 and decorators that we're previously working in my `config.js` file are now throwing errors:

```
// config.js
import React from 'react';
import { withA11y } from '@storybook/addon-a11y';

addDecorator(withA11y);
addDecorator(Story => <Story />);
```

Results in `Error: Unexpected token`

Likewise if I use a custom decorator in a story results in the same:

```
// myDecorator.js
import React from 'react'

export default (getStory, context) => {
  return <div className="center">{getStory(context)}</div>
}


// component.story.js
import MyDecorator from './myDecorator';

// ...
storiesOf( ... )
  .addDecorator(withFormComponentWrapper)
  .add(...)
// ...
```

Results in the same `Error: Unexpected token`. It seems they're not being run through Babel for the transpilation process.

**Comment by leepowellcouk** [comment]
After a bit more investigation with this it turns out Storybook is picking up our babel config - which we don't want Storybook to use. Is there a way of telling Storybook not to use it?

**Comment by ndelangen** [comment]
If you want a storybook specific babel config, you can create a .babelrc in the storybook folder.

**Comment by leepowellcouk** [comment]
@ndelangen - this is what I ended up doing, but ideally I didn't want to use any specific babel config, just the one baked into Storybook.
