### ISSUE TITLE
Documentation for "top bar"

### ISSUE THREAD

**Issue by garrettmaring** [storybookjs/storybook#6985]
**Is your feature request related to a problem? Please describe.**

On https://storybook.js.org/ there is a large picture of a demo Storybook page. There is a top bar with non-default elements. "Canvas", "Docs", a theme switcher, etc.

I haven't been able to find any documentation on what exactly those are. Are they add-ons as well or is that a different sort of plugin space?
 
**Describe the solution you'd like**
Documentation on how to use the top bar and how to recreate the examples in the demo.

**Describe alternatives you've considered**
I considered reading the source...

**Are you able to assist bring the feature to reality?**
Possibly

**Additional context**
<img width="858" alt="Screen Shot 2019-06-05 at 12 34 00 PM" src="https://user-images.githubusercontent.com/8270120/58984925-0ece8780-878f-11e9-9c80-eda8b39a3e92.png">

**Comment by garrettmaring** [comment]
Thanks for adding this to the 5.1.x milestone, @shilman!

In the meantime, is there somewhere I can look (source is fine) to get a basic understanding of how that section works and how I can configure it?

**Comment by shilman** [comment]
@ndelangen can you help him out?

**Comment by ndelangen** [comment]
Yes, documenting this is high priority for me.

**Comment by garrettmaring** [comment]
I'm still interested in using this feature. Has this been documented? If not, is there example code somewhere for this?

**Comment by aromanarguello** [comment]
Is someone working on this? I don't much about those features either but I can learn and document it :)
