### ISSUE TITLE
@storybook/addon-knobs: color selector doesn't work in Firefox

### ISSUE THREAD

**Issue by ericmick** [storybookjs/storybook#6992]
### Bug or support request summary

This is still reproducible in 5.0.11 : https://github.com/storybookjs/storybook/issues/5390

Color selector closes immediately when clicked.  Value does not change.

- @storybook/react 5.0.11
- @storybook/addon-knobs 5.0.11

**Comment by shilman** [comment]
@ericmick What about `5.1.1`?

**Comment by lonyele** [comment]
@ericmick I tested with `5.1.1` and it looks fine for me(Loom is only available to chrome so it is recorded with chrome but I tested with firefox too and it worked ok) https://www.loom.com/share/7591109e616949a1aaf9c582a44fc3f5
