### ISSUE TITLE
@storybook/angular@5.1 moduleMetadata is not rerendering scene

### ISSUE THREAD

**Issue by alexan** [storybookjs/storybook#7002]
**Describe the bug**
I'm using moduleMetadata to mock some services in angular stories via knobs. After updating to storybook 5.1, storybook does update the value from the knob via the service

**To Reproduce**
I prepared a repo containing a story wich works with storybook 5.0.11 but doesn't with 5.1.3
https://github.com/alexan/storybook-module-metadata
https://github.com/alexan/storybook-module-metadata/tree/storybook-5.0
- checkout repository 
- run npm ci
- run npm run storybook
- uncheck isActive knob
- observe isActive is not changing in mocked service
- checkout `storybook-5.0` branch
- run npm ci
- run npm run storybook
- uncheck isActive knob
- isActive is changing in booth service and prop

**Expected behavior**
storybook 5.1 should behave a 5.0.x

**Screenshots**
Storybok 5.1.x:
![Bildschirmfoto 2019-06-07 um 11 06 40](https://user-images.githubusercontent.com/563746/59093613-aad5cb80-8914-11e9-9808-a1816f99bce4.png)

Storybook 5.0.x:
![Bildschirmfoto 2019-06-07 um 11 04 55](https://user-images.githubusercontent.com/563746/59093423-33a03780-8914-11e9-9162-e3b8d76196aa.png)

**Code snippets**
here is the story used in the repository
```
@Injectable({
  providedIn: 'root'
})
export class AppService {
  isActive() {
    return false;
  }
}


@Component({
  selector: 'app-root',
  template: `
    Service active: {{ appService.isActive() }}
  `,
})
export class AppComponent {
  constructor(public appService: AppService) {}
}


storiesOf('app', module)
  .addDecorator(withKnobs)
  .addDecorator(
    moduleMetadata({
      declarations: [
        AppComponent
      ]
    })
  )
  .add('showcase', () => {
    const isActive = boolean('isActive', true);

    return {
      template: `
        <app-root></app-root><br>
        Prop active: {{ isActive }}
      `,
      props: {
        isActive
      },
      moduleMetadata: {
        providers: [
          {
            provide: AppService,
            useValue: {
              isActive() {
                return isActive;
              }
            }
          }
        ]
      }
    };
  });

```
**System:**
 - Framework:  angular
 - Addons: knobs
 - Version: 5.1.3

**Comment by alexan** [comment]
can I implement the story in a different way? Is this unintended behaviour?

**Comment by alexan** [comment]
this is still present in `5.1.4`

**Comment by alexan** [comment]
can anybody provide feedback for this one?

**Comment by alexan** [comment]
where can I start to look for a change wich introduced this behavior. I'm not understanding the codebase enough to fix this myself

**Comment by shilman** [comment]
@alexan You can look in the CHANGELOG to see every Agnular-related change that's been merged https://github.com/storybookjs/storybook/blob/next/CHANGELOG.md

**Comment by alexan** [comment]
ok I checked the versions and https://github.com/storybookjs/storybook/pull/6094 introduced this behavior. I will investigate further. My code relies on angular re rendering the scene

**Comment by alexan** [comment]
@jonrimmer do you think it would be possible to add a parameter to a knob which tells storybook to rerender the sceene on change or not?

**Comment by andrei-ilyukovich** [comment]
@alexan you are not alone) I'm also experiencing the exactly same issue. And can confirm that calling `forceReRender()` doesn't have any impact of the story. I've tried to invoke it inside button knob
```
 button: button("Update Story", () => {
           forceReRender();
 })
```
