### ISSUE TITLE
[addon-notes] console warning (Each child in a list should have a unique "key" prop)

### ISSUE THREAD

**Issue by mtmacdonald** [storybookjs/storybook#7005]
**Describe the bug**
When using the Notes Addon, there's a React console warning: 

```
vendors~main.608b7bf874843e30ef63.bundle.js:88356 Warning: Each child in a list should have a unique "key" prop.

Check the top-level render call using <Styled(div)>. See https://fb.me/react-warning-keys for more information.
    in NotesPanel
    in Unknown
    in Unknown
    in Unknown
    in Unknown (created by Context.Consumer)
    in ManagerConsumer (created by _default)
    in _default (created by Layout)
    in div (created by Context.Consumer)
    in Styled(div) (created by Panel)
    in Panel (created by Layout)
    in div (created by Context.Consumer)
    in Styled(div) (created by Main)
    in div (created by Context.Consumer)
    in Styled(div) (created by Main)
    in Main (created by Layout)
    in Layout (created by Context.Consumer)
    in WithTheme(Layout)
    in Unknown
    in Unknown (created by ResizeDetector)
    in ChildWrapper (created by ResizeDetector)
    in ResizeDetector
    in div (created by Context.Consumer)
    in Styled(div)
    in Unknown
    in Unknown (created by Manager)
    in ThemeProvider (created by Manager)
    in Manager (created by Context.Consumer)
    in Location (created by QueryLocation)
    in QueryLocation (created by Root)
    in LocationProvider (created by Root)
    in HelmetProvider (created by Root)
    in Root
```

**To Reproduce**
1. Install and enable the Notes Addon following the default [readme instructions](https://github.com/storybookjs/storybook/tree/master/addons/notes)
2. Run Storybook
3. Open the console

**Expected behavior**
No console warning.

**System:**
 - OS: [MacOS]
 - Device: [Macbook Pro 2018]
 - Browser: [Chrome]
 - Framework: [React]
 - Addons: [Notes]
 - Version: [e.g. 5.1.3]

**Comment by mydesireiscoma** [comment]
I have same issue if `addon-notes` is installed

**Comment by brendanmckeown** [comment]
I am experiencing the same error in Vue.

**Comment by isametal88** [comment]
Hi, any update on this issue?

**Comment by SQReder** [comment]
bump

**Comment by mtmacdonald** [comment]
Issue is still unresolved for me. I think it's important for release quality that console warnings are fixed, because this tool is used for component testing, and if the tool itself is giving warnings it doesn't look great.

**Comment by shilman** [comment]
@mtmacdonald PRs welcome!

**Comment by laitine** [comment]
bump

**Comment by shilman** [comment]
Also take a look at Storybook Docs, which is intended to replace `addon-info` and `addon-notes`, doesn't have this problem, and is being more actively maintained: https://medium.com/storybookjs/storybook-docspage-e185bc3622bf

**Comment by shilman** [comment]
Ta-da!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-alpha.34 containing PR #8633 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Yowza!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.6 containing PR #8633 that references this issue. Upgrade today to try it out!

**Comment by lesliesu** [comment]
updated to 5.3.9, I still got this issue

**Comment by shilman** [comment]
`addon-notes` is being superceded by `addon-docs`, which fixes a bunch of bugs and is easier to maintain. Please give it a try! https://medium.com/storybookjs/storybook-docspage-e185bc3622bf
