### ISSUE TITLE
Incomplete stories

### ISSUE THREAD

**Issue by agrapine** [storybookjs/storybook#7010]
**Describe the bug**
Starting up storybook brings up only a few stories from the full list. 
If I add a new [xxxx].stories.js or rename one of the existing story file, all is good again :D

**Expected behavior**
Expect storybook to start with all the stories.

**System:**
 - OS: MacOS
 - Device: Macbook Pro 2015
 - Browser: chrome
 - Framework: react
 - Version: 5.1.3

**Additional context**
<img width="407" alt="Screenshot 2019-06-08 at 16 00 16" src="https://user-images.githubusercontent.com/282716/59148973-6b3bdc00-8a07-11e9-83cd-d50a3e56edbb.png">
<img width="219" alt="Screenshot 2019-06-08 at 16 01 54" src="https://user-images.githubusercontent.com/282716/59148974-6bd47280-8a07-11e9-8e43-ffb6be2833df.png">
renamed one story file here... then magic :D
<img width="214" alt="Screenshot 2019-06-08 at 16 05 36" src="https://user-images.githubusercontent.com/282716/59148975-6bd47280-8a07-11e9-9e04-344f62d7584e.png">

**Comment by shilman** [comment]
Is there an error in the browser JS console?

**Comment by agrapine** [comment]
just typescript warnings :(

**Comment by rembrandtreyes** [comment]
I ran into this issue as well. It seems like the issue rises up when the story at the location of the issue is "broken." Could you paste your code for your `Banners.stories.*` I'm curious to see if there is something that is missing from `search trust banner`

**Comment by ndelangen** [comment]
Storybook loads all stories synchronous in `config.js`, when there's an error in 1 story, the storyStore won't be complete. There should be an error in the terminal & browser console.

Fix the story and they should all show up.
