### ISSUE TITLE
dark base theme hides js code snippet

### ISSUE THREAD

**Issue by tenjojeremy** [storybookjs/storybook#7014]
**Describe the bug**
Js Code snippet uses dark text when using storybooks dark theme, which results in the snippet disappearing. 

**To Reproduce**
1. Create readme and add <Modal show={show} animation='centerOut' />```
2. Click reload page
3. open notes panel/tab
4. js snippet code will be hidden 

**Expected behavior**
js snippet text should be white and legible 

**Screenshots**
![image](https://user-images.githubusercontent.com/25231946/59163209-bd860700-8ab2-11e9-987a-11e55b1869b3.png)

Thank you,

**Comment by shilman** [comment]
Egads!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.1.4 containing PR #7057 that references this issue. Upgrade today to try it out!

Closing this issue. Please re-open if you think there's still more to do.

**Comment by tenjojeremy** [comment]
Works great. Thank you
