### ISSUE TITLE
Not work with `webpack2`.

### ISSUE THREAD

**Issue by zhaoyi0113** [storybookjs/storybook#7015]
I am using `webpack2` with `"@storybook/react": "^5.1.3",` but I found that I can't customise my webpack configuration. Because the `config` passed to the customised webpack is not `webpack4` format. As below example:

```
module.exports = async ({ config, mode }) => {
  // `mode` has a value of 'DEVELOPMENT' or 'PRODUCTION'
  // You can change the configuration based on that.
  // 'PRODUCTION' is used when building the static version of storybook.

  config.module.loaders.push({
    test: /\.(js|jsx)$/,
    loader: require.resolve('babel-loader'),
  });

  config.resolve.extensions.push('.jsx', '.js');

  // Return the altered config
  return config;
};
```

It will throw an error saying `loaders.push` is `undefined`. 
I am not sure how to use `storybook` with `webpack2`. Is it supported or is there any workaround?

**Comment by shilman** [comment]
That's correct. Storybook uses Webpack 4. You can read more about upgrading here: https://medium.com/storybookjs/migrating-to-storybook-4-c65b19a03d2c
