### ISSUE TITLE
Docs view PropsTable should steal from addon-info

### ISSUE THREAD

**Issue by jonwilliams-bluescape** [storybookjs/storybook#7018]
The info addon 
https://github.com/storybookjs/storybook/tree/master/addons/info
does a decent job dealing rendering deeply nested props in its PropTable implementation
whereas the docs addon currently dumps everything on one line. 

The use of expanding elipses is nice but even some pretty-printing / newlines would go a long way.

<img width="764" alt="Screen Shot 2019-06-10 at 11 41 50 AM" src="https://user-images.githubusercontent.com/49409459/59207607-5aa97400-8b75-11e9-9112-78d0c7725296.png">

**Comment by shilman** [comment]
@jonwilliams-bluescape Thanks for the request & example! We'll beef this up before we ship 👍

**Comment by patricklafrance** [comment]
@jonwilliams-bluescape does the improvements that landed with the Rich Props table fix this issue?
