### ISSUE TITLE
Add storybook-addon-themes to community addons list

### ISSUE THREAD

**Issue by Yankovsky** [storybookjs/storybook#7052]
Link https://github.com/tonai/storybook-addon-themes

It allows you to select theme in top menu
![https://camo.githubusercontent.com/ceb01675678a451312afac04509d8883b45d95d9/687474703a2f2f732e63737373722e72752f5530324432343854362f323031392d30362d30342d303730392d376f35716868707831722e706e67](https://camo.githubusercontent.com/ceb01675678a451312afac04509d8883b45d95d9/687474703a2f2f732e63737373722e72752f5530324432343854362f323031392d30362d30342d303730392d376f35716868707831722e706e67)
Theme is just a class or classes added to document.body.

I think it is quite useful and should be added to https://storybook.js.org/addons/ and https://storybook.js.org/docs/addons/addon-gallery/ pages.

I've tried to edit Addon Gallery page myself but link is broken or I don't have sufficient permissions
![http://s.csssr.ru/U02D248T6/2019-06-11-1703-e12dy2rdr3.png](http://s.csssr.ru/U02D248T6/2019-06-11-1703-e12dy2rdr3.png)

I am ready to add info to these pages but I don't know how to do that.

**Comment by Yankovsky** [comment]
I still think it will be a good addition.

**Comment by shilman** [comment]
@Yankovsky You can add it here: https://github.com/storybookjs/storybook/blob/master/docs/src/pages/addons/addon-gallery/index.md

Separately, I'll figure out why the link is broken on the site

**Comment by Yankovsky** [comment]
@shilman done
