### ISSUE TITLE
To support nuxt-optimized-images module - https://www.bazzite.com/docs/nuxt-optimized-images/

### ISSUE THREAD

**Issue by p-moreira** [storybookjs/storybook#7060]
**Is your feature request related to a problem? Please describe.**
I can't use nuxt-optimized-images module with Storybook. The `?include` [query](https://www.bazzite.com/docs/nuxt-optimized-images/usage/#include) doest not works in Storybook component preview.

**Describe the solution you'd like**
**Solution 1:** To detect the nuxt-optimized-images module and setup the necessary webpack config.
**Solution 2:** To write a setup guide in the docs.

**Comment by shilman** [comment]
Maybe a good candidate for https://github.com/storybookjs/presets ?

**Comment by backbone87** [comment]
Does nuxt use vue cli 3? If so, you could give vue-cli-plugin-storybook a shot
