### ISSUE TITLE
Case Sensitive issue on Windows

### ISSUE THREAD

**Issue by kershnerd** [storybookjs/storybook#7068]
On Windows, adding `"react-vega": "^6.0.1", "vega": "^5.4.0"` to the package.json file gives the following error when running storybook:

```
ERROR in ./node_modules/react-vega/esm/Vega.js
Module not found: Error: Cannot find file: 'vega.jsx' does not match the corresponding name on disk: '.\node_modules\react-vega\src\Vega.jsx'.
```

This works correctly with a create-create-app but not in storybook.  My understanding is that `case-sensitive-paths-webpack-plugin ` is in both react-scripts and storybook, so not sure that is the issue.

And suggestions on how to fix this?

**System:**
 - OS: [Windows10]
 - Browser: [chrome]
 - Framework: [react]
 - Version: latest

**Additional context**
BTW.. there are no problems running on Ubuntu... this seems to be just a Windows issue.  Also, not sure this relevant, but we are using yarn 1.16.0

**Comment by ndelangen** [comment]
We add `case-sensitive-paths-webpack-plugin` to both webpack (manager & preview).

We don't use vega anywhere in our codebase, is this a package you're using?

If the package.json main entry of either `react-vega` or `vega` has case-inconsistency I'd advice opening a PR on those packages to fix that.

I don't think there's anything we can do here.

I'm surprised these no issue for other platforms..

**Comment by kershnerd** [comment]
Thank you!  I will check vega.
