### ISSUE TITLE
Addon-docs: Support non-story exports in module story format

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#7071]
[Storybook docs](https://medium.com/storybookjs/storybook-docs-sneak-peak-5be78445094a) is shipping with a new story format for ES6 modules based on [this gist](https://gist.github.com/tmeasday/4de20eab47226a870ab1025642ba848c) that treats all named exports as stories.

Opening this issue as a place to discuss how we might also support non-story exports. This came up in https://github.com/storybookjs/storybook/issues/6995 but it is a generally useful feature for exporting reusable story data.

Here's a simple example for the discussion:

```js
export default {
  title: 'components/Button'
}; // stories metadata
export normal = () => <Button>Hello button</Button> // a story
export someData = { foo: 1, bar: 2 } //????
```

Three proposals so far from @tmeasday / @ndelangen / @shilman include marking individual stories, specifying story exports, and filtering non-story exports.

## Marking stories
```js
export normal = () => <Button>Hello button</Button>;
normal.isStory = true;
```

Which could be stylized as:
```js
import { story } from '@storybook/story';
export normal = story(() => <Button>Hello button</Button>);
```

## Specifying story exports
```js
export default {
  title: 'components/Button'
  storyExports: ['normal'] // defaults to all exports as stories
};
...
```

## Filtering non-story exports
```js
export default {
  title: 'components/Button'
  ignoreExports: ['someData'] // defaults to all exports as stories
};
...
```

**Comment by tmeasday** [comment]
@ndelangen I'm sort of interested in why you thought it would bad to annotate functions in this way? If that's a problem we should reconsider annotating the functions with other things like title and parameters

**Comment by shilman** [comment]
More discussion w/ @tmeasday 

1. Specifying the blacklist/whitelist is awkward because it opens up the door for typos etc. Boxing is awkward because it's extra syntax and requires an extra import. Would be much better if this was "just plain javascript"
2. Story blacklist (`ignoreExports`) better than whitelist (`storyExports`) from a discoverability standpoint. If you have a typo in your blacklist, the story will show up and you'll debug it. If you have a typo in your whitelist, the story won't show up and you might not even notice.

Proposed solution:
1. Implement blacklist as an array of names or a regex
2. Implement blacklist as a parameter so that we can add it globally using a standard mechanism
3. Default blacklist is a regex that filters out all named exports that starts with an underscore (i.e. a convention for non-story exports)
4. Users can override this if they prefer another convention, e.g. `dataXXX`

**Comment by tmeasday** [comment]
I think if we can make the black/whitelist easily configurable via params, then we shouldn't have a default -- to me that falls under the purview of magic that the user might not know about and find hard to debug (why is my story `_iLoveUnderscores` not showing up?)

**Comment by ndelangen** [comment]
Here's an idea:

```jsx
import MyComponent from './my-component';

export default {
  title: 'components/MyComponent',
  component: MyComponent,
  stories: {
    normal: { title: 'Normal' },
    special: { title: 'Special' },
    odd: { title: 'Odd' },
  },
};

export const normal = () => <MyComponent type="normal" />;
export const special = () => <MyComponent type="special" />;
export const odd = () => <MyComponent type="odd" />;

export { MyComponent };
```

If we're going to assume users will re-use these `normal`, `special`, `odd` exports in other places, having them clean, means less potential for conflicts, but also from a tree-shaking perspective having this:

```jsx
import withSomeDecorator from 'some-storybook-addon';

export const normal = story(
  () => <MyComponent type="normal" />,
  { decorators: [withSomeDecorator] }
);
```

Will mean 'some-storybook-addon' will go into the user's bundle.

**Comment by ndelangen** [comment]
I agree the api is verbose, the main issue is that it separates the definition from the 'metadata'..

**Comment by tmeasday** [comment]
Hmm, I hear you about the treeshaking, but I think there is a really big downside ergonomically in having to put something in two spots every time you write a story.

**Comment by kylesuss** [comment]
A bit of color on how I found this issue -- mdx mentions on the official docs that you need to export a variable in order to use it in the same mdx file.

https://mdxjs.com/getting-started#defining-variables-with-exports

With that in mind, it is quite likely that many users will attempt to define variables this way as it appears to be the only way to use variables in the .mdx file.

**Comment by shilman** [comment]
Crikey!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-alpha.30 containing PR #7185 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by bdombro** [comment]
Hint: To use the new feature you can now allowList using `includeStories: ['myStory1', ...]` or blockList using `excludeStores: ['myNonStoryExport', ...]` in `export default`
