### ISSUE TITLE
combined knobs default value @5.1.0

### ISSUE THREAD

**Issue by stropho** [storybookjs/storybook#7079]
**Describe the bug**
We've been using a feature of Knobs addon since storybook@3. A feature the allowed us using one knob value in a different one

**Steps To Reproduce**
1. Create an Object of strings, such as `const BUTTON_MODIFIER = {A: 'a', B: 'b'}`
2. Create a story with a React component accepting an array prop
3. use an array knob with combination of select knob
```jsx
<Button
  customClassNames={array(
    'customClassNames', 
    [select('CSS BUTTON_MODIFIER', BUTTON_MODIFIER)]
  )}
/>
```
	
**Expected behavior**
If a user selected a value from the select knob, it should be added to the array knob
As mentioned, using it since storybook@3, screenshots are from storybook@5.0.11
https://prnt.sc/o1as57
https://prnt.sc/o1asi9

**Actual Result**
storybook@^5.1 https://prnt.sc/o1atav

**System:**
 - OS: Ubuntu
 - Browser: Chromium, Firefox
 - Framework: react
 - Addons: knobs
 - Version: ^5.1.0 and also the "latest" 5.2.0-alpha.24

**Comment by stropho** [comment]
Anybody interested in this ?
I found another problem with the `info addon` - it breaks if the text option includes tabs. For example 
```js
storiesOf('Button', module)
.add('simple button', () => {
	return (		
		</button/>
	);
}, {
	info: {
               // TABS are present in the `text`
		text: `
		Very good button.
		Awesome!
    `,
	},
});
```
As mentioned before, it worked in storybook@5.0.11
The error now says "Cannot read property 'defaultText' of undefined" - something with the syntax-highlighter probably

**Comment by stropho** [comment]
This is still a valid issue  @Armanio @leoyli

**Comment by jesusmaldonado** [comment]
Still broken

**Comment by stropho** [comment]
reminding ... :reminder_ribbon:

**Comment by shilman** [comment]
@stropho any interest in trying to fix this?

**Comment by stropho** [comment]
I can definitely give it a try. I have never really investigated the code of storybook or its addons. Can you give me some pointer where to start ? I mean I can just read the code but if you possibly know where the problem might reside, that would be great.

**Comment by shilman** [comment]
@stropho I'm not sure what the problem is. However if I was going to debug it, I'd get the storybook repo set up on my dev machine, create a repro in `examples/official-storybook`, and then debug it there, so that I could edit the storybook source and have the storybook hot-reload using `yarn dev`. More info in CONTRIBUTING.md.

**Comment by stropho** [comment]
It took me a time, but at least I figured out that this problem first occurred in `v5.1.0-alpha.25`. That means somewhere in https://github.com/storybookjs/storybook/compare/v5.1.0-alpha.24...v5.1.0-alpha.25

The diff even contains
```diff
-    // But, if the user changes the code for the defaultValue we should set
-    // that value instead.
```
And now just to find what change broke the behavior described in this issue :rofl: 


Tried with this snippet if anybody's interested
```diff
diff --git a/examples/official-storybook/stories/addon-knobs.stories.js b/examples/official-storybook/stories/addon-knobs.stories.js
index 932df0c43..4a972bb40 100644
--- a/examples/official-storybook/stories/addon-knobs.stories.js
+++ b/examples/official-storybook/stories/addon-knobs.stories.js
@@ -316,6 +316,14 @@ storiesOf('Addons|Knobs.withKnobs', module)
   ))
   .add('accepts story parameters', () => <div>{text('Rendered string', '<h1>Hello</h1>')}</div>, {
     knobs: { escapeHTML: false },
+  })
+  .add('selectToText', () => {
+    const selectOptions = select('Select Option', ['A', 'B'], 'A');
+    return (
+      <Fragment>
+        <div>{text('overriden by select', selectOptions)}</div>
+      </Fragment>
+    );
   });
 
 storiesOf('Addons|Knobs.withKnobs using options', module)
```

**Comment by stropho** [comment]
Hopefully next year after xmas,....

**Comment by stropho** [comment]
So I see it has been added to a hotlist. Does it mean that someone is working on it @shilman ? You know, just in case a find some spare time next week... :man_shrugging:

**Comment by adriencaccia** [comment]
Hi @stropho I managed to make it temporarily work with this solution https://github.com/storybookjs/storybook/issues/3855#issuecomment-540113248

**Comment by stropho** [comment]
@adriencaccia thx for the message. I don't feel comfortable with the solution as long as it is not documented anywhere. That way, the functionality could be removed just like that any time.
Let's hope for the best in version 6 :crossed_fingers:
