### ISSUE TITLE
Contexts addon is missing core-js dependency

### ISSUE THREAD

**Issue by emmenko** [storybookjs/storybook#7083]
**Describe the bug**
The `contexts` addons package is missing an explicit dependency of `core-js`, which causes problems when hoisting modules (e.g. yarn workspaces).
Other addons packages have it (e.g. https://github.com/storybookjs/storybook/blob/6d3d4fafd2888b13d2cb8eb1aa987cec0100775f/addons/a11y/package.json#L37), so we should define it there as well.

**Comment by shilman** [comment]
Egads!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.1.5 containing PR #7094 that references this issue. Upgrade today to try it out!

Closing this issue. Please re-open if you think there's still more to do.

**Comment by emmenko** [comment]
Awesome, thanks a lot for the quick fix! I’ll try it out later
