### ISSUE TITLE
build-storybook does not reflect last code changes

### ISSUE THREAD

**Issue by x1c0** [storybookjs/storybook#7085]
**Describe the bug**
I have to use `build-storybook` in order to run a local server so that after I can run visual regression tests on top of it.

My issue is that if I update one component style (using angular) and I run `backstop test` then I see the style change immediately as expected.

If I run `build-storybook -c .storybook -o .out` && `http-server .out` i get old style.. 
Is this some cache issue? is the angular app not being totally recompiled again?

**System:**
 - OS: [MacOS]
 - Framework: [angular]
 - Version: [5.1.3]

**Comment by x1c0** [comment]
If I hit several time hard reload then the change appears.. maybe is some caching issue from http-server :/

**Comment by DoviMaj** [comment]
I got the same behavior, when deleting a story it still appears on build, 
For it to disapear I need to hard refresh a couple of times
