### ISSUE TITLE
[addon-centered] installs not needed packages

### ISSUE THREAD

**Issue by darkowic** [storybookjs/storybook#7087]
**Describe the bug**
`@storybook/addon-centered` installs `preact` and `mithril` packages in my `react` project. Why?

**To Reproduce**
Install `@storybook/addon-centered` and `preact` nad `mithril` will be installed as a required dependency...

**Expected behavior**
Do not install any not needed packages. See my `package-lock.json`
```
    "@storybook/addon-centered": {
      "version": "5.1.4",
      "resolved": "https://registry.npmjs.org/@storybook/addon-centered/-/addon-centered-5.1.4.tgz",
      "integrity": "sha512-WhMjlZFtQk1U9Te3eClUV10lp/ICcXh4FZ0pc2WEpDvoCvsSsXDV8Gr4b3x3Fiu4ytpHdRgqsxoPf8taNwXShg==",
      "dev": true,
      "requires": {
        "core-js": "^3.0.1",
        "global": "^4.3.2",
        "mithril": "*",
        "preact": "*",
        "react": "*",
        "util-deprecate": "^1.0.2"
      },
      "dependencies": {
        "core-js": {
          "version": "3.1.3",
          "resolved": "https://registry.npmjs.org/core-js/-/core-js-3.1.3.tgz",
          "integrity": "sha512-PWZ+ZfuaKf178BIAg+CRsljwjIMRV8MY00CbZczkR6Zk5LfkSkjGoaab3+bqRQWVITNZxQB7TFYz+CFcyuamvA==",
          "dev": true
        }
      }
    },
```
I have obviously `react` already installed. `preact` and `mithril` has been added to my `node_modules`

**System:**
- npm - 6.9.0
- framework: react
 - Version: 5.1.4

**Comment by darkowic** [comment]
Probably still a problem mr bot

czw., 4 lip 2019, 22:44 użytkownik stale[bot] <notifications@github.com>
napisał:

**Comment by shilman** [comment]
Egads!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-alpha.37 containing PR #7315 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Egads!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.1.10 containing PR #7315 that references this issue. Upgrade today to try it out!
