### ISSUE TITLE
Warning: Received `true` for a non-boolean attribute `loading`

### ISSUE THREAD

**Issue by gajusp** [storybookjs/storybook#7089]
**Describe the bug**

Create the new project in angular with storybook 

ng new angular-storybook-app
cd angular-storybook-app
npm install @storybook/angular --save-dev
npm install babel-loader @babel/core --save-dev 

I have follow the below steps mentioned in this site - https://storybook.js.org/docs/guides/guide-angular/
 

**To Reproduce**
1. Follow the above mentioned steps
2.run the storybook project - npm run storybook
3. See error (open the console se the below error)
Warning: Received `true` for a non-boolean attribute `loading`.

If you want to write it to the DOM, pass a string instead: loading="true" or loading={value.toString()}.
    in div (created by Context.Consumer)
    in Styled(div) (created by SidebarItem)
    in SidebarItem
    in div (created by Context.Consumer)
    in Styled(div)
    in Unknown
    in Unknown (created by Context.Consumer)
    in Styled(Component) (created by Sidebar)
    in div (created by SimpleBar)
    in div (created by SimpleBar)
    in div (created by SimpleBar)
    in div (created by SimpleBar)
    in div (created by SimpleBar)
    in div (created by SimpleBar)
    in SimpleBar
    in Unknown (created by Context.Consumer)
    in Styled(Component) (created by ScrollArea)
    in ScrollArea (created by Context.Consumer)
    in Styled(ScrollArea) (created by Sidebar)
    in nav (created by Context.Consumer)
    in Styled(nav) (created by Sidebar)
    in Sidebar (created by Context.Consumer)
    in ManagerConsumer (created by _default)
    in _default (created by Layout)
    in div (created by Context.Consumer)
    in Styled(div) (created by Nav)
    in Nav (created by Layout)
    in Layout (created by Context.Consumer)
    in WithTheme(Layout)
    in Unknown
    in Unknown (created by ResizeDetector)
    in ChildWrapper (created by ResizeDetector)
    in ResizeDetector
    in div (created by Context.Consumer)
    in Styled(div)
    in Unknown
    in Unknown (created by Manager)
    in ThemeProvider (created by Manager)
    in Manager (created by Context.Consumer)
    in Location (created by QueryLocation)
    in QueryLocation (created by Root)
    in LocationProvider (created by Root)
    in HelmetProvider (created by Root)
    in Root

**Expected behavior**
no console error should give if we are creating new project

**Screenshots**

**System:**
 - OS: MacOS
 - Device: Macbook Pro 2018
 - Browser:  chrome
 - Framework:angular
 - Version: [
"@angular/animations": "~7.2.0",
    "@angular/common": "~7.2.0",
    "@angular/compiler": "~7.2.0",
    "@angular/core": "~7.2.0",
    "@angular/forms": "~7.2.0",
    "@angular/platform-browser": "~7.2.0",
    "@angular/platform-browser-dynamic": "~7.2.0",
    "@angular/router": "~7.2.0",
    "@storybook/addon-actions": "^5.1.3",
    "@storybook/addon-links": "^5.1.3",
    "@storybook/addons": "^5.1.3",
    "@storybook/theming": "^5.1.3",
    "core-js": "^2.5.4",
    "rxjs": "~6.3.3",
    "tslib": "^1.9.0",
    "zone.js": "~0.8.26"
]

**Additional context**

Not sure what is missing, Please help

Thanks in advance

**Comment by jnielson94** [comment]
Duplicates #7049

**Comment by shilman** [comment]
Closing as dupe to #7049

**Comment by gajusp** [comment]
@shilman - Could you please let me know how to fix this issue

**Comment by shilman** [comment]
@gajusp i'll be releasing a fix for it in the next few hours. please track #7049 for the fix
