### ISSUE TITLE
Storybook 5 doesn't seem to render in IE 11

### ISSUE THREAD

**Issue by piperchester** [storybookjs/storybook#7093]
**Describe the bug**
Not sure if this is a known bug already (didn't see it as a pre-existing issue) but we don't see our Storybook rendering in IE 11. 

We suspect it's related to `Object.assign` not being transpiled somewhere: https://github.com/storybookjs/storybook/search?q=Object.assign&unscoped_q=Object.assign

Opening to see if others have experienced this issue, or if it's likely a problem that's locally scoped to our setup.

**To Reproduce**
Launch Storybook ^5 in IE 11. 

**Expected behavior**
Storybook renders.

**Screenshots**
<img width="1465" alt="Screen Shot 2019-06-13 at 11 59 51 AM" src="https://user-images.githubusercontent.com/1530684/59460011-f126a100-8dd2-11e9-997a-c20b2c2f8170.png">

**System:**
 - OS: Windows 10
 - Browser: IE 11
 - Framework: React
 - Version: ^5.0.11

**Comment by piperchester** [comment]
Closing this out -- it looks like an issue with our local setup. Apologies for any unwarranted FUD!

**Comment by shilman** [comment]
@piperchester relieved to hear that! 😅

**Comment by Badlapje** [comment]
If anyone else has this issue and winds up here: for us it was the usage of an arrow function in our config.js.  We solved it by changing it to the below (the function in the forEach was the arrow function before).

```
function loadStories() {
  req.keys().forEach(function(filename) {
    req(filename)
  });
}
```

**Comment by binomialstew** [comment]
@piperchester, what was your local issue? We're seeing the same error in IE11 and think your solution might shed some light.
