### ISSUE TITLE
Upgrade to Storybook 5.0 to 5.1 overlapping addon panel's State tab content on other tabs

### ISSUE THREAD

**Issue by gsaran** [storybookjs/storybook#7099]
**Describe the bug**
Upgraded Storybook from 5.0.x to 5.1.4, content of State tab in addon sidepanel overlaps content of other tabs: Readme, Actions or Knobs. 

**To Reproduce**
Add any story with initial state using withState() from @dump247/storybook-state

**Expected behavior**
On tab change, content of State tab should be hidden

**Screenshots**
![image](https://user-images.githubusercontent.com/18233426/59526783-d5d99580-8ea7-11e9-8fb8-fa1dd6cdd26f.png)
![image](https://user-images.githubusercontent.com/18233426/59526791-da9e4980-8ea7-11e9-8ee3-bf04d2aae133.png)

**Code snippets**
stories.add(
  'Component',
  withReadme(
    ComponentReadme,
    withState(
      {
        previousSize: 200,
        size: 200,
      },
      store =>{.....})));

**Versions:**
@storybook/react: 5.1.4 
@dump247/storybook-state: 1.6.0
react: 16.8.6
react-dom: 16.8.6

**Additional context**
Tested with latest version of storybook 5.1.8 but problem still exists. It was working fine with Storybook 5.0.11

**Comment by shilman** [comment]
Is this a problem with any of the other storybook addons, or is it something about `storybook-state`?

**Comment by gsaran** [comment]
It's an issue with just storybook-state other add-ons are working fine.

**Comment by shilman** [comment]
Maybe open an issue on the `storybook-state` repo?

**Comment by gsaran** [comment]
Upgrading to storybook v5.1.9 and @dump247/storybook-state to v1.6.1 fixed the issue.
