### ISSUE TITLE
[Angular] [bug] Automatic component declaration for Angular not working with `forRoot`

### ISSUE THREAD

**Issue by pascaliske** [storybookjs/storybook#7106]
**Describe the bug**
One of the last Storybook releases introduced a new behavior for NgModules where Storybook only declares components dynamically if they were not declared already inside of an imported NgModule (see #6666 - Thanks to @MaximSagan for his awesome work!).

This new behavior also introduces an error with NgModules imported by a static `forRoot` method which is a really common pattern for Angular apps:

**TypeError: Cannot read property 'value' of undefined**

I already traced the error down to the [line 60 in angular helpers](https://github.com/storybookjs/storybook/blob/v5.1.8/app/angular/src/client/preview/angular/helpers.ts#L60). I would suggest to check the importItem for an existing key `ngModule` to identify `forRoot`-imports.

<details>
  <summary>Click to expand diff</summary>
  
  ```diff
    const extractNgModuleMetadata = (importItem: any): NgModule => {
  + const target = importItem && importItem.ngModule ? importItem.ngModule : importItem;
    const decoratorKey = '__annotations__';
    const decorators: any[] =
      Reflect && Reflect.getOwnPropertyDescriptor
  -     ? Reflect.getOwnPropertyDescriptor(importItem, decoratorKey).value
  -     : importItem[decoratorKey];
  +     ? Reflect.getOwnPropertyDescriptor(target, decoratorKey).value
  +     : target[decoratorKey];

      if (!decorators || decorators.length === 0) {
        return null;
      }

      const ngModuleDecorator: NgModule | undefined = decorators.find(
        decorator => decorator instanceof NgModule
      );
      if (!ngModuleDecorator) {
        return null;
      }
      return ngModuleDecorator;
    };
  ```
</details>

**I can provide a PR with this fix if you're fine with this change.**

**To Reproduce**
Repo: https://github.com/pascaliske/form-elements
Branch: `feature/v8`
Problematic line: https://github.com/pascaliske/form-elements/blob/feature/v8/.storybook/config.ts#L24
1. Clone repo at branch `feature/v8`
2. Start storybook with `yarn run build && yarn run storybook`
3. See error in almost every story

**Expected behavior**
Storybook can extract Metadata from imported NgModules both with or without `forRoot`.

**Screenshots**
n/a

**Code snippets**
n/a

**System:**
 - OS: MacOS 10.14.5
 - Device: Macbook Pro 2019
 - Browser: chrome
 - Framework: angular
 - Addons: notes, knobs, actions, links
 - Version: v5.1.8

**Additional context**
n/a

**Comment by methodus** [comment]
Maybe my issue (https://github.com/storybookjs/storybook/issues/7157) is related to this. Any work-a-rounds?

**Comment by pascaliske** [comment]
@methodus Yes, your issue describes the same bug.

I have a workaround (provided inside the collapsed diff above) which requires to edit the storybook source code inside node_modules but im willing to extract a PR from this issue changing the storybook code for a future release.

Until the issue is fixed I would suggest to create a little script that applies the above diff and put that script in your npm / yarn `postinstall` script.

**Comment by methodus** [comment]
Do you mean this commit? https://github.com/pascaliske/form-elements/pull/105/commits/3f00b3c9818b94e0bbac40626ea02095199012d0

**Comment by pascaliske** [comment]
@methodus yes but inside the `storybook-patch.js` you need to change the search and replace strings for the above diff:

<details>
    <summary><code>storybook-patch.js</code></summary>

    #!/usr/bin/env node
    const { readFile, writeFile } = require('fs')
    const { join, dirname } = require('path')
    const { promisify } = require('util')
    const chalk = require('chalk')

    /* tslint:disable:max-line-length */
    const SEARCH = `
        var decoratorKey = '__annotations__';
        var decorators = Reflect && Reflect.getOwnPropertyDescriptor
            ? Reflect.getOwnPropertyDescriptor(importItem, decoratorKey).value
            : importItem[decoratorKey];
    `
    const REPLACE = `
        var target = importItem && importItem.ngModule ? importItem.ngModule : importItem;
        var decoratorKey = '__annotations__';
        var decorators = Reflect && Reflect.getOwnPropertyDescriptor
            ? Reflect.getOwnPropertyDescriptor(target, decoratorKey).value
            : target[decoratorKey];
    `
    /* tslint:enable:max-line-length */

    async function execute() {
        const path = dirname(require.resolve('@storybook/angular'))
        const file = join(path, 'preview', 'angular', 'helpers.js')
        const contents = await promisify(readFile)(file, 'utf8')

        // only replace the exact search pattern
        if (!contents.includes(SEARCH)) {
            console.warn(
                chalk.yellow(
                    // tslint:disable-next-line
                    '@storybook/angular was not patched as their source code changed or the patch is already applied.',
                ),
            )
        }

        await promisify(writeFile)(file, contents.replace(SEARCH, REPLACE), 'utf8')
    }

    execute().catch(e => console.error(e.toString()))
</details>

**Comment by cormickjbrowne** [comment]
@pascaliske I ran your script and I can see that this line...
```
var target = importItem && importItem.ngModule ? importItem.ngModule : importItem;
```

...was added in
`node_modules\@storybook\angular\dist\client\preview\angular\helpers.js`

but I'm still seeing the same error in storybook. The `importItem` that it's trying to load looks like this:
```
/**
 * @fileoverview added by tsickle
 * @suppress {checkTypes} checked by tsc
 */
var HighchartsChartModule = /** @class */ (function () {
    function HighchartsChartModule() {
    }
    HighchartsChartModule.decorators = [
        { type: NgModule, args: [{
                    declarations: [HighchartsChartComponent],
                    exports: [HighchartsChartComponent]
                },] }
    ];
    /** @nocollapse */
    HighchartsChartModule.ctorParameters = function () { return []; };
    return HighchartsChartModule;
}());
```

Any thoughts?

**Comment by pascaliske** [comment]
@cormickjbrowne How did you import your module in Storybook? If you log out the `target` variable it should contain the actual ngModule which is required by sotrybook:

<img width="917" alt="log-imports" src="https://user-images.githubusercontent.com/7473880/60019280-ccadad00-968d-11e9-9ab9-014e75c4f226.png">

My fix above works for the cases where the `forRoot` convention of Angular is used. The `forRoot` returns an object containing the ngModule with providers instead of providing the ngModule directly which will be considered by the target variable.

**Comment by pascaliske** [comment]
For my own Angular library I can confirm that the automatic component declaration works together with compiled files (built with `ng-packagr`) if I build the lib with the Angular compiler flag `"annotateForClosureCompiler": false,` turned off. This compiles Angulars decorators using tslibs `__decorate` function which injects the `__annotations__` metadata correctly.

**Comment by pascaliske** [comment]
Besides the problem with AOT-compiled code I would suggest to implement the following change which fixes the actual error:

<details>
  <summary>Click to expand diff</summary>
  
  ```diff
    const extractNgModuleMetadata = (importItem: any): NgModule => {
  +   const target = importItem && importItem.ngModule ? importItem.ngModule : importItem;
      const decoratorKey = '__annotations__';
      const decorators: any[] =
  -     Reflect && Reflect.getOwnPropertyDescriptor
  -       ? Reflect.getOwnPropertyDescriptor(importItem, decoratorKey).value
  -       : importItem[decoratorKey];
  +     Reflect && Reflect.getOwnPropertyDescriptor && Reflect.getOwnPropertyDescriptor(target, decoratorKey)
  +       ? Reflect.getOwnPropertyDescriptor(target, decoratorKey).value
  +       : target[decoratorKey];

      if (!decorators || decorators.length === 0) {
        return null;
      }

      const ngModuleDecorator: NgModule | undefined = decorators.find(
        decorator => decorator instanceof NgModule
      );
      if (!ngModuleDecorator) {
        return null;
      }
      return ngModuleDecorator;
    };
  ```
</details>

**Comment by pascaliske** [comment]
It would be awesome if we can keep this open. I just provided a PR (#7224) to fix this error hopefully we can merge it. 😊

**Comment by shilman** [comment]
Ooh-la-la!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-beta.9 containing PR #7224 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by pascaliske** [comment]
The bugfix from the PR works as expected. Thanks! 🙂
