### ISSUE TITLE
ERROR:  in ./node_modules/core-js/internals/array-for-each.js Module not found: Error: Can't resolve '../internals/array-methods'

### ISSUE THREAD

**Issue by ubaid-dev** [storybookjs/storybook#7113]
Problem with core-js package.

After running component explorer command `yarn run storybook` i end up with this issue.
![storybook1](https://user-images.githubusercontent.com/38039843/59622739-14d34980-913b-11e9-88a3-9a8ddfbf2e0d.JPG)

Requiring module that doesn't exists;
![storybook2](https://user-images.githubusercontent.com/38039843/59622965-aa6ed900-913b-11e9-88c8-7be1f374c248.JPG)

**System:**
 - OS: Windows 10
 - Node - 10.15.1 
 - Npm - 6.4.1

**Comment by ndelangen** [comment]
what the? how can that happen? 

so array-for-each was found, but array-methods is not?
These paths are there for core-js v3, What version have you installed?

**Comment by ubaid-dev** [comment]
I started with this tutorial [https://www.learnstorybook.com/react/en/get-started/](url) and end up with issue i described above. This file looks different in the latest version of core-js.

**Comment by abruzzihraig** [comment]
I got the same issue when I try to start with the tutorial https://www.learnstorybook.com/react/en/get-started/. And the core-js version is 3.1.4 in it.

**Comment by ndelangen** [comment]
When I'm installing `core-js` v3.1.4, within the file: `node_modules/core-js/internals/array-for-each.js` I get:

```js
'use strict';
var $forEach = require('../internals/array-iteration').forEach;
var sloppyArrayMethod = require('../internals/sloppy-array-method');

// `Array.prototype.forEach` method implementation
// https://tc39.github.io/ecma262/#sec-array.prototype.foreach
module.exports = sloppyArrayMethod('forEach') ? function forEach(callbackfn /* , thisArg */) {
  return $forEach(this, callbackfn, arguments.length > 1 ? arguments[1] : undefined);
} : [].forEach;
```

no references to `../internals/array-methods`..

Does anyone have a reproduction repo I can checkout?When I'm installing `core-js` v3.1.4, within the file: `node_modules/core-js/internals/array-for-each.js` I get:

```js
'use strict';
var $forEach = require('../internals/array-iteration').forEach;
var sloppyArrayMethod = require('../internals/sloppy-array-method');

// `Array.prototype.forEach` method implementation
// https://tc39.github.io/ecma262/#sec-array.prototype.foreach
module.exports = sloppyArrayMethod('forEach') ? function forEach(callbackfn /* , thisArg */) {
  return $forEach(this, callbackfn, arguments.length > 1 ? arguments[1] : undefined);
} : [].forEach;
```

no references to `../internals/array-methods`..

Does anyone have a reproduction repo I can checkout?

**Comment by svanbelleghem** [comment]
Not sure if it's gonna help, but I resolved this issue by removing the node_modules folder and running Yarn install again.
