### ISSUE TITLE
Options knob throws 'Object(...) is not a function'

### ISSUE THREAD

**Issue by robbertolierook** [storybookjs/storybook#7116]
**Describe the bug**
Options knob throws `Object(...) is not a function` error

**To Reproduce**
I used this knob directly on my component:
```
    defaultValue={options(
          "Default Value",
          { First: 1, Second: 2, Third: 3, },
          1,
          { display: 'check', }
        )}
```
The Knob did not render in the addon panel, and the story display threw this error: 

```
TypeError: Object(...) is not a function
    at webpackHotUpdate../src/stories/checkboxGroup.stories.js._index_stories__WEBPACK_IMPORTED_MODULE_2__.default.add.readme.content (checkboxGroup.stories.js:29)
    at client_api.js:114
    at wrapper (index.js:179)
    at make-decorator.js:17
    at make-decorator.js:29
    at client_api.js:112
    at client_api.js:114
    at jsxDecorator (index.js:98)
    at client_api.js:112
    at client_api.js:114
```

Since it also mentions the 'readme' addon, it might be a problem with the combination of both, which is weird, because all other knobs work perfectly.

**Expected behavior**
The knob to work and render checkboxes

**System:**
 - OS: [MacOS]
 - Device: [Macbook Pro 2018]
 - Browser: [chrome]
 - Framework: [react]
 - Addons: [knobs, storybook-readme]
 - Version: [5.0.5]

**Comment by zackphilipps** [comment]
@robbertolierook how are you importing the options knob?

**Comment by robbertolierook** [comment]
Like the rest of the knobs:

```
import {
  text, boolean, select, options,
} from '@storybook/addon-knobs';
```

**Comment by zackphilipps** [comment]
@robbertolierook according to the docs, it's actually `optionsKnob`, so `options` is probably something else:

```js
import { optionsKnob as options } from '@storybook/addon-knobs';
```

Not intuitive, but 🤷‍♂

**Comment by robbertolierook** [comment]
Oh golly, thanks for that! Now it works:)
