### ISSUE TITLE
Static build loop

### ISSUE THREAD

**Issue by chulanovskyi** [storybookjs/storybook#7136]
**Describe the bug**
Static build falls into infinity rendering of nested instances. See *gif* for details

**To Reproduce**
1. Upgrade to the latest version
2. Make static build - `build-storybook -c .storybook -o build`
3. Start - `serve -s build/`

**Expected behavior**
Renders as a usual (development) build (but faster ;) )

**Screenshots**
![Example](https://i.ibb.co/tZyWqW8/ezgif-2-4d3baabeea3b.gif)

**Code snippets**
[Storybook config](https://gist.github.com/chulanovskyi/dcb8908b336f1e57e52f2a34b13cfff0)
[Webpack config](https://gist.github.com/chulanovskyi/68d512c13c874ce304aac9003fd648ab)

**System:**
 - OS: Ubuntu
 - Browser: Chrome
 - Framework: React
 - Addons:
```
    "@sambego/storybook-state": "1.3.4",
    "@storybook/addon-actions": "5.1.8",
    "@storybook/addon-info": "5.1.8",
    "@storybook/addon-knobs": "5.1.8",
    "@storybook/addon-links": "5.1.8",
    "@storybook/addon-options": "5.1.8",
    "@storybook/addon-storysource": "5.1.8",
    "@storybook/react": "5.1.8",
    "@storybook/theming": "5.1.8",
```
 - Version: 5.1.8

**Comment by shilman** [comment]
dupe to https://github.com/storybookjs/storybook/issues/5269 ?
