### ISSUE TITLE
addons-info stylesheetBase sets info to `height: 110vh` which cuts off propTypes table

### ISSUE THREAD

**Issue by jendowns** [storybookjs/storybook#7140]
**Describe the bug**
In the pre-release `5.2.0-alpha.27`, the `stylesheetBase` for addons-info now has `height: 110vh` applied, which cuts off the propTypes table. 

Note: we are aware of the risk of using pre-releases! In this case we are trying to get fixes from https://github.com/storybookjs/storybook/pull/6016 😅 

**To Reproduce**
1. Upgrade to `5.2.0-alpha.27`
2. View a component's "Info" 
3. Scroll down to the bottom fo the "Info" pane and see that the propTypes table is cut off (you may need to reduce the size of your browser window to get a scrollbar)

**Expected behavior**
The propTypes in "Info" is not cut off.

**System:**
 - OS: MacOS
 - Device: Macbook Pro 2018
 - Browser: Chrome 75
 - Framework: React
 - Version: 5.2.0-alpha.28

**Comment by shilman** [comment]
Jiminy cricket!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-alpha.30 containing PR #7141 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

**Comment by shilman** [comment]
Son of a gun!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.1.10 containing PR #7141 that references this issue. Upgrade today to try it out!
