### ISSUE TITLE
Building Storybook fails, unable to find Jest globals

### ISSUE THREAD

**Issue by jackiehluo** [storybookjs/storybook#7142]
**Describe the bug**
Running `yarn build-storybook` fails consistently after upgrading our dependencies. The "Compiling preview" step fails with this output (just a small sample):

```
ERR! => Failed to build the preview
ERR! /Users/jackieluo/Development/square-console/packages/sqc-foundation/components/__tests__/Alert.test.tsx
ERR! [tsl] ERROR in /Users/jackieluo/Development/square-console/packages/sqc-foundation/components/__tests__/Alert.test.tsx(6,1)
ERR!       TS2582: Cannot find name 'describe'. Do you need to install type definitions for a test runner? Try `npm i @types/jest` or `npm i @types/mocha`.
ERR! /Users/jackieluo/Development/square-console/packages/sqc-foundation/components/__tests__/Alert.test.tsx
ERR! [tsl] ERROR in /Users/jackieluo/Development/square-console/packages/sqc-foundation/components/__tests__/Alert.test.tsx(7,3)
ERR!       TS2582: Cannot find name 'test'. Do you need to install type definitions for a test runner? Try `npm i @types/jest` or `npm i @types/mocha`.
ERR! /Users/jackieluo/Development/square-console/packages/sqc-foundation/components/__tests__/Alert.test.tsx
ERR! [tsl] ERROR in /Users/jackieluo/Development/square-console/packages/sqc-foundation/components/__tests__/Alert.test.tsx(9,5)
ERR!       TS2304: Cannot find name 'expect'.
ERR! /Users/jackieluo/Development/square-console/packages/sqc-foundation/components/__tests__/Alert.test.tsx
ERR! [tsl] ERROR in /Users/jackieluo/Development/square-console/packages/sqc-foundation/components/__tests__/Alert.test.tsx(10,5)
ERR!       TS2304: Cannot find name 'expect'.
ERR! /Users/jackieluo/Development/square-console/packages/sqc-foundation/components/__tests__/Alert.test.tsx
ERR! [tsl] ERROR in /Users/jackieluo/Development/square-console/packages/sqc-foundation/components/__tests__/Alert.test.tsx(13,3)
ERR!       TS2582: Cannot find name 'test'. Do you need to install type definitions for a test runner? Try `npm i @types/jest` or `npm i @types/mocha`.
ERR! /Users/jackieluo/Development/square-console/packages/sqc-foundation/components/__tests__/Alert.test.tsx
ERR! [tsl] ERROR in /Users/jackieluo/Development/square-console/packages/sqc-foundation/components/__tests__/Alert.test.tsx(15,5)
ERR!       TS2304: Cannot find name 'expect'.
ERR! /Users/jackieluo/Development/square-console/packages/sqc-foundation/components/__tests__/Alert.test.tsx
ERR! [tsl] ERROR in /Users/jackieluo/Development/square-console/packages/sqc-foundation/components/__tests__/Alert.test.tsx(16,5)
ERR!       TS2304: Cannot find name 'expect'.
```

As one might expect, only test files that use Jest globals are affected. Running the tests and the app, however, works fine—only Storybook is failing.

**Expected behavior**
Storybook builds successfully.

**Versions:**
 - TypeScript `3.5.2`
 - React `16.8.0`
 - Storybook `5.1.8`
 - Jest `24.8.0`
 - @types/jest `24.0.15`

**Comment by namhong2001** [comment]
Same here. Did you find any workarounds?

**Comment by graup** [comment]
I found a workaround by pinning both `jest` and `@types/jest` to `24.0.0`. 

https://github.com/facebook/jest/issues/8285#issuecomment-500165012

**Comment by jackiehluo** [comment]
> I found a workaround by pinning both jest and @types/jest to 24.0.0.

This fix didn't work for me! That linked issue deals with the tests failing; our tests are working fine, though. Only Storybook is broken for us.

**Comment by reaktivo** [comment]
Hey @jackiehluo, just ran into the same issue as you did (Storybook breaking trying to load test.tsx files). It's a long shot, but did you find a solution?

**Comment by dspacejs** [comment]
Same problem, following. These globals don't throw errors normally because I've set `env.jest` to `true` in my ESLint config. But since Storybook doesn't use ESLint, it doesn't know how to find these globals.

I've also tried excluding test files from compilation with both the Webpack config and tsconfig.json, but this didn't work. Will report back here if I figure out a solution

**Comment by dspacejs** [comment]
The problem for me was the regex for stories in `.storybook/config.js` was incorrect. This meant Storybook was loading all TypeScript files (including tests).

By changing it to the following, Storybook now ignores test files so this isn't a problem anymore:

```js
configure(require.context('../src/components', true, /\.stories\.tsx$/), module);
```

**Comment by eranimo** [comment]
I am experiencing this in v6.5.9 (latest)

**Comment by eranimo** [comment]
@dspacejs I am confused that code does, can you explain?

**Comment by eranimo** [comment]
I am literally not even using glob patterns, but storybook is still including all ts files

**Comment by ndelangen** [comment]
IS this also an issue in the 7.0 beta @eranimo ?
