### ISSUE TITLE
@storybook/angular@5.1.8 peer dependency on autoprefixer@^8.1.0

### ISSUE THREAD

**Issue by T-Higgs** [storybookjs/storybook#7143]
**Describe the bug**
@storybook/angular@5.1.8 has peer dependency on autoprefixer@^8.1.0 which cannot be resolved with Angular 8 and @storybook/core@5.1.8. 

**To Reproduce**
1. create a new angular project `ng new storybook-test`
2. add story book `npx -p @storybook/cli sb init`
3. run `npm install`
4. You should have a warning reading: `npm WARN @storybook/angular@5.1.8 requires a peer of autoprefixer@^8.1.0 but none is installed. You must install peer dependencies yourself.`

**Expected behavior**
@storybook/angular shouldn't have a peer dependency on autoprefixer@^8.1.0

**System:**
 - Framework: Angular
 - Version: 5.1.8

**Comment by rubiesonthesky** [comment]
It was added on 5.1.0-alpha.6 (March 14, 2019) , PR here https://github.com/storybookjs/storybook/pull/5612
