### ISSUE TITLE
Add story funtion breaks HMR

### ISSUE THREAD

**Issue by Jony-Y** [storybookjs/storybook#7148]
Hi,
I'm trying to create my own wrapper to create stories, to save some redundant code.
every time I use my createStory, the story loads fine but the HMR breaks and I get this warning in the console

I tested everything, even dumbed down versions, still doesnt work

lets say I have a function:

`/** createStory*/
 export default (section) => storiesOf(section, module)
`

and I try to use it in my story file

`/** component.story.js */
createStory('my Story').add(...)
`

This will not get HMR, and I will get this error:

> story with id v2-components--avatar-structures already exists in the store!
> Perhaps you added the same story twice, or you have a name collision?
> Story ids need to be unique -- ensure you aren't using the same names modolo url-sanitization.

now if I do this:
`/** component.story.js */
storiesOf('My Story', module).add(...)
`

everything works fine.

can someone help?

using:
@storybook: 5.1.8
react: 16.8.6

**Comment by shilman** [comment]
AFAIK you need `module` to be different for each `storiesOf` call, so you should pass it individually each time.

**Comment by Jony-Y** [comment]
so if I pass the module? would that work?

**Comment by Jony-Y** [comment]
So, Adding module to the createStory function worked. Thanks!
