### ISSUE TITLE
Cannot find module node_modules/babel-preset-react-app/node_modules/@babel/runtime/helpers/interopRequireDefault

### ISSUE THREAD

**Issue by Yankovsky** [storybookjs/storybook#7152]
**Describe the bug**
Running `npm run test` command results in error:
Cannot find module '/Users/yankovskyandrey/Code/cra-sb-storyshots-bug/node_modules/babel-preset-react-app/node_modules/@babel/runtime/helpers/interopRequireDefault' from 'Storyshots.test.js'

**To Reproduce**
1. Use npm to install all dependencies
2. Setup CRA + storybook using this instruction https://www.learnstorybook.com/react/en/get-started/
3. Add addon-storyshots and addon-storyshots-puppeteer by following their instructions

or just clone my repo https://github.com/Yankovsky/cra-sb-storyshots-bug and follow instructions inside

**Expected behavior**
Everything works, tests run.

**Screenshots**
![http://s.csssr.ru/U02D248T6/2019-06-19-23-09-11-xjj9e_.jpg](http://s.csssr.ru/U02D248T6/2019-06-19-23-09-11-xjj9e_.jpg)

**Code snippets**
I pushed repo with that bug, just follow readme inside https://github.com/Yankovsky/cra-sb-storyshots-bug

**System:**
 - OS: MacOS
 - Device: Macbook Pro 2015
 - Framework: react
 - Addons: addon-actions, addon-links, addon-storyshots, addon-storyshots-puppeteer
 - Version: 5.1.8

**Additional context**
This problem relates somehow to module resolution. npm installs @babel/runtime as a topmost dependency but as you can see on screenshot test command looks for @babel/runtime here `node_modules/babel-preset-react-app/node_modules/@babel/runtime`. Manually installing @babel/runtime as project dependency fixes the problem for some reason. Yarn installs @babel/runtime as babel-preset-react-app dependency so it works just fine.

**Comment by Yankovsky** [comment]
I saw issues like that without proper solution. People just blindly remove npm/yarn cache or delete package-lock/yarn.lock files and at one point they get lucky – different version of @babel/runtime become root dependency and version required by babel-preset-react-app stay inside its node_modules.
We can't rely on that.
Let's fix this problem once and for all.

**Comment by mrmckeb** [comment]
@Yankovsky, that `blind` solution is actually one that works most of the time... unfortunately there isn't a better solution yet. If you have one, please suggest it.

The appropriate place would be the Create React App project, as this is seen outside of Storybook installs. https://github.com/facebook/create-react-app/issues

We're yet to work out how to solve it, but it is a deduping issue I believe, and happens with NPM and Yarn.

**Comment by Yankovsky** [comment]
@mrmckeb I agree, it is definitely deduping issue, I've spent one whole day trying to debug that. I suspect that some module rely on having @babel/runtime inside its own dependencies and for some reason has relative path to it. Just to be clear are you sure that it is not storybook's problem, but CRA's?

**Comment by MichaelBitard** [comment]
Not sure if that's about CRA, I'm having the same issue using vuejs, so I guess it's related to jest and require-context

**Comment by pdemarino** [comment]
FWIW, what helped me was running `jest` with `--clearCache`. I suspect some outdated information was sitting there, that polluted all my tests.

[See here for specifics](https://jestjs.io/docs/en/cli#--clearcache)

**Comment by deviator206** [comment]
@pdemarino   thanks ...   this worked for me 

> jest --cleanCache.

But is there any other solution  ?

**Comment by natlang** [comment]
@pdemarino This worked for me too. Thanks.

**Comment by zokaman** [comment]
> FWIW, what helped me was running `jest` with `--clearCache`. I suspect some outdated information was sitting there, that polluted all my tests.
> 
> [See here for specifics](https://jestjs.io/docs/en/cli#--clearcache)

This solution is worked for me! Thx!

**Comment by mjbryan10** [comment]
> FWIW, what helped me was running `jest` with `--clearCache`. I suspect some outdated information was sitting there, that polluted all my tests.
> 
> [See here for specifics](https://jestjs.io/docs/en/cli#--clearcache)

This solution worked for me also, much appreciated!

**Comment by danpadua** [comment]
> FWIW, what helped me was running `jest` with `--clearCache`. I suspect some outdated information was sitting there, that polluted all my tests.

Worked for me, tks

**Comment by prkrekel** [comment]
Same, this worked. Thanks!

**Comment by aqueiros** [comment]
> FWIW, what helped me was running jest with --clearCache. I suspect some outdated information was sitting there, that polluted all my tests.

OMG I was going nuts with my tests failing just because some minor dependencies in yarn.lock file were updated. This totally solved it for me! 1000 thanks! 🙏

**Comment by goamn** [comment]
Thanks, works. Skypack issues after I upgraded tiptap react. I guess these three commands should clear node_modules plus clear the jest:
```
npm i --package-lock-only
npm ci
npm run jest --clearCache
```

**Comment by israelsaraiva** [comment]
In my case I was using craco, so I run
`craco test --clearCache`
and after added to my scripts 
`"test": "craco test --no-cache",`
