### ISSUE TITLE
Throw errors on storybook start if @babel/core or babel-loader are not installed as dependencies

### ISSUE THREAD

**Issue by Yankovsky** [storybookjs/storybook#7156]
**Is your feature request related to a problem? Please describe.**
@babel/core and babel-loader are peer dependencies for storybook. People can miss storybook installation instructions or later delete these dependencies because they are not used in project directly. There are many issues because of it, e.g. https://github.com/storybookjs/storybook/pull/6967 and https://github.com/storybookjs/storybook/issues/7058

**Describe the solution you'd like**
I suggest adding some friendly reminder if @babel/core and babel-loader are not installed as dependencies in project. Consider create-react-app notification on different version of required dependency
![http://s.csssr.ru/U02D248T6/2019-06-19-20-36-32-4babm_.jpg](http://s.csssr.ru/U02D248T6/2019-06-19-20-36-32-4babm_.jpg)
We can run something similar on storybook start.

**Describe alternatives you've considered**
I know that there are notifications about missing peer dependencies but they are easy to ignore. ![http://s.csssr.ru/U02D248T6/2019-06-19-21-03-02-rec2i_.jpg](http://s.csssr.ru/U02D248T6/2019-06-19-21-03-02-rec2i_.jpg)
If we could turn them into errors it would be much better but I don't know if there is such flag in package.json or in npm install command.

Another approach would be to turn peerDependencies into real dependencies. What are implications of this approach?

**Are you able to assist bring the feature to reality?**
Yes, I can.

**Comment by shilman** [comment]
Throwing errors up front is a good idea -- I imagine it can save people time. Can you create a PR for it? I don't think converting peerDependencies is a good idea but I can't recall the rationale for it. I'm sure @Hypnosphi remembers :)

**Comment by Yankovsky** [comment]
I can work on this issue but first I want to understand why these dependencies are peer dependencies and I'll try to find a way to turn peer dependencies warning for package into errors.

**Comment by Hypnosphi** [comment]
We need those as peer dependencies as long as we're going to support both babel 6 and babel 7 configs

**Comment by Yankovsky** [comment]
Ok ok bot, I'll try to do something with that issue.
