### ISSUE TITLE
trying to import withKnobs for Knobs on device add-on fails (regression bug ?)

### ISSUE THREAD

**Issue by z00m1n** [storybookjs/storybook#7163]
**Describe the bug**
Trying to import `withKnobs` for the [Knobs on device add-on](https://github.com/storybookjs/storybook/tree/master/addons/ondevice-knobs) fails; using code such as e.g.

```
import { withKnobs } from '@storybook/addon-ondevice-knobs';
import { storiesOf } from '@storybook/react-native';

storiesOf('MyView', module)
  .addDecorator(withKnobs)
  .add('default view', () => <MyView/> );
);
```

does not work due to `withKnobs` being undefined:

![20190621-090500 Screenshot iPhone Xs storybook github bug report import withKnobs fails](https://user-images.githubusercontent.com/662044/59904968-294a6700-9405-11e9-8c58-2741495d74b8.png)

It seems this issue has come up before: https://github.com/storybookjs/storybook/issues/4839. Importing `withKnobs` from `@storybook/addon-knobs` instead of `@storybook/addon-ondevice-knobs` **does work**, but it still takes a frustrating extra round to figure that out. The earlier issue seems to have been fixed at the time, but currently exists again - possibly some kind of regression bug, therefore posting a new issue.

**To Reproduce**
1. install packages (see below on versions): `npm install --save-dev @storybook/react-native @storybook/addon-knobs@5.1.0-rc.0 @storybook/addon-ondevice-knobs`
2. add `import '@storybook/addon-ondevice-knobs/register';` to `<project root>/storybook/rn-addons.js`
3. add the code shown above to `<project root>/storybook/stories/index.js`
4. try to run the app
5. see error

**NOTE:** when installing the currently latest version of `@storybook/addon-knobs` as per the [official documentation](https://github.com/storybookjs/storybook/tree/master/addons/ondevice-knobs) (and per convention), `@storybook/addon-ondevice-knobs@5.1.9` is missing a peer dependency:

```
npm ERR! peer dep missing: @storybook/addon-knobs@5.1.0-rc.0, required by @storybook/addon-ondevice-knobs@5.1.9
```

This can be resolved / worked around by installing `@storybook/addon-knobs@5.1.0-rc.0` instead.

**Expected behavior**
I expected this to work.

**System:**
 - OS: macOS 10.14.5 (18F132) (latest)
 - Device: Xcode Version 10.2.1 (10E1001) Simulator (latest)
 - Browser: Chrome 74.0.3729.169 (Official Build) (64-bit) (latest; AFAICT not involved though)
 - Framework: React Native
 - npm packages:

```
$ npm list --depth=0
<project name>@ <path to project root>
├── @storybook/addon-actions@5.1.9
├── @storybook/addon-knobs@5.1.0-rc.0
├── @storybook/addon-ondevice-actions@5.1.9
├── @storybook/addon-ondevice-knobs@5.1.9
├── @storybook/react-native@5.1.9
├── babel-preset-expo@5.0.0
├── expo@32.0.6
├── expo-postpublish-slack-notify@1.2.0
├── expokit@32.1.1
├── react@16.5.0
├── react-native@0.57.1
├── react-native-circular-progress@0.2.0
├── react-native-dotenv@0.2.0
├── react-native-elements@1.1.0
├── react-native-svg@9.4.0
├── react-navigation@3.9.1
├── react-redux@6.0.1
└── redux@4.0.1
```

**Comment by Gongreg** [comment]
Hey @z00m1n. I guess we could expose @storybook/addon-knobs api inside @storybook/addon-ondevice-knobs. That way user could import from both addon-knobs and addon-ondevice-knobs. What do you think? Could you help us with PR here? :)

**Comment by shilman** [comment]
Son of a gun!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-beta.30 containing PR #7555 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
