### ISSUE TITLE
Addon-docs: Naming consistency for Story blocks

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#7164]
As raised in @ndelangen 's review of #7119. We currently define stories in MDX as:

```jsx
<Story name="some name">...</Story>
```

However, in the module format we can override the story title as:

```jsx
export const story = () => ...
story.title = "some name"
```

Should we rename the `Story`'s `name` attribute to `title` for consistency? Or rename `title` to `name`?

**Comment by tmeasday** [comment]
Or the other way (use name for both)

**Comment by shilman** [comment]
We run into a problem when trying to do:

```
export const foo = () => <Foo />;
foo.name = 'foo bar'
```

=> `Cannot assign to read only property 'name' of function 'function(){return _ref2}'`

New proposal:

```js
export const foo = () => <Foo />;
foo.storyData = {
  name: 'foo bar',
  parameters: ...
  decorators: ...
};
```

This is pure JS, allows us to stuff anything we want into `storyData` without worrying about name collisions, and is just slightly more verbose.

**Comment by shilman** [comment]
Whoopee!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-alpha.31 containing PR #7202 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
