### ISSUE TITLE
Addon Centered causes component to disappear when zooming

### ISSUE THREAD

**Issue by CodeByAlex** [storybookjs/storybook#7167]
**Describe the bug**

**To Reproduce**
1. Open a component that uses addon centered
2. use the + or - magnifying glass in storybook
3. component will disappear 

**Expected behavior**
Component shouldnt disappear.

**Screenshots**
![centered-zoom-bug](https://user-images.githubusercontent.com/29763590/59945023-5104f380-9434-11e9-9c62-db14e620db31.gif)

**System:**
 - Browser: [chrome]
 - Framework: [react, angular, and more?] example above is from the official storybook
 - Version: [at least as of addon centered: 5.1.1 will have to check on 5.0 versions]

**Comment by ndom91** [comment]
Can confirm I have the same issue.

**Comment by CodeByAlex** [comment]
@ndom91 is this something that you would like to take a look into?

**Comment by ndom91** [comment]
@CodeByAlex yeah ill take a look at it this evening when I have some free time :)

**Comment by ndom91** [comment]
So unfortunately I dont have a solution yet, but I did find some things - maybe it will ring a bell for someone else.. 

The element disappears immediately once any css transform is applied, be it scale, transformX, translateY, translateZ, etc. 

In this case the zoom button adds a `translate: scale(1.25)`, for example. If you take this property off in the dev tools the element reappears. I did some googling and none of the common suggestions fixed the issue.

There is kind of a work-around which I discovered which we could implement, and that is using `zoom(1.25)` instead.

According to MDN zoom is a 'non-standard' property though, but has pretty good browser compatibility:

![image](https://user-images.githubusercontent.com/7415984/60368101-40ceb480-99f0-11e9-9b9e-2daa5da4a467.png)


https://developer.mozilla.org/en-US/docs/Web/CSS/zoom

**Comment by 8beeeaaat** [comment]
I found the solution.
The `body` element should styled
```
width: 100%;
height: 100%;
```

![Jul-12-2019 21-54-07](https://user-images.githubusercontent.com/4495546/61129636-c2920800-a4ef-11e9-9815-0701f766a633.gif)

**Comment by ndom91** [comment]
Should this be changed in storybook itself, or in the addon?

**Comment by ndom91** [comment]
Looks good on my end too! Have you made a pull request?

**Comment by 8beeeaaat** [comment]
@ndom91 
Sorry, I couldn't make PR...
I can't push commit with permission error.

**Comment by ndom91** [comment]
If you clone it first, make your change in your cloned version, and then you should be able to make a PR from there.

**Comment by 8beeeaaat** [comment]
Wow!! I'll try it!!

**Comment by ndom91** [comment]
Yes, this is the standard way to do it if you dont have the rights to the repo.

See, for example, this pull request: https://github.com/storybookjs/storybook/pull/7397

It is from @ctavan's clone, back into storybookjs:next branch

**Comment by 8beeeaaat** [comment]
@ndom91 
I'made PR #7400 ! 
Thank you very much for guiding me! !

**Comment by shilman** [comment]
Egads!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-beta.6 containing PR #7400 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

**Comment by 8beeeaaat** [comment]
@shilman
Thanks!!🙌

**Comment by shilman** [comment]
Son of a gun!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.1.10 containing PR #7400 that references this issue. Upgrade today to try it out!

**Comment by shilman** [comment]
Yay!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-beta.21 containing PR #7640 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

**Comment by shilman** [comment]
@CodeByAlex @ndom91 @8beeeaaat @quentind @Hypnosphi 

I'm reverting #7640 and #7400. We should not be modifying the preview styles since it can conflict with the user's style and break visual tests (among other things).

We'll have to come up with a different solution to this problem. @Hypnosphi suggested `body {transformOrigin: center center;}` as an option. Whatever we do it's important that it's only applied to centered stories.

**Comment by CodeByAlex** [comment]
@shilman thats a really good point and something that should have been considered. I will say that addon centered applies styles to the component to place it in the center to begin with as seen here: https://github.com/storybookjs/storybook/blob/next/addons/centered/src/styles.ts

If we want to make sure that styles aren’t interfering(which makes sense), we may want to consider how the addon works from the ground up.

**Comment by shilman** [comment]
Yay!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-beta.29 containing PR #7749 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Boo-yah!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-alpha.21 containing PR #8442 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.
