### ISSUE TITLE
Update src/index.html issue?

### ISSUE THREAD

**Issue by justindasilva** [storybookjs/storybook#7168]
I'm attaching a screenshot of what I see after running `npm run start`
Anyone know how to fix this?

<img width="987" alt="Screen Shot 2019-06-21 at 2 56 24 PM" src="https://user-images.githubusercontent.com/882534/59945245-03d55180-9435-11e9-9bf2-3fd73fb28c5b.png">

**Comment by shilman** [comment]
Need a lot more context. What does your setup look like? What version, addons, etc?

**Comment by justindasilva** [comment]
Using latest StencilJS (1.0.7)
Using latest `stencil-storybook-wrapper` (1.3.1) (https://www.npmjs.com/package/stencil-storybook-wrapper)

No addons or anything.

**Comment by justindasilva** [comment]
@shilman Has this issue that I brought up not been reported by anyone else? I basically started a new project from scratch and got the result that I posted.

Could it be something with my environment?

**Comment by shilman** [comment]
@justindasilva I think this is an issue with stencil-storybook-wrapper. You should try to get help there.
