### ISSUE TITLE
Renaming stories in MDX fails to remove old story

### ISSUE THREAD

**Issue by kylesuss** [storybookjs/storybook#7169]
**Describe the bug**

When using `.mdx` to compose stories on the latest alpha release (`5.2.0-alpha.29`), renaming a story has the effect of creating a newly named story in the currently running storybook, but the old story and name still exists in the UI.

**To Reproduce**
1. Using `5.2.0-alpha.29`, add a story as simple as the following:

```javascript
import { Story, Meta } from '@storybook/addon-docs/blocks';

<Meta title="Test" />

<Story name="testing">
  <div>Test</div>
</Story>
```

2. Fire up storybook
3. Change the name of the story to anything other than the current name
4. Verify in the UI that the story for `testing` still exists

**Expected behavior**
When renaming a story using JS, storybook refreshes the list of available stories and maintains an up to date catalog of the stories that are available. I would expect the behavior to be consistent between the two approaches.

**Screenshots**
![docs-mdx-name](https://user-images.githubusercontent.com/3035355/59946548-0da48800-9428-11e9-9bd7-cd760e609792.gif)

**Code snippets**
If applicable, add code samples to help explain your problem.

**System:**
 - OS: MacOS
 - Device: Macbook Pro 2019
 - Browser: Chrome
 - Framework: react
 - Version: `5.2.0-alpha.29`

**Comment by shilman** [comment]
Egads!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-alpha.37 containing PR #7319 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

**Comment by shilman** [comment]
Yowza!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.1.10 containing PR #7319 that references this issue. Upgrade today to try it out!
