### ISSUE TITLE
CLI update message leads to wrong changelog

### ISSUE THREAD

**Issue by webOS101** [storybookjs/storybook#7170]
**Describe the bug**
CLI update message links to wrong CHANGELOG

**To Reproduce**
1. Install storybook `5.1.8`
2. Start storybook

**Expected behavior**
Link to change log will show `5.1.9` (or newer) changes (/blob/master)

**Screenshots**
A new version (5.1.9) is available!
Read full changelog here: https://git.io/fhFYe   

Link above leads to `/blob/next`

**Code snippets**
n/a

**System:**
 - OS: MacOS
 - Device: MacBook Pro
 - Browser: n/a
 - Framework: React
 - Addons: n/a
 - Version: [e.g. 4.0.0]  5.1.8

**Additional context**
n/a

**Comment by mjaltamirano** [comment]
I tried to take a crack at this: https://github.com/storybookjs/storybook/pull/7166

**Comment by shilman** [comment]
Changelog has been updated!
