### ISSUE TITLE
Cannot import modules from modules CommonJS exports

### ISSUE THREAD

**Issue by mypum** [storybookjs/storybook#7176]
**Describe the bug**
I build a component in react using NextJS and use next-routes as the router. So I create routes.js inside project and export by CommonJS syntax for compatible with custom server.js to require modules.

The component in the project that runs by NextJS works well with import syntax. But the same component that runs in the storybook environment cannot find modules that export from CommonJS file (routes.js) 

**To Reproduce**
1. Import function that export from CommonJS file
2. Render component in the story file 

**Expected behavior**
I think this should work in the storybook environment same the NextJS environment

**Code snippets**

routes.js
```
const routes = require('next-routes')

module.exports = routes()
.add('about')
```

Hello.js
```
import { Link } from './routes'

export default function Home () {
   return (
     <div>
        <Link to="about">
           <a>About</a>
        </Link>
     </div>
  )
}
```
And show error like this in Storybook console
```
WARNING in ./components/Home.js "export 'Link' was not found in '../router'
```

**System:**
 - OS: MacOS
 - Device: Macbook Pro Late 2013
 - Browser: [Chrome
 - Framework: react
 - Version: 5.1.9

**Comment by adamchenwei** [comment]
similar issue.
