### ISSUE TITLE
Missing ts-pnp dependency

### ISSUE THREAD

**Issue by ZebraFlesh** [storybookjs/storybook#7179]
Installing @storybook/react@5.1.9, I'm now presented with the following warning from npm:
```
npm WARN ts-pnp@1.1.2 requires a peer of typescript@* but none is installed. You must install peer dependencies yourself.
```

That leads me to:
```
> npm ls ts-pnp
project@4.8.2 C:\Users\nope\git\project
`-- @storybook/react@5.1.9
  `-- @storybook/core@5.1.9
    `-- pnp-webpack-plugin@1.4.3
      `-- ts-pnp@1.1.2
```

Which was introduced in commit https://github.com/storybookjs/storybook/commit/c28af59e7db496ed01cec55dab70c98916d5d858 by @crubier. Why am I being asked to install typescript things in my not-typescript repo?

**Comment by crubier** [comment]
Hmm this seems to be a limitation of `pnp-webpack-plugin`, which is kind of "hardcoded" to use typescript: https://github.com/arcanis/pnp-webpack-plugin#ts-loader-integration

I didn't see this problem as I tested it in a project that already uses typescript... 

To be fair I think that commit https://github.com/storybookjs/storybook/commit/c28af59e7db496ed01cec55dab70c98916d5d858 can be reverted as the solution we found afterwards was to use storybook presets.

**Comment by shilman** [comment]
@crubier any chance you can create a PR to fix it?

**Comment by ZebraFlesh** [comment]
Definitely still a problem that needs to be fixed

**Comment by ZebraFlesh** [comment]
Still a problem in non-pre-release versions

**Comment by shilman** [comment]
@ZebraFlesh Is it fixed in the prerelease version?
