### ISSUE TITLE
CRNA-kitchen-sink example doesn't work

### ISSUE THREAD

**Issue by lonyele** [storybookjs/storybook#7199]
**Describe the bug**
I can't run crna-kitchen-sink example on device.

**To Reproduce**
1. Download this repo
2. Setting up the project by `yarn install`, `yarn bootstrap`
3. Go to `/examples-native/crna-kitchen-sink` and `yarn start` (If it's not working `yarn install` here at this directory)
`... module schedule/tracking does not exist in the Haste module map ...`

**Expected behavior**
It should show the example on device(In my case, android simulator)

**System:**
 - OS: [Windows10]
 - Device: [Android Simulator]
 - Browser: []
 - Framework: [React-native]
 - Addons: [if relevant]
 - Version: [latest repo]

**Additional context**
I'm not sure if it is only not working for me. I want to know if anyone has met this situation that CRNA example is not working. Personally, setting up react-native gives me a headache and really tricky... wonder if it is happening only to me

**Comment by shilman** [comment]
@lonyele is this fixed?

**Comment by Gongreg** [comment]
@shilman, I've tried to run CRNA example in storybook yesterday without success.

**Comment by lonyele** [comment]
@shilman @Gongreg I think versioned up from #7200 should fix the problem though not yet merged(I'll resolve `yarn.lock` conflict and make it mergeable so that others can test again)

**Comment by shilman** [comment]
Yippee!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-beta.3 containing PR #7200 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
