### ISSUE TITLE
Source-loader: Post-merge fire fighting

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#7204]
I accidentally broke the build by merging #7117, which replaced `@storybook/addon-storysource/loader` with `@storybook/source-loader` in all of the examples.

There are two problems, both of which can be reproduced locally.

- [ ] a broken unit test
```
yarn jest --testPathPattern inject-decorator.test.js
```

- [ ] source-loader somehow causes `build-storybook` to run out of memory in most of the example directories
```
cd examples/angular-cli
yarn build-storybook
```

I've temporarily reverted the change to unblock the build in #7203, but these problems should be properly fixed to get `source-loader` ready for production.

**Comment by libetl** [comment]
Oh ok i told you those were missing and I will try to catch up asap sorry for the inconvenience

**Comment by shilman** [comment]
Ermahgerd!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-alpha.31 containing PR #7203 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Yo-ho-ho!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-alpha.32 containing PR #7214 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
