### ISSUE TITLE
Give preset the ability to inject content in preview/manager head

### ISSUE THREAD

**Issue by freeman** [storybookjs/storybook#7209]
**Is your feature request related to a problem? Please describe.**
To use storybook in multiple projects for my environment, I need to inject custom tags in head (mostly scripts tags with company wide shared libraries).

**Describe the solution you'd like**
To make it easy for everyone to use it I thought about creating a preset for that (and other needed customization).

**Describe alternatives you've considered**
I though about creating a new storybook "platform" (like `@storybook/html`, `@storybook/react`) but this seems very involved and my understanding is that presets are more likely to be the future.

The other alternative would be to ask everyone to configure a `.storybook/preview-head.html` in their respective projects 😢 

**Are you able to assist bring the feature to reality?**
yes, I can...

**Additional context**

**Comment by AdamVig** [comment]
@shilman I have a use case for this feature as well. I have a repository with many separate Storybook instances, but want all of them to use the same `preview-head.html`.

Currently, I have to copy and paste that file to each individual `.storybook` directory. Instead, I would like to be able to add `preview-head.html` to my internal preset and only have a single copy of it in the repository.

Would a pull request that adds this feature be welcome?

**Comment by shilman** [comment]
@AdamVig We'd might accept a PR for this. But before you go there, you might try the following workaround. If you have a `managerEntries` export in your preset, it can include files that get evaluated in Storybook's UI, aka the manager. Any code there should be able to programmatically modify the page `head`.

Example of auto-registering an addon in a preset: https://github.com/storybookjs/storybook/blob/next/addons/a11y/src/preset/index.ts#L6

**Comment by AdamVig** [comment]
@shilman I tried the suggested approach and got it working, but found that it's not actually what I need: I am trying to modify the _preview_ `<head>`, not the _manager_ `<head>`. I don't see a corresponding `previewEntries` preset property, so I am stuck. Do you have another workaround that I could try?

For what it's worth, here is the code I used to programmatically modify the manager `<head>`:

```JavaScript
// preset.js
module.exports = {
	managerEntries: entry => {
		return [...entry, require.resolve('./head')];
	},
};

// head.js
const fontLink = document.createElement('link');
fontLink.setAttribute('rel', 'stylesheet');
fontLink.setAttribute('href', 'https://fonts.googleapis.com/css?family=Noto+Sans:400,700');

const css = `
* {
	box-sizing: border-box;
}
`;
const styleElement = document.createElement('style');
styleElement.appendChild(document.createTextNode(css));

window.document.head.append(fontLink, styleElement);
```

**Comment by shilman** [comment]
There’s an “entries” export that does the same thing for the preview

**Comment by AdamVig** [comment]
@shilman I got it working. Thank you for your quick responses and thoughtful workarounds!
