### ISSUE TITLE
How do we get dark theme in storysource?

### ISSUE THREAD

**Issue by haldunanil** [storybookjs/storybook#7213]
I'm trying to use the dark theme shown here only in the storysource code section but can't find the docs to do it: 

![image](https://user-images.githubusercontent.com/9256828/60216596-5345c400-981f-11e9-8cb3-6ae4e8d2d218.png)

How can I achieve this in Storybook v5.0?

**Comment by shilman** [comment]
I believe it's currently tied to the overall storybook theme. So if you do the following in config.js:

```
addParameters({options: {theme: themes.dark}})
```

It should set your overall theme to dark as well as the storysource. I don't think there's a way to use the dark theme in storysource and the light theme overall .. yet.

**Comment by krutoo** [comment]
@shilman At the moment, is it still not possible to use the dark theme only for storysource?
