### ISSUE TITLE
CSSTransition of Reactjs in Storybook show error

### ISSUE THREAD

**Issue by ArmandoAA** [storybookjs/storybook#7226]
**Describe the bug**
I'm develop a modal that uses CSSTransition to animate itself but when I make this storybook show me a error.

> Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

**To Reproduce**
1. Install react-transition-group in your project
2. Create a component inside a CSSTransition
3. Create a stories for this component

**Expected behavior**
When I remove CSSTransition the component show in the storybook, thas is what I expected.

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System:**
 - OS: Windows10
 - Device: [e.g. iPhoneX, Macbook Pro 2018]
 - Browser: chrome
 - Framework: react
 - Version:5.1.9

**Comment by rembrandtreyes** [comment]
@ArmandoAA Could you share the files that you used to create the story and the components. That error seems to be more on the side of exporting/importing the files rather than storybook itself.

**Comment by ArmandoAA** [comment]
@rembrandtreyes 

Sorry for the delay to reply.
I'm posting the url to code.

https://github.com/ArmandoAA/csstransition-storybook
