### ISSUE TITLE
Component shows up in center of docs when using addon-centered

### ISSUE THREAD

**Issue by CodeByAlex** [storybookjs/storybook#7227]
**Describe the bug**
Addon centered causes component  to show up in the center of the docs view which is not the expected result.

**To Reproduce**
1. Apply addon centered
2. Click on the docs tab
3. See that the component is in the middle of the screen rather than in the markdown

**Expected behavior**
 Component should show up inline with the markdown

**Screenshots**
Coming soon

**Env**
 - Framework: [angular and maybe more]
 - Addons: [centered and docs]
 - Version: [5.2.0-alpha.31]

**Comment by shilman** [comment]
Starting in storybook 6.0 we're deprecating addon centered and we have a built-in `layout` parameter that controls the layout:

https://github.com/storybookjs/storybook/blob/next/examples/official-storybook/stories/core/layout.stories.js

Give that a try?

**Comment by shilman** [comment]
General issue #6700

**Comment by danielo515** [comment]
I'm on storybook 5 and addon-centered makes the component to not show at all. What is the workaround there?

**Comment by shilman** [comment]
@danielo515 not using addon-centered

**Comment by danielo515** [comment]
> @danielo515 not using addon-centered

Thans, and what is the alternative? I was previously using a custom decorator. Is that the only way?

**Comment by shilman** [comment]
in SB5 yes, in SB6, we `layout` parameter is the recommended way

**Comment by donaldpipowitch** [comment]
> in SB5 yes, in SB6, we `layout` parameter is the recommended way

I use `export const parameters = { layout: 'centered', }` and this looks awesome in the canvas view. But now the docs will be actually _centered_ but the stories inside aren't:

**Canvas (`layout: 'centered'`)**

![image](https://user-images.githubusercontent.com/1152805/88714669-6a8b6b00-d11d-11ea-9be3-341991b16352.png)

**Docs (`layout: 'centered'`)**

![image](https://user-images.githubusercontent.com/1152805/88714724-7d05a480-d11d-11ea-904b-9c4eae2811aa.png)

**Docs (default layout)**

![image](https://user-images.githubusercontent.com/1152805/88714780-8f7fde00-d11d-11ea-8a22-b9673ea010cc.png)

---

I'd be nice if the docs would have the  default width and that the components inside the story view would be centered.

**Comment by hzhu** [comment]
The `layout` parameter centers the "story" preview, but doesn't seem center the "docs" preview. Is there a recommended way to center "docs" previews?

**Comment by shilman** [comment]
@hzhu please upvote #12135

**Comment by ndelangen** [comment]
This is fixed in storybook 7.0:
https://github.com/storybookjs/storybook/pull/20723
