### ISSUE TITLE
Storyshots require-context.macro causes start-storybook build to fail

### ISSUE THREAD

**Issue by mateja176** [storybookjs/storybook#7232]
**Describe the bug**
Storyshots require-context.macro causes start-storybook build to fail

**To Reproduce**
1. git clone https://github.com/mateja176/react-hot-starter
2. cd react-hot-starter
3. git checkout storyshots-macro
4. npm run storybook

*NOTE* react-hot-starter is based on create-react-app@2

**Expected behavior**
Storybook builds and opens localhost:6006

**Screenshots**

![Screenshot from 2019-06-30 16-22-08](https://user-images.githubusercontent.com/33357948/60397975-6b854e00-9b53-11e9-9a3a-522916be4f78.png)

![Screenshot from 2019-06-30 16-22-29](https://user-images.githubusercontent.com/33357948/60397977-6fb16b80-9b53-11e9-93a8-e0721c2511d8.png)

**Code snippets**
N / A

**System:**
 - OS: Linux Ubuntu 19.04 
 - Device: Acer Aspire Laptop
 - Browser: N / A
 - Framework: Reac
 - Addons: N / A
 - Version: "@storybook/react": "^5.1.9"

**Additional context**
The tests work great, however start-storybook fails.

**Comment by mateja176** [comment]
Related #7231

**Comment by dennybiasiolli** [comment]
@mateja176 there is a temporary workaround here: https://github.com/storybookjs/storybook/issues/7231#issuecomment-508254388
