### ISSUE TITLE
In the "addon-info"  in the "Story Sourse" section, add the ability to display functions in detail as component properties.

### ISSUE THREAD

**Issue by antonyjaved** [storybookjs/storybook#7236]
**Is your feature request related to a problem? Please describe.**
In the "addon-info" in the "Story Sourse" section, a component property that is a function displayed as function noRefCheck () {}. It is necessary to give the opportunity to display the function in detail.

**Describe the solution you'd like**
In the addon, the "react-element-to-jsx-string" package is used to display the jsx component, which takes the showFunctions property as options. It is necessary when using the addon to give the opportunity to also specify this property for the detailed display of the function.

**Are you able to assist bring the feature to reality?**
 yes

**Additional context**
![image](https://user-images.githubusercontent.com/22159876/60420890-670f7280-9bf1-11e9-8acd-fc43c6bf741e.png)
![image](https://user-images.githubusercontent.com/22159876/60420981-8f976c80-9bf1-11e9-91e1-b9f90d086e6e.png)

**Comment by shilman** [comment]
`Addon-info` is being replaced by `addon-docs`, which is available today and is actively maintained. Check out the announcement here: https://medium.com/storybookjs/storybook-docspage-e185bc3622bf
