### ISSUE TITLE
dist version addon-info should not require user's webpack css loader

### ISSUE THREAD

**Issue by brennancheung** [storybookjs/storybook#7246]
**Describe the bug**
When upgrading to `@storybook/addon-info` `5.1.9` I receive the following error:

```
ERROR in ./node_modules/@storybook/addon-info/dist/components/PropTable/style.css 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> .info-table {
|   width: 100%;
| }
 @ ./node_modules/@storybook/addon-info/dist/components/PropTable/components/Table.js 14:0-23
```

**To Reproduce**
This is most likely caused because I have the following rule defined in my `webpack.config.js`:

```
      {
        test: /\.css$/,
        exclude: /node_modules/,
        use: ['style-loader', 'css-loader'],
      },
```
Note that `node_modules` is excluded.  This is a very common config but unfortunately it means webpack won't be processing anything inside of shipped `npm` modules.

**Expected behavior**
There is an expectation that anything shipped as `dist` within an `npm` module should already be compiled and not rely on the user's version of `webpack` in order to run.  There are serious performance and bundle size issues that require `node_modules` to be `excluded`.  This is the expected contract that all npm modules normally follow.

**Comment by brennancheung** [comment]
I worked around the issue by excluding just `@storybook/addon-info` from the `exclude`.

```
      {
        test: /\.css$/,
        exclude: /node_modules(?!\/@storybook\/addon-info)/,
        use: ['style-loader', 'css-loader'],
      }
```

**Comment by seraj** [comment]
is there any update here? i have same problem

**Comment by joyfulelement** [comment]
> I worked around the issue by excluding just `@storybook/addon-info` from the `exclude`.
> 
> ```
>       {
>         test: /\.css$/,
>         exclude: /node_modules(?!\/@storybook\/addon-info)/,
>         use: ['style-loader', 'css-loader'],
>       }
> ```

@brennancheung thanks for the workaround, but I still run into the same issue even _without_ the `exclude` option for css rules as follow, did you had to change anything else?

```
{
        test: /\.css$/,
        use: [
          {
            loader: 'style-loader',
          },
          {
            loader: 'css-loader',
            options: {
              modules: {
                localIdentName: '[name]__[local]--[hash:base64:5]',
              },
              sourceMap: true,
              importLoaders: 1,
            },
          },
          {
            loader: 'postcss-loader',
            options: {
              sourceMap: 'inline',
            },
          },
        ],
        include: path.resolve(__dirname, '../src/')
      },
```

**Comment by joyfulelement** [comment]
I tried with a different line up of dependencies and confirms that this issue exist since version `5.1.8` for `@storybook/addon-info`, and the **workaround mentioned above with the `exclude` option also does not work.** 

```
    "@dump247/storybook-state": "1.6.1",
    "@storybook/addon-actions": "5.1.8",
    "@storybook/addon-info": "5.1.8",
    "@storybook/addon-knobs": "5.1.8",
    "@storybook/addon-options": "5.1.8",
    "@storybook/react": "5.1.8",
```

**Comment by joyfulelement** [comment]
Hi @shilman could you help remove the `has workaround` label? Since the issue still exist with or without the suggested workaround, thanks.

**Comment by ellisio** [comment]
I am experiencing this issue with `5.1.10` using the following `webpack.config.js`. We are using PostCSS and TailwindCSS.

```
const path = require('path');

module.exports = async ({ config }) => {
  config.module.rules = config.module.rules.filter(f => f.test.toString() !== '/\\.css$/');

  config.module.rules.push({
    test: /\.css$/,
    exclude: /node_modules/,
    loaders: ['style-loader', 'css-loader', 'postcss-loader'],
    include: path.resolve(__dirname, '../src'),
  });

  return config;
};
```

The above was proposed on this thread: https://github.com/storybookjs/storybook/issues/6319#issuecomment-477852640

**Comment by ellisio** [comment]
I was able to resolve this by modifying our `webpack.config.js` to be the following:

```
const path = require('path');
const autoprefixer = require('autoprefixer');

module.exports = async ({ config }) => {
  config.resolve.alias = {
    '@arcadia/ui': path.resolve(__dirname, '../src'),
  };

  config.module.rules = config.module.rules.map(f => {
    // Needed to add this to ignore our ../src/ for the default rule, instead of purging it.
    if (f.test.toString() === '/\\.css$/') {
      f.exclude = path.resolve(__dirname, '../src/');
    }

    return f;
  });

  config.module.rules.push({
    test: /\.css$/,
    include: path.resolve(__dirname, '../src/'), // Needed to be changed from ../
    loaders: ['style-loader', 'css-loader', 'postcss-loader'],
  });

  return config;
};
```

**Comment by shilman** [comment]
FYI `addon-info` is being superceded by `addon-docs`, which fixes a bunch of bugs and is easier to maintain. It’s reached release candidate (RC) status and will be properly released soon. Please give it a try! https://medium.com/storybookjs/storybook-docspage-e185bc3622bf

@brennancheung @joyfulelement @Zodiase @edwardsCam @pbaio-veritext @github-actions @seraj @stale @ellisio

**Comment by jerriclynsjohn** [comment]
@ellisio I'm really stuck in bringing in TailwindCSS for Svelte into Storybook, can you let me know what you did besides the above mentioned `webpack.config.js`. Is there any way that you could share a Svelte  + Tailwind + Storybook implementation.

**Comment by jerriclynsjohn** [comment]
Figured out how to do it and have made a dedicated repo, if anyone needs help in this integration. https://github.com/jerriclynsjohn/svelte-storybook-tailwind

**Comment by shilman** [comment]
@jerriclynsjohn If you tweet about it and mention `@storybookjs` and I'd be happy to retweet!

**Comment by jerriclynsjohn** [comment]
@shilman I've tweeted about it, do let me know if there needs to be any changes in the repo specific to Storybook

**Comment by mledu** [comment]
@jerriclynsjohn does it process @apply in Style blocks in a Svelte component?

**Comment by jerriclynsjohn** [comment]
@mledu Yes it does, I've made changes to the code [here](https://github.com/jerriclynsjohn/svelte-storybook-tailwind/blob/master/storybook/components/buttons/buttons-outline.svelte). Do take a look at it. :+1:

**Comment by lucasjs** [comment]
This section helped me a lot:
https://storybook.js.org/docs/configurations/custom-webpack-config/#using-your-existing-config

**Comment by j18s** [comment]
Hi all, I solved this by reading suggestion from @jerriclynsjohn. thanks @jerriclynsjohn  
```
rules: [
      {
        test: /\.css$/,
        use: ['style-loader', 'css-loader'],
        include: path.resolve(__dirname, '../'),
      },
```
