### ISSUE TITLE
addon-info propTables

### ISSUE THREAD

**Issue by MrDestroii** [storybookjs/storybook#7254]
**Describe the bug**
via addParameters I specify for info, propTables, I want props to be displayed only for those components that are specified in propTables

**Expected behavior**
In the Prop Types block, props should only be displayed for Form

**Code snippets**
`import Form from 'Form'`
`import Input from 'Input'`
`import Button from 'Button'`
`storiesOf('Form', module)`
`  .addParameters({ info: { propTables: [Form] } })`
`  .add('witch children', () => (`
`    <div className="col-md-12" style={{ height: '100vh' }}>`
`      <Form>`
`        <Input placeholder="Search">`
`        <Button />`
`     </Form>`
`    </div>`
`  ))`

**System:**
 - OS: [Ubuntu 18.04]
 - Browser: [chrome]
 - Framework: [react]
 - Addons: [addon-info]
 - Version: ["@storybook/addon-info": "^5.1.9", "@storybook/addons": "^5.1.9", "@storybook/react": "^5.1.9", "@types/storybook__react": "^4.0.2"]

**Comment by smasontst** [comment]
@MrDestroii I have a fix for this, I'll PR once I get a test written

**Comment by shilman** [comment]
Released #7477. closing.
