### ISSUE TITLE
Composable storybooks (storybooks within storybooks)

### ISSUE THREAD

**Issue by OwenPattison** [storybookjs/storybook#7255]
**Is your feature request related to a problem? Please describe.**
I'm trying to implement several Storybooks in a monorepo.
What I'd like to be able to do is then create a Storybook that I can compose from the several Storybooks I've created for each part of the monorepo.
This would allow me have an isolated development environment for each part of the monorepo whilst being able to publish a publicly accessible Storybook that would have all the components within the monorepo.

**Describe the solution you'd like**
The solution I'd like would be the ability to create a Storybook that is able to inherit other Storybooks to compose a single Storybook.

**Describe alternatives you've considered**
Currently the only alternative I can think of would be to still use the architecture outlined below, then I'd have to duplicate all of the stories from within packages in the root Storybook to achieve the same thing.

**Are you able to assist bring the feature to reality?**
I could potentially take some work to help achieve this goal, though im yet to have contributed to the repository.

**Additional context**
Given this hierarchy I'd like the root Storybook to be composed by the Storybooks within each package.

![image](https://user-images.githubusercontent.com/5864244/60522422-d7e18800-9ce0-11e9-9a74-3a6ffed4fb31.png)

**Comment by shilman** [comment]
You can achieve something like this today by simply loading all the `*.stories.js` files from each of those directories into the root storybook.

```js
  let req = require.context('packages/detail/stories', true, /\.stories\.js$/);
  req.keys().forEach(filename => req(filename));

  req = require.context('packages/forms/stories', true, /\.stories\.js$/);
  req.keys().forEach(filename => req(filename));

  ...
```

If each of the stories were appropriately "rooted", this would probably do something like what you'd want:

```js
storiesOf("Detail|path/to/component", module).add(...)
storiesOf("Detail|path/to/another", module).add(...)

storiesOf("Forms|path/to/component", module).add(...)
...
```

Storybook can def be smarter about how it loads these in, but I think this would be a workaround that you could use today. What do you think?

**Comment by OwenPattison** [comment]
@shilman thanks for the response, this seems like a functional workaround to use today definitely. I'll give this a try 👍

**Comment by shilman** [comment]
@OwenPattison Please do and post back here if it's working. Also, we're definitely interested in giving first-class support for this use case so if you're interested in figuring out a better way together that would be fantastic.

**Comment by OwenPattison** [comment]
@shilman I've tried to get the suggestion working without much success.
When i require the stories from the root storybook i'm seeing alot of errors, here's how I've setup my config.ts: https://i.imgur.com/F377kj9.png 
and these are the errors i'm seeing: https://i.imgur.com/pWq6JxB.png

If i import stories from a subfolder of root it compiles and runs fine.

**Comment by shilman** [comment]
@OwenPattison i think this is related to `core-js` version, not really related to composition. @ndelangen can you give a hand?
