### ISSUE TITLE
emotion-theming@10.0.14" has unmet peer dependency "@emotion/core@^10.0.14"

### ISSUE THREAD

**Issue by kaiyoma** [storybookjs/storybook#7260]
**Describe the bug**
After upgrading from Storybook 5.1.3 to 5.1.9, we see this warning during `yarn install`:

```
warning "@storybook/core > @storybook/ui > emotion-theming@10.0.14" has unmet peer dependency "@emotion/core@^10.0.14".
```

**System:**
 - OS: Windows 10, Linux
 - Framework: React
 - Version: 5.1.9

**Comment by anfriis** [comment]
Possible Duplicate of #6882

**Comment by kaiyoma** [comment]
Still an issue.
