### ISSUE TITLE
Addon-docs: No global Style anymore

### ISSUE THREAD

**Issue by rwieruch** [storybookjs/storybook#7264]
Tried Addon-docs with Alpha version 35 today. Everything worked fine, except for my global style which isn't applied in the new **Docs** panel, but still working in the old **Canvas** panel.

This is how my *.storybook/config.js* looks like:

```
import React, { Fragment } from 'react';
import { load, addParameters, addDecorator } from '@storybook/react';
import { DocsPage } from '@storybook/addon-docs/blocks';

import { Style } from '../src';

// Global Style

addParameters({
  docs: DocsPage,
  options: {
    storySort: (a, b) => a[1].id.localeCompare(b[1].id),
  },
});

addDecorator(storyFn => (
  <Fragment>
    <Style />
    {storyFn()}
  </Fragment>
));

load(require.context('../src', true, /stories\.js$/), module);
load(require.context('../src', true, /stories\.js$/), module);
```

Whereas *Style* comes from styled-components:

```
import { createGlobalStyle } from 'styled-components';

import 'opensans-npm-webfont/style.css';

export default createGlobalStyle`
  h1 {
    font-size: 12px;
  }
`;
```

**Comment by shilman** [comment]
This is closely related to #6803

**Comment by leerob** [comment]
I also noticed this one!

**Comment by shilman** [comment]
Hurrah!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-beta.31 containing PR #7771 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
