### ISSUE TITLE
Addon-docs: Oh no! The source is not available.

### ISSUE THREAD

**Issue by rwieruch** [storybookjs/storybook#7267]
I tried the new Storybook addon-docs in Alpha version 35. Everything works as expected! However, I don't see the source code of  the Story. I guess it isn't implemented yet, is it? If it is implemented, do I need to add something to my story?

![Screenshot 2019-07-03 at 14 03 35](https://user-images.githubusercontent.com/2479967/60590231-c9a47200-9d9b-11e9-92b8-812251712c22.png)

```
storiesOf('1. Atoms|01. Buttons/1. ContentButton', module)
  .addParameters({ component: ContentButton })
  .add('01. default', () => {
    const props = {
      label: text('label', 'Button'),
      onClick: () => {},
      selected: boolean('selected', false),
      disabled: boolean('disabled', false),
    };

    return <ContentButton {...props} />;
  });
```

**Comment by shilman** [comment]
@rwieruch What does your `webpack.config.js` look like? You need to add `source-loader` like this: https://github.com/storybookjs/storybook/blob/next/examples/official-storybook/webpack.config.js#L42

**Comment by rwieruch** [comment]
That's my .storybook/webpack.config.js:

```
module.exports = ({ config }) => {
  config.module.rules.push(
    {
      test: /\.(js|jsx)$/,
      exclude: /node_modules/,
      use: ['babel-loader'],
    },
    {
      test: /stories\.(js|jsx)?$/,
      loaders: [require.resolve('@storybook/addon-storysource/loader')],
      enforce: 'pre',
    },
    // No other file loaders needed, because they are mocked for Jest
  );

  // https://github.com/storybookjs/storybook/issues/7092
  config.devtool = 'eval';

  return config;
};
```

**Comment by shilman** [comment]
This line:
```
      loaders: [require.resolve('@storybook/addon-storysource/loader')],
```

Needs to be updated to:
```
      loaders: [require.resolve('@storybook/source-loader')],
```

Along with adding `@storybook/source-loader` as a dependency. We've refactored out that part into a separate package that will be shared by `addon-storysource` and `addon-docs`. However, we're still getting it all working. I'll update here when I think it's stabilized.

**Comment by libetl** [comment]
If you do that you lose the storysource.
I have a pending PR #7272 to make both work at once (storysource and docs sharing the same source-loader)

**Comment by JabbyPanda** [comment]
Probably storybook source addon does not work out of the box together with `storiesOf` API from storybook, at least that what I've experiences with Storybook source addon@4.0.13.

Can you try to write story for your component without relying on 'storiesOf` and get back here with results ?

**Comment by shilman** [comment]
@jabbypanda you should be using the same version of all `@storybook/*` packages if possible. PR #7272 brings the storysource and docs add-ons up to date and dependent on the same source-loader package. Will merge and update once it's stable.

**Comment by JabbyPanda** [comment]
>@JabbyPanda you should be using the same version of all @storybook/* packages if possible

Yes, we follow this rule of thumb across all of our projects. 
The project I referred to above is using Storybook 4 (was not yet migrated to Storybook 5)

**Comment by benjamingeorge** [comment]
I followed the google doc for getting addon-docs setup.  I'm using version 5.2.0-beta.7 for all required packages (this is a new project).  The story source doesn't seem to work with typescript.  

presets.js
```
module.exports = [
    '@storybook/preset-typescript',
    {
        name: '@storybook/addon-docs/react/preset',
        options: {
            configureJSX: true,
        },
    },
];
```

webpack.config.js
```
const path = require('path');

module.exports = async ({ config }) => {
    config.module.rules.push({
        test: /\.stories\.[tj]sx?$/,
        loader: require.resolve('@storybook/source-loader'),
        options: {
            injectParameters: true,
            inspectLocalDependencies: false,
            inspectDependencies: false,
        },
        include: [path.resolve(__dirname, '../src')],
        enforce: 'pre',
    });
    return config;
};
```

The props table is populated by the Typescript interfaces used for the props so that works correctly.  Just the source doesn't show up. 

![docs](https://user-images.githubusercontent.com/1595732/61746695-e6601400-ad61-11e9-8848-af7fefe6ea78.png)

**Comment by shilman** [comment]
@benjamingeorge that's strange! Got a repo I can look at? Or wanna hop onto our Discord and we can debug it together interactively?

**Comment by benjamingeorge** [comment]
Sure here is a pared down version https://github.com/benjamingeorge/ts-addon-docs

**Comment by shilman** [comment]
@benjamingeorge Your include path is wrong:

```
    include: [path.resolve(__dirname, "../src")],
```

For your project structure should be:

```
    include: [path.resolve(__dirname, "../stories")],
```

**Comment by benjamingeorge** [comment]
Wow.  Thats embarrassing. Thank you.

**Comment by polRk** [comment]
What about CRA preset ? How can i fix this problem ?
