### ISSUE TITLE
Upgrade Core-js

### ISSUE THREAD

**Issue by alistair-hmh** [storybookjs/storybook#7269]
**Describe the bug**

## ~~Issue 1~~

~~With some projects `@storybook/addon-actions` does not work. When launching storybook with the command `yarn storybook`, the following kinds of errors can be seen:~~

```
ERROR in node_modules/@storybook/channel-postmessage/dist/index.js
Module not found: Error: Cannot find module 'core-js/modules/web.dom.iterable'
```

## Issue 2

Additionally, when installing `@storybook/react` - there is a warning about Storybook using an old version of `core-js`. I think these may be related?

**To Reproduce**

1. `yarn add @storybook/react@5.1.9`
2.  Note the following message:

```
warning @storybook/react > @storybook/core > @storybook/ui > recompose > fbjs > core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
```

**Expected behavior**
There should be no core-js message when installing the latest @storybook/react.

**Screenshots**
<img width="890" alt="CleanShot 2019-07-03 at 12 36 33@2x" src="https://user-images.githubusercontent.com/38665769/60609260-4e3cc380-9d8f-11e9-95c4-21e126e8bec8.png">

## Note:

The same message is seen when installing `@storybook/addon-actions@5.2.0-alpha.35`

```shell
yarn add @storybook/addon-actions@5.2.0-alpha.35
```

<img width="842" alt="CleanShot 2019-07-03 at 12 48 26@2x" src="https://user-images.githubusercontent.com/38665769/60610033-f4d59400-9d90-11e9-8e54-1369307c0056.png">

~~This is stopping us from upgrading Storybooks above version 4.~~

**System:**
 - OS: [MacOS]
 - Device: [Macbook Pro 2015]
 - Browser: [e.g. chrome, safari]
 - Framework: [react]
 - Addons: [actions]
 - Version: [5.1.9]

**Comment by shilman** [comment]
@ndelangen Here we go again :)

**Comment by alistair-hmh** [comment]
After more digging, we found that we had a conflicting version of @storybook/react in one of our own sub-dependencies that was triggering `Issue 1`: `Cannot find module '...web.dom.iterable'`.

React 16.8.6 w/ Storybooks 5.1.9 seems to be working well for us now.

Perhaps you can ignore that part of the problem as that is likely just configuration on our side.

With respect to `Issue 2`, it does seem odd that `@storybook/addon-actions@5.2.0-alpha.35` would use an older `core-js` - as I think your release notes point to the older `core-js` being upgraded a few versions back. Here: https://github.com/storybookjs/storybook/releases/tag/v5.2.0-alpha.30

**Comment by stjepangolemac** [comment]
We are experiencing the "Issue 2" too. Any suggestions or timelines?

**Comment by shilman** [comment]
@alistair-hmh It sounds like you resolved your own issue? Closing, please feel free to shout if this was premature. :)
