### ISSUE TITLE
Placement of NotificationList on Docs-page 

### ISSUE THREAD

**Issue by lonyele** [storybookjs/storybook#7289]
**Describe the bug**
It seems like the placement of `Notifications` on `Docs` page is at the wrong place.

**To Reproduce**
1. Open official-storybook
2. Go to `Notifications` -> `Notifications` -> any of `single`, `all`, `placement` and goes to `Docs` insted of `Canvas`
3. It seems like `Notifications` are at wrong place

**Expected behavior**
At least, `single, all` should be inside of component wrapper

**Screenshots**
![Screenshot_2019-07-04 Storybook](https://user-images.githubusercontent.com/15892571/60640567-bad4c280-9e62-11e9-8071-679a18066f74.png)

**System:**
 - OS: [e.g. Windows 10 pro, Ubuntu 18.04]
 - Device: []
 - Browser: [chrome, firefox]
 - Framework: [react]
 - Addons: [docs]
 - Version: [v5.2.0-alpha.35]

**Additional context**

**Comment by shilman** [comment]
w00t!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-alpha.42 containing PR #7290 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
