### ISSUE TITLE
Google Analytics storyMissing undefined

### ISSUE THREAD

**Issue by claudio-moya** [storybookjs/storybook#7292]
**Describe the bug**
The plugin trigger an error exception when there are missed stories.

**To Reproduce**
1. Use default setup using type react.
2. Enable the addon in `addons.js` (`import '@storybook/addon-google-analytics/register';`)
3. Run the project using the root localhost path (ex.: http://localhost:8080)
4. After the router redirects you to any of the stories, the error is triggered.
4. Open the developers console and see the error:
`TypeError: Cannot read property 'id' of undefined`

**Expected behavior**
Run the project and don't show an error during the router changes from root path to stories path.

**Screenshots**
![storybook-addon-google-analytics](https://user-images.githubusercontent.com/10554673/60643725-fe352e00-9e6e-11e9-8621-a7a26cf9435f.gif)

**Code snippets**
The issue is located at `register.ts` due to the `id` variable is undefined.

```
api.on(STORY_MISSING, ({ id }: { id: string }) => { //<-- id is undefined here
    ReactGA.exception({
      description: `attempted to render ${id}, but it is missing`,
      fatal: false,
    });
  });
```

**System:**
 - OS: MacOS
 - Device: Macbook Pro Retina
 - Browser: Chrome, Safari, Firefox
 - Framework: react
 - Addons: addon-google-analytics
 - Version: v5.1.9

**Additional context**

**Comment by chris-dura** [comment]
I’m experiencing the same thing for `@storybook/html`

**Comment by shilman** [comment]
ZOMG!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-alpha.43 containing PR #7410 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

**Comment by shilman** [comment]
Great Caesar's ghost!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.1.10 containing PR #7410 that references this issue. Upgrade today to try it out!
