### ISSUE TITLE
Linting fails after upgrading to the latest commit

### ISSUE THREAD

**Issue by lonyele** [storybookjs/storybook#7313]
**Describe the bug**
`yarn lint` fails after #6923 is merged

**To Reproduce**
1. `git clone` or `git pull` to the latest `next` branch after #6923 is [merged](https://github.com/storybookjs/storybook/commit/b9d2ba26114b1007af6cdd7bd3c3adfeb1d11df4)
2. Setting up project and run `yarn lint`
3. See errors 
```
/tmp/storybook/addons/ondevice-backgrounds/src/BackgroundPanel.js
  66:42  error  Caution: `Constants` also has a named export `PARAM_KEY`. Check if you meant to write `import {PARAM_KEY} from './constants'` instead  import/no-named-as-default-member
```

**Expected behavior**
`yarn lint` result should be success

**Screenshots**
#7190 [CI fails](https://circleci.com/gh/storybookjs/storybook/138076?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link)

#7307 [CI fails](https://circleci.com/gh/storybookjs/storybook/138101?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link)

#7308 [CI fails](https://circleci.com/gh/storybookjs/storybook/138126?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link)

**Comment by shilman** [comment]
Ermahgerd!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-alpha.36 containing PR #7311 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.
