### ISSUE TITLE
Notes addon using markdown - code block with lang breaks

### ISSUE THREAD

**Issue by beltranrengifo** [storybookjs/storybook#7314]
**Describe the bug**
Using Storybook Vue and Notes addon, if any md has a code block with any lang specified, the app crashes. I'm using markdown-loader for webpack to handle this files.
**To Reproduce**
1. Create new Vue CLI3 project && Storybook
2. Install markdown-loader && html-loader && configure Webpack
3. Add Storybook Notes
4. Create a markdown with any code block with lang defined
5. Start Storybook server and it should crash

**Expected behavior**
Formatted code blocks

**Screenshots**
![image](https://user-images.githubusercontent.com/19485114/60681475-a1963b00-9e8f-11e9-8925-4ef986e281f6.png)
![image](https://user-images.githubusercontent.com/19485114/60681485-b1158400-9e8f-11e9-82b4-5bc27298513c.png)

**Code snippets**
Webpack conf
```
module.exports = async ({ config, mode }) => {
  config.module.rules.push(
    {
      test: /\.md$/,
      use: [
        { loader: 'html-loader' },
        {
          loader: 'markdown-loader'
        }
      ]
    },
    {
      test: /\.(html)$/,
      use: { loader: 'html-loader' }
    }
  )

  return config
}
```

**System:**
 - OS: MacOS
 - Device: Macbook Pro 2018
 - Browser: Any
 - Framework: Vue
 - Addons: Notes
 - Version: 5.1.9

**Comment by beltranrengifo** [comment]
Hi there!
Just want to know if this issue is on the roadmap for future releases.
Thanks!

**Comment by shilman** [comment]
Nobody's picked it up so far. We're in the process of releasing addon-docs, which does not have this problem and is a superset of notes, so a lot of attention is going there:

https://docs.google.com/document/d/1un6YX7xDKEKl5-MVb-egnOYN8dynb5Hf7mq0hipk8JE/edit

**Comment by beltranrengifo** [comment]
Cool!

Will this addon-docs be available for Vue.js in short or just for React?
Is there a way I can try to help to fix the actual notes addon in Vue.js?

Thanks!

**Comment by shilman** [comment]
@beltranrengifo It's available for all frameworks already. You can see the feature support matrix here: https://github.com/storybookjs/storybook/blob/next/addons/docs/README.md

As for debugging the notes addon, you can read all about that here: https://github.com/storybookjs/storybook/blob/next/CONTRIBUTING.md

And if you want help getting going jump on our Discord and you can get realtime help there https://discordapp.com/invite/UUt2PJb
