### ISSUE TITLE
[Help Needed] ZoneAwarePromise `(window|global).Promise` has been overwritten

### ISSUE THREAD

**Issue by ezpub** [storybookjs/storybook#7318]
Hi, I got Storybook successful setup with Angular 7 on a MacOS 10.14.5, but couldn't get Storyshots working.

Below is the error I got, as you can see, my other Jest tests were running fine without any problems, but Storyshots won't generate snapshots from the stories, looks like global["Promise"] was overwritten by `es.promise.js`. 

I tried fiddling around with the files in `node_modules/@storybook/addon-storyshots/dist/frameworks/angular/loader.js`, and make sure `zone.js` was imported after `es.promise.js`, but still no avail.

Any clues? Thanks!

```
...

  ● Storyshots › Another Button › button with link to another story

    Zone.js has detected that ZoneAwarePromise `(window|global).Promise` has been overwritten.
    Most likely cause is that a Promise polyfill has been loaded after Zone.js (Polyfilling Promise api is not necessary when zone.js is loaded. If you must load one, do so before loading zone.js.)

      at Function.Object.<anonymous>.Zone.assertZonePatched (node_modules/zone.js/dist/zone.js:58:23)
      at new NgZone (../packages/core/src/zone/ng_zone.ts:123:10)
      at TestBedViewEngine._initIfNeeded (../../packages/core/testing/src/test_bed.ts:408:20)
      at TestBedViewEngine.createComponent (../../packages/core/testing/src/test_bed.ts:594:10)
      at Function.TestBedViewEngine.createComponent (../../packages/core/testing/src/test_bed.ts:247:36)
      at _testing.TestBed.compileComponents.then (node_modules/@storybook/addon-storyshots/dist/frameworks/angular/renderTree.js:56:35)
      at node_modules/@storybook/addon-storyshots/node_modules/core-js/modules/es.promise.js:105:22
      at flush (node_modules/@storybook/addon-storyshots/node_modules/core-js/internals/microtask.js:26:9)

Test Suites: 1 failed, 18 passed, 19 total
Tests:       8 failed, 126 passed, 134 total
Snapshots:   0 total
Time:        28.119s, estimated 30s
Ran all test suites.
```

**Comment by iMarv** [comment]
Running into the same problem with Angular 8, Storyshots v5.1.9

**Comment by iMarv** [comment]
Just gonna bump it as this is a serious issue for us.

**Comment by shilman** [comment]
Have you tried the latest 5.2-beta? Worth a try if you haven't. There are some other angular-related fixes in there, tho I don't know the status of this one.

**Comment by aroget** [comment]
@shilman i'm getting the same error after running `npx -p @storybook/cli@next sb init --type angular` as suggested here https://github.com/storybookjs/storybook/issues/6804.

Our app is on Angular 8.0.1
Will debug this further tomorrow.

**Comment by aroget** [comment]
storybook v5.0.11 works fine on Angular 8.0.1

**Comment by ruudyroon** [comment]
Still stuck here :-( is there going to be an update on this?

**Comment by philippone** [comment]
Hello,

I try to write an addon but got the a similar error:

```
host-report-errors.js:6 Unhandled promise rejection Error: Zone.js has detected that ZoneAwarePromise `(window|global).Promise` has been overwritten.
Most likely cause is that a Promise polyfill has been loaded after Zone.js (Polyfilling Promise api is not necessary when zone.js is loaded. If you must load one, do so before loading zone.js.)
    at Function.push../node_modules/zone.js/dist/zone.js.Zone.assertZonePatched (zone.js:58)
    at new NgZone (core.js:26130)
    at getNgZone (core.js:26848)
    at PlatformRef.push../node_modules/@angular/core/fesm5/core.js.PlatformRef.bootstrapModuleFactory (core.js:26741)
    at core.js:26790
    at es.promise.js:107
```

My addon (does nothing at the moment) defined in an external package (throws error):
```
// angular.js

import {makeDecorator} from "@storybook/addons";

export const testAddonExternal = makeDecorator({
    name: "testAddon",
    parameterName: "testAddon",
    skipIfNoParametersOrOptions: false,
    allowDeprecatedUsage: false,
    wrapper: (getStory, context, settings) => {
        const story = getStory(context);
        console.log("Addon external", story);
        return story;
    }
});
```

```
// angular.d.ts (also external package)

import {testAddonExternal as test} from './angular';
export const testAddonExternal = test;
```


My Story (in Angular Project):

```
// button.stories.tsx

import {  testAddon } from "../../../../../../test/testaddon";
import { testAddonInLib } from "@storybook/addon-testaddon/angular";

const section = {
  component: ButtonComponent,
  title: "Button-CSF",
  moduleMetadata: {
    declarations: [ButtonComponent],
    imports: [CommonModule]
  },
  decorators: [
     // working
     testAddonInline,
	
    // working
    testAddon,
    
    // throws: Unhandled promise rejection Error 
    testAddonExternal
  ]
};
export default section;

const normalButton = {
  component: ButtonComponent,
  props: defaultProps
};
```

<details>
  <summary>testAddonInline: Addon defined inside of my Story File (working)</summary>

```
// button.stories.tsx

// same addon code but inline in the same file as the story (is working)
const testAddonInline = makeDecorator({
  name: "testAddon",
  parameterName: "testAddon",
  skipIfNoParametersOrOptions: false,
  allowDeprecatedUsage: false,
  wrapper: (getStory: StoryGetter, context: StoryContext, settings: WrapperSettings) => {
    const story = getStory(context);
    console.log("Addon inline", story);
    return story;
  }
});
```

</details>



<details>
  <summary>testAddon: I also tested to write my addon inside of my Angular Project and used it in the story (working)</summary>

```
// testaddon.ts

import { makeDecorator } from "@storybook/addons";

export const testAddon = makeDecorator({
  name: "testAddon",
  parameterName: "testAddon",
  skipIfNoParametersOrOptions: false,
  allowDeprecatedUsage: false,
  wrapper: (getStory, context, settings) => {
    const story = getStory(context);
    console.log("Addon in Angular Project", story);
    return story;
  }
});
```
</details>

My addons defined inside of the angular project are working. The external loded addon produces also the console output but then throws the error:

![Screenshot 2019-10-20 at 15 12 18](https://user-images.githubusercontent.com/1104798/67160020-5c1d5100-f34c-11e9-9487-2c70d6b3bd69.png)


Tried storybook (and /addon) version `5.2.4` and `^5.3.0-alpha.23`

**Comment by markushall** [comment]
Ping. Issue still exists on Storybook 5.2.5 and Angular 8.2.12

**Comment by markushall** [comment]
I am using this workaround until this gets fixed properly:
`
Object.defineProperty(global, "Promise", {
    writable: false,
    value: global.Promise
});
`
Placed last in my Jest setup file it makes (the Zone patched) Promise read-only, silently ignoring any further patching/polyfill attempts. Sure it is a hack and may have unwanted side effects, but it seems to do the job for me at least.

**Comment by aroget** [comment]
Ping. Still happening on v.5.3.0-beta.31

**Comment by shilman** [comment]
@aroget want to take a shot at fixing this?

**Comment by costalvaro** [comment]
Ping. Still happening on v.5.3.3. :)

**Comment by Roen00** [comment]
I am facing the same issue with storybook v5.3.7 and angular 8.2.14 :(

**Comment by costalvaro** [comment]
> I am facing the same issue with storybook v5.3.7 and angular 8.2.14 :(

Did you try using @markushall workaround?
Sure it's not perfect but at least it permits to move on. ;)

**Comment by Roen00** [comment]
@costalvaro I am not really sure where exactly I need to put it.
I am not using Jest.

**Comment by Roen00** [comment]
@markushall could u help?

**Comment by Roen00** [comment]
The issue is still there :(

**Comment by aroget** [comment]
After upgrading our app to @angular v9.0.7 and @storybook v.5.3.17 this issue is now resolved on our end.

Thanks!

**Comment by xemlock** [comment]
I recently had the same issue with Storybook 6.3.4 and Angular 12.1.0 on Firefox (90.0) and Safari (13.0.3), no issue on Chrome though. The only solution that worked for me was to completely ignore `core-js/modules/es.promise.js` module in webpack config, by adding the following:

```js
config.resolve = config.resolve || {};
config.resolve.alias['core-js/modules/es.promise.js$'] = false;
```

to `webpackFinal()` function in `.storybook/main.js`.

**Comment by decline** [comment]
Thank you @xemlock, I had the exact same issue on Firefox and Safari (while it worked on Chrome).

I had to put the code in `.storybook/webpack.config.js` though:

```js
module.exports = async ({ config, mode }) => {
  // Make whatever fine-grained changes you need
  config.resolve = config.resolve || {};
  config.resolve.alias['core-js/modules/es.promise.js$'] = false;

  // Return the altered config
  return config;
};
```

**Comment by adriankremer** [comment]
Solved it by updating zone.js to 0.11.4 (0.9.1 before) https://github.com/storybookjs/storybook/issues/15752#issuecomment-894169667

**Comment by stefan-schweiger** [comment]
I'm on 0.11.4 but I still have the problem :/ The code from @decline does work as a temporary workaround at least.
