### ISSUE TITLE
Addon-contexts: switching tab causes SB crash

### ISSUE THREAD

**Issue by pocka** [storybookjs/storybook#7324]
**Describe the bug**
When using `@storybook/addon-contexts@5.2.0-alpha.xx` with addons which use toolbar (e.g. viewport addon) and create tabs (e.g. notes addon), switching to `Canvas` tab causes page crash.

**To Reproduce**
1. `yarn add -D @storybook/addon-contexts@5.2.0-alpha.36 @storybook/addon-viewport@5.2.0-alpha.36 @storybook/addon-notes@5.2.0-alpha.36` then configure them
2. Launch SB
3. Click `Notes` tab
4. Click `Canvas` tab

repo: <https://github.com/pocka/storybook-issue-contexts-tab-crash>
demo: <https://eager-bardeen-152af4.netlify.com>

**Expected behavior**
See canvas tab contents

**Screenshots**
![Screenshot from 2019-07-05 23-25-01](https://user-images.githubusercontent.com/13316015/60728828-3f673400-9f7c-11e9-852a-db0dcce0700c.png)

![Screenshot from 2019-07-05 23-31-43](https://user-images.githubusercontent.com/13316015/60729197-185d3200-9f7d-11e9-8a20-f97529f91f47.png)

**System:**
 - OS: Linux
 - Device: HP Spectre13.3
 - Browser: Google Chrome
 - Framework: React
 - Addons: contexts
 - Version: 5.2.0-alpha

**Additional context**
Doesn't happen in 5.1.x.

**Comment by shilman** [comment]
Son of a gun!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-beta.8 containing PR #7393 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
