### ISSUE TITLE
Can't load font files using custom webpack

### ISSUE THREAD

**Issue by brendonco** [storybookjs/storybook#7335]
Cant load font files using custom webpack.

Font files are stored at: ```src/assets/fonts/[.eot, .ttf, .woff, .woff2]```

custom webpack (even using the comment out webpack config below doesnt help):
```
  config.module.rules.push({
    test: /\.(eot|ttf|woff|otf|woff2)$/,
    include: [path.resolve(__dirname, '../src')],
    use: [
      'file-loader',
    ],
    // use: {
    //   loader: 'file-loader?name=/fonts/[name].[ext]',
    //   options: {
    //     name: 'assets/fonts/[name].[ext]',
    //   },
    // },
  });
```

Storybook version:
```
 "@storybook/addon-actions": "^5.0.11",
    "@storybook/addon-info": "^5.0.11",
    "@storybook/addon-links": "^5.0.11",
    "@storybook/addon-storysource": "^5.0.11",
    "@storybook/addons": "^5.0.11",
    "@storybook/react": "^5.0.11",
```

Please advise.

**Comment by shilman** [comment]
@brendonco First suggestion is to run storybook with `--debug-webpack` and see whether there are collisions for those types (I expect there are). If so, you'll probably need to remove the conflicting rules.

**Comment by brendonco** [comment]
@shilman Thanks.  Indeed there is. I tried to remove the conflict rules but still the fonts doesnt get loaded.

Remove below rules.
```
        { test: /\.(svg|ico|jpg|jpeg|png|gif|eot|otf|webp|ttf|woff|woff2|cur|ani)(\?.*)?$/,
          loader: 'C:\\project\\node_modules\\@storybook\\core\\node_modules\\file-loader\\dist\\cjs.js',
          query: { name: 'static/media/[name].[hash:8].[ext]' } },

```

**Comment by diegolamanno** [comment]
Has anyone found a solution for this? I used to have it working but after upgrading this stopped working.

**Comment by spacegiant** [comment]
@diegolamanno I had this issue with loading SVG files.

It seems that Storybook now imports SVG (and some other file types) already so having a custom rule for SVG was causing a problem.

From my .storybook/webpack.config.js I deleted the whole ruleblock relating to the file type I was having problems with and this seemed to fix my problem:

`{
    test: /\.svg$/,
    loaders: ["file-loader"]
},`

**Comment by alazurenko** [comment]
Hi, 
Are there any update? 
I've stumbled upon the same issue while loading `woff2` font  😞

**Comment by goranefbl** [comment]
Here is the next.config.js that worked for me:


```
module.exports = withSass({
    webpack(config, options) {
        config.module.rules.push({
            test: /\.(woff|woff2|eot|ttf|otf|svg)$/,
            use: [
                {
                    loader: 'url-loader',
                    options: {
                        limit: 8192,
                        fallback: 'file-loader',
                        publicPath: `/_next/static/chunks/fonts/`,
                        outputPath: `${options.isServer ? '../' : ''}static/chunks/fonts/`,
                        name: '[name]-[hash].[ext]'
                    }
                }
            ]
        });
        return config;
    }
});
```

**Comment by brendonco** [comment]
@goranefbl  The config doesn't seem to work. here's my config.  I'm using latest version of storybook.

![image](https://user-images.githubusercontent.com/6521691/69782029-e332d400-11ea-11ea-86e5-ecbb5650f899.png)

**Comment by ndelangen** [comment]
Possibly a silly question, but is the font actually used? A browser will only load a font upon finding it's first usage.

**Comment by fallemand** [comment]
Same problem here after upgrading to `5.3` From `5.2` Can't get it to work

**Comment by iampava** [comment]
Just got it to work by using **CopyWebpackPlugin** instead of the file loader.

Our usecase is this: multiple apps in the same repo (monorepo). Among them, one is a library of common UI components, and it also has storybook. The fonts are located in a different app **client/**. I wanted to import the fonts from **client app** inside **common-ui** to be used by storybook.

Inside storybook's `webpack.config.js` I added:
```
config.plugins.push(
    new CopyWebpackPlugin({
      patterns: [{
        from: resolve(__dirname, '../../client/src/assets/fonts'),
        to: 'static/fonts'
      }]
    }),
  );
```

And then, inside **preview-head.html** I added:

```
<style>
@font-face {
    font-family: "OurFontName";
    src: url("static/fonts/OurFontName.eot");
    src: url("static/fonts/OurFontName.eot?#iefix") format("embedded-opentype"),
      url("static/fonts/OurFontName.woff2") format("woff2"),
      url("static/fonts/OurFontName.woff") format("woff"),
      url("static/fonts/OurFontName.woff") format("truetype");
    font-weight: bold;
    font-style: normal;
  }

  @font-face {
    font-family: "OurFontName";
    src: url("static/fonts/OurFontName.eot");
    src: url("static/fonts/OurFontName.eot?#iefix") format("embedded-opentype"),
      url("static/fonts/OurFontName.woff2") format("woff2"),
      url("static/fonts/OurFontName.woff") format("woff"),
      url("static/fonts/OurFontName.woff") format("truetype");
    font-weight: 400;
    font-style: normal;
  }
</style>
```

And it woooorks 🎉

**Comment by dragos199993** [comment]
> Just got it to work by using **CopyWebpackPlugin** instead of the file loader.
> 
> Our usecase is this: multiple apps in the same repo (monorepo). Among them, one is a library of common UI components, and it also has storybook. The fonts are located in a different app **client/**. I wanted to import the fonts from **client app** inside **common-ui** to be used by storybook.
> 
> Inside storybook's `webpack.config.js` I added:
> 
> ```
> config.plugins.push(
>     new CopyWebpackPlugin({
>       patterns: [{
>         from: resolve(__dirname, '../../client/src/assets/fonts'),
>         to: 'static/fonts'
>       }]
>     }),
>   );
> ```
> 
> And then, inside **preview-head.html** I added:
> 
> ```
> <style>
> @font-face {
>     font-family: "OurFontName";
>     src: url("static/fonts/OurFontName.eot");
>     src: url("static/fonts/OurFontName.eot?#iefix") format("embedded-opentype"),
>       url("static/fonts/OurFontName.woff2") format("woff2"),
>       url("static/fonts/OurFontName.woff") format("woff"),
>       url("static/fonts/OurFontName.woff") format("truetype");
>     font-weight: bold;
>     font-style: normal;
>   }
> 
>   @font-face {
>     font-family: "OurFontName";
>     src: url("static/fonts/OurFontName.eot");
>     src: url("static/fonts/OurFontName.eot?#iefix") format("embedded-opentype"),
>       url("static/fonts/OurFontName.woff2") format("woff2"),
>       url("static/fonts/OurFontName.woff") format("woff"),
>       url("static/fonts/OurFontName.woff") format("truetype");
>     font-weight: 400;
>     font-style: normal;
>   }
> </style>
> ```
> 
> And it woooorks
also please note that `copy-webpack-plugin` needs to be locked on version 6.2.1
and on newer version this config usually it's in main.js (which is the same as webpack.config.js)

**Comment by LavaGolem** [comment]
> Just got it to work by using **CopyWebpackPlugin** instead of the file loader.
> 
> Our usecase is this: multiple apps in the same repo (monorepo). Among them, one is a library of common UI components, and it also has storybook. The fonts are located in a different app **client/**. I wanted to import the fonts from **client app** inside **common-ui** to be used by storybook.
> 
> Inside storybook's `webpack.config.js` I added:
> 
> ```
> config.plugins.push(
>     new CopyWebpackPlugin({
>       patterns: [{
>         from: resolve(__dirname, '../../client/src/assets/fonts'),
>         to: 'static/fonts'
>       }]
>     }),
>   );
> ```
> 
> And then, inside **preview-head.html** I added:
> 
> ```
> <style>
> @font-face {
>     font-family: "OurFontName";
>     src: url("static/fonts/OurFontName.eot");
>     src: url("static/fonts/OurFontName.eot?#iefix") format("embedded-opentype"),
>       url("static/fonts/OurFontName.woff2") format("woff2"),
>       url("static/fonts/OurFontName.woff") format("woff"),
>       url("static/fonts/OurFontName.woff") format("truetype");
>     font-weight: bold;
>     font-style: normal;
>   }
> 
>   @font-face {
>     font-family: "OurFontName";
>     src: url("static/fonts/OurFontName.eot");
>     src: url("static/fonts/OurFontName.eot?#iefix") format("embedded-opentype"),
>       url("static/fonts/OurFontName.woff2") format("woff2"),
>       url("static/fonts/OurFontName.woff") format("woff"),
>       url("static/fonts/OurFontName.woff") format("truetype");
>     font-weight: 400;
>     font-style: normal;
>   }
> </style>
> ```
> 
> And it woooorks 🎉

Hi all of the above is correct, just note from my side, some additional things I needed to do, since I'm new to all this

1. I wasn't able to use just resolve, but path.resolve
2. Make sure that the path you are copying to is the same one as one specified in html you are creating (preview-head-html)
