### ISSUE TITLE
ReactNative: Error: Unable to resolve module `emotion-theming`

### ISSUE THREAD

**Issue by keshavkaul** [storybookjs/storybook#7361]
**Describe the bug**
Cannot build the app because of missing dependency of `emotion-theming` in `@storybook/react-native`. I cannot find `emotion-theming` package directly under root `node_modules` folder but I see that it is present in `node_modules` folder of `@storybook/ui`

Actual error -
```
error: bundling failed: Error: Unable to resolve module `emotion-theming` from `/react-native-project/node_modules/@storybook/react-native/dist/preview/index.js`: Module `emotion-theming` does not exist in the Haste module map
```

**Additional context**
I am using Yarn as my package manager. This seems like a packager issue because I didn't face any error before I rebased my branch.

Versions -
Storybook - 5.1.9
React Native - 0.59.2

**Comment by keshavkaul** [comment]
Quick fixed the issue by adding `emotion-theming@^10.0.10` and `@emotion/core@^10.0.10` to my project's dev dependencies. Maybe this needs to be added as dev dependencies in `@storybook/react-native` for actually solving the root cause.

**Comment by vincentbriglia** [comment]
you have to add @storybook/theming separately

**Comment by oNaiPs** [comment]
Seems to have been fixed in @next
