### ISSUE TITLE
Addon info display possible values for propTypes of oneOf

### ISSUE THREAD

**Issue by jacklimwenjie** [storybookjs/storybook#7365]
**Is your feature request related to a problem? Please describe.**
The Storybook addon `addon-info` displays `oneOf` propType as `other` in the auto-generated PropType Table. 

This is strange because this should already been [fixed in v3.3.14](https://github.com/storybookjs/storybook/issues/790#issuecomment-367326481). 

**Describe the solution you'd like**
In the PropType Table, it should at least display `oneOf` for the `propType` column, preferably with the possible values e.g. `oneOf("val1" | "val2" | "val3" | ... )`

**Describe alternatives you've considered**
The easiest workaround is to include the possible values in the `description` of PropType Table.

**Are you able to assist bring the feature to reality?**
Maybe

**Additional context**
Below are the version of related packages I'm using: 
```
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "@storybook/addons": "^5.1.9",
    "@storybook/react": "^5.1.9",
    "@storybook/addon-info": "^5.1.9",
    "babel-loader": "^8.0.6",
    "@babel/core": "^7.5.4",
```
I've tried to reproduce the issue above with a fresh `create-react-app` project.

**Comment by shilman** [comment]
FYI `addon-info` is being superceded by `addon-docs`, which fixes a bunch of bugs and is easier to maintain. It’s reached release candidate (RC) status and will be properly released soon. Please give it a try! https://medium.com/storybookjs/storybook-docspage-e185bc3622bf

@jacklimwenjie @github-actions @stale
