### ISSUE TITLE
Error spawn cmd ENOENT

### ISSUE THREAD

**Issue by uxitten** [storybookjs/storybook#7386]
After run Storybook, I see an error

**To Reproduce**
1- Run command ```start-storybook -p 6006```
2- See an error

**Screenshots**
![image](https://user-images.githubusercontent.com/1549069/61051650-c5610000-a3fe-11e9-8df6-2b4b4d3b6531.png)

**Code snippets**
```js
import { configure } from '@storybook/react';
import { initializeRTL } from 'storybook-addon-rtl';

initializeRTL();

// automatically import all files ending in *.stories.js
const req = require.context('../src', true, /\.stories\.js$/);
function loadStories() {
  req.keys().forEach(filename => req(filename));
}

configure(loadStories, module);
```

**System:**
 - OS: Windows10
 - Device: PC
 - Browser: Chrome
 - Framework: react (create-react-app)
 - Addons: [@storybook/addon-knobs, @storybook/addon-notes/, storybook-addon-rtl]
 - Version: 5.1.9

**Comment by klh** [comment]
bump on this one

**Comment by snyderhaus** [comment]
Double bump, what's going on with this? Tried multiple things to resolve with no conclusion.

**Comment by cmmdmx** [comment]
Wow, the 

`BROWSER=none`

is giving me a real  bunch of errors - but - it works? Strange. But thank you so much!

**Comment by sarahannnicholson** [comment]
@snyderhaus Thank you! That worked for me. Is there any way to specify a default browser? like a storybook or webpack env file?

**Comment by HazelCindy** [comment]
I

> Wow, the
> 
> `BROWSER=none`
> 
> is giving me a real bunch of errors - but - it works? Strange. But thank you so much!

This worked for me with no errors

**Comment by silleknarf** [comment]
For anyone who finds this thread. I found a workaround here: https://github.com/storybookjs/storybook/issues/24191#issuecomment-1744987158

In short, try:

`BROWSER=true npm run storybook`
