### ISSUE TITLE
Angular Storybook's 'Centered' stories are broken.

### ISSUE THREAD

**Issue by MatthewMSaucedo** [storybookjs/storybook#7396]
**Describe the bug**
Console shows issue with styles.

**To Reproduce**
1. Go to 'https://storybooks-angular.netlify.com/?path=/story/addon-centered--centered-component'

**Screenshots**
![Screen Shot 2019-07-12 at 9 01 28 AM](https://user-images.githubusercontent.com/42758985/61130329-6f36a000-a484-11e9-9ad1-37937693c9cc.png)

**Comment by shilman** [comment]
@CodeByAlex didn't you fix this?

**Comment by ThibaudAV** [comment]
I think we can close this issue @MatthewMSaucedo 
I tested with the latest version of storybook and what is said here: 
https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#removed-addon-centered
and it looks good :) 

cc @shilman
