### ISSUE TITLE
@storybook/marko: Add DefinePlugin to src/server/framework-preset-marko.js

### ISSUE THREAD

**Issue by melquan** [storybookjs/storybook#7403]
**Describe the solution you'd like**
Add DefinePlugin to src/server/framework-preset-marko.js to set an environment variable.

```
const { DefinePlugin } = require('webpack');

...

  plugins: [...config.plugins, new DefinePlugin({
    "process.env.BUNDLE": true
  })],
```

**Comment by shilman** [comment]
Is this something required by all marko users or just your project? If the latter, you should be able to configure it yourself in `.storybook/webpack.config.js`?

**Comment by melquan** [comment]
@shilman, it should be for all marko users, but please confirm with Dylan Piercey (@DylanPiercey).  He asked me to file this ticket.

**Comment by DylanPiercey** [comment]
@shilman it is needed for a subset of Marko API's and should probably be set by default for Marko apps.

I will be personally integrating storybook with Marko into some apps shortly and I'll put up a PR for this and #7404 to make sure all is running smoothly. 😄

**Comment by shilman** [comment]
Thanks for the clarification @melquan @DylanPiercey. Looking forward to the PR! 💯

**Comment by DylanPiercey** [comment]
@shilman on second glance I am realizing this is not needed. The `process.env.BUNDLE` we are only using when you are bundling Marko with the `node` target in webpack which is not happening here.

This issue can be closed.

**Comment by melquan** [comment]
Closing per Dylan's comment.
