### ISSUE TITLE
@storybook/marko: Migrate from 'marko-loader' to '@marko/webpack/loader'

### ISSUE THREAD

**Issue by melquan** [storybookjs/storybook#7404]
**Describe the solution you'd like**
Migrate from 'marko-loader' to '@marko/webpack/loader' which provides some bug fixes and enhanced functionality.

https://github.com/marko-js/webpack

**Comment by ndelangen** [comment]
Hello @melquan would you be able to contribute with a PR for this? I can help if you want.

**Comment by shilman** [comment]
Jiminy cricket!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-beta.4 containing PR #7459 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
