### ISSUE TITLE
Harden `actions` function of `@storybook/addon-actions`

### ISSUE THREAD

**Issue by backbone87** [storybookjs/storybook#7423]
**Describe the bug**
Harden `actions` function of `@storybook/addon-actions` to allow calls with empty args:
https://github.com/storybookjs/storybook/blob/next/addons/actions/src/preview/actions.ts#L9

should be:
`names.length > 1`

when called with no args (which is a valid use case, when actions are generated from some metadata), the condition on the linked line will be `true`, then this would cause an error, when the last value is spread into the config. (pop returns undefined on empty arrays)

**Comment by backbone87** [comment]
Not stale

**Comment by vanessayuenn** [comment]
Hi! I am going through and cleaning up old issues in the repo. We just shipped a ton of improvements in Storybook 7.0, and I suspect this bug might be fixed already. Can you please try it out? If this issue persists with the latest version, please open a new bug report with a 7.x reproduction. Thank you so much! 🙏🏼
