### ISSUE TITLE
Storybook 5.2 Release 🚀

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#7430]
It's that time again! [Storybook 5.1](https://medium.com/storybookjs/storybook-5-1-50afd02b5bbb) is stable and 5.2 is coming down the pipe!

## Schedule

- ✅ `5.2.0-alpha.0`: 2019-04-29
- ✅ `5.2.0-beta.0`: 2019-07-15
- ✅ `5.2.0-rc.0`: 2019-08-30
- ✅ `5.2.0`: 2019-09-17 (ready on 09-10, delaying to avoid clashing with Apple event)

## Contents

- [x] [Storybook DocsPage](https://medium.com/storybookjs/storybook-docspage-e185bc3622bf)
  - [x] React
  - [x] Partial support for all frameworks
  - [x] Iterate beta feedback
  - [x] Documentation
- [x] [Component Story Format](https://medium.com/storybookjs/component-story-format-66f4c32366df)
  - [x] Definition
  - [x] Loader
  - [x] Codemods
  - [x] SB CLI Migration
  - [x] Documentation
- [x] [Design System](https://medium.com/storybookjs/introducing-storybook-design-system-23fd9b1ac3c0)
  - [x] Component librray
  - [x] 3x Apps
  - [ ] Documentation
- [x] Addon API
  - [x] Hooks-based API
  - [ ] Documentation
- [x] Jest Addon redesign
- [x] Story sorting
  - [x] Implementation
  - [x] Documentation
- [ ] Typescript
  - [x] Typings for addons, `@storybook/react`, `@storybook/angular`
- [x] CLI `--preview-url` for remote preview
  - [x] Rollup example
- [ ] Yarn PnP support?

Full list of changes in [CHANGELOG](https://github.com/storybookjs/storybook/blob/next/CHANGELOG.md)

## Help Wanted (Now!)

We need your help stabilizing Storybook 5.2 for the final release. It's in beta now because we think it's ready to use in most projects.

The biggest thing is to try upgrading your project to the latest prerelease, see if you run into problems, and file github isues. The sooner we uncover problems with the upgrade, the more time we have to fix and document them.

To upgrade your project:

```bash
npx npm-check-updates '/storybook/' -un
npm install # yarn if you prefer
```

We've also started to document [migration instructions](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#From-version-51x-to-52x), and will continue to update the documentation throughout the release.

And of course, if you see any issues that you can help with, PRs are _always_ welcome. Storybook wouldn't be possible without high-quality contributions from our wonderful community.

Thanks for your help and stay posted for more updates!

**Comment by gaui** [comment]
When you say, partial support for all frameworks, does it mean we could adapt to any library that utilises hyperscript syntax?

**Comment by shilman** [comment]
@gaui Storybook supports multiple frameworks and docs uses the same mechanism under the hood. But docs has additional functionality (like automatically displaying prop tables for your components) that is implemented on a framework-by-framework basis. 

You can see which features are supported for which frameworks here: https://github.com/storybookjs/storybook/blob/next/addons/docs/README.md

**Comment by inlikealion** [comment]
So, I'm working on my first big Storybook and Vue app. Would you say Vue with Storybook has broad enough support in the current 5.2 beta? Or are you mostly looking for React folks at this point as far as viewing this as relatively stable?

**Comment by shilman** [comment]
@inlikealion SB Vue support is stable and usable. Vue support SB Docs is also useable but still early. If it's useful I'd be happy to go through any issues you run into on our Discord and get them sorted out, since the documentation is still sparse. https://docs.google.com/document/d/1un6YX7xDKEKl5-MVb-egnOYN8dynb5Hf7mq0hipk8JE/edit?usp=sharing

**Comment by inlikealion** [comment]
@shilman Thanks for the documentation hookup. Which channel in Discord should I go to for followup?

**Comment by shilman** [comment]
@inlikealion It's the `#docs-mode` channel 👍

**Comment by shilman** [comment]
Released Sep 13, announcement coming Sep 17
