### ISSUE TITLE
Ability to hide the tab bar

### ISSUE THREAD

**Issue by flxwu** [storybookjs/storybook#7431]
There are documentation-only pages on which I don't want to see the tab bar at the top. Can I hide it somehow? This is probably coming with addon-docs, but I'm not using it yet.

Thanks!

**Comment by flxwu** [comment]
Yeah, that was what I searched for. Thank you a lot! I hope that we'll soon see individual show/hide tab functionalities as well :)

**Comment by rodoabad** [comment]
So this can't be turned off per story right now? Only global @shilman ?

**Comment by NishargShah** [comment]
This will be your answer

https://stackoverflow.com/a/66188323/8798220
