### ISSUE TITLE
React Native: Backgrounds addon

### ISSUE THREAD

**Issue by RWOverdijk** [storybookjs/storybook#7432]
**Describe the bug**

The backgrounds addon for ondevice doesn't work as expected. I've seen several issues:

1. When combined with the knobs addon and importing the backgrounds addon **first**, an error is thrown:

> TypeError: null is not an object ('evaluating this.state.selection'). 

I see duplicate dependencies (nested node_modules) so perhaps something hasn't been updated yet? For some reason `this.state` is null in the `BackgroundPanel.render()`.

2. Once loaded, the background colour I set as a default is shown, but there's no panel for me to change the background colour and thus I can only ever see one of the colours. I do think the two issues are related.

**To Reproduce**

This is a new React Native project with all the latest versions of storybook (`@next`). It's all basic quick start stuff (addons file, and decorators).

**Expected behavior**

A way to toggle the background colour.

**System:**
 - Device: iPhone X
 - Framework: React Native
 - Addons: Knobs and backgrounds
 - Version: See additional

**Additional context**

A dump of all storybook related packages and their versions:

```
mixed/efteling-app [ yarn list | grep storybook                                                                                              feature/APP-2743-storybook * ] 10:49 AM
├─ @storybook/addon-actions@5.2.0-beta.0
│  ├─ @storybook/addons@5.2.0-beta.0
│  ├─ @storybook/api@5.2.0-beta.0
│  ├─ @storybook/client-api@5.2.0-beta.0
│  ├─ @storybook/components@5.2.0-beta.0
│  ├─ @storybook/core-events@5.2.0-beta.0
│  ├─ @storybook/theming@5.2.0-beta.0
├─ @storybook/addon-backgrounds@5.2.0-beta.0
│  ├─ @storybook/addons@5.2.0-beta.0
│  ├─ @storybook/api@5.2.0-beta.0
│  ├─ @storybook/client-logger@5.2.0-beta.0
│  ├─ @storybook/components@5.2.0-beta.0
│  ├─ @storybook/core-events@5.2.0-beta.0
│  ├─ @storybook/theming@5.2.0-beta.0
├─ @storybook/addon-knobs@5.2.0-beta.0
│  ├─ @storybook/addons@5.2.0-beta.0
│  ├─ @storybook/client-api@5.2.0-beta.0
│  ├─ @storybook/components@5.2.0-beta.0
│  ├─ @storybook/core-events@5.2.0-beta.0
│  ├─ @storybook/theming@5.2.0-beta.0
├─ @storybook/addon-ondevice-actions@5.2.0-beta.0
│  ├─ @storybook/addons@5.2.0-beta.0
│  ├─ @storybook/core-events@5.2.0-beta.0
├─ @storybook/addon-ondevice-backgrounds@5.2.0-beta.0
│  ├─ @storybook/addons@5.2.0-beta.0
├─ @storybook/addon-ondevice-knobs@5.2.0-beta.0
│  ├─ @storybook/addons@5.2.0-beta.0
│  ├─ @storybook/core-events@5.2.0-beta.0
├─ @storybook/addon-storyshots@5.2.0-beta.0
│  ├─ @storybook/addons@5.2.0-beta.0
├─ @storybook/addons@5.2.0-beta.0
│  ├─ @storybook/api@5.2.0-beta.0
│  ├─ @storybook/channels@5.2.0-beta.0
│  ├─ @storybook/client-logger@5.2.0-beta.0
├─ @storybook/api@5.2.0-beta.0
│  ├─ @storybook/channels@5.2.0-beta.0
│  ├─ @storybook/client-logger@5.2.0-beta.0
│  ├─ @storybook/core-events@5.2.0-beta.0
│  ├─ @storybook/router@5.2.0-beta.0
│  ├─ @storybook/theming@5.2.0-beta.0
├─ @storybook/channel-postmessage@5.2.0-beta.0
│  ├─ @storybook/channels@5.2.0-beta.0
│  ├─ @storybook/client-logger@5.2.0-beta.0
├─ @storybook/channel-websocket@5.2.0-beta.0
│  ├─ @storybook/channels@5.2.0-beta.0
├─ @storybook/channels@5.2.0-beta.0
├─ @storybook/client-api@5.2.0-beta.0
│  ├─ @storybook/addons@5.2.0-beta.0
│  ├─ @storybook/channel-postmessage@5.2.0-beta.0
│  ├─ @storybook/channels@5.2.0-beta.0
│  ├─ @storybook/client-logger@5.2.0-beta.0
│  ├─ @storybook/core-events@5.2.0-beta.0
│  ├─ @storybook/router@5.2.0-beta.0
├─ @storybook/client-logger@5.2.0-beta.0
├─ @storybook/components@5.2.0-beta.0
│  ├─ @storybook/client-logger@5.2.0-beta.0
│  ├─ @storybook/theming@5.2.0-beta.0
├─ @storybook/core-events@5.2.0-beta.0
├─ @storybook/react-native@5.2.0-beta.0
│  ├─ @storybook/addons@5.2.0-beta.0
│  ├─ @storybook/channel-websocket@5.2.0-beta.0
│  ├─ @storybook/channels@5.2.0-beta.0
│  ├─ @storybook/client-api@5.2.0-beta.0
│  ├─ @storybook/core-events@5.2.0-beta.0
├─ @storybook/router@5.2.0-beta.0
├─ @storybook/theming@5.2.0-beta.0
│  ├─ @storybook/client-logger@5.2.0-beta.0
```

**Comment by shilman** [comment]
@RWOverdijk this might not solve anything but please upgrade all the packages to `5.2.0-beta.0`. All bets are off when different versions are running together. That's probably not the issue here, but it's good to eliminate that variable anyway. 😉

**Comment by RWOverdijk** [comment]
@shilman Your release cycle is absolutely insane. 😄 I like it.

I updated everything and same thing.

I did find out something else though! The tab for backgrounds _does_ show up, but it's behind the notch. If I wrap the StorybookUI in a SafeAreaView I can see the tabs.

Is that considered a bug? Or is it in the docs and I missed it?

Anyway, it doesn't solve the problem as the tab is showing this (which I've done):

![Simulator Screen Shot - iPhone X - 2019-07-16 at 10 45 21](https://user-images.githubusercontent.com/781745/61279690-e20e8680-a7b6-11e9-8922-6b78b414c3fb.png)

Which is weird, because it does show my default background color:

```js
addDecorator(withBackgrounds)
addParameters({
  backgrounds: [
    { name: 'light', value: '#eeeeee', default: true },
    { name: 'dark', value: '#222222' },
  ]
})
```

I've tried all variations. Global decorators, global parameters, story-level decorator and parameters... No bueno. Keep seeing what's in that screenshot.

**Comment by RWOverdijk** [comment]
Both issues have been fixed through #7437

**Comment by shilman** [comment]
Gadzooks!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-beta.1 containing PR #7437 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

**Comment by RWOverdijk** [comment]
> gadzooks
> /ɡadˈzuːks/
> _exclamation (ARCHAIC)_
> an exclamation of surprise or annoyance.

:o

**Comment by shilman** [comment]
@RWOverdijk More the former than the later, I assure you 😘
