### ISSUE TITLE
Dark theme: Markdown inline code is hard to read

### ISSUE THREAD

**Issue by shiftgeist** [storybookjs/storybook#7434]
**Describe the bug**
When dark theme is enabled, markdown (Notes) inline code is hard to read, because it is styled white text on white'ish background.

**To Reproduce**
1. Run storybook.
0. Navigate to story.
0. Click on 'Notes'.
0. Get white text on white'ish background.

**Expected behavior**
Black text on white'ish background.

**Screenshots**
![image](https://user-images.githubusercontent.com/30648730/61280210-c5bf1980-a7b7-11e9-8d80-bd07d4a5fbeb.png)

**Code snippets**
```javascript
// themeFile.js

import { create } from '@storybook/theming';

export default create({
    base: 'dark'
});
```

```javascript
// demo.story.js

storiesOf('Documentation', module)
    .add('README', () => ({
        template: 'Nothing here.',
        props: {
            demo: boolean('demo', false)
        }
    }), {
        notes: { markdown: elementsDocs }
    });

```

**System:**
 - OS: Debian Buster
 - Device: Linux
 - Browser: Chrome Beta 76.0.3809.62
 - Framework: Angular
 - Addons: `@storybook/addon-notes`
 - Version: `"@storybook/angular": "^5.1.9"`

**Comment by shilman** [comment]
Pretty sure this got fixed in 5.3 (or late 5.2?)
