### ISSUE TITLE
CLI: Warn on package version mismatch

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#7435]
I see lots of support issues where users are using a variety of different `@storybook/*` package versions, e.g. `5.0.x`, `4.0.x`, `5.2.0-alpha.x` all mixed together.

We should check for this on load and warn them to upgrade to the same version.

**Comment by shilman** [comment]
@jamesgeorge007 Any interest in taking a crack at this?

**Comment by jamesgeorge007** [comment]
@shilman sure would be great if you could elaborate it further :clap:

**Comment by shilman** [comment]
@jamesgeorge007 For example, a user might have the following packages installed in their project:

```
@storybook/addon-docs@5.2.0-beta.24,
@storybook/addon-knobs@5.1.10,
@storybook/react@5.0.0,
```

While this is OK from a semver standpoint (theoretically these packages might work together since they are all the same major version), we want users to be using the same versions of `@storybook/*`. So in this case we'd prefer them to upgrade all their packages to match. This will minimize the chances of bugs due to weird version differences:

```
@storybook/addon-docs@5.2.0-beta.24,
@storybook/addon-knobs@5.2.0-beta.24,
@storybook/react@5.2.0-beta.24,
```

I think a warning on the CLI when they `start-storybook` or `build-storybook`.

I filed the issue because I see this all the time when I'm trying to support storybook users. If everybody's using consistent versions, it will result in fewer support issues and fewer steps in the support process.

**Comment by shilman** [comment]
One tricky thing is that we have other packages, like `@storybook/design-system` that are not part of the monorepo and are on a different versionings schedule.

**Comment by rogerhutchings** [comment]
Related to #4617?

**Comment by pahan35** [comment]
@shilman what is the expected format of warning should be?

I managed to retrieve storybook packages and added a hardcoded list of packages for which we shouldn't warn about mismatch, but it's not clear which kind of warning to show if there is a mismatch.

If you provide your expectations here, I'll submit a PR for this improvement.

**Comment by shilman** [comment]
@pahan35 Sorry for the slow reply. Something like:

```
The following Storybook package versions are mismatched in your project:

@storybook/react: ^6.3.0 => 6.3.12
@storybook/core: ^6.3.0 => 6.4.8
...

For best results, make sure that you are running the same package versions.

To upgrade all packages to a consistent version:

Latest stable release: `npx sb@latest upgrade`	
Latest prerelease: `npx sb@next upgrade --prerelease`
```

**Comment by valentinpalkovic** [comment]
The Storybook doctor command takes care of this: https://github.com/storybookjs/storybook/blob/next/code/lib/cli/src/doctor/getMismatchingVersionsWarning.ts. Closing
