### ISSUE TITLE
CSF: Component Story Format documentation

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#7440]
- [x] blog post
- [x] module format embedding example
- [x] module format reference
- [x] update existing docs examples
- [x] migration instructions

**Comment by SQReder** [comment]
It is still not clear why I should specify the `component` field when exporting by default to CSF. In fact, the default export format does not have a clear specification, at all.

TypeScript definitions might provide specification, but AFAIK they don't. (#7677)
