### ISSUE TITLE
[Feature Question] Hyperlinks in sidebar?

### ISSUE THREAD

**Issue by flxwu** [storybookjs/storybook#7443]
Is there a way to have direct hyperlinks in the sidebar? See example below.

Thank you very much!

![image](https://user-images.githubusercontent.com/16862997/61349696-47b94c00-a865-11e9-9cda-90573fa566c6.png)

**Comment by shilman** [comment]
@flxwu not currently. you can modify the storybook logo AND/OR make it link to a custom page, however. See `brandUrl` etc. options in https://storybook.js.org/docs/configurations/theming/#create-a-theme-quickstart

**Comment by shilman** [comment]
Closing as dupe to #8047
