### ISSUE TITLE
addon/notes: syntaxhighlighter treat children as string may have errors

### ISSUE THREAD

**Issue by fxxjdedd** [storybookjs/storybook#7447]
**Describe the bug**
I encountered an error while writing markdown in notes, the console suggesting that `children.trim` is not a function.

The strange thing is that only when I write the code block such as ```jsx will report an error, there is **no problem** writing the general markdown code.

**To Reproduce**
write code block in notes suchs as:
![image](https://user-images.githubusercontent.com/13739947/61368773-2dad5700-a8c1-11e9-983c-48ba2b388fe2.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/13739947/61368827-503f7000-a8c1-11e9-99f8-e73abf1f9531.png)

**System:**
 - OS: Windows10
 - Browser: chrome
 - Framework: Vue
 - Addons: notes
 - Version: 5.1.9

**Additional context**
the children prop may be an array, treat children as string may have errors:
https://github.com/storybookjs/storybook/blob/538924f3e2995aafeb3935b2e985f5357d4d0df5/lib/components/src/syntaxhighlighter/syntaxhighlighter.tsx#L156

**Comment by slaviczavik** [comment]
Is there any news about this issue? Simple block code with triple ` works fine, but if you specify language such as ```js ```html or something else it throws this error.

**Comment by shilman** [comment]
Please take a look at Storybook Docs, which is intended to replace `addon-info` and `addon-notes`, doesn't have this problem, and is being more actively maintained: https://medium.com/storybookjs/storybook-docspage-e185bc3622bf
