### ISSUE TITLE
[addon-contexts] Syntax causing issues with Storyshots addon

### ISSUE THREAD

**Issue by jrsearles** [storybookjs/storybook#7453]
**Describe the bug**
The contexts plugin works fine for me in the browser, but when run through Jest via the Storyshots addon a syntax error is generated.

```
    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    Details:

    C:\dev\random\repo\node_modules\@storybook\addon-contexts\react.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { withContexts } from './dist/preview/frameworks/react';
```

**To Reproduce**
1. Add the import into your Storybook config in a project using Storyshots
2. Run jest

**System:**
 - OS: Windows10
 - Device: PC (node v10.15.0)
 - Browser: jsdom
 - Framework: React
 - Addons: addon-contexts & addon-storyshots
 - Version: 5.1.9

**Additional context**
The problem appears to be the import destructuring syntax in the react.js file. I believe that i could resolve this by updating the Jest and/or Webpack config to transpile the files in the node_modules, however this hasn't been necessary for other addons. I believe the addon should probably be transpiled to es5.

**Comment by saviomuc** [comment]
To all others looking for a quick solution, just add this to your jest config and make sure that you have you babel config in a `babel.config.js` file.

```
    "transformIgnorePatterns": [
      "node_modules/(?!(@storybook/addon-contexts)/)"
    ]
```

**Comment by alex-knyazev** [comment]
Hi, this issue is still actual. I have issue with "LinkTo " component when using jest with storybook.

![image](https://github.com/storybookjs/storybook/assets/15632220/ed641c35-9e32-439d-8bf9-3fbc94b5ed1b)
