### ISSUE TITLE
Storysource: possible to show _only_ story code?

### ISSUE THREAD

**Issue by tommedema** [storybookjs/storybook#7461]
Currently when I have a story like so:

<img width="620" alt="Screen Shot 2019-07-17 at 4 09 36 PM" src="https://user-images.githubusercontent.com/331833/61417792-4ad82a80-a8ad-11e9-9bf5-6f19c1c82f2f.png">

This displays the entire `.stories.js` code:

<img width="493" alt="Screen Shot 2019-07-17 at 4 10 04 PM" src="https://user-images.githubusercontent.com/331833/61417815-5c213700-a8ad-11e9-8ffd-d18873273144.png">

The story "boilerplate" surrounding the actual story function is confusing and distracting to the user interested in using the component. Instead, would it be possible to _only_ show the story code? For example in this case it would render only:

```
<FlipCardFront />
```

**Comment by shilman** [comment]
@tommedema You might want to check out addon-docs, which almost does this, tho with a very different UI:

<img width="869" alt="Storybook" src="https://user-images.githubusercontent.com/488689/61434727-538e3680-a969-11e9-8984-e642fb79d183.png">

https://docs.google.com/document/d/1un6YX7xDKEKl5-MVb-egnOYN8dynb5Hf7mq0hipk8JE/edit?usp=sharing

**Comment by tommedema** [comment]
@shilman cool, this looks like something we will use once it gets out of beta. Will stick with the more noisy storysource code for now due to the lesser complexity/effort involved.
