### ISSUE TITLE
Support react-scripts installed at monorepo root

### ISSUE THREAD

**Issue by duhseekoh** [storybookjs/storybook#7462]
**Is your feature request related to a problem? Please describe.**
It is a feature request. 
I have a monorepo (yarn workspaces) with several CRA apps. Each of those apps has their own storybook. I recently decided to move react-scripts to the monorepo root package.json as a dev dep since it stopped making sense to keep individual versions of react-scripts for each workspace as I update all of them at once anyways.
When I start a storybook in one of the workspaces it doesn't detect react-scripts even though its installed in the repo root node_modules.
When working in a monorepo setup it's typical to have a lot of common devDependencies in the root package.json and react-scripts happens to be one of those.

**Describe the solution you'd like**
For storybook to detect react-scripts installed in a monorepo root and using the webpack config from that.

**Describe alternatives you've considered**
Tried going into full-control mode, requiring the react-scripts webpack config and using that, but ran into a bunch of errors 🤷‍♂ 

**Are you able to assist bring the feature to reality?**
Sure, I could help out. I believe it can be fixed by some modifications to this file: https://github.com/storybookjs/storybook/blob/e211b3765e57bc7cc32b8dd9579d86ea03a6c5ee/app/react/src/server/cra-config.js#L22

**Comment by mrmckeb** [comment]
Right now there are problems with `react-scripts` and monorepos in general. We need to resolve that on the CRA-side, and then update the implementation here to match.

You said you were having issues with the `webpack.config.json` route, perhaps I can help there? Can you share an example repo maybe?
