### ISSUE TITLE
Possible invalid peer dependency version for @angular-devkit/build-angular

### ISSUE THREAD

**Issue by nzacca** [storybookjs/storybook#7466]
**Describe the bug**
Peer dependency for `@angular-devkit/build-angular` in the `@storybook/angular` package lists a required version of `>= 6.0` . All versions for devkit appear to be `< 1`, with the latest for Angular 8 being `0.801.2` at this current time.

**To Reproduce**
1. Install `@storybook/angular` package with the latest devkit installed.
2. Note the peer dependency warning.

**Expected behavior**
Expect no peer dependency warning.

**System:**
 - OS: Windows 10
 - Framework: Angular
 - Version: storybook/angular 5.2.0-beta.1

**Additional context**
Not sure what version of devkit would be appropriate here to recommend a minimum version. I'm willing to submit a PR if someone could indicate which version to use instead.

**Comment by nzacca** [comment]
Version 0.8.9 appears to be [marked](https://www.npmjs.com/package/@angular-devkit/build-angular?activeTab=versions) as `v6-lts` which I assume is for Angular v6. Could we change the peer dependency to be `>=0.8.9`?

https://github.com/storybookjs/storybook/blob/v5.2.0-beta.12/app/angular/package.json#L47

**Comment by kroeder** [comment]
@nzacca `>=0.8.9` sounds good! Can you open a PR for this?

**Comment by nzacca** [comment]
@kroeder Of course! Coming right up.

**Comment by nzacca** [comment]
@kroeder [PR is up](https://github.com/storybookjs/storybook/pull/7585).
