### ISSUE TITLE
Storybook and RN 0.60.3

### ISSUE THREAD

**Issue by simonwalker-celadin** [storybookjs/storybook#7472]
This is our package.json script command for storybook: "storybook": "start-storybook -p 7007 | yarn start --projectRoot storybook --watchFolders $PWD",
This appears to be working well with RN v .59.9 and Storybook 1.0.0. However the '--projectRoot' command causes storybook to fail to launch when we upgrade to RN .60.3.

**Comment by shilman** [comment]
@simonwalker-celadin what version of storybook?

**Comment by simonwalker-celadin** [comment]
I am running Storybook version 5.1.9

This is the package.json section defining storybook
```
"@storybook/addon-actions": "^5.1.9",
"@storybook/addon-links": "^5.1.9",
"@storybook/addons": "^5.1.9",
"@storybook/react-native": "^5.1.9",
"@storybook/react-native-server": "^5.1.9",
```

This is in package.json scripts
```
 "storybook": "start-storybook -p 7007 | yarn start --projectRoot storybook --watchFolders $PWD"
```

This is the error I am getting
```
yarn run v1.6.0
$ start-storybook -p 7007 | yarn start --projectRoot storybook --watchFolders $PWD
$ node node_modules/react-native/local-cli/cli.js start --projectRoot storybook --watchFolders /Users/XXXX/XXXX/XXXX/XXXXReactNativePlayground
error: unknown option `--projectRoot'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
info => Loading presets
info => Loading custom babel config as JS
info => Loading custom addons config.
```

**Comment by Gongreg** [comment]
Hey, 
Looks like projectRoot option has been removed from cli in RN 60.
If you want to keep using it like this I recommend to add projectRoots to your metro config and change them according to the environment.

Also the documentation in storybook should be updated to reflect this change.

**Comment by simonwalker-celadin** [comment]
Thanks for your response. This is something new for me, could you please expand on this. My current metro config looks like this...

```
module.exports = {
  transformer: {
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: false,
      },
    }),
  },
};
```

**Comment by Gongreg** [comment]
```

module.exports = {
  transformer: {
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: false,
      },
    }),
  },
  projectRoot: process.env.RUNNING_STORYBOOK ? path.resolve(__dirname, './storybook') : path.resolve(__dirname),
};

```


And then in the command:

`"storybook": "start-storybook -p 7007 | RUNNING_STORYBOOK=true yarn start --watchFolders $PWD",`

**Comment by simonwalker-celadin** [comment]
Thank you, this has got me going with this version of RN and Storybook
