### ISSUE TITLE
Switch css files from theme

### ISSUE THREAD

**Issue by padevone** [storybookjs/storybook#7474]
Hi. I created storybook for Vue, but i want to display my components in different themes.
The themes are different css styles. Can do i switch these files from selected theme?
These files build by Webpack (full-control mode).

**Comment by shilman** [comment]
Maybe this will help? https://github.com/storybookjs/storybook/pull/7465

**Comment by padevone** [comment]
@shilman thanks for reply. It's not that i want, but maybe i will try it.
In my case i want to switch style-files for different themes, because they have absolutely different styles.

**Comment by padevone** [comment]
@shilman Thanks. it's near my goal. I will try it.

**Comment by padevone** [comment]
@shilman, i try use addon cssresource, but i have one problem. 
I build stylesheet with storybook's webpack. I add my style sources in entry for webpack's config, but storybook includes all entries.
Can i exclude some webpack's entries for storybook?

**Comment by ndelangen** [comment]
@padevone I'm working on making this easier.

Right now you can customize the storybook webpack config so you override the `files` templateParameters.

This is what we do in storybook:
https://github.com/storybookjs/storybook/blob/next/lib/core/src/server/preview/iframe-webpack.config.js#L47-L62

You'll want to filter the `files.css` so they do not contain the specific css files you don't want.

**Comment by padevone** [comment]
Thanks, @ndelangen. I will try it. I saw enough solutions.
