### ISSUE TITLE
Addon-Docs: Configurable Source snippetization

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#7479]
Add the ability to configure Source block with per-framework snippetization, or even user-configurable snippetization. E.g. 

- @CodeByAlex wants just the `template:` field for Angular
- `etb` (?) wants to remove the `() => ...`
- `HamHam` wants to remove single quotes from:

```jsx
    <Story name="heading" height="100px">
      {'<h1>Hello World</h1>'}
    </Story>
```
- @kushalmahajan wants to include the component's source in the story #10039

**Comment by mpalpha** [comment]
Perhaps adding an option globally to pass each UI pattern through a transformer would be a good approach.

**Comment by alazurenko** [comment]
Hello, 
Is there is chance that it would be shipped in next 5.3.0 version? 😊

**Comment by shilman** [comment]
@alazurenko yeah, good chance of that!

**Comment by kfayelun** [comment]
Hey! I see it's not listed on the top here, but I saw it mentioned in a comment on dischord; that this fix might let us show html markup from rendered react components. Do you know if this will make it in? When will 5.3.0 ship? Will it be on a @next tag?

**Comment by shilman** [comment]
@kfayelun hopefully will work this in over the next 1-2 weeks. 5.3 will ship in early jan https://github.com/storybookjs/storybook/issues/8658

**Comment by o-t-w** [comment]
Is this now available in the 5.3.0-beta? I'd really like to try it! How do I get it to show both the React markup and the HTML markup?

**Comment by kfayelun** [comment]
I hate to nag, I know you guys have loads of stuff to sort out before 5.3 release. My deadline is closing in on me fast, any idea when this will be tackled?

**Comment by hsablonniere** [comment]
In our case, we cheated and would love an official way to provide a custom source snippet:

* Generate source https://github.com/CleverCloud/clever-components/blob/master/stories/lib/make-story.js#L67-L93
* Override source with `mdxSource` https://github.com/CleverCloud/clever-components/blob/master/stories/lib/make-story.js#L67-L93

Event better would be to be able to customize the source component used in the docs page.

**Comment by shilman** [comment]
@hsablonniere you might be able to hack in your own component today: 

https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/theming.md#mdx-component-overrides

We should also provide better source snippetization in 6.0 (knock wood)

**Comment by hsablonniere** [comment]
@shilman I think I already tried those, does it laso work for DocsPage generated from CSF files?

**Comment by shilman** [comment]
@hsablonniere Aha unfortunately not. We'll do our best to get you a good solution in the next release cycle.

**Comment by rijkvanzanten** [comment]
@shilman Are there any outstanding things that need to be done to move this forwards? I would love to help out where possible.

**Comment by rijkvanzanten** [comment]
You can use `mdxSource` on `<Preview>` as a temporary override. Not ideal, but provides the expected highlighted source code:

```html
<Preview mdxSource={`
  <v-icon name="accessibility_new" color="--red" x-small />
  <v-icon name="warning" color="--purple" small />
  <v-icon name="gesture" color="--blue" />
  <v-icon name="security" color="--green" large />
  <v-icon name="person" color="--orange" x-large />
`}>
```

![image](https://user-images.githubusercontent.com/9141017/72556723-37fade80-386d-11ea-9ae2-bf0bac85a94f.png)


<details>
<summary>Full example</summary>
<pre>
&#x3C;Preview mdxSource={&#x60;
&#x3C;v-icon name=&#x22;accessibility_new&#x22; color=&#x22;--red&#x22; x-small /&#x3E;
&#x3C;v-icon name=&#x22;warning&#x22; color=&#x22;--purple&#x22; small /&#x3E;
&#x3C;v-icon name=&#x22;gesture&#x22; color=&#x22;--blue&#x22; /&#x3E;
&#x3C;v-icon name=&#x22;security&#x22; color=&#x22;--green&#x22; large /&#x3E;
&#x3C;v-icon name=&#x22;person&#x22; color=&#x22;--orange&#x22; x-large /&#x3E;
&#x60;}&#x3E;
&#x9;&#x3C;Story name=&#x22;x-small&#x22; height=&#x22;50px&#x22;&#x3E;
&#x9;&#x9;{{
&#x9;&#x9;&#x9;components: { VIcon },
&#x9;&#x9;&#x9;template: &#x60;&#x3C;v-icon name=&#x22;accessibility_new&#x22; color=&#x22;--red&#x22; x-small /&#x3E;&#x60;
&#x9;&#x9;}}
&#x9;&#x3C;/Story&#x3E;
&#x9;&#x3C;Story name=&#x22;small&#x22; height=&#x22;50px&#x22;&#x3E;
&#x9;&#x9;{{
&#x9;&#x9;&#x9;components: { VIcon },
&#x9;&#x9;&#x9;template: &#x60;&#x3C;v-icon name=&#x22;warning&#x22; color=&#x22;--purple&#x22; small /&#x3E;&#x60;
&#x9;&#x9;}}
&#x9;&#x3C;/Story&#x3E;
&#x9;&#x3C;Story name=&#x22;default&#x22; height=&#x22;50px&#x22;&#x3E;
&#x9;&#x9;{{
&#x9;&#x9;&#x9;components: { VIcon },
&#x9;&#x9;&#x9;template: &#x60;&#x3C;v-icon name=&#x22;gesture&#x22; color=&#x22;--blue&#x22; /&#x3E;&#x60;
&#x9;&#x9;}}
&#x9;&#x3C;/Story&#x3E;
&#x9;&#x3C;Story name=&#x22;large&#x22; height=&#x22;50px&#x22;&#x3E;
&#x9;&#x9;{{
&#x9;&#x9;&#x9;components: { VIcon },
&#x9;&#x9;&#x9;template: &#x60;&#x3C;v-icon name=&#x22;security&#x22; color=&#x22;--green&#x22; large /&#x3E;&#x60;
&#x9;&#x9;}}
&#x9;&#x3C;/Story&#x3E;
&#x9;&#x3C;Story name=&#x22;x-large&#x22; height=&#x22;50px&#x22;&#x3E;
&#x9;&#x9;{{
&#x9;&#x9;&#x9;components: { VIcon },
&#x9;&#x9;&#x9;template: &#x60;&#x3C;v-icon name=&#x22;person&#x22; color=&#x22;--orange&#x22; x-large /&#x3E;&#x60;
&#x9;&#x9;}}
&#x9;&#x3C;/Story&#x3E;
&#x3C;/Preview&#x3E;
</pre>
</div>
</details>

**Comment by shilman** [comment]
@rijkvanzanten that's pretty sweet!! not what i had in mind, but effective! 💯

**Comment by kerryj89** [comment]
I'm Hamham on Discord and to clarify on what I want, I would just like plain HTML output for storybook-html.  It'd be cool if it could also generate the knob-affected preview.

**Comment by dannymcgee** [comment]
> You can use `mdxSource` on `<Preview>` as a temporary override. Not ideal, but provides the expected highlighted source code:
> ...

Forgive me for butting in here without doing a whole lot of research, but would this workaround be feasible to use with Angular? I thought I remembered reading somewhere that MDX is available now for Angular, but I can't remember where and can't find it now.

**Comment by shilman** [comment]
@dannymcgee  MDX has been available for all storybook supported frameworks from the start. Documentation is catching up with the code, but check the addon-docs README for angular and also examples/angular-cli in the storybook repo

**Comment by shilman** [comment]
Gadzooks!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-alpha.22 containing PR #10084 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Almost there. Next release will fix it 😉

**Comment by shilman** [comment]
Egads!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-alpha.24 containing PR #10089 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
¡Ay Caramba!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-alpha.28 containing PR #10184 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

**Comment by absalonv** [comment]
@shilman is there an example to just load the code inside the `template:` field when using angular components and mdx docs?

**Comment by shilman** [comment]
@absalonv i've seen one for vue `template:` but can't find it at the moment. it's just a regex.
