### ISSUE TITLE
Storybook/react v5 breaks flow checks

### ISSUE THREAD

**Issue by gergelyke** [storybookjs/storybook#7481]
**Describe the bug**
After updating to @storybook/react v5, flow type checks start to fail (timeout).

**To Reproduce**
https://github.com/uber-web/baseui/pull/1581

```
git clone && yarn && yarn
```

=>

```
Jul 17 15:03:15.005 [info] Creating a new Flow server
Jul 17 15:03:15.831 [error] Exception while trying to establish new connection over the socket. Closing connection: (Failure
Jul 17 15:03:15.831 [error]   "Server still initializing -> hangup. server_status=Server is initializing (parsed files 7000) watchman_status=Dfind file watcher is still initializing")
Jul 17 15:03:15.831 [error] backtrace:
Jul 17 15:03:15.831 [error] Raised at file "pervasives.ml", line 32, characters 17-33
Jul 17 15:03:15.831 [error] Called from file "src/monitor/socketAcceptor.ml", line 313, characters 36-89
Jul 17 15:03:15.831 [error] Called from file "src/core/lwt.ml", line 2080, characters 16-20
```

**Expected behavior**
Flow type check works.

**System:**
 - OS: MacOS and Ubuntu
 - Framework: react
 - Version: 5

**Comment by gergelyke** [comment]
Please let me know if you need more information for me / there is anything I can help with!

**Comment by kevliu** [comment]
@gergelyke Does the problem go away if you increase the memory limit for the Flow shared hash table by adding `sharedmemory.hash_table_pow=21` to the options block of your flowconfig?

**Comment by gergelyke** [comment]
> @gergelyke Does the problem go away if you increase the memory limit for the Flow shared hash table by adding `sharedmemory.hash_table_pow=21` to the options block of your flowconfig?

let me try that, thanks for getting back to me!

**Comment by gergelyke** [comment]
it seems like it solved it, thank you: https://github.com/uber-web/baseui/pull/1631
