### ISSUE TITLE
Is there a way to remove the body margin only when in a specific viewport?

### ISSUE THREAD

**Issue by steel** [storybookjs/storybook#7483]
When displayed in a responsive default viewport, I want to leave the default margin intact. But when the viewport is adjusted to say a mobile viewport, I'd like to remove the body margin to simulate how it's actually look on a device.

I can do it across the board in preview-head.html but would like more flexibility in how it's configured.

**Comment by ndelangen** [comment]
We're currently not exposing viewport change events on the channel.

We did a month ago 😄 

We could add these events back unto the channel, so you could use listen for them in a custom decorator and change the body styles based on the viewport.

Would you be interested in contributing?
This would be the place where an `api.emit()` would need to be added:
https://github.com/storybookjs/storybook/blob/next/addons/viewport/src/Tool.tsx#L147-L148

**Comment by kevinSuttle** [comment]
> I can do it across the board in preview-head.html 

Thank you for this!
