### ISSUE TITLE
No Scrollbar inside Storybook

### ISSUE THREAD

**Issue by w2kzzz** [storybookjs/storybook#7488]
**Describe the bug**
i'm not getting scrollbar on the render side of the storybook

**To Reproduce**
1. Load Storybook with content greater than the layout
2. Scrollbar won't show

**Expected behavior**
Scrollbar should appear if the content overflows the container

**Screenshots**
![storybook](https://user-images.githubusercontent.com/13698269/61538701-f85f5100-aa07-11e9-916e-5420bdd56b97.png)

![storybook2](https://user-images.githubusercontent.com/13698269/61538980-74f22f80-aa08-11e9-9902-e5bee3294506.png)

**Code snippets**
my config.js

`import { configure, addDecorator, addParameters } from '@storybook/angular';
import { withNotes } from '@storybook/addon-notes';
import etpTheme from './etpTheme';

addDecorator(withNotes);

addParameters({
  options: {
    theme: etpTheme
  }
});
`

import '../apps/portal-web/src/styles.scss';

const req = require.context('../', true, /.stories.ts$/);

function loadStories() {
  req.keys().forEach((filename) => req(filename));
}

configure(loadStories, module);

my etpTheme.js

`import { create } from '@storybook/theming';
import del_sec_rgb from '../apps/portal-web/src/assets/images/logos/del_sec_rgb.png';

export default create({
  base: 'dark',

  appContentBg: '#f5f5f5',
  layoutMargin: 10,
  fontBase: '"NotoSans-Light", "Muli", "Helvetica Neue", "Arial", sans-serif',

  brandTitle: 'Brand',
  brandUrl: 'https://www.brand.com',
  brandImage: del_sec_rgb
});`

my preview-head.html

`<link
  href="https://fonts.googleapis.com/icon?family=Material+Icons"
  rel="stylesheet"
/>
<link rel="stylesheet" href="assets/icons/icomoon-icons/style.css" />
<style>
  html,
  body {
    margin: 0;
    height: 100%;
    font-family: 'NotoSans-Light', 'Muli', 'Helvetica Neue', 'Arial', sans-serif;
  }
  storybook-dynamic-app-root {
    display: flex;
    height: 100%;
    padding: 15px;
  }
  storybook-dynamic-app-root > ng-component {
    margin: 0 auto;
  }
</style>
`

**System:**
 - OS: MacOS 10.14.5
 - Device: Macbook Pro 2017
 - Browser: Chrome
 - Framework: Angular
 - Version: 5.0.0

**Additional context**
not really sure if i'm missing configuration

**Comment by ndelangen** [comment]
@w2kzzz The scrollbar in the iframe should behave as configured on your OS/browser.

AFAIK we're not doing any styling of removal of the scrollbar there.

Whether the scrollbar is visible is configurable on MacOS.

**Comment by w2kzzz** [comment]
@ndelangen thanks for the response i think i made it work by changing the overflow inside my css, thanks a lot for the follow up.
