### ISSUE TITLE
Typescript template support

### ISSUE THREAD

**Issue by aloifolia** [storybookjs/storybook#7492]
**Is your feature request related to a problem? Please describe.**
Currently, in order to add Storybook to a project that uses Typescript, you first have to install Storybook (e.g. `npx -p @storybook/cli sb init --type react_native`). Afterwards you have to migrate the codebase [manually](https://storybook.js.org/docs/configurations/typescript-config/). This is much more tedious than it should be. 

**Describe the solution you'd like**
Ideally, the script would automatically detect the language that is used in a project. Alternatively, a second `--language ts/js` option would work.

Since the project is currently being migrated to Typescript, I am wondering whether, in the foreseeable future, there will be better Typescript support on the consumer side.

**Comment by shilman** [comment]
Mostly duplicate to #6342
