### ISSUE TITLE
Trying to load antd via less

### ISSUE THREAD

**Issue by asheinfeld** [storybookjs/storybook#7495]
**Bug Description**
I followed [This guide](https://ant.design/docs/react/use-with-create-react-app#Advanced-Guides) to set up React with antd and typescript. Then I added Storybook using [this tutorial](https://blog.crowdbotics.com/setup-a-react-app-with-typescript-storybook-and-crowdbotics/)

I have a small component like this:
```javascript
import * as React from "react";

import { Button } from "antd";

const MyButton: React.SFC<IButtonProps> = props => (
  <Button type="primary" onClick={props.onClick}>
    {props.children}
  </Button>
);
```

This component renders perfectly (loading the css from antd) when used inside React using `yarn start`, but when I run `yarn run storybook` none of the css loads.

I already tried adding the following into a `webpack.config.js` inside my `.storybook` folder, but it still doesn't load the styles from antd.

```javascript
const path = require('path');

module.exports = ({
  config
}) => {
  config.module.rules.push({
    test: [/\.less$/],
    use: [{
      loader: "style-loader"
    }, {
      loader: "css-loader"
    }, {
      loader: "less-loader",
      options: {
        javascriptEnabled: true
      }
    }]
  });

  return config
}
```

I'm using all the latest versions as of today for `antd`, `storybook` and `create-react-app`.

**Comment by ndelangen** [comment]
Use the `--debug-webpack` flag when starting storybook to view the full config storybook creates.

Then compare that with what your app is using. You're likely missing the `babel-plugin-import` thing.
