### ISSUE TITLE
Support for aXe / Puppeteer / storyshot / CI / Jest flow?

### ISSUE THREAD

**Issue by interactivellama** [storybookjs/storybook#7511]
**Is your feature request related to a problem? Please describe.**
No. Other than, trying to make the world a little more accessible! 😉 

**Describe the solution you'd like**
I've got code working with Storyshots, but the `addon-a11y` mentions CI integration in its roadmap and add-ons seem more focused on the Storybook UI and not on test suites. Storyshots seems to be focused on DOM and image snapshots--that is it has artifacts that are stored in git and diff'ed.

The workflow working today is `Storybook build CLI -> Jest -> Storyshots -> Puppeteer -> Jest expect() -> AxePuppeteer -> aXe`. Performance is more than twice (3 min vs 8 min) that of StoryShots + `jest-axe` which uses `jsDOM` on the 448 stories I'm testing in [Salesforce Lightning Design System for React](https://github.com/salesforce/design-system-react).

**Describe alternatives you've considered**
I've implemented `jest-axe` with Storybook, but it's too slow for the large scope of our project of implementing https://www.lightningdesignsystem.com/ .

**Are you able to assist bring the feature to reality?**
Yes, I'd love to contribute after corporate approval. That's primarily why I'm asking for some direction. Where would this feature live? I'm guessing it would be it's own add-on like `addon-storyshots-puppeteer` or be added into that add-on and linked to from the `addon-a11y`. `addon-storyshots-puppeteer` is a vague name. It describes the how and not the what it does. On a related note, is `storyshots` really `story-ci` in its purpose? My running code structure is very similar to `addon-storyshots-puppeteer`, it's almost like it got copied and pasted or something. 😄 

**Additional context**
Screenshot: Unfortunately, the color contrast in the terminal isn't very high in this screenshot.
![Screen Shot 2019-07-20 at 2 19 30 PM](https://user-images.githubusercontent.com/1290832/61583741-6e8fb080-aaf9-11e9-9c15-bbbea5e1664e.png)

Related links
* #7103 
* https://discordapp.com/channels/486522875931656193/580149748225409024
* https://gist.github.com/donaldpipowitch/898854e2f71f64d0d91e199537b3ee1a

**Comment by shilman** [comment]
@interactivellama This sounds awesome. 💯💯💯 

I think it would be its own package like `addon-storyshots-puppeteer`, as you suggest. `addon-a11y-ci` to start? It would be good if this new package and `addon-a11y` could share configuration, etc.

And maybe we can refactor & rename the way CI services work as part of a 6.0 breaking change.

**Comment by shilman** [comment]
Hey @interactivellama anything I can do to help move this forward?

**Comment by interactivellama** [comment]
No, I was out-of-the-office right after I posted two weeks, and now I'm working it into my release planning. It's been on the roadmap on the add-on's readme for a while (2016). Are you targeting any certain release?

Do you all have any contributing license agreement (CLA)? I see that it's all MIT, so probably not.

**Comment by shilman** [comment]
@interactivellama Once there's a PR we'll figure out which release to slot it into. We're finishing up 5.2 right now. 5.3 will probably go out late Sept / early Oct, and so forth. Happy to coordinate with you once you have a better sense of your schedule. We don't have a CLA AFAIK!

**Comment by Hypnosphi** [comment]
I think it can be actually a part of `addon-storyshots-puppeteer`, and use [jest-puppeteer-axe](https://github.com/WordPress/gutenberg/tree/master/packages/jest-puppeteer-axe) in test body

**Comment by Hypnosphi** [comment]
Implemented in #8934
