### ISSUE TITLE
Core: Preserve component ("kind") order on HMR

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#7517]
When you edit a story name, it is possible for that story (and its component) to change position in the treeview if there is no story sort function.

This is due to the way HMR works. By default, Storybook sorts by load order, but this load order chan change with edits.

I think we to fix this problem as follows:
- Keep an ordering on all "kinds" that we've seen
- Sort on that kind order by default, load order within a kind

**Comment by vkrol** [comment]
Probably it is fixed in `5.2.0-alpha.31` https://github.com/storybookjs/storybook/issues/6439#issuecomment-506164318.

**Comment by shilman** [comment]
I think this was fixed in #9482
