### ISSUE TITLE
Set focus on iframe for keyboard usage

### ISSUE THREAD

**Issue by soundstep** [storybookjs/storybook#7521]
**Is your feature request related to a problem? Please describe.**
Working on components that use keyboard rather than mouse, I need to click on the iframe to retrieve key events before using the keyboard. I'd like this to be automatic so I don't have to click on the iframe every time.

**Describe the solution you'd like**
I'd like to set the focus myself on the iframe, or tell storybook to do so.
I'd like to add a class from my story:
```
document.body.classList.add('with-focus');
```
And have storybook do (or add a script to the storybook main page):
```
const bodyWithFocus = document.querySelector('#storybook-preview-iframe').contentDocument.querySelector('body.with-focus');
if (bodyWithFocus) {
    bodyWithFocus.focus();
}
```

**Describe alternatives you've considered**
Not sure I can think to an easier way than the one described above.

**Are you able to assist bring the feature to reality?**
Possibly, I may have the time to do a PR, but I'd like to discuss the request before.

**Additional context**
NA

**Comment by schickling** [comment]
I'm facing the same problem. Has anyone found a solution/workaround for this?
