### ISSUE TITLE
Unable to connect to redux extension tools

### ISSUE THREAD

**Issue by gptt916** [storybookjs/storybook#7525]
**Describe the bug**
I have several components that use the redux store, functionally they work as intended. However I am unable to connect to the redux devtools extension (https://github.com/zalmoxisus/redux-devtools-extension) when using both basic (window.__REDUX) and advanced (npm package) setups for the extension in my store configuration.

https://github.com/storybookjs/storybook/search?q=redux+devtools&type=Commits

**To Reproduce**
1. Set up component with redux store
2. Set up redux devtools extension in browser and code
3. Extension panel in browser unable to connect

**Expected behavior**
Extension able to connect

**Screenshots**
![image](https://user-images.githubusercontent.com/20601623/61652840-e50de900-ac86-11e9-8ab0-953ad0118e58.png)
![image](https://user-images.githubusercontent.com/20601623/61652863-efc87e00-ac86-11e9-8c85-a0a5773eb313.png)

**System:**
 - OS: [MacOS]
 - Device: [Macbook Pro 2018]
 - Browser: [Chrome]
 - Framework: [react]
 - Addons: [Knobs]
 - Version: [5.1.9]

**Additional context**
https://github.com/storybookjs/storybook/search?q=redux+devtools&type=Commits
I did a search and see there were commits regarding support for redux devtools, so this must have been brought up before? Maybe I missed a step in the configuration somewhere? Help appreciated!.

**Comment by kroeder** [comment]
Can you try to open your story in a separate window? (use the control in the upper right in storybook)

I got the same problem using augury for angular.
Its because storybooks preview is an iframe and augury can't detect angular inside that iframe. Chances are redux behaves the same
