### ISSUE TITLE
@storybook/addon-storyshots Add a way to disable animations.

### ISSUE THREAD

**Issue by EdenTurgeman** [storybookjs/storybook#7530]
When testing the storybook, some of our pages contain loading bars and Circular progress components.
These cannot be tested because even with a delay, results are inconsistent because of many variables, puppeteer seems to allow disabling all animations but I haven't found anyone using this addon that managed to pull it off. Please add a way to disable animations as it is essential to visual testing.

**Comment by EdenTurgeman** [comment]
Not inactive :)

**Comment by svewag** [comment]
IMHO this is not an issue or feature in storyshots. Animations can be done by CSS oder JavaScript and you can't disable this in a way that your snapshots makes sense from the viewpoint of storyshots.

Think about a property in your component that will disable the animation.

**Comment by rj-wowza** [comment]
so we should add a prop to each component to disable animations? imagine defending that in a PR lmao
