### ISSUE TITLE
React Native, ondevice-knobs select fails without default

### ISSUE THREAD

**Issue by RWOverdijk** [storybookjs/storybook#7532]
**Describe the bug**

When using ondevice-knobs: select() but neglecting to provide a default the app throws:

> cannot read property of label undefined

Upon investigation I found and fixed the issue.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System:**
 - OS: iOS/Android
 - Device: Mobile
 - Framework: React Native
 - Version: master (@5.2.0-beta.6)

**Comment by shilman** [comment]
Crikey!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-beta.7 containing PR #7533 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
