### ISSUE TITLE
@storybook/addon-contexts: Style story background based on context value

### ISSUE THREAD

**Issue by benjamingeorge** [storybookjs/storybook#7541]
"@storybook/react": "^5.2.0-beta.7",
"@storybook/addon-contexts": "^5.2.0-beta.7",

I'm using this addon-contexts to be able to switch between Styled-components themes.  When the theme value in context switches, i want to be able to change the color of the story background (essentially styling the `<body class="sb-show-main">` inside the iframe).  

Is it possible to dynamically change the iframe body background color based on context?

Having to use a decorator to wrap stories with a SC ThemeConsumer and div seems hacky and causes issues with story-source and the new addon-docs.

**Comment by leoyli** [comment]
Nope, this addon does not allow you directly do that.  But it's is possible to "hook" such logic as a context by writing a component to manipulate the DOM. Please do it with caution.

Instead, I would recommend you to create a helper component like:

(A) create a wrapper box
```jsx
const BackgroundBoxBase = (color, ...props) => <div {...props} />;
const BackgroundBox = styled(BackgroundBoxBase)`
  background-color; ${(({ color }) => color};
  width: 100vw;
  height: 100vh;
```

And put `BackgroundBox` as one of the context, which wrapping all of your component in a box with background.

(B) use [`createGlobalStyle`](https://www.styled-components.com/docs/api#createglobalstyle)

There are some minor caveats, but you can "inject" styles to the `body` tag.  And you can create a component out of this special helper and pass a one of the context. I will leave this for your own exploration. :)

Hope that helped you.  I will close this issue, but feel free to reply here if you find there are something we could discuss :)
