### ISSUE TITLE
Make Storybook compatible with Parcel.js

### ISSUE THREAD

**Issue by jamesguan** [storybookjs/storybook#7550]
**Is your feature request related to a problem? Please describe.**
I really want Storybook to work with parceljs bundler
**Describe the solution you'd like**
Storybook works with parceljs bundler
**Describe alternatives you've considered**
Storybook is the best and parcel-story does not compare

**Are you able to assist bring the feature to reality?**
no | yes, I can...
maybe
**Additional context**
https://parceljs.org/

**Comment by shilman** [comment]
Have you looked at this? https://github.com/storybookjs/storybook/tree/next/examples/standalone-preview

**Comment by jamesguan** [comment]
@shilman I tried your example, but nothing rendering. No console errors but nothing rendering either.

**Comment by shilman** [comment]
Yeah the enclosing UI is still driven with webpack, but the "preview" portion which is the user code is run with parcel.

If you want to convert all of storybook to parcel, I don't think that will happen any time soon.

**Comment by danieltroger** [comment]
Also using parcel.js and would like to use storybook with it. FYI https://github.com/storybookjs/storybook/tree/next/examples/standalone-preview 404s
