### ISSUE TITLE
storybook build contacts recursive "docs" folder

### ISSUE THREAD

**Issue by SilencerWeb** [storybookjs/storybook#7551]
**Describe the bug**
My storybook build is 238MB, it has tons of "docs" folders inside each other, it's like a ZIP bomb.

**To Reproduce**
1. `git clone git@github.com:SilencerWeb/storybook-build-bug.git`
2. `cd storybook-build-bug && npm install`
3. `npm run build`
4. Open folder "public" and check "storybook" size

**Expected behavior**
There should be only one "docs" folder?

**System:**
`error Command "sb" not found.`
macOS Mojave 10.14.5

**Comment by shilman** [comment]
What happens when you change this:

```
    "build:storybook": "NODE_ENV=production build-storybook --static-dir public,static --output-dir public/storybook",
```

To this:

```
    "build:storybook": "NODE_ENV=production build-storybook --static-dir static --output-dir public/storybook",
```

**Comment by SilencerWeb** [comment]
@shilman, yea, that's what I thought. Now the size is 5.3MB and no "docs" folder. In my case, build version somehow works okay without this static folder, but in development I definitely need it. Anyway, thanks a lot!
