### ISSUE TITLE
design-assets missing from ADDONS_SUPPORT

### ISSUE THREAD

**Issue by pvinis** [storybookjs/storybook#7556]
**Describe the bug**
The table [here](https://github.com/storybookjs/storybook/blob/next/ADDONS_SUPPORT.md) is missing the design-assets [addon](https://github.com/storybookjs/storybook/tree/next/addons/design-assets)

**Expected behavior**
To be there.

**Comment by ndelangen** [comment]
@pvinis would you be able to open a PR?

**Comment by pvinis** [comment]
I didn't do it because I was not sure of that's supported, but I think I can do it now

**Comment by pvinis** [comment]
thanks @ndelangen :)
