### ISSUE TITLE
Ability to set window's width like in DevTools Device Toolbar

### ISSUE THREAD

**Issue by SilencerWeb** [storybookjs/storybook#7560]
**Is your feature request related to a problem? Please describe.**
Right now it is pretty comfortable to work on adaptive of some block inside the storybook but it's still not enough.

**Describe the solution you'd like**
Would be awesome to have the ability to set window's width like in DevTools Device Toolbar. 

**Describe alternatives you've considered**
Right now I still have to use DevTools Device Toolbar sometimes because I need to be sure in window's width.

Here is how it works in my head:
1. On one of these sides appear button for setting window's width — http://prntscr.com/ojw91w
2. When you click on it, modal shows up with input for entering a number
3. You enter the number, press enter and window resizes.
Also, it would be useful to have a shortcut to call this window.
And I think the window shouldn't be fixed, this feature should only resize the window to specific width but the user should still be able to resize it with the mouse.

**Are you able to assist bring the feature to reality?**
No :(

P.S. Another feature — show window's width on it's resize, how Chrome does when DevTools are open and you are resizing the window.

**Comment by shilman** [comment]
Have you tried the Viewport addon? https://github.com/storybookjs/storybook/tree/next/addons/viewport

**Comment by SilencerWeb** [comment]
@shilman, uuu, nice, I'll check it out when I have time, thanks!
