### ISSUE TITLE
Select knob with array options does not correctly set the select list to the default

### ISSUE THREAD

**Issue by elliotlarson** [storybookjs/storybook#7569]
**Describe the bug**

When using a select knob with arrays as option values, the default value is not getting set properly on the select list.  The code is comparing two arrays with ===, which is always false.  

**To Reproduce**

Create a select knob with option values that are arrays.  Set the default to an option that is not the first option.

**Expected behavior**

The default option should be selected.

**Code snippets**

My specific use case was:

```javascript
    const panelSelect = select(
      "Panels",
      {
        "39.37 x 65.63": [39.37, 65.63],
        "39.37 x 78.5": [39.37, 78.5],
        "65.63 x 39.37": [65.63, 39.37],
        "78.5 x 39.37": [78.5, 39.37],
      },
      [65.63, 39.37],
    );
```

When loading the story, the select knob is not defaulted to the correct option: "65.63 x 39.37".

**System:**

Environment Info:

```text
  System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
  Binaries:
    Node: 8.15.0 - ~/.nvm/versions/node/v8.15.0/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v8.15.0/bin/npm
  Browsers:
    Chrome: 75.0.3770.142
    Firefox: 67.0.4
    Safari: 12.1.1
```

**Comment by shilman** [comment]
ZOMG!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-beta.12 containing PR #7568 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
