### ISSUE TITLE
Core: Rename `load` to `configure`

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#7570]
To support Component Story Format (CSF) in Storybook 5.2 we added a `load` function to all frameworks. This load function uses the `configure` function internally but accepts more arguments (a `require.context` `req` or an array of them) for convenience. It also processes CSF exports from those `reqs`, or allows you to pass a loader function that returns an array of exports.

During CSF feedback, it was pointed out that `load` is basically a superset of `configure` and we don't need to add a new API. This issue is to address that suggestion.

- [x] Rename `load` to `configure`
- [x] Update exports so the new `configure` is exported
- [x] If user passes a configure function (i.e. they are using the old API), be really strict about the return values, and issue a warning with instructions if the values don't match what we expect (either void or an array of objects that contain a `default` export).
- [ ] Update docs and Technical Preview doc
- [ ] Export a deprecated `load`, just for people who are using the beta and don't want to be broken

**Comment by tmeasday** [comment]
> Export a deprecated load, just for people who are using the beta and don't want to be broken

How long will this stick around for?

**Comment by shilman** [comment]
Ta-da!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-beta.13 containing PR #7576 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
