### ISSUE TITLE
addon-info not working properly

### ISSUE THREAD

**Issue by rahulpsd18** [storybookjs/storybook#7575]
**Describe the bug**
Followed the readme to add addon-info to my storybook but the info created is wrong.
In my story source, instead of showing the JSX I have provided to the story, the following is shown:
```jsx
<ReactDecorator story={<Tiles />} onMount={anonymous} onUnMount={anonymous} />
```
I am using typescript so I know PropTypes won't work out of the box and needs to be configured but the story source should render fine.

**To Reproduce**
1. Followed readme to install addon-info
2. Added it to config file
3. Passed `info` parameter to my story
4. Source story not as expected
5. Then added `withInfo` as 1st decorator on my story
6. No change in Source Story 

**Expected behavior**
My Story Source should be render instead of `<ReactDecorator ... />`

**Screenshots**
![CaptureIssue](https://user-images.githubusercontent.com/14837582/61951970-3512e580-afd0-11e9-88c7-2f257c764970.PNG)

**Code snippets**
```jsx
storiesOf('RibbonBox', module)
    .addDecorator(withInfo)
    .addDecorator(withKnobs)
    .add('Default', () => (
        <Tiles>
          <Tiles.Card>
            <Tiles.Details iconSize="2x" iconName="id-badge" text="Lorem Ipsum" />
          </Tiles.Card>
          <Tiles.Card>
            <Tiles.Details iconSize="2x" iconName="cog" text="Dolor Sit Amet" />
          </Tiles.Card>
        </Tiles>
    ), {
        info: { text: 'Description' }
    }
})
```

**System:**
```
Environment Info:

  System:
    OS: Windows 7
    CPU: (4) x64 Intel(R) Core(TM) i5-4210M CPU @ 2.60GHz
  Binaries:
    Node: 10.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.15.2 - C:\Users\rahulpsd18\AppData\Roaming\npm\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
```

**Additional context**
Regrading PropTypes: I followed the issue #1519 and integrated [react-docgen-typescript-loader](https://github.com/strothj/react-docgen-typescript-loader) to add Prop Types automatically from my Typescript interfaces but no changes were seen in the storybook. It still showed the props: `story`, `onMount` and `onUnMount` as seen in the screenshot attached.

**Comment by shilman** [comment]
FYI `addon-info` is being superceded by `addon-docs`, which fixes a bunch of bugs and is easier to maintain. It’s reached release candidate (RC) status and will be properly released soon. Please give it a try! https://medium.com/storybookjs/storybook-docspage-e185bc3622bf

@rahulpsd18 @github-actions @stale
