### ISSUE TITLE
v5 URL format: default to first story if no path or storyId is included

### ISSUE THREAD

**Issue by kevinSuttle** [storybookjs/storybook#7582]
**Is your feature request related to a problem? Please describe.**
Having to include `--*` at the end of Storybook URLs is a bit of a task. Seems avoidable. 

**Describe the solution you'd like**
1. If the URL doesn't have --* or $[storyID} at the end of it, the router would redirect to the first story listed.

2. (Maybe related?) If the URL doesn't have 
- a `/` 
- or `?` 
- or `path`

redirect to the first story

e.g. https://monorepo-git-next.storybook.now.sh/examples/official-storybook - nothing happens
https://monorepo-git-next.storybook.now.sh/examples/official-storybook/ - redirect happens

**Describe alternatives you've considered**
Always including `/`, `?`, `path`, and `--*` at the end of Storybook URLs.

**Are you able to assist bring the feature to reality?**
I can

**Additional context**
Example: 

https://monorepo-dzdv58z2b.now.sh/examples/official-storybook/?path=/story/docs-docspage--with-subtitle - works

If you remove the --${storyId} at the end, the Story group is selected on the left, but there is no individual story selected or rendered on the Canvas

Try: https://monorepo-dzdv58z2b.now.sh/examples/official-storybook/?path=/story/docs-docspage

<img width="1373" alt="Image 2019-07-26 at 3 45 54 PM" src="https://user-images.githubusercontent.com/95672/61978198-9f228f00-afbe-11e9-832b-8cca9a81bda2.png">

**Comment by macrozone** [comment]
@kevinSuttle would also be great if the urls would not be case-sensitive, see https://github.com/storybookjs/storybook/issues/8500

**Comment by shilman** [comment]
Egads!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-alpha.27 containing PR #7648 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by kevinSuttle** [comment]
Thank you!
