### ISSUE TITLE
StoryShots/Storyshots-Puppeteer is inconsistent and buggy with docker 

### ISSUE THREAD

**Issue by EdenTurgeman** [storybookjs/storybook#7587]
**Describe the bug**
We are trying to use Storyshots with puppeteer to take snapshots of our storybook and integrate it to out ci Jenkins pipeline, but are running into many problems when using it with docker, specifically these issues :
Screenshots are inconsistent, primarily each time we run the tests with the exact same project and storybook hosted locally, we keep getting these errors related to mismatched resolution and diffs show all pages are slightly misaligned to the right.

![image](https://user-images.githubusercontent.com/12447231/62012246-9089d280-b18c-11e9-82ac-0337e87c133d.png)

We have 107 stories and somehow this is what happens when we run in docker

![image](https://user-images.githubusercontent.com/12447231/62012268-bd3dea00-b18c-11e9-8d0c-c8a954899e04.png)
107 Fails + 107 Passes ?

**To Reproduce**
My base chromium docker image, the rest is copying the project and running `yarn test`

```dockerfile
FROM node:11.7.0-alpine
ENV CHROME_BIN="/usr/bin/chromium-browser"
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD="true"

RUN apk update && apk upgrade && \
    echo @edge http://nl.alpinelinux.org/alpine/edge/community >> /etc/apk/repositories && \
    echo @edge http://nl.alpinelinux.org/alpine/edge/main >> /etc/apk/repositories && \
    apk add --no-cache \
      chromium@edge=~73.0.3683.103 \
      nss@edge \
      freetype@edge \
      freetype-dev@edge \
      harfbuzz@edge \
      ttf-freefont@edge

RUN addgroup -S pptruser && adduser -S -g pptruser pptruser \
    && mkdir -p /home/pptruser/Downloads /app \
    && chown -R pptruser:pptruser /home/pptruser \
    && chown -R pptruser:pptruser /app
```
The docker image based on it.  
Copies the storybook and runs the tests.
```dockerfile
FROM node:11.7.0-puppeteer

WORKDIR /src
COPY --from= /src       .
COPY .                      storybook
RUN yarn install:ci:dev
CMD cd storybook && yarn test
```

imageSnapshots.js
```javascript
import initStoryshots from '@storybook/addon-storyshots';
import { imageSnapshot } from '@storybook/addon-storyshots-puppeteer';

require('babel-plugin-require-context-hook/register')();

const waitBeforeSnapshotTime = 400;

// Hide all elements with classes containing these phrases
const ignoredElementsSelectors = ['MuiCircularProgress', 'MuiLinearProgress'];

const disableAnimationElements = ignoredElementsSelectors => {
  const animationSelectors = ignoredElementsSelectors.map(animationClass => `[class*='${animationClass}']`);
  const animatedPageElements = document.querySelectorAll(animationSelectors);

  animatedPageElements.forEach(pageElement => {
    pageElement.style.visibility = 'hidden';
  });
};

const storybookUrl = 'http://app-storybook:7071/';

const storiesToTestRegex = '^((?!.*?(Sketch|IFrame)).)*$';

const beforeScreenshot = page =>
  new Promise(resolve =>
    page
      .evaluate(disableAnimationElements, ignoredElementsSelectors)
      .then(() => page.setViewport({ width: 1920, height: 1080 }))
      .then(() => setTimeout(resolve, waitBeforeSnapshotTime)),
  );

const customizePage = page => page.setViewport({ width: 1920, height: 1080 });


initStoryshots({
  framework: 'react',
  suite: 'Image Storyshots',
  storyKindRegex: storiesToTestRegex,
  test: imageSnapshot({
    storybookUrl,
    beforeScreenshot,
    customizePage,
    chromeExecutablePath: process.env.CHROME_BIN,
  }),
});

```

**Expected behavior**
The screenshots should consistent with the local ones especially since I only install puppeteer with addon-storyshots-puppeteer so there is no version mismatch.

The documentation does not make it clear that there might be differences between os's and that results might be inconsistent. 

Currently, for me, it is broken and I am trying super hard to make it work and to understand most the process required for it to work.

Thank you for reading my issue, I'm really hoping for a response and hope this will be helpful for others. :)

**Comment by EdenTurgeman** [comment]
This issue is still relevant. Would love to get a reply and looking into my case.

**Comment by B3Kay** [comment]
I also got this problem. It renders different snapshots between computers.

**Comment by meeech** [comment]
anyone find a solution yet? i've started down the path of dockerizing the snapshot creation (with goal of images being consistent between creation and pipeline testing), but this ticket makes me wonder if I'm going in the wrong direction?

**Comment by EdenTurgeman** [comment]
@meeech Hey we've done the same here for a little while.. doesn't seem like there is a better option for now, would love to know why this is happening.

**Comment by bohdanbirdie** [comment]
I wonder if anyone got this working properly

**Comment by petermikitsh** [comment]
It **is** possible to get consistent screenshots across environments. Here's how:

I ran into this issue and followed the strategy outlined in `storybook-addon-image-snapshots` (https://github.com/spring-media/storybook-addon-image-snapshots#testing-with-a-local-running-storybook-server). Two general principles I picked up:

- Generate your baseline snapshots and test snapshots using the same docker image. I've had success with `browserless/chrome`. You can mount your built storybook like so using `-v`.
- Always create snapshots against a built storybook (<ins>not</ins> when running `start-storybook`).

```
docker run -d --rm \
  -p 9222:3000 \
  -e "CONNECTION_TIMEOUT=600000" \
  -v $STORYBOOK_DIR/dist:/opt/storybook-static \
  browserless/chrome
```

Then, setup your tests with a custom puppeteer browser. The puppeteer driver will use Chrome from the docker container (above) exposed on port 9222. 

<details>
  <summary>Test Setup: storyshots.test.js</summary>

  ```js
  import initStoryshots from '@storybook/addon-storyshots';
  import { imageSnapshot } from '@storybook/addon-storyshots-puppeteer';
  import puppeteer from 'puppeteer';

  const HOST_IP = process.env.HOST_IP;
  let browser;

  const testFn = imageSnapshot({
    storybookUrl: 'file:///opt/storybook-static',
    getCustomBrowser: async () => {
      browser = await puppeteer.connect({
        browserURL: (() => {
          // For CI env's: If running in docker inside docker, you'll need the IP address of the host
          if (HOST_IP) {
            return `http://${HOST_IP}:9222`;
          }
          return 'http://localhost:9222';
        })(),
      });
      return browser;
    },
    beforeScreenshot: async (page, { context: { kind, story }, url }) => {
      await page.evaluateHandle('document.fonts.ready');
      await page.setViewport({ deviceScaleFactor: 2, width: 800, height: 600 });
    },
    getScreenshotOptions: ({ context, url }) => {
      return {
        encoding: 'base64',
        fullPage: false,
      };
    },
  });

  // Override 'afterAll' so jest doesn't hang
  testFn.afterAll = () => {
    if (browser) {
      browser.close();
    }
  };

  initStoryshots({
    test: testFn,
  });
  ```
</details>


You'll probably want 2 separate scripts: one for updating snapshots, the other for testing.

<details>
  <summary>snapshots.sh</summary>

  ```sh
  DOCKER_ID=$(docker run -d --rm \
    -p 9222:3000 \
    -e "CONNECTION_TIMEOUT=600000" \
    -v $STORYBOOK_DIR/dist:/opt/storybook-static \
    browserless/chrome)

  npx --no-install jest --useStderr --update-snapshot

  docker kill $DOCKER_ID
  ```
</details>

<details>
  <summary>test.sh</summary>

  ```sh
  DOCKER_ID=$(docker run -d --rm \
    -p 9222:3000 \
    -e "CONNECTION_TIMEOUT=600000" \
    -v $STORYBOOK_DIR/dist:/opt/storybook-static \
    browserless/chrome)

  if [[ "$CI" ]]; then
    DOCKER_HOST_IP=$(/sbin/ip route|awk '/default/ { print $3 }')
  fi

  HOST_IP=$DOCKER_HOST_IP npx --no-install jest --useStderr
  docker kill $DOCKER_ID
  ```
</details>

**Comment by steinroe** [comment]
HI @petermikitsh 

thanks for your guide - really helpful! However, I am getting `Error when connecting to file:///opt/storybook-static/iframe.html?id=avatar--empty-prop, did you start or build the storybook first? A storybook instance should be running or a static version should be built when using puppeteer test feature.` although using the exact same config as you did, just changed the docker run to 

```
DOCKER_ID=$(docker run -d --rm \
  -p 9222:3000 \
  -e "CONNECTION_TIMEOUT=600000" \
  -v "$(pwd)/storybook-static/:/opt/storybook-static" \
  browserless/chrome)

yarn test --useStderr --update-snapshot

docker kill $DOCKER_ID
```

any ideas why this may happen?

**Comment by petermikitsh** [comment]
@steinroe Could you make a repro repo? Happy to take a look, but from the error message alone, it's hard to say for certain.

**Comment by steinroe** [comment]
@petermikitsh that would be great. You can find a repro repo here: https://github.com/steinroe/storyshots-issue

Thank you!

**Comment by cgat** [comment]
Just in case anyone else is hung up on this, I also had to add the `ALLOW_FILE_PROTOCOL=true` env variable to the docker image running browserless/chrome. The latest version of puppeteer won't run `file` URLs without it.

**Comment by naomiaro** [comment]
I've got this setup with tsdx now, but I'm still getting blank screenshots returned. Anyone else have this issue?

**Comment by naomiaro** [comment]
Found that my issue was probably do to this:

From
https://storybook.js.org/addons/@storybook/addon-storyshots

Testing stories that rely on addon-added decorators
If you have stories in your Storybook that can only render inside a decorator (for instance the [apollo-storybook-decorator](https://github.com/abhiaiyer91/apollo-storybook-decorator)), you'll need to ensure those decorators are applied in Storyshots.

If you export those decorators from your .storybook/preview.js then Storyshots will apply those decorators for you in the same way that Storybook does. However if the addon automatically adds the decorator for you (which is a new feature in Storybook 6.0), you will find the decorator does not get added in Storyshots. This is a limitation in Storyshots currently.

To ensure such decorators get added, export them from .storybook/preview.js:

```
import addonDecorator from 'some-addon';

export const decorators = [addonDecorator];
```

**Comment by sag1v** [comment]
> Always create snapshots against a built storybook (not when running start-storybook)

@petermikitsh Interesting, why do you think its important to get consistent images?
