### ISSUE TITLE
@storybook/addon-storyshots-puppeteer@5.1.9 dependency locked on 5.1.0-rc.0 version

### ISSUE THREAD

**Issue by 1oglop1** [storybookjs/storybook#7588]
Hi,
I'm unable to install `@storybook/addon-storyshots-puppeteer@5.1.9` due to its version lock. 
I noticed @shilman pushed a new version in `next` branch just an hour ago.

**Comment by shilman** [comment]
I see the bad dep here: https://github.com/storybookjs/storybook/blob/master/addons/storyshots/storyshots-puppeteer/package.json#L33

I'll fix it in the next few hours when I do a release. Thanks for letting me know.

**Comment by shilman** [comment]
Looks like I fixed this
