### ISSUE TITLE
There is a bug in CoreJSUpgradeWebpackPlugin

### ISSUE THREAD

**Issue by vipcxj** [storybookjs/storybook#7591]
This plugin did not deal with the module like `node_modules/XXX/node_modules/@babel/runtime/core-js/YYY`.
Add 
```
if (originalRequest.match(/@babel\/runtime\/core-js/)) {
    return;
}
```
after
```
if (originalRequest.startsWith('./') || originalRequest.startsWith('../')) {
    return;
}
```
fix it.
However, there is no repo of `CoreJSUpgradeWebpackPlugin` on github. So I can't submit a pull request.
And with full control webpack mode, I cannot recognize the plugin, So I have no workaround with `storybook`. Please fix it.

**Comment by shilman** [comment]
@vipcxj https://github.com/ndelangen/corejs-upgrade-webpack-plugin

**Comment by vipcxj** [comment]
@shilman The fix not work at all.
For example:
```
resource.context = '/path/to/project/node_modules/dva-loading/lib'
resource.request = '@babel/runtime/core-js/object/keys'
resource.userRequest = undefined
```
This will cause an Error be throwed.
I am not very familiar with webpack plugin. So my fix may not cover all the case. I think the key is the latest version of `@babel/runtime` has dropped all core-js package. However the regex `/core-js/` match the path of `@babel/runtime/core-js` too, This should not be a design behavior. We should let it not touched.
