### ISSUE TITLE
CSF documentation

### ISSUE THREAD

**Issue by affanshahid** [storybookjs/storybook#7603]
Where can I find documentation for the new CSF feature?

**Comment by shilman** [comment]
Here are the docs so far:

https://github.com/storybookjs/storybook/blob/next/docs/src/pages/basics/writing-stories/index.md

https://github.com/storybookjs/storybook/blob/next/docs/src/pages/formats/component-story-format/index.md

**Comment by shilman** [comment]
Olé!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-rc.10 containing PR #8030 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

**Comment by pvinis** [comment]
How would the decorators work with this? just a regular component?

**Comment by shilman** [comment]
@pvinis Works similar to `storiesOf` if you're familiar with that:

```js
export default {
  title: 'blah'
  decorators: [d1, d2, ...]
}
export const story1 = () => 
story1.story = { 
  decorators: [d3, d4, ...]
}
```

Where `d*` are regular storybook decorators, e.g. for `react`:

```js
const d1 = (storyFn) => <b>{storyFn()}</b>
```
