### ISSUE TITLE
[CSF/MDX] Auto-generated code snippet flexibility 

### ISSUE THREAD

**Issue by brennj** [storybookjs/storybook#7607]
**Is your feature request related to a problem? Please describe.**

From the [technical preview where I added this comment](https://docs.google.com/a/visma.com/document/d/1un6YX7xDKEKl5-MVb-egnOYN8dynb5Hf7mq0hipk8JE/edit?disco=AAAADPXQZA4) I would like to see for the following code snippet:

```jsx
import { action } from '@storybook/addon-actions';
import { Button } from '@storybook/react/demo';
import { Story, Meta } from '@storybook/addon-docs/blocks';

<Meta title='MDX|Button' component={Button} />


# Hello Docs

Welcome to the future of Storybook!

<Story name="hello">
  <Button onClick={action('clicked')}>Hello button!</Button>
</Story>

<Story name="with emoji">
  <Button onClick={action('clicked')}>🤘🚀💯</Button>
</Story>
```

To have the same code-snippet preview as:

![](https://i.imgur.com/g4nt6kz.png)

If it was also possible to have a prop to auto-show the code snippet it would also be amazing. :)

Possibly too, I would love to be able to edit this codesnippet and play around with it, and cross referencing the props table to code it to what I need live in the storybook browser itself. But thats a big ask 😄

**Comment by shilman** [comment]
Hey @brennj, still documenting everything but I think it's already there. Try:

```jsx
import { action } from '@storybook/addon-actions';
import { Button } from '@storybook/react/demo';
import { Story, Meta, Preview } from '@storybook/addon-docs/blocks';

<Preview withSource="open">
  <Story name="hello">
    <Button onClick={action('clicked')}>Hello button!</Button>
  </Story>
</Preview>
```

As for in-place editing, we've got our best guys on it! 😄 

https://github.com/storybookjs/storybook/issues/6642

**Comment by brennj** [comment]
<3 <3 <3
