### ISSUE TITLE
[Angular] Storyshots 5.1.9: Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by rfreydi** [storybookjs/storybook#7620]
I reopen my previous issue which is still present :

https://github.com/storybookjs/storybook/issues/6490

I tried to modify node_modules/@storybook/addon-storyshots/dist/api/index.js : 
```
// before
if (desc.get || desc.set)
// after
if (desc && (desc.get || desc.set))
```
But now I'm getting an error related to config : 
```
.storybook/config.js:136
    import { addParameters, configure } from '@storybook/angular';
           ^

    SyntaxError: Unexpected token {
```

**Comment by jusefb** [comment]
I am having the same issue

**Comment by whjvenyl** [comment]
bump
