### ISSUE TITLE
CLI: `sb info` should print out package info

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#7621]
#6937 introduced `sb info` to print out environment info, and #7225 added that to the default issue template as the way to give context for the issue. 

In addition to what it already does, `sb info` should print out `@storybook/*` package information, (...and maybe also `babel`/`webpack`-related packages too?)

As a workaround we could update the issue template to instruct people to paste this info manually, but it's probably better if we control the format!

See https://github.com/storybookjs/storybook/issues/7619#issuecomment-516326549 for an example.

**Comment by shilman** [comment]
@jamesgeorge007 Any interest in following up on this?

**Comment by jamesgeorge007** [comment]
> @jamesgeorge007 Any interest in following up on this?

sure :clap:

**Comment by shilman** [comment]
Awesome. Love it! 💯

**Comment by shilman** [comment]
Son of a gun!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-beta.19 containing PR #7624 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

**Comment by shilman** [comment]
@jamesgeorge007 Doesn't seem to work:

```
Environment Info:

  System:
    OS: macOS 10.14.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 8.16.0 - /usr/local/opt/node@8/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/opt/node@8/bin/npm
  Browsers:
    Chrome: 75.0.3770.142
    Firefox: 68.0.1
    Safari: 12.1.1
```

I believe your change is just for globally installed `@storybook/*` packages. But what about ones that are installed in the user's project?
