### ISSUE TITLE
Misleading usage information

### ISSUE THREAD

**Issue by jamesgeorge007** [storybookjs/storybook#7626]
```bash
Usage: sb [options] [command]

Options:
  -V, --version                  output the version number
  -h, --help                     output usage information

Commands:
  init [options]                 Initialize Storybook into your project.
  add [options] <addon>          Add an addon to your Storybook
  info                           Prints debugging information about the local environment
  migrate [options] [migration]  Run a storybook codemod migration on your source files
```

The usage information should be:-
Usage: sb &lt;command&gt; [options] instead

**Comment by shilman** [comment]
Ooh-la-la!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.1.10 containing PR #7627 that references this issue. Upgrade today to try it out!

**Comment by shilman** [comment]
Olé!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-beta.19 containing PR #7627 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.
