### ISSUE TITLE
build-storybook: calling configure more than once causes only last call to be honored

### ISSUE THREAD

**Issue by city41** [storybookjs/storybook#7636]
**Describe the bug**
Calling `configure` from `@storybook/react` more than once in your `.storybook/config.js` file works just fine in dev mode. All stories for each call to `configure` are present in the storybook.

But when invoking `build-storybook`, only the stories from the last call to `configure` are present.

**To Reproduce**

using 5.2.0-beta.18

1. In `.storybook/config.js`, call `configure` more than once, such that each call would load different stories
2. `yarn build-storybook`
3. `cd storybook-static && http-server`
4. Head to http://localhost:8080

**Expected behavior**
expected: All stories are present in the static build
actual: only the stories that matched in the last call to `configure` are present

**Screenshots**

**Code snippets**
I have a small repro repo here (probably not necessary, the issue is pretty straightforward): https://github.com/city41/storybookRepro

**System:**
```
  System:
    OS: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.13.0 - ~/.yarn/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
  Browsers:
    Chrome: 75.0.3770.142
    Firefox: 68.0
```

**Additional context**
This is probably not a bug. I could see the Storybook team preferring `configure` only be called once. But if that is the case, I think an error or warning should be emitted in dev mode.

I do see `index.js:42 Unexpected loaded state. Did you call `load` twice?` in the browser console, perhaps it could be a stronger error with a more clear message?

**Comment by shilman** [comment]
Added to documentation. Closing.
