### ISSUE TITLE
AddonStore crashes from bad logger import

### ISSUE THREAD

**Issue by jeremy-deutsch** [storybookjs/storybook#7637]
**Describe the bug**
In `@storybook/addons` 5.1.9, AddonStore has a bad import of `@storybook/client-logger`. This was fixed in [commit 9fb7217](https://github.com/storybookjs/storybook/commit/9fb72175b76b7ec613a34d31c15329a5333ab3b6#diff-95dd793bf940eb95d270f44051641e08), but doesn't seem to have made its way into a patch release for users still on Storybook 5.1. `@storybook/client-logger` needs to be imported as such:
```
import { logger } from '@storybook/client-logger';
```
but in `@storybook/addons`, in `index.ts` (the version on NPM), it's imported as:
```
import logger from '@storybook/client-logger';
```

**To Reproduce**
In a React Native Storybook project (this happens to be my use case), set up storybook with the following `addons.js` file:
```
import "@storybook/addon-actions/register"
import "@storybook/addon-ondevice-actions/register"
```

**Screenshots**
<img src="https://user-images.githubusercontent.com/13303900/62180676-c69e9200-b305-11e9-8685-1897bc3fa6d0.png" width="450">

**Code snippets**
If applicable, add code samples to help explain your problem.

**System:**
```
  System:
    OS: Linux 4.15 Ubuntu 16.04.6 LTS (Xenial Xerus)
    CPU: (8) x64 Intel(R) Core(TM) i7-6700T CPU @ 2.80GHz
  Binaries:
    Node: 10.10.0 - ~/.nvm/versions/node/v10.10.0/bin/node
    Yarn: 1.13.0 - ~/.nvm/versions/node/v10.10.0/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.10.0/bin/npm
  Browsers:
    Chrome: 75.0.3770.142
    Firefox: 68.0.1
```

**Comment by shilman** [comment]
Hey @jeremy-deutsch sorry I missed this the first time around. Is this still an issue? If so we'll try to get it patched ASAP.
