### ISSUE TITLE
DeprecationWarning: @storybook/addon-storysource/loader is deprecated

### ISSUE THREAD

**Issue by Edd-Strickland** [storybookjs/storybook#7654]
**Describe the bug**
DeprecationWarning: @storybook/addon-storysource/loader is deprecated, please use @storybook/source-loader instead.

on start up of beta 5.2.0-beta.19

**To Reproduce**
install latest beta and install then run start command. 

**Expected behavior**
seems this is deep linked into the core modules

**Comment by shilman** [comment]
@Edd-Strickland Can you share which packages you're using?

**Comment by Edd-Strickland** [comment]
> @Edd-Strickland Can you share which packages you're using?

default add ons included with SB 

The package is the HTML version SB

**Comment by shilman** [comment]
@Edd-Strickland can you do:

```
yarn why @storybook/addon-storysource
````

**Comment by Edd-Strickland** [comment]
on npm but I think I understand why it's doing it.

in the webpack config currently the config is set to :
`loaders: [
        {
          loader: require.resolve('@storybook/addon-storysource/loader')
       }`
But it needs to be set for 5.2 too:

`loaders: [
        {
          loader: require.resolve('@storybook/source-loader')
       }`

to work.

**Comment by Edd-Strickland** [comment]
however this now causes the HMR to constantly reload.  I'm assuming we should remove the deprecated package @storybook/addon-storysource/loader?

**Comment by shilman** [comment]
@Edd-Strickland i would expect `loader: require.resolve('@storybook/addon-storysource/loader')` to work, but to issue a deprecation warning

**Comment by Edd-Strickland** [comment]
Again not entirely sure why this was happening other than an abstract there seems to be a conflict however if you do not remove the @storybook/addon-storysource/ install after you've installed the @storybook/source-loader it seems to cause an HMR issue were it builds and then loads the SB instance only to then restart the build. 

removing the depreciated add-on install seems to reset it to not do this. 

Something for the upgrade to 5.2 docs I guess? if moving from the deprecated @storybook/addon-storysource/  to  @storybook/source-loader then ensure the old module is uninstalled and then make the changes in the webpack config above. 

Happy to close this as it appears all is resolved now. 

Are there any docs for 5.2 yet?  I've looking to attempt to upgrade to the CSF but need to do it manually due to the number of stories in play.   The automated won't cover it.

**Comment by shilman** [comment]
@Edd-Strickland That's pretty weird. Let's close it and feel free to re-open, holler, or open another issue if it rears its ugly head again.

The CSF stuff is reasonably documented in "writing stories" and its linked pages (IMHO, lmk if it's not):

https://github.com/storybookjs/storybook/blob/next/docs/src/pages/basics/writing-stories/index.md

The docs stuff is still WIP. Most recent docs is the tech preview doc, but will move that over to storybook monorepo hopefully this week:

https://docs.google.com/document/d/1un6YX7xDKEKl5-MVb-egnOYN8dynb5Hf7mq0hipk8JE/edit?usp=sharing

**Comment by Edd-Strickland** [comment]
thanks
