### ISSUE TITLE
addon-info works poorly with nesting & titles

### ISSUE THREAD

**Issue by Lexicality** [storybookjs/storybook#7655]
**Describe the bug**
If you use a title or a nested folder in your story name, `addon-info` shows an ugly title and does not show the documentation for the component

**To Reproduce**
Create a story with metadata in the title such as `Components/ExampleComponent` and then look at the story info pane

**Expected behavior**
The title should not include any metadata and the class documentation should be visible

**Screenshots**
![Screenshot 2019-08-01 at 14 06 47](https://user-images.githubusercontent.com/847422/62295959-198f5b00-b466-11e9-9cad-5aa27349b0a6.png)
![Screenshot 2019-08-01 at 14 06 56](https://user-images.githubusercontent.com/847422/62295960-198f5b00-b466-11e9-9913-4a82304d6bc2.png)
![Screenshot 2019-08-01 at 14 07 07](https://user-images.githubusercontent.com/847422/62295962-198f5b00-b466-11e9-80e7-50fca35fbba7.png)

**Code snippets**
_example-component.jsx_
```javascript
import PropTypes from "prop-types";
import React from "react";

/**
 * This is an example component that displays words
 */
export function ExampleComponent({ words }) {
    return <p>{words}</p>;
}

ExampleComponent.propTypes = {
    /** What to show in the component */
    words: PropTypes.string,
};

ExampleComponent.defaultProps = {
    words: "Hello, World!",
};
```
_example-component.stories.js_
```javascript
import { storiesOf } from "@storybook/react";
import React from "react";
import { ExampleComponent } from "./example-component";


let storyA = storiesOf("Components|ExampleComponent", module);
storyA.add("Example #1", () => <ExampleComponent />);

let storyB = storiesOf("Components/ExampleComponent", module);
storyB.add("Example #2", () => <ExampleComponent />);

let storyC = storiesOf("ExampleComponent", module);
storyC.add("Example #3", () => <ExampleComponent />);
```

**System:**
```
  System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-4308U CPU @ 2.80GHz
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 75.0.3770.142
    Safari: 12.1.2
```
(ps: I also have Firefox 68.0.1 installed)

**Additional context**
[`Story._getComponentDescription`](https://github.com/storybookjs/storybook/blob/v5.1.9/addons/info/src/components/Story.js#L266-L281) checks for a fulltext match against the story title, rather than a partial.

**Comment by Lexicality** [comment]
I guess I can have a poke at trying to fix this?

**Comment by shilman** [comment]
@Lexicality absolutely! would welcome a PR for this 🙏

**Comment by Lexicality** [comment]
I've got a patch that should work but I'm having considerable trouble getting a development environment working for this project

**Comment by shilman** [comment]
FYI `addon-info` is being superceded by `addon-docs`, which fixes a bunch of bugs and is easier to maintain. It’s reached release candidate (RC) status and will be properly released soon. Please give it a try! https://medium.com/storybookjs/storybook-docspage-e185bc3622bf

@Lexicality @mikewheaton @github-actions @stale

**Comment by Lexicality** [comment]
I'm aware, but unfortunately my team's pretty busy right now and I'd vastly prefer to just fix what we're currently using with a patch version update rather than spend any extra time changing things to a new system. 🙂

**Comment by shilman** [comment]
@Lexicality completely understood. happy to merge the PR and patch it back into 5.1.x once it's ready!

**Comment by shilman** [comment]
Just saw your dev environment comment. Did you get it working? Happy to help you out on Discord if it's useful: https://discord.gg/UUt2PJb
