### ISSUE TITLE
"cannot read property 'rules' of undefined" when upgrading from v4 to v5

### ISSUE THREAD

**Issue by Tycholiz** [storybookjs/storybook#7659]
After upgrading from v4 to v5, 'yarn storybook' no longer works, and I get the error above originating from my storybook/webpack.config.js. Here is that module:

storybook/webpack.config.js
```
const baseConfig = require('../../webpack.config')

module.exports = storybookBaseConfig => Object.assign({}, storybookBaseConfig, {
  resolve: Object.assign({}, storybookBaseConfig.resolve, {
    modules: baseConfig.resolve.modules,
  }),
  module: Object.assign({}, storybookBaseConfig.module, {
    rules: storybookBaseConfig.module.rules.concat(baseConfig.module.rules.slice(1)),
  }),
})
```

I'm not exactly sure what the issue is, as webpack is something I am not totally advanced in, so it may be a simple issue I am just not understanding. 

Here is also:

package.json
```
"devDependencies": {
    "@storybook/addon-actions": "^5.1.10",
    "@storybook/addon-viewport": "^5.1.10",
    "@storybook/addons": "^5.1.10",
    "@storybook/react": "^5.1.10",
}
```

I scaffolded this project with ARc React, whose storybook directory can be found here: https://github.com/diegohaz/arc/tree/master/private/storybook.

Aside from adding one addon (viewport), it is virtually unchanged

Thank you for all the help you provide to me :)

**Comment by shilman** [comment]
@Tycholiz https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#webpack-config-simplification
