### ISSUE TITLE
Info Addon - Props table when using nested types with react-docgen-typescript-loader

### ISSUE THREAD

**Issue by affanshahid** [storybookjs/storybook#7661]
**Describe the bug**
I have followed the storybook docs to enable auto generation of the prop types table for my components. Things are working but there is a slight issue when I use separate nested types.
For example with the following props:

```ts
export type TaskInfo = {
  id: string;
  title: string;
  state: 'TASK_INBOX' | 'TASK_PINNED' | 'TASK_ARCHIVED';
  updatedAt: Date;
}

export type TaskProps = {
  task: TaskInfo;
  onArchiveTask: (id: string) => void;
  onPinTask: (id: string) => void;
}
```
I get the following table:
![image](https://user-images.githubusercontent.com/17955210/62348251-eefcdb00-b515-11e9-8d0b-0d434a335c0d.png)

the type of the `task` property is `TaskInfo` without showing the details of `TaskInfo` anywhere. Is it possible to somehow show details of `TaskInfo` or display the structure of `TaskInfo` as the type instead?

**System:**
```
  System:
    OS: Windows 10
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 12.2.0 - D:\Program Files\nodejs\node.EXE
    npm: 6.9.0 - D:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
```

**Comment by shilman** [comment]
FYI `addon-info` is being superceded by `addon-docs`, which fixes a bunch of bugs and is easier to maintain. It’s reached release candidate (RC) status and will be properly released soon. Please give it a try! https://medium.com/storybookjs/storybook-docspage-e185bc3622bf

@affanshahid @github-actions @stale

**Comment by xikobe** [comment]
Did you manage to achieve this? I'm trying to do the same but could not get around to do it

**Comment by LukyVj** [comment]
Same, if anyone got an idea, I'm interested! 

My quick fix for now, is to literally paste the interface within a mdx comment. 

Like this: 
```javascript
/** `Component` blablabla some docs on here as usual

  ```
  // Types for NestedInterface
  node: {
    // description here
    foo: string;
    // description here
    bar: object;
    // description here
    baz: Number;
    // description here
    qux: object;
  };```
  */

```

I guess that'll do the trick while I look for a legit solution!

**Comment by vinod-donthi-by** [comment]
Is this issue fixed? Do we have a way to display nested types?
