### ISSUE TITLE
[Angular 8.1.2] Can't resolve all parameters for AppComponent: (?, ?, [object Object]).

### ISSUE THREAD

**Issue by prapansak** [storybookjs/storybook#7662]
**Describe the bug**
Unable to create story, I'm using Angular `8.1.2` and Storybook `5.1.10`

**To Reproduce**
Steps to reproduce
1.  Install Storybook `npx -p @storybook/cli sb init --type angular`
2. Run Storybook `npm run storybook`
4. See error `Can't resolve all parameters for AppComponent: (?, ?, [object Object]).`

**Expected behavior**
Story works well

**Screenshots**
![image](https://user-images.githubusercontent.com/15844170/62361720-bf65c700-b545-11e9-97d8-30fbb00516e5.png)

**Code snippets**
```
import { storiesOf } from '@storybook/angular';
import { Button } from '@storybook/angular/demo';

storiesOf('Button', module)
  .add('with text', () => ({
    component: Button,
    props: {
      text: 'Hello Button',
    },
  }));
```

**System:**
```
  System:
    OS: macOS 10.14.2
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  Binaries:
    Node: 12.7.0 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.10.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 75.0.3770.142
    Safari: 12.0.2
  npmGlobalPackages:
    @storybook/cli: 4.0.12
```

**Comment by thandaanda** [comment]
This may solve your issue [#7457 (comment)](https://github.com/storybookjs/storybook/issues/7457#issuecomment-514236598)

**Comment by prapansak** [comment]
@thandaanda It works! Thank you so much.

**Comment by brew-danica** [comment]
For anyone else lurking - pop that in your compilerOptions and that should work a treat. As it did for me - thanks @thandaanda !

**Comment by divisivadev** [comment]
i have added "emitDecoratorMetadata": true in .storybook/tsconfig.json
```
{
  "extends": "../tsconfig.app.json",
  "compilerOptions": {
    "types": [
      "node"
    ],
    "emitDecoratorMetadata": true
  },
  "exclude": [
    "../src/test.ts",
    "../src/**/*.spec.ts",
    "../projects/**/*.spec.ts"
  ],
  "include": [
    "../src/**/*",
    "../projects/**/*"
  ]
}
```
