### ISSUE TITLE
@storybook/addon-centered@5.1.10" has unmet peer dependency "mithril@*" "preact@*".

### ISSUE THREAD

**Issue by hinok** [storybookjs/storybook#7665]
**Describe the bug**
Adding `@storybook/addon-centered@5.1.10` ends with displaying warnings below.
I use React in my project.

```
warning " > @storybook/addon-centered@5.1.10" has unmet peer dependency "mithril@*".
warning " > @storybook/addon-centered@5.1.10" has unmet peer dependency "preact@*".
```

**To Reproduce**
1. Create a basic project
2. Add newest storybook and storybook/addon-centered

**Expected behavior**
No warnings about peer dependencies

**Screenshots**
N/A

**Code snippets**
N/A

**System:**
```
Environment Info:

  System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  Binaries:
    Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.10.1 - ~/.nvm/versions/node/v8.11.3/bin/npm
  Browsers:
    Chrome: 76.0.3809.87
    Firefox: 68.0.1
    Safari: 12.1.1
```

**Additional context**
I'd like to get rid off those warnings but I don't want to install `preact` or `mithril` in my project.

**Related**
https://github.com/storybookjs/storybook/issues/7087

**Comment by shilman** [comment]
We have two options here:
1) Remove the peer dependencies, implicitly depend on the various framework packages, and ignore warnings on our side
2) Add peer dependencies, explicitly depend on the various framework packages, and have users ignore warnings on their side

I think option (1) is the more user-friendly option. @leoyli @ndelangen @igor-dv  agree?

**Comment by leoyli** [comment]
@shilman, I agreed for (1).  The user definitely have no clue and should not care about that.  We will also need it to be stated in the contribution guide and perhaps let all maintainer knows in discord.

**Comment by ndelangen** [comment]
done
