### ISSUE TITLE
Component story format break hot reloading

### ISSUE THREAD

**Issue by tomitrescak** [storybookjs/storybook#7666]
**Describe the bug**
When used the new component story format with latest 5.2 beta, the hot reloading stops working. Reverting back to old format all works.

**To Reproduce**

Used the code from: https://medium.com/storybookjs/component-story-format-66f4c32366df
Modified component, received buch of messages in the console but the component not reloaded.

**Expected behavior**
Component hot reloads.

**Comment by shilman** [comment]
@tomitrescak Need a lot more context to answer your question. Do you have a repro repo I can look at?

**Comment by tomitrescak** [comment]
Hi, yes, silly me. Here it goes:

https://github.com/tomitrescak/react-boilerplate

**Comment by shilman** [comment]
Thanks. Will take a look this weekend!

**Comment by shilman** [comment]
Yo-ho-ho!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-beta.22 containing PR #7670 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
