### ISSUE TITLE
Jest is throwing an error after importing @storybook/addon-contexts/react to config.js

### ISSUE THREAD

**Issue by MikeYermolayev** [storybookjs/storybook#7678]
**Describe the bug**
Hello,
I'm using create-react-app 3.0.1 and trying to setup the storybook. 
I've set up automated snapshot testing of my stories and now I want to add context addon. But when I run `npm run test` I observe the error that Jest can't parse the file.

**To Reproduce**
1. Build new project using create-react-app
2. Init storybook
3. Add storyshots addon
4. Try to Import '@storybook/addon-contexts/react' to the config.js
5. Run `npm run test`
6. See error

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/8783498/62444183-7b510d00-b765-11e9-8d33-5645d787e9f3.png)

**Code snippets**
config.js
```
import { configure } from '@storybook/react';
import { withContexts } from '@storybook/addon-contexts/react';
import requireContext from 'require-context.macro';
import { contexts } from './contexts';

import '../src/index.css';

const req = requireContext('../src/components', true, /\.stories\.jsx?$/);

function loadStories() {
  req.keys().forEach(filename => req(filename));
}

addDecorator(withContexts(contexts));
configure(loadStories, module);
```
**System:**
Environment Info:

  System:
    OS: macOS 10.14.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 10.14.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 75.0.3770.142
    Firefox: 66.0.3
    Safari: 12.1
  npmPackages:
    @storybook/addon-actions: ^5.1.10 => 5.1.10
    @storybook/addon-contexts: ^5.1.10 => 5.1.10
    @storybook/addon-knobs: ^5.1.10 => 5.1.10
    @storybook/addon-links: ^5.1.10 => 5.1.10
    @storybook/addon-storyshots: ^5.1.10 => 5.1.10
    @storybook/addons: ^5.1.10 => 5.1.10
    @storybook/react: ^5.1.10 => 5.1.10

Probably I just need to add some babel config or specify some loaders but maybe there is some advanced case for create-react-app.

Thanks in advance, looking for any advices.

**Comment by sebslomski** [comment]
Hi,
this seems to be an open issue. @saviomuc solved it over here: https://github.com/storybookjs/storybook/issues/7453#issuecomment-517686819

**Comment by MikeYermolayev** [comment]
@sebslomski thanks for the link. Yeah the issue is the same so probably my can be closed as duplicate.

@saviomuc looks like this solution fits for ejected CRAs but I'd like to not eject mine.

Maybe some solution with babel-plugins-macro can be made?

**Comment by saviomuc** [comment]
@MikeYermolayev If you don't want to eject you could also use https://github.com/harrysolovay/rescripts to modify the babel config.

**Comment by shilman** [comment]
Cool, closing this as a duplicate! 👍

**Comment by MikeYermolayev** [comment]
@saviomuc thanks a lot but still it looks like a workaround. 
Do you know if it's possible to make it work out-of-the-box? Are there any plans for that?

**Comment by zakkor** [comment]
I don't see why this one file in this one addon should use ES6 modules, unlike all the others.
This requires CRA users to do a ton of extra work to get this addon to work.

Try importing the built file instead of the ES6 modules file:
`import { withContexts } from '@storybook/addon-contexts/dist/preview/frameworks/react'`

**Comment by shilman** [comment]
FYI `addon-toolbars` is replacing `addon-contexts`: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-addon-contexts
