### ISSUE TITLE
Props in typescript not displayed

### ISSUE THREAD

**Issue by aaa-magenic-eleazarj** [storybookjs/storybook#7687]
**Describe the bug**
The props in typescript are not displayed when component is wrapped in HOC withStyles/withTheme of material ui. Only 'innerRef' props are displayed

**Expected behavior**
All defined props should be displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/32895751/62490836-edc0fc00-b7fc-11e9-985c-9be7c1a34d4a.png)

**Code snippets**
export default withStyles(styleClasses, { index: 0, withTheme: true })(
   ColorButton
 );
export default withTheme(Button);

**Comment by shilman** [comment]
FYI `addon-info` is being superceded by `addon-docs`, which fixes a bunch of bugs and is easier to maintain. It’s reached release candidate (RC) status and will be properly released soon. Please give it a try! https://medium.com/storybookjs/storybook-docspage-e185bc3622bf

@aaa-magenic-eleazarj @einaralex @github-actions

**Comment by freddy-reye16** [comment]
Has anyone found a solution or workaround for this topic? I'm running into the same issue. Thanks in advance

**Comment by petermikitsh** [comment]
This issue is still present: `classes` and `innerRef` are all that's show for components from `@material-ui/core`.

<img width="1493" alt="Screen Shot 2020-03-19 at 4 04 18 PM" src="https://user-images.githubusercontent.com/1571918/77122622-527f3e80-69fb-11ea-97ce-e15476c1916a.png">

**Comment by petermikitsh** [comment]
Workaround:

```tsx
// storybook/components/Button.tsx
import * as React from "react";
import { Button as MatButton, ButtonProps } from "@material-ui/core";

export const Button: React.FC<ButtonProps> = props => <MatButton {...props} />;
```

```tsx
// storybook/stories/1-Button.stories.tsx
import * as React from "react";
import { action } from "@storybook/addon-actions";
import { Button } from "../components/Button";

export const Text = props => (
  <Button variant="contained" color="primary" onClick={action("clicked")}>
    Hello Button
  </Button>
);

export default {
  title: "Button",
  component: Button
};
```

<img width="1436" alt="Screen Shot 2020-03-19 at 5 44 35 PM" src="https://user-images.githubusercontent.com/1571918/77127347-56b25880-6a09-11ea-902f-d1588c62eb26.png">
