### ISSUE TITLE
storiesof-to-csf removes comment above storiesOf import

### ISSUE THREAD

**Issue by dburles** [storybookjs/storybook#7698]
5.2.0-beta.23

It appears as though comments positioned directly above the `storiesOf` import are also removed. This is a breaking issue in this case as the comment is required.

![Screen Shot 2019-08-07 at 9 27 57 am](https://user-images.githubusercontent.com/319567/62583976-f5b09700-b8f5-11e9-88be-8c89c4534534.png)

**Comment by vanessayuenn** [comment]
Hi! I am going through and cleaning up old issues in the repo. We just shipped a ton of improvements in Storybook 7.0, and I suspect this bug might be fixed already. Can you please try it out? If this issue persists with the latest version, please open a new bug report with a 7.x reproduction. Thank you so much! 🙏🏼
