### ISSUE TITLE
CSF: storiesof-to-csf parameters with duplicate keys

### ISSUE THREAD

**Issue by dburles** [storybookjs/storybook#7699]
5.2.0-beta.23

Stories with more than one `addParameters({ component: ... })` result in an export containing parameters with duplicate keys for `component`. e.g:
```js
export default {
  title: 'Elements/Card',

  parameters: {
    component: Card,
    component: CardHeader,
    component: CardImage,
    component: CardContent,
    component: CardActions,
  },
};
```

**Comment by shilman** [comment]
@dburles what would you expect it to do in this case?

**Comment by dburles** [comment]
Should passing multiple `addParameters` to a single story been allowed in the first place? I wondered since it is possible that you couldn't also pass an array `addParameters: { components: [Card, CardHeader, ...] }`

**Comment by shilman** [comment]
I'd argue that the current behavior is desirable.

The codemod takes the user's current code and creates CSF-style code that preserves some of the weirdness of the original. It's up to the user to figure out what to do about it. It could also error in this case, or issue a warning to the user?

I think what it would ideally do is to create story-level parameters. But that's tricky to implement, and I'd rather loop in the user to clean it up.

**Comment by dburles** [comment]
Yeah, I guess generally you don't want to generate code that's broken, but if there isn't an automated way to avoid it, then I guess it's unavoidable. A warning could perhaps assist too.
