### ISSUE TITLE
IE11:  Object doesn't support property or method 'assign'

### ISSUE THREAD

**Issue by adamdoyle** [storybookjs/storybook#7706]
**Describe the bug**
The following usage (in [lib/core/src/server/templates/index.ejs](https://github.com/storybookjs/storybook/blob/next/lib/core/src/server/templates/index.ejs#L28)) of `Object.assign(...)` in the EJS template for the manager is incompatible with IE11:

```ejs
<% if (typeof globals !== 'undefined' && Object.keys(globals).length) { %>
  <script>
    Object.assign(window, <%= JSON.stringify(globals) %>);
  </script>
<% } %>
```

Additionally, it's ineligible for babel transformation since it's embedded in a `<script>` tag

**To Reproduce**

<details>
<summary>(1) Launch Storybook</summary>

1. Clone Storybook
```bash
>> git clone https://github.com/storybookjs/storybook.git
>> cd storybook
```

2. Install dependencies
```bash
>> yarn
```

3. Bootstrap core
```bash
>> yarn bootstrap --core
```

4. Launch sample Storybook
```bash
>> yarn start
```
</details>

<details>
<summary>(2) Observe Error</summary>

1. Open IE11
2. Navigate to endpoint
3. Press [F12] to open "Developer Tools"
4. Switch "Developer Tools" tab to "Console"
5. Reload page
6. Observe that error is present

</details>

**Screenshots**

![SCRIPT438: Object doesn't support property or method 'assign' File: <host>:9011, Line: 49, Column: 9](https://user-images.githubusercontent.com/728428/62620536-951a5d80-b8e7-11e9-9ae1-db396a5038b1.png)

**System:**

<details>
<summary>Serving Storybook (CentOS 7)</summary>

```
System:
  OS: Linux 3.10 CentOS Linux 7 (Core)
  CPU: (16) x64 Intel(R) Core(TM) i7-7820X CPU @ 3.60GHz
Binaries:
  Node: 11.4.0 - /opt/node/current/bin/node
  Yarn: 1.15.2 - ~/globalNodeModules/bin/yarn
  npm: 6.9.0 - ~/globalNodeModules/bin/npm
Browsers:
  Chrome: 74.0.3729.157
npmGlobalPackages:
  @storybook/cli: 5.0.11
```
</details>

<details>
<summary>Testing Storybook (Windows 7 Professional)</summary>

```
  System:
    OS: Windows 7
    CPU: (8) x64 Intel(R) Xeon(R) CPU W3520 @ 2.67GHz
  Binaries:
    Node: 11.8.0 - C:\applications\node\v11.8.0-x64\node.EXE
    npm: 6.5.0 - C:\applications\node\v11.8.0-x64\npm.CMD
```
</details>

**Comment by adamdoyle** [comment]
@ndelangen Looks like it was [this change](https://github.com/storybookjs/storybook/commit/1a6007d46f114d0b60f46936028bde7c5c8d097e) that switched from IE11-safe `window[/* ... */] = /* ... */` assignments to IE11-unsafe `Object.assign(/* ... */);`.

I tested switching back to the old form (but switching to the `globals` variable), which eliminated the error and _appeared(?)_ to correctly set the global variables:

```ejs
<% if (typeof globals !== 'undefined' && Object.keys(globals).length) { %>
  <script>
    <% for (var varName in globals) { %>
        <% if (globals[varName] != undefined) { %>
          window['<%=varName%>'] = <%= JSON.stringify(globals[varName]) %>;
        <% } %>
    <% } %>
  </script>
<% } %>
```

**Comment by shilman** [comment]
Huzzah!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-beta.25 containing PR #7707 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
