### ISSUE TITLE
NativeScript support

### ISSUE THREAD

**Issue by caamx** [storybookjs/storybook#7708]
**Is your feature request related to a problem? Please describe.**
Apps created with NativeScript cannot be used with storybook.

**Describe the solution you'd like**
Apps created with NativeScript can be used with storybook. 
Since NativeScript already offers the possibility to preview the apps on the device by using the NativeScript playground app and NativeScript CLI to generate a QR Code, something similiar to this would be preferable. This could look something like: Display the storybook in the browser and preview the component on the device/simulator.

**Describe alternatives you've considered**
Unfortunately, there are none.

**Are you able to assist bring the feature to reality?**
no 

**Additional context**

**Comment by sinkersan** [comment]
Any updates? I think this will be very useful. Or maybe someone knows good alternatives?

**Comment by diegovincent** [comment]
@shilman I did not realize this was the "main" repository. Feel free to close https://github.com/storybookjs/react-native/issues/61 and open it here.

**Comment by diegovincent** [comment]
Could we reopen this?

**Comment by diegovincent** [comment]
Number of likes is increasing. No PRs by anbody?

**Comment by shilman** [comment]
Assuming NativeScript can run in Appetize, we may have a solution prototyped 

https://medium.com/@vasikarla.raj/storybook-for-native-d772654c7133

**Comment by pascal-puetz** [comment]
> 
> 
> Assuming NativeScript can run in Appetize, we may have a solution prototyped
> 
> https://medium.com/@vasikarla.raj/storybook-for-native-d772654c7133

Now this looks really promising! Pretty sure NativeScript can work with Appetize, though I haven't verified that. I will take a deeper look into that as soon as I have some free time on hand and will report back!

**Comment by MrSnoozles** [comment]
Has anyone tried making Storybook work with NativeScript yet?
