### ISSUE TITLE
Addon-viewport: defaultViewport does not work

### ISSUE THREAD

**Issue by XYShaoKang** [storybookjs/storybook#7717]
**Describe the bug**

Addon-viewport parameter configuration `defaultViewport` does not work in Storybook 5.2

**To Reproduce**

Follow the [documentation](https://github.com/storybookjs/storybook/tree/v5.2.0-beta.25/addons/viewport#installation) installation

Configuration

```js
// config.js
import { INITIAL_VIEWPORTS } from '@storybook/addon-viewport'

addParameters({
  viewport: {
    viewports: {
      ...INITIAL_VIEWPORTS,
    },
    defaultViewport: 'ipad',
  },
})
```

Refresh storybook, `defaultViewport` does not work, Preview Area is still 100% filled.

I can switch Preview Area by clicking viewport addon icon and selecting ipad.

**Expected behavior**

`defaultViewport` should work. The default Preview Area should be ipad

**System:**

```
System:
  OS: Linux 5.1 Arch Linux undefined
  CPU: (8) x64 Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz
Binaries:
  Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
  Yarn: 1.17.2 - ~/.yarn/bin/yarn
  npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
npmPackages:
  @storybook/addon-actions: ^5.2.0-beta.25 => 5.2.0-beta.25
  @storybook/addon-backgrounds: ^5.2.0-beta.25 => 5.2.0-beta.25
  @storybook/addon-console: ^1.2.1 => 1.2.1
  @storybook/addon-graphql: ^5.2.0-beta.25 => 5.2.0-beta.25
  @storybook/addon-jest: ^5.2.0-beta.25 => 5.2.0-beta.25
  @storybook/addon-knobs: ^5.2.0-beta.25 => 5.2.0-beta.25
  @storybook/addon-links: ^5.2.0-beta.25 => 5.2.0-beta.25
  @storybook/addon-notes: ^5.1.10 => 5.1.10
  @storybook/addon-storyshots: ^5.2.0-beta.25 => 5.2.0-beta.25
  @storybook/addon-storysource: ^5.2.0-beta.25 => 5.2.0-beta.25
  @storybook/addon-viewport: ^5.2.0-beta.25 => 5.2.0-beta.25
  @storybook/react: ^5.2.0-beta.25 => 5.2.0-beta.25
```

**Additional context**

I am trying to find the answer in the source code, guessing the problem may appear in this code
[Tool.tsx#L129](https://github.com/storybookjs/storybook/blob/a27848360dca94efb14e48b6b00fbc821c3d2e0d/addons/viewport/src/Tool.tsx#L129)

```js
const [state, setState] =
  useAddonState <
  ViewportToolState >
  (ADDON_ID,
  {
    selected: defaultViewport || responsiveViewport.id,
    isRotated: false,
  })
const list = toList(viewports)

const { selected, isRotated } = state
const item =
  list.find(i => i.id === selected) ||
  list.find(i => i.id === defaultViewport) ||
  list.find(i => i.default) ||
  responsiveViewport
```

I debug the output through `console.log(defaultViewport)` and see that `defaultViewport` is initially `reset`, and then it will change once and become `ipad`.

I guess the initial value is obtained when the plugin is registered, and the latter change occurs when the configuration parameters are fetched.

`state.selected` is initially set by `defaultViewport`, and `useAddonState` does not reset `state` according to `defaultViewport`, so `selected` will not change according to the change of `defaultViewport`. Even if `defaultViewport` is set, the final `selected` is always `reset`.

I think `selected` should change when `defaultViewport` changes.

I added the following code to [ViewportTool(Tool.tsx#L134)](https://github.com/storybookjs/storybook/blob/next/addons/viewport/src/Tool.tsx#L134) to make the `defaultViewport` setting take effect.

```js
useEffect(() => {
  // If `defaultViewport` is not set, `defaultViewport` will become `undefined`
  // There is no need to trigger a modification at this time.
  if (defaultViewport) {
    setState({
      selected: defaultViewport,
      isRotated: false,
    })
  }
}, [defaultViewport])
```

Because I am not familiar with `storybook` and the plugin system, I am not sure if this is the best way to solve this problem, and whether there will be problems that I don't know, so I hope to get guidance.

**Comment by shilman** [comment]
Fixed in https://github.com/storybookjs/storybook/pull/7448 & released in `5.2.0-beta.41`. Closing 🎉

**Comment by shilman** [comment]
Oops looks like that PR addressed another issue. Reopening.

**Comment by shilman** [comment]
ZOMG!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-rc.1 containing PR #7934 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
