### ISSUE TITLE
[API] storybook api onchange returns undefined kind

### ISSUE THREAD

**Issue by flxwu** [storybookjs/storybook#7720]
**Describe the bug**
When calling `storybookAPI.onChange((kind,story) =>` as specified in the docs, story is undefined.

**To Reproduce**
```
import addonAPI from '@storybook/addons';
addonAPI.register('test', storybookAPI => {
	storybookAPI.on((kind, story) => {
                console.log(kind); // returns the story id, e.g. components--action-button
		console.log(story); // returns undefined
	});
});
```
**Expected behavior**
kind should be the component type, story should be the story name.

**System:**
Environment Info:

  System:
    OS: macOS 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz
  Binaries:
    Node: 12.6.0 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 76.0.3809.100
    Firefox: 67.0.2
    Safari: 12.1.1
  npmPackages:
    @storybook/react: ^5.2.0-alpha.36 => 5.2.0-beta.25

**Additional context**
I'm on the new storybook with addon-docs, maybe something got changed there that isn't in the docs yet?

**Comment by ndelangen** [comment]
`storybookAPI.onChange` doesn't exist AFAIK
`storybookAPI.on` requires an eventType and a handler
`storybookAPI.onStory` is deprecated in favour of:

```js
import { STORY_CHANGED } from '@storybook/core-events';

addons.register('my-organisation/my-addon', api => {
  api.on(STORY_CHANGED, storyId => console.log(storyId));
});

```

**Comment by ndelangen** [comment]
Please let us know if you're still experiencing problems.

**Comment by numerized** [comment]
This should be added to the documentation where deprecated info onStory is shown.
