### ISSUE TITLE
Use style files from repo with addon-cssresources

### ISSUE THREAD

**Issue by nbrylev** [storybookjs/storybook#7725]
Greetings!

**Is your feature request related to a problem? Please describe.**
Our team is making components library for inner projects and we use Storybook. We have couple of themes for components (different component's styles for every project). So I've tried addon-cssresources and faced with next problem. I can't link/use css files from components repo (so, Storybook in the same repo). As I understood that addon is useful if you want link styles from any UI stuff like Bootstrap and etc. So sad :( 

**Describe the solution you'd like**
I'd like to import style files from the same repo where Storybook is running.

**Describe alternatives you've considered**
:(

**Are you able to assist bring the feature to reality?**
Yep

**Additional context**
BTW themes' files are huge-ish, there're imports of all our components :)
Maybe anyone faced with same problem and found a working solution?

**Comment by shilman** [comment]
Are you interested in trying to solve this? Do you need any help getting set up to contribute?
