### ISSUE TITLE
@storybook/react-native error after upgrade to 5.1.10

### ISSUE THREAD

**Issue by chrisdrackett** [storybookjs/storybook#7730]
I upgraded `@storybook/react-native` from `5.1.9` to `5.1.10` and got the following error when building my app:

```
[0] [20:48:36] Failed to compile.
[0] [20:48:36] /Users/cwd/src/calm/node_modules/@emotion/native/dist/native.browser.esm.js
[0] [20:48:36] Module not found: Can't resolve 'react-native' in '/Users/cwd/src/calm/node_modules/@emotion/native/dist'
```

rolling back to `5.1.9` fixed the issue. Might be worth mentioning that this issue is when using `expo` and shows up when compiling for web or iOS.

**Comment by shilman** [comment]
Sounds like a yarn/npm issue. Can you try removing node_modules & reinstalling? And if that doesn't work, removing your package lock file also and reinstalling?

**Comment by trflagg** [comment]
Hi. Just want to add that I am also getting this exact error
```
error: bundling failed: Error: Unable to resolve module `react-native` from `[HIDDEN]/storybook/index.js`: Module `react-native` does not exist in the Haste module map or in these directories:
  [HIDDEN]/node_modules
```

For me, it started after I upgraded react to v16.9 and react-native to 59.0.

I reset watchman, cleared the cache, recreated node_modules, and cleared my emulator's data, but always the same issue. I upgraded to storybook@5.2.0-rc6 but got the same error.

**Comment by trflagg** [comment]
Quick update.  I figured out that my problem was from running

`storybook start -p 7007 | react-native start --projectRoot storybook` 

I guess `--projectRoot` doesn't work anymore.

**Comment by shilman** [comment]
@benoitdion @ Looks like `--projectRoot` got lost in the server rearchitecture. can either of you help me with an update to `MIGRATION.md`?

**Comment by benoitdion** [comment]
Is https://github.com/react-native-community/cli/pull/259 helpful?

**Comment by Gongreg** [comment]
Hi, can you try out 5.3.0-alpha.37 ? I think you shouldn't have issues anymore.
