### ISSUE TITLE
Redesigned addon-jest counts pending tests and todos as "failed"

### ISSUE THREAD

**Issue by fabiradi** [storybookjs/storybook#7740]
**Describe the bug**
The redesigned addon-jest handles **skipped tests** (pending) and **todos** (todo) differently compared to the previous version: They currently **don't show up in the list**. Previously, they were counted as "failed", but shown in "green" (like "passed"). This was still not perfect, but – at least – they were displayed.

**To Reproduce**
1. Create skipped test and todos
2. (Re-)Generate JSON results as usual: `jest test` lists skipped tests and todo separately in its summary.
3. Look at the "Tests" panel

**Expected behavior**

**Screenshots**
<img width="382" alt="jest-summary" src="https://user-images.githubusercontent.com/5428213/61635478-f5789080-ac93-11e9-8d43-b4b3d3017fdc.png">

![jest-failed-tests](https://user-images.githubusercontent.com/5428213/61635700-691a9d80-ac94-11e9-938c-c63251304ab2.png)

**Code snippets**
```javascript
test.todo('This is a todo');
xit('This is a skipped test', () => {});
```

**System:**
(I'm wrinting this issue on a different machine, so no results of `npx -p @storybook/cli@next sb info` here...)

**Additional context**
I'm already working on the fix 😄

**Comment by fabiradi** [comment]
✋ As I'm already working on the fix, I would like to have this issue assigned.

**Comment by shilman** [comment]
Thanks @fabiradi !!! 🙏

**Comment by shilman** [comment]
Olé!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-beta.33 containing PR #7793 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
