### ISSUE TITLE
Preview not responsive

### ISSUE THREAD

**Issue by idahogurl** [storybookjs/storybook#7744]
**Describe the bug**
The Preview iframe does not have a viewport meta tag. This causes the page not to act responsively.

**To Reproduce**
1. Open Chrome
2. Go to 'http://localhost:6006/'
3. Open 'DevTools'
4. Click 'Toggle device toolbar'
5. Enter 320 for the screen width.
6. The page does not apply applicable media queries.

**Expected behavior**
The page should render responsively.

**Screenshots**

*Source of Page: No viewport meta tag*
![image](https://user-images.githubusercontent.com/10620169/62881677-8ec42100-bced-11e9-9a98-2005ff6df777.png)

*Page renders "desktop" version despite set to 320px screen size*
![image](https://user-images.githubusercontent.com/10620169/62881634-7227e900-bced-11e9-951d-8815e831bd7a.png)

*Source of Page: After I add the viewport meta tag*
![image](https://user-images.githubusercontent.com/10620169/62881711-9be11000-bced-11e9-8e2a-932671dce870.png)

*Page renders correctly*
![image](https://user-images.githubusercontent.com/10620169/62881733-a8fdff00-bced-11e9-985c-2e6cec6c9ee5.png)

**System:**
  System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    Yarn: 1.17.3
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 76.0.3809.100
    Firefox: 68.0.1
    Safari: 12.1.1
  npmPackages:
    @storybook/addon-options: ^4.0.8 => 4.1.4 
    @storybook/addons: ^4.0.8 => 4.1.4 
    @storybook/react: ^4.0.8 => 4.1.4

**Comment by shilman** [comment]
@idahogurl Any chance you can upgrade to 5.1 or 5.2-beta? I don't know whether this is fixed there, but there's a low likelihood that we'd implement a patch for 4.x at this point unless it's a major breaking issue (which it's not).

**Comment by Huespal** [comment]
Hello.
Viewport feature is a bit useless if it is not responsive as @idahogurl asks for.
4 years is a lot of time, please, can someone just take this into consideration?
Thank you.

**Comment by Juroviol** [comment]
Exactly. What is the purpose of this if it doesn't work as it should?
