### ISSUE TITLE
Addon-actions: "action" is always wrapped in an array

### ISSUE THREAD

**Issue by Haroenv** [storybookjs/storybook#7764]
**Describe the bug**

I'm trying to periodically log actions of deep objects. Because the default view is only one level deep, it's stringified, however, this wraps a bit oddly in certain circumstances.

Ideally I'd be able to use the default object representation, but be able to specify it should be expanded N levels, as well as not having the wrapping array around it.

If it is something possible via a decorator, that would also be fine, but I couldn't see how to do that.

**To Reproduce**
1. log a single value
2. see an array being logged

**Expected behavior**

Only a single value is taken up while logging.

**Screenshots**

<img width="346" alt="Screenshot 2019-08-13 at 13 55 01" src="https://user-images.githubusercontent.com/6270048/62939632-ff446e00-bdd1-11e9-9861-d2e3b1cedaf9.png">
<img width="919" alt="Screenshot 2019-08-13 at 13 53 22" src="https://user-images.githubusercontent.com/6270048/62939633-ffdd0480-bdd1-11e9-92ac-d1db625eb23a.png">

**Code snippets**

```js
import { action } from '@storybook/addon-actions';

const urlLogger = action('Routing state');

// ...

const routeState = { "numericMenu": { "price": "100:" }, "refinementList": { "brand": [ "Samsung" ] } };

urlLogger(JSON.stringify(routeState, null, 2));
```

**System:**

Environment Info:

  System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i7-7Y75 CPU @ 1.30GHz
  Binaries:
    Node: 8.16.0 - ~/.nvm/versions/node/v8.16.0/bin/node
    Yarn: 1.16.0 - ~/.yarn/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v8.16.0/bin/npm
  Browsers:
    Chrome: 76.0.3809.100
    Safari: 12.1.2
  npmPackages:
    @storybook/addon-actions: 5.1.9 => 5.1.9 
    @storybook/html: 5.1.9 => 5.1.9 
    @storybook/theming: 5.1.9 => 5.1.9 

**Additional context**

https://deploy-preview-4000--instantsearchjs.netlify.com/stories/?path=/story/currentrefinements--default

**Comment by Haroenv** [comment]
Sorry, seems like this isn't important after all. Tell me if this isn't worth it :)

**Comment by shilman** [comment]
Can you use the `depth` option?:

```js
action('my-action', {
  depth: 5,
})
```

**Comment by Haroenv** [comment]
Sounds great, will try

**Comment by Haroenv** [comment]
@shilman, it seems to be still collapsed with that option unfortunately. Is there a lower-level primitive I could hook into maybe? 

for reference, here's what it looks like with:

depth: 5

<img width="265" alt="Screenshot 2019-09-04 at 09 15 59" src="https://user-images.githubusercontent.com/6270048/64233651-f6d4e400-cef4-11e9-9649-dcd8aa3bd9b9.png">

as a string

<img width="591" alt="Screenshot 2019-09-04 at 09 16 18" src="https://user-images.githubusercontent.com/6270048/64233667-fd635b80-cef4-11e9-8847-678f2bb4ef18.png">

Thanks!

**Comment by OutThisLife** [comment]
why's this closed? still happens. should not.

**Comment by yannbf** [comment]
Reopening this issue because indeed it still happens and we actually have a contribution by @guilhermewaess that fixes it! 🎉

**Comment by shilman** [comment]
ZOMG!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.0-alpha.15 containing PR #13624 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
