### ISSUE TITLE
PropType descriptions not showing.

### ISSUE THREAD

**Issue by anthify** [storybookjs/storybook#7766]
**Describe the bug**
PropTypes descriptions not appearing, but all other table items are visible `property`, `default`, `required`, and `propType`.

Description example.
```javascript
Block.propTypes = {
  /**
   * Margin bottom.
   */
  mb: PropTypes.string,
}
```

**To Reproduce**
Followed `addon-info` docs applied it in the config file. 

**Expected behavior**
PropType descriptions to appear in the PropTypes table in Storybook.

**Screenshots**
![image](https://user-images.githubusercontent.com/11407171/62977156-2886ed80-be16-11e9-9612-4bd0cfb71879.png)

**Code snippets**
If applicable, add code samples to help explain your problem.

**System:**
```console
  System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 8.12.0 - /usr/local/bin/node
    Yarn: 1.17.3 - ~/projects/studio/app/node_modules/.bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 76.0.3809.100
    Firefox: 66.0.3
    Safari: 12.1.1
  npmPackages:
    @storybook/addon-actions: ^5.1.11 => 5.1.11 
    @storybook/addon-backgrounds: ^5.1.11 => 5.1.11 
    @storybook/addon-info: ^5.1.11 => 5.1.11 
    @storybook/addons: ^5.1.11 => 5.1.11 
    @storybook/react: ^5.1.11 => 5.1.11
```

**Additional context**
I've searched all over for a solution, but nothing I've read and tried has worked. I'm hoping it's something simple I'm missing. Any time and help you can put into this would be greatly appreciated 🙇

**Comment by shilman** [comment]
FYI `addon-info` is being superceded by `addon-docs`, which fixes a bunch of bugs and is easier to maintain. It’s reached release candidate (RC) status and will be properly released soon. Please give it a try! https://medium.com/storybookjs/storybook-docspage-e185bc3622bf

@anthify @p1t1ch @github-actions

**Comment by Zenoo** [comment]
@anthify : I had the same issue myself.
Fixed it by installing [babel-plugin-react-docgen](https://github.com/storybookjs/babel-plugin-react-docgen):

```
npm install -D babel-plugin-react-docgen
```
Then register it to Babel's plugins inside your `.babelrc`
```
{
  "plugins": ["react-docgen"]
}
```

Restart your Storybook server and it should show up.
