### ISSUE TITLE
Unable to host static build on sub folder

### ISSUE THREAD

**Issue by jontansey** [storybookjs/storybook#7775]
I'm trying to host  the static build of story book on a sub folder e.g. `https://domain.com/shared-ui` and I'm having some trouble. The index.html file generated by storybook has all of the scripts like this `<script src="main.[hash].bundle.js">` which is an issue because they're not at `main.[hash].bundle.js` they're at `/shared-ui/main.[hash].bundle.js` I've tried all the config options and it's still not prepending `shared-ui` to those files. 

Things I've tried:
* Changing values in the `.storybook/wepback.config.js` -  `config.output.path`, `config.output.filename` & `config.output.publicPath`
* Changing the `homepage` value in `package.json`
* Running the `build-storybook` command with `-o /shared-ui/` to output the static site to `/shared-ui/`
* Modifying the webpack config HtmlWebpackPlugin options to use a custom template for the page generation - this seems this only works for `iframe.html` (also built by the static site script) and not `index.html`

Ideally I'm looking for a way to configure sb correctly to generate the script tags in index.html with the correct url or override the template for index.html so I can do it myself

Many thanks for any help that you can give

**Comment by cogoo** [comment]
Having this same issue, anyway to resolve this?

**Comment by ndelangen** [comment]
Interesting, we do this ourselves, without problem:
https://storybookjs-next.now.sh/dev-kits/
https://storybookjs-next.now.sh/official-storybook/

Anything special to how you serve those subfolders?

Do you have a reproduction we could look at?

**Comment by dangodev** [comment]
Just wanted to chime in and say I too had this issue, but it was _because_ I had a configuration error in `webpack.config.js` unrelated to this. I was able to get this working **out-of-the-box** with the latest Storybook with no configurations 🎉.

If others are experiencing the same problem, it may be from some custom configuration you or someone on your team added. Try removing all of that, then adding your config back one-by-one to see what’s breaking the subfolder build.

**Comment by kimromi** [comment]
try it

```console
$ echo '<base href="/shared-ui/">' >> .storybook/manager-head.html
```

and run `build-storybook`.

- https://storybook.js.org/docs/configurations/add-custom-head-tags/#add-tags-or-scripts-to-the-main-ui
- https://storybook.js.org/docs/configurations/serving-static-files/#absolute-versus-relative-paths
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base

**Comment by gvinter** [comment]
This is still a problem for me. I'm in a Rails app, and want to load Storybook at `abc.io/storybook`, but the `main`, `vendors`, and `runtime` JS files and `iframe.html` files are all src'd to the root, when they should be at `/storybook/...`.

Build command I'm using: `build-storybook -o ./public/storybook`

Here's what I have tried:
* Adding `<base href="/storybook/" />` to `manager-head.html`
* Trying to update webpack in `main.js`, but when I add `--debug-webpack` this isn't represented in the config logged: 
```
module.exports = {
  stories: ['../**/*.stories.(jsx|mdx)'],
  addons: ['@storybook/addon-actions', '@storybook/addon-links', '@storybook/addon-docs'],
  webpackFinal: async (config) => {
    const updatedConfig = {
      output: {
        path: './storybook',
        filename: '/storybook/[name].[hash].bundle.js',
        publicPath: '/storybook/',
      },
      ...config,
    };

    return updatedConfig;
  },
};
```
* When I remove this `webpackFinal`, it also doesn't work (for an "out of the box" attempt)

Any help would be much appreciated!

**Comment by ndelangen** [comment]
@gvinter I'm unsure what's going on..

We use this ourselves:
https://next--storybookjs.netlify.com/cra-ts-essentials/

In the we have storybook running in a sub-dir without special config.
This **should** work out of the box.

**Comment by gvinter** [comment]
We got it sorted on our side. The `<base>` element was the way to go, no webpack alternations needed.

**Comment by marr** [comment]
The `base` solution seems to work fine for production (static) builds. But how do you get the dev server working with it?

**Comment by patsplat** [comment]
@marr If the web server doesn't enforce the trailing slash add a redirect to `manager-head.html`:

```
<script>
if (window.location.pathname == "/storybook") {
  window.location.pathname = "/storybook/"
}
</script>
```

**Comment by evanjmg** [comment]
Any solution for local dev? adding it on build is quite hacky

**Comment by AshleyDawson** [comment]
Very much a hack, but you can try:

```bash
build-storybook -o public/storybook && sed -i 's/<head>/<head><base href="\/storybook\/">/g' public/storybook/index.html
```

**Comment by filipemir** [comment]
Another hacky workaround that may work for some setups: if you are using a server to serve the static storybook files you can likely also use it to interpolate the base URL values into the HTML template. We set it up like this on our end, using express:
```
<!-- .storybook/manager-head.html -->
<base href="{{baseStorybookPath}}" />
```
And in our express server:
```
 app.get("/storybook", (req, res) => {
    res.render("storybook-static/index", {
      baseStorybookPath: "/storybook/"
    })
  })
  
   app.use(
    "/storybook/",
    express.static(path.join(__dirname, "storybook-static"))
  )
```
This seems to work because the `{{baseStorybookPath}}` value is not interpolated during local development, which results in an invalid `<base>` tag which is ignored

**Comment by MXTcomunica** [comment]
If you want to inject the `base` rule only for the production (static) builds, and leave the dev server untouched, you have to:

1. do **NOT** use the `.storybook/manager-head.html` file
2. add a `managerHead` preset in your `main.js` file and inject the `base` there, checking for `confType` condition, like this: 
```
module.exports = {
  managerHead: (head, { configType }) => {
    if (configType === 'PRODUCTION') {
      return (`
        ${head}
        <base href="/shared-ui/">
      `);
    }
  },
} 
```

Ref: #13432

**Comment by Marcus-Rise** [comment]
> If you want to inject the `base` rule only for the production (static) builds, and leave the dev server untouched, you have to:
> 
> 1. do **NOT** use the `.storybook/manager-head.html` file
> 2. add a `managerHead` preset in your `main.js` file and inject the `base` there, checking for `confType` condition, like this:
> 
> ```
> module.exports = {
>   managerHead: (head, { configType }) => {
>     if (configType === 'PRODUCTION') {
>       return (`
>         ${head}
>         <base href="/shared-ui/">
>       `);
>     }
>   },
> } 
> ```
> 
> Ref: #13432

thank you so much, it finally works! :)

**Comment by DarioRega** [comment]
> If you want to inject the `base` rule only for the production (static) builds, and leave the dev server untouched, you have to:
> 
> 1. do **NOT** use the `.storybook/manager-head.html` file
> 2. add a `managerHead` preset in your `main.js` file and inject the `base` there, checking for `confType` condition, like this:
> 
> ```
> module.exports = {
>   managerHead: (head, { configType }) => {
>     if (configType === 'PRODUCTION') {
>       return (`
>         ${head}
>         <base href="/shared-ui/">
>       `);
>     }
>   },
> } 
> ```
> 
> Ref: #13432

Facing the same issue here, however, my path is dynamic, so i've tried this
```
<base href="${document.location.pathname}">
```
But i got build errors : _TypeError: previewBuilder.bail is not a function_

Basically i have a root website where i serve the stable branch (https://styleguide.hackventures.co) and it works fine, but i also deploy previews environments on each pull requests via my CI.

And when i say that the url is dynamic it means that i slugify the branch name (feature/button-xyz -> feature-button-xyz) and upload it via ssh to https://styleguide.hackventures.co/preview/${slugified-branch-name}

And i can't make it work...

Before your solution i add @jontansey endless loading with this error :
_Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec._

And locally (without the serve command) i had CORS errors...

**Comment by emosheeep** [comment]
# Summaries of above

- If you want to **change the path of assets inside the `index.html`**, you should edit `managerWebpack` whether you used webpack or vite. Because storybook's main frame is built with webpack, `managerWebpack` is used to change its configurations.

- If you want to **change the path of assets of `iframe.html`**, you should edit `webpackFinal` or `viteFinal` according to which tool you're using.

After above, you will find that your storybook main frame appears but the stories(iframe.html) doesn't. You should set global var `window.PREVIEW_URL` with `'${your subpath}/iframe.html'`, how to set it was referred above, you can create a new file named `manager-head.html` and write a script to modify or use `managerHead` function.

# Examples

Before deploying your websites to a subpath like `https://example.com/storybook/`:

```js

const base = '//cdn.example.com/storybook/'; // we usually upload assets to CDN

module.export = {
  ...
  // This is to change configurations of building process of storybook's main frame
  managerWebpack: (config, { configType }) => {
    if (configType === 'PRODUCTION') {
      config.output.publicPath = base;
    }
    return config;
  },
  managerHead: (head, { configType }) => {
    const injections = [
      `<link rel="shortcut icon" type="image/x-icon" href="${base}favicon.ico">`, // This set icon for your site.
      `<script>window.PREVIEW_URL = '${base}iframe.html'</script>` , // This decide how storybook's main frame visit stories 
    ]
    return configType === 'PRODUCTION'
      ? `${head}${injections.join('')}`
      : head
  },
  // Or webpackFinal
  async viteFinal(config, { configType }) {
    if (configType === 'PRODUCTION') {
      config.base = base
    }
    return config;
  }
  ...
}

```
