### ISSUE TITLE
Storysource Addon - better support for "create-react-app" based projects

### ISSUE THREAD

**Issue by shootermv** [storybookjs/storybook#7776]
Currently, according to the [docs](https://github.com/storybookjs/storybook/tree/master/addons/storysource) , for configure the addon you must use webpack configuration   
unfortunately, "create-react-app" is hiding the webpack config stuff under the hood, and for make the addon work you must find the way to somehow override it (to use "eject" for example)  
This can be not very easy especially for some newbies like me...

I wish - the configuration not to involve webpack (in case you using create-react-app)- as it does with other addons  
If that is possible - it will be great!
Thanks

**Comment by stearruda** [comment]
I have the same question about that.
Is there any workaround?

**Comment by shilman** [comment]
I think the workaround is to configure storysource with webpack?

**Comment by stearruda** [comment]
Sorry @shilman !
I misunderstood that the `webpack.config.js` on `.storybook` it's an extension from the default CRA's `webpack.config.js` therefore can be customized.

Reading the docs gave me the 'click' to try.

Following the steps from addon Storysource's README I can successfully see the story :smiley: 

Thanks!
