### ISSUE TITLE
build examples/angular-cli fails

### ISSUE THREAD

**Issue by yrong** [storybookjs/storybook#7779]
**Describe the bug**
➜  angular-cli git:(next) ✗ ng build
@angular/compiler-cli@7.2.15 requires typescript@'>=3.1.1 <3.3' but 3.5.3 was found instead.
Using this version can result in undefined behaviour and difficult to debug problems.

Please run the following command to install a compatible version of TypeScript.

    npm install typescript@">=3.1.1 <3.3"

To disable this warning run "ng config cli.warnings.typescriptMismatch false".

 93% after chunk asset optimization SourceMapDevToolPlugin main.js generate Sour 93% after chunk asset optimization SourceMapDevToolPlugin polyfills.js generate 93% after chunk asset optimization SourceMapDevToolPlugin runtime.js generate S 93% after chunk asset optimization SourceMapDevToolPlugin styles.js generate So 93% after chunk asset optimization SourceMapDevToolPlugin main.js attach Source 93% after chunk asset optimization SourceMapDevToolPlugin polyfills.js attach S 93% after chunk asset optimization SourceMapDevToolPlugin runtime.js attach Sou 93% after chunk asset optimization SourceMapDevToolPlugin styles.js attach Sour                                                          
Date: 2019-08-16T03:16:47.248Z
Hash: 09dbb2241678256e0c33
Time: 2886ms
chunk {main} main.js, main.js.map (main) 633 bytes [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 2.19 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.08 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 19.9 kB [initial] [rendered]

ERROR in /ssd/mynode/storybook/node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/jit-polyfills.js
Module not found: Error: Can't resolve 'core-js/es7/reflect' in '/ssd/mynode/storybook/node_modules/@angular-devkit/build-angular/src/angular-cli-files/models'
ERROR in The Angular Compiler requires TypeScript >=3.1.1 and <3.3.0 but 3.5.3 was found instead.

**To Reproduce**
1. yarn install
2. cd examples/angular-cli
3. ng build

**Expected behavior**

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System:**
➜  angular-cli git:(next) ✗ npx -p @storybook/cli@next sb info
[BABEL] Note: The code generator has deoptimised the styling of /home/ronyang/.npm/_npx/10956/lib/node_modules/@storybook/cli/node_modules/lodash/lodash.js as it exceeds the max of 500KB.

Environment Info:

  System:
    OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.17.3 - ~/.yarn/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
  Browsers:
    Chrome: 73.0.3683.75

**Additional context**

**Comment by shilman** [comment]
@ndelangen @kroeder I'm not sure if this is an angular problem or a core-js problem? Or both?

**Comment by yrong** [comment]
@shilman  seems upgrade angular devDependencies  can fix it 

`
"devDependencies": {
    "@angular-devkit/build-angular": "^0.802.2",
    "@angular/cli": "^8.2.2",
　...
`

`
➜  angular-cli git:(next) ✗ ng build
                                                                               p
chunk {main} main.js, main.js.map (main) 10.6 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 450 kB [initial] [rendered]
chunk {polyfills-es5} polyfills-es5.js, polyfills-es5.js.map (polyfills-es5) 495 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.09 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 20.1 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 3.56 MB [initial] [rendered]
Date: 2019-08-16T14:22:16.229Z - Hash: ffc76101055e0548a7fd - Time: 12062ms

`

**Comment by kroeder** [comment]
FYI I'm in the middle of updating the example to angular 8
https://github.com/storybookjs/storybook/pull/7747

But our runners need to run on node 10 first. 
CC @ndelangen

**Comment by shilman** [comment]
@kroeder I think we're upgraded to node 10 now 💯

**Comment by kroeder** [comment]
can be closed; it got fixed a while ago
