### ISSUE TITLE
CSF Stories with MDX Docs recipe not working

### ISSUE THREAD

**Issue by joeycozza** [storybookjs/storybook#7810]
I am trying to follow the Storybook Docs recipe located [here](https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/recipes.md#csf-stories-with-mdx-docs) to write csf stories, and mdx docs.

When I follow the recipe and I have an mdx file with NO `<Meta>` tag, I get this error
![Screen Shot 2019-08-19 at 3 18 52 PM](https://user-images.githubusercontent.com/3885959/63300123-b2aad800-c294-11e9-8ff5-9da2273ce153.png)

In the docs [located here for Documentation-Only MDX](https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/mdx.md#documentation-only-mdx) it says 
>If you don't define a Meta, you can write Markdown and associate with an existing story. See "CSF Stories with MDX Docs".

BUT from what I can tell, I am forced to have a <Meta> tag in order for storybook to be happy right now.

If I add a <Meta> tag where the title is exactly the same as the Story's default export, then I get the `Duplicate title 'Button' used in multiple files; use unique titles or combine 'Button' stories into a single file.` error message.

If I add a <Meta> tag where the title is different, then I get a Documentation-Only MDX "story" show up on the left, which I don't want.  

## Reproduction
I have a little repo [this specific branch](https://github.com/joeycozza/addon-info-bug-repro/tree/tryingNoMetaTagMdx) where I am trying to make csf stories with mdx docs work. 
If you run storybook, you'll see the error when trying to follow the recipe exactly.

**Comment by shilman** [comment]
Whoopee!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-beta.37 containing PR #7814 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by ahmetkuslular** [comment]
hi @shilman, i have the same error
**version:** 5.2.8

**Comment by atanasster** [comment]
@ahmetkuslular you should not name your mdx file as a `button.stories.mdx` (in this case the mdx compiler in storybook will be looking for a Meta tag) but rather `button.mdx`. You can check CSF stories with arbitrary MDX for more info:
https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/recipes.md#csf-stories-with-arbitrary-mdx

**Comment by ahmetkuslular** [comment]
> @ahmetkuslular mdx dosyanızı bir ad olarak adlandırmamalısınız `button.stories.mdx`(bu durumda hikaye kitabındaki mdx derleyicisi bir Meta etiketi arayacaktır) `button.mdx`. CSF hikayelerini daha fazla bilgi için rastgele MDX ile kontrol edebilirsiniz:
> https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/recipes.md#csf-stories-with-arbitrary-mdx

i did as described. but this time I just uploaded the stories file. Doc (mdx) file did not load.

`configure(require.context("../src", true, /\.stories\.(js)$/), module);`

I removed mdx in this section.
