### ISSUE TITLE
Add support for vanilla webcomponents without any third-party-support or -enhancement like Polymer

### ISSUE THREAD

**Issue by franktopel** [storybookjs/storybook#7815]
I really appreciate the broad support for alot of frameworks and libraries, yet I sorely miss a version that is meant to be used for vanilla webcomponent development, without any supporting or enhancing libraries like Polymer. Just plain ESNext Code written for browsers that can run the code _as-is_ including full support for ES modules, private class properties and methods, in short: state-of-the-art web component development.

On our project so far we've been using Fabricator for the job - both  as an asset building stack, and as a component showcasing environment. Especially for the latter we're less-than-happy with it.

**Are you able to assist bring the feature to reality?**
I probably cannot, because I'm yet to take a look behind the curtains of Storybook, but to the best of my abilities and knowledge, I'd be willing to help.

**Comment by shilman** [comment]
cc @lonyele 😸

**Comment by lonyele** [comment]
@franktopel Hi! Have you checked `app/html` which supports rendering plain html on Storybook. [HTML guide](https://storybook.js.org/docs/guides/guide-html/) If what you `return` is a `plain` html then it should work without a problem(btw if you want state-of-the-art, you can also [setup Typescript](https://storybook.js.org/docs/configurations/typescript-config/) with this `app/html`) 

Just a side note, I know it can be little confusing but Polymer or other web-components related framework/compiler supports here at Storybook are kind of a wrapper that converts any framework specific code to pure web-components

I hope I answered your question?

**Comment by lzygmanski** [comment]
@lonyele 
It is working when you have this:
```js
.add('with emoji', () => {
	const button = document.createElement('custom-webcomponent-button');
	button.clsss= 'super-class';
	return button;
})
```

but in this case there is some issue:
```js
.add('with emoji', () => (
 <custom-webcomponent-button class="super-class" />
))
```
Error: ReferenceError: React is not defined

**Comment by Hypnosphi** [comment]
`@storybook/html` is the recommended solution for everything vanilla

**Comment by kylewelsby** [comment]
It looks like this is going to be a thing in 5.3.0

See [v5.3.0-alpha.34 WebComponents Kitchen Sink](https://github.com/storybookjs/storybook/tree/v5.3.0-alpha.34/examples/web-components-kitchen-sink)

**Comment by reno1979** [comment]
> It looks like this is going to be a thing in 5.3.0
> 
> See [v5.3.0-alpha.34 WebComponents Kitchen Sink](https://github.com/storybookjs/storybook/tree/v5.3.0-alpha.34/examples/web-components-kitchen-sink)

This is no vanilla web component, it is using litHTML etc
