### ISSUE TITLE
--ci no longer shows startup information

### ISSUE THREAD

**Issue by ghengeveld** [storybookjs/storybook#7821]
When starting storybook with the `--ci` flag, the startup information is no longer displayed. This problem was introduced here: https://github.com/storybookjs/storybook/pull/6949

**Comment by shilman** [comment]
Jeepers creepers!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-beta.38 containing PR #7822 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
