### ISSUE TITLE
Link to example in storybook UI not working

### ISSUE THREAD

**Issue by tl-caoan-le** [storybookjs/storybook#7825]
The [link](https://github.com/storybookjs/storybook/blob/next/lib/ui/example) provided in this [readme](https://github.com/storybookjs/storybook/blob/next/lib/ui/README.md) is not working.

Could this be fixed please? It would be really helpful to see an example of the use of @storybook/ui

Thanks

**Comment by arthurdenner** [comment]
@shilman, is this example available somewhere? I couldn't find it anywhere.
