### ISSUE TITLE
addon-info throws error with styled-components

### ISSUE THREAD

**Issue by adammlr** [storybookjs/storybook#7834]
**Describe the bug**
The withInfo addon throws a javascript error when attempting to render prop documentation for styled-components

**To Reproduce**
1. clone https://github.com/adammlr/storybook-bug
2. yarn storybook
3. No errors on the console
4. Click on Button - With Text Story
5. Javascript error in console (see below) and Props are not documented fully (compare to Container story)

Error: checkPropTypes.js:20 Warning: Failed prop type: Invalid prop `type` of type `object` supplied to `TableComponent`, expected `function`.
    in TableComponent (created by Story)

**Expected behavior**
Prop Type documentation generated without error

**Screenshots**
![image](https://user-images.githubusercontent.com/1544426/63456858-72bf2e80-c415-11e9-958e-2677cd9b6cf9.png)
![image](https://user-images.githubusercontent.com/1544426/63456912-92565700-c415-11e9-8be0-0185b98d4ac6.png)

**Code snippets**
```
import styled from "styled-components";
import PropTypes from "prop-types";

const Button = styled.button`
  background: white;
  border: solid 1px black;
  color: black;
`;

Button.displayName = "Button";
Button.propTypes = {
  size: PropTypes.oneOf(["small", "large"])
};

export default Button;
```
```
storiesOf("Container", module)
  .addDecorator(withInfo)
  .add("with text", () => <Container>Container</Container>);

storiesOf("Button", module)
  .addDecorator(withInfo)
  .add("with text", () => (
    <Button onClick={action("clicked")}>Hello Button</Button>
  ));

```
**System:**
  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 8.12.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.13.0 - C:\Program Files\nodejs\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    @storybook/addon-actions: ^5.1.11 => 5.1.11
    @storybook/addon-info: ^5.1.11 => 5.1.11
    @storybook/addon-links: ^5.1.11 => 5.1.11
    @storybook/addons: ^5.1.11 => 5.1.11
    @storybook/react: ^5.1.11 => 5.1.11

**Additional context**

**Comment by JBustin** [comment]
Same mistakes, with latest of storybook and add-ons (info, knobs, storyshot).
I just add `withInfo` decorator, 3 warnings `Invalid prop ...` appear : 

![Capture d’écran 2019-08-22 à 16 00 56](https://user-images.githubusercontent.com/2632709/63520947-d9b41480-c4f5-11e9-9722-4211faa2b9f0.png)

**Context :** 

```
    "@storybook/addon-info": "5.1.11",
    "@storybook/addon-knobs": "5.1.11",
    "@storybook/addon-storyshots": "5.1.11",
    "@storybook/react": "5.1.11",
```

**Comment by shilman** [comment]
`Addon-info` is being superceded by `addon-docs`, which fixes a bunch of bugs and is easier to maintain. Please give it a try! https://medium.com/storybookjs/storybook-docspage-e185bc3622bf

**Comment by JBustin** [comment]
@shilman thanks for the information.
But it's for Storybook 5.2 beta (which is not the latest).

**Comment by shilman** [comment]
@JBustin will be released this month

**Comment by adammlr** [comment]
Closing due to moving to addon-docs
