### ISSUE TITLE
Addon-docs: Preview code of imported html component in MDX

### ISSUE THREAD

**Issue by alazurenko** [storybookjs/storybook#7843]
Dear maintainers, 

I've faced with an issue of not able to preview code of imported html component. 
It is possible to see the preview of live component but when I expand `show code` I see the string representation of import, in case below it is `html`. 

**config.js**
```js
import { configure } from "@storybook/html";
configure(require.context('../src', true, /\.stories\.(js|mdx)$/), module);
```

**button.html**
```html
<button class="my-button">Default</button>
```

**button.stories.mdx**
```jsx
import { Meta, Story, Preview } from "@storybook/addon-docs/blocks";
import html from "./button.html";

<Meta title="Component|Button" />
<Preview>
  <Story name="default">
    {html}
  </Story>
</Preview>
```

Contrary, If I'd use html directly in the story I'm getting error directly in live preview:
`Expecting an HTML snippet or DOM node from the story: "default" of "Component|Button".` but able to see code.

**button.stories.mdx**
```jsx
<Meta title="Component|Button" />
<Preview>
  <Story name="default">
    <button class="my-button">Default</button>
  </Story>
</Preview>
```

Versions 
```
"@storybook/addon-docs": "^5.2.0-beta.39",
"@storybook/html": "^5.2.0-beta.39",
```

I appreciate your help. 
Thanks

**Comment by shilman** [comment]
@alazurenko please take a look at these examples: https://raw.githubusercontent.com/storybookjs/storybook/next/examples/html-kitchen-sink/stories/addon-docs.stories.mdx

**Comment by alazurenko** [comment]
@shilman Thanks for the snippet! 

In this case I don't have live preview of component and I'm getting this in code preview:
```
() => {
  const btn = document.createElement('button');
  btn.innerHTML = 'Hello Button';
  btn.addEventListener('click', action('Click'));
  return btn;
}
```
Whereas I'd like to see plain HTML for given input:  
```html
<button>Hello Button</button>
```

Would be great to display html code via import like in my first example.

**Comment by rootical** [comment]
Also running into this issue. By importing html I would expect a proper preview :)

**Comment by shilman** [comment]
@rootical that's not how storybook works, so it's not how docs works either. for now they are one-to-one equivalent

**Comment by alazurenko** [comment]
What is the correct way to override the source for the component's story in the preview?

For instance:
**button.stories.mdx**
```jsx
import button from "./button-standard.html";
import { Preview, Source } from "@storybook/addon-docs/blocks";

<Preview>
   <Story name="standard">
    {button}
   </Story>
    <Source>
       // this is what is going to be shown in the `Show Code` section.
    </Source>
</Preview>
```
Unfortunately, that way it doesn't work :/

**Comment by shilman** [comment]
@alazurenko coming soon: https://github.com/storybookjs/storybook/issues/7479

**Comment by gsedlacz** [comment]
If you struggle to find a working example:

SomeStory.stories.mdx
```
import {Meta, Story, Preview} from '@storybook/addon-docs'

<Meta title="Component/Button"/>

### Default Buttons

import buttonDefault from "../html/button/button-default.html"
export const Button = (args) => `${buttonDefault}`

<Preview mdxSource={`${buttonDefault}`}>
	<Story name="Default Buttons">
    {Button.bind(({}))}
	</Story>
</Preview>
```

../html/button/button-default.html
```
<input type="submit" value="Submitbutton" class="button">
```

Please let me know if there is an even simpler version than this.
