### ISSUE TITLE
Addon Docs: preview doesn’t change when switching between stories and not going back to canvas

### ISSUE THREAD

**Issue by CodeByAlex** [storybookjs/storybook#7846]
**Describe the bug**
When switching between stories, if you never click back on the canvas the components in iframes on the docs page don’t change. The Markdown does change however.

**To Reproduce**
1. Follow the steps to setup docs for angular found here: https://medium.com/storybookjs/storybook-docspage-e185bc3622bf
2. Go to a story
3. Click on docs tab
4. View component preview
5.  Go to different component story
6. See that the preview doesn’t change but the markdown does

**Expected behavior**
Docs preview should show the correct components based on the story

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System:**
Please paste the results of `npx -p @storybook/cli@next sb info` here.

Running angular 7 with latest version of addons ( will provide more info soon

**Additional context**

**Comment by shilman** [comment]
Repro'd on `examples/vue-kitchen-sink`. AFAICT it's only the first story, and it's only for iframe stories (i.e. non-react stories). Investigating.

**Comment by shilman** [comment]
Fixed in #7849

**Comment by shilman** [comment]
Yay!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-beta.40 containing PR #7849 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
