### ISSUE TITLE
Syntax highlighting for C#

### ISSUE THREAD

**Issue by cgatian** [storybookjs/storybook#7847]
**Describe the bug**
Code highlighting should work with C# in MDX stories

**To Reproduce**
1. Create a new story
2. Add code snippet using markdown code block syntax or with `SyntaxHighlighter`

**Expected behavior**
Code highlighted

**Screenshots**
![image](https://user-images.githubusercontent.com/1752170/63589392-fa707e80-c576-11e9-8533-00ee4d12c20b.png)

**Code snippets**
```
<SyntaxHighlighter language="C#" copyable={true}>
{`
 // A Hello World! program in C#.
        using System;
        namespace HelloWorld
        {
          class Hello
          {
            static void Main()
            {
              Console.WriteLine("Hello World!");
              // Keep the console window open in debug mode.
              Console.WriteLine("Press any key to exit.");
              Console.ReadKey();
            }
          }
        }
`}
</SyntaxHighlighter>

```

**System:**
Environment Info:

  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  Binaries:
    Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    @storybook/addon-a11y: ^5.2.0-beta.38 => 5.2.0-beta.38
    @storybook/addon-actions: ^5.2.0-beta.38 => 5.2.0-beta.38
    @storybook/addon-docs: ^5.2.0-beta.38 => 5.2.0-beta.38
    @storybook/addon-knobs: ^5.2.0-beta.38 => 5.2.0-beta.38
    @storybook/addon-links: ^5.2.0-beta.38 => 5.2.0-beta.38
    @storybook/addon-notes: ^5.2.0-beta.38 => 5.2.0-beta.38
    @storybook/addon-viewport: ^5.2.0-beta.38 => 5.2.0-beta.38
    @storybook/addons: ^5.2.0-beta.38 => 5.2.0-beta.38
    @storybook/angular: ^5.2.0-beta.38 => 5.2.0-beta.38

**Comment by shilman** [comment]
We're using `react-syntax-highlighter` internally.

Can you try adding the folllowing to `.storybook/config.js`:

```js
import { registerLanguage } from 'react-syntax-highlighter/prism-light';
import csharp from 'react-syntax-highlighter/languages/prism/csharp';

registerLanguage('C#', csharp);
```

I don't have a good sense for the tradeoff of including this out of the box vs. making it a user configuration like the above.

**Comment by cgatian** [comment]
Thank you for the reply. I will try your suggestion. 

Sorry if this request was misguided, I assumed when I found a C# story for SyntaxHighlighter in the source this should just work.

**Comment by shilman** [comment]
Hahaha, I just checked and the `C#` story is called ... "unsupported"!!

Right now we include `jsx`, `bash`, `css` in addition to `react-syntax-highlighter`'s defaults (whatever those are?). I'm guessing the reason we don't include more is about tree-shaking (@ndelangen confirm?) and that it's probably enough to document how to add your own.

**Comment by ndelangen** [comment]
@cgatian I added that story to showcase what happens if a language is given, but it's not installed.

**Comment by epiknut** [comment]
> We're using `react-syntax-highlighter` internally.
> 
> Can you try adding the folllowing to `.storybook/config.js`:
> 
> ```js
> import { registerLanguage } from 'react-syntax-highlighter/prism-light';
> import csharp from 'react-syntax-highlighter/languages/prism/csharp';
> 
> registerLanguage('C#', csharp);
> ```

Is there a different approach for including csharp in SyntaxHighlighter these days? I'm having trouble getting something like this to work in the current version (6.2.9) of storybook.

**Comment by shilman** [comment]
@epiknut We switched over to ESM in 6.2 which enables tree shaking, which removes hundreds of unused languages from the bundle & reduces its size/improves performance dramatically. i think to get custom highlighting back we'll probably need to switch to a different highlighting library

**Comment by epiknut** [comment]
@shilman I see. Good to know, thanks for the reply :)

**Comment by ndelangen** [comment]
@epiknut  @shilman this is how users can register extra languages:
https://github.com/storybookjs/storybook/blob/8b2517f2687ab808dbdac990320df4f42a609e93/lib/components/src/syntaxhighlighter/syntaxhighlighter.tsx#L39-L49

**Comment by i-am-the-slime** [comment]
@ndelangen I can't make this work (in v7 alpha), did it break?

**Comment by ndelangen** [comment]
Yeah i think this indeed breaks in 7.0.

We'll have to come up with a better solution for this.
