### ISSUE TITLE
React Native - Stories aren't displaying in browser (5.1.1)

### ISSUE THREAD

**Issue by alexakasanjeev** [storybookjs/storybook#7858]
**Describe the bug**
My stories don't appear in browser.
On (android) simulator i can see the stories
I have also tried running `adb reverse tcp:7007 tcp:7007` this command and nothing happens
I even changed the port then also nothing happened

**To Reproduce**
1. clone the repo `https://github.com/alexakasanjeev/magento_react_native.git`
2. cd into the folder
3. change branch `git checkout  bug/storybook-server-not-working`
4. run `npm run storybook`
5. in another terminal run `npm start`
6. in another terminal run `react-native run-android`
7. stories are visible in emulator put not on browser

**Expected behavior**
It should have shown the stories on the browser

**Screenshots**
![storybook](https://user-images.githubusercontent.com/13250741/63635879-5d503b80-c685-11e9-9218-ae09eb5f030b.png)

**Code snippets**
**package.json**
```[js]
{
  "name": "magento_react_native",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest",
    "prestorybook": "rnstl",
    "storybook": "start-storybook -p 7007"
  },
  "dependencies": {
    "@react-native-community/async-storage": "^1.3.0",
    "axios": "^0.18.0",
    "prop-types": "^15.7.2",
    "react": "16.8.3",
    "react-native": "0.59.5",
    "react-native-gesture-handler": "^1.1.0",
    "react-native-swiper": "^1.5.14",
    "react-native-vector-icons": "^6.4.1",
    "react-navigation": "^3.3.2",
    "react-navigation-header-buttons": "^2.2.0",
    "react-redux": "7.1.0-alpha.4",
    "redux": "^4.0.1",
    "redux-logger": "^3.0.6",
    "redux-saga": "^1.0.2"
  },
  "devDependencies": {
    "@storybook/addon-actions": "^5.1.11",
    "@storybook/react-native": "^5.1.11",
    "@storybook/react-native-server": "^5.1.11",
    "babel-core": "7.0.0-bridge.0",
    "babel-eslint": "^10.0.1",
    "babel-jest": "24.3.1",
    "babel-loader": "^8.0.6",
    "eslint": "^5.15.3",
    "eslint-config-airbnb": "^17.1.0",
    "eslint-plugin-import": "^2.16.0",
    "eslint-plugin-jsx-a11y": "^6.2.1",
    "eslint-plugin-react": "^7.12.4",
    "eslint-plugin-react-native": "^3.6.0",
    "jest": "24.3.1",
    "metro-react-native-babel-preset": "0.53.0",
    "react-native-storybook-loader": "^1.8.0",
    "react-test-renderer": "16.8.4"
  },
  "jest": {
    "preset": "react-native"
  },
  "config": {
    "react-native-storybook-loader": {
      "searchDir": [
        "./src"
      ],
      "pattern": "**/stories.js"
    }
  }
}

```

**System:**
```[bash]
Environment Info:

  System:
    OS: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 76.0.3809.87
    Firefox: 68.0.1
  npmPackages:
    @storybook/addon-actions: ^5.1.11 => 5.1.11 
    @storybook/react-native: ^5.1.11 => 5.1.11 
    @storybook/react-native-server: ^5.1.11 => 5.1.11 
  npmGlobalPackages:
    @storybook/cli: 5.0.11

```

**Additional context**
similar issue #6489

**Comment by shilman** [comment]
@alexakasanjeev Have you tried the latest 5.2-beta?

**Comment by sanjeevyadavIT** [comment]
no, do I need to update all these three dependencies to 5.2-beta
```[bash]
    "@storybook/addon-actions": "^5.1.11",
    "@storybook/react-native": "^5.1.11",
    "@storybook/react-native-server": "^5.1.11",
```

And what command do I need to run in order to get 5.2-beta
and most current version is `v5.2.0-beta.40` should I switched to that

**Comment by shilman** [comment]
Yeah all the storybook packages should be the same version. `npx npm-check-updates '/storybook/' -un` should upgrade your `package.json` and then use `npm` or `yarn` to install.

**Comment by sanjeevyadavIT** [comment]
did that, upgraded storybook to `5.2.0-beta40` stories are loading now but
**story not changing when clicking on any story from browser**

facing the same issue now as storybookjs/storybook#7723

checkout my repo here [storybook-error](https://github.com/alexakasanjeev/magento_react_native/tree/bug/storybook-server-not-working)

```[bash]
Environment Info:

  System:
    OS: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 76.0.3809.87
    Firefox: 68.0.1
  npmPackages:
    @storybook/addon-actions: ^5.2.0-beta.40 => 5.2.0-beta.40 
    @storybook/react-native: ^5.2.0-beta.40 => 5.2.0-beta.40 
    @storybook/react-native-server: ^5.2.0-beta.40 => 5.2.0-beta.40 
  npmGlobalPackages:
    @storybook/cli: 5.0.11

```

**Comment by jhau** [comment]
I have the same issue as @alexakasanjeev, when clicking on the link in the webpage, it doesnt change the story on device (or simulator).

**Comment by shilman** [comment]
Thanks @alexakasanjeev @jhau I've marked storybookjs/storybook#7723 as a high priority bug, so hopefully one of our RN maintainers can address it soon

**Comment by sanjeevyadavIT** [comment]
@shilman Just tested storybook 5.2.1, finally working fine, thank you

**Comment by abhishek1305** [comment]
i am facing the same issue while setting up my react-native project. I am unable to access stories from the browse. i am using storybook -v 5.3.9 .

**Comment by khrystynapochynok** [comment]
@shilman Having the same issue as described with v5.3.9.
Using storybook in react-native project and typescript.

**Comment by Gongreg** [comment]
Hey, I've created an issue in storybook for react native repository. The RN project was abandoned for some time but I am trying to get back to it again. I will be working on it on weekend and might have a chance to look into this issue.

**Comment by shilman** [comment]
@Gongreg you can transfer issues in the right-hand side underneath "lock conversation" and "pin issue". I'm transferring this one.
