### ISSUE TITLE
The preview iframe does not unload causing performance issues

### ISSUE THREAD

**Issue by marian-c** [storybookjs/storybook#7859]
**Describe the bug**

When you switch stories, the browser gets slower and slower; You'd have to be in a situation in which you'd easily observe the performance drop, see the steps below

**To Reproduce**
1. Create two stories, each with a canvas animation keeping the fps under 60
2. Load storybook and switch between the two stories
3. Observe the fps dropping more and more as each switch happens. It drops under the value that you'd see for any story after a hard refresh. 

**Expected behavior**

Performance should not be impacted by the fact that the iframe switches contents.

**System:**

Environment Info:
```
  System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4750HQ CPU @ 2.00GHz
  Binaries:
    Node: 10.10.0
    Yarn: 1.17.3
    npm: 6.4.1
  Browsers:
    Chrome: 76.0.3809.100
    Firefox: 66.0
    Safari: 12.1.2
  npmPackages:
    @storybook/addon-notes: ^5.1.11 => 5.1.11 
    @storybook/addon-storysource: ^5.1.11 => 5.1.11 
    @storybook/html: ^5.1.11 => 5.1.11 
```

**Additional context**

I think the iframe should rerender (if not remount) if the src changes. I've done some tests and [rerending](https://github.com/storybookjs/storybook/blob/feb21fc3f796ee319ef1138b8b79085064cb1830/lib/ui/src/components/preview/iframe.js#L40) the iframe component gets rid of the performance problems.

There are other circumstances that affect the performance of the iframe but this particular one will reach the final user (will be encountered on environments other then the dev's machine)

**Comment by ndelangen** [comment]
@marian-c do you have a reproduction for me?

It's easy to miss cleanup up after unmounting the component in the component code itself, that might be what's going on.

Storybook unmount the previous story then mounts the new one.

**Comment by marian-c** [comment]
@ndelangen This isn't dealing with React, but with html, observe the npm packages in the description
```
npmPackages:
    @storybook/addon-notes: ^5.1.11 => 5.1.11 
    @storybook/addon-storysource: ^5.1.11 => 5.1.11 
    @storybook/html: ^5.1.11 => 5.1.11 
```

Canvas animations add animation frames callbacks, and since the iframe of the story does not unload I suspect they keep piling up as you switch from story to story.

Also see the link to the code that mentions that iframes don't get _refreshed_ by design.

Now that I thing about it, a html story should get _pinged_ when it's about to be replaced by another one, so it has a chance to do the cleanup itself.

I'll try to give you a reproduction repo on of these days

**Comment by ndelangen** [comment]
Yes, whatever renders should clear itself when it gets unmounted/removed from the DOM.

I'm guessing in webcomponents-land or pure-html-world this is done via the platform APIs?
In framework-country this is usually part of the component API.

The assumption is in many modern application there won't be a refresh, ever.

Components should clean after themselves, not hope that at some point the mess they make gets cleaned up by something else.

Refreshing on every story render would be slow..

**Comment by marian-c** [comment]
> I'm guessing in webcomponents-land or pure-html-world this is done via the platform APIs?

Yes, I think so, I would typically use unload event on the window for cleaning up, but I don't think unload happens when you switch stories.

I guess MutationObserver would do the job here (haven't tested it).

**Comment by ndelangen** [comment]
> I don't think unload happens when you switch stories
Correct!

You can also use `useEffect` from `@storybook/client-api`.

```js
import { useEffect } from '@storybook/client-api';

export const Logger = () => {
  useEffect(() => {
    // executes when switched to this story
    return () =>
      // executes when switched away from this story
  }, []);

  return `
    <div>
      some html
    </div>
  `;
};
```

**Comment by ndelangen** [comment]
I don't think there's something actionable for storybook here, We can't possibly know what the user's components do, so there's no way to know how to clean up.

We're not changing to do a full refresh on story change.
