### ISSUE TITLE
Do a full page reload on asset change

### ISSUE THREAD

**Issue by liron-navon** [storybookjs/storybook#7864]
**Is your feature request related to a problem? Please describe.**
I'm using stencil with storybook/polymer - and I wish to reload the page when the stencil bundle change.

**Describe the solution you'd like**
I'm calling storybook like this: `start-storybook -p 9001 -c .storybook -s www`
When files in `www` change, storybook peek it up in the console but don't reload the page, I would like an option to make it reload on asset change.

**Are you able to assist bring the feature to reality?**
yes

**Additional context**
As you see, HMR picks the changes, but it won't reload the page when they happen.

![Screenshot 2019-08-26 at 12 47 01](https://user-images.githubusercontent.com/18119833/63685452-a0361e80-c7ff-11e9-8900-25c6a2806954.png)

**Comment by Hypnosphi** [comment]
HMR is about updating the page without reloading it. Can you share your setup on GitHub so that I could take a look?

**Comment by liron-navon** [comment]
@Hypnosphi Any setup would do, but I'm not talking about the code that HMR compiles and replace, I'm talking about assets like images and video - when those change, it would be nice to have a full page reload to show the changes - even make it optional like having another flag `-reload-on-public-directory-change true` or something like that.
