### ISSUE TITLE
React Native - Unable to change story via browser

### ISSUE THREAD

**Issue by tedcurrent** [storybookjs/storybook#7873]
**Describe the bug**
The "in app" Storybook navigator works just fine, but with browser, when changing the story, the app screen goes blank with `Please open the Storybook UI...` text. Updated from Storybook 4 to 5. See details and screenshots below.

**To Reproduce**
1. `react-native run-ios --scheme 'Storybook'` (start simulator and set storybook env)
2. `start-storybook`
3.  See initial story in app, all good.
4. Go to `http://localhost:7007`
5. Change story
6. App is blank (there MIGHT be a small flicker of the story changed to)

**Expected behavior**
Should be able to change stories.

**Screenshots**
`Initial view (all good)`
![Screenshot 2019-08-27 10 20 40](https://user-images.githubusercontent.com/7895034/63749624-8276c100-c8b4-11e9-8e56-e095f41d55c3.png)

`After changing story (broken)`
![Screenshot 2019-08-27 10 20 56](https://user-images.githubusercontent.com/7895034/63749627-8571b180-c8b4-11e9-9f20-47dfa6f9d6c1.png)
**Code snippets**
`storybook/index.js`
```
import React, { Component } from 'react'
import { AppRegistry, View } from 'react-native'
import { getStorybookUI, configure } from '@storybook/react-native'

// import stories
configure(() => {
  require('./stories')
}, module)

const StorybookUIRoot = getStorybookUI({ port: 7007, onDeviceUI: false })

class StorybookUIHMRRoot extends Component {
  render() {
    return (
      <View style={{ backgroundColor: 'white', flex: 1 }}>
        <StorybookUIRoot />
      </View>
    )
  }
}

AppRegistry.registerComponent('AppName', () => StorybookUIHMRRoot)
export default StorybookUIHMRRoot

```

`index.ios.js`
```
import Config from 'react-native-config'

import 'app/App'

if (Config.STORYBOOK_ENABLED === 'true') {
  require('./storybook')
}
```

**System:**
```
System:
    OS: macOS 10.14.4
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    Yarn: 1.17.3 - ~/.yarn/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 76.0.3809.100
    Firefox: 62.0.2
    Safari: 12.1
  npmPackages:
    @storybook/addon-actions: ^5.1.11 => 5.1.9 
    @storybook/addon-links: ^5.1.11 => 5.1.9 
    @storybook/react-native: ^5.1.11 => 5.1.9 
    @storybook/react-native-server: ^5.1.11 => 5.1.9 
    @storybook/theming: ^5.1.11 => 5.1.9 
```
**Additional context**
Everything worked on `"@storybook/react-native": "^4.1.18"`
After updating to `"@storybook/react-native": "^5.1.11"` it broke

**Comment by shilman** [comment]
Closing as duplicate to #7723

**Comment by tedcurrent** [comment]
@shilman thanks for responding so fast! I don't see how this is a duplicate, but these issues may be related I guess. I'm not even sure if this is a similar issue to #7723 as we don't have any issues with the web browser, just the app showing the storybook "Please" overlay when trying to interact with it via browser.
