### ISSUE TITLE
Addon-docs disables @storybook/addon-knobs

### ISSUE THREAD

**Issue by CheezeCoder** [storybookjs/storybook#7880]
**Describe the bug**

When using the new CSF form for creating stories with knobs, the knobs functionality will be disabled after switching from the docs view back to the canvas view. 

This means that on any reload or story switch the knobs addon will start working again.  But if before or without reloading the page or switching to another story you go to the docs view and then back to the canvas view your knobs will stop working.

This is using a typescript environment. I haven't tested this in an environment without typescript so I can't say for certain if its related or not. 

**To Reproduce**
1. Use the latest @next branch
2. Create a story in CSF form with knobs
3. Start Storybook
4. Test to make sure knobs works on the initial render
5. Switch to the docs view via the toolbar for the component.
6. Switch back to the canvas view via the toolbar
7. Your knobs will no longer work.

**Expected behavior**
Knobs functionality should continue working regardless of view state. 

**Screenshots**
Hard to show with screen shots. 

**Code snippets**
A link to a repo showcasing the example:  [here](https://github.com/CheezeCoder/storybook-monorepo-woes)

**System:**
Environment Info:

  System:
    OS: Windows 10
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
  Binaries:
    Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.267.0

**Additional context**
Have only tested this in Chrome, and there are no console errors.

**Comment by CheezeCoder** [comment]
Haven't tested that yet @enagy27  but you could clone and test it out on this repo as well if you want.  I don't have time to do it this week.

**Comment by shilman** [comment]
@ndelangen and I took a long look at this and tried a bunch of different approaches to fixing the problem.

A few things we observed:

1) the storybook preview hooks API seems to be messed up:

  - when i render a story in canvas/"story" mode, it the knobs addon CONNECTS to the channel
  - when i switch to "docs" it DISCONNECTS
  - when i switch back to "story" it CONNECTS and then immediately DISCONNECTS

2) in docs mode, all the stories are executed with their decorators, and it adds ALL of the knobs to the knobs store (which is a singleton)

If we add this code to to the `knob` base object, it seems to work:

```js
  knob<T extends KnobType = any>(name: string, options: Knob<T>): Mutable<Knob<T>['value']> {
    const query = qs.parse(document.location.search, { ignoreQueryPrefix: true });
    const { viewMode } = query;
    if (viewMode !== 'story') {
      return options.value;
    }
    // normal knob behavior
```

**Comment by shilman** [comment]
Yowza!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-rc.6 containing PR #7992 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Still need to disable `knob` when `viewMode` !== 'story', using `useStoryContext` hook, IF `viewMode` was in the context. Cc @ndelangen

**Comment by toadkicker** [comment]
I'm still seeing this problem in the 5.3+ branches.

**Comment by RuneKR** [comment]
Hey @shilman it is not just a problem for docs-mode. When i run the following in one story:

When i have the following story: 

```
import { getStorybook } from '@storybook/react'
const myStory = getStorybook()[0].stories[0].render // can pick any story

export {myStory}
```

and then navigate to that story i have the same issue. Perhaps it is lifecycle that is broken? I know the use case seems a bit strange. I can provide a full repo later this week

**Comment by shilman** [comment]
@RuneKR thanks -- looking forward to your repro! tho, i must say that example looks pretty strange

**Comment by RuneKR** [comment]
Just posting this as i get prepare the repo. I am trying to create my own "docs mode" as the current storybook direction unfortunately won't cover my use cases. I need to be able to include both sass/css and tsx in the code example.

```
import { Button } from '@my-ui/button'
import { action } from '@storybook/addon-actions'
import * as React from 'react'
import { getStorybook } from '@storybook/react'
import { linkTo } from '@storybook/addon-links'
import { createExampleBlock } from '../../components/createExampleBlock'

import PrimaryExample from './examples/primary'
import SecondaryExample from './examples/secondary'
import TextExample from './examples/text'

export default {
    component: Button,
    title: 'Component Demos|Buttons',
    parameters: { options: { showPanel: true } }
}

const description = 'My component'

export const Usage = () => (
    <ComponentDocs
        props={Button.__docgenInfo}
        kind={'Component Demos|Buttons'}
        description={description}
        title="Buttons"
    />
)

Usage.story = {
    parameters: { options: { showPanel: false } }
}

export const Primary = () => <PrimaryExample onClick={action('click')} />

const primaryCode = require('!raw-loader!./examples/primary/index.tsx')
const primarySass = require('!raw-loader!./examples/primary/style.module.scss')

Primary.story = {
    decorators: [createExampleBlock([{ type: 'typescript', code: primaryCode }, { type: 'sass', code: primarySass }])]
}

const ComponentDocs: React.FunctionComponent<IComponentDocsProps> = props => {
    const { stories } = getStorybook().find(data => data.kind === props.kind)

    // remove first 'usage' story
    const usageStory = stories.findIndex(value => value.name === 'Usage' || value.name === 'usage')
    stories.splice(usageStory, 1)

    return (
        <div>
            <div>
                <h1>{props.title + ' docs'}</h1>
                <p>{props.description}</p>
            </div>
            <div>
                {stories.map(story => (
                    <section key={story.name}>
                        <h2>{story.name}</h2>
                        <StoryBlock kind={props.kind} storyName={story.name}>
                            {story.render()}
                        </StoryBlock>
                    </section>
                ))}
            </div>
        </div>
    )
}

const StoryBlock = ({ kind, storyName, children }) => {
    const gotTOStory: any = linkTo(kind, storyName)

    return (
        <div>
            <div>
                <Button variant="text" onClick={gotTOStory}>
                    View Story
                </Button>
            </div>
            {children}
        </div>
    )
}

```

**Comment by shilman** [comment]
@RuneKR did you consider contributing those improvements to the current docs? both of those things sound like they'd be pretty easy to add.

Here's an issue for the import statement: https://github.com/storybookjs/storybook/issues/7772

And it's already possible to show CSS/SCSS in MDX, and probably also possible to configure it in DocsPage https://github.com/storybookjs/storybook/pull/8855

**Comment by RuneKR** [comment]
Yeah - Just trying to learn the internals of StoryBook first and thats where i encountered this issue.

**Comment by chris-pearce** [comment]
None of the addons that render in the bottom pane are displaying for me on `5.3.0-beta.15`. These are the addons that don't display:

- addon-knobs
- addon-a11y
- addon-actions
- addon-storysource

I'm using "info" addon whilst migrating to "docs".

**Comment by shilman** [comment]
@chris-verclytte

**Comment by chris-pearce** [comment]
@shilman yes tried that and still doesn't show. It's been like this for days. The bottom pane simply isn't showing.

**Comment by shilman** [comment]
@ndelangen and I looked at this and we can't repro it in the monorepo. Please open specific questions on a separate issue and we'll do our best to help you out!
