### ISSUE TITLE
Addon Docs: Icon Background Color Shouldn't Change

### ISSUE THREAD

**Issue by CodeByAlex** [storybookjs/storybook#7895]
**Describe the bug**
The background color on hover should not change but the icon color should

**To Reproduce**
Hover over an icon in docs mode using Docs Page

**Expected behavior**

**Screenshots**
![icon-bg-colors](https://user-images.githubusercontent.com/29763590/63850606-78130080-c962-11e9-9b2b-12280d8d5255.gif)

**System:**
Framework: Angular
All addons and packages on version 5.2.0-beta.43

**Comment by shilman** [comment]
@CodeByAlex is this still a problem? Not repro'ing on https://storybookjs.now.sh/

**Comment by CodeByAlex** [comment]
@shilman - It's not - Ill close it out
