### ISSUE TITLE
Performance regression between Storybook v3 and v5

### ISSUE THREAD

**Issue by kevinweber** [storybookjs/storybook#7907]
**Describe the bug**
As you know, many companies are using Storybook and some might have hundreds and thousands of variations in a single Storybook (and even more spread across several Storybooks). Storybook v5 is slower than its predecessors and has so far prevented us from upgrading to Storybook v5.

To test the regression, I've set up a new Storybook with the latest version and minimal customization. Then I've run it with different amounts of variations. Each variation holds ten stories:

- With just one variation (i.e. 10 stories), switching between stories happens nearly instantly.
- With 100 variations (i.e. 1000 stories), the animation frame task takes 400ms (see screenshot).
- With 1000 variations (i.e. 10,000 stories), my Chrome tab froze.

Related ticket: https://github.com/storybookjs/storybook/issues/6391

**To Reproduce**
I set up a [demo repo](https://github.com/kevinweber/storybook-large-demo) and [documented my methodology](https://paper.dropbox.com/doc/Storybook-5-Performance--Ajy6cFIZ6_b61QBr5VGTUxYDAg-inBHZ9u4PYSRCM643zCn5).

**Expected behavior**
It should not be an issue to have 10,000 variations in one Storybook.
A 1-3 second loading time for such large Storybooks is acceptable; a freezing Chrome tab isn't.

**Screenshot**
![image_preview](https://user-images.githubusercontent.com/2785791/63910582-32931980-c9dc-11e9-9e29-a67ff8ab88e9.png)

**Comment by shilman** [comment]
Thanks @kevinweber -- we're on it

**Comment by kevinweber** [comment]
That seems to be correct, yes. You should be able to reproduce the issue using the mentioned [demo repo](https://github.com/kevinweber/storybook-large-demo). The repo's readme includes instructions on how to generate a larger amount of variations if needed. I tested this three months ago and doubt that it has changed since then.

**Comment by jaredmahan** [comment]
I using angular 8 and the latest from storybook and I am having some very bad performance issues as well with very few stories. Switching takes upwards of 5 to 6 sec with only 3 stories each having on several variations.

**Comment by shilman** [comment]
Ooh-la-la!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-beta.47 containing PR #7910 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
@kevinweber I released `v5.2.0-beta.47` containing some low-hanging fixes that speed things up a bunch. I tried it out in your repo with ~10,000 stories. The initial load takes a few seconds, but the story switching is now fairly quick. Please let me know how this works for you, and thanks for the nice repro & methodology doc. Super helpful!

**Comment by kevinweber** [comment]
@shilman Thank you so much for this fix, super helpful! I haven't verified the fix yet but if there are still issues, you'll hear back from me in a few weeks once we'll be actively migrating to v5. Lots of ❤️for your work and the whole Storybook project.
