### ISSUE TITLE
puppeteer image snapshots not recognizing absolute paths of assets when running from static build

### ISSUE THREAD

**Issue by adirn15** [storybookjs/storybook#7911]
I have a static build of my storybook. when I run `jest --no-cache` it takes image snapshots of all my stories, but fails to render my static assets. 

storyshots.test.js: 
```
const chromeExecutablePath = process.env.CHROME_PATH;
const staticBuildPath = path.join(__dirname, '/build');

initStoryshots({
    suite: 'Image storyshots',
    test: imageSnapshot({
        storybookUrl: `file://${staticBuildPath}`,
        chromeExecutablePath
    })
});

```
my static files in the build directory tree:
```
-build
    - static
        - images
            * all my static assets (added with copy-webpack-plugin)
        - media
            * assets from direct imports in stories.js files (added by build-storybook)
```

for instance: 
```
storiesOf('button', module)
    .add('button test', () => {
        return <ButtonView><img src='/static/images/img.png'/> I'M A  BUTTON</ButtonView>
    })
```

fails to load the image from '/static/images/img.png' and the image snapshot output is:
![example](https://user-images.githubusercontent.com/13698539/63930922-ea680b80-ca5c-11e9-898b-8adabcff2cea.png)

if I change the storybook URL to a running instance of storybook it works, but I need it to work on a static build. any idea why this is happening?

**Comment by brandondurham** [comment]
Having the very same issue and haven’t found a solution.
