### ISSUE TITLE
In NX Workspace configured for Angular (possibly regular CLI project), storybook won't start if first project in angular.json is of type "library". 

### ISSUE THREAD

**Issue by tcoz** [storybookjs/storybook#7913]
In NX Workspace configured for Angular (possibly in regular Angular CLI project), if a project of type "library" is the first item in the projects list in angular.json, storybook will not start. 

Error:

WARN Broken build, fix the error below.
WARN You may need to refresh the browser.

ERR! TypeError: Cannot destructure property `options` of 'undefined' or 'null'.

If I move that project section below the project types of "application", everything is fine. 

Minimally, a clearer error saying "unrecognized project type: library" or some such might be helpful, ideally, ignore library project types (or any project type that would prevent storybook from running) regardless where in the projects collection it appears.

**Comment by shilman** [comment]
Possibly (probably?) related: #6978

**Comment by valentinpalkovic** [comment]
This should be fixed in SB 7.0. Please feel free to reopen it, if it is still an issue.
