### ISSUE TITLE
TypeError: Cannot read property 'lightest' of undefined

### ISSUE THREAD

**Issue by iamdriz** [storybookjs/storybook#7914]
I have installed Storybook Docs as per the documentation here: https://github.com/storybookjs/storybook/blob/next/addons/docs/README.md#installation

And I have used the Manual preset configuration.

When I view the Docs tab for any of my stories I get the following error:

```js
TypeError: Cannot read property 'lightest' of undefined
    at getScrollAreaStyles (http://localhost:6006/vendors~main.e02af6e0f1f31fb510a2.bundle.js:11822:78)
    at http://localhost:6006/vendors~main.e02af6e0f1f31fb510a2.bundle.js:41276:100
    at updateContextConsumer (http://localhost:6006/vendors~main.e02af6e0f1f31fb510a2.bundle.js:92999:19)
    at beginWork (http://localhost:6006/vendors~main.e02af6e0f1f31fb510a2.bundle.js:93187:14)
    at performUnitOfWork (http://localhost:6006/vendors~main.e02af6e0f1f31fb510a2.bundle.js:96827:12)
    at workLoop (http://localhost:6006/vendors~main.e02af6e0f1f31fb510a2.bundle.js:96867:24)
    at renderRoot (http://localhost:6006/vendors~main.e02af6e0f1f31fb510a2.bundle.js:96950:7)
    at performWorkOnRoot (http://localhost:6006/vendors~main.e02af6e0f1f31fb510a2.bundle.js:97857:7)
    at performWork (http://localhost:6006/vendors~main.e02af6e0f1f31fb510a2.bundle.js:97769:7)
    at performSyncWork (http://localhost:6006/vendors~main.e02af6e0f1f31fb510a2.bundle.js:97743:3)
```

Any ideas what the problem could be or where I could start looking to see the issue?

The packages used are as follows:
```js
    "@babel/core": "^7.4.5",
    "@storybook/addon-docs": "^5.2.0-beta.46",
    "@storybook/addon-knobs": "^5.2.0-beta.46",
    "@storybook/addon-notes": "^5.2.0-beta.46",
    "@storybook/html": "^5.2.0-beta.46",
    "babel-loader": "^8.0.6",
    "webpack": "^4.39.3"
```

The `config.js` file is as follows:

```js
import { addParameters, configure } from '@storybook/html';
import { themes } from '@storybook/theming';
import yourTheme from './yourTheme';
import { DocsPage, DocsContainer } from '@storybook/addon-docs/blocks';

// automatically import all files ending in *.stories.js
const req = require.context('../stories', true, /\.stories\.(js|mdx)$/);
function loadStories() {
  req.keys().forEach(filename => req(filename));
}

// Option defaults:
addParameters({
  docs: {
    container: DocsContainer,
    page: DocsPage
  },
  options: {
    /**
     * show story component as full screen
     * @type {Boolean}
     */
    isFullscreen: false,
    /**
     * display panel that shows a list of stories
     * @type {Boolean}
     */
    showNav: true,
    /**
     * display panel that shows addon configurations
     * @type {Boolean}
     */
    showPanel: true,
    /**
     * where to show the addon panel
     * @type {('bottom'|'right')}
     */
    panelPosition: 'bottom',
    /**
     * sorts stories
     * @type {Boolean}
     */
    sortStoriesByKind: false,
    /**
     * regex for finding the hierarchy separator
     * @example:
     *   null - turn off hierarchy
     *   /\// - split by `/`
     *   /\./ - split by `.`
     *   /\/|\./ - split by `/` or `.`
     * @type {Regex}
     */
    hierarchySeparator: /\/|\./,
    /**
     * regex for finding the hierarchy root separator
     * @example:
     *   null - turn off multiple hierarchy roots
     *   /\|/ - split by `|`
     * @type {Regex}
     */
    hierarchyRootSeparator: /\|/,
    /**
     * sidebar tree animations
     * @type {Boolean}
     */
    sidebarAnimations: true,
    /**
     * enable/disable shortcuts
     * @type {Boolean}
     */
    enableShortcuts: false,
    /**
     * show/hide tool bar
     * @type {Boolean}
     */
    isToolshown: true,
    /**
     * theme storybook, see link below
     */
    theme: themes.light
  }
});

// must come last
configure(loadStories, module);
```

**Comment by rej156** [comment]
Having the same issue here :(

**Comment by atanasster** [comment]
@rej156 do you have a repo to reproduce the issue? I am trying with the latest RC and can't reproduce it.

**Comment by pierrenel** [comment]
Same issue here - could it be related to storybook-addon-styled-component-theme - are you using it @iamdriz ?

**Comment by MarianSulgan** [comment]
Same issue here.
@pierrenel I am not using mentioned addon and still get the error, so must be related to something else...
Adding list of addons I have - worked without problems on 5.1.9.
`@storybook/addon-actions/register
@storybook/addon-links/register
@storybook/addon-backgrounds/register
@storybook/addon-viewport/register
@storybook/addon-a11y/register`

**Comment by pierrenel** [comment]
I tried 5.2.1 and still having the same issue - the getScrollAreaStyles code references a property on a theme which it doesn't have access to for some reason :(

**Comment by sami616** [comment]
I am suddenly seeing this after updating to the new `alpha.9` release.

**Comment by shilman** [comment]
@sami616 upgrading from what?

**Comment by SimonS** [comment]
I don't know what's causing this, but we had the same issue. I pared it down to markdown looking like this (that's double-indented text):

<img width="177" alt="Screenshot 2019-10-08 14 25 57" src="https://user-images.githubusercontent.com/1513/66399548-bb3ba700-e9d7-11e9-9fe7-38948d247c33.png">

Converting it to a simple bullet list makes that error go away.

**Comment by SimonS** [comment]
Further investigation seems to point it to anything involving code blocks. Our use case was that we changed a bunch of README.md files to .mdx files and imported them with the hopes that some super-literate component readmes could sit beside our components in storybook, so something like:

```
### Example

```jsx
import React from 'react';
...
```

Is enough to make it fall over.

An example `.stories.jsx` file might look like:

```jsx
import mdx from './README.mdx';

export default {
  title: '...',
  component: Paragraph,
  parameters: {
    docs: {
      page: mdx
    }
  }
};
```

I add the extra detail, cos there's a chance we might be abusing stories/trying to use them for something they're not intended to, so please tell us if this is a fool's errand 🗡 

I need to find some time to look deeper, but having a click around the DocsPages code and the getScrollAreasStyle - it looks like when the MDX interpreter hits a code block, it is passing it to a scroll area, which is expecting that theme parameter to be passed to it, and then borking out. I imagine it's a wiring problem, but lack the time and expertise right now to get my head in it.

**Comment by sami616** [comment]
@SimonS i can confirm that removing the code block from my mdx file has worked, so seems to be the culprit. I'm also using the `docs: { page }` parameter

**Comment by ArnoZx** [comment]
I managed to fix the issue by installing storybook theming
```
"@storybook/theming": "^5.2.3",
```

**Comment by shilman** [comment]
@SimonS @sami616 can you try @ArnoZx 's workaround and lmk if it works for you?

**Comment by pierrenel** [comment]
@shilman - tried adding `"@storybook/theming": "^5.2.3",` and still getting:

```
TypeError: Cannot read property 'lightest' of undefined
    at getScrollAreaStyles (http://localhost:6006/vendors~main.29b4625e4d045c010817.bundle.js:16817:78)
```

**Comment by SimonS** [comment]
@shilman - cheers, I'm getting a slightly different error, but seems to be in the same area:

```
theme.color is undefined

getScrollAreaStyles@http://localhost:6006/vendors~main.660c17218fffa9c4bfcf.bundle.js:27130:7
../../../node_modules/@storybook/theming/node_modules/@emotion/core/dist/core.browser.esm.js/Global
```

**Comment by SimonS** [comment]
I dunno if it's helpful for anyone else getting this error, for now we're working around this by sending in our own component. It loses the syntax highlighting, however:

```
parameters: {
  docs: {
    page: mdx,
    components: { code: ({ children }) => <code>{children}</code> }
  }
}
```

**Comment by shilman** [comment]
If anybody has a public repro of this, I'd love to take a look!

**Comment by pierrenel** [comment]
@thecreazy nope, still borked. Are you using styled components by any chance? Or storybook-addon-styled-component-theme ?

**Comment by pierrenel** [comment]
@shilman I'm trying to figure out if I'm allowed to stick a 5.2.* branch on a public repo for you :)

**Comment by thecreazy** [comment]
thx @pierrenel nope i'm using  this packages: 

```
  "@storybook/addon-a11y": "^5.2.4",
    "@storybook/addon-actions": "^5.2.4",
    "@storybook/addon-options": "^5.2.4",
    "@storybook/addon-storysource": "^5.2.4",
    "@storybook/addon-viewport": "^5.2.4",
    "@storybook/react": "^5.2.4",

```
and this is my `config.js`

```
import {
  addDecorator,
  addParameters,
  configure
} from '@storybook/react';
import { DocsPage, DocsContainer } from '@storybook/addon-docs/blocks';


import {
  withA11y
} from '@storybook/addon-a11y';

import { INITIAL_VIEWPORTS } from '@storybook/addon-viewport';


import exeleroLight from './theme.js';

import '@exelerotech/fringe-style/src/style/index.scss';


addParameters({
  viewport: {
    viewports: INITIAL_VIEWPORTS,
  },
  options: {
    theme: exeleroLight,
  },
  docs: {
    container: DocsContainer,
    page: DocsPage
  },
});

addDecorator(withA11y);


function requireAll(requireContext) {
  return requireContext.keys().map(requireContext);
}

function loadStories() {
  require('./generalStories/colors.jsx');
  require('./generalStories/typography.jsx');
  requireAll(require.context('../src/components', true, /index.stories\.(jsx|mdx)?$/));
}



configure(loadStories, module);

```


Unfortunately i'm not working on a public repo but if you need more information you can write directly to me

**Comment by pierrenel** [comment]
What happens if you remove all the bits to do with the exelerotech theme?

**Comment by seanmhanson** [comment]
The work-around of installing the theming and using a dark theme didn't work for me. For the record here were the changes that I made:

### Packages
```
"@storybook/theming": "5.2.4"
```

### Config
```
import { (...), addParameters } from '@storybook/react';

(...)

addParameters({
  options: {
    theme: themes.dark,
  },
});

(...)
```

**Comment by shilman** [comment]
@seanmhanson what happens when you run `yarn list @storybook/theming` (or whatever the npm equivalent is) or `yarn ls @emotion/core`. i suspect that there's some package that should be a singleton, that's actually installed multiple times in your project due to some yarn/npm weirdness.

If you find that there are multiple copies installed, try installing `@storybook/theming`, clearing your lockfile, and re-generating.

Just a hunch....

**Comment by seanmhanson** [comment]
@shilman good hunch! That wound up being the trick, and I'm pretty certain it was something dup'd or stale involving my `package-lock.json`. Thanks for the help.

**Comment by teddywsi** [comment]
Generating a new lock file seems to have resolved the error for me as well.

**Comment by thecreazy** [comment]
New lock file don't help me :/

**Comment by SimonS** [comment]
that fixes it for me locally - I had to bump the `@emotion/core` dependency explicitly, but it did the trick - thank you!

**Comment by danchristian** [comment]
When trying to use the new [Storybook Docs ](https://github.com/storybookjs/storybook/blob/next/addons/docs/README.md#installation) I am gettig `theme.color is undefined` and a new lock file didn't help me.

If I run `npm list @storybook/theming` I get:

```
├─┬ @storybook/addon-a11y@5.2.5
│ ├─┬ @storybook/api@5.2.5
│ │ └── @storybook/theming@5.2.5  deduped
│ ├─┬ @storybook/components@5.2.5
│ │ └── @storybook/theming@5.2.5  deduped
│ └── @storybook/theming@5.2.5  deduped
├─┬ @storybook/addon-actions@5.2.5
│ └── @storybook/theming@5.2.5  deduped
├─┬ @storybook/addon-docs@5.3.0-alpha.33
│ ├─┬ @storybook/api@5.3.0-alpha.33
│ │ └── @storybook/theming@5.3.0-alpha.33  deduped
│ ├─┬ @storybook/components@5.3.0-alpha.33
│ │ └── @storybook/theming@5.3.0-alpha.33  deduped
│ ├─┬ @storybook/source-loader@5.3.0-alpha.33
│ │ └─┬ @storybook/addons@5.3.0-alpha.33
│ │   └─┬ @storybook/api@5.3.0-alpha.33
│ │     └── @storybook/theming@5.3.0-alpha.33 
│ └── @storybook/theming@5.3.0-alpha.33 
├─┬ @storybook/react@5.2.5
│ └─┬ @storybook/core@5.2.5
│   ├── @storybook/theming@5.2.5  deduped
│   └─┬ @storybook/ui@5.2.5
│     └── @storybook/theming@5.2.5  deduped
```
I then `npm i -D @storybook/theming` and `npm i --package-lock-only` and then `npm list @storybook/theming` and `npm list @emotion/core` I get:

```
├─┬ @storybook/addon-a11y@5.2.5
│ ├─┬ @storybook/api@5.2.5
│ │ └── @storybook/theming@5.2.5  deduped
│ ├─┬ @storybook/components@5.2.5
│ │ └── @storybook/theming@5.2.5  deduped
│ └── @storybook/theming@5.2.5  deduped
├─┬ @storybook/addon-actions@5.2.5
│ └── @storybook/theming@5.2.5  deduped
├─┬ @storybook/addon-docs@5.3.0-alpha.33
│ ├─┬ @storybook/api@5.3.0-alpha.33
│ │ └── @storybook/theming@5.3.0-alpha.33  deduped
│ ├─┬ @storybook/components@5.3.0-alpha.33
│ │ └── @storybook/theming@5.3.0-alpha.33  deduped
│ ├─┬ @storybook/source-loader@5.3.0-alpha.33
│ │ └─┬ @storybook/addons@5.3.0-alpha.33
│ │   └─┬ @storybook/api@5.3.0-alpha.33
│ │     └── @storybook/theming@5.3.0-alpha.33 
│ └── @storybook/theming@5.3.0-alpha.33 
├─┬ @storybook/react@5.2.5
│ └─┬ @storybook/core@5.2.5
│   ├── @storybook/theming@5.2.5  deduped
│   └─┬ @storybook/ui@5.2.5
│     └── @storybook/theming@5.2.5  deduped
└── @storybook/theming@5.2.5 
```

```
├─┬ @storybook/addon-docs@5.3.0-alpha.33
│ ├─┬ @storybook/source-loader@5.3.0-alpha.33
│ │ └─┬ @storybook/addons@5.3.0-alpha.33
│ │   └─┬ @storybook/api@5.3.0-alpha.33
│ │     └─┬ @storybook/theming@5.3.0-alpha.33
│ │       └── @emotion/core@10.0.22 
│ └─┬ @storybook/theming@5.3.0-alpha.33
│   └── @emotion/core@10.0.22 
└─┬ @storybook/theming@5.2.5
  └── @emotion/core@10.0.22
```
There seem to be different versions of `@storybook/theming` being referenced.

These are my other config files just for reference:

**package.json**
```
{
  "name": "",
  "version": "0.0.1",
  "scripts": {
    "storybook": "start-storybook -p 6006",
    "build-storybook": "build-storybook"
  },
  "dependencies": {
    "react": "^16.9.0",
    "react-dom": "^16.9.0",
    "styled-components": "^4.4.0",
    "styled-system": "^5.1.2"
  },
  "devDependencies": {
    "@babel/core": "^7.6.0",
    "@storybook/addon-a11y": "^5.2.5",
    "@storybook/addon-actions": "^5.2.5",
    "@storybook/addon-docs": "^5.3.0-alpha.33",
    "@storybook/addon-links": "^5.2.5",
    "@storybook/addons": "^5.2.5",
    "@storybook/react": "^5.2.5",
    "@storybook/theming": "^5.2.5",
    "babel-loader": "^8.0.6"
  }
}
```
**.storybook/addons.js**
```
import '@storybook/addon-actions/register';
import '@storybook/addon-links/register';
import '@storybook/addon-docs/register';
import '@storybook/addon-a11y/register';
```
**.storybook/config.js**

```
import ReactDOM from "react";
import { addDecorator, addParameters, configure } from "@storybook/react";
import { withA11y } from "@storybook/addon-a11y";
import { DocsPage, DocsContainer } from '@storybook/addon-docs/blocks';
import { ThemeProvider } from "styled-components";
import theme from "../target/npm/frontend.ui.design_system.theme.js";

const themeDecorator = story =>
  ReactDOM.createElement(ThemeProvider, theme, story());

addParameters({
  docs: {
    container: DocsContainer,
    page: DocsPage,
  },
});

addDecorator(themeDecorator);
addDecorator(withA11y);
configure(require.context("../target/npm", true, /_stories.js$/), module);
```

**.storybook/webpack.config.js**
```
const createCompiler = require('@storybook/addon-docs/mdx-compiler-plugin');

module.exports = async ({ config }) => {
  config.module.rules.push({
    test: /\.(stories|story)\.mdx$/,
    use: [
      {
        loader: 'babel-loader',
        // may or may not need this line depending on your app's setup
        options: {
          plugins: ['@babel/plugin-transform-react-jsx'],
        },
      },
      {
        loader: '@mdx-js/loader',
        options: {
          compilers: [createCompiler({})],
        },
      },
    ],
  });
  config.module.rules.push({
    test: /\.(stories|story)\.[tj]sx?$/,
    loader: require.resolve('@storybook/source-loader'),
    exclude: [/node_modules/],
    enforce: 'pre',
  });
  return config;
};
```

**Comment by winssps** [comment]
@storybook/theming
@emotion/core
@emotion/styled

**Comment by Iuriy-Budnikov** [comment]
I'm still getting this error in the 5.3.12

**Comment by Iuriy-Budnikov** [comment]
<img width="1705" alt="Screenshot 2020-02-07 at 11 16 05" src="https://user-images.githubusercontent.com/3968373/74016551-45524700-499b-11ea-9228-f0413e62e3e3.png">

**Comment by ndelangen** [comment]
@Iuriy-Budnikov I can take a look at your issue, if you give me a repro repo.

**Comment by pierrenel** [comment]
Yep, still getting it too - I had to set up a patch to change ScrollAreaStyles.js so it doesn't refer to theme.color.darkest / theme.color.lightest. Something was invoking this file without passing in the theme properly 😬

**Comment by shilman** [comment]
@pierrenel @Iuriy-Budnikov 99% sure this is the symptom of a version mismatch / yarn issue. I'm not sure what's the best way to diagnose/fix, but I've seen and fixed this in dozens of different storybooks.

**Comment by ndelangen** [comment]
Yeah standard practice of "removing lockfiles & node_modules and re-install" fixes this 99.99% of the time.

There's nothing we can really to to prevent this, I think.

**Comment by Iuriy-Budnikov** [comment]
Hey @ndelangen ,
here my [repo](https://github.com/wearepush/push-ui) and [storybook](https://wearepush-ui.herokuapp.com/)

**Comment by ndelangen** [comment]
FIX: https://github.com/wearepush/push-ui/pull/31

Storybook 6 will feature a big change, no longer sharing babel config between manager & preview.

**Comment by pierrenel** [comment]
thanks @shilman - I ended up ripping all the storybook related packages out of my package.json, and ran sb init from scratch and slowly re-added each storybook addon. It's working perfectly now ✨

**Comment by VladimirPittner** [comment]
This same issue had occurred for us yesterday after updating our `yarn.lock` (without updating storybook).
Removing `yarn.lock`, `node_modules` did not helped.

I found out, that for some reason we had two `@emotion/core` in `yarn.lock`.
We use emotionJS in our project aswell, the version in our `package.json` was `10.0.27`. (I remember I already had to bump the version once to .27 when moving to SB 5.3).
Bumping the version of `@emotion/core` in our `package.json` to `10.0.28` helped to have just one `@emotion/core` in `yarn.lock`.

Posting this here, because maybe it will help someone.

**Comment by Premm** [comment]
> @storybook/theming
> @emotion/core
> @emotion/styled

Just for better clarification for those still struggling with this, these seem to be the 3 packages that need to all be on the same version in your package.lock. 

By just installing the latest of each, deleting your package-lock / yarn-lock file, and then re-running `npm i` / `yarn`, should fix your issue.

**Comment by shilman** [comment]
@Premm In general, all `@storybook/*` packages from the monorepo should have the same version and we recommend in multiple places that people upgrade them simultaneously.

**Comment by honorsuper** [comment]
@Iuriy-Budnikov   I have the same problem with you ,have you solve it ,i have found you github project push-ui, great project, i should learn form it

**Comment by Iuriy-Budnikov** [comment]
Hi @honorsuper ,
Yes, I resolved it. Try to remove package-lock/yarn lock files. 
It should help

**Comment by bwhitty** [comment]
To build on https://github.com/storybookjs/storybook/issues/7914#issuecomment-595508641, may I suggest this is a bug (or at least documentation gap?) in the way Emotion is depended upon in Storybook? I don't see any documentation stating that you must install it yourself, but for instance, having the following dependencies
```
    "@storybook/addon-actions": "^5.3.18",
    "@storybook/addon-info": "^5.3.18",
    "@storybook/addon-knobs": "^5.3.18",
    "@storybook/addon-viewport": "^5.3.18",
    "@storybook/react": "^5.3.18",
    "@storybook/theming": "^5.3.18",
```
Yields the following `UNMET PEER DEPENDENCY` error:
```
npm ls @emotion/core
├─┬ @storybook/addon-knobs@5.3.18
│ └─┬ react-select@3.1.0
│   └── @emotion/core@10.0.16
├─┬ @storybook/react@5.3.18
│ └─┬ @storybook/core@5.3.18
│   └─┬ @storybook/ui@5.3.18
│     └── UNMET PEER DEPENDENCY @emotion/core@10.0.27
└─┬ @storybook/theming@5.3.18
  └── UNMET PEER DEPENDENCY @emotion/core@10.0.27

npm ERR! peer dep missing: @emotion/core@^10.0.27, required by emotion-theming@10.0.27
npm ERR! peer dep missing: @emotion/core@^10.0.27, required by @emotion/styled@10.0.27
npm ERR! peer dep missing: @emotion/core@^10.0.27, required by emotion-theming@10.0.27
```

`npm install --save-dev @emotion/core@^10.0.27` alleviates the problem:
```
npm ls @emotion/core
├── @emotion/core@10.0.27
├─┬ @storybook/addon-knobs@5.3.18
│ └─┬ react-select@3.1.0
│   └── @emotion/core@10.0.27  deduped
├─┬ @storybook/react@5.3.18
│ └─┬ @storybook/core@5.3.18
│   └─┬ @storybook/ui@5.3.18
│     └── @emotion/core@10.0.27
└─┬ @storybook/theming@5.3.18
  └── @emotion/core@10.0.27
```
and fixes the bug from this issue.

**Comment by ndelangen** [comment]
@bwhitty looks to me like you likely have a lockfile that is forcing multiple version of emotion.

Storybook packages that use emotion depend on it. We do not have peerDependencies on emotion:
https://github.com/storybookjs/storybook/blob/ff99e99f39e58efdad406aa6689cd5ed5175ba37/lib/theming/package.json#L31-L32
https://github.com/storybookjs/storybook/blob/ff99e99f39e58efdad406aa6689cd5ed5175ba37/lib/ui/package.json#L31-L32

**Comment by ludan1107743896** [comment]
## When I view the Docs tab for any of my stories I get the following error? When I view the Docs tab for any of my stories I get the following error.
```jsavscript
Cannot read property 'lightest' of undefined,
TypeError: Cannot read property 'lightest' of undefined
    at getScrollAreaStyles (http://localhost:9009/vendors~main.02fb8fc8078fab4170f7.bundle.js:21928:78)
    at http://localhost:9009/vendors~main.02fb8fc8078fab4170f7.bundle.js:12656:100
    at updateContextConsumer (http://localhost:9009/vendors~main.02fb8fc8078fab4170f7.bundle.js:162572:19)
    at beginWork (http://localhost:9009/vendors~main.02fb8fc8078fab4170f7.bundle.js:162929:14)
    at HTMLUnknownElement.callCallback (http://localhost:9009/vendors~main.02fb8fc8078fab4170f7.bundle.js:144456:14)
    at Object.invokeGuardedCallbackDev (http://localhost:9009/vendors~main.02fb8fc8078fab4170f7.bundle.js:144505:16)
    at invokeGuardedCallback (http://localhost:9009/vendors~main.02fb8fc8078fab4170f7.bundle.js:144560:31)
    at beginWork$1 (http://localhost:9009/vendors~main.02fb8fc8078fab4170f7.bundle.js:167471:7)
    at performUnitOfWork (http://localhost:9009/vendors~main.02fb8fc8078fab4170f7.bundle.js:166425:12)
    at workLoopSync (http://localhost:9009/vendors~main.02fb8fc8078fab4170f7.bundle.js:166398:22)
```

**Comment by ndelangen** [comment]
@ludan1107743896 can you give us some more info on your environment?

**Comment by mike-lawson** [comment]
I'm running into this same problem, with the following added quirks:
* @emotion/core has been updated to 10.0.28
* @emotion/styled is still on 10.0.27

I've installed each package manually to the exact same 10.0.27 version, and there doesn't appear to be any mismatch between versions, nor are there multiple versions that I'm seeing.

```
> npm ls @emotion/core
├── @emotion/core@10.0.27 
├─┬ @storybook/addon-actions@5.3.18
│ └─┬ @storybook/theming@5.3.18
│   └── @emotion/core@10.0.27  deduped
├─┬ @storybook/addon-knobs@5.3.18
│ └─┬ react-select@3.1.0
│   └── @emotion/core@10.0.27  deduped
└─┬ @storybook/react-native@5.3.18
  └── @emotion/core@10.0.27  deduped

> npm ls @emotion/styled
├── @emotion/styled@10.0.27 
└─┬ @storybook/addon-actions@5.3.18
  └─┬ @storybook/theming@5.3.18
    └── @emotion/styled@10.0.27  deduped
```

All Storybook packages are the same version as well:
```
...
    "@storybook/addon-actions": "^5.3.18",
    "@storybook/addon-knobs": "^5.3.18",
    "@storybook/addon-ondevice-actions": "^5.3.18",
    "@storybook/addon-ondevice-knobs": "^5.3.18",
    "@storybook/addons": "^5.3.18",
    "@storybook/react-native": "^5.3.18",
...
```

Still, I'm getting the same error. Looking deeper into it, and I believe that it's an issue caused by @storybook/react-native in the sense that when this error occurs, the value of `theme` the same value that is in https://github.com/storybookjs/react-native/blob/ea2950016afd1f7c94f2086309ee4dad59ea77bb/app/react-native/src/preview/components/Shared/theme.ts

I'd love to have some guidance on what I'm doing wrong here before I spend too much more time with this.

**Comment by sshhdaniella** [comment]
Just in case anyone is having the same issues as mentioned above or getting this error `Cannot read property 'theme.color' of undefined` after a recent upgrade to storybook `6.1.10`

I can confirm that a complete nuke of storybook and a fresh re-install using `npx sb init` did it for me. I think some old dependencies were interfering 🤷‍♀️
