### ISSUE TITLE
doc page addon: issue with react stories using hooks

### ISSUE THREAD

**Issue by atanasster** [storybookjs/storybook#7924]
**Describe the bug**
The Docs tab gives the following error on stories with react hooks:
```
Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
```

Running the same stories in the preview tab does not give an error

**To Reproduce**
1. https://atanasster.github.io/grommet-controls/?path=/story/controls-input-numberinput--main and try all the stories of this component - they work fine
2. Click on 'Docs'
3. https://atanasster.github.io/grommet-controls/?path=/docs/controls-input-numberinput--main
4. The error above is on dev mode, in production it will show `inified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 

**Screenshots**
![screenshot802](https://user-images.githubusercontent.com/6075606/63984938-608b6300-ca9b-11e9-9ebd-08fff99536af.jpg)

**Code snippets**
https://github.com/atanasster/grommet-controls/blob/master/src/components/NumberInput/doc/NumberInput.stories.tsx

**System:**
```
  System:
    OS: macOS 10.14.1
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  Binaries:
    Node: 12.1.0 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.11.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 76.0.3809.132
    Firefox: 66.0.5
    Safari: 12.0.1
  npmPackages:
    @storybook/addon-a11y: ^5.1.11 => 5.1.11 
    @storybook/addon-docs: ^5.2.0-beta.40 => 5.2.0-beta.47 
    @storybook/react: ^5.2.0-beta.47 => 5.2.0-beta.47 
```

**Comment by atanasster** [comment]
small CSF story snippet to reproduce:

```
export const Default = () => {
  const [count, setCount] = React.useState(0);
  return <BaseButton onClick={() => setCount(count + 1)} label={`count: ${count}`} />;
};
```

**Comment by shilman** [comment]
Whoopee!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-rc.2 containing PR #7946 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
