### ISSUE TITLE
Addon-backgrounds: README img is broken

### ISSUE THREAD

**Issue by beizhedenglong** [storybookjs/storybook#7925]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System:**
Please paste the results of `npx -p @storybook/cli@next sb info` here.

**Additional context**

**Comment by shilman** [comment]
Can provide a screenshot? Any more info that would help repro?

**Comment by beizhedenglong** [comment]
@shilman The screenshot img used in https://github.com/storybookjs/storybook/tree/master/addons/backgrounds

<img width="1031" alt="image" src="https://user-images.githubusercontent.com/12963675/63991327-dc2bf500-cb19-11e9-86c8-02ea995ade03.png">

**Comment by shilman** [comment]
Ah ok. Thanks!! 🙇
