### ISSUE TITLE
Addon-docs: React forwardRef breaks Props block

### ISSUE THREAD

**Issue by magicspon** [storybookjs/storybook#7933]
Ref: https://github.com/storybookjs/storybook/pull/4961

**To Reproduce**
component:
```javascript
import React from 'react'
import { string } from 'prop-types'

const Title = React.forwardRef((props, ref) => (
  return <div ref={ref}>{prop.text}</div>
))

Title.propTypes = { 
  text: string.isRequired
}

export default Title
```

story:
```javascript
import React from 'react'
import Title from './Title'

export default {
	title: 'Example|Title',
	parameters: {
		component: Title
	}
}

export const newUser = () => <Title text="Ted Doe"  />
```

**Expected behavior**
The props table should show `props.text` is of type `string`

**Screenshots**
![image](https://user-images.githubusercontent.com/3268717/64018079-4dbc7100-cb23-11e9-949d-cb7eba76f941.png)

**System:**
 System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
  Binaries:
    Node: 12.6.0 - ~/.nvm/versions/node/v12.6.0/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.11.2 - ~/.nvm/versions/node/v12.6.0/bin/npm
  Browsers:
    Chrome: 76.0.3809.132
    Firefox: 68.0.2
    Safari: 12.1.2
  npmPackages:
    @storybook/addon-a11y: ^5.2.0-rc.0 => 5.2.0-rc.0 
    @storybook/addon-actions: ^5.2.0-rc.0 => 5.2.0-rc.0 
    @storybook/addon-docs: ^5.2.0-rc.0 => 5.2.0-rc.0 
    @storybook/addon-knobs: ^5.2.0-rc.0 => 5.2.0-rc.0 
    @storybook/addon-storysource: ^5.2.0-rc.0 => 5.2.0-rc.0 
    @storybook/addons: ^5.2.0-rc.0 => 5.2.0-rc.0 
    @storybook/react: ^5.2.0-rc.0 => 5.2.0-rc.0 
    @storybook/source-loader: ^5.2.0-rc.0 => 5.2.0-rc.0

**Comment by darmawanalbert** [comment]
@shilman I'm trying to fix this issue 🙇

**Comment by shilman** [comment]
Huzzah!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-alpha.23 containing PR #8445 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Jeepers creepers!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.5 containing PR #8445 that references this issue. Upgrade today to try it out!
