### ISSUE TITLE
Addon-docs: Code will not be shown in docs if CSF story is camelCase'd

### ISSUE THREAD

**Issue by roman-balzer** [storybookjs/storybook#7936]
If you are reporting a bug or requesting support, start here:
### Bug or support request summary

_Please provide issue details here - What did you expect to happen? What happened instead?_ 
I'll wrote my stories in the new CSF format, some had a now, containing a single word and some multiple, which I then used camelCase for. For those with camelCase'd names the source code of the story could not be shown. Oddly, camel_Case_With_Underscores did work again. To summarize

```
export const foo = () => <Component />`  // Works
export const Foo = () => <Component />`  // Works
export const withFoo = () => <Component />`  // Does not work
export const WithFoo = () => <Component />`  // Does not work
export const with_Foo = () => <Component />`  // Oddly works
```

### Steps to reproduce

Just write csf stories with different upper und lower cases 

### Please specify which version of Storybook and optionally any affected addons that you're running
all versions on 5.2.0-beta.46

### Affected platforms 
Windows and Chrome

**Comment by shilman** [comment]
Thanks so much @roman-balzer. Looks like a bug introduced in https://github.com/storybookjs/storybook/pull/7901 or one of the related PRs. Will fix and release in the next 12h.

**Comment by shilman** [comment]
Egads!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-rc.1 containing PR #7940 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
