### ISSUE TITLE
addons.add -> types.TOOLEXTRA does not exist

### ISSUE THREAD

**Issue by atanasster** [storybookjs/storybook#7938]
`addon.types.TOOLEXTRA` is used in 
https://github.com/storybookjs/storybook/blob/e70f91c1470f6376e21310a4079e1d7aa175fe6f/lib/ui/src/components/preview/preview.js#L125

but does not exist in`adons.types` :
https://github.com/storybookjs/storybook/blob/next/lib/addons/src/types.ts

Maybe it was intended for right-aligned buttons and we can finish it? Or just remove it?

**Comment by shilman** [comment]
Good catch @atanasster ! @ndelangen can you take a look at this?

**Comment by yannbf** [comment]
Hey @ndelangen this issue is not applicable anymore. The `preview` file has been rewritten to typescript and also it doesn't use `types.TOOLEXTRA`, which by the way is present in `addons/src/types`. Seems like you can close this 👍
