### ISSUE TITLE
withInfo doesn't respect theme colors

### ISSUE THREAD

**Issue by steve-taylor** [storybookjs/storybook#7949]
**Describe the bug**
When using `@storybook/addon-info`, the info HTML uses hardcoded text and background colors instead of inheriting them via CSS inheritence or using colors from the current theme (e.g. `themes.dark` from `@storybook/theming`).

**To Reproduce**

1. In `.storybook/config.js`:

   ```js
   import {themes} from '@storybook/theming';

   addParameters({
       options: {
           theme: themes.dark
       }
   });
   ```

2. In a story, use `withInfo` to show story info.

**Expected behavior**
The story info's `color` and `background-color` styles match the theme.

**Screenshots**

![image](https://user-images.githubusercontent.com/1135589/64075120-82812180-ccf7-11e9-861b-4563c8fd38ef.png)

**Code snippets**
(see above)

**System:**
```
Environment Info:

  System:
    OS: macOS 10.14.4
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  Binaries:
    Node: 12.3.1 - ~/.nvm/versions/node/v12.3.1/bin/node
    npm: 6.10.0 - ~/.nvm/versions/node/v12.3.1/bin/npm
  Browsers:
    Chrome: 76.0.3809.132
    Firefox: 68.0.1
    Safari: 12.1
  npmPackages:
    @storybook/addon-actions: ^5.1.11 => 5.1.11 
    @storybook/addon-info: ^5.1.11 => 5.1.11 
    @storybook/addon-knobs: ^5.1.11 => 5.1.11 
    @storybook/addon-links: ^5.1.11 => 5.1.11 
    @storybook/addon-notes: ^5.1.11 => 5.1.11 
    @storybook/addon-options: ^5.1.11 => 5.1.11 
    @storybook/addon-viewport: ^5.1.11 => 5.1.11 
    @storybook/addons: ^5.1.11 => 5.1.11 
    @storybook/react: ^5.1.11 => 5.1.11 
    @storybook/theming: ^5.1.11 => 5.1.11
```

**Additional context**
None

**Comment by steve-taylor** [comment]
Workaround:

preview-head.html:

```html
<style>
    html, body {
        margin: 0;
        background: #000;
        padding: 0;
        height: 100%;
        color: #ced4da;
    }

    #root {
        height: 100%;
    }

    .info-table, .info-table td, .info-table th {
        color: currentColor !important;
    }
</style>
```

config.js:

```js
addParameters({
    info: {
        inline: true,
        // inherit colors from preview-iframe.html
        styles: {
            infoBody: {
                backgroundColor: 'transparent',
                color: 'currentColor'
            }
        }
    },
    options: {
        theme: themes.dark
    }
});
```

**Comment by shilman** [comment]
FYI `addon-info` is being superceded by `addon-docs`, which fixes a bunch of bugs and is easier to maintain. It’s reached release candidate (RC) status and will be properly released soon. It also supports theming out of the box. Please give it a try! https://medium.com/storybookjs/storybook-docspage-e185bc3622bf
