### ISSUE TITLE
Addon-storysource: Add preset

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#7954]
https://github.com/storybookjs/presets/blob/master/packages/preset-storysource/index.js

- [ ] Move the preset from the presets repo into this package
- [ ] Update it to use `source-loader`
- [ ] Update docs

**Comment by drd-2rcl** [comment]
Hi @shilman, I have been looking for a good first issue, but normally other people take before. If it's possible, and with your help I would like try to take this issue.

**Comment by Trishaannco** [comment]
Please help me with this. littelestree17@gmail.com

**Comment by shilman** [comment]
@drd-drcl happy to. Are you on our Discord?

**Comment by drd-2rcl** [comment]
@shilman I join now and waiting for permission to send a msg

**Comment by shilman** [comment]
chatted you on discord. thanks for volunteering on this!

**Comment by afmire877** [comment]
Hi @shilman. I want to take a crack at this if it is still an issue.

**Comment by shilman** [comment]
@afmire877 go for it!

**Comment by afmire877** [comment]
@shilman Can you elaborate more on the this?

**Comment by mattfelten** [comment]
Looks like this was done in #8437 but I'm getting `Failed to load preset: "@storybook/addon-storysource/preset"` errors. Has this not be released yet?

**Comment by shilman** [comment]
@mattfelten it's in 5.3-alpha

**Comment by shilman** [comment]
Released in https://github.com/storybookjs/storybook/releases/tag/v5.3.0-alpha.21

**Comment by mattfelten** [comment]
Gotcha, thanks!
