### ISSUE TITLE
Addon-docs: docsOnly parameter generates rte

### ISSUE THREAD

**Issue by atanasster** [storybookjs/storybook#7956]
**Describe the bug**
using the new docsOnly parameter on a story generates a run time exception

**To Reproduce**
following story in an mdx file:
```
<Story name='docs-only-story' parameters={{ docsOnly: true } }>
  <Button onClick={action('clicked')}>preview source</Button>
</Story>
```

**Screenshots**
![screenshot806](https://user-images.githubusercontent.com/6075606/64086826-6934a100-cd08-11e9-98ef-22baeca8d5c9.jpg)

**System:**

```
 System:
    OS: macOS 10.14.1
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  Binaries:
    Node: 12.1.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.10.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 76.0.3809.132
    Firefox: 66.0.5
    Safari: 12.0.1
```

**Comment by shilman** [comment]
It's an internal parameter, probably should be renamed with ___prefix. But that does look like a bug!

**Comment by atanasster** [comment]
the navigation is not expecting it to be hidden (the tree view and also the next/prev stories), found it while I was exploring #7844
