### ISSUE TITLE
Storyshots afterAll is not defined error

### ISSUE THREAD

**Issue by himanshu-dixit** [storybookjs/storybook#7959]
**Describe the bug**
```
ReferenceError: afterAll is not defined
    at Object.<anonymous> (/Users/himanshu/Desktop/headout/aer/node_modules/jest-specific-snapshot/dist/index.js:28:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/himanshu/Desktop/headout/aer/node_modules/@storybook/addon-storyshots/dist/test-bodies.js:9:1)
```
**To Reproduce**
Boilerplate of code.

https://github.com/himanshu-dixit/storybook-mock-setup

**Expected behavior**
Should run the test

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System:**
Please paste the results of `npx -p @storybook/cli@next sb info` here.

**Additional context**

**Comment by dlombardi** [comment]
This is still happening:

```

    ReferenceError: afterAll is not defined

      1 | import registerRequireContextHook from 'babel-plugin-require-context-hook/register';
    > 2 | import initStoryshots from '@storybook/addon-storyshots';
        |                                               ^
      3 |
      4 | registerRequireContextHook();
      5 | initStoryshots();

      at Object.<anonymous> (node_modules/jest-specific-snapshot/dist/index.js:28:1)
      at Object.<anonymous> (node_modules/@storybook/addon-storyshots/dist/test-bodies.js:9:1)
      at Object.<anonymous> (node_modules/@storybook/addon-storyshots/dist/api/ensureOptionsDefaults.js:10:19)
      at Object.<anonymous> (node_modules/@storybook/addon-storyshots/dist/api/index.js:12:53)
      at Object.<anonymous> (node_modules/@storybook/addon-storyshots/dist/index.js:52:35)
      at Object.<anonymous> (storybook/test/jest.setup.js:2:47)
```

**Comment by RyanPayso13** [comment]
I am experiencing this.  Anyone have any ideas?

**Comment by RyanPayso13** [comment]
Is there any idea as to why this might be happening as it is blocking my progress with chromatic!

**Comment by crunchyfrog42** [comment]
Today, I suddenly got the same error when trying to start storybook. Deleting node_modules/.cache/storybook solved the issue for me. I'm still seeing the error message, but apart from this, everything seems to be working.

**Comment by vdpdev** [comment]
@crunchyfrog42 this didn't help for me. Still watching for this issue be solved.

**Comment by cherylcarpenter** [comment]
This issue is preventing me from using storyshot. I don't understand why things get closed.
Environment Info:

  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  Binaries:
    Node: 12.13.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.12.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 88.0.4324.96
    Safari: 14.0.1
  npmPackages:
    @storybook/addon-actions: ^6.1.11 => 6.1.14 
    @storybook/addon-essentials: ^6.1.11 => 6.1.14 
    @storybook/addon-knobs: ^6.1.15 => 6.1.15 
    @storybook/addon-links: ^6.1.11 => 6.1.14 
    @storybook/addon-notes: ^5.3.21 => 5.3.21 
    @storybook/addon-storyshots: ^6.1.15 => 6.1.15 
    @storybook/addon-storysource: ^6.1.15 => 6.1.15 
    @storybook/addons: ^6.1.14 => 6.1.14 
    @storybook/preset-scss: ^1.0.3 => 1.0.3 
    @storybook/theming: ^6.1.14 => 6.1.14 
    @storybook/vue: ^6.1.11 => 6.1.14

**Comment by phated** [comment]
I just ran into this and it took me a little bit to figure it out. Essentially, you can't add `@storybook/addon-storyshots` to your list of addons in `.storybook/main.js` because it doesn't have Jest globals available. Instead, you just create the test files and then run Jest and it generates the storyshot files.

I'm not exactly sure why this is called an "addon" if it can't be added to that addon list.

**Comment by unknownterritory** [comment]
Thank you, @phated ! This was a mostly innocuous but nevertheless irritating warning. I am quite happy to see it gone.

**Comment by shilman** [comment]
Boo-yah!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.0-alpha.25 containing PR #13842 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

**Comment by shilman** [comment]
Huzzah!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.18 containing PR #13842 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```

**Comment by Ravindersingh1526** [comment]
Don't add  addon @storybook/addon-storyshots in main.js file

**Comment by jackdh** [comment]
Is anyone else seeing this when using the @storybook/build-vite? I've made not not to include the addon-storyshots in the main.js file.

**Comment by Jarzka** [comment]
I'm getting the same error even if I have not added `@storybook/addon-storyshots` to the addon list.

**Comment by Jarzka** [comment]
Also got the same error with vitest. It seems that there is no support for it (yet): https://github.com/storybookjs/storybook/issues/17578
