### ISSUE TITLE
Notes are displaying from center of box.

### ISSUE THREAD

**Issue by patrickteivas** [storybookjs/storybook#7960]
**Describe the bug**
Notes are displaying from center of box.

**To Reproduce**
1. Create note

**Expected behavior**
Aligned to left.

**Screenshots**
![image](https://user-images.githubusercontent.com/29047825/64114117-d9890400-cd94-11e9-83fe-6d1cf6867d35.png)
![image](https://user-images.githubusercontent.com/29047825/64114268-3e445e80-cd95-11e9-8ef2-6e84d755e11d.png)

**Code snippets**
Content of `test.stories.js`
```
import Vue from 'vue';
import { storiesOf } from '@storybook/vue';
import Link from '@/components/Link';
import LinkMarkdown from '@/stories/LinkMarkdown.md';

storiesOf('test', module).add(
  'Link',
  () => ({
    components: { Link },
    template: `<link :url="'test-url'" />`,
  }),
  {
    notes: { markdown: LinkMarkdown },
  }
);
```
Content of `LinkMarkdown.md`
```
#Also you can use markdown notes
```

**System:**
```
Environment Info:

  System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
  Binaries:
    Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.17.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.17763.1.0
  npmPackages:
    @storybook/addon-actions: ^5.1.11 => 5.1.11
    @storybook/addon-notes: ^5.1.11 => 5.1.11
    @storybook/vue: ^5.1.11 => 5.1.11
```

**Additional context**
Using Chrome.

**Comment by shilman** [comment]
FYI `addon-notes` is being superceded by `addon-docs`. It’s reached release candidate (RC) status and will be properly released soon. Please give it a try! https://medium.com/storybookjs/storybook-docspage-e185bc3622bf

**Comment by patrickteivas** [comment]
Thanks for replying! Sorry, but can't actually use dev-versions. Can you give more information about release date? About month?

**Comment by shilman** [comment]
@patrickteivas Next week (or possibly the week after to avoid conflicting with the Apple announcement)

**Comment by patrickteivas** [comment]
Nice. Also tried `addon-docs` on `"@storybook/vue": "5.2.0-rc.2"`, but got
```
ERROR in ./.storybook/config.js
Module not found: Error: Can't resolve '@storybook/addon-docs/blocks' in 'C:\Users\User\Desktop\Projects\test\.storybook'
```
`config.js` content
```
import Vue from 'vue'
import Vuex from 'vuex'
import { configure, addDecorator, addParameters } from '@storybook/vue'
import { DocsPage, DocsContainer } from '@storybook/addon-docs/blocks';
import { action } from '@storybook/addon-actions'
import VueI18n from 'vue-i18n';

Vue.use(VueI18n);
Vue.use(Vuex)

Vue.component('nuxt-link', {
  props: ['to'],
  methods: {
    log() {
      action('link target')(this.to)
    },
  },
  template: '<a href="#" @click.prevent="log()"><slot>NuxtLink</slot></a>'
})

addDecorator(() => ({
  template: '<story />',
  i18n: {
    locale: '',
  },
}));

addParameters({
  docs: {
    container: DocsContainer,
    page: DocsPage,
  },
});

function loadStories() {
  const req = require.context('../stories', true, /\.stories\.js$/)
  req.keys().forEach(filename => req(filename))
}

configure(loadStories, module)
```

**Comment by shilman** [comment]
@patrickteivas Did you install the addon? See https://github.com/storybookjs/storybook/blob/next/addons/docs/README.md#installation

**Comment by patrickteivas** [comment]
@shilman of course :)
![image](https://user-images.githubusercontent.com/29047825/64176255-b1b5a100-ce65-11e9-90cf-b424c21db8cc.png)

**Comment by shilman** [comment]
@patrickteivas all your `@storybook/*` should be on `5.2.0-rc.4`

**Comment by patrickteivas** [comment]
My bad. Upgraded all packages to `5.2.0-rc.4`. Now I'm almost achieved working solution, but still need some help.
`Badge.stories.mdx` content
```
import { Meta, Story, Props } from '@storybook/addon-docs/blocks';
import Badge from '@/components/Badge';

<Meta title="Demo/Badge" component={Badge} />

# Badge

With `MDX` we write longform markdown documentation for our `Badge` component and embed Doc Blocks inline.

<Props of = { Badge} />

<Story name="positive">
  <Badge to="test-url" />
</Story>
```
Getting
```
  11 | const makeShortcode = name => function MDXDefaultShortcode(props) {
  12 |   console.warn("Component " + name + " was not imported, exported, or provided by MDXProvider as global scope")
> 13 |   return <div {...props}/>
     |          ^
  14 | };
```
Where exactly I have to register components?

**Comment by shilman** [comment]
@patrickteivas Your syntax for vue MDX stories is wrong. See https://github.com/storybookjs/storybook/issues/7984 for full explanation, or https://raw.githubusercontent.com/storybookjs/storybook/next/examples/vue-kitchen-sink/src/stories/addon-docs.stories.mdx for examples

cc @Aaron-Pool on vue-specific questions

**Comment by patrickteivas** [comment]
New `Badge.stories.mdx` content.
```
import { Story, Preview, Meta } from '@storybook/addon-docs/blocks';
import Badge from '@/components/Badge';

<Meta title="Addon|Docs" />

<Story name="badge">
  {{
    template: '<badge :to="test-link" />',
  }}
</Story>
```
Still same error
```
  11 | const makeShortcode = name => function MDXDefaultShortcode(props) {
  12 |   console.warn("Component " + name + " was not imported, exported, or provided by MDXProvider as global scope")
> 13 |   return <div {...props}/>
     |          ^
  14 | };
```
Can't get, what I'm doing wrong.

**Comment by shilman** [comment]
I'm not too familiar with Vue, but in `vue-kitchen-sink/.storybook/config.js`, I see this line:

```
Vue.component('my-button', MyButton);
```

Wonder if you need to do this for `Badge`?

**Comment by patrickteivas** [comment]
> Wonder if you need to do this for `Badge`?

It's test component I created, to match docs.



> but in `vue-kitchen-sink/.storybook/config.js`, I see this line:
> 
> ```
> Vue.component('my-button', MyButton);
> ```

Tried, still same error. Btw, that would be weird, if I'd must register every component I'm writing docs on in `config.js` file
Also some debug info. Even if I delete all content from `Badge.stories.mdx` file, I get still same error.

**Comment by shilman** [comment]
Ok, @Aaron-Pool can you shed any light on this?

**Comment by Aaron-Pool** [comment]
Pretty early in the Eastern Time zone, so I'm not in front of a computer yet, but here are some thoughts:

@Shilman looks like his build is choking on jsx. I see he isn't using a a docs preset, and he isn't using the Babel react jsx plugin. So could it maybe just be that?

On the Vue side, to ensure it isn't a component registration issue, you could change your story to this (leaving the rest of the file unchanged):

```js
<Story name="badge">
  {{
    components: { Badge },
    template: '<badge :to="test-link" />',
  }}
</Story>
```

That's the more common way of registering components for stories. The Vue kitchen sink uses a global registration in the config because it's mostly a demo app.

But, like I said, the error you're getting really makes me think it's more of a build issue than anything. So I don't expect changing your story to fix it.

I'll dig into it more when I can get to a computer.

**Comment by patrickteivas** [comment]
> On the Vue side, to ensure it isn't a component registration issue, you could change your story to this (leaving the rest of the file unchanged):
> 
> ```js
> <Story name="badge">
>   {{
>     components: { Badge },
>     template: '<badge :to="test-link" />',
>   }}
> </Story>
> ```

Nope, still same error.

**Comment by Aaron-Pool** [comment]
Yeah, like I said, I figured it was a build issue and unrelated to component registration. I'll try to get back to you in a few hours.

**Comment by Aaron-Pool** [comment]
Ok @patrickteivas give this a shot.

1) In your `.storybook` folder, create a file called `presets.js` (I'm assuming it doesn't exist)
2) Set the file content to:
```js
module.exports = ['@storybook/addon-docs/vue/preset'];
```
3) Change your `webpack.config.js` file to be
```js
const path = require('path');

module.exports = async ({ config }) => {
  config.module.rules.unshift({
    test: /\.s?css$/,
    loaders: ['style-loader', 'css-loader', 'sass-loader'],
    include: path.resolve(__dirname, '../')
  });
  return config;
};
```

Give that a whirl. If it doesn't work. I'll probably need a minimal reproduction repo to debug for you.

**Comment by patrickteivas** [comment]
@Aaron-Pool okay, now I have also good news :).
I don't have any errors anymore, but no stories appear on the list.
Also, the problem is aliases. I need to configure `@` and `~` aswell.

**Comment by Aaron-Pool** [comment]
@patrickteivas If you click the "canvas" tab rather than the "docs" tab, does the selected story render?

**Comment by patrickteivas** [comment]
@Aaron-Pool 
> If you click the "canvas" tab rather than the "docs" tab, does the selected story render?

Nope. I have only 1 story (That one I sent before) for the test and it's not displayed in the sidebar at all (So I see "loading" animation in it).
To test config without aliases, I deleted all `@` and `~` and replaced them with relative paths.

**Comment by Aaron-Pool** [comment]
@patrickteivas alright, well, if it's still not working, I probably need a minimal repro to debug.

**Comment by patrickteivas** [comment]
@Aaron-Pool I don't think I can fully reproduce situation, but here's my minimal repo.
https://github.com/patrickteivas/Storybook-DocsPage-Mini

**Comment by Aaron-Pool** [comment]
@patrickteivas thanks for the repro, I'll try to pull it down and debug when I get off work tonight.

**Comment by Aaron-Pool** [comment]
@patrickteivas k. FIxed it. You were using a deprecated story loading format. Also, the vue docs preset already contained the new Parameters you were adding.

Basically, change your config to:
```js
import Vue from 'vue';
import { configure } from '@storybook/vue';
import { DocsPage, DocsContainer } from '@storybook/addon-docs/blocks';
import { action } from '@storybook/addon-actions';

Vue.component('nuxt-link', {
  props: ['to'],
  methods: {
    log() {
      action('link target')(this.to);
    }
  },
  template: '<a href="#" @click.prevent="log()"><slot>NuxtLink</slot></a>'
});

// Remove this completely
/*
addParameters({
  docs: {
    container: DocsContainer,
    page: DocsPage
  }
});
*/

// And change this
/*
function loadStories() {
  const req = require.context('../stories', true, /\.stories\.(js|mdx)$/);
  req.keys().forEach((filename) => req(filename));
}
// configure(loadStories, module);
*/

// To this
configure(require.context('../stories', true, /\.stories\.(ts|mdx)$/), module);

```

You'll _theeeeennnn_ get the `<Logo/>` component is not recognized. So change `Logo.stories.mdx` to:
```js
import { Story, Preview, Meta } from '@storybook/addon-docs/blocks';
import Logo from '../components/Logo';

<Meta title="Addon|Docs" />

<Story name="Logo">
  {{
    components: { Logo },
    template: '<Logo />'
  }}
</Story>
```

Aaaaaaaannnnnddd _theeeennn_ you're good 👍

**Comment by shilman** [comment]
@Aaron-Pool you're an angel 👼

**Comment by patrickteivas** [comment]
@Aaron-Pool wow, that's very impressive. I'm very thankful that you find time and patience to help me.
Fixed aliases by adding this in `module.exports`
```
config.resolve.alias = {
  ...config.resolve.alias,
  '@': path.dirname(path.resolve(__dirname)),
  '~': path.dirname(path.resolve(__dirname))
};
```
But text still centered, it's should be like this?
![image](https://user-images.githubusercontent.com/29047825/64336936-d5542500-cfe6-11e9-8c83-f9ef0dbd4089.png)

**Comment by Aaron-Pool** [comment]
@patrickteivas no problem at all!

And I think what you're seeing now is that the docs add-on content has a Max width, and you seem to have a pretty wide monitor. Typically for documentation though, a Max width is a good thing. You normally don't want text content to stretch more than 80 characters or else people will [lose their place while reading](https://www.w3.org/WAI/tutorials/page-structure/styling/#line-length).

If this has a really negative impact on you, feel free to creat a feature request as a separate issue to adjust the docs max-width!

**Comment by patrickteivas** [comment]
> to adjust the docs max-width!

I don't mean `max-width` adjustment. Like, just align content to the left.


> and you seem to have a pretty wide monitor

FullHD.

**Comment by Aaron-Pool** [comment]
@patrickteivas that's actually very helpful to know that an FHD monitor can make things look odd with the current layout settings. One of the most difficult things about testing software can be thinking about edge cases in user environments. Like I said, if you want to create a feature request issue to be able to set the docs content to align to the left (thanks for that clarification, btw), just so it's documented, that would be great!

**Comment by patrickteivas** [comment]
Big thanks to both of you, who helped me to set up `addon-docs` in my project.
Created the feature request. Closing issue.
#8004
