### ISSUE TITLE
api.on is not a function

### ISSUE THREAD

**Issue by waleedarshad** [storybookjs/storybook#7963]
Hi I am using ignite and while running npm run storybook I got this error `api.on is not a function`
these are the blow version that ignites is using. can you explain why this is happening or is this the version issues
    `"@storybook/addon-actions": "5.0.11",`
    `"@storybook/addon-links": "5.0.11",`
    `"@storybook/addon-storyshots": "^4.1.11",`
    `"@storybook/addons": "^4.1.11",`
    `"@storybook/channels": "^4.1.11",`
    `"@storybook/react-native": "^4.1.11",`

![Desktop screenshot](https://user-images.githubusercontent.com/5329697/64125187-a5c4d300-cdc2-11e9-8e90-44a9dd8ba2a3.png)

**Comment by shilman** [comment]
@waleedarshad Please update all your `@storybook/*` to the same version

**Comment by waleedarshad** [comment]
Yes worked for me 

Thanks
