### ISSUE TITLE
Addon-docs: mdx empty story generates exception

### ISSUE THREAD

**Issue by atanasster** [storybookjs/storybook#7964]
**Describe the bug**
Using an empty story on an mdx page generates an exception

**To Reproduce**
```
<Preview>
  <Story id="empty-story" />
</Preview>
```

**Screenshots**
![screenshot807](https://user-images.githubusercontent.com/6075606/64126684-b3f00080-cd7c-11e9-8813-a9b0876de922.jpg)

**Comment by shilman** [comment]
Whoopee!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-rc.6 containing PR #7965 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
