### ISSUE TITLE
Add Marionette.js support

### ISSUE THREAD

**Issue by avasuro** [storybookjs/storybook#7980]
**Describe the solution you'd like**
I'd like to see Marionette.js support, as I see Storybook to be very component focused, and Marionette being a very component focus framework - these tools would compliment each other very well.

**Are you able to assist bring the feature to reality?**
yes, I can.

**Comment by shilman** [comment]
Great Caesar's ghost!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-alpha.0 containing PR #7981 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
