### ISSUE TITLE
Addons-docs; dark theme styling issues

### ISSUE THREAD

**Issue by atanasster** [storybookjs/storybook#7982]
**Describe the bug**
Some of the text is not visible in dark theme

**To Reproduce**
switch to theme.dark in config.js

**Screenshots**
![docs-dark](https://user-images.githubusercontent.com/6075606/64195837-6cd33f80-ce50-11e9-8df3-f82545da40a3.jpg)

**Comment by shilman** [comment]
ZOMG!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-rc.6 containing PR #7991 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by chrsep** [comment]
Hi, thanks for fixing this. The list elements are still dark though, so i try to make another PR to extend the change on #7991  to the `<li>` elements. I also feel H6 still seems to be too dark, but I'm not sure what color is best for it on the dark theme.

**Comment by shilman** [comment]
Gadzooks!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-rc.8 containing PR #8015 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.
