### ISSUE TITLE
[addon-centered] Peer dependencies

### ISSUE THREAD

**Issue by Svish** [storybookjs/storybook#7989]
**Describe the bug**
The `@storybook/addon-centered` package has the following `peerDependencies`:

```json
{
  "peerDependencies": {
    "mithril": "*",
    "preact": "*",
    "react": "*"
  }
}
```
Meaning installing it will always add 2-3 annoying warnings to a project. You'll never have more than 1 of those installed at the same time, and you can even use the addon without any of them.

**Expected behavior**
A package should not have `peerDependencies` that can't/won't ever be met. Please find a better solution ([`optionalDependencies`](https://docs.npmjs.com/files/package.json#optionaldependencies)?), or just remove the `peerDependencies` all together in this case.

**Comment by shilman** [comment]
`optionalDependencies` has the same problem. We should just remove the dependencies.

**Comment by shilman** [comment]
Hey @leoyli here you go go go!! 🚀

**Comment by Svish** [comment]
Inactive? Fixed by #8156, maybe?

**Comment by leoyli** [comment]
@Svish, yes fixed, stay tune 👀

**Comment by shilman** [comment]
Fixed & released on both `next` and `latest`
