### ISSUE TITLE
Storybook with Polymer does not work in Internet Explorer 11

### ISSUE THREAD

**Issue by michael-breazeale** [storybookjs/storybook#7995]
### Describe the bug 🔍
Unable to view storybook polymer example on Internet Explorer 11. This also occurs on local, but since it's presenting on the example that seems to be the best place to focus.

### To Reproduce 💥
1. Open IE 11 (My version is 11.950.17134.0)
2. Open Developer console if you want to see the errors in the log.
3. Go to '[https://storybooks-polymer.netlify.com/](https://storybooks-polymer.netlify.com/)'

### Expected behavior ✨
The working story book that shows in Chrome.

### Screenshots 📸
![image](https://user-images.githubusercontent.com/3037540/64281509-e8002880-cf18-11e9-93ca-48f828a54cd9.png)

![image](https://user-images.githubusercontent.com/3037540/64281588-0fef8c00-cf19-11e9-9155-47ce0d107420.png)

With chrome we see:
![image](https://user-images.githubusercontent.com/3037540/64281761-72e12300-cf19-11e9-81d1-bb38d6a0a817.png)

### Context👨‍💻
 - Device: Computer/PC
 - OS: Windows 10 Enterprise (Version 1803 Build 17134.95)
 - Browser: Internet Explorer 11
 - Browser version: 11.950.17134.0
 - Storybook Version: 5.1.11

**Comment by michael-breazeale** [comment]
#7093 #7263 And other IE 11 issues might help. I think there must be some missing polyfills. I've tried the workaround in #4099 with no success (but I didn't expect that since it's from v4.

**Comment by shilman** [comment]
Which version of storybook are you running? I think the netlify deploys are outdated (cc @ndelangen)

**Comment by michael-breazeale** [comment]
@shilman Storybook 5.1.11

**Comment by michael-breazeale** [comment]
In testing, I created an empty storybook project. 

```console
npx -p @storybook/cli sb init
```

Selected Polymer manually. 


Manually added lit-element because it's not added via the init, resulting in the following package.json:
``` json
{
  "dependencies": {
    "lit-element": "^2.2.1"
  },
  "devDependencies": {
    "@babel/core": "^7.5.5",
    "@storybook/polymer": "^5.1.11",
    "babel-loader": "^8.0.6",
    "polymer-webpack-loader": "^2.0.3"
  },
  "scripts": {
    "storybook": "start-storybook -p 6006",
    "build-storybook": "build-storybook"
  }
}
```
Even with an empty `index.stories.js`

I see this in Internet Explorer:
![image](https://user-images.githubusercontent.com/3037540/64283832-d5d4b900-cf1d-11e9-97cc-418ac9d172b7.png)

![image](https://user-images.githubusercontent.com/3037540/64283854-e2591180-cf1d-11e9-81f3-2ee36e84bf02.png)


And this in Chrome:

![image](https://user-images.githubusercontent.com/3037540/64283886-f43ab480-cf1d-11e9-9df0-834b9ddce2b5.png)

![image](https://user-images.githubusercontent.com/3037540/64283952-16343700-cf1e-11e9-838b-46806b16fc6f.png)

**Comment by michael-breazeale** [comment]
It may be related to this lit-html issue: https://github.com/Polymer/lit-html/issues/873

**Comment by michael-breazeale** [comment]
I was able to get the error to go away in IE 11 with the webpack config in this issue: 

https://github.com/storybookjs/storybook/issues/7084#issuecomment-522883376
