### ISSUE TITLE
Unclear documentation for storyKindRegex and "story kinds"

### ISSUE THREAD

**Issue by worc** [storybookjs/storybook#7996]
What is a "story kind"? I'm trying to work with the `storyKindRegex`, but I'm not finding any documentation on what a `story kind` _is_. Is it a reference to a file name? File extension? Something to do with the component type? The storybook entry strings?

**Comment by shilman** [comment]
Story kind is the first arg to `storiesOf`. In the following, the kind is `MyComponent`:

```
storiesOf('MyComponent', module).add(...)
```

`storyKindRegex` is a way to only include certain kinds ("components") in your snapshot tests.

**Comment by holmesal** [comment]
How can we exclude individual stories by name?

**Comment by sergej-s** [comment]
@holmesal It seems that adding `storyNameRegex` along with `storyKindRegex` does work:
```javascript
storyKindRegex: /^MyComponent$/,
storyNameRegex: /^((?!.*?DontTest).)*$/,
```
```
storiesOf('MyComponent', module)
  .add(`Playground (DontTest)`, () => {
     ...
```
