### ISSUE TITLE
addon-docs for react-native

### ISSUE THREAD

**Issue by declanelcocks** [storybookjs/storybook#8003]
Sorry if this is a duplicate issue, but I couldn't find the feature request anywhere. Just wondering if you guys have any roadmap with regards to adding `addon-docs` support for `react-native`?

**Comment by shilman** [comment]
I have no current plans to support `addon-docs` for React Native. But I'd be happy to work with anybody who wants to make it happen.

Some quick thoughts:

- It would be easy to support `react-native-web` docs.
- It might be possible to hook docs up to a third party service like https://appetize.io/
- It might be possible to build `on-device` docs?!

**Comment by declanelcocks** [comment]
@shilman was taking a quick look through how `addon-docs` is setup and I can see how it would be complicated to set up for RN. It would be nice to build the docs on-device as you mentioned, even if that means through a separate RN version of the addon.

I'd be happy to contribute but I haven't used `addon-docs` on web yet to get an idea of how it functions. From a quick look, I'd say most of the default docs stuff would work fine for RN (props table etc.) and showing all the stories could be as simple as just showing all the stories on the simulator.

**Comment by Gongreg** [comment]
@declanelcocks, there is jsx addon that support RN: https://github.com/Gongreg/storybook-usage . The addon for docgen should be possible also, but I don't know if there is one.

**Comment by Gongreg** [comment]
@declanelcocks, also today I saw that there is an experimental decorator for info:
https://github.com/RobinLebhar/with-info-doc-expo-storybook

**Comment by senghuotlay** [comment]
Hey guys, I know that this has been a while. Therefore, will there be any plans for react-native?
