### ISSUE TITLE
Align docs content to the left

### ISSUE THREAD

**Issue by patrickteivas** [storybookjs/storybook#8004]
**Is your feature request related to a problem? Please describe.**
When writing docs with `addon-docs`, content of `.mdx` file (Documentation file) starting from the center of window on FHD monitor resolution.

**Describe the solution you'd like**
Content aligned to the left, no need to increase `max-width` of the content block.

**Are you able to assist bring the feature to reality?**
Don't think so.

**Additional context**
Screenshot of content starting from the center (Like I described)
![image](https://user-images.githubusercontent.com/29047825/64344908-0be66b80-cff8-11e9-9bfb-c982e812f8df.png)
Screenshot of my idea
![image](https://user-images.githubusercontent.com/29047825/64345588-4dc3e180-cff9-11e9-9846-d4df815350de.png)

**Comment by patrickteivas** [comment]
If this feature request will be accepted, I realized that `display: flex` on `docs-root` child `div` is responsible for this. I'm not expert in frontend development, but if just take this off, will it break other things?
```
display: -webkit-box;
display: -webkit-flex;
display: flex;
```

**Comment by shilman** [comment]
Cc @domyen who designed the current layout

**Comment by patrickteivas** [comment]
cc @domyen so, what about it?

**Comment by shilman** [comment]
Those classes should now be present in the SB Docs CSS in `next` (5.3.0-alpha.x). Documented here: https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/theming.md#css-escape-hatches

Closing for now!
