### ISSUE TITLE
liElement Array property breaks storybook knobs when when value is undefined

### ISSUE THREAD

**Issue by christophe-g** [storybookjs/storybook#8005]
**Describe the bug**
A story testing a lit Element like this: 
```js
import { LitElement, html } from 'lit-element';

class Test  extends LitElement {

  static get properties() {
    return {
       anArray : {
         type: Array
       }
    };
  }
  
  render() {
    return html`
      <!-- template content -->
      <p>A paragraph</p>
    `;
  }
}

// Register the new element with the browser.
customElements.define('my-test', Test **);**
```

breaks storybook knobs when Array has not been initialized with a value. 

Root cause is knob component Array render function calling `join` on undefined `knob.value`: 
```js
 render() {
    const { knob } = this.props;
    const value = knob.value.join(knob.separator);

    return (
      <Form.Textarea
        id={knob.name}
        name={knob.name}
        value={value}
        onChange={this.handleChange}
        size="flex"
      />
    );
  }
```
Will submit a PR shortly

**Comment by shilman** [comment]
Hurrah!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-alpha.4 containing PR #8006 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

**Comment by shilman** [comment]
Zoinks!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.2 containing PR #8006 that references this issue. Upgrade today to try it out!
