### ISSUE TITLE
SSR (server side render) stories in the iframe

### ISSUE THREAD

**Issue by treshugart** [storybookjs/storybook#8009]
Hey, everyone. First and foremost, Storybook is awesome and a joy to use, especially with the improvements coming in 5.2. Stoked!

I've looked, and it doesn't seem that Storybook server-side-renders the stories in the iframe. Searching only yielded a couple of results that are close to what I was looking for.

- https://github.com/storybookjs/storybook/issues/828
- https://github.com/storybookjs/storybook/issues/4082
- https://github.com/storybookjs/storybook/issues/4271

Looking at the iframe, it doesn't show any SSR content etc. Looking at the source also didn't reveal any clues, either.

I think it would be great as you could develop your stories and components with SSR in mind, and even run automated testing over them.

Do you have any thoughts regarding the support of SSR'ing stories?

FWIW, I'd be open to helping with this effort, but just wanted to gauge interest beforehand.

Thanks!

**Comment by shilman** [comment]
Would love to figure this out for docs

**Comment by YoungElPaso** [comment]
In this case is SSR synonymous with pre-rendering? I guess if you're developing w/ SSR in mind, that's not the case.  But I think pre-rendering and SSR are related, and @shilman 's use case (docs) is the same one I'm going for.

**Comment by treshugart** [comment]
Yeah, I think that would be sufficient. I think pre-rendering could cover a smoke test of SSR'able components.
