### ISSUE TITLE
Include css from assets folder return "Refused to include..." error

### ISSUE THREAD

**Issue by JEricaM** [storybookjs/storybook#8010]
Hi, I'm including Font Awesome inside my Storybook Stencil project.
This is my project structure

```
|-> src
	|-> assets
		|-> fontawesome
			|-> css
				|-> all.css
|-> .storybook
	|-> manager-head.html
	|-> preview-head.html
```

In order to make font awesome work inside storybook, as I read in the doc, I need to include inside  **manager-head** and **preview-head** this reference
<link
  rel="stylesheet"
  type="text/css"
  href="../src/assets/fontawesome/css/all.css"
/>

But when I start storybook, I have this problem:
<img width="1064" alt="Schermata 2019-09-06 alle 10 49 34" src="https://user-images.githubusercontent.com/9347586/64414687-19e9ca00-d094-11e9-87bb-2827cce1c64a.png">

<img width="1012" alt="Schermata 2019-09-06 alle 10 49 46" src="https://user-images.githubusercontent.com/9347586/64414708-22420500-d094-11e9-9988-89126972b7fd.png">

The full error is:
> Refused to apply style from 'http://localhost:6007/src/assets/fontawesome/css/all.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled

I don't know why the error said **MIME type ('text/html')**, because I wrote **type="text/css"**
The path it's correct but and I don't know why I have this error.

**Comment by Hypnosphi** [comment]
@JEricaM what do you see if you open http://localhost:6007/src/assets/fontawesome/css/all.css in your browser?

**Comment by Hypnosphi** [comment]
@JEricaM You probably have to pass `src/assets` as [statics directory](https://storybook.js.org/docs/configurations/serving-static-files/#2-via-a-directory) to storybook commands:

```js
// package.json
{
  ...
  "scripts": {
    ...
    "storybook": "start-storybook -p 6006 -s ./src/assets",
    "build-storybook": "build-storybook -s ./src/assets"
  }
}
```

Then change the reference to `all.css`:
```html
// preview-head.html
<link rel="stylesheet" type="text/css" href="fontawesome/css/all.css" />
```

You shouldn't need `manager-head` at all, because you probably only want font awesome inside your own stories.

Here's an example of working setup: https://github.com/Hypnosphi/storybook-fontawesome-repro
