### ISSUE TITLE
[addon-docs] How Props component works?

### ISSUE THREAD

**Issue by patrickteivas** [storybookjs/storybook#8013]
`Badge.stories.mdx` content.
```
import { Story, Preview, Meta, Props } from '@storybook/addon-docs/blocks';
import Badge from '../components/Badge;

<Props of={Badge} />
```
`Badge.vue` props section.
```
export default {
  props: {
    url: {
      type: String,
      default: '',
      required: true,
    },
  },
};
```
Gives me
![image](https://user-images.githubusercontent.com/29047825/64427809-bde66c00-d0ba-11e9-8090-9035b21c359e.png)

Found no examples of proper `Props` component usage.
Do I need to manually write them or it's supposed to take them automatically?

**Comment by shilman** [comment]
It currently only works for React, based on `propTypes` or Typescript annotations.

https://github.com/storybookjs/storybook/blob/next/addons/docs/README.md#framework-support

https://github.com/storybookjs/storybook/blob/next/addons/docs/README.md#typescript-configuration

**Comment by patrickteivas** [comment]
Thanks for the reply! Think, now the issue can be closed.

**Comment by MichaelTrilford-Airwallex** [comment]
Just FYI, the documentation around `import { Props } from '@storybook/addon-docs/blocks'` is super hard to find.
