### ISSUE TITLE
Error processing spread flow types

### ISSUE THREAD

**Issue by IanVS** [storybookjs/storybook#8017]
**Describe the bug**
I'm having the same bug as https://github.com/storybookjs/storybook/issues/4873, which was closed due to inactivity.  I don't have anything else to add, but I think this should still be tracked.

**To Reproduce**
See original issue

**Expected behavior**
See original issue

**Screenshots**
See original issue

**Code snippets**
```js
type Props<T> = {|
    ...React.ElementConfig<T>,
    as: T,
|};
```

**System:**
```
Environment Info:

  System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  Binaries:
    Node: 10.15.1 - ~/.nvm/versions/node/v10.15.1/bin/node
    Yarn: 1.17.3 - ~/.yarn/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.1/bin/npm
  Browsers:
    Chrome: 76.0.3809.132
    Firefox: 68.0.1
    Safari: 12.1.2
  npmPackages:
    @storybook/addon-actions: 5.2.0-beta.46 => 5.2.0-beta.46
    @storybook/addon-info: 5.2.0-beta.46 => 5.2.0-beta.46
    @storybook/addon-knobs: 5.2.0-beta.46 => 5.2.0-beta.46
    @storybook/react: 5.2.0-beta.46 => 5.2.0-beta.46
    @storybook/theming: 5.2.0-beta.46 => 5.2.0-beta.46
```

**Additional context**
Mentioning @maikthomas and @VaclavSir in case they've found a solution.  Maybe I need to switch to the new docs format instead of `addon-info`?

**Comment by shilman** [comment]
AFAIK docs does not yet support flow. However, `addon-docs` is being actively developed and maintained whereas `addon-info` is not. So your chances of getting support there is considerably better. at the same time, i'll note that i'll be relying on one of our flow users to figure it out. i don't use flow myself, and there is an unending list of other issues that i'm already signed up for.

**Comment by maikthomas** [comment]
Hi @IanVS, we ended up with something like this in our storybook presets
```module.exports = {
    async babel() {
        /*
            This return does that storybooks only uses our .babelrc so we don't have the problem of babel plugin react-docgen.
                - The problem: https://github.com/storybooks/storybook/issues/4873
                - Inspiration to workaround: https://storybook.js.org/docs/presets/writing-presets/#advanced-configuration
        */
        return {
            babelrc: true,
        };
    },
```

**Comment by IanVS** [comment]
@maikthomas thanks for the tip, but I'm not able to get that working so far.  It would be great if we could keep this open until the bug is fixed.

**Comment by shilman** [comment]
FYI I believe flow is supported in addon-docs now.
