### ISSUE TITLE
[addon-contexts] Toolbar does not reset between stories with/without contexts

### ISSUE THREAD

**Issue by clintandrewhall** [storybookjs/storybook#8019]
**Describe the bug**
If I write stories that use the contexts addon, and then switch to a story that does not, the toolbar icon persists.  If I load a story that does not use contexts add-on first, the toolbar icon is not present... so I would expect it to go away when the process is reversed.

**To Reproduce**
1. Refresh the storybook browser window.
2. Load a story that does not use the context add-on - note the toolbar icon is missing.
3. Load a story that uses the add-on - note the toolbar icon is loaded.
4. Load a story that does not - the toolbar icon persists.
5. Reload the browser - the toolbar icon is missing.

**Expected behavior**
I would expect the icon to exist based on if the story uses the addon or not.

**Code snippets**

I'm adding the add-on only in stories, not elsewhere.

```
storiesOf('components/SomeContextComponent', module)
  .addDecorator(withContexts(contexts))
  .add('SomeContextComponent', () => <SomeContextComponent />);
```

**Comment by leoyli** [comment]
I will take a look this weekend, thanks!

**Comment by clintandrewhall** [comment]
Hi @leoyli -- I was curious if you'd made any headway, and if I could be of any help?
