### ISSUE TITLE
[addon-contexts] Story does not refresh when different context is selected.

### ISSUE THREAD

**Issue by clintandrewhall** [storybookjs/storybook#8020]
**Describe the bug**
When I change contexts, the component story does not refresh to reflect the change.  I have to select a different component for the change to take effect.

**To Reproduce**
1. Load a context-driven story.
2. Change contexts - note the component does not change.
3. Change stories - note the story reflects the new context.
4. Change to original component - the previous story is now correct.

**Expected behavior**
I would expect the component to immediately reflect the context change.

**Code snippets**

I'm using `createContext` from React to maintain state across components.  My Context Provider mock alters one parameter the initial state of that component when changing context through the addon.

**Comment by clintandrewhall** [comment]
More information: I added a `console.log` in my story and in my context:

```ts
// context.ts
<ExternalEmbedStateProvider initialState={state}>
  <Container>
    {console.log('CONTEXT MOCK', state.name)}
    {children}
  </Container>
</ExternalEmbedStateProvider>

// component.ts
storiesOf('runtime/Footer', module)
  .addDecorator(withContexts(contexts))
  .add('Footer', () => (
    <div style={{ height: 172 }}>
      {console.log('re-render')}
      <Footer />
    </div>
  ))
```

In the console, `re-render` was logged **before** `CONTEXT MOCK`.

![Screen Shot 2019-09-06 at 12 45 53 PM](https://user-images.githubusercontent.com/297604/64448893-4e658200-d0a4-11e9-9fa2-43f52317dfbb.png)

**Comment by leoyli** [comment]
I will take a look this weekend, thanks!

**Comment by clintandrewhall** [comment]
Hi @leoyli -- I was curious if you'd made any headway, and if I could be of any help?

**Comment by agrohs** [comment]
Did this ever get resolved?

**Comment by shilman** [comment]
FYI, I'm deprecating `addon-contexts` in 6.0 and have created a new addon, `addon-toolbars` that achieves the same result in a simple/standard/ergonomic/cross-framework way. If you can upgrade, I highly recommend it:

https://github.com/storybookjs/storybook/tree/next/addons/toolbars
