### ISSUE TITLE
Debounce input filtering on sidebar tree

### ISSUE THREAD

**Issue by fforres** [storybookjs/storybook#8031]
**Is your feature request related to a problem? Please describe.**
We have a somewhat big project currently using storybook, and while filtering with the search box, it is a bit janky and as an experience, it doesn't feel great that it filters on every keystroke.

**Describe the solution you'd like**
Just adding a simple debounce to the filtering function being called (With a 250ms time?)

**Describe alternatives you've considered**
Nothing besides that.

**Are you able to assist bring the feature to reality?**
Yep. 

**Additional context**

**Comment by fforres** [comment]
Closed since #8032 	is merged

**Comment by shilman** [comment]
Olé!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-alpha.0 containing PR #8032 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.
