### ISSUE TITLE
Old version of react-syntax-highlighter breaking pnpm builds

### ISSUE THREAD

**Issue by Sureiya** [storybookjs/storybook#8038]
**Describe the bug**
@storybook/components is using an older version of react-syntax-highlighter that imports old versions of babel. I believe it is missing a peerDependency on the package 'babel-runtime' that isn't getting resolved correctly. The updated react-syntax-highlighter references '@babel/runtime' and therefore builds properly. I've tested this change and confirmed that builds pass, however the react-syntax-highlighter API has changed so the component needs to be rewritten.

**To Reproduce**
1. Setup a new empty CRA project with Storybook.
2. Install dependencies using pnpm install
3. run pnpm run build-storybook

**Expected behavior**
Build to run and resulting storybook to run

**System:**

Environment Info:

  System:
    OS: Windows 10
    CPU: (6) x64 Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
  Binaries:
    Node: 10.16.3 - C:\Program Files\nodejs\node.EXE     
    Yarn: 1.16.0 - ~\AppData\Roaming\npm\yarn.CMD        
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.267.0
  npmPackages:
    @storybook/react: 5.1.11 => 5.1.11

**Additional context**

Related to #5338

**Comment by shilman** [comment]
@Sureiya Does this fix it? https://github.com/storybookjs/storybook/pull/8266
