### ISSUE TITLE
Storybook Options Documentation Unclear

### ISSUE THREAD

**Issue by zeebenzene** [storybookjs/storybook#8044]
I'm adding some components to storybook which are multi-lingual.  The current way that I'm going about this is by creating a new story and setting the prop manually in the react component. 

Specifically I'm doing this
~~~~
storiesOf('Switcher', module).add('Russian', () => <Button language="ru" />);
storiesOf('Switcher', module).add('Kiswahili', () => <Button language="sw" />);
storiesOf('Switcher', module).add('Chinese', () => <Button language="zh" />);
~~~~

This works fine but it would be better to allow this to be a parameter somehow in the UI.  I'm not sure if this is possible but it seemed like the Options Parameter might be something that I could use for this.  

However it was unclear for me from the documentation what the per-story options parameter would even be used for - how it would look if I successfully used it, and so on.

I think there's some clarity that could be added to that documentation. However am I even on the right track?  Is what I'm asking for even possible in storybook?

**Comment by shilman** [comment]
@zeebenzene Depends on what you want to achieve! I'd probably take a look at this: https://github.com/storybookjs/storybook/tree/next/addons/contexts
