### ISSUE TITLE
Feature request: pass aggregateTimeout to Webpack

### ISSUE THREAD

**Issue by nategreen** [storybookjs/storybook#8046]
Hi 👋. Storybook is awesome; thanks for making it.

**Is your feature request related to a problem? Please describe.**
Sort of. When I'm running Storybook in watch mode, I'm also running a watcher on my Angular library. When/while the library builds, several file changes take place, and Webpack/Storybook responds to each of these changes, resulting in several duplicate/overlapping rebuilds. But, I'm not able to reload the page and see the changes until all builds have finished. So, one actual change to the library can take almost a minute to see in Storybook—by the time the library builds, then Storybook builds 2 or 3 times.

**Describe the solution you'd like**
I'd like to [pass a delay to Webpack's `aggregateTimeout` option](https://webpack.js.org/configuration/watch/#watchoptionsaggregatetimeout). I _think_ that would allow me to set a long enough time out for the Angular build to complete, after which Storybook could respond and rebuild.

(I'd rather avoid a custom Webpack config just for this _one thing_ but I could certainly do that as a workaround.)

**Describe alternatives you've considered**
As you might've guessed, I am pointing Storybook to the `dist` output of this library rather than directly to the TypeScript; an alternative would be to point it to the source, but I'd rather not do that, since that's not the version downstream projects will see/use.

**Are you able to assist bring the feature to reality?**
Only by being opinionated. 😬

**Comment by shilman** [comment]
@nategreen This is exactly what full customization is for, and I'd recommend you go that route. Let's leave this issue around and see if there are lots of requests, but otherwise, I doubt we'd put it into core when there's already a mechanism that makes it easy to get this. Please let me know if I'm missing something though! :)
