### ISSUE TITLE
Addon-docs: Configuration of DocsContent max-width (styles)

### ISSUE THREAD

**Issue by alazurenko** [storybookjs/storybook#8051]
Greetings Dear Maintainers, 

**Is your feature request related to a problem? Please describe.**
I'd like to have control over DocsContent width. Currently, it's set to 800px. Is there is a way to change it? 
https://github.com/storybookjs/storybook/blob/376b793f2a6699108c230988f077b05adde4a92b/lib/components/src/blocks/DocsPage.tsx#L48

**Describe the solution you'd like**
I would like to have options to change the width of docs content in configuration/theme to addon docs, so it is set for every story. Even more, there would be nice to have more control over container's styling.

**Describe alternatives you've considered**
I have tried to use css classes they are being overwritten  

**Are you able to assist bring the feature to reality?**
Yes

**Comment by alazurenko** [comment]
[This issue](https://github.com/storybookjs/storybook/issues/8004) seems to be related to this one.

**Comment by shilman** [comment]
Cc @domyen who owns docs theming 🙏

**Comment by domyen** [comment]
Hey @alazurenko good idea. We should add a static `className` to allow you to target it reliably (chatted to @shilman about this just now)
 
We're unlikely to add this support to the theme explicitly because we want to keep the API small for now.

**Comment by shilman** [comment]
Yee-haw!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-alpha.1 containing PR #8061 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Jeepers creepers!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.2 containing PR #8061 that references this issue. Upgrade today to try it out!

**Comment by alazurenko** [comment]
Thank you!
