### ISSUE TITLE
Global Knobs using decorators

### ISSUE THREAD

**Issue by vinceumo** [storybookjs/storybook#8052]
Hi, first thanks a lot for this amazing project.

I want to create a Storybook panel where the user can access and edit all the root CSS custom properties of the page (They could be defined in a separate file). I want the user to be able to edit the values of these and append the new values in the Iframe:

```html
<style>
:root {
  --myCssCustomProperty: 1rem;
}
</style>
<Component/>
```

I was thinking to use Knobs and a custom component to do so. But can't find a way or using it globally and added this custom component to overwrite the CSS variables. I need as well to use Knobs at the component level to pass some props to my components.

Is there any way I can achieve this using Knobs or something else?

Thanks a lot.

**Comment by shilman** [comment]
@vinceumo have you looked at this? https://github.com/storybookjs/storybook/tree/next/addons/contexts

**Comment by vinceumo** [comment]
Hi @shilman, I did try Contexts, My understanding is that they are switches. I want the user to be able to modify the props in the panel, When I tried i couldn't figure out how the user could pass custom values (strings) to the Iframe.
