### ISSUE TITLE
Feat req: Show component name in page <title>

### ISSUE THREAD

**Issue by iKristy** [storybookjs/storybook#8053]
**Is your feature request related to a problem? Please describe.**
When viewing individual component pages in Storybook and reviewing them in my browser history, it's very hard to differentiate which page is which:

<img width="325" alt="Screenshot 2019-09-11 18 52 42" src="https://user-images.githubusercontent.com/7912948/64721915-5ae34380-d4c5-11e9-8dde-5597c11d2f99.png">

**Describe the solution you'd like**
I would love if the component name (re-use the one from the sidebar / URL) would appear in the `<title>` of the page.

**Are you able to assist bring the feature to reality?**
No 🙈 (...or, maybe, if I was pointed to where this is defined)

**Comment by shilman** [comment]
Yeah this is a pretty basic feature we should have. Closing this as duplicate to #866
