### ISSUE TITLE
Addon-docs: Story source not shown when a variable named parameters is declared within CSF story

### ISSUE THREAD

**Issue by enagy27** [storybookjs/storybook#8055]
**Describe the bug**
"No code available" is shown in docs preview when a variable, `parameters`, is declared at the top level in a CSF file.

**To Reproduce**
Uncomment the commented lines in this code snippet:
```
import React from 'react';
import { text } from '@storybook/addon-knobs';
import FormatSentence from '.';
// import { packageName } from '../../constants/stories';

// const componentSubtitle = `import FormatSentence from '${packageName}/lib/elements/format_sentence';`;

// const parameters = {
//   componentSubtitle,
// };

export const basic = () => {
  const sentence = text('sentence', 'This is a \uE000test\uE001 sentence.');
  return <FormatSentence sentence={sentence} />;
};

export default {
  title: 'Elements|FormatSentence',
  component: FormatSentence,
  // parameters,
};
```

**Expected behavior**
Both the commented and uncommented version of the snippet should behave the same.

**System:**
Environment Info:

  System:
    OS: macOS 10.14.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 10.16.0 - /usr/local/opt/node@10/bin/node
    Yarn: 1.17.3 - ~/workspace/component-library/node_modules/.bin/yarn
    npm: 6.5.0 - ~/workspace/component-library/node_modules/.bin/npm
  Browsers:
    Chrome: 76.0.3809.132
    Safari: 12.1.1
  npmPackages:
    @storybook/addon-a11y: ^5.2.0-rc.11 => 5.2.0-rc.11 
    @storybook/addon-actions: ^5.2.0-rc.11 => 5.2.0-rc.11 
    @storybook/addon-docs: ^5.2.0-rc.11 => 5.2.0-rc.11 
    @storybook/addon-knobs: ^5.2.0-rc.11 => 5.2.0-rc.11 
    @storybook/addon-links: ^5.2.0-rc.11 => 5.2.0-rc.11 
    @storybook/addon-viewport: ^5.2.0-rc.11 => 5.2.0-rc.11 
    @storybook/addons: ^5.2.0-rc.11 => 5.2.0-rc.11 
    @storybook/preset-scss: 1.0.2 => 1.0.2 
    @storybook/preset-typescript: 1.1.0 => 1.1.0 
    @storybook/react: ^5.2.0-rc.11 => 5.2.0-rc.11 
    @storybook/source-loader: 5.2.0-rc.11 => 5.2.0-rc.11 
    @storybook/theming: ^5.2.0-rc.11 => 5.2.0-rc.11

**Comment by shilman** [comment]
@enagy27 Can repro. @enagy27 There's something about the `source-loader` generated code that doesn't like the parameters variable.

**Comment by patdryburgh** [comment]
@shilman Just wanted to let you know that I'm experiencing this as well, but I haven't added a `parameters` variable to any of my default exports.

**Comment by shilman** [comment]
@patdryburgh can you try the latest 5.3 prerelease on `next` and let me know more details if it still fails? we've made a handful of improvements to the source-loader during the alpha

**Comment by tolerance-go** [comment]
same problem, and I use `storiesOf` method, still is not ok

**Comment by shilman** [comment]
@tolerance-go do you have a repro?

**Comment by tolerance-go** [comment]
after the overall upgrade of the storybook package, my problem was solved

**Comment by tolerance-go** [comment]
https://github.com/tolerance-go/markv/blob/d53c41486275730118731e932a456dad6abd73aa/src/components/MarkdownEditor/stories/index.stories.js#L15 

same issue，I upgraded to CSF ​​story export

**Comment by shilman** [comment]
@tolerance-go Source-loader doesn't support fully dynamic titles. Please use a static variable or a template literal.

```js
export default {
  title: "components|MarkdownEditor",
  // title: route,
  component: MarkdownEditor
};
```

**Comment by 0x0006e** [comment]
> @tolerance-go Source-loader doesn't support fully dynamic titles. Please use a string constant or template literal.
> 
> ```js
> export default {
>   title: "components|MarkdownEditor",
>   // title: route,
>   component: MarkdownEditor
> };
> ```
😔
