### ISSUE TITLE
Addon-docs: Enable dynamic titles in .mdx stories

### ISSUE THREAD

**Issue by jonathanherdt** [storybookjs/storybook#8060]
**Is your feature request related to a problem? Please describe.**
For the sake of consistency and because I imagine writing a lot of stories, I would like to use a file that defines the titles for my story folders, like so:

```js
export default {
	gettingstarted: "MyProject|Getting Started",
	guidelines: "MyProject|Guidelines",
	components: "MyProject|Components",
	resources: "MyProject|Resources",
	updates: "MyProject|Updates",
	help: "MyProject|Help"
}
```

I would like to use the contents of this file in my stories, like so:

```js
import storyHierarchy from "../story-hierarchy";
storiesOf(`${storyHierarchy.components}.Calendar`, module)
```

When I try to do the same with a `.mdx` story, it is not possible:

```mdx
import storyHierarchy from "../story-hierarchy";
<Meta title={`${storyHierarchy.components}.Calendar`} />
```

This problem can be boiled down to the most simple case in that any form of dynamic content does not work:

```mdx
<Meta title={"Getting Started.Developers"} />
```

**Describe the solution you'd like**
I would like to be able to use recurring titles in my stories so I can make sure they always end up at places in the hierarchy where I would expect them to be.

**Describe alternatives you've considered**
I have not considered alternatives

**Are you able to assist bring the feature to reality?**
If given instructions where to look at, I would gladly contribute.

**Additional context**
No additional context

**Comment by patricklafrance** [comment]
Almost working. It works fine in the nav bar and for canvas. The remaining problem is that the stories are unavailable in docs.

https://cdn.discordapp.com/attachments/551682580941111296/659509145338118157/unknown.png
![image](https://user-images.githubusercontent.com/794579/71452549-0736f600-2754-11ea-8761-38bd58d72977.png)

@atanasster drill down the problem to be with `mdxStoryNameToId`.

> the issue is with the mdxStoryNameToId being stored at mdx compile time, when the template strings are not yet evaluated

**Comment by shilman** [comment]
@patricklafrance @atanasster Can you create a branch and add a repro to official storybook? I tried this and it worked for me:

```
import { Story, Meta } from '@storybook/addon-docs/blocks';

# Dyamic title

export const foo = 'foo'

<Meta title={`Addons/Docs/dynamic-title-${foo}`} />

## Stories

<Story name="testing" inline={false}>
  <>hello</>
</Story>
```

**Comment by patricklafrance** [comment]
@shilman there you go: https://github.com/storybookjs/storybook/blob/8060-dynamic-title-mdx-issue/examples/official-storybook/stories/addon-docs/meta-string-template.stories.mdx

![image](https://user-images.githubusercontent.com/794579/71455156-d8278100-2761-11ea-914a-3d2266b55373.png)

**Comment by shilman** [comment]
Yee-haw!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-rc.4 containing PR #9248 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
