### ISSUE TITLE
@storybook/polymer not working in IE11

### ISSUE THREAD

**Issue by jorenbroekema** [storybookjs/storybook#8065]
**Describe the bug**
Storybook is broken in IE11 with error in console:

**To Reproduce**
1. Create a simple storybook scaffold, all defaults
2. Install dependencies: lit-html and @storybook/polymer
3. Create a stories.js file with:
```js
import { html } from 'lit-html'
import { storiesOf } from '@storybook/polymer';

storiesOf('Test', module)
  .add('Default', () => html`<div>Hello, World!</div>`);
```
4. Run start-storybook, open in IE11, it works great!
5. Now run build-storybook, open index.html of the output in IE11 -> Error + blank page 😭. 

**Expected behavior**
Working example in IE11

**System:**
```
Environment Info:

  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
  Binaries:
    Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.17.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    @storybook/html: ^5.1.11 => 5.1.11
```

**Comment by jorenbroekema** [comment]
Odd.. I cannot reproduce this anymore... I'm on a slightly different machine (still Windows 10), but now building storybook -> serve it, works just fine, consistently as well. IE just being flaky I suppose, I'm not sure.

I guess I'll close this.

**Comment by shilman** [comment]
Thanks! Lmk if it comes up again!
