### ISSUE TITLE
Addon-docs: Make anchor links work without being thrown into iframe.html

### ISSUE THREAD

**Issue by jonathanherdt** [storybookjs/storybook#8068]
**Is your feature request related to a problem? Please describe.**
I created a rather long document (a changelog) and wanted to make navigation easier by providing anchor links. The anchor links work but they take me to the `iframe.html` version of the story I'm looking at.

Minimal example:

```
[Test](#a)
```

**Describe the solution you'd like**
I would like it so that clicks on an anchor link keep me on the current page and just scroll the content there.

**Describe alternatives you've considered**
I did not consider alternatives since the current behavior is not perfect but works.

**Are you able to assist bring the feature to reality?**
no

**Additional context**
This works as intended [on the MDX playground](https://mdxjs.com/playground) so I guess this is an issue with Storybook.

**Comment by shilman** [comment]
Closing this as a duplicate to #8184

**Comment by shilman** [comment]
Whoopee!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-alpha.46 containing PR #8132 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.
