### ISSUE TITLE
Wait for page to load completely

### ISSUE THREAD

**Issue by faun** [storybookjs/storybook#8076]
**Is your feature request related to a problem? Please describe.**
When taking a screenshot of a Storybook page, there are often elements missing, as the 
`window.load` event loads before all of the stories have rendered.

**Describe the solution you'd like**
It would be great if there was an event that was emitted or a selector that I can rely on to determine if all of the stories on a given page are have finished rendering and there are no more outstanding XHR requests and the page is fully painted. Is there an event I can subscribe to that Storybook emits when this state has been achieved?

**Describe alternatives you've considered**
Listen for `window.load` event, which is fired before any storybook events have been rendered.

**Are you able to assist bring the feature to reality?**
No

**Additional context**
I'm using Chrome (via remote developer protocol) and Firefox (via Selenium) currently. I'm not sure if that matters.

Edit: change `DOMContentLoaded` to `window.load` to accurately represent the situation.

**Comment by faun** [comment]
This question still stands, robot.

**Comment by shilman** [comment]
We deal with this in [Chromatic](https://www.chromaticqa.com/) and AFAIK I know there is no easy way to do this on the Storybook side in a browser-independent way.

**Comment by sunecosuri** [comment]
I'm running into the same challenge, and I'd love to hear from anyone who has ideas, even workaround.

**Comment by shilman** [comment]
I responded earlier about [Chromatic](https://www.chromatic.com/)'s heuristics for this. If you're looking for something purely open-source, the [Test runner](https://github.com/storybookjs/test-runner) also contains some support for this. Also Storybook [play functions](https://storybook.js.org/docs/react/writing-stories/play-function) allow you to wait for things programmatically, post-render.
