### ISSUE TITLE
About the error "Module build failed (from ./node_modules/babel-loader/lib/index.js)"

### ISSUE THREAD

**Issue by mozgbrasil** [storybookjs/storybook#8077]
About the error "Module build failed (from ./node_modules/babel-loader/lib/index.js)"

Hello my friends

As per images

I followed the registration process of the following addon

https://github.com/storybookjs/storybook/tree/master/addons/viewport

But in the terminal we see the error return

Can you help me ?

![Captura de tela de 2019-09-13 18-32-50](https://user-images.githubusercontent.com/17202780/64896452-47b3ad80-d656-11e9-95a8-d8d0a9e3ec57.png)
![Captura de tela de 2019-09-13 18-33-54](https://user-images.githubusercontent.com/17202780/64896453-484c4400-d656-11e9-80e4-c423c94021f5.png)
![Captura de tela de 2019-09-13 18-33-59](https://user-images.githubusercontent.com/17202780/64896454-484c4400-d656-11e9-8af1-c551c0e031d3.png)
![Captura de tela de 2019-09-13 18-38-54](https://user-images.githubusercontent.com/17202780/64896455-484c4400-d656-11e9-9e70-fc9c58ac9de2.png)
![Captura de tela de 2019-09-13 18-39-03](https://user-images.githubusercontent.com/17202780/64896456-484c4400-d656-11e9-8212-734eb6270d4e.png)
![Captura de tela de 2019-09-13 18-39-34](https://user-images.githubusercontent.com/17202780/64896457-484c4400-d656-11e9-8f65-65f5511fb36a.png)

**Comment by Ajayghoshm** [comment]
Any Solution?

**Comment by ndelangen** [comment]
```
.add(() => </>, {})
```

is not valid JSX AFAIK
