### ISSUE TITLE
CSF issues when using ES6 Proxy object in story title

### ISSUE THREAD

**Issue by manuelbieh** [storybookjs/storybook#8084]
**Describe the bug**
I did two things and failed at it and I'm not sure if it's my fault or a bug in Storybook. 

First thing: I converted my existing stories to the new Component Story Format using the codemod in the migration guide. (This part worked mostly fine 😉)

Second thing: I used an ES6 Proxy for the first time, to toy around with Proxies, with the goal of having a little bit nicer syntax for abstracting my story titles away and to avoid string interpolation. Precisely, I used ```Group.Layout('Grid')``` instead of ``` `${HierarchyGroups.LAYOUT}Grid` ```

This causes storybook to fail with a `TypeError: Cannot read property 'toLowerCase' of undefined`. I was able to narrow it down to the part where I am using the Proxy. I can console.log it in the story and it correctly say `Layout|Footer` and I can also use it in the old `storiesOf()` format stories without any issues. Once I use a default export like: `export default { title: Group.Layout('Footer') };` it fails with the error message above.

**To Reproduce**
`git clone git@github.com:manuel-bieh/ui.git`
`git checkout chores-storybook-5.2`
`yarn start`

Go to this file and change the default export to the one annotated with "Fails":
https://github.com/manuel-bieh/ui/blob/chores-storybook-5.2/src/Footer/Footer.stories.js

The proxied object I use to create the title strings can be found here:
https://github.com/manuel-bieh/ui/blob/chores-storybook-5.2/.storybook/config.js#L11

**Expected behavior**
Storybook should work without throwing an error

**System:**
```
Environment Info:

  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
  Binaries:
    Node: 10.15.3 - C:\cygwin64\tmp\yarn--1568566952300-0.20670909143867577\node.CMD
    Yarn: 1.17.3 - C:\cygwin64\tmp\yarn--1568566952300-0.20670909143867577\yarn.CMD
    npm: 6.5.0 - C:\htdocs\_git\@manuel-bieh\ui\node_modules\.bin\npm.CMD
  Browsers:
    Edge: 44.18362.329.0
  npmPackages:
    @storybook/addon-storysource: 5.2.0-rc.11 => 5.2.0-rc.11
    @storybook/addons: 5.2.0-rc.11 => 5.2.0-rc.11
    @storybook/cli: 5.2.0-rc.11 => 5.2.0-rc.11
    @storybook/react: 5.2.0-rc.11 => 5.2.0-rc.11
```

**Comment by shilman** [comment]
This might be dupe to https://github.com/storybookjs/storybook/issues/8060

I'll take a look at both in the next couple days
