### ISSUE TITLE
Error handling broken in Storybook 5.2

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#8087]
In 5.2, errors are silently swallowed.

In 5.1, story errors would result in the stack trace showing up in the main window:

<img width="1078" alt="Storybook" src="https://user-images.githubusercontent.com/488689/64954225-f02e6100-d852-11e9-8852-6022c5975aaf.png">

To repro in monorepo:

```
cd examples/official-storybook
yarn storybook
```

Open `Core > Errors > story throws exception` (and compare to `release/5.1` branch).

**Comment by shilman** [comment]
I believe the problem is related to preview hooks. First, it seemed like it was `source-loader` related, but when I removed the source-loader (by removing the addon-docs preset and also `*.stories.mdx` in `official-storybook`), I see the following error in the stack trace:

```
    hooks.nextHookIndex = 0;
    var prevContext = _global.window.STORYBOOK_HOOKS_CONTEXT;
    _global.window.STORYBOOK_HOOKS_CONTEXT = hooks;
    var result = fn.apply(void 0, arguments);
    _global.window.STORYBOOK_HOOKS_CONTEXT = prevContext;
```

I believe this code needs an exception handler and ultimately needs to call `showError`

**Comment by Hypnosphi** [comment]
@tmeasday do you think we can find a way to enable chromatic testing for those error stories?

**Comment by tmeasday** [comment]
@Hypnosphi do you have any ideas about how that could work? Chromatic is designed so that an error needs to be resolved before you can start accepting/denying changes as a matter of course.

In any case we want to capture the actual error div etc which falls outside of the way that Chromatic captures (we get the contents of the `#root` element). One way we could do it is using an iframe maybe, although that's a bit of a hack.

**Comment by Hypnosphi** [comment]
yes, I think I can just add a story that renders iframes with other stories

**Comment by shilman** [comment]
Whoopee!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-alpha.0 containing PR #8097 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Yippee!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.1 containing PR #8097 that references this issue. Upgrade today to try it out!

**Comment by shilman** [comment]
Probably needs another fix, but better to get something out for the influx of new users. Will close this after we finalize what's in #8100

**Comment by shilman** [comment]
Shiver me timbers!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-alpha.9 containing PR #8100 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Yowza!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.2 containing PR #8100 that references this issue. Upgrade today to try it out!
