### ISSUE TITLE
TypeScript, router, & react-native produce type error

### ISSUE THREAD

**Issue by mAAdhaTTah** [storybookjs/storybook#8095]
**Describe the bug**
```
$ tsc
node_modules/@types/reach__router/index.d.ts:9:37 - error TS2339: Property 'location' does not exist on type 'Window'.

9 export type WindowLocation = Window["location"] & HLocation;
                                      ~~~~~~~~~~


Found 1 error.
```

**To Reproduce**
1. Set up a react-native project with Storybook@5.2.0
2. Run tsc

**Expected behavior**
No type errors

**Additional context**
`@storybook/router` is pulled in via this chain:

```
@storybook/react-native -> @storybook/client-api -> @storybook/router -> @types/reach__router
```

This dep was added in 5.2.0 to `@storybook/router`. I'm not sure I have an obvious solution here, unfortunately. That said, I'm not sure how `@react/router` is used in a React Native project w/ Storybook, since it's web-only.

**Comment by yaelballa** [comment]
Had the same problem, just with React (I'm not using react-native)

As a workaround, you can add location property on the global window type:

```
declare module 'storybook-router' {
    global {
        interface Window {
            location: any
        }
    }
}
```

**Comment by SophieDonut** [comment]
it's still an issue...

**Comment by Gongreg** [comment]
Hi @SophieDonut, we are going to separate out react native part of storybook to a separate repo, that should make solving issues like these easier in the future. :)
