### ISSUE TITLE
All live examples are down

### ISSUE THREAD

**Issue by ludwigbacklund** [storybookjs/storybook#8108]
**Describe the bug**
All live examples on the website are down.

**To Reproduce**
1. Go to https://storybook.js.org/docs/basics/live-examples/
2. Click on any example

**Expected behavior**
They should not be down

**Screenshots**
<img width="811" alt="Screenshot 2019-09-18 at 09 51 27" src="https://user-images.githubusercontent.com/13007299/65128557-f448b300-d9f9-11e9-800d-7c2ec24931f5.png">

**Comment by youcanping** [comment]
我刚看也是这样，不知道怎么回事呢？

**Comment by jholt1** [comment]
If you go to https://monorepo-git-master.storybook.now.sh/ you can see all of the examples, but all the links are broken in the documentation.
