### ISSUE TITLE
Typescript build fail when removing @types/storybook__react

### ISSUE THREAD

**Issue by sami616** [storybookjs/storybook#8110]
My understanding is that the `@types` package is no longer needed for `@storybook/react`. However when i uninstall the module i get the below error when trying to build my project.

```
ERROR in [at-loader] ./node_modules/@storybook/react/dist/client/preview/index.d.ts:2:23 
    TS2688: Cannot find type definition file for 'webpack-env'.
```

Have i misunderstood ?

**Comment by shilman** [comment]
This might be a typing bug. @kroeder fixed this for Angular by removing those typings from `tsconfig.json`, but it seems like maybe we need to do that across the board.

**Comment by hipstersmoothie** [comment]
I can remove that line from my node_modules and see if it build. If it does I can remove them all for the different apps and add that to my PR

**Comment by shilman** [comment]
Just to be clear, I don't know what the right fix is. Maybe we need to add the dep across the board. Maybe we need to move it from tsconfig.json across the board. Or maybe it's case by case. I don't know enough about what's going on, just making sure the right hand is talking to the left. 😅

**Comment by sami616** [comment]
Just to confirm, i'm now not seeing this oddly, i think it may be linked to addon-docs, which im having trouble setting up with TS. Will investigate further and come back to you! Thanks!

**Comment by hipstersmoothie** [comment]
If it's a needed type it for sure needs to be moved from devDeps to deps somewhere.

**Comment by ndelangen** [comment]
https://github.com/storybookjs/storybook/pull/8119

**Comment by shilman** [comment]
Crikey!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-alpha.3 containing PR #8119 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

**Comment by shilman** [comment]
Shiver me timbers!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.2 containing PR #8119 that references this issue. Upgrade today to try it out!
