### ISSUE TITLE
New Component Story Format (CSF) doesn't work with old recommended way to load stories

### ISSUE THREAD

**Issue by hipstersmoothie** [storybookjs/storybook#8122]
**Describe the bug**

When trying to switch to CSF none of my stories were loading. Looking at the docs it seems like you can now call configure a little differently:

```js
configure(require.context('../stories', true, /\.stories\.js$/), module);
```

When i switch my `config.js` to this the CSF stories load. but when I use the old way I am greeted with no stories and no helpful error message.

*the old way*

```js
function loadStories() {
  const req = require.context(
    require.context('../stories', true, /\.stories\.js$/)
  );

  req.keys().forEach(req);
}

configure(loadStories, module);
```

**To Reproduce**
1. Clone https://github.com/hipstersmoothie/storybook-bug
2. `yarn`
3. `yarn storybook`

**Expected behavior**

Loads the stories.

**System:**
Please paste the results of `npx -p @storybook/cli@next sb info` here.

**Comment by shilman** [comment]
@hipstersmoothie It's not supposed to and it actually can't. It's documented here: https://storybook.js.org/docs/basics/writing-stories/#loading-stories

**Comment by hipstersmoothie** [comment]
Ah I see it looks like I was almost doing the right thing. I just have to return the required stories.

**Comment by sergej-s** [comment]
CFS isn't loaded also if I use `require-context.macro` as described here https://www.npmjs.com/package/@storybook/addon-storyshots#configure-jest-to-work-with-webpacks-requirecontext (Option 2)
So tests don't work with migrated stories :(

**Comment by shilman** [comment]
I think that's being addressed by #8000 ?

**Comment by donaldpipowitch** [comment]
Also I followed CSF closely I seem to have missed that part every time 🤔 You also can't mix'n'match the old format and new format correct? (`Loader function passed to 'configure' should return void or an array of module exports that all contain a 'default' export.`)

**Comment by shilman** [comment]
@donaldpipowitch You can mix and match, you just need to do it deliberately. See the last code example here:

https://github.com/storybookjs/storybook/blob/next/docs/src/pages/basics/writing-stories/index.md#loading-stories

**Comment by arsinclair** [comment]
> @donaldpipowitch You can mix and match, you just need to do it deliberately. See the last code example here:
> 
> https://github.com/storybookjs/storybook/blob/next/docs/src/pages/basics/writing-stories/index.md#loading-stories

Your links in this thread are either dead or don't point to the relevant information...

**Comment by jonniebigodes** [comment]
@arsinclair no need to thank whatsoever, glad that I was able to provide you with some context and put you on the right track to help you get the information you wanted. I'm aware of that, but the documentation required quite an overhaul with Storybook 6.0 release, there were a lot of changes that need to be documented, and based on an analysis from the team it was decided to adjust it accordingly for not only maintainability but to allow easy access to the new features tied to the documentation.

Stay safe!
