### ISSUE TITLE
Addon-docs: Generalize DocsPage prop tables

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#8123]
Storybook's prop tables were written with React in mind, which only has the concept of `props`.

- Vue #6663 has the additional concept of events & slots
- Angular #6664 similarly has other types of props (outputs?)

We should generalize DocsPage to support these different component inputs/outputs.

**Comment by alexlafroscia** [comment]
Just to add additional use-case ideas, Web Components (which I have been using through the `html` support in Storybook) might want to document

- Props
- Attributes (often overlapping, but not always)
- Slots
- Events
- CSS variables

You can get an idea of how this is being used right now here: https://github.com/storybookjs/storybook/issues/4600#issuecomment-532741672

**Comment by raihle** [comment]
For Vue (dunno about Angular or other frameworks) it would also be interesting to support `methods`. E.g. https://buefy.org/documentation/collapse#api-view

**Comment by shilman** [comment]
Whoopee!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-alpha.28 containing PR #8489 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Yowza!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-alpha.29 containing PR #8567 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

**Comment by shilman** [comment]
Son of a gun!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-alpha.34 containing PR #8632 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.
