### ISSUE TITLE
[addon-docs]: No content in the Description.

### ISSUE THREAD

**Issue by ellisio** [storybookjs/storybook#8124]
**Describe the bug**
Defining `propTypes` is not generating the `description` column.

**To Reproduce**
1. Create a basic component with a documented `propType`. 
2. Create a story to demonstrate the component.
3. Verify the `Description` column is not populated.

**Expected behavior**
The `Description` column should contain the content in the jsdoc.

**Code snippets**

*Tester.js:*
```
import React from 'react';
import PropTypes from 'prop-types';

const Tester = ({ children, variant }) => (
  <div variant={variant}>{children}</div>
);

Tester.propTypes = {
  children: PropTypes.any.isRequired,
  /**
   * The variant to use.
   */
  variant: PropTypes.string,
};

Tester.defaultProps = {
  variant: 'default',
};

export default Tester;
```

*Tester.story.js:*
```
import React from 'react';
import Tester from './Tester';

export default {
  title: 'Design System|Tester',
  component: Tester,
};

export const Buttons = () => (
  <React.Fragment>
    <Tester variant="primary">Primary</Tester>
  </React.Fragment>
);
```

**System:**
```
Environment Info:

  System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 12.10.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.11.1 - ~/Developer/salesmessage/arcadia-ui/node_modules/.bin/npm
  Browsers:
    Chrome: 76.0.3809.132
    Firefox: 63.0.3
    Safari: 12.1.2
  npmPackages:
    @storybook/addon-a11y: 5.2.1 => 5.2.1 
    @storybook/addon-actions: 5.2.1 => 5.2.1 
    @storybook/addon-docs: 5.2.1 => 5.2.1 
    @storybook/addon-knobs: 5.2.1 => 5.2.1 
    @storybook/addon-links: 5.2.1 => 5.2.1 
    @storybook/addon-storysource: 5.2.1 => 5.2.1 
    @storybook/addons: 5.2.1 => 5.2.1 
    @storybook/react: 5.2.1 => 5.2.1 
```

**Additional information:**

I have tried various jsdoc formats, none are working.

```
/**
 Testing.
*/

/**
 * Testing.
 */

/** Testing. */
```

**Comment by ellisio** [comment]
I literally went to sleep, woke up, and restarted storybook. Now I have Description values. I changed absolutely nothing. Closing this... 😕

**Comment by shilman** [comment]
What do your config/presets files contain?

**Comment by shilman** [comment]
Lol ok 👌

**Comment by BenjaminVanRyseghem** [comment]
got the same issue :/

I tried several variations, tried with a fresh install, still got no descriptions... (also when I build the static doc, all `required` props are gone). I feel like I got something missing, but I can't find it.

If anyone have any hint

**Comment by davidouanounou** [comment]
Same here :)  If anyone have any hint

**Comment by ellisio** [comment]
@BenjaminVanRyseghem @davidouanounou Storybook has a cache. If I remember correctly (haven't run into this issue since then), you just need to remove any build foot print from `node_modules/.cache` then restart Storybook. Might be a directory in `.storybook/*` as well.

**Comment by davidouanounou** [comment]
Thanks Andrew. I’ll make a try and let you know.

Le mer. 9 oct. 2019 à 19:14, Andrew Ellis <notifications@github.com> a
écrit :

**Comment by BenjaminVanRyseghem** [comment]
@ellisio I just tried, didn't change a thing 😢

**Comment by shilman** [comment]
Is anybody here using CRA? Might need to add the docgen loader seperately. Cc @mrmckeb

**Comment by brianbento** [comment]
Getting this myself. Any ideas why?

**Comment by Zunaib** [comment]
Any Leads on this ?

**Comment by JGordy** [comment]
Same here, no idea why so far

**Comment by shilman** [comment]
For reference, here's a working setup: https://gist.github.com/shilman/bc9cbedb2a7efb5ec6710337cbd20c0c

Same setup will work with PropTypes. Obviously there are an endless number of combinations, but sometimes having a working example can help get to the bottom of what's going wrong.
