### ISSUE TITLE
a11y-addon: Parameters at story level affect other stories

### ISSUE THREAD

**Issue by donaldpipowitch** [storybookjs/storybook#8126]
**Describe the bug**
`a11y` parameters _at a story level_  affect other stories. Probably they aren't reseted correctly.

**To Reproduce**
https://github.com/donaldpipowitch/storybook-bug-demo-a11y-at-story-level

**Expected behavior**
`a11y` parameters _at a story level_ should not affect other stories.

**System:**

```
  System:
    OS: macOS 10.14.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.17.3 - ~/.yarn/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
  Browsers:
    Chrome: 76.0.3809.132
    Safari: 12.1.2
  npmPackages:
    @storybook/addon-a11y: ^5.2.1 => 5.2.1 
    @storybook/addons: ^5.2.1 => 5.2.1 
    @storybook/react: ^5.2.1 => 5.2.1 
```

**Additional context**
I actually wanted to configure _one story_ with an unknown root element _on purpose_, because the `a11y` check was running _very_ long. It would be nice if there would be an official way to disable the `a11y` check on a _per story level_ or to disable the automatic run. Maybe something like `{ a11y: { manual: true } }` which defaults to `manual: false`?

**Comment by donaldpipowitch** [comment]
Wow, the stale bot got quicker. I eventually would like to fix this myself, but maybe just in months or so to finish a previous project.

**Comment by shilman** [comment]
I've added the `todo` label (which tells the bot to go away) and assigned you! 😄

**Comment by donaldpipowitch** [comment]
Would you be fine with the 'manual' setting as well? See "Additional context". That would be a new feature however, not just a bug fix.

**Comment by shilman** [comment]
@donaldpipowitch I like that idea. Any thoughts @CodeByAlex @jsomsanith-tlnd ?

**Comment by jsomsanith** [comment]
Hi !
To disable an addon per story you have #6923.
But having an option to only run it manually would be awesome.

**Comment by donaldpipowitch** [comment]
> To disable an addon per story you have #6923.

@jsomsanith That's awesome. I never saw that setting before. Thank you. That is a good workaround for me until a "manual run" feature landed.

**Comment by shilman** [comment]
Gadzooks!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-alpha.45 containing PR #8779 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Jeepers creepers!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.7 containing PR #8779 that references this issue. Upgrade today to try it out!

**Comment by shilman** [comment]
Ooh-la-la!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-alpha.0 containing PR #8883 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.
