### ISSUE TITLE
addon-backgrounds doesn't work in iframe.html

### ISSUE THREAD

**Issue by SiAdcock** [storybookjs/storybook#8129]
**Describe the bug**

`addon-backgrounds` does not work in iframe.html that is generated by `build-storybook`. When setting a default background colour for a particular story, this background colour does not show up.

**To Reproduce**
Please follow the instructions here: https://github.com/SiAdcock/storybook-playground

**Code snippets**

```js
// index.stories.js

import React from "react"
import { storiesOf } from "@storybook/react"
import { Button } from "@storybook/react/demo"

storiesOf("Button", module)
  .add("with text", () => <Button>Hello Button</Button>)
  .add(
    "with some emoji",
    () => (
      <Button>
        <span role="img" aria-label="so cool">
          😀 😎 👍 💯
        </span>
      </Button>
    ),
    {
      backgrounds: [
        {
          name: "red",
          value: "rgba(255, 0, 0)",
          default: true
        }
      ]
    }
  )
```

**Expected behavior**
The background colour in `iframe.html?id=button--with-some-emoji` ought to be red

**System:**
```
  System:
    OS: macOS 10.14.3
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
  Binaries:
    Node: 12.10.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 76.0.3809.132
    Firefox: 68.0.1
    Safari: 12.0.3
  npmPackages:
    @storybook/addon-backgrounds: ^5.2.1 => 5.2.1
    @storybook/react: ^5.2.1 => 5.2.1
```

**Additional context**
I believe this is a bug or limitation with addons in iframe.html in general. `addon-links` does not appear to work in iframe.html either - I can probably knock up a minimal reproduction of this if necessary.

**Comment by SiAdcock** [comment]
It occurs to me that this might be a feature request rather than a bug report. Is anyone able to confirm whether this behaviour has previously worked?

**Comment by SiAdcock** [comment]
I've noticed that use of `iframe.html` is not really documented anywhere, so maybe it's not supported. From what I can see, [Zeroheight's Storybook integration](https://help.zeroheight.com/share/Eh0d6pGfMIV2vwA_ozzLBQ/101/p/507ba7) works by embedding `iframe.html` directly into the page. If this is unsupported, it would be really useful to know, so we can try to find an alternative way of embedding a Storybook iframe. We can also potentially close this issue 😅

**Comment by leonardofaria** [comment]
Can confirm: 

I have the buttons in the UI but clicking on them go nowhere - my `config.js`:

```js
  backgrounds: [
    { name: 'default', value: '#f5f5f5', default: true },
    { name: 'indigo', value: '#100d59' },
  ],
});
```

**Comment by shilman** [comment]
@SiAdcock i think having default the background carry over to the iframe popout is a feature request, and a pretty reasonable one. cc @ndelangen

**Comment by shilman** [comment]
@leonardofaria not sure what's going on with your setup -- I can't repro. can you share a reproduction?

**Comment by leonardofaria** [comment]
@shilman my apologies for not including them

```
 npx -p @storybook/cli@next sb info
npx: installed 477 in 82.569s

Environment Info:

  System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Binaries:
    Node: 8.14.1 - ~/.nvm/versions/node/v8.14.1/bin/node
    Yarn: 1.19.0 - /usr/local/bin/yarn
    npm: 5.2.0 - ~/.nvm/versions/node/v8.14.1/bin/npm
  Browsers:
    Chrome: 77.0.3865.90
    Firefox: 70.0
    Safari: 13.0.2
  npmPackages:
    @storybook/addon-a11y: ^5.2.3 => 5.2.3
    @storybook/addon-actions: ^5.2.3 => 5.2.3
    @storybook/addon-centered: ^5.2.3 => 5.2.3
    @storybook/addon-info: ^5.2.3 => 5.2.3
    @storybook/addon-knobs: ^5.2.3 => 5.2.3
    @storybook/addon-links: ^5.2.3 => 5.2.3
    @storybook/addon-options: ^5.2.3 => 5.2.3
    @storybook/addon-viewport: ^5.2.3 => 5.2.3
    @storybook/addons: ^5.2.3 => 5.2.3
    @storybook/react: ^5.2.3 => 5.2.3
```

config.js

```js
import { configure, setAddon, addDecorator } from '@storybook/react'
import infoAddon from '@storybook/addon-info'
import { setOptions } from '@storybook/addon-options'
import { withA11y } from '@storybook/addon-a11y'
import { addParameters } from '@storybook/react';
import { INITIAL_VIEWPORTS } from '@storybook/addon-viewport';

addDecorator(withA11y)

const req = require.context('../src/components', true, /^(?!.*\/node_modules(?=\/).*\/).*\.stories\.js$/)

setAddon(infoAddon)

const loadStories = () => req.keys().forEach((filename) => req(filename))

addParameters({
  viewport: {
    viewports: INITIAL_VIEWPORTS,
  },
  backgrounds: [
    { name: 'default', value: '#f5f5f5', default: true },
    { name: 'indigo', value: '#100d59' },
  ],
});

configure(loadStories, module)
```

addons.js

```js
import '@storybook/addons'
import '@storybook/addon-options/register'
import '@storybook/addon-actions/register'
import '@storybook/addon-knobs/register'
import '@storybook/addon-a11y/register'
import '@storybook/addon-viewport/register'
import '@storybook/addon-backgrounds/register'
```

**Comment by likethemammal** [comment]
This seems to break things for `addon-storyshots-puppeteer` as well, since it uses iframe.html to create snapshot images.

Since `addon-backgrounds` [sets the background-color to the `<iframe>` element](https://github.com/storybookjs/storybook/blob/next/addons/backgrounds/src/containers/BackgroundSelector.tsx#L130) directly, those styles dont get carried over inside iframe.html. This means all the image storyshots have white backgrounds and dont match the same visual of the story.

It looks like handling [background styles was moved from a wrapper within the iframe and applied to the iframe itself](https://github.com/storybookjs/storybook/pull/2807/files#diff-c9a5929950c334d8dc7420ff782e5472L76), so `addon-backgrounds` + `addon-storyshots-puppeteer` used to work. Not sure why this switch was needed, but I imagine an injected wrapper would be one of the best solutions for this.

**Comment by ndelangen** [comment]
This is essentially the same issue as https://github.com/storybookjs/storybook/issues/9283

@lkopacz I know you're currently busy, let me know if you'd be able to work on this, and perhaps we could work on it together for a bit?

**Comment by ndelangen** [comment]
Background addon should use `useAddonState()` to sync the state which background should be displayed, and then edit the HTML in the preview to make the whole html page have the correct background.

**Comment by yptr** [comment]
Are there any news?

**Comment by ndelangen** [comment]
@yptr no news, would you like to contribute by fixing this issue perhaps?

**Comment by araldev** [comment]
# Storybook Theme Sync Solution

## Problem

When using a custom `globalTypes.theme` toolbar in Storybook to control light/dark/system mode, changing the theme updates the component colors (via `data-theme`) but **does not update the iframe background** (canvas or docs).

The component renders correctly because `data-theme` controls CSS variables in `index.css`. But Storybook controls the iframe background **independently** through `globals.backgrounds`, which is set via `parameters.backgrounds`.

## Root Cause

Storybook has 3 separate theme systems:

1. **Component** — controlled by `data-theme` on `<html>`
2. **Iframe background** — controlled by `globals.backgrounds` (Storybook's backgrounds addon)
3. **Manager chrome** (sidebar, toolbar) — controlled by `docs.theme`

A custom `theme` global does **not** sync with `globals.backgrounds` automatically.

## Solution

Use a Decorator that listens to the custom theme and updates `globals.backgrounds` via `useGlobals`. This makes the custom theme the "single source of truth" that drives both the component colors and the iframe background.

### `.storybook/preview.ts`

```tsx
import "@/index.css";
import "@/sotoryBook-safeList.css";
import { useEffect } from 'react';
import type { Preview, Decorator } from '@storybook/react-vite';
import { useGlobals } from 'storybook/internal/preview-api';

// Manager chrome themes (Storybook sidebar/toolbar)
const lightTheme = {
  base: 'light' as const,
  appBg: '#ffffff',
  // ... other theme vars
};

const darkTheme = {
  base: 'dark' as const,
  appBg: '#1a1a1a',
  // ... other theme vars
};

const globalTypes = {
  theme: {
    name: 'Theme',
    description: 'Global theme for v12-ui stories',
    defaultValue: 'system',
    toolbar: {
      icon: 'circlehollow' as const,
      items: [
        { value: 'light', icon: 'sun' as const, title: 'Light' },
        { value: 'dark', icon: 'moon' as const, title: 'Dark' },
        { value: 'system', icon: 'mirror' as const, title: 'System' },
      ],
      dynamicTitle: true,
    },
  },
};

const withTheme: Decorator = (Story, context) => {
  const selected = (context.globals.theme ?? 'system') as 'light' | 'dark' | 'system';
  const [globals, setGlobals] = useGlobals();

  const resolvedTheme = selected === 'system'
    ? (window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light')
    : selected;

  // Sync Storybook's backgrounds global with our theme
  useEffect(() => {
    if (globals.backgrounds !== resolvedTheme) {
      setGlobals({ backgrounds: resolvedTheme });
    }
  }, [resolvedTheme]);

  // Apply data-theme for our component CSS
  useEffect(() => {
    if (typeof window === 'undefined') return;
    document.documentElement.setAttribute('data-theme', resolvedTheme);
    localStorage.setItem('v12-theme', selected);
  }, [resolvedTheme, selected]);

  return <Story {...context} />;
};

const preview: Preview = {
  globalTypes,
  decorators: [withTheme],
  parameters: {
    docs: {
      theme: lightTheme,
    },
    backgrounds: {
      options: {
        light: { name: 'Light', value: '#ffffff' },
        dark: { name: 'Dark', value: '#1a1a1a' },
      },
    },
  },
  initialGlobals: {
    backgrounds: 'light',
  },
};

export default preview;
Key Points
1. useGlobals hook — gives access to set Storybook globals from a decorator
2. setGlobals({ backgrounds: 'dark' }) — this is what actually changes the iframe background
3. parameters.backgrounds.options — must define both light and dark options that match the toolbar values
4. as const on toolbar icons — Storybook 10 requires literal types for icon (e.g., 'sun' as const, not just 'sun')
Why This Works
When the user clicks the theme toolbar:
1. context.globals.theme updates
2. withTheme Decorator re-runs
3. setGlobals({ backgrounds: resolvedTheme }) syncs the backgrounds global
4. Storybook's backgrounds addon sees the change and repaints the iframe
5. data-theme attribute is also set, updating component CSS
Storybook Version
Verified working with Storybook 10.4.6 after running npx storybook@latest upgrade and applying the addon-globals-api migration.
Environment
- Storybook: 10.4.6
- React: 19.x
- Vite builder
