### ISSUE TITLE
[addon-docs] docgen descriptions do not work with component decorators

### ISSUE THREAD

**Issue by DigTheDoug** [storybookjs/storybook#8134]
**Describe the bug**
When using a component with a decorator, the component description and propType descriptions do not show up. Removing the decorator from the component allows them to show up.

**To Reproduce**
1. Have a React Component with a decorator
2. View the story in Storybook
3. Click on the Docs tab
4. See no description for component or proptypes
5. Remove decorator. 
6. See descriptions in storybook docs tab.

**Expected behavior**
The description and propTypes description should display when a component is using a decorator.

**Screenshots**
_With decorator_
![Screen Shot 2019-09-19 at 1 28 41 PM](https://user-images.githubusercontent.com/1428256/65266660-811a6c00-dae1-11e9-9b44-88837fb37347.png)

_Without decorator`_
![Screen Shot 2019-09-19 at 1 28 56 PM](https://user-images.githubusercontent.com/1428256/65266659-811a6c00-dae1-11e9-81ca-e0df0af7bb9a.png)

**Code snippets**
_ExampleComponent.jsx_
```jsx
import React, { Component, Fragment } from 'react';
import PropTypes from 'prop-types';

function exampleDecorator() {
  return DecoratedClass =>
    class extends Component {
      render() {
        return <DecoratedClass {...this.props}/>;
      }
    };
}

@exampleDecorator()
/**
 * The `ExampleComponent` component does a thing.
 */
export class ExampleComponent extends Component {
  
  render() {
    return (
      <Fragment>
        Display this here
      </Fragment>
    );
  }
}

ExampleComponent.propTypes = {
  /**
   * A map of CSS classes to be appended to DOM nodes internally
   */
  testParam: PropTypes.string,
};


ExampleComponent.defaultProps = {
  testParam: 'one'
};

```

_ExampleComponent.stories.jsx_
```jsx
import React from 'react';
import { ExampleComponent } from './ExampleComponent';
import { storiesOf } from '@storybook/react';

storiesOf('ExampleComponent', module)
  .addParameters({
    component: ExampleComponent,
    componentSubtitle: 'The example component'
  })
  .add('Default', () => (
    <ExampleComponent/>
  ));
```

**System:**
```
  System:
    OS: macOS High Sierra 10.13.6
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.12.1 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
  Browsers:
    Chrome: 76.0.3809.132
    Firefox: 68.0.2
    Safari: 12.1.2
  npmPackages:
    @storybook/addon-docs: ^5.2.0 => 5.2.0 
    @storybook/react: ^5.2.0 => 5.2.0 
```

**Additional context**
None

**Comment by salmanm** [comment]
I think this is the fix for it https://github.com/storybookjs/babel-plugin-react-docgen/pull/74

Can someone please take a look? 

 @elevatebart @JeroenReumkens @shilman

**Comment by Zunaib** [comment]
Any update on this, cant seem to have description for props.

**Comment by DigTheDoug** [comment]
I tried the `v5.3.0-beta.31` build which should include the possible fix @salmanm mentioned above (storybookjs/babel-plugin-react-docgen#74), but get the same results, so that unfortunately may not be the fix.

**Comment by DigTheDoug** [comment]
To add some additional information, after updating all @storybook packages to `5.3.0-rc.0` I no longer see _any_ props when using a decorator.

![Screen Shot 2019-12-19 at 1 49 12 PM](https://user-images.githubusercontent.com/1428256/71200798-b9f3e980-2266-11ea-91e5-30fd35d37e0c.png)

It doesn't seem to matter using `storiesOf` or CSF format.

**Comment by lednhatkhanh** [comment]
Same for me, the props table is empty

**Comment by shilman** [comment]
As a workaround you can simply provide the undecorated component as the `component` metadata in your stories.

**Comment by DigTheDoug** [comment]
In one of the recent updates (I'm on `5.3.12` but I haven't checked backwards) this was fixed somewhere. It works as expected for me now, so thanks!
