### ISSUE TITLE
Unable to load stories after upgrade to 5.2

### ISSUE THREAD

**Issue by jacobgranberry** [storybookjs/storybook#8135]
Hey there - unable to successfully load a test story after upgrading to latest SB version.  Wonder if I'm missing something obvious?

.storybook/config.js
![image](https://user-images.githubusercontent.com/7347426/65272961-baed7180-dae5-11e9-81f7-f6a2abe4d320.png)

src/Components/Atoms/Avatar/avatar.stories.js
![image](https://user-images.githubusercontent.com/7347426/65272994-c9d42400-dae5-11e9-8b82-fa2980431cd2.png)

presets.js
`module.exports = ["@storybook/addon-docs/react/preset"];`

**Comment by shilman** [comment]
I don't see any stories defined?

**Comment by jacobgranberry** [comment]
> I don't see any stories defined?

I'm an idiot - I figured the export default would create a default story.  It works now :) Thanks and keep up the good work
