### ISSUE TITLE
Addon-docs: MDX files do not support JSX elements with string props in curly braces

### ISSUE THREAD

**Issue by stmillMSFT** [storybookjs/storybook#8137]
**Describe the bug**
Attempting to use `<Meta title={'Title'} />` in MDX results in errors saying that no title was specified. Similar errors occur for <Story /> tags.

Instead MDX _requires_ use of the optional `<Meta title="Title" />` syntax

**To Reproduce**
Add a MDX story file, try to create tags with the {} syntax in them. Those props are totally ignored

**Expected behavior**
both `""` and `{''}` syntaxes should be supported

I observed this behavior on both 5.2.1 and 5.3.0-alpha-0

**Comment by shilman** [comment]
I believe this problem is specific to the `Meta title` attribute and is a duplicate to https://github.com/storybookjs/storybook/issues/8060
