### ISSUE TITLE
@storybook/addon-docs React.CSSProperties

### ISSUE THREAD

**Issue by Uyarn** [storybookjs/storybook#8139]
Hi, I use storybook v.5.2.0 to implement my React component library with typescript.
Although @storybook/addon-docs can generate the props list in document and most of them are correct, it convert ”React.CSSProperties“ to "any" in the document.
Any idea to resolve this problem?
![image](https://user-images.githubusercontent.com/26377630/65297219-b4b8cd00-db99-11e9-8047-d199ed9f3ce0.png)
![image](https://user-images.githubusercontent.com/26377630/65297241-c306e900-db99-11e9-8de2-420ff6420fb2.png)

**Comment by Uyarn** [comment]
I just realized how to resolve it, I feel @storybook/react  can not convert the prop type like A.B (React.CSSProperties) @shilman 
such as 
```javascript
import React from 'React'

interface IProps {
 style?: React.CSSProperties
}
```

therefore, we can avoid this problem like this

```javascript
import { CSSProperties } from 'React'

interface IProps {
 style?: CSSProperties
}
````

**Comment by shilman** [comment]
@Uyarn so the second one works? that's pretty useful to know!

**Comment by Uyarn** [comment]
@shilman , exactly
