### ISSUE TITLE
Storybook 5.2 static app docs either has missing props section or props descriptions

### ISSUE THREAD

**Issue by glenp01** [storybookjs/storybook#8140]
**Describe the bug**
After updating to Storybook 5.2, the props section is rendering fine when running via storybook  locally but after generating a static app with the storybook build, the props section either does not show up or the descriptions are missing.

**To Reproduce**
1. Create a component with proptypes
2. Add stories for it.
3. When viewing it locally it works fine
4. After running `yarn build-storybook` and viewing the static app, the props section has the above issues

**Expected behavior**
The props section should be the same as it is when running storybook

**Screenshots**
*Locally*
<img width="876" alt="Screenshot 2019-09-20 at 11 35 52 AM" src="https://user-images.githubusercontent.com/50567666/65303273-32310d00-db9b-11e9-8b42-1b85645705e0.png">
<img width="875" alt="Screenshot 2019-09-20 at 11 36 46 AM" src="https://user-images.githubusercontent.com/50567666/65303298-41b05600-db9b-11e9-9418-b76b41b49142.png">

*Static app*
<img width="842" alt="Screenshot 2019-09-20 at 11 36 06 AM" src="https://user-images.githubusercontent.com/50567666/65303313-4ecd4500-db9b-11e9-93a1-fd8508d62f0f.png">
<img width="874" alt="Screenshot 2019-09-20 at 11 36 28 AM" src="https://user-images.githubusercontent.com/50567666/65303320-54c32600-db9b-11e9-9b4a-70ab80a6c5de.png">

**Code snippets**
```
Alert.defaultProps = {
  mode: "static",
  type: "warning",
};

Alert.propTypes = {
  mode: PropTypes.oneOf(["static", "timed"]),
  type: PropTypes.oneOf(["success", "warning", "error", "primary"]),
  message: PropTypes.string.isRequired,
  /**
   * No background or border if static alert
   */
  blank: PropTypes.bool,
  /**
   * Allows icon override, accepts material icon name
   */
  icon: PropTypes.string,
};
```

**System:**
```
Environment Info:

  System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 76.0.3809.132
    Safari: 13.0
  npmPackages:
    @storybook/addon-actions: ^5.2.1 => 5.2.1
    @storybook/addon-docs: ^5.3.0-alpha.0 => 5.3.0-alpha.0
    @storybook/addon-knobs: ^5.2.1 => 5.2.1
    @storybook/addon-links: ^5.2.1 => 5.2.1
    @storybook/addon-notes: ^5.2.1 => 5.2.1
    @storybook/addons: ^5.2.1 => 5.2.1
    @storybook/react: ^5.2.1 => 5.2.1
```

**Additional context**
None

**Comment by shilman** [comment]
Sorry for the slow reply here. Can you post your config/presets files? Also, are you using CRA?

**Comment by glenp01** [comment]
Here you go.
`config.js`
```
import React from "react";
import { addParameters, configure, addDecorator } from "@storybook/react";
import { withKnobs } from "@storybook/addon-knobs";
import StoryRouter from "storybook-react-router";
import { ThemeProvider } from "styled-components";
import { AlertContainer } from "../src/components/Common/Alerts/AlertContainer";
import theme from "../src/utils/theme";
import "../public/reset.css";
import "../src/styles/app.scss";

function loadStories() {
  req.keys().forEach(filename => req(filename));
}

addParameters({
  options: {
    storySort: (a, b) => a[1].id.localeCompare(b[1].id),
  },
});

addDecorator(withKnobs);
addDecorator(StoryRouter());
addDecorator(story => (
  <ThemeProvider theme={theme}>
    <AlertContainer>{story()}</AlertContainer>
  </ThemeProvider>
));

// automatically import all files ending in *.stories.js
configure(
  [
    require.context("../src", true, /\.stories\.mdx$/),
    require.context("../src", true, /\.stories\.js$/),
  ],
  module
);
```


`presets.js`
```
module.exports = ["@storybook/addon-docs/react/preset"];
```

And yes CRA is being used. Thanks!

**Comment by shilman** [comment]
@glenp01 can you try this? https://www.npmjs.com/package/@storybook/preset-create-react-app

cc @mrmckeb

**Comment by jebadirad** [comment]
I am having this same issue, both with CRA and without CRA. 

Without CRA i installed react-scripts and was able to get the `loading create-react-app config` message to appear.  I think that solved another issue I was facing as well so I have kept react-scripts as a dev dependency.  

Would you, @shilman ,  suggest trying that preset-create-react-app as well? Unfortunatley I am using a `babel.config.js` at the root of my project. So i am not sure if thats going to hurt more than help?

**Comment by shilman** [comment]
There are a collection of issues piling up with different versions of what's probably the same underlying problem. I'm going to try to spend some time on it this week.

**Comment by jebadirad** [comment]
Much appreciated!!!

**Comment by robbeman** [comment]
It may be related to how the context is consumed.

I am writing stories in MDX, using the `<Meta />` block to set the context and then I use `<Props of="." />`. This works in dev builds, but on static builds I get similar, partial props tables as described above.

The reason I think it has to do with the context is because in some of my MDX files I reference multiple components with `<Props of={Button} />` (for example) and this one shows the complete props table.

**Comment by aleshh** [comment]
Having the same issue. For me, the props table in the static app does not show props that are required, or props that have an undefined default.

**Comment by shilman** [comment]
Repro here: https://github.com/storybookjs/storybook/commit/964d40dc6917ac1b7e7184daa2ef064f7462165c

**Comment by vgvg** [comment]
I was running into the same issue. Setting `NODE_ENV` to `development` for the `build-storybook` command got this working for me. The default seems to be `NODE_ENV=producction` for this command. My build-storybook script now looks like so:

```javascript
"scripts": {
    "build-storybook": "NODE_ENV=development build-storybook"
}
```

Not sure what else this might do under the hood, but I'm now seeing props in the static build of Storybook just like when running locally.

**Comment by agrauch** [comment]
Setting `NODE_ENV` to `development` fixed our problems as well.

The issue was caused by including the `transform-react-remove-prop-types` plugin in our `babel.config.js` production environment. Without propTypes to read, there's nothing to display.

**Comment by fholzer** [comment]
Having the same issue. For testing I created a completely new react app using CRA5, then installed SB, (including the webpack5 fix/workaround that `sb init` suggests I should use) and the same issue there. No documentation, not for my component, but also not for the example stories that `sb init` adds. Also setting `NODE_ENV=development` didn't help.

Demo repo: https://github.com/fholzer/sb-proptype-doc-issue

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
