### ISSUE TITLE
[Need help]How to set reset.css for all the component stories in the iframe?

### ISSUE THREAD

**Issue by Sara2009** [storybookjs/storybook#8144]
The component will be rendered in the iframe. But I want to set the reset.css to clean the browser default style of the iframe. The reset.css is not included in the component code.  I wonder how to solve this problem?

**Comment by vinceumo** [comment]
Hi you could import your reset css in `.storybook/config.js`

```js
import '!style-loader!css-loader!sass-loader!../src/styles/reset.css';
```

**Comment by sergej-s** [comment]
or you can use a custom head tag `<link rel="stylesheet" type="text/css" href="pathto/reset.css">`
https://storybook.js.org/docs/configurations/add-custom-head-tags/

**Comment by Sara2009** [comment]
> Hi you could import your reset css in `.storybook/config.js`
> 
> ```js
> import '!style-loader!css-loader!sass-loader!../src/styles/reset.css';
> ```

It works! Thanks a lot~

**Comment by Sara2009** [comment]
> or you can use a custom head tag `<link rel="stylesheet" type="text/css" href="pathto/reset.css">`
> https://storybook.js.org/docs/configurations/add-custom-head-tags/

It also works! Thanks very much~

**Comment by appcypher** [comment]
If anyone is wondering where the file is, `config.js` has been renamed to `preview.js` so you can add 
```
import '!style-loader!css-loader!sass-loader!../src/styles/reset.css';
```
to your `preview.js` file.

**Comment by Odinaev444** [comment]
I imported reset css like this : 

`import '../src/styles/reset.css';`
