### ISSUE TITLE
Storysource with mdx?

### ISSUE THREAD

**Issue by bmayen** [storybookjs/storybook#8157]
It's not clear to me if storysource is supposed to be working with Docs mdx stories definitions. The example manual webpack config has the loader running against `test: /\.(stories|story)\.[tj]sx?$/`. If all of my stories are defined in .mdx, is it possible to show source for them? Some additional documentation clarifying this one way or another would be helpful.

**Comment by shilman** [comment]
@bmayen good question. this is a bug--for now we can't do it without either hacking up storysource or rearchitecting how source is displayed. need to figure this out with @libetl @igor-dv and it's a little complicated.

**Comment by bmayen** [comment]
Thanks for the clarification

**Comment by shilman** [comment]
This is working as of 6.0, closing.
