### ISSUE TITLE
upgraded from 5.10.0 to 5.2.1 now get error

### ISSUE THREAD

**Issue by MMT-LD** [storybookjs/storybook#8158]
Hey,

When running my storybook i now get the following:
Uncaught TypeError: Cannot read property 'parameters' of undefined.

My storybook is wrapped in an addDecorator. my config looks like this....

```
import React, { Fragment } from 'react';
import { configure, setAddon, addDecorator } from '@storybook/react';
import { withOptions } from '@storybook/addon-options';
import JSXAddon from 'storybook-addon-jsx';
import { withTheme } from './test';

setAddon(JSXAddon);

addDecorator(withTheme);

const loadStories = () => require(`glob-loader!./stories.pattern`);

withOptions({
  name: 'blah',
  url: '#',
  goFullScreen: false,
  showStoriesPanel: true,
  showAddonPanel: true,
  showSearchBox: false,
  addonPanelInRight: false,
  sortStoriesByKind: false,
});

configure(loadStories, module);
```

and my decorator... Wrapper is a react component...

```
export const withTheme = makeDecorator({
  name: 'withTheme',
  parameterName: 'theme',
  wrapper: (storyFn, context, { parameters }) => {
    return (
              <Wrapper>{storyFn(context)}</Wrapper>
    );
  },
});
```

This is from my console....

```
uncaught TypeError: Cannot read property 'parameters' of undefined
    at make-decorator.js:29
    at make-decorator.js:53
    at decorated (preview.js:63)
    at hooks.js:238
    at client_api.js:129
    at client_api.js:130
    at withSubscriptionTracking (client_api.js:158)
    at hooks.js:238
    at client_api.js:129
    at hooks.js:266
react-dom.development.js:19814 The above error occurred in the <storyFn> component:
    in storyFn
    in ErrorBoundary

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
```

Thanks in advance. Everything works in 5.10.0 with no issues when i revert to that version. So i'm not sure what the issue is here?

**Comment by shilman** [comment]
@Hypnosphi not sure if this is an issue with hooks or an issue with `<StoryFn />`.  what do you think?

**Comment by MMT-LD** [comment]
@shilman @Hypnosphi - so i fixed this by not using the makeDecorator function and instead passing story() to my withTheme like so;

```
export const WithTheme = ({ story }) => {
  return (
      <Wrapper>{story()}</Wrapper>
  );
};
```

and modifying my config to look like this:

```
addDecorator(story => (
  <WithTheme story={story} />
));
```

not sure on whats the best approach here.... But hey, it works. Now on version 5.2.1.

**Comment by shilman** [comment]
It's the code that's calling `makeDecorator` not passing in the correct args. AFAIK `makeDecorator` didn't change

**Comment by Hypnosphi** [comment]
@MMT-LD I tried to add you example to our own [setup](https://github.com/storybookjs/storybook/tree/next/examples/official-storybook) locally and it seems to work OK.

Can you please create a GitHub repo with minimal reproduction of your issue?

**Comment by leifoolsen** [comment]
Having similar issues.

After upgrading from version 5.1 to 5.2, I experience many of the same error messages mentioned here.

![image](https://user-images.githubusercontent.com/10088486/65897463-9a5bcc00-e3af-11e9-857e-d400d04f0ab3.png)

**Comment by bkniffler** [comment]
Try the latest `5.3.0-alpha.40` @leifoolsen, I had same issue with 5.2.x (didn't have issues with 5.1.x) and with the latest alpha, no more issues.
