### ISSUE TITLE
Errors in console after updating application

### ISSUE THREAD

**Issue by Mahesh-Cheemalapati** [storybookjs/storybook#8164]
Updated the version of storybook from 5.1.11 to 5.2.1 for Vue js config, by running yarn upgrade-interactive --latest. It is updating the files and while I am running the application using yarn build and yarn start it is throwing the below errors in the console and storybook is not working.
**Expected behavior**
Expect storybook to upgrade to version 5.2.1 and work normally

**Screenshots**
![error-storybook1](https://user-images.githubusercontent.com/52803946/65433934-f17c0280-ddeb-11e9-84e5-2e5591faa852.png)
![error-storybook2](https://user-images.githubusercontent.com/52803946/65433943-f5a82000-ddeb-11e9-90b9-1f7533ae64ad.png)
![error-storybook3](https://user-images.githubusercontent.com/52803946/65433947-f80a7a00-ddeb-11e9-94e7-1bd749021cda.png)

**Comment by shilman** [comment]
Did you try clearing node_modules & reinstalling?  Can you paste the results of `sb info` here?

**Comment by Mahesh-Cheemalapati** [comment]
I just deleted and reinstalled the node_modules and run the build again but it showed me the same error. 
Also when I run after upgrading it still shows the info as below
![image](https://user-images.githubusercontent.com/52803946/65449190-6e1cda00-de08-11e9-94fe-93997e458e8c.png)

I will shortly upload the steps that I have followed to upgrade so that you will have a better understanding of what I am doing here.

**Comment by ndelangen** [comment]
@Mahesh-Cheemalapati I'm pretty sure, there's something odd going on with the installation, or the node_modules weren't deleted at all.

Do you have lockfiles? yarn or npm?

How do you delete all node_modules?
how do you install?

Can you run `yarn list @storybook/react` and give us the output here?
Can you run `npx sb info` and give us the output here?

**Comment by Mahesh-Cheemalapati** [comment]
Step 1 
![image](https://user-images.githubusercontent.com/52803946/65451751-d1f5d180-de0d-11e9-94c6-de6fa2c97848.png)

Step 2 
![image](https://user-images.githubusercontent.com/52803946/65451828-f3ef5400-de0d-11e9-9f55-cc291fb57807.png)

Step 3 
yarn upgrade-interactive --latest
![image](https://user-images.githubusercontent.com/52803946/65452356-1635a180-de0f-11e9-9a2e-be52d6978901.png)

Output for yarn list @storybook/react and npx sb info 
![image](https://user-images.githubusercontent.com/52803946/65453050-69f4ba80-de10-11e9-9a98-b878db3dd5b9.png)

Yes I do have a yarn.lock file and to uninstall node_modules - I am going into the folder and using shift+delete to delete all the files and after that to install I am running yarn install and yarn build and yarn start commands

**Comment by ndelangen** [comment]
sorry the yarn list commands should be:
```
yarn list --pattern storybook
```

**Comment by ndelangen** [comment]
I'm super confused about why storybook report this seemingly wrong version in your terminal.

**Comment by Mahesh-Cheemalapati** [comment]
Result after running yarn list --pattern storybook
![image](https://user-images.githubusercontent.com/52803946/65455423-349e9b80-de15-11e9-880d-b94ecc544c18.png)

That's definitely weird and it is also updating in the package.json and package.json  storybook core 
![image](https://user-images.githubusercontent.com/52803946/65455547-72032900-de15-11e9-925c-4b4d1c9cc0d6.png)

**Comment by Mahesh-Cheemalapati** [comment]
I also checked the yarn.lock file - after deleting the node_modules and installing them again the yarn.lock is also getting updated with changes

![image](https://user-images.githubusercontent.com/52803946/65458582-e80a8e80-de1b-11e9-9fea-b643d8d382db.png)

**Comment by ndelangen** [comment]
Notice how the storybook-readme & vue-cli-stroybook-plugin has a dependency on 5.1?

It must be that one of those is actually used?

**Comment by Mahesh-Cheemalapati** [comment]
Yes I just noticed that, do you want me to update them manually and check or is there a work-around to that? 

I am unsure as of now if any of those is triggering this issue!

**Comment by ndelangen** [comment]
Have you tried regenerating your lockfile?

I'm unsure why yarn didn't upgrade them tbh.

**Comment by Mahesh-Cheemalapati** [comment]
Yes, I deleted the lock file and regenerated them again before I posted the screenshots there. 

Please let me know if you have any suggestions

**Comment by Mahesh-Cheemalapati** [comment]
So I am using the vue-cli-plugin-storybook in the application and I think that is causing the issue 

![image](https://user-images.githubusercontent.com/52803946/65464431-c0212800-de27-11e9-85c3-a4d77328c140.png)

So if you have any suggestions as to what can be done, please let me know

**Comment by ndelangen** [comment]
@pksunkara any idea what might be the issue here?

**Comment by pksunkara** [comment]
Yeah, vue-cli-plugin uses it's own storybook dependency which is currently 5.1.x. There is an existing issue for users who want to use 5.2.x whose fix should allow any version once we fix it. https://github.com/storybookjs/vue-cli-plugin-storybook/issues/71
