### ISSUE TITLE
URL params don't work with addParameters

### ISSUE THREAD

**Issue by SiAdcock** [storybookjs/storybook#8170]
**Describe the bug**
When using the `?full=1` query parameter, Storybook displays in full screen mode as expected. However, if I use `addParameters()` in config.ts this seems to override the query parameter and Storybook is not displayed in full screen mode. This occurs even if I don't set the `isFullscreen` option

**To Reproduce**
1. Open a story in Storybook
2. Add the URL parameter `full=1`
3. Observe: story is displayed in fullscreen mode
4. In config.ts, add the following:
```js
addParameters({
	options: {
		isToolshown: false,
	},
})
```
5. Open a story in Storybook
6. Add the URL parameter `full=1`
7. Observe: story is **not displayed in fullscreen mode**

**Expected behavior**
I would expect the URL param `full=1` to be respected even if global parameters are added in config.ts. Moreover, I would expect the URL parameters to *override the global parameters*.

**System:**
```
  System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
  Binaries:
    Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
  Browsers:
    Chrome: 77.0.3865.90
    Firefox: 67.0
    Safari: 13.0

```

**Comment by SiAdcock** [comment]
Good shout @Uyarn, something like this would work for me too!

I'll keep this issue open, because I still think it's a bug, but your workaround is very useful, thanks so much 😄

**Comment by Uyarn** [comment]
@SiAdcock , definitely, this is just a compatible workaround . Let's wait for the official fix from storybook 😄

**Comment by ecl1ps** [comment]
Hello, this is still a valid issue for us. The woarkaround means you need to host storybook application twice - once normalny with menu and secondly in fullscreen mode. It is not a good solution. 

Can you look into it? Thanks

**Comment by shilman** [comment]
cc @ndelangen

**Comment by rabelloo** [comment]
I'm currently working around the issue like so, for those interested:

`manager-head.html`
```html
<script>
  var { searchParams } = new URL(location.href);
</script>
```

`searchParams.js`
```js
const { searchParams } = parent;
const get = name => searchParams?.get(name);
const truthy = value => ['1', 'true'].includes(value);
const is = name => truthy(get(name));

export const isFullscreen = is('full') ?? false;
export const showNav = is('nav') ?? true;
export const showPanel = is('panel') ?? true;
export const isToolshown = is('tool') ?? true;
```

`config.js`
```js
import { isFullscreen, isToolshown, showNav, showPanel } from './searchParams';

addParameters({
  options: {
    isFullscreen,
    isToolshown,
    showNav,
    showPanel,
  },
});
```

I'd love native support along with documentation though!

**Comment by Aftab22** [comment]
hey @rabelloo ,
I am trying to get storybook working for my component.
My implementation->
componentDidMount(){
gets userName and userId from the url using window.location.search
//example www.xyz.com/userName=foo&userId=bar
and saves them in state
this.setState({userName, userId,});
}
render(){
return(<div>
userName is {this.state.userName} userId is {this.state.userId}
</div>)}

how do i pass this using storybook.
I know how to pass props via storybook.
but since this is coming from the url i cant use props.
