### ISSUE TITLE
Build fails after adding addon-docs/react/preset to presets.js [Typescript]

### ISSUE THREAD

**Issue by tx-steven** [storybookjs/storybook#8171]
When trying to start storybook after installing @storybook/addon-docs and adding `module.exports = ['@storybook/addon-docs/react/preset'];` to my presets.js file. I get a typescript error: 

Variable '__MODULE_DEPENDENCIES__' implicitly has an 'any[]' type.

This happens once for every story that I have. Been messing with my config for a while and can't seem to get it to work. Tried adding `react-docgen-typescript-loader` as well.

**Comment by shilman** [comment]
Closing as duplicate to #7829
