### ISSUE TITLE
Use node 10 in CI

### ISSUE THREAD

**Issue by kroeder** [storybookjs/storybook#8173]
We need `node >= 10` for `Angular 8 >=` and EOL of node 8 is by the end of this year. 
It blocks us from using the latest Angular version in our CI tests.

For detailed EOL information see https://github.com/nodejs/Release

**Comment by shilman** [comment]
Gadzooks!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-alpha.4 containing PR #8207 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.
