### ISSUE TITLE
[Addon-storyshots] Hooks in story break tests

### ISSUE THREAD

**Issue by shmidt-i** [storybookjs/storybook#8177]
**Describe the bug**
Recently the feature of using hooks directly inside the stories landed. Unfortunately, it is still an error when using addon-storyshots. Wrapping in component helps

**To Reproduce**
```js
storyOf('Test', module).add('error', () => {
  React.useEffect(() => {}, []);
  return null;
})
```
**Expected behavior**
Storyshot with null in it

**Screenshots**
```
Invariant Violation: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one 
of the following reasons:
    1. You might have mismatching versions of React and the renderer (such as React DOM)
    2. You might be breaking the Rules of Hooks
    3. You might have more than one copy of React in the same app
    See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.

      165 |   })
      166 |   .add('error', () => {
    > 167 |     React.useEffect(() => {}, []);
          |           ^
      168 |     return null;
      169 |   })
```

**System:**

Environment Info:

  System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
  Binaries:
    Node: 10.13.0
    Yarn: 1.17.3
    npm: 6.5.0 
  Browsers:
    Chrome: 77.0.3865.90
    Firefox: 68.0.1
    Safari: 13.0
  npmPackages:
    @storybook/addon-a11y: 5.2.1 => 5.2.1 
    @storybook/addon-actions: 5.2.1 => 5.2.1 
    @storybook/addon-knobs: 5.2.1 => 5.2.1 
    @storybook/addon-links: 5.2.1 => 5.2.1 
    @storybook/addon-storyshots: 5.2.1 => 5.2.1 
    @storybook/addon-storysource: 5.2.1 => 5.2.1 
    @storybook/addons: 5.2.1 => 5.2.1 
    @storybook/react: 5.2.1 => 5.2.1 

**Additional context**

**Comment by shmidt-i** [comment]
CSF maybe will solve the problem, although it's unlikely we are going this way with our codebase.

But, the original question is - according to the https://github.com/storybookjs/storybook/pull/7571 the hooks should work directly in the story. And they do. Until you try to run `addon-storyshots`, which is broken :)

**Comment by shmidt-i** [comment]
We are using storybook more like a toolset for TDD, that's why all our stories resemble tests descriptions
```
describe('counter interactivity', () => {
  it('should increment when enabled[special case] (EXPERIMENAL)', () => {
   
```
We don't want (at least for now) to do 
```
export default {title: 'counter interactivity'}
export const shouldIncrementWhenEnabled_specialCase__EXPERIMENTAL = ...
```

**Comment by shmidt-i** [comment]
And I totally get the benefit of switching towards CSF in a long run, and believe me we've waited a lot for docs and MDX to happen, but that switch cannot be done in one moment and we want to use hooks as first-class citizens already :)

Also, great job on recent changes!!!

**Comment by shilman** [comment]
cool, we should support storiesOf for awhile so it shouldn't be a problem for you to stick with that. just wanted to know if there was something wrong with CSF specifically that was preventing you from upgrading, and it sounds like there's not.

hopefully we can fix this storyshots problem soon and get you unblocked with hooks!

**Comment by tmikeschu** [comment]
Confirming this issue:

```
    "@storybook/addon-actions": "^5.2.1",
    "@storybook/addon-links": "^5.2.1",
    "@storybook/addon-storyshots": "^5.2.1",
    "@storybook/addons": "^5.2.1",
    "@storybook/react": "^5.2.1",
    "babel-plugin-require-context-hook": "^1.0.0",
    "jest": "^24.9.0",
    "react": "^16.9.0",
    node: 10.15.3
```

Using this as a workaround:

```js
const StoryWithHook = () => {
  const [value, setValue] = useState(0);
  return <div onClick={() => setValue(value + 1)}>{value}</div>;
};

export const storyWithHook = () => <StoryWithHook />;
```

**Comment by qooban** [comment]
Workaround suggested by @tmikeschu works fine, but that way you lose the ability to show the code on the story page:
![image](https://user-images.githubusercontent.com/5202105/67080601-db1c5900-f195-11e9-89cc-1f9e7b99272d.png)

**Comment by B3Kay** [comment]
I also got this problem. I want to render a story with hooks and also be able to show the code example. Not just using the workaround like @tmikeschu

**Comment by qooban** [comment]
@B3Kay I just checked the most recent `v5.3.0-alpha.34` and it looks like it works fine in that version.

**Comment by shilman** [comment]
@B3Kay if you can verify this works in the alpha, I'd love to close this issue 😄

**Comment by qooban** [comment]
@shilman @B3Kay Sorry, my bad, I just checked if the docs are presented properly, but not checked if the storyshots are working fine. Unfortunatelly - this issue is still valid.

**Comment by sdrissi** [comment]
Hey there! Same issue for me with React hooks in CSF stories...Any idea when a fix will be available (I would gladly contribute to fix the issue but I'm not familiar with your codebase).

**Comment by brandon-leapyear** [comment]
Hi, coming across this issue using CSF. Am currently using this workaround:

```diff
+// https://github.com/storybookjs/storybook/issues/8177
+const storyshotsHack = (StoryFn: React.FC) => () => <StoryFn />
 
-export const basic = () => {
+export const basic = storyshotsHack(() => {
   const [isToggled, setIsToggled] = useState(false)
   return (
     <>
       <Text>Normal Toggle</Text>
       <Toggle value={isToggled} onClick={() => setIsToggled(!isToggled)} />
     </>
   )
-}
+})
```

**Comment by sdrissi** [comment]
Thanks @brandon-leapyear for your solution. I've tried it and it's a better alternative than the one provided by @tmikeschu since it keeps the source code. @B3Kay this should do the trick ;)

**Comment by chrisfosterelli** [comment]
You can also wrap the story in `React.createElement` as the PR mentioned above does. It seems for some reason the PR applied to the stories in storybook but not for storyshots.

**Comment by shilman** [comment]
We could probably apply that here:

https://github.com/storybookjs/storybook/blob/next/addons/storyshots/storyshots-core/src/frameworks/react/renderTree.ts#L5

https://github.com/storybookjs/storybook/blob/next/addons/storyshots/storyshots-core/src/frameworks/react/renderShallowTree.ts#L5

Anybody want to give that a try?

**Comment by tmikeschu** [comment]
@shilman I can take a look tomorrow! I haven't contributed yet and I'd like to 😄

**Comment by tmikeschu** [comment]
https://github.com/storybookjs/storybook/pull/9187

**Comment by tmikeschu** [comment]
It's interesting that @brandon-leapyear 's solution is like a lazy identity function. Just food for thought!

**Comment by Bjodol** [comment]
Hey! Came over this issue and found a solution that simplify the hack. 
Add to your .storybook/preview.js:

```tsx
// .storybook/preview.js
import { addDecorator } from '@storybook/react';
import React from 'react';

addDecorator(StoryFn => {
    return (
            <StoryFn />
    );
});
```

**Comment by phpSing** [comment]
> Confirming this issue:
> 
> ```
>     "@storybook/addon-actions": "^5.2.1",
>     "@storybook/addon-links": "^5.2.1",
>     "@storybook/addon-storyshots": "^5.2.1",
>     "@storybook/addons": "^5.2.1",
>     "@storybook/react": "^5.2.1",
>     "babel-plugin-require-context-hook": "^1.0.0",
>     "jest": "^24.9.0",
>     "react": "^16.9.0",
>     node: 10.15.3
> ```
> 
> Using this as a workaround:
> 
> ```js
> const StoryWithHook = () => {
>   const [value, setValue] = useState(0);
>   return <div onClick={() => setValue(value + 1)}>{value}</div>;
> };
> 
> export const storyWithHook = () => <StoryWithHook />;
> ```

It works for me, I am using jest and storyshots, initially it throws the Invalid hook call error, I checked the React duplicate issue and all other suggestions, but no luck.

until I find this solution!

**Comment by qdozaq** [comment]
@Bjodol 's solution is perfect and can actually be simplified even more!

```js
// .storybook/preview.js
import { addDecorator } from '@storybook/react';
import {createElement} from 'react';

addDecorator(createElement);
```

**Comment by vdh** [comment]
These workarounds still break the snapshots though? AFAIK any shallow rendering is wrecked by this hack.

**Comment by varundey** [comment]
Facing same issue with `react`, `react-dom` and `react-test-renderer` v16.13.1

**Comment by brandon-leapyear** [comment]
FYI storybook works with hooks now: https://github.com/storybookjs/storybook/pull/7571

it would be great to get the same support with storyshots

**Comment by shilman** [comment]
Released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-alpha.43 which contains #10529 and may address this

**Comment by michaelbayday** [comment]
I'm still getting this issue. Does anyone have any suggestions?

storyshots.test.js
```js
import initStoryshots, { Stories2SnapsConverter } from '@storybook/addon-storyshots';
import renderer from 'react-test-renderer';
import { styleSheetSerializer } from 'jest-styled-components/serializer';
import { addSerializer } from 'jest-specific-snapshot';

addSerializer(styleSheetSerializer);

initStoryshots({
  test: ({ story, context }) => {
    const converter = new Stories2SnapsConverter();
    const snapshotFilename = converter.getSnapshotFileName(context);
    const storyElement = story.render(context);
    const tree = renderer.create(storyElement).toJSON();
    expect(tree).toMatchSpecificSnapshot(snapshotFilename);
  },
});
```

jest.config.js
```js
module.exports = {
  preset: 'ts-jest/presets/js-with-ts',
  roots: ['src'],
  setupFilesAfterEnv: ['./jest.setup.js'],
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json'],
  transformIgnorePatterns: ['node_modules/(?!@storybook/*)'],
  testMatch: ['**/*.test.(js)'],
  moduleNameMapper: {
    // Mocks out all these file formats when tests are run.
    '\\.(jpg|ico|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$':
      '<rootDir>/__mocks__/fileMock.js',
  },
  globals: {
    'ts-jest': {
      tsConfig: 'tsconfig.test.json',
    },
  },
  collectCoverageFrom: ['src/**/*.tsx'],
};
```

jest.setup.js
```js
import '@testing-library/jest-dom';
```

The serialization of the styled components is working, but just running into this last hiccup.
