### ISSUE TITLE
mockdate breaks knobs

### ISSUE THREAD

**Issue by susannakosic** [storybookjs/storybook#8180]
**Given this story**
import React from 'react';
import {storiesOf} from '@storybook/react';
import MockDate from "mockdate";
const NOW = "2019-07-22T16:29:28Z";
MockDate.set(NOW);
storiesOf('Components / CountDown / Snapshots', module)
.add('date is set', function(){ return (<div>hello</div>)});

**With these dependencies installed**
"@storybook/addon-actions": "5.1.10",
"@storybook/addon-console": "1.2.1",
"@storybook/addon-info": "5.1.10",
"@storybook/addon-knobs": "5.1.10",
"@storybook/addon-links": "5.1.10",
"@storybook/addon-storyshots": "5.1.10",
"@storybook/addon-storysource": "5.1.10",
"@storybook/addon-viewport": "5.1.10",
"@storybook/addons": "5.1.10",
"@storybook/react": "5.1.10",
"mockdate": "2.0.3"

**Stories with Knobs stop working**
When I comment out mockdate bits then knobs (on different stories) are working as expected.
I don't see any relevant error in the browser console.

**Is there any online example on how to mock a date for a particular story?**
I tried different approaches to workaround this.
1. Using a wrapper component to mock/reset mock on componentWillMount and componentDidUnmount events.
2. Rewriting a story so that it is ran as spec using storybook-addon-specifications, with enzime/beforeEach/afterEach to mock/reset mock.
3. Used mockdate to mock global date as part of setupFiles.
I didn't manage to mock dates without breaking other stories with are using knobs.

**Comment by darondel** [comment]
Hey there!
We found a related issue by using [timemachine](https://github.com/schickling/timemachine) and fixing the global `Date`. When the user update an input in the knobs panel, the iframe is not refreshed.
