### ISSUE TITLE
client.js is missing from @storybook/core@5.3.0-alpha.1

### ISSUE THREAD

**Issue by Pittan** [storybookjs/storybook#8181]
**Describe the bug**
Using `@storybook/angular@next` with `@storybook/addon-docs@next` will fail.
Error message says `Module not found: Error: Can't resolve '@storybook/core/client' in '/Users/pittan/Dev/live-web/node_modules/@storybook/angular/dist/client/preview'`

I checked `node_modules/@storybook/core` , but `client.js` is missing.

**To Reproduce**

**Expected behavior**
`@storybook/core/client.js` exists.

**System:**
Environment Info:

  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
  Binaries:
    Node: 10.14.2 - ~/.nvm/versions/node/v10.14.2/bin/node
    Yarn: 1.17.3 - ~/.nvm/versions/node/v10.14.2/bin/yarn
    npm: 6.7.0 - ~/.nvm/versions/node/v10.14.2/bin/npm
  Browsers:
    Chrome: 76.0.3809.132
    Firefox: 67.0.3
    Safari: 13.0
  npmPackages:
    @storybook/addon-actions: 5.3.0-alpha.1 => 5.3.0-alpha.1 
    @storybook/addon-docs: 5.3.0-alpha.1 => 5.3.0-alpha.1 
    @storybook/addon-links: 5.3.0-alpha.1 => 5.3.0-alpha.1 
    @storybook/addon-notes: 5.3.0-alpha.1 => 5.3.0-alpha.1 
    @storybook/addons: 5.3.0-alpha.1 => 5.3.0-alpha.1 
    @storybook/angular: 5.3.0-alpha.1 => 5.3.0-alpha.1

**Comment by shilman** [comment]
Jeepers creepers!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-alpha.2 containing PR #8182 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
w00t!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.3 containing PR #8182 that references this issue. Upgrade today to try it out!
