### ISSUE TITLE
Theme doesn't apply immediately

### ISSUE THREAD

**Issue by mikolaj6r** [storybookjs/storybook#8188]
**Describe the bug**
I have defined theme in config.js
```
addParameters({
    options: {
        theme: myTheme
    },
});
```
However, when storybook is started it launches with default theme and after few clicks in menu, e.g. going to another story is switches to my theme.

**To Reproduce**
1. Define your own theme in config.js
2. Start storybook

**Expected behavior**
Storybook should lanuch with theme defined in config

**Additional context**
"@storybook/core": "^5.2.0",

**Comment by ndelangen** [comment]
Yeah this is unfortunately a side effect of the way storybook themes are configured + the optimization to prevent flashes of default theme when refreshing.

I'm working on a (it's taking long) overhaul of configuration that solves this problem once and for all: #6806
