### ISSUE TITLE
[addon-docs] doesn't get defaultProps from React function component

### ISSUE THREAD

**Issue by linkntt** [storybookjs/storybook#8191]
First time opening an issue. I checked the list of open issue and doesn't seem like this is a duplicate but apology in advance in case it is.

**Describe the bug**
Default props column on DocsPage doesn't have any default value when component is a function component even though when implemented as class component it worked.

**Screenshots**
With class component:
````
export interface ICheckboxProps {
    checked?: boolean;
    defaultChecked?: boolean;
    disabled?: boolean;
    onChange?: (e: CheckboxChangeEvent) => void;
    children?: any;
}

export class Checkbox extends React.Component<ICheckboxProps> {
    defaultProps = {
        defaultChecked: false
    };

    render() {
        return <CoreCheckbox {...this.props} />;
    }
}
````
![image](https://user-images.githubusercontent.com/55785820/65590205-12cb2300-df93-11e9-863b-a1a01bc9bd1f.png)

With function component:
````
export const Checkbox = (props: ICheckboxProps) => <CoreCheckbox {...props} />;

Checkbox.defaultProps = {
    defaultChecked: false
};
````
![image](https://user-images.githubusercontent.com/55785820/65589992-aea85f00-df92-11e9-9c8e-5f208ac751f8.png)

**System:**
    OS: macOS Mojave 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  Binaries:
    Node: 12.9.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.10.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 77.0.3865.90
    Firefox: 68.0.1
    Safari: 12.1.1

**Comment by linkntt** [comment]
Hi,

I realized this was because I added a property to the component after the export. So if the code is like this:
````
export const Checkbox = (props: ICheckboxProps) => <CoreCheckbox {...props} />;

Checkbox.Group = (props: ICheckboxGroupProps) => {

    const { vertical, ...rest } = props;
    return vertical ? (
        <StyledCheckboxGroup {...rest}>{rest.children}</StyledCheckboxGroup>
    ) : (
        <CoreCheckbox.Group {...rest}>{rest.children}</CoreCheckbox.Group>
    );
};

Checkbox.defaultProps = {
    defaultChecked: false
};
````
the defaultProps doesn't appear:
![image](https://user-images.githubusercontent.com/55785820/65613467-c5fd4180-dfbe-11e9-99e0-9ddb3f11b21c.png)

But if I move the defaultProps block up right after the export line like this:
````
export const Checkbox = (props: ICheckboxProps) => <CoreCheckbox {...props} />;

Checkbox.defaultProps = {
    defaultChecked: false
};

Checkbox.Group = (props: ICheckboxGroupProps) => {

    const { vertical, ...rest } = props;
    return vertical ? (
        <StyledCheckboxGroup {...rest}>{rest.children}</StyledCheckboxGroup>
    ) : (
        <CoreCheckbox.Group {...rest}>{rest.children}</CoreCheckbox.Group>
    );
};
````
then it works.
![image](https://user-images.githubusercontent.com/55785820/65613549-e6c59700-dfbe-11e9-8d68-56bb5ab53fc0.png)

**Comment by mourad1081** [comment]
Hey, @linkntt how did you do to insert a description of your property `defaultChecked` please?

**Comment by linkntt** [comment]
> Hey, @linkntt how did you do to insert a description of your property `defaultChecked` please?

@mourad1081 Should work with this :D

````
export interface ICheckboxProps {
    ...
    /**
     * If the checkbox is checked by default
     */
    defaultChecked?: boolean;
    ...
}
````

**Comment by velopert** [comment]
I am facing a similar issue here.

It works perfectly when I use arrow function syntax.

```tsx
import React from 'react';

export interface DialogProps {
  /** this is a title */
  title: string;
  /** this is a body */
  body: string;
}

const Dialog = ({ title, body }: DialogProps) => {
  return (
    <div>
      <h1>{title}</h1>
      <p>{body}</p>
    </div>
  );
};

Dialog.defaultProps = {
  title: 'Hello World'
};

export default Dialog;
```

![image](https://user-images.githubusercontent.com/17202261/66700051-67a6c180-ed27-11e9-8c7a-58a52e69b4e2.png)

However, if I use function keyword, it does not extract defaultProps. 
```tsx
import React from 'react';

export interface DialogProps {
  /** this is a title */
  title: string;
  /** this is a body */
  body: string;
}

function Dialog({ title, body }: DialogProps) {
  return (
    <div>
      <h1>{title}</h1>
      <p>{body}</p>
    </div>
  );
}

Dialog.defaultProps = {
  title: 'Hello World'
};

export default Dialog;

```

![image](https://user-images.githubusercontent.com/17202261/66700075-9f156e00-ed27-11e9-97a1-8c5bace7b61c.png)

**Comment by velopert** [comment]
I think this is a bug of react-docgen-typescript-loader because same thing happens when I use @storybook/addon-info

**Comment by gmukul01** [comment]
@linkntt in my case default props are still not coming

My Component is like this
`
export const Label: SFC<Props> & WithStyle = React.memo(props => <LabelStyled {...props}>{props.children}</LabelStyled>);

Label.defaultProps = {
    showPointer: false,
    labelPosition: 'left',
    required: false
};
Label.displayName = 'Label';
Label.Style = LabelStyled;
`

**Comment by SenhorLion** [comment]
Using an interface, adding `@default blah` works for me:

```js
interface ButtonProps {
  /**
   * Type of Button
   *
   * @default button
   */
  type?: 'button' | 'submit';
}
```

**Comment by shilman** [comment]
Ermahgerd!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-beta.10 containing PR #8950 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
