### ISSUE TITLE
Knobs Textarea Max Height Feature

### ISSUE THREAD

**Issue by ahmetcaglayan** [storybookjs/storybook#8192]
Hello,
I am using version 5.2.1.
But this textarea has too much height.
Is it possible to restrict?
Is it possible to provide a sample setting code?
I couldn't find anything as a result of my research :(
<img width="415" alt="Ekran Resmi 2019-09-25 14 13 32" src="https://user-images.githubusercontent.com/13018803/65596230-211f3c00-df9f-11e9-8d7e-8a336e3d061f.png">

**Comment by shilman** [comment]
How about we just hardcode it to something reasonable rather than adding an extra option?

**Comment by ahmetcaglayan** [comment]
> How about we just hardcode it to something reasonable rather than adding an extra option?

Of course, you can suggest a solution for now.

**Comment by ahmetcaglayan** [comment]
Is there a technological?

**Comment by shilman** [comment]
Sorry for the late reply. How about 10 lines? Would you mind putting together a PR for this?

**Comment by ahmetcaglayan** [comment]
if it is simple I would like to apply

**Comment by ahmetcaglayan** [comment]
?

**Comment by shilman** [comment]
PR's welcome!
