### ISSUE TITLE
Angular Docs Addon Storysource Not Loading

### ISSUE THREAD

**Issue by chriscarpenter12** [storybookjs/storybook#8198]
With a mix of `storiesOf`, `CSF` and `MDX` stories some of the stories source fail to load. This can be see today by running the Angular-CLI example and loading the story `Component with self and dependencies declared in its feature module`.

![Screenshot from 2019-09-25 12-38-19](https://user-images.githubusercontent.com/458486/65622845-86216480-df94-11e9-9dd4-3ee1068649cf.png)

To fix this intermittent loading apply the `typescript` parser to the docs preset.
```
module.exports = [
  {
    name: '@storybook/addon-docs/angular/preset',
    options: {
      sourceLoaderOptions: {
        parser: 'typescript',
      },
    },
  },
];
```
This fixes the source loading issue for Angular now:

![Screenshot from 2019-09-25 12-39-09](https://user-images.githubusercontent.com/458486/65622942-bbc64d80-df94-11e9-992b-9efcdb6ec90a.png)

But breaks loading a [docs only MDX file in CSF](https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/recipes.md#csf-stories-with-mdx-docs).

[Sample Repo](https://github.com/chriscarpenter12/storybook/tree/next/examples/angular-cli)

**Expected behavior**
All story sources should load using the docs preset.

**System:**
```
Environment Info:

  System:
    OS: Linux 5.0 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Binaries:
    Node: 10.15.3 - ~/.nodenv/versions/10.15.3/bin/node
    Yarn: 1.17.3 - /usr/bin/yarn
    npm: 6.11.3 - ~/.nodenv/versions/10.15.3/bin/npm
  Browsers:
    Chrome: 77.0.3865.90
    Firefox: 69.0
  npmGlobalPackages:
    @storybook/cli: 5.2.1
```

**Additional context**
When importing the docs only `.mdx` file it's necessary to have type definition. Using the definition provided by [MDX](https://mdxjs.com/advanced/typescript). This is what I used, but may be wrong because when running storybook like this it complains about duplicate export 'default'

I created a new story at `stories/csf-mdx-error.stories.ts` with a matching `csf-mdx-error.mdx` as an example as I didn't see this existing example in the story list.

```
Module parse failed: Duplicate export 'default' (41:7)
File was processed with these loaders:
 * ./node_modules/ts-loader/index.js
 * ./node_modules/angular2-template-loader/index.js
 * ./node_modules/@storybook/source-loader/dist/server/index.js
You may need an additional loader to handle the result of these loaders.
| }); }, { __STORY__: __STORY__, __ADDS_MAP__: __ADDS_MAP__, __MAIN_FILE_LOCATION__: __MAIN_FILE_LOCATION__, __MODULE_DEPENDENCIES__: __MODULE_DEPENDENCIES__, __LOCAL_DEPENDENCIES__: __LOCAL_DEPENDENCIES__, __SOURCE_PREFIX__: __SOURCE_PREFIX__, __IDS_TO_FRAMEWORKS__: __IDS_TO_FRAMEWORKS__ });
| var addSourceDecorator = require("@storybook/source-loader/preview").addSource;
> export default {
|     title: 'Core|CSF MDX Error',
|     decorators: [
```

**Comment by shilman** [comment]
@chriscarpenter12 I think this is expected behavior (tho not desirable behavior). Right now storysource does not support MDX at all. How exactly does it break? Does it unbreak when you navigate to another story?

**Comment by chriscarpenter12** [comment]
@shilman It fails to load any story with `parser: 'typescript'` and loading a single CSF with MDX story. Displays an error in the preview pane for any story selected.

**Comment by chriscarpenter12** [comment]
If that is the desired behavior you then you can't see the source of a `CSF` story then? And as it stands right now you can't see the source of existing stories in the current state. Eg: Load the story for `Component with self and dependencies declared in its feature module` to see what I'm talking about

**Comment by shilman** [comment]
@chriscarpenter12 Definitely NOT the desired behavior. I wouldn't expect MDX to work, but I didn't know that it also breaks the rest, which sucks. I'll see what we can do to fix it. Thanks!

**Comment by chriscarpenter12** [comment]
No problem at all. Hard to articulate the problem :)

**Comment by DmitryEfimenko** [comment]
Using [the official example](https://github.com/storybookjs/storybook/tree/next/examples/angular-cli) provided by Storybook team, I can't get it to work even with the workaround suggested by @chriscarpenter12.

Any help is highly appreciated!

**Comment by shilman** [comment]
Son of a gun!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-alpha.37 containing PR #8499 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
