### ISSUE TITLE
`babel-preset-react-app` listed as a dependency

### ISSUE THREAD

**Issue by daveisfera** [storybookjs/storybook#8201]
**Describe the bug**
The [`babel-preset-react-app` package states](https://www.npmjs.com/package/babel-preset-react-app) that `You don’t need to install it separately in Create React App projects.` but it's listed as a dependency

**To Reproduce**
Look at [`package.json` for `@storybook/react`](https://github.com/storybookjs/storybook/blob/cd6ba7734fed91016edda07794d0feab5b9e62ec/app/react/package.json#L39)

**Expected behavior**
It's not listed as a dependency because it's [requiring specific versions that end up causing multiple versions of packages to be installed](https://github.com/facebook/create-react-app/issues/7655)

**System:**
```
Environment Info:

  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 77.0.3865.90
    Firefox: 69.0
    Safari: 12.1.2
```

**Comment by shilman** [comment]
@mrmckeb is this something you know about?

**Comment by mrmckeb** [comment]
I think we need to remove this as a part of the migration to the preset. I've added it to the new task.

**Comment by daveisfera** [comment]
So what does that mean as far as timeline goes? Can we expect this to be fixed in the 5.3 release?

**Comment by mrmckeb** [comment]
@daveisfera, I hope so - but it might take a little longer as this may be a breaking change for `@storybook/react`.

**Comment by daveisfera** [comment]
Great! Thanks for the update and hopefully it's doable. 🤞

**Comment by mrmckeb** [comment]
@shilman and I will need to discuss... basically, removing this from the package is fine - but then it would need to be installed by users alongside their package (when not using `react-scripts`).

Perhaps we'll need to move to peer deps and have a script that verifies existence.

**Comment by JabbyPanda** [comment]
Related commit that removed `babel-preset-react-app` runtime dependency from `@storybook/react` package

https://github.com/storybookjs/storybook/commit/942238acc8f2a87e83898d93c789818d391a2f06#diff-b5412b044e81f54a9cadb0982c0aa7c6
