### ISSUE TITLE
New React-Router library hooks do not work

### ISSUE THREAD

**Issue by javierguzman** [storybookjs/storybook#8204]
Hello for the first time around here!

I am a new user of Storybook and this week the new react-router library was released and I have modified some code in order to use one of the new hooks (useLocation). It builds ok but this provokes the following error when showing that component on the storybook created web:

"useContext(...) is undefined" followed by a big function call stack

I now this is pretty new, so it is normal, but just leaving this here to make you aware. 

On the other hand, it could be possible that maybe I need some addon??

Thank you in advance and regards,
Javier

**Comment by sofiageo** [comment]
@javierguzman I accidentally got subscribed to this issue and I noticed the text from the bot. I just tested and both useLocation and useHistory hooks work fine for me.

**Comment by javierguzman** [comment]
@sofiageo actually you are right, I forgot to update this issue, sorry! I think it was something else in my code but it works now. I close this.
