### ISSUE TITLE
Multiple versions of regenerator-runtime are required by storybook

### ISSUE THREAD

**Issue by stof** [storybookjs/storybook#8208]
**Describe the bug**
`@storybook/ui` requires the latest 0.13 version of `regenerator-runtime`, while `@storybook/html`, `@storybook/core` and ``@storybook/node-logger` require the older 0.12 version.
This increases the size of the bundle for nothing, as it duplicates `regenerator-runtime` in it.

The same version should be used for all dependencies (and best would be to settle on 0.13 rather than 0.12).

On a side note, `react-syntax-highlighter` (required by `@storybook/components`) depends on the old `babel-runtime` package (instead of the newer `@babel/runtime` package) and so depends on version 0.11 of `regenerator-runtime`, bundling a third version.

**Comment by stof** [comment]
Regarding `react-syntax-highlighter`, this is because an old version is used. Latest version (11, while storybook uses version 8) uses the new babel runtime package. So this is also an issue to solve on the storybook side.

**Comment by shilman** [comment]
Good catch @stof! @ndelangen mind taking point on this?

**Comment by ndelangen** [comment]
@stof would you like to work on this together maybe in a pair programming session?

**Comment by stof** [comment]
I opened a PR for the upgrade of regenrator-runtime, getting rid of 0.12.

Regarding the upgrade of react-syntax-highlighter, I'm stuck for now. Types are wrong in DefinitelyTyped. The fix has been submitted in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/38776 and is pending a merge.

**Comment by shilman** [comment]
Hurrah!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-alpha.9 containing PR #8258 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by stof** [comment]
The merged PR fixes only half of it. We still have `regenerator-runtime` 0.11 bundled due to the old version of `react-syntax-highlighter`, so I'm reopening this issue until the second related PR is also merged.

**Comment by ndelangen** [comment]
It's merged!

**Comment by ndelangen** [comment]
@stof thank you so much for your efforts!
