### ISSUE TITLE
Dark theme renders unreadable text on the about page

### ISSUE THREAD

**Issue by stof** [storybookjs/storybook#8211]
**Describe the bug**
Text for `<code>` is rendered as white text on a white background.

**To Reproduce**
1. Configure storybook with a dark theme
2. Click on 'About storybook' in the top-left dropdown

**Expected behavior**
Text should be readable

**Screenshots**
![image](https://user-images.githubusercontent.com/439401/65692104-4df05380-e072-11e9-9630-5855fce17106.png)

**System:**

```
Environment Info:

  System:
    OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
  Binaries:
    Node: 10.16.3 - /usr/bin/node
    Yarn: 1.17.3 - /usr/bin/yarn
    npm: 6.11.3 - ~/.local/bin/npm
  Browsers:
    Firefox: 69.0.1
  npmPackages:
    @storybook/addon-centered: ^5.0.3 => 5.2.1 
    @storybook/addon-knobs: ^5.0.3 => 5.2.1 
    @storybook/addon-notes: ^5.0.3 => 5.2.1 
    @storybook/addon-viewport: ^5.0.3 => 5.2.1 
    @storybook/html: ^5.0.3 => 5.2.1 
    @storybook/theming: ^5.0.3 => 5.2.1
```

**Comment by shilman** [comment]
Good catch! Closing as dupe to #8094

**Comment by shilman** [comment]
Yay!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-alpha.7 containing PR #8260 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

**Comment by shilman** [comment]
Huzzah!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.2 containing PR #8260 that references this issue. Upgrade today to try it out!
