### ISSUE TITLE
Error when using latest create-react-app

### ISSUE THREAD

**Issue by balazsorban44** [storybookjs/storybook#8223]
**Describe the bug**
I recently updated `@storybook/react` and `react-scripts`, and now I cannot start storybook.
With `@storybook/react@5.2.1` and `react-scripts@3.1.x`, I get the error presented on the screenshot. Changing back to `react-scripts@3.0.1` though works fine. 

**To Reproduce**
1. Install `@storybook/react@5.2.1` and `react-scripts@3.1.x`,
2. Create a story
3. Start storybook

**Expected behavior**
Should not crash.

**Screenshots**
![image](https://user-images.githubusercontent.com/18369201/65829969-58e1f880-e2ab-11e9-81b0-3a0fbce087ef.png)

**System:**
```
  System:
    OS: Linux 5.0 Ubuntu 19.04 (Disco Dingo)
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
  Binaries:
    Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
    Yarn: 1.17.3 - ~/.yarn/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
  Browsers:
    Chrome: 77.0.3865.90
    Firefox: 69.0.1
  npmPackages:
    @storybook/react: ^5.2.1 => 5.2.1 

```

**Additional context**
I am uncertain if this is an issue with storybook or CRA.

**Comment by 0tho** [comment]
Having the same issue

**Comment by mrmckeb** [comment]
Hi @0tho, have you tried (while on the newer `react-scripts`) removing your `node_modules` and lockfile, and reinstalling?

**Comment by calumgunn** [comment]
Hi @mrmckeb - I'm having the same issue, and a reinstall didn't fix things.

My error is different, however:
```
Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at vendors~main.cff839a2a50bbfd2c813.bundle.js:8101
    at memoizerific (vendors~main.cff839a2a50bbfd2c813.bundle.js:67932)
    ...
```

**Comment by mrmckeb** [comment]
Are you able to share that repo with me @calumgunn?

**Comment by calumgunn** [comment]
@mrmckeb Sadly not as it's in a private repo... I'll try to find time to create a minimal reproduction today.

**Comment by 0tho** [comment]
@mrmckeb deleting node_modules, lockfile and reinstalling didn't solve the problem. (tried both npm and yarn)

I also can't share my main repo, but I will try to create a minimum project later.

I believe this error could be related to [this](https://github.com/facebook/create-react-app/pull/7718)

**Comment by 0tho** [comment]
@mrmckeb updated to `react-scripts@3.1.2` and for me it has fixed the problems.
