### ISSUE TITLE
Doc issue: link to storybook's storybook does not work

### ISSUE THREAD

**Issue by just-boris** [storybookjs/storybook#8224]
**Describe the bug**

There is a mention of storybook's own storybook page in this section:
https://storybook.js.org/docs/addons/writing-addons/#re-using-existing-components

However, the link does not contain anything relevant

**To Reproduce**
1. Go to https://storybook.js.org/docs/addons/writing-addons/#re-using-existing-components
2. Click on "our storybook"

**Expected behavior**
See a storybook for storybook's components

**Comment by lbelavoir** [comment]
@shilman If I can contribute, I'll be happy to do a PR to fix this small issue. Do you have a link in mind where it should lead to ?

**Comment by just-boris** [comment]
Fixed in https://github.com/storybookjs/storybook/pull/8273, thank you!
