### ISSUE TITLE
Viewport addon: Add option to handle viewport change

### ISSUE THREAD

**Issue by hgenru** [storybookjs/storybook#8230]
Before there was an option to handle viewport change. But now this option is [deprecated](https://github.com/storybookjs/storybook/commit/a5dd722190ed66d11ace1823f927a9c74add0921#diff-0b19096a27d5827867e96b205e01a2ffR35). Also, there is an [event about that](https://github.com/storybookjs/storybook/blob/next/addons/viewport/src/constants.ts#L7), but this event isn't documented and maybe not implemented yet.

Please, add an option to handle viewport change or give me advice about implementation. This kind of functionality is needing for me to develop an addon for pixel-perfect markup preview.

**Comment by jlazarski** [comment]
Agreed.  Please add this functionality back in.  It is necessary on occasion to react to a viewport change in code that wouldn't be covered by just CSS alone.

**Comment by raufabr** [comment]
@shilman Is it possible to pick this issue? Would like to try a first issue for this project 👍

**Comment by shilman** [comment]
@raufabr it's all yours! 🚀

**Comment by raufabr** [comment]
Hi @shilman I tried setting up everything on my machine but am struggling to figure out how to set up storybook on my machine. Can you help me here?

**Comment by shilman** [comment]
@ndelangen can you help out @raufabr ?

**Comment by ndelangen** [comment]
@raufabr definitely! How about a call on Thursday?

I'm in the EU timzone, you can PM me on discord:
https://discord.gg/sMFvFsG

**Comment by raufabr** [comment]
Hey @ndelangen sorry I was busy yesterday. How about today? Do you have any time? I'm based in the EU timezone as well.

**Comment by ndelangen** [comment]
Yeah I'm available right now!

**Comment by hgenru** [comment]
In October I started building MR for this issue but had some problems with typings. By my Idea package should extend emit, on and off methods of Channel API. But declaration extending wasn't working for me. I tried some ways, but no solution was found.

Now I have time to back to the problem and there are two options:
— don't write typing
— learn more and extend typing in a different way

Do you have experience with typing extending? @raufabr what status of your MR?

https://github.com/hgenru/storybook/commit/f849cd8b29768977a3d05dfa110d0ba89b981b3d#diff-3b1024bf09c2de209faf08d3717b0269R11

**Comment by ndelangen** [comment]
@hgenru go for "don't write types" and make it work. We'll find someone to assist with the typings after! 

Just add a bunch of `any`s, 

> make it work, make it right, make it fast. - in that order

**Comment by hgenru** [comment]
@ndelangen I created PR, please look: https://github.com/storybookjs/storybook/pull/9201

**Comment by maniator** [comment]
Any updates here?

**Comment by ndelangen** [comment]
You should be able to subscribe to the addon's state with:
```js
useAddonState('storybook/viewport')
```

We'll however possibly change this to use global args in 6.1:
https://github.com/storybookjs/storybook/pull/11627#issuecomment-664328874

**Comment by hgenru** [comment]
@ndelangen is this is the right way or just hack? Will event API deprecated?

**Comment by ndelangen** [comment]
Hasn't been decided yet. My proposal is to migrate it to use args, and then re-rendering should just happen automatically when the viewport changes, and you can read the current value off of args!

**Comment by ndelangen** [comment]
If you'd be keen to take a stab at this migration, I'd be happy to assist you.

You can schedule a meeting with me to get you up to speed here:
https://calendly.com/ndelangen/storybook

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if this is still relevant in SB 7.x.
