### ISSUE TITLE
UI: Option to collapse single-story components

### ISSUE THREAD

**Issue by klangfarbe** [storybookjs/storybook#8255]
Hi,

currently I migrate to Storybook 5.2 and update all stories to the new CSF. I recognised that it isn't possible to reuse a story title for grouping simple stories as you could before with `storiesOf`. 

*For example:* If you have a group `atoms` and some simple components belonging to that group, e.g. a checkbox and a radio button with one story for each component, you **must** specify a unique name as a title since the stories are located in different source files. This leads to unnecessary and ugly folder structures with only one entry inside:

<img width="203" alt="storybook-csf-wanted" src="https://user-images.githubusercontent.com/386914/65965831-88396680-e45f-11e9-8001-47d81c5dd9f2.png">

Instead what I would like to have is this:

<img width="207" alt="storybook-csf-current" src="https://user-images.githubusercontent.com/386914/65965826-840d4900-e45f-11e9-859c-40d59f2d7d0f.png">

This behaviour currently can only be achieved with some `index.stories.js` file with transient exports of all stories from the sub-stories and one default export:

```js
export default {
  title: "Form Elements|Atoms"
};

export * from "./Checkbox.stories";
export * from "./FormField.stories";
export * from "./Radio.stories";
```

While `FormSelect` has multiple stories exported and therefore a default export like
```js
export default {
  title: "Form Elements|Atoms/FormSelect"
}

export const defaultStory = ...
export const placeholder = ...
export const customSlot = ...
```

My suggestion would be to create folders in the component tree only, if there are multiple stories exported. Otherwise the `title` from the `default` export should be used as the story title:

```js
export default {
  title: "Form Elements|Atoms/CheckBox"
}

export const onlyOneStory = ...
```

Here the visible story would have the name `CheckBox` instead of `Only One Story`. If we add another story to the file, the UI creates the folder `CheckBox` containing both stories. The benefit would be that you still can group stories from different simple components and keep the requirement to have a unique title in a `default` export in each story-file.

Best regards,
Chris

**Comment by shilman** [comment]
Related: #8035 #7700 

We definitely wouldn't make this the default behavior since it would be a breaking change. I'm open to the idea of making it opt-in, though, since it seems to be a frequently requested feature.

You can also achieve this with https://github.com/storybookjs/storybook/pull/8133

**Comment by klangfarbe** [comment]
Thanks for the info, I will check out #8133. Would be good if this could be an opt-in functionality.

**Comment by fernandopasik** [comment]
The feature from https://github.com/storybookjs/storybook/pull/8133 can provide a possible solution, but you end up with all your stories having the same title
```
export default {
  component: MyComponent,
  title: 'My grouped stories',
}
```

export const myComponent => () => <MyComponent />

from the maintainability perspective seems not great to repeat the title in every story

**Comment by tmeasday** [comment]
@ghengeveld can we add this feature to the sidebar work you've been doing?

**Comment by ghengeveld** [comment]
I discussed this with @shilman today. We're inclined to implement the following:

- IF a component has **exactly one** story
- AND the story name **exactly matches** the component name
- **Hide the component** node in the tree view
- **Show the story** node instead

We think this should be the built-in behavior, without any opt-in/opt-out configuration.

This behavior is similar to docs-only mode, except that docs-only hides the **stories**, applies to **all** components, and changes the icon.

**Comment by thany** [comment]
Yes please! After upgrading from `storiesOf()` notation to CSF, the titles must be unqiue per stories-file, which wasn't the case in storiesOf-notation. So now I had to make them unique, basically putting every story one level deeper in the stories tree.

**Comment by ghengeveld** [comment]
@klangfarbe @fernandopasik @thany Please take a look: https://github.com/storybookjs/storybook/pull/13039

**Comment by shilman** [comment]
Ermahgerd!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.0-beta.5 containing PR #13039 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
