### ISSUE TITLE
Storysource addon shows selected story highlight incorrectly when using uglyCommentsRegex

### ISSUE THREAD

**Issue by andrewpeterprifer** [storybookjs/storybook#8262]
**Describe the bug**
I have a `// @ts-check` comment on top of every file and I'm using `uglyCommentsRegex` to remove it from the story source. This works, however the highlight for the selected story shifts by two lines, the same amount that was removed from the top of the file.

**To Reproduce**
1. Create a story with an ugly comment on top
2. Add the ugly comment to `uglyCommentsRegex` in the custom webpack config
3. Launch storybook and go to the Story addon panel
4. See the gray highlight indicating the selected story shifted down

**Expected behavior**
The gray highlight precisely covers the selected story in the storysource panel

**Screenshots**
<img width="1050" alt="Screen Shot 2019-10-01 at 18 47 51" src="https://user-images.githubusercontent.com/2991360/65982668-263b2a00-e47c-11e9-9f31-f82d9f9ffb1f.png">

**Code snippets**
```js
// .storybook/webpack.config.js
module.exports = function({ config }) {
  config.module.rules.push({
    test: /stories\.jsx?/,
    loaders: [
      {
        loader: require.resolve('@storybook/source-loader'),
        options: {
          uglyCommentsRegex: [
            /^eslint-.*/,
            /^global.*/,
            /^eslint-.*/,
            /@ts-check/,
          ],
        },
      },
    ],
    enforce: 'pre',
  });

  return config;
};
```
```js
// @ts-check

import React from 'react';
import chroma from 'chroma-js';
import { zonedTimeToUtc } from 'date-fns-tz';

import Block from '.';

export default {
  component: Block,
  title: 'Staff planner | Block',
  decorators: [
    story => <div style={{ width: 132, height: 104 }}>{story()}</div>,
  ],
};

export const empty = () => (
  <Block
    kind="bookable"
    color={chroma('#A6FCC9')}
    timeInterval={{
      start: zonedTimeToUtc(new Date(0, 0, 0, 9, 0), 'Europe/Amsterdam'),
      end: zonedTimeToUtc(new Date(0, 0, 0, 17, 0), 'Europe/Amsterdam'),
    }}
    heightPercentage={100}
    progressPercentage={0}
  />
);

// ...
```
**System:**
```
  System:
    OS: macOS 10.15
    CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
  Binaries:
    Node: 12.10.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 77.0.3865.90
    Safari: 13.0.1
  npmPackages:
    @storybook/addon-actions: ^5.2.1 => 5.2.1 
    @storybook/addon-contexts: ^5.2.1 => 5.2.1 
    @storybook/addon-links: ^5.2.1 => 5.2.1 
    @storybook/addon-storysource: ^5.2.1 => 5.2.1 
    @storybook/addons: ^5.2.1 => 5.2.1 
    @storybook/cli: ^5.3.0-alpha.5 => 5.3.0-alpha.5 
    @storybook/react: ^5.2.1 => 5.2.1 `
```

**Comment by andrewpeterprifer** [comment]
@shilman  I’m not sure if there’s a misunderstanding but just to clarify, uglyCommentsRegex is an option of the storysource loader which is supposed to be officially supported, not something external, so I’m not sure if the compatibility with other tools label is correct.

**Comment by shilman** [comment]
@andrewpeterprifer Indeed that was a misunderstanding. good catch! 😄

**Comment by andrewpeterprifer** [comment]
@shilman are you sure this shouldn't be labeled as a bug instead?

**Comment by andrewpeterprifer** [comment]
bump
