### ISSUE TITLE
Disable Story panel

### ISSUE THREAD

**Issue by ethikz** [storybookjs/storybook#8276]
I could be missing the option but I don't see anywhere in docs to disable showing the `Story` panel.  

I still want to show other actions in the panel but just not the `Story` specific one

**Comment by Pau1fitz** [comment]
@ethikz is [this](https://storybook.js.org/docs/configurations/options-parameter/) what you are looking for? `showNav`, `showPanel`?

**Comment by ethikz** [comment]
@Pau1fitz No unfortunately.  That seems to not show the whole bottom panel for me.  I just wanted to not show the Story addon but I didn't see a way so I just removed the add on and it's gone.
