### ISSUE TITLE
Addon-docs: story source showing "No code available".

### ISSUE THREAD

**Issue by sergiop** [storybookjs/storybook#8290]
Story source showing **"No code available"**

<img width="491" alt="Schermata 2019-10-04 alle 00 29 56" src="https://user-images.githubusercontent.com/2235134/66168738-60ecc000-e63e-11e9-9d79-3fc846e54539.png">
 
`/stories/button.stories.tsx`:
```javascript
import React from 'react'
import { radios } from '@storybook/addon-knobs'
import Button, { Type } from '../src/components/Button/Button'

export default {...}

const typeOptions = {
  Default: 'default',
  Action: 'action',
}

export const withText = () => (
  <Button
    label="Button label"
    type={radios('Type', typeOptions , 'default') as Type}
  />
)
```
`/src/components/Button/Button.tsx`:
```javascript
export type Type = 'default' | 'action'
```
If I remove **"as Type"**, code block **is shown as expected** (but Typescript show me this error: *Type 'string' is not assignable to type '"default" | "action"'.ts(2322)*)

<img width="490" alt="Schermata 2019-10-04 alle 00 31 30" src="https://user-images.githubusercontent.com/2235134/66168878-c80a7480-e63e-11e9-8986-927014cdffa1.png">

**Comment by sergiop** [comment]
I have a similar issue with `addon: storysource`, caused by the same type declaration inside the **Button** story. Other components story sources work as expected. This makes me think that is not `addon: docs` related issue.

Let me know if you need me to share a github repo with this config to reproduce the issue.

<img width="521" alt="Screenshot_2019-10-04_at_12_18_33" src="https://user-images.githubusercontent.com/2235134/66200664-df2e7e00-e6a1-11e9-9cd2-056e4f09a96e.png">

**Comment by shilman** [comment]
@sergiop can you try with the latest beta? lots of source loader improvements since you filed this...

**Comment by sergiop** [comment]
Hi @shilman, with `5.2.6` the issue persists, but with `5.3.0-beta.6` I can correctly see the story source, both on the docs page and story pane. Thanks.
