### ISSUE TITLE
What is the actual requirement for a folder to appear as folder?

### ISSUE THREAD

**Issue by raphaellueckl** [storybookjs/storybook#8292]
We tried to approximate it, but nothing really turned out to be true.

![Screenshot 2019-10-04 at 08 48 18](https://user-images.githubusercontent.com/8248662/66187027-1beb7c80-e684-11e9-8c11-7d4a2a096f7d.png)

Is it the amount of stories inside the folder? Is it the amount of files that are being displayed within a folder? Or is it maybe the depth of the folder that makes it appear as a folder?

This is just out of curiosity, we plan to handle our stories differently and then that folder "problem" should vanish anyways.

Explanation: Button and Input Text are labeled as folders instead of components (see the icon).

**Comment by shilman** [comment]
AFAIK "groups" that contain only stories are shown as components and groups that contain anything else are shown as folders.

I think we could change this behavior if there was an alternative proposal that made sense.

**Comment by raphaellueckl** [comment]
Thanks @shilman , issue can be closed if you want.

**Comment by andrewplummer** [comment]
Would be nice to allow specifying this in the `<Meta />` component. The plus icon works great to show it can be expanded, I don't really need the distinction between folders and "something else" which isn't really explained well visually by the icons themselves.
