### ISSUE TITLE
Can't access React v3.3 of storybook

### ISSUE THREAD

**Issue by kanishk30** [storybookjs/storybook#8293]
I need to migrate from v3.3 to v5.2 of storybook for my app build in react. However, I m unable to see the diff and go through the docs of v3.3. 

**To Reproduce**
1. Go to https://release-3-3--storybooks-official.netlify.com/
2. See error of NOT FOUND

**Expected behavior**
Shouls work to see the expected behaviour

**Comment by shilman** [comment]
Recommended reading:

- https://medium.com/storybookjs/migrating-to-storybook-4-c65b19a03d2c
- https://medium.com/storybookjs/storybook-5-migration-guide-d804b38c739d

**Comment by kanishk30** [comment]
Thanks, it worked. You may consider to include this in the official documentation as well.
