### ISSUE TITLE
Material UI - custom styles are not getting applied

### ISSUE THREAD

**Issue by Vivek205** [storybookjs/storybook#8295]
**Describe the bug**
The default styles of the material-ui components are overriding my styles.It is happening only in the storybook.

**To Reproduce**
1. Customize MaterialUI `Button` component using `makeStyles`.
2. Host the app using storybook.
3. You will find that your styles are ignored by the browser.

**Expected behavior**
I want to view my customized MaterialUI component.

**Screenshots**
The background color in the screenshot provided below was overridden by the default materialUI button styles
![image](https://user-images.githubusercontent.com/26110173/66208414-a3f87300-e6d2-11e9-85bf-efffcc02f1ac.png)

**Code snippets**
```
const StyledButton = ({ btnText }) => {
  const classes = useStyles();
  return (
    <Button
      className={clsx(classes.styledButton, classes[buttonColor[type]])}
    >
      {btnText}
    </Button>
  );
};
```
**System:**
System:
    OS: Linux 4.15 Ubuntu 18.04 LTS (Bionic Beaver)
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Binaries:
    Node: 8.10.0 - /usr/bin/node
    Yarn: 1.15.2 - /usr/bin/yarn
    npm: 6.8.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 77.0.3865.90
    Firefox: 69.0.2
  npmPackages:
    @storybook/addon-actions: ^5.1.11 => 5.2.1 
    @storybook/addon-links: ^5.1.11 => 5.2.1 
    @storybook/addons: ^5.1.11 => 5.2.1 
    @storybook/react: ^5.1.11 => 5.2.1

**Comment by speculees** [comment]
You create a HOC component with MUIs ThemeProvider, then use is in each story

**Comment by Vivek205** [comment]
@speculees I have already created a HOC for MUI and added it using `addDecorator` globally.. The issue is, the default styles of MUI are overriding my styles. The way I see it is, the default styles are added after my styles are added, so it changes the `css specificity`
