### ISSUE TITLE
Is it possible to mock the current url?

### ISSUE THREAD

**Issue by javierguzman** [storybookjs/storybook#8303]
Hello,

I have a component that behaves in two ways depending on the url the user is currently visiting. I know there is a queryparam addon that allows you to mock query parameters. However,  I have not found anything related to the url itself. Is there a way to tell a story with a specific url?

Thank you in advance and regards.

**Comment by javierguzman** [comment]
I have managed today to do this with react-router-addon. Apparently you can specify the current path as second argument when calling StoryRouter, specifically the param name is "initialEntries".

I close this.

**Comment by kasir-barati** [comment]
More info, like sample code or ref would help others to see how you've done it.
