### ISSUE TITLE
Storybook hot reloading causes hooks error

### ISSUE THREAD

**Issue by wgpsutherland** [storybookjs/storybook#8306]
I get the following error when my storybook hot reloads. It works perfectly on the first load:

    TypeError: Cannot read property 'hooks' of undefined
    at StoryStore.cleanHooks (http://localhost:9009/vendors~main.0e777466815571a0333e.bundle.js:6197:22)
    at renderMain (http://localhost:9009/vendors~main.0e777466815571a0333e.bundle.js:8181:22)
    at StoryStore.renderUI (http://localhost:9009/vendors~main.0e777466815571a0333e.bundle.js:8296:9)
    at StoryStore.emit (http://localhost:9009/vendors~main.0e777466815571a0333e.bundle.js:6474:35)
    at http://localhost:9009/vendors~main.0e777466815571a0333e.bundle.js:5943:16

I am using a redux provider, although I am not sure if it is related. It's code and the stories look like this regardless:

    // provider.tsx
    const Provider: React.FC = ({ children }) => (
        <ThemeProvider theme={theme}>
            <Provider store={store}>
                <Router>
                    {children}
                </Router>
            </Provider>
        </ThemeProvider>
    )
    
    export default Provider

    // decorators.tsx
    export const withProvider = (storyFn: any) => <Provider>
        {storyFn()}
    </Provider>

    // 2-TodoCard.stories.tsx
    const complete = () => <TodoCard todo={completeTodo} />  // the TodoCard is just a React.FC
    const incomplete = () => <TodoCard todo={incompleteTodo} />
    
    storiesOf('TodoCard', module)
        .addDecorator(withProvider)
        .add('complete', complete)
        .add('incomplete', incomplete)

webpack.config.js (inside .storybook/ - normal app uses default create-react-app webpack):

    module.exports = ({ config }) => {
        config.module.rules.push({
            test: /\.(ts|tsx)$/,
            use: [
                {
                    loader: require.resolve('awesome-typescript-loader'),
                },
                // Optional
                {
                    loader: require.resolve('react-docgen-typescript-loader'),
                },
            ],
        });
        config.resolve.extensions.push('.ts', '.tsx');
        // config.entry = config.entry.filter(singleEntry => !singleEntry.includes('/webpack-hot-middleware/'));  // hot reloading causing a hooks bug
        return config;
    };

**Comment by shilman** [comment]
@wgpsutherland Have you tried `4.3.0-alpha.x`? There are one or more related bugfixes there that haven't made it back to `latest` yet.

**Comment by wgpsutherland** [comment]
Hey, thanks for the reply. I upgraded from 

    devDependencies": {
        "@storybook/addon-actions": "^5.2.1",
        "@storybook/addon-info": "^5.2.1",
        "@storybook/addon-links": "^5.2.1",
        "@storybook/addons": "^5.2.1",
        "@storybook/react": "^5.2.1",
        "@types/storybook__react": "^4.0.2"
     }

to 

    "devDependencies": {
        "@storybook/addon-actions": "^5.3.0-alpha.11",
        "@storybook/addon-info": "^5.3.0-alpha.11",
        "@storybook/addon-links": "^5.3.0-alpha.11",
        "@storybook/addons": "^5.3.0-alpha.11",
        "@storybook/react": "^5.3.0-alpha.11",
        "@types/storybook__react": "^4.0.2"
      }

and the issue still persists

**Comment by shilman** [comment]
@wgpsutherland Thanks for trying. Can you try disabling `addon-info`? It's been mostly replaced by `addon-docs` and it wouldn't surprise me if it's what's causing the problem.

**Comment by Hypnosphi** [comment]
@wgpsutherland does it happen on any code change?

**Comment by wgpsutherland** [comment]
@shilman I'm afraid it still happens after removing `addon-info`.
@Hypnosphi the error happens when modifying the story code of the story the browser is on, and the story you just changed disappears from the sidebar and the error is persistent across all other stories. When you modify the code of a story the browser is not currently navigated to, the story that you modified disappears from the sidebar, and the other stories continue to work, including the one you were navigated to.

**Comment by gpawlik** [comment]
I think the following method: https://github.com/storybookjs/storybook/blob/next/lib/client-api/src/story_store.ts#L399 should be changed to something safer, eg.:
```
cleanHooks(id: string) {
    this._data[id] && this._data[id].hooks.clean();
}
```

**Comment by MarkLyck** [comment]
I'm having this issue as well.

**Comment by Hypnosphi** [comment]
@wgpsutherland I tried to reproduce this in our own setup, and it happens only when I rename a story. If you're saying that in your case it also happens on any change in story _code_ (as opposed to the name), please create a GitHub repo with minimal reproduction

**Comment by wgpsutherland** [comment]
@Hypnosphi it happens every time I change the code in the story or in the component. I've created this repo that reproduces the issue: https://github.com/wgpsutherland/storybook-hotreload-repro

**Comment by Hypnosphi** [comment]
@wgpsutherland Looks like you're mixing [Component Story Format](https://storybook.js.org/docs/formats/component-story-format/) and [`storiesOf` API](https://storybook.js.org/docs/formats/storiesof-api/) in your stories:

```js
export default {
    title: 'Button',
};

storiesOf('Button', module)
    .add('gray', () => <Button color='gray' fluid size='large' type='submit'>Add</Button>)
    .add('blue', () => <Button color='blue' fluid size='large' type='submit'>Add</Button>)
```

You have to pick one. So it should be either
```js
export default {
    title: 'Button',
};

export const gray = () => <Button color='gray' fluid size='large' type='submit'>Add</Button>
export const blue = () => <Button color='blue' fluid size='large' type='submit'>Add</Button>
```

or 
```js
storiesOf('Button', module)
    .add('gray', () => <Button color='gray' fluid size='large' type='submit'>Add</Button>)
    .add('blue', () => <Button color='blue' fluid size='large' type='submit'>Add</Button>)
```

**Comment by Hypnosphi** [comment]
@shilman I think we should show some warning when CSF and storiesOf are mixed inside a single file

**Comment by Hypnosphi** [comment]
Tu sum everything up, there are two issues here:

1. Stories get removed on HMR. The fix is to removing duplicate kind declarations, i.e. picking one from `export default` and `storiesOf`
2. When you remove a story, an exception is thrown. Fixed by #8408

**Comment by shilman** [comment]
@Hypnosphi In the first version of CSF I actually forbid duplicate kinds. Then I re-enabled it due to this PR from @hipstersmoothie, which I tested (but perhaps not thoroughly enough). Can you take a look: https://github.com/storybookjs/storybook/pull/8133

**Comment by Hypnosphi** [comment]
@shilman Let's add duplicate kinds in official-storybooks and test how HMR works?

**Comment by Hypnosphi** [comment]
@shilman BTW #8133 was [released](https://github.com/storybookjs/storybook/releases/tag/v5.3.0-alpha.12) in `alpha.12` while the repro [uses](https://github.com/wgpsutherland/storybook-hotreload-repro/blob/master/package-lock.json#L1802) `alpha.11` and I still see no warning here, probably because only one of kind declarations is CSF.

The problem with duplicate kinds and HMR is not CSF-specific, it applies to `storiesOf` as well.

**Comment by shilman** [comment]
Egads!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-alpha.18 containing PR #8411 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by Hypnosphi** [comment]
Issue with HMR not fixed yet

**Comment by shilman** [comment]
Ermahgerd!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.4 containing PR #8411 that references this issue. Upgrade today to try it out!

Closing this issue. Please re-open if you think there's still more to do.

**Comment by selrond** [comment]
Not sure how is #8411 fixing it, as I don't use `storiesOf` in my app at all, but it works!

**Comment by Hypnosphi** [comment]
@selrond I think it was #8408 in your case
