### ISSUE TITLE
using svg-spritemap-webpack-plugin with storybook

### ISSUE THREAD

**Issue by romaindurand** [storybookjs/storybook#8318]
I'm using a pretty straightforward config file, but no file is emitted

**To Reproduce**
Steps to reproduce the behavior (I created a minimal repo to reproduce the issue)
- clone https://github.com/romaindurand/storybook-svgspritemap/
- install deps, run storybook, search for generated spritemap

**Expected behavior**
A spritemap.svg file should be generated in `./node_modules/@storybook/core/dist/public`

**Code snippets**
Here's my custom webpack config :
```js
const SVGSpritemapPlugin = require('svg-spritemap-webpack-plugin')
const path = require('path')

module.exports = async ({ config }) => {
  config.plugins.push(new SVGSpritemapPlugin(path.join(__dirname, '../assets/icons/*.svg')))
  return config
}
```

**System:**
Environment Info:

  System:
    OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Xeon(R) CPU E3-1270 v3 @ 3.50GHz
  Binaries:
    Node: 8.15.1 - /usr/local/bin/node
    Yarn: 1.15.2 - /usr/bin/yarn
    npm: 6.10.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 74.0.3729.131
  npmPackages:
    @storybook/addon-actions: ^5.2.3 => 5.2.3 
    @storybook/addon-links: ^5.2.3 => 5.2.3 
    @storybook/addons: ^5.2.3 => 5.2.3 
    @storybook/react: ^5.2.3 => 5.2.3

**Comment by jhopley-stadion** [comment]
I am having the same issue now.
