### ISSUE TITLE
mdx is not compiling

### ISSUE THREAD

**Issue by JamesIves** [storybookjs/storybook#8322]
**Describe the bug**

I'm trying to get `addon-docs` working, but I'm running into a syntax error and I'm not sure why. I'm requiring `addon-docs` via `presets.js`, and I've updated my story loader to support `mdx` like so:

```javascript
module.exports = [
    {
      name: '@storybook/addon-docs/react/preset',
      options: {
        configureJSX: true,
        babelOptions: {},
        sourceLoaderOptions: null,
      },
    },
  ];
```

```
const req = require.context('../components', true, /story\.(js|mdx)$/);
```

I've got a single story named `Box.story.mdx` which you can view [here](https://github.com/UnitedIncome/components/blob/app-4006/components/atoms/Box/Box.story.mdx).  For whatever reason I get a syntax error, despite it being very simple.

```
WARNING in ./components/atoms/Box/Box.story.mdx
Module build failed (from ./node_modules/@mdx-js/loader/index.js):
SyntaxError: Unexpected token (2:0)
```

Am I missing something in the setup? I've tried using the `stories.mdx` naming convention also but I run into the same issue. `babel-loader` is also required in `package.json`.

**To Reproduce**
1. Go to `Box.story.mdx`
2. It does not compile the mdx version of the story.
3. The old method of creating stories does work.

**Expected behavior**

I expect it to compile.

**Additional context**

I followed the setup guide but I'm wondering if there's a step that's missing when migrating to 5.2 that is not docs related?

**Comment by shilman** [comment]
@JamesIves Looking at that branch:

- Great-looking storybook! 💯 
- You'll need to update the `configure` call in `.storybook/config.js`: https://github.com/storybookjs/storybook/blob/next/docs/src/pages/basics/writing-stories/index.md#loading-stories

I checked out your branch and made the following mod and it's working for me:

```js
function loadStories() {
  return req
    .keys()
    .map(req)
    .filter((req) => Boolean(req.default));
}
```

My changes don't explain the error you're seeing, however, so I'm not sure what's going on there. Not able to reproduce the problem. Try removing node_modules and reinstalling?

**Comment by JamesIves** [comment]
Jk found it! thanks so much for your help: https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/mdx.md#decorators-and-parameters
