### ISSUE TITLE
Couldn't load images from public folder, looks like something is missing from documentation.

### ISSUE THREAD

**Issue by vanoMekantsishvili** [storybookjs/storybook#8328]
I am trying to load images from public folder like "import imageName from "../../public/imageName.svg" but it is not working. I added file loader as documentation suggested but still not working. please anyone give me any suggestions. 

My custom Webpack config looks like below:

```js
const path = require('path');

module.exports = ({ config }) => {
    config.module.rules.push({
        test: /\.scss$/,
        use: ['style-loader', 'css-loader', 'sass-loader'],
      });
    config.module.rules.push({
      test: /\.(ts|tsx)$/,
      use: [
        {
          loader: require.resolve('awesome-typescript-loader'),
        },
      ],
    });
    config.module.rules.push({
      test: /\.(svg|png|jpe?g|gif)$/i,
      use: [
        {
          loader: 'file-loader',
        },
      ]
    },);
    
    config.resolve.extensions.push('.ts', '.tsx')

    return config;
};
```

It show error below: 

<img width="613" alt="error" src="https://user-images.githubusercontent.com/15087225/66372661-3ccb0f00-e9af-11e9-8647-7c1620543c45.png">

I searched a lot and couldn't find any clear answer why file loader doesn't work in storybook. One weird part is that I am using same configuration for 'sass' and typescript' - and they work perfectly. There is some kind of issue or I am doing sth incorrectly? thank you whoever find some time to help me out with this problem.

**Comment by shilman** [comment]
maybe you can put your svg inside your `src` directory if you want to refer to it like that. if you put it in `public`, you can refer to it as `<img src="/public/clock.svg" />`.

**Comment by vanoMekantsishvili** [comment]
Sorry people forgot to update my question here. I fixed my issue and wrote an answer to my question on StackOverflow. If someone has same issue you can check [this link](https://stackoverflow.com/questions/58267903/serving-static-files-in-storybook-js), cheers
