### ISSUE TITLE
TypeScript Preset - Make react-docgen-typescript-loader optional

### ISSUE THREAD

**Issue by darondel** [storybookjs/storybook#8337]
**Description**
At the moment, we cannot use  the TypeScript preset without installing `react-docgen-typescript-loader`. This one should be optional for non-React storybooks.

**Solution**
Make `react-docgen-typescript-loader` dependency optional.

**Alternatives**
None.

**Are you able to assist bring the feature to reality?**
If I can help, yes of course. :)

**Additional context**
None.

**Comment by shilman** [comment]
@darondel Sorry this got caught in the shuffle. Would it be possible for you to remove this from the typescript preset and adding it to `addon-docs/react/preset`?

**Comment by darondel** [comment]
@shilman Sure, I can do that. Presets are in [storybookjs/presets](https://github.com/storybookjs/presets). What about the ones for docs addon? Any guidance would help. :)

**Comment by shilman** [comment]
Released `preset-typescript@2.0.0` which contains https://github.com/storybookjs/presets/pull/68 and fixes this issue. See its CHANGELOG for migration info: https://github.com/storybookjs/presets/blob/master/packages/preset-typescript/CHANGELOG.md#200
