### ISSUE TITLE
storybook/angular is not respecting css settings in angular.json

### ISSUE THREAD

**Issue by ctaepper** [storybookjs/storybook#8340]
**Describe the bug**
My angular application has the following config in `angular.json`
```json
"extractCss": true,
"styles": [
  "apps/storybook/src/styles.scss",
    {
      "input": "apps/storybook/src/theme-light.scss",
      "inject": false
    },
    {
      "input": "apps/storybook/src/theme-dark.scss",
      "inject": false
    }
]
```
when I build the app, I end up with 3 css files: `styles.css`, `theme-light.css` and `theme-dark.css`. The 2 theme files get build into separate files. `extractCss:true` tells the compiler to build separate css files and `inject:false` tells the compiler not to insert this css file into the index.html. At runtime, I insert the related stylesheet according to the user's theme settings

My intentions with storybook are now to use `@storybook/addon-cssresources` in order to switch those theme files within storybook.

However, when I run storybook, it does not respect this setting from `angular.json` but produces one large `main.css` which contains the styles from all those 3 scss input sources

**Expected behavior**
I expect that storybook, just as the angular compiler, will create 3 files and only attach one file to the component preview. Then, using the addon, I can add the theme files

**System:**
```
  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
  Browsers:
    Chrome: 77.0.3865.90
    Safari: 13.0.2
  npmPackages:
    @storybook/addon-actions: 5.2.3 => 5.2.3
    @storybook/addon-cssresources: 5.2.3 => 5.2.3
    @storybook/addon-knobs: 5.2.3 => 5.2.3
    @storybook/addon-notes: 5.2.3 => 5.2.3
    @storybook/addon-storysource: 5.2.3 => 5.2.3
    @storybook/addon-viewport: 5.2.3 => 5.2.3
    @storybook/angular: 5.2.3 => 5.2.3
```

**Additional context**
my workaround for now is to prod-build the storybook angular application and then run storybook and serve the dist directory as static folder (`-s dist/app`). While that works quite well for deployment, it is horrible for development as I lose the live reload option

**Comment by ctaepper** [comment]
still valid problem... anyone?

**Comment by cwmrowe** [comment]
I'm also getting this issue. @shilman do you know if there is a plan to fix this or another way to achieve the same result?

**Comment by shilman** [comment]
No idea. cc @kroeder @gaetanmaisse

**Comment by Fl0r14n** [comment]
The issue still persists. Any workarounds?

**Comment by OvidiuGuta** [comment]
I have the same scenario as @ctaepper and obviously the same problem. It works perfect with ng serve and build but when running storybook both the theme and theme-dark files are loaded by webpack in the bundles and they are both applied so I get the styles for whichever I declare last in angular.json styles. 
The only workaround I can think of for now is to not use separate files for the themes, but bundle them together in styles.scss and put the dark one under a class, but the problem I have with this, besides the performance issues, is that now I don't have a way of switching the theme dynamically inside storybook.

My question is why is this happening and can we do anything about it?

**Comment by Fl0r14n** [comment]
@OvidiuGuta For now just duplicate your application object in angular.json. Then call it 'storybook' and customize it there

"storybook": {
      "projectType": "application",
      "schematics": {
        "@schematics/angular:component": {
          "style": "scss"
        }
      },
      "root": "",
      "sourceRoot": "src",
      "prefix": "app",

....

In my main app I have 2 themes like this:

"styles": [
              "src/styles.scss",
              {
                "input": "src/themes/alpha/theme.scss",
                "inject": false,
                "bundleName": "theme-alpha"
              },
              {
                "input": "src/themes/lambda/theme.scss",
                "inject": false,
                "bundleName": "theme-lambda"
              }
            ],

so in storybook app definition just remove one of them

**Comment by ctaepper** [comment]
@Fl0r14n @OvidiuGuta @cwmrowe here is what I ended up with: 
1. create app in `angular.json` called `storybook`. If Storybook finds this app, it will be used as build config (instead of the `angular.json` default app.
2. Only use one theme there and bundle it with the "regular css", this is how my config looks like: 
   ```
   "styles": [
     "apps/storybook/src/styles.scss",
     "apps/storybook/src/theme-light.scss"
   ]
   ```
3. Use the [cssresources](https://github.com/storybookjs/storybook/tree/next/addons/cssresources) Storybook plugin to additionally provide the other themes.
  ```
  import { withCssResources } from '@storybook/addon-cssresources'
  import { default as darktheme } from '../apps/storybook/src/theme-dark.scss'
  
addDecorator(withCssResources)
addParameters({
    cssresources: [
        {
            id: `dark-theme`,
            code: `<style>${darktheme}</style>`,
            picked: false,
            hideCode: true
        }
    ]
})
  ```  
4. Storybook will now display the default theme and you can override that by selecting the different theme from the plugin panel: 
<img width="681" alt="Bildschirmfoto 2021-02-08 um 17 32 41" src="https://user-images.githubusercontent.com/4319790/107249627-d12a0380-6a33-11eb-981e-22cc2573a76f.png">

**Comment by kausters** [comment]
Just wanted to chime in support of fixing this (SB 7.6.20). We have an Angular project where we have one base stylesheet and one we add conditionally, coming from another package in node_modules.

```json5
// angular.json
"styles": [
    {
        "input": "node_modules/<…>/base-styles.scss",
        "inject": true
    },
    {
        "input": "node_modules/<…>/conditional-styles.scss",
        "inject": false,
        "bundleName": "conditional-global"
    },
    "src/project-styles.scss"
],
```

This works great with `"builder": "@angular-devkit/build-angular:browser"` — we get base and project styles, and conditional styles as are built to a separate file which we add with `<link rel="stylesheet" href="conditional-global.css">` when needed. But for Storybook, this fails bad, even though the JSON schema seems to support the same configuration.

Not only is the bundleName not recognized and no external file is generated (so `<link rel="stylesheet" href="conditional-global.css">` fails), but all the styles are merged into one file, giving us absolutely no way to conditionally add it, or even remove it if it's added by default.

So for now we resort to manually loading it in with inline webpack loaders in Storybook's `preview.js`:

```ts
import conditionalStyles from '!!raw-loader!sass-loader!node_modules/<…>/conditional-styles.scss';
```

which we then pass as string to a `<style>` element's innerHTML. It works, but it could be so much easier.
