### ISSUE TITLE
@storybook/angular & @storybook/addons require node types

### ISSUE THREAD

**Issue by sod** [storybookjs/storybook#8343]
Can't find it in the source code, but the published `@storybook/angular` & `@storybook/addons` version 5.2.3 types require node types:

![image](https://user-images.githubusercontent.com/905328/66405649-b7fde680-e9ea-11e9-8a6f-0190285000fc.png)
![image](https://user-images.githubusercontent.com/905328/66406695-55a5e580-e9ec-11e9-97d0-c2b617cd7848.png)

That conflicts with client code, e.g. we see lots of:

```log
Error:(10, 9) TS2322: Type 'Timeout' is not assignable to type 'number'.
```

Because the node.js setTimeout definition returns `Timeout` and the dom implementation returns `number`. Is that reference to node.js really required? Given that much of the code also runs in the browser, node.js types are kind of misleading anyway.

**Comment by sod** [comment]
The workaround I use right now it setting this in tsconfig.json compilerOptions:

```json
        "typeRoots": [
            "@types",
            "../node_modules/@types"
        ]
```

and created an empty `@types/node/index.d.ts` file. So when typescript tries to resolve the `/// <reference types="node" />`, it'll grab the empty definition instead of the one installed in `node_modules/@types`.

**Comment by aaronjensen** [comment]
This is a pretty important one, it just bit us as well.

**Comment by kroeder** [comment]
The client and server code of `app/angular` shares the same tsconfig with `types: ['node']`

Maybe we can use the tripple-slash reference directly where they are needed and remove `node` from the tsconfig 🤔 
Hopefully the same works for `@storybook/addon`

**Comment by aaronjensen** [comment]
I'm guessing its the uses of the global `NodeModule`:

https://github.com/storybookjs/storybook/blob/7ac1cab8d5039c35e0aa8dd92497ab16b75ae9bd/lib/addons/src/types.ts#L97

and

https://github.com/storybookjs/storybook/blob/5770c8e6357910f489a942a87cc579a3188db136/app/react/src/client/preview/index.ts#L13

**Comment by aaronjensen** [comment]
Still an issue.

**Comment by aaronjensen** [comment]
Still an issue, unless it's been addressed? Someone is assigned to it. It's probably not a tough issue to address.

**Comment by shilman** [comment]
@aaronjensen do you want to take a crack at this?

**Comment by ndelangen** [comment]
Maybe @gaetanmaisse knows how to solve this?

**Comment by aaronjensen** [comment]
I think I have a fix. Will submit soon.

**Comment by aaronjensen** [comment]
Try out https://github.com/storybookjs/storybook/pull/9213

**Comment by aaronjensen** [comment]
This was fixed.
