### ISSUE TITLE
Request to have Storybook work with FontAwesome 5's (angular-fontawesome) Icon Library.

### ISSUE THREAD

**Issue by adamlongaway** [storybookjs/storybook#8349]
Have Storybook work with FontAwesome 5's library feature. Currently when making a story there is now obvious way to use the icon library as it says in the documentation below, it needs to be part of the Angular Modules Constructor. Storybook Stories have no Constructor to add this code to.

https://github.com/FortAwesome/angular-fontawesome/blob/master/docs/usage/icon-library.md#using-the-icon-library

**Comment by christiancueto** [comment]
I'm running into issues using the both together, has there been any updates?

**Comment by devoto13** [comment]
I've described one working approach in [this SO answer](https://stackoverflow.com/a/58672268/1377864).
