### ISSUE TITLE
propType shows "unknown"

### ISSUE THREAD

**Issue by rawris** [storybookjs/storybook#8352]
@storybook/addon-info doesn't take PropTypes types, instead it shows "unknown"

1. use @storybook/addon-info
2. Define proptypes in a React Component
3. Build storybook again

**Expected behavior**
Storybook should show the propType of a Prop (eg.: String, func etc)

**Screenshots**
![image](https://user-images.githubusercontent.com/27147880/66466202-e8538c80-ea9f-11e9-8245-d2b338f50440.png)

**System:**
Environment Info:

  System:
    OS: macOS Mojave 10.14.4
    CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 77.0.3865.90
    Safari: 12.1
  npmPackages:
    @storybook/addon-actions: ^5.2.3 => 5.2.3 
    @storybook/addon-info: ^5.2.3 => 5.2.3 
    @storybook/addon-knobs: ^5.2.3 => 5.2.3 
    @storybook/addon-links: ^5.2.3 => 5.2.3 
    @storybook/addon-notes: ^5.2.3 => 5.2.3 
    @storybook/addon-storysource: ^5.2.3 => 5.2.3 
    @storybook/react: ^5.2.3 => 5.2.3

**Comment by shilman** [comment]
`Addon-info` is being superceded by `addon-docs`, which fixes a bunch of bugs and is easier to maintain. Please give it a try! https://medium.com/storybookjs/storybook-docspage-e185bc3622bf
