### ISSUE TITLE
react-native : rn-host-detect module has a bug

### ISSUE THREAD

**Issue by yomybaby** [storybookjs/storybook#8355]
**Describe the bug**
react-native use `rn-host-detect` module to find a host.
https://github.com/storybookjs/storybook/commit/4b35ffc9fb28e0332ef2e8b91b1ba03a0c4c0852#diff-8c8fb660862821ef881e7a34133fd4dcR35

`rn-host-detect` has a polyfill of `console.warn` and a bug : 
When [arguments[0].indexOf](https://github.com/jhen0409/rn-host-detect/blob/master/index.js#L33) is not a function, exception!

I was wondering why storybook use `rn-host-detect`? 
storybook [call `rn-host-detect`](https://github.com/storybookjs/storybook/blob/28fed37f0d7d6a3c1276d0e54060205858f54c29/app/react-native/src/preview/index.tsx#L84) even storyBookUI stated with `host` option explicitly.
```
const StorybookUIRoot = getStorybookUI({host:'192.168.0.123'});
```

**To Reproduce**
1. On iOS Simulator, `console.warn({})` with Debug mode enabled :
It works!
2. On iOS Simulator, `console.warn({})` with Debug mode disabled :
You can see the Red Error screen.

**Expected behavior**
console.warn work properly in any mode!

**Screenshots**
![Simulator Screen Shot - iPhone X - 2019-10-09 at 20 54 35](https://user-images.githubusercontent.com/621215/66483132-0b4d6300-ead7-11e9-96f8-3a0f4c1fd6ae.png)

**Comment by cwhenderson20** [comment]
I am also seeing this behavior!

**Comment by Gongreg** [comment]
Hey.
I've written to the maintainer of the said package a letter. While we are waiting for a patch, I will create a Pull Request for Storybook which will used patched version of rn-host-detect.

**Comment by shilman** [comment]
Good golly!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-alpha.38 containing PR #8683 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
