### ISSUE TITLE
Show Code Open by default

### ISSUE THREAD

**Issue by PaulieScanlon** [storybookjs/storybook#8356]
Hey team, CSF is great but it would be even better if it were possible to configure the 'stories'

Where you currently have the "Show code" could there be config to allow this to show code by default and for the button to say "Hide code"

I'd be happy to contribute if someone could point me in the right direction.

<img width="866" alt="Screenshot 2019-10-09 at 11 56 31" src="https://user-images.githubusercontent.com/1465706/66491048-0a520c80-eaaa-11e9-8d06-062b83b2f196.png">

**Comment by sinharaksh1t** [comment]
I'd like to help contribute too. We can work together if you want @PaulieScanlon :)
I would, however, wait for the author(s) to give us a green signal to work on it.

**Comment by sinharaksh1t** [comment]
Fantastic. Sounds like we're in an agreement then. I'll also keep an 👀 out for #8024. Once that gets merged, we'll start work on this. Thanks @PaulieScanlon and @shilman.

**Comment by sinharaksh1t** [comment]
So it looks like #8024 has been merged successfully?

**Comment by qooban** [comment]
I'd like to add live editor in our Storybook (as https://github.com/storybookjs/storybook/issues/6642 is not yet implemented) and if I can get more options for stories customization (especially that Show/Hide code part) from CSF it'll be great.

**Comment by shilman** [comment]
@qooban track this issue https://github.com/storybookjs/storybook/issues/7479

**Comment by signal-intrusion** [comment]
Any status update on this?

**Comment by shilman** [comment]
closing as dupe to #10430
