### ISSUE TITLE
Cannot overrule styles for markdown in addon-info

### ISSUE THREAD

**Issue by thany** [storybookjs/storybook#8357]
**Describe the bug**
It doesn't seem possible to overrule the styles for headers in markdown, that is injected via the addon `addon-info`.

**To Reproduce**
In my config file:
```javascript
import { withInfo } from '@storybook/addon-info';

addDecorator(
  withInfo({
    inline: true,
    header: false,
    style: {
      header: {
        h1: {
          fontSize: '25px'
        },
        h2: {
          fontSize: '20px'
        },
        h3: {
          fontSize: '18px'
        },
      }
    }
  })
);
```
I'm setting the overrules as per [this documentation](https://www.npmjs.com/package/@storybook/addon-info). It clearly says "Overrides styles of addon. The object should follow this shape", which is what I did.

After restarting storybook, the markdown styles are still the same (i.e. too huge and not in line with the other headers like "Story Source"). I can prove that the decorator works, by setting `header` to `true` and seeing the header appear after a restart, so that tells me all the scaffolding works and is not relevant to post here.

**Expected behavior**
Styles should be overruled if the documentation indicated I can overrule them.

**System:**
```
Environment Info:

  System:
    OS: Windows 10
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
  Binaries:
    Node: 10.16.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.329.0
```

**Additional context**
It might help to know that `@storybook/react` and `@storybook/addon-info` are both on 5.2.1. Forgive me for not using the latest version, but I'd rather only update if neccesary due to the complexity an update may bring.

**Comment by shilman** [comment]
`Addon-info` is being superceded by `addon-docs`, which fixes a bunch of bugs and is easier to maintain. Please give it a try! https://medium.com/storybookjs/storybook-docspage-e185bc3622bf
