### ISSUE TITLE
Tags in preview-head.html are also applied to the Docs tab

### ISSUE THREAD

**Issue by mlegait** [storybookjs/storybook#8360]
**Describe the bug**
I would like to apply some global style (reset.css to be precise) to the stories. But I don't want this style to affect the rest of Sorybook, and to be more precise, to affect the DocsPage.

I updated `config.js` in order to have each story in its own iframe in the DocsPage:
```javascript
addParameters({ docs: { inlineStories: false } });
```
I added the reset styles in `preview-head.html`.

But the reset styles are applied to each story's iframe AND to the DocsPage iframe 😕 

**To Reproduce**
Here is a very simple repo where you can reproduce it: https://github.com/mlegait/storybook-sandbox

The strong text in `DumbComponent` is reseted. This is what I want.
BUT the strong text in the description of the component is also reseted and I don't want to loose all the DocsPage formatting. 

**Expected behavior**
I would like to be able to add some specific css only to the stories without affecting the rest of Storybook.

**Screenshots**
![Capture d’écran 2019-10-09 à 21 59 21](https://user-images.githubusercontent.com/19664438/66516301-0392bc00-eae1-11e9-87d8-6bbef7692524.png)

**System:**
```
Environment Info:
  System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i5 CPU       M 520  @ 2.40GHz
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.17.3 - ~/.yarn/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 77.0.3865.90
    Firefox: 66.0.2
    Safari: 12.1.2
  npmPackages:
    @storybook/addon-actions: ^5.2.3 => 5.2.3 
    @storybook/addon-docs: ^5.2.3 => 5.2.3 
    @storybook/addon-links: ^5.2.3 => 5.2.3 
    @storybook/addons: ^5.2.3 => 5.2.3 
    @storybook/react: ^5.2.3 => 5.2.3
```
Thank you very much 😄

**Comment by shilman** [comment]
@mlegait unfortunately that's just a limitation of how docs is built in 5.x, since it renders in the preview. If it helps, canvas is rendered under `#root` and docs is rendered under `#docs-root`... so maybe you could scope your reset as a workaround. Not ideal, I know.

**Comment by mlegait** [comment]
OK, thank you for your answer 😄
