### ISSUE TITLE
DocPage: Prop table does not appear in the Docs panel if a component is exported wrapped in a React.memo function

### ISSUE THREAD

**Issue by tenjojeremy** [storybookjs/storybook#8361]
**Describe the bug**
Proptypes tabel does not appear in the Docs panel if a component is exported wrapped in a memo function.

For example
export default React.memo(Button)

**To Reproduce**
1. Create regular React component
2. Export component wrapped in React.memo function
3. Run storybook
4. Open Doc panel
5. The prop table does not appear.

**Expected behavior**
The prop table does appears when component exported wrapped in React.mem()

**Comment by shilman** [comment]
Related: #7933

**Comment by qooban** [comment]
In my case (component wrapped with `React.memo`) props documentation is not displayed automatically. I used this workaround https://github.com/storybookjs/storybook/issues/8435#issuecomment-547075209 (exporting wrapped component) and now props are displayed fine.

Still - I found another problem with wrapped components. I don't see DocGen description for the component (I added it on top of the component declaration in source code).

**Comment by patricklafrance** [comment]
@shilman 

This should be fixed by https://github.com/storybookjs/storybook/pull/8665

**Comment by AntonDolgov** [comment]
Similar problem with forwardRef. Code and "docs" tab:

**Without forwardRef:**

![Screenshot at Nov 08 17-08-21](https://user-images.githubusercontent.com/22680010/68482453-afe3d180-024a-11ea-8310-64b28e52b2ad.png)
![Screenshot at Nov 08 17-11-13](https://user-images.githubusercontent.com/22680010/68482509-ce49cd00-024a-11ea-8608-77a75d8cb532.png)

**With forwardRef:**

![Screenshot at Nov 08 17-13-15](https://user-images.githubusercontent.com/22680010/68482670-1d8ffd80-024b-11ea-9aee-923040a1287e.png)
![Screenshot at Nov 08 17-14-40](https://user-images.githubusercontent.com/22680010/68482763-4ca66f00-024b-11ea-9808-c39bb4b4d5f5.png)

**Version:**

![Screenshot at Nov 08 17-09-21](https://user-images.githubusercontent.com/22680010/68482402-9478c680-024a-11ea-8afa-0caf1aa5b766.png)

**Comment by shilman** [comment]
Unsatisfying workaround is to also export your pure component and use that for documentation purposes 😭

**Comment by Lughino** [comment]
This issue seems to be still unfixed but the stale bot closed it. Any updates?

**Comment by shilman** [comment]
Dupe to #9586
