### ISSUE TITLE
Unescaped error messages are injected into the DOM

### ISSUE THREAD

**Issue by hasparus** [storybookjs/storybook#8362]
**Describe the bug**
HTML/JSX tags in error messages are inserted into the DOM as HTML.

Error such as:
> `Invariant failed: You should not use <Link> outside a <Router>`

is displayed as:

> `Invariant failed: You should not use  outside a`

**To Reproduce**
1. Go to story that throws an error containing `<example>` text. (or create such story) 
2. See error -- `<example>` string is missing, but it's present as HTML element in the DOM.

**Expected behavior**
I suppose they should be displayed.
I think (no research though) that people usually treat error.message as plaintext and don't relaly throw HTML stylized errors.

**Screenshots**

🐛 Problem:
![storybook-html-1](https://user-images.githubusercontent.com/15332326/66519082-df39de00-eae6-11e9-93df-086e27c39076.png)

✨ Expected:
![storybook-html-2](https://user-images.githubusercontent.com/15332326/66519456-ae0ddd80-eae7-11e9-9913-5daec5390591.png)

**System:**

```
  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz
  Binaries:
    Node: 11.13.0 - D:\universal-tools\Node\node.EXE
    Yarn: 1.12.3 - D:\universal-tools\bin\yarn.CMD
    npm: 6.9.0 - D:\universal-tools\Node\npm.CMD
  Browsers:
    Edge: 44.18362.1.0
```

**Additional context**

https://github.com/storybookjs/storybook/pull/6972 changed how error messages are displayed. ANSI is being transformed into HTML for better error messages, but a message that already includes html-like tag is broken.

Here's the diff of that change: https://github.com/storybookjs/storybook/pull/6972/files#diff-a28189b3c6ad8b95af8afd9eb81561c5R38-R40

**Comment by shilman** [comment]
Pretty sure this was released in `5.3.0-alpha.3x`, tho for some reason it didn't show up in `CHANGELOG.md`
