### ISSUE TITLE
Unknown property: 'backgroundColor' at button.svelte

### ISSUE THREAD

**Issue by agusID** [storybookjs/storybook#8368]
**Describe the bug**
After I installed storybook at Svelte, I found this unknown CSS property (backgroundColor)
```bash
npx -p @storybook/cli sb init --type svelte
```
**To Reproduce**
1. Go to 'stories/button.svelte'
2. Scroll down to 'line 9'
3. See unknown CSS property

**Screenshots**
![Screen Shot 2019-10-10 at 14 42 08](https://user-images.githubusercontent.com/13955708/66549086-ba884980-eb6c-11e9-9e88-0a9994b8e1d4.png)
![code](https://user-images.githubusercontent.com/13955708/66549146-ddb2f900-eb6c-11e9-9df1-4abd8451d8c0.png)

**Comment by shilman** [comment]
Shiver me timbers!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-alpha.18 containing PR #8369 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Whoopee!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.4 containing PR #8369 that references this issue. Upgrade today to try it out!
