### ISSUE TITLE
Missing details on custom event using actions addon

### ISSUE THREAD

**Issue by hrobarikt** [storybookjs/storybook#8375]
Hi,
just wanted to ask if there is any way of displaying additional details from the custom event in the actions panel.
This is the event details I see when logged to the console:
<img width="482" alt="Screenshot 2019-10-10 at 17 18 05" src="https://user-images.githubusercontent.com/19704768/66582773-97689480-eb82-11e9-9daf-53617b6e5266.png">
This is the event details I seen in the actions panel:
<img width="309" alt="Screenshot 2019-10-10 at 17 18 33" src="https://user-images.githubusercontent.com/19704768/66582897-c2eb7f00-eb82-11e9-89ca-565840dacfa9.png">
As you can see there is only isTrusted property. I'm using the html version of storybook with a webcomponent written in stencilJS.

**Comment by ssbelle** [comment]
I am also having this issue and am very interested in suggestions and solutions. Thanks

**Comment by ssbelle** [comment]
@hrobarikt did you ever find a solution?

**Comment by hrobarikt** [comment]
> 
> 
> @hrobarikt did you ever find a solution?

As a quick workaround, you can try another addon @storybook/addon-console in which you can output the console log into the actions panel as well. But it is still not outputting the whole object and you need to specify the exact property that you wanna log (in my case event.detail.message).

**Comment by ssbelle** [comment]
> > @hrobarikt did you ever find a solution?
> 
> As a quick workaround, you can try another addon @storybook/addon-console in which you can output the console log into the actions panel as well. But it is still not outputting the whole object and you need to specify the exact property that you wanna log (in my case event.detail.message).

Thanks, yeah I had tried that addon a few days ago, and while it does show the event payload it shows each log beginning with 'console'. I have yet to find a way to replace the 'console' with something more verbose such as the name of the event. Did you manage to customize the console addon in that way @hrobarikt ?

**Comment by shilman** [comment]
I don't know. I don't maintain the actions addon. cc @ndelangen

**Comment by ndelangen** [comment]
Does this help?
https://storybookjs-next.now.sh/official-storybook/?path=/story/addons-actions--all-types
(click the button that says "SyntheticEvent")

code: https://github.com/storybookjs/storybook/blob/24ec9d3674fe8a2b151144803c1443c6d0a389ab/examples/official-storybook/stories/addon-actions.stories.js#L181-L182

**Comment by matteobarone** [comment]
Hello everyone, any news about this issue?

**Comment by ndelangen** [comment]
Is this problem specific to Stencil?

**Comment by matteobarone** [comment]
@ndelangen apparently not.
Seems related to native JS custom events, but also in my case I'm exporting web components through Stencil. I don't know if this is relevant.

implementation:
```
window.addEventListener('myCustomEvent', action('logMyEvent'));
```

output:
```
logMyEvent: (1) [CustomEvent]
  0: CustomEvent
    isTrusted: false
```

the console.log output is:
```
isTrusted: false
detail: {myDetail: 97815, ...}
type: "myCustomEvent"
target: my-tag.hydrated
currentTarget: null
eventPhase: 0
bubbles: true
cancelable: true
defaultPrevented: false
composed: true
timeStamp: 17609.72000000038
srcElement: my-tag.hydrated
returnValue: true
cancelBubble: false
path: (6) [...]
_constructor-name_: "CustomEvent"
```

Would be great if the addon could output also the other data.

Thanks for your time.

**Comment by ssbelle** [comment]
@matteobarone I created a work around for custom events, it is here https://www.npmjs.com/package/storybook-events-logger let me know if you need help implementing!

**Comment by calebdwilliams** [comment]
FWIW, this problem isn't only related to Stencil, I have a completely vanilla web component library and am experiencing this issue as well.

**Comment by ssbelle** [comment]
@calebdwilliams I was using web components as well and my npm package gives us the full data payload like so: 
```event_name  Payload(event.data.payload): >
                                                   otherdata: "whatever is passed in data payload"
                                                   other: "whatever else is in the data payload "```

https://www.npmjs.com/package/storybook-events-logger

**Comment by calebdwilliams** [comment]
@ssbelle, how are your events constructed? I'm just using `CustomEvent` and `event.detail`, with your package payload was null.

**Comment by ssbelle** [comment]
@calebdwilliams 
export function logEvent(e) {
  const id = uuid();
  const formattedEvent = {
    id,
    data: {
      name: e.type,
      payload: e.detail
    }
  };

hope that answers your question!

**Comment by matteobarone** [comment]
@ssbelle Yea it is working for me ;);) Thanks a lot!
If you could also add Typescript, would be perfect.
And maybe storybook will include it in one of their official addons.

**Comment by urish** [comment]
Seems like the same issue as #8544

**Comment by SunilSalve** [comment]
@ssbelle  - How to use https://www.npmjs.com/package/storybook-events-logger. can u share example

**Comment by AGrabovajFitA** [comment]
Here is a solution to this problem: https://stackoverflow.com/questions/13333683/javascript-customevent-detail-not-getting-passed

**Comment by dutscher** [comment]
https://github.com/storybookjs/storybook/issues/8544 see here for my solution. we should fix only telesync's JSON.parse for prototypes and everything is fine :)

cheers

**Comment by tfrijsewijk** [comment]
I don't think this has anything to do with Storybook, check out what happens when you try to object spread an CustomEvent:

```
{ ...new CustomEvent('test') }
```

![image](https://user-images.githubusercontent.com/9696261/115786484-2afa6280-a3c1-11eb-9719-cd4672ef133a.png)

Since I'm not interested in the actual CustomEvent object but only what's on `.detail`, I went with the following:

```
import { action } from '@storybook/addon-actions';

window.addEventListener('myCustomEvent', (e: CustomEvent) => action('checkedOverlaysChange')(e.detail));
```

**Comment by michaeljsalo** [comment]
We're still missing some details on custom events fired from Stencil web components.  On Storybook v6.3.13, Storybook Actions tab reports the 'event.target' property as undefined, for all events.  If I console log the same event, I can see the event.target successfully.

**Comment by tfrijsewijk** [comment]
Thinking aloud: The event comes from an element in an iframe. I wouldn't be surprised that the communication is done using serialization, which inadvertently means loss of data: you can't serialize a reference to an element.

![image](https://user-images.githubusercontent.com/9696261/199430128-86b70611-0e83-4fdb-89a5-c003da44bf1d.png)

**Comment by michaeljsalo** [comment]
Oddly enough we are seeing values for 'currentTarget' and 'srcElement' properties. It's just 'target' that's showing as undefined.
![Screen Shot 2022-11-02 at 12 12 37 PM](https://user-images.githubusercontent.com/1945279/199556684-1c4bfabf-e527-4650-b8cf-aca58a1a50bc.png)

**Comment by acapro** [comment]
I'm having this issue when upgrading from v8 to v9, i only see something like 

<img width="774" alt="Image" src="https://github.com/user-attachments/assets/c135a2c9-3865-4e20-98a1-42eb5031ac9e" />

In v8 it would log much more.
