### ISSUE TITLE
Can't init story book with an app created by create-react-app:3.2.0

### ISSUE THREAD

**Issue by darewreck54** [storybookjs/storybook#8380]
**Describe the bug**
create-react-app:3.2.0 has a bug where it will expect a "@babel/generator" that matches "^7.6.4".  If it's not there, it will ask the user to select a lower version.  This doesn't prevent created app to run, but the msg gets prompted every time you try to do a yarn install.

When you try to 'npx -p @storybook/cli sb init',  it will throw an error:
  
![image](https://user-images.githubusercontent.com/16171726/66616912-8706e880-eb87-11e9-99d5-e4544762ea02.png)

This prevents me from being able to init a storybook onto my project.

Filed issue: https://github.com/facebook/create-react-app/issues/7806

**To Reproduce**

This is specified in https://github.com/facebook/create-react-app/issues/7806

**Expected behavior**
Expect storybook to ask which version similar to what create-react-app does or have some way to workaround this if create-react-app is broken.

**Screenshots**
https://github.com/facebook/create-react-app/issues/7806

**System:**
Can't install it

**Additional context**
Even though this is probably a problem with create-react-app, it would be nice to have a way to workaround it since with create-react-app it just install the selected version and you can still run it.  But you can never do an init for storybook.

**Comment by shilman** [comment]
Try https://github.com/storybookjs/presets/tree/master/packages/preset-create-react-app, which I believe is fully compatible with recent versions of CRA
