### ISSUE TITLE
[addon-docs] Typo at svelte documentation

### ISSUE THREAD

**Issue by agusID** [storybookjs/storybook#8382]
**Describe the bug**
Typo at svelte documentation (guide-svelte)

**To Reproduce**
1. Go to [https://github.com/storybookjs/storybook/blob/master/docs/src/pages/guides/guide-svelte/index.md](https://github.com/storybookjs/storybook/blob/master/docs/src/pages/guides/guide-svelte/index.md)
2. Scroll down to 'Step 4'
3. See typo on the `Button` word that should be `MyButton`

**Screenshots**
<img width="741" alt="Screen Shot 2019-10-11 at 13 58 22" src="https://user-images.githubusercontent.com/13955708/66630850-3a76e800-ec2f-11e9-9526-0909d58cae24.png">

**Comment by shilman** [comment]
fixed!
