### ISSUE TITLE
Custom webpack.config.js not loaded with react-native

### ISSUE THREAD

**Issue by lindesvard** [storybookjs/storybook#8385]
**Describe the bug**
Storybook with @storybook/react-native-server does not pick up my custom webpack.config.js when running `yarn storybook` (start-storybook). This works when I'm doing it in web context but on react-native it will not load.

Am I doing something totally wrong here or is this even supported? Can't find any documentation that this do not work on react-native.

Repo: https://github.com/lindesvard/storybook-5-react-native

**To Reproduce**
1. `git clone git@github.com:lindesvard/storybook-5-react-native.git`
2. `yarn`
3. `yarn storybook` or `yarn storybook --debug-webpack`

**Expected behavior**
Should log the webpack config in the terminal and similar to `info => Custom webpack config loaded`

**System:**
```
  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.13.0 - ~/.nvm/versions/node/v10.15.3/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
  Browsers:
    Chrome: 77.0.3865.90
    Firefox: 69.0.1
    Safari: 13.0.2
  npmPackages:
    @storybook/addon-actions: ^5.2.3 => 5.2.3
    @storybook/addon-links: ^5.2.3 => 5.2.3
    @storybook/addons: ^5.2.3 => 5.2.3
    @storybook/react-native: ^5.2.3 => 5.2.3
    @storybook/react-native-server: ^5.2.3 => 5.2.3
```

**Comment by Gongreg** [comment]
Hi, seems like custom webpack config is not supported in react-native-server. @shilman , can you confirm? I don't see anything related to it in the package.

**Comment by wrezuh** [comment]
Hi @lindesvard React Native does not use webpack and subsequently won't look for your webpack config.

**Comment by lindesvard** [comment]
Hm okey. So to be able to customize webpack I guess I should use presets then?

**Comment by Gongreg** [comment]
@lindesvard , what exactly are you trying to achieve? :)

**Comment by lindesvard** [comment]
I need to run babel-loader for custom addons we have in our repo. So I can solve this pretty easy either way. I will close this ticket because the main question was if storybook native supported custom webpack.config.
