### ISSUE TITLE
Storyshots housekeeping for renamed and deleted snapshots

### ISSUE THREAD

**Issue by SQReder** [storybookjs/storybook#8386]
**Is your feature request related to a problem? Please describe.**
We use `addon-storyshots-puppeteer` for automatic regression testing and it doesn't do anything with obsolete snapshots. We need to have some kind of housekeeping for image snapshots of stories that have been renamed or deleted entirely. 

**Describe the solution you'd like**
The simplest way is to check for snapshots that cannot be matched with story and suggest to remove it.
If story was just renamed - need nothing to do, as new snapshot will be created and git will recognize it as file move.

**Are you able to assist bring the feature to reality?**
yes, I can...

**Comment by mudrila** [comment]
Such a great feature, if you need some help on that - let me know, I will try to support you

**Comment by shilman** [comment]
Related https://github.com/storybookjs/storybook/pull/8889

**Comment by shilman** [comment]
@SQReder did you want to take a shot at this?

**Comment by SQReder** [comment]
I'll check it after january 9th. Does it already published in npm?

чт, 2 янв. 2020 г., 4:17 Michael Shilman <notifications@github.com>:

**Comment by shilman** [comment]
Yes #8889 is published to NPM

**Comment by SQReder** [comment]
It seems to does not work in 5.2.8

**Comment by shilman** [comment]
@SQReder that's because it's not in 5.2.8. It's in 5.3.x.

**Comment by SQReder** [comment]
Oh, well, my bad! I'll check it out ASAP 😖

**Comment by SQReder** [comment]
Checked it again and, I suppose that #8889 does not cover my case.
I created a story, snapshotted it, then remove the story, run `jest -u` again. The snapshot wasn't removed.

**Comment by shilman** [comment]
@Hypnosphi can you help out @SQReder ?

**Comment by SQReder** [comment]
To be specific, all storybook packages are version ~5.3.3

**Comment by Hypnosphi** [comment]
@SQReder can you please share your `storyshots.tests.js`? Or, even better, create a GitHub repo with minimal reproduction of your issue?

**Comment by SQReder** [comment]
I use image snapshots from `addon-storyshots-puppeteer` package, so I think this is the core issue 😮

```js
initStoryshots({
  suite: "Visual Regression",
  storyNameRegex: /^((?!(in action$|dynamic props)).)*$/i,
  test: imageSnapshot({
    storybookUrl: process.env.STORYBOOK_LIVE ? "http://localhost:9009" : `file:///${__dirname}/storybook-static`,
    getGotoOptions,
    chromeExecutablePath,
    beforeScreenshot,
    customizePage,
    getMatchOptions,
  }),
});
```

**Comment by Hypnosphi** [comment]
Looks like https://github.com/americanexpress/jest-image-snapshot/issues/59 to me
