### ISSUE TITLE
[addon-docs] Display HTML code for react storybooks

### ISSUE THREAD

**Issue by inspiratweb** [storybookjs/storybook#8387]
Can we have a block like in the current addon-docs to display also the resulting plain html markup?
It would be very useful for design systems

**Describe the solution you'd like**
Using the `text.stories` given in the installation example we get the react code (in my case) like
```
() => <Button onClick={action('clicked')}>Hello Button</Button>
```

Is there a way to get the plain HTML from that code (not using addon-info)?
```
<button>Hello Button</button>
```

**Comment by shilman** [comment]
Closing as dupe to https://github.com/storybookjs/storybook/issues/7479
