### ISSUE TITLE
Reference Error: It is not defined

### ISSUE THREAD

**Issue by bfeeley** [storybookjs/storybook#8390]
**Description**
When running Storybook, it throws the error: "Reference error: It is not defined".

**To Reproduce**
1. Run SB using `yarn storybook`

**Describe the bug**
Storybook should launch with no errors. It seems to choke on describe, it, etc.

**Screenshots**
![Screen Shot 2019-10-11 at 9 51 28 AM](https://user-images.githubusercontent.com/1482340/66657252-82851300-ec0d-11e9-9e4e-1928aef31599.png)

![Screen Shot 2019-10-11 at 2 13 01 PM](https://user-images.githubusercontent.com/1482340/66674643-5d0a0080-ec31-11e9-9350-fe4c71e0b30f.png)

**Code snippets**
*config.js*

```
import React from 'react';
import { addDecorator, configure } from '@storybook/react';
import { withTests } from '@storybook/addon-jest';
import results from '../.jest-test-results.json';
import requireContext from 'require-context.macro';

addDecorator(
    withTests({
        results,
    })
);

const req = requireContext('../src', true, /\.stories\.tsx?$/);

function loadStories() {
  req.keys().forEach(filename => req(filename));
}

configure(loadStories, module);
```

*webpack.config.js*

```
module.exports = ({ config }) => {
    config.module.rules.push({
      test: /\.(ts|tsx)$/,
      use: [
        {
          loader: require.resolve('awesome-typescript-loader'),
        },
        {
          loader: require.resolve('react-docgen-typescript-loader'),
        },
      ],
    });
    config.resolve.extensions.push('.ts', '.tsx');
    return config;
  };
```

*tsconfig.json*

```
{
  "rootDir": "src",
  "compilerOptions": {
    "baseUrl": "src",
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "preserve",
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false
  },
  "include": [
    "src/**/*"
  ],
  "exclude": [
    "node_modules",
    "build",
    "scripts",
  ]
}
```

**Additional context**
App built with create react app.
"@storybook/addon-actions": "^5.2.3",
"@storybook/addon-info": "^5.2.3",
"@storybook/addon-jest": "^5.2.3",
"@storybook/addon-knobs": "^5.2.3",
"@storybook/addon-links": "^5.2.3",
"@storybook/addon-storyshots": "^5.2.3",
"@storybook/addon-storysource": "^5.2.3",
"@storybook/addon-viewport": "^5.2.3",
"@storybook/addons": "^5.2.3",
"@storybook/preset-create-react-app": "^1.0.0-beta.3",
"@storybook/react": "^5.2.3",
"react": "^16.8.6",
"react-scripts": "3.2.0",
"typescript": "3.6.2"

**Comment by shilman** [comment]
@bfeeley do you use describe/it in your stories?

**Comment by bfeeley** [comment]
@shilman No .. just in the *.test.tsx. Not entirely sure why SB cares about the test files. I don't have them included in any of the build configs.

**Comment by bfeeley** [comment]
The thing is really perplexing is i have an almost exact copy of the app in another branch and it works fine.

**Comment by bfeeley** [comment]
Ok .. I have half figured this out. Have the cause but not the reason. So I am creating mock data for my tests and stories. The mock data is defined in the test file as a `const`, and imported from there into the story: The minute i add the import in the story to get the mock from the test file is when this error shows up. Remove the import, and it goes away.

**Comment by bfeeley** [comment]
*.test.tsx
```
export const myMockData = {
    example: observable.box('foo'),
};
```

*.story.tsx
```
...
import { myMockData } from './*.test.tsx';

storiesOf('Components/My Component', module)
    .addDecorator(withKnobs)
    .add(
        'Default', () => {
            return (
                <MyComponent store={myMockData} />
            );
        },
    );
```

**Comment by shilman** [comment]
`describe` is provided by `jest` when you're testing, but storybook doesn't provide it. you could try providing a stub in your `config.js`, something like `window.describe = () => {}`? Or create your data in a third file. Or, if you're using [component story format](https://medium.com/storybookjs/component-story-format-66f4c32366df), you can define your data in your stories and import it into your jest tests.

**Comment by bfeeley** [comment]
@shilman Yeah that's actually the route i went. Just set up the stubbed data in the story instead of pulling it from the test file. Seems to be working now. I would have thought having jest installed as a dev dependency would have covered the issue, but didn't seem to help. Anyway ...  I'll close this since there's a workaround. Thanks!
