### ISSUE TITLE
MDX ability to loop (map) <Preview> and <Story>

### ISSUE THREAD

**Issue by vinceumo** [storybookjs/storybook#8392]
Hi, Thanks for this project, I love using it.

I'm using MDX, I would like to be able to generate multiple stories using an array. Not sure if it is possible. 

I tries something like that with `@storybook/react v5.2.3`:

```mdx
import { Meta, Story, Preview } from "@storybook/addon-docs/blocks";

<Meta title="UI" />

# My story

<div>
  {[0, 1, 2].map(el=>(
    <Preview>
      <Story name={`el${el}`}>
          <div>{el}</div>
        </Story>
    </Preview>
  ))}
</div>
```

I have no error but the output is not as expected:

![Capture](https://user-images.githubusercontent.com/21067002/66681633-03262c80-ec6b-11e9-99d2-87962e916842.PNG)

Thanks a lot

**Comment by shilman** [comment]
@vinceumo Unfortunately I don't see this happening any time soon. Those story definitions get automatically compiled to named exports when the file is loaded, so they need to be static at this time. Making them dynamic is tricky, and a low priority unless somebody from the community wants to take it on.

**Comment by Aaron-Pool** [comment]
For simple and deterministic cases, you might consider using [this](https://github.com/kentcdodds/codegen.macro)

**Comment by lukaskoeller** [comment]
Are there any updates on this one? Would be highly interested in this feature as well.

Especially when I think of Design Tokens (Colors, Icons, etc.) and using `<ColorPalette>` and `<ColorItem>` provided by `addon-docs`. It would enable me to loop through all colors (key, values) provided by a json file that is part of Style Dictionarie's build. No more manual maintenance.

**Comment by shilman** [comment]
@lukaskoeller You can do that WITHIN a Story or JSX element in the page, no problem. The only limitation is you can't dynamically generate stories. But it doesn't sound like you need that for your use case.

**Comment by lukaskoeller** [comment]
Does this also works for `for` loops? When I try to use it I get an error, saying:
```
Module build failed (from ./node_modules/@mdx-js/loader/index.js):
SyntaxError: unknown: Unexpected token (23:6)
```

This appears when I'm trying to use `for...of` loop. Though, it doesn't appear when I use `map`.
```js
for (let token of Object.entries(tokens)) {
      console.log(key, value);
}
```

**Comment by vinceumo** [comment]
Hi @lukaskoeller, in JSX you should use [.map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map). 

https://reactjs.org/docs/lists-and-keys.html

Assuming you have an object you could have something like that:

```mdx
<Preview>
  <Story name="My Story">
     {Object.keys(tokens).map(key => (
       <p>My key is {key} and my value is {tokens[key]}</p>
      )}
  </Story>
</Preview>
```

**Comment by lukaskoeller** [comment]
Thank you @shilman and @vinceumo very much for your help. For anybody interested and feedback for improvements, I ended up using this code:

```jsx
<ColorPalette>
{
  Object.entries(tokens.color.brand).map((token, i) => {
    return(
      <ColorItem
        key={i}
        title={`${token[0]} color`}
        subtitle={ token[1].base.name.replace('Base', '[name]') }
        colors={
          Object.entries(token[1]).map((value) => {
            return value[1].value
          })
        }
      />
    )
  })
}
</ColorPalette>
```
