### ISSUE TITLE
More inclusive language in docs

### ISSUE THREAD

**Issue by carolstran** [storybookjs/storybook#8394]
:wave: Sorry I know I'm ignoring all of your well-thought out templates, but I wasn't sure where this would land! Here me out...

I noticed that there are many instances of the word "simply" in your documentation. Unfortunately, words like this can make people feel frustrated and isolated while reading (myself included, hence the issue) - especially if they are facing issues.

If it's alright with your team, I'd like to take a shot at updating the content to make it more inclusive by removing instances of "simply", "easy", "just", etc. I used Storybook _all_ the time at my last job, so I'm happy to help 😊  

Also if you're interested or want more information on this topic, I'd highly recommend watching Jim Fisher's [Don't Say Simply](https://www.youtube.com/watch?v=gsT2BBWBVmM) talk from Write the Docs Prague 2018 ✍️ 🤓 

Thank you for the work you do and please let me know if you need more details!

**Comment by shilman** [comment]
@carolstran we'd absolutely welcome those updates! 🙏

**Comment by carolstran** [comment]
Yay! I'm on it 🚀
