### ISSUE TITLE
Storybook with React Native, rendering react-native-linear-gradient gives error `_reactNative.requireNativeComponent) is not a function`

### ISSUE THREAD

**Issue by marcoautiero** [storybookjs/storybook#8398]
**Describe the bug**
In a React Native app, launching `storybook-web` with `npm run storybook-web`, trying to get the story of a component using `react-native-linear-gradient` i get the error `(0 , _reactNative.requireNativeComponent) is not a function`

![image](https://user-images.githubusercontent.com/2686869/66702811-f86fa400-ed0b-11e9-8e65-85679b0af1dc.png)

**To Reproduce**
1. Create e basic react native app
2. configure storybook for react native
3. install react-native-linear-gradient `npm i react-native-linear-gradient`
4. include `<LinearGradient>` in the app rendering 
5. launch storybook-web `npm run storybook-web`

**Code snippets**
my webpack config in storybook-web is the following
```
const path = require("path");

module.exports = async ({ config }) => {
  config.module.rules.push({
    test: /\.js$/,
    include: [
      /node_modules\/react-native-app-intro-slider/
    ],
    use: {
      loader: 'babel-loader'
    }}
  });

  config.resolve.extensions = [".web.js", ".js", ".json", ".web.jsx", ".jsx"];

  config.resolve.alias = {
    ...config.resolve.alias,
    "react-native": "react-native-web",
    "@storybook/react-native": "@storybook/react",
  };

  return config;
};

```

**Comment by neiker** [comment]
Same issue with `styleguidist` (wich use storybook internaly) and `react-native-svg`. 

EDIT: Solved using:
https://github.com/bakerface/react-native-svg-web

**Comment by neiker** [comment]
@marcoautiero You should add a shim for`react-native-linear-gradient`. 

I solved my problem adding an alias for `react-native-svg`.

`webpack.config.js`: 
```js
resolve: {
      alias: {
        'react-native': 'react-native-web',
        'react-native-svg': path.resolve(__dirname, 'react-native-svg.js'),
      },
      extensions: ['.web.js', '.js', '.ts', '.web.ts', '.tsx', '.web.tsx'],
    },
```

`react-native-svg.js`: 
```js
export const Circle = 'circle';
export const ClipPath = 'clipPath';
export const Defs = 'defs';
export const Ellipse = 'ellipse';
export const G = 'g';
export const Image = 'image';
export const Line = 'line';
export const LinearGradient = 'linearGradient';
export const Path = 'path';
export const Polygon = 'polygon';
export const Polyline = 'polyline';
export const RadialGradient = 'radialGradient';
export const Rect = 'rect';
export const Stop = 'stop';
export const Svg = 'svg';
export const Symbol = 'symbol';
export const Text = 'text';
export const TextPath = 'textPath';
export const TSpan = 'tspan';
export const Use = 'use';
export const Mask = 'mask';

export default Svg;
```
