### ISSUE TITLE
Code preview in addon-docs only works for arrow functions in CSF

### ISSUE THREAD

**Issue by cycleseven** [storybookjs/storybook#8401]
**Describe the bug**

The docs panel doesn't seem to display a code preview when using a regular old `function` in Component Story Format (CSF). Instead, "No code available" is displayed. Looks like it only works for arrow functions.

Not a huge deal of course, can work around it by just using arrows instead :)

**To Reproduce**

Here's a new story in a [cra-kitchen-sink fork](https://github.com/cycleseven/storybook-code-preview-bug/blob/next/examples/cra-kitchen-sink/src/stories/code-preview.stories.js) that demonstrates the issue.

**Expected behavior**

I'd have expected arrows and regular functions to be interchangeable in CSF.

**Screenshots**

<img width="1440" alt="Screenshot 2019-10-12 at 20 37 04" src="https://user-images.githubusercontent.com/2000549/66706871-7b0a5a80-ed30-11e9-8e60-66131828f750.png">

**Code snippets**

```
import { action } from '@storybook/addon-actions';
import { Button } from '@storybook/react/demo';
import React from 'react';

/* Code preview works */
export const usingArrowFunction = () => (
  <Button onClick={action('clicked')}>
    <span role="img" aria-label="yolo">
      😀 😎 👍 💯
    </span>
  </Button>
);

/* Code preview works */
export const alsoUsingArrowFunction = () => {
  return (
    <Button onClick={action('clicked')}>
      <span role="img" aria-label="yolo">
        😀 😎 👍 💯
      </span>
    </Button>
  );
};

/* No code preview for this though. */
export function regularOldFunction() {
  return (
    <Button onClick={action('clicked')}>
      <span role="img" aria-label="yolo">
        😀 😎 👍 💯
      </span>
    </Button>
  );
}

export default {
  title: 'Code preview',
  component: Button,
};
```

**System:**

```
Environment Info:

  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
  Binaries:
    Node: 12.11.1 - ~/n/bin/node
    Yarn: 1.19.0 - ~/.yarn/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 77.0.3865.90
    Firefox: 69.0.3
    Safari: 13.0.2
```

**Comment by shilman** [comment]
Huzzah!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-beta.20 containing PR #9092 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.
