### ISSUE TITLE
Presets-Docs: Advanced configuration compilation errors

### ISSUE THREAD

**Issue by jerriclynsjohn** [storybookjs/storybook#8420]
**Describe the bug**
Following the steps for advanced preset configuration in the docs leads to error in compilation. Please look at the steps to reproduce for the solution to fix it.

**To Reproduce**
1. Add the `my-preset.js` file in the storybook folder with the necessary configs as mentioned in docs
```javascript
export async function webpack(config, options) {
    return config;
}

export async function addon(entry = []) {
    return entry;
}
```
2. Add the `presets.js` file in the storybook folder with the necessary configs as mentioned in docs
```javascript
const path = require('path');
module.exports = [path.resolve('./my-preset')];
```
3. Compile and you'll see error `Failed to load preset: "<ProjectFolder>\\my-preset"` while it should have been `<ProjectFolder>\\.storybook\\my-preset`
4. Change `presets.js` into :
```javascript
const path = require('path');
module.exports = [path.resolve('./.storybook/my-preset')];
```
5. Compile and you'll see error:
```bash
WARN   Failed to load preset: "<project-folder>\\.storybook\\my-preset"
ERR! <project-folder>\.storybook\my-preset.js:1
ERR! export async function webpack(config, options) {
ERR! ^^^^^^
ERR!
ERR! SyntaxError: Unexpected token export
```
6. Change `my-preset.js` into:
```javascript
async function webpack(config, options) {
    return config;
}
async function addons(entry = []) {
    // return [...entry, require.resolve('@storybook/addon-storysource/register')];
    return entry;
}
module.exports = { webpack, addons };
```
7. Compile and run error free (So yeah that's the solution)

**Expected behavior**
If we follow the instructions provided in the documentation then we should get an error free compilation

**Comment by jerriclynsjohn** [comment]
@shilman I'm so loving advanced preset configuration right now!

**Comment by shilman** [comment]
@jerriclynsjohn great, thanks for the doc fix!!! 🙏
