### ISSUE TITLE
Knobs addon - 'Copy' button does not encode URL specific chars in query params

### ISSUE THREAD

**Issue by smakhl** [storybookjs/storybook#8422]
**Describe the bug**
When you use a 'Copy' button in knobs addon, if any of the input values contain symbols like `#`, `&`, `?` , it is added in the URL 'as is' and breaks it.

**To Reproduce**
1. Go to https://storybookjs.now.sh/html-kitchen-sink/?path=/story/addons-knobs--simple
1. Type `Storybook & knobs` in Name text knob, 
1. Click 'Copy' 
1. Result URL is `https://storybookjs.now.sh/html-kitchen-sink/?path=/story/addons-knobs--simple&knob-Name=Storybook & knobs&knob-Age=44`. 
1. The URL is broken, because the `& knobs` part becomes a separate query param.

**Expected behavior**
To encode the URL specific chars.

In git blame I see that encoding is explicitly disabled, but could not find the reason why:
https://github.com/storybookjs/storybook/blob/master/addons/knobs/src/components/Panel.tsx#L170

IMO, the solutions can be:
1) To turn encoding back on, if there's no particular reason to keep it off.
2) To manually replace URL specific chars like `param.replace(/#/g, '%23')`

Let me know, if you'd like me to submit a PR for it.
Thanks!

**Comment by andrew-boyd** [comment]
I'm also running into this issue. I'm unable to create various example links of different component configurations because the url that is generated fails to load with the message "Unexpected end of JSON input".

Would be great to have URL encoding of share links.
