### ISSUE TITLE
@storybook/react-native invalid style prop used on TextInput

### ISSUE THREAD

**Issue by luke-john** [storybookjs/storybook#8438]
**Describe the bug**

Invalid style prop being used by TextInput, generating react-native error on @storybook/react-native@5.3.0-alpha.20

It looks like this was introduced when converting from style template string to style objects in the following pr.

https://github.com/storybookjs/storybook/commit/0f384bce072c7897926d98d43340581a6292ecb7#diff-811d44b672d9d337f90c5158a9b2bd69R21

As the style was in the template string though, I'd assume emotion did some filtering which was preventing this error in previous versions

Downgrading to @storybook/react-native@5.3.0-alpha.19 "resolved" this error for us.

**To Reproduce**
1. Install @storybook/react-native@5.3.0-alpha.20
2. Run storybook on simulator
3. See error

**Expected behavior**
No errors

**Comment by Gongreg** [comment]
https://github.com/storybookjs/storybook/pull/8480 Fixes the issue :)
