### ISSUE TITLE
Error source-loader using typescript parser with CSF

### ISSUE THREAD

**Issue by apanizo** [storybookjs/storybook#8439]
**Describe the bug**
Using TS with CSF and source-loader (in both ways, directly using addon-storysource or using addon-docs), specifying **parser: 'typescript'** fails.

**To Reproduce**
1. Fork https://github.com/apanizo/cra-sb
2. run `yarn install && yarn storybook`

**Expected behavior**
Works and show the source code of the stories

**Screenshots**
<img width="1426" alt="Screenshot 2019-10-14 at 17 52 06" src="https://user-images.githubusercontent.com/4266059/66765352-0a884880-eeac-11e9-9546-394300aae3e0.png">

**Code snippets**
```
import React from "react";
import { action } from "@storybook/addon-actions";
import { Button } from "@storybook/react/demo";

export default {
  title: "Button"
  // parameters: { foo: 'bar'}, <--- You can uncomment this for different behaviors
  // decorators: [...] <----------- This as well
};

export const text = () => (
  <Button onClick={action("clicked")}>Hello Button</Button>
);

export const emoji = () => (
  <Button onClick={action("clicked")}>
    <span role="img" aria-label="so cool">
      😀 😎 👍 💯
    </span>
  </Button>
);
```

**Comment by apanizo** [comment]
Note I have created a Pull request for fixing it 💪. @shilman I would appreciate if you can provide me some feedback.

Thanks!

**Comment by shilman** [comment]
Thanks @apanizo! I'll take a look tomorrow--very excited to see this fixed 💯
