### ISSUE TITLE
Svelte named slot support

### ISSUE THREAD

**Issue by jerriclynsjohn** [storybookjs/storybook#8443]
**Describe the bug**
As mentioned in the docs if we use slots in a component then stories have to be created using another "view" component. This works perfectly for normal slots, but doesn't work for named slots. 

**To Reproduce**
1. Create a base svelte component with named slot `default.svelte`:
```html
<slot name="one">
    <p> This is shown from default (1) </p>
</slot>
<br>
<slot name="two">
    <p> This is shown from default (2) </p>
</slot>
```
2. Create a view component `view.svelte`:
```html
<script>
import Default from './default.svelte';
</script>
<Default>
       <div name="one">This is shown from the view (1)</div>
       <div name="two">This is shown from the view (2)</div>
</Default>
```
3. Create a story `default.stories,js`
```js
import View from './view.svelte';

export default { title: 'Named Slot View' };

export const namedSlot = () => ({
    Component: View ,
});
```
4. The output is:
```
This is shown from the default (1)
This is shown from the default (2)
```

**Expected behavior**
Ideally since the slot is called in a view this should work, ideally. The output of the above example should be
```
This is shown from the view (1)
This is shown from the view (2)
```

**Comment by jerriclynsjohn** [comment]
This was a basic error from my end, in the view component if we use `slot` instead of `name` the problem is solved! which is basic svelte syntax which i missed, my bad!

**Comment by northkode** [comment]
![image](https://user-images.githubusercontent.com/6988083/74474326-80a0ba00-4e62-11ea-8874-ca4ab2b40aa0.png)
Named slots dont seem to work any more
