### ISSUE TITLE
Advice - best way to kickstart react/typescript storybook

### ISSUE THREAD

**Issue by rezaabedian** [storybookjs/storybook#8446]
Hi team,

We are using storybook 5.1 and want to upgrade to storybook 5.2 to benefit from Docs mode and future MDX support.

What is the recommended, easiest and fool proof way to get up and running with a new storybook with react and typescript support? This could be either utilizing create-react-app, or full control mode, ts-loader or babel. 

Thanks

**Comment by shilman** [comment]
Here's a walkthrough: https://gist.github.com/shilman/bc9cbedb2a7efb5ec6710337cbd20c0c

**Comment by rezaabedian** [comment]
Thank you! 🙏
