### ISSUE TITLE
Issue loading CSS styles inside MDX

### ISSUE THREAD

**Issue by oscardavidrm** [storybookjs/storybook#8447]
**Describe the bug**
I am really not sure what's going on, but the thing is that I am building some *.stores.mdx files to document a project and some of my CSS classes are not rendering. The weird thing is that some of them are correctly rendering, and some of them are not. 

**To Reproduce**

**Expected behavior**
I would expect to have all my CSS styles properly rendered.

**Screenshots**
FOLDER STRUCTURE:
![image](https://user-images.githubusercontent.com/40501486/66944428-c1063d80-f012-11e9-8f43-7694087bbf1e.png)

Inside index.css I am importing all my CSS files to then include them into the stories:
![image](https://user-images.githubusercontent.com/40501486/66944465-d7ac9480-f012-11e9-9e55-8a81448885f6.png)

index.stories.js (which is the one that enables classes for the stories):
![image](https://user-images.githubusercontent.com/40501486/66944515-f14ddc00-f012-11e9-97e9-99e4b145ca1f.png)

This is a peek inside my button.stories.mdx, in where I am using SOME of the classes that are supposedly imported from index.stories.js (here they work like a charm):
![image](https://user-images.githubusercontent.com/40501486/66944577-0dea1400-f013-11e9-96ee-f3abe3554b3e.png)

But in here, inside card.stories.mdx, suddenly the classes are not working, they are just not rendering:
![image](https://user-images.githubusercontent.com/40501486/66944633-2eb26980-f013-11e9-844e-3e8eae4e1fb3.png)

I am importing all CSS files exactly the same, and button.css works and card.css won't. I am not pretty sure what is going on. I already tried mashing everything together inside button.css file to see if there was an issue with card.css file, but it still doesn't work.

Any ideas? Would really appreciate some help.

**Comment by shilman** [comment]
Did you try putting your examples inside `<Story>` blocks?
