### ISSUE TITLE
Two stories, same templates, different props - props from the second story are passed to the instances of the components in the first story on story change

### ISSUE THREAD

**Issue by sharikovvladislav** [storybookjs/storybook#8456]
**Describe the bug**

**To Reproduce**
1 Clone the repo https://github.com/sharikovvladislav/angular-with-storybook-props-problem to some <directory> (`git clone git@github.com:sharikovvladislav/angular-with-storybook-props-problem.git`)
2 Go to the <directory> (`cd <directory>`)
3 Install deps via npm (`npm i`)
4 Run storybook (`npm run storybook`) and wait for browser to open
5 Open the console
6 Open first story Test -> TestX (or reload this story if you have it opened, so you will see something in console). You will see the following:
```
16:55:20.331 with-control-value-accessor.component.ts:20 >> constructor 4552a685-7c83-48d5-972a-a1628faf01e1
16:55:20.335 with-control-value-accessor.component.ts:32 >> writeValue value is null 4552a685-7c83-48d5-972a-a1628faf01e1
16:55:20.339 with-control-value-accessor.component.ts:32 >> writeValue value is x 4552a685-7c83-48d5-972a-a1628faf01e1
```
Remember the `uuid` value in constructor.
7 Now go to the second story Test -> TestY
8 You will see in console this messages:

**Actual result**

```
with-control-value-accessor.component.ts:32 >> writeValue value is y 4552a685-7c83-48d5-972a-a1628faf01e1
16:56:18.273 with-control-value-accessor.component.ts:24 >> ngOnDestroy12323451 4552a685-7c83-48d5-972a-a1628faf01e1
16:56:18.305 with-control-value-accessor.component.ts:20 >> constructor d409c67b-0e0e-4de5-bc30-c22d25df99ff
16:56:18.306 with-control-value-accessor.component.ts:32 >> writeValue value is null d409c67b-0e0e-4de5-bc30-c22d25df99ff
16:56:18.307 with-control-value-accessor.component.ts:32 >> writeValue value is y d409c67b-0e0e-4de5-bc30-c22d25df99ff
```

Take a look at `writeValue` call at first line with same uuid as in constructor above. Also, check the value. This means that when I clicked to the second story `writeValue` of the component created in **first** story was called with the value passed as props to the second story. Woooot?

**Explanation of the code in the repo**
- there is simple component WithControlValueAccessorComponent. It implements ControlValueAccessor (so `ngModel` or `formControl` directives are available) https://github.com/sharikovvladislav/angular-with-storybook-props-problem/blob/master/src/app/with-control-value-accessor/with-control-value-accessor.component.ts#L13
- there is instanceId in each component instance and there are lifecycle hooks which show you what happens in console
- there are 2 very simple stories. Only one difference is that in TestX `x` value is passed as input to the component and in TestY `y` is passed https://github.com/sharikovvladislav/angular-with-storybook-props-problem/blob/master/src/stories/with-control-value-accessoro.stories.ts

**Expected behavior**
When I go to the second story I expect: first (testX, current) story component destroy without calling writeValue with value from the second story

**System:**
```
 ~/tmp/try-sb/without-ivy-with-latest-storybook   master  npx -p @storybook/cli@next sb info

Environment Info:

  System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 77.0.3865.120
    Safari: 13.0.2
  npmPackages:
    @storybook/addon-actions: ^5.2.4 => 5.2.4 
    @storybook/addon-links: ^5.2.4 => 5.2.4 
    @storybook/addon-notes: ^5.2.4 => 5.2.4 
    @storybook/addons: ^5.2.4 => 5.2.4 
    @storybook/angular: ^5.2.4 => 5.2.4 
  npmGlobalPackages:
    @storybook/cli: 5.2.3
```

**Additional context**
Storybook version: 
```
sb --version
5.2.3
```

Installed storybook:
```
// from package-lock.json
// ...
    "@storybook/angular": {
      "version": "5.2.4",
// ...
```

Angular version:
```
Angular CLI: 8.3.10
Node: 10.16.0
OS: darwin x64
Angular: 8.2.11
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.10
@angular-devkit/build-angular     0.803.10
@angular-devkit/build-optimizer   0.803.10
@angular-devkit/build-webpack     0.803.10
@angular-devkit/core              8.3.10
@angular-devkit/schematics        8.3.10
@angular/cli                      8.3.10
@ngtools/webpack                  8.3.10
@schematics/angular               8.3.10
@schematics/update                0.803.10
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2
```

**Comment by sharikovvladislav** [comment]
The problem for us: now in some stories we get exceptions since writeValue of some components are called with props from sibling stories.

**Comment by sharikovvladislav** [comment]
Do you think it is a problem or not? Can you accept or reject it please.

**Comment by shilman** [comment]
cc @kroeder

**Comment by sharikovvladislav** [comment]
Do you confirm this or not?
