### ISSUE TITLE
5.1.10 -> 5.2.4 - parameters inside theme object?

### ISSUE THREAD

**Issue by MMT-LD** [storybookjs/storybook#8458]
**Describe the bug**
weirdly i'm getting "parameters" key inside my theme object in some levels? None of this happened in 5.1.10. Trying to figure out what has changed to make this happen.

I also now see this in my console...

```
index.js:42 Loader function passed to 'configure' should return void or an array of module exports that all contain a 'default' export. Received: 
```

**To Reproduce**
I output my theme in the console, using console.log to see it is clearly visible? (see below image) My app is wrapped in my theme object at a top level in config.js like so...

This subsequently breaks my view because i loop over the keys in some story file and it cant find the key i'm looking for as what i'm matching it to does not exist because "parameters' is not something i recognise it has been injected. So to fix it i have to do something like:

```
theme: {
      // FIXME: - Storybook 5.2.4 issue with weirdly adding params into my icons object??
      icons: { parameters, ...restIcons },
    },
```

then map on restIcons instead to remove parameters.

below is my config where i wrap the stories in the theme.

```
import React, { Fragment } from 'react';
import { configure, setAddon, addDecorator } from '@storybook/react';
import { withOptions } from '@storybook/addon-options';
import JSXAddon from 'storybook-addon-jsx';
import { WithGlobalTheme } from '../src/components/HOC';

setAddon(JSXAddon);

addDecorator(story => (
  <Fragment>
    <WithGlobalTheme>
      <div>  
          {story()}
      </div>
    </WithGlobalTheme>
  </Fragment>
));

const loadStories = () => require(`glob-loader!./stories.pattern`);

withOptions({
  name: 'Design System Storybook',
  url: '#',
  goFullScreen: false,
  showStoriesPanel: true,
  showAddonPanel: true,
  showSearchBox: false,
  addonPanelInRight: false,
  sortStoriesByKind: false,
});

configure(loadStories, module);
```

**Expected behavior**
This not to appear in my object...

**Screenshots**
<img width="664" alt="Screenshot 2019-10-17 at 15 17 47" src="https://user-images.githubusercontent.com/28092872/67018189-c63ab980-f0f2-11e9-8e28-1cdc53e69594.png">

**Comment by shilman** [comment]
Looks like it's running `source-loader` on non-story files. How's that configured?

**Comment by MMT-LD** [comment]
> Looks like it's running `source-loader` on non-story files. How's that configured? (Or `addon-storysource` if you never configured `source-loader`)

Yeah that'll be it. Thanks for the help. It was configured to look at all js files and not just stories. Once i changed the custom webpack it was all working.

**Comment by shilman** [comment]
Great 🚀
