### ISSUE TITLE
Navigating to a story always start an animation from the top of the page

### ISSUE THREAD

**Issue by patricklafrance** [storybookjs/storybook#8466]
**Describe the bug**
With the new docs addon, navigating to a story by clicking on a link from the menu always animate from the top of the page. This is quite annoying when you have a long page.

Is it possible to have a config to disable the animation and maybe use the browser native anchors instead?

**To Reproduce**
1. Have a long page with multiple stories
2. Switch to the "Docs" tabs
3. Click on multiple links in the stories nav menu

**Expected behavior**
When a nav link from the menu is clicked, go straight to the selected story without going back to the top of page

**Screenshots**

![sb-navigation](https://user-images.githubusercontent.com/794579/67046259-ecb22200-f0fd-11e9-9aff-40625052d0eb.gif)

**System:**
  Using storybook/react version 5.2.4

  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  Binaries:
    Node: 12.5.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.19.1 - C:\Dev\20_gsoft\sg-orbit\node_modules\.bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.17763.771.0

**Comment by shilman** [comment]
Closing as dupe to #8286
