### ISSUE TITLE
Multiline template error with empty rows inside mdx

### ISSUE THREAD

**Issue by artaommahe** [storybookjs/storybook#8473]
**Describe the bug**
Storybook provides an error while using empty row inside multiline template in mdx files (DocsPage, angular)
```
Module build failed (from ./node_modules/@mdx-js/loader/index.js):
SyntaxError: unknown: Unexpected token (17:53)

  15 |       template: `
  16 |         
> 17 | 
{`    <app-root></app-root>
     |                                                      ^
  18 |   \`
  19 | }}
  20 | `}</code></pre>
```

**To Reproduce**
1. clone https://github.com/artaommahe/storybook-docs-multiline-template
2. yarn install
3. yarn start-storybook
4. see an error
5. remove empty row in template https://raw.githubusercontent.com/artaommahe/storybook-docs-multiline-template/master/src/app/app.stories.mdx
6. no error
7. add `\` at empty row
8. no error

**Expected behavior**
Empty rows are allowed inside mdx template.

**Code snippets**
```
<Preview>
  <Story name="Overview">
    {{
      template: `
        <app-root></app-root>

        <app-root></app-root>
      `
    }}
  </Story>
</Preview>
```

It's a regular use-case for complex markup showcase or having same component multiple times in different states.

**Comment by shilman** [comment]
Closing as dupe to https://github.com/storybookjs/storybook/issues/7902
