### ISSUE TITLE
Addon-storysource : `keyof typeof` bug

### ISSUE THREAD

**Issue by dbenfouzari** [storybookjs/storybook#8476]
**Describe the bug**
I had some problems by working with `addon-storysource` and TypeScript, and after some investigations I see that is caused by an import of a `type`.

Let's see together :

**To Reproduce**
* Write a simple working story (and `addon-storysource` of course)
* Inside the file, write something like :
```ts
const myObject = { one: 'One', two: 'Two' };

type MyObjectKeys = keyof typeof myObject;

// or event simpler :

type MyObjectKeys = "one" | "two";
```

**Expected behavior**
Nothing special, just working like before.

**Actual behavior**
`Story` addon tab silently crashes by drawing "loading source..."

**System:**
```
Environment Info:

  System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 12.12.0 - ~/.nodenv/shims/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.11.3 - ~/.nodenv/shims/npm
  Browsers:
    Chrome: 77.0.3865.120
    Safari: 13.0.2
  npmPackages:
    @storybook/addon-a11y: 5.2.4 => 5.2.4 
    @storybook/addon-actions: 5.2.4 => 5.2.4 
    @storybook/addon-docs: ^5.2.4 => 5.2.4 
    @storybook/addon-knobs: 5.2.4 => 5.2.4 
    @storybook/addon-links: 5.2.4 => 5.2.4 
    @storybook/addon-storysource: 5.2.4 => 5.2.4 
    @storybook/addons: 5.2.4 => 5.2.4 
    @storybook/preset-create-react-app: 1.1.0 => 1.1.0 
    @storybook/react: 5.2.4 => 5.2.4
```

**Comment by pocka** [comment]
@dbenfouzari 
I tested your code (`const myObject ...`) in `cra-ts-kitch-sink` but didn't reproduce the bug 🤔 
Can you provide a reproduce repo?
