### ISSUE TITLE
Addon-docs: "No props found for this component" when keep interface in separate file

### ISSUE THREAD

**Issue by khantopa** [storybookjs/storybook#8482]
I'm using **create-react-app --typescript**
Docs page show "No props found for this component" when keep the interface in separate file.
But it works fine when keeping the interface with component file.
 
For type i create a interface like this

It works fine
======================================================================

*Text.tsx*

```
import React, {FC} from 'react'

interface IText {
  /**
  * Some text to display
  */
   text: string;
}


/**
* Text component
*/
const Text: FC<IText> = ({text}) => {
  return <h1> { text } </h1>
}

export default Text;
```

*Text.stories.tsx*

```
import Text, { IText } from './Text';

export default {
  title: 'Text',
  component: Text
}

export const text: FC<IText> = ()=> <Text />
```

Not working
======================================================================

***No props found for this component***
When keeping interface inn separate file

*Text.interface.tsx*

```
export default interface IText {
  /**
  * Some text to display
  */
   text: string;
}
```

*Text.tsx*

```
import {IText} from './IText.tsx';

/**
* Text component
*/
const Text: FC<IText> = ({text}) => {
  return <h1> { text } </h1>
}

export default Text;
```

*Text.stories.tsx*
```
import Text from './Text';
import IText from './Text.interface'

export default {
  title: 'Text',
  component: Text
}

export const text: FC<IText> = ()=> <Text />

```

**Comment by khantopa** [comment]
By keeping interface file name with `.ts` instead of `.tsx` it shows the props table

**Comment by zaleGZL** [comment]
@

> By keeping interface file name with `.ts` instead of `.tsx` it shows the props table

This method can indeed solve the problem, but I found that when I modify the comment document, webpack is not rebuild, which makes it impossible to refresh the page to see the modified content.
