### ISSUE TITLE
Addon-docs: default prop of function type should render the function name when available

### ISSUE THREAD

**Issue by patricklafrance** [storybookjs/storybook#8484]
**Describe the bug**
My component have the following default props:

```
static defaultProps = {
    onSearch: startsWithSearch
};
```

with the following named function:

```
function startsWithSearch(event, items, query) {
    return items.filter(x => x.text.toUpperCase().startsWith(query.toUpperCase()));
}
```

The rendered default prop in docs props table is:

```
"function startsWithSearch(event, items, query) {\r\n return items.filter(x => x.text.toUpperCase().startsWith(query.toUpperCase()));\r\n}"
```

**Expected behavior**
The name of the function when available, in this case : `startsWithSearch`.

When it's an anonymous function, I suggest something like: `func` or `anonymous function`.

IMO the stringify representation of the function is never a good fit since it takes a lot of space and most of the time is not helpfull to the reader of the documentation.

**Screenshots**
![image](https://user-images.githubusercontent.com/794579/67147749-a8da2c80-f265-11e9-8756-675abe36cec1.png)

**System:**
OS: Windows 10
CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
Binaries:
Node: 12.5.0 - C:\Program Files\nodejs\node.EXE
Yarn: 1.19.1 - C:\Dev\20_gsoft\sg-orbit\node_modules.bin\yarn.CMD
npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
Browsers:
Edge: 44.17763.771.0

**Additional context**
My storybook is available here: https://github.com/gsoft-inc/sg-orbit/tree/storybook-docs

To install: `yarn bootstrap`
To start sb: `yarn start-sb`

Then view "Multi Select/default" is docs view mode

**Comment by shilman** [comment]
Olé!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-alpha.45 containing PR #8826 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
