### ISSUE TITLE
Surplus support

### ISSUE THREAD

**Issue by Qix-** [storybookjs/storybook#8485]
**Describe the solution you'd like**
Support for [Surplus](https://github.com/adamhaile/surplus) would be wonderful.

**Describe alternatives you've considered**
Basic HTML mode, but that quickly ran into limitations.

**Are you able to assist bring the feature to reality?**
Yes.

**Additional context**
One of the fastest JSX libraries available (according to benchmarks), beginning to ramp up in popularity.

cc @adamhaile

**Comment by Qix-** [comment]
There's an open PR.

**Comment by shilman** [comment]
We are releasing the frameworks API as part of 7.0. Announcement here: https://storybook.js.org/blog/framework-api/

This should make it possible for somebody for the community to release surplus support as an independent package. If anybody is interested & wants help, please chat us in the #contributing channel on the Storybook Discord https://discord.gg/storybook
