### ISSUE TITLE
Unnecessary prompt for available port in react-native

### ISSUE THREAD

**Issue by RamKrish2079** [storybookjs/storybook#8487]
**Describe the bug**
When using storybook with react-native, `yarn storybook` which runs `start-storybook -p 7007` prompting

> Port 7007 is not available. Would you like to run Storybook on port 7007 instead?

**To Reproduce**
```
npx react-native init myapp
cd myapp
npx -p @storybook/cli sb init

 • Detecting project type. ✓
? Do you want to install dependencies necessary to run storybook server? You can manually do it later by install @storybook/react-native-server
Yes
...
yarn storybook
```

**Expected behavior**
If the specified port(ie: using the option `-p` for `start-storybook`) is available it should run without any prompt

**Screenshots**
![20-Oct-Sun-2019-14:57:55-821x89](https://user-images.githubusercontent.com/26812792/67157452-0647a980-f34a-11e9-880e-e588df469464.png)

**System:**
````
    @storybook/addon-actions: ^5.2.4 => 5.2.4 
    @storybook/addon-links: ^5.2.4 => 5.2.4 
    @storybook/addons: ^5.2.4 => 5.2.4 
    @storybook/react-native: ^5.2.4 => 5.2.4 
    @storybook/react-native-server: ^5.2.4 => 5.2.4
````

**Comment by shilman** [comment]
Yay!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.5 containing PR #8491 that references this issue. Upgrade today to try it out!

**Comment by shilman** [comment]
Ermahgerd!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-alpha.24 containing PR #8491 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

**Comment by shilman** [comment]
Huzzah!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-alpha.32 containing PR #8584 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

**Comment by shilman** [comment]
Boo-yah!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.6 containing PR #8584 that references this issue. Upgrade today to try it out!
