### ISSUE TITLE
Addon-docs: DOCS_MODE available in PREVIEW code

### ISSUE THREAD

**Issue by patricklafrance** [storybookjs/storybook#8490]
**Is your feature request related to a problem? Please describe.**
I would like to know if my storybook is built in DOCS_MODE in the .storybook/config.js file.

My goal is to filter out stories when the site is built for docs.

**Describe the solution you'd like**
Something like `import { DOCS_MODE } from "globals";` would work.

**Describe alternatives you've considered**
I defined a custom `STORYBOOK_DOCS_MODE` env var.

**Comment by shilman** [comment]
@patricklafrance Nice, currently the variable is available in MANAGER code (storybook UI), but not in PREVIEW code (user stories). Shouldn't be hard to add it, but can you tell me about your use case a little bit more? What will you do based on the existence of that variable?

**Comment by patricklafrance** [comment]
Got it!

I want to filter out story paths and conditionally add / remove decorators.

For the story paths:

```
if (!isDocs) {
        stories = [...stories, require.context("../../packages/react-components/components", true, /.chroma.jsx$/)];
}
```

Basically, I wrote specific stories for chromatic visual regression tests. 

I want to load those stories when I build my default storybook (canvas + docs) and when I build my storybook for chromatic.

But I don't want them when I built my storybook for my documentation website.

I am not sure the current way to exclude a story from docs (story parameters) work, since the stories will be available in the navigation menu even if there is no docs associated with them.

![image](https://user-images.githubusercontent.com/794579/67163461-1c9b3880-f33d-11e9-8cda-7092c63166da.png)

As for the decorators:

```
if (!isDocs) {
   addDecorator((storyFn, context) => <StoryContainer story={storyFn()} context={context} />);
}
```

Since it's a custom decorator and it load in the manager UI I guess I could move the logic in the StoryContainer and use the currently available DOCS_MODE variable.

But, personally, I like the idea of having a central location where I put all my conditional logic instead of spreading it in all my custom decorators / addons.

I could also make 2 distinct storybook config but it seem overkill for my needs.

Thank you,

Patrick

**Comment by shilman** [comment]
The reason I ask is because there's a `{ docs: { disable: true }}` parameter that might also do what you need

**Comment by patricklafrance** [comment]
You're right. I did test it with `{ docs: { disable: true }}` but I forgot I am currently on version 5.2.4 and not 5.3.0.

I will try it when version 5.3.0 is officially out. Thanks!

**Comment by shilman** [comment]
closing this as duplicate to #8474
