### ISSUE TITLE
[Angular Ivy]: Angular throws an exception when storybook re-bootstraps the application

### ISSUE THREAD

**Issue by sharikovvladislav** [storybookjs/storybook#8494]
**Describe the bug**
Angular throws exception when HMR loads updated chunk of code. The problem will reproduce in this conditions: 
- 1 module
- 1 component and 1 directive in declarations array of that module
- 1 story that imports the module to the story
- you change the code of the component, so new chunk of the code is downloaded by browser

Exception:

```
vendors~main.831b1287c1a8912e0be9.bundle.js:171455 Unhandled Promise rejection: Type DirectiveDirective is part of the declarations of 2 modules: SomeModule and SomeModule! Please consider moving DirectiveDirective to a higher module that imports SomeModule and SomeModule. You can also create a new NgModule that exports and includes DirectiveDirective then import that NgModule in SomeModule and SomeModule. ; Zone: <root> ; Task: Promise.then ; Value: Error: Type DirectiveDirective is part of the declarations of 2 modules: SomeModule and SomeModule! Please consider moving DirectiveDirective to a higher module that imports SomeModule and SomeModule. You can also create a new NgModule that exports and includes DirectiveDirective then import that NgModule in SomeModule and SomeModule.
    at verifySemanticsOfNgModuleDef (vendors~main.831b1287c1a8912e0be9.bundle.js:60892)
    at Function.get (vendors~main.831b1287c1a8912e0be9.bundle.js:60830)
    at getInjectorDef (vendors~main.831b1287c1a8912e0be9.bundle.js:36208)
    at R3Injector.push../node_modules/@angular/core/fesm5/core.js.R3Injector.processInjectorType (vendors~main.831b1287c1a8912e0be9.bundle.js:47670)
    at vendors~main.831b1287c1a8912e0be9.bundle.js:47707
    at vendors~main.831b1287c1a8912e0be9.bundle.js:36741
    at Array.forEach (<anonymous>)
    at deepForEach (vendors~main.831b1287c1a8912e0be9.bundle.js:36741)
    at vendors~main.831b1287c1a8912e0be9.bundle.js:36741
    at Array.forEach (<anonymous>)
```

Long story short,
1 Application bootstraps and loads initial chunks of the code (all modules, declarations and others)
2 Storybook creates DynamicModule/DynamicComponent with imports/declarations and others from the story (`draw` function in `helpers.ts`)
...
3 You change the code and trigger wepback and webpack-dev-server to send the browser a command to download a new chunk of code (hot-update)
4 The browser requests the changed chunk of the code and executes it
4 Storybook executes `draw` again and do whole process again
5 At some moment Angular checks if declaration what you try to register is already registered in some module.

In case of new received component you will get no error, since it would be another function declaration / class (it physically placed in another JS file - in `*.hot-update.js` file). In case of old dependencies (which are not changed) you will get exception.

**To Reproduce**
1 Clone the repo to some directory https://github.com/sharikovvladislav/with-ivy-with-latest-storybook-declaration-of-two-modules
2 Go to the directory
3 Install the deps
4 Run storybook `npm run storybook`
5 Wait unitl browser is opened
6 Go to `component.component.ts` , you can see `console.log` in constructor
7 Go back to the browser and check the console & story

**Expected behavior**
1 Story is working (no blank screen in storybook story-window)
2 No exceptions in the console.

**Screenshots**
![image](https://user-images.githubusercontent.com/5622526/67196870-4bc8ad00-f404-11e9-9cff-db255dd29cf1.png)

**Code snippets**
NgModule source code (this modules is imported to the story):
```
// ...
import { ComponentComponent } from './component/component.component';
import { DirectiveDirective } from './directive.directive';

@NgModule({
  declarations: [ComponentComponent, DirectiveDirective],
  imports: [
    CommonModule
  ],
  exports: [ ComponentComponent ]
})
export class SomeModule { }
```

Initial compiled code of the module is: 

```
/***/ "./src/app/some/some.module.ts":
/*!*************************************!*\
  !*** ./src/app/some/some.module.ts ***!
  \*************************************/
/*! exports provided: SomeModule */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "SomeModule", function() { return SomeModule; });
/* harmony import */ var tslib__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! tslib */ "./node_modules/tslib/tslib.es6.js");
/* harmony import */ var _angular_core__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! @angular/core */ "./node_modules/@angular/core/fesm5/core.js");
/* harmony import */ var _angular_common__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! @angular/common */ "./node_modules/@angular/common/fesm5/common.js");
/* harmony import */ var _component_component_component__WEBPACK_IMPORTED_MODULE_3__ = __webpack_require__(/*! ./component/component.component */ "./src/app/some/component/component.component.ts");
/* harmony import */ var _directive_directive__WEBPACK_IMPORTED_MODULE_4__ = __webpack_require__(/*! ./directive.directive */ "./src/app/some/directive.directive.ts");

let SomeModule = class SomeModule {
};
SomeModule = Object(tslib__WEBPACK_IMPORTED_MODULE_0__["__decorate"])([
    Object(_angular_core__WEBPACK_IMPORTED_MODULE_1__["NgModule"])({
        declarations: [_component_component_component__WEBPACK_IMPORTED_MODULE_3__["ComponentComponent"], _directive_directive__WEBPACK_IMPORTED_MODULE_4__["DirectiveDirective"]],
        imports: [
            _angular_common__WEBPACK_IMPORTED_MODULE_2__["CommonModule"]
        ],
        exports: [_component_component_component__WEBPACK_IMPORTED_MODULE_3__["ComponentComponent"]]
    })
], SomeModule);

/***/ }),
```

Note, that there are imports to `component.component.ts` and `directive.directive.ts` in the module.

This is the `hot-update` chunk of code when you change `Component.component.ts` file:

```
/***/ "./src/app/some/component/component.component.ts":
/*!*******************************************************!*\
  !*** ./src/app/some/component/component.component.ts ***!
  \*******************************************************/
/*! exports provided: ComponentComponent */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "ComponentComponent", function() { return ComponentComponent; });
/* harmony import */ var tslib__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! tslib */ "./node_modules/tslib/tslib.es6.js");
/* harmony import */ var _angular_core__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! @angular/core */ "./node_modules/@angular/core/fesm5/core.js");


let ComponentComponent = class ComponentComponent {
    constructor() {
        console.log('>> 12345');
    }
    ngOnInit() {
    }
};
ComponentComponent = Object(tslib__WEBPACK_IMPORTED_MODULE_0__["__decorate"])([
    Object(_angular_core__WEBPACK_IMPORTED_MODULE_1__["Component"])({
        selector: 'app-component',
        template: (__webpack_require__(/*! ./component.component.html */ "./src/app/some/component/component.component.html").default || __webpack_require__(/*! ./component.component.html */ "./src/app/some/component/component.component.html")).length ? (__webpack_require__(/*! ./component.component.html */ "./src/app/some/component/component.component.html").default || __webpack_require__(/*! ./component.component.html */ "./src/app/some/component/component.component.html")) : '',
        styles: [(__webpack_require__(/*! ./component.component.css */ "./src/app/some/component/component.component.css").default || __webpack_require__(/*! ./component.component.css */ "./src/app/some/component/component.component.css")).length ? (__webpack_require__(/*! ./component.component.css */ "./src/app/some/component/component.component.css").default || __webpack_require__(/*! ./component.component.css */ "./src/app/some/component/component.component.css")) : '']
    })
], ComponentComponent);
/***/ })

})
```

So there is new function declaration there.

Here is the code which throws the exception (from `@angular/core`):
```
    // somewhere at the top
    var ownerNgModule = new Map();

    // some code

    function verifyDeclarationIsUnique(type, suppressErrors) {
        type = resolveForwardRef(type);
        var existingModule = ownerNgModule.get(type);
        if (existingModule && existingModule !== moduleType) {
            if (!suppressErrors) {
                var modules = [existingModule, moduleType].map(stringifyForError).sort();
                errors.push("Type " + stringifyForError(type) + " is part of the declarations of 2 modules: " + modules[0] + " and " + modules[1] + "! " +
                    ("Please consider moving " + stringifyForError(type) + " to a higher module that imports " + modules[0] + " and " + modules[1] + ". ") +
                    ("You can also create a new NgModule that exports and includes " + stringifyForError(type) + " then import that NgModule in " + modules[0] + " and " + modules[1] + "."));
            }
        }
        else {
            // Mark type as having owner.
            ownerNgModule.set(type, moduleType);
        }
    }
```

What happens there?

The code inititalize simple Map at start. When the application bootstraps, Angular put entities to that map.

When we change the `component.component.ts` file Angular will execute this function again (for all declarations/modules and others recursively). At some moment Component and Directive will be passed to that check function. `Component` will pass the check, since it is new function declaration (from `hot-update` file). But in case of `Directive` same function declaration (as initial) will be resolved with absolutely same reference. So `ownerNgModule.get(type)` property acces expression will return parent NgModule and will throw the exception.

**System:**
Please paste the results of `npx -p @storybook/cli@next sb info` here.

**Additional context**
I think, that this problem is actual only for Ivy.

Check that angular components which are rendered in storybook are compiled using Ivy.

1 You should see such definition for the component in the Chrome sources:
![image](https://user-images.githubusercontent.com/5622526/67196718-06a47b00-f404-11e9-9138-11b9d831a053.png)
Notice, that storybook works in JIT mode, so such definitions are created just in time, not ahead of time (like in AOT mode)

2 You should not see *.ngfactory files or code in the application `main.*.js`.

If you see ngfactories, try to compile node_modules again using `ngcc` compiler: run `./node_modules/.bin/ngcc` in the project root.

If you have any problems, ask me, I will try to help.

**Comment by sharikovvladislav** [comment]
Any information? @shilman

**Comment by sharikovvladislav** [comment]
You released beta.0 few days ago. Am I right that Angular will just not work correctly (very poor developer experience due to this bug) when storybook will be released? 

@shilman

**Comment by shilman** [comment]
@sharikovvladislav No. Beta just means that we're trying not to add any big changes between now and release. Bugfixes can come in all the way until release, and you're welcome to contribute a fix for this prerelease angular feature whenever you'd like.

**Comment by sharikovvladislav** [comment]
Oops https://github.com/angular/angular/issues/35265

**Comment by chriscarpenter12** [comment]
@sharikovvladislav You [commented](https://github.com/angular/angular/issues/35265#issuecomment-589083119) that it works when AoT is enabled. Were you able to enable AoT with Storybook?

**Comment by DerZyklop** [comment]
@sharikovvladislav i second @chriscarpenter12’s question.
