### ISSUE TITLE
Trying to Use Docs Addon (DocsPage) with Emotion

### ISSUE THREAD

**Issue by araligan** [storybookjs/storybook#8496]
**Describe the bug**
When trying to use jsx from @emotion/core, it mess with the auto-generated documentation (DocsPage)

**To Reproduce**
1. In your component file, add import jsx from @emotion/core and use it
2. Add comment in your file, so it will be shown as description in the DocsPage

**Expected behavior**
Description and the Props Description should not be empty / null

**Code snippets**
```
/** @jsx jsx */
import { jsx } from '@emotion/core';
import PropTypes from 'prop-types';
...

/** 
* Sample Description 
*/
const Button = () => {...}
...
Button.propTypes = {
  appearance: PropTypes.oneOf(['primary', 'default', 'link', 'danger']),
};
```

**System:**
  System:
    OS: Windows 10
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 8.11.3 - D:\Program Files\nodejs\node.EXE
    Yarn: 1.19.1 - D:\Users\Repository\adhub-component\node_modules\.bin\yarn.CMD
    npm: 5.6.0 - D:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.387.0

**Additional context**
Emotion Lib: https://emotion.sh/docs/@emotion/core
I'm using this syntax, unless there's another way to use the jsx.. please let me know. Thanks! I'm just starting to learn all of this :)

**Comment by pierrecholhot** [comment]
With emotion's header (`/** @jsx jsx */`), the component's description is correctly parsed when using Class Components. Not the `propTypes` descriptions though.
