### ISSUE TITLE
storybook deep-links should be more flexible

### ISSUE THREAD

**Issue by macrozone** [storybookjs/storybook#8500]
**Is your feature request related to a problem? Please describe.**

with https://docs.gitlab.com/ee/ci/review_apps/index.html#route-maps you can make links on review apps for changed files.

However, if you name your components in your sourcecode in usual PascalCase

`src/components/MyComponent.js`

the corresponding story might look like:

```

storiesOf("MyComponent", module)
  .add("default view", () => (
    <MyComponent />
  ));
```

Problem is now that you can't derive a deeplink from the filename, because the deeplink from storybook will be

```
?path=/story/mycomponent--default-view
```

there are two problems:

- `mycomponent` has to be lowercase
- you have to now the story name or always have your first story for a component have the same name, otherwise you can't add `--default-view`

**Describe the solution you'd like**

- storybook should accept deeplinks which uppercase
- storybook should accept deeplinks without the story-name:

`?path=/story/MyComponent`

this should redirect to the first sub-story (default View)

**Describe alternatives you've considered**

nothing easy comes to my mind. 

**Are you able to assist bring the feature to reality?**

I guess, if i now the internals

**Comment by macrozone** [comment]
related: https://github.com/storybookjs/storybook/issues/7582

**Comment by shilman** [comment]
Ermahgerd!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-alpha.46 containing PR #8516 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
