### ISSUE TITLE
Question: how to start using CSF?

### ISSUE THREAD

**Issue by jeron-diovis** [storybookjs/storybook#8501]
It is said that CSF is recommended since v.5.2.

I have 5.2.4 installed. My story looks like this:

```js
import base from "paths.macro"

import App from "./App"

export default {
  title: `${base}/TEST`,
  Component: App,
  includeStories: [
    "main"
  ]
}

export const main = () => <App />

console.log("IMPORTED")
```

With this, I see my "IMPORTED" message in console, but storybook says me "No Preview". No errors.

![Screenshot 2019-10-21 18 02 30](https://user-images.githubusercontent.com/2756868/67217170-fce33d80-f42c-11e9-9ecb-b1307c0e3400.png)

I can't understand what am I doing wrong.

**Comment by shilman** [comment]
@jeron-diovis A few things:

1. You might need to update your `configure` statement in `.storybook/config.js`: https://storybook.js.org/docs/basics/writing-stories/#loading-stories 
2. Try making the title a static string
3. Unrelated:
 - `includeStories` unnecessary
 - `Component` => `component`

LMK if that works

**Comment by jeron-diovis** [comment]
It appears I missed the fact that loader func for `configure` must return an exports array now. My bad.
Now it works, thx.
