### ISSUE TITLE
Permalinking to stories

### ISSUE THREAD

**Issue by akrawchyk** [storybookjs/storybook#8507]
**Is your feature request related to a problem? Please describe.**

I want to integrate ZeroHeight or Invision DSM with Storybook. Each product has docs for integrating with Storybook:

* https://zeroheight.com/3xlwst8/p/507ba7
* https://support.invisionapp.com/hc/en-us/articles/360028214732

This is great, however it seems brittle because with Invision DSM, designers could break the integration by changing/removing a Component Container which would [invalidate whatever container id is configured in the story](https://support.invisionapp.com/hc/en-us/articles/360028692651). And ZeroHeight has the opposite problem where a developer could change the url to a story and [invalidate what's configured in that Live Preview](https://zeroheight.com/3xlwst8/p/507ba7/t/2a43).

**Describe the solution you'd like**

I want a way to set a `slug` or describe a permalink with story configuration that will be provided as a permanent route to the story. It is independent of the [story hierarchy](https://storybook.js.org/docs/basics/writing-stories/#story-hierarchy) so if that changes, the permalink will still route to the same story.

**Describe alternatives you've considered**

**Are you able to assist bring the feature to reality?**

Yes but I am new to Storybook so would need help getting started.

**Additional context**

**Comment by shilman** [comment]
@akrawchyk Somehow missed this the first time around. This is great & I'm taking a crack at it in #8775 since it's related to another change.

**Comment by akrawchyk** [comment]
Great! Thanks @shilman, please tell me how I can help with the work 😄

**Comment by shilman** [comment]
Egads!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-alpha.45 containing PR #8808 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Son of a gun!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-beta.2 containing PR #8872 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

**Comment by shilman** [comment]
Egads!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-beta.16 containing PR #9054 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.
