### ISSUE TITLE
Content in `...` menu is scrolling unnecessarily

### ISSUE THREAD

**Issue by kaiyoma** [storybookjs/storybook#8509]
As the title says. Can be seen on any recent version of Storybook. Here's a screencast showing the issue happening on 5.3.0-alpha.23:

https://imgur.com/a/s9bdQLu

**Comment by francismarcus** [comment]
I'l have a look :)

**Comment by francismarcus** [comment]
@kaiyoma Could you perhaps explain the issue further? 
I am unable to reproduce any problem with the scrolling in the menu

**Comment by kaiyoma** [comment]
Oh, the issue is that scrolling isn't necessary at all. If you make the menu a little bit taller, the scrollbar can go away. There's plenty of screen space left. 😄

**Comment by shilman** [comment]
Whoopee!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-alpha.27 containing PR #8545 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Jeepers creepers!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.6 containing PR #8545 that references this issue. Upgrade today to try it out!
