### ISSUE TITLE
Story sorting is broken when CSF and storyOf format are used in the same project

### ISSUE THREAD

**Issue by coryhouse** [storybookjs/storybook#8519]
**Describe the bug**
If you create stories in both formats, the CSF stories are always displayed last. Alphabetical ordering isn't honored.

**To Reproduce**
1. Create a CSF story and a storyOf story. Name the CSF with a letter that starts earlier in the alphabet than the storyOf story.
1. Note that the CSF is displayed last

**Expected behavior**
CSF and storyOf stories should be sorted together into an alphabetized list.

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System:**
Please paste the results of `npx -p @storybook/cli@next sb info` here.

**Additional context**

**Comment by shilman** [comment]
@coryhouse By default Storybook sorts based on load order: https://storybook.js.org/docs/basics/writing-stories/#loading-stories

You can override the sort order with the `storySort` parameter: https://github.com/storybookjs/storybook/blob/master/lib/ui/README.md#story-order

We might reconsider the default order in a future version, but it would be a breaking change, and for now hopefully these two options should have you covered.

**Comment by coryhouse** [comment]
Thanks for the quick reply @shilman. I converted all stories to CSF to resolve, but it sounds like you're saying the order issue I described is working as designed since CSF is loaded after storyOf. Correct?

**Comment by shilman** [comment]
Yeah, I hadn't thought it through but now that you say it, definitely the CSF always get loaded after storiesOf in the current implementation, and for details I won't go into, it would be really hard to do it any other way. Now that you're fully on CSF, the load order within CSF files should be respected. Also, it's a big step up!!! 😁 

If you need more control over sort order, the `storySort` option is still available.

**Comment by SimonFinney** [comment]
@coryhouse I've also come across this issue while leveraging a custom `storySort` function - We're not in a position to completely migrate our stories to CSF immediately, but our CSF stories are always appearing after any stories that have been defined with `storiesOf`, regardless of the sort.
