### ISSUE TITLE
Addon-docs: Allow a TOOL addon to be available when the storybook is built with --docs

### ISSUE THREAD

**Issue by patricklafrance** [storybookjs/storybook#8521]
**Is your feature request related to a problem? Please describe.**
Allow a custom "TOOL" addon to be available when the storybook is built with the --docs flag.

**Comment by shilman** [comment]
Can you elaborate on this? Is it different from #6700

**Comment by patricklafrance** [comment]
A little bit, I am not looking for compatibility with the actual addons for story.

In my case, I have an addon to switch my design system themes. All it does, is updating some CSS variables based on the selected theme and those variables affect all my components.

I would like to be able to have as a tool in the docs tabs.

**Comment by shilman** [comment]
@patricklafrance FYI you can label an issue as `todo` or `in progress` if you don't want the stale bot to touch it.

**Comment by patricklafrance** [comment]
oh, good tip, thanks @shilman :)

**Comment by shilman** [comment]
closing as dupe to #13025
