### ISSUE TITLE
Addon-docs: oneOf([]) prop type doesn't render well in the props table

### ISSUE THREAD

**Issue by patricklafrance** [storybookjs/storybook#8522]
**Describe the bug**
My component define the following property:

`position: oneOf(POSITIONS)`

with the following POSITIONS definition:

```
export const TOP_LEFT = "top-left";
export const TOP_RIGHT = "top-right";
...

export const POSITIONS = [TOP_LEFT, TOP_RIGHT, TOP_CENTER, BOTTOM_LEFT, BOTTOM_RIGHT, BOTTOM_CENTER];
```

The rendered prop in docs props table is:

{"name":"enum","computed":true,"value":"POSITIONS"}

**Expected behavior**
I would expect it to be something like:

["top-left", "top-right", ...]

**Screenshots**
![image](https://user-images.githubusercontent.com/794579/67316388-5489b380-f4d6-11e9-80fc-97a7b73213c0.png)

**System:**
System:
OS: Windows 10
CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
Binaries:
Node: 12.5.0 - C:\Program Files\nodejs\node.EXE
Yarn: 1.19.1 - C:\Dev\20_gsoft\sg-orbit\node_modules.bin\yarn.CMD
npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
Browsers:
Edge: 44.17763.771.0

**Comment by patricklafrance** [comment]
Semantic UI is doing it like this...

For

```
additionPosition: PropTypes.oneOf(['top', 'bottom'])
```

You get

![image](https://user-images.githubusercontent.com/794579/67398781-2dd08900-f579-11e9-80c7-bf795f66f07e.png)

**Comment by mcpatten** [comment]
It would be great to have some support like this for `enums` in typescript as well.  

With `typescript/react-docgen-typescript-loader` string unions display the list of options as expected, but when using an `enum` it just prints the name of the enum.

 **string literal union:** 
 &nbsp;<img height="26px" src="https://user-images.githubusercontent.com/4432259/67410733-89efd900-f58a-11e9-984b-624c93c597f3.png" />
**enum:**
<img height="30px" src="https://user-images.githubusercontent.com/4432259/67410737-8c523300-f58a-11e9-8e1c-fc0ae78e024a.png" />

**Comment by patricklafrance** [comment]
@mcpatten you can fix this for string enum by settings the `shouldExtractLiteralValuesFromEnum` prop of `https://github.com/strothj/react-docgen-typescript-loader` to true.

Here's a complete sample if you are using the presets:

```js
// preset.js

module.exports = [
  {
    name: '@storybook/preset-create-react-app',
    options: {
      tsDocgenLoaderOptions: {
        tsconfigPath: path.resolve(__dirname, '../tsconfig.json'),
        shouldExtractLiteralValuesFromEnum: true,
      },
    },
  },
  '@storybook/addon-docs/react/preset',
];
```

**Comment by patricklafrance** [comment]
Closing this since it's works fine in the latest alpha.
