### ISSUE TITLE
Addon-docs: arrayOfType([]) prop type doesn't render well in the props table

### ISSUE THREAD

**Issue by patricklafrance** [storybookjs/storybook#8523]
**Describe the bug**
My component define the following property:

`initialVisibleMonth: oneOfType([momentType, func])`

The rendered prop in docs props table is:

```
Union<custom | func>
```

**Expected behavior**
I am not sure, what bothers me is the "union" text, IMO this is confusing for the reader of the doc. Ideally, it would be awesome to have someting like:

moment | func

A maybe easier alternative would be:

custom | func

**Screenshots**
![image](https://user-images.githubusercontent.com/794579/67316903-45573580-f4d7-11e9-8358-7d93b6970def.png)

**System:**
OS: Windows 10
CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
Binaries:
Node: 12.5.0 - C:\Program Files\nodejs\node.EXE
Yarn: 1.19.1 - C:\Dev\20_gsoft\sg-orbit\node_modules.bin\yarn.CMD
npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
Browsers:
Edge: 44.17763.771.0

**Comment by shilman** [comment]
Yee-haw!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-alpha.45 containing PR #8826 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
