### ISSUE TITLE
React-Native dev-server not working

### ISSUE THREAD

**Issue by Jm-Zion** [storybookjs/storybook#8524]
**Describe the bug**
Following CLI steps for react-native : npx -p @storybook/cli sb init --type react_native
Launching Storybook
Load endlessly, nothing show up.

**To Reproduce**
npx -p @storybook/cli sb init --type react_native
install react-native-server deps throught CLI
Open localhost
Nothing show up

**System:**

  System:
    OS: macOS Mojave 10.14.3
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 77.0.3865.120
    Firefox: 69.0.2
    Safari: 12.0.3
  npmPackages:
    @storybook/addon-actions: ^5.2.4 => 5.2.4 
    @storybook/addon-links: ^5.2.4 => 5.2.4 
    @storybook/react-native-server: ^5.2.4 => 5.2.4

**Comment by Gongreg** [comment]
Hey, you should check out 5.3.0-alpha.37 . I cannot reproduce your issue.
