### ISSUE TITLE
addon-info: Need options to pass to react-element-to-jsx-string

### ISSUE THREAD

**Issue by felixpis** [storybookjs/storybook#8528]
Method `_getSourceCode()` was changed and now uses **react-element-to-jsx-string** module to render the code of component:
`<Code code={jsxToString(children)} language="jsx" format={false} />`.
I think it would be very useful to pass additional options to `jsxToString`.
For instance now all the default props of the component rendered in code. And I would like to not render these props if values are equal to what I set in story for this component (or if I don't set value at all)

**Comment by shilman** [comment]
`Addon-info` is being superceded by `addon-docs`, which fixes a bunch of bugs and is easier to maintain. Please give it a try! https://medium.com/storybookjs/storybook-docspage-e185bc3622bf
