### ISSUE TITLE
Much higher CPU usage when moving from 5.1.X to 5.2.X on idle storybook

### ISSUE THREAD

**Issue by cherouvim** [storybookjs/storybook#8529]
I have a create-react-app (all packages to latest version) with 20-40 stories. When `npm run storybook` has finished and is simply running to monitor file changes, process `node` on 5.1.X idles at 2.5% but on 5.2.X idles at 30%.

**System:**
```
  System:
    OS: Linux 4.4 Ubuntu 16.04.5 LTS (Xenial Xerus)
    CPU: (2) x64 AMD FX(tm)-6300 Six-Core Processor
  Binaries:
    Node: 10.15.3 - /usr/bin/node
    Yarn: 1.15.2 - /usr/bin/yarn
    npm: 6.11.2 - /usr/bin/npm
  npmPackages:
    @storybook/addon-actions: 5.1.x => 5.1.11
    @storybook/addon-centered: 5.1.x => 5.1.11
    @storybook/addon-knobs: 5.1.x => 5.1.11
    @storybook/addons: 5.1.x => 5.1.11
    @storybook/react: 5.1.x => 5.1.11
  npmGlobalPackages:
    @storybook/cli: 4.0.9
```

**Comment by cherouvim** [comment]
I confirm this on Windows as well.

**Comment by shilman** [comment]
Thanks @cherouvim. I saw this in Storybook's `official-storybook` example and it was bothering me, but I couldn''t repro it in a standalone project. Do you have a repro you can share?

**Comment by cherouvim** [comment]
Currently on my windows machine, the node process when `npm install & npm run storybook` has completed and is idle:
- this has 0% CPU: [8529-repro-5.1.11.zip](https://github.com/storybookjs/storybook/files/3762641/8529-repro-5.1.11.zip)
- this has 40% CPU: [8529-repro-5.2.5.zip](https://github.com/storybookjs/storybook/files/3762642/8529-repro-5.2.5.zip)

**Comment by cherouvim** [comment]
Regarding the linked issue https://github.com/storybookjs/telejson/issues/26 note that I started 5.2.5 in a vanilla Ubuntu 18 VM and {{watch -c "netstat | fgrep tcp"}} didn't show any signs that storybook connected anywhere while starting up or while running (idling at 30%).

**Comment by shilman** [comment]
Thanks for checking @cherouvim. I figured that scenario is highly unlikely, but wanted to raise the concern just in case!

**Comment by cherouvim** [comment]
In case it helps, I've identified that the high CPU issue is introduced when moving from 5.1.11 to 5.2.0.

**Comment by shilman** [comment]
@cherouvim any interest in bisecting on the 5.2 alphas/betas to see exactly where this got introduced? it would help tremendously!

**Comment by cherouvim** [comment]
Will do and let you know ASAP.

**Comment by cherouvim** [comment]
I tested releases in the following order and found that the CPU issue must have been introduced in `5.2.0-alpha.36`:
- :-1: 5.2.0-beta.6
- :-1: 5.2.0-beta.0
- :+1: 5.2.0-alpha.23
- :-1: 5.2.0-alpha.37
- :+1: 5.2.0-alpha.30
- :+1: 5.2.0-alpha.33
- :+1: 5.2.0-alpha.35
- :-1: 5.2.0-alpha.36

**Comment by shilman** [comment]
@cherouvim you are a hero 🥇 

@ndelangen how much do you want to bet it's this change: https://github.com/storybookjs/storybook/pull/6265

**Comment by shilman** [comment]
@cherouvim Reverted & released as `5.3.0-alpha.35`. Can you upgrade and confirm this fixes it?

**Comment by shilman** [comment]
Zoinks!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-alpha.35 containing PR #8657 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by cherouvim** [comment]
I confirm that `5.3.0-alpha.35` solves the issue. Thanks.

**Comment by shilman** [comment]
@cherouvim Great work on tracking it down. Much appreciated!!!

**Comment by ndelangen** [comment]
You people absolutely 100% ROCK, @cherouvim You deserve a freaking medal 🎖

**Comment by cherouvim** [comment]
I'm glad I helped. The medal goes to my slow workstation which allowed me to spot this issue in the first place :)

**Comment by shilman** [comment]
Great Caesar's ghost!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.6 containing PR #8657 that references this issue. Upgrade today to try it out!
