### ISSUE TITLE
`addSourceDecorator` declared but not read

### ISSUE THREAD

**Issue by mfolnovic** [storybookjs/storybook#8530]
**Describe the bug**

I'm defining my stories in Typescript and I'm getting an error:

```
TS6133: 'addSourceDecorator' is declared but its value is never read.
```

**To Reproduce**
1. create a story that works:

```
export const empty = () => <Header titleLabel={"Some String"} />;
```

2. try to simulate opaque types in Typescript (https://codemix.com/opaque-types-in-javascript/):

```
export const empty = () => <Header titleLabel={"Some String" as string & { _: "Label" }} />;
```

3. see above error

**Expected behavior**
It should work.

**Code snippets**

```
export const empty = () => <Header titleLabel={"Some String" as string & { _: "Label" }} />;
```

**System:**

```
Environment Info:

  System:
    OS: Linux 5.3 Arch Linux undefined
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  Binaries:
    Node: 12.11.1 - /usr/bin/node
    Yarn: 1.19.0 - ~/.yarn/bin/yarn
    npm: 6.11.3 - /usr/bin/npm
  Browsers:
    Firefox: 69.0.2
  npmPackages:
    @storybook/addon-actions: ^5.2.3 => 5.2.5 
    @storybook/addon-contexts: ^5.2.3 => 5.2.5 
    @storybook/addon-docs: ^5.2.3 => 5.2.5 
    @storybook/addon-knobs: ^5.2.4 => 5.2.5 
    @storybook/addon-links: ^5.2.3 => 5.2.5 
    @storybook/addon-storyshots: ^5.2.4 => 5.2.5 
    @storybook/addon-storyshots-puppeteer: ^5.2.4 => 5.2.5 
    @storybook/addon-viewport: ^5.2.4 => 5.2.5 
    @storybook/addons: ^5.2.3 => 5.2.5 
    @storybook/preset-typescript: ^1.1.0 => 1.1.0 
    @storybook/react: ^5.2.3 => 5.2.5 
```

**Comment by iheidari** [comment]
It seems you are using storysource addon in your storybook to show the source of your stories.
This addon as default, inject the decorator to your stories.
From the error it seems you have `"noUnusedLocals": false,` is your tsconfig file.

You can turn this config off in your tsconfig file(_not recommended_) 
or
You can overwrite your config just for storybooks like this:

```javascript
config.module.rules.push({
    test: /\.(ts|tsx)$/,
    loaders: [
      {
        loader: require.resolve('awesome-typescript-loader'),
        options: {
          noUnusedLocals: false,
        },
      },
    ],
  });

  config.module.rules.push({
    test: /\.(tsx)$/,
    loaders: [
      {
        loader: require.resolve('@storybook/source-loader'),
        options: {
          parser: 'typescript',
          prettierConfig: {
            semi: true,
            singleQuote: true,
            jsxSingleQuote: false,
            useTabs: false,
            tabWidth: 2,
            trailingComma: 'all',
            printWidth: 80,
            arrowParens: 'always',
          },
        },
      },
    ],
    enforce: 'pre',
  });
```

**Comment by Amay88** [comment]
So the problem still exists. Is there any idea how to fix it or maybe somebody is working on it? It would be nice **not** to disable `noUnusedLocals` in tsconfig file just because of that...

**Comment by Uyarn** [comment]
> So the problem still exists (version 5.2.8). Is there any idea how to fix it or maybe somebody is working on it? It would be nice **not** to disable `noUnusedLocals` in tsconfig file just because of that...

Hey @Amay88 , the workaround doesn't mean to set `noUnusedLocals` in `tsconfig` file. You should set `noUnusedLocals` to be disabled in the options of `awesome-typescript-loader` and you can see my code in the image below.
![image](https://user-images.githubusercontent.com/26377630/73904753-ff807a80-48d7-11ea-8109-8e7ffe6932e6.png)
Good luck :)
