### ISSUE TITLE
Can't access styled-components theme in stories

### ISSUE THREAD

**Issue by daviddelusenet** [storybookjs/storybook#8531]
**Describe the bug**
I'm using `styled-components` in combination with `@storybook/react`. I'm wrapping all my stories in the SC `ThemeProvider` like this:

```jsx
addDecorator((storyFn) => (
    <ThemeProvider theme={themeBasic}>
        {storyFn()}
    </ThemeProvider>
));
```

This works fine and all of my Styled Components have access to the theme. However, I also want to access the theme in my stories:

```jsx
import { ThemeContext } from 'styled-components';

export const Configurable = () => {
    const theme = useContext(ThemeContext);
    console.log(theme); // undefined

    return (
        // Some React stuff here
    );
};
```

Shouldn't this be working?

**System:**
```
Environment Info:

  System:
    OS: macOS 10.15
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.12.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 78.0.3904.70
    Firefox: 69.0.3
    Safari: 13.0.2
  npmPackages:
    @storybook/addon-actions: ^5.2.5 => 5.2.5
    @storybook/addon-backgrounds: ^5.2.5 => 5.2.5
    @storybook/addon-info: ^5.2.5 => 5.2.5
    @storybook/addon-knobs: ^5.2.5 => 5.2.5
    @storybook/react: ^5.2.5 => 5.2.5
```

**Comment by daviddelusenet** [comment]
So any update on this issue? Does someone need additional information or something?

**Comment by shilman** [comment]
nope. there are over 400 issues in storybook and not many people to answer. hopefully somebody with styled components experience can answer. i know this repo uses it, so maybe check what they're doing here: https://github.com/storybookjs/frontpage

**Comment by EdenTurgeman** [comment]
@daviddelusenet We inject it with a wrapper component that wraps all our stories

**Comment by daviddelusenet** [comment]
tWhat do you mean @EdenTurgeman ? Isn't that the point of the `ThemeProvider`?

**Comment by kylesuss** [comment]
Hi @daviddelusenet 👋  -- please see this example:

https://github.com/kylesuss/styled-components-storybook-theme-example/blob/89f2193bb87f208a351b47b107c0eba1beb96b49/src/index.stories.js

You can do what you need to do, but you need another component to do it -- you can't just put the `useContext` stuff in the component story function. Why? Not sure exactly to be honest. Maybe somebody with a bit more knowledge on that can chime in here.

**Comment by daviddelusenet** [comment]
@kylesuss thanks, your suggestion eventually led me to a solution. I had the following story:

```jsx
export const Configurable = () => {
    const colors = getColorsFromTheme(themeBasic, colorKeys);

    return (
        <div
            style={{
                color: select('Color', colors, colors['colorHeaderText-primary']),
                fontSize: select('Size', {
                    XSMALL: '12px',
                    SMALL: '16px',
                    MEDIUM: '20px',
                    LARGE: '24px',
                    XLARGE: '28px',
                    XXLARGE: '32px',
                }, '24px'),
            }}
        >
            <Icon type={select('Type', Icon.types, Icon.types.CALENDAR)} />
        </div>
    );
};
```

I wanted to dynamically get the colors from the selected theme, it's now hardcoded as you can see. By rewriting my story to this I could get it working:

```jsx
const ConfigurableStory = () => {
    const theme = useContext(ThemeContext);
    const colors = getColorsFromTheme(theme, colorKeys);

    console.log(theme); /* <-- this works */

    return (
        <div
            style={{
                color: select('Color', colors, colors['colorHeaderText-primary']),
                fontSize: select('Size', {
                    XSMALL: '12px',
                    SMALL: '16px',
                    MEDIUM: '20px',
                    LARGE: '24px',
                    XLARGE: '28px',
                    XXLARGE: '32px',
                }, '24px'),
            }}
        >
            <Icon type={select('Type', Icon.types, Icon.types.CALENDAR)} />
        </div>
    );
};

export const Configurable = () => (
    <ConfigurableStory />
);
```

**Comment by daviddelusenet** [comment]
Nevermind, this doesn't work.

The `theme` is now available but all of the knobs are broken.

**Comment by javierbrea** [comment]
I don't really understand why, but it seems like "wrapping" the story with another component works:

> This does not work, it throws an error "theme.spacing is not defined":

```jsx
const useStyles = makeStyles(theme => {
  return {
    fooClass: {
      padding: theme.spacing(4)
    }
  };
});

export const fooStory = () => {
  const classes = useStyles();
  return (
    <Paper className={classes.fooClass}>
      Foo content
    </Paper>
  );
};
```

> But, converting the story into a component, and exporting another component that simply renders the first one, does work:

```jsx
const useStyles = makeStyles(theme => {
  return {
    fooClass: {
      padding: theme.spacing(4)
    }
  };
});

const FooStory = () => {
  const classes = useStyles();
  return (
    <Paper className={classes.fooClass}>
      Foo content
    </Paper>
  );
};

export const fooStory = () => (
  <FooStory />
);
```
This is not the ideal scenario, and I'd like to know why, but at least it works, and I think it is an admissible workaround until this issue is fixed, and could provide a clue about how to solve it definitively.

I have my Theme Provider defined as a global decorator:

```jsx
import React from "react";

import { addDecorator } from "@storybook/react";

import { makeDecorator } from "@storybook/addons";

import CssBaseline from "@material-ui/core/CssBaseline";
import { ThemeProvider } from "@material-ui/core/styles";
import { muiTheme } from "src/theme";

const withMuiTheme = storyFn => {
  return (
    <ThemeProvider theme={muiTheme}>
      <CssBaseline />
      {storyFn()}
    </ThemeProvider>
  );
};

const muiThemed = makeDecorator({
  name: "mui-theme",
  wrapper: withMuiTheme
});

addDecorator(muiThemed);
```

**Comment by Portals** [comment]
I'm having some similiar unexplainable issue accessing my redux provider. I have a decorator that wraps every story with the <Provider> from redux, but I cannot use useDispatch since it cannot find the Provider.

**Comment by pocka** [comment]
I guess this issue is the same as https://github.com/storybookjs/storybook/issues/8426.
If so, [this](https://github.com/storybookjs/storybook/issues/8426#issuecomment-542240804) could solve your problem. (NOTE: I didn't test the code.)

```js
// Using StoryFn as component instead of invoking it
addDecorator(StoryFn => (
    <ThemeProvider theme={themeBasic}>
        <StoryFn/>
    </ThemeProvider>
));
```

**Comment by agusburgos** [comment]
Hello @daviddelusenet , i have a working approach on my app using `vue-styled-components` and knobs as well.

You have to create a decorator and pass the knobs properties.
This worked for me:

> In theme-decorator.js:

```
import { ThemeProvider } from 'vue-styled-components';
import { customTheme } from "custom-theme";

import { withKnobs } from '@storybook/addon-knobs';

export default (story, context) => {
  // Decorated with story-function
  const WrapButton = story();
  const storyWithKnobs = withKnobs(story, context);
  
  return {      
    ...storyWithKnobs,
    
    components: { ThemeProvider, WrapButton },

    props: {
      ...storyWithKnobs.props,
    },
    
    template: `<theme-provider :theme="themeKnob"><wrap-button/></theme-provider>`,
    data() {
      return { themeKnob: customTheme }
    }
  };
};
```

> In config.js:

```
import { withTheme } from './theme-decorator';

addDecorator(withTheme);
```

I based my solution on this closed PR https://github.com/storybookjs/storybook/issues/2962 but i wasn't able to add the select to change the props.

I hope this helps!

**Comment by semoal** [comment]
Feel free to give a try to an addon I've built.
It supports also changing the background-color of the storybook (to simulate a real theming experience)

https://github.com/semoal/themeprovider-storybook

**Comment by glocore** [comment]
According to the latest docs (v5.3), you need to add a global decorator in `.storybook/preview.js`:

```javascript
import React from "react";
import { addDecorator } from '@storybook/react';
import { ThemeProvider } from "styled-components";
import theme from "../src/theme";

addDecorator(storyFn => <ThemeProvider theme={theme}>{storyFn()}</ThemeProvider>)
```

https://storybook.js.org/docs/addons/introduction/#storybook-decorators

**Comment by PatFawbertMills** [comment]
How do you add decorators in line with the new v6.0 migration to the `main.js` file?

**Comment by shilman** [comment]
@PatFawbertMills you add it to `preview.js`.

In 5.3:
```js
import { addDecorator } from '@storybook/react';
addDecorator(myDecorator)
```

In 6.0:
```js
export const decorators = [myDecorator];
```

**Comment by mushinz** [comment]
> According to the latest docs (v5.3), you need to add a global decorator in `.storybook/preview.js`:
> 
> ```js
> import React from "react";
> import { addDecorator } from '@storybook/react';
> import { ThemeProvider } from "styled-components";
> import theme from "../src/theme";
> 
> addDecorator(storyFn => <ThemeProvider theme={theme}>{storyFn()}</ThemeProvider>)
> ```
> 
> https://storybook.js.org/docs/addons/introduction/#storybook-decorators

This was a life saving

**Comment by SamSverko** [comment]
> I guess this issue is the same as #8426.
> If so, this could solve your problem. (NOTE: I didn't test the code. Just saw [the workaround](https://github.com/storybookjs/storybook/issues/8426#issuecomment-542240804).)
> 
> ```js
> // Using StoryFn as component instead of invoking it
> addDecorator(StoryFn => (
>     <ThemeProvider theme={themeBasic}>
>         <StoryFn/>
>     </ThemeProvider>
> ));
> ```

This worked for me! Thank you so much, it was driving me crazy!

**Comment by joaogarin** [comment]
In version 6 I managed to do this by adding the theme to the args property that is passed to all components : 

```tsx
import theme from './../theme.tsx';
const withThemeProvider = (Story, context) => {
  // Pass the theme to all story args.
  context.args = { ...context.args, ...{ theme } };
  return (
    <ThemeProvider theme={theme}>
      <>
        <div>
          <GlobalStyle />
          <AppGlobalStyle />
          <Story {...context} />
        </div>
      </>
    </ThemeProvider>
  );
};
export const decorators = [withThemeProvider];
```

This way in a story I can grab the theme like this : 

```tsx
export const NavbarBox = ({ theme }) => {
  return (
    <Navbar>
      <img src={theme.logo} alt="Logo" title="Logo" />
      <div>
        <MenuLink>Home</MenuLink>
        <MenuLink>My CV</MenuLink>
        <MenuLink>Jobs</MenuLink>
        <MenuLink>Companies</MenuLink>
      </div>
    </Navbar>
  );
};
NavbarBox.story = {
  title: 'Header'
};
export const NavbarBox = ({ theme }) => {
  return (
    <Navbar>
      <img src={theme.logo} alt="Logo" title="Logo" />
      <div>
        <MenuLink>Home</MenuLink>
        <MenuLink>My CV</MenuLink>
        <MenuLink>Jobs</MenuLink>
        <MenuLink>Companies</MenuLink>
      </div>
    </Navbar>
  );
};
NavbarBox.story = {
  title: 'Header'
};
```

Main use case for me is that I am using the same storybook and shipping to many clients and some of the branding I want to have in the stories (e.g. logo in this story should adapt to whatever logo set in the theme object

**Comment by yareyaredesuyo** [comment]
storybook 6 version

```js
import { ThemeProvider } from "styled-components";
import { Defaultheme } from "../src/components/themes"; 
const themeDecorator = storyFn => <ThemeProvider theme={Defaultheme}>{storyFn()}</ThemeProvider>
export const decorators = [themeDecorator];
```

**Comment by ncesar** [comment]
> storybook 6 version(preview.js)
> 
> ```js
> import { ThemeProvider } from "styled-components";
> import { Defaultheme } from "../src/components/themes"; 
> const themeDecorator = storyFn => <ThemeProvider theme={Defaultheme}>{storyFn()}</ThemeProvider>
> export const decorators = [themeDecorator];
> ```

haha thanks a lot :)

**Comment by mszczepanczyk** [comment]
Another thing that's easy to miss that I've just spent more time on than I'd like to admit.

Remember to import **the same** piece of code for your context and context provider in stories and storybook config. Otherwise the provider inside a global decorator will not come from the same context as consumers in your stories. 

```diff
-import { ThemeProvider } from '../dist';
+import { ThemeProvider } from '../src';

export const decorators = [
  (Story, context) => {
    return (
      <ThemeProvider>
        <Story {...context} />
      </ThemeProvider>
    );
  },
];
```

**Comment by brendonco** [comment]
how does it work for storybook v8?

Created an issue here:
https://github.com/storybookjs/storybook/issues/26693

**Comment by araphiel** [comment]
I ran into a few related issues I was able to resolve working with storybook 8.


1. The `decorators` array is processed in reverse (similar to webpack rules)

2. As of `storybook@v8.3.5`, you need to use individual property exports to properly apply the styled component theme provider.

```ts
// 🚫 avoid using this
export const preview: Preview = {
 decorators: [...]
}

// ✅ this works well
export const decorators: Preview['decorators'] = [...];
```

Need to confirm but I have a feeling there may also be an additional resolution conflict between storybook's emotion `ThemeProvider` and your styled-component's one.
