### ISSUE TITLE
Addon-docs: Support JSDoc params to describe the signature of a function in the props table

### ISSUE THREAD

**Issue by patricklafrance** [storybookjs/storybook#8532]
**Is your feature request related to a problem? Please describe.**
I would like to be able to define the signature of my function in description column of the props table.

I love how it's done in [Semantic UI React documentation](https://react.semantic-ui.com/modules/dropdown/)

![image](https://user-images.githubusercontent.com/794579/67397528-48096780-f577-11e9-8024-7e8a7a8a98ed.png)

This is define with JSDoc:

```
    /**
     * Called on blur.
     *
     * @param {SyntheticEvent} event - React's original SyntheticEvent.
     * @param {object} data - All props.
     */
    onBlur: PropTypes.func,
```

This doesn't seem to be a native feature of react-docgen. I made a quick test on the [playground](https://reactcommunity.org/react-docgen/) and I get the following:

```
    "bar": {
      "type": {
        "name": "custom",
        "raw": "function(props, propName, componentName) {\n  // ...\n}"
      },
      "required": false,
      "description": "Description of prop \"bar\" (a custom validation function).\n@param {SyntheticEvent} event - Test",
      "defaultValue": {
        "value": "21",
        "computed": false
      }
    },
```

I guess they somehow parse the JSDoc in the description prop.

**Comment by patricklafrance** [comment]
Any tips on how to implement this @layershifter ?

**Comment by layershifter** [comment]
@patricklafrance we have there the additional processing of results from `react-docgen` to get more descriptive types. We also parse JSDoc with `doctrine` (it's deprecated, BTW, sic!) to parse tags: https://github.com/Semantic-Org/Semantic-UI-React/blob/master/gulp/plugins/util/parseDocblock.js

**Comment by anwalkers** [comment]
@layershifter Take a look at the Typedoc project for inspiration. They have done great work generating static docs. 

https://typedoc.org/

**Comment by patricklafrance** [comment]
Thank you very much @layershifter !

**Comment by patricklafrance** [comment]
It could be done in a lot of ways, here's 2 option:

### Render the function signature in the description column. 

This is similar to the screenshot above.

The main advantages of this implementation is space:

`+`
- The function parameters description can be rendered
- Most of the time, the signature will fit on a single line

`-`
- It might be counter intuitive to have the function signature in the description column instead of the type column.

### Render the function signature in the type column. 

`+`
- Intuitive

`-`
- Currently the type column doesn't take much space since most of types name are short. A function signature tends to be quite wide. Most of the time. the type column will either get very large or truncate the function signature on multiple lines.
- The function parameters description cannot be rendered

What do you think @shilman ?

**Comment by shilman** [comment]
@patricklafrance Currently, the prop type is rendered in the `Description` column, which indeed is more compact. I think we should keep it that way, since the full design (which is not yet implemented) also has a "knob" column to edit the prop value, and it starts to get crowded as we add more columns.

@domyen this is your design -- anything to add?

**Comment by patricklafrance** [comment]
That make sense!

**Comment by domyen** [comment]
Description column makes sense to me. We can make further layout
optimizations when more people start using it.

**Comment by shilman** [comment]
Ooh-la-la!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-alpha.36 containing PR #8660 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by patricklafrance** [comment]
Still need to add the params and returns optionnal description under the func type.

Working on it now!

**Comment by shilman** [comment]
w00t!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-alpha.41 containing PR #8702 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by Losses** [comment]
@shilman This feature is not work with the combination of TypeScript + React + tsdocs, any idea about this?

**Comment by shilman** [comment]
@Losses there are two different codepaths, one for `react-docgen-typescript-loader` (the recommended 5.3 setup) and one for `babel-plugin-react-docgen` (the recommended 6.0 setup). i'm guessing @patricklafrance fixed this for the former but not the latter.

More info: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#rolling-back

**Comment by Losses** [comment]
@shilman I should open a new issue or just reopen this issue?

**Comment by shilman** [comment]
Related: #10311

**Comment by Losses** [comment]
> Related: #10311

Cool!
