### ISSUE TITLE
Addoc-docs: Support multi-line description for props table

### ISSUE THREAD

**Issue by patricklafrance** [storybookjs/storybook#8533]
**Is your feature request related to a problem? Please describe.**
I defined the following prop type:

```
/**
* Whether or not the calendar should close when a click is made outside the date picker.
* Requires `closeOnBlur` to be false.
*/
closeOnOutsideClick: bool,
```

I would expect the line break to be honored. Instead I get:

![image](https://user-images.githubusercontent.com/794579/67399451-455c4180-f57a-11e9-8b9e-4d2d3e633a31.png)

**Describe the solution you'd like**
I would expect the line breaks to be honored.

```
Whether or not the calendar should close when a click is made outside the date picker.
Requires `closeOnBlur` to be false.
```

**Comment by shilman** [comment]
If description supported markdown, per https://github.com/storybookjs/storybook/issues/8534, then you could use markdown formatting (e.g. `<br/>`, or maybe there's another force-break construct) to achieve what you're looking for, right?

**Comment by patricklafrance** [comment]
Closing this in favor of using markdown format.

For more info view @shilman comments in https://github.com/storybookjs/storybook/pull/8703
