### ISSUE TITLE
Addon-docs: Support code format in the description column of the props table

### ISSUE THREAD

**Issue by patricklafrance** [storybookjs/storybook#8534]
**Is your feature request related to a problem? Please describe.**
Add support for code format in the description column of the props table.

**Describe the solution you'd like**
I would like to have "Requires `closeOnBlur` to be false" rendered with code format in the props table

**Comment by shilman** [comment]
@patricklafrance Would markdown be sufficient?

**Comment by patricklafrance** [comment]
Yes that would even be better!

**Comment by patricklafrance** [comment]
@shilman I dont think this issue is still relevant since you introduce markdown in the description column.

I'm I right?

**Comment by patricklafrance** [comment]
I added a story to the PropRow stories to showcase the new markdown feature.

**Comment by shilman** [comment]
Correct. Closing!!
