### ISSUE TITLE
Identifier has already been declared 

### ISSUE THREAD

**Issue by psamusev** [storybookjs/storybook#8536]
**Describe the bug**
When I'm trying to write a story in `.mdx` format, I'm getting an error 
`Identifier has already been declared `. I noticed that it happen only in case when the story file contains both import variable's name and story name in similar form

**To Reproduce**
Please take a look at the code section for `*.mdx` file example

Since `import multimediaImage` and name in story `multimedia-image` will be translated to same global name scope (As I understood) I'm getting the error `Identifier 'multimediaFigure' has already been declared`

**Expected behavior**
Import variable names shouldn't depend on the story name

**Code snippets**
```
import {
  Meta,
  Story,
  Preview
} from "@storybook/addon-docs/blocks";

import multimediaImage from './multimedia-image.html';

<Meta title="Test" />

### Image

<Preview>
  <Story height="720px" name="multimedia-image">
    {multimediaImage}
  </Story>
</Preview>
```

**System:**

```
Environment Info:

  System:
    OS: macOS 10.15
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  Binaries:
    Node: 10.15.1 - ~/.nvm/versions/node/v10.15.1/bin/node
    npm: 6.12.0 - ~/.nvm/versions/node/v10.15.1/bin/npm
  Browsers:
    Chrome: 77.0.3865.120
    Firefox: 69.0
    Safari: 13.0.2
  npmPackages:
    @storybook/addon-a11y: ^5.2.3 => 5.2.3 
    @storybook/addon-actions: ^5.2.3 => 5.2.3 
    @storybook/addon-docs: ^5.2.3 => 5.2.3 
    @storybook/addon-links: ^5.2.3 => 5.2.3 
    @storybook/html: ^5.2.3 => 5.2.3 
```

**Comment by shilman** [comment]
Yeah the MDX compiler turns the code into Component Story Format and injects a named export that is the camel-case of the story name, which in this case collides with the imported variable. The compiler should be a little smarter.

In the meantime you can work around by renaming the story or by renaming the import...
