### ISSUE TITLE
MDX Addon-docs: source color scheme are different from CHF mode

### ISSUE THREAD

**Issue by lorenzomigliorero** [storybookjs/storybook#8537]
Source color scheme are different between **MDX** and **CHF** mode.
After investigation, i noticed that the `dark` prop is missing [here](https://github.com/storybookjs/storybook/blob/next/addons/docs/src/blocks/DocsContainer.tsx#L33) and [here](https://github.com/storybookjs/storybook/blob/next/addons/docs/src/blocks/Source.tsx#L79).

**Comment by shilman** [comment]
I think this has been fixed
