### ISSUE TITLE
Storybook Not Remembering View Tab

### ISSUE THREAD

**Issue by sanchez** [storybookjs/storybook#8547]
**Describe the bug**
If I am viewing a story in the "Canvas" tab and switch to a documentation page the tab is changed to "Docs" but when I go back to the story the tab remains on "Docs". Previously I had experience it switching back and I was wondering if this feature can be added back? Thanks!

**To Reproduce**
1. Fire up storybook
2. Navigate to a document page with no stories
3. Read the beautiful documentation
4. Decide you wanna view a story page
5. Click said story page and notice you are still viewing blank documentation

**Expected behavior**
If I click on a story show the "Canvas" tab by default (or at least remember my past tab view)

**System:**
```
System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
  Binaries:
    Node: 12.0.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.12.1 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 41.16299.1004.0
```

**Comment by shilman** [comment]
@sanchez I think the old behavior was a bug. No plans to add that back at the moment...

**Comment by sanchez** [comment]
So for the use case where I want to have both documentation and examples/stories for the end-user, is there the ability for these tabs to automagically switch? Thanks
