### ISSUE TITLE
Prompt reader to add webpack config file in .storybook before the webpack config snippet

### ISSUE THREAD

**Issue by brightpixels** [storybookjs/storybook#8555]
**Is your feature request related to a problem? Please describe.**
The documentation on this page https://github.com/storybookjs/storybook/tree/master/addons/storysource doesn't explain that you need to add a webpack config file in .storybook. It took me a long time to understand this because I was initially trying to add it to the create-react-app root and using rewired.

**Describe the solution you'd like**
Before showing the snippet of the webpack config, prompt reader to add `webpack.config.js` to `.storybook`, if it doesn't already exist.

**Describe alternatives you've considered**
N/A

**Are you able to assist bring the feature to reality?**
Yes

**Additional context**
N/A

**Comment by shilman** [comment]
We're moving to using a preset instead, which should be easier: https://github.com/storybookjs/storybook/tree/next/addons/storysource#install-using-preset

**Comment by brightpixels** [comment]
When? next version?

**Comment by shilman** [comment]
Yeah already available in 5.3-alpha
