### ISSUE TITLE
Storybook/angular uses wrong tsconfig for TsconfigPathsPlugin

### ISSUE THREAD

**Issue by artaommahe** [storybookjs/storybook#8556]
**Describe the bug**
Tsconfig file path, using by storybook/angular TsconfigPathsPlugin [here](https://github.com/storybookjs/storybook/blob/2ebcb6c41b23e6f09b6b9db96bfcb38ca30a83ca/app/angular/src/server/angular-cli_config.ts#L148), is
1. taken from angular.json config and ignores `.storybook/tsconfig.json`
2. even that one from angular.json is wrong and is related to another application in workspace (app1 instead of app2 in example repo)

console.log of [cliWebpackConfigOptions.buildOptions.tsConfig](https://github.com/storybookjs/storybook/blob/2ebcb6c41b23e6f09b6b9db96bfcb38ca30a83ca/app/angular/src/server/angular-cli_config.ts#L148) shows
```
projects/app1/tsconfig.json
```
despite we're running storybook for app2 and have a `projects/app2/.storybook/tsconfig.json` file

**To Reproduce**
1. clone https://github.com/artaommahe/storybook-tsconfigpaths
2. `yarn install`
3. `yarn start-storybook -c projects/app2/.storybook`
4. see an error
```
ERROR in ./projects/app2/src/app/app.component.ts
Module not found: Error: Can't resolve '@app2/test-module/const' in 'D:\projects\tests\storybook-tsconfigpaths\projects\app2\src\app'    
 @ ./projects/app2/src/app/app.component.ts 3:0-53 6:21-31
```
5. uncomment in [webpack.config.js](https://github.com/artaommahe/storybook-tsconfigpaths/blob/master/projects/app2/.storybook/webpack.config.js)
6. `yarn start-storybook -c projects/app2/.storybook`
7. storybook started

**Expected behavior**
Proper tsconfig path resoltion that respects `.storybook/tsconfig.json` existing

@storybook/angular@^5.2.5

**Comment by gaetanmaisse** [comment]
As @artaommahe well said, until now, when starting SB `ts-loader` uses `tsconfig.json` from SB config folder and TsconfigPathsPlugin webpack plugin is using `tsconfig.json` related to the main project of `angular.json` file.

I made a commit on a branch to use `tsconfig.json` from SB config folder if it has one `tsconfig.json` (and it should) and fallback to `angular.json` related one if it doesn't https://github.com/storybookjs/storybook/commit/686422787c9b397872fee86b5f7e986fe2b9c06c

As we are not using the same `tsconfig.json` file as before, TS compiler throws new errors and I don't know how to fix them for now.

An other interesting point is that we are continuing to use loaders from projects of `angular.json` file for styles and CLI related, it's done with `@angular-devkit/build-angular` here: inhttps://github.com/storybookjs/storybook/blob/b84559e40dc063d06041ccbccb78554e9ca8a5bc/app/angular/src/server/angular-cli_config.js#L109

@kroeder @ndelangen can you take a look at my commit and tell me if it's ok to do something like I did and if you have any idea about the direction we should follow about SB x Angular with multiple (sub) projects?

**Comment by ndelangen** [comment]
This is too deep into ts + angular land for me to make a judgement on I'm afraid. I'd trust @kroeder's expertise.

**Comment by artaommahe** [comment]
@stale nope :/

**Comment by CodeByAlex** [comment]
Bump

**Comment by ThibaudAV** [comment]
@artaommahe is the problem still relevant?

have you seen these lines: https://github.com/storybookjs/storybook/blob/next/app/angular/src/server/angular-cli_config.ts#L76-L84 ? 

I'm not sure about me 🙈  :
as in the example you give the defaultProject is app1 in angular.json
I think you should run storybook cmd with STORYBOOK_ANGULAR_PROJECT 
 : `STORYBOOK_ANGULAR_PROJECT=app2 yarn start-storybook -c projects/app2/.storybook`

`STORYBOOK_ANGULAR_PROJECT` has been added more recently as this issue may solve it 🤷‍♂️

**Comment by artaommahe** [comment]
@ThibaudAV yes, it is. Look here
https://github.com/storybookjs/storybook/blob/0c21c460309b332c0f49fdbe3972ff1b7907eb09/app/angular/src/server/angular-cli_config.ts#L205
it uses project's tsconfig file, but ignores the `.storybook/tsconfig.json` one

**Comment by mhulse** [comment]
I can't tell for sure, but I can't seem to get my `.storybook/tsconfig.json` to work. I'll be interested to see if anyone has a fix?

**Comment by covationlabs** [comment]
Same issue for us as well

**Comment by mandarini** [comment]
I'm having the same issue on a Nx workspace. If I have a root level `tsconfig.json` file, Storybook uses that and ignores the `.storybook/tsconfig.json`. Is there a way to force Storybook to use a tsconfig.json at a specific path? @gaetanmaisse

**Comment by EloB** [comment]
@mandarini Haven't tried it but someone claims that this should work.
https://stackoverflow.com/a/69040674

**Comment by valentinpalkovic** [comment]
It should be fixed in Storybook 7. Please feel free to reopen the issue if it is still a problem. Closing for now.
