### ISSUE TITLE
Add ability to document typesets in different units

### ISSUE THREAD

**Issue by ezhikov** [storybookjs/storybook#8568]
**Is your feature request related to a problem? Please describe.**
We using rem units in our typography and would like to document it with addon-docs. Right now Typeset component accepts numbers in pixels to show those sizes. If we provide rem units, it works correctly, except for size itself - it shows `rempx`

**Describe the solution you'd like**
It would be great to accept not only numbers, but strings with units. Since it already works, it should take single `isNaN` check to determine if it should append `px` or leave as is. Also types should be changed.

**Describe alternatives you've considered**
We can make our own component for Typesets, if you not willing to accept this proposal

**Are you able to assist bring the feature to reality?**
yes, I can... I just need guidance on codebase and tests.

**Additional context**

This code:
```jsx
<Typeset fontSizes={[16, '1rem']} />
```

Gives us this result:
![image](https://user-images.githubusercontent.com/4413493/67555178-77f07080-f719-11e9-8a50-3c31f1cb41c5.png)

And this is _almost_ desirable result

**Comment by ezhikov** [comment]
Array of strings is good, but it will be breaking change, since there is explicit typings with numbers.

**Comment by shilman** [comment]
I see. It's an undocumented component anyway, so I think it's fine if we break the API. cc @domyen

**Comment by ezhikov** [comment]
Anyway, I'd like to make necessary changes if it's ok.

**Comment by domyen** [comment]
Absolutely, definitely open to a PR!

**Comment by shilman** [comment]
Yippee!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-alpha.30 containing PR #8574 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
