### ISSUE TITLE
Change background color of canvas in single story

### ISSUE THREAD

**Issue by RobbertWolfs** [storybookjs/storybook#8570]
Is it possible to change the background color of the canvas for a single story??

Because we have like a component with two states... a dark one and a light one..
The dark one is visible 

![image](https://user-images.githubusercontent.com/12511178/67559863-0bc23c80-f71a-11e9-9a87-8e191b90cbb3.png)

But our light version is not visible on the light grey background...

![image](https://user-images.githubusercontent.com/12511178/67559894-18df2b80-f71a-11e9-83d2-d073eaf86922.png)

So it would be nice if we can set the background color of our canvas for a single story.. Something like this: 

![image](https://user-images.githubusercontent.com/12511178/67559977-3ca27180-f71a-11e9-9f50-b0721b80de0c.png)

**Comment by RobbertWolfs** [comment]
Or another possible solution would be to know in what theme I am using a HTLM class or somthing, because you can create a custom theme but I didn't found if it was possible to change the canvas color.. Only the items around it 👎 

If our HTML uses a custom class for a specific theme than I maybe can use this class to overwrite it:
`.sb-show-main` because this is the class that sets the background...

So if I know what theme it is I maybe can do something like this to overwrite it:
``` css
.storybook-dark-theme .sb-show-main {
    background-color: hotpink;
} 
```

**Comment by lukasluecke** [comment]
If it's only for a subset of stories the easiest way would probably be to use a custom `decorator` that wraps it with an element that has the correct `background-color`.

**Comment by sbussard** [comment]
I tried toggling a CSS class on the body when certain components mount. 
They don't seem to unmount though, because the class doesn't get removed when I got to the next story.

**Comment by sbussard** [comment]
Slightly related -- here's a SCSS mixin I'm using to generate a light and dark checkerboard pattern

```
@mixin checkers($size: 50px, $contrast: 0.07, $lightOverlay: false) {
  $angle: 45deg;
  $tp: 25%;
  $checkerColor: rgba(#000, $contrast);

  @if ($lightOverlay == true) {
    $checkerColor: rgba(#fff, $contrast);
  }

  background-image: linear-gradient($angle, $checkerColor $tp, transparent $tp),
    linear-gradient(-$angle, $checkerColor $tp, transparent $tp),
    linear-gradient($angle, transparent 3 * $tp, $checkerColor 3 * $tp),
    linear-gradient(-$angle, transparent 3 * $tp, $checkerColor 3 * $tp);
  background-size: $size $size;
  background-position: 0 0, 0 $size/2, $size/2 -1 * $size/2, -1 * $size/2 0;
}
```

**Comment by winterlamon** [comment]
@RobbertWolfs Not sure if you've already figured it out, but sharing just in case. If you're using CSF, you can set the background for a single story using the `story` object like this:
```
keypadLight.story = {
  name: 'light',
  parameters: {
    background: [
      { name: 'dark background', value: '#000', default: true }
    ]
  }
}
```

**Comment by PhilippeMorier** [comment]
In Storybook `v6.5.9` after reading [backgrounds - extending-the-configuration](https://storybook.js.org/docs/react/essentials/backgrounds#extending-the-configuration) I ended up setting the `parameters` like this:

```typescript
export default {
  title: 'MyComponent',
  parameters: {
    backgrounds: { default: 'dark' },
  },
} as Meta<MyComponent>;
```
