### ISSUE TITLE
Addon-Docs: MDX Story only renders first child

### ISSUE THREAD

**Issue by json2d** [storybookjs/storybook#8571]
**Describe the bug**
The `Story` component in MDX only renders first child. 

**To Reproduce**
using these package versions:
- `@storybook/react@5.2.5`
- `@storybook/addon-docs@5.2.5`

1. Add this into an MDX file
```jsx
<Preview>
  <Story name="hello">
    <p>Hello Child #1</p>
    <p>Hello Child #2</p>
  </Story>
</Preview>
```
2. See error in the rendered preview

**Expected behavior**
expected to see both `<p>Hello Child #1</p>` and `<p>Hello Child #2</p>` rendered

**Screenshots**
![image](https://user-images.githubusercontent.com/143295/67611104-3c7b9380-f765-11e9-9b52-72a0890113b7.png)

**Additional context**
wrapping the children in a  `Fragment` works fine - eg:
```jsx
<Preview>
  <Story name="hello-2">
    <>
      <p>Hello Child #1</p>
      <p>Hello Child #2</p>
    </>
  </Story>
</Preview>
```

**Comment by hasparus** [comment]
I'd like to bump this.

Multiple children of story crash for me at 5.3.3 with `SyntaxError: Unexpected token` and I'd love to drop fragments on the picture below.

![image](https://user-images.githubusercontent.com/15332326/72519841-7934c380-3858-11ea-8082-2035896e0217.png)

**Comment by shilman** [comment]
Thanks @hasparus good call. Any interest in creating a PR for this?

**Comment by shilman** [comment]
Huzzah!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-beta.2 containing PR #9531 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
