### ISSUE TITLE
Addon-docs: Canvas-only story are available in the navigation menu even with --docs only

### ISSUE THREAD

**Issue by patricklafrance** [storybookjs/storybook#8587]
**Describe the bug**
This is related to https://github.com/storybookjs/storybook/issues/7837

I disabled a story with:

```
{
   docs: {
      disable: true
   }
}
```

It works fine, the story is not visible anymore in the docs.

However the story is still available in the navigation menu and is clickable.

**Expected behavior**
A disable story should not be available in the navigation menu when the site is built using the `--docs` flag.

**Screenshots**
![image](https://user-images.githubusercontent.com/794579/67637061-342e7000-f8ad-11e9-8c54-5e1cae7891b6.png)

**System:**
I am using the following packages:

```
        "@storybook/addon-docs": "5.3.0-alpha.31",
        "@storybook/react": "5.3.0-alpha.31",
```

**Comment by shilman** [comment]
@patricklafrance I think this is the fix for this: https://github.com/storybookjs/storybook/pull/7700

What do you think? I'll try to revive it this week.

**Comment by patricklafrance** [comment]
That would do it!

I will also kind of fix https://github.com/storybookjs/storybook/issues/8520 and https://github.com/storybookjs/storybook/issues/8286 for `--docs`

**Comment by patricklafrance** [comment]
One think thought, will we still be able to link to an anchor within the page?

**Comment by patricklafrance** [comment]
Fix by https://github.com/storybookjs/storybook/pull/7700
