### ISSUE TITLE
Script tag does not execute in stories

### ISSUE THREAD

**Issue by DannyvanderJagt** [storybookjs/storybook#8593]
**Describe the bug**
When adding any kind of script (inline or src) to a story, it won't execute. 

I found different issues telling that this is by design, but for quite a few use-cases this is a problem. How can we make this work, or make it additional option to enable/disable script executions in stories?

I like storybook as it enables teams to do component-driven development a bit easier, but this only helps if storybook is as close as possible to a production environment. It doesn't make sense to implement extra stuff because of a technical design decision made by a tool.

**To Reproduce**
1. Setup storybook
2. Create a story, use `@storybook/html`
3. Add a script tag, like `<script type='text/javascript'>alert('Hello world!')</script>`
4. Open storybook in your browser, and see no alert.
5. The script in the source, but it won't execute.

**Expected behavior**
I would expect to see default browser behaviour. To see the script working as normal.

**Comment by kevinvanhove** [comment]
Hi, you have to use a React feature called useEffect(), see here: https://reactjs.org/docs/hooks-effect.html

**Your story**
`
import VideoBackground from './VideoBackground'
import { useEffect } from '@storybook/client-api';

export default {
	title: 'Design System/Molecule/Video',
}

export const Background = () => {
	
	let template = `

		<section>my component</section>

		`;

	useEffect(VideoBackground);
	return template;

}`

**Your VideoBackground.js file**

`
export default () => {

	(function () {

		console.log('hi', window)
		
	})();

};
`

**Comment by shilman** [comment]
Fixed here I believe: https://github.com/storybookjs/storybook/pull/12089
