### ISSUE TITLE
Possibility to mute logs

### ISSUE THREAD

**Issue by axhamre** [storybookjs/storybook#8595]
**Is your feature request related to a problem? Please describe.**
My logs are totally flooded with irrelevant info that hinders valuable info to be identified.

**Describe the solution you'd like**
Remove this messages prefixed with "message arrived at ..."

**Screenshot:**

<img width="600" alt="image" src="https://user-images.githubusercontent.com/1907343/67695686-c87bfe00-f9a5-11e9-831b-5f59adb27310.png">

**Comment by shilman** [comment]
@axhamre you should be able to filter those out in your browser by unselecting verbose logs

**Comment by axhamre** [comment]
@shilman Of course. Thank you!

**Comment by sdurham** [comment]
What if I want verbose logs from my own code though?

**Comment by shilman** [comment]
It's filtered out by default in 6.0: https://github.com/storybookjs/storybook/pull/10370
