### ISSUE TITLE
Addon-docs: Docs breaks emotion theming

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#8601]
Addon-docs is incompatible with component libraries that use emotion theming, since it uses emotion theming itself.

To fix this, we would need to hide Storybook's theme somehow.

As a workaround, you can set your stories to render in iframes in docs. In your `.storybook/config.js`:

```js
import { addParameters } from '@storybook/react';

addParameters({
  docs: {
    inlineStories: false,
    iframeHeight: '60px', // some default height
  }
});
```

**Comment by GitProdEnv** [comment]
Is there another solution to this? I have the same issue, where my component library is built with emotion. 

Accessing the theme within the styled components does not work, since the docs addon overwrites the theme.

I do the workaround as mentioned above. Any help appreciated

**Comment by shilman** [comment]
@GitProdEnv there's an open PR to replace Storybook's theming with a custom context to avoid conflicts. I'm hoping we can get that into 6.3.
