### ISSUE TITLE
[addon-viewport] TypeScript types missing

### ISSUE THREAD

**Issue by screendriver** [storybookjs/storybook#8611]
**Describe the bug**

The TypeScript types in `@storybook/addon-viewport` are not working because you are missing the [types](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#including-declarations-in-your-npm-package) field in your [package.json](https://github.com/storybookjs/storybook/blob/next/addons/viewport/package.json) is missing like it is in [knobs package.json](https://github.com/storybookjs/storybook/blob/next/addons/knobs/package.json#L27). So when you try something like `import { INITIAL_VIEWPORTS } from '@storybook/addon-viewport';` you get

```
Could not find a declaration file for module '@storybook/addon-viewport'. '/Users/me/project/node_modules/@storybook/addon-viewport/preview.js' implicitly has an 'any' type.
```

I tried to open a pull request but I was unsure because there is no `index.ts` in `addons/viewport/src/` and the `types` property should point to one. 

What I am doing in my project is `import { INITIAL_VIEWPORTS } from '@storybook/addon-viewport';` so that would mean to re-export everything from the `index.ts` file.

**To Reproduce**

Use TypeScript in your project and try to import `import { INITIAL_VIEWPORTS } from '@storybook/addon-viewport';`

**Expected behavior**

Should compile

**Screenshots**

**Code snippets**

**System:**

**Additional context**

**Comment by shilman** [comment]
@screendriver mind issuing a small PR for this?

**Comment by screendriver** [comment]
As I already wrote I tried to open a pull request but had some serious thoughts about it. Should I just re-export everything from a non-existent `index.ts`?

**Comment by shilman** [comment]
@kroeder @gaetanmaisse @ndelangen can you advise?

**Comment by gaetanmaisse** [comment]
I think a good option is to move `preview.js` in `addons/viewport/src/`, migrate it to TS and finally update both `main` and `types` in `package.json` to point to the new files, something like:
```
"main": "dist/preview.js",
"types": "dist/preview.d.ts",
```

This should not create breaking change and should also export TS types correctly :)
Are you ok with this solution @kroeder @ndelangen?

**Comment by shilman** [comment]
Whoopee!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-alpha.47 containing PR #8848 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
ZOMG!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.7 containing PR #8848 that references this issue. Upgrade today to try it out!
