### ISSUE TITLE
Notes - Giphy query not propagating

### ISSUE THREAD

**Issue by rblock-aw** [storybookjs/storybook#8620]
**Description**
When creating a note as stated in the [documentation](https://github.com/storybookjs/storybook/tree/master/addons/notes#giphy), the same Gif always renders. Some quick debugging showed me the addon is actually expecting a property named 'query', as can be seen in [giphty.tsx](https://github.com/storybookjs/storybook/blob/master/addons/notes/src/giphy.tsx). Changing the example from the documentation into
`<Giphy query='this works' />`
does seem to work.

**To Reproduce**
1. Install the Storybook Addon Notes
2. Create a note with an embedded Giphy
3. Look at the resulting gif and realise that it is always the same one, even if the 'gif' property is update (don't forget to reload Storybook after updating the property!).
4. Open the browser debugging window on the network tab, reload the story and notice that the 'search' request has an 'undefined' value as the 'q' parameter of the request.

**Expected behavior**
That the either the documentation states that the property is 'query' or that the 'gif' property propagates to the search request to Giphy.

**Code snippets**
Incorrect example:
`<Giphy gif='this does not work' />`
Correct example:
`<Giphy query='this does' />`

**System:**
Environment Info:

  System:
    OS: macOS 10.15
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 10.17.0 - /usr/local/opt/node@10/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/opt/node@10/bin/npm
  Browsers:
    Chrome: 78.0.3904.70
    Firefox: 65.0.1
    Safari: 13.0.2
  npmPackages:
    @storybook/addon-actions: ^4.1.0 || ^5.0.0 => 5.2.5 
    @storybook/addon-knobs: ^4.1.0 || ^5.0.0 => 5.2.5 
    @storybook/addon-links: ^4.1.0 || ^5.0.0 => 5.2.5 
    @storybook/addon-notes: ^4.1.0 || ^5.0.0 => 5.2.5 
    @storybook/addon-viewport: ^5.2.5 => 5.2.5

**Comment by shilman** [comment]
FYI, please take a look at Storybook Docs, which is intended to replace `addon-info` and `addon-notes`, may not have this problem, and is being more actively maintained: https://medium.com/storybookjs/storybook-docspage-e185bc3622bf

**Comment by rblock-aw** [comment]
Looks interesting! Thanks for the pointer!
