### ISSUE TITLE
Addon-docs: React component are not unmount when switching from "canvas" to "docs"

### ISSUE THREAD

**Issue by patricklafrance** [storybookjs/storybook#8622]
**Describe the bug**
React component are not unmount when switching from "canvas" to "tabs"

![docs_unmount](https://user-images.githubusercontent.com/794579/67791056-30395400-fa4d-11e9-884a-d6f44f94d7f6.gif)

Storybook: 5.3.0-alpha.31

**Comment by shilman** [comment]
ZOMG!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-alpha.41 containing PR #8625 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Yee-haw!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.6 containing PR #8625 that references this issue. Upgrade today to try it out!

**Comment by mokone91** [comment]
Exactly same bug with vue3 in v6.5.12
