### ISSUE TITLE
@storybook/addon-ondevice-knobs@5.2.5" has incorrect peer dependency "@storybook/addon-knobs@5.2.0-beta.13

### ISSUE THREAD

**Issue by Victorien-Tardif** [storybookjs/storybook#8634]
**Describe the bug**
@storybook/addon-ondevice-knobs@5.2.5 has incorrect peer dependency declared in package.json: https://github.com/storybookjs/storybook/blob/536a0bd5c793bf01f70273b5b8b83281e5acf13d/addons/ondevice-knobs/package.json#L41

**Expected behavior**
It should have the peer dependency @storybook/addon-knobs ~5.2.0 or something like that but should not complain if I have @storybook/addon-knobs@5.2.5 in any case.

**Comment by shilman** [comment]
Yay!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-alpha.35 containing PR #8643 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Olé!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.6 containing PR #8644 that references this issue. Upgrade today to try it out!

**Comment by Victorien-Tardif** [comment]
@storybook/addon-ondevice-knobs@5.2.6" has incorrect peer dependency "@storybook/addon-knobs@5.2.5" 

:/
