### ISSUE TITLE
[addon-knobs] Add `escapeHTML: false` option in documentation for React

### ISSUE THREAD

**Issue by clecrois** [storybookjs/storybook#8635]
**Is your feature request related to a problem? Please describe.**
I use knobs in a React project and encountered the issue of my inputs being escaped by default unless I specify `escapeHTML: false` in the knobs configuration.

**Describe the solution you'd like**
*"It's safe to set it to `false` with frameworks like React which do escaping on their side."* => Since it's safe not to escape inputs with `escapeHTML` in React, would it be possible to desactivate it in the [React example of addon-knobs documentation](https://github.com/storybookjs/storybook/tree/next/addons/knobs#with-react).

Replace :
```js
// in https://github.com/storybookjs/storybook/tree/next/addons/knobs#with-react
stories.addDecorator(withKnobs);
```
with
```js
// in https://github.com/storybookjs/storybook/tree/next/addons/knobs#with-react
stories.addDecorator(
  withKnobs({
      escapeHTML: false,
    })
);
```

**Are you able to assist bring the feature to reality?**
yes, I can add the lines above in the React example of the addon-knobs doc :)

**Comment by tysonmatanich** [comment]
+1
