### ISSUE TITLE
font size

### ISSUE THREAD

**Issue by abhilakshyadobhal** [storybookjs/storybook#8637]
Is there any way to increase the font size of the sidebar in the storybook, if possible please tell me.

**Comment by shilman** [comment]
Can you try updating the styling in `manager-head.html`?

**Comment by abhilakshyadobhal** [comment]
Yes i tried but nothing happens to the font size of sidebar

**Comment by kylesuss** [comment]
@abhilakshyadobhal would adding something like this to your `manager-head.html` file help?

```css
```

**Comment by anil-hulkapps** [comment]
```
.sidebar-container * { /* This will target all of the children */
  font-size: 110% !important;
}
```

Write important at the end its important
