### ISSUE TITLE
Advice/Feature Request - Doc prop types for multiple components

### ISSUE THREAD

**Issue by dcods22** [storybookjs/storybook#8640]
**Is your feature request related to a problem? Please describe.**
When using the docs feature instead of the addon-info, we have sub components in one story that have different prop types but need to be self contained into one story since they cannot exist without eachout.  For Example, our Accordion is broken up into a header and body.  

```
<Accordion>
 <Header>Click me</Header>
 <Body>Show me</Body>
</Accordion>
```

When we put this in a story only the table shows for the Accordion but we want to also display the props and types of them for Header and Body.  Im not sure if this exists currently but I couldnt find an example or documentation on this.

![image](https://user-images.githubusercontent.com/3107251/67865888-7995ac00-fafe-11e9-8f01-e6221f4783b2.png)

**Describe the solution you'd like**
Ideally there would be a way to pass additional components to be documented outside of the export default { title: "Accordion", component: Accordion}; So that I could add components in specific stories to display or at the top for this accordion one to display for each of the children components.

**Describe alternatives you've considered**
We currently use addon-info which provides this functionality.  We are using CSF now that we converted from storiesOf

**Are you able to assist bring the feature to reality?**
Possibly depending on the solution

**Additional context**
We have multiple use cases for this so this would prevent us from converting to docs which we would ideally like to do based on our discussion with Chromatic.

**Comment by shilman** [comment]
I agree. This will be coming to docs, hopefully in 5.3! Closing as a duplicate to https://github.com/storybookjs/storybook/issues/7811
