### ISSUE TITLE
Addon-docs: Ember support

### ISSUE THREAD

**Issue by btecu** [storybookjs/storybook#8646]
When using Ember, is there a preset for the docs addon (`@storybook/addon-docs/ember/preset`)?
Are we supposed to use React or something else for that?

I was able to get something rendering but it says `No code available`:
![image](https://user-images.githubusercontent.com/7517745/67898329-8930e700-fb36-11e9-8ca2-9cab75c12f68.png)

Any ideas on how to get the docs addon working with Ember?

**Comment by btecu** [comment]
Ping @meirish

**Comment by shilman** [comment]
@btecu starting in 5.3 (in beta) you should be able to use the `@storybook/addon-docs/preset`. haven't tested with ember but should work out of the box.

**Comment by meirish** [comment]
Added support for prop tables generation as well: https://github.com/storybookjs/storybook/pull/9067

**Comment by shilman** [comment]
Great Caesar's ghost!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-beta.17 containing PR #9067 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Jeepers creepers!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-beta.18 containing PR #9067 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

**Comment by btecu** [comment]
@meirish @shilman Thanks for working on this. 
I'm trying this feature now on an Ember application and the default DocsPage doesn't appear to work:
![image](https://user-images.githubusercontent.com/7517745/71685656-06f7b580-2d67-11ea-9f86-e047562d0f80.png)

**Comment by meirish** [comment]
Followed up with @btecu on discord - https://github.com/storybookjs/ember-cli-storybook/issues/25 was the result, we'll track things there!
