### ISSUE TITLE
web-components cannot be initialized

### ISSUE THREAD

**Issue by tonysviews** [storybookjs/storybook#8650]
**Describe the bug**
When initializing a new storybook web-components project, it is not recognized and throws an error:

The provided project type was not recognized by Storybook.

**To Reproduce**
1. Open terminal and type in: 
  npx -p @storybook/cli sb init -t web-components
  or
  npx -p @storybook/cli@next sb init -t web-components

2. The error "The provided project type was not recognized by Storybook." is shown.

**Expected behavior**
A new storybook web-components project is created.

**Code snippets**
`$ npx -p @storybook/cli sb init -t web-components

 sb init - the simplest way to add a storybook to your project. 

 • Installing Storybook for user specified project type. ✖

     The provided project type was not recognized by Storybook.

The project types currently supported by Storybook are:

    - angular
    - ember
    - html
    - marko
    - meteor
    - mithril
    - polymer
    - preact
    - rax
    - react
    - react_native
    - react_project
    - react_scripts
    - riot
    - sfc_vue
    - svelte
    - vue
    - webpack_react`

**System:**
Environment Info:

  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  Binaries:
    Node: 12.8.1 - C:\Development\nodejs\node.EXE
    npm: 6.10.2 - C:\Development\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.387.0

**Comment by Draccoz** [comment]
Just tried to create a web components storybook, got the same issue as described above. Pretty weird that official readme does not work...

**Comment by shilman** [comment]
Whoopee!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-beta.21 containing PR #9106 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.
