### ISSUE TITLE
withKnobs addon problem

### ISSUE THREAD

**Issue by abhilakshyadobhal** [storybookjs/storybook#8654]
whatever i'm passing in the text field in knobs addon it is rendered as html entity like i wanted to show a h1 heading which will be passed in text in knobs but it is rendered as
```
&lt;h1&gt;hi&lt;/hi&gt;
```
Please help

**Comment by jchiem** [comment]
Have you set `escapeHTML` to `false` ?

```  
addParameters({
    knobs: {
      escapeHTML: false
    }
  })```

**Comment by abhilakshyadobhal** [comment]
I tried this one also but it didn't worked.
