### ISSUE TITLE
Storybook 5.3 Release 🙌

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#8658]
Here we go ... [Storybook 5.2](https://medium.com/storybookjs/storybook-5-2-794958b9b111) is stable and 5.3 is on its way!

## Schedule

- ✅ `5.3.0-alpha.0` 2019-09-16
- ✅ `5.3.0-beta.0` 2019-11-16 (est. 2019-11-11)
- ✅ `5.3.0-rc.0` 2019-12-19 (est. 2019-12-16)
- 🏁 `5.3.0` 2020-01-11 (est. 2020-01-07)

## Contents

- [x] 📝 [Custom documentation in MDX](https://medium.com/storybookjs/rich-docs-with-storybook-mdx-61bc145ae7bc)
- [x] 🎨 [Multi-framework SB Docs (React, Vue, Angular, WC, Ember)](https://medium.com/storybookjs/storybook-docs-for-new-frameworks-b1f6090ee0ea)
- [x] 📦 Web-components framework support
- [x] 🔼 [Main.js declarative configuration](https://medium.com/storybookjs/declarative-storybook-configuration-49912f77b78)

Plus hundreds more changes of varying sizes and shapes, documented in the [CHANGELOG](https://github.com/storybookjs/storybook/blob/next/CHANGELOG.md)

## Help wanted

We need your help stabilizing Storybook 5.3 for the final release. It's in beta now because we think it's ready to use in most projects.

The biggest thing is to try upgrading your project to the latest prerelease, see if you run into problems, and file github isues. The sooner we uncover problems with the upgrade, the more time we have to fix and document them.

```
npx npm-check-updates '/storybook/' -un
npm install # yarn if you prefer
```

Take note of feature-specific [migration instructions](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#from-version-52x-to-53x) when you upgrade.

And of course, if you see any [issues](https://github.com/storybookjs/storybook/issues) that you can help with, PRs are always welcome. Storybook wouldn't be possible without high-quality contributions from our wonderful community.

Thanks for your help and stay posted for more updates!

**Comment by BradCandell** [comment]
I assume that the (estimated) release date of 1/7/2019 is supposed to be 1/7/2020?

**Comment by drew-codes** [comment]
Sweeeet! Thanks @shilman.

Just popping by to say that the above command didn't work for me, but the following did:
`npx npm-check-updates "/^@storybook.*$/" -un`

**Comment by o-t-w** [comment]
How do I set up a brand new project to use this?

**Comment by shilman** [comment]
@o-t-w

```
cd my-project
npx -p @storybook/cli@next sb init 
```

To add docs, see the instructions:  https://github.com/storybookjs/storybook/blob/next/addons/docs/README.md#installation

**Comment by andrewpeterprifer** [comment]
@shilman considering it seems like there were quite some changes to the preferred way of configuring Storybook (moving to main.js and presets), will there be a migration guide from 5.2 to 5.3? Currently I can't find any.

**Comment by m0t0r** [comment]
@andrewpeterprifer you can find the Migration Guide [here](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#from-version-52x-to-53x).

**Comment by shilman** [comment]
@andrewpeterprifer We do migration notes for every release like @m0t0r linked to. All of the changes in 5.3 really just test balloons for the next release, which is 6.0. We'll work out the kinks, make breaking changes if we need to, deprecate the old versions, and release a more structured guide like we did for 5.0 and 4.0 before it.

As for globs, I can't speak to that decision, except that it seems to be the most common way to deal with file-related matching.

**Comment by andrewpeterprifer** [comment]
Thank you for pointing me to the guide! I was looking in the docs. The point about globs for file matching is fair.
