### ISSUE TITLE
How to rename tab?

### ISSUE THREAD

**Issue by guikeller** [storybookjs/storybook#8661]
Hello there,

First and foremost, great project I really like it! :smiley: 

Unfortunately, I couldn't find any examples on how to rename the 'tabs' within a story.
For example the 'Canvas' tab to 'Example' 
And/or the 'Notes' (addon) tab to 'Source'.

Cheers! :+1:

**Comment by guikeller** [comment]
Nevermind, thanks.

**Comment by levaigabor** [comment]
> @guikeller did you figure this out? I'd like to do the same.

If it's still a question for you, here's the answer: https://github.com/storybookjs/storybook/pull/9095
