### ISSUE TITLE
How to stub global methods in storybook ?

### ISSUE THREAD

**Issue by qinglong-kooboo** [storybookjs/storybook#8662]
Beacuse nuxt-i18n is integrated with vue-i18n, so when i use nuxt-i18n with storybook, i 
import vue-i18n to config.js. However some bulit-in methods in nuxt-i18n, like `localePath`, `switchLocalePath` can't be accessed in story. How to stub it? 

this is config file 
![image](https://user-images.githubusercontent.com/40824476/68010030-71846a80-fcbe-11e9-9bc5-22fba85118d9.png)
I have tried to stub it in methods, seems not worked.
![image](https://user-images.githubusercontent.com/40824476/68010136-c3c58b80-fcbe-11e9-905e-d88637636978.png)
Stiil get error below
![image](https://user-images.githubusercontent.com/40824476/68010163-d8a21f00-fcbe-11e9-9ef6-c197b9af0bd5.png)
Any ideas?

**Comment by qinglong-kooboo** [comment]
never mind, just like stub a component, use `Vue.mixin` to stub it.

**Comment by qinglong-kooboo** [comment]
now comes to new problem, how can i stub extentions from vue-i18n..  
like: `locales`
![image](https://user-images.githubusercontent.com/40824476/68363907-53f44c80-0167-11ea-860e-d0f01c525a70.png)

**Comment by noisy** [comment]
@qinglong-kooboo example would be great!

**Comment by aminimalanimal** [comment]
@noisy Looks like it's this easy:

```
// preview.js (or config.js)

Vue.mixin({
  methods: {
    localePath() {},
  },
})
```
