### ISSUE TITLE
[Docs] extractProps assumes propTypes to be in wrapped component

### ISSUE THREAD

**Issue by donysukardi** [storybookjs/storybook#8664]
**Describe the bug**

In `extractProps` function for React, the code will always unwrap the component before checking if propTypes is assigned to the wrapped component itself (a relatively common pattern).

https://github.com/storybookjs/storybook/blob/27a3a04cab0c5919faf436b972e438bb52749980/addons/docs/src/frameworks/react/extractProps.ts#L62-L76

**To Reproduce**

PropTypes will be _invisible_ in this case.

```
const Component = forwardRef((props, ref) => (/* ... */);

Component.propTypes = {
  /* some prop types */
}
```

**Expected behavior**

`extractProps` will check if the wrapped component has propTypes assigned before trying to unwrap it for further check.

**Comment by shilman** [comment]
Egads!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-alpha.36 containing PR #8665 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.
