### ISSUE TITLE
[Addon-docs]: Preview Pane not showing proper component source code

### ISSUE THREAD

**Issue by gmukul01** [storybookjs/storybook#8666]
**Describe the bug**
Preview Pane not showing proper component source code. I am following below link
https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/recipes.md#csf-stories-with-mdx-docs

**Screenshots**
Docs
![image](https://user-images.githubusercontent.com/3636885/68034676-1ff0d580-fce8-11e9-8c32-8968a9849162.png)

**Code snippets**
CheckboxGroup.stories.tsx
![image](https://user-images.githubusercontent.com/3636885/68034703-3434d280-fce8-11e9-9033-6b50bbb23b6d.png)

CheckboxGroup.stories.mdx
![image](https://user-images.githubusercontent.com/3636885/68034740-49116600-fce8-11e9-831d-b923c91b2e83.png)

**Comment by gmukul01** [comment]
it is showing proper jsx in storybook-addon-jsx but not in the preview pane of docs
![image](https://user-images.githubusercontent.com/3636885/68034962-b4f3ce80-fce8-11e9-8285-6f9358538739.png)

**Comment by shilman** [comment]
Closing as dupe to #8444
