### ISSUE TITLE
Addon-docs: Test coverage doc block

### ISSUE THREAD

**Issue by fervanrijswijk** [storybookjs/storybook#8668]
**Describe the solution you'd like**
Show code coverage for all component/child components for a component described in a story. This coverage can be an aggregation of all the components that can be found under a certain dir for the main story component.

**Are you able to assist bring the feature to reality?**
no

**Comment by pgangwani** [comment]
@shilman : This should be addition to jest, right ? Like If one is passing './.jest-test-results.json' results already, so new tab or subtab should show html coverage report. Is my understanding correct ?

**Comment by pgangwani** [comment]
@shilman : I may help if you welcome newbie contributors

**Comment by atanasster** [comment]
@pgangwani - this request is with creating custom doc blocks - you can start it in your own repo as a storybook addon and I would be glad to contribute as well. 
The Dependencies plugin can be used for inspiration on creating custom Doc blocks, and customizing DocsPpage: https://github.com/atanasster/storybook-addon-deps

**Comment by shilman** [comment]
@pgangwani like @atanasster said, if you want to built a standalone package for that, we'd be happy to promote it in all the storybook channels (twitter, medium, etc.). If you're interested in contributing it after the addon has stabilized, we'd be open to that too!
