### ISSUE TITLE
Components with vue functional keyword does not render on storybook

### ISSUE THREAD

**Issue by silwalsubin** [storybookjs/storybook#8669]
**Describe the bug**
Functional components (Vue components with functional keyword) do not render on storybook

**To Reproduce**
1. Create a functional vue component (By adding functional keyword)
2. Notice that by adding the functional keyword, the component would not render correctly.

**Expected behavior**
Functional vue components should render just like non functional vue components.

**Code snippets**
An example of functional component. 
<template functional>
   <div>
      hello world
   </div>.
</template>

**Comment by Aaron-Pool** [comment]
@silwalsubin are you saying _stories_ which represented by functional components don't render. Or components _inside_ of stories that are functional don't render.

**Comment by Aaron-Pool** [comment]
Any way you could set up a minimal repro repo?

**Comment by webistomin** [comment]
It works if you render your component like this:
```js
/* AppLogo.stories.js */

import AppLogo from './AppLogo';

export default {
  title: 'AppLogo',
  component: AppLogo,
};

export const Default = () => ({
  render: (h) => h(AppLogo),
  // components: { AppLogo },
  // template: '<app-logo />', this way doesn't work
});
```

**Comment by eLoyyyyy** [comment]
> It works if you render your component like this:
> 
> ```js
> /* AppLogo.stories.js */
> 
> import AppLogo from './AppLogo';
> 
> export default {
>   title: 'AppLogo',
>   component: AppLogo,
> };
> 
> export const Default = () => ({
>   render: (h) => h(AppLogo),
>   // components: { AppLogo },
>   // template: '<app-logo />', this way doesn't work
> });
> ```

would this apply for a component with a child component _that_ is a functional component? I haven't tried it as of this writing.
