### ISSUE TITLE
Setting component via Meta does not work directly

### ISSUE THREAD

**Issue by daKmoR** [storybookjs/storybook#8676]
**Describe the bug**
Setting the "component" via `Meta` in an mdx story.

That works
```js
<Meta parameters={{ component: 'demo-wc-card' }} />
```

This does not
```js
<Meta component="demo-wc-card" />
<Meta component={'demo-wc-card'} />
```

**Expected behavior**
Setting the component directly via meta should be posible.

Tested in `next` branch.

**Comment by vanessayuenn** [comment]
Hi! I am going through and cleaning up old issues in the repo. We just shipped a ton of improvements in Storybook 7.0, and I suspect this bug might be fixed already. Can you please try it out? If this issue persists with the latest version, please open a new bug report with a 7.x reproduction. Thank you so much! 🙏🏼
