### ISSUE TITLE
Vue: Use `parameters.component` if available

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#8685]
In Vue stories, you currently need to pass a component argument as part of the story input (for some modes):

```js
export const basic = () => ({
  components: { InfoButton },
  template: '<info-button label="I\'m a button!"/>',
});
```

However, in 5.2 and later, it's recommended to pass this as part of the component metadata:

```
export default {
  title: 'InfoButton',
  component: InfoButton,
};
```

This gets translated into the underlying API call:

```
storiesOf('InfoButton', module)
  .addParameters({ component: InfoButton })
  .add('Basic', () => ...);
```

Therefore Vue should use `parameters.component` if it's available and the story's component ISN'T available. If possible, in 6.0 we should deprecate the Story's component, and in 7.0 we should remove support entirely.

Related: #8673

**Comment by pksunkara** [comment]
@shilman Should you close https://github.com/storybookjs/storybook/issues/8109 because they look the same?

**Comment by shilman** [comment]
@pksunkara good call. closing this issue instead as dupe to #8109, since that one already has upvotes.
