### ISSUE TITLE
Addon-docs: Use babel-plugin-react-docgen instead of react-docgen-typescript-loader to generate TS docs

### ISSUE THREAD

**Issue by patricklafrance** [storybookjs/storybook#8701]
**Is your feature request related to a problem? Please describe.**

TS props docs is generated with a webpack plugin called *react-docgen-typescript-loader* instead of using a babel plugin called [babel-plugin-react-docgen](https://github.com/storybookjs/babel-plugin-react-docgen).

This has been done this way because [react-docgen](https://github.com/reactjs/react-docgen) didn't support TS at the time.

Now that react-docgen support TS, it's time to re-visist and if possible, move TS to babel-plugin-react-docgen

Also, *react-docgen-typescript-loader* is currently configure in [preset-create-react-app](https://github.com/storybookjs/presets/tree/master/packages/preset-create-react-app) and [preset-typescript](https://github.com/storybookjs/presets/tree/master/packages/preset-typescript). babel-plugin-react-docgen should be configured in the addon-docs preset instead.

**Additional context**
JSDoc parsing would also benefits from this change.

**Comment by patricklafrance** [comment]
I tryed react-docgen with TS.

Not sure if it was my setup but it wasn't working very well..

I could not even get a "type" value.

The following type throw:

- Enums (cannot even define one)
- funcWithIndexTypes: <T, K extends keyof T>(o: T, propertyNames: K[]) => T[K][]; (cannot even define one)
- readonly readonlyPrimitive: string; (cannot event define one)

**Comment by shilman** [comment]
Closing as dupe to #9837
