### ISSUE TITLE
<Source /> component doesn't pass dark theme prop

### ISSUE THREAD

**Issue by adrian-potepa** [storybookjs/storybook#8709]
**Describe the bug**
If we use `<Source />` [component](https://github.com/storybookjs/storybook/blob/next/addons/docs/src/blocks/Source.tsx) in .mdx file it doesn't pass `dark` prop.

**To Reproduce**
.mdx file:
```
import {
  Meta,
  Source,
} from '@storybook/addon-docs/blocks';

import * as stories from './Button.stories.tsx';
import { Button } from '.';

<Meta title="Components|Buttons/Button" component={Button} />

## Using with `<a>` tag

You can use `<Button>` as link content.

<Source
  code={`<a href="#" rel="Some rel text" target="_blank">
    <Button>Link text</Button>
  </a>`}
  language="jsx"
  dark={true}
/>
```

**Expected behavior**
It should looks:
![Zrzut ekranu 2019-11-5 o 08 12 10](https://user-images.githubusercontent.com/6291752/68186260-ffed3a80-ffa3-11e9-97ac-55e6d5fd4013.png)

For now component ignores `dark` prop:
![Zrzut ekranu 2019-11-5 o 08 03 23](https://user-images.githubusercontent.com/6291752/68186311-214e2680-ffa4-11e9-9800-34d922c96286.png)

**Comment by adrian-potepa** [comment]
I'll create PR for this later ;)

**Comment by shilman** [comment]
Huzzah!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-beta.11 containing PR #8732 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
