### ISSUE TITLE
RenderFunction & Renderable are not exported

### ISSUE THREAD

**Issue by thenods** [storybookjs/storybook#8713]
**Describe the bug**
I am using react, and some addons.
I was migrating from v5.1.11 to v5.2.5. But type errors are occurred because `RenderFunction` & `Renderable` are not exported.

**Expected behavior**
Importing `RenderFunction` and `Renderable` works

**Code snippets**
```ts
// node_modules/@storybook/react/dist/client"' has no exported member 'RenderFunction'.
// node_modules/@storybook/react/dist/client"' has no exported member 'Renderable'.
import { RenderFunction, Renderable } from '@storybook/react';
```

**System:**
```
  System:
    OS: macOS Mojave 10.14.6
    CPU: (6) x64 Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz
  Binaries:
    Node: 12.11.1 - /usr/local/bin/node
    npm: 6.12.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 78.0.3904.70
    Safari: 13.0.3
  npmPackages:
    @storybook/addon-actions: ^5.2.5 => 5.2.5
    @storybook/addon-options: ^5.2.5 => 5.2.5
    @storybook/addons: ^5.2.5 => 5.2.5
    @storybook/react: ^5.2.5 => 5.2.5
```

**Comment by atanasster** [comment]
@thenods I can't find any reference to `RenderFunction` or `Renderable` in the 5.3xx code - how are you using them?

**Comment by shilman** [comment]
@atanasster I think these were defined in `@types/storybook__react` which is now obsolete. So users of that package are missing that when they migrate..

**Comment by atanasster** [comment]
@shilman - I mean those types are not used anymore, so probably whatever code is using them needs to be upgraded, right?
Here is what they looked like: 
```
export type Renderable = React.ComponentType | JSX.Element;
export type RenderFunction = () => Renderable | Renderable[];
```

I can also  just add them back to https://github.com/storybookjs/storybook/blob/97a4aad4587ac975fd814c22a136f8293b72fc12/app/react/src/client/preview/index.ts#L30
