### ISSUE TITLE
[addon-docs] Vanilla element represented as MDXCreateElement in source

### ISSUE THREAD

**Issue by thany** [storybookjs/storybook#8721]
**Describe the bug**
Sometimes it's neccesary to show vanilla elements in a story to indicate. However, when I do that, it'll display verbose `<MDXCreateElement>` elements instead of the elements themselves.

**To Reproduce**
1. Make sure Story Source is enabled
2. Build a story in MDX
3. Make sure the story contains vanilla elements in some way.

**Expected behavior**
For example, a `<h1>` ought to be rendered as `<h1>`.

**Screenshots**
Vanilla elements are rendered like this:
![Capture](https://user-images.githubusercontent.com/152227/68215552-bc182680-ffdf-11e9-92b8-296f33b709b2.PNG)
(sorry, I don't know how to get github to display this any smaller)

**Code snippets**
Something like this should suffice:
```jsx
<Story name="default">
  <h1>Hello world</h1>
</Story>
```

**System:**
```
Environment Info:

  System:
    OS: Windows 10
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
  Binaries:
    Node: 10.16.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
```

**Comment by shilman** [comment]
- Are you using the docs preset?
- Are your files named `*.stories.mdx`?
- What version of MDX is installed?

**Comment by hipstersmoothie** [comment]
I am seeing this behavior too

> Are you using the docs preset?

yes

> Are your files named *.stories.mdx?

No. Currently we structure it like: create file `Card.mdx`, import that file into the story and set it on

```js
export default {
  title: 'Components|Card',
  parameters: {
    docs: {
      page: mdx
    }
  }
};
```

> What version of MDX is installed?

1.1.0

**Comment by shilman** [comment]
@hipstersmoothie The docs preset only applies the storybook magic to `.(stories|story).mdx`. If you want it to run on all MDX files, you need to use that naming convention OR you need a custom webpack config:

https://github.com/storybookjs/storybook/blob/next/addons/docs/src/frameworks/common/preset.ts#L44

**Comment by thany** [comment]
>     * Are you using the docs preset?

Yes

>     * Are your files named `*.stories.mdx`?

Yes

>     * What version of MDX is installed?

Whatever installs with addon-docs. I don't know how to check.

**Comment by shilman** [comment]
@thany do you have a repro i can look at?

**Comment by thany** [comment]
@shilman Sorry, it's a private repo that I'm not at liberty to expose.
Just to be on the same page, are you implying this behaviour doesn't happen for you?

**Comment by shilman** [comment]
@thany I cannot repro. There are a number of different ways to use docs/MDX, so my question was an attempt to narrow things down. If you look at our [official-storybook](https://github.com/storybookjs/storybook/tree/next/examples/official-storybook) MDX `h1`'s are rendered as `h1`.

Storybook uses a preprocessor to add some extra data to `.(stories|story).mdx` files, and it's possible that somehow it's not running on your MDX files. However, your files are named correctly and you're using the preset, so I'd need to look at your repo, or a stripped down reproduction repo that's not private, to figure out what's going on. AFAIK you're the first person to report this.

**Comment by thany** [comment]
Here's a repo that reproduces the problem:
https://github.com/thany/mdx-reduced-test

To run it, please check it out and run `npm i` and `npm run storybook`.

**Comment by shilman** [comment]
@thany remove the following lines from config.js:

```
addDecorator(
  withInfo({
    inline: true,
    header: false,
  })
);
```
