### ISSUE TITLE
[addon-docs]: DocsPage blocks configuration proposal

### ISSUE THREAD

**Issue by atanasster** [storybookjs/storybook#8723]
thinking of a way to configure the order and content of DocsPage without getting into too much breaking changes before 5.3 beta, a proposal for composing the DocsPage in a react way:

```

addParameters({
  
docs: { page: (
 <DocsPage>
    <ComponentName/>
    <ComponentDescription />
    <PrimaryStory />
     <PropsTable />
      <Dependencies /> <— third-party doc block
      <DocsStories />
  </DocsPage>
) }
```

Where each component will include a title and the underlying pure component ( users could configure their section titles if desired). The underlying components will be shared with the mdx stories and will use their DocsContext each block component instead of sharing them through DocsPage.
```
const DocStories = () => (
  <>
     <DocsSection>Stories</DocsSection>
     <PureDocsStories />
  </>
);
```
This will also remove the usage of DocsPage slots.

Other options considered were 
- an external .mdx file for the docs page
- a list of blocks:

```
page: DocsPage,
blocks: [ComponentName, ComponentDescription, ..., Dependencies, ...], 
```

Each component will accept a context: DocsContext parameter passed from the DocsPage component

**Comment by shilman** [comment]
This is awesome @atanasster. I like the JSX example -- very clean. This is probably too late for 5.3, tho we might be able to sneak it into early-beta if it gets done soon and isn't TOO disruptive. Otherwise it'd be great to ship first thing in 5.4!

**Comment by shilman** [comment]
Boo-yah!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-beta.2 containing PR #8855 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
