### ISSUE TITLE
[addon-docs] Clean up the docs page

### ISSUE THREAD

**Issue by thany** [storybookjs/storybook#8735]
**Is your feature request related to a problem? Please describe.**
As a developer, I want a docs page to be clear, non-repetitive, and pertaining only to the component I'm looking at.

**Describe the solution you'd like**
The docs page should be cleaned up.

1. It should not repeat the proptable after each story, but only once.
2. It should not scroll down when the user wants to read the documentation.
3. There is a "story source" and a little source button. Both produce different representation of the source. Please choose one and stick with it.
4. The proptables should list ALL props a component can have. This is especially appearant when using typescript and the props interface is extended from another.
5. A proptype should be displayed as its name, not its underlying meaning. Current behaviour is especially useless when having a prop of type `JSX.IntrinsicAttributes`.
6. The proptables for other components will be displayed in addition, if multiple components are used in a story. At the same time, others will arbitrarily be omitted. Please only list proptables for the component defined in the `<Meta />` element.
7. The description of a proptype is markdown for intellisense (and this is standardized in JSDoc), but is rendered as-is. Newlines are converted to `<br>`, which proves that transformation is at least possible.

**Describe alternatives you've considered**
I would take the current DocsPage component and make a custom one. I considered it. But then I realised I don't have time to do that.

**Are you able to assist bring the feature to reality?**
You yourselves actually made a pretty good design already:
https://github.com/storybookjs/storybook/blob/15d4f135982c78ee2c2cece716ebde7c33b581ee/addons/docs/docs/docspage.md
Sadly this design wasn't achieved. But it's exactly what *would* make a docspage interesting to use.

**Additional context**
This screenshot shows unnecessary repetition and just not a very useful layout once the number of stories grows. It also shows Story Source which is useful in this particular case, but there's also a "Show code" button. In many cases, that one shows different code, but pertains to the same actual source file.
![Screenshot_2019-11-06 Components Typography Text - Default Story ⋅ Storybook](https://user-images.githubusercontent.com/152227/68292318-e6bfb900-008b-11ea-97ba-b8c1ed97b3be.png)

This one is even worse. I also opened the "Show code" to show the difference.
![Screenshot_2019-11-06 Storybook](https://user-images.githubusercontent.com/152227/68292566-71a0b380-008c-11ea-8932-faca9ae0aa68.png)

It just needs a little bit more 💕

**Comment by shilman** [comment]
The image you link to an actual screenshot from a live storybook, and is what's shipped in storybook with zero configuration

https://storybook-design-system.netlify.com/

**Comment by shilman** [comment]
I don't know what those screenshots are. Looks like addon-info maybe, which is deprecated

**Comment by thany** [comment]
If I remove addon-info, I don't get _any_ story source or proptypes.
