### ISSUE TITLE
[addon-docs] Props component render defaultProps from the last component from the file

### ISSUE THREAD

**Issue by lgraziani2712** [storybookjs/storybook#8740]
**Describe the bug**

I have a MDX file that renders the `Props` for a component from a file with two components. The default value for one of its props has the value from the `defaultProps` of the last component. If I change the order of them, it changes the default value being rendered.

BTW,  I'm using the `typescript-preset`.

**To Reproduce**
1. Create a tsx files with two named export components and configure a prop with default value for each of them. That prop must have the same name for both of them but different accepted values.
2. Create a mdx story.
3. Import one or both (it doesn't matter) components and render their props.
4. Change the order of the components (in the tsx file).
5. See how the default value changes to the value of the last component.

**Expected behavior**
To respect the default value for each component.

**Screenshots**

![image](https://user-images.githubusercontent.com/15050200/68308369-8761a900-008b-11ea-879c-7bbd97836457.png)

**Code snippets**

```tsx
export interface ElemAProps {
  size?: 'a' | 'b' | 'c' | 'd';
}

export const ElemA: React.SFC<ElemAProps> = ({ size = 'a', children }) => (
  <div className={size}>{children}</div>
);

export interface ElemBProps {
  size?: 'sm' | 'md' | 'lg';
}

export const Paragraph: React.SFC<ElemBProps> = props => (
  <div className={props.size}>{props.children}</div>
);

ElemBProps.defaultProps = { size: 'md' };
```

**System:**

```
  System:
    OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.19.1 - /usr/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
  Browsers:
    Chrome: 78.0.3904.87
    Firefox: 71.0b7
  npmPackages:
    @storybook/addon-actions: 5.2.5 => 5.2.5 
    @storybook/addon-backgrounds: 5.2.5 => 5.2.5 
    @storybook/addon-docs: 5.2.5 => 5.2.5 
    @storybook/addon-knobs: 5.2.5 => 5.2.5 
    @storybook/preset-typescript: 1.1.0 => 1.1.0 
    @storybook/react: 5.2.5 => 5.2.5 
```

**Comment by shilman** [comment]
Repro: https://github.com/storybookjs/storybook/commit/85e4f6d790cacbc1c64a3bedf53d3f2c86d30e79

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid.

Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
