### ISSUE TITLE
Access to an angular service in an action

### ISSUE THREAD

**Issue by remybd** [storybookjs/storybook#8741]
Hello

I'm not finding anywhere (in the documentation, google or github) an example of someone calling a service (angular service) in an action of the story.
On click, I want to call a service.

Does this functionality exist ? if yes, how can I access to the service ?

I'm trying to dynamicaly add toasters from a button in my story
```typescript
export const toasters = () => ({
  template: '<tpz-toasters</tpz-toasters>' +
    '<button (click)="onClick()">Add Toaster</button>',
  props: {
    onClick: () => {
      toasterService.addToaster();
    },
  }
});
```

Here tpz-toasters is my global toaster container. It's a component plug on an observable of a service (TpzToasterService).
When a new toaster is added to the service, the toaster container will be able to display it.

How can I access to toasterService ? Is it a new feature to implement ?

Thanks for your help

**Comment by Terrafire123** [comment]
I'm having the same issue. 

Has anyone come up with a solution?

**Comment by kroeder** [comment]
You can create a wrapper demo component 
```typescript
export const primaryButton = () => ({
  component: PrimaryButtonDemo
})

@Component({
  template: `<button (click)="doStuff()">Do stuff</button>`
})
class PrimaryButtonDemo {
  constructor(private myService: MyService) {
  }

  doStuff() {
    this.myService.callMethod();
  }
}
```

I structure my stories like that

```typescript
| /stories
| --- primary-button.stories.ts
| --- primary-button-demo.component.ts
| /primary-button.component.ts
```

I don't think there's another way expect creating an instance of your service manually (without using angulars DI)

So, of course this is also possible:

```typescript
const service = new MyService();

export const primaryButton = () => ({
  template: `<button (click)="doStuff()">Do stuff</button>`,
  props: {
    doStuff: () => {
      service.callMethod()
    }
  }
})
```

**Comment by remybd** [comment]
I did smething like that to. With another folder that I called demo-components. But it's the same system.
For documentation, it's better in this case to write it by hand instead of let it storybook generate it for you

**Comment by leopangchan** [comment]
@kroeder Great workaround!! I still hope storybook team can take this more seriously. It will be a very useful feature.

**Comment by prachi00** [comment]
Facing this issue, is there any way to do it without creating a demo component?

**Comment by Marcodebo** [comment]
Do you have any news?

**Comment by Hamcker** [comment]
This solution didn't work for me, but might be helpful for a solution:

https://jgelin.medium.com/inject-angular-services-in-storybook-7-c26b7f5a41e5

**Comment by Hobart2967** [comment]
Did not work for me either :(

Still trying to figure out how storybook is building its module tree to fix it.

> This solution didn't work for me, but might be helpful for a solution:
> 
> https://jgelin.medium.com/inject-angular-services-in-storybook-7-c26b7f5a41e5
