### ISSUE TITLE
Storybook/angular has components looking for storybook/react

### ISSUE THREAD

**Issue by osa10928** [storybookjs/storybook#8742]
**Describe the bug**
I'm not sure if this is a bug or something I'm doing wrong but when trying to setup storybook and storybook add-on storyshot with Jest I keep running into errors where components of storybook expect require storybook/react even though I installed Storybook/angular.

**To Reproduce**
1. Go to [my github](https://github.com/osa10928/storybook-testing)
2. Clone Repo
3. Run npm run storybook
4. Alternatively run npm run jest

**Expected behavior**
Since I initialized storybook like this:
`npx -p @storybook/cli sb init --type angular
`
I expect for the storysnapshot to run to completion, without error codes referencing storybook/react such as `Cannot find module '@storybook/react' from 'Badge.stories.js'`

**Screenshots**
<img width="741" alt="Screen Shot 2019-11-06 at 1 09 55 PM" src="https://user-images.githubusercontent.com/23482698/68329455-dd881980-0096-11ea-8d15-e39470bf9a27.png">

**Code snippets**
Configurations files can be found at the repo but I can post any upon request

**System:*
<img width="741" alt="Screen Shot 2019-11-06 at 1 15 32 PM" src="https://user-images.githubusercontent.com/23482698/68329736-88003c80-0097-11ea-897b-bb14526bf093.png">
` here.

**Comment by osa10928** [comment]
Sorry my mistake:
On the steps to reproduce the issue, before running anything in the terminal run `npm install` to install the dependencies.

**Comment by geromegrignon** [comment]
The React error comes from your config.js content as your regex matches js files rather than ts files.
I can't help you with *less* configuration but by deleting your `webpack.config.js` file , you should be able to run successfully storybook (you'll need to change your task.component.ts selector from 'app-task' to 'task-item' to match your task.stories.ts).
