### ISSUE TITLE
How to use addon-notes in combination with CSF stories?

### ISSUE THREAD

**Issue by daviddelusenet** [storybookjs/storybook#8746]
I'm using both the most recent version of `storybook` and the `addon-notes` addon.

However, I can't get the notes the work with my stories written in the CSF format.

Example of one of my stories:

```jsx
import ErrorMessage from './ErrorMessage';
import React from 'react';
import { text } from '@storybook/addon-knobs';

export default { title: 'atoms/ErrorMessage' };

export const Configurable = () => (
    <ErrorMessage>
        {text('Error message', 'Everything is broken, help!')}
    </ErrorMessage>
);
```

So how would I add notes to this story?

**Comment by daviddelusenet** [comment]
I figured it out. You should set the `notes` key inside of the `parameters` object:

```jsx
import ErrorMessage from './ErrorMessage';
import React from 'react';
import test from './test.md';
import { text } from '@storybook/addon-knobs';

export default {
    notes: test,
    parameters: {
        notes: test,
    },
    title: 'atoms/ErrorMessage',
};

export const Configurable = () => (
    <ErrorMessage>
        {text('Error message', 'Everything is broken, help!')}
    </ErrorMessage>
);
```

**Comment by patrick-radulian** [comment]
Have you found out whether there's any way to supply a separate note per story?
Using the parameters field sets the notes for all stories of that component, which is pretty limiting.
Any ideas?

**Comment by daviddelusenet** [comment]
@patrick-radulian nope, we're just using the solution mentioned above, sorry 😞

**Comment by patrick-radulian** [comment]
Thanks for the quick reply - will keep digging and notify if I find something useful.
