### ISSUE TITLE
Making Docs look like the actual screenshot shown

### ISSUE THREAD

**Issue by iamdriz** [storybookjs/storybook#8750]
This screenshot: https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/media/hero.png

Is that actually what is available right now? as with the very latest version of Storybook and add-ons my version doesn't look anything like that... 

The version picker in the sidebar
The search box saying 'Search docs...'
The complete removal of the toolbars and tabs (Canvas and Docs) so you just have the docs.
The share option in the top right.

Is is some highly customized version of Storybook? Or what's actually available?

**Comment by iamdriz** [comment]
Also should you be able to disable the Canvas tab then? So you only have the Docs?

**Comment by iamdriz** [comment]
![image](https://user-images.githubusercontent.com/801252/68405712-822e5800-0178-11ea-8e51-e36c499c8888.png)

**Comment by iamdriz** [comment]
We tried using the MDX route and the same outcome... should it not disable the Canvas tab if you have written your own MDX file and bypassed DocPage?

**Comment by shilman** [comment]
@iamdriz you can run storybook with `--docs` to force it to only show the docs tab. the rest of the features are in various stages of development

**Comment by iamdriz** [comment]
@shilman Ah okies... that's cool. Thanks! Is that documented anywhere?

**Comment by iamdriz** [comment]
@shilman Hmm doesn't seem to remove it for me: `"start-storybook --docs -p 6006"` is that correct?

**Comment by shilman** [comment]
https://github.com/storybookjs/storybook/blob/master/addons/docs/docs/recipes.md#exporting-documentation
