### ISSUE TITLE
Cannot read property 'fonts' of undefined - using ColorPalette in addon-docs

### ISSUE THREAD

**Issue by groces** [storybookjs/storybook#8753]
**Describe the bug**
I am attempting to use ColorPalette and ColorItem from addon-docs but I keep getting this error. The error is only visible in the Canvas tab. The story renders fine in the Docs tab.

**To Reproduce**
Go to story using ColorPalette
Go to Canvas tab
See error

**Expected behavior**
ColorPalette and ColorItem to render also render properly in Canvas tab.

**Screenshots**
Canvas tab
![Screen Shot 2019-11-07 at 4 05 34 PM](https://user-images.githubusercontent.com/21180214/68438308-95d9be80-0178-11ea-8edd-aee38aef0078.png)

Docs tab
![Screen Shot 2019-11-07 at 4 05 42 PM](https://user-images.githubusercontent.com/21180214/68438312-9a05dc00-0178-11ea-85f1-500d4f8d2432.png)

Console error
![Screen Shot 2019-11-07 at 3 57 09 PM](https://user-images.githubusercontent.com/21180214/68438376-ddf8e100-0178-11ea-858b-ffe73ae6d185.png)

![Screen Shot 2019-11-07 at 3 57 22 PM](https://user-images.githubusercontent.com/21180214/68438390-e81adf80-0178-11ea-89a7-ebe84c78f0c2.png)

**Code snippets**
`import React from 'react';
import { storiesOf } from '@storybook/react';
import { ColorItem, ColorPalette } from '@storybook/addon-docs/blocks';
import { themes } from '@storybook/theming';

storiesOf('Colors', module)
  .addParameters({
    options: {
      theme: themes.dark,
    },
  })
  .add('Colors', () => {
    return (
      <ColorPalette>
        <ColorItem title={'color item'} colors={['#000000']}></ColorItem>
      </ColorPalette>
    );
  });
`

**System:**
  Browsers:
    Chrome: 78.0.3904.97
    Firefox: 66.0.5
    Safari: 12.1.1
  npmPackages:
    @storybook/addon-actions: ^5.2.5 => 5.2.5
    @storybook/addon-docs: ^5.2.5 => 5.2.5
    @storybook/addon-info: ^5.2.5 => 5.2.5
    @storybook/addon-knobs: ^5.2.5 => 5.2.5
    @storybook/addon-links: ^5.2.5 => 5.2.5
    @storybook/addon-notes: ^5.2.5 => 5.2.5
    @storybook/addon-options: ^5.2.5 => 5.2.5
    @storybook/react: ^5.2.5 => 5.2.5
    @storybook/theming: ^5.2.5 => 5.2.5

**Additional context**
Running through solutions to similar issues. I checked the following:

Output of `npm ls emotion-theming`
<img width="429" alt="Screen Shot 2019-11-07 at 4 00 10 PM" src="https://user-images.githubusercontent.com/21180214/68438419-fbc64600-0178-11ea-9aec-73f440ce0174.png">

Output of `npm ls @storybook/theming`
<img width="319" alt="Screen Shot 2019-11-07 at 4 10 03 PM" src="https://user-images.githubusercontent.com/21180214/68438500-37611000-0179-11ea-9ef2-bdcf6a499881.png">

Current dependencies:
 "devDependencies": {
    "@babel/core": "^7.4.3",
    "@babel/polyfill": "^7.6.0",
    "@sambego/storybook-state": "^1.3.4",
    "@sentry/webpack-plugin": "^1.6.2",
    "@storybook/addon-actions": "^5.2.5",
    "@storybook/addon-docs": "^5.2.5",
    "@storybook/addon-info": "^5.2.5",
    "@storybook/addon-knobs": "^5.2.5",
    "@storybook/addon-links": "^5.2.5",
    "@storybook/addon-notes": "^5.2.5",
    "@storybook/addon-options": "^5.2.5",
    "@storybook/react": "^5.2.5",
    "@storybook/theming": "^5.2.5"
},
  "dependencies": {
    "@emotion/core": "^10.0.22",
    "@emotion/styled": "^10.0.23"
}

I've also removed node_modules, yarn.lock, and yarn installed but error still occurs

**Comment by shilman** [comment]
It's possible that the problem is that these doc blocks are not meant to go into your stories directly. They are meant to be used in the docs addon in your MDX documentation. They require a context that's set up in docs.

Can you try that instead?

**Comment by groces** [comment]
@shilman I seem to still be getting that error after converting my story to mdx.

**Comment by groces** [comment]
@shilman I seem to still be getting that error after I converted my story to mdx.

Colors.stories.mdx
```
import { action } from '@storybook/addon-actions';
import { Story, Meta } from '@storybook/addon-docs/blocks';

import Colors from '../colors/Colors';

<Meta title='Design|Colors' component={Colors} />

# Colors

<Story name="Colors">
    <Colors />
</Story>
```

Colors.jsx
```
import React, { Component } from 'react';
import { ColorPalette, ColorItem } from '@storybook/addon-docs/blocks';

class Colors extends Component {
  render() {
    return (
      <div>
        <ColorPalette>
          <ColorItem title="color item" colors={['#000000']} />
        </ColorPalette>
      </div>
    );
  }
}

export default Colors;
```

![Screen Shot 2019-11-12 at 2 31 06 PM](https://user-images.githubusercontent.com/21180214/68716452-1887c280-0559-11ea-85b2-bb163818839c.png)

**Comment by shilman** [comment]
Right, it's still inside a story. It's meant to be used in docs OUTSIDE of stories... 😬

**Comment by groces** [comment]
SMH I see now haha. Thanks for the help!

**Comment by justin-peterson-jdas** [comment]
I'm actually seeing this same behavior but my ColorPalette and ColorItems are within an mdx file. I'm seeing the same exact errors mentioned by @groces 

<img width="1178" alt="Screen Shot 2020-01-31 at 2 59 39 PM" src="https://user-images.githubusercontent.com/58446641/73580417-5e5a7580-443a-11ea-80cf-ec2f8049563c.png">

<img width="1086" alt="Screen Shot 2020-01-31 at 3 00 15 PM" src="https://user-images.githubusercontent.com/58446641/73580436-687c7400-443a-11ea-84d5-79428bd12565.png">

And what I have in my palette.stories.mdx file:
```
import { LightTheme, Palette } from "..";
import { Meta, Story, Props, ColorPalette, ColorItem } from "@storybook/addon-docs/blocks";

<Meta title="Foundation|Colors"/>

# LUI Colors

## Color Palette
<Story name='Color Palette'>
  <ColorPalette>
    <ColorItem
      title="Palette.colors.red"
      
      colors={[
        Palette.colors.red[50],
        Palette.colors.red[100],
        Palette.colors.red[200],
        Palette.colors.red[300],
        Palette.colors.red[400],
        Palette.colors.red[500],
        Palette.colors.red[600],
        Palette.colors.red[700],
        Palette.colors.red[800],
        Palette.colors.red[900],
        Palette.colors.red.A100,
        Palette.colors.red.A200,
        Palette.colors.red.A400,
        Palette.colors.red.A700
      ]}
    />
  </ColorPalette>
</Story>
```

**Comment by shilman** [comment]
@justin-peterson-jdas like i said above, it's meant to be used outside of stories. your example is inside a `<Story>...</Story>`

**Comment by justin-peterson-jdas** [comment]
@shilman  apologies! I read the answer a different way. Thank you sir.

**Comment by shilman** [comment]
These are documentation-only components for now. They could be adapted to be used in stories, by providing providing an emotion theme in a decorator. But that's an advanced usage, and not the intended use. More docs forthcoming!

**Comment by bsgreenb** [comment]
@shilman Is it super advanced usage?

I have a GlobalStyle object I want to document in a non conventional way (using color swatches etc. from docs blocks)..

It seemed natural to me that I'd have a GlobalStyle.stories.tsx object, where I could `export const colors`

**Comment by shilman** [comment]
@bsgreenb are you using them inside stories? or inside the docs tab?

**Comment by bsgreenb** [comment]
@shilman Got it working with mdx (not inside story).  Yeah, it worked in the build inside a story

**Comment by VladRose** [comment]
@shilman 
Hey! Could you help me with emotion decorator for canvas? Is it really possible? If yes, can you advise me a starting point to make it? I really want to union docs and canvas, this would be so cool

**Comment by smellai** [comment]
I would like to be able to build the color palette dynamically with a loop, similar to what's described here: https://github.com/storybookjs/storybook/issues/7671#issuecomment-797064663 
I can't loop in mdx
