### ISSUE TITLE
addon-docs `show code` block bleeds CSS  classes

### ISSUE THREAD

**Issue by MrHus** [storybookjs/storybook#8758]
**Describe the bug**
The addon-docs uses a CSS class called `tag` which collides with CSS classes used in the 
style from the library it is documenting.

**To Reproduce**
1. Go to https://42bv.github.io/ui/storybook/?path=/docs/core-asynccontent--when-loaded
2. Click on show code
3. Notice the blue background on tags, and the missing text

**Expected behavior**
I expect to see a code block which can be read by the user.

**Screenshots**
![Screenshot 2019-11-08 at 09 46 41](https://user-images.githubusercontent.com/22608/68462462-e0a51600-020c-11ea-8968-cf892a6ad5b3.png)

**System:**
Environment Info:

  System:
    OS: macOS Mojave 10.14.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
    Yarn: 1.19.1 - ~/.nvm/versions/node/v10.16.3/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
  Browsers:
    Chrome: 78.0.3904.97
    Firefox: 70.0
    Safari: 13.0.3
  npmPackages:
    @storybook/addon-actions: 5.2.5 => 5.2.5 
    @storybook/addon-docs: 5.2.5 => 5.2.5 
    @storybook/preset-scss: 1.0.2 => 1.0.2 
    @storybook/preset-typescript: 1.1.0 => 1.1.0 
    @storybook/react: 5.2.5 => 5.2.5

**Comment by shilman** [comment]
Closing this as dupe to #9414 which has more detail
