### ISSUE TITLE
Previous story keyboard shortcut doesn't work right after a page load

### ISSUE THREAD

**Issue by yguedidi** [storybookjs/storybook#8759]
**Describe the bug**
The Alt+Left Arrow doesn't work right after a page load, but the Alt+Right Arrow does.
However, after clicking on the canvas, Alt+Left Arrow works properly.

**To Reproduce**
1. Got to a story that has stories before and after
2. Reload the page (F5)
3. Hit Alt+Right Arrow once, it works
4. Hit now Alt+Left Arrow, it doesn't work, this is the issue
5. But if you now click on the canvas to give it focus, Alt+Left Arrow will work as expected

**Expected behavior**
I expect that like the Alt+Right Arrow shortcut, the Alt+Left Arrow one work directly ater a page load, without focusing on the canvas

**System:**
```
Environment Info:

  System:
    OS: Linux 5.0 Debian GNU/Linux 9 (stretch) 9 (stretch)
    CPU: (8) x64 Intel(R) Core(TM) i7-4700HQ CPU @ 2.40GHz
  Binaries:
    Node: 12.13.0 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.12.0 - /usr/local/bin/npm
  npmPackages:
    @storybook/addon-centered: ^5.0.3 => 5.2.5 
    @storybook/addon-knobs: ^5.0.3 => 5.2.5 
    @storybook/addon-notes: ^5.0.3 => 5.2.5 
    @storybook/addon-viewport: ^5.0.3 => 5.2.5 
    @storybook/html: ^5.0.3 => 5.2.5 
    @storybook/theming: ^5.0.3 => 5.2.5 
```

**Comment by hsablonniere** [comment]
I have the same issue, in Firefox I think `Alt+Left` means history back so there's a conflict.

**Comment by hsablonniere** [comment]
Anyone?

**Comment by omril1** [comment]
In chrome as well, <kbd>alt + ⬅</kbd> means history back, seems to conflict and cause problems.

**Comment by kaiyoma** [comment]
I'm seeing this issue as well. Alt + Left is super janky.
