### ISSUE TITLE
Docs: Angular-props Use component param from the story return

### ISSUE THREAD

**Issue by CodeByAlex** [storybookjs/storybook#8762]
**Is your feature request related to a problem? Please describe.**
The adoption of angular props with docs would be a lot easier if we didn't have to specify the component twice in the stories file. The docs suggest adding "component: ComponentName" as a param: https://github.com/storybookjs/storybook/tree/next/addons/docs/angular. Would it be possible to us the component returned in the JSON of the story: 

export const story = () => {
  return {
    template: `<tag></tag>`,
    component: TagComponent, <----
  };
};

**Are you able to assist bring the feature to reality?**
no

**Comment by shilman** [comment]
Closing as dupe to https://github.com/storybookjs/storybook/issues/8673
