### ISSUE TITLE
addon-docs: Parser Hooks

### ISSUE THREAD

**Issue by JWambaugh** [storybookjs/storybook#8766]
**Is your feature request related to a problem? Please describe.**

We are currently using react-styleguidist and are considering switching to storybook for development and documentation. We wrote a custom parser for styleguidist that detects the CSS variables used in a component, and then automatically adds a table of CSS variables used to the documentation. So we want to make sure something similar is possible using storybook and addon-docs before we make the switch.

**Describe the solution you'd like**
I would like hooks to process the jsdoc comments before being rendered. react-styleguide provides such hooks by allowing you to provide your own [propsParser](https://react-styleguidist.js.org/docs/configuration.html#propsparser). Are there such hooks available for addon-docs?

**Describe alternatives you've considered**

**Are you able to assist bring the feature to reality?**
Maybe, depends on how difficult this would be to implement.

**Additional context**

**Comment by shilman** [comment]
@martamius There are in 5.3, which is going into beta next week. The hooks have been used to surface events/slots in Vue, inputs/outputs/methods in Angular, and so forth:

https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/multiframework.md#props-tables

Here's an example from Vue:

<img src= "https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/media/vue-hero.png?raw=true" />

It's all pretty new, so if you need more control than what's available, we'd love your input on that. cc @patricklafrance who's in the process of making a bunch of props improvements this week.

**Comment by shilman** [comment]
Closing this now -- I believe this is fully supported now in 5.3. Please let me know if you have any more questions!
