### ISSUE TITLE
Storyshot tests for all knobs

### ISSUE THREAD

**Issue by VikramTiwari** [storybookjs/storybook#8767]
**Is your feature request related to a problem? Please describe.**
Knobs add-on allows us to keep the stories straightforward and keep all the possible ways of rendering that specific component in options. But when we use storyshot testing, it tests only the default behavior. This by itself is sufficient generally, to test if the component is working. But as soon as you start tracking coverage, you can see that rest of the options aren't tested. To test rest of the options, you have to write a story for each one of those options. If I have a set of 4 options with 4 possible values for each, I would have to write and maintain 64 stories just to get coverage on that component. This defeats the purpose of using knobs add-on altogether.

**Describe the solution you'd like**
A possible solution could be to generate these possible stories in run time. This way we still test those possible options but don't have to maintain those cases manually.

**Describe alternatives you've considered**
Only other alternative is to write all the stories manually.

**Are you able to assist bring the feature to reality?**
I can give it a try.

**Additional context**
This feature has been previously mentioned in multiple PRs and issues but those issues are closed due to inactivity.

**Comment by shilman** [comment]
@VikramTiwari That sounds excellent! Do you want to sketch out a design here & get feedback? I'm thinking ideally this takes the form of a standalone addon that maybe we merge into the monorepo after it's been iterated a bit. What do you think?

**Comment by osdiab** [comment]
Hmm looks like this didn't fly, but I'm interested in this as well. I haven't thought much about how this would work yet, will comment with ideas as some time frees up
