### ISSUE TITLE
Custom PropsTable

### ISSUE THREAD

**Issue by iamdriz** [storybookjs/storybook#8783]
Is there an example anywhere of building a custom props table?
We're wanting to use it to list all of our Design Tokens... so it can't be auto-generated from a Component but we want to match the style and layout of our components prop tables.

We've imported the PropsTable component like so:

`import { PropsTable } from '@storybook/addon-docs/blocks';`

But haven't been able to source any examples of how to build one from scratch... from reading the source of the DocsPage components we've come up with something like:

```
<PropsTable props={{ name: 'Cam', type: 'hello', required: true, description: 'Example...' }} />
```

But we're not clear on the exact syntax to build a custom PropsTable... the above code is throwing us the error:

```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of 'MDXCreateElement'
```

**Comment by shilman** [comment]
Check out 

https://github.com/storybookjs/storybook/blob/next/lib/components/src/blocks/PropsTable/PropsTable.stories.tsx

**Comment by iamdriz** [comment]
@shilman Still seems to be giving the same error about the type being invalid?

```
<PropsTable rows={[<PropRow row={{
  name: '--primary-color',
  type: { name: 'string' },
  required: true,
  description: 'Primary color',
  defaultValue: '#FF0000',
}} />]} />
```

**Comment by shilman** [comment]
import { PropsTable } from '@storybook/components';

**Comment by iamdriz** [comment]
@shilman Cool that fixes the error... but now the rows are blank :/

![image](https://user-images.githubusercontent.com/801252/68596597-66d28e00-0493-11ea-8a9e-3bbace1ea278.png)

**Comment by bpeab** [comment]
@iamdriz @shilman Have you found a solution to this problem ? I have the same result with the console outputing the following: `Warning: Each child in a list should have a unique "key" prop.`.

**Comment by iamdriz** [comment]
@bpeab No we still have the blank rows as reported above.

**Comment by shilman** [comment]
@iamdriz Sorry missed your comment. Try:

```jsx
<PropsTable rows={[{
  name: '--primary-color',
  type: { name: 'string' },
  required: true,
  description: 'Primary color',
  defaultValue: '#FF0000',
}, {
  name: '--secondary-color',
  type: { name: 'string' },
  required: true,
  description: 'Secondary color',
  defaultValue: '#FF0000',
}]} />
```

**Comment by iamdriz** [comment]
@shilman Cool that works... Thanks!

**Comment by alexortizl** [comment]
Is building a custom props table still supported? I can't find the `PropsTable` component in storybook v6.4

**Comment by shilman** [comment]
@alexortizl https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#previewprops-renamed
