### ISSUE TITLE
Include css inside .stories.js file

### ISSUE THREAD

**Issue by JEricaM** [storybookjs/storybook#8787]
I would like to include css (not inline) inside my .stories.js files so I can manipulate the stories a little bit. For example, If I want to create a grid and show my component inside the grid I don't want to write css for each div, but I want to have a "global" css as for the components itself, but only for the stories.
Is it possible?

I use storybook with stencil.

Thank you

**Comment by shilman** [comment]
@JEricaM sorry for the slow response. does this do what you want?

https://github.com/storybookjs/storybook/tree/next/addons/cssresources
