### ISSUE TITLE
Build Storybook with Docs doesn't show Props Description

### ISSUE THREAD

**Issue by araligan** [storybookjs/storybook#8789]
**Describe the bug**
Running storybook locally `npm run storybook` doesn't have any issues on displaying the all the Props. When trying to build for deployment `npm run build-storybook -s public --docs` the Props data don't have any description and is missing some props

**Expected behavior**
Props details should be completely shown

**Screenshots**
Local:
![image](https://user-images.githubusercontent.com/10905326/68603124-aa081d80-04e2-11ea-9813-5b038d803ed2.png)

Deployed:
![image](https://user-images.githubusercontent.com/10905326/68603109-a1afe280-04e2-11ea-92dd-680ed66b6b8e.png)

**Code snippets**
```
...

CoreButton.propTypes = {
  /**
   * For button layout and style
   */
  appearance: PropTypes.oneOf(['primary', 'default', 'link', 'danger', 'facebook', 'google']),
  /**
   * Icon element to be added on the button
   */
  // eslint-disable-next-line react/require-default-props
  icon: PropTypes.element,
  /**
  * Change the state of the button to loading. This will show a spinner
  */
  isLoading: PropTypes.bool
};

CoreButton.defaultProps = {
  appearance: 'primary',
  isLoading: false,
};

export default CoreButton;
```

**System:**
  System:
    OS: Windows 10
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 8.11.3 - D:\Program Files\nodejs\node.EXE
    npm: 5.6.0 - D:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.387.0

   "@storybook/addon-a11y": "^5.2.5",
    "@storybook/addon-actions": "^5.2.5",
    "@storybook/addon-docs": "^5.2.5",
    "@storybook/addon-knobs": "^5.2.5",
    "@storybook/addon-links": "^5.2.5",
    "@storybook/addon-notes": "^5.2.6",
    "@storybook/addon-viewport": "^5.2.5",
    "@storybook/addons": "^5.2.5",
    "@storybook/react": "^5.2.5",

**Additional context**
Issue happens for both .js and .mdx files.
We deploy our storybook in AWS (S3)

**Comment by shilman** [comment]
Closing as dupe to #8140
