### ISSUE TITLE
viewMode enhancement

### ISSUE THREAD

**Issue by atanasster** [storybookjs/storybook#8790]
Adding a new Tab type of storybook addon generates an error:

`Warning: Failed prop type: Invalid prop `viewMode` of value `deps` supplied to `Preview`, expected one of ["story","info","docs","settings"]`

example usage: 
https://github.com/atanasster/storybook-addon-deps/blob/master/src/register.tsx

Currently `viewMode` prop for addons is declared in several places:

1. https://github.com/storybookjs/storybook/blob/d7c36532919f6fe20d090f2a95f6efd83858a1b2/lib/ui/src/app.js#L77

2. https://github.com/storybookjs/storybook/blob/d7c36532919f6fe20d090f2a95f6efd83858a1b2/lib/ui/src/components/layout/container.js#L556

3. https://github.com/storybookjs/storybook/blob/d7c36532919f6fe20d090f2a95f6efd83858a1b2/lib/ui/src/components/layout/desktop.js#L74

4. https://github.com/storybookjs/storybook/blob/d7c36532919f6fe20d090f2a95f6efd83858a1b2/lib/ui/src/components/layout/mobile.js#L204

5. https://github.com/storybookjs/storybook/blob/d7c36532919f6fe20d090f2a95f6efd83858a1b2/lib/ui/src/components/preview/preview.js#L316

This is a proposal to consolidate all those declarations into a single place to remove code duplication  and to allow a generic string as a possible viewMode value so an addon can register any type of Tab.

**Comment by ndelangen** [comment]
The typings say it can also be any string, the propTypes should be changed to allow this.

**Comment by shilman** [comment]
Gadzooks!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-beta.12 containing PR #8994 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
