### ISSUE TITLE
Story sort should be stable

### ISSUE THREAD

**Issue by tmeasday** [storybookjs/storybook#8792]
**Describe the bug**
We sort stories with `Array.prototype.sort()` which isn't guaranteed to be stable (as per JS spec).

For example in v8 <  v7 (Chrome <70, Node <12 (?)) sorting was not stable: https://v8.dev/blog/array-sort

**To Reproduce**
1. Consider official storybook: https://storybooks-official.netlify.com/?path=/story/ui-panel--default -- notice the story order in latest chrome:

<img width="223" alt="image" src="https://user-images.githubusercontent.com/132554/68625243-c2048f00-052c-11ea-9ec9-6f82def8ac75.png">

2. Notice the story order in Chromatic: (uses JSDOM, ie node sort)

<img width="381" alt="image" src="https://user-images.githubusercontent.com/132554/68625262-ce88e780-052c-11ea-8584-9678c1740792.png">

In theory the order should be wrong in Chrome 69 also but I haven't yet been able to reproduce.

**Expected behavior**
The stories should stay in order.

**Comment by shilman** [comment]
Good golly!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-alpha.44 containing PR #8795 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

**Comment by shilman** [comment]
Whoopee!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.8 containing PR #8795 that references this issue. Upgrade today to try it out!
