### ISSUE TITLE
Remove hierarchy separators configuration option.

### ISSUE THREAD

**Issue by tmeasday** [storybookjs/storybook#8793]
Although hierarchy separators (`hierararchySeparator` and `heirarchyRootSeparator`) are configurable, it is problematic from a maintenance perspective:

1. We need to carry the option around anywhere we want to split stories.
2. It makes it hard to look at a kind name and understand the hierarchy simply
3. In theory you could set a different separator for each story, although we don't actually support that.

Also, the separation of roots from groups is probably an unnecessary complication: 

 - It doesn't seem useful to have some stories with a root and some without in a automatic root called "others" (cf https://github.com/storybookjs/storybook/pull/8784)
 - Having a separate separator for roots is complicating things without clear benefit (why can't I use `|` twice in my kind?)

A proposal for where where want to get to:

1. A single path separator `/`, *not* configurable.
2. A single option `showRoots` that simply decides if the first group of *every* story is a root. This is purely a UI option and makes no "logical" change (e.g. it doesn't change the story order for keyboard shortcuts).

We'd like to deprecate the old behaviour in 5.3 and drop it in 6.0. Difficulties in doing so:

1. **People that are using different separators for aesthetic purposes.** (I think?) this is a fairly small proportion and it's not worth the maintenance complexity for this reason.

2. **People that are using different separators because they want to use one of the characters `'.', '|', '.'` in their actual names.** This proposed change would reduce that list of "reserved" characters to 1 (`'/'`) which I think is not too bad. If there's a lot of pushback we could consider an escape sequence to allow it but I am hopeful it won't be a big problem.

3. **People that are currently using `|` and `.` as separators** -- we can provide a codemod to change them to `/`s.

Here's a proposed way forward for 5.3 that avoids breaking changes until 6.0:

1. If the user is using custom separators: Retain the current behaviour but show a warning.

2. If the user is using default separators, not using the `showRoots` option, but has `|` or `.` in their kind names: retain the current behaviour, show a warning telling them to run the codemod, and add the `showRoots` option if they want to change the behaviour.

3. If the user is using default separators, not using the `showRoots` option, but has NO `|` or `.` in their kind names: use the new behaviour with `showRoots: false`. (This should be equivalent to the current behaviour)

4. If the user has set the `showRoots` option: use the new behaviour.

Likely we'll make `showRoots` default to `true` in 6.0, so users in group 3 will see a breaking change in 6.0 but it'll be easily fixed.

**Comment by shilman** [comment]
This is a great proposa

**Comment by tmeasday** [comment]
> Likely we'll make showRoots default to true in 6.0, so users in group 3 will see a breaking change in 6.0 but it'll be easily fixed

Actually considering this more, I think we will indeed not support this.

**Comment by shilman** [comment]
Zoinks!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-alpha.45 containing PR #8796 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
