### ISSUE TITLE
Jest Add-on: Can't change bar background color

### ISSUE THREAD

**Issue by kirstypeee** [storybookjs/storybook#8797]
**Is your feature request related to a problem? Please describe.**
The background colour for the results bar on the jest add-on is picked up automatically from my theme and I can't seem to override it. Unfortunately the variety of colours used for the text in the add-on are not accessible with our brand colour.

**Describe the solution you'd like**
I would like to either be able to pick my own background colour for that bar, or similar to the Accessibility add-on keep the bar a colour that you know works with the text and not grab the colour from my custom theme. 

**Describe alternatives you've considered**
I looked in the doco for any style props and tried to overide with CSS but I could only apply styles to the canvas part.

**Are you able to assist bring the feature to reality?**
Yes

**Additional context**
The desired visuals:
![Screen Shot 2019-11-12 at 4 30 28 pm](https://user-images.githubusercontent.com/2062179/68645012-e41d0200-056a-11ea-92a0-5d8d690a2029.png)

Actual:
![Screen Shot 2019-11-12 at 4 30 33 pm](https://user-images.githubusercontent.com/2062179/68645031-f008c400-056a-11ea-9ad0-b57b01ea3587.png)

As a side note: I'm really enjoying using storybook to set up our design system/component library, thanks for all the great work!!

**Comment by shilman** [comment]
Hi @kirstypeee I think we'd accept a PR to make the background behave like the accessibility add-on. Any interest in putting that together? cc @CodeByAlex
