### ISSUE TITLE
`@storybook/core` adds loaders after presets

### ISSUE THREAD

**Issue by mrmckeb** [storybookjs/storybook#8804]
**Describe the bug**
Whilst developing the new preset for Create React App, we've found that Storybook is adding loaders _after_ the preset.

https://github.com/storybookjs/storybook/blob/5d967df94cad3cf9bb92eae71d8416156e9ede11/lib/core/src/server/preview/base-webpack.config.js#L42-L75

The duplicate loaders create failures. We can solve this by removing the first instantiation of the loaders in the preset - however, as we'd be removing the CRA loaders, this could result in unexpected behaviour for users. Some things work in Storybook and not in their applications, and visa versa.

**To Reproduce**
Using the preset for CRA, run Storybook with `--debug-webpack`, and note the duplicated loaders at the end of the config.

**Expected behavior**
No loaders should be added after the preset.

**Comment by shilman** [comment]
See also: https://gist.github.com/shilman/bc9cbedb2a7efb5ec6710337cbd20c0c#gistcomment-3080725

**Comment by vanessayuenn** [comment]
Hi! I am going through and cleaning up old issues in the repo. We just shipped a ton of improvements in Storybook 7.0, and I suspect this bug might be fixed already. Can you please try it out? If this issue persists with the latest version, please open a new bug report with a 7.x reproduction. Thank you so much! 🙏🏼
