### ISSUE TITLE
Ember Documentation on Addons

### ISSUE THREAD

**Issue by proverbial-ninja** [storybookjs/storybook#8805]
**Is your feature request related to a problem? Please describe.**
Can't seem to find any  documentation on how to use the addons with ember.... like the notes-addon

**Are you able to assist bring the feature to reality?**
no 

**Additional context**
been trying to itegrate notes, 

```
export const hello = () => ({
  template: hbs`<button {{action onClick}}>Hello Button</button>`,
notes,"Awesome Notes.. The Best Notes",
  context: {
    onClick: action('clicked'),
  },
});
```

**Comment by dbendaou** [comment]
You can try this 
```js 
export const button = () => {
  return {
    template: hbs`
      <button>
         <h4>title</h4>
      </button>
    `,
  };
};

button.story = {
  parameters: {
    notes: {
      markdown: `
      ##Component usage with block 
      The component is call as any other example but with a block instead of a title param 
    `,
    },
  },
};
```

**Comment by proverbial-ninja** [comment]
> You can try this
> 
> ```js
> export const button = () => {
>   return {
>     template: hbs`
>       <button>
>          <h4>title</h4>
>       </button>
>     `,
>   };
> };
> 
> button.story = {
>   parameters: {
>     notes: {
>       markdown: `
>       ##Component usage with block 
>       The component is call as any other example but with a block instead of a title param 
>     `,
>     },
>   },
> };
> ```

@dbendaou is this documented somewhere ??

**Comment by dbendaou** [comment]
Not yet lol, but my PR have been merged so it should be in the next release https://github.com/storybookjs/storybook/pull/8978

**Comment by dbendaou** [comment]
And if you want to know more about markdown you can go there https://github.com/storybookjs/storybook/pull/8978
You should be able to import you markdown file like documented 
```

import markdownNotes from './someMarkdownText.md';

...
parameters: {
    notes: {
      markdown: markdownNotes,
    },
...
```
