### ISSUE TITLE
No scroll bar on documentation-only MDX pages

### ISSUE THREAD

**Issue by bradringel** [storybookjs/storybook#8809]
**Describe the bug**
On a page rendered from a `stories.mdx` file with no stories defined (documentation only), I don't have a scrollbar even though the content is overflowing

**To Reproduce**
1. Create a documentation only MDX page with enough content that it runs off the screen
2. Open the rendered page to the Docs tab

**Expected behavior**
When the content overflows, users should be able to scroll to see it

**Screenshots**
![image](https://user-images.githubusercontent.com/19391834/68690988-f7b37300-0540-11ea-9e46-52b957842a57.png)

**Code snippets**
If applicable, add code samples to help explain your problem.

**System:**
Environment Info:

  System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz
  Binaries:
    Node: 12.12.0 - ~/.nvm/versions/node/v12.12.0/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.11.3 - ~/.nvm/versions/node/v12.12.0/bin/npm
  Browsers:
    Chrome: 78.0.3904.97
    Firefox: 58.0.2
    Safari: 13.0.3
  npmPackages:
    @storybook/addon-actions: ^5.2.6 => 5.2.6
    @storybook/addon-docs: ^5.2.6 => 5.2.6
    @storybook/addon-knobs: ^5.2.6 => 5.2.6
    @storybook/addon-links: ^5.2.6 => 5.2.6
    @storybook/addon-storysource: ^5.2.6 => 5.2.6
    @storybook/addons: ^5.2.6 => 5.2.6
    @storybook/react: ^5.2.6 => 5.2.6

**Additional context**

**Comment by ndelangen** [comment]
I can't reproduce this, do you have a link where this problem exists?

**Comment by ndelangen** [comment]
<img width="1061" alt="Screenshot 2019-11-16 at 15 48 52" src="https://user-images.githubusercontent.com/3070389/68994949-b4326f00-0888-11ea-81b7-a54194c6c263.png">

**Comment by bradringel** [comment]
Hi sorry for the delay, I'm not sure what config files are needed to reproduce this issue, but here's what i'm seeing in our project:

![image](https://user-images.githubusercontent.com/19391834/70921406-392cb780-1ff2-11ea-84ae-370b6f50d8be.png)

As you can see, the body tag has `overflow-y: hidden` set as its styling, which is preventing the scrollbar from showing

**Comment by bradringel** [comment]
I just looked a bit more closely, and realized that these are our styles from our application that I accidentally copied into preview-head.html. Thanks

**Comment by tuanluu-agilityio** [comment]
```
As you can see, the body tag has overflow-y: hidden set as its styling, which is preventing the scrollbar from showing
```
I got same issue and just override this to show scrollbar. Thanks your noted!

**Comment by Elidor00** [comment]
I had the same problem and the solution seems to be overriding the property overflow-y. Do you think it is appropriate to reopen the issue with another example?
