### ISSUE TITLE
StoryBook for Vue: [Vue warn]: Failed to mount component: template or render function not defined

### ISSUE THREAD

**Issue by Brotzka** [storybookjs/storybook#8812]
My dependecies:

```
"dependencies": {
    "bootstrap": "^4.3.1",
    "gridsome": "^0.7.0",
    "sass-resources-loader": "^2.0.1",
    "vue": "^2.6.10"
  },
  "devDependencies": {
    "@babel/core": "^7.7.2",
    "@storybook/addon-actions": "^5.2.5",
    "@storybook/addon-links": "^5.2.5",
    "@storybook/addons": "^5.2.5",
    "@storybook/vue": "^5.2.6",
    "babel-loader": "^8.0.6",
    "babel-preset-vue": "^2.0.2",
    "node-sass": "^4.13.0",
    "sass-loader": "^8.0.0",
    "style-resources-loader": "^1.2.1",
    "vue-loader": "^15.7.2",
    "vue-template-compiler": "^2.6.10"
  }
```

I want to build my frontend using [Gridsome][1] and [StoryBook][2] to offer our developers and product-managers a web-based component-library.

Gridsome is working as it should. Running StoryBook via `npm run storybook` works. But when I visit the page in Chrome there is console-error saying: *[Vue warn]: Failed to mount component: template or render function not defined.*

I've followed the StoryBook documentation to setup my settings. But I've created a customized webpack.config.js because I have global (scss) resources which should be loaded and injected in all my components (such as global variables).

I think the problem is somewhere in my webpack-file. But changing things results in more errors^^

My Component:

    <template>
        <h1 :style="styles">
            <slot></slot>
        </h1>
    </template>
    <script>
        export default {
            name: "FaaH1",
            props: {
                color: {
                    type: String,
                    required: false
                }
            },
            computed: {
                styles(){
                    return {
                        color: this.color
                    }
                }
            }
        }
    </script>
    <style scoped lang="scss">
        h1 {
            font-size:   $font-size-base * 2.5;
            color: $secondary;
            text-transform: uppercase;
            font-weight: $font-weight-extrabold;
        }
    </style>

My StoryBook Story:

    import { linkTo } from "@storybook/addon-links";
    import Vue from 'vue';
    
    import FaaH1 from "../src/components/texts/headings/FaaH1";
    
    export default {
        title: 'Headings',
    };
    
    export const faaH1 = () => ({
        components: {FaaH1},
        template: '<faa-h1>Heading H1</faa-h1>'
    });

My config.js:

    import { configure } from '@storybook/vue';
    
    // Components-Import
    import FaaH1 from "../src/components/texts/headings/FaaH1";
    
    import Vue from 'vue';
    
    Vue.component('faa-h1', FaaH1);
    
    // automatically import all files ending in *.stories.js
    configure(require.context('../stories', true, /\.stories\.js$/), module);

And finally my webpack.config.js

    const path = require('path');
    
    module.exports = async ({config, mode}) => {
        config.module.rules.push({
            test: /\.scss$/,
            use: ['style-loader', 'css-loader', 'sass-loader'],
            include: path.resolve(__dirname, '../src/assets/styles/'),
        });
    
        config.module.rules.push({
            test: /\.vue$/,
            use: 'vue-loader'
        });
    
        config.module.rules.push({
            test: /\.css$/,
            use: [
                { loader: 'vue-style-loader' },
                { loader: 'css-loader', options: { sourceMap: true } },
            ]
        });
    
        config.module.rules.push({
            test: /\.scss$/,
            use: [
                { loader: 'vue-style-loader' },
                { loader: 'css-loader', options: { sourceMap: true } },
                { loader: 'sass-loader', options: { sourceMap: true } },
                { loader: 'sass-resources-loader',
                    options: {
                        sourceMap: true,
                        resources: [
                            path.resolve('../src/assets/styles/_globals.scss')
                        ]
                    }
                }
            ]
        });
    
        return config;
    };

  [1]: https://gridsome.org/
  [2]: https://storybook.js.org/

**Comment by Pumba-Coder** [comment]
@Brotzka Did you have any success with this? i'm currently getting the same issue.

**Comment by shilman** [comment]
Closing as a duplicate to #6932 to consolidate discussion there
