### ISSUE TITLE
MDX stories cannot be nested within other JSX

### ISSUE THREAD

**Issue by Peeja** [storybookjs/storybook#8814]
I'd like to use markup to position and present my stories, but that breaks the stories.

**To Reproduce**
1. Add the following to an MDX stories file:

```jsx
<Meta title="Buttons" />

<div style={{ border: '1px solid red' }}>
  <Story name="Simple Button">
    <button>A button</button>
  </Story>
</div>
```

2. Pull up Storybook and the `Buttons` stories.
3. See:

![image](https://user-images.githubusercontent.com/2407/68717848-cd2fdd00-0575-11ea-8d96-5ccbec000438.png)

**Desired behavior**
* A `Buttons/Simple Button` story would exist, consisting of `<button>A button</button>`.
* The doc would render that story inside a red rectangle.

**System:**
```
Environment Info:

  System:
    OS: macOS High Sierra 10.13.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 12.12.0 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 78.0.3904.97
    Firefox: 69.0.2
    Safari: 13.0.2
  npmPackages:
    @storybook/addon-a11y: 5.2.5 => 5.2.5 
    @storybook/addon-actions: 5.2.5 => 5.2.5 
    @storybook/addon-docs: ^5.3.0-alpha.43 => 5.3.0-alpha.43 
    @storybook/addon-knobs: 5.2.5 => 5.2.5 
    @storybook/addon-storyshots: 5.2.5 => 5.2.5 
    @storybook/addon-viewport: 5.2.5 => 5.2.5 
    @storybook/react: 5.2.5 => 5.2.5 
    @storybook/theming: 5.2.5 => 5.2.5 
```

**Comment by shilman** [comment]
`Story` elements need to be placed either at the top level or directly underneath `Preview` elements. Adding arbitrary support is a feature request.

**Comment by Peeja** [comment]
@shilman Darn. Thanks, I've updated the description to read that way.

Is that an intentional design decision, or just all that's been implemented so far? Would the project be open to this change? If I were going to try to PR it, are there any challenges I should be aware of?

**Comment by shilman** [comment]
@Peeja sorry I missed this. Yeah this was intentional, just to keep things simple & fast. Maybe a PR for one-level deep search?

**Comment by Peeja** [comment]
@shilman It should be fast enough to do a full-depth search, no? I'm imagining searching the element tree rendered by the MDX directly, not the full eventual component tree. But I think we could make it so any use of `<Story>` directly in the MDX at any depth would show up.

WDYT?

**Comment by shilman** [comment]
Yeah, you're probably right!

**Comment by Peeja** [comment]
Cool! No idea when I'll get a chance, but I'll give that a shot sometime.

**Comment by sarahbethfederman** [comment]
Would love to see this happen! I have things nested with layout components that I would like to be able to make into Stories
