### ISSUE TITLE
Configure the width of the iframe just as we can the height

### ISSUE THREAD

**Issue by grouchal** [storybookjs/storybook#8816]
**Is your feature request related to a problem? Please describe.**
I would like to be able to configure the iframe width in the same way I can already configure the height.

**Describe the solution you'd like**
To add a parameter similar to `iframeHeight` that will configure the width of the iframe. Ideal name would be `iframeWidth`

**Describe alternatives you've considered**
Any other method to set the default width of the iframe and override for different stories.

**Are you able to assist bring the feature to reality?**
Maybe...

**Additional context**
No

**Comment by alonsosfera** [comment]
Hey, can I work on this?

**Comment by shilman** [comment]
@alonsosfera That would be awesome! 🙏

**Comment by vineetsgr07** [comment]
Hi @shilman, Can I pick this one? @alonsosfera, let me know if you going to look into it.

**Comment by shilman** [comment]
He’s already got a PR open and it’s on my plate to merge @vineetsgr07 ! Thanks for the offer!

**Comment by KeertiSaikrishna** [comment]
Hi @shilman I see the PR fixing this issue was closed, can i pick this one up?

**Comment by valentinpalkovic** [comment]
This should be configurable with the https://storybook.js.org/docs/essentials/viewport addon. Closing.
