### ISSUE TITLE
Failed prop type: The prop `active` is marked as required in `<<anonymous>>`, but its value is `undefined`.

### ISSUE THREAD

**Issue by ltodorov** [storybookjs/storybook#8819]
**Describe the bug**
```
Warning: Failed prop type: The prop `active` is marked as required in `<<anonymous>>`, but its value is `undefined`.
    in Unknown (created by MobileLayout)
    in MobileLayout
    in div (created by Context.Consumer)
    in Styled(div)
    in Unknown
    in Unknown (created by SizeMeRenderer(Component))
    in SizeMeReferenceWrapper (created by SizeMeRenderer(Component))
    in SizeMeRenderer(Component) (created by SizeMe(Component))
    in SizeMe(Component) (created by Manager)
    in ThemeProvider (created by Manager)
    in Manager (created by Context.Consumer)
    in Location (created by QueryLocation)
    in QueryLocation (created by Root)
    in LocationProvider (created by Root)
    in HelmetProvider (created by Root)
    in Root
```
Upgraded Storybook from 5.2.4 to 5.2.6. This warning message appears in browser's console when I open the page in mobile view. It doesn't appear on desktop or in version 5.2.4.

**To Reproduce**
1. Visit Storybook locally
2. Change device type in Chrome Dev tools to mobile
3. Reload the page

**Expected behavior**
No warnings should appear in console. Like it was in 5.2.4.

**Screenshots**
N/A

**Code snippets**
N/A

**System:**
System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
  Binaries:
    Node: 12.13.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.12.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
    Chrome: 78.0.3904.97 (Official Build) (64-bit)
    Firefox: 70.0.1 (64-bit)

**Additional context**
package.json
```json
"devDependencies": {
    "@babel/core": "7.6.4",
    "@storybook/addon-a11y": "5.2.6",
    "@storybook/addon-actions": "5.2.6",
    "@storybook/addon-cssresources": "5.2.6",
    "@storybook/addon-knobs": "5.2.6",
    "@storybook/addon-notes": "5.2.6",
    "@storybook/react": "5.2.6",
    "@types/storybook__react": "4.0.2",
    "babel-loader": "8.0.6"
  },
```

**Comment by shilman** [comment]
Closing as dupe to https://github.com/storybookjs/storybook/issues/5910 (and re-opening that)
