### ISSUE TITLE
Using media queries in decorators

### ISSUE THREAD

**Issue by iamdriz** [storybookjs/storybook#8820]
I have the following decorator in my stories:
```
export default {
    title: 'Components/Button',
    decorators: [storyFn => <div style={{ backgroundColor: 'black', padding: '24px' }}>{storyFn()}</div>],
};
```
This is because the elements support dark mode out of the box so need a black background when displayed in the Docs...

However I only want this when in Dark Mode...

So I need something like:
~~~
export default {
    title: 'Components/Button',
    decorators: [storyFn => <div style={{ @media(prefers-color-scheme: dark) { backgroundColor: 'black', } padding: '24px' }}>{storyFn()}</div>],
};
~~~

But it doesn't like that syntax (obviously)... how can you add media queries into the decorator?

**Comment by iamdriz** [comment]
Anyone got any ideas on how to solve this?

**Comment by iamdriz** [comment]
😬 pretty please? ❤️

**Comment by Bowriverstudio** [comment]
Did you manage to solve this issue?

**Comment by aldrichdev** [comment]
If you are using MUI and Emotion, it is possible via an Emotion CSS object, which you add to the decorator div.

https://gist.github.com/aldrichdev/08815f3cc7963c34c6d650a9b1d7c9b8
