### ISSUE TITLE
Story Source addon code highlighting 

### ISSUE THREAD

**Issue by subelta** [storybookjs/storybook#8821]
When using Story Source addon and adding stories in one file, code in the snippet  doesn't get highlighted when click on different stories, no auto scroll either

**Steps to reproduce the behavior:**
1. Install storysource addon
2. add some stories in Component.stories.tsx file using storiesOf API 
3. Click on a story in UI
4. Code snippet doesn't change - source code of separate story doesn't get highlighted, no auto scroll either

**Expected behaviour**
When click on a story, storybook auto scrolls file to the beginning of this particular story's code and highlights this piece of code, like it happens with Ring UI storybook

**Code snippets**
file top
~~~
import React from 'react'
import { withKnobs } from '@storybook/addon-knobs'
import { storiesOf } from '@storybook/react'

import { Component } from './Component'
...

const stories = storiesOf('Component', module)
stories.addDecorator(withKnobs)
~~~

story example
`stories.add('inherit font from wrappers', () => {
	return (
		<Component />
	)
})`

**System:**
System:
    OS: macOS 10.15.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 78.0.3904.97
    Firefox: 70.0.1
    Safari: 13.0.3``

**Comment by wolfmarco** [comment]
I was surprised to read that there should be this feature. This would really be very helpful if the relevant code would be directly visible without the reader having to scroll there manually. I am using Storybook for HTML with this addon and this feature has never worked for me before.

    "@babel/core": "^7.6.4",
    "@storybook/addon-storysource": "^5.2.6",
    "@storybook/html": "^5.2.6",
    "babel-loader": "^8.0.6",

**Comment by subelta** [comment]
Ain't fixed yet

**Comment by shilman** [comment]
I think storysource only works with chained stories. So:

```js
storiesOf(...).addDecorator(...).add(...)
```

Not:

```js
const stories = storiesOf(...)
stories.addDecorator(...)
...
```

**Comment by subelta** [comment]
> I think storysource only works with chained stories. So:
> 
> ```js
> storiesOf(...).addDecorator(...).add(...)
> ```
> 
> Not:
> 
> ```js
> const stories = storiesOf(...)
> stories.addDecorator(...)
> ...
> ```

Sorry for delayed response, and thanks, it does work with chained stories, but according to this: https://github.com/storybookjs/storybook/issues/6136 , I get the impression that it's supposed to work without chaining on 5.2.x and I'm on 5.2.8

<img width="257" alt="Screenshot 2020-01-08 at 14 33 41" src="https://user-images.githubusercontent.com/40162440/71975560-546f9900-3225-11ea-8140-ff658859e2a7.png">

<img width="286" alt="Screenshot 2020-01-08 at 14 33 14" src="https://user-images.githubusercontent.com/40162440/71975582-618c8800-3225-11ea-9956-1239b15ba10b.png">

It's not that big of a deal for me though, so you can close this if it's not worth fixing in the light of new CSF API
