### ISSUE TITLE
Addon-docs: Rich props table UI

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#8828]
## Why

Prop types & their default values can be quite large, making it hard to skim the table. If we abstract this into a `summary` / `detail` representation, we can increase readability without sacrificing information.

## What

Design by @domyen :

![rich-props-design](https://user-images.githubusercontent.com/488689/68827194-fbc7c800-06db-11ea-8422-af814422eb6f.png)

Also, related to #7943 cc @atanasster

**Comment by shilman** [comment]
Yowza!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-alpha.45 containing PR #8826 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by patricklafrance** [comment]
@fraincs

**Comment by shilman** [comment]
Hurrah!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-beta.3 containing PR #8887 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
