### ISSUE TITLE
Ability to generate a copy button with arbitrary text using CSF

### ISSUE THREAD

**Issue by priyajeet** [storybookjs/storybook#8837]
As a workaround to https://github.com/storybookjs/storybook/issues/7772 I would like to have a way to add arbitrary text and it show up as a copy button using CSF format. So that my components docs page shows a copy-able import path.

Using MDX format one could generate this
<img width="806" alt="Screen Shot 2019-11-13 at 4 15 55 PM" src="https://user-images.githubusercontent.com/1075325/68903792-0fc9f480-06f1-11ea-856c-7e9332875cf1.png"> by using code like
<img width="561" alt="Screen Shot 2019-11-14 at 3 12 23 PM" src="https://user-images.githubusercontent.com/1075325/68903855-34be6780-06f1-11ea-9ae7-583b04ecdc1b.png">

Haven't found a way to do this using CSF. When importing an .md file within a CSF module, it just renders like a regular MD without a copy button.

**Comment by lana-k** [comment]
I managed to add text (e.g. component import string) with a copy button in docs  using empty string after ``` like this:

```
import Dropdown from '@components/Dropdown'

export default {
  title: 'Dropdown',
  component: Dropdown,
  parameters: {
      docs: {
          description: {
              component: "This is component description" + "\n\n" +
              "```" + "\n\n" +
              "import DropdownRemote from '@components/Elements/Syncfusion/DropdownRemote'"+ "\n" +
              "```"
          },
      },
  },
...
```
