### ISSUE TITLE
Use constructor inside a story

### ISSUE THREAD

**Issue by RobbertWolfs** [storybookjs/storybook#8840]
Is it possible to inject a service inside a storybook using a contstructor or something else?

We are implementing storybook with our angular components. And it would be nice if we can do something like:

```ts
export const story = () => ({
    template: `
        <my-component (click)="clicked()"></my-component>
    `,
    constructor(private customService: MyCustomService): void {
    },
    props: {
        clicked(): void {
            this.customService.doSomething();
        }
    }
});
```

**Comment by melodi24** [comment]
Did you ever figure this out? I am trying to do the same thing and so far the only thing I've found that works is wrapping the the component I want to test inside of a parent component which injects the service. It's definitely not ideal.

**Comment by RobbertWolfs** [comment]
No never figured this out... Still waiting of this is possible..

**Comment by dimitriy-k** [comment]
I have similar problem, I want to build FormGroup with FormBuilder, but cannot figure out how to do it for story, because the is no constructor, so I cannot inject FormBuilder, and where can I call method like:

```
this.form = this.formBuilder.group({
      input: ['', Validators.required],
      email: ['', Validators.email],
    });
```

**Comment by Simon245** [comment]
> I have similar problem, I want to build FormGroup with FormBuilder, but cannot figure out how to do it for story, because there is no constructor, so I cannot inject FormBuilder, and where can I call method like:
> 
> ```
> this.form = this.formBuilder.group({
>       input: ['', Validators.required],
>       email: ['', Validators.email],
>     });
> ```

Also trying to work this out. Did you find a way to do this?

**Comment by dimitriy-k** [comment]
> Also trying to work this out. Did you find a way to do this?

I just build `FormGroup`:

```
import { FormGroup, FormControl, FormsModule, ReactiveFormsModule } from '@angular/forms';

export const dateRange = () => ({
  moduleMetadata: {
    imports: [
      ReactiveFormsModule,
      FormsModule,
    ],
  },
  component: MyComponent,
  template: `
  <form [formGroup]="formGroup">
    <my-form-field formControlName="formControl"></my-form-field>
    <my-form-field formControlName="formControlPrefilled"></my-form-field>
  </form>
  `,
  props: {
    formGroup: new FormGroup({
      dropdown: new FormControl(null),
      formControlPrefilled: new FormControl({ start: 21, end: 345 }),
    }),
  },
});


```
