### ISSUE TITLE
After Refactoring Storybook Stories Into TypeScript, 'select' Knob Add-on No Longer Works

### ISSUE THREAD

**Issue by whenmoon** [storybookjs/storybook#8844]
**Describe the bug**

I have just refactored Storybook stories to be written in TypeScript. Now, the `select` add-on method asks for 3 - 4 arguments. When I give it the third argument which is a default for color, the selection box no longer changes the color / works / does anything.

**Expected behavior**

I expect to be able to make a selection from using the `select` knob and change a color. 

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

Here is my previous JS that works:

`select('Spinner color', ['green', 'dark'])`

Now with TS, I have to add a default, it compiles but it stops the selection knob actually changing anything in the story:

`select('Spinner color', ['green', 'dark'], 'dark')`

[Here are the docs](https://github.com/storybookjs/storybook/tree/master/addons/knobs) that suggest this should work.

**System:**
Please paste the results of `npx -p @storybook/cli@next sb info` here.

  System:
    OS: macOS Mojave 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  Binaries:
    Node: 12.3.1 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 78.0.3904.97
    Firefox: 67.0.1
    Safari: 12.1.1
  npmPackages:
    @storybook/addon-actions: 5.2.5 => 5.2.5
    @storybook/addon-knobs: 5.2.5 => 5.2.5
    @storybook/addon-links: 5.2.5 => 5.2.5
    @storybook/react: 5.2.5 => 5.2.5

**Additional context**

**Comment by Beni27** [comment]
same issue here...

**Comment by ndelangen** [comment]
@emilio-martinez could you take a look at this?
