### ISSUE TITLE
Addon-a11y: CI support

### ISSUE THREAD

**Issue by Peeja** [storybookjs/storybook#8845]
We'd like our components to be accessible, so we use the `a11y-addon`. But it's easy to forget to look at that all the time. Having the result in CI (or even better, in a command that can also run locally from the command line) would help a lot to make sure we cover our bases.

I see that that's on the [roadmap](https://github.com/storybookjs/storybook/tree/next/addons/a11y#roadmap) already. Has the path to get there been thought out yet? If I were to try to make that happen, as someone not at all familiar with the code yet, is there anything I should know going in?

**Comment by shilman** [comment]
@Peeja this would be amazing! You might take a look at storyshots as an example of a standalone CI process that uses storybook's story store?

https://github.com/storybookjs/storybook/tree/next/addons/storyshots

**Comment by diegoNutmeg** [comment]
+1

**Comment by shilman** [comment]
FYI, this appears to be work in progress by @Hypnosphi here: https://github.com/storybookjs/storybook/pull/8934

**Comment by Hypnosphi** [comment]
It's actually ready to use with current beta, see https://github.com/storybookjs/storybook/tree/next/addons/storyshots/storyshots-puppeteer#axetest
