### ISSUE TITLE
[addon-docs] Documentation is missing if component is exported with a higher order component (like React.memo)

### ISSUE THREAD

**Issue by laplacesdemon** [storybookjs/storybook#8846]
**Describe the bug**
When exporting a component like the following, the docs from comments are embedded in the "docs" page:

```
export default MyComponent
```

But it's not the case if it's exported like this:

```
export default React.memo(MyComponent);

// or any other HOC:
// export default pipe(withErrorBoundary, withMemo)(MyComponent)
```

I've tested it in the new story style:

```
import MyComponent from '..';

export default {
title: 'MyComponent',
component: MyComponent
}

export const MyStory = ...
``` 

**Expected behavior**
The docs should be embedded in the docs page:
<img width="600" alt="Screen Shot 2019-11-15 at 11 01 47 AM" src="https://user-images.githubusercontent.com/752529/68968435-61c55580-0797-11ea-94a1-2face76b2ea1.png">

**Current Behavior**
The docs and props are not embedded, only the stories are visible.
<img width="690" alt="Screen Shot 2019-11-15 at 10 58 43 AM" src="https://user-images.githubusercontent.com/752529/68968289-0e530780-0797-11ea-9c0d-308ed83aa492.png">

**Comment by shilman** [comment]
closing as dupe to #8361
