### ISSUE TITLE
Addon documentation for CSF

### ISSUE THREAD

**Issue by dvnrsn** [storybookjs/storybook#8849]
**Is your feature request related to a problem? Please describe.**
The [Addon docs](https://storybook.js.org/docs/addons/introduction/) seem too focused on `storiesOf` API and have no examples of CSF which seems to be the way moving forward. 

**Describe the solution you'd like**
Can I add some examples for CSF?

**Describe alternatives you've considered**
Is it intentional to not have docs for CSF here but to focus on `storiesOf`? Doesn't seem likely.

**Are you able to assist bring the feature to reality?**
yes

**Additional context**
Would like to see something like
```js
import React from 'react';

export default {title: 'Button'}
export const Button = () => <button>Hello Button</button>

const styles = {
  textAlign: 'center',
};
const CenterDecorator = storyFn => <div style={styles}>{storyFn()}</div>;

Button.story = {
  decorators: [
    CenterDecorator
  ]
};
```

**Comment by shilman** [comment]
@dvnrsn CSF is a relatively new thing and not all of the docs have been migrated yet. If you wouldn't mind migrating the addon docs, that would be 💯💯💯 

No need to preserve the `storiesOf` strictly. Maybe leave an example here and there for people who are still stuck on that format or want to dynamically generate stories (which is not possible in CSF).

Many thanks!!! 🙏

**Comment by dvnrsn** [comment]
https://github.com/storybookjs/storybook/pull/9059/files
