### ISSUE TITLE
Move remaining addon-options to be configurable via `manager.js`

### ISSUE THREAD

**Issue by tmeasday** [storybookjs/storybook#8860]
Currently, global parameters are used to inject manager UI options. And this is the documented way of setting things up.

We moved `theme` into a new api in `manager.js`, we should move over all UI configurations: https://storybook.js.org/docs/configurations/options-parameter/#docs-content

**Comment by shilman** [comment]
Yowza!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-beta.11 containing PR #8871 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
