### ISSUE TITLE
Migrate all examples to tri-config

### ISSUE THREAD

**Issue by ndelangen** [storybookjs/storybook#8861]
dev-kits and html-example are already migrated, all others should be too.

When users look at our examples, we should show them what the latest and greatest method for configuration is.

**Comment by shilman** [comment]
w00t!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-beta.10 containing PR #8942 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
