### ISSUE TITLE
Presets: Allow recursive presets via function

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#8864]
Most preset exports are functions that take the current value and an options object and return an updated value. For instance:

```ts
export function addons(entry: any[] = [], options: any) {
  return [...entry, '@storybook/addon-actions/register'];
}
```

However, `presets` is currently just an array:

```ts
export const presets = ['@storybook/addon-docs/preset'];
```

It would be great if presets could also be a function, e.g.

```ts
type Preset = string | { name: string, options: any };

export function presets(p: Preset[] = [], options?: Record<string, any>): Preset[] {
  return ['@storybook/addon-docs/preset'];
}
```

This way presets that include presets can configure them as a function of their options, similar to our convention for how presets configure loaders.

**Comment by ndelangen** [comment]
@shilman 

I've run into some trouble with spec'ed API.

I'll open a PR momentarily with a slightly tweamed API

```ts
type Preset = string | { name: string, options: any };

export function presets(options: Record<string, any>): Preset[] {
  return ['@storybook/addon-docs/preset'];
}
```

The present function CANNOT change the existing array of presets anymore.

Its returned array is injected into the list.

**Comment by shilman** [comment]
Yay!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-beta.6 containing PR #8921 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
