### ISSUE TITLE
exported forwardRefs fail to render

### ISSUE THREAD

**Issue by seanmcintyre** [storybookjs/storybook#8870]
### Description
When using a custom webpack config with `@storybook/addon-storysource/loader` in Storybook `^5.2.0` exported `forwardRef` components fail to render with the error:
```
Objects are not valid as a React child (found: object with keys {$$typeof, render}).
If you meant to render a collection of children, use an array instead.
```

### Reproduced At
https://github.com/seanmcintyre/storybook-storysource-export-react-bug
https://github.com/seanmcintyre/storybook-storysource-export-react-bug/blob/master/src/Test.tsx#L12

`export const VimeoV = forwardRef()` does not work.
`const VimeoV = forwardRef()` works.

### Screenshots
<div align="center">
<img width="300" alt="Screen Shot 2019-10-23 at 12 12 22 AM" src="https://user-images.githubusercontent.com/319302/69093807-3eabd780-0a1d-11ea-8760-54e61cf7e04a.png"><img width="300"src="https://user-images.githubusercontent.com/319302/69093808-3eabd780-0a1d-11ea-887d-f5d566fae553.png">
</div>

### Comments
I have not been to discern if this is related to #5974, #4787, #6925.

**Comment by pocka** [comment]
@seanmcintyre 
The problem is that `@storybook/addon-storysource/loader` is applied to non-story files, in this case `src/Test.tsx`. You need to set the loader separately from normal `.jsx?` and `.tsx?` rules.

```js
// .storybook/webpack.config.js

// ...
module.exports = ({ config, mode }) => {
  config.module.rules.push({
    test: /\.(ts|tsx)$/,
    use: [
      {
        loader: 'ts-loader',
        options: {
          transpileOnly: true,
          experimentalWatchApi: true,
          getCustomTransformers: () => ({
            before: [StyledTransformer],
          }),
        },
      },
    ],
  },
  // storysource loader must not be applied to non-story files.
  // the loader transform/inject/modify source code as assuming 
  // it as a story file.
  {
    test: /\.stories\.tsx?$/,
    // The loader should run at first
    enforce: 'pre',
    use: [
      {
        loader: require.resolve(
          '@storybook/addon-storysource/loader',
        ),
        options: {
          parser: 'typescript',
        }
      }
    ]
  });
  
  // ...
}
```
