### ISSUE TITLE
5.3.0-beta.2: Actions emitted multiple times after editing Knobs fields

### ISSUE THREAD

**Issue by costalvaro** [storybookjs/storybook#8886]
Hi, thanks for offering us this amazing tool that Storybook is !
Just tried your beta version and had a bug with it.. hope this report helps. 👍 

**Describe the bug**
Whenever I modify a knobs field then try an action, there is an additionnal action emitted.
If I modify 20 times my knobs fields, I'll have 20 events triggered for a single action.

**To Reproduce**
1. Create a very simple story of a component with knobs + actions
2. Trigger an action : An event is emitted one time (good)
3. Modify multiple knobs values
4. Trigger the same action : An event is emitted multiple times (bad)

**Expected behavior**
Triggering an event should emit only once in the Actions tab.

**System:**
"@angular/core": "~8.2.12",
"@babel/core": "^7.6.4",
"babel-loader": "^8.0.6",
"@storybook/addon-a11y": "^5.3.0-beta.2",
"@storybook/addon-actions": "^5.3.0-beta.2",
"@storybook/addon-knobs": "^5.3.0-beta.2",
"@storybook/addon-links": "^5.3.0-beta.2",
"@storybook/addon-storysource": "^5.3.0-beta.2",
"@storybook/addons": "^5.3.0-beta.2",
"@storybook/angular": "^5.3.0-beta.2",

**Additional context**
On the terminal :  
At Step 2, only one message "storybook/actions/action-event" is displayed.
At Step 4, several messages "storybook/actions/action-event" are displayed with unique ids.

**Comment by shilman** [comment]
@Hypnosphi @ndelangen Is this something you guys can look at?

**Comment by aaryn101** [comment]
This is a super annoying issue - can it be looked at?

**Comment by costalvaro** [comment]
Hi, fyi I just updated and can confirm that the issue is still present with version 5.3.0-beta.22. 😉

**Comment by norbert-doofus** [comment]
Hi there!
I've just faced the same annoying nuisance. In my project I use the latest stable version of package, which is 5.3.18 at the moment, and the issue is still there.
