### ISSUE TITLE
Error: Invariant failed: You should not use <Link> outside a <Router>

### ISSUE THREAD

**Issue by swoppy** [storybookjs/storybook#8892]
**Describe the bug**
It throws an error when trying to view a components with react-router(s). However, components works fine with the normal react-scripts start

**To Reproduce**
view any components with react-router-dom

**Expected behavior**
no errors

**Code snippets**
If applicable, add code samples to help explain your problem.

**Screenshots**
![image](https://user-images.githubusercontent.com/24859633/69216293-d38e0c80-0ba6-11ea-8434-201041f30af7.png)

**System:**
System:
    OS: macOS 10.15.1
    CPU: (4) x64 Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz
  Binaries:
    Node: 10.16.2 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 78.0.3904.97
    Safari: 13.0.3
  npmPackages:
    @storybook/addon-actions: ^5.2.4 => 5.2.4 
    @storybook/addon-links: ^5.2.4 => 5.2.4 
    @storybook/addons: ^5.2.4 => 5.2.4 
    @storybook/react: ^5.2.4 => 5.2.4

**Comment by dgpro** [comment]
Same here when using 
```
import { Link } from 'react-router-dom'
```

**Comment by swoppy** [comment]
for the meantime, this lib https://github.com/gvaldambrini/storybook-router mitigated the error

**Comment by Hemant27031999** [comment]
Yes, the error still exist. If I try to use the Link component outside a Router, it throws the following error.
![Screenshot from 2020-01-13 15-33-37](https://user-images.githubusercontent.com/43013193/72247136-443b2d80-361a-11ea-8b1d-0554e28b182d.png)

**Comment by mavenik** [comment]
I'm getting this too. Just bumping the comment thread to not let this go stale.
Meanwhile, https://github.com/gvaldambrini/storybook-router has worked for me.

**Comment by afholderman** [comment]
This is not an issue with storybook, the error comes from `react-router` as is evidenced by the screenshots being posted.  If you look at the source of https://github.com/gvaldambrini/storybook-router the fix is clear. Wrap the output of your story in a `<MemoryRouter/>` from `react-router`. To make this reusable write your own simple decorator:
```
export const withMemoryRouter = (story: any) => (
  <MemoryRouter>{story()}</MemoryRouter>
);
```
Storybook can't be expected to pull in and wrap third party library's wrappers. For example similar errors would occur with components that use `connect` or `useSelector` outside of a mocked `react-redux` `<Provider/>` or `@material-ui` theme functions outside of a `<ThemeProvider/>`.

**Comment by juanhelbert** [comment]
Same error for me. @afholderman solution worked perfectly.

**Comment by nickzcv** [comment]
Thanks @afholderman 

Also we can simply use `addDecorator` method:

```
...
import { MemoryRouter } from 'react-router-dom';
import { Provider } from 'react-redux';
import { store } from '../../../../redux/store/connect';

storiesOf('common', module)
  .addDecorator(getStory => <Provider store={store}>{getStory()}</Provider>)
  .addDecorator(getStory => <MemoryRouter>{getStory()}</MemoryRouter>)
  .add('Component Name', () => <Component/>);
```

**Comment by shilman** [comment]
@nickzcv and for those of you using [CSF](https://medium.com/storybookjs/component-story-format-66f4c32366df):

```js
import { MemoryRouter } from 'react-router-dom';
import { Provider } from 'react-redux';
import { store } from '../../../../redux/store/connect';

export default {
  title: 'common',
  decorators: [
    getStory => <Provider store={store}>{getStory()}</Provider>,
    getStory => <MemoryRouter>{getStory()}</MemoryRouter>,
  ]
}

export const ComponentName = () => <Component />;
```

**Comment by josh231101** [comment]
I'm using styled components and get this error by creating an styled link, although if I create the styled componentn inside the index.js I get no error, why?
