### ISSUE TITLE
[Addon-docs] ForwardRef has props === undefined during exractProps

### ISSUE THREAD

**Issue by shmidt-i** [storybookjs/storybook#8894]
**Describe the bug**
ForwardRef components receive `undefined` as `props` during `exractProps` step.
https://github.com/storybookjs/storybook/blob/next/addons/docs/src/frameworks/react/extractProps.ts#L28-L31

Check out code snippets [1], [2]

Both are actually incorrect, since in React runtime you always have the `props` object presented, it just doesn't have any keys on it if no props were passed.
 
**To Reproduce**
If you change  `examples/official-storybook/components/ForwardedRefButton.js` to have a destructuring on props, the props extraction process will fail, e.g. [3]

And then check the story examples/official-storybook/stories/addon-docs/props.stories.mdx.
There would be no props available for the component.

**Expected behavior**
Props table is shown 

**Code snippets**
[1]:
```
processedComponent = component.render().type;
```

[2]:
```
processedComponent = component.type().type;
```

[3]: 
```
const ForwardedRefButton = forwardRef(({ disabled, ...restProps }, ref) => (
  <BaseButton disabled={disabled} {...restProps} forwardedRef={ref} />
));

```

**System:**
Replicated in latest storybook repo's examples, but originally found in @storybook/addon-docs@5.2.5.

**Additional context**
Here is a downgrade commit in our repo that fixed the behaviour: https://github.com/nordnet/ui/commit/6cf7ee5a56d1b065aba1243a30baa267805e8b13.

The component that failed was https://github.com/nordnet/ui/tree/master/src/Atoms/Box

**Comment by shilman** [comment]
Repro: https://github.com/storybookjs/storybook/commit/822f3dfe70ae10a0dac035408addbd5fee991a29

**Comment by shilman** [comment]
@andezzat here's the `forwardRef` case as we discussed relative to #12638

**Comment by shilman** [comment]
Jeepers creepers!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.0-alpha.21 containing PR #12686 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.
