### ISSUE TITLE
Addon-docs: "Integration" stories for Doc blocks

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#8903]
## Why

There are already "unit" stories for doc blocks in `lib/components`. We need analogous stories for `addon-docs/blocks`:

- Provide user-facing documentation for the blocks they actually interact with
- Catch regressions in more complex blocks like `Props`

## What

- [ ] Description
- [ ] Props
- [ ] Story

**Comment by zhuweileo** [comment]
Is there a documentation for Addon-docs block components (like Meta, Preview, Props……)?

**Comment by shilman** [comment]
Coming in 5.3 😉

**Comment by shilman** [comment]
This has been fixed in 7.0 in https://github.com/storybookjs/storybook/tree/next/code/ui
