### ISSUE TITLE
Addon-docs: title shows whole path @5.3.0-beta.2

### ISSUE THREAD

**Issue by adrian-potepa** [storybookjs/storybook#8907]
**Describe the bug**
In docs tab title shows whole path with category.

**To Reproduce**
```
import React from 'react';

import { TextInput } from '.';

export default {
  title: 'Components|TextInput',
  component: Text,
};


export const basic = () => <TextInput placeholder="Input text" width={312} />;

```

**Expected behavior**

We should get only **TextInput**.

**Screenshots*
![Zrzut ekranu 2019-11-21 o 09 06 35](https://user-images.githubusercontent.com/6291752/69319034-ae4cdd00-0c3e-11ea-8250-f1218891be78.png)

**Comment by shilman** [comment]
Ouch. Here's a workaround for now: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#simplified-hierarchy-separators

**Comment by shilman** [comment]
w00t!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-rc.1 containing PR #9204 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
