### ISSUE TITLE
Addon-docs: Add anchor to Meta

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#8914]
In MDX, you might have some content at the top of the page, and your first story further down on the page. Currently this will cause the page to scroll when you click on the component.

Proposal:

```
<Meta title='some/component' anchor />
```

Will automatically generate an `<Anchor storyId='some-component--first-story' />` inside the `Meta` when `anchor` is set to true.

**Comment by tenderloin420** [comment]
This feature would be great! I have the same problem with my mdx format stories.

**Comment by shilman** [comment]
Hurrah!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-rc.10 containing PR #9331 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
