### ISSUE TITLE
Addon-docs: Prop types function signature should be expandable

### ISSUE THREAD

**Issue by patricklafrance** [storybookjs/storybook#8917]
**Is your feature request related to a problem? Please describe.**

A large function signature can significantly increase the width of the type column of the props table.

![image](https://user-images.githubusercontent.com/794579/69364851-20361e00-0c61-11ea-8168-0f8c06f8adc5.png)

**Describe the solution you'd like**
Use the same summary / expandable behavior that we use for the objects.

**Describe alternatives you've considered**

**Are you able to assist bring the feature to reality?**
Yes

**Additional context**

**Comment by shilman** [comment]
Ta-da!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-beta.10 containing PR #8950 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
