### ISSUE TITLE
Addon-docs: Props table detail tooltip is too small for JSX component

### ISSUE THREAD

**Issue by patricklafrance** [storybookjs/storybook#8919]
**Describe the bug**
The props table detail tooltip cut the end of the JSX component.

![image](https://user-images.githubusercontent.com/794579/69370667-6775dc00-0c6c-11ea-8acd-de1393a7329b.png)

**Comment by shilman** [comment]
Egads!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-beta.6 containing PR #8923 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
