### ISSUE TITLE
addon-docs angular: prop tables don't show for angular directives

### ISSUE THREAD

**Issue by afebbraro** [storybookjs/storybook#8920]
### Bug or support request summary
For components, you pass the component to the "component" property for each story to get the Prop Table to show up. This doesn't work for directives.  The prop tables for angular directives do not show up.

### Steps to reproduce
```
export default {
  title: 'Components/Button',
  component: ButtonDirective,
};

```
Check the proptable in the DocsPage, it doesn't show the props when you pass a directive to "component".

### Please specify which version of Storybook and optionally any affected addons that you're running

    "@compodoc/compodoc": "^1.1.11",
    "@storybook/addon-a11y": "^5.3.0-beta.3",
    "@storybook/addon-docs": "^5.3.0-beta.3",
    "@storybook/addons": "^5.3.0-beta.3",
    "@storybook/angular": "^5.3.0-beta.3",
    "@storybook/preset-scss": "^1.0.2",
    "@storybook/theming": "^5.3.0-beta.3",

If you are creating a issue to track work to be completed, start here:
### Work summary
Need to add the ability to pull prop info from directives into SB. Furthermore, Compodoc does provide output for directives and this can fulfill the data needed for the prop tables but compodoc does not provide the "rawdescription" which SB uses to populate the Description slot. This looks to be a missed field in the directives JSON and I filled an issue on Compodoc here: https://github.com/compodoc/compodoc/issues/875

UPDATE: Compodoc accepted the issue and completed the work to add in the "rawdescription"! Woohoo!

**Comment by afebbraro** [comment]
See PR #8922, let me know any feedback!

**Comment by shilman** [comment]
Yay!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-beta.10 containing PR #8922 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
