### ISSUE TITLE
Addon-docs: A prop row shouldn't have top margin when there is no description

### ISSUE THREAD

**Issue by patricklafrance** [storybookjs/storybook#8924]
**Describe the bug**
A prop row shouldn't have top margin when there is no description

![image](https://user-images.githubusercontent.com/794579/69384786-42449600-0c8b-11ea-8cce-2d495b31194f.png)

**To Reproduce**
1. Start cra-ts-kitchen-sink
2. Go to the docgen/types docs story
3. Find a prop that have JSDoc and no description

**Expected behavior**
Dont have a top margin when there is no description

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System:**
Please paste the results of `npx -p @storybook/cli@next sb info` here.

**Additional context**

**Comment by shilman** [comment]
Jeepers creepers!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-beta.10 containing PR #8950 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
