### ISSUE TITLE
TypeSet block needs bigger lineHeight

### ISSUE THREAD

**Issue by kfayelun** [storybookjs/storybook#8926]
**Describe the bug**
The lineHeight of the TypeSet doc block Sample div is set to 1. This cuts off characters that goes below the main body of characters.

**To Reproduce**
1. Use the TypeSet doc block in a story.
2. Add a sampleText that has characters like p, y, g, j etc
3. See that the part that dips down gets cut off.
4. Set the div's lineHeight to 1.2 and see that this fixes the issue

**Expected behavior**
That the characters aren't cut off. 

**Screenshots**
Added but text in Norwegian 
<img width="1565" alt="Skjermbilde 2019-11-22 kl  11 43 04" src="https://user-images.githubusercontent.com/4848101/69419728-5933c880-0d1d-11ea-8552-292df584f1b8.png">

**Code snippets**
https://github.com/storybookjs/storybook/blob/next/lib/components/src/blocks/Typeset.tsx#L18
That line needs to be 1.2 or higher. Alternatively lineHeight could be a prop.

**System:**
Environment Info:

  System:
    OS: macOS 10.15
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 78.0.3904.108
    Firefox: 70.0.1
    Safari: 13.0.2
  npmPackages:
    @storybook/addon-a11y: ^5.3.0-alpha.45 => 5.3.0-alpha.45 
    @storybook/addon-actions: ^5.3.0-alpha.45 => 5.3.0-alpha.45 
    @storybook/addon-docs: ^5.3.0-alpha.45 => 5.3.0-alpha.45 
    @storybook/addon-links: ^5.3.0-alpha.45 => 5.3.0-alpha.45 
    @storybook/addons: ^5.3.0-alpha.45 => 5.3.0-alpha.45 
    @storybook/preset-create-react-app: ^1.2.0 => 1.2.0 
    @storybook/react: ^5.3.0-alpha.45 => 5.3.0-alpha.45 

**Additional context**
There's also a font issue for this doc block, adding so they might be fixed together. 
https://github.com/storybookjs/storybook/issues/8161

**Comment by domyen** [comment]
Thanks for reporting this @kfayelun! Would be open to a PR that implements your suggestion 🙏

**Comment by philippe-lavoie** [comment]
I created a pull request to fix this #9567

**Comment by shilman** [comment]
Jeepers creepers!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-alpha.0 containing PR #9567 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
