### ISSUE TITLE
Addon-docs: Preview component is not compatible with content that is hidden

### ISSUE THREAD

**Issue by fraincs** [storybookjs/storybook#8928]
**Describe the bug**
When a component shows content that is absolutely positioned, the content is hidden behind a scrollbar.

**To Reproduce**
1. Place a component that has hidden absolute positioned element by default
2. Make them appear (onClick, onHover)

**Expected behavior**
The content would show over the preview.

**Screenshots**
before clicking the date picker
![image](https://user-images.githubusercontent.com/361632/69436615-b4f75500-0d0f-11ea-8453-94514164f8cf.png)

clicked
![image](https://user-images.githubusercontent.com/361632/69436644-c4769e00-0d0f-11ea-8101-4ee9ec7d7301.png)

What is expected

![image](https://user-images.githubusercontent.com/361632/69437014-7ca44680-0d10-11ea-8a5c-a19557de7606.png)

**System:**

Environment Info:

  System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  Binaries:
    Node: 12.7.0 - ~/.nvm/versions/node/v12.7.0/bin/node
    Yarn: 1.19.1 - ~/Repos/sg-orbit/node_modules/.bin/yarn
    npm: 6.10.0 - ~/.nvm/versions/node/v12.7.0/bin/npm
  Browsers:
    Chrome: 78.0.3904.108
    Firefox: 69.0.1
    Safari: 13.0.3
  npmPackages:
    @storybook/addon-actions: 5.3.0-beta.3 => 5.3.0-beta.3 
    @storybook/addon-console: 1.2.1 => 1.2.1 
    @storybook/addon-docs: 5.3.0-beta.3 => 5.3.0-beta.3 
    @storybook/addon-knobs: 5.3.0-beta.3 => 5.3.0-beta.3 
    @storybook/react: 5.3.0-beta.3 => 5.3.0-beta.3

**Comment by matiasmenker** [comment]
The same issue here!

**Comment by fraincs** [comment]
@matiasmenker it's unfortunately not that easy, when there is a second preview just under.

![image](https://user-images.githubusercontent.com/361632/69564505-21c55600-0f81-11ea-87e2-513b4c71fa7f.png)

**Comment by kikorb** [comment]
Hi bot! I am still interested in a solution.

**Comment by kikorb** [comment]
> @matiasmenker it's unfortunately not that easy, when there is a second preview just under.
> 
> ![image](https://user-images.githubusercontent.com/361632/69564505-21c55600-0f81-11ea-87e2-513b4c71fa7f.png)

I understand this is a concern but shouldn't the popable content have a higher z-index than the entire next component? Wouldn't you run on the same issue in your application?

I would prefer for the preview overflown content to be visible than hidden, at least we would be able to fix the issue you are pointing out on a per-page basis.

**Comment by kumarharsh** [comment]
+1 I'd like to be able to tell the `<Preview>` component that there is some content inside which might be absolutely positioned.

The issue I'm facing is the same as highlighted above, but for React-Select and Popper tooltips. I could override it in a crude way by writing this CSS:

```css
.sbdocs-preview, /* for the preview wrapper */
.sbdocs-preview > div > div { /* for another wrapper within the preview div */
  overflow: visible;
}
```

Maybe there should be a prop which can be passed to the `<Preview>` component to control this on a case-by-case basis?

**Comment by shilman** [comment]
@kumarharsh if you have ideas about how to do that, I'd be open to PRs

**Comment by kumarharsh** [comment]
Okay, will look into it next week :)

**Comment by mvirbicianskas** [comment]
hey, any chance @kumarharsh you made progress on that? I'm facing same issues, any kind of absolutely positioned popover is broken inside the Prieview block :(

**Comment by codequistador** [comment]
I hacked my way around this. Thought I'd share how. The third child deep off of `sbdocs-preview` has a `transform` property on it. Disabling that and setting some choice `overflow: visible`s did the trick

```
// preview-head.html
#docs-root .sbdocs-preview {
  overflow: visible;
}

#docs-root .sbdocs-preview > div:first-child > div:first-child {
  overflow: visible;
}

#docs-root .sbdocs-preview > div:first-child > div:first-child > div:first-child {
  transform: none;
}
```

**Comment by shilman** [comment]
closing as dupe to #8011
