### ISSUE TITLE
Application of general good practices, for Yarn v2 compatibility.

### ISSUE THREAD

**Issue by crubier** [storybookjs/storybook#8944]
**Describe the bug**

Storybook does not work with Yarn V2 at the moment, due to some lax-specification of dependencies and other not ideal practices. 

This is discussed in detail in https://github.com/yarnpkg/berry/issues/592 , and more generally in https://github.com/yarnpkg/berry/issues/484 . 

I think the effort on yarn's side has been done, the ball is mostly in storybooks side right now.

The full problem and workaround (which points to a solution clearly) is fuond here:

https://github.com/crubier/yarnv2-storybook

**Expected behavior**

Storybook works out of the box directly with yarn v2

**Comment by crubier** [comment]
I also opened an MR there https://github.com/ndelangen/corejs-upgrade-webpack-plugin/pull/4

**Comment by crubier** [comment]
MR fr storybook here:

https://github.com/storybookjs/storybook/pull/8945

**Comment by shilman** [comment]
Zoinks!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-beta.9 containing PR #8945 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
