### ISSUE TITLE
Addon-docs: Duplicate ID's in DOM if you view a component in Canvas first, then in Docs.

### ISSUE THREAD

**Issue by davidn0rman** [storybookjs/storybook#8946]
**Describe the bug**
We've run into an issue where a story for a set of radio buttons on the `Docs` page do not work if you visit the same story in the Canvas page first. After a bit of digging, we've noticed the component is still in the DOM when flicking over to the Docs page. I noticed that the `<div id="root">` element has `hidden="true"` set when flicking to Docs, which might be the cause of the problem.

This appears to be the same for any component, but because we have custom styles for our radio buttons and duplicate ID's exist in the DOM, we've noticed it heavily with them.

Example: We have in our stories:

```
- Radio buttons
  - Basic
  - Invalid
  - Disabled
```

If I select the `Basic` story, I see three radio buttons as expected under the Canvas tab. If I then flick to the `Docs` tab, the radio buttons in the Basic story section of the doc does not select when we click them. If you then refresh the page (Or load straight into the Basic story on the Docs page) the issue goes away, because there's only one instance of the component in existence.

**To Reproduce**
1. Go to a story and look at it in the Canvas
2. Click on Docs tab
3. Find your component in the relevant story
4. See component isn't working,

**Expected behavior**
The original component to not exist in the DOM.

**Screenshots**
Basic > Canvas...
![image](https://user-images.githubusercontent.com/20046480/69557769-0d905180-0f9f-11ea-8562-84580ea5b43e.png)

Basic > Docs, having already been on the Canvas page...
![image](https://user-images.githubusercontent.com/20046480/69558032-77106000-0f9f-11ea-84e5-a90f0df51ebf.png)

**System:**

Environment Info:

```
  System:
    OS: macOS 10.15.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Binaries:
    Node: 11.11.0 - /usr/local/bin/node
    npm: 6.13.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 78.0.3904.108
    Firefox: 70.0
    Safari: 13.0.3
```

**Comment by shilman** [comment]
Which version of Storybook? This might be a dupe to https://github.com/storybookjs/storybook/issues/8622

**Comment by davidn0rman** [comment]
> Which version of Storybook? This might be a dupe to #8622

Whoops! My bad, we're rocking v5.2.5 😄 

Fundamentally looks similar to the GIF in #8622 however we never have more than one component on screen as we flick around. (Looks like it's hiding and showing the root div in the DOM as we navigate off from Canvas)
