### ISSUE TITLE
Addon-docs: Expand the props table max-width to 1000px

### ISSUE THREAD

**Issue by patricklafrance** [storybookjs/storybook#8947]
**Is your feature request related to a problem? Please describe.**
Initially the props table have been design for a max width of 800px. 

Since then, the use cases have expanded significantly and I would like to expand it to 1000px. With a wider props table we could increase the props summary significantly and have less expandables for simple objects, arrays and elements.

@domyen and I agree on this.

I would love to have everyone opinion @shilman @atanasster .

**Comment by shilman** [comment]
Yeah I'm OK with this if @domyen is 👍

**Comment by patricklafrance** [comment]
No by default.

Currently the props table ship with a max-width of 800px. The default max-width will be increase to 1000px.

If a user want to increase the width further, yes an escape-hatch is available.

**Comment by domyen** [comment]
Chatted with Patrick – I think this is a good affordance for the new ways folks are starting to use SB Docs. FYI the intended scope of this is to change the `max-width` of the DocsPage wrapper from `800px` to `1000px` (not just the PropsTable).

**Comment by shilman** [comment]
Thanks, that makes more sense!! 👍

**Comment by shilman** [comment]
Ermahgerd!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-beta.10 containing PR #8970 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by krizpoon** [comment]
Is there any way to configure the max width? I'm currently overriding the style with something like this:

```
export const StorybookScreenWidener = () => {
  return (
    <style
      dangerouslySetInnerHTML={{
        __html: `
          .sbdocs.sbdocs-content {
            max-width: none;
          }`,
      }}
    ></style>
  );
};
```
