### ISSUE TITLE
Addon-docs: Multiple Tab

### ISSUE THREAD

**Issue by tounsoo** [storybookjs/storybook#8951]
**Is your feature request related to a problem? Please describe.**
For design system documentation, we have a lot of content per component that is hard to be viewed in a single page format. In a high level, our doc is made up of 3 parts: Component Documentation, Component Guidelines, Pattern Guidelines(optional).

**Describe the solution you'd like**
With the newest addon/doc that supports MDX, it would be perfect if I can make multiple tabs of mdx with custom title - each tab with its mdx.

**Describe alternatives you've considered**
Without adding a new feature, alternate solution can be to create 3 stories for each component with each MDX attached.

**Are you able to assist bring the feature to reality?**
yes and no, I'm a designer who can use but not create code in efficient manner. But I would definitely want to contribute with whatever I can.

**Comment by patricklafrance** [comment]
A good example of that: https://microsoft.github.io/fluent-ui-react/components/accordion/definition

@domyen

**Comment by just-andy** [comment]
We have a similar request for this feature and trying to look through the addon guides and existing docs block to see how this could be put into practice.

**Comment by domyen** [comment]
This seems possible via MDX (5.3) if you code up your own tab component. iirc I saw an implementation for this somewhere.

**Comment by adeelibr** [comment]
> This seems possible via MDX (5.3) if you code up your own tab component. iirc I saw an implementation for this somewhere.

Can you kindly share the implementation details if possible

**Comment by LucasLeandro1204** [comment]
I'm waiting for this one too!

**Comment by AndreasLoukakis** [comment]
I'm using storybook/angular and wanted to implement something similar so I was looking around for other examples. I have a setup that works in a similar way and might be helpful to share, although I'm pretty much sure it's not the best way to do it.

In my docs tab, I need to have let's say Overview - API - Examples - Changelog tabs.
I created a separate .mdx for each tab (which is much easier to work on) and on the story mdx, I used @reach/tabs (some other react tab components didn't work well for me) to setup the content. So my main story looks something like this:

```
import MyTabMDX from './somefile.mdx'

<Tabs >
      <TabList>
        <Tab>My tab</Tab>
      </TabList>
      <TabPanels>
        <TabPanel>
          <MyTabMDX />
        </TabPanel>
      </TabPanels>
</Tabs>

<Meta title="Tabs" decorators={...} />
<Story name="SimpleTabs">...</Story>

```

Have in mind you obviously can't use mdx syntax if you write the content inline in-between the TabPanel tags, but external mdx works great.

**Comment by shilman** [comment]
Nice one @AndreasLoukakis !!!

**Comment by andywd7** [comment]
I know this is closed but I would like o know how to do this in Vue using Storybook 6? Both the tabs and importing nested mdx files as content.

**Comment by orgertot** [comment]
@AndreasLoukakis did u get it working with canvas+stories in the mdx file?

I get an error...

**Comment by AndreasLoukakis** [comment]
Yes, it was and still is working but many updates on many libraries happened since then. Is there something in specific that would help you figure it out? what's the error?

**Comment by orgertot** [comment]
I have a simple Story:

```
import { Story, Meta, ArgsTable, Preview, Canvas } from "@storybook/addon-docs";
import Rest from "./1-Rest.stories.mdx";

<Meta title="Components/Neues Template"

<Rest />
```
And the 1-Rest.stories.mdx with an angular story:

```
import { Story, Meta, ArgsTable, Preview, Canvas } from "@storybook/addon-docs";
import { moduleMetadata } from "@storybook/angular";
import { TabsComponent } from "../../../projects/ui-components-library/src/lib/modules/tabs/tabs/tabs.component.ts";

<Meta
    title="Components/Neues Template 2"
    decorators={[
        moduleMetadata({
            declarations: [TabsComponent],
        }),
    ]}
    parameters={{ test: "TEST" }}
/>

<Canvas>
    <Story
        id="components-neues-template-2--tabs"
        name="Tabs"
        args={{
            listOfTabs: ["tab1", "tab2", "..."],
            active: "tab1",
        }}
        parameters={{
            docs: { source: { code: `<libri-tabs></libri-tabs>` } },
            options: {
                showPanel: true,
            },
        }}
        height="75px"
    >
        {(args, { argTypes }) => ({
            component: TabsComponent,
            props: args,
        })}
    </Story>
</Canvas>
```

I get the following error: `Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.` The Element seems to be a storybook element definition? 

When I rename the 1-Rest.stories.mdx to 1-Rest.mdx I get a different error. I think its because storybook adds a wrapper to mdx files. See here https://github.com/storybookjs/storybook/issues/9598#issuecomment-578832842

@AndreasLoukakis : Do you use Stories in the mdx file? Do you use another react component to render the mdx file?

**Comment by AndreasLoukakis** [comment]
My bad, seems we have moved to a different format for the stories template since then so I can't confirm. But we did use an external React lib @reach/tabs for the tabs at the time, some others had some issues but can't remember exactly.

**Comment by cliedelt** [comment]
I gave up and wrote an addon... https://github.com/cliedelt/storybook-addon-docs-tabs

**Comment by sir-captainmorgan21** [comment]
@cliedelt I am using your addon. Works well. Thanks!

**Comment by sir-captainmorgan21** [comment]
@shilman could possibly use your help with @cliedelt 's tabs add-on. He is being forced to use iframes to display the tab content which is causing some overflow issues. We were wondering if you could provide any guidance with using an imported mdx stories file as a component in another mdx file. @cliedelt can provide more info too if needed.

**Comment by elpddev** [comment]
Could this be opened? Its a desired feature for us.

**Comment by vinodkola1337** [comment]
I would like to have this feature.

**Comment by Michael2109** [comment]
A lot of component libraries tend to split their pages into examples, properties, and styling. 

How do we do this in Storybook 7? 

I can't see how this is done using `<x>.stories.mdx` files as it doesn't look like a component can be directly loaded into it.
