### ISSUE TITLE
Addon-links: linkTo typings error

### ISSUE THREAD

**Issue by zhzz** [storybookjs/storybook#8958]
Hello!

**Describe the bug**
According to `linkTo`'s typings it returns a function that expects only strings as arguments. Which is not the case for an arbitrary event handler.

**To Reproduce**
Implement the next example with Typescript:
```
<button onClick={linkTo('Button', 'Second')}>Go to "Second"</button>
```

**Expected behavior**
No type errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/4607770/69621507-0df12100-1061-11ea-9db7-fb0c41d75c06.png)

**Code snippets**
[https://codesandbox.io/s/cocky-black-8jdd9](https://codesandbox.io/s/cocky-black-8jdd9)

**System:**
    OS: macOS 10.15.1
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  
Binaries:
    Node: 12.13.1 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.12.1 - /usr/local/bin/npm
  
Browsers:
    Chrome: 78.0.3904.108
    Firefox: 68.0.1
    Safari: 13.0.3
  
npmGlobalPackages:
    @storybook/cli: 5.2.6

**Additional context**
I'd like to send a PR if you guys confirm.

**Comment by shilman** [comment]
Jiminy cricket!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-beta.11 containing PR #8975 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
