### ISSUE TITLE
addon-docs: Angular prop tables drill-down type and value support

### ISSUE THREAD

**Issue by afebbraro** [storybookjs/storybook#8959]
### Support request summary
The Props Tables in the React Storybook docs support drill-down types and values and it would be awesome to have that in the Angular storybook too!
This is react:
<img width="947" alt="Screen Shot 2019-11-26 at 8 24 29 AM" src="https://user-images.githubusercontent.com/2117593/69637664-1dec0f00-1027-11ea-9a83-f73ac0831482.png">
 
This is Angular: NarrowNavLinks has a type definition but it doesn't show the shape.
<img width="1060" alt="Screen Shot 2019-11-26 at 8 20 12 AM" src="https://user-images.githubusercontent.com/2117593/69637680-26444a00-1027-11ea-90b6-851dc6f5ceba.png">

```
export interface NarrowNavLinks {
  /**
   * The text for the link.
   */
  text: string;
  /**
   * The `href` value for the link.
   */
  href: string;
  /**
   * Optional sub-navigation for the link.
   */
  subNav?: Array <{
   /**
    * The text for the sub-navigation link.
    */
    text: string
    /**
     * The `href` for the sub-navigation link.
     */
    href: string
    /**
     * The icon name supplied will
     * be used to render
     * the specified icon to the
     * left of the sub-navigation link text.
     */
    leadingIcon?: string
  }>;
  /**
   * If `true`, denotes that the link
   * represents the current page.
   */
  active?: boolean;
  /**
   * The icon name supplied will
   * be used to render
   * the specified icon to the
   * left of the link text.
   */
  leadingIcon?: string;
}
```
### Steps to reproduce
Go into angular storybook and open up a component that has array or object types for it's Inputs and see that it doesn't show their shape.
### Please specify which version of Storybook and optionally any affected addons that you're running
```
 "@compodoc/compodoc": "^1.1.11",
    "@storybook/addon-a11y": "^5.3.0-beta.6",
    "@storybook/addon-docs": "^5.3.0-beta.6",
    "@storybook/addons": "^5.3.0-beta.6",
    "@storybook/angular": "^5.3.0-beta.6",
    "@storybook/preset-scss": "^1.0.2",
    "@storybook/theming": "^5.3.0-beta.6",
```

**Comment by Kosai106** [comment]
+1, this also applies to the React preset using TypeScript.

**Comment by Kosai106** [comment]
This is not stale @shilman. 😅

**Comment by shilman** [comment]
cc @patricklafrance on typescript types

**Comment by shilman** [comment]
@Kosai106 do any of the examples in `cra-ts-kitchen-sink` help you out? if not, can you add a repro there and i can take a look?

**Comment by Kosai106** [comment]
@shilman I'll try and see if I can make time to create a small reproduction for you today.

**Comment by Kosai106** [comment]
Alright @shilman I took a look at `cra-ts-kitchen-sink`.

In the Prop Types example, there's `arrayOfComplexShape` which has the desired look, but it's made using PropTypes, not TypeScript types.

<img width="1029" alt="Screenshot 2020-01-23 at 16 43 02" src="https://user-images.githubusercontent.com/6379824/72999331-82e19c80-3dff-11ea-8e4c-9dd2c5561c46.png">

In the TypeScript examples, there's `arrayOfComplexObject` but it doesn't have the drill-down values either. None of the TypeScript examples has this feature by the looks of it - Only for default values.

<img width="1007" alt="Screenshot 2020-01-23 at 16 43 26" src="https://user-images.githubusercontent.com/6379824/72999332-82e19c80-3dff-11ea-8179-f66b0715d488.png">

**Comment by patricklafrance** [comment]
Yeah this kind of support hasn't been implemented yet for TypeScript. If I remember well, the tree structure returned for TS is a lot less refined than the one returned for PropTypes which make it hard to implement.

I might be wrong though, it's been a few month since I looked at it.

We are currently working through switching to react-docgen for TS support. We might be able to work this out while we are doing that.

**Comment by Kosai106** [comment]
Any update on this @patricklafrance?

**Comment by patricklafrance** [comment]
Redirect to @shilman

**Comment by shilman** [comment]
@Kosai106 I'm midway through a major refactor of the props table code for 6.0. When that is done, this should either come "for free" or be very easy to add. This issue is not on my radar right now, but I'll dig it up when the time comes.

**Comment by davoam** [comment]
Hi @shilman !

Thanks for the Storybook! 

Is there any progress on this feature? I checked version 6 official angular example, it looks like, the feature is not implemented yet.

**Comment by shilman** [comment]
We have an API to do it manually now but have not automated that for anything but React so far.

https://storybook.js.org/docs/react/api/argtypes

**Comment by davoam** [comment]
> We have an API to do it manually now but have not automated that for anything but React so far.
> 
> https://storybook.js.org/docs/react/api/argtypes

Got it, thanks for the answer!
