### ISSUE TITLE
Storybook not recognizing .d.ts files for typings

### ISSUE THREAD

**Issue by AssisrMatheus** [storybookjs/storybook#8961]
I'm using storybook with next.js and typescript and it's not recognizing the .d.ts files I create.

I'm having the following error when creating a story for an element that imports `baguettebox.js`:
```ERROR in [at-loader] ./src/components/ImageGallery/index.tsx:2:25 
    TS7016: Could not find a declaration file for module 'baguettebox.js'. 'D:/dev/sge/sge-portal-frontend/node_modules/baguettebox.js/dist/baguetteBox.min.js' implicitly has an 'any' type.
  Try `npm install @types/baguettebox.js` if it exists or add a new declaration (.d.ts) file containing `declare module 'baguettebox.js';`
```
`@types/baguettebox.js` **does not exist**. So I created a `baguettebox.d.ts` with `declare module 'baguettebox.js';` inside it on `./src/typings/`. **But the error still shows up.**

I know I can use `"noImplicitAny": false` but that doesn't fix for other typings(like next.js's `next-env.d.ts`), it should load types correctly. I tried moving and copying my `typings` folder to `./storybook` or to `./` instead of `./src` with no success.

My IDE and next.js's typescript compiler are correctly considering my .d.ts files.

I tried using `typeRoots` but with no success, maybe I used it wrong?

---

`./storybook/tsconfig.json`:
 ```json
{
  "compilerOptions": {
    "baseUrl": "./",
    "allowSyntheticDefaultImports": true,
    "module": "commonjs",
    "target": "es5",
    "lib": ["es5", "es6", "es7", "es2017", "dom"],
    "sourceMap": true,
    "allowJs": false,
    "jsx": "react",
    "moduleResolution": "node",
    "rootDir": "../",
    "outDir": ".storybook/dist",
    "noImplicitReturns": false,
    "noImplicitThis": false,
    "noImplicitAny": true,
    "strictNullChecks": false,
    "declaration": true,
    "skipLibCheck": true,
    "strict": true,
    "esModuleInterop": true,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "removeComments": false,
    "preserveConstEnums": true,
    "forceConsistentCasingInFileNames": true,
    "resolveJsonModule": true,
    "suppressImplicitAnyIndexErrors": true
  },
  "include": ["next-env.d.ts", "src/**/*"],
  "exclude": ["node_modules", "build", "scripts", ".next", ".awcache", "dist"]
}
```

`./storybook/webpack.config.js`:
```js
const path = require('path');
const SRC_PATH = path.join(__dirname, '../src');
const STORIES_PATH = path.join(__dirname, '../stories');

module.exports = ({ config }) => {
  config.module.rules.push({
    test: /\.(ts|tsx)$/,
    include: [SRC_PATH, STORIES_PATH],
    use: [
      {
        loader: require.resolve('awesome-typescript-loader'),
        options: {
          configFileName: './.storybook/tsconfig.json',
          useCache: true
        }
      },
      { loader: require.resolve('react-docgen-typescript-loader') }
    ]
  });
  config.resolve.extensions.push('.ts', '.tsx');
  return config;
};
```

`./src/typings/baguettebox.d.ts`
```ts
declare module 'baguettebox.js';
```

This is how my files are structured:
![image](https://user-images.githubusercontent.com/12276174/69642910-3c5f0400-1041-11ea-9969-41d1f497aecc.png)

I am running storybook with:
`start-storybook -s ./ -p 6006 -c .storybook`

**Comment by kroeder** [comment]
Hey! 

Can you try to add your `d.ts` file in your `./.storybook/tsconfig.json` like this: 

`"files": ["./next-env.d.ts"]`

Does this work?

**Comment by AssisrMatheus** [comment]
@kroeder This worked :). But I had to change to `../next-env.d.ts`

But I'm still having issues, I am also using styled-components and I'm using its theme functionality. So, for typescript types to work with the theme I have a `./src/typings/styled-components.d.ts` file with the following content:
```ts
// import original module declarations
import 'styled-components';
import { AppTheme } from 'src/styles/Theme'; // My theme type

declare module 'styled-components' {
  // eslint-disable-next-line @typescript-eslint/no-empty-interface
  export interface DefaultTheme extends AppTheme {}
}
```

Within `AppTheme` are my theme type with properties like `breakpoints` or `color` for example. And I get code completion throughout all my components with that.

But I have a utils file that receives styled-components' properties and returns a default css:
```ts
import { ThemeProps, DefaultTheme } from 'styled-components';

export const TabletAndUp = (props: ThemeProps<DefaultTheme>) => `@media (min-width: ${props.theme.breakpoints.small})`;
```

This file works just fine with styled-components/next/my IDE. But storybook's typescript says:
```
    TS2339: Property 'breakpoints' does not exist on type 'DefaultTheme'.
```

Because it's probably not loading my `./src/typings/styled-components.d.ts` file correctly. I am using styled-components addon for storybook, and I also tried adding `../src/typings/styled-components.d.ts` just like your suggestion asks me to, but with no success.

For now I have changed `DefaultTheme` to `any`, but I wish it just worked.

**Comment by anwalkers** [comment]
@AssisrMatheus Could this bug be related to #9606 ??

**Comment by jstoleg** [comment]
I have the same problem :( I don’t know how to solve it.

storybook@7.6.4

**Comment by Henrique018** [comment]
Had the same problem,  just had to tell webpack to also resolve extensions that starts with **.d.ts** 
`  webpackFinal: async (config) => {
    config.resolve?.extensions?.push('.d.ts');
    return config;
  },`
