### ISSUE TITLE
Not working properly storybook

### ISSUE THREAD

**Issue by begoliu** [storybookjs/storybook#8976]
report an error:
ERROR in ./.storybook/config.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: [BABEL] F:\storybook_react\my_react_storybook\.storybook\config.js: Using `babel-preset-react-app` requires that you specify `NODE_ENV` or `BABEL_ENV` environment variables. Valid values are "development", "test", and
 "production". Instead, received: "dev". (While processing: "F:\\storybook_react\\my_react_storybook\\node_modules\\babel-preset-react-app\\index.js")

installation package:  pass create-react-app@2.0.3 Set up the react-app
"devDependencies": {
    "@babel/core": "^7.7.4",
    "@storybook/react": "^5.2.6",
    "babel-loader": "^8.0.6"
  }

May I ask how to solve it??

**Comment by shilman** [comment]
Do you have a repro repo you can share?
