### ISSUE TITLE
Cannot use jasmine-marbles Observables

### ISSUE THREAD

**Issue by ivasansa** [storybookjs/storybook#8979]
### Bug summary

In our Angular project, we're using cold Observables from jasmine-marbles in a ts file. This causes storybook to throw a "jasmine is not defined" error.

### Steps to reproduce

When using a marbles Observable in a ts file like:

```
import { cold } from 'jasmine-marbles';

•••

getAlertNavState() {
	this.getAlertNavState$ = cold('-x|', { x: 'Nav Done' });
}
```

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/angular": "^5.2.6",
- "jasmine-marbles": "^0.6.0",

### Affected platforms 

"@angular/common": "~8.2.10",

### Screenshots / Screencast / Code Snippets (Optional)

![image](https://user-images.githubusercontent.com/14893591/69715195-27997380-1108-11ea-8a74-9a65a2830fc5.png)

Any idea why this is happening and how could we fix this issue?

**Comment by mspoerer** [comment]
+1

**Comment by sonic1981** [comment]
why don't you just use rxjs `of` instead of marbles? It seems to me that marbles are useful for unit tests but storybook isn't a unit test, it runs. I've got something similar working using:

```
import { Observable, of } from 'rxjs';
import { delay } from 'rxjs/operators'
....
return of(MockISMIncidentManagementService.metaData).pipe(
      delay(1000)
    );
```
