### ISSUE TITLE
Inject GlobalStyle into mdx docs

### ISSUE THREAD

**Issue by jole78** [storybookjs/storybook#8980]
Question:

Trying to construct design system documentation with storybook (v 5.2.6).
The issue is that our design system relies heavily on some global styles and fonts that we inject via styled-components GlobalStyle into our apps where we use the design system.

We are writing all of our docs in mdx since we already had that setup with another doc lib before.
The issue now is that I can't find any way I can globally inject the GlobalStyle components we have so that the docs tab (mdx) will make use of them. 

I have been able to get it injected into every story we define but not for the entire docs page.

Any help available??

**Comment by shilman** [comment]
@jole78 can you share how you did it for the stories and i can suggest how to do it for the MDX page?

**Comment by jole78** [comment]
Did with a decorator

**Comment by shilman** [comment]
Can you paste the code?

**Comment by jole78** [comment]
**Button.stories.mdx**
```
import { Button } from "./Button";
import { Story, Meta, Preview } from "@storybook/addon-docs/blocks";

<Meta title="Components/Button" />

# Button

some text here about buttons...



## The Contained Button 

Some text here about this type of button

<Button variant="contained">Contained Button</Button>

Some other text etc...

<Preview>
  <Story name="Contained Button">
    <FlexBox list="horizontal space-3">
      <Button variant="contained" color="primary">
        Primary
      </Button>
      <Button variant="contained" color="gray">
        Gray
      </Button>
      <Button variant="contained" disabled>
        Disabled
      </Button>
    </FlexBox>
  </Story>
</Preview>
```
I can get the GlobalStyle injected into the <Story /> here...I think?? via:
**config.js**
```
const WrapWithGlobalStyleThing = (storyFn) => {
  return (
    <>
        <GlobalFonts />
        {storyFn()}
    </>
  )
}

addDecorator(WrapWithGlobalStyleThing);

...etc...
configure(...add stories here....)
```
But since I'm writing long stories (or what do you call them) it's really a mix of "just components" and stories sometimes...etc

So I really need to "control" how the docs page looks in some sense...at least be able to inject things at the top.

As a reference my app/s that use this design system usually look like this:

```
function App() {
  return (
    <AuthenticationProvider>
      <React.Fragment>
        <GlobalFonts />
        <GlobalStyles />
        <Router>
          <Switch>
            <Route path="/login" component={LoginPage} />
            <AuthenticatedRoute role="admin" path="/" component={Application} />
          </Switch>
        </Router>
      </React.Fragment>
    </AuthenticationProvider>
  );
}
```

**Comment by shilman** [comment]
Take a look at this PR that was just merged and is available in the latest 5.3 beta:

https://github.com/storybookjs/storybook/pull/8968/files#diff-d9426aeec39287f8251196af2593b198

**Comment by jole78** [comment]
Ah great...had trouble getting latest beta working though (that's why we're on 5.2.6) but that probably is  something on our side. Can you get that thing added globally too?

**Comment by shilman** [comment]
@jole78 Globally: definitely, just add in your .storybook/config using `addParameters(...)`

**Comment by csantos-nydig** [comment]
Hi, I just landed into this issue because I need to add global styles to all my MDX. Is this the right approach to do it still?

**Comment by shilman** [comment]
Yes overriding `docs.container` is the probably the best way to do it still

**Comment by csantos-nydig** [comment]
Hi @shilman - I didn't get the notification for your message, sorry.

Let me elaborate my scenario:
`.storybook/preview.tsx`
```
import { globalStyles } from './global';
import { addDecorator } from '@storybook/react';

addDecorator((story) => {
  globalStyles();
  return <>{story()}</>;
});
```

`globalStyles` basically adds some reset styles and most importantly, define some font-faces that all my components reference.

And I have a lot of `*.stories.mdx` that renders components as live-documentation, for example:
```
import { Meta } from '@storybook/addon-docs';
import { Button } from '.';

<Meta title="Button" />

# Button
Hi this is the button component.
## Default style
<Button>Simple button</Button>
```

But none of my global styles are being applied to my "Simple button". How/where should I apply the `docs.container` change you mention?

Thanks in advance!
