### ISSUE TITLE
Unable to migrate to CSF

### ISSUE THREAD

**Issue by phaistonian** [storybookjs/storybook#8981]
Ideas ?:)

![image](https://user-images.githubusercontent.com/796530/69726100-71925180-1128-11ea-83b3-5c770c8be44b.png)

**Comment by shilman** [comment]
Try `sb migrate storiesof-to-csf --glob="**/*.stories.js"` with the `=`?

**Comment by phaistonian** [comment]
@shilman  Same issue ;(

**Comment by shilman** [comment]
Do you have 55 `.stories.js` files in your project? I think it's sending other files that it shouldn't be sending? What if you point it at `src/**/*.stories.js` or something like that?

**Comment by phaistonian** [comment]
Yes, this is the correct figure.

I tried it in a different system and it worked.

Perhaps an `rm -rf node_modules && yarn` would solve it.

Thank you.

**Comment by shilman** [comment]
Pretty strange. Glad you figured it out! 👍

**Comment by jayliu50** [comment]
Not working for me.  No stories show up whatsoever.

- ran the script. all stories.js files transformed fine, as per manually inspection.
- changing any story to CSF makes it disappear from the UI. 
    - Going with output from the script makes ALL stories disappear (all were transformed successfully).
    - change any stories BACK to `storiesOf` makes them reappear
- NO errors in the browser console
- NO errors in the terminal
- config matches that of the tutorial 
- I can verify that all stories ARE being loaded through `function loadStories() { req.keys().forEach(filename => {console.log(filename); return req(filename));} }

**Comment by shilman** [comment]
@jayliu50 please read the "loading stories" documentation:

https://github.com/storybookjs/storybook/blob/next/docs/src/pages/basics/writing-stories/index.md#loading-stories

Your `loadStories` function needs to return a value if you want to use CSF.

**Comment by jayliu50** [comment]
@shilman thanks for the reply!

Yes, I have a config.js. (it was all working fine in 5.1. As far as I'm aware, this hasn't changed in 5.2?)

Thanks

```
import React, { Fragment } from 'react';

import { configure, addDecorator } from '@storybook/react';
import GlobalStyle from '../src/styles/global';

// automatically import all files ending in *.stories.js
const req = require.context('../src', true, /\.stories\.js$/);

function loadStories() {
  req.keys().forEach(filename => req(filename));
}

addDecorator(storyFn => (
  <Fragment>
    {storyFn()}
    <GlobalStyle></GlobalStyle>
  </Fragment>
));

configure(loadStories, module);

```

**Comment by phaistonian** [comment]
The way to _fix_ this is to move `babel.config.js` so that it's not used when migrating.

When done, you can put it back / rename it.
