### ISSUE TITLE
Cannot use `useAddonState` inside a react-native addon.

### ISSUE THREAD

**Issue by Okazari** [storybookjs/storybook#8982]
**Describe the bug**
Hi ! I'm currently trying to develop an hybrid addon (working on both storybook web and storybook in react native). Everything worked fine until i used `useAddonState`. It still work in web but i get the `invalid hook call. Hooks can only be claled inside of the body of a function component` error when it run on the react-native app.

**To Reproduce**

1. Create an addon like this : 
```js
import React, { useState } from "react";
import { STORY_RENDERED } from "@storybook/core-events";
import { Text, View } from "react-native";
import addons, { types } from "@storybook/addons";
import { useParameter, useAddonState } from "@storybook/api";

const ADDON_ID = "myaddon";
const PARAM_KEY = "myAddon";
const PANEL_ID = `${ADDON_ID}/panel`;

const MyPanel = () => {
  const [bla] = useAddonState("test", "blablaaaaaaaa");
  return <Text>{bla}</Text>;
};

addons.register(ADDON_ID, api => {
  const title = "My Addon";

  addons.addPanel(PANEL_ID, {
    type: types.PANEL,
    title,
    render: ({ active, key }) => (
      <View>
        <MyPanel />
      </View>
    ),
    paramKey: PARAM_KEY
  });
});
```
2. Add it into a react-native storybook.
3. Watch it crash :'(

**Expected behavior**
`useAddonState` should work in react-native

**System:**Environment Info:

  System:
    OS: Linux 5.3 Ubuntu 19.10 (Eoan Ermine)
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.19.2 - ~/.nvm/versions/node/v10.15.3/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
  Browsers:
    Chrome: 73.0.3683.75
    Firefox: 70.0.1
  npmPackages:
    @storybook/addon-actions: ^5.3.0-alpha.15 => 5.3.0-beta.9 
    @storybook/addon-docs: ^5.3.0-alpha.15 => 5.3.0-beta.9 
    @storybook/addon-links: ^5.3.0-alpha.15 => 5.3.0-beta.9 
    @storybook/addon-ondevice-notes: ^5.2.6 => 5.2.6 
    @storybook/react: ^5.3.0-alpha.15 => 5.3.0-beta.9 
    @storybook/react-native: ^5.2.6 => 5.2.6 

Running on Android (Samsung Galaxy S9)

**Comment by Okazari** [comment]
Curious thing is that if replace `useAddonState` with a regular `useState` everything works fine on both platform :thinking:

**Comment by jonniebigodes** [comment]
i'm running into the same issue aswell, with `useParameter` i know that for react web you have to install `@babel/preset-react` to make it work with the api. I haven't tested it with react native but it seems that a good start is adding this package and change babel config and see if it works.
