### ISSUE TITLE
What if the component can have undefined as color prop ?

### ISSUE THREAD

**Issue by gothraven** [storybookjs/storybook#8988]
**Is your feature request related to a problem? Please describe.**
I would like to select a color using `color(..)` and in the same time be able to not send any color `undefined` to test the component default params.

**Describe the solution you'd like**
maybe change the modal which shos colors to have an option to deactivate it which means undefined.

**Describe alternatives you've considered**
I tried to look if there are any combine options in the package api, and example would be:
```js
combien(color(...), select(...))
```
```js
select('color or not', [color(...), undefined], undefined)
```

**Are you able to assist bring the feature to reality?**
maybe ... but it would take time to look around and understand the project, because this is the first time I use it.

**Comment by hcz** [comment]
You can use a workaround for TypeScript: 
```typescript
const components: Record<string, HTMLTag | undefined> = {
	none: undefined,
	pre: 'pre',
	code: 'code'
};
const component = select('component', components, components.none);
```
Also, current version supports this way to use undefined value:
```javascript
const components = ['pre', 'code', undefined];
const component = select('component', components, undefined);
```
