### ISSUE TITLE
Get rid of the harmful effects of zloirock and his core-js library

### ISSUE THREAD

**Issue by dmaksimovic** [storybookjs/storybook#8990]
**Is your feature request related to a problem? Please describe.**
When npm install is executed, the terminal is full of messages like:

```
Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
```
This is a major problem in the open source community, that we may depend on work of someone who might as well go nuts at some moment and we are at his mercy. There has been a big discussion here https://github.com/zloirock/core-js/issues/635 where the author is openly reckless and promotes the freedom to clog his own library any way he wants. It is also being discussed around the internet. 

**Describe the solution you'd like**
Now that it has been identified, I believe major libraries should break apart from this library, and replace its functionality with something else.

**Are you able to assist bring the feature to reality?**
I would be happy to try, unless there is someone capable of doing it much faster than me.

**Comment by ezhikov** [comment]
Sorry for intrusion, but I believe this issue title should be worded in some other way. I believe that in current state it violates code of conduct (insulting).

I, personally, have no problems with existence of this issue, I'm just concerned about words

**Comment by shilman** [comment]
Thanks @ezhikov, I agree with your concern about the issue and updated the title. @dmaksimovic I hope this reflects what you meant.
