### ISSUE TITLE
Addon-docs: Improve props table func signature display

### ISSUE THREAD

**Issue by patricklafrance** [storybookjs/storybook#8997]
**Is your feature request related to a problem? Please describe.**
After trying the latest beta, @domyen and I figured out the new "compact" display of long function is not ideal.

- Function summary max length should be increased from 70 to 150
- Expandable function should be have a multi line display instead of being displayed on a single line.

**Comment by shilman** [comment]
Egads!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-beta.14 containing PR #8998 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
