### ISSUE TITLE
Default path configuration

### ISSUE THREAD

**Issue by SergeS** [storybookjs/storybook#9002]
**Is your feature request related to a problem? Please describe.**
I would like to specify default story to start (Ie. I have some intro stories and mdx explaining some core concepts of project)

**Describe the solution you'd like**
Specify somewhere, which path should be chosen when no path is provided

**Describe alternatives you've considered**
Hardcoding full URL into other documents etc., but this is annoying and there is risk that stories tructure will change overtime

**Are you able to assist bring the feature to reality?**
yes, I can...

**Additional context**
I was looking for it in docs and elsewhere, but without success

**Comment by shilman** [comment]
Closing as dupe to #7664

**Comment by SergeS** [comment]
@shilman Hi, I'm not sure if this is exact duplication - in my case I want to have this as default behavior for built version, not only while developing

**Comment by SergeS** [comment]
and I would preffer to have it in config.js / storybook configuration

**Comment by shilman** [comment]
Feel free to comment on #7664
