### ISSUE TITLE
CLI: Exclude pre-existing named exports in `storiesof-to-csf` migration

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#9007]
`storiesOf` users can safely export whatever they want (helper functions, data, etc.). But these are interpreted as stories in CSF. So the migration should be smart enough to flag these as `excludeStories`, which is what CSF uses to ignore exports.

**Comment by shilman** [comment]
@tmeasday This behavior is already supported:

https://github.com/storybookjs/storybook/blob/next/lib/codemod/src/transforms/__testfixtures__/storiesof-to-csf/exports.input.js

https://github.com/storybookjs/storybook/blob/next/lib/codemod/src/transforms/__testfixtures__/storiesof-to-csf/exports.output.snapshot

**Comment by tmeasday** [comment]
Great!
