### ISSUE TITLE
addon-docs bug: Toolbar and Addon Panel not hidden when viewing MDX story

### ISSUE THREAD

**Issue by JoshTumath** [storybookjs/storybook#9009]
**Describe the bug**
Our Storybook contains a mixture of component stories made using the CSF format with associated MDX docs, and standalone MDX stories with a filename ending in `.stories.mdx`. Storybook's toolbar has those buttons for flicking between the Canvas view and the Docs view.

When I open a standalone MDX story, those buttons are still showing, so I can be looking at a doc in the Canvas and the addon panel is still open.

**To Reproduce**
Steps to reproduce the behaviour:
1. Set up the Storybook docs addon
2. Create a component story using CSF and link to some MDX docs
3. Create a standalone MDX doc with a filename ending in `.stories.mdx`.

**Expected behavior**
When viewing a standalone MDX doc, the toolbar and addon bar should be hidden.

**Screenshots**
<img width="725" alt="Screenshot 2019-11-29 at 16 26 12" src="https://user-images.githubusercontent.com/1760227/69881456-029e2f80-12c5-11ea-8f14-475314097486.png">

**Code snippets**
```js
addParameters({
  options: {
    isFullscreen: false,
    showAddonsPanel: true,
    showSearchBox: false,
    panelPosition: 'bottom',
    enableShortcuts: true,
    theme: create({
      base: 'light',
      brandTitle: 'BBC Web Core',
      brandUrl: 'https://example.com',
      gridCellSize: 12
    }),
    storySort: (a, b) => (a[1].kind === b[1].kind ? 0 : a[1].id.localeCompare(b[1].id, { numeric: true }))
  },
  viewport: {
    viewports: INITIAL_VIEWPORTS
  }
});
```

**System:**
```
Environment Info:

  System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.19.0 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
  Browsers:
    Chrome: 78.0.3904.108
    Safari: 13.0.3
```

**Additional context**

**Comment by rtkaaho** [comment]
Excited for this to be fixed! :)

**Comment by shilman** [comment]
This has been fixed for awhile now. Closing.
