### ISSUE TITLE
Failed to load preset @storybook/addon-docs/preset

### ISSUE THREAD

**Issue by Matrixbirds** [storybookjs/storybook#9015]
branch: next
example path: examples/cra-ts-kitchen-sink

after install npm dependency and execute npm run build-storybook

**Comment by shilman** [comment]
Which version of addon-docs is it trying to install?

**Comment by p-moreira** [comment]
Hi @Matrixbirds , I think the docs missing the path to the specific framework you is using. The dos point us to add this line: 

`module.exports = ['@storybook/addon-docs/preset']`

but this line would be:

`module.exports = ['@storybook/addon-docs/react/preset']` or
`module.exports = ['@storybook/addon-docs/vue/preset']` etc

**Comment by shilman** [comment]
@p-moreira @Matrixbirds the version on `next` (`5.3.0-beta.x`) uses `@storybook/addon-docs/preset`. The old paths still work but are deprecated and will be removed in 6.0.
