### ISSUE TITLE
Examples of storybook demos with possible codesandbox links

### ISSUE THREAD

**Issue by Angelk90** [storybookjs/storybook#9024]
**Is your feature request related to a problem? Please describe.**
Thanks to storybook you can see an example of how to use the component, but I often want to try it on codesandbox.
Storybook has the story menu where you can see the code that was used.

**Describe the solution you'd like**
My suggestion would be the possibility of integrating an "edit to codesandbox" button, so if the user wants can directly try the code, even with different data or settings different from those initially set by the type of element selected by the storybook, but starting from the base that user wanted to try.

Example: [Link](https://material-ui.com/components/skeleton/#youtube-example)
For each code, there is a section to try it on codesandbox.

**Comment by dvnrsn** [comment]
I am unable to get storybook to work for me in a codesandbox though I see plenty of links on google for a codesandboxes that seems configured. There must be something I'm misunderstanding about stoybook's bundling and serving in that environment?

**Comment by dvnrsn** [comment]
The reason this is relevant to me is that I'm trying to understand and replicate the basic badge [docspage](https://github.com/storybookjs/storybook/blob/master/addons/docs/docs/docspage.md) locally without success. I need to get it working in a siloed env to wrap my mind around how the story docs are generated

**Comment by dvnrsn** [comment]
https://github.com/codesandbox/codesandbox-client/issues/1603

**Comment by Angelk90** [comment]
@shilman , @dvnrsn : Are there any news?

**Comment by xiaoxiangmoe** [comment]
0

**Comment by lpoulter** [comment]
This would be great it seems shopify do this but I'm not sure how. Prehaps something like this could be used.
https://www.npmjs.com/package/remark-codesandbox

**Comment by shilman** [comment]
I believe @kevin940726 just added a nice example to reaviz.io

**Comment by kevin940726** [comment]
@lpoulter Mind elaborate more? Open a reproduction issue in the [github repo](https://github.com/kevin940726/remark-codesandbox) would be great! Thx ❤️

**Comment by lpoulter** [comment]
@kevin940726 added #9632

**Comment by Angelk90** [comment]
@lpoulter : are there any news?

**Comment by lpoulter** [comment]
My issue was resolve, it was a problem with my config. I have managed to make use of remark-codesandbox following the example in reaviz.io
