### ISSUE TITLE
Production builds on storybook can fail.

### ISSUE THREAD

**Issue by pllee** [storybookjs/storybook#9026]
**Describe the bug**
@storybook/core depends on `"html-webpack-plugin": "^4.0.0-beta.2",` which has an issue when using [production mode](https://github.com/jantimon/html-webpack-plugin/issues/1311.
)
**To Reproduce**
```build-storybook -s```
I have not tested this on a fresh storybook install but my set up fails.

**Screenshots**
```
info => Loading manager config..
info => Loading presets
info => Compiling manager..
ERR! => Failed to build the manager
ERR!   Error: Cannot find module 'html-minifier'
ERR!
ERR!   - module.js:11 require
ERR!     internal/module.js:11:18
ERR!
ERR!   - index.js:445 HtmlWebpackPlugin.postProcessHtml
ERR!     [name]/[html-webpack-plugin]/index.js:445:9
ERR!
ERR!   - index.js:274 Promise.all.then.then
ERR!     [name]/[html-webpack-plugin]/index.js:274:25
```

**Comment by shilman** [comment]
@ndelangen can we upgrade this?
