### ISSUE TITLE
Disable query strings for addon-knobs

### ISSUE THREAD

**Issue by JamesIves** [storybookjs/storybook#9027]
Is there a way to remove the query string configuration ability with `addon-knobs`?  I'd like to prevent a user from sending a link with a pre-configured component as this opens the floor to potential vulnerabilities depending on the type of component. 

Either that or is there a way to have a "read only" prop for addon-knobs, that will show you the prop but won't allow you to modify it?

**Comment by JamesIves** [comment]
@shilman I'm happy to PR this feature if this is something the teem is open to. Lemme know!

**Comment by shilman** [comment]
@JamesIves sounds like it could be useful. would certainly be open to reviewing!

**Comment by JamesIves** [comment]
@shilman https://github.com/storybookjs/storybook/pull/9048
