### ISSUE TITLE
Storybook build failing - v5.2.8

### ISSUE THREAD

**Issue by salmanmd786** [storybookjs/storybook#9028]
We updated the storybook version 5.2.8 and it started breaking

Steps to reproduce
npm run storybook
npm run build-storybook

version 5.2.8

```js
> build-storybook -c .storybook -o .out
info @storybook/react v5.2.8
info 
info clean outputDir..
info => Copying prebuild dll's..
info => Building manager..
info => Loading manager config..
info => Loading presets
info => Loading custom addons config.
info => Compiling manager..
ERR! => Failed to build the manager
ERR! ./.storybook/addons.js
ERR! Module build failed (from ./node_modules/babel-loader/lib/index.js):
ERR! Error: Cannot find module './src/data'
ERR! Require stack:
```

**Comment by shilman** [comment]
Did you try clearing your node_modules? Can you provide a repro repo? I can't reproduce.

**Comment by JanithaR** [comment]
I am also facing errors right after upgrading.

```
error: bundling failed: Error: Unable to resolve module `../internals/function-to-string` from `/Users/janithar/Desktop/mobile_react_native/ProfessionalApp/node_modules/@storybook/react-native/node_modules/core-js/internals/redefine.js`: The module `../internals/function-to-string` could not be found from `/Users/janithar/Desktop/mobile_react_native/ProfessionalApp/node_modules/@storybook/react-native/node_modules/core-js/internals/redefine.js`. Indeed, none of these files exist:
  * `/Users/janithar/Desktop/mobile_react_native/ProfessionalApp/node_modules/@storybook/react-native/node_modules/core-js/internals/function-to-string(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`
  * `/Users/janithar/Desktop/mobile_react_native/ProfessionalApp/node_modules/@storybook/react-native/node_modules/core-js/internals/function-to-string/index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`
    at ModuleResolver.resolveDependency (/Users/janithar/Desktop/mobile_react_native/ProfessionalApp/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:163:15)
    at ResolutionRequest.resolveDependency (/Users/janithar/Desktop/mobile_react_native/ProfessionalApp/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (/Users/janithar/Desktop/mobile_react_native/ProfessionalApp/node_modules/metro/src/node-haste/DependencyGraph.js:283:16)
    at Object.resolve (/Users/janithar/Desktop/mobile_react_native/ProfessionalApp/node_modules/metro/src/lib/transformHelpers.js:261:42)
    at /Users/janithar/Desktop/mobile_react_native/ProfessionalApp/node_modules/metro/src/DeltaBundler/traverseDependencies.js:399:31
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/janithar/Desktop/mobile_react_native/ProfessionalApp/node_modules/metro/src/DeltaBundler/traverseDependencies.js:396:18)
    at /Users/janithar/Desktop/mobile_react_native/ProfessionalApp/node_modules/metro/src/DeltaBundler/traverseDependencies.js:269:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/janithar/Desktop/mobile_react_native/ProfessionalApp/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)
```

I did remove the `node_modules` folder and ran `npm install` and still getting the same error.

**Comment by shilman** [comment]
@JanithaR do you have a repro repo you can share?

**Comment by JanithaR** [comment]
@shilman Sorry, I can't share this repo. Let me see if I can recreate with a brand new project.

**Comment by salmanmd786** [comment]
`I too can't share the repo. below is configuration.

import { addParameters, configure, addDecorator } from '@storybook/react';
import { withA11y } from '@storybook/addon-a11y';
import { withInfo } from '@storybook/addon-info';
import { withKnobs } from '@storybook/addon-knobs';
import { withThemesProvider } from 'storybook-addon-emotion-theme';
import Theme from './theme';

addDecorator(withKnobs);
addDecorator(withA11y);
addDecorator(withInfo);
addDecorator(withThemesProvider(require('custom-themes')));

addParameters({
  a11y: {
    config: {},
    options: {
      checks: { 'color-contrast': { options: { noScroll: true } } },
      restoreScroll: true
    }
  },
  options: {
    theme: Theme,
    panelPosition: 'bottom'
  },
  backgrounds: [
    { name: 'White', value: '#FFFFFF' },
    { name: 'Mid Grey', value: '#C4C4C4' },
  ]
});

const loadStories = () => {
  const req = require.context('../src/components', true, /\.stories\.js$|\/stories\/.*\.js$/);
  req.keys().forEach(filename => req(filename));
};

configure(loadStories, module);
`

**Comment by shilman** [comment]
For anybody experiencing this problem, does `5.2.7` work for you?

**Comment by JanithaR** [comment]
Don't know about 5.2.7 but I reverted to 5.2.6 which I had originally and things work just fine.

**Comment by salmanmd786** [comment]
I see 5.2.8 is working fine now. Thank you.
