### ISSUE TITLE
Storybook Build Failed

### ISSUE THREAD

**Issue by Jordan-ascent** [storybookjs/storybook#9029]
### Issue
Storybook Build Failed

### Steps to reproduce
cd file-directory
npm run storybook
build fail error

**Error:**
> taskbox@0.1.0 storybook /Users/jordankramer/taskbox
> start-storybook -p 9009 -s public

info @storybook/react v5.2.8
info 
info => Loading static files from: /Users/jordankramer/taskbox/public .
info => Loading presets
info => Loading presets
info => Loading custom addons config.
info => Using default Webpack setup.
info => Loading create-react-app config.
webpack built 3c048aa1b649074924d5 in 6010ms
✖ ｢wdm｣: Hash: 3c048aa1b649074924d5
Version: webpack 4.41.0
Time: 6010ms
Built at: 12/02/2019 1:57:00 PM
                                          Asset       Size        Chunks                                Chunk Names
                            asset-manifest.json  640 bytes                [emitted]                     
                                    iframe.html   3.05 KiB                [emitted]                     
            main.3c048aa1b649074924d5.bundle.js   5.04 KiB          main  [emitted] [immutable]         main
        main.3c048aa1b649074924d5.bundle.js.map  219 bytes          main  [emitted] [dev]               main
    runtime~main.3c048aa1b649074924d5.bundle.js   31.2 KiB  runtime~main  [emitted] [immutable]         runtime~main
runtime~main.3c048aa1b649074924d5.bundle.js.map   32.3 KiB  runtime~main  [emitted] [dev]               runtime~main
    vendors~main.3c048aa1b649074924d5.bundle.js    688 KiB  vendors~main  [emitted] [immutable]  [big]  vendors~main
vendors~main.3c048aa1b649074924d5.bundle.js.map    690 KiB  vendors~main  [emitted] [dev]               vendors~main
Entrypoint main [big] = runtime~main.3c048aa1b649074924d5.bundle.js runtime~main.3c048aa1b649074924d5.bundle.js.map vendors~main.3c048aa1b649074924d5.bundle.js vendors~main.3c048aa1b649074924d5.bundle.js.map main.3c048aa1b649074924d5.bundle.js main.3c048aa1b649074924d5.bundle.js.map
[0] multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/config.js (webpack)-hot-middleware/client.js?reload=true&quiet=true 64 bytes {main} [built]
[./.storybook/config.js] 3.02 KiB {main} [built] [failed] [1 error]
[./node_modules/@storybook/core/dist/server/common/polyfills.js] 120 bytes {vendors~main} [built]
[./node_modules/@storybook/core/dist/server/preview/globals.js] 93 bytes {vendors~main} [built]
[./node_modules/@storybook/core/node_modules/regenerator-runtime/runtime.js] 23 KiB {vendors~main} [built]
[./node_modules/airbnb-js-shims/index.js] 40 bytes {vendors~main} [built]
[./node_modules/airbnb-js-shims/target/es5.js] 88 bytes {vendors~main} [built]
[./node_modules/core-js/features/symbol/index.js] 359 bytes {vendors~main} [built]
[./node_modules/global/window.js] 232 bytes {vendors~main} [built]
[./node_modules/querystring-es3/index.js] 127 bytes {vendors~main} [built]
[./node_modules/webpack-hot-middleware/client-overlay.js] (webpack)-hot-middleware/client-overlay.js 2.17 KiB {vendors~main} [built]
[./node_modules/webpack-hot-middleware/client.js?reload=true&quiet=true] (webpack)-hot-middleware/client.js?reload=true&quiet=true 7.68 KiB {vendors~main} [built]
[./node_modules/webpack-hot-middleware/node_modules/strip-ansi/index.js] (webpack)-hot-middleware/node_modules/strip-ansi/index.js 161 bytes {vendors~main} [built]
[./node_modules/webpack-hot-middleware/process-update.js] (webpack)-hot-middleware/process-update.js 4.35 KiB {vendors~main} [built]
[./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {vendors~main} [built]
    + 232 hidden modules

ERROR in ./.storybook/config.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: [BABEL] /Users/jordankramer/taskbox/.storybook/config.js: Cannot find module './src/data'
Require stack:
- /Users/jordankramer/taskbox/node_modules/core-js-compat/helpers.js
- /Users/jordankramer/taskbox/node_modules/core-js-compat/get-modules-list-for-target-version.js
- /Users/jordankramer/taskbox/node_modules/babel-preset-react-app/node_modules/@babel/preset-env/lib/polyfills/corejs3/entry-plugin.js
- /Users/jordankramer/taskbox/node_modules/babel-preset-react-app/node_modules/@babel/preset-env/lib/index.js
- /Users/jordankramer/taskbox/node_modules/babel-preset-react-app/create.js
- /Users/jordankramer/taskbox/node_modules/babel-preset-react-app/index.js
- /Users/jordankramer/taskbox/node_modules/@babel/core/lib/config/files/plugins.js
- /Users/jordankramer/taskbox/node_modules/@babel/core/lib/config/files/index.js
- /Users/jordankramer/taskbox/node_modules/@babel/core/lib/index.js
- /Users/jordankramer/taskbox/node_modules/babel-loader/lib/index.js
- /Users/jordankramer/taskbox/node_modules/loader-runner/lib/loadLoader.js
- /Users/jordankramer/taskbox/node_modules/loader-runner/lib/LoaderRunner.js
- /Users/jordankramer/taskbox/node_modules/webpack/lib/NormalModule.js
- /Users/jordankramer/taskbox/node_modules/webpack/lib/NormalModuleFactory.js
- /Users/jordankramer/taskbox/node_modules/webpack/lib/Compiler.js
- /Users/jordankramer/taskbox/node_modules/webpack/lib/webpack.js
- /Users/jordankramer/taskbox/node_modules/@storybook/core/dist/server/build-static.js
- /Users/jordankramer/taskbox/node_modules/@storybook/core/server.js
- /Users/jordankramer/taskbox/node_modules/@storybook/react/dist/server/index.js
- /Users/jordankramer/taskbox/node_modules/@storybook/react/bin/index.js (While processing: "/Users/jordankramer/taskbox/node_modules/babel-preset-react-app/index.js$0$9")
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/jordankramer/taskbox/node_modules/core-js-compat/helpers.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/jordankramer/taskbox/node_modules/core-js-compat/get-modules-list-for-target-version.js:2:51)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/config.js (webpack)-hot-middleware/client.js?reload=true&quiet=true main[2]
Child HtmlWebpackCompiler:
                          Asset     Size               Chunks  Chunk Names
    __child-HtmlWebpackPlugin_0  536 KiB  HtmlWebpackPlugin_0  HtmlWebpackPlugin_0
    Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
    [./node_modules/html-webpack-plugin/lib/loader.js!./node_modules/@storybook/core/dist/server/templates/index.ejs] 2.08 KiB {HtmlWebpackPlugin_0} [built]
    [./node_modules/lodash/lodash.js] 528 KiB {HtmlWebpackPlugin_0} [built]
    [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {HtmlWebpackPlugin_0} [built]
    [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {HtmlWebpackPlugin_0} [built]

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

WARN force closed preview build

**Comment by shilman** [comment]
Closing as dupe to #9028
