### ISSUE TITLE
Vue: Examples for `nuxt`, `vue-cli`

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#9031]
## Why

Our current `vue-kitchen-sink` is a vanilla Vue setup. But many users have `nuxt.js` or `vue-cli` setups. Having examples of these in the monorepo will help reduce support burden, and also help ensure compatibility with new features as they are introduced.

## What

- [ ] Nuxt example
- [ ] Vue CLI example

**Comment by nonlinearcom** [comment]
+1 for the Nuxt example :)
