### ISSUE TITLE
Use Triconfig in CLI generators

### ISSUE THREAD

**Issue by tmeasday** [storybookjs/storybook#9032]
Switch all app skeletons to use just `.storybook/main.js`.

**Comment by shilman** [comment]
Jiminy cricket!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-beta.17 containing PR #9075 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Yo-ho-ho!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-beta.18 containing PR #9075 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.
