### ISSUE TITLE
Transformation error ... TypeError: Cannot read property 'declarations' of null

### ISSUE THREAD

**Issue by pgangwani** [storybookjs/storybook#9033]
**Describe the bug**
I am migrating storybook repo from stories-of to csf using https://www.npmjs.com/package/@storybook/codemod, getting error as in screenshots

**To Reproduce**
Using `jscodeshift` and `@storybook/codemod`
1.  In existing up & running storyOf stories repo, run `./node_modules/.bin/jscodeshift -t ./node_modules/@storybook/codemod/dist/transforms/storiesof-to-csf.js . --ignore-pattern "node_modules|dist"
`
2. See error in screenshot section 

Using `sb migrate`
1. In existing up & running storyOf stories repo, run `npx -p @storybook/cli@next sb migrate storiesof-to-csf  --glob "packages/**/*.story.js*" `
2. getting error `Error: Cannot find module '@babel/runtime/regenerator' `

**Expected behavior**
All story.jsx files should be migrated to csf which is one step ahead of what I want to achieve (to mdx format) [stories-of to mdx]

**Screenshots**
Using `jscodeshift` and `@storybook/codemod`
![image](https://user-images.githubusercontent.com/14316332/70019555-a5013000-15af-11ea-971a-11c752147cca.png)

Using `sb migrate`
![image](https://user-images.githubusercontent.com/14316332/70020221-fad6d780-15b1-11ea-9798-eff730bebd4d.png)

**Code snippets**
If applicable, add code samples to help explain your problem.

**System:**

```
Environment Info:

  System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Binaries:
    Node: 8.15.1 - ~/.nvm/versions/node/v8.15.1/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v8.15.1/bin/npm
  Browsers:
    Chrome: 78.0.3904.87
    Firefox: 65.0.1
    Safari: 13.0.3
  npmPackages:
    @storybook/addon-a11y: ^5.2.8 => 5.2.7 
    @storybook/addon-actions: ^5.2.8 => 5.2.7 
    @storybook/addon-info: ^5.2.8 => 5.2.7 
    @storybook/addon-jest: ^5.2.8 => 5.2.7 
    @storybook/addon-knobs: ^5.2.8 => 5.2.7 
    @storybook/addon-storysource: ^5.2.8 => 5.2.7 
    @storybook/addon-viewport: ^5.2.8 => 5.2.7 
    @storybook/react: ^5.2.8 => 5.2.7 

```

**Additional context**
I am using react & styled-components mainly.Moreover, if required, I am happy to give additional context.

**Comment by pgangwani** [comment]
@shilman : could you please help ?

**Comment by shilman** [comment]
Try the workaround of running `jscodeshift` directly per https://github.com/storybookjs/storybook/blob/next/lib/codemod/README.md

**Comment by pgangwani** [comment]
Unfortunately, It didnt work too, was giving 1st screenshot

**Comment by shilman** [comment]
Ok, please share a repro
