### ISSUE TITLE
Run Chromatic on every example app

### ISSUE THREAD

**Issue by tmeasday** [storybookjs/storybook#9039]
Also run at least one (smaller) example on a Chromatic app that includes IE&FF.

**Comment by shilman** [comment]
Son of a gun!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-beta.22 containing PR #9114 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
