### ISSUE TITLE
IStory interface is not exported anymore

### ISSUE THREAD

**Issue by andrei-ilyukovich** [storybookjs/storybook#9041]
There was possibility to import `IStory` interface from `"@storybook/angular"` before (if I'm not mistaken it is still possible in v5.0.6). In the latest versions there is no such import available. It looks like proper replacement could be `StoryFnAngularReturnType`, but it is used internally and not exported  from the root of  `"@storybook/angular"` and only could be retrieved by 
`import { StoryFnAngularReturnType } from "@storybook/angular/dist/client/preview/types";` which is not a proper way.
Below is the code snippet where we used `IStory` before:

```typescript
const wrap: Function = (templateFn) => (storyFn) => {
    const story: IStory = storyFn();
    return {
        ...story,
        template: templateFn(story.template)
    };
};
addDecorator(wrap((content) => `<sdo-storybook-settings></sdo-storybook-settings>${content}`));
```
System:
`"@storybook/*": "5.2.4"`

**Comment by shilman** [comment]
Yay!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.8 containing PR #9097 that references this issue. Upgrade today to try it out!

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
¡Ay Caramba!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-alpha.1 containing PR #9097 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.
