### ISSUE TITLE
'@storybook/addon-storyshots' package contains .ts files instead of .d.ts

### ISSUE THREAD

**Issue by andrei-ilyukovich** [storybookjs/storybook#9042]
'@storybook/addon-storyshots' package contains .ts files as on the screenshot below:

![image](https://user-images.githubusercontent.com/6919053/70055518-bf0c3400-15ea-11ea-8809-37bdb562995e.png)

And if using storyshots in the Angular project with typescript it is necessary to setup `transformIgnorePatterns` section in storybook `jest.config.js` to allow `ts-jest` transpile needed files on the fly:
```typescript
...
transformIgnorePatterns: [
        'node_modules/(?!@storybook/addon-storyshots/*)'
    ],
...
```
To my mind '@storybook/addon-storyshots' should only emit already transpiled .js files with .d.ts files to make them work with typescript.

In addition local transpilation also has some issues:

![image](https://user-images.githubusercontent.com/6919053/70056078-e6173580-15eb-11ea-95de-ca5655d8581d.png)

It looks like '@storybook/addon-storyshots' still depends on Angular 7 but my project uses Angular 8 version so I need to disable `diagnostics` to avoid mentioned error:

```typescript
globals: {
        "ts-jest": {
            tsConfig: "<rootDir>/../tsconfig.json",
            stringifyContentPathRegex: "\\.html$",
            // Disable "jest" diagnostics flag to pass through failures during transpiling "@storybook/addon-storyshots" files
            diagnostics: false,
            astTransformers: [
                require.resolve("jest-preset-angular/InlineHtmlStripStylesTransformer")
            ]
        }
    }
```
**System:**
```
"@storybook/*": "5.2.4"
"@angular/*": "8.2.*"
```

**Comment by n3utrino** [comment]
Another possible workaround is, switch the order of the `moduleFileExtensions` in your jest.config.js so `js` is picked up first.

```
module.exports = {
    moduleFileExtensions: ['js', 'html', 'ts', 'json'],
};
```

**Comment by andrei-ilyukovich** [comment]
yeah, that also works, thanks a lot. But technically speaking it is better to use "typescript order" as jest documentation recommends:

> We recommend placing the extensions most commonly used in your project on the left, so if you are using TypeScript, you may want to consider moving "ts" and/or "tsx" to the beginning of the array.

**Comment by shilman** [comment]
I don't think this is still a problem in 5.3. Closing!
