### ISSUE TITLE
HMR breaks when changing preset to non-framework specific one

### ISSUE THREAD

**Issue by rblock-aw** [storybookjs/storybook#9044]
**Describe the bug**
When changing the content of `.storybook/presets.js` from
```javascript
module.exports = ['@storybook/addon-docs/vue/preset'];
```
to
```javascript
module.exports = ['@storybook/addon-docs/preset'];
```
Storybook stops detecting changes in my underlying Single-File-Components and doesn't update stories when changing components or stories.

**To Reproduce**
1. Change the content of `.storybook/presets.js` as described above (to get rid of the deprecation warning).
2. Open a story
3. Change either the story or the component the story is about (or even both) and save
4. Notice that the Webpack did not detect a change and thus no update is sent to the browser.

**Expected behavior**
That the browser automatically shows the updated content.

**System:**
```
Environment Info:
  System:
    OS: macOS 10.15.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 13.2.0 - /usr/local/bin/node
    Yarn: 1.21.0 - /usr/local/bin/yarn
    npm: 6.13.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 78.0.3904.108
    Firefox: 65.0.1
    Safari: 13.0.3
  npmPackages:
    @storybook/addon-actions: ^5.3.0-alpha.44 => 5.3.0-beta.14 
    @storybook/addon-docs: ^5.3.0-alpha.44 => 5.3.0-beta.14 
    @storybook/addon-knobs: ^5.3.0-alpha.44 => 5.3.0-beta.14 
    @storybook/addon-links: ^5.3.0-alpha.44 => 5.3.0-beta.14 
    @storybook/addons: ^5.3.0-alpha.44 => 5.3.0-beta.14 
    @storybook/client-api: ^5.3.0-alpha.44 => 5.3.0-beta.14 
    @storybook/core: ^5.3.0-alpha.44 => 5.3.0-beta.14 
    @storybook/vue: ^5.3.0-alpha.44 => 5.3.0-beta.14 
```

**Comment by shilman** [comment]
@rblock-aw do you have a repro i can look at? the vue-kitchen-sink example in the storybook monorepo is working fine: https://github.com/storybookjs/storybook/tree/next/examples/vue-kitchen-sink

**Comment by rblock-aw** [comment]
Unfortunately I cannot share the repo in which I encountered the issue. If I have some spare time, I will try to create a minimal example and update this issue.

**Comment by patrick-radulian** [comment]
Any update on this topic? I've run into issues with HMR as well - not in so far as the changes are not detected, but the browser does not reload the respective updated resources. WebPack re-builds when changes occur.
I am interested if both issues might stem from the same root cause.
