### ISSUE TITLE
Angular Storybook Tutorial

### ISSUE THREAD

**Issue by SipOfJoe** [storybookjs/storybook#9056]
**Describe the bug**

I'm trying to build out a composite component in the angular storybook tutorial https://www.learnstorybook.com/intro-to-storybook/angular/en/composite-component/

In the "Build out the states" section it wants me to import { Task } from './task.model';  however, the tutorial did not have me build a task.model..... I even looked in the code to keep synced with the chapter and it also does not have the task.model ?

I'm unable to complete the tutorial until I get this resolved it seems...?

What's up with the task.model ?

**Comment by shilman** [comment]
Please file here: https://github.com/chromaui/learnstorybook.com
