### ISSUE TITLE
Addon-docs: Meta title don't escape quotes  

### ISSUE THREAD

**Issue by patricklafrance** [storybookjs/storybook#9062]
**Describe the bug**
The following code DOESN'T work:

```
<Meta title="Introduction|What's available?" />
```

But the following work:

```
<Meta title="Introduction|What\'s available?" />
```

Error:

![image](https://user-images.githubusercontent.com/794579/70172448-aeb59100-169e-11ea-98f0-b6542f6a6092.png)

**Expected behavior**
Quotes should be escaped by default.

**Comment by atanasster** [comment]
This should be fixed in #9069, closing for now
