### ISSUE TITLE
Failed to execute 'createElement' on 'Document': The tag name provided ('static/media/arrow-right.981294d1.svg') is not a valid name.

### ISSUE THREAD

**Issue by tranthaison1231** [storybookjs/storybook#9070]
I have error in storybook when config svgr webpack for project. 

This is my config

```
const path = require('path');

module.exports = async ({ config }) => {
  config.module.rules.push(
    {
      test: /\.less$/,
      use: [
        'style-loader',
        'css-loader',
        {
          loader: 'less-loader',
          options: {
            javascriptEnabled: true,
          },
        },
      ],
      include: path.resolve(__dirname, '../'),
    },
    {
      test: /\.svg$/,
      use: [
        {
          loader: '@svgr/webpack',
          options: {
            icon: true,
          },
        },
      ],
    }
  );
  config.resolve.extensions.push('.js', '.jsx', '.svg');
  config.resolve.modules.push(path.resolve('.'));
  return config;
};
```

**Comment by josephchenghandshakes** [comment]
Hi @tranthaison1231 , do you have the solution for the error?

**Comment by GR34SE** [comment]
> Hi @tranthaison1231 , do you have the solution for the error?

This solution worked for me: 
https://stackoverflow.com/a/61706308/10331102

add the following to yours storybook's webpackFinal config:
```
        const fileLoaderRule = config.module.rules.find(
            (rule) => rule.test && rule.test.test(".svg")
        );
        fileLoaderRule.exclude = /\.svg$/;

        config.module.rules.push({
            test: /\.svg$/,
            enforce: "pre",
            loader: require.resolve("@svgr/webpack")
        });
```

**Comment by andyford** [comment]
Just ran into this with a Preact project.

solution  was the same as was posted by  @GR34SE  but with a different loader

```{
  test: /\.svg$/,
  enforce: 'pre',
  use: ['preact-svg-loader'],
}```

**Comment by dtaltana** [comment]
> const fileLoaderRule = config.module.rules.find(
>             (rule) => rule.test && rule.test.test(".svg")
>         );
>         fileLoaderRule.exclude = /\.svg$/;
> 
>         config.module.rules.push({
>             test: /\.svg$/,
>             enforce: "pre",
>             loader: require.resolve("@svgr/webpack")
>         });

Thank you so much for posting this, this absolutely worked!

**Comment by imki123** [comment]
Thank you! @GR34SE 
In my case, I had 2 svg rules. I used `filter` and `forEach` instead of find.
```
const fileLoaderRule = config.module.rules.filter(
    (rule) => rule.test && rule.test.test('.svg'),
  )
  fileLoaderRule.forEach(rule => rule.exclude = /\.svg$/)

  config.module.rules.push({
    test: /\.svg$/,
    enforce: 'pre',
    loader: require.resolve('@svgr/webpack'),
  })
```

**Comment by deepak-contentstack** [comment]
> const fileLoaderRule = config.module.rules.find(
>             (rule) => rule.test && rule.test.test(".svg")
>         );
>         fileLoaderRule.exclude = /\.svg$/;
> 
>         config.module.rules.push({
>             test: /\.svg$/,
>             enforce: "pre",
>             loader: require.resolve("@svgr/webpack")
>         });

@GR34SE, I am upgrading my project with storybook@7 and stuck with same issue for svg. I tried using the modification suggested by you, but now m getting error of `TypeError: Cannot set properties of undefined (setting 'exclude')`. 
It seem that there is no fileLoader in rules. 
I also tried logging all the rules within config which output is:
`[
  { test: /\.md$/, type: 'asset/source' },
  {
    enforce: 'pre',
    exclude: /@babel(?:\/|\\{1,2})runtime/,
    test: /\.(js|mjs|jsx|ts|tsx|css)$/,
    loader: '/Users/deepak/Documents/work/contentstack/venus-components/node_modules/react-scripts/node_modules/source-map-loader/dist/cjs.js',
    include: [
      '/Users/deepak/Documents/work/contentstack/venus-components/tools/.storybook'
    ]
  },
  {
    oneOf: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object]
    ]
  },
  { test: /(stories|story)\.mdx$/, use: [ [Object] ] },
  {
    test: /\.mdx$/,
    exclude: /(stories|story)\.mdx$/,
    use: [ [Object] ]
  },
  { test: /\.m?js$/, type: 'javascript/auto' },
  { test: /\.m?js$/, resolve: { fullySpecified: false } }
]`
I am confused now that if there is no fileLoader then how this error is appearing .

**Comment by Bender101** [comment]
```
config.module.rules = config.module.rules.map((rule: RuleSetRule) => {
    if (/svg/.test(rule.test as string)) {
      return { ...rule, exclude: /\.svg$/i };
    }

    return rule;
  });

  config.module.rules.push({
    test: /\.svg$/,
    use: ["@svgr/webpack"],
  });
```
