### ISSUE TITLE
Keyboard shortcut for @storybook/addon-viewport

### ISSUE THREAD

**Issue by muhajirdev** [storybookjs/storybook#9073]
**Is your feature request related to a problem? Please describe.**
Sometimes I implement component (Figma -> React) with storybook. It often switch between two viewports. It would be nice if we have a shortcut to switch between two viewport

**Describe the solution you'd like**
Honestly. Probaly something like cmd + i . to toggle between two viewport 

**Describe alternatives you've considered**
There's also other consideration when there are many viewport. Probably we can also use alt + 1, alt + 2 , alt + 3.

**Are you able to assist bring the feature to reality?**
Currently not yet. But I might try it when I have free time

**Comment by kaelig** [comment]
For me, cycling through the viewports with <kbd>V</kbd> (next) and <kbd>shift</kbd> + <kbd>V</kbd> (previous) would be a nice addition.
