### ISSUE TITLE
[addon-docs] Why Props component doesn't work?

### ISSUE THREAD

**Issue by Mu-xue** [storybookjs/storybook#9074]
In `index.stories.mdx` :
```
import { Meta, Preview, Story, Props } from '@storybook/addon-docs/blocks';
import { HomePanel } from '@/index';

<Meta title='Mdx|Home|Panel' component={HomePanel} />

# HomePanel

With `MDX` we can define a story for `HomePanel` right in the middle of our
markdown documentation.

<Preview>
  <Story name='Panel'>
     <HomePanel title="abc" amount="1000" description="123" />
  </Story>
</Preview>

## Props

<Props of={HomePanel} />
```

In `HomePanel.tsx`:
```
import React, { ReactNode, FC } from 'react'

interface HomePanelProps {
  title: string | ReactNode
  amount: string | ReactNode
  description: string | ReactNode
  style?: Object
}

const HomeCreditPanel: FC<HomePanelProps> = ({ title, amount, description, style }) => {
  return (
    <div className="panel" style={style}>
      <div className='title'>
        { title }
      </div>
      <div className='amount'>
        {amount}
      </div>
      <div className='description'>
        {description}
      </div>
    </div>
  )
}

export default HomePanel

```
But the docs shows:
![image](https://user-images.githubusercontent.com/26177732/70228982-4cd55400-1790-11ea-8044-b03f417681e6.png)

**Comment by Zunaib** [comment]
I'm trying to make MDX work, not succeeded so far. Can you share your configuration files, i.e presets.js and webpack config ?
i'm using typescript too.

**Comment by Mu-xue** [comment]
> I'm trying to make MDX work, not succeeded so far. Can you share your configuration files, i.e presets.js and webpack config ?
> i'm using typescript too.

What's your error?

**Comment by Zunaib** [comment]
There is no error, it does compile.
But it misses out on the MDX files
<img width="644" alt="Capture__Github_storybook" src="https://user-images.githubusercontent.com/25710588/70239086-78563f80-178c-11ea-93b6-0949fee66d85.PNG">

**Comment by Zunaib** [comment]
Never mind, made it work like a charm.

**Comment by Zunaib** [comment]
You need to define, 
1. propTypes
2. default proptypes
in your HomePanel.tsx
Then it'll work.

**Comment by Zunaib** [comment]
HomePanel.propTypes = {
  title: PropTypes.string
};
HomePanel.defaultProps = {
  title: "Test
};

**Comment by shilman** [comment]
Did you configure `react-docgen-typescript-loader`? Or are you using CRA?

**Comment by Mu-xue** [comment]
It works when I add 'export':
```
- const HomeCreditPanel: FC<HomePanelProps> = ({ title, amount, description, style }) => {
+ export const HomeCreditPanel: FC<HomePanelProps> = ({ title, amount, description, style }) => {
```

I just saw it in [react-docgen-typescript-loader](https://github.com/strothj/react-docgen-typescript-loader)
![image](https://user-images.githubusercontent.com/26177732/70310380-7652b600-184a-11ea-9f82-abbd2d8ec6f1.png)

However, I am still unable to understand why...

**Comment by Zunaib** [comment]
Are you able to showcase prop descriptions ? 
Mind sharing your presets and config
