### ISSUE TITLE
VueJs Knobs with CSF format in docs

### ISSUE THREAD

**Issue by dotamir** [storybookjs/storybook#9078]
**Describe the bug**
I want to implement VueJs components with docs addons in CSF format. But I faced a issue and the problem is I don't know how to implement knobs in CFS format. Actually I'm doing it but when I want to change prop in knobs tab it doesn't change at all! I'll paste my code below.

**Expected behavior**
I expect props to change when I'm changing them in knobs tab.

**Screenshots**
Hard to explain it with screenshot.

**Code snippets**
I'm using this code:
```
export default {
  title: 'Buttons|Button',
  component: EcButton,
  includeStories: [],
};

export const types = () => ({
  components: { EcButton },
  template: `<main>
              <ec-button type="${text('Type', 'default')}">Primary</ec-button>
              <ec-button type="secondary">Secondary</ec-button>
              <ec-button type="danger">Danger</ec-button>
              <ec-button type="create">Create</ec-button>
              <ec-button type="vibrant">Vibrant</ec-button>
            </main>`,
});
```

**Additional context**
And also when I'm using `:type="${text('Type', 'default')}"` it doesn't show the anything in the story page
It's all alright with `storiesOf` API but it doesn't support `mdx` as well and I want to use CSF format.

What's the problem? Does is support VueJs as well as it does React?

Thanks in advance.

**Comment by shilman** [comment]
See here: https://github.com/storybookjs/storybook/blob/next/addons/knobs/README.md#with-vuejs

**Comment by dotamir** [comment]
@shilman Okay but I faced another issue. Since I'm using CSF with MDX stories. I have this:
```
export default {
  title: 'Buttons|Button',
  includeStories: [],
  decorators: [withKnobs]
};
```

and knobs doesn't work when I'm changing the value in knobs tab, and when I remove `includeStories: []`, knobs working well but docs page doesn't show MDX document anymore.

With `includeStories` docs looks like this (the exact thing that I want):
<img width="1052" alt="Screenshot 2019-12-06 at 9 26 36 PM" src="https://user-images.githubusercontent.com/16477296/70346827-7071ca80-1874-11ea-98d4-c66e0b619c5f.png">

Without that:
<img width="1052" alt="Screenshot 2019-12-06 at 10 03 52 PM" src="https://user-images.githubusercontent.com/16477296/70346847-7d8eb980-1874-11ea-9367-d8cf10d5625e.png">

How can I mix both of them together?

**Comment by dotamir** [comment]
@shilman Any comment?

**Comment by dotamir** [comment]
@shilman I'm still waiting for a response. I tried so many ways but it doesn't work!

**Comment by shilman** [comment]
AFAIK knobs work in the canvas view but not in docs. recently verified in the latest beta.

**Comment by uaalah** [comment]
Hi all!! 
@shilman ,  I think I have a problem similar to @dotamir . On the one hand I have the stories in CSF with knobs, and they work well. These stories are linked to an MDX that shows the stories with <Story id = "" />. The question is ... how can I pass the knobs by parameters to these stories? It's possible? 
I've been looking for information, but I haven't found it, and I don't know if it exists. I'm developing with Vuejs and storybook 5.3.0-beta.10.
Thanks for all

**Comment by uaalah** [comment]
Sorry, I just found https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/recipes.md#csf-stories-with-mdx-docs and https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/docspage.md#replacing-docspage.
I think the first one will be valid for me.
