### ISSUE TITLE
"Duplicate title" error with "CSF Stories with MDX Docs" example

### ISSUE THREAD

**Issue by schneidmaster** [storybookjs/storybook#9094]
**Describe the bug**

The [CSF Stories with MDX Docs](https://github.com/storybookjs/storybook/blob/v5.2.8/addons/docs/docs/recipes.md#csf-stories-with-mdx-docs) recipe produces an error:

```
Duplicate title 'Demo/Button' used in multiple files; use unique titles or combine 'Demo/Button' stories into a single file.
```

**To Reproduce**

Copy/paste the demo code into your Storybook project. Here is a repo with a simple reproduction: https://github.com/schneidmaster/storybook-error-demo

**Expected behavior**

The story renders correctly combining metadata from the `.stories.js` and `.stories.mdx` files.

**Screenshots**

<img width="1680" alt="error" src="https://user-images.githubusercontent.com/1896112/70378280-0e50ae00-18e4-11ea-8cc6-b16d0acdf558.png">

**Code snippets**

Reproduction repo:  https://github.com/schneidmaster/storybook-error-demo

**System:**

```
Environment Info:

  System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
  Binaries:
    Node: 8.15.1 - ~/.asdf/installs/nodejs/8.15.1/bin/node
    Yarn: 1.17.3 - ~/.asdf/installs/nodejs/8.15.1/.npm/bin/yarn
    npm: 6.4.1 - ~/.asdf/installs/nodejs/8.15.1/bin/npm
  Browsers:
    Chrome: 78.0.3904.108
    Firefox: 68.0.2
    Safari: 13.0.3
  npmPackages:
    @storybook/addon-docs: ^5.2.8 => 5.2.8
    @storybook/react: ^5.2.8 => 5.2.8
```

**Comment by atanasster** [comment]
@schneidmaster thanks for reporting this. 

afaics, this issue has already been addressed. Just in case, I tried your repo with `5.3.0-beta.18` and it worked as expected.

**Comment by schneidmaster** [comment]
Thanks! I'm also seeing it working with `5.3.0-beta.18`. Sorry if this was a duplicate, I searched but couldn't find any relevant issues logged.

**Comment by atanasster** [comment]
I also searched to use it as a reference, but didn't find. Anyway, I lets close this :)
