### ISSUE TITLE
@storybook/docs doesn't use the loaded compodoc .json file

### ISSUE THREAD

**Issue by Aaltuj** [storybookjs/storybook#9103]
**Describe the bug**
After following the https://github.com/storybookjs/storybook/tree/next/addons/docs/angular instructions. Storybook fails to show the component information in the Docs tab.

It loads the json file because setCompodocJson is called and that sets the global variable 
![image](https://user-images.githubusercontent.com/1876081/70438585-73e09e00-1a8e-11ea-893b-bfd0f80d54df.png)

But it isn't used when selecting the doc tab.

![image](https://user-images.githubusercontent.com/1876081/70438932-329cbe00-1a8f-11ea-8b2e-b2e81ddb485a.png)

Am i missing something?

**To Reproduce**
1. open / extract files
[cs-shared - Copy.zip](https://github.com/storybookjs/storybook/files/3939827/cs-shared.-.Copy.zip)
2. run `yarn install`
3. run `yarn storybook`

**Expected behavior**
That the generated compodoc information is used to show the compodoc generated props

**Comment by tommyc38** [comment]
I followed the docs as well and couldn't get it to work.  Please help.

**Comment by shilman** [comment]
In the attached ZIP file, it uses `.storybook/preset.js`, which is wrong. The file should be called `.storybook/presets.js`. Or, if you're using the new [declarative configuration](https://medium.com/storybookjs/declarative-storybook-configuration-49912f77b78), `.storybook/main.js`.

**Comment by tommyc38** [comment]
@shilman, I made the changes and still couldn't get it to work.  Do you know if there is a live example of Docs working with Angular anywhere?

**Comment by shilman** [comment]
@tommyc38 For sure!

Demo: https://storybookjs-next.now.sh/angular-cli/
Source: https://github.com/storybookjs/storybook/blob/next/examples/angular-cli/

**Comment by tommyc38** [comment]
@shilman thank you for your quick response.  My wife went into labor with our twins the minute you responded haha.  At any rate, I found the issue...I was using SBv5.3.6 which doesn't seem to support Docs just yet.  SBv5.3.5 works just as expected.  Thanks again!

**Comment by shilman** [comment]
Congratulations!!! 🎉 (on both fronts, but more on the twins -- that's amazing!!!)

**Comment by Steven-Harris** [comment]
@tommyc38  I reverted to 5.3.18 and I still can't get storybook to load my documentation.json file. I don't get any errors it just doesn't work. DocsPage works but only has the component in it, I can't customize it

**Comment by shilman** [comment]
@Steven-Harris do you have a public repro?

**Comment by Steven-Harris** [comment]
@shilman, sure thing! Here you go! [repo](https://github.com/Steven-Harris/storyboook-compodoc-issue)

**Comment by Steven-Harris** [comment]
should this issue be re-opened?

**Comment by sl-benjamindupuy** [comment]
I followed the docs as well and I have the exac same problem. "No Docs" but the global variable __STORYBOOK_COMPODOC_JSON__ is ok.
Any news ?
Thanks

**Comment by shilman** [comment]
@matheo any chance you can take a look at this?

**Comment by matheo** [comment]
Steve's repro is incomplete tho, the AppComponent stories.ts file just exports the CSF metadata and no story. The other stories are from `@storybook/angular/demo` components, and those doesn't have properties extracted by compodoc.

@sl-benjamindupuy we will need a repro with the configuration that you're using to see if there's a missing detail.

**Comment by Steven-Harris** [comment]
@matheo can you explain more? I followed the directions in the docs completely. And this is a clone of the demo provided by the examples that are supposed to work.

**Comment by matheo** [comment]
@Steven-Harris The demo is supposed to work inside Storybook, not inside another Angular project where compodoc doesn't know the Properties of the components.

Add a story to your AppComponent and you will be able to see the properties, check the differences between your app.component.stories.ts and the example files.

**Comment by Steven-Harris** [comment]
Getting a `Invalid compodoc JSON` now

**Comment by Steven-Harris** [comment]
got it working now

**Comment by Steven-Harris** [comment]
something in the docs about setting `component`  in the default object and the stories would have been helpful

**Comment by shilman** [comment]
@Steven-Harris it's there https://github.com/storybookjs/storybook/blob/next/addons/docs/angular/README.md#props-tables
