### ISSUE TITLE
Update docs when props vary by || (OR)

### ISSUE THREAD

**Issue by sushmithaGayam** [storybookjs/storybook#9108]
**Is your feature request related to a problem? Please describe.**
I have a Typescript react component whose props vary between two interfaces. I currently have an issue with the documentation of props. storybookis not able to recognize || (OR) operator.
interface A {
}
interfact B {
}
type ComponentProps = A || B

_TSX file:_
export default class SampleComponent extends React.Component<ComponentProps> {
}

_stories.mdx_
<Props of={SampleComponent }></Props>
This should show two tables seperated indicating the props can vary beween A or B

**Describe the solution you'd like**
I would want storybook to recognize or when displaying the prop documentationh.

**Describe alternatives you've considered**
An alternative option right now is do a manual documentation.

**Are you able to assist bring the feature to reality?**
**no** | yes, I can...

**Additional context**

**Comment by shilman** [comment]
cc @atanasster related to https://github.com/storybookjs/storybook/issues/7943

**Comment by atanasster** [comment]
This is an issue with `react-docgen-typescript` - probably best to follow it there: 

https://github.com/styleguidist/react-docgen-typescript/issues/57
