### ISSUE TITLE
propTypes not informing description

### ISSUE THREAD

**Issue by dvnrsn** [storybookjs/storybook#9120]
**Describe the bug**
Probably not a bug, but I can't figure out [docspage](https://github.com/storybookjs/storybook/blob/master/addons/docs/docs/docspage.md) esp in regards to slot proptypes informing `description` and 

**To Reproduce**
```js
/**
 * some cool docs
 */

export const Button = (props) => {
  return <Cb {...props} />
}
Button.propTypes = {
  actionType: PropTypes.oneOf(['positive', 'negative', 'neutral', 'error', 'warning']),
};
```

**Expected behavior**
Something like this 
![image](https://user-images.githubusercontent.com/9112811/70565020-7d313f80-1b4e-11ea-8ead-a35114026ab0.png)

**Actual**
![image](https://user-images.githubusercontent.com/9112811/70565338-1ceecd80-1b4f-11ea-8c4b-968e56db97c9.png)

**Comment by shilman** [comment]
If you're using CRA, you should use the preset https://github.com/storybookjs/presets/tree/master/packages/preset-create-react-app

However, there is a known bug when using it with versions > 5.3.0-beta.15 that's in progress now: https://github.com/storybookjs/presets/issues/71

**Comment by ryanboswell** [comment]
For what it's worth, I'm seeing more or less the same issue with my component and I'm definitely not using CRA, so unsure if that bug would affect my use-case.

This is what I end up with:

```
const Button = (props) => {
};

Button.propTypes = {
  /**
   * Whether or not to center the button.
   */
  centerAlign: PropTypes.bool,
  /**
   * The color theme to apply to the button.
   */
  color: PropTypes.oneOf([...buttonColors, ...brandColors]),
  /**
   * Classes to apply to the column element to adjust it's responsive width.
   */
  columnClasses: PropTypes.string,
  /**
   * The classes to apply to the outer grid element.
   */
  gridClass: PropTypes.string,
  /**
   * The text the button should display.
   */
  text: PropTypes.string,
  /**
   * The URL the button should link to.
   */
  url: PropTypes.string,
  /**
   * Whether or not the button's link should open in a new tab.
   */
  urlOpenNewTab: PropTypes.bool,
  /**
   * The button variant to use.
   */
  variant: PropTypes.oneOf(variants),
};

Button.defaultProps = {
  centerAlign: true,
  color: 'upgrade',
  columnClasses: '',
  gridClass: '',
  text: '',
  url: '',
  urlOpenNewTab: false,
  variant: 'solid',
};
```

**Comment by shilman** [comment]
@ryanboswell can you use `--debug-webpack` in your project to verify that the `babel-plugin-react-docgen` is running on your components?

**Comment by robborrego** [comment]
I'm experiencing the same issue as @ryanboswell and when I use `--debug-webpack` I see that docgen should be running on all my .jsx components.

**Comment by ryanboswell** [comment]
Took me a bit, but I did eventually figure out how to get `react-docgen` running on the project by adding it to our custom `babelrc` file.

**Comment by dvnrsn** [comment]
I am not using CRA. Curious what exactly you changed @ryanboswell. Was it something like: 

```js
{
  "plugins": ["react-docgen"]
}
```

**Comment by ryanboswell** [comment]
@dvnrsn Yeah, that was the trick. For us, we have a bunch of different environment specific config in `.babelrc`, so it took some trial an error to get it into the right one for Storybook (and avoid having it in `prod` config).

If anyone else has the same question, it's the `development` config env as far as babel is concerned when you're running from `npm run storybook`.

**Comment by dvnrsn** [comment]
Alright, now I'm able to invest more fully in this. There seem to have been a few significant updates to storybook so I've updated and moved to `main.js` config. Here are the [steps](https://github.com/storybookjs/storybook/tree/master/addons/docs#installation) I've taken to get addon-docs working: 

```
yarn add -D @storybook/addon-docs
yarn add -D react react-is babel-loader
````
Add the following to main.js
```
module.exports = {
  stories: ['../src/**/*.stories.js'],
  addons: ['@storybook/addon-actions', '@storybook/addon-links', '@storybook/addon-docs'],
```
After completion, I get the docs tab, but only the component title and the exported component is showing. 

![image](https://user-images.githubusercontent.com/9112811/73692950-92c86e80-4692-11ea-86a0-0a8d3af5bf60.png)

Now, none of my slots are filling...

**Comment by dvnrsn** [comment]
Installing `babel-plugin-react-docgen and including in .babelrc seems to have solved for me. Submitted PR for docs

**Comment by dvnrsn** [comment]
Just realized I'm back at square 0. Unable to get the Description to populate...weird because the `react-docgen` does get everything else to work..
```js
Button.propTypes = {actionType: PropTypes.oneOf(['a', 'b'])}
Button.defaultProps = {
  className: 'coolDefault',
}
```
![image](https://user-images.githubusercontent.com/9112811/73699683-b0e99b00-46a1-11ea-886a-a8e3661f1974.png)

**Comment by dvnrsn** [comment]
Well, this is awkward. It turns out it was failing because there was a misalignment between `Component.proptypes` and `Component.defaultProps`. I had one extra attribute in the former. Why this mattered, I'm not sure, but it works if I have matching properties.

**Comment by shilman** [comment]
@dvnrsn Pretty interesting. There are a million "props table" issues and we'll be doing a major cleanup as part of 6.0. Knowing about little gotcha's like this is incredibly helpful. Thanks a bunch!! 💯

**Comment by dvnrsn** [comment]
Was revisiting this problem with storybook v6 and here are the docs that helped me get up and going again https://github.com/storybookjs/babel-plugin-react-docgen
