### ISSUE TITLE
unable to run static storybook build after npm run build-storybook

### ISSUE THREAD

**Issue by bigtone1284** [storybookjs/storybook#9121]
**Describe the bug**
Following the steps here:
https://storybook.js.org/docs/basics/exporting-storybook/

After running `npm run build-storybook`, when I try to run the static build locally via `npx http-server .out`, I get this error in the browser:

`Uncaught Error: Accessing non-existent addons channel, see https://storybook.js.org/basics/faq/#why-is-there-no-addons-channel`

I followed the FAQs link on this topic and found that the suggested solutions did help or were not relevant for my case.

`npm run start-storybook` works.

**Expected behavior**
The static build should be able to be run locally.

**Screenshots**
<img width="1613" alt="Screen Shot 2019-12-09 at 5 42 48 PM" src="https://user-images.githubusercontent.com/7755586/70571142-16ae2080-1b52-11ea-8101-4c267408697e.png">

**System:**
Environment Info:

  System:
    OS: macOS Mojave 10.14.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Binaries:
    Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
  Browsers:
    Chrome: 78.0.3904.108
    Firefox: 69.0.1
    Safari: 13.0.3
  npmPackages:
    @storybook/addon-a11y: ^5.2.4 => 5.2.8
    @storybook/addon-actions: ^5.2.4 => 5.2.8
    @storybook/addon-knobs: ^5.2.4 => 5.2.8
    @storybook/addon-links: ^5.2.4 => 5.2.8
    @storybook/addon-viewport: ^5.2.4 => 5.2.8
    @storybook/cli: ^5.2.4 => 5.2.8
    @storybook/react: ^5.2.4 => 5.2.8
    @storybook/theming: ^5.2.4 => 5.2.8

**Comment by shilman** [comment]
I'm not able to repro. Can you share a reproduction repo?

**Comment by bigtone1284** [comment]
So I actually fixed this and found that we were not including all the needing dependencies in our devDependencies...

@shilman for easier debugging, is there a way to run `npm run build-storybook` (building the static build of storybook) with a sourcemap?

**Comment by shilman** [comment]
Maybe try `NODE_ENV=development`?

**Comment by eugercek** [comment]
I have the same issue.
```
"@storybook/addon-actions": "^6.5.13",
"@storybook/addon-docs": "^6.5.13",
"@storybook/addon-links": "^6.5.13",
"@storybook/addons": "^6.5.13",
"@storybook/react": "^6.5.13",
 ```
