### ISSUE TITLE
@storybook/addon-notes missing typings for addonNotesTheme

### ISSUE THREAD

**Issue by jcfranco** [storybookjs/storybook#9124]
**Describe the bug**
Using `@storybook/addon-notes`, TS complains about the `addonNotesTheme` prop in my theme file:

  ```ts
// theme.ts
  export default create({
    base: "light",
    brandTitle: "Title",
    brandUrl: "./",
    brandImage: logo,

    // TS error 👇
    addonNotesTheme: {
      code: {
        whiteSpace: "normal !important"
      }
    }
  });
  ```

One solution would be to use interface merging within this addon and extend `ThemeVars` to include `addonNotesTheme`. For now, I can workaround this with the following:

  ```ts
  // theme.ts
  import { ThemeVars, create } from "@storybook/theming";

  export default create({
    base: "light",
    brandTitle: "Title",
    brandUrl: "./",
    brandImage: logo,

    addonNotesTheme: {
      code: {
        whiteSpace: "normal !important"
      }
    }

    // have to assert type this way for now
  } as ThemeVars & { addonNotesTheme: any });
  ```

**Comment by shilman** [comment]
FYI, please take a look at Storybook Docs, which is intended to replace `addon-info` and `addon-notes`, may not have this problem, and is being more actively maintained: https://medium.com/storybookjs/storybook-docspage-e185bc3622bf

**Comment by jcfranco** [comment]
I'll take a look. Thanks!
