### ISSUE TITLE
Addon-docs: Using PropTypes.oneOfType([typeX, typeY]) renders "Union<typeX || typeY>

### ISSUE THREAD

**Issue by aguelo** [storybookjs/storybook#9126]
**Describe the bug**
When PropTypes' `oneOfType()`-method is used, the prop-table in the DocsPage-tab renders a `Union<` before the props, and a `>`.

**To Reproduce**
1. Go to a story (CSF or MDX) that have a PropTypes-declaration using `oneOfType([...])`.
2. Scroll down to and check the Props-table for that story.
4. Check out the above mentioned prop in the table. You should see the strings `Union<` ... `>`

**Expected behavior**
I expect the `Union<` and `>` not to be there

**Screenshots**
![image](https://user-images.githubusercontent.com/10112513/70610622-30a83b80-1c04-11ea-9df6-e339f896f69e.png)

**Code snippets**
```
Button.propTypes = {
  as: PropTypes.oneOfType([
    PropTypes.element,
    PropTypes.node,
    PropTypes.func,
    PropTypes.object,
  ])
}
```
**System:**
```
System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
    Yarn: 1.21.0 - ~/.yarn/bin/yarn
    npm: 6.12.1 - ~/.nvm/versions/node/v12.13.1/bin/npm
  Browsers:
    Chrome: 78.0.3904.108
    Safari: 12.1.2
```

**Comment by shilman** [comment]
Please check out 5.3-beta. This has been completely upgraded!

**Comment by aguelo** [comment]
> Please check out 5.3-beta. This has been completely upgraded and we are closing in on a release.

Ah okay! I actually tested that before posting this issue, but for me the props-table doesn't show up at all with the latest 5.3.0-beta.21... Do I have to add something specific in order to make it work in 5.3? 

I've tried both CSF and the `<Props of={Button} />` in MDX.

**Comment by shilman** [comment]
Try `5.3.0-beta.15`? And if you're using CRA, use the standalone preset https://www.npmjs.com/package/@storybook/preset-create-react-app
