### ISSUE TITLE
addon-knobs causing component re-render, cannot test transitions

### ISSUE THREAD

**Issue by pitops** [storybookjs/storybook#9128]
This is a followup to this thread here that the stale bot closed (i hate these bots).

https://github.com/storybookjs/storybook/issues/6705

The problem still happens. The usecase is a modal. If I close the modal instead of triggering a transition, the knob reloads the component

**Comment by shilman** [comment]
Yo-ho-ho!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-alpha.18 containing PR #9447 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.
