### ISSUE TITLE
Storybook cannot update the code of node_modules in real time

### ISSUE THREAD

**Issue by gyh9457** [storybookjs/storybook#9134]
**Describe the bug**
Storybook cannot update the code of node_modules in real time. 
When I modify the code in node_modules for debugging, I must restart the service to see the effect. 
I hope to be able to update in real time for debugging.

**To Reproduce**
Use storybook in react project, modify the code in node_modules for debugging

**Expected behavior**
Hope to update the code in node_modules in real time for debugging

**System:**
win10
@storybook/cli@5.2.6

**Comment by michaelknoch** [comment]
did you find a workaround @gyh9457
