### ISSUE TITLE
Sass import not working

### ISSUE THREAD

**Issue by pistacchio** [storybookjs/storybook#9139]
**Describe the bug**
I setup Storybook on an ejected CRA application. Everything seems to compile correctly (no errors or warnings) and the app itself works correctly. I can also see all the stories that I have declared.

The only problem is that when within a story I import a SASS stylesheet, it returns en empty dictionary and hence no style is applied to any component Storybook. The styles are loaded and applied correctly in the app itself.

**Code snippets**
Example of non working story and component:

```js
import React from 'react';
import classnames from 'classnames';

import style from './loader.scss';

const Loader = ({className, ...otherProps}) => {
  console.log(style);

  return (
    <div className={classnames(style.loader, className)} {...otherProps}>
      <div className={style.container}>
        <div className={classnames(style.bar, style.bar1)}/>
        <div className={classnames(style.bar, style.bar2)}/>
        <div className={classnames(style.bar, style.bar3)}/>
      </div>
    </div>
  );
};

export { Loader };
```

```js
import React from 'react';

import { Loader } from './loader';

const elementStyle = {
  width: '300px',
};

export default {title: 'Ui/Loader'};

export const simple = () => (
  <Loader
    style={elementStyle}>
  </Loader>
);
```

I didn't declare a custom `webpack.config.js` thought I tried extending the config module rules to force sass.

`.storybook/addons.js`:
```js
import '@storybook/addon-knobs/register'
import '@storybook/addon-actions/register';
import '@storybook/addon-viewport/register'
import '@storybook/addon-backgrounds/register';
import 'storybook-addon-intl/register';
```

`.storybook/config.js`:
```js
import { configure } from '@storybook/react';

// automatically import all files ending in *.stories.js
configure(require.context('../src', true, /\.story\.jsx?$/), module);
```

`.storybook/presets.js`:
```js
module.exports = ['@storybook/preset-create-react-app'];
```

Did I configured something wrong?

**Comment by shilman** [comment]
@pistacchio take a look at preset-scss: https://www.npmjs.com/package/@storybook/preset-scss

**Comment by kaleem-elahi** [comment]
Need this resolved, getting same issue :(

**Comment by teo-garcia** [comment]
I realized that you don't need this preset if you're using `@storybook/preset-create-react-app`, to import your global styles just place this import in the `preview.js` file:

```js
import '!style-loader!css-loader!sass-loader!../src/pathToYourGlobalStyles/file.scss';
```
