### ISSUE TITLE
[Question: Knobs] Examples for html

### ISSUE THREAD

**Issue by jmacaluso711** [storybookjs/storybook#9145]
**Is your feature request related to a problem? Please describe.**
Wondering if there are any example setups for knobs using `@storybook/html`. I only see documentation for React, Angular and Vue. Is it possible to add knobs to the html implementation, for example, a knob that changes the class name.

**Describe the solution you'd like**
Here is my current setup for reference. Not sure where to go from here.
```
import { storiesOf } from '@storybook/html';
import { withKnobs, text, boolean, select } from '@storybook/addon-knobs';
const stories = storiesOf('Storybook Knobs', module);

export default { title: 'Button' };

stories.addDecorator(withKnobs);

const label = 'Button';
const options = {
  Primary: 'btn-primary',
  Secondary: 'btn-secondary',
  Tertiary: 'btn-tertiary',
};
const defaultValue = 'Primary';
const value = text(label, defaultValue, groupId);
const selectButtonType = select(label, options, defaultValue, groupId);

stories.add('primary', () => (
  `<button class="btn-primary" type="button" id="primary-action-two">${value}</button>`
));
```

**Comment by shilman** [comment]
Check this out: https://github.com/storybookjs/storybook/blob/next/examples/html-kitchen-sink/stories/addon-knobs.stories.js
