### ISSUE TITLE
Using Storybook with MobX and CRA

### ISSUE THREAD

**Issue by SaadRegal** [storybookjs/storybook#9162]
I'm having trouble running Storybook with MobX, i'm using create-react-app with  react-app-rewired.

Here's my babel configuration in **package.json**

```
    "plugins": [
      [
        "@babel/plugin-proposal-decorators",
        {
          "legacy": true
        }
      ]
    ],
```

Storybook config **.storybook/config.js** 

```
import { configure } from '@storybook/react';

configure(require.context('../src', true, /\.stories\.js$/), module);
```

react-app-rewire configuration **config-overrides.js**
```
const {
    override,
    disableEsLint,
    addDecoratorsLegacy,
    fixBabelImports,
} = require("customize-cra");
module.exports = override(
    disableEsLint(),
    addDecoratorsLegacy(),
    fixBabelImports("react-app-rewire-mobx", {
        libraryDirectory: "",
        camel2DashComponentName: false
    }),
);
```
I get the following error when i run `yarn run storybook` :

> ...src\store\KeyframesStore.js: Support for the experimental syntax 'decorators-legacy' isn't currently enabled (6:5):

![image](https://user-images.githubusercontent.com/12308809/70908279-1ce94480-200b-11ea-8d7e-e83aa2c1a0e9.png)

The app works fine with current config, is there any missing configuration for storybook ?

**Comment by shilman** [comment]
You need to use the standalone preset `@storybook/preset-create-react-app` (if you're not already) and configure it to use `react-app-rewired`.

**Comment by zhigang1992** [comment]
sry, how to do that?

Setting `scriptsPackageName` to `react-app-rewired` doesn't seems to work.


@shilman

**Comment by roman-balzer** [comment]
Using `path.resolve` works for me

```
const path = require("path");

module.exports = {
  stories: ['../src/**/*.stories.(js|jsx|ts|tsx|mdx)'],
  addons: [
    '@storybook/addon-actions',
    '@storybook/addon-knobs',
    '@storybook/addon-viewport',
    '@storybook/addon-backgrounds',
    '@storybook/addon-a11y',
    {
      name: '@storybook/preset-create-react-app',
      options: {
        tsDocgenLoaderOptions: {},
        scriptsPackageName: path.resolve("../node_modules/react-app-rewired"),
      },
    },
    {
      name: '@storybook/addon-docs',
      options: { configureJSX: true },
    },
  ],
}
```

**Comment by shilman** [comment]
cc @mrmckeb

**Comment by mrmckeb** [comment]
@SaadRegal, this is not officially supported by CRA, and we do a best-effort to support customisations like the one you're using. 

The `scriptsPackageName` is for forks of `react-scripts`. Unfortunately, `react-app-rewired` is not compatible with this approach.

Are you able to supply a reproducible demo for me to take a look at?

Also, have you tried adding a `.babelrc` to your Storybook directory with the config you need?

**Comment by mrmckeb** [comment]
Also, as we don't support `react-app-rewired` or `customize-cra` (and others) directly, files like `config-overrides.js` won't work.

If you need something more than Babel plugins (again, `.babelrc` should work fine), you can intercept the Webpack config yourself. You can find out more about this feature here:
https://storybook.js.org/docs/configurations/custom-webpack-config/

**Comment by shilman** [comment]
@mrmckeb That doesn't answer the question about what might have broken:

<img width="691" alt="_support_-_Discord" src="https://user-images.githubusercontent.com/488689/72274478-3c55aa80-3667-11ea-92eb-204b90941a5a.png">

I think getting a CRA fork working and the mobx/decorator thing are actually two separate issues.

**Comment by SaadRegal** [comment]
> @SaadRegal, this is not officially supported by CRA, and we do a best-effort to support customisations like the one you're using. I think we'll be able to find a fix in this case ;)
> 
> The `scriptsPackageName` is for forks of `react-scripts`. Unfortunately, `react-app-rewired` is not compatible with this approach.
> 
> Are you able to supply a reproducible demo for me to take a look at?
> 
> Also, have you tried adding a `.babelrc` to your Storybook directory with the config you need?
@mrmckeb 
i tried adding babel.rc under .storybook/ didn't work, Here's a demo of the error :

https://gitlab.com/saadregal/mobx-sb-error-demo

**Comment by mrmckeb** [comment]
I'm working on this and will test against your repo ASAP :)

**Comment by mrmckeb** [comment]
Hi @SaadRegal, I can confirm this work fine with `@storybook/preset-create-react-app`.

All I did was add a `main.js` with:
```js
module.exports = {
  addons: ["@storybook/preset-create-react-app"]
};
```

I then saw another error, which was related to an import of a non-existent file (a `jpg`). I removed that, and everything worked as expected.

Let me know how you go with this :)

**Comment by SaadRegal** [comment]
> Hi @SaadRegal, I can confirm this work fine with `@storybook/preset-create-react-app`.
> 
> All I did was add a `main.js` with:
> 
> ```js
> module.exports = {
>   addons: ["@storybook/preset-create-react-app"]
> };
> ```
> 
> I then saw another error, which was related to an import of a non-existent file (a `jpg`). I removed that, and everything worked as expected.
> 
> Let me know how you go with this :)

Yes, adding that to `.storybook/main.js ` solved it. Thanks !

**Comment by AkhmedovValikhan** [comment]
having the same issue with unejected CRA, 
`SyntaxError: /Users/valikhan.akhmedov/Documents...: Decorators are not enabled.
If you are using ["@babel/plugin-proposal-decorators", { "legacy": true }], make sure it comes *before* "@babel/plugin-proposal-class-properties" and enable loose mode, like so:`

**Comment by AkhmedovValikhan** [comment]
What has worked for me, is removing new separate "preset-create-react-app" and rely on old built-in one, althought I am getting deprication warnings it compiles everything without decorator errors

**Comment by shilman** [comment]
cc @mrmckeb

**Comment by mrmckeb** [comment]
@AkhmedovValikhan are you able to provide any more information? Do you have a babel config anywhere in that project?

**Comment by richardwardza** [comment]
I had the same that I managed to solve with https://github.com/storybookjs/storybook/issues/6069#issuecomment-617208417
