### ISSUE TITLE
Decorator execution order

### ISSUE THREAD

**Issue by Vanuan** [storybookjs/storybook#9163]
**Is your feature request related to a problem? Please describe.**

Global and local decorators are applied in a determined order, no matter which order you add them. Local decorators are applied first, global decorators are applied last.

**Describe the solution you'd like**
Maybe there's a way to apply global decorators for each story before `.addDecorator` is applied.
That is, some internal global decorator:
```
addDecorator(myDecorator, { internal: true })
```
So that internal decorator is applied first, then the local decorator is applied, and the global decorator is applied last.

**Describe alternatives you've considered**
I've tried changing order:
```
addDecorator(globalDecorator);
storiesOf().addDecorator(localDecorator);
addDecorator(internalDecorator);
```
But it has no effect.

**Are you able to assist bring the feature to reality?**
no, unfortunately, I'm not familiar with the storybook codebase yet. Maybe, there's a simpler way?

**Additional context**
Expected behavior:

```
<globalDecorator>
  <localDecorator>
    <internalDecoratory>
      <story />
    <interalDecorator>
  </localDecorator>
</globalDecorator>
```

**Comment by LeeBurton** [comment]
I am having exactly this issue too. For instance, I am loading source code for the stories using the "addon-storysource" addon, and trying to overwrite it for some stories using "withSource(source)". The withSource content is being overwritten by the code loaded by the loader. For this use case, it would also be resolved by being able to execute the local decorators first.

Or should this not be the preferable execution order anyway - to execute the loader decorators first, then allow the user to override them with the story global decorators, and then local story-specific decorators?

@shilman

**Comment by shilman** [comment]
@LeeBurton if you're using MDX, this might help https://github.com/storybookjs/storybook/issues/7479#issuecomment-575309548

**Comment by LeeBurton** [comment]
@shilman Thanks for the swift response.

We are not currently using MDX and don’t have a lot of time right now to refactor everything. How could this be resolved without MDX?

**Comment by shilman** [comment]
@LeeBurton MDX support became official in 5.3. Updating the documentation now:

https://medium.com/storybookjs/rich-docs-with-storybook-mdx-61bc145ae7bc

**Comment by LeeBurton** [comment]
Thanks. That may help us. We are currently looking into using MDX and seeing if we can get it working. Hopefully, that’ll make things somewhat easier :-)
