### ISSUE TITLE
[Security] Vulnerability of medium severity disclosed in transitive dependencies

### ISSUE THREAD

**Issue by DanHatesNumbers** [storybookjs/storybook#9173]
### Bug or support request summary

On December 10th 2019, a Cross-site Scripting vulnerability was disclosed in the Serialize-javascript package in versions below 2.1.1.

Storybook transitively depends on vulnerable versions of this package through the following paths:

@storybook/react > @storybook/core > corejs-upgrade-webpack-plugin > webpack >  terser-webpack-plugin > serialize-javascript

@storybook/react > @storybook/core > webpack > terser-webpack-plugin > serialize-javascript

@storybook/react > webpack > terser-webpack-plugin > serialize-javascript

@storybook/react > @storybook/core > terser-webpack-plugin > serialize-javascript

### Please specify which version of Storybook and optionally any affected addons that you're running

- "@storybook/react": "^5.1.9"

However, this was last updated to 5.2.6. I've confirmed that as of 9e66d9f26c49fee2a2c527775be5e638ff011b5d these vulnerabilities are still present in Storybook according to yarn audit.

### Affected platforms 

- _If UI related, please indicate browser, OS, and version_
- _If dependency related, please include relevant version numbers_
- _If developer tooling related, please include the platform information_

### Screenshots / Screencast / Code Snippets (Optional)

```js
// code here
```
End bug report support request - delete the rest below

**Comment by mattmoreira** [comment]
@shilman, can we get an update on this, please? Is someone available to pick this up? We're also dependant on this fix.

Maybe we can help with that?

**Comment by shilman** [comment]
Would love help with this @mattmoreira ! PR's welcome -- let me know how I can help

**Comment by mattmoreira** [comment]
@shilman, as this was solved by #10071, can we close it?

**Comment by shilman** [comment]
thanks @mattmoreira !
