### ISSUE TITLE
Toggle default parameter options per story in CSF format

### ISSUE THREAD

**Issue by tleite** [storybookjs/storybook#9175]
I would like to be able to change the default parameter options of a story on a named export level. (it has to be in CSF format)

For example, I have a button story, one export shows the documentation, the other export shows the example. On the documentation, I would like to set showPanel = false and in the example set it to **true**

pseudo code below:

export default {
  title: 'Button', 
  parameters: { options: {showPanel: true}}
}; 
export const Documentation = () => <>    
{default.parameters.options.showPanel = false}
</>;

export const Example = () => <>    
{default.parameters.options.showPanel = true}
</>;

Is this currently possible?

**Comment by shilman** [comment]
Parameters are hierarchical, so here's how that would work:

```js
export default {
  title: 'Button',
  parameters: { foo: 'bar' } // by default all stories in this file get this
}

export const A = () => ... // foo = 'bar'

export const B = () => ...
B.story = {
  parameters: { foo: 'baz' } // overrides the default
}

**Comment by tleite** [comment]
This does not work for me...
Is there any example that you are aware, in which we can show/hide panel per export (not per story)?

**Comment by shilman** [comment]
@tleite This doesn't work?

```js
export default {
  title: 'Button',
  parameters: { options: {showPanel: true}}
};

export const Documentation = () => <>Foo</>;
Documentation.story = {
  parameters: { options: {showPanel: false}}
}
```
