### ISSUE TITLE
Provide way to make Docs default tab

### ISSUE THREAD

**Issue by wbobeirne** [storybookjs/storybook#9178]
**Is your feature request related to a problem? Please describe.**

Forgive me if this has been covered before, I searched around but couldn't find it. I intend to make Docs the primary way to browse my storybook, so I'd like a way to make it the default tab when you land on the storybook. As far as I can tell, it will always default to Canvas.

**Describe the solution you'd like**

Some kind of flag in `presets.js` to make it replace Canvas as the default tab

**Comment by shilman** [comment]
Closing this as dupe to #7066

**Comment by openscript** [comment]
It seems to be possible now. See #12111
