### ISSUE TITLE
Hide Default Props from Source Output

### ISSUE THREAD

**Issue by igloude** [storybookjs/storybook#9186]
Our team is super happy with Storybook so far! But in `@storybook/addon-info` we'd love the ability to hide default props from the source output.

Take this source code as an example:
```jsx
const Button = () => {
  const getClasses = () => {
    const { className, large } = props;
    const classList = ['button'];
    if (large) classList.push('-large');
    if (className) classList.push(className);
    return classList.join(' ');
  };

  return (
    <button
      className={getClasses()}
      disabled={props.disabled}
    >
      {props.text}
    </button>
  )
}

Button.propTypes = {
  /** toggles large button */
  large: PropTypes.bool,
  /** button text */
  text: PropTypes.string.isRequired,
  /** sets button theme */
  theme: PropTypes.oneOf([
    'primary',
    'secondary',
    'transparent',
  ]),
};

Button.defaultProps = {
  large: null,
  theme: 'primary',
};

export default Button;
```
A story of `<Button text="Hello Button" />` would give us a source output of:

```jsx
<Button
  large={null}
  text="Hello Button"
  theme="primary"
/>
```

We'd love a way to exclude those default props from the source output and just see:
```jsx
<Button text="Hello Button" />
```

**Comment by laij84** [comment]
I just upgraded from Addon-info 5.1.9 to 5.2.8 and am also seeing this issue. Previously the defaultProps did not display in the story source. This is confusing for developers looking at storybook documentation to understand the implementation of a component.

**Comment by shilman** [comment]
`Addon-info` is being superceded by `addon-docs`, which fixes a bunch of bugs and is easier to maintain. Please give it a try! https://medium.com/storybookjs/storybook-docspage-e185bc3622bf

**Comment by igloude** [comment]
Oh wow, `addon-docs` is exactly what I'm looking for. Thank you!
