### ISSUE TITLE
Storybook not picking up .mdx stories

### ISSUE THREAD

**Issue by dfnjy** [storybookjs/storybook#9189]
**Describe the bug**
I tried a fresh storybook setup using steps described in https://docs.google.com/document/d/1un6YX7xDKEKl5-MVb-egnOYN8dynb5Hf7mq0hipk8JE/edit

Basically just:

npx -p @storybook/cli@next sb init

then:
yarn add -D @storybook/addon-docs@next

And configure docs addon in main.js:
```
module.exports = {
  stories: ['../stories/**/*.stories.js'],
  addons: ['@storybook/addon-actions/register', '@storybook/addon-links/register'],
  presets: [
    {
      name: "@storybook/addon-docs/react/preset",
      options: {
        configureJSX: true
      }
    }
  ]
};
```

And created a button.stories.mdx file under stories folder. However after I run storybook I cannot find the newly added mdx stories anywhere.
And this file is being picked up by webpack because everytime I change this mdx file it will re render.
The version being picked up is 5.3.0-beta.31.

Anyone could help me? Thanks!

**Comment by shilman** [comment]
From the package README:

> Then add the following to your .storybook/main.js:

```js
module.exports = {
  presets: ['@storybook/addon-docs/preset'],
  stories: ['../src/**/*.stories.(js|mdx)'],
};
```

**Comment by dfnjy** [comment]
Thanks! That's the part I was missing. Looks like that hint only exits in npm page but not in github https://github.com/storybookjs/storybook/tree/master/addons/docs

**Comment by shilman** [comment]
@dfnjy If you're using that config method, you should be look at the docs on `next`! 👍
