### ISSUE TITLE
Addon-docs: MDX classes have precedence over custom user classes

### ISSUE THREAD

**Issue by patricklafrance** [storybookjs/storybook#9190]
**Is your feature request related to a problem? Please describe.**
CSS classes added by MDX have precedence over the custom classes added by the user.

You can see it in action in the following screenshot. Same code rendered twiced. The first box is in a story, the second is not.

![image](https://user-images.githubusercontent.com/794579/71126195-8bb6d100-21b6-11ea-8d4f-d0795c2e70b9.png)

**Describe the solution you'd like**
It would be nice if we could import a block like `<ResetStyles>` and paste inside code that shouldn't be affected by MDX default styles.

**Comment by shilman** [comment]
@patricklafrance is this still a problem?

**Comment by patricklafrance** [comment]
@shilman yes!

In my SB I overcame this by repeating all my selectors 4 times. That's more a hack than a solution though.

**Comment by konsalex** [comment]
Still an issue for me too. I use Storybook in conjunction with TailwindCSS.

**Comment by Benoye** [comment]
Still an issue for me, I use Chakra.
