### ISSUE TITLE
Error: Illegal mix of CSF default export and storiesOf calls in a single file

### ISSUE THREAD

**Issue by EgoziE** [storybookjs/storybook#9196]
**Describe the bug**
I'm getting an error:
`Illegal mix of CSF default export and storiesOf calls in a single file: /node_modules/wix-storybook-utils/dist/src/Story/index.js`
What causes this?
What am I doing wrong?

**Expected behavior**
I guess.. no error :P

**Screenshots**
![image](https://user-images.githubusercontent.com/35173937/71164079-03d4d380-2257-11ea-9c74-d2427217b70d.png)

**Code snippets**
I load stories like that:
```
require('../src/s1/docs/index.story');
require('../src/s2/docs/index.story');
require('../src/s3/docs/index.story');
require('../src/s4/docs/index.story');
...
```

My story file looks like:
```
export default ({ _config, _metadata, ...storyConfig }) =>
  _config
    .storiesOf(storyConfig.category, module)
    .add(storyConfig.storyName || _metadata.displayName, () => { ... }
```

**Environment Info:**
```
  System:
    OS: macOS 10.15.2
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 12.13.1 - /usr/local/bin/node
    npm: 6.12.1 - /usr/local/bin/npm
  Browsers:
    Firefox: 71.0
    Safari: 13.0.4
  npmPackages:
    @storybook/addon-google-analytics: ^5.1.0 => 5.2.8 
    @storybook/addon-links: ^5.1.0 => 5.2.8 
    @storybook/addon-options: ^5.1.0 => 5.2.8 
    @storybook/react: ^5.1.0 => 5.2.8 
```

**Additional context**
Everything works regardless the exception :)

**Comment by shilman** [comment]
In Storybook 5.2 and above, Storybook can load both `storiesOf` and `CSF` stories. [More info on CSF](https://medium.com/storybookjs/component-story-format-66f4c32366df).

It the `default` export to denote a CSF file. So in this case, it thinks your `storiesOf` file is CSF that also contains `storiesOf`, which is not allowed.

As a workaround, you can use a named export.

**Comment by EgoziE** [comment]
Thanks for the comment, I'll give it a try.
Just a question, will Storybook ever support this "mix" of loading stories both ways?
(Sometimes we prefer not to touch legacy code...)

**Comment by shilman** [comment]
@EgoziE Storybook fully supports a mix of `storiesOf` and `CSF`, as long as they are in different files. I don't foresee supporting both in a single file, but could be convinced if there was a compelling use case.
