### ISSUE TITLE
AddonDocs - Iframe background and font-color same color.

### ISSUE THREAD

**Issue by Highklaas** [storybookjs/storybook#9197]
**Describe the bug**

The background aswell as the object properties in the iframe are black. Which leads to the properties beeing only visible on selected text.

**Screenshots**

![Bildschirmfoto 2019-12-19 um 13 46 24](https://user-images.githubusercontent.com/8190490/71174860-77321180-2266-11ea-98c7-f5b844a7bbe4.png)

**Comment by shilman** [comment]
@Highklaas i haven't seen this before. do you have a repro repo you can share?
