### ISSUE TITLE
No props appearing for named function export with Addon-docs

### ISSUE THREAD

**Issue by LiteMorgan** [storybookjs/storybook#9205]
**Describe the bug**
Been trying various things to get the props to appear for my component library with no luck. This is using the `5.3.0-rc.0` version of Storybook and Addon-docs.

I've been trying with both `js` and `mdx` file types and seeing no success. A named function export, with props and comments, renders in the Docs file with "No props found for this component".

I've set up the MDX rules following the [Manual configuration guide on the README](https://github.com/storybookjs/storybook/tree/master/addons/docs#manual-configuration).

**Expected behavior**
Props should be populated in Docs.

**Code snippets**
Component:
```js
import React from 'react'
import PropTypes from 'prop-types'

export const Dummy = ({
  textProp
}) => {
  return (
    <div>
      { textProp }
    </div>
  )
}

Dummy.propTypes = {
  /**
   * Test code export
   */
  textProp: PropTypes.string.isRequired,
}
```

MDX:
```
import { Meta, Props, Preview, Story } from '@storybook/addon-docs/blocks'
import { Dummy } from './'

<Meta
  title="mdx/dummy"
  component={Dummy}
/>

# Test

<Preview>
  <Story name="testing">
    <Dummy textProp="Hello world" />
  </Story>
</Preview>

## Props

<Props of={Dummy} />
```

**Screenshots**
![Screenshot 2019-12-20 at 09 52 22](https://user-images.githubusercontent.com/1698932/71246380-71900680-230e-11ea-821b-f01db86df647.png)

**System:**
```
  System:
    OS: macOS 10.15.1
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
  Binaries:
    Node: 11.13.0 - ~/.nvm/versions/node/v11.13.0/bin/node
    Yarn: 1.21.1 - ~/.yarn/bin/yarn
    npm: 6.7.0 - ~/.nvm/versions/node/v11.13.0/bin/npm
  Browsers:
    Chrome: 79.0.3945.88
    Safari: 13.0.3
  npmPackages:
    @storybook/addon-a11y: ^5.3.0-rc.0 => 5.3.0-rc.0 
    @storybook/addon-contexts: ^5.3.0-rc.0 => 5.3.0-rc.0 
    @storybook/addon-docs: ^5.3.0-rc.0 => 5.3.0-rc.0 
    @storybook/addon-knobs: ^5.3.0-rc.0 => 5.3.0-rc.0 
    @storybook/addon-links: ^5.3.0-rc.0 => 5.3.0-rc.0 
    @storybook/addon-viewport: ^5.3.0-rc.0 => 5.3.0-rc.0 
    @storybook/addons: ^5.3.0-rc.0 => 5.3.0-rc.0 
    @storybook/preset-scss: ^1.0.2 => 1.0.2 
    @storybook/react: ^5.3.0-rc.0 => 5.3.0-rc.0 
    @storybook/theming: ^5.3.0-rc.0 => 5.3.0-rc.0
```

**Comment by shilman** [comment]
Are you using CRA? If so, have you tried the standalone preset? https://github.com/storybookjs/presets/tree/master/packages/preset-create-react-app 

Is `babel-plugin-react-docgen` being applied when you `yarn storybook --debug-webpack`?

**Comment by getignited** [comment]
Not using CRA, as this is a Components-only library (is bundled and then exported for use in a different project).

`babel-plugin-react-docgen` appears under the `test: /\.(mjs|jsx?)$/` section, as an option for `babel-loader`.

```
[ '/.../@storybook/react/node_modules/babel-plugin-react-docgen/lib/index.js',
   { DOC_GEN_COLLECTION_NAME: 'STORYBOOK_REACT_CLASSES' } ]
```

**Comment by Zunaib** [comment]
## Try doing this, got out of the same problem.

```ts
import React, {  FC } from 'react';
import PropTypes from 'prop-types'

export interface DummyProps extends HTMLAttributes<HTMLElement> {
textProp:string;
 };

export const Dummy: FC<DummyProps > = function ({ textProp }) {
 return (
    <div>
      { textProp }
    </div>
  );
};

Dummy.propTypes = {
  /**
   * Test code export
   */
  textProp: PropTypes.string.isRequired,
};

export default Dummy;
```

**Comment by getignited** [comment]
That seems a little excessive just to get Prop definitions working within Storybook - I was under the impression standard React could be used, rather than having to double up on type definitions for every Component.

@shilman has there been any update on this? I've updated to 5.3.0-rc.9 and I'm still facing the same issue.

**Comment by shilman** [comment]
@getignited Do you have a reproduction?

**Comment by getignited** [comment]
@shilman I'll put something together for you.

**Comment by getignited** [comment]
@shilman I've managed to reproduce that correctly here: https://github.com/getignited/storybook-docs-test

**Comment by shilman** [comment]
@getignited
- I added a debugging statement to `babel-plugin-react-docgen` and saw that it wasn't being run on your JS files due to your configuration
- I added `babel-plugin-react-docgen` to your list of babel plugins in `.storybook/webpack.config.js`
- I uncommented an error logging line in `babel-plugin-react-docgen` and am seeing this error: `Error: Configuration contains string/RegExp pattern, but no filename was passed to Babel`

I need to jump onto something else, but maybe that gets you on the right path?

**Comment by getignited** [comment]
@shilman I'll take a look at that, thank you. When I was setting that reproduction up, it definitely worked for a bit, until some of the Babel stuff started coming into play. Just got to figure out which one is upsetting it, I suppose!

**Comment by andreasabilio** [comment]
We've also run into this issue. Indeed `babel-plugin-react-docgen` seems not to be running.

Furthermore, it works with a dummy React component but doesn't work with Semantic UI React (SUIR) components... And all SUIR components do have a `propTypes` property.

When A SUIR component reaches the `getDocgenSection` function it lacks the `__docgenInfo` property.

This is on Storybook v5.3.3 and v5.3.6.

Hope it helps with the debugging :-)

**Comment by AlexMold** [comment]
@shilman I have the same problem with CRA
`.storybook/main.js`
```
module.exports = {
    presets: [
        {
            name: 'storybook-addon-deps/preset',
            options: {
                exclude: /^@babel/,
            },
        },
    ],
    stories: ['../src/**/*.stories.(js|mdx)'],
    addons: [
        '@storybook/preset-create-react-app',
        '@storybook/addon-actions',
        '@storybook/addon-links',
        '@storybook/addon-knobs/register',
        '@storybook/addon-storysource',
        '@storybook/addon-backgrounds/register',
        '@storybook/addon-docs',
    ],
}
```

I have a component
```
import React from 'react'
import PropTypes from 'prop-types'
import classNames from 'classnames'
import {capitalize} from 'util/capitalize'
import styles from './styles/Button.module.sass'

const baseClassName = 'Button'

export const ButtonView = React.memo(Button)

function Button({children, classes = {root: styles[baseClassName]}, className, color, ...other}) {
    return (
        <button
            className={classNames(
                classes.root,
                {
                    [styles[`${baseClassName}${capitalize(color)}`]]: color !== 'default',
                },
                className,
            )}
            {...other}
        >
            {children}
        </button>
    )
}

Button.defaultProps = {
    color: 'default',
}

Button.propTypes = {
    children: PropTypes.node.isRequired,
    color: PropTypes.oneOf(['default', 'primary']),
    classes: PropTypes.object,
}
```
Screenshot
<img width="570" alt="Screen Shot 2020-02-11 at 08 42 15" src="https://user-images.githubusercontent.com/7162245/74213493-8a7fbd00-4caa-11ea-96f1-e5dfd92c417f.png">

**Comment by soulfresh** [comment]
I've noticed this same issue on a couple projects and was just able to track it down to the CRA preset. The props table works if I remove `@storybook/preset-create-react-app` in `main.js`. Removing this doesn't seem to have any other impact on my storybook (though error messages note this will break in the future).

Here's my config setup:
```js
// main.js
var path = require('path');

module.exports = {
  stories: ['../src/**/*.stories.mdx'],
  addons: [
    // '@storybook/preset-create-react-app',
    '@storybook/addon-actions',
    '@storybook/addon-storysource',
    '@storybook/addon-knobs',
    '@storybook/addon-a11y',
    '@storybook/addon-docs',
  ],
  webpackFinal: (config) => {
    config.resolve.alias = {
      '~': path.resolve(__dirname, '../src/'),
    };

    return config;
  },
};
```

I also have a `preview.js` file that imports a global stylesheet but I doubt that has any impact here.

**Comment by shilman** [comment]
cc @mrmckeb

**Comment by anusky** [comment]
Same problem here. This is my `main.js` configuration.
![image](https://user-images.githubusercontent.com/5641377/74348490-1715a280-4db3-11ea-85ea-d9476f5f0650.png)
I'm currently using `version 5.3.13` of storybooks and addons.

**Comment by mrmckeb** [comment]
@soulfresh, are you able to supply a simple repro repo? I can then take a look in context and see what's happening.

We have this working with the preset in the `examples` folder in that project, so it might be something else conflicting.

**Comment by Dashue** [comment]
Another one having the same issue here. It was working recently

**Comment by shilman** [comment]
@Dashue do you have a repro?

**Comment by Dashue** [comment]
@shilman Hey Michael, thanks for your time.
I spent yesterday digging through bugs, issues and discussions.
I was both wrapping my components in a hoc (to apply consistent styling to all my components), which involved generics, this was working until I moved the hoc to it's own file for re-use.

I've solved it by exporting one component to feed to the docs addon and another to consume and use in the story itself.
I also upgraded to 6.0 but I believe this approach would work for 5x as well.

I.e
export const _heading = () => ...
export const Heading = ComponentBaseHoc<TProps>(()=>...)

Story:
export default {
  title: 'UI | Type / Heading',
  component: _heading,
}

export const HeadingWithTitle = () => <Heading title='my title' />

**Comment by thehulke** [comment]
@getignited  Hey, Have you tried `import * as React from 'react' ` in your component?

**Comment by Dashue** [comment]
I would love to help out with this. I'm currently in the 6 alpha, but still using the old 1.2.2 preset. As soon upgrade to 2 or 3 my props disappear

**Comment by tabrez96** [comment]
I had a similar issue, I had forgotten to add 'Component' attribute in the story's export.

```export default {
  title: 'Playground|Components/Button',
  decorators: [/** Your decorators */],
  component: Button (/** Your component name */),
};```

**Comment by Horsty80** [comment]
Hi all, i've a similar issue, and i didn't know how to fix it ?
Any suggestion ?

//main.js
```
module.exports = {
  stories: ["../src/**/*.stories.js"],
  addons: [
    "@storybook/preset-create-react-app",
    "@storybook/addon-actions",
    "@storybook/addon-links",
    "@storybook/addon-docs",
  ],
};
```

```
addParameters({
  docs: {
    inlineStories: true,
    container: DocsContainer,
    page: DocsPage,
  },
});
```

```
storiesOf("Test", module)
  .addParameters({ component: Test })
  .add("primary", () => <Test text={primaryButton.text} />);
```
```
import React from "react";
import PropTypes from "prop-types";

const Test = ({ text }) => {
  return <button>{text}</button>;
};
Test.defaultProps = {
  text: "Create",
};
Test.propTypes = {
  text: PropTypes.string,
};

export default Test;

```

**Comment by shilman** [comment]
We've overhauled props handling in 6.0, can somebody who's having this issue try upgrading and LMK if you're still having the issue? https://github.com/storybookjs/storybook/issues/9311

**Comment by Horsty80** [comment]
Hi @shilman , i've update to v6
```
  "devDependencies": {
    "@storybook/addon-actions": "^6.0.0-beta.37",
    "@storybook/addon-docs": "^6.0.0-beta.37",
    "@storybook/addon-links": "^6.0.0-beta.37",
    "@storybook/addons": "^6.0.0-beta.37",
    "@storybook/preset-create-react-app": "^3.1.2",
    "@storybook/react": "^6.0.0-beta.37",
```

But props it's steel not working and don't appear in docs tab.
=/

**Comment by shilman** [comment]
@Horsty80 do you have a public repro i can look at?

**Comment by Horsty80** [comment]
Yes sure normally it's public, let me know if it's not
[https://gitlab.com/Horsty/horsty-components](https://gitlab.com/Horsty/horsty-components)

**Comment by Horsty80** [comment]
Hum my build on netlify doesn't work anymore....

> 2:19:47 PM: ┌────────────────────────────────┐
2:19:47 PM: │ 1. Build command from settings │
2:19:47 PM: └────────────────────────────────┘
2:19:47 PM: ​
2:19:47 PM: $ npm run build-storybook
2:19:47 PM: > horsty-components@0.1.0 build-storybook /opt/build/repo
2:19:47 PM: > build-storybook -s public
2:19:48 PM: info @storybook/react v6.0.0-beta.37
2:19:48 PM: info 
2:19:48 PM: info clean outputDir..
2:19:48 PM: info => Copying static files from: public
2:19:48 PM: info => Copying prebuild dll's..info => Building manager..
2:19:48 PM: info => Loading manager config..
2:19:48 PM: info => Loading presets
2:19:49 PM: info => Compiling manager..
2:19:58 PM: ERR! => Failed to build the manager
2:19:58 PM: ERR! ./.storybook/generated-refs.js
2:19:58 PM: ERR! Module build failed (from ./node_modules/babel-loader/lib/index.js):
2:19:58 PM: ERR! TypeError: [BABEL] /opt/build/repo/.storybook/generated-refs.js: Cannot read property 'chrome' of undefined (While processing: "/opt/build/repo/node_modules/@babel/preset-env/lib/index.js")
2:19:58 PM: ERR!     at getLowestImplementedVersion (/opt/build/repo/node_modules/@babel/helper-compilation-targets/lib/utils.js:58:24)
2:19:58 PM: ERR!     at /opt/build/repo/node_modules/@babel/helper-compilation-targets/lib/filter-items.js:26:77
2:19:58 PM: ERR!     at Array.filter (<anonymous>)
2:19:58 PM: ERR!     at targetsSupported (/opt/build/repo/node_modules/@babel/helper-compilation-targets/lib/filter-items.js:25:54)
2:19:58 PM: ERR!     at isRequired (/opt/build/repo/node_modules/@babel/helper-compilation-targets/lib/filter-items.js:58:11)
2:19:58 PM: ERR!     at filterItems (/opt/build/repo/node_modules/@babel/helper-compilation-targets/lib/filter-items.js:70:9)
2:19:58 PM: ERR!     at /opt/build/repo/node_modules/@babel/preset-env/lib/index.js:262:65
2:19:58 PM: ERR!     at /opt/build/repo/node_modules/@babel/preset-env/node_modules/@babel/helper-plugin-utils/lib/index.js:19:12
2:19:58 PM: ERR!     at /opt/build/repo/node_modules/@babel/core/lib/config/full.js:199:14
2:19:58 PM: ERR!     at Generator.next (<anonymous>)
2:19:58 PM: ERR!     at Function.<anonymous> (/opt/build/repo/node_modules/@babel/core/lib/gensync-utils/async.js:26:3)
2:19:58 PM: ERR!     at Generator.next (<anonymous>)
2:19:58 PM: ERR!     at step (/opt/build/repo/node_modules/gensync/index.js:254:32)
2:19:58 PM: ERR!     at evaluateAsync (/opt/build/repo/node_modules/gensync/index.js:284:5)
2:19:58 PM: ERR!     at Function.errback (/opt/build/repo/node_modules/gensync/index.js:108:7)
2:19:58 PM: ERR!     at errback (/opt/build/repo/node_modules/@babel/core/lib/gensync-utils/async.js:70:18)
2:19:58 PM: ERR!  @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/client/manager/index.js ./node_modules/@storybook/addon-actions/dist/register.js ./node_modules/@storybook/addon-links/dist/register.js ./node_modules/@storybook/addon-docs/dist/register.js ./.storybook/generated-refs.js main[5]
2:19:58 PM: (node:1415) UnhandledPromiseRejectionWarning: [object Object]
2:19:58 PM: (node:1415) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
2:19:58 PM: (node:1415) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2:19:58 PM: npm ERR! code ELIFECYCLE
2:19:58 PM: npm ERR! errno 1
2:19:58 PM: npm ERR! horsty-components@0.1.0 build-storybook: `build-storybook -s public`
2:19:58 PM: npm ERR! Exit status 1
2:19:58 PM: npm ERR!
2:19:58 PM: npm ERR! Failed at the horsty-components@0.1.0 build-storybook script.
2:19:58 PM: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2:19:58 PM: npm ERR! A complete log of this run can be found in:
2:19:58 PM: npm ERR!     /opt/buildhome/.npm/_logs/2020-06-29T12_19_58_931Z-debug.log
2:19:59 PM: ​
2:19:59 PM: ┌─────────────────────────────┐
2:19:59 PM: │   "build.command" failed    │
2:19:59 PM: └─────────────────────────────┘
2:19:59 PM: ​
2:19:59 PM:   Error message
2:19:59 PM:   Command failed with exit code 1: npm run build-storybook
2:19:59 PM: ​
2:19:59 PM:   Error location
2:19:59 PM:   In Build command from settings:
2:19:59 PM:   npm run build-storybook
2:19:59 PM: ​
2:19:59 PM:   Resolved config
2:19:59 PM:   build:
2:19:59 PM:     command: npm run build-storybook
2:19:59 PM:     publish: /opt/build/repo/storybook-static
2:19:59 PM: Caching artifacts
2:19:59 PM: Started saving node modules
2:19:59 PM: Finished saving node modules
2:19:59 PM: Started saving build plugins
2:19:59 PM: Finished saving build plugins
2:19:59 PM: Started saving yarn cache
2:19:59 PM: Finished saving yarn cache
2:19:59 PM: Started saving pip cache
2:20:06 PM: Finished saving pip cache
2:20:06 PM: Started saving emacs cask dependencies
2:20:06 PM: Finished saving emacs cask dependencies
2:20:06 PM: Started saving maven dependencies
2:20:06 PM: Finished saving maven dependencies
2:20:06 PM: Started saving boot dependencies
2:20:06 PM: Finished saving boot dependencies
2:20:06 PM: Started saving go dependencies
2:20:06 PM: Finished saving go dependencies
2:20:06 PM: Error running command: Build script returned non-zero exit code: 1
2:20:06 PM: Failing build: Failed to build site
2:20:06 PM: Failed during stage 'building site': Build script returned non-zero exit code: 1
2:20:06 PM: Finished processing build request in 1m51.731339398s

**Comment by Horsty80** [comment]
Hi @shilman any news of this bug ? =/
How can i help you to investigate on this ?

**Comment by shilman** [comment]
Took me awhile to track down with @mrmckeb and I'm not very satisfied with where we got. Try adding the following to your `babel.config.js`:

```js
  const presets = ["@babel/preset-env", "@babel/preset-react"];
```

I modified a bunch of other things in the project in the process of debugging, but pretty sure that's the proper fix. WDYT?

**Comment by Horsty80** [comment]
Thanks @shilman it's working fine !
i've my propsTypes showing.

So fix with : 
 - update in v6
 - add presets `const presets = ["@babel/preset-env", "@babel/preset-react"];` in `babel.config.js`
 - npm install

**Comment by EdenTurgeman** [comment]
@shilman after upgrading to ``
We couldn't get our typescript props to display even with a simple example component
`No inputs found for this component. Read the docs >`

with this `main.ts`: 
```js 
const path = require('path');

interface TypescriptOptions {
  check?: boolean;
  docgen?: 'none' | 'react-docgen' | 'react-docgen-typescript';
}

export const typescript: TypescriptOptions = {
  check: true,
  docgen: 'react-docgen-typescript'
};

module.exports = {
  typescript,
  stories: ['../stories/**/*.story.@(js|jsx|ts|tsx)'],
  addons: [
    {
      name: '@storybook/addon-docs',
      options: {
        sourceLoaderOptions: {
          rule: {
            include: [path.resolve(__dirname, '../stories')],
          },
          loaderOptions: {
            prettierConfig: { printWidth: 80, singleQuote: false },
          },
        },
      },
    },
    {
      name: '@storybook/addon-storysource',
      options: {
        rule: {
          include: [path.resolve(__dirname, '../stories')],
        },
        loaderOptions: {
          prettierConfig: { printWidth: 80, singleQuote: false },
        },
      },
    },
    '@storybook/addon-knobs/register',
]
};
```

`preview.js`:
```js
import React from 'react';
import { bootstrap } from "@ui/styleguide";
import { addDecorator ,addParameters} from '@storybook/react';
import { DocsPage, DocsContainer } from '@storybook/addon-docs/blocks';
import { StoryContainer } from "../stories/storyComponents/StoryContainer";

addDecorator(Story =>
  <StoryContainer>
    <Story />
  </StoryContainer>
);

addParameters({
  docs: {
    container: DocsContainer,
    page: DocsPage,
  },
});

bootstrap();
```

**Comment by shilman** [comment]
@EdenTurgeman do you have a repro?

**Comment by EdenTurgeman** [comment]
@shilman 
Not currently... since we're working with a private repo.
I might eventually try to create a public repo since we're having quite a few issues upgrading which we can't diagnose, is there a way I could give out more info considering our current state? (webpack debug info? custom webpack config?)

**Comment by shilman** [comment]
@EdenTurgeman standalone minimal repro is the best way. if you have a bunch of issues around a specific feature, like prop tables, a repo that demonstrates all those issues in one place is also great

**Comment by wolfhoundjesse** [comment]
Just popping in to say that I created a minimum repro for you, but everything was working fine, so … .

In my own project, the props aren't showing up for a default export. If I change it to named (but won't, because code splitting) it works, and if I export it both ways (why is this allowed?), then I get props when I import it as a named component.

At any rate, thanks for taking the time!

**Comment by ianldgs** [comment]
In my case is a Stencil component using the [react integration](https://stenciljs.com/docs/react).

No propTypes on the component, but there are TypeScript `Props` definitions.

```
export default {
  title: 'My Stencil Component',
  parameters: { notes: { markdown } },
  component: MyStencilComponent
};
```

**Comment by keyserfaty** [comment]
Same issue here. Proptypes are not shown not even in the example provided by Storybook:

``` jsx
import React from 'react';
import PropTypes from 'prop-types';
import './button.css';

/**
 * Primary UI component for user interaction
 */
export const Button = ({ primary, backgroundColor, size, label, ...props }) => {
  const mode = primary ? 'storybook-button--primary' : 'storybook-button--secondary';
  return (
    <button
      type="button"
      className={['storybook-button', `storybook-button--${size}`, mode].join(' ')}
      style={backgroundColor && { backgroundColor }}
      {...props}
    >
      {label}
    </button>
  );
};

Button.propTypes = {
  /**
   * Is this the principal call to action on the page?
   */
  primary: PropTypes.bool,
  /**
   * What background color to use
   */
  backgroundColor: PropTypes.string,
  /**
   * How large should the button be?
   */
  size: PropTypes.oneOf(['small', 'medium', 'large']),
  /**
   * Button contents
   */
  label: PropTypes.string.isRequired,
  /**
   * Optional click handler
   */
  onClick: PropTypes.func,
};

Button.defaultProps = {
  backgroundColor: null,
  primary: false,
  size: 'medium',
  onClick: undefined,
};

```

Docs:
<img width="1065" alt="Screen Shot 2021-02-13 at 14 17 25" src="https://user-images.githubusercontent.com/4960753/107856331-33a14c00-6e06-11eb-831d-186633b5526d.png">


Versions:
```
    "@storybook/addon-actions": "^6.1.17",
    "@storybook/addon-essentials": "^6.1.17",
    "@storybook/addon-links": "^6.1.17",
    "@storybook/node-logger": "^6.1.17",
    "@storybook/preset-create-react-app": "^3.1.5",
    "@storybook/react": "^6.1.17",
    "react": "^16.13.1",
```

**Comment by keyserfaty** [comment]
Nevermind! Can confirm that adding and installing the following solved the issue for me:
```
"presets": [
    "@babel/preset-env",
    "@babel/preset-react"
  ]
```

**Comment by srt4rulez** [comment]
On Storybook 6.1.21, I had the same issue as @keyserfaty, where it only showed a few props from the default "button" component that Storybook shipped with.

The issue was because I completely overwrote the module.rules array in webackFinal function of main.js with my own webpack config.

I instead spread storybooks rules first, then did my own webpack config:

```js
const webpackConfig = require('./../webpack.config');

module.exports = {
    // ...
    webpackFinal: async (config) => {

        const appConfig = webpackConfig(); // my webpack config exports a function

        return {
            ...config,
            module: {
                ...config.module,
                rules: [
                    ...config.module.rules,
                    ...appConfig.module.rules,
                ],
            },
        };
    },
}
```
