### ISSUE TITLE
addon-info: is `withInfo` decorator deprecated?

### ISSUE THREAD

**Issue by zaki-yama** [storybookjs/storybook#9211]
**Describe the bug**
Sorry this is just a question.
addon-info's `withInfo()` decorator is deprecated?

**To Reproduce**
When I write a story like this,

```javascript
import React from 'react';
import { storiesOf } from '@storybook/react';
import { action } from '@storybook/addon-actions';
import { withInfo } from '@storybook/addon-info';

import Button from './Button';

storiesOf('Button', module)
  .add('Default', withInfo('Default button')(() => (
    <Button label="The Button" onClick={action('click')} />
  )));
```

I get the following warning in the browser's console.

```
Passing stories directly into withInfo() is deprecated,
          instead use addDecorator(withInfo) and pass options with the 'info' parameter
```

**What I want to know**
I found that Storybook 4 had introduced story parameters.
https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#addon-story-parameters
But addon-info wasn't listed here.

So I want to ask you 3 questions:

1. Is it correct that `withInfo()` is also deprecated, and I shouldn't use it any more?
2. Do you have any plans about from which version I can't use this decorator style?
3. Are there any codemods? I found [update-addon-info.js](https://github.com/storybookjs/storybook/blob/next/lib/codemod/src/transforms/update-addon-info.js), but it just replaces old `addWithInfo()` API

**Comment by shilman** [comment]
`Addon-info` is being superceded by `addon-docs`, which fixes a bunch of bugs and is easier to maintain. Please give it a try! https://medium.com/storybookjs/storybook-docspage-e185bc3622bf

**Comment by zaki-yama** [comment]
@shilman 
Thank you! I'll try the new `addon-docs`.
What about my questions? Is `withInfo()` also deprecated like other addons' `withXXX` methods, right?

**Comment by shilman** [comment]
@zaki-yama It looks like it's deprecated and better to use `parameters: { info: ... }}` instead. But still supported (for now)!

**Comment by zaki-yama** [comment]
@shilman 
I understood! Thank you.
