### ISSUE TITLE
Open Canvas in new tab stopped working in MAC browsers.

### ISSUE THREAD

**Issue by salmanmd786** [storybookjs/storybook#9217]
**Open Canvas in new tab** stopped working in MAC Browsers, opens blank screen and no console errors. Tested in Chrome, FF and Safari latest versions, whereas in **windows browsers** it works absolutely fine. Am not sure if anyone as well facing the same problem.

We are using the latest versions of storybook(5.2.8) and its add-on's and as well this issue is reproducible in version 5.2.6. 
Can someone help with the solution.

1. Run storybook
2. Click on the icon **Open Canvas in new tab**, which looks like a square box with arrow facing upwards, located on the top right side of the bar.

storybook config:
```js
import { addParameters, configure, addDecorator } from '@storybook/react';
import { withA11y } from '@storybook/addon-a11y';
import { withInfo } from '@storybook/addon-info';
import { withKnobs } from '@storybook/addon-knobs';
import { withThemesProvider } from 'storybook-addon-emotion-theme';
import Theme from './theme';

addDecorator(withKnobs);
addDecorator(withA11y);
addDecorator(withInfo);
addDecorator(withThemesProvider(require('custom-themes')));

addParameters({
a11y: {
config: {},
options: {
checks: { 'color-contrast': { options: { noScroll: true } } },
restoreScroll: true
}
},
options: {
theme: Theme,
panelPosition: 'bottom'
},
backgrounds: [
{ name: 'White', value: '#FFFFFF' },
{ name: 'Black', value: '#000000' },
]
});

const loadStories = () => {
const req = require.context('../src', true, /.stories.js$|/stories/.*.js$/);
req.keys().forEach(filename => req(filename));
};

configure(loadStories, module);
```

**Comment by shilman** [comment]
@salmanmd786 can you provide a reproduction repo? it seems to be working fine in storybook's monorepo.
