### ISSUE TITLE
@storybook/notes documentation should have examples for CSF

### ISSUE THREAD

**Issue by acroyear** [storybookjs/storybook#9222]
All of the examples in the README.md page for the notes add-on are still only using storiesOf.

There are no examples of how to configure notes for CSF. As a result, it discourages moving to the new format.

**Comment by acroyear** [comment]
I did eventually stumble into it when I found a 'parameters' entry in an example on another bug.

`export default {
  title: 'Welcome',
  parameters: { notes: "hi mom"}
};`

**Comment by shilman** [comment]
All of the examples are now in CSF: https://github.com/storybookjs/storybook/blob/next/addons/notes/README.md

**Comment by acroyear** [comment]
ah.  i'm not so cutting edge to be using 'next' yet. :)  i'm still catching up to react 16 hooks features and all that.  feel free to close this if you like.
