### ISSUE TITLE
Addon-action does not work on projects created with 'storybook cli' and created with 'CSF'.

### ISSUE THREAD

**Issue by Dev-Jeromebaek** [storybookjs/storybook#9233]
### 1. Bind the storybook through the cli first.
```
mkdir storybook-tutorial
cd storybook-tutorial
yarn init -y 
# OR npm init -y
npx -p @storybook/cli sb init --type react
```

### 2. Run the storybook server.
```
yarn storybook
# OR npm run storybook
```

## **Expected behavior**
Action should occur as shown in the following image, but no response will occur.
![image](https://user-images.githubusercontent.com/27988231/71388260-ea5acf80-263a-11ea-9ded-e8563334d306.png)

but, No matter how many times you press the button, the action does not appear.

## **Screenshots**

![image](https://user-images.githubusercontent.com/27988231/71388189-a5369d80-263a-11ea-9571-9d4b7c34a86b.png)

**Comment by Dev-Jeromebaek** [comment]
Looks like there's a collision with another chrome extension.

**Comment by adeelibr** [comment]
@Dev-Jeromebaek what was the plugin that was causing the conflict?
