### ISSUE TITLE
Site with documentation works not stable.

### ISSUE THREAD

**Issue by alexandrsmirnov93** [storybookjs/storybook#9240]
I have a problem during loading web site https://storybook.js.org/
This site is loading succsecfuly not all the time, aproximatly one time of five. Could you please resolve it?

**Comment by shilman** [comment]
Is it possibly a connection issue? It's a static site hosted at netlify -- not really sure what could be going wrong...

**Comment by alexandrsmirnov93** [comment]
This problem is reproduced on several devices, internet - providers and people. I guess it could be the problems on hosting.
