### ISSUE TITLE
Let the user define a CSS theme, not a JS theme file

### ISSUE THREAD

**Issue by ylacaute** [storybookjs/storybook#9256]
**Is your feature request related to a problem? Please describe.**
I am using a custom JS theme and I do not find a way to center my logo in its container. As the result, my circle logo is stuck on the left.
I read [the theming doc](https://storybook.js.org/docs/configurations/theming/) and checked the code without any clue. I also checked the **preview-head.html** or tried to include a custom CSS in the **config.js** but all this is for the iframe scope, not for the Storybook website.

**Describe the solution you'd like**
As the web standard for theming is CSS (not JS), I would like to have an option/addon/anything which let me specify a CSS file to customize the Storybook website.

**Describe alternatives you've considered**
An alternative could be to add a new property to the JS theme system, but this would be ugly. The standard is CSS.

**Are you able to assist bring the feature to reality?**
No, I am still discovering how this library is working.

**Additional context**
V5.2.8, React

**Comment by ivomynttinen** [comment]
You can add custom CSS to the storybook wrapper by adding it to the **manager-head.html** file (instead of preview-head, which can contain css for the story iframes).

**Comment by ylacaute** [comment]
Thank you, I still don't manage to include the CSS. For example:
```html
<!-- manager-head.html -->
<link rel="stylesheet" href="test.css" />
```
In which directory should be test.css in order to have something working ? (I got a 404 on that file wherever I put it).

**More info:**
 - package.json: "start-storybook -s ./src/main/resources -p 6006 -c doc
 - ".storybook" rennamed to "doc"

**Comment by ivomynttinen** [comment]
There's probably a way to achieve that with an external file, but I wasn't able to get it working either. The only solution that worked for me was to include all styles directly within the manager-head.html as a style tag:

```html
<style>
  //styles
</style>
```

Also, you will probably need to work a lot with dirty `!important` overwrites, since all the styles in storybooks are inline styles.

**Comment by ylacaute** [comment]
Yes thank you, I was thinking about this as a workaround, but I must say it: inline styles are **EVIL** and we are assisting at the worst terrible trend over the last decade in the frontend development world. There are no valid argument, inline styles should be banned and the very last option.

That's said, I am exactly in the situation right now where inline styles can be acceptable since I have no other option. For a tiny fix (I just want a centered logo), it is acceptable.

But I think it could be interesting to have an external CSS (working locally) because JS theming is not standard. CSS is ! 

**Use case:** Oh, I will customize my web site with a shadow on some container ! I have to add something in the JS theming file... Oh wait... where is the doc... oh wait, there is no option to do that... oh wait, I have to make a PR just that, really ? This is inconcevable for me, CSS has been invented exactly to do that. That is why I don't like either JS theming :stuck_out_tongue_winking_eye:
