### ISSUE TITLE
Addon Centered: position fixed should be relative

### ISSUE THREAD

**Issue by ylacaute** [storybookjs/storybook#9260]
**Describe the bug**
The position "fixed" for the component container do not scale in all situations.
**The position should be "relative".**

**To Reproduce**
1. Create a component without width defined with flex display
2. Display it in MDX with a preview

**Expected behavior**
The component should appears, we see an empty container. But if we inspect the dom elements, we can find it. When we change the position of the container (the one who use fixed) to "relative", everything is fine.

**Screenshots**
No need, its like no component where defined.

I wanted to check this bug directly in the code source but I cannot start the app: too many open files, watch 'src'. I tried some fixes but without result:
 - Change "fs" to "graceful-fs": change nothing
 - increase the soft limit to 40k ! change nothing
 - /proc/sys/fs/file-max is already to 5M...

Note: I only see one use case to set a "fixed" position : when you want to scroll a container and keep a child in front who does not follow. Maybe it exists some tricks but I am pretty sure this position should not be used at all in all the Storybook project.

**Comment by Eplumecocq** [comment]
+1 to replace the `position:fixed` on parent container by `position:relative`. 

Is there any workaround ?

**Comment by ylacaute** [comment]
@Eplumecocq You Could forgot this plugin and build your own container (centered in flex in mine), it is much more poweful :)
Check this code: https://github.com/ylacaute/ez-Dashing/tree/master/ez-client/doc/containers

**Comment by shilman** [comment]
@ndelangen can we move centered out of monorepo and update the docs to point to the new `layout` parameter?

**Comment by ndelangen** [comment]
Yes, I'll do that as part of my 6.0 deprecation efforts. I plan on starting that work next week when composition is finished and merged.
