### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by SoloJiang** [storybookjs/storybook#9262]
https://circleci.com/gh/storybookjs/storybook/186184?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

I submitted a [pull request](https://github.com/storybookjs/storybook/pull/9220) last week. But I couldn't understand the test result meaning.

**Comment by shilman** [comment]
This typically means that babel is not configured properly for JSX

**Comment by SoloJiang** [comment]
> This typically means that babel is not configured properly for JSX

But, weirdly, I don't have this error locally

**Comment by SoloJiang** [comment]
@shilman Can you help me to solve it?

**Comment by shilman** [comment]
@SoloJiang sure I'll take a closer look
