### ISSUE TITLE
Addon docs - Docgen regression with spead props

### ISSUE THREAD

**Issue by ylacaute** [storybookjs/storybook#9266]
**Describe the bug**
Composed props are not displayed anymore in the generated docs.

**Last working version:** 5.2.8
**The next is not working anymore:** 5.3.0-alpha.0 (RC-1 and RC-4 also verifed)

**To Reproduce**
1. Create a component with its story
2. Define propTypes with spread: 
```jsx
AudioPlayerWidget.propTypes = {
  /**
   * All these props coming from elsewhere are not displayed anymore
   */
  ...Widget.propTypes,

  /**
   * This prop is displayed correctly
   */
  sample: PropTypes.number
};
```
**Expected behavior**
The name (and only the name) of the prop should be displayed. I don't expect type, description and default value as the problem for these fields come from the React-docgen which does not support prop composition (https://github.com/reactjs/react-docgen/issues/151).

**System:**
React 16

**Comment by shilman** [comment]
@ylacaute If this is a regression, does that mean that there's an older working version? If so, what version worked?

**Comment by ylacaute** [comment]
Yes, with v5.2.8 it is working as expected

**Comment by shilman** [comment]
cc @patricklafrance - I think this is due to relying entirely on `react-docgen` without the fallback props processor. WDYT?

**Comment by patricklafrance** [comment]
To my knowledge it never worked if the props types are imported from another file. This is is an issue with react-docgen.

There is a test case for this in cra-ts-kitchen-sink

**Comment by shilman** [comment]
The fallback code that got deleted didn't rely on `react-docgen`.

**Comment by patricklafrance** [comment]
@shilman the fallback code is for the defaultProps not the propTypes

**Comment by patricklafrance** [comment]
Sorry, was on my phone. If I understand well, in 5.2 there was fallback code that basically took the original propTypes object and use output the value for all the props that were not returned by react-docgen.

If this is the case, yeah that code is gone.

I think this is something to have been fix in react-docgen 5.0.

**Comment by patricklafrance** [comment]
Pretty sure though that it was working if the spreaded object was local. Only imported object were not working.

**Comment by patricklafrance** [comment]
Works fine for me with the current `next` branch with a local object.

**Comment by patricklafrance** [comment]
@ylacaute this is how I fixed it in my design system until the issue is solved in react-docgen:

https://github.com/gsoft-inc/sg-orbit/blob/master/packages/react-components/components/date-picker/src/range/date-range-picker.jsx#L14

IMO it's better than adding back a fallback in storybook docs that will only partially render the prop. It's ugly but you'll get a proper rendering with the prop name & type.

**Comment by ylacaute** [comment]
I agree with you, don't add this fallback.

From what I understand, all your DatePick declare all props directly, you don't factorize the props definition, that is exaclty what I was tried to not do but it is not a big deal, I will do the same :)

I will give a closer look at Orbit, it seems a very nice project !! Thank you for sharing.
