### ISSUE TITLE
[addon-docs] Add a check for multiple stories before rendering the Stories component in the DocsPage.

### ISSUE THREAD

**Issue by afebbraro** [storybookjs/storybook#9269]
### Bug or support request summary
Check for multiple stories before rendering the the Stories component in the DocsPage. Without this check, unnecessary rendering of the Stories component headline would occur.

Expect to not see a "Stories" headline with nothing underneath it.

### Steps to reproduce

Go to the examples HTML storybook app and check out a component that only has one story. For example, '/docs/addons-centered--story-1'. You will see that there is a headline at the bottom that reads "Stories". This headline is not needed. This happens in react/angular ETC ETC too. Just using the HTML one as an example to help explain the problem.

This is current in SB HTML. You can see the unneeded "Stories" heading.
![Screen Shot 2019-12-30 at 10 57 35 AM](https://user-images.githubusercontent.com/2117593/71590458-8af73680-2af6-11ea-8739-427c6d738f75.png)

This is with my PR https://github.com/storybookjs/storybook/issues/9269. The heading is removed because there is only one story.
![Screen Shot 2019-12-30 at 11 15 32 AM](https://user-images.githubusercontent.com/2117593/71590466-9b0f1600-2af6-11ea-805f-03693e9b529a.png)

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/html x v5.3.0-rc.4
- @storybook/addon-docs  v5.3.0-rc.4

- but happens in all frameworks!

**Comment by shilman** [comment]
Gadzooks!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-rc.5 containing PR #9271 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
