### ISSUE TITLE
Integrate addons-background with addons-a11y

### ISSUE THREAD

**Issue by patdryburgh** [storybookjs/storybook#9283]
**Is your feature request related to a problem? Please describe.**

When I switch the background using the `addons-background` module and re-run the `addons-a11y` tests, I want the tests to use the new background colour, so I can test whether my components work on all available background colours.

**Describe the solution you'd like**

1. Open Storybook;
2. Select a new background colour using the `addons-background` module;
3. Re-run the accessibility tests from the `addons-a11y` module;
4. See that the new test results show the results using the new background colour.

**Describe alternatives you've considered**

Using the `addons-contexts` module to create my own background colour switcher in the hopes that the `addons-a11y` module would use that setting to determine the colour values to test.

**Are you able to assist bring the feature to reality?**

I haven't had a look at the codebase, so I'm not sure.

**Additional context**

![Dec-31-2019 15-33-05](https://user-images.githubusercontent.com/751461/71633839-dab42b80-2be4-11ea-8a29-bf011d05b850.gif)

**Comment by shilman** [comment]
cc @ndelangen

**Comment by ndelangen** [comment]
Hey @lkopacz, perhaps this issue would be something you'd be keen to investigate?
