### ISSUE TITLE
Addon-docs with MDX: ResizeObserver loop limit exceeded (?)

### ISSUE THREAD

**Issue by ylacaute** [storybookjs/storybook#9286]
**Describe the bug** 
I am not sure at all this is related to Storybook. When building a MDX page with the code below, it generates 5 console errors "ResizeObserver loop limit exceeded" in the console (not in the broswer console, only in the "actions" tab with the console addons).

**To Reproduce**
1. Construct a MDX page with the code below
2. View the result on the browser, clic on the "details" html (it is this expension which generate the error)
3. Go in canvas tab and look at any component, in the "Actions" tab (console addon, no HMR logs)
4. You see 5 times the error "ResizeObserver loop limit exceeded"

I don't undertand why I see those logs in "Actions" and not in the browser.

**Expected behavior**
No error in "Actions" tab.

**Screenshots**
No need screenshot, but the full error is : 
> error: (5) ["ResizeObserver loop limit exceeded", "http://localhost:6006/iframe.html?id=introduction-installation--page&viewMode=docs", 0, 0, null]

**Code snippets**
```mdx
<details>
  <summary>install the packages</summary>
  

``bash
npm install titi
``


</details>
```

**System:**
React 16.12, Storybook 5.3.0-beta.31, Firefox & Chromium

**Additional context**
If we remove the markdown "npm install titi" and replace it with a big text, we don't have the error.
I put only 2 backquotes otherwise it breaks the Github code formatting.

**Comment by shilman** [comment]
That is super bizarre! What happens when you change `bash` to `js`? We only register a small number of highlighters, so perhaps that's causing the problem?
