### ISSUE TITLE
【DOCS】cant't resolve docgen comments from mixin file's props.

### ISSUE THREAD

**Issue by lefreet** [storybookjs/storybook#9296]
**Describe the bug**
when use `addon-docs`，i find that it's is no use for a `vue` mixin file, to resolve docgen comments

**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/25679627/71650611-0dc7fd80-2d52-11ea-8eae-72b0fe037b3e.png)

**Code snippets**

* control.js

```js
{
  props: {
    theme: {
      /**
      * 控件主题
      */
      type: String,
      default: 'light'
    }
  }
}
```

* my control file

```js
{
  mixins: [ control ],
  props: {
    /** 
     * 绑定值
    */
    value: [ String, Number ]
  }
}
```

**System:**
System:
    OS: macOS Mojave 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz
  Binaries:
    Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 6.12.0 - ~/.nvm/versions/node/v12.13.0/bin/npm
  Browsers:
    Chrome: 79.0.3945.88
    Safari: 12.1.1
  npmPackages:
    @storybook/addon-actions: 5.3.0-rc.6 => 5.3.0-rc.6
    @storybook/addon-backgrounds: 5.3.0-rc.6 => 5.3.0-rc.6
    @storybook/addon-docs: 5.3.0-rc.6 => 5.3.0-rc.6
    @storybook/addon-knobs: 5.3.0-rc.6 => 5.3.0-rc.6
    @storybook/addon-notes: 5.3.0-rc.6 => 5.3.0-rc.6
    @storybook/addon-storysource: 5.3.0-rc.6 => 5.3.0-rc.6
    @storybook/addon-viewport: 5.3.0-rc.6 => 5.3.0-rc.6
    @storybook/addons: 5.3.0-rc.6 => 5.3.0-rc.6
    @storybook/source-loader: 5.3.0-rc.6 => 5.3.0-rc.6
    @storybook/vue: 5.3.0-rc.6 => 5.3.0-rc.6
  npmGlobalPackages:
    @storybook/cli: 5.3.0-rc.3

**Additional context**

**Comment by shilman** [comment]
@Aaron-Pool @pocka @elevatebart Looks like an interesting use case... I'm not familiar with vue, so I don't know how common this is?

**Comment by lefreet** [comment]
oh, may some hot refresh bug, it's done well now, thanks.

and there some way to show the `Description` of vue's `method` and `slots`? i can't find in document.

![image](https://user-images.githubusercontent.com/25679627/71654783-83da5d80-2d6e-11ea-9a33-23ba776b2331.png)

**Comment by pocka** [comment]
`vue-docgen-api` can parse derived mixins and its props, so I think something went wrong.

https://codesandbox.io/embed/sparkling-forest-2umxp?fontsize=14&hidenavigation=1&theme=dark

**Comment by pocka** [comment]
@lefreet 
Since docs-addon for Vue uses `vue-docgen-api`, you can add docs for methods and events via special comments.

https://github.com/vue-styleguidist/vue-styleguidist/tree/dev/packages/vue-docgen-api#using-jsdoc-tags

**Comment by lefreet** [comment]
@pocka may some guide link of `vue-docgen-api` in the document will better for green hand. Now I can know more details about how to write docgen comments. thanks you anwer.
