### ISSUE TITLE
Vue with css modules

### ISSUE THREAD

**Issue by chrisjbrown** [storybookjs/storybook#9297]
I'm able to run storybook in my Vue project however the css modules are missing. I've also created a new storybook project with the default webpack config and I have the same issue. No styles

i have a component like this
```js
<template>
  <div :class="$style.component">
    red text
  </div>
</template>

<script>
export default {
  name: 'Thing'
}
</script>

<style module>
.component {
  color: red;
}
</style>
```

and the rendered html is
```html
<div>
  red text
</div>
```

With no css class. Do I need to do something specific to enable css modules?

**Comment by pocka** [comment]
@chrisjbrown 
Yeah, you need to configure a webpack rule for `.css` file in the way [Vue Loader Docs](https://vue-loader.vuejs.org/guide/css-modules.html#opt-in-usage) describing (if you have files something like SASS, add rules for them too.)
I'm not sure `vue-cli-plugin` handles it or not, though.

#### Sample Config

```js
// man.js
module.exports = {
  // ...
  webpackFinal(config) {
    const isCssRule = rule =>
      rule.test && rule.test instanceof RegExp && rule.test.test("./file.css");

        return {
      ...config,
      module: {
        ...config.module,
        rules: [
          ...config.module.rules.filter(rule => !isCssRule(rule)),
          {
            test: /\.css$/,
            oneOf: [
              {
                resourceQuery: /module/,
                use: [
                  "style-loader",
                  {
                    loader: "css-loader",
                    options: {
                      modules: true
                    }
                  }
                ]
              },
              {
                use: ["style-loader", "css-loader"]
              }
            ]
          }
        ]
      }
    }
  }
}
```

[CodeSandbox](https://codesandbox.io/s/vue-storybook-css-modules-fy4n7)

**Comment by chrisjbrown** [comment]
thanks @pocka that worked for me!
for anyone else who finds this, I also needed to add postcss

```js
...
    {
      test: /\.css$/,
      oneOf: [
        {
          resourceQuery: /module/,
          use: [
            'vue-style-loader',
            {
              loader: 'css-loader',
              options: {
                modules: true
              }
            },
            'postcss-loader'
          ]
        },
        {
          use: ['vue-style-loader', 'css-loader', 'postcss-loader']
        }
      ]
    }
...
```

**Comment by 3nuc** [comment]
The above config wasn't working for me initially, because I followed the advice from https://github.com/storybookjs/presets/tree/master/packages/preset-scss#basic-usage saying to do `yarn add -D @storybook/preset-scss css-loader sass-loader style-loader`. I didn't have css-loader and style-loader in my package.json, so I was relying on the package versions installed by subdependencies.

After running the mentioned yarn add, it installed `style-loader@2.0.0`, `css-loader@4.3.0` whereas storybook uses `style-loader@1.3.0`, `css-loader@3.6.0` internally.

To fix the issue, I just changed the style-loader and css-loader to 1.3.0 and 3.6.0 respectively

**Comment by shilman** [comment]
Ugh @3nuc that sounds painful to track down. How should we update the documentation for `preset-scss`?

**Comment by 3nuc** [comment]
I created a repro case here (:class="$style.myClass" in IDE turning into class="" in browser element inspector): https://github.com/3nuc/storybook-is9297 if someone wants to dig in for docs purposes

@shilman I didn't really track down the issue, I just changed the versions blindly and it started working :P Would be nice to know what is missing in the Webpack dist that caused :class="[$style.myStyle]" to turn into class="" in the inspector in Storybook though. 

As for the docs:
1. Removing the instructions to download `css-loader sass-loader style-loader` is slightly "less bad". This reduces the probability of someone running into this issue, but someone that has css-loader and style-loader with too new versions explicitly in their package.json will still run into this issue. I know maintaining loaders is a [nightmare as they change property names every so often](https://stackoverflow.com/questions/62779449/sass-loader-9-0-x-vue-validationerror-invalid-options-object-sass-loader-ha)
1. Seeing how all config examples in this issue use the `oneOf` rule to allow using both `<style> and <style module>`, setting up Storybook for a project that uses css modules and vanilla css interchangeably may be a common usecase. I noticed there's an undocumented `options.rule` option in `preset-scss`: https://github.com/storybookjs/presets/blob/0ad1358dbdb515a0f6c1c78fa65c375ea1f8f87c/packages/preset-scss/index.js#L20 . It may be worth adding to the docs that you can put the oneOf rule there and pasting one of our webpack configs
1. Adding a section about how to troubleshoot class="" - I don't know Webpack enough to understand where to look in the dist to understand why this is happening, so I can't write anything meaningful. Things I've tried:  
    - Comparing webpack configs side by side `vue inspect > vue-webpack-config.log` and `npx start-storybook --loglevel silly --debug-webpack > storybook-webpack-config.log` (You can also do that in my repro case repo). In 'storybook-webpack.config.log' in the 'preview webpack config' section you can see that it storybook for it's own css module.rules uses this:
```js
      {
        test: /\.css$/,
        sideEffects: true,
        use: [
          '/home/artur/dev/storybook-is9297/node_modules/@storybook/core/node_modules/style-loader/dist/cjs.js',
          {
            loader: '/home/artur/dev/storybook-is9297/node_modules/@storybook/core/node_modules/css-loader/dist/cjs.js',
            options: { importLoaders: 1 }
          },
```
but the rule added by us at the end uses
```js
      {
        test: /\.scss$/,
        oneOf: [
          {
            resourceQuery: /module/,
            use: [
              'vue-style-loader',
              {
                loader: 'css-loader', //not absolute path, so uses root css-loader in package.json
                options: { modules: { localIdentName: '[name]-[hash]' } }
              },
              'sass-loader'
            ]
          },
          { use: [ 'vue-style-loader', 'css-loader', 'sass-loader' ] }
        ]
      }
```

**Comment by gretchelin** [comment]
I recently face this problem and unfortunately none of the suggestion above worked for me as is. The idea is correct, but I had to copy the vue-cli actual webpack config implementation for the css rule to make this work instead of using the one shown by pocka or other users above. For people who face the same problem, this is what works for me:

1. Run `vue-cli-service inspect > output.js` 
this will print out the webpack config vue actually uses. Refer to this [official guide] (https://cli.vuejs.org/guide/webpack.html#modifying-options-of-a-plugin) ). Doing this will make sure the rules used by storybook is the one used by vue itself. 

2. Look for the css rule from the file and copy pasted the whole css rule to storybook webpack config `module.rule`. 
At the time of this post, this is what the complete css rule look like
```
/* config.module.rule('css') */
      {
        test: /\.css$/,
        oneOf: [
          /* config.module.rule('css').rule('vue-modules') */
          {
            resourceQuery: /module/,
            use: [
              {
                loader: 'vue-style-loader',
                options: {
                  sourceMap: false,
                  shadowMode: false
                }
              },
              {
                loader: 'css-loader',
                options: {
                  sourceMap: false,
                  importLoaders: 2,
                  modules: {
                    localIdentName: '[name]_[local]_[hash:base64:5]'
                  }
                }
              },
              {
                loader: 'postcss-loader',
                options: {
                  sourceMap: false
                }
              }
            ]
          },
          /* config.module.rule('css').rule('vue') */
          {
            resourceQuery: /\?vue/,
            use: [
              {
                loader: 'vue-style-loader',
                options: {
                  sourceMap: false,
                  shadowMode: false
                }
              },
              {
                loader: 'css-loader',
                options: {
                  sourceMap: false,
                  importLoaders: 2
                }
              },
              {
                loader: 'postcss-loader',
                options: {
                  sourceMap: false
                }
              }
            ]
          },
          /* config.module.rule('css').rule('normal-modules') */
          {
            test: /\.module\.\w+$/,
            use: [
              {
                loader: 'vue-style-loader',
                options: {
                  sourceMap: false,
                  shadowMode: false
                }
              },
              {
                loader: 'css-loader',
                options: {
                  sourceMap: false,
                  importLoaders: 2,
                  modules: {
                    localIdentName: '[name]_[local]_[hash:base64:5]'
                  }
                }
              },
              {
                loader: 'postcss-loader',
                options: {
                  sourceMap: false
                }
              }
            ]
          },
          /* config.module.rule('css').rule('normal') */
          {
            use: [
              {
                loader: 'vue-style-loader',
                options: {
                  sourceMap: false,
                  shadowMode: false
                }
              },
              {
                loader: 'css-loader',
                options: {
                  sourceMap: false,
                  importLoaders: 2
                }
              },
              {
                loader: 'postcss-loader',
                options: {
                  sourceMap: false
                }
              }
            ]
          }
        ]
      },
```

3. Re run storybook and now `<style module>` will work just fine.


**NOTE**: as the goal is to **_replace_** the css rule the storybook uses, make sure if you extend the existing rules, you exclude the original css rule! The code @pocka shown here helped do the job: 

>     const isCssRule = rule =>
>       rule.test && rule.test instanceof RegExp && rule.test.test("./file.css");
>
