### ISSUE TITLE
addon-knobs tab groups do not support horizontal scrolling on the panel

### ISSUE THREAD

**Issue by christiancooksponge** [storybookjs/storybook#9299]
**Describe the bug**
When there are too many groups for the knobs addon, the tabs flow off the edge of the container. The user is then unable to scroll horizontally to see the hidden tab groups.

**To Reproduce**
1. Create multiple tab groups for knobs so it exceeds the panel width
2. Try and horizontally scroll the tabs

**Expected behavior**
Horizontal scrolling behaviour should be present on the group tabs, much like the tabs for the addons bar above.

**Screenshots**
![image](https://user-images.githubusercontent.com/53049564/71670543-162b3300-2d68-11ea-9651-3a5e9ff041a9.png)

In this screenshot, the addon tabs scroll correctly when there are more addons added, however the tabs for the knobs addon below do not scroll.

**Comment by baker-travis** [comment]
I took a stab at fixing this one in the PR above. Just added a line of css to allow overflow on the container.

**Comment by shilman** [comment]
Yo-ho-ho!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-alpha.2 containing PR #9383 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

**Comment by christiancooksponge** [comment]
@baker-travis @shilman thank you both for your contributions to getting this issue resolved... I will upgrade and give it a whirl!
