### ISSUE TITLE
Addon Docs: dark mode toggle

### ISSUE THREAD

**Issue by smollweide** [storybookjs/storybook#9301]
**Is your feature request related to a problem? Please describe.**
While implementing a design system which supports dark mode it's not yet possible to toggle into the dark mode in docs. I added a toggle for each single story which works fine in Canvas but don't work in docs because a story is not an iFrame there.

**Describe the solution you'd like**
A Quite good example on how this could look like is the [Zeit design system](https://zeit.co/design)

**Comment by smollweide** [comment]
I tried to solve it by creating a custom switch in a portal in `.storybook/config.js`.

And than override the background :

```tsx
addDecorator((story, options) => {
  const [dark, setDark] = useState(false);
  return (
    <Fragment>
      <Global
        styles={css`
          .sbdocs-content > div[id^='anchor--'] > div {
            background: ${dark ? '#000' : '#fff'} !important;
          }
        `}
      />
      <SwitchDarkMode checked={dark} onChange={() => setDark(!dark)} />
    </Fragment>
  );
});
```

With this approach each story has the dark mode but storybook itself stays in the chosen theme. My idea to solve also this part would be like this:

```tsx
addDecorator((story, options) => {
  const [dark, setDark] = useState(false);

  useEffect(() => {
    addParameters({
      options: {
        theme: dark ? themes.dark : themes.normal,
      },
    });
  }, [dark]);

  return (
    <Fragment>
      <Global
        styles={css`
          .sbdocs-content > div[id^='anchor--'] > div {
            background: ${dark ? '#000' : '#fff'} !important;
          }
        `}
      />
      <SwitchDarkMode checked={dark} onChange={() => setDark(!dark)} />
    </Fragment>
  );
});
```
But this is not working.

**Comment by smollweide** [comment]
Some UI inspiration :)

<img width="208" alt="2020-01-04_0920" src="https://user-images.githubusercontent.com/2912007/71804831-f005db80-3064-11ea-921a-ff81f45f2f71.png">

**Comment by connor-baer** [comment]
Does this [Storybook darkmode addon](https://github.com/hipstersmoothie/storybook-dark-mode) solve your issue? 

You can integrate it with your own theme provider or however else you apply the dark mode.

**Comment by angelolucas** [comment]
It would be interesting if the Docs toggle to dark mode along with the Storybook.

![image](https://user-images.githubusercontent.com/828776/79227375-2b6b2f80-7e36-11ea-8eaa-afa01da711df.png)

**Comment by jayarjo** [comment]
@connor-baer @angelolucas `storybook-dark-mode` doesn't affect `@storybook/addon-docs` in any way. The rest toggles dark/light as expected I guess.

**Comment by keemor** [comment]
So there's no way to integrate toggle with Docs https://stackoverflow.com/a/67365473/343900 ?

**Comment by keemor** [comment]
I found solution here https://github.com/hipstersmoothie/storybook-dark-mode/issues/127#issuecomment-1070524402
