### ISSUE TITLE
MDX linking should allow external link without target="_blank"

### ISSUE THREAD

**Issue by patricklafrance** [storybookjs/storybook#9302]
**Is your feature request related to a problem? Please describe.**
Currently, when an MDX anchor doesn't have the target="_blank" attribute, MDX will prepend the manager iframe hostname to the URL. This means, that it's impossible to open an external url in the same tab.

This feature is in place to facilitate linking to another story without requiring users to specify absolute URL.

**Describe the solution you'd like**
The hostname could be prepend if the URL is relative or absolute with the same host as the manager iframe.

**Comment by patricklafrance** [comment]
@shilman did you fix this in 5.3?

**Comment by shilman** [comment]
I might have. Can you verify? It all came together pretty quick at the end.

**Comment by patricklafrance** [comment]
Yes it's fixed, great success @shamin :)
