### ISSUE TITLE
Security vulnerability found in @storybook/react > @storybook/core > shelljs

### ISSUE THREAD

**Issue by yingzuo** [storybookjs/storybook#9304]
**Describe the bug**
npm audit security report shows a moderate vulnerability found in shelljs. 

**To Reproduce**
Version on package.json: "@storybook/react": "^5.3.0-rc.7",
Run `npm audit` and it reports this issue:

Moderate      │ Command Injection
Package       │ shelljs
Dependency of │ @storybook/react [dev]
Path          │ @storybook/react > @storybook/core > shelljs

**Expected behavior**
Clear security report

**Comment by bostanio** [comment]
I can't reproduce. From a blank npm project just with just a @storybook/react: 5.3.0-rc.7 dependency `npm audit` does not report issues. This means we're not requiring a version with a problem but likely something specific to your environment. Most likel you are npm locked to a old version of the offending package which you could just upgrade.

**Comment by jamie-sanger** [comment]
I just upgraded from storybook 5.2.8 -> 5.3.14, and am getting this issue too.

Also seen it identified in snyk
https://snyk.io/test/npm/@storybook/cli

Have tried removing node_modules, package-lock and clearing npm cache with fresh install, same issue.
Snippet of audit:
`  Patched in      >=4.0.0                                                       
                                                                                
  Dependency of   @storybook/cli [dev]                                          
                                                                                
  Path            @storybook/cli > pkg-add-deps > libnpm > lock-verify >        
                  @iarna/cli > yargs > os-locale > mem  `
