### ISSUE TITLE
Security vulnerability found in npm dependency open

### ISSUE THREAD

**Issue by yingzuo** [storybookjs/storybook#9305]
Describe the bug
npm audit security report shows a high vulnerability found in npm package open.

To Reproduce
Version on package.json: "@storybook/react": "^5.3.0-rc.7",
Run npm audit and it reports this issue:

High │ Arbitrary Command Injection
Package │ open
Dependency of │ @storybook/react [dev]
Path │ @storybook/react > @storybook/core > react-dev-utils > open

Expected behavior
Clear security report

Additional information:
$ npm -v
6.13.4

**Comment by bostanio** [comment]
This feels like a very similar issue as #9304. If there are specific details and reproduction steps please add to that ticket.
