### ISSUE TITLE
Clicking on showcode in docs tab directs to just plain background.

### ISSUE THREAD

**Issue by Zunaib** [storybookjs/storybook#9309]
**Describe the bug**
whenever i shift to the docs tab and click showcode button to view sourcecode. It falls apart and shows me plain screen instead of any code.

**Expected behavior**
When showcode is to be clicked, the sourcecode should be displayed.

**Screenshots**
## Before Clicking Show Code 
![2020-01-03_12-39](https://user-images.githubusercontent.com/25710588/71712224-2bff2d80-2e26-11ea-9d62-1c42b4038077.png)
## After Clicking Show Code
![2020-01-03_12-39_1](https://user-images.githubusercontent.com/25710588/71712237-37eaef80-2e26-11ea-8f99-b22e3e28d81d.png)

# Setup
i'm currently on rc.7 and everything is up to date.

**System:**
Environment Info:
  System:
    OS: Linux 5.4 Fedora 31 (Workstation Edition) 31 (Workstation Edition)
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 13.5.0 - ~/.nvm/versions/node/v13.5.0/bin/node
    npm: 6.13.4 - ~/.nvm/versions/node/v13.5.0/bin/npm
  Browsers:
    Chrome: 79.0.3945.88
    Firefox: 71.0

**Comment by shilman** [comment]
Not seeing this, can you share a reproduction repo?

**Comment by Zunaib** [comment]
Its a private repo. let me make a little example one.
I'll get back to this soon.
