### ISSUE TITLE
Addon-docs: GlobalStyles rendered multiple times

### ISSUE THREAD

**Issue by smollweide** [storybookjs/storybook#9312]
**Describe the bug**
Following the documentation for [adding global styles](https://www.learnstorybook.com/design-systems-for-developers/react/en/build/) to storybook ends up with multiple global style tags because each story on a docs page creates one instance of the global style. This issue is only related to the docs pages not canvas!

**To Reproduce**
1. Create a storybook with addon-docs
2. Create a component with multiple stories
3. Add global styles (see Code snippets -> .storybook/config)
3. Click on docs tab 
4. Inspect dom. You will see the global style tag is rendered once per story
5. Switch the stories within the current docs page -> clicks x stories = rendered global style tags

**Expected behavior**
Global tags should be rendered once per docs page

**Screenshots**
<img width="1239" alt="2020-01-03_1235" src="https://user-images.githubusercontent.com/2912007/71723680-da5aa100-2e2d-11ea-9bd6-1ea7ec4d6d9f.png">

**Code snippets**

*.storybook/config*
```jsx
/** @jsx jsx */
import { css, jsx, Global } from '@emotion/core';
import { addDecorator } from '@storybook/react';

// https://www.learnstorybook.com/design-systems-for-developers/react/en/build/
addDecorator((story) => {
  return (
    <Fragment>
      <Global
        styles={css`
          body { background: purple; }					
	`}
      />
      {story()}
    </Fragment>
  );
});
```

**System:**
```
Environment Info:

  System:
    OS: macOS Mojave 10.14.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 12.14.0 - /usr/local/bin/node
    Yarn: 1.19.2 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 79.0.3945.88
    Firefox: 71.0
    Safari: 13.0.3
  Storybook:
    @storybook/react: 5.2.8
    @storybook/addon-docs: 5.2.8
```

**Comment by smollweide** [comment]
I was able to solve this issue by adding the following workaround:

*.storybook/config*
```jsx
/** @jsx jsx */
import { css, jsx, Global } from '@emotion/core';
import { addDecorator } from '@storybook/react';

// https://www.learnstorybook.com/design-systems-for-developers/react/en/build/
addDecorator((story) => {
  const searchArr = window.parent.location.search.split('/');
  // prevent render multiple global styles in addon-docs
  const shouldRenderGlobalStyles = searchArr[searchArr.length - 1] === options.id;
  return (
    <Fragment>
      {shouldRenderGlobalStyles && <Global
        styles={css`
          body { background: purple; }					
	`}
      />}
      {story()}
    </Fragment>
  );
});
```

So maybe it's enough to update the documentation.
What do you think?

Btw. thanks a lot for the new Storybook. I'm using storybook for a while and the new version is just amazing 😉

**Comment by shilman** [comment]
Hey @smollweide sorry I missed this the first time around! Another workaround would be to render each story in an iframe, using `inline={false}`, but that comes with its own performance issues.

**Comment by smollweide** [comment]
Hi @shilman,
thank you that is good to know.

**Comment by smollweide** [comment]
Hi @shilman,
is `inline={false}` now available?
If so where can I find the docs for it?

**Comment by shilman** [comment]
Docs need improving but it's described here https://github.com/storybookjs/storybook/blob/master/addons/docs/web-components/README.md#stories-not-inline
