### ISSUE TITLE
Unexpected Token (with JSX syntax)

### ISSUE THREAD

**Issue by rexkenley** [storybookjs/storybook#9335]
**Describe the bug**
SyntaxError: Unexpected token 

**To Reproduce**
.jest\register-context.js
`import registerRequireContextHook from "babel-plugin-require-context-hook/register";
registerRequireContextHook();`

.storybook\addons.js
`import "@storybook/addon-actions/register";`

.storybook\config.js
`import { configure } from "@storybook/react";
import { configureActions } from "@storybook/addon-actions";

const req = require.context("../stories", true, /\.stories\.js$/);
function loadStories() {
  req.keys().forEach(filename => req(filename));
}
configure(loadStories, module);

configureActions({
  depth: 100,
  limit: 20
});
`

jest.config
`module.exports = {
  setupFiles: ["<rootDir>/.jest/register-context.js"],
  transform: {
    "^.+\\.jsx?$": ["babel-jest", { presets: ["@babel/preset-env"] }]
  }
};`
package.json
`"babel": {
    "env": {
      "test": {
        "plugins": [
          "require-context-hook"
        ]
      }
    }
  },`

**GitHub repository**
https://github.com/rexkenley/d365DatetimeBox

**Screenshots**
![image](https://user-images.githubusercontent.com/10548251/71841404-50a90e80-308d-11ea-89b3-7fc9c18ef12f.png)

**System:**
System:
    OS: Windows 10 10.0.18363
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
  Binaries:
    Node: 13.1.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.12.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0

**Comment by shilman** [comment]
Do you need https://babeljs.io/docs/en/babel-preset-react

**Comment by rexkenley** [comment]
Thank you shilman, that solved it. But now I get a new error

![image](https://user-images.githubusercontent.com/10548251/71895342-ca3d0d00-311e-11ea-8e15-47355e146dba.png)

**Comment by rexkenley** [comment]
@shilman Thanks for your help. I am closing this issue as resolved.

**Comment by markjackson02** [comment]
Per storybook docs, you may need to create the .babelrc inside your .storybook folder https://storybook.js.org/docs/configurations/custom-babel-config/
