### ISSUE TITLE
Writing addons for Storybook Angular

### ISSUE THREAD

**Issue by ibnYusrat** [storybookjs/storybook#9339]
Hi,

I was reading this document about writing Addons for storybook: https://storybook.js.org/docs/addons/writing-addons/

Is this guide actually valid for Storybook Angular also? I see mentioning of react pretty much everywhere in storybook. I have to write an addon for Storybook Angular but am completly clueless here.

**Comment by shilman** [comment]
Most addons live entirely within the `manager`, which is the UI that wraps the user's components (which are rendered in the `preview` iframe). The manager is written in react, and the APIs are mostly framework-independent. The only angular-specific docs you need are if you want to modify the preview, and AFAIK those docs don't exist. However `addon-centered` and `addon-knobs` are example addons that modify the preview.
