### ISSUE TITLE
build-storybook ignores custom theme settings

### ISSUE THREAD

**Issue by ivomynttinen** [storybookjs/storybook#9341]
**Describe the bug**
I've set up a custom theme as described here https://storybook.js.org/docs/configurations/theming/#create-a-theme-quickstart which works well so far. However, when building a static version of storybook to host on guthub pages, the custom theme is entirely ignored. This is kinda critical in my opinion, since theming is especially important for public available storybooks.

**To Reproduce**
1. Create custom theme file
2. yarn build-storybook

**Expected behavior**
All custom theme properties should get compiled and included in the static build.

**Screenshots**

**Code snippets**
Theme file for example:

```
import { create } from '@storybook/theming';

export default create({
  base: 'light',

  colorPrimary: '#282C31',
  colorSecondary: '#1883FE',

  // UI
  appBg: '#F7F7F9',
  appContentBg: '#FFF',
  appBorderColor: '#E1E5EA',
  appBorderRadius: 5,

  // Typography
  fontBase: '-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol',
  fontCode: 'SFMono-Regular,Consolas,Liberation Mono,Menlo,Courier,monospace',

  // Text colors
  textColor: '#282C31',
  textInverseColor: 'rgba(255,255,255,0.9)',

  // Toolbar default and active colors
  barTextColor: '#939598',
  barSelectedColor: '#1883FE',
  barBg: '#FFF',

  // Form colors
  inputBg: '#FFF',
  inputBorder: '#E1E5EA',
  inputTextColor: '#282C31',
  inputBorderRadius: 3,

  brandTitle: 'everchron shards'
});
```

**System:**
npmPackages:
    @storybook/addon-actions: ^5.3.0-beta.14 => 5.3.0-beta.14
    @storybook/addon-docs: ^5.3.0-beta.14 => 5.3.0-beta.14
    @storybook/addon-info: ^5.3.0-beta.14 => 5.3.0-beta.14
    @storybook/addon-knobs: ^5.3.0-beta.14 => 5.3.0-beta.14
    @storybook/addon-links: ^5.3.0-beta.14 => 5.3.0-beta.14
    @storybook/addon-notes: ^5.3.0-beta.14 => 5.3.0-beta.14
    @storybook/addons: ^5.3.0-beta.14 => 5.3.0-beta.14
    @storybook/vue: ^5.3.0-beta.14 => 5.3.0-beta.14

**Comment by shilman** [comment]
Lots of static storybooks using theming. Can you share a repro?

**Comment by ivomynttinen** [comment]
You can pull my repo (I just remove basically all the components and stories since this shouldn't be public, but result is the same) here: https://github.com/ivomynttinen/storybook-example

### local version `yarn storybook`

This is how it should look like:

![image](https://user-images.githubusercontent.com/1096989/71898294-8af8d580-318b-11ea-9ad5-31f2618aa51f.png)

### Static version `yarn build-storybook`

everchronTheme.js theme file is ignored, however manager-head styles are included.

![image](https://user-images.githubusercontent.com/1096989/71898379-bd0a3780-318b-11ea-8176-2cd946a7cadb.png)

**Comment by ivomynttinen** [comment]
Solved the issue, just fyi if anyone has the same problem as me, this is what I did:

Before I had an external theme file, as described in the storybook documentation. I moved the content of the theme file directly into the main .config file like this:

```
...
import { create } from '@storybook/theming';

const theme = create({
  base: 'light',

  colorPrimary: '#282C31',
  colorSecondary: '#1883FE',
})
...
```

This way the theme is included correctly when creating a static version.

**Comment by MrWittman612** [comment]
this does not work for me either and I don't see a . config file any were
