### ISSUE TITLE
New config test for `register` add ons

### ISSUE THREAD

**Issue by atanasster** [storybookjs/storybook#9343]
**Describe the bug**

using a `register` file in the add ons section generates a console error:
```
ERR! Addon value should end in /register OR it should be a valid preset https://storybook.js.org/docs/presets/introduction/
ERR! /Users/atanasster/storybook-addon-deps/dist/register.js
```

**To Reproduce**

```
module.exports = {
  addons: [require.resolve('./register')],
}  
```

**Comment by shilman** [comment]
Hurrah!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-rc.12 containing PR #9347 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by RuneKR** [comment]
Hi. The solution does not work on a MacBook. Regex fails for absolute paths such as /User/Rune/some/nested/@at/here/register.js

**Comment by shilman** [comment]
Yippee!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.4 containing PR #9485 that references this issue. Upgrade today to try it out!
