### ISSUE TITLE
Addon-docs: CORS issues on Standalone server

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#9348]
When `manager`/`preview` run on different ports or domains, it triggers a CORS issue due to some hacked up preview code.

This commit patches over the issue: https://github.com/storybookjs/storybook/pull/9250/commits/c8faee0ac08f8e01acf330452fc115eaf1caf670

However, a superior fix would be to use the channel that we already have available to allow the `preview` to post an event to the `manager` to ask it to set the anchor in the URL.

**Comment by atanasster** [comment]
How can I reproduce this?

**Comment by shilman** [comment]
Repro: Run standalone mode with docs enabled 

https://github.com/storybookjs/storybook/pull/7848

**Comment by atanasster** [comment]
should be fixed in rc13
