### ISSUE TITLE
Configuring Storybook dynamically

### ISSUE THREAD

**Issue by lordofthelake** [storybookjs/storybook#9349]
**Is your feature request related to a problem? Please describe.**
As mentioned [on Twitter](https://twitter.com/vacooom/status/1214569358472699905) to @shilman, as part of the work that we're doing at [Compositive](https://compositive.design/), we're trying to integrate Storybook with our CLI toolbelt: the vision would be that it would be possible to spin (or build) an instance of Storybook programmatically, that is zero-configuration for the user and that comes with parameters that a generated on the fly by our tool, without relying on having a directory with configuration files on the disk.

**Describe the solution you'd like**
Ideally, it would be possible to invoke Storybook as a library function and pass to it one or more configuration objects instead of loading the files from disk.

**Describe alternatives you've considered**
One workaround would be to generate the configuration files, write them to a temporary directory and point Storybook to it. But it feels like a very dirty and convolute hack, probably with unwanted side effects about path resolutions, module loading, etc.

**Are you able to assist bring the feature to reality?**
Yes, I would love to help, but I will need some onboarding about how the configuration flow works in Storybook right now.

**Comment by BPScott** [comment]
Over at Shopify we follow a similarish approach where most of our CLI tools (builds, running tests, linting etc) are centralised into a single entrypoint "sk" (e.g. `sk build` runs a build using webpack under the hood, `sk test` runs jest under the hood, etc).

We're interested in adding storybook to that swiss army knife, and would also appreciate this feature too.

**Comment by shilman** [comment]
cc @ndelangen

**Comment by BPScott** [comment]
Oi stalebot, I wanna keep this fresh

**Comment by ndelangen** [comment]
Hey, let's meet and discuss?

I can show you around the codebase, and exchange ideas on how to make this happen?

https://calendly.com/ndelangen/storybook
