### ISSUE TITLE
[addon-docs] Notes with multiple sections are not rendered

### ISSUE THREAD

**Issue by jcfranco** [storybookjs/storybook#9350]
**Describe the bug**

If a story using `addon-notes` [is configured with multiple sections](https://github.com/storybookjs/storybook/tree/master/addons/notes#multiple-notes-sections), the `Docs` tab does not display any content from notes.

**Expected behavior**

Each note section is rendered under the `Docs` tab.

**Screenshots**

**Code snippets**

```ts
export default {
  title: "no notes under docs tab",
  parameters: {
    notes: { 
      section: "# This is NOT rendered"
    }
  }
};
```

<img width="1274" alt="Screen Shot 2020-01-07 at 2 14 47 PM" src="https://user-images.githubusercontent.com/197440/71933996-4869d580-3158-11ea-97a7-5e67f192540d.png">

```ts
export default {
  title: "this works fine",
  parameters: {
    notes: "# Works fine"
  }
};
```

<img width="1242" alt="Screen Shot 2020-01-07 at 2 12 19 PM" src="https://user-images.githubusercontent.com/197440/71934002-4b64c600-3158-11ea-83fd-ef6a66850167.png">

**System:**

```
Environment Info:

  System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Binaries:
    Node: 13.3.0 - /usr/local/bin/node
    npm: 6.12.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 79.0.3945.88
    Firefox: 71.0
    Safari: 13.0.4
  npmPackages:
    @storybook/addon-backgrounds: 5.2.8 => 5.2.8
    @storybook/addon-centered: 5.2.8 => 5.2.8
    @storybook/addon-docs: 5.2.8 => 5.2.8
    @storybook/addon-knobs: 5.2.8 => 5.2.8
    @storybook/addon-notes: 5.2.8 => 5.2.8
    @storybook/html: 5.2.8 => 5.2.8
```

**Comment by shilman** [comment]
@jcfranco I think you're confusing `addon-notes` and `addon-docs`

**Comment by jcfranco** [comment]
@shilman Sorry for the belated response. 

>  I think you're confusing addon-notes and addon-docs

No, I _am_ referring to both addons. 😄 We haven't migrated 100% to `@addon/docs`, so we have both configured in our project (here's a [test-case repo](https://github.com/jcfranco/storybook-repro-case-9350) showing the issue)

As a workaround, we're using `extractComponentDescription` to handle this case:

```ts
extractComponentDescription: (_component, { notes }) => {
  if (notes) {
    if (typeof notes === "string") {
      return notes;
    }

    return Object.keys(notes)
      .map((section) => notes[section])
      .join("\n");
  }

  return null;
}
```

**Comment by shilman** [comment]
@jcfranco Aha! Sorry for the misunderstanding. Glad you figured it out! 💯
