### ISSUE TITLE
Can't change knobs when material-ui dialog is open

### ISSUE THREAD

**Issue by artem7902** [storybookjs/storybook#9352]
**Describe the bug**
Hello everyone. Just have a bug with knob addon. Fields lost focus immediately after click so that I can't change knobs. It happens only with material-ui Dialog.  Please look at the screenshot below. Thanks a lot for your help.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/26010756/71940926-c366d680-31c0-11ea-9053-5772b5b00f92.gif)

**Comment by aryyya** [comment]
This doesn't just affect the knob addon, it also stops other input fields on the page from working. Try using the Storybook sidebar search and you will notice the same behaviour.

You can use the `disableEnforceFocus` prop on the Material UI `<Dialog />` component to prevent this from happening.
