### ISSUE TITLE
Include option in default webpack config breaks Lerna projects

### ISSUE THREAD

**Issue by JDansercoer** [storybookjs/storybook#9357]
In the default Storybook webpack config, the `include` option for the `js` rule is set to the directory of the project.

We recently ran into some issues. In our stories, we were including a React component from one of our other packages in the repo. When trying to run Storybook, we would run into an `unexpected token` error, complaining about the `<` character in our React files.

After digging around into why this file wasn't being transpiled by Babel, I noticed that the `include` option is explicitly set to the folder where Storybook is installed. But, since the included files from my other package were included relatively, they were not transpiled.

Overriding the Storybook config and effectively `delete`ing the `included` key of the js rule made Storybook work again.

Is this include option intentional? If so, why?

**To Reproduce**
1. Start a new Storybook project
2. Run Storybook with `--debug-webpack`
3. Check for the presence of the `include` option in the `js(x)` rule

**Expected behavior**
Not entirely sure why the `include` option is explicitly set.

**System:**
  System:
    OS: Windows 10 10.0.18362
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
  Binaries:
    Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.17.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD

**Comment by JDansercoer** [comment]
Well, it's inactive because there's no answer..

**Comment by shilman** [comment]
cc @ndelangen

**Comment by ndelangen** [comment]
This is fixed in 6.0.0
