### ISSUE TITLE
preview-head.html not working with <noscript />

### ISSUE THREAD

**Issue by ifndefdeadmau5** [storybookjs/storybook#9363]
**Describe the bug**
I was following this guide(https://storybook.js.org/docs/configurations/add-custom-head-tags/)
and when I did, storybook UI were not loaded without any explicit errors

**To Reproduce**
Add 'preview-head.html' under `.storybook` with below code
```html
<noscript id="jss-insertion-point" />
```
**Expected behavior**
Storybook UI should inject custom tag and working properly

**Screenshots**
![image](https://user-images.githubusercontent.com/8914311/72031646-59d5ed80-32d0-11ea-820c-4a09bddeaf41.png)

**System:**
 System:
    OS: macOS 10.15.2
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
  Binaries:
    Node: 12.9.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.10.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 79.0.3945.88
    Safari: 13.0.4
  npmPackages:
    @storybook/addon-actions: ^5.2.8 => 5.2.8
    @storybook/addon-links: ^5.2.8 => 5.2.8
    @storybook/addon-storyshots: ^5.2.8 => 5.2.8
    @storybook/addons: ^5.2.8 => 5.2.8
    @storybook/react: ^5.2.8 => 5.2.8

**Comment by dzwillia** [comment]
This issue still exists.

If you add `manager-head.html`, that file is injected when building the docs, but if you add `preview-head.html`, that file is not injected into the docs. Using `manager-head.html` is not ideal, however,  as it will also affect the non-docs view.

**Comment by shilman** [comment]
@dzwillia any interest in contributing a fix?

**Comment by dzwillia** [comment]
@shilman Can't commit on this in the short term, but I may have a window to take a look at it in a couple of weeks. I'll see what I can do.

**Comment by parash-namespace** [comment]
`preview-body` seems to work rather than `preview-head` with version 6.0.26. `preview-body` fixed it for me.
