### ISSUE TITLE
CSF referenced in MDX does not work the expected way in Docs mode

### ISSUE THREAD

**Issue by jorenbroekema** [storybookjs/storybook#9366]
**Describe the bug**

When viewing a CSF that is imported in MDX by the use of `<Story id="yourID" />`, a strange Docs view is shown when clicking on the CSF story in the Storybook UI.

**To Reproduce**

1) Create an .mdx (using @open-wc/demoing-storybook + es-dev-server but this is essentially just re-exports made to work without a build/compile step, don't worry about them, you can import from `@storybook/docs-addon/blocks` directly with your own preferred way e.g. using webpack):
```js
import { Meta, Story, html } from '@open-wc/demoing-storybook';

<Meta title="Bug Repro" />

# Bug Repro

Hello there, this is a bug reproduction.

Sup..

<Story name="Default">
  {html`
    <div>Sup Planet</div>
  `}
</Story>

Some text

<Story id="bug-repro--hello-world" />
```

And then create a demo.stories.js with CSF:

```js
export default {
  title: 'Bug Repro',
};

export const helloWorld = () => {
  const myNode = document.createElement('div');
  myNode.innerHTML = 'Hello, World!';
  myNode.style.color = 'red';
  return myNode;
};
```

Start storybook, and click on "default" and go into docs mode (not canvas). Everything looks great! 

<img width="526" alt="Screenshot 2020-01-09 at 11 49 48" src="https://user-images.githubusercontent.com/36734656/72063094-66127880-32d9-11ea-9160-5b0a67e75e6a.png">

Now click on "Hello World" and note that you get a very weird docs view, while the expectation is to get the exact same view (it should only scroll down to the hello world story, which is already in view): 

<img width="858" alt="Screenshot 2020-01-09 at 11 49 56" src="https://user-images.githubusercontent.com/36734656/72062326-e0da9400-32d7-11ea-9d5a-69ce8c3b7e3f.png">

The only thing visible are the two Story's and suddenly they are wrapped in Preview which we never specified. And all of the markdown text is missing now...?

**Expected behavior**
Precisely the same view in docs mode when clicking the MDX story as when clicking the CSF story.

**System:**
```
System:
    OS: macOS Mojave 10.14.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 13.3.0 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.10.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 79.0.3945.88
    Safari: 13.0.4
  npmPackages:
    @storybook/addon-a11y: ~5.0.0 => 5.0.11 
```

**Further Thoughts**

It seems to me like CSF imported in MDX e.g. by use of just reference <Story id="someID"/> kind of "works" as a soft reference. E.g. clicking the Story reference in the Storybook sidebar normally will scroll you to the right place in docs mode, but if your Story originates from an external CSF, this feature does not work. 

Is the CSF considered its own thing even if referenced in the MDX? This may explain why suddenly there's a <Preview> element with code snippet wrapped around it, because it only looks at the CSF file.. where a preview element is default? Let me know if I'm thinking in the right direction.

And perhaps someone can tell me if there's another way to import CSF into MDX in a "hard" way, so that it's actually part of the MDX, I assume that will make it work as expected

**Comment by shilman** [comment]
Please see

https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/recipes.md#csf-stories-with-mdx-docs

OR

https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/recipes.md#csf-stories-with-arbitrary-mdx

**Comment by jorenbroekema** [comment]
Ahhh that makes sense, so not a bug then, thanks for pointing me to those docs, currently we have to use external CSF imported inside the MDX because dynamic imports don't work in MDX (MDX-to-JS issue).

I don't have the time to try this, I'm off on vacation for the next week so feel free to close it, I trust both of those documented ways will resolve my issue ;).

**Comment by shilman** [comment]
The CSF/MDX story is still a little wonky. Feel free to re-open later if you want to continue the discussion. In the meantime, have a great vacation!

**Comment by jorenbroekema** [comment]
Since this is still open, I would like to add something.

We have a white label component library that we extend to a design system. Essentially, the white label components have MDX docs to start with already. We then extend those in our internal design system, and we add some extra stories. These extra stories appear under the same section in the sidebar menu (because same meta title) but the DocPages are not merged (which is basically this issue). 

From the docs you linked I can see that I can import the "extra CSF stories" in the MDX to make sure the DocsPage is merged, which is nice and indeed solves my initial issue:
```
import * as stories from './Button.stories.js';
<Story name="basic">{stories.basic()}</Story>
```
But the new problem is that the white label component library MDX and my extra CSF stories don't live in the same repo (MDX comes from the `/node_modules/white-label-component-library` and CSF comes from `/packages/some-extension/stories/index.stories.js`). So it's not easy (not impossible) for me to do this kind of import to ensure the DocsPages are merged.

I think we have a pretty decent use case for saying that it would be really nice if similar meta titled MDX / CSF are merged as a single DocsPage. They already are merged in the sidebar navigation menu. 

Just wondering if you guys agree with me on this ^^

**Comment by shilman** [comment]
@jorenbroekema I think yours is a pretty special use case. Actually Docs is super-configurable to handle cases like this, but through configuration rather than built in:

https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/docspage.md#replacing-docspage

And here are some examples of that:

https://github.com/storybookjs/storybook/blob/next/examples/official-storybook/stories/addon-docs/addon-docs-blocks.stories.js

More work needed for your use case, but this is the direction I'd recommend.
