### ISSUE TITLE
Angular DI broken with storybook and Angular 8+ projects

### ISSUE THREAD

**Issue by kenborge** [storybookjs/storybook#9380]
**Describe the bug**
Components with dependency injection doesn't work in Storybook with new Angular 8+ projects.
They fail with `Can't resolve all parameters for XXX: (?).`

I think i tracked this problem down to a change in the CLI that was introduced with Angular 8.
https://github.com/angular/angular-cli/pull/14473
Angular CLI has moved away from using emitDecoratorMetadata: true and instead have written a transformer that does the same in ngtools. 
New projects generated with Angular CLI are no longer setting the emitDecoratorMetadata property.

Storybook however does not seem to use ngtools for building so the reflect metadata needed for angular dependency injection is missing.

**To Reproduce**
```
1. ng new demo --create-application false --minimal true
2. cd demo/
3. npx -p @storybook/cli sb init --type angular
4. Add a constructor function to src/app/app.component.ts that has some dependency injection like:
 constructor(el: ElementRef) {}
5. Modify src/stories/0-Welcome.stories.ts by swapping component in the story to the AppComponen :
component: AppComponent
6. npm run storybook
```
Observe that Welcome - to Storybook now displays the error :
Can't resolve all parameters for AppComponent: (?).

**Expected behavior**
Components with dependency injection should work in storybook

**Screenshots**
<img width="1048" alt="Screenshot 2020-01-10 at 13 19 50" src="https://user-images.githubusercontent.com/599468/72154704-9cbbc200-33b1-11ea-9b7b-1da90d55fe73.png">

**System:**
Environment Info:

  System:
    OS: macOS 10.15.2
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
  Binaries:
    Node: 12.10.0 - ~/.nodenv/versions/12.10.0/bin/node
    npm: 6.10.3 - ~/.nodenv/versions/12.10.0/bin/npm
  Browsers:
    Chrome: 79.0.3945.117
    Firefox: 71.0
    Safari: 13.0.4
  npmPackages:
    @storybook/addon-actions: ^5.2.8 => 5.2.8
    @storybook/addon-links: ^5.2.8 => 5.2.8
    @storybook/addon-notes: ^5.2.8 => 5.2.8
    @storybook/addons: ^5.2.8 => 5.2.8
    @storybook/angular: ^5.2.8 => 5.2.8

**Additional context**
Manually adding emitDecoratorMetadata to tsconfig fixes the problem. However that doesn't seem like the best idea going forward with Angular moving away from that for good reasons.

**Comment by michaelcamper** [comment]
Same issue here.

A temporary work around would be to explicitly inject dependencies:
```
 constructor(@Inject(ElementRef) el: ElementRef) {}
```

**Comment by anwalkers** [comment]
@shilman Yeah I can add the ```@Inject()``` as a workaround to all of the constructors, but I shouldn't have to. Here is an example of what I am having to deal with. 

```
Unhandled Promise rejection: Can't resolve all parameters for OverflowTooltipDirective: (?, ?, ?, ?, ?, ?, ?, ?, ?, [object Object], ?, [object Object]). ; Zone: <root> ; Task: Promise.then ; Value: Error: Can't resolve all parameters for OverflowTooltipDirective: (?, ?, ?, ?, ?, ?, ?, ?, ?, [object Object], ?, [object Object]).
``` 

I need to add 10 ```@Inject()``` decorators just to support Storybook?? Angular DI has no issues with the current constructor when I run ```ng build```, ```ng test```, and ```ng serve```. Why am I having to add all of these just for Storybook?

**Comment by kenborge** [comment]
@anwalkers you can temporarily set emitDecoratorMetadata instead of adding inject to everything, unless you are affected by any of the problems that caused them to move away from using it
