### ISSUE TITLE
StoryBook CLI init fails on v5.3.0

### ISSUE THREAD

**Issue by jeffryang24** [storybookjs/storybook#9391]
**Describe the bug**

StoryBook CLI init (`npx -p @storybook/cli sb init --type react_scripts`) did not execute successfully.

**To Reproduce**

1. Initialize a directory with `create-react-app`.
2. Initialize storybook to above directory with `npx -p @storybook/cli sb init --type react_scripts`.
3. See error

**Expected behavior**

StoryBook should be successfully installed.

**Screenshots**

![error](https://user-images.githubusercontent.com/8284757/72205095-b0e6e880-34b1-11ea-8241-2af965392715.png)

**Code snippets**

n/a

**System:**

Can't execute `npx -p @storybook/cli@next sb info` because there is a same error as current issue. But let me summarize it manually.

System: Ubuntu 18.04 LTS x86_64
CPU: Intel i7 8th Generation 8750H - 6 cores 6 threads
Node: Node 12.14.1
Yarn: 1.21.1
NPM: 6.13.6
Chrome: 79.0.3945.117 (Official Build) (64-bit)

**Additional context**

n/a

**Comment by jeffryang24** [comment]
Probably because of `remark-mdx`.

**Comment by shilman** [comment]
@jeffryang24 Not able to reproduce. Can you check your network connection, clear your cache, and try again?

**Comment by jeffryang24** [comment]
Ok, will try to clear cache and use another network connection. :bowing_man:

**Comment by jeffryang24** [comment]
Yes, seems like my home connection is weird today. Just tested with my office VPN and it worked perfectly. Sorry for bothering the weekend. :bowing_man: Case closes... hahaha...
