### ISSUE TITLE
DocsPage Reference link is broken in NPM Readme

### ISSUE THREAD

**Issue by jonasantonelli** [storybookjs/storybook#9393]
**Describe the bug**
It's not possible to go to DocsPage reference using the link in NPM readme

**To Reproduce**
1. Go to https://www.npmjs.com/package/@storybook/addon-docs#docspage
2. Click on _DocsPage reference_ link
3. See error

**Expected behavior**

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System:**
Please paste the results of `npx -p @storybook/cli@next sb info` here.

**Additional context**

**Comment by shilman** [comment]
This is annoying. For now you'll need to click over to the GitHub readme where the link works fine
