### ISSUE TITLE
Document how to add support for a new framework

### ISSUE THREAD

**Issue by p3k** [storybookjs/storybook#9403]
I know RactiveJS is not the most popular framework out there but at least ancestor of Svelte (both written by Rich Harris) and thus, comes with some similarities. And last but not least: I am using it.

So question is: (how) could it be supported by Storybook?

I would be able to assist bringing this feature to reality but first I’d need some pointers how such support needs to be implemented in Storybook to evaluate realization options.

Already looked at the Svelte app but maybe there is a documentation / how-to available?

**Comment by shilman** [comment]
Hey @p3k we don't have any docs on that. I recently helped another contributor with this, and will try to write up a guide this week. I'll post a link here when it's ready.

**Comment by p3k** [comment]
hi @shilman thanks for your reply. some basic pointers and a rough how-to would be appreciated! :cat:

**Comment by p3k** [comment]
any update on this?

**Comment by shilman** [comment]
Work in progress here: https://docs.google.com/document/d/1fe6uCfpr3mzSnj4jN_uoZqVnyNtjBjfOMxt_ZI7ktL8/edit?usp=sharing

**Comment by jonniebigodes** [comment]
Closing this as the documentation is already in place. @p3k thanks for bringing this to our attention.

Stay safe
