### ISSUE TITLE
Addon-docs: Chapter component

### ISSUE THREAD

**Issue by Hramkanvas** [storybookjs/storybook#9404]
Hi, I'd like to have some component like `<Chapter/>` so I can put it above some section name in my .mdx file so I can see it in the sidebar on the left and navigate on it.

For example:

_myComponent.stories.mdx:_

```
imports...

# - myComponent

<Chapter name="Usage"/>
## Usage
...
<Chapter name="Imports"/>
## Imports
...

## Default
<Preview>
<Story name="Default" height="10px">
{...}
</Story>
</Preview>

## Special
<Preview>
<Story name="Special" height="10px">
{...}
</Story>
</Preview>
```

So in the sidebar:
- Usage
- Imports
- Default
- Special

Now, instead of it, I'm using `<Story name="Usage" height="0px"/>`

**Comment by thuringia** [comment]
@shilman Is something like this, or a table of contents feature planned/in the pipeline?
Or is this something we should be addressing in MDX directly, seeing as they lack support for TOCs in general?

**Comment by shilman** [comment]
@thuringia good question and there are a couple of different answers.

If you want a TOC in the body of the docs page, Storybook's MDX is extensible with an API and it should be possible to write something yourself based on your needs. I have some documentation in the works, but have been swamped with other stuff.

Something else we talked about was generating a sidebar navigation hierarchy based on the header structure in the document. The current navigation hierarchy is based on stories. It's something I'd like to do eventually, but is a major architectural change for Storybook and not currently on the roadmap.

**Comment by thuringia** [comment]
@shilman Thanks for the quick response :)

While the second answer sounds much better in terms of developer experience, I'm on board with this not being on the roadmap. Major change doesn't seem worthwhile for this feature at the moment.
Some docs on how to work around this, as in the first one, sound really good though.

Right now, I'm thinking about something like the `:toc:` helper in AsciiDoc. That one should be fairly easy to do with some MDX extension. Maybe even with a one of the new v6 controls or something.

It's not really pressing on my end, so please don't feel pressured.
Meanwhile, I will check if MDX has an issue for this, may as well bump them. Then we wouldn't have to so build this specifically for storybook.

**Comment by hudochenkov** [comment]
@thuringia I just discovered [storybook-docs-toc](https://github.com/frassinier/storybook-docs-toc), while was searching for TOC solution for Storybook. Good starting point. But it doesn't use Storybook or MDX, so it should be styled manually.
