### ISSUE TITLE
Weird re-routing when fixing a bug

### ISSUE THREAD

**Issue by elevatebart** [storybookjs/storybook#9419]
**Describe the bug**
When working on a story and making a mistake, I stay on the story and see the error.
When fixing the error, I get redirected to another page.

**To Reproduce**
Use the repo linked
Open storybook: `yarn storybook`
Open MoreMenu.tsx
Make the component fail somehow
Fix your mistake,
You get redirected to a page

**Screenshots**
![InvalidRouting](https://user-images.githubusercontent.com/5592465/72300302-0396e080-3629-11ea-9547-fab6cd11b658.gif)

**System:**
  System:
    OS: Windows 10 10.0.17763
    CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
  Binaries:
    Node: 10.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.21.1 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.10.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.17763.831.0

**Additional context**
[repro repo](https://github.com/elevatebart/reproduce-storybook)

**Comment by shilman** [comment]
ZOMG!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.3 containing PR #9424 that references this issue. Upgrade today to try it out!

Closing this issue. Please re-open if you think there's still more to do.

**Comment by benmvp** [comment]
@shilman I think this _may_ have caused the bug I've mentioned in #9477. I left some details there...
