### ISSUE TITLE
UI: Navigation sections disappear after 5.3 upgrade

### ISSUE THREAD

**Issue by elevatebart** [storybookjs/storybook#9420]
**Describe the bug**
Upgrading to 5.3 from 5.2.3 made the groupped components of the side menu disapear

**To Reproduce**
Open the repo
Run `yarn storybook`

**Expected behavior**
In a minor version we should not see a feature broken without backwards compatibility features

**Code snippets**
```js
storiesOf("MyComp|02. General/MoreMenu", module)
```
should keep on yielding `MyComp` folder on the left

**System:**
Environment Info:

  System:
    OS: Windows 10 10.0.17763
    CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
  Binaries:
    Node: 10.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.21.1 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.10.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.17763.831.0

**Comment by shilman** [comment]
Jiminy cricket!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.3 containing PR #9425 that references this issue. Upgrade today to try it out!

Closing this issue. Please re-open if you think there's still more to do.
