### ISSUE TITLE
eslint failure on 5.3.1

### ISSUE THREAD

**Issue by zhigang1992** [storybookjs/storybook#9423]
**Describe the bug**
![](https://user-images.githubusercontent.com/1057756/72264612-eb1bcb80-3612-11ea-8057-e3e4d40760f1.png)

**To Reproduce**
> From https://gist.github.com/shilman/bc9cbedb2a7efb5ec6710337cbd20c0c#gistcomment-3135798

```
I think the eslint issue isn't yet fixed.

It won't show up at first, everything works.

After editing any file the error will show up.

It will keep showing up if you edit any other file that is not the one that's being reported.

Then after you edit this reported file, and refresh the error will go away... temporarily until you edit any other file again.

It's a really strange while frustrating problem. :(
```

**System:**

https://github.com/zhigang1992/bug-free-fiesta
https://loom.com/share/2dbe62f73c9c470e83f732a8c9aa381c

**Comment by zhigang1992** [comment]
https://gist.github.com/shilman/bc9cbedb2a7efb5ec6710337cbd20c0c#gistcomment-3136341

@shilman there you go. :)

**Comment by shilman** [comment]
Huzzah!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.3 containing PR #9417 that references this issue. Upgrade today to try it out!

Closing this issue. Please re-open if you think there's still more to do.
