### ISSUE TITLE
EXTEND_ESLINT=true breaks linting (typescript?)

### ISSUE THREAD

**Issue by josias-r** [storybookjs/storybook#9441]
I'm working with Storybook and create-react-app and am using the `@storybook/preset-create-react-app` preset.

W/ react-scripts you need to set the environment variable `EXTEND_ESLINT` to true, to have it recognize the .eslintrc config.

...So I added `EXTEND_ESLINT=true` to my `.env` file, but now I'm getting errors from TSX files.
Weird errors like when using the TypeScript `as` keyword I get a Syntax error, unexpected `;`.

It kinda seems like Typescript files are read as usual js files, but I'm not sure.

... I know that my eslintrc is not correctly loaded, because inside it I have prettier configured i.e, but prettier errors only show up in my editor, not in the storybook runtime.

**Comment by shilman** [comment]
@josias-r Can you file this issue on the presets repo?

https://github.com/storybookjs/presets

**Comment by josias-r** [comment]
@shilman  Ofc, but I don't think it's caused by the preset itself 🤔

**Comment by shilman** [comment]
@josias-r TBH i'm not exactly sure what's going on. But I'd like to consolidate CRA-related issues around that preset package as much as possible.
