### ISSUE TITLE
How to render stories to individual HTML files?

### ISSUE THREAD

**Issue by kalinchernev** [storybookjs/storybook#9455]
## Versions

- `@storybook/addon-a11y`: 5.2.8,
- `@storybook/addon-cssresources`: 5.2.8,
- `@storybook/addon-knobs`: 5.2.8,
- `@storybook/addon-options`: 5.2.8,
- `@storybook/addon-viewport`: 5.2.8,
- `@storybook/addons`: 5.2.8,
- `@storybook/react`: 5.2.8,
- `@storybook/theming`: 5.2.8,

Hello, I'm looking for a way to provide rendered HTML files for each story defined withing a project.

The current syntax is [`StoriesOf`](https://storybook.js.org/docs/formats/storiesof-api/), for example:

```jsx
/* eslint-disable import/no-extraneous-dependencies */
import React from 'react';
import { storiesOf } from '@storybook/react';
import { withKnobs, text } from '@storybook/addon-knobs';
import StoryWrapper from '@ecl/story-wrapper';
import demoContent from '@ecl/ec-specs-accordion2/demo/data';

import { Accordion2 } from '../src/Accordion2';
import { Accordion2Item } from '../src/Accordion2Item';

storiesOf('Components|Accordion', module)
  .addDecorator(withKnobs)
  .addDecorator(story => (
    <StoryWrapper
      afterMount={() => {
        if (!window.ECL) return {};

        const components = window.ECL.autoInit();
        return { components };
      }}
      beforeUnmount={context => {
        if (context.components) {
          context.components.forEach(c => c.destroy());
        }
      }}
    >
      {story()}
    </StoryWrapper>
  ))
  .add('default', () => {
    const toggle1 = {
      ...demoContent.items[0].toggle,
      label: text('Toggle 1', demoContent.items[0].toggle.label),
    };

    const toggle2 = {
      ...demoContent.items[1].toggle,
      label: text('Toggle 2', demoContent.items[1].toggle.label),
    };

    const toggle3 = {
      ...demoContent.items[2].toggle,
      label: text('Toggle 3', demoContent.items[2].toggle.label),
    };

    return (
      <Accordion2 data-ecl-auto-init="Accordion2">
        <Accordion2Item
          toggle={toggle1}
          id={demoContent.items[0].id}
          level={demoContent.items[0].level}
        >
          {text('Content 1', demoContent.items[0].content)}
        </Accordion2Item>
        <Accordion2Item
          toggle={toggle2}
          id={demoContent.items[1].id}
          level={demoContent.items[1].level}
        >
          {text('Content 2', demoContent.items[1].content)}
        </Accordion2Item>
        <Accordion2Item
          toggle={toggle3}
          id={demoContent.items[2].id}
          level={demoContent.items[2].level}
        >
          {text('Content 3', demoContent.items[2].content)}
        </Accordion2Item>
      </Accordion2>
    );
  });
````

And the config file is with an older organization, such as this:

```js
import { configure, addDecorator, addParameters } from '@storybook/react';

// addDecorator() ...

// addParameters() ...

const contexts = [
  require.context('../../templates', true, /stories.*\.jsx?$/),
  require.context('../../page-structure', true, /stories.*\.jsx?$/),
  require.context('../../layout', true, /stories.*\.jsx?$/),
  require.context('../../components', true, /stories.*\.jsx?$/),
  require.context('../../utilities', true, /stories.*\.jsx?$/),
  require.context('../../deprecated', true, /stories.*\.jsx?$/),
];

configure(() => {
  contexts.forEach(context => {
    context
      .keys()
      .filter(key => !key.includes('node_modules'))
      .forEach(context);
  });
}, module);

```
A given `story` and `context` is accessible through a [`makeDecorator()` API](https://storybook.js.org/docs/addons/writing-addons/#creating-a-decorator) but I can't figure a way to have a function with these parameters out of Storybook's context.

What I'm trying to achieve is to load all stories from node and use [ReactDOMServer](https://reactjs.org/docs/react-dom-server.html) to render stories with their contexts.

Would it be possible with 5.2.8? Would I need to first migrate to 5.3 [as suggested here](https://medium.com/storybookjs/declarative-storybook-configuration-49912f77b78)? (the hint is one of the last points about "Creating a separate page per component")

Thanks in advance for any hints!

**Comment by kalinchernev** [comment]
Possibly related https://github.com/storybookjs/storybook/issues/9221

Maybe an example of https://github.com/storybookjs/storybook/issues/775#issuecomment-568088728 will be helpful enough.

**Comment by kalinchernev** [comment]
Another issue I found which could be related: https://github.com/storybookjs/storybook/issues/8009

I tried to use `getStorybook` from storybook and get a list of stories during the process of "sourcing" the information in the configuration file. It's a client API though and I don't quite want to have the need to load the storybook in the browser in order to click on a button to get a list of stories and possibly render them later.

**Comment by kalinchernev** [comment]
It's still a valid question.

**Comment by kalinchernev** [comment]
Still relevant

**Comment by shilman** [comment]
@kalinchernev AFAIK there's no way to do this currently

**Comment by kalinchernev** [comment]
Hi @shilman in a project where I need this, I have already migrated configurations to latest recommended structure, as well as stories format.

I made a small attempt last week to use the stories glob pattern from the config which was ok, and I also validated that the custom babel config for the storybook is usable outside the storybook (duh :))

In a week or two I plan to setup a webpack to follow the babel config or possibly the overrides coming from storybook and I still have hope that stories being react components, with react's server side rendering it might be some how possible.

Do you think this way of thinking is wrong or there have been similar failed attempts?

**Comment by shilman** [comment]
@kalinchernev I'm not aware of any efforts here yet. You've commented on  https://github.com/storybookjs/storybook/issues/9382 which is a similar issue/concern (can I close this and we continue the conversation there?). It should be possible, with work, and @ndelangen would be the right person to collaborate with on this.

**Comment by ndelangen** [comment]
@kalinchernev I've been giving the following some thought recently:

What if storybook had a command to generate a `data.json` which would include the stories? Would that help your case?

**Comment by kalinchernev** [comment]
The task at hand for me at the moment is to generate HTML files for teams
to compare markup between different language implementations in different
instances of storybook. Like between React and Twig.

What would the data.json look like?

**Comment by kalinchernev** [comment]
Clarification: comparison of components between implementations.

**Comment by ndelangen** [comment]
@kalinchernev I think you could use storyshots for this purpose?
https://github.com/storybookjs/storybook/tree/next/addons/storyshots/storyshots-core

**Comment by kalinchernev** [comment]
The projects are in different repositories. One is
https://github.com/ec-europa/europa-component-library and another is
https://github.com/ec-europa/ecl-twig

I tried the storyshots few months ago for regression testing in the first
one, but wasn't quite successful and the setup wasn't accepted in the main
branch.

I also checked it's code few weeks ago trying to imagine using part of its
APIs for rendering with puppeteer, but could find a doable path for few
hours.

**Comment by ndelangen** [comment]
@kalinchernev I'd be open to an online meeting discussing this, and perhaps helping you in the right direction.

https://calendly.com/ndelangen/storybook

**Comment by kalinchernev** [comment]
Many thanks, sent a suggestion, please adjust to your preference!

Much appreciated!

**Comment by ndelangen** [comment]
@kalinchernev 

Topic: Norbert de Langen's Personal Meeting Room
Date: Mar 9, 2020 03:04 PM Amsterdam

Meeting Recording:
https://zoom.us/rec/share/2MZ7Kozo-U1LZs-R10H4U7wxG57rX6a8hnNKrqINmE5x_3HCu8_bsfHWIQxvdm7P

**Comment by kalinchernev** [comment]
Thank you again for the time @ndelangen !

**Comment by aghan** [comment]
Hello All,

I wanted to do something similar. Is there a way we could render stories and export them into HTML files? I read the comments and it seems there is no way to do this but still wanted to check.

**Comment by muratcorlu** [comment]
> @kalinchernev
> 
> Topic: Norbert de Langen's Personal Meeting Room Date: Mar 9, 2020 03:04 PM Amsterdam
> 
> Meeting Recording: https://zoom.us/rec/share/2MZ7Kozo-U1LZs-R10H4U7wxG57rX6a8hnNKrqINmE5x_3HCu8_bsfHWIQxvdm7P

@ndelangen @kalinchernev Can you share a summary of your discussion? Zoom link doesn't work anymore. I'm also very interested in with this. Is there any blocker?

**Comment by kalinchernev** [comment]
The meeting was a bit more than 2 years ago. From the technical discussions I remember https://storybook.js.org/docs/react/sharing/storybook-composition being mentioned as a potential solution.
