### ISSUE TITLE
Prop table defaults does not pick up boolean values in typescript

### ISSUE THREAD

**Issue by sami616** [storybookjs/storybook#9464]
Hi, when using typescript and setting default values when destructuring props boolean values seem to be ignored, eg: 

```typescript

interface Props extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  disabled?: boolean
}

const Component = ( { disabled = false, children }: Props) => <button disabled={disabled}>{children}</button>
```

The proptable for the above renders as expected only its missing the value  'false' in the default column. As far as i can see this is working correctly with other types, eg - strings, objects, functions etc.

**Comment by shilman** [comment]
Closing as dupe to #9394
