### ISSUE TITLE
Prop table does not render when a Type is used

### ISSUE THREAD

**Issue by sami616** [storybookjs/storybook#9465]
`Interface`'s work as expected, however when declaring prop as a `Type` storybook isn't able to render a prop table.

ie: 

👍🏼
```typescript
interface Props extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  disabled?: boolean
}

const Component = ( { disabled = false, children }: Props) => <button disabled={disabled}>{children}</button>
``` 

<hr/>

👎🏼
```typescript
type Props = React.ButtonHTMLAttributes<HTMLButtonElement> &  {
  disabled?: boolean
}

const Component = ( { disabled = false, children }: Props) => <button disabled={disabled}>{children}</button>
```

**Comment by shilman** [comment]
Repro: https://github.com/storybookjs/storybook/commit/dd10817f392544abc88f09f5d9c8fb4cda8ad62c

This appears to be working in `react-docgen`

**Comment by shilman** [comment]
@sami616 can you try the recommended 6.0 setup (should work in 5.3 too) and based on the repro linked above I expect the problem to be fixed:

https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#react-prop-tables-with-typescript
