### ISSUE TITLE
Imported interfaces not displaying in Prop tables

### ISSUE THREAD

**Issue by sami616** [storybookjs/storybook#9467]
When extending an interface with another imported from another file, the prop table doesn't render any of the imported properties. I assume this would also apply when using the `Type`'s too.

eg:

```typescript

// Foo.tsx

export interface Foo {
  bar?: string
}

// Component.tsx

import { Foo } from './Foo.tsx'

interface Props extends React.ButtonHTMLAttributes<HTMLButtonElement>, Foo {
  disabled?: boolean
}

const Component = ( { disabled = false, children }: Props) => <button disabled={disabled}>{children}</button>
```

☝🏼Prop table only outputs the disabled prop (ignores `bar`)

**Comment by kylemh** [comment]
It also won't catch the default in this case (at least it isn't for me)

**Comment by kylemh** [comment]
It's not about any import, it's about using types stemming from a default export.

https://github.com/storybookjs/storybook/issues/9556

**Comment by shilman** [comment]
Closing this in favor of #9556. Thanks @kylemh!!

**Comment by tobiaskraus** [comment]
I have the same issue, and **#9556 is not the same as the issue described here**.

@sami616 wrote

> Prop table only outputs the disabled prop (ignores bar)

So it did render the base properties, and not like in 9556 described, nothing.
I am NOT using the default import syntax `React.FunctionComponent` but the named export syntax `FunctionComponent` and I try to extend another properties interface from another file (named export), and it ignores these properies:

```ts
// InptTextField.tsx
export interface InputTextFieldProps {
  placeholder?: string;
  labelId?: string;
  error?: boolean;
}


// Input.tsx
import InputTextField, { InputTextFieldProps } from './elements/InputTextField';

export interface InputProps extends InputTextFieldProps {
  forTag?: string;
  labelText?: string;
}

const Input: FunctionComponent<InputProps> = ({
```
### Output in Storybook:

Name|Description|Default
---|---|---
forTag|string|-
labelText|string|-

So my properties from other file are ignored.

**Comment by tobiaskraus** [comment]
This issue is a currently opened issue in [react-docgen-typescript-loader/issues/47](https://github.com/strothj/react-docgen-typescript-loader/issues/47)

The problem seems to lay deep:

> This is a bit tricky because the loader is executed once for each file seen by webpack, and at that time we have no information of some other extended interfaces imported from other files

(from paibamboo in the above issue)

**Comment by shilman** [comment]
FYI we are recommending `react-docgen` in SB 6.0. It suffers from the same issue, but fixes a lot of other issues, and we think issues are more likely to get fixed there:

https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#react-prop-tables-with-typescript
