### ISSUE TITLE
Storybook docs description for primary slot

### ISSUE THREAD

**Issue by AlekseyPn** [storybookjs/storybook#9468]
Hi, i need help.
How i can write description for primary slot with vue story, and how i can describe props or events, i have not found how i can do it.
And i have not found describes for parameters.docs api. I lost many hours in tried find describes((

**Comment by shilman** [comment]
Use JSDoc, like this: https://github.com/storybookjs/storybook/blob/next/examples/vue-kitchen-sink/src/stories/components/InfoButton.vue

**Comment by AlekseyPn** [comment]
![Screenshot_20200117_184644](https://user-images.githubusercontent.com/18575325/72617197-470b8a80-395a-11ea-9439-9878c658304a.png)

@shilman Thanks for reply, I talk about that example, on the third line "description" rendered by JSDoc, from this example https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/docspage.md#description
But when i use it in my stories with vue, it doesn't applied

**Comment by shilman** [comment]
Does this help? https://github.com/storybookjs/storybook/commit/3bcaaeb769ef21234837cc755a27c056092d1f00

**Comment by HoraceKeung** [comment]
It works and would like to share the following info from my experience in case of any misunderstanding:
1. The comment for the description should be inside the Vue single file component, not in the story
2. The comment must be right above this line of code: `export default {`
i.e.
```
<script>
import Another from '~/components/Another'
/**
 * Component description
 */
export default {...}
</script>
```
The above will work and the below will not
```
<script>
/**
 * Component description
 */
import Another from '~/components/Another'
export default {...}
</script>
```
3. It won't work if the story is written with MDX

**Comment by shilman** [comment]
@HoraceKeung thanks! for MDX, you should be able to do:

```
import { Description } from '@storybook/addon-docs';
import { Component } from './component';

<Description of={Component} />
```

**Comment by AlekseyPn** [comment]
@HoraceKeung Thanks!!!

**Comment by HoraceKeung** [comment]
@shilman Thank you! Would like to mention that in Vue, it is `import Component from './component';`, also I think it should be `import { Description } from '@storybook/addon-docs/blocks';` Speaking of docs blocks, I couldn't find documentation regarding all the available docs blocks, but I guess it is coming soon on this page? https://storybook.js.org/docs/formats/mdx-syntax/

**Comment by shilman** [comment]
@HoraceKeung thanks, fixed. yes docs coming soon 🙈

**Comment by annacv** [comment]
> Use JSDoc, like this: https://github.com/storybookjs/storybook/blob/next/examples/vue-kitchen-sink/src/stories/components/InfoButton.vue

Hi @shilman it works properly :) But, what about slots, how can we add a slots' description? I've noticed it "catches" the slot when used as a tag (instead of using it as <div slot: 'bla'/>) but I'm not achieving how to customize the description. Any idea? Thks!

**Comment by ecarrera** [comment]
@annacv you can describe slots with `@slot` tag.

`<template>
  <div>
    
    <slot name="header"></slot>

    
    <slot name="footer" :item="item" />
  </div>
</template>`

Here is the reference: https://github.com/vue-styleguidist/vue-styleguidist/tree/dev/packages/vue-docgen-api#slots

**Comment by MatthijsBe** [comment]
Is there any other way to do this, or exclude this on a production build? 

My point is that when I inspect any component that uses `@slot` description it also shows in the dom. 


![image](https://user-images.githubusercontent.com/31308832/108674506-aafd6c80-74e5-11eb-83d8-ace1cbe20a80.png)

**Comment by alexcroox** [comment]
Has anyone managed to define this subheader in their story? Looking at the storybook documentation for the docs page i just can't get it to work, I've tried:

```
export default {
  title: `Forms/Form Elements/${Component.name}`,
  component: Component,
  docs: {
    description: {
      story: 'A subheader of the docs page here'
    }
  }
}
```

```
export default {
  title: `Forms/Form Elements/${Component.name}`,
  component: Component,
  componentSubtitle:  'A subheader of the docs page here'
}
```
