### ISSUE TITLE
Problem with docgen description/props when exporting arrow function

### ISSUE THREAD

**Issue by Tibblist** [storybookjs/storybook#9474]
**Describe the bug**
When you export a component using either export or export default const xyz = props => {} the docgen doesn't grab the description from above it in comments nor does it read any propTypes you attach to it.

**To Reproduce**
TestBadge.js
```js
import React from "react";
import PropTypes from "prop-types";

/**
 * This is a Badge function
 */
export const Badge = (props) => {
  return <div>Hello World!</div>;
}

Badge.propTypes = {
  label: PropTypes.string.isRequired
};
```
TestBadge.stories.js
```js
import React from "react";
import { Badge } from "./TestBadge";

export default {
  title: "Badge",
  component: Badge
};

export const Primary = () => {
  return <Badge />;
};
```

**Expected behavior**
Docgen will generate with a description below the title and show the label proptype in the proptype table below
**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System:**
Environment Info:

  System:
    OS: Windows 10 10.0.18362
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
Browser used was Chrome 79 on Windows 10

**Additional context**

**Comment by shilman** [comment]
`babel-plugin-react-docgen` is probably not being run on your components, so it's a configuration issue. Are you overriding your babel settings?
