### ISSUE TITLE
Show template value in Preview component

### ISSUE THREAD

**Issue by rijkvanzanten** [storybookjs/storybook#9476]
Hi there! I'm really excited about Storybook Docs. Great work 😄 

**Is your feature request related to a problem? Please describe.**
When using MDX stories with Vue, you have to put the components and template in an object like structure in the `<Story>` component as follows:

```html
<Story name="x-small">
{{
    components: { VIcon },
    template: `<v-icon name="person" color="--blue-grey" x-small />`
}}
</Story>
```

The `<Preview>` component has a very handy Show Source button, however, when used with Vue (as demoed above) it will show the full object as source:

![image](https://user-images.githubusercontent.com/9141017/72468015-36b4ad80-37aa-11ea-9fb6-6ac069ecbd55.png)

While I would have expected just the template:

```vue
<v-icon name="person" color="--blue-grey" large />
```

**Describe the solution you'd like**
Add the ability to point the source code that's rendered here to a value inside the object of the <Story> component, so we can render just the template. This could potentially work as follows:

```html
<Preview source={ obj => obj.template } />
  <Story>
    {{
      components: { VIcon },
      template: `<v-icon name="person" color="--blue-grey" large />`
    }}
  </Story>
</Preview>
```

**Describe alternatives you've considered**
I've tried duplicating the templates in the `mdxSource` property manually. This seems to work (including highlighting!) 

```html
<Preview mdxSource='<v-icon name="person" color="--blue-grey" small />'>
	<Story name="small" height="50px">
		{{
			components: { VIcon },
			template: `<v-icon name="person" color="--blue-grey" small />`
		}}
	</Story>
</Preview>
```

but is less than ideal when using multiple Story blocks:

```html
<Preview mdxSource={`
<v-icon name="person" color="--blue-grey" small />
<v-icon name="person" color="--blue-grey" medium />
<v-icon name="person" color="--blue-grey" large />
`}>
	<Story name="small" height="50px">
		{{
			components: { VIcon },
			template: `<v-icon name="person" color="--blue-grey" small />`
		}}
	</Story>
	<Story name="medium" height="50px">
		{{
			components: { VIcon },
			template: `<v-icon name="person" color="--blue-grey" medium />`
		}}
	</Story>
	<Story name="large" height="50px">
		{{
			components: { VIcon },
			template: `<v-icon name="person" color="--blue-grey" large />`
		}}
	</Story>
</Preview>
```

Also, having to duplicate the template strings makes it very easy to forget to update one or the other.

**Are you able to assist bring the feature to reality?**
Yes, I can help think out an ideal spec and potentially implement the feature (with some pointers)

**Comment by shilman** [comment]
Totally agree @rijkvanzanten! Closing this as a dupe to #7729

**Comment by rijkvanzanten** [comment]
I wouldn't say it's a duplicate per se, more a different way to achieve the same thing. I do agree that having "native" support without the need of the object syntax is a preferable solution 🙂

**Comment by shilman** [comment]
Gotcha, sorry I pattern-matched and kind of glossed over the details. It's actually a special case of #7479, and also related to #8109
