### ISSUE TITLE
Stories appearing in reverse order in v5.3.3

### ISSUE THREAD

**Issue by benmvp** [storybookjs/storybook#9477]
**Describe the bug**
I upgraded from 5.3.2 to 5.3.3 today and my stories were displaying in reverse order than how they are exported (using CSF).

**To Reproduce**
1. Write stories using CSF
2. Observe that in the nav pane on the left they are in reverse order, including subcategories

**Expected behavior**
I would expect that the stories would be in the order that they were exported in, which is how they worked in 5.3.2.

**System:**

```sh
Environment Info:

  System:
    OS: macOS Mojave 10.14.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 9.11.1 - ~/.nvm/versions/node/v9.11.1/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 5.6.0 - ~/.nvm/versions/node/v9.11.1/bin/npm
  Browsers:
    Chrome: 79.0.3945.117
    Firefox: 70.0.1
    Safari: 13.0.4
  npmPackages:
    @storybook/addon-a11y: ^5.3.3 => 5.3.3 
    @storybook/addon-actions: ^5.3.3 => 5.3.3 
    @storybook/addon-links: ^5.3.3 => 5.3.3 
    @storybook/addons: ^5.3.3 => 5.3.3 
    @storybook/react: ^5.3.3 => 5.3.3 
```

**Additional context**
One thing to note is that if I force the sort order following the [sorting stories guide](https://storybook.js.org/docs/configurations/options-parameter/#sorting-stories), they appear in alphabetical order.

**Comment by benmvp** [comment]
I think the problem has to do with [this line in `story_store.ts`](https://github.com/storybookjs/storybook/blob/31365c1534f7fb9d543d115a40c8951596e916ea/lib/client-api/src/story_store.ts#L146):

```typescript
stable.inplace(stories, (s1, s2) => kindOrder[s1[1].kind] - kindOrder[s2[1].kind]);
```

I'm not entirely sure what it does, but it seems to sort the stories by their category, but amongst themselves. This process must inadvertently reverse the original order of the stories themselves?

This appears to be something new @shilman added two days ago in #9424 (to fix #9419). Maybe you can chime in?

**Comment by tmeasday** [comment]
Thanks for the issue @benmvp, can you just clarify with a screenshot -- is it the stories are the wrong order within a kind? Or are the kinds in the wrong order? Or both?

**Comment by chris-pearce** [comment]
I'm experiencing this also after updating to `5.3.3`. Seems it's now alphabetical? Here's the order I see now:

<img width="211" alt="Screen Shot 2020-01-16 at 11 08 35" src="https://user-images.githubusercontent.com/1342772/72482041-6e763080-3850-11ea-8334-a45162874044.png">

Before `5.3.3`, "Default" was first.

**Comment by benmvp** [comment]
@tmeasday, it appears like both. 

Here's a screenshot:
![Screen Shot 2020-01-15 at 6 33 45 PM](https://user-images.githubusercontent.com/5714478/72488361-98364580-37c5-11ea-86c2-abfb8d9b91b5.png)

The kinds used to be sorted alphabetically, and now they are backwards. The stories w/in the kind used to be sorted by their `export`s within the story file and now they are sorted in reverse.

**Comment by tmeasday** [comment]
Thanks @benmvp and @chris-pearce. Fix coming.

**Comment by shilman** [comment]
¡Ay Caramba!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.4 containing PR #9482 that references this issue. Upgrade today to try it out!

Closing this issue. Please re-open if you think there's still more to do.

**Comment by benmvp** [comment]
Yup, that fixed it! Thanks! 🎉
