### ISSUE TITLE
Writing Stories Documentation Typo

### ISSUE THREAD

**Issue by third** [storybookjs/storybook#9478]
**Describe the bug**
Writing Stories documentation says

"Storybook will prioritize the componentId over the title for ID generation"

I tried using `componentId` and did not work. I looked at the code and saw it uses `id` instead of `componentId`. One way to fix this is to update the documentation. The other option is to update the code. I can do either one of the option if need be.

https://storybook.js.org/docs/basics/writing-stories/#permalinking-to-stories

**Comment by shilman** [comment]
You're right, that was a typo in the docs. Fixed & deploying now!
