### ISSUE TITLE
[addon-docs] theme.background is undefined

### ISSUE THREAD

**Issue by VladimirPittner** [storybookjs/storybook#9484]
**Describe the bug**
When using addon-docs in 5.3.3, I am getting `theme.background is undefined` error in Docs tab.
![storybook](https://user-images.githubusercontent.com/1529181/72493130-80dc7400-3828-11ea-84be-4f67ec620cff.png)

**To Reproduce**
My test setup:
main.js
```
module.exports = {
  stories: ['../src/**/*.stories.(js|mdx)'],
  addons: [
    '@storybook/addon-links',
    '@storybook/addon-knobs',
    '@storybook/addon-backgrounds',
    '@storybook/addon-a11y',
    '@storybook/addon-jest',
    '@storybook/addon-docs',
  ],
};
```
preview.js
```
import { addDecorator } from '@storybook/react';
import { withKnobs } from '@storybook/addon-knobs';
import { withA11Y } from '@storybook/addon-a11y';
import { withTests } from '@storybook/addon-jest';
import results from '../.jest-test-results.json';

addDecorator(withKnobs);
addDecorator(withA11Y);
addDecorator(
  withTests({
    results,
    filesExt: '.test.js',
  })
);
```
manager.js
```
import { addons } from '@storybook/addons';
import { themes } from '@storybook/theming';

addons.setConfig({
  panelPosition: 'right',
  theme: themes.dark
})
```
test.stories.js
```
import React from 'react';
export default { title: 'Test' };
export const basic = () => <p>Hello World</p>;
```
**System:**
Environment Info:
  Binaries:
    Node: 8.17.0 - /usr/bin/node
    Yarn: 1.21.1 - /usr/bin/yarn
    npm: 6.13.4 - /usr/bin/npm
  Browsers:
    Chrome: 79.0.3945.117
    Firefox: 72.0.1

**Comment by VladimirPittner** [comment]
It seem to have been problem of @storybook/addon-docs not getting installed in correct place (due to unknown reason, probably our tooling). 
Closing the issue

**Comment by chris-aeviator** [comment]
I'm running into this with `@emotion/core` v10.1.1

**Comment by bageren** [comment]
I'm getting this error with storybook 7.2 when trying to open docs

**Comment by ritik-spenmo** [comment]
+1 facing this error when upgrading from 7.0.26

**Comment by apetta** [comment]
Same issue on 7.6 when setting up docs addon
