### ISSUE TITLE
Props table is broken when using more exports in file (vue)

### ISSUE THREAD

**Issue by chiptus** [storybookjs/storybook#9491]
**Describe the bug**
I'm working with VUE.
I have a component that in addition to its default export (as required by SFC) it has some states that are exported for use for others that use this component. In this component stories are working fine, but the props table doesn't show.

**Expected behavior**
I expect to see the props table in every component

**Screenshots**
when using exports:
![image](https://user-images.githubusercontent.com/1381655/72516083-c1081a80-3859-11ea-93df-e34165ec016b.png)
without exports:
![image](https://user-images.githubusercontent.com/1381655/72516165-e5fc8d80-3859-11ea-9432-8ad8497338c5.png)

**Code snippets**
```
<template>
  <div>
    template
  </div>
</template>

<script>
export const STATES = {
  on: 'on',
  off: 'off'
}

export defualt {
}
```

**System:**
```

Environment Info:

  System:
    OS: macOS 10.15.2
    CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
  Binaries:
    Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
    Yarn: 1.21.1 - ~/.yarn/bin/yarn
    npm: 6.13.1 - ~/.nvm/versions/node/v10.15.0/bin/npm
  Browsers:
    Chrome: 79.0.3945.117
    Firefox: 70.0.1
    Safari: 13.0.4
  npmPackages:
    @storybook/addon-actions: ^5.3.4 => 5.3.4 
    @storybook/addon-docs: ^5.3.0-rc.14 => 5.3.0-rc.14 
    @storybook/addon-links: ^5.3.4 => 5.3.4 
    @storybook/addons: ^5.3.4 => 5.3.4 
    @storybook/vue: ^5.3.4 => 5.3.4 
```

also using rails webpacker

**Comment by shilman** [comment]
@Aaron-Pool @pocka any insights here?

**Comment by pocka** [comment]
vue-docgen-api not supporting additional named-exports in SFC?
https://codesandbox.io/s/vue-docgen-api-mixed-export-w2xj3

**Comment by shilman** [comment]
Aha, I thought we already solved this with `vue-docgen-loader` for the Evergarden stuff... 🤔

**Comment by pocka** [comment]
No 👌 
I'll check source codes of vue-docgen-api and vue-docgen-loader, soon.

**Comment by Aaron-Pool** [comment]
Yeah. My guess is that the docgen-api supports mixed default and named exports in a regular js file, but maybe hasn't considered that case in a SFC. It isn't a super common thing, though I think I've done it once or twice in my own code base.

**Comment by pocka** [comment]
It was that vue-docgen-api cannot parse mixed exports in SFC, as @Aaron-Pool said. I filed an issue on docgen-api repo (https://github.com/vue-styleguidist/vue-styleguidist/issues/717).

**Comment by pocka** [comment]
You can now parse an SFC including named exports with `vue-docgen-api: >=4.6.0`.

**Comment by shilman** [comment]
@pocka do we need to make changes in storybook?

**Comment by pocka** [comment]
@shilman No, just re-installing vue-docgen-api (after removing lockfile) then it should work! (https://github.com/storybookjs/storybook/blob/next/addons/docs/package.json#L73)
