### ISSUE TITLE
Description and Props slots not shown when using TS and Component.displayName

### ISSUE THREAD

**Issue by eriktoyra** [storybookjs/storybook#9493]
**Describe the bug**
@storybook/addon-docs fails to populate the "Description" and "Props" slots in the following scenario;

- TypeScript is used.
- The component to document has a `Component.displayName` and the display name is assigned a string that doesn't match the component's name exactly. 

**To Reproduce**
Here's a sample repo which reproduces this bug: https://github.com/eriktoyra/storybook-component-displayname-bug

1. `npm run storybook`
2. Open up the `EmpireAlert` story in the storybook and go to the Docs tab. Note that both the "Description" and "Props" slots are populated.
3. Open up `./src/components/EmpireAlert.tsx` and uncomment `//EmpireAlert.displayName = "RebelAlliance.EmpireAlert"` on line 47. (You might have to restart Storybook to see the effect)
4. Go back to the Storybook and note that the "Description" and "Props" slots have lost their content.

**Expected behavior**
I expect `Component.displayName` to have no effect at all on "Description" and "Props" in the docs. The `displayName` string [is meant for debugging purposes](https://reactjs.org/docs/react-component.html#displayname).

**Screenshots**

*Actual result*
<img width="1680" alt="Skärmavbild 2020-01-16 kl  13 52 54" src="https://user-images.githubusercontent.com/149738/72533115-e48c8e80-3874-11ea-8ef3-b92f300cae1f.png">

*Expected result*
<img width="1680" alt="Skärmavbild 2020-01-16 kl  13 53 23" src="https://user-images.githubusercontent.com/149738/72533116-e48c8e80-3874-11ea-816d-f8be079e238e.png">

**Code snippets**

*./.storybook/main.js*
```javascript
module.exports = {
  stories: ["../src/**/*.stories.(js|tsx)"],
  addons: [
    "@storybook/preset-typescript",
    {
      name: "@storybook/preset-create-react-app",
      options: {
        tsDocgenLoaderOptions: {}
      }
    },
    "@storybook/addon-actions",
    {
      name: "@storybook/addon-docs",
      options: {
        configureJSX: true
      }
    },
    "@storybook/addon-links"
  ]
};
```

*./src/components/EmpireAlert.tsx*
```TypeScript
import styled from "@emotion/styled";
import React from "react";

const Wrapper = styled("div")<{}>(({ theme }) => ({
  backgroundColor: "tomato",
  color: "white",
  padding: 10
}));

type AlertCode = "Code Red" | "Code Yellow" | "Code Green";

export interface EmpireAlertProps {
  /**
   * A title that brings attention to the alert.
   */
  title: AlertCode;
  /**
   * A message alerting about Empire activities.
   */
  message: string;
}

/**
 * This message should show up in the Docs panel if everything works fine.
 */
export const EmpireAlert: React.FC<EmpireAlertProps> = ({
  title = "Code Yellow",
  message
}) => (
  <Wrapper>
    <h1>{title}</h1>
    <p>{message}</p>
  </Wrapper>
);

/**
 * Specifying a displayName with a different name for the component will
 * cause DocsPage to fail to populate the Description and Props slots
 *
 * Works:
 *  - Using a displayName that _matches_ the component name exactly.
 *  - Not using a displayName at all.
 *
 * Fails:
 *  - Using a displayName that _does not match_ the component name exactly.
 */
 // EmpireAlert.displayName = "RebelAlliance.EmpireAlert"; // Uncomment to trigger bug
```

*./src/components/EmpireAlert.stories.tsx*

```TypeScript
import React from "react";
import { EmpireAlert } from "./EmpireAlert";

export default {
  title: "EmpireAlert",
  component: EmpireAlert
};

export const _default = () => (
  <EmpireAlert
    title="Code Red"
    message="The Empire has been sighted on Hoth. Man the battle stations!"
  />
);
```

**System:**
Storybook 5.3.3 is also affected. 

```
Environment Info:

  System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
    npm: 6.13.4 - ~/.nvm/versions/node/v10.15.0/bin/npm
  Browsers:
    Chrome: 79.0.3945.117
    Firefox: 70.0.1
    Safari: 13.0.4
  npmPackages:
    @storybook/addon-actions: 5.3.4 => 5.3.4 
    @storybook/addon-docs: 5.3.4 => 5.3.4 
    @storybook/addon-links: 5.3.4 => 5.3.4 
    @storybook/addons: 5.3.4 => 5.3.4 
    @storybook/preset-create-react-app: ^1.5.1 => 1.5.1 
    @storybook/preset-typescript: ^1.2.0 => 1.2.0 
    @storybook/react: 5.3.4 => 5.3.4 
```

**Additional context**
Yes, I will be able to assist in pushing a PR for this given som guidance.

**Comment by eriktoyra** [comment]
I poked around in the code base and found line 34 in `./addons/docs/src/blocks/utils.ts` that might be the cause of this problem. 

https://github.com/storybookjs/storybook/blob/66c524f194e14a6ba1328ba19bd6c71ecfc9e2da/addons/docs/src/blocks/utils.ts#L23-L39

**Comment by shilman** [comment]
@patricklafrance mind taking a look?

**Comment by atanasster** [comment]
@eriktoyra - i think the displayName is used by `react-docgen-typescript` to match the parsed typescript prop tables and and docgen info (ie the description). In this respect, it makes sense that the dislayName will affect those features, since the component prop table will not be "found", no?

**Comment by eriktoyra** [comment]
> @eriktoyra - i think the displayName is used by `react-docgen-typescript` to match the parsed typescript prop tables and and docgen info (ie the description). In this respect, it makes sense that the dislayName will affect those features, since the component prop table will not be "found", no?

@atanasster Thank's for looking that up! It seems you are correct. But the purpose of `displayName` is not to be used as a "component lookup" alternative to the actual component name. As per the [official documentation](https://reactjs.org/docs/react-component.html#displayname) its purpose is to be used for _displaying_ an alternative component name when debugging. 

Given the fact that this bug does not occur when using `displayName` in a JavaScript based component I would say that the TypeScript version is doing it wrong.

**Comment by shilman** [comment]
Repro: https://github.com/storybookjs/storybook/commit/ed714ba365dcb449810464f33d12590fda1c8b1d (and https://github.com/storybookjs/storybook/commit/57e571cada30114ffc57bfaef3c7f4045dc0a23a oops!!)

**Comment by sidhuko** [comment]
OP could you try changing your code to use `import * as React from 'react';`?

**Comment by eriktoyra** [comment]
> OP could you try changing your code to use `import * as React from 'react';`?

@sidhuko Tried that just now. It had no effect unfortunately. Even tried to update Storybook to 5.3.13 (latest as of now) but still no effect.

**Comment by shilman** [comment]
@eriktoyra can you try disabling `typescript-react-docgen-loader` and using the built-in `babel-plugin-react-docgen` instead? i'll be writing a guide about this as part of 6.0, but in the meantime maybe this tip can get you on the right track.

**Comment by eriktoyra** [comment]
@shilman It had no effect I'm afraid. Or maybe I dit it the wrong way? Did the following:

1. Uninstalled `react-docgen-typescript-loader`.
2. Installed `babel-plugin-react-docgen`.
3. Added `.babelrc` containing the following snippet:
```
{
  "plugins": ["react-docgen"]
}
```

Let me know if I can assist in some other way with this issue.

**Comment by shilman** [comment]
@eriktoyra one more thing 😄 

Try changing:

```ts
export const EmpireAlert: React.FC<EmpireAlertProps> = ({
  title = "Code Yellow",
  message
}) => (
```

To:

```ts
export const EmpireAlert: React.FC<EmpireAlertProps> = ({
  title = "Code Yellow",
  message
}: EmpireAlertProps) => (
```

Workaround for https://github.com/reactjs/react-docgen/issues/387

**Comment by eriktoyra** [comment]
@shilman Still no success. The only way I can make it work is as in my code comment below. It seems very much related to the `displayName` property. 

```
/**
 * Specifying a displayName with a different name for the component will
 * cause DocsPage to fail to populate the Description and Props slots
 *
 * Works:
 *  - Using a displayName that _matches_ the component name exactly.
 *  - Not using a displayName at all.
 *
 * Fails:
 *  - Using a displayName that _does not match_ the component name exactly.
 */
EmpireAlert.displayName = "RebelAlliance.EmpireAlert";
```

I'm still having a theory that using a `displayName` not matching the actual component's name sends the component doc parser looking for a component that does not exists. See [function `getComponentName` here](https://github.com/storybookjs/storybook/blob/66c524f194e14a6ba1328ba19bd6c71ecfc9e2da/addons/docs/src/blocks/utils.ts#L23-L39).

**Comment by pachuka** [comment]
Looks like the issue specifically has to do with the filename of the component. For example if I do `product-section-header.tsx` the generated docgeninfo is attached to `productsectionheader`:

**This one fails to find props:**
```jsx
/***/ "./src/molecules/quote/product-section-header/product-section-header.tsx":
/*!*******************************************************************************!*\
  !*** ./src/molecules/quote/product-section-header/product-section-header.tsx ***!
  \*******************************************************************************/
 /*component implementation removed*/
try {
    // @ts-ignore
    productsectionheader.displayName = "productsectionheader";
    // @ts-ignore
    productsectionheader.__docgenInfo = { /* data removed */ };
    // @ts-ignore
    if (typeof STORYBOOK_REACT_CLASSES !== "undefined")
        // @ts-ignore
        STORYBOOK_REACT_CLASSES["src/molecules/quote/product-section-header/product-section-header.tsx#productsectionheader"] = { docgenInfo: productsectionheader.__docgenInfo, name: "productsectionheader", path: "src/molecules/quote/product-section-header/product-section-header.tsx#productsectionheader" };
}
catch (__react_docgen_typescript_loader_error) { }
/***/ }),
```

vs. if I name the file `ProductSectionHeader.tsx`
**this one the props map properly**
```jsx
/***/ "./src/molecules/quote/product-section-header/ProductSectionHeader.tsx":
/*!*****************************************************************************!*\
  !*** ./src/molecules/quote/product-section-header/ProductSectionHeader.tsx ***!
  \*****************************************************************************/
 /*component implementation removed*/
exports.ProductSectionHeader = ProductSectionHeader;
try {
    // @ts-ignore
    ProductSectionHeader.displayName = "ProductSectionHeader";
    // @ts-ignore
    ProductSectionHeader.__docgenInfo = {  /* data removed */};
    // @ts-ignore
    if (typeof STORYBOOK_REACT_CLASSES !== "undefined")
        // @ts-ignore
        STORYBOOK_REACT_CLASSES["src/molecules/quote/product-section-header/ProductSectionHeader.tsx#ProductSectionHeader"] = { docgenInfo: ProductSectionHeader.__docgenInfo, name: "ProductSectionHeader", path: "src/molecules/quote/product-section-header/ProductSectionHeader.tsx#ProductSectionHeader" };
}
catch (__react_docgen_typescript_loader_error) { }
/***/ }),
```

**Comment by dzwillia** [comment]
I ran into this issue just a bit ago as well. We wanted to preface our components with the library name for better specificity in React DevTools. Have not had any luck with any of the workaround or suggestions above.

**Comment by HarishSha** [comment]
Facing same issue

**Comment by phocks** [comment]
+1 still having this issue. Svelte + TS

**Comment by valentinpalkovic** [comment]
@phocks I just tried it, and I couldn't reproduce it with the latest Storybook version. Can you provide a reproduction with the latest version of Storybook?
