### ISSUE TITLE
[question] Getting passing tests in spec addon but failing in browser console. Does storybook render twice or catch story errors?

### ISSUE THREAD

**Issue by sw-yx** [storybookjs/storybook#9495]
**Describe the bug**

i have a weird bug with react testing library and the storybook specs addon (its no longer maintained but we were dumb enough to use it) and i have a weird symptom of passing tests in the addon but failing tests inside the browser console 

repro repo: https://github.com/sw-yx/repro-react-storybook-specs-addon-bug
live demo of bug: https://repro-react-storybook-specs-addon-bug.netlify.com/

i spent way too much time trying to replicate this problem in a standalone repo and i think i have a handle on it, but i cant get this error out of the way:

![image](https://user-images.githubusercontent.com/6764957/72539346-2a356100-384d-11ea-96cc-a1f37ca49f37.png)

does storybook somehow render twice? or does it catch async story errors somehow? trying to puzzle out how to even track down this bug - it could be storybook, it could be the specs addon, it could be react-testing-library, i have no idea :(

**Comment by shilman** [comment]
cc @ndelangen

**Comment by sw-yx** [comment]
more broadly - also wondering if you'd like to take on maintenance of storybook-addon-specs. its pretty much [the only thing you recommend for interaction testing](https://storybook.js.org/docs/testing/interaction-testing/), and it is unmaintained. i probably dont need to sell you guys on how its probably a good idea to have a good interaction testing story together with storybook. the question is who takes on the maintenance 😂 (i can't, im only on this project another 1 month). fwiw we have about 600+ tests written inside storybook tests and no idea how to move them to CSF if we ever end up moving to that.

**Comment by shilman** [comment]
@sw-yx i'll be trying to build out a bunch of maintainers this year, and will keep `addon-specs` in mind. it's come up a couple times in support, but otherwise doesn't seem to be particularly widely-used.

agree about interaction testing support, but i'm guessing the documentation needs to be updated more than anything. with CSF the sky's the limit on interop with your favorite testing tools. that said, i don't have a recommendation off the top of my head. 😅

**Comment by sw-yx** [comment]
yeah. obviously no pressure, you dont owe us anything. You could even wipe out that page and just ask for someone to step up with a new take on it.

anyway, back to the main question of this issue - how come i have a failing test in the browser console but not in the addon? just looking for a hint as to how storybook might work internally, i saw some mentions of [double rendering](https://github.com/storybookjs/storybook/issues?q=is%3Aissue+sort%3Aupdated-desc+render+twice+is%3Aclosed) or maybe there's some sort of catch-and-retry strategy going on? i made that repro so hopefully its easy to take a quick look for someone with knowledge of internals.

**Comment by ndelangen** [comment]
@sw-yx I'm looking at repro-react-storybook-specs-addon-bug.netlify.com but I'm seeing this:

<img width="1121" alt="Screenshot 2020-01-23 at 12 25 09" src="https://user-images.githubusercontent.com/3070389/72980748-6c294e80-3ddb-11ea-90af-5bebfdecbd5b.png">

I'm not seeing a specs panel at all. Nor do I see any errors in the console.
https://repro-react-storybook-specs-addon-bug.netlify.com/?path=/story/test--button

I'll add looking into this on my todo-list, thanks for the reproduction repo.

**Comment by sw-yx** [comment]
wow, you're right - it disappeared in production?! i think i did have it while in dev. even weirder :(

**Comment by ndelangen** [comment]
@sw-yx it's on the wish-list to revamp the connection between testing + storybook.

Both on the e2e & unit test front, I have a lot of amazing things in mind. but not really the time to work on it, right now.

**Comment by sw-yx** [comment]
yeah. i'm gonna go ahead and close this for now. but hey, when you start it back up, lmk!
