### ISSUE TITLE
Questions: Web components HMR for v5.3.4

### ISSUE THREAD

**Issue by alazurenko** [storybookjs/storybook#9496]
Dear Maintainers,

With `v5.3.x` came new setup, particularly, import stories into `main.js`.
Thus [HMR approach for Web Components](https://github.com/storybookjs/storybook/tree/master/app/web-components#setup-page-reload-via-hmr) no longer works for  `'@storybook/html'`
Are there any workarounds?

**Comment by shilman** [comment]
cc @daKmoR @ndelangen

**Comment by daKmoR** [comment]
what "does no longer work" mean in that context? and are we talking about `@storybook/web-components` or `@storybook/html`?

**Comment by alazurenko** [comment]
HMR for web components when `@storybook/html` is used. 
Previously, there [was a way to configure it](https://github.com/storybookjs/storybook/tree/master/app/web-components#setup-page-reload-via-hmr) but now configuration is different and we don't have that much control.

**Comment by daKmoR** [comment]
indeed you can not use that configuration in `main.js` 🙈 

@ndelangen any way to influence the HMR behaviour now?

**Comment by shilman** [comment]
@daKmoR can you put this in `preview.js`?

```js
if (module.hot) {
  module.hot.accept(req.id, () => {
    const currentLocationHref = window.location.href;
    window.history.pushState(null, null, currentLocationHref);
    window.location.reload();
  });
}
```

**Comment by apalaniuk** [comment]
[It still works](https://github.com/storybookjs/storybook/blob/97a4aad4587ac975fd814c22a136f8293b72fc12/examples/web-components-kitchen-sink/.storybook/preview.js), but then you're also moving some declarative config from `main.js` into `preview.js`, which is a bit odd. It would be nice to have a callback that's provided module/req so you can do post-config tweaks, or something.

**Comment by ndelangen** [comment]
@daKmoR @alazurenko The code to deal with stories HMR when configured with `main.js` is right here:
https://github.com/storybookjs/storybook/blob/a6c2a85183e3701c8f73003b0df4d62c540ce771/lib/core/src/client/preview/start.js#L493-L502

As you see, we know exactly which framework we're in, so we can do a bit of framework dependent HMR handling code.

Would you be able to open a PR @alazurenko ?

**Comment by alazurenko** [comment]
Alright, I think this setup would be beneficial for HTML and Web Components.

**Comment by oldwestaction** [comment]
when i click the link in [ndelangen's response](https://github.com/storybookjs/storybook/issues/9496#issuecomment-577612267), i don't see lines 493-502 at all, so i'm not quite sure what i'm supposed to be looking at.

i'm currently using `@storybook/web-components` v5.3.12 and tried following the example set out [here](https://github.com/storybookjs/storybook/tree/master/app/web-components#setup-page-reload-via-hmr) by adding this to `preview.js`: 
```
const req = require.context('../components', true, /\.stories\.(js|mdx)$/);
configure(req, module);
if (module.hot) {
  module.hot.accept(req.id, () => {
    const currentLocationHref = window.location.href;
    window.history.pushState(null, null, currentLocationHref);
    window.location.reload();
  });
}
```
the behavior i'm seeing is that updates to the stories trigger a hot reload, updates to the components don't trigger a reload at all (components and stories are both under the path `/components/*` if that's useful context). it also seems like using `configure(req, module);` causes the console error `Unexpected loaded state. Did you call `load` twice?` as though `configure` is being called multiple times, even though i'm only using it once.

what's the correct way to set storybook up so that the iframe reloads when updates are made to the web components?

**Comment by alazurenko** [comment]
@oldwestaction I have managed to split config for development and production environment, since we only need HRM for development. 

`utils.js`
```js
const { NODE_ENV } = process.env;
const PRODUCTION = 'production';
const isProduction = NODE_ENV === PRODUCTION;
module.exports = { isProduction }
```
`main.js`
```js
const { isProduction } = require('./utils.js');
module.exports = {
    stories: [ isProduction ? '../src/components/**/*.stories.(js|mdx)': null ],
    addons: [],
  // .... rest of config
}
```

`preview.js`
```js
const { isProduction } = require('./utils.js');
// ... preview configuration
if (!isProduction) {
    const stories = require.context('./../src/components', true, /\.stories\.(js|mdx)$/);
    configure(stories, module);
    if (module.hot) {
        module.hot.accept(stories.id, () => {
            const currentLocationHref = window.location.href;
            window.history.pushState(null, null, currentLocationHref);
            window.location.reload();
        });
    }
}

```

**Comment by steel** [comment]
We wrote a HMR handler for custom elements and it's been working fairly well for our situation: https://github.com/polleverywhere/hmr-custom-element

Hope this works for you guys as well.

**Comment by shilman** [comment]
Nice one @steel! 💯 

@steel @daKmoR any chance we can integrate this into `@storybook/web-components` out of the box so it's zero config?

**Comment by ndelangen** [comment]
Impressive @steel, would love to have that by default in app/web-components for 6.0.0!

If you need any help, we could pair program on it?

**Comment by steel** [comment]
I'll put up a PR

**Comment by steel** [comment]
I'm gonna delay this. We don't use LitElement, only lit-html within the custom element. This helper does not work with LitElement which is what the kitchen sink app uses. I don't want folks to get some sense of false hope. I can still put up a PR though if you like that updates the doc with instructions on how to try it if they are not using LitElement.

Let me know.
Thanks.

**Comment by dakom** [comment]
For vanilla storybook (e.g. html) here's a workaround for live reload in the meantime.

1. `npm install --save-dev webpack-livereload-plugin`

2. In `.storybook/main.js`:

    2a. `const LiveReloadPlugin = require('webpack-livereload-plugin');`

    2b. Edit the webpack config.  `config`, here is the thing passed to `webpackFinal` in `module.exports`

    ```
    //remove HMR
    config.plugins = config.plugins.filter(plugin => plugin.constructor.name != "HotModuleReplacementPlugin");
    config.entry = config.entry.filter(entry => entry.indexOf("webpack-hot-middleware") === -1);

    //Add LiveReload
    config.plugins.push(new LiveReloadPlugin());
    ```

3. In `.storybook/preview-head.html` add:
    `<script src="http://localhost:35729/livereload.js"></script>`

**Comment by shilman** [comment]
Related: #12307

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if this is still relevant in SB 7.x.
