### ISSUE TITLE
Docs not applying base theme in manager.js

### ISSUE THREAD

**Issue by wadehammes** [storybookjs/storybook#9498]
**Describe the bug**
Migrating to manager.js has caused Docs to not apply my theme which has a base of 'dark'

**To Reproduce**
1. Create a theme in `manager.js` and set the base to 'dark'.

**Expected behavior**
Docs would have a base theme of 'dark' as in 5.2.

**Screenshots**
Canvas:
![Screen Shot 2020-01-16 at 12 54 14 PM](https://user-images.githubusercontent.com/222170/72549865-85704f00-385f-11ea-8478-2ba4285f8940.png)

Docs:
![Screen Shot 2020-01-16 at 12 54 20 PM](https://user-images.githubusercontent.com/222170/72549879-8d2ff380-385f-11ea-9b56-719117ab5858.png)

**Code snippets**
`manager.js`

```
import {addons} from '@storybook/addons';
import {create} from '@storybook/theming/create';
import {APP_COLORS as color} from '../src/styles/colors';

const theme = create({
  base: 'dark',
  colorPrimary: color.SW_SKY_BLUE,
  colorSecondary: color.SW_SKY_BLUE,
});

addons.setConfig({
  theme,
});
```

**System:**
Environment Info:

  System:
    OS: macOS 10.15.2
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.13.0 - ~/.yarn/bin/yarn
    npm: 6.13.6 - /usr/local/bin/npm
  Browsers:
    Chrome: 79.0.3945.117
    Firefox: 70.0.1
    Safari: 13.0.4
  npmPackages:
    @storybook/addon-actions: ^5.3.4 => 5.3.4
    @storybook/addon-centered: ^5.3.4 => 5.3.4
    @storybook/addon-docs: ^5.3.4 => 5.3.4
    @storybook/addon-jest: ^5.3.4 => 5.3.4
    @storybook/addon-knobs: ^5.3.4 => 5.3.4
    @storybook/addon-links: ^5.3.4 => 5.3.4
    @storybook/addon-storysource: ^5.3.4 => 5.3.4
    @storybook/addons: ^5.3.4 => 5.3.4
    @storybook/react: ^5.3.4 => 5.3.4
  npmGlobalPackages:
    @storybook/cli: 3.4.4

**Comment by shilman** [comment]
@ndelangen I think this was a case we didn't think through in the theming update 😱

**Comment by shilman** [comment]
Based on discussion with @ndelangen: 

### In 5.3 

- [ ] Verify that parameters still works
- [ ] Recommend to users (here and in migration/documentation) to use parameters if they're using docs

### In 6.0

- [ ] Allow specifying manager/preview/(docs?) themes in main.js and recommend that

**Comment by tmeasday** [comment]
😨

**Comment by ndelangen** [comment]
I added this to my todo list

**Comment by palashkaria** [comment]
current workaround:	use `addParameters` -> `docs` -> `container` & use Global style from emotion there.

**Comment by shilman** [comment]
@palashkaria if you use `addParameters` on `options.theme` I'd expect it to work in docs without having to do any other workarounds.

**Comment by ndelangen** [comment]
> Recommend to users (here and in migration/documentation) to use parameters if they're using docs

in PR: https://github.com/storybookjs/storybook/pull/9661

**Comment by ndelangen** [comment]
I'll open a new issue for https://github.com/storybookjs/storybook/issues/9498#issuecomment-575600598
> Allow specifying manager/preview/(docs?) themes in main.js and recommend that
