### ISSUE TITLE
Addon-Docs: MDX links to internal docs cannot be opened in new tab

### ISSUE THREAD

**Issue by zbream** [storybookjs/storybook#9502]
**Describe the bug**

When writing MDX, opening an internal link in a new tab displays an error due to a malformed URL (see screenshot). This is related to the new `NAVIGATE_URL` functionality introduced in #9328, which is otherwise amazing btw.

The new URL has `iframe.html` before the query string, so presumably the manager isn't getting loaded in the new tab.

**To Reproduce**

1. Go to the following: 
<https://storybookjs.now.sh/official-storybook/?path=/docs/addons-docs-mdx-in-story--typography#links>
2. Open `link to another story (docs)` in new tab, or middle click it.
3. See error in new tab.

**Expected behavior**

The new tab should correctly load the linked docs page.

**Screenshots**

![image](https://user-images.githubusercontent.com/16364440/72567923-ececc580-3884-11ea-816f-5550225cccf0.png)

**System:**

```
  System:
    OS: Windows 10 10.0.17134
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Binaries:
    Node: 12.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.21.1 - C:\Users\zream\AppData\Roaming\npm\yarn.CMD
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1098.0
```

**Comment by zbream** [comment]
I found a workaround while troubleshooting an unrelated problem with Angular routing in a story.

By adding `<base href="/">` to `preview-head.html`, this goes away. Both relative and absolute links work perfectly, as far as I can tell.

I'm unsure if this has any broader implications, but perhaps this should come default on the existing `<base target="_parent">` tag.

**Comment by dimitrieh** [comment]
This issue continues to exist. Is the storybook development team aware of this navigation issue with their platform?

cc: @yannbf

**Comment by dimitrieh** [comment]
I have created a test for internal linking for storybook 7.0 using beta 48 as this issue seems to persist there.

- Test Repo: https://www.loom.com/share/cc3a9260fe4a4adebc66e0cb63557323
- Live URL: https://dimitrieh.github.io/Test-Storybook-7-Internal-Linking (behaved differently than the one locally spun up in dev mode)
- Loom video: https://www.loom.com/share/cc3a9260fe4a4adebc66e0cb63557323 

Other related issues: 
- https://github.com/storybookjs/storybook/issues/8618
- https://github.com/storybookjs/storybook/issues/17921

cc: @yannbf

**Comment by shilman** [comment]
Crikey!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-rc.4 containing PR #21569 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```

**Comment by dimitrieh** [comment]
@shilman amazing! We'll be trying this out as soon as we migrated to 7.0 🥳
