### ISSUE TITLE
Addon-Docs: Props table won't be generated for TypeScript types if forwardRef used with the default export

### ISSUE THREAD

**Issue by SirMoustache** [storybookjs/storybook#9511]
**Describe the bug**
If forwardRef used without named export and with only default one, then no props table will be generated.

For example, this:

**Button.tsx**
```tsx
import React, { forwardRef } from 'react';

interface ButtonProps {
  /**
   * Sets the button size.
   */
  variant?: 'small' | 'large';
  /**
   * Disables the button.
   */
  disabled?: boolean;
}

const Button = forwardRef<HTMLButtonElement, ButtonProps>(
  ({ disabled = false, variant = 'small', children }, ref) => (
    <button disabled={disabled} ref={ref}>
      {children} {variant}
    </button>
  ),
);

export default Button;
```

**Button.stories.tsx**
```tsx
import React, { FC } from 'react';
import Button from './Button';

export default { title: 'Button', component: Button };

export const Default: FC = () => <Button>I'm a button!</Button>;
```
Will lead to this result:

![image](https://user-images.githubusercontent.com/8169559/72607436-5b835f00-3929-11ea-9ee3-b1318796bc9d.png)

But if I add **export**, a props table will be generated. No need to change import from default to named, jus add export.
 
```tsx
export const Button = forwardRef<HTMLButtonElement, ButtonProps>(
  ({ disabled = false, variant = 'small', children }, ref) => (
    <button disabled={disabled} ref={ref}>
      {children} {variant}
    </button>
  ),
);
```

![image](https://user-images.githubusercontent.com/8169559/72611731-8377c000-3933-11ea-9258-37e0d81ab2c7.png)

**Expected behavior**
A props table should be generated 

**Packages**

```
{
    "@storybook/addon-actions": "^5.3.5",
    "@storybook/addon-docs": "^5.3.5",
    "@storybook/addon-links": "^5.3.5",
    "@storybook/addons": "^5.3.5",
    "@storybook/preset-create-react-app": "^1.5.1",
    "@storybook/preset-typescript": "^1.2.0",
    "@storybook/react": "^5.3.5"
}
```

**main.js**
```javascript
module.exports = {
  stories: ['../src/**/*.stories.(tsx|mdx)'],
  addons: [
    {
      name: '@storybook/preset-create-react-app',
      options: {
        tsDocgenLoaderOptions: {},
      },
    },
    {
      name: '@storybook/addon-docs',
      options: {
        configureJSX: true,
      },
    },
  ],
};

```

**Comment by Zunaib** [comment]
**Hi,**
You are missing the export keyword before the Component's name.
You have to **export** const {Component} too, as react-docgen-typescript-loader has not added support for forwardRef's yet.
```
import React, { forwardRef } from 'react';

interface ButtonProps {
  /**
   * Sets the button size.
   */
  variant?: 'small' | 'large';
  /**
   * Disables the button.
   */
  disabled?: boolean;
}

//Add export here
export const Button = forwardRef<HTMLButtonElement, ButtonProps>(
  ({ disabled = false, variant = 'small', children }, ref) => (
    <button disabled={disabled} ref={ref}>
      {children} {variant}
    </button>
  ),
);

export default Button;
```

**Comment by MateusAndrade** [comment]
Thanks @Zunaib , applying the docs-gen at webpack fixed that.

For anybody having this problem, you just need to add a docs gen for TS after you TS loader. Like that:

```js
      {
        test: /\.tsx?$/,
        include: path.resolve(__dirname, '../src'),
        loader: 'awesome-typescript-loader', //any loader you want
      },
      {
        test: /\.tsx?$/,
        include: path.resolve(__dirname, '../src'),
        loader: 'react-docgen-typescript-loader',
      },
```

Then it worked like a charm! 💃 

<img width="991" alt="Screen Shot 2020-01-19 at 12 49 39" src="https://user-images.githubusercontent.com/15278828/72683862-35d98f80-3aba-11ea-8a59-d7307322cf07.png">

**Comment by Zunaib** [comment]
Happy To Help

**Comment by shilman** [comment]
Repro: https://github.com/storybookjs/storybook/commit/1032b774211f15e67c3f9a01b28633a44a83a2d3

**Comment by taze-fullstack** [comment]
@shilman chiming in on this with the CRA + TS template (not able to have a customized webpack to apply @MateusAndrade's solution :<) 

Also not sure if this is actually a separate issue but I feel like this is very closely related to this one so I'll just comment here.

### **Without forwardRef:** 
![image](https://user-images.githubusercontent.com/36070737/75147789-1aa51400-5739-11ea-8c5a-280b60ee64da.png)
```jsx
export const Hello = ({title, children}: HelloProps) => {
  return <div className="hello">Hello Component {title} {children}</div>;
};
```

### **With forwardRef:**
![image](https://user-images.githubusercontent.com/36070737/75148100-ca7a8180-5739-11ea-8b9a-d292a530ea69.png)
```jsx
export const Hello = forwardRef<HTMLDivElement, HelloProps>(
  ({title, children}, ref) => {
    return (
      <div className="hello" ref={ref}>
        Hello Component {title} {children}
      </div>
    );
  }
);

```

**Comment by thany** [comment]
If I add an export, I get only two props in the props table: `ref` and `key`. Both are not useful to display there. I actually have a whole interface defined that is still completely ignored.

```typescript
export const FormInputCheckbox = React.forwardRef<Ref, React.PropsWithChildren<IFormInputCheckRadio>>
```

At least the error is gone, but we're not there yet.

**Comment by shilman** [comment]
FYI the recommended 6.0 setup (should work in 5.3 too) is ready, and is the default in the most recent versions of both `@storybook/preset-typescript` and `@storybook/preset-create-react-app`:

https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#react-prop-tables-with-typescript

I am commenting on all props-related issues to request that you upgrade so we can get this right before release. Thanks!

Also, Args-based props tables are available in 6.0 alpha:

gist.github.com/shilman/69c1dd41a466bae137cc88bd2c6ef487

**Comment by thany** [comment]
Sooo, what should I actually *do*, to try out the new setup? Currently our SB instance still uses RDTL and removing it from the `config.module.rules` simply breaks *all* props tables.

I'm on SB 5.3.18.

**Comment by shilman** [comment]
@thany do you have a repro I can look at?

**Comment by thany** [comment]
@shilman, I'm sorry, but our project is private. I don't have another project that reproduces the problem. I think mosty I just need to know *how* I'm supposed to implement BPRD, because the migration guide doesn't speak of it. It just says "use BPRD", basically, but how?

**Comment by gius** [comment]
I had the same problem with the `6.1.20` version. It turned out you should not use `React.xxx` reference and directly use the decomposed member `xxx`:

```ts
// does not work
export const Button: React.FunctionComponent<ButtonProps> = props => {...}

// works
export const Button: FunctionComponent<ButtonProps> = props => {...}


// does not work
export const Button3 = React.forwardRef<RawButton, ButtonProps>((props, ref) => {...}

// works
export const Button = forwardRef<RawButton, ButtonProps>((props, ref) => {...}
```

Moreover, just changing the type while Storybook is running in watch mode does not work. You need to restart the storybook (or force a full recompilation of the file).

**Comment by iwan-uschka** [comment]
https://github.com/storybookjs/storybook/issues/18136 is somehow related and might help someone.
