### ISSUE TITLE
lit-html missing when installing web_components 

### ISSUE THREAD

**Issue by mbulfair** [storybookjs/storybook#9512]
**Describe the bug**
When running `npx -p @storybook/cli sb init -t web_components` 

The documentation says some dependencies are installed, but they aren't

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/5325543/72614733-07fd1b00-3901-11ea-8555-bbb740bb693f.png)

![image](https://user-images.githubusercontent.com/5325543/72614817-3b3faa00-3901-11ea-80f4-0ed3c425a6e0.png)

**Code snippets**
`npm WARN @storybook/web-components@5.3.6 requires a peer of lit-html@^1.0.0 but none is installed. You must install peer dependencies yourself.`
**System:**
```bash
Environment Info:

  System:
    OS: macOS 10.15.2
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
    Yarn: 1.10.1 - /usr/local/bin/yarn
    npm: 6.13.6 - ~/.nvm/versions/node/v12.13.1/bin/npm
  Browsers:
    Chrome: 79.0.3945.117
    Firefox: 72.0.1
    Safari: 13.0.4
  npmPackages:
    @storybook/web-components: ^5.3.6 => 5.3.6
  npmGlobalPackages:
    @storybook/cli: 5.3.5

```

**Comment by shilman** [comment]
cc @daKmoR

**Comment by daKmoR** [comment]
I don't really understand? do you want to automatically setup `lit-html` as a devDependency to the projects?

on storybook it is a peerDependency and that gives you
```
npm WARN @storybook/web-components@5.3.6 requires a peer of lit-html@^1.0.0 but none is installed. You must install peer dependencies yourself.
```
which means you have to do that yourself?

is that the step you want to change?

**Comment by mbulfair** [comment]
I think my point is the docs that I found say its there, but it's not so if you run the basic install, then start storybook you get an error. I doubt that's the intent is it? I just like clear documentation. Also is this ready? since it's not listed on the main storybook doc site? I'm having issues with mdx docs with my web components as well.
