### ISSUE TITLE
No sidebar in Storybook UI

### ISSUE THREAD

**Issue by BrianD91** [storybookjs/storybook#9519]
**Describe the bug**
When I run `yarn storybook` it compiles and opens in a browser as normal, but the sidebar UI / stories list doesn't render

**Expected behavior**
The search textfield and list of stories will appear in a sidebar on the UI

**Screenshots**
![image](https://user-images.githubusercontent.com/37163937/72645036-99d84880-3940-11ea-87c7-4e18e8bc4512.png)

**Comment by shilman** [comment]
- Try hitting "f" on your keyboard to toggle fullscreen
- Try doing `localStorage.clear()` in browser console & hard refreshing page

**Comment by coreybruyere** [comment]
For anyone being linked to this thread, hitting the "s" key toggled by sidebar back. Is there documentation for this somewhere?

**Comment by jonniebigodes** [comment]
@coreybruyere i'm going to address this shortly. Soon i'll expand the documentation to include this as well.

**Comment by jankalfus** [comment]
It would be nice to display a small popup somewhere on how to exit the fullscreen mode. It's so easy to mispress "F" when searching for something on a page (Ctrl + F), without realizing that one pressed it without the Ctrl key.

**Comment by justin-longbottom** [comment]
Is there no UI element to restore the sidebar? It HAS to be this undocumented keyboard shortcut?

**Comment by hcientist** [comment]
in case others find this like I just have, It turns out the in my case I needed to press <kbd>s</kbd>, as [answered on SO here](https://stackoverflow.com/a/64957511/1449799).

n.b. the suggestion above to do `localStorage.clear()` was insufficient, but as mentioned in an earlier answer on the same (linked) SO question, `sessionStorage.clear()` worked.

**Comment by toppsdown** [comment]
Hello from 2025. The "s" button doesn't seem to do anything now. ~Still searching for a solution~

It's Option - S
