### ISSUE TITLE
Vue version in template

### ISSUE THREAD

**Issue by rijkvanzanten** [storybookjs/storybook#9520]
**Describe the bug**
While writing a story, I noticed that Storybook's `template` string doesn't play nicely with Vue's scoped slot syntax. This indicates to me that the Vue version that's used to render the template string is < 2.6. 

**To Reproduce**
1. Create a `.stories.js` file that renders a Vue component as follows:

```js
export default {
  title: 'MyButton'
};

export withText = () => ({
  template: '<v-button><v-icon #icon /></v-button>'
});
```

2. Note how 
`'<v-button><v-icon #icon /></v-button>'` does not work as expected, while 
`'<v-button><v-icon slot="icon" /></v-button>'` does.

**Expected behavior**
I expected Storybook to render this template with the Vue version that's installed in `node_modules`. Which in my case is `2.6.11` (according to `yarn list`).

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System:**
```
Environment Info:

  System:
    OS: macOS 10.15.2
    CPU: (12) x64 Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz
  Binaries:
    Node: 12.13.0 - ~/n/bin/node
    Yarn: 1.21.1 - ~/n/bin/yarn
    npm: 6.13.6 - ~/n/bin/npm
  Browsers:
    Chrome: 79.0.3945.117
    Firefox: 70.0.1
    Safari: 13.0.4
  npmPackages:
    @storybook/addon-actions: ^5.3.3 => 5.3.6 
    @storybook/addon-centered: ^5.3.6 => 5.3.6 
    @storybook/addon-knobs: ^5.3.6 => 5.3.6 
    @storybook/addon-links: ^5.3.3 => 5.3.6 
    @storybook/addon-notes: ^5.3.6 => 5.3.6 
    @storybook/addons: ^5.3.3 => 5.3.6 
    @storybook/vue: ^5.3.3 => 5.3.6 
```

**Additional context**
What is this template string rendered with? How can I upgrade the Vue version in use here? The `slot=""` syntax will be deprecated in Vue 3, so I'd like to keep my stories / components as "future proof" as possible.

**Comment by shilman** [comment]
@pksunkara @Aaron-Pool @pocka any thoughts?

**Comment by pksunkara** [comment]
Additional context, Latest @storybook/vue devDependencies has

```
  'babel-preset-vue': '^2.0.2',
  vue: '^2.6.8',
  'vue-loader': '^15.7.0',
  'vue-template-compiler': '^2.6.8'
```

**Comment by Aaron-Pool** [comment]
@rijkvanzanten Any public code that I can easily pull down and debug?
