### ISSUE TITLE
Live examples for next and current releases throw 404

### ISSUE THREAD

**Issue by whitebackdoor7** [storybookjs/storybook#9528]
**Describe the bug**
Live examples for next and current releases throw 404.

**To Reproduce**
1. Go to [https://storybook.js.org/docs/basics/live-examples/](https://storybook.js.org/docs/basics/live-examples/)
2. Click on any example from next and current releases.
3. See error: `404: NOT_FOUND
Code: RESOURCE_NOT_FOUND`

**Expected behavior**
Live examples for next and current releases should work.

**Screenshots**
<img width="470" alt="Screen Shot 2020-01-18 at 4 41 28 PM" src="https://user-images.githubusercontent.com/45042199/72666348-8fd24a80-3a11-11ea-87f4-4adaac789440.png">

**Comment by shilman** [comment]
I think this might be a service issue on Now. @ndelangen WDYT?

**Comment by whitebackdoor7** [comment]
Still broken for me.

**Comment by shilman** [comment]
@whitebackdoor7 the deployed content is wrong. The links themselves are correct

**Comment by whitebackdoor7** [comment]
Right @shilman

**Comment by ndelangen** [comment]
Yeah the script to build-storybooks is broken on now.sh, though it works locally & on CircleCI.

This isn't the first time now.sh has some issue (presumably cache).

It's a bit frustrating to say the least.

**Comment by ndelangen** [comment]
I'm attempting to migrate (back) to netlify for the examples

**Comment by shilman** [comment]
Jeepers creepers!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-alpha.2 containing PR #9585 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Olé!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.10 containing PR #9585 that references this issue. Upgrade today to try it out!

**Comment by twhoff** [comment]
Hi @shilman, is there any chance you could post the links to the updated live examples? They've been offline quite a while...

**Comment by shilman** [comment]
https://next--storybookjs.netlify.com/

**Comment by ndelangen** [comment]
We should get this on master asap
https://github.com/storybookjs/storybook/pull/9653
