### ISSUE TITLE
Applying custom styles to Storybook components doesn't work

### ISSUE THREAD

**Issue by ArrayKnight** [storybookjs/storybook#9532]
**Describe the bug**
When trying to apply styles (new or override) to Storybook components (not all have been tested, but should be), the styles do not get applied.

**To Reproduce**
See code sample below.

**Expected behavior**
Styles are applied.

**Screenshots**
![image](https://user-images.githubusercontent.com/5431637/72669494-ff7f1000-39e6-11ea-9a8b-f835da5d0631.png)

**Code snippets**
```
import { Form } from '@storybook/components'
import { css, styled } from '@storybook/theming'

const { Field } = Form

export const AField = styled(Field)`
    padding: 0;
    margin: 0;
    color: red;
`

export const BField = styled(Field)(({ theme }) => ({
    padding: 0,
    margin: 0,
    color: 'red',
}))

export const CField = styled(Field)(
    ({ theme }) => css`
        padding: 0;
        margin: 0;
        color: red;
    `,
)
```

**System:**
Environment Info:

  System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz
  Binaries:
    Node: 10.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.15.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.11.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0

I'm using Chrome Version 79.0.3945.130 (Official Build) (64-bit), but browser doesn't matter.

"@storybook/addons": "^5.3.6",
"@storybook/api": "^5.3.6",
"@storybook/components": "^5.3.6",
"@storybook/core-events": "^5.3.6",
"@storybook/theming": "^5.3.6",

**Additional context**
This is true if using styled from @storybook/theming or from @emotion/styled and no matter which syntax is used.

**Comment by ArrayKnight** [comment]
"@storybook/addons": "^5.3.6",
"@storybook/api": "^5.3.6",
"@storybook/components": "^5.3.6",
"@storybook/core-events": "^5.3.6",
"@storybook/theming": "^5.3.6",

**Comment by shilman** [comment]
@ndelangen any ideas?

**Comment by ndelangen** [comment]
Adding this to my todo list

**Comment by ndelangen** [comment]
Yes, I know what's going on, opening a PR

**Comment by shilman** [comment]
Jeepers creepers!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-alpha.2 containing PR #9665 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Ta-da!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.10 containing PR #9665 that references this issue. Upgrade today to try it out!
