### ISSUE TITLE
Update or expose maxDepth for telejson

### ISSUE THREAD

**Issue by ArrayKnight** [storybookjs/storybook#9534]
**Is your feature request related to a problem? Please describe.**
I'm working on building an addon and when trying to pass graphql-tag DocumentNode(s) through parameters, data is lost (stringified) at a certain depth and queries are rendered useless.

**Describe the solution you'd like**
I'd like to be able to set the max depth (via register config?)

**Describe alternatives you've considered**
I also tried to avoid using the useParameter hook and to pass the parameter through the channel from decorator to panel. But it seems to have the same issue since all data in coming from the same store.

An alternative would be to find a solution that has an extreme or "infinite" max depth

**Are you able to assist bring the feature to reality?**
Not right now

**Comment by ArrayKnight** [comment]
Update: It may actually be as simple as adding the same maxDepth option to the parse call:
https://github.com/storybookjs/storybook/blob/next/lib/api/src/lib/store-setup.ts#L12

It appears that options are not shared, and need to be passed to both:
https://github.com/storybookjs/telejson/blob/master/src/index.ts#L378

50 may be enough, though I wouldn't mind it being higher just in case.

**Comment by ArrayKnight** [comment]
I initially thought this was part of:
https://github.com/storybookjs/storybook/blob/next/lib/api/src/lib/store-setup.ts#L8

But now I think it's actually:
https://github.com/storybookjs/storybook/blob/next/lib/channel-postmessage/src/index.ts#L78

**Comment by shilman** [comment]
cc @ndelangen @tmeasday

**Comment by tmeasday** [comment]
Can you tell us a bit more about the data you are sending over @ArrayKnight?

**Comment by ndelangen** [comment]
This is already possible:

https://github.com/storybookjs/storybook/blob/2046e904e5c78491929d111915dceccc94283dc6/addons/actions/src/preview/action.ts#L13-L32

https://github.com/storybookjs/storybook/blob/341fc2d90d4f3ae42fd9b68173b9f7b1856917f0/lib/channels/src/index.ts#L71-L79

https://github.com/storybookjs/storybook/blob/7e18c2e41f018e95e9ff99b87cd6f4333049c726/lib/channel-postmessage/src/index.ts#L62-L71

**Comment by ArrayKnight** [comment]
@tmeasday I'm sending through a DocumentNode which is created with a `gql\`...\`` tag for a GraphQL query.

@ndelangen I'll have to give this a closer look. Is this documented anywhere?

**Comment by ArrayKnight** [comment]
@ndelangen I'm seeing how you'd be able to set the depth manually for each emit but this doesn't appear to be configurable for the issue I'm having.

In a story:
```
import { gql } from '@apollo/client'

export default {
    ...,
    parameters: {
        myAddon: {
            foo: gql`
                {
                    artworks {
                        artist {
                            name
                            location
                        }
                        imageUrl
                        title
                    }
                }
            `
        }
    }
}
```

In my decorator:
```
export const withMyAddon: (
    options: HeadlessOptions,
) => DecoratorFunction<ReactElement<unknown>> = makeDecorator({
    name: DECORATOR_NAME,
    parameterName: PARAM_KEY,
    skipIfNoParametersOrOptions: true,
    wrapper: (storyFn, context, { options, parameters }) => {
        const channel = addons.getChannel()

        console.log(parameters) // Correctly logs full parameters without a max depth

        return (
            <Decorator
                channel={channel}
                context={context}
                options={options}
                parameters={parameters}
                storyFn={storyFn}
            />
        )
    },
})
```

In my panel:
```
export const Panel = memo(({ active }: Props): ReactElement | null => {
    const parameters = useParameter<MyAddonParameters>(PARAM_KEY, {})

    console.log(parameters) // Max depth has been applied and data is forever lost

    return <></>
})
```

I've been unable to find a way to configure the max depth so that the parameters maintains all data.

Now that I know about manually applying options to each message, I could in theory pass the parameters through the channel from the decorator to the panel, but that doesn't feel like what I'm supposed to do.

Also, it would be really helpful if the `...args: any` somehow included the typing for an optional options object.

**Comment by ArrayKnight** [comment]
@tmeasday To help clarify why I couldn't just send the query as a string over, the `gql` tag creates a validated editing experience that works along with a *.graphql schema file.

**Comment by ndelangen** [comment]
I see, the depth in parameters isn't enough for you.

**Comment by tmeasday** [comment]
@ArrayKnight you could stringify the `DocumentNode` yourself though and pass it as a string?

I'm sure it would be better to be able to control telejson, but essentially that'd be the same thing, no?

**Comment by ArrayKnight** [comment]
That's what I'm having to do currently. But because I'm running into this issue as part of a Storybook addon, it means anybody that wants to use the addon has to do this extra step. My ideal would be to have the addon control telejson so that the end user implementation is as simple as possible.
