### ISSUE TITLE
please allow for a 'manager-body.html" to append to the parent window body

### ISSUE THREAD

**Issue by dennis8844** [storybookjs/storybook#9543]
**Is your feature request related to a problem? Please describe.**

I'd like to add some script at the bottom of the page, and some elements. This way I can wrap the root div in vanila js to hide it and show a login button if the session is not logged in. 

**Describe the solution you'd like**

i can add the google client login package and functions in the manager-head. I need a div to render the login button to in the body.

**Describe alternatives you've considered**

-integrating a react lib would be overkill for such a simple auth. I'd just like SB to work when a member of our organization is looged into their google suite. I'm 99% there. if you do this, it allows for more tweaks.   Cheers

**Are you able to assist bring the feature to reality?**
no | yes, I can...

Yea, but ill be messy

**Additional context**

**Comment by shilman** [comment]
shouldn't need to be messy: https://github.com/storybookjs/storybook/blob/next/lib/core/src/server/utils/template.js

**Comment by dennis8844** [comment]
Cool. I a virgin to commiting to a project like this, but sure! I see the getPreviewBodyHtml grabs a base template. Would A base template need to be created or should I do something else with the base? like grab the manager index or the root div?

```
export function getManagerBodyHtml(configDirPath, interpolations) {
  const base = fs.readFileSync(
    path.resolve(__dirname, '../templates/base-manager-body.html'),
    'utf8'
  );

  const bodyHtmlPath = path.resolve(configDirPath, 'manager-body.html');
  let result = base;

  if (fs.existsSync(bodyHtmlPath)) {
    result = fs.readFileSync(bodyHtmlPath, 'utf8') + result;
  }

  return interpolate(result, interpolations);
}
```
