### ISSUE TITLE
Legacy "selectedName=$name" query parameter doesn't work if story name/id is different

### ISSUE THREAD

**Issue by tmeasday** [storybookjs/storybook#9544]
**Describe the bug**

As we naively map the name to an "story id part" using `toId()` we don't factor in the possibility the story has a non-automatic name. 

**To Reproduce**
```js
export const defaultStory = () => {}
defaultStory.story = { name: 'Default' };
```

1. Browse to http://localhost:6006/iframe.html?selectedKind=kind&selectedName=Default
2. Notice it redirects you to http://localhost:6006/iframe.html?id=kind--default

**Expected behavior**
It should redirect you to the actual story id, ie `kind--default-story` in this case.

**Comment by shilman** [comment]
Yowza!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.7 containing PR #9545 that references this issue. Upgrade today to try it out!

Closing this issue. Please re-open if you think there's still more to do.

**Comment by tmeasday** [comment]
@shilman it seems this bug is also present in 5.2, we should probably backport the fix.

**Comment by shilman** [comment]
@tmeasday We’ve never backported a fix to a minor version before and I’m not sure I want to get into the habit of it. We’ve done it across major versions and I’m happy to do that when needed. What’s wrong with forcing people to upgrade to 5.3 for the fix?
