### ISSUE TITLE
Update @storybook/react react-dev-utils dependency to v10

### ISSUE THREAD

**Issue by robcaldecottvelo** [storybookjs/storybook#9551]
**Storybook 5.3.6**

We have a fairly complicated yarn monorepo and are seeing build problems when using node 12 on MacOS due to an old version of `fsevents` that is ultimately being pulled in via the v9 `react-dev-utils` dependency of `@storybook/react`. However, `react-dev-utils` is now at v10 (and is the version used by `create-react-app` v3.3.0) and we believe this will help address the `fsevents` issue. Would it be possible to upgrade Storybook to use this later version?

We can workaround this by hand-tweaking our `yarn.lock` but it might be good to have Storybook use the same core package versions as `create-react-app`? I am happy to open a PR if the team think this is worthwhile.

**Comment by shilman** [comment]
@robcaldecottvelo mind submitting a small PR for that?
