### ISSUE TITLE
stories displays none after trigger auto refresh

### ISSUE THREAD

**Issue by Pain-and-Love** [storybookjs/storybook#9553]
**Describe the bug**
after auto refresh, other stories displays none;
**To Reproduce**
1. Go to 'OverView.stories.tsx'
2. change the``` OverView.story = { name: 'OverView111' }``` or any other modify can trigger the Chrome auto refresh
3. back to the Chrome waiting for the refresh
**Expected behavior**

**Screenshots**
before modify the  OverView story
![image](https://user-images.githubusercontent.com/9690422/72719575-183c2100-3bb3-11ea-8e54-6bf35b26ce0d.png)
after modify the OverView story (without any action expect change the story name to OverView111)
![image](https://user-images.githubusercontent.com/9690422/72719726-56d1db80-3bb3-11ea-8376-9418397b407d.png)

**Code snippets**
-

**System:**

**Additional context**
version 5.3.12。
it is possible that something results in the auto reload or HMR disabled...  is it a bug?

**Comment by benjipott** [comment]
Sorry mister bot 🤖 but this isssue affect our development time so I think that can be fixed

**Comment by shilman** [comment]
do you have a repro?

**Comment by Pain-and-Love** [comment]
> do you have a repro?

no,but u can start a new storybook project. then u can find it.
after trigger HMR, the stories except the modified one display none in the side bar
