### ISSUE TITLE
NPM/Yarn Cannot find the latest version 

### ISSUE THREAD

**Issue by SimonSch** [storybookjs/storybook#9554]
**Describe the bug**
When trying to install the lastest versions(+5.2.8) via npm or yarn I get an error message that it is not able to find the package.

**To Reproduce**
1. Add "@storybook/angular" to package.json
2. run install 
3. See error

**Expected behavior**
The latest version is found and installed

**Screenshots**
`Couldn't find any versions for "@storybook/angular" that matches "5.3.3"
? Please choose a version of "@storybook/angular" from this list:
  3.3.0-alpha.0
  5.3.0-rc.12
  5.3.0-rc.11
  5.3.0-rc.10
  5.3.0-rc.9
  5.3.0-rc.8
  5.3.0-rc.7
  5.3.0-rc.6
  5.3.0-rc.5
  5.3.0-rc.4
  5.3.0-rc.3
`

**System:**
Environment Info:

  System:
    OS: Windows 10 10.0.17134
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 11.7.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.6 - C:\Program Files\nodejs\npm.CMD

**Comment by shilman** [comment]
Try clearing your yarn cache? There are multiple 5.3.x versions on NPM:

https://www.npmjs.com/package/@storybook/angular

**Comment by SimonSch** [comment]
Tried that already, still have the same issue. Tried it on another computer  and have the same problem.

**Comment by shilman** [comment]
@SimonSch i can't repro, and we have over 50,000 people installing `@storybook/angular` each week, so I don't know what to say.

**Comment by SimonSch** [comment]
After cleaning my yarn cache, deleting all node_modules, invalidating caches in Intellij and restarting it seem to have finally worked. Could have also been a internal infrastructure problem on my side.
