### ISSUE TITLE
Support config addons panel position

### ISSUE THREAD

**Issue by Jiavan** [storybookjs/storybook#9555]
**Is your feature request related to a problem? Please describe.**
Addons panel it's always appear to the page bottom, when I run `yarn storybook`, but I want to rendering it at right side forever. Now I just can only click the `change orientation` button to change it.

**Describe the solution you'd like**
Addons panel's position is configurable, add options in main.js or CLI.

**Describe alternatives you've considered**
// none

**Are you able to assist bring the feature to reality?**
yes

**Additional context**
// none

**Comment by shilman** [comment]
See `panelPosition` parameter: https://storybook.js.org/docs/configurations/options-parameter/

**Comment by gyenabubakar** [comment]
@shilman Content of `.storybook/manager.ts` doesn't do it:

```ts
import { addons } from '@storybook/manager-api';

addons.setConfig({
  panelPosition: 'right',
});
```

**Comment by thenick775** [comment]
^ bump, same here

**Comment by gyenabubakar** [comment]
@thenick775 re-run the `storybook` script and try opening a new tab if re-running alone doesn't make a difference. I dunno why I had to that.
