### ISSUE TITLE
In README, rax example online link is not found

### ISSUE THREAD

**Issue by SoloJiang** [storybookjs/storybook#9572]
**Describe the bug**
https://storybooks-rax.netlify.com/ this link is not found.

**To Reproduce**
Click README **Supported Frameworks** table.

**Expected behavior**
A real link

**Comment by shilman** [comment]
@SoloJiang our now deployment broke and it's now been moved to https://storybookjs.netlify.com. Can you fix it in the docs?

**Comment by SoloJiang** [comment]
Okay, I will solve it later~
