### ISSUE TITLE
Docs tab shows 'no code available' when using dynamic title for story

### ISSUE THREAD

**Issue by aizerin** [storybookjs/storybook#9582]
**Describe the bug**
When creating story with dynamic title, story shows no code available.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create story with dynamic title
2. Start storybook
3. See the docs tabs

**Expected behaviour**
Code will be available

**Screenshots**

![image](https://user-images.githubusercontent.com/18553162/72805215-a0bdce80-3c52-11ea-874b-3ea4f133eea3.png)

**Code snippets**

```
import React from "react";
import { Button } from "@storybook/react/demo";

const createTitle = title => `a/${title}`;

export default {
  title: createTitle("NokButton"),
  component: Button
};

export const Text = () => <Button>Hello Button</Button>;
```

**System:**

```
  System:
    OS: macOS 10.15.2
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.12.1 - ~/.nvm/versions/node/v12.13.1/bin/npm
  Browsers:
    Chrome: 79.0.3945.130
    Firefox: 70.0.1
    Safari: 13.0.4
  npmPackages:
    @storybook/addon-actions: ^5.3.7 => 5.3.7
    @storybook/addon-docs: ^5.3.7 => 5.3.7
    @storybook/addon-links: ^5.3.7 => 5.3.7
    @storybook/addons: ^5.3.7 => 5.3.7
    @storybook/react: ^5.3.7 => 5.3.7
```

**Comment by ibrahimchraibi** [comment]
Same issue here :(

**Comment by shilman** [comment]
cc @atanasster

**Comment by atanasster** [comment]
I can reproduce - source-loader is not loading locationsMap for such stories.
I will take a look again when we check in the new source-loader.

**Comment by shilman** [comment]
Yeah, just wanted to give you a head's up for the new one!

**Comment by TakenPilot** [comment]
Still true, still an issue.

**Comment by DScheglov** [comment]
It is still an issue.

The case:

**File Structure**:

```bash
./components/
├── atoms
│   └── Heading
│       ├── index.d.ts
│       ├── index.js
│       ├── index.stories.js
│       └── index.test.js
├── molecules
│   └── FormField
│       ├── index.d.ts
│       ├── index.js
│       ├── index.stories.js
│       └── index.test.js
└── story-names.js
```

**./components/story-names.js**:
```js
export const ATOM = name => `1-Atoms/${name}`;
export const MOLECULE = name => `2-Molecules/${name}`;
export const ORGANISM = name => `3-Organisms/${name}`;
export const TEMPLATE = name => `4-Templates/${name}`;
export const PAGE = name => `5-Pages: ${name}`;
```

**./components/atoms/Headings/index.stories.js**
```js
import React from "react";
import { ATOM } from "../../story-names";
import Heading from ".";

export default {
	component: Heading,
	title: ATOM("Heading"),
};

// some stories for Heading
```

The result:
![image](https://user-images.githubusercontent.com/9888941/78073727-1b6d3d80-73aa-11ea-9823-2c863b16bdf2.png)

Fix **./components/atoms/Headings/index.stories.js**
```js
// ...imports
export default {
	component: Heading,
	title: "1-Atoms/Heading"
};
// ...stories
```
The result:
![image](https://user-images.githubusercontent.com/9888941/78074164-e44b5c00-73aa-11ea-987e-bdbe7cea00a4.png)

Please fix it.

**Motivation**
To reduce efforts required to keep stories in specific structure the story names are generated with functions.

**Comment by shilman** [comment]
@DScheglov would you like to submit a PR for this?

**Comment by DScheglov** [comment]
> @DScheglov would you like to submit a PR for this?

Oh! It's an interesting task due it requires deep diving in the source-loader. But I have lack of time for job projects ...

So, Sorry. For now, I cannot collaborate more then just register/comment issues.

**Comment by timmaloshtan** [comment]
Same issue :(

**Comment by DScheglov** [comment]
it is still actual

**Comment by deholger** [comment]
This topic is still actual with 6.0 betas

**Comment by adamborowski** [comment]
I think that current approach is invalid. The loader adds a preamble to the file and it needs storybook title to be present at compile time.

The better approach would be to replace part of AST by injecting special story parameter.

That way we don't care about title and the addon still can access the source metadata but not from a 'register' queried by story id. Instead it can read this just from story parameter.
