### ISSUE TITLE
When using addon-docs with multiple embedded stories the toolbar disappears

### ISSUE THREAD

**Issue by ahdigital** [storybookjs/storybook#9593]
**Describe the bug**
The toolbar which normally shows buttons to zoom in | out | reset and open story in new tab are missing from the top of my stories, apart from one.

It looks like once this toolbar has been rendered once, for one story in my app any other story doesn't have it.

This is my first time using Storybook, and the addon-docs plugin following the Git docs. The framework is Angular.

**Expected behavior**
A toolbar showing default controls to be shown for each story embedded in my page no matter if the story was written in JS|TS|MDX.

**Screenshots**

![image](https://user-images.githubusercontent.com/3088454/72895567-90baf300-3d15-11ea-8bb7-337a3f945f70.png)

**Code snippets**

_index.stories.js_
```
import { Button } from '@storybook/angular/demo';

export default { title: 'My Button', component: Button }

export const withText = () => ({
  component: Button,
  props: {
    text: 'Hello Button',
  },
});

export const withEmoji = () => ({
  component: Button,
  props: {
    text: '😀 😎 👍 💯',
  },
});
```

_example2.stories.mdx_
```
import { Meta, Story, Preview } from '@storybook/addon-docs/blocks';
import { Button } from '@storybook/angular/demo';

<Meta title="Linked with ID" component={Button} />

# Button

<Preview>
  <Story id="my-button--with-text"/>
</Preview>
```

**System:**
  System:
    OS: Windows 10 10.0.17134
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  Binaries:
    Node: 12.13.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.13.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1098.0

**Comment by shilman** [comment]
Sorry for the slow response. The behavior you describe is by design. In "DocsPage", the default docs that are generated for your stories, the first ("primary") story gets the toolbar and the rest don't.

If you want to show the toolbars, it's possible to customize DocsPage https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/docspage.md#replacing-docspage

**Comment by ricovitch** [comment]
I'm also interested in a simple solution to allow toolbar display on the <Preview /> component in DocsPage.
Our use case is that we build storybook with Docs page only, and we want to allow users to open standalone stories for some stories that involve responsive behaviors or layout logic demonstration.

Actually this works : <Preview withToolbar />
But it does not show the "open canvas in new tab" icon button.

**Comment by JKoehler11** [comment]
@ricovitch  Were you able to solve this?

I have some pages that are Docs only and I have a need to show the responsive layout button for some of the stories.

**Comment by alfredosalzillo** [comment]
> I have some pages that are Docs only and I have a need to show the responsive layout button for some of the stories.
> 
> Update:
> I was able to get the toolbar to display, however, it does not show the @storybook/addon-toolbars and instead only shows the zoom and open in a new page link.
> 
> To get that to show up I used:
> `<DocsStory id="my-story" withToolbar />`

@ghost any news? I have the same problem
