### ISSUE TITLE
docs: what are the differences between `main.js`, `preview.js`, `manager.js`?

### ISSUE THREAD

**Issue by lidoravitan** [storybookjs/storybook#9594]
### Issue
Can't find any documentation about what the difference between `main.js`, `preview.js`, `manager.js`.
when should I use/choose each one? what are their lifecycle (I mean do they load before/after the env)?

**Comment by shilman** [comment]
@lidoravitan can you review this PR and add questions as comments there?

**Comment by lidoravitan** [comment]
@shilman sure I'm on it! thanks for response

**Comment by goepi** [comment]
What are after all the differences between all these different files???

It's nowhere to be found in the docs. Take "Using addons" for example; the docs say to add something to main.js, then later in a section entitled "global configuration" it says "To do that, you can add your decorators to a config file, typically in .storybook/preview.js.", but nowhere is it explained what "typically" even means. 

I don't know what I should put in preview.js vs main.js

**Comment by shilman** [comment]
cc @ndelangen

**Comment by ndelangen** [comment]
Here's where it's explained, but it's missing in the docs for some reason:
https://github.com/storybookjs/storybook/blob/next/docs/src/pages/configurations/overview/index.md

**Comment by ndelangen** [comment]
@shilman do we deploy the docs for next somewhere somehow?

**Comment by shilman** [comment]
@ndelangen No because of the whole "frontpage" / "docs" split. I think we need to patch that into `master`. It came in on this PR, but didn't have the `patch` label:

https://github.com/storybookjs/storybook/pull/9552

I'll do the patch now. Thanks!

**Comment by sme3x** [comment]
You have it all nicely explained here by @shilman - [Migration docs](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#from-version-52x-to-53x)
