### ISSUE TITLE
Unable to define / surcharge sass variable in global scss loaded using inline-loader

### ISSUE THREAD

**Issue by jivane-perich** [storybookjs/storybook#9600]
**Describe the bug**

I'm using storybook for angular, and my project is using bootstrap.

I have a themable component (using $primary and $secondary scss variables of bootstrap), and I'm trying to switch between themes.

In order to visualize the component for each theme, I add the inline loader as per  https://storybook.js.org/docs/configurations/default-config/#css-support and I'm loading variables definition from the loaded file.

The bug : I can't use the inline loader to declare / surcharge sass variable and I can't find a doc or an issue describing how to do it.

**To Reproduce**

A sample project is available here : https://github.com/jivane-perich/angular-storybook

I have tried 2 cases : 
- surcharging a sass variable (no errors, but no action)
- defining a sass variable in my global scss file and use it in my component (compilation error)

**Expected behavior**

The scss file loaded with the inline loader (or another workaround based on a custom webpack config) can be used to surcharge or declare sass variables.

**Code snippets**

A basic test bed is available here : https://github.com/jivane-perich/angular-storybook

When launching storybook, you will see the only story displaying a component with the default theme (green & yellow), instead of a specific theme loaded by the inline loader (red & orange)

**System:**

Results of `npx -p @storybook/cli@next sb info` :

```
Environment Info:

  System:
    OS: Linux 5.3 Ubuntu 19.10 (Eoan Ermine)
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  Binaries:
    Node: 13.7.0 - /usr/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.13.6 - /usr/bin/npm
  Browsers:
    Firefox: 72.0.1
  npmPackages:
    @storybook/addon-actions: ^5.3.2 => 5.3.2 
    @storybook/addon-docs: ^5.3.2 => 5.3.2 
    @storybook/addon-knobs: ^5.3.2 => 5.3.2 
    @storybook/addon-links: ^5.3.2 => 5.3.2 
    @storybook/addon-notes: ^5.3.2 => 5.3.2 
    @storybook/addons: ^5.3.2 => 5.3.2 
    @storybook/angular: ^5.3.2 => 5.3.2
```
 

**Additional context**

**Comment by jivane-perich** [comment]
Can we let this issue open ?
I'm trying to find a workaround. I will post it here if I find it.

**Comment by jivane-perich** [comment]
After investigating more on the issue, I didn't find a way to make it work with Sass.
We are currently using CSS variables defined by boostrap instead.

**Comment by SunilManthenaG01** [comment]
@jivane-perich  I know its been long time but did you find any work around for the above issue that you can remember ?

**Comment by jivane-perich** [comment]
Hi,

As stated before, my workaround is to use CSS custom properties.
Since this issue, we have removed the use of SCSS variables and are instead using CSS custom properties.

Then, we can surcharge the property at runtime in the story.

ex : 

instead of $primary, we are using a css with the following syntax : 

```css
:root {
  --primary: blue;
}

/* surcharge the property with a more specific selector */
.themable {
  --primary: green;
}

.themable {
 color: var(--primary);
}
```

Documentation here : https://developer.mozilla.org/en-US/docs/Web/CSS/--*

In our case, it was relatively easy to switch because bootstrap is declaring the custom properties for us.
