### ISSUE TITLE
Overriding header text of Stories in addon-docs?

### ISSUE THREAD

**Issue by izhan** [storybookjs/storybook#9604]
**Is your feature request related to a problem? Please describe.**
A small nit! It's more common for engineers at my company to talk about "examples" or "usage" rather than "stories". I'd like to change some copy to avoid confusion.

**Describe the solution you'd like**
I'd like to change this header text from `Stories` to something else:
<img width="1114" alt="Image 2020-01-22 at 4 35 22 PM" src="https://user-images.githubusercontent.com/4621962/72947024-890b4680-3d35-11ea-8b15-f8a2b58cc8df.png">

Is there any way? A parameter, etc?

**Describe alternatives you've considered**
My workaround right now is overriding the `defaultProps` of Stories:
```ts
import { Stories } from "@storybook/addon-docs/blocks"

Stories.defaultProps = {
    title: "Usage",
}
```

**Are you able to assist bring the feature to reality?**
Yup!

**Additional context**

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if this is still relevant in SB 7.x.
