### ISSUE TITLE
REACT demo broken

### ISSUE THREAD

**Issue by tweetzal** [storybookjs/storybook#9611]
**Describe the bug**
The react demo is broken.
When I clicke it, it just shows: 

404: NOT_FOUND
Code: RESOURCE_NOT_FOUND
ID: lhr1:49fkm-1579785960719-17bc0f2c5c01

**To Reproduce**
1. Go to https://storybook.js.org/docs/basics/live-examples/
2. Click on 'React'

**Expected behavior**
Should show react demo of storybook

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System:**
Please paste the results of `npx -p @storybook/cli@next sb info` here.

**Additional context**

**Comment by shilman** [comment]
closing as dupe to #9528
