### ISSUE TITLE
After updating to 5.3.8 getStorybook() always returns an empty array

### ISSUE THREAD

**Issue by faberyx** [storybookjs/storybook#9622]
**Describe the bug**
After upgrading to latest 5.3.8 version when calling getStorybook() from a story or from a configuration file always returns an empty array, before on 5.2 I was correctly getting an array of all stories.

Did something change  in the new version?

**Comment by shilman** [comment]
Did you change anything, or is your code identical? Can you share a repro?

I made some changes the story store here, but neither should affect you: https://github.com/storybookjs/storybook/pull/9424 https://github.com/storybookjs/storybook/pull/9482

It's also possible that something related to main.js config could have introduced a regression.

**Comment by faberyx** [comment]
I did update all configuration files according to the 5.3 specifications.

On 5.3 I used to get the stories from the old `config.js` file and from a CSF story, this is actually the code:
```js
/** @jsx createElement */
import { createElement } from 'react';
import CorePaletteComponent from './palette/palette';
import { getStorybook } from '@storybook/react';

const stories = getStorybook();
console.log(stories);

export default {
  title: 'Core UI/Elements'
};
export const ColorPalette = () => <CorePaletteComponent />;
```
`console.log` now returns an empty array, but it works if I save the file and hot reload kicks in, then I get the correct list of stories in the log.

**Comment by shilman** [comment]
cc @ndelangen @tmeasday

**Comment by ndelangen** [comment]
Did the code work before changing to main.js?

I'm thinking that CSF doesn't work together with get Storybook. 

One thing that you might try is wrapping the getStorybook call in a setTimout. 

The problem is that CSF stories evaluate first THEN agree injected into the storystore. 

getStorybook asks the storystore which at this point in the runtime is Emory.

**Comment by ndelangen** [comment]
I'm fairly sure this is NOT a bug in tri-config @shilman

**Comment by shilman** [comment]
sounds like it worked in 5.2 w/ CSF tho?

i touched the story_store (w/ @tmeasday) recently. @faberyx what happens if you revert to 5.3.0? those changes started in 5.3.3.

**Comment by ndelangen** [comment]
At best getStorybook returns an incomplete storystore.

**Comment by faberyx** [comment]
In 5.2.8 I was able to get the list, also I could get the list of storis in the configuration file `.storybook/config.js`
```
import { configure, addDecorator, addParameters } from '@storybook/react';
import { getStorybook } from '@storybook/react';
configure([require.context('../src', true, /\.stories\.tsx$/)], module);

const myStories = getStorybook();

console.log(myStories);
```

now I moved the same code to `preview.js` and the array was also empty here.

Using a setTimeout fixed the problem, so Ill close the issue, thanks!

**Comment by ndelangen** [comment]
Preview.js executes before the configure call automated by main.js

This is by design.

**Comment by jonyw4** [comment]
@faberyx @ndelangen can you share how you get all stories (including _CSF_ files) using `getStorybook` with setTimeout? ([maybe in this discussion too](https://github.com/storybookjs/storybook/discussions/13528))
