### ISSUE TITLE
Automatically test different break points.

### ISSUE THREAD

**Issue by jonathandalgaard** [storybookjs/storybook#9624]
Is it possible to test different break points at the same time without having to resize the window and click rerun tests.

By break points I mean different screen sizes.

I thought about being able to define a set of screen sizes that I want to get tested automatically, and then the A11Y addon will show the results for the given breakpoints.

Is this possible?

**Comment by shilman** [comment]
Tools like https://chromaticqa.com can do this. If you want to do it visually, it would be straighforward to implement in `addon-docs`, but nobody's done it yet.

**Comment by shilman** [comment]
There's also this addon that somebody reminded me of recently. I haven't used it but it might help: https://github.com/vizeat/storybook-addon-responsive-views
