### ISSUE TITLE
Ember.js example app linked in README is a 404

### ISSUE THREAD

**Issue by trek** [storybookjs/storybook#9634]
The example Ember.js application linked here https://github.com/storybookjs/storybook/blob/e1c8ca054aacd8f3bae889746c4a690d476fee26/README.md#L124 results in a 404.

https://storybooks-ember.netlify.com/

**Comment by trek** [comment]
This issue sadly can't be handled by an outside PR: you'd need access to whatever Netflify account is used to host the demo apps.

**Comment by shilman** [comment]
@trek fixed in #10088 and will patch on next release. thanks!!

**Comment by trek** [comment]
@shilman Awesome! I'll close this issue. Thank you so much.
