### ISSUE TITLE
Broken @storybook/addon-contexts types

### ISSUE THREAD

**Issue by TeoTN** [storybookjs/storybook#9639]
**Describe the bug**
Types for `@storybook/addon-contexts@5.3.9` seem to be broken, causing following TypeScript error:
```
Could not find a declaration file for module '@storybook/addon-contexts/react'. '.../node_modules/@storybook/addon-contexts/react.js' implicitly has an 'any' type.
  Try `npm install @types/storybook__addon-contexts` if it exists or add a new declaration (.d.ts) file containing `declare module '@storybook/addon-contexts/react';`  TS7016
```

**To Reproduce**
`import { withContexts } from '@storybook/addon-contexts/react';`

**Expected behavior**
No errors

**Comment by sjwilczynski** [comment]
Same issue for me

**Comment by iansan5653** [comment]
Using
```ts
import { withContexts } from '@storybook/addon-contexts/dist/preview/frameworks/react';
```
Works, but then TypeScript can't determine the type of the `contexts` argument because "Cannot find module '../../shared/types'."

**Comment by TeoTN** [comment]
I'd expect a way to get correct types without knowing internal structure of the library...

**Comment by shilman** [comment]
Looking to replace `addon-contexts` in SB6.0 with `addon-toolbars` that is much simpler and uses Storybook core features (args, decorators). Feedback welcome!

https://github.com/storybookjs/storybook/pull/10028

**Comment by no-todos** [comment]
I wonder if this bug was ever fixed or the only way to solve it is to migrate to next major version?
