### ISSUE TITLE
Test + Storybook

### ISSUE THREAD

**Issue by ndelangen** [storybookjs/storybook#9650]
We have addon-jest & addon-specs & addon-storyshots, all are really limited, but serve some important idea:

> stories are like test, but what about real unit tests & e2e tests?

I think we should come up with a addon or core feature that serves this purpose really well, and deprecate the other 3 options perhaps?

**Comment by anilanar** [comment]
I plan to invest in this, as part of my work, paid by my employer. We were considering a combination of cypress + storybooks, but I'm open to other options as well. I can potentially help make this happen.

**Comment by ndelangen** [comment]
@anilanar Let's get in touch and meet online to pair on ideas?
https://calendly.com/ndelangen/storybook
