### ISSUE TITLE
Missing title error in a MDX story file lacks path to that file

### ISSUE THREAD

**Issue by hasparus** [storybookjs/storybook#9651]
**Describe the bug**
Missing title error in a MDX story breaks all other stories.

**To Reproduce**
1. go to your project
2. start storybook
3. create an empty MDX story
4. 🔥

**Expected behavior**

I see two possible improvements:

1. Preserve the path to the broken file to display it in the error message
2. ~~Contain the error and display it in a toast or in another way that doesn't break access to all other stories~~ (by design)

**Screenshots**

![image](https://user-images.githubusercontent.com/15332326/73218118-93747880-4159-11ea-98ee-bae65277d1ca.png)

**Comment by shilman** [comment]
Is this specific to docs? All story errors result in this UI, and it's a design decision to force users to fix the errors before they can view the storybook.

**Comment by hasparus** [comment]
Okay, so we can discard my point (2).
Totally correct design decision.

Still, the error could guide the user to the file that needs to be fixed.

I have "addon-docs", but I’m running storybook in dev mode. (no —docs flag).

**Comment by shilman** [comment]
That makes sense @hasparus. We can catch the error and re-throw a more user-friendly error in this case. Great call! 💯

**Comment by vanessayuenn** [comment]
Hi! I am going through and cleaning up old issues in the repo. We just shipped a ton of improvements in Storybook 7.0, and I suspect this bug might be fixed already. Can you please try it out? If this issue persists with the latest version, please open a new bug report with a 7.x reproduction. Thank you so much! 🙏🏼
