### ISSUE TITLE
setConfig(theme) in `manager.js` theme definition not applied to addon-docs

### ISSUE THREAD

**Issue by ndelangen** [storybookjs/storybook#9662]
As discussed in:
https://github.com/storybookjs/storybook/issues/9498#issuecomment-575600598

The new method for configuring theme in `manager.js` unfortunately means addon-docs doesn't receive the theme.

This can be quite disturbing when using dark-mode for example.

We should come up with a good method for sharing the theme / defining it once.

We also discussed to users might actually WANT different themes for manager & docs...

**Comment by shubjhamb** [comment]
`setOptions` also didn't work to set theme in docs, If we want to use `setOptions` in our custom addon to switch theme.

**Comment by shilman** [comment]
I think we should just set the docs theme independently in the preview, and update the documentation accordingly. WDYT @ndelangen ? If you're good with that solution I can update the documentation.

**Comment by ndelangen** [comment]
Yeah that would work for me @shilman

**Comment by shilman** [comment]
ZOMG!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-alpha.26 containing PR #10114 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by 0x0006e** [comment]
😔
