### ISSUE TITLE
IE Text Knobs laggy and flickers

### ISSUE THREAD

**Issue by elijah1210** [storybookjs/storybook#9663]
When entering text into the text type knob of addon-knobs, the text flickers and sometimes autocorrects itself.

**Steps to reproduce**

1. Load Storybook in IE
2. Click on the knobs tab and start typing content into the text knob.
3. The input is not super quick and will sometimes autocorrect or characters will disappear.

**Expected behavior**
The text should be entered as I have typed it out.

**Screenshots**
![Issue being demonstrated in my Storybook.](https://user-images.githubusercontent.com/23367979/73274238-402f1400-41b3-11ea-8b85-822cd8b2245a.gif)
![Issue being demonstrated in Storybook Official](https://user-images.githubusercontent.com/23367979/73274380-7c627480-41b3-11ea-88e4-77c1966b38cb.gif)

**System:**
Environment Info:
  System:
    OS: Windows 10 10.0.17763
    CPU: (8) x64 Intel(R) Xeon(R) W-2125 CPU @ 4.00GHz
  Binaries:
    Node: 10.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.17763.831.0

Versions from package.json:
    "@storybook/addon-actions": "5.1.11",
    "@storybook/addon-console": "1.2.1",
    "@storybook/addon-info": "5.1.11",
    "@storybook/addon-knobs": "5.1.11",
    "@storybook/addon-viewport": "5.1.11",
    "@storybook/react": "5.1.11",

**Additional context**
I am able to recreate it to a lesser degree on the storybook [found here](https://storybooks-official.netlify.com/?path=/story/addons-knobs-withknobs--tweaks-static-values) but I have attached screen captures from both my storybook and the official..

**Comment by shilman** [comment]
Maybe debouncing is not working properly in IE11?

**Comment by elijah1210** [comment]
@shilman 
I went into the onChange handler of the editor and logged out the value and it seems to work correctly.

There is a log that happens a few seconds later that contains "message arrived at preview", "storybookjs/knobs/change" and then an object { name, type, value }.

I don't see the same logs in Chrome. Is this the debouncing you're talking about?
