### ISSUE TITLE
When running build-storybook, the build fails with typescript errors from files that aren't even supposed to be built

### ISSUE THREAD

**Issue by AndrewPrifer** [storybookjs/storybook#9666]
**Describe the bug**
When I run storybook in dev mode, all is fine. However when I run build-storybook, the build fails with typescript errors from files that aren't even supposed to be included in the build. These files are not included in the `stories` glob or ever imported into stories. Is it possible that typescript is running type checks on all files instead of just the included ones?

Error:

```
ERR! => Failed to build the preview
ERR! /Users/andrewprifer/Projects/Clinicminds/frontend/src/containers/StaffPlanner/index.tsx
ERR! TypeScript error in /Users/andrewprifer/Projects/Clinicminds/frontend/src/containers/StaffPlanner/index.tsx(139,18):
ERR! Type '{}' is missing the following properties from type 'WorkingTimeEditorProps': workers, locations, onSubmit, onClose  TS2739
ERR! 
ERR!     137 |               </Button>
ERR!     138 |               <Modal open={addModalOpen} onClose={() => setAddModelOpen(false)}>
ERR!   > 139 |                 <WorkingTimeEditor />
ERR!         |                  ^
ERR!     140 |               </Modal>
ERR!     141 |             </div>
ERR!     142 |             <div className={styles.menuItem}>
```

If you look at main.js, you can see that the error is for a file in a directory that is excluded from the `stories` glob.

**To Reproduce**
1. Run `build-storybook`

**Expected behavior**
Storybook build finishes without errors.

**Code snippets**

main.js:
```js
const path = require('path');

module.exports = {
  stories: ['../src/components/**/stories.ts{x,}'],
  addons: [
    {
      name: '@storybook/preset-create-react-app',
      options: {
        tsDocgenLoaderOptions: {},
      },
    },

    '@storybook/addon-actions',
    '@storybook/addon-links',
    '@storybook/addon-contexts',
    '@storybook/addon-docs',
    {
      name: '@storybook/addon-storysource',
      options: {
        rule: {
          test: [/stories\.tsx?$/],
          include: [path.resolve(__dirname, '../src')], // You can specify directories
        },
        loaderOptions: {
          parser: 'typescript',
        },
      },
    },
  ],
};
```

**System:**
```
  System:
    OS: macOS 10.15.2
    CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
  Binaries:
    Node: 12.11.1 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 79.0.3945.130
    Safari: 13.0.4
  npmPackages:
    @storybook/addon-actions: ^5.3.6 => 5.3.6 
    @storybook/addon-contexts: ^5.3.6 => 5.3.6 
    @storybook/addon-docs: ^5.3.6 => 5.3.6 
    @storybook/addon-links: ^5.3.6 => 5.3.6 
    @storybook/addon-storysource: ^5.3.6 => 5.3.6 
    @storybook/addons: ^5.3.6 => 5.3.6 
    @storybook/preset-create-react-app: ^1.5.2 => 1.5.2 
    @storybook/react: ^5.3.6 => 5.3.6 
```

**Comment by shilman** [comment]
@mrmckeb I seem to recall there was some production-specific logic in `preset-cra`?

**Comment by AndrewPrifer** [comment]
Don't close pls, storybook should not depend on unbundled modules. I imagine people don't necessarily want to go and fix all their code every time they want to publish a new storybook version.

**Comment by mrmckeb** [comment]
This is actually an issue in CRA itself from memory. This happens because the [`fork-ts-checker-webpack-plugin`](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/issues) is running against more files than just stories.

In the preset for CRA, we simply lift that config and use it. We don't exclude files. 

I'm not sure there is an easy fix - but we'd welcome a PR @AndrewPrifer. We'd need to be careful though, to ensure we don't exclude the wrong files.

**Comment by AndrewPrifer** [comment]
@mrmckeb I see that fork-ts-checker has a reportFiles option that accepts a glob. If there’s a more or less simple way to modify the lifted CRA config (I imagine there should be), I think we could just pass Storybook’s glob directly to it. What do you think?

**Comment by mrmckeb** [comment]
I'd argue that only type checking stories may not be expected behaviour.

I personally would expect an error if my component had type errors. This is why I think the issue is complex.

**Comment by AndrewPrifer** [comment]
@mrmckeb oh I see my error. Makes perfect sense. This way modules imported in stories would be excluded too.

**Comment by AndrewPrifer** [comment]
@mrmckeb I see why this is complex now. The whole idea of fork-ts-checker is that it doesn’t traverse the dependency graph so sadly this sounds pretty impossible to do properly indeed.

**Comment by mrmckeb** [comment]
I mean that there's no easy solution (that I can think of)... But if you do have a good idea, or want to create a PR with some ideas, please do and tag me 🙂

**Comment by AndrewPrifer** [comment]
@mrmckeb I'll let you know if I come up with something but I can't think of anything that wouldn't cause a considerable performance degradation. The way I see it we'd necessarily have to wait for Webpack to finish compiling to have the correct list of files to type check, which is not ideal. In the meantime I'll close this issue so it doesn't take up space. Hopefully we can reopen it in the future.

**Comment by mrmckeb** [comment]
Thanks @AndrewPrifer
