### ISSUE TITLE
PropsType is not displayed correctly.

### ISSUE THREAD

**Issue by Moonachi** [storybookjs/storybook#9668]
PropsType is not displayed correctly

- isRequired is not displayed.
![image](https://user-images.githubusercontent.com/46507959/73341076-3f83a400-42bf-11ea-8a6c-805f8037975d.png)
![image](https://user-images.githubusercontent.com/46507959/73341088-47434880-42bf-11ea-9c3f-1316bd7d6308.png)

- Display unknown.
![image](https://user-images.githubusercontent.com/46507959/73341217-8e313e00-42bf-11ea-8578-e58d8a529475.png)
![image](https://user-images.githubusercontent.com/46507959/73341230-91c4c500-42bf-11ea-9b41-d37950657c9a.png)

- devDependencies
![image](https://user-images.githubusercontent.com/46507959/73340847-d00db480-42be-11ea-9a3c-842bbb662c80.png)

Thanks

**Comment by shilman** [comment]
Unable to repro here https://github.com/storybookjs/storybook/commit/8219af19d09c5142f64830e545fdfb496c5fe636

**Comment by shilman** [comment]
@Moonachi can you try the recommended 6.0 setup (should work in 5.3 too) and based on the repro linked above I expect the problem to be fixed:

https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#react-prop-tables-with-typescript
