### ISSUE TITLE
Drop support for babel 6

### ISSUE THREAD

**Issue by ndelangen** [storybookjs/storybook#9675]
I'd like to simplify by dropping support for babel 6 in the next major release (`6.0.0`)

@shilman sounds like we should discuss this next roadmap meeting

**Comment by ndelangen** [comment]
@kroeder What would this mean for angular version support?

**Comment by kroeder** [comment]
Angular does not use babel. But babel is a dep added in all angular projects added by sb init. This might break apps?

**Comment by ndelangen** [comment]
If we're adding babel for our own use, then it should be safe to update it?
