### ISSUE TITLE
No documentation for @storybook/components

### ISSUE THREAD

**Issue by dantman** [storybookjs/storybook#9677]
**Describe the bug**
There is no documentation on how to use `@storybook/components` or what components are present in it.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the package page https://www.npmjs.com/package/@storybook/components
2. Click through to the homepage https://github.com/storybookjs/storybook/tree/master/lib/components
3. Note that neither page has links to documentation

**Expected behaviour**
Given that the library appears to have stories, there should be a running Storybook instance with links to it.

**Comment by shilman** [comment]
For now, they are effectively an internal library. For a reusable design system, check out:

https://storybook-design-system.netlify.com

**Comment by dantman** [comment]
I'm not looking for a design system. I'm trying to write a Storybook addon and would like documentation on the components I'm supposed to be using to make an addon that fits into Storybook.

**Comment by atanasster** [comment]
@dantman - I walked that walk recently myself, and am now much better acquainted with the storybook/components package. 
Shoot any questions you have, hopefully you can get your addon idea implemented.

**Comment by atanasster** [comment]
https://storybooks-official.netlify.com/?path=/story/basics-actionbar--singleitem

**Comment by dantman** [comment]
Thanks. I think that link should be present in the `@storybook/components` README.

**Comment by dantman** [comment]
Ok, I knew that storybook instance existed and tried googling to get to it this time. And I'm right back to looking up this issue to get the link. It definitely needs to be present in documentation and READMEs if it's the only way to check out the available components and icon names.

**Comment by shilman** [comment]
@dantman  can you submit a PR with the changes you have in mind?
