### ISSUE TITLE
Unexpected story state manipulation

### ISSUE THREAD

**Issue by BrianD91** [storybookjs/storybook#9683]
**Describe the bug**
My story is manipulating state behind the scenes and causing erroneous behavior in the rendered component.

**To Reproduce**
1. Attempt to jury-rig component state that responds to knobs events 

**Expected behavior**
Component/Story state behave exactly as described by the code.

**Screenshots**
![image](https://user-images.githubusercontent.com/37163937/73472814-a81f5f00-4359-11ea-8fa1-866e342c3284.png)

In the attached screenshot you see the resulting console.logs that result from the following series of actions:

1. enter red, blue, green into the knobs array() input
2. click on the rendered <ContextMenu />
3. click on one of the items in the dropdown menu that appears

As you can see, the `itemsList` state mysteriously goes form being an array of 3 objects to an array of one object.

**Code snippets**
```
/** @jsx jsx */
import {jsx} from '@emotion/react';
import {withKnobs, array, boolean, text} from '@storybook/addon-knobs/react';
import {initializeIcons} from 'office-ui-fabric-react/lib/Icons';
import {useState} from 'react';

import {ContextMenu} from './ContextMenu';

initializeIcons();

export default {
  component: ContextMenu,
  title: 'Buttons',
  decorators: [withKnobs]
};

export const contextMenu = () => {
  const [itemsList, setItemsList] = useState([{
    key: '',
    text: '',
    onClick: (e, item) => toggleItem(item),
    canCheck: true,
    isChecked: false
  }]);
  const [inputBuffer, setInputBuffer] = useState(['']);
  const listInput = array('Items List', ['red'], ', ');

  console.log('render');
  console.log(itemsList);
  console.log(inputBuffer);

  if (listInput !== inputBuffer) {
    const newInputList = listInput.map(item => {
      const swapIndex = itemsList.findIndex(el => item === el.key);

      return itemsList.find(el => item === el.key)
        ? itemsList[swapIndex]
        : {
            key: item,
            text: item,
            onClick: (e, item) => toggleItem(item),
            canCheck: true,
            isChecked: false
          }
    });

    setItemsList(newInputList);
    setInputBuffer(listInput);
  }

  const toggleItem = (clickedItem) => {
    console.log('inside the click');
    console.log(clickedItem);
    console.log(itemsList);
    const swapIndex = itemsList.findIndex(item => item.key = clickedItem.key);

    clickedItem.isChecked = !clickedItem.isChecked;
    itemsList.splice(swapIndex, 1, clickedItem);
    setItemsList(itemsList);
  };

  return (
    <ContextMenu 
      disabled={boolean('Disabled', false)}
      items={itemsList}
      text={text('Button Text', 'Button Text')}
      type='neutralAction'
    />
  );
};
```

**System:**
Environment Info:

  System:
    OS: macOS 10.15.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Binaries:
    Node: 13.6.0 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 79.0.3945.130
    Safari: 13.0.3
  npmPackages:
    @storybook/react: ^5.3.0 => 5.3.0

**Comment by BrianD91** [comment]
Oh and I guess to give a better description of the visual bug.

You'll have the list of items in the dropdown menu that opens when you click the button, then if you click on one of the items in the dropdown, it closes. THEN if you click the button again the dropdown opens and the only item there is the item you clicked on the first time. But if you then change the 'Items List' arrray() knob the entire list will come back, with the one you clicked on still being checked.

**Comment by matt-shine** [comment]
I think there's some issues with your code that are responsible for the issues you're seeing.

1. `export const contextMenu = () => {` React requires the component name to be capitalized, I'm seeing errors as React doesn't think this is a React function component. Changing it `TestContextMenu` or something similar fixes this.
2. In toggleItem(), you're attempting to modify state directly:
```
    itemsList.splice(swapIndex, 1, clickedItem);
    setItemsList(itemsList);

   // should be
   setItemsList(itemsList.splice(swapIndex, 1, clickedItem));
```
3. I'm not sure the below works the way you might be expecting, it will execute on each render (maybe try logging in there to get some visibility). 
```
const listInput = array('Items List', ['red'], ', '); 

if (listInput !== inputBuffer) {
    const newInputList = listInput.map(item => {
      const swapIndex = itemsList.findIndex(el => item === el.key);

      return itemsList.find(el => item === el.key)
        ? itemsList[swapIndex]
        : {
            key: item,
            text: item,
            onClick: (e, item) => toggleItem(item),
            canCheck: true,
            isChecked: false
          }
    });

    setItemsList(newInputList);
    setInputBuffer(listInput);
  }
```

There's probably more, but it's difficult without the code for `ContextMenu`
