### ISSUE TITLE
Missing script: build-storybook

### ISSUE THREAD

**Issue by Ninita1** [storybookjs/storybook#9685]
**Describe the bug**
When executing `npm run build-storybook -c .storybook -o ./dist/myProject/storybook/` I always get this error: `npm ERR! missing script: build-storybook`.
I suspect the problem are the dependencies versions. But I already updated or downgraded versions and deleted node_modules and package-lock.json thousand times and install everything again and the problem remains. Can someone help me?

**To Reproduce**
Run `npm run build-storybook -c .storybook -o ./dist/myProject/storybook/`

**Expected behavior**
The storybook should be built normally and successfully.

**Screenshots**
![erro storybook build](https://user-images.githubusercontent.com/12759409/73479916-c3599100-4390-11ea-923e-ecb5c537e24c.png)
![erro storybook build file 1](https://user-images.githubusercontent.com/12759409/73479919-c5bbeb00-4390-11ea-9a8e-26613cffcde0.png)
![erro storybook build file 2](https://user-images.githubusercontent.com/12759409/73479927-c9e80880-4390-11ea-9429-27aff3271558.png)

**Code snippets**
```
  "scripts": {
    "start": "npm run storybook-start",
    "storybook-start": "start-storybook -p 9001 -s ./src -c .storybook",
    "storybook-build": "npm run build-storybook -c .storybook -o ./dist/gis-framework/storybook/"
  },
  "dependencies": {
    "prop-types": "^15.7.2",
    "react": "^16.9.0",
    "react-dom": "^16.9.0",
    "react-scripts": "^3.1.1"
  },
  "devDependencies": {
    "@storybook/addon-options": "3.4.8",
    "@storybook/addons": "3.4.8",
    "@storybook/components": "3.4.8",
    "@storybook/react": "3.4.8",
    "babel-cli": "^6.26.0",
    "babel-core": "^6.26.3",
    "babel-eslint": "^10.0.3",
    "babel-jest": "^23.6.0",
    "babel-loader": "^7.1.4",
    "babel-minify": "^0.5.1",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-imports": "^2.0.0",
    "babel-plugin-transform-react-remove-prop-types": "^0.4.24",
    "babel-plugin-transform-require-ignore": "^0.1.1",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-plugin-transform-strict-mode": "^6.24.1",
    "babel-preset-env": "^1.7.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-1": "^6.24.1",
    "clean-webpack-plugin": "^0.1.17",
    "copy-webpack-plugin": "^4.5.3",
    "cross-env": "^7.0.0",
    "css-loader": "^3.4.2",
    "enzyme": "^3.10.0",
    "enzyme-adapter-react-16": "^1.14.0",
    "enzyme-to-json": "^3.4.0",
    "eslint": "^5.16.0",
    "eslint-config-airbnb": "^16.1.0",
    "eslint-loader": "^2.1.2",
    "eslint-plugin-import": "^2.18.2",
    "eslint-plugin-jsx-a11y": "^6.2.3",
    "eslint-plugin-react": "^7.14.3",
    "extract-text-webpack-plugin": "^3.0.2",
    "file-loader": "^5.0.2",
    "jest": "^23.6.0",
    "jest-canvas-mock": "^2.2.0",
    "jest-environment-jsdom": "^25.1.0",
    "jest-html-reporter": "^2.8.0",
    "js-beautify": "^1.10.2",
    "marksy": "^8.0.0",
    "optimize-css-assets-webpack-plugin": "^5.0.3",
    "prismjs": "^1.17.1",
    "raw-loader": "^4.0.0",
    "react-addons-create-fragment": "^15.6.2",
    "react-komposer": "^2.0.0",
    "react-test-renderer": "^16.9.0",
    "resolve-url-loader": "^3.1.1",
    "style-loader": "^1.1.3",
    "uglifyjs-webpack-plugin": "^2.2.0",
    "webpack": "^3.11.0",
    "webpack-bundle-analyzer": "^3.6.0",
    "webpack-cli": "^3.3.10",
    "webpack-common-shake": "^1.5.3"
  }
```

**System:**
```
Environment Info:

  System:
    OS: Windows 10 10.0.17763
    CPU: (4) x64 Intel(R) Core(TM) i5-4300M CPU @ 2.60GHz
  Binaries:
    Node: 12.13.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.12.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.17763.831.0
```

**Comment by shilman** [comment]
Is there a build-storybook in your `node_modules/.bin` directory? I suspect this might be an issue with 3.x on windows.

I'd recommend upgrading to 5.3. We don't really support 3.x anymore.

**Comment by Ninita1** [comment]
> Is there a build-storybook in your `node_modules/.bin` directory? I suspect this might be an issue with 3.x on windows.
> 
> I'd recommend upgrading to 5.3. We don't really support 3.x anymore.

**Comment by Ninita1** [comment]
@shilman Hi. Yes, there is. There is a build-storybook, a build-storybook.cmd and a build-storybook.ps1

**Comment by Ninita1** [comment]
@shilman I updated now my project version according with you articles and some others:
https://medium.com/storybookjs/migrating-to-storybook-4-c65b19a03d2c
https://medium.com/storybookjs/storybook-5-migration-guide-d804b38c739d
https://medium.com/storybookjs/storybook-5-3-83e114e8797c
https://babeljs.io/docs/en/v7-migration

Now I have many other problems! But well I think I gonna close this issue for now

**Comment by Ninita1** [comment]
After all, the problem was the command `storybook-build`. Should only be "build-storybook -c .storybook -o ./dist/gis-framework/storybook/", without the "npm run"
