### ISSUE TITLE
proposal: extract components prop utilities into own package

### ISSUE THREAD

**Issue by atanasster** [storybookjs/storybook#9690]
this is a request to extract the prop-tables utility functions into their own package, so other tools, like a smart-controls (smart-knobs++) could take advantage of pop tables type information.

currently located in addon-docs package: https://github.com/storybookjs/storybook/tree/next/addons/docs/src/lib

**Comment by shilman** [comment]
This sounds good to me @atanasster. @patricklafrance and I talked about this as part of the 6.0 refactor, and providing data for `addon-controls` is an even better reason to get this going.

**Comment by atanasster** [comment]
Great, here is what i took out so far

https://github.com/atanasster/storybook/blob/properties-2/addons/docs/src/blocks/propExtract.ts

**Comment by patricklafrance** [comment]
sounds good, how will you deal with common code like the jsdoc parser?

**Comment by atanasster** [comment]
I didnt see which is the common code - what is it used for?

Either way all i think all doc parsing code would belong into this new package?

**Comment by patricklafrance** [comment]
Depends on what you mean by the new package.

IMO each framework should have his own docgen package and they should not really share code between each others. Currently, they are all coupled and this is a problem.

We could have some kind of docgen-utils packages that could contains a few utilities like:

- https://github.com/storybookjs/storybook/blob/next/addons/docs/src/lib/jsdocParser.ts
- https://github.com/storybookjs/storybook/tree/next/addons/docs/src/lib/docgen/utils

**Comment by atanasster** [comment]
sorry dont really have an opinion, you know better about this subject. 
Just my 0.02:
 i would imagine a generic doc extracting library that would work with all frameworks, s-o -if one day storybooks supports multiple frameworks inside the same project. If that even possible.

**Comment by shilman** [comment]
Our first  attack at multi-framework support will be to achieve that through composition. So each framework would have its own storybook and there would be an overarching storybook that composes those and provides an integrated UX. In this architecture, i think we can pretty much think of prop tables as a “one framework at a time” problem. Once we get this all working, if we want to support a UX where multiple frameworks exist on the same page (which could be useful) we can think about a major refactor. But there’s enough distance between here and there that i don’t think we need to design for it yet.

**Comment by atanasster** [comment]
I agree - 
- we can just extract the utility functions that I pointed out above would be a great stat and we can take the further refactoring one step at a time..
- or I can just import them from addon-docs as I am already doing.

**Comment by shilman** [comment]
In the short term do what you’re doing now. Next week I’ll see if i can come up with a proposal for a standalone package. When i first implemented the props table it was a super simple and i mistakenly thought it was an easy problem that was already solved by the libraries we were using. Turns out that’s not the case: not only is this a rich area for differentiating storybook above other options, but it’s also a major source of bugs/configuration challenges 🤦‍♂️! So making a separate package and getting that package right sounds great to me.

**Comment by atanasster** [comment]
sounds good :)
