### ISSUE TITLE
[Addon-docs] Components in Stories block share handlers or state with Primary block

### ISSUE THREAD

**Issue by TMaszko** [storybookjs/storybook#9694]
**Describe the bug**
Components added in Stories block are invoking handlers from the Primary block even if they are rendered with different props at the start. 

**To Reproduce**
Create simple component with state i.e Toggle 
Add console.log to onClick handler with props which distinguish from the other components i.e label
Click on Toggle button in Stories block fires handler from Primary block and state only changes in one primary component

**Expected behavior**
All components are independent and don't share anything.

**Screenshots**
I recorded screencast for this situation. Here is a link to google drive: https://drive.google.com/open?id=1g5_BKvwQI7YpUXbslCOzY0y_wjcTt1Jz

**Code snippets**
Repository with reproduced issue.
https://github.com/TMaszko/addon-docs-example

**System:**
  System:
    OS: Linux 5.3 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
  Binaries:
    Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
    Yarn: 1.19.1 - ~/.nvm/versions/node/v10.16.3/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v10.16.3/bin/npm
  Browsers:
    Chrome: 79.0.3945.79
    Firefox: 72.0.2
  npmPackages:
    @storybook/addon-actions: ^5.3.7 => 5.3.9 
    @storybook/addon-console: ^1.2.1 => 1.2.1 
    @storybook/addon-docs: ^5.3.9 => 5.3.9 
    @storybook/addon-info: ^5.3.7 => 5.3.9 
    @storybook/addon-knobs: ^5.3.7 => 5.3.9 
    @storybook/addon-options: ^5.3.7 => 5.3.9 
    @storybook/react: ^5.3.9 => 5.3.9

**Comment by shilman** [comment]
@TMaszko do you have a repro you can share?

**Comment by TMaszko** [comment]
I don't have it now. I've faced this problem at my company's repo but I will try to create private one at the weekend probably.

**Comment by TMaszko** [comment]
@shilman I updated my previous comment with the link to sample repo :)

**Comment by TMaszko** [comment]
I think that it might be interesting case. I found it today in the morning :P
```jsx
storiesOf('Toggle', module)
    .addParameters({ component: Toggle, componentSubtitle: 'Display a simple Toggle component' })
    .add('default', () => (
        <div>
            <Toggle label="with onToggle" onToggle={onToggleAction} />
            <Toggle label="default" />
        </div>
    ))
    .add('with onToggle', () => <Toggle label="with onToggle" onToggle={onToggleAction} />);
```
I'll add it later to the repo

**Comment by TMaszko** [comment]
After deeper research turned out that problem lied in a focus management. Sorry for making unnecessary issue report ;)

**Comment by shilman** [comment]
@TMaszko glad you figured it out! 🚀
