### ISSUE TITLE
Redirect to story/canvas from non-existent docs page

### ISSUE THREAD

**Issue by ArrayKnight** [storybookjs/storybook#9702]
**Describe the bug**
Introducing docs addon leads to poor UX when switching between docs pages and stories without docs pages.

**To Reproduce**
1. Go to https://storybook-addon-headless.netlify.com/
2. Notice that the default page is a docs only page and that the path is a story, not docs
3. Notice that the paths for the 3 docs pages are not stories, but docs instead
4. Click on Examples > GraphQL > Artworks (a story without docs)
5. Notice that the story loads as expected and that the path is a story, not docs
6. Click on any of the 3 docs pages
7. Click on Examples > GraphQL > Artworks
8. Notice that the story doesn't load as expected and that the path is docs, not story

The bug is that there's no value in showing a docs page that doesn't exist and that there's no way (that I'm aware of) to control the navigation links.

**Expected behavior**
Any (or all) of the below:
- The docs page redirects to the story
- The sidebar navigation links should always point to the story path
- Docs only pages should default to using the story path (only)

**Code snippets**
https://github.com/ArrayKnight/storybook-addon-headless

**System:**
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz
  Binaries:
    Node: 12.14.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.15.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.7 - D:\Git\storybook-addon-headless\node_modules\.bin\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
    Chrome: Version 79.0.3945.130 (Official Build) (64-bit)

**Comment by shilman** [comment]
@ArrayKnight What a cool addon! Why don't you try the `viewMode` parameter, available in 6.0.0:

https://github.com/storybookjs/storybook/pull/9090

**Comment by ArrayKnight** [comment]
Once v6 is released/stable I'll give that a host. Is there no way to do so in v5?
