### ISSUE TITLE
Depends on core-js twice

### ISSUE THREAD

**Issue by dmnd** [storybookjs/storybook#9705]
`@storybook/router` currently depends on `@reach/router^1.2.1`. `@reach/router^1.2.1` has a dependency on `core-js@1` via `create-react-context@0.2`'s dependency on `fbjs`. But `@storybook/router` also directly depends on `core-js@3`, meaning it has two copies 😞

This can be resolved by updating to `@reach/router^1.3.0` which no longer depends on `fbjs` or `core-js`.

**Comment by ndelangen** [comment]
I'll check it out.

**Comment by shilman** [comment]
Great Caesar's ghost!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-alpha.21 containing PR #10016 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
