### ISSUE TITLE
Build: Race condition in `yarn run createDlls`

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#9707]
When i run `yarn bootstrap --reset --core`:

```
storybook info bootstrap Generate DLL (dll)
storybook info bootstrap dll
lerna notice cli v3.19.0
lerna notice filter including "@storybook/ui"
lerna info filter [ '@storybook/ui' ]
lerna info Executing command in 1 package: "yarn run createDlls"
lerna ERR! yarn run createDlls exited 1 in '@storybook/ui'
lerna ERR! yarn run createDlls stdout:
$ node -r esm ./scripts/createDlls.js
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run createDlls stderr:
/Users/shilman/projects/baseline/storybook/lib/ui/scripts/createDlls.js:1
import path from 'path';
SyntaxError: Unexpected identifier
    at new Script (vm.js:83:7)
error Command failed with exit code 1.
lerna ERR! yarn run createDlls exited 1 in '@storybook/ui'
error Command failed with exit code 1.
```

however, when i subsequently run `yarn bootstrap --core` it succeeds.
this is a small thing. but it's problem, because it adds an extra step to my release process, and i release all the time. it's my first time to encounter this, and i'm seeing it on both `next` and `master`.

**Note:** I just upgraded to `yarn@1.21.1`. I'm not sure if it's related.

**Comment by lmaze** [comment]
Same error with the `yarn bootstrap --all` command.

**Comment by shilman** [comment]
Shiver me timbers!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-alpha.7 containing PR #9770 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Yowza!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.13 containing PR #9770 that references this issue. Upgrade today to try it out!
