### ISSUE TITLE
6.0.0-alpha.3: lib/cli package.json dependencies

### ISSUE THREAD

**Issue by atanasster** [storybookjs/storybook#9710]
The following 2 dependencies seem leftover

https://github.com/storybookjs/storybook/blob/455765a594f214bd3a6f4e1e5d2cc4542ae59dfa/lib/cli/package.json#L63

https://github.com/storybookjs/storybook/blob/455765a594f214bd3a6f4e1e5d2cc4542ae59dfa/lib/cli/package.json#L66

**Comment by shilman** [comment]
Not seeing this in the current `next` branch. Maybe somebody fixed it? Closing.
