### ISSUE TITLE
Addon-a11y: Don't run in docs `viewMode`

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#9715]
When storybook is in docs-mode it can run multiple stories on a page, and especially when combined with knobs can cause hundreds of runs in a single render, which locks up slower machines.

Therefore:
- [ ] Expose viewMode in the render context
- [ ] Only execute a11y test when viewMode is 'story'

**Comment by tooppaaa** [comment]
The A11yPanel is now in charge for asking the axe-core execution. 
As it's not present in docs mode, I don't think this issue is relevant anymore.

**Comment by shilman** [comment]
💯
