### ISSUE TITLE
bug(addon-docs): Code styling preview bug in CSF format

### ISSUE THREAD

**Issue by ocBruno** [storybookjs/storybook#9718]
**Describe the bug**
Code styling is not rendered correctly

**To Reproduce**
1. Reproduction available in
 https://github.com/ocBruno/components/tree/fix/replace-addon-info-addon-docs
2. Some discussions which might be relevant
https://github.com/HospitalRun/components/pull/241

**Expected behavior**
Correct code styling preview

**Screenshots**
Working component styling preview:
![image](https://user-images.githubusercontent.com/34284312/73624893-5ad51300-4621-11ea-86a0-705ff33ecc07.png)

Component styling preview bug:
![image](https://user-images.githubusercontent.com/34284312/73624958-9f60ae80-4621-11ea-9988-af4d47c7f92d.png)

**Code snippets**
DefaultNavbar provides correct styling while linked list doesn't:

````
export const DefaultNavbar = () => (
  <Navbar
    navItems={[
      {
        type: 'icon',
        src:
          'https://raw.githubusercontent.com/HospitalRun/hospitalrun.github.io/master/favicon.png',
        onClick: () => {
          Toast('success', 'Icon clicked!!', 'Success')
        },
      },
      {
        type: 'header',
        label: 'HospitalRun',
        onClick: () => {
          Toast('success', 'Header clicked!!', 'Success')
        },
      },
      {
        type: 'link',
        label: 'Link',
        onClick: () => {
          Toast('success', 'Link clicked!!', 'Success')
        },
      },
      {
        type: 'link',
        label: 'Link 2',
        onClick: () => {
          Toast('success', 'Link clicked!!', 'Success')
        },
      },
      {
        type: 'search',
        className: 'ml-auto mr-3',
        onClickButton: () => {
          Toast('success', 'Button clicked!!', 'Success')
        },
        onChangeInput: () => {
          Toast('success', 'Search box changed!!', 'Success')
        },
      },
    ]}
  />
)

export const NavbarWithLinkedList = () => (
  <Navbar
    bg="dark"
    variant="dark"
    navItems={[
      {
        type: 'icon',
        src:
          'https://raw.githubusercontent.com/HospitalRun/hospitalrun.github.io/master/favicon.png',
        onClick: () => {
          Toast('success', 'Icon clicked!!', 'Success')
        },
      },
      {
        type: 'header',
        label: 'HospitalRun',
        onClick: () => {
          Toast('success', 'Header clicked!!', 'Success')
        },
      },
      {
        type: 'link',
        label: 'Link',
        onClick: () => {
          Toast('success', 'Link clicked!!', 'Success')
        },
      },
      {
        type: 'link-list',
        label: 'Link List',
        onClick: () => {
          Toast('success', 'Link list clicked!!', 'Success')
        },
        children: [
          {
            type: 'link',
            label: 'Sublink1',
            onClick: () => {
              Toast('success', 'Sublink1 clicked!!', 'Success')
            },
          },
          {
            type: 'link',
            label: 'Sublink2',
            onClick: () => {
              Toast('success', 'Sublink2 clicked!!', 'Success')
            },
          },
        ],
      },
      {
        type: 'search',
        placeholderText: 'Custom',
        className: 'ml-auto',
        buttonText: 'Text',
        buttonColor: 'secondary',
        onClickButton: () => {
          Toast('success', 'Search button clicked!!', 'Success')
        },
        onChangeInput: () => {
          Toast('success', 'Search box changed!!', 'Success')
        },
      },
    ]}
  />
)
````
**System:**
    OS: Windows 10 10.0.18362
    CPU: (12) x64 AMD Ryzen 5 3600X 6-Core Processor
  Binaries:
    Node: 12.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.21.1 - C:\Program Files\nodejs\yarn.CMD
    npm: 6.12.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
**Additional context**
Removing the link-list makes the preview render correctly so I'm thinking it might be a problem parsing the nested objects.

**Possible bug**
I'm not sure if this is supposed to show the arguments that can be passed to create the component, if it's a bug, or if there is something wrong with my config.
![image](https://user-images.githubusercontent.com/34284312/73625085-2c0b6c80-4622-11ea-94f8-3256c03afdb7.png)

**Thanks and if any help is needed to fix this issue leave me a message!**

**Comment by ocBruno** [comment]
I'm going to look into this bug but as it's my first storybook issue if anyone has any ideas or is currently working on this please let me know!

**Comment by shilman** [comment]
@ocBruno if you want help debugging this, please jump on the Storybook discord and hopefully somebody can give you a hand! https://discord.gg/UUt2PJb
