### ISSUE TITLE
Main.js config: Export decorators and parameters declaratively

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#9719]
In CSF, we can define component-level decorators and parameters on the default export. Let's do the same for `preview.js` and also on the `decorators`/`parameters` fields in `main.js` as a way to define global decorators/parameters.

### Why

This is more ergonomic for the user, and analogous consistent with CSF.

It will also be simpler to define presets for addons (e.g. a11y, knobs)

**Comment by tmeasday** [comment]
Actually this was already implemented as part of https://github.com/storybookjs/storybook/pull/9877
