### ISSUE TITLE
addon-queryparams do not have consistent behavior when each story has its own query.

### ISSUE THREAD

**Issue by tredmon** [storybookjs/storybook#9729]
**Describe the bug**
addon-queryparams do not have consistent behavior when each story has its own query params.

**To Reproduce**
```js
import React from 'react';
import { storiesOf, addDecorator } from '@storybook/react';
import { withQuery } from '@storybook/addon-queryparams';
storiesOf('App', <div/>)
    .addDecorator(withQuery)
    .add('Show query params before', () => (
        <div>
            {window.location.search}
        </div>
    ), {
        query: {
            spaces: '    ',
        },
    })
    .addParameters({
      query: {
        state: 'bwaha', 
      },
    })
    .add('Show query params', () => (
        <div>
            {window.location.search}
        </div>
    ), {
        query: {
            something: 'random',
        },
    })
;
```
1. start storybook
2. Go to `http://localhost:6006/?path=/story/app--show-query-params-before`
3. Note the output is as expected `?id=app--show-query-params-before&viewMode=story&spaces=%20%20%20%20`
4. Click `Show query params`
5. Note the output includes the unexpected `spaces` param in addition to the expected `something` and `state` params.
6. Click `Show query params before`
7. Note the output is different from (3), and now includes the unexpected `something` param.
8. Also note the output in (7) now includes the `state` param which the output of (3) did not. This may be a separate issue, but it is unclear to me whether parameters added via `addParameters` should be added to all stories or just those added after the parameters were added.

**Expected behavior**
Query params should be consistent between visits of the story.

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System:**
Please paste the results of `npx -p @storybook/cli@next sb info` here.

Environment Info:

  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  Binaries:
    Node: 12.10.0 - /usr/local/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 6.10.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 79.0.3945.130
    Firefox: 69.0
    Safari: 13.0.5
  npmPackages:
    @storybook/addon-actions: ^5.3.10 => 5.3.10 
    @storybook/addon-queryparams: ^5.3.10 => 5.3.10 
    @storybook/addons: ^5.3.10 => 5.3.10 
    @storybook/react: ^5.3.10 => 5.3.10 

**Additional context**

**Comment by shilman** [comment]
cc @ndelangen

**Comment by ndelangen** [comment]
Right.. I think it's very hard for the addon to know exactly which queryParams should be removed.

But not impossible..

Would be great to have some help on this, would you be interested in helping out @tredmon ?

**Comment by Goddiemk** [comment]
Yea, I am also having problem using on this. Any updates?

**Comment by tredmon** [comment]
I haven't had time to look at the source. For me personally it is a low priority because there is a workaround -- after clicking the story I want to see I can refresh the page to load up with just the intended query params.

**Comment by luk82** [comment]
I was able to fix similar issue with search param by setting query parameter to undefined for other stories. Not sure it will work with state...

```
.addParameters({
      query: {
        search: undefined, 
      },
    })
```

**Comment by joe4mg** [comment]
Hi @ndelangen - is there a reason we couldn't just remove _all_ queryParams before applying the new parameters?
If there are storybook 'internal' queryParams that should persist then perhaps these could these be name-spaced (and persisted)?

**Comment by joe4mg** [comment]
In case anyone finds this issue via google - the neatest way I found to 'fix' this was to set all querys as undefined using a component level parameters (https://storybook.js.org/docs/react/writing-stories/parameters#component-parameters) and settings parameters with story level parameters (https://storybook.js.org/docs/react/writing-stories/parameters#story-parameters). The parameters at component level get merged with the story level (story takes precedence) so each story is 'clean'.
