### ISSUE TITLE
DevTools failed to load SourceMap

### ISSUE THREAD

**Issue by zhaoxuyll** [storybookjs/storybook#9732]
**Describe the bug**
Warning in console:
`DevTools failed to load SourceMap: Could not load content for http://localhost:6006/unfetch.mjs.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE`.

**To Reproduce**
1. Starting Storybook

**Expected behavior**
No warning.

**Screenshots**
![image](https://user-images.githubusercontent.com/3224165/73705610-59930b80-4731-11ea-9683-78c13acef8a9.png)

**Code snippets**
this my `webpack.config.js`
```js
const webpack = require('webpack');
const _ = require('lodash');
const WebpackNotifierPlugin = require('webpack-notifier');
const WebpackShellPlugin = require('webpack-shell-plugin');
const FilterWarningsPlugin = require('webpack-filter-warnings-plugin');

module.exports = ({ config }) => {
  config.resolve.extensions.push('.ts', '.tsx', '.js', '.jsx', '.json');
  config.module.rules.push(
    {
      test: /\.tsx?$/,
      exclude: /node_modules/,
      use: [
        {
          loader: 'babel-loader',
          options: { cacheDirectory: true }
        },
        {
          loader: 'ts-loader',
          options: { transpileOnly: true }
        }
      ]
    },
    {
      test: /\.tsx?$/,
      exclude: /node_modules/,
      use: [
        {
          loader: '@storybook/addon-storysource/loader',
          options: { parser: 'typescript' }
        }
      ],
      enforce: 'pre'
    }
  );
  config.node = {
    fs: 'empty',
    path: 'empty'
  };
  _.remove(config.plugins, plugin =>
    ['DefinePlugin', 'ProgressPlugin'].includes(plugin.constructor.name)
  );
  config.plugins.push(
    new webpack.ProvidePlugin({ React: 'react' }),
    new webpack.DefinePlugin({
      'process.env.LAUNCHER': JSON.stringify(process.env.LAUNCHER)
    }),
    new webpack.WatchIgnorePlugin([/\.jsx?$/, /\.d\.ts$/]),
    new FilterWarningsPlugin({
      // unable to re-export
      exclude: /export .* was not found in .*/
    }),
    new WebpackNotifierPlugin({ title: 'storybook' }),
    new WebpackShellPlugin({
      onBuildEnd: [
        'chrome.exe ' + `http://localhost:${process.env.STORYBOOK_PORT}`
      ]
    })
  );
  return config;
};
```

**System:**
```
Environment Info:

  System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HK CPU @ 2.70GHz
  Binaries:
    Node: 10.18.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.17.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0

```

**Comment by Oscar-Everest** [comment]
I have an issue. My react project is rendered partially instead of on full screen
![Screenshot (1)](https://user-images.githubusercontent.com/63425337/80585446-4085b800-8a0b-11ea-9198-3e1a352c1928.png)
![Screenshot (2)](https://user-images.githubusercontent.com/63425337/80585449-424f7b80-8a0b-11ea-97aa-87b232e9771e.png)

**Comment by Oscar-Everest** [comment]
after deploying to firebase hosting, my react project was rendered partially instead of  full screen; i got this error when i console logged: 
DevTools failed to load SourceMap: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.postload.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

**Comment by Eventyret** [comment]
> after deploying to firebase hosting, my react project was rendered partially instead of full screen; i got this error when i console logged:
> DevTools failed to load SourceMap: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.postload.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
 
Isn't that your adblocker? "gighmmpiobklfepjocnamgkkbiglidom" in chrome web store will suggestion [this](https://chrome.google.com/webstore/search/gighmmpiobklfepjocnamgkkbiglidom) @Oscar-Everest 
Try to turn it off to possible see if it affects it.

**Comment by ShNURoK42** [comment]
@Eventyret I have same warning, yes it's adblock.
