### ISSUE TITLE
Document `@storybook/server`

### ISSUE THREAD

**Issue by tmeasday** [storybookjs/storybook#9740]
Update the README for https://github.com/storybookjs/storybook/pull/9722 explaining how to use it and how you might go about writing an integration.

**Comment by jonspalmer** [comment]
We have some docs in the server Readme.md. @tmeasday and @shilman do they cover it or are there gaps you'd like to see closed?

**Comment by tmeasday** [comment]
Wow, no I hadn't seen that, that's great!
