### ISSUE TITLE
Vue - addon-docs does not work with render functions

### ISSUE THREAD

**Issue by mattgreenfield** [storybookjs/storybook#9745]
**Describe the bug**
When adding addon-docs to a Vue component with a render function (and no <template>) I get the following error:
`[vue-docgen-loader] failed to parse the component file with docgen-api: Cannot read property 'leadingComments' of null`

The 'Docs' tab loads in the browser and shows the component in the iframe but does not show the component description and prop info.

Removing the render function and adding a <template> fixes this.

**To Reproduce**
1. Add addon-docs to a Vue project
2. Add a story for a component with a render function
3. See error

**Expected behavior**
This should work just like any other component. 
If that's not possible, maybe the warning could be better? "addon-docs does not support components with a render function"

**Screenshots**
<img width="956" alt="Screenshot 2020-02-04 at 11 32 15" src="https://user-images.githubusercontent.com/7290654/73741387-0d9c9280-4742-11ea-9270-3e9cb9eb0cf1.png">

**System:**
System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7600 CPU @ 3.50GHz
  Binaries:
    Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
    npm: 6.13.7 - ~/Documents/ui-baseplate/node_modules/.bin/npm
  Browsers:
    Chrome: 79.0.3945.130
    Firefox: 71.0
    Safari: 13.0.5
  npmPackages:
    @storybook/addon-actions: ^5.3.7 => 5.3.10 
    @storybook/addon-backgrounds: ^5.3.7 => 5.3.10 
    @storybook/addon-docs: ^5.3.10 => 5.3.10 
    @storybook/addon-knobs: ^5.3.7 => 5.3.10 
    @storybook/addon-links: ^5.3.7 => 5.3.10 
    @storybook/addon-notes: ^5.3.7 => 5.3.10 
    @storybook/addon-storysource: ^5.3.7 => 5.3.10 
    @storybook/addon-viewport: ^5.3.7 => 5.3.10 
    @storybook/addons: ^5.3.7 => 5.3.10 
    @storybook/source-loader: ^5.3.7 => 5.3.10 
    @storybook/vue: ^5.3.7 => 5.3.10

**Comment by shilman** [comment]
@Aaron-Pool is this anything you know aboutr?

**Comment by Aaron-Pool** [comment]
@shilman no, I'm fairly confident render functions are known to be working. At least the typical use case. @mattgreenfield any chance you could set up a minimal repro repo for debugging purposes?

**Comment by mattgreenfield** [comment]
Thanks for your time and help.

I've created a reduced test case and narrowed down the error a little (it's not render functions that's the problem).

I've opened a new issue here https://github.com/storybookjs/storybook/issues/9821

**Comment by mattgreenfield** [comment]
I've managed to reproduce this one and have raised an issue with vue-docgen here https://github.com/vue-styleguidist/vue-styleguidist/issues/753
