### ISSUE TITLE
Use raw-loader with Storybook Docs mdxSource 

### ISSUE THREAD

**Issue by thomasoreilly** [storybookjs/storybook#9746]
**Is your feature request related to a problem? Please describe.**
My use case is to use the raw value of a file as the `mdxSource` to Preview component.
The below snippet explains my use case. So the source code of my.component.ts is rendered as the show source instead of `component: MyComponent`

```
<Preview mdxSource={require('!raw-loader!./my.component.ts')} >
    <Story name='My Story'>{{
      component: MyComponent
    }}</Story>
</Preview>
``` 

**Describe the solution you'd like**
I would like for the mdxSource property to accept raw source code. 

**Describe alternatives you've considered**
I have this working somewhat, the decodeURI function within preview.js throws `URIError: URI malformed` exception when using the approach above. It doesn't like inline styles in Angular component's metadata. I do have solutions around this, a better approach would for `mdxSource` to accept raw values.   

**Are you able to assist bring the feature to reality?**
maybe

**Additional context**
I haven't read anywhere on the documentation to achieve the above so I'd be delighted if there is an alternative way to do this.

**Comment by shilman** [comment]
Using `mdxSource` to override the source snippet is kind of an undocumented, unsupported hack. I hope we can introduce a better solution soon.

**Comment by thomasoreilly** [comment]
Out of a matter of interest, what is `mdxSource`'s function? Be great to have this feature in it cause I won't implement an unsupported hack. Let me know if there's anything I can do to help.

**Comment by shilman** [comment]
It's basically an internal API that the MDX compiler uses to communicate the source code inside the `<Preview>` block. I think some people figured out that you could use this internal API to hack the output. I think we have a better solution in `source-loader` v6.0

**Comment by thomasoreilly** [comment]
Thanks. I'll have a look into `source-loader`. Any idea on release for it?

**Comment by shilman** [comment]
it's available in 6.0.0-alpha.x. the 6.0 release is targeted for april.

**Comment by thomasoreilly** [comment]
Cool thanks @shilman

**Comment by FarisSum** [comment]
Hi @shilman

I posted [this ](https://github.com/storybookjs/storybook/issues/9846) a few days ago. I think this issue addresses my issue in a more direct way.

Take a look at my code:

```import { Meta, Preview, Props } from '@storybook/addon-docs/blocks';
import { Spinner } from '../';
import { SpinnerSample } from './Spinner.samples';

<Meta title="Components|Spinner" />

# Spinner

<SpinnerSample />

```jsx
copy and pasted code from Spinner.samples

<Props of={Spinner} />
```

I want the JSX code snipit **to not be manually typed**. My feature request addresses this, but idealistically a better solution is to pass-through the underlying code string to the MDX file.

Could it be possible to address both these feature requests with something like this?:


```import { Meta, Preview, Props } from '@storybook/addon-docs/blocks';
import { Spinner } from '../';
import { SpinnerSample } from './Spinner.samples';

<Meta title="Components|Spinner" />

<Preview>
 <SpinnerSample />
</Preview

<Props of={Spinner} />
```

@thomasoreilly Is there a short-term workaround with mdxSource? Admittedly, I am still trying to understand how I could use what you posted above as a solution.

**Comment by thomasoreilly** [comment]
Hi @FarisSum, 

The above idea is more of a hack than a solution. 
What I did was use Webpack's raw-loader to require the source code of the referenced file and pass it to the internal mdxSource property of the Preview component. The mdxSource is expecting a URL, not a string. It calls decodeURL internally so this is why this is not a good idea  and also its used internally and subject to change. 

I haven't got around trying out the 6.0.0-alpha.x of the source-loader yet.

**Comment by FarisSum** [comment]
Thanks @thomasoreilly 

Check out how mdxSource is used [here ](https://github.com/storybookjs/storybook/issues/9905)to accomplish this.

**Comment by FarisSum** [comment]
This works, but the code snipit output isn't a 1:1 from the react function :(

```
<Preview mdxSource={String(SpinnerSample)}>
  <Story id="SpinnerSample">
    <SpinnerSample />
  </Story>
</Preview>
```

**Comment by FarisSum** [comment]
@thomasoreilly How did you configure raw-loader in webpack.config.js. I'm getting errors, probably from conflicting loaders

**Comment by thomasoreilly** [comment]
@FarisSum the raw-loader works out of the box with Angular’s configuration. I guess you just need to apply the raw-loader to your Webpack configuration if not using Angular.

**Comment by FarisSum** [comment]
I almost have a perfect workaround, unfortunently I can't use modules with the raw-loader (@storybook/source-loader as a tsx formatted loader didn't work for me) 

I would have liked to wrap each component with it's own code snipit... not sure if there's a fancy webpack workaround for overloading modules (see below code for reference)

```
import { Meta, Preview, Props } from '@storybook/addon-docs/blocks';
import { Spinner } from '../';
import { SpinnerSample, SpinnerSmallSample } from './Spinner.samples';

//this won't work because the modules are already declared above ---->
//import { SpinnerSample, SpinnerSmallSample } from '!!raw-loader!./Spinner.samples.tsx'';

import code from '!!raw-loader!./Spinner.samples.tsx';

<Meta title="Components|Spinner" />

# Spinner

<Preview>
  <SpinnerSmallSample />
  <SpinnerSample />
</Preview>

# Code Snipits

<Preview mdxSource={code}>
  <Story id="SampleCode">
    <div>Code behind the above components...</div>
  </Story>
</Preview>

# Props

<Props of={Spinner} />
```

A second issue is within the preview story source. Some of the text must be in black, because it doesn't appear given the dark background. Is there a way to alter the background in the preview code block with themes? @shilman 

Thanks for reading!

**Comment by shilman** [comment]
@FarisSum i think you can just do `<Source dark={false} />`. i'm not sure about theming. the black text is probably due to a CSS clash between your code and `react-syntax-highlighter`

**Comment by FarisSum** [comment]
Thanks @shilman 

Where would I add <Source dark={false} /> ?
Is that supposed to be a component nested within <Preview> ?

**Comment by shilman** [comment]
@FarisSum Aha. `Source` is a standalone doc block and it's also nested within `Preview`. AFAICT there's no easy way of theming that instance, but we should add an option for it.

**Comment by FarisSum** [comment]
Hey @shilman 

I was able to switch up the background via preview-head.html
```
<style>
  .simplebar-content {
    background-color: rgb(11, 126, 155);
    font-weight: 500;
    font-size: medium;
  }
</style>
```

**Comment by zacnomore** [comment]
> It's basically an internal API that the MDX compiler uses to communicate the source code inside the `<Preview>` block. I think some people figured out that you could use this internal API to hack the output. I think we have a better solution in `source-loader` v6.0

As of today, `source-loader` 6.0 is not out so it probably still makes sense to use the above workaround

**Comment by alcail** [comment]
I just had this issue because of use of '%' character in my snippet
Solution was to replace '%' by its unicode value '\u0025'
Like { height: '100%' } became { height: '100\u0025' }

**Comment by LeeWeisheng** [comment]
I met the same error message, because the `%` appears in the example code. And I found that the `mdxSource` is decoded by `decodeURI` method in https://github.com/storybookjs/storybook/blob/release/6.2.x/addons/docs/src/blocks/Canvas.tsx#L40. So I solved the problem in the following way:

```jsx
import source from "!!raw-loader!./example";

<Canvas mdxSource={source.replace(/\%/g, "%25")}>
  ...
</Canvas>
```

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if this is still relevant in SB 7.x.
