### ISSUE TITLE
Storybook interface frozen and no stories visible when running in docker

### ISSUE THREAD

**Issue by TomasHnidek** [storybookjs/storybook#9757]
**Describe the bug**
When I want to run storybook inside a docker, I am able to successfully create a docker image with http-server and correct files I get from build-storybook. However, when opening the webpage, interface of storybook is frozen and I see no errors and also no stories.

**To Reproduce**
Steps to reproduce the behavior, assuming nodejs and docker are installed:
1. Clone https://github.com/TomasHnidek/storybook-docker-bug 
2. Run `docker build -t local/bugstory .`
3. Run `docker run -d -p6006:6006 local/bugstory`
4. Go to localhost:6006

**Expected behavior**
Storybook is running with all stories visible and functional

**Screenshots**
![image](https://user-images.githubusercontent.com/25525080/73822408-51e96a80-47f6-11ea-9ddb-89ab608e6a83.png)

**System:**
  System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
  Binaries:
    Node: 12.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.12.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.387.0

**Comment by TomasHnidek** [comment]
Has anyone some idea?

**Comment by ahmadalli** [comment]
This issue is still happening
