### ISSUE TITLE
Something are being displayed on the console

### ISSUE THREAD

**Issue by Moonachi** [storybookjs/storybook#9758]
I don't know why something are being displayed on the console. 
I want to get rid of the something on the console, but I wonder how.

![image](https://user-images.githubusercontent.com/46507959/73826568-5be48b00-4841-11ea-8101-80dedce52325.png)

My devDependencies
![image](https://user-images.githubusercontent.com/46507959/73826900-ed53fd00-4841-11ea-9935-e73b4ac7812e.png)

Thanks

**Comment by shilman** [comment]
Duplicate to #8461
