### ISSUE TITLE
Prop table doesn't show all the props in 5.3

### ISSUE THREAD

**Issue by etylsarin** [storybookjs/storybook#9764]
**Describe the bug**
While using v5.3.12, preset-create-react-app & TypeScript, I have a problem with the props table.
When I use `extends` on an interface, it only shows the extension when I left the interface definition empty.

**Expected behavior**
I should have both sets of props in the table: interface itself as well as the extension.

**Screenshots**

**Before**
![Screenshot 2020-02-05 17 14 55](https://user-images.githubusercontent.com/293403/73860206-7ae01e80-483b-11ea-9ae5-d39989a0d150.png)

**After**
![Screenshot 2020-02-05 17 14 21](https://user-images.githubusercontent.com/293403/73860231-859ab380-483b-11ea-9da7-a7d65a927213.png)

**Code snippets**
this code works:
```javascript
interface RadioProps extends InputProps {}
```
this code doesn't:
```javascript
interface RadioProps extends InputProps {
  defaultChecked?: boolean;
  checked?: boolean;
}
```

**System:**
Environment Info:

  System:
    OS: macOS 10.15.3
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  Binaries:
    Node: 10.18.1 - ~/.nvm/versions/node/v10.18.1/bin/node
    Yarn: 1.21.1 - ~/repos/ui-kit/node_modules/.bin/yarn
    npm: 6.13.7 - ~/repos/ui-kit/node_modules/.bin/npm
  Browsers:
    Chrome: 79.0.3945.130
    Firefox: 71.0
    Safari: 13.0.5
  npmPackages:
    @storybook/addon-actions: 5.3.12 => 5.3.12 
    @storybook/addon-docs: ^5.3.12 => 5.3.12 
    @storybook/addon-links: 5.3.12 => 5.3.12 
    @storybook/addon-viewport: ^5.3.12 => 5.3.12 
    @storybook/addons: 5.3.12 => 5.3.12 
    @storybook/preset-create-react-app: ^1.5.2 => 1.5.2 
    @storybook/react: ^5.3.12 => 5.3.12 
    @storybook/theming: ^5.3.12 => 5.3.12 

**Additional context**
It used to work fine in v5.2

**Comment by shilman** [comment]
cc @patricklafrance

**Comment by shilman** [comment]
Repro: https://github.com/storybookjs/storybook/commit/ce8a9f2772c77274672b4b32bbbbaf137f446b5e

**Comment by etylsarin** [comment]
this is still an issue

**Comment by shilman** [comment]
@etylsarin can you try the recommended 6.0 setup (should work in 5.3 too) and based on the repro linked above I expect the problem to be fixed:

https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#react-prop-tables-with-typescript

**Comment by Benwick91** [comment]
I have the same problem. The extends properties aren't shown in the prop table. But I want to use the `react-docgen-typescript-loader` because I use smart-knobs and for the select knobs I have to use the option `shouldExtractLiteralValuesFromEnum`.

I use CRA. Is there a possibility to get it work that I can see all props. That is needed for the documentation, because other users should see, what the props are and what the props do. Thank you!

**Comment by etylsarin** [comment]
Hi everyone, so after some time, I've returned to this issue as I wanted to upgrade SB version to 6. I finally realised that the issue was caused by autogenerated propTypes (via babel-plugin-typescript-to-proptypes). When propTypes are declared, SB uses those over the ones generated via docGen.
And babel-plugin-typescript-to-proptypes has the issue with interface extends as I described above.
