### ISSUE TITLE
addon-docs inserts TypeScript JSDoc as HTML markup/string.

### ISSUE THREAD

**Issue by ivoiv** [storybookjs/storybook#9766]
**Describe the bug**
JSDoc is from .tsx files is imported as pure HTML markup text with no formatting.

**To Reproduce**
1. Go to https://gist.github.com/shilman/bc9cbedb2a7efb5ec6710337cbd20c0c
2. Follow the guide through Step 5.
3. Add some JSDoc to the The world's most _basic_ button section
4. Open Storybook

**Expected behavior**
A better representation of the JSDoc markup, with better visual presentation of the JSDoc tags and their contents.
Show the @example tag as code snippet rather than making a HTML element out of it.

Possibility to ignore certain JSDoc tags, like the @example tag.

**Screenshots**
![image](https://user-images.githubusercontent.com/11502345/73861665-a19f5480-483d-11ea-8ad1-6d0d2ce1bce8.png)

**Code snippets**
````
/**
 * The world's most _basic_ button
 * 
 * @param {string} name - This should be a string.
 * 
 * @param {ExtraProps} extraProps
 * 
 * @example <Button>Click me!</Button>
 * 
 */
````

**System:**
````
Environment Info:

  System:
    OS: macOS Mojave 10.14.5
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 11.15.0 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.7.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 79.0.3945.130
    Firefox: 72.0.2
    Safari: 12.1.1
  npmPackages:
    @storybook/addon-actions: ^6.0.0-alpha.6 => 6.0.0-alpha.6 
    @storybook/addon-docs: ^6.0.0-alpha.6 => 6.0.0-alpha.6 
    @storybook/addon-links: ^6.0.0-alpha.6 => 6.0.0-alpha.6 
    @storybook/addons: ^6.0.0-alpha.6 => 6.0.0-alpha.6 
    @storybook/preset-create-react-app: ^1.5.2 => 1.5.2 
    @storybook/react: ^6.0.0-alpha.6 => 6.0.0-alpha.6 
````
**Additional context**
Repository with problem - [https://github.com/ivoiv/cra-ts](https://github.com/ivoiv/cra-ts)

**Comment by ivoiv** [comment]
Bumping this as it's still relevant.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid.

Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
