### ISSUE TITLE
Allow meta viewport tag to be customised

### ISSUE THREAD

**Issue by karl** [storybookjs/storybook#9776]
### Bug or support request summary

We have an existing website that we are adding React components to. The website has a viewport tag with the initial scale set to `0.6`:

```
<meta name="viewport" content="width=device-width, initial-scale=0.6">
```

We would like to set Storybook to use the same `initial-scale` value so that components rendered there appear the same size as they will on the website.

We've tried adding a viewport tag to `preview-head.html` but the browser (Chrome) seems to ignore it in favour of the one that Storybook defines above it in the document head.

It would be great if we had the option of replacing the meta viewport tag without our own one.

- @storybook/react 5.3.9

### Affected platforms 

- Chrome on macOS running using the devtools to run as an iPhone 6 device.

**Comment by christopherhafke** [comment]
Hi, @eashwar and I are interested in working on this as first-time contributors. Could we take this one?

**Comment by shilman** [comment]
@christopherhafke absolutely! contributions always welcome!

**Comment by christopherhafke** [comment]
Unfortunately, due to our schedules, I don't think we're going to be able to work on this issue, and we didn't want to prevent others from tackling it. Sorry about that!

**Comment by krutoo** [comment]
@shilman is it possible now to change default meta tags?
