### ISSUE TITLE
storyshots found 0 stories

### ISSUE THREAD

**Issue by iansan5653** [storybookjs/storybook#9779]
When I attempt to run `npm test` after setting up storyshots, the storyshots test fails with "storyshots found 0 stories":
![image](https://user-images.githubusercontent.com/2294248/73959824-ebd51400-48d7-11ea-86b4-7ed534457843.png)

I am using create-react-app with TypeScript and storybook `^5.3.8`. I have (in addition to storyshots) the following addons:

- actions
- knobs
- storysource
- viewport
- contexts

My `config.tsx` file looks like this (note that I set up the `requireContext` macro; I know that's working properly because Storybook does start and load the stories):
```tsx
import {withContexts} from "@storybook/addon-contexts/react";
import {withKnobs} from "@storybook/addon-knobs";
import {INITIAL_VIEWPORTS} from "@storybook/addon-viewport";
import {addDecorator, addParameters, configure} from "@storybook/react";
import React from "react";
import GlobalStyle from "../src/components/GlobalStyle";
import {contexts} from "./contexts";
import requireContext from 'require-context.macro';

const req = requireContext("../src/components", true, /stories\.tsx$/);

addDecorator((storyFn) => (
  <>
    <GlobalStyle />
    {storyFn()}
  </>
));
addDecorator(withKnobs);
addDecorator(withContexts(contexts));

addParameters({
  viewport: {
    viewports: INITIAL_VIEWPORTS,
    defaultViewport: "iPad (L)"
  }
});

configure(req, module);
```

My `presets.js` file looks like this:
```js
const path = require("path");

module.exports = [
  {
    name: "@storybook/preset-create-react-app",
    options: {
      tsDocgenLoaderOptions: {
        tsconfigPath: path.resolve(__dirname, "../tsconfig.json")
      }
    }
  },
  {
    name: "@storybook/addon-docs/preset",
    options: {
      configureJSX: true
    }
  }
];
```

And I also have a custom Webpack config for storybook to make `source-loader` work:
```js
const path = require("path");
const webpack = require("webpack");

module.exports = function({config}) {
  config.module.rules.unshift({
    test: /stories\.tsx$/,
    loaders: [
      {
        loader: require.resolve("@storybook/source-loader"),
        options: {parser: "typescript"}
      }
    ],
    enforce: "pre"
  });

  config.plugins.push(
    new webpack.DefinePlugin({
      SC_DISABLE_SPEEDY: true
    })
  );

  return config;
};
```

My `Storyshots.test.ts` file is the most basic setup:
```ts
import initStoryshots from "@storybook/addon-storyshots";

initStoryshots();
```

My folder structure looks like this:

- .storybook
  - addons.ts
  - config.tsx
  - presets.js
  - webpack.config.js
- src
  - components
    - ComponentName
      - stories.tsx
  - Storyshots.test.ts

My stories files use the export form, so each looks something like this:
```tsx
import React from "react";
import ComponentName from ".";

export default {
  title: "ComponentName",
  component: ComponentName
};

export const Default = (): React.ReactNode => (
  <ComponentName />
);
```

Please let me know if I can provide any further information - I'm not sure what's relevant and what's not.

**Comment by iansan5653** [comment]
I was able to resolve this by switching to the new `main.js` config method and using `stories: ["../src/components/**/stories.tsx"]` instead of the context loader.

**Comment by egor-a-trubnikov-panov** [comment]
main.js
`module.exports = {
  stories: ['../src/**/*.stories.tsx'],
  addons: [
    '@storybook/addon-knobs/register',
    '@storybook/addon-actions/register',
    '@storybook/addon-viewport/register',
    '@storybook/addon-backgrounds/register',
  ],
};
`

**Comment by egor-a-trubnikov-panov** [comment]
Even if I specify the path in the config

<img width="982" alt="Снимок экрана 2020-03-18 в 11 55 44" src="https://user-images.githubusercontent.com/2979574/76933858-e83d9f80-690f-11ea-9f4b-6c7b3191696b.png">

**Comment by iansan5653** [comment]
@egor-a-trubnikov-panov You should probably file a new bug; looks like a separate issue since mine was caused by the update to the new config method.

**Comment by MarkLyck** [comment]
I'm also having this issue with the new method.
