### ISSUE TITLE
[addon-docs] PropTable shows only default props in production

### ISSUE THREAD

**Issue by iamshadmirza** [storybookjs/storybook#9784]
**Describe the bug**
Addon-docs PropTable is not working correctly in production. The table is correct in development but after deploying to Netlify, it shows only those props which are common to `propTypes` and `defaultProps`. Also, the description column shows `unknown`. The deployed site is here: https://rnds.netlify.com

**To Reproduce**
1. Go to https://github.com/iamshadmirza/react-native-design-system

There is no error log. StoryBook is compiling without error. The PropTable is not working as expected in production.

**Expected behavior**
https://github.com/iamshadmirza/react-native-design-system

**Screenshots**
This is in development:   

![Screenshot (64)](https://user-images.githubusercontent.com/22999030/73993953-cef11d00-4979-11ea-8d81-f601dfc7fc91.png)

This is after deploying to Netlify or GitHub pages.  

![Screenshot (65)](https://user-images.githubusercontent.com/22999030/73993984-eaf4be80-4979-11ea-8689-7c7b6a6b9e49.png)

**Code snippets**
To run storybook in development:
```shell
start-storybook -p 9001 -c .storybook -s .storybook/assets
```
To create build:
```shell
build-storybook -c .storybook -s .storybook/assets -o docs
```

**Additional context**
Modules used
```json
{
    "@storybook/addon-actions": "^5.3.12",
    "@storybook/addon-docs": "^5.3.12",
    "@storybook/addon-knobs": "^5.3.12",
    "@storybook/react": "^5.3.12",
    "@storybook/theming": "^5.3.12",
}
```

**Comment by iamshadmirza** [comment]
Any support on this?

**Comment by shilman** [comment]
I'm not seeing this on https://storybook-design-system.netlify.com/
