### ISSUE TITLE
Unable to upgrade from Angular 8 -> 9 with the Angular CLI due to zone.js dependency

### ISSUE THREAD

**Issue by TheAngularGuy** [storybookjs/storybook#9785]
**Describe the bug**
Upgrading from Angular 7 to Angular 8 via the CLI won't proceed due to @storybook/angular's zone.js peerDependency.

**To Reproduce**
`ng update @angular/core @angular/cli -C`

**Output**
`
Package "@storybook/angular" has an incompatible peer dependency to "zone.js" (requires "^0.8.29 || ^0.9.0", would install "0.10.2").
`

**Expected behavior**
The upgrade should complete.

**System:**
- System:
    OS: Windows 10 10.0.17134
    CPU: (4) x64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
 - Binaries:
    Node: 12.14.1 - C:\Program Files\nodejs\node.EXE
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  - Browsers:
    Edge: 42.17134.1098.0

**Comment by gaetanmaisse** [comment]
@TheAngularGuy which version of Storybook are you using? Because it should have been fixed with https://github.com/storybookjs/storybook/commit/3b84236d60bec580c5d3849d58f63458bea4e80e and released with Storybook 5.3.
