### ISSUE TITLE
StyledComponent ThemeProvider value working in canvas but causes error in Docs in react storybook with addon-docs

### ISSUE THREAD

**Issue by suraj-eai** [storybookjs/storybook#9789]
**Describe the bug**
I have created react typescript app with Crate React App and integrated Storybook.

In the storybook `preview.js`:

```js
import React, { Fragment } from 'react';
import { addDecorator } from '@storybook/react';
import { ThemeProvider } from 'styled-components';
import { GlobalStyle, theme } from '../src/theme';

addDecorator(story => (
  <ThemeProvider theme={theme}>
    <Fragment>
      <GlobalStyle />
      {story()}
    </Fragment>
  </ThemeProvider>
));

```

The component works fine in Canvas tab but gives error in Docs tab. 

![Screen Shot 2020-02-07 at 22 18 58](https://user-images.githubusercontent.com/52927184/74047112-ecfd6280-49f7-11ea-9090-7bc46b3184b7.png)

![Screen Shot 2020-02-07 at 22 19 17](https://user-images.githubusercontent.com/52927184/74047134-f38bda00-49f7-11ea-81fa-17ec2841fa2d.png)

In `Button.tsx`

```js
const Button = styled.button`
 background-color: ${props => props.theme.color.primary};
`;

In Docs tab, the theme object is undefined but works in Canvas tab. 
```

The issue occurs in `Button.stories.mdx` but does not occur if we create `Button.stories.tsx` file.

**Comment by shilman** [comment]
Can you show me `Button.stories.tsx` and `Button.stories.mdx` too?

**Comment by shilman** [comment]
Aha looks like you fixed it 👍

**Comment by suraj-eai** [comment]
@shilman I reinstalled storybook and all storybook integrations from beginning and the error seems to be fixed.
