### ISSUE TITLE
Does the web-components template need a main.js?

### ISSUE THREAD

**Issue by robdodson** [storybookjs/storybook#9793]
**Describe the bug**
I noticed when I used the web-components template that I got duplicate registration errors. It seems like the stories are being loaded by both the `main.js` and `preview.js` files. Would it make sense to remove the `main.js` file?

**main.js**
![image](https://user-images.githubusercontent.com/1066253/74077175-8580ec00-49d2-11ea-83b7-c85bb44d2dc3.png)

**preview.js**
![image](https://user-images.githubusercontent.com/1066253/74077181-90d41780-49d2-11ea-8be5-ce001fb8ea02.png)

**To Reproduce**
1. Run `npx -p @storybook/cli sb init -t web_components`
2. Run `npm run storybook`

**Expected behavior**
No warnings in the console

**Screenshots**

![image](https://user-images.githubusercontent.com/1066253/74077150-4357aa80-49d2-11ea-86bc-8ba38d03b442.png)

**Comment by shilman** [comment]
yeah this looks like a bug to me, possibly introduced when the templates were upgraded to `main.js` @ndelangen 

@robdodson i'd guess removing `main.js` is a good temporary workaround

@daKmoR what do you think? what's the longterm solution?

**Comment by daKmoR** [comment]
in many cases there should be no need for a `preview.js`

loading of the stories should definitely be handled in main.js... an iirc it also offers a functionality to hook into the HMR... we should update this in the docs/demo

**Comment by shilman** [comment]
@daKmoR I guess the big question is what's the HMR solution for web components using `main.js`. I can understand the `preview.js` solution (sort of) but not sure how I'd port that to `main.js`...

**Comment by fernandopasik** [comment]
wouldn't it be better to keep the semantics of main.js and preview.js and have a way to disable HMR and remove the hack from preview.js?

**Comment by fernandopasik** [comment]
This might be related to #9496

**Comment by fernandopasik** [comment]
I think with this change https://github.com/storybookjs/storybook/blob/next/app/web-components/src/client/index.ts#L36 full reload is done so this is no longer needed.

**Comment by shilman** [comment]
Son of a gun!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.3.0-beta.13 containing PR #15149 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
