### ISSUE TITLE
Import Less not work.

### ISSUE THREAD

**Issue by LittleboyHarry** [storybookjs/storybook#9796]
**Describe the bug**
Can't import less file in JavaScript.

**To Reproduce**
1. Use Creaet-React-App create a default React template SPA
2. `cd <dir>`, then Execute `npx -p @storybook/cli sb init`
3. `yarn add -D less less-loader`
4. modify `.storybook/main.js`:
5. create 'src/stories/temp.less`, then write some style, and import it in story module:

```js
import './temp.less';
````
```less
span{background:black;}
// for test, it makes emojis container background in the template example Button story to be black
```

**Expected behavior**
Import Less file successfully into story, then show styles defined by the less file.

**Screenshots**

I know the webpack doesn't load less finally by devtools

![image](https://user-images.githubusercontent.com/13063376/74096306-2dfc9080-4b38-11ea-8637-6bb2faa824c5.png)

However, when I wrote down `options.errorFlag = true` in rules delibrately, it throw a loader error, which proves it has already parse the imported less file. Why? 🤔

![image](https://user-images.githubusercontent.com/13063376/74096575-ae70c080-4b3b-11ea-813e-a5635af2735f.png)

**Code snippets**

.storybook/main.js

```js
const fs = require('fs')
const path = require('path')

module.exports = {
  stories: ['../src/**/*.stories.js'],
  addons: [
    '@storybook/preset-create-react-app',
    '@storybook/addon-actions',
    '@storybook/addon-links',
  ],
  webpackFinal: async (config, { configType }) => {
    config.module.rules.push({
      test: /\.less$/,
      use: [
        'style-loader',
        'css-loader',
        'resolve-url-loader',
        {
          loader: 'less-loader',
          options: {
            javascriptEnabled: true,
            sourceMap: true,
          }
        }]
    });
    return config;
  },
};
```

**System:**

* System:
  - OS: Windows 10 10.0.18363
  - CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
* Binaries:
  - Node: 12.14.0 - C:\Program Files\nodejs\node.EXE
  - Yarn: 1.19.2 - C:\Program Files\nodejs\yarn.CMD
  - npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
* Browsers:
  - Chrome: 79.0.3945.131

**Additional context**

* Storybook Version:

Using the newest stable 5.3.12.

If I change the `.less` extension to `.css`, it works! Why not less?

**Comment by c690554125** [comment]
I find that less file was handled with file-loader or url-loader. But I don't know how to fix this. 😢 
```jsx
import styles from './index.less'

console.log(style) // it's a url path
```

**Comment by billcreative** [comment]
I've been looking for the answers for a similar problem. In [@storybook/preset-create-react-app](https://github.com/storybookjs/presets/tree/master/packages/preset-ant-design) it mentions configuring CRA to exclude less from the file loader.

```
{
  "name": "@storybook/preset-create-react-app",
  "options": {
    "craOverrides": {
      "fileLoaderExcludes": ["less"]
    }
  }
}
```

May help.

**Comment by GloriaCHL** [comment]
I have the same problem. I use `index.module.less`module  file which  support in create-react-app 2.

**Comment by honorsuper** [comment]
i have the same problem

**Comment by weshoke** [comment]
Here's an example using craco and semantic UI

```
module.exports = {
  stories: ['../src/**/*.stories.js'],
  addons: [
    '@storybook/preset-create-react-app',
    '@storybook/addon-actions',
    '@storybook/addon-links',
  ],
  webpackFinal: async (webpackConfig, { configType }) => {
    // `configType` has a value of 'DEVELOPMENT' or 'PRODUCTION'
    // You can change the configuration based on that.
    // 'PRODUCTION' is used when building the static version of storybook.
    const { loadCracoConfig } = require('@craco/craco/lib/config');
    const { getCraPaths } = require('@craco/craco/lib/cra');
    const context = {env: process.env.NODE_ENV};
    const cracoConfig = loadCracoConfig(context);
    context.paths = getCraPaths(cracoConfig);
    console.log(context);
    const {overrideWebpackConfig} = require('@semantic-ui-react/craco-less');
    overrideWebpackConfig({
      context,
      webpackConfig
    });

    // Return the altered config
    return webpackConfig;
  },
};
```

**Comment by nanjixiong218** [comment]
because cra's  file-loader intercept all other file, so the less file can't go into less-loader;
solution is to config the @storybook/preset-create-react-app;
![image](https://user-images.githubusercontent.com/5085933/83622841-18b5e100-a5c3-11ea-801d-28bac3207078.png)
there are some diffrent between storebook 5.3.0 and the 5.2.x ; can read https://github.com/storybookjs/presets/tree/master/packages/preset-create-react-app

**Comment by younthu** [comment]
same here

**Comment by Tilek0** [comment]
Hi everyone, i cant integrate less into my react app 
i used yarn add less less-loader @types/less but there are not anough 
a question is, I can't do like import styles from './someStyle.less'

**Comment by grylance** [comment]
we're also experiencing issues trying to import styles into our components in storybook using `css-loader` & `less-loader` like so `import styles from './Button.less'`

**Comment by jsweber** [comment]
I meet this problem too. This is my resolution.
```js
// main.js

webpackFinal: async (config) => {
    const lessLoaderChain = {
      test: /\.less$/,
      use: [
        'style-loader',
        {
          loader: 'css-loader'
        },
        {
          loader: 'less-loader',
          options: {
            lessOptions: {
              javascriptEnabled: true
            }
          }
        }
      ]
    }

    if (config.module.rules[config.module.rules.length - 1].oneOf) {
      config.module.rules[config.module.rules.length - 1].oneOf.unshift(lessLoaderChain);
    } else {
      config.module.rules.unshift(lessLoaderChain);
    }
    
    return config;
  },

```
