### ISSUE TITLE
StoryBook 5.3.12 fail add rules, work on 5.1.10 

### ISSUE THREAD

**Issue by gwmaster** [storybookjs/storybook#9800]
If you are reporting a bug or requesting support, start here:
### Bug or support request summary

try to load less on my starter project 
https://github.com/gwmaster/reactStarter
example 
https://github.com/gwmaster/reactStarter/tree/master/src/appsDevelop/starterProject/components/Avatar

### Steps to reproduce

5.3.12 don't work 
.storybook/main.js
```
const path = require('path');

module.exports = {
    stories: ['../src/**/*.stories.[tj]s'],
    addons: [
        '@storybook/preset-create-react-app',
        '@storybook/addon-actions',
        '@storybook/addon-links',
        '@storybook/addon-storysource',
        '@storybook/addon-knobs',
    ],
    webpackFinal: async (config, { configType }) => {
        config.module.rules.push({
            test: /\.less$/,
            loaders: [
                'style-loader',
                'css-loader',
                {
                    loader: 'less-loader',
                    options: {
                        modifyVars: {},
                        javascriptEnabled: true
                    }
                }
            ],
            include: [
                path.resolve(__dirname, '../src'),
                /[\\/]node_modules[\\/].*antd/
            ]
        });
        console.log('less config')
        // Return the altered config
        return config;
    },
};
```

work on 5.1.10 
.storybook/webpack.config.js
```
const path = require('path');
module.exports = async ({ config, mode }) => {


  config.module.rules.push({
      test: /\.less$/,
      loaders: [
          'style-loader',
          'css-loader',
          {
              loader: 'less-loader',
              options: {
                  modifyVars: {},
                  javascriptEnabled: true
              }
          }
      ],
      include: [
        path.resolve(__dirname, '../src'),
        /[\\/]node_modules[\\/].*antd/
      ]
  });
  return config;
};

```

**Comment by shilman** [comment]
Cc @mrmckeb

**Comment by mrmckeb** [comment]
This is an interesting one, sorry you've hit this @gwmaster. We don't officially support modifying the CRA config, but what you're doing should work.

Can you try adding that rule in before CRA's `oneOf` configuration?

Also, can I suggest you look to use CRA's new template feature for your starter? It might suit you better :)

**Comment by gwmaster** [comment]
i upgrade to 6.0.0-alpha.9 and now its work
https://github.com/gwmaster/reactStarter

**Comment by mrmckeb** [comment]
@shilman is there anything in 6.x that would have made a difference here? I'm a little confused by what's happened - but have been out of the loop.

**Comment by shilman** [comment]
@mrmckeb i'm not sure what's going on here. there has been some drama around `MiniCssExtractPlugin`, e.g. https://github.com/storybookjs/storybook/issues/9777#issuecomment-584058329, but I haven't tracked down the current status in 6.0/5.3 to know what's going on. @ndelangen was looking into this.

**Comment by ndelangen** [comment]
I nuked the MiniCssExtractPlugin, because it was giving nothing but grief.

5.3 should work fine with the cra preset configured.

**Comment by shilman** [comment]
Releasing this now as 5.3.13. Hoping it will fix peoples' problems and not cause new ones 🙈

**Comment by mrmckeb** [comment]
Hi all, is this still an issue? Or can we close this off?

**Comment by gwmaster** [comment]
ok i definitely find how reproduce the problem
why this happen i don't know
load my 
https://github.com/gwmaster/reactStarter
if node_modules have 'react-scripts' less don't loaded!
antd button no less styles
![image](https://user-images.githubusercontent.com/5362853/75859738-3d06f380-5e03-11ea-908d-4a89147d34a2.png)

work after delete 'react-scripts'
antd less styles loaded
![image](https://user-images.githubusercontent.com/5362853/75859747-442e0180-5e03-11ea-8cff-f7a97b908890.png)
the storybook throw error
![image](https://user-images.githubusercontent.com/5362853/75859769-514af080-5e03-11ea-9e07-efc7a4abfbcc.png)

**Comment by mrmckeb** [comment]
Hi @gwmaster, if `react-scripts` is detected in the project, that webpack config will be used for Storybook.

It looks like you've got multiple configurations in that project. CRA doesn't support Less, are you modifying it?

**Comment by gwmaster** [comment]
if not include react-scripts StoryBook write failed .

**Comment by dergroncki** [comment]
I have a similar problem. I want to use the "csv-loader" to load a csv-file into one of my stories.

I am using Storybook with CRA. As well I am using the lastest Beta of Storybook: @storybook/react v6.0.0-beta.30

I have modified the .storybook\main.js as it is described in the documentation:

```javascript
module.exports = {
  stories: ['../src/components/**/*.stories.js'],
  addons: [
    '@storybook/preset-create-react-app',
    '@storybook/addon-actions',
    '@storybook/addon-links',
  ],
  webpackFinal: async (config, { configType }) => {
    config.module.rules.push({

        test: /\.csv$/,
        loader: 'csv-loader',
        options: {
          dynamicTyping: true,
          header: true,
          skipEmptyLines: true
        }

    });

    console.dir(config, { depth: null });

    // Return the altered config
    return config;
  },
};
```
In my story file I imported the csv file like so:
```javascript
import csvDataFromFile from '../log_ibe.csv';
```
For testing if the import works, I am using console.log in one of the model exports:
```javascript
  console.log(csvDataFromFile);
```
But I only get the following output:
```javascript
static/media/log_ibe.5217ea59.csv
```

What could be the problem? Any hint would be helpful. Thank you.
