### ISSUE TITLE
[addons-docs] React RE rendering with decorator work's only on last preview child

### ISSUE THREAD

**Issue by Vol4n3** [storybookjs/storybook#9802]
Storybook version : 5.3.12
Styled-component version : 5.0.1

I made a decorator that change the theme with styled-component ThemeProvider  

This decorator work in canvas but in docs just the last child <Preview> change

I have duplicated Preview in MDX files for see changes.

The decorator has been added in config.js
like 
```
import { addDecorator } from "@storybook/react"; 
import {ThemeDecorator} from './custom-addons/theme-decorator';

addDecorator(ThemeDecorator);
```

My ThemeDecorator Look's like

```
import React from 'react';
import {ThemeProvider} from 'styled-components';
import {defaultTheme} from './default-theme';

class ThemeOptions extends React.Component {
  
  componentDidMount() {
    // window parent for access outside iframe
    window.parent.ListenerThemeChange = theme => {
      this.setState({
        theme
      });
    };
  }

  render() {
    return (
      <ThemeProvider theme={{ID :this.state.theme}}>
        {this.props.children}
      </ThemeProvider>
    );
  }

  state = {
    theme: defaultTheme
  };
}
export const ThemeDecorator = storyFn => (
  <ThemeOptions>{storyFn()}</ThemeOptions>
);
```

![example-error](https://user-images.githubusercontent.com/11995909/74144396-f1469d00-4bfc-11ea-9d6b-45e4267b8ddb.gif)

**Comment by shilman** [comment]
Thanks @Vol4n3, this looks like a good bug. Do you have a repro handy, or any chance you can create one in the Storybook `official-storybook` and submit as a PR?

**Comment by Vol4n3** [comment]
ok  @shilman , I 'll try to reproduce it on `official-storybook` !

**Comment by Vol4n3** [comment]
@shilman I did not succeed to compile storybook on my environment for dev.

But i made a repository on my github to reproduce this https://github.com/Vol4n3/storybook-addons-docs-bug-react-rendering

**Comment by shilman** [comment]
Thanks @Vol4n3! I'll try to figure out what's going on, but have a backlog of other issues ahead of this. If anybody else has bandwidth to look, that would be amazing 💯

**Comment by Vol4n3** [comment]
Sorry, this bug is due to a misuse of the event subscribe in the decorator, event was overwrite that is why only last child change.

Sorry again
