### ISSUE TITLE
Refactor story state mechanism

### ISSUE THREAD

**Issue by tmeasday** [storybookjs/storybook#9811]
We have `useStoryState`, however it is buggy and not very well tested.

Implement a new `state` field on story (eq. `parameters`) that:
  - is mutable, both from the manager and preview,
  - the "master" copy is stored in the store
  - whenever it changes, it re-renders the current story.

Additionally:
  - refactor `useStoryState` to leverage it, manager+preview,
  - add a "state initializer" concept to the store that allows you to initialize the state of a story before it renders, based on parameters.

**Comment by atanasster** [comment]
That's the spirit - I think I have seen that approach somewhere :) 
A few notes:
- Unless I misunderstand, but there isn't anything to refactor from useStoryState (except the name), right? The approach will be to implement the state in the api and then if users do need a hook, create a useStoryState hook on top of the api. 
- "initialize the state of a story before it renders" - that will be a bit of a hack and in my opinion will cause issues long term, I believe it will be better to initialize state at story "create" (loading of stories)

Good luck.

**Comment by tmeasday** [comment]
> Unless I misunderstand, but there isn't anything to refactor from useStoryState (except the name), right? The approach will be to implement the state in the api and then if users do need a hook, create a useStoryState hook on top of the api.

Heh, I guess it just depends what you mean by "refactor" ;)

**Comment by atanasster** [comment]
Lol :)

**Comment by shilman** [comment]
Egads!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-alpha.22 containing PR #10014 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by tmeasday** [comment]
We still need to delete `useStoryState` as per a conversation with @ndelangen

**Comment by shilman** [comment]
Whoopee!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-alpha.24 containing PR #10015 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
