### ISSUE TITLE
Addon-docs: default value is an integer when it should be undefined [CRA + TS]

### ISSUE THREAD

**Issue by taze-fullstack** [storybookjs/storybook#9827]
**Describe the bug**
The default value on the prop table is an integer when it should be undefined.

**To Reproduce**
1. Setup CRA + typescript
2. add a component with an interface containing two or more props
3. define only one defaultProp

**Expected behavior**
Only the defined default prop must contain a value. Instead, others have integers on them.

**Screenshots**
![image](https://user-images.githubusercontent.com/36070737/74316920-6361e200-4db5-11ea-8f71-65fa38c44dd0.png)

**Code snippets**
```
export interface HelloProps {
  title: string;
  foo: boolean;
  bar?: string[];
}

const Hello = ({title}: HelloProps) => {
  return <div className="hello">Hello Component {title}</div>;
};

Hello.defaultProps = {
  title: 'this is the default :)',
};

export default Hello;
```

**System:**
```
Environment Info:

  System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 Intel(R) Core(TM) i3-4170 CPU @ 3.70GHz
  Binaries:
    Node: 12.14.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.21.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
```

**Additional context**

**Comment by shilman** [comment]
Repro: https://github.com/storybookjs/storybook/commit/05f44c1572409c13b4e7fef3f6633185bb55467a

**Comment by shilman** [comment]
Egads!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-alpha.17 containing PR #9873 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Ooh-la-la!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.14 containing PR #9873 that references this issue. Upgrade today to try it out!
