### ISSUE TITLE
Action add-on position

### ISSUE THREAD

**Issue by maciekgrzybek** [storybookjs/storybook#9829]
**Is your feature request related to a problem? Please describe.**
I am building a mini-component that uses Intersection Observer API. The action-addon is 'breaking' the functionality of the demo, as it's covering the bottom of the screen, so the Observer callback doesn't fire when an element is in the viewport. I still want to use that addon, but I wish there was a config option to move the addon to the right instead of the bottom.

**Describe the solution you'd like**
I want to use the current functionality that changes the addon position and extend it, so when setting up Storybook I can pass the correct config option.

**Are you able to assist bring the feature to reality?**
Yes, I am happy to work on this.

**Comment by shilman** [comment]
Try adding the following to `manager.js`:

```js
import { addons } from '@storybook/addons';

addons.setConfig({
  panelPosition: 'right',
  theme,
});
```

**Comment by maciekgrzybek** [comment]
@shilman thanks for that 😄 is it anywhere in the Docs? I couldn't find it.

**Comment by maciekgrzybek** [comment]
Nevermind, found it all :) Thanks again for help!
