### ISSUE TITLE
Addon-docs: Move to react-docgen for typescript prop tables

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#9837]
We currently use `react-docgen` for JS prop tables and `react-typescript-docgen-loader` (`RDTL`) for TS prop tables. Now that `react-docgen` supports Typescript natively, let's simplify our lives and our users' configurations by moving to `react-docgen` for all react prop table generation.

- [x] Use react-docgen
  - [x] Remove `RDTL` from `preset-typescript` https://github.com/storybookjs/presets/pull/68
  - [x] Remove `RDTL` from `preset-create-react-app` https://github.com/storybookjs/presets/pull/103
- [x] Set up test cases in #9836
- [ ] File bugs as needed to `react-docgen`
- [x] Update [Storybook Docs w/ CRA & TypeScript](https://gist.github.com/shilman/bc9cbedb2a7efb5ec6710337cbd20c0c) walkthrough
- [ ] Migration guide

**Comment by maniax89** [comment]
@shilman was taking a look at the reasoning behind this issue and one of the issues I was trying to get around was this statement in `react-docgen` for typescript:

https://github.com/reactjs/react-docgen#flow-and-typescript-support
> Note: react-docgen will not be able to grab the type definition if the type is imported or declared in a different file.

This is noted in https://github.com/strothj/react-docgen-typescript-loader/issues/80#issuecomment-583107882

> This loader unfortunately does not automatically locate your project's tsconfig.json file (would be a great enhancement if a pull request is made).

> If its path isn't specified, the underlying library react-docgen-typescript will fallback to creating a new TypeScript project for each file (I believe), which unfortunately does not resolve types external to the file being checked.

>I've updated the documentation and updated the example project to show its usage:

will `react-docgen` support loading types external to the file being checked eventually? or is this use-case dropped in the CRA preset (https://github.com/storybookjs/presets/pull/103) without a workaround?

**Comment by shilman** [comment]
@maniax89 please upvote this https://github.com/reactjs/react-docgen/pull/352

**Comment by shilman** [comment]
OK gang. We've reversed course on this:

👉👉👉 **[`react-docgen-typescript` is now the default in SB6](https://gist.github.com/shilman/036313ffa3af52ca986b375d90ea46b0).**

I documented this out in detail for anybody who cares, and will be updating the docs shortly.
