### ISSUE TITLE
Form Textarea does not have a height or maxHeight

### ISSUE THREAD

**Issue by Raphe-dev** [storybookjs/storybook#9849]
**Describe the bug**
Textarea in Knobs addon does not have a height, which makes a huge text area when passing big arrays.

**To Reproduce**
Create a object or text knobs and pass a big array of data to it.

**Expected behavior**
Maybe a 10 or 20 line default height would be great (200 - 400px according to hardcoded line-height).

**Code snippets**
[/lib/components/src/form/input/input.tsx line148](https://github.com/storybookjs/storybook/blob/17298955ad839c881e9f8e734cb06d25e5b3b586/lib/components/src/form/input/input.tsx#L148)
I'm not used to TypeScript but I believe adding a height : 200 at this line would solve this. 
Or maybe it would just make all textarea 200px by default no matter the content? 
If so maybe a maxHeight of 400 - 600 would be good anyway it does not make sense to be bigger than that does it?

**System:**

>   System:
>     OS: Linux 5.3 Ubuntu 18.04.4 LTS (Bionic Beaver)
>     CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
>   Binaries:
>     Node: 12.15.0 - /usr/bin/node
>     npm: 6.13.4 - /usr/bin/npm
>   Browsers:
>     Chrome: 80.0.3987.87
>     Firefox: 72.0.2
>   npmPackages:
>     @storybook/addon-actions: ^5.3.12 => 5.3.12 
>     @storybook/addon-knobs: ^5.3.12 => 5.3.12 
>     @storybook/addon-links: ^5.3.12 => 5.3.12 
>     @storybook/addon-viewport: ^5.3.12 => 5.3.12 
>     @storybook/addons: ^5.3.12 => 5.3.12 
>     @storybook/vue: ^5.3.12 => 5.3.12 

I know there was an issue about that in the near past that the bot closed ( [Issue 8192](https://github.com/storybookjs/storybook/issues/8192) ) but I believe this is a simple fix that would benefit all big data knobs users

**Comment by shilman** [comment]
@Raphe-dev any interest in contributing a small PR for this?
