### ISSUE TITLE
How can I selectively show tabs in panel?

### ISSUE THREAD

**Issue by dvnrsn** [storybookjs/storybook#9853]
**Is your feature request related to a problem? Please describe.**
Is there a way to selectively show addons like [actions](https://github.com/storybookjs/storybook/tree/HEAD/addons/actions), [knobs](https://github.com/storybookjs/storybook/tree/master/addons/knobs)

I want to hide globally and then pick certain stories that should show them

![image](https://user-images.githubusercontent.com/9112811/74492915-bad38100-4e8d-11ea-996f-386865c71528.png)

Docs has [a good way of disabling](https://github.com/storybookjs/storybook/blob/master/addons/docs/docs/docspage.md#replacing-docspage) per story but I'd like a way of enabling per story.

I feel like this would exist but I'm not understanding. I tried excluding from addons in main.js and then using the `.story = {decorator: [knobs]}` kind of syntax

**Comment by shilman** [comment]
@dvnrsn you can use `showPanel` to completely show or hide that panel based on the story https://storybook.js.org/docs/configurations/options-parameter/#per-story-options

**Comment by dvnrsn** [comment]
This doesn't quite address the job to be done seeing as I generally want to show only a few of the addons. It is good to know about because I would use it. However, when I apply the following code on an individual story, it seems to apply to every story, hiding the panel globally which is not desired.

```js
export default {
  title: 'mycomp',
  component: mycomp,
  parameters: {
    options: {
      showPanel: false,
    }
  }
}

**Comment by dvnrsn** [comment]
Just found this blog https://medium.com/storybookjs/declarative-storybook-configuration-49912f77b78 which seems to articulate the future of storybook config. I realize I joined this party right when there were some major changes happening so I might need to adjust my config to this standard. To solve my problem here, perhaps manager.js is necessary as indicated in the link provided by shilman above.

**Comment by shilman** [comment]
@dvnrsn I think it's all or nothing. You can hide the entire panel or show it. You can't selectively hide tabs currently.

**Comment by dvnrsn** [comment]
Ah, ok.

What I learned is that one must include the addon in `main.js` addons AND sometimes include it in the story itself (eg `decorators: [withKnobs]`). It would be cool to have a way to only include tabs when desired, but this is not the current intention of addons.
