### ISSUE TITLE
[@storybook/theming] dark theming on test fail panel is incorrect

### ISSUE THREAD

**Issue by rwu823** [storybookjs/storybook#9858]
**Describe the bug**
official dark theming on test fail panel is incorrect.

**To Reproduce**
1. setup addon jest
2. write a fail spec
3. open the tests panel

**Expected behavior**
color contrast for best readability.

**Screenshots**
![image](https://user-images.githubusercontent.com/890063/74534330-7370f180-4f6e-11ea-9eeb-ef39da32d9ba.png)

**Code snippet**

~~~js
// .storybook/manager.js
import { addons } from '@storybook/addons'
import { themes } from '@storybook/theming'

addons.setConfig({
  theme: themes.dark,
})
~~~

~~~js
// .storybook/preview.js
import { addParameters, addDecorator } from '@storybook/react'
import { withTests } from '@storybook/addon-jest'

import results from './jest-test-results.json'

addDecorator(withTests({ results }))

addParameters({
  jest: ['spec.tsx'],
})
~~~

**Comment by shilman** [comment]
@rwu823 any interest in contributing a fix for this?

**Comment by rwu823** [comment]
@shilman  yeah I'll try.

**Comment by rwu823** [comment]
I tried the latest version `6.0.0-alpha.30` is worked fine. close it.


![image](https://user-images.githubusercontent.com/890063/78023938-1b5d4580-738a-11ea-8c98-c3d92d73445a.png)
