### ISSUE TITLE
[Angular 4] not able to start with setup

### ISSUE THREAD

**Issue by vvdwivedi** [storybookjs/storybook#9872]
**Describe the bug**
For Angular 4 app, `npx -p @storybook/cli@next sb init --type angular` gives this error ` Error: Could not find a default project in your Angular workspace. Add a project and re-run the installation.`

This happens with any project created from Angular CLI (I am using 1.4.3) without any changes or configs.

**To Reproduce**
1. Take any Angular 4 repo
2. Run `npx -p @storybook/cli@next sb init --type angular`
3. See error

**Expected behavior**
Initialize a new storybook with Angular 4

**System:**
Please paste the results of `npx -p @storybook/cli@next sb info` here.

```
Environment Info:

  System:
    OS: macOS 10.15.2
    CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
  Binaries:
    Node: 11.11.0 - ~/.nvm/versions/node/v11.11.0/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v11.11.0/bin/npm
  Browsers:
    Chrome: 79.0.3945.130
    Firefox: 67.0.4
    Safari: 13.0.4

```

**Comment by aboudard** [comment]
Hello,
Is it possible that you try to run a too recent version of storybook against an "old" version of angular project, since the config file was renamed in Angular 6 : from angular-cli.json to angular.json ?

https://nitayneeman.com/posts/understanding-the-angular-cli-workspace-file/

**Comment by vvdwivedi** [comment]
Yes, I used latest storybook with Angular 4. Is there a mapping or document which mentions which version of storybook would be compatible with Angular 4 and so on? That would be really helpful.

**Comment by HiCoke** [comment]
Hello, this is also the problem I have encountered at present angular.json  And. Angular- cli.json I can't continue. Is there a storybook version corresponding to angular4, or are there other solutions when angular4 is not upgraded to a higher version? Thank you for your reply
