### ISSUE TITLE
Migrate to leven which is more actively maintained

### ISSUE THREAD

**Issue by jamesgeorge007** [storybookjs/storybook#9878]
**Is your feature request related to a problem? Please describe.**
As of now [didyoumean.js](https://github.com/dcporter/didyoumean.js/) matching engine is used to suggest matching commands if the user mistypes. But it is not longer actively maintained.

**Describe the solution you'd like**
 Instead I would suggest switching over to [leven](https://github.com/sindresorhus/leven) which is the fastest JS implementation of the Levenshtein distance algorithm, `leven` returns the distance between 2 strings which can be made use of to find the exact match.

**Are you able to assist bring the feature to reality?**
For sure :+1:

**Additional context**
N/A

**Comment by shilman** [comment]
Ermahgerd!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-alpha.14 containing PR #9881 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.
