### ISSUE TITLE
Switching from Canvas to Docs doesn't render JavaScript components properly

### ISSUE THREAD

**Issue by bpeab** [storybookjs/storybook#9884]
**Describe the bug**
We have some components (ES6 or Vue) that must be initialized (we use `useEffect()` to do so) and that works perfectly on both the Canvas and the Docs tabs if the page is re-loaded. If we switch — from the Canvas tab — to the Docs tab, some components are not rendered properly. 

We are using the `html` preset.

**Expected behavior**
Components should be initialized properly when switching from the Canvas tab to the Docs tab.

**Code snippets**
An example of the component initialization:

```jsx
<Preview>
  <Story name="Default">
    {() => {
      useEffect(() => {
        new Styleguide.Vue({
          el: '#tabs-default',
        });
      });
      return `
        <div class="container">
          <tabs id="tabs-default" active-tab-id="description" v-cloak>
            <tab id="test1" label="Test1">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                eiusmod tempor incididunt ut labore et dolore magna aliqua. At
                volutpat diam ut venenatis tellus. Feugiat in ante metus dictum at
                tempor commodo ullamcorper. Id cursus metus aliquam eleifend mi
                in. Elit scelerisque mauris pellentesque pulvinar pellentesque
                habitant morbi tristique. Vestibulum lorem sed risus ultricies
                tristique.
            </tab>
            <tab id="test2" label="Test2">
                Ultricies leo integer malesuada nunc vel risus commodo viverra
                maecenas. Sit amet venenatis urna cursus eget nunc scelerisque.
                Curabitur vitae nunc sed velit dignissim sodales. Dui vivamus arcu
                felis bibendum ut tristique et. Nec sagittis aliquam malesuada
                bibendum arcu vitae. Donec et odio pellentesque diam volutpat.
                Elit duis tristique sollicitudin nibh sit.
            </tab>
            <tab id="test3" label="Test3">
                Auctor elit sed vulputate mi sit amet mauris commodo. In eu mi
                bibendum neque. Curabitur gravida arcu ac tortor dignissim
                convallis. Mauris in aliquam sem fringilla.
            </tab>
          </tabs>
        </div>
      `;
    }}
  </Story>
</Preview>
```

**Additional context**
Apparently, `useEffect()` is fired as expected and the components are initialized (a simple `console.log(component)` shows the constructed component) but for some reason, the DOM of the Docs iframes are not rendering properly.

Also, it happens every single time and always on the same components/stories. For exemple, we have 3 stories for one components, which are initialized with different configs, only the second one always renders correctly.

**Comment by shilman** [comment]
@bpeab Are your stories rendering in iframes or inline? If iframe, can you try configuring it to render inline and let me know if it's still a problem? 

Also, any chance you can add a repro to `vue-kitchen-sink` in the Storybook repo to make it easier to debug and fix? Thanks!
