### ISSUE TITLE
Generic 'union' shown in prop table instead of Union<X | Y> [CRA + TS]

### ISSUE THREAD

**Issue by taze-fullstack** [storybookjs/storybook#9896]
**Describe the bug**
Prop table shows generic `union` on props with declared union types. [This might be the intended behavior (?) so this might be a feature request instead of a bug]

**To Reproduce**
1. Setup CRA + TS
2. define a component prop with a union type

**Expected behavior**
Prop table should say something like `Union<X | Y>`

**Screenshots**
![image](https://user-images.githubusercontent.com/36070737/74713459-9a2b7280-5263-11ea-8387-29f4886ca2d6.png)

**Code snippets**
```
export interface HelloProps {
  title?: string | string[];
}

export const Hello = ({title}: HelloProps) => {
  return (
    <div className="hello">
      {typeof title === 'string'
        ? title
        : title?.map((line) => {
            return (
              <span key={line} style={{display: 'block'}}>
                {line}
              </span>
            );
          })}
    </div>
  );
};

Hello.defaultProps = {
  title: 'this is the default :)',
};

export default Hello;
```

**System:**
```
  System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 Intel(R) Core(TM) i3-4170 CPU @ 3.70GHz   
  Binaries:
    Node: 12.14.1 - C:\Program Files\nodejs\node.EXE       
    Yarn: 1.21.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
```

**Comment by shilman** [comment]
I'm overhauling the props rendering and will try to get this working

**Comment by bradennapier** [comment]
Any update with this?  Latest install - any types that use a union are rendered as `union` not the actual union values.

**Comment by derek-k-watson** [comment]
Having the same issue. It is pretty frustrating to work around. I'm having to put the union/options in the description, which makes for a cluttered and incosistent experience for the devs consuming our component library.

**Comment by bradennapier** [comment]
You can fix this but it takes a decent amount of work.  You basically need to add custom webpack config and add in the typescript info loader I forget exact name and not at computer right now

**Comment by bradennapier** [comment]
https://github.com/strothj/react-docgen-typescript-loader

I think that is it

**Comment by bradennapier** [comment]
https://github.com/hipstersmoothie/storybook-addon-react-docgen/issues/46

Never mind the info is here — even though this is a different add on - once I added the loader as I show in the issue the unions showed up for this add on as well

**Comment by RuneKR** [comment]
This is used for docgen now right? https://www.npmjs.com/package/babel-plugin-react-docgen-typescript

**Comment by hipstersmoothie** [comment]
@taze-fullstack @bradennapier @Rune-KR @derek-k-watson Has this issue persisted with storybook 6.0? The configuration for typescript docgen is a bit smarter now. If this issue has persisted could you post a reproduction repo?

**Comment by derek-k-watson** [comment]
Going to 6.0 fixed it for me!
    	
    	

    	Get Outlook for iOS
    
  




On Fri, Oct 23, 2020 at 1:38 PM -0500, "Andrew Lisowski" <notifications@github.com> wrote:















@taze-fullstack @bradennapier @Rune-KR @derek-k-watson Has this issue persisted with storybook 6.0? The configuration for typescript docgen is a bit smarter now. If this issue has persisted could you post a reproduction repo?

**Comment by hipstersmoothie** [comment]
Awesome! I'm going to close this issue. If the issue persists for the rest feel free to open another issue with a reproduction repo and tag me in it.
