### ISSUE TITLE
Link Child Components in Docs

### ISSUE THREAD

**Issue by Paratron** [storybookjs/storybook#9899]
While is is very pleasant to browse through a component library with storybook, I find it hard to signal relationships of components or how they build up on eachother.

It would be great if the docs addon could detect if components are imported that have stories themselves, then provide links to those components/stories in the docs section. Something along: 

This component utilizes `<ComponentA />` and `<ComponentB />`.

**Comment by shilman** [comment]
@Paratron there's an addon for this! https://medium.com/storybookjs/discover-dependencies-in-storybook-49264d361e21

**Comment by Paratron** [comment]
Oh my god, why didnt I see this? Okay, its not listed in the addons area of the website :)
