### ISSUE TITLE
build-storybook doesn't load sourcemaps

### ISSUE THREAD

**Issue by rey-wright** [storybookjs/storybook#9901]
**Describe the bug**
`build-storybook` seemingly doesn't either generate sourcemaps, or load sourcemaps (or both)

**To Reproduce**
1. Run `build-storybook`
2. Navigate to the built index.html file and open it in a browser (Chrome ideally)
3. Go to the "Sources" tab in Chrome
4. Cmd / Ctrl + P for your original file / component. You won't be able to find it.
5. Now run the local server and repeat all the above steps. You should easily be able to find it.

**Expected behavior**
I expect that, since the correct configuration is in place to render sourcemaps (`devtool: **'#cheap-module-source-map'**`) that it should render.

**Screenshots**
N/A

**Code snippets**
N/A

**System:**
```
Environment Info:

  System:
    OS: macOS Mojave 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 79.0.3945.130
    Firefox: 67.0.1
    Safari: 12.1.1
  npmPackages:
    @storybook/addon-a11y: ^5.3.3 => 5.3.3 
    @storybook/addon-actions: ^5.3.3 => 5.3.3 
    @storybook/addon-backgrounds: ^5.3.3 => 5.3.3 
    @storybook/addon-centered: ^5.3.3 => 5.3.3 
    @storybook/addon-docs: ^5.3.3 => 5.3.3 
    @storybook/addon-knobs: ^5.3.3 => 5.3.3 
    @storybook/addon-links: ^5.3.3 => 5.3.3 
    @storybook/addons: ^5.3.3 => 5.3.3 
    @storybook/react: ^5.3.3 => 5.3.3 
    @storybook/theming: ^5.3.3 => 5.3.3 
```

**Additional context**
N/A

**Comment by shilman** [comment]
cc @ndelangen

**Comment by DanielHoffmann** [comment]
I can confirm that the default settings are not working properly for sourcemaps, but changing the devtool in the `.storybook/webpack.config.js` to `'inline-source-map'` or `''source-map'` works

**Comment by shilman** [comment]
cc @ndelangen do you think we should change this setting per @DanielHoffmann 's comment?

**Comment by shilman** [comment]
Ooh-la-la!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-alpha.31 containing PR #10290 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

**Comment by ndelangen** [comment]
@shilman is there something for me to do here?

**Comment by totszwai** [comment]
@ndelangen lol please fix the sourcemaps? XD

**Comment by DanielHoffmann** [comment]
@totszwai you can set a custom devtool in storybook webpack configuration in `.storybook/main.js` like explained in this guide:
https://storybook.js.org/docs/react/configure/webpack

something like:

```
// .storybook/main.js
module.exports = {
  webpackFinal: async (config, { configType }) => {
    config.devtool = 'inline-source-map'
    return config;
  },
};

**Comment by Philzen** [comment]
@DanielHoffmann i was trying out adding `webpackFinal` to get around some "sourcemap not found" warning in a RedwoodJS project (which integrates v6.4.19) but as soon as i add it Storybook won't start anymore. Unsure if this is a redwood setup (which is why i filed it [here](https://github.com/redwoodjs/redwood/issues/4980) for now) or if anybody else has experienced this with storybook before.

**Comment by WodenWang820118** [comment]
Hi, I still bump into the same issue after using the suggested `webpackFinal` in the `main.js`.
Storybook version: `6.5.9`
Angular version: `13`

Here is my `main.js`
```
module.exports = {
  "stories": [
    "../src/**/*.stories.mdx",
    "../src/**/*.stories.@(js|jsx|ts|tsx)"
  ],
  "addons": [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/addon-interactions"
  ],
  "framework": "@storybook/angular",
  "core": {
    "builder": "@storybook/builder-webpack5"
  },
  "features": {
    "babelModeV7": true,
  },
  "webpackFinal": async (config, { configType }) => {
    config.devtool = 'source-map'
    return config;
  },
}
```

Thanks.
