### ISSUE TITLE
Storybook with docs addon does not load story pages

### ISSUE THREAD

**Issue by avkonst** [storybookjs/storybook#9905]
**Describe the bug**
I have got storybook with docs addon. All my stories are in mdx format. When storybook is loaded, it shows blank page:
![image](https://user-images.githubusercontent.com/3971413/74805370-bbfe2580-5347-11ea-9cc8-118a92cc8b19.png)

iframe is requested with id undefined, and preview says: "no preview"

This can be seen online at [https://hookstate.js.org/docs/](https://hookstate.js.org/docs/)

**To Reproduce**
1. Go to  [https://hookstate.js.org/docs/](https://hookstate.js.org/docs/)'
2. See blank page

An observation: when I click "Version Info" story, it is loaded. When I return back to the first story, it is loaded successfully after this.

**Expected behavior**
The page is loaded successfully first time: 
![image](https://user-images.githubusercontent.com/3971413/74805518-2b741500-5348-11ea-81e9-422e2110aaa7.png)

**Screenshots**
Above.

**Code snippets**
The source code for this story book is here: https://github.com/avkonst/hookstate/tree/master/hookstate.js.org/docs

**System:**
```
System:
    OS: Linux 4.15 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-2700K CPU @ 3.50GHz
  Binaries:
    Node: 10.19.0 - /usr/bin/node
    Yarn: 1.17.3 - ~/.npm-global/bin/yarn
    npm: 6.13.4 - /usr/bin/npm
  Browsers:
    Chrome: 80.0.3987.87
    Firefox: 73.0
  npmPackages:
    @storybook/addon-actions: ^5.3.12 => 5.3.12 
    @storybook/addon-docs: ^5.3.12 => 5.3.12 
    @storybook/addon-links: ^5.3.12 => 5.3.12 
    @storybook/addons: ^5.3.12 => 5.3.12 
    @storybook/preset-create-react-app: ^1.5.2 => 1.5.2 
    @storybook/react: ^5.3.12 => 5.3.12 
  npmGlobalPackages:
    @storybook/cli: 5.3.12
```

**Comment by shilman** [comment]
It's rendering your stories, which are empty. If you hit "t" on your keyboard it will show the toolbar and you can see more clearly what's going on. I'd suggest running in `--docs` mode.

**Comment by avkonst** [comment]
The stories are not empty, they are just not loaded. That is why the issue
was reported. But I do not care, you may close it as I moved to docusaurus
2 and it works perfectly.
