### ISSUE TITLE
Addon-docs: Vue - Grab event information from template

### ISSUE THREAD

**Issue by mwong7861** [storybookjs/storybook#9909]
**Is your feature request related to a problem? Please describe.**
Vue-docgen-api added support for events in the template in 4.7.0:
https://github.com/vue-styleguidist/vue-styleguidist/compare/v4.6.1...v4.7.0

**Describe the solution you'd like**
It would be nice to have events in template appear in the docs tab in storybook. example of event:
![image](https://user-images.githubusercontent.com/15059516/74880379-ef2cbe80-531f-11ea-81cc-9cdacdfd7b77.png)

**Describe alternatives you've considered**
One alternative solution is to push the event that is being emitted into a method and then document it there, but this can add a lot of unnecessary code if there are a lot of events.

**Comment by shilman** [comment]
@mwong7861 if you upgrade `vue-docgen-api` and `vue-docgen-loader` to the latest, does it show up in the `events` section of the prop table? i'd expect it to.

**Comment by mwong7861** [comment]
That solved it. I thought I tried that before posting, but didn't realize we were using storybook-addon-vue-info/loader... Thank you very much for the response!
