### ISSUE TITLE
material-ui useTheme not working with muiTheme

### ISSUE THREAD

**Issue by Moonachi** [storybookjs/storybook#9910]
- preview.js
![image](https://user-images.githubusercontent.com/46507959/74893196-26a67400-53cf-11ea-8455-ee8c1d365251.png)

- main.js
![image](https://user-images.githubusercontent.com/46507959/74893214-2f974580-53cf-11ea-9dcc-45b69be30eca.png)

- package.js
![image](https://user-images.githubusercontent.com/46507959/74893236-3c1b9e00-53cf-11ea-9106-6a5e90923526.png)

- using
![image](https://user-images.githubusercontent.com/46507959/74893258-489ff680-53cf-11ea-9930-bc4b99d1722d.png)

I used "const theme = useTheme();". I expected theme I made. But theme has a material ui theme.
I want to use my custom theme. Thanks.

![image](https://user-images.githubusercontent.com/46507959/74893665-42f6e080-53d0-11ea-939f-7d9fca1b7f99.png)

**Comment by shilman** [comment]
Shouldn't this be an issue on `storybook-addon-material-ui`?
