### ISSUE TITLE
Addon-docs: Props component should accept a sort function.

### ISSUE THREAD

**Issue by patricklafrance** [storybookjs/storybook#9917]
**Is your feature request related to a problem? Please describe.**
IMO for a user, this is easier to find a specific property in the props table if the props are sort. I believe this is still best to keep the declaration order by default but the component should allow a way to provide sorting.

**Describe the solution you'd like**
The `<Props />` component could accept a `sort` function, something similar to sort function for the nav.

Otherwise, maybe it could be a `string` prop accepting 2 values `asc` and `desc`.

Material UI props are sort ascending (https://material-ui.com/api/form-control/):

![image](https://user-images.githubusercontent.com/794579/74945011-01146d00-53c5-11ea-955a-4c388a3c5f5a.png)

Same thing with Semantic UI (https://react.semantic-ui.com/elements/button/):

![image](https://user-images.githubusercontent.com/794579/74945081-17222d80-53c5-11ea-9f9a-bc3c2a6ecbb8.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1199622255231368/1200021016063941) by [Unito](https://www.unito.io/learn-more)

**Comment by meyerds** [comment]
I'd like to see this option too. [This bug](https://github.com/storybookjs/storybook/issues/8539) is affecting me, but I'm in a Typescript codebase, so the bugfix on that issue didn't have any effect. A sort prop on the `Props` component seems like the best way to make everybody happy.

**Comment by mattcorner** [comment]
Would also like a sort function. Currently the input args to my first story seem to be overriding the order of the props, such that if props "C" and "D" are input to the first story, the props table order is "C", "D", "A", "B" even if they were defined alphabetically.

**Comment by Vadorequest** [comment]
Could the default be changed until this is done?

Basically, split all props in 2, those enabled and those disabled, and sort alphabetically each group, so that disabled props always appear at the bottom and not at the top (they currently appear at the top when we disable them on a component/story level).

**Comment by chadlavi-casebook** [comment]
Any updates on this or anyone know a sneaky workaround for TypeScript users?

It's maddening that the props are in a seemingly random order. For components that have dozens of props this ends up making it quite difficult to find the one you want.

**Comment by shilman** [comment]
There's an open PR for this and I'll try to get it merged before 6.2 is released

**Comment by shilman** [comment]
ZOMG!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.0-beta.15 containing PR #13125 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by pybuche** [comment]
@shilman Thanks for this awesome feature! I'm just wondering: it doesn't seem to work on the ArgsTable, only on the controls panels, am I right? Is there a way to make it work in the docs blocks?

**Comment by shaneajeffery** [comment]
Just in case someone reaches this PR and is confused on how to implement the solution that @shilman implemented, look at: https://github.com/storybookjs/storybook/pull/13125/files#diff-a44a21d62567f8d33a192d4c68af926444a466a18c8680d10ce10a3394ee6512R9

It is just an update to the story parameters for each story or you an add it as a global parameter like I did in the `preview.js`:

```js
export const parameters = {
  ...
  controls: { sort: 'requiredFirst' },
}
```

Documentation for global parameters: https://storybook.js.org/docs/react/writing-stories/parameters#global-parameters

**Comment by nicollecastrog** [comment]
First of all, thanks for your solution @shilman! 😍 `requiredFirst` is already SO much better than the seemingly random order the props were displaying in before.

However, I was wondering if you (or anyone else) knows of a way to set an actual sort _function_ for the props? I know you can do this for the order of the Stories themselves (`parameters.options.storySort`) and was hoping for a similar param for the order of the _props_ as I have an unusual use-case.

For context: my component is a superset of a MUI component, so it has LOADS of props, but I want to highlight certain important props at the top of my Docs ArgsTable, some of which are required, some of which are optional but that are nonetheless more important to know about than the other slew of 40+ props. So I want to implement a custom prop sorting function to achieve this.

Any help is appreciated 🙏

**Comment by IndProgo** [comment]
This change would help
https://github.com/storybookjs/storybook/blob/421b066d53746ec9b65eb7701b3d61d25d0730d4/code/ui/blocks/src/components/ArgsTable/ArgsTable.tsx#L288

```diff
-  const sortFn = sortFns[sort];
+  const sortFn = typeof sort === "function" ? sort : sortFns[sort];
```
Then in preview.js I can make my custom sort function, in addition to requiredFirst 
```js
const SORT_PROPTYPES_FUNC = (a, b) => Number(!!b.type?.required) - Number(!!a.type?.required)
    || Number(a.description.includes('custom')) - Number(b.description.includes('custom'))
    || a.name.localeCompare(b.name)

const parameters = {
    controls: {
        sort: SORT_PROPTYPES_FUNC,
    },
    docs: {
        controls: {
            sort: SORT_PROPTYPES_FUNC,
        },
    }
}
```

To temporarely modify source file, I put *pre-* script in packages.json which would update node_modules file before building storybook 

For example:
```
{
  "scripts: {
    "predev-storybook": "node _utils/node-replacer.js",
  }
}
```
**node-replacer.js**

```node
const fs = require('fs')
const { resolve } = require('path')
const nodemodulesfile = resolve(__dirname, '../node_modules/@storybook/blocks/dist/index.mjs')

fs.readFile(nodemodulesfile, 'utf8', function (err, data) {
    if (err) {
        return console.error(err);
    }

    // Allow custom sort function for ArgTables canvas and docs
    const result = data
        .replace('let sortFn=sortFns[sort],', 'let sortFn=typeof sort==="function"?sort:sortFns[sort],')

    if (result !== data) {
        fs.writeFile(nodemodulesfile, result, 'utf8', function (err) {
            if (err) return console.error(err);
        });
    }
});
```

**Comment by wesleymostien** [comment]
sorting controls in every component by setting it globally in `preview` file is not working for me:

```
const preview = {
  parameters: {
    controls: {
      sort: 'alpha',
    },
...

export default preview;
```

**Comment by PVUL** [comment]
@wesleymostien try
```js
const preview = {
  parameters: {
    docs:  {
      controls: {
        sort: 'alpha',
      },
...

export default preview;
```

**Comment by Shinigami92** [comment]
> This change would help
> 
> https://github.com/storybookjs/storybook/blob/421b066d53746ec9b65eb7701b3d61d25d0730d4/code/ui/blocks/src/components/ArgsTable/ArgsTable.tsx#L288
> 
> ```diff
> -  const sortFn = sortFns[sort];
> +  const sortFn = typeof sort === "function" ? sort : sortFns[sort];
> ```
> 
> Then in preview.js I can make my custom sort function, in addition to requiredFirst
> 
> ```js
> const SORT_PROPTYPES_FUNC = (a, b) => Number(!!b.type?.required) - Number(!!a.type?.required)
>     || Number(a.description.includes('custom')) - Number(b.description.includes('custom'))
>     || a.name.localeCompare(b.name)
> 
> const parameters = {
>     controls: {
>         sort: SORT_PROPTYPES_FUNC,
>     },
>     docs: {
>         controls: {
>             sort: SORT_PROPTYPES_FUNC,
>         },
>     }
> }
> ```
> 
> To temporarely modify source file, I put _pre-_ script in packages.json which would update node_modules file before building storybook
> 
> For example:
> 
> ```
> {
>   "scripts: {
>     "predev-storybook": "node _utils/node-replacer.js",
>   }
> }
> ```
> 
> **node-replacer.js**
> 
> ```js
> const fs = require('fs')
> const { resolve } = require('path')
> const nodemodulesfile = resolve(__dirname, '../node_modules/@storybook/blocks/dist/index.mjs')
> 
> fs.readFile(nodemodulesfile, 'utf8', function (err, data) {
>     if (err) {
>         return console.error(err);
>     }
> 
>     // Allow custom sort function for ArgTables canvas and docs
>     const result = data
>         .replace('let sortFn=sortFns[sort],', 'let sortFn=typeof sort==="function"?sort:sortFns[sort],')
> 
>     if (result !== data) {
>         fs.writeFile(nodemodulesfile, result, 'utf8', function (err) {
>             if (err) return console.error(err);
>         });
>     }
> });
> ```

The new location seems to be here: https://github.com/storybookjs/storybook/blob/a997fa100dac2efe648515c63c23c357378c120c/code/lib/blocks/src/components/ArgsTable/ArgsTable.tsx#L257

Could someone provide a PR?
