### ISSUE TITLE
Error when themeing mdx files with Vue components: undefined is not an object (evaluating 'element.options[VALUES]')

### ISSUE THREAD

**Issue by AJB99** [storybookjs/storybook#9920]
**Describe the bug**
When attempting to theme Storybook, and Docs (using mdx files) for a book of Vue components I'm getting the following error where the components should be displayed.

**To Reproduce**
Following this documentation for themeing that includes the Docs addon and mdx files:
https://github.com/storybookjs/storybook/blob/master/addons/docs/docs/theming.md

**Expected behavior**
The Vue components should display without error.

**Code**
_config/storybook/main.js_
```
module.exports = {
  stories : ['../../src/**/*.stories.(js|jsx|ts|tsx|mdx)'],
  addons : [
    '@storybook/addon-actions',
    '@storybook/addon-links',
    '@storybook/addon-backgrounds/register',
    '@storybook/addon-docs'
  ]
}
```

_config/storybook/preview.js_
```
import { addParameters } from '@storybook/react'
import { themes } from '@storybook/theming'

addParameters({
	options : {
		theme : themes.dark
	}
})
```

> **IMPORTANT NOTE:**
The components will display properly when the above code is placed in a `config/storybook/manager.js` file instead of a `config/storybook/preview.js` file. However, the themeing is not applied to the Docs (`mdx`) in that case.

_ui-button.stories.mdx_
```
import { Meta, Story, Preview } from '@storybook/addon-docs/blocks';
import uiButton from './ui-button.vue';

<Meta title="ui-button" component={ uiButton } />

# ui-button

With `MDX` we can define a story for `ui-button` right in the middle of our
markdown documentation.

<Preview>
	<Story name="ui-button primary">
		{{
			components : { uiButton },
			template : '<ui-button>Click Me</ui-button>',
		}}
	</Story>
</Preview>
```

**The Error**
```
undefined is not an object (evaluating 'element.options[VALUES]')
render@http://localhost:6006/vendors~main.4a4fb70d6395beff577f.bundle.js:22911:33
tryCatch@http://localhost:6006/vendors~main.4a4fb70d6395beff577f.bundle.js:170627:44
invoke@http://localhost:6006/vendors~main.4a4fb70d6395beff577f.bundle.js:170853:30
asyncGeneratorStep@http://localhost:6006/vendors~main.4a4fb70d6395beff577f.bundle.js:20131:103
_next@http://localhost:6006/vendors~main.4a4fb70d6395beff577f.bundle.js:20133:212
http://localhost:6006/vendors~main.4a4fb70d6395beff577f.bundle.js:20133:369
initializePromise@[native code]
Promise@[native code]
http://localhost:6006/vendors~main.4a4fb70d6395beff577f.bundle.js:20133:108
renderMain@http://localhost:6006/vendors~main.4a4fb70d6395beff577f.bundle.js:20436:16
renderUI@http://localhost:6006/vendors~main.4a4fb70d6395beff577f.bundle.js:20463:19
emit@http://localhost:6006/vendors~main.4a4fb70d6395beff577f.bundle.js:57556:37
http://localhost:6006/vendors~main.4a4fb70d6395beff577f.bundle.js:11767:20
```

**Screenshots**
<img width="1407" alt="Screen Shot 2020-02-20 at 4 24 44 PM" src="https://user-images.githubusercontent.com/6812084/74980215-122da000-53fe-11ea-848c-eff90547ab99.png">

<img width="1440" alt="Screen Shot 2020-02-20 at 4 40 09 PM" src="https://user-images.githubusercontent.com/6812084/74981142-b82dda00-53ff-11ea-8f1b-6061aea112a6.png">

**System**
```
$ npx -p @storybook/cli@next sb info

Environment Info:

  System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
  Binaries:
    Node: 12.13.1 - /usr/local/bin/node
    Yarn: 1.5.1 - /usr/local/bin/yarn
    npm: 6.12.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 80.0.3987.116
    Firefox: 71.0
    Safari: 13.0.5
  npmPackages:
    @storybook/addon-actions: >=5.3.0 => 5.3.13
    @storybook/addon-backgrounds: 5.3.13 => 5.3.13
    @storybook/addon-docs: 5.3.13 => 5.3.13
    @storybook/addon-knobs: >=5.3.0 => 5.3.13
    @storybook/addon-links: >=5.3.0 => 5.3.13
    @storybook/addon-notes: 5.3.13 => 5.3.13
    @storybook/react: 5.3.13 => 5.3.13
    @storybook/theming: 5.3.13 => 5.3.13
    @storybook/vue: >=5.3.0 => 5.3.13
```

**Comment by shilman** [comment]
@pocka @Aaron-Pool is this something either of you have encountered?

**Comment by pocka** [comment]
I've never seen that error before (I'm React user btw 😮 ) but it seems to be from [this line](https://github.com/storybookjs/storybook/blob/next/app/vue/src/client/preview/render.ts#L53). Probably a result of story functions missing `options` property somehow (caused by Docs addon stuff or incorrect usage of something? IDK).
A reproduction project would help better, anyway.

**Comment by AJB99** [comment]
@shilman @pocka @Aaron-Pool Thanks for the quick reply folks.

@pocka Seems to have found the origin-line of the error, but I'm not sure where it's expecting `element.options[VALUES]` to be coming from.

Is there any documentation on the how to use Vue comps within an mdx file by embedding them using the double-curly syntax.

e.g.
```
{{
	components : { uiButton },
	template : '<ui-button>Click Me</ui-button>',
}}
```

I'll try to find time to work up a repro repo later today.

**Comment by pocka** [comment]
@AJB99 `element.options[VALUES]` is added at story execution time by Storybook core. So you don't need to care about it at writing stories 👍 

> Is there any documentation on the how to use Vue comps within an mdx file by embedding them using the double-curly syntax.

I think [this](https://github.com/storybookjs/storybook/tree/next/addons/docs/vue#mdx) is the only documentation about it and your code is totally ok.

**Comment by Aaron-Pool** [comment]
@shilman this is actually ringing a bell. Didn't we create an issue in the vue-docgen-api at some point where sometimes the doc object was attached to an `options` field on the component, and other times it was attached to the component itself?

**Comment by shilman** [comment]
@Aaron-Pool great memory. it was this one: https://github.com/pocka/vue-docgen-loader/issues/7

@AJB99 do you have a repro we can look at?
