### ISSUE TITLE
addon-docs: Props table does not include `children` prop from TypeScript type.

### ISSUE THREAD

**Issue by etlovett** [storybookjs/storybook#9921]
**Describe the bug**
When using addon-docs with Storybook, the props table does not include the `children` prop, despite it being an explicit part of the TypeScript type.

I'm using `react-docgen-typescript-loader@^3.6.0`, as recommended by https://storybook.js.org/docs/configurations/typescript-config/#setting-up-typescript-with-ts-loader and https://github.com/storybookjs/storybook/tree/master/addons/docs#typescript-configuration.  `3.6.0` is the latest version of this dependency.

**To Reproduce**
1. Clone https://github.com/etlovett/storybook-bug-repros/tree/children-omitted.
    1. As you can see from the commit history, this repo/branch is create-react-app in TypeScript, plus Storybook in TypeScript, plus addon-docs, with a local copy of [the demo button](https://github.com/storybookjs/storybook/blob/next/app/react/src/demo/Button.tsx) that has an explicit `children: ReactNode` prop.
2. Run `yarn storybook`
3. Go to the Button page
4. See that the props table only lists the `onClick` prop.

**Expected behavior**
I would expect the `children` prop to appear in the props table because it's part of the component's `Props` type.  With `children` omitted, it's not clear to Storybook Docs consumers whether or not a component takes children.

**Screenshots**
<img width="1021" alt="Screen Shot 2020-02-20 at 5 05 33 PM" src="https://user-images.githubusercontent.com/537241/74994556-3f308180-5403-11ea-9bfa-bb3bc08b6c9f.png">

**Code snippets**
The `Props` type I'm using is below. This is the base `Props` type from https://github.com/storybookjs/storybook/blob/next/app/react/src/demo/Button.tsx with the addition of an explicit item for `children`.
```ts
type Props = {
  children: ReactNode
} & Pick<HTMLAttributes<HTMLButtonElement>, 'onClick'>;
```

Note that if I drop the `& Pick<...>`, I get an empty props table ("No props found for this component"), so it's not related to the fact that I'm using an intersection.

**System:**
```
Environment Info:

  System:
    OS: macOS 10.15.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 13.7.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  Browsers:
    Safari: 13.0.5
  npmPackages:
    @storybook/addon-actions: ^5.3.13 => 5.3.13
    @storybook/addon-docs: ^5.3.13 => 5.3.13
    @storybook/addon-links: ^5.3.13 => 5.3.13
    @storybook/addons: ^5.3.13 => 5.3.13
    @storybook/preset-create-react-app: ^1.5.2 => 1.5.2
    @storybook/react: ^5.3.13 => 5.3.13
```

Thanks for building a great tool!

**Comment by shilman** [comment]
@etlovett thanks for the bug report! any chance you can submit a repro for this, following the template of https://github.com/storybookjs/storybook/pull/9924

haven't yet figured out the workflow to file this in the react-docgen repo, but once i do, i'll file all of the outstanding issues there!

**Comment by jeffreymeng** [comment]
I have this problem too (also using `react-docgen-typescript-loader`). For me, the prop and descriptions show fine, but the type is `any`.

#### Output
<img width="1064" alt="2020-03-06_18-28-45" src="https://user-images.githubusercontent.com/15185258/76135065-76448c80-5fd8-11ea-8249-74728bae4b92.png">

#### Prop Types
```typescript
interface LayoutProps {
  /**
   * The content of the page. It will be wrapped in a contianer.
   */
  children: React.ReactNode
...
}
```

**Comment by shilman** [comment]
can you try the recommended 6.0 setup (should work in 5.3 too) and let me know if that helps?

https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#react-prop-tables-with-typescript

**Comment by jeffreymeng** [comment]
@shilman I upgraded to babel-plugin-react-docgen, and it now says no props found for every single component.
Here's where I include the plugin:
```javascript
config.module.rules.push({
    test: /\.(ts|tsx)$/,
    use: [
      {
        loader: require.resolve("babel-loader"),
        options: {
          presets: [["react-app", { flow: false, typescript: true }]],
          plugins:["babel-plugin-react-docgen"]
        },
      },
    ],
  })
```

**Comment by shilman** [comment]
@jeffreymeng can you try `require.resolve('babel-plugin-react-docgen')`?

here's how it's configured for JS files: https://github.com/storybookjs/storybook/blob/next/app/react/src/server/framework-preset-react-docgen.ts

Or if you're using CRA, you should be able to get it all "for free" in `@storybook/preset-create-react-app`.

**Comment by jeffreymeng** [comment]
@shilman Is this what you mean by using require.resolve?
When I try that, there are no errors, however it says `No props found for this component` in storybook.
```javascript
config.module.rules.push({
    test: /\.(ts|tsx)$/,
    use: [
      {
        loader: require.resolve("babel-loader"),
        options: {
          presets: [["react-app", { flow: false, typescript: true }]],
          plugins:[
            [
              require.resolve('babel-plugin-react-docgen'),
              {
                DOC_GEN_COLLECTION_NAME: 'STORYBOOK_REACT_CLASSES',
              },
            ],
          ]
        },
      },
      // require.resolve("react-docgen-typescript-loader"),
    ],
  })
```

**Comment by shilman** [comment]
@jeffreymeng yeah that's what i meant. can you share a repro?

**Comment by nicholasbraun-de** [comment]
I'm having the same issue when following @shilman 's gist: https://gist.github.com/shilman/bc9cbedb2a7efb5ec6710337cbd20c0c

package.json:
```
{
  "name": "client",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.3.2",
    "@testing-library/user-event": "^7.1.2",
    "@types/jest": "^24.0.0",
    "@types/node": "^12.0.0",
    "@types/react": "^16.9.0",
    "@types/react-dom": "^16.9.0",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-scripts": "3.4.1",
    "typescript": "~3.7.2"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "storybook": "start-storybook -p 9009 -s public",
    "build-storybook": "build-storybook -s public"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "@storybook/addon-actions": "^5.3.19",
    "@storybook/addon-docs": "^5.3.19",
    "@storybook/addon-links": "^5.3.19",
    "@storybook/addons": "^5.3.19",
    "@storybook/preset-create-react-app": "^3.1.3",
    "@storybook/react": "^5.3.19",
    "babel-plugin-react-docgen": "^4.1.0"
  }
}
```

**Comment by nicholasbraun-de** [comment]
It works however, when I give the `children` prop a comment:

```
import React, { FC, ReactNode } from 'react';

interface ButtonProps {
  /**
   * children prop
   */
  children: ReactNode;
  onClick?: () => void;
}

/**
 * The world's most _basic_ button
 */
const Button: FC<ButtonProps> = ({ children, onClick }: ButtonProps) => (
  <button onClick={onClick} type="button">
    {children}
  </button>
);

export default Button;
```
