### ISSUE TITLE
@storybook/addon-docs props table with flow

### ISSUE THREAD

**Issue by zazagag** [storybookjs/storybook#9926]
**Is your feature request related to a problem? Please describe.**
Hi! First of all many thanks for great tool! 
I am using custom `webpack.config.js`, and `flow` types, and trying to get *addon-docs* to show *props table*, but it only show empty *props table*("No props found for this component").
As I understand through related issues - it is possible, but I didn't find any working solution, or documentation/example for properly configuration. 
 Can someone clarify workaround to make it work? 
In my case *props table* appears only if component has `defaultProps` (means came not from `flow` typed) and also no one prop has description.

**Describe the solution you'd like**
Complete documentation for using *addon-docs* with `flow` types.

**Additional context**
Repo to reproduce:
[https://github.com/zazagag/storybook-flow-example](https://github.com/zazagag/storybook-flow-example)

**Comment by VladimirPittner** [comment]
Hi, 
you seem to be missing `babel-plugin-react-docgen`, maybe thats causing problems.

It seem to be requirement for that plugin you are using: https://github.com/vertexbz/storybook-addon-react-flow-docgen

**Comment by zazagag** [comment]
Thank for reply, but unfortunately that has no effect. Moreover `storybook-addon-react-flow-docgen` has `babel-plugin-react-docgen` in `peerDependencies` so it is not necessary to add it directly.
