### ISSUE TITLE
Order of execution

### ISSUE THREAD

**Issue by Moonachi** [storybookjs/storybook#9936]
I tried to use useContext, but it didn't work, so I took a picture of the console and got a strange result.

I use a CSF style storybook.

I think main.js, preview.js will be executing and stories will be executing . Is this not it?

If you look at the picture below, Console is printed first in the stories and then in the preview.

![image](https://user-images.githubusercontent.com/46507959/75137311-9fd4fc80-572a-11ea-8ce5-dc18552aa32f.png)

Thanks

**Comment by kenwardt** [comment]
Are you using global decorators and invoking children as a function? I had this same problem using a provider from Material-UI and solved it from this [change](https://github.com/storybookjs/storybook/issues/8531#issuecomment-568947201).

```
// Using StoryFn as component instead of invoking it
addDecorator((StoryFn) => (
  <ContextProvider>
    <StoryFn />
  </ContextProvider>
));
```

**Comment by Moonachi** [comment]
@kenwardt Thanks!!!!
