### ISSUE TITLE
IE11 - Error on loading of Storybook 

### ISSUE THREAD

**Issue by lmaze** [storybookjs/storybook#9938]
**Describe the bug**
The interface loads well on Internet Explorer 11 but not the canvas of a story.
There are errors in the browser console and an error is displayed directly in Storybook instead of the content of the story.

**To Reproduce**
1. Launch the last alpha of Storybook (v6.0.0-alpha.18)
2. Open it with IE11

**Expected behavior**
Storybook should be working correctly on Internet Explorer 11.

**Screenshots**
![image](https://user-images.githubusercontent.com/11060691/75145251-e01b8700-56f8-11ea-942b-c83153430e5c.png)

**Code snippets**
The error occurs with the code `document.body.style = styles;` of the function `applyLayout` (file `storybook/lib/core/src/client/preview/start.js`).

IE11 does not support defining styles directly from the `style` property.

**System:**
  System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  Binaries:
    Node: 12.14.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    IE 11.657.18362.0 - MAJ 11.0.175

**Comment by lmaze** [comment]
Replace code with `document.body.setAttribute('style', styles);` seems to work. I can test and make the PR ;)

**Comment by shilman** [comment]
@lmaze yes please! 🙏

**Comment by shilman** [comment]
Crikey!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-alpha.28 containing PR #9942 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

**Comment by shilman** [comment]
Ta-da!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-alpha.35 containing PR #10377 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.
