### ISSUE TITLE
Rename Storyshots "storyKindRegex" to "storyTitleRegex"

### ISSUE THREAD

**Issue by gsklee** [storybookjs/storybook#9944]
The "kind" terminology is probably an obsolete usage and doesn't really align with other parts of the docs glossary nowadays.

**Comment by shilman** [comment]
Maybe `componentTitleRegex`? Now would be a good time to make a change since we're on a breaking release. We can deprecate the old property and alias it to whatever new name we come up with. cc @ndelangen @tmeasday

**Comment by tmeasday** [comment]
Sure, works for me.

**Comment by shilman** [comment]
@gsklee would you be able to create a PR with `componentTitleRegex` rename and an entry in `MIGRATION.md`?
