### ISSUE TITLE
Question: CRA + Storyshots multiSnapshotWithOptions

### ISSUE THREAD

**Issue by gsklee** [storybookjs/storybook#9946]
I am trying to follow the instructions on enabling [multiSnapshotWithOptions](https://github.com/storybookjs/storybook/tree/master/addons/storyshots/storyshots-core#multisnapshotwithoptionsoptions) for a CRA based project but couldn't figure out how to do it since CRA doesn't allow for a customized `jest.config.js`. Also a bit lost regarding the meaning of the `integrityOptions` config. Would be great if the docs could include more explanations on these.

**Comment by mrmckeb** [comment]
Hi @gsklee, good question - CRA provides Jest config through `package.json`. Does that work for you?

If not, let me know and we'll try to sort this out.

**Comment by gsklee** [comment]
@mrmckeb unfortunately nope.

**Comment by mrmckeb** [comment]
OK, thanks @gsklee. Did you want to take a look at this issue, try to raise a PR?

If not, I could take a look this weekend.

**Comment by gsklee** [comment]
@mrmckeb Sorry but no idea where to look at for the cause of the bug

**Comment by techieshark** [comment]
Same question - as a CRA user I get a warning like this when I run `react-scripts test`:

```
  console.warn node_modules/@storybook/addon-console/dist/index.js:121
    Storybook was unable to detect filename for stories of kind "Button".
    To fix it, add following to your jest.config.js:
        transform: {
          // should be above any other js transform like babel-jest
          '^.+\\.stories\\.js$': '@storybook/addon-storyshots/injectFileName',
        }
```

I've tried adding the `transform` config to both package.json (under the "jest" field) as well as `jest.config.js`, with no luck.

**Comment by reanimatter** [comment]
I'm seeing the same warning that `Storybook was unable to detect filename`. Interestingly,

```
import initStoryshots, { multiSnapshotWithOptions } from '@storybook/addon-storyshots';

initStoryshots({
  integrityOptions: { cwd: __dirname },
  test: multiSnapshotWithOptions({})
});
```

generates a single snapshot combining all stories in the app, which pretty much ignores `multiSnapshotWithOptions`.
