### ISSUE TITLE
Change react to a peer dependency for a11y-addon

### ISSUE THREAD

**Issue by jmakGH** [storybookjs/storybook#9953]
**Is your feature request related to a problem? Please describe.**
The `a11y-addon` has `react` as a normal dependency at `^16.8.3` which leads to incompatibility issues for us as a consumer since we're using a pinned version of `react@16.9.0`. This is due to Storybook bundling the latest minor version of react, which is `16.12`, resulting in there being two versions of React being used within the same tree which causes the following error to be thrown:

![image (1)](https://user-images.githubusercontent.com/3829337/75282235-b472cc80-57de-11ea-8926-51faa3c1bad4.png)
 

**Describe the solution you'd like**
Is it possible to change `react` to being a `peerDependency: *` such as how the centered or knobs addons specify it? This keeps inline with the premise that Storybook/react functions independent of whatever version of React a consumer is using.

**Describe alternatives you've considered**
At this point, we can only drop the addon or implement our own version.

**Are you able to assist bring the feature to reality?**
Yes I can

**Comment by shilman** [comment]
@jmakGH sounds totally reasonable. PR welcome!

**Comment by jmakGH** [comment]
Thank you, PR submitted!

**Comment by jmakGH** [comment]
Resolved by #9957

**Comment by shilman** [comment]
ZOMG!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-alpha.28 containing PR #9957 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.
