### ISSUE TITLE
Storyshots snapshot generation for every knobs composition

### ISSUE THREAD

**Issue by stereodenis** [storybookjs/storybook#9962]
**Is your feature request related to a problem? Please describe.**
Now storyshots doesn't generate snapshots for every knobs composition.

**Describe the solution you'd like**
Generate snapshots for every knobs composition

**Describe alternatives you've considered**

**Are you able to assist bring the feature to reality?**
no

**Comment by stereodenis** [comment]
@shilman add `knobs` label please

**Comment by stereodenis** [comment]
this is not stale

**Comment by shilman** [comment]
@stereodenis do you want to pick this up?

**Comment by stereodenis** [comment]
@shilman could you give me a direction?

**Comment by shilman** [comment]
@stereodenis Yeah I'd be happy to. Want to jump on our Discord https://discord.gg/UUt2PJb

I'm pretty booked up for the next month or so until 6.0 is out, but I'd love to see this get into SB 6.1.

**Comment by osdiab** [comment]
I too am interested in this!

**Comment by osdiab** [comment]
I would assume that some knobs would be easy to exhaustively step through (finite ones like radios and selects), but some knobs are not so straightforward (unbounded ranges); and that the number of combinations would explode in numbers if you have a lot of knobs, however. Not sure good ways to resolve those

**Comment by stereodenis** [comment]
@osdiab 5 knobs with 5 settings generate 120 combinations

**Comment by osdiab** [comment]
Huh? It would be 5^5 permutations no? Which is far more than 120

**Comment by stereodenis** [comment]
not stale. waiting for v6

**Comment by shilman** [comment]
Hi gang, We’ve just released addon-controls in 6.0-beta!

Controls are portable, auto-generated knobs that are intended to replace addon-knobs long term.

- [Controls README](https://github.com/storybookjs/storybook/tree/next/addons/controls)
- [Migration instructions](https://github.com/storybookjs/storybook/blob/next/addons/controls/README.md#how-do-i-migrate-from-addon-knobs)

Please upgrade and try them out today. Thanks for your help and support getting this stable for release!

**Comment by stereodenis** [comment]
@shilman what about React Native?

**Comment by shilman** [comment]
For anybody who is interested in Controls but don't know where to start, I've created a quick & dirty step-by-step walkthrough to go from a fresh CRA project to a working demo. Check it out:

=> [Storybook Controls w/ CRA & TypeScript](https://gist.github.com/shilman/69c1dd41a466bae137cc88bd2c6ef487)

There are also some "knobs to controls" migration docs in the Controls README:

=> [How do I migrate from addon-knobs?](https://github.com/storybookjs/storybook/blob/next/addons/controls/README.md#how-do-i-migrate-from-addon-knobs)

**Comment by shilman** [comment]
@stereodenis Storybook for RN is still catching up with Component Story Format (CSF). It might adopt controls someday, but no direct path from here to there until it supports CSF.

**Comment by chrisj-skinner** [comment]
@shilman I've been using controls with the latest V9 of Angular lately and having good progress 👍  Nice one on the CRA project.

**Comment by ZDerekh** [comment]
Isn't this feature must have to get proper coverage of the components? Correct me if I'm wrong, but this would give so much value either based on knobs or brand new controls. It's been so many threads already on this topic, and no one was resulting in a submitted PR or a draft.

**Comment by ybrodsky** [comment]
Any update on this? 
Any way to do it?

If you have 10 stories and you manage to reduce it to just 1 by using knobs (or controls, whatever) you will see a coverage decresed. So you are forced to have 10x more code just to avoid losing coverage.

**Comment by shilman** [comment]
@ybrodsky rough proposal here https://docs.google.com/document/d/1MF1QZdMvJ-0mMxCuFXxgthkig5AZp2L6f4VGNIu03zc/edit?usp=sharing

**Comment by jorisw** [comment]
Just to chime in, I don't think we're looking for Storybook Combos per se.

We're looking for StoryShorts to cover boolean and enum Control options.

This would automate 10x the coverage on the components, without having a Combo story, which is a feature with a different target audience.

**Comment by ndelangen** [comment]
The future of storyshots is the test-runner:
https://storybook.js.org/docs/react/writing-tests/test-runner#page-top

And use the play function for expectations:
https://storybook.js.org/docs/react/writing-stories/play-function#page-top

We will not be making any improvement / changes to storyshots.
