### ISSUE TITLE
linkTo seems to expect the humanized story name

### ISSUE THREAD

**Issue by skrivanos** [storybookjs/storybook#9963]
**Describe the bug**

It seems like `linkTo` expects the humanized story name as the second parameter, rather than what the function is called. I.e. giving it "withEmoji" fails and "With Emoji" succeeds. This does not align with the docs where it looks like you should use the same name as the function itself.

**To Reproduce**
1. Use snippet below
2. Click on the button
3. No navigation.

**Expected behavior**
Navigate to the withEmoji story.

**Code snippets**

Does not work:
```
import React from 'react';
import { linkTo } from '@storybook/addon-links';
import Button from '../Button';

export default { title: 'Button' };

export const withText = () => (
  <Button onClick={linkTo('Button', 'withEmoji')}>Change To Emojis</Button>
);

export const withEmoji = () => (
  <Button>
    <span role="img" aria-label="so cool">
      😀 😎 👍 💯
    </span>
  </Button>
);
```

Works:
```
import React from 'react';
import { linkTo } from '@storybook/addon-links';
import Button from '../Button';

export default { title: 'Button' };

export const withText = () => (
  <Button onClick={linkTo('Button', 'With Emoji')}>Change To Emojis</Button>
);

export const withEmoji = () => (
  <Button>
    <span role="img" aria-label="so cool">
      😀 😎 👍 💯
    </span>
  </Button>
);
```

**System:**
````
Environment Info:

  System:
    OS: macOS 10.15.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
  Binaries:
    Node: 10.16.3 - /usr/local/opt/node@10/bin/node
    Yarn: 1.19.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/opt/node@10/bin/npm
  Browsers:
    Chrome: 80.0.3987.122
    Firefox: 72.0.2
    Safari: 13.0.3
  npmPackages:
    @storybook/addon-actions: ^5.3.14 => 5.3.14
    @storybook/addon-links: ^5.3.14 => 5.3.14
    @storybook/react: ^5.3.14 => 5.3.14**Additional context**

**Comment by garystephens** [comment]
I just hit the same issue, took a while to work out the solution. The docs say:

> Second (optional) parameter is the story name (what you named with `exported name`). 

which doesn't seem to tally with the implementation. Plus `exported name` is tagged as code, but that's not valid code, is it?

**Comment by skrivanos** [comment]
As far as I know the bug is still there.

**Comment by garystephens** [comment]
At the very least, the documentation should be updated as it doesn't tally with the implemenation.

**Comment by mikestopcontinues** [comment]
I would defintely consider this a bug. When looking at the story file, I see the names prior to humanization, so I should be able to use them the same. It seems the addon should humanize whatever is passed to it before creating the anchor slug from the result.

Here's another example of what doesn't currently work:
```js
export default {
  title: 'common/Example',
  component: Example,
};

export const Default = () => (
  <Example>
    <LinkTo story="LinkedTo">Link</LinkTo>
  </Example>
);

export const LinkedTo = () => (
  <Example>You have arrived.</Example>
);
```

**Comment by mikestopcontinues** [comment]
This is still an issue.

**Comment by mikestopcontinues** [comment]
Still an issue.
