### ISSUE TITLE
Outdated information on README (addons)

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#9973]
**Describe the bug**
When checking the README of this repo, under the addons section, there are links pointing to pages that don't exist anymore.

**To Reproduce**
Check the links from README:
notes: https://github.com/storybookjs/storybook/blob/next/addons/notes
info: https://github.com/storybookjs/storybook/blob/next/addons/info

**Expected behavior**
Documentation should be up to date

**Additional context**
From what I understand, both addons *notes* and *info* are deprecated in favor of using [docs](https://github.com/storybookjs/storybook/tree/next/addons/docs). I guess they still are supported, so if that's the case there has to be a link to them somewhere as well.

I also see that both the addons section on README and the [addons support table ](https://github.com/storybookjs/storybook/blob/next/ADDONS_SUPPORT.md) are not up to date, they're missing: [essentials](https://github.com/storybookjs/storybook/tree/next/addons/essentials), [docs](https://github.com/storybookjs/storybook/tree/next/addons/docs) and [queryparams](https://github.com/storybookjs/storybook/tree/next/addons/queryparams).

I would like to contribute to this and make those sections clear, if possible! But I would need a small guide on what's the correct info to present :)

**Comment by ckbedwell** [comment]
I've had exactly the same issue today. I'm new to Storybook and the out of date documentation is very confusing. I don't have any past experience to know what the latest and recommended packages are, so I'm just going through trial and error and trying to work it out via the latest commits.

**Comment by shilman** [comment]
Hey @yannbf thanks for volunteering to help here! Storybook is a large and rapidly moving project and we definitely need to get better on the documentation front.

Based on your description above:
- [ ] `Notes` and `Info` should be removed from the documentation, and replaced with Docs examples. I'd be happy to answer questions here.
- [ ] `Docs` and `Queryparams` should be added to the addons support table.
- [ ] `Essentials` is still work in progress, so let's come back to that later.

**Comment by yannbf** [comment]
Thanks for the quick reply @shilman ! Regarding `Notes` and `Info` addons, shouldn't there be some information for whoever is still using them? 
Maybe some guides like: If you're using those, please consider moving to `Docs` instead, pointing to that [blogpost](https://medium.com/storybookjs/storybook-docspage-e185bc3622bf) of yours?

**Comment by shilman** [comment]
Good point @yannbf. I've been posting transition information on every info/notes-related issue for the past year, but it would also be great to add that to the README.

There's some migration instructions here (that can probably also be improved): https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/recipes.md#migrating-from-notesinfo-addons

**Comment by apsychogirl** [comment]
Hi, Can I help in improving the documentation?

**Comment by yannbf** [comment]
@shilman thanks for the info. I believe the migration instructions could indeed be improved, also showing how to move away from the previous addon if possible.

Regarding the addons table, I'm wondering what is the best way to display information. Would it be best to:
1 - remove deprecated addons from the tables
2 - keep deprecated addons but without a link, and a text saying it's deprecated
3 - have a separate section for deprecated addons which might link to migration info or something else

Also, does docs have Rax support?

**Comment by shilman** [comment]
Yeah, docs should work with every framework except react native! 😄 

Re: addons table, I like option 3. We'll be deprecating more addons in the future and it would be awesome to have a nice setup for this. Thanks so much for driving this!

**Comment by yannbf** [comment]
this was fixed on #10045
