### ISSUE TITLE
Exporting stories from MDX files for reuse in other files

### ISSUE THREAD

**Issue by renet** [storybookjs/storybook#9978]
I'm pretty new to Storybook, but for what I know, it's possible to export stories in `*.stories.tsx` for reuse in other story files, tests or whatever, for example like this:

```js
// Button.stories.tsx

// ...

export const DefaultButton = ({ method = action("clicked") }): JSX.Element => (
  <Button onClick={method}>Hello Button</Button>
);
```

In my case, I then reuse the export for unit testing with jest:

```js
// Button.test.tsx

// ...
import { DefaultButton } from "./Button.stories";

test("story", () => {
  const stub = jest.fn();
  const { getByText } = render(<DefaultButton method={stub} />);
  userEvent.click(getByText("Hello Button"));
  expect(stub).toHaveBeenCalled();
});
```

But my question is about `*.stories.mdx` files: Is there a way to export/import stories from MDX files to reuse them in other files? I didn't find any issues dealing with that exact usecase. If not, that'd probably be a feature request. :)

**Comment by shilman** [comment]
@renet Actually it's already possible, just not especially documented. MDX is compiled to CSF under the hood, so it's importable by the export key, which is basically the camel-cased version of the name:

https://github.com/storybookjs/storybook/blob/master/addons/docs/src/mdx/mdx-compiler-plugin.js#L23-L33

So if you define:

```js
// foo.stories.mdx
<Story name="Foo Bar">...</Story>
```

Then the following should work:

```
// baz.js
import { fooBar } from './foo.stories.mdx';
...
```

**Comment by shilman** [comment]
Closing this. Please lmk if you have any more questions.

**Comment by nfabacus** [comment]
Hi, @shilman 
I tried as you mentioned above https://github.com/storybookjs/storybook/issues/9978#issuecomment-592250751
However, I am getting an error `TS2307: Cannot find module './index.stories.mdx' or its corresponding type declarations.`
It is not letting me import anything from mdx file...

Any pointer to resolve this issue?  Thank you

**Comment by shilman** [comment]
@nfabacus If you're trying to import it into typescript you need to declare the module. I'm on my phone and don't have an example handy but hopefully it's easy to google

**Comment by nfabacus** [comment]
Hi, @shilman Thank you very much for your reply.
I added `mdx.d.ts` in the same component folder as the `index.stories.mdx` and `index.test.tsx`.
mdx.d.ts
```ts
declare module '*.mdx' {
  let MDXComponent: (props) => JSX.Element;
  export default MDXComponent;
}
```
Now the error disappeared but another error came up in the import line:
`import { DefaultButton } from './index.stories.mdx';`

`TS2614: Module '"*.mdx"' has no exported member 'DefaultButton'. Did you mean to use 'import DefaultButton from "*.mdx"' instead?`

Does the mdx file automatically export stories or do I need to do something to export each story?

**Comment by shilman** [comment]
I would just declare the module and not its contents. You won't get type checking for that part of your code but it will be far less annoying than having to type it

**Comment by nfabacus** [comment]
HI, @shilman Sorry I am not too familiar with typescript declaration files.  I just followed the mdx doc and copy pasted it.. so, not sure what I am doing exactly.  All I would like to do is just import individual stories from my .mdx file if possible, so that I can reuse them in my jest unit testing.  Thank you for your help.

**Comment by shilman** [comment]
```
declare module '*.mdx';
```

**Comment by nfabacus** [comment]
Hi, @shilman Thank you for your reply.  I tried that, but I get another error below in my test:
```
TypeError: Cannot destructure property 'instrument' of 'undefined' as it is undefined.

      3 | import { render, screen } from '@testing-library/react';
      4 |
    > 5 | import { DefaultButton } from './index.stories.mdx';
        | ^

```
I  tried to import differently as below as well, but I get the same error.
```
import * as stories from './index.stories.mdx';
const { DefaultButton } = stories;
```
Any idea?

**Comment by shilman** [comment]
@yannbf @ghengeveld does this look familiar?

> TypeError: Cannot destructure property 'instrument' of 'undefined' as it is undefined.

**Comment by yannbf** [comment]
> @yannbf @ghengeveld does this look familiar?
> 
> > TypeError: Cannot destructure property 'instrument' of 'undefined' as it is undefined.

Yes, [I saw a storyshots issue](https://github.com/storybookjs/storybook/issues/15916) that mentioned the same problem. Seems to be related to the new `process` API in Jest 27. I wonder if that is related somehow. Can you give a bit more info of your setup @nfabacus ?

**Comment by nfabacus** [comment]
Hi, @yannbf thank you for your comment.
Here is the repo I am building https://github.com/nfabacus/quarks/tree/jest-downgrade
working branch: main branch (button component, without the import from mdx).
jest-downgrade branch: I downgraded to jest 26, but still the similar error, it cannot find the imported Button component.

**Comment by yannbf** [comment]
> Hi, @yannbf thank you for your comment.
> Here is the repo I am building https://github.com/nfabacus/quarks/tree/jest-downgrade
> working branch: main branch (button component, without the import from mdx).
> jest-downgrade branch: I downgraded to jest 26, but still the similar error, it cannot find the imported Button component.

Thank you so so much for the repro! I'll take a look once I can next week and get back to you

**Comment by yannbf** [comment]
> Hi, @yannbf thank you for your comment. Here is the repo I am building https://github.com/nfabacus/quarks/tree/jest-downgrade working branch: main branch (button component, without the import from mdx). jest-downgrade branch: I downgraded to jest 26, but still the similar error, it cannot find the imported Button component.

Alright, after testing it out I noticed that things work correctly, it's just a typo in your code. Currently, the stories are exported in lowercase:
```diff
-import { DefaultButton } from './index.stories.mdx';
+import { defaultButton } from './index.stories.mdx';
```

**Comment by nfabacus** [comment]
Hi, @yannbf 
Wow, that is great, I did not know about the lowercase. Thank you! =)

To summarise:

- jest 27 does not seem to work.  When I clean installed jest 26, it worked with lower case.
  => For now, I will just use jest 26.
- imported story component has to start with lower case.
  => I wonder why the stories components are exported with lower case starts as the names of react components have to start with upper cases.
   For now, I just import it like: `import { defaultButton as DefaultButton } from './index.stories.mdx';`

@shilman and @yannbf  Thank you very much for your help.  Now, I can utilise the stories for my unit testing which allows me to write flexible/rich stories and unit tests that are consitent with the stories.

**Comment by joelstransky** [comment]
I was not able to get this to work when the <Story>'s were nested inside <Canvas>
