### ISSUE TITLE
Load storybook bundle with SystemJS

### ISSUE THREAD

**Issue by dvnrsn** [storybookjs/storybook#9979]
I realize this is a long shot, but 

I'm trying to load a number of modules with SystemJS. I'm doing this so that we can include features from other microservices in our storybook library.

What I've tried is populating `preview-head.html` with a script that obtains and adds an import map to the DOM. Then it fetches SystemJS and addons. 

When I add the `config.output.libraryTarget = 'system'` to storybook webpack, I see the `main.` loaded with preview `System.register...` before system.js in network.

![image](https://user-images.githubusercontent.com/9112811/75475864-caa39880-5956-11ea-9fd9-7964d0d5ccba.png)

I know SystemJS is loaded successfully in the iframe 

![image](https://user-images.githubusercontent.com/9112811/75475759-916b2880-5956-11ea-9d06-0e8471c8191b.png)

But I am thinking I need to adjust storybook's webpack to output a usable bundle name for systemJS.

**Comment by abhijit945** [comment]
Are there any updates on this? 
I am running into the same issue, I am wondering if the storybook sources need to be pulled in via `type="systemjs-module"` ?

**Comment by pavlovp** [comment]
In order to adjust storybook's webpack output to output usable bundle name for systemJS, you can additionally set in the webpack config: 
config.output.library = 'somename',

the Storybook bundle will start like this: "System.register("somename",[],(function(e)... "

But is it required to load external SystemJS modules to your Storybook build?

**Comment by gingerlee** [comment]
One solution here - hope this helps 💫

We were facing a similar issue, working in a microfrontend monorepo structure using [Single SPA](https://single-spa.js.org/), having issues loading components in Storybook that had other component imports from packaged libraries in the same repo. The solution that worked here was to add a [browser](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#browser) field in the `package.json` for each imported library/component that will point Storybook to the root component file for Storybook to find and load. 

For example, I was importing a cookie consent component to Storybook that was not rendering, the cookie consent had a button import that was its own packaged library. To get the cookie consent to load, I added this line in the button library `package.json`, (which has a root file called `mp-button.ts`):

`"browser": "./src/mp-button.ts",`

I hope this helps anyone in a similar situation. 

Shoutout to my awesome colleague [Joe](https://github.com/jsmapr1), for always making JS a little less painful.

**Comment by wbern** [comment]
I changed my storybook instance to systemjs and it was pretty painless.

Just switch output to "system" in webpack config, add an import map using a previewHead hook in main.js, and it is done.

Another important part is that each story needs to import from the module name, not by relative path.

The original posters issue sounds like the script tag for systemjs just wasn't high up enough in the previewHead html perhaps? All this works fine for me.

**Comment by sourceful-debarshi** [comment]
@wbern Could you post how the import map looks for you? I can load other Microfrontends, but story itself is not loading for me.
