### ISSUE TITLE
Replacing DocsPage doesn't work

### ISSUE THREAD

**Issue by thany** [storybookjs/storybook#9995]
**Describe the bug**
I'm trying to replace DocsPage. I just want to change some styling, and it appears to be possible by replacing DocsPage with another component. At least that's what I'm trying to do. It doesn't work. No error. No warning. Builds absolutely fine. Everything works. DocsPage just simply isn't getting replaced.

[It says right here](https://github.com/storybookjs/storybook/blob/8b11ec6eb9b710c5e7d896ce4da8074bd4af7f6f/addons/docs/docs/docspage.md#replacing-docspage) That I can add this to `preview.js`:
```javascript
addParameters({ docs: { page: null } });
```
Now I have a `config.jsx` so I can't have a `preview.js` so I'll have to put it there. Other parameters declared in `config.jsx` are picked up as expected. Even other docs parameters.

This works:
```javascript
addParameters({
  docs: {
    components: {
      Preview // Custom Preview component
    }
  },
});
```
So why can't I supply `null`, or indeed my custom DocsPage component, as described in the documentation?

**To Reproduce**
1. Follow the documentation to install addon-docs
2. Follow the documentation to use with typescript? Not sure if this is relevant?
3. Try the above.

**Expected behavior**
Even if I replace docs with a custom component that literally doesn't d o anyting other than log the props and return a fragment, that log isn't even printed out, which to me is proof that the `page` parameter isn't even so much as looked at (even though I can find loads of references in the source code). Example:
```javascript
const Foo = props => {
  console.log(props);

  return <>Yolo</>;
};

addParameters({ docs: { page: Foo } });
```
This should print out the props of a replaced DocsPage to the console. But no log entry ever appears. Not even an undefined value or whatever. Absolutely nothing. I'd expect quite the opposite.

**System:**
Results of `npx -p @storybook/cli@next sb info`:
```
  System:
    OS: Windows 10 10.0.18363
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
  Binaries:
    Node: 10.16.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
```
It might also help to know I'm on the latest stable version. That's Storybook 5.3.14 at the time of writing. Addon-docs as well.

**Comment by shilman** [comment]
Do you have a repro? Working for me in `official-storybook` and every other project I've tried.
