### ISSUE TITLE
Strange behavior when passing single files to -s

### ISSUE THREAD

**Issue by nategreen** [storybookjs/storybook#9998]
**Describe the bug**
When attempting to pass single files to the `-s` parameter of `start-storybook` or `build-storybook`, it didn't fail (with an error message), but:

- `start-storybook` started and built normally, but when visiting the local URL, a file called "download" was downloaded and the page wasn't shown.
- `build-storybook` didn't include the static assets listed but otherwise ran normally

**To Reproduce**
1. Run `start-storybook -s ./README.md` (or whatever other static file you'd want to include; mine was a stylesheet in `node_modules`)
2. Attempt to go to the Storybook server on `localhost`

**Expected behavior**
- Show an error in the terminal and fail to build/start, or
- Include the listed file, as if I were including a directory with only that file in it, or
- Load Storybook normally but show an error there

**System:**
```
Environment Info:

  System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  Binaries:
    Node: 12.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.21.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.12.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
```

**Comment by shilman** [comment]
@nategreen the argument to `-s` should be a directory filled with static files, not a single file

**Comment by nategreen** [comment]
Yep, I figured that out…I guess maybe it's not a bug per se, but I would've expected it to fail somehow, instead of building "successfully," since that's the case. The lack of errors made it kind of tricky to figure out what was wrong.

**Comment by shilman** [comment]
@nategreen any interest in contributing a small PR for this? would be a good improvement to DX
